### ISSUE TITLE
Nullability analysis when the checks are made through a function call

### ISSUE THREAD

**Issue by pebezo** [dotnet/roslyn#36990] opened 2019-07-04 15:00 UTC
**Version Used**: VS2019 16.1.5 + C# Tool 3.1.1-beta4

**Steps to Reproduce**:

```csharp
public class Something
{
    public void Do()
    {
        var foo1 = new Foo();

        if (foo1.Value is null) throw new Exception();
        
        string notNull1 = foo1.Value; // No warnings

        var foo2 = new Foo();

        Check(foo2);

        string notNull2 = foo2.Value; // CS8600 even though Check() made sure .Value is not null
    }

    public void Check(Foo foo)
    {
        if (foo.Value is null) throw new Exception();
    }

    public class Foo
    {
        public string? Value;
    }
}
```

1. I use the sample/repro above in a project that has the null analysis enabled and uses the latest C# version

**Expected Behavior**:

I'd expect the null-check being in-line (this works) or through a function call not to matter. This is a common pattern where the validation is handled by a separate function.

**Actual Behavior**:

Null checking works if done inline, but it does not when done through a function call.

**Comment by RikkiGibson** [comment] 2019-07-05 18:38
Today we have a `NotNullAttribute` which lets you express that an argument is not-null when the function returns. Among other things this lets users express the meaning of `ThrowIfNull(arg)`-style methods. But this won't let you specify the null state of a field/property within the argument such as `Foo.Value`. This issue raises the question of whether/how that should be possible.

See the relevant LDM notes here: https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-05-15.md

/cc @jcouv.

**Comment by RikkiGibson** [comment] 2019-07-05 18:39
Note that the nullability flow analysis doesn't analyze between method calls by design. So probably the only way to make this scenario work is through some kind of annotation on the method signature that does the validation.

**Comment by pebezo** [comment] 2019-07-05 18:43
"Note that the nullability flow analysis doesn't analyze between method calls by design." -- is this a "v1" limitation (open for improvement later) or a permanent one? I can see the complexity of doing this, but at the same time it's very limiting. Maybe do it for a depth of one, but not more? Or for simple methods that only do validation?

**Comment by twest820** [comment] 2020-11-11 16:10
Just hit a variation of this updating some unit tests. Since `Assert.IsNotNull()` is void and  `Assert.IsTrue()` takes a `bool` I'm not seeing a way the MS Test team could make a fix to the example below with the currently available nullability attributes. Similarly, I'm not seeing a way I could wrap `Assert` to avoid the CS8602. So it'd be nice if `[NotNull]` or an equivalent was available as a post-condition in this case. The workaround's trivial but ugly and suppressing the issue's fragile.

Am I missing anything? From Rikki's remarks it looks like there was intent for `[NotNull]` to support `ThrowIfNull(arg)` at one point, consistent with the current [documentation for `NotNullAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=net-5.0), but the linked meeting minutes restrict it to `ref` and `out` arguments. I don't see an issue tracking adding `ThrowIfNull(arg)` support and the attribute documentation might be contradicted by [other nullability documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis), though the wording is a bit cryptic.

**Version Used**: .NET 5.0, C# 9, VS 16.8.0

**Steps to Reproduce**:
```C#
        using Microsoft.VisualStudio.TestTools.UnitTesting;

        internal class AssertNullability
        {
            public static void IsNotNull([NotNull] object? value)
            {
                Assert.IsNotNull(value); // or
                if (value == null)
                {
                    throw new AssertFailedException();
                }
            }
        }

        internal class SomeClass
        {
            public object? SomeProperty { get; private set; }
        }

        private void Test(SomeClass foo)
        {
            object? bar = foo.SomeProperty;
            Assert.IsNotNull(bar); // or
            Assert.IsTrue(bar != null); // or
            AssertNullability.IsNotNull(bar);
            string baz = bar.ToString();
            //              ^ CS8602
            // workaround: bar!.ToString()
        }
```

**Expected Behavior**: no CS8602

**Actual Behavior**: CS8602

**Comment by RikkiGibson** [comment] 2020-11-11 18:51
The code sample you shared shows a CS8600 warning, not CS8602, when I run it in [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFBUACADITQIwB0AIgJYQDmaA9rA4BjKCwDCfACZwAgqSwBPKBygBuWgwCywhAL4AzGCwBqKjBCwBlGBkkc+LACpxYjvnyyiAqmg4xngmjc6tSUAPRhhLAYwMAcQYR8GDCEMAAWKoSkYC4ADhBCRMpohYR+AORQWXwpEABuEBy4+ETxhJZpEAi5ADJ4VNl5BUTaQrpQBkamUOZWNnYOAf7uniw+fkvx3FQA3lSEB4wAzIwATIQyUFCIMPuHe5SHT8eMTABsjAAshACSUAByNX+2CwAAo+MAAFZwIQwAD8iShAEpCDtCABfO7PF7MD40b5/RwIDBwUHAFaEYAotGYx7YwhYjGMxk0E40c6Xa4IGAAMUaBEkAFEAB6FXIwexoQggV4sEViiV8KU0qi02hs87MADsu0Z8XgCHkZwuVxuwJweCafgUjIe9Jx7y+vwBQJBoIA2oCYOasABdRHQ2EIhpYElIxlPO32w6cm4sP5en2gkNh1SECKJBAR+kcfSEZMWEmEAC8xayIPDdOjqOz1fSugA7lk4E3Y9y+U04ELRXBxZLQUiQtWDrT7aPDmqq2U0Aajez2nwcmJcFdbbWXhDA/CFzkAAq6XI3BSowjcOAwNO5BAcBrwKLntPjkdURlXm8QO/4whLUGWRdwZdoCqfR3ErSN103GFt2ALoS0IECHD/PcDyPId6TbIwE1dHAyS6Qd00iPgsynJ4MPjKAiRJXCEEIABCMtMBwfCMyI9cMJ9S0sGtcjEzdGCEEHddmAYGCAC84P4pw+Gsa8ggHNDsQzYcDgAPUIMRLAADjeOhTnXDMGyIgBrLokjQSQZX42ipJkrYB0ZWlaSAA===). Behavior is the same when I try it in VS 16.8 Preview 6 (haven't gotten around to installing VS 16.8 yet, but I don't think we changed this behavior between the two releases.)

This particular warning is because `object.ToString()` returns `string?`. Thus the expression `bar.ToString()` produces a CS8600 warning when assigning it to a local of type `string`. The motivation for this is described in the linked section of this document: https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/api-guidelines/nullability.md#virtualabstract-methods-and-interfaces

**Comment by twest820** [comment] 2020-11-11 21:37
I guess that confirms `[NotNull]` should obviate an 8602 in this case. I had a stable 8602 persisting through build with the above snippet. However, I'd written it inline in one of the test project's existing .cs files and didn't save it after copy/paste to this issue. If I paste it back I get the 8600 as well rather than the 8602. My previous post came after I'd been toggling various project-level nullable settings in the solution back and forth as well as changing files between unmarked, `#nullable enable`, and `#nullable disable`. Not long after that VS had an internal exception and I restarted it.

So I suspect the most plausible explanation is the 8602 was a stuck warning and therefore spurious. That happens every so often in VS 16.5ish+ builds as they appear to have a race condition where Roslyn background tasks fail to fully clear previous warnings when updating. I wasn't checking against the actual text from the build on the output tab.

Sorry, my bad. Thanks for the reply.

**Comment by jaredpar** [comment] 2021-02-09 22:46
Closing as this behavior is "By Design".

Some progress was made here when we implemented the `[NotNull] / [NotNullWhen]` attributes. However LDM decided to limit the impact of that attribute to members declared in the same type where the annotation is present. Future changes here would need to start with a proposal on csharplang.

**Closed by jaredpar** 2021-02-09 22:46 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Nullable Reference Types
