### ISSUE TITLE
Generate HashCode Codefix introduces an error for an abstract base class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46213] opened 2020-07-22 16:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1118234/generate-hashcode-codefix-introduces-an-error-for.html)._

---
If I use the code fix "Generate GetHashCode", the implementation of the base class is invoked, even if this method is declared abstract.

```
using System;

namespace ConsoleApp1
{

public abstract class A : IEquatable<A>
    {
        public string S { get; set; }
        public virtual bool Equals(A? other) => true;
        public override bool Equals(object obj) => Equals(obj as A);
        public abstract override int GetHashCode();
    }

public abstract class B : A { public string Z { get; set; } }

public class C : B
    {
        public string Q { get; set; }
        public override bool Equals(A other)
            => base. Equals(other);

}

}
```

If I use _Generate GetHashCode_ in class _C_ the result will be
```
public override int GetHashCode() => HashCode.Combine(base. GetHashCode(), S, Z, Q);
```

This introduces a syntax error (CS9205) becaue base. GetHashCode is abstract.

---
#### Feedback Bot on 7/20/2020, 03:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-07-22 16:44
Duplicate of #43290

**Closed by sharwell** 2020-07-22 16:44 UTC
