### ISSUE TITLE
Prefer Using User's Namespaces Over System's in Visual Studio Quick Actions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45630] opened 2020-07-02 23:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1090752/prefer-using-users-namespaces-over-systems-in-visu.html)._

---
I have defined a type named `Component`, but there is already a type named that in `System.ComponentModel` namespace.

As a result when quick actions suggest to import a namespace for this type there are two choices.

It seems like system's namespaces are given a priority as my namespace always comes in second in the suggestions. This leads to always having to press `arrow down` when a list appears. 

I think user defined namespaces should be first in the list, as you are more likely to want to use your defined type in the same project.

---
#### Visual Studio Feedback System on 6/27/2020, 11:51 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by vatsalyaagrawal** [comment] 2020-07-07 18:51
Duplicate of #38453

**Closed by vatsalyaagrawal** 2020-07-07 18:51 UTC
Labels: Area-IDE
