### ISSUE TITLE
[Test Failure] xUnit returned error code without errors in prtest/win/dbg/unit64 on PR #9685

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9690] opened 2016-03-11 17:46 UTC
PR: [#9685](https://github.com/dotnet/roslyn/pull/9685) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5098/

**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Comment by davkean** [comment] 2016-03-11 17:49
Dupe of https://github.com/dotnet/roslyn/issues/9490.

**Closed by davkean** 2016-03-11 17:49 UTC
Labels: Bug
