### ISSUE TITLE
Tooltip on `throw` expression keyword shows targeted type instead of exception type

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#66126] opened 2022-12-25 23:06 UTC
**Version Used**:
- **Visual Studio** Version `17.5.0 Preview 2.0`
- **Roslyn** Version `4.5.0-2.22580.13+ea0b6351c129c7decd9bf76f4388239509e28e0d`

**Steps to Reproduce**:

One quick example involves a switch expression, or a ternary expression.
1. Write a switch expression using target typing (either on the target variable, or within the return statement of a method)
2. On the one arm, use any throw expression and throw any exception, or `null` (repro is same)
3. Hover over the `throw` keyword

[SharpLab repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCecAmIA1AD4ACATAIwCwAUPbAgATLMC8zAojMlOgHsYYVDAQA6AHKoA7gBlYqZgGcZUBAGMAFvQDe9ZoeYwBLAEQAddBZhmOAPmYItgmcYCuAG09x6AXwBuekYxZiwOJ3R3JQB+JxcBNxgvT2YQeNcPbwCgA==)

**Expected Behavior**:
Tooltip shows the information of the type that is being thrown, or `Exception` if it's `null`, like it already does when hovering over the `null` keyword.

**Actual Behavior**:
The type that is being targeted, which is basically the type of the expression even if it's a `throw` expression.

**Comment by CyrusNajmabadi** [comment] 2022-12-26 02:08
I believe from the languages perspective, that is the type of the throw expression. :-)

**Comment by Rekkonnect** [comment] 2022-12-26 07:18
That is correct, my issue is that I'd expect some information for the thrown exception instead of the type that is being targeted. It feels like it provides no value to the end user.

**Comment by CyrusNajmabadi** [comment] 2024-11-22 20:29
Closing out as not  planned.  This is working as intended wiht how the language works.

**Closed by CyrusNajmabadi** 2024-11-22 20:29 UTC
Labels: Question, Area-IDE
