### ISSUE TITLE
Error in Microsoft.CodeAnalysis.CSharp in VS2017.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#29754] opened 2018-09-10 19:39 UTC
**Version Used**: Unknown, VS2017 15.9 Preview 1.

**Steps to Reproduce**:

1. I edited a file to add documentations from StyleCop warnings of public methods / properties.
2. This error shows up from ``Microsoft.CodeAnalysis.CSharp``:

```cs
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBase(BaseExpressionSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpressionHelper(Binder binder,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpression(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,Binder& binder,ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position,SyntaxNode node,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.ReplaceDocCommentTextWithTag.AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider.TryRegisterSeeCrefTagIfSymbol(CodeRefactoringContext context,SemanticModel semanticModel,SyntaxToken token,TextSpan replacementSpan,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ReplaceDocCommentTextWithTag.AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Expected Behavior**:

No error from this disabling something in VS.

**Actual Behavior**:

This error disabling something in VS.

**Comment by jaredpar** [comment] 2018-09-11 17:33
Thanks for reporting this. Do you happen to know what code is triggering this? That method doesn't have an obvious place where a `NullReferenceException` could occur.

**Comment by gafter** [comment] 2018-12-12 00:40
Because this is not actionable without more details, closing.  However, if you manage to come up with details that could help us diagnose what's going on, please feel free to reopen.

**Comment by csi-tsmith** [comment] 2019-08-22 13:24
I'm able to repro this consistently by putting "base" in XML doc comments on a ctor and moving the cursor to it.

**Comment by gafter** [comment] 2019-08-22 19:27
@csi-tsmith Can you please share exactly what such an XML doc comment would look like?

**Comment by csi-tsmith** [comment] 2019-08-22 21:37
public class Foo
    {
        /// <summary>
        /// base
        /// </summary>
        public Foo()
        {

        }
    }

**Comment by svick** [comment] 2019-08-29 08:31
I couldn't reproduce this, though I did find some odd behavior when it comes to `base` in XML comments, which I reported as https://github.com/dotnet/roslyn/issues/38370.

**Comment by jaredpar** [comment] 2019-09-09 22:23
@cston lets see if this reproduces on the latest bits. If not then lets close out until we have a repro on newer bits.

**Comment by cston** [comment] 2019-09-14 18:25
Thanks for reporting. This is a duplicate of https://github.com/dotnet/roslyn/issues/29933, fixed in https://github.com/dotnet/roslyn/pull/36081.

**Closed by cston** 2019-09-14 18:25 UTC
Labels: Area-Compilers, Bug, Investigation Required
