### ISSUE TITLE
Task List doesn't show any tokens except built in TODO

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44736] opened 2020-06-01 00:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1053092/task-list-doesnt-show-any-tokens-except-built-in-t.html)._

---
[regression] [worked-in:16.5]
In previous version it also worked badly, because the task list didn't refresh, the only way I found to refresh the list was to delete one slash from the comment, wait until the item disappers from the list, then add the slash back.

In current version the list updates on file saved, but only TODO token.

I tried to find my FIXME comments. There are not on the Task List. I tried to see the options if the tokens are defined.
They are defined. Marked as high priority.

I deleted the tokens and then added them again.
It didn't help.

I restarted VS, it didn't help.

It seems like the feature of using custom tokens with priorities is totally broken in this version.

BTW, I work on Blazor project. I haven't tested it on other types of projects.
My comments however are in regular .cs files.

Fragment like this
```
// FIXME: A serious bug.
// TODO: A new feature.
```
Gives only TODO: A new feature on the Task List, despite the FIXME token is set, and set to high priority.

---
#### Visual Studio Feedback System on 5/28/2020, 01:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### jeff.skaistis on 5/28/2020, 07:41 AM: 

Having the same issue in both 16.6 and 16.7 preview. My custom tokens are not displaying.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2020-06-01 06:25
Dupe of https://github.com/dotnet/roslyn/issues/43788

**Closed by CyrusNajmabadi** 2020-06-01 06:25 UTC
