### ISSUE TITLE
Formatting, New Lines not works for "else"

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#7421] opened 2015-12-11 12:27 UTC
Bug in Update 1. Before all was fine.

I have all check boxes checked under Options/Text Editor/C#/Formatting/New Lines

But when I try a reformat next code:
```cs
if(1 > 2) {
} else {
}
```
it formatted as:
```cs
if(1 > 2)
{
}
else { // <-- this should be on the new line
}
```

**Comment by Pilchie** [comment] 2015-12-11 16:22
This is a duplicate of #6628

**Closed** 2015-12-11 17:22 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
