### ISSUE TITLE
Go To Definition for typeof(Program) highlights the first keyword/identifier in Program.cs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56848] opened 2021-09-29 16:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-To-Definition-for-typeofProgram-hig/1541614)._

---
Create a new ASP.NET Core 6.0 app, which has a Program.cs that uses top-level statements. In that file I added the code `var q = typeof(Program);`, which is perfectly valid. I then put the caret on the `Program` identifier and press F12, which navigates and highlights to the first keyword/identifier in the file. At best it should navigate to the first line of the document. Highlighting a seemingly arbitrary piece of text in the file is quite odd.

---
#### Feedback Bot on 9/29/2021, 03:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2021-09-29 17:16
I genuinely don't see this as a bad thing :)

**Comment by Eilon** [comment] 2021-09-29 17:18
It's not an _awful_ thing, but it's very weird that it highlights a completely arbitrary token in the document. It's not even the _first_ token. For example, it skips past comments and goes to the first non-comment token (it seems).

**Comment by CyrusNajmabadi** [comment] 2021-09-29 17:27
taht makes sense to me as well.  Note: in roslyn 'comments' are not 'tokens'.  They are trivia (i.e. things that have no impact on the final emitted code).  It makes sense to me that hte location of hte Program type would be the start of the first real token in the file...  It doesn't seem arbitrary.  It seems very by-design that that is it's location.

**Comment by Eilon** [comment] 2021-09-29 17:34
I think from the user perspective having <kbd>F12</kbd> do that is bizarre. People don't understand the concept of trivia and syntax tokens and the differences between them. Please note that it actually _highlights_ that first token. If it merely places the caret there without highlighting. And now that I try another scenario, it's even weirder than that. It skips past comments and past `using`'s:

![image](https://user-images.githubusercontent.com/202643/135319736-a9b1cd48-c8c6-4f4f-880c-b43384245bc4.png)

From the user perspective I am trying to navigate to the _definition of an identifier_ and the behavior of VS is absolutely not that.

**Comment by CyrusNajmabadi** [comment] 2021-09-29 17:42
> And now that I try another scenario, it's even weirder than that. It skips past comments

Again, comments are never considered the locaiton for any symbolic definition.

> and past using's:

This also makes sense to me.  The 'Program' type is created from teh top-level-statements present in the file.  It takes you to the start of the very first statement.  This genuinely makes sense to me.  

> I am trying to navigate to the definition of an identifier

The definition of 'Program' is the top level statements.  It's what caused the 'Program' type and the special 'Main' method to be created.  

> People don't understand the concept of trivia and syntax tokens and the differences between them

I think they do.  Whenever you f12 on anything else, we always take you to a token, we've never taken you to trivia... why would we?  What would a comment be the desirable location to ask where a symbol's definition is?

**Comment by Eilon** [comment] 2021-09-29 17:49
> The definition of 'Program' is the top level statements. It's what caused the 'Program' type and the special 'Main' method to be created.

I agree with this. But it doesn't make sense to _highlight_ and _select_ the `var` keyword. That is not itself the definition of `typeof(Program)`. Of course, we both know that the `Program` symbol has no source-based definition in the program, but by that logic, _nothing_ should be selected. Moving the _caret_ to that location would be perfectly reasonable, but highlighting an arbitrary symbol does not make sense.

I'm not saying this is a high priority bug and I can sympathize with what logic and compromises must have gone into making this work at all. But that doesn't change that this behavior is bizarre.

**Comment by CyrusNajmabadi** [comment] 2021-09-29 18:28
> Of course, we both know that the Program symbol has no source-based definition in the program

I disagree.  The top level statements are the source-definition of the Program type.

> Moving the caret to that location would be perfectly reasonable, but highlighting an arbitrary symbol does not make sense.

I would be potentially ok with that.  Though it seems very minor.  Selecting or not-selecting the first token seems about equal.  If it wasn't selected, i would find it odd that you couldn't see anything indicating where the location was.

> But that doesn't change that this behavior is bizarre.

Enh.  Seems reasonable to me.

**Comment by nkarl7** [comment] 2021-10-03 18:19
> I disagree. The top level statements are the source-definition of the Program type.

This makes a lot of sense to me.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:30
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-22 18:30 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, Developer Community
