### ISSUE TITLE
Targeting netstandard1.3 with multiple imports breaks portable project flavor

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#12461] opened 2016-07-12 21:07 UTC
**Version Used**: Visual Studio 2015 Update 3 Microupdate 3.1

**Steps to Reproduce**:

1. Open Roslyn.sln at 255596ba195819fa2668b9a2c709a4105e2ac762
2. Look at the error list.

**Expected Behavior**: No warnings are in the error list.

**Actual Behavior**: There are warnings about incompatible PCL projects. If you look at 9df214f1507154b3486fd5e9f0366d27535cad6d you can see that removing imports that are lists made some of them go away.

**Comment by Pilchie** [comment] 2016-07-25 16:28
Dupe of #12452.

**Closed by Pilchie** 2016-07-25 16:28 UTC
Labels: Area-IDE
