### ISSUE TITLE
Unnecessary qualified type argument name suggested when a field has the same name

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#10662] opened 2016-04-18 19:48 UTC
Extremely minor bug.

---

**Version Used**: VS 2015 Update 2

**Steps to Reproduce**:

1. `using System;`
2. In a class, declare a field `int Random`. (the type doesn't matter, only the name)
3. In the same class, type `Action<Random> a = new`, which prompts IntelliSense.

**Expected Behavior**: IntelliSense should recommend `Action<Random>()`.

**Actual Behavior**: IntelliSense recommends `Action<System.Random>()`.

**Comment by Pilchie** [comment] 2016-04-18 19:51
Dupe of https://github.com/dotnet/roslyn/issues/2644

**Closed by Pilchie** 2016-04-18 19:51 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
