### ISSUE TITLE
VS2015 auto-prop with only a getter compiles for project targeting .net 4.5

### ISSUE THREAD

**Issue by ckasabula** [dotnet/roslyn#6251] opened 2015-10-22 21:26 UTC
void Main()
{
    var x= new Foo("cheese");
}

public class Foo {
    public Foo(string name) {
        Name = name;
    }
    public string Name {get;}
}

Project targets .net 4.5
Builds fine in VS2015
Build error in VS2013
Foo.Name.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.

c#6 property initializer feature leak??

Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079
Installed Version: Professional
Visual C# 2015   00322-50350-07590-AA793
Microsoft Visual C# 2015

**Comment by Vannevelj** [comment] 2015-10-22 21:56
In C# 5 terms you created a read-only property and tried to assign it a value in the constructor. C# 5 didn't allow this. C# 6, however, expanded on that and allows you to treat it almost as if it had the `readonly` keyword: you can also assign it a value in the constructor.

.NET is just the framework with some classes and doesn't dictate the difference between C# 5 and C# 6-- the compiler does. The compiler is bundled with Visual Studio and the latest, C# 6's compiler, came with VS2015.

**Comment by Joe4evr** [comment] 2015-10-22 23:43
The VS2013 compiler only knows up to C# 5. You can't use C# 6 features with only a C# 5 compiler.

**Comment by davkean** [comment] 2015-10-22 23:52
Yes, the behavior you are seeing is by design. C# features are tied to Visual Studio versions, not .NET Framework versions. 

In saying that, there are certain features (such as String interpolation) that only work when associated new framework types are available, which usually implies a new framework version, but that's not typically required.

You can restrict yourself to C# 5.0 features via:

1) Right-click on the project and choose __Properties__
2) Choose the __Build__ tab -> __Advanced__
3) Under __Language Version__, choose _C# 5.0_.

**Closed by davkean** 2015-10-22 23:52 UTC
