### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.BoundSequencePointExpression has OperationKind.None and implement only IOperation

### ISSUE THREAD

**Issue by isanych** [dotnet/roslyn#13784] opened 2016-09-14 13:55 UTC
Version is 2.0.0-beta3 (in master class interfaces and OperationKind are the same). 

I was hoping to use only operations for method's body analysis but there is no usable operation for catch filter clause and I have to use syntax here:

``` c#
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Semantics;
using System;
using System.Linq;

internal static class Program
{
    private static void Main()
    {
        var tree = CSharpSyntaxTree.ParseText(@"
class c
{
    static void Main()
    {
        try { }
        catch (System.Exception e) when (e.Message != "") { }
    }
}
");
        var mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
        var compilation = CSharpCompilation.Create(null, new[] { tree }, new[] { mscorlib });
        var model = compilation.GetSemanticModel(tree);
        var node = tree.GetRoot().DescendantNodes().OfType<TryStatementSyntax>().First();
        var @try = (ITryStatement)model.GetOperation(node);
        var @catch = @try.Catches.First();
        Console.WriteLine(@catch.Filter.Kind); // Kind is None, could not use operation here, only could use syntax
    }
}
```

**Comment by bkoelman** [comment] 2017-01-06 00:14
Related to #11741.

**Comment by jinujoseph** [comment] 2017-07-03 23:50
dupe of #11741, closing this one

**Closed by jinujoseph** 2017-07-03 23:50 UTC
Labels: Area-Analyzers, Concept-API, Feature Request, New Feature - IOperation
