### ISSUE TITLE
IDE0079 false positive on roslyn-analyzers

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#50194] opened 2020-12-31 11:18 UTC
**Version Used**: 16.9.0 Preview 2

**Steps to Reproduce**: Run "Code analysis on solution" on `roslyn-analyzers`, you will end up with more than 70 diagnostics and most of them are false-positive. Removing the pragma results in the suppressed diagnostic to be raised.

**Expected Behavior**: Diagnostic raised only when it's valid/safe to remove pragma.

**Actual Behavior**: False-positives.

For some actual example, `IDE0079` is raised here https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/Compiler/PooledObjects/ArrayBuilder.cs#L10 while removing this pragma results in the `CA1000` to be raised.

Might relate to #49925

**Comment by CyrusNajmabadi** [comment] 2020-12-31 17:32
Tagging @mavasani

**Comment by mavasani** [comment] 2020-12-31 18:44
This is a known limitation for (all) analyzers on linked/shared project files when the analyzer fires is some shared contexts but not all.

**Comment by sharwell** [comment] 2020-12-31 18:46
Duplicate of #49925

**Closed by sharwell** 2020-12-31 18:46 UTC
Labels: Area-Analyzers, untriaged
