### ISSUE TITLE
Proposal: Add the null-aware assignment operator

### ISSUE THREAD

**Issue by jolleekin** [dotnet/roslyn#10249] opened 2016-04-01 16:13 UTC
It will be very helpful if C# can support the null-aware assignment operator.

``` c#
// If [x] is null, assign [y] to [x].
x ??= y;
```

This operator is inspired by [Dart](http://news.dartlang.org/2015/08/dart-112-released-with-null-aware.html)

**Comment by HaloFour** [comment] 2016-04-01 17:55
Dupe of #9529, #8894, #3366, #205

**Comment by gafter** [comment] 2017-03-24 20:27
Discussion moved to https://github.com/dotnet/csharplang/issues/34.

**Closed by gafter** 2017-03-24 20:27 UTC
Labels: Area-Language Design, Discussion
