### ISSUE TITLE
Moving a nested type to a separate file moves trailing preprocessor, creating CS1028 error

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#43600] opened 2020-04-23 15:27 UTC
**Version Used**: VS 16.5.4, 16.6-p3

Invoke 'Move type to C.Nested.cs':

```cs
class C
{
    class [||]Nested { }

    #region

    void Member() { }

    #endregion
}
```

Created file:

```cs
partial class C
{
    class Nested { }

    /* ❌ CS1028 Unexpected preprocessor directive
    ↓↓↓↓↓↓↓↓↓↓ */
    #endregion
}

```

**Comment by jcouv** [comment] 2020-04-27 18:16
FYI @ryzngard

**Comment by ryzngard** [comment] 2020-04-27 19:06
Looks like a dupe of #39640

**Closed** 2020-05-21 06:14 UTC
Labels: Area-IDE, Resolution-Duplicate
