### ISSUE TITLE
Decompilation is producing invalid C#

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25310] opened 2018-03-07 09:58 UTC
1. Create a new Console Application
2. Install **xUnit 2.1.0** NuGet package
3. Turn on decompilation
4. Right-click on `Assert.Single` and choose **Go to Definition**

``` C#
using System;
using Xunit;

namespace ConsoleApp191
{
    class Program
    {
        static void Main(string[] args)
        {
            Assert.Single("foo", "c");
        }
    }
}

```

5. Click member down drop

**Expected:** Every single member of Assert to be listed (> 100)
**Actual:** Only the following are listed:

![image](https://user-images.githubusercontent.com/1103906/37085870-4585b6e6-224a-11e8-9f44-12a763a42711.png)

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:04
Is this specific to deconstruction?  If you take the generated source and place it in a new file, do you see the same issue?

**Comment by davkean** [comment] 2018-03-07 10:07
It looks like decompiling/deconstruction is producing invalid C#, which causes the issue: https://gist.github.com/davkean/d07e62021593f3328f7583a0dce21881.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:08
This is likely due to the decompiled code being unparseable.  i.e. it contains gibberish in it like:

```c#
                catch (Exception item)
                {
                    ((Stack)(?)val).Push((!0)new Tuple<int, object, Exception>(i, (object)array[i], item));
```

**Comment by davkean** [comment] 2018-03-07 10:09
And braces in the wrong spot:

https://gist.github.com/davkean/d07e62021593f3328f7583a0dce21881#file-assert-cs-L201

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:09
This looks like a dupe/fallout of https://github.com/dotnet/roslyn/issues/25246

**Comment by davkean** [comment] 2018-03-07 10:11
It one thing not be able to produce a body of a method - another to have the braces in the wrong sport.

**Comment by davkean** [comment] 2018-03-07 10:17
Oh my mistake - that's just formatting. I thought it was an additional brace just hanging out - but it's just the end of the `if` block.

It might be a dupe of that bug - I really like to make sure we're aware of the bugs in the generation, ILSpy seems to be miles behind where Reflector was ~5 to 10 years old.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:24
Should these issues go over to ILSpy?  It looks like all we're doing is:

```c#
            var decompiler = new CSharpDecompiler(ad.MainModule, new DecompilerSettings());
            var fullTypeName = new FullTypeName(fullName);

            // Try to decompile; if an exception is thrown the caller will handle it
            var text = decompiler.DecompileTypeAsString(fullTypeName);
```

So the ball is effectively in their court as to the quality of the decompiled code.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:27
I believe @sharwell did the decompilation integration.  @sharwell Maybe we should reach out to the ilspy guys so they know we're using this library in VS now.  We can then try to coordinate issues between the teams to help getting things addressed in a timely manner.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:27
Bed time for me.  Good luck!

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:32
> where Reflector was

Indeed.  Reflector produces this code for that method:

```c#
public static void All<T>(IEnumerable<T> collection, Action<T> action)
{
    GuardArgumentNotNull("collection", collection);
    GuardArgumentNotNull("action", action);
    Stack<Tuple<int, object, Exception>> stack = new Stack<Tuple<int, object, Exception>>();
    T[] localArray = Enumerable.ToArray<T>(collection);
    for (int i = 0; i < localArray.Length; i++)
    {
        try
        {
            action.Invoke(localArray[i]);
        }
        catch (Exception exception)
        {
            stack.Push(new Tuple<int, object, Exception>(i, localArray[i], exception));
        }
    }
    if (stack.get_Count() > 0)
    {
        throw new AllException(localArray.Length, stack.ToArray());
    }
}
```

That looks entirely correct, without any issues around ```//IL_0016: Unknown result type (might be due to invalid IL)``` or bogus casts like ```(!0)``` or ```(?)```.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:37
When i decompiled this using ilspy, it also automatically pulled in:

![image](https://user-images.githubusercontent.com/4564579/37087816-3d7929d2-21b0-11e8-922c-d583dec03db8.png)

Maybe we're not setting things up so that assembly resolution works properly?  That might then explain why we see things like ```//IL_0016: Unknown result type (might be due to invalid IL)```

**Comment by CyrusNajmabadi** [comment] 2018-03-07 10:40
Note: IL_0016 is: ```IL_0016: newobj instance void class [System.Collections]System.Collections.Generic.Stack`1<class [System.Runtime]System.Tuple`3<int32, object, class [System.Runtime]System.Exception>>::.ctor()```

So it looks like it's having trouble understanding these types.  And once it doesn't understand some types, all sorts of issues follow.  For example, the ```(!0)``` we're seeing is due to this instruction:

```
IL_004c: callvirt instance void class [System.Collections]System.Collections.Generic.Stack`1<
    class [System.Runtime]System.Tuple`3<int32, object, class [System.Runtime]System.Exception>>::Push(!0)
```

**Comment by sharwell** [comment] 2018-03-07 11:46
Duplicate of #25246

**Closed** 2018-03-07 11:46 UTC
