### ISSUE TITLE
The error message you get when an analyzer has a dependency on Roslyn higher than your compiler's version should be more specific

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30836] opened 2018-10-30 06:51 UTC
If you install an analyzer that has a dependency on Roslyn that is higher than your compiler, you get the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Roslyn.Diagnostics.CSharp.Analyzers.CSharpSymbolDeclaredEventAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\roslyn.diagnostics.analyzers\2.9.0-beta1-63118-01\analyzers\dotnet\cs\Roslyn.Diagnostics.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed\CSC	1	Active

```

I have 2680 warnings like above in my solution for every single analyzer for every project, it would be much friendly to only show this for a single analyzer assembly and say something like "This analyzer was build for a higher version of compiler than you are using" or words to that effect. Even better if you could tell me what version it was built for, because there's not a clear mapping between 2.9.0.0 and the version of the compiler/Visual Studio I need.

**Comment by mavasani** [comment] 2018-11-06 18:57
Dupe of https://github.com/dotnet/roslyn/issues/20316

**Closed by mavasani** 2018-11-06 18:57 UTC
Labels: Area-Analyzers, Concept-Diagnostic Clarity, Resolution-Duplicate
