### ISSUE TITLE
Find all references on throw Exception expression does not list catch usages 

### ISSUE THREAD

**Issue by davidroth** [dotnet/roslyn#21093] opened 2017-07-25 09:08 UTC
**Version Used**: 
VS 2017.2

**Steps to Reproduce**:

1. Find a throw expression (throw new MyException()) in yourcode
2.  Context-Menu, Right Click, Find all references (SHIFT+F12)

**Expected Behavior**:
References dock window lists all usages of this exception, also all catch statement.

**Actual Behavior**:
Catch statement not listed in window:

![image](https://user-images.githubusercontent.com/338856/28564492-71c3101e-7129-11e7-8fc7-c8e649142ebe.png)

If you call SHIFT+F12 on the class declaration, the catch statement is listed in the references window:

![image](https://user-images.githubusercontent.com/338856/28564531-92e1a5c6-7129-11e7-9ce2-558f4c58ebf5.png)

**Comment by Pilchie** [comment] 2017-07-25 15:56
This is a duplicate of #3225.  The issue is that if you FAR for a constructor, we show you only the references to the constructor.

**Closed** 2017-07-25 21:54 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
