### ISSUE TITLE
Separate import directive groups only works when already sorted correctly

### ISSUE THREAD

**Issue by ousnius** [dotnet/roslyn#47910] opened 2020-09-21 20:45 UTC
Separating import directive groups (using groups) with the .editorconfig and GUI option ``dotnet_separate_import_directive_groups`` stops working correctly when the existing imports/groups are not already sorted alphabetically (System first, alphabetically after).

Instead, any new imports will inserted at the end.

**Example:**
```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

using Syslog.Common;

using NLua;
```

Adding a new import ``using Syslog.Common.DB``, it will be placed after NLua instead of after ``using Syslog.Common``.

Consider #44052 so that any changes or ideas don't clash.

**Comment by CyrusNajmabadi** [comment] 2020-09-21 22:56
yeah, we basically don't touch things if your code doesn't match the current settings.  The thinking being "We don't understand what they're doing, so we won't mess with it".

That said, when adding imports, if we see that it is grouped (even in a way that doesn't match the settings we have), we could attempt to add into the appropriate group.

**Comment by CyrusNajmabadi** [comment] 2022-11-02 19:44
Closing out as working as intended

**Closed by CyrusNajmabadi** 2022-11-02 19:44 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement
