### ISSUE TITLE
Can't fix all naming violations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15754] opened 2016-12-08 07:36 UTC
Unlike a lot of our code fixes, I can't fix all naming violations:

![image](https://cloud.githubusercontent.com/assets/1103906/21001563/31acb588-bd75-11e6-9268-383edca7d9b7.png)

Please allow it. :)

**Comment by Pilchie** [comment] 2016-12-12 21:40
Dupe of https://github.com/dotnet/roslyn/issues/14983.

**Closed by Pilchie** 2016-12-12 21:40 UTC
Labels: Area-IDE, Feature Request
