### ISSUE TITLE
using namespace invalid

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#37423] opened 2019-07-23 06:22 UTC
**Visual Studio Version**:16.1.6

**Summary**:

The reference namespace is invalid and will be cleaned up by the editor, which will cause the compilation to fail.

**Steps to Reproduce**:

1. 

```csharp
using System;
using System.Data;
using System.Drawing;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
#if DEBUG
            Console.WriteLine(CommandType.Text);
#else
            Console.WriteLine(Color.Red);
#endif
        }
    }
}

```
2. Remove And Sort Usings

3. Switch to Release mode

4.rebuild

**Expected Behavior**:

build success

**Actual Behavior**:

build fail

**User Impact**:

**Comment by drewnoakes** [comment] 2019-07-23 07:00
@Varorbc I've transferred this to Roslyn as this isn't a project system feature.

**Comment by Varorbc** [comment] 2019-07-23 07:05
@drewnoakes similar to this [issue](https://github.com/dotnet/project-system/issues/2733 ), shouldn't it belong to the project system?

**Comment by CyrusNajmabadi** [comment] 2019-07-23 09:14
This is by design.  If you have usings you need for certain configurations, place them in their own `#if` blocks as well.  i.e.

```c#
using System;
using System.Data;
#if !DEBUG
using System.Drawing;
#endif
```

Now they won't get removed as they won't be in your debug config (where they aren't needed), but wil be in your release config where they are.

**Comment by drewnoakes** [comment] 2019-07-23 09:22
> removed by the editor

Actually it's removed by a codefix belonging to Roslyn.

> similar to this issue, shouldn't it belong to the project system?

In that issue, the change in configuration was not being propagated to the editor component.

In this case you're seeing the results of code analysis performed with full knowledge of the active configuration.

**Comment by jinujoseph** [comment] 2019-07-23 17:35
As explained by @CyrusNajmabadi this is currently by design. 
you can wrap using with #if block to avoid the same

**Closed by jinujoseph** 2019-07-23 17:35 UTC
Labels: Area-IDE, Resolution-By Design
