### ISSUE TITLE
Generate better IL for `(a, b) = (b, a)`

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#61127] opened 2022-05-04 11:28 UTC
I just noticed this conversation in dotnet/runtime: https://github.com/dotnet/runtime/pull/64412#discussion_r857798132
Apparently, they avoid using `(a, b) = (b, a)` to swap variables because it generates worse IL (adds one additional local) than using a temp variable. It would be nice if this generated the same code as the classic way of swapping 2 variables, because this is a really nice, clear and explicit way of doing the swapping and helps readability.

**Comment by Neme12** [comment] 2022-05-04 12:10
BTW, in the issue templates, there's no template that is not a bug report and  doesn't suggest an API or an analyzer:
![image](https://user-images.githubusercontent.com/11444821/166678404-4667cc25-d7ed-46f3-8101-2169dc474534.png)

**Comment by Youssef1313** [comment] 2022-05-04 12:42
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/53300?

**Closed as completed** 2022-05-04 13:28 UTC
Labels: untriaged
