### ISSUE TITLE
CS8602 No warning/error should be given when using string.IsNullOrEmpty and returning that same string within ?: operator

### ISSUE THREAD

**Issue by zaggo0** [dotnet/roslyn#39290] opened 2019-10-15 14:45 UTC
**Version Used**: 
dotnet 3.0.100
Visual Studio 2019 version 16.3.4

**Steps to Reproduce**:
```C#
class Test
{
    public string? MyVar { get; set; }
    public string Computed => !string.IsNullOrEmpty(MyVar) ? MyVar : string.Empty;
}
```

**Expected Behavior**:
No warning/error should be given here, as the NullOrEmpty check suggests that `null` is never returned.

**Actual Behavior**:
The compiler throws a warning (or error when WarningsAsErrors is enabled) that the condition is possibly returning null.

**Comment by sharwell** [comment] 2019-10-15 14:48
Duplicate of #37995

**Comment by sharwell** [comment] 2019-10-15 14:49
I believe this is a duplicate of the linked issue. @zaggo0 can you confirm the target framework for your project? We would not expect CS8602 to be reported if you target netcoreapp3.0 (where `string.IsNullOrEmpty` is annotated for null-checking behavior), but for other targets where the annotations are not available the warning will appear.

**Comment by zaggo0** [comment] 2019-10-15 14:51
My apologies, I thought I checked for existing issues and thought it did not yet exist.
The Target framework is set to .NET Standard 2.0.

**Comment by sharwell** [comment] 2019-10-15 16:02
@zaggo0 No problem at all! I'm going to close this as a duplicate. 😄

**Closed by sharwell** 2019-10-15 16:02 UTC
Labels: Area-Compilers
