### ISSUE TITLE
VS option: allign pragma with code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47003] opened 2020-08-20 17:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1151364/vs-option-allign-pragma-with-code.html)._

---
I am using C# exclusively now for over 15 years. I hardly ever used pragmas, but since the compiler now flags many lines with warnings and sometimes pragmas are the only wax to get rid of the warning, I use pragma more often. Unfortunately, pragma spoils the look of the code, because VS puts them at the start of the line, which makes them look much more important than the code and breaks the indentation, but actually the pragmas a completely unimportant to understand the code. Can we have an option which aligns pragmas with the code ? 

```
namespace PragmaProblem {
  partial class BaseClass {
    public void AMethod(object o1, object o2, object o3, string message) {
      onAMethod1(o1, o2, o3, message);
      onAMethod2(o1, o2, o3, message);
      onAMethod3(o1, o2, o3, message);
    }
    partial void onAMethod1(object o1, object o2, object o3, string message);
    partial void onAMethod2(object o1, object o2, object o3, string message);
    partial void onAMethod3(object o1, object o2, object o3, string message);
  }

partial class BaseClass {
    partial void onAMethod1(object o1, object o2, object o3, string message) {
      Console.WriteLine(message);
    }
#pragma warning disable IDE0060 // Remove unused parameter
    partial void onAMethod2(object o1, object o2, object o3, string message) {
#pragma warning restore IDE0060 // Remove unused parameter
      Console.WriteLine(message);
    }
    #pragma warning disable IDE0060 // Remove unused parameter
    partial void onAMethod3(object o1, object o2, object o3, string message) {
    #pragma warning restore IDE0060 // Remove unused parameter
      Console.WriteLine(message);
    }
  }
}
```

---
#### Feedback Bot on 8/17/2020, 00:54 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-08-20 19:53
Duplicate of #12306

**Comment by sharwell** [comment] 2020-08-20 19:53
📝 This is _slightly_ different from the original report of #12306, but the design conclusion detailed in https://github.com/dotnet/roslyn/issues/12306#issuecomment-446206052 applies equally to this request so I have marked it as a duplicate.

**Closed by sharwell** 2020-08-20 19:53 UTC
