### ISSUE TITLE
Invalid warning IDE0059 when more than two assignments are on the same line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35886] opened 2019-05-22 19:15 UTC
VSF_TYPE_MARKDOWNIDE0059 can't handle more than two declaration/assignments on the same line. The following console app repros 

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using static System.Console;

    namespace InvalidWarningIDE0059
    {
        class Program
        {
            static void Main(string[] args)
            {
                int first, second, third, fourth = -1;
                first = DERP();
                second = DERP();
                third = DERP();
                fourth = DERP();
                WriteLine(first);
                WriteLine(second);
                WriteLine(third);
                WriteLine(fourth);
            }
            static int DERP()
            {
                return 1;
            }
        }
    }

The last variable when 2+ variables are declared and assigned on a single line triggers IDE0059. In this example, ```fourth``` is marked with the warning. If you remove ```fourth``` then ```third``` is.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/552602/invalid-warning-ide0059-when-more-than-two-assignm.html
VSTS ticketId: 860172_
_These are the original issue comments:_

Visual Studio Feedback System on 5/4/2019, 07:54 PM (17 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by WillSullivan** [comment] 2019-05-22 19:18
(My original issue, ping me for questions or updates, kthx)

**Comment by mavasani** [comment] 2019-05-22 19:25
@WillSullivan This issue is a duplicate of https://github.com/dotnet/roslyn/issues/35845. Please refer to this specific comment on the clarification about the intent of the diagnostic: https://github.com/dotnet/roslyn/issues/35845#issuecomment-494696985. We have improved the messaging with a recent fix that should clarify that IDE is complaining about _redundant assignment_ not a _redundant variable_

**Comment by mavasani** [comment] 2019-05-22 19:27
Closing this as a duplicate. Feel free to ask more questions if there is still any confusion. Thanks for the feedback!

**Closed by mavasani** 2019-05-22 19:27 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, Resolution-Duplicate
