### ISSUE TITLE
Metadata As Source doesn't refresh when "framework types" option changes to "predefined types"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13748] opened 2016-09-12 22:15 UTC
Metadata as source has started using "framework types" instead of "predefined types":

![image](https://cloud.githubusercontent.com/assets/1103906/18454857/9469f7ee-78fb-11e6-8789-005967ba0822.png)

The former is current preview builds, the later is VS 2015. 

I cannot figure out how to flip this setting back to what it was (predefined type preferences, which I thought would control this, does not).

**Comment by CnSimonChan** [comment] 2016-09-14 01:27
Metadata As Source now follows the Code Style settings for using framework types or predefined types, this is actually an enhancement.

But changing the Code Style settings needs a restart to take effect, because the generated source is cached.

**Comment by Pilchie** [comment] 2016-09-15 16:33
Can you dig in - there seems to be something up with the use framework types/use predefined types option serialization.

**Comment by CnSimonChan** [comment] 2016-09-16 15:56
I believe it's caused by cache. I tried:

1. Hit F12 to generate Metadata As Source.
2. Locate the generated file, delete it.
3. Edit Code Style settings.
4. Close the file and hit F12 again to re-generate it.

Two generated files will use corresponding Code Style settings.

**Comment by olegtk** [comment] 2016-09-29 22:39
This also affects LightBulb - for example "Generate local" now generates Object and String. Is it by design? If so - how to turn it off? I don't really like it.

**Comment by jasonmalinowski** [comment] 2016-09-29 23:15
@olegtk It affects everything, more or less. Option should be changed here:

![image](https://cloud.githubusercontent.com/assets/201340/18975570/e61ae32a-865f-11e6-9ed9-8886a0728800.png)

**Comment by olegtk** [comment] 2016-09-29 23:18
So this is by design and we should just update our tests, right?

**Comment by jasonmalinowski** [comment] 2016-09-29 23:22
@olegtk: no, this is a bug.

**Comment by jmarolf** [comment] 2017-01-11 20:22
metadata as source respects the option, but any already generated files are not re-generated when you change options.  I'll use this bug to track fixing the metadata as source service to delete old generated files once the option is changed.

**Comment by davkean** [comment] 2017-01-11 22:46
@jmarolf This was tracking that default changed.

**Comment by Pilchie** [comment] 2017-01-20 17:32
That was fixed by https://github.com/dotnet/roslyn/pull/16373.  Keeping this to track refreshing when options change.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 21:08
Can't repro this now.

**Closed by CyrusNajmabadi** 2024-10-18 21:08 UTC
Labels: Bug, help wanted, Area-IDE
