### ISSUE TITLE
Generate constructor refactoring should be available inside the class

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#47565] opened 2020-09-09 21:50 UTC
**Version Used**: 
VS2019 16.8 P2.1

**Steps to Reproduce**:

1. Create empty class
2. Invoke bulb menu _inside_ the class

**Expected Behavior**:
Generate constructor refactoring should be available, same as it happens with other Generate refactorings (overrides, Equals, GetHashCode)

**Actual Behavior**:
Generate constructor is available only on type definition, but not inside.

![tmOh2tSJFR](https://user-images.githubusercontent.com/17177729/92658678-a8280a00-f2ff-11ea-80f0-ae7d203df7eb.gif)

**Comment by jinujoseph** [comment] 2020-10-14 19:54
Duplicate of #48318

**Closed by jinujoseph** 2020-10-14 19:54 UTC
