### ISSUE TITLE
Using ! operator on field causes analyzers to treat it as not accessed

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31848] opened 2018-12-16 23:58 UTC
**Version Used**: 
VS2019 Preview 1 (also repros with newer compilers)

**Steps to Reproduce**:

```C#
using System;

class C
{
    object? _field = new object();

    public C()
    {
        var v = _field!.ToString();
        Console.WriteLine(v);
    }
}
```

1. Enable C# 8, and `<NullableReferenceTypes>true</>`
2. Open in VS, or install FxCop analyzers

**Expected Behavior**:
No diagnostics

**Actual Behavior**:
IDE0052	Private member 'C._field' can be removed as the value assigned to it is never read.

**Note**:
Remove the `!` and the message goes away.

**Comment by mavasani** [comment] 2019-01-22 18:24
Dupe of https://github.com/dotnet/roslyn/issues/31582? Tagging @jcouv

**Comment by jasonmalinowski** [comment] 2019-05-14 17:53
Appears to work now, and this does appear to be a dupe of #31582. Since that added IDE tests (thanks @jcouv for being awesome) there's nothing further to do here.

**Closed by jasonmalinowski** 2019-05-14 17:53 UTC
Labels: Area-IDE, Bug, New Language Feature - Nullable Reference Types
