### ISSUE TITLE
Suppressed warnings/errors from "Run Code Analysis" never disappear from Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#42351] opened 2020-03-12 01:16 UTC
Similar to https://github.com/dotnet/roslyn/issues/42350.

**Version Used**: 
Version 16.6.0 Preview 2.0 [29911.137.master]

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 237cce27c979609b92de208e9befaf42814fcf35`
4. `ProjectSystem.sln`
5. Right-click on ProjectSystem.sln and choose Analyzer and Cleanup -> Run Code Analysis
6. In Error List, select all errors and choose Suppress -> GlobalSuppression.cs, follow prompts

**Expected Behavior**:
All warnings/errors to disappear

**Actual Behavior**:
None of the warnings/errors disappear. You need unload and reload solution for them to disappear.

**Comment by mavasani** [comment] 2020-03-12 17:47
This seems to be the same root cause as https://github.com/dotnet/roslyn/issues/42353 - hidden analyzers are not running in background during FSA, when the effective severity is changed via editorconfig.

**Comment by mavasani** [comment] 2020-03-13 22:27
Verified that this issue is resolved with https://github.com/dotnet/roslyn/issues/42353.

**Closed by mavasani** 2020-03-13 22:27 UTC
Labels: Area-IDE, Bug
