### ISSUE TITLE
Decompiling ASP.NET Core 3.x assemblies in VS 2019 doesn't show actual implementation

### ISSUE THREAD

**Issue by mderriey** [dotnet/roslyn#42010] opened 2020-02-28 01:10 UTC
_Issue created as asked by David Kean in https://twitter.com/davkean/status/1233194846040444929_

**Version Used**: VS 2019 16.4.5

**Steps to Reproduce**:

1. Enable navigation to decompiled sources in "Text Editor > C# > Advanced"
1. Create a new web application project using the empty template targeting >= .NET Core 3.0
1. Open `Startup.cs`
1. Press `F12` on `UseRouting`
1. Accept the decompilation disclaimer

**Expected Behavior**:

See the implementation of the `UseRouting` method.

**Actual Behavior**:

All methods are implemented as `throw null;`.

Note VS uses the assembly in `C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.0\ref\netcoreapp3.1\` &mdash; opening the assemblies in ILSpy does show the same implementation, so it doesn't seem to be a VS decompilation issue.

The assemblies in `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.1` do have the correct implementations.

```csharp
#region Assembly Microsoft.AspNetCore.Routing, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.0\ref\netcoreapp3.1\Microsoft.AspNetCore.Routing.dll
// Decompiled with ICSharpCode.Decompiler 4.0.0.4521
#endregion

using Microsoft.AspNetCore.Routing;
using System;

namespace Microsoft.AspNetCore.Builder
{
    public static class EndpointRoutingApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseEndpoints(this IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
        {
            throw null;
        }

        public static IApplicationBuilder UseRouting(this IApplicationBuilder builder)
        {
            throw null;
        }
    }
}
```

**Comment by davkean** [comment] 2020-02-28 07:23
There's clearly some smarts to already do this for reference assemblies from .NET Framework, that same logic needs to apply to .NET Core targeting packs.

**Comment by sharwell** [comment] 2020-02-28 15:02
The root cause of this problem is decompilation is not expected to be used for these assemblies _at all_. Per #24349, navigation to ASP.NET assemblies should navigate to the original source (step 4), and not rely on ILSpy at all.

> There's clearly some smarts to already do this for reference assemblies from .NET Framework, that same logic needs to apply to .NET Core targeting packs.

It uses the GAC:

https://github.com/dotnet/roslyn/blob/f278fd4dbf471a14eaebbff4f1456ea52c706bae/src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceService.cs#L58

**Comment by sharwell** [comment] 2020-02-28 15:04
Duplicate of #24349

**Closed by sharwell** 2020-02-28 15:04 UTC
