### ISSUE TITLE
C#: cdoes not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65378] opened 2022-11-11 21:55 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C:-Tools---Options-highlighting-settin/10192476)._

---
[severity:It's more difficult to complete my work]
I'm working on a number of files that contain many of the same keywords; for example, one file contains a larger number of 'await' and 'async' keywords.
Whenever I set the cursor on an instance of a particular keyword, ALL of the other instances of that keyword on the page light up and it's highly distracting.

This action should be managed by the Tools -> Options -> Text Editor -> C# -> Advanced -> Highlighting check boxes:

    Highlight references to symbol under cursor
    Highlight related keywords under cursor

But setting or clearing the check boxes has no effect. I have attached a screenshot of an example of this problem.

---
#### Feedback Bot on 11/7/2022, 11:23 PM: 

(private comment, text removed)
#### Feedback Bot on 11/7/2022, 11:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-11-12 07:55
@arkalyanms This looks like a bug rather than a Feature Request?

My first guess would be that changes to `OptionStore` aren't reflected in `GlobalOptions` some how?

As a starting point for investigation, I think we need to first confirm if we properly hit this code path when checking/unchecking the option:

https://github.com/dotnet/roslyn/blob/cc216c93956a2c534d551568b9ae825dc3a5a6c4/src/VisualStudio/Core/Impl/Options/PerLanguageOptionBinding.cs#L44

Then, see what happens in https://github.com/dotnet/roslyn/blob/cc216c93956a2c534d551568b9ae825dc3a5a6c4/src/EditorFeatures/Core/KeywordHighlighting/HighlighterViewTaggerProvider.cs#L88-L91

**Comment by Youssef1313** [comment] 2022-11-12 11:01
This *may* be the same root cause https://github.com/dotnet/roslyn/issues/64317

**Comment by Youssef1313** [comment] 2022-11-15 21:38
I'm suspecting this to be a regression from https://github.com/dotnet/roslyn/commit/29a29d54e5ddd609650d47cb58318f874f0b99f0

**Comment by Youssef1313** [comment] 2022-11-15 21:56
I cannot reproduce the issue.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 20:43
Closing out as not repro.

**Closed by CyrusNajmabadi** 2024-10-25 20:43 UTC
Labels: Bug, Area-IDE
