### ISSUE TITLE
IOperation: VB - BoundAssignmentOperator.IValue is likely to return incorrect result for compound assignment

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8765] opened 2016-02-16 22:27 UTC
It looks like conversions on top of the operator are not handled properly:

```
        Private ReadOnly Property IValue As IOperation Implements IAssignmentExpression.Value
            Get
                If ExpressionKind() = OperationKind.CompoundAssignmentExpression Then
                    Dim rightBinary As BoundBinaryOperator = TryCast(Me.Right, BoundBinaryOperator)
                    If rightBinary IsNot Nothing Then
                        Return rightBinary.Right
                    End If

                    Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = TryCast(Me.Right, BoundUserDefinedBinaryOperator)
                    If rightOperatorBinary IsNot Nothing Then
                        Return rightOperatorBinary.Right
                    End If
                End If

                Return Me.Right
            End Get
        End Property
```

Basically, if there is a conversion on top of the operator, implementation returns the conversion. If there is no conversion, the right operand of the operator is returned.

Also, we need to clarify design for IAssignmentExpression.Value property with respect to compound assignment. Is it supposed to return the value being assigned (a binary operator with possible conversion on top) or the right operand of the binary operator with possible conversion on top? If the latter, then there is no way for a consumer to get information about conversion used for right operand.

**Comment by jinujoseph** [comment] 2017-09-29 20:44
dupe of https://github.com/dotnet/roslyn/issues/21738

**Closed by jinujoseph** 2017-09-29 20:44 UTC
Labels: Area-Analyzers, Bug, Language-VB, New Feature - IOperation
