### ISSUE TITLE
Patterns: Formatting should not insert space between Type and positional sub-pattern

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#31975] opened 2018-12-21 01:36 UTC
Proper formatting from design discussion is: `e is Point(1, 2)`.

While doing that it would be good to confirm the formatting on empty property sub-pattern (`e is { }`) as well.

FYI @gafter

**Comment by sharwell** [comment] 2018-12-21 02:47
Duplicate of #27268

**Closed by sharwell** 2018-12-21 02:47 UTC
Labels: Area-IDE, New Language Feature - Pattern Matching
