### ISSUE TITLE
VB interpolated local const keeps "unused" warning

### ISSUE THREAD

**Issue by Sehnsucht-Fr** [dotnet/roslyn#3381] opened 2015-06-08 20:47 UTC
![capture d ecran 101](https://cloud.githubusercontent.com/assets/12448828/8044832/a254df1e-0e2f-11e5-88c9-0c221e4fa370.png)
What I expect : A local const variable shouldn't stay "unused" when accessed in interpolated string.
What I get : The warning doesn't disappear even after been accessed in an interpolated string.

(Note : it works as expected in C# ; as soon as the const item appears in an interpolated string the warning vanish.)

**Comment by srivatsn** [comment] 2015-06-12 16:18
Fixed by #3435

**Comment by AnthonyDGreen** [comment] 2015-06-12 19:33
@Sehnsucht-Fr,

Thanks a bunch for finding this. We're very lucky you did. We tracked the problem to an oversight in the way the VB compiler tracks reads of local variables and constants inside of interpolated strings - in that it wasn't. Which is unnoticeable in most code patterns. But if your only reads of the local are in an interpolated string you'll get a warning. We never report an unused warning for variables that are assigned at least once but we do for constants so your specific scenario was needed to show the problem. There were other issues it revealed as well, including that refactoring would sometimes produce incorrect code. I checked in a fix for the cause along with a unit test covering your specific case. You can find the test here: https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Test/Semantic/Semantics/InterpolatedStringTests.vb#L1172

Thanks again for helping make VB14 even better!

Regards,

**-ADG**

**Closed** 2015-06-12 20:26 UTC
Labels: Area-Compilers, Bug
