### ISSUE TITLE
Error connected with the column attribute/

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44773] opened 2020-06-01 23:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1010158/error-connected-with-the-column-attribute.html)._

---
Hello,
I would like to report an error that appears during the code writing.
If you write an attribute:
[Column]
and then you add lbirary:
using System.ComponentModel.DataAnnotations.Schema;
and next you write:
[Column(name=] 
VIsual studio 2019 stop working

Kind regards,
Wojciech Kurowski

---
#### Visual Studio Feedback System on 4/28/2020, 07:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-06-04 19:52
```
Event Time (UTC): 28.04.2020 12:13:38
Event ID: 1025
Data: Aplikacja: devenv.exe
Wersja architektury: v4.0.30319
Opis: aplikacja zażądała przerwania procesu za pomocą metody System.Environment.FailFast(ciąg komunikatu).
Komunikat: System.ArgumentOutOfRangeException: Indeks był spoza zakresu. Musi mieć wartość nieujemną i mniejszą niż rozmiar kolekcji.

Nazwa parametru: index

   w System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   w System.Collections.Generic.List`1.get_Item(Int32 index)

   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.GetSelectedItem(Model currentModel, SignatureHelpItems items, ISignatureHelpProvider provider, Boolean& userSelected)

   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.<ComputeModelInBackgroundAsync>d__4.MoveNext()
Stos:
   w System.Environment.FailFast(System.String, System.Exception)
   w Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   w Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   w Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session+<ComputeModelInBackgroundAsync>d__4.MoveNext()
   w System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   w System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session.GetSelectedItem(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Model, Microsoft.CodeAnalysis.SignatureHelp.SignatureHelpItems, Microsoft.CodeAnalysis.SignatureHelp.ISignatureHelpProvider, Boolean ByRef)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session+<ComputeModelInBackgroundAsync>d__4.MoveNext()
   w System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session+<ComputeModelInBackgroundAsync>d__4, Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComputeModelInBackgroundAsync>d__4 ByRef)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session.ComputeModelInBackgroundAsync(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Model, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SignatureHelp.ISignatureHelpProvider>, Microsoft.VisualStudio.Text.SnapshotPoint, Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph, Microsoft.CodeAnalysis.SignatureHelp.SignatureHelpTriggerInfo, System.Threading.CancellationToken)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller+Session+<>c__DisplayClass3_0.<ComputeModel>b__0(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Model, System.Threading.CancellationToken)
   w Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1+<>c__DisplayClass17_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ChainTaskAndNotifyControllerWhenFinished>b__0(System.Threading.Tasks.Task`1<System.__Canon>)
   w Roslyn.Utilities.TaskExtensions+<>c__DisplayClass15_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWithFromAsync>b__0(System.Threading.Tasks.Task)
   w System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
   w System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   w System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   w System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   w System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   w System.Threading.ThreadPoolWorkQueue.Dispatch()
   w System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by sharwell** [comment] 2020-06-04 19:55
Duplicate of #36858

**Closed by sharwell** 2020-06-04 19:55 UTC
Labels: Area-IDE, Bug, Developer Community
