### ISSUE TITLE
Don't add Async suffix when making method async

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47592] opened 2020-09-10 19:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1171699/dont-add-async-suffix-when-making-method-async.html)._

---
<p>When you add the `await` keyword in a method body, Visual Studio helpfully offers to make the method async.</p> <p>When you apply that change, however, it also changes the name of the method to append the `Async` suffix.</p> <p>I consider that suffix redundant and don't want to name my methods according to that convention. Is there a setting so that this refactoring feature doesn't change the name of the method? If not, could you please add one?</p>

---
#### Robert I W Lang on 9/2/2020, 05:31 AM: 

<p>Agreed! I want to choose how to name things and not be forced by someone else's naming paradigm. </p>

#### Mark Seemann on 9/2/2020, 06:11 AM: 

<p>Here's an example to illustrate what I mean:</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/154438-async.png"></p><p>You can see in the preview how the name of the method changes.</p>

#### Romain DENEAU on 9/2/2020, 09:02 AM: 

<p>I agree with you, Mark. No `Async` suffix, or optionally (through the settings or another refactoring or a checkbox). In this case, a refinement could be to check it by default when there is already another method not async (e.g. `FirstOrDefault()` vs `FirstOrDefaultAsync()`).</p>

#### Nick Craver on 9/2/2020, 02:30 PM: 

<p>This has been discussed quite a few times, for example in <a target='_blank' href="https://github.com/dotnet/runtime/issues/26908">https://github.com/dotnet/runtime/issues/26908</a> - the consensus of the framework was that the BCL <em>does</em> use the Async suffix, for reasons there and others. It's also in the official documentation as the convention: <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model">https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model</a></p><p>&gt; The name of an async method, by convention, ends with an "Async" suffix.</p><p>Overall, I wanted to add the voice that this behavior is desirable, and should not be changed. It has a lot of benefits to the reader and is consistent with the framework itself.</p>

#### Mark Seemann on 9/2/2020, 10:30 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/48705/d7e48ff7-216a-421e-b238-10f5e5c84116.html" nodeid="48705">@Nick Craver</a> I didn't intend this to be a discussion for and against that naming convention.</p><p>In general, the .NET naming guidelines advise <em>against</em> Hungarian notation, but exceptions exist, the longest-standing of which is that interfaces are prefixed with an <em>I.</em> That convention I do follow, for various reasons.</p><p>Visual Studio does have a knob for <em>that</em> naming rule:</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/154553-i.png"></p><p>My question is whether there's a similar way to tweak the naming rules for asynchronous methods, and if not, if one could be made.</p><p>I'm not trying to change how other people name their methods.</p>

#### Dustin Moris Gorski on 9/2/2020, 11:40 PM: 

<p>100% agree with Mark. This is about preference and allowing a user to set it in their IDE just like they can do it for other code conventions too. There should be no discrimination towards async when settings already exist for other code conventions.</p>

#### Feedback Bot on 9/3/2020, 02:11 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Nick Craver on 9/3/2020, 03:54 AM: 

<p>To be clear on my above: an option for this sounds completely reasonable (even if I disagree with the resulting inconsistency), definitely want to ensure that it *is* an option though, and not a baseline change as we've seen in a few of the changes lately. Those have "flipped the bit" so to speak and did not seem to consider why it's that way now with equal weight, resulting in reverting it back and pain for both sides of a preference in the first place.</p>

#### Mark Seemann on 9/3/2020, 04:18 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/48705/d7e48ff7-216a-421e-b238-10f5e5c84116.html" nodeid="48705">@Nick Craver</a>, to be clear as well, an option is all I ask for. I'm even happy if the default setting remains the current behaviour, as long as I have a way to change it. Something to put in `.editorconfig` would be perfect, because I can see how following one rule or the other is contextual.</p>

**Comment by CyrusNajmabadi** [comment] 2020-09-11 02:33
Dupe of https://github.com/dotnet/roslyn/issues/26312

**Closed by CyrusNajmabadi** 2020-09-11 02:33 UTC

**Comment by ploeh** [comment] 2020-09-11 05:36
@CyrusNajmabadi This doesn't look like a duplicate. If I understand #26312 correctly, it's only about not renaming the `Main` method. This issue doesn't mention the `Main` method at all.

Also, #26312 was closed as fixed in April **2018**. The fact that I'm reporting this issue in 2020 indicates that the issue I'm reporting hasn't been fixed.

Please consider reopening this.

**Comment by CyrusNajmabadi** [comment] 2020-09-11 09:16
Sorry, wrong issue number.  I meant: https://github.com/dotnet/roslyn/issues/20348

**Comment by CyrusNajmabadi** [comment] 2020-09-11 09:18
> Please consider reopening this.

The issue was taken to a design review and the current behavior is as expected.  If, at some point, we get the ability to state that async methods are preferred to not have the 'Async' suffix, we'd update this feature to respect taht.

**Comment by avihais** [comment] 2022-10-03 09:25
hi, I also think that this (annoying) suffix hurts code elegancy, we don't suffix any void method with  "method" suffix:
`public void DoSomethingMethod()`
or adding function to any method that returns a value:
`public double CalculateNumbersFunction()`
also we are not worried that that the function was called but value was not used.
and yet, there is a requirement to add an Async suffix to *Any* async  method , for some reason we *do* worry for the async method not being awaited (I would except a compiler error by default).
I hope that this suffix convection will be removed as I don't think this is relevant to a modern use of code anymore, anyway, adding Async suffix to a method need to be justified, since many modern code just adding an almost pass-trough code, 
I would except that the Async suffix convention would be applied only to public methods and not on *every* method existing.

**Comment by sravimohan** [comment] 2024-03-01 22:27
Looks like the community is divided whether to the postfix Async or not.  So would be great to have an option to disable the postfix Async.

**Comment by christattum** [comment] 2024-09-03 07:05
Another vote for making this optional. I think adding the Async suffix makes sense (and is necessary) when there are async and non-async versions of a method. But where there are only async methods, the Async postfix everywhere looks redundant and ugly imho.

**Comment by CyrusNajmabadi** [comment] 2024-10-16 15:37
> Rather the method name is called via

Can those locations use nameof instead?

**Comment by iNetDaniel** [comment] 2024-10-16 15:41
Another use case would be for JavaScript that references AJAX endpoints.

**Comment by JoseTuttuGeorge** [comment] 2025-02-04 07:51
This doesn't makes sense when your web api controller methods are async. The endpoints will look weird with async after action names if custom route is not provided. Also, why do you want to add async to the name if you already defined the method as async. By the same logic, the method name should also contain the type that is returned by the method like AddInt, AddDouble etc. The compiler is already doing it's job of notifying if a method is not awaited, shouldn't that be enough?
[Compiler Warning (level 1) CS4014](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014?f1url=%3FappId%3Droslyn%26k%3Dk(CS4014)) 

Also, if the development team is overlooking warnings, then they will overlook namings as well. With the current advancement in Intellisense, these conventions should be optional.

**Comment by avihais** [comment] 2025-02-04 15:14
Hi, I'm here again (since October 2022).

I believe the Async suffix is **unnecessary** because the async keyword in the method signature already indicates that a method is asynchronous. The main reason for keeping the suffix is to improve clarity at the call site and differentiate between sync/async method pairs. **However, if the C# compiler enforced awaiting async methods by default (unless explicitly ignored), there would be no need for the suffix at all**. Removing it would make modern code cleaner and more consistent.

**Comment by CyrusNajmabadi** [comment] 2025-02-04 15:57
The `async` keyword is not part of a method's signature. Without access to the source code, you cannot tell if it was present or not. The keyword simply affects how parsing works within the body. Manuel, if `await` is a keyword, or just a simple identifier.

**Comment by JoseTuttuGeorge** [comment] 2025-02-04 16:44
It might make sense when you are working on a library. But there are web services where your repo layer is accessing db using async methods. Now all the layers needs to add this async suffix to its method name. A simple GetById becomes GetByIdAsync. This is actually a pain for the eyes. By looking at the signature we know that the return type is task<object>. So isn't it obvious I have to await?  Why do I need to specify it again in the name? Then why not make the other way round also, suffix methods with sync. In database oriented application I have worked on 90 percent of the methods are async since they have atleast one db call. So if the intellisense correction can be tweaked based on option we can avoid the async suffix for those who doesn't want it.

**Comment by triynko** [comment] 2025-02-04 17:44
I completely disagree that Async at the end of a method name looks bad. It looks great. It makes it super clear that it's a task returning method. A method name like GetById looks like it's a synchronous call. GerByIdAsync makes it clear that it's a Task-returning method that needs to be awaited. Not the company I work for doing global loyalty, The entire stack is.net and we follow this original Microsoft recommendation of using async suffix as everywhere. When I'm doing a code review and someone makes a Task-returning method doesn't and the name and Async I let them know. When you're inspecting code for correctness and to make sure that there aren't things that aren't awaited and so on and so forth. And you're just glancing at the code. All you have to go on is the method name and I'm telling you it's infinitely more helpful to have async there than not. And it can become super confusing when someone fails to include it, especially if they left it off whether the only justification being "I don't like the way it looks".  Sorry, but no. Too many negative consequences of using that as a justification.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by triynko** [comment] 2025-02-04 17:53
Sorry for all the typos in that last reply. All I'm trying to say is that I find the Async suffix very clear and useful. I think it looks great. It makes it easier to read and understand code at a glance, without even having to hover over anything, knowing with certainty that a method returns a Task. It can be hard to tell whether "result" is a Task when you see just "var result = MethodCall()" everywhere. If I'm storing a Task in a variable then I name the variable with a Task suffix like "var resultTask", to keep things very clear. This makes it much easier to manage several Tasks started in parallel. This distinction of Task-returning and non-Task-returning methods is extremely important and low-level, and it's agnostic to the operation's subject matter. Regardless of what you name your variable, it's a completely separate concern to distinguish whether that variable is an actual result versus a Task that contains a result, so these suffixes are extremely useful.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iNetDaniel** [comment] 2025-02-04 19:25
I think it's fantastic that the existing functionality works for you. We're not asking to get rid of it, merely to make it optional for organizations like mine where we don't want that naming convention because it simply doesn't apply to us. We disallow implicit type declarations in our code base, so the example of "var result = MethodCall()" is a non-issue. Awaitable function calls that are not awaited popup as a warning in our CI build pipeline, again making it a non-issue. We don't even have to code review to find it.

**Comment by CyrusNajmabadi** [comment] 2025-02-04 19:29
> we don't want that naming convention because it simply doesn't apply to us.

There is no requirement to follow this naming convention.  You are free to name methods how you want :)

**Comment by JoseTuttuGeorge** [comment] 2025-02-06 11:58
> > we don't want that naming convention because it simply doesn't apply to us.
> 
> There is no requirement to follow this naming convention. You are free to name methods how you want :)

Yes. But currently the intellisense is forcing it. There is no option to turn it off. If there was an option to avoid rename of function it would be great. By default let it append async to the method. But, there should be an option somewhere in visual studio to make it optional so that it caters to the other audience as well.
