### ISSUE TITLE
Improve detection of availability of GAC in GacFileResolver

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5538] opened 2015-09-29 20:33 UTC
Currently we check for absence of `AssemblyLoadContext`. Consider a better check (perhaps the presence of `Assembly.GlobalAssemblyCache` once CoreCLR mscorlib is cleaned up).

**Comment by gafter** [comment] 2015-09-30 02:21
@tmat can you please assign this to the appropriate team? I don't know from the description what the problem is or which component is implicated.

**Comment by kennethy2** [comment] 2016-06-04 20:47
I am not sure of the problem either we need a more in depth knowledge of the problem

**Closed** 2020-07-13 17:35 UTC
Labels: Area-Interactive, Concept-Continuous Improvement, Interactive-ScriptingLogic
