### ISSUE TITLE
VS2019 syntax highlight (C#) - methods aren't colorized within nameof()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35246] opened 2019-04-24 21:03 UTC
VSF_TYPE_MARKDOWNWithin a class, when referencing a local method using `nameof()`, it isn't colorized according to Fonts and Colors rule for “User Members - Methods”. Method's declaration and its calls are correctly colorized.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/529390/vs2019-syntax-highlight-c-methods-arent-colorized.html
VSTS ticketId: 845546_
_These are the original issue comments:_

Visual Studio Feedback System on 4/12/2019, 01:01 AM (12 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/15/2019, 06:44 PM (8 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by JoeRobich** [comment] 2019-04-26 00:48
Duplicate of https://github.com/dotnet/roslyn/issues/35246
Fixed by https://github.com/dotnet/roslyn/pull/35247

**Closed by JoeRobich** 2019-04-26 00:48 UTC
Labels: 4 - In Review, Area-IDE, Bug
