### ISSUE TITLE
Expose a public API to tell whether Document/SyntaxTree is likely a generated file

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#4530] opened 2015-08-13 07:15 UTC
There is an IGeneratedCodeRecognitionService, but it's internal: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/GeneratedCodeRecognition/IGeneratedCodeRecognitionService.cs,da8ecea861634562

My scenario: I don't want the diagnostic produced by my analyzer to show up in the Error List and I don't want fixes offered in files such as g.i.cs etc. I should be able to either declaratively specify this on my diagnostic provider (via attribute, optional param etc) or imperatively during analysis ask the Document or the SyntaxTree whether it was likely generated (either by making the interface above public or by exposing a property "LooksLikeGeneratedCode" or something).

**Comment by pharring** [comment] 2015-08-13 15:06
CSharpEssentials (@DustinCampbell) had the same [problem] (https://github.com/DustinCampbell/CSharpEssentials/issues/14). Ended up [copying the source code](https://github.com/DustinCampbell/CSharpEssentials/blob/dacfd48b2ad793d5c427f486b25d6741d65deffb/Source/CSharpEssentials/Extensions.cs#L139).
Note that it's just a heuristic based on the document's filename.

You might also want something that works on a SyntaxNode that looks for "compiler generated" attributes. See https://github.com/DustinCampbell/CSharpEssentials/issues/26

**Comment by KirillOsenkov** [comment] 2015-08-13 18:45
Yeah. Imagine every analyzer out there having an outdated copy of that list :) I think that language service should be made public and extensible by MEF so you could export your own criteria to extend the hardcoded list.

**Comment by paul1956** [comment] 2015-08-13 23:41
+1 I had to clone from CSharpEssentials (@DustinCampbell <https://github.com/DustinCampbell> ) and then change for VB.

**Comment by srivatsn** [comment] 2015-08-26 19:10
We would likely have to tackle this when we get to #3705.

**Comment by giggio** [comment] 2015-08-26 19:37
We had to manually solve this on CodeCracker: https://github.com/code-cracker/code-cracker/issues/260
This should really be on the Roslyn platform, not on the analyzer project themselves.

**Comment by giggio** [comment] 2015-08-26 19:38
BTW, is this a duplicate of #1751?

**Comment by srivatsn** [comment] 2015-08-26 20:09
It's not a duplicate but it's related. The codeanalysis property page for a project today has a switch called "Suppress issues in generatedcode" and FxCop knows to not analyze things marked with that attribute. I think to implement #3705 we'd want a similar treatment for roslyn analyzers where analyzers aren't even called by the compiler on generated code. However what is generated code is very heuristic driven and making an API for problematic unless there was either some clear definition or a way to customize that definition.

**Comment by DustinCampbell** [comment] 2015-08-26 20:15
FWIW, I just submitted https://github.com/DustinCampbell/CSharpEssentials/pull/31 to do a better job than just looking at file names. Now, C# Essentials also looks for ```<auto-generated>``` in a file's comment header, which StyleCop supports.

**Comment by bkoelman** [comment] 2015-09-03 15:34
I'm doing (similar checks)[https://github.com/bkoelman/ResharperCodeContractNullability/blob/master/src/CodeContractNullability/CodeContractNullability/GeneratedCodeDocumentCache.cs]. it would be great to have an API within the compiler for that.

**Comment by srivatsn** [comment] 2015-11-24 17:20
We discussed this in a design meeting recently and exposing the current API as is doesn't seem to be wise because it is a small set of heuristics. We need a configuration file that can extend these heuristics. We'll use #3705 to track that work. However, even when we have that, for analyzers atleast, the default should be that issues shouldn't be reported in generated code because users cannot fix them in most cases and requiring analyzers authors to remember to call this API wouldn't lead to a pit of success. So we want to instead implement #6998 to make it easy for analyzer authors to say they do\don't care about reporting issues in generated code and have the users override them.

**Comment by srivatsn** [comment] 2015-11-24 18:00
Closing this issue to expose a generic API given #6998.

**Closed** 2015-11-26 12:22 UTC
Labels: API, Area-Analyzers, Feature Request
