### ISSUE TITLE
CodeLens does not count references to extension methods

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1796] opened 2015-04-04 06:56 UTC
When calculating the number of references to an extension method, CodeLens ignores all calls to the extension method which take the form of an instance method invocation. This makes it very easy to accidentally remove an extension method which is used during a code review for unreferenced code.

**Comment by Pilchie** [comment] 2015-04-06 16:52
Do you have a specific repro, and which build are you using?  I can't repro this using:
```C#
class Program
{
    static void Main(string[] args)
    {
        new Program().M();
    }
}

static class Ex
{
    public static void M(this Program p) { }
}
```

**Comment by balajikris** [comment] 2015-04-06 18:01
I wonder if the scenario was something like this: a method symbol defined in a project and consumed in projects A and B via an assembly reference. Now, reference counts at usages in A and B would be incorrect. 

If so, we recently fixed a bug where shadow copying of metadata references could fail, thus leading to incorrect reference counts.

**Comment by sharwell** [comment] 2015-04-06 18:21
Using Visual Studio 2015 CTP 6, it seems the problem occurs when the caller is in the same class as the extension method. I didn't realize that previously.

**Comment by sharwell** [comment] 2015-04-06 18:24
From **SpacingExtensions.cs** in DotNetAnalyzers/StyleCopAnalyzers@98c5b7a418c752fa0a7c70d4a3144c31afc3c16a. The first `WithoutWhitespace` method is actually not used, but the second is obviously used and shows 0 references.

![image](https://cloud.githubusercontent.com/assets/1408396/7009465/12edc36e-dc60-11e4-949a-397b37a31f54.png)

**Comment by balajikris** [comment] 2015-04-09 17:52
@sharwell It looks like this works in our latest internal drops. Screenshot below. I also tried via downloading the zip and also by forking the project (in case the git provider had something to do with it), but it seems to work in both cases. I suspect that it could have been fixed due to some of our recent changes, but I am not sure yet. I will spend a bit more time trying to break it :smile: 

![image](https://cloud.githubusercontent.com/assets/4213867/7073100/ecd15bf8-dea5-11e4-966b-f4bdadc0c0d1.png)

**Comment by Pilchie** [comment] 2015-05-01 02:03
Hey @sharwell - could you give this a try on the RC build and see if you still see it?

**Comment by balajikris** [comment] 2015-05-19 00:14
Hi @sharwell , I attempted numerous times to reproduce this issue but couldn't hit it in our latest drops. I also don't find anything suspicious when I inspected this with a debugger attached. Before I close out this issue as Not-Reproducible, I wanted to get confirmation from you if everything works good for you in the recent RC build? when you get a chance, please let me know.

**Comment by sharwell** [comment] 2015-05-19 01:15
It's working for me in the RC build. :+1:

**Comment by balajikris** [comment] 2015-05-19 01:17
Great, thanks for confirming. Closing as Not-Reproducible.

**Closed by balajikris** 2015-05-19 01:17 UTC
Labels: Area-IDE, Bug, Resolution-Not Reproducible
