### ISSUE TITLE
GoTo doesn't list source-generated symbols

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#50352] opened 2021-01-09 01:28 UTC
Repro: From `Compilers.sln` hit `CTRL+.` to invoke `GoTo` and type the name of a syntax node that is exclusively declared in source-generated source (for example, `NullableDirectiveTriviaSyntax`).

The type isn't found (but should).

This should also work when adding new types via `syntax.xml`.

FYI @jasonmalinowski @chsienki

**Comment by jasonmalinowski** [comment] 2021-01-09 01:44
Duplicate of #49581.

**Closed by jasonmalinowski** 2021-01-09 01:44 UTC
Labels: Area-IDE, New Feature - Source Generators, untriaged
