### ISSUE TITLE
IDE0029 results in a behaviour change when the comparison operator is overridden

### ISSUE THREAD

**Issue by corngood** [dotnet/roslyn#62765] opened 2022-07-19 12:32 UTC
**Version Used**: 
6.3.322007+dc5c84e776364e1c23a5cf2d1a848d4022f8634f

**Steps to Reproduce**:

https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABAZixICYsAVLAb2KxcooHsA3DAJx4Etg2fjAAuWAOIZRACWQBnABYBhdkIAUASiwBeAHxYADAG5mrcli68BQrKnbsEWAKIBHOMgTz17VACsMAGNRAH5Lf219LAAzT3kMUyJWNkoARgA2OwcndgAHXmRRdh4dHXVaMIAPABo6MIBPSINYrwSzFgsSDKzHS3yeQuKAQjKKrBq6rEbdA1EeODaiAF9iYk6aZUZ2lLGAWXKw5Fqx1G0mJOTzAHYsZCwRrHgkLEOsEDtE5JXloA===

**Expected Behavior**:

`??` should not be suggested when the comparison operator is overloaded

**Actual Behavior**:

`??` is suggested, which changes behaviour

**Comment by CyrusNajmabadi** [comment] 2022-07-19 15:31
So you have a real world example where this was a problem?  Thanks!

**Comment by corngood** [comment] 2022-07-19 16:29
Yeah, unfortunately Unity has this 'fake null' thing in their base object implementation (https://docs.unity3d.com/ScriptReference/Object-operator_eq.html) which is implemented in operator ==/!=.

**Comment by Youssef1313** [comment] 2022-07-19 16:34
I was expecting the answer to be "Unity" :)

This was previously reported in https://github.com/dotnet/roslyn/issues/59263

**Comment by CyrusNajmabadi** [comment] 2022-07-19 16:41
Dupe of https://github.com/dotnet/roslyn/issues/59263.  Note: i do not believe we'd change this.  Tons of normal types overload `==` and `!=` in a sane fashion.  Thing of things as basic as System.String you'd want the following to be simplified: `Foo(string x, string y) => x != null ? x : y;`.  

Looking at the entire BCL and all the codebases we use, people operate sanely here and we want this analyzer to be usable for all those APIs.  Unity is the odd group out that really violates the spirit of .net here.  Note that .net recommends for `.Equals` that this always return false: `x.Equals(null) returns false.` (https://docs.microsoft.com/en-us/dotnet/api/system.object.equals?view=net-6.0).  It also says:

> ✔️ DO ensure that [Object.Equals](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals) and the equality operators have exactly the same semantics and similar performance characteristics."

Our analyzers need to work on code following best patterns and practices.  They should not be unable to do that because of pathological cases in the wild that violate these best practices.  For your codebase, i would recommend suppressing or disabling this analyzer.

**Closed by CyrusNajmabadi** 2022-07-19 16:41 UTC
Labels: untriaged
