### ISSUE TITLE
Deduplicate Find All References results in multi-targeting projects

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#23730] opened 2017-12-11 23:24 UTC
**Version Used**: 
the version shipped in 15.4.3

**Steps to Reproduce**:

1. Have an SDK-style project that multitargets, e.g. `<TargetFrameworks>net461;netstandard1.5</TargetFrameworks>`
2. FAR on any symbol from that project

**Expected Behavior**:
Fully identical occurrences should be unified (deduplicated).

**Actual Behavior**:
I'm seeing every definition and reference twice and they're exactly the same location and everything.

![image](https://user-images.githubusercontent.com/679326/33859101-4ea3d17e-de87-11e7-854b-ea9ad9ad8606.png)

This is a problem with cognitive load. You have double the information. FAR is a very commonly used tool and it needs to get out of the way as much as possible. Having every reference showing twice or more is just not helpful. When looking through the list I often build a mental map of all usages, classifying them and bucketizing by some criteria (aha, it can't be here, can't be here, this one is suspicious, this one we can ignore, etc. etc.)

The current structure makes that really complicated (I have to do twice the work).

Same problem in Navigate To:
![image](https://user-images.githubusercontent.com/679326/33859134-6c9ec684-de87-11e7-85bb-6f9a697cb511.png)

**Comment by CyrusNajmabadi** [comment] 2017-12-11 23:35
Note: this would need some help/support from the Editor team.  Right now hte API design is such that an entry in the list can only be associated with a single project.  ideally we could weaken that to be associated with multiple projects.  Then, from a presentation perspective, handling this would be fairly trivial.  We'd just bucket based on filename+location, and we'd ensure that any new results that came it would be merged with the old one.

I'd be happy to provide guidance here for hte Roslyn side of htings.  But we'd have to drive some editor work here as well.

**Comment by Pilchie** [comment] 2017-12-12 00:44
Dupe of https://github.com/dotnet/roslyn/issues/16587.

**Comment by jcouv** [comment] 2017-12-12 04:07
Closing as dupe. Thanks

**Closed by jcouv** 2017-12-12 04:07 UTC
Labels: Area-IDE, Resolution-Duplicate
