### ISSUE TITLE
Proposal: Intersection types

### ISSUE THREAD

**Issue by MouseProducedGames** [dotnet/roslyn#4586] opened 2015-08-16 17:36 UTC
Let's say you have an IQuadruped interface:

```
public interface IQuadruped
{
    public Leg FrontLeftLeg { get; set; }
    public Leg FrontRightLeg { get; set; }
    public Leg BackLeftLeg { get; set; }
    public Leg BackRightLeg { get; set; }
    // ...
}
```

and an IMammal interface:

```
public interface IMammal
{
    public NumberOfHairs { get; }
    // ...
}
```

And, of course, some classes implementing both interfaces.

```
public class Dog : IQuadruped, IMammal, ... { // ... }
public class Cat : IQuadruped, IMammal, ... { // ... }
public class Platypus : IQuadruped, IMammal, IReallyWeird, ... { // ... }
// ...
```

Now you want to operate on all the quadrupedal mammals in your enumerable of animals:

```
foreach (var animal in animals.Where(a => a is IQuadruped && a is IAnimal))
{
    IQuadruped qAnimal = (IQuadruped)animal;
    IMammal mAnimal = (IMammal)animal;
    // Code involving both interfaces here.
}
```

And, of course, the complexity goes up the more interfaces you want to check.

However, if, instead, you had:

```
foreach (var animal in animals.Select(a => a as I<IQuadruped, IAnimal>).Select(a => !object.Equals(a, null))
{
    // animal is now of type I<IQuadruped, IAnimal>.
    // Any operation supported by either interface is supported by the combined interface.
    // And you only have to reference one variable.
}
```

In short, `I<Interface, ...>` combines interfaces into one interface, without having to create an IQuadrupedMammal interface, going back into your code, and refactoring. Which may not be possible, or may be impractical. IQuadrupedMammalReallyWeirdFromAustralia...

**Comment by MouseProducedGames** [comment] 2015-08-17 19:33
I used IAnimal a few times instead of IMammal. Doesn't change the point or anything, but I don't know how to go back and edit out those word errors.

**Comment by Corey-M** [comment] 2015-08-18 03:19
This can be done by creating composite interfaces and applying them to the classes:

````
public interface IQuadrupedMammal : IQuadruped, IMammal
{
}

public class Dog : IQuadrupedMammal { /*...*/ }

for (var animal in animals.OfType<IQuadrupedMammal>())
{
}
````

Unfortunately this would require you to create such a composite for every combination of interfaces you want to test/use and apply all of the relevant composites to every qualifying class.  Especially where you have overlapping composites this has the potential to get out of hand very quickly and certainly damages maintainability.

Perhaps a better alternative is to allow duck typing on interfaces, either in general or by the introduction of a new interface type: implicit interface.  I have no idea whether this is possible without changes to the CLR.

**Comment by aluanhaddad** [comment] 2015-09-05 04:47
I think this is a special case for a general feature: Expressing intersection types.
I don't think the proposed syntax  would work particularly well, as it would clash with the syntax for generics.
How about
``` scala
IQuadruped with IMammal with IAnimal
```
a la Scala or 
```typescript
IQuadruped & IMammal & IAnimal
```
a la TypeScript?

As a side note, this would be very useful in the context of the proposed pattern matching feature.

**Comment by alrz** [comment] 2015-10-21 19:32
once again, conjunctive patterns would solve this.
```cs
if(obj is IQuadruped and IMammal and IAnimal) {}
```
although, if you want variables, you should define one per interface
```cs
foreach (var animal in animals) {
    if(obj is IQuadruped q and IMammal m and IAnimal a) {
        ...
    }
}
```
I think this is more practical than "type intersections" since C# doesn't allow such syntax in `catch` clause neither.

**Comment by aluanhaddad** [comment] 2015-10-21 23:37
@alrz the problem with
```C#
(animal is IMammal m and IQuadruped q and ICarnivore c)
```
Is that you would frequently want to have a single variable. 

>you should declare one per interface
Does not feel right.

**Comment by alrz** [comment] 2015-10-21 23:52
The nice thing about conjunctive patterns is that since they are defined under *pattern* they would be used in a wider context, while you can already use generic constraints for that case:
```cs
void F<T>(IEnumerable<T> animals) where T :  IMammal, IQuadruped, ICarnivore {
    foreach(var animal in animals) {
        ...
    }
}
```
VB Syntax is even more closer to what you've suggested:
```vb
Public Sub F(Of T As {IMammal, IQuadruped, ICarnivore})(animals As IEnumerable(Of T))
    For Each animal In animals
        ...
    Next
End Class
```
What does type intersections do that can't be done with generic constraints?

**Comment by aluanhaddad** [comment] 2015-10-21 23:58
@alrz the ability to write
```C#
void F<T>(IEnumerable<T> animals) where T :  IMammal, IQuadruped, ICarnivore {
    foreach(var animal in animals) {
        ...
    }
}
```
How do I pass an argument to ```F```?
e.g. how does this work?
```C#
switch (x)
{
    case animal is IMammal m and IQuadruped q and ICarnivore c:
    F(???);
}
```

**Comment by alrz** [comment] 2015-10-22 00:01
You shall pass the `x` itself, which (I suppose) is of some type that implements all three interfaces.

**Comment by aluanhaddad** [comment] 2015-10-22 00:02
Right, but _how_ do you pass it. It cannot be by a cast, since there is again no way to refer to the type.

**Comment by alrz** [comment] 2015-10-22 00:08
You mean it's an `object`? How would that get there? I would declare an overload for enclosing method of `switch` so it will be known that it implements those interfaces. If it's upcast to `object` what is the point of these interfaces at first place?

**Comment by aluanhaddad** [comment] 2015-10-22 00:12
The idea is you are in some general animal handler function like
```C#
void ProcessAnimals(IEnumerable<IAnimal> animals) { ... } 
```
So the type my not be object, but it may not be specific enough. Furthermore, and this was a key point made in the original post of this proposal, suppose you do not _have_ an ```ICarnivorousMammalianQuadruped``` interface in the first place.

**Comment by alrz** [comment] 2015-10-22 00:24
Well, that is not what you would get from [*polymorphism*](https://en.wikipedia.org/wiki/Polymorphism_(computer_science)). "A polymorphic type is one whose operations can also be applied to values of some other types". If these operations vary from type to type, then you should use virtual dispatch or method overloads to specialize these operations for a specific type.

So, in your example, `ProcessAnimals` shall be overloaded for operations that cannot be done to a *general animal*. And the compiler will infer appropriate method from the target type.

**Comment by aluanhaddad** [comment] 2015-10-22 00:25
@alrz then what is the justification for pattern matching?

**Comment by alrz** [comment] 2015-10-22 00:33
When you're using record types in patterns, that is called pattern matching, because you're actually *matching* a *pattern* like `Expr(Const(0), Const(1))` against an object, but what you're doing here is just a type test which of course is base of pattern matching. By the way, F# is using a different syntax for type tests:
```fs
match x with
| :?  IMammal as m
& :? IQuadruped as q
& :? ICarnivore as c -> ...
```

**Comment by aluanhaddad** [comment] 2015-10-22 00:39
But the example does not involve a sum type that can be decomposed into different components. That is composition not inheritance.

Suppose I have a hierarchy
```C#
interface IWord { string Text { get; } }
interface INoun : IWord { IVerb SubjectOf { get; } }
interface IVerb : IWord { INoun: Subject { get; } }
``` 
We can agree that nouns and verbs _are_ words, but there are additional properties that are not common between them such that they can be extracted into the base type word. Nevertheless it may be valuable to have an IEnumerable<IWord>.

**Comment by alrz** [comment] 2015-10-22 00:50
> I have a *hierarchy*

Yeah, that's inheritance.

Why not you do this:
```cs
void F(IEnumerable<IWord> words) {
    foreach(var word in words) {
        switch(word) {
            case INoun n: ... // operations to nouns
            case IVerb v: ... // operations to verbs
        }
    }
}
```
If these operations are exactly the same, you should do it on the base `IWord`.

**Comment by aluanhaddad** [comment] 2015-10-22 01:04
But now, imagine I define the following
```C#
interface IPresentPartciple : INoun, IVerb { }
```
Of course I can define that interface, but there are other conceptual types that implement both interfaces but are not present participles and I would like to be able to treat them the same way.

**Comment by alrz** [comment] 2015-10-22 01:08
If there is a "same way" so they both should be derived from the same type. If your class hierarchy was well designed, you wouldn't encounter these problems at all.

**Comment by ufcpp** [comment] 2015-10-22 01:26
I like this concept, but IMO, its syntax should be consistent with that of generic constraints. How about the following:

```
x is T t where T : IQuadruped, IMammal
```

**Comment by aluanhaddad** [comment] 2015-10-22 01:32
In many cases, that would be symptomatic of an ill thought out hierarchy, but sometimes you have multiple axes of inheritance that cut across one another due to the semantics of the domain. 

At any rate deriving such combinations from a base type, here it could be ```INounAndVerb```, is possible, even easy, but it is unpleasant because you have to define and extend an interface for _every_ combination. That aside, conjunctive patterns, as you propose them, do _not_ suffice because they do not give you a single reference to the matched value. 

Also the number of combinations can get out of hand quickly. 
Going back to the original example:
```C#
interface IAnimal { }
interface IReptile : IAnimal { }
interface IMammal : IAnimal { }
interface ICarnivore : IAnimal { }
interface IMammalLikeReptile : IReptile, IMammal { } // of paleontologic interest
interface ICarnivorousReptile : IReptile, ICarnivore { }
interface ICarnivorousMammal : IMammal, ICarnivore { }
... and on and on 
```
@ufcpp that seems quite nice.

**Comment by alrz** [comment] 2015-10-22 01:36
Which ones you want to combine then?

**Comment by aluanhaddad** [comment] 2015-10-22 01:39
Quite possibly all of them, but it could will evolve as functionality increases.
if I add 
```C#
interface ICarnivorousMammalLikeReptile : IMammalLikeReptile, ICarnivore { }
```
I want to be able to match the type of carnivorous reptiles against it.

**Comment by alrz** [comment] 2015-10-22 01:41
What kind of operation that would it be? That doesn't make sense at all. You are just mentioning types and combinations. Not operations.

**Comment by aluanhaddad** [comment] 2015-10-22 01:44
How does it not make sense? Perhaps I have some logic that takes into account aspects of reptiles in determining their likelihood of successfully catching prey.

**Comment by alrz** [comment] 2015-10-22 01:51
> of reptiles

So the method your are looking for would be defined in the `IReptile` interface. Hence, you don't need any combination.

**Comment by aluanhaddad** [comment] 2015-10-22 01:56
Negative it would be a generic method
```C#
AnalyzeReptilianHuntingBehavior<T>(T hunter) where T: IReptile, ICarnivore { ... }
```
And I may pass an ICarnivorousMammalLikeReptile or an ICarnivorousReptile to it.

**Comment by alrz** [comment] 2015-10-22 02:02
You are just twisting the question without knowing your hierarchy. See, carnivorousness is not even in the *classification*, it's a *property* of a *general animal*.

**Comment by aluanhaddad** [comment] 2015-10-22 02:06
I just named it that for readability. ICarnivore is in the hierarchy. Why do you presume it is a property of a the base type? Anyway, I fail to see the resistance to the example given that you are _proposing_ if (a is IReptile r and ICarnivore c) { ... } which implies the combination can exist. I am simply proposing a way to for a value have the aggregate type of the set of matched types.

**Comment by alrz** [comment] 2015-10-22 02:12
There is no combination, it's just two individual type tests. "Why do you presume it is a property of a the base type?" I just googled it. There is no "carnivore" in the classification. That's all I know.

**Comment by aluanhaddad** [comment] 2015-10-22 02:17
It is an abstract, arbitrary example. Nevertheless, cats are classified as Mammalia -> Placenta -> Carnivora -> ...
But this is not about modelling the domain of existing classification taxonomies, it is about having cross cutting classifications for types and the ability to express that and perform different operations depending on different combinations. My point is that if it makes sense as a constrained generic type, and if it also makes sense as a pattern, then it makes sense for there to exist some value of said type and to be able to refer to its type. I fail to see the problem.

**Comment by alrz** [comment] 2015-10-22 02:26
ok how would  type intersection syntax (if it's intended to be used as *pattern*) doesn't conflict with conjunctive patterns? The former is only valid in type tests (to be more precise, just interfaces) while the latter works with all kind of patterns.

**Comment by aluanhaddad** [comment] 2015-10-22 02:33
That's a fair question. I say both features have value and are complementary. As far as syntax, I have no proposed one. There could easily be a syntax for type intersection that does not conflict in any way with conjunctive patterns. I merely wrote
```C#
if (a is IReptile and ICarnivore rc) { ... } 
```
to illustrate that the validity of conjunctive patterns implies the semantic validity of intersection types.
@ufcpp proposed a syntax that would not conflict but it has other issues. I don't think the syntax matters so long as it does not conflict.

**Comment by alrz** [comment] 2015-10-22 02:40
I don't know if this is ambiguous with #5402, since no lexical grammar mentioned in the suggestion.

**Comment by aluanhaddad** [comment] 2015-10-22 02:49
I'll try to come up with a lexical grammar and propose it. May I suggest you create a separate proposal for conjunctive and/or disjunctive patterns. #5402 has a lot of ideas and implications and I see conjunctive and disjunctive patterns as orthogonal to expression forms for statements.

**Comment by alrz** [comment] 2015-10-22 03:36
@aluanhaddad That wasn't part of it at first, but conversation goes on and proposal changes several times. It's fixed now.

**Comment by HaloFour** [comment] 2015-10-22 09:57
I'd think that intersection should be a type pattern unto itself rather than trying to shoe-horn it into "conjunctive patterns" with odd variable declaration.

```cs
if (x is (IDisposable && IFormattable) y) {
    Console.WriteLine(y.Format(format, null));
    y.Dispose();
}
```

This would be syntactically equivalent to:

```cs
if (x is IDisposable y1 && x is IFormattable y2) {
    Console.WriteLine(y1.Format(format, null));
    y2.Dispose();
}
```

The compiler would emit a local for each type, assign them all to the same instance and silently switch between the locals depending on the context of its use.  I initially thought that this might be an issue, especially if `y` was passed to a method as `ref`, but since pattern variables are readonly I don't think that would be an issue.

What would likely have to be resolved is the new typing that this would introduce.  To my knowledge C# has no concept of treating a variable as a set of multiple types.  The closest you'd get is with generic constraints but even then the compiler/tools know the variable as the generic type, not as the separate constraint interfaces.

**Comment by alrz** [comment] 2015-10-22 16:39
I wonder what happens if there is a method with same name and signature in both interfaces.

**Comment by alrz** [comment] 2015-10-22 16:46
@HaloFour exactly, this cannot be compared to generic "constraints", it will be a new kind of type, I guess?

**Comment by aluanhaddad** [comment] 2015-10-23 17:54
@HaloFour exactly my point. This is the motivation for intersection types as a separate type construct. As you say it would require a new kind of type construct. If they were only available as local declarations the compiler could generate a type behind the scenes which implements the intersected types with methods that delegate to the actual value, but there are a number of details that need to be worked out. I think it would be worthwhile.

**Comment by lmcarreiro** [comment] 2016-08-18 14:49
What happens in the case that two interfaces when both of them contains a member with the same name, but with different implementations (explicit implementations)?

I think that it would be complicated, even if the implementations are the same (implicit implementation), because the member gets duplicated in the class's method table... at runtime there is no difference, CLR doesn't know if the implementations are the same or not.

**Comment by HaloFour** [comment] 2016-08-18 17:06
@lmcarreiro 

Personally I'd go with overload resolution in the order in which the intersected interfaces are defined:

```cs
public interface IFoo {
    void Hello();
}

public interface IBar {
    void Hello();
}

public class FooBar : IFoo, IBar {
    public Hello() {
        Console.WriteLine("Foo!");
    }

    void IBar.Hello() {
        Console.WriteLine("Bar!");
    }
}

(IFoo && IBar) test1 = new FooBar();
(IBar && IFoo) test2 = new FooBar();

test1.Hello(); // prints Foo!
test2.Hello(); // prints Bar!
```

I can appreciate that there may be some confusion that `IFoo && IBar` and `IBar && IFoo` wouldn't behave identically, though.

**Comment by alrz** [comment] 2016-08-18 17:38
This situation is currently reproducible,
```cs
interface A {void M();}
interface B {void M();}

void M<T>(T t) where T : A, B => t.M(); // ERROR

```
The only place that I've encountered in which order becomes significat is with covariants ([example](http://stackoverflow.com/questions/14562047/generic-type-parameter-covariance-and-multiple-interface-implementations)). In that case, the compiler *can not possibly know about the ambiguity*.

**Comment by Pzixel** [comment] 2016-12-26 07:57
It would be a great feature. For example I'm using some code-generating method which returns class for specific inerface:

```csharp
public T GenerateMyClass<T>(){...}
```

But if my inner class is for example `IDisposable` I have only two possibilities

1. Just implement it and return base interface. It should be manually casted to `IDIsposable` to free resources or
2. I have to force my users to inherit `IDisposable` interface themselfs by using `where T : IDisposable` even when T should not be IDisposable.

With this feature it would be easy to write:
```csharp
public T & IDisposable GenerateMyClass<T>(){...}
```
which would accomplish it without any cons.

**Comment by TonyValenti** [comment] 2017-01-04 13:16
I really like the following syntax for declaring variables:
````
var x is IAnimal, IMammal = Something();

if(y is IAnimal, IMammal Z){
    ...
}

````

As noted above, this keeps the syntax similar to that of constraints.

**Comment by Pzixel** [comment] 2017-01-04 15:11
@TonyValenti it's ruining current C# style so it won't be applied. We have two syntaxes: C-like when you declare type and then variable name, and Pascal-like, when you are specifying it after variable name. The latest is used in languages with strong type inference, and C# 1.0 wasn't it. Thus, we will have C-style until C#'s death.

So answering your question, it's just easy to forbid explicit type specification in those cases (like it is for anonymous types). So it's qute easy:

```csharp
var x = (object) Something();
var y = (IAnimal, IMammal) x;
var z = x as IAnimal, IMammal;
```

**Comment by Pzixel** [comment] 2017-01-06 13:53
@HaloFour 

> The compiler would emit a local for each type, assign them all to the same instance and silently switch between the locals depending on the context of its use. I initially thought that this might be an issue, especially if y was passed to a method as ref, but since pattern variables are readonly I don't think that would be an issue.

But what if we call a method where both aspects are required? I think this feature should generate following interface intersection and add it to all classes which implements both of them. It's probably better than generate interface on the fly and it's defenitly solves the problem with, for example, `IDisposableList`:

```csharp
if (a is (IList<int>, IDisposable) disposableList)
{
   Consume(disposableList);
}

...

public void Consume<T, TList>(T list) where T : IList<TList>, IDisposable
{
    var index = list.IndexOf(default(TList));
    list.Dispose();
}
```

There is no way to do it with `silent switch`

**Comment by HaloFour** [comment] 2017-01-06 14:16
@Pzixel 

It'd be doable, but it'd be messy.  I don't know that the compiler would have a choice but to resort to reflection to obtain the open generic type/method and then close it with the original type of `a`.  Then the compiler would invoke the member dynamically.  It would carry a bit of overhead.

Another option would be for the compiler to emit a proxy type which does meet the constraint and to use the generic type/method with that proxy type.  That would eliminate the overhead of reflection but the consuming code would be dealing with a different type which could have other unwanted consequences.

I don't see how the compiler could ever support that correctly without the CLR understanding the concept of intersection types.  Otherwise there's no way for the compiler to correctly close that generic at compile-time.

**Comment by jnm2** [comment] 2017-01-06 14:22
I'm pretty sure that this would just end up being frustrating without CLR support.

**Comment by Pzixel** [comment] 2017-01-06 14:29
@HaloFour I see your point. For example we may ask for `if (a is (IFoo, IBar) foobar)` and behaviour may differs based on if there is `IFooBar` interface and we can use it or we should generate another one? I think there is simple answer: just generate a proxy interface always. It's fine with anonymous types, why not generate anonymous interfaces? If user whant specific interface it always can manually cast to `IFooBar` instead of `(IFoo, IBar)`, so if it writes this code, it's explicitely asks us to generate some proxy interface for him just because he is too lazy to write `IQuadrupedMammalReallyWeirdFromAustralia`

**Comment by HaloFour** [comment] 2017-01-06 15:04
@Pzixel 

I don't understand what a generated composite interface would accomplish?  If the underlying type doesn't implement that interface it still couldn't be cast to it or used as a generic type argument.

That also doesn't take into account the possibility of base types being included in the intersection.

**Comment by Pzixel** [comment] 2017-01-06 15:46
@HaloFour it would accomplish situation, when you need methods from interfaces IA and IB, but there is no common divider for them. And underlying type can't implement an interface which is does not exist yet. And this is exactly what we are trying to do: allow compiler to generate this interface for us.

> That also doesn't take into account the possibility of base types being included in the intersection.
That's not true. I said `Always generate another interface`. So if there is already an `IFooBar` interface we just ignore it because it may add additional methods which is NOT what type intersection is.

**Comment by HaloFour** [comment] 2017-01-06 16:00
@Pzixel 

I still don't understand what you're proposing there.  Are you suggesting that if you try to convert to `(IFoo, IBar)` that the compiler would automatically emit a new composite interface which implements both interfaces as well as a proxy class which implements the composite interface and dispatches the methods to the underlying type?

And I don't understand your response about base types.  Are you suggesting that base types cannot participate in type intersection?  Why not?

```cs
public interface IFizz { ... }
public class Foo { ... }
public class Bar : Foo, IFizz { ... }

object o = new Bar();
if (o is (Foo, IFizz) fooFizz) {
    ...
}
``` 

How would compiler-generated composite interfaces or proxies help there?

**Comment by Pzixel** [comment] 2017-01-06 16:44
@HaloFour no, I'm suggesting proxy-interface generation only.

For example I'm writing following method:

```csharp
public void Consume<T, TItem>(T list) where T : ICollection<TItem>, IReadOnlyList<TItem>
{
    bool hasDefaultItem = list.Contains(default(TItem));
    var something = list[10];
}
```

We can not use it with type `List<T>`, because it implements both `ICollection<T>` and `IReadOnlyList<T>`. We also have our own class which implements them:

```csharp
class CollectionReadOnlyList<T> : ICollection<T>, IReadOnlyList<T>
{
    ...
}
```

Now the question is how can we call this method?

```csharp
object obj = GetListOrOurOwnCollection();
var collectionAndReadOnlyList = obj as ???
if (collectionAndReadOnlyList != null)
{
   Consume(collectionAndReadOnlyList )
}
```

I propose automatic generation of interface intersection which allows us to write something like:

```csharp
object obj = GetListOrOurOwnCollection<int>();
var collectionAndReadOnlyList = obj as (ICollection<int>, IReadOnlyList<int>)
if (collectionAndReadOnlyList != null)
{
   Consume(collectionAndReadOnlyList )
}
```

Today we only can do something like:

```csharp
object obj = GetListOrOurOwnCollection<int>();
var list = obj as List<int>;
if (list != null)
{
   Consume(list)
}
else
{
   var ourOwnCollection = obj as CollectionReadOnlyList<int>;
   if (ourOwnCollection != null)
   {
      Consume(list)
   }
   else
   {
      var somethingElse = obj as SomethingElseThatImplementsThoseInterfaces<int>;
      ...
   }
}
```

We can't modify built-in collection and make `List<T>` implement `CollectionReadOnlyList<T>`, but it obviosly implements it, because if it implements `ICollection<T>` and `IReadOnlyList<T>`, it defenitly implements both. So we don't have to write it explicitely, compiler is great in such things like this one, it can infer all combinations of all interfaces inherited.

**Comment by HaloFour** [comment] 2017-01-06 16:54
@Pzixel 

> We can't modify built-in collection and make `List<T>` implement `CollectionReadOnlyList<T>`, but it obviosly implements it, because if it implements `ICollection<T>` and `IReadOnlyList<T>`, it defenitly implements both.

Not according to either C# or the CLR.  `List<T>` would be required to directly implement `ICollectionReadOnlyList<T>` itself, it doesn't matter that it already implements `ICollection<T>` and `IReadOnlyList<T>` separately.

The only way that would work would be if the C# compiler *also* created a proxy class which implements this generated composite interface and then dispatched all of the member calls to the underlying reference.  But then you're no longer dealing with ` List<T>`.

**Comment by jnm2** [comment] 2017-01-06 17:04
> The only way that would work would be if the C# compiler also created a proxy class which implements this generated composite interface and then dispatched all of the member calls to the underlying reference. But then you're no longer dealing with List<T>.

Yes, and imagine the side effects: just by casting to an intersection, you end up passing a different instance around. Even worse if this is done implicitly.

**Comment by Pzixel** [comment] 2017-01-06 17:46
@HaloFour I got your point. There is no way to object to be casted to an interface which was not added at compile time. Thus this feature is not backward-compatible and thus will be defenitly rejected. 

P.S. Now I see that it's really hard to enhance a language without breaking existing things down...

**Comment by aluanhaddad** [comment] 2017-01-14 03:31
I agree this needs CLR support to be viable.
I really want this feature as I've indicated in many comments, but CLR support is a must.
I really hope the next version of the language looks into questions like this and seriously considers this and many other features that require changes to the CLR.

**Closed** 2018-09-27 21:14 UTC
Labels: 1 - Planning, Area-Language Design, Feature Request
