### ISSUE TITLE
VB: Can't use string comparison expressions for conditional breakpoints.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#21879] opened 2017-09-01 19:11 UTC
**Version Used**: 

Visual Studio 2017 Community 15.3.2

**Steps to Reproduce**:

Create a VB console project and type in the following code:

```vb
Module Module1
  Sub Main()
    For Each s In {"a", "b", "c"}
      Console.WriteLine(s)
    Next
  End Sub
End Module
```

Put a breakpoint on `Console.WriteLine()` and set the conditional expression to `s = "b"`:

![vs_conditional_breakpoint_withstr1](https://user-images.githubusercontent.com/20465797/29984055-36cb8828-8f61-11e7-8150-f41204bc206d.png)

Press the Close button, then run the code. You get the following error message:

![vs_conditional_breakpoint_withstr2](https://user-images.githubusercontent.com/20465797/29984086-6c130de4-8f61-11e7-981f-e63cd1befdc6.png)

**Expected Behavior**:

It should be possible to use string comparison expressions like we can with any other kind of expression (e.g. the expression `s.Length = 1` works just fine because it is comparing two integers).

**Actual Behavior**:

As shown above: we get an error message.

**Comment by ivanbasov** [comment] 2017-10-05 01:47
dupe of  #17936

**Closed by ivanbasov** 2017-10-05 01:47 UTC
Labels: Area-Interactive, Interactive-Debugging
