### ISSUE TITLE
C# Intellisense Suggestion - Hide GET only properties from intellisense inside object initalizer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41546] opened 2020-02-10 18:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/900532/c-intellisense-suggestion-hide-get-only-properties.html)._

---
When using an object initializer GET only properties aren't valid so they shouldn't be suggested by intellisense.

```
public class Example
{
    public Example()
    {
        var exampleInitializer = new ExampleInitializerClass
        {
            Property1 = "prop 1",
            Property2 = "prop 2",
            GetOnlyProperty // This can't be set and clutters the intellisense suggestions
        };
    }
}

public class ExampleInitializerClass
{
    public string GetOnlyProperty => "Example";

public string Property1 { get; set; }
    public string Property2 { get; set; }
}
```

---
#### Fiona Niu[MSFT] on 2/3/2020, 07:53 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment] 2020-02-10 20:21
NOte: get-only properties are totally fine and legal to reference here in some cases.  For example:

```c#
class Customer
{
    public List<Order> Orders { get; } = new List<Order>();
}

// ...

new Customer
{
    Orders = { ... }
}

// Also:

class Point { public int X, Y }

class Shape
{
    public Point Origin { get; } = new Point();
}

// ...

new Shape
{
    Origin = { X = 1, Y = 2 }
}
```

**Comment by sharwell** [comment] 2020-02-12 20:31
Duplicate of #22816

**Closed by sharwell** 2020-02-12 20:31 UTC
Labels: Area-IDE, Developer Community
