### ISSUE TITLE
'Configure severity' has no effect

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#45662] opened 2020-07-05 23:46 UTC
**Version Used**: 16.7-p3.1 and @mikernet reports the same on 16.6.3.

This persists across reboots. There is a single existing .editorconfig file next to a single .sln file in the repo root. The .editorconfig is linked from the 'Solution Items' folder of the solution.

No matter which 'Configure severity' option you choose, nothing happens. The menu is being invoked on a file that is not yet tracked by Git (it's showing as added in Visual Studio's Git window).

![image](https://user-images.githubusercontent.com/8040367/86544703-1b279580-bef7-11ea-8684-92acfd262568.png)

File structure:

```
│   .editorconfig
│   .gitattributes
│   .gitignore
│   GenerateRefAssemblySource.sln
│
└───GenerateRefAssemblySource
    │   Extensions.cs
    │   FlagsEnumSolver.cs
    │   GeneratedBodyOptions.cs
    │   GeneratedBodyType.cs
    │   GenerateRefAssemblySource.csproj
    │   GenerationContext.cs
    │   GenerationOptions.cs
    │   GraphUtils.cs
    │   IndentedTextWriter.cs
    │   IProjectFileSystem.cs
    │   MetadataFacts.cs
    │   NamespaceOrTypeFullNameComparer.cs
    │   Program.cs
    │   ProjectFileSystem.cs
    │   SlnWriter.cs
    │   SlnWriter.WriterState.cs
    │   SourceGenerator.cs
    │   TODO.txt
    │   TypeMemberSortKind.cs
    │
    └───Properties
            launchSettings.json
```

**Comment by MeikTranel** [comment] 2020-07-06 00:04
I observed the same behavior also using the latest preview. I'm not sure whether this is more VS instead of Roslyn.

**Comment by mikernet** [comment] 2020-07-06 12:12
I can confirm that this happened to me as well. Restarting the computer did not fix the issue. The problem persisted across different solutions. 10 minutes of trying to click on the menu in different ways and debug the issue caused it to eventually start working again but I have no idea what caused the issue or fixed the issue. The "preview changes" was correctly showing the necessary changes but clicking to apply the changes closed the menu but the changes would not apply.

**Comment by mikernet** [comment] 2020-07-06 17:47
It appears as though it works when `.editorconfig` is open, otherwise it does not.

**Comment by mavasani** [comment] 2020-07-08 12:51
Duplicate of https://github.com/dotnet/roslyn/issues/45417, which has consistent repro. @mikernet is correct that the regression only seems to be for the case when .editorconfig is not open in VS. So, at least there is a workaround until the underlying regression is fixed.

**Closed by mavasani** 2020-07-08 12:51 UTC
Labels: Area-IDE, Bug
