### ISSUE TITLE
Suboptimal code for o is 42

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#22628] opened 2017-10-10 05:33 UTC
The following code causes two boxing allocations:

```csharp
public void BoxTwice(int n)
{
    if (n is 42) Console.WriteLine("n is 42");
}
```

Because the compiler generates the call to `object.Equals(42, o)`.

Similarly, if the `n` is `object`, the `is`-expression causes one boxing allocation when the similar switch statement causes no allocations:

```csharp
public void BoxOnce(object o)
{
    if (o is 42) Console.WriteLine("o is 42");
}

public void NoBoxing(object o)
{
    switch (o)
    {
        case 42:
            Console.WriteLine("o is 42");
            break;
    }
}
```
The code gen is:

```csharp
public void BoxOnce(object o)
{
    if (object.Equals(42, o))
    {
        Console.WriteLine("o is 42");
    }
}

public void NoBoxing(object o)
{
    object obj = o;
    if (obj != null)
    {
        object obj2 = obj;
        bool expr_10 = obj2 is int;
        int num = expr_10 ? ((int)obj2) : 0;
        if (expr_10 && num == 42)
        {
            Console.WriteLine("o is 42");
        }
    }
}
```

Is there any unobvious reason for this behavior or just code gen simply not optimal and can be improved in the future?

Related issue: #13247

**Comment by jcouv** [comment] 2017-10-10 06:49
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/20642
@TyOverby to confirm.

**Comment by SergeyTeplyakov** [comment] 2017-10-10 20:14
@jcouv Indeed looks like a duplicate.

**Comment by jcouv** [comment] 2017-10-10 20:19
Closing as dupe. Thanks

**Closed by jcouv** 2017-10-10 20:19 UTC
Labels: Area-Compilers
