### ISSUE TITLE
Generate Constructor shouldn't generate protected constructor if the class is sealed

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#22699] opened 2017-10-14 19:31 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2017 
Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16
Microsoft .NET Framework
Version 4.7.02556

**Steps to Reproduce**:

Define these types:

```C#
abstract class BaseClass
{
    protected BaseClass(int value)
    {
    }
}

sealed class DerivedClass : BaseClass
{

}
```

You'll get error CS1729 for `DerivedClass` since it doesn't call the base constructor. Invoke the fixer [Generate Constructor](https://github.com/dotnet/roslyn/blob/9a09a7075983765f986658294c52d90e71b9f887/src/Features/CSharp/Portable/GenerateConstructor/GenerateConstructorCodeFixProvider.cs#L46).

**Expected Behavior**:

Since `DerivedClass` is sealed it should generate a public constructor.

**Actual Behavior**:

It generates a constructor matching the base visibility, which is protected:

```C#
sealed class DerivedClass : BaseClass
{
    protected DerivedClass(int value) : base(value)
    {
    }
}
```

**Comment by lostllama** [comment] 2017-11-21 02:49
I'd argue that it shouldn't generated a protected constructor if the class is _public_. What's the point in generating a constructor that you can't use?

**Comment by terrajobst** [comment] 2017-11-21 03:02
> I'd argue that it shouldn't generated a protected constructor if the class is public. What's the point in generating a constructor that you can't use except in derived classes?

One could argue that if there are other constructors you might not want to expose the constructor as public. But if the class is sealed, protected is definitely not sensible.

That being said, I'd also be happy if the fixer would emit pubic constructors unless the class is abstract as that's what most people probably want. However, I think the visibility of the class is relevant.

**Comment by alrz** [comment] 2017-11-21 17:57
I think we should just have another analyzer to flag  `protected` and `sealed` if the type is `sealed`.

IMO the only thing that code generation features should follow is naming conventions, style preference, etc

**Comment by DustinCampbell** [comment] 2018-04-05 13:18
Related to https://github.com/dotnet/roslyn/issues/25238, which is already fixed. Is this essentially a duplicate of that one now?

**Comment by terrajobst** [comment] 2018-04-05 17:15
Not entirely sure how #25238 works but it sure looks like a dupe. 

@zaytsev-victor, does it handle this case too?

**Comment by zaytsev-victor** [comment] 2018-04-16 06:18
@terrajobst, it is already fixed in https://github.com/dotnet/roslyn/pull/25866. This should be closed.

**Comment by DustinCampbell** [comment] 2018-04-16 17:02
Thanks for checking @zaytsev-victor.

**Closed by DustinCampbell** 2018-04-16 17:02 UTC
Labels: Area-IDE, Bug
