### ISSUE TITLE
"Insert space between method name and its opening parenthesis" apper twice in the new editorConfig UI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56482] opened 2021-09-17 16:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Insert-space-between-method-name-and-it/1529701)._

---
[severity:It's more difficult to complete my work]
The `Insert space between method name and its opening parenthesis` apper twice in the new editorConfig UI, one entry is mapped to the `csharp_space_between_method_call_name_and_opening_parenthesis` directive and the other is mapped to the `csharp_space_between_method_declaration_name_and_open_parenthesis
` directive of the `.editorconfig` file

Visual Studio version info:
```
Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 4.0
VisualStudio.17.Preview/17.0.0-pre.4.0+31710.8

---
### Original Comments

#### Feedback Bot on 9/15/2021, 01:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>


---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 22:09
duplicate of https://github.com/dotnet/roslyn/issues/60232

**Closed by jmarolf** 2022-03-18 22:09 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - Editor Config UI

**Comment by Youssef1313** [comment] 2022-07-29 07:45
@jmarolf This doesn't seem like a duplicate of #60232.
