### ISSUE TITLE
Inconsistency between `!= null` and `is not null` on NRTs

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#65740] opened 2022-12-03 07:53 UTC
**Version Used**: `Compiler version: '4.4.0-6.22561.11 (1ce8866c)'. Language version: preview.`

**Steps to Reproduce**:

1. Get any type such as `record class R(int _, R Child);`
2. Declare a variable `R r = new(0, null!);`
3. Traverse the type until null with pattern matching `while ((r = r.Child) is not null) {}`
4. Traverse the type until null with `!=` check `while ((r = r.Child) != null) {}`

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

[sharplab](https://sharplab.io/#v2:C4LgpgHgDgNghgSwHYB8DESCuN4CMZgAEYSc+YAsAFDUBKhAToQLyFJgDuAFAAwA0bbDACEASgDc1DgAsEBQly5NWDAHQBhWTAAmowggDObAPbBBOPQG8AvtTqEAbizadeArDjGSqMuUUVOrA4aWrqEwqweMFa2NFQMYADGxgzahAACAEyEtFzIZgD6AvSacrreQA===)

**Diagnostic Id**: CS8602: Dereference of a possibly null reference.

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**: Either both loops raise a warning or neither loops raise a warning.

**Actual Behavior**: The loop with `is not null` raises `CS8602: Dereference of a possibly null reference.`, but the loop with `!=` doesn't

**Comment by Youssef1313** [comment] 2022-12-03 08:20
Looks similar to https://github.com/dotnet/roslyn/issues/59152

@RikkiGibson Is this a duplicate?

**Comment by RikkiGibson** [comment] 2022-12-03 18:46
I think so.

**Comment by RikkiGibson** [comment] 2022-12-06 19:21
Duplicate of #59152. Thanks for filing this issue. It does help us get a sense of the impact of the bug.

**Closed by RikkiGibson** 2022-12-06 19:21 UTC
Labels: Bug, Resolution-Duplicate, Area-Compilers, New Language Feature - Nullable Reference Types
