### ISSUE TITLE
Crash in suppression

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#38865] opened 2019-09-26 00:50 UTC
Not sure how to repro this.

Got this error:

```

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: length   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)   at
 Microsoft.CodeAnalysis.CodeFixes.Suppression.AbstractSuppressionCodeFixProvider.PragmaHelpers.NormalizeTriviaOnTokens(AbstractSuppressionCodeFixProvider fixer, Document& document, SuppressionTargetInfo& suppressionTargetInfo)   at
 Microsoft.CodeAnalysis.CodeFixes.Suppression.AbstractSuppressionCodeFixProvider.<GetSuppressionsAsync>d__30.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.CodeFixes.Suppression.AbstractSuppressionCodeFixProvider.<GetSuppressionsAsync>d__28.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at
 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```

**Comment by CyrusNajmabadi** [comment] 2019-09-26 00:51
Tagging @mavasani

**Comment by sharwell** [comment] 2019-10-01 18:16
Duplicate of #11173

**Closed by sharwell** 2019-10-01 18:16 UTC
Labels: Area-IDE
