### ISSUE TITLE
Spaces are not ignored in declaration statements

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31868] opened 2018-12-17 18:00 UTC
**Version Used**: 16.0 Preview 1

🔗 https://developercommunity.visualstudio.com/content/problem/83437/ignore-spaces-in-declaration-statements.html

**Steps to Reproduce**:

1. Add a **.editorconfig** with the following setting:

    ```ini
    csharp_space_around_declaration_statements = ignore
    ```

2. Add a declaration statement with more than one space between the type and variable name
3. Run a **Format Document** operation

**Expected Behavior**:

The multiple spaces are preserved in the declaration statement.

**Actual Behavior**:

The multiple spaces are collapsed to one space in the declaration statement.

📝 Note that spaces are ignored around field declarations for the above setting, but this issue relates to declaration statements, i.e. local variable declarations within a member.

**Comment by sharwell** [comment] 2019-04-09 23:09
@jinujoseph We were not able to reproduce this bug in the latest releases of Visual Studio 2017 or 2019. Can you work with the InternalAsk user(s) to get more specific information about how to reproduce the issue?

**Comment by chborl** [comment] 2019-04-09 23:35
Here's a gif of the issue.  I moved the curly brace back, then [Format]([url](url)) Document.  The spacing is retained.  

![SpaceInDeclarationStatement_ignore](https://user-images.githubusercontent.com/25776963/55841769-734dcd00-5ae5-11e9-9896-a7e228f018e7.gif)

**Comment by vatsalyaagrawal** [comment] 2019-04-10 22:45
Synced offline and provided repro. Please let me know if more information is needed.

**Comment by chborl** [comment] 2019-04-11 23:52
Thanks, @vatsalyaagrawal.  It appears these two editor config settings are conflicting with each other:
`csharp_space_around_declaration_statements = ignore`
`csharp_preserve_single_line_statements = false`

If I remove the second one, the issue does not occur.  I'll look into it further.

**Comment by LeeMSilver** [comment] 2019-04-29 23:29
Same problem here. Note that this was originally reported on 7/20/2017 - close to 2 years ago. I fully realize man-power has to be allocated carefully, but this seems to me to be a fairly simple to fix - especially as the option works for Fields and only fails for Locals.

**Comment by CyrusNajmabadi** [comment] 2019-04-30 16:52
>but this seems to me to be a fairly simple to fix 

@LeeMSilver Would you be interested in contributing a fix? Roslyn is open source after all :)

**Comment by LeeMSilver** [comment] 2019-05-01 00:29
Cyrus: Since the apparent cause is conflicting options I believe the problem is in VS and not in Roslyn.

**Comment by CyrusNajmabadi** [comment] 2019-05-01 00:48
@LeeMSilver Seems unlikely here... all this woudl fall under the Roslyn umbrella unless i've missed something.

**Comment by jinujoseph** [comment] 2019-05-02 22:20
fixed via https://github.com/dotnet/roslyn/pull/34959

**Closed by jinujoseph** 2019-05-02 22:20 UTC
Labels: Area-IDE, Bug, Developer Community, InternalAsk, Resolution-Fixed

**Comment by LeeMSilver** [comment] 2019-05-22 23:36
Thanks much guys.
In VS 16.1 this now works as expected (and identically to VS2010)
