### ISSUE TITLE
No completion after dot inside async lambda

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#25356] opened 2018-03-08 21:46 UTC
Copied from https://github.com/OmniSharp/omnisharp-vscode/issues/2097
C# extension for VS Code just uses CompletionService API, so porting this to Roslyn.

Use dotnet's "Web" template to write code in "Startup.cs" in the following cases: 

```csharp
app.Run(async (context) =>
            {
                context.Items.<There is not anything appear!!>
                await context.Response.WriteAsync("Hello World!");
            });
but when you writer this:
app.Run(async (context) =>
            {
                context.Items.<Add a semicolon at the end of the line beforehand,and it would be ok>;
                await context.Response.WriteAsync("Hello World!");
            });
```

**Comment by rchande** [comment] 2018-03-08 21:46
cc @jinujoseph

**Comment by Neme12** [comment] 2018-03-09 10:15
sounds like a duplicate of #23798

**Comment by Neme12** [comment] 2018-03-09 10:24
also possibly #4474

**Comment by sharwell** [comment] 2019-03-28 13:26
Duplicate of #4474

**Closed by sharwell** 2019-03-28 13:26 UTC
Labels: Area-IDE, Bug
