### ISSUE TITLE
Improve error messages for portable class libraries created when NuGet is disabled.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#23399] opened 2017-11-27 18:08 UTC
**Version Used**:

Visual Studio Community 2017 v15.4.4

**Steps to Reproduce**:

Under Tools > Options > NuGet Package Manager > General, make sure `Allow NuGet to download missing packages` is NOT checked:

![vs_nuget_disabled](https://user-images.githubusercontent.com/20465797/33280731-19cf1482-d3b4-11e7-9088-677d99475a70.png)

Now create a new solution with a portable class library targeting .NET Standard and you should see something like this in Solution Explorer:

![vs_portable_class_library_error](https://user-images.githubusercontent.com/20465797/33280841-711f68c2-d3b4-11e7-9719-cd69ace44560.png)

Looking at the Error List window reveals really strange error messages:

![vs_portable_class_library_error_messages](https://user-images.githubusercontent.com/20465797/33280988-d1148938-d3b4-11e7-825f-1ff8d45f64cf.png)

...I say strange error messages because types like `System.Void` and `System.String` have never ever been user-defined. They are always "just there" as a standard part of the .NET Framework.

**Expected Behavior**:

It is really difficult to figure out what to do in this case unless you somehow know that targeting the .NET Standard requires NuGet packages to be available. After scratching my head for an hour, I finally remembered that I had disabled automatic restore of NuGet packages. After ticking the `Allow NuGet to download missing packages` option described earlier, I was able to restore the packages and the error messages all went away.

One of two things should be done instead: either automatically restore NuGet packages when a portable library project is created so users don't have to even think about it...or modify the compiler error messages when fundamental types such as `System.String` are missing (perhaps the messages could hint "are you missing some NuGet packages or assemblies?").

**Comment by jcouv** [comment] 2017-11-27 20:50
Relates to https://github.com/dotnet/roslyn/issues/16810

**Comment by jcouv** [comment] 2017-11-28 03:51
I'll go ahead and close as duplicate of #16810. We'll reduce the number of errors in such cases, and try to improve the error message ("are you missing a reference to mscorlib, or forgot to restore the NuGet packages?").

**Closed by jcouv** 2017-11-28 03:51 UTC

**Comment by ericmutta** [comment] 2017-11-28 03:52
@jcouv many thanks for following up, sounds good 👍
