### ISSUE TITLE
Refactoring essentials analyzer crashed Visual Studio on 2.0 because they have not implemented VisitLocalFunctionStatement

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#13820] opened 2016-09-15 10:41 UTC
**Steps to Reproduce**:

1. Install Refactoring essentials nuget package
2. Create a local function in a C# project in visual studio

**Expected Behavior**:
Refactoring essentials is built against Microsoft.CodeAnalysis 1.2.0 which should continue to work under 2.0.  Even if the analyzer crashes because it does not expect local functions it should not be able to bring down Visual Studio

**Actual Behavior**:
Refactoring essentials [throws NotSupportedException](https://github.com/icsharpcode/RefactoringEssentials/blob/879f8e796bdaefd83771552a30ae8adc777804b4/RefactoringEssentials/Util/Analysis/ControlFlow.cs#L353) which crashes visual studio.  
```
   at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.HandleStatementList(IEnumerable`1 statements, ControlFlowNode source)
   at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(StatementSyntax statement, SemanticModel typeResolveContext, Func`3 resolver, CancellationToken cancellationToken)
   at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(StatementSyntax statement, SemanticModel resolver, CancellationToken cancellationToken)
   at RefactoringEssentials.Util.Analysis.ReachabilityAnalysis.Create(StatementSyntax statement, SemanticModel resolver, RecursiveDetectorVisitor recursiveDetectorVisitor, CancellationToken cancellationToken)
   at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.GatherVisitor.VisitBody(String entityType, SyntaxToken markerToken, StatementSyntax body, ISymbol symbol, SyntaxKind accessorKind)
   at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.GatherVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.<>c__DisplayClass3_0.<<Initialize>b__1>d.MoveNext()
```

**Comment by mavasani** [comment] 2016-09-16 15:39
Dupe of VSO 237576

**Closed by mavasani** 2016-09-16 15:39 UTC
Labels: Area-Analyzers, Bug

**Comment by mavasani** [comment] 2016-09-16 15:41
I meant dupe of https://github.com/dotnet/roslyn/issues/13120
