### ISSUE TITLE
Navigating to an analyzer issue causes the issue to disappear for a few seconds making me lose confidence in the product

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31038] opened 2018-11-08 05:55 UTC
This issue has bothered me for a while, if I navigate to an issue, Roslyn appears to retag/scan/analyze the file resulting in issues that disappear momentarily only to come back. This does not happen for compiler errors or warnings, only for analyzers.

The larger the file, the longer this process takes. This makes me lose confidence in the product.

![slow](https://user-images.githubusercontent.com/1103906/48180184-a2191900-e376-11e8-8164-3e1eb55ed0ed.gif)

**Comment by davkean** [comment] 2018-11-08 06:47
This also has the following behavior "weirdness":

- The first time you navigate, instead of a lightbulb showing it's a screwdriver:
![image](https://user-images.githubusercontent.com/1103906/48182111-2d49dd00-e37e-11e8-96c1-0783956937ad.png)

- If you drop down the lightbulb/screwdriver too fast or at the "wrong time", the code fix sometimes doesn't even show up:
![image](https://user-images.githubusercontent.com/1103906/48182147-4e123280-e37e-11e8-86d9-8f02465fc0c6.png)

**Comment by CyrusNajmabadi** [comment] 2018-11-08 08:03
@davkean Are you only seeing this with the new "remove unused member" analyzer?  Or are you seeing it with others as well?

Tagging @mavasani .  Maybe some race condition in the new code to do symbol start/stop analysis?

**Comment by davkean** [comment] 2018-11-08 08:06
I've noticed it since we added the ... (likely filed bugs back then), but it's got more noticeable with the new analyzers.

**Comment by CyrusNajmabadi** [comment] 2018-11-08 08:07
Do you mean the `...` in the `Error list ...` title?  Thanks!

**Comment by CyrusNajmabadi** [comment] 2018-11-08 08:08
Tagging @heejaechang as well. This may be an issue in the analyzer driver.

**Comment by davkean** [comment] 2018-11-08 08:08
The ... in the editor.

**Comment by CyrusNajmabadi** [comment] 2018-11-08 08:13
Sorry, not trying to be dense, but i'm not sure what you're referring to?  Can you draw a box around what `...` you're referring to in the editor?

**Comment by davkean** [comment] 2018-11-08 08:15
![image](https://user-images.githubusercontent.com/1103906/48185919-9b949c80-e38a-11e8-8dca-d0252b3fce46.png)

This the first time I noticed it because something visibly changed to the editor.

**Comment by CyrusNajmabadi** [comment] 2018-11-08 08:19
Oh sorry.  I totally didn't even make that connection.  Thanks for clearing htat up.  Sorry for the brain fart.

We may have to examine your project.  I haven't experienced this behavior myself.  When i open files i may see things unadorned, but then they switch from that to showing all these analyzer results.  I have not experienced the "adorned/unadorned/adorned" behavior you show in your gif.  That's definitely not good and should be tracked down.  Thanks for the report!

**Comment by davkean** [comment] 2018-11-08 08:21
It's only if the document hasn't been opened before.

**Comment by davkean** [comment] 2018-11-08 10:01
That checkbox is enabled by default for VB, but yes I have it on.

**Comment by sharwell** [comment] 2018-11-08 16:07
Tagging @mavasani in case this behavior is specific to symbol end analyzers

**Comment by mavasani** [comment] 2018-11-08 17:21
I think @heejaechang can confirm/explain the behavior with certainty, but I feel the IDE behavior has been the same for quite a while:
1. IDE computes all live diagnostics and populates the error list 
2. User edits some source file in the project which essentially invalidates all the diagnostics for that project (and possibly referencing projects), but we don't instantly clear the error list.
3. User double clicks any of the existing diagnostic from error list (from prior compilation) which opens a source file.
4. IDE diagnostic service prioritizes diagnostic computation for the opened file by first clearing all the diagnostics for that file (which removes all the squiggles, fading, etc.) and then force complete the live analysis for it on a higher priority queue.
5. Once this finishes it adds back the diagnostics to the system and you can see the squiggles, fading, up-to-date error list diagnostics for that file.

Step 4. is generally instantaneous for compiler diagnostics for the file (`SyntaxTree.GetDiagnostics` and `SemanticModel.GetDiagnostics`) and is also instantaneous for all analyzers that require just to re-analyze the opened file to recompute diagnostics. The update is not instantaneous for compilation end analyzers as it needs to re-analyze whole compilation, but none of the IDE analyzers are compilation end analyzers. With the new dead code analyzer (and any symbol start/end analyzer), the update time is somewhat in between these two buckets as it needs to re-analyze the opened file and all partial definitions for types in opened file before it can report diagnostics. This is expected as the analysis scope is slightly bigger then the current file, and depends on the number of partial definitions for the opened file. Note that the IDE experience here is already known in prior VS versions for existing third party compilation end analyzers, and has in fact a much slower refresh. I am not sure if we can do much more then fine tune the overall diagnostic computation/background analysis perf so it is overall faster for this issue.
I would let @heejaechang still confirm if this is indeed the correct reasoning for this IDE refresh behavior.

**Comment by CyrusNajmabadi** [comment] 2018-11-08 17:46
@mavasani I would say that there should be some investment here.  I just tried this out with loading Roslyn in an Roslyn-hive and i observed teh behavior that @davkean mentioned.  It's fairly obvious and distracting.  It would be akin to opening a file and having classification flicker.  While it's not great that you can open a file and go from unclassified->classified.  It's much work to go classified->unclassified->classified.  I'm with Dave that it actually makes the product feel unstable.

At the very least, can we make it so that this particular set of operations is somehow recognized by the analyzer system and tuned a little more finely?  i.e. if we have opened a file, don't *clear* adornments until we get the most up to date version of things.  That way, things go from "Stale->correct", instead of "stale->gone->correct".  The "gone" part is the particularly unpleasant thing here.

Thanks!

**Comment by mavasani** [comment] 2018-11-08 18:21
@heejaechang is the expert in this area, so I will let him give more affirmative answers, but I think the challenge is that we leave the stale diagnostics in the system while the latest are being computed, then not only the user will see the stale diagnostics, but even the code fixer's RegisterCodeFixesAsync will get invoked with stale diagnostics for computing the light bulb preview on Ctrl + Dot. I recall @heejaechang had actually proposed once that we invoke the code fix with a stale diagnostic for computing the light bulb preview for a better experience with compilation end diagnostic's code fix. The primary risk is what if user edit had actually changed the original syntax node on which diagnostic was reported and the code fixer is not resistant enough to handle stale diagnostics from an older snapshot. Other minor side effect could be that preview shows the diagnostic can be fixed but attempting to apply it is a no-op as the actual code action will be invoked with latest diagnostics from the new snapshot, and that diagnostic may no longer exist, but I think that is acceptable experience.

@heejaechang Do you think it is a big task to prototype this approach? If not, we can try out an experimental VSIX with this change and see if the experience is better. If so, we basically need to make sure that all IDE code fixers are hardened for the stale diagnostic scenario, which I presume most of them should be, but @CyrusNajmabadi can confirm.

**Comment by mavasani** [comment] 2018-11-08 18:35
Tagging @jinujoseph as we have discussed about the stale diagnostics approach before and it might be worth a quick prototype/dogfood experience. It will also potentially improve the code fix experience for compilation end diagnostics, which is currently ever worse then the issues discussed here.

**Comment by CyrusNajmabadi** [comment] 2018-11-08 19:13
Note: we may have to separate out the different types of diagnostics.  For example, diagnostics that actually change the UI in some way (i.e. by fading out) may need to stay versus diagnostics that don't.

**Comment by davkean** [comment] 2018-11-09 03:52
Just a point of clarification; while it doesn't show it above, this repros even when ... has disappeared from the Error List, ie everything is up-to-date.

**Comment by heejaechang** [comment] 2018-11-19 23:38
need to take a look, but error gets removed and come back probably due to data being reset on file open. + the work we did due to some complaints from users saying errors don't go away fast enough after fixing and errors come in too fast while typing. for that, we made errors go away faster and errors comes in slower.

**Comment by heejaechang** [comment] 2018-11-19 23:39
> User edits some source file in the project which essentially invalidates all the diagnostics for that project (and possibly referencing projects), but we don't instantly clear the error list.

that will make error list flicker like when file is opened. we only clear it when new data came.

**Comment by heejaechang** [comment] 2018-11-19 23:45
so request is

1. remove the flickering and 2. make sure symbol end analyzer get synchronously calculated on ctrl+.? (@mavasani what symbol end analyzer return for this?
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs,408 - if it doesn't return block then it will act like compilation end analyzer)

I don't think we will ever calculate compilation end analyzer synchronously on ctrl+.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:00
Closing out as these experiences were all entirely rewritten.

**Closed by CyrusNajmabadi** 2024-10-19 21:00 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Concept-Design Debt
