### ISSUE TITLE
Source generated documents should be opened in the real workspace instead of Miscellaneous files

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#50676] opened 2021-01-21 18:44 UTC
Some tasks for the implementation

- [ ] Ensure the active document tracking is correctly updated.
- [ ] Ensure the Navigate To support for prioritizing open documents works.
- [ ] Fix https://github.com/dotnet/roslyn/issues/56998
- [ ] Fix https://github.com/dotnet/roslyn/issues/57082

**Comment by jasonmalinowski** [comment] 2021-05-10 22:36
The core of this is done under a feature flag, moving to 16.11 for the rest of the todo items.

**Comment by jasonmalinowski** [comment] 2021-09-13 18:57
The feature checkbox is there, we're targeting 17.1 for enabling it by default.

**Comment by jasonmalinowski** [comment] 2022-03-23 01:10
The checkbox is there, but we've fixed enough in 17.2 that we don't want to turn it on late. It'll be turned on by default in 17.3.

**Comment by CyrusNajmabadi** [comment] 2023-03-07 23:55
This seems to be done:

![image](https://user-images.githubusercontent.com/4564579/223582506-29a3e9d7-61fa-487d-acff-a063bd983ecf.png)

Closing out.

**Closed by CyrusNajmabadi** 2023-03-07 23:55 UTC
Labels: Area-IDE, Concept-Continuous Improvement

**Comment by Sergio0694** [comment] 2023-04-04 12:45
This doesn't seem to be completely fixed, I just reproed this with 17.5.3:

![image](https://user-images.githubusercontent.com/10199417/229795392-80c88fa7-8658-4c77-9279-c94d63d09fcc.png)

Ended up here by F11 stepping into a method that called a generated one while debugging (after hitting a breakpoint in the manually written method that invoked the generated one). VS went into this file and let me continue debugging (eg. with F10 to go line by line), but the file was still classified as "miscellaneous", and IntelliSense was half broken (eg. CTRL + click and F12 didn't work at all and wouldn't let me jump to selected symbols, such as other generated members the code is using).

**Comment by jasonmalinowski** [comment] 2023-04-07 21:43
@Sergio0694 Do you have this unchecked in Tools > Options?

![image](https://user-images.githubusercontent.com/201340/230682294-e4d158aa-925d-48b7-8c18-ccf184310000.png)

We've rolled out the feature flag to all users at this point (unless I broke something), but if you had manually turned it off at some point you might not see it active.

**Comment by Sergio0694** [comment] 2023-04-07 21:46
Yup, I have that option set 🥲

**Comment by jasonmalinowski** [comment] 2023-04-07 21:48
Was this the file that the debugger opened? Can you copy/paste in the path that the file is? You can redact the filename and username, I'll be looking at exactly where under %TEMP% or similar it is.

**Comment by Sergio0694** [comment] 2023-04-07 22:15
The file is in:

> "C:\Users\<USERNAME>\AppData\Local\Temp\.vsdbgsrc\8A80FD2566EE423D4F1DDB6B1DA2EBF7C81E2489"

I can confirm the repro steps are pretty easy at least, if that helps:
- Source generate some method/property/whatever
- Step into it with F11 from some normal code

That'll open the generated file in miscellaneous mode, from that path.

Also should we reopen this, or should I open a different issue to track this? 🙂
And thank you for looking into this!
