### ISSUE TITLE
IDE0016 incorrectly reorders statements, introducing behavioral change

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38082] opened 2019-08-18 01:06 UTC
**Version Used**: 
3.3.0-beta3-19413-06+ac06df1bffb7b7fd0e5bf63cc91921af76b21e03

**Steps to Reproduce**:
```C#
using System;

class Program
{
    static void Main() { }

    static void DoWork(string value)
    {
        if (value == null) throw new ArgumentNullException(nameof(value));
        DoExpensiveWork();
        if (IsInconsistentState) throw new InvalidOperationException();
        Value = value;
    }

    public static string Value { get; private set; }

    static void DoExpensiveWork() { }
    static bool IsInconsistentState => false;
}
```
Run the offered IDE0016.

**Expected Behavior**:
IDE0016 is not offered.

**Actual Behavior**:
IDE0016 is offered, and running it changes the code to:
```C#
static void DoWork(string value)
{
    DoExpensiveWork();
    if (IsInconsistentState) throw new InvalidOperationException();
    Value = value ?? throw new ArgumentNullException(nameof(value));
}
```
This is bad for several reasons:
1. It's changing the order in which exceptions could occur.
2. It's resulting in a bunch of work being done that should have been avoided.
3. Both of those more generally mean it's changing program behavior.

(I could have sworn I opened an issue on this a while ago, but I can't find it now.  It just bit me again, though, so I'm opening one in case that one is lost somewhere.)

**Comment by sharwell** [comment] 2019-08-19 14:50
Duplicate of #36177

**Closed by sharwell** 2019-08-19 14:50 UTC
Labels: Area-IDE
