### ISSUE TITLE
Implicitly typed lambdas with `[UnscopedRef]` don't match their own anonymous delegate types

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#63565] opened 2022-08-24 15:14 UTC
**Version Used**: 
```
commit e041ae9802b68f7c6f6903ec92b56d27ff0caec3
Author: Youssef Victor <youssefvictor00@gmail.com>
Date:   Wed Aug 24 16:00:43 2022 +0200

    Delete extra character in Syntax.xml (#63561)
```

**Steps to Reproduce**:

```cs

using System.Diagnostics.CodeAnalysis;

public ref struct RefStruct { }
public struct RegularStruct { }

delegate void D1([UnscopedRef] ref RefStruct s);
delegate void D2([UnscopedRef] out RegularStruct s);

public class C
{
  public void M()
  {
    var x = ([UnscopedRef] ref RefStruct s) => { }; // error CS8986: The 'scoped' modifier of parameter 's' doesn't match target '<anonymous delegate>'.
    var y = ([UnscopedRef] out RegularStruct s) => { }; // error CS8986: The 'scoped' modifier of parameter 's' doesn't match target '<anonymous delegate>'.
    D1 q = ([UnscopedRef] ref RefStruct s) => { };
    D2 w = ([UnscopedRef] out RegularStruct s) => { };
  }
}

namespace System.Diagnostics.CodeAnalysis
{
  [AttributeUsage(AttributeTargets.All, Inherited = false)]
  internal sealed class UnscopedRefAttribute : Attribute
  {
    public UnscopedRefAttribute()
    {
    }
  }
}
```

**Expected Behavior**:
No errors for lambda expressions assigned to `var` variables. The anonymous delegates created for them should have `[UnscopedRef]` annotations on their parameters

**Actual Behavior**:
Lambda expressions with completely valid signatures (as demonstrated by `D1`, `D2` and corresponding lambda expressions) produce errors due to mismatches with their own implicit types

**Comment by TessenR** [comment] 2022-11-23 17:55
The same behavior again in the latest main branch:

```
commit ce5e3f27fd426447a4780c530e77f6a7515cdbe9
Author: Ankita Khera <40616383+akhera99@users.noreply.github.com>
Date:   Tue Nov 22 14:28:17 2022 -0800
```

Compile the following code:
```

using System.Diagnostics.CodeAnalysis;

struct EmptyStruct { }

class C
{
  static void Main(string[] args)
  {
    var a = ([UnscopedRef] ref int x, ref int y) => ref y;
  }
}
```

Expected result: compiles without errors
Actual result: `error CS8986: The 'scoped' modifier of parameter 'x' doesn't match target '<anonymous delegate>'.`

@AlekseyTs will you reopen this issue or should I create a new one?

**Comment by AlekseyTs** [comment] 2022-11-23 19:21
@TessenR 
> The same behavior again in the latest main branch

Was it working as expected after the fix mentioned above?

**Comment by TessenR** [comment] 2022-11-23 19:29
@AlekseyTs I believe it was working at some point, but I don't remember when exactly I tried it.

I think it might be caused by the fact that `[UnscopedRef]` now can affect whether a delegate conversion or an override is valid without affecting `DeclarationScope` of parameters, i.e. in the last example both `ref int x` and `[UnscopedRef] ref int x` are considered `Unscoped`, so perhaps now it's required to propagate the attribute as well as parameters' scoped-ness

**Comment by AlekseyTs** [comment] 2022-11-23 19:34
Sounds like this is a possible regression. Apparently `ref` returns somehow make a difference.
This code is fine:
```
    var e = ([UnscopedRef]ref int x) => x;
```

But this causes error CS8986: The 'scoped' modifier of parameter 'y' doesn't match target '<anonymous delegate>'.
```
var f = ([UnscopedRef]ref int y) => ref y;
```

**Comment by AlekseyTs** [comment] 2022-11-23 21:21
>  E.g. you can observe the same behavior by adding a ref struct parameter.

If nothing is returned, the parameter doesn't cause any problems:
```
    var b = ([UnscopedRef]ref int x, EmptyStruct y) => {};
```

Perhaps return of ref structs also affecting the behavior.

**Comment by TessenR** [comment] 2022-11-23 21:32
> If nothing is returned, the parameter doesn't cause any problems:

Here's a counter example ツ
```
using System.Diagnostics.CodeAnalysis;

ref struct EmptyStruct { }

class C
{
  static void Main(string[] args)
  {
    // error CS8986: The 'scoped' modifier of parameter 'x' doesn't match target '<anonymous delegate>'.
    var b = ([UnscopedRef]ref int x, ref EmptyStruct y) => { };
  }
}
```

Anyway, right now we are just exploring when the `scoped` modifiers are validated in conversions and the condition for this is written in the method I linked above.

I believe that the error is reported when `scoped` modifiers must match (as determined by `SourceMemberContainerTypeSymbol.RequiresValidScopedOverrideForRefSafety`) and when `[UnscopedRef]` is present, because right now anonymous delegates don't seem to inherit their `[UnscopedRef]` attributes from their source lambda expressions, but "scoped override rules" take these attributes into account (as determined by `SourceMemberContainerTypeSymbol.CheckValidScopedOverride.isValidScopedConversion`)

**Comment by AlekseyTs** [comment] 2022-11-23 23:12
Sure, it appears that compiler doesn't always complain about parameter ```[UnscopedRef]ref int x```. Its presence on its own isn't sufficient for the error to appear.

**Comment by AlekseyTs** [comment] 2022-11-27 21:26
@cston It looks like this is a regression from #65153. More specifically from this change https://github.com/dotnet/roslyn/pull/65153/files#diff-f1dd35829350df4e369550b5aee43764f85e7a1233ea79e1b4df174a40e8e2dd in SourceComplexParameterSymbol.cs.

Also, the fact that an error is not reported for a simple scenario like ```var e = ([UnscopedRef]ref int x) => x;``` is likely to indicate an inconsistency between checks performed by different components/helpers, which prevents invocation of ```CheckValidScopedOverride<TArg>``` in cases when it would report a diagnostics.

**Comment by cston** [comment] 2023-01-17 19:19
Fixed in https://github.com/dotnet/roslyn/pull/66035.

**Closed by cston** 2023-01-17 19:19 UTC
Labels: Bug, Area-Compilers, New Language Feature - Ref Fields
