### ISSUE TITLE
Convert.ToString is using incorrect method overload for argument of type string in .NET Core

### ISSUE THREAD

**Issue by smitpatel** [dotnet/roslyn#14567] opened 2016-10-17 21:26 UTC
**Version Used**: 
VS 2015 Update 3

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Steps to Reproduce**:
`Program.cs`

``` C#
using System;
using System.Linq.Expressions;

namespace RoslynBug
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Expression<Func<int, string>> expression = i => Convert.ToString("");

            var outerMethodCall = expression.Body as MethodCallExpression;
            Console.WriteLine(outerMethodCall?.Method);
        }
    }
}
```

`project.json`

``` JSON
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {},

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      }
    },
    "net451": {}
  },

  "runtimes": {
    "win10-x64": {}
  }
}
```

**Expected Behavior**:

```
>dotnet run --framework net451
Project RoslynBug (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
System.String ToString(System.String)
```

**Actual Behavior**:

```
> dotnet run --framework netcoreapp1.0
Project RoslynBug (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
System.String ToString(System.Object)
```

Given that `Convert.ToString()` is being passed argument of type `String`, the method selected in `net451` is correct one. It should give same output for `netcoreapp1.0` too.

**Comment by svick** [comment] 2016-10-18 10:36
The overload `System.Convert(string)` does not exist on .Net Core 1.0.1, so the behavior you see is correct.

The overload is planned to be included in .Net Core 1.2, which is scheduled for spring 2017.

**Comment by jcouv** [comment] 2016-12-08 05:03
Closing, since this is resolved by design and I see that Smit acknowledged Paul's response.

**Closed by jcouv** 2016-12-08 05:03 UTC
Labels: Area-Compilers, Language-C#, Resolution-By Design

**Comment by smitpatel** [comment] 2017-04-20 17:52
@svick @jcouv - What minimum version of Roslyn or .NET Core (or any other CLI/SDK/Package) to get this overload available?

**Comment by jcouv** [comment] 2017-04-20 18:03
@smitpatel I think @svick already answered this above: 
> The overload is planned to be included in .Net Core 1.2, which is scheduled for spring 2017.

(note: it's possible that .NET Core 1.2 is now called .NET Core 2.0, but that's really not my area)

**Comment by smitpatel** [comment] 2017-04-20 18:16
I am using dotnet CLI 2.0.0-preview1 targeting tfm netcoreapp2.0 still I am not able to find that overload. So I am trying to find where should I look for.
```
.NET Command Line Tools (2.0.0-preview1-005815)

Product Information:
 Version:            2.0.0-preview1-005815
 Commit SHA-1 hash:  a150055dfb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\smpatel\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005815\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002028-00
  Build    : 6d0caecf154d3398b9bc0e637089b6af9e250479
```

cc: @ajcvickers

**Comment by jcouv** [comment] 2017-04-20 18:22
I see. Thanks for the clarification.
Let's ask @terrajobst and @KrzysztofCwalina: is there a planned `Convert.ToString(string)` API in .NET Core 2.0? @smitpatel does not see it in the .NET Core 2.0 preview and I cannot find it in apisof.net.

**Comment by terrajobst** [comment] 2017-04-20 19:11
Yes, `Convert.ToString(string)` will be added to .NET Core 2.0 (FKA 1.2) as part of our support of .NET Standard 2.0.

**Comment by svick** [comment] 2017-04-20 20:02
@smitpatel It works fine for me on 2.0.0-preview1-005797.

**Comment by smitpatel** [comment] 2017-04-21 16:54
@svick - Thank you. I am able to see it in 5828 build.
