### ISSUE TITLE
Formatting doesn't work on multiline object initializer

### ISSUE THREAD

**Issue by ershadbh** [dotnet/roslyn#56003] opened 2021-08-30 08:39 UTC
**Version Used**: 

**Steps to Reproduce**:

Format the following code:
```cs
                    var v = new[] 
                    {
                        new MyObject
                        {
                            MyProperty=""
                        }
                    };
```

**Expected Behavior**:
```cs
                    var v = new[] 
                    {
                        new MyObject
                        {
                            MyProperty = ""
                        }
                    };
```
**Actual Behavior**:

No formatting applied.

Note: Formatting is working in one line object initializer like:

```cs
var v = new[] { new MyObject { MyProperty = "" } };
```

**Comment by jinujoseph** [comment] 2021-09-08 18:18
Duplicate of #8269

**Closed by jinujoseph** 2021-09-08 18:18 UTC
Labels: Resolution-Duplicate, Area-IDE
