### ISSUE TITLE
Test plan for "checked operators"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#59196] opened 2022-02-01 18:56 UTC
Proposal: https://github.com/dotnet/csharplang/issues/4665

## Productivity
- [ ] QuickInfo should show whether a checked or regular operator is used

**Comment by AlekseyTs** [comment] 2022-02-11 14:15
Dupe of https://github.com/dotnet/roslyn/issues/59458

**Closed by AlekseyTs** 2022-02-11 14:15 UTC
Labels: Area-Compilers

**Comment by jcouv** [comment] 2022-02-11 18:10
It would have been better to close the other issue instead, as the present issue is the one linked from feature status page.
