### ISSUE TITLE
Rename 'class1' to 'Class1' lingers after IDE1006 fixer

### ISSUE THREAD

**Issue by RieBi** [dotnet/roslyn#74217] opened 2024-06-30 06:23 UTC
**Steps to Reproduce**:

1. Create a new Console App template project in Visual Studio using top-level instructions
2. Create a new class file in the project named 'class1.cs'
3. Use fixer for IDE1006
4. Observe the "rename 'class1' to 'Class1'" that does nothing.

**IDE1006**:

If this is a report about a bug in an analyzer, please include the diagnostic ID and message if possible (e.g. `"IDE0030: Use coalesce expression"`).

**Expected Behavior**: Nothing redundant appears after IDE1006 fixer is used

**Actual Behavior**: That strange thing appears

VS version: 17.10.3

Details in the video:

https://github.com/dotnet/roslyn/assets/42877671/b348f0c7-c518-44d4-8be1-b1598584ba0a

**Comment by Cosifne** [comment] 2024-07-10 19:40
The linger code action is RenameTracking Code action.
It thinks the naming violation fix is a normal text edit, and provide that rename suggestion

**Comment by RieBi** [comment] 2024-07-11 14:44
> The linger code action is RenameTracking Code action. It thinks the naming violation fix is a normal text edit, and provide that rename suggestion

Very cool

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:04
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-11-26 02:04 UTC
Labels: Area-IDE
