### ISSUE TITLE
Strange indentation two new lines after comment

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#18390] opened 2017-04-03 09:53 UTC
Code:
```cs
using System;

namespace ConsoleApp1
{
    // Anything

    class Program
    {
        static void Main()
        {
            Console.ReadLine();
        }
    }
}
```

Place caret at the end of the line `// Anything`. Press enter twice.

Expected:
```cs
using System;

namespace ConsoleApp1
{
    // Anything

   [|]

    class Program
    {
        static void Main()
        {
            Console.ReadLine();
        }
    }
}
```

Actual:
```cs
using System;

namespace ConsoleApp1
{
    // Anything

       [|]

    class Program
    {
        static void Main()
        {
            Console.ReadLine();
        }
    }
}
```

**Comment by SolderedMushroom** [comment] 2017-04-03 15:38
Duplicate of https://github.com/dotnet/roslyn/issues/3321. Been perennially waiting for this to be fixed for several VS releases.

**Comment by Pilchie** [comment] 2017-04-03 16:15
Yes it's a dupe.  We welcome PRs though!

**Closed by Pilchie** 2017-04-03 16:15 UTC
