### ISSUE TITLE
Warning Level 3 breaks Remove Unused Usings and Simplify Type Name

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#20377] opened 2017-06-21 22:23 UTC
**Version Used**: 15.3 Preview 2.1

**Steps to Reproduce**:

1. Set C# warning level to 3
2. Add the following code

    ```csharp
    using System;
    using System.Threading;

    class Class
    {
      System.Action _action = (Action)(() => { });
    }
    ```

**Expected Behavior**:

1. `System.Threading` is indicated as an unused using directive, and the light bulb allows its removal
2. The `System.` qualification in `System.Action` is marked as unnecessary, and the light bulb allows the type to be simplified to `Action`

**Actual Behavior**:

1. Both using directives are indicated as used
2. `System.Action` is not indicated as overly qualified

Neither the light bulb nor the Remove and Sort Usings command may be used to make the desired corrections.

**Comment by jaredpar** [comment] 2017-06-21 22:47
Note: I tried this in 15.2 RTM and the behavior matches the expected behavior. Used a new Class Library targeting 4.5.2 as the test environment.

**Comment by Pilchie** [comment] 2017-06-22 17:39
I suspect the "info" diagnostic for this gets filtered away in this case.

**Comment by sharwell** [comment] 2017-09-13 16:52
This is caused by the following:

https://github.com/dotnet/roslyn/blob/5b636eb916ad317a09341e59e27ba1fcdd7b71cd/src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs#L496-L497

It seems the fix is removing the dependence of warning level on severity. If a user configures a rule with a specific severity, the current warning level shouldn't undo that.

**Comment by jcouv** [comment] 2017-09-29 16:38
Assigned to Sam since he already has a PR for this.

**Closed** 2018-01-16 17:36 UTC
Labels: Area-Compilers, Bug, Resolution-Fixed

**Comment by IanKemp** [comment] 2018-06-26 17:50
If this was resolved in January, why am I still seeing this issue in June?

**Comment by hunghq** [comment] 2019-08-29 04:15
This happens to me with Visual studio 2019. The cause is the theme Blue High Constrast. Using other themes fix the issue.

Reference
https://www.devexpress.com/Support/Center/Question/Details/T588868/visual-studio-2017-unused-using-is-not-grayed-out

**Comment by soniaZhao66** [comment] 2019-10-01 21:39
change the theme to Blue not (blue high contrast), High Contrast will not grey out the unused namespace.
