### ISSUE TITLE
Remove (or disable by default) IDE0062 (Local function can be made static)

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#41308] opened 2020-01-30 12:32 UTC
**Version Used**: 
16.4.2

**Steps to Reproduce**:
Write a local function that could be made static, but don't mark it with the `static` keyword.

**Expected Behavior**:
No IDE messages.

**Actual Behavior**:
IDE message IDE0062 + "..." underline in IDE.

**Justification**:
Nothing about this message is incorrect, but unlike the other IDE messages which tend to improve my code when followed, my feeling is that this generally makes my code worse. 

If my local function does not capture, I will already get the performance benefits of that without the static keyword. Asking me to add the static keyword makes my code more verbose, assuming (incorrectly) that the non-capturing nature of the function is more important to me than being concise when in almost all cases (except bottlenecks), it isn't. 

The ability to annotate as static to assert the non-capturing nature of my function when I care about that is useful, but in most cases I think the less-verbose code would be preferred. 

Perhaps this is merely personal preference, but I wonder how many devs out there will end up complying with this IDE message just to keep the message pane readable (as I have) and/or out of ignorance as to what the static keyword actually does for them in this context (in my experience, the average C# dev isn't aware of the performance implications of capturing).

**Comment by CyrusNajmabadi** [comment] 2020-01-30 19:15
> Expected Behavior:
> No IDE messages.

You can get your expected behavior by turning off:

![image](https://user-images.githubusercontent.com/4564579/73482040-d9942c80-4351-11ea-9c1e-d84f771db684.png)

**Comment by madelson** [comment] 2020-01-30 23:18
@CyrusNajmabadi does that preference save with the solution or just my VS instance?

Regardless, I guess I’m suggesting that this be turned off by default.

**Comment by CyrusNajmabadi** [comment] 2020-01-30 23:24
> @CyrusNajmabadi does that preference save with the solution or just my VS instance?

It can be either.  If you want it to travel with your solution, you can place your choice in a .editorconfig option. 

> Regardless, I guess I’m suggesting that this be turned off by default.

I don't think that's appropriate.  The option is correctly informing people that they can make their local functions static. Something which adds very little clutter (since a local function is already quite ceremonious), while helping to ensure no accidental captures in the future. At the point where a capture is wanted/desirable, the `static` bit can be assessed and easily removed.

**Comment by madelson** [comment] 2020-02-01 15:05
@CyrusNajmabadi good to know that this can be configured at the solution level.

>  The option is correctly informing people that they can make their local functions static. Something which adds very little clutter (since a local function is already quite ceremonious), while helping to ensure no accidental captures in the future.

I see what you're saying here, and there are related cases where I definitely agree (such as some functional language's ability to explicitly label tail recursion). 

In particular, where I see a ton of value in these types of annotations is expressing programmer intent. It protects against cases where you go out of your way to write code in a non-capturing way to maximize performance at a bottleneck point, only to have that degraded by a future change that adds capturing back. You can try to use comments to protect against this, but a language keyword that enforces this works so much better. The problem is that if _every_ non-capturing local method uses this annotation _whether or not it is important_ to performance, we lose this benefit because `static` _no longer conveys intent_; as you say programmers can easily remove the annotation.

I'm also curious how much you think capturing matters for performance in scenarios where the local function is not being made into a delegate (the IDE message displays regardless). Looking at the IL it seems quite efficient to me (still allocation-free), but perhaps there are scenarios where the impact of this is still measurable.

**Comment by CyrusNajmabadi** [comment] 2020-02-01 18:30
> The problem is that if every non-capturing local method uses this annotation whether or not it is important to performance, we lose this benefit because static no longer conveys intent; as you say programmers can easily remove the annotation.

I don't see any problem with that. 

I don't use static only for performance. I use it to convert the idea: this doesn't capture. 

The modifier helps me document the code clearly and catches when a change is made to that in the future.

**Comment by mavasani** [comment] 2020-02-04 00:02
Design meeting review:

1. We will keep this new feature enabled by default, until we get enough feedback that it is not desirable.
2. It is very easy to configure the code style and severity of this analyzer to turn it off from the light bulb itself:

![image](https://user-images.githubusercontent.com/10605811/73701444-77636080-469e-11ea-8c8e-144b4c84ca78.png)
![image](https://user-images.githubusercontent.com/10605811/73701477-9104a800-469e-11ea-8a11-a890ae90fd5c.png)

**Comment by mavasani** [comment] 2020-02-04 00:05
Marking this as closed, pending more user feedback.

**Closed by mavasani** 2020-02-04 00:05 UTC
Labels: Area-IDE, Concept-Continuous Improvement
