### ISSUE TITLE
Report WRN_UninitializedNonNullableField warnings for static fields.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#30020] opened 2018-09-19 16:54 UTC
```
        // PROTOTYPE(NullableReferenceTypes): Report warnings for static fields.
        [Fact]
        public void StaticFields_DefaultConstructor()
        {
            var source =
@"class C
{
#pragma warning disable 0169
    private static object F1;
    private static object F2 = new object();
    private readonly static object F3;
    private readonly static object F4 = new object();
}";
            var comp = CreateCompilation(new[] { source, NonNullTypesTrue, NonNullTypesAttributesDefinition }, parseOptions: TestOptions.Regular8);
            comp.VerifyDiagnostics();
                //// (8,12): warning CS8618: Non-nullable field 'F3' is uninitialized.
                ////     static C()
                //Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("field", "F3").WithLocation(8, 12),
                //// (8,12): warning CS8618: Non-nullable field 'F1' is uninitialized.
                ////     static C()
                //Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("field", "F1").WithLocation(8, 12));
        }

        // PROTOTYPE(NullableReferenceTypes): Report warnings for static fields.
        [Fact]
        public void StaticFields_ExplicitConstructor()
        {
            var source =
@"class C
{
#pragma warning disable 0169
    private static object F1;
    private static object F2;
    private readonly static object F3;
    private readonly static object F4;
    static C()
    {
        F2 = new object();
        F4 = new object();
    }
}";
            var comp = CreateCompilation(new[] { source, NonNullTypesTrue, NonNullTypesAttributesDefinition }, parseOptions: TestOptions.Regular8);
            comp.VerifyDiagnostics();
                //// (8,12): warning CS8618: Non-nullable field 'F3' is uninitialized.
                ////     static C()
                //Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("field", "F3").WithLocation(8, 12),
                //// (8,12): warning CS8618: Non-nullable field 'F1' is uninitialized.
                ////     static C()
                //Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("field", "F1").WithLocation(8, 12));
        }
```

**Comment by PathogenDavid** [comment] 2018-12-18 07:54
I believe this is a duplicate of #27014.

**Comment by cston** [comment] 2019-07-25 22:39
Closing as a duplicate of https://github.com/dotnet/roslyn/issues/34668.

**Closed by cston** 2019-07-25 22:39 UTC
Labels: Area-Compilers, Bug, Language-C#, New Language Feature - Nullable Reference Types
