### ISSUE TITLE
Naming Rule for Event Handlers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57848] opened 2021-11-18 01:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Naming-Rule-for-Event-Handlers/1584473)._

---
When creating the naming rules for code style, the list of Specifications includes Method but not Event Handler. I understand that in an individual file there may be little or no difference between a method & event handler (especially in languages such as C# where the handler is often added in another part of the code, or even another class or file). If there is some way that you could have Visual Studio make a distinction between event handlers & other methods (this certainly wouldn't be the first time VS looked in multiple locations to make decisions!), it would be very useful. I might also suggest that, to go along with this (since there will always be that oddball scenario), an Attribute that can be used to explicitly mark a method/handler as one or the other (maybe something like CodeStyleAttribute(xxx)).

---
#### Feedback Bot on 11/15/2021, 11:22 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment] 2021-11-18 19:36
This woudl make naming depend on how something was referenced.  On a perf-level alone this is substantively problematic.  It also means that naming isn't possible unless knowing exactly how the code will be used elsewhere.  

Fundamentally this shifts naming away from being purely about the declaration of a symbol itself, to something else entirely.  I'm very wary of going down this route.

**Comment by jmarolf** [comment] 2021-11-25 03:56
I agree with @CyrusNajmabadi that there is not a good way to prove that a method isn't being used to handle an event (which would be the prerequisite here). WPF along has enough interesting dynamic binding cases that I don't really think there is much that could be done here. A workaround would be to have different naming styles in `[*.xaml.cs]` vs `[*.cs]` files in your editorconfig  so you could allow different naming schemes in files where you know event handlers are expected to be defined.

The only place I think we should consider special-casing and/or allowing a naming rule to have some semantic context is for methods that return task-like-types. It is not possible today to define a naming style that enforcing task-like-type returning methods end with the "Async" suffix.

**Comment by sharwell** [comment] 2021-12-01 19:31
I believe the primary avenue we are pursuing to resolve naming style problems for event handlers is updating the designers (e.g. WinForms / WPF) to choose default event handler names that match the active code style rather than use a hard-coded default. See #20999.

**Comment by sharwell** [comment] 2021-12-22 17:08
@jmarolf @CyrusNajmabadi Should we just mark this as a duplicate of #20999?

**Comment by jmarolf** [comment] 2021-12-22 21:19
I am fine with that resolution. I believe the core issue here is that the tooling is throwing you into a pit by offering to generate names that violate developer-specified rules.

**Comment by sharwell** [comment] 2021-12-23 22:27
Duplicate of #20999

**Closed by sharwell** 2021-12-23 22:27 UTC
Labels: Area-IDE, Concept-Design Debt, Developer Community
