### ISSUE TITLE
Auto fix semicolon missing issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47440] opened 2020-09-03 22:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1110520/auto-fix-semicolon-missing-issue.html)._

---
<p>If the compiler detect there is a semicolon missing in line {N}, It should add a semicolon itself, currently it gives error.</p> <p><strong>CS1002 ; expected<br></strong></p><p></p><p><br><strong></strong></p>

---
#### Feedback Bot on 7/12/2020, 08:55 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-09-03 23:44
In general, i would be hesitant about doing this sort of thing automatically (as it could interfere with typing and be generally aggravating).  I'm also hesitant about having a quick-fix for is as it's going to be much slower to invoke the quickfix than to just type the semicolon itself.

**Comment by sharwell** [comment] 2020-09-04 00:14
Duplicate of #30238

**Closed by sharwell** 2020-09-04 00:14 UTC
