### ISSUE TITLE
Target-typed new expression does not work with params method signature when invoked with a single argument

### ISSUE THREAD

**Issue by RichardVesely** [dotnet/roslyn#56880] opened 2021-09-30 19:18 UTC
**Version Used**: 
Visual Studio 16.11.3

**Steps to Reproduce**:
```csharp
Foo(new Bar());             // Okay
Foo(new Bar(), new Bar());  // Okay
Foo(new(), new());          // Okay
Foo(new());                 // CS8752: The type 'Bar[]' may not be used as the target type of new()

void Foo(params Bar[] bars)
{
}

class Bar
{
}
```
**Expected Behavior**:
Target type should be resolved as `Bar`, not `Bar[]` and generate no compile-time error. This is arguably somewhat ambiguous, but `params` keyword should improve type resolution and empty constructor instantiation makes more sense as a `Bar` instance than `Bar` array.

**Actual Behavior**:
Compiler generates CS8752 error.

**Comment by RikkiGibson** [comment] 2021-09-30 19:42
dotnet/csharplang#4939 discusses modifying the [target typed new rules](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/target-typed-new.md) to make such expressions "prefer" converting to the expanded form over the normal form.

Once a change to those rules is proposed and accepted in the csharplang repo, we can implement those new rules in the compiler (i.e. in this repo) for C# 11.

**Comment by jaredpar** [comment] 2021-10-05 21:00
Closing as this is a dupe of the referenced csharplang issue (also it's not a compiler bug as compiler has properly implemented the spec here)

**Closed by jaredpar** 2021-10-05 21:00 UTC
Labels: Area-Compilers, Area-Language Design, New Language Feature - Target-Typed New, untriaged
