### ISSUE TITLE
There is a problem with simplifying interpolation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42800] opened 2020-03-26 18:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/962125/简化内插存在问题.html)._

---

```
Console.WriteLine($"{{{DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss fff")}}}");
```
被简化后为

```
Console.WriteLine($"{{{DateTime.Now:yyyy-MM-dd hh:mm:ss fff}}}");
```

运行结果一致，但代码着色不一致

---
#### Visual Studio Feedback System on 3/25/2020, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-03-26 18:15
The issue here is syntax colorization of the `}}}` characters.

![image](https://user-images.githubusercontent.com/1408396/77681738-0d0ac600-6f53-11ea-942b-7739b3c7b3c0.png)

**Comment by SourceSkyBoxer** [comment] 2020-03-26 18:24
![image](https://user-images.githubusercontent.com/57066679/77682502-58df5e80-6f97-11ea-9dc5-29558715df9c.png)
It looks nothing bug. It looks works as well for me. I am using Ubuntu 18.04
I can't reproduce it.

**Comment by sharwell** [comment] 2020-03-26 18:58
@SourceSkyBoxer The issue is the coloring of the final `}}}` characters in the string. If you zoom in on the image I posted in the previous comment, you can see the difference.

**Comment by SourceSkyBoxer** [comment] 2020-03-26 19:50
@sharwell hmmm?.
![image](https://user-images.githubusercontent.com/57066679/77690012-f0967a00-6fa2-11ea-92f6-d1588abf0102.png)
> The issue is the coloring of the final }}}
Do you mean coloring of the final. Please see my latest picture I post screenshot. I know It is different.

**Comment by CyrusNajmabadi** [comment] 2020-03-26 22:15
@SourceSkyBoxer that's VSCode.  This is an issue with token classification in VisualStudio itself.

**Comment by CyrusNajmabadi** [comment] 2022-02-05 18:24
This has been fixed in VS:
![image](https://user-images.githubusercontent.com/4564579/152654119-09d10a4e-dea2-4a3f-8f39-09b0227793a4.png)

**Closed by CyrusNajmabadi** 2022-02-05 18:24 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community
