### ISSUE TITLE
"IDE0059: Value assigned to variable is never used" is appearing with local function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35845] opened 2019-05-21 18:11 UTC
VSF_TYPE_MARKDOWNThe warning appears on variable &quot;check&quot; in the following code:

```
       public bool TestMethod()
        {
            bool check = true;
            LocalFunction();
            return check;

void LocalFunction()
            {
                check = false;
                Console.WriteLine(check);
            }
        }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/575232/ide0059-value-assigned-to-variable-is-never-used-i.html
VSTS ticketId: 896188_
_These are the original issue comments:_

Visual Studio Feedback System on 5/20/2019, 09:35 PM (13 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by canton7** [comment] 2019-05-22 08:01
Looks like the same thing as #35203?

The diagnostic is correct, and it working as intended. The assignment in `bool check = true;` is unnecessary since it's always reassigned to false - the diagnostic wants you to write `bool check;`, and the associated quick fix makes this change.

What's confusing is the message, and this was changed in #35494.

**Comment by mavasani** [comment] 2019-05-22 17:43
Agreed with @canton7's assessment. Hopefully the improved message will provide more clarity.

**Closed by mavasani** 2019-05-22 17:43 UTC
Labels: Area-IDE, Bug, Developer Community

**Comment by catlion** [comment] 2019-10-05 06:08
What about this one?

            var level = LogEventLevel.Information;
            _ = Enum.TryParse(logLevel, out level);

**Comment by canton7** [comment] 2019-10-05 06:42
Also unnecessary? Since `level` is passed to `Enum.TryParse` as an `out` variable, it will always be assigned to by `Enum.TryParse`. Any value you give it first will therefore always be overwritten.

**Comment by catlion** [comment] 2019-10-05 07:15
Ah sorry, this is kinda obvious now when I think of it :)
