### ISSUE TITLE
"Implement Interface" quickfix doesn't respect nullability annotation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33077] opened 2019-02-03 11:36 UTC
VSF_TYPE_MARKDOWNConsider this code:

    public interface IPossibleNull
    {
        string? Method();
    }

    public sealed class SomeNull : IPossibleNull
    {
    }

The implementing class is missing the interface method. Showing the quick fixes at the interface implementation specification (where the squiggles are) shows the &quot;Implement Interface&quot; suggestion. Executing it results in this code being generated:

    public sealed class SomeNull : IPossibleNull
    {
        public string Method()
        {
            throw new NotImplementedException();
        }
    }

The return type has lost its nullable annotation and a warning is thus generated.

The quick fix needs to respect nullability.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/443107/implement-interface-quickfix-doesnt-respect-nullab.html
VSTS ticketId: 784088_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jasonmalinowski** [comment] 2019-06-20 01:18
Duplicate of #30324.

**Closed by jasonmalinowski** 2019-06-20 01:18 UTC
Labels: Area-IDE, Bug, Developer Community, New Language Feature - Nullable Reference Types
