### ISSUE TITLE
NullReferenceException in IAssemblySymbolExtensions.cs:line 64

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#45298] opened 2020-06-18 20:14 UTC
**Version Used**: 
16.6.1

I have typed code where the method didn't exist:

![image](https://user-images.githubusercontent.com/679326/85067440-88040700-b165-11ea-8802-30b8532c3d85.png)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at bool Microsoft.CodeAnalysis.Shared.Extensions.IAssemblySymbolExtensions.IsSameAssemblyOrHasFriendAccessTo(IAssemblySymbol assembly, IAssemblySymbol toAssembly) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/IAssemblySymbolExtensions.cs:line 64
   at bool Microsoft.CodeAnalysis.Shared.Extensions.ISymbolExtensions.IsNonNestedTypeAccessible(IAssemblySymbol assembly, Accessibility declaredAccessibility, ISymbol within) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions_Accessibility.cs:line 227
   at bool Microsoft.CodeAnalysis.Shared.Extensions.ISymbolExtensions.IsNamedTypeAccessible(INamedTypeSymbol type, ISymbol within) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions_Accessibility.cs:line 191
   at bool Microsoft.CodeAnalysis.Shared.Extensions.ISymbolExtensions.IsSymbolAccessibleCore(ISymbol symbol, ISymbol within, ITypeSymbol throughType, out bool failedThroughTypeCheck) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions_Accessibility.cs:line 107
   at ImmutableArray<SyntaxNode> Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeService.CreateGetHashCodeStatements(SyntaxGenerator factory, Compilation compilation, INamedTypeSymbol namedType, ImmutableArray<ISymbol> members) in /_/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs:line 150
   at IMethodSymbol Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeService.CreateGetHashCodeMethod(SyntaxGenerator factory, Compilation compilation, INamedTypeSymbol namedType, ImmutableArray<ISymbol> members) in /_/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs:line 128
   at async Task<IMethodSymbol> Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeService.GenerateGetHashCodeMethodAsync(Document document, INamedTypeSymbol namedType, ImmutableArray<ISymbol> members, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs:line 121
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<IMethodSymbol> Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeService.GenerateGetHashCodeMethodAsync(Document document, INamedTypeSymbol namedType, ImmutableArray<ISymbol> members, CancellationToken cancellationToken)
```

**Comment by CyrusNajmabadi** [comment] 2020-06-18 23:19
@jasonmalinowski you fixed this right?

**Comment by jasonmalinowski** [comment] 2020-06-23 00:47
@KirillOsenkov In your scenario, is there a System.HashCode somewhere in a library? As a test type System.HashCode and see if you get an 'inaccessible type' or try go to def and see where it takes you.

If so, then yes this is a dupe of #44808.

**Comment by KirillOsenkov** [comment] 2020-06-23 01:00
Nope, no System.HashCode anywhere in sight.

I wasn't able to isolate the repro unfortunately, but I have a solid repro that I can't share here. Ping me for a repro if you're going to take a look, it's easy.

It happens during computing previews for Convert to struct:

![image](https://user-images.githubusercontent.com/679326/85349059-47ccbd80-b4b2-11ea-9436-fa727803b255.png)

**Comment by jasonmalinowski** [comment] 2020-06-23 01:13
@KirillOsenkov: be careful, some libraries you may reference have their own internal copy. That's what tripped this up.

**Comment by KirillOsenkov** [comment] 2020-06-23 01:49
Ah, yes, I was able to repro, turns out 
`C:\Users\Kirill\.nuget\packages\messagepack\2.1.90\lib\netstandard2.0\MessagePack.dll` contains a `System.HashCode` that's internal

```msbuild
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.1.90" />
  </ItemGroup>

</Project>

```

```csharp
class A
{
    public override int GetHashCode()
    {
        return (1, B.GetHashCode()).GetHashCode();
    }
}

static class B
{
    public static int GetHashCode(this byte[] b) => 0;
}
```

**Comment by jasonmalinowski** [comment] 2020-06-23 01:50
Yep MessagePack was what broke it in Roslyn too. Closing then as a dupe.

**Closed by jasonmalinowski** 2020-06-23 01:50 UTC
Labels: Area-IDE, Bug
