### ISSUE TITLE
Incorrect `IDE0007 use 'var' instead of explicit type` for List<T>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37343] opened 2019-07-18 19:54 UTC
```csharp
var result = new List<CorrespondenceModel>();
// ...
List<CorrespondenceModel> sortedresult = result.OrderByDescending(r => r.CreationDate).ToList();
```

I'm getting "use 'var' instead of explicit type" for line "List<...>"

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/520039/incorrect-ide0007-use-var-instead-of-explicit-type.html
VSTS ticketId: 841177_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 01:55 AM (101 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 7/18/2019, 00:54 PM (42 sec ago): <markdown><p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment] 2019-07-18 19:55
I believe this is by design as the type is apparent due to `ToList` invocation. @sharwell for further comment.

**Comment by tiangco** [comment] 2019-07-19 06:22
Hi @mavasani, while a command like: var myList = someObject.ToList();
Tells the reader that myList is some kind of list, it does not indicate what type of list it is.

I believe the intent of using explicit vs var (IDE0007) is to use "var" when the type is inferred from the command. While this is somewhat true in the example above, I think knowing the list type is what developers would like to know. And I would rather not convert these to "var"s but use explicit instead.

Thank you for your consideration.

**Comment by CyrusNajmabadi** [comment] 2019-07-19 07:31
@tiangco This was explicitly considered by the design team and rejected.  I had a PR to provide an option for that here: https://github.com/dotnet/roslyn/pull/33651

Final conclusion:

> Design review conclusion: this pull request introduces a permanent option to work around one specific design limitation of a feature. We decided to table this discussion until we can evaluate the complete scenario, in particular in combination with the new diagnostic suppression APIs that are coming in 16.3. We will reconsider the explicit/implicit type feature as a whole during work to migrate the analyzer from an IDE analyzer to a NuGet package.

**Comment by sharwell** [comment] 2019-07-19 14:27
@CyrusNajmabadi One proposed solution was rejected. The original issue is still open.

**Comment by sharwell** [comment] 2019-07-19 14:27
Duplicate of #29657

**Closed by sharwell** 2019-07-19 14:27 UTC
Labels: Area-IDE, Developer Community, Question
