### ISSUE TITLE
Project.AdditionalDocuments is empty after acepting a refactor that Adds an Additional Document.

### ISSUE THREAD

**Issue by danmendonca** [dotnet/roslyn#19503] opened 2017-05-15 08:11 UTC
**Version Used**: 
1.3.2
**Steps to Reproduce**:

1. In Visual Studio 2017, write a code refactor that generates na AdditionalDocument and add it to the a Project through Project.AddAdditionalDocument(string, SourceText,, Folders)
2. Though the Visual Studio Instance now has the AdditionalDocument visible in the solution explorer, if you get the instance of the modified Project, property AdditionalDocuments count is 0. 

**Expected Behavior**:
After adding na AdditionalDocument to a Project, when running getting the new instance the Document should be available in the Project AdditionalDocuments property
**Actual Behavior**:
![2017-05-15 1](https://cloud.githubusercontent.com/assets/5736384/26048305/7dc27ed0-394e-11e7-8192-517c292a4005.png)
There are no Additional Documents in the Project AdditionalDocuments collection

**Comment by sharwell** [comment] 2017-05-15 11:37
This bit me as well while working on StyleCop Analyzers. It appears to be a duplicate of #4655.

**Closed by sharwell** 2017-05-15 11:37 UTC
