### ISSUE TITLE
Unable to use re-throw in expression form

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#25294] opened 2018-03-07 03:57 UTC
```
class C
{
    void F(object x, object y, object z, int u)
    /*<bind>*/{
        try
        {
            u = 1;
        }
        catch
        {
            M(x, (y ?? throw), z);
        }
    }/*</bind>*/

    static void M(object x, object y, object z){}
}
```

Observed:
```
                // (12,29): error CS1525: Invalid expression term ')'
                //             M(x, (y ?? throw), z);
                Diagnostic(ErrorCode.ERR_InvalidExprTerm, ")").WithArguments(")").WithLocation(12, 29)
```

Expected:
No error, an exception should be re-thrown as appropriate.
I didn't check whether the current behavior is according to the specification of the "Throw Expression" feature, however it feels to me that it would be good if the code would just work.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 04:09
Looks like a dupe of https://github.com/dotnet/csharplang/issues/1340

**Comment by gafter** [comment] 2018-03-07 06:34
This behavior is by spec. There is already an open issue that @CyrusNajmabadi identified.

**Closed** 2018-12-12 01:16 UTC
Labels: Area-Compilers, Bug, Language-C#, New Language Feature - Throw Expression
