### ISSUE TITLE
#region Auto-Indenting Misbehaving

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38517] opened 2019-09-05 17:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/703701/region-auto-indenting-misbehaving.html)._

---
C#/Tabs/Indenting: Block
C#/Tabs/Tab/Tab_size: 4
C#/Tabs/Tab/Indent_size: 4
C#/Tabs/Tab/Keep_tabs (true)

I have to stipulate that I am somewhat old-school, and have tried to disable _most-if-not-all_ auto-formatting.  All I want is the _guarantee_ that when I press [ENTER], the editor Inserts a newline plus indentation to place the cursor at (R+1, C).

**EXAMPLE 1**:  Start with the following code:
```
namespace Minimum
{
	public class Foo
	{
	}
}
```
Press [ENTER], [TAB], create a property, then press [ENTER].  As expected, the cursor will be indented correctly.

```
	public class Foo
	{
		public bool Bar { get; set; }
		// cursor is here
	}

```
Do the same with #region Methods[ENTER] and you get
```
	public class Foo
	{
		#region Methods
	// cursor is here but should be 1 indentation right
	}

```
**EXAMPLE  2**: Start with the following code:
```
	public class Foo
	{
		#region Properties

// cursor is here

public bool Bar { get; set; }

#endregion Properties
	}
```
Type #region [SPACE] and you get
```
	public class Foo
	{
		#region Properties

#region // code has been shifted left

public bool Bar { get; set; } // code has been shifted left

#endregion Properties
	}
```
this behavior even skips regions, e.g.,
```
	public class Foo
	{
		#region Properties

// cursor is here

#endregion Properties

#region Methods

public void Bat()
			{
				// NOOP
			}

#endregion Methods
	}
```
Type #region[SPACE] and you get:
```
	public class Foo
	{
		#region Properties

#region // code has been shifted left

#endregion Properties

#region Methods

public void Bat() // code has been shifted left
			{
				// NOOP
			}

#endregion Methods
	}
```
Not observing the Block is frustrating enough without the &quot;spooky action at a distance.&quot;

---
#### Visual Studio Feedback System on 8/22/2019, 04:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2019-09-17 19:28
Duplicate of #2487

**Closed by jinujoseph** 2019-09-17 19:28 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community, IDE-CodeStyle
