### ISSUE TITLE
Cursor indentation problem after commenting a piece of code

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn#28752] opened 2018-07-21 00:07 UTC
**Version Used**: 
VS Community 2017 Version 15.7.5

**Steps to Reproduce**:
1. Comment a piece of code
2. Place the cursor at the end of the commented code
3. Hit the "Enter" key twice (please have a look at the image)

![bug](https://user-images.githubusercontent.com/4363170/43029789-878f1220-8c9a-11e8-8f71-97577de92146.gif)

**Expected Behavior**:
The cursor to stay at a correct indentation level.

**Actual Behavior**:
The cursor jumps back to the previous indentation level.
Note that this doesn't happen on a method level or a class level. It happens inside `if`, `foreach` and other blocks.

Sorry if this has already been reported. I wasn't able to find the existing issue.

**Comment by CyrusNajmabadi** [comment] 2018-07-21 00:18
Note: you don't even need to do the "comment selection" command.  This repros simply if you press enter underneath a commented line:

![indentation](https://user-images.githubusercontent.com/4564579/43030058-eb8db330-8c40-11e8-8b47-e35289bed4c7.gif)

**Comment by saeed-serpooshan** [comment] 2018-12-26 10:10
@CyrusNajmabadi 
> Note: you don't even need to do the "comment selection" command. This repros simply if you press enter underneath a commented line:
> 
> ![indentation](https://user-images.githubusercontent.com/4564579/43030058-eb8db330-8c40-11e8-8b47-e35289bed4c7.gif)

There is also another wrong indentation i reported recently [here](https://developercommunity.visualstudio.com/content/problem/414629/wrong-indentation-of-comments-above-the-class-or-n.html). When we want to add some comments in c# code, the cursor goes to a wrong position (increased/doubled indent) after hitting two <Enter> keys (for the purpose of having an empty line between the two comment lines)
![scrshot-wrong-indent2-serpooshan](https://user-images.githubusercontent.com/40749960/50442372-76fd7100-08b3-11e9-8a6c-9bb4b4c0713f.png)

**Comment by PyroChiliarch** [comment] 2019-09-04 12:16
I am currently having this issue in Visual Studio Community 2019 version 16.2.3.

Tools -> Import and Export Settings -> Reset All Settings. Fixed it for me.

**Comment by dog44wgm** [comment] 2019-11-10 20:32
Why is this closed? It's still a problem in VS2019.
![image](https://user-images.githubusercontent.com/25846791/68550223-b2af0580-03b5-11ea-9552-7ee43efd543f.png)

**Comment by CyrusNajmabadi** [comment] 2019-11-11 05:38
@dog44wgm 

> Why is this closed? It's still a problem in VS2019.

What do you mean?  This issue is still open, and is still listed as "help wanted".

**Comment by PeterHuberSg** [comment] 2020-03-22 07:01
Why is Microsoft not fixing this bug, which exists in VS since years ? Just marking this issue with "help wanted" looks lazy to me. Shouldn't take Microsoft take some responsibility for solving old bugs in their software ?

**Comment by CyrusNajmabadi** [comment] 2020-03-22 07:32
> Why is Microsoft not fixing this bug, which exists in VS since years 

The issue is currently lower priority than all existing with people are working on. 

> Shouldn't take Microsoft take some responsibility for solving old bugs in their software ?

Age doesn't make issues more important. 

>Just marking this issue with "help wanted" looks lazy to me.  

It's marked 'help wanted' because we would certainly take a community pr if provided. 

It sounds like this is very important to you. Would you be willing to contribute a fix here?  Thanks!

**Comment by TKharaishvili** [comment] 2020-03-22 15:46
> Would you be willing to contribute a fix here?

Roslyn is a huge codebase(needless to say). I've spent a couple dozen hours digging through it and debugging it over the years and I still have no idea where to even start if I wanted to fix this problem.
It would probably take weeks and weeks of prior experience working with the codebase to pinpoint the origin of this issue and deal with it.

That's why marking it as "help wanted" sounds like: "meh, you guys can fix it yourselves if you really want to".

With that said, if somebody was willing/had a little time to provide some guidance through the process I'd gladly give it a try.

**Comment by CyrusNajmabadi** [comment] 2020-03-23 05:03
> and I still have no idea where to even start if I wanted to fix this problem.

The best place to start here would in the SmartIndet component: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/SmartIndent/SmartIndent.cs

If you run into roadblocks there, LMK and i can try to help you through it:

> That's why marking it as "help wanted" sounds like: "meh, you guys can fix it yourselves if you really want to".

Help wanted means what i said above.  We would take a community PR here.  Right now that this hasn't risen above the priority of all the existing work the team has.  The choices are to wait until it does, or see if the community can supply a fix.

> With that said, if somebody was willing/had a little time to provide some guidance through the process I'd gladly give it a try.

Yup!  See above.  Also, feel free to reach out on gitter.im/dotnet/roslyn or discord.gg/csharp (#roslyn channel).

**Comment by PeterHuberSg** [comment] 2020-03-27 06:37
> > Why is Microsoft not fixing this bug, which exists in VS since years
> 
> The issue is currently lower priority than all existing with people are working on.
> 
> > Shouldn't take Microsoft take some responsibility for solving old bugs in their software ?
> 
> Age doesn't make issues more important.
> 
> > Just marking this issue with "help wanted" looks lazy to me.
> 
> It's marked 'help wanted' because we would certainly take a community pr if provided.
> 
> It sounds like this is very important to you. Would you be willing to contribute a fix here? Thanks!

Sorry for having no experience with how VS gets maintained. However, I wonder if the right weights are given to which problem gets solved. It seemed that presently problems that get complained about a lot get most likely fixed. Which is understandable. But there is another category of problems that should get fixed, the ones which might have not so grave consequences, but nearly everybody encounters. It is sad if VS get's a bad reputation of being buggy, just because simple problems that almost everyone encounters don't get fixed. Using // comments is something every C# developer does, meaning that bug should really get fixed. I understand that the unpaid, community helpers might not want to spend their time on such a problem. But here Microsoft has a responsibility and should step in. Also, someone who has worked on that part of the Editor might solve the problem in a day or two, while someone like me who has never seen any VS code might take forever. Being that the case, I feel it is cheap from Microsoft to suggest I should fix it myself.

**Comment by CyrusNajmabadi** [comment] 2020-03-27 06:49
> Which is understandable. But there is another category of problems that should get fixed, the ones which might have not so grave consequences, but nearly everybody encounters. 

We call these paper-cuts, and they are def things that are fixed.  But they still have to be prioritized against everything else.  Every issue that is fixed is time from someone that is taken away from other things to fix.  So far, this hasn't been as important to push anything else out.

> Using // comments is something every C# developer does, meaning that bug should really get fixed. 

This can be stated about many, if not most of all the bugs we have.

> But here Microsoft has a responsibility and should step in. 

We have triaged things and have assessed other issues as being more important currently.  If we pull someone off to work on this, that means taking back on something else.  

There isn't enough time or resources to address all the issues in a timely manner.  So it will always be the case that some issues get pushed out.

>  Also, someone who has worked on that part of the Editor might solve the problem in a day or two,

Yes, but that means two days taken away from more important work that is more important to the community as a whole.

> Being that the case, I feel it is cheap from Microsoft to suggest I should fix it myself.

This is an open source project.  Many people contribute to it.  One of the great benefits of this is that if you find something more important for your own needs than the team does, then it's possible for you to dive in, get your hands dirty, and solve the problems that you feel are impacting you more than the ones that we are working on.

We literally have finite time and people to work on a backlog of *thousands* of items.  It will always be the case that whatever we pick to work on, we'll not be addressing the needs of some users.  Being open source means you're not still forced to wait forever for fixes.  If it's this important, then you can fix.

Note: i agree that this would take learning from someone starting out.  But many contributors have done this, and given that investment they now commonly provide many features and fixes that they find important to them.   

It can be done, and it's something we're happy to help you out with if you're interested.

**Comment by PyroChiliarch** [comment] 2020-03-27 08:56
Ive been following this issue for so long i had completely forgotten about
it.
I was getting so annoyed by this i even tried reinstalling windows.
I went to go back and check on it again recently but its somehow not doing
it any more.
Thank you for being a contributor but I agree with peterhuberSG, its been
around long enough that if it was easy, it would probably be fixed by now
and its not the kind of bug that goes away with a quick restart.

**Comment by CyrusNajmabadi** [comment] 2020-03-27 09:33
Have been at the vet for a few hours.  can't sleep here, and i needed a distraction.  so i looked into seeing if i could fix this.  i might have a potential PR here.

**Comment by CyrusNajmabadi** [comment] 2020-03-28 02:25
Ok.  I ended up tearing out a bunch of the existing code to go with an approach that is hopefully simpler and better.  If all goes well, this won't cause any regressions in cases people care about.  PR is going through CI now.

**Closed** 2020-03-28 03:47 UTC
Labels: Area-IDE, Bug, help wanted
