### ISSUE TITLE
CS0618 shown in error when method uses obsolete element internally

### ISSUE THREAD

**Issue by NetTecture** [dotnet/roslyn#39130] opened 2019-10-08 12:28 UTC
Visual Studio 16.3.2

I have a method using an obsolete element INTERANALLY - it is not used as parameter, nor is it actually returned.

I am getting offered to add the obsolete attribute to the method:

![image](https://user-images.githubusercontent.com/909612/66395471-c7276900-e9d7-11e9-9fbb-08edc63e501d.png)

This is factually incorrect. While the warning on the obsolete element is sensible, adding obsolete to the method would mark this method as obsolete - which is wrong. It may need rework, but it is not obsolete - it is still to be used.

This would be different if the obsolete element would be part of input or output parameters. But in this case, it is not - it is defined within the method body and then discarded.

**Comment by CyrusNajmabadi** [comment] 2019-10-08 20:51
The adding of 'obsolete' is just offered as a potential option to solve the issue.  It is not intended to state that you must solve it in this manner.

**Comment by NetTecture** [comment] 2019-10-08 22:22
Look, I use the refactorings very regularly. This one is different.

EVERY other refactoring is functionally identical. It never changes the behavior.

This one tells me to add obsolete to a method - using an obsolete api - although no obsolete element is exposed. if I do so, I change the behavior because i will tell users of my library to NOT use this particualr method. Which means updating an external reference (nuget) can result in proposed refactorings that possibly change the interface of my library to third parties.

The correct way would be to ONLY offer this if an exposed element is either returned or entered in the function, either directly or indirectly (as element of one of the classes), NOT when it is only internally used.

**Comment by CyrusNajmabadi** [comment] 2019-10-08 23:01
> EVERY other refactoring is functionally identical. It never changes the behavior.

It's not a refactoring.  It's a potential suggestion on how to fix the issue.  

> This one tells me to add obsolete to a method - using an obsolete api - although no obsolete element is exposed. if I do so, I change the behavior because i will tell users of my library to NOT use this particualr method.

Sure.  So in this case, it's not appropriate for your API.  So you wouldn't take this suggestion.  Just like how many other issues offer lots of fixes, many (or all) of which may not be appropriate for that code :)

> The correct way would be to ONLY offer this if an exposed element is either returned or entered in the function, either directly or indirectly (as element of one of the classes), NOT when it is only internally used.

"correct" is in the eye of the beholder.  For your use case, you do not wish to annotate your methods like this.  For other users, they may want to do this, regardless of the signature of hte method.  The point of the fix suggestions is to supply potential fixes, which users can then evaluate to determine whether or not they're appropriate for their use case.

> It never changes the behavior.

This is not true :)   And it's not a desirable goal for the suggestions either.  Lots of suggestions change behavior as part of their suggestion on what to do with the code.

Cheers! :)

**Comment by gafter** [comment] 2019-10-14 22:37
This fix should be offered alongside one that offers to suppress the warning using pragmas.

**Comment by mavasani** [comment] 2019-10-15 19:17
I agree with @CyrusNajmabadi here - this is by design. Let us step back and examine the state of your current code:

1. User is editing non-obsolete code, which invokes obsolete or unsupported code.
2. User is likely do either of the below actions:
   1. Add a pragma suppression for the obsolete diagnostic, clarifying intent that I still want to continue invoking unsupported code.
   2. Mark the currently edited code as also being obsolete or unsupported, as it relies on obsolete or unsupported functionality. This is very likely when some core functionality of a component gets obsoleted and all the downstream public APIs consuming that functionality also need to be marked obsolete.

Both of these are valid _potential_ user actions, which the user can accept based on which applies for them in the current context.

**Comment by sharwell** [comment] 2019-10-15 19:19
Closing as **By Design** based on https://github.com/dotnet/roslyn/issues/39130#issuecomment-542364007

**Closed by sharwell** 2019-10-15 19:19 UTC
Labels: Area-IDE
