### ISSUE TITLE
Access violation on null-conditional access of tuple item when tuple is a generic class property

### ISSUE THREAD

**Issue by thedewi** [dotnet/roslyn#41109] opened 2020-01-21 04:52 UTC
When a generic class has a tuple property utilizing its generic type, a null-conditional access of the tuple's item causes `System.AccessViolationException: Attempted to read or write protected memory.`

Observed on .NET Core runtimes `3.1`, `2.2`, and `2.1` in Windows, and `2.2` in Ubuntu 16. The `2.x` runtimes do not display the error to console, but it is logged under Application in the Windows Event Log.

.NET Framework runtime appears to be unaffected.

## Minimal example

`Program.cs` -
```csharp
using System;

class Program
{
    static void Main()
    {
        GenericMethod<string>();
        Console.WriteLine("Hello World!");
    }
    static void GenericMethod<T>()
    {
        new GenericClass<T>().Prop.Item2?.ToString();
    }
}

public class GenericClass<T>
{
    public ValueTuple<long, T> Prop { get; }
}
```

`Crasher.csproj` -
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

### Expected output

```
> dotnet run -c Release
Hello World!
```

### Actual output

```
> dotnet run -c Release
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Program.GenericMethod[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at Program.Main()
```

**Comment by jaredpar** [comment] 2020-01-21 15:32
@RikkiGibson can u confirm this is a dupe of #40690

**Comment by RikkiGibson** [comment] 2020-01-21 18:36
Yes, this looks like a dupe. The program works in the latest [Microsoft.Net.Compilers.Toolset](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers.Toolset) compiler.

**Closed** 2020-01-21 18:36 UTC
Labels: Area-Compilers, Bug, Resolution-Duplicate
