### ISSUE TITLE
Update IOperation tests to have LanguageName and IsImplicit property

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21330] opened 2017-08-04 23:01 UTC
Because it's too big and mostly unrelated of a change, this should go in separately from https://github.com/dotnet/roslyn/pull/21040.

this should also include parent pointer.

**Comment by heejaechang** [comment] 2017-09-18 18:43
dupe of this - https://github.com/dotnet/roslyn/issues/22174

**Closed** 2017-10-04 21:16 UTC
Labels: Area-Analyzers, New Feature - IOperation, Test, Urgency-Now
