### ISSUE TITLE
Null state static analysis not working when passing function

### ISSUE THREAD

**Issue by momt99** [dotnet/roslyn#53692] opened 2021-05-26 11:14 UTC
**Version Used**: 
c# 8.0
.NET 5.0.201

**Steps to Reproduce**:

1. Consider this method with `NotNullIfNotNull` attribute:
```csharp
[return: NotNullIfNotNull(nameof(entity))]
public MyClass? GetMyClass(MyClassEntity? entity) =>
    return this.AConvertingMethod(entity);
```
2. When I use it as a lambda expression for `Select` method, everything is fine and it is recognized by the compiler that items won't be `null` so there's no warning.
```csharp
public IEnumerable<MyClass> Children =>
    this.entity.Children.Select(e => this.GetMyClass(e));

// this.entity.Children is: public ICollection<MyClassEntity> Children { get; set; };
```
3. But when the method (`GetMyClass`) is passed directly as the `selector` parameter, the compiler generates:
```
CS8619: Nullability of reference types in value of type 'IEnumerable<MyClass?>' doesn't match target type 'IEnumerable<MyClass>.
```
```csharp
public IEnumerable<MyClass> Children =>
    this.entity.Children.Select(this.GetMyClass);
```

**Expected Behavior**:
The two cases are equal and no warning is generated.

**Actual Behavior**:
It generates a warning in the second case which means it couldn't recognize that the method return value won't be null.

**Comment by RikkiGibson** [comment] 2021-05-26 17:01
Possibly a duplicate of #44174

**Closed** 2021-05-26 20:11 UTC
Labels: Area-Compilers, untriaged
