### ISSUE TITLE
Bug in IntelliSense xml file generation causing DocIds of unusual APIs to show up malformed

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#56302] opened 2021-09-09 21:19 UTC
I found this bug in the dotnet/runtime repo, consuming the latest bits in `main`.

This following API has a very unusual signature that receives delegate pointers as parameters:

[runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/ObjectiveC/ObjectiveCMarshal.cs#L60-L64
](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/ObjectiveC/ObjectiveCMarshal.cs#L60-L64)
```cs
       public static unsafe void Initialize(
            delegate* unmanaged<void> beginEndCallback,
            delegate* unmanaged<IntPtr, int> isReferencedCallback,
            delegate* unmanaged<IntPtr, void> trackedObjectEnteredFinalization,
            UnhandledExceptionPropagationHandler unhandledExceptionPropagationHandler)
```

When we build dotnet/runtime, the intellisense xml file for this API is saved in: `%repos%\runtime\artifacts\bin\coreclr\windows.x64.Release\IL\System.Private.CoreLib.xml`

This is how the DocId for this API looks like in the file. Notice **the delegate pointer parameters are missing**:
```xml
<member name="M:System.Runtime.InteropServices.ObjectiveC.ObjectiveCMarshal.Initialize(,,,System.Runtime.InteropServices.ObjectiveC.ObjectiveCMarshal.UnhandledExceptionPropagationHandler)">
```

Strangely, this is how the Docs build system interpreted that DocId of that new API after we updated it with the latest ref assemblies. At least dotnet-api-docs showed _something_ in the parameters:

[dotnet-api-docs/xml/System.Runtime.InteropServices.ObjectiveC/ObjectiveCMarshal.xml#L86](https://github.com/dotnet/dotnet-api-docs/blob/9629ac3eea0218cd64979ec1973141989b709633/xml/System.Runtime.InteropServices.ObjectiveC/ObjectiveCMarshal.xml#L86)
```xml
<MemberSignature Language="DocId" Value="M:System.Runtime.InteropServices.ObjectiveC.ObjectiveCMarshal.Initialize(=FUNC:System.Void,=FUNC:System.Int32(System.IntPtr),=FUNC:System.Void(System.IntPtr),System.Runtime.InteropServices.ObjectiveC.ObjectiveCMarshal.UnhandledExceptionPropagationHandler)" />
```

This problem prevented us from getting documentation ported from the intellisense file to the dotnet-api-docs repo, for APIs with unusual signatures like this one. We use [a tool](https://github.com/carlossanlop/DocsPortingTool) that matches APIs by DocId.

cc @AaronRobinsonMSFT who helped me discover it.

**Comment by CyrusNajmabadi** [comment] 2021-09-09 21:34
@333fred What shoudl teh docids be?  A reference to IntPtr?

**Comment by 333fred** [comment] 2021-09-09 23:29
Duplicate of https://github.com/dotnet/roslyn/issues/48363.

**Comment by 333fred** [comment] 2021-09-09 23:30
In general, we don't have a definition for that the DocID should be, particularly with respect to calling conventions.

**Closed by 333fred** 2021-09-09 23:29 UTC
Labels: Area-Compilers, untriaged
