### ISSUE TITLE
Visual Studio hangs while writing a set property body with a typo

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24640] opened 2018-02-05 12:56 UTC
While writing a property set body, and having a typo, VS hangs, e.g.:

```csharp
     private string _hello;
     public string Hello
      {
            get => _hello;
            set => SetProperty)ref
      }
```

And then attempt to remove the typo..

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/193242/visual-studio-hangs-while-writing-a-set-property-b.html
VSTS ticketId: 562172_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment] 2018-02-05 13:18
Can repro on 15.5.5 but not on 15.6p3 or in latest master.

**Comment by sharwell** [comment] 2018-02-05 13:21
After looking at the performance trace submitted by the user, this appears to be a loop deep inside the language parser under `IncrementallyParse`. Moving to @dotnet/roslyn-compiler.

**Comment by jcouv** [comment] 2018-02-05 18:13
`IncrementallyParse` is in IDE code, so it's not obvious what compiler change may have affected its performance.
I took a look at compiler PRs related to parsing since 15.5, but nothing jumped out. Tagging @gafter in case he recognizes that situation.
Otherwise, I'd go ahead and close the issue.

**Comment by CyrusNajmabadi** [comment] 2018-02-06 19:40
@jcouv I think @sharwell meant that it's *deep* under ```IncrementallyParse```.  i.e. ```IncrementallyParse``` calls SyntaxTree.WithChangedText which bottoms out in incremental parsing.

This does sound like an incremental parsing infinite loop of some sort.  Given that @Neme12 can repro it, we should def investigate to see what the core issue is and make sure it was actually fixed.

**Comment by sharwell** [comment] 2018-02-06 20:13
@CyrusNajmabadi Yes that is what I meant 👍

**Comment by jcouv** [comment] 2018-02-06 20:18
Right, but it sounds like @Neme12 cannot repro on newer versions. I'm just not sure what fixed it.

**Comment by gafter** [comment] 2019-07-16 17:23
Closing as not reproducible.  If that changes please open a new issue.

**Closed by gafter** 2019-07-16 17:23 UTC
Labels: Area-Compilers, Bug, Developer Community, Tenet-Reliability, help wanted
