### ISSUE TITLE
Failure of BasicGoToDefinition.xml test blocks integration from stabilization into master and into future-stabilization

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10561] opened 2016-04-14 17:08 UTC
See https://github.com/dotnet/roslyn-internal/pull/832 and https://github.com/dotnet/roslyn-internal/pull/833

Failing builds: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/317/

**Comment by jasonmalinowski** [comment] 2016-04-14 18:17
This is a possible dupe of #9602.

**Comment by jasonmalinowski** [comment] 2016-05-13 23:40
Unfortunately haven't gotten any new hits to make progress on anything. We'll reactivate on next failure.

**Closed by jasonmalinowski** 2016-05-13 23:40 UTC
Labels: Area-IDE, Blocked, Test, Urgency-Soon
