### ISSUE TITLE
Quick actions use wrong indent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65375] opened 2022-11-11 20:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-actions-use-wrong-indent/10197217)._

---
[regression] [worked-in:17.2]
When using a "Quick action or Refactoring...", either started by Ctrl+. or clicking the lightbulb or through the context menu, the resulting code is not indented with the configured value. We use an indent of 2, but the code is indented with the default of 4.

This used to work correctly in the previous versions of VS 2022 (I guess 17.2; now using 17.4.0).

Steps to reproduce:

0. (Make sure you have tab indent set to 2)
1. Type `var up = "down".ToUpper();`
2. Position cursor on `var`
3. Type Ctrl+.
4. In the context menu choose "Use explicit type instead of 'var'"

As you can see in the screenshot, the proposed substitution is incorrectly indented.
![image.png](https://aka.ms/dc/image?name=B0f3c993a194345899053540f88bebbd2638036765296476786_20221110-122846-image.png&tid=0f3c993a194345899053540f88bebbd2638036765296476786)

This happens with all refactorings.

---
#### Feedback Bot on 11/10/2022, 06:53 PM: 

(private comment, text removed)
#### Chris Wang [MSFT] on 11/11/2022, 00:08 AM: 

(private comment, text removed)
#### hdejonge on 11/11/2022, 00:56 AM: 

(private comment, text removed)
#### Feedback Bot on 11/11/2022, 02:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by arkalyanms** [comment] 2022-11-11 21:04
Could this be from https://github.com/dotnet/roslyn/pull/61091?

**Comment by Youssef1313** [comment] 2022-11-11 21:13
See also https://github.com/dotnet/roslyn/issues/65360

**Comment by CyrusNajmabadi** [comment] 2022-11-11 21:18
Dupe of https://github.com/dotnet/roslyn/issues/65360.

**Closed by CyrusNajmabadi** 2022-11-11 21:18 UTC
Labels: Bug, Area-IDE
