### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in windows_vsi_p0_open_prtest on PR #12826

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#12862] opened 2016-08-01 21:24 UTC
Add Analyzer TAO action failed.

...

PR: [#12826](https://github.com/dotnet/roslyn/pull/12826) *porting OOP to preview 4 branch* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p0_open_prtest/7/

**2 Test Failures:**
AnalyzersNode.C# Analyzers Node
AnalyzersNode.VB Analyzers Node

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

AnalyzersNode.xml

**Comment by Pilchie** [comment] 2016-08-04 16:20
Dupe of #12503.

**Closed** 2016-08-04 16:21 UTC
Labels: Bug, Resolution-Duplicate
