### ISSUE TITLE
Cannot build deeply nested hierarchies with .NET 8 RC 1 SDK (e.g. Microsoft.AspNetCore.Odata)

### ISSUE THREAD

**Issue by andrewlock** [dotnet/roslyn#70272] opened 2023-10-06 16:20 UTC
### Describe the bug
With the .NET SDK version `8.0.100-rc.1.23463.5` I cannot build a project that contains a deeply-nested class hierarchy. Instead the build hangs for 45+ mins(forever?)

### To Reproduce

I've attached the repro project - this compiles quickly with the .NET 7 SDK, but never (effectively) with the .NET 8 SDK. The problem appears to be around deeply nested class hierarchies (which are present in the [Microsoft.AspNetCore.Odata](https://www.nuget.org/packages/Microsoft.AspNetCore.OData) library - the hierarchies in this sample are based on that)

[DeepNestedHierarchy.zip](https://github.com/dotnet/roslyn/files/12856489/DeepNestedHierarchy.zip)

As a further test I tried to build the [Microsoft.AspNetCore.OData](https://github.com/OData/AspNetCoreOData) project itself using the .NET 8 SDK and I see the exact same problem.

### Exceptions (if any)

N/A - it spins forever

### Further technical details

<details><summary>Using <code>8.0.100-rc.1.23463.5</code>. Full <code>dotnet --info</code></summary>
<pre><code>
dotnet --info
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
</pre></code></details>

**Comment by andrewlock** [comment] 2023-10-06 17:02
> I'll transfer and poke a few folks.

Perfect, thank you! 🙂

**Comment by andrewlock** [comment] 2023-10-10 11:34
As a follow up to this, if I add the package `Microsoft.Net.Compilers.Toolset` with version `4.6.0` ([as described in this issue](https://github.com/OData/AspNetCoreOData/issues/1025#issuecomment-1694702152)) then the build succeeds (with warnings):

```
> dotnet build
MSBuild version 17.8.0-preview-23418-03+0125fc9fb for .NET
  Determining projects to restore...
  Restored C:\Users\andrew.lock\Downloads\DeepNestedHierarchy\DeepNestedHierarchy.csproj (in 219 ms).
C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support
-policy [C:\Users\andrew.lock\Downloads\DeepNestedHierarchy\DeepNestedHierarchy.csproj::TargetFramework=net7.0]
CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Sdks\Microsoft.NET.Sdk
.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler,
 which is newer than the currently running version '4.6.0.0'. [C:\Users\andrew.lock\Downloads\DeepNestedHierarchy\De
epNestedHierarchy.csproj::TargetFramework=net7.0]
  DeepNestedHierarchy -> C:\Users\andrew.lock\Downloads\DeepNestedHierarchy\bin\Debug\net7.0\DeepNestedHierarchy.dll

Build succeeded.

CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Sdks\Microsoft.NET.Sdk
.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler,
 which is newer than the currently running version '4.6.0.0'. [C:\Users\andrew.lock\Downloads\DeepNestedHierarchy\De
epNestedHierarchy.csproj::TargetFramework=net7.0]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.88
```

**Comment by jasonmalinowski** [comment] 2023-10-10 21:26
Tagging @jaredpar to triage further.

**Comment by andrewlock** [comment] 2023-10-10 21:59
I've just tested this with the RC2 bits just released, and it seems to work, so I think you're off the hook 😅 Will confirm for sure tomorrow 🙂

**Comment by jaredpar** [comment] 2023-10-11 01:28
Based on the title I was pretty sure this was a dupe of #70169. Given it doesn't repro in RC2 I'm really sure 😄 .

**Closed by jaredpar** 2023-10-11 01:28 UTC
Labels: Area-Compilers, untriaged
