### ISSUE TITLE
.NET compiler (csc.exe) ends compilation with code -2146232797 (COR_E_FAILFAST) in Release configuration

### ISSUE THREAD

**Issue by NSentinel** [dotnet/roslyn#5348] opened 2015-09-18 23:17 UTC
.NET compiler (`csc.exe`) ends compilation with code `-2146232797` / `0x80131623` in `Release` configuration. 

Compiler: Microsoft (R) Visual C# version 1.0.0.50618

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079
Windows 10 Pro v10.0.10525

`-2146232797` error code equals to `COR_E_FAILFAST` according to [this article](http://blogs.msdn.com/b/eldar/archive/2007/04/03/a-lot-of-hresult-codes.aspx)

Project compiled normally as `Debug` but in `Release` configuration I got `COR_E_FAILFAST` error. There is noticeable delay before this error appears. `Debug` built in `5.5` sec, Release failed in `15.5` sec according to `MSBuild` stats.

I have made a few experiments searching for any relation to configuration and found that:

- `Optimize code` can be in any state;
- Enabling `Define DEBUG constant` leads to this error.

We use `DEBUG` constant to [conditional compile] (https://msdn.microsoft.com/en-us/library/system.diagnostics.conditionalattribute(v=vs.110).aspx) (via `Conditional` attribute) our extensive logging: fully logged with `DEBUG` and partially without it. 

**I think this conditional compilation seems leads to `COR_E_FAILFAST` error.**

Maybe such construction in code (conditional compilation + null-conditional operator) is a problem:
`st.Log?.Logger.ConditionalTrace("New packet: [{0}]", packet.ToString());`

**I compiled project successfully after surrounded all such constructions with `#if #endif`**

I've tried to gather any additional details via various combination of debugging compiler options: `/reportanalyzer`,  `/errorlog`, `/errorreport` and `/bugreport` but have no success since compiler always failed without any debug output.

Command line used to compile (full source file list is omitted):

>"C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe" /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll" /reference:"W:\Work\packages\NLog.4.1.1\lib\net45\NLog.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\Assembly.dll /ruleset:"W:\Dev\VS2015\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output Properties\AssemblyInfo.cs  "W:\Temp\AppData\Local\Temp\.NETFramework,Version=v4.6.AssemblyAttributes.cs"

**Error stack trace from compiler obtained by running compiler under `WinDbg`**:

>CLR: Managed code called FailFast, saying "System.NullReferenceException: Object reference not set to an instance of an object.
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteConditionalAccess(BoundConditionalAccess node, Boolean used, BoundExpression rewrittenWhenNull)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIfStatement(BoundIfStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIfStatement(BoundIfStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIfStatement(BoundIfStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIfStatement(BoundIfStatement node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   in Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawAwaitInExceptionHandler)
   in Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
   in Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   in Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol)
   in Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()"
ntdll!ZwTerminateProcess+0x14:

**Comment by jaredpar** [comment] 2015-09-22 21:18
@AlekseyTs this looks to be a duplicate of #4615.  Can you confirm?

**Comment by AlekseyTs** [comment] 2015-09-22 22:50
Yes, looks like the same issue as #4615.

**Closed by AlekseyTs** 2015-09-22 22:50 UTC
Labels: Area-Compilers
