### ISSUE TITLE
Region position bug for #if & #elif

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#58895] opened 2022-01-17 06:23 UTC
**Version Used**: 
Visual Studio 2022(17.0.5)
Resharper 2021.3

**Steps to Reproduce**:

1. Open source file and expand method code
2. Auto pop up folding label on the left
3. Click this

**Expected Behavior**:
In fact, no folding device is needed to avoid vs unsatisfactory processing results. If you really want to process, the processing strategy is to allow folding with parentheses. The position should be accurate, and the folding should be allowed to be the same as the normal conditional statements if and else in the method. I also submitted some suggestions and bug feedback on conditional compilation formatting to Resharper.

**Actual Behavior**:

- Display region location problem.
![image](https://user-images.githubusercontent.com/23723575/149718662-32924df6-e120-432c-8212-abed4f75e3d8.png)

- The folded position should refer to the code block position, which is consistent with 'for' or 'foreach'.

1. Current region:
![image](https://user-images.githubusercontent.com/23723575/149719979-dc83676b-56c1-4fa9-8a18-bcb586e5b53f.png)

2. Desired region:
![image](https://user-images.githubusercontent.com/23723575/149719821-ff7409a7-d675-45ed-a001-ad6fe4c677d1.png)

Reference: https://youtrack.jetbrains.com/issue/RSRP-487549

**Comment by sharwell** [comment] 2022-01-20 00:34
I tried to reproduce this, but found that collapsing regions are not provided for preprocessor directives at all:

![image](https://user-images.githubusercontent.com/1408396/150240738-70c0ad4e-363c-444a-a2fd-d2dda4249c03.png)

Can you provide a more detailed set of steps to reproduce this?

**Comment by CyrusNajmabadi** [comment] 2022-01-20 01:29
I get regions @sharwell 

![image](https://user-images.githubusercontent.com/4564579/150245790-588183c0-e96b-4f45-a488-4f7058d3946a.png)

I think they have to have at least 2+ lines in them though.

**Comment by sharwell** [comment] 2022-01-20 16:07
I'm now able to reproduce this, but only if the `#elif` line is indented. Since this is not a current or planned supported formatting scenario (#12306), I'll mark this as help wanted.

**Comment by kelicto** [comment] 2022-01-24 01:13
If the plug-in can support it, it is also a great solution.

**Comment by CyrusNajmabadi** [comment] 2024-12-03 23:58
Closing as this is not an area we are investing in.

**Closed by CyrusNajmabadi** 2024-12-03 23:58 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, IDE-Formatter
