### ISSUE TITLE
Collection Initializer cannot handle Extensions akin to `IEnumerable<T>.Add(IEnumerable<T>)` ( `IDE0028` vs `CS0029`)

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#72460] opened 2024-03-08 13:20 UTC
**Version Used**: 
Visual Studio: Version 17.9.2
dotnet: 6.0.419

**Steps to Reproduce**:

1. have legacy Extension-Code like this
```cs
public class Class1
{
  public void Issue()
  {
    int[] numbers = [1, 2,3];
    Dictionary<string, int> dict = new() { numbers.Select(i => new KeyValuePair<string, int>(i.ToString(), i)) };
  }

  public void Issue2()
  {
    Dictionary<string, int> dict = new() { GetPairs() };
  }

  private static ICollection<KeyValuePair<string, int>> GetPairs() => throw new NotImplementedException();
}


public static class MyExtensions2
{
  public static void Add<T, TEnumElement>(this ICollection<T> collection,
    IEnumerable<TEnumElement>? elements)
    where TEnumElement : T
  {
    if (elements is null)
      return;
    ArgumentNullException.ThrowIfNull(collection);
    if (collection is List<T> list)
      list.AddRange((IEnumerable<T>)elements);
    else
      foreach (T element in elements)
        collection.Add(element);
  }
}
```
2. invoke CodeFix
![image](https://github.com/dotnet/roslyn/assets/71026023/b54fc03f-83c6-4eaa-b4aa-4baa6f0fca2a)

3.  get compiler error 
![image](https://github.com/dotnet/roslyn/assets/71026023/fc9cdaac-ab8e-4fc6-bef5-0143675db44c)

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

- `IDE0028` Collection initialization can be simplified
- `CS0029` Cannot implicitly convert type 'System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<string, int>>' to 'System.Collections.Generic.KeyValuePair<string, int>'	ClassLibrary2	D:\repos\WinFormsApp1\ClassLibrary2\Class1.cs

**Expected Behavior**:
something like
```cs
Dictionary<string, int> dict = [.. GetPairs()];
```
![image](https://github.com/dotnet/roslyn/assets/71026023/745be293-396c-44d7-9f5c-45bc8563dd23)

**Actual Behavior**:
- IDE0028 is very eager to find "...Add(...)" Methods, however does not care if it produces valid code.
- Collection Initalizer cannot handle Dictionaries/KeyValuePairs very well (see just above)

**Notes**:

we've experienced the same Problem with Lists/Collections (ie Generics with Arity=1), however I'm unable to get a working minimal example:
(in this case `ExecuteSync()` returns an `ICollection<string?>`, but we know it's exactly one element so capacity=2)
![image](https://github.com/dotnet/roslyn/assets/71026023/59876d5f-4c0e-481d-8a32-69a15246ed5e)

![image](https://github.com/dotnet/roslyn/assets/71026023/792fdc2b-edc9-4b67-8c53-647a450ac2d6)

![image](https://github.com/dotnet/roslyn/assets/71026023/8b5380b2-5703-4398-a2db-cc22312f10e6)

corrected (and working):
![image](https://github.com/dotnet/roslyn/assets/71026023/c4a9dc01-a357-4813-bb7b-11c24fdab33d)

**Comment by sharwell** [comment] 2024-03-08 14:34
This is also covered in #71240

**Comment by CyrusNajmabadi** [comment] 2024-07-11 17:13
Dupe of https://github.com/dotnet/roslyn/issues/71240

**Closed by CyrusNajmabadi** 2024-07-11 17:13 UTC
Labels: Area-Language Design, New Feature - Collection Expressions
