### ISSUE TITLE
CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider threw exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34535] opened 2019-03-28 06:36 UTC
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBase(BaseExpressionSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpressionHelper(Binder binder,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpression(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,Binder& binder,ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position,SyntaxNode node,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.ReplaceDocCommentTextWithTag.AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider.TryRegisterSeeCrefTagIfSymbol(CodeRefactoringContext context,SemanticModel semanticModel,SyntaxToken token,TextSpan replacementSpan,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ReplaceDocCommentTextWithTag.AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by heejaechang** [comment] 2019-03-28 06:37
use NFW or vsdata.io feature dashboard fault page to find dump.

**Comment by jinujoseph** [comment] 2019-04-03 19:40
@ivanbasov do you see this being hit in watson

**Comment by ivanbasov** [comment] 2019-04-03 19:48
@jinujoseph @heejaechang no same issues found in Watson

**Comment by jinujoseph** [comment] 2019-05-30 07:35
Duplicate of https://github.com/dotnet/roslyn/issues/29933

**Closed by jinujoseph** 2019-05-30 07:35 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, Investigation Required
