### ISSUE TITLE
Generic name angle brackets

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27236] opened 2018-05-30 00:00 UTC
I try to type next code in c# for Unity:

```csharp
private Animator anim;
void Awake()
{
    anim = GetComponent<Animator>();
}
```

Lets jump to the problem line of code:

```csharp
anim = GetComponent<Animator>();
```

I type from the keyboard:
&quot;anim = get&quot; 
and VS suggests me to use GetComponent, GetComponent&lt;&gt; and so on.
I choose 'GetComponent&lt;&gt;'
WITH ANGLE BRACKETS, but it inserts 'GetComponent', and not expected GetComponent&lt;
WITH LEFT ANGLE BRACKET

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/200105/generic-name-angle-brackets.html
VSTS ticketId: 569079_
_These are the original issue comments:_

David Poeschl [MSFT] on 3/13/2018, 10:42 AM (77 days ago): <p>The behavior you're seeing is happening on Tab/Enter or click, correct? If you commit with `&lt;`, then it will result in `GetComponent&lt;&gt;`, with the caret between the `&lt;&gt;` and it will be in brace completion mode, which means once you've finished typing the type arguments, you can press `&gt;` and it will overtype the existing `&gt;`. Can you give this a try and see if you like using completion this way?</p>
Denis Op on 3/13/2018, 11:17 AM (77 days ago): <a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/24763-vs-generic-name-angle-brackets.png">vs-generic-name-angle-brackets.png</a><p>If I type 'get', so VS opens menu and there is selected string "GetComponent", I press ENTER or select with the mouse next string "GetComponent&lt;&gt;", and my word 'get' changes into 'GetComponent', but there are no<code>&lt;</code></p><p>only blinking text cursor at the end of 'GetComponent'.</p>

Denis Op on 3/13/2018, 11:20 AM (77 days ago): <p>If I manual type GetComponent<code>&lt;</code>, VS adds <code>&gt;</code>and set cursor inside of them.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by wachulski** [comment] 2018-06-04 09:58
![gh-27236](https://user-images.githubusercontent.com/1669844/40911074-270e1566-67ee-11e8-93e4-b90c35ed4c0d.gif)
To depict the problem.

After a few secs delay I type `<` to get `<>` completion and then I type `string>` which puts caret right after `>` to manually complete with `();`

**Comment by wachulski** [comment] 2018-06-04 10:00
I understand the expected behavior is to get `GetComponent<|>` where `|` is the caret position. I'm looking into it why it does not happen.

**Comment by wachulski** [comment] 2018-06-05 06:46
Here I share what I found:

`Microsoft.CodeAnalysis.CSharp.Completion.Providers.CompletionUtilities.GetDisplayAndInsertionText`:

```csharp
public static (string displayText, string insertionText) GetDisplayAndInsertionText(ISymbol symbol, SyntaxContext context)
{
    var insertionText = GetInsertionText(symbol, context);
    var displayText = symbol.GetArity() == 0 
        ? insertionText 
        : string.Format("{0}<>", insertionText);

    return (displayText, insertionText);
}

public static string GetInsertionText(ISymbol symbol, SyntaxContext context)
{
    if (CommonCompletionUtilities.TryRemoveAttributeSuffix(symbol, context, out var name))
    {
        // Cannot escape Attribute name with the suffix removed. Only use the name with
        // the suffix removed if it does not need to be escaped.
        if (name.Equals(name.EscapeIdentifier()))
        {
            return name;
        }
    }

    if (symbol.Kind == SymbolKind.Label &&
        symbol.DeclaringSyntaxReferences[0].GetSyntax().Kind() == SyntaxKind.DefaultSwitchLabel)
    {
        return symbol.Name;
    }

    return symbol.Name.EscapeIdentifier(isQueryContext: context.IsInQuery);
}
```

I conclude this is by design as `GetInsertionText` does not handle generic angle brackets, but `displayText` deliberately takes this into account.

**Comment by sharwell** [comment] 2023-08-22 16:30
Design review conclusion: The current behavior is **By Design**. Users are not generally expected to complete words by typing <kbd>Enter</kbd> or <kbd>Tab</kbd> (it is allowed, but unnecessary). Rather than press <kbd>Enter</kbd>, users should press either <kbd>&lt;</kbd> to complete the identifier and insert the generic brackets, or type <kbd>(</kbd> to complete the identifier and insert the parentheses. This approach involves fewer keystrokes and provides consistent support for cases where generic type inference is involved (i.e. the generic method will be invoked without including the generic brackets at all).

**Closed** 2023-08-22 16:30 UTC
Labels: Bug, Area-IDE, Resolution-By Design, Developer Community, IDE-IntelliSense
