### ISSUE TITLE
IOperation: VB - need to figure out what is the right way to expose various Bound...Placeholder nodes

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8905] opened 2016-02-19 00:54 UTC
Right now, it looks like the nodes are exposed with OperationKind.None and no additional useful information except the Type. Consumers should be able to make sense what these nodes are about, or the nodes shouldn't be exposed.

**Comment by jinujoseph** [comment] 2017-07-03 23:55
dupe of https://github.com/dotnet/roslyn/issues/18548

**Closed by jinujoseph** 2017-07-03 23:55 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, Concept-API, Language-VB, New Feature - IOperation
