### ISSUE TITLE
Bad MSIL code generated for expression causing incorrect return value when using null operator with generic type constructor

### ISSUE THREAD

**Issue by lucasseries900** [dotnet/roslyn#23163] opened 2017-11-14 19:00 UTC
64 bit Microsoft Windows 7 Enterprise OS
OS Version: 6.1.7601 Service Pack 1 Build 7601
.Net Version: 4.6.1590
Visual Studio Version: 15.3.3

**Steps to Reproduce**:

1. See stack over flow link for simple vb.net console applications that show how to reproduce.
2. https://stackoverflow.com/questions/47278596/null-operator-returns-incorrect-value-when-using-generic-type-constructor-v
3. 

Expected the output of         Console.WriteLine(obj1.MyDate) and Console.WriteLine(obj2.CurrentDate) to be the same for the first console application. This one uses the type constructor.

Actual Output
Console.WriteLine(obj1.MyDate) = 11/13/2017 8:25:00 AM
Console.WriteLine(obj2.CurrentDate) = 2/24/0010 4:56:53 AM

Workaround 1 - Use long hand version in CurrentDate property. Change CurrentObject1?.MyDate to If(CurrentObject1 IsNot Nothing, CurrentObject1.MyDate, Nothing)

Workaround 2 - Don't use generic type constructor. This is demonstrated in the second console application.

**Comment by jcouv** [comment] 2017-11-24 21:58
@AlekseyTs I think this is a duplicate of an issue you recently fixed with PR https://github.com/dotnet/roslyn/pull/23359. 
Could you confirm and close? Thanks

**Comment by AlekseyTs** [comment] 2017-11-27 22:12
Yes, already fixed by that PR.

**Closed by AlekseyTs** 2017-11-27 22:12 UTC
Labels: Area-Compilers, Language-VB
