### ISSUE TITLE
GenerateDocumentationFile causes CS warnings to appear in Resources.Designer.cs

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53729] opened 2021-05-27 20:47 UTC
**Version Used**: 16.10.0

I think CS warnings for documentation comments should never appear in auto-generated files. There are no warnings when GenerateDocumentationFile is false, so there should be no warnings in auto-generated files when GenerateDocumentationFile is true. It looks like the code is indeed generated incorrectly, but that doesn't change anything about the previous two statements.

![image](https://user-images.githubusercontent.com/8040367/119894744-fb340280-bf0a-11eb-99a1-0cfdd46f18a7.png)

Full repro: [Repro.zip](https://github.com/dotnet/roslyn/files/6556702/Repro.zip)

Resource file being included (real-life example was a SQL file that was truncated by the resource code generator when included in the XML comment):

```

/
```

Problematic excerpt from Resources.Designer.cs:

```cs
/// <summary>
///   Looks up a localized string similar to 
////.
/// </summary>
internal static string SomeResourceFile {
    get {
        return ResourceManager.GetString("SomeResourceFile", resourceCulture);
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
```

Specific errors:

![image](https://user-images.githubusercontent.com/8040367/119894927-39c9bd00-bf0b-11eb-818a-fb195ef813a9.png)

![image](https://user-images.githubusercontent.com/8040367/119894894-2f0f2800-bf0b-11eb-8bc9-62701c664b2c.png)

![image](https://user-images.githubusercontent.com/8040367/119894847-1bfc5800-bf0b-11eb-83ea-2fbf378d4f39.png)

**Comment by jnm2** [comment] 2021-05-27 21:55
Also, there does not appear to be a way to instruct the Resources.Designer.cs generator to stop putting file content in XML comments:

https://github.com/dotnet/msbuild/blob/v16.10.0/src/Tasks/system.design/stronglytypedresourcebuilder.cs#L562-L593

It looks like CodeDom itself is at fault when it generates invalid C# syntax for CodeCommentStatement.

**Comment by AraHaan** [comment] 2021-05-27 22:12
I think I know why, on that line it wants to output 2, and possibly recurse agan and write 2 more ``//``'s on that line screwing it up.

**Comment by jnm2** [comment] 2021-05-27 23:12
On that line it outputs `///` because of `string commentLineStart = e.DocComment ? "///" : "//";` just above. Then the next character of `value` that it writes is a single `/`. This breaks any time a forward slash follows a newline in `CodeComment.Text`.

**Comment by jnm2** [comment] 2021-05-27 23:58
A workaround is to put this in .editorconfig:

```ini
[*.Designer.cs] # Workaround for https://github.com/dotnet/roslyn/issues/53729
dotnet_diagnostic.CS1570.severity = none
dotnet_diagnostic.CS1587.severity = none
```

**Comment by jaredpar** [comment] 2021-07-13 21:02
Closing because this behavior is "By Design" and I don't really see us changing it here. The compiler itself has very little understanding of generated code in terms of how it handles diagnostics. That is true for the types of files that we register as generated as well as the behavior we tweak for those files (think it's pretty much just nullable diagnostics at this point). 

The solution here is to either generate the correct code or to disable the warning in editorconfig for that pattern of files (as you showed in the sample above)

**Closed by jaredpar** 2021-07-13 21:02 UTC
Labels: Area-Compilers, Resolution-By Design

**Comment by AraHaan** [comment] 2021-07-14 20:57
While it's nice I do prefer the compiler to default ignore files marked with ``// <autogenerated/>`` (or any other similar comments at top of the file) where it would actually ignore them unless they opted into emitting warnings for those files.

This is because I do not like explicitly suppressing warnings either in an ``.editorconfig`` file (which then would become per-project instead of per-solution), in the solution file itself, in any other files like ``Directory.Build.props``, ``Directory.Packages.props``, etc. I just overall think it's cleaner if the warnings is avoided by default by having the compiler ctually check for those comments at the top of said files to control those warnings being emitted (which should be trivial too) and *should* not break anything either. The opt-in could be an MSBuild property as well like ``$(EnableGeneratedFileWarnings)`` and default to ``false``.

**Comment by jnm2** [comment] 2021-07-15 00:36
Brought the issue to https://github.com/dotnet/msbuild/issues/6677.

**Comment by jnm2** [comment] 2021-07-15 00:48
@AraHaan The editorconfig workaround is a per-solution workaround. I have not yet seen a project using editorconfig that didn't have a solution-wide .editorconfig file.

**Comment by AraHaan** [comment] 2021-07-15 01:25
Ah for that kind of setup take a look at: https://github.com/Elskom/Sdk/ (that does not have a solution wide .editorconfig (they are in the directories of every single csproj file there).

Note: do not forget to add ``--recursive`` to the clone command if using command line to clone.

**Comment by jnm2** [comment] 2021-07-15 14:28
@AraHaan I believe there would be nothing stopping you from adding a solution-wide .editorconfig file while keeping the project-specific ones.

**Comment by jnm2** [comment] 2021-07-24 14:02
Filed at https://github.com/dotnet/runtime/issues/56267 as well at the MSBuild team's request.
