### ISSUE TITLE
Remove BinderOpt and UseSetterForDefaultArgumentGeneration workaround in C# bound nodes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20787] opened 2017-07-11 15:58 UTC
BoundIndexerAccess and BoundObjectInitializerMember have temporary workaround for IOperation implementation. We should remove the temporary fields BinderOpt and UseSetterForDefaultArgumentGeneration

**Comment by jinujoseph** [comment] 2017-09-29 21:22
dupe of https://github.com/dotnet/roslyn/issues/19603

**Closed by jinujoseph** 2017-09-29 21:22 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
