### ISSUE TITLE
ConstructorArguments inexplicably empty

### ISSUE THREAD

**Issue by M-Pixel** [dotnet/roslyn#22501] opened 2017-10-03 21:03 UTC
**Version Used**: Microsoft.CodeAnalysis.CSharp 2.3.2

**Steps to Reproduce**: Create a C# netcoreapp1.1 project with the following source code

``` csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

class Program
{
	static void Main(string[] args)
	{
		var someScript = "public class MyAttributeAttribute : Attribute { MyAttribute(string message) {} };\n" +
		                 "[MyAttribute(\"Foo\")] public class FooBar {}";
		
		var compilation = CSharpCompilation.Create("CodeGeneration")
			.WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
			.AddSyntaxTrees(CSharpSyntaxTree.ParseText(someScript));

		foreach (var tree in compilation.SyntaxTrees)
		{
			var semanticModel = compilation.GetSemanticModel(tree);
			foreach (var node in semanticModel.SyntaxTree.GetRoot().DescendantNodes().OfType<MemberDeclarationSyntax>())
			{
				var nodeSemantic = semanticModel.GetDeclaredSymbol(node);
				if (nodeSemantic == null)
					continue;

				foreach (var attribute in nodeSemantic.GetAttributes())
				{
					Console.WriteLine($"{attribute.AttributeClass.Name} has {attribute.ConstructorArguments.Length} args.");
					foreach (var argument in attribute.ConstructorArguments)
					{
						Console.WriteLine($"\t{argument}");
					}
				}
			}
		}
	}
}
``` 

**Expected Behavior**: The number **1** and the value **Foo** are printed

**Actual Behavior**: The number **0** is printed

**Comment by M-Pixel** [comment] 2017-10-03 21:26
This is a workaround that works:

```csharp
var arguments = node.DescendantNodes()
	.First((d) => d.IsKind(SyntaxKind.Attribute))
	.DescendantNodes()
	.OfType<AttributeArgumentSyntax>()
	.ToImmutableArray();
Console.WriteLine($"Args via LINQ = {arguments.Length}");
foreach (var argument in arguments)
{
	Console.WriteLine($"\t{argument.Expression}");
}
```

... which makes me suspect even more strongly that `ConstructorArguments.Length == 0` is a bug.

**Comment by jcouv** [comment] 2017-11-02 02:20
Confirmed there is a problem.
Simplified the repro a bit (below). We'll need to investigate further.

```C#
        [Fact]
        void Test()
        {
            var source = @"
public class MyAttributeAttribute : System.Attribute { MyAttribute(string message) { } }

[MyAttribute(""hello"")] 
public class C {}
";

            //var comp = CreateStandardCompilation(source); // doesn't repro
            var comp = CSharpCompilation.Create("CodeGeneration").AddSyntaxTrees(CSharpSyntaxTree.ParseText(source)); // does repro

            var tree = comp.SyntaxTrees.Single();
            var semanticModel = comp.GetSemanticModel(tree);
            var c = comp.GetMember("C");
            var attribute = c.GetAttributes().Single();
            Assert.Equal(1, attribute.ConstructorArguments.Count()); // expected 1, but actual is 0
        }
```

**Comment by jcouv** [comment] 2017-11-02 19:27
@M-Pixel The problem is that the constructor for your attribute type is not properly named.
Changing `MyAttribute(string message) {}` to `MyAttributeAttribute(string message) {}` makes things work as expected.
Closing the issue as by-design.

**Closed by jcouv** 2017-11-02 19:27 UTC
Labels: Area-Compilers
