### ISSUE TITLE
New editorconfig editor doesn't save any changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54530] opened 2021-07-01 18:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-editorconfig-editor-doesnt-save-any/1435579)._

---
[severity:Other]
The new enditorconfig editor doesn't save any changes I've made. It's totally useless for me. Thanks for repair!

---
#### Feedback Bot on 5/30/2021, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/2/2021, 10:02 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-07-02 07:39
Duplicate of https://github.com/dotnet/roslyn/issues/54556.

**Closed** 2021-07-09 00:56 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate
