### ISSUE TITLE
Nullability dropped in binding typeof()

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#32447] opened 2019-01-14 23:18 UTC
The compiler accepts `typeof(string?)`, but totally ignores the nullability annotation.

In my opinion the nullability annotation should be forbidden here.

**Comment by jcouv** [comment] 2019-01-31 23:37
Duplicate of https://github.com/dotnet/roslyn/issues/29894

**Closed by jcouv** 2019-01-31 23:37 UTC
Labels: Area-Compilers, Bug, Need Design Review, New Language Feature - Nullable Reference Types
