### ISSUE TITLE
Collection Expressions: Extra array copy when spreading `IEnumerable<T>` to `Span<T>`.

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#74292] opened 2024-07-08 21:42 UTC
[SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lQDMmM6AwugN7Lq2bFTboCyAFAEoCmAhsAPIA7ADYBPAMoAHbgIA8ASwEAXAHzoAzlIEBKKjToBfPbSP1MTAHKssheUtWcBAVwC2nAE7cARkM47qSOkCWVgBtADow9AcXdy8fAF0tfACDZH0gA=)

Given this code:

```C#
using System;
using System.Collections.Generic;
public class C {
    public void M(ReadOnlySpan<int> span) {
    }
    
    public void N(IEnumerable<int> enumerable) {
        M([.. enumerable]);
    }
}
```

The C# compiler produces:

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue | DebuggableAttribute.DebuggingModes.DisableOptimizations)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[assembly: AssemblyVersion("0.0.0.0")]
[module: UnverifiableCode]
[module: RefSafetyRules(11)]

public class C
{
    public void M(ReadOnlySpan<int> span)
    {
    }

    [NullableContext(1)]
    public void N(IEnumerable<int> enumerable)
    {
        List<int> list = new List<int>();
        IEnumerator<int> enumerator = enumerable.GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                int current = enumerator.Current;
                list.Add(current);
            }
        }
        finally
        {
            if (enumerator != null)
            {
                enumerator.Dispose();
            }
        }
        M(new ReadOnlySpan<int>(list.ToArray()));
    }
}

```

The resulting code has far more allocations than expected, especially the final `ToArray()` call. Consider the following improvements:

1. If available, use the `IEnumerable<T>.TryGetCount(...)` extension method to set a capacity for the `List<T>`. Or, use the count to produce an inline array.
2. If available, use `CollectionsMarshal.AsSpan(...)` to avoid calling `List<T>.ToArray()``.

**Comment by CyrusNajmabadi** [comment] 2024-07-08 21:58
@RikkiGibson we've talked about '1' and my recollection is that there was some oogyness on that.  '2' def seems like something we want here.  Going from List->Span forcing an allocation/copy seems really undesirable.  Either we should own the array ourselves (with helpers to grow it as necessary), or we should use List, but then get at hte underlying span cheaply.

**Comment by RikkiGibson** [comment] 2024-07-08 22:07
This appears to be a duplicate of #71755 (though that one doesn't show the simple reproducer in the issue description, which makes it a little more time consuming to figure out).

Up to date compiler produces this: [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4D0BmMzEgYRIG8CSuyH0KSAsgAoASgFMICAPIwANgE8AygAcIMADywALgD4SAZ1UwAlO07cAvua7WeZfgDkh5Oppi6SYmAFcwYgE4QwLJiphz43JGCQgDaAHRxnj5+gcFiALrGNBGWBBZAA==)

```cs
    public void N(IEnumerable<int> enumerable)
    {
        List<int> list = new List<int>();
        list.AddRange(enumerable);
        M(new ReadOnlySpan<int>(list.ToArray()));
    }
```

I think the path forward for these specific cases is to start calling `Enumerable.ToArray()` for single-spread of an IEnumerable to non-List type. This will knock out `T[]`, `ImmutableArray<T>`, `Span<T>` and `ReadOnlySpan<T>` cases nicely.

For collection-exprs of multiple elements containing spreads of `IEnumerable<T>`s, let's just keep using the intermediate List and we can certainly use the Marshal method to get a span in those cases instead of `ToArray()`.

**Comment by DustinCampbell** [comment] 2024-07-09 18:47
FWIW, we _do_ use `ImmutableCollectionsMarshal`, so it feels like `CollectionsMarshal` is just undone work? [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4DizsA6AYQHsAbNgUwGMAXKFjADODAJJgwAV14RgXGoQDMZTCSYkA3gRI6yy8VJlzOAQQBOZiAE8APLF4A+EgFkAFOUV2YjkpxiSwTktjAEpNbV1I9AB2EgBtBgZff0DgrgBdBUiAXwJsoA==)

**Comment by RikkiGibson** [comment] 2024-07-09 22:29
closing out as duplicate of #71755

**Closed by RikkiGibson** 2024-07-09 22:29 UTC
Labels: Resolution-Duplicate, Area-Compilers, Code Gen Quality, untriaged, New Feature - Collection Expressions
