### ISSUE TITLE
NuGet build task pollutes .NET Framework/portable builds with a warning "The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute but not found"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6840] opened 2015-11-17 20:49 UTC
Build any .NET Framework/portable build, get lots of:

```
         Building solution configuration "Debug|Mixed Platforms".
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
       The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
     2>Project "c:\roslyn\Roslyn.sln" (2) is building "c:\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj" (3) on node 1 (default targets).
```

**Comment by kjeremy** [comment] 2015-12-08 16:56
:+1:

**Comment by jasonmalinowski** [comment] 2015-12-08 17:27
This is a dupe of NuGet/Home#1814. (Or it's a dupe of this, not sure how we want to track these.)

**Comment by davkean** [comment] 2015-12-08 20:40
We should revert the dependency, NuGet build tasks shouldn't know anything about BeforeGeneateProjectPriFile.

**Comment by jasonmalinowski** [comment] 2015-12-08 22:09
@davkean: agreed. The dependency landed this way purely for, uh, expediency when this was all being built.

**Comment by jeanie77** [comment] 2016-01-14 11:12
Any news on this? Did anyone succeeded in getting rid of those messages?

**Comment by jasonmalinowski** [comment] 2016-01-14 17:49
@jeanie77, this bug is still open, so no progress has been made. Right now I'm heads down trying to get some feature work done before an upcoming preview that is taking priority over bug fixes such as this one.

**Comment by jasonmalinowski** [comment] 2016-01-26 22:05
Now that we're tracking NuGet bugs over in the NuGet GitHub org, we'll let NuGet/Home#1814 be the primary bug and this a dupe.

**Closed** 2016-01-26 22:05 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
