### ISSUE TITLE
GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider encountered an error

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19749] opened 2017-05-24 14:59 UTC
**Version Used**: 15.3 Preview 1

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Open src\Features\VisualBasic\Portable\AddImport\VisualBasicAddImportCodeFixProvider.vb
3. Place care on line 180

**Expected Behavior**:

No message.

**Actual Behavior**:

> 'GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider' encountered an error and has been disabled.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.HandleNonSelectionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Neme12** [comment] 2018-03-10 01:46
From looking at the commit history, that code should now be in VisualBasicAddImportFeatureService.vb on line 88, but I couldn't reproduce the issue there.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 22:36
No repro, and prism shows no faults here.  I'm going to close this out as not actionable.

**Closed by CyrusNajmabadi** 2022-10-28 22:36 UTC
Labels: Bug, Area-IDE
