### ISSUE TITLE
Change access level

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57273] opened 2021-10-20 19:51 UTC
Customer ask: 

>Have a refactoring that can change the accessibility of a member. If the type itself is internal and you want to make the member/property public then also make the type public. Similarly if you are making a public member internal, and nothing else expose it then make the type internal.

**Comment by vatsalyaagrawal** [comment] 2021-11-09 05:48
Design meeting notes:

We need more information about the underlying scenario. What is the user trying to do? Better understanding of the intent will help us design the correct solution.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:40
Closing as by design.

**Closed by CyrusNajmabadi** 2024-10-22 18:40 UTC
Labels: Area-IDE, Feature Request, Need Design Review
