### ISSUE TITLE
Provide documentation for IDExxx analyzers

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45264] opened 2020-06-17 21:00 UTC
I think it may be a good idea to follow the same process followed in dotnet/roslyn-analyzers.

1. All the analyzers should have documentation.
2. The helpLinkUri for them will be the specific-analyzer documentation instead of a Bing search.

The benefits includes:

1. Developers facing a specific warning/suggestion will always find a well-documented page with information about the specific warning/suggestion.
2. Developers can find more information about the editorconfig options explained (this is specific to analyzers that has configurable options)
3. The current Bing search may/may not provide useful information. But, the documentation will provide these information.

cc: @333fred

**Comment by 333fred** [comment] 2020-06-18 00:19
@sharwell, as you've looked at this type of stuff before.

**Comment by jmarolf** [comment] 2020-06-18 00:45
I generally agree that anything that could potentially be and error (and therefore appear in the error list) should link to a doc page instead of doing a web search.

**Comment by mavasani** [comment] 2020-06-20 02:20
Duplicate of https://github.com/dotnet/roslyn/issues/41324

**Closed by mavasani** 2020-06-20 02:20 UTC
Labels: Area-IDE, Feature Request
