### ISSUE TITLE
Internal error in Immediate Window when trying to create an already existing variable

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#22599] opened 2017-10-09 14:23 UTC
**Version Used**: 
D15svc 27004.2002
**Steps to Reproduce**:
1. Create a new C# console app.
2. Add some code to create a variable and add a breakpoint.
```
string s = "foo";
System.Diagnostics.Debugger.Break();
```
3.  Start Debugging
4. Open immediate window and try to create the existing variable s. Do something like:
```
string s = "asdf";
````

**Expected Behavior**:
It should throw an error explaining that the variable already exists.
**Actual Behavior**:
It sends an error saying "Internal error in the C# compiler"

No other ill effects appear to occur. Immediate window still works properly after the error.

**Comment by tmat** [comment] 2017-10-09 18:47
@ivanbasov Could you investigate? This seems like a very basic scenario. 
/cc @jinujoseph

**Comment by ivanbasov** [comment] 2017-10-09 19:59
I believe that the root cause is the same as at https://github.com/dotnet/roslyn/issues/22474. Not sure if it meets the bar for 15.5 but it would be nice to schedule it at least for 15.6.

**Comment by ivanbasov** [comment] 2017-11-01 01:00
@jinujoseph, I could not find an easy way to fix yet. I'm not sure that this meets 15.5 bar: it seems that this is a bad diagnostic message. I suggest to punt it to 15.6 and consider moving it back if we will find an the easy fix.

**Comment by ivanbasov** [comment] 2018-01-16 21:29
Resolved with https://github.com/dotnet/roslyn/pull/24198

**Closed by ivanbasov** 2018-01-16 21:29 UTC
Labels: 4 - In Review, Area-Interactive, Interactive-Debugging, _Product-level triaged
