### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit64 on PR #9560

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9573] opened 2016-03-08 18:26 UTC
PR: [#9560](https://github.com/dotnet/roslyn/pull/9560) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4921/

**2 Test Failures:**
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.GenerateEvent.GenerateEventTests.TestGenerateEventForRemoveEventMultiLineLambdaIntoCSharp
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests+VisualBasicConflicts.RenameEvent

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by DustinCampbell** [comment] 2016-03-09 17:49
@jasonmalinowski, is this a dupe of the cross language flakiness that's already been fixed?

**Comment by jasonmalinowski** [comment] 2016-03-09 19:25
Yes, this is a dupe of #9308. Since this was yesterday morning's merge, the fix wasn't in future or carried along this PR yesterday morning. I've verified the fix was not included by inspecting the raw DLLs from the build artifacts.

**Closed by jasonmalinowski** 2016-03-09 19:25 UTC
Labels: Area-IDE, Flaky, Test, Urgency-Now
