### ISSUE TITLE
Tolerate ref/out assignments when throwing after the method returns

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40623] opened 2019-12-27 17:01 UTC
**Version Used**: VS 16.4.2

There is a purist argument that ref/out assignments and returning a value happen at different times, but this seems like it would fit with other null-tracking assumptions like nullability of properties accessed multiple times.

```cs
#nullable enable

class C
{
    string[] M()
    {
        var array = new string[1];

        // CS8601 Possible null reference assignment.
        //                 ↓
        if (!TryGetFoo(out array[0]))
            throw new ArgumentException("...");

        return array;
    }

    bool TryGetFoo([NotNullWhen(true)] out string? foo)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by jaredpar** [comment] 2021-01-08 07:22
Closing as this behavior is "By Design" at this point. The argument to a `ref / out` needs to match nullability in the declaration type even if we can later change the flow state to be non-null.

**Closed by jaredpar** 2021-01-08 07:22 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Nullable Reference Types
