### ISSUE TITLE
"Attempted to read or write protected memory." in metadata reader.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#13123] opened 2016-08-12 16:51 UTC
We had a test failure here: 
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/2337/

With this stack:
09:34:51   Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
09:34:51      at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
09:34:51      at Microsoft.CodeAnalysis.PEModule.GetBaseTypeOfTypeOrThrow(TypeDefinitionHandle typeDef) in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 860
09:34:51      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 429
09:34:51      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(ConsList`1 basesBeingResolved) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 406
09:34:51      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 1603
09:34:51      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeSymbol.cs:line 694

**Comment by tmat** [comment] 2016-08-12 19:29
@dotnet/roslyn-infrastructure why are there no artifacts?

**Comment by CyrusNajmabadi** [comment] 2016-09-06 20:50
Another case of this: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit64_prtest/516/console

**Comment by tmat** [comment] 2016-09-06 20:59
This is unlikely a bug in the compiler. Morel likely the component that manages metadata references for the tests disposes them too soon, or something like that.

**Comment by Pilchie** [comment] 2016-09-12 16:25
Dupe of https://github.com/dotnet/roslyn/issues/13243 I believe.

**Closed by Pilchie** 2016-09-12 16:25 UTC
Labels: Area-IDE, Bug
