### ISSUE TITLE
'ref var' should either not be nullable when initialized with non-nullable reference or produce a warning

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#42670] opened 2020-03-22 17:15 UTC
**Version Used**: 
```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

Compile and run the following code
```cs
#nullable enable
using System;
public class C {
    public static void Main() {
        string s = "";
        ref var x = ref s;
        x = null;
        s.ToString();
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8BiTdAG3ImHLgAI5NraBYAKAAEAmARnY4DMdbnQDCdAN7s6M4Vy6Tps5Rx4AGOlDoBeOgCI9AbiXKZCOADM6ANwgI6ADx11zVqMbanZT3WUoevGSgAOgAVAHsAZRgEAEtMAHMACgBKANkAX3YMoA

**Expected Behavior**:
Either
`warning CS8625: Cannot convert null literal to non-nullable reference type.` reported for `x = null` (the same behavior if you use `ref string x = ref s;`)
Or
`warning CS8619: Nullability of reference types in value of type 'string' doesn't match target type 'string?'.` reported for `ref var x = ref s;` (the same behavior if you use `ref string? x = ref s;`)

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Notes**
It seems that `ref var` case was overlooked when implementing the `var is nullable by default` part of this design: https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-12-18.
It currently behaves as neither nullable (no warnings on initialization) nor notnullable (no warnings on assignments with null).

**Comment by TessenR** [comment] 2020-03-22 18:26
Seems that the root cause is the same as https://github.com/dotnet/roslyn/issues/42018

**Comment by sharwell** [comment] 2020-03-22 21:26
Duplicate of #42018

**Closed by sharwell** 2020-03-22 21:26 UTC
