### ISSUE TITLE
Project items added via VS API are writing resulting formatted doc in wrong place

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#58311] opened 2021-12-13 23:45 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.1.0 Preview 2.0 [32001.329.main]

**Steps to Reproduce**:

1. Using a modified version of AddAnyItem extension which has this change: https://github.com/madskristensen/AddAnyFile/pull/101 
2. Add an editorconfig with the following rule enabled:
`csharp_style_namespace_declarations = file_scoped:warning`
3. In a C# project right-click and create a new folder `Foo`
4. Right-click on the `Foo` folder and Add...New Empty Item
![image](https://user-images.githubusercontent.com/4821/145905852-39f1315c-2807-4fb0-be34-f9a532fd30da.png)
4. Type `FooBar.cs` and Add

**Expected Behavior**:
The item is added into the `Foo` folder with `FooBar.cs` that has file-scoped formatted namespace

**Actual Behavior**:
A correctly formatted `FooBar.cs` is in the ROOT of the project, BUT ALSO a non-formatted `FooBar.cs` is in the `Foo` folder as well.

**What is Happening**:
When the item is added via this API, the following Roslyn API is executed:
https://cs.github.com/dotnet/roslyn/blob/ececd39a161603d008256f6540275e03c50b93f9/src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs#L248 but the `filePath` being passed in is not the full path, only the end filename root (thus `FooBar.cs` and not `Foo\FooBar.cs`).  This causes the problem that when this function calls into https://cs.github.com/dotnet/roslyn/blob/ececd39a161603d008256f6540275e03c50b93f9/src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs#L359 that it is writing to the wrong path that it was created if a folder was involved.

I cannot tell if this is happening due to the `AddFileFromTemplate` API being an error in not passing in full name

https://user-images.githubusercontent.com/4821/145906817-19133d83-e5c4-48ba-90b2-63de9a4bf45c.mp4

**Comment by davidwengier** [comment] 2021-12-15 00:59
Its not clear to me from your report, are you calling `AddFromTemplate` with the full path? That's certainly what Roslyn expects, and indeed is what the API expects per the documentation.

If you're calling it with the full path, but Roslyn is getting a relative path, then I would guess thats a bug on the project system, either csproj or CPS depending on whether you're using SDK style projects.

The other thing I don't really understand, is why there would be two files either way. If `FooBar.cs` is passed in to Roslyn, then it is going to read that file ([here](https://cs.github.com/dotnet/roslyn/blob/ececd39a161603d008256f6540275e03c50b93f9/src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs#L320)), format it, and write it back out. That file must have existed before Roslyn gets called though, as Roslyn doesn't create the file.

**Comment by davidwengier** [comment] 2021-12-15 01:03
The other thing to mention, if you're just looking for a way to call into this spot in Roslyn, and AddItemFromTemplate is causing issues, is perhaps you can find the EditorFactory for the item you added, and call [`NotifyItemAdded`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivseditorfactorynotify.notifyitemadded?view=visualstudiosdk-2022) for it directly. Again with the full path, but that is what Roslyn is responding too.

**Comment by timheuer** [comment] 2021-12-15 01:08
> Its not clear to me from your report, are you calling `AddFromTemplate` with the full path? That's certainly what Roslyn expects, and indeed is what the API expects per the documentation.

Yes, sorry the PR isn't the most current and the second arg is `item.FullName` in my updated code.  This is SDK style project (not sure if EnvDTE makes a distinction?).



> The other thing I don't really understand, is why there would be two files either way.

Best I can tell is Roslyn is getting the file of course because it is able to format it...but the associated path it is getting is not the correct path so the `filePath` in `formattedText.Write` call is incorrect...thus writing out a new file.

**Comment by davidwengier** [comment] 2021-12-15 01:36
> This is SDK style project (not sure if EnvDTE makes a distinction?).

The distinction is which project system implements the `AddFromTemplate` method. Being SDK style you'll be hitting CPS, which would mean [this method](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Automation/OAProjectItems.cs&version=GBmain&line=49&lineEnd=50&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). Looking at that code, I think I can see what is going on.

[This line](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Automation/OAProjectItems.cs&version=GBmain&line=88&lineEnd=89&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) is what is tripping you up I think: You're asking the project root item to add a new item "Foo\FooBar.cs", so that line resolves the directory for the root project item, and adds "FooBar.cs" on the end. What you should be doing is finding the project item for the "Foo" folder, and then telling it that you're adding "FooBar.cs", and then I think everything will work.

**Comment by timheuer** [comment] 2021-12-15 02:47
Interesting...I see that the method calls [this](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Automation/OAProjectItems.cs&version=GBmain&line=86&lineEnd=87&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) right before that...which is the same call when [this method](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Automation/OAProjectItems.cs&version=GBmain&line=157&lineEnd=158&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) is called -- which doesn't have the issue when I just use AddFromFile (everything works fine).  Are you saying that CPS is basically adding the file, doing the notification but in the NotifyFileAdded the path gets mangled because the CPS call is doing some node interpretation?

What's weird is Roslyn is definitely getting the right input so it knows the path

**Comment by davidwengier** [comment] 2021-12-15 02:49
> What's weird is Roslyn is definitely getting the right input so it knows the path

I find this very surprising. You can see under the debugger that Roslyn is getting the full file path?

Roslyn is reading the file passed in, formatting it, and writing it back out, without modifying the variable that was passed in. I don't see how this would be happening if the passed in path was correct.

**Comment by timheuer** [comment] 2021-12-15 03:02
I'm struggling to accurately debug all this - roslyn as a VSIX, this extension as a VSIX, and haven't even tried project system to see -- so all I know is the Roslyn formatting call is absolutely happening and writing the formatted file out.  Is the input to Roslyn not the path to read from but a handle to the file itself?

**Comment by davidwengier** [comment] 2021-12-15 03:13
No, the input to Roslyn is the path to the file. Let me see if I can install the extension and debug through it.

**Comment by timheuer** [comment] 2021-12-15 03:20
you'll need the modified version of the extension -- i have a version if you need it

**Comment by timheuer** [comment] 2021-12-15 03:28
The final output is what is confusing me as the project is now aware of the new directory/file (e.g., Foo\Class1.cs) but also one in the root.  So somewhere the project item is getting added correctly in two ways and not just on disk, but the project system is aware of it.

**Comment by davidwengier** [comment] 2021-12-15 03:42
I haven't dug in, but something in CPS/VS is swallowing the path.

In the extension the full path is there:
<img width="802" alt="Extension" src="https://user-images.githubusercontent.com/754264/146118876-d7911d27-a826-461c-829f-967d86023dfe.png">

That comes through to AddItemFromTemplate fine:
<img width="958" alt="CPS" src="https://user-images.githubusercontent.com/754264/146118898-2b90182e-c4e9-4da9-b054-fd0263339162.png">

But by the time it gets to Roslyn, its been changed and folder structures removed:
<img width="963" alt="Roslyn" src="https://user-images.githubusercontent.com/754264/146118952-258e747d-5fb2-4c0a-8762-21a9f47dc7bd.png">

I tried my suggestion of calling AddItemFromTemplate on the project item for the folder, and it seemed to work fine - the full path flowed through to Roslyn, and no file was written to the project root folder. I commented on your PR with the suggestion.

**Comment by timheuer** [comment] 2021-12-15 03:49
Thanks -- should this bug be moved to project system?  It's weird right that the path gets munged?  I had already started on the alternate path but there is an issue in that as well :-)

**Comment by davidwengier** [comment] 2021-12-15 03:52
For completeness, here is where the path is disappearing: https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Nodes/ProjectNode.cs&version=GBmain&line=4797&lineEnd=4799&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

I suspect this is by design, but @lifengl can probably confirm. I expect the correct usage of DTE is to call AddItemFromTemplate at the spot in the project you actually want it to be added :)

**Comment by timheuer** [comment] 2021-12-15 03:55
LOL comment on that line.  Narrator: We need it 🤣🤣

**Comment by davidwengier** [comment] 2021-12-15 04:10
I'm going to close this out, since its not a Roslyn bug, but I also don't think its a CPS bug either, it's just some bad assumptions by the extension. What is happening is:

1. Extension constructs a path `C:\code\project\a\b\c\d.cs`
2. Extension writes a file at that location
3. Extension calls AddItemToTemplate, essentially saying "Add a new file to the root of the project, and use this one as a template" (passes [VSADDITEMOP_CLONEFILE](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Package/Automation/OAProjectItems.cs&version=GBmain&line=78&lineEnd=79&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) as the operation)
4. CPS creates a new file in the project root folder, with the filename you specified (throwing out the rest of the path), and copies in the content
5. CPS tells Roslyn to format the file it just created

So end result is one formatted file, put there by CPS and formatter by Roslyn, and one unformatted file, put there by the extension and used as a template for the other one.

**Closed by davidwengier** 2021-12-15 04:10 UTC
Labels: Area-IDE, Concept-Continuous Improvement
