### ISSUE TITLE
CompareSymbolsCorrectlyAnalyzer throws NRE

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#49662] opened 2020-11-30 07:49 UTC
**Version Used**: Microsoft.CodeAnalysis.Analyzers Version=3.3.1, Visual Studio 16.9 preview 1

**Steps to Reproduce**:

You can see the exceptions when you build [StrongInject](https://github.com/YairHalberstadt/stronginject/tree/1.0.4) in visual studio or dotnet build.

If anyone can show me how to find the stack trace I'd be happy to post it here.

**Comment by Youssef1313** [comment] 2020-11-30 17:29
This analyzer is implemented in dotnet/roslyn-analyzers repo not dotnet/roslyn

**Comment by Youssef1313** [comment] 2020-11-30 17:30
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/4414

**Closed** 2020-11-30 17:59 UTC
Labels: Area-Compilers, untriaged
