### ISSUE TITLE
"extern" was removed with CTRL + K + D

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30814] opened 2018-10-27 09:23 UTC
1-

```csharp
[System.Runtime.InteropServices.DllImport(&quot;kernel32.dll&quot;)]
static extern IntPtr GetConsoleWindow();
```

2 - <kbd>Ctrl</kbd>+<kbd>K</kbd>, <kbd>D</kbd>

3-

```csharp
[System.Runtime.InteropServices.DllImport(&quot;kernel32.dll&quot;)]
private static IntPtr GetConsoleWindow();
```

Erro:
&quot;extern&quot; was removed

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/365138/extern-was-removed-with-ctrl-k-d.html
VSTS ticketId: 714100_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-10-28 20:29
Duplicate of #29561

**Closed by sharwell** 2018-10-28 20:29 UTC
