### ISSUE TITLE
Private field Name Convention

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44699] opened 2020-05-29 20:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1046765/private-field-name-convention.html)._

---
The name convention in the private fields is suggested to start with a underscore.
Example: private readonly IServiceProvider _serviceProvider;
But in the name suggestions there is no suggestion name that starts with a underscore.
So I suggest to add name suggestions starting with underscore on private fields.

---
#### Visual Studio Feedback System on 5/25/2020, 02:41 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-05-29 20:46
The naming suggestions use the naming style configured for the project to produce these suggestions. The default naming style does not include the `_` prefix, so the suggestions also do not. You can configure private fields to include a `_` prefix in an **.editorconfig** file, like this:

https://github.com/dotnet/roslyn/blob/c5e9838a758820843637508ebc0472b49180ec3a/.editorconfig#L107-L115

**Comment by CyrusNajmabadi** [comment] 2020-05-30 01:11
Closing out as this appears by design, and has a viable and supported path for the customer to get the behavior they want.

**Closed by CyrusNajmabadi** 2020-05-30 01:11 UTC
Labels: Area-IDE, Developer Community, IDE-CodeStyle, Question

**Comment by polina-kravchenko** [comment] 2024-11-15 10:20
Same issue after update of VS to version  17.12.0
