### ISSUE TITLE
Proposal: "with" expressions for mutable objects

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5676] opened 2015-10-04 14:04 UTC
This has been concluded in #5365 but I thought it deserves a separate ticket. Also it can be considered as an extension to #5172 for using `with` expressions on other types.

It basically provides a `With...End With`-like syntax for C# but as an *expression*.
``` 
var car = with carFactory.CreateCar() {
    Brand = "Ferrari",
    Model = "Enzo"
};
```
->
```
var car = carFactory.CreateCar();
car.Brand = "Ferrari";
car.Model = "Enzo";
```
However, you can ignore the returned value if you don't need it e.g. after `with car { ... };` you can continue to use the existing variable.

**Comment by orthoxerox** [comment] 2015-10-04 17:26
How will you reconcile the difference in semantics between `with`ing an immutable (create a copy and modify it) and a mutable (mutate the object passed to the expression) object?

**Comment by alrz** [comment] 2015-10-04 17:28
@orthoxerox `with mutableCar { ... }` vs existing syntax `immutableCar with { ... }`.

**Comment by orthoxerox** [comment] 2015-10-04 18:14
@alrz wouldn't this still be too confusing?

**Comment by alrz** [comment] 2015-10-04 18:19
@orthoxerox Programmers should be familiar with this kind of "confusing"! For example `const` in C++ is pretty confusing!
```cpp
const char* pstring = "";
char* const pstring = "";
const char* const pstring = "";
```
These are all different.

**Comment by MgSam** [comment] 2015-10-04 18:25
So because a completely separate language has a confusing design for a completely separate feature means it's ok for C# to add confusing features?

**Comment by aluanhaddad** [comment] 2015-10-04 21:06
Factory initializers are a good idea. Using the same keyword that is specifically intended for use in immutable context for a mutability oriented feature is not

**Comment by ashmind** [comment] 2015-10-04 21:42
Duplicate of #133?

**Comment by alrz** [comment] 2015-10-04 23:03
@ashmind the use case is partially the same but you didn't mentioned a practical syntax, it's the same as `with` for record types which as @orthoxerox mentioned these should be different to some degree.
However, the intention for this proposal is not limited to factory initialization, it's more of a `With...End With` syntax that actually covers the factory initialization too (that's why I didn't see your proposal in the first place) and followed by #5365 this shouldn't be limited to just properties.

**Comment by alrz** [comment] 2015-10-04 23:17
@aluanhaddad you're saying that this should use another keyword? my proposed syntax is based on the fact that these two basically do the same job with a different implementation. And since I'm against of totally immutable records (well, not algebraic types, just records; see [#206 comment](dotnet/roslyn/issues/206#issuecomment-145349482)) this would make sense that you actually decide how you want to do this when you are doing it — like C++ classes; you decide where you want to put your variable (stack or heap) just when you are declaring it not based on type.

**Comment by alrz** [comment] 2015-10-05 01:44
As an alternative syntax this could be done with no keyword at all e.g. a scope braces with a leading expression `var car = carFactory.CreateCar() { ... };`.

**Comment by gafter** [comment] 2015-10-05 16:46
@alrz This appears to be a dup of #133 with a different syntax. 
#5365 does not appear to have much to do with this proposal, even though it is a separate proposal for a similar construct.

**Closed by gafter** 2015-10-05 16:46 UTC
Labels: Area-Language Design
