### ISSUE TITLE
"args" variable does not show up in intellisense for top level statements (console template)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55969] opened 2021-08-27 18:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/args-variable-does-not-show-up-in-inte/1514531)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:vs 2019]
Using the new console app template, the "args" variable does not show up in intellisense. Once you've written it, it is valid and intellisense on the variable show up correctly, but just typing "ar" will not suggest "args". this was confusing to me as i didnt understand how to get the arguments for a top level statement app, and i didnt think the "args" variable worked since it didnt show up in intellisense

Repro:
in a new console app, start typing "args"

---
#### Feedback Bot on 8/26/2021, 11:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sandyarmstrong** [comment] 2022-03-21 14:02
I can still reproduce this issue in VS 17.2.0 Preview 1.0. We are starting to see reports from VSMac 17.0 customers who are also surprised by this behavior. `args` becomes available in the completion list in other contexts (e.g. in the condition of an `if` statement), but the fact that it is missing when typing `a` at the end of a new Console template makes the user think it is not available at all.

**Comment by DoctorKrolic** [comment] 2022-05-05 11:31
Tried to debug this. The problem lies in `LookupSymbols` method of `CSharpSemanticModel` class. Tried to debug it, and its waaay to complicated for me. Leaving this here for the person, who will fix this in the future

**Comment by CyrusNajmabadi** [comment] 2022-10-27 18:32
This is a compiler issue afaict.  We defer to them to get the symbols in scope.  I'm not sure how this was missed as part of hte min-bar pass for top-level-statements as intellisense and typing of those language features is part of that bar.

**Comment by jcouv** [comment] 2022-11-03 05:48
Indeed, this looks like a compiler issue:

```
        [Fact]
        public void Args_01()
        {
            var text = @"
#nullable enable
System.Console.WriteLine(args.Length == 0 ? 0 : -args[0].Length);
";

            var comp = CreateCompilation(text, options: TestOptions.DebugExe, parseOptions: DefaultParseOptions);
            CompileAndVerify(comp, expectedOutput: "0").VerifyDiagnostics();
...

            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);
            var invocation = tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().Single();
            var symbols = model.LookupSymbols(invocation.Position, name: "args");
            Assert.Empty(symbols); // Expected: args should be found
        }
```

**Comment by AlekseyTs** [comment] 2022-11-03 18:22
I do not think the repro above is representative of the issue being reported here. The ```invocation.Position``` is 0 and, effectively the repro is asking for symbols that are in scope at the ```#```. Position that is before the ```SpanStart``` of the first global statement is treated as not within the method body, therefore, ```args``` are not in scope. Starting with the ```SpanStart``` of the first global statement, ```args``` are in scope, This can be observed with the following test:
```

        [Fact]
        public void Args_01()
        {
            var text = @"
#nullable enable
System.Console.WriteLine(args.Length == 0 ? 0 : -args[0].Length);
System.Console.Write("""");

System.Console.Write("""");
";

            var comp = CreateCompilation(text, options: TestOptions.DebugExe, parseOptions: DefaultParseOptions);
   
            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);
            var invocations = tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().ToArray();

            var symbols = model.LookupSymbols(invocations[0].Position, name: "args");
            Assert.Empty(symbols); // Expected: args should be found
            symbols = model.LookupSymbols(invocations[0].SpanStart, name: "args");
            Assert.Equal("System.String[] args", symbols.Single().ToTestDisplayString());

            symbols = model.LookupSymbols(invocations[1].Position, name: "args");
            Assert.Equal("System.String[] args", symbols.Single().ToTestDisplayString());
            symbols = model.LookupSymbols(invocations[1].SpanStart, name: "args");
            Assert.Equal("System.String[] args", symbols.Single().ToTestDisplayString());

            symbols = model.LookupSymbols(invocations[2].Position, name: "args");
            Assert.Equal("System.String[] args", symbols.Single().ToTestDisplayString());
            symbols = model.LookupSymbols(invocations[2].SpanStart, name: "args");
            Assert.Equal("System.String[] args", symbols.Single().ToTestDisplayString());
        }
```

**Comment by CyrusNajmabadi** [comment] 2022-11-03 18:30
This reproes without the pp directive right?  Like for the normal template?

**Comment by AlekseyTs** [comment] 2022-11-03 18:31
Going back to the issue being reported, as I understand it. Given the following code:
```
System.Console.WriteLine(args);
ar
```
```args``` are not offered after "ar" on the second line.

I think this is caused by the fact that the second line is not parsed as a global statement, but instead is parsed as an incomplete member:
![image](https://user-images.githubusercontent.com/10522107/199804863-49a511d2-4629-405a-b60e-67b8c784b385.png)

Given that, compiler doesn't consider that the position is within the method body and, therefore, "args" are not in scope

**Comment by CyrusNajmabadi** [comment] 2022-11-03 18:36
An interesting approach at the top level would be to parse this out in the same way that it would be parsed in a method body.  (in this case, likely an expression-statement containing that identifier).  That seems, to me at least, to be better than an incomplete-member (which basically breaks everything everywhere it appears :)).

I'd be happy to try making such a change. Feel free to reassign to me and i can look into that.

**Comment by AlekseyTs** [comment] 2022-11-03 18:45
> This reproes without the pp directive right? Like for the normal template?

Presence of the directive makes ```Position``` < ```SpanStart```. I am not sure what is in the "normal template", but I do not think this is what is causing the issue during typing. During typing position of the cursor is within a global statement, assuming the line is parsed as part of one.

**Comment by CyrusNajmabadi** [comment] 2022-11-03 18:51
I can repro this with trivial cases.  For example, just trying to bring up completion in an empty file:

![image](https://user-images.githubusercontent.com/4564579/199808514-b4993d0f-3573-469d-95b8-97e97d5fa415.png)

or even starting to type out args:

![image](https://user-images.githubusercontent.com/4564579/199808590-d1856fb7-44bd-451e-b606-beb9c2d33c06.png)

In both cases, we are asking what symbols are available at position 0.  But the compiler does not return `args` in either of these cases, despite `args` being something that would be legal here.  

My guess, without debugging through, is that the syntax tree says 'incomplete member' and we're defaulting to assuming that that means we can't have a `args` there.  Generally speaking, 'incomplete member' is really bad for all higher layers as it basically breaks lots of things in semantic analysis.  My proposal, which i'm happy to try out, is to instead parse this the same way as if it was contained in a block.  i.e. treat it as an incomplete statement (which is well supported by the entire stack) and then have things fall out from that.

**Comment by AlekseyTs** [comment] 2022-11-03 19:01
> My proposal, which i'm happy to try out, is to instead parse this the same way as if it was contained in a block. i.e. treat it as an incomplete statement (which is well supported by the entire stack) and then have things fall out from that.

This is what I am planning to do. I am not saying there is no problem, simply capturing results of my investigation for others to understand the background of the problem

**Comment by CyrusNajmabadi** [comment] 2022-11-03 19:06
sgtm.  thanks!

**Closed** 2022-11-17 19:38 UTC
Labels: Bug, Area-Compilers, Developer Community, New Language Feature - Simple Programs
