### ISSUE TITLE
Upgrade Project fixer should be able to upgrade TargetFramework to support new language versions

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#47977] opened 2020-09-23 17:26 UTC
Scenario: you have an existing netcoreapp3.1 project and you just installed VS 16.8. You want to try some of the new C# 9 features so you go into your code and add:

```cs
record Widget(string Name, int Id);
```

This gives some diagnostics about how there's no type named 'record' in scope, this language feature requires LangVersion 9.0, etc. So you use the lightbulb menu to upgrade your project's LangVersion to 9.0.

However, the TargetFramework in your project is unchanged. Instead of building successfuly, the fixed project has the diagnostic: `CS0518 Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported`. This type is only present in net5.0, so you have to upgrade the TargetFramework or declare the type yourself (not officially supported) in order to use records. *note: it's a bug that the upgrade was offered to a language version not supported by the target framework. Tracked by #47983*

Given this behavior, and given that we basically require using new TargetFramework in order to adopt new language versions (old TargetFrameworks are unsupported in combination with newer LangVersions), perhaps the UpgradeProject fixer should offer to change the TargetFramework instead of the LangVersion in certain scenarios.

/cc @CyrusNajmabadi @jcouv

**Comment by CyrusNajmabadi** [comment] 2020-09-23 17:49
@jasonmalinowski is it possible for IDE to change this value if we wanted to?

**Comment by jasonmalinowski** [comment] 2020-09-23 18:21
Yeah we _could_ do it; the tricky bit is knowing what to change it to, and also that a conversion to .NET 5.0 implicitly may also require other upgrade changes too.

> So you use the lightbulb menu to upgrade your project's LangVersion to 9.0.

We did work to make sure we didn't show a lightbulb in this case:

https://github.com/dotnet/roslyn/pull/37518

Somebody should figure out why that's not working here.

**Comment by RikkiGibson** [comment] 2020-09-23 18:23
@jasonmalinowski @ryzngard should I open a follow-up issue with repro steps?

**Comment by jasonmalinowski** [comment] 2020-09-23 18:25
@RikkiGibson Or just edit this bug, your call.

**Comment by jasonmalinowski** [comment] 2020-09-23 18:26
I guess it may make sense to keep this issue open to track trying to support a proper upgrade, but the difficulty of that meant we instead scoped that scenario out. We're not going to support upgrade in 16.8, but I'd absolutely say we should fix this for 16.8.

**Comment by RikkiGibson** [comment] 2020-09-23 18:29
Placing in 16.9 speculatively, feel free to move the milestone on this as you see fit 😉

**Comment by ryzngard** [comment] 2020-09-23 19:59
@RikkiGibson  I'm looking

**Comment by sharwell** [comment] 2020-09-24 08:07
This appears to be a duplicate of #47983. That issue highlights the specific regression and suggests a quick fix for it.

**Comment by RikkiGibson** [comment] 2020-09-24 17:11
This issue tracks the suggestion to automatically upgrade the user's TargetFramework. #47983 tracks the bug where the UpgradeProject code fix is offered in scenarios it should not be offered in.

**Comment by sharwell** [comment] 2020-09-24 17:26
@RikkiGibson Thanks, I updated the title and removed the records label since it applies to all version-specific features starting with C# 8

**Closed** 2024-11-11 20:10 UTC
Labels: Area-IDE, Feature Request, IDE-CodeStyle
