### ISSUE TITLE
Local Method lookup isn't available in Go To All

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#50398] opened 2021-01-12 17:23 UTC
**Version**
VS 2019 Version 16.9.0 Preview 2.0

**Steps to Reproduce**:

1. create code with a method and a local method in it
2. Ctrl-T for the name of the local method
3. see that nothing turns up

**Expected Behavior**:
Local methods should be found there

**Actual Behavior**:
no local methods are found

**Comment by jinujoseph** [comment] 2021-01-12 20:46
Duplicate of #39083

**Closed by jinujoseph** 2021-01-12 20:46 UTC
Labels: Area-IDE
