### ISSUE TITLE
CSharpEncapsulateField.EncapsulateThroughCommand is flakey

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20818] opened 2017-07-12 04:54 UTC
Failed here: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/lastCompletedBuild/testReport/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpEncapsulateField/EncapsulateThroughCommand/

```
Stacktrace

MESSAGE:
Assert.Contains() Failure\r\nNot found: public static int? Param { get => param; set => param = value; }\r\nIn value: \r\nnamespace myNamespace\r\n{\r\n class Program\r\n {\r\n private static int? param = 0;\r\n static void Main(string[] args)\r\n {\r\n param = 80;\r\n }\r\n }\r\n}
+++++++++++++++++++
STACK TRACE:
at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.Verifier.TextContains(String expectedText, Boolean assertCaretPosition) at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpEncapsulateField.EncapsulateThroughCommand() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpEncapsulateField.cs:line 47
```

**Comment by Pilchie** [comment] 2017-07-12 18:14
Dupe of https://github.com/dotnet/roslyn/issues/19816

**Closed by Pilchie** 2017-07-12 18:14 UTC
Labels: Area-IDE, Test
