### ISSUE TITLE
Automatic XML Documentation Comments for Exceptions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54922] opened 2021-07-19 17:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-XML-Documentation-Comments-for/1466019)._

---
Crawls the call hierarchy for all throws and possible exceptions and automatically compiles the XML comments for exceptions found.

---
#### Feedback Bot on 7/1/2021, 08:02 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment] 2021-07-19 18:38
Duplicate of https://github.com/dotnet/roslyn/issues/54245

**Closed** 2021-07-20 23:04 UTC
Labels: Area-IDE, Resolution-Duplicate
