### ISSUE TITLE
Find All References not working with var

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24905] opened 2018-02-16 23:46 UTC
Find All References done on a class name does not return usages of this class if var is used instead of the class name.

In this example, Find All References done on the class name in the class definition (first line) finds the line 13 where class name is used (TestObject o2 = GetTestObject()) but not the line 12 where var is used (var o1 = GetTestObject())

public class TestObject
{
}

private TestObject GetTestObject()
{
	return new TestObject();
}

private void Test()
{
	var o1 = GetTestObject();
	TestObject o2 = GetTestObject();
}

Found in VS 15.5.5 but it seems it was already like that in VS 2015.

Thank you.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/195156/find-all-references-not-working-with-var.html
VSTS ticketId: 563885_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-02-18 00:45
> Find All References done on a class name does not return usages of this class if var is used instead of the class name.

Yes.  this is expected behavior.  You did not reference the type name, so it's not a reference :)

Consider these cases:

```c#
class Foo {
}

//
var f = GetFoo();
DoStuff(f);
``` 

If 'var' is a reference here because hte 'type' is referenced as the result of 'GetFoo()' then why would we not also have a reference here:

```c#
DoStuff(GetFoo());
```

In both cases there is a temporary value.  And both temps have the type "Foo".  Just one temp is named ('f') and the other is unnamed.  Why should the presence of a *named* local mean that we now have a reference to that type, when not having that local be named means we don't have a reference?

If you needed to know that the type was used here ```var f = GetFoo();``` then certainly you needed that same information for ```DoStuff(GetFoo())```.

--

On top of that, there is no way for FindRefs to be efficient in the current architecture if we were to find refs in vars.  in a project, essentially, all files use 'var'.  As such, we'd have to analyze all of them.  Which would be an unacceptable perf regression.

**Comment by CyrusNajmabadi** [comment] 2022-10-29 00:39
Closing out as by design.

**Closed by CyrusNajmabadi** 2022-10-29 00:39 UTC
Labels: Area-IDE, Developer Community

**Comment by v-kydela** [comment] 2024-06-25 06:56
> In both cases there is a temporary value. And both temps have the type "Foo". Just one temp is named ('f') and the other is unnamed. Why should the presence of a _named_ local mean that we now have a reference to that type, when not having that local be named means we don't have a reference?
> 
> If you needed to know that the type was used here `var f = GetFoo();` then certainly you needed that same information for `DoStuff(GetFoo())`.

Surely your argument works the opposite way.

Consider this case:

```c#
Foo f = GetFoo();
```

Using `var` is supposed to have exactly the same functionality as using the explicit type. Why should the presence of an explicit type mean that we now have a reference to that type, when not having that type be explicit means we don't have a reference?

If you needed to know that the type was used here `Foo f = GetFoo();` then certainly you needed that same information for `var f = GetFoo();`.

**Comment by cremor** [comment] 2024-10-18 06:12
This is annoying. `var` is used to shorten our code. There are even code fixes that do it automatically. The type of `var` is known at compile time, so why can't it be found by "find all references"?

Is there an (open) issue where we can vote to add/fix this?

**Comment by CyrusNajmabadi** [comment] 2024-10-18 07:04
> Is there an (open) issue where we can vote to add/fix this?

That is this issue.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 07:05
> The type of var is known at compile time, so why can't it be found by "find all references"?

Performance. We build syntactic indices to determine where to search. But 'var' is both everywhere, and has nothing in the syntax to indicate if it's a match for the type you're looking for.  This would blow the perf out of find references by several orders of magnitude.
