### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VisualBasic_FixupSpanDuringResolvableConflict_ReferenceConflict unit test is flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#38247] opened 2019-08-23 18:06 UTC
I have a PR https://github.com/dotnet/roslyn/pull/38230 that targets release/dev16.3 branch and the 
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VisualBasic_FixupSpanDuringResolvableConflict_ReferenceConflict unit test fails for it (failed on rerun as well) only in Windows_Desktop_Unit_Tests release_32 build. Note, the PR doesn’t make any changes to VB.
Here is a link to the build https://dev.azure.com/dnceng/public/_build/results?buildId=321462&view=logs.

```
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VisualBasic_FixupSpanDuringResolvableConflict_ReferenceConflict [STARTING]
      Assert.Equal() Failure
      Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[21..24), [72..75), [78..81)]
      Actual:   List<Span> [[21..24), [72..75), [72..75), [78..81), [78..81)]
      Stack Trace:
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(91,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(26,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_2_VerifyTaggedSpans.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(61,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_6_VerifySpansBeforeConflictResolution.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(865,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_21_VisualBasic_FixupSpanDuringResolvableConflict_ReferenceConflict.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AlekseyTs** [comment] 2019-08-23 18:11
Skipping the test for now.

**Comment by sharwell** [comment] 2019-08-23 18:35
@AlekseyTs Please do not skip this test. It fails very rarely (above the bar), and skipping this test will not correct the occasional build failures because the flakiness impacts several different tests.

**Comment by sharwell** [comment] 2019-08-23 18:35
Duplicate of #29483

**Comment by AlekseyTs** [comment] 2019-08-23 19:15
The test is skipped and linked to this issue. It tracks re-enabling the test.

**Closed** 2020-01-10 21:39 UTC
Labels: Area-IDE, Disabled Test, Resolution-Duplicate
