### ISSUE TITLE
BUG in VS2022 on Visual Basic code when click on Peek Definition doesn't show the element, shows the file where is declared at the first line.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58809] opened 2022-01-12 18:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BUG-in-VS2022-on-Visual-Basic-code-when-/1555932)._

---
[severity:It's more difficult to complete my work]
Hi,
Using Microsoft Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 5.0 (see first gif).
In Microsoft Visual Studio Community 2019 Version 16.11.5 works as expected (see third gif).

It's happened on Visual Basic code, in C# works as expected.

Select a property or method of a class/module then right click (secondary mouse button) to show the menu, then select the option **Peek Definition**.
It should show the definition of the element, but instead shows the file where it's declared.

See the first GIF:
[BUG_VS2022_peek_definition_VB_vs2022.gif](https://aka.ms/dc/file?name=B15ab7e420ef246ef9db151bb75f55fb6637700689390891452_BUG_VS2022_peek_definition_VB_vs2022.gif&tid=15ab7e420ef246ef9db151bb75f55fb6637700689390891452)

If you instead of using the context menu press ALT+F12, works fine.
See second GIF:
[BUG_VS2022_peek_definition_VB_vs2022_ALTF12.gif](https://aka.ms/dc/file?name=B7421bea2c6724c63b6509605ac2e4588637700698290856120_BUG_VS2022_peek_definition_VB_vs2022_ALTF12.gif&tid=7421bea2c6724c63b6509605ac2e4588637700698290856120)

I have no extra things added (plug-ins, etc) to Visual Studio, have the default things installed.

Here you can see how is expected to work (captured on Visual Studio 2019 using the same project).
[BUG_VS2022_peek_definition_VB_vs2019.gif](https://aka.ms/dc/file?name=B7a59f057c75f44088da5993d36bffaae637700700148472744_BUG_VS2022_peek_definition_VB_vs2019.gif&tid=7a59f057c75f44088da5993d36bffaae637700700148472744)

The solution has Visual Basic and C# projects.

Guillermo.
P.S.
I'll create a test project and upload here, but not right now ;-)

---
#### Feedback Bot on 10/17/2021, 11:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/18/2021, 10:11 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Jiří Zídek on 11/25/2021, 05:10 AM: 

<p>Alt-F12 works OK, but old-good Ctrl-Click opens new file !</p>

#### Sven Widowski on 1/12/2022, 01:21 AM: 

<p>Same Problem exists in <strong>C#</strong>, too! Please fix it soon. Thank you.</p>

---
### Original Solutions
(no solutions)

**Comment by MartinThorsen** [comment] 2022-02-01 19:23
This is completely busted for me in VS2022 for C#. Doesn't matter which method I use to peek definition. Just opens the file at the first line. Really annoying as it is a feature I use quite often.

**Comment by olegtk** [comment] 2022-03-06 20:43
@jinujoseph it's a dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1455990, it's Editor's bug, will be fixed in 17.2 Preview3.

**Closed** 2022-03-07 02:24 UTC
Labels: help wanted, Area-IDE, Language-VB, Area-External, Developer Community, IDE-Navigation
