### ISSUE TITLE
do not set FatalError handlers in unit tests

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30572] opened 2018-10-17 23:28 UTC
looks like we are setting those handlers in unit test making unit test that checks error case to hit the code and fail the test.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 03:44
I this this is very much by design.  Watsons indicate something bad.  They always have.  If we hit any in tests, we would want things to fail.

**Comment by heejaechang** [comment] 2018-10-18 04:14
then, why did you have a test that explicitly hit it?

**Comment by CyrusNajmabadi** [comment] 2018-10-18 04:18
Because you had me convert to NFW...  my test works properly with the new logic where we don't crash/throw/nfw when we encounter a case we didn't explicitly add support for.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 04:28
Think about every feature we have, and every branch that says: "bail out gracefully since we don't have explicit support for this".  We write a test for taht to validate things work.  But we don't expect those to watson/crash/throw.  

Again, it's literally only EM that seems to ever have had this behavior.  It doesn't make sense, is out of place in the IDE, and is exactly what i was undoing here :)

**Comment by heejaechang** [comment] 2018-10-18 04:30
okay. it will go in circle again so just leave your opinion and move on rather than make this issue get messy.

my opinion is error case where we want to NFW but recover should be tested so that recover worked as expected.

it doesn't make sense either removing NFW nor not testing the case.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 04:30
@heejaechang Simple questions: 

Why do you think that none of our other refactorings/analyzers work this way?  I'm really not certain how to explain things any better at this point.  They aren't written this way because of hte precise sorts of problems encountered here, and because the cost they would incur when the language changes.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 04:33
> my opinion is error case where we want to NFW but recover should be tested so that recover worked as expected.

This is not an error case.  That's the entire point.  It's expected that *absent invariants documented somewhere* our code should be resilient to seeing something like this.  And, in that case, we can design the feature appropriately, while reporting information to us about cases we didn't anticipate so we can address them.

Again, as per https://github.com/dotnet/roslyn/issues/30572#issuecomment-430871650, this is how the rest of our features are designed.  It's not going in circles to state this.  It's simply pointing out the expected and practical approach we've taken to layer things on the compiler, which helps avoid these problems.  This pattern works well and, in general, we should consistently follow patterns like this.  When our features go their own way, then they run into problems and inconsistencies that end up costing us over time.

**Comment by heejaechang** [comment] 2018-10-18 04:35
if you are talking about extract method, then I see you keep saying that. and I don't get it. since I completely don't agree. it works as everything else works. I keep telling you and I am not sure how I can explain it better. looks like you made up your mind and just keep repeating same thing.

and, now this issue is not about extract method. it is about FatalError being noop in unit test. and again, I dont agree at all that we shouldn't have test that excercise error scenario which we want to have NFW in production code.

anyway, I am gonig to stop since I dont agree and keep talking in circle I dont think either you or me will change our mind.

**Comment by heejaechang** [comment] 2018-10-18 04:36
> This is not an error case
well, that's your opinion. 

and also, this issue is not about that either.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 04:42
> if you are talking about extract method, then I see you keep saying that. and I don't get it. since I completely don't agree. it works as everything else works. 

It doesn't.  That's what prompted the PR i just sent through.  The code in EM threw based on an assumption that it had exhaustively covered all cases.  However, i can find no documentation *anywhere* indicating that there are only 69 cases to consider.  I also can find nothing in the documentation indicating that this set of permutations is fixed over time.  

Given that, it's inappropriate to throw.  Other IDE refactorings/analyzers do this.  They either depend on documented invariants of Roslyn, or they check and validate and bail if the data isn't what they expect.

> and, now this issue is not about extract method. it is about FatalError being noop in unit test. 

FatalError should not be a noop.  Because FatalError catches issues for us.  FatalError is literally a way for a feature to say: this crashed

If a test causes our code to say "this crashed", the we need to fix the code to *not crash*.

This came up in my PR because you wanted the code to say it crashed, then have a test htat validated that it was crashing.  But that's not what the feature or tests should do.  The feature should not crash.  And if a test found a crash, we shoudl just *fix the crash*.

> anyway, I am gonig to stop since I dont agree and keep talking in circle I dont think either you or me will change our mind.

You are correct.  But here's the thing.  You keep trying to push positions that *are not how things are done in teh IDE*.  This is the part i continually find baffling.  We can see the problems with these positions.  And we've had these problems for years.  This is frustrating because you keep trying to change the IDE to fit your view, instead of trying to make this code and these features follow the best patterns and practices of the *rest of the IDE*.  This has come up numerous times before and i simply do not see why we keep on having ot have this same argument over and over and over again.

I get that you don't seem to want to do things the same way as the rest of hte IDE.  But it's so incredibly strange to have to relitigate these issues over and over and over again.  

I would ask *please please please* to consider in the future that there are good reasons for why the IDE does things in these manners.  And to try to follow these best practices unless there is absolutely some necessary reason to deviate.

**Comment by heejaechang** [comment] 2018-11-20 03:36
just to clarify, I am not saying I will stop here because I didn't hear your reasoning, I am saying I will stop since I feel like I have spent enough effort to explain my reasoning to you and expressed that I don't agree with your reasoning and arguments. so keep repeating each other's position seems just a waste of time to me. so I am saying I will stop first and let the team decide.

**Comment by CyrusNajmabadi** [comment] 2018-11-20 03:47
Tagging @jinujoseph

**Comment by jinujoseph** [comment] 2018-11-20 07:58
This is already marked for design meeting.
Lets discuss offline and we will respond back based on what team decides.

**Comment by CyrusNajmabadi** [comment] 2023-02-10 01:05
Closing out as working as intended.

**Closed by CyrusNajmabadi** 2023-02-10 01:05 UTC
Labels: Area-IDE, Test, Need Design Review, Integration-Test
