### ISSUE TITLE
IDE1006 doesn't provide a "fix all"?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38552] opened 2019-09-06 18:01 UTC
**Version Used**: 
3.4.0-beta1-19426-03+b18d90790da95b6862def56802fa4249e4868bb4

IDE1006 (naming violations) doesn't provide a "fix all".  My project has > 1000 violations; how do I fix them all based on my editorconfig settings without going through one-by-one?

**Comment by CyrusNajmabadi** [comment] 2019-09-06 22:52
> how do I fix them all based on my editorconfig settings without going through one-by-one?

Unfortunately there is no way.  Part of the problem here is that 'fixing' individual issues is done with a rename (which is expensive and can stomp on other things).  While it would def be nice to have some sort of fix all, actually implementing htat would actually be quite complex, so it hasn't been done yet.

My suggestion for things like this is to bite off a little at a time.  Just send in a couple of commits a day that fix things up.  Eventually, the codebase gets into a good state.

Alternatively, you could consider using roslyn itself as an api and go and find your issues and call the rename API to fix them.  You could just basically do this in a loop, either fixing everything, or at least fixing large chunks in an automated fashion.

**Comment by sharwell** [comment] 2019-09-07 17:22
Duplicate of #14983

**Closed by sharwell** 2019-09-07 17:22 UTC
Labels: Area-IDE
