### ISSUE TITLE
CS0103 Generate method preview shows empty line only

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#38572] opened 2019-09-07 11:43 UTC
**Version Used**: VisualStudio.16.Preview/16.3.0-pre.3.0+29230.61

**Steps to Reproduce**:
```C#
class Program
{
    static void Main()
    {
        Test();
    }

    void OtherMethod()
    {
    }
}
```
Preview the quick fix of generating the `Test()` method

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/10546952/64474455-0cecd980-d16d-11e9-9c69-cd64ce8a7dd2.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/10546952/64474445-f6df1900-d16c-11e9-9b8b-a2bf8aea1559.png)

**Comment by sharwell** [comment] 2019-09-07 17:10
Duplicate of #38345

**Closed by sharwell** 2019-09-07 17:10 UTC
