### ISSUE TITLE
[Generators] Captured msbuild properties do not escape editorconfig reserved characters

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/roslyn#47814] opened 2020-09-17 21:26 UTC
**Version Used**: VS 16.8 Pre 3

**Steps to Reproduce**:

1. Capture an msbuild property
```
<CompilerVisibleProperty Include="MyProperty" />
```
2. Set the property:
```xml
<MyProperty>Value1;Value2</MyProperty>
```
3. Read the property
```csharp
context.AnalyzerConfigOptions.GlobalOptions.TryGetValue($"build_property.MyProperty", out var value);
```

**Expected Behavior**:
The value is `Value1;Value2`

**Actual Behavior**:
The value is `Value1`

**Comment by sharwell** [comment] 2020-09-22 20:26
Duplicate of #44596

**Comment by sharwell** [comment] 2020-09-22 20:26
📝 I don't believe there is any escape sequence for the two characters `#` and `;`.

**Closed by sharwell** 2020-09-22 20:26 UTC
