### ISSUE TITLE
Upgrading Microsoft.CodeAnalysis.Analyzers from 3.3.4 to 3.11.0 Breaks Code

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/roslyn#75810] opened 2024-11-07 19:46 UTC
**Version Used**: 

I'm upgrading an existing source generator sample that includes the package `Microsoft.CodeAnalysis.Analyzers` from version 3.3.4 to 3.11.0. 

**Steps to Reproduce**:

1. Create a new Source Generator project with a `GeneratorAttribute`
2. Updgrade the Microsoft.CodeAnalysis.Analyzers package to `3.11.0`
3. Build solution to use source code generator

This project consists of the following generator.

```csharp
/// <summary>
/// A sample source generator that creates C# classes based on the text file (in this case, Domain Driven Design ubiquitous language registry).
/// When using a simple text file as a baseline, we can create a non-incremental source generator.
/// </summary>
[Generator]
public class SampleSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required for this generator.
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // If you would like to put some data to non-compilable file (e.g. a .txt file), mark it as an Additional File.

        // Go through all files marked as an Additional File in file properties.
        foreach (var additionalFile in context.AdditionalFiles)
        {
            if (additionalFile == null)
                continue;

            // Check if the file name is the specific file that we expect.
            if (Path.GetFileName(additionalFile.Path) != "DDD.UbiquitousLanguageRegistry.txt")
                continue;

            var text = additionalFile.GetText();
            if (text == null)
                continue;

            foreach (var line in text.Lines)
            {
                var className = line.ToString().Trim();

                // Build up the source code.
                string source = $@"// <auto-generated/>

namespace Entities
{{
    public partial class {className}
    {{
    }}
}}
";

                // Add the source code to the compilation.
                context.AddSource($"{className}.g.cs", source);
            }
        }
    }
}
```

and the file used by the generator is the following:

```txt
Customer
Product
Stock
Shop
Employee
```

This sample project is the starting template provided by JetBrains Rider.

**Diagnostic Id**: `RS1035`

**Expected Behavior**: Project/Generator builds or at least gives a warning since this package seems to be following SemVer and `3.3.4` to `3.11.0` is still within the minor version band (so it should be compatible).

**Actual Behavior**:

💥💥BOOM💥💥

```
SampleSourceGenerator.cs(56,17): Error RS1035 : The symbol ‘GeneratorExecutionContext’ is banned for use by analyzers: Non-incremental source generators should not be used, implement IIncrementalGenerator instead
```

**Comment by CyrusNajmabadi** [comment] 2024-11-07 20:45
Closing as by design.  As stated, this symbol is banned.  We do not consider new analyzer warnings a semver affecting issue.

**Closed by CyrusNajmabadi** 2024-11-07 20:45 UTC
Labels: Area-Analyzers, untriaged

**Comment by TiagoAntunesALS** [comment] 2024-11-20 09:47
@CyrusNajmabadi Could the examples be updated?  https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md
