### ISSUE TITLE
Typing a semicolon should move the cursor to the end of the statement

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59913] opened 2022-03-03 16:04 UTC
If I have this line: _differenceCreator.CreateReportDifferences(testResult, comparisonFiles); 
When I change the last argument to something else, but leave the last 2 characters in place, when I hit the semicolon again, I end up with this:
_differenceCreator.CreateReportDifferences(testResult, newVariable); ;
ReSharper was smart enough to not duplicate the semicolon.

**Comment by sharwell** [comment] 2022-03-09 19:56
Duplicate of https://github.com/dotnet/roslyn/issues/52299#issuecomment-811247953

**Closed by sharwell** 2022-03-09 19:56 UTC
Labels: Bug, help wanted, Area-IDE
