### ISSUE TITLE
csharp_indent_preprocessor_region=usual_indent vs. preprocessor-disabled code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57416] opened 2021-10-27 18:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/csharp_indent_preprocessor_regionusual_/1563769)._

---
Hi!
I have an editor config containing the line
```csharp_indent_preprocessor_region=usual_indent```

This causes auto-formatting conflicts in files with regions inside preprocessor directives, depending on whether the code is enabled for the current configuration or not. E.g., the following indents are caused by the 'Format Document' menu option if `DEBUG` is defined; if not, the indents are reversed. This obviously causes unnecessary changes and conflicts in version control.

```
#if DEBUG
class Foo
{
    #region A
    #endregion
}
#endif

#if ! DEBUG
class Foo
{
#region A
#endregion
}
#endif
```

---
#### Feedback Bot on 10/26/2021, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-11-04 17:42
`csharp_indent_preprocessor_region` is not a formatting option. The formatter currently has no ability to customize the formatting of `#region` directives.

**Comment by sharwell** [comment] 2021-11-04 17:45
@CyrusNajmabadi is correct that we don't really have a clean way to address this. Inside the disabled code, there is no structure by which we can determine a "proper indentation level".

**Comment by sharwell** [comment] 2022-07-15 19:34
Duplicate of #62612

**Closed by sharwell** 2022-07-15 19:34 UTC
Labels: Area-IDE, Concept-Design Debt, Developer Community, Need Design Review
