### ISSUE TITLE
Implementing missing members of an interface uses .NET framework value types instead of aliased value types

### ISSUE THREAD

**Issue by jltjohanlindqvist** [dotnet/roslyn#14553] opened 2016-10-17 06:11 UTC
**Version Used**: Visual Studio "15" Preview 5

**Steps to Reproduce**:
1. Create an interface with a method that has a aliased value type as a parameter, e.g. string, int, bool. 
2. Create a class that implements the interface. (don't implement the methods manually)
3. Use the IntelliSense helper to implement the missing members.

**Expected Behavior**: IntelliSense should implement the methods with the aliased value types as parameters, i.e. string, int, bool.

**Actual Behavior**: IntelliSense uses the .NET framework types as parameters, i.e. String, Int32, Boolean.

**Comment by Pilchie** [comment] 2016-10-17 18:57
This is because the default value for the option at Tools\Options\Text Editor\C#\Code Style\General "predefined type preference" got flipped to "Prefer framework types" somehow.

Let's get this straightened out.

**Comment by jasonmalinowski** [comment] 2016-10-20 21:36
@jltjohanlindqvist: did you have previous previews installed on this machine? did you have any previous versions on a *different* machine that we might have synced settings through? I suspect this is some sort of upgrade issue and want to make sure I'm not missing all the cases.

**Comment by jltjohanlindqvist** [comment] 2016-10-21 04:57
I have VS 2015 Community installed as well, but I don't have the same problem there. No other previous VS 15 preview versions installed, and I'm not logged in to any account in any of the VS instances.

**Comment by Pilchie** [comment] 2016-11-02 23:24
This is a dupe, right?

**Comment by jasonmalinowski** [comment] 2016-11-03 01:20
I guess this is a dupe of #13748 because the engine for both is the same. I do want to leave both that and #13556 open though as I still don't have proof one is related to the other.

**Closed by jasonmalinowski** 2016-11-03 01:20 UTC
Labels: Area-IDE, Bug
