### ISSUE TITLE
Unhelpful generate method suggestion

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#2677] opened 2015-05-12 16:38 UTC
```C#
class MarkupTestFile
{
    public static void GetPosition(string markup, out string text, out int position)
    {
        text = null;
        position = 0;
    }
}

class Program
{
      static void Main(string[] args)
    {
        string markup = "xxx";
        int position = 0;
        MarkupTestFile.GetPosition(markup, $$text, position);
    }
}
```

Place the caret at the $$ and invoke the light bulb. The first suggestion is "Generate Method", which offers to generate a new overload of GetPosition where the parameter ```text``` is now an Object. Generate method probably shouldn't offer to generate methods from callsites with symbols that don't bind.

**Comment by Pilchie** [comment] 2015-05-13 22:51
Moving to analyzers for consideration in 1.0.

**Comment by srivatsn** [comment] 2015-05-15 21:29
This is by design. We went back and forth on this a few times. One school of though (like this bug) says that it is useless to offer this suggestion whereas another says for a forward-typing style, having the suggestion is good and the user can choose to not generate. We've decided to go with the current behavior. If we hear a lot of feedback about this we should reconsider.

See internal TFS bugs 992811 and 784793 for the two views.

**Closed by srivatsn** 2015-05-15 21:29 UTC
Labels: Area-Analyzers, Bug
