### ISSUE TITLE
The program text fragment with the initialization of the dictionary Is not formatted properly.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35533] opened 2019-05-06 17:31 UTC
VSF_TYPE_MARKDOWNThere is no Proper alignment when inserting the trailing parenthesis **&quot;}&quot;** or the &quot;Format Document&quot; command (**Ctrl-K, Ctrl-D**).
The Correct formatting can only be obtained by **manually** adding dictionary values.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/507237/the-program-text-fragment-with-the-initialization.html
VSTS ticketId: 829994_
_These are the original issue comments:_

Visual Studio Feedback System on 3/27/2019, 09:37 PM (39 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Enbi Zhang [MSFT] on 4/3/2019, 00:19 AM (33 days ago): <p>Thanks for your feedback.</p><p><br></p><p>Could you provide a video or gif for reproduce steps?</p><p><br></p>

Konstantin 'Office 365' Dyakov on 4/3/2019, 01:33 AM (33 days ago): <p>Я могу дать вам файл с текстом, который не форматируется.</p>

Konstantin 'Office 365' Dyakov on 4/3/2019, 01:55 AM (33 days ago): <p>Вот такой файл. <a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/66234-ctrlkd-testcs.zip">ctrlkd-testcs.zip</a></p>

Wendy Wang [MSFT] on 4/3/2019, 11:16 PM (32 days ago): <p>Translated from Bing:</p><p>Here's a file.<a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/66234-ctrlkd-testcs.zip">ctrlkd-testcs.zip</a></p><p><strong></strong><u></u><sub></sub><sup></sup><strong></strong><u></u><sub></sub><sup></sup></p>

Wendy Wang [MSFT] on 4/3/2019, 11:16 PM (32 days ago): <p>Translated from Bing:</p><p>I can give you a file with text that is not formatted.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

Visual Studio Feedback System on 4/9/2019, 10:57 PM (26 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-05-06 18:14
Duplicate of #8269

**Closed by sharwell** 2019-05-06 18:14 UTC
