### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by fazelfarajzade** [dotnet/roslyn#51221] opened 2021-02-14 06:07 UTC
System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.&lt;GetDescriptionAsync&gt;d__27.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.&lt;CallExtensionPointAsync&gt;d__36`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by sharwell** [comment] 2021-02-14 08:29
Duplicate of AB#1246915

**Comment by sharwell** [comment] 2021-02-14 08:30
Here's the public link for the above: https://developercommunity2.visualstudio.com/t/Constant-Intellisense-crashes-in-VS-2019/1256398?preview=true

**Closed by sharwell** 2021-02-14 08:29 UTC
Labels: untriaged
