### ISSUE TITLE
Ability to auto add string intrapolation character "$" at the beginning of the string if a valid "{" is typed inside the string.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58223] opened 2021-12-09 20:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ability-to-auto-add-string-intrapolation/1594886)._

---
It's very trivial that developers will start strings in a C#/other languages using a double quote, type some content, and then immediately realize that it needs string interpolation. The typical way is to add the required replacement variable within {} and then add the "$" character at the beginning of the string. This is not that efficient considering the number of times this will happen and the number of keystrokes/mouse actions required to make changes.

Can Visual Studio detect that a valid interpolation is required when typed inside a string, probably "{" and automatically add the "$" prefix for the string? This will greatly improve efficiency and would reduce the number of keystrokes/mouse actions needed. This could be backed by a configuration if this behaviour is not required.

---
### Original Comments
(no comments)

**Comment by sharwell** [comment] 2021-12-14 23:37
Duplicate of #53996

**Closed by sharwell** 2021-12-14 23:37 UTC
Labels: Area-IDE, untriaged
