### ISSUE TITLE
C# 'out' variable intellisense completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46268] opened 2020-07-23 20:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1108309/c-out-variable-intellisense-completion.html)._

---
<p>In C#, I often use the &quot;Try...&quot; methods to retrieve a value via an out variable. For example, the TryGetValue method on Dictionary. I notice that Visual Studio 2019 IntelliSense shows a reasonable out parameter type and default variable name, like out SubscriptionItem value in the example shown below. However, I can't figure out a way to autocomplete this and accept the suggested parameter definition in the manner of an expanded snippet.</p> <p>Is there a way to autocomplete this without manually typing out what IntelliSense is already suggesting? If not, I'd like to suggest this feature. Thanks!</p> 

![image](https://user-images.githubusercontent.com/1408396/88337753-154df480-ccec-11ea-9f0c-6f89fba7c587.png)

---
#### Feedback Bot on 7/9/2020, 11:16 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by Dreamescaper** [comment] 2020-07-24 10:16
Probably same as https://github.com/dotnet/roslyn/issues/39538.

**Comment by jinujoseph** [comment] 2020-07-28 19:34
cc @genlu

**Comment by sharwell** [comment] 2020-07-28 19:36
Duplicate of #39538

**Closed by sharwell** 2020-07-28 19:36 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-IntelliSense, Need Design Review
