### ISSUE TITLE
ExtractMethodCodeRefactoringProvider crashes with System.InvalidOperationException : Unexpected false

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19584] opened 2017-05-17 09:10 UTC
1. Highlight "evaluationRuleNames" below:

``` C#
  private static ImmutableArray<(string evaluationRuleNames, Func<UnconfiguredProject, IWorkspaceProjectContext, object> creator)>  CreateHandlerFactories()
        {
            var builder = ImmutableArray.Create<(string evaluationRuleNames, Func<UnconfiguredProject, IWorkspaceProjectContext, object> creator)(

            // Evaluation and Command-line
            (Compile.SchemaName,               (project, context) => new SourceItemHandler(project, context),                // <Compile /> item

            // Evaluation only
            (ConfigurationGeneral.SchemaName,  (project, context) => new ProjectPropertiesItemHandler(context)),             // <ProjectGuid>, <TargetPath> properties

            // Command-line only
            (null,                             (project, context) => new MetadataReferenceItemHandler(project, context)),     // <ProjectReference />, <Reference /> items
            (null,                             (project, context) => new AnalyzerItemHandler(context)),                       // <Analyzer /> item
            (null,                             (project, context) => new AdditionalFilesItemHandler(context))                 // <AdditionalFiles /> item
            );
            return builder.MoveToImmutable();
        }
```

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by sharwell** [comment] 2017-05-17 12:20
❓ In your example, isn't `builder` already an `ImmutableArray` (i.e., one you could return without calling `MoveToImmutable`)?

**Comment by Pilchie** [comment] 2017-05-17 16:57
@davkean You filed this two weeks ago :)

Dupe of https://github.com/dotnet/roslyn/issues/19136

**Closed** 2017-05-17 17:01 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate

**Comment by davkean** [comment] 2017-05-17 22:35
@Pilchie Hmm, forgot about that - the repro is slightly different though.

@sharwell I was rewriting the method and hadn't finished - that array used to be a builder.
