### ISSUE TITLE
Roslyn failed to build itself under system codepage 936

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#5413] opened 2015-09-23 20:07 UTC
I was building Roslyn with cibuild.cmd, this error happened when the bootstrapped compiler compiles a test project

My system locale is Simplified Chinese/CodePage936/GB2312, from cmd invoke cibuild.cmd failed to build the following file:

    src\EditorFeatures\VisualBasicTest\Diagnostics\GenerateType\GenerateTypeTests.vb(695,114)
    ...
    src\EditorFeatures\VisualBasicTest\Diagnostics\GenerateType\GenerateTypeTests.vb(724,6)

When I used NotePad++ to open this file, I saw
![garbage](http://ww4.sinaimg.cn/large/6783ba97gw1ewd0ahlr2xj21080i0n6u.jpg)

Then I changed encoding to UTF-8 Without BOM
![0xA0](http://ww3.sinaimg.cn/large/6783ba97gw1ewd0jq3fusj213o0gjwox.jpg)

When I use some Charset from European the content looks correct.
![correct](http://ww1.sinaimg.cn/large/6783ba97gw1ewd0zavnplj21460hv7e9.jpg)

**Comment by Pilchie** [comment] 2015-09-23 21:54
Tagging @jaredpar who has looked at some encoding issues before.

**Comment by jaredpar** [comment] 2015-09-23 22:04
Thanks for reporting.  This is a duplicate of #4264.  This has already been fixed and will be included in update 1.  

In the mean time you can work around this by adding the following entry int your vbproj file:

``` xml
<CodePage>936</CodePage>
```

This will override the encoding detection logic to prefer this encoding instead of the standard fall back mechanisms.

**Comment by diryboy** [comment] 2015-09-24 00:50
No, I don't think this is duplicate. I was compiling Roslyn. The cibuild.cmd bootstrap itself then use the new compiler to compile Roslyn, if it's fixed then this won't happen.

**Comment by dpoeschl** [comment] 2015-09-24 17:02
Reopening on @diryboy's behalf for now, as per #5424.

**Comment by jaredpar** [comment] 2015-09-24 17:05
@diryboy @dpoeschl ah okay.  I misread the original bug report.

**Comment by diryboy** [comment] 2015-09-24 17:09
@jaredpar I didn't explain the issue well earlier, apology for that.

**Closed** 2015-09-28 17:34 UTC
Labels: Area-Infrastructure
