### ISSUE TITLE
Flaky test TestRemoteHostSynchronizeIncrementalUpdate

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#47126] opened 2020-08-25 22:26 UTC
https://github.com/dotnet/roslyn/blob/05b8f2d4f627ae4756b0a99ca0fad853e101baef/src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs#L295

CI run: https://dev.azure.com/dnceng/public/_build/results?buildId=787135&view=ms.vss-test-web.build-test-results-tab&runId=24808824&resultId=205258&paneView=debug

```
System.TimeoutException : Failed to clean up listeners in a timely manner.
  ProcessAsync IdleProcessor.cs 92
  WorkItem WorkCoordinator.LowPriorityProcessor.cs 98
  WorkItem WorkCoordinator.LowPriorityProcessor.cs 98
  EnqueueWorkItemAsync WorkCoordinator.SemanticChangeProcessor.cs 410
  EnqueueWorkItemAsync WorkCoordinator.SemanticChangeProcessor.cs 410
  WorkItem WorkCoordinator.LowPriorityProcessor.cs 98
  EnqueueWorkItemAsync WorkCoordinator.SemanticChangeProcessor.cs 410
  EnqueueWorkItemAsync WorkCoordinator.SemanticChangeProcessor.cs 410
  WorkItem WorkCoordinator.LowPriorityProcessor.cs 98
  ProcessAsync IdleProcessor.cs 92
---- System.OperationCanceledException : Operación cancelada.
```

```
   en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.DisposeExportProvider(ExportProvider exportProvider) en /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:línea 155
   en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest) en /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:línea 88
   en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__1() en C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestInvoker.cs:línea 93
   en Xunit.Sdk.ExecutionTimer.Aggregate(Action action) en C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:línea 31
   en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__0() en C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestInvoker.cs:línea 93
   en Xunit.Sdk.ExceptionAggregator.Run(Action code) en C:\projects\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:línea 73
----- Inner Stack Trace -----
   en System.Threading.CancellationToken.ThrowOperationCanceledException()
   en System.Threading.CancellationToken.ThrowIfCancellationRequested()
   en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcherNoResult(Task task, CancellationToken cancellationToken) en /_/src/Workspaces/CoreTestUtilities/TaskJoinExtensions.cs:línea 60
   en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcher(Task task, CancellationToken cancellationToken) en /_/src/Workspaces/CoreTestUtilities/TaskJoinExtensions.cs:línea 22
   en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.DisposeExportProvider(ExportProvider exportProvider) en /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:línea 142
```

**Comment by sharwell** [comment] 2020-09-09 16:24
I can't find any recent failures in the logs and cannot reproduce locally, so closing as not reproducible.

**Closed by sharwell** 2020-09-09 16:24 UTC
Labels: Area-IDE, Flaky, Test
