### ISSUE TITLE
c# struct operator taking "in" (byref) fails to report CS8374 when used with "this" and can expose internals / cause stack corruption

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#72239] opened 2024-02-23 11:45 UTC
C# 12
SDK 8.0.200

Origin: https://stackoverflow.com/questions/78006611/returning-a-new-ref-struct-instance-that-holds-a-reference-to-the-returning-inst - credit to [patvax](https://stackoverflow.com/users/5853383/patvax)

The compiler has guards to prevent references (spans or direct `ref`) fields on structs being exposed outside of their lifetime, most notably CS8374. These guards fail to handle operator scenarios, which can lead to stack corruption.

Consider the struct:

``` c#
readonly struct Repro
{
    private readonly int i;
}
```

We can add `static` methods that take an `in Repro` that fetch a span/ref, without issue (because the lifetime of the object is now guarded at the caller):

``` c#
    // all fine, no problem
    public static ReadOnlySpan<int> ToSpan(in Repro value) => new ReadOnlySpan<int>(in value.i);
    public static ref readonly int ToRef(in Repro value) => ref value.i;
```

Since this is guarded at the call-site, we **cannot** call these methods using `in this`; this is a correct protection:

``` c#
    // neither of these are allowed; this is good
    public ReadOnlySpan<int> SelfToSpan() => ToSpan(in this); // CS8374, CS8170
    public ref readonly int SelfToRef() => ref ToRef(in this); // CS8374, CS8170
```

However, it is possible to define an *operator* that converts `Repro` to `ReadOnlySpan<int>`, and this operator is allowed to take `in`; this could be `implicit` or `explicit`:

``` c#
    // no error; this is bad
    public static implicit operator ReadOnlySpan<int>(in Repro value) => new ReadOnlySpan<int>(in value.i);
    public ReadOnlySpan<int> SelfToSpan() => this;
```

or

``` c#
    // no error; this is bad
    public static explicit operator ReadOnlySpan<int>(in Repro value) => new ReadOnlySpan<int>(in value.i);
    public ReadOnlySpan<int> SelfToSpan() => (ReadOnlySpan<int>)this;
```

This means that we can incorrectly get a span from `in this`.

This can be shown to cause invalid stack memory reuse with the full repro (only works reliably in debug, but the concept stands):

``` c#
// get an invalid span to transient stack-space
ReadOnlySpan<int> values = GetSpan();

// create a valid buffer and fill it
Span<int> buffer = stackalloc int[20];
buffer.Fill(42);

// oops, they overlapped
Console.WriteLine(values[0]); // outputs: 42
for (int i = 0; i < buffer.Length; i++)
{
    if (Unsafe.AreSame(in values[0], in buffer[i]))
    {
        Console.WriteLine(i); // outputs: 2
    }
}

ReadOnlySpan<int> GetSpan() => new Repro();

readonly struct Repro
{
    private readonly int i;

    public static implicit operator ReadOnlySpan<int>(in Repro value) => new ReadOnlySpan<int>(in value.i);
}
```

**Expected Behavior**:

The implicit/explicit operator usage that resolves to `in` on a protected value (such as `this`) should cause CS8374

**Actual Behavior**:

The implicit operator usage *does not* cause CS8374, and exposes internals

(note: in an abundance of caution I also tested extension methods with `in this`; these also caused CS8347, so: extension methods with hidden by-ref semantics *do not* appear to cause this problem)

**Comment by jjonescz** [comment] 2024-02-23 12:37
Thanks for the detailed report. Looks like a duplicate of https://github.com/dotnet/roslyn/issues/71773 which we already have fix PR open for.

**Closed** 2024-03-25 09:36 UTC
Labels: Bug, Area-Compilers, New Language Feature - Ref Fields
