### ISSUE TITLE
ISourceGenerator should have async methods

### ISSUE THREAD

**Issue by springy76** [dotnet/roslyn#44045] opened 2020-05-07 12:09 UTC
Please don't repeat the same design error as aspnetcore1.0 did with the unmodified `IFileProvider` imported from Owin/Katana.

**Comment by jcouv** [comment] 2020-05-07 15:58
FYI @chsienki

**Comment by chsienki** [comment] 2020-05-07 18:02
The `ISourceGenerator` methods are synchronous by design. Generators shouldn't be doing any I/O bound work: the reading of files etc should be handled by the compiler itself, and the generator just accesses the contents.

I'm going to close this as by-design, but feel free to add comments if there are scenarios that you think can only be achieved with async.

**Closed by chsienki** 2020-05-07 18:02 UTC
Labels: Area-Compilers, Discussion, New Feature - Source Generators

**Comment by as-ivanov** [comment] 2020-06-23 15:34
Hi @chsienki,

> I'm going to close this as by-design, but feel free to add comments if there are scenarios that you think can only be achieved with async.

What if I need to generate, say, a typescript or json-schema file based on my C# code? In case source generators (or analyzers) had async flow, async I/O could be utilized for that.  
From the other hand source generators do not provide any API for generating arbitrary files. Do you have an intention to support possibility of generating arbitrary content in future?

**Comment by CyrusNajmabadi** [comment] 2020-06-23 19:41
> Do you have an intention to support possibility of generating arbitrary content in future?

No, there is no intention to support that.

**Comment by kjkrum** [comment] 2021-06-03 22:34
A very unfortunate limitation. For my purposes, not only should `ISourceGenerator` methods be async, they should be able to make HTTP calls to obtain sources to transpile. I guess we're all the way back to using console applications as source generators, since the issues with MSBuild tasks leaving files locked and processes hanging around were never fixed.
