### ISSUE TITLE
[Flaky] CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict is flaky

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#40850] opened 2020-01-09 18:35 UTC
Seen in https://dev.azure.com/dnceng/public/_build/results?buildId=477708&view=ms.vss-test-web.build-test-results-tab&runId=15180274&resultId=156922&paneView=debug

**Comment by sharwell** [comment] 2020-01-09 20:04
Duplicate of #29483

**Closed by sharwell** 2020-01-09 20:04 UTC
Labels: Area-Infrastructure, Flaky

**Comment by dibarbet** [comment] 2020-01-09 20:08
I could have sworn I searched for it and didn't find anything...

**Comment by sharwell** [comment] 2020-01-09 20:09
It's a different test name, same underlying cause. It affects about a dozen tests.
