### ISSUE TITLE
Add documentation for IDE0220

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65763] opened 2022-12-05 08:57 UTC
<html>
<body>

IDE0220 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0220 | Add explicit cast
-- | -- | --

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by CyrusNajmabadi** [comment] 2022-12-05 17:10
Dupe of https://github.com/dotnet/roslyn/issues/65760

**Closed by CyrusNajmabadi** 2022-12-05 17:10 UTC
Labels: help wanted, Area-IDE, Feature Request, Documentation, untriaged
