### ISSUE TITLE
Embedded JsonParser.TryParse throws FormatException

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#62883] opened 2022-07-23 11:55 UTC
**Version Used**: Microsoft.CodeAnalysis.Features.dll 4.2.0-dev.22326.1+85af7b046d5fd74b014b8502bd8ab3c0c05d73ea

**Steps to Reproduce**:

```C#
var a = "0x";
```

**Expected Behavior**:

https://github.com/dotnet/roslyn/blob/d82c81bf2029f4d64c0c78d25fd91fcdc02ed4e1/src/Features/Core/Portable/EmbeddedLanguages/Json/JsonParser.cs#L101-L106

**Actual Behavior**:

System.FormatException: Could not find any recognizable digits.

<TABLE><TR><TD>mscorlib</TD><TD>System.Convert.ToInt64 Line 2072</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.JsonNetSyntaxChecker.CheckNumber Line 87</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.JsonNetSyntaxChecker.CheckLiteral Line 54</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.JsonNetSyntaxChecker.CheckSyntax Line 30</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.JsonNetSyntaxChecker.&lt;CheckSyntax&gt;g__CheckChildren|0_0 Line 43</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.JsonNetSyntaxChecker.CheckSyntax Line 32</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.ParseTree Line 127</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.JsonParser.TryParse Line 113</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.LanguageServices.JsonLanguageDetector.IsProbablyJson Line 109</TD></TR><TR><TD>Microsoft.CodeAnalysis.Features</TD><TD>Microsoft.CodeAnalysis.Features.EmbeddedLanguages.Json.LanguageServices.JsonLanguageDetector.TryParseString Line 94</TD></TR>
</TABLE>

Called during AddEmbeddedLanguageClassifications or ProduceTags/GetMatchingBraces.

**Comment by CyrusNajmabadi** [comment] 2022-07-23 14:52
Yes, this is by design. We are seeing if we can legally convert this to json. This calls into this code which attempts a numeric conversion and fails out of it can't: https://github.com/dotnet/roslyn/blob/d82c81bf2029f4d64c0c78d25fd91fcdc02ed4e1/src/Features/Core/Portable/EmbeddedLanguages/Json/JsonParser.JsonNetSyntaxChecks.cs#L85

**Comment by miloush** [comment] 2022-07-23 15:57
My bad, was misled by first-chance reporting, sorry!

**Comment by KirillOsenkov** [comment] 2022-07-23 17:38
`Convert.ToInt64` just calls `Int64.Parse`:
https://referencesource.microsoft.com/#mscorlib/system/convert.cs,45eec6b0712dc8f2

Can we call `Int64.TryParse` instead and avoid throwing here unnecessarily?

**Comment by KirillOsenkov** [comment] 2022-07-23 17:51
Oh, it's calling this one, isn't it?
https://source.dot.net/#System.Private.CoreLib/Convert.cs,4dc2a1afe9cd9708

Does this method not exist in .NET Framework?

**Comment by CyrusNajmabadi** [comment] 2022-07-23 18:58
Closing out. This is currently working as intended ) which is to exactly match json.net semantics. If this behavior can be provided without an exception lmk and we can move forward on this.

**Closed by CyrusNajmabadi** 2022-07-23 18:58 UTC
Labels: Area-Compilers, untriaged

**Comment by CyrusNajmabadi** [comment] 2022-07-23 19:00
> Is it possible to call Int64.TryParse instead and avoid throwing here unnecessarily?

Only if it can be proven that that had the exact semantics of json.net. That means passing on an strings that Json.net allows and failing on all it does not support.
