### ISSUE TITLE
System.ValueTuple does not serialize properly.

### ISSUE THREAD

**Issue by andras-ferencz** [dotnet/roslyn#17454] opened 2017-02-28 17:13 UTC
this works fine:
`new BinaryFormatter().Serialize(File.Create(Path.GetTempFileName()), new System.Tuple<int, int>(0,0));` 

this throws "is not marked as serializable":
`new BinaryFormatter().Serialize(File.Create(Path.GetTempFileName()), (lat: 0, lon: 0));`

In WebAPI: `
[Route("api/geocoords/usa/zipcodes/{zip}")]
public (double lat, double lon) GetZipCoords(int zip) => (0, 0);
`
returns: `{"Item1":0.0,"Item2":0.0}`
instead of: `{"lat":0.0,"lon":0.0}`

Which as you can probably guess is rather disappointing that the new Tuples are almost useless for daily usage in this context.

**Comment by RichiCoder1** [comment] 2017-02-28 18:18
That second issue sounds like a short coming of Json.Net, which handles JSON serialization and deserialization for Web API. I'd create an issue there. You do have to remember that the "friendly" names are largely just compiler magic.

**Comment by gafter** [comment] 2017-02-28 19:27
@jcouv

**Comment by jcouv** [comment] 2017-02-28 19:58
Regarding the first part ("is not marked as serializable" error):
`System.ValueTuple` initially shipped without the serializable annotation. This was recently added to the various implementations (mscorlib, coreCLR, coreRT, xamarin) following issue https://github.com/dotnet/corefx/issues/15229. This should work once those implementations ship and you upgrade your target group.
As a demonstration, see the [tests added to coreFX](https://github.com/dotnet/corefx/pull/15772/files).

More details in the [umbrella issue ](https://github.com/dotnet/roslyn/issues/13177) for `ValueTuple` changes.

Regarding the second part (tuple names getting lost): 
The element names don't exist in instantiated `ValueTuple` objects. So I don't expect the names could be preserved by such serialization.

**Comment by jcouv** [comment] 2017-02-28 21:25
@andras-ferencz I will close this issue as by design.
The first part was fixed and will become available as the frameworks ship.
The second part could be discussed with Json.Net, but I expect it cannot be fixed because tuple element names don't exist at runtime.

Feel free to ping me or re-open if this doesn't make sense.

**Closed by jcouv** 2017-02-28 21:25 UTC
Labels: Area-Compilers, New Language Feature - Tuples, Question
