### ISSUE TITLE
IDE0071 suggests simplification for .PadRight() that does not behave as expected

### ISSUE THREAD

**Issue by onclethomas** [dotnet/roslyn#43780] opened 2020-04-29 08:41 UTC
**Version Used**: 
Visual Studio 2019 16.5.4

**Steps to Reproduce**:

1. For an expression like `$"{anr.PadRight(11, ' ')}"` the IDE pops up IDE0071 and simplifies the expression to `$"{item.Key.anr,11}"`.
2. For an expression like `$"{anr.PadRight(maxProfileLength, ' ')}"` where `maxProfileLength` is a local int, the IDE pops up IDE0071 and simplifies the expression to `$"{item.Key.profile,maxProfileLength}"`.

**Expected Behavior**:
1. .PadRight() should be simplified to negative values, PadLeft() should be simplified to positive values like described in [String interpolation in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation). 
2. The simplification is a) wrong in terms of point 1. and b) causes a CS0150 (A constant value is expected) error. So the simplification should not occur at all.

**Actual Behavior**:
see above

~~~
Thomas

**Comment by sharwell** [comment] 2020-04-29 13:04
Duplicate of #41826

**Closed by sharwell** 2020-04-29 13:04 UTC

**Comment by sharwell** [comment] 2020-04-29 13:06
@onclethomas This should be fixed for 16.6 Preview 1 👍
