### ISSUE TITLE
Add documentation for IDE0250

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65767] opened 2022-12-05 09:08 UTC
<html>
<body>

IDE0250 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0250 | Make struct 'readonly'
-- | -- | --

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by CyrusNajmabadi** [comment] 2022-12-05 17:09
Dupe of https://github.com/dotnet/roslyn/issues/65760

**Closed by CyrusNajmabadi** 2022-12-05 17:09 UTC
Labels: help wanted, Area-IDE, Feature Request, Documentation

**Comment by gewarren** [comment] 2023-07-26 04:28
Fixed by https://github.com/dotnet/docs/pull/36378.
