### ISSUE TITLE
Expression evaluation bug (VS 2015)

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#4375] opened 2015-08-06 12:41 UTC
There's a problem with expression evaluation in Immediate Window (and Watch Window) while debugging 32 bit processes (64 bit processes work fine). The problem is with passing custom struct argument to methods.
It can be very easily reproduced by this simple code:
```C#
using System;

namespace ExpressionEvaluationBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var myStruct = new MyStruct(7);
            Console.WriteLine(myStruct.Value);
        }

        private static void Test1(MyStruct myStruct)
        {
            Console.WriteLine(myStruct.Value);
        }

        private static int Test2(MyStruct myStruct)
        {
            return myStruct.Value;
        }
    }

    struct MyStruct
    {
        public int Value;

        public MyStruct(int value)
        {
            Value = value;
        }
    }
}
```

When you break execution on line "Console.WriteLine(myStruct.Value);" and type "Test1(myStruct)" expression into Immediate Window it will write some 'random' number to console (in my case 36954684 but it's every time different one).

The same holds for expression "Test2(myStruct)" (which can be tried in Watch Window).

**Comment by cston** [comment] 2015-09-29 17:10
Tracked by an internal bug.

**Comment by pnelsonmsft** [comment] 2015-09-29 17:34
Unable to find internal tracking bug.  Re-opening...

**Comment by Przemyslaw-W** [comment] 2015-09-30 08:38
might be connected to #3614

**Comment by KevinH-MS** [comment] 2015-10-07 20:00
This is indeed a duplicate of #3614.  I'm just going to close this issue for now (we'll use the earlier one to track this).

**Closed by KevinH-MS** 2015-10-07 20:00 UTC
Labels: Area-Interactive, Interactive-Debugging

**Comment by ManishJayaswal** [comment] 2015-10-07 21:22
This is a dupe of internal debugger bug 151194
