### ISSUE TITLE
Result of null-conditional access not clearing nullability of receiver inside if statement body, when assigned to a variable

### ISSUE THREAD

**Issue by ABCRic** [dotnet/roslyn#37032] opened 2019-07-06 05:56 UTC
**Version Used**: http://sharplab.io, commit 898bed74a765fedf3071c6f25c3804995d39c7fa (master 21 Jun 2019)

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKAMQB2ArgDYkTAlwAEcBFVuKAzNetQMLUDeu1/bVigAs1AIIAKAJQ8+AgJAA3CAmqxVAXmoAhaQG45AgctVUC1LeoD8AOgAydAOYwAFgZxGjASwBmEs9QAhFrEZFKGnvIoGACcEuo2ACoIXmDSUu5GAL4RESxsGAAMVjrSsh4KKADs1ABEtZkCOThZQA=
```csharp
using System;
#nullable enable
public class C {
    public void A() {
    	var str = B();
        var len = str?.Length;
        if(len != null)
            Console.WriteLine(str.Trim());
    }
    
    public string? B() {
    	return "";
    }
}
```
**Expected Behavior**:
No warnings. If `str` is null, then `str?.Length` is null, then `len` is null, then the `if` body is not executed. Therefore the `if` body is only executed if `str` is not null.
Note that manually inlining `len` like so:
```csharp
if(str?.Length != null)
```
makes the warning go away as expected.

**Actual Behavior**:
`warning CS8602: Dereference of a possibly null reference` for `str` in the call to `str.Trim()`

**Comment by ABCRic** [comment] 2019-07-07 02:41
Similar case:
```csharp
using System;
#nullable enable
public class C {
    public void A() {
    	var str = B();
        var len = str?.Length;
        if(len == null)
            return;
        Console.WriteLine(str.ToString()); // CS8602
    }
    
    public string? B() {
    	return "";
    }
}
```
Like the first example, the warning also disappears when inlining `len`.

**Comment by jcouv** [comment] 2019-07-08 19:58
Yes, this is a known limitation with nullability analysis. Once you store some information into a local we loose track of it.
Closing as duplicate of https://github.com/dotnet/roslyn/issues/34800

**Closed by jcouv** 2019-07-08 19:58 UTC
