### ISSUE TITLE
[Test Failure] Hung processs on target machine in prtest/lin/dbg/unit32 on PR #7414

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7426] opened 2015-12-11 16:10 UTC
PR: [#7414](https://github.com/dotnet/roslyn/pull/7414) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1996/

**Issue 1: Hung processs on target machine**
A process is hung on the target machine and preventing it from cleaning up the workspace

Console log shows several IO related errors on the machine.

**Comment by davkean** [comment] 2015-12-11 17:10
Dupe of https://github.com/dotnet/roslyn/issues/7411

**Closed by davkean** 2015-12-11 17:10 UTC
Labels: Area-Infrastructure, Contributor Pain, Resolution-Duplicate
