### ISSUE TITLE
Duplicate AnalyzerDependencyConflict diagnostics and possibly unnecessary analyzer assembly loading just to detect dependency conflicts

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2738] opened 2015-05-13 23:49 UTC
1. Create a C# diagnostic + code fix project (I have "Analyzer5" for this repro).

2. Add 2 portable class library projects to the solution, say "AnalyzerDependency_1" and "AnalyzerDependency_2". Add P2P reference from AnalyzerDependency_1 to AnalyzerDependency_2. Add the below code snippets to respective projects:

    1. AnalyzerDependency_2:
        ```c#
namespace AnalyzerDependency_2
{
    public class Class1
    {
        public string Message = "Message";
    }
}
        ```

    2. AnalyzerDependency_1:
        ```c#
namespace AnalyzerDependency_1
{
    public class Class1
    {
        public string Title = "Title";
        public static string Message = new AnalyzerDependency_2.Class1().Message;
    }
}
        ```

3. Add P2P reference from primary Analyzer5 project to AnalyzerDependency_1.

4. Build solution.

5. Repeat all the steps 1-4 above on a new solution (say Analyzer6). However, use different strings for code added to AnalyzerDependency_* projects, say "Title2" and "Message2". This ensures that Analyzer5 and Analyzer6 have dependencies with same assembly name, but different contents.

6. In a new VS instance, create a new solution with 2 C# projects, Classlibrary1.csproj and Classlibrary2.csproj

7. Add nuget package "Analyzer5.1.0.0.0.nupkg" to Classlibrary1.csproj to add the analyzer created in step (1).

8. Add nuget package "Analyzer6.1.0.0.0.nupkg" to Classlibrary2.csproj to add the analyzer created in step (5).

**Actual**: Following duplicate `AnalyzerDependencyConflict` diagnostics show in the error list.

```
Severity	Code	Description	Project	File	Line
Warning	AnalyzerDependencyConflict	Assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer5.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' and assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer6.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' have the same identity but different contents. These analyzers may not run correctly.	ClassLibrary1		1

Warning	AnalyzerDependencyConflict	Assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer5.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' and assembly 'C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary2\packages\Analyzer6.1.0.0.0\tools\analyzers\AnalyzerDependency_2.dll' used by analyzer 'AnalyzerDependency_1' have the same identity but different contents. These analyzers may not run correctly.	ClassLibrary2		1
```

It would be good to de-duplicate such diagnostics across projects.

Probably the more severe issue here is: are we actually loading AnalyzerDependency_1.dll and AnalyzerDependency_2.dll? Neither of these 2 dependency assemblies have any DiagnosticAnalyzers, so shouldn't be loaded to instantiate analyzers from it. Additionally, neither of these 2 assemblies are actually referenced by Analyzer5.dll and Analyzer6.dll (they ended up in the nuget package only because they were dumped to the output folder of core analyzer projects due to a redundant P2P reference).

So, are we eagerly loading analyzer reference assemblies just to determine if they have dependency conflicts, when the assembly itself has no analyzers and hence shouldn't be ever loaded?

**Comment by tmeschter** [comment] 2015-05-14 16:38
@mavasani All of the described behavior is by design.

Yes, we're actually loading the assemblies. Our template simply adds *every* .dll included in the NuGet as an analyzer. Since the binary has been specified as an analyzer, we need to load it up-front to check that you're getting the assembly you think you are.

I *personally* think that we should require analyzer authors to update the *.nuspec and *.ps1 files to be explicit about what gets included in the NuGet and which assemblies are added as analyzers, but I seem to be in the minority on that point. Feel free to file a bug about that and try your luck, though. :-)

I'm going to try and make the error messages shorter as part of the fix for #2684, but we're going to continue to report them for every affected project.

Closing as By Design.

**Comment by mavasani** [comment] 2015-05-14 17:11
This is extremely unfortunate, especially for VS scenario. It seems all the work that @srivatsn did to ensure that we only load analyzer assemblies that have relevant analyzers for the current project language is nullified in both command line and VS for project analyzer references. As it turns out, we are not only loading all the assemblies specified as analyzer assemblies upfront, but also all of it's dependencies. Isn't this going to be bad for solution open performance, as we will end up doing all of this eager loading for all projects with analyzer references?

"_Since the binary has been specified as an analyzer, we need to load it up-front to check that you're getting the assembly you think you are._"
I understand doing this for VBCSCompiler scenario as there is a fallback path of using csc.exe/vbc.exe that needs to be taken upfront. However, for VS IDE, what action do we take when detect these conflicts? We can't unload the assemblies, so I presume we are just giving out the conflict diagnostics? If so, why can't we delay all the dependency checks (and assembly loading) up until actually loading the analyzer assembly when queried for analyzers? I think this call: http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/AbstractProject_IAnalyzerHost.cs,37 should be delayed up until the assembly loader is actually requested to load the analyzer reference assembly for VisualStudio analyzers. This will ensure we don't do any eager or unnecessary assembly loading. Re-opening to consider this alternate.

/cc @pharring @heejaechang as they may have better guidance.

**Comment by tmeschter** [comment] 2015-05-14 18:05
@mavasani Performance concerns are always valid, but without data its impossible to know how much of an effect this is actually going to have. That being said, here are some relevant points:

1. We only run the consistency check for a project once we're pushing data from the language services to the workspace. This means we often won't kick off the consistency check until after the solution is loaded.
2. The actual consistency check runs on a background thread, and only posts work back to the UI thread in order to update the Error List.
3. We already do some caching of the consistency check results. If all projects in your solution use the same set of analyzer assemblies, we're only going to run the check once.
4. The move away from the `InMemoryAssemblyLoader` means that in general we're already performing fewer assembly loads. Previously, if `C:\Alpha\MyAnalyzer.dll` and `C:\Beta\MyAnalyzer.dll` had the same identity *we still would have loaded them both* due to the way the "No Context" load context work. Now that we're using the LoadFrom context, we will only load one.
5. When I fix #2684 I'm going to make the consistency check cheaper in some ways. Right now it reads the entire assembly file contents and computes a hash to determine if two assemblies are the same; I'm going to change this to simply check the MVID.

**Comment by mavasani** [comment] 2015-05-14 18:09
@tmeschter I am wondering if for VS scenarios we need any eager loading or dependency checking at all. Can we just get rid of this call: http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/AbstractProject_IAnalyzerHost.cs,37 and have a VS specific ShadowCopyAnalyzerAssemblyLoader (http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices/R/525c10f4c44b5bd9.html) which overrides the LoadCore (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/InternalUtilities/ShadowCopyAnalyzerAssemblyLoader.cs,84), invokes base.LoadCore and then checks if the loaded assembly has same MVID as the file requested to be loaded. If so, just report a diagnostic.

**Comment by mavasani** [comment] 2015-05-14 18:17
_Performance concerns are always valid, but without data its impossible to know how much of an effect this is actually going to have_

Well, we know for sure that we are loading analyzer assemblies + its dependencies upfront, while earlier we loaded them only at the point where it was needed, and only if it had analyzers. Given there are no functional scenarios that need us to do this and there could be easy tweaks to delay the diagnostic reporting at load time itself, isn't it preferable to avoid this eager/unnecessary loading?

**Comment by heejaechang** [comment] 2015-05-14 20:53
@mavasani @tmeschter if we are loading the dlls just for consistency checking, can we load them in different app domain and dump them once finished analysis?

**Comment by heejaechang** [comment] 2015-05-14 21:08
@tmeschter @mavasani @srivatsn @pharring by the way, if this change will cause dlls that are not part of current solution's language to be loaded. it needs to be taken out. that is RI blocking gate violation.

**Comment by mavasani** [comment] 2015-05-14 21:11
@heejaechang This change only affects per-project analyzers, not host specific analyzers. So I guess we are fine for that scenario.

However, I feel that we should still try to delay any kind of eager assembly loading/consistency checks here as the eventual goal is just reporting the conflict diagnostics, and we can do that when the VS assembly loader is asked to load any assembly.

**Comment by heejaechang** [comment] 2015-05-14 21:13
@mavasani no, same goes for per project analyzer.

**Comment by heejaechang** [comment] 2015-05-14 21:14
opened #2763

**Comment by mavasani** [comment] 2015-05-14 21:15
@heejaechang oh ok, I didn't know that. I thought our main concern was loading assemblies with our built in analyzers.

**Comment by heejaechang** [comment] 2015-05-14 22:13
@mavasani well we care about VM very much and the biggest offender is image load. thank you noticing it by the way.

**Comment by tmeschter** [comment] 2015-05-14 22:49
@mavasani @heejaechang I've figured out how to avoid the assembly loading (or at least not load it any sooner than it would have been).

The point of the assembly load is to check that the analyzer your project specifies and the one that actually gets loaded are the same (specifically, have the same MVID). The most likely scenario where this will *not* be the case is if you have two analyzers at different paths with the same identity but different MVIDs. We can catch this just using the metadata reader.

The less likely scenario that we will miss is if an analyzer assembly has the same identity as something else that is already loaded in VS. I'm willing to live with that.

**Comment by mavasani** [comment] 2015-05-14 23:08
@tmeschter +1 on your solution. Thanks!

**Comment by tmeschter** [comment] 2015-05-15 18:39
@mavasani OK, so that takes care of the assembly loading aspect of this issue.

I do not intend to de-duplicate the warnings that are the same across projects. We don't do that for missing references, and it would also lead to weird behavior when unloading projects.

Say you had two projects, A and B, with the same warning. Say we de-duplicate the warnings and only show the one for project A. If the user then unloads project A, the warnings go away--even though they apply equally well to project B.

What do you think?

**Comment by mavasani** [comment] 2015-05-15 18:46
@tmeschter Yes, I think that's fine.

**Closed** 2015-05-18 20:17 UTC
Labels: 4 - In Review, Area-Analyzers, Bug

**Comment by tmeschter** [comment] 2015-05-18 20:25
@mavasani Assigning back to you for verification.

**Comment by mavasani** [comment] 2015-06-15 22:58
@tmeschter Verified that the Analyzer dependency checker doesn't eagerly load the dependencies anymore.
