### ISSUE TITLE
ISymbol.ToDisplayString misses `where T : default` constrains for overridden method

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#63512] opened 2022-08-22 10:53 UTC
**Version Used**: `4.3.0-3.final`

**Steps to Reproduce**:

1. take example code snippet and compile dynamic library out of it
2. read symbols of `dll` `CSharpCompilation.GetAssemblyOrModuleSymbol(reference)`
3. synthesize source tree: ISymbol.ToDisplayString with listed `SymbolDisplayFormat`

p.s. I found it during testing of PoC https://github.com/andriipatsula/PoC-GenAPI-Roslyn and probably there is scenario to test this.

**Symbol Display Format**:
```C#
SymbolDisplayFormat _defaultDisplayFormat = new SymbolDisplayFormat(
    globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
    typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
    delegateStyle: SymbolDisplayDelegateStyle.NameAndSignature,
    extensionMethodStyle: SymbolDisplayExtensionMethodStyle.StaticMethod,
    propertyStyle: SymbolDisplayPropertyStyle.ShowReadWriteDescriptor,
    miscellaneousOptions: SymbolDisplayMiscellaneousOptions.AllowDefaultLiteral |
                          SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                          SymbolDisplayMiscellaneousOptions.RemoveAttributeSuffix |
                          SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                          SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier,
    kindOptions: SymbolDisplayKindOptions.IncludeMemberKeyword,
    parameterOptions: SymbolDisplayParameterOptions.IncludeDefaultValue |
                      SymbolDisplayParameterOptions.IncludeExtensionThis |
                      SymbolDisplayParameterOptions.IncludeName |
                      SymbolDisplayParameterOptions.IncludeParamsRefOut |
                      SymbolDisplayParameterOptions.IncludeType,
    genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                     SymbolDisplayGenericsOptions.IncludeTypeParameters |
                     SymbolDisplayGenericsOptions.IncludeVariance,
    memberOptions: SymbolDisplayMemberOptions.IncludeExplicitInterface |
                   SymbolDisplayMemberOptions.IncludeConstantValue |
                   SymbolDisplayMemberOptions.IncludeModifiers |
                   SymbolDisplayMemberOptions.IncludeParameters |
                   SymbolDisplayMemberOptions.IncludeType);
```

**Example**:
```C#
public abstract partial class A
{
    public abstract TResult? Accept<TResult>(int a);
}

public sealed partial class B : A
{
    public override TResult? Accept<TResult>(int a) where TResult : default { throw null; }
}
```

**Expected Behavior**: compilable code, similar to `Example`

**Actual Behavior**:
```C#
public abstract partial class A {
    protected A() { throw null; }
    public abstract TResult? Accept<TResult>(int a);
}
public sealed partial class B : A {
    public B() { throw null; }
    /// error CS0508: 'B.Accept<TResult>(int)': return type must be 'TResult' to match overridden member 'A.Accept<TResult>(int)'
    /// error CS0453: The type 'TResult' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
    public override TResult? Accept<TResult>(int a) { throw null; } // compiler expects `where TResult : default`
}
```

**Link to Arcade issue**: https://github.com/dotnet/arcade/issues/10526

**Comment by 333fred** [comment] 2022-08-22 21:31
Highly related to https://github.com/dotnet/roslyn/issues/56573. In general, we do not expect that the code produced by `ToDisplayString` is necessarily compileable. It's debatable whether the constraint should be included here, as it's not really a constraint: it's actually an anti-constraint. As an example, take this code snippet:

```cs
class C
{
    public virtual void M<T>() where T : struct {}
}

class D : C
{
    public override void M<T>() {}
}
```

If you call `ToDisplayString()` on the override of `M` here with the above format, you'll get `override void M<T>() where T : struct`, despite there not being a `where T : struct` in source. I'll ask @CyrusNajmabadi to chime in as well, but I think this should be closed as by-design.

**Comment by CyrusNajmabadi** [comment] 2022-08-22 21:40
This is by design for me.  Producing compilable code is dependent on a host of factors (including knowing precisely the context where the code is being generated into).  

Trivial examples of this include things like accessbility (which only previously became legal in things like interfaces) or whether abstract/virtual should be specified (which can depend on if you're in a class/interface/etc.).  

While i can't find a recorded note of this (since it far predates github), ToDisplayString was explicitly stated as *not* being for this purpose, and htat all codegen for it is explicitly out of scope.

*That said*.  Knowing the impl, i think it is ok to use ToDisplayString *solely* to generate *only* a type-syntax.  e.g. generating `System.Collections.Generic.IList<(int foo, string[] bar)>`.  It should actually work ok for that (as long as you are not referring to anonymous types), and doesn't have any known issues (AFAIK) that are problematic.  

However, it should not be used *beyond* that.  e.g. for signatures, inheritance lists, or other non-ITypeSymbol symbol types.

**Comment by 333fred** [comment] 2022-08-22 21:41
Closing as by-design then.

**Closed by 333fred** 2022-08-22 21:41 UTC
Labels: Area-Compilers, Feature Request
