### ISSUE TITLE
null flow error where bang operator does not bypass null error

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#74333] opened 2024-07-10 17:06 UTC
**Version Used**: 
VS Version 17.9.3

**Steps to Reproduce**:

```
        public int Compare(SomeEnum? x, SomeEnum? y)
        {
            var a = x != null
                ? _localizer.GetString(x)
                : string.Empty;
            var b = y != null
                ? _localizer.GetString(y)
                : string.Empty;

            if(a is not null && b is not null)
                return x is not null && y is not null
                    ? InternalCompare(a, b, x, y) // issue happens here
                    : a.CompareTo(b);

            if (a is null && b is null)
                return 0;

            return a != null ? 1 : -1;

            int InternalCompare(string sa, string sb, SomeEnum ea, SomeEnum eb)
            {
                var result = CompareLowSort(ea, eb);
                if (result == 0)
                    result = sa.CompareTo(sb);
                return result;
            }
        }
```

Sharplap [HERE](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxAvo0a+u2ugKYB2ArgFt0AZQD2g7gFEBg9gSTEl6AIIAadACF2LJJ1JwADAH50AcW4AXADJiAxgEMANgEsAXt2DVxkmUNMA1twAnrTy7EpQAOyYRgB0UoIADpbBANw67ProLryWOBJJDgBO3N4S0rKmAB4aPpX+6KHhispEAG4l6A7oALzo1egAhP0CTk4RbeimFjb2zu6e1NVhrVPEILGGCcmpGWvKncXoAEZ9TcOj/OOTbTNWto6uHl7NB+ubUPGJKenItzkAGbUHouADO6F4YnyYyc6AAZPDTjkIVCYdcnKt1pEYoNwZDoZCMQikcEUQT0Td3tiiKYAJJ5bjFXjObCFEplBwaE4aWpNegAegFKLB/G46AAFg4kkk+BCJUzuACPt04mzkhyACpiagnWj7AEuQHoEHk2Ek5H42FYmmYGKGA3UojRbqXInjaboODoTYAWjgjvWuXyDMsTJZTnVRVK1C+hnQYK5WwTPNEFT8wm4SfqGZ4eoBClt6CO6FKoqc+X6DuVxCNJrL10rVZtRaIDYr50TavZpW11DBev2RZd7csQ6muiUuiYQA=)

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

CS1503

**Expected Behavior**:

No diagnostic error. Or ! should work, but it does not.

**Actual Behavior**:

Does not compile - Bang operator does not work.

**Comment by taori** [comment] 2024-07-17 12:40
@RikkiGibson Updated the issue + provided Sharplab. Sorry for the delay. Was busy and forgot about it for a bit.

**Comment by RikkiGibson** [comment] 2024-10-22 16:18
Thank you for filing this issue.

It looks like the issue in this case is due to the representation of nullable value types. Unlike reference types, there is no implicit conversion between a nullable value type (which is really a `System.Nullable`), and its non-nullable counterpart. This is the case even if the compiler can see that you null-checked a variable of nullable value type beforehand.

One way to fix this would be to pass `x.Value` instead of `x` to `InternalCompare`.

While it is unfortunate that the behavior of nullable types is not unified across value and reference types in .NET, it is something we don't have any plans to change. Therefore I will close this issue out as "by design".

**Closed by RikkiGibson** 2024-10-22 16:18 UTC
Labels: Area-Compilers, untriaged
