### ISSUE TITLE
Roslyn ignores the minus operator from -NaN

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#64690] opened 2022-10-13 00:53 UTC
**Version Used**: main

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATABgLABQ2AjIYRsQJwAUAQgJYAuAwhAHYBuMUj3AdABEIAV2AAbGABUIASTaNUDRgGdqAExHiYfAHIBDHQEo+0gMqMo9NgHNqAIgAaADjuHDAbkIc9UAARq2XwBef00JXQNPIio6JlZObl4oQTCpWXlFJlUA4zMLK1tHFzcoiholeK4efiFRCWk5BRQlVTgckwhzSxt7Z1cPIA=

This doesn't conform IEEE754. 

**Expected Behavior**:
```csharp
Console.WriteLine(BitConverter.DoubleToInt64Bits(0.0 - double.NaN).ToString("X8"));
 Console.WriteLine(BitConverter.DoubleToInt64Bits(double.NaN).ToString("X8"));
 Console.WriteLine(BitConverter.DoubleToInt64Bits(0.0 - double.NaN).ToString("X8");
```

**Actual Behavior**:
```csharp
Console.WriteLine(BitConverter.DoubleToInt64Bits(double.NaN).ToString("X8"));
 Console.WriteLine(BitConverter.DoubleToInt64Bits(double.NaN).ToString("X8"));
 Console.WriteLine(BitConverter.DoubleToInt64Bits(0.0 - double.NaN).ToString("X8");
```

**Comment by CyrusNajmabadi** [comment] 2022-10-13 01:01
> This doesn't conform IEEE754.

Can you clarify which part?

@tannergooding looks to be a dupe of the other Convo on this topic.

**Comment by tannergooding** [comment] 2022-10-13 02:11
You've taken that slightly out of context. The relevant portions are:

> A language implementation preserves the literal meaning of the source code by, for example:
> * ...
> The following value-changing transformations, among others, preserve the literal meaning of the source
code:
> * ...
> * Changing the payload or sign bit of a quiet NaN
> * ...

This means that changing the payload or sign bit of a qNaN is allowed considered to preserve the literal meaning of the source code.

**Comment by tannergooding** [comment] 2022-10-13 02:24
That being said, Roslyn could choose to handle `0 - NaN` and `-NaN` as "regular sign inversion" to better match what happens at runtime for the canonical `NaN` input.

This is ultimately up to the Roslyn team since the current behavior is spec compliant. Just potentially confusing for some users.

It's worth calling out that the canonical `NaN` can vary between hardware. On Arm64 this is typically `+qNaN` but on x86/x64 it is typically `-qNaN`. Roslyn opted to normalize to `-qNaN` a couple releases back to help ensure determinism and to be "better compatible" with the 20 year "standard" since x86/x64 had effectively been the only supported architecture.

**Comment by hez2010** [comment] 2022-10-13 02:26
However, we don't have any way to express a -NaN in the source code now. I don't think it's a right thing:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+WQCYQCuwANjKQLIAUASlr1GYgG4BDKKQSkAvKQAMAOiWk4pVh24qAcpL0BuUWIYYA7LJMExAX0J2gA

**Comment by tannergooding** [comment] 2022-10-13 02:28
`-NaN` is the existing canonical NaN for Roslyn. It's therefore `+NaN` that you can't express as a constant.

The question would be why do you need this and why isn't one of the alternative patterns which Roslyn won't constant fold viable?

**Comment by hez2010** [comment] 2022-10-13 02:31
So why would
```csharp
var x = 0.0;
Console.WriteLine(x - double.NaN);
```

yields -NaN, while

```csharp
Console.WriteLine(0.0 - double.NaN);
```

yields NaN?

Shouldn't `0.0 - double.NaN` goes through `double.operator-`? It's inconsistent and confusing.

**Comment by tannergooding** [comment] 2022-10-13 02:33
> It's inconsistent and confusing.

There are many scenarios where constant folding vs not can lead to subtle differences in these kind of edge cases.

You are depending on functionality that normally doesn't matter. In the case of `Console.WriteLine`, we don't display the "sign" for NaN nor the payload so its not "visible" unless you manually extract the underlying bit representation or try and use it with something like SIMD operations.

**Comment by hez2010** [comment] 2022-10-13 02:37
So basically this kind of optimization leads to undefined behaviors. We should either update the spec or fix the behavior to match the runtime behavior. 
Personally I would like to see this optimization behavior being fixed given that it doesn't require major efforts, and also it can make things intuitive and consistent.

**Comment by tannergooding** [comment] 2022-10-13 02:43
> So basically this optimization leads to undefined behaviors.

Yesn't. Like many scenarios, there can be very subtle cases where this "could" matter. But if you're depending on it, you are more likely than not doing something wrong.

The question is then again, why do you need this and why isn't one of the alternative patterns which Roslyn won't constant fold viable?

> We should either update the spec or fix the behavior to match the runtime behavior.

There is no way to match the runtime behavior because the runtime behavior depends on the CPU you're executing on as I described above. On x86/x64 `0.0 / 0.0` produces `-qNaN` on Arm64 it produces `+qNaN`. This means that if no constant folding is done, the result of `0 - NaN` can be one of two results depending on if you're running on arm or xarch. Other platforms can differ in other ways.

> which makes it hard to port sNaN-aware algorithms from other languages.

.NET don't support `sNaN` and disables all IEEE 754 Exception Handling. Therefore `sNaN` is treated identically to `qNaN`. Trying to depend on `sNaN` will not do what you expect. This likewise applies to most other languages and runtimes where IEEE 754 exceptions are often disabled by default.

**Comment by tannergooding** [comment] 2022-10-13 02:46
The IEEE 754 specification explicitly tells you in `11. Reproducible floating-point results` to:
1. Not use `sNaN`
2. Not depend on the sign or payload of `qNaN`

As soon as you try to do either of these, you start getting into a scenario where the exact behavior and experience can vary across every device you run on, or even across multiple executions of the same code within a given process (because such functionality often has hardware level switches allowing the behavior to be dynamically changed).

This is why I say:
> if you're depending on it, you are more likely than not doing something wrong.

**Comment by CyrusNajmabadi** [comment] 2022-10-13 03:51
Closing out as this has been the long standing behavior of roslyn, is complaint with both the c# and ieee specs and only seems to be an issue for scenarios that are themselves explicitly called out as suspect.

**Closed by CyrusNajmabadi** 2022-10-13 03:51 UTC
Labels: Area-Compilers, untriaged

**Comment by hez2010** [comment] 2022-10-13 03:59
Seems that based on IEEE754-2019 5.5.1, the `negate` and `subtract` are treated differently, and when it comes with `-NaN`, the sign bit should be reversed.

**Comment by tannergooding** [comment] 2022-10-13 04:08
> Seems that based on IEEE754-2019 5.5.1, the negate and subtract are treated differently, and when it comes to -NaN (negate), the sign bit should be reversed.

Yes, `5.5` normally treats the values "opaquely" and ignore any special results around `sNaN` and "should" preserve the value of the sign bit and the payload of a given `qNaN`. However, this doesn't hold true for non-interchange formats and is not required to be held true in the face of the allowances given by `10.4` and `11`.

However, `10.4` and `11` effectively "override" the otherwise explicit behavior defined for `NaN` defined almost anywhere else in the spec. This also includes the behavior defined in `6.2` that explicitly describes `NaN` handling including "correct" propagation of results and with the callout that `5.5` is considered special. There is no such equivalent callout in `10.4` nor in `11` and so there is no special modification or rule that overrides the statement around changing the sign or payload of a `qNaN` still preserving the literal meaning of the source code.

**Comment by tannergooding** [comment] 2022-10-13 04:19
Once again, this ends up in a scenario where whatever the compiler does will potentially differ from what happens at runtime.

What happens at runtime can differ between different CPU architectures, even for the same assembly and runtime.

This is why the IEEE 754 spec explicitly calls out, without any special annotations or other considerations, that developers should not use `sNaN` and should not depend on the sign or payload of `qNaN`. If you are doing either of these then you are most likely depending on implementation defined behavior and it is highly possible you are leaving your algorithm open to subtle bugs when running under various different environments.

**Comment by tannergooding** [comment] 2022-10-13 04:23
If you do need to explicitly test an `sNaN` or the sign/payload of a `qNaN`, I would recommend using `BitConverter.Int32BitsToSingle` or `BitConverter.Int64BitsToDouble` (or the unsigned equivalents).

I would potentially also recommend explicitly using the relevant platform specific hardware intrinsics available via the `System.Runtime.Intrinsics` namespace (such as `System.Runtime.Intrinsics.X86.Sse` or `System.Runtime.Intrinsics.AdvSimd.Arm`). These give access to very specific hardware instructions where you can rely on a more exact behavior and handling with regards to implementation defined floating-point values.

However, I would also recommend simply not depending on such functionality in the first place. There is little to no reason to do so in .NET or even any modern floating-point algorithm in other languages. It is simply an additional path that will slow down your logic to support something that the vast majority of code will have disabled by default.
