### ISSUE TITLE
Codelens for internal static variables is not showing up

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35926] opened 2019-05-23 23:03 UTC
VSF_TYPE_MARKDOWNI have _internal static class_ and declared some _internal static variables_ at class level. The codelens is not working for this particular variables. Seems to me its a bug.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/542962/codelens-for-internal-static-variables-is-not-show.html
VSTS ticketId: 853984_
_These are the original issue comments:_

Visual Studio Feedback System on 4/23/2019, 01:15 AM (30 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-05-23 23:07
Reproduces in 16.1.0

![CodeLens_Bug](https://user-images.githubusercontent.com/7817401/58292078-d2556180-7d74-11e9-95da-d4a3cc7ddd62.png)

**Comment by vatsalyaagrawal** [comment] 2019-06-06 22:11
Duplicate of #23908

**Closed** 2019-06-06 22:11 UTC
Labels: Area-IDE
