### ISSUE TITLE
record Equals/GetHashCode - use CompilerGenerated attribute

### ISSUE THREAD

**Issue by MichaRotstein** [dotnet/roslyn#47613] opened 2020-09-01 01:33 UTC
Is there a reason why the compiler generated Equals and GetHashCode for C# 9 records are not annotated with [CompilerGenerated] ?

Can this be added ?

**Comment by Youssef1313** [comment] 2020-09-11 07:10
Probably it should be applicable also to Clone and PrintMembers

**Comment by Youssef1313** [comment] 2020-09-11 13:46
Duplicate of #46439

**Comment by kofifus** [comment] 2020-09-29 01:06
Any news/ETA on this ?

**Comment by stakx** [comment] 2021-01-06 09:57
Putting a `[CompilerGenerated]` attribute would be useful on all compiler-generated members, not just on `Equals` and `GetHashCode`. An empty `public record EmptyRecord { }` generates a whole batch of other members:

```csharp
public class EmptyRecord : IEquatable<EmptyRecord>
{
    public EmptyRecord() { }
    protected EmptyRecord(EmptyRecord original) { }
    protected virtual Type EqualityContract { get; }
    public virtual EmptyRecord <Clone>$() { }
    public virtual bool Equals(EmptyRecord? other) { }
    public override bool Equals(object? obj) { }
    public override int GetHashCode() { }
    protected virtual bool PrintMembers(StringBuilder builder) { }
    public override string ToString() { }
    public static bool operator !=(EmptyRecord? r1, EmptyRecord? r2) { }
    public static bool operator ==(EmptyRecord? r1, EmptyRecord? r2) { }
}
```

The only one currently marked as `[CompilerGenerated]` is the `EqualityContract` getter.

My own use case is as follows: I am working on [PublicApiGenerator](https://github.com/PublicApiGenerator/PublicApiGenerator) which, given an assembly, creates something like a source code version of the corresponding reference assembly. Ideally, we would want the above `EmptyRecord` represented in the output as follows:

```csharp
public record EmptyRecord
{
}
```

i.e. we'd like to filter out all default type members that the compiler has provided (in absence of user-provided members). This is only possible if the default implementations are marked in some way.

**Closed** 2022-02-08 20:40 UTC
Labels: Area-Compilers, New Language Feature - Records

**Comment by jcouv** [comment] 2022-06-15 17:13
Moving [discussion](https://github.com/dotnet/roslyn/pull/58542#issuecomment-1156199133) from PR back to issue.

> As far as I can tell this didn't make it to today's release of Version 17.3.0 Preview 2.0

@kofifus Can you add `#error version` in your repro and share the resulting output when you do a command-line build?

**Comment by kofifus** [comment] 2022-06-15 17:17
```
Compiler version: '4.3.0-2.22307.7 (069a85a7)'. Language version: preview
```

**Comment by kofifus** [comment] 2022-06-16 07:42
Thanks! Here is what I tried:

```
record R(int I);
var atts = typeof(R).GetConstructors()[0].GetCustomAttributes(true);
```

I get an empty array where I expected the `CompilerGeneratedAttribute` as described in https://github.com/dotnet/roslyn/pull/58542

**Comment by Youssef1313** [comment] 2022-06-16 08:27
This seems opposite to the tests I added in #58542

https://github.com/dotnet/roslyn/blob/ca4c5390dee39eb3ea4fb1960add9d2a1b931e1d/src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_Synthesized.cs#L840-L845

only copy constructor will have the attribute.
