### ISSUE TITLE
Large amount of tests appear to be no longer run in Jenkins

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8860] opened 2016-02-18 00:31 UTC
It appears that a large swath of tests are "passing" but not producing an XML file or taking any time:

```
15:01:12   RemoveByValVB.UnitTests.dll                                                 PASSED 00:00:00
15:01:12   Roslyn.Compilers.VisualBasic.Semantic.UnitTests.dll                         PASSED 00:00:00
15:01:12   Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll                             PASSED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.Emit.UnitTests.dll                                  PASSED 00:00:00
15:01:12   Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll                           FAILED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.Semantic.UnitTests.dll                              PASSED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.Symbol.UnitTests.dll                                FAILED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.Syntax.UnitTests.dll                                PASSED 00:00:00
15:01:12   Roslyn.Compilers.VisualBasic.Syntax.UnitTests.dll                           PASSED 00:00:00
15:01:12   Roslyn.Services.UnitTests.dll                                               PASSED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.WinRT.UnitTests.dll                                 PASSED 00:00:00
15:01:12   Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll              PASSED 00:00:00
15:01:12   Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll                      PASSED 00:00:00
15:01:12   Roslyn.Compilers.CSharp.CommandLine.UnitTests.dll                           PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.dll                       PASSED 00:00:00
15:01:12   Roslyn.Compilers.UnitTests.dll                                              PASSED 00:00:00
15:01:12   Microsoft.DiaSymReader.PortablePdb.UnitTests.dll                            PASSED 00:00:00
15:01:12   ImplementNotifyPropertyChangedCS.UnitTests.dll                              PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll                      PASSED 00:00:00
15:01:12   ImplementNotifyPropertyChangedVB.UnitTests.dll                              PASSED 00:00:00
15:01:12   Roslyn.InteractiveWindow.UnitTests.dll                                      PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.VisualBasic.Scripting.UnitTests.dll                  PASSED 00:00:00
15:01:12   ConvertToAutoPropertyVB.UnitTests.dll                                       PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.Scripting.UnitTests.dll                              PASSED 00:00:00
15:01:12   Roslyn.InteractiveHost.UnitTests.dll                                        PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.CSharp.Scripting.Desktop.UnitTests.dll               PASSED 00:00:00
15:01:12   Microsoft.CodeAnalysis.VisualBasic.Scripting.Desktop.UnitTests.dll          PASSED 00:00:00
15:01:12   Microsoft.Build.Tasks.CodeAnalysis.UnitTests.dll                            PASSED 00:00:00
15:01:12   Roslyn.ExpressionEvaluator.VisualBasic.ResultProvider.UnitTests.dll         PASSED 00:00:00
15:01:12   Roslyn.Compilers.CompilerServer.UnitTests.dll                               PASSED 00:00:00
15:01:12   ConvertToConditionalCS.UnitTests.dll                                        PASSED 00:00:00
15:01:12   Roslyn.Services.VisualBasic.UnitTests.dll                                   PASSED 00:00:11.7481261
15:01:12   Roslyn.Services.CSharp.UnitTests.dll                                        PASSED 00:00:14.5011862
15:01:12   Roslyn.Services.Editor.CSharp.UnitTests2.dll                                PASSED 00:00:26.6863418
15:01:12   Roslyn.ExpressionEvaluator.CSharp.ExpressionCompiler.UnitTests.dll          PASSED 00:01:00.6463166
15:01:12   Roslyn.ExpressionEvaluator.VisualBasic.ExpressionCompiler.UnitTests.dll     PASSED 00:01:41.2306168
15:01:12   Roslyn.VisualStudio.CSharp.UnitTests.dll                                    PASSED 00:02:09.3388020
15:01:12   Roslyn.Services.Editor.UnitTests.dll                                        PASSED 00:07:06.1559266
15:01:12   Roslyn.VisualStudio.Services.UnitTests.dll                                  PASSED 00:08:06.1926203
15:01:12   Roslyn.Services.Editor.UnitTests2.dll                                       PASSED 00:08:29.4659221
15:01:12   Roslyn.Services.Editor.CSharp.UnitTests.dll                                 PASSED 00:12:10.3820652
15:01:12   Roslyn.Services.Editor.VisualBasic.UnitTests.dll                            PASSED 00:12:48.5019948
```
See the test trend:

![image](https://cloud.githubusercontent.com/assets/1103906/13129738/caf45e3c-d593-11e5-8b48-6ff82b72a7a7.png)

This is extremely worrying and means we're missing a bunch of coverage in Jenkins.

**Comment by davkean** [comment] 2016-02-18 00:31
tag @dotnet/roslyn-infrastructure 

@natidea Can you please look into this? Tomorrow or as soon as possible?

**Comment by jaredpar** [comment] 2016-02-18 00:39
This is partially expected.  Our test infrastructure memoizes test results and has for some time.  This was of limited advantage until recently when we enabled deterministic builds.  Now tests on the same machine which produce the same binaries will just grab the old results intsead of re-running them.  That's why you see the 0 length run time.  

What's odd is the test results file not being placed in a location that jenkins can find.  

Can you point to a jenkins run where this happened so  I can look into the artifacts and see what is going wrong?  

Note: we can disable this caching if we need to pretty easily.

**Comment by jaredpar** [comment] 2016-02-18 00:41
To disable essentially change this line to `if (true)` 

https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/RunTests/Cache/CachingTestExecutor.cs#L34

**Comment by davkean** [comment] 2016-02-18 00:43
Here's a log: http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_master_win_rel_unit64/838/ with an example.

**Comment by davkean** [comment] 2016-02-18 00:43
And here's unit test results: http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_master_win_rel_unit64/838/artifact/Binaries/Release/xUnitResults/

**Comment by davkean** [comment] 2016-02-18 00:47
Trying to process what this means.

I was under the impression we cleaned the output, given this is kicking in that might not be the case. Secondly, does this mean flaky issues are more likely to be hit if they've already failed? Above in the log you see they have failed, but that was probably from a previous run.

**Comment by davkean** [comment] 2016-02-18 00:49
Also wonder if this is the cause of this: https://github.com/dotnet/roslyn/issues/8859. Or rather due to the way we log failures into a .out.log file, means that you're not copying the XML?

**Comment by davkean** [comment] 2016-02-18 00:51
One more question, does this mean that given there was 7000 tests actually run in this zero change merge - mean that determinism has a bug or our build has a bug?

**Comment by davkean** [comment] 2016-02-18 00:56
I like this if we can get the experience right. Right now this PR will never pass: https://github.com/dotnet/roslyn/pull/8812.

**Comment by jaredpar** [comment] 2016-02-18 01:44
> I was under the impression we cleaned the output, given this is kicking in that might not be the case. 

That's the beauty of determinism.  Even if you delete Binaries in its entirety the same build will produce identical outputs.  

> Secondly, does this mean flaky issues are more likely to be hit if they've already failed?

Yes.  The caching just caches based on the check sums of the inputs.  If a flaky test hits during a run then the flaky test will be cached.  Another run of the same bits will hit the cache and repro the flaky result.  But once the test is disabled the check sum changes for the binary, there will be no cache hit and the tests will be re-run. 

> Also wonder if this is the cause of this: #8859. Or rather due to the way we log failures into a .out.log file, means that you're not copying the XML?

This looks like a dupe of this issue.  Essentially something is wrong in the cache logic that deserializes the test results into the output folder.  

> I like this if we can get the experience right. 

Agree.  I'm happy to look into this and figure out what is going on here.  This has been running without error for some time now.  I'm interested to see what caused this to fail.  

> Right now this PR will never pass: #8812.

We should comment out that line I mentioned while i look into this.  That will cause this PR, and any others similarly blocked, to run.

**Comment by diryboy** [comment] 2016-02-18 09:51
Out of curiosity, suppose project B depends on A, and the source code of A changes, source code of B no changes, will the assembly produced by project B change?

**Comment by jaredpar** [comment] 2016-02-18 17:01
@diryboy time for my favorite answer: it depends :smile:

A case where it's unlikely to change is a change to a private implementation detail.  Say I made a minor bug fix to a private method (fixed a typo or added a comment).  In that case `A` will absolutely change but `B` likely will not because nothing observable about `A` has changed.  

A case where it will change is say if a default parameter value changes in `A` and `B` called that method relying on the default parameter.  Nothing in the source code of `B` has changed but since the default parameter is used within `B` it will produce a different binary.  

The test runner cache code takes this into account.  It doesn't simply hash the assembly being tested but the set of all assemblies that will participate in the test run.  That catches the exact case you are calling out here.

**Comment by diryboy** [comment] 2016-02-18 17:15
@jaredpar Thanks for the explanation!

**Comment by natidea** [comment] 2016-02-18 22:19
@davkean It does not appear there is any action needed on this bug. The pull requests we were worried about ( #8812 ) did pass in the end, and the test trends appear to be that all tests eventually run after not running for a few builds because of caching.

**Comment by diryboy** [comment] 2016-02-19 05:41
@jaredpar Do we have projects with dynamic references, such as MEF? Say project A defines the interface, project B implements, and project C only statically references A, but implicitly depends on B?

**Comment by davkean** [comment] 2016-02-19 05:48
@natidea Either we disable this until we've figured out the experience or we change it to do the right thing with the results XML. 

@jaredpar Letting you make the call on this. If you can't get to it soon, we should disable it.

**Comment by diryboy** [comment] 2016-02-19 07:02
Maybe not cache the result for a failed test assembly, so flaky tests have a chance to unblock PR?

**Comment by jaredpar** [comment] 2016-02-19 15:43
@davkean pretty sure I understand why this is happening.  Going to get this fixed in the AM today.

**Comment by tannergooding** [comment] 2016-02-19 17:01
@jaredpar, how does a deterministic build in any way impact how xUnit runs a test. As far as I am aware, if you tell xUnit to run the same binary twice, it will do exactly that. Did we add some special logic to our normal runs (not the deterministic build) to skip running the tests if a build was deterministic?

**Comment by tannergooding** [comment] 2016-02-19 17:06
Also, all of our temporary files and the workspace itself is completely wiped before each build, so there should never be any files left over when the next build runs.

**Comment by tannergooding** [comment] 2016-02-19 17:56
Ah, I see. Nevermind. We generate a folder in the %LocalAppData% directory to cache information. Then when running the tests we generate a file that would contain the information to cache (checksums, command line switches, etc) and compare it to the cached file. If they match, we don't run the test (but still print timing information).

**Closed** 2016-02-20 17:56 UTC
Labels: 2 - Ready, Area-Infrastructure, Urgency-Now
