### ISSUE TITLE
IOperation: VB - BoundLateMemberAccess, some information is not exposed through ILateBoundMemberReferenceExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8903] opened 2016-02-19 00:25 UTC
```
    <!--"Type" argument of the LateCall method. Optional when there is a receiver object. -->
    <Field Name="ContainerTypeOpt" Type="TypeSymbol" Null="allow"/>
    <Field Name="TypeArgumentsOpt" Type="BoundTypeArguments" Null="allow"/>
```

**Comment by jinujoseph** [comment] 2017-07-03 23:57
dupe of https://github.com/dotnet/roslyn/issues/20117

**Closed by jinujoseph** 2017-07-03 23:57 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, Concept-API, Language-VB, New Feature - IOperation
