### ISSUE TITLE
Unexpected behavior when Source Generator access external dll

### ISSUE THREAD

**Issue by lxymahatma** [dotnet/roslyn#73235] opened 2024-04-25 16:16 UTC
**Version Used**: 
Microsoft.CodeAnalysis 3.3.3
Microsoft.CodeAnalysis.CSharp 4.4.0

**Steps to Reproduce**:
I have the very simple `MyClass` in one project
```cs
public class MyClass
{
    private int _privateField;
}

```

And using [PrivateProxy](https://github.com/Cysharp/PrivateProxy) in another project in the same solution to automatically generate the proxy class. 
```cs
[GeneratePrivateProxy(typeof(MyClass))]
public partial struct MyClassProxy;
```
When using the extension method `AsPrivateProxy` will cause the `Error CS1061: 'MyClass' does not contain a definition for 'AsPrivateProxy' and no accessible extension method 'name' accepting a first argument of type 'MyClass' could be found (are you missing a using directive or an assembly reference?).`

I tried looking into PrivateProxy's source code to find a solution to use types from external dlls. I found out that because of #72369; the `INamedTypeSymbol.GetMembers()` call cannot access the private members of the class; therefore, the length of [Members after some execution](https://github.com/Cysharp/PrivateProxy/blob/2896a79bba4135e75ac3a3c834f537b99fb37eb6/src/PrivateProxy.Generator/PrivateProxyGenerator.cs#L87) should be 0 in this case (which is exactly 0 when debugging source generator, and if i comment out those lines, the whole thing compiles normally) . And [Line 94](https://github.com/Cysharp/PrivateProxy/blob/2896a79bba4135e75ac3a3c834f537b99fb37eb6/src/PrivateProxy.Generator/PrivateProxyGenerator.cs#L94) will cause the source generator to exit, so basically there should be no source generated files.

However, I could find the generated files both in Rider and VS
```cs
partial struct ClassLibraryMyClassProxy
{

    global::ClassLibrary.MyClass target;

    public ClassLibraryMyClassProxy(global::ClassLibrary.MyClass target)
    {
        this.target = target;
    }

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_privateField")]
    static extern ref int ___privateField__(global::ClassLibrary.MyClass target);

    public ref int _privateField => ref ___privateField__(this.target);
}

public static class MyClassPrivateProxyExtensions
{
    public static global::Test.ClassLibraryMyClassProxy AsPrivateProxy(this global::ClassLibrary.MyClass target)
    {
        return new global::Test.ClassLibraryMyClassProxy(target);
    }
}

}
```

Also, if i output the members.Length using source generator, it shows up 1 in the generated file
I think it's a some kind bug

**Expected Behavior**:
No source generated files.

**Actual Behavior**:
There are source generated files but cannot get correctly compiled.

**Comment by jaredpar** [comment] 2024-04-26 00:19
Looks like a dupe of #73269

**Closed** 2024-04-26 00:19 UTC
Labels: Area-Compilers, untriaged

**Comment by jaredpar** [comment] 2024-04-26 00:21
In short generators are not guaranteed to see private members in external assemblies. That may happen when run in VS but will not when run through the command line. That is due to a combination of factors (ref assemblies and metadata import options) and these behaviors are by design.

**Comment by lxymahatma** [comment] 2024-04-26 00:31
> In short generators are not guaranteed to see private members in external assemblies. That may happen when run in VS but will not when run through the command line. That is due to a combination of factors (ref assemblies and metadata import options) and these behaviors are by design. 

oh.. I thought since source generator cannot access private members in external libraries, the different behavior in debug and inside project is unexpected and is a bug
Cz like it's still a bit weird that you cannot access it, but in project it actually generate the files but can't get compiled. I thought it's a bug because i supposed it should be completely disabled

**Comment by jaredpar** [comment] 2024-04-26 00:39
It's more an artifact of the different way the IDE handles references compared to the command line. It would be ideal if there was the same behavior but each environment has different constraints they are working with.

**Comment by lxymahatma** [comment] 2024-04-26 00:44
> It's more an artifact of the different way the IDE handles references compared to the command line. It would be ideal if there was the same behavior but each environment has different constraints they are working with. 

Ah i see, then i guess I'll just wait for future improvements. Thank you for the detailed answer 👍🏻

**Comment by CyrusNajmabadi** [comment] 2024-04-26 00:46
Note: we do this in the IDE for huge memory savings.  In the IDE we have hte compilation objects just reference each other, without any emitting of IL/Metadata.

The command line doesn't do this at all.  When you build, it biulds, and it produces all those dlls (and all that IO).  What it produces is fed into the next compiler.

This is ok on the command line (people don't mind seconds or minutes of compile costs when tey make a change).  it's not ok in the IDE.  People make a change and expect it to be incorporated, globally, immediately.
