### ISSUE TITLE
SimplifyInterpolation inverts PadLeft and PadRight

### ISSUE THREAD

**Issue by martinstenhoff** [dotnet/roslyn#41811] opened 2020-02-20 10:46 UTC
**Visual Studio 2019 16.5 preview2 and preview3 with netcore sdk 3.1.101 and 3.1.200-preview-014977**: 

I was looking at the release notes for VS2019 16.5 P2 [What's New - Simplify interpolation](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.5.0-pre.2.0)
and thought the example looked a bit bizarre.

```
D d = new D();
var s = $"...{0.ToString("bar").PadLeft(3)}";
```
Use simplify interpolation and it's refactored to:
`var s = $"...{0,-3:bar}...";`

Why 0.ToString("bar") is used here to produce the output "bar" is perhaps some clever trick I'm not aware of as I would have expected a FormatException, however that's a different question.

**Steps to Reproduce**:
1. Add the following code:
```
var original   = $"|{"Roslyn".PadLeft(30)}|";
var refactored = $"|{"Roslyn".PadLeft(30)}|";

Console.WriteLine(original);
Console.WriteLine(refactored);
```

2. Run the suggested "interpolation can be simplified" code fix on the refactored variable expression =>
```
var original   = $"|{"Roslyn".PadLeft(30)}|";
var refactored = $"|{"Roslyn",-30}|"; //<- What?

Console.WriteLine(original);
Console.WriteLine(refactored);
```

**Expected Behavior**:

```
|                        Roslyn|
|                        Roslyn|
```

**Actual Behavior**:

```
|                        Roslyn|
|Roslyn                        |
```

**Comment by jinujoseph** [comment] 2020-02-26 20:52
Duplicate of #41826

**Closed by jinujoseph** 2020-02-26 20:52 UTC
Labels: Area-IDE, Bug, Resolution-Fixed
