### ISSUE TITLE
[readonly-ref] out parameter in ref struct method is disallowed?

### ISSUE THREAD

**Issue by ektrah** [dotnet/roslyn#21872] opened 2017-09-01 13:10 UTC
**Version Used**: 

[2.6.0-rdonly-ref-62031-09](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers/2.6.0-rdonly-ref-62031-09)

**Steps to Reproduce**:

1. Create a new .NET Core 2.0 C# console application
2. Add a package reference to Microsoft.Net.Compilers 2.6.0-rdonly-ref-62031-09
3. Change the language version to 7.2
4. Compile this code:

```csharp
public static class Program
{
    public static void Main()
    {
        new Foo().TryGet(out int value);
    }
}

public ref struct Foo
{
    public void TryGet(out int result)
    {
        result = 1;
    }
}
```

**Expected Behavior**:

No errors.

The code looks safe to me.

**Actual Behavior**:

Errors:

* Program.cs(5,30,5,39): error CS8168: Cannot return local 'value' by reference because it is not a ref local
* Program.cs(5,9,5,40): error CS8524: This combination of arguments to 'Foo.TryGet(out int)' is disallowed because it may expose variables referenced by parameter 'result' outside of their declaration scope

~~What's wrong with the code?~~  
(I assume this is work in progress.)

More importantly: What do the error messages *mean*? In particular the second one. I read it several times and still cannot figure out what it tries to say.

(I have read [span-safety.md#safe-to-escape](https://github.com/dotnet/csharplang/blob/9bae7bfdf94850fac6a87de7ff5aad7d2ecbe064/proposals/span-safety.md#safe-to-escape)).

cc @VSadov

**Comment by VSadov** [comment] 2017-09-01 13:58
This is a dupe of https://github.com/dotnet/roslyn/issues/21858

**Comment by VSadov** [comment] 2017-09-01 18:42
Thanks for reporting this!!!  
The issue should be fixed in https://github.com/dotnet/roslyn/pull/21860

The escape errors are a bit cryptic. For now we are more concerned with correctness of the analysis, but eventually may need to do something with errors to make them easier to follow/fix.

**Closed by VSadov** 2017-09-01 18:42 UTC

**Comment by VSadov** [comment] 2017-09-01 18:57
Actually, it was the https://github.com/dotnet/roslyn/issues/21858 that was fixed. 

In your sample, the error will still be reported. The reason is that we have to assume it is possible to wrap a single lvalue variable into a span or some other ref-like type.

So the callee can do something like

```C#

        public ref struct Foo
        {
            public void TryGet(out int result)
            {
                result = 1;
                this = WrapInASpan(ref result);
            }
        }
```

Such possibility triggers "no-mixing" rule at the call site. 'new Foo()' is safe-to-return and is a writeable input to `TryGet` and there is also an argument that is a local reference, which is not ref-returnable. Since there is a possibility of one affecting returnability of another, such mixing is disallowed.

 See https://github.com/dotnet/csharplang/blob/9bae7bfdf94850fac6a87de7ff5aad7d2ecbe064/proposals/span-safety.md#language-constraints

That is the part under "In a method invocation, the following constraints apply:"

**Comment by VSadov** [comment] 2017-09-01 19:23
In your particular case the error might go away if `Foo` is readonly struct, since `this` would be passed effectively as `readonly ref`, but the rules for that are not yet implemented.

```C#
    public readonly ref struct Foo
    {
        public void TryGet(out int result)
        {
            result = 1;
        }
    }
```

**Comment by ektrah** [comment] 2017-09-01 19:36
My real-world code is [here](https://github.com/ektrah/nsec/blob/d84450c7507502ece856084cb4918721618a1d10/src/Cryptography/Formatting/Asn1Reader.cs). The purpose of the struct is to conveniently pass around mutable state for incrementally reading from a ReadOnlySpan\<T\> (e.g., [here](https://github.com/ektrah/nsec/blob/d84450c7507502ece856084cb4918721618a1d10/src/Cryptography/ChaCha20Poly1305.cs#L170-L182)).

Changing the `bool TryRead(int, out Span)` method to `Span Read(int)` and setting the `bool _failed` field instead of returning it, fixes the TryRead error, but now the same error occurs at other places in the file.

**Comment by VSadov** [comment] 2017-09-01 19:51
`bool TryRead(int, out Span)` should work after #21858 that is fixed.

With [2.6.0-rdonly-ref-62101-05](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.NETCore.Compilers/2.6.0-rdonly-ref-62101-05)   the following compiles:

```C#
    public static class Program
    {
        public static void Main()
        {
            new Foo().TryRead(1, out var value);
        }
    }

    public ref struct Foo
    {
        public bool TryRead(int i, out Span s)
        {
            s = default;
            return true;
        }
    }

    public ref struct Span
    {

    }
```

**Comment by ektrah** [comment] 2017-09-01 20:04
I can confirm that the error no longer occurs with 2.6.0-rdonly-ref-62101-05.

Of course, this is instantly replaced by a new problem: If I make [my `Span` struct](https://github.com/ektrah/nsec/blob/cfb7c49cc3ea00415244a604d201f329d323bd13/src/Cryptography/Formatting/Asn1Reader.cs#L279-L316) a `ref struct`, I can no longer have a `Span[]` (and not even my unsafe allocation-free array where I access sequential `Span` fields by index using Unsafe.Add).

**Comment by VSadov** [comment] 2017-09-01 20:14
Ref structs are fundamentally stack-only types. That is the reason why they cannot be array elements or fields of types that are not themselves ref-like structs.

That is the price for being able to contain direct references to internals of heap objects - subranges of arrays and such. Such references cannot themselves be placed into a heap object, otherwise garbage collection will not know how to trace through them.

**Comment by ektrah** [comment] 2017-09-01 20:20
Hence my idea to use a struct that contains only an `int start` and an `int length`, so it can be safely placed into an array on the heap, and to slice the ReadOnlySpan\<T\> on demand. With my allocation-free array, actually nothing is placed on the heap at all. But I guess I can't convince the compiler of that...

**Comment by ektrah** [comment] 2017-09-01 21:17
[Fixed.](https://github.com/ektrah/nsec/commit/714ead88887d59bfd3941d8f85021cfbeab5546b)

Thank you for looking into this!
