### ISSUE TITLE
Add integration tests for Tools → Options

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69929] opened 2023-09-13 16:45 UTC
These issues would benefit from integration tests for Tools &rarr; Options behavior:

* #49473
* #69425

**Comment by Youssef1313** [comment] 2023-09-14 17:37
I'm not sure if https://github.com/dotnet/roslyn/pull/62357 could help with #49473. Depending on the root cause of #49473, it could be possible that #62357 help?

Though, #62357 introduces simple unit testing, far away from the capabilities and benefits of integration tests.

**Comment by CyrusNajmabadi** [comment] 2024-10-26 15:54
Closing out as speculative.  If we need to do this, this should be assigned to someone and should be in a milestone to get it done.

**Closed by CyrusNajmabadi** 2024-10-26 15:54 UTC
Labels: Area-IDE, Story, Test-Gap, untriaged
