### ISSUE TITLE
Intellisense "contains" not working fine!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68188] opened 2023-05-15 12:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-contains-not-working-fine/10362199)._

---
Hello,
I'm not able to find member or property with name of "AvailableUid" when I'm searching by "id".
I can only find this member when I type "uid" or "avail" or something like that.
I'm using latest version of Visual Studio 2022 and you can find the video as attached.

Best regards

---
#### Feedback Bot on 5/14/2023, 10:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2023-05-15 12:43
Completion is failing to correctly include a 'contains' filter when fewer than 3 characters appear. This is not the expected behavior.

**Comment by genlu** [comment] 2023-05-15 18:09
The pattern matcher is implemented this way to avoid overly aggressively matching when user just started typing (filter text of fewer than 3 characters)
https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/PatternMatching/PatternMatcher.cs,225

**Comment by sharwell** [comment] 2023-05-15 20:06
@genlu IMO we should not include a length restriction here if a substring match exists _and_ the filter text did not produce any higher priority match.

**Comment by genlu** [comment] 2023-05-15 20:55
We can definitely try it.

**Comment by kandicst** [comment] 2023-05-30 21:35
I think this makes sense. Since the pattern isn't at the start of the string these suggestion will usually be pretty far down it so won't make much of a difference.
However, users can quickly get to them if they know what they are looking for using Alt + P and other similar shortcuts.

I'll try to make a PR today.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 19:38
Closing out due to lack of movement on this.

**Closed by CyrusNajmabadi** 2024-10-25 19:38 UTC
Labels: Bug, help wanted, Area-IDE, IDE-IntelliSense, IntelliSense-Completion
