### ISSUE TITLE
Core CLR test failed on CI: Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#19929] opened 2017-06-01 00:28 UTC
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_coreclr_test_prtest/1589/consoleFull#-14656154052d31e50d-1517-49fc-92b3-2ca637122019

```
     Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName [FAIL]
16:26:44         Assert.Equal() Failure
16:26:44         Expected: System.IComparable
16:26:44         Actual:   System.IComparable
16:26:44         Stack Trace:
16:26:44               at Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName()
```

**Comment by cston** [comment] 2017-06-26 21:45
Duplicate of #18985.

**Closed by cston** 2017-06-26 21:45 UTC
Labels: Area-Compilers, Concept-CoreCLR, Flaky, Test
