### ISSUE TITLE
Nullable reference types: homogenizing them and nullable value types.

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#9936] opened 2016-03-21 09:56 UTC
As of now the following four functions have to be implemented to support nullability for both kinds (and the compiler still fails with CS1940):

```c#
	public static class NullableSS
	{
		public static U? SelectMany<T, U>(this T? source, Func<T, U?> func)
			where T : struct
			where U : struct
		{
			if (source.HasValue) {
				return func(source.GetValueOrDefault());
			} else {
				return null;
			}
		}
	}
	
	public static class NullableCS
	{
		public static U? SelectMany<T, U>(this T source, Func<T, U?> func)
			where T : class
			where U : struct
		{
			if (!ReferenceEquals(source, null)) {
				return func(source);
			} else {
				return null;
			}
		}
	}
	
	public static class NullableSC
	{
		public static U SelectMany<T, U>(this T? source, Func<T, U> func)
			where T : struct
			where U : class
		{
			if (source.HasValue) {
				return func(source.GetValueOrDefault());
			} else {
				return null;
			}
		}
	}
	
	public static class NullableCC
	{
		public static U SelectMany<T, U>(this T source, Func<T, U> func)
			where T : class
			where U : class
		{
			if (!ReferenceEquals(source, null)) {
				return func(source);
			} else {
				return null;
			}
		}
	}
```

With explicitly nullable reference types one single function should be sufficient to support all four cases:

```c#
	public static class Nullable
	{
		public static U? SelectMany<T, U>(this T? source, Func<T, U?> func)
		{
			if (IsNull(source)) {
				return func(AsNotNull(source));
			} else {
				return null;
			}
		}
	}
```

where `IsNull()` and `AsNotNull()` are some new language features that work the same way for both nullable value and reference types.

I'll test this on the latest working draft and will return with results.

**Comment by bkoelman** [comment] 2016-03-21 11:35
`ReferenceEquals(source, null)` today already works for both nullable value types and reference types. It returns `true` when passing in `int? i = null` and `string s = null`.

**Comment by HaloFour** [comment] 2016-03-21 11:57
This is a dupe of #9932.  As mentioned the compiler can't emit a single method that would support both nullable reference types and nullable value types as the types are different which would make the signatures different as well as the containing IL.  `T?` is either `T` or `Nullable<T>` and `Func<T, U?>` is either `Func<T, U>` or `Func<T, Nullable<U>>`, they are not interchangeable.

I don't know that there are any good solutions for consolidating this.  Without changing the BCL/CLR you could have the compiler spit out a Cartesian product of possible methods with the appropriate signatures, meaning that your one method would actually be four methods.  Changing the BCL alone you could have a `struct` reference type wrapper so that you can pass a reference within a `struct` to a `Nullable<T>`, e.g. `Nullable<Ref<string>>`.  Changing the BCL and CLR together you could remove the generic constraint and other specific behaviors around `Nullable<T>` so that it could support generic type arguments of reference types.

**Comment by orthoxerox** [comment] 2016-03-21 12:23
@HaloFour 

I'd rather change the CLR in a way that avoids storing a `bool` next to every nullable reference type. `object.ReferenceEquals` works on nullables because it accepts `object`s, and `box` CIL instruction is clever enough to push a `null` onto the stack when it pops an empty `Nullable<T>`. If I go back to my example:

```c#
    public static class Nullable
    {
        public static U? SelectMany<T, U>(this T? source, Func<T, U?> func)
        {
            if (ReferenceEquals(source, null)) {
                return func(AsNotNull(source));
            } else {
                return null;
            }
        }
    }
```

it looks like we might need a new CIL opcode, e.g., `castnotnull`, that unwraps a value if it's a nullable value type, does nothing if it's a reference type and spawns nasal demons if it's a non-nullable value type. Then the function can be compiled into the same sequence of opcodes for all combinations of generic parameter kinds.

**Comment by alrz** [comment] 2016-03-21 12:26
>I'd rather change the CLR in a way that avoids storing a bool next to every nullable reference type.

:+1:

This is basically [what Rust does](http://smallcultfollowing.com/babysteps/blog/2015/05/05/where-rusts-enum-shines/) when you use `Option<&T>` type.

/cc @HaloFour

**Comment by HaloFour** [comment] 2016-03-21 12:36
@orthoxerox 

> I'd rather change the CLR in a way that avoids storing a bool next to every nullable reference type.

You mean "nullable value type"?  You'd have to store something as there's no way to express a value type as a `null` otherwise.  What is the `null` value of an `int`?  The CLR needs that flag in order to know to box that `Nullable<int>` as a `null`.

**Comment by orthoxerox** [comment] 2016-03-21 12:59
@HaloFour No, I meant "nullable reference type", I was aiming to reply to your proposals:

> Changing the BCL alone you could have a struct reference type wrapper so that you can pass a reference within a struct to a Nullable<T>, e.g. Nullable<Ref<string>>. Changing the BCL and CLR together you could remove the generic constraint and other specific behaviors around Nullable<T> so that it could support generic type arguments of reference types.

**Comment by HaloFour** [comment] 2016-03-21 13:10
@orthoxerox 

> No, I meant "nullable reference type", I was aiming to reply to your proposals:

Ah, I do completely agree, a additional flag there is pointless.  But that's how `Nullable<T>` has to work and since `T?` can mean two things the only way to unify them would be through a lowest-common denominator.  I'm just throwing spaghetti against the wall as options to solve this problem.

**Comment by orthoxerox** [comment] 2016-03-21 13:24
Hm, or a workaround that should work, once again, because `??` is smart, but would add a tiny bit of overhead.

```c#
    public static class Nullable
    {
        public static U? SelectMany<T, U>(this T? source, Func<T, U?> func)
        {
            if (ReferenceEquals(source, null)) {
                return func(source ?? default(T));
            } else {
                return null;
            }
        }
    }
```

**Comment by HaloFour** [comment] 2016-03-21 13:38
@orthoxerox 

>  because `??` is smart, but would add a tiny bit of overhead.

The `??` isn't that smart (currently) and the compiler emits different IL depending on whether the target is a value type or a reference type.

**Comment by gafter** [comment] 2016-03-21 20:37
Dup of #9932; please move discussion there.

**Closed by gafter** 2016-03-21 20:37 UTC
Labels: Area-Language Design, New Language Feature - Nullable Reference Types
