### ISSUE TITLE
CS8616 in IEnumerator with structs

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#31556] opened 2018-12-05 18:17 UTC
The following code:
```c#
using System;
using System.Collections;
using System.Collections.Generic;
namespace N {
   public struct IndexedListEnumerable<T> : IEnumerable<(T Item, int Index)> {
       private readonly IReadOnlyList<T> list;
       public IndexedListEnumerable(IReadOnlyList<T> list) => this.list = list;
       public IndexedListEnumerator<T> GetEnumerator() => new IndexedListEnumerator<T>(list);
       IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
       IEnumerator<(T Item, int Index)> IEnumerable<(T Item, int Index)>.GetEnumerator() => GetEnumerator(); //warning
   }
   public struct IndexedListEnumerator<T> : IEnumerator<(T Item, int Index)> {
       private int i;
       private readonly IReadOnlyList<T> list;
       public (T Item, int Index) Current => (list[i], i);
       internal IndexedListEnumerator(IReadOnlyList<T> list) => (this.i, this.list) = (-1, list);
       public bool MoveNext() => ++i < list.Count;
       object IEnumerator.Current => Current;
       public void Dispose() { }
       public void Reset() => throw new NotImplementedException();
   }
}
```
Emits the following warning:
> Warning	CS8616	Nullability of reference types in return type doesn't match implemented member 'IEnumerator<(T Item, int Index)> IEnumerable<(T Item, int Index)>.GetEnumerator()'.

Is this the expected behavior? How exactly am I supposed to get rid of this warning in this case?

**Comment by jcouv** [comment] 2018-12-26 06:11
Thanks for reporting this. It's definitely a bug.
This is being worked on. Closing as duplicate of https://github.com/dotnet/roslyn/issues/31862

**Closed by jcouv** 2018-12-26 06:11 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
