### ISSUE TITLE
Local functions not in the navigation bar

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#17104] opened 2017-02-12 17:23 UTC
Currently we have 3 dropdowns in the navigation bar, projects, types in current file and members in current type.

Local functions are not in there, neither in GoToAll.

Should we have a fourth dropdown with variables/consts and local functions in current member?

**Comment by gafter** [comment] 2017-02-12 18:09
I should hope that methods are no so large that you need extensive tooling to navigate within them.

**Comment by miloush** [comment] 2017-02-12 18:30
I should too. I did end up in the need to jump to a local function from a different place in the file though, so if they were part of the methods shown in the third dropdown or at least reachable through GoTo**All**, that would help.

**Comment by miloush** [comment] 2017-02-12 19:49
Also note that you are talking production code here. One-off tools and sketching things is usually much more wild, yet still valid scenario I would argue.

**Comment by jnm2** [comment] 2017-02-13 16:13
I don't think I'd like local functions to be listed in the class member list, neither would I like having yet another dropdown at the top! What I would like this for the classes and members dropdowns to be unified to a single hierarchical dropdown so I can navigate the entire source file at once without switching back and forth between dropdowns.

Then optionally local functions could be nested inside the class member that defines them. But even without showing local functions, putting everything in one hierarchical dropdown would be amazing.

**Comment by miloush** [comment] 2017-02-13 16:34
@jnm2 isn't that what Solution Explorer does?

**Comment by jnm2** [comment] 2017-02-13 16:38
@miloush Not really, because I can't see everything at once in the file without clicking on each node to expand it. Plus I usually have Solution Explorer on another monitor.

**Comment by DustinCampbell** [comment] 2017-02-13 18:04
This is a duplicate of https://github.com/dotnet/roslyn/issues/8648. If you feel strongly about this, we can continue the discussion there.

**Closed by DustinCampbell** 2017-02-13 18:04 UTC
Labels: Area-IDE, Resolution-Duplicate

**Comment by miloush** [comment] 2017-02-13 18:17
@jnm2 you can set the solution explorer to track the active file, and activate it using keyboard. However I do see the point about expanding the tree, I think it's a bug that the star key does not work to expand it all the way down. Also note that you can create new SE views and scope them to the file, although there seems to be another bug of not showing the classes in that case. Yeah, I don't see any great way for your scenario at the moment...
