### ISSUE TITLE
(Bug?) Wrong ASCII Range

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#674] opened 2015-02-19 13:25 UTC
[scanner.vb::L580](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L580)

Should that `>`
```vb
            ' optimization for a common case
            ' the ASCII range between ': and ~ , with exception of except "'", "_" and R cannot start trivia
            If ch > ":"c AndAlso ch <= "~"c AndAlso ch <> "'"c AndAlso ch <> "_"c AndAlso ch <> "R"c AndAlso ch <> "r"c Then
                Return Nothing
            End If
```          
be `>=`
```vb
            ' optimization for a common case
            ' the ASCII range between ': and ~ , with exception of except "'", "_" and R cannot start trivia
            If ch >= ":"c AndAlso ch <= "~"c AndAlso ch <> "'"c AndAlso ch <> "_"c AndAlso ch <> "R"c AndAlso ch <> "r"c Then
                Return Nothing
            End If
```

**Comment by pharring** [comment] 2015-02-20 18:20
Yes, I think you're right.
Note that, for this kind of perf, we often use the "check the range in one comparison by using unsigned" trick.
i.e. instead of
```if (c >= low && c <= hi) ...```
we do
```if (c-(unsigned)low <= (unsigned)(hi - low)) ...```
I forget exactly where the casts go and you probably also need an ```unchecked``` in there too.
For an example, see [SourceText.cs#L742](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/SourceText.cs#L742)

**Comment by AdamSpeight2008** [comment] 2015-11-20 21:46
If I set the comparison operator to `>=` rather than `>` the following test fails.
```
<collection time="0.007" skipped="0" failed="1" passed="0" total="1" name="Test collection for Microsoft.CodeAnalysis.VisualBasic.UnitTests.Microsoft.CodeAnalysis.VisualBasic.UnitTests.SyntaxTriviaListTests">
<test time="0.0073255" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.Microsoft.CodeAnalysis.VisualBasic.UnitTests.SyntaxTriviaListTests.Extensions" result="Fail" method="Extensions" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.Microsoft.CodeAnalysis.VisualBasic.UnitTests.SyntaxTriviaListTests">
<failure exception-type="Xunit.Sdk.EqualException">
<message>
<![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   -1]]>
</message>
<stack-trace>
<![CDATA[   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Microsoft.CodeAnalysis.VisualBasic.UnitTests.SyntaxTriviaListTests.Extensions() in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Syntax\SyntaxTriviaListTests.vb:line 9]]>
</stack-trace>
</failure>
</test>
</collection>
```

```
<test time="0.0032917" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests.Scanner_EmptyToken" result="Fail" method="Scanner_EmptyToken" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests">
<failure exception-type="Xunit.Sdk.EqualException">
<message>
<![CDATA[Assert.Equal() Failure\r\nExpected: 11\r\nActual:   7]]>
</message>
<stack-trace>
<![CDATA[   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests.ParseTokensAndVerify(String str, SyntaxKind[] kinds) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Scanner\ScannerTests.vb:line 367
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests.Scanner_EmptyToken() in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Scanner\ScannerTests.vb:line 351]]>
</stack-trace>
</failure>
</test>
```

```
<test time="0.0195163" name="Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Formatting.Indentation.SmartIndenterTests.Bug5559" result="Fail" method="Bug5559" type="Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Formatting.Indentation.SmartIndenterTests">
<traits>
<trait name="Feature" value="SmartIndent"/>
</traits>
<failure exception-type="Xunit.Sdk.EqualException">
<message>
<![CDATA[Assert.Equal() Failure\r\nExpected: 8\r\nActual:   12]]>
</message>
<stack-trace>
<![CDATA[   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Formatting.Indentation.SmartIndenterTests.AssertSmartIndent(String code, Int32 indentationLine, Nullable`1 expectedIndentation, IndentStyle indentStyle) in H:\Source\Repos\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\Formatting\Indentation\SmartIndenterTests.vb:line 2916
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Formatting.Indentation.SmartIndenterTests.Bug5559() in H:\Source\Repos\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\Formatting\Indentation\SmartIndenterTests.vb:line 1852]]>
</stack-trace>
</failure>
</test>
```

So is just an error in the comment?

**Comment by AdamSpeight2008** [comment] 2015-11-20 22:13
Also a github bug. As the link in the original post is broken because the source has been updated.

**Comment by VSadov** [comment] 2015-11-20 22:41
The test fails because ":" can start trivia. - SyntaxKind.ColonTrivia .

**Comment by VSadov** [comment] 2015-11-20 22:42
The "  > " part is actually correct. The unsigned compare as Paul suggested, might still be a viable optimization though.

**Comment by AdamSpeight2008** [comment] 2015-11-20 22:47
I think just a change to the comment would suffice, to clarify the clusivity of the range.
```vb
' optimization for a common case
' the ASCII range between ': (exclusive) and ~ (inclusive) , with exception of except "'", "_" and R cannot start trivia
```

**Comment by VSadov** [comment] 2015-11-20 23:04
yes, the comment is indeed ambiguous. "with exception of except" also seems a bit clumsy.

**Comment by AdamSpeight2008** [comment] 2015-11-20 23:36
@VSadov I've submitted a PR.

**Comment by gafter** [comment] 2015-11-22 16:39
The ascii range in the code is correct. Trivia can begin with ":". Closing as by design.

**Closed by gafter** 2015-11-22 16:39 UTC
Labels: Area-Compilers, Resolution-By Design
