### ISSUE TITLE
Collection Expression Compile Error after upgrading to SDK 8.0.3.

### ISSUE THREAD

**Issue by oruchreis** [dotnet/roslyn#73761] opened 2024-05-29 09:38 UTC
**Version Used**:  8.0.3

**Steps to Reproduce**:
Build below code in 8.0.1 and 8.0.3, 8.0.1 succeeds, but 8.0.3 doesn't.
```csharp
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text;
using System;

public class C {
    public void M() {
        IpList list = ["",("","")];
    }
}

public class IpList : IEnumerable
{    
    public IpList()
    {
        
    }
    private uint ParseIp(string ipNumber)
    {
        throw new NotImplementedException();
    }

    public void Add(string ipNumber)
    {
        throw new NotImplementedException();
    }

    public void Add(uint ip)
    {
        throw new NotImplementedException();
    }
    
    public void Add(string ipNumber, string mask)
    {
        throw new NotImplementedException();
    }

    public void Add((string ipNumber, string mask) ipMask)
    {
        throw new NotImplementedException();
    }

    public static implicit operator IpList((string, string) ipMask)
    {
        throw new NotImplementedException();
    }

    public static implicit operator IpList(string ipNumber)
    {
        throw new NotImplementedException();
    }
    
    public void Add(uint ip, uint umask)
    {
       throw new NotImplementedException();
    }
    
    public void Add(string ipNumber, int maskLevel)
    {
        throw new NotImplementedException();
    }
    
    public void AddRange(string fromIp, string toIp)
    {
        throw new NotImplementedException();
    }
    
    public void AddRange(uint fromIp, uint toIp)
    {
        throw new NotImplementedException();
    }    
    
    public IEnumerator<(string, uint)> GetEnumerator()
    {
        throw new NotImplementedException();
    }
    
    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }   
    
    private class IpArrayList
    {
        public void Add(uint ip) {}
    }
}
```
If I remove `public IEnumerator<(string, uint)> GetEnumerator()` method, it builds in 8.0.3 too.

I've tried in sharplab.io too, it compiles in c# 12 collection expression branch, but not in main branch.

[Compile Failed Main Branch](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAOgGEB7AGzIFMBjAFyhJgGcBuAWACgtc8AWdrjnwEAcpVoDuwgEoBXGPTCViJMAAcoVAE4BlSloBuUapVacphACqUAHhPMAmPJ3MBmXA+xFsAb07YA3Hd0XmwAWQAKAEpff0D4gEk1ABkoJlpsMjSMgF5sAG0AIkK4COK4YqiAXQF4gF9OBo43D2wk1PTsEB5XTh94uID0d3bs6MHYjniBqcCm+LUtKAMIWkpsWVgMgAUILSZKJIj8HCg1EVkwYH0oib9Z6exaAAstEgB3bBhKT5ESWgS6ioSgUlAQAFEbCY1PRGNFanMXA8grhQgBBBAIY54U7nS7XLS3ZH3R4BF5vT7fX7/QFqYGUUEQqGUGEMGDwiZNCbDVHYDFYzYKbBnInxEmk8kfL4/bB/AFAyggtZM6Gw9lRBEBeaBbnBdGY7G4i5XfRwHg4SBMADWosC4sekspMrltPpjMhqrZHORXORPJCfINhuFeJNWjNJ2wlptIbCEGttoC9umjul1PldMVDOVHpZau99SR8X9eAAbMKgcYoBkSGp9KsSFo2ikxoaIziYmc4wm7hN4qmqbKaQqlWDc6y4RrOUXAiXy1BK9Rq9ha/XaI3mx1aMGzsaCYnJqSnq8pYOXSPs2PmRP1ZrsNqArrefyIoKMmczW+NtGD8nAgPnWHTNRxVPMvSnH0JifAMX0jXd8VNYUhWjZJKAMSgyF/Pt/xPJ101dLN3WvfMIMLZFoP1BBpAgGAAHNKGDAAzN4wCSdscHXJIsORftcLTIcMzdHNiPAu8H2wCjAyomj6NfLZsGY1Q2I2eTOLUbijwA/CLyIz1JzEmZDNnEZwRgS410bAAeNsVIUKIAD5sAAcXEUzzK0BstHGYlsLJPizyAoSrz029p3I5EEjcpQPPXJt8FcAgXNoKKLK8jSJX8wDBMI4SQoLOYdXChYlhWNZWiSNEtA8gBPLdex44znwNL8RV8cSmjqIA===)
[Compiled in C#12 Collection Expression branch](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGED2AbbEDGMAlpgHYAyRMECU2yANACYgDUAPgAIAMABJwEYAdFlwFiZZAG4AsACge/AQBZZCvoKEA5CDDWLNAJTiliAWwgjMZgA5E8CAMo0AbkXwp9G4QBUIADz15TgAmAXlggGZ+EN50XgBveV4U/mjOZV4AWQAKAEpE5NTigEkbSmQYXmwiSt4AXl4AbQAiFoYctoY2vIBdNWKAX3lhuSiY3jKKqpAlSPkE4qKUzmip2ph85cK5YqXd1NHimwQiF1gIXjgiU14ABSgEZAgynME+IhstODNgGjztkkDnteDAABYITAAd14pAgMK0mBgJVseAspggTAAov4PDYJKR8gNDhFgWl+JkAIJMJhvAQfL4/P4IAFkoEglLgyEwuEIpEomxoiAY7G4iD4kiEvLElKjbarCm8am0663T6s4rsjlc6Gw+G8RHI1EQdHUUV4glE7ZHVLy9JUml0hnfX40BhKPhmKDIADWGtSWpBOp5+sNAqFIpxFslVrJcrJCoySsdTt4nxdzPd714Xt9BU+WW9fsB22Kwb1fKNgpNwrNUfFlul1tJxUTAgAbGnUe4qLxMDYaLBMAhJuUNjknVn6fmbIW8yWyWWIbreQb+cbTZj6xKyLGhi3Um3O0Ru/he/3BzBh6Ppqn00z/guOaDlyHK+Ga5GxTupTLeDaUjtRVlRyVUqk+d0wKuXNizZUtOVfCs1yrCM62/Rs/wA3ggKTEDs3vV0EHdG4qhg8gIBcCBsH9FJAz2ctVzDDday3dCYybONthwh0mEMKBSAAcwgVMwEhMwyinPgrzKGidmfBjQ3XatN3NBt2MwriE3tZNeP4oTQJI3hROsCSrkM6SbFkuil25JCmOUljVJ/PdDn2NzDzWLFSB+S9hwAHknMzTDyAA+XgAHFdC8nzaCvBAtjgxdUgU99mK/aNdw4/cyW2EpoosWLr0ESIhEimB8t8+KrPghDbMYpTUNYjLf2tW0crJE4zguCYykpBBaAAT2mJ8OUTHiDLVSzEiw0ZBiAA)

**Expected Behavior**:
It compiles in SDK 8.0.3, too.

**Actual Behavior**:
It fails to compile collection expression when adding `public IEnumerator<(string, uint)> GetEnumerator()` method.

**Comment by cston** [comment] 2024-05-29 14:26
@oruchreis, thanks for reporting this.

The collection expression conversion requires each element in the collection to be implicitly convertible to the *iteration type* of the target type. Previously, the compiler ignored the strongly-typed `GetEnumerator()` implementation and assumed the *iteration type* of a type implementing `IEnumerable` only is `object` (rather than `(string, uint)` in this case) and that all elements were implicitly convertible to `object`.

Sorry for the inconvenience.

**Comment by oruchreis** [comment] 2024-05-30 06:51
@cston But the element item is not `(string, uint)`, it is `object` in this case, The class is `IEnumerable` and not `IEnumerable<(string, uint)>`. The `IEnumerator<(string, uint)> GetEnumerator()` method is not belong to `IEnumerable` interface. Shouldn't the compiler not recognise this method as part of `IEnumerable`? Anyway, this method does not belong to `IEnumerable`. So the collection expression is applied to a class that implements `IEnumerable`, not to a class that is `IEnumerable<(string, uint)`.

**Comment by cston** [comment] 2024-05-30 12:31
The *iteration type* used by collection expression conversions is the [*foreach statement iteration type*](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/statements.md#1295-the-foreach-statement) which prefers the signature of the accessible `GetEnumerator()` method, if any, over the interface. It was an oversight that the compiler ignored the accessible `GetEnumerator()` method previously for the conversion and simply relied on the interface.

**Comment by jaredpar** [comment] 2024-06-05 17:25
Closing as the new behavior is "By Design".

**Closed by jaredpar** 2024-06-05 17:25 UTC
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions
