### ISSUE TITLE
IntelliSense lists not filtering for generic constraints on extension methods

### ISSUE THREAD

**Issue by BrianBu01** [dotnet/roslyn#40022] opened 2019-11-26 19:00 UTC
This is similar to #38382, but this is with constraints.  I believe that in past versions this worked, not 100% sure though.

**Version Used**: 

I tried Framework 4.7.2 and 3.1.0-preview3.19553.2, Visual Studio 2017 and Visual Studio 2019 Preview

**Steps to Reproduce**:
```
    class Program
    {
        static void Main(string[] args)
        {
            var list1 = new List<Entity1>();
            list1.FindEntity("");

            var list2 = new List<Entity2>();
            list2.FindEntity("", 1);
        }
    }
```

    public interface IIdentity<T1>
    {

    }

    public interface IIdentity<T1, T2>
    {

    }

    public class Entity1 : IIdentity<string>
    {
    }

    public class Entity2 : IIdentity<string, int>
    {
    }

    public static class ListExtensions
    {
        
        public static TEntity FindEntity<TEntity, T1>(this List<TEntity> list, T1 key1)
            where TEntity : IIdentity<T1>
        {
            return default(TEntity);
        }

        public static TEntity FindEntity<TEntity, T1, T2>(this List<TEntity> list, T1 key1, T2 key2)
            where TEntity : IIdentity<T1, T2>
        {
            return default(TEntity);
        }
    }

**Expected Behavior**:
I expect the generic types to be inferred and only 1 of the extension methods show up.

![TypedMethodShows](https://user-images.githubusercontent.com/4741884/69663547-75ed3a80-1054-11ea-85ce-bab0ffac53f0.PNG)

**Actual Behavior**:
Both extension methods show up without generics being applied.

![BothExtensionsShow](https://user-images.githubusercontent.com/4741884/69663559-7c7bb200-1054-11ea-8411-37adf505859a.PNG)

**Comment by Dreamescaper** [comment] 2019-11-27 10:37
Duplicate https://github.com/dotnet/roslyn/issues/39689

**Comment by sharwell** [comment] 2019-11-27 22:41
Duplicate of #39689

**Closed by sharwell** 2019-11-27 22:41 UTC

**Comment by BrianBu01** [comment] 2020-08-06 19:40
@sharwell Can you confirm this was fixed with the duplicate?  Cause I am still seeing this bug in 16.6.5
