### ISSUE TITLE
Unity 2017 / .NET 3.5 records support

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#55812] opened 2021-08-23 13:19 UTC
This issue makes it impossible to use records in Unity.

**Version Used**: 
3.1100.21.40306

**Steps to Reproduce**:

Code:
```cs
record A{}

public class P {static void Main(){}}
```

Project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>9</LangVersion>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
</Project>
```

**Expected Behavior**:
Use System.Type.Equals instead of System.Type.op_Equality when compiling to .NET 3.5 or below.
It could be a compiler flag.

**Actual Behavior**:
error CS0656: Missing compiler required member 'System.Type.op_Equality'

**Comment by jcouv** [comment] 2021-08-23 17:03
Records are only supported in .NET 5 and above. This is by-design.
That said, some people have used records in older frameworks by defining the `IsExternalInit` attribute ([example](https://blog.ndepend.com/using-c9-record-and-init-property-in-your-net-framework-4-x-net-standard-and-net-core-projects/)).

**Comment by NN---** [comment] 2021-08-23 17:07
Thanks.
Unfortunately the problem in .NET 3.5 is more subtle than simply adding attribute.

**Comment by RikkiGibson** [comment] 2021-08-23 18:29
I thought for a moment that maybe a sealed record inheriting from object could sidestep the issue, but that doesn't seem to be the case. [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDOQZwKYEMA2HgAEAThgMYD2RhASmQBQCWAdgC4EAeANAc2wJ4BKZAG9kAXyA===)

@jcouv is there a specific reason that we continue to emit EqualityContract, etc. members and check them in Equals for such a record? It does [appear to be intentional](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/records.md#equality-members).

**Comment by CyrusNajmabadi** [comment] 2021-08-23 19:14
> @jcouv is there a specific reason that we continue to emit EqualityContract, etc. members and check them in Equals for such a record?

I think the main complaint is that we emit `EqualityContract == other.EqualityContract` and don't have a fallback to `Equals(EqualityContract, other.EqualityContract)` when System.Type doesn't provider `==`.  

However, as we do not support .net 3.5, i'm not sure why we'd really change that as `==` here has been supported for ages:

![image](https://user-images.githubusercontent.com/4564579/130504476-b5271185-e1e3-410a-9f24-af8f721e7d91.png)

3.5 is currently 14 years old and incredibly ancient.  I'd recommend moving to more modern platforms.

**Comment by NN---** [comment] 2021-08-23 19:20
@CyrusNajmabadi Thanks for clarification.
You are right that .NET 3.5 is old, but Unity 2017 is not ;)

Solving this for Unity 2017 in a way you mentioned has a nice side effect of supporting .NET 3.5.

**Comment by CyrusNajmabadi** [comment] 2021-08-23 19:22
Can unity provide that System.Type operator?

**Comment by NN---** [comment] 2021-08-23 19:38
Yes, Unity has non experimental .NET 4 support since 2018.

Upgrading Unity not always easy, hence the proposal.

**Comment by RikkiGibson** [comment] 2021-08-23 19:59
> > @jcouv is there a specific reason that we continue to emit EqualityContract, etc. members and check them in Equals for such a record?
> 
> I think the main complaint is that we emit `EqualityContract == other.EqualityContract` and don't have a fallback to `Equals(EqualityContract, other.EqualityContract)` when System.Type doesn't provider `==`.

That's correct, however, it appears at a glance that EqualityContract is superfluous on a sealed record inheriting from object, and so eliding it could be seen as a small optimization which has the side effect of making the user's scenario happen to work.

**Comment by jaredpar** [comment] 2021-08-24 17:18
Closing because as mentioned above this behavior is "By Design". Records are only officially supported on `net5.0` and above. Some allowances are made for `net48` but it is still "buyer beware". The `net35` framework is well out of support here and not in our support matrix here.

**Closed by jaredpar** 2021-08-24 17:18 UTC
Labels: Area-Compilers, Resolution-By Design, untriaged

**Comment by jaredpar** [comment] 2021-08-24 17:20
> That's correct, however, it appears at a glance that EqualityContract is superfluous on a sealed record inheriting from object, and so eliding it could be seen as a small optimization which has the side effect of making the user's scenario happen to work.

Consider the case when you're consuming record instances across assembly boundaries. At the moment you compile yes the type is `sealed` but you can't depend on that being true at runtime. Consider that removing `sealed` from a type is not a breaking change. That means the assembly author between versions could remove `sealed`, add some derived types, and update the assembly in place in an app where you compiled code against the `sealed` version. That is why we need to keep the equality contract check in place even for `sealed` records. 

Yes in the case where we are comparing `sealed record` instances in the assembly where they are defined we could elide the check but that is getting fairly corner case.

**Comment by koszeggy** [comment] 2023-09-27 17:32
This issue is not Unity-related. Affects also simple class libraries containing class records compiled against .NET Framework 3.5.

> 3.5 is currently 14 years old and incredibly ancient. I'd recommend moving to more modern platforms.

As of today, .NET Framework 3.5 is officially planned to be [supported](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework) until Jan 9, 2029. But since Roslyn is not complaining about targeting an unsupported platform (unlike in case of default interface implementations, for example) and just unconditionally emits a faulty code, this seems clearly a bug to me.

And though recommending an upgrade can be reasonable for an application, a class library generally should aim for lower versions (among the newer ones) to be able to be used on every possible platform.

**Workaround:**

Though a bit inconvenient, you can actually forcibly replace the strongly typed `Equals` method to make the code compile even in .NET Framework 3.5:

```cs
record A
{
#if NET35 // Workaround for compiler bug: CS0656: Missing compiler required member 'System.Type.op_Equality'

    public bool Equals(A other) => ReferenceEquals(this, other)
        || (other is not null && EqualityContract == other.EqualityContract
        /*&& Prop1 == other.Prop1 && Prop2 == other.Prop2, etc. */);

#endif
}
```

**Note:** only class records are affected by the bug.

Sorry for commenting in a closed issue. I'm not necessarily asking for reopening it but wanted to at least share the workaround. Still, I would be glad if the compiler team considered fixing this issue as the workaround is not quite refactoring safe in terms of adding new properties.

**Comment by CyrusNajmabadi** [comment] 2023-09-27 18:09
> this seems clearly a bug to me.

we have explicitly stated that compiling these features for downlevel runtimes is unsupported/undefined.  Unsupported/undefined means that any behavior is acceptable.  We sometimes makes marginal efforts for a non-terrible experience.  But we're basically not ever signing up for that.
