### ISSUE TITLE
Opening older VB .NET Project in VS2019 - Missing Goto Definition Feature and Form Designer Failure

### ISSUE THREAD

**Issue by chatteberg** [dotnet/roslyn#41338] opened 2020-01-31 18:39 UTC
**Version Used**: VB .NET 4.6.1 Windows Forms Application Project

**Steps to Reproduce**: We have been using VS2017 and this specific project works correctly. I installed VS2019 and noticed some features are not working. 

1. When I attempt to open a Form Designer, I get the error 'The designer could not be shown for this file because none of the classes within it can be designed'. There are no other details explaining where to start looking for a cause. It happens on all 50+ forms. If I create a new form, it happens with the new form, too.
2. When I click on a Function Name, of a Function in another file, and select Peek Definition, nothing happens.
3. When I click on a Function Name, of a Function in another file, and select Goto Definition, the error 'Cannot navigate to the symbol under the caret' occurs.
4. When I click on a Function Name, of a Function in same file, and choose either Peek or Goto Definition, it works correctly.

**Expected Behavior**: 
1. Expect to see Form Designer
2. Expect to be taken to Peek or Definition of Function.

**Actual Behavior**:
1. Error: 'The designer could not be shown for this file because none of the classes within it can be designed'
2. Error: 'Cannot navigate to the symbol under the caret'

Steps taken:
The project compiles in both versions of VS.
I can close VS2019 and open VS2017 and the same project still works correctly.
I have uninstalled VS2019 and installed VS2019. No change 
I have uninstalled VS2019 and VS2017, then installed VS2017 and VS2019. No change
I have tried each of the following, one at a time: cleaned solution, deleted '.vs' folder, cleared symbols cache, checked NuGet packages are current, checked VS2019 is current, and even removed extra '<Import Project' lines, from *.vbproj file, as mentioned in other troubleshooting suggestions. No change.

**Comment by jasonmalinowski** [comment] 2020-02-05 19:18
@chatteberg: in your Visual Studio 2019 instance, can you follow these steps?

https://github.com/dotnet/roslyn/blob/master/docs/wiki/Diagnosing-Project-System-Build-Errors.md#how-do-i-get-log-files-to-diagnose-what-is-happening-in-visual-studio-2019

This will get you some logs which you can share with us. The logs will contain some potentially private information like source file paths or names of some of your types in your projects. To share that I'd recommend you place them in a cloud storage location of your choosing and privately email me the link to them. My Microsoft email address is on my GitHub profile page.

**Comment by jasonmalinowski** [comment] 2020-02-05 20:19
The other option too for submitting the attachments is to open a ticket at https://developercommunity.visualstudio.com/. Add the link to the ticket here so we can link them up.

**Comment by chatteberg** [comment] 2020-02-06 17:33
https://developercommunity.visualstudio.com/content/problem/909735/goto-definition-is-not-working.html

**Comment by jasonmalinowski** [comment] 2020-03-26 19:19
I'm going to close this bug here in favor of the feedback ticket, which I've now marked as a duplicate of another issue the project system team is looking at. It looks like the design time builds are succeeding but the Workspace isn't being populated.

**Closed by jasonmalinowski** 2020-03-26 19:19 UTC
Labels: Area-IDE, Bug, IDE-Navigation
