### ISSUE TITLE
CodeFix does not fix all occurrences

### ISSUE THREAD

**Issue by vbspoony** [dotnet/roslyn#2872] opened 2015-05-18 21:06 UTC
A VB CodeFix I wrote works OK, when its suppose to fix only one occurrence. However, it gives the option to fix all occurences, and that does not work. Instead, when you have several classes when a potential fix can be applied, it fixes only one occurrence per class.

A repro can be found here:

http://1drv.ms/1GjUH50

**Comment by mavasani** [comment] 2015-05-19 09:02
@vbspoony The behavior you described is by design. The well known BatchFixer is designed to work for simple fixers where individual code fixes coming from different diagnostics don't overlap in eventual text spans. It basically invokes your code fixer for each diagnostic of the same kind as the original trigger diagnostic, then tries to merge all the fixed documents. If conflicts are detected between the results, then it drops the conflicting code fix on the floor.

 The fixer that you have implemented is inserting a new property declaration node into the type for a given unused field in a type. So, if you had `n` unused fields, a fix for each of these would try to add a new property declaration at the end of this type. When the batch fixer tries to merge these documents, it sees that the text spans of added property in all the fixed documents overlap, so it ends up picking just the first one.

Our team had initially also talked about implementing a sequential fixer (as opposed to the current parallel batch fixer), which would apply one fix at a time and then do a "find and fix" iteratively on your fix all scope. We voted out on this approach due to multiple reasons:

1. Performance: Iterative approach would be extremely slow as you would need to re-compute all the diagnostics in newer solution after applying each fix.
2. Functionality: How would you handle cases where original subsequent fixes might have spans overlapping a prior fix in the chain? How can you convey about such conflicts to the user, who only knows about his original code snapshot?

Batch approach is more performant and likely lead to correct results for most fixers, which do apply just a local fix and hence have an easy merge. For anything more complicated, you should implement your own FixAllProvider.

I am resolving this as by design. I have opened #2902 as a follow up documentation work item on this.

**Closed** 2015-05-19 09:03 UTC
Labels: Area-Analyzers, Bug
