### ISSUE TITLE
UI delay after solution load when registering workspace

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#23449] opened 2017-11-28 23:38 UTC
**Version Used**: Multiple versions

PerfWatson is reporting a frequent UI delay occurring after solution load. The blamed cause is `RegisterWorkspaceHostAsync`:

https://github.com/dotnet/roslyn/blob/7a92f356512e23eeaba5743012df7b68a4619d1f/src/VisualStudio/Core/Def/Implementation/Remote/ServiceHubRemoteHostClient.cs#L140

This method ends up invoking the following asynchronous method, and then blocking the UI thread waiting for a result:

https://github.com/dotnet/roslyn/blob/7f81cfd311d26c810669b25c91e38f3334612a1b/src/VisualStudio/Core/Def/Implementation/Remote/ServiceHubRemoteHostClient.WorkspaceHost.cs#L60-L62

**Comment by sharwell** [comment] 2017-11-28 23:39
@CyrusNajmabadi This is the next highest priority issue if you were looking for something to make a big impact.

**Comment by CyrusNajmabadi** [comment] 2017-11-29 00:01
Sorry, i have no clue on how to make this better (without asyncifying a lot of the core workspace layers).  I think @jasonmalinowski had some ideas on what to do here.  Good luck! :) 

--

Note: another option might be to make the above fire-and-forget, or to allow it to happen later during a real async portion of the workspace.  However, IIRC, that would take non-trivial work to support on the Remote side as it will be in an intiially incorrect state for some amount of time, which can affect things.  For example, if the primary-solution issn't properly registered, then that impacts the persistence service (and possibly other services)..  This could be fixed after hte fact on the remote side, but it's also non trivial.

I think this will take some discussion between remote (@heejaechang) and workspace (you and @jasonmalinowski  probably).

--

Of course, i could be wrong, and maybe there's a super simple way to fix this.  If so, great! :)

**Comment by jasonmalinowski** [comment] 2017-11-29 00:15
It turns out that the remote thing never actually cared about the results of computing the state -- it was just using this as a way to get an event which could have been done much more cheaply.

In either case, this bug is a dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/527587 which is assigned to me. This code is all getting burned down as a part of the project system interaction cleanup, so at this point we weren't going to do one-off engineering for it.

**Comment by CyrusNajmabadi** [comment] 2017-11-29 00:21
> This code is all getting burned down as a part of the project system interaction cleanup

:fire: 🕺

**Comment by jasonmalinowski** [comment] 2017-11-29 00:22
(note, made previous post that wasn't entirely correct.)

There's no reason to block VS for this -- fire it off asynchronously, and block other requests for a remote solution on it. There you have the proper async hooks.

Note that the remote workspace isn't actually using the host stuff to get workspace data -- it's just using this as an overly expensive way to be told what the solution directory is. I'm burning this code down as a part of my work which is why a partial dupe of this is in the DevDiv repo assigned to me. But what might survive there is a simple "here's a new solution path" event that this still needs to remote over.

**Comment by CyrusNajmabadi** [comment] 2017-11-29 00:23
> fire it off asynchronously

i'm concerned that could lead to a race condition on the remote side.  We fire htis off asynchronously, then fire off other stuff that then gets processed before this, but which needs the directory to be set.

**Comment by Pilchie** [comment] 2017-11-29 01:10
I think @jasonmalinowski's idea is that you save the task for this, and then everywhere you are going to make a request to the other process you first `await` the task for this to make sure it's done before starting the next request.

NOTE: also switch to `ValueTask` so that the common case of it being done doesn't need to allocate?

**Comment by heejaechang** [comment] 2017-11-29 01:34
problem is that VS has info on where .vs folder is. and we use workspace host to send that info to remote side. I think we can delay it if possible, but VS also can change that path to different one for same solution, when that happen we must tell remote side synchronously, otherwise, we will still have a lock on a file in that path such as SQLite db file, and .vs path change will fail.

**Comment by Pilchie** [comment] 2017-11-29 01:41
@heejaechang - sure, so hold onto the task and synchronously wait for it in the *rare* case of a directory change, instead of the common case of solution load.

**Comment by heejaechang** [comment] 2017-11-29 01:43
that was my workaround, but it is workaround since.. when someone need to create things like SQLite file, it needs to know where to create it. and if that info is not there yet, we need to decide what to do...

**Comment by Pilchie** [comment] 2017-11-29 01:45
Block on the task *then*, but not early in solution load.

**Comment by heejaechang** [comment] 2017-11-29 01:48
my thinking on workaround was, holding onto the task (solution add). and on every remote host request, I make sure it is await on that task first and then let people call remote side. and leave folder name change as synchronous like we are now.

..

this was a bit nasty change since task are leaked multiple places, moving this to BG and leave it synchronous as it was was cleaner.

**Comment by CyrusNajmabadi** [comment] 2022-10-29 00:13
These codepaths are gone now :)

**Closed by CyrusNajmabadi** 2022-10-29 00:13 UTC
Labels: Tenet-Performance, Area-Performance
