### ISSUE TITLE
Intermittent failure in CSharpRazor.VerifyCompletionList

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12881] opened 2016-08-02 21:19 UTC
See https://github.com/dotnet/roslyn/issues/12320#issuecomment-237044742

Scenario: Verify Completion list in Razor syntax
 Executing action [8/2/2016 7:08:34 PM] OpenFile
 DEBUG: executed DTE command File.OpenFile.
 DEBUG: start polling for code window
 DEBUG: polling complete
 Executing action [8/2/2016 7:08:37 PM] PlaceCursor
 Executing action [8/2/2016 7:08:37 PM] SendKeys
 Executing action [8/2/2016 7:08:42 PM] WebUtilities
 Executing action [8/2/2016 7:08:42 PM] WaitForWorkspace
 Executing action [8/2/2016 7:08:42 PM] PlaceCursor
 Executing action [8/2/2016 7:08:43 PM] SendKeys
 Executing action [8/2/2016 7:08:44 PM] VerifyCompletionList

System.Exception: The following expected item(s) not found:
 DateTime

**Comment by Pilchie** [comment] 2016-11-02 22:28
Dupe of #12320

**Closed by Pilchie** 2016-11-02 22:28 UTC
Labels: Area-IDE, Flaky, Test
