### ISSUE TITLE
VS crashes upon selecting output in interactive window

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#5247] opened 2015-09-15 18:41 UTC
The crash can be reproduced by submitting the following line of code in C# interactive window and selecting the entire line of output

```
System.Console.Write(" ");
```

Selecting output with a newline at the end (e.g. `System.Console.Write(" \n");`) will not crash.

![snip_20150915113942](https://cloud.githubusercontent.com/assets/788783/9886315/7a0fdb78-5b9e-11e5-99c6-659b246e7599.png)

**Comment by Pilchie** [comment] 2015-09-21 16:42
Is this the Inert buffer issue that you were looking at the other day.

**Comment by rchande** [comment] 2015-09-21 16:43
@amcasey Is this a dupe of the bug you were looking at last week?

**Comment by amcasey** [comment] 2015-09-21 16:50
Yes, this should be suppressed by https://github.com/dotnet/roslyn/commit/6e515e6ee4a74ba398a7311c58b08e99d7a41b8d.

**Comment by amcasey** [comment] 2015-09-21 16:51
@genlu Can you please verify that this no longer repros (and add the Verified label if it does not)?

**Closed by amcasey** 2015-09-21 16:50 UTC
Labels: Area-IDE, Bug
