### ISSUE TITLE
C# xml "see cref" incorrectly resolves to internal type (or fails to resolve)

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#41925] opened 2020-02-25 04:11 UTC
**Version Used**: 16.6.0 Preview 1.0 (29823.26.master)

**Steps to Reproduce**:

1. Create a solution with three projects. 
1. Two libraries define the same type, but one is internal while the other is public.
2. The third project references both of the other libraries, and references the (public) type both within a method body and in its xml doc comment.

See minimal repro: [RoslynInternalRepro.zip](https://github.com/dotnet/roslyn/files/4248029/RoslynInternalRepro.zip)

**Expected Behavior**:

No compile errors or warnings.
Go to Definition on either reference to the type defined in both referenced projects should always jump to the *public* type, since that's the one we have visibility to.

**Actual Behavior**:

In the minimal repro, Go To Definition on the xml doc comment's cref jumps to the *internal* type.

In the original repro solution (in the VS repo), it wouldn't even compile. It complained about the cref, even though the method body itself had no problem referencing the right one:

> error CS0419: Ambiguous reference in cref attribute: 'VsTaskLibraryHelper'. Assuming 'VsTaskLibraryHelper', but could have also matched other overloads including 'VsTaskLibraryHelper'.

![badGTD gif](https://user-images.githubusercontent.com/3548/75214362-7e840880-574a-11ea-853f-78ef4aafd7fe.gif)

**Comment by sharwell** [comment] 2020-02-25 16:47
Duplicate of #4033

**Closed by sharwell** 2020-02-25 16:47 UTC
