### ISSUE TITLE
Please allow class contain memory of other class or fixed size array

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#2097] opened 2015-04-18 14:07 UTC
(I have proposed this idea in coreclr repository, but they say I should propose it here. You can see: https://github.com/dotnet/coreclr/issues/735#issuecomment-94121406)
Please allow class contain memory of other class or fixed size array. Thus, total object number can be less, and GC pressure can be lower, even accessing class fields can be faster because they can be directly located by accessing memory only once, not twice or more.
The class or array included in other class would act as struct, and can't be referenced.
For example, CLR should allow users to define class like this:
class A
{
class B { int x; char c; };
struct B b; // for example, use keyword "struct" to force class B to act as struct
B b0; // a reference to class B
B b1[10]; // reference array, the array itself is stored in class A, but b1[0]~b1[9] are only reference
struct B b2[10]; //b2[0]~b2[9] are not reference, they store all fields of class B
B[] b3; //a reference to a referencearray
struct B[] b4; //a reference to an array which stores values directly
int y[20]; //instead of "unsafe fixed int y[20]", when access "y", the index should be checked, so there is no necessary to use the keyword "unsafe"
int[] z; //normal array
};

**Comment by ygc369** [comment] 2015-04-18 14:07
![mem](https://cloud.githubusercontent.com/assets/11640479/7215745/5655ff20-e617-11e4-8010-2c7202017d9f.png)

**Comment by HaloFour** [comment] 2015-04-18 19:23
Sounds largely like a dupe of #126:  [Proposal: Fixed-size buffers enhancements](https://github.com/dotnet/roslyn/issues/126)

**Comment by ygc369** [comment] 2015-10-16 07:11
any progress?

**Comment by ygc369** [comment] 2015-10-16 07:36
@HaloFour 
Not same as https://github.com/dotnet/roslyn/issues/126, this one is more ambitious.
C# language should have the ability to use class as struct or use struct as class.

**Comment by HaloFour** [comment] 2015-10-16 12:43
@ygc369

I'm not aware of any CLR functionality that would allow you to allocate a normal class on the stack or within the memory of another class.  C++/CLI fakes it by still allocating the classes on the heap and using copy constructors.

**Comment by monoman** [comment] 2015-10-16 13:02
An experiment on Stack Allocation of classes can be found here:
http://xoofx.com/blog/2015/10/08/stackalloc-for-class-with-roslyn-and-coreclr/


Rafael Teixeira
O..:.)oooo

**Comment by gafter** [comment] 2017-03-20 19:47
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Closed by gafter** 2017-03-20 19:47 UTC
Labels: Area-Language Design, Discussion
