### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p3 on PR #8038

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8051] opened 2016-01-20 18:58 UTC
PR: [#8038](https://github.com/dotnet/roslyn/pull/8038) *Ensure that we only reduce extension methods from the same language.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/189/

**1 Test Failures:**
CSharpWinForms.Change control property in code

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpWinForms.xml

**Comment by brettfo** [comment] 2016-02-03 21:12
Dupe of #7643.

**Closed by brettfo** 2016-02-03 21:12 UTC
Labels: Area-IDE, Bug, Test, Urgency-Soon
