### ISSUE TITLE
Parameter used in XML literal reported as unused

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33898] opened 2019-03-06 14:45 UTC
> @mavasani This parameter is incorrectly reported as unused.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/33028#discussion_r262971002_

**Comment by mavasani** [comment] 2019-03-06 15:05
Dupe of https://github.com/dotnet/roslyn/issues/33142

**Closed by mavasani** 2019-03-06 15:05 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle
