### ISSUE TITLE
NullReferenceException in ReplaceMethodWithPropertyCodeRefactoringProvider

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#21934] opened 2017-09-06 11:36 UTC
**Version Used**: 15.3.3

**Steps to Reproduce**:

1. Open System.Collections.Immutable.sln from dotnet/corefx@06b1365d9881ed26a921490d7edd2d4e4de35565
2. Open ImmutableList_1.Node.cs
3. Add the following code before the declaration for `Node`

    ```csharp
    internal abstract class Node2 : IReadOnlyList<T>
    {
        public abstract T this[int index] { get; }

        public abstract int Count { get; }

        IEnumerator<T> IEnumerable<T>.GetEnumerator() => throw new NotImplementedException();

        IEnumerator IEnumerable.GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }

    internal sealed class Index
    {
    }

    internal sealed class Leaf
    {

    }
    ```

4. Place the caret at the end of the line containing `IEnumerable.GetEnumerator()`

5. Press <kbd>Ctrl</kbd>+<kbd>.</kbd>

**Expected Behavior**:

No error report.

**Actual Behavior**:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.UpdateReferencesInDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.UpdateReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.ReplaceMethodsWithProperty(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by zaytsev-victor** [comment] 2017-09-07 05:22
I can't reproduce the issue. But when I use this refactoring on ```IEnumerable.GetEnumerator()``` in ```Node2``` class it also replaces ```IEnumerable.GetEnumerator()``` method in ```Node``` class.

**Comment by sharwell** [comment] 2017-09-07 10:57
@zaytsev-victor When you open the file in step 1, does the first dropdown bar at the top say "System.Collections.Immutable" or "Miscellaneous Files"?

**Comment by zaytsev-victor** [comment] 2017-09-07 11:33
@sharwell, it is "Miscellaneous Files"

**Comment by zaytsev-victor** [comment] 2017-09-07 11:36
@sharwell, regarding to this refactoring I think that it should not be available if we can't change interface (3rd party assembly, NuGet package, etc). And probably for implementation of public interface (but it should be available inside the interface declaration). What do you think?

**Comment by sharwell** [comment] 2017-09-07 11:36
I was able to fix that by running **managed-build.cmd** in the project root, but only after making the following change:

```diff
diff --git a/external/test-runtime/XUnit.Runtime.depproj b/external/test-runtime/XUnit.Runtime.depproj
index ad99709224..421a8c485b 100644
--- a/external/test-runtime/XUnit.Runtime.depproj
+++ b/external/test-runtime/XUnit.Runtime.depproj
@@ -26,6 +26,12 @@
     <PackageReference Include="Microsoft.xunit.netcore.extensions">
       <Version>$(XunitNetcoreExtensionsVersion)</Version>
     </PackageReference>
+    <PackageReference Include="System.Linq.Expressions">
+      <Version>4.3.0</Version>
+    </PackageReference>
+    <PackageReference Include="System.Text.RegularExpressions">
+      <Version>4.3.0</Version>
+    </PackageReference>
     <PackageReference Include="xunit.performance.api">
       <Version>$(XunitPerfAnalysisPackageVersion)</Version>
     </PackageReference>
```

@stephentoub Is something broken right now or is it always this hard to open a project from corefx?

**Comment by stephentoub** [comment] 2017-09-07 11:40
> Is something broken right now or is it always this hard to open a project from corefx?

In general with corefx you need to do a build.cmd/build.sh from the root before you do any work in the repo. But there shouldn't be anything more you need to do than that. cc: @weshaggard

**Comment by sharwell** [comment] 2017-09-07 11:47
> regarding to this refactoring I think that it should not be available if we can't change interface 

The original decision in #14991 was to to not make this restriction, but I think it makes sense to revisit it. If the method overrides or implements a method defined in metadata it seems totally reasonable to suppress this refactoring. Looping in @dotnet/roslyn-ide for the discussion.

With that said, I wouldn't make any change to this aspect unless all of the following are accounted for:

1. It needs to behave uniformly for "Convert method to property" and "Convert property to method"
1. It *probably* needs to behave uniformly for C# and VB
1. It needs to be tested

> In general with corefx you need to do a build.cmd/build.sh from the root before you do any work in the repo.

I'm using **managed-build.cmd** to avoid the cmake dependency which is not automatically acquired. **build.cmd** is even worse for getting started than **managed-build.cmd**, because in addition to the NuGet-related build failures of the latter you have to modify the system path and whatnot to provide cmake.

**Comment by CyrusNajmabadi** [comment] 2023-02-08 18:32
Fixed with https://github.com/dotnet/roslyn/pull/57891.

**Closed by CyrusNajmabadi** 2023-02-08 18:32 UTC
Labels: Bug, help wanted, Area-IDE
