### ISSUE TITLE
Missing nullability warning for spreads of maybe-null collections

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#74667] opened 2024-08-06 21:59 UTC
**Version Used**: 17.11 preview 6

There should be a warning "CS8602 Dereference of a possibly null reference" in the following example, but there is not:

```cs
List<int>? maybeNull = null;
List<int> clone = [.. maybeNull];
```

When this code runs, it throws NullReferenceException.

In both <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions#known-length-translation> and <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions#unknown-length-translation>, the translation uses `foreach` over the expression being spread, which would equivalently throw:

```cs
foreach (var _ in maybeNull) // Both warns and throws
```

**Comment by jaredpar** [comment] 2024-08-08 12:38
This is effectively a dupe of #68786

**Closed by jaredpar** 2024-08-08 12:38 UTC
Labels: Resolution-Duplicate, Area-Compilers, New Language Feature - Nullable Reference Types, untriaged, New Feature - Collection Expressions
