### ISSUE TITLE
[Proposal] Scoped variable (With keyword)

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#3109] opened 2015-05-27 05:31 UTC
Sometimes I need to use some object in two lines, but I don't want to pollute scope.
Example
```
IEnumerable<IModel> models = <...>;
View view = new View();
view.Position = new Point(models.First().Position.X, models.First().Position.Y / 2);
```
I'd like to write
```
IEnumerable<IModel> models = <...>;
View view = new View();
with (var model = models.First())
{
    view.Position = new Point(model.Position.X, model.Position.Y / 2);
}
```

**Comment by Joe4evr** [comment] 2015-05-27 06:28
Dupe of #951.

**Comment by erik-kallen** [comment] 2015-05-27 07:02
You can do that today

    IEnumerable<IModel> models = <...>;
    View view = new View();
    {
        var model = models.First();
        view.Position = new Point(model.Position.X, model.Position.Y / 2);
    }

**Comment by KalitaAlexey** [comment] 2015-05-27 08:57
@erik-kallen I know. But this may be misunderstanding. Someone may see
```
View view = new View()
{
    var model = models.First();
    view.Position = new Point(model.Position.X, model.Position.Y / 2);
}
```

**Comment by HaloFour** [comment] 2015-05-27 12:24
This proposal doesn't add anything new to the language.  Yet another method of introducing scope is extraneous, especially since absolutely nothing special is happening or being done with the `model` variable.

**Closed** 2015-05-27 13:46 UTC
