### ISSUE TITLE
AsyncMethodBuilder.Start called with a different this reference than AsyncMethodBuilder.Task

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#41222] opened 2020-01-26 02:32 UTC
**Version Used**: 
Visual Studio 16.4.2

**Steps to Reproduce**:

I came across this when trying to leverage the capability to build custom async method return types.

I wanted to build a type similar to Task<T>, but which would be resiliant to StackOverflow. To do this, I wanted to do more inside the methodbuilder's `Start()` method rather than just always calling `stateMachine.MoveNext()`. Here's a minimal example which reproduces the behavior I found.

```C#
class Program
{
    public static void Main(string[] args)
    {
        Foo(10).GetAwaiter().GetResult(); // throws "no state set"
            
        async MyTask<string> Foo(int n) =>
                n <= 0 ? "bar" : await Foo(n - 1);
    }
}

[AsyncMethodBuilder(typeof(MyTaskMethodBuilder<>))]
    public readonly struct MyTask<TResult> : INotifyCompletion
    {
        internal MyTask(object state) { }

        public bool IsCompleted => false;

        public MyTask<TResult> GetAwaiter() => this;

        public TResult GetResult() => throw new NotImplementedException();

        public void OnCompleted(Action continuation) => throw new NotImplementedException();
    }

    public struct MyTaskMethodBuilder<TResult>
    {
        private object _state;

        public static MyTaskMethodBuilder<TResult> Create() => default;

        public void Start<TStateMachine>(ref TStateMachine stateMachine)
            where TStateMachine : IAsyncStateMachine
        {
            // doesn't stick because a copy of the builder is used for accessing the Task property
            this._state = new State<TStateMachine>();
        }

        public void SetStateMachine(IAsyncStateMachine stateMachine) { }

        public void SetException(Exception exception) => throw new NotImplementedException();

        public void SetResult(TResult result) => throw new NotImplementedException();

        public void AwaitOnCompleted<TAwaiter, TStateMachine>(
            ref TAwaiter awaiter,
            ref TStateMachine stateMachine)
            where TAwaiter : INotifyCompletion
            where TStateMachine : IAsyncStateMachine => throw new NotImplementedException();

        public void AwaitUnsafeOnCompleted<TAwaiter, TStateMachine>(
            ref TAwaiter awaiter,
            ref TStateMachine stateMachine)
            where TAwaiter : ICriticalNotifyCompletion
            where TStateMachine : IAsyncStateMachine => throw new NotImplementedException();

        public MyTask<TResult> Task => new MyTask<TResult>(this._state ?? throw new InvalidOperationException("no state set"));

        internal object ObjectIdForDebugger => this._state ??= new State<IAsyncStateMachine>();

        private class State<TStateMachine>
            where TStateMachine : IAsyncStateMachine
        {
        }
    }
```

**Expected Behavior**:
With the builder being a mutable struct, I would expect that the generated async code would ensure that each call made into the builder is done in such a way that ensures that the builder state can flow between calls. This works between `AwaitOnCompleted` and `Task`, for example, but not between `Start` and `Task`.

**Actual Behavior**:
Setting instance fields of the builder in `Start()` does not carry over to `Task`.

**Comment by benaadams** [comment] 2020-01-26 03:20
I'm not great at il, but...
```asm
; method Program::'<Main>g__Foo|0_0'
ldloca.s 0
ldarg.0
stfld int32 Program/'<<Main>g__Foo|0_0>d'::n
ldloca.s 0
call valuetype MyTaskMethodBuilder`1<!0> valuetype MyTaskMethodBuilder`1<string>::Create()
stfld valuetype MyTaskMethodBuilder`1<string> Program/'<<Main>g__Foo|0_0>d'::'<>t__builder'
ldloca.s 0
ldc.i4.m1
stfld int32 Program/'<<Main>g__Foo|0_0>d'::'<>1__state'
ldloc.0
ldfld valuetype MyTaskMethodBuilder`1<string> Program/'<<Main>g__Foo|0_0>d'::'<>t__builder'
stloc.1
ldloca.s 1
ldloca.s 0
call instance void valuetype MyTaskMethodBuilder`1<string>::Start<valuetype Program/'<<Main>g__Foo|0_0>d'>(!!0&)
ldloca.s 0
ldflda valuetype MyTaskMethodBuilder`1<string> Program/'<<Main>g__Foo|0_0>d'::'<>t__builder'
call instance valuetype MyTask`1<!0> valuetype MyTaskMethodBuilder`1<string>::get_Task()
ret
```
Looks like its calling `::Start` on a local copy
```
ldfld valuetype MyTaskMethodBuilder`1<string> Program/'<<Main>g__Foo|0_0>d'::'<>t__builder'
```
Rather than the field (by loading address)? e.g. what happens for the `get_Task`
```
ldflda valuetype MyTaskMethodBuilder`1<string> Program/'<<Main>g__Foo|0_0>d'::'<>t__builder'
call instance ... ::get_Task()
```

/cc @stephentoub

**Comment by benaadams** [comment] 2020-01-26 03:29
Note: it should be calling it on the field; not a copy

**Comment by benaadams** [comment] 2020-01-28 04:17
As C# the issue is easier to see
```csharp
internal static MyTask<string> <Main>g__Foo|0_0(int n)
{
    <<Main>g__Foo|0_0>d stateMachine = default(<<Main>g__Foo|0_0>d);
    stateMachine.n = n;
    stateMachine.<>t__builder = MyTaskMethodBuilder<string>.Create();
    stateMachine.<>1__state = -1;

    // Create local copy of struct
    MyTaskMethodBuilder<string> <>t__builder = stateMachine.<>t__builder;

    // Call start on copy
    <>t__builder.Start(ref stateMachine);

    // return Task from struct field
    return stateMachine.<>t__builder.Task;
}
```

**Comment by sharwell** [comment] 2020-01-28 05:14
Duplicate of #20606

**Closed by sharwell** 2020-01-28 05:14 UTC

**Comment by benaadams** [comment] 2020-01-28 07:25
Addressed by https://github.com/dotnet/roslyn/pull/41253
