### ISSUE TITLE
[Regression] Usages are not highlighted is next character is an operator

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#34108] opened 2019-03-14 03:44 UTC
**Version Used**: 
Version 16.0.0 Preview 4.2 [28711.60.d16.0]

**Steps to Reproduce**:

``` C#
        static void Main(string[] args)
        {
            int count = 0;

            count++;    // 1
            count--;    // 2
            count&= 1;  // 3

            Console.WriteLine(count);
        }
```

Two ways to reproduce this, one is a regression from 15.9 and one is not.

1. Give above, put caret inside `count` in line marked with 1, 2 or 3 and then double-click `count` in same line [Regression]

-or-

2. Double-click `count` in the line marked with 1, 2 or 3 [No regression - repros in 15.9]

``` C#
        static void Main(string[] args)
        {
            int count = 0;

            count++;    // 1
            count--;    // 2
            count&= 1;  // 3

            Console.WriteLine(count);
        }
```

**Expected Behavior**:
All usages of count to be highlighted

![image](https://user-images.githubusercontent.com/1103906/54329734-09b5dc80-4667-11e9-9c55-d0fb6246f871.png)

**Actual Behavior**:
No usages are highlighted

![image](https://user-images.githubusercontent.com/1103906/54329760-310ca980-4667-11e9-8a90-706b4b9ca8f1.png)

**Comment by jinujoseph** [comment] 2019-06-10 17:30
also reported at [link](https://developercommunity.visualstudio.com/content/problem/590958/highlight-references-not-working-when-caret-betwee.html)

**Comment by ryzngard** [comment] 2019-06-10 23:06
Verified this is a regression. It happens for any case where the symbol is touching another bindable/navigable token. `count++`, `count--` show it because they bind to `--` or `++` operands for int.

**Comment by TonyRietwyk** [comment] 2019-11-29 06:02
I'm not sure if this is related, but I am seeing this in C++ when searching for a variable that is a class member.  When I select the line in the find results, the cursor correctly positions at the start of the member variable, but all of the C++ arrow operators (->) are highlighted instead. 
The same occurs when I use the keyboard right arrow to move the cursor over the operator. 
<img width="883" alt="arrow operator highlighted" src="https://user-images.githubusercontent.com/5600947/69847016-fff20900-12c9-11ea-9d03-3fb9a0763847.png">

**Comment by ryzngard** [comment] 2019-12-05 20:55
@TonyRietwyk thanks for the feedback. I don't believe this is related, since the initial problem looks like an error in the roslyn code base which doesn't handle c++. Please file a new issue on https://developercommunity.visualstudio.com/ so that it can get routed correctly.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:39
Closing out as the expected design.

**Closed by CyrusNajmabadi** 2024-11-06 02:39 UTC
Labels: Bug, Area-IDE, Developer Community, Regression, IDE-IntelliSense
