### ISSUE TITLE
After upgrading Roslyn.Diagnostics.Analyzers, randomly get CS8032	

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30890] opened 2018-10-31 23:59 UTC
**Version Used**: 
Version 16.0.0 Preview 1.0 [28231.52.d16.0]

**Steps to Reproduce**:

After upgrading our version of Roslyn.Diagnostics.Analyzers in https://github.com/dotnet/project-system/tree/dev16.0.x, I'm randomly getting the following warnings:

```
Severity	Code	Description	Project	Project Rank	File	Line	Category	Suppression State	Tool
Warning	CS8032	An instance of analyzer Roslyn.Diagnostics.CSharp.Analyzers.CSharpSymbolDeclaredEventAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\roslyn.diagnostics.analyzers\2.6.1-beta1-62702-01\analyzers\dotnet\cs\Roslyn.Diagnostics.CSharp.Analyzers.dll: Could not load file or assembly 'Roslyn.Diagnostics.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Roslyn.Diagnostics.CSharp.Analyzers.CSharpSpecializedEnumerableCreationAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\roslyn.diagnostics.analyzers\2.6.1-beta1-62702-01\analyzers\dotnet\cs\Roslyn.Diagnostics.CSharp.Analyzers.dll: Could not load file or assembly 'Roslyn.Diagnostics.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Roslyn.Diagnostics.CSharp.Analyzers.CSharpDiagnosticDescriptorAccessAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\roslyn.diagnostics.analyzers\2.6.1-beta1-62702-01\analyzers\dotnet\cs\Roslyn.Diagnostics.CSharp.Analyzers.dll: Could not load file or assembly 'Roslyn.Diagnostics.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Roslyn.Diagnostics.CSharp.Analyzers.CSharpCodeActionCreateAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\roslyn.diagnostics.analyzers\2.6.1-beta1-62702-01\analyzers\dotnet\cs\Roslyn.Diagnostics.CSharp.Analyzers.dll: Could not load file or assembly 'Roslyn.Diagnostics.Analyzers, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpReportDiagnosticAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\microsoft.codeanalysis.analyzers\2.6.2-beta2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpRegisterActionAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\microsoft.codeanalysis.analyzers\2.6.2-beta2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\microsoft.codeanalysis.analyzers\2.6.2-beta2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\microsoft.codeanalysis.analyzers\2.6.2-beta2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpUpgradeMSBuildWorkspaceAnalyzer cannot be created from C:\Users\davkean\.nuget\packages\microsoft.codeanalysis.analyzers\2.6.2-beta2\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests	5		1	Roslyn.HostError	Active	
```

I've turned on fusion logging, but I see zero failed binds to these assembly & versions inside devenv and ServiceHub. It's all from a single project and from `Microsoft.CodeAnalysis.Analyzers` and `Roslyn.Diagnostics.Analyzers`.

**Comment by davkean** [comment] 2018-11-01 00:02
I've confirmed that those dlls that are "missing" live alongside the analyzers and have the version they are expecting.

**Comment by davkean** [comment] 2018-11-01 00:03
@mavasani Have you seen above? ^

**Comment by mavasani** [comment] 2018-11-01 00:06
@amcasey Also noticed the same issue yesterday, but I haven't been able to repro yet. Seems the shadow copied assembly has an older version, so older assembly is somehow getting pulled from somewhere.

**Comment by jaredpar** [comment] 2018-11-01 16:19
Are these analyzers the IDE team owns?

**Comment by mavasani** [comment] 2018-11-01 17:19
> Are these analyzers the IDE team owns?

I don't think the issue here is with the analyzers/analyzer package. As @davkean mentioned and @amcasey confirmed, the analyzer package does have the correct versioned analyzer assembly, but the IDE live analysis seems to be loading some older version. @heejaechang do you know if any of the recent IDE changes could cause this all of sudden?

**Comment by mavasani** [comment] 2019-01-11 22:21
Dupe of https://github.com/dotnet/roslyn/issues/32226, which also has a repro that I can reliably reproduce on one of my machines.

**Closed by mavasani** 2019-01-11 22:21 UTC
Labels: Area-IDE, Bug
