### ISSUE TITLE
IActionResult Un-necessary Casting with Ternary Expression

### ISSUE THREAD

**Issue by napalm684** [dotnet/roslyn#21405] opened 2017-08-09 17:57 UTC
**Version Used**:  .Net Core 1.1 with 
Nuget Version: Microsoft.AspNetCore.Mvc v1.1.3

[Reference: 6642 aspnet/Mvc](https://github.com/aspnet/Mvc/issues/6642)

**Steps to Reproduce**:

1. See Code
```
        [HttpPost]
        [Route("{id:int}/notes")]
        public IActionResult CreateNote([FromRoute] int id, [FromBody] Dtos.NoteData note)
        {
            //This works but resharper reports it as an un-necessary cast which is true
            //remove the IActionResult cast on both and the types cannot be implicitly converted?
            //Remove the cast on one (not both) it also works
            return _noteService.CreateNote(id, note) == true
                ? (IActionResult) Ok()
                : (IActionResult) NotFound();

            //This also works without casts, but the if seems verbose and un-necessary
            //var result = _noteService.CreateNote(id, note);

            //if(result == OperationResult.NotFound)
            //    return NotFound();
            //else
            //    return Ok();
        }
```

**Expected Behavior**:
Return is functional without cast

**Actual Behavior**:
Cannot return unless both IActionResults are redundantly cast to IActionResult

**Comment by CyrusNajmabadi** [comment] 2021-12-07 23:57
This is by design as far as i can tell.  In C# in a conditional expression there must be a common type between the two branches.  And the common type must be one of the types of the branches to begin with.   As such, teh following are all fine:

```c#
           return _noteService.CreateNote(id, note) == true
                ? (IActionResult) Ok()
                : (IActionResult) NotFound();
```

Both branches are IActionResult, so the common type is IActionResult.

```c#
           return _noteService.CreateNote(id, note) == true
                ? Ok()
                : (IActionResult) NotFound();
```

`Ok()` is convertible to IActionResult, so the common type is IActionResult, which is the type of teh RHS.  So this is ok. (and the reverse case is the same).

```c#
           return _noteService.CreateNote(id, note) == true
                ? Ok()
                : NotFound();
```

Two disparate types.  Neither of the two are convertible to other side's type.  So this is not legal.  Closing out.  

Note: i had to infer what was going on based on incomplete code above.  If you think this assessment is in error, please supply a repro with a full set of code that demonstrates teh problem (including definitions for Ok and NotFound, etc.

**Closed by CyrusNajmabadi** 2021-12-07 23:57 UTC
Labels: Area-Analyzers
