### ISSUE TITLE
Format on semicolon for expression bodied properties

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3505] opened 2015-06-15 18:31 UTC
I noticed today that expression bodied members don't get formatted the same way as normal expressions.

I think it'd be nice if the formatting were consistent and both formatted properly when semicolons were added.

![image](http://i.gyazo.com/3a00c5b7a24ce2aa11153ca2db38fbf1.gif)

**Comment by JoshVarty** [comment] 2015-06-15 18:53
Upon further review, I've noticed this only affects expression bodied properties, not methods:

![image](http://i.gyazo.com/728dce25a240c6c32f1eb6eb191ef5d9.gif)

**Comment by Pilchie** [comment] 2015-06-15 23:16
Dupe of #2292, which is already fixed for 1.0

**Closed by Pilchie** 2015-06-15 23:16 UTC
Labels: Area-IDE

**Comment by dpoeschl** [comment] 2015-06-16 23:17
Verified this specific repro against yesterday's ```1.0 (stable)``` build.
