### ISSUE TITLE
Default constructors C# 7

### ISSUE THREAD

**Issue by josejmoran** [dotnet/roslyn#9833] opened 2016-03-17 15:10 UTC
**Version Used**: C# 6

**Steps to Reproduce**:

The code below is part of the code we get when we create a project for MVC 5 in ManageController.cs

The code for the controller should be a default controller. All classes that we create should inherit a default controller that initialize all instance variables.

    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    private readonly IEmailSender _emailSender;
    private readonly ISmsSender _smsSender;
    private readonly ILogger _logger;
// The constructor below code will be unnecessary with the implementation of default constructor.
making our classes easier to the eyes and less code to browse over.

    public ManageController(
    UserManager<ApplicationUser> userManager,
    SignInManager<ApplicationUser> signInManager,
    IEmailSender emailSender,
    ISmsSender smsSender,
    ILoggerFactory loggerFactory)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _emailSender = emailSender;
        _smsSender = smsSender;
        _logger = loggerFactory.CreateLogger<ManageController>();
    }

**Comment by RichiCoder1** [comment] 2016-03-17 15:33
If I'm reading this correctly, this sounds like a duplicate of #9517

**Comment by mgravell** [comment] 2016-03-18 09:44
Looks to be a troll having some fun; see all suggested issues: https://github.com/josejmoran

**Comment by marxidad** [comment] 2016-03-25 04:55
I think what is being asked is that a constructor is automatically generated for classes with a parameter for each instance field. 

    class MyController { IService _service; }
    var controller = new MyController(service:svc); // controller._service = svc

**Comment by gafter** [comment] 2016-03-29 19:55
See #10154 for a discussion of records. We will not change the meaning of existing code.

**Closed by gafter** 2016-03-29 19:55 UTC
Labels: Area-Language Design
