### ISSUE TITLE
The classes listed by the C# overrides glyph should be sorted by their depth in the class hierarchy.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58219] opened 2021-12-09 20:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-classes-listed-by-the-C-overrides-g/1590636)._

---
When VS2022's O^ glyph (that appears in the margin next to C# class and overridden function headers) is clicked, it lists Base Types, Overridden members etc. in alphabetical order.  It would be far more useful if they were sorted in order of inheritance instead.  This short cut is so nearly an excellent feature, but each time the list pops up there are wasted seconds where you ask yourself "Now where is the base class in all these? This one? Or maybe this one?" and that repeated delay would be completely avoidable with better sorting.

---
#### Feedback Bot on 11/21/2021, 11:54 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2022-05-13 19:54
Duplicate of #53862

**Closed by sharwell** 2022-05-13 19:54 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community
