### ISSUE TITLE
IdentifierName Node missing symbol info

### ISSUE THREAD

**Issue by pquiring** [dotnet/roslyn#22905] opened 2017-10-29 21:08 UTC
**Version Used**:  2.4.0

**Steps to Reproduce**:

1. compile sample code
2. print SyntaxNode tree

**Expected Behavior**:
IdentifierName node has symbol info

**Actual Behavior**:
In the invocation to setCallback() the IdentifierName SyntaxNode for setCallback has no symbol info making it difficult to analyze code.  The invocation to call() has proper symbol info.

Thanks

```
using System;

namespace test
{
    public delegate void funcptr(int x);

    public class Base {
        funcptr ptr;
        public void setCallback(funcptr ptr) {
            this.ptr = ptr;
        }
        public void call() {
            ptr(1);
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            Base b = new Base();
            b.setCallback((int x) => {Console.WriteLine("x=" + x);});
            b.call();
        }
    }
}

```

**Comment by jcouv** [comment] 2017-11-02 00:52
@pquiring I wasn't able to reproduce the problem. Can you clarify what you mean by "print SyntaxNode tree"?

Here's what I tried:
```C#
        [Fact]
        [WorkItem(22923, "https://github.com/dotnet/roslyn/issues/22923")]
        void GetSymbolInfoOnMethodCall()
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(@"
using System;

public delegate void funcptr(int x);

public class C
{
    public void setCallback(funcptr ptr) { }
    public void M()
    {
        this.setCallback((int x) => {Console.WriteLine(""x = "" + x);});
    }
}");

            var comp = CreateStandardCompilation(tree);
            comp.VerifyDiagnostics();
            var model = comp.GetSemanticModel(tree);
            var root = tree.GetRoot();

            var method = root.DescendantNodes().OfType<InvocationExpressionSyntax>().First().Expression as MemberAccessExpressionSyntax;
            IdentifierNameSyntax setCallbackSyntax = method.Name as IdentifierNameSyntax;
            Assert.Equal("setCallback", setCallbackSyntax.ToString());
            Assert.Equal("void C.setCallback(funcptr ptr)", model.GetSymbolInfo(setCallbackSyntax).Symbol.ToTestDisplayString());

        }
```

**Comment by pquiring** [comment] 2017-11-03 15:09
I use this project to print out the SyntaxNode tree:

github.com/pquiring/CSPrintTree

I'll attach the print out of the program.  In the output I added *BUG* where the problem occurs.

[bug.txt](https://github.com/dotnet/roslyn/files/1441467/bug.txt)

**Comment by jcouv** [comment] 2017-11-03 17:11
There are errors/diagnostics in the code that you're analyzing, which are visible because the nodes near the "*BUG*" marker have `Type.Kind=ErrorType`. Code with errors cannot be successfully be bound, which means that syntax won't successfully be associated with symbols.
You can find out the errors in the code by looking at diagnostics on the compilation.

The behavior you describe still appears by-design, as far as I can tell. I'll go ahead and close the issue.

**Closed by jcouv** 2017-11-03 17:11 UTC
Labels: Area-Compilers, Need More Info, Resolution-Answered

**Comment by pquiring** [comment] 2017-11-04 18:03
The diagnostics say this:
`error CS0103: The name 'Console' does not exist in the current context`
If I add System to the Console call it then says this:
`error CS0234: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)`

In the compiler setup I use the following:

                String lib = typeof(object).Assembly.Location;
                Console.WriteLine("Adding Reference:" + lib);
                compiler = compiler.AddReferences(MetadataReference.CreateFromFile(lib));

to add the corelib.  Why do I still get these errors?  

I've updated the CSPrintTree program to printout the diagnostics.

Thanks.

**Comment by pquiring** [comment] 2017-11-07 12:33
I found the fix, after googling it I ended up at bug # 16846

> https://github.com/dotnet/roslyn/issues/16846#issuecomment-276443112

So I added this code:

```
            var libs = ((String)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")).Split(Path.PathSeparator);
            foreach(var lib in libs) {
                Console.WriteLine("Adding Reference:" + lib);
                compiler = compiler.AddReferences(MetadataReference.CreateFromFile(lib));
            }

```

And it works now!  Please close ticket.

Please update the documentation for Roslyn.  Just adding the dll from typeof(object).Assembly.Location is not enough.
