### ISSUE TITLE
[Test Failure] Compile Error in prtest/win/dbg/unit32 on PR #8083

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8099] opened 2016-01-22 05:30 UTC
PR: [#8083](https://github.com/dotnet/roslyn/pull/8083) *[WIP] readonly locals and parameters* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3059/

**Issue 1: Compile Error**
error CS2007: Unrecognized option: '/publicsign+' [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\Core\Portable\CodeAnalysis.csproj]

**Comment by Pilchie** [comment] 2016-01-22 17:11
Can you find the dup?

**Comment by Pilchie** [comment] 2016-01-22 17:12
Dupe of #8062

**Closed by Pilchie** 2016-01-22 17:12 UTC
Labels: Area-Infrastructure, Bug, Resolution-Duplicate
