### ISSUE TITLE
The type parameters aren't correctly inferred on function pointers

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#50096] opened 2020-12-22 02:25 UTC
**Version Used**: 

VS 16.9 Preview 2

**Steps to Reproduce**:

Type code

```csharp
#nullable enable

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

unsafe
{
    string s = new StringBuilder()
        .AppendRange<int, string>(Enumerable.Range(1, 10), &converter) // Here.
        .ToString();
    
    Console.WriteLine(s);
}

static string converter(int v) => $"{v}, ";

public static class C
{
    public static unsafe StringBuilder AppendRange<TElement, TOther>(
        this StringBuilder @this,
        IEnumerable<TElement?> contentList,
        delegate*<TElement?, TOther?> converter)
    {
        foreach (var content in contentList)
        {
            @this.Append(converter(content)?.ToString() ?? string.Empty);
        }

        return @this;
    }
}
```

The code segment

```csharp
string s = new StringBuilder()
    .AppendRange<int, string>(Enumerable.Range(1, 10), &converter) // Here.
    .ToString();
```

should specify type parameters `<int, string>`.

**Expected Behavior**:

Because of the type parameters can be inferred from function pointers, so we can omit them:

```csharp
string s = new StringBuilder()
    .AppendRange(Enumerable.Range(1, 10), &converter)
    .ToString();
```

**Actual Behavior**:

An compiler error CS0411 raised: Try to specify type parameters.

**Comment by jcouv** [comment] 2020-12-30 18:26
Doesn't repro on latest build ([sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWAChGABAJgEYWAGC59gOgAyAS1wBHANzde7ACxSGzHn34AVOAA8YCxvlxQIAMziMA3owqWZPKBQC8FXHADuFAMowEogOYAhfMKEKIgAFACUFlZR/ACCAA5x1CgAShC43nAAPKIwSNYAfCEAogRgiLRw/KnpcCHseexcYXkAZADGAPa4AG6I8AhhFAD0QxQAEoiVkVGWah0eXunhClHTMgCcIVBhCgC+jCzsAGzWFJ09faE5FN2DdvkUACQARKbdu3nPOooAzDInbAoAGEzGtmH8+Cc9AZjO5PD5/IFgggKPFErgUmkMplVEVyGVcLkKKoAPIwAAWiEKayiFOEtgWCICQUQvGYdKgSBpVj4PxxeLgBJgAH4Hud4ISRLAuQwZlZguRvBB4AAqfn46givKkimIUVnLq9BD9CKyqzmM1ywwdBBwCBtckUELdCAo8WaiiiA2EzVSmCmuWWC2BmbMdnk+mxBJJELnI39WNdCX+4VzRlLQbC4XWfhFMBxGAATx23Ms+yYltDAHY2RyVlZy7sgA===)). I think this was fixed in PR https://github.com/dotnet/roslyn/pull/43041. But that PR pre-dates 16.9p2, so I may be missing something.

@333fred can you confirm and close if appropriate?

**Comment by 333fred** [comment] 2020-12-30 20:28
I cannot reproduce this on VS 16.9 Preview 2 with the code snippet provided, and this project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
```

@SunnieShine, is there anything else special about your environment?

**Comment by 333fred** [comment] 2021-01-04 22:32
@SunnieShine I've been unable to replicate this issue, and am closing it out. If you have more info, please comment and we can reopen.

**Comment by 333fred** [comment] 2021-01-04 22:34
Hmm, actually, the original snippet has the type parameters there, I misread it. I can reproduce it if I modify the snippet.

**Comment by SunnieShine** [comment] 2021-01-05 05:59
@333fred I'm so sorry for late to read your reply. The real problem is that the type parameters can't be omitted.

To be honest, I have the same configuration with yours:

```xml
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>9.0</LangVersion>
</PropertyGroup>
```

Snapshots:

![Correct-case](https://user-images.githubusercontent.com/23616315/103611902-3c2c7a00-4f5e-11eb-869d-45f4ae6c3142.png)

![Wrong-case](https://user-images.githubusercontent.com/23616315/103611908-3f276a80-4f5e-11eb-8f59-f87dd7443c0b.png)

**Comment by 333fred** [comment] 2021-01-05 06:12
As I mentioned, I misread your initial snippet. I have a draft out now that should fix the issue.

**Comment by SunnieShine** [comment] 2021-01-05 06:34
:)

**Comment by 333fred** [comment] 2021-01-29 23:11
Fixed in https://github.com/dotnet/roslyn/pull/50249/

**Closed by 333fred** 2021-01-29 23:11 UTC
Labels: 4 - In Review, Area-Compilers, Feature - Function Pointers
