### ISSUE TITLE
Proposal: Extended Object Initializer 

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5365] opened 2015-09-21 15:26 UTC
Extend object initializer block to support method calls and event subscriptions:

```
var timer = new DispatcherTimer {
    Tick += delegate {},
    Interval = TimeSpan.FromSeconds(1d),
    Start()
};
```

->

```
var timer = new DispatcherTimer();
timer.Tick += delegate {};
timer.Interval = TimeSpan.FromSeconds(1d);
timer.Start();
```

**Comment by paulomorgado** [comment] 2015-09-21 16:34
Event subscription makes sense and would be useful.

But how would you disambiguate `MethodCall()`?

There might be other methods in scope and it would make a lot more sense to call methods not from the object being initialized than the object being initialized.

**Comment by alrz** [comment] 2015-09-21 18:49
@paulomorgado 
>There might be other methods in scope

The scope wouldn't be a problem at all because same goes with properties and they are actually in the initializer block scope, so they belong to the object being initialized.

**Comment by paulomorgado** [comment] 2015-09-21 19:09
@alrz, an asignment has a left and a right side. The method invocation doesn't.

I can have this:

    C Clone() => new C
    {
        Property = Property.
        Method()
    }:

There's no doubt that the new instance is being initialize by seting it's `Property` property with the value of the current object's `Property` property.

At first, it's also obvious what `Method` that is.

But how about this?

    C Clone() => new C
    {
        Property = Method()
    }:

**Comment by alrz** [comment] 2015-09-21 21:47
@paulomorgado since there is no dot syntax for initializers (as in VB `New AnObject {.Property = value}`) that would be limited to void-returning methods only, or you should ignore the return value.

**Comment by dsaf** [comment] 2015-09-22 08:17
Sometimes I want to be able to write this:

```csharp
var car = carFactory.CreateCar()
{
    Brand = "Ferrari",
    Model = "Enzo"
};
```

...but not sure if this would be a good thing.

**Comment by alrz** [comment] 2015-09-22 08:53
@dsaf this is already proposed in #5172:
```
var car = carFactor.CreateCar() with
{
    Brand = "Ferrari",
    Model = "Enzo"
};
```

**Comment by dsaf** [comment] 2015-09-22 09:04
@alrz Yes, the fact that it creates a new instance is a no go for me, even if I don't care about the performance. Besides it's not yet extended to types other than records.

**Comment by alrz** [comment] 2015-09-22 09:31
@dsaf Of course, with-expression has a different intention and plays nice with immutable objects, on the other hand, the scenario here is kind of "re-initialization" for mutable objects. It could be done with a `With...End With`-like *expression* e.g. `var car = with carFactory.CreateCar() { ... }`.

**Comment by dsaf** [comment] 2015-09-22 09:50
@alrz That makes complete sense.

**Comment by gafter** [comment] 2015-11-21 00:29
This issue has two separate proposals. I think we are likely to be interested in event subscription. I think we are unlikely to be interested in the method call.

**Comment by firda-cze** [comment] 2016-01-24 00:29
**Event subscription** inside initializer is what brought me here (as I was going to suggest it and found this).
There already is `Add` or `AddRange` call for readonly lists (get-only property) and events are actually delegate (handler) lists.

**Calling method** inside the initializer list really sounds like `with` and either only one method will usually be called or it can be chained with fluent syntax in most situations I can think of. So, it won't be so big advantage. But still, sounds like doable - methods after `{` or `,` reference the created class, methods after `=` do not (as properties cannot be assigned from another property of the created object ...or can they?)

What about **nested initialization**? Now I am thinking about `SplitContainer` with two properties - `Panel1` and `Panel2`. Why not adding controls directly like this?

    new SplitContainer {
        Panel1.Controls = { ... }, // first version
        Panel2 { // second version
            Controls = { .... } ....

the same could of course be done by adding properties `Panel1Controls` and `Panel2Controls` to the `SplitContainer` ... but on the other hand, `Panel1.Collapsed` could disapear. Don't know what would that mean for the designer, but it should be doable as well.

**Comment by alrz** [comment] 2016-01-24 02:11
@firda-cze nested initialization like that doesn't make sense, you have to create the nested object and initialize it in turn, 
```cs
new SplitContainer {
    Panel1 = new Panel { Controls = { ... } }
}
```
which is currently possible.

**Comment by firda-cze** [comment] 2016-01-25 07:28
@alrz Panel1 is get-only (readonly) property, it cannot be assigned to. Same apply to event subscription and list initialization (both are actually get-only and manipulated by other means in initializer - either by `Add` or `Combine`)

But I agree that it could produce a mess and should rather be handled by designer of the class (to redirect whatever property to inner classes to allow easy initialization)

**Comment by nathanielcook** [comment] 2016-01-28 14:59
I'm not sure if it is appropriate for me to "+1" in this manner, but I just wanted to voice my support for event subscription in the object initializer. This is something I've wanted in C# for quite some time.

**Closed** 2017-03-21 09:30 UTC
Labels: 1 - Planning, Area-Language Design
