### ISSUE TITLE
Suggestion: this class type

### ISSUE THREAD

**Issue by umanduz** [dotnet/roslyn#13397] opened 2016-08-26 06:44 UTC
Is it possible to add special keyword to return this class type? We need if we use inherited class.

```
public class A
{
	public this Method1 ()
	{
		// do something
		return this;
	}
}

public class B : A
{
	public B Method2 () {}
}

var b = new B ();
b.Method1().Method2();
```

**Comment by alrz** [comment] 2016-08-26 07:59
Duplicate of #311

**Comment by jcouv** [comment] 2016-09-01 20:56
Closing as duplicate.

**Closed by jcouv** 2016-09-01 20:56 UTC
Labels: Area-Language Design
