### ISSUE TITLE
Right click variable context menu needs "Find all assignments"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38267] opened 2019-08-24 00:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/409321/right-click-variable-context-menu-needs-find-all-a.html)._

---
<p>Currently when you right click a variable you can choose &quot;go to definition&quot; which is handy and &quot;find all references&quot; which can have hundreds of results. </p><p>It would make it much easier if you changed &quot;Find all References&quot; to only show where the variable value is accessed </p><pre>Console.WriteLine(myvariable);</pre><p>And then added a new item &quot;Find all assignments&quot; which shows where the variable is assigned </p><pre>myvariable = &quot;hello&quot;;
</pre>

---
#### Jane Wu [MSFT] on 12/16/2018, 05:52 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment] 2019-08-24 00:31
Find-All-References will let you sort/filter by read/writes.  So that should suffice for this use case.

**Comment by alexfevery** [comment] 2019-08-24 00:51
There are 3 major classifications of variable operations. Declaration, assignment, and reference. It is illogical to have a separate menu item for one, and group the two others together. Filtering should only be reserved for special rarely used situations otherwise it unnecessarily complicates VS

**Comment by CyrusNajmabadi** [comment] 2019-08-24 01:28
Adding a new concept to represent what is already possible in VS today seems unnecessarily complicated.  

> Filtering should only be reserved for special rarely used situations

Why?  It's a simple and easy to do.  It means not having to define new features and new UI just to do what can already be done.

**Comment by hyagli** [comment] 2019-08-26 08:26
The current usage where we can use the filter in Find-All-References is too obscure. I've been using Visual Studio for 15 years and I've learned it today by reading this thread.

**Comment by CyrusNajmabadi** [comment] 2019-08-26 08:38
Teach a man to fish. 

--

We genuinely stripped down the context menu by like 75% because every team felt "it's hard to find our stuff, we'll just put it in the context menu because some users will benefit from it".  It's a sure-fire way to just bog everything down.

**Comment by CyrusNajmabadi** [comment] 2019-08-26 08:39
> I've been using Visual Studio for 15 years and I've learned it today by reading this thread.

Well, it wasn't in VS until just a few months ago.  So it's unsurprising that you wouldn't have known about it for the last 15 years.  The same would have been true of the context menu.  15 years of experience woudlnt' have helped you, since it hasn't been in the context menu the majority of that time.

**Comment by hyagli** [comment] 2019-08-26 08:46
> Well, it wasn't in VS until just a few months ago. So it's unsurprising that you wouldn't have known about it for the last 15 years.

The point is, it is a feature that is currently hard to find.

> 15 years of experience woudlnt' have helped you, since it hasn't been in the context menu the majority of that time.

Are you trying to help this thread or are you just trying to win an argument?

**Comment by CyrusNajmabadi** [comment] 2019-08-26 08:51
> Are you trying to help this thread 

I'm trying to help the thread.  Part of helping is providing the thinking that went into the decisions around this.  As someone who wrote the FindRefs feature several times for C#, and who had to do a lot of work and design around the context menu, I've got a ton of context here that is pretty much directly on point to the discussion being had.  :)

**Comment by CyrusNajmabadi** [comment] 2019-08-26 08:52
> The point is, it is a feature that is currently hard to find.

Yes.  But that's not a sufficient argument to put it an easier-to-find location.  Consider applying that argument to all the rest of the things in VS that are hard-to-find.  Consider the outcome you might get if you did that... :)

**Comment by CyrusNajmabadi** [comment] 2019-08-26 08:57
> There are 3 major classifications of variable operations. Declaration, assignment, and reference. 

Note: going back to the actual proposal.  This is not how C# sees things.  This definitely doesn't cover everything.  For example, the majority of feedback we got in the past was that people wanted to know when something *could* be written-to.  However, you can potential write to a variable *both* through assignment *and* through reference.  This is especially true now that C# has so many ref-oriented features.

This is why FindRefs actually breaks things down in the detail needed because if you want to know about 'potential writes' you need to know about more than actual 'assignments'.  

Right now i'd say this proposal seems attractive on a surface level, but it doesn't actually solve the likely problem that people would want it for.  If it was implemented it would likely be the case that soon afterwards people would be complaining and asking for anothe tweak for it to handle all the interesting and important cases that do come in the language quite often.

**Comment by hyagli** [comment] 2019-08-27 20:16
> IMO this is very _in your face_ and follows the same patterns and practices the rest of VS has.

Could you be more rude? We can't understand you when you communicate in civilized way.


Also, as you can read from the previous posts, we know where the feature is currently.
And you had to write a long post with 4 pictures to describe how to use it.

**Comment by hyagli** [comment] 2019-08-27 20:37
As a workaround, we could customize our own menu to get this feature.

`Tools` -> `Customize` -> `Commands` ->` Context Menu` -> `Editor Context Menus | Code Window`
If I insert a new menu here, I could have "Find All Assignments" in my own context menu.

![image](https://user-images.githubusercontent.com/3749620/63806073-6f4f0a00-c923-11e9-897c-c7b0ca31b668.png)


The problem is, we need a command like "Find All References" in this commands list.

**Comment by vatsalyaagrawal** [comment] 2019-09-03 21:25
related to #25994

**Comment by jmarolf** [comment] 2019-09-03 21:48
> We could have buttons for common things like all / reads / writes so you could trivially turn on these features. 

This sounds like a good idea. Placing things in the results tool window would be a good place to start and track how often this feature is discovered.

Now if only we could improve discover-ability on find-all-references for literal expressions...

**Comment by vatsalyaagrawal** [comment] 2022-08-08 16:19
Design meeting notes:

We need more customer development to find the right solution. Some questions that came up are:
Is peek definition #1 things folks do in this menu? 
- What is the current situation with menus? What are the numbers of context menu usage? High/Low usage can help drive the right solution here. 
- Our menus are too big, can we reduce those down? 
- Can filter button be always there (not hidden)? 
- Can we have dedicated (may be context aware) commands like, find, move? 
- Can we surface/alert users about features that they have not used/might not know about? May be we can use the new feature window or something similar.

**Comment by CyrusNajmabadi** [comment] 2022-11-01 17:51
Closing out.  This would need to go through editor/platform.  The data roslyn is rpoviding (and would continue to provide through LSP) contains what is necessary to feed any UI improvements here.

**Closed by CyrusNajmabadi** 2022-11-01 17:51 UTC
Labels: Area-IDE, Feature Request, Developer Community, Need Design Review

**Comment by jmarolf** [comment] 2022-11-01 18:05
@CyrusNajmabadi as we are closing this out can we "reactivate" the original feedback item and move it to the vs platform team?
