### ISSUE TITLE
Source Generators incompatible with .Net7

### ISSUE THREAD

**Issue by nikolatomasevicpro** [dotnet/roslyn#63806] opened 2022-09-05 14:19 UTC
Hello. First of all i wasn't sure where to post this but the source generators seem to be here so i will post it here.

I recently tried to upgrade my source generator with Generic Attributes. The idea is to make use of the generics to allow for factories providing parameters that my generators use. But i ran into an issue : 
 - CS8919 : Target runtime doesn't support static abstract members ininterfaces.
 
This is obviously because the project containing the models is targeted for netstandard2.0, which is required for the source generators. But if i switch to anything else, the generators project can't compile anymore.

Below is an exemple of how i wanted to use the attributes

```cs
    public interface IGenericGeneratorAttributeParametersFactory<TModel>
    {
        static abstract TModel GetParameters();
    }

    public class GenericGeneratorParameters
    {
        public string Name { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }
    }

    public class GenericGeneratorParametersFactory : IGenericGeneratorAttributeParametersFactory<GenericGeneratorParameters>
    {
        public static GenericGeneratorParameters GetParameters() => new GenericGeneratorParameters { Amount = 1, Name = "Some Name", Description = "Some Description" };
    }

    [AttributeUsage(AttributeTargets.Class)]
    public class GenericGeneratorAttribute<T> : Attribute
        where T: IGenericGeneratorAttributeParametersFactory<GenericGeneratorParameters>
    {

    }
```

We would add the attribute on a class with T being the factory providing the equired parameters for the generator.
Is this possible or will it be possible at the release?

**Comment by jaredpar** [comment] 2022-09-07 16:13
> But if i switch to anything else, the generators project can't compile anymore

Can you elaborate here? What errors are you seeing?

Flipping a source generator to `net7.0` for example should be fine in terms of the generator being able to compile. It's totally unsupported and the generator **will** fail when used from `msbuild`. But it should build just fine. 

> We would add the attribute on a class with T being the factory providing the equired parameters for the generator.
Is this possible or will it be possible at the release?

It will not be possible to use this sample in generators. Source generators and analyzers run on both .NET Framework and .NET Core because that is where the compiler runs. Several features in this sample aren't supported on .NET Framework hence the sample will fail. This is not expected to change for several more releases. 

Closing as the overall scenario is not supported by design. Interested though to keep working through why you hit compilation errors.

**Closed by jaredpar** 2022-09-07 16:13 UTC
Labels: Area-Compilers, untriaged

**Comment by nikolatomasevicpro** [comment] 2022-09-09 11:05
Hello. As you have said, the feature i'm trying to use is not supported currently. That is why i'm getting the error. 
As for the compilation. i have a project containing the models used by the generator separate from the project containing the generator. So if the models project targets net7.0 the generators project can't reference the models project.

But if i change the target framwork of the models project to netstandard2.0 i can't have the statics in the interface. 

I also tried to use types names and instantiate the factory in the generator with Type.GetType("MyFactory") which obviously returns null (i remember it's because the types are not initialised yet). 

So i guess i'm stuck at waiting and using the strings in attribute parameters to get data that my generator needs.
