### ISSUE TITLE
Upgrading Microsoft.CodeAnalysis.CSharp package from 4.0.1 to 4.1.0 broke build until SDK 6.0.2 and VS update

### ISSUE THREAD

**Issue by voroninp** [dotnet/roslyn#59687] opened 2022-02-22 14:00 UTC
My solution stopped building because added analyzers (same solution) were failing with the following error:

> Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

After I installed .NET 6.0.2 SDK and Updated VS to 17.1 everything started working again.

My expectation is that package's minor version increase should not cause that issue.

**Comment by jinujoseph** [comment] 2022-02-23 18:50
cc @sharwell

**Comment by sharwell** [comment] 2022-02-23 19:43
This behavior is by design. Analyzers which target a newer version of the compiler than is used during a build are expected to fail. Since the 6.0.100 SDK only includes Roslyn 4.0, analyzers targeting 4.1 or greater will fail to load.

**Comment by sharwell** [comment] 2022-02-23 21:58
The option I use is to add the following line to a source file:

```
#error version
```

Then I run a build; the build error will include a message stating the exact version of the compiler used for that build. Analyzer packages will need to use that version or earlier.

@jmarolf while the above covers detecting SDK versions, do we have a separate list of which Roslyn versions ship in which versions of Visual Studio?

**Comment by CollinAlpert** [comment] 2022-04-04 13:37
@sharwell I get why this is by design, but this is still a breaking change. Version 4.0.1 works fine with .NET 5.

**Comment by CollinAlpert** [comment] 2022-04-04 13:37
@sharwell I get why this is by design, but this is still a breaking change. Version 4.0.1 works fine with .NET 5.

**Comment by sharwell** [comment] 2022-04-04 16:56
> ... but this is still a breaking change ...

@CollinAlpert Can you clarify precisely what you mean by 'this'?

**Comment by CollinAlpert** [comment] 2022-04-04 18:31
Sorry for not elaborating more. What I mean is the upgrade from version 4.0.1 to 4.1.0 breaking a build when not using .NET 6. If my .NET 5 build succeeds using version 4.0.1, I'd expect it to also do so when upgrading to 4.1.0. I would expect something like this to happen when bumping up a major version, e.g 5.0.0.

**Comment by sharwell** [comment] 2022-04-04 18:35
@CollinAlpert The .NET SDK 5.0.406 ships with Roslyn 3.11, so tools using Roslyn 4.x (including 4.0 and 4.1) will not work with that SDK.

**Comment by mavasani** [comment] 2022-12-12 03:55
Closing this as by design as explained by Sam's comments.

**Closed by mavasani** 2022-12-12 03:55 UTC
Labels: Question, Area-Infrastructure
