### ISSUE TITLE
Cannot rename tuple `using` alias

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#75433] opened 2024-10-08 12:58 UTC
### Version Used

Compiler: 4.12.0-3.24470.4 (d799b056)  
.NET: 9.0.100-rc.1.24452.12  
Visual Studio Code: 1.94.0, `d78a74bcdfad14d5d3b1b782f87255d802b57511`, x64  
C# Extension: v2.49.25  
C# Dev Kit Extension: v1.11.11

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code (Visual Studio untested).
2. Add the following code wherever syntactically applicable:
   ```cs
   using Point = (int X, int Y);
   
   class C
   {
       Point _pt;
   }
   ```
3. Attempt to rename the `Point` symbol at either place (from its definition or at its usage).

### Expected Behavior

The `using` alias is renamed, as well as all usages of it.

### Actual Behavior

Renaming from the definition is allowed, but does not rename any of the usages.  
Renaming at the usage is not allowed, showing a `The element can't be renamed.` message.

**Comment by CyrusNajmabadi** [comment] 2024-10-08 15:14
Pretty sure this is a dupe.

**Comment by CyrusNajmabadi** [comment] 2024-10-08 15:16
Dupe of #67642

**Closed** 2024-10-08 15:16 UTC
Labels: Area-Compilers, untriaged
