### ISSUE TITLE
Lambdas + custom delegate types + type inference = breaking change in C# 10

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#57916] opened 2021-11-22 12:01 UTC
**Version Used**: 

.NET 6.0 SDK RTM

**Steps to Reproduce**:

Compile the following code:
```c#
using System;

DataRules.AddRule(new Constant<MyDelegate>(), () => Function); // Error
DataRules.AddRule(new Constant<Func<string, int>>(), () => Function); // OK
DataRules.AddRule<MyDelegate>(new Constant<MyDelegate>(), () => Function); // OK

int Function(string s) => s.Length;

static class DataRules
{
  public static void AddRule<T>(Constant<T> constant, Func<T> factory) { }
  public static void AddRule<T>(Constant<T> constant, T value) { }
}

class Constant<T> { }
delegate int MyDelegate(string s);
```

**Expected Behavior**:

This code compiles in C# 9.0/.NET 5.0 SDK, all invocations are bound to `AddRule<T>(Constant<T> constant, Func<T> factory)` overload. I expect the same behavior in C# 10/.NET 6.0 SDK

**Actual Behavior**:

Failed build in C# 10/.NET 6.0 SDK:
> CS1593	Delegate 'MyDelegate' does not take 0 arguments

If I understand correctly, the compiler should prefer overloads that don't infer "function type" for the type arguments.

**Comment by controlflow** [comment] 2021-11-22 12:10
Probably related to https://github.com/dotnet/roslyn/pull/57713#discussion_r748779212

**Comment by svick** [comment] 2021-11-22 12:22
I looks like a duplicate of https://github.com/dotnet/roslyn/issues/57630, which has already been fixed. Indeed, when I build your code using a daily build (Microsoft.Net.Compilers.Toolset version 4.0.1-1.21569.2), it compiles successfully.

**Comment by cston** [comment] 2021-11-22 17:59
Thanks for reporting this issue @controlflow. 

As @svick mentioned, this was also reported in #57630 and has been fixed.

**Comment by jcouv** [comment] 2022-01-04 05:30
@cston Should this issue be closed then?

**Closed** 2022-01-04 05:59 UTC
Labels: Area-Compilers, untriaged, New Feature - Lambda Improvements
