### ISSUE TITLE
CSC.exe exits with code -2146232797 in strange cases where local function declared in an inner scope calling another local function

### ISSUE THREAD

**Issue by priyanr** [dotnet/roslyn#22027] opened 2017-09-11 09:01 UTC
**Version Used**: 
VS 2017 .Net 4.6.2
C# Compiler version 2.3.2.61928 (ec1cde8b)

**Steps to Reproduce**:
1. CSC exits when compiling 
 class Program
    {
        static void Main(string[] args)
        {
            
        }
        public object TestLocalFn(object inp)
        {
            try
            {
                var sr = new object();
                return sr;
                void Local1()
                {
                    var copy = inp;
                    Local2();
                }
                void Local2()
                {

                }
            }
            catch { throw; }
        }
    }
2. Working case 1

 class Program
    {
        static void Main(string[] args)
        {
            
        }
        public object TestLocalFn(object inp)
        {
            try
            {
                var sr = new object();
                return sr;
                void Local1()
                {
                    //var copy = inp;  //removing this line it works
                    Local2();
                }
                void Local2()
                {

                }
            }
            catch { throw; }
        }
    }
3. everything works if not scoped

    class Program
    {
        static void Main(string[] args)
        {

        }
        public object TestLocalFn(object inp)
        {

            var sr = new object();
            return sr;
            void Local1()
            {
                var copy = inp;
                Local2();
            }
            void Local2()
            {

            }

        }
    }

**Comment by svick** [comment] 2017-09-11 09:07
This looks like another duplicate of https://github.com/dotnet/roslyn/issues/19033, which is fixed in master.

**Comment by gafter** [comment] 2017-09-15 19:06
@svick I don't think so. This crashes for me on the latest internal build.

**Comment by svick** [comment] 2017-09-15 20:38
@gafter That's weird. It compiles fine for me with locally compiled csc from latest master (266f5b9), and also on [2 weeks old build on SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATAAmwEYB2AWACgBvS4gNkIBZCiAOACmIAYBtAXXwQEAcygBKSjQqV8AXxnYAzPgD2wAFZwAxjHwAVOLAAyKrRAA2AMQB27NZp34AltYAOEivin4fPmAgBPGV8vYJDfADchfCgEfABefGs4AHdVDW0YdjEAbjDwwhIYhDzPAp9sZhMzcyJs/PDvcvCouK0VVwCE5zdS5vDqi1xsvub5MvLK/EHzYY9+qQaQ8fCVkLMYLQALL3wYLYQVFJy5GXHKWSA===) (1a36abc). And the exception [when compiling on SharpLab from NuGet](https://sharplab.io/#v2:CYLg1APgAgTABFAjAdgLACgDeGkDYEAsCiAHABRIAMA2gLpwCGATgOYDOAlBtuhnAL58oAZjgB7AEYArAKYBjAC5wAKjLYKAMmLkMANgDEAdmUmzFcAJaGADl3RwecJ04VMAnn2cPPX5wDdmODYmOABeOEMZAHdxaXkFMg4Abh9fBGQgphT7NKcoIi0dXURE1N9HXN8AkLkxazcwyxtsyt9CvRhElsrBHNz8uHbdTrtWnjKvXt8prx0FOQALBzgFBaYxKKSBPl6MfiA=) is a `KeyNotFoundException`, just like in #19033. Though the stack trace is different.

**Comment by agocke** [comment] 2017-10-02 21:17
Our internal builds were using 15.4, which is not `master`. This does appear to be fixed by the closure conversion rewrite.

**Closed** 2017-10-04 18:23 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
