### ISSUE TITLE
Add or change parameter in an existing method (ReSharper style)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39107] opened 2019-10-07 19:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/740946/add-or-change-parameter-in-an-existing-method-resh.html)._

---
<p>This previous feature suggestion was incorrectly marked as included in VS2017. This capability is still not available in the general case.</p><p><a href="https://developercommunity.visualstudio.com/content/idea/351698/refactoring-to-add-a-parameter-to-existing-method.html">https://developercommunity.visualstudio.com/content/idea/351698/refactoring-to-add-a-parameter-to-existing-method.html</a></p><p>The steps provided here: </p><p><a href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-parameter?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-parameter?view=vs-2019</a></p><p>are not applicable generally.</p><p>I have</p><p>-An interface defining a code contract with a particular method</p><p>-Several classes implementing this method</p><p>The add parameter mentioned in the above public doc does not appear in my case (in VS 2019).</p><p>I additionally want the ability to</p><ul><li>Change the type of an existing parameter</li><li>Add new parameters</li><li>Remove existing parameters</li><li>Rename existing parameters</li></ul><p>And I need these changes to take effect on every implementation of the method. Resharper has had this for years. When can we expect this same functionality in Vanilla VS 2019?</p>

---
#### Jane Wu [MSFT] on 9/22/2019, 11:27 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-10-08 19:39
Duplicate of https://github.com/dotnet/roslyn/issues/33534
cc @ivanbasov

**Closed by jinujoseph** 2019-10-08 19:39 UTC
