### ISSUE TITLE
Visual Studio becomes unresponsive then eventually crashes with OOM after writing "throw" in method argument list

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#12823] opened 2016-07-29 17:41 UTC
Recent Preview 4 build

1.  At $ enter a space _then_ backspace

``` C# 
using System;

class Program
{
    static void Main(string[] args)
    {
        Type.GetType("Foo", throw$)
    }
}

```

Visual Studio becomes unresponsive and finally crashes with an OOM with this stack:

```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IdentifierNameSyntax.SetDiagnostics(Microsoft.CodeAnalysis.DiagnosticInfo[] diagnostics)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GreenNodeExtensions.WithDiagnosticsGreen<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax>(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticInfo[] diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.WithAdditionalDiagnostics<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax>(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticInfo[] diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.AddError<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax>(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.ErrorCode code, object[] args)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTerm(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseArgumentExpression(bool isIndexer)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseArgumentList(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openToken, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SeparatedSyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ArgumentSyntax> arguments, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken closeToken, Microsoft.CodeAnalysis.CSharp.SyntaxKind openKind, Microsoft.CodeAnalysis.CSharp.SyntaxKind closeKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedArgumentList()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParsePostFixExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionSyntax expr)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTerm(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.Precedence precedence)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseElementInitializer()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableInitializer(bool allowStackAlloc)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableDeclarator(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax parentType, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.VariableFlags flags, bool isFirst, bool allowLocalFunctions, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken> mods, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken refTokenOpt, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LocalFunctionStatementSyntax localFunction, bool isExpressionContext)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableDeclarators(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.VariableFlags flags, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SeparatedSyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.VariableDeclaratorSyntax> variables, bool variableDeclarationsExpected, bool allowLocalFunctions, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken> mods, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken refTokenOpt, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LocalFunctionStatementSyntax localFunction)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLocalDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SeparatedSyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.VariableDeclaratorSyntax> variables, bool allowLocalFunctions, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken> mods, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken refTokenOpt, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LocalFunctionStatementSyntax localFunction)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLocalDeclarationStatement()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParsePossibleBadAwaitStatement(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ResetPoint resetPointBeforeStatement)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParsePossibleBadAwaitStatement()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatements(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CSharpSyntaxNode previousNode, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.StatementSyntax> statements, bool stopOnSwitchSections)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlock(bool isMethodBody, bool isAccessorBody)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlockAndExpressionBodiesWithSemicolon(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax blockBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ArrowExpressionClauseSyntax expressionBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken semicolon, bool parseSemicolonAfterBlock)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder modifiers, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken refKeyword, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeParameterListSyntax typeParameterList)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder modifiers)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder modifiers)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceDeclaration()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax>(System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> parseFunc, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> createEmptyNodeFunc)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(Microsoft.CodeAnalysis.Text.SourceText newText, System.Collections.Generic.IReadOnlyList<Microsoft.CodeAnalysis.Text.TextChangeRange> changes)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(Microsoft.CodeAnalysis.Text.SourceText newText)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__13>(ref Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__13 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.CreateLazyIncrementallyParsedTree.AnonymousMethod__0(System.Threading.CancellationToken c)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.StartAsynchronousComputation(Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.AsynchronousComputationToStart computationToStart, Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.Request requestToCompleteSynchronously, System.Threading.CancellationToken callerCancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.GetValueAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__34>(ref Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__34 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Document.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Host.BackgroundParser.ParseDocumentAsync.AnonymousMethod__0()	Unknown

****
```

**Comment by Pilchie** [comment] 2016-07-29 17:44
Dupe of https://github.com/dotnet/roslyn/issues/12197

**Closed by Pilchie** 2016-07-29 17:44 UTC
Labels: Area-Compilers, Bug
