### ISSUE TITLE
[Regression] Opening Code Style options page crashed VS

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#43177] opened 2020-04-08 02:01 UTC
**Version Used**: 
Version 16.6.0 Preview 3.0 [30005.27.master]

**Steps to Reproduce**:

```
Unable to cast object of type 'Microsoft.CodeAnalysis.CodeStyle.CodeStyleOption2`1[System.Boolean]' to type 'Microsoft.CodeAnalysis.CodeStyle.CodeStyleOption`1[System.Boolean]'.
Exception Info: System.InvalidCastException
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.BooleanCodeStyleOptionViewModel..ctor(Microsoft.CodeAnalysis.Options.IOption, System.String, System.String, System.String, Microsoft.VisualStudio.LanguageServices.Implementation.Options.AbstractOptionPreviewViewModel, Microsoft.VisualStudio.LanguageServices.Implementation.Options.OptionStore, System.String, System.Collections.Generic.List`1<Microsoft.VisualStudio.LanguageServices.Implementation.Options.CodeStylePreference>, System.Collections.Generic.List`1<Microsoft.VisualStudio.LanguageServices.Implementation.Options.NotificationOptionViewModel>)
   at Microsoft.VisualStudio.LanguageServices.CSharp.Options.Formatting.StyleViewModel..ctor(Microsoft.VisualStudio.LanguageServices.Implementation.Options.OptionStore, System.IServiceProvider)
   at Microsoft.VisualStudio.LanguageServices.CSharp.Options.Formatting.CodeStylePage+<>c.<CreateOptionPage>b__0_0(Microsoft.VisualStudio.LanguageServices.Implementation.Options.OptionStore, System.IServiceProvider)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.GridOptionPreviewControl.OnLoad()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.AbstractOptionPage.OnActivate(System.ComponentModel.CancelEventArgs)
   at Microsoft.VisualStudio.Shell.DialogPage+DialogSubclass.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(System.String, System.Object, System.Object ByRef)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(System.String, System.Object, System.Object ByRef)
   at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Expected Behavior**:

**Actual Behavior**:

**Comment by davkean** [comment] 2020-04-08 02:02
@mavasani Related to these changes: https://github.com/dotnet/roslyn/commit/6692e76f4071e015ae07a90490ebf806e95f4612?

**Comment by mavasani** [comment] 2020-04-08 02:05
Yes, dupe of https://github.com/dotnet/roslyn/issues/42923. Unfortunately, missed the last insertion but was inserted today. Can you please try on tomorrow’s build?

**Comment by sharwell** [comment] 2020-04-08 04:54
Duplicate of #42923

**Closed by sharwell** 2020-04-08 04:54 UTC
