### ISSUE TITLE
Fix-all solution level is really slow

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#50193] opened 2020-12-31 11:15 UTC
**Version Used**: 16.9.0 Preview 2.0

**Steps to Reproduce**: 
When doing some big refactoring for `roslyn-analyzers`, I have noticed multiple times that waiting for solution-level fix-all is extremely slow. Waiting for more than 10min and I still don't have any preview window. But doing a project-per-project fix-all shows the window in less than 30s.

**Comment by CyrusNajmabadi** [comment] 2020-12-31 17:32
Can you please provide more information?  What fix all were you performing?  What file/line did you perform it on?

**Comment by Evangelink** [comment] 2020-12-31 17:49
It happened for the following PRs:
- https://github.com/dotnet/roslyn-analyzers/pull/4555
- https://github.com/dotnet/roslyn-analyzers/pull/4595
- https://github.com/dotnet/roslyn-analyzers/pull/4631
- https://github.com/dotnet/roslyn-analyzers/pull/4641

I don't recall exactly which file/line but I am sure I have tested that with a couple of locations.

I will get back to some previous commit and give you an exact scenario for you to (try to) reproduce.

**Comment by CyrusNajmabadi** [comment] 2020-12-31 17:56
Can you follow the instructions here to report a performance trace: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

Basically start the the trace, then do the fix all.  Then stiop the trace after say a minute. Finish the bug report process and tag @sharwell in the issue that is filled. Thanks!

**Comment by sharwell** [comment] 2020-12-31 19:07
@Evangelink no need to report an issue here, I already know what the issue is

**Comment by sharwell** [comment] 2020-12-31 19:08
Duplicate of #49698

**Closed by sharwell** 2020-12-31 19:08 UTC
Labels: Area-Analyzers, untriaged

**Comment by Evangelink** [comment] 2021-01-01 09:39
Sorry for the duplicate, I was searching for an already existing issue but couldn't find one.

**Comment by sharwell** [comment] 2021-01-01 22:03
Duplicates aren't a problem. I was just trying to save you time by not filing the performance feedback mentioned in https://github.com/dotnet/roslyn/issues/50193#issuecomment-753016413. 😄
