### ISSUE TITLE
CreateHostClientAsync takes 10-15 seconds to complete

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#51198] opened 2021-02-12 20:07 UTC
An example breakdown:

ServiceHubRemoteHostClient.CreateAsync: 00:00:14.9413773

This was spent doing the following:
RequestServiceAsync: 00:00:04.8270036
InitializeGlobalState: 00:00:02.7949971
EnableAsync: 00:00:07.2393847

That's 15 seconds until a feature can actually make a call to OOP (which will then have its own overhead.

Note: this was for a basic console app.  

ETL trace at: https://microsoft-my.sharepoint.com/:u:/p/cyrusn/EVmceT6x-kNBu1ICaqd6omgBqaMNzpqLTydJ97eXdnIrjg

**Comment by sharwell** [comment] 2021-02-14 08:37
@CyrusNajmabadi The performance trace is missing a bunch of data. Can you make sure manual performance traces are captured using the [General Purpose](https://github.com/dotnet/roslyn/blob/master/docs/wiki/Recording-performance-traces-with-PerfView.md#general-purpose) profile?

**Comment by sharwell** [comment] 2021-02-14 08:40
The performance trace shows 13.5 seconds of JIT time in ServiceHub.RoslynCodeAnalysisService.exe. A breakdown of JIT operations shows that 7 of the top 12 assemblies are local builds, which means they have not gone through OptProf and have not been installed with NGEN, so the delay as described would be expected.

**Comment by CyrusNajmabadi** [comment] 2021-02-14 09:39
Is there a way to get these ngen'ed locally.  I need a way to validate local performance improvements relating to features being avialable soon after VS launch.

**Comment by sharwell** [comment] 2021-02-14 22:13
> Is there a way to get these ngen'ed locally?

No, you can only ngen a strong named assembly locally if it is "real" signed. The public sign mechanism in the open source repositories will not work.

**Comment by sharwell** [comment] 2021-02-14 22:15
Closing this issue since it's not actionable for open source developers. If you have further questions about specific testing related to this, it would be better to check with internal infrastructure teams who handle signing/OptProf/NGEN.

**Comment by CyrusNajmabadi** [comment] 2021-02-15 00:05
Reactivating :-). It still tracks needing some way to effectively perf test a real world, high impact and high priority area.

**Comment by sharwell** [comment] 2021-02-15 00:19
@CyrusNajmabadi The title and first post are no longer accurate, and could result in users spending time investigating a case which already has a known root cause. Can you file a new issue for the test scenario instead?

**Closed** 2022-11-01 23:10 UTC
Labels: Area-IDE, Resolution-By Design
