### ISSUE TITLE
Full solution analysis does not respect Code Style settings

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#15386] opened 2016-11-19 11:56 UTC
**Version Used**: 25909

**Steps to Reproduce**:

1. Enable full solution analysis
2. Change the default Code Style settings, 
3. Open some files that will trigger Code Style

**Expected Behavior**: Settings (i.e. preference and severity) to apply for the whole solution

**Actual Behavior**: Settings applied for opened files only. Rest of the solution is analysed with default settings.

**Comment by Pilchie** [comment] 2016-11-21 23:05
Dupe of https://github.com/dotnet/roslyn/issues/9712 I believe

**Closed by Pilchie** 2016-11-21 23:05 UTC
Labels: Area-IDE
