### ISSUE TITLE
Indexing string with from-end Index results in InvalidProgramException

### ISSUE THREAD

**Issue by jkotas** [dotnet/roslyn#34209] opened 2019-03-18 16:59 UTC
_From @briman0094 on March 18, 2019 16:3_

Running the following program under .NET Core 3.0.100-preview3-010431 results in an `InvalidProgramException` thrown upon startup in both Debug and Release builds:

```csharp
using System;

public class Program
{
	public static void Main()
	{
		var s = "ABC123";

		Console.WriteLine(s[^1]);
	}
}
```

Output from `dotnet run`:

```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Program.Main()
```

The following program runs as expected:

```csharp
using System;

public class Program
{
	public static void Main()
	{
		var s = "ABC123";
		var a = s.ToCharArray();

		Console.WriteLine(a[^1]);
		Console.WriteLine(s[1]);
		Console.WriteLine(s[1..^1]);
		Console.WriteLine(s[^4..^1]);
	}
}
```

Output from `dotnet run`:

```
3
B
BC12
C12
```

This demonstrates that the issue **only** occurs when indexing a string with a FromEnd Index; using a Range which includes a FromEnd index works fine.

_Copied from original issue: dotnet/coreclr#23316_

**Comment by jkotas** [comment] 2019-03-18 16:59
_From @mikedn on March 18, 2019 16:30_

Checked JIT asserts:
```
Assert failure(PID 7036 [0x00001b7c], Thread: 9464 [0x24f8]): Assertion failed '!"Unexpected node in impNormStructVal()"' in 'Program:Main()' (IL size 65)

    File: d:\projects\coreclr\src\jit\importer.cpp Line: 1743
    Image: D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\CoreRun.exe
```

**Comment by jkotas** [comment] 2019-03-18 16:59
_From @mikedn on March 18, 2019 16:43_

Looks like this is caused by broken IL generated by the C# compiler:
```
	IL_0027: ldloc.1
	IL_0028: ldloc.1
	IL_0029: callvirt instance int32 [System.Private.CoreLib]System.String::get_Length()
	IL_002e: ldloca.s 0
	IL_0030: call instance int32 [System.Private.CoreLib]System.Index::get_Value()
	IL_0035: sub
	IL_0036: callvirt instance char [System.Private.CoreLib]System.String::get_Chars(valuetype [System.Private.CoreLib]System.Index)
```
It Calls `get_Chars(Index)` with an `i4` on the stack.

**Comment by briman0094** [comment] 2019-03-18 22:15
It seems like this should have been fixed by #33679. Prior to #33679, `LocalRewriter_IndexerAccess.VisitIndexerAccess` would rewrite `string[^n]` to `string[string.Length - n]` (which should be `get_Chars(int32)`) but would then use the same `node.Indexer` `PropertySymbol` from the `FromEndIndexExpression` which is `get_Chars(System.Index)`.

.NET Core 3.0.100-preview3-010431 was built off of commit d98a9be343afa26e0fe7459e1026bf9e1dce3553 which includes #33679. The problematic IL being generated (seen above) seems to be coming from [here](https://github.com/dotnet/roslyn/pull/33679/files#diff-74a82622051b7b258352d8b4f8a95630L105) which was eliminated in #33679; I'm not sure why it's still being generated like that instead of simply passing the `Index` instance to `get_Chars(Index)`.

**Comment by briman0094** [comment] 2019-03-19 14:55
Building Roslyn off of `master` and compiling this program generates the correct IL and runs as intended

**Comment by jcouv** [comment] 2019-07-15 04:06
It looks like this was fixed. @briman0094 confirmed above and I was also not able to repro on sharplab.
I'm going ahead and closing this issue.

FYI @agocke

**Closed by jcouv** 2019-07-15 04:06 UTC
Labels: Area-Compilers, New Language Feature - Range
