### ISSUE TITLE
EditorConfig UI enhancements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53171] opened 2021-05-05 08:18 UTC
- [x] 1. Font currently feels too large compared with other UI elements (e.g, solution explorer). Opened https://github.com/dotnet/roslyn/pull/54599 to fix that.

    ![image](https://user-images.githubusercontent.com/31348972/117113696-2489c480-ad8b-11eb-8293-4a0965883e73.png)

- [x] 2. New line preferences has a typo (Carrage return should be Carriage return) and probably no need to have double `\` before `r` or `n`. Being fixed in #53327

    
    ![image](https://user-images.githubusercontent.com/31348972/117114185-d0cbab00-ad8b-11eb-84a0-c5a6a0bdc5fd.png)

- [x] 3. The grid columns should by default be expanded to fit the content if there is a space.

- [x] 4. "RemoveUnnecessaryImportsFixable" shouldn't probably exist on UI since it has "NotConfigurable" custom tag. (applies to IDE0005_gen as well)

    ![image](https://user-images.githubusercontent.com/31348972/117115936-096c8400-ad8e-11eb-99f1-d84df5ca4bb6.png)

    Proposed fix is to add `GetConfigurableDiagnosticDescriptors` similar to [`GetNonCompilationEndDiagnosticDescriptors`](https://github.com/dotnet/roslyn/blob/6971285fe7d345afc08b1b11c3a4012dd6dcb3dd/src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache.cs#L64-L70) and call it [here](https://github.com/dotnet/roslyn/blob/2976da0ab00d676ef2817644c833682dcc901ae4/src/EditorFeatures/Core/EditorConfigSettings/DataProvider/Analyzer/AnalyzerSettingsProvider.cs#L58). (#53175)

- [ ] 5. CA2016 is duplicated for some reason:

    ![image](https://user-images.githubusercontent.com/31348972/117116132-446eb780-ad8e-11eb-9621-0ca268a9b296.png)

- [ ] 6. I'm not sure if the Category column is necessary, since the category is apparent from the parent node anyway. I also see that RS1023 is duplicated, so it seems like the previous point is general, wasn't specific to CA2016.

    ![image](https://user-images.githubusercontent.com/31348972/117116333-84359f00-ad8e-11eb-84aa-5c8f15707f81.png)

- [ ] 7. For some reason, I don't see any changes I make in UI in the actual .editorconfig text

Note: I was using Roslyn.sln while experimenting.

**Comment by Youssef1313** [comment] 2021-05-05 08:47
@jmarolf

**Comment by jinujoseph** [comment] 2021-05-05 18:18
cc @jmarolf 
#2, #4, #5 could make it into 16.11 
#7 is a priority bug if its reproducible

**Comment by jmarolf** [comment] 2021-05-05 18:20
I'll investigate 7 today

**Comment by Youssef1313** [comment] 2021-05-05 21:15
> I'll investigate 7 today

For reference, here are the steps I've done (I didn't have VS Preview on the machine I was working on - so I used `main` build):

- Open `Roslyn.sln` using non-preview VS
- Set build configuration to `Release` and set RoslynDeployment as startup project.
- CTRL+F5 to start without debugging.
- Opened `Roslyn.sln` in the second VS instance.
- Opened `.editorconfig` by double clicking under `Solution Items` in Solution Explorer.

**Comment by jmarolf** [comment] 2021-05-05 21:46
What specific items were not saved? or did literally nothing work?

**Comment by Youssef1313** [comment] 2021-05-05 21:47
@jmarolf What I have tried was changing a few severities from code style tab. Haven't tried something else.

**Comment by jmarolf** [comment] 2021-05-05 21:47
Can you list the exact repo steps please? That would help a lot.

**Comment by Youssef1313** [comment] 2021-05-05 21:48
Is https://github.com/dotnet/roslyn/issues/53171#issuecomment-833012576 missing anything?

**Comment by jmarolf** [comment] 2021-05-05 21:50
Which options? What did you set them to? how did you view the results? Did the editor mark the file as dirty or did nothing happen?

**Comment by Youssef1313** [comment] 2021-05-05 21:55
@jmarolf I believe I have tried lots of options from code style tab. After modifying from UI, I attempted to save (while I could see there was no asterisk next to editorconfig file name - which means that no unsaved changes exists). Then, I did a `git status` to see if there are any changes to editorconfig, but there wasn't.

I'll check tomorrow if I could reproduce again.

Anything I can do if I was able to reproduce?

**Comment by jmarolf** [comment] 2021-05-06 01:05
Looking into this today, it appears that a sequence of changes can cause the editor and the file buffer to get "out of sync". Unclear what the root cause is yet

**Comment by DotJoshJohnson** [comment] 2021-11-13 17:56
I just ran into item 7 today. Fresh install of VS 2022, new project, new .editorconfig. I tried changing the "Namespace declarations" settings to "File scoped" and the underlying .editorconfig file was not changed.

**Comment by yodasad** [comment] 2021-11-18 09:33
Yes, I ran into the item 7 too, fresh install of VS 2022, new project, new .editorconfig.

**Comment by Youssef1313** [comment] 2021-11-18 10:02
@jmarolf @jinujoseph Can this be prioritized?

**Comment by Sergio0694** [comment] 2021-11-24 17:28
I had the same issue the other day when I tried using the UI. Actually I could swear that in my case it not only not save the settings correctly, but it also kept resetting them back to some other values, seemingly at random. I just gave up and started editing the `.editorconfig` file manually after a bit 😅

**Comment by TheBeardedLlama** [comment] 2022-02-21 16:44
Ran into point 7 too
VS2019 16.11.3

I was changing values in the Code Analyzers tab.
No asterisk to indicate values had changed and nothing happened when hitting save.
File remains the same as before.

**Comment by Nicholas-Westby** [comment] 2022-03-01 23:05
I am also experiencing point 7 (editorconfig UI doesn't update the .editorconfig file). Here's the current commit I'm working with: https://github.com/rhythmagency/formulate/tree/48aa47296ad72477fef64f45899a3633054c1899

Here's the solution you can open: https://github.com/rhythmagency/formulate/blob/48aa47296ad72477fef64f45899a3633054c1899/src/Formulate.sln

Here's the editor config file: https://github.com/rhythmagency/formulate/blob/48aa47296ad72477fef64f45899a3633054c1899/src/.editorconfig

Here's a screenshot that shows the two items I attempted to change:

<img width="960" alt="screenshot showing two highlighted editor config items" src="https://user-images.githubusercontent.com/5933222/156263265-69113f6a-33d1-4690-a638-2f2cdec1af92.png">

I tried CTRL+S, File Save, File Save As, and File Save All. None of them caused the file to be updated.

Note also that it shows the location as "Visual Studio Settings". At one point, that changed to list the path to the actual .editorconfig file in the solution, but I haven't been able to reproduce that again.

I'm using Visual Studio Professional 2022 64-bit version 17.0.4. I do not have Visual Studio 2019 installed (this is a pretty new machine). I'm using Windows 11. I think .Net 6 is installed and that .Net 5 is not installed. At least, I think when creating new projects in Visual Studio I'm only given .Net 6 as an option.

I was able to confirm that manually editing the .editorconfig file shows the file as updated in my Git GUI tool (SmartGit).

**Comment by Youssef1313** [comment] 2022-03-17 18:35
point 7 in https://github.com/dotnet/roslyn/issues/53171

**Comment by jmarolf** [comment] 2022-03-18 21:53
closing this in favor of tracking individual bugs

**Closed by jmarolf** 2022-03-18 21:53 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Feature - Editor Config UI, Dev17 IDE Priority
