### ISSUE TITLE
Allow customization of auto-generated XML comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58224] opened 2021-12-09 20:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Allow-customization-of-auto-generated-XM/1593420)._

---
Currently, when "///" is typed above a class/method/etc, a snippet of xml documentation comment is automatically generated. However, there doesn't seem to be any way to customize this template/snippet. This is unfortunate considering the potential of xml documentation and 3rd party tools that use it. For exemple, custom tags are supported and many of us would like to have some added to the snippet generated, for example:

Replace

```
/// <summary>
/// 
/// </summary>
/// <param name="myParam"></param>
/// <returns></returns>
public int MyMethod(string myParam) { }
```
with

```
/// <summary>
/// 
/// </summary>
/// <param name="myParam"></param>
/// <myTag></myTag>
/// <returns></returns>
public int MyMethod(string myParam) { }
```
That is the essential idea. As a side note, perhaps there could be a way to reuse the existing snippet template system to generate and customize xml comments?

---
#### Feedback Bot on 11/23/2021, 06:59 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by sharwell** [comment] 2021-12-14 23:38
Duplicate of #39141

**Closed by sharwell** 2021-12-14 23:38 UTC
Labels: Area-IDE, Feature Request, Developer Community
