### ISSUE TITLE
Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeCSharp seems flaky

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#13506] opened 2016-08-31 21:45 UTC
It's failed twice in the past two days: 

* http://jdash.azurewebsites.net/builds/test?name=Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeCSharp&viewName=dotnet_roslyn&pr=False&limit=10&startDate=2016-08-30
* https://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_release_unit64/567/

I suspect this has the same root cause as https://github.com/dotnet/roslyn/issues/13433

**Comment by jcouv** [comment] 2016-09-16 03:31
Yes, I suspect TestRecoverableSyntaxTreeCSharp as well: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3650/

**Comment by natidea** [comment] 2016-09-16 18:38
Duplicate of #13788

**Closed** 2016-09-16 18:38 UTC
Labels: Area-IDE, Flaky, Resolution-Duplicate
