### ISSUE TITLE
Compiler should report semantic diagnostics from broken lambdas

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#32628] opened 2019-01-18 20:33 UTC
Derived from https://github.com/dotnet/roslyn/issues/23667 and more precisely from @gafter's comment https://github.com/dotnet/roslyn/issues/23667#issuecomment-374980551, which states the requested compiler feature.

**Comment by jaredpar** [comment] 2021-07-13 21:11
Going to mark this as a dupe of #53238. These appear to be the same issue but #53238 has more detail as to what is going on here and what needs to be solved.

**Closed by jaredpar** 2021-07-13 21:11 UTC
Labels: Area-Compilers, Feature Request
