### ISSUE TITLE
Unit Testing ValueTuple with Microsoft Fakes fails to compile when used in interfaces

### ISSUE THREAD

**Issue by gongin** [dotnet/roslyn#18628] opened 2017-04-12 13:17 UTC
I have made this post here for reference: http://stackoverflow.com/questions/43369733/unit-testing-valuetuple-with-microsoft-fakes

**Version Used**:  <package id="System.ValueTuple" version="4.3.0" targetFramework="net452" />

**Steps to Reproduce**:

1.  Create c# project and unit test project, add project reference in unit test
2.  Create fakes for project
3.  Create interface as below:
public interface IModelClass
{
    (string val1, int val2) Run();
}

4. Build solution

**Expected Behavior**: It compiles

**Actual Behavior**:
Building the solution yields this error:

Severity: Error
Code: CS8141
Description: The tuple element names in the signature of method 'StubIModelClass.IModelClass.Run()' must match the tuple element names of interface method 'IModelClass.Run()' (including on the return type).

The error stems from the f.cs file in the fakes build directory as it implements the Run() method stub as:

svt::System.ValueTuple<string, int> vt::ValueTuple.IModelClass.Run()

**Comment by jcouv** [comment] 2017-05-28 05:23
I just noticed this issue. @VSadov @jaredpar do you known anything about Microsoft Fakes? Or maybe some contacts?

**Comment by jcouv** [comment] 2017-05-28 05:24
@gongin I suspect that the issue with Fakes is not specific to tuples, but likely applies to any struct type. Is that correct?

**Comment by jaredpar** [comment] 2017-07-07 18:14
This looks like a duplicate of #20528.

**Closed by jaredpar** 2017-07-07 18:14 UTC
Labels: Area-Compilers, New Language Feature - Tuples
