### ISSUE TITLE
Semicolon terminating a field declaration misplaced when typed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35221] opened 2019-04-23 21:13 UTC
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/56616102-824a7a00-65d1-11e9-8958-5b124f763a06.png)

**Steps to Reproduce**:

Place caret in the below code as indicated by `|` and type `;`.

```C#
using System;
class Program
{
    private const int Max = 1000|

    [Obsolete]
    public string Property { get; set; }
}
```

**Expected Behavior**:

```C#
using System;
class Program
{
    private const int Max = 1000;

    [Obsolete]
    public string Property { get; set; }
}
```

**Actual Behavior**:

The semicolon is written to the buffer after the `[Obsolete]` attribute.

```C#
using System;
class Program
{
    private const int Max = 1000

    [Obsolete];
    public string Property { get; set; }
}
```

**Comment by CyrusNajmabadi** [comment] 2019-04-23 21:25
Looks like dupe of https://github.com/dotnet/roslyn/issues/34983

**Comment by sharwell** [comment] 2019-04-23 21:52
Duplicate of #34983

**Closed by sharwell** 2019-04-23 21:52 UTC
Labels: Area-IDE
