### ISSUE TITLE
AD0001 warning when #nullable is used inside of a block

### ISSUE THREAD

**Issue by johnkellyoxford** [dotnet/roslyn#31912] opened 2018-12-18 20:23 UTC
**Version Used**: VS 2019 Preview 1, C# 8.0 beta, <NullableReferenceTypes> true in .csproj

**Steps to Reproduce**:
Build this:
```
using System;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;

namespace Playground
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
#nullable enable
            string? a;
            #nullable disable
        }
    }
}
```

**Expected Behavior**:
All good, except for the unused warning

**Actual Behavior**:
"Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.Formatting.FormattingDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Unexpected false'."

**Comment by jaredpar** [comment] 2019-01-02 17:41
The design of `#nullable` is specifically to allow it in blocks. The warning though is unexpected. Moving to IDE

**Comment by jasonmalinowski** [comment] 2019-06-20 00:26
Not able to reproduce anymore.

**Closed by jasonmalinowski** 2019-06-20 00:26 UTC
Labels: Area-IDE, Bug, New Language Feature - Nullable Reference Types
