### ISSUE TITLE
TypeLoadException when c# compiled with 2015 tries to load managed C++ assembly (works with 2013)

### ISSUE THREAD

**Issue by aml11** [dotnet/roslyn#5993] opened 2015-10-15 07:55 UTC
I have a solution with c# and managed c++ (which is built with VS2008 compiler), when I use VS2013 (with the exact same sln) everything works, with 2015 I get:

```
Unhandled Exception: System.TypeLoadException: Signature of the body and declaration in a method implementation do not match.  Type: 'ConsoleApplication21.CI'.  Assembly: 'ConsoleApplication21, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ConsoleApplication21.Program.Main(String[] args)
```

The consists of the following c++ (managed):
```cpp

#include "stdafx.h"

using namespace System;

namespace X {
public __gc __interface I
{
	Void A(UInt32& x);
	Void B(UInt32* x);
};
}
```

and a simple C# class:
```cs

using X;

namespace ConsoleApplication21
{
		class CI : I {
			public void A(ref uint x)
			{
			}

			public void B(ref uint x)
			{
				
			}
		}

	internal class Program
	{
		private static void Main(string[] args)
		{

			new CI();

		}
	}
}
```

Comparing IL it seems that it makes a mistake when trying find the signature in the dll:
VS2015:
```
          instance void  X.I.A(uint32 modopt([mscorlib]System.Runtime.CompilerServices.IsImplicitlyDereferenced)& x) cil managed
```
VS2013:
```
          instance void  X.I.A(uint32& modopt([mscorlib]System.Runtime.CompilerServices.IsImplicitlyDereferenced) A_1) cil managed
```

IL files can be found here:
https://mega.nz/#!Uw1AGYBR!KKoRmNJPbrjQxszrhRe50t5I7IpuHczkSS41l8rbrQU
Project files can be found here:
https://mega.nz/#!V4dknBSL!A6-Gt98XFtiuuiorWAXjE1r17TOk6RHOCFp53MD75w8
Built binaries (VS2013):
https://mega.nz/#!8sUTmSIa!002PeSJWeASkSUDQsN7LWOAUlJY9QjyIaT6wRkbErUw
Built binaries (VS2015):
https://mega.nz/#!Z9V0VZZT!1Pau62941xUWtpHpBl9I8Dn9CLCvofvxyjYmjKckPxM

**Comment by jaredpar** [comment] 2015-10-15 23:08
@AlekseyTs I believe this is a duplicate of #4163.  Can you confirm?

**Comment by AlekseyTs** [comment] 2015-10-15 23:23
@jaredpar Not exactly. It looks like this issue is about the order of ByRef and custom modifiers in the signature of a parameter. I am not aware of any issues in this particular area in RTM. Still, it is possible that the issue is fixed by the changes we’ve made around custom modifiers' handling since RTM, but this needs real confirmation/verification.

**Comment by AlekseyTs** [comment] 2015-10-16 21:23
@jaredpar I am able to reproduce this issue with current bits. It looks like only interface implementation is affected, overriding is not. Should be easy to fix, I think.

**Comment by AlekseyTs** [comment] 2015-10-16 22:36
IL for the interface:
```
.class interface public abstract auto ansi beforefieldinit X.I
{
  .method public newslot abstract virtual 
          instance void  A(uint32& modopt([mscorlib]System.Runtime.CompilerServices.IsImplicitlyDereferenced) x) cil managed
  {
  } // end of method I::A

  .method public newslot abstract virtual 
          instance void  B(uint32& x) cil managed
  {
  } // end of method I::B

} // end of class X.I
```

**Comment by AlekseyTs** [comment] 2015-10-19 20:09
@VSadov Please verify.

**Closed** 2015-10-19 20:08 UTC
Labels: 4 - In Review, Area-Compilers, Tenet-Compatibility

**Comment by aml11** [comment] 2015-10-20 06:43
Wow, quick response, thanks.
Might I ask when Milestone 1.2 is expected to get to beta/release?

**Comment by AlekseyTs** [comment] 2015-10-20 17:09
@aml11 We can’t comment on release dates till they are finalized and publicly announced.

**Comment by AlekseyTs** [comment] 2015-10-20 22:16
@aml11 In the meantime, you can use explicit interface implementation as a workaround.
