### ISSUE TITLE
Type of `-(2147483648)`

### ISSUE THREAD

**Issue by dgrunwald** [dotnet/roslyn#2429] opened 2015-05-01 11:27 UTC
The type of `-(2147483648)` differs between VS2013 and VS2015:

When compiled with VS2013 / csc, the following program prints `System.Int64`.
When compiled with VS2015RC, it prints `System.Int32`.

```c#
using System;

class Program
{
  static void X(object i)
  {
   Console.WriteLine(i.GetType());
  }
  
  public static void Main(string[] args)
  {
   X(-(2147483648));
  }
}
```

This Issue was found when compiling the [NRefactory unit tests](https://github.com/icsharpcode/NRefactory/blob/99189662c7a4a59771df56163fc9d7300f7e6a14/ICSharpCode.NRefactory.Tests/CSharp/Resolver/UnaryOperatorTests.cs#L236) with Roslyn.

The spec is kind of ambiguous in this situation, but the comment in `Binder.BindIntegralMinValConstants` seems to interpret the spec in the same way as csc and NRefactory: the special case does not apply when the integer literal is in parentheses, so the type should be `long`.

**Comment by HaloFour** [comment] 2015-05-01 13:37
Dupe of #2075.

**Closed** 2015-05-01 19:54 UTC
Labels: Area-Compilers, Bug, Language-C#, Resolution-Duplicate

**Comment by MattGertz** [comment] 2015-05-15 22:22
Verified as dupe.
