### ISSUE TITLE
Remove final newline if `insert_final_newline = false`

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/roslyn#59729] opened 2022-02-24 03:24 UTC
**Version Used**: 

17.1.0

**Steps to Reproduce**:

1. Set `insert_final_newline = false` in your editorconfig file
2. Format a document with a newline at the end
 
**Expected Behavior**:

The newline is removed.

**Actual Behavior**:

The newline is left there, which means that if you set `insert_final_newline = true`, format documents, then set `insert_final_newline = false`, you'll be left with final newlines in every document.

**Comment by danielchalmers** [comment] 2022-02-24 03:25
I came across this when trying to use it as a workaround for #59728. Not sure if it's intended behavior or not.

**Comment by jinujoseph** [comment] 2022-03-02 19:11
Duplicate of #20356

**Closed by jinujoseph** 2022-03-02 19:11 UTC
Labels: Bug, help wanted, Area-IDE, Investigation Required
