### ISSUE TITLE
C# override completion left compile errors due to unqualified parameter types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41027] opened 2020-01-17 00:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/867332/c-override-completion-left-compile-errors-due-to-u.html)._

---
Within an Exception-derived class, I typed `public override GetObj` and pressed TAB. Instead of fully-qualifying the parameter type names or adding the necessary `using`, C# just added the simple type names which did not resolve in the current file, leaving compile errors. 

```cs
namespace NerdBank.Algorithms.NodeConstraintSelection
{
	using System;
	public class BrokenConstraintException : InvalidOperationException
	{
		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			base. GetObjectData(info, context);
		}
	}
}

```

See two screenshots.

---
#### Visual Studio Feedback System on 12/26/2019, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/27/2019, 01:05 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment] 2020-03-13 00:01
Dupe of https://github.com/dotnet/roslyn/issues/39909

**Closed by genlu** 2020-03-13 00:01 UTC
Labels: Area-IDE, Bug, Developer Community, IDE-IntelliSense
