### ISSUE TITLE
Default `.editorconfig` creates properties that are tried to be localized

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61595] opened 2022-05-31 11:15 UTC
**Version Used**:
VS 2022 v17.3 Preview 1.1

**Steps to Reproduce**:
1. Set your VS language not to be English
2. Create project of any kind
3. Create new `.editorconfig` _on solution level_ (for some reason the behaviour is ok when generating on project level)
4. Observer this (part of generated `.editorconfig`):
```
dotnet_naming_rule.interface_should_be_начинается_с_i.severity = suggestion
dotnet_naming_rule.interface_should_be_начинается_с_i.symbols = interface
dotnet_naming_rule.interface_should_be_начинается_с_i.style = начинается_с_i

dotnet_naming_rule.типы_should_be_всечастиспрописнойбуквы.severity = suggestion
dotnet_naming_rule.типы_should_be_всечастиспрописнойбуквы.symbols = типы
dotnet_naming_rule.типы_should_be_всечастиспрописнойбуквы.style = всечастиспрописнойбуквы

dotnet_naming_rule.не_являющиеся_полем_члены_should_be_всечастиспрописнойбуквы.severity = suggestion
dotnet_naming_rule.не_являющиеся_полем_члены_should_be_всечастиспрописнойбуквы.symbols = не_являющиеся_полем_члены
dotnet_naming_rule.не_являющиеся_полем_члены_should_be_всечастиспрописнойбуквы.style = всечастиспрописнойбуквы

# Спецификации символов

dotnet_naming_symbols.interface.applicable_kinds = interface
dotnet_naming_symbols.interface.applicable_accessibilities = public, friend, private, protected, protected_friend, private_protected
dotnet_naming_symbols.interface.required_modifiers = 

dotnet_naming_symbols.типы.applicable_kinds = class, struct, interface, enum
dotnet_naming_symbols.типы.applicable_accessibilities = public, friend, private, protected, protected_friend, private_protected
dotnet_naming_symbols.типы.required_modifiers = 

dotnet_naming_symbols.не_являющиеся_полем_члены.applicable_kinds = property, event, method
dotnet_naming_symbols.не_являющиеся_полем_члены.applicable_accessibilities = public, friend, private, protected, protected_friend, private_protected
dotnet_naming_symbols.не_являющиеся_полем_члены.required_modifiers = 

# Стили именования

dotnet_naming_style.всечастиспрописнойбуквы.required_prefix = 
dotnet_naming_style.всечастиспрописнойбуквы.required_suffix = 
dotnet_naming_style.всечастиспрописнойбуквы.word_separator = 
dotnet_naming_style.всечастиспрописнойбуквы.capitalization = pascal_case

dotnet_naming_style.начинается_с_i.required_prefix = I
dotnet_naming_style.начинается_с_i.required_suffix = 
dotnet_naming_style.начинается_с_i.word_separator = 
dotnet_naming_style.начинается_с_i.capitalization = pascal_case
```
This was done with russian language of VS. As you can see, not only the comments got translated (which is kind of expected here), but also a lot of actual values are tried to be localized: `interface_should_be_начинается_с_i`, `типы_should_be_всечастиспрописнойбуквы`, `всечастиспрописнойбуквы` etc...

This is **not** an expected behaviour. Actual values **must** never be localized

**Comment by Youssef1313** [comment] 2022-05-31 12:39
Duplicate of https://github.com/dotnet/roslyn/issues/39602

**Comment by CyrusNajmabadi** [comment] 2022-05-31 14:04
Closing as dupe.

**Closed by CyrusNajmabadi** 2022-05-31 14:04 UTC
Labels: Area-IDE, untriaged
