### ISSUE TITLE
Magical semi-colon teleportation in Visual Studio

### ISSUE THREAD

**Issue by I-Omnibus** [dotnet/roslyn#64577] opened 2022-10-07 20:59 UTC
```csharp
/*
 * Microsoft Visual Studio Community 2022
 * Version 17.4.0 Preview 1.0
 * VisualStudio.17.Preview/17.4.0-pre.1.0+32804.182
 * Microsoft .NET Framework
 * Version 4.8.03761
 */
namespace Sample;

internal class TrivialIssue {

   InvalidProgramException Up { get => new(); }

   internal TrivialIssue() {
      _ = String.Empty switch {/*↓ Down there*/
         string TypeSemiColonHere => nameof(Up),
         _ => throw this.Up
      } ;
   }/* ↑ Reappears here */

}
```

**Comment by Youssef1313** [comment] 2022-10-08 06:51
This is a feature called complete statement. You can disable it via **Tools** → **Options** → **Text Editor** → **C#** → **IntelliSense** → and uncheck **Automatically complete statement on semicolon**

**Comment by CyrusNajmabadi** [comment] 2022-10-08 07:09
Closing out as this is working as intended, and is accompanied by an option to disable this entirely if not desired.  Thanks @Youssef1313 !

**Closed by CyrusNajmabadi** 2022-10-08 07:09 UTC
Labels: Area-IDE, untriaged
