### ISSUE TITLE
New decompilation prompt makes find refs *UNUSABLE*

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42778] opened 2020-03-25 22:24 UTC
Gif to give you an idea about how bad this is:

![killme](https://user-images.githubusercontent.com/4564579/77591027-5bb15500-6eac-11ea-840c-46968c79e03f.gif)

**Comment by CyrusNajmabadi** [comment] 2020-03-25 22:25
Tagging @kendrahavens @mikadumont @sharwell @jinujoseph 

This is unbelievably bad.

**Comment by CyrusNajmabadi** [comment] 2020-03-25 22:25
this started happening after my last VS upgrade

**Comment by sharwell** [comment] 2020-03-25 22:32
Duplicate of #42638

**Comment by CyrusNajmabadi** [comment] 2020-03-25 22:36
i don't thiink this a dupe.  I'm not even saying "goto def".  I'm F8'ing through find-ref results.

**Comment by sharwell** [comment] 2020-03-26 04:54
@CyrusNajmabadi This is a duplicate. The header items used for grouping the results are definitions from metadata. Cycling through the list attempts to navigate to them.

**Closed by sharwell** 2020-03-26 04:54 UTC
Labels: Resolution-Duplicate
