### ISSUE TITLE
The new decompilation log should be collapsed by default

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41351] opened 2020-01-31 23:27 UTC
The decompilation log in #41007 is not collapsed by default, so for short files it is readily visible. The outlining applied to decompiled source files should collapse this region by default.

/cc @siegfriedpammer

**Comment by siegfriedpammer** [comment] 2020-02-01 09:16
I just tested this and I cannot reproduce this. All comments should be collapsed by default.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:21
Closing as not repro.

**Closed by CyrusNajmabadi** 2024-10-21 19:21 UTC
Labels: Bug, help wanted, Area-IDE
