### ISSUE TITLE
Improper outlines for else-if block with multiple line condition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48523] opened 2020-10-12 16:55 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/195301/improper-outlines-for-else-if-block-with-multiple.html)._

---
In an else-if statement, where the condition takes multiple lines, the dashed lines that appear for outlining are lined up underneatht the &quot;if&quot;, and not the &quot;else&quot;, and they do not appear properly.

A rough illustraion:

if (condition)
{
|
|
|
}

else if (condition 1 &amp;&amp;
           condition 2)
{
       |
       |
       |
}

---
#### Cytheria Ji [MSFT] on 2/7/2018, 11:34 PM: 

<p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

#### Feedback Bot on 3/31/2019, 11:57 PM: 

<p>Thank you for the feedback, but our team was unable to prioritize it at this time as they are working on problems with broader customer impact. You can see details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . Please comment below if you have additional data or details that will help us appropriately reprioritize this issue. It is possible that this problem has been addressed in our latest version which can be downloaded from:  https://visualstudio.microsoft.com/downloads/  . Thanks for contributing to Developer Community.</p>

#### Feedback Bot on 10/12/2020, 09:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2020-10-12 17:05
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/95772977-7691be00-0c72-11eb-8b40-17fcb7ecf328.png)

If you can include a code sample that shows this, that would be very helpful.

**Comment by Youssef1313** [comment] 2020-10-12 17:22
@CyrusNajmabadi The screenshot you provided isn't what the original posted was describing. I could reproduce what he wanted to describe:

![image](https://user-images.githubusercontent.com/31348972/95774198-38bb8680-0cc0-11eb-9423-b2d10d1fc65d.png)

Can you re-open?

**Comment by CyrusNajmabadi** [comment] 2020-10-12 17:34
Yup.  Reactivating.  Seems to have something to do with multi-line conditions.  May be a dupe of some existing bug.

**Comment by Youssef1313** [comment] 2020-10-12 17:39
> May be a dupe of some existing bug.

@CyrusNajmabadi Your feeling is right. I searched in the issues and found https://github.com/dotnet/roslyn/issues/45682

**Comment by CyrusNajmabadi** [comment] 2020-10-12 17:39
Dupe of https://github.com/dotnet/roslyn/issues/45682.  Closing out.

**Closed by CyrusNajmabadi** 2020-10-12 17:39 UTC
Labels: Area-IDE, Resolution-Not Reproducible, untriaged
