### ISSUE TITLE
Can't use latest main: 19b5e961ecb97b008106f1b646c077e0bffde4a7

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#74286] opened 2024-07-08 15:56 UTC
VS fails to restore:

![image](https://github.com/dotnet/roslyn/assets/4564579/d8aad1bb-c3a4-4067-9db3-56b220118005)

```
...
Failed to restore D:\github\roslyn\src\Compilers\CSharp\Test\IOperation\Microsoft.CodeAnalysis.CSharp.IOperation.UnitTests.csproj (in 22 ms).
Failed to restore D:\github\roslyn\src\Workspaces\TestAnalyzerReference\Microsoft.CodeAnalysis.TestAnalyzerReference.csproj (in 6 ms).
Failed to restore D:\github\roslyn\src\Compilers\CSharp\Test\EndToEnd\Microsoft.CodeAnalysis.CSharp.EndToEnd.UnitTests.csproj (in 22 ms).
Failed to restore D:\github\roslyn\src\Compilers\CSharp\Test\Emit3\Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests.csproj (in 26 ms).
Failed to restore D:\github\roslyn\src\EditorFeatures\VisualBasic\Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj (in 13 ms).
Failed to restore D:\github\roslyn\src\Compilers\CSharp\Test\CommandLine\Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj (in 24 ms).
Failed to restore D:\github\roslyn\src\EditorFeatures\VisualBasicTest\Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj (in 36 ms).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:02.3988418
========== Finished ==========
```

![image](https://github.com/dotnet/roslyn/assets/4564579/5823229e-b762-47f4-874e-82af44f5105c)

**Comment by arkalyanms** [comment] 2024-07-08 16:29
Duplicate of https://github.com/dotnet/sdk/issues/41791

**Closed by arkalyanms** 2024-07-08 16:29 UTC
Labels: Area-Infrastructure, Priority:0
