### ISSUE TITLE
Visual Basic IntelliSense Problem

### ISSUE THREAD

**Issue by NaxAlpha** [dotnet/roslyn#4373] opened 2015-08-06 09:24 UTC
Visual Basic .Net - Visual Studio 2015 Issues
1) Non-Shared Members are listed while pressing dot after class name
![i1](https://cloud.githubusercontent.com/assets/11090613/9108037/06cbd590-3c45-11e5-93f6-8457beccdac7.png)
2) Pressing Ctrl+S moves cursor to next line at first instead of keeping it there (if file is not saved)
3) Sometimes pressing Enter moves cursor to next to next line
![i1](https://cloud.githubusercontent.com/assets/11090613/9108201/e2138940-3c45-11e5-976e-669d5ca1bd9d.png)
4) There are other very little experience issues as compared to VB.net of VS 2013

**Comment by Pilchie** [comment] 2015-08-06 17:27
Hi,  issue 1 is already tracked in #4090, and should be fixed for the next VS Update.

Can you provide more details for the rest of the issues?  I'm not able to reproduce them from the descriptions you've given.  Additionally, it would be nice to have separate issues for each, as they will likely require separate fixes and it's easier to track that way.

**Comment by NaxAlpha** [comment] 2015-08-07 06:41
Thanx for your reply. I ll ask them as different issues

**Closed** 2015-08-07 06:41 UTC
Labels: Area-IDE, Bug
