### ISSUE TITLE
IOperation: VB - BoundAttribute should either implement specific interface or throw from all IOperation members.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8915] opened 2016-02-19 03:24 UTC

**Comment by mavasani** [comment] 2017-03-27 18:35
Depends on https://github.com/dotnet/roslyn/issues/18198

**Comment by jinujoseph** [comment] 2017-07-03 23:52
dupe of https://github.com/dotnet/roslyn/issues/18198

**Closed by jinujoseph** 2017-07-03 23:52 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, Concept-API, Language-VB, New Feature - IOperation
