### ISSUE TITLE
Add namespace indentation option to C# editor configuration.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54223] opened 2021-06-18 20:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-namespace-indentation-option-to-C-e/1442122)._

---
Please add a namespace indentation option to the C# text editor configuration.

Tools -> Options -> Text Editor -> C# -> Code Style -> Formatting -> Indentation would be a good place for it.

---
#### Feedback Bot on 6/6/2021, 07:13 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment] 2021-06-19 04:58
Duplicate of #24129.

**Closed** 2021-07-14 22:18 UTC
Labels: Area-IDE, Resolution-Duplicate
