### ISSUE TITLE
C#7 inline As variable scope is too wide

### ISSUE THREAD

**Issue by pixellos** [dotnet/roslyn#19129] opened 2017-04-29 20:39 UTC
**Versions Used**: 
2.1.0 (nuget from 24-04-2017),

Release version from 
Internal ID: Roslyn-Signed_20170320.4
Internal VS ID: d15rel.26403.00

**Steps to Reproduce**:

1.  new file test.cs with
```
using System; 

namespace Test
{
    public class Program
    {
        public static void Main()
        {
            Exception e = null;
            if (e is ArgumentException ae)
            {
            }
            if  (e is ArgumentException ae)
            {
            }
        }
    }
}
```
2. Compile with csc.exe from newest release 
https://github.com/dotnet/roslyn/releases/tag/Visual-Studio-2017-Update-1

**Expected Behavior**:
Build should have pass.
This construct should be treated like
```
Exception e = null;
{
    var ae = e as ArgumentException;
    if (ae != null)
    {
    }
}
{
    var ae = e as ArgumentException;
    if (ae != null)
    {
    }
}
```

**Actual Behavior**:
Microsoft (R) Visual C# Compiler version 2.1.0.56735
Copyright (C) Microsoft Corporation. All rights reserved.

test.cs(15,17): error CS0128: A local variable or function named 'ae' is already defined in thi
s scope

Code is treated like
```
Exception e = null;
var ae = e as ArgumentException;
if (ae != null)
{
}
var ae = e as ArgumentException;
if (ae != null)
{
}
```

**Comment by sharwell** [comment] 2017-04-30 18:23
The behavior you are observing is actually by design. It was implemented in order to support common scenarios like this:

```csharp
if  (!(e is ArgumentException ae))
{
  return;
}

// do something with ae here
```

**Comment by sharwell** [comment] 2017-04-30 18:27
I'm leaving this open so one of the language design members can add more context and/or links to related issues to help you understand how to best use this new feature. 😄

**Comment by pixellos** [comment] 2017-04-30 19:12
Ok, i've been trying to understand it right, so i put a little piece of code into vs 2017/ .net 4.7.0 (Microsoft.Net.Compilers 2.1.0)

``
using System.Reflection;
using System.Reflection.Emit;
namespace Csharp7
{
    class Program
    {
        public static MethodBase GetSomeMethod => MethodInfo.GetCurrentMethod();
        public static void Main(string[] args)
        {
            var k = Program.GetSomeMethod;
            if (!(k is MethodBuilder m))
            {
            }
            m.ToString();
        }
    }
}
``
And build is failing. `error CS0165: Use of unassigned local variable 'm'`

**Comment by jcouv** [comment] 2017-10-22 03:02
This is indeed by design.
You can find more details in the [pattern-matching proposal](https://github.com/dotnet/csharplang/blob/1918cb06e1c8b79e024c688d1c4159046479276d/proposals/patterns.md#scope-of-pattern-variables) and issue https://github.com/dotnet/roslyn/issues/12597.

I'll go ahead and close this. Thanks

**Closed by jcouv** 2017-10-22 03:02 UTC
Labels: Area-Language Design, Question
