### ISSUE TITLE
[C# Feature Request] implicit namespace per file

### ISSUE THREAD

**Issue by michalczerwinski** [dotnet/roslyn#43216] opened 2020-04-09 06:36 UTC
The idea is simple: let's allow default namespace for all things declared in single cs file:

```csharp
namespace default
{
	public class SomeClass
	{
	}
}
```
The above should declare some class within the namespace as per project "Default Namespace" and folder names (file path).

What are the gains here?
* file can be moved accross project without need to change its content
* no changes in specific file needed when modifying parent namespace or project folder structure (usings changes in other files would be still required, though)
* DRY, why shall we specify the namespace if it can be concluded by tools

One variation could be:

```csharp
namespace default;

public class SomeClass
{
}
```
which is even shorter and reduce nesting parenthesis.
 
The suggestion is inspired by razor file behavior in Blazor. Additional thing to consider is _Import.cs file which might be a nice addition to this feature.

**Comment by sharwell** [comment] 2020-04-09 13:34
Duplicate of dotnet/csharplang#2908

**Closed by sharwell** 2020-04-09 13:34 UTC
