### ISSUE TITLE
Expand Selection: Select full line when only whitespace chars left

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28335] opened 2018-07-06 21:21 UTC
When using Expand Selection, if all the non-whitespace chars on a line are selected, the next Expand operation should select the entire line including the line break.
(Technically, this is position zero on the current line to position zero on the following line.)

For example, expanding from this:
![image](https://user-images.githubusercontent.com/17131343/42400702-82a2aba6-8127-11e8-86c4-9a88ba8069f1.png)

Would result in this:
![image](https://user-images.githubusercontent.com/17131343/42400757-b3ad6740-8127-11e8-965a-b06b1f0c905e.png)

This makes it easier when using line operations like Duplicate Code or Move Lines.

**Comment by CyrusNajmabadi** [comment] 2018-07-06 21:23
Perhaps this logic should just be part of move-lines or duplicate-code.  i.e. if it can see that you've selected all the code on the lines, it should just expand to include the whitespace as well.

**Comment by justcla** [comment] 2018-07-06 22:08
Selecting whole lines is useful. Duplicate Code and Move Lines are just examples. Not intended to distract from the usefulness of selecting whole lines.

**Comment by justcla** [comment] 2018-07-06 22:11
Yes, it's very possible this behavior could be implemented at the platform level, but the current implementation is that Roslyn offers the next expanded block. Having the editor artificially expand the selection based on certain rules can be done - but creates an inconsistency. Maybe something to bring in the Editor team to discuss.

**Comment by CyrusNajmabadi** [comment] 2018-07-06 22:13
>Selecting whole lines is useful. Duplicate Code and Move Lines are just examples. Not intended to distract from the usefulness of selecting whole lines.

Right.  But the point still stands that we could just update those features once... instead of having to fix up N languages.  Note that even if you get all the languages under MS control, will you get all the other languages in the ecosystem to buy into this behavior?

To me, it makes more sense for hte langauges to expose language-based selection.  And editor features can figure out how to bridge that to line-oriented operations.

**Comment by justcla** [comment] 2018-07-06 22:30
Then perhaps you can bring that up with the editor team. Right now, the Editor team provide the platform for language teams to supply the next largest block. At the moment it is up to each language to implement the desired behavior.

For now, it is a suggestion for Roslyn implementation.

**Comment by CyrusNajmabadi** [comment] 2018-07-06 22:35
I can't file bugs against the editor team (no access to the VSO repo).  I would suggest you open a bug with them to track the discussion.  

> At the moment it is up to each language to implement the desired behavior.

Right.  And i'm saying: i believe roslyn it implementing the desired behavior (to me at least).  it is mapping the operations appropriate over our tree.

If those selections then aren't ideal for other editor operations, then i would update *those* editor operations.  

this is likely the best path forward because my expectation is that if you can actually even get enough languages to implement this API, they will implement it similar to how roslyn does things.

**Comment by justcla** [comment] 2018-07-06 22:39
The Editor team told me to raise bugs against Roslyn.

We don't agree that the strict tree based model current being used is the correct implementation of this API by Roslyn.

I'm leaving this bug for tracking against Roslyn.

**Comment by sharwell** [comment] 2021-04-26 19:57
Duplicate of #49925

**Comment by CyrusNajmabadi** [comment] 2023-02-09 22:13
We don't plan on doing this.  Uniform whitespace handling should be handled by the editor.  That way it works properly for all languages.

**Closed by CyrusNajmabadi** 2023-02-09 22:13 UTC
Labels: Area-IDE, Feature Request, Need Design Review
