### ISSUE TITLE
A linQ  Range variable error that I think it is not!

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#48309] opened 2020-10-04 04:20 UTC
I have this query:
```vb.net
Dim PayStateID = (From s In db.CheckStates
                  Where s.ID = stateId
                  Select s.PayStateID).First
```

where s.PayStateID is of type byte, so the query returns `IQueryable(Of Byte)` and first returns byte.
The strange thing is that I get this error in design time:
> Range variable 'PayStateID' hides a variable in an enclosing block or a range variable previously defined in the query expression
```

why `PayStateID' is considered a range variable? There is no anonymous type involved to think it can be a field name. So, is this a true error?

**Comment by CyrusNajmabadi** [comment] 2020-10-04 16:09
Duplicate of https://github.com/dotnet/roslyn/issues/48307.

**Closed by CyrusNajmabadi** 2020-10-04 16:09 UTC

**Comment by VBAndCs** [comment] 2020-10-04 16:20
@CyrusNajmabadi
> Roslyn is the VB compiler.

But in previous issues, you said to me it is not Roslyn-specific, but belongs to VB compiler. I really can't realize the fine difference between them.

**Comment by CyrusNajmabadi** [comment] 2020-10-04 16:37
Please point out where i said this and i can clarify.  

>  I really can't realize the fine difference between them.

There is no difference.  Roslyn is the C# and VB compiler today (and has been for the last 10 years).
