### ISSUE TITLE
Flakey Test - Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopy

### ISSUE THREAD

**Issue by TIHan** [dotnet/roslyn#24749] opened 2018-02-09 23:19 UTC
**Branch**: master-vs-deps

Test is failing and passing sometimes. Here it is failing:

Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopy

```
Stacktrace
MESSAGE:
System.Reflection.TargetParameterCountException : Parameter count mismatch.

+++++++++++++++++++
STACK TRACE:
at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at System.Delegate.DynamicInvokeImpl(Object[] args) 
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperation.InvokeImpl() 
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state) 
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) 
at System.Windows.Threading.DispatcherOperation.Invoke() 
at System.Windows.Threading.Dispatcher.ProcessQueue() 
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) 
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) 
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) 
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) 
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) 
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) 
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) 
at Roslyn.Test.Utilities.DispatcherExtensions.DoEvents(Dispatcher dispatcher) 
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize) 
at Microsoft.CodeAnalysis.Workspace.Dispose() 
at Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopy()
```

**Comment by sharwell** [comment] 2018-02-15 03:13
Do you have a link to a Jenkins run where this failed?

**Comment by 333fred** [comment] 2018-02-26 18:33
Likely a dupe of https://github.com/dotnet/roslyn/issues/24754.

**Comment by 333fred** [comment] 2018-02-26 18:36
@jinujoseph I'm not sure who on the IDE team would be best to look at this, but this call: https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/EditorFeatures/TestUtilities/DispatcherExtensions.cs#L10, has started failing on a number of IDE tests in the 15.7.x-vs-deps branch.

**Comment by jinujoseph** [comment] 2018-02-26 18:58
@333fred can you point to a recent Jenkins Run where this has failed pls

**Comment by 333fred** [comment] 2018-02-26 19:29
@jinujoseph there were `DoEvents` related failures in these:
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_debug_unit64/38/
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_release_unit64/40/
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master-vs-deps/job/windows_release_unit64/81/

**Comment by sharwell** [comment] 2018-02-27 06:00
@333fred thanks, I've flagged all three as exempt from deletion policy until they are investigated

**Comment by 333fred** [comment] 2018-02-28 18:42
Another one: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_debug_unit64/43/

**Comment by Shyam-Gupta** [comment] 2018-03-12 21:27
Another: https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x-vs-deps/job/windows_debug_unit64_prtest/133/consoleFull#-410211996a086b3e-df04-41d2-bc4d-43e8f9406d07

**Comment by 333fred** [comment] 2018-03-13 17:40
Still more failures: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_release_unit32/57/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense/CSharpCompletionCommandHandlerTests_Projections/TestInObjectCreationExpression/. @sharwell, any progress on this?

**Comment by 333fred** [comment] 2018-03-20 17:46
And again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master-vs-deps/job/windows_release_unit64/96/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense/CSharpCompletionCommandHandlerTests_Projections/TestInObjectCreationExpression/

**Closed** 2020-08-07 19:35 UTC
Labels: Area-Infrastructure, Disabled Test, Flaky
