### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave test is flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21668] opened 2017-08-22 20:44 UTC
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5.x/job/windows_debug_vs-integration/19/

**Comment by Pilchie** [comment] 2017-08-23 16:41
Can you take a look?

**Comment by 333fred** [comment] 2017-09-06 18:33
Stack from a recent failure:
```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave
      Assert.Contains() Failure
      Not found: Sub Main(x As Integer)
      In value:  Module Module1
          Sub Main(x   As   Integer)
          End Sub
      End Module
      
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicLineCommit.cs(81,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave()
```

**Comment by tmat** [comment] 2017-09-07 00:50
Seems like a dup of https://github.com/dotnet/roslyn/issues/20991

**Comment by tmat** [comment] 2017-12-05 21:29
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/9342/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by tmat** [comment] 2018-02-28 19:25
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration_prtest/409/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicLineCommit/CommitOnSave/

**Comment by sharwell** [comment] 2019-03-07 21:57
Duplicate of #26041

**Closed by sharwell** 2019-03-07 21:57 UTC
Labels: Area-IDE, Test, Urgency-Soon
