### ISSUE TITLE
windows_release_vs-integration_prtest failure due to AppDomainUnloadedException or MissingMethodException

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#19815] opened 2017-05-26 21:03 UTC
Two indications, this in the [integration tests log](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4662/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log): 

```
...
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicErrorListNetCore.ErrorsDuringMethodBodyEditing
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicErrorListNetCore.ErrorsDuringMethodBodyEditing [SKIP]
      https://github.com/dotnet/roslyn-project-system/issues/1825
  Finished:    Roslyn.VisualStudio.IntegrationTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
```

A [mysterious MissingMethodException](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4662/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/Unknown-MissingMethodException-13.16.28.png)

**Comment by Pilchie** [comment] 2017-05-29 19:50
Same as #19824?

**Comment by Pilchie** [comment] 2017-05-30 16:33
@jasonmalinowski @jaredpar Any idea how to get more info to track this down?

**Comment by jaredpar** [comment] 2017-05-30 16:37
See the following:

> https://github.com/xunit/xunit/issues/490

It looks like it's just considered noise by xunit and not actually affecting the tests.  Are you seeing it affect the tests here?

**Comment by Pilchie** [comment] 2017-05-30 16:39
@dpoeschl / @tmat ?

**Comment by dpoeschl** [comment] 2017-05-30 18:24
@jaredpar Not quite sure what you're asking. The test run failed, but no individual tests failed. I guess that makes it "noise"?

**Comment by jaredpar** [comment] 2017-05-30 18:28
@dpoeschl the discussion in the xunit site makes me skeptical this error message directly resulted in the test failing.  All of the reports I could find, more besides that particular thread, showed that the error message appeared even when tests passed.  

I agree it's suspicious though.  I tried to look into the run to see if I could definitively determine if it was responsible but the run had already been recycled.  If we see this again can we pin the run so that we can do a deep dive?

**Comment by jasonmalinowski** [comment] 2017-05-30 21:42
I think I'd at least entertain figuring out what the full stack is here. Not sure if that needs an xunit modification, or we can log that, or can use procdump somehow.

**Comment by jaredpar** [comment] 2017-05-30 21:53
@jasonmalinowski 

> I think I'd at least entertain figuring out what the full stack is here.

I think the first step is figuring out if it's actually causing the Jenkins leg to fail.  I can't find any references to this failing xunit, only it being extraneous output.  

I do agree it would be nice to figure out where this is coming from.  But given the randomness, and lack of desire by xunit to figure it out either, it doesn't seem likely unless we put in a bit of effort here.  Not justifiable unless we know it's actually failing tests.  

> or we can log that, or can use procdump somehow.

That would only be useful if it was an unhandled exception.  That doesn't seem to be the case.

**Comment by jasonmalinowski** [comment] 2017-05-30 22:00
> That would only be useful if it was an unhandled exception. That doesn't seem to be the case.

Never underestimate the power of evil first chance exception handlers. (Although I guess this is icky because who knows which AppDomain to be listening to here...)

**Comment by jasonmalinowski** [comment] 2017-06-02 00:15
Duplicate of #15497.

**Closed by jasonmalinowski** 2017-06-02 00:15 UTC
Labels: Area-Infrastructure, Test
