### ISSUE TITLE
VB.NET: Local variables not available in code completion when there is no space between If and "("

### ISSUE THREAD

**Issue by yevgeni-zolotko** [dotnet/roslyn#46041] opened 2020-07-16 17:30 UTC
**Version Used**: 3.6.0

**Steps to Reproduce**:

1. In Visual Studio 2019, create a new VB.NET project.
2. Paste the following code:
```vb
    Sub Main(args As String())
        Dim i = 1234
        If(
    End Sub
```
Notice *there is no space between `If` and the `(`*.

3. Locate the caret after the `If(`, and press `Ctrl+Space` to invoke code completion.

**Expected Behavior**:
`i` variable is included into the code completion list.

**Actual Behavior**:
`i` variable is missing from the code completion list.

See the following screenshot:
![image](https://user-images.githubusercontent.com/64135073/87703154-0d99c780-c7a3-11ea-868a-e2b68ef5b10d.png)

**Comment by jinujoseph** [comment] 2020-07-21 20:08
cc @genlu

**Comment by Youssef1313** [comment] 2020-10-09 18:59
I digged into this a little bit, the root cause is the SyntaxContext has a value of `false` for `IsAnyExpressionContext`. This happen specifically in the following line:

https://github.com/dotnet/roslyn/blob/b61d9d2863eebfc76b032e5f8fcd0a918fb27147/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb#L351

**Comment by CyrusNajmabadi** [comment] 2024-10-21 21:12
Closing as we are unlikely to be changing these experiences.

**Closed by CyrusNajmabadi** 2024-10-21 21:12 UTC
Labels: Bug, help wanted, Area-IDE, Language-VB, IDE-IntelliSense
