### ISSUE TITLE
[Test Failure] No identified problem in prtest/win/dbg/unit64 on PR #10119

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10196] opened 2016-03-30 08:29 UTC
PR: [#10119](https://github.com/dotnet/roslyn/pull/10119) *Handle pattern-matching against Nullable<T>.* by @gafter
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5685/

**1 Test Failures:**
Microsoft.VisualStudio.LanguageServices.UnitTests.Progression.InheritsGraphQueryTests.TestSolutionWithMultipleProjects

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by davkean** [comment] 2016-03-30 16:19
Dupe of https://github.com/dotnet/roslyn/issues/9653

**Closed by davkean** 2016-03-30 16:19 UTC
Labels: Bug
