### ISSUE TITLE
Interface implementation option not available for classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73540] opened 2024-05-17 13:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Interface-implementation-option-not-avai/10660498)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.9.7]
Visual Studio does not provide an option for implementing an interface on a class. 

Repro steps:
1. Create a new WPF XAML Windows C# desktop application.
2. Add a folder to the project with the folder name Converters.
3. Add a class to convert a client's name to a more friendly display format. Class name is ClientNameDisplayConverter
4. Make the class implement the IValueConverter interface.
internal class ClientNameDisplayConverter : IValueConverter
{
        
}
5. View the error message under the currently unimplemented interface for IValueConverter. The expected behaviour is to see the error message and also a "Potential fixes" option that allows us to implement the interface. This option is available in version 17.9.7, but is missing in the 17.10.0 Preview version of Visual Studio.

---
#### Feedback Bot on 5/17/2024, 00:11 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment] 2024-06-19 01:17
(Triage) - show potential fixes only seems to show up if the cursor is on the line containing the error.  Hovering over it while the cursor is on a different line does not have it:

Cursor elsewhere:
![image](https://github.com/dotnet/roslyn/assets/5749229/0733ce28-b2eb-47ec-ada6-116dea4edea6)

Cursor on IValueConverter:
![image](https://github.com/dotnet/roslyn/assets/5749229/071a402d-55c6-4320-bd80-a481ecdf7b45)

Assigning over to Sam to take an initial look (if this is expected or not).

**Comment by CyrusNajmabadi** [comment] 2024-11-26 01:30
Closing out as htis is by design.

**Closed by CyrusNajmabadi** 2024-11-26 01:30 UTC
Labels: Area-IDE
