### ISSUE TITLE
ForAttributeWithMetadataName in IIncrementalGenerator never runs comparisons on output values

### ISSUE THREAD

**Issue by erichiller** [dotnet/roslyn#66324] opened 2023-01-09 12:56 UTC
When using `ForAttributeWithMetadataName` rather than `CreateSyntaxProvider` the output values are never checked if equal, resulting in no caching and the function specified in `RegisterSourceOutput` being run for every change which matches the `predicate`. (Code Below)

**Version Used**: 
```xml
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3" PrivateAssets="All" />
    </ItemGroup
```
```txt
dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [/usr/share/dotnet/sdk]
  7.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet/dotnet6-6.0.108]
```

**Example Code**

```cs
public class MyGenerator : IIncrementalGenerator {
    public virtual void Initialize( IncrementalGeneratorInitializationContext context ) {
        // CreateSyntaxProvider: this will hit the IntComparer
        IncrementalValuesProvider<int> createSyntaxProviderOutputValues =
                context.SyntaxProvider
                       .CreateSyntaxProvider( 
                           // simple filter for attributes
                           predicate: static ( node, _ ) => {
                               return node is ClassDeclarationSyntax { Identifier.ValueText: "TestDependentClass" };
                           },
                           // filter out attributed classes that we don't care about
                           transform: static ( syntaxContext, _ ) => {
                               return ( syntaxContext.Node as ClassDeclarationSyntax )?.Identifier.ValueText.Length ?? 33;
                           } )
                       .WithComparer( new IntComparer() );

        // this will NOT hit the IntComparer
        IncrementalValuesProvider<int> forAttributeWithMetadataNameOutputValues =
                context.SyntaxProvider
                       .ForAttributeWithMetadataName(
                           _attributeName,
                           // simple filter for attributes
                           predicate: static ( node, _ ) => {
                               return node is ClassDeclarationSyntax { Identifier.ValueText: "TestDependentClass" };
                           },
                           // filter out attributed classes that we don't care about
                           transform: static ( syntaxContext, _ ) => {
                               return ( syntaxContext.TargetNode as ClassDeclarationSyntax )?.Identifier.ValueText.Length ?? 33;
                           } ).WithComparer( new IntComparer() );

        context.RegisterSourceOutput( createSyntaxProviderOutputValues, ( SourceProductionContext sourceProductionContext, int value ) => {
            // ONLY EXECUTED ONCE
            // generate the source code and add it to the output
            string result = $"public class s_{value} {{ }}";
            sourceProductionContext.AddSource( $"CreateSyntaxProviderOutputValues_TEST_STRING_{( value )}.g.cs", SourceText.From( result, Encoding.UTF8 ) );
        } );

        context.RegisterSourceOutput( forAttributeWithMetadataNameOutputValues, ( SourceProductionContext sourceProductionContext, int value ) => {
            // EXECUTED TWICE
            // generate the source code and add it to the output
            string result = $"public class s_{value} {{ }}";
            sourceProductionContext.AddSource( $"ForAttributeWithMetadataNameOutputValues_{( value )}.g.cs", SourceText.From( result, Encoding.UTF8 ) );
        } );
}
internal class IntComparer : IEqualityComparer<int> {
    public bool Equals( int x, int y )=> x == y;
    public int GetHashCode( int obj ) => obj.GetHashCode();
}
```

Test code:
```cs

[ UsesVerify ] // Add hooks for Verify into XUnit
public class SyntaxTreeChangeTests {
    [ Fact ]
    public void NoRelevantChangeTest( ) {
        ( string original, string changed ) testClassSource = (
            /* language=cs */ """
            namespace NpgsqlEfSqlGenerator.Example {
                using System.ComponentModel.DataAnnotations;
                class TestClass {
                    public int Id { get;                                 set; }
                    public required string  Name                  { get; set; }
                    public          string? NullableReferenceType { get; set; }
                    public          int?    NullableValueType     { get; set; }
                }
            }
            """,
                              /* language=cs */ """
            namespace NpgsqlEfSqlGenerator.Example {
                using System.ComponentModel.DataAnnotations;
                class TestClass {
                    [ Key ]
                    public int Id { get;                                 set; }
                    public required string  Name                  { get; set; }
                    public          string? NullableReferenceType { get; set; }
                    public          int?    NullableValueType     { get; set; }
                }
            }
            """ );
        string testDependentClassSource =
            // original
            /* language=cs */
            """
            #nullable enable
            namespace NpgsqlEfSqlGenerator.Example {
                using System.ComponentModel.DataAnnotations;
                [ GenerateSql ]
                public class TestDependentClass {
                    [ Key ]
                    public int DependentId { get;                                 set; }
                    public required string  DependentName                  { get; set; }
                    public          string? DependentNullableReferenceType { get; set; }
                    public          int?    DependentNullableValueType     { get; set; }
                }
            }
            """;

        var compilation = TestHelper.CreateCompilation<NpgsqlEfSqlGenerator>(
            CSharpSyntaxTree.ParseText( testClassSource.original, path: "./TestClass.cs" ),
            CSharpSyntaxTree.ParseText( testDependentClassSource, path: "./TestDependentClass.cs" )
        );
        var generator = new NpgsqlEfSqlGenerator();

        GeneratorDriver driver = CSharpGeneratorDriver.Create( generator );

        driver = driver.RunGeneratorsAndUpdateCompilation( compilation, out var outputCompilation, out var diagnostics );
        // diagnostics.Should().BeEmpty();

        compilation = compilation.ReplaceSyntaxTree( compilation.SyntaxTrees[ 0 ], CSharpSyntaxTree.ParseText( testClassSource.changed, path: "./TestClass.cs" ) );
        driver = driver.RunGeneratorsAndUpdateCompilation( compilation, out outputCompilation, out diagnostics );
        diagnostics.Should().BeEmpty();
    }
}
```

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

For the `CreateSyntaxProvider` pipeline and `ForAttributeWithMetadataName` to both have their source output code run a single time when a change is not made to a matching item.

**Actual Behavior**:

For the `CreateSyntaxProvider` pipeline (see _ONLY EXECUTED ONCE_) is run once as expected as is `IntComparer.Equals`.
However for `ForAttributeWithMetadataName` (see _EXECUTED TWICE_) is run twice and `IntComparer.Equals` is never hit.

**Comment by kjkrum** [comment] 2024-04-29 23:11
I'm finding that it *does* run the comparison, it just doesn't make use of it. A transformed value is created for every symbol with the trigger attribute, and every transformed value is passed to the generator regardless of the result of the comparison.

Before I found this issue, I created a demo project: [GeneratorBug](https://github.com/kjkrum/GeneratorBug). By setting breakpoints, I confirmed that the comparer is being called and is returning the expected values. To help see what's going on without messing around with the debugger, I instrumented my `Transformed` type so the comparer could set a property indicating whether it was changed. Open up the two generated files, then open one of the classes with the trigger attribute and modify it. As expected, the corresponding generated file is marked changed and the other is not. However, both are always regenerated at the same time.

What's up with that 14-month-old PRQ?

![GeneratorBug](https://github.com/dotnet/roslyn/assets/1007080/e8c801c5-854e-49be-9729-8797b8461c46)

**Comment by kjkrum** [comment] 2024-04-29 23:16
My demo uses Microsoft.CodeAnalysis.CSharp 4.8 but I confirmed it's still an issue in 4.9.2.

**Comment by CyrusNajmabadi** [comment] 2024-04-29 23:50
> public bool Equals(SourceText x, SourceText y) => x.ContentEquals(y);

This is a very bad idea.  You're comparing hte contents of source-texts on every change.

**Comment by CyrusNajmabadi** [comment] 2024-04-29 23:51
@kjkrum The way you've written your generator, it will always regenerate for all inputs the moment one of htem has changed.  that's literallyhow you wrote that here:

```c#
		private void Generate(SourceProductionContext sourceContext, ImmutableArray<Transformed> inputs)
		{
			foreach(var input in inputs)
			{
				sourceContext.AddSource($"{input.Name}.g.cs", $"// Generated at {DateTime.Now}. [Changed: {input.Changed}]");
			}
		}
```

**Comment by CyrusNajmabadi** [comment] 2024-04-29 23:55
@kjkrum i highly recommend coming to our discord so we can help you through this.  Writing incremental generrators is hard, and it's important to get it right from the start.

**Comment by kjkrum** [comment] 2024-04-30 03:08
> You're comparing hte contents of source-texts on every change.

That's exactly my intention. Anyway, this is just a demo.

> The way you've written your generator, it will always regenerate for all inputs the moment one of htem has changed.

I thought `Collect` was only supposed to collect the changed values. In other words, an `IncrementalValuesProvider<T>` should return exactly the same `T`s with or without `Collect`. Is that not so?

**Comment by CyrusNajmabadi** [comment] 2024-04-30 03:34
> I thought Collect was only supposed to collect the changed values.

No. It collects all the values.   

Its purpose is to take an `IncrementalValuesProvider<T>` (note: 'values') and produce an `IncrementalValueProvider<ImmutableArray<T>>` (note: 'value'). 

If any of the individual values change you get an entirely new array. And you are generating sources based on *all* the values of that new array.  So of course everything regenerates for your case.  

Again, I would recommend the discord.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 03:35
> That's exactly my intention

We would strongly advise against doing this. Even if your intention, it's a bad Idea.

**Comment by kjkrum** [comment] 2024-04-30 03:50
> And you are generating sources based on _all_ the values of that new array.

As you must, or the old version of the generated file is removed from the compilation.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 03:58
> Are you sure Collect is really intended to return the unchanged values from the provider?

Pipelines don't filter out unchanged elements.  Pipelines decide when they can reuse entire next steps when all the inputs flowing into a step are unchanged.   

In your case, the inputs to a step are changing, and as such, so is the output.  You are then using the entirety of that output to generate code.  So you are seeing all the files get generated.  This is a bug in your generator.

> As you must

No, not at all.  You could generate new sources based on *each* input individually, not on hte array of inputs.  then, we'd only regenerate when the input to a single source changed.  But collecting into an array, and then generating based on that entire array, you are asking for exactly the behavior you are reporting her.e

Again, I would recommend the discord.

**Comment by kjkrum** [comment] 2024-04-30 04:08
I think we're talking past each other. You seem to be assuming I don't understand some things that I do understand.

If you don't use `Collect`, the signature of the `action` parameter to `RegisterSourceOutput` changes. Instead of the second parameter of the action being `ImmutableArray<T>`, it just becomes `T`. And it will be called once for each `T` instead of just once with an array.

But either way, shouldn't it be called with the same `T`s? If you don't use `Collect`, it's only called with the *changed* `T`s as expected. But if you do use `Collect`, the array contains both changed and unchanged `T`s. And yes, you *must* generate output for every `T` in the array or the corresponding generated source is removed from the compilation. If you have the generated file open in VS, you see an error to the effect of, "the source generator is no longer generating this file." In other words, `Collect` compels you to regenerate everything. That seems wrong to me.

Discord does not create an easily searchable and reviewable record.

**Comment by kjkrum** [comment] 2024-04-30 04:14
I actually cannot repro OP's problem with `ForAttributeWithMetadataName`. `WithComparer` is working entirely as expected once I got rid of `Collect`.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 04:25
> If you don't use Collect, the signature of the action parameter to RegisterSourceOutput changes. Instead of the second parameter of the action being ImmutableArray<T>, it just becomes T. And it will be called once for each T instead of just once with an array.

Right.  Exactly as i said.  And in line with:

> Pipelines don't filter out unchanged elements. Pipelines decide when they can reuse entire next steps when all the inputs flowing into a step are unchanged.

if you have a single element flow into a pipeline step, the same output will be produced if hte same input is produced.

By calling 'Collect' your 'single element' is now the array.  And so since a different array is being passed in, the entire pipeline step reruns.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 04:27
> But if you do use Collect, the array contains both changed and unchanged Ts.

Correct. pipeline steps always give you their outputs.  Those outputs may be values produced by prior runs, or they may be new values.  or they may be a mix as the stages of the pipeline run.

Importantly, incremental generators only stop runnign the later steps of a pipeline one a step produces the same values as the last run.  if that never happens, the later steps will continue to run.  That's literally how things work here (and how most incremental systems work).

Calling 'Collect' means instead of operating on individual values as hte units of change detection, you're operating on the entire array of values.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 04:32
> In other words, Collect compels you to regenerate everything. That seems wrong to me.

This is incorrec.t

Collect generates an array of values.  Generating sources still depends on if changed values flowed to that stage of hte pipeline.  If they did not, new sources don't need to be generated.

Note: you can see this *trivially* with how ForAttributeWithMetadataName is itself implemented.  It uses .Collect internally quite effectively exactly to map from N invidual values to 1 array value.  But despite that, generators using FAWMN rarely need to regenerate *anything* because .Collect doesn't compel you to regenerate.  You only need to regenerate if a change continues to flow down the pipeline stages and doesn't produce a cached value from a prior run.

--

Again, in your case, you are regenerating all files because that's what you are choosing to do.  Your pipeline is literally saying "if anything changes and i get a new array, i will regenerate all sources".  So the engine is exactly following your rules as you set them up, and *your* rules are forcing regeneration of everything.

if your code were implemented similar to ForAttributeWithMetadataName, it could use 'collect' and not regenerate everything.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 04:33
> Discord does not create an easily searchable and reviewable record.

Your call.  I'm not sure what else can be added here.  As long as you are write your generator as you have, then you'll get this behavior.  I'd advise against it as it's basically *not* incremental.  If you want to make it incremental, there are changes we can help you walk through that will help out here.

**Comment by kjkrum** [comment] 2024-04-30 06:02
> Your pipeline is literally saying "if anything changes and i get a new array, i will regenerate all sources".

Not quite. I expected it regenerate sources for outputs that match the `Where` on the values provider. Which outputs those are change from run to run.

On the first run, as expected, `Collect` aggregates all (and only) outputs that match the `Where`. On subsequent runs, `Collect` aggregates all outputs that *originally* matched the `Where`, even if the new versions of those outputs do not.

I still don't get why that would be intended, not to mention how it's even possible. Like, how does `Collect` identify which sources are the "same" ones that originally matched the `Where`?

**Comment by CyrusNajmabadi** [comment] 2024-04-30 06:19
> I still don't get why that would be intended

Because this is the design of incremental generators.  They work like incremental works in normal incremental compilers and build systems.

Namely that the pipeline stages move forwards, rerunning the stages if any inputs change.  When outputs are produced they are compared against the prior outputs to see if they are the same and if that can stop further steps from running.  IN your case, they're not the same, because the output is the array *itself*, not the individual values.

That's due to you using 'Collect' here in this fashion.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 06:22
>  I expected it regenerate sources for outputs that match the Where on the values provider. Which outputs those are change from run to run.

That's not how this works.  The values produced by pipeline stages are compared with prior produced values to determine if the following stages can be skipped and have their outputs directly placed in the final compilation.  In the case of individual values, this works as expected.  But when you aggregate everything into a single array, it is the array itself that is checked to see if it has changed.  In your case, it has, so that causes the next stages to run.  Since your next stages produce an output source for every element in the array, that generates the sources all over again.

Again, you've set up your pipeline to work in this fashion.  as i've mentioned a few times, you very likely do not want to do this, and our own FAWMN impl (which uses Collect) does not work in this fashion (to avoid this sort of problem as well) :)

**Comment by CyrusNajmabadi** [comment] 2024-04-30 06:27
> Like, how does Collect identify which sources are the "same" ones 

It's fairly trivial.  All the pipeline stages have inputs and outputs.  Sometimes those inputs are many-to-many  (like Select/Where). Sometimes they are many-to-one like 'Collect').  Sometimes they are one-to-many (like 'SelectMany').

All pipeline stages see what inputs are flowing in.  If the same inputs flowed in, then the pipeline stage is simply skipped.  Similarly, if the inputs are not hte same, the pipeline stage is run, and then the *outputs* are then passed along to the following stages, which then do the same check mentioned.  Once a stage sees that all its inputs are the same, then it shortcircuits and doesn't produce outputs (since it can use the ones from the last time.

So, for 'Collect', you have the 'many to one' transform.  The inputs are the individual outputs of some IncrementalValuesProvider.  And the output is the array of those inputs.  You can see that in the signature here:

```c#
public static IncrementalValueProvider<ImmutableArray<TSource>> Collect<TSource>(this IncrementalValuesProvider<TSource> source) => ...
```

So it identifies which are the same inputs by literally taking the inputs from the last time around, comparing them to the ones this time around, and seeing if they are the same.  If they're the same, the results of the Collect are shortcircuited and the same array as the prior run is used.  If they're different a new arrayis generated. 

That's it :)

**Comment by CyrusNajmabadi** [comment] 2024-04-30 06:32
`.Where(o => !o.Compared || o.Changed)`

Do not do this.  This is encoding mutable state in your pipeline, which simply will not work.  Your values must be data values operating with sane .net value-equality semantics.  Any usage of mutable data, where you mutate the values as the pipeline runs, and then check those mutated values inside your pipeline operators is *undefined* and *unsupported* behavior.

I cannot express this anymore clearly.  What you are doing is *explicitly* undefined.  Any behavior (including not running, running multiple times, crashing, or anything else) is within bounds of the generator.

**Comment by CyrusNajmabadi** [comment] 2024-04-30 06:35
@kjkrum I genuinely don't know what else i can say at this point.  I've explained (as one of the author/designers here) how this system works and why it works this way (it is very intentional).  I've explained why your generator isn't working, and why the current behavior you're seeing is expected and intentionally the design. I've given guidance on how you should write your generators to actually be incremental and how to use these APIs properly.

I'm not sure what else can be said.  Given that this seems to not be going anywhere, i'm closing out this issue.  Feel free to utilize the team resources to guide you on how to write a generator.  However, as there is no issue here in the incremental generator engine itself, and it's entirely in the authoring of yoru SG, hijacking this issue for support isn't really appropriate.

I look forward to hearing from you on discord, or another support venue.  Thanks!

**Closed by CyrusNajmabadi** 2024-04-30 06:35 UTC
Labels: Bug, Area-Compilers
