### ISSUE TITLE
Visual Studio crashed after switching Roslyn branches

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10515] opened 2016-04-12 22:26 UTC
Have Roslyn.sln open, swtiched from future -> master, and Visual Studio crashed in the background.

Stack:

```
>	
IndexOutOfRangeException {"Index was outside the bounds of the array."}
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Solution.CompilationTracker.GetMetadataOnlyImageReferenceAsync(Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.ProjectReference projectReference, System.Threading.CancellationToken cancellationToken)	Unknown
 	[Native to Managed Transition]	
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol typeToTest)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.VisualBasic.Symbol> visited, Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol root, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol current)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.VisualBasic.Symbol> visited, Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol root, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol current)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol this, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol base)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.BaseTypeNoUseSiteDiagnostics.get()	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.VisualBasic.Symbol> basesBeingResolved)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.VisualBasic.Symbol> basesBeingResolved, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(Microsoft.CodeAnalysis.VisualBasic.LookupResult result, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol container, string name, int arity, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol accessThroughType, Microsoft.CodeAnalysis.VisualBasic.Binder binder, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol type, string name, int arity, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, Microsoft.CodeAnalysis.VisualBasic.Binder binder, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol container, string name, int arity, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, string name, int arity, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, Microsoft.CodeAnalysis.VisualBasic.Binder originalBinder, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.Lookup(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, string name, int arity, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, ref System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.DiagnosticInfo> useSiteDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupBasicName(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax basicNameSyntax, Microsoft.CodeAnalysis.VisualBasic.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagBag, ref bool reportedAnError)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupTypeOrNamespaceSyntax(Microsoft.CodeAnalysis.VisualBasic.LookupResult lookupResult, Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.VisualBasic.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagBag, ref bool reportedAnError, bool unwrapAliases, bool suppressUseSiteError, bool inGetTypeContext, bool resolvingBaseType)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.VisualBasic.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagBag, bool suppressUseSiteError, bool inGetTypeContext, bool resolvingBaseType)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeFieldType(Microsoft.CodeAnalysis.VisualBasic.Syntax.ModifiedIdentifierSyntax modifiedIdentifierSyntax, Microsoft.CodeAnalysis.VisualBasic.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, bool isConst, bool isWithEvents, bool ignoreTypeSyntaxDiagnostics)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.GetDeclaredType(Microsoft.CodeAnalysis.DiagnosticBag diagBag)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeType(Microsoft.CodeAnalysis.DiagnosticBag diagBag)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.Type.get()	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFieldSymbol.GenerateDeclarationErrors(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-0._Lambda$__1(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceOrTypeSymbol typeOrNamespace)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.VisitTypesAndNamespacesWithin(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceOrTypeSymbol ns, System.Action<Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceOrTypeSymbol> visitor, System.Collections.Concurrent.ConcurrentStack<System.Threading.Tasks.Task> tasks, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetAllDeclarationErrors(System.Threading.CancellationToken cancellationToken, ref bool hasExtensionMethods)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.GetAllDeclarationErrors(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(Microsoft.CodeAnalysis.CompilationStage stage, bool includeEarlierStages, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, bool emittingPdb, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate<Microsoft.CodeAnalysis.ISymbol> filterOpt, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Compilation.Compile(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, bool emittingPdb, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate<Microsoft.CodeAnalysis.ISymbol> filterOpt, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Compilation.Emit(Microsoft.CodeAnalysis.Compilation.EmitStreamProvider peStreamProvider, Microsoft.CodeAnalysis.Compilation.EmitStreamProvider pdbStreamProvider, Microsoft.CodeAnalysis.Compilation.EmitStreamProvider xmlDocumentationStreamProvider, Microsoft.CodeAnalysis.Compilation.EmitStreamProvider win32ResourcesStreamProvider, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ResourceDescription> manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, Microsoft.CodeAnalysis.IMethodSymbol debugEntryPoint, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData, System.Func<System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic>> getHostDiagnostics, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream peStream, System.IO.Stream pdbStream, System.IO.Stream xmlDocumentationStream, System.IO.Stream win32Resources, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ResourceDescription> manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, Microsoft.CodeAnalysis.IMethodSymbol debugEntryPoint, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData, System.Func<System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic>> getHostDiagnostics, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream peStream, System.IO.Stream pdbStream, System.IO.Stream xmlDocumentationStream, System.IO.Stream win32Resources, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ResourceDescription> manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, Microsoft.CodeAnalysis.IMethodSymbol debugEntryPoint, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.MetadataOnlyImage.Create(Microsoft.CodeAnalysis.Host.ITemporaryStorageService service, Microsoft.CodeAnalysis.Compilation compilation, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.ProjectReference projectReference, Microsoft.CodeAnalysis.Compilation finalCompilation, Microsoft.CodeAnalysis.VersionStamp version, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Solution.CompilationTracker.GetMetadataOnlyImageReferenceAsync(Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.ProjectReference projectReference, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<Microsoft.CodeAnalysis.VersionStamp>.TrySetResult(Microsoft.CodeAnalysis.VersionStamp result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.CodeAnalysis.VersionStamp>.SetResult(Microsoft.CodeAnalysis.VersionStamp result)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Solution.CompilationTracker.GetDependentSemanticVersionAsync(Microsoft.CodeAnalysis.Solution solution, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<Microsoft.CodeAnalysis.VersionStamp>.TrySetResult(Microsoft.CodeAnalysis.VersionStamp result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.CodeAnalysis.VersionStamp>.SetResult(Microsoft.CodeAnalysis.VersionStamp result)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.VersionStamp>.Request.CompleteFromTaskSynchronously(System.Threading.Tasks.Task<Microsoft.CodeAnalysis.VersionStamp> task)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.VersionStamp>.Request.CompleteFromTaskSynchronouslyStub(object task)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

**Comment by davkean** [comment] 2016-04-12 22:27
Dump: \\[teamshare]\public\davkean\10515

**Comment by Pilchie** [comment] 2016-04-12 22:32
+ @TyOverby.  Isn't this a dupe of something you were looking at?

**Comment by TyOverby** [comment] 2016-04-13 22:50
Dupe of #10211

**Closed by TyOverby** 2016-04-13 22:50 UTC
Labels: Area-Compilers
