### ISSUE TITLE
C# code snippet for region violating document EOL sequence

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58134] opened 2021-12-06 18:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-code-snippet-for-region-violating-doc/1603974)._

---
# Repro
A Visual Studio Solution with .editorconfig containing
```
[*.cs]
end_of_line = lf
insert_final_newline = true
```

A C# Project within said Solution.

A C# Source code file in said Project.

Said C# file shall contain some code.

Said code shall contain only LF EOL-sequences.
This can be verified by looking at the View's EOL indicator at view bottom-right. That indicator shall display `LF`. If it displays anything but `LF`, click on it. This operation shall open a pop-up selection with at least three choices. One of those three choices shall be `LF`. Click on the choice `LF`. If required, repeat until the indicator displays `LF`.

On the last line in said C# source file, type `#re`. You should now be presented with a "Code snippet" for `#region`.

Press the Tab key twice, to insert said "Code snippet".

You should now see
```
#region | MyRegion$|

#endregion
```
where the pipe characters denotes active selection and `$` denotes cursor position.

# Expected
The "snippet" to respect
1. The EOL sequence of the document. This shall be the primary defining EOL sequence.
2. In case the document contains no EOL sequences at all, an existing .editorconfig setting shall be obeyed.
3. the `insert_final_newline` setting.

# Actual
- The "snippet" inserts (probably hardcoded) malforming CRLF, making the EOL indicator display `MIXED`. indicating the document has been corrupted by this snippet.
- The snippet does not terminate the document with a newline sequence (it doesn't even terminate _itself_ with a newline sequence), which violates the explicitly specified .editorconfig setting.

\
This behavior violates all three of the listed expectations, where point 1 should be implicitly obvious (i.e. not needed to spell out), and points 2 and 3 which are _explicitly_ spelled out by being specified in .editorconfig.

This experience is considerably less than satisfying.

---
#### Feedback Bot on 12/5/2021, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/6/2021, 09:41 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-12-06 18:40
Duplicate of #28638

**Closed by sharwell** 2021-12-06 18:40 UTC
Labels: Area-IDE, untriaged
