### ISSUE TITLE
.editorconfig csharp_new_line_before_open_brace is wrong with switch expression

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#45780] opened 2020-07-08 14:08 UTC
I configure my `.editorconfig` to require K&R-style braces and produce a warning if they're wrong:

```
# IDE0055: Fix formatting
dotnet_diagnostic.IDE0055.severity = warning

# K&R-style braces
csharp_new_line_before_open_brace = none
```

However, Allman-style braces are still enforced with a warning for a switch expression such as:

```
int input = 123;

bool result = input switch {
    246 => true,
    _ => false
};
```

**Comment by vatsalyaagrawal** [comment] 2020-07-08 16:36
Duplicate of #36913

**Closed by vatsalyaagrawal** 2020-07-08 16:36 UTC
