### ISSUE TITLE
Portable library properties page fails to load when the project contains a project.json that cannot be parsed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9487] opened 2016-03-04 16:40 UTC
See: https://twitter.com/mteper/status/705241495574413312

```

{
  "supports": {},
  "dependencies": {},
  "frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile7": {},
    "net45+win": {
      "wrappedProject": "Foo.Dto.csproj",
      "bin": {
        "assembly": "obj/{configuration}/Foo.Dto.dll",
        "pdb": "obj/{configuration}/Foo.Dto.pdb"
      }
    }
  },
  "version": "1.0.0-*"
}
```

**Comment by Pilchie** [comment] 2016-03-04 18:44
Is this a dupe of something already fixed in 1.2?

**Comment by rchande** [comment] 2016-09-19 19:34
@rchande Is this fixed?

**Comment by Pilchie** [comment] 2016-11-02 02:00
If not, at this point I think maybe we should just have a dialog explaining why it fails to load?

**Comment by Pilchie** [comment] 2017-01-19 17:26
Closing, as we're phasing out project.json anyway.

**Closed by Pilchie** 2017-01-19 17:26 UTC
Labels: Area-IDE, Bug
