### ISSUE TITLE
Intellisense does not work after updating to 17.10.0 Preview 3.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73023] opened 2024-04-15 13:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-does-not-work-after-updatin/10638506)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.10.0 preview 2]
After updating to Visual Studio 17.10.0 Preview 3 my intellisense was not able to handle complex datatypes like keyvaluepairs or properties vom the mvvm communitytoolkit

For example the calculation class has a property called SellingPrice and as you can see it exists.
But Intellisense does not suggest the property as shown in the screenshot below.
![B13b3fe358abb40e280f263781ec6fd08638487588159382542_20240415-082014-image](https://github.com/dotnet/roslyn/assets/1408396/b17615b9-6cf2-4cf5-bbf8-b9e67138eea8)

The model class Calculations:
![B7a34617321994ca998df230def1569d6638487588605065493_20240415-082100-image](https://github.com/dotnet/roslyn/assets/1408396/23e52223-6eaa-4191-aac5-09a58dd50e0c)

With the previous versions this worked great.
Unfortunately a rollback to preview 2 did not fix this wrong behavior.

I already made a repair installation and also cleared the cache for intellisense in the local appdata directory.
Also i tried to roll back to the previous version but nothing fixed this.

---
#### Feedback Bot on 4/15/2024, 01:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-04-15 15:07
@genlu ptal.

**Comment by genlu** [comment] 2024-04-23 23:27
@CyrusNajmabadi looks like those properties are generated by SG? Any recent change around it that would impact completion?

**Comment by CyrusNajmabadi** [comment] 2024-04-23 23:46
Yes.  Completion uses frozen-partial-semantics.  And those will absolutely not have SG results if they haven't been computed.  Sounds like this may just be by design due to the nature of SG results not being reliably present in frozen-partial scenarios.

**Comment by genlu** [comment] 2024-04-24 00:30
I think what makes it confusing is referencing generated code in the screenshot above isn't an error. So SG results are available in OOP but not devenv?

**Comment by CyrusNajmabadi** [comment] 2024-04-24 00:34
> I think what makes it confusing is referencing generated code in the screenshot above isn't an error. So SG results are available in OOP but not devenv?

I'm not exactly sure what your question is asking.  However, diagnostics/errors are very different from completion.  The former doesn't use frozen-partial, exactly so it can get correct results.  Completion, on the other hand, uses frozen-partial for speed, as it has to meet its latency goals, which it couldn't if it had to run generators.

**Comment by weiyoucheng** [comment] 2024-08-08 13:42
I also have this issue after upgrading to 17.10

**Comment by CyrusNajmabadi** [comment] 2024-08-08 14:43
@weiyoucheng can you please supply a repro?

**Comment by weiyoucheng** [comment] 2024-08-11 07:10
> 你能提供一个复制品吗？
![image](https://github.com/user-attachments/assets/cc9b18b7-d2a3-4345-868f-86e94f9d2bf8)
The "EwbNo" property generated by the source code generator does not appear in the IntelliSense list, while the "HasErrors" member of the base class ObservableValidator is displayed normally.

**Comment by weiyoucheng** [comment] 2024-08-11 07:14
![image](https://github.com/user-attachments/assets/9610f1de-b915-47eb-88ba-fb708918bb58)

**Comment by weiyoucheng** [comment] 2024-08-11 07:16
![image](https://github.com/user-attachments/assets/0b87f1a0-4b22-4028-86b1-398dd3e1e57c)
visual studio version info.

**Comment by CyrusNajmabadi** [comment] 2024-11-26 01:12
Closing out as these are generators, and it is part of the design that IDE features may not include all data produced by generators due to perf costs.

**Closed by CyrusNajmabadi** 2024-11-26 01:12 UTC
Labels: Area-IDE
