### ISSUE TITLE
SyntaxGenerator.Argument doesn't generate RefKind.In properly

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#66118] opened 2022-12-24 14:12 UTC
```c#
var workspace = new AdhocWorkspace();
var syntaxGenerator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);

var invocation = syntaxGenerator.InvocationExpression(
    syntaxGenerator.IdentifierName("func"),
    syntaxGenerator.Argument(RefKind.None, syntaxGenerator.IdentifierName("noneParam")),
    syntaxGenerator.Argument(RefKind.In, syntaxGenerator.IdentifierName("inParam")),
    syntaxGenerator.Argument(RefKind.Out, syntaxGenerator.IdentifierName("outParam")),
    syntaxGenerator.Argument(RefKind.Ref, syntaxGenerator.IdentifierName("refParam")),
    syntaxGenerator.Argument(RefKind.RefReadOnly, syntaxGenerator.IdentifierName("refReadOnlyParam")));

Console.WriteLine(invocation.NormalizeWhitespace().ToFullString());
```

This outputs:

```
func(noneParam, inParam, out outParam, ref refParam, refReadOnlyParam)
```

Should inParam be prefixed with an `in` token, just like outParam is prefixed with an `out`? If not, is there some other method for generating `in` parameters with SyntaxFactory?

The [relevant code](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L203) in CSharpSyntaxGenerator:

```c#
internal static SyntaxToken GetArgumentModifiers(RefKind refKind)
{
    switch (refKind)
    {
        case RefKind.None:
        case RefKind.In:
            return default;
        case RefKind.Out:
            return SyntaxFactory.Token(SyntaxKind.OutKeyword);
        case RefKind.Ref:
            return SyntaxFactory.Token(SyntaxKind.RefKeyword);
        default:
            throw ExceptionUtilities.UnexpectedValue(refKind);
    }
}
```

**Comment by Youssef1313** [comment] 2022-12-24 14:50
> If not, is there some other method for generating in parameters with SyntaxFactory?

Yes, it's possible to produce anything node that the parser can produce using `SyntaxFactory`. [Roslyn Quoter](http://roslynquoter.azurewebsites.net/) and SharpLab can help with that.

@kinkeadian25 You might be interested in contributing a fix here :)

**Comment by roji** [comment] 2022-12-24 15:55
@Youssef1313 oh sure, I know I can use SyntaxFactory (and have done a lot with that). I'm just wondering if this is a bug in SyntaxGenerator or whether I've misunderstood something.

One reason I prefer SyntaxGenerator - beyond it being generally simpler and less verbose - is the automatic addition of parentheses to preserve evaluation order when the tree is output as C# text; with SyntaxFactory this has to be done manually, unless I'm mistaken.

**Comment by CyrusNajmabadi** [comment] 2022-12-24 16:56
An argument doesn't need `in` to be specified, which is likely why we don't include it here.

**Comment by roji** [comment] 2022-12-24 17:16
@CyrusNajmabadi right, but the [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier#overload-resolution-rules) on `in` do specify two reasons why one might want to explicitly specify the keyword (force the compiler to select an `in` method when there are multiple overloads, clarity of intent) - shouldn't it be possible to do that with SyntaxGenerator?

Asked the other way - when the user took the trouble to explicitly specify RefKind.In (as opposed to just defaulting to None), is there a good reason to omit it?

**Comment by CyrusNajmabadi** [comment] 2022-12-24 17:48
I think the premise was that this was copied over from the parameter and we didn't want to have the consumer of the API have to strip this off

**Comment by roji** [comment] 2022-12-24 20:20
@CyrusNajmabadi does it make sense for the Simplifier to strip it off when it's not needed (i.e. when the semantic model indicates that the actual method parameter isn't an in parameter)? After all, SyntaxGenerator already generates lots of "unneeded" stuff (like parentheses) which get stripped out later.

**Comment by CyrusNajmabadi** [comment] 2022-12-24 20:58
Yup yup. That would make perfect sense.

**Comment by kinkeadian25** [comment] 2022-12-24 21:45
@CyrusNajmabadi, @Youssef1313, @roji, I dont mind working on this if none of you are interested! Thanks!

**Comment by CyrusNajmabadi** [comment] 2024-11-22 20:28
Closing out due to lack of movement.  Currently, this is all working as intended.

**Closed by CyrusNajmabadi** 2024-11-22 20:28 UTC
Labels: help wanted, Area-IDE

**Comment by kinkeadian25** [comment] 2024-11-24 16:59
@CyrusNajmabadi, anything in particular to work on? just help wanted tags? this inspired me!

**Comment by CyrusNajmabadi** [comment] 2024-11-24 18:38
Well, we'd need an API proposal first on this. :-)
