### ISSUE TITLE
Closure may be unnecessarily split

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#29965] opened 2018-09-17 21:01 UTC
**Version Used**: 
2.8.2 / master (17th September 2018)

**Steps to Reproduce**:
[Using following code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACh0tsAWAwolAZlIDYsAmUgdiIG8iMes6dGKMhgCyEAJYA7ABQBKbry6FeKjADcICDGACeOJlAwBeDJLgB3DABlxsADz6AfHMqreGrboDKMBFIDmhiZmljb2OGjOshgcGABEAPZmcQA08TDmCanpABYIcHBxGAC+lApuAGYJWtIeGOLGGGi49Rh22jo+fpKBAHQAwgkArpIwLeIA1BPyym4x5XM8+hgADt0wjXLGjjGkAJzS3r4BUADa4gC6si2lC4u6+lC9AIIAJq/Sa1Iw13e8xUQ/jwHtgDKc0BcXAsAYQYUA=) will unnecessarily produce two nested closures.
```csharp
using System;
using System.Collections.Generic;

public static class Program
{
    public static void Main()
    {
        var myActions = new List<Action>();
        var myStrings = new List<string>() { "one", "two", "three" };

        for (var i = 0; i < myStrings.Count; i++)
        {
            Action print = () => { Console.WriteLine(myStrings[i]); };
            myActions.Add(print);
        }

        myActions[0]();
    }
}
```

**Expected Behavior**:
```csharp
public static class Program
{
    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_1
    {
        public int i;

        public List<string> myStrings;

        internal void <Main>b__0()
        {
            Console.WriteLine(myStrings[i]);
        }
    }

    public static void Main()
    {
        List<Action> list = new List<Action>();
        List<string> list2 = new List<string>();
        list2.Add("one");
        list2.Add("two");
        list2.Add("three");
        <>c__DisplayClass0_1 closure = new <>c__DisplayClass0_1();
        closure.myStrings = list2;
        closure.i = 0;
        while (closure.i < closure.myStrings.Count)
        {
            Action item = closure.<Main>b__0;
            list.Add(item);
            closure.i++;
        }
        list[0]();
    }
}
```

**Actual Behavior**:
```csharp
public static class Program
{
    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_0
    {
        public List<string> myStrings;
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_1
    {
        public int i;

        public <>c__DisplayClass0_0 CS$<>8__locals1;

        internal void <Main>b__0()
        {
            Console.WriteLine(CS$<>8__locals1.myStrings[i]);
        }
    }

    public static void Main()
    {
        <>c__DisplayClass0_0 <>c__DisplayClass0_ = new <>c__DisplayClass0_0();
        List<Action> list = new List<Action>();
        <>c__DisplayClass0_0 <>c__DisplayClass0_2 = <>c__DisplayClass0_;
        List<string> list2 = new List<string>();
        list2.Add("one");
        list2.Add("two");
        list2.Add("three");
        <>c__DisplayClass0_2.myStrings = list2;
        <>c__DisplayClass0_1 <>c__DisplayClass0_3 = new <>c__DisplayClass0_1();
        <>c__DisplayClass0_3.CS$<>8__locals1 = <>c__DisplayClass0_;
        <>c__DisplayClass0_3.i = 0;
        while (<>c__DisplayClass0_3.i < <>c__DisplayClass0_3.CS$<>8__locals1.myStrings.Count)
        {
            Action item = <>c__DisplayClass0_3.<Main>b__0;
            list.Add(item);
            <>c__DisplayClass0_3.i++;
        }
        list[0]();
    }
}
```

**Comment by gafter** [comment] 2018-12-12 00:36
Your expected program has the incorrect behavior, as all the lambdas will be sharing the same `i` variable.

**Comment by gafter** [comment] 2018-12-12 01:42
@Suchiman My mistake - I see it is a `for` loop and not a `foreach` loop (which would create a new variable each iteration).

**Comment by gafter** [comment] 2018-12-12 01:43
We create a separate closure for each scope.  That is by design.  I don't think we can change the design since some programs depend on it (if we put variables in the same closure, keeping one of them alive causes the other to remain alive for GC purposes).

**Comment by Suchiman** [comment] 2018-12-12 02:09
In this case though, the lifetime is identical so this optimization should only apply when it is beneficial, in the case above, it only generates additional overhead.

**Comment by gafter** [comment] 2018-12-12 17:51
OK, I'll leave this open just in case someone wants to contribute a way of doing it that would not undermine existing clients.

**Comment by YairHalberstadt** [comment] 2018-12-23 13:56
I've experimented with this a little, and I think there may be a relatively simple solution.

In `LambdaRewriter.MakeAndAssignEnvironments` we replace this:

```csharp
// Next create the environment and add it to the declaration scope
var env = new ClosureEnvironment(variablesInEnvironment, isStruct);
scope.DeclaredEnvironments.Add(env);
```

With this

```csharp
ClosureEnvironment env = null;
if (scope.BoundNode.Syntax.Kind() == SyntaxKind.ForStatement &&
    scope.Parent.DeclaredEnvironments.Count > 0)
{
    // Right now we only create one environment per scope
    Debug.Assert(scope.Parent.DeclaredEnvironments.Count == 1);
    var parentEnv = scope.Parent.DeclaredEnvironments[0];
    if (parentEnv.IsStruct == isStruct)
    {
        // We can use the parent environment since it has the same lifetime
        env = parentEnv;
        foreach (var variable in variablesInEnvironment)
        {
            env.CapturedVariables.Add(variable);
        }
    }
}
if (env is null)
{
    // Next create the environment and add it to the declaration scope
    env = new ClosureEnvironment(variablesInEnvironment, isStruct);
    scope.DeclaredEnvironments.Add(env);
}
```

If @gafter thinks this is a suitable direction to go in, I'm happy to implement this.

**Comment by YairHalberstadt** [comment] 2018-12-23 21:45
I also see the opposite problem occur with a foreach loop:

*Version Used:*
2.9.0

*Steps to Reproduce:*
Using following code will unnecessarily produce two nested closures.

```csharp

public static class Program
{
    public static void Main()
    {
        var myActions = new List<Action>();
        var myStrings = new List<string>() { "one", "two", "three" };

        foreach(var str in myStrings)
        {
            var x = 0;
            Action print = () => { Console.WriteLine(str + x); };
            myActions.Add(print);
        }

        myActions[0]();
    }
}
```

*Expected Behaviour:*

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[assembly: AssemblyVersion("0.0.0.0")]
[module: UnverifiableCode]
public static class Program
{
    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_0
    {
        public string str;

        public int x;

        internal void <Main>b__0()
        {
            Console.WriteLine(str + x);
        }
    }

    public static void Main()
    {
        List<Action> list = new List<Action>();
        List<string> list2 = new List<string>();
        list2.Add("one");
        list2.Add("two");
        list2.Add("three");
        List<string> list3 = list2;
        List<string>.Enumerator enumerator = list3.GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                <>c__DisplayClass0_0 <>c__DisplayClass0_ = new <>c__DisplayClass0_0();
                <>c__DisplayClass0_.str = enumerator.Current;
                <>c__DisplayClass0_.x = 0;
                Action item = <>c__DisplayClass0_.<Main>b__0;
                list.Add(item);
            }
        }
        finally
        {
            ((IDisposable)enumerator).Dispose();
        }
        list[0]();
    }
}
```

*Actual Behaviour:*
```csharp
public static class Program
{
    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_0
    {
        public string str;
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_1
    {
        public int x;

        public <>c__DisplayClass0_0 CS$<>8__locals1;

        internal void <Main>b__0()
        {
            Console.WriteLine(CS$<>8__locals1.str + x);
        }
    }

    public static void Main()
    {
        List<Action> list = new List<Action>();
        List<string> list2 = new List<string>();
        list2.Add("one");
        list2.Add("two");
        list2.Add("three");
        List<string> list3 = list2;
        List<string>.Enumerator enumerator = list3.GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                <>c__DisplayClass0_0 <>c__DisplayClass0_ = new <>c__DisplayClass0_0();
                <>c__DisplayClass0_.str = enumerator.Current;
                <>c__DisplayClass0_1 <>c__DisplayClass0_2 = new <>c__DisplayClass0_1();
                <>c__DisplayClass0_2.CS$<>8__locals1 = <>c__DisplayClass0_;
                <>c__DisplayClass0_2.x = 0;
                Action item = <>c__DisplayClass0_2.<Main>b__0;
                list.Add(item);
            }
        }
        finally
        {
            ((IDisposable)enumerator).Dispose();
        }
        list[0]();
    }
}
```

I believe this could be solved in a similar manner - if a parent scope is a foreach loop, and a closure environment already exists for the parent scope, use the parent scope for any captured variables.

**Comment by YairHalberstadt** [comment] 2018-12-23 21:47
Are there any other cases where this issue occurs? that is two scopes have the same lifetime, but captured variables in both scopes will have different display classes?

**Comment by YairHalberstadt** [comment] 2018-12-23 21:54
Another case: using statements

```csharp
using System;
using System.Collections.Generic;

public static class Program
{
    public class Disposable : IDisposable
    {
        public void Dispose(){}
    }
    
    public static void Main()
    {
        var myActions = new List<Action>();
        var str = "string";

        using(var disposable = new Disposable())
        {
            Action print = () => { Console.WriteLine(disposable.ToString() + str); };
            myActions.Add(print);
        }

        myActions[0]();
    }
}
```

**Expected Behaviour**
```csharp
public static class Program
{
    public class Disposable : IDisposable
    {
        public void Dispose()
        {
        }
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass1_0
    {
        public string str;

        public Disposable disposable;

        internal void <Main>b__0()
        {
            Console.WriteLine(disposable.ToString() + str);
        }
    }

    public static void Main()
    {
        <>c__DisplayClass1_0 <>c__DisplayClass1_ = new <>c__DisplayClass1_0();
        List<Action> list = new List<Action>();
        <>c__DisplayClass1_.str = "string";
        <>c__DisplayClass1_.disposable = new Disposable();
        try
        {
            Action item = <>c__DisplayClass1_.<Main>b__0;
            list.Add(item);
        }
        finally
        {
            if (<>c__DisplayClass1_.disposable != null)
            {
                ((IDisposable)<>c__DisplayClass1_.disposable).Dispose();
            }
        }
        list[0]();
    }
}
```
**Actual Behaviour**
```csharp
public static class Program
{
    public class Disposable : IDisposable
    {
        public void Dispose()
        {
        }
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass1_0
    {
        public string str;
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass1_1
    {
        public Disposable disposable;

        public <>c__DisplayClass1_0 CS$<>8__locals1;

        internal void <Main>b__0()
        {
            Console.WriteLine(disposable.ToString() + CS$<>8__locals1.str);
        }
    }

    public static void Main()
    {
        <>c__DisplayClass1_0 <>c__DisplayClass1_ = new <>c__DisplayClass1_0();
        List<Action> list = new List<Action>();
        <>c__DisplayClass1_.str = "string";
        <>c__DisplayClass1_1 <>c__DisplayClass1_2 = new <>c__DisplayClass1_1();
        <>c__DisplayClass1_2.CS$<>8__locals1 = <>c__DisplayClass1_;
        <>c__DisplayClass1_2.disposable = new Disposable();
        try
        {
            Action item = <>c__DisplayClass1_2.<Main>b__0;
            list.Add(item);
        }
        finally
        {
            if (<>c__DisplayClass1_2.disposable != null)
            {
                ((IDisposable)<>c__DisplayClass1_2.disposable).Dispose();
            }
        }
        list[0]();
    }
}
```

**Comment by YairHalberstadt** [comment] 2018-12-23 21:59
In the foreach case I believe this is probably the most important, since you halve the amount of garbage created on every iteration of the loop, and also simplify the logic inside the loop.

I am going to try doing some benchmarking to see how much of a performance impact this could theoretically make.

**Comment by Suchiman** [comment] 2018-12-23 22:47
I think it makes sense to look at the case where this optimization actually benefits:
**Source**:
```csharp
using System;
using System.Collections.Generic;

public class C
{
    public void M(String top, int test)
    {
        var actions = new List<Func<string>>();
        if (test > 1)
        {
            var x1 = Console.ReadLine();
            if (test > 2)
            {
                var x2 = Console.ReadLine();
            	actions.Add(() => x1 + x2 + top);
            }
        }
        
        if (test > 3)
        {
            var y1 = Console.ReadLine();
            actions.Add(() => y1 + top);
        }
    }
}
```

**Codegen**:
```csharp
public class C
{
    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_0
    {
        public string top;
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_1
    {
        public string x1;

        public <>c__DisplayClass0_0 CS$<>8__locals1;
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_2
    {
        public string x2;

        public <>c__DisplayClass0_1 CS$<>8__locals2;

        internal string <M>b__0()
        {
            return CS$<>8__locals2.x1 + x2 + CS$<>8__locals2.CS$<>8__locals1.top;
        }
    }

    [CompilerGenerated]
    private sealed class <>c__DisplayClass0_3
    {
        public string y1;

        public <>c__DisplayClass0_0 CS$<>8__locals3;

        internal string <M>b__1()
        {
            return y1 + CS$<>8__locals3.top;
        }
    }

    public void M(string top, int test)
    {
        <>c__DisplayClass0_0 <>c__DisplayClass0_ = new <>c__DisplayClass0_0();
        <>c__DisplayClass0_.top = top;
        List<Func<string>> list = new List<Func<string>>();
        if (test > 1)
        {
            <>c__DisplayClass0_1 <>c__DisplayClass0_2 = new <>c__DisplayClass0_1();
            <>c__DisplayClass0_2.CS$<>8__locals1 = <>c__DisplayClass0_;
            <>c__DisplayClass0_2.x1 = Console.ReadLine();
            if (test > 2)
            {
                <>c__DisplayClass0_2 <>c__DisplayClass0_3 = new <>c__DisplayClass0_2();
                <>c__DisplayClass0_3.CS$<>8__locals2 = <>c__DisplayClass0_2;
                <>c__DisplayClass0_3.x2 = Console.ReadLine();
                list.Add(<>c__DisplayClass0_3.<M>b__0);
            }
        }
        if (test > 3)
        {
            <>c__DisplayClass0_3 <>c__DisplayClass0_4 = new <>c__DisplayClass0_3();
            <>c__DisplayClass0_4.CS$<>8__locals3 = <>c__DisplayClass0_;
            <>c__DisplayClass0_4.y1 = Console.ReadLine();
            list.Add(<>c__DisplayClass0_4.<M>b__1);
        }
    }
}
```

Following behavior can be observed:
From each declaration of a closuring lambda expression, moving from inner to outer scopes, each scope it traverses will generate a dedicated closure object.
This is obviously inefficient.
The optimal codegen strategy, preserving the optimized GC behavior, would be to inline single-use closures from outer to inner.
Additionally a fast path can be used where there is only a single lambda expression declaration to merge everything into a single closure.

Another possible optimization would be to not create closure objects for multi-use outer scope closures if they are either readonly variables or write-once (might need an exception for large user defined structs).

**Comment by gafter** [comment] 2018-12-24 01:54
Looking at the proposal in https://github.com/dotnet/roslyn/issues/29965#issuecomment-449638005, I'm wondering why a solution should be specific to a `for` loop?  What about a `using` statement?  Or a `{}` block containing declarations?  Or any other sequential construct with controlled statements?  It isn't clear to me what is special about a for loop.

**Comment by YairHalberstadt** [comment] 2018-12-24 06:20
@gafter
Agreed. At that point I hadn't realised this could occur with more than for loops. But indeed, I will try and work out under exactly which circumstances this is safe to do.

**Comment by YairHalberstadt** [comment] 2018-12-24 10:04
I think I'm going to start off by writing some unit tests asserting the current garbage collecting behaviour of closures. Then I will try to optimise the selection of env.

I think in general the rules should be:

1. variables declared inside a for loop, should not use the parent scopes environment
2. The variables declared by the for construct (i.e. x in `for(var x = ...; ... ; ...)`) should use the parents scopes environment
3. The variable declared by a foreach construct (i.e. x in `foreach( var x in ...)`) should not use the parent scopes environment
4. the variables declared inside a foreach loop should use the parent scopes environment ( i.e. the scope of the variable declared by the foreach construct)
5. a variable declared inside an `if` or a `then` statement should not use the parent scopes environment, as otherwise it will cause the creation of a display class even when the branch is not taken
6. a `{}` block should use the parent scopes environment
7. variables declared inside a while loop should not use the parent scopes environment
8. variables inside a try block should use the parent scopes environment
9. variables inside a catch or finally block should not use the parent scopes environment, as otherwise it will cause the creation of a display class even when the branch is not taken
10. variables declared by or inside a using block should use the parent scopes environment

Is there anything I've missed?

This should work recursively. So if we move something to the parent scopes environment, we can then move it to that scope's parent's  scope's environment.

#### Preventing changes in GC

We need to watch out for cases where doing this will prevent GC of objects which could previously have been garbage collected. For example:

```csharp
using System;

public Action M()
{
	var str = "";
	Action act0 = () => Console.WriteLine(str);
	{
		var str1 = "";
		Action act1 = () => Console.WriteLine(str1);
	}

return act0;
}
```

Currently `str1` can be collected once M returns. However if we were to use the same display class for both `str1` and `str2` str1 would live however long act0 does.

Under the trivial case where a parent scope only contains one closure I think it will always be safe to move display classes to the parent scope. Also if all lambdas declared inside the scope have their methods declared in the same display class, it should also be safe to do so.

If we can prove that all lambdas in a parent scope have the same lifetime it may also be possible to do so. However this would require significantly more effort, and in general is very difficult to prove. I think we should just attempt to solve the trivial cases initially.

@Suchiman 
I don't think in the general case it will be possible to optimize closures captured by an if statement. In some cases it may be possible to move a variable that's declared outside the if statement, but is only used inside the if statement to the scope inside of the if statement, but that's rare enough that I don't think it's worth making that an exceptional case.

**Comment by gafter** [comment] 2018-12-24 20:12
@YairHalberstadt Please keep in mind the fact that this
``` c#
while (condition)
{
    something;
}
```
should behave exactly the same as this:
``` c#
retry:
if (condition)
{
    something;
    goto retry;
}
```
Specifically, in both cases variables declared inside `something` and also captured in a lambda should get a new instance for each entry into that block.  If you share with the parent scope you will get the wrong behavior.  This applies to the for loop as well (if the body of the for loop jumps back to before the for loop, you should get a new instance of the for loop's variables when you reenter the for loop).  Your proposed change appears to get that wrong.

**Comment by YairHalberstadt** [comment] 2018-12-24 20:18
I forgot about about jumps. They make life far trickier, don't they...

**Comment by gafter** [comment] 2018-12-24 20:48
It is only backward `goto`s that are an issue. They are more rare than `goto`s.

**Comment by YairHalberstadt** [comment] 2018-12-30 08:36
The algorithm I'm using to avoid keeping anything alive longer than it would have been previously is:

If there are any closures that reference the display-class in the parent-scope, but not the display-class in the child-scope, the child display-class cannot be merged into the parent display-class.

This is because keeping the closure that references the parent display-class but not the child display-class alive would previously have allowed the variables in the child display-class to be GCed, but if they are merged it would keep them alive.

However if there are no such closures, I believe that from a GC perspective there are no issues with merging the two display-classes.

**Comment by YairHalberstadt** [comment] 2018-12-30 08:37
Currently I have a working prototype, and I am just writing tests to make sure I have covered all scenarios.

**Comment by YairHalberstadt** [comment] 2018-12-30 08:45
With `GOTO`s I could not find any way to easily find the target of the Jump, so I just don't do this analysis if there are any `GOTO`s in the method at all. 

However in theory we could do this analysis even if there is a `GOTO`, so long as it is forward jumping, or it occurs before the start of the child-scope, or it occurs after the end of the child scope, and jumps to a point after the end of the child scope, or it occurs at a point in the child scope and jumps to another point in the child scope.

Thus there is room for future optimisation, but GOTOs are rare enough that I'm happy to just leave this for now.

**Comment by YairHalberstadt** [comment] 2018-12-30 21:01
Semantically the only cases where we cannot always merge a display-class into its parent display-class are:

We cannot merge the child of a for loop into a for loop

We cannot merge anything in a do int the parent of a do

We cannot merge a while or a foreach into their parents.

In all other cases, so long as there are no `GOTO`s it is always semantically safe to merge display-classes

**Comment by YairHalberstadt** [comment] 2018-12-30 21:45
In CodeGenClosureLambdaTests.ParentFrame05 there's a comment:
```csharp
// IMPORTANT: this code should not initialize any fields in Program.c1.<>c__DisplayClass0 except "a"
//            Program.c1.<>c__DisplayClass0 should not capture any frame pointers.
```
Does anyone here have any idea what this means?

**Comment by YairHalberstadt** [comment] 2019-01-02 08:57
https://github.com/dotnet/roslyn/pull/32092

**Closed** 2019-04-25 05:32 UTC
Labels: Area-Compilers, Concept-Code Quality Improvement, Feature Request, help wanted
