### ISSUE TITLE
C# Analyzer gives wrong fix solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24628] opened 2018-02-04 11:06 UTC
My code looks like:

```csharp
if (arg == null) throw new ArgumentNullException();
var key = MakeKey(arg);
dict[key] = arg;
```

The analyzer suggests using throw expressions:

```csharp
var key = MakeKey(arg);
dict[key] = arg ?? throw new ArgumentNullException();
```

But in fact the two are not identical because `MakeKey` method can have side effects.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/187379/c-analyzer-gives-wrong-fix-solution.html
VSTS ticketId: 556384_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2018-02-04 19:14
I tried with the following code and didn't see this refactoring offered.
```c#
using System;
using System.Collections.Generic;

public class Class1
{
    public void Method(object arg)
    {
        Dictionary<object, object> dict = null;

        if (arg == null) throw new ArgumentNullException();
        var key = MakeKey(arg);
        dict[key] = arg;
    }

    object MakeKey(object x)
    {
        return null;
    }
}
```
(on 15.6 preview 1.1)

**Comment by Neme12** [comment] 2018-02-04 19:15
I don't see it on 15.5.5 either.

**Comment by sharwell** [comment] 2018-02-04 22:20
My best guess is this is either a duplicate of #21612, or just happened to be fixed at the same time.

**Comment by Neme12** [comment] 2018-02-04 22:29
It seems like exactly the same issue because `arg` is indeed accessed on the line before.

**Closed** 2018-02-05 04:04 UTC
Labels: Area-IDE, Bug, Developer Community, Test, help wanted
