### ISSUE TITLE
IDE features don't handle crefs to primary constructor parameters

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#69446] opened 2023-08-09 18:58 UTC
**Version Used**: 
Version 17.8.0 Preview 2.0 [34008.482.main]

**Steps to Reproduce**:

```C#
/// <summary>
/// <paramref name="Primary"/>
/// </summary>
class C(int Primary)
{
    /// <summary>
    /// <see cref="Primary"/>
    /// </summary>
    void WritePrimary()
    {
        Console.WriteLine(Primary);
    }
}
```

GTD: "Cannot navigate to the symbol under the caret."
FAR: 
![image](https://github.com/dotnet/roslyn/assets/41759/9361048a-edac-4811-b9c5-319fdfbbf71e)
Highlight:
![image](https://github.com/dotnet/roslyn/assets/41759/3ef39843-08b7-465a-8e95-1445e84fd9c6)

However, completion does include it:
![image](https://github.com/dotnet/roslyn/assets/41759/0d8607c7-e4e8-4895-865c-b11001d72221)

**Comment by tmat** [comment] 2023-08-09 19:02
@CyrusNajmabadi FYI

**Comment by CyrusNajmabadi** [comment] 2024-12-06 20:58
Looks to be by design:

![Image](https://github.com/user-attachments/assets/6d040c30-0f75-42d8-9090-2cfdcc89c34b)

Compiler itself doesn't resolve this, so IDE can't do anything different here.  If you think compiler should handle this, i'd reopen and assign to them.

**Closed by CyrusNajmabadi** 2024-12-06 20:58 UTC
Labels: Area-IDE
