### ISSUE TITLE
[Test Failure] MSBuild Error in windows_vsi_p3_open_prtest on PR #12097

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12508] opened 2016-07-14 00:43 UTC
PR: [#12097](https://github.com/dotnet/roslyn/pull/12097) *refactor how we do completion set filtering.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/249/

**Issue 1: MSBuild Error**
error MSB3073: The command ""d:\j\workspace\windows_vsi_p---ee5cdb44\Closed\Tools\ibcmerge\ibcmerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p---ee5cdb44\Open\Binaries\Obj\ServicesVisualStudio\Release\Microsoft.VisualStudio.LanguageServices.dll" -incremental "d:\j\workspace\windows_vsi_p---ee5cdb44\Closed\OptimizationData\Microsoft.VisualStudio.LanguageServices.pgo"" exited with code -1. [d:\j\workspace\windows_vsi_p---ee5cdb44\Open\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]

**Comment by tannergooding** [comment] 2016-07-14 02:28
I have pinged @KevinH-MS

**Comment by natidea** [comment] 2016-07-19 18:07
@KevinH-MS is this still being investigated? With the extra logging in place, can we close this until the issue occurs again?

**Comment by tannergooding** [comment] 2016-07-19 18:10
This has been resolved by moving to a checked version of ibcmerge. The issue is now being tracked internally by 241626

**Closed by tannergooding** 2016-07-19 18:10 UTC
Labels: Area-Performance, Bug, Urgency-Now
