### ISSUE TITLE
Compilation sometimes fails. Sometimes succeeds.

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/roslyn#52890] opened 2021-04-24 09:33 UTC
**Version Used**: VS 16.9.3

Unfortunately, it's very hard to reproduce it in a sample separate project.

The problem is that sometimes (rather rarely than often) the compiler fails to build a code in some relatively-complicated generic methods. To be precise, it says that it cannot implicitly convert a subtype to `T`. But this subtype is a derived type of the type which is substituted under `T`. **So it seems like the compiler *sometimes* resolves these types in a different order, such that it tries to convert a type into `T` before knowing that `T` is actually is a super type of the type** . My assumption can be wrong, though.

The example of the error can be found [**here**](https://github.com/asc-community/AngouriMath/pull/390/checks?check_run_id=2425957433).
The file where it happens is [**here**](https://github.com/asc-community/AngouriMath/blob/905262c50d06115a35ddded7d96523daf1078873/Sources/AngouriMath/Core/Entity/Continuous/Number/Operators.cs#L69).

Sorry for this inconvenience, but the only way you can reproduce it is actually clone that repo and rebuild it a couple of times, and if you are lucky, you will get the error. I didn't find any way to reproduce it in a separate project, it seems to be a very rare error. But the problem appears every ~20 builds throughout the entire last year, so it's stable in a sense, that it *could* be reproduced.

**Comment by Youssef1313** [comment] 2021-04-24 11:46
@jaredpar Would you be able to take a look at this? Likely a race condition with (per description) a good repro rate.

**Comment by jaredpar** [comment] 2021-04-26 13:18
This looks like a duplicate of #50040. Looked at the GH Action and it's installing 5.0.100 which is a version that still has that bug. If upgrading to 5.0.202 doesn't fix the issue will take another look at this.

**Closed by jaredpar** 2021-04-26 13:18 UTC
Labels: Area-Compilers, Resolution-Duplicate

**Comment by WhiteBlackGoose** [comment] 2021-04-26 13:19
Thanksm I'll try 202
