### ISSUE TITLE
Bug: `required` keyword completion does not work in `record` and `record struct` types

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#62873] opened 2022-07-22 19:44 UTC
### Version Used
```
Compiler version: 4.3.0-3.22329.30 (29e657c0)
Language version: preview
.NET version: 7, preview 5
Visual Studio version: 17.3.0 Preview 4.0
```

### Steps to Reproduce
1. Declare a new `record` or `record struct` type.
2. Begin declaring a new member by typing any amount of the `required` keyword.

### Expected Behavior
Much like in `class` and `struct` declarations, the IDE should suggest a statement completion for the `required` keyword.

### Actual Behavior
The statement completions will not feature a completion for the `required` keyword.

**Comment by Youssef1313** [comment] 2022-07-22 20:49
Duplicate of https://github.com/dotnet/roslyn/issues/62421

**Comment by svick** [comment] 2022-07-22 21:19
Closing as duplicate.

**Closed by svick** 2022-07-22 21:19 UTC
Labels: Area-IDE, untriaged
