### ISSUE TITLE
IOperation: VB - BoundMethodGroup should implement specific interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8914] opened 2016-02-19 03:16 UTC
BoundMethodGroup can survive initial binding in presence of errors. 

Same for BoundPropertyGroup

**Comment by JohnHamby** [comment] 2016-02-24 22:59
We might get by with having these implement IInvalidExpression.

**Comment by AlekseyTs** [comment] 2016-02-24 23:34
I think there is a benefit in exposing some information about the group: the name, type arguments, maybe even the set of symbols. Though, semantic model can be used to lookup the symbols based on name and the arity.

**Comment by jinujoseph** [comment] 2017-07-03 23:53
dupe of https://github.com/dotnet/roslyn/issues/19965

**Closed by jinujoseph** 2017-07-03 23:53 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, Concept-API, Language-VB, New Feature - IOperation
