### ISSUE TITLE
Add switch-case collapse

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39355] opened 2019-10-17 17:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/776275/add-switch-case-collapse.html)._

---
&quot;switch&quot; already has it, might as well add to &quot;case&quot;. Having to type #region is kind of annoying.

---
#### Jane Wu [MSFT] on 10/14/2019, 07:53 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-10-23 19:46
Duplicate of #29998

**Closed by jinujoseph** 2019-10-23 19:46 UTC
Labels: Area-IDE
