### ISSUE TITLE
Unexpected SemanticModel responses related to ValueTuples when it involves a nullable element

### ISSUE THREAD

**Issue by Liander** [dotnet/roslyn#73052] opened 2024-04-16 20:17 UTC
Consider the types reported for these different deconstructions and ValueTuple related access. See screenshot:

![ValueTuple with nullable elements](https://github.com/dotnet/roslyn/assets/4334883/ff1702bf-d653-4d07-a599-571950965ea7)

[sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8DEADshAOaQAEA7hMjLKRRlAM4TAA2AphQJIAiAUQAMogOwUA9JIoBVFjyhhCHKAGMoCCggCehLgFgAUERLkI1WvRiNmbTjwEjhAVgCcUmbJgwuarixsyDoUEIFQpDBgXDBaAPYAZqEUAG4QHKiGRgACAEwAjMbZAMwUeRQAwhQA3sYU9WWl2QAsFACyABQAlHUNtUYNg54UABJxKVzIDBRxMNoAFgE8aVPs3CwUpFATLCC9Q6m0FCwIyFxcWgC8FB3Z+cIA/F0ARC4I888A3PXS2npcIDK9we+yGK2Op3OCHyFGur3eXx+Ml0+kBd0exlBg1+AEEAHSjcaTaYANXSmQAKqgVDxomBgJMKBS4gBlU4MbqbbYBPYDA7DIYAWkqcWQZzUCDgFGAqC0mgorAVMDUsxYrAQMS0CDiCx4xCWsS4GEOqwcf30LAJFMWFDAcROFA4cS2anSWIavyGVDiqA4xoZ2h16RoOg2+oUsWo8wgco2AGsYHEqPAo+p5gqNu8YxQAOQnM4XfI5jPJHPonN4931Dr5qFS54AOQAms8unjmWypjZut9hiiATd0Q8IQXJUDhD0+Qca5DC/Xm6326z2d2ur3fv3Abd7iOofkpejJ1XhgAhAljCZdxiCACOqHSLGZcZiStC4Ui0VivP5AsGwoAMiMLIltujy7hcuRSgA+l0UosPMSZzFQmgIbKFAwL6HDsFAqi6KEMDGgASkBJbHp6gygeBY6HgSLIIchNgUMRwHer6/pXraoqKDACSipACBQLMlZTkM5ENMKF7Eox7w8HYrrIMaWw7EqvEzEkFi8BqYC5LaXD0oyEBqP4gRSlQ8xpgqsYwDmCDCT+oHDrWEHQV0sI3E5Y6Ni2a5IuaA6UR5kHjkeInYjIFTnkSHG3veHCPnEz4wN+/JifUwpkqa6yhGcFBnIQooasaYS5kOOZSlwd4PoGiW5Vw+XIAgGzIe8PpaBhHBYcAOGaDocBkTIXrmdwCpJMx1A+n60o8KBB7Am2x4ObaUrggAHq51wdM8IxcB1cTPFKDldO1HA+cM4aakaflbuiS3jhQa2YqFHoyPwkWXtMFWxZmCUvrxyBMH4qqnKgEqCXMiS2jGaiLMaMAQNExoINS3DJQcqUUMKFK0KQFx+RQCTIHEYCVCyAAc+S5KUirNahbXwwEg73LNE4EieFwav9CTnBgwCGXG/UHIqvhGpdUBJO8ipxrAxoQ2EaofpqJaJloLDUvVhV2fyi0sMzFBqOt7mAh5UpqICXmtuuyL/NdO463d+uPT+vyCG9UmMDduGTOk2WkKgn5aObAtCnwWk6XSDL/YZxkbPBiEzHMsAqjAaonIr/aWjcvDKqq6oxBoDMPjqswUJ9D6Tj+UFuTOo7zt5ltXYzYHG8Fx7gtXULFC5VfN+bp0btbjdUcz5da0OVHNF3G09wufdW6ig/N4ejspTIABirscU6roCbMQd/rmW8xmDxYrFAaw8LHbFTbV6uXcVyvoZhUYxFwl4UKgCj+jtSaawc4KHzvOYU9ZzQlrouZkVIaQ9gWuCFgRMuCdjrBQGCbkAFg2+L8RM+MnRUAhDGHgeUCrxwPnEbex9jx3DcB0NBxcHjDk2m8D4YC2wQORlwbos8SFkNmMWIWcQ2pP0WGcCh+QqE0JgHiTSel9wUF7hgmQOZxHFkgCEAMx0KBCKyIMAAvsYbRQA===)

1. What I am really trying to do is to get the RHS type at any assignment of a nullable typed variable. The nullable annotation info seems to get lost in various places as I am trying to show in the above examples. 

2. The above is what you get from API calls to GetSymbols for the hovering token. What API should I use to get the type for the RHS when assigning a variable? 
**Expected**: GetTypeInfo(assignment.Right) should get the type (with annotations) for ValueTuple assignments and GetDeconstructInfo should get it when a Deconstruct call applies (which it does). Even better if that is embedded into an operator on the designated variable so that a custom variable to argument mapping is avoided.
**Actual**: The nullable annotation seems to get lost, just like what happens in the examples above.

3. Example A explores the fact that the compiler sometimes makes use of its knowledge of the nullability of a reference type and sometimes it doesn't. It makes the user question its code and/or question the tooling. To model the effectively inferred nullability of a reference variable 's' you have the states:
 - 's' is nullable, inferred at declaration.
 - 's' is nullable, inferred from a reassignment. (Implying it's not nullable at declaration) 
 - 's' is not nullable, inferred from all assignments.
I think it should be considered to have that inference knowledge included in the symbol from the semantic model. That would make it easy for analyzers to do things like saying when a nullable reference (such as string? s = "Hello") can be declared with a non-nullable type instead. And for tooling like QI to show a description of the actual nullable inference when its contradictory to its presented symbol (the 'var' case) and provide any symbol presenter the choice whether to show the symbol with its effectively inferred nullability or not. (See also #63959)

**Comment by 333fred** [comment] 2024-06-14 22:57
Duplicate of https://github.com/dotnet/roslyn/issues/35010. Unfortunately, the fixes here are pretty complicated, which makes it hard for contributors to attempt, and we just haven't had the pressure to do the work to fix it.

**Closed by 333fred** 2024-06-14 22:57 UTC
Labels: Question, Area-Compilers
