### ISSUE TITLE
When proposing autocomplete suggestions for classes,  which respect the expected signature should be displayed first

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41879] opened 2020-02-21 20:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/913233/when-proposing-autocomplete-suggestions-for-classe.html)._

---
I have the following line of code in the Startup method of a .NET Core app:

services. AddScoped<IWadoRsService,Wa...>()

When I start typing Wa I get the autocomplete list popping up, however the lists is ordered alphabetically,  Ideally the relevant ones should appear first (in the above case  classes which respect the IWadoRsService should be displayed first and then the rest alphabetically.  (see attached screenshot)

I believe that I have seen similar behaviour for autocomplete on parameter passing,  I will update the issue or add a screenshot for other cases.

In the screenshot the WadoRsService appears later in the list (after classes which do not implement the interface).

I believe there are quite a few cases where autocomplete can be improved by ordering the list so that the ones matching the expected type appear first.

---
#### Visual Studio Feedback System on 2/10/2020, 02:02 PM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 2/10/2020, 08:44 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment] 2020-04-08 20:43
This is not a bug, we don't do type inference for completion.

**Comment by genlu** [comment] 2020-04-08 20:44
@jinujoseph @vatsalyaagrawal I'm moving this to backlog as a feature request.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:47
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-21 19:47 UTC
Labels: Area-IDE, Feature Request, IDE-IntelliSense
