### ISSUE TITLE
Wrong suggestion by intellisense, "using directive is unnecessary" but its not!

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24992] opened 2018-02-22 13:18 UTC
Quick action thinks that using statement is useless, and will suggest to clean it up (and will do so if I perform full clean up).

If you remove that using statement, documentation becomes invalid.

![wrong suggestion](https://user-images.githubusercontent.com/15255162/36540484-c9b49d7a-17ef-11e8-90b9-7b979784c773.JPG)

---

**Tested Version : 15.5.5**

**Comment by sharwell** [comment] 2018-02-22 15:40
Duplicate of #2773

**Closed by sharwell** 2018-02-22 15:40 UTC
