### ISSUE TITLE
IDE0005 reports Deconstruct method's namespace as not necessary

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#60594] opened 2022-04-05 22:22 UTC
**Version Used**: 
Version 17.3.0 Preview 1.0 [32403.30.main]

**Steps to Reproduce**:
I am editing code in Roslyn. And IDE0005 is reporting there is an unneeded namespace.
![image](https://user-images.githubusercontent.com/24360909/161860063-a0d36192-823d-4c9a-9cde-1da01da5b573.png)
But if I delete it, and run Build.cmd, I get errors.
![image](https://user-images.githubusercontent.com/24360909/161860283-82ac2653-f2e4-4aee-8d39-43d9e6d04394.png)

It turns out I was referencing the Deconstruct method in a for each loop
![image](https://user-images.githubusercontent.com/24360909/161860349-0e44e7f3-d503-4b5f-b1b4-2795a0968b00.png)

**Expected Behavior**:
IDE0005 should not be reported for deconstruct method.

**Actual Behavior**:
IDE0005 is reported

**Comment by Cosifne** [comment] 2022-04-05 22:22
Might be related to https://github.com/dotnet/roslyn/issues/59817

**Comment by sharwell** [comment] 2022-04-06 19:49
Duplicate of #49925

**Comment by sharwell** [comment] 2022-04-06 19:50
This is a duplicate of the issue above, particularly in relation to the following comment:
https://github.com/dotnet/roslyn/issues/49925#issuecomment-749268021

**Closed by sharwell** 2022-04-06 19:49 UTC
Labels: Bug, Resolution-Duplicate, Area-IDE
