### ISSUE TITLE
IOperation: It looks like collection initializers and some forms of member initializers cannot be represented by IObjectCreationExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8883] opened 2016-02-18 19:02 UTC
C#

```
object-initializer:
    {   member-initializer-listopt   }
    {   member-initializer-list   ,   }
member-initializer-list:
    member-initializer 
    member-initializer-list   ,   member-initializer
member-initializer:
    initializer-target   =   initializer-value
initializer-target:
    identifier
    [   argument-list   ]
initializer-value:
    expression
    object-or-collection-initializer
```

It looks like initializer-target with argument list and initializer-value of the object-or-collection-initializer form cannot be represented.

**Comment by jinujoseph** [comment] 2017-07-07 08:14
Dupe of https://github.com/dotnet/roslyn/issues/18781

**Closed by jinujoseph** 2017-07-07 08:14 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, Concept-API, New Feature - IOperation, Urgency-Soon
