### ISSUE TITLE
Contents of hover lightbulb menu depend on caret position

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#1595] opened 2015-03-25 23:50 UTC
I had an error in a field declaration like ```int x = T.NonExistent.GetHashCode()```.  When I mouse over ```Nonexistent``` the lightbulb offers to generate it, as expected.  However, the lightbulb may also offer to encapsulate the field in a property, depending on the caret location.  If the caret is within the field declaration, the actions are present; otherwise, they are not.  Since I triggered the menu with the mouse, depending on the caret position surprised me.

**Comment by amcasey** [comment] 2015-03-25 23:50
FYI @shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment] 2015-04-03 04:54
The root cause here is probably #1030. We should not be returning refactorings during hover because I believe light bulb only asks us for code fixes in this case.

**Comment by srivatsn** [comment] 2015-04-09 17:30
Fixed by #1824

**Closed by srivatsn** 2015-04-09 17:30 UTC
Labels: Area-Analyzers, Bug

**Comment by shyamnamboodiripad** [comment] 2015-04-09 22:07
Could you please verify that this is fixed @amcasey?

**Comment by amcasey** [comment] 2015-04-14 19:53
Seems to be based solely on the squiggle now.
