### ISSUE TITLE
Add support for .editorconfig and Visual Studio "Enable full solution analysis"

### ISSUE THREAD

**Issue by Gav-Brown** [dotnet/roslyn#25405] opened 2018-03-11 12:49 UTC
**Version Used**: 

Visual Studio 2017 v15.6.1

**Steps to Reproduce**:

1. Create .editorconfig file with the [.NET coding conventions](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) configured within it.
2. Enable `Options\Text Editor\C#\Advanced\Enable full solution analysis`

**Expected Behaviour**:

VS will run all code convention rules, on all files in the solution, whether they are open or not.
This is the behaviour when using the Visual Studio Code Style rules configured directly in the options dialog.

**Actual Behaviour**:

The rules only get applied to the currently open file(s).

Could we add support for and respect this option?

I originally posted this on the [editorconfig](https://github.com/editorconfig/editorconfig/issues/341) board. I hope this is the correct place for this item?

**Comment by jcouv** [comment] 2018-03-11 18:27
Tagging @kuhlenh

**Comment by sharwell** [comment] 2018-03-11 18:36
Duplicate of #19089

**Closed by sharwell** 2018-03-11 18:36 UTC
Labels: Area-IDE, Feature Request

**Comment by sharwell** [comment] 2018-03-11 18:37
The underlying issue is .editorconfig settings are not currently passed to the out-of-process analysis engine. In the default configuration, this engine is only used for Fix All operations. However, when full solution analysis is enabled it is also used for analyzing files not currently open in the editor.
