### ISSUE TITLE
Function pointers do not have documentation id

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#65345] opened 2022-11-10 23:27 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.5.0 Preview 2.0 [33108.404.main]

**Steps to Reproduce**:

Declare two methods taking different function pointers. Use documentation comments to document them differently, for instance:

```C#
public class Class1
{
    /// <summary>
    /// This version of DoIt handles an fp that takes an int and
    /// produces a float.
    /// </summary>
    public static unsafe void DoIt(int x, delegate*<int, float> fp) {}

    /// <summary>
    /// This version of DoIt handles an fp that takes a float and
    /// produces no result.
    /// </summary>
    public static unsafe void DoIt(int x, delegate*<float, void> fp) {}
}
```

**Expected Behavior**:

Getting a documentation file that has unique values for the documentation IDs.

**Actual Behavior**:

Both methods produce the same ID. It seems the documentation ID for a function pointer is always the empty string.

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Class1</name>
    </assembly>
    <members>
        <member name="M:Class1.DoIt(System.Int32,)">
            <summary>
            This version of DoIt handles an fp that takes an int and
            produces a float.
            </summary>
        </member>
        <member name="M:Class1.DoIt(System.Int32,)">
            <summary>
            This version of DoIt handles an fp that takes a float and
            produces no result.
            </summary>
        </member>
    </members>
</doc>
```

It doesn't seem like function pointers [were spec'd to produce documentation IDs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments), but that seems problematic for folks like me who use it as way to uniquely identify public APIs.

For reference, CCI produces the following documentation IDs. Not sure that syntax can be considered elegant, but it gets the job done...

```text
M:Class1.DoIt(System.Int32,function System.Single (System.Int32))
M:Class1.DoIt(System.Int32,function System.Void (System.Single))
```

**Comment by tannergooding** [comment] 2022-11-10 23:38
Dupe of https://github.com/dotnet/roslyn/issues/46674 ?

**Comment by 333fred** [comment] 2022-11-10 23:39
Duplicate of https://github.com/dotnet/roslyn/issues/46674.

**Closed by 333fred** 2022-11-10 23:39 UTC
Labels: Area-Compilers, untriaged
