### ISSUE TITLE
Proposal: Language "using" blocks with multiple resources

### ISSUE THREAD

**Issue by doktrova** [dotnet/roslyn#13493] opened 2016-08-31 18:43 UTC
This is more a feature than an issue. It would be nice if we can use "using" block with multiple resources such as below:
`using(var custSvc =  new CustomerService(), var empSvc = new EmployeeService()) { }`

I do not for see any limitations to being able to achieve this but I could be wrong.

**Comment by svick** [comment] 2016-08-31 18:49
This is a duplicate of https://github.com/dotnet/roslyn/issues/2331 (only with `,` instead of `;`), which [was closed as "Won't fix"](https://github.com/dotnet/roslyn/issues/2331#issuecomment-139841086) by @gafter:

> The benefit of this proposal seems close to zero, plus or minus epsilon.

**Comment by doktrova** [comment] 2016-08-31 18:53
The benefit is readability. It prevents nested usings.

**Comment by svick** [comment] 2016-08-31 18:56
You don't need to nest `using`s in blocks:

```c#
using (var custSvc = new CustomerService())
using (var empSvc = new EmployeeService())
{
}
```

**Comment by doktrova** [comment] 2016-08-31 19:04
That's good enough then, at least in the surface. I wonder if ugly nested 'try.. catch.. finally..' get created in the background.

**Comment by alrz** [comment] 2016-08-31 20:01
VB version also generates two try block.
```vb
using custSvc = new CustomerService(), empSvc = new EmployeeService()
end using	
```
Not sure if it has any performance penalties, though.

**Comment by gafter** [comment] 2016-09-01 18:32
Dup of #2331

**Closed by gafter** 2016-09-01 18:32 UTC
