### ISSUE TITLE
inserting #if snippet doesn't respect .editorconfig end_of_line setting in *.cs files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48764] opened 2020-10-19 16:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1224650/inserting-if-snippet-doesnt-respect-editorconfig-e.html)._

---
[severity:It bothers me. A fix would be nice]
Similar, but not an option
https://developercommunity.visualstudio.com/content/problem/940874/code-snippets-dont-respect-the-newline-setting-of.html
https://developercommunity.visualstudio.com/content/idea/409252/inconsistent-line-endings-dialog-should-respect-ed.html

My .editorconfig have end_of_line = lf
When i type #if then press Tab, Tab there is next insertion (checked in notepad++):
#if true (CRLF)
(LF)
#endif(LF)

Same for #region:
#region MyRegion (CRLF)
(LF)
#endregion(LF)

So, the problem is using #if makes .cs file with inconsistent line endings

---
#### Feedback Bot on 10/18/2020, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-10-19 16:46
Duplicate of #28638

**Closed by sharwell** 2020-10-19 16:46 UTC
Labels: Area-IDE, untriaged
