### ISSUE TITLE
ReassignedVariable classifier crashed

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#61503] opened 2022-05-25 02:42 UTC
Version 17.3.0 Preview 2.0 [32523.442.main]

Stack:

```
StreamJsonRpc.RemoteInvocationException: Local did not come from same file that we were analyzing? - line 212
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidOperationException: Local did not come from same file that we were analyzing? - line 212
      at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<GetLocationsAsync>g__ComputeLocalIsAssigned|5_8(ILocalSymbol local, <>c__DisplayClass5_0& )
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<GetLocationsAsync>g__IsSymbolReassigned|5_5(ISymbol symbol, <>c__DisplayClass5_0& )
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<GetLocationsAsync>g__ProcessIdentifier|5_1(TIdentifierNameSyntax identifier, <>c__DisplayClass5_0& )
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<GetLocationsAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddClassificationsInCurrentProcessAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

FYI @CyrusNajmabadi

**Comment by sharwell** [comment] 2022-06-02 19:43
Duplicate of AB#1548037

**Closed by sharwell** 2022-06-02 19:43 UTC
Labels: Bug, Area-IDE
