### ISSUE TITLE
Nuget package Microsoft.VisualStudio.LanguageServices 1.0.0 for target v4.5.2 is built against v4.6

### ISSUE THREAD

**Issue by uppi** [dotnet/roslyn#10749] opened 2016-04-21 13:13 UTC
**Versions Used**:
MSVS Community 2015 Version 13.0.25123.00 Update  2
Microsoft.VisualStudio.LanguageServices 1.0.0
.NET 4.5.2

**Steps to Reproduce**:
1. Create an extension project with target framework version .NET 4.5.2
2. Install-Package -Version 1.0.0 Microsoft.VisualStudio.LanguageServices
3. Build

**Expected Behavior**:
Build succeeded

**Actual Behavior**:

```
Install:

Attempting to gather dependency information for package 'Microsoft.VisualStudio.LanguageServices.1.0.0' with respect to project', targeting '.NETFramework,Version=v4.5.2'
<...>
Successfully installed 'Microsoft.VisualStudio.LanguageServices 1.0.0'

Build:
warning MSB3274: The primary reference "Microsoft.VisualStudio.LanguageServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".
```

**Comment by Pilchie** [comment] 2016-05-27 20:46
Note - all of the visual studio binaries actually require 4.6 - the issue here is in the nuspec.

**Comment by Pilchie** [comment] 2016-05-27 20:47
@jmarolf: Can you verify this is fixed in the 2.0 packages?

**Comment by jmarolf** [comment] 2016-05-27 21:03
Our nuget packages [here](https://www.myget.org/gallery/roslyn-future-nightly) still say they are compatible with .net 4.5.  Specifically they have:
* net45
* netstandard1.3
* portable-net45 win8

We should change these to:

* net46
* netstandard1.3
* portable-net46 win8

**Comment by Pilchie** [comment] 2016-05-27 21:05
Tag @agocke and @tmat.  Should we actually remove the portable-net46+win8?  I thought it was only there because netstandard didn't exist yet?

**Comment by tmat** [comment] 2016-05-27 21:10
It's my understanding that if we remove "portable-net46+win8" it would make the packages unusable by clients who still are on nuget 2.0.

**Comment by jmarolf** [comment] 2016-05-27 21:26
@Pilchie @tmat we should still change it from `portable-net45 win8` to `portable-net46 win8` though, correct?

**Comment by Pilchie** [comment] 2016-05-27 21:30
Adding the usual suspects... @yishagalatzer, @emgarten, @ericstj.

**Comment by tmat** [comment] 2016-05-27 21:39
@jmarolf What packages are we specifically talking about? Workspaces?

**Comment by ericstj** [comment] 2016-05-27 22:25
I doubt you run on net46+win8.  Win8 is a subset of net45.  You can't create a PCL project that targets this combo.  Why don't you just package how you build?

**Comment by jmarolf** [comment] 2016-05-27 22:43
@tmat looked at Microsoft.CodeAnalysis.CSharp first.  I can confirm that all the packages have this problem.

**Comment by tmat** [comment] 2016-05-28 00:19
@jmarolf  Is this future branch or master?

**Comment by jmarolf** [comment] 2016-05-28 00:40
@tmat 2.0 is future

**Comment by yishaigalatzer** [comment] 2016-05-28 05:23
We are working on releasing nuget 2.12 that will support netstandard downlevel, should be out in June timeframe

**Comment by jasonmalinowski** [comment] 2016-07-08 17:35
@shyamnamboodiripad here's the bug we discussed.

**Comment by Pilchie** [comment] 2016-11-02 21:22
@tmat - you updated us to 1.3/net46 right?

**Comment by tmat** [comment] 2016-11-02 21:37
@Pilchie We went back and forth a couple times. I think we are now on 1.3/net46.

**Comment by jmarolf** [comment] 2016-11-03 22:06
Here is the layout of nuget packages shipping for RC from the latest dev15-rc build:
```
Microsoft.CodeAnalysis.CSharp.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.CSharp.Features.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.CSharp.Scripting.2.0.0.nupkg\lib\dotnet
Microsoft.CodeAnalysis.CSharp.Workspaces.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.EditorFeatures.2.0.0.nupkg\lib\net46
Microsoft.CodeAnalysis.EditorFeatures.Text.2.0.0.nupkg\lib\net46
Microsoft.CodeAnalysis.Features.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.Scripting.Common.2.0.0.nupkg\lib\dotnet
Microsoft.CodeAnalysis.VisualBasic.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.VisualBasic.Features.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.VisualBasic.Workspaces.2.0.0.nupkg\lib\netstandard1.3
Microsoft.CodeAnalysis.Workspaces.Common.2.0.0.nupkg\lib\net46
Microsoft.CodeAnalysis.Workspaces.Common.2.0.0.nupkg\lib\netstandard1.3
Microsoft.NetFX20.1.0.3.nupkg\lib\net20
Microsoft.VisualStudio.LanguageServices.2.0.0.nupkg\lib\net46
Roslyn.VisualStudio.Test.Utilities.2.0.0.nupkg\lib\net46
```

every package either targets net46, netstandard1.3 or both with the exception of Microsoft.NetFX20.1.0.3.nupkg

**Comment by jmarolf** [comment] 2016-11-03 23:25
As per @tmat we should update scripting to netstandard1.3
```
Microsoft.CodeAnalysis.CSharp.Scripting.2.0.0.nupkg\lib\dotnet
Microsoft.CodeAnalysis.Scripting.Common.2.0.0.nupkg\lib\dotnet
```

**Comment by jmarolf** [comment] 2016-11-04 03:43
closed with https://github.com/dotnet/roslyn/pull/14951

**Closed by jmarolf** 2016-11-04 03:43 UTC
Labels: Area-IDE, Bug
