### ISSUE TITLE
Many errors reported when enabling nullable reference types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#31858] opened 2018-12-17 12:25 UTC
**Version Used**: Microsoft.Net.Compilers 3.0.0-beta2-18616-01

🔗 https://github.com/tunnelvisionlabs/dotnet-trees/pull/65
🔗 https://ci.appveyor.com/project/sharwell/dotnet-trees/builds/21060162

**Steps to Reproduce**:

tunnelvisionlabs/dotnet-trees#65

**Expected Behavior**:

The project compiles, with zero or more new warnings related to nullable reference types reported.

**Actual Behavior**:

The project does not compile. The reported errors appear to be unrelated to nullable reference types.

```
1>SortedTreeDictionary`2.cs(89,14,89,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(89,14,89,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(187,14,187,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(189,14,189,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(191,14,191,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(193,14,193,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(199,14,199,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(195,14,195,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(201,49,201,88): error CS0540: 'SortedTreeDictionary<TKey, TValue>.IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()': containing type does not implement interface 'IEnumerable<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(197,49,197,88): error CS0540: 'TreeDictionary<TKey, TValue>.IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()': containing type does not implement interface 'IEnumerable<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(207,14,207,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(203,14,203,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0738: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()'. 'SortedTreeDictionary<TKey, TValue>.GetEnumerator()' cannot implement 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()' because it does not have the matching return type of 'IEnumerator<KeyValuePair<TKey, TValue>>'.
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly'
1>TreeDictionary`2.cs(13,57,13,82): error CS0738: 'TreeDictionary<TKey, TValue>' does not implement interface member 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()'. 'TreeDictionary<TKey, TValue>.GetEnumerator()' cannot implement 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()' because it does not have the matching return type of 'IEnumerator<KeyValuePair<TKey, TValue>>'.
```

When I add `ICollection<KeyValuePair<TKey, TValue>>` explicitly to the set of interfaces for the two types reporting these errors, the output changes but still fails:

```
1>SortedTreeDictionary`2+Enumerator.cs(10,26,10,46): error CS0695: 'SortedTreeDictionary<TKey, TValue>' cannot implement both 'IEnumerable<KeyValuePair<TKey, TValue>>' and 'IEnumerable<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>SortedTreeDictionary`2+Enumerator.cs(10,26,10,46): error CS0695: 'SortedTreeDictionary<TKey, TValue>' cannot implement both 'ICollection<KeyValuePair<TKey, TValue>>' and 'ICollection<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>TreeDictionary`2+Enumerator.cs(10,26,10,40): error CS0695: 'TreeDictionary<TKey, TValue>' cannot implement both 'IEnumerable<KeyValuePair<TKey, TValue>>' and 'IEnumerable<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>TreeDictionary`2+Enumerator.cs(10,26,10,40): error CS0695: 'TreeDictionary<TKey, TValue>' cannot implement both 'ICollection<KeyValuePair<TKey, TValue>>' and 'ICollection<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
```

**Comment by jaredpar** [comment] 2018-12-17 20:39
CC @AlekseyTs . looks like we may have an OHI issue here.

**Comment by jaredpar** [comment] 2018-12-17 20:44
Could this be a duplicate of #31862

**Comment by AlekseyTs** [comment] 2018-12-17 21:20
It is likely related to https://github.com/dotnet/roslyn/issues/30677

**Closed** 2019-01-04 00:47 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
