### ISSUE TITLE
Fake positive CS8619 when using Linq

### ISSUE THREAD

**Issue by Silencersn** [dotnet/roslyn#76180] opened 2024-11-30 15:16 UTC
**Version Used**: 
VS 17.12.0
.NET8

**Steps to Reproduce**:

```c#
using System;
using System.Linq;

public class C {
    public void M() {
            string?[] nullableItems = [];
            string[] items = nullableItems.Where(item => item is not null).ToArray(); // CS8619
    }
}
```
 [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBkCWAdgI4DcyyUAzJjOgMLoDey6bmNUALOgLIAUASmat2YsVlQB+ANoBddIQCuAGxUBDAEYqApgEkALjoC2AZ3QBedPPJJx9zHFTz0+I2cuLVG7fvensAHUACx0AJx1+NxNLAD5Xd1dzQgB7Ay81QWwAFRSAQTCw9QBPIVsxAF9kCqA==)

**Diagnostic Id**:
CS8619

**Expected Behavior**:
No warnings

**Actual Behavior**:
Warn CS8619

**Comment by Youssef1313** [comment] 2024-12-01 10:11
From the language perspective, I think the current behavior is expected, though it's unfortunate.

There is no way to annotate `Where` in the BCL such that the compiler would be aware that null is filtered out.

The reasonable workaround for this is to introduce an extension method `WhereNotNull` where you add a null suppression so that the null suppression is "centralized" in this single method and all callers can use it seamlessly.

**Comment by CyrusNajmabadi** [comment] 2024-12-02 01:25
Closing as by design.  The compiler is correctly implementing the language spec here.  For this to be recognized a change in the language would have to happen at dotnet/csharplang.

**Closed by CyrusNajmabadi** 2024-12-02 01:25 UTC
Labels: Area-Compilers, untriaged
