### ISSUE TITLE
VisualStudioTextBufferSupportsFeatureService throws a bunch of first-chance exceptions

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#35903] opened 2019-05-23 09:02 UTC
Hit this a bunch while debugging:

GetContainedDocumentId can return null, this null is then used to lookup a ConcurrentDictionary which throws ArgumentException.

https://github.com/dotnet/roslyn/blame/f5af4fb3bdcada8f64444374790acac3dc0cd9fb/src/VisualStudio/Core/Def/Implementation/VisualStudioSupportsFeatureService.cs#L29

Typical stack:
```
 	mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<Microsoft.CodeAnalysis.DocumentId, Microsoft.VisualStudio.LanguageServices.Implementation.Venus.ContainedDocument>.TryGetValue(Microsoft.CodeAnalysis.DocumentId key, out Microsoft.VisualStudio.LanguageServices.Implementation.Venus.ContainedDocument value)	Unknown
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.SuggestionService.VisualStudioSupportsFeatureService.VisualStudioTextBufferSupportsFeatureService.SupportsCodeFixes(Microsoft.VisualStudio.Text.ITextBuffer textBuffer) Line 24	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextBufferExtensions.SupportsCodeFixes(Microsoft.VisualStudio.Text.ITextBuffer buffer)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetFixLevelAsync(Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider provider, Microsoft.CodeAnalysis.Document document, Microsoft.VisualStudio.Text.SnapshotSpan range, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActionCategoriesAsync.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<string>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown

```

//cc @genlu

**Comment by genlu** [comment] 2019-05-23 22:40
@dibarbet IS this the same bug fixed by this PR?
https://github.com/dotnet/roslyn/pull/35831

**Comment by dibarbet** [comment] 2019-05-23 22:43
@genlu Probably, it looks the same as https://github.com/dotnet/roslyn/issues/35889 .  I couldn't reproduce it specifically in that issue, but the requester tried it with the fix and couldn't reproduce it any longer.

**Comment by davkean** [comment] 2019-05-23 22:45
I can't see how the fix in https://github.com/dotnet/roslyn/pull/35831 resolves above issue but maybe I'm missing stuff?

**Comment by dibarbet** [comment] 2019-05-23 22:56
@davkean 
GetContainedDocumentId can return a null id, which is then passed to SupportsCodeFixes.  That calls into the contained document's TryGetContainedDocument.  Before the PR referenced, this just called into the concurrent dictionary with a null id which throws the exception.

The fix in the PR is to just return back the null instead of querying the dictionary with a null id, this then gets passed back into [here](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/VisualStudioSupportsFeatureService.cs#L97) where it checks for a null result.

**Comment by jinujoseph** [comment] 2019-06-13 21:28
Closing this, feel free to reopen if you hit this again

**Closed by jinujoseph** 2019-06-13 21:28 UTC
Labels: Area-IDE, Bug, help wanted
