### ISSUE TITLE
Solution checksum are busted when build Roslyn in debug mode

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#55968] opened 2021-08-27 18:24 UTC
I am building Roslyn on main 
hash:  ef8ab06db36851202111ae376bdb0269bf88c103

And open Roslyn.sln
Many features are failing
![image](https://user-images.githubusercontent.com/24360909/131172101-ff333044-43d4-4f6f-885b-b198b6116a6a.png)

Full log:

[log.txt](https://github.com/dotnet/roslyn/files/7068837/log.txt)

**Comment by CyrusNajmabadi** [comment] 2021-12-16 19:00
Dupe of https://github.com/dotnet/roslyn/issues/57324

**Closed by CyrusNajmabadi** 2021-12-16 19:00 UTC
Labels: Bug, Area-IDE, Concept-OOP
