### ISSUE TITLE
Peek definition on constructor shows the class declaration instead of the actual constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51514] opened 2021-02-26 17:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Peek-definition-on-constructor-shows-the/1348480)._

---
[severity:It's more difficult to complete my work]
Repro:
- peek on constructor invocation (from a class that has multiple constructors)

Expected:
- peek window shows the code of the constructor
Actual:
- peek window shows the class declaration instead of the constructor

I provided a recording with the issue.

---
#### Feedback Bot on 2/25/2021, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2021-03-02 20:22
Duplicate of #23480

**Closed by jinujoseph** 2021-03-02 20:22 UTC
Labels: Area-IDE
