### ISSUE TITLE
Methods missing from intellisense in vb.net

### ISSUE THREAD

**Issue by gdroumpalis** [dotnet/roslyn#19940] opened 2017-06-01 09:39 UTC
Visual Studio 2017

Language: VB.Net

1. In Ado.net situations you call a filled dataset
2. If you type ds.Tables("Namesofthetable").Rows(0).*Missing Some Methods like BeginEdit()*
3. You expect that there is a method BeginEdit() after the dot. But there is not

**Comment by Pilchie** [comment] 2017-06-01 16:09
I suspect the method has the `<EditorBrowsable>` attribute set so that it is hidden from completion.

**Comment by gdroumpalis** [comment] 2017-06-01 16:36
Sorry for my bad description... I also encountered the same error but on the Count property of the Datagridviewrowcollection. It was kinda mind boggling at the beginning because I was trusting the intellisense suggestions with closed eyes. It got me to uninstall all the versions of visual studio and reinstall them to fix this. Then the count property showed up again. I also want to add that the Hide advanced members option is greyed out in Visual Studio's options and it looks disabled. Can you reproduce this?

**Comment by ehasis** [comment] 2017-11-14 12:06
I'm also having the same issue with VS2017 15.4.3. If the property or method have EditorBrowsableAttribute setted to EditorBrowsableState.Advanced, then looks like VB.NET editor interprets as EditorBrowsableState.Never. In C# editor this does not happens.

**Comment by sharwell** [comment] 2017-11-14 12:13
I am able to reproduce the items mentioned by @gdroumpalis and @ehasis in version 15.4.3. The **Hide advanced members** option is grayed out, and behaving as though it's permanently enabled. One of the following needs to happen:

1. Enable the option and follow its setting properly
2. Leave the option disabled and stop hiding advanced members

**Comment by ehasis** [comment] 2018-05-08 01:25
Tested with the version 15.7.0 and the problem still exists. It is very annoying because this force you know the API in advance.

**Comment by TranstecJasonD** [comment] 2019-10-29 17:01
Still an issue with 16.3.6. Example: Dispatcher is missing from System.Windows.Application.

**Comment by adegeo** [comment] 2021-07-21 17:10
Just ran into this too:

- `TextBox1.BeginInvoke`
- `TextBox1.InvokeRequired`

It's a shame this issue has been around for so long... :(

**Comment by CyrusNajmabadi** [comment] 2021-07-21 17:16
@adegeo as per https://github.com/dotnet/roslyn/issues/19940#issuecomment-344240780 we would take a PR here if you're interested.

**Comment by adegeo** [comment] 2021-07-21 17:20
Would you have time to review them? The repo has almost 400 open PRs 😁

I'll look into it.

**Comment by CyrusNajmabadi** [comment] 2021-07-21 17:29
I will ensure that i have time to review this.  :)

**Comment by adegeo** [comment] 2021-07-21 20:25
I just tested with VS 2019 Community and the latest 2019 Internal Preview and the options IS available and it works just fine. The question I do have though (@jinujoseph) why is this enabled by default for Visual Basic? Should this be turned off? Would this be the location to set the default? 

https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/VisualBasic/Impl/PackageRegistration.pkgdef#L174

**Comment by CyrusNajmabadi** [comment] 2021-07-21 21:01
> why is this enabled by default for Visual Basic?

It's been the experience in teh VB space for 15+ years, primarily driven by feedback back then from teh vb community that there was a ton of complexity in the API surface area of .net and it would be nice to hide by default things that were generally very esoteric and unlikely to be used.  People who were interested in seeing this stuff could just turn it on, but we wouldn't clutter the completion lists of tons of users who would not care with these items.

**Comment by CyrusNajmabadi** [comment] 2021-07-21 21:02
> I just tested with VS 2019 Community and the latest 2019 Internal Preview and the options IS available and it works just fine. 

Given this, it sounds like we can potentially close this issue :)

**Comment by CyrusNajmabadi** [comment] 2021-07-21 21:03
Fixed with https://github.com/dotnet/roslyn/pull/49891

**Comment by CyrusNajmabadi** [comment] 2021-07-21 21:04
For anyone coming to this in the future, this behavior can be controlled with this option in the VS UI:

![image](https://user-images.githubusercontent.com/4564579/126559872-62962d41-0617-4d82-9b39-69b26517ac75.png)

**Closed by CyrusNajmabadi** 2021-07-21 21:03 UTC
Labels: Area-IDE, Bug, help wanted

**Comment by adegeo** [comment] 2021-07-21 21:17
> > why is this enabled by default for Visual Basic?
> 
> It's been the experience in teh VB space for 15+ years, primarily driven by feedback back then from teh vb community that there was a ton of complexity in the API surface area of .net and it would be nice to hide by default things that were generally very esoteric and unlikely to be used. People who were interested in seeing this stuff could just turn it on, but we wouldn't clutter the completion lists of tons of users who would not care with these items.

I think the advancements with roslyn and intellicode and promoting most used items to the top really solve the "i'm seeing too much!" problem, though I don't think it's that much of a problem. We're constantly trying to get new devs into C# and we're not hiding things from them, so there really isn't any reason to hide things in VB. Really though, that's a discussion for a different time :)

**Comment by KathleenDollard** [comment] 2021-07-22 17:14
If anyone encounters this after VS 2019 Update 10, please reopen this issue.
