### ISSUE TITLE
Diff'ing a VB file crashes Visual Studio

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6173] opened 2015-10-20 01:25 UTC
__Repro:__

1. Sync https://github.com/davkean/roslyn/tree/dev/davkean/donotdelete_Bug6173 locally
2. In Team Explorer, right-click on branch, and choose __View History__
3. Double-click the most recent commit, __e9730e79__
4. Right-click on __MiscDiagnosticUpdateSourceTests.vb__ and choose __Compare with Previous__

__Expected:__ Diff to show
__Actual:__ Diff shows, but ~4 or 5 seconds later VS crashes with below

Stack:
```
An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.VisualStudio.Platform.VSEditor.dll

Additional information: The point does not belong to a source snapshot of the projection snapshot
>	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapFromSourceSnapshot(Microsoft.VisualStudio.Text.SnapshotPoint sourcePoint, Microsoft.VisualStudio.Text.PositionAffinity affinity)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager<Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTag>.UpdateSpans_CallOnlyOnUIThread(Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection changedSpanCollection, bool removeOldTags)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager<Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTag>.UpdateInvalidSpans()	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager<Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.LineSeparatorTag>.OnTagsChanged.AnonymousMethod__0()	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source = {System.Windows.Threading.Dispatcher}, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler = null)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd = {System.IntPtr}, int msg = 49648, System.IntPtr wParam = {System.IntPtr}, System.IntPtr lParam = {System.IntPtr}, ref bool handled = false)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source = {System.Windows.Threading.Dispatcher}, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler = null)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd = {System.IntPtr}, int msg = 49648, System.IntPtr wParam = {System.IntPtr}, System.IntPtr lParam = {System.IntPtr})	Unknown
```

**Comment by Pilchie** [comment] 2015-10-22 03:10
@CyrusNajmabadi Is this a regression caused by your recent changes around either outlining and diff or outlining and line separators?

**Comment by Pilchie** [comment] 2015-10-22 04:27
Looks like a duplicate of #5959.

**Closed by Pilchie** 2015-10-22 04:27 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate

**Comment by davkean** [comment] 2015-10-22 04:30
Hmm, really? They look completely unrelated?

**Comment by Pilchie** [comment] 2015-10-22 04:33
Oh, oops.  Fixed number.

**Comment by CyrusNajmabadi** [comment] 2015-10-22 18:55
Will look asap.

**Comment by CyrusNajmabadi** [comment] 2015-10-22 18:58
This is definitely the code I added.  Will debug through to see why this is happening.
