### ISSUE TITLE
Code cleanup on save while resolving merge conflicts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60818] opened 2022-04-18 19:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-cleanup-on-save-while-resolving/10015181)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:VS2019]
With turned on feature 'Code Cleanup on Save', while resolving conflicts after merging branches, after applying changes all 'using' directives are gone.

---
#### Feedback Bot on 4/18/2022, 01:41 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by kakone** [comment] 2022-06-17 17:11
Very annoying, we must deactivate "Code Cleanup on Save" before resolving conflicts.

**Comment by DavidJohnWilliams** [comment] 2022-07-22 12:25
I don't know if this is the only time it happens, but I have noticed that if you have conflicts in a project file it causes the project to be unloaded. If you are then reviewing conflicts in a file within that project then it loads the files from outside of the project i.e. with the path to file on disk. Which means the code cleanup does not have context and removes all using statements. This happens even in the diff window not just the merge window.

As a workaround, it may be possible that resolving project conflicts first prevents this from happening.

**Comment by MatthieuTruchet-VA** [comment] 2022-08-04 07:14
Hi,

We have the same behavior.

Any news on this issue ?

**Comment by kakone** [comment] 2022-08-09 13:42
> As a workaround, it may be possible that resolving project conflicts first prevents this from happening.
Unfortunately not. I didn't find any workaround apart from deactivating "Code Cleanup on Save".

**Comment by AbdullahAlRana** [comment] 2022-08-18 04:44
I am also facing the same problem, I found code cleanup feature very handy but for this problem I had to unable it.

**Comment by alexandresmoraes** [comment] 2022-09-12 17:31
i'm having the same behavior

**Comment by waitwhereami** [comment] 2022-09-27 13:02
Can confirm this is still a problem as of VS 2022 17.3.4. Very annoying bug.

**Comment by l-e-f** [comment] 2022-10-31 19:02
Confirming this is still an issue

**Comment by LiviuD** [comment] 2022-11-05 12:14
Still an issue, quite a big one.

**Comment by mblichowski** [comment] 2022-11-29 14:40
**Very** annoying

**Comment by fredrikbergman** [comment] 2022-12-01 07:47
Same for me in VS2022 17.4.2.. 🙁

**Comment by andreatosato** [comment] 2022-12-06 07:02
Same here

**Comment by cremor** [comment] 2022-12-06 07:03
Note that this not only removes all using directives, but also breaks the code style of the merged file by ignoring rules defined in the EditorConfig file.

If someone needs steps to reproduce:

1. Enable Options - Text Editor - Code Cleanup - Run Code Cleanup profile on Save
2. Make sure that the chosen Code Cleanup profile formats the document and removes unnecessary usings.
3. Do a Git merge that results in a conflict in a C# file.
4. Resolve the conflict. Note that the preview of the resulting file in the lower part of the conflict window shows everything as it should be.
5. Open the file after resolving the conflict.
6. Note that all usings are removed from the file, which breaks the code.
7. Also note that the formatting of the file was reset to the Visual Studio settings instead of the settings defined in the EditorConfig file.

**Comment by randyshoopman** [comment] 2022-12-13 17:59
Our team is also seeing this issue.  It's a big pain. Please fix. VS 17.4.0

**Comment by Bosch-Eli-Black** [comment] 2022-12-21 05:26
@JoeRobich Can we get a quick update on this? 🙂  Seems like lots of people are running into this (including myself! 😄)

**Comment by xania** [comment] 2022-12-21 15:59
Include me in the list of people having this issue.

**Comment by Bosch-Eli-Black** [comment] 2022-12-22 02:47
If anyone is looking for a quick workaround, here's what I do:

1. Make sure that the `Add missing using directives on paste` option is enabled (Tools -> Options -> Text Editor -> C# -> Advanced -> "Using directives" section)
2. After the editor has stripped out your `using` statements, open the file and do `Ctrl+A`, `Ctrl+X`, `Ctrl+V`

Basically, copying and pasting the document on top of itself triggers the `Add missing using directives on paste` functionality, which readds the `using` statements 🙂

**Comment by Bosch-Eli-Black** [comment] 2022-12-22 02:48
@sharwell Sorry to message you directly, but is @JoeRobich still the correct person to be assigned to this, or could we get a status update? 🙂   Seems like a lot of people are hitting this, especially in the newer versions of VS.

**Comment by EngWagner** [comment] 2022-12-29 13:37
@CSTI-IHarwell

**Comment by Bosch-Eli-Black** [comment] 2022-12-30 02:27
@EngWagner I'm guessing they're probably on Christmas or New Year's vacation 🙂

**Comment by xania** [comment] 2022-12-30 15:03
> If anyone is looking for a quick workaround, here's what I do:
> 
> 1. Make sure that the `Add missing using directives on paste` option is enabled (Tools -> Options -> Text Editor -> C# -> Advanced -> "Using directives" section)
> 2. After the editor has stripped out your `using` statements, open the file and do `Ctrl+A`, `Ctrl+X`, `Ctrl+V`
> 
> Basically, copying and pasting the document on top of itself triggers the `Add missing using directives on paste` functionality, which readds most of the `using` statements 🙂

This is unfortunately not working for me, first I have to find the file first which is the hardest part because I always forget the name of the file and regret it immediately after hitting the _accept merge_ button.

**Comment by AleksTem** [comment] 2023-01-03 12:12
I also have this annoying issue. Visual Studio Professional 2022 (64bit) 17.4.3

**Comment by Carl-Granstrom** [comment] 2023-01-24 12:21
Also suffering from this. It's also not only when resolving merges, VS always removes all using directives except System ones when I run code cleanup.

**Comment by et3rnalcynic** [comment] 2023-01-27 15:51
I literally created an account on github just to thumbs-up this post, though my whole team has been dealing with this since last year. Visual Studio Professional (64 bit) 17.4.4

**Comment by Dreamescaper** [comment] 2023-01-27 16:03
I'm using [CodeCleanupOnSave](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CodeCleanupOnSave) extension, which has the same functionality. It is very strange that this issue is still present after almost a year. It is also funny that it's  an extension by [Mads Kristensen](https://devblogs.microsoft.com/visualstudio/author/madsk/) :) .

**Comment by Bosch-Eli-Black** [comment] 2023-01-30 03:22
Hi @sharwell, now that it's after Christmas/New Year's vacation, can we confirm that @JoeRobich is the correct person to be assigned to this? It seems this is affecting a lot of people, and there hasn't been any visible activity from @JoeRobich since April 20th, 2022 😄

**Comment by mwasson74** [comment] 2023-01-30 14:08
> Hi @sharwell, now that it's after Christmas/New Year's vacation, can we confirm that @JoeRobich is the correct person to be assigned to this?
> 
> It seems this is affecting a lot of people, and there hasn't been any visible activity from @JoeRobich since April 20th, 2022 😄

And that activity in April was not even by Joe, it was by @jinujoseph who assigned Joe to this... 🤯

**Comment by vmelamed** [comment] 2023-01-30 21:39
Please, fix this. Like many here said already, it is extremely annoying...

**Comment by phse0** [comment] 2023-02-01 14:23
We have the same issue. i disabled that for the moment...Hope it will get fixed soon

**Comment by Kraego** [comment] 2023-02-02 07:09
Shouldn't this issue be moved to VS? How should the roslyn analyzer know that VS in "merge resolution mode"? Shouldn't VS disable the autoformat feature during merging.

**Comment by Dreamescaper** [comment] 2023-02-02 09:39
@Kraego 
I don't think it should care whether it's "merge mode" or not. It shouldn't remove all 'using' directives anyway.

**Comment by cremor** [comment] 2023-02-02 10:29
Please don't forget that this bug is not just about the usings that are removed. The code cleanup also applies "wrong" code style options on merge. (It uses the current VS settings instead of the ones defined in the editorconfig file.)

**Comment by Kraego** [comment] 2023-02-02 13:48
@Dreamescaper 
> @Kraego I don't think it should care whether it's "merge mode" or not. It shouldn't remove all the 'using' directives anyway.

I wrote this in the hope of a reassignment, since the current assignee @JoeRobich didn't have any activity on github since april 22.

But you're right a reporter should not make assumptions of the failure source.

**Comment by stevenveerbeek** [comment] 2023-02-15 09:11
Same issue here, really frustrating 😕

**Comment by EngWagner** [comment] 2023-02-26 01:34
No action taken yet... Regrettable. :(

**Comment by luccawilli** [comment] 2023-03-02 07:29
I'm facing the same issue, VS 17.4.3

**Comment by nomadedge** [comment] 2023-03-10 06:45
Visual Studio 17.5.1 the issue is still a thing. It's almost a year now since the issue was created...

**Comment by EngWagner** [comment] 2023-03-30 16:59
This bug is almost having a birthday lol

**Comment by Bosch-Eli-Black** [comment] 2023-03-31 02:41
I see that sharwell removed JoeRobich and marked this as `help wanted`. Thanks, @sharwell 🙂

**Comment by DarkGraySun** [comment] 2023-04-20 11:08
Please fix the bug. My teammates are already using alternative merge tools, I can't get them back to the Visual Studio standard.
(Simple "Enable Code Cleanup" checkbox only in the merge window that I uncheck?)

**Comment by wokket** [comment] 2023-05-05 20:50
I've been tearing my hair out over why merges where losing usings, finding out MS has known about this for over a year and hasn't even responded on the ticket 😡

**Comment by 21r8390** [comment] 2023-05-24 07:47
Can please @CyrusNajmabadi @mavasani @sharwell @JoeRobich @Cosifne @genlu @beccamc @jasonmalinowski or someone  else have more clarity on why the second most updated bug is still not fixed after a year?

**Comment by Bosch-Eli-Black** [comment] 2023-05-24 08:40
I feel like part of the problem is that this seems like a VS issue, but it's logged in the Roslyn repo.

**Comment by cremor** [comment] 2023-05-24 10:20
All Visual Studio bug reports (on the MS Developer Community) were closed as duplicates of this GitHub issue.

**Comment by Bosch-Eli-Black** [comment] 2023-05-24 12:52
Ya, that's part of what concerns me 😅

**Comment by sharwell** [comment] 2023-05-24 15:24
The IDE just instructs the language service to "run cleanup" with a given profile. The actual changes being made in response to that instruction are defined by the language service, which in this case is Roslyn. We haven't had the chance to investigate what makes a merge situation different from other situations. If someone wanted to investigate, this is the specific block of code which is responsible for removing using directives during this operation:

https://github.com/dotnet/roslyn/blob/6e2fc198af168657419b1fd1513365a293c782e3/src/Features/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs#L115-L123

**Comment by cremor** [comment] 2023-05-24 17:07
> If someone wanted to investigate, this is the specific block of code which is responsible for removing using directives during this operation

As I've explained in [my comment above](https://github.com/dotnet/roslyn/issues/60818#issuecomment-1338878613), this issue is not just about the removal of using statements. So the bug might be somewhere else (or there are multiple bugs).

**Comment by rab0805** [comment] 2023-05-25 06:41
Just merged in 17.6 the usings where not removed. Can anyone confirm this?

**Comment by Bosch-Eli-Black** [comment] 2023-05-25 07:07
Thanks, @sharwell, good to know 🙂

**Comment by luccawilli** [comment] 2023-05-25 11:18
Thank you @sharwell for the code ref.

As far as i can tell, the problem lies in how the cleanup works.
You can see it pretty well in the CSharpUnnecessaryImportsProvider class.
The semantic model gets diagnosed and the resulting diagnostic output will then be filtered for "CS8019" warnings. And then all usings which triggered such a warning will be removed.
https://github.com/dotnet/roslyn/blob/6e2fc198af168657419b1fd1513365a293c782e3/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Helpers/RemoveUnnecessaryImports/CSharpUnnecessaryImportsProvider.cs#L30

Presumably not everything is loaded in the semantic model. Otherwise no warnings would arise.

You can see the same behavior when using the "Compare with unmodified..." command in the git changes panel or in the merge conflict view. If you try to use IntelliSense to find a local class (or some class in a imported namespace) you will be disappointed, nothing will be suggested.

For me there are now two options, first removing of unnecessary imports should be disabled in this "compare/merge views" or secondly the imported namespaces must also be loaded in the "compare/merge views". 
But I am unsure if the necessary changes can be made here in the roslyn repository.

**Comment by Kraego** [comment] 2023-05-25 16:10
Imho I would go a step further than @luccawilli pointed out in his first suggestion. For me it would be okay to disable the format on save completely in the merge view.

**Comment by tim-davies-oneadvanced** [comment] 2023-06-29 08:44
Please fix it!

**Comment by holmes-mike** [comment] 2023-06-29 10:29
This is becoming increasingly annoying, (i.e. forgetting to restore using prior to a force push and discovering CI build failures).
I'm now having to resort to VS code for rebasing/merge conflict resolution...

**Comment by vmelamed** [comment] 2023-07-05 16:03
There are many people here who are experiencing this extremely annoying and counterproductive bug. I wonder if we can collect enough bribe money to have someone fix this 15-month-old bug...?

**Comment by olegtk** [comment] 2023-07-07 23:15
Moved to VS Editor, tracked internally as https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1847852, tracked externally as https://developercommunity.visualstudio.com/t/Code-cleanup-on-save-while-resolving/10015181 (please vote on it).

**Closed** 2023-07-08 00:09 UTC
Labels: Bug, help wanted, Area-IDE, Investigation Required, Developer Community

**Comment by mwasson74** [comment] 2023-07-08 00:28
Closed and back to the original Developer Community issue? Can someone please help me understand?

**Comment by cremor** [comment] 2023-07-08 05:41
I assume someone analyzed the bug in detail and noticed that is is not a bug in Roslyn, but in VS itself.

**Comment by waitwhereami** [comment] 2023-07-08 05:50
Bully work, all of us ignored for 15 months because of some good old fashioned buck passing at MS. Couldn't be arsed to verify where the issue really was in 2022 when it was buck-passed to Roslyn, so here we are again.

**Comment by sharwell** [comment] 2023-07-10 13:00
We did a bunch of work last week to consolidate feedback on this issue to the team that now has ownership of it. Please place additional feedback on the tracking issue, as feedback here will not be seen by the team working on a fix for the issue.
