### ISSUE TITLE
Excessive memory usage (almost 20GB!)

### ISSUE THREAD

**Issue by jons-aura** [dotnet/roslyn#50331] opened 2021-01-08 16:26 UTC
**Version Used**: 

Executable file version is 2.7.100.16974

**Steps to Reproduce**:

1. Open a moderate sized solution (8 projects, half test projects), run some unit tests or debug and watch memory usage skyrocket.

**Expected Behavior**:

Reasonable memory and CPU usage.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/35536253/104039157-0547a580-51a4-11eb-8528-143ab3a36284.png)

**Comment by sharwell** [comment] 2021-01-12 21:07
Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.

Based on the information provided so far, the most likely scenario to follow is for "Slowness and High CPU Issues". Please look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#slowness-and-high-cpu-issues

**Comment by sharwell** [comment] 2021-01-12 21:08
Closing since this will need to be re-filed through developer community.

**Closed by sharwell** 2021-01-12 21:07 UTC
Labels: Area-IDE, Bug
