### ISSUE TITLE
IDE1006 should support fix all

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#49846] opened 2020-12-08 04:11 UTC
Naming style warnings/error have a single fix but no fix all support.

**Comment by ryzngard** [comment] 2020-12-08 18:03
Possible dupe of #48381 . Not sure if we want to track this as a code cleanup option

**Comment by JoeRobich** [comment] 2020-12-08 23:21
Dupe of https://github.com/dotnet/roslyn/issues/14983

**Closed** 2020-12-09 18:47 UTC
Labels: Area-IDE, Resolution-Duplicate
