### ISSUE TITLE
Unlike C#, VB string literals in attributes aren't treated as strings until you close them

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#11224] opened 2016-05-10 22:12 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/15164112/7fc3feda-16c1-11e6-95d8-a1ad8bc67f14.png)

``` VB
        ''' <summary>
        ''' Returns the ProjectProperties object from a VSLangProj-based project (VB, C#, J#).  Used for querying
        '''   common project properties in these types of projects.  Should only be used if you are certain of the
        '''   project type.  Otherwise, use CommonPropertiesObject.
        ''' </summary>
        ''' <value></value>
        ''' <remarks></remarks>
        <DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)>
        <Obsolete("This is 
        Public ReadOnly Property ProjectProperties() As VSLangProj.ProjectProperties
            Get
                Return _projectPropertiesObject
            End Get
        End Property
```

**Comment by davkean** [comment] 2016-05-10 23:03
Even in C# if you use verbatim strings, which is similar to the VB, you don't get completion while typing above.

**Comment by markhurd** [comment] 2016-06-08 06:25
Is this with a current build? I can't reproduce it in VS2015 Update 2.

**Comment by AdamSpeight2008** [comment] 2016-06-08 17:12
I think this done on purpose as before vb would end the parsing of a string at the end of the line.
Now it is in "a lesser" broken state, than assume the rest of the source is part the string, end the parse at the next `"` (not escaped). Thus breaking the previous valid string.

**Comment by hartmair** [comment] 2020-07-07 11:24
I am not able to reproduce this in VS 2019 16.6.3, i.e.

- no completion while typing
![image](https://user-images.githubusercontent.com/998108/86772570-90f54380-c054-11ea-9928-176ea1542ee0.png)

- parity with C# verbatim strings
![image](https://user-images.githubusercontent.com/998108/86772814-06f9aa80-c055-11ea-95f5-ec540694e66c.png)

**Comment by CyrusNajmabadi** [comment] 2020-07-07 19:23
Going to close this out.  If you still repro this Dave, let us know.

**Closed by CyrusNajmabadi** 2020-07-07 19:23 UTC
Labels: Area-Compilers, Bug, Language-VB, help wanted

**Comment by davkean** [comment] 2020-07-07 23:25
Yep, can't repro this anymore.
