### ISSUE TITLE
VS 15.9.8 Unknown Hard Error ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36672] opened 2019-06-21 22:34 UTC
VSF_TYPE_MARKDOWNTyping or pasting this line of code into the IDE will immediately cause a crash with error message: Unknown Hard Error.

```
A a&lt;int, ItrPtr, =
```

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentOutOfRangeException: Position is not within syntax tree with full span [5573..5733)
Parameter name: position
Actual value was 5538.
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32 position, SyntaxToken&amp; token)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetAdjustedNodePosition(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(LocalFunctionStatementSyntax declarationSyntax, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaOrLocalFunctionParameterSymbol(ParameterSyntax parameter, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(ParameterSyntax declarationSyntax, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(ParameterSyntax declarationSyntax, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolsCore(SyntaxNode declaration, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.IsDiagnosticSuppressed(String id, Location location, SuppressMessageInfo&amp; info)
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ApplySourceSuppressions(Diagnostic diagnostic, ISymbol symbolOpt)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.FilterDiagnosticsSuppressedInSource(ImmutableArray`1 diagnostics, Compilation compilation, SuppressMessageAttributeState suppressMessageState)
   at Microsoft.CodeAnalysis.Diagnostics.AnalysisResultBuilder.StoreAnalysisResult(AnalysisScope analysisScope, AnalyzerDriver driver, Compilation compilation, Func`2 getAnalyzerActionCounts, Boolean fullAnalysisResultForAnalyzersInScope)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.&lt;ComputeAnalyzerDiagnosticsCoreAsync&gt;d__64.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1&lt;System.Exception&gt;)
   at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;ComputeAnalyzerDiagnosticsCoreAsync&gt;d__64.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32, Microsoft.CodeAnalysis.SyntaxToken ByRef)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetAdjustedNodePosition(Microsoft.CodeAnalysis.SyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaOrLocalFunctionParameterSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolsCore(Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.IsDiagnosticSuppressed(System.String, Microsoft.CodeAnalysis.Location, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageInfo ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ApplySourceSuppressions(Microsoft.CodeAnalysis.Diagnostic, Microsoft.CodeAnalysis.ISymbol)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.FilterDiagnosticsSuppressedInSource(System.Collections.Immutable.ImmutableArray`1&lt;Microsoft.CodeAnalysis.Diagnostic&gt;, Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState)
   at Microsoft.CodeAnalysis.Diagnostics.AnalysisResultBuilder.StoreAnalysisResult(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver, Microsoft.CodeAnalysis.Compilation, System.Func`2&lt;Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer,Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerActionCounts&gt;, Boolean)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;ComputeAnalyzerDiagnosticsCoreAsync&gt;d__64.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;ComputeAnalyzerDiagnosticsCoreAsync&gt;d__64, Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](&lt;ComputeAnalyzerDiagnosticsCoreAsync&gt;d__64 ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1&lt;Microsoft.CodeAnalysis.Diagnostics.CompilationEvent&gt;, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;&gt;c__DisplayClass57_2+&lt;&lt;ComputeAnalyzerDiagnosticsAsync&gt;b__1&gt;d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;&gt;c__DisplayClass57_2+&lt;&lt;ComputeAnalyzerDiagnosticsAsync&gt;b__1&gt;d, Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](&lt;&lt;ComputeAnalyzerDiagnosticsAsync&gt;b__1&gt;d ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+&lt;&gt;c__DisplayClass57_2.&lt;ComputeAnalyzerDiagnosticsAsync&gt;b__1()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/485564/vs-1598-unknown-hard-error-argumentoutofrangeexcep.html
VSTS ticketId: 817403_
_These are the original issue comments:_

Visual Studio Feedback System on 3/11/2019, 11:52 PM (101 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2019-06-24 17:22
@chsienki Might this be related to the parsing issue you fixed recently, which resulted in roundtripping issue (ie. length is not the actual length).

**Comment by chsienki** [comment] 2019-06-24 19:29
Interesting, this looks like the same crash, but is probably a different cause; I don't think we shipped any of the using decl bits that I fixed pre 16.0

What's the servicing bar for 15.9? @heejaechang fixed the IDE in 16.0 so we don't hard crash in these cases. It might be simplest to just port that https://github.com/dotnet/roslyn/pull/36620

**Comment by KirillOsenkov** [comment] 2020-03-12 22:35
We're seeing this in VSMac 8.5:

```
ERROR [2020-03-05 12:41:10Z]: Roslyn non-fatal exception
System.ArgumentOutOfRangeException: Position is not within syntax tree with full span [1821..1857)
Parameter name: position
Actual value was 204.
  at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition (System.Int32 position, Microsoft.CodeAnalysis.SyntaxToken& token) [0x000c4] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1208 
  at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition (System.Int32 position) [0x00000] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1175 
  at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbol (System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:4653 
  at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbolCore (System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:5065 
  at Microsoft.CodeAnalysis.SemanticModel.GetEnclosingSymbol (System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Compilers/Core/Portable/Compilation/SemanticModel.cs:779 
  at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions.IsInstanceContext (Microsoft.CodeAnalysis.SyntaxTree syntaxTree, Microsoft.CodeAnalysis.SyntaxToken targetToken, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs:1813 
  at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker (Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00124] in /_/src/Workspaces/CSharp/Portable/Extensions/ContextQuery/CSharpSyntaxContext.cs:211 
  at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContext (Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Workspaces/CSharp/Portable/Extensions/ContextQuery/CSharpSyntaxContext.cs:151 
  at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.CreateContext (Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Int32 position, System.Threading.CancellationToken cancellationToken) [0x00000] in /_/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs:24 
  at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService`1[TSyntaxContext].GetRecommendedSymbolsAtPositionAsync (Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Int32 position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) [0x00011] in /_/src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs:31 
  at Microsoft.CodeAnalysis.Recommendations.Recommender.GetImmutableRecommendedSymbolsAtPositionAsync (Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Int32 position, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) [0x00078] in /_/src/Workspaces/Core/Portable/Recommendations/Recommender.cs:52 
  at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync (Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext context, Microsoft.CodeAnalysis.Document document, System.Int32 position, System.Lazy`1[T] inferredTypes, Microsoft.CodeAnalysis.Options.OptionSet options, System.Boolean preselect, Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider+TelemetryCounter telemetryCounter, System.Threading.CancellationToken cancellationToken) [0x000b1] in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:301 
  at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync (Microsoft.CodeAnalysis.Completion.CompletionContext context) [0x002b0] in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:279 
```

**Comment by tmat** [comment] 2020-07-15 18:23
Hit this again.

**Comment by CyrusNajmabadi** [comment] 2020-07-15 18:24
How can a syntaxtree haev a FullSpan that doesn't start at 0?

**Comment by KirillOsenkov** [comment] 2020-12-30 00:25
Is https://github.com/dotnet/roslyn/issues/44299 related or the same issue?

**Comment by Youssef1313** [comment] 2021-01-10 22:23
> How can a syntaxtree haev a FullSpan that doesn't start at 0?

I guess this might be a SyntaxNode passed somewhere *as if* it's the root, but it's actually not the root.

**Comment by KirillOsenkov** [comment] 2021-02-05 06:19
OK I have just reproduced this under debugger:

![image](https://user-images.githubusercontent.com/679326/106996904-b0f9fc00-6736-11eb-9ab3-d62a9d2edb0d.png)

I've marked the positions from the error message:
```
Position is not within syntax tree with full span [29615..29967)
Parameter name: position
Actual value was 29435.
```

Stack:
```
Microsoft.CodeAnalysis.CSharp	CSharpSemanticModel.CheckAndAdjustPosition Line 1300
Microsoft.CodeAnalysis.CSharp	CSharpSemanticModel.GetEnclosingSymbol Line 4828
Microsoft.CodeAnalysis.CSharp	CSharpSemanticModel.GetEnclosingSymbolCore Line 5248
Microsoft.CodeAnalysis.CSharp.Workspaces	SyntaxTreeExtensions.IsInstanceContext Line 2010
Microsoft.CodeAnalysis.CSharp.Workspaces	CSharpSyntaxContext.CreateContextWorker Line 217
Microsoft.CodeAnalysis.CSharp.Workspaces	CSharpRecommendationService.CreateContextAsync Line 26
Microsoft.CodeAnalysis.Workspaces	AbstractRecommendationService`1.GetRecommendedSymbolsAtPositionAsync
Microsoft.CodeAnalysis.Workspaces	Recommender.<GetImmutableRecommendedSymbolsAtPositionAsync>d__2.MoveNext Line 50
Microsoft.CodeAnalysis.Workspaces	Recommender.GetImmutableRecommendedSymbolsAtPositionAsync
Microsoft.CodeAnalysis.CSharp.Features	SymbolCompletionProvider.GetSymbolsAsync Line 38
Microsoft.CodeAnalysis.Features	AbstractSymbolCompletionProvider.GetSymbolsAsync Line 362
Microsoft.CodeAnalysis.Features	AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__19.MoveNext Line 317
Microsoft.CodeAnalysis.Features	AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__17.MoveNext Line 276
Microsoft.CodeAnalysis.Features	CompletionServiceWithProviders.<GetContextAsync>d__35.MoveNext Line 544
Microsoft.CodeAnalysis.Features	CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__29.MoveNext Line 414
Microsoft.CodeAnalysis.Features	CompletionServiceWithProviders.<GetCompletionsWithAvailabilityOfExpandedItemsAsync>d__26.MoveNext Line 312
Microsoft.CodeAnalysis.Features	CompletionServiceWithProviders.<GetCompletionsAsync>d__25.MoveNext Line 254
Microsoft.CodeAnalysis.Features	AbstractSpellCheckCodeFixProvider`1.<CreateSpellCheckCodeIssueAsync>d__11.MoveNext
Microsoft.CodeAnalysis.Features	AbstractSpellCheckCodeFixProvider`1.<CheckNodeAsync>d__7.MoveNext Line 80
Microsoft.CodeAnalysis.Features	AbstractSpellCheckCodeFixProvider`1.<RegisterCodeFixesAsync>d__6.MoveNext
Microsoft.CodeAnalysis.EditorFeatures	CodeFixService.<>c__DisplayClass31_1.<ContainsAnyFixAsync>b__1 Line 745
Microsoft.CodeAnalysis.Workspaces	IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext Line 73
Microsoft.CodeAnalysis.EditorFeatures	CodeFixService.<ContainsAnyFixAsync>d__31.MoveNext Line 745
Microsoft.CodeAnalysis.EditorFeatures	CodeFixService.<GetFirstDiagnosticWithFixAsync>d__15.MoveNext
Microsoft.CodeAnalysis.EditorFeatures	CodeFixService.<>c__DisplayClass14_0.<GetMostSevereFixableDiagnosticAsync>b__2 Line 114
```

The SemanticModel in question is MethodBodySemanticModel

**Comment by KirillOsenkov** [comment] 2021-02-05 06:25
OK I have a solid repro:

You'll want to be debugging VS with first-chance exceptions.

Paste this code into a C# file:
```
class C
{
    void M()
    {
        HoverHere("");
    }

    void M2()
    {
        ThenHoverHere("");
    }
}
```

Hover over `HoverHere`, then hover over `ThenHoverHere`, maybe expand lightbulbs but don't make any edits. After some hovering and tinkering it will repro.

FYI @sharwell @CyrusNajmabadi I've found a simple repro for a long-standing elusive bug that was difficult to diagnose.

**Comment by KirillOsenkov** [comment] 2021-02-05 06:28
I'm almost positive that https://github.com/dotnet/roslyn/issues/44299 is the same issue. It's been pretty annoying over the years so it would be nice to prioritize this soonish.

See quotes from users in 44299:

> Peter Shaw on 5/15/2020, 07:42 AM:
> Been plaguing me for months in VS2019 now, and I've finally gotten fed up of it killing my IntelliSense!!

**Comment by KirillOsenkov** [comment] 2021-03-27 21:37
Here's another repro from #44299:

Type out this code (don't paste) and hover over the error squiggle:

```
using System.Collections.Generic;

class C
{
    Dictionary<string, string> d;

    public bool P { get; set; } d.Keys;

    public C()
    {
        d = 
    }
}
```

**Comment by KirillOsenkov** [comment] 2021-11-26 23:47
@jinujoseph I keep running into this, and there is a solid repro, would it be possible to prioritize this? Thanks!

**Comment by CyrusNajmabadi** [comment] 2022-10-31 23:07
We were able to fix this recently.  Closing this out.

**Closed by CyrusNajmabadi** 2022-10-31 23:07 UTC
Labels: Bug, Area-Compilers, Developer Community
