### ISSUE TITLE
Will IDE0305 not support Prepend?

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#70035] opened 2023-09-20 15:19 UTC
## Summary

```cs
int[] a = [1, 2, 3];
int[] b = [4, 5];

int[] x = a.Concat(b).ToArray();
// → int[] x = [..a, ..b];

int[] y = a.Append(4).ToArray();
// → int[] x = [..a, 4];

int[] z = a.Concat(b).Append(6).ToArray();
// → int[] x = [..a, ..b, 6];

int[] w = a.Prepend(0).ToArray();
// expected: int[] w = [0, ..a];
// actual: no code fix.
```

## Background and Motivation

I have VS17.8p2 installed and was trying the IDE0305 fixer against our own code and while I was surprised that `Append` could be fixed, `Prepend` was left out.

## Proposed Feature

The IDE0305 fixer supports `Prepend`.

**Comment by CyrusNajmabadi** [comment] 2023-09-20 16:09
Note. We're unlikely to do this as it would change the order the expressions are evaluated in.

**Comment by CyrusNajmabadi** [comment] 2024-10-26 15:57
Closing as by design.

**Closed by CyrusNajmabadi** 2024-10-26 15:57 UTC
Labels: help wanted, Area-IDE, Feature Request
