### ISSUE TITLE
Incorrect "name can be simplified" lightbulb with nullable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#34723] opened 2019-04-03 15:21 UTC
**Version Used**: 
3.1.0-beta1-19172-05+edd2de88fb3e84a097fb30b4070e0f219f624e40

**Repro**:
```C#
#nullable enable
using System;

class Program
{
    static void Main()
    {
        string? s1 = null;
        string s2 = EnsureInitialized(ref s1!, () => "hello");
    }

    public static T EnsureInitialized<T>(ref T target, Func<T> valueFactory) where T : class? =>
        target ?? (target = valueFactory());
}
```
That code produces a warning:
![image](https://user-images.githubusercontent.com/2642209/55490809-6111f180-5602-11e9-810f-29fe7d712a34.png)

The warning then goes away if I explicitly specify the type parameter as `string`:
![image](https://user-images.githubusercontent.com/2642209/55490889-84d53780-5602-11e9-8891-48eb66a01dce.png)
but as is visible above, the IDE then suggests that the type parameter is unnecessary, and accepting the auto-fix removes the type parameter and reintroduces the warning.

cc: @dotnet/nullablefc

**Comment by YairHalberstadt** [comment] 2019-04-17 20:56
@AlekseyTs 

Ultimately this comes down to this line of code in SubstitutedMethodSymbol:

```csharp
public override bool Equals(object obj)
...
            for (int i = 0; i < arity; i++)
            {
                // TODO: what about annotations
                if (!TypeSymbol.Equals(this.TypeArgumentsWithAnnotations[i].Type, other.TypeArgumentsWithAnnotations[i].Type, TypeCompareKind.ConsiderEverything2))
                {
                    return false;
                }
            }
```

That TODO dates back to 2015, from a commit by you.
Is there any reason it shouldn't use annotations?

**Comment by AlekseyTs** [comment] 2019-04-17 21:11
> Is there any reason it shouldn't use annotations?

I don't think so.

As to the original issue. I believe at the moment IDE has no way to get information about inferred type arguments with nullability that is figured out by nullable analysis.

CC @333fred

**Comment by AlekseyTs** [comment] 2019-04-17 21:15
@dotnet/roslyn-ide Could you confirm if this scenario involves speculative binding and what IDE is trying to speculate on?

**Comment by YairHalberstadt** [comment] 2019-04-17 21:16
It does use speculative binding here.

**Comment by AlekseyTs** [comment] 2019-04-17 21:19
> It does use speculative binding here.

It would be good to have more details than just that. What API is used for speculation, with what syntax, at what position. Then we will be able to create a repro in the form of a compiler unit-test and get a better understanding of scenarios we might need to support.

**Comment by jasonmalinowski** [comment] 2019-04-17 21:21
> I believe at the moment IDE has no way to get information about inferred type arguments with nullability that is figured out by nullable analysis.

Right now the APIs for the IDE to get nullable information aren't even complete yet, but @333fred is working on it. It's expected that lightbulbs like this will be broken until that work is complete.

This may be a duplicate of #31849.

**Comment by YairHalberstadt** [comment] 2019-04-17 21:21
Sure. I have a unit test created for the diagnostic, and will try to create one for the compiler.

**Comment by YairHalberstadt** [comment] 2019-04-17 21:29
> It would be good to have more details than just that. What API is used for speculation, with what syntax, at what position. Then we will be able to create a repro in the form of a compiler unit-test and get a better understanding of scenarios we might need to support.

We use AbstractSpeculationAnalyzer.ReplacementChangesSemantics() on the GenericNameSyntaxes `EnsureInitialized<string>` and `EnsureInitialized`

**Comment by AlekseyTs** [comment] 2019-04-17 21:31
```AbstractSpeculationAnalyzer``` is not an API in the compiler layer

**Comment by YairHalberstadt** [comment] 2019-04-17 21:54
I'm using the simplified test case:

```csharp
using System;
#nullable enable
public class C {
    public void M() {
       	string? s1 = null;
        string s2 = M1<string>(ref s1!);
    }
    
    public T M1<T>(ref T t) where T : class? => t;
```

We use `CSharpExtensions.TryGetSpeculativeSemanticModel(this SemanticModel semanticModel, int position, StatementSyntax statement, out SemanticModel speculativeModel)`, with the LocalDeclarationStatement `string s2 = M1<string>(ref s1!);` and position 112

**Comment by AlekseyTs** [comment] 2019-04-17 22:02
And then? Where the logic breaks down? What value confuses IDE layer at the end and what would we expect to get instead?

**Comment by YairHalberstadt** [comment] 2019-04-17 22:12
The type returned is `M1<oblivious string>` whereas the original type is `M1<non-nullable string>`

Because we don't compare type annotations equality in `SubstitutedMethodSymbol.Equals`, they're considered equal. If we change it, then the following case fails to warn, even though it shouldn't, since the speculative node is oblivious:

```csharp
using System;
#nullable enable
public class C {
    public void M() {
       	string? s1 = null;
        string s2 = M1<string>(s1!);
    }
    
    public T M1<T>(T t) where T : class? => t;
```

**Comment by AlekseyTs** [comment] 2019-04-17 22:18
> The type returned is `M1<oblivious string>` whereas the original type is `M1<non-nullable string>`

What API is used to get that? ```TryGetSpeculativeSemanticModel``` simply returns a SemanticModel.

> Because we don't compare type annotations equality in `SubstitutedMethodSymbol.Equals`, they're considered equal.

I am missing something here. It looks like the code uses ```TypeCompareKind.ConsiderEverything2``` option, I would expect the difference in nullable annotation to be significant, i.e. not equal.

**Comment by AlekseyTs** [comment] 2019-04-17 23:01
Opened https://github.com/dotnet/roslyn/issues/35083 for the ```SubstitutedMethodSymbol.Equals``` implementation. However, I am pretty sure fixing that would likely be insufficient for the IDE scenario.

**Comment by YairHalberstadt** [comment] 2019-04-18 06:44
> What API is used to get that? TryGetSpeculativeSemanticModel simply returns a SemanticModel.

We use `SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken = default(CancellationToken)).Symbol` on the speculative model, with `IdentifierNameSyntax M1`.

**Comment by ryzngard** [comment] 2019-04-23 20:45
Looks related to #35031

**Comment by ryzngard** [comment] 2019-06-26 22:24
With the current state of master, this looks to be fixed. Testing with the below, I don't have any warnings or suggestions that type parameters can be removed. I'll keep open as I think it's worth adding tests for this behavior as well. 

```C#
        static void M()
        {
            string? s1 = null;
            string s3 = M1<string>(s1!);
            string s2 = EnsureInitialized<string>(ref s1!, () => "hello");
        }

        static T EnsureInitialized<T>(ref T target, Func<T> valueFactory) where T : class ? =>
            target ?? (target = valueFactory());

        static T M1<T>(T t) where T : class? => t;
```

**Closed** 2019-08-20 07:00 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, New Language Feature - Nullable Reference Types, help wanted
