### ISSUE TITLE
IDE0071 suggests simplification for `$"{ToString()}"` to `$"{ToString}"` then CS0428 suggests `$"{string}"`

### ISSUE THREAD

**Issue by jadaml** [dotnet/roslyn#43902] opened 2020-05-02 09:12 UTC
**Version Used**:
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
IntelliCode Extension   1.0

**Steps to Reproduce**:

1. Anywhere in a class instance implementation assign or return the `$"{ToString()}"` string.

**Expected Behavior**:
IDE0071 *not* presented *OR* suggesting to use `$"{this}"` instead.

**Actual Behavior**:
IDE0071 presented, suggesting to replace the interpolation to `$"{ToString}"` which generates (even in the preview) the CS0428 error. But even though the error message suggest invoking the method, the associated suggestion offers to change the string to `$"{string}"` which generates the CS1525.

**Additional**:

* This is a fresh installation, and I had no opportunity yet to change the Code Style options. for C#
* This bug looks fairly similar to #42669, but I opened a new issue, since it was closed and do not know if this was addressed.

**Comment by jnm2** [comment] 2020-05-02 15:28
This is a duplicate of https://github.com/dotnet/roslyn/issues/41381 and has been fixed in 16.6 previews. Really appreciate you taking the time to file though!

**Comment by CyrusNajmabadi** [comment] 2020-05-02 18:10
Dupe of https://github.com/dotnet/roslyn/issues/41381.  Closing out.

**Closed by CyrusNajmabadi** 2020-05-02 18:10 UTC
