### ISSUE TITLE
Rename doubles characters when identifier is at the end of the document

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#68375] opened 2023-05-30 03:39 UTC
When the identifier being renamed is at the end of the document, after a few characters being typed, the characters start to double up, and not match what is actually being typed. Additionally, after backspacing because I noticed the error, the rename operation got committed without me hitting Enter. If I had empty space at the end of the file, the issue doesn't repro.

See GIF.

![RenameDoubleChars](https://github.com/dotnet/roslyn/assets/754264/23b38b4c-a6b6-423b-9d1f-28be3871c0b8)

**Comment by Gnamra** [comment] 2023-08-12 20:03
This issue is very frustrating and doesn't only apply to identifiers renamed at the end of the document unfortunately.
I've attached a gif showing this, and while developing this happens sporadically to me with one time visual studio crashing. 

![Animation](https://github.com/dotnet/roslyn/assets/1496695/a0245d9f-04c6-45a2-8768-006a0d63e206)

I hope that this issue can be prioritized higher due to the fact that it doesn't only apply to identifiers at the end of the document.

**Comment by davidwengier** [comment] 2023-08-12 22:37
The cursor jumping was also happening to me in https://github.com/dotnet/roslyn/issues/68374 though not to a different line. Perhaps the two bugs are related though, and have a common cause (or you're just really unlucky and hitting both at the same time 😁)

**Comment by Gnamra** [comment] 2023-08-13 08:41
It bothered me that I wasn't not able to replicate the issue perfectly every time, in the gif I posted you can see me erasing the name of the class multiple times as I try to show the issue, before it actually occurs. While playing around I realized that the amount of characters from the identifier to the end of the document is key for replicating this issue, explaining why it occurs so sporadically. 

Knowing this I was able to do some controlled testing and verify on my machine that all identifiers in a document are affected by this issue. Adding text or code after the identifier does not fix the issue, it just increases the required length of the identifier for the issue to present itself. 

My gut feeling is that the cursor jumping mentioned in #68374 is related. I'm not sure that this is related to Roslyn, perhaps it's just a bug in the renaming functionality in visual studio?

**Comment by CyrusNajmabadi** [comment] 2023-08-13 15:06
@ryzngard can you take a look?

If we can't fix this, do we still have the prior UI that we could potentially roll back to until we get this resolved?  Thanks!

**Comment by sharwell** [comment] 2023-08-14 17:32
Duplicate of #68880

**Comment by sharwell** [comment] 2023-08-14 17:33
@CyrusNajmabadi @ryzngard I marked this as a duplicate since the other issue has a detailed explanation of the conditions for the error to occur. See https://github.com/dotnet/roslyn/issues/68880#issuecomment-1622034478.

**Closed by sharwell** 2023-08-14 17:32 UTC
Labels: Area-IDE, Feature - Rename
