### ISSUE TITLE
Async method with nullable return type can return null

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26614] opened 2018-05-03 23:59 UTC
Currently, this produces a warning, but it should not.

```C#
using System.Threading.Tasks;

public class C {
    public async Task<string?> M() {
        await Task.Delay(10);
        return null; // warning CS8625: Cannot convert null literal to non-nullable reference or unconstrained type parameter.
    }
}
```

Found in nullable dogfood. Assigned to @cston

**Comment by cston** [comment] 2018-05-04 03:51
Duplicate of #23275.

**Closed by cston** 2018-05-04 03:51 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
