### ISSUE TITLE
CS8762 issues: unnecessarily pops up in a NotNullWhen+MaybeNullWhen combination and in some cases doesn't pop up at all

### ISSUE THREAD

**Issue by marchewek** [dotnet/roslyn#76140] opened 2024-11-28 16:11 UTC
Some say an image is worth 1k of words. I think the same is about code, so there you have it:

```csharp
class NullableIssues
{
	public bool Issue1(string key, [NotNullWhen(true)] out string? value)
	{
		// no error, even though `Issue1Internal` gives no guarantee on value's nullability
		// regardless of concrete type of generic type
		return Issue1Internal(key, out value);
	}

	private bool Issue1Internal(string key, out string? value)
	{
		value = null;
		return false;
	}

	public bool Issue2<T>(string key, [NotNullWhen(true)] out T? value)
	{
		// Error CS8762: Parameter 'value' must have a non-null value when exiting with 'true'.
		// even though `Issue2Internal` gives guarantee that value is not null on returning true
		// error for generic type, but interestingly enough no error for concrete type (at least for string)
		return Issue2Internal<T>(key, out value);

		// no error if you introduce an explicit variable - lmao
		var retval = Issue2Internal<T>(key, out value);
		return retval;
	}

	private bool Issue2Internal<T>(string key, [MaybeNullWhen(false)] out T value)
	{
		value = default(T);
		return false;
	}
}
```

**Version Used**: Visual Studio Enterprise 17.11.5

**Diagnostic Id**: CS8762

**Comment by RikkiGibson** [comment] 2024-12-02 19:15
Thanks for filing this issue. I believe everything I am seeing here is by design. Several comments to try and explain:

> ``// even though `Issue2Internal` gives guarantee that value is not null on returning true``

`Issue2Internal` doesn't appear to give such a guarantee. The nullability of its return depends on its type argument. To illustrate I will replace the type parameters with type argument `string?` in your sample.

```cs
	public bool Issue2<string?>(string key, [NotNullWhen(true)] out string? value)
	{
		return Issue2Internal<string?>(key, out value);

		var retval = Issue2Internal<string?>(key, out value);
		return retval;
	}

	private bool Issue2Internal<string?>(string key, [MaybeNullWhen(false)] out string? value)
	{
		value = null;
		return false;
	}
```

Instead, it's recommended to use `[MaybeNullWhen(false)]` rather than `[NotNullWhen(true)]` when implementing a `TryGetValue`-like method with a type parameter output. This allows the type argument's nullability to decide whether the result is nullable or not. See also https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md#nullable-attributes.

> ``// no error if you introduce an explicit variable - lmao``

This is a general limitation of C#'s nullable analysis. Conditional nullable state is only used when an expression is used directly in a flow control construct. Thus we can understand `if (x != null) x.M();`, but not `bool notNull = x != null; if (notNull) x.M();`. This is unlikely to change due to potentially very large increases in computational and conceptual complexity in doing so in the general case.

> ``// no error, even though `Issue1Internal` gives no guarantee on value's nullability``

Enforcement of `NotNullWhen` and similar attributes is prone to "nuisance warnings", so is only enforced in certain cases where we think it is unlikely for such nuisances to occur, including when:
- returned expression is a bool constant
- returned expression results in a conditional state (i.e. something about it implies the expression itself is performing a null test, including a call to a method attributed with `NotNullWhen` or similar conditional nullability attributes)

See #48425 and related issues for more motivation and details.

**Comment by RikkiGibson** [comment] 2024-12-12 22:37
Closing out the issue as by-design. Feel free to follow up if there are further questions or concerns. Thanks!

**Closed by RikkiGibson** 2024-12-12 22:37 UTC
Labels: Area-Compilers, Feature - Nullable Reference Types
