### ISSUE TITLE
Suggestion: Fade ! (null suppressing operator) if it suppressed nothing

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#40071] opened 2019-11-30 07:50 UTC
```cs
string? x = "";

// x is not null here.
string y = x!;
```
`!` here suppresses nothing and I think it would be convenient if VS faded this `!` operator.

**Comment by huoyaoyuan** [comment] 2019-11-30 10:39
Duplicate of #34714 .

**Closed** 2019-11-30 12:05 UTC
