### ISSUE TITLE
Format Document (^K^D) deletes needed line continuation underscores in VB.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69696] opened 2023-08-24 14:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Format-Document-KD-deletes-needed-li/10448372)._

---
[severity:It's more difficult to complete my work] [regression]
Whenever I press ^K^D to format a VB.NET code behind file in a web application, it removes many needed continuation underscore characters and breaks the application so it will no longer compile.

Example:
  
```
Dim ErrMsg As String = "Header line is empty!\n" _
                                      & "The first line of the file must contain header field names..."
```

Becomes:
  
```
Dim ErrMsg As String = "Header line is empty!\n" 
                                      & "The first line of the file must contain header field names..."
```

Removing the continuation character prevents it from compiling.

---
#### Feedback Bot on 8/23/2023, 09:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by frontier777** [comment] 2023-08-25 04:22
I have the same issue. And the suggestion that I have read elsewhere, to put an apostrophe (comment) at the end of the line, while it does preserve the underscores, it also breaks the old compiler.

**Comment by sharwell** [comment] 2023-10-09 22:01
I can't reproduce this while editing a VB document, and I also can't reproduce it in unit tests.

**Comment by CyrusNajmabadi** [comment] 2024-10-26 16:21
Closing out as not repro.

**Closed by CyrusNajmabadi** 2024-10-26 16:21 UTC
Labels: Bug, Area-IDE, IDE-Formatter
