### ISSUE TITLE
[Proposal] Null Event Binding and Unbinding

### ISSUE THREAD

**Issue by neurospeech** [dotnet/roslyn#10939] opened 2016-04-28 10:22 UTC
```
var c = cp?.Content;
if(c != null){
    c.PropertyChanged += C_PropertyChanged;
}
if(c != null){
    c.PropertyChanged -= C_PropertyChanged;
}
```

Can be easily written as

```
cp?.Content?.PropertyChanged += C_PropertyChanged;
cp?.Content?.PropertyChanged -= C_PropertyChanged;
```

**Comment by alrz** [comment] 2016-04-28 11:48
#1276

**Comment by gafter** [comment] 2016-04-28 14:04
This is a duplicate of #1276

**Closed** 2016-04-28 14:04 UTC
Labels: Area-Language Design, Resolution-Duplicate
