### ISSUE TITLE
Getting solution

### ISSUE THREAD

**Issue by typicalHuman** [dotnet/roslyn#42891] opened 2020-03-30 04:36 UTC
I need to get existing solution. I used MSBuildWorkspace, but there're 0 projects in solution, what I can do? (variant with AdhocWorkspace doesn't work too)
`using (var workspace = MSBuildWorkspace.Create())
            {
                var solution = workspace.OpenSolutionAsync(SolutionPath).Result;
            }`

**Comment by CyrusNajmabadi** [comment] 2020-03-30 05:00
If you listen to `workspace.WorkspaceFailed` do you get notified about any issues?

**Comment by sharwell** [comment] 2020-04-01 23:01
Duplicate of #41331

**Closed by sharwell** 2020-04-01 23:01 UTC
Labels: Area-IDE, IDE-MSBuildWorkspace, Question
