### ISSUE TITLE
Source generator doesn't have access to MSBuild metadata when items have '..' in path

### ISSUE THREAD

**Issue by pantosha** [dotnet/roslyn#52034] opened 2021-03-21 12:52 UTC
**Version Used**: VS 2019 16.9.2, Roslyn 3.9.0

**Steps to Reproduce**:

1. Write a source generator that operates `AdditionalFiles`
```csharp
foreach (var file in context.AdditionalFiles)
{
    var options = context.AnalyzerConfigOptions.GetOptions(file);
    Debug.Assert(
        options.TryGetValue("build_metadata.additionalfiles.IsTemplate", out var isTemplate),
        "AdditionalFiles option 'IsTemplate' is not found.");
}
```
2. Add `AdditionalFiles` items with `..` in an Include and metadata to project
```csproj
<ItemGroup Label="Bug">
  <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="IsTemplate" />
  <!-- Source generator doesn't have access to items metadata when items have '..' in path -->
  <AdditionalFiles Include="..\*.template" IsTemplate="true" />
</ItemGroup>
```

**Expected Behavior**:
`AnalyzerConfigOptions` for `AdditionalFile` contains defined metadata.

**Actual Behavior**:
`AnalyzerConfigOptions` doesn't provide access to defined metadata for `AdditionalFile`.

**Workaround**:
Use full path in `AdditionalFiles`:
```csproj
<ItemGroup Label="Workaround">
  <None Include="..\*.template" />
  <AdditionalFiles Include="@(None -> '%(FullPath)')" IsTemplate="true" />
</ItemGroup>
```

Full example: [source-generator-bug.zip](https://github.com/dotnet/roslyn/files/6177433/source-generator-bug.zip)

**Comment by mattleibow** [comment] 2021-06-08 10:52
I can confirm this happens and that using the `Include="@(TheItemGroup -> '%(FullPath)')"` works.

**Comment by chsienki** [comment] 2021-09-21 20:27
Dupe of https://github.com/dotnet/roslyn/issues/47786

**Closed by chsienki** 2021-09-21 20:27 UTC
Labels: Bug, Area-Compilers, New Feature - Source Generators
