### ISSUE TITLE
IntelliSense does not work for target-typed "new" expression (C# 9)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47289] opened 2020-08-31 16:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1167506/intellisense-does-not-work-for-target-typed-new-ex.html)._

---
[severity:I'm frustrated, but able to complete my work]
When I'm using new target-typed *new* expression, I don't get IntelliSense for all the properties the object has.
Say, I have a simple class:
```
class Worker
{
    public int Age { get; set; }
}
```
When I write new way:
```
Worker worker = new() { Age = 29 };
```
then I don't get IntelliSense after `{` character as I would get if I'd have written it old way:
```
Worker worker = new Worker { Age = 29 };
```
Morerover, the editor moves curly braces into new line, so I get this:
```
Worker worker = new()
{ Age = 29 };
```

**Additional Info:**
_.NET_: 5.0.100-preview.8.20417.9
_Visual Studio_: Community 2019 Preview 16.8.0 Prevew 2.0

---
#### Feedback Bot on 8/30/2020, 07:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2020-08-31 17:45
Duplicate of #46397

**Comment by CyrusNajmabadi** [comment] 2020-08-31 19:55
Closing as dupe of https://github.com/dotnet/roslyn/issues/46397.  Thanks :)

**Closed by CyrusNajmabadi** 2020-08-31 19:55 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
