### ISSUE TITLE
Intermittent test failure: BlockCommentEditingTests.EofCase0

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21480] opened 2017-08-13 16:44 UTC
https://ci.dot.net/job/dotnet_roslyn/job/dev15.5.x/job/windows_release_unit32_prtest/21/testReport/junit/Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.BlockCommentEditing/BlockCommentEditingTests/EofCase0/

```
MESSAGE:
System.IndexOutOfRangeException : Index was outside the bounds of the array.
+++++++++++++++++++
STACK TRACE:
at System.Collections.Generic.List`1.get_Item(Int32 index) at System.AggregateException..ctor(String message, IList`1 innerExceptions)
 at System.AggregateException..ctor(String message, IEnumerable`1 innerExceptions) at System.AggregateException..ctor(IEnumerable`1 innerExceptions)
 at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Flatten(ICollection`1 exceptions) 
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize) 
at Microsoft.CodeAnalysis.Workspace.Dispose() 
at Microsoft.CodeAnalysis.Editor.UnitTests.BlockCommentEditing.AbstractBlockCommentEditingTests.Verify(String initialMarkup, String expectedMarkup) 
at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.BlockCommentEditing.BlockCommentEditingTests.EofCase0() in q:\roslyn\src\EditorFeatures\CSharpTest\BlockCommentEditing\BlockCommentEditingTests.cs:line 81
```

Likely the same issue in Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets.CSharpSnippetExpansionClientTests.TestAddImport_EmptyDocument_SystemAtTop:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.5.x/job/windows_release_unit64_prtest/21/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets/CSharpSnippetExpansionClientTests/TestAddImport_EmptyDocument_SystemAtTop/

```
MESSAGE:
System.IndexOutOfRangeException : Index was outside the bounds of the array.
+++++++++++++++++++
STACK TRACE:
at System.Collections.Generic.List`1.get_Item(Int32 index)
 at System.AggregateException..ctor(String message, IList`1 innerExceptions)
 at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Flatten(ICollection`1 exceptions) 
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
 at Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets.CSharpSnippetExpansionClientTests.VB$StateMachine_21_TestSnippetAddImportsAsync.MoveNext() in q:\roslyn\src\VisualStudio\Core\Test\Snippets\CSharpSnippetExpansionClientTests.vb:line 388 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets.CSharpSnippetExpansionClientTests.VB$StateMachine_2_TestAddImport_EmptyDocument_SystemAtTop.MoveNext() in q:\roslyn\src\VisualStudio\Core\Test\Snippets\CSharpSnippetExpansionClientTests.vb:line 33
 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Pilchie** [comment] 2017-08-14 17:54
Duplicate of #21388.

**Closed by Pilchie** 2017-08-14 17:54 UTC
Labels: Area-IDE, Flaky, Test
