### ISSUE TITLE
String interpolation + LangVersion=10.0 + out parameters results in CS1615

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/roslyn#56579] opened 2021-09-21 15:39 UTC
**Version Used**: 

```
$ dotnet --version
6.0.100-rc.2.21420.30
```

**Steps to Reproduce**:

Code:

```csharp
using System;
using System.Text;

class App {
	void GenerateTypeLowering (out StringBuilder convs)
	{
		convs = new StringBuilder ();
		convs.Append ($"var v = default ({GetType ()});\n");
	}
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
</Project>
```

Setting LangVersion=9.0 makes the project build.

**Expected Behavior**:

Successful compilation.

**Actual Behavior**:

```
$ dotnet build /nologo /v:quiet
/Users/rolf/test/dotnet/consoleapp/Program.cs(12,17): error CS1615: Argument 3 may not be passed with the 'out' keyword
/Users/rolf/test/dotnet/consoleapp/Program.cs(12,17): error CS1615: Argument 4 may not be passed with the 'out' keyword
```

**Comment by 333fred** [comment] 2021-09-29 22:48
Closing as a duplicate of https://github.com/dotnet/roslyn/issues/56624.

**Closed by 333fred** 2021-09-29 22:48 UTC
Labels: Bug, Area-Compilers
