### ISSUE TITLE
Exclude attributes when outlining VB member declaration

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#54665] opened 2021-07-07 20:03 UTC
**Version Used**: 
Version 17.0.0 Preview 2.0 [31425.81.main]

Unlike C#, VB includes attributes in the outline and collapses them all to the same line as the method declaration signature.
When the attribute declaration is long this pushes the method name and parameters out.

C#:
![image](https://user-images.githubusercontent.com/41759/124821359-741f7480-df23-11eb-9ae8-ceaaae8f754c.png)

VB:
![image](https://user-images.githubusercontent.com/41759/124821376-7aadec00-df23-11eb-82d4-0d0c9ac707b7.png)

**Comment by CyrusNajmabadi** [comment] 2021-07-07 20:05
fun fact.  we did this earlier in roslyn and got heavy pushback for users (Since vb has behaved this way forever).  However, i do generally support this.  I just think we'll need an option here to opt in/out.

**Comment by tmat** [comment] 2021-07-07 20:33
What was the pushback? Could we collap
![image](https://user-images.githubusercontent.com/41759/124824991-eabe7100-df27-11eb-97d1-1e44252037a5.png)
se the attributes separately from the declaration like we do with doc comments?

**Comment by sharwell** [comment] 2021-08-02 20:47
Duplicate of #43285

**Closed by sharwell** 2021-08-02 20:47 UTC
Labels: Area-IDE, Concept-Continuous Improvement
