### ISSUE TITLE
Unexpected possible null reference warning on MaybeNullWhen out parameter

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40266] opened 2019-12-10 00:14 UTC
**Version Used**: 
16.5.0 Preview 2.0 [29529.20.master]

**Steps to Reproduce**:

```C#
#nullable enable

using System.Diagnostics.CodeAnalysis;

abstract class C<T>
{
    public abstract bool TryGetValue([MaybeNullWhen(false)]out T value);
}

class D<T> : C<T>
    where T : class
{
    private readonly C<T> _source;

    public D(C<T> source)
    {
        _source = source;
    }

    public override bool TryGetValue([MaybeNullWhen(false)]out T value)
    {
        return _source.TryGetValue(out value); // warning on out value
    }
}

```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

```
D.cs(22,40,22,45): warning CS8601: Possible null reference assignment.
```

**Comment by jcouv** [comment] 2019-12-11 22:32
Closing as duplicate of https://github.com/dotnet/roslyn/issues/39656

**Closed by jcouv** 2019-12-11 22:32 UTC
Labels: Area-Compilers, Language-C#, New Language Feature - Nullable Reference Types
