### ISSUE TITLE
Visual Studio crashes when Interface definition is wrong (wrongly generated by Visual Studio)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41624] opened 2020-02-12 21:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/877582/visual-studio-crashes-when-interface-definition-is.html)._

---
If a file has a wrong interface definitions which members used like in explicit interface implementation, Visual Studio 2019 (16.4.2) and also Visual Studio 2019 Preview (16.5.0 Preview 1.0) will crash without any error message.

Steps to reproduce:

1.) Create a file e.g. with the following content:

```
public interface ITest
{
    string Name { get; set; }
    string ITest.Greeting { get; set; }
}
```

2.) Open it in visual studio

==> Visual Studio will crash

or create it with Visual Studio in a project, this is even more annoying, because everytime you want to open the solution it loads the last opened files and will crash again right away because it opens this file. You have to delete the ".vs" folder in order to be able to open the solution again or delete/modify the file outside of Visual Studio. But then if you open the file again it will crash again.

So you could argue how did I end up with this clearly wrong interface definition, but this was not my fault, it was done by Visual Studio. Here are the steps how to end up with such an interface member.

1). Have an interface with at least one member. e.g. like this:

```
public interface ITest
{
    string Name { get; set; }
}
```

2.) implement that interface explicit in a class, e.g. like this:

```
public class Test : ITest
{
    string ITest.Name { get ; set }
}
```

3.) copy the Name property, paste it below and rename it, e.g:

```
public class Test : ITest
{
    string ITest.Name { get ; set }
    string ITest.Greeting { get ; set }
}
```

4.) press Ctrl + . on the new property and go to "Pull up to base type"
==> A file like the one given at the start with wrong interface member is created and Visual Studio crashes.

Now (if you managed to open Visual Studio again (deleting .vs) Visual Studio will not only crash if you open the file with the interface but also if you open the file containing a class that implements that interface or if you try to implement the interface on a new class.

So this are rather two issues:
1) The crash when opening those files
2) That "Pull up" to interface does not produce this crashing file if you execute it on an explicit interface member that's not yet in the interface

---
#### Fiona Niu[MSFT] on 1/8/2020, 00:35 AM: 

<p>Thank you for taking the time to log this issue! Could you please provide more information via the Visual Studio Feedback Tool(Help -&gt; Send Feedback -&gt; Report A Problem) so that we can conduct further research? The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:</p>
<pre><code>• Open Visual Studio Feedback tool.
• Click the banner letting you know that you have problems requesting your attention.
• Click this problem from the list
• Click &quot;View their request and respond&quot; from the problem details banner
• Add a comment, in the Attachments/Record: click Start Recording
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.
• When you're done, choose the Stop Record button.
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don't appear on Developer Community.
</code></pre>
<p>For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Alex Lambert on 1/8/2020, 11:16 AM: 

I thought I included all log/dump files in the issue..<br><br>Last time I tried to record the problem with the recorder (some month back), the recorder did procces for hours and did not finsih, so I had to cancel, hopefully it will work this time.<br><br>But you should also be able to reproduce the described crash easily on your machine (at least I got it to crash on another PC)
#### Fiona Niu[MSFT] on 1/8/2020, 06:32 PM: 

<p>Thanks a lot for providing the information. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/12/2020, 09:08 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 2/12/2020, 10:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment] 2020-02-12 21:24
@agocke Does this look like an issue fixed in https://github.com/dotnet/roslyn/pull/40175?

**Comment by AlekseyTs** [comment] 2020-02-12 21:37
I am not able to reproduce the crash in Microsoft Visual Studio Enterprise 2019 Int Preview Version 16.6.0 Preview 1.0 [29809.16.master].

**Closed by AlekseyTs** 2020-02-12 21:37 UTC
Labels: Area-Compilers, Bug

**Comment by agocke** [comment] 2020-02-12 21:47
Yup, looks resolved to me, thanks!
