### ISSUE TITLE
MetadataReferences return empty list for MonoAndroid and MonoTouch projects

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [dotnet/roslyn#5481] opened 2015-09-28 06:05 UTC
I created solution with 3 projects:
1. Windows Console Application
2. Xamarin Android Application
3. Xamarin iOS Application.

Only in first project, project.MetadataReferences returns not empty list. (project is Microsoft.CodeAnalysis.Project)
iOS and Android projects has references. And all projects have at least one same reference to my portable assembly.

**Comment by Pilchie** [comment] 2015-09-29 16:39
Can you provide a link to the project where you are seeing an issue?  Also, can you be more detailed about how you are opening the solution?

**Comment by MAX-POLKOVNIK** [comment] 2015-09-30 04:41
This is my test solution in VisualStudio:
![vsprojecttree](https://cloud.githubusercontent.com/assets/8066100/10184486/f86e6ac2-675e-11e5-8f3d-9ce9400acb64.png)

I open this solution as MSBuildWorkspace:
    var msWorkspace = MSBuildWorkspace.Create();
    var solution = await msWorkspace.OpenSolutionAsync(solutionPath);

Now I want get references of project. In simple console application:
![testextensionreferences](https://cloud.githubusercontent.com/assets/8066100/10184489/f870155c-675e-11e5-917b-8922f711b268.png)

But in android app:
![testextensionandroidreferences](https://cloud.githubusercontent.com/assets/8066100/10184488/f86f2732-675e-11e5-947e-eaa1848fe576.png)

And same in iOS:
![testextensionreferencestouch](https://cloud.githubusercontent.com/assets/8066100/10184487/f86eb36a-675e-11e5-8077-96554361d135.png)

Even in csproj file of android and ios apps has these lines:
<Reference Include="mscorlib" />
<Reference Include="System" />
<Reference Include="System.Core" />
<Reference Include="System.Xml" />

**Comment by MAX-POLKOVNIK** [comment] 2015-09-30 05:07
VS Solutions:
https://drive.google.com/file/d/0B74FM-rW6y0rMENnQkhyRWFvOEk/view?usp=sharing
https://drive.google.com/file/d/0B74FM-rW6y0rMkg1OGNGM21GVUk/view?usp=sharing

**Comment by jasonmalinowski** [comment] 2015-10-02 20:14
@MAX-POLKOVNIK: thanks for the bug, I've been able to reproduce it. As a workaround, if you add the following to your app.config of your app calling `MSBuildWorkspace`, this should address your issue:

    <?xml version="1.0" encoding="utf-8" ?>
    <configuration>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build.Conversion.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build.Tasks.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Build.Utilities.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
    </configuration>

@Pilchie, @mattwar: this is just another instance of #3034 which @mattwar just closed yesterday. I still think it's important to fix, but I'm not sure how close @mattwar was to actually getting everything to work. I'm happy to take another shot.

**Comment by jasonmalinowski** [comment] 2015-10-05 20:59
Looks like we'll count this as a duplicate of #3034, and track the underlying issue there if still needed.

**Comment by jasonmalinowski** [comment] 2015-10-05 21:00
Looks like we'll count this as a duplicate of #3034, and track the underlying issue there if still needed. @MAX-POLKOVNIK, let us know if that workaround doesn't work for you, and feel free to reopen the bug if you still have concerns.

**Comment by MAX-POLKOVNIK** [comment] 2015-10-06 04:51
@jasonmalinowski, Your workaround doesn't work for me. Still 0 references. I think because of this bug in Android & iOS projects SymbolFinder.FindCallersAsync doesn't work. In 3 projects I write Console.WriteLine()  method and try to find this symbol. SymbolFinder.FindCallersAsync works only in first project where MetadataReferences list not empty, in other two I cant find this symbol.

**Comment by jasonmalinowski** [comment] 2015-10-06 05:25
@MAX-POLKOVNIK: yeah, if you don't have references than semantics in general are going to be very broken. FindCallersAsync won't be the only thing not working.

**Comment by Pilchie** [comment] 2015-10-23 22:10
Hi @MAX-POLKOVNIK - I was also able to reproduce your issue with the projects above, but when I changed the app.config for `OpenSolution` to include the binding redirects that @jasonmalinowski mentioned, I get:

```
Project TestExtension has 4 MetadataReferences
Project TestExtensionAndroid has 5 MetadataReferences
Project TestExtensionTouch has 6 MetadataReferences
```

**Closed by Pilchie** 2015-10-23 22:10 UTC
Labels: API, Area-IDE, Resolution-Duplicate
