### ISSUE TITLE
folded comment with cref removes spacing after the reference term.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23389] opened 2017-11-27 09:47 UTC
If i have a comment like this ...

```csharp
/// <summary>
/// The <see cref="BodyPart"/> that the Transforms operate on.
/// </summary>
```

When i fold the comment, the space between 'BodyPart' and 'that is removed. So the folded comment looks like this ..

```csharp
/// <summary> The BodyPartthat the Transforms ..
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155566/folded-comment-with-cref-removes-spacing-after-the.html
VSTS ticketId: 529532_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2017-11-27 12:30
Duplicate of #20679

**Closed by sharwell** 2017-11-27 12:30 UTC
