### ISSUE TITLE
UseDefaultLiteral IDE Diagnostics (IDE0034) suggest wrong fix

### ISSUE THREAD

**Issue by nphmuller** [dotnet/roslyn#22748] opened 2017-10-18 15:38 UTC
**Version Used**: The version in VS15.4.0

**Steps to Reproduce**:
``` c#
namespace DefaultBug
{
    public class Program
    {
        public enum MyEnum
        {
            One,
            Two,
            Three
        }

        [Fact]
        public static void Main()
        {
            Method(default(MyEnum)); // Warning/suggestion IDE0034. default returns 'One'
            Method(default); // No warning/suggestion. 'default' returns  null.
        }

        public static void  Method(object obj)
        {
        }
    }
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Warning IDE0034.

**Comment by jcouv** [comment] 2017-10-18 15:48
Thanks for reporting this issue.
It is likely a duplicate of https://github.com/dotnet/roslyn/issues/22184

**Closed** 2017-10-18 15:49 UTC
Labels: Area-IDE, Resolution-Duplicate

**Comment by sharwell** [comment] 2017-10-18 15:51
@nphmuller Thank you for providing this sample. Even though this appears to be a duplicate, I made a note in the original issue to include your case as an additional test to prevent future regressions.
