### ISSUE TITLE
Missing File Banner not using the most common banner?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24658] opened 2018-02-06 02:58 UTC
I have four C# files with banners, one file has &quot;// Banner 1&quot; and three have &quot;// Banner 2&quot;. 

Now I added a new C# file, and try the Missing File Banner code fix.  &quot;// Banner 1&quot; was provided.

How do you decide which banner to use when there are multiple ones inside of a project?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/122660/missing-file-banner-not-using-the-most-common-bann.html
VSTS ticketId: 502137_
_These are the original issue comments:_

Anthony D. Green [MSFT] on 9/29/2017, 04:59 PM (129 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-02-06 03:01
We use the first we find in the same project (prioritizing files that are already before before looking at closed files).  The theory being that it's highly unlikely for multiple files in the same project to need or want different banners.

**Comment by CyrusNajmabadi** [comment] 2020-03-06 07:55
Closing out as the existing algorithm is fine for the vast majority of caes.  For projects that want to specify a banner explicitly, the can now do so with @sharwell 's work here: https://github.com/dotnet/roslyn/pull/41982

**Closed by CyrusNajmabadi** 2020-03-06 07:55 UTC
Labels: Area-IDE, Bug, Developer Community

**Comment by sharwell** [comment] 2020-03-06 15:26
Duplicate of #33012
