### ISSUE TITLE
Discrepancy between code metadata and behavior for Microsoft.CodeAnalysis.Operations.BinaryOperator

### ISSUE THREAD

**Issue by John-L-Cao** [dotnet/roslyn#59359] opened 2022-02-08 01:13 UTC
**Version Used**: 
Microsoft.CodeAnalysis assembly, Version 2.6.0.0

**Steps to Reproduce**:

1. Create a new (or use an existing) Analyzer that register a Operation Action on OperationKind.BinaryOperator
2. Create some test code to be analyzed that has usages of `&&` and `||`. 
3. Set a break point on the Operation Action created in 1, analyze the test code with a debug build. 

**Expected Behavior**:
According to assembly metadata: 
![image](https://user-images.githubusercontent.com/99226249/152899056-9a698119-ee9a-4917-93d9-4ede167affd7.png)

The IBinaryOperation.OperatorKind of the operation corresponding to `&&` should be `BinaryOperatorKind.ConditionalAnd`; 
The IBinaryOperation.OperatorKind of the operation corresponding to `||` should be `BinaryOperatorKind.ConditionalOr`.

**Actual Behavior**:
The IBinaryOperation.OperatorKind of the operation corresponding to `&&` is `BinaryOperatorKind.And`; 
The IBinaryOperation.OperatorKind of the operation corresponding to `||` is `BinaryOperatorKind.Or`.

**Comment by Sodiaq** [comment] 2022-02-08 04:57
iOS update

**Comment by 333fred** [comment] 2022-02-14 19:20
The next steps are for me to investigate, but I've been on vacation for the past week so it might take me another few days before I'm caught back up and can do more than a cursory look. It might be useful to have a complete code sample that demonstrates the problem.

**Comment by John-L-Cao** [comment] 2022-02-15 18:40
Thanks @333fred!

Here is a code sample, suppose we had a operation action call back like: 
```
// suppose the code analyzed was 'firstBool && secondBool || thirdBool && fourthBool'
private void AnalyzeBinaryOperation(OperationAnalysisContext context)
{
    var binaryOperation = context.Operation as IBinaryOperation;
    if ((binaryOperation.OperatorKind == BinaryOperatorKind.And || binaryOperation.OperatorKind == BinaryOperatorKind.Or))
    {
         /* 
             We would enter this block. even though the metadata (screenshot) suggests that we should check for
             BinaryOperatorKind.ConditionalAnd and BinaryOperatorKind.ConditionalOr respectively. 
         */
    }
}
```

**Comment by 333fred** [comment] 2022-02-15 19:01
@John-L-Cao I'm unable to reproduce this locally. Here's what I'm seeing for this simple test:

```cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

var syntaxTree = CSharpSyntaxTree.ParseText(@"
bool firstBool = true, secondBool = true, thirdBool = true, fourthBool = true;
_ = firstBool && secondBool || thirdBool && fourthBool;");
var comp = CSharpCompilation.Create("Test", new[] { syntaxTree }, new[] { MetadataReference.CreateFromFile(typeof(bool).Assembly.Location) });

var binarySyntax = syntaxTree.GetRoot().DescendantNodes().OfType<BinaryExpressionSyntax>().First();
Console.WriteLine(binarySyntax.ToString());
var model = comp.GetSemanticModel(syntaxTree);

var parentBinary = (IBinaryOperation)model.GetOperation(binarySyntax)!;
Console.WriteLine($"Parent binary op: {parentBinary.OperatorKind}");
Console.WriteLine($"Left binary: {((IBinaryOperation)parentBinary.LeftOperand).OperatorKind}");
Console.WriteLine($"Right binary: {((IBinaryOperation)parentBinary.RightOperand).OperatorKind}");
```
```
 ❯ dotnet run                                  [10:59:54]
firstBool && secondBool || thirdBool && fourthBool
Parent binary op: ConditionalOr
Left binary: ConditionalAnd
Right binary: ConditionalAnd
```

I'll need a more complete example to try and diagnose what you're seeing.

**Comment by 333fred** [comment] 2022-02-15 19:05
> Could you share what version you are using for Microsoft.CodeAnalysis?

The latest: 4.1.0-3.final

**Comment by John-L-Cao** [comment] 2022-02-15 19:07
Right - the issue is for Assembly version 2.6.0.0. Is this still supported / maintained?

**Comment by 333fred** [comment] 2022-02-15 19:15
> Right - the issue is for Assembly version 2.6.0.0. Is this still supported / maintained?

No, this corresponds to VS 2017.6, which is not a supported version of VS 2017. The only supported versions are 2017.0 (Roslyn 2.0.0.0, where IOperation was _definitely_ not supported), and 2017.9 (Roslyn 2.9.0.0). In either case, a brief discussion with @jaredpar indicated that this would likely not meet the servicing bar for VS 2017.

**Comment by 333fred** [comment] 2022-02-15 19:23
I'm going to close this issue out, as it is only reproducing in an unsupported version of the compiler. For future readers, the VS 2017 support policy is clarified here: https://docs.microsoft.com/en-us/lifecycle/products/visual-studio-2017. 15.9 is currently the only supported version, which will go out of servicing on Apr 13, 2027, and corresponds to Roslyn 2.9.0.0.

**Closed by 333fred** 2022-02-15 19:23 UTC
Labels: Area-Analyzers, Concept-Continuous Improvement, Feature - IOperation
