### ISSUE TITLE
IDE0019 "Use pattern matching" can produce code that is not equivalent to initial code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65391] opened 2022-11-11 21:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0019-Use-pattern-matching-can-produ/10195876)._

---
The original code is something like this:

            Container parentContainer = originalObj.ParentObj as Container; 

            (more code... )

            if (parentContainer != null)
            {
               (do something with parentContainer)
             }

VS wants use pattern matching to change it to:

            (more code... )

            if (originalObj.ParentObj is Container parentContainer)
            {
               (do something with parentContainer)
             }

But these two blocks of code aren't equivalent if (more code...) changes the value of originalObj.ParentObj.  In my particular case, I'm changing ParentObj in a method of originalObj.

This could cause issues that are subtle and difficult to debug

---
#### Feedback Bot on 11/9/2022, 06:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-22 18:42
Closing as by design. Preserving exact semantics is a non-goal (as it's generally not possible and would make it so we could not offer most fixes in most places).

**Closed by CyrusNajmabadi** 2024-11-22 18:42 UTC
Labels: help wanted, Area-IDE
