### ISSUE TITLE
RegexGenerator does not work in Razor files

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#59780] opened 2022-02-25 21:54 UTC
**Version Used**: 17.2-Preview1

**Steps to Reproduce**:

1. Create a Blazor project
2. Open Index.Razor
3. Replace its content with
```C#
@using System.Text.RegularExpressions

@code {
    [RegexGenerator("[0-9]")] private static partial Regex someRegex();
}
```
4. Build the project

**Expected Behavior**:
No compile error

**Actual Behavior**:
Compile error:
![image](https://user-images.githubusercontent.com/2008729/155807955-b53e1cee-dd84-4b2a-aea1-c4036718235d.png)

**Additional Notes**:
I'm assuming this is due to SourceGenerators not being able to reliable consume outputs from other SourceGenerators

**Comment by jinujoseph** [comment] 2022-02-25 22:05
cc @timheuer for info

**Comment by timheuer** [comment] 2022-02-27 01:02
From a user experience standpoint, the developer doesn't know this, they are following tutorials and blog posts and writing C#...which they can do in `code` blocks. Ideally the C# developer shouldn't know this, but if this is going to be an unsupported language+tools feature, is there some type of analyzer we could have to indicate this won't be supported?

**Comment by jmarolf** [comment] 2022-02-28 17:34
related to: https://github.com/dotnet/roslyn/issues/57239

**Comment by CyrusNajmabadi** [comment] 2022-02-28 20:16
> it's again one of those "i made my decl so much larger for what is information that i effectively want to be extremely minor". 

Sure, but i'm not sure how this is different from any situation with generators.  Any time someone is using generator A, and then they add generator B, they have to understand (and/or accept) that generator A and B cannot play together.  

> but if this is going to be an unsupported language+tools feature, is there some type of analyzer we could have to indicate this won't be supported?

That does seem reasonable.  Perhaps we should advise generators to also ship with a corresponding analyzer that then checks any SG docs created in the final compilation.  If they detect their trigger case in that generated doc, they can warn.

**Comment by jcouv** [comment] 2022-03-01 05:54
Closing this issue as duplicate of https://github.com/dotnet/roslyn/issues/57239. Added a note there to mention the motivating scenario.

**Closed by jcouv** 2022-03-01 05:54 UTC
Labels: Area-Compilers, Feature Request, untriaged
