### ISSUE TITLE
C# compiler should not crash on discards in expressions

### ISSUE THREAD

**Issue by TKilFree** [dotnet/roslyn#19617] opened 2017-05-18 08:13 UTC
**Version Used**:  C# 7.0

**Steps to Reproduce**:

1. Try to compile the following:
```
        public static void DoSomething(Expression<Func<bool>> param)
        {

        }

        public static void CallDoSomething()
        {
            DoSomething(() => Guid.TryParse("", out _));
        }
```

**Expected Behavior**:
The above code should presumably be roughly equivalent to:

```
        public static void DoSomething(Expression<Func<bool>> param)
        {

        }

        public static void CallDoSomething()
        {
            Guid guid;
            DoSomething(() => Guid.TryParse("", out guid));
        }
```
which compiles fine.

**Actual Behavior**:

The compiler crashes with the following message:
"Microsoft.CSharp.Core.targets(71, 5): [MSB6006] "csc.exe" exited with code -2146232797."

**Comment by Rcomian** [comment] 2017-05-18 08:48
Can confirm this crashes for me too:

> VisualStudio/15.0.0-RTW+26228.4
> Microsoft .NET Framework Version 4.6.01586

**Comment by jcouv** [comment] 2017-05-20 00:05
Yes. I think the expected behavior at this point would be `error CS8144: An expression tree may not contain a discard.`
@VSadov @gafter to confirm.

**Comment by jcouv** [comment] 2017-05-27 22:43
I tried this on latest preview bits for dev15.3 and did not encounter the problem.

```
Microsoft Visual Studio Enterprise 2017 Int Preview (dogfood)
Version 15.3 (26510.0-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.3.0-Preview+26510.0.d15rel
```

@TKilFree I'll close this issue since I cannot repro it. I'd encourage you to install Visual Studio 2017 version 15.3 ([preview 1 is now available](https://www.visualstudio.com/vs/preview/)) and re-open if the issue persists for you.
Thanks for reporting this.

**Closed by jcouv** 2017-05-27 22:43 UTC
Labels: Area-Compilers
