### ISSUE TITLE
Provide a way for built-in analyzers to run on closed files.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9712] opened 2016-03-12 03:23 UTC
**New General Issue**

We recently set all built-in IDE analyzers to not run on closed files. Let's use this issue to track adding the ability to re-enable running on closed files for built-in analyzers.

**Old Specific Issue**

**Steps to Reproduce**:
1. Write a naming style rule, and set the enforcement to warning
2. Write something that violates the rule
3. Close the file

**Expected Behavior**:
Error list shows the violation

**Actual Behavior**:
Error list is cleared shortly after closing the file.

**Comment by dpoeschl** [comment] 2016-09-07 21:02
We recently set all built-in IDE analyzers to not run on closed files. Let's use this issue to track adding the ability to re-enable running on closed files for built-in analyzers.

**Comment by dpoeschl** [comment] 2016-09-07 21:04
@mavasani @heejaechang @pilchie, FYI about the new title & shared area path (until we have a design and know what we're doing for this)

**Comment by dpoeschl** [comment] 2017-01-19 17:53
Dupe of https://github.com/dotnet/roslyn/issues/13838

**Closed by dpoeschl** 2017-01-19 17:53 UTC
Labels: Area-Analyzers, Area-IDE, Bug
