### ISSUE TITLE
Allow distributed `.editorconfig`

### ISSUE THREAD

**Issue by AdamWillden** [dotnet/roslyn#29592] opened 2018-08-30 09:36 UTC
Please excuse if this is not the correct repo to suggest this. I could not see an appropriate issue open.

# Problem

I'm looking to be able to have a single common `.editorconfig` to use across all projects within my company. Unless there is a method of which I am unaware, we are currently forced to duplicate an `.editorconfig` file across all our solutions/repositories. If we want to make an update, we need to manually copy and paste changes into each solution/repository.

# StyleCop Example 

The `StyleCop.Analyzers` project [supports using a nuget package with a props file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#sharing-configuration-among-solutions) to 'virtually' include the file relevant ruleset and settings files within a solution. These virtual files are picked up and respected by StyleCop.

The one thing that `StyleCop.Analyzers` does not support is inheritance...

# Proposed Solution

It would be great if we could follow the same example with `.editorconfig` files. The issue lies in how the solution structure and physical folder structures combine to be interpreted for the purposes of inheritance. 

The easiest solution here is to only allow virtual files to be found at a project root. Then if a physical file also exists at the project root, the virtual file would take the role of the parent such that a project may override the distributed (virtual) version using a physical file.

Hopefully this makes sense. Thanks.

**Comment by jinujoseph** [comment] 2018-09-06 16:51
duplicate of #19028

**Closed by jinujoseph** 2018-09-06 16:51 UTC
Labels: Feature Request
