### ISSUE TITLE
Error in "await foreach" in C# 8.0 beta

### ISSUE THREAD

**Issue by kenteltest** [dotnet/roslyn#35637] opened 2019-05-10 17:44 UTC
**Version Used**: Visual Studio 2019 version 16.0.3, C# 8 (beta) and 3.0.100-preview4-011223

**Steps to Reproduce**:
When i try to compile this code
```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        try
        {
            try
            {
                await foreach (var item in NumGenerateAsync())
                {
                    switch (item)
                    {
                        case 5:
                            return;
                    }
                }
                
            }
            catch
            {
            }
        }
        finally
        {
            await Task.Delay(42);
        }
    }

    static async IAsyncEnumerable<int> NumGenerateAsync()
    {
        for (int i = 0; i < 30; i++)
        {
            await Task.Delay(42);
            yield return i;
        }
    }
}
```
VS 2019 reports an error: "MSB6006 "csc.exe" exited with code -2146232797".

**Expected Behavior:**
But I think, this code is logically correct and I expect the code to be compiled

**Actual Behavior:**
"MSB6006 "csc.exe" exited with code -2146232797"

**Remarks:**
If I delete inner try-catch, or await statement in finally block - it works as expected.

To avoid this error I replace ``return`` with ``goto`` now:
```csharp
public static async Task Main(string[] args)
{
    try
    {
        try
        {
            await foreach (var item in NumGenerateAsync())
            {
                switch (item)
                {
                    case 5:
                        goto exit;
                }
            }
        exit:;
        }
        catch
        {
        }
    }
    finally
    {
        await Task.Delay(42);
    }
}
```

**Comment by jcouv** [comment] 2019-05-10 20:28
I tried reproing on [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBWAbgFgAoPQogFkquuwGZCAmOgdmoG9q+IYXbEAbIQAchCQFkIASwB2ACmK4A2gF18EBAHMoASkHCBVYZfwwEAT1NX85x45v2LLy888vsATnwAMwB7BDgIAGMAC3wVADc9fAV4MCSlfAA5AFcwAHE4JUQIeABBKFslCJUjEw8fK296zygAd2To2OS4MFqmn0a+nwjoOHwSEAdBvuxuJinHAF9JvqW6weWXVb7hmGiNxwHPLc39oOUIABsL909D3wDsMQA6ABE4C4hbFXoOIzmTtarSbiKT4ACSZQqEQAokockVgBc4AAeZQwAB8mRy+UKCGKcEhlWqkzuQhCCE6ShgSXwAF58LgyDTkfhWIykuh0L0XKSrP4ZK93p9vr9/vViERCNwkmKrMchKsgcxlUoIGA4FAAA6RUbEej8YHsNGIQI68GEmFw9V4xEo4JZakAFXRJNOEPKlVh8LxMFCyOd+HyMAtXutxVCaiIT0dUTCEBQyn0TwAwhBKu8PjAFMElI7ggBrArWAtF+koOCmrIXGB/SZKyxsNLwBCmiKjd1Q0NFX0IZH2p2YkB0J4dyovBRa4JQCC211rBukJ4ANUuWTgj2RwGCwQumNkwTicAycAAHsGPVVa/PhI78MmsggwlSnPh9HAYEz5fhFdRVeqtWaxAGmsjbGi2ZqjhE46TtOs5rLyxAkMuq7rhI0GalOBIXtUso/iqaoatqbbDgASlkVIKOqKbBGAmoKEiCAAMqIHEChtlAwGWBoJQwDYCjAA6cAAKrTm+Kg8XxAnwI6ehvjAUBPLI75RMEKBIOCShRIgXQoHSQSXFAcDqSUVzBC0shVlmmpInppoXIZRhaIa+CGZccC6dgXAWmCzbhkxMD4vI0TKASvEIPxgn4EOjEBfAQVRCFEnhVJcBzp4jbeb5PYxYFkQJYUSURfAKiOrYmqjLAuXBYUpXlUYUX4MAIwqJVcV5SFtVwNyBynF+eHUAAxHCVwzjZCawUi1C/gRAHEYhTyMfaCDsZxwi0MQrwKBA+hKFOWYRFAsrrVGZEUVR0Inm2mpZjmzEIKx7FHQQG2nVmVFglSiDBJqd0PRqTCTBoMUIFkEQwAAMp8/YqJDtj9gA0soKBPCUDrBI5zmwCDYP4PIcKXCRGrviuFxro8i0Pm2yahCijqE1AlkuvBpyauFCTwHQHB9sAABWcBg5iAD6EQ5lm+M3UosqWKzCjs6MwS8/z1LC6LyhZMU2ZKDl8BS8IMty/gF38w6mvU59Z74ILp7GxLZvwGeutCPr+L4ArfM48LEDXQ+7l26eH4s2zLtbjulsi7RSLwCgjv4M7HN0xqlmW2EDPVjHcejBdV0S+hxTRB9ISW4gCChOnQcc1AKkIMrh4IFAmsA9eQgAPSt/gyIM2AkB2OiQZQK7FKGfJ+AtFpMBaRSvpBKExEixR4ua/3U8g+k2CSLGOb2lA1xPMized93thM54rfN+3YTd/mUDonbasazm/eQLY+Ar1IG+7Vk2/PwogTWAl/cTn0vZIyjUHR/zgLYAA5FcfAhRa4v3Ii5KE78t7XCSL/cegDAE2DXLvZuF89BX2Pr4dgIcLj4FOrfBeD8LQoM/mgvgr53xMiHp+KaTd8Cn3bgfPQR96bviXsEWOYRtRhGnpPLSsD/au3Kj6TWeCeE91OI2bA9AKFExgMSDhvJLBt34TAZuWRNQoBdq1UY5JwFSItp/OAzd+TBAwf/NIlV0xPFOJYQWtd645k5DHDx4drLvncrZAycA/HCEFinJOZYKwQEsuEoQVtHyhD0sNC4CSi4nhtqbUW0j6RpIyZ7b2YQUB+wtvkqs6T3ERLnmLdWEtUmVMKbUu+EttajAqVcGO9YSGEDUcxGA9NLIlSGdWF+idqzdQaNUxJUSxn0jmQHDhlhGIKB2pcamEd3yaxwr1dh6VRD9PfFnOA10dknLOTmfAxdQhTK8DMouySKT0guTnCc2pdhRALsEFMXsYA+xUDchAV4+irPWRcTZgSJa7I4T0xwjZK6hGpEuRA3j0i0iFl4hu+zekkzJmICmy04Da0/oGd8JKoAtSrtSX0hYlB3LMA8kmCgTHSRLKoWlBQQVNBmA8ywABCFWWyo74AAPz4DxahQlbYKVPAAAoFATEofQUU+URKBXSTp5DxWSvJktGVsVP4LVBm2dywSJjLJcEkkuCAFr6rgK8zWSR+4AHlZH3yUKmdMSIUCOquTqlCerKbEsNQpL1bYfWqstY4XVBL7WyoAGJxOrO5bpOL4XsATqnakQZRmaMRdXYsdKGVCB0cIZlrK4B5jpSoTl9KMk/1iIKgJkd3IlumdGqweN1YXH0bG6VcBqZhEYlEPQ7lowbxaB9BIFwWVuu7JrP1qhuX1DhT4a1oRRUTpLi0GF0xpSRImUso46a+SHPwC6z1NEoXuUjFzN2StMQtOoUodSD6cZmPUgWml7L1L9vtZeyFraUAJo+IYIIYHjCnDLUIRtKhn31KdbSLV7b7mdssOPHdUiWj4BKAYeEVJshXCXSoP8cAHHwdVi+moGSvyeArfiatBRa3sqvA8uDKhAiQfwAAMglYGuNwbAPXuA6B7aClQNmSNhEE2OYyk1nwPy+kuBUOMvQ+qrJMnba5PKYbTTsmr3mxgL84pcA91NDXZ4DjXHxO8f46TKVAGr3CvcmJwwTwRLEuiO5KsiZ5P1SUwyVTpa1VCEYsgkuSgFAAC8PXyZchEPS4XKjvxi3FnTxn7yPgKMe+YcGoCJcC2k3jfGCtPCDJ1aoin6QwDKuRwIKhkvREi2l7TRmaihacJ1/xfyfalIy3pArGTLB0aaO8QynWYM+HJt5lAVZEDWH7vSGbWk5sMRTA+J8uX5jCDg8PQLK2fPrbeJWSZ3W1M7c8EU/5JT4s1cOudhUnXRuLFPSfM+AB1UYhRglTyHpYhDHqXKxVGMACsNMR4VRaF7NIljyxIn0PiL9Qjx7FAeW3Rt49EBwEgf3CAL8zRg5gC0OARZMF46ULpAZebm5Lt0JT/A1Oj208uqciW6Oz6GQ1JYlW89ENXOgLAnMABaNJ6lkjQPIWD3QtpixpDiCWJI1I2jj0sWYjnwOaa6QnnAJ4QgAASZk4C13UuT3Q9khHqjTEvUd1JMdOMATY3SygRbZbBmgwFTwkwa/8L9tos8cwyey1Sa4Rh1K87qR69p+AwBrKiNSOS1zkmFFQc/A8iAWjhV4gUNxna255hj8oSiMXRhY/wNENM7FXaOOKOpEn5etIRHzMI0ntEsyHjQaPZSC2I+tM1hrwBlw4woGfv9v7NFlKJldljiRaYAcie2Vcwy893i54ee+6kO5+t86B/SXvL6G2/xUFvqh/P0UoYeVN/xVGz/R/pGY4bwgT8393xpZsFxghN/HZCsdWdR3KrMzCF/n3zP3UkBwlnUjSRXR8EsxcDg2fx3waSK0qWCy63UxbjPnnTkQFwuGH2fhbSCTUhciEXrx+10ingAEc1w1w1cjFrIFBglhgrgmom9c8ds4N+VCZAhsd0xoQqCDJj8Lht9I8IDcY0we0+0BMB0h1iVR0SkngoBBZl8xZ3gOt0C0DLthBu0CYNF/1g0ZCR0x1kYYwd1p1Lg513UJYSNoCVg3smhWh2gYgVBrs+t/NJtHty8RhYFKkLVND4Vngk0wZQhbAFoApq5jxd1wDNYv0Qd1Jw0MwPUmMlAngMgcwQFHhkw4wJY3UJYFI3glBbBkwEohCJI8p1JDs1tEBBRTsaxH96hgA4x8xG4/DPDDJGcIscxWsckjMEtfCWjhAys5U9oWo6RiF+iNDxirAEhJ4jEbJ6QSpZiURiB71FYBY31ViMQjAHt1C+h/lAkRwUgiBa1FiDjuhRQPCRt1JHQTjMjwhiooicwYj8QaMLjhAGjwgmi7Cphhg2iKj5tJ4oA+jxjHgnhAiewQicpwi4BIiX9RDP07xK8EiJYkiUi0jyixBbiPUcjF5BQCiij6IUBSjohTdjA6ifB3iIBPj1CXs5Q9llRPAM4+l7MWVGN2UqUkUi0uVoN2Mj861qtLYsUcxUCr8tDxCdCh49CiUDC5Dx0TCzIzDZ0UAsCPVrDaM6TA5ZYXZVFGc1lVQIUF9oV20ps4MhUb0UBhTOttDe1dCpD7VpSjDt15SlAZ0LCF0cxVSHkaTr8XNdIasQYwkvirATSHj0hkCYFMBMA39EAP8v9kYf8wg/80wxIgCw5YToixD8ZrSJTbT9CaZDD5DFDlCQoLhICUD+SoDL9OsTTrYtNuj7ZqQwyLhUC0MWjpMDN5MnhToVBXjEkaz2yMskAeyXJRjYgVArTJCHMg0pSaZ/Q810QtijARxnSSxT8PVqhBydiXBycbCLNOtxtUp1CRTHBp0Vy0ycxzMpgvThAaTYCnZy5dQ1ETzCxVzDTuTO0HDPlYgXDbsMsLT1CfjvsfCPC4NKEzylAoBaFItU9myeQhyQSwTgjQi9AYAIjnCQzw8Qz2k4jESRpkT2VUTCh0TMTsjLlwLcTCjijCTeIyiZBGJZt/jqjk1aiPCrz6h9yPCjz10Qy0KwL2kdzLyPCKSqTOsAL2iUsWtYs2t6zeiPDBjhilsxjLtOLPBpjgcXZ5jrjAlkRljuZ3YMR1i9L5ztjJi1L4BTiwAjizFzLzjNyFQribisizMQCPUMLeKQcXjbLGpGjmj5hRK/iGJFsgTLt4LIhwSkKoTd1nLRCorNYsKETvVMxNYUTUjCKZBiLNZsSH5yL8SSjqLiTFt+LBghK1TYU6xT0wI9S6AJBPIMyJCbTJzBNpzh0ZTdI25DJRF8RdJ+xq8mFcQ2I5cIBtTyJCh2Jpw7B8A5t6Cdh+9mYOEKrLgqqmS5Sp1nTzClTLDF1WdSKqsMU/4sNCgcMFTXTsClAPT6S4DPoEBKqQRh8cw0EdKN9MRCyctiy9IgNF8tYXrCgqkOFGSQRtT3q2kvr3hj8NjLZ6o24yNdJ1Rx5VIBqWUJq4ABJ9B9BEw3y+g3hkbQTFALgVAAAiGMCqYG8heHOARHCuFSKsXSOBBbaXZQBXQsZGPGwqywZao69at006raw0tNQEagJUMjWaXUE6ciN6XXSFeiRAX6NiDUVaIQY6Ts0WyiXXD6Zsb6aWx6U9LhDuHIQ+dEQmVmImKkPHUBAkhbCxNeOhABLKUIBSPeRRI+QGYGUGCGKGB0GGN2mARGSnFGNGDGECdgLGF23DC8HybsUIJSWGlAAAISyDNoQDShcDbkynDoQEjpUhjrjqEIW0d0Ml0mAGfjLw+GVXVjfHL2vUlopEF1EU31/jfFxA1mVVODbjXiV1ToUnwATRSV2haFN0kUokCXVCpCBx5k/mVzxE1H7gtEeHTtUljvjvUmgGbrPjAD2h6qLuCFRsS0AUrgdINyNxN1hzL0CAdB9j/kARFipsalGArwAN0jTBQGXpkTehL2RiEC7opFPDVECTr1GBQCETIIGtMh2FGDnw31iEDy6jly4zMlMtGFnULCfrbKkv9jrwSg6GnrEFnszvjvwH/xQCRCgHUikiVzwYfsIdIYLqfsuBjMbpVXx0eGF3LDZmCQ3z13wC+3Lqvu+hfui1LycRPurgnkamfgvgPDRo4TbjL0eCCBLlSDLwSiKGWiiFsGIbAWUAmuCCnygBIJx3vot3wA/zaPx2mIYNqx6p4eL0ksXifrCEzF+yEWSGR0h0gWptJ3IKEREVnRAfN3IQcT/kwmfqsY9X7k9yTE13CibskbPlR2pC3BPFdjBoTDCHd2/ipCEQYbEFx3LsQKdUCAYKEMXMDMZMwewfnuzopEFhhozvKeYaZDbjAAdFGgqhwTBiZH/qF2pEgELFIduqUGuEDJUSIAkBTp9AjuUjnqzuYbvEcp2sUs8AOpDqhDDrGbTomZwYqaq0YSqfWdqYW3pFKd2amaqOIrM3qgWB8scA0GwbBAjjHPWdueskyrIpKBRpTnrkPA+lnSi2VX9oOSZP3EPGPDPH9HaXihCnRBUBTMdDBfakKDgfBcKHqi7zERhZB0RdGCHEglheqg6XmatWqcmfjvCs0RTLMQxbYw4RUTURKGh2SGEx9P9FpcUGbCuJxfyjgEheheZa6ApF92QHGV/jRaqg5YRbha6geRRdGEdB5ebAajBFSKzECEKINJmr6ClfwGFbalxflYtHZZClGIeR2ajr2dtVlYZbNKhYrEID8EQHUjJfRfFcpf+e1NlaEnAogG4IteAyZbpdZc1f1cKC5etZlb9YW35ftZDcDZaZFZClQI1dDZZYWyxcyOSDYkuEVZ/hVeFTVaaATejd1YvALYxSNcJY2eYZRj9fdenC9ec0tZTIjcFbFdxedaTrbh1q7l4XRHkAQCvjbpOt0H7jBynwIKjjQe70HhNQ1CgBPquDTwpGCBnzaEMgUV1q7eUXPUBrOZHONZqeOdtSZ2zQvO/H5qAA) by copying the code above and adding the types needed by the compiler and the code compiled successfully.

**Comment by svick** [comment] 2019-05-12 20:07
I can reproduce this on VS 16.0.3, the exception I got is:

```
System.InvalidOperationException: Unexpected value 'Beq' of type 'System.Reflection.Metadata.ILOpCode'
   at Microsoft.CodeAnalysis.CodeGen.ILOpCodeExtensions.GetLeaveOpcode(ILOpCode opcode)
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.BasicBlock.RewriteBranchesAcrossExceptionHandlers()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RewriteBranchesAcrossExceptionHandlers()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize()
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl()
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32& asyncCatchHandlerOffset, ImmutableArray`1& asyncYieldPoints, ImmutableArray`1& asyncResumePoints)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
   at Microsoft.CodeAnalysis.CodeGen.ILOpCodeExtensions.GetLeaveOpcode(System.Reflection.Metadata.ILOpCode)
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder+BasicBlock.RewriteBranchesAcrossExceptionHandlers()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RewriteBranchesAcrossExceptionHandlers()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks()
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize()
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl()
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32 ByRef, System.Collections.Immutable.ImmutableArray`1<Int32> ByRef, System.Collections.Immutable.ImmutableArray`1<Int32> ByRef)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain, Boolean, Boolean, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan>)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
   at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I can't reproduce it on master and according to `git bisect`, the issue was fixed by https://github.com/dotnet/roslyn/pull/34791. Based on the description of that PR, it was meant to fix exactly this problem, so I think this issue can be closed as already fixed in master.

**Closed** 2019-05-13 08:18 UTC
Labels: Area-Compilers, New Feature - Async Streams
