### ISSUE TITLE
Compiler 'warning level' affects if we show 'suggestions' or not.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17286] opened 2017-02-21 22:04 UTC
If projects change their warning level (say to 0), here:

![image](https://cloud.githubusercontent.com/assets/4564579/23187125/93aa0f98-f83e-11e6-8c6d-f3281f8d9efa.png)

Then suggestions will no longer show up.  This doesn't make sense to me.

**Comment by Pilchie** [comment] 2017-02-21 22:30
@mavasani or @heejaechang do you know why this is?  Also, is it only if it is `0`?

**Comment by mavasani** [comment] 2017-02-21 22:33
I have no idea - I know the IDE driver uses diagnostic severity in some way to determine what analyzers to execute for closed files, but don't know if anything is using the warning level. Likely a bug...

**Comment by heejaechang** [comment] 2017-02-21 22:57
this is compiler code so tagging @dotnet/roslyn-compiler 

but looking at the source code 
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpDiagnosticFilter.cs,116

giving 0 to that looks like it will filter out any diagnostics that has warning level bigger than 0 (if 0 is given) which means, all diagnostics except error.

**Comment by heejaechang** [comment] 2017-02-21 22:59
question on whether suggestion should be part of compiler diagnostic error mechanism or not will be design question. right now, analyzers are compiler's concept which has no difference than compiler generated diagnostics.

so, if user set to filter out any diagnostics that has warning level bigger than 0, than suggestion will be filtered out.

**Comment by gafter** [comment] 2017-02-21 23:28
Probably the warning level should only affect filtering of warnings.

**Comment by mavasani** [comment] 2017-02-21 23:31
@gafter - I like your suggestion, though I am not sure if this will be a breaking change or not.

**Comment by heejaechang** [comment] 2017-02-21 23:43
@gafter suggestion is currently concept in compiler, so what method are we giving customers if users do want to filter out all suggestions?

**Comment by mavasani** [comment] 2017-02-21 23:48
@heejaechang - end users can still suppress suggestions by using `/nowarn:<SuggestionID>`. I think Neal's suggestion was to update the first part of the if condition in the code you pointed to do the "warning level" based filtering only for diagnostics with severity Warning:

```
           // Compute if the reporting should be suppressed.
            if ((diagnosticWarningLevel > warningLevelOption && report == ReportDiagnostic.Warning)  // honor the warning level
                || report == ReportDiagnostic.Suppress)                // check options (/nowarn)
            {
                return ReportDiagnostic.Suppress;
            }
```

**Comment by jinujoseph** [comment] 2018-06-26 16:19
Duplicate of #20377

**Closed by jinujoseph** 2018-06-26 16:19 UTC
Labels: Area-Analyzers
