### ISSUE TITLE
Go to implementation throws AggregateException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39325] opened 2019-10-16 19:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/745946/go-to-implementation-throws-aggregateexception.html)._

---
<p>[regression] [worked-in:16.2.3]<br>
After upgrading to 16.3 the Go to Implementation command (Ctrl+F12 in the default shortcuts) no longer work and throws an AggregateException.</p><p>Update: this works properly on a dotnet core solution. The project where this fails is a larger (50+ csproj) legacy dotnet framework solution. The main project type is ASP.NET.</p><p>I tried disabling all plugins but the error persists.</p><p>Please see the attached logs/recording for more details.</p><p>This is the stack trace for the error:</p>
<pre>System.AggregateException: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.&lt;CreateIndexAsync&gt;d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;AddSourceTypesInProjectAsync&gt;d__30.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesInProjectAsync&gt;d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesAsync&gt;d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;&gt;c__DisplayClass9_0.&lt;&lt;FindTypesFromCacheOrComputeAsync&gt;b__0&gt;d.MoveNext() --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesFromCacheOrComputeAsync&gt;d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTransitivelyImplementingStructuresAndClassesAsync&gt;d__13.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.&lt;FindImplementationsAsync&gt;d__50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.&lt;FindImplementationsAsync&gt;d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsWorkerAsync&gt;d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsAsync&gt;d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsAsync&gt;d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.&lt;FindImplementationsAsync&gt;d__2.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.Editor.GoToImplementation.GoToImplementationCommandHandler.StreamingGoToImplementation(Document document, Int32 caretPosition, IFindUsagesService findUsagesService, IStreamingFindUsagesPresenter streamingPresenter, CancellationToken cancellationToken, String&amp; messageToShow)at Microsoft.CodeAnalysis.Editor.GoToImplementation.GoToImplementationCommandHandler.ExecuteCommand(Document document, Int32 caretPosition, IFindUsagesService streamingService, CommandExecutionContext context)at Microsoft.CodeAnalysis.Editor.GoToImplementation.GoToImplementationCommandHandler.ExecuteCommand(GoToImplementationCommandArgs args, CommandExecutionContext context)at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;&lt;span class=&quot;hljs-selector-tag&quot;&gt;Execute&lt;/span&gt;&gt;&lt;span class=&quot;hljs-selector-tag&quot;&gt;b__1&lt;/span&gt;()&lt;span class=&quot;hljs-selector-tag&quot;&gt;at&lt;/span&gt; &lt;span class=&quot;hljs-selector-tag&quot;&gt;Microsoft&lt;/span&gt;&lt;span class=&quot;hljs-selector-class&quot;&gt;.VisualStudio&lt;/span&gt;&lt;span class=&quot;hljs-selector-class&quot;&gt;.Text&lt;/span&gt;&lt;span class=&quot;hljs-selector-class&quot;&gt;.Utilities&lt;/span&gt;&lt;span class=&quot;hljs-selector-class&quot;&gt;.GuardedOperations&lt;/span&gt;&lt;span class=&quot;hljs-selector-class&quot;&gt;.CallExtensionPoint&lt;/span&gt;(&lt;span class=&quot;hljs-selector-tag&quot;&gt;Object&lt;/span&gt; &lt;span class=&quot;hljs-selector-tag&quot;&gt;errorSource&lt;/span&gt;, &lt;span class=&quot;hljs-selector-tag&quot;&gt;Action&lt;/span&gt; &lt;span class=&quot;hljs-selector-tag&quot;&gt;call&lt;/span&gt;, &lt;span class=&quot;hljs-selector-tag&quot;&gt;Predicate&lt;/span&gt;`1 exceptionFilter) ---&gt; (Inner Exception #0) System.AggregateException: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.&lt;CreateIndexAsync&gt;d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;AddSourceTypesInProjectAsync&gt;d__30.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesInProjectAsync&gt;d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesAsync&gt;d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;&gt;c__DisplayClass9_0.&lt;&lt;FindTypesFromCacheOrComputeAsync&gt;b__0&gt;d.MoveNext() --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesFromCacheOrComputeAsync&gt;d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTransitivelyImplementingStructuresAndClassesAsync&gt;d__13.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.&lt;FindImplementationsAsync&gt;d__50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.&lt;FindImplementationsAsync&gt;d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsWorkerAsync&gt;d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsAsync&gt;d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.FindUsagesHelpers.&lt;FindImplementationsAsync&gt;d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.&lt;FindImplementationsAsync&gt;d__2.MoveNext() ---&gt; (Inner Exception #0) System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.&lt;CreateIndexAsync&gt;d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;AddSourceTypesInProjectAsync&gt;d__30.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesInProjectAsync&gt;d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;FindTypesAsync&gt;d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.&lt;&gt;c__DisplayClass9_0.&lt;&lt;FindTypesFromCacheOrComputeAsync&gt;b__0&gt;d.MoveNext() ---&gt; (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.&lt;CreateIndexAsync&gt;d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;--- &lt;--- &lt;--- 
</pre>

---
#### Visual Studio Feedback System on 9/24/2019, 11:19 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by VitorRigoni** [comment] 2019-10-16 23:08
Got your notification and subscribed to this issue. Thanks for the heads up! =)

**Comment by sharwell** [comment] 2019-10-21 22:15
Duplicate of #32083

**Closed by sharwell** 2019-10-21 22:15 UTC
Labels: Area-IDE, Bug
