### ISSUE TITLE
`TypeLoadException` for co-/contravariant interfaces with default methods having a closure

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#40299] opened 2019-12-11 16:31 UTC
**Version Used**: 

`%ProgramFiles%\dotnet\sdk\3.1.100\Roslyn\bincore\Microsoft.CodeAnalysis.CSharp.dll`
File SHA1: `46f61df92a8fb01930a0f8b529b0abb365ffd64b`
File Version: `3.400.19.56205`
Product Version: [`3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d`](https://github.com/dotnet/roslyn/commit/ff930dec4565e2bc424ad3bf3e22ecb20542c87d)

`%ProgramFiles%\dotnet\dotnet.exe`
File SHA1: `755f1b51255447383e514cb0a2d0e2f43b4b27c9`
File Version: `3.100.19.56502`
Product Version: `3,100,19,56502 @Commit: 65f04fb6db7a5e198d05dbebd5c4ad21eb018f89`

**Steps to Reproduce**:

Compile and run:
```csharp
using System;

interface IA<in T>
{
    public Action Bind(Action<object> a, T x)
    {
        return () => a(x);
    }
}

class C : IA<object>
{
    static void Main()
    {
        IA<string> x = new C();
        Action a = x.Bind(Console.WriteLine, "hi");
        a();
    }
}
```

**Expected Behavior**:

The program compiles successfully and prints `hi`.

**Actual Behavior**:

No compile-time errors, but the program throws an exception:
```
Unhandled exception. System.TypeLoadException: Could not load type '<>c__DisplayClass0_0'
    from assembly 'ConsoleApp2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because
    it declares a covariant or contravariant type parameter and is not an interface or delegate.
   at IA`1.Bind(Action`1 a, T x)
   at C.Main()
```

**Comment by VladimirReshetnikov** [comment] 2019-12-11 22:05
The same issue happens with static members too:

```csharp
using System;

interface IX<out T>
{
    public static Action A = delegate {  };
}

static class Program
{
    static void Main()
    {
        IX<string>.A();
    }
}
```

Exception:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'IX`1' 
    threw an exception.
 ---> System.TypeLoadException: Could not load type '<>c' from assembly 
    'ConsoleApp2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
    because it declares a covariant or contravariant type parameter and is not an interface or delegate.
   at IX`1..cctor()
   --- End of inner exception stack trace ---
   at Program.Main()
```

**Comment by jcouv** [comment] 2019-12-12 00:33
FYI @AlekseyTs

**Comment by AlekseyTs** [comment] 2019-12-12 00:48
@VladimirReshetnikov Is this a duplicate of https://github.com/dotnet/roslyn/issues/39731?

**Comment by VladimirReshetnikov** [comment] 2019-12-12 04:33
Yes, it looks the same.

**Comment by AlekseyTs** [comment] 2019-12-13 00:35
Both scenarios are working as expected in recent VS builds

**Closed by AlekseyTs** 2019-12-13 00:35 UTC
Labels: Area-Compilers, New Language Feature - Default Interface Impl
