### ISSUE TITLE
Nullables with Switch case showing strange behavior

### ISSUE THREAD

**Issue by vendettamit** [dotnet/roslyn#5025] opened 2015-09-04 22:35 UTC
In Visual studio 2015 using a Nullable type in switch case having only two cases; case "null" and default ; debugger always jumps to null. As an expected behavior it must go to default. Tried using Console.Write() and running without debugging shown the same behavior. 

Steps to reproduce - 

           int? a = 1;
            switch (a)
            {
                case null:
                    break; //even though value is 1, code runs here
                default:
                    break;
            }

More details: http://stackoverflow.com/questions/32407191/switch-on-nullable-boolean-case-goes-to-null-when-value-is-true

**Comment by jaredpar** [comment] 2015-09-04 22:57
Thanks for taking the time to report this bug.  This appears to be a duplicate of #4344.  The title of the bug is a bit misleading (refers only to `string?`).  While reviewing the fix we found the same problem existed for `int?` and fixed it up as well.

**Closed by jaredpar** 2015-09-04 22:57 UTC

**Comment by vendettamit** [comment] 2015-09-05 01:32
Though this is duplicate but wanted to bring your attention guys I tried it with other value types as well. e.g. Boolean. It seems like the Nullable handling in IL for switch case have some glitches.
