### ISSUE TITLE
Fix Code Style should have an option for fix all occurences like analzysers do

### ISSUE THREAD

**Issue by lmeyer3** [dotnet/roslyn#15723] opened 2016-12-07 11:21 UTC
**Version Used**: 

Visual Studio  2017 RC

**Steps to Reproduce**:

1.  Create any project
2.  add this method:
```
        public async Task Test()
        {
            await Task.Delay(100);
        }
```
3. Open Quick Actions 
![capture](https://cloud.githubusercontent.com/assets/24432440/20965753/7f75a59e-bc77-11e6-9380-076c15e11abc.PNG)

**Expected Behavior**:

Have an option for fix all code styles in Project, Document or Solution like analzysers have.

**Actual Behavior**:

Fixes only the current selection

**Comment by Pilchie** [comment] 2016-12-12 21:26
Duplicate of https://github.com/dotnet/roslyn/issues/14983

**Closed by Pilchie** 2016-12-12 21:26 UTC
Labels: Area-IDE
