### ISSUE TITLE
[Test Failure] <description> in windows_eta_open_prtest on PR #12056

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#12069] opened 2016-06-17 03:19 UTC
PR: [#12056](https://github.com/dotnet/roslyn/pull/12056) *Improve parsing recovery for local functions* by @agocke
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/614/

**Comment by Pilchie** [comment] 2016-06-17 18:00
Dupe of #12065

**Closed by Pilchie** 2016-06-17 18:00 UTC
Labels: Bug
