### ISSUE TITLE
can remove the semicolon at the end of statement?

### ISSUE THREAD

**Issue by birenchens** [dotnet/roslyn#34671] opened 2019-04-02 09:28 UTC
can remove the semicolon at the end of statement?
its too troublesome.

**Comment by svick** [comment] 2019-04-02 11:40
If I understand what you're saying correctly, see the discussion at https://github.com/dotnet/csharplang/issues/496.

The short answer is that this is not going to happen, because such a huge syntactical change can't be done well to an existing language.

**Comment by birenchens** [comment] 2019-04-02 11:47
Thanks, I got it.




| |
陈
邮箱：birenchens@163.com
|

签名由 网易邮箱大师 定制

On 04/02/2019 19:41, Petr Onderka wrote:

If I understand what you're saying correctly, see the discussion at dotnet/csharplang#496.

The short answer is that this is not going to happen, because such a huge syntactical change can't be done well to an existing language.

**Comment by sharwell** [comment] 2019-04-02 12:39
Duplicate of dotnet/csharplang#496

**Closed by sharwell** 2019-04-02 12:39 UTC
