### ISSUE TITLE
Cannot navigate to the symbol under the caret

### ISSUE THREAD

**Issue by GerryGe** [dotnet/roslyn#20779] opened 2017-07-11 05:48 UTC
**Version Used**: VS 2017 Professional Version 15.2 (26430.14) Release

**Steps to Reproduce**:

1. Go to Definition of Class "AbpWebApplication" 

![image](https://user-images.githubusercontent.com/6952917/28052521-3af49404-663e-11e7-9039-6cab8c581b27.png)

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/6952917/28052798-9b799134-663f-11e7-951b-8e9a931b3169.png)

**Actual Behavior**:
I can work on VS 2015 Professional Version 14.0.25431.01 Update 3.
![image](https://user-images.githubusercontent.com/6952917/28052768-7fa42550-663f-11e7-902f-50774de60246.png)

**Comment by GerryGe** [comment] 2017-07-11 06:09
![image](https://user-images.githubusercontent.com/6952917/28053293-3d1ea16c-6642-11e7-8b59-0f2c02607b66.png)
![image](https://user-images.githubusercontent.com/6952917/28053300-49c28960-6642-11e7-9d66-14ebea56bbe8.png)

Because of class AbpWebApplication is generic?

**Comment by Pilchie** [comment] 2017-07-11 15:45
Yes.  This is a dupe of https://github.com/dotnet/roslyn/issues/17360, which is fixed in the Visual Studio 2017 Preview version 15.3

**Closed by Pilchie** 2017-07-11 15:45 UTC
Labels: Area-IDE, Bug

**Comment by GerryGe** [comment] 2017-07-12 01:52
@Pilchie Thanks.

**Comment by zeeshan-ahmad111** [comment] 2019-04-10 12:37
I am facing the same problem in VS 2019 Professional.
Tried many things but nothing worked for me.
The Code compiles successfully.

**Comment by arjunkumarkhadka5** [comment] 2019-06-30 07:42
Just delete .vs folder and open the solution again.

**Comment by rdijkstra** [comment] 2019-09-06 17:13
Sorry, I deleted the .vs folder (AND I installed the compiler version 3.2.1) makes no difference!

**Comment by zeeshan-ahmad111** [comment] 2019-09-09 06:36
These are the steps to resolve
1) Right click on "References" in the Solution Explorer
2) Select "Manage NuGet Packages"
3) Under the "Installed" tab search fro "Microsoft.Net.Compilers"
4) Select "Microsoft.Net.Compilers"
5) On the side window of "Microsoft.Net.Compilers" click the update button

**Comment by rdijkstra** [comment] 2019-09-09 08:26
Dear Replier,

thanks!

But... That is exactly what I did, and the installed version 3.2.1. of 
the Windows.net.compilers and pushed the update button (the update 
button is now greyed out, because there is now nothing to update... )

This, however, has no effect on the problem... I still can't use F12 to 
navigate to the function definitions in de javascript of the .aspx files 
(it DOES work with F12 the definitions in C# in the .cs files...)

-- 

met vriendelijke groet,

Rients Dijkstra
VeriDOP Software Services BV
e. rhdijkstra@veridop.nl
m. 06 21 408 730

**Comment by chatteberg** [comment] 2020-01-31 16:48
I have a VB .NET 4.6.1 Windows Forms Application. 
When I open it in VS2017, all works. 
When I open it in VS2019, the following problems occur: 
1. For references to functions in another file (references in same file work): 
    Peek Definition doesn't work (respond)
    GoTo Definition pops error 'Cannot navigate to the symbol under the caret'
2. None of the 10+ Windows form designers can display the form, instead get the error 'The designer could not be shown for this file because none of the classes within it can be designed'. There are no other references or details in the designer error to indicate a problem. 

The solution compiles without any errors. 
When I close VS2019 and open up VS2017, it works with exact same files and solution. 
I have de-installed both versions of VS and installed them again. No change. 
I have removed '.vs' folder, cleaned solution, cleared symbol cache, checked NuGet packages (all current), and removed extra '<Import Project' lines from .vbproj file. . 
In VS2019, I can add a new form and the designer fails to work.
In VS2017, I can add a new form and the designer works.

**Comment by sharwell** [comment] 2020-01-31 17:28
@zeeshan-ahmad111 @rdijkstra @chatteberg Can you file a new issue for what you observed? This is an old/unrelated/fixed bug.
