### ISSUE TITLE
ExtractMethodCodeRefactoringProvider crash on method highlight in expression body

### ISSUE THREAD

**Issue by HekiShavik** [dotnet/roslyn#18600] opened 2017-04-11 07:48 UTC
**Version Used**: VS2017 (15.1 (26403.3)).

**Steps to Reproduce**:

1. Create empty ASP.NET Web Application project (I have only testet with this project type).
2. Create empty class in any namespace.
3. Insert the following code:
```C#
private static string Testing() => "";
public static string TestError { get => Testing(); }
```
Highlight `Testing` in the `TestError` property.

If refactored to `... TestError => Testing() ?? "";` Everything is fine.
The error also happens with a setter.

**Expected Behavior**: No thrown exceptions.

**Actual Behavior**: Thrown exceptions and ExtractMethodCodeRefactoringProvider crashes.

-----
Stack trace from the error:

    System.InvalidOperationException : Unexpected false
      at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
      at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetCallSiteContainerFromExpression()
      at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetOutermostCallSiteContainerToProcess(CancellationToken cancellationToken)
      at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement, TExpression, TNodeUnderContainer] (<Unknown Parameters>)
      at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
      at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator, TExtractor, TResult] (<Unknown Parameters>)
      at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
      at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
      at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Pilchie** [comment] 2017-04-11 15:19
Note - I can repro in 15.1, but not the latest 15.3 bits, but I didn't see a dupe with a quick search.  Can you check for a dupe and a unit test for this case?

**Comment by HekiShavik** [comment] 2017-04-12 13:17
This also happens when highlighting other things. Actually just any text between two spaces after the `=>` and before the semi-colon. This could be the null-coalescing operator or the 0 in `get => Testing2() ?? 0;` - except the parentheses and never if there is a syntax error.

I could not find a dupe and no unit test. I do not feel confident to write one.

**Comment by WillPittenger** [comment] 2017-04-13 00:33
I'm getting this inside a C# DLL source file.  All I do is put the caret on a field inside a property and boom.  I wasn't refactoring anything, but I figure maybe it was going to tell about options for refactoring.  The class in question is nested inside another class in a namespace.

**Comment by WillPittenger** [comment] 2017-04-13 00:33
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetCallSiteContainerFromExpression()
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetOutermostCallSiteContainerToProcess(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by weitzhandler** [comment] 2017-05-02 15:08
Issue still exists on VS 15.1 26403.7.

**Comment by Pilchie** [comment] 2017-05-02 15:37
Yes, the issue is still Open, and is currently targeted at the 15.3 milestone.

**Comment by weitzhandler** [comment] 2017-05-02 17:35
oops sorry i missed that, thanks for your response, deleting my posts to keep the thread clean

**Comment by Pilchie** [comment] 2017-05-15 16:03
Also reported in https://developercommunity.visualstudio.com/content/problem/56279/extractmethodecoderefactoringprovider-encountered.html

**Comment by sharwell** [comment] 2017-06-01 17:00
This was fixed in #18375.

**Comment by dpoeschl** [comment] 2017-09-26 02:26
Looks like it's happening in 15.3.4

https://developercommunity.visualstudio.com/content/problem/113806/extractmethodcoderefactoringprovider-encountered-a-10.html

**Comment by joel081112** [comment] 2020-01-14 10:01
Its happening for me on the latest version

**Comment by sharwell** [comment] 2020-05-13 16:40
The issues happening today are not the same as the issue that led to this report, so I'm going to close this one as a duplicate of the very old one.

**Closed by sharwell** 2020-05-13 16:40 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
