### ISSUE TITLE
Incorrectly inserting using statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25980] opened 2018-04-06 01:47 UTC
For C# in Visual Studio Community 2017, after adding a class that derives from another class in an explicitly named namespace, typing &quot;override&quot; and hitting tab to allow the autocomplete to populate my override method causes Visual Studio to insert a using statement to the base class's namespace at the top of the file.

Example:

```csharp
public class DerivedClass : UndesiredNamespace.BaseClass
{
    override 
}
```

after hitting tab to accept autocomplete turns into

```csharp
using UndesiredNamespace;

public class DerivedClass : UndesiredNamespace.BaseClass
{
    public override int SomeMethod(int arg)
    {
        return base.SomeMethod(arg);
    }
}
```

This is undesired behavior.  I neither need nor want the using statement, and I cannot find an option to turn this behavior off.  Please either remove the insertion of the using statement, provide an option to turn off this behavior, or point me to where such an option is hiding if it already exists.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/224645/incorrectly-inserting-using-statements.html
VSTS ticketId: 591396_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎4‎/‎2‎/‎2018, 03:15 AM (3 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, we will continue to monitor this.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-02-04 21:27
Closing out.  THis is very much by design and we've heard very little feedback from people disliking this.  Note: We do not add a using for `System` for the `throw` statement if we generate one.  That addressed the bulk of hte feedback we got here.

**Closed by CyrusNajmabadi** 2022-02-04 21:27 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community
