### ISSUE TITLE
Use of unassigned local variable

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#72974] opened 2024-04-10 21:36 UTC
```c#
   internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        static void Test(dynamic obj)
        {
            if (obj is string str1)
                Console.WriteLine(str1); // No problem
            if (Check(obj) && obj is string str2)
                Console.WriteLine(str2); // Use of unassigned local variable
        }

        static bool Check(dynamic obj) => true;
    }
```

**Comment by huoyaoyuan** [comment] 2024-04-18 05:56
I can't reproduce this with VS 17.10P4.

**Comment by CreateAndInject** [comment] 2024-04-18 14:15
I tested on 17.6.14

**Comment by huoyaoyuan** [comment] 2024-04-18 16:12
Since Windows 7 has reached EOL for years, there won't be effort to enable newer versions on Windows 7.
The compiler don't backport this type of fix to previous channels.

**Comment by CreateAndInject** [comment] 2024-04-18 20:22
Can you reproduce this issue on VS2019 and older VS2022?

**Comment by jaredpar** [comment] 2024-04-22 18:51
Closing as this bug does not reproduce on more recent compilers and this is not severe enough of a bug for us to service older releases.

**Closed by jaredpar** 2024-04-22 18:51 UTC
Labels: Area-Compilers, untriaged
