### ISSUE TITLE
generate task from interface does not add async

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41590] opened 2020-02-12 00:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/904547/generate-task-from-interface-does-not-add-async.html)._

---
Hi,
I have an interface definition like this:

```
public interface IUserManager
{
Task<AvsWebUser> GetItemById(string id);
}
```
when deriving a class from it and use "implement interface" I get

```
public Task<AvsWebUser> GetItemById(string id){ }
```
but would expect
```
public async Task<AvsWebUser> GetItemById(string id){ }
```
Am I  wrong?
Cheers.
Josef

---
#### Visual Studio Feedback System on 2/3/2020, 09:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-02-12 00:20
Tentatively marking this as **By Design**, but will update with more information after the next design review.

**Comment by sharwell** [comment] 2020-03-24 19:30
Duplicate of #27181

**Closed by sharwell** 2020-03-24 19:30 UTC
Labels: Area-IDE, Feature Request, IDE-CodeStyle, Need Design Review, Resolution-By Design
