### ISSUE TITLE
Unexpected default formatting for multi-line switch expressions

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#36589] opened 2019-06-19 21:48 UTC
Type the following code (IDE will format it as follows):
```
            var i = 3;
            var str = i switch
            {
                1 => "1",
                2 => "2",
                3 => "3",
            };
```

Expected: The body of the expression should be indented to the right.
Like this:
```
            var str = i switch
                {
                    1 => "1",
                    2 => "2",
                    3 => "3",
                };
```

Or even better like this:
```
            var i = 3;
            var str = i switch
                      {
                          1 => "1",
                          2 => "2",
                          3 => "3",
                      };
```

Motivation - improved readability.

**Comment by CyrusNajmabadi** [comment] 2019-06-20 17:35
I actally expect the first form (similar to object/collection literals).  But i agree that the otehr forms seem reasonable and that this could def fall under a formatting option.   Tagging @sharwell for visibility.

**Comment by sharwell** [comment] 2019-06-20 23:23
Duplicate of #34272

**Comment by sharwell** [comment] 2019-06-20 23:24
:memo: This already went to a design review, and the current brace placement was deemed by-design. See https://github.com/dotnet/roslyn/issues/34272#issuecomment-479168753.

**Closed by sharwell** 2019-06-20 23:23 UTC
Labels: Area-IDE, New Language Feature - Pattern Matching
