### ISSUE TITLE
Inline method

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38636] opened 2019-09-11 18:09 UTC
Customer Request Copying Here

>It should propose to replace method calls with content of the method and delete the method definition (this is really tedious to do manually):

![image](https://user-images.githubusercontent.com/46729679/64723073-a295ab00-d484-11e9-9f49-2983cc66df44.png)

**Comment by jinujoseph** [comment] 2019-12-04 19:59
Dupe of https://github.com/dotnet/roslyn/issues/22052

**Closed by jinujoseph** 2019-12-04 19:59 UTC
Labels: Area-IDE, Concept-Continuous Improvement
