### ISSUE TITLE
VBCSCompiler not cancelling when existing VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33538] opened 2019-02-21 00:38 UTC
I have a lot of analyzers for a particular build configuration and even after exiting VS, VBCSCompiler will continue to run - looks like cancellation when there are slow analyzers is no longer working in latest preview.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/438750/vbcscompiler-not-cancelling-when-existing-vs.html
VSTS ticketId: 780026_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jaredpar** [comment] 2019-09-09 20:54
Resolving as a duplicate of #38342. 

The core issue here is that when you cancel an MSBuild invocation the compiler will not actively cancel the compilations that are in progress. Rather it will let them run to completion and then ignore the results.

That behavior has not changed since it was originally authored. But recently it's started showing up as probably not the desired behavior and #38342 tracks fixing it.

**Closed by jaredpar** 2019-09-09 20:54 UTC
Labels: Area-Compilers, Investigation Required
