### ISSUE TITLE
Visual Basic "Move Type to..." refactoring for nested types duplicates entire parent type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66018] opened 2022-12-14 20:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Basic-Move-Type-to-refactori/10208440)._

---
When I use the "Move type to..." refactoring on any nested type in Visual Basic, a new code file is created for the nested type, and the parent class is declared as partial (as I would expect). However, instead of including only the nested type, the entire parent type is duplicated in the new file. This makes the refactoring effectively useless, since I have to manually remove the duplicated class content in the new file.

---
#### Feedback Bot on 11/21/2022, 05:02 PM: 

(private comment, text removed)
#### Feedback Bot on 12/5/2022, 11:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-12-14 21:11
Duplicate of https://github.com/dotnet/roslyn/issues/22012

**Comment by CyrusNajmabadi** [comment] 2024-10-26 17:23
Closing as dupe

**Closed by CyrusNajmabadi** 2024-10-26 17:23 UTC
Labels: Area-IDE, IDE-CodeStyle
