### ISSUE TITLE
CCRewrite unhappy with Toolset Compilers 1.0.0-rc1-20150113-03

### ISSUE THREAD

**Issue by codespare** [dotnet/roslyn#21] opened 2015-01-17 14:28 UTC
After upgrading from to Microsoft.Net.ToolsetCompilers.1.0.0-beta2-20141216-04, CodeContract ccrewrite.exe (latest, v1.7.11202.10) starts to fail during build with:
error CC1099: Contract extraction failed: Found field <>8__1 in contract that shouldn't be here: In method ns.type.member.
Exact same code had no issue with Microsoft.Net.ToolsetCompilers.1.0.0-beta2-20141223-03.
Function exhibiting error is in a static class, along the lines of:

    public static IEnumerable<tuple<object, MemberInfo, LinkArity, int, LinkDirection, object, LinkOutput>> BreadthFirstTraversal(
            object fromObject,
            Func<object, IEnumerable<Tuple<MemberInfo, LinkArity>>> getSubjectRelations,
            Func<object, MemberInfo, LinkArity, IEnumerable<Tuple<int, object, LinkOutput>>> getRelatedObjects,
            IEqualityComparer<object> nodeComparer = null
            )
        {
            Contract.Requires<ArgumentNullException>(getSubjectRelations != null);
            Contract.Requires<ArgumentNullException>(getRelatedObjects != null);
        ...

so with only 2 simple preconditions. Function body uses yield return after that.
Commenting out the contracts removes the build error.
This only occurs in a few instances overall, the majority of contracts are unaffected, but I haven't identified the exact pattern causing that issue yet.
In another instance, ccrewrite goes through, but runtime behavior becomes faulty with a precondition asserting systematically.

**Comment by codespare** [comment] 2015-01-17 14:46
And re-reading myself I realize nuget also has an issue merrily upgrading Microsoft.Net.ToolsetCompilers 1.0.0-beta2-20141223-03 to Microsoft.Net.ToolsetCompilers 1.0.0-beta2-20141216-04 instead of Microsoft.Net.ToolsetCompilers 1.0.0-rc1-20150113-03... but the issue remains after rectifying that (and double checking the .csproj and the build output and restarting Visual Studio).

**Comment by tmat** [comment] 2015-01-17 18:33
Could you share the binary before CC rewrites it?

**Comment by tmat** [comment] 2015-01-17 18:59
I think I found what the problem is in Code Contracts. I have contacted the owners to see how CC can be fixed.

**Comment by codespare** [comment] 2015-01-25 12:25
Apologies for the delay in replying, I should check github web interface more often... Do you or the Code Contracts team still want the assembly prior to rewrite?

**Comment by tmat** [comment] 2015-01-26 04:51
Not necessary. We know where the problem is. As a workaround I'd recommend avoiding using Code Contracts in iterator and async methods.

**Comment by codespare** [comment] 2015-01-26 13:15
All right, that's manageable, thank you. I saw even ILSpy can only render the complete source in IL, and by the looks of it, rewriting that is no mean feat. Hopefully no one will request an async iterators feature :)

**Comment by gafter** [comment] 2015-06-23 17:31
@tmat Can you please close this issue if it isn't actionable in the Roslyn code base?

**Closed** 2015-09-01 15:30 UTC
Labels: 1 - Planning, Area-Compilers, Bug, Resolution-By Design
