### ISSUE TITLE
Linux compilation fails in multi-user environments due to sharing same tmp folder when using source generation

### ISSUE THREAD

**Issue by Skyedra** [dotnet/roslyn#68852] opened 2023-07-02 00:55 UTC
**Version Used**: 7.0.305

**Steps to Reproduce**:

1. Download & install Ubuntu 22.04LTS on virtualbox (issue also occurs on real hardware, VM is just to show a clean environment this happens on)
2. Add users:
```
sudo -i
useradd -m dotnetuser1
useradd -m dotnetuser2
```
4. Login as user 1 and install dotnet 7
```
su - dotnetuser1
bash
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 7.0
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
```
5. Create test project
```
mkdir test
cd test
dotnet new console
nano Program.cs
```
Replace Program.cs with this test:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

public static partial class ServerTagInfer
{
	public static readonly Regex TagLikeRegex = MyRegex();

	public static void main()
	{
		string testInput = "[1]hi";

		// Extract all name [tags] via regex.
		var tagLikes = TagLikeRegex
			.Matches(testInput)
			.Select(x => x.Groups[1].Captures[0].Value)
			.ToHashSet(StringComparer.CurrentCultureIgnoreCase);

		if (tagLikes.Contains("1"))
		{
			Console.WriteLine("Found the [1] tag.");
		} else {
			Console.WriteLine("Did not find the [1] tag.");
		}
	}

	[GeneratedRegex("\\[(.*?)\\]")]
	private static partial Regex MyRegex();
}

```
6. Build:
```
dotnet build
```
It compiles OK.
7. Note some leftover artifacts:
```
ls -lth /tmp | grep Compile
# drwxrwxr-x 3 dotnetuser1 dotnetuser1 4.0K Jul  1 17:16 VBCSCompiler
# Note write permission missing.
ps aux | grep dotnet
# dotnet process still running
```
8. Now, repeat step 4 as user 2 to install dotnet 7
9. Repeating step 5 to create the new project will result in an error during `dotnet new console`
```
dotnetuser2@UbuntuTest:~/test$ dotnet new console
System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
This is because dotnet is still running as the other user.  You can `killall dotnet` as root to continue and get the new project init to work.
10. Set up the Program.cs with the sample code
11. Attempt building as before.
```
dotnetuser2@UbuntuTest:~/test$ dotnet build
MSBuild version 17.6.3+07e294721 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
/home/dotnetuser2/test/Program.cs(29,34): error CS8795: Partial method 'ServerTagInfer.MyRegex()' must have an implementation part because it has accessibility modifiers. [/home/dotnetuser2/test/test.csproj]

Build FAILED.

CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly /home/dotnetuser2/.dotnet/packs/Microsoft.NETCore.App.Ref/7.0.8/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll : Access to the path '/tmp/VBCSCompiler/AnalyzerAssemblyLoader/d3aff803d8bd4895a8186f2d01a7d081' is denied. [/home/dotnetuser2/test/test.csproj]
/home/dotnetuser2/test/Program.cs(29,34): error CS8795: Partial method 'ServerTagInfer.MyRegex()' must have an implementation part because it has accessibility modifiers. [/home/dotnetuser2/test/test.csproj]
    6 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.46
```
12. Workaround by as root `rm -rf /tmp/VBCSCompiler/` and `killall dotnet`
13. Now compile works as user 2

**Diagnostic Id**:

CS8034

**Expected Behavior**:  No errors are generated.  dotnet ceases running when compile finishes.  

**Actual Behavior**:  Errors are generated.  dotnet continues running in background.

**Thought**: Possibly temporary folders should be per-user?

**Comment by jaredpar** [comment] 2023-08-09 23:07
thanks for filing. This is a dupe of #65415 that I just merged a PR to fix.

**Closed by jaredpar** 2023-08-09 23:07 UTC
Labels: Resolution-Duplicate, Area-Compilers

**Comment by Skyedra** [comment] 2023-08-10 08:28
Awesome, thanks much!
