### ISSUE TITLE
Overridden != and == do not affect nullability

### ISSUE THREAD

**Issue by Forgind** [dotnet/roslyn#74010] opened 2024-06-14 18:24 UTC
**Version Used**: 

**Steps to Reproduce**:

1. Try running nullable checks on the code snippet below. It passes. It shouldn't.
[code](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAxAOwK4QgQwEYQFMACA1PQgWACgABAJiIFkBPAFQAsxUBzagb2pEhRGgGYRARgBsRXAHs5EInIAOBAE7Zgc9UQC8egBQsOXbgH4iEdgGcoTNpx6X1tgJSDhAqsN8iA7EQAZtgQNgQA3J5CAL7U0SLiNNKyCkqqGlo6RACERiZOFla29gVmLu4J3n7CNIHA6uiRCXFUCWLKAG4a6mAwxPKKRACiAI7ooTaGcrgAVgQAxsCWM7Nu+gB8wZPNbT614nLd6r39RFzARADiBMAAEtg27ADCcv2G63pbElF7vh3JGRlHhEABKt3Q6lQph4HyqCV8wKKwEK+iIGCwvxqQjAQSIhhRZlyenRmAgHn2NWq2P+9UKWOxrQRtUCqAIAHcHDDuB8GbFqK00GTyMQYGAbCKgA)

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic ID and message if possible (e.g. `"IDE0030: Use coalesce expression"`).

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment] 2024-06-14 18:50
Closing out as by design.  The analysis here assumes well intentioned code, not APIs that return strange values.  If `!= null` doesn't have the semantics "not equal to null" that's a problem with the `!=` impl.

**Closed by CyrusNajmabadi** 2024-06-14 18:50 UTC
Labels: Area-Compilers, untriaged
