### ISSUE TITLE
Cant see definitions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32534] opened 2019-01-16 20:55 UTC
I get the error cannot navigate to the symbol under the caret.

```csharp
public class T
{
  new // <-- caret is on the 'new' keyword
  void Method() { }
}
```

1. Place the caret on the `new` keyword
2. Press <kbd>F12</kbd>

The following message is shown in a pop-up dialog:

> Cannot navigate to the symbol under the caret.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/346960/cant-see-definitions.html
VSTS ticketId: 694698_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2019-01-18 16:17
It's not clear to me where the navigation should go. Navigation is largely based on what the compiler binds, and I don't think we have anything reasonable to bind in this invalid code.

**Comment by CyrusNajmabadi** [comment] 2023-02-10 15:00
Closing out as this is working as intended.

**Closed by CyrusNajmabadi** 2023-02-10 15:00 UTC
Labels: Bug, Area-IDE, Developer Community, Need Design Review
