### ISSUE TITLE
Quick fix does not respect code style preferences

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14077] opened 2016-09-26 20:39 UTC
I might have seen this somewhere but can't find it now.

**Version Used**: 2.0.0.60923

**Steps to Reproduce**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            string s = "";
            new Program(s);
        }
    }
}
```

![capture](https://cloud.githubusercontent.com/assets/10546952/18850910/780d3b60-8431-11e6-826b-7fe77761b597.PNG)
Invoke the generate constructor quick fix.

**Expected Behavior**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        private string _s;

        public Program(string s)
        {
            _s = s;
        }

        static void Main(string[] args)
        {
            string s = "";
            new Program(s);
        }
    }
}
```

**Actual Behavior**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        private string s;

        public Program(string s)
        {
            this.s = s;
        }

        static void Main(string[] args)
        {
            string s = "";
            new Program(s);
        }
    }
}
```

**Comment by dpoeschl** [comment] 2016-09-29 18:30
Rather than implement something that handles this problem for every quick fix, perhaps a targeted fix for this case would alleviate the pain of a common case.

**Comment by CyrusNajmabadi** [comment] 2016-11-09 01:15
This seems by design to me.  The preference option is about if you want "this." or not when "this." is optional.  In this case, "this." is required, because "s = s" would be incorrect.

Now, what we probably want is for this feature to follow your *naming* preferences.  So if you've said that "fields need to start with _", then we'll create a field with that name.

**Comment by Pilchie** [comment] 2016-11-09 02:01
@CyrusNajmabadi That's exactly what @miloush seems to be requesting in the "Expected" section.

**Comment by CyrusNajmabadi** [comment] 2016-11-09 02:02
Ok.  :)

I'm just pointing out that this would be unaffected by the "do not prefer this." option.

**Comment by miloush** [comment] 2017-01-20 11:34
I see, sorry, both you are correct, this wasn't a good example as there is a conflict in the constructor. I think the main problem here might be that I was interpreting "do not prefer this" as "use underscores".

I expect the code style to be followed in the optional cases. If that is the case now, this can be closed or transferred to the feature request of following the naming preferences.

**Closed** 2019-02-27 21:33 UTC
Labels: 4 - In Review, Area-IDE, Bug
