### ISSUE TITLE
Proposal: add a null-coalescing-assignment operator

### ISSUE THREAD

**Issue by emsaks** [dotnet/roslyn#13628] opened 2016-09-06 20:46 UTC
It would be nice to have a null-coalescing assignment operator, like so:

`buffers[i] ??= new byte[4*1024*1024];` 

This would help in a case where one operation doesn't need all of the buffers, so it only initializes some of them, and a subsequent operation needs to utilize more of them - instead of re-initializing all of the buffers, it reuse previous ones and only initialize the indices that are null. Currently, the code would look like this:

`for (int i; i < MAX_IO; i++)`
`{`
`buffers[i] = buffers[i] ?? new byte[4*1024*1024];`
`}`

which could be simplified using the proposed operator.

**Comment by svick** [comment] 2016-09-06 21:38
This is a duplicate of https://github.com/dotnet/roslyn/issues/205 (and few other issues), which was closed by @gafter:

> The benefits of this proposal do not overcome the drawbacks in terms of language complexity. It is unlikely to ever have a high enough benefit-for-cost to make us prefer it over many other things we could do in this release or many releases into the future.

**Comment by ashmind** [comment] 2016-09-08 08:45
I think it's worth having, and in fact I did a prototype in the thread linked above (which is https://is.gd/BOcmcy at TryRoslyn). It does not include `||=` and `&&=`, but a full implementation should consider those as they play a similar role.

The implementation isn't too hard, aside from questions in IDE support where I didn't fully understand the implications. It's a conversion -- prototype does `x = x ?? y`, though now I think it should be `if (x == null) x = y;`

**Comment by alrz** [comment] 2016-09-08 13:02
@ashmind I think in the expression context `x ??= y` should be translated to `(x ?? (x = y))` and in the statement context it'll be `if((object)x==null) x = y;`.

**Comment by gafter** [comment] 2018-01-08 02:02
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

This may be close enough to https://github.com/dotnet/csharplang/issues/34 that discussion can continue there.

**Closed by gafter** 2018-01-08 02:02 UTC
Labels: 0 - Backlog, Area-Language Design
