### ISSUE TITLE
ESLint style single line ignore and lightbulb improvements

### ISSUE THREAD

**Issue by johnnyreilly** [dotnet/roslyn#60668] opened 2022-04-09 13:27 UTC
The actual issue that I had in https://github.com/dotnet/roslyn/issues/60620 I now consider solved. (A better way of expressing it might be to say that it wasn't an issue; I just didn't understand correctly 😅) 

I've got some developer experience feedback that has occurred to me, as a consequence of writing a [blog post that talks about linting in C# as compared to JS/TS with ESLint](https://blog.johnnyreilly.com/2022/04/06/eslint-your-csharp-in-vs-code-with-roslyn-analyzers). Essentially things that the JS/TS ecosystem has that are quite nice that dotnet does not.

I love the lightbulb 💡. When I'm developing, I love the auto fixes and suggestions that it provides. 

I don't want to act upon each lint diagnostic. I may just want to ignore a particular one. This is made very easy in the JavaScript ecosystem for two reasons:

1. It's a one liner with ESLint - I can deactivate linting for a single line with `// eslint-disable-next-line`. 

![screenshot of "// eslint-disable-next-line no-var"](https://user-images.githubusercontent.com/1010525/162576182-782893c4-3cc0-4a61-aa62-ed5ec005c6f2.png)

2. ESLint has a VS Code extension which for lints it will present a lightbulb 💡. And one of the options is "ignore the line" which will apply a `// eslint-disable-next-line` to do just that.

![screenshot of the lightbulb menu in TS/JS including "Disable no-var for this line"](https://user-images.githubusercontent.com/1010525/162576039-e805290d-fd24-48eb-848b-32aacf87ed77.png)

It would be awesome if a similar mechanisms existed in dotnet.

## Single line ignore

Obviously I can ignore single lines in C#, but it takes me 2 lines of code to achieve it; like so:

```cs
#pragma warning disable IDE0052
    private readonly ILogger<WeatherForecastController> _logger;
#pragma warning restore IDE0052
```

What if instead, something like this existed:

```cs
#pragma warning disable-line IDE0052
    private readonly ILogger<WeatherForecastController> _logger;
```

Which disabled a single line of linting

## Lightbulb

Imagine if the lightbulb with the C# extension offered the option to ignore a lint; just as the ESLint menu does.  Quite the timesaver. 

I'm not too sure where this feedback should go, but I thought I'd share it here to start with. What do people think? And more than that, is this the right place to discuss this?

**Comment by Youssef1313** [comment] 2022-04-10 07:32
This is a language change. Not something Roslyn can do directly, I think. It should start as a discussion in dotnet/csharplang

**Comment by jinujoseph** [comment] 2022-04-19 19:05
@sharwell

**Comment by sharwell** [comment] 2022-04-20 02:29
Duplicate of https://github.com/dotnet/csharplang/discussions/1070

**Closed by sharwell** 2022-04-20 02:29 UTC
Labels: Area-IDE, Feature Request

**Comment by sharwell** [comment] 2022-04-20 02:31
Note that the light bulb already provides the option to suppress a diagnostic:
![image](https://user-images.githubusercontent.com/1408396/164135189-b4e2f2e0-c510-4234-8b73-3aefc85c5fe2.png)

**Comment by johnnyreilly** [comment] 2022-04-20 05:12
Hi @sharwell - I don't see that option in the lightbulb for VS Code - I think that may be a visual studio only option. Take a look at my screenshots further up and you'll see what I see. Or am I missing something hiding in plain sight?

**Comment by johnnyreilly** [comment] 2022-04-20 05:16
![Screenshot from 2022-04-20 06-14-56](https://user-images.githubusercontent.com/1010525/164155501-1aa17137-81c6-4e60-b6c8-30e7c53248b9.png)

This is what we see in VS Code.

**Comment by CyrusNajmabadi** [comment] 2022-04-20 06:09
@333fred for feedback on vscode.

**Comment by Youssef1313** [comment] 2022-04-20 06:33
@CyrusNajmabadi

https://github.com/dotnet/roslyn/blob/e1629052738683dac234a4d75bb1d1c442c46d7d/src/Features/CSharp/Portable/CodeFixes/Suppression/CSharpSuppressionCodeFixProvider.cs#L26-L27

This is the only codefix that doesn't have `ExportCodeFixProvider` and doesn't inherit `CodeFixProvider` (`AbstractSuppressionCodeFixProvider` only implements an `IConfigurationFixProvider` interface).

It seems there is a wrapper `CodeFixProvider`:

https://github.com/dotnet/roslyn/blob/e1629052738683dac234a4d75bb1d1c442c46d7d/src/Features/Core/Portable/CodeFixes/Suppression/WrapperCodeFixProvider.cs#L19

But it also doesn't have the attribute (and its constructor is not parameterless).

Things around this CodeFixProvider is special cased here:

https://github.com/dotnet/roslyn/blob/e1629052738683dac234a4d75bb1d1c442c46d7d/src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs#L679-L696
