### ISSUE TITLE
Chinese string is compiled to garbage characters

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/roslyn#4255] opened 2015-07-31 11:18 UTC
A project that includes the following C# code：
```csharp
public class Pager : Control
{
    protected string PreviousText = "上一页";
    protected string NextText = "下一页";

    //...
}
```
Build it with Visual Studio 2015 and get a assembly.
Decompile the assembly with ILSpy and get the following garbage characters.
```csharp
public class Pager : Control
{
    protected string PreviousText = "ÉÏÒ»Ò³";
    protected string NextText = "ÏÂÒ»Ò³";
    //...
}
```
View IL code with ildasm and get the following result.
```
.maxstack  2
IL_0000:  ldarg.0
IL_0001:  ldstr      bytearray (C9 00 CF 00 D2 00 BB 00 D2 00 B3 00 ) 
IL_0006:  stfld      string BlogServer.Web.Controls.Pager::PreviousText
IL_000b:  ldarg.0
IL_000c:  ldstr      bytearray (CF 00 C2 00 D2 00 BB 00 D2 00 B3 00 ) 
IL_0011:  stfld      string BlogServer.Web.Controls.Pager::NextText
```
If build it with Visual Studio 2013, get right Chinese string and the following IL code.
```
.maxstack  2
IL_0000:  ldarg.0
IL_0001:  ldstr      bytearray (0A 4E 00 4E 75 98 )                               // .N.Nu.
IL_0006:  stfld      string BlogServer.Web.Controls.Pager::PreviousText
IL_000b:  ldarg.0
IL_000c:  ldstr      bytearray (0B 4E 00 4E 75 98 )                               // .N.Nu.
IL_0011:  stfld      string BlogServer.Web.Controls.Pager::NextText
```

**Comment by CrazyViper** [comment] 2015-07-31 12:06
@cnblogs-dudu 
It seems the same problem as #4222: VS2015 (MSBuild/14) compiler can't detect file ecoding correctly

**Comment by cnblogs-dudu** [comment] 2015-07-31 12:48
@CrazyViper 
Exactly! Saving .cs file with UTF-8 encoding fixes it.

**Comment by CrazyViper** [comment] 2015-07-31 13:11
@cnblogs-dudu 
Yep, but it still the regression bug in the new compiler.

**Comment by cnblogs-dudu** [comment] 2015-07-31 14:56
@CrazyViper 
So we should leave the issue open.

**Comment by jaredpar** [comment] 2015-07-31 18:29
This may be a duplicate of #4264.

**Comment by AlekseyTs** [comment] 2015-08-02 17:45
@cnblogs-dudu, what is the code page of the .cs file and what is the default ANSI code page of the OS?

**Comment by cnblogs-dudu** [comment] 2015-08-02 23:39
@AlekseyTs 
They are both 936 (GBK—Chinese (PRC, Singapore)).

**Comment by AlekseyTs** [comment] 2015-08-05 00:07
@cnblogs-dudu, Could you please verify if #4303 fixed the issue?

**Comment by AlekseyTs** [comment] 2015-08-05 00:08
@jaredpar Please verify

**Closed** 2015-08-05 00:10 UTC
Labels: Area-Compilers, Bug, Resolution-Fixed
