### ISSUE TITLE
"ref" modifier is suggested for classes

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59966] opened 2022-03-05 12:35 UTC
Related to https://github.com/dotnet/roslyn/issues/59965. The main focus in https://github.com/dotnet/roslyn/issues/59965 is the fact, that I alredy have a "structure type" (class, struct, enum...) but VS suggests them, even though it shouldn't. Here the focus is that completion of modifiers does not provide it's suggestions based on the context

**Version Used**:
VS 2022 v17.2 Preview 1

**Steps to Reproduce**:
```
public $$ class Test
{

}
```
$$ - place, where to invoke completions

**Expected Behavior**:
"ref" keyword suggestion is not shown

**Actual Behavior**:
![devenv_kE8fHq35Gm](https://user-images.githubusercontent.com/70431552/156883148-6a56bf78-eb90-4b39-8c68-a4b780e8b16c.png)

**Comment by CyrusNajmabadi** [comment] 2022-03-05 14:17
Closing as by design for the same reason as the other issue.

**Closed by CyrusNajmabadi** 2022-03-05 14:17 UTC
Labels: Area-IDE, untriaged
