### ISSUE TITLE
CSharpRazor fails with MissingMethodException

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7162] opened 2015-12-01 21:50 UTC
In the WebUtilities action:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Microsoft.Html.Editor.Document.HtmlEditorDocument Microsoft.Html.Editor.Document.HtmlEditorDocument.FromTextView(Microsoft.VisualStudio.Text.Editor.ITextView)'.
    at Microsoft.VisualStudio.Web.Common.TestServices.Services.HtmlParseTreeService.<>c.<IsReady>b__0_0()
    --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Delegate.DynamicInvokeImpl(Object[] args)
    at System.Delegate.DynamicInvoke(Object[] args)
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByFunc(Object[] values) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 129
    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
    --- End of inner exception stack trace ---

 Server stack trace: 
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(RemoteInvoker invoker, RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 105
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(IRemoteUIThreadInvokerService invoker, RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 78
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn[T](IRemoteUIThreadInvokerService invoker, Func`1 func) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 39
    at Microsoft.Test.Apex.Hosts.MarshallableApexObject.UIInvoke[T](Func`1 func) in f:\dd\src\Omni\Apex\Framework\Hosts\MarshallableApexObject.cs:line 416
    at Microsoft.VisualStudio.Web.Common.TestServices.Services.HtmlParseTreeService.IsReady() in C:\dd2\WTE\Main\test\Common\TestServices\Services\HtmlParseTreeService.cs:line 23
    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

 Exception rethrown at [0]: 
    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
    at Microsoft.VisualStudio.Web.Common.TestServices.Services.HtmlParseTreeService.IsReady()
    at Microsoft.VisualStudio.Web.Common.TestServices.Utilities.WebUtility.<>c__DisplayClass19_0.<WaitForParseTreeReady>b__0() in C:\dd2\WTE\Main\test\Common\TestServices\Utilities\WebUtility.cs:line 299
    at Omni.Common.WaitFor.TryIsTrue(Func`1 predicate, TimeSpan timeout, Nullable`1 interval) in f:\dd\src\Omni\Common\WaitFor.cs:line 68
    at Microsoft.VisualStudio.Web.Common.TestServices.Utilities.WebUtility.WaitForParseTreeReady(Int32 timeout) in C:\dd2\WTE\Main\test\Common\TestServices\Utilities\WebUtility.cs:line 297
    at Microsoft.VisualStudio.Web.Common.TestServices.Utilities.WebUtility.WaitForCodeReady() in C:\dd2\WTE\Main\test\Common\TestServices\Utilities\WebUtility.cs:line 316
    at Roslyn.VSHosting.Test.WebUtilitiesAction.WaitForCodeReady() in c:\src\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\WebUtilitiesAction.cs:line 20
 
```

**Comment by Pilchie** [comment] 2015-12-03 17:40
I suspect that the issue here is that we need to update our VS automation binaries to the Update 1 version.

**Comment by Pilchie** [comment] 2016-02-08 23:06
This is a duplicate of internal bug 161421 on @balajikris

**Closed by Pilchie** 2016-02-08 23:06 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate, Test
