### ISSUE TITLE
When doing a "fix all" there's no indication that anything is happening

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15761] opened 2016-12-08 09:45 UTC
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Change your VB code style settings to:
![image](https://cloud.githubusercontent.com/assets/1103906/21003545/17200750-bd80-11e6-9058-5a78ad4bd2bd.png)
5. Open a file with "Me.
6. Drop lightbulb, and click Fix all in solution
-- Notice UI isn't blocked, appears if nothing is happen --
7. Drop lightbulb, and click Fix all in project
8. Drop lightbulb again, and click Fix all in project

I could get three or four preview windows showing up.

![image](https://cloud.githubusercontent.com/assets/1103906/21005104/90776c72-bd87-11e6-9def-46ef39eb013e.png)

Given it took so long and was async had zero indication that anything was happening.

**Comment by jmarolf** [comment] 2016-12-08 09:46
dupe of https://github.com/dotnet/roslyn/issues/15411 I hope to get a fix out for this soon

**Comment by Pilchie** [comment] 2016-12-12 21:53
Closing as dupe.

**Closed by Pilchie** 2016-12-12 21:53 UTC
Labels: Area-IDE
