### ISSUE TITLE
Goto Definition doesn't utilize source linking when available.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#49292] opened 2020-11-11 20:15 UTC
# Repro

Find a package with source linking available, like https://www.nuget.org/packages/TerraFX.Interop.Windows/10.0.19041-beta1.

Add it as a package reference and add some simple code utilizing members from it:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.19041-beta1" />
  </ItemGroup>

</Project>
```

```cs
using TerraFX.Interop;
using static TerraFX.Interop.Windows;

namespace ConsoleApp65
{
    class Program
    {
        static unsafe void Main(string[] args)
        {
            IDXGIFactory2* dxgiFactory;
            var iid = IID_IDXGIFactory2;
            CreateDXGIFactory2(default, &iid, (void**)&dxgiFactory);
            dxgiFactory->Release();
        }
    }
}
```

Select `IDXGIFactory2` and `Goto Definition`. The same goes for any member, but `IID_IDXGIFactory2` and `CreateDXGIFactory2` are members in a 40k member class (Interop Code), so it may take some time to complete for these members.

# Expected Behavior

Since source linking is available, it should be preferred over decompilation and over showing metadata.

# Actual Behavior

Goto Definition does not use the source linked files and instead opts for decompiling the sources instead:
![image](https://user-images.githubusercontent.com/10487869/98859134-8ab61000-2416-11eb-88c3-f0a25e8c5e4d.png)

Choosing "no" on decompilation results in metadata being shown as well:
![image](https://user-images.githubusercontent.com/10487869/98859349-e4b6d580-2416-11eb-8309-ad314b1f2436.png)

# Additional Information

Source linking can be confirmed to be enabled/correct by single stepping into `dxgiFactory->Release()`

**Comment by jinujoseph** [comment] 2020-11-17 21:04
Duplicate of https://github.com/dotnet/roslyn/issues/24349

**Closed by jinujoseph** 2020-11-17 21:04 UTC
Labels: Area-IDE
