### ISSUE TITLE
Declared type precedence in new operator (regression)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#2836] opened 2015-05-17 00:16 UTC
Mentioned but not addressed in comments at CodePlex [#138](https://roslyn.codeplex.com/workitem/138).

```csharp
bool b;
Program p = new |
b = false;
```

This results in Intellisense offering `bool` instead of `Program`. There is no scenario where `bool` would be acceptable at this place (or where the code after cursor would be relevant to what is following the `new` operator).

This worked in previous version of Visual Studio.

**Comment by Pilchie** [comment] 2015-05-18 17:25
I believe this is a dupe of something @rchande recently fixed.  Can you find the issue and close?

**Comment by rchande** [comment] 2015-05-18 17:35
This was tracked by an internal workitem, but is fixed by this commit: https://github.com/dotnet/roslyn/commit/a97484ae74646712bbc17fc33f06a01fbb9c6d7b.

**Comment by tmat** [comment] 2015-06-11 01:13
Still reproes.

![image](https://cloud.githubusercontent.com/assets/41759/8097829/64aa23e0-0f9c-11e5-8e72-6b8f9cd550a5.png)

**Comment by Pilchie** [comment] 2015-06-11 02:16
Can you take a look?

**Comment by rchande** [comment] 2015-06-11 03:16
Ah, this is slightly different than the case I fixed.

**Comment by balajikris** [comment] 2015-06-11 07:47
Submitting a PR shortly.

**Comment by balajikris** [comment] 2015-06-11 18:51
Fix submitted to master for Update 1.

**Comment by balajikris** [comment] 2015-06-11 19:58
Test and address compound assignment cases, if the fix doesn't address it:

```C#
int i;
Program p = new |
i += 1;
```

**Closed** 2015-08-18 22:20 UTC
Labels: 4 - In Review, Area-IDE, Bug

**Comment by miloush** [comment] 2016-07-24 21:01
Still seeing this (15.0.25428.1/2.0.0.60620):

```C#
int[] array;

Program p = new |
array[4] = 4;
```
