### ISSUE TITLE
inline temporary variable creates invalid output

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23155] opened 2017-11-14 00:48 UTC
Relevant code: https://github.com/mrexodia/AStyleHelper/blob/e44405801ed92e945672a10b9e1b49f1ad472f26/AStyleHelper/AStyleHelper.cs#L29

If you use the &quot;inline temporary variable&quot; feature it will propose invalid output:

https://i.imgur.com/D2w3XV1.png

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/144318/inline-temporary-variable-creates-invalid-output.html
VSTS ticketId: 519940_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by dpoeschl** [comment] 2017-11-14 00:49
We could consider not offering to inline variables being initialized to a new object creation.

**Comment by CyrusNajmabadi** [comment] 2017-11-14 03:58
Couple of notes:

> If you use the "inline temporary variable" feature it will propose invalid output:

This output doesn't look invalid to me.  

> We could consider not offering to inline variables being initialized to a new object creation, 

I don't see why.  It may be precisely what someone wants.  In general 'inline variable' will always change semantics.  As long as the initialization does any computation, then you'll now do that computation multiple times.  Inline-var is also allowed when it causes the computation to happen after where it used to happen.

Inline-variable is very much *not* a feature that preserves semantics.  It's a feature that helps do something quickly.

**Comment by jinujoseph** [comment] 2018-01-06 00:22
another report
![image](https://user-images.githubusercontent.com/12449387/34633955-93655a06-f234-11e7-808d-a914fe482eb9.png)

from https://developercommunity.visualstudio.com/content/problem/173424/issue-with-quick-actions.html

**Comment by CyrusNajmabadi** [comment] 2018-01-06 02:00
Same rational as before.  Contructors, in particular, may be side effecting, and may be what the user wants.  This is equivalent to me deciding to select some code, extract it, and then say "but i didn't want it extracted" :)

If you don't want your 'contructor call' inlined... then don't ask to inline a variable initialized with a constructor call.  These options are to speed up a bunch of manual steps you might have to make.

**Comment by sharwell** [comment] 2019-09-26 23:08
Duplicate of #34131

**Closed by sharwell** 2019-09-26 23:08 UTC
Labels: Area-IDE, Developer Community
