### ISSUE TITLE
No warnings or errors are shown inside Visual Studio for rules in .editorconfig

### ISSUE THREAD

**Issue by ExplicitlyImplicit** [dotnet/roslyn#33689] opened 2019-02-26 09:05 UTC
**Version Used**: 

Visual Studio 2017 15.9.7

**Steps to Reproduce**:

1. Create a .net core console app (I'm using .net core 2.2)
2. Add an .editorconfig
3. Make some change that violate a rule that has :error or :warning

<img width="187" alt="vs_solution" src="https://user-images.githubusercontent.com/19637414/53400220-b167b500-39ad-11e9-87c3-f5b8b231e6d9.png">
<img width="452" alt="vs_editorconfig" src="https://user-images.githubusercontent.com/19637414/53400231-b4fb3c00-39ad-11e9-8f67-138903be400d.png">
<img width="521" alt="vs_program" src="https://user-images.githubusercontent.com/19637414/53400237-b6c4ff80-39ad-11e9-820f-7b6bcb8951fa.png">

**Expected Behavior**:
An error or a warning is shown inside the text editor view

**Actual Behavior**:
No change in the text editor view

**Notes**
I've tried reloading/restarting but that does not help.
Visual Studio automatically fixes the violation if I format the document.

**Comment by CyrusNajmabadi** [comment] 2019-02-26 10:02
csharp_preserve_single_line_statements is not an option that supports `:error`/`:warning`.  It's simply a true/false option that informs the formatter as to what the right formatting should be when it does its job.

**Comment by jinujoseph** [comment] 2019-02-27 18:45
Duplicate of #19055

**Closed by jinujoseph** 2019-02-27 18:45 UTC
