### ISSUE TITLE
Checkbox in "change signature" refactoring does nothing

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10584] opened 2016-04-14 19:33 UTC
There was no noticeable difference when selecting the checkbox, despite the fact that the method being refactored was invoked in the project.

![change-signature-checkbox](https://cloud.githubusercontent.com/assets/12466233/14541069/f46ce7e0-023c-11e6-87eb-82a52f42d376.png)

**Comment by dpoeschl** [comment] 2016-04-14 22:33
Dupe of https://github.com/dotnet/roslyn/issues/4608

**Closed by dpoeschl** 2016-04-14 22:33 UTC
Labels: Area-Compilers, New Language Feature - Tuples
