### ISSUE TITLE
C# multi-line comments are indented too much

### ISSUE THREAD

**Issue by tommai78101** [dotnet/roslyn#28946] opened 2018-07-30 20:40 UTC
**Version Used**: Visual Studio 2017 Professional 15.7.5
**Original report**: https://developercommunity.visualstudio.com/content/problem/301763/c-multi-line-comments-are-indented-too-much.html?childToView=302440#comment-302440

Moved to a new issue, suggested from here:
https://github.com/dotnet/roslyn/issues/28868#issuecomment-408974947

**Steps to Reproduce**:

1. Copy the following code:

```
public void Test {
	/* */
	void Start() {
	}
}
```

2.  Inside the `/* */`, press Enter key multiple times.
3.  Observe the subsequent lines after the first newline is indented by 1 extra indent.

**Expected Behavior**:

The `*/` should line up below `/*`.

```
public void Test {
	/*
	
	
	 */
	void Start() {
	}
}
```

**Actual Behavior**:

The `*/` is 1 indent more to the right, from `/*`.

```
public void Test {
	/*
	
	
		 */
	void Start() {
	}
}
```

**Comment by CyrusNajmabadi** [comment] 2018-07-30 20:45
tagging @heejaechang

**Comment by heejaechang** [comment] 2018-07-30 21:51
@tommai78101 thank you for reporting the bug. I will talk with @kuhlenh whether we want to indent 4 (then this is by design) or not ident body inside in multiple /* */ or we want to special case where user hit enter right before */

**Comment by tommai78101** [comment] 2020-05-14 21:19
@heejaechang @kuhlenh Hello, I know it's been a while. Are there any updates in regard to this issue?

**Comment by CyrusNajmabadi** [comment] 2020-05-14 21:36
I'm closing this out.  The above is invalid code.  `public void Test {` is either an invalid method (no parameters), or it's an invalid property (invalid return type, and invalid accessors).  

As such, there's no real clear thing to do here.  In my own testing, when i hit enter i get:

![image](https://user-images.githubusercontent.com/4564579/81988411-40331280-95f0-11ea-91bb-84cc06635f84.png)

Which is expected for me.  We're continuing the comment properly and placing the asterisk and caret in the right place, despite the invalid code around it.

**Closed by CyrusNajmabadi** 2020-05-14 21:36 UTC
Labels: Area-IDE, Bug, help wanted

**Comment by tommai78101** [comment] 2020-05-14 22:23
@CyrusNajmabadi 

That was my mistake for the copy/paste error.

This is the real result:

![](https://user-images.githubusercontent.com/6444116/43412661-edbab1d6-93fb-11e8-9f3c-539e4df0c1b7.gif)
