### ISSUE TITLE
remove and sort usings should not touch globalusings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72542] opened 2024-03-14 17:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/remove-and-sort-usings-should-not-touch-/10603771)._

---
When you run the  code cleanup action of _Remove unnecessary imports or usings_, it removes unused global usings from globalusings.cs.
This is common when you create a new project and bring in a standard global usings list.
It does not break the build, but it create an undesirable developer experience where i need to manually revert the changes to those files before committing.
It would be nice if the action did not remove the global usings, 
if desired removing unneeded global usings could be a seperate cleanup action, but I would think this use case would be less common, and may not be necessary.

---
#### Feedback Bot on 2/28/2024, 09:06 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2024-11-26 00:42
Closing out as by design.  the using are not used, and the user explicitly asked to remove the ones that are not used.

**Closed by CyrusNajmabadi** 2024-11-26 00:42 UTC
Labels: Area-IDE
