### ISSUE TITLE
Ctrl+. Fix all "Use expression body for methods" problems in document doesn't do anything

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23039] opened 2017-11-07 00:57 UTC
108-WinForms app with ASP.NET Web API backend

1. Clone https://github.com/cartermp/15.x-E2E

2. Add .editorconfig from https://gist.githubusercontent.com/kuhlenh/50fdabc40918255747c156cc1412f491/raw/5222b2fd781ada4f59d4132e085836a118764eff/.editorconfig

3. In ValuesController, put the cursor on Get(string word) definition's &quot;return&quot;

4. Ctrl+. &gt; Use expression body for methods &gt; Fix all Problems in Document

Expected: 3 fixes show up
Actual: No changes show up

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/143226/ctrl-fix-all-use-expression-body-for-methods-probl.html
VSTS ticketId: 518925_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2017-11-07 17:53
Almost certainly a duplicate of #19089 (the Fix All operation ignores .editorconfig, instead using whatever is in Tools &rarr; Options).

**Closed** 2017-11-07 20:30 UTC
Labels: Area-IDE, Resolution-Duplicate
