### ISSUE TITLE
'Add Overloads' Quick-Fix for BC40003 produces invalid code

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#21948] opened 2017-09-06 22:17 UTC
**Version Used**: VS2017 RTM

**Steps to Reproduce**:

1. Drop this in a new console app.

``` VB.NET
Class Base
    Sub M()

    End Sub
End Class

Class Derived
    Inherits Base

    Sub M() ' <--- Invoke the light bulb on this line.

    End Sub
End Class
```

2. Invoke the light bulb on the indicated line.

**Expected Behavior**:
Modifier is either added on same line as `Sub` keyword.

**Actual Behavior**:
Modifier is added to a new line before the `Sub` keyword, which produces parse errors:

![image](https://user-images.githubusercontent.com/10539978/30137040-6c8fb5de-9316-11e7-8c89-6eb42f91eaeb.png)

**Comment by 06needhamt** [comment] 2017-10-26 19:07
PR is Out! #22871

**Comment by 06needhamt** [comment] 2017-10-26 19:10
I am currently working on a fix for this along with #21946

**Comment by Youssef1313** [comment] 2021-03-07 06:58
@AlekseyTs Can you please take a look if this is the expected behavior from compiler API?

![image](https://user-images.githubusercontent.com/31348972/110231904-28cc6980-7f23-11eb-8e09-72a8dfffd7a3.png)

**Comment by AlekseyTs** [comment] 2021-03-08 00:40
> Can you please take a look if this is the expected behavior from compiler API?

What specific compiler API we are talking about and how exactly it is used? It looks like the proposed fix doesn't change behavior of any compiler API.

**Comment by Youssef1313** [comment] 2021-03-08 05:25
@AlekseyTs It is MethodStatementSyntax.Update
The method has a leading trivia and the update aaks for adding a modifier. The result is leading trivia being duplicated.

In the proposed fix, I removed the trivia before calling Update, then added it back, which feels like a workaround, but should probably be okay if the compiler API is expected to behave like that.

**Comment by AlekseyTs** [comment] 2021-03-08 05:52
> It is MethodStatementSyntax.Update

It is quite possible I am missing something, but I do not see this method to do anything special about the trivia. In order to avoid any confusion, I recommend creating small complete standalone repro to demonstrate the questionable behavior. A complete compiler unit-test would be preferred.

**Comment by Youssef1313** [comment] 2021-03-08 06:39
```vb
        <Fact, WorkItem(21948, "https://github.com/dotnet/roslyn/issues/21948")>
        Public Sub Test21948()
            Dim tree = SyntaxFactory.ParseSyntaxTree("
Class Base
    Sub M()
    End Sub
End Class

Class Derived
    Inherits Base
    ' Comment
    Sub M()
    End Sub
End Class
")
            Dim root = tree.GetRoot()
            Dim node = DirectCast(root.DescendantNodes().Where(Function(n) TypeOf n Is MethodStatementSyntax).Last(), MethodStatementSyntax)
            Dim newNode = node.AddModifiers(SyntaxFactory.Token(SyntaxKind.OverloadsKeyword))
            Dim newRoot = root.ReplaceNode(node, newNode)
            Assert.Same("
Class Base
    Sub M()
    End Sub
End Class

Class Derived
    Inherits Base
    ' Comment
    Overloads Sub M()
    End Sub
End Class
", newRoot.GetText().ToString())
        End Sub
```

The test isn't duplicating the trivia unfortunately, but at least produces incorrect code:

```
Expected:
Class Base
    Sub M()
    End Sub
End Class

Class Derived
    Inherits Base
    ' Comment
    Overloads Sub M()
    End Sub
End Class

Actual:
Class Base
    Sub M()
    End Sub
End Class

Class Derived
    Inherits Base
Overloads    ' Comment
    Sub M()
    End Sub
End Class
```

The duplication could be from the IDE-side.

**Comment by AlekseyTs** [comment] 2021-03-08 16:10
> Is this behavior in the test above is intended/by-design?

My understanding is that trivia is actually attached to tokens. I don't believe the basic syntax nodes building APIs are supposed to move trivia around from one token to another. The nodes are simply created from the provided building blocks and correctness of the resulting node from the grammar point of view is consumer's concern.

**Comment by Youssef1313** [comment] 2021-03-08 16:14
@Aleksey Great. Thanks for clarification. #51721 should handle this in the IDE-side.

**Closed** 2021-04-14 21:30 UTC
Labels: Area-IDE, Bug, Language-VB, help wanted
