### ISSUE TITLE
Ensure IOperation.Children never contains null

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#21849] opened 2017-08-31 17:02 UTC
We should do a sanity check on our implementations and make sure that we're never returning null elements for IOperation.Children.

**Comment by sharwell** [comment] 2017-09-03 15:42
:bulb: I'm really hoping to use cases like this and `ISymbol.Name` (#20493) to validate some of the work being done for nullable reference types.

**Comment by jinujoseph** [comment] 2017-09-29 21:15
dupe of https://github.com/dotnet/roslyn/issues/21196

**Closed by jinujoseph** 2017-09-29 21:15 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
