### ISSUE TITLE
C# "where T : enum"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36429] opened 2019-06-13 21:35 UTC
VSF_TYPE_MARKDOWNOver the years we keep finding ourselves using generics where one of the parms is invariably required to be an enum. Currently the best restriction which can be placed on the parm is &quot;where T : struct&quot;. So rather than imposing an enum restriction at compile time, the restriction gets deferred to runtime.

We actually do impose an explicit check at runtime (assuming we remember) up-front in constructors to signal the problem as early as possible with as minimum a testing sequence as possible. However even static constructors do not run until the class is actually used. The explicit check specifically for Type.IsEnum helps ensure the compiler's willingness to do implicit type conversions isn't masking a problem. 

This would be a nice stepping stone toward (in the future) introducing an Enum&lt;T&gt; class to &quot;modernize&quot; the use of the very ancient Enum class.  The class having extension methods would go a long way toward &quot;moderizing&quot; code that manipulates enums. Of course such a class &quot;could&quot; be introduced without &quot;where T : enum&quot; (we have such a class), but it might lead to backward compatibility concerns if it were to be converted to &quot;where T : enum&quot; after having been introduced as &quot;where T : struct&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/602871/c-where-t-enum.html
VSTS ticketId: 916592_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/12/2019, 02:24 AM (36 hours ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by tannergooding** [comment] 2019-06-13 21:38
C# has already added `where T : Enum` in 7.3

**Comment by sharwell** [comment] 2019-06-14 02:58
Duplicate of #262

**Closed by sharwell** 2019-06-14 02:58 UTC
