### ISSUE TITLE
Rename tuple members

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24768] opened 2018-02-11 07:46 UTC
allow to rename tuple names

    (int x, int y) s;

 - right click on `x`
 - select rename

you get this error "You can not rename this element."

Originally I wanted to rename tuple member name from inherited member. 

    public override (Foo foo, Bar bar) Current => ...

so renaming `foo` requires me to rename base thus rename every where else manually.

---

Either allow inherited tuple member to have different name, or give us option to easily rename tuple member names.

**Comment by jcouv** [comment] 2018-02-12 04:10
Thanks for reporting this. It's a known issue.
I'll go ahead and close as duplicate of https://github.com/dotnet/roslyn/issues/14115

**Closed by jcouv** 2018-02-12 04:10 UTC
