### ISSUE TITLE
Intellisense commits unselected entry after Backspace and Tab in snippets

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#34373] opened 2019-03-23 11:23 UTC
**Version Used**: VisualStudio.16.Preview/16.0.0-pre.4.3+28714.193

**Steps to Reproduce**:

Enable _Show completion list after a character is deleted_

1. Type `foreach` and press Tab twice to insert the snippet.
2. Tab into the `collection` variable and press Backspace to delete the whole word. At this point, the intellisense will appear with nothing preselected:
![image](https://user-images.githubusercontent.com/10546952/54865505-9d259680-4d66-11e9-95ad-584f5ad43d8c.png)

4. Press Tab.

**Expected Behavior**: Select the next field in the snippet, i.e. `var`. The same behavior when the intellisense is dismissed with Esc first and then Tab is pressed.

**Actual Behavior**: `#if` (or other last selected item) is inserted.

I have snippets where removing the whole entry is a valid input and this behavior breaks it. Regardless of that scenario, there is nothing selected in the intellisense so nothing should be inserted.

**Comment by sharwell** [comment] 2019-03-23 16:41
We should investigate the impact of the following on this:

1. What is the behavior in earlier versions of Visual Studio?
2. What impact does Suggestion Mode have on the scenario?
3. Does the improved design proposal also work to fix the user experience described in #20145?

**Comment by miloush** [comment] 2019-03-23 16:48
Ono this is duplicate of #24377. Feel free to close one of them.

**Comment by sharwell** [comment] 2019-03-23 17:06
I've done that before too (filed a duplicate of my own bug)!

**Comment by sharwell** [comment] 2019-03-23 17:06
Duplicate of #24377

**Closed by sharwell** 2019-03-23 17:06 UTC
Labels: Area-IDE, Need Design Review
