### ISSUE TITLE
Strange behavior when passing `null` for ReadOnlyMemory/ReadOnlySpan

### ISSUE THREAD

**Issue by sungam3r** [dotnet/roslyn#58160] opened 2021-12-07 17:59 UTC
**Version Used**: 

Version:   5.0.403
Commit:    bf9d168ac2

**Steps to Reproduce**:

```csharp
public readonly struct A { }

public static void Do1(ReadOnlyMemory<byte> bytes) => Console.WriteLine(bytes.ToString());

public static void Do2(ReadOnlySpan<byte> bytes) => Console.WriteLine(bytes.ToString());

public static void Do2(A a) => Console.WriteLine(a.ToString());

Do1(null); // compiles [why?]
Do2(null); // compiles [why?]
Do3(null); // failed - CS1503	Argument 1: cannot convert from '<null>' to 'A'	 [OK]
```

**Expected Behavior**:

Compilation error for `Do1`, `Do2`, `Do3` calls.

**Actual Behavior**:

Compilation error only for `Do3`.

https://dotnetfiddle.net/pIb1Rj

**Comment by sungam3r** [comment] 2021-12-07 18:01
Maybe this is because of implicit operators from array/segment ?

**Comment by svick** [comment] 2021-12-09 08:41
> Maybe this is because of implicit operators from array/segment ?

That's exactly it: `null` is treated as an array, which is then implicitly converted to ROM/ROS.

**Comment by sungam3r** [comment] 2021-12-09 16:07
Although I understand the logic of what is happening, but it looks strange.

**Comment by CyrusNajmabadi** [comment] 2021-12-09 17:14
Closing out as this is by design given the language and the explicit API design of the ROM/ROS apis.

**Closed by CyrusNajmabadi** 2021-12-09 17:14 UTC
Labels: Area-Compilers, untriaged
