### ISSUE TITLE
Go to Definition with decompiled sources is useless

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/roslyn#40151] opened 2019-12-05 01:53 UTC
**Version Used**: 
VS2019 16.3.10
.NET Core 3.0

**Steps to Reproduce**:

1. Enable  navigation to decompiled sources
![image](https://user-images.githubusercontent.com/2280140/70196724-c7d14700-175d-11ea-8845-9d49dc205eab.png)

2. Find a type you're interested in and "Go to Definition"
![image](https://user-images.githubusercontent.com/2280140/70196791-f0f1d780-175d-11ea-9345-19c69b40fd2a.png)

**Expected Behavior**:
Get the real code decompiled (even better, downloaded from source reference)!

**Actual Behavior**:
Get useless satellite assembly sources (with no implementation details)

Example:
```csharp
    //
    // Summary:
    //     Represents a specific JSON value within a System.Text.Json.JsonDocument.
    public readonly struct JsonElement
    {
        //
        // Summary:
        //     Represents an enumerator for the contents of a JSON array.
        public struct ArrayEnumerator : IEnumerable<JsonElement>, IEnumerable, IEnumerator<JsonElement>, IEnumerator, IDisposable
        {
            private object _dummy;

            private int _dummyPrimitive;

            //
            // Summary:
            //     Gets the element in the collection at the current position of the enumerator.
            //
            // Returns:
            //     The element in the collection at the current position of the enumerator.
            public JsonElement Current
            {
                get
                {
                    throw null;
                }
            }

            //
            // Summary:
            //     Gets the element in the collection at the current position of the enumerator.
            //
            // Returns:
            //     The element in the collection at the current position of the enumerator.
            object IEnumerator.Current
            {
                get
                {
                    throw null;
                }
            }

            //
            // Summary:
            //     Releases the resources used by this System.Text.Json.JsonElement.ArrayEnumerator
            //     instance.
            public void Dispose()
            {
            }

            //
            // Summary:
            //     Returns an enumerator that iterates through a collection.
            //
            // Returns:
            //     An enumerator that can be used to iterate through the array.
            public ArrayEnumerator GetEnumerator()
            {
                throw null;
            }

            //
            // Summary:
            //     Advances the enumerator to the next element of the collection.
            //
            // Returns:
            //     /// true if the enumerator was successfully advanced to the next element; false
            //     if the enumerator has passed the end of the collection.
            public bool MoveNext()
            {
                throw null;
            }

            //
            // Summary:
            //     Sets the enumerator to its initial position, which is before the first element
            //     in the collection.
            public void Reset()
            {
            }

            //
            // Summary:
            //     Returns an enumerator that iterates through a collection.
            //
            // Returns:
            //     An enumerator for an array of System.Text.Json.JsonElement that can be used to
            //     iterate through the collection.
            IEnumerator<JsonElement> IEnumerable<JsonElement>.GetEnumerator()
            {
                throw null;
            }

            //
            // Summary:
            //     Returns an enumerator that iterates through a collection.
            //
            // Returns:
            //     An enumerator that can be used to iterate through the collection.
            IEnumerator IEnumerable.GetEnumerator()
            {
                throw null;
            }
        }
```

**Comment by davidroth** [comment] 2019-12-05 22:07
It seems to depend on the type though. Sometimes  it works. However, the quality of the decompilation is often very bad then.

This whole feature feels half-baked. Especially when comparing with the rider decompilation which is far far ahead and terms of reliability and quality.

**Comment by jinujoseph** [comment] 2019-12-10 20:56
related to #24349

**Comment by sharwell** [comment] 2020-05-12 20:09
@oliverjanik I'm marking this as a duplicate of #24349 (general request to improve the navigation experience for metadata). However, if you encounter _specific_ cases where decompilation is broken in the 16.6 release or newer (we've made improvements over time, with some big improvements landing in 16.6), please feel free to open new issues so we can find and fix them.

**Comment by sharwell** [comment] 2020-05-12 20:09
Duplicate of #24349

**Closed by sharwell** 2020-05-12 20:09 UTC
Labels: Area-IDE, Concept-Continuous Improvement
