### ISSUE TITLE
Unlike interfaces, "Go To Implemention" on an abstract base class doesn't go direct to implementation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25304] opened 2018-03-07 06:11 UTC
_From @davkean on March 7, 2018 5:26_

1. Right-click on IBase and choose **Go To Implementation**

-- Notice that you go straight to the only implementation; `Derived`

2. Right-click on Base and choose **Go To Implementation**

``` C#

    abstract class Base
    {

    }

    interface IBase
    {

    }

    abstract class Derived : Base, IBase
    {

    }
```

**Expected:** To go straight to the only implementation; `Derived`
**Actual:**

Find Results window opens with two results:

```
Code	File	Line	Column	Project
abstract class Derived : Base	c:\users\davkean\Source\Repos\ConsoleApp192\ConsoleApp192\Program.cs	29	20	ConsoleApp192
abstract class Base	c:\users\davkean\Source\Repos\ConsoleApp192\ConsoleApp192\Program.cs	24	20	ConsoleApp192
```

_Copied from original issue: dotnet/project-system#3355_

**Comment by sharwell** [comment] 2018-03-07 11:33
:memo: The Ctrl+Click operation is **Go To Definition**. We don't currently have a mouse gesture for **Go To Implementation**.

Duplicate of #24856.

**Closed by sharwell** 2018-03-07 11:33 UTC

**Comment by sharwell** [comment] 2018-03-07 11:34
Duplicate of #24856.

**Comment by davkean** [comment] 2020-07-22 05:07
@sharwell Why is this bug duplicated against adding a short-cut for Go To Implementation? They are two different things;
