### ISSUE TITLE
Building 5.0 projects with 6.0-preview SDK results in warnings when EnforceCodeStyleInBuild=true

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#54867] opened 2021-07-12 20:38 UTC
SDK: v6.0.100-preview.6.21355.2
VS: 16.11-p2

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
```

Opening the project in VS produces many warnings such as this:

```
1>CSC : warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```

**Comment by jmarolf** [comment] 2022-03-18 21:24
closing as duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5458

**Closed by jmarolf** 2022-03-18 21:24 UTC
Labels: Bug, Area-Infrastructure
