### ISSUE TITLE
First-chance NativeIntegerTypeDecoder+ErrorTypeException in semantic classifier/binder

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#49823] opened 2020-12-06 22:50 UTC
**Version Used**: 
16.8.2 (regression since 16.7.3 where it didn't repro)

**Steps to Reproduce**:

1. Open a large C# file in VS under debugger with first-chance exceptions on

**Expected Behavior**:
No exceptions

**Actual Behavior**:
```
Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder+ErrorTypeException: Exception of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder+ErrorTypeException' was thrown.
   at TypeSymbol Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder.TransformType(TypeSymbol type) in /_/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/NativeIntegerTypeDecoder.cs:line 91
   at TypeSymbol Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder.TransformType(TypeSymbol type, ImmutableArray<bool> transformFlags) in /_/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/NativeIntegerTypeDecoder.cs:line 31
   at TypeSymbol Microsoft.CodeAnalysis.CSharp.Symbols.CustomModifierUtils.CopyTypeCustomModifiers(TypeSymbol sourceType, TypeSymbol destinationType, AssemblySymbol containingAssembly) in /_/src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs:line 81
   at void Microsoft.CodeAnalysis.CSharp.Symbols.CustomModifierUtils.CopyMethodCustomModifiers(MethodSymbol sourceMethod, MethodSymbol destinationMethod, out TypeWithAnnotations returnType, out ImmutableArray<CustomModifier> customModifiers, out ImmutableArray<ParameterSymbol> parameters, bool alsoCopyParamsModifier) in /_/src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs:line 57
   at void Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbolBase.MethodChecks(DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs:line 171
   at void Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.LazyMethodChecks() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs:line 318
   at ImmutableArray<ParameterSymbol> Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbolBase.get_Parameters() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs:line 336
   at void Microsoft.CodeAnalysis.CSharp.InMethodBinder.LookupSymbolsInSingleBinder(LookupResult result, string name, int arity, ConsList<TypeSymbol> basesBeingResolved, LookupOptions options, Binder originalBinder, bool diagnose, ref HashSet<DiagnosticInfo> useSiteDiagnostics) in /_/src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs:line 206
   at Binder Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsInternal(LookupResult result, string name, int arity, ConsList<TypeSymbol> basesBeingResolved, LookupOptions options, bool diagnose, ref HashSet<DiagnosticInfo> useSiteDiagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:line 97
   at Binder Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsWithFallback(LookupResult result, string name, int arity, ref HashSet<DiagnosticInfo> useSiteDiagnostics, ConsList<TypeSymbol> basesBeingResolved, LookupOptions options) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs:line 63
   at BoundExpression Microsoft.CodeAnalysis.CSharp.Binder.BindIdentifier(SimpleNameSyntax node, bool invoked, bool indexed, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 1423
   at BoundExpression Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, bool invoked, bool indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 553
   at BoundExpression Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, bool invoked, bool indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 481
   at BoundStatement Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 2692
   at BoundStatement Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 99
   at BoundStatement Microsoft.CodeAnalysis.CSharp.MemberSemanticModel+IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:line 2414
   at BoundNode Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:line 2367
   at BoundNode Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs:line 107
   at ImmutableArray<BoundNode> Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:line 2103
   at BoundNode Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:line 540
   at void Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, out CSharpSyntaxNode bindableNode, out BoundNode lowestBoundNode, out BoundNode highestBoundNode, out BoundNode boundParent) in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:line 1340
   at SymbolInfo Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:line 1221
   at SymbolInfo Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:line 216
   at SymbolInfo Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:line 572
   at SymbolInfo Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/CSharpExtensions.cs:line 503
   at void Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken) in /_/src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:line 60
   at void Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxNode syntax, SemanticModel semanticModel, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken) in /_/src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:line 35
   at void Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.ClassifyNode(SyntaxNode syntax) in /_/src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassificationService.Worker.cs:line 134
   at void Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.ProcessNodes()
   at void Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder<ClassifiedSpan> list, Func<SyntaxNode, ImmutableArray<ISyntaxClassifier>> getNodeClassifiers, Func<SyntaxToken, ImmutableArray<ISyntaxClassifier>> getTokenClassifiers, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassificationService.Worker.cs:line 69
   at async Task Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, Func<SyntaxNode, ImmutableArray<ISyntaxClassifier>> getNodeClassifiers, Func<SyntaxToken, ImmutableArray<ISyntaxClassifier>> getTokenClassifiers, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassificationService.cs:line 41
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, Func<SyntaxNode, ImmutableArray<ISyntaxClassifier>> getNodeClassifiers, Func<SyntaxToken, ImmutableArray<ISyntaxClassifier>> getTokenClassifiers, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsInCurrentProcessAsync(Document document, TextSpan textSpan, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Classification/AbstractClassificationService.cs:line 88
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsInCurrentProcessAsync(Document document, TextSpan textSpan, ArrayBuilder<ClassifiedSpan> result, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, List<ClassifiedSpan> result, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Classification/AbstractClassificationService.cs:line 52
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, List<ClassifiedSpan> result, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, IClassificationService classificationService, List<ClassifiedSpan> classifiedSpans, CancellationToken cancellationToken) in /_/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs:line 200
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, IClassificationService classificationService, List<ClassifiedSpan> classifiedSpans, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ClassifySpansAsync(TaggerContext<IClassificationTag> context, DocumentSnapshotSpan spanToTag, IClassificationService classificationService, ClassificationTypeMap typeMap) in /_/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs:line 150
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ClassifySpansAsync(TaggerContext<IClassificationTag> context, DocumentSnapshotSpan spanToTag, IClassificationService classificationService, ClassificationTypeMap typeMap)
   at async Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ProduceTagsAsync(TaggerContext<IClassificationTag> context, DocumentSnapshotSpan spanToTag, IClassificationService classificationService, ClassificationTypeMap typeMap) in /_/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs:line 53
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ProduceTagsAsync(TaggerContext<IClassificationTag> context, DocumentSnapshotSpan spanToTag, IClassificationService classificationService, ClassificationTypeMap typeMap)
   at Task Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationViewTaggerProvider.ProduceTagsAsync(TaggerContext<IClassificationTag> context) in /_/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationViewTaggerProvider.cs:line 104
   at async Task Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<TTag>+TagSource.RecomputeTagsAsync(object oldState, SnapshotPoint? caretPosition, TextChangeRange? textChangeRange, ImmutableArray<DocumentSnapshotSpan> spansToTag, ImmutableDictionary<ITextBuffer, TagSpanIntervalTree<TTag>> oldTagTrees, bool initialTags, CancellationToken cancellationToken) in /_/src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:line 459
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<TTag>+TagSource.RecomputeTagsAsync(object oldState, SnapshotPoint? caretPosition, TextChangeRange? textChangeRange, ImmutableArray<DocumentSnapshotSpan> spansToTag, ImmutableDictionary<ITextBuffer, TagSpanIntervalTree<TTag>> oldTagTrees, bool initialTags, CancellationToken cancellationToken)
   at void Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<TTag>+TagSource.RecomputeTagsForeground(bool initialTags)+(CancellationToken ct) => { } in /_/src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:line 308
   at void Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue.EnqueueBackgroundTask(Func<CancellationToken, Task> taskGeneratingFunctionAsync, string name, int afterDelay, CancellationToken cancellationToken)+(Task _) => { } [0] in /_/src/EditorFeatures/Core/Shared/Threading/AsynchronousSerialWorkQueue.cs:line 131
   at void System.Threading.Tasks.ContinuationResultTaskFromTask<TResult>.InnerInvoke()
   at void System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch()
   at bool System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by KirillOsenkov** [comment] 2020-12-07 21:57
One file that would exhibit this for example is ActiveConfigurationGroupDataSourceBase.cs (available on http://index).

The code it was trying to classify is the `latestData` token on this property declaration:

```
public IProjectVersionedValue<IReadOnlyCollection<T>>? Current => this.latestData;
```

**Comment by nschuessler** [comment] 2021-03-29 14:01
@KirillOsenkov 
Has this been root caused? I am not hitting this :(
What is the net effect, it abandons analysis of the method?

**Comment by KirillOsenkov** [comment] 2021-03-29 15:44
I don't know, I don't have any updates after logging this issue. Waiting on a dev to investigate.

**Comment by AlekseyTs** [comment] 2021-09-01 15:31
As far as I can see, the exception is caught by the the method on the stack.

**Comment by nschuessler** [comment] 2021-09-01 16:04
@AlekseyTs  Is closing the issue because it is caught on the stack investigating the issue?  Shouldn't it be understood before deciding whether to fix or not?  

```csharp
public IProjectVersionedValue<IReadOnlyCollection<T>>? Current => this.latestData;
```

This was a test case found by @KirillOsenkov

**Comment by AlekseyTs** [comment] 2021-09-01 17:03
@nschuessler 

> Is closing the issue because it is caught on the stack investigating the issue? Shouldn't it be understood before deciding whether to fix or not?

The exception is compiler's internal exception. Throwing and catching it in some scenarios is by design. I believe the exception never escapes compiler's code. The issue complains about the fact that the exception is thrown. I see nothing wrong in that.

**Comment by sharwell** [comment] 2021-09-10 21:18
Reopening this issue. 68% of the exceptions thrown while opening Roslyn.sln are this exception (33,626 exceptions). The current pattern forces a severe productivity impairment attempting to debug Visual Studio with Roslyn.sln. The Snappy Jr work is tracking fixes for first chance exceptions occurring just dozens of times to improve the IDE load experience.

**Comment by AlekseyTs** [comment] 2021-09-10 21:45
Assigning to @jaredpar to re-triage.

**Comment by nschuessler** [comment] 2021-09-13 12:03
@sharwell When you say productivity imparement, what is it you are seeing? In my app via the API yes the exception doesn't leak, but they compilation never completes (it appears).  i.e.:

```csharp
compilationWithAnalyzers.GetAnalyzerDiagnostics(cancellationToken);
```

hangs overnight (12 hours+)

**Comment by sharwell** [comment] 2021-09-13 15:45
> When you say productivity imparement, what is it you are seeing?

The debugging effort took 20 minutes instead of 3-5 minutes.

**Closed** 2021-09-14 02:55 UTC
Labels: Bug, Area-Compilers, Urgency-Soon, New Language Feature - Native Int
