### ISSUE TITLE
Pattern-matching NRE when variable is captured in lambdas

### ISSUE THREAD

**Issue by YaakovDavis** [dotnet/roslyn#16537] opened 2017-01-16 19:37 UTC
In 2017 RC (26020), a NullReferenceException is thrown when entering pattern-matching cases containing lambdas that capture the introduced variable. 
In the example bellow, an NRE is thrown when entering the `switch` statement. 

A similar issue occurs when falling through cases, where the case we're falling into contains a lambda referring the introduced variable.

Examining the generated code, it appears that a closure instance is referred to without initialization.

```
    class C { public int A; }

    class Program
    {
        static void Main(string[] args)
        {
            switch (new C())
            {
                case C c:
                    Func<bool> f = () => c.A > 10;
                    break;
                default:
                    break;
            }
        }
    }
```

**Comment by svick** [comment] 2017-01-16 21:42
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/16066.

**Comment by YaakovDavis** [comment] 2017-01-16 22:17
It does seem a duplicate indeed.

**Comment by YaakovDavis** [comment] 2017-01-16 22:22
See a [workaround ](https://github.com/dotnet/roslyn/issues/16066#issuecomment-272975076)I posted there.

**Closed** 2017-01-16 22:32 UTC
