### ISSUE TITLE
Visual Studio 2015 C# code format issue

### ISSUE THREAD

**Issue by JoeBug** [dotnet/roslyn#8224] opened 2016-01-28 12:51 UTC
In VS 2015 options under Text Editor > C# > Tabs I set Indenting to Smart and checked option Keep tabs.

Now if I auto-format code, everything is formated as expected.
But the space before a comment is changed to spaces if there were tabs:

[Screenshot](http://i.stack.imgur.com/zM0wx.png)

In previous versions of Visual Studio, tabs stays on auto code formatting.
There seems to be no option to change that behavior.

This is not an issue of beautification - this is an issue because auto-formated files are now marked as different with our tool chain.

**Comment by Pilchie** [comment] 2016-01-28 17:37
You've already looked at some reports of issues like this.  Can you take a look and see if this one is fixed?

**Comment by CyrusNajmabadi** [comment] 2016-01-28 19:30
@JoeBug Can you please provide a repro file (ideally as small as possible) that demonstrates the problem?

**Comment by lorcanmooney** [comment] 2016-01-28 22:13
Duplicate of #5873. The last comment from @CyrusNajmabadi in that thread suggests this was an intentional change.

**Comment by JoeBug** [comment] 2016-01-29 05:52
Yes, issue [#5873](https://github.com/dotnet/roslyn/issues/5873) is the same.
Is it possible to introduce a option in Tools>Options>Text Editor> * >Formatting>Spacing?

**Comment by JoeBug** [comment] 2016-01-29 06:09
@CyrusNajmabadi: You can reproduce this in every file that has a comment on the same line - just insert tabs before the comment:

`using System;			// blah`

**Comment by CyrusNajmabadi** [comment] 2016-01-29 18:02
I believe this is by design.  tabs vs spaces is only about controlling your indentation of code.  It's not about preserving tabs anywhere they might exist in code.  For example, if you have:

```if<tab>(```, then we will convert that to ```if (``` all the time.

I don't believe we'd want to have rules to cover all the cases.  Perhaps it might be sufficient to have a rule that says "if there is a tab used as whitespace, and it isn't at the start of a line, and the user has 'tabs' enabled. then attempt to preserve it."

**Comment by FlorianHaupt** [comment] 2016-03-30 11:28
I do not see how this could be by design, the behaviour now is nuisance as it creates unneccessary extra work. There is a bunch of options for spacing and all of them describe a concrete case where they should end in an automatic conversion of the code line. I have checked all of these options mentioned in Visual Studio 2015 and none of them match the case that was already described by JoeBug. The conversion you described can be found in the spacing options, so I think it is ok in that case to change the tabs to spaces if it was selected - even so I do not think this spacing options have anything to do with the tabs replaced by spaces behaviour because it is also triggered if whitespace is completly missing.
If none of the spacing options matches the "keep tabs" option should be respected, everything else is mysterious behaviour.
I like to add that we do not have this autoformat issue with VS 2012.

**Comment by CyrusNajmabadi** [comment] 2016-03-31 00:11
> I do not see how this could be by design, the behaviour now is nuisance as it creates unneccessary extra work.

Something can be 'by design' and still be a nuisance :)

I'm considering ways this could be addressed. It's non-trivial though given how the current formatting engine works.  Note that a design here that pleases all users is going to be tricky to provide.  For example, if we look at the examples that JoeBug provided he mentioned there were cases where he *would* want tabs between tokens to be changed into spaces (even if he had 'use tabs' set), and there were places where he would want tabs to be preserved.  

This means if we try to do this with some sort of simple rule, then we'd switch the behavior to be better for half of JoeBug's cases, and we'd make things worse for half of the cases.  The alternative is to provide lots of knobs to customize where you do or don't want this sort of preservation logic.

Now, maybe we just go with a rule and we accept that some things may degrade for JoeBug's case.  However, as we've seen with the history of formatting here, when you make changes that degrade some functionality, that is usually irksome for some people.  It would be unfortunate if we changed behavior again to make some people happy, and we ended up making more people unhappy.  I'd far prefer some sort of solution that can keep existing cases working well while improving cases that aren't working well.

**Comment by CyrusNajmabadi** [comment] 2016-03-31 00:29
Interestingly enough, we added some support to align comments over multiple lines.  So, for example, in the example being mentioned, post format you end up with:

![image](https://cloud.githubusercontent.com/assets/4564579/14161958/90494656-f69c-11e5-8ac2-73ac7b96ff3a.png)

Alignment is an interesting problem, and currently we have no support for alignment to happen with tabs *when formatting between tokens*.   However, it gets more and more complex considering you might have these comments attached to items which themselves get moved around by formatting and thus may have their locations move to places that are not on tabstop boundaries.

 I'm noodling around some ideas where we could potentially make this work, but it's causing my brain to hurt a bit trying to think about all the permutations and complex scenarios we might run into here :)

**Comment by FlorianHaupt** [comment] 2016-04-05 08:56
I do not know what kind of breaking design changes were be done and for what reason. The spacing options were already there with the VS 2012 version and we did not run into any auto formatting issues with them.
What we were running into is this one (While using VS 2015):
`<tab><tab>variable;<tab>// Comment
trigger one of the autoformats by typing ";" or "}" in the next line or otherwise use format whole document and the line will be changed to:
<tab><tab>variable;<space><space><space><space> // Comment`
There is nothing special with this line, so: What is it that causes the autoformat? For me as user this is completly mysterious and on top I have no chance to avoid this.
I expect to "Only format on selected autoformat option", as they were mentioned and shown in example in the spacing section.
It should be solveable, as it was already working in previous versions.

**Comment by JoeBug** [comment] 2016-04-05 09:08
> For me as user this is completly mysterious and on top I have no chance to avoid this.
That's why I struggle with it.

Because auto-format changes all existing tabs with spaces, a LOT of lines marked as different when comparing source files with previous ones.

**Comment by CyrusNajmabadi** [comment] 2016-04-05 18:29
> It should be solveable, as it was already working in previous versions.

As mentioned before, this is an entirely new formatting engine that works in a very different manner, and which has additional functionality which works at odds with what you're asking for.  I'm trying to find a solution that can make the cases you want work without regressing cases that other people care about.

As noted already there are people in this thread that want a myriad of different behaviors.  For example, preservation of tabs in certain contexts, but also removal of tabs in other contexts.  I haven't even gotten around to codification of any rules because i'm still trying to figure out what the rules should be that can give everyone what they want.  Note: i also haven't figured out if there's even a way to provide default rules that work for everyone.  It may be necessary to add options around this space to allow for all the configurations people are asking for.  However, i want to avoid options until i determine that they're completely and totally necessary.

> There is nothing special with this line

What is special (from the perspective of the formatting engine) is that you have tabs used for non-indentation purposes.  That wasn't something the current engine was designed to deal with.   Instead, hte new engine follows the principle espoused in many different locations that tabs should only be used for indentation and spaces should be used for alignment.

Now, since moving to that model, it's clear that that's something that's making some people very unhappy.  So i'm working at some sort of solution that can perhaps allow for some sort of alignment through tabs as well.  It gets much trickier though now that our engine has the concepts of things like anchoring and all sorts of operations could change the alignment.

**Comment by CyrusNajmabadi** [comment] 2016-04-05 18:32
Question for those having an issue here.  Would you prefer an option that turns off formatting altogether?  That way we would never muck with spaces used for alignment purposes and whatnot.  You would then be in total control of how things get formatted.

Or would you prefer to still use the formatting engine, but now have rules that control how tabs are treated in different contexts?  I don't think we can have a general tab rule as some people have asked for tabs to get replaced with spaces, while some want tabs to be preserved (in some form).   Also, if tabs are preserved, how shoudl that interact with alignment/anchoring.  i.e. say the code being moved is anchored to something else.  That thing it is anchored to moves in some way.  Now, if we were to keep tabs then the items might move around oddly (and may become unaligned).  Is that ok?  Can we insert spaces along with the tabs to keep alignment?  Is a mix of tabs/spaces ok?  Or do you want it to always be all tabs?

**Comment by JoeBug** [comment] 2016-04-06 06:46
@CyrusNajmabadi: Thanks for your reply!
Sure I would prefer to use the formatting engine - great stuff!

I thought about the real reason for this discussion (from my point of view) and came to this conclusion:
If multiple source code lines contains comments (like the example I gave), the comments should be aligned vertically, so the code is easier to read:

![comments](https://cloud.githubusercontent.com/assets/16937933/14307979/4250fb4c-fbd3-11e5-8952-5b48b0db4a9a.png)

Changing the code part will move the comments, so it would be good if this could be done by the formatting engine. If so, then it is of no matter if the spacing is done with tabs or with spaces.
Is that possible?

**Comment by FlorianHaupt** [comment] 2016-04-06 07:59
> As mentioned before, this is an entirely new formatting engine that works in a very different manner, and which has additional functionality which works at odds with what you're asking for. I'm trying to
find a solution that can make the cases you want work without regressing cases that other people care about.

Thanks.
>Would you prefer an option that turns off formatting altogether?

If the formatting engine does what is reflected by the options it is really nice to have it because it adds an easy way to format the whole document. Most of the time I do not trigger any of the rules there, so it would be better to deactivate than having to retype something that was unnecessarily autoformatted.
It fears me a little bit to read that there are more autoformat rules that were not reflected by any options.
>new engine follows the principle espoused in many different locations that tabs should only be used for indentation and spaces should be used for alignment.

I've read some of these discussions, but always think it is something that the user should decide. Thanks for mentioning it, as I could now understand why this is done by the new engine.
>Now, if we were to keep tabs then the items might move around oddly (and may become unaligned). Is that ok? Can we insert spaces along with the tabs to keep alignment? Is a mix of tabs/spaces ok? Or do you want it to always be all tabs?

If I select "keep tabs" I do not expect that this is for indention reasons only, my expectation is to keep all tabs. I can accept that the autoformat does only care on changing indention tabs to spaces if the "keep tabs" option was unselected. On the other hand I can accept that alignment spaces were not replaced by tabs if the "keep tabs" option is activated and an autoformat is triggered.
Whatever this autoformat engine does, it should be transparent to the user and even better be selectable by the user (if it is not selectable I really vote for an option to deactivate the whole thing). If it helps in any way change "keep tabs" to "keep indention tabs" and "keep alignment tabs".
>...some people have asked for tabs to get replaced with spaces...

As far as what I've read this cases were only those that are matched by spacing options and I can agree with it, because the spacing autoformats (options mentioned in the spacing section) should not care about any whitespace around the matching case, it should not matter if there were tabs, spaces or whatever.

**Comment by CyrusNajmabadi** [comment] 2016-04-06 16:18
> It fears me a little bit to read that there are more autoformat rules that were not reflected by any options.

There have always been *tons* of formatting rules not reflected by any options.  That's because, otherwise, we'd need an option to reflect how any piece of whitespace might be changed between any two tokens.  That literally would end up with over 10k rules :)

So a lot of the rules operate implicitly.  For example, if you write ```new [] {1,2,3}``` then you're going to always end up with ```new[] { 1, 2, 3 }``` after formatting.  As far as i can tell, we don't provide any ability to customize most of that.  For example, if you don't want spaces around the curlies, then that's not something you can control.  (Note: i haven't actually verified.  So for this exact example i may be incorrect.  I'm just talking about in general how we've essentially codified the behavior of many thousand relationships in a way that can't be configured).  

Note that this has always essentially been the case.  Our formatter, at *no* point, provided a way to configure every bit of behavior it had.

--

> If I select "keep tabs" I do not expect that this is for indention reasons only, my expectation is to keep all tabs

Right, but the "keep tabs" is in this "Indenting" section:

![image](https://cloud.githubusercontent.com/assets/4564579/14323956/b421cdec-fbd7-11e5-901a-a6099a9c3565.png)

Also, as mentioned before, other people *in this conversation* have mentioned that even if htey had "keep tabs" on, there are still places they would expect tabs to be replaced with spaces.  That's why this is difficult.  If we switch to always preserve tabs, then that will break behavior that some people like and depend on.  

So, at this point, i only think we can get the behavior you want through the use of new options.  I'm just trying to think what those options should be.  I'm going to try prototyping a "keep tabs around comments" options to see what sort of behavior we now get.

> As far as what I've read this cases were only those that are matched by spacing options and I can agree with it

Having conflicting options is something that worries me :)

**Comment by atykhyy** [comment] 2016-09-21 09:50
> Question for those having an issue here. Would you prefer an option that turns off formatting altogether?

Yes, please! Auto-formatting works fine for many people, but there is a large minority for whom it's _incredibly_ frustrating. A simple option to turn off formatting completely would be a godsend. I for one would much prefer having to type the few extra keystrokes needed to format my code, which I do without thinking, to rather more keystrokes and a mental hiccup needed to undo the auto-formatting. Also, the new smart indent seems to be too smart by half: e.g. if I type

    using (var stream = new FileStream (...))
    using (var writer  = new BinaryWriter (stream, ...))

smart indent insists on indenting the next `{` instead of leaving it aligned with the `using`s, and even if I persuade it to honor my indentation later code changes are apt to re-induce the "correct" indentation.

**Comment by craigs100** [comment] 2016-09-28 13:54
Thank goodness I found this thread. VS2015 has been driving me nuts since first installed. I work mainly with web sites so html, C#, js, css, sass and Razor. I work with my own files, old files and other peoples files in many projects. I've tried desperately to switch off all auto-formatting because I'm expending more keystrokes fixing formatting issues than writing actual code. I'd rather just tab and space my indents if VS can't do it properly. Particularly where I paste code into a page and find everything is now left aligned. In that particular case I've found if I ctrl+z then the formatting is removed but the pasted code remains. I can then  indent the whole block as it should be. Just opening a brace can cause issues where more keystrokes have to be made to put the closing brace where it should be. Can't seem to stop it auto-closing those in css files.

Either very clear instructions are needed as to how to set up auto-formatting, including pastes and the options actual effects described, or a facility to switch it ALL off.

Many thanks for listening.

**Closed** 2016-10-17 21:31 UTC
Labels: Area-IDE, Bug
