### ISSUE TITLE
Warning/errors/messages are not correctly grouped for multi-targeting projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#32055] opened 2018-12-29 09:07 UTC
**Version Used**: 
Version 16.0.0 Preview 2.0 [28420.135.d16.0stg]

**Steps to Reproduce**:

1. Create a new Console App (.NET Core)
2. Change project to:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.0;net45;net46</TargetFrameworks>
  </PropertyGroup>

</Project>

```

3. Reload project
4. Wait for background analysis to be finished

**Expected Behavior**:
Single message with:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'args'	ConsoleApp338(net45), ConsoleApp338(net46), ConsoleApp(netcoreapp3.0)	C:\Users\davkean\Source\Repos\ConsoleApp338\ConsoleApp338\Program.cs	7	Style	Active
```

**Actual Behavior**:
Two messages:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'args'	ConsoleApp338(net45), ConsoleApp338(net46)	C:\Users\davkean\Source\Repos\ConsoleApp338\ConsoleApp338\Program.cs	7	Style	Active
Message	IDE0060	Remove unused parameter 'args'	ConsoleApp338(netcoreapp3.0)	C:\Users\davkean\Source\Repos\ConsoleApp338\ConsoleApp338\Program.cs	7	Style	Active

```

tag @mavasani @heejaechang

**Comment by mavasani** [comment] 2019-01-14 14:55
So after playing around with this further, it seems something is really broken with multi-targeting projects, but _only_ during the time when user is editing the csproj.

The above given repro steps causes the multiple diagnostics issue to show up sometimes, but not always. Additionally, editing the csproj to remove and then re-add any of the target frameworks causes the diagnostic for that framework to go away from the error list and never re-appear. See the below gif:

![multitfm](https://user-images.githubusercontent.com/10605811/51119725-724c1e80-17c8-11e9-8d4f-577536e941e4.gif)

If I re-add the new target frameworks one at a time, I see an additional duplicate diagnostic show up for every added target framework, see the below gif:

![multitfm_2](https://user-images.githubusercontent.com/10605811/51119818-a9bacb00-17c8-11e9-8923-2e2eede7f187.gif)


For all the above cases, unloading and reloading the project OR closing and reopening the solution _always_ fixes the issue and we end up a single correct de-duplicated diagnostic which lists all the target frameworks.

**Comment by mavasani** [comment] 2019-01-14 14:58
Also confirmed that the issue is not specific to any analyzer, it repros even with compiler diagnostics.

**Comment by mavasani** [comment] 2019-01-14 14:59
@sharwell - any reason this has been marked as Needs design review?

**Comment by davkean** [comment] 2019-01-16 00:50
> Also confirmed that the issue is not specific to any analyzer, it repros even with compiler diagnostics.

What is the repro for this? Make sure this isn't build-time because that would likely be: https://github.com/dotnet/project-system/issues/2811.

**Comment by mavasani** [comment] 2019-01-16 00:57
> What is the repro for this?

Just have a simple method with an unused local, which generates a CS diagnostic.

**Comment by mavasani** [comment] 2019-01-16 00:57
> Make sure this isn't build-time

Yep, I never did a build.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:25
Not repro:

![Image](https://github.com/user-attachments/assets/2d326de3-2308-4c75-b436-1b005c47d096)

**Closed by CyrusNajmabadi** 2024-11-06 02:25 UTC
Labels: Bug, Area-IDE
