### ISSUE TITLE
Go To Implementation can't find implementation of IActiveStatementTrackingService

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43469] opened 2020-04-18 00:38 UTC
**Version Used**: 

Version 16.7.0 Preview 1.0 [30016.20.master]

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Open src\Features\Core\Portable\EditAndContinue\IActiveStatementTrackingService.cs
3. Invoke Go To Implementation on IActiveStatementTrackingService

**Expected Behavior**:

Finds 2 implementations:
src\EditorFeatures\TestUtilities\EditAndContinue\TestActiveStatementTrackingService.cs
src\EditorFeatures\Core\Implementation\EditAndContinue\ActiveStatementTrackingService.cs

**Actual Behavior**:

Finds no implementation.

**Comment by CyrusNajmabadi** [comment] 2020-04-18 02:37
Dupe of https://github.com/dotnet/roslyn/issues/43093.  You find the items if you're in 2.0:

![image](https://user-images.githubusercontent.com/4564579/79626168-df90e280-80e2-11ea-9c3f-84a65cda2b3b.png)

**Closed by CyrusNajmabadi** 2020-04-18 02:37 UTC
Labels: Area-IDE
