### ISSUE TITLE
Error, C# compiler exit with code -1, error MSB6006

### ISSUE THREAD

**Issue by vaualbus** [dotnet/roslyn#3476] opened 2015-06-12 19:45 UTC
So I run into a very strange error on a project I'm doing.
Basicly one line code that seem compltly right make the c sharp compiler to crash with error -1.
With the error be on C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(384,9): error MSB6006 this file.
If anyone wanna try the issue please see my github page and download the code, the error happen if line 111 is there for apparently no reason.
the github repository is here: https://github.com/vaualbus/Zelda-Game-Engine, the brach is ChangeScriptEngineInterfaces and rember to run the prepare.bat that basicly download the packages.
It is a script engine and a  very little fun game.
Please help me!

**Comment by biqas** [comment] 2015-06-13 19:59
Hi maybe this #3487 will help you?

**Comment by vaualbus** [comment] 2015-06-14 23:46
Nope Microsoft.CSharp is present,  also I have done a compltly new install of windows and vs and the error remain. So please somebody help me!

**Comment by vaualbus** [comment] 2015-06-15 08:15
I figured out that If you change the line that cause the error to var script2 = ScriptRepository.Scripts[scriptDataFormAttribute.Value.ScriptName]; 
instead of calling TryGetScriptGameObject function inside the ScriptRepository class, now it compile.
I really cannot get what the problem could be.
Thanks for the help.

**Comment by jaredpar** [comment] 2015-08-13 19:55
I was investigating this bug today and wasn't seeing any errors.  Have you tried this out on more recent bits to see if the problem still reproduces?

**Comment by vaualbus** [comment] 2015-08-13 20:09
no I have not tried it. But If I recall right I change the code so anyway
thanks for the research!

2015-08-13 21:55 GMT+02:00 Jared Parsons <notifications@github.com>:

**Comment by jaredpar** [comment] 2015-08-13 20:52
@vaualbus if you've changed the code and I can't reproduce it should we just close this issue then?  We can definitely open it back up if the issue comes back.

**Comment by vaualbus** [comment] 2015-08-13 21:02
Ya let's close it.


2015-08-13 22:53 GMT+02:00 Jared Parsons <notifications@github.com>:

**Closed** 2015-08-13 21:04 UTC
Labels: Area-Compilers, Bug

**Comment by vaualbus** [comment] 2015-08-13 21:06
Ok.
Il 13/Ago/2015 23:04, "Jared Parsons" <notifications@github.com> ha scritto:

**Comment by vaualbus** [comment] 2015-08-13 21:15
I revert to the code that get me the error, but now no more so it is anyway
fixed.

2015-08-13 23:06 GMT+02:00 Alberto Vaudagna <alberto.vaudagna@gmail.com>:
