### ISSUE TITLE
[C#] Itellisense when attaching lambda event handlers should show delegate parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49590] opened 2020-11-24 01:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Itellisense-when-attaching-lambda-e/1248603?preview=true)._

---
When attaching an event handler, you can "tab, tab" to create a handler for the event

if using lambdas, there is no obvious way to see the parameter count or types, it would be nice if intellisense or some other hints would be provided.

I find it is easier to tab, tab then, to remind myself of the parameters, then write the lambda

---
#### Feedback Bot on 11/9/2020, 11:48 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-11-24 01:31
We now have this with inline-hints.

**Comment by sharwell** [comment] 2020-12-01 19:43
Duplicate of #46190

**Closed by sharwell** 2020-12-01 19:43 UTC
Labels: Area-IDE, Feature Request, IDE-IntelliSense
