### ISSUE TITLE
Can't find implementation of Task<T> when targeting netstandard from netcoreapp

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#42795] opened 2020-03-26 16:35 UTC
**Steps to Reproduce**:

1. Create new netcoreapp3.1 class library solution A.
2. Add new netstandard2.0 class library to solution B.
3. Add `ITestClass` to solution B with member `Task<bool> DoSomething();`.
4. Add `TestClass` to solution B which implements `ITestClass`.
5. Reference solution B from solution A and declare `ITestClass foo = new TestClass();`.
6. Add line `foo.DoSomething()` in solution A.
7. Ctrl+F12 on `DoSomething` in solution A.

**Expected Behavior**:
Visual Studio 2019 navigates to the implementation of DoSomething in solution B.

**Actual Behavior**:
Visual Studio 2019 gives popup message "The symbol has no implementations."

**Comment by jez9999** [comment] 2020-03-26 16:40
If you change the target framework of solution B to netcoreapp3.1, the implementation is found, so the bug seems to happen with the combination of the different frameworks and the return type Task<T>.

**Comment by sharwell** [comment] 2020-04-08 18:38
Duplicate of #43093

**Closed by sharwell** 2020-04-08 18:38 UTC
Labels: Area-IDE
