### ISSUE TITLE
The Persian text is shown in Summary, vice versa

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37845] opened 2019-08-08 23:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/664018/the-persian-text-is-shown-in-summary-vice-versa.html)._

---
The Persian text is shown in Summary, vice versa
The description method is properly displayed before writing method but after that Reverse is displayed
see pic 1 and 2

---
#### Visual Studio Feedback System on 7/29/2019, 02:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/29/2019, 10:09 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2019-08-09 03:13
From @tmeschter:

> The Completion List quick info shows the doc comment correctly, but the Parameter Help quick info shows it with the words in reverse order. Possibly we're stripping out (or failing to insert) the right-to-left markers in the text in the case of Parameter Help.

**Comment by sharwell** [comment] 2019-08-09 03:26
I suspect this is caused by the following:

https://github.com/dotnet/roslyn/blob/8a30f458dae4c5a5170bd7d3cc73e2e2227fcd8a/src/Features/Core/Portable/Common/TaggedText.cs#L245-L253

If whitespace in the documentation comment is getting classified as whitespace, then a left-to-right mark will be inserted before each space.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:25
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-21 19:25 UTC
Labels: Bug, Area-IDE, Developer Community
