### ISSUE TITLE
C# interpolated raw strings cause FormatExceptions in .NET 5 and earlier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60374] opened 2022-03-24 23:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-interpolated-raw-strings-cause-Format/1692766)._

---
[severity:It bothers me. A fix would be nice]
When using C# 11, the following code works as expected in .NET 6.0, but throws a FormatException in .NET 5 and .NET Core 3.1:
```C#
Console.WriteLine($$"""{{{0}}""");
```
In .NET 5 and .NET Core 3.1, the generated IL contains  `ldstr "{{0}"` instead of the expected `ldstr "{{{0}"`.

The expected behavior is either 
* The compiler should correctly transform the raw string to a string that can be handled by String.Format, or
* The compiler should not attempt to transform the raw string into something that can be handled by String.Format, and should instead produce an error to the effect of "Missing complier required member 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler'", as it does when it can't compile dynamic expressions or init properties.

---
#### Feedback Bot on 3/16/2022, 01:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/23/2022, 08:38 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by 333fred** [comment] 2022-03-24 23:41
Duplicate of already fixed issue https://github.com/dotnet/roslyn/pull/59607. This fix will ship in the next preview of VS and with SDK version 6.0.300.

**Closed by 333fred** 2022-03-24 23:41 UTC
Labels: Bug, Area-Compilers
