### ISSUE TITLE
VBCSCompiler.exe Induces 11 GCs Every 30 Seconds When Not Handling Requests

### ISSUE THREAD

**Issue by brianrob** [dotnet/roslyn#44313] opened 2020-05-16 00:54 UTC
**Version Used**: 16.7 Preview 2

**Steps to Reproduce**:

1. Start VS and open a desktop C# project.
2. Build the project.

**Actual Behavior**:
The compiler server, `VBCSCompiler.exe` executes 11 induced GCs every 30 seconds, as long as the server remains alive and isn't handling a compilation request.  I imagine that the goal is to reduce memory footprint when the server isn't in-use, but this seems pretty excessive.

The code that performs these GCs is located at https://github.com/dotnet/roslyn/blob/master/src/Compilers/Server/VBCSCompiler/ServerDispatcher.cs#L241.

I'd say inducing a GC when the server is quiescent is reasonable (and maybe even 2 to handle finalizable objects), but I don't think that 11 GCs are needed, and I don't think this needs to continuously happen when the process isn't really doing any work.

Including @maoni0 as well, since I discussed this with her offline, and she likely has some good guidance here as well.

**Comment by davkean** [comment] 2022-02-01 07:06
This is a dupe of https://github.com/dotnet/roslyn/issues/55807, which ended up getting resolved in https://github.com/dotnet/roslyn/pull/55814. Feel free to open another bug here if you feel the new algorithm is still too aggressive.

**Closed by davkean** 2022-02-01 07:06 UTC
Labels: Area-Compilers, Area-Performance
