### ISSUE TITLE
"CS7038: Failed to emit module" when using List Pattern Matching on custom type

### ISSUE THREAD

**Issue by JaThePlayer** [dotnet/roslyn#60090] opened 2022-03-10 19:24 UTC
**Version Used**:  c#11 preview, Visual Studio 2022 17.1.1, though it also happens on SharpLab.
**Steps to Reproduce**:
* Create a new class or struct, and implement the `this[Index i]` function, but *don't* add a `Count` or `Length` property.
* Try to use List Pattern Matching on an instance of that class/struct

I've created a [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5Md8UA6AGVgEdSsBmfJXAYVwG9Nc/8WyCtgCCAJzEA1KAFMA7t179lCQSmwBtALq4IEiAE9Gy5UpMDhuAC4ALKAGcNASRgATGQA9cUHQF4AfLr6Bho+xvwAvma40aq4wAD2CQA2uAAKEFZWMmIwALKZAMY2ABQEohLS8rjJAJTRPBjmfFAAZrglqQ64GgBEAMTurbAyvTr1Tc2NzSYIAOzWYgCuMuHmURjRKgutEMn2q9EbEUA===) example that suffers from this issue, though it also happens locally in Visual Studio.

**Expected Behavior**:
A helpful error message.
**Actual Behavior**:
The compiler issues an unhelpful error:
`Error	CS7038	Failed to emit module '_': Unable to determine specific cause of the failure.`

**Comment by RikkiGibson** [comment] 2022-03-10 21:55
Duplicate of #59465

**Comment by RikkiGibson** [comment] 2022-03-10 21:56
Thank you for filing this issue. The fix for this should be available when VS 17.2 preview 2 comes out.

**Closed** 2022-03-10 21:55 UTC
Labels: Bug, Resolution-Duplicate, Area-Compilers, New Feature - List Patterns
