### ISSUE TITLE
Toggle for C#/.Net default value names

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48442] opened 2020-10-08 16:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1208287/toggle-for-cnet-default-value-names.html)._

---
<p>It seems a bit silly for Intellisense to &quot;suggest&quot; shortening &quot;Int16&quot; to &quot;short&quot; - the former is an abstract which guarantees number properties independent of process and language, while the latter is a language specific default that guarantees number properties independent of processor.</p> <p>So it is a matter of personal preference. I happen to like the former because it is more descriptive and because i code in C/C++ and C# it prevents numerous misunderstandings about overflow behaviour.</p> <p>Surely a better option would be a &quot;.Net&quot; number convention/&quot;C# number convention toggle or even a code cleanup filter, whereby the editor would automagically display/change as appropriate.</p>

---
#### Feedback Bot on 10/5/2020, 04:06 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment] 2020-10-08 16:55
Does this suggest adding a code style option to choose between the .NET types and the C# aliases?

(By the way, it's not only a matter of style, See [this blog](https://blog.paranoidcoding.com/2019/04/08/string-vs-String-is-not-about-style.html) from @jaredpar)

**Comment by CyrusNajmabadi** [comment] 2020-10-08 16:57
The two types are literally identical. C# recommends using the c# keyword by default since you are in c#. You can also disable this behavior. So the toggle already exists. As we are not going to change the default here, I'm going to close this out as by design

**Closed by CyrusNajmabadi** 2020-10-08 16:57 UTC
