### ISSUE TITLE
Incorrect "Cast is redundant" suggestion

### ISSUE THREAD

**Issue by ckimes89** [dotnet/roslyn#4271] opened 2015-07-31 20:21 UTC
In interpolated strings, VS2015 is suggesting that casting enums to ints is redundant.

```
public enum Foo
{
    One,
    Two
}

$"{(int)Foo.One}, {Foo.One}"
```

Output should be "0, One", but the suggestion would change it to "One, One".

**Comment by Pilchie** [comment] 2015-07-31 23:08
Duplicate of #4037.

**Closed by Pilchie** 2015-07-31 23:08 UTC
Labels: Area-IDE
