### ISSUE TITLE
XUnit build failures in 'prodcon/roslyn/master/' - '20180525.01'

### ISSUE THREAD

**Issue by jcagme** [dotnet/roslyn#27154] opened 2018-05-25 16:33 UTC
@dotnet-mc-bot commented on [Fri May 25 2018](https://github.com/dotnet/core-eng/issues/3545)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1720162
  - **Agent:** DDMBLDW149
  - **Error log:**Command: C:\Users\dlab14\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.console.x86.exe "E:\A\_work\24\s\Binaries\Release\UnitTests\CSharpVisualStudioTest\Roslyn.VisualStudio.CSharp.UnitTests.dll"  -xml "E:\A\_work\24\s\Binaries\Release\UnitTests\CSharpVisualStudioTest\xUnitResults\Roslyn.VisualStudio.CSharp.UnitTests.dll.xml" -noshadow -verbose
xUnit output log: E:\A\_work\24\s\Binaries\Release\Logs\Roslyn.VisualStudio.CSharp.UnitTests.dll.out.log
xunit produced no error output but had exit code 1
Errors Roslyn.Services.Editor2.UnitTests.dll

@mmitche, @jaredpar

**Comment by sharwell** [comment] 2018-05-25 21:11
Duplicate of #26842

**Closed by sharwell** 2018-05-25 21:11 UTC
