### ISSUE TITLE
[Discussion] Solution size threshold for falling back to persistent storage

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#25453] opened 2018-03-13 22:42 UTC
**Version Used**: 
2.8.0-beta2-62708-11 

Currently, persistent storage is used only in the case of a solution that is larger than 50MB.

Doing a bit of grepping around, I've come to this conclusion, that was based on Esent being the storage service.

https://github.com/dotnet/roslyn/issues/910#issuecomment-76292294

I'm wondering whether the solution threshold should be decreased in the case of SQLite or not via profiling, but I've done some research on the slqite cache size.

> Since the SQLite database file format was designed (in 2003) the default page size for new databases has been 1024 bytes. This was a reasonable choice in 2003. But on modern hardware, a 4096 byte page is a faster and better choice. So, beginning with SQLite version 3.12.0 (2016-03-29)) the default page size for new database files has been increased to 4096 bytes.

> The upper bound on the database cache size has traditionally defaulted to 2000 pages. SQLite version 3.12.0 also changes this default setting to be "-2000" which means 2000*1024 bytes, regardless of page size. So, the upper bound on the amount of memory used for the page cache is unchanged.

That means that, compared to esent's cache of 50MB, we're now using a <2MB cache.

See https://www.sqlite.org/pgszchng2016.html and https://www.sqlite.org/pragma.html#pragma_cache_size

**Comment by heejaechang** [comment] 2018-03-13 22:57
the 50MB threshold was decide at the time by doing some testing. basically we generated multiple various size solutions (* I can't remember exact number but something like this - 10 projects with 100 files, each file containing 1 type with 10 members and each member containing 1 error => 1000 types and 10000 members and 10000 errors) and then we increased solution size to (10 projects, 100 projects, 200 projects and so on)

and loaded those solutions in VS with and without persistent service and wait VS to become idle and see VM using vmmap.

and find solution size where holding everything in memory > saving data in persistent service. and use that solution size as threshold.

...

the 50MB is not just size of cache, it is memory reserved by persistent component itself such as image size (itself and dependencies). memory needed to save its states and etc.

**Comment by heejaechang** [comment] 2018-03-13 22:59
by the way, what is making you to think about using smaller threshold? if 50MB is too much, I think you have bigger problem than just making threshold smaller.

**Comment by Therzok** [comment] 2018-03-13 23:16
MonoDevelop recently dropped slightly under 50mb. That makes it not use a persistent storage, even though it's near the threshold. That delays the initial time until searching through types (via `AbstractNavigateToSearchService.SearchProjectInCurrentProcessAsync`) is finished by quite a few dozen seconds, which I think was not the case when there was a persistent storage in place.

Thus that is why I opened an issue about this while looking through history, because it seemed like the decision was based completely on Esent being the backend, not SQLite, so I thought different tuning would be needed for each of them. If it's solely tied to what solution size, and not how much the backend keeps in memory, that's cool. I got taken aback at the difference between caches 50mb in esent vs 2mb in sqlite. (I'm not suggesting dropping the threshold to 2mb, but something smaller than 50, or raising the sqlite in memory cache)

We can obviously control the size via the option, but I wanted to bring this into discussion, as now sqlite is the sole backend provided by roslyn, maybe fine tuning is needed in this scenario. There are probably different characteristics in tuning between Esent and SQLite.

**Comment by heejaechang** [comment] 2018-03-13 23:26
I am fine changing option to smaller threshold. we probably need to do some benchmark like we did for Esnet to find out new threshold though.

...

in VS, I think your issue might be okay since navigate to/ find references will soon run in OOP where it always saves data to persistent storage.

for other host, they can first try option to reduce threshold and see whether that improve perf? or consider using OOP as well?

**Comment by Therzok** [comment] 2018-03-13 23:36
> in VS, I think your issue might be okay since navigate to/ find references will soon run in OOP where it always saves data to persistent storage.

This is in VSMac where we don't have OOP (yet, not sure if we'll add it).

I'm going to try and measure it on our side too. Is there any infrastructure that's reusable in this scenario for when the esent tuning was done?

**Comment by heejaechang** [comment] 2018-03-14 00:06
unfortunately, it is years ago, nothing left from that era. all perf related tests/infrastructures at the time are all gone.

**Comment by CyrusNajmabadi** [comment] 2018-03-14 00:23
AFAIK, we could just use this db in all cases.  It's likely either a strict win, or neutral at worst.

The only place things fall down is that MS has a pretty strict policy about dlls loading.  And there are perf systems that flag this and make things fail if this dll gets loaded all the time.  So, by making there be this large threshold, it helps ensure that large projects get the boost, while not making the trigger fire in the regression harness.

**Comment by heejaechang** [comment] 2018-09-20 19:06
@Therzok if it is for VSForMac, you can just set this to 0 for now in VSForMac?
(http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/StorageOptions.cs,17) 

you don't need to change the default value, just in your MacWorkspace or something, in ctor, do

this.Options = this.Options.WithChangedOptions(... SolutionSizeThreshold, 0);

**Comment by Therzok** [comment] 2018-09-20 19:12
We did that already, I was just discussing whether better defaults should be done in roslyn.

**Comment by Therzok** [comment] 2018-09-20 19:16
So, the following points are:

The main solution we worked on dropped under 50MB, experiencing longer time to code times, because we were no longer using persistent storage.

Given that increase in time to code for subsequent solution loads, decided to bring this up for discussion, as it might mean perf gains for solutions of this size in VSWindows. SQLite cache size remark was directly related to this.

We already set it [here](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs#L132)

**Comment by CyrusNajmabadi** [comment] 2018-09-20 19:17
> We did that already, I was just discussing whether better defaults should be done in roslyn.

The main problem here is simply RPS.  It would actually be fine in practice to have this show up earlier.  But VS has gates that will disallow htis due to the dll load, and so we have to put in a value that ensures that RPS runs don't trigger this as a regression.

**Comment by heejaechang** [comment] 2018-09-20 19:27
@Therzok sure, we can change the default. persistent service used to only exist in VS side, so changing that value was only specific to VS. now persistent service got down to Desktop layer where any host can just implicitly get. its impact is bigger so, probably require some validation before we can change such big impact value.

**Comment by heejaechang** [comment] 2018-09-20 19:29
tagging @jinujoseph since changing this value will require a lot of hoop to go through if we decide to do so.

**Comment by sandyarmstrong** [comment] 2020-03-04 23:36
@Therzok @CyrusNajmabadi fixed by https://github.com/dotnet/roslyn/pull/42027?

**Closed** 2020-03-04 23:37 UTC
Labels: Area-IDE, Discussion, Resolution-Not Applicable
