### ISSUE TITLE
Add usings leaves out some expected directives

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33891] opened 2019-03-06 01:09 UTC
**Version Used**: 
Visual Studio 2019 Preview 4.1

**Steps to Reproduce**:

1. Copy and paste some code that will trigger the "Add missing usings"
```csharp
using System;

class C
{
    void M()
    {
        Console.WriteLine("Hello World!");

        List<string> greetings = new List<string>()
        { "hi", "yo", "hello", "howdy" };

        string json = JsonConvert.SerializeObject("some json");

        StringBuilder sb = new StringBuilder("ABC", 50);

        bool checkFile = File.Exists(".\\");
    }
        
}
```

2. Types (Ctrl + .) to "Add missing usings"
![image](https://user-images.githubusercontent.com/8293542/53848440-2e27ff80-3f69-11e9-9d12-9b46eadfeb95.png)

**Expected Behavior**:
All missing usings are added.
```csharp
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

class C
{
    void M()
    {
        Console.WriteLine("Hello World!");

        List<string> greetings = new List<string>()
        { "hi", "yo", "hello", "howdy" };

        string json = JsonConvert.SerializeObject("some json");

        StringBuilder sb = new StringBuilder("ABC", 50);

        bool checkFile = File.Exists(".\\");
    }
        
}
```

**Actual Behavior**:
`using System.IO` was left out.
![image](https://user-images.githubusercontent.com/8293542/53848455-3c761b80-3f69-11e9-8e1d-bc5a7b4dc777.png)

@JoeRobich

**Comment by sharwell** [comment] 2019-03-06 14:51
This is _likely_ by design. "Add missing usings" only adds using directives for cases where there is *exactly one* resolution for the missing using. For the `File` case, there are two possible resolutions, so it needs to be resolved separately from the rest.

**Comment by JoeRobich** [comment] 2019-03-06 16:03
@kendrahavens In this case Sam is right. We don't add ambiguous usings. I know you had a case yesterday where only the Newtonsoft using would get added instead of all the usings. Do you have a way to reproduce that behavior?

**Comment by miloush** [comment] 2019-03-06 19:28
To be fair one is `using` and one is `using static`, I would take a guess and expect that `using static` is much much less used than adding `using`, so it feels a bit unfortunate that they are in one bag. Moreover only one of the ambiguous resolutions can possibly compile.

**Comment by CyrusNajmabadi** [comment] 2019-03-06 20:02
> Moreover only one of the ambiguous resolutions can possibly compile.

Agreed.  I do think we decided this was out of scope for the original work.  But it would be a *super nice* way to deal with the ambiguity case in the future.  It could potentially be an "up for grabs" item for someone to take on.  I know i miht be interested in doing this if no one else takes it!

**Comment by CyrusNajmabadi** [comment] 2022-10-31 22:21
I get the right set of usings added *except* for the json.net ones.  But i think that's appropriate.  Automatically adding nuget-packages to a project is not something that we should do.  users should be explicit on that.

**Closed by CyrusNajmabadi** 2022-10-31 22:21 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, IDE-CodeStyle
