### ISSUE TITLE
Quick Action: Convert for to foreach and vice versa

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/roslyn#24381] opened 2018-01-22 22:53 UTC
just like resharper, allow converting for to foreach and vice versa. me not a genius. me realize index is needed where I wrote `foreach`, me realize index is no more needed where I wrote `for`. thanks.:)

**Comment by sharwell** [comment] 2018-01-23 14:06
I'm going to close this as a duplicate of #8953 as we continue working on the feature design, though it may get split back out during the implementation portion.

**Closed by sharwell** 2018-01-23 14:06 UTC
Labels: Area-IDE
