### ISSUE TITLE
Compile time constant some reflection values 

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#10972] opened 2016-04-29 17:02 UTC
For example `typeof(MyClass).Namespace` could be an interned string?

**Comment by svick** [comment] 2016-04-29 18:16
Duplicate of dotnet/coreclr#2591. Not sure whether this would be better implemented in Roslyn or CLR.

**Comment by gafter** [comment] 2016-05-01 18:18
@benaadams Do you really mean "compile-time constant" in the language sense (i.e. could be using in a switch case expression), or do you mean you want more efficient generated code?

**Comment by benaadams** [comment] 2016-05-01 19:25
@gafter literally a compile time constant for the string values in the style of `nameof()`; where appropriate - not everything could go this way but some things could be resolved at compile time rather than runtime or jit time.

So `typeof(MyClass).FullName` could be resolved at compile time, but `Type t; ... t.FullName` probably couldn't.

More complex reflected items like bindings or assembly name I don't think would be able to be resolved at compile time as they may change as dlls were swapped or updated.

A corner case would be `typeof(MyClass).FullName` would fail quite badly at runtime if `MyClass` has changed namespace in or been removed form a dependent dll. However it would return a value if it was a compile time constant. However that behaviour is similar to `nameof`.

**Comment by gafter** [comment] 2016-05-05 19:07
So this is actually a language change request, as whether or not a string is a constant is visible to the language.

**Comment by benaadams** [comment] 2016-05-05 19:24
Not sure; currently they are evaluated at runtime? Common use cases are in logging and exceptions (logging) which are slow areas anyway. Not hugely fussed about them working in `switch` would just be a nice extrapolation.

**Comment by benaadams** [comment] 2016-05-05 19:26
Or could be an extension to `nameof` to add namespace qualification to stay away from Type?

**Comment by paulomorgado** [comment] 2016-05-06 15:59
@benaadams 

`namespaceof()`

**Comment by benaadams** [comment] 2016-05-06 16:13
@paulomorgado that would work. 

Rather than going

 `nameof(System) + '.' nameof(Collections) +  '.' nameof(Generic)` or `typeof(Dictionary<string,string>).Namespace`

You could go

`namespaceof(Dictionary<string,string>)`

or 
`namespaceof(Dictionary<string,string>) + '.' + nameof(Dictionary<string,string>)`

Rather than `typeof(Dictionary<string,string>).FullName`

**Comment by paulomorgado** [comment] 2016-05-06 16:59
@benaadams 

`fullnameof()`

😄

**Comment by alrz** [comment] 2016-05-06 19:10
Basically, most of properties coming out of `typeof`(and the type itself #8194) can be treated as compile-time constants (if the compiler cares enough). I think the "syntax" in the original post is the most flexible way of doing this, `typeof(T).FullName`. So practically `typeof(T).Name` and `nameof(T)` would be the same.

**Comment by alrz** [comment] 2017-04-20 10:02
@benaadams May you move this to csharplang repo?

**Comment by mwpowellhtx** [comment] 2019-10-22 14:49
I like it, and I am working on a use case where that might be interesting. i.e.

```C#
namespace Foo
{
    class Bar { }
}

// ...

const string barNameSpace = namespaceof(Bar); // "Foo" const string
```

**Closed** 2022-11-08 17:00 UTC
Labels: Feature Request, 0 - Backlog, Area-Language Design

**Comment by jnm2** [comment] 2024-10-11 21:32
This is now proposed at https://github.com/dotnet/csharplang/issues/8505.

**Comment by jnm2** [comment] 2025-03-14 18:32
That's right. The language design team has decided that this is not desired. The reasons why and the recommended path forward are at the linked design meeting notes: <https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-10-16.md#typeof-string-constants>
