### ISSUE TITLE
We don't handle a C# file in a VB project correctly

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8048] opened 2016-01-20 17:07 UTC
Ran into this converting some C# code to VB:
1. Create a C# file in a VB project, with the following contents

``` VB
namespace Microsoft.VisualStudio.Shell.Interop
{
    [ComImport()]
    [ComVisible(false)]
    <Guid("C1F63D0C-4CAE-4907-BE74-EEB75D386ECB")> $$ <InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)>
    internal interface IVsSqm
    {
        void GetSessionStartTime(
            [Out] out System.Runtime.InteropServices.ComTypes.FILETIME time
            );
        void GetFlags(
            [Out, MarshalAs(UnmanagedType.U4)] out System.UInt32 flags
            );
        void SetFlags(
            [In, MarshalAs(UnmanagedType.U4)] System.UInt32 flags

```
1. At $$, press ENTER

@Expected: New line
@Actual: 

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax'.
---------------------------
OK   
---------------------------
```

Apparently this is a dupe but couldn't find it.

**Comment by davkean** [comment] 2016-01-20 17:18
Weirdly, the compiler is treating the file as VB - but the workspace appears to be treating it as C# file.

**Comment by paul1956** [comment] 2016-01-22 02:04
I reported something similar in #5375

**Comment by Pilchie** [comment] 2016-01-22 17:44
We think this is a dupe, but couldn't find it.

**Comment by paul1956** [comment] 2016-01-22 20:04
@pilchie #5375 but it was closed.

**Comment by jasonmalinowski** [comment] 2016-01-22 20:27
@paul1956: that was a unique problem with the Analyzer templates.

**Comment by CyrusNajmabadi** [comment] 2022-02-04 19:08
Closing out as this does not repro for me.  I observe no failures or unexpected behavior editing a cs file in a vb project.

**Closed by CyrusNajmabadi** 2022-02-04 19:08 UTC
Labels: Bug, help wanted, Area-IDE
