### ISSUE TITLE
Access Denied error for vbc on Linux and Mac

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9030] opened 2016-02-23 00:23 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4114/

MSBuild Error

error MSB6003: The specified task executable "vbc" could not be run. ApplicationName='/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Bootstrap/vbc', CommandLine=' -noconfig @"/tmp/tmpea495231a89a4b6faffe8dfcd733d323.rsp"', CurrentDirectory='', Native error= Access denied [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj]
Indication 1

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/4051/

MSBuild Error

error MSB6003: The specified task executable "vbc" could not be run. ApplicationName='/Users/dotnet-bot/j/workspace/roslyn_prtest_mac_dbg_unit32/Binaries/Bootstrap/vbc', CommandLine=' -noconfig @"/tmp/tmp19cfbed064594a9fb9ecdf295cdfc828.rsp"', CurrentDirectory='', Native error= Access denied [/Users/dotnet-bot/j/workspace/roslyn_prtest_mac_dbg_unit32/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj]
Indication 1

**Comment by davkean** [comment] 2016-02-23 03:16
@mmitche @agocke Any idea on this one?

**Comment by mmitche** [comment] 2016-02-23 16:22
Not sure.  I assume the executable got marked as +x?

**Comment by natidea** [comment] 2016-02-23 17:07
Note this build is happening against a feature branch, not against master

**Comment by davkean** [comment] 2016-02-23 17:47
@AlekseyTs has run into this once before when he accidentally ripped of the execute bit of cibuild.sh, but I don't know how he would have influence over this in the bookstrap compiler.

**Comment by AlekseyTs** [comment] 2016-02-23 18:20
> when he accidentally ripped of the execute bit of cibuild.sh

I didn't do this, git dropped the bit during merge.

**Comment by davkean** [comment] 2016-02-23 18:22
@AlekseyTs regardless of whether you and GIT caused it, it happened in your branch, on your machine. :)

**Comment by AlekseyTs** [comment] 2016-02-23 18:28
@davkean Regardless on whose machine it happened, the issue could be a "courtesy" of Git rather than people accidentally ripping bits of files they have absolutely no interest in. :)

**Comment by davkean** [comment] 2016-02-23 18:29
We've never seen this before - we do merges *all* of the time, so if you could get a repro that would be great.

**Comment by AlekseyTs** [comment] 2016-02-23 18:40
It is all in the history, here is the commit that fixed up the attribute https://github.com/dotnet/roslyn/commit/6075e151b789c70fa6a3de93baa02976d290c107

**Comment by davkean** [comment] 2016-02-23 18:42
That shows the fix up, but not the cause, why was cibuild.sh touched in the first place?

**Comment by AlekseyTs** [comment] 2016-02-23 18:46
Well, you can trace the history back and see what was happening with this file and when. What I know is that I didn't touch the file. I didn't know the file existed and would be very happy to not learn about its existence.

**Comment by davkean** [comment] 2016-02-23 18:49
Nat, if @AlekseyTs can find a repro, we'll be happy to look at it, until then I would put this down as a branch specific issue. We're not running into this on any other branch.

**Comment by davkean** [comment] 2016-02-25 01:21
Nat, it looks like execute bit can get ripped off in certain cases on Windows. If someone was to run into this on Windows, they can set the following:

`git config core.filemode false`

And this will prevent the issue.

**Comment by davkean** [comment] 2016-02-26 17:47
I'm going to mark this as no repro, I'm not seeing this in recent builds.

**Closed by davkean** 2016-02-26 17:47 UTC
Labels: Area-Infrastructure, Bug, Flaky
