### ISSUE TITLE
Turning on Nullable references crashes VS with analyzers installed

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#31637] opened 2018-12-08 04:34 UTC
**Version Used**: 16.0.0 Preview 2.0 [28407.111.d16.0stg]

**Steps to Reproduce**:

Install Roslyn.Diagnostics.Analyzers on a project with Nullable references turned on.

**Expected Behavior**:

No Crash

**Actual Behavior**:

Visual Studio Crashes with the following fail fast exception:

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Sequence contains no elements"} | System.InvalidOperationException

[Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.CompilationAnalyzer..ctor(INamedTypeSymbol symbolType, INamedTypeSymbol compilationType)](https://github.com/dotnet/roslyn-analyzers/blob/3a9597c623019cc68af10a3478188906ce4a2170/src/Roslyn.Diagnostics.Analyzers/Core/SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs#L77)

```ini
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source) in f:\dd\ndp\fx\src\Core\System\Linq\Enumerable.cs:line 1174
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.CompilationAnalyzer..ctor(INamedTypeSymbol symbolType, INamedTypeSymbol compilationType) in E:\A\_work\59\s\src\Roslyn.Diagnostics.Analyzers\Core\SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs:line 77
   at Roslyn.Diagnostics.CSharp.Analyzers.CSharpSymbolDeclaredEventAnalyzer.GetCompilationAnalyzer(Compilation compilation, INamedTypeSymbol symbolType) in E:\A\_work\59\s\src\Roslyn.Diagnostics.Analyzers\CSharp\CSharpSymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs:line 26
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.<Initialize>b__7_0(CompilationStartAnalysisContext compilationContext) in E:\A\_work\59\s\src\Roslyn.Diagnostics.Analyzers\Core\SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs:line 46
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.CollectCompilationActionsContext.RegisterCompilationStartAction(Action`1 action) in /_/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs:line 351
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.Initialize(AnalysisContext context) in E:\A\_work\59\s\src\Roslyn.Diagnostics.Analyzers\Core\SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs:line 43
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.IsCompilationEndAnalyzer(DiagnosticAnalyzer analyzer, Project project, Compilation compilation) in /_/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs:line 311
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.StateSet.ComputeCompilationEndAnalyzer(Project project, Compilation compilation) in /_/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateSet.cs:line 269
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.<AnalyzeProjectAsync>d__88.MoveNext() in /_/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs:line 112
```

Dump available at `\mlangfs1\public\jmarolf\Dumps\crash.dmp`

**Comment by jinujoseph** [comment] 2018-12-10 09:58
@jmarolf  dupe of https://github.com/dotnet/roslyn/issues/31490 ? 
cc @mavasani

**Comment by mavasani** [comment] 2018-12-10 10:23
@heejaechang fixed this couple of days ago.

**Comment by jinujoseph** [comment] 2018-12-10 10:39
Duplicate of  #31490

**Closed by jinujoseph** 2018-12-10 10:39 UTC
Labels: Area-IDE, Resolution-Duplicate
