### ISSUE TITLE
"is" doesn't differentiate signed & unsigned array types

### ISSUE THREAD

**Issue by ColoradoNate** [dotnet/roslyn#20874] opened 2017-07-13 22:34 UTC
**Version Used**:  VS2015, VS2017

**Steps to Reproduce**:

1.  Create a ushort[]
2.  Test if the ushort[] 'is' a short[]

**Expected Behavior**: 'is' claims signed arrays are not unsigned arrays, and unsigned arrays are not signed arrays

**Actual Behavior**: 'is' claims signed arrays are both signed and unsigned arrays.

NOTE:  This issue shows up with short/ushort, int/uint, and long/ulong arrays.

NOTE: The new C#7 switch syntax ("case ushort[] ua:") exhibits the same issue.  The first signed/unsigned case in the source wins.

NOTE:  see [SwitchOnType.zip](https://github.com/dotnet/roslyn/files/1146854/SwitchOnType.zip) for an example

**Comment by HaloFour** [comment] 2017-07-13 23:20
The resultant IL is the expected `isinst uint[]`, so if this isn't the expected behavior it looks like it would be a bug in the CLR itself.  However, since `int[]` and `uint[]` are effectively equivalent in terms of storage I'm going to go so far as to say that this behavior is likely intentional.  The compiler could possibly emit additional IL to be more strict in the type comparison, but since it's likely been like this since C# 1.0 that would probably be considered a breaking change.

**Comment by sharwell** [comment] 2017-07-13 23:57
Based on @HaloFour's investigation, I'm going to close this as **external**. @ColoradoNate the place to file this issue would be in the [dotnet/coreclr](https://github.com/dotnet/coreclr) repository, where you'll get a bunch of information about why this occurs even if it doesn't change behavior. :smile:

**Comment by ColoradoNate** [comment] 2017-07-17 18:46
I'm not *quite* convinced yet.  I posted this question to the CoreCLR repo, and they said (among other things) that "It is one of the cases where .NET Runtime is more permissive than C# language".  However, they also said that this "issue" should be show up for ushort/short scalars as well as arrays, and uint8 and bool too.  But, C# seems to work fine differentiating those with "is" and the new C#7 switch syntax.  It's just arrays where the issue shows up.

When I looked at the output IL, when checking "x is ushort[]", the output IL uses "isinst uint16[]".  But when checking "x is ushort", the output IL uses "isinst [mscorlib]System.UInt16".  In other words, the C# compiler DOES work around the CLR permissiveness difference with scalars, but not arrays.  And that seems like an unnecessary inconsistency.

Side note, if I say "x is UInt16[]", the IL still uses "isinst ushort[]", so that potential work-around doesn't work either.

Is there not a way that C# could generate IL that would make C# self-consistent (both in terms of scalars being consistent with arrays AND being consistent in that ushort[] is not a short[] in the language)?

**Comment by HaloFour** [comment] 2017-07-17 18:59
@ColoradoNate 

I *think* that the differences you are seeing are related mostly to the different aliases that C# and IL have for the primitive types, not actual differences in the byte code or behavior.  I'd have to explore that to be sure.

However, even if it is the case that the C# compiler has an option to emit IL that is more strict it is way too late to change this behavior now, even if it isn't consistently applied.  It seems that both the CLR teams and the C# teams consciously decided to live with the clash in their specs and that the C# team intentionally decided to not implement a stricter but much slower type check.  At best you could probably try to propose some alternate syntax for type checking on the [C# Language Repository](https://github.com/dotnet/csharplang/).

**Comment by sharwell** [comment] 2017-07-17 23:25
I'll reopen this for the compiler team to give more details.

**Comment by jaredpar** [comment] 2017-07-17 23:53
CC @gafter for resolution.

**Comment by gafter** [comment] 2017-07-29 00:27
While this appears unfortunate from the C# perspective, this is just the way the runtime works. From the runtime's perspective, this is by design, or at least far too late to change now.

I recommend avoiding the use of primitive array types in pattern-matching.

**Closed by gafter** 2017-07-29 00:27 UTC
Labels: Area-Compilers, Question

**Comment by tannergooding** [comment] 2017-07-29 15:55
@gafter, are you indicating that it is too late to change the runtime or the IL emitted by the language (or both)?

The runtime doesn't differentiate between signed or unsigned primitive types on the stack and instead relies on subsequent instructions to do the right thing with the value on the stack. As such, `isinst ushort` is true for both `ushort` and `short` (and likewise for `isinst short`).

However, as mentioned above, when doing `x is ushort` the compiler emits `isinst [mscorlib]System.UInt16` and this allows the check to succeed for `ushort` and fail for `short` (since it is validating the full type, rather than the primitive type). So, it would seem like (assuming the compiler could take such a change) the compiler could emit `isinst [mscorlib]System.UInt16[]` for `x is ushort[]` (or at least emit the full type when the user explicitly does `x is System.UInt16[]`) and the issue would be resolved (I did validate this works).

**Comment by gafter** [comment] 2017-07-30 04:06
@tannergooding that is what the compiler does.

**Comment by tannergooding** [comment] 2017-07-30 04:18
@gafter, I'm confused by your statement.

For the following code:
```C#
static void Test(object o)
{
    Console.WriteLine(o is ushort);
    Console.WriteLine(o is ushort[]);
}
```

The compiler emits:
```IL
IL_0000:  nop
IL_0001:  ldarg.0
IL_0002:  isinst     [mscorlib]System.UInt16
IL_0007:  ldnull
IL_0008:  cgt.un
IL_000a:  call       void [mscorlib]System.Console::WriteLine(bool)
IL_000f:  nop
IL_0010:  ldarg.0
IL_0011:  isinst     uint16[]
IL_0016:  ldnull
IL_0017:  cgt.un
IL_0019:  call       void [mscorlib]System.Console::WriteLine(bool)
IL_001e:  nop
IL_001f:  ret
```

The proposed fix is for the compiler to emit (or provide a way to emit) `isinst [mscorlib]System.UInt16[]` for `IL_0011` so that arrays have the same behavior as scalar values.

**Comment by gafter** [comment] 2017-07-30 04:40
@tannergooding Despite the fact that these are displayed differently, I believe the same encoding is used for both `ushort` and `System.UInt16` in the assembly.

To put it another way, how do you suggest the compiler produce code to correct the behavior of the following program?

``` c#
using System;

namespace Repro
{
    public class Program
    {
        public static void Main()
        {
            M<uint>(new int[10]);
        }

        public static void M<T>(object o)
        {
            Console.WriteLine($"{o.GetType()} is {typeof(T)}[] : {o is T[]}");
        }
    }
}
```

which prints

``` none
System.Int32[] is System.UInt32[] : True
```

**Comment by tannergooding** [comment] 2017-07-30 05:16
@gafter, thanks for the explanation. Based on your sample, it does sound like there is nothing the compiler can do and that the CLR would have to make a change to ensure that `isinst` behaves 'correctly' here.

The actual speclet on the `isinst` instruction indicates:
> If the actual type (not the verifier tracked type) of obj is verifier-assignable-to the type typeTok then isinst succeeds and obj (as result) is returned unchanged while verification tracks its type as typeTok. Unlike coercions (§III.1.6) and conversions (§III.3.27), isinst never changes the actual type of an object and preserves object identity (see Partition I).
>
>If obj is null, or obj is not verifier-assignable-to the type typeTok, isinst fails and returns null. 

I don't know enough about `verifier-assignable-to` rules to say whether or not this would be a bug or a feature request on CoreCLR.

**Comment by VSadov** [comment] 2017-07-31 15:36
I beleive "is" is a check for assignment compatibility per runtime rules, so it passes.
For a strict type check 'inst.GetType() == typeof(type)' can be used. Generally assignability is more interesting though.

I think the behavior is by design. 
Runtime treats int[] as assignment compatible with uint[].

**Comment by VSadov** [comment] 2017-07-31 16:17
`verifier-assignable-to` means that an instance of one type can be verifiably used as an instance of another. The set is larger than being in the same inheritance hierarchy. 

The other examples are delegates with compatible signatures, anything assignment-compatible by variance.
