### ISSUE TITLE
Make ProjectTracker and AbstractProject free threaded

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#15871] opened 2016-12-13 20:21 UTC
Investigate the possibility of making the ProjectTracker and AbstractProject classes free threaded (or mostly) to enable better performance when being accessed by CPS project system (running on background thread) to avoid switching to foreground thread to serialize all work.

**Comment by mavasani** [comment] 2016-12-14 19:11
Note that this issue will essentially block moving CPS calls into Roslyn Language service on the background thread, i.e. https://github.com/dotnet/roslyn-project-system/issues/353. We hope to do this change in CPS soon after RTW to improve performance.

**Comment by mavasani** [comment] 2016-12-14 19:12
I think AbstractProject is already free threaded. We need to revert https://github.com/dotnet/roslyn/pull/15852 and make the ProjectTracker free threaded.

**Comment by jasonmalinowski** [comment] 2017-11-06 23:26
This is now a dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/501654 internally, and since these are both just tracking bugs for work I'll give the internal cross-team one precedence.

**Closed by jasonmalinowski** 2017-11-06 23:26 UTC
Labels: Area-IDE, Concept-API, Feature Request
