### ISSUE TITLE
'=' in path causes issues with /reference

### ISSUE THREAD

**Issue by mmitche** [dotnet/roslyn#18395] opened 2017-04-03 17:43 UTC
**Version Used**: 

**Steps to Reproduce**:

1. Clone corefx into a path containing '='
2. Build corefx

**Expected Behavior**:
Successful build.

**Actual Behavior**:
/reference paths appended to csc command line contain = signs, but are not quoted.  Roslyn interprets these as aliases.

Appears to be a bug in https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Csc.cs#L290

**Comment by jaredpar** [comment] 2017-04-03 17:46
Looks like a duplicate of #5623

**Closed by jaredpar** 2017-04-03 17:46 UTC

**Comment by mmitche** [comment] 2017-04-03 17:47
@jaredpar Thanks, looks exactly the same.  I was attempting to auto-generate some job names in jenkins based on input parameters and hit this.  Any chance it will get fixed?

**Comment by jaredpar** [comment] 2017-04-03 17:50
It's on the list but given the low number of reports it's probably not going to meet the bar soon (been that way for 2+ years now).  Is it easy to aoid this?

**Comment by mmitche** [comment] 2017-04-03 17:51
@jaredpar Yeah.
