### ISSUE TITLE
C# go to implementation feature lists unsuitable implementations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64538] opened 2022-10-06 17:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-go-to-implementation-feature-lists-un/10152037)._

---
**Context:** Interface IRepository has method Save. IPersonRepository and IDepartmentRepository extend IRepository. PersonRepository implements IPersonRepository and DepartmentRepository implements IDepartmentRepository. An instance of IPersonRepository is used to Save a Person object in TestMethod.

**Result:** Using feature "Go to implementation" on Save method inside TestMethod lists that there are two implementing classes: PersonRepository and DepartmentRepository.

**Expected:** Using feature "Go to implementation" on Save method inside TestMethod opens PersonRepository and navigates to Save method.

Note that listing multiple results makes sense in some scenarios, for example if TestMethod would use an instance of IRepository, rather than IPersonRepository.

My question is very similar to [[C++] Go to definition should go to child class implementation, not parent class implementation](https://developercommunity.visualstudio.com/t/C-Go-to-definition-should-go-to-chil/791931?entry=suggestion&ref=native&refTime=1663612775313&refUserId=3abf2cc9-24f9-63b2-aed3-4e62166fa71a), but it's about go to implementation feature, rather than go to definition.

---
#### Feedback Bot on 9/19/2022, 08:29 PM: 

(private comment, text removed)

**Comment by jasonmalinowski** [comment] 2022-10-06 17:56
To summarize the user's code they mean something like below. If you have something typed as IPersonRepository and you call .Save(), we are binding that method to IRepository.Save and then showing all implementations, even though the stronger interface means we know DepartmentRepository couldn't be called.

```
interface IRepository { void Save(); }
interface IPersonRepository : IRepository { }
interface IDepartmentRepository : IRepository { }
class PersonRepository : IPersonRepository
{
    public void Save()
    {
    }
}

class DepartmentRepository : IDepartmentRepository
{
    public void Save()
    {
    }
}
```

**Comment by jasonmalinowski** [comment] 2022-10-06 19:13
@CyrusNajmabadi: but without the presence of that, why would we show it? Taken to the extreme that means go to implementation on any interface method has to show any method that matches the signature, but we don't do that.

**Comment by CyrusNajmabadi** [comment] 2022-10-06 19:17
In this case, i think the idea is simply that this isn't some special Save method.  It's just IRepository.Save and we're taking you to impls of that.  I'd be extremely wary of not showing this as users may say "i was simply interested in this member, not just through instances of the particular tyep i was calling through" (i know i do this a ton myself).

**Comment by jasonmalinowski** [comment] 2022-10-06 21:05
@CyrusNajmabadi The general guideline for how go to implementation works was to specifically be "take me to where the other side of this call is"; I can't recall if we changed that definition a bit but I can see both sides here. Find References filtered to just definitions can also get you the thing you want, but that's not terribly friendly.

**Comment by CyrusNajmabadi** [comment] 2022-10-06 21:08
> The general guideline for how go to implementation works was to specifically be "take me to where the other side of this call is";

FWIW, i don't remember such a guideline.  To me it was always: take me to the one impl if it exists, or show me the N impls if there are many.

I am *extraordinarily* hesitant about filtering here as this absolutely may convey to people that there is just a subset of impls of this interface method, and they may miss the rest.  Requiring users to know they must traverse first to the interface method to ask this question is extremely subtle and could be very surprising.  It also def violates the existing idea that you can ask these questions at decl vs ref location and get consistent results.

**Comment by jasonmalinowski** [comment] 2022-10-06 21:18
> i don't remember such a guideline.

Well that was my guideline when I wrote it. :smile:

I'll add this to IDE design backlog. I see good arguments for both behaviors.

**Comment by MatrixRonny** [comment] 2022-10-13 11:50
I would like to note that Implements section from View Call Hierarchy works like the existing Go To Implementation. There are two features that expose the same information. One of them should be changed. I recommend preserving View Call Hierarchy the way it is and exposing the new feature by replacing existing Go To Implementation.

I agree with @CyrusNajmabadi that the current Go To Implementation has some benefits, but I find the current feature inappropriate when used on code like the following. I would not be interested in `DepartmentRepository.Save` in this case.

``` C#
PersonRepository personRepository;

void TestMethod(Person person)
{
    personRepository.Save(person);
}
```

If it were to use the suggested feature, the existing one would be the result of Go To Definition and then using the new feature (two consecutive shortcuts). For example, pressing F12 and then CTRL + F12 with cursor on Save, would list both `IPersonRepository` and `IDepartmentRepository` implementations after opening the base definition. The other way around, preserving the current Go To Implementation provides no option when many implementations are listed.

In addition, it is technically incorrect to say that `DepartmentRepository.Save` implements `IPersonRepository.Save`. The following code does not compile:

``` C#
IPersonRepository smt = new DepartmentRepository();
```

> class DeeperRepository : DepartmentRepository, IPersonRepository 

I took a closer look at that example. I consider that `DeeperRepository` does implement `IPersonRepository`, but the code is found in `DepartmentRepository`. This has to do with the *stitching* mechanism that @CyrusNajmabadi mentioned, which also makes the previous code compile using rocket science:

``` C#
IPersonRepository smt = (IPersonRepository)new DepartmentRepository();
```

**Comment by MatrixRonny** [comment] 2022-10-13 21:04
We may be different kind of programmers. I prefer brevity over broadness. 

In my project, the interfaces currently have only one implementation. It's annoying to keep searching for the appropriate implementation instead of navigating to it automatically. You have your feature, I want mine 😄

**Comment by CyrusNajmabadi** [comment] 2022-10-13 21:10
> In my project, the interfaces currently have only one implementation

Can you link to your project?  If there is just one implementation then we will try to navigate to it automatically *provided* we find the impl in a reasonable amount of time.  If not, we pop up the results window so you can proceed with working while the search is happening.

**Comment by MatrixRonny** [comment] 2022-10-13 21:23
My project is a private fork of https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator

Since my code is detached from the main repository, it would help if you describe how to apply your changes or at least indicate a branch.

Thanks! I really wasn't expecting direct help.

**Comment by MatrixRonny** [comment] 2022-10-21 09:04
I would like to add that Find All References feature can be improved in the current scenario as well.

Using Find All References on `PersonRepository.Save` definition would also find code that calls `DepartmentRepository.Save`.

**Comment by CyrusNajmabadi** [comment] 2024-11-22 04:42
Closing out as this is working as intended.

**Closed by CyrusNajmabadi** 2024-11-22 04:42 UTC
Labels: Area-IDE

**Comment by MatrixRonny** [comment] 2024-11-27 19:44
@CyrusNajmabadi I just tested the "Go to Implementation" feature and it works ok for classes, but not for methods. See the following code and comments:

``` C#
interface RootInterface { void DoSomething(); }
interface Concept1 : RootInterface { }
interface Concept2 : RootInterface { }
class Implementation1 : Concept1 
{
    public void DoSomething() { }
}
class Implementation2 : Concept2 {
    public void DoSomething() { }
}

void TestMethod()
{
    // Go to Implementation command on Concept1 type bellow correctly identifies Implementation1.
    Concept1 concept1 = new Implementation1();

    // Go to Implementation command on DoSomething method bellow incorrectly lists both implementations.
    concept1.DoSomething();
}
```
