### ISSUE TITLE
Visual Studio 2022's new rename box leads into forgetting "Rename symbol's file"-option after renaming non-symbol like variable, namespace and other

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63181] opened 2022-08-03 20:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022s-new-rename-box-lead/10083717)._

---
Well, the title is very concrete. Since Visual Studio 2022 there is a new rename box. I appreciate this, but there is a bug!

First of all: I am only talking about the option “Rename smybol’s file” that is only appearing when symbol’s name and symbol’s filename are equal!

How to reproduce the bug:

1.  Create a .cs-file and a class within it. There names have to be equal.
2.  Write a meaning less field or property.
3.  Trigger the action “Refactor.Rename” on the class name (right click “Quick Actions and Refactorings” or shortcut), tick the option “Rename smybol’s file” and press the “Apply”-button. The option should remain when renaming a **symbol** again!
4.  Now trigger the action “Refactor.Rename” but for this time on the field or property. The option “Rename symbol’s file” does not appear. Press the “Apply”-button.
5.  You now produce the bug by triggering the action “Refactor.Rename” again on the class name. The option “Rename smybol’s file” you just ticked before is now unticked.

Please fix this.

---
#### Feedback Bot on 6/29/2022, 06:58 PM: 

(private comment, text removed)
#### Feedback Bot on 7/1/2022, 10:58 AM: 

(private comment, text removed)

---
#### Andrew Hall 🤘 [MSFT] solved on 7/1/2022, 00:18 PM, 0 votes: 

<p>A fix for this issue has been released! Install the most recent release from <a target='_blank' href="https://visualstudio.microsoft.com/downloads/">https://visualstudio.microsoft.com/downloads/</a>. Thank you for providing valuable feedback which has helped improve the product.</p>
<p>You can track the fix merged with <a target='_blank' href="https://github.com/dotnet/roslyn/pull/61785">https://github.com/dotnet/roslyn/pull/61785</a></p>

#### Sergio Fonseca on 8/3/2022, 11:09 AM: 

(private comment, text removed)
#### Teroneko on 8/3/2022, 01:00 PM: 

(private comment, text removed)

**Comment by ryzngard** [comment] 2022-08-03 20:11
Was able to reproduce in latest 17.3 builds. The "Rename symbol's file" checkbox state is always getting reset

**Comment by teneko** [comment] 2022-10-02 21:10
Most of the times I am not one of these asking for progress, but I am surprised. Am I only hitting this problem?? Is no one ever renaming classes and files and gets annoyed by filename<->class name diffs? Would love to see some progress. I am facing this problem for months now.

**Comment by CyrusNajmabadi** [comment] 2022-10-02 22:18
> Would love to see some progress. I am facing this problem for months now.

@teneko Roslyn gladly accepts community PRs for issues people are passionate about :)

**Comment by ryzngard** [comment] 2022-10-03 01:29
This was fixed with #63827 , I just missed duping the bugs together. There are also lightbulb fixes to help in cases where file and classname differ even if the checkbox is not checked.

**Comment by teneko** [comment] 2022-10-04 03:05
@CyrusNajmabadi Normally I absolutely aggree to you, but I see myself more as a consumer of Visual Studio and I cannot identify myself with Roslyn. I am fan of dotnet/runtime, dotnet/msbuild, dotnet/ef6 and many others but I had no touching point with dotnet/roslyn and it would take time to get into the topic. Time I don't have.

@ryzngard Thanks for taking your time. I just checked your suggestion and you are right: I never recognized the "Rename file to" or "Rename class to" lightbulb feature. I think because I always use the rename feature do two two jobs in one and having the security the file name matches the class name automatically. Thanks for the tip.

**Comment by ryzngard** [comment] 2022-10-10 21:40
@teneko I'm going to close this as a fixed by #63927 which will release with 17.4 Preview 3

**Closed by ryzngard** 2022-10-10 21:40 UTC
Labels: Area-IDE

**Comment by roryap** [comment] 2022-12-31 14:55
@ryzngard 	in your last comment (Oct 10) you link to 63927 -- did you mean 63827?

**Comment by ryzngard** [comment] 2022-12-31 20:10
Yes! Got it right the first time and then typoed. 63827 is the correct pr
