### ISSUE TITLE
Block structure incorrect when using proportional font

### ISSUE THREAD

**Issue by breyed** [dotnet/roslyn#18365] opened 2017-04-01 16:35 UTC
When the F# text editor uses a proportional font, the block structure shows extra lines, sometimes in addition to, sometimes in place of, the desired lines.

#### Repro steps

1. Set the Text Editor font to Calibri.

2. Create an F# file with this code:

```
module test
open System

let x =
    if 3 = 4 then
        5
    else
        6

```

#### Expected behavior

Two block structure vertical lines, like you get if you're using Consolas.

#### Actual behavior

A third, middle block structure line between the two standard ones. Before the `let` line, only this middle line appears.

#### Known workarounds

Use a non-proportional font and buy a wider monitor. :-)

#### Related information 

[Readability data](http://ux.stackexchange.com/q/48753/79277)

**Comment by vasily-kirichenko** [comment] 2017-04-01 17:23
A screenshot would be a great addition.

**Comment by breyed** [comment] 2017-04-01 18:51
![consolas](https://cloud.githubusercontent.com/assets/1299073/24581494/3d31c1e8-16e2-11e7-9880-19d37b019a5b.PNG)
![calibri](https://cloud.githubusercontent.com/assets/1299073/24581496/41abb01c-16e2-11e7-812f-6cd4c8a195dc.PNG)

**Comment by CyrusNajmabadi** [comment] 2017-04-01 18:55
I'm going to get the editor guys to come take a look.

**Comment by vasily-kirichenko** [comment] 2017-04-01 19:02
@breyed is it reproduced in C# editor as well? (just to be sure it's not a F# editor bug. It's very unlikely, but still).

**Comment by gundermanc** [comment] 2017-04-01 19:11
Hi all, I am looking now. I haven't yet seen a repro for C#, VB, or TextMate in RTW or 15.3 bits yet. I'm spinning up an F# install now.

**Comment by breyed** [comment] 2017-04-01 19:27
I have not encountered a repro for C# either. Scanning through some existing code and trying a some variations with LINQ expressions and spaces vs. tabs didn't turn up anything either.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 19:33
If this turns out to be F# specific that will enormously weird me out :)  All F# is doing is passing back data through the roslyn subsystem...

**Comment by vasily-kirichenko** [comment] 2017-04-01 19:44
Hmm. It works pretty good for me

![image](https://cloud.githubusercontent.com/assets/873919/24581884/b32fc3a0-172c-11e7-9805-9845235afb2f.png)

![image](https://cloud.githubusercontent.com/assets/873919/24581886/cdbd0052-172c-11e7-9189-ac677cf29538.png)

**Comment by gundermanc** [comment] 2017-04-01 19:45
Ok I have determined the root cause. Technically, both the editor and F# are doing the right thing, but we've hit an edge case. There is a structure adornment added to the editor for `module test` as well as for `let x = ...`, which is not indented.

By default, the editor horizontally centers the block adornment on the anchor character for the block (in this case, the 'm' in module, and 'l' in let respectively). In Consolas, both characters have equal width, so, the adornments for the module and the let block overlap and appear to be a single line. In Calibri, however, 'm' is wider than 'l', causing the adornment for the module block to be a few pixels right of the adornment for let, hence the 3rd adornment that you're seeing.

There are a couple of options moving forward:

- F# could disable block adornments for modules (or disable them only with non-variable width fonts). This would be my preference, as the module contents don't seem to be indented by convention, so the adornments usually overlap and don't afford much additional information.
- Editor could change the adornments to be horizontally positioned at the left-most pixel of each character. This would ensure that the adornments for modules and it's top-level children always overlap, but I always felt that this positioning was a bit less visually appealing than centering on each character.
- Editor could allow the language service to explicitly set the positioning mode as centered, left-most pixel per character, or right-most pixel per character.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 19:50
> F# could disable block adornments for module

I'm opposed to any fix that requires individual languages to have to know to do this for any of their constructs.  It would require languages to know that such an issue exists, and that certain combinations of characters in certain fonts woul dhave a problem.

That's precisely something we want languages to not have to think about, and why roslyn attempts to hide any information about your editor and only asks for raw data from languages.  It allows languages to focus on language analysis and keeps editor related integration and related issues isolated.

--

I feel like the appropriate *4th* option would be:

4. If the editor is drawing a line for a character in a particular column, it chooses the middle location (as that is aesthetically pleasing).  If below it, it runs into a letter that starts at the same horizontal position, and wants a structure guide as well, then it overrides the "middle location heuristic" for that letter, and uses the horizontal location of the outer line so that the lines overlap.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 19:52
In other words, once the editor picks a horizonal starting position X1 for the structure guide S1 for a character starting at a certain horizontal position X2, then all other structure guides for characters starting at X2, that are in the span of S1 should also have their structure guide start at X1.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 20:10
Note: looking at the actual code issue, i think my solution is suboptimal.  Specifically, the line drawn under 'm' will be too far to the right for the structure guide for 'let'.  I would revise my algorithm to say that:

For all structure lines drawn for characters with the same starting 'x' position, teh structure guides should all be drawn on the horizontal position of the leftmost guide.  So, in the above case, we would pick the middle point of 'l' in 'let' as the the preferred horizontal position, and the structure guide for the 'm' in 'module' would be drawn at the same horizontal location as well.

**Comment by gundermanc** [comment] 2017-04-01 21:24
Although we can implement the change that you suggest, I think that we'll find that depending on the lines overlapping will bring a whole host of issues that will cause bugs in other edge cases and limit what we can do with the feature in the future. For example:

- Introducing transparency into the structure guide line style would cause lines that overlap to be darker in color. Adopting the proposed fix requires committing to never using transparency in the line styles (which would be unfortunate because we have received some feedback that they are a bit too high contrast).
- The lines appearing correctly depends on them overlapping precisely, which they currently do because most fonts are rendered such that each line is the same height. However, if a user installs an extension that changes the line height for some lines and not others, the dotted lines will not overlap perfectly and will cause an irregular dotting pattern. I can't find the link right now, but I have seen extensions that make method headers a larger font than the surrounding lines, that would not look good in this case.
 - The editor renders structure guide lines as adornments in an adornment layer. We don't really have a story for overlapping adornments in a single layer, so, if we change the line style based on semantics, similar to what the VS PPT does, depending on which order the adornment layer chooses to draws the adornments, the module line could cover up the let lines. Presumably, any adornment drawn later will cover up previous adornments, but for this to work, it requires either well defined ordering of structure tags from the language service + tag aggregator, or it requires us to explicitly sort the tags and add the adornments to the layer in a specific order.
- With overlapping adornments, the choice of which adornment to show the tooltip for is now ambiguous. The current behavior is to choose the first one that is under the mouse cursor when iterating the set of visible adornments, but there is no consistent ordering, so the tooltip content displayed is not guaranteed to be consistent.

Some of the issues mentioned above can be corrected within the editor by adding awareness of order, but we already have heuristics in place for doing things like skipping lines that intersect text. Any work done here has to be re-done on keystroke, potentially incurring additional typing delay, so I would very much discourage any solution that requires the editor to do additional work.

The adornments were originally conceived to help show structure in indented blocks of code, so, in situations in which there is by-convention no indentation, I think it makes sense to omit the adornment. 

If fixing this from the Roslyn or F# side is impractical, I'll start a thread with the editor folks and see what we can do.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 22:57
> Introducing transparency into the structure guide line style would cause lines that overlap to be darker in color.

Why?  We can choose whatever we want with overlapping.  My expectation would be that overlapping would not cause any darkening.

>The lines appearing correctly depends on them overlapping precisely, which they currently do because most fonts are rendered such that each line is the same height. However, if a user installs an extension that changes the line height for some lines and not others, the dotted lines will not overlap perfectly and will cause an irregular dotting pattern. 

I think the overall intuition should be:

If a nested block has a structure guide at the same horizontal position as a containing guide line, there is simply no need to draw the nested guide.  

Note that seems like something that could be done either at the editor layer quite easily.  Indeed, it seems like it doesn't even need to be based on the horizontal pixel position, but could just be done based on the column of the structure guide.  Why draw the nested structure guide if it is subsumed by some parent block?

Note that this also handles the transparency issue you mentioned.

**Comment by CyrusNajmabadi** [comment] 2017-04-01 23:00
IMO, this would be a reasonable change to do at teh editor layer.  One thing that makes it hard for the roslyn layer is that we have no concept of 'view' here, and the view is necessary to really make a determination about which 'column' of the screen you're on.  The editor, however, knows about teh view, the columns, and the nesting structure of the blocks.  So it could simply say "if this nested block wants the structure guide at the same column of a parent block, then just don't bother with it at all.  You just get the structure guide for the parent."

This also addresses your concern about what you would see when you hover on the guide-line.  With this rule you always see the largest node (which seems sane and sensible to me).

**Comment by CyrusNajmabadi** [comment] 2017-04-01 23:03
> If fixing this from the Roslyn or F# side is impractical, I'll start a thread with the editor folks and see what we can do.

IMO, it's completely impractical at the language level.  It requires nodes to understand what final column they will be rendered at in the UI.  That is dependent on things like tab-expansion and whatnot.  i.e. if i have:

```c#
<space><space><space><space>module
<tab>let
```

then those may or may not be at the same columnar location depending on the view settings.  Roslyn technically has this information and can compute it.  but then that would only help roslyn languages.  If the editor just adopts this idea, then all languages get this for free.

**Comment by breyed** [comment] 2017-04-01 23:37
Worth noting is that while F# programs typically use whitespace only for indentation, F# supports the older verbose syntax that is whitespace agnostic, and so allows mixed tabs and spaces. This verbose syntax, like other whitespace agnostic languages such as C#, benefits from block structure highlighting. Additionally, other languages such as Python do allow tabs even where whitespace indentation is significant (although I'm not sure about the rules on mixing tabs and spaces), and nothing stops F# from one day supporting tab indentation, too.

**Comment by Pilchie** [comment] 2017-04-03 23:01
@CyrusNajmabadi assigning to you to track doing the right thing with @gundermanc

**Comment by CyrusNajmabadi** [comment] 2017-07-12 19:24
@gundermanc Is there any more information you need on this?  Or were the suggestions sufficient to be able to do something about this?  Thanks!

**Comment by CyrusNajmabadi** [comment] 2023-02-07 19:11
Closing out as this is not on roslyn.  Up to editor to decide if anything should be done here.

**Closed by CyrusNajmabadi** 2023-02-07 19:11 UTC
Labels: Bug, Area-IDE
