### ISSUE TITLE
Allow to configure spacing around unary operators for Code Style rules in .editorconfig

### ISSUE THREAD

**Issue by macrogreg** [dotnet/roslyn#55721] opened 2021-08-19 12:34 UTC
**Brief description:**

Allo to configure spacing around unary operators .editorconfig, in particular, around the NOT (`!`) operator.
For example, it should be possible to configure any of the following:

* Require space:
```cs
// Valid formatting:
if (! isSomeConditionApplicable)
{
    DoStuff();
}

// Invalid formatting:
if (!isSomeOtherConditionApplicable)
{
    DoMoreStuff();
}
```

* Require NO space:
```cs
// Invalid formatting:
if (! isSomeConditionApplicable)
{
    DoStuff();
}

// Valid formatting:
if (!isSomeOtherConditionApplicable)
{
    DoMoreStuff();
}
```

* Allow both:
```cs
// Valid formatting:
if (! isSomeConditionApplicable)
{
    DoStuff();
}

// Valid formatting:
if (!isSomeOtherConditionApplicable)
{
    DoMoreStuff();
}
```

**Languages applicable:**

C#

**Additional information:**

This is a Code Formatting option that should be added to the existing white space options.
This is a readability issue and I have seen many code bases that use a space between a `!` and the following expression. Particularly, when the expression starts with characters such as `i` `I` or `l`, the exclamation is particularly hard to spot or differentiate, and adding a space is critical for readability.

This is particularly important for dyslexic people. Dyslexia makes it very hard to differentiate similar looking characters, and allowing to highlight the negation using spaces is critical to include the needs of the affected developers in Coding Style guidelines.

In our code base we have to fall back to very "ugly" workarounds such as
```cs
if (false == IsSomething) { ... }
```
```cs
if (!(IsSomething)) { ... }
```

which is both, unfortunate.

Please add support for the required .editorconfig configuration option.

Thank you.

**Comment by sharwell** [comment] 2021-08-19 16:50
> This is particularly important for dyslexic people. Dyslexia makes it very hard to differentiate similar looking characters, and allowing to highlight the negation using spaces is critical to include the needs of the affected developers in Coding Style guidelines.

Dyslexic developers should not be placed at a disadvantage due to code style choices made by project developers. For a user who needs the additional space described above for the purpose of reading code, it should be possible to _render_ that space (e.g. with a space negotiating intra-line adornment with no content like we use for the <kbd>Alt</kbd>+<kbd>F1</kbd> feature) without forcing other users of the project to adopt the same style.

**Comment by sharwell** [comment] 2021-08-19 16:55
Duplicate of #54921

**Closed by sharwell** 2021-08-19 16:55 UTC
Labels: Area-IDE, Feature Request, untriaged
