### ISSUE TITLE
ArgumentOutOfRangeException throw by AbstractDiagnosticsTaggerProvider.ProduceTags

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#21301] opened 2017-08-03 02:12 UTC
**Version Used**: 15.0.26430.16, 15.0.26711.1 or 15.0.26430.15 

Found walking through customer's crashes.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.TaggerProvider.ProduceTags(TaggerContext`1 context, DocumentSnapshotSpan spanToTag)
   at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.TaggerProvider.ProduceTagsAsync(TaggerContext`1 context, DocumentSnapshotSpan spanToTag, Nullable`1 caretPosition)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.<ProduceTagsAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__83.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessInnerTask(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessCompletedOuterTask(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeCore(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"
```

**Comment by davkean** [comment] 2017-08-03 02:35
These two also are duplicates of this: 

https://developercommunity.visualstudio.com/content/problem/38898/devenvexe-systemargumentoutofrangeexception.html.
https://developercommunity.visualstudio.com/content/problem/47296/silent-crash-when-cutting-text-by-ctrlx.html

**Comment by Pilchie** [comment] 2017-08-03 17:55
@heejaechang @CyrusNajmabadi this is a dupe of an internal bug, right?

**Comment by heejaechang** [comment] 2017-08-03 18:05
let me take a look

**Comment by heejaechang** [comment] 2017-08-03 18:49
@davkean @Pilchie do we have a dump? both link seems doesn't have a link?

**Comment by davkean** [comment] 2017-08-03 23:06
I only saw above looking at customer's event log - if you want dumps, you'll probably need to dig through/request them via watson.

**Comment by Pilchie** [comment] 2017-08-08 21:23
@heejaechang - is this https://devdiv.visualstudio.com/DevDiv/_workitems/edit/428328 ?

**Comment by heejaechang** [comment] 2017-08-08 21:25
could be, but I did this so it shouldn't happen anymore.. not sure whether this got into 15.3 or not though.

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.TaggerProvider.cs,85

**Comment by Pilchie** [comment] 2017-08-11 00:37
It does NOT look like it's in 15.3, seeing as how this [commit](https://github.com/dotnet/roslyn/commit/27b4c3809776dac6a96569c187dbbb129e176a12) is currently only in `master`

**Comment by davkean** [comment] 2017-08-11 00:39
Even if it is a NFW post 15.3 - we still want to fix the underlying cause, right?

**Comment by heejaechang** [comment] 2017-08-11 00:45
sure. once we have dump that tell us what is giving the wrong span. we can fix it. right now, we don't exactly know how this can happen.

**Comment by davkean** [comment] 2017-08-11 00:46
Have you requested dumps on the associated watson?

**Comment by heejaechang** [comment] 2017-08-11 16:33
that is probably question to @tmeschter ?

**Comment by kamenlitchev** [comment] 2017-09-28 09:57
Happens in latest VS (15.3.5). How do I get Watson dump? I only get dialog that crash report was generated as ActivityLog.xml

**Comment by jinujoseph** [comment] 2017-11-08 09:57
also reported at https://developercommunity.visualstudio.com/content/problem/145998/systemargumentoutofrangeexception-when-editing-c-c.html

**Comment by heejaechang** [comment] 2017-11-08 16:37
@jinujoseph @ivanbasov 2 are different issues.

for this, I moved explicitly to NFW
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.TaggerProvider.cs,85

crash can't happen anymore.

the other bug you linked is happening on syntax tagger not diagnostic tagger. sound like issues are not tagger but something is wrong in workspace.

**Comment by vd1972** [comment] 2018-03-02 18:19
Is this issue has any solution?

**Comment by heejaechang** [comment] 2018-03-02 19:08
@vd1972 is this still repro? I believe it is fixed in latest VS. fix should be in 15.6 (Preview)

**Comment by heejaechang** [comment] 2018-03-02 19:08
fixed - https://github.com/dotnet/roslyn/pull/23448

**Closed by heejaechang** 2018-03-02 19:08 UTC
Labels: Area-Analyzers, Bug, Developer Community

**Comment by jaydeepbhowmik1982** [comment] 2018-06-23 07:10
I have same issue for some days. After run window update. While copy some code or press delete button, VS crashed.

**Comment by heejaechang** [comment] 2018-06-25 23:19
@jaydeepbhowmik1982 can you provide us a dump?
