### ISSUE TITLE
Test `AddProjectReferenceBetweenMixedLanguages1` is flaky

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9316] opened 2016-02-29 23:46 UTC
```
Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddMissingReference.AddMissingReferenceTests.AddProjectReferenceBetweenMixedLanguages1 (from Roslyn.Services.Editor.UnitTests2)

Failing for the past 1 build (Since Failed#4562 )
Took 14 ms.
Stacktrace

MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_10_TestAddProjectReferenceAsync.MoveNext() in d:\j\workspace\roslyn_prtest---345e02d2\src\EditorFeatures\Test2\Diagnostics\AbstractCrossLanguageUserDiagnosticTest.vb:line 135 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddMissingReference.AddMissingReferenceTests.VB$StateMachine_9_AddProjectReferenceBetweenMixedLanguages1.MoveNext() in d:\j\workspace\roslyn_prtest---345e02d2\src\EditorFeatures\Test2\Diagnostics\AddMissingReference\AddMissingReferenceTests.vb:line 71 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

@dotnet/roslyn-infrastructure

**Comment by heejaechang** [comment] 2016-03-02 21:25
@srivatsn @Pilchie is this update 2 bug or regular bug?

**Comment by Pilchie** [comment] 2016-03-02 21:29
In general, we'd like to drive down flakiness in tests for 1.2 if possible, since it improves our ability to validate the release.

In this particular case, this is likely the same issue that @jasonmalinowski is already investigating

**Comment by davkean** [comment] 2016-03-07 00:24
@jasonmalinowski Do you think this is the same cause that @TyOverby just fixed?

**Comment by davkean** [comment] 2016-03-07 00:42
Dupe of https://github.com/dotnet/roslyn/issues/9308

**Closed by davkean** 2016-03-07 00:42 UTC
Labels: Area-Analyzers, Flaky, Test

**Comment by jasonmalinowski** [comment] 2016-03-07 18:41
It's definitely plausible.

**Comment by jasonmalinowski** [comment] 2016-03-07 18:42
It's definitely plausible. We had a hit yesterday in master but we didn't hook up the logging to that particular test so we can't say for certain either way. I have no problem with closing this.
