### ISSUE TITLE
Can't type after add using

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5843] opened 2015-10-09 22:53 UTC
I'm using Add Using on one of our most dogfooding builds. After add using, the caret disappears from the editor, and I can no longer type characters. However, tab and shift-tab will still insert and remove tabs.

I have a video on our share under public\rchande\lightbulb.MOV. I apologize for the video in lieu of a gif, but the bug doesn't repro under screen to gif.

**Comment by rchande** [comment] 2015-10-09 22:54
If you watch the video, you'll see I apply a fix, which goes in, and the caret stops blinking. I mash the keyboard for a while and nothing happens, but then I start inserting and removing tabs (watch the visible whitespace).

**Comment by Pilchie** [comment] 2015-10-12 16:26
Tagging @olegtk and @markw-t.  Are there any known issues here with RTM bits?

**Comment by dpoeschl** [comment] 2015-10-12 22:37
This is happening to me now too every time I add using (!)

**Comment by dpoeschl** [comment] 2015-10-12 22:42
Rename Tracking _with preview_ exhibits the problem, but Rename Tracking _without preview_ does not.

**Comment by balajikris** [comment] 2015-10-14 17:16
I have a reliable repro: 
1. Have a (any) tool window floating and not docked and set focus to it by clicking on it.
2. The move focus to the editor, bring up a (any) quick action and wait until the preview pane is shown.
3. commits the fix
4. further inputs from keyboard no longer go to the editor, unless its a TAB or RETURN from what I've observed.

Notes:
1. if one didn't visit a tool window before shifting focus to editor, this problem doesn't seem to appear.
2. this problem will also not appear, if one didn't wait for the preview to show before applying the quick fix.

**Comment by balajikris** [comment] 2015-10-14 17:43
![editorfocuslost](https://cloud.githubusercontent.com/assets/4213867/10492357/6d756e72-7260-11e5-9125-bfb6fdd4143e.gif)

**Comment by balajikris** [comment] 2015-10-14 18:03
confirmed with the editor team that is a dupe of something that's known and fixed in Update 1.
115988 is the original bug in the internal database.

**Closed** 2015-10-14 18:03 UTC
Labels: Area-IDE, Bug
