### ISSUE TITLE
Inheritance margin interferes with breakpoints

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#55353] opened 2021-08-02 22:08 UTC
**Version Used**: Version 17.0.0 Preview 4.0 [31601.41.main]

**Steps to Reproduce**:

1. Have a single-line expression-bodied member that inherits or implements a containing type member.
2. Attempt to set a breakpoint in that member

**Expected Behavior**:

There is a clickable location a breakpoint can be set in, and the icons do not interfere.

**Actual Behavior**:

There is no clickable margin location, and creating a breakpoint via a command (using vsvim) then has the inheritance margin and breakpoint icons overlapping and interfering.
![image](https://user-images.githubusercontent.com/2371880/127929812-68143146-8591-4750-89ee-dc5b0117bf98.png)

**Comment by Youssef1313** [comment] 2021-08-03 08:38
Duplicate of #55056

**Comment by 333fred** [comment] 2021-08-03 15:05
I don't think this is quite a duplicate, because I'm also reporting the inability to _set_ a breakpoint.

**Comment by sharwell** [comment] 2021-08-06 16:11
📝 Note that <kbd>F9</kbd> still works to toggle the breakpoint.

**Comment by Cosifne** [comment] 2021-08-06 21:51
We also have similar feedback here https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1346626/

Right now Inheritance Margin always handles the click event before the debugger. And since both of them are using the same margin, when the margin is clicked, either the breakpoint or inheritance margin would handle the event. (e.g. you can't set a breakpoint and open the inheritance margin by only one click)

For the time being, I think the fix should be
1. When such a case happens, let breakpoint handles the mouse click first. (Based on the feedback posted above and Fred's issue here, breakpoint looks like a more important function)
2. We should have a command so that Inheritance Margin could be open by using the keyboard.

By doing so, user should be able to do everything by using keyboard short-cut. 

And if later we still receive a lot of feedback around the overlapping we should consider moving the inheritance margin to a separate column in the editor.

FYI @sharwell @mikadumont

**Comment by Cosifne** [comment] 2021-08-31 17:37
We have a new option to control the position of the margin so close this

**Closed by Cosifne** 2021-08-31 17:37 UTC
Labels: Bug, Area-IDE, IDE-Navigation, Navigation-Inheritance Margin
