### ISSUE TITLE
Fixer that fixes name violation doesn't appear to work for WithEvents

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15755] opened 2016-12-08 07:49 UTC
I've previously filed the bug around this firing on withevents "fields" in the first place - but even if I wanted to fix this, it doesn't appear that you can:

![image](https://cloud.githubusercontent.com/assets/1103906/21001780/6cadeb60-bd76-11e6-9700-aed976113883.png)

Note there's no Preview? If I click Fix Name Violation, nothing visibly happens to the file (however, "Git Changes window things that the file has been modified in memory - as it appears in its changes list)

**Comment by miloush** [comment] 2016-12-12 15:28
This is an interesting case of #15464 resp. #15326. I guess the fix just tries to call ToUpperCase on the underscore and nothing really happens.

**Comment by Pilchie** [comment] 2016-12-12 21:43
See also https://github.com/dotnet/roslyn/issues/10111 for more needed handling of `_`.

**Comment by Pilchie** [comment] 2017-01-19 01:11
Dupe of #10111 + https://github.com/dotnet/roslyn/issues/15343 causing the field to be interpreted as a property.

**Closed** 2017-01-19 01:12 UTC
Labels: Area-IDE, Bug
