### ISSUE TITLE
[Regression] Naming style rules are no longer being enforced or used

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#36353] opened 2019-06-12 06:56 UTC
This works in 15.9 & 16.1.2 and has regressed in Version 16.2.0 Preview 3.0 [29010.160.d16.2stg].

EditorConfig: https://github.com/dotnet/project-system/blob/master/.editorconfig#L115.

Naming style rules (at least for fields) are no longer being enforced or used.

15.9/16.1.2:
![image](https://user-images.githubusercontent.com/1103906/59329588-93427c80-8d32-11e9-8f92-c1c1f13418da.png)

16.2:
![image](https://user-images.githubusercontent.com/1103906/59329652-b705c280-8d32-11e9-9a95-373ce846ff07.png)

The warnings are 16.2 are the new ones telling me that they can be literals.

**Comment by davkean** [comment] 2019-06-12 07:15
This may or may not be related: https://github.com/dotnet/roslyn/issues/36355.

**Comment by sharwell** [comment] 2019-06-12 13:52
@davkean Are you using the compiler's implementation of .editorconfig or the editor's? In the new compiler implementation, keys in the .editorconfig file are unordered. The priority of naming rules is determined from the order in which they appear in the .editorconfig model, so when using the compiler implementation they will be evaluated in an unspecified order.

We are working to find a solution, but the new API does not offer information about the original order of keys so it will not be possible to *strictly* preserve behavior.

**Comment by sharwell** [comment] 2019-06-12 14:49
Duplicate of #36355

**Closed by sharwell** 2019-06-12 14:49 UTC

**Comment by jasonmalinowski** [comment] 2019-06-12 22:49
This may not have been a duplicate: @davkean was included in the internal flighting of deferring to the compiler data, but his repo doesn't have the MSBuild flag enabled so his .editorconfigs would have been ignored in that case.
