### ISSUE TITLE
error VSTHRD010 errors are not displayed in the error list (17.4.0 RTM)

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#65304] opened 2022-11-09 17:11 UTC
**Version Used**: 
17.4.0 RTM

**Steps to Reproduce**:

1. Add a ThreadHelper.ThrowIfNotOnUIThread(); to some method that might be called from a background thread.
2. Build
3. Expect to see a VSTHRD010: Accessing "Microsoft... error in the error list.
4. Don't (though I do see it in the build output.

**Expected Behavior**:
Error shows up in both error list and build output.

**Actual Behavior**:
Only shows up in build output.

11>StandaloneModelLoader -> B:\dd\IntelliCode-VS3\bin\Debug\StandaloneModelLoader\StandaloneModelLoader.exe
9>RefactoringsTest -> B:\dd\IntelliCode-VS3\bin\Debug\RefactoringsTest\RefactoringsTest.dll
2>InlineSuggestions -> B:\dd\IntelliCode-VS3\bin\Debug\InlineSuggestions\Microsoft.VisualStudio.Internal.InlineSuggestions.vsix
13>B:\dd\IntelliCode-VS3\src\VSIX\IntelliCode.VSIX\SuggestionService\Implementation\SuggestionBroker.cs(865,22,865,37): error VSTHRD010: Accessing "Microsoft.VisualStudio.IntelliCode.SuggestionService.Implementation.SuggestionBroker.UpdateScopeTags" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.
13>Done building project "IntelliCode.VSIX_gn0nj2rv_wpftmp.csproj" -- FAILED.
13>Done building project "IntelliCode.VSIX.csproj" -- FAILED.
14>------ Rebuild All started: Project: IntelliCode.VsPackage.UnitTests, Configuration: Debug Any CPU ------
12>ModelServiceTest -> B:\dd\IntelliCode-VS3\bin\Debug\ModelServiceTest\ModelServiceTest.dll
12>Done building project "ModelServiceTest.csproj".
10>ModelInference -> B:\dd\IntelliCode-VS3\bin\Debug\ModelInference\ModelInference.dll
10>Done building project "ModelInference.csproj".
15

**Comment by Youssef1313** [comment] 2022-11-09 18:29
One thing to note is that VSTHRD010 is a compilation-end analyzer.

https://github.com/microsoft/vs-threading/blob/a83e88dac6a824cd80e8ad6024b29a473ca2e270/src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs#L154

**Comment by CyrusNajmabadi** [comment] 2022-11-09 18:30
Good point @Youssef1313 .  However, i would still expect them to show up in the build-errors-list.  @mavasani how should this work?

**Comment by Youssef1313** [comment] 2022-11-09 18:35
> Good point @Youssef1313 . However, i would still expect them to show up in the build-errors-list. @mavasani how should this work?

Yeah I'd expect it to work. I pointed that out in case the issue is specific to compilation end.

**Comment by mavasani** [comment] 2022-11-10 07:30
@Youssef1313 It seems the descriptor doesn’t have the CompilationEnd tag: https://github.com/dotnet/roslyn/blob/440b6fc370f0ddcea68b445e183f1383c0d1bc6e/src/Compilers/Core/Portable/Diagnostic/WellKnownDiagnosticTags.cs#L56

we use this tag to identify build only diagnostics for live-build de-duping. We should do couple of things here:

1. Fix the descriptor above to add this tag.
2. Add a new RSxxxx diagnostic to our MS.CA.Analyzers package to flag any descriptor without this custom tag being used to report a diagnostic on CompilationEndContext

**Comment by mavasani** [comment] 2022-11-21 05:31
Closing this issue as relevant issues have been filed in the respective repos - see https://github.com/dotnet/roslyn/issues/65304#issuecomment-1309882140

**Closed by mavasani** 2022-11-21 05:31 UTC
Labels: Area-IDE
