### ISSUE TITLE
C# - A breakpoint cound not be inserted at this location because of comments and #regions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23666] opened 2017-12-08 08:24 UTC
The following source code does compile and run, but it is not possible to set a breakpoint in VS 2017.
It seems to be related to the extra line break in the comment within a #region.

Here is the code:
```
using System;

namespace NoBreakpointSet
    {    
    public class Program
        {

        #region Methods

        /// &lt;param name=&quot;args&quot;&gt;      

        ///&lt;/param&gt;             
        public static void Main(string[] args)
            {
            Console.WriteLine(&quot;Unable to set breakpoint here.&quot;);
            }
    
        #endregion
        }
    }
```

WIthout the line-break between the two ///-comments everything is ok.

Intellisense also shows an error message &quot;CS1028	Unexpected preprocessor directive&quot;
at the #endregion line.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/137023/c-a-breakpoint-cound-not-be-inserted-at-this-locat.html
VSTS ticketId: 513856_
_These are the original issue comments:_

Jinu Joseph [MSFT] on 10/26/2017, 07:10 PM (42 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2017-12-08 22:31
I'm not able to repro in 15.6 preview 1.
As the screenshot shows, a breakpoint can be set on the `WriteLine` statement. I'm also able to debug this method, automatically break at the breakpoint, and step through. The behavior is the same whether there is an empty line the xml docs or not.

Let's confirm repro with customer.

![image](https://user-images.githubusercontent.com/12466233/33787801-d002d802-dc23-11e7-9482-a1cfa5965290.png)

![image](https://user-images.githubusercontent.com/12466233/33787838-faa1ba7e-dc23-11e7-9b23-f8e95f1a5229.png)

Also works in a console app project (with a Main method):

![image](https://user-images.githubusercontent.com/12466233/33787921-4e99482c-dc24-11e7-8a3c-f45d8a3a8855.png)

**Comment by jcouv** [comment] 2017-12-15 23:27
I'm not able to reproduce with the information provided. I pinged the customer (Marco) on the community issue above in case he has something to add.
In the meantime, I'll close this issue as No Repro. We can re-open if new information unblocks the investigation.

**Closed by jcouv** 2017-12-15 23:27 UTC
Labels: Need More Info
