### ISSUE TITLE
Method group syntax doesn't produce optimized code like equivalent lambda/delegate

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#43785] opened 2020-04-29 16:36 UTC
**Version Used**: 16.7.0 Preview 1 (30028.18.master)

**Steps to Reproduce**:

Pass a method group as the argument to a method that accepts a delegate.

[SharpLab repro](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwDoAqAFgE4CmAhjGAHYDmA3ALABQzyAzJgEzoDC6A3s3TDMAFnQBZEsAIB7GAHEisgK4AHABQ8yVAMYkIEMsDCyqeWQGsSVdLuABKAUJGv7OAEokaYAM7ASIg0AMVlZKHQqFUMHRiZXAF8XYWSxdAAZMgBbACMYMi0dfUNjU3MrGztHZ3jXEXcvH39AjV8AXgA+UNlWhwiomLjE1NS1IjAAN2MSTCwANjTujVkcgCsSe3RfJ350JKYEoA==)

**Expected Behavior**:

Optimized IL should be generated to cache and reuse the allocated delegate when possible.
This would match the optimization the compiler offers for lambdas/delegates.

**Actual Behavior**:

Passing a method group as an argument that accepts takes a delegate results in a delegate allocation on every iteration.
Simply changing the syntax to a lambda or delegate that invokes the same method used in the method group causes the C# compiler to generate more optimized code where the delegate is only allocated once and stored in a static field for reuse on the next invocation.

**Comment by Therzok** [comment] 2020-04-29 17:30
Duplicate of https://github.com/dotnet/roslyn/issues/5835

**Comment by CyrusNajmabadi** [comment] 2020-04-29 19:54
Closing as dupe.

**Closed by CyrusNajmabadi** 2020-04-29 19:54 UTC
