### ISSUE TITLE
Code Formatting option to enforce using directive inside a namespace

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/roslyn#34008] opened 2019-03-11 01:20 UTC
Apologies if I missed this. I did my best to search through issues.

Both Resharper and StyleCop had formatting rules where they could enforce using directives to be placed inside the namespace.

At the moment Visual Studio lets me place using directives inside the namespace and it works fine with them when refactoring but it does not let me *enforce* that all using directive *should* be inside a namespace.

**Comment by CyrusNajmabadi** [comment] 2019-03-11 07:53
@oliverjanik You can write such a rule yourself.  Or you can just use StyleCopAnalyzers: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1200.md

**Comment by oliverjanik** [comment] 2019-03-11 10:54
How can I make a rule so that it get's auto-formatted not just highlighted?

**Comment by sharwell** [comment] 2019-03-11 13:19
This is currently being implemented by @JoeRobich in #30760.

**Comment by sharwell** [comment] 2019-03-11 13:20
Duplicate of #27179

**Closed by sharwell** 2019-03-11 13:20 UTC

**Comment by sharwell** [comment] 2019-03-11 13:21
> Apologies if I missed this. I did my best to search through issues.

No problems here. We've all had this happen too. 😄
