### ISSUE TITLE
When XML doc generation is off, namespaces used by crefs are treated as unused

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4034] opened 2015-07-21 20:53 UTC
When XML doc generation is off, namespaces used by crefs are greyed out indicating that are they are unused:
![image](https://cloud.githubusercontent.com/assets/1103906/8812139/336f55ce-2faf-11e5-8982-d8f0d1bf3999.png)

I'm also offered to remove ```using System``` despite it actually being used by the cref.

I'm not sure if this by design or not (or rather a fallout of how this was designed), but this seems incorrect, especially as the colorizer appears to be processing them (if we're not processing them, why we run the colorizer over them?).

**Comment by gafter** [comment] 2015-07-21 21:54
We should probably disable reporting unused usings when we are not processing doc comments.

**Comment by dotnetjunkie** [comment] 2015-07-30 14:52
Do note that this refactoring will cause a compile error once you switch to a configuration that generates XML docs (which is typically what you do in a release build).

**Comment by sharwell** [comment] 2015-07-30 15:06
Duplicate of #2773.

**Closed** 2015-07-31 20:41 UTC
Labels: Area-Compilers, Resolution-Duplicate

**Comment by jnm2** [comment] 2016-12-30 11:58
If removing the `using` causes an error, it should not be suggested. Please fix.

If the only correct solution is truly to enable XML doc generation, then please **stop suggesting removal of the using** and **start suggesting enabling XML documentation output**.

This may be a moonshot, but in an ideal world, I think I should be able to leave XML documentation output off and still have all the syntax checking as though it was on.

**Comment by jnm2** [comment] 2016-12-30 12:00
If removing the `using` breaks a cref, it should not be suggested. Please fix.

Currently this results in bouncing back and forth between ReSharper complaining  that you should add the using for the XML documentation and Roslyn complaining that you should remove it. It's a bad user experience.

If the only correct solution is truly to enable XML doc generation, then please **stop suggesting removal of the using** and **start suggesting enabling XML documentation output**.

This may be a moonshot, but in an ideal world, I think I should be able to leave XML documentation output off and still have all the syntax checking as though it was on.

**Comment by gafter** [comment] 2017-01-01 07:16
@jnm2 discussion has moved to #2773

**Comment by jnm2** [comment] 2017-01-01 23:52
@gafter Thanks. [Moved the comment.](https://github.com/dotnet/roslyn/issues/2773#issuecomment-269925184)
