### ISSUE TITLE
"Move to <type>.cs" operation should open the new file in the editor

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#61340] opened 2022-05-16 06:05 UTC
**Version Used**: 

Version 17.3.0 Preview 2.0 [32512.305.main] 

**Steps to Reproduce**:

1. Create a type in a file where the name of the type and file don't match
2. <kbd>Ctrl</kbd>+<kbd>.</kbd> on the type name
3. Select "Move to <type>.cs"

**Expected Behavior**:

`<type>.cs` is opened in the editor.

**Actual Behavior**:

The original file maintains focus, and the type disappears from it.

---

I regularly want to view or edit a type after moving it to its own file. I just like to verify what the IDE did, and maybe improve the docs, layout and so forth. Usually when I move a file to a new type, it's newly written code that I'm in the process of cleaning up for commit.

Currently, finding and opening the newly created file requires something like:

- Remember the moved type's name, invoke search, type the name, wait for results, parse results, select result, or
- Open Solution Explorer, click "locate in solution" in the toolbar to select the current file (requires mouse or binding commands to keystrokes), find its new sibling, then open it.

Each of these multiple steps can take several moments.

If the file opened immediately, I could quickly close it if I don't want it, or <kbd>Ctrl</kbd>+<kbd>Tab</kbd> back to where I was.

There's an asymmetry between the possible behaviours here. One has a complex workaround, the other has a simple one.

**Comment by sharwell** [comment] 2022-05-19 19:50
Note that in cases where a file contains multiple nested types that each need to be moved to a new file, the current behavior is ideal. We need to figure out which case is more common.

**Comment by CyrusNajmabadi** [comment] 2022-05-19 19:53
This was a very intentional decision based on us hearing from people that navigating was very disruptive.  Many people are doing a series of operations (or just want to focus on the code they have currently) without actually navigating to the new thing until they're ready to work on the moved stuff.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 20:17
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-22 20:17 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Need Design Review
