### ISSUE TITLE
CallerMemberName should work on target typed new()

### ISSUE THREAD

**Issue by HobbsCode** [dotnet/roslyn#49547] opened 2020-11-21 19:29 UTC
### Description
CallerMemberNameAttribute is not working correctly with the new target typing feature. 
The caller should be the same regardless of target typing. However, the attribute is currently not being respected when target typing new(). The program below demonstrates.

```
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApp2
{
    class Foo
    {
        public string Caller { get; set; }
        public Foo([CallerMemberName] string caller = "?") => Caller = caller;
        public void PrintCaller() => Console.WriteLine(Caller);
    }

    class Program
    {
        static void Main()
        {            
            Foo f1 = new Foo(); // Explicit typing
            f1.PrintCaller();   // Prints "Main"
            
            Foo f2 = new();   // Target typing
            f2.PrintCaller(); // Prints "?"

            Console.WriteLine("\n\nPress any key...");
            _ = Console.ReadKey(intercept: true);
        }
    }
}
```

### Configuration
.NET 5.0.100 (C# 9) 
Win10-1909 x64

### Regression?
No. New feature in C# 9.

**Comment by Youssef1313** [comment] 2020-11-22 11:28
I cannot reproduce using [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQuADAAS6EB0ASljAJZhx0DCA9mAA4sANogDKiAG4sAxnCgBuMmQJUAYt25kA3mSq6aAZhqFqnCIOEIqmqgHM4MOVSj3HAXx17chtdwAUAbVNzRABZODBgRAA5CHYAXSNqKTMLKgBeKgAiAH5MgEp0gD4qINSM5OCEBVI9AxoAFioABQQWTBhSxF8CtOLaAE5fToQ86vdSJXwjAHYtD11aADYGqhCINu75q1qdvS3anyoAM0J0qkw4AHdVdW7HAHp7qgBRAA8+QWkWGCoYAE8BJgbPs9Cc6C02h0Ul1RnpHs1Wu0oFk1m1MooarsbtxjlMMhdLnc4U8ACoQBB2H7/QHAzG7I74cGIqGVInwiFIrK5LbjcZAA).

**Comment by Youssef1313** [comment] 2020-11-22 11:54
I tested on [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQygg5hG6CeADgJYB2WAPgAIBMAjALABQVADAARV0B0ASnKRjEAthG4BhAPbCSAGwgIAygoBuxAMYoA3M2a12AMUmTmAb2btLnAMyc6HcVFnyE7U+xwwt7ZLm8BfCysqWyNJAAoAbUdnBQBZCGFgBQA5KFEAXTsOdScXdgBedgAiAH5igEpCgD52GPyi3NiEHSYrG04AFnYABQQyGHqFcKqC2q4ATnChhArWwKY9GjsAdjMgyy4ANi72OKgyEY23dtOrY/aw9jA6QvZSCAB3Q2MR7wB6d/YAUQAPQlkGmIMHYMCIZCwFysN24fQGMzeVk+vX6gmQJX2ZGKujaZxekmuyyKD0eiMsyIAKphPKDweQoZYwDRYajBnlhnN2Mi4WiSuVjgsFkA===) using an old branch and could reproduce the issue.

This bug might have got fixed at some point of time without actually knowing about it. A test will be needed to prevent future regressions before closing this issue.

**Closed** 2020-11-23 04:32 UTC
Labels: Area-Compilers, untriaged

**Comment by feeleen** [comment] 2021-10-20 20:02
while we are at it, why VS2019/2022 with .NET5.0 and .NET 6.0 give me this:

```
C.ctor
        .ctor
        .ctor
        Main
B
        .ctor
        .ctor
        Main
AMain
        .ctor
        Main
```

while [SharpLab run](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoARKCAcxgHsBnBKAYzYG5iylGgCV0nMAFNqAYRZgADlAA2E5AGVVAN24S+AilWoAZWAEd+RYjAiS28iFwnlZMNixUBBefJzEA3sTkQZQ4QgDsgcEBRMGxQgBslAAs5ACy0DAAFACUkXHk0fn50uRc5AC85DASAO45FkVxAELkwBVVtfV5jeQe5BDt1XXZDUUAvt0TljHBWADMIc7kIL3dhUXzzjnLrRBsEtt+5FOxU92buOQtKx5r3bGbTYfHk93nC5e3M0Hr+ZsemQA2tIIEoVMhUhIwMBVAA5GwSAC6QlIAH5yJpQagnJUYKgwblvnFfj0qABOTIIAAWUDY1AA4hIEAAVACe8gO2Wo8Mk5AA1BisRIRsR7kUhuQ1AgHABrZnIBychlMgBiCtsOWozIgMoOcy5zJYJg4OTFPXI1BVLGQAFEHFTMgAPCoAPiEFIARAAdBAe/nkR3KhCQ6ksAAmOVR3IR2RFRNOryIYyAA===)

gives:
```
C.ctor
	.ctor
	Main
	InvokeMethod
B
	.ctor
	Main
	InvokeMethod
AMain
	.ctor
	Main
	InvokeMethod
```

?

**Comment by feeleen** [comment] 2021-10-21 07:30
> > or "Main" if call is implicit, as I see it
> 
> We definitely do _not_ know who it is :) When B's constructor calls into 'A', it has no idea who called it. Specifically, think about this code:
> 
> ```cs
> public B() { }
> ```
> 
> This is translated quite literally to `public B() : base() { }`
> 
> there is no location there to place 'Main' as B has no idea who called it (note the lack of parameters entirely).

You have two pieces of paper, put them together and pierce it with the needle. Who made a hole in a second piece ?

**Comment by CyrusNajmabadi** [comment] 2021-10-21 07:49
> You have two pieces of paper, put them together and pierce it with the needle. Who made a hole in a second piece ?

 I have no idea what that means.

**Comment by CyrusNajmabadi** [comment] 2021-10-21 07:52
> and I think it should be revised

What should it be revised to?  There's no way to pass in 'Main' in your case.  The intermediary constructor literally has no parameters.  So there's no mechanism by which to pass that name along from your 'Main' method through B's constructor all the way to A's constructor.  

If you want that behavior, then write B like so:

```c#
    public class B : A
    {
        public B([CallerMemberName] string? value = null) : base(value) { }
    }

    public class A
    {
        public A([CallerMemberName] string? value = null)
        {
            Console.WriteLine(this.GetType().Name + value);
        }
    }
```

If you do this, the calling B's constructor will pass in `"Main"`, and B's constructor will then pass that along to A's constructor.

**Comment by feeleen** [comment] 2021-10-21 07:52
> > Users want real caller names
> 
> What is the 'real caller name' for a constructor?

I mean name of someone **who did call constructor**

**Comment by feeleen** [comment] 2021-10-21 07:56
> If you do this, the calling B's constructor will pass in `"Main"`, and B's constructor will then pass that along to A's constructor.

too much excessive code. And often I do not want to explicitly declare constructors to keep classes clean and clear

**Comment by CyrusNajmabadi** [comment] 2021-10-21 08:02
>I'll show you what result I want from CallerMemberName attribute. Something like this:

this will not work.  Even basic things like async-calls will break that.

**Comment by CyrusNajmabadi** [comment] 2021-10-21 08:09
> It's just an idea that it should go up the calls pipeline and look for someone who is not constructor

See the above example.  It would print out 'MoveNext'.  And, frankly, if htat's what you want, then just write a helper utility function that does exactly what you have there.  If you're ok with the perf overhead of using StackTrace, any issues that might arise with it not working in some environments (like release mode), and also ok getting random names like this, then def just use this.

However, that's not what CallerMemberName is.  CallerMemberName is substituting the name of the caller *from teh perspective* of C#, not from what actually happens at runtime.  If you want hte latter, just use things like StackTrace+Reflection+etc.  If you want the former, then you'll need to annotate the methods and pass values along if that's the semantics you want.

**Comment by CyrusNajmabadi** [comment] 2021-10-21 08:51
> and add OmitConstructors attribute too

You haven't explained how that would work at all.  Again, the *caller* has to supply their name to the *callee*.  The callee cannot say "omit constructors" as that doesn't solve the question of: how does the omitted constructor know the name of what called *it*?

The omitted constructor can only know the name of what called it if it itself has a CallerMemberName parameter on it.  In other words, you have three enties:

1. The caller (i.e. Main)
2. The intermediary constructor you want to omit. (Let's call this 'X')
3. The final code that wants the name of the non-constructor caller. (Let's call this 'Y').

So, we know 'Y' wants this name.

So you start by annotating 'Y' like you've requested:

```c#
void Y([CallerMemberName(OmitConstructor = true)] string? caller = null) { ... }
```

Ok great... but now what?  In `Main` we are calling `new X`, we're not calling `Y`.   So say we're compiling the `X` constructor and we see the call to `Y`.  We see that we are supposed to pass in a Callername, but that we should omit constructors (which we are).  Ok... so we can omit ourselves.  But we can't pass in 'Main' to `Y` because we don't have that information.  

Think about it.  X's constructor could have been called from arbitrary number of places.  Each of  those places could have a different name.  X has absolutely no idea what it's caller was.  So how can it possibly let 'Y' know?

So, the only way we can make this work is if the 'X' constructor is *passed* the name of any of its callers.  And how do we do that, by adding a `[CallerMemberName]` parameter to *it*.  Then we finally have a working solution.  All the callers in '1' can pass their name to 'X'.  And when 'X' calls 'Y' it can pass that name along.

There is literally *no* other solution that can work here.  StackTrace is a complete non-starter as StackTrace literally does not contain these names.  So, absent some new proposalyou have that solves this, the only viable path is to use CallerMemberName in the prescribedd fashion (which is how it was designed to be used).

**Comment by CyrusNajmabadi** [comment] 2021-10-21 09:19
>  to get real caller at compile time 

A core problem is that you haven't defined what even is 'a real caller'.  From the C# language's perspective, this is working as intended.  You haven't explained why your perspective is more appropriate (or even fully what it is).

>  or at runtime only (maybe via thread's context)

It is not possible at runtime.  It literally is information that may not exist at all.

> I need new Fully Working Feature.

If you want a change to the langauge:

1. you will need to open a discussion at github.com/dotnet/csharplang
2. that discussion will have to lay out the problem clearly you are having
3. that discussion should ideally explain why the existing solutions are not acceptable (for example, why you won't use a SourceGenerator here).
4. that discussion should lay out some potential solutions, including explaining what it would compile down to

In other words, it's not sufficient to say: i don't like how thi feature works.

Instead, you need to explain how you would actually want it to work *and how to make that possible*.  For example, saying you want it to work in some fashion, but having no way for the compiler or runtime to do that makes things a non-starter as we literally can't provide you with something we can't actually implement.

> Maybe there should be a special mark for those threads, by which we know which method created this code

I don't know what this means.  I think the problem is that you yourself don't have a good idea of what a "fully working feature" would be.   I genuinely don't know, even have read the entire thread a few times.  It sounds like you want something akin to a stacktrace... but you want it to somehow see through asynchrony and potential lambda-indirections.  

however, you also want this to work without you even having to put attributes on some of your code to let the compiler know what you're doing (https://github.com/dotnet/roslyn/issues/49547#issuecomment-948355063).

I'm skeptical that a solution exists here that would be ale to provide you with the functionality you want, with the adde requirement that you not even need to add attributes to things.  if you are able to come up with such a design, please open a discussion over at csharplang and we can assess it.

However, absent that, no movement on anything will be made here.  As evidenced by this conversation:

1. the feature is workign exactly as spec'ed.
2. the feature is doing what we wanted it to do (pass in the lexically scoped name, not the runtime stackframe name).
3. the feature has a solution to address the issue you raised (passing a name through an intermediary).

So the only thing we've garnered is that you do not like the available solution.  But without a suitable alternate, we would not change anything here as we'd generally find the available solution sufficient, and would not accept the reasoning that you "do not want" to use it as sufficient to invent something else which you might also not want to use.

**Comment by feeleen** [comment] 2021-10-21 09:42
> A core problem is that you haven't defined what even is 'a real caller'.

Real caller is the nearest method who initiate current method call or async code
with two additional rules:
1. omit the implicit constructor calls! because they are useless and must not be counted in
2. In this case below it should also omit B() constructor and set value to Main as we're not passing through anything:
```cs
public class B : A
    {
        public B() : base ()
        { }
    }

    public class A
    {
        public A([CallerMemberName] string? value = null)
        {
            Console.WriteLine(this.GetType().Name + value);
        }
    }
```

I believe compiler **able to get this information** and do substitutions in any case (sync/async/anonymous calls etc).

**Comment by CyrusNajmabadi** [comment] 2021-10-21 09:50
> In this case below it should also omit B() constructor and set value to Main as we're not passing through anything:

*how*?

> I believe compiler able to get this information

It is not.  The compiler would have no idea on how to do this.  Consider, for example, that B and A may just be metadata-symbols in a compiled dll somewhere.  When compiling Main, there is no way for the compiler to have any clue what will happen here, nor does it have any mechanism to pass this informatio along.

> and do substitutions in any case (sync/async/anonymous calls etc).

How?  it would literally be impossible.  The IL and metadata for B and A are already fixed in this case.  B takes no parameters and has no way to pass any information about what called it to A.  As such there is literally nothing the compiler can do here in `Main` to get that information all the way to 'A'.

You say you "believe" the compiler can do this.  But you have to actually demonstrate *how* it would do that.  If it helps, i can supply a prebuilt dll containing B and A;.  You can then provide any code necessary in your progam's Main method that proves out how you could pass `"Main"` into `A's constructor` when you do the `new B();` call.  

I think you'll find *quickly* that this is not possible.  

--

Again, to repeat, it is not sufficient ot say you believe it can be done.  You need to show *how* it can be done.  because, from my perspective, it's not actually possible at all.

**Comment by feeleen** [comment] 2021-10-21 10:28
Ok. It's impossible to do using attribute. I see.

But let's clear something: do you agree that if it was working as I say it would be better and more convenient? (do not pay attention to is it impossible to implement or not)

**Comment by feeleen** [comment] 2021-10-21 12:02
As for runtime features, we have 
1. `ExecutionContext `(it's always captured and available even for async code, if not suppressed)
2. `MethodBase.GetCurrentMethod();` (don't know how this works, but we may have similar `MethodBase.GetCallerMethod()` or `MethodBase.GetCallerMemberName()`)

so when sync method is executed, it's name may be added into ExecutionContext's special storage. For async methods added into additionally created storage for each thread. 

so we would just do something like
`Thread.CurrentThread.GetCallerMemberName() `
or
`MethodBase.GetCallerMemberName()`
 
and it'll look into current thread storage, then ExecutionContext storage if thread storage is empty

I still believe it's possible to implement it somehow

**Comment by feeleen** [comment] 2021-10-21 16:29
> Because it's entirely up to the runtime what may or may not happen here. Sometimes when a task finishes, it may choose to inline execution if the next continuation into that frame.

there was no "await" inside Y method.. that's why call stack different.. copy paste

**Comment by CyrusNajmabadi** [comment] 2021-10-21 16:54
That's the point. Any changes here can affect the results. That's why this can not be used. These frames are an implementation of how the runtime schedules things.
