### ISSUE TITLE
GetSymbolInfo behaves differently in msbuild from the IDE

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#5362] opened 2015-09-21 10:50 UTC
Over at StyleCopAnalyzers we got this [bug report](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1501). When investigating I discovered that the problem only was showing up when the analyzer ran on the command line (or our testing application) but not in the IDE. The problem was that `GetSymbolInfo` was returning two different answers when resolving this symbol:
```csharp
    public enum Lifetime
    {
        Persistent,
        Transient,
        Scoped
    }
   public class Example
    {
        public Lifetime Lifetime => Lifetime.Persistent;
        //                          ^^^^^^^^
    }
```
In the IDE it returned the symbol of the enum (which is correct). On the command line however the symbol of the `Lifetime` property was returned. It looks like the bug only shows up when the symbol is on an ArrowExpressionClause. The bug also shows up if the property has a different name and there is different Property with the name `Lifetime`:
```csharp
    public enum Lifetime
    {
        Persistent,
        Transient,
        Scoped
    }
   public class Example
    {
        public Lifetime Lifetime2 => Lifetime.Persistent;
        //                           ^^^^^^^^
        public Lifetime Lifetime
        {
            get
            {
                return Lifetime.Persistent;
            }
        }
    }
```

**Comment by jaredpar** [comment] 2015-11-30 21:01
Sorry we're just getting around to this. 

There are only two items I can think of that MSBuild would influence here which could explain this:

1. Picks a different version of the Roslyn APIs hence you're just seeing different code execute.
2. The compilation is built in a subtly different way that causes the difference you're seeing. 

It's hard to determine which is the case based on the bug info.  My instinct is to lean towards 1.  Are you able to test locally and see which is the case?

**Comment by jaredpar** [comment] 2016-01-18 18:35
I'm unable to reproduce this locally hence closing.  Please comment back if you have additional information that could help me repro this issue.

**Comment by pdelvo** [comment] 2016-01-18 22:05
I tried it and it still happens. maybe it is easier to repro it like this:

- Clone stylecopanalyzers
- Revert [this](https://github.com/pdelvo/StyleCopAnalyzers/commit/fac59f2b49ac35d16f21a1c641626d451da47242) commit.
- Add the analyzer to a project that has the code from above in it.
- Compile it.
A violation of SA1101 is raised if the command line compiler is used, but not in the live analysis of visual studio.

**Comment by pdelvo** [comment] 2016-01-25 13:55
After some research I think I have some more information. I think the problem is, that [this](https://github.com/dotnet/roslyn/blob/ac49fc47bbcf7ef4d507a410a6c57021f9fb549c/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L815-L818) statement is not true in this case. The BindIdentifier method does not handle the "Color Color" case but it should. I dont have time to look into this further, but I think it might have to call [BindLeftOfPotentialColorColorMemberAccess](https://github.com/dotnet/roslyn/blob/ac49fc47bbcf7ef4d507a410a6c57021f9fb549c/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L4351) at some point or the caller of BindIdentifier has to do that.

**Comment by pdelvo** [comment] 2016-01-25 20:20
I think I found the commit that is causing this problem: https://github.com/dotnet/roslyn/commit/92b896ba This would explain why I saw different results before, probably because of different version of roslyn with and without this change

**Comment by jaredpar** [comment] 2016-01-25 20:30
Thanks for the additional information @pdelvo.

**Comment by gafter** [comment] 2016-04-18 18:13
Integrated into future in 7d02e6cfa7402b8dcd86cf54f4c885ac78b13e9b .

**Closed by gafter** 2016-04-18 18:13 UTC
Labels: Area-Compilers, Bug, Concept-API, Resolution-Fixed
