### ISSUE TITLE
Failure to compile (error code 1) when deployed

### ISSUE THREAD

**Issue by seascan** [dotnet/roslyn#4799] opened 2015-08-25 23:44 UTC
Hi.  I am very new to 4.5.2 and the Roslyn compiler so, please forgive any ignorance in this issue:

I recently completed an MVC project locally -- it works great and I am ready to deploy it to my remote server.  I set everything up (as I usually do for MVC projects) and copied my project over.

No matter what I do, I can't get past the following error.  Does anyone recognize this or perhaps point me in a direction?

C:\Windows\SysWOW64\inetsrv>E:\HostingSpaces\MySite\MySite.com\wwwroot\bin\roslyn\vbc.exe /t:library /utf8output /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Deployment\v4.0_2.0.0.0__31bf3856ad364e35\System.Web.WebPages.Deployment.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\6ebaa760\e883b0be_83dfd001\EntityFramework.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\1c914da5\e1c1cac6_83dfd001\System.Web.WebPages.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\1a633926\f39ffbc2_83dfd001\Microsoft.Owin.Security.OAuth.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\790d9b1c\57afb4bc_83dfd001\EntityFramework.SqlServer.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\f86368af\13db50c1_83dfd001\Microsoft.Owin.Host.SystemWeb.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\f88dd8ff\e38845c3_83dfd001\Microsoft.Owin.Security.Twitter.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Web.Infrastructure\v4.0_1.0.0.0__31bf3856ad364e35\Microsoft.Web.Infrastructure.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\b361f461\3fff95c1_83dfd001\Microsoft.Owin.Security.Cookies.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\67b9117d\6fce67c2_83dfd001\Microsoft.Owin.Security.Google.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\100e6b5a\6d315cc7_83dfd001\TailWalker.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\226b9610\68c3aec0_83dfd001\Microsoft.AspNet.Identity.Owin.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\288eeec8\f741f6c0_83dfd001\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\6d77e575\2790aac2_83dfd001\Microsoft.Owin.Security.MicrosoftAccount.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\e7b30f74\a3335cbf_83dfd001\Microsoft.AspNet.Identity.Core.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\90a70323\66d264c0_83dfd001\Microsoft.AspNet.Identity.EntityFramework.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\6c2c7fd2\2fb3b4c4_83dfd001\System.Web.Helpers.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\5bf42557\6c5fc8c6_83dfd001\System.Web.WebPages.Razor.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\6f38e044\98babcbb_83dfd001\Antlr3.Runtime.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\1b2ee4c0\40af5dc8_83dfd001\WebGrease.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\d1431339\0e9f66c6_83dfd001\System.Web.WebPages.Deployment.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\b7cbc3f1\a8784ec1_83dfd001\Microsoft.Owin.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\019e4e14\ca181fc6_83dfd001\System.Web.Razor.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\db5535ea\39815cc4_83dfd001\Owin.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Deployment\v4.0_1.0.0.0__31bf3856ad364e35\System.Web.WebPages.Deployment.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\a4ee668d\4a8cddc1_83dfd001\Microsoft.Owin.Security.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\151295c8\3231b6c5_83dfd001\System.Web.Optimization.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\42815245\f7821bc2_83dfd001\Microsoft.Owin.Security.Facebook.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\8db31120\e9e569c5_83dfd001\System.Web.Mvc.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\assembly\dl3\2cdd7088\bb9131c4_83dfd001\Newtonsoft.Json.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /out:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\App_global.asax.-e3dq0ca.dll" /D:DEBUG=1 /debug+ /nowarn:41008,40000,40008 /define:_MYTYPE=\"Web\" /imports:Microsoft.VisualBasic,System,System.Collections,System.Collections.Generic,System.Collections.Specialized,System.ComponentModel.DataAnnotations,System.Configuration,System.Linq,System.Text,System.Text.RegularExpressions,System.Web,System.Web.Caching,System.Web.DynamicData,System.Web.SessionState,System.Web.Security,System.Web.Profile,System.Web.UI,System.Web.UI.WebControls,System.Web.UI.WebControls.WebParts,System.Web.UI.HtmlControls,System.Xml.Linq  /optionInfer+ /langversion:14 /nowarn:41008 /define:_MYTYPE=\"Web\" /optionInfer+  "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\App_global.asax.-e3dq0ca.0.vb" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\2eb58901\bf7d9a5c\App_global.asax.-e3dq0ca.1.vb"

**Comment by jmarolf** [comment] 2015-08-26 00:11
I can see no error.  Looks like standard command-line arguments being passed into vbc.exe.  What is the error you are seeing?

**Comment by seascan** [comment] 2015-08-26 00:15
![capture](https://cloud.githubusercontent.com/assets/6199840/9482816/1182114a-4b66-11e5-8c5b-d3b3fdb4b33b.PNG)

**Comment by seascan** [comment] 2015-08-26 00:21
Sorry!  hit the wrong button... didn't mean to close.

**Comment by jmarolf** [comment] 2015-08-26 07:35
Thanks, so its a compiler crash.  Can you provide any more details about how you Deployed your MVC app so we can reproduce this?

**Comment by seascan** [comment] 2015-08-26 21:07
It turns out it was an issue on the server.  Whatever it was, it is fixed now.  I am trying to find out from my service provider what they did to fix the issue.

**Comment by jmarolf** [comment] 2015-08-26 21:59
Alright, I'll close this issue for now.

**Closed by jmarolf** 2015-08-26 21:59 UTC
Labels: Area-Compilers

**Comment by seascan** [comment] 2015-08-27 14:10
I just heard back and they had to switch the App Pool to 64 bit in IIS.  Appears that was the culprit.  Does that makes sense?  Is it a requirement to have the App Pool set to 64 bit?
