### ISSUE TITLE
RenameCrefCrossAssembly_VisualBasic failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9566] opened 2016-03-08 16:24 UTC
```
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 0)\r\nExpected: Global.R\r\nActual: N\r\n ↑ (pos 0)
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLocationReplacedWith(Location location, String replacementText, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn_master---01224af0\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 203 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLabeledSpansAre(String label, String replacement, Nullable`1 type, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn_master---01224af0\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 134 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.RenameCrefCrossAssembly_VisualBasic() in d:\j\workspace\roslyn_master---01224af0\src\EditorFeatures\Test2\Rename\RenameEngineTests.vb:line 5241
```

**Comment by davkean** [comment] 2016-03-08 16:30
https://github.com/dotnet/roslyn/issues/9565, https://github.com/dotnet/roslyn/issues/9566 and https://github.com/dotnet/roslyn/issues/9568 all look related.

**Comment by jasonmalinowski** [comment] 2016-03-08 18:12
This is a dupe of #9308.

**Closed by jasonmalinowski** 2016-03-08 18:12 UTC
Labels: Area-IDE, Flaky, Test
