### ISSUE TITLE
IntelliSense should show conditional compilation symbols

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#16542] opened 2017-01-16 21:57 UTC
**Version Used**: Visual Studio 2017 RC.3+26114.2.d15rel

**Steps to Reproduce**:

1. Create a new C# project
2. Add a conditional compilation symbol to your project (e.g. `AWESOME`)
3. Start typing `#if ` and invoke IntellISense

**Expected Behavior**:

IntelliSense displays the list of conditional compilation symbols. Ideally, across all configurations but at least for the current project configuration (e.g. `Debug|x86`).

**Actual Behavior**:

It helpfully shows `true` and `false`. Hooray!

This is especially frustrating for projects that are cross-compiled (i.e. compile for multiple TFMs). The developer cannot easily discover the conditional compilation symbol for the TFM. I ended up running a diagnostic build to see what's passed to CSC.

![image](https://cloud.githubusercontent.com/assets/5169960/22000242/f50715b4-dbf2-11e6-8f23-84350832e459.png)

**Comment by miloush** [comment] 2017-01-16 22:06
A duplicate of #11499?

**Comment by terrajobst** [comment] 2017-01-16 22:39
Thanks. Was searching, but was probably using the wrong keywords.

@srivatsn @davkean @Pilchie should be bump the priority? I expect cross compilation to become a lot more prominent, considering the improvement in our tooling. Not having IntelliSense for symbols makes this harder than it needs to be.

**Closed** 2017-01-20 18:41 UTC
Labels: Area-IDE
