### ISSUE TITLE
`CSharpMergeConsecutiveIfStatementsCodeRefactoringProvider` encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74773] opened 2024-08-15 13:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpMergeConsecutiveIfStatementsCodeR/10723697)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Preview 11]
![image.png](https://aka.ms/dc/image?name=Bbd0e7f5d3191415b98923896e9d5e49f638593171701467760_20240815-071249-image.png&tid=bd0e7f5d3191415b98923896e9d5e49f638593171701467760)

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span,Boolean findInsideTrivia,Boolean getInnermostNodeForTie)
   at async Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeIfStatementsCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-30 18:55
Dupe of https://github.com/dotnet/roslyn/issues/74772.

**Closed by CyrusNajmabadi** 2024-11-30 18:55 UTC
Labels: Area-IDE
