### ISSUE TITLE
[Source Generator] Cannot use MetadataLoadContext in source generators

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/roslyn#50150] opened 2020-12-28 08:57 UTC
**Version Used**: 

Visual Studio 16.8.3

**Steps to Reproduce**:

1. Create a .NET Standard 2.0 project as source generator and add an nuget package reference of `System.Reflection.MetadataLoadContext` (the version of the package does not affect the issue)
2. Create a source generator class and use any type in the above package inside the `Execute` method, e.g. write a simple statement just like `var t = typeof(MetadataLoadContext)`. 
3. Create a .NET Standard 2.0, .NET Core 3.1 or .NET 5 project and add the above project as a source generator project (edit the project file and add a line as `<ProjectReference Include="path-to-sourcegenerator-project.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />`) 
4. Generate the new project

**Expected Behavior**:
The generation should be ended successfully.

**Actual Behavior**:
A warning of CS8785 generated and it says "The generator cannot generate source. Cannot load file or assembly System.Reflection.MetadataLoadContext or one of its depedencies. File cannot be found."

**Remarks**:
Actually I'm just trying to generate source code from another existing DLL/project (it is necessary for cross platform middleware interactions, such as generating proxies for web services) If there's any way to retrieve type and member information from another DLL or project, could you please give  me a short guide and many thanks!

**Comment by sharwell** [comment] 2020-12-28 18:59
Duplicate of #47517

**Comment by sharwell** [comment] 2020-12-28 18:59
See specifically https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145. The error is occurring because steps 2 and 3 were not completed.

**Closed by sharwell** 2020-12-28 18:59 UTC
Labels: Area-Compilers, untriaged
