### ISSUE TITLE
Misleading error message for local function

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#18555] opened 2017-04-08 15:40 UTC
**Version Used**: 
2.0

**Steps to Reproduce**:

Compile the following code:
```c#
public void M() {
   void Local()
}
```

**Expected Behavior**:

> error CS0XXX: local function 'Local()' must declare a body

**Actual Behavior**:

> error CS0501: 'Local()' must declare a body because it is not marked abstract, extern, or partial

Note that you neither can mark local function with `abstract`, `extern` or `partial` modifier

**Comment by khyperia** [comment] 2017-05-09 22:27
Duplicate of #14900

**Closed by khyperia** 2017-05-09 22:27 UTC
Labels: Area-Compilers, Bug, Concept-Diagnostic Clarity, New Language Feature - Local Functions
