### ISSUE TITLE
Refactoring between a cast operator and an as operator does not produce identical functionality

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn#61014] opened 2022-04-28 17:55 UTC
**Version Used**: 6.0

**Steps to Reproduce (as to cast)**:

1. Assign a type to `object` and use the as expression to cast to an invalid type

```csharp
object obj = new SomeType();
_ = obj as InvalidType
```

2. Use roslyn analyzer to switch to a cast

```csharp
_ = (InvalidType)obj;
```

**Expected Behavior**:

Functionality is maintained.

**Actual Behavior**:

After the code action, the cast now throws an exception.

**Steps to Reproduce (cast to as)**:

1. Assign a type to `object` and use the cast operator to cast to an invalid type
 
```csharp
try
{
    object obj = new SomeType();
    _ = (InvalidType)obj;
}
catch(InvalidCastException)
{
    MessageBox.Show("Could not cast value");
}
```

2. Accept the roslyn suggestion

```csharp
try
{
    object obj = new SomeType();
    _ = obj as InvalidType;
}
catch(InvalidCastException)
{
    MessageBox.Show("Could not cast value");
}
```

**Expected Behavior**:

Functionality is maintained.

**Actual Behavior**:

After the code action, the exception doesn't happen anymore and the code is susceptible to further issues.

**Real world scenario:**

1. We have a WinForms app that has `DataTable`s assigned to `BindingSource`s

```csharp
private void btnSelect_Click(object sender, EventArgs e)
{
    try
    {
        var row = (DataRowView)bindingSource.Current;
        if (row != null)
            Close();
    }
    catch(InvalidCastException)
    {
        MessageBox.Show("Could not cast value");
    }
}
```

2. We are migrating to EF Core and naively assign a `DbSet` to `BindingSource.DataSource` instead.
3. At runtime, errors occur telling us that the row couldn't be cast.
4. We find the cast(s) and fix them. Oh, and while we are there, we see a suggestion that we can use the `as` expression, so we accept it.

```csharp
private void btnSelect_Click(object sender, EventArgs e)
{
    try
    {
        var row = bindingSource.Current as SomeType;
        if (row != null)
            Close();
    }
    catch(InvalidCastException)
    {
        MessageBox.Show("Could not cast value");
    }
}
```

5. We now decide to replace the `DbSet` with a View Model and we again naively assign the view model to `BindingSource.DataSource`
7. At runtime, the button click doesn't appear to do anything.
    - Under different conditions, like if `row` was used without null checking, we would end up with `NullReferenceException`s.

Solving this for all cases seems like a non-starter, but maybe the refactor suggestions can be limited to cases where the analyzer is sure that the functionality would not change, for instance, if the target class is a base class of the source class. 

So a refactor suggestion would appear to convert from `(Person)student` to `student as Person`, and the vice versa. But `(Student)person` and `person as Student` and `student as Car` would not give suggestions.

**Comment by CyrusNajmabadi** [comment] 2022-04-28 17:59
@MisinformedDNA 

> Use roslyn analyzer to switch to a cast

Which roslyn analyzer reported this?  Can you give the diagnostic ID it reported?  A screenshot would also be helpful.  Thanks!

**Comment by MisinformedDNA** [comment] 2022-04-28 23:11
Sorry, yes, a refactoring.
![image](https://user-images.githubusercontent.com/1784452/165862175-b12f63da-e6fa-4157-b9f1-a1e4f8c1ed7c.png)

**Comment by CyrusNajmabadi** [comment] 2022-04-28 23:47
Closing as by design. The purpose of this refactoring is exactly to let you change between these forms because you want the different semantics (e.g. one is bad conversion tolerant, one is not).

**Closed by CyrusNajmabadi** 2022-04-28 23:47 UTC
Labels: Area-IDE, Resolution-By Design, IDE-CodeStyle, untriaged
