### ISSUE TITLE
IntelliSense: suggest direct enum members where can be inferred

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#24563] opened 2018-01-31 20:42 UTC
```cs
enum E { A, B, C }
```
Autocomplete should suggest `E.A`, `E.B`, ... in the following cases
```cs
E e = $$ 

if (e == $$

switch (e) {
  case $$
````
etc.

**Comment by sharwell** [comment] 2018-01-31 21:13
Duplicate of #19506

**Closed by sharwell** 2018-01-31 21:13 UTC
