### ISSUE TITLE
Workspace.Dispose throwing on shutdown trying to instantiate MEF components during the MEF container disposable

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#61140] opened 2022-05-05 03:01 UTC
**Version Used**: 
Version 17.3.0 Preview 2.0 [32503.442.main]

**Steps to Reproduce**:
This path is occurring on the disposal of the VS global container. Workspace.Dispose is throwing closing VS after opening Orchard Core due to it trying to instantiate MEF components during the disposal of the MEF container:

![image](https://user-images.githubusercontent.com/1103906/166857754-1d453988-63e0-4fd6-be2c-e9e0c4f6eddd.png)

**Comment by sharwell** [comment] 2022-05-16 23:23
Duplicate of #56177

**Closed by sharwell** 2022-05-16 23:23 UTC
Labels: Bug, Area-IDE
