### ISSUE TITLE
style rule to remove accessibility modifier shows up as "Add accessibility modifier" in lightbulbs (IDE0040 Accessibility modifiers required)

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#64877] opened 2022-10-20 21:03 UTC
**Version Used**: 
[33019.161.main]

**Steps to Reproduce**:
I'm working in a repo where their style conventions are to not explicitly provide “private” as an accessibility modifier.
 
Fair enough but I’m getting prompted to remove the “private” in my code with “Add accessibility modifiers” which seems odd, though the diff makes it clear.
 
The hint also reads IDE0040 Accessibility modifiers required (as opposed to forbidden)
 
![access](https://user-images.githubusercontent.com/11394666/197057278-9adb98b4-db9e-43aa-a459-964ec572d8b0.png)

**Expected Behavior**:
Label is "remove" access modifier.

**Actual Behavior**:
Label is "add" access modifier.

**Comment by DoctorKrolic** [comment] 2022-10-22 07:00
Duplicate of https://github.com/dotnet/roslyn/issues/29633

**Comment by CyrusNajmabadi** [comment] 2022-10-22 15:57
Closing as dupe.

**Closed by CyrusNajmabadi** 2022-10-22 15:57 UTC
Labels: Bug, help wanted, Area-IDE
