### ISSUE TITLE
DebuggerDisplayAttribute

### ISSUE THREAD

**Issue by AlexanderMorou** [dotnet/roslyn#26054] opened 2018-04-10 00:05 UTC
**Version Used**: 
Visual Studio 15.6.5

**Steps to Reproduce**:

1. Create an enum
2. Add Debugger Display that uses `{this}` or `{this.ToString()}`
3. Attempt to view variable or property which uses a reference to the enum.

**Expected Behavior**:
Debugger Display correctly executes and displays the result when you hover over the relevant variable or property in break mode.

**Actual Behavior**:
Debugger indicates the following in the result:
`The debugger is unable to evaluate this expression`

**A Simple Example**
```
[DebuggerDisplay("Testing Debugger Display: {this.ToString()}")]
public enum MyTest
{
    Item1,
    Item2,
}
```

This used to work in previous versions of Visual Studio.  It was useful to send the value to a method of some kind in the event that you wanted to manipulate the result

**Comment by tmat** [comment] 2018-04-10 05:11
Be advised that it is not recommended to use arbitrary expressions in DebuggerDisplay attribute:

https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute#using-expressions-in-debuggerdisplay

**Comment by AlexanderMorou** [comment] 2018-04-10 16:11
Agreed.

I usually only use light-weight methods with no side-effects.  An example is a static method auto-generated for the enum that has no side-effects, or a method that operates on enums in general (via unconstrained melody, for instance.)

DebuggerDisplayAttribute is allowed on enum types, I'm merely pointing out: that which used to work, no longer does.

**Comment by Tyler-IN** [comment] 2023-02-13 23:47
🧟

Occasionally I run into a [Flags] enum with multiple masks.

CEF has a request transition type, the low byte uses values 0 through 10 with the remaining values in the byte reserved; the high 3 bytes are used for qualifier bit flags.

`[DebuggerDisplay("{this&0xFF} | {string.Join('|',Helpers.SplitOutFlags(this&0xFFFFFF00))}")` would be kind of cool.

**Comment by ClosetBugSlayer** [comment] 2024-01-24 19:54
I have had this problem all through .NET Core, it worked fine in .NET Framework. What I used to do was call FormatMessage() for Win32 error codes and av_strerror() for FFmpeg error codes and put the resulting message in [DebuggerDisplay] but today I just get the same expression error. This affects productivity.

**Comment by CyrusNajmabadi** [comment] 2024-10-15 18:58
Closing out as by design.  We do not recommend arbitrary expressions. Instead, make a simple epxression that references a property and do the work inside that property.  We are unlikely to change this.

**Closed by CyrusNajmabadi** 2024-10-15 18:58 UTC
Labels: Interactive-Debugging, Area-Interactive
