### ISSUE TITLE
String interpolation errors when concatenating multiple string

### ISSUE THREAD

**Issue by ceccomil** [dotnet/roslyn#55993] opened 2021-08-26 07:07 UTC
Using Preview 7, It was working on Preview 6, I got this weird behaviour.

Considering this simple console app:

```
using System;

//NET6.0 Preview 7

var myValue1 = "|someValue|";
var myResult = $"I want the value here: {myValue1}"; //this is fine 
Console.WriteLine(myResult);
Console.WriteLine();


myResult = $"I want the value here: {myValue1};" +
    $"Another String using {myValue1} in the middle";
Console.WriteLine(myResult);
Console.WriteLine();
```

This is the result I'm getting (see also picture below):
```
I want the value here: |someValue|

;|someValue|I want the value here:  in the middle|someValue|Another String using

```

![image](https://user-images.githubusercontent.com/40296947/130917049-c9a6079d-f6b5-4316-9509-eafd0eb87418.png)

**Comment by adamsitnik** [comment] 2021-08-28 09:49
It might have been fixed by #55494 in 17.0p4, but I am not 100% sure so I would prefer someone from the Roslyn Team to confirm

**Comment by stephentoub** [comment] 2021-08-28 10:35
Yes, this is a dup of https://github.com/dotnet/roslyn/issues/55461.

**Comment by jcouv** [comment] 2021-09-03 22:59
Closing as duplicate of  #55461. Thanks for reporting

**Closed by jcouv** 2021-09-03 22:59 UTC
Labels: Resolution-Duplicate, Area-Compilers, New Feature - Interpolated String Improvements
