### ISSUE TITLE
Warning IDE0044 not valid for Fields

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29373] opened 2018-08-17 19:35 UTC
Declaring in a VB class

Private HasFree() As Boolean

This is marked as IDE0044, but this is not valid if later onfor example a Redim is declared.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/312744/warning-ide0044-not-valid-for-fields.html
VSTS ticketId: 665072_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-08-17 19:53
Added info:

IDE0044 is "Make field readonly".
The field here is  of type `boolean()` (it's not a func/sub).

**Comment by jinujoseph** [comment] 2018-08-23 18:42
@mavasani can you check if this is already fixed

**Comment by mavasani** [comment] 2018-09-27 21:46
The root cause is lack of IOperation support for Redim statement in VB: https://github.com/dotnet/roslyn/issues/30175

**Comment by mavasani** [comment] 2018-09-28 18:30
I have a PR out to fix this and add IOperation support: https://github.com/dotnet/roslyn/pull/30217

**Comment by mavasani** [comment] 2018-10-15 12:40
Fixed with https://github.com/dotnet/roslyn/pull/30217

**Closed by mavasani** 2018-10-15 12:40 UTC
Labels: 4 - In Review, Area-IDE, Bug
