### ISSUE TITLE
Collection expressions wrapping can't be configured

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71891] opened 2024-01-31 18:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Collection-expressions-wrapping-cant-be/10574252)._

---
[severity:It bothers me. A fix would be nice]
Visual studio automatically wraps the items in the new collection expressions of C# 12. I have scoured the internet and could not find an .editorconfig rule or Visual Studio setting available to turn this off.

For example:
```
bool[] mask =
[
    false, false,
    false, false,
];
```

will change after saving the file (because of automatic cleanup):
```
bool[] mask =
[
    false, 
    false,
    false, 
    false,
];
```

I would like to turn this off or have it configurable, preferably with a .editorconfig rule.

Thanks!

---
#### Feedback Bot on 1/30/2024, 06:46 PM: 

(private comment, text removed)
#### Feedback Bot on 1/31/2024, 06:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment] 2024-01-31 18:42
Duplicate of https://github.com/dotnet/roslyn/issues/70951

**Comment by CyrusNajmabadi** [comment] 2024-01-31 18:49
Closing as dupe.

**Closed by CyrusNajmabadi** 2024-01-31 18:49 UTC
Labels: Area-IDE, untriaged
