### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports.RemoveUnnecessaryImportsTests.TestFixAllInProject (from Roslyn.Services.Editor.VisualBasic.UnitTests) failure

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9493] opened 2016-03-04 18:40 UTC
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future-stabilization_win_rel_unit64/5/testReport/junit/Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports/RemoveUnnecessaryImportsTests/TestFixAllInProject/

Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports.RemoveUnnecessaryImportsTests.TestFixAllInProject (from Roslyn.Services.Editor.VisualBasic.UnitTests)

Failing for the past 1 build (Since Failed#5 )
Took 83 ms.
add description
Stacktrace

MESSAGE:
Expected 0 items but found 1: Found analyzer exception diagnostics\r\nItems:\r\n warning AD0001: Analyzer 'Microsoft.CodeAnalysis.VisualBasic.Diagnostics.RemoveUnnecessaryImports.VisualBasicRemoveUnnecessaryImportsDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Cannot call Enqueue when the queue is already completed.'.\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at Roslyn.Test.Utilities.AssertEx.Empty[T](IEnumerable`1 items, String message) in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\Test\Utilities\Shared\Assert\AssertEx.cs:line 501 at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractDiagnosticProviderBasedUserDiagnosticTest.<GetDiagnosticAndFixesAsync>d__5.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\Diagnostics\AbstractDiagnosticProviderBasedUserDiagnosticTest.cs:line 75 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractUserDiagnosticTest.<GetDiagnosticAndFixAsync>d__3.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\Diagnostics\AbstractUserDiagnosticTest.cs:line 44 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractUserDiagnosticTest.<GetCodeActionsWorkerAsync>d__2.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\Diagnostics\AbstractUserDiagnosticTest.cs:line 37 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<GetCodeActionsAsync>d__7.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 96 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__14.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 191 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__12.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 155 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports.RemoveUnnecessaryImportsTests.VB$StateMachine_50_TestFixAllInProject.MoveNext() in d:\j\workspace\roslyn-intern---0cc4523b\Open\src\EditorFeatures\VisualBasicTest\Diagnostics\RemoveUnnecessaryImports\RemoveUnnecessaryImportsTests_FixAllTests.vb:line 146 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by jmarolf** [comment] 2016-03-07 22:39
Dupe of https://github.com/dotnet/roslyn/issues/8178

**Closed by jmarolf** 2016-03-07 22:39 UTC
Labels: Area-IDE, Flaky, Test
