### ISSUE TITLE
Global alias qualified name is not allowed in string-interpolation?

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#50741] opened 2021-01-24 22:41 UTC
**Version Used**: 16.9.0 Preview 3

**Sample Code**:
[Link](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWACgjUBDAWwFMBnAB1IGNKACAFRrmqIG8jn/mmAMyDszAIK1afAb0ICFo7DMXM5q1QHpNAEwD2NZqj1xmAdz2IA1iBUb+mXAE4AFABIARAAUAkiDUA5gA2esCkQSAgjgB0ALKkcAAW0b4Avh4AlADcdva5GtoW1tS28vYCjq6evv7cMfFJKT7p2fn8qXYdhKlAA===)
```CSharp
using System;

namespace Tests
{
    public class App
    {
        public static void Main()
        {
            //does not work:
            Console.WriteLine($"PI: {global::System.Math.PI}");
            
            //works:
            Console.WriteLine($"PI: {System.Math.PI}");
        }
    }
}
```

**Expected Behavior**:
Both versions should compile. A global alias qualified name is useful to avoid name conflicts - esepecially for generated code.

**Actual Behavior**:
Code is rejected with: `​error CS0103: The name 'global' does not exist in the current context`

**Comment by bernd5** [comment] 2021-01-24 22:45
Here a sample with a name conflict:
```CSharp
using System;

namespace Tests
{
    public class App
    {
        public static string System = "IBM";
        
        public static void Main()
        {
            //does not work:
            //Console.WriteLine($"PI: {global::System.Math.PI}");
            
            //works:
            Console.WriteLine($"PI: {System.Math.PI}");
        }
    }
}
```

**Comment by svick** [comment] 2021-01-25 07:23
The problem is that `:` in string interpolation is treated as delimiter for formatting. This means that `global::System.Math.PI` is parsed as "the identifier `global`, followed by formatting delimiter `:`, followed by the format string `:System.Math.PI`.

To make it work the way you want, [you can use parentheses](https://sharplab.io/#v2:C4LghgzsA+ACBMBGAsAKFgZgAQKwYTQG80tSdtYAWLAWQAoBKEs41M9nRATjoBIAiAAoBJEFkJ0A5gBsA9gCMw0kCFiIAdDTDAAFupEMAvvwYBuZqUNpDQA=):

```c#
Console.WriteLine($"PI: {(global::System.Math.PI)}");
```

Note that the same thing also happens for the ternary operator: https://github.com/dotnet/csharplang/discussions/1409. The compiler was improved to produce a better error message for that case, but I'm not sure that's worth doing for `global::`, since that's used much less often, and usually by more experienced developers.

**Comment by CyrusNajmabadi** [comment] 2021-01-25 07:30
Closing out as by design. This is a fundamental ambiguity, and the language leaned toward : being part of the format specifier over it being pulled into the expression.

**Closed by CyrusNajmabadi** 2021-01-25 07:30 UTC
Labels: Area-Compilers, untriaged
