### ISSUE TITLE
[Feature request]: An option to opt-in for internal API analysis for `IDE0051` (Remove unused private member)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69483] opened 2023-08-12 11:28 UTC
Currently, IDE0051 only works on the private API surface, which is intentional.

It would be good if this supports [`api_surface`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-quality-rule-options#api_surface) option similar to lots of CAxxxx rules.

**Comment by mavasani** [comment] 2023-08-17 12:12
Note that analyzing internal API usage would require full project analysis. Hence these diagnostics can only be reported at CompilationEnd, which means they will be build-only diagnostics and cannot support code fixes. These would still be valuable for customers who want to enable build time enforcement of unused internal APIs, but not something that will lightup automatically in the IDE.

One other alternate approach we have discussed in the passed is to add a command under the Analyze menu in Solution explorer to explicitly run such project/solution level analyzers over the entire project/solution and potentially also apply the code fix - very similar to `Remove unnecessary references` command on the References/Dependencies node.

**Comment by mavasani** [comment] 2023-11-02 08:36
Duplicate of #68029

**Closed by mavasani** 2023-11-02 08:36 UTC
Labels: Area-IDE, Feature Request, Feature - IDE0051
