### ISSUE TITLE
Offer a codefix for BC30433

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45163] opened 2020-06-14 09:39 UTC
I had a class whose methods were all "Shared", so it could be a Module instead. After changing it to Module, the "Shared" keyword now generates a compile error BC30433. Now, I've to manually go and delete the Shared keyword one by one. It'd be nice if a codefix is offered to fix all and remove the "Shared" keyword easily. The codefix should be straight forward, just remove any "Shared" keyword that has reported BC30433.

**Comment by CyrusNajmabadi** [comment] 2020-06-15 01:32
I believe we would take a community PR on tihs.

**Comment by paul1956** [comment] 2020-06-15 03:00
There is already a diagnostic CS1052 when all functions are shared, so you could do the whole thing. Change Class to Module, and remove the Shared. Or do you just want a CodeFix for BC30433?

**Comment by Youssef1313** [comment] 2020-06-15 06:32
I haven't checked, but I think CA1052 doesn't have a code fix as well. So, now there are two possible places for the fixer. But I personally would prefer BC30433 to have the codefix. As it'll serve more developers (developers who doesn't use FxCop NuGet package)

**Comment by paul1956** [comment] 2020-06-18 23:10
@Youssef1313 I tried to prototype a fix for CA1052 but for testing I need the Analyzer that produces it. Is there a way to use a NuGet Analyzer in a test or does that even make sense inside Roslyn? Is the thing that produces CA1052 Open Source and would that be a better place to put it?

**Comment by Youssef1313** [comment] 2020-06-19 06:04
My personal opinion would be to make the code fix in roslyn, not roslyn-analyzers. You can write the codefix in Roslyn and make a PR.

**Comment by paul1956** [comment] 2020-06-20 04:22
@jinujoseph, @Youssef1313  I will give fixing CA1052 a try but what Context.Register action would you use the issue is on the "Shared"

**Comment by mavasani** [comment] 2020-06-22 09:02
Roslyn should only have code fixes for analyzer diagnostics produced by compiler or IDE. For CA1051 code fix, please submit PR to Roslyn-analyzers repo. If fixing compiler diagnostic mentioned here, you can submit a PR to Roslyn.

**Comment by Youssef1313** [comment] 2020-06-22 12:02
I believe the codefix should be for BC30433

**Comment by paul1956** [comment] 2020-06-23 08:40
@Youssef1313 BC30433 should be fixed in Roslyn and I was not planning on doing anything with that. If someone wants to work on I I can share source of a working standalone CodeFix but it don't have integration with Roslyn. For CA1052 I will look at Roslyn-analyzers repo but it will take me some time to understand its support for CodeFixes written in VB.

**Closed** 2020-10-16 03:17 UTC
Labels: Area-IDE, Feature Request, help wanted
