### ISSUE TITLE
Setting not persisted: Collapse #regions

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16392] opened 2017-01-10 17:22 UTC
**Version Used**: 2.0.0.61308

_Text Editor > C# > Advanced > Collapse #regions when collapsing to definitions_ setting does not seem to be preserved.

1. Export settings
2. Enable the setting above
3. Import the exported settings

**Expected:** The setting to be cleared as it was at the time of export
**Actual:** Stays enabled

**Comment by Pilchie** [comment] 2017-01-20 18:06
Dupe of https://github.com/dotnet/roslyn/issues/16247 for another option.

**Closed by Pilchie** 2017-01-20 18:06 UTC
Labels: Area-IDE, Bug

**Comment by Pilchie** [comment] 2017-01-20 18:08
Oops, actually a duplicate of https://github.com/dotnet/roslyn/issues/14810.
