### ISSUE TITLE
Nullable references: Deconstruction of valueTuple in foreach removes nullability of valueTuple items if collection uses System.Linq

### ISSUE THREAD

**Issue by MiYanni** [dotnet/roslyn#39736] opened 2019-11-07 23:54 UTC
This took me some time to figure out what was going on. I create a simple class like this:
```csharp
internal class Alpha
{
    public string Value { get; set; }
    public override string ToString() => Value;
}
```

Here is the test code:
```csharp
var items = new (int? Index, Alpha? Alpha)[]
{
    (0, new Alpha { Value = "A" }),
    (1, new Alpha { Value = "B" }),
    (2, new Alpha { Value = "C" })
}.Select(p => p);
foreach (var (index, alpha) in items)
{
    Console.WriteLine(index);
    Console.WriteLine(alpha);
}

var items2 = Enumerable.Empty<(int? Index, Alpha? Alpha)>().Where(p => true);
foreach (var (index, alpha) in items2)
{
    Console.WriteLine(index);
    Console.WriteLine(alpha);
}
```

Basically, any *nullable class references* become non-nullable in the `foreach`. Screenshots:
![image](https://user-images.githubusercontent.com/17788297/68437134-e7804a00-0174-11ea-96df-6d796d05a42d.png)
![image](https://user-images.githubusercontent.com/17788297/68437216-27473180-0175-11ea-8f44-246daf0239ba.png)
![image](https://user-images.githubusercontent.com/17788297/68437232-3b8b2e80-0175-11ea-83ac-851d9751280c.png)
![image](https://user-images.githubusercontent.com/17788297/68437258-45149680-0175-11ea-809e-ddae15b8b93f.png)
![image](https://user-images.githubusercontent.com/17788297/68437141-f666fc80-0174-11ea-9024-ecd07115f202.png)
![image](https://user-images.githubusercontent.com/17788297/68437288-5493df80-0175-11ea-852e-555ddb27a8b6.png)

It does not seem to be specific to a particular Linq extension method. That's why I included two. As soon as you remove the Linq method, it works correctly:
![image](https://user-images.githubusercontent.com/17788297/68437763-bd2f8c00-0176-11ea-8ae9-84d1e27acb84.png)

**Comment by jcouv** [comment] 2019-11-08 17:10
Moving issue to roslyn. Something seems wrong indeed. Needs some investigation.

**Comment by MiYanni** [comment] 2019-11-08 18:29
@Gnbrkm41 Thank you for narrowing it down. I ran into once the other week in a project I'm working on. And, then again this week in a different part of the project. I time-boxed investigating it, so I didn't get to narrow it down as far as you did.
@jcouv Please transfer the issue appropriately as it causes other issues with tools like Resharper that get quite confused about what to suggest. I had one instance where compilation failed despite VS having no qualms with the code (no red squiggles).

**Comment by jcouv** [comment] 2019-11-08 18:51
@333fred I assigned this to you as I will be OOF most of next week. Would you be able to take a look after Ignite? Thanks

**Comment by 333fred** [comment] 2019-11-12 01:39
Alright, I've dug into this. The problem is coming from the use of a generic method call: even an annotated `Identity` method would hit the issue. Currently, we end up using the return type of `Current` from initial binding where we should not. The type from initial binding is oblivious, which then converts to not annotated. I've submitted a PR to fix the single-variable declaration case, but we still need to fix the tuple case. https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L6068 does not pass the updated return type of `Current` through to `VisitTupleDeconstructionArguments`, and thus the deconstruction infers the wrong thing. We'll need to, for every tuple element, check to see whether the type was inferred, and if so, use the type from the original property. Because @jcouv is updated the handling of tuple symbols in the compiler, this part will wait until he's done.

**Comment by 333fred** [comment] 2019-11-13 17:42
The first part of this fix has been merged.

**Closed** 2022-01-26 03:32 UTC
Labels: Bug, Area-Compilers, New Language Feature - Nullable Reference Types
