### ISSUE TITLE
Incorrect suggestion to use 'var'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15736] opened 2016-12-07 22:42 UTC
![image](https://cloud.githubusercontent.com/assets/4564579/20989874/37cff744-bc8b-11e6-82f6-edc557f8ff53.png)

In this case, I'm foreaching over an InlineCollection, but i'm stating that the values will be of type "Run".  This is effectively doing a ```.Cast<Run>()``` on the expression i'm foreaching over.  If this gets changes to 'var', then the type will be 'Inline', not 'Run'.  And if that happens, i won't be able to call "run.Text" below (as .Text is not defined on 'Inline').

**Comment by CyrusNajmabadi** [comment] 2016-12-07 22:42
tagging @dpoeschl

**Comment by dpoeschl** [comment] 2016-12-07 23:39
Good find!

**Comment by Pilchie** [comment] 2016-12-12 21:31
Dupe of https://github.com/dotnet/roslyn/issues/14052.

**Closed** 2016-12-12 21:31 UTC
Labels: Area-IDE, Resolution-Duplicate
