### ISSUE TITLE
Diff view can't understand preview language features

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#35937] opened 2019-05-24 10:00 UTC
**Version Used**: 

Visual Studio 2019 both 16.1.0 and 16.2.0 Pregview 1.0

**Steps to Reproduce**:

1. write any C# 8.0 code e.g. [this](https://github.com/ufcpp/UfcppSample/commit/7a47b5cf20a3de37529b79e80edff356e67b57b6)
2. show it with "Compare with Previous..."

**Expected Behavior**:

No error in the Diff view.

**Actual Behavior**:

The Diff view can't understand preview language features.

![image](https://user-images.githubusercontent.com/3760955/58320057-ca212300-7e55-11e9-9a34-5a13434fc031.png)

**Comment by sharwell** [comment] 2019-05-24 18:21
@jasonmalinowski is this fixed by https://github.com/dotnet/roslyn/pull/35859?

**Comment by jasonmalinowski** [comment] 2019-05-24 18:25
Likely, we should test to confirm though since sometimes diff view can be a bit funky.

**Comment by jinujoseph** [comment] 2019-10-10 17:14
Closing this issue.
Confirmed by vendors, no repro in 16.4.Preview2

**Comment by jasonmalinowski** [comment] 2019-10-10 17:17
@jinujoseph Which features was this tested with? The features in the bug were migrated to 8.0 but a new preview feature might still be broken.

**Comment by jinujoseph** [comment] 2019-10-10 17:25
It was validated against the repro steps provided above. reopened to validate compiler feature still under preview flag. ( if any )

**Closed** 2022-10-31 22:56 UTC
Labels: Bug, Area-IDE
