### ISSUE TITLE
Incorrect definite assignment error with local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13739] opened 2016-09-12 16:45 UTC
The following program produces an incorrect error.

```cs
using System;

class Program
{
    public static void Main(string[] args)
    {
        int u;
        M();
    https://github.com/dotnet/roslyn/issues/13739
        Console.WriteLine(u); // error: use of unassigned local variable 'u'
        return;

        void M()
        {
            goto La;
        Lb: return;
        La: u = 3;
            goto Lb;
        }
    }
}
```

**Comment by agocke** [comment] 2016-09-12 17:56
@gafter Ha! Nice trick using the link as a label.

I guess the problem is we don't trim unreferenced labels from the pending branches?

**Comment by gafter** [comment] 2016-09-13 00:01
The problem is that we don't initialize the initial value of the "written by local function" set to `Unreachable()`.

**Comment by agocke** [comment] 2016-09-13 21:19
@gafter Agreed.

On the plus side, this is an error in precision, not in soundness, so no unsafe program can be compiled because of this bug.

**Comment by agocke** [comment] 2016-10-03 20:08
@dotnet/roslyn-compiler Could one more person take a look at this please?

**Comment by agocke** [comment] 2016-10-03 20:18
Woops, wrong issue :)

**Comment by agocke** [comment] 2016-10-04 06:55
Resolved by #14190

**Closed by agocke** 2016-10-04 06:55 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
