### ISSUE TITLE
Cancelling a lightbulb produces a yellow-bar

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42115] opened 2020-03-03 00:15 UTC
```
  <entry>
    <record>796</record>
    <time>2020/03/03 00:14:42.940</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.OperationCanceledException: The operation was canceled.&#x000D;&#x000A;   at System.Threading.CancellationToken.ThrowOperationCanceledException()&#x000D;&#x000A;   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#x000D;&#x000A;   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#x000D;&#x000A;   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#x000D;&#x000A;   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#x000D;&#x000A;   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetCodeFixes(ITextBufferSupportsFeatureService supportsFeatureService, ISuggestedActionCategorySet requestedActionCategories, Workspace workspace, Document document, SnapshotSpan range, Func`2 addOperationScope, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.&lt;&gt;c__DisplayClass40_4.&lt;TryGetSuggestedActionSets&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by mavasani** [comment] 2020-03-03 18:07
Duplicate of https://github.com/dotnet/roslyn/issues/41218, which has just recently been fixed by the VS Editor team.

**Closed by mavasani** 2020-03-03 18:07 UTC
