### ISSUE TITLE
Overload resolution fails in complex scenario with Delegate overloads and extension methods

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#55691] opened 2021-08-18 06:13 UTC
**Version Used**: 
Version 17.0.0 Preview 4.0 [31616.459.main]

**Steps to Reproduce**:

```C#
var app = new WebApp();

app.Map("/sub", builder =>
{
    builder.UseAuth();
});


class WebApp : IAppBuilder, IRouteBuilder
{
    public void UseAuth()
    {
        
    }
}

public interface IAppBuilder
{
    void UseAuth();
}

public interface IRouteBuilder
{

}

static class AppBuilderExtensions
{
    public static IAppBuilder Map(this IAppBuilder app, PathSring path, Action<IAppBuilder> callback) => app;
}

public static class RouteBuilderExtensions
{
    public static IRouteBuilder Map(this IRouteBuilder routes, string path, Delegate callback) => routes;
}

struct PathSring
{
    public PathSring(string? path)
    {
        Path = path;
    }

    public string? Path { get; }

    public static implicit operator PathSring(string? s) => new PathSring(s);

    public static implicit operator string?(PathSring path) => path.Path;
}
```

**Expected Behavior**:

AppBuilderExtensions.Map would be chosen by the overload resolution algorithm.

**Actual Behavior**:

The call is ambiguous between the following methods or properties: 'AppBuilderExtensions.Map(IAppBuilder, PathSring, Action<IAppBuilder>)' and 'RouteBuilderExtensions.Map(IRouteBuilder, string, Delegate)'	C:\Users\david\source\repos\ConsoleApp133\WebApplication1\Program.cs

It seems like the implicit conversion on `PathString` throws off the overload resolution completely. If `PathString` is replaced with string, it works as expected.

cc @cston

**Comment by cston** [comment] 2021-08-18 18:14
Fixed in https://github.com/dotnet/roslyn/pull/55357.

**Comment by cston** [comment] 2021-08-18 22:07
> I noticed that a small change of specifying the parameter type brings back the same error.

Thanks for catching this @halter73, I'll investigate.

**Comment by cston** [comment] 2021-09-02 15:40
The ambiguity error for the second example (with explicit parameter type)
```
app.Map("/sub", (IAppBuilder builder) =>
{
    builder.UseAuth();
});
```
was resolved as "by design" in [C# LDM-2021-08-23](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-08-23.md#better-function-member-now-ambiguous-in-some-cases).

**Closed by cston** 2021-09-02 15:40 UTC
Labels: Area-Compilers, New Feature - Lambda Improvements
