### ISSUE TITLE
Incorrect formatter behavior in implicit conversions to a tuple

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#33910] opened 2019-03-06 22:39 UTC
```C#
class C
{
    public static implicit operator (C, C)(C c) => throw null;
    public static implicit operator int?(C c) => throw null;
}
```

Currently, the formatter wants to insert a space between the type and the argument list here. It should not, like all other conversions.

**Comment by sharwell** [comment] 2019-03-06 22:47
Second one is a duplicate of #31571

**Closed** 2019-03-15 23:37 UTC
Labels: 4 - In Review, Area-IDE, Bug, IDE-Formatter, New Language Feature - Tuples
