### ISSUE TITLE
Add using for assembly attribute can introduce error with existing attribute in AssemblyInfo.cs

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#11755] opened 2016-06-03 21:34 UTC
Memory dump & repro solution
%internal_share%\public\tomat\Bugs\11755

`Ctrl+.` here $$, add missing using.

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

[assembly: AssemblyVersion("")$$]
```

**Comment by jasonmalinowski** [comment] 2016-06-08 19:32
@balajikris can you take a quick look to see if this is a regression or something that might indicate an Update 3-worthy fix? @tmat, what version was this with?

**Comment by tmat** [comment] 2016-06-08 20:02
Some dogfood on top of U2.

**Comment by balajikris** [comment] 2016-06-08 20:56
Works for me in some roslyn version via roslyn updater on U2, and on building latest stabilization locally. I tried a few variations with a new project and also by opening the repro solution provided and it always works. I'm seeing "add usings, fully qualify, generate type" in that order.

@tmat could you pls verify on a latest build to double check?

**Comment by balajikris** [comment] 2016-06-08 20:57
ah, just reading it more clearly. assertion failed. okay, onto the dump then.

**Comment by balajikris** [comment] 2016-06-08 21:14
So, when i applied Add-using, I still saw a red squiggly after the refactoring completed. It read, duplicate Assembly version attribute. Because, it was indeed defined in AssemblyInfo.cs as well as in Program.cs.

True enough, under debug bits, the assertion mentioned in the bug fails. It says refactoring or code action introduced errors and these were the errors.

~~~
+		[0]	C:\Users\balajik\Documents\Visual Studio 2015\Projects\ConsoleApp16\ConsoleApplication14\Properties\AssemblyInfo.cs(35,12): error CS0579: Duplicate 'AssemblyVersion' attribute	Microsoft.CodeAnalysis.Diagnostic {Microsoft.CodeAnalysis.CSharp.CSDiagnostic}
+		[1]	C:\Users\balajik\Documents\Visual Studio 2015\Projects\ConsoleApp16\ConsoleApplication14\Properties\AssemblyInfo.cs(2,1): hidden CS8019: Unnecessary using directive.	Microsoft.CodeAnalysis.Diagnostic {Microsoft.CodeAnalysis.CSharp.CSDiagnostic}
~~~

the second diagnostic is a direct consequence of the first one. Note that the diagnostic was surfaced at the location in AssemblyInfo.cs this time, I suppose it could be surfaced on either locations and the number of diagnostics varies according to where it was surfaced.

I do not see a problem here. Is there something we should do about this?

**Comment by balajikris** [comment] 2016-06-08 21:16
should we special case this and choose to not offer add-using here? I'm not sure.

**Comment by balajikris** [comment] 2016-06-14 16:47
clearing assignment for re-triage. I was asked to investigate this for U3 and my findings are above. I'm not sure what we should do about this? 
cc @Pilchie

**Comment by Pilchie** [comment] 2016-06-28 16:57
We could add some sort of conflict marker to the preview for cases like this, but I'm not sure it's worth it

**Comment by CyrusNajmabadi** [comment] 2024-11-05 18:46
Closing out as no repro.

**Closed by CyrusNajmabadi** 2024-11-05 18:46 UTC
Labels: Bug, Area-IDE
