### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.Basic.BasicReferenceHighlighting.Highlighting test failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18714] opened 2017-04-14 20:03 UTC
```
Stacktrace

MESSAGE:
\r\nExpected:\r\n[77..80)\r\nActual:\r\n[77..80)\r\n[91..94)\r\nDifferences:\r\n [77..80)\r\n++> [91..94)\r\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator) at Roslyn.VisualStudio.IntegrationTests.Basic.BasicReferenceHighlighting.Verify(String marker, IDictionary`2 spans) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicReferenceHighlighting.cs:line 54 at Roslyn.VisualStudio.IntegrationTests.Basic.BasicReferenceHighlighting.Highlighting() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicReferenceHighlighting.cs:line 39
```

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/2672/testReport/junit/Roslyn.VisualStudio.IntegrationTests.Basic/BasicReferenceHighlighting/Highlighting/

**Comment by 333fred** [comment] 2017-04-15 19:24
Dupe of https://github.com/dotnet/roslyn/issues/18705.

**Closed by 333fred** 2017-04-15 19:24 UTC
Labels: Area-IDE, Test
