### ISSUE TITLE
Error message for invalid csharp_using_directive_placement is not clear

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67299] opened 2023-03-14 16:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-plugins-keep-crashing/10179228)._

---
[severity:It's more difficult to complete my work]
![image.png](https://aka.ms/dc/image?name=Bfb93f8e1616c4139931354a416949176638020583054758670_20221022-195825-image.png&tid=fb93f8e1616c4139931354a416949176638020583054758670)

De problem occurs in Visual Studio 2022. It prevents the usage of most refactoring tools. Very annoying when your used to it.
We actually switched back to VS 2019 because of this.

---
#### Feedback Bot on 10/23/2022, 08:19 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/24/2022, 02:53 AM: 

(private comment, text removed)
#### Freek Felling on 10/31/2022, 08:42 AM: 

(private comment, text removed)
#### Freek Felling on 10/31/2022, 08:31 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 11/1/2022, 04:25 AM: 

(private comment, text removed)
#### Feedback Bot on 3/7/2023, 10:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2023-03-14 16:35
In the above case, the user has the following in their .editorconfig file:

```ini
# usings outside namespace
csharp_using_directive_placement = true
```

This is producing an exception in the following parsing code:

https://github.com/dotnet/roslyn/blob/f9946775cde0bf9034bfe29e8cf3e01b5e099795/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions_Parsing.cs#L55-L60

The parsing code should be updated to provide a more detailed (actionable) error message for users.

**Comment by sharwell** [comment] 2023-03-14 16:39
Duplicate of #49407

**Closed by sharwell** 2023-03-14 16:39 UTC
Labels: Area-IDE, untriaged
