### ISSUE TITLE
Invalid cast exception when using "or" for compatible types in pattern matching in a switch expression

### ISSUE THREAD

**Issue by m-gallesio** [dotnet/roslyn#62640] opened 2022-07-14 08:30 UTC
### Description

When using:
- pattern matching
- in a switch expression
- using an `or` clause to test for multiple types
- trying to cast the result to a type which should be compatible with all of them
the codes compiles, but at runtime an `InvalidCastException` is raised.

### Reproduction Steps

```csharp
byte a = 1;
short b = 1;
sbyte c = 1;
ushort d = 1;
int e = 1;

object[] numbers = new object[] { a, b, c, d, e };

foreach (var number in numbers)
{
    Console.WriteLine(number switch
    {
        byte or short or sbyte or ushort or int => (int)number,
        _ => -1
    });
}
```

### Expected behavior

The result get correctly cast to the specified, compatible type.

### Actual behavior

An `InvalidCastException` is raised:
> Unable to cast object of type 'System.Byte' to type 'System.Int32'.

### Known Workarounds

Separating the clauses works as expected:

```csharp
foreach (var number in numbers)
{
    Console.WriteLine(number switch
    {
        byte   n => (int)n,
        short  n => (int)n,
        sbyte  n => (int)n,
        ushort n => (int)n,
        int n=> n,
        _ => -1
    });
}
```

This specific use case might also get obsoleted by .NET 7's generic math capabilities.

### Configuration

- .NET SDK 6.0.302
- Windows 10 Pro 21H2 19044.1826
- x64

**Comment by CyrusNajmabadi** [comment] 2022-07-14 13:56
Closing this out as by design. If you'd like different behavior a change to the language would be necessary. Those can be requested over at dotnet/csharplang.  Thanks!

**Closed by CyrusNajmabadi** 2022-07-14 13:56 UTC
Labels: Area-Compilers, untriaged
