### ISSUE TITLE
[x64](3.0.100-preview-010184) Switch expression bug

### ISSUE THREAD

**Issue by RUSshy** [dotnet/roslyn#33054] opened 2019-02-01 08:00 UTC
Hi

Looks like the new pattern matching feature broke old style switch expression

https://github.com/rds1983/StbImageSharp/blob/master/src/StbImageSharp/PngDecoder.cs#L714

Doesn't compile anymore 

```
  PngDecoder.cs(714, 38): [CS1003] Syntax error, ':' expected
  PngDecoder.cs(714, 70): [CS1002] ; expected
  PngDecoder.cs(714, 70): [CS1513] } expected
  PngDecoder.cs(718, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(774, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(793, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(842, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(878, 39): [CS1003] Syntax error, ',' expected
```

**Comment by jaredpar** [comment] 2019-02-01 22:53
@gafter can you verify this is a dupe of the switch bugs you've already fixed?

**Comment by gafter** [comment] 2019-02-09 00:53
@jaredpar I do not believe this has been fixed

**Comment by alrz** [comment] 2019-02-10 08:16
Looks like a dupe for https://github.com/dotnet/roslyn/issues/33208

**Comment by gafter** [comment] 2019-02-15 02:02
Fixed in https://github.com/dotnet/roslyn/pull/33279 for dev16.0

**Closed by gafter** 2019-02-15 02:02 UTC
Labels: Area-Compilers, Bug

**Comment by gafter** [comment] 2019-02-15 23:37
As a workaround, declare a named local constant to hold the constant value you are using for the switch case.
