### ISSUE TITLE
csc.exe and vbc.exe should support /LargeAddressAware switch

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#12523] opened 2016-07-14 19:33 UTC
Creating a 32-bit .exe with the managed compilers can never address more than 2GB of RAM.
C++ apps can by using the `/largeaddressaware` switch, but this isn't offered by the managed compilers.
`editbin.exe` as a post-build step is an option, but `editbin.exe` is a VC tool that requires VS to be installed (it's not in the MSBuild toolset), so its use is unreliable from a CI standpoint and will fail if the user doesn't happen to be running inside a "Developer Command Prompt" window.

See also this StackOverflow question: [Can I set LARGEADDRESSAWARE from within Visual Studio?](http://stackoverflow.com/questions/2597790/can-i-set-largeaddressaware-from-within-visual-studio/2598395)

**Comment by rainersigwald** [comment] 2017-01-26 01:12
Looks like this is a duplicate of #9209 (which I like better because it got tentatively added to an earlier milestone than this one).

**Comment by jaredpar** [comment] 2017-03-09 19:11
Closing and letting #9209 track the issue.

**Closed by jaredpar** 2017-03-09 19:11 UTC
Labels: Area-Compilers, Feature Request
