### ISSUE TITLE
Ctrl+click a URL in a string literal takes you to the String class definition instead of following the link

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38770] opened 2019-09-19 21:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/716317/ctrlclick-a-url-in-a-string-literal-takes-you-to-t.html)._

---
What steps will reproduce the problem?
1. Put a URL inside a C# string literal. Ex: &quot;https://github.com/dotnet/corefx/issues/30691&quot;
2. Inside the VS C# editior, click the URL while holding the Ctrl key

What is the expected output? What do you see instead?

I expect for the URL to be opened in my default browser. Instead, I get taken to the System.String class metadata or a decompiled version of the System.String reference assembly (which all no-op, but that's another issue).

---
#### Visual Studio Feedback System on 8/29/2019, 07:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment] 2020-10-13 23:20
@sharwell Was this closed because because it's low priority or because it was already supposed to be fixed by #24910? I still see this issue in 16.8 previews.

**Comment by halter73** [comment] 2020-10-13 23:25
I see the "Resolution-Not Reproducible". I'm going to reopen this then. Feel free to reach out to me on Teams or something if you need help with a repro.

**Comment by halter73** [comment] 2020-10-13 23:44
I figured out this issue doesn't repro without VsVim. I filed an issue there (https://github.com/VsVim/VsVim/issues/2857). Sorry for the spam.

**Closed by halter73** 2020-10-13 23:44 UTC
Labels: Area-IDE, Bug, Developer Community, Resolution-Not Reproducible
