### ISSUE TITLE
EnC breaks debugging if it is supposed to hit another break point

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#14621] opened 2016-10-19 19:05 UTC
**Version Used**: 
ML 25818.01
**Steps to Reproduce**:
Create a New C# console application
Add the following lines to the Main method:

```
System.Diagnostics.Debugger.Break();
//string s = "test";
System.Diagnostics.Debugger.Break();
```

Start Debugging.
At the first breakpoint, uncomment string s = "test"
Hit Continue

**Expected Behavior**:
VS reaches the next breakpoint successfully.

**Actual Behavior**:
A window pops up saying that 'Source is not Available'. Locals, Autos, and other related Expression Evaluator windows are unpopulated.

**Comment by ManishJayaswal** [comment] 2016-10-26 19:12
This may be a dupe of internal bug 277603

**Comment by ManishJayaswal** [comment] 2016-11-02 22:42
I can't repro this in latest d15rel. It was probably a dupe as the VSO bug got fixed yesterday.

**Closed by ManishJayaswal** 2016-11-02 22:42 UTC
Labels: Area-Interactive, Interactive-EnC
