### ISSUE TITLE
Subsequent build should not succeed when the first build was failed by warnings treated as error

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#38040] opened 2019-08-16 05:47 UTC
**Version Used**: 
VS16.3.0 Preview 2

**Steps to Reproduce**:

1. Create a C#/VB console app
1. Turn on **Treat Warning as Error**
1. Add anything that would generate compiler warning, for example, a Task returning async method with empty body: `async Task M() { }`
1. Build
1. Build again

**Expected Behavior**:

Both builds should fail

**Actual Behavior**:

The second build succeeds

**Comment by gafter** [comment] 2019-08-16 21:14
@mavasani Will this be addressed by https://github.com/dotnet/roslyn/pull/37948 ?

**Comment by mavasani** [comment] 2019-08-16 21:24
@gafter Yes, this seems to be a duplicate of that one.

**Closed** 2019-08-17 00:21 UTC
Labels: Area-Analyzers, Area-Compilers
