### ISSUE TITLE
[VB.NET] Sometimes, editor doen't append missing `( )` after method names

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#48581] opened 2020-10-14 02:01 UTC
Som,etimes, VB editor adds the missing `()` (like in comments 1, 2, and 3 in the next sample) after method names, and sometimes it doesn't (like in comments 4, 5 in the next sample). 
```VB.NET
    Class Foo
        Sub Test()
        End Sub
    End Class

    Sub Test2()
    End Sub

    Sub main()
        Dim x As New Foo
        x.Test() ' 1
        Test2() ' 2
        System.IO.Directory.GetCurrentDirectory() ' 3

        Dim y As Action = AddressOf x.Test
        y.Invoke ' 4
        Dim z As Date?
        Dim w = z.GetValueOrDefault ' 5

    End Sub
```

Is there a reason for this?

**Comment by CyrusNajmabadi** [comment] 2020-10-14 02:56
Would take a community PR here.  @VBAndCs are you interested in contributing?  If so, we can help walk you through a PR here :)

**Comment by AdamSpeight2008** [comment] 2020-10-14 16:45
When method takes no (or in case of extension method, additional) arguments the parenthesis are optional.

**Comment by CyrusNajmabadi** [comment] 2020-10-14 17:17
@AdamSpeight2008 yes.  but the issue here is that for some no-arg methods we automatically add parens, and for some we do not.  it's the inconsistency that's the issue.

**Comment by AdamSpeight2008** [comment] 2020-10-14 18:31
@CyrusNajmabadi  was that clear from original post. If we do take this please make it an option based choice.

**Comment by CyrusNajmabadi** [comment] 2020-10-14 19:23
Isn't this what the first line says:

> Sometimes, VB editor adds the missing () (like in comments 1, 2, and 3 in the next sample) after method names, and sometimes it doesn't (like in comments 4, 5 in the next sample).

The issue is the inconsistency.  We do this for some method calls and not for others, seemingly randomly.

> If we do take this please make it an option based choice

There is already an option controlling if VB pretty lists your code or not.  This feature is already controlled by this.  I don't see why we would need anything beyond that.

**Comment by VBAndCs** [comment] 2020-10-14 22:18
I think there may be a reason for this behaviour, but didn't end up well.
In LinQ, many methods has a property-like names (such as Count, FirstOrDeafsult...etc), so, in VB, it is better not to add the `()`. 
So, maybe LinQ can be excluded from this fix, or at least LinQ methods that are named like properties. 
This of course doesn't explain why `Invoke` and `GetValueOrDefault` do't get their `()`.  

@CyrusNajmabadi 
I hope I can help, but now I am overwhelmed in two projects, and have to mind capacity not time. Thanks

**Comment by paul1956** [comment] 2020-10-14 22:40
If VB does not get () everywhere C# does then ChangeSignature fails when the () is missing, reported as a separate issue.

**Comment by VBAndCs** [comment] 2020-10-14 22:56
@paul1956
> If VB does not get () everywhere C# does then ChangeSignature fails when the () is missing, reported as a separate issue.

I don't get what you mean. Can you explain?
In general, this issue is about the pretty listing behaviour, not about language syntax rules. Auto adding `()` or not, the code compiles.

**Comment by CyrusNajmabadi** [comment] 2020-10-14 22:59
> I hope I can help, but now I am overwhelmed in two projects, and have to mind capacity not time. Thanks

Sure.  If you get some time later let us know and we can help you out here.

**Comment by jmarolf** [comment] 2020-10-14 23:50
> If VB does not get () everywhere C# does then ChangeSignature fails when the () is missing, reported as a separate issue

That is just a bug we should fix in my opinion. We can just check if parens exist for the call site being updated and add them if they do not.

**Comment by paul1956** [comment] 2020-10-15 05:25
@jmarolf details #48090

**Comment by Youssef1313** [comment] 2020-10-16 21:52
@jmarolf @CyrusNajmabadi There is a contradiction between this, and the design meeting conclusions in https://github.com/dotnet/roslyn/issues/45170#issuecomment-644392752

While they are separate features (pretty listing vs an analyzer) they're closely related.

In https://github.com/dotnet/roslyn/issues/45170#issuecomment-644392752, it requests that the analyzer should be configurable.

Note that https://github.com/dotnet/roslyn/issues/45170#issuecomment-644392752 is more general. The conclusion was to allow configuring both invocations and properties access. Pretty lister currently deals only with invocations, and it's not completely working.

I believe it will be more organized if this was taken to a design meeting review that discusses *both* issues as they're related.

**Comment by CyrusNajmabadi** [comment] 2020-10-16 22:06
this seems just like a straight up bug.  We do this for some methods, but not others.  I can't see any legit reasons for that.

**Comment by Youssef1313** [comment] 2020-10-16 22:52
@CyrusNajmabadi I don't disagree. But it's unclear how both features will work together if #45170 is implemented, or if there is no need for it, and should pretty lister remove extra parentheses in properties or not, etc.

**Comment by VBAndCs** [comment] 2020-10-17 06:19
Additional note:
While `System.IO.Directory.GetCurrentDirectory( )` gets `( )`,
`Dim x = System.IO.Directory.GetCurrentDirectory`  doesn't.
The rule seems to add `()` if no `Call` or Return value.
But, this rule is not consistent, as in `y.Invoke` and `Dim z = y.Invoke`.

**Comment by CyrusNajmabadi** [comment] 2020-10-17 17:26
`Invoke` is a special method, so there's likely just some of our code that doesn't know to handle it.  THe rest seems like a straight up bug.  If you open a PR to fix this @VBAndCs i can likely review it asap.

**Comment by VBAndCs** [comment] 2020-10-26 03:51
Note:
The editor should not append `()` after a function name inside its body, as VB allow using the function name to store its return value. This is legal in VB, and there is no recursion  involved:
```VB.NET
    Function Foo() As Integer
        Foo = 1
        Foo = Foo * 10
        Foo = Foo + 3
    End Function
```

But just adding `()` in the right-hand side will make it a recursive expression:
`Foo = Foo() + 3`

**Comment by CyrusNajmabadi** [comment] 2024-10-21 21:21
Closing as we are unlikely to be changing these experiences.

**Closed by CyrusNajmabadi** 2024-10-21 21:21 UTC
Labels: Bug, help wanted, Area-IDE, Language-VB
