### ISSUE TITLE
Roslyn compiler still doesn't recognize extension methods from libraries written in C++/CLI

### ISSUE THREAD

**Issue by MulleDK19** [dotnet/roslyn#3220] opened 2015-06-01 17:03 UTC
#365

This is NOT fixed. Any extension method defined in C++/CLI, with or without assembly-level extension attribute, will not be found by Roslyn. Both C# and VB.NET is affected.

Tested using VS 2015 RC.

Test case: http://treesoft.dk/temp/MethodExtensionBug.zip

**Comment by gafter** [comment] 2015-06-01 18:51
#365 is not listed as fixed in milestone 1.0-rc1 or 1.0-rc2. It is listed as fixed in 1.0-stable, which is VS 2015 RTM. That is not the version you tested with.

**Comment by gafter** [comment] 2015-06-01 18:52
Your test file at http://treesoft.dk/temp/MethodExtensionBug.zip does not exist.

**Comment by MulleDK19** [comment] 2015-06-01 20:01
Link should work now.

This issue is stated to be fixed by #2506, but the issue isn't that it doesn't work without an assembly-level extension attribute, the issue is that it doesn't work regardless of whether there's an assembly-level extension attribute.

**Comment by gafter** [comment] 2015-06-01 21:25
The problem is that you named your extension method `IsValid` but you tried to use it with the name `Exists`.

That "fix" (actually, re-introduction of an old compiler bug) only applied to C#. VB requires the assembly-level attribute as it always did.

**Comment by MulleDK19** [comment] 2015-06-01 23:19
Weird. I could have sworn I quadruple checked the test case. I even copied the extension method from my actual project directly where it's called Exists().

Well, better a broken test case than a broken compiler.

Thanks.

**Closed** 2015-06-02 23:34 UTC
Labels: Area-Compilers, Bug, Resolution-Duplicate, Verified
