### ISSUE TITLE
Pressing Apply from Preview Changes for IntelliCode does nothing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28931] opened 2018-07-29 07:51 UTC
I'm debugging and I notice that I have a &quot;IDE0019 Use pattern matching&quot; suggestion in the Visual Studio editor. I click Preview Changes so that I can look at the suggested changes. I like the changes, so I press Apply. Nothing happens. No changes are applied. This is because the file is locked during debugging, but VS didn't tell me that--it just acted as if it was ignoring my pressing the Apply button. Either it shouldn't offer to make changes or it should tell me when I try to apply them that it cannot do so while the file is locked for debugging.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/297852/pressing-apply-from-preview-changes-for-intellicod.html
VSTS ticketId: 652498_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-07-31 17:12
Related to #681

**Comment by sharwell** [comment] 2018-07-31 17:14
Duplicate of #681

**Closed by sharwell** 2018-07-31 17:14 UTC
Labels: Area-Interactive, Bug, Need Design Review
