### ISSUE TITLE
Indentation in WinForms Designer generated variables block is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42911] opened 2020-03-30 18:30 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/947130/indentation-in-winforms-designer-generated-variabl.html)._

---
[regression] [worked-in:16.3.x]
When creating a new WinForms Form and adding controls to it, the indentation of the generated variables does not match our settings, see attached file "codeeditor.png". The indentation is done with spaces, not with tabs.

Our indentation settings are a bit special (use 2 spaces for all languages). See "settings.png" (upper half of screenshot).

One thing to note: when I change the settings and reopen the settings dialog again, there is a info message "The indentation settings ... conflict with each other", though I did not change anything  in beetween (lower half of screenshot "settings.png")

I am not sure when this broke, but we observed it since a few months. So I guess that it worked for 16.3.x.

---
#### Visual Studio Feedback System on 3/12/2020, 03:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Wolfgang Knauf on 3/12/2020, 04:09 AM: 

The same happens if an eventhandler is created by doubleclicking an event in the property grid: the handler method has wrong indentation.
#### Zheng Li [MSFT] on 3/13/2020, 00:53 AM: 

<p>Dear customer, thanks for your feedback.</p>
<p>Try to getting more details from the screenshots, but failed, see below loadded failed screenshot, could you pease attached it again.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/123029-feedback.png"></p>
<p>And if the issue also can reproduce on new winforms application? or all types project(WPF/Console etc.) also have the same issue?</p>
<p>Thanks<br>
Zheng</p>

#### Wolfgang Knauf on 3/13/2020, 01:11 AM: 

<p>Attached are the two screenshots. As far as I remember there was an error message at the end ob submitting this issue.</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/123010-codeeditor.png">codeeditor.png</a><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/123031-settings.png"><br></a></p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/123031-settings.png">settings.png<br></a></p><p>It happens also for a new WinForms app (.NET Framework). It does not seem to happen for WPF (at least the event handler indentation is OK)<br><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/123031-settings.png"></a></p><br>

#### Zheng Li [MSFT] on 3/13/2020, 02:56 AM: 

(private comment, text removed)
#### Wolfgang Knauf on 3/13/2020, 03:35 AM: 

<p>Hi Zheng,</p><p>thanks for the clarification about "Smart/Block". </p><p>The indentation issue is weird: if you create a new form and add a few controls, only the first control has wrong indentation, the others are OK (does not  depend on the control type). If you first close designer before adding any control and reopen it and add other controls, it seems to work, too. Maybe related to Visual Studio restart?</p><p>While trying to reproduce this, I had some situations where indentation was wrong later, but I cannot define a rule when this happens. And in our "real" code I also find wrong indentation in existing code when a control was added to an older form. Also indentation might be wrong for a block of several controls.</p><p>Best regards</p><p>Wolfgang</p>

#### Visual Studio Feedback System on 3/16/2020, 06:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2020-04-07 06:13
**Design Review Notes**
We are not sure how difficult is this to get fixed. If someone found an easy way to fix this..we will be willing to accept the solution here

**Comment by WolfgangHG** [comment] 2020-09-10 06:58
It seems this was fixed in the meantime - I cannot reproduce it with Visual Studio 16.7.3.

Thanks!

**Comment by WolfgangHG** [comment] 2021-05-04 11:08
Can this be closed by anyone? I am not able to do so, though this issue was created from my ticket in the developer community.

**Comment by CyrusNajmabadi** [comment] 2021-05-04 15:34
Closing out as the op says it's no longer reproes. Thanks!

**Closed by CyrusNajmabadi** 2021-05-04 15:34 UTC
Labels: Area-IDE, Bug, IDE-Formatter, help wanted
