### ISSUE TITLE
Convert to struct has errors on uninitiated members

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33407] opened 2019-02-15 00:04 UTC
**Version Used**: Visual studio 2019

**Steps to Reproduce**:

1. Have code

```csharp
public class Class
{
    void MyMethod()
    {
        var tuple = (3, "string");
    }

```
2. Place cursor before open parenthesis and type (Ctrl+.) to open codefixes
![image](https://user-images.githubusercontent.com/8293542/52825445-a178d880-3071-11e9-822e-47189759e04c.png)

3. Select Convert to struct

**Expected Behavior**:
Generated struct gives no errors.

**Actual Behavior**:
Generated struct gives errors on uninitialized members Item1 and Item2.
![image](https://user-images.githubusercontent.com/8293542/52825427-9160f900-3071-11e9-92e5-3ecd00e1f702.png)

Adding these declarations fixes warnings:
```
internal struct NewStruct
{
    public int Item1 { get; }
    public string Item2 { get; }
...
```

@CyrusNajmabadi Julien mentioned you might want to take a look. :)

**Comment by jcouv** [comment] 2019-02-15 00:11
Given the high bar for p4/GA at this point, I wonder if we should: 1) try to fix for p4/GA, or 2) disable the fix for now, or 3) leave as-is for p4/GA.
Tagging @jinujoseph to advise.

**Comment by jinujoseph** [comment] 2019-02-15 00:17
Lets see what it takes to fix it

**Comment by ivanbasov** [comment] 2019-02-16 01:44
Found a root cause:
1. https://github.com/dotnet/roslyn/blob/defeca5d0e44915fc978cfd93d3de2e4a6d0dbf4/src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs#L232 requires member to be not implicitly declared.

2. However, those ItemN fields are implicitly declared.

**Comment by mavasani** [comment] 2019-02-19 22:38
I wonder if the refactoring for unnamed tuple literals is providing a real value add here with the chosen field names. Even if we were to fix the scenario listed here so `Convert to struct` generates a struct with fields named Item1, Item2, etc., it is more then likely that user has to go to each such declared field and invoke inline rename to rename the fields to something sensible for the introduced struct.

I feel we already have a different 2 step refactoring to achieve the same result:

1. @jcouv recently added a refactoring to `Add name to tuple element` which allows you to name the tuple elements based on the usages.
2. Once the names have been added using that refactoring, current convert to struct refactoring works fine and would generate reasonable field names for the struct.

We can possibly improve the overall experience here by enhancing convert to struct refactoring on unnamed tuples to detect what names `Add name to tuple element` refactoring would add on each unnamed element and use that as the field names. This is possibly not something to be considered for 16.0 though.

@kendrahavens @jinujoseph - do we have any feedback on this scenario from customers? Otherwise, not sure if this will meet the 16.0 bar at this point, especially given it is a refactoring, and we can then discuss the desired experience at next week's design meeting.

**Comment by jinujoseph** [comment] 2019-02-19 22:44
No customer feedback yet. 
I am ok to move this for 16.1 atthis point and wait for more feedback.

**Comment by ivanbasov** [comment] 2019-02-21 07:42
Fix merged. Target: 16.0 Preview 4

**Closed by ivanbasov** 2019-02-21 07:42 UTC
Labels: Area-IDE, Bug
