### ISSUE TITLE
Add a right click context menu to copy fully qualified name of the Class or method.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40308] opened 2019-12-11 22:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/825141/add-a-right-click-context-menu-to-copy-fully-quali.html)._

---
Add a right click context menu to copy fully qualified name of the Class or method.

It is useful in many scenarios such as --
1. Adding function breakpoint  (Method level qualified name). 
2. Adding anything related to COM (Class level qualified name).

---
#### Visual Studio Feedback System on 11/18/2019, 11:32 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.   We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2019-12-19 19:07
Duplicate of #39506

**Closed by sharwell** 2019-12-19 19:07 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review
