### ISSUE TITLE
Looping between IDE0002 and CS0110.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/roslyn#64768] opened 2022-10-16 20:53 UTC
In my code:

    public const LogLevel LogLevel = Microsoft.Extensions.Logging.LogLevel.Debug;

Causes:  IDE0002 can be simplified

Simpified:

    public const LogLevel LogLevel = LogLevel.Debug;

Causes: CS0110	The evaluation of the constant value for 'LogLevel' involves a circular definition.

**Comment by CyrusNajmabadi** [comment] 2022-10-16 20:57
Dupe of https://github.com/dotnet/roslyn/issues/45739.

**Closed by CyrusNajmabadi** 2022-10-16 20:57 UTC
Labels: Area-IDE, Feature Request, untriaged
