### ISSUE TITLE
Roslyn Services Editor test failed with "Attempt to access unloaded App Domain"

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#21361] opened 2017-08-08 03:54 UTC
See https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/8746/

**Comment by Pilchie** [comment] 2017-08-08 16:37
Duplicate of #15497

**Closed by Pilchie** 2017-08-08 16:37 UTC
Labels: Flaky, Resolution-Duplicate, Test
