### ISSUE TITLE
CSharpCodeActions/GenerateMethodInClosedFile Test Recurring failures

### ISSUE THREAD

**Issue by jfleisher** [dotnet/roslyn#26204] opened 2018-04-17 18:43 UTC
Skipping Test because of recurring failures. The test has failed regularly on master/job/windows_release_vs-integration and master-vs-deps/job/window_release_vs-integration over the last week.

**Comment by sharwell** [comment] 2018-04-18 12:33
Each failure should be a duplicate of either #26038 or #26042.

**Closed** 2020-07-22 14:17 UTC
Labels: Area-IDE, Flaky
