### ISSUE TITLE
Intellisense MRU precedence

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16053] opened 2016-12-21 20:59 UTC
**Version Used**: 2.0.0.61213

1. Say you have a type `MyFantasy`...
2. You include `using System.Runtime.InteropServices;` (obviously)
3. Now every time you type `MF.` the `PARAMFLAG` item gets preselected.

Shouldn't the fact that you used `MF` last time to commit `MyFantasy` make it preferred choice next time?

**Comment by Pilchie** [comment] 2016-12-31 23:10
@rchande - did something happen to MRU here?

**Comment by miloush** [comment] 2017-01-14 18:00
Not sure if the same issue, but typing `TN` preselects `tn` if that is a local in scope, even if `TN` was used to commit `TypeName` previously.

**Comment by CyrusNajmabadi** [comment] 2017-01-14 18:12
intellisense uses a case-aware, bucketing system for determining which item to select.  Exact algorithm is in code.  But general idea is we look for things like:

1. case-sensitive, exact match.
2. case-insensitive, exact match.
3. case-sensitive, prefix match.
4. case-insensitive, prefix match.
5. case-sensitive, substring match.
6. case-insensitive, substring match.
7. case-sensitive, camelcase match.
8. case-insensitive, camelcase match.
9. etc.

If mutiple matches are found in one of those buckets *then* MRU comes into play.  MRU will not override a 'better' bucket match higher in the list. 

Note that right now the MRU system itself is very 'weak'.  in that all we track is the items which were committed.  We do not track waht you typed to commit that item.  It would be an intriguing idea to store what you typed as well.  Then, if you typed that exact same string, we could elevate your previous committed item to be best as that would be a strong signal you wanted that item again.

**Comment by miloush** [comment] 2017-01-15 00:52
Hm, I admit that doesn't look good for my issue. Any rule I can think of is just beaten by the simplicity of remembering what was typed.

In any case, this doesn't seem to be a bug then.

**Comment by CyrusNajmabadi** [comment] 2017-01-15 04:18
It's not a bug per se. But I imagine we could still do better here.  In that regard it's an interesting feature request.

**Comment by rchande** [comment] 2017-01-17 23:55
I did take a stab at this but wound up breaking some tests that assert the opposite behavior. This is probably something we could achieve but not for 2.0. @Pilchie to what milestone would you recommend moving this?

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:44
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-19 21:44 UTC
Labels: Bug, Area-IDE
