### ISSUE TITLE
Attempting to resolve a using on certain generic declarations are favoring their non-generic equivalents

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19575] opened 2017-05-17 04:15 UTC
``` C#
        private ImmutableArray<string> GetEvaluationRuleNames()
        {
            IEnumerable<string> <---- Resolve this
            return ImmutableArray.CreateRange(;

            foreach (ExportFactory<IEvaluationHandler, IEvaluationHandlerMetadata> factory in HandlerFactories)
            {
                factory.Metadata.EvalutionRuleName
            }
        }
```

**Expected:** To be only offered to resolve the generic version
**Actual:** Get both generic and non-generic:

![image](https://cloud.githubusercontent.com/assets/1103906/26138242/01732730-3b0b-11e7-987e-6062c469ce5d.png)

**Comment by davkean** [comment] 2017-05-17 04:17
This is annoying because I usually blindly accept the first one if I know it's a type that exists.

**Comment by davkean** [comment] 2017-05-17 04:19
I'm guessing this is due to the way that compiler parses this - as once I've added the using the rest of the ide thinks this this is `System.Collections.IEnumerable`  instead of `System.Collections.IEnumerable<string>`:
![image](https://cloud.githubusercontent.com/assets/1103906/26138332/cbb611c4-3b0b-11e7-9962-1769f5cb19e9.png)

**Comment by SolderedMushroom** [comment] 2017-05-17 14:35
Definitely seems like a bug, since merely adding `new` before that makes Intellisense realize it's a generic.

**Comment by Pilchie** [comment] 2017-05-17 16:51
Want to see if we can do something better here too?

**Comment by CyrusNajmabadi** [comment] 2017-05-17 19:07
This is likely fixed with the work i've already done.

@SolderedMushroom this is because this scenario is highly ambiguous (it could be a type or an expression) the presence or absence of certain tokens helps the compiler 'lock on' to the more appropriate interpretation.  Note, any changes here may potentially regress behavior in other scenarios as the user *may* actually want to be typing an expression.

**Comment by CyrusNajmabadi** [comment] 2017-05-17 19:08
Possible dupe of: https://github.com/dotnet/roslyn/pull/19467

**Closed** 2017-06-21 19:24 UTC
Labels: Area-IDE, Bug
