### ISSUE TITLE
C# parser runs out of memory when given a VSIX file as text

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#2771] opened 2015-05-14 22:34 UTC
Consider the following app:

```C#
using System.IO;
using Microsoft.CodeAnalysis.CSharp;

class Program
{
    const string vsix = @"D:\Roslyn\Open\Binaries\Debug\Roslyn.VisualStudio.Setup.vsix";

    static void Main(string[] args)
    {
        CSharpSyntaxTree.ParseText(File.ReadAllText(vsix));
    }
}
```

Change the path to the Roslyn.VisualStudio.Setup.vsix file as necessary.
Add a reference to Microsoft.CodeAnalysis.dll and Microsoft.CodeAnalysis.CSharp.dll and run the app.

Run the app and wait. Eventually you get an OutOfMemoryException. Of course, this is a contrived example, but it is very close to an OutOfMemory condition reported by one of our partner teams.

Expect:
We should fail the parse long before running out of memory. The parser is not making reasonable forward progress (the error rate is too high).

I propose that we add a "fuse" to the parser that tracks the rate of errors being generated (number of errors per KB of parsed text, for example) and stops further parsing if the error rate is too high.

**Comment by pharring** [comment] 2015-05-14 23:01
Same thing happens with the VB parser, BTW.

**Comment by pharring** [comment] 2015-05-14 23:48
@jaredpar for triage. @VSadov, @AlekseyTs heads up (incoming).

**Comment by pharring** [comment] 2015-05-14 23:50
I should note that the use of a VSIX file is just an example. There are undoubtedly other binary files that will cause such runaway behavior.

**Comment by Pilchie** [comment] 2015-05-15 20:59
An alternative would be to use a binary file heuristic (I think a common one is > some threshold number of null bytes in the first 1000 characters)

**Comment by pharring** [comment] 2015-05-15 21:31
Indeed, SourceText looks for consecutive NUL chars: http://source.roslyn.io/#Microsoft.CodeAnalysis/Text/SourceText.cs,240
I would think the Lexer can do that quite efficiently.

**Comment by gafter** [comment] 2015-05-18 01:10
The strategy I'm working on essentially counts the number of "bad character" errors reported by the scanner. When it exceeds a threshold it treats the file as binary. This is a generalization of the "null character" heuristic and is actually easier to implement.

**Comment by VSadov** [comment] 2015-05-18 16:26
I agree with @gafter here. "Bad character" case would be a superset of null bytes, unpaired surrogates and other junk that is very uncommon in actual source. 
Both C# and VB lexers already have to deal with bad chars, so it makes sense to consider text a complete garbage if it has too many (1000?) bad characters and make the rest of the text one big error.

**Comment by Pilchie** [comment] 2015-05-18 16:30
Yes, that approach sounds perfectly reasonable too.

**Comment by gafter** [comment] 2015-05-18 20:08
I filed #2867 for a possible corresponding issue for VB.

**Comment by gafter** [comment] 2015-05-20 23:03
Fixed in #2957

**Comment by gafter** [comment] 2015-05-20 23:04
@pharring Please Verify

**Closed by gafter** 2015-05-20 23:03 UTC
Labels: 4 - In Review, Area-Compilers, Bug

**Comment by jcouv** [comment] 2016-12-14 18:52
FYI this caused an un-intended side-effect. Some bad text files trigger this failure mode, this breaks the rountripping invariant, which results in IDE crashes.
See more details in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=217398

**Comment by gafter** [comment] 2016-12-14 23:12
I believe the code added to fix this was intended to preserve the round-tripping invariant. Sounds like a bug in that new code.
