### ISSUE TITLE
Pattern mathing on generic types does not work

### ISSUE THREAD

**Issue by fanoI** [dotnet/roslyn#18981] opened 2017-04-25 18:03 UTC
**Version Used**: 
Visual Studio 2017

**Steps to Reproduce**:

 Create a function like this:
```cs
     void TestGenericPatternMatching<T>(T anT)
        {
            switch (anT)
            {
                case int v: 
                    break;
               case string s:
                    break;
            }
        }
```cs

**Expected Behavior**:
Pattern matching works

**Actual Behavior**:
The code above does not compiles with a strange error "an expression of type T can not be handled by an int", the match with object is OK but well not really useful (anything matches with object).

**Comment by sharwell** [comment] 2017-04-25 18:12
This looks like a duplicate of #16195. If this is not correct let me know! 👍

**Closed** 2017-04-25 18:12 UTC
Labels: Resolution-Duplicate

**Comment by sharwell** [comment] 2017-04-25 18:14
:memo: Also very relevant is dotnet/csharplang#154.

**Comment by fanoI** [comment] 2017-04-25 20:53
But then there will be a 7.1 version of C# to download? Or we have to wait until C# 8.0?
It seems really a big bug!

**Comment by sharwell** [comment] 2017-04-25 22:02
@fanoI The milestone indicators say 7.1, but those aren't always correct. Best way to find out would be to ask in one of the linked issues. :smile:
