### ISSUE TITLE
Performance tests for solution wide refactorings

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#2637] opened 2015-05-11 15:11 UTC
Hi together! 

Matt Gertz wrote together some interesting aspects measuring and observing performance in Roslyn and the heads behind this. Old, but very cool post: http://blogs.msdn.com/b/csharpfaq/archive/2014/01/15/roslyn-performance-matt-gertz.aspx 

I know you take performance very serious there at the Roslyn team and the work you have done is great at all! Further, I don't know if this question was asked before, I could not find the appropriate thread. So please let me ask again: 

Are there performance tests to measure and ensure performance goals of solution-wide refactorings for small, mid-sized and large solutions? During a talk, I try to show the performance of Roslyn by "Remove unnecessary Usings" in the Roslyn solution. It took a very long time on my i7 quad code PC with 16 GB RAM. Would be cool to read any statement from the Roslyn team.

Many thanks in advance!

**Comment by jmarolf** [comment] 2015-05-11 19:57
"remove all usings" - I assume you were trying to remove all of the unused usings in a document? Or was this solution wide?

For the document case there should have been no slowdown because we've already done the computation to determine that they are unnecessary, so essentially applying the code-action just deletes the text.

For applying "remove unused usings" across a solution, that is going to take time.  We may need to bind your entire solution in order to perform this operation.  If you have just opened your solution and nothing is in the cache, that would be equivalent to rebuilding your entire solution.  

I would appreciate if you could share a reproduce-able scenario so we could have a look. 

Tagging @pharring  and @heejaechang who can talk more about the tests being run to verify these scenarios.

**Comment by heejaechang** [comment] 2015-05-11 20:21
@robinsedlaczek "Refactoring" is too broad word that can mean multiple things and features.

normally refactoring "feature" itself can't be applied solution wide. there are special refactoring feature such as "rename" that can be applied solution wide and we do track performance of it and make sure we don't regress than our goal.

there is code fix "Fix All" feature that can apply any random code fix to solution wide. @mavasani I believe currently we do not track performance of this. since it is a engine that has multiple heuristics to attempt to apply a code fix to solution wide and performance might be heavily depends on code fix itself not engine.

I think we do need to have some "fix all" performance tests for in box code fixes such as "remove unused usings", but right now, we don't have them yet. for now, supporting "Fix all" properly is first priority.

anyway, I think we should add performance tests for most common in box code fixes.

**Comment by mavasani** [comment] 2015-05-11 20:28
I agree @heejaechang we need to have performance tests for FixAll scenarios. I'll file an issue to track that work item.

**Comment by robinsedlaczek** [comment] 2015-05-12 07:16
Yes, sorry. I correct my wording above. Of course, I mean "Remove Unnecessary Usings" resp. "Fix All" features. Please see the screenshot. Here just the steps to reproduce:

1. Open Visual Studio.
2. Open Roslyn solution (or any other).
3. Use CTRL+. on using statements.

![solution-wide refactoring](https://cloud.githubusercontent.com/assets/2900224/7581552/c2a1eeda-f884-11e4-9239-b6018072b3e0.png)

4. Select "Fix all occurrences in Solution".
5. Wait... Wait.. Wait... :) (it took about 2 minutes for the Roslyn solution here until the Preview Changes dialog appeared).
6. Confirm the Preview Changes dialog.
7. It took 2 minutes and 34 seconds (excluding manual file save operations).

![execute suggested action](https://cloud.githubusercontent.com/assets/2900224/7581792/67c63518-f887-11e4-8eec-b93208be5511.png)

Question: Visual Studio is completely blocked during the operation. I know you have to respin syntax trees of all documents etc., but I does not feel really async. Maybe you can show a progress indicator?

**Comment by heejaechang** [comment] 2015-05-12 07:28
@robinsedlaczek you can commit before preview window shows up. previous will take almost exactly same time as you committed the change since it does almost exactly same thing.

actual committing can't be Async since that can corrupt files if some other operation (including operation that is not under Roslyn's control) mess with files.

but we should have some kind of progress bar if possible.

**Comment by robinsedlaczek** [comment] 2015-05-12 07:49
Yes, mustn't be async, but progress bar gives nice feedback.

How can I commit without waiting for the Preview Changes dialog? I did not click "Preview Changes". I clicked the "Solution" link.

Another point: If I undo all the changes via CTRL+Z, it also takes a lot of time. Yes, this is understandable. But during undo action, Visual Studio is not responding. Please see screenshot below. So here we have no progress indication or any other indication that showing that an operation is running (except the wait cursor). The not responding Visual Studio window does not feel really good. 

![undo](https://cloud.githubusercontent.com/assets/2900224/7582255/09c35c52-f88c-11e4-869c-addf6c406d35.png)

**Comment by heejaechang** [comment] 2015-05-12 07:52
@robinsedlaczek ah, you are right. "Fix All" preview is not Async operation @mavasani @shyamnamboodiripad we should consider making it Async as well.

and yes, we should show some kind of progress bar for undo as well even though undo is not cancellable action.

**Comment by robinsedlaczek** [comment] 2015-05-12 07:53
Sounds great! :)

**Comment by mavasani** [comment] 2015-05-12 16:22
@robinsedlaczek Regarding the below:
_2.Wait... Wait.. Wait... :) (it took about 2 minutes for the Roslyn solution here until the Preview Changes dialog appeared)._

Well, that's expected if you working on a freshly opened solution. Building Roslyn.sln from command line takes about the same time, and we need to force diagnostics across entire solution to compute unnecessary usings, so you should expect at least the same time for a cold FixAll operation.

However, note that we try to cache and re-use the computed diagnostics in the IDE, so the performance of FixAll should get better with time on an opened solution.

@heejaechang Yes, we should consider making fix all preview async and add progress bar. All this work would be after 1.0-stable milestone though.

**Comment by robinsedlaczek** [comment] 2015-05-12 18:05
@mavasani Yes, I can live with that. And every experienced developer should know what it means to refactor a complete solution. But as I said, some progress indication would be cool to generate a fluent experience for the user. E.g. showing the files that are processed or something like that. Consider it for the upcoming milestone please.

**Comment by shyamnamboodiripad** [comment] 2015-05-12 19:31
> "Fix All" preview is not Async operation @mavasani @shyamnamboodiripad we should consider making it Async as well.

@heejaechang Yes this would be nice. We should discuss this with folks on the editor side for I think we will need editor API changes for this. Each action for Fix All is actually an ISuggestedAction (just like the top level ISuggestedAction for the primary suggestion in the light bulb menu). To make the preview for Fix All async, we would have to make ISuggestedAction.Invoke() async. But doing that today will mean that Invoke() for the primary light bulb suggestion will also have to become async which would be bad - applying the primary suggestion should not be an asynchronous operation. We would probably need to split the ISuggestedAction API to implement this correctly...

I agree with @mavasani that unfortunately this will have to be post-1.0-stable.

**Comment by heejaechang** [comment] 2015-05-12 19:40
@shyamnamboodiripad well, since now RTM is just another release, I dont think it not in 1.0 is that unfortunate. I think releasing features as they are ready is way better than before where even already done feature has to wait until RTM. or fix was to wait another 1~2 year.

...

also, for Fix All preview window, is making Invoke Async is only way? is it because we need to invoke it to determine whether to show link or not? otherwise, I think we can do Invoke in a task and show progress bar while waiting for the task.

**Comment by shyamnamboodiripad** [comment] 2015-05-12 19:47
@heejaechang :+1: about relasing features as they become ready :)

Also, I think you are right we should be able to invoke the action asynchronously on our side for our actions. But if we wanted the solution to be general for any links (flavored actions) that providers can show in the preview pane, then shouldn't the progress bar to be on the editor side?

**Comment by heejaechang** [comment] 2015-05-12 19:50
@shyamnamboodiripad ya, I think progress bar should be something platform provide. not us. same for other progress bar we mentioned above as well.

**Comment by srivatsn** [comment] 2015-08-28 19:01
We should probably create an issue to track providing a progress mechanism for fix all providers.

**Comment by srivatsn** [comment] 2015-08-28 19:01
Since we have custom fixall providers the context object likely need a ReportProgress method on it.

**Comment by sharwell** [comment] 2015-08-28 19:08
> I agree @heejaechang we need to have performance tests for FixAll scenarios. I'll file an issue to track that work item.

Related to DotNetAnalyzers/StyleCopAnalyzers#1199.

We do most of our testing using a console application to more accurately profile the analyzers (and eventually code fixes) separate from the presentation layer in Visual Studio.

**Comment by robinsedlaczek** [comment] 2015-08-29 13:46
Fair enough to separate performance tests of analyzers, code fixes and refactorings from the presentation layer. Make sense at all, of course. But I hope, the Visual Studio team tracks an item as well, to improve the UX I described above.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 18:09
Yes.  We test performance now and have an analyzer runner framework we can use.  We also heavily rewrote the fix-all systems to be scalable and to be able to handle large solutions.  When creating new fixers we routinely run them on projects the size of roslyn (around 600+ virtual projects) ensuring they can complete in reasonable time.  Note: it still may take a couple of minutes to finish, but it does make solid progress and we feel like that is reasonable time.

Closing this out as completed.

**Closed by CyrusNajmabadi** 2022-10-28 18:09 UTC
Labels: Area-IDE, Discussion
