### ISSUE TITLE
Field assigned via ref return warns about being un-assigned

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#12283] opened 2016-06-29 15:52 UTC
See `RefReturningInvocation` test.
The code runs fine, but the warning is incorrect.

```C#

        [Fact, CompilerTrait(CompilerFeature.RefLocalsReturns)]
        public void RefReturningInvocation()
        {
            string source = @"
class C
{
    static int i;

    static void Main()
    {
        int x = 0, y = 0;
        M(x, y) = 42;
        System.Console.WriteLine(i);
    }
    static ref int M(int a, int b) { return ref i; }
}
";

            var comp = CompileAndVerify(source, expectedOutput: "42");
            comp.VerifyDiagnostics(
                // (4,16): warning CS0649: Field 'C.i' is never assigned to, and will always have its default value 0
                //     static int i;
                Diagnostic(ErrorCode.WRN_UnassignedInternalField, "i").WithArguments("C.i", "0").WithLocation(4, 16)
                );
        }
```

@VSadov FYI

**Comment by gafter** [comment] 2016-07-01 23:57
Taking a ref of a variable should normally be considered an assignment. For example, the following program results in no diagnostic:

```cs
class Program
{
    static int i;
    static void Main(string[] args)
    {
        M(ref i);
    }
    static void M(ref int i) { }
}
```

**Comment by VSadov** [comment] 2016-07-02 00:10
ahould behave the same as if the field is passed as burned parameter.
Seems to be a bug.

**Comment by VSadov** [comment] 2016-07-02 00:13
Also check ref  assignment to a byref  local

**Comment by jaredpar** [comment] 2016-09-13 18:19
Looks like a duplicate of #10544

**Closed by jaredpar** 2016-09-13 18:19 UTC
Labels: Area-Compilers, Bug, New Language Feature - Ref Locals and Returns
