### ISSUE TITLE
Visual Studio adds second quotation mark in unappropriate situations #59427 [Still not fixed]

### ISSUE THREAD

**Issue by DrPepperBianco** [dotnet/roslyn#76138] opened 2024-11-28 11:06 UTC
> @DrPepperBianco It appears that the majority case for this issue was already fixed for the 17.2 release. Can you clarify the exact scenario that you are running into that is still causing problems? 

 _Originally posted by @sharwell in [#59427](https://github.com/dotnet/roslyn/issues/59427#issuecomment-1751430567)_

@sharwell I am a little bit lost. You said the majority is fixed, but it is not at all fixed for me.

A very simple scanrio:

I have code like this:
```csharp
string @string = FooBar;
```

And I want to add Quotes. I position the cursor bevor FooBar and hit »"«. The result is this:
```csharp
string @string = ""FooBar;
```
With the cursor being between the quotes.

In practice, I usually end up with something like this:
```csharp
string @string = ""FooBar";
```
because my muscle memory typed the quote before, then end, arrow-left, quotation after the word, before I realized that Visual Studio broke the code again.

PS: For some reason, I couldn’t answer to you question, but had to create a new issue instead. Sorry for the inconvenvience.

**Comment by CyrusNajmabadi** [comment] 2024-11-30 21:58
Closing as dupe of https://github.com/dotnet/roslyn/issues/71898.

**Closed by CyrusNajmabadi** 2024-11-30 21:58 UTC
Labels: Area-IDE, untriaged
