### ISSUE TITLE
Please update build instructions for roslyn

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#21053] opened 2017-07-22 22:54 UTC
I have dotnet core 2.0 installed
```
> dotnet --info
.NET Command Line Tools (2.0.0-preview2-006502)

Product Information:
 Version:            2.0.0-preview2-006502
 Commit SHA-1 hash:  07dfded669

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16246
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006502\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
but the build still fails.  
```
Build FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(57,5): error : The version of Microsoft.NET.Sdk used by this project is insufficient to support .NET Standard 2.0 which is required by this project's
references.  Please install version 2.0 or higher of the .NET Core SDK. [C:\source\roslyn\Open\src\Tools\RoslynPublish\RoslynPublish.csproj]
    0 Warning(s)
    1 Error(s)
```

Please list the version of dotnet core that needs to be installed for roslyn to build

**Comment by sharwell** [comment] 2017-07-24 14:57
I believe this is a duplicate of #20945, where the goal is to make things "just work" without having to update the instructions.

**Closed by sharwell** 2017-07-24 14:57 UTC
