### ISSUE TITLE
Adding inheritdoc on class ignores added comments in intelisense

### ISSUE THREAD

**Issue by lugospod** [dotnet/roslyn#48994] opened 2020-10-28 20:14 UTC
1. Class MigrationDAO implements interface IMigrationDAO
2. If I add /// <inheritdoc cref=“IMigrationDAO”/> on top of MigrationDAO class, interface implementation method receives a comment that is comming from IMigrationDAO file - OK (first attached image)
3. When I add /// <inheritdoc cref=“IMigrationDAO”/> on top of Class MigrationDAO, then when hovering over MigrationDAO type there is no information (second attached image)
4. When I remove /// <inheritdoc cref=“IMigrationDAO”/>from MigrationDAO, then hovering over MigrationDAO displays the comments above MigrationDAO class (third attached image)
5. Even if I remove all comments above MigrationDAO except  /// <inheritdoc cref=“IMigrationDAO”/>, hover over MigrationDAO still displays nothing

In my opinion, hovering over type MigrationDAO should display either the comments that are above MigrationDAO class or at least comments from IMigrationDAO. 

![image](https://user-images.githubusercontent.com/29342608/97490435-22b8f180-1961-11eb-9097-4e5cbaa05fd6.png)
![image](https://user-images.githubusercontent.com/29342608/97490524-4419dd80-1961-11eb-9f51-649880b17a51.png)
![image](https://user-images.githubusercontent.com/29342608/97490469-2fd5e080-1961-11eb-9eae-807865415293.png)

**Comment by sharwell** [comment] 2020-11-04 15:35
This looks like a case where invalid XML leads to empty rendered documentation. Can you enable XML documentation file output for the build and verify that the XML comments do not contain errors? This is the approach I recommend:

```xml
<PropertyGroup>
  <!--
    Make sure any documentation comments which are included in code get checked for syntax during the build, but do
    not report warnings for missing comments.

    CS1573: Parameter 'parameter' has no matching param tag in the XML comment for 'parameter' (but other parameters do)
    CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
    CS1712: Type parameter 'type_parameter' has no matching typeparam tag in the XML comment on 'type_or_member' (but other type parameters do)
  -->
  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  <NoWarn>$(NoWarn),1573,1591,1712</NoWarn>
</PropertyGroup>
```

**Comment by CyrusNajmabadi** [comment] 2024-10-22 16:25
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-22 16:25 UTC
Labels: Bug, Area-IDE
