### ISSUE TITLE
named argument type is not being used by intellisense, quick fixes, etc.

### ISSUE THREAD

**Issue by kayle** [dotnet/roslyn#14332] opened 2016-10-06 18:12 UTC
VS 2015 Update 3

```
using System;

namespace N1
{
    public class Class1
    {
        public void Foo()
        {
            Baz(action: c => c.Bar()); // missing "Add using fix"
            Baz(1, c => c.Bar()); // ok
        }

        public void Baz(int x = 0, Action<Class1> action = null) { }
    }
}

namespace N2
{
    public static class Extensions
    {
        public static int Bar(this N1.Class1 x) => 5;
    }
}
```

**Expected Behavior**:
Add using fix should be available for both errors.

**Comment by Pilchie** [comment] 2016-10-06 18:19
I have a feeling this is a dupe of something @CyrusNajmabadi  or @jmarolf  fixed already where we stopped  looking before extension methods.

**Comment by Pilchie** [comment] 2016-10-17 17:19
Anyway, I can't repro this in VS "15" Preview 5, so I'm going to close it out.

**Comment by Pilchie** [comment] 2016-10-17 17:19
(Would love it if someone could check if we have a unit test for it though...)

**Closed** 2016-10-17 18:04 UTC
Labels: Area-IDE, Bug, Resolution-Fixed
