### ISSUE TITLE
.editorconfig - indexer brackets at call-site

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#33134] opened 2019-02-05 09:07 UTC
Is there a .editorconfig option to control the spacing between indexer brackets? The option I'm after would:

(a) produce a diagnostic and fix for:
```csharp
array[index]
```

(b) produce no diagnostic, and VS would generate code as:
```csharp
array[ index ]
```

though some people would want the exact opposite setting.

**Comment by CyrusNajmabadi** [comment] 2019-02-05 09:13
csharp_space_between_square_brackets?

**Comment by yaakov-h** [comment] 2019-02-08 01:19
Using Visual Studio Community v15.9.4, that option and several others seem to have no effect.

See: https://github.com/yaakov-h/SteamKit/tree/editorconfig

If I open SteamKit2/SteamKit2.sln from there, I expect to see all sorts of warnings and errors related to spacing, as per [the editorconfig](https://github.com/yaakov-h/SteamKit/blob/editorconfig/.editorconfig#L24-L35).

Instead, after VS finished background analysis, there are no warnings, errors, or messages show in the Error List pane.

**Comment by yaakov-h** [comment] 2019-02-08 01:31
Created #33231 as related to can't-get-anything-to-work.

**Comment by sharwell** [comment] 2019-02-08 04:02
This is another duplicate of #19055 (invalid .editorconfig items are silently ignored, but should show a warning). See https://github.com/dotnet/roslyn/issues/33231#issuecomment-461682920 for more information.

**Closed by sharwell** 2019-02-08 04:02 UTC
Labels: Area-IDE, Bug, Need More Info
