### ISSUE TITLE
Syntax highlighting in <code> XML doc elements

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#54416] opened 2021-06-26 14:17 UTC
Please add a `language` attribute to the `<code>` element which recognizes the value `C#` or `csharp` and causes the quick info display in the IDE to highlight the syntax:

![image](https://user-images.githubusercontent.com/8040367/123515952-abf70400-d667-11eb-97dd-75dc1725180b.png)

**Comment by sharwell** [comment] 2021-07-06 19:07
Duplicate of #39154

**Closed by sharwell** 2021-07-06 19:07 UTC
Labels: Area-IDE, untriaged
