### ISSUE TITLE
IOperation: NoneOperation in nameof expression

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#27740] opened 2018-06-12 09:48 UTC
**Version Used**: 
Microsoft.CodeAnalysis NuGet v2.8.2

**Steps to Reproduce**:
Consider the next program, which prints `IOperation` info on visited `nameof` expression:
```csharp
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace RoslynNameOfBug
{
    class Program
    {
        static void Main()
        {
            const string source = @"
namespace N
{
    class C
    {
        string M()
        {
            return nameof(System.Linq.Enumerable);
        }
    }
}";

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source);
            var compilation = CSharpCompilation.Create("test.dll", new[] { tree }, new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
            }, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
            var model = compilation.GetSemanticModel(tree);

            ImmutableArray<Diagnostic> compilerDiagnostics = compilation.GetDiagnostics(CancellationToken.None);
            Diagnostic[] compilerErrors = compilerDiagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
            if (compilerErrors.Any())
            {
                throw new Exception();
            }

            var methodSyntax = tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First();

            var block = (IBlockOperation)model.GetOperation(methodSyntax.Body);

            var walker = new NameOfWalker();
            walker.Visit(block);
        }

        private sealed class NameOfWalker : OperationWalker
        {
            public override void VisitNameOf(INameOfOperation operation)
            {
                Console.WriteLine($"INameOfOperation.Argument type: {operation.Argument.GetType().Name}");
                Console.WriteLine($"INameOfOperation.Syntax: {operation.Syntax}");

                base.VisitNameOf(operation);
            }
        }
    }
}
```
**Expected Behavior**:
A type that implements `IMethodReferenceOperation` for `INameOfOperation.Argument`.

**Actual Behavior**:
Output:
```
INameOfOperation.Argument type: NoneOperation
INameOfOperation.Syntax: nameof(System.Linq.Enumerable)
```

**Comment by jcouv** [comment] 2018-06-12 20:55
Tagging @AlekseyTs for triage. Thanks

**Comment by mavasani** [comment] 2018-06-26 15:05
Dupe of https://github.com/dotnet/roslyn/issues/8909. Argument to nameof is a BoundTypeExpression, which is currently exposed as operation kind None.

**Closed by mavasani** 2018-06-26 15:05 UTC
Labels: Area-Compilers, New Feature - IOperation, _Product-level triaged
