### ISSUE TITLE
Add search for quick action "Generate overrides..."

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47806] opened 2020-09-17 19:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1038488/add-search-for-quick-action-generate-overrides.html)._

---
When I was using EntityFrameworkCore and used the quick action to generate overrides, there a dozens of methods. Now I just want to override a specific Method and I know the name of it. It would be easier if you could simply search for it in the "Pick members" window. Just add a search bar at the beginning of the list (see screenshots).

---
#### Feedback Bot on 5/20/2020, 02:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### william on 7/28/2020, 07:40 AM: 

I often find myself scrolling though large lists of overrides for some objects, a simple search bar which filters the overrides screen (&quot;Pick Members&quot;) would save time and would be awesome to have
#### jeliknes [MSFT] on 8/21/2020, 08:51 AM: 

<p>Moved issue to GitHub. <a target='_blank' href="https://github.com/dotnet/efcore/issues/22163">https://github.com/dotnet/efcore/issues/22163</a> this is where the team tracks issues and feature requests.</p>

#### jeliknes [MSFT] on 8/21/2020, 09:16 AM: 

We moved this issue to a relevant GitHub project. Please comment and track it at this URL: https://github.com/dotnet/efcore/issues/22163

#### Patrick Hintermayer on 8/24/2020, 02:46 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/175431/980a2d72-f3b6-6ec6-ada7-d408deb5bd73.html" nodeid="175431">@jeliknes [MSFT]</a></p><p>The suggestion is not EF specific and that's the reason the issue on GitHub got closed.</p><p>I just mentioned EF because this was my use case but this is a general Visual Studio topic.</p>

**Comment by CyrusNajmabadi** [comment] 2020-09-17 21:50
Yes, adding a searh/filter box to our "pick members" dialog seems reasonable.  it could either be a simple case-insensitive substring match, or it could actually use the pattern-matcher logic we have elsewhere.

**Comment by Hefaistos68** [comment] 2021-04-14 09:10
While at it, please uncheck all members by default. Nobody wants to override all 500 members of the System.Windows.Forms.Form class.

**Comment by CyrusNajmabadi** [comment] 2021-04-14 17:44
> I just want to override a specific Method and I know the name of it.

In this case, the simple way that already exists is to just type `override YourMethodName`.  Completion will just select and allow you to commit that entry.

**Comment by CyrusNajmabadi** [comment] 2021-04-14 17:44
> While at it, please uncheck all members by default. Nobody wants to override all 500 members of the System.Windows.Forms.Form class.

There's a 'Deselect all' button:

![image](https://user-images.githubusercontent.com/4564579/114755409-71d7c080-9d0e-11eb-956d-250cb56f81f3.png)

**Comment by Hefaistos68** [comment] 2021-04-14 17:50
Didn't notice among all the check boxes 🙄

**Comment by CyrusNajmabadi** [comment] 2021-04-14 17:55
> Didn't notice among all the check boxes 🙄

It's got first-class prominence in the UI :)

![image](https://user-images.githubusercontent.com/4564579/114756676-d9dad680-9d0f-11eb-919e-c85b4e3111ff.png)

**Comment by mmarinchenko** [comment] 2021-04-27 09:41
> While at it, please uncheck all members by default. Nobody wants to override all 500 members of the System.Windows.Forms.Form class.

+1

It also would be nice to have a tree with type hierarchy instead of plain member list.

**Comment by mmarinchenko** [comment] 2021-04-27 09:51
> There's a 'Deselect all' button
The problem is I have to click it every time I open this dialog. There is no need for this.

> I just want to override a specific Method and I know the name of it.
> In this case, the simple way that already exists is to just type `override YourMethodName`.

I may be not sure about arguments list. Classes often overload methods at different points in the hierarchy.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 14:55
> +1

Unchecking by default just puts the burden in the other direction if you want to override everything. 

It's literally one click to deselect everything. So I don't see this being needed. 

> It also would be nice to have a tree with type hierarchy instead of plain member list.

I think this would be fine. We'd take a contribution here if you wanted to provide it @mmarinchenko   thanks!

**Comment by mmarinchenko** [comment] 2021-04-27 15:04
>  I don't see this being needed

99% of the time I use this dialog to override methods of large classes from frameworks such as Xamarin or ASP.NET. So I have to do 99 additional clicks out of every 100 dialog usages. 1 click vs 99 clicks is a huge difference :)

> We'd take a contribution here if you wanted to provide it @mmarinchenko

Fair enough)

**Comment by Hefaistos68** [comment] 2021-04-27 15:10
In all the years this dialog exists (I am using VS since it was called VS 97 beta) I have literally NEVER overridden all methods in a class. So please uncheck by default.

**Comment by Zerotask** [comment] 2021-04-27 15:15
> > I just want to override a specific Method and I know the name of it.
> 
> In this case, the simple way that already exists is to just type `override YourMethodName`.  Completion will just select and allow you to commit that entry.

And what If I want to override multiple similar named methods? Would be your solution then to repeat that?
I don't see any disadvantages of having a search box at this dialog. It would be completely optional to use

**Comment by Hefaistos68** [comment] 2021-04-27 15:16
> > I just want to override a specific Method and I know the name of it.
> 
> In this case, the simple way that already exists is to just type `override YourMethodName`. Completion will just select and allow you to commit that entry.

`Ctrl+.`, `Cursor Down`, `Enter`, `Y`, `Enter `is quite faster than typing `override YourMethodName` (given that there is a search box where I can type into) and if there where an accelerator for the "create overrides..." menu entry it would be even faster.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 15:20
> So I have to do 99 additional clicks out of every 100 dialog usages

It's one extra click per dialog that comes up. 

And you are flipping this for people that do override everything and would be need to do the same in reverse. How often are you overriding members, and how is one extra click each time you do that so impactful?

**Comment by CyrusNajmabadi** [comment] 2021-04-27 15:26
> Ctrl+., Cursor Down, Enter, Y, Enter is quite faster than typing override YourMethodName (

There's no way this is true. Override completion is `ov<space>`. 

That's it. You get the override list which is now filterable to whatever item you want using all our pattern/camel-hump matching. That's much faster than 5 different keystrokes and chords spread across different uis

**Comment by CyrusNajmabadi** [comment] 2021-04-27 15:27
Here's a solution I can get behind. If you click unselect-all (or the opposite), we remember that the next time the dialog opens and we maintain that selection style.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 15:33
> Yet all this does not void the idea of an search box, 

A contribution to add the search box would be accepted as well :-)

**Comment by CyrusNajmabadi** [comment] 2021-04-27 15:35
Here are the three things we would take contributions on:

1. Allow for a tree view to make it easier to group by inheritance type. 
2. Remember the 'select-all/deselect-all' choice. 
3. Have a way to filter down the set to those that match a provided pattern.

**Comment by mmarinchenko** [comment] 2021-04-27 16:18
> In this case, the simple way that already exists is to just type `override YourMethodName`.

This works great for simple classes with one or two methods. In fact, the dialog is not needed at all for such cases.

> you are flipping this for people that do override everything and would be need to do the same in reverse.

I understand the logic itself but how does this apply to real-world use cases? When you need to implement an interface or virtual methods of an abstract class then "implement-them-all" is good default choice. But when you need to override something (hence the term!) then it's quite opposite. Who on earth is more likely to override everything than something specific?

> How often are you overriding members

On the server side not often actually. But this is a way of live in Xamarin... or any event-driven framework. You never need to override all the methods of Activity or Form but you constantly need to override several `On<SomeEvent>()` methods.

>  It's one extra click per dialog that comes up.

> how is one extra click each time you do that so impactful?

Any extra click is a sign of poor UI design. This annoys users. More importantly, it's a sign that developers don't understand how their product is actually being used.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 17:11
> This works great for simple classes with one or two methods.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 17:13
> This annoys users. 

But that's your argument for people who aren't you.   Not ever path can have the same amount of work put into it by the user.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 17:14
Regardless, this conversation does not seem to be bearing any fruit.  You've clearly stated that the defaults are not desirable for you.  I've outlined approaches we would be willing to explore and accept to make it better for your particular use case.  I don't think there is any value in continuing to state that you want a change here to make thins more ideal for your use case.

**Comment by mmarinchenko** [comment] 2021-04-27 20:18
@CyrusNajmabadi

I appreciate approaches which you've outlined ;) I wrote my last comment only because you asked me questions about clicks earlier. It's a pity that when you received my answers you started to discuss me rather than dialog issue and effectively asked me to shut up.

The only important thing I can add now is that if you find yourself in a situation where you need to override entire behavior of the class (not the interface) you are probably inheriting wrong type. Or the hierarchy needs to be decomposed. So I was genuinely interested in real-world examples that demonstrate when the people you're talking about would have to click "Select all" button. But now I see that it's called _argument for people who aren't you_. Thanks.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 20:27
>  and effectively asked me to shut up.

I did not ask you to do this.  I jsut said i don't think the dialog there is going anywhere as all the points seem to have been made, and are now being circled back on. 

> The only important thing I can add now is that if you find yourself in a situation where you need to override entire behavior of the class (not the interface) you are probably inheriting wrong type. 

I genuinely do this all the time.  I make a new type and the first thing i want to do is override Equals/GetHashCode/ToString.

**Comment by CyrusNajmabadi** [comment] 2021-04-27 20:28
> But now I see that it's called argument for people who aren't you. Thanks.

I've made my points.  You've made yours.  I don't think belaboring any of them helps here as it would not change any of the three items specified above.   My goal was to keep things focused and outcome driven.  If you want to discuss this further, i would ask that we take it to some place like gitter.im/dotnet/roslyn or discord.gg/csharp that are better suited to free form discussion and debate.

**Comment by mmarinchenko** [comment] 2021-04-28 06:38
> I genuinely do this all the time. I make a new type and the first thing i want to do is override Equals/GetHashCode/ToString.

Well, at least now it's clear why you initially took the idea of changing default behavior without enthusiasm.

**Comment by CyrusNajmabadi** [comment] 2021-04-28 06:46
I take it without enthusiasm because it involves changing a default we've had since the beginning unilaterally for all customers based on three votes.  If this were strictly better for all customers, this would be different. But it's a request to just flip toys around to save a single click for some, and add a click for others.  

I'm wary about such a change because in our experience when we do that we often find out that the amount of people inconvenienced and irked often can outweigh those that benefit. 

I think we should keep the default where it is, and take potential contributions for the items outlined here: https://github.com/dotnet/roslyn/issues/47806#issuecomment-827704602

That way we can potentially target multiple user/scenarios, without unilaterally regressing things for some as the initial request would have us do. I think that's a far better way to move forward here imo, and I'd be happy to help out with any prs that come along in this area. Thanks!

**Comment by Hefaistos68** [comment] 2021-04-28 08:12
> I genuinely do this all the time. I make a new type and the first thing i want to do is override Equals/GetHashCode/ToString.

So maybe there should be some rethinking how those are handled in general. But independent of this, I do understand your resistance on changing defaults that have been around for so l long. 

On the other side, i think we can agree that this part of the UI is really no longer in  sync with current VS  features. Its outdated and not appropriate anymore, thus a modernized interface should substitute it. 

This said, maybe we can close this issue now as its not going anywhere.

**Comment by mmarinchenko** [comment] 2021-04-28 08:55
> This said, maybe we can close this issue now as its not going anywhere.

Please do not close this issue. It has been reported several times on Developer Community ([here](https://developercommunity2.visualstudio.com/t/Pick-member-window-after-generate-overr/854382) and [here](https://developercommunity2.visualstudio.com/t/Add-search-for-quick-action-Generate-ov/1038488)). And I think we all agree with https://github.com/dotnet/roslyn/issues/47806#issuecomment-827704602 (is there a way to somehow pin that comment?).

**Comment by CyrusNajmabadi** [comment] 2021-04-28 14:16
> This said, maybe we can close this issue now as its not going anywhere.

I described several times the prs we would accept here. It includes having a search filter for this ui.  Would you like to contribute that @Hefaistos68 ?

**Comment by CyrusNajmabadi** [comment] 2021-04-28 14:18
> Please do not close this issue.

I will not be closing it :-)

**Comment by Hefaistos68** [comment] 2021-04-28 14:41
> I described several times the prs we would accept here. It includes having a search filter for this ui. Would you like to contribute that @Hefaistos68 ?

As much as I would like to, no time really. sorry.

**Comment by CyrusNajmabadi** [comment] 2021-04-28 17:55
> On the other side, i think we can agree that this part of the UI is really no longer in sync with current VS features. Its outdated and not appropriate anymore, thus a modernized interface should substitute it.

It's unclear what you mean by this.  What part of this is no longer in sync with current vs features?  what sort of 'modernized interface' would you replace this with?

**Closed** 2021-04-29 03:42 UTC
Labels: Area-IDE, Feature Request, help wanted

**Comment by CyrusNajmabadi** [comment] 2021-05-21 16:36
The following two items have now been done:

1. Remember the 'select-all/deselect-all' choice.  https://github.com/dotnet/roslyn/pull/52992
2. Have a way to filter down the set to those that match a provided pattern. https://github.com/dotnet/roslyn/pull/53584

I think this scenario is now adequately handled.  So i'm going to close this out.  The  request for a treeview seems like something we can wait to see if there is more feedback on being really necessary.
