### ISSUE TITLE
No best type was found for the switch expression

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#54381] opened 2021-06-25 02:11 UTC
**Version Used**: 
C# 8.0+ Visual Studio 2019 .NET Framework 4.8

**Steps to Reproduce**:
1. Writes 'switch-case' code
2. Converts to 'Switch Expression' by Resharp 2019

**Expected Behavior**:
It should be supported.

**Actual Behavior**:
Tells the error message 'No best type was found for the switch expression' on Error List

![image](https://user-images.githubusercontent.com/23723575/123358227-b1881780-d59d-11eb-8dd5-66305e2030a3.png)

**Comment by CyrusNajmabadi** [comment] 2021-06-25 02:14
More information is needed here.  But this sounds like a resharper bug currently.  You'd have to let them know if they're converting the code to somethign invalid.

Can you provide a self contained repro with teh before/after code?

**Comment by kelicto** [comment] 2021-06-25 05:35
I don't think so.
Method Code:
```
public static object GetParameterValue(this Parameter parameter)
{
    if (parameter is null)
        throw new ArgumentNullException(nameof(parameter));

    return parameter.StorageType switch
    {
        StorageType.None => throw new InvalidDataException(nameof(parameter)),
        StorageType.Integer => parameter.AsInteger(),
        StorageType.Double => parameter.AsDouble(),
        StorageType.String => parameter.AsString(),
        StorageType.ElementId => parameter.AsElementId(),
        _ => throw new ArgumentOutOfRangeException()
    };
}
```

**Comment by Youssef1313** [comment] 2021-06-25 05:44
I'm not able to reproduce the error for some reason:

![image](https://user-images.githubusercontent.com/31348972/123375542-33ba1100-d589-11eb-91c3-7691b15108bb.png)

**Comment by CyrusNajmabadi** [comment] 2021-06-25 05:51
> I don't think so.

Can you please provide a self contained repo?  The snippet you provided doesn't compile without surrounding code.

**Comment by kelicto** [comment] 2021-06-27 07:33
I don't know why the code can work well on my person computer.

**Comment by Youssef1313** [comment] 2021-06-27 13:51
@kelicto Do you mean the same code works on one machine but not the other?

@CyrusNajmabadi Was this allowed in a recent version of the compiler but not an older one (e.g, new feature or bug fix)?

**Comment by kelicto** [comment] 2021-06-27 14:47
VS version of person pc: 16.9.1. It seems that my company pc has tried to update vs, when I submited the issue. Tomorrow I will give feedback about VS version.

**Comment by CyrusNajmabadi** [comment] 2021-06-27 17:04
@Youssef1313 I can't make any determination because we lack a self contained repo from the op. @kelicto can you provide one?  One way to do this is too make the repo, upload to GitHub and then give us the branch/commit. Thanks!

**Comment by kelicto** [comment] 2021-06-28 01:15
Check for updates:
![image](https://user-images.githubusercontent.com/23723575/123565900-e9d36400-d7f0-11eb-915d-fad6e415741d.png)

I will almost certainly cause of the issue that vs version is old  or patch should update. So, The code is ok. But, 'Check for updates' don't help me to solve the problem. Maybe I need vs installer to update.

**Comment by kelicto** [comment] 2021-06-30 06:48
Now, I don't know how to reproduce the issue.

**Comment by jaredpar** [comment] 2021-07-08 14:17
Thanks for taking the time to file this and attempt to get us a working repro. But given there is no repro at the moment closing the issue. If you can reproduce this please post the steps here and we'll re-open it.

**Closed by jaredpar** 2021-07-08 14:17 UTC
Labels: Area-Compilers, untriaged
