### ISSUE TITLE
Highlight references to symbol under caret not working for symbols used in tuple types (value tuples)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36742] opened 2019-06-25 18:45 UTC
VSF_TYPE_MARKDOWNWhen a variable (local variable or class field) is used in a value tuple, placing the cursor on the symbol in value tuple, does not highlight the other references. This only happens when the symbol is used as a single value in a member of a value tuple. When the symbol is used in an expression, the highlighting works correctly.

Code example:

var value = 1;       // #1
    var x = (value, 2);  // #2

If the cursor is on `value` in line #2, the other `value` in line #1 is not highlighted, and the shortcut keys for navigation between highlighted references (Ctrl+Shift+Up/Down arrow) will do nothing.
If the cursor is placed on the first usage (line #1) it works correctly.

Also this code sample works with no problem:

var value = 1;
    var x = (value + 1, 2);

because `value` is used in an expression.

It just happens in VS 2019.
It is all fine in VS 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/620242/highlight-references-to-symbol-under-caret-not-wor.html
VSTS ticketId: 937020_
_These are the original issue comments:_

Visual Studio Feedback System on 6/25/2019, 04:00 AM (7 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2019-06-27 16:04
Closing as  duplicate of https://github.com/dotnet/roslyn/issues/20115

**Closed by jcouv** 2019-06-27 16:04 UTC
