### ISSUE TITLE
'return value is unused' is overly aggressive

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#32721] opened 2019-01-24 00:17 UTC
I'm getting a warning by default for writing code like this:

![image](https://user-images.githubusercontent.com/4564579/51645611-fa999480-1f29-11e9-86be-cd06a93bd4fb.png)

This is because i'm not bothering to look at the return value.  This is because the return value is pretty irrelevant to me.  All it has is:

![image](https://user-images.githubusercontent.com/4564579/51645640-19982680-1f2a-11e9-9e33-b1703e358ecc.png)

However, i'm now forced to update my code to look much more ugly as:

![image](https://user-images.githubusercontent.com/4564579/51645659-2a489c80-1f2a-11e9-9014-3c7af8ec9b59.png)

Or to suppress the warning.  However, the original code was *the* idiomatic way to just call code and not have to worry about the return value. 

It seems like the feature is super aggressive here.  In our projects, we see literally thousands of these warnings, and i'm struggling to think how we could deal with them.  either:

1. we bulk-fix.  but that means if we're actually ignoring something we shouldn't be ignoring, then we're SOL.
2. we don't have this feature on.

It seems like the feature needs to be smarter.  Perhaps by having an understanding of which APIs it's very much a problem to ignore results from.

**Comment by CyrusNajmabadi** [comment] 2019-01-24 00:17
Tagging @mavasani

**Comment by CyrusNajmabadi** [comment] 2019-02-20 20:52
This really needs to be done.  The experience is so annoying.

![image](https://user-images.githubusercontent.com/4564579/53123625-58f86980-350e-11e9-95fc-1ffeeb1477da.png)

Yes.  i know i'm not using the value.  I don't care about it at all.  and needin to say `_ = ...` is just so ugly and unnecessary.

**Comment by mavasani** [comment] 2019-02-20 21:21
@CyrusNajmabadi - this diagnostic is hidden by default. Can you restore it to the original severity so you don't have any user visible impact (no squiggle, suggestions in error list or ... in the editor for the diagnostic), at which point this is just a refactoring?

**Comment by ransagy** [comment] 2019-05-04 22:36
I've been unable to make this go away as suggested. What code style rule governs this and what valye would I use to make it go away entirely?

**Comment by Dragonsangel** [comment] 2019-06-18 08:51
Would it be possible to have an additional option under Preference for "Never" as with other options like "Use expression body for ..."?

**Comment by sharwell** [comment] 2019-06-18 12:01
> Would it be possible to have an additional option under Preference for "Never" as with other options like "Use expression body for ..."?

Tools &rarr; Options does not have the ability to *completely disable* analyzers, but the corresponding .editorconfig rules do. In .editorconfig, you can set the severity to `none` to disable rules.

**Comment by ransagy** [comment] 2019-06-18 19:27
Is there a governing rule in .editorconfig for this setting?

**Comment by mavasani** [comment] 2019-06-18 19:38
Can you try:
```
# IDE0058
csharp_style_unused_value_expression_statement_preference = discard_variable:none
```

**Comment by ransagy** [comment] 2019-06-19 08:36
Exactly what i needed, Should have looked there first. Thanks!

**Comment by mavasani** [comment] 2019-06-24 10:34
I am going to close this as by design given the following:
1. Diagnostic is hidden by default, so has no visible UI impact: https://github.com/dotnet/roslyn/issues/32721#issuecomment-465759018
2. Can be easily disabled: https://github.com/dotnet/roslyn/issues/32721#issuecomment-503281258

**Closed by mavasani** 2019-06-24 10:34 UTC
Labels: Area-IDE, Concept-Continuous Improvement

**Comment by jerviscui** [comment] 2021-08-02 08:30
Hello, I have some questions.

VS 2019 version:
![image](https://user-images.githubusercontent.com/6396748/127828303-0d367d83-4021-4b91-8cfe-6d2042f4a617.png)

I have a snippet of code:

```csharp
public void Test()
{
    Func<int, int> func = i => i + 1;
    func.Invoke(1);
}
```

The VS gvie me a suggestion:
> IDE0058

But, I have used `.editorconfig` in root folder, and setting `csharp_style_unused_value_expression_statement_preference`
![image](https://user-images.githubusercontent.com/6396748/127828246-e005fe09-3cdf-4801-811c-8beedf20d90c.png)

VS setting is:
![image](https://user-images.githubusercontent.com/6396748/127828091-5c9b7dc7-72d5-46bc-81d3-5494a2dd49d0.png)

Why? `.editorconfig` doesn't override VS setting?

**Comment by jerviscui** [comment] 2021-08-02 08:35
If I change the VS setting to `silent`, then suggestion will disappear.
