### ISSUE TITLE
Changing severity of "Prefer object initializers" to "none" isn't respected

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15756] opened 2016-12-08 08:31 UTC
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Wait at least 1 "Object initialization can be simplified" to show up
5. Change severity of "Prefer object initialization" to "None"
6. Wait for Error List to no longer show that it's working "..."

Expected: The messages to disappear
Actual: The messages stick around

![image](https://cloud.githubusercontent.com/assets/1103906/21002994/f1c4ba4e-bd7c-11e6-90bf-2a83a8c28f81.png)

**Comment by davkean** [comment] 2016-12-08 08:33
Even if I restart VS it's not respected. Also doesn't work for collection initializers rule either.

**Comment by CyrusNajmabadi** [comment] 2016-12-14 23:45
This is by design.  Your preference is set to 'yes'.  So we do the analysis.  The 'none' controls how we show it in the editor.  If you don't want this at all, set your preference to 'no' to indicate you don't want this at all.

**Comment by CyrusNajmabadi** [comment] 2016-12-14 23:45
@kuhlenh @dpoeschl For visiblity on the confusion around having multiple preferences to control this sort of experience.

**Comment by davkean** [comment] 2016-12-14 23:47
What?! "Suggestion" isn't related to the Error List?

**Comment by davkean** [comment] 2016-12-14 23:48
They have the same icon - hence why I thought they were related.

**Comment by CyrusNajmabadi** [comment] 2016-12-14 23:49
Actually, not certain about that.  If so, @heejaechang @mavasani About this.

I'm not seeing the dots in the UI, so it looks like we're correctly setting the severity.  I'm not sure what controls them showing up in the error list or not.

**Comment by CyrusNajmabadi** [comment] 2016-12-14 23:51
ok. Jmarolf just showed this option should affect the error list as well.  So @heejaechang or @mavasani to address the error list issue.

**Comment by CyrusNajmabadi** [comment] 2016-12-14 23:53
> They have the same icon - hence why I thought they were related.

Yes, i agree.  This sounds like a simple bug.  Have assigned to heejae to take a look.

**Comment by heejaechang** [comment] 2016-12-15 01:07
@davkean is this RC2 drop?

**Comment by davkean** [comment] 2016-12-15 01:08
Build is in the repo

**Comment by davkean** [comment] 2016-12-15 01:12
I can still repro this on yesterday's build out of D15PreRel

**Comment by heejaechang** [comment] 2016-12-15 01:16
looks like option change doesnt cause re-analysis to happen.

**Comment by mavasani** [comment] 2016-12-15 01:17
Heejae is this same issue you fixed last week? Note we haven't inserted into d15prerel for more than a week now

**Comment by heejaechang** [comment] 2016-12-15 01:18
no, I think it is new issue. I don't see changing option causing re-analysis to happen. there must be a bug on option change causing re-analysis to happen on IDE analyzers.

**Comment by Pilchie** [comment] 2016-12-15 19:12
Pretty sure that @dpoeschl fixed triggering re-analysis on option change, but that may have been broken by switching to OOP?

**Comment by heejaechang** [comment] 2016-12-15 20:41
@Pilchie don't know. but I will take a look today. I also have this bug. https://github.com/dotnet/roslyn/issues/13914

**Comment by heejaechang** [comment] 2017-01-05 21:47
this seems same root cause of this - https://github.com/dotnet/roslyn/issues/15764

PR for fix is https://github.com/dotnet/roslyn/pull/16264

**Comment by heejaechang** [comment] 2017-01-05 21:57
yep. it is dupe.

**Closed by heejaechang** 2017-01-05 21:57 UTC
Labels: Area-IDE, Bug
