### ISSUE TITLE
Shortcut key to surround C# code block with braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48280] opened 2020-10-03 17:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1201370/shortcut-key-to-surround-c-code-block-with-braces.html)._

---
In other editors including VS Code, pressing the closing-brace "}" key when a block of code is selected surrounds that code with open/close braces. There are plug-ins and snippets and other clumsy multi-keystroke options, but this commonly-needed task should really be a fast operation. As a bonus it would be nice to get brackets "]" and parenthesis ")" support in the same way.

My interest is C# in VS2019. A search seems to suggest it may exist for other languages in VS, or perhaps just in older versions of VS. Probably all languages would benefit from this.

---
#### Mila Zhou[MSFT] on 9/27/2020, 00:31 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2020-10-06 17:14
Duplicate of #39109

**Closed by jinujoseph** 2020-10-06 17:14 UTC
