### ISSUE TITLE
VS_E_UNSUPPORTEDFORMAT exception while trying to apply fix all for StyleCop SA1005

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#37908] opened 2019-08-12 16:46 UTC
C# Tools 3.3.0-beta2-19401-05+8ed56b826700926009731ca4d3de0a4e4e652969

Trying to apply SA1005 for all of corefx, hit this at some point...

"'FixAll' encountered an error and has been disabled."
 ```
System.Runtime.InteropServices.COMException : Exception from HRESULT: 0x80041FEB
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode,IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider,String filePath,IVsHierarchy hierarchyOpt,Boolean needsSave,Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

**Comment by stephentoub** [comment] 2019-08-13 21:46
I just hit a similar exception with IDE0044.  I attached a debugger, and narrowed it down to this file causing problems:
https://github.com/dotnet/corefx/blob/2858aee575e53a2d5e117d14cb8632f52f65fb70/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlJsonReader.cs#L1
I'm able to repro just by adding that one file to a new project and in another file doing the refactor and applying all (Visual Studio also refuses to display the file). There are three characters in the file that Visual Studio really doesn't like (ASCII values 15, 21, and 20).  When I remove those:
https://github.com/dotnet/corefx/pull/40291
everything starts working again. Those characters shouldn't have been there, but VS should also be more robust to this. :smile:

**Comment by sharwell** [comment] 2019-08-13 21:58
Duplicate of #37385

**Closed by sharwell** 2019-08-13 21:58 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle
