### ISSUE TITLE
Affect on profiler API

### ISSUE THREAD

**Issue by sawilde** [dotnet/roslyn#2477] opened 2015-05-03 22:01 UTC
I have the following issue raised against OpenCover - [Lines showing as not covered](https://github.com/OpenCover/opencover/issues/285) - OpenCover is an open-source code coverage tool for .NET (similar to PartCover).

What I am seeing is that the IL begin sent to the profiler is different to that on the disk. e.g. for release assemblies (I am not sure why only release assemblies are affected)

    IL_0007: bge.s IL_0019

is being changed to

    IL_0008 clt
    IL_000A stloc.1
    IL_000B ldloc.1
    IL_000C brfalse.s IL_001E

This is functionally the same but seems to be wanting to store (intermediate) values.

During my investigations I see references to roslyn in the debug output and I was wondering if it was responsible.

Is this the sort of thing I would expect to see due to roslyn or am I looking in the wrong place?

**Comment by gafter** [comment] 2015-05-04 16:58
Can you please provide the sources for the code?

**Comment by sawilde** [comment] 2015-05-04 21:29
> Can you please provide the sources for the code?

The code that the issue was raised against is here - https://github.com/StephenCleary/Deque.git

> We have no control of your profiling tools. Why would it profile code that is different from the code that you run?

That is the problem - why is it different? Why is the IL on the disk different to that sent to the profiler (I have not seen that before with any .NET runtime that OpenCover works against? Is Roslyn responsible for changing it (hence my query) or something else?

If the above IL change is not something that Roslyn can/will do then perhaps I am looking at the wrong source - hence my query.

**Comment by mjsabby** [comment] 2015-05-04 21:51
Roslyn only generates the IL, it has no interaction with the runtime. It would be quite strange to see that the IL on disk is somehow different than the IL being run and handed to your profiler.

Can you confirm by using ILDASM? Pick a small method, and both ILDASM it and look under the debugger --> https://msdn.microsoft.com/en-us/library/system.reflection.methodbody%28v=vs.110%29.aspx

You may find this useful to compare the debugger byte[] and ascertain they are different or not http://en.wikipedia.org/wiki/List_of_CIL_instructions

**Comment by sawilde** [comment] 2015-05-04 23:41
I did and the details are here in the original ticket - https://github.com/OpenCover/opencover/issues/285

**Comment by mjsabby** [comment] 2015-05-05 18:02
@sawilde - I tried a small app locally and am unable to reproduce the difference in IL being given to the runtime.

You have correctly observed (and it is by design) that Roslyn produces different IL than you may be used to (and different between debug and release).

**Comment by sawilde** [comment] 2015-05-05 21:51
> You have correctly observed (and it is by design) that Roslyn produces different IL than you may be used to (and possibly different between debug and release). Could you try the [nito.colections.deque](https://github.com/StephenCleary/Deque) example that is the first example I have seen that has the issue.

I am probably missing something obvious at the moment but now at least I have something to concentrate on.

What I don't get is why it is rewriting an assembly - what is the purpose of doing something like this

(from ILSPY)

    IL_0022: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
    IL_0027: ret

becoming (dumped from profiler so not as elegantly printed)

    IL_0024 stfld 0A00003B
    IL_0029 ldloc.0
    IL_002A stloc.1
    IL_002B br.s IL_002D
    IL_002D ldloc.1
    IL_002E ret

other than (guess) to create some sort of hook for future manipulation of the value to be returned.

If a new assembly is being emitted before being executed where is the PDB file? I think what I also need to know is understand the workflow and where the change is happening, then I can determine how OpenCover is going to deal with it.

**Comment by gafter** [comment] 2015-05-08 18:13
Perhaps you are not running the assembly you think you are running.

**Comment by sawilde** [comment] 2015-09-12 02:40
It seems that some people got it working by using the `--lib` option from dnx (https://github.com/OpenCover/opencover/issues/327)

e.g.

    OpenCover.Console.exe 
      -target:C:\users\jbruun.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\dnx.exe 
      -targetargs:"--lib c:\projects\cpip\src\website\bin\debug\dnx451 c:\projects\cpip\test\Website.Tests test" 
      -output:coverage.xml 
      -filter:+[Website]*

**Comment by jaredpar** [comment] 2015-12-04 17:17
After reading the issue on Open Cover this issue appears to be resolved.  Closing for now.  Please push back if you think this is incorrect.

**Closed by jaredpar** 2015-12-04 17:17 UTC
Labels: Area-Compilers, Need More Info
