### ISSUE TITLE
Source Generator AnalyzerConfigOptions delete all Property text after the first newline or semicolon

### ISSUE THREAD

**Issue by flo-everett-xero** [dotnet/roslyn#59761] opened 2022-02-25 03:04 UTC
**Version Used**: 
Visual C# Compiler version 3.11.0-4.21602.3 (fc14a135)
**Steps to Reproduce**:

1. Add `CompilerVisibleProperty` to Source Generator consuming project, and define property with a semicolon or newline in it
2. Reference property from source generator with `GeneratorExecutionContext.AnalyzerConfigOptions.GlobalOptions.TryGetValue`

**Expected Behavior**:
Full text of the property should be returned
**Actual Behavior**:
only text up to the first semicolon or newline is returned. If, for example, the property starts with a newline due to formatting your MSBuild file like
```
<Project>
  <PropertyGroup>
    <MyProperty>
      This is my property test
   </MyProperty>
 </PropertyGroup>
</Project>
```
then the value returned will be an empty string

**Comment by jcouv** [comment] 2022-02-25 18:00
Tagging @chsienki for triage.

**Comment by chsienki** [comment] 2022-02-28 23:04
Closing as a dupe of https://github.com/dotnet/roslyn/issues/43970

**Closed by chsienki** 2022-02-28 23:04 UTC
Labels: Area-Compilers, New Feature - Source Generators, untriaged
