### ISSUE TITLE
Nuget Exception while running Unit Testing example for Source Generator Testing

### ISSUE THREAD

**Issue by papafe** [dotnet/roslyn#61432] opened 2022-05-20 13:17 UTC
I was trying to setup my system to test source generators following the recommended approach (`Solution A`) in the [roslyn cookbook ](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#unit-testing-of-generators). I have practically copy pasted the code, but I get the following exception when running the test:

```
NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://api.nuget.org/v3/index.json.
  ----> System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I am a little confused by this exception, as the source generator project has no reference to external packages, while the test project uses NewtonSoft.Json version 13.0.1.  I also don't have issues with Nuget otherwise. 

I have tried also the non-recommended approach (`Solution B`), and that works fine. 

I'm using:
`Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.NUnit (1.1.1)`

**Comment by sharwell** [comment] 2022-05-20 13:35
This issue is caused by your test project declaring a reference to Newtonsoft.Json, and NuGet omitting a difference one (https://github.com/NuGet/Home/issues/10505). To resolve this issue, you'll need to change the project to reference Newtonsoft.Json 9.0.0.0, or provide a binding redirect to the newer version it's using.

**Comment by sharwell** [comment] 2022-05-20 13:35
Duplicate of NuGet/Home#10505

**Closed by sharwell** 2022-05-20 13:35 UTC
Labels: Area-Compilers, untriaged
