### ISSUE TITLE
VS Search should disambiguate types with more information

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#38706] opened 2019-09-16 18:52 UTC
**Version Used**: 
Visual Studio 2019 16.3 Preview 3

**Steps to Reproduce**:

1. Open a solution that has a project with 4 different 'Logger' types.
2. Ctrl+Q and search for 'Logger'

**Expected Behavior**:
All four 'Loggers' show up and are distinguishable.

**Actual Behavior**:
There are 4 identical 'Logger' class entries.

![image](https://user-images.githubusercontent.com/5387680/64984626-19adb380-d878-11e9-98d2-6dc60b4ad34c.png)

Some ways address this:

- Add namespace to the information shown
- Add part of the directory in addition to the file name
- Migrate preview experience from 'GoTo'.

This will probably require PM input to solve.

**cc:** @mikadumont migrated from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972547

**Comment by CyrusNajmabadi** [comment] 2019-09-16 19:16
I believe this is a dupe of https://github.com/dotnet/roslyn/issues/31563

**Comment by gundermanc** [comment] 2019-09-16 19:18
Very similar, note, however that this bug is happening for non-partial classes.

**Comment by CyrusNajmabadi** [comment] 2022-11-01 18:03
Closing out.  This would be on AIOSP to do better here.

**Closed by CyrusNajmabadi** 2022-11-01 18:03 UTC
Labels: Area-IDE, Concept-Continuous Improvement
