### ISSUE TITLE
Comments are lost when changing modifiers via SyntaxEditor

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#18711] opened 2017-04-14 19:45 UTC
See https://github.com/dotnet/roslyn-analyzers/pull/1070#discussion_r111505387.

**Steps to Reproduce**:
Consider the next program:
```csharp
static void Main()
{
    const string source = @"
        class C
        {
            public /*leading*/ static /*intermediate*/ readonly /*trailing*/ string F = """";
        }";

    Document document = new AdhocWorkspace()
        .AddProject("TestProject", LanguageNames.CSharp)
        .AddMetadataReferences(new[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
        })
        .WithCompilationOptions(
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
        .AddDocument("Source.cs", source)
        .Project
        .Documents
        .First();

    SemanticModel model = document.GetSemanticModelAsync().Result;
    if (model.Compilation.GetDiagnostics().Any())
    {
        throw new Exception(string.Join(
            Environment.NewLine, model.Compilation.GetDiagnostics()));
    }

    ISymbol field = model.Compilation.GetTypeByMetadataName("C").GetMembers("F").Single();
    FieldDeclarationSyntax fieldSyntax = 
        (FieldDeclarationSyntax) field.DeclaringSyntaxReferences[0].GetSyntax().Parent.Parent;

    SyntaxNode syntaxRoot = document.GetSyntaxRootAsync().Result;
    SyntaxEditor editor = new SyntaxEditor(syntaxRoot, document.Project.Solution.Workspace);

    DeclarationModifiers newModifiers = editor.Generator.GetModifiers(fieldSyntax) - 
        DeclarationModifiers.Static - DeclarationModifiers.ReadOnly + 
        DeclarationModifiers.Const;
    editor.SetModifiers(fieldSyntax, newModifiers);

    SyntaxNode newSyntaxRoot = editor.GetChangedRoot();
    Document newDocument = document.WithSyntaxRoot(newSyntaxRoot);
    SyntaxNode formatted = Formatter.Format(newDocument.GetSyntaxRootAsync().Result, 
        newDocument.Project.Solution.Workspace);
    var newSource = formatted.ToString();

    Console.WriteLine(newSource);
}

```
**Expected Behavior**:
Program output:
```
class C
{
    public /*leading*/ /*intermediate*/ /*trailing*/ const string F = "";
}
```

**Actual Behavior**:
Program output:
```
class C
{
    public /*leading*/ const string F = "";
}
```

Order and precise location of the comments may differ, they just should be preserved.

**Comment by CyrusNajmabadi** [comment] 2017-04-19 19:07
AFAICT, this is by design.  You replaced those modifiers with other modifiers.  "Intermediate" and "Trailing" belong to "static" and "readonly" respectively.  You got rid of those modifiers, so their trivia was removed with them as well.

If you want low level control over which trivia *on tokens* is preserved, you will need to go to the specific syntax APIs for that language.  There you can decide precisely what behavior is desirable.

**Comment by CyrusNajmabadi** [comment] 2017-04-19 19:07
@Pilchie Thoughts?

**Comment by bkoelman** [comment] 2017-04-19 19:46
Tagging @mavasani for asking me to create this issue.

Op 19 apr. 2017 9:07 p.m. schreef "CyrusNajmabadi" <notifications@github.com

**Comment by mavasani** [comment] 2017-04-19 22:20
@CyrusNajmabadi I thought the syntax editor APIs allowed you to remove nodes/tokens while preserving leading/trailing trivia using [SyntaxRemoveOptions](http://source.roslyn.io/#q=SyntaxRemoveOptions). Is there no API to remove modifiers from a node without losing their trivia?

**Comment by CyrusNajmabadi** [comment] 2017-04-19 22:35
SyntaxEditor allows for removal of 'nodes' (not tokens), and provides some limited options for how leading/trailing trivia around those 'nodes' are handled. 

In this case, the RemoveNode operation is not being called.  Instead, this is just the 'SetModifiers' method which wholesale replaces the existing modifiers (trivia and all) with the replaced modifiers.

I recommend that if someone does want this to work (though it seems exceptionally corner case) that they just write the modifier replacing code themselves.  They'll have to decide what the right behavior is anyways since it's open to interpretation how all of those pieces of trivia should be handled, so it can be done at that point int time.

**Comment by CyrusNajmabadi** [comment] 2017-04-22 01:09
Closing as by design.  Inter-token trivia manipulation is currently out of scope for syntaxeditor.  If that level of trivia manipulation is necessary for your scenario, the guidance is to write the specialized code as only you have the domain knowledge to know which trivia really should be preserved or not.

**Closed by CyrusNajmabadi** 2017-04-22 01:09 UTC
Labels: Area-IDE, Bug
