### ISSUE TITLE
Flaky IDE Suites

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9412] opened 2016-03-02 18:46 UTC
The following suites failed on a PR that didn't change any product code:

- Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.RenamingEventCascadesToCSUsingEventHandlerDelegate
- Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateVariable.GenerateVariableCrossLanguageTests.TestSimpleInstanceProperty_VisualBasicToCSharp

Relevant PR: https://github.com/dotnet/roslyn/pull/9405

**Comment by DustinCampbell** [comment] 2016-03-03 17:11
@jasonmalinowski, we believe the first is a dupe of stuff you're already looking at and the second is a dupe of a bug introduced by another change that @Pilchie already reverted.

**Comment by jasonmalinowski** [comment] 2016-03-03 17:59
Dupe against #9308.

**Closed by jasonmalinowski** 2016-03-03 17:59 UTC
Labels: Area-IDE, Bug, Flaky
