### ISSUE TITLE
Created Template Item not duplicated exactly when added

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74717] opened 2024-08-12 14:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Created-Template-Item-not-duplicated-exa/10719614)._

---
[severity:It bothers me. A fix would be nice]
I created a template item for a c# class that looks like this:

```
namespace $rootnamespace$;

public class $safeitemname$
{
}
```

but when I add the class it looks like this:

```
namespace MyProject
{
    public class NewClass
    {
    }
}
```

If I am creating a template, I should not have to add that item, and then have to change it after I've added it to look the way I want.

---
#### Feedback Bot on 8/11/2024, 09:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:38
Closing out as by design.  This is controlled by an editorconfig setting, and we update the code to match the usre preference.  user needs to say they want file scoped namespaces to have this kept.

**Closed by CyrusNajmabadi** 2024-11-26 02:38 UTC
Labels: Area-IDE, untriaged
