### ISSUE TITLE
C#: Missing formatting options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29920] opened 2018-09-16 01:47 UTC
In C# there are some formattiong options not available:
- in enum-declarations either a) ignore whitespace like in variable-declarations or b) add an option to auto-align the assigned values. Current workaround to stop auto-formatting to mess up manual enum-formattings is to insert /**/-comments
- option to insert a single space after an enum-value assignment 
- option to remove the whitespace on the fixed-statement and the following opening parenthesis (like for other keywords as if,while,foreach etc)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/331622/c-missing-formatting-options.html
VSTS ticketId: 680203_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-09-16 01:51
Can you clarify what you meany by:

> option to insert a single space after an enum-value assignment

An example would be good :)

**Comment by nonsensation** [comment] 2018-09-16 03:35
I like to have my code kind of not clumped together, so I have spaces everywhere (before & after commas eg). In VS you have quite good formatting options for that, except for enums.
What I personally mean by *single space* would be this: 
    enum MyEnum {
        OptionA = 0  ,
        OptionB ,
    }

This has pretty low priority though. Hope that clarifies it abit.

**Comment by CyrusNajmabadi** [comment] 2018-09-16 03:48
@nonsensation Interesting.  Though i highly doubt C# would ever provide an option for that particular formatting style in the box.  Maybe at some point the engine will be open enough for you to plug in your rules for that particular sort of feature.

I do think alignment of consecutive initialization values is something that might be more widely applicable and might get more attention and interest.  

Would you be interested in providing a PR here to help contribute toward that feature?

**Comment by sharwell** [comment] 2019-07-06 01:46
Design review conclusion:

1. Enum member declarations should already follow the same rules for ignoring spacing in declarations that local variables follow.
1. The comma after enum member declarations should already be following the `csharp_space_before_comma` option. Finer-grained configuration for this would eventually be supported by #31691.
1. The `fixed` statement should already be following the option for inserting a space after keywords. If this is not the case, it should be corrected.
1. The formatting for spacing in angle brackets would be supported by #31691.
1. The formatting for spacing in tuples is covered by #10587.

**Comment by sharwell** [comment] 2019-07-06 01:53
Closing this as a duplicate of the various items mentioned in the previous comment. 😄

**Closed by sharwell** 2019-07-06 01:53 UTC
Labels: Area-IDE, Feature Request, Need Design Review
