### ISSUE TITLE
Analyzer not working using Nuget

### ISSUE THREAD

**Issue by jol64** [dotnet/roslyn#56076] opened 2021-09-01 19:12 UTC
I implemented an analyzer and codefixprovider, and it is working when referenced via projectreference within the analyzer solution. It is also working when installing the vsix (or running that as the template project doc suggests).
However I cannot get it to run when publishing and then consuming it via Nuget. It appears not even to be instantiated (no error message I have seen). And when I look at dependencies/Analyzers, I cannot open the analyzer and see the diagnostic codes it is supposed to look for.
Any idea what to check?
Thanks, Joachim

**Comment by sharwell** [comment] 2021-09-08 18:09
Can you include a copy of the NuGet package? It can either be attached to this issue where it will be publicly visible, or you can use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) feature in Visual Studio to submit the file private to Microsoft under the normal privacy policies.

**Comment by sharwell** [comment] 2021-09-08 18:15
Duplicate of #56024

**Comment by jmarolf** [comment] 2021-09-08 21:25
also @jol64 what version of Visual Studio are you attempting to install the nuget package into?

**Comment by jol64** [comment] 2021-09-08 21:37
I am using  Visual Studio Community 2019 Version 16.10.4 on one system, Professional 2019 on the other.
I attaching the nuget (zipped to make Github happy)
[Dataport.OSP.Quality.XmlValidation.Analyzer.1.0.0.nupkg.zip](https://github.com/dotnet/roslyn/files/7131939/Dataport.OSP.Quality.XmlValidation.Analyzer.1.0.0.nupkg.zip)

**Comment by jmarolf** [comment] 2021-09-08 22:55
everything appears to be packages correctly. Looking at the included assemblies in ILSpy it appears the analyzer assembly is empty: 
![image](https://user-images.githubusercontent.com/9797472/132596145-db065623-1684-41d9-b938-48051a6e4e21.png)

With only the code fix provider existing I would not expect things to work. Is it possible for you to share your project?

**Closed** 2021-09-18 23:01 UTC
Labels: Area-Analyzers, Need More Info

**Comment by jol64** [comment] 2021-09-19 15:44
Sorry, I didn´t get a notification on @jmarolf ´s message. 
I now checked - the analyzer DLL is not empty, but the packaging step produces the kind of empty dll. Any suggestion on how I can debug that step?

**Comment by jmarolf** [comment] 2021-09-20 03:47
@jol64 without a repro project to look at I do not know how to advise you.

**Comment by jol64** [comment] 2021-09-20 05:13
@jmarolf : cannot decide on my own. I am going to check with my managers. Is there an option to share the source privately with you/Microsoft?
Thanks, Joachim

**Comment by jmarolf** [comment] 2021-09-20 05:27
If you file an issue on https://developercommunity.visualstudio.com/ there is an option to upload attachments that only Microsoft employees can see. If you go that route please respond back here with a link to the feedback item.

**Comment by jol64** [comment] 2021-09-28 16:13
@jmarolf I finally got permission to upload the source. I created a problem report on  https://developercommunity.visualstudio.com/ as suggested and added the source there. Unfortunately I could not obtain a link to the report and paste it here.
Thanks, Joachim

**Comment by jmarolf** [comment] 2021-09-28 23:53
The issue was having different nuget package versions across all your projects. I've uploaded a zip (that only you should be able to access) with what unified packages look like.

**Comment by jol64** [comment] 2021-09-29 14:03
@jmarolf thanks. but unfortunatly "seems" can be wrong. I tried your version, but the pack project is still using the wrong version.
Regards, Joachim
