### ISSUE TITLE
Suggested names don't have proper kinds in top-level statement context

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#61727] opened 2022-06-06 19:23 UTC
See screenshot below, it contains all kind of name suggestion except locals (note the icons):

<img width="367" alt="image" src="https://user-images.githubusercontent.com/788783/172231768-734e7db6-220c-4983-b17e-58bb449d3efe.png">

Also this is the result of using convert to Program.Main refactoring, I suspect they have the same root cause.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/788783/172232307-a8d7a687-8531-4179-b308-71d012514071.png">

**Comment by CyrusNajmabadi** [comment] 2022-06-07 14:30
Yes. I would view this as a compiler issue.

**Comment by DoctorKrolic** [comment] 2022-11-17 19:49
@genlu The issue is resolved (I believe by https://github.com/dotnet/roslyn/pull/65262):
![devenv_LLrbF2HPDF](https://user-images.githubusercontent.com/70431552/202544724-5669c2dc-fded-46d2-8627-21bb7a98feb4.png)

**Comment by CyrusNajmabadi** [comment] 2024-10-25 05:28
Closing out due to lack of broader feedback on this.

**Closed by CyrusNajmabadi** 2024-10-25 05:28 UTC
Labels: Bug, Area-IDE, IDE-IntelliSense, IntelliSense-Completion
