### ISSUE TITLE
Missing CS0177 (unassigned out params) if method calls a local function

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#70391] opened 2023-10-15 15:54 UTC
**Version Used**: `4.9.0-ci` and `4.7.0-3.23469.2 (a3b9f0c2)`, same result

**Steps to Reproduce**:

```csharp
// This method has an out parameter, yet it compiles
// just fine without ever assigning it. It fails to
// compile (correctly) if you remove Bar entirely.
// Repros with result being any type.
static void Foo(out object result)
{
    static void Bar() { }

    Bar();
}
```

[Sharplab link](https://sharplab.io/#v2:EYLgtghglgdgPgegQAgCoAsoGdlgKYAu6A9gCbLoQ4QzLECuByADhAE4T4F5sA0yAT0LIoTAMbEwzKABs8WALAAoJMgBW9LEwBmsPMgDuoko2R4Abj2RUsUAOYxYdkQQB0yAJI7oMnAWLKqhJSsvoAFBJsbHhiBDICAJQi2oIMyNFgxJbIAELsZjAEUNHxrsoAAgCMAGzI5QAsyABixMRhDEzEwGoxTNFY9DIECcoA3srIk3U1dY15bGFJo8gAvsoTU/OLANzKK0A===)

**Expected Behavior**:

Code should fail to compile with this error:

> "CS0177: The out parameter 'result' must be assigned to before control leaves the current method"

**Actual Behavior**:

Code compiles just fine, but that `out` parameter is never assigned.

**Comment by SirCxyrtyx** [comment] 2023-10-16 00:02
I _think_ the problem is here:
https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_LocalFunctions.cs#L73-L78

`TopState()` :https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs#L1792-L1800

The analysis to determine whether out parameters have been assigned does not seem to occur. Excluding out params from being marked as assigned with the other params in this loop causes this test to fail:
https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/CSharp/Test/Emit2/FlowAnalysis/RegionAnalysisTests.cs#L10780
This part specifically:
https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/CSharp/Test/Emit2/FlowAnalysis/RegionAnalysisTests.cs#L10797-L10807
because `x` is no longer among the symbols marked as DefinitelyAssignedOnEntry to the local function (even though it _is_ assigned).

Not really sure how to fix this. Figured I'd share what I figured out though.

**Comment by jcouv** [comment] 2023-10-16 04:52
Thanks for reporting @Sergio0694  and thanks @SirCxyrtyx for investigating.
I'm closing this issue as duplicate of https://github.com/dotnet/roslyn/issues/69775 and will add a link back to the investigation details.

**Closed** 2023-10-16 04:52 UTC
Labels: Area-Compilers, untriaged
