### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p0 on PR #8864

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8893] opened 2016-02-18 21:42 UTC
PR: [#8864](https://github.com/dotnet/roslyn/pull/8864) *Update roslyn semantic version from 1.2 to 1.3* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/282/

**1 Test Failures:**
BasicExpressionEvaluator.Validate Locals Window

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicExpressionEvaluator.xml

**Comment by davkean** [comment] 2016-02-20 18:54
@amcasey You fixed this, no?

**Comment by davkean** [comment] 2016-02-20 19:33
Dupe of: https://github.com/dotnet/roslyn/issues/8725

**Closed by davkean** 2016-02-20 19:33 UTC
Labels: Area-Interactive, Bug

**Comment by amcasey** [comment] 2016-02-22 17:12
@davkean No, the fix turned out not to work.  I'm still investigating.
