### ISSUE TITLE
CSharp.EmitTests failed in CI without terminating properly

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#45696] opened 2020-07-06 18:57 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=715301

The only available info in test log is:

```
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: Microsoft.CodeAnalysis.CSharp.Emit.UnitTests
  Discovered:  Microsoft.CodeAnalysis.CSharp.Emit.UnitTests
  Starting:    Microsoft.CodeAnalysis.CSharp.Emit.UnitTests
    Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EndToEndTests.Constraints [STARTING]
```

**Comment by gafter** [comment] 2020-07-06 19:10
Looks like the stack depth test overflowed.

**Comment by sharwell** [comment] 2020-07-29 01:17
Duplicate of #45815

**Closed by sharwell** 2020-07-29 01:17 UTC
Labels: Area-Compilers, Test
