### ISSUE TITLE
Colon at BaseConstructorInitializer wrong -> NormalizeWhitespace()

### ISSUE THREAD

**Issue by p-bojkowski** [dotnet/roslyn#53254] opened 2021-05-07 09:33 UTC
Hi!

there is an issue in the NormalizeWhitespace() methode:

```csharp

public class CLASS_NAME : ClassTemplateBase
{
	public CLASS_NAME() : base()
	{

	}
}

```

Result:

```csharp
CompilationUnit()
.WithMembers(
    SingletonList<MemberDeclarationSyntax>(
        ClassDeclaration("CLASS_NAME")
        .WithModifiers(
            TokenList(
                Token(SyntaxKind.PublicKeyword)))
        .WithBaseList(
            BaseList(
                SingletonSeparatedList<BaseTypeSyntax>(
                    SimpleBaseType(
                        IdentifierName("ClassTemplateBase")))))
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                ConstructorDeclaration(
                    Identifier("CLASS_NAME"))
                .WithModifiers(
                    TokenList(
                        Token(SyntaxKind.PublicKeyword)))
                .WithInitializer(
                    ConstructorInitializer(
                        SyntaxKind.BaseConstructorInitializer,
                        ArgumentList()))
                .WithBody(
                    Block())))))
.NormalizeWhitespace()

```

What result with this:

```csharp

public class CLASS_NAME : ClassTemplateBase
{
	public CLASS_NAME(): base()
	{

	}
}

```

The position of the colon is wrong

```csharp

CLASS_NAME(): base()

```

it should be:

```csharp

CLASS_NAME() : base()

```
like in the class declaration.

**Comment by svick** [comment] 2021-05-07 11:11
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/35371.

**Closed** 2021-05-18 00:31 UTC
Labels: Area-Compilers, untriaged
