### ISSUE TITLE
Feature request: Allow null-propagation operator for event accessors

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1276] opened 2015-03-15 12:14 UTC
Why can't I write code like this?

``` C#
Process.GetProcessById(2)?.Exited += delegate { };
```

Error:

> CS0079   The event 'Process.Exited' can only appear on the left hand side of += or -=

This would be especially useful when writing property setters that add and remove event handlers to their values if non-null.

**Comment by DavidKarlas** [comment] 2015-03-26 06:59
Bump, Is this bug or?

**Comment by gafter** [comment] 2015-03-26 16:34
the ?. Operator never produces an lvalue, so this is by design.

**Comment by SLaks** [comment] 2015-03-26 17:01
Can I reopen this as a feature request?
This would be very useful for code like [this](https://github.com/SLaks/DroidMaster/blob/master/DroidMaster/Core/PersistentDevice.cs#L65-L66).

**Comment by DavidKarlas** [comment] 2015-03-26 17:05
Maybe add also properties setters into request like:

Object?.Prop = false;

I think it's very good feature request compared to some futuristic requests for C#7 ;)

**Comment by SLaks** [comment] 2015-03-26 18:05
Note that the delegate expression (eg, `x?.SomeEvent += ExpensiveFunction().SomeMethod`) would still be evaluated if `x` is null.

**Comment by series0ne** [comment] 2015-09-22 11:15
@SLaks you're not the only one that has raised this: 

http://stackoverflow.com/questions/32519200/c-sharp-6-0-null-propagation-operator-property-assignment/32715351#32715351

**Comment by jnm2** [comment] 2016-09-22 15:42
What would it take to not evaluate the RHS if the object is null? That would seem far more helpful at first blush.

It makes me happy that this is being considered. I've wished for this on a regular basis writing UI code.

**Comment by jnm2** [comment] 2016-09-22 19:03
Just for context, I ran into wanting this again today.

**Comment by miloush** [comment] 2016-10-12 14:07
Just for the record, I expected this to work for attaching event handlers too, though I now understand what the issue is.

```C#
object o = null;
INotifyCollectionChanged c = null;

c?.CollectionChanged += OnChanged;
(o as INotifyCollectionChanged)?.CollectionChanged += OnChanged;
((INotifyCollectionChanged)o)?.CollectionChanged += OnChanged;
```

@SLaks 
> Note that the delegate expression (eg, `x?.SomeEvent += ExpensiveFunction().SomeMethod`) would still be evaluated if `x` is null.

Not if it was rewritten to `if (x != null) x.SomeEvent += ...` or am I missing something? Do you want it to be evaluated?

**Comment by salmelo** [comment] 2016-10-20 00:26
Would just like to add a vote to this (and null conditional lvalues in general) for whatever that's worth.

I run into wanting this very frequently when writing code to bridge UI and internal objects.

**Comment by SLaks** [comment] 2016-11-15 16:40
@miloush: You're right; it should check the LHS first.

**Comment by jnm2** [comment] 2017-04-15 15:44
@SLaks Could you migrate this to https://github.com/dotnet/csharplang please?

**Comment by Misiu** [comment] 2017-06-07 12:54
Whats the status of this?

I'd like to do this:

`TabListControl?.SelectedIndexChanged += this.OnSelectedIndexChanged;`

but I must add extra check

```
if (TabListControl != null)
{
  TabListControl.SelectedIndexChanged += this.OnSelectedIndexChanged;
}
```

I've looked at _Null-coalescing assignments_, but this isn't something I could use in this specific case.

**Comment by jnm2** [comment] 2017-07-12 03:27
Issue moved to [dotnet/csharplang #737](https://github.com/dotnet/csharplang/issues/737) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CyrusNajmabadi** [comment] 2022-10-28 17:43
Closing out as this is a language request.  I believe @RikkiGibson is championing allowing exactly this for the next version of C#.

**Closed by CyrusNajmabadi** 2022-10-28 17:43 UTC
Labels: Feature Request, 0 - Backlog, Area-Language Design

**Comment by RikkiGibson** [comment] 2022-10-28 18:43
dotnet/csharplang#6045
