### ISSUE TITLE
Assembly reference is added when not needed

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#31252] opened 2018-11-19 13:33 UTC
**Version Used**: Visual C# Compiler version 2.8.2.62916 (2ad4aabc)

**Steps to Reproduce**:

1. Compile following code

```c#
using ImportantForBug = System.Net.IPAddress;

class X
{
	public static void Main ()
	{
	}
}
```

Disassembly the output

**Expected Behavior**:

No System assembly reference or make it consistent with /refonly option which does not have the unused assembly reference right now.

**Actual Behavior**:

it includes

```
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
```

**Comment by sharwell** [comment] 2018-11-19 14:34
Duplicate of #31192

**Closed by sharwell** 2018-11-19 14:34 UTC
