### ISSUE TITLE
Formatting doesn't fix curly brace for else-clause

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6628] opened 2015-11-06 22:11 UTC
![elseformatting](https://cloud.githubusercontent.com/assets/4564579/11009952/34e7bbe0-8490-11e5-99d3-8eb2a1e7d851.gif)

**Comment by CyrusNajmabadi** [comment] 2015-11-06 22:11
This affects 'format document' as well, not just format-on-typing.

**Comment by diryboy** [comment] 2015-11-08 11:14
Cannot reproduce this from VS2015 RTM.

**Comment by Pilchie** [comment] 2015-11-09 16:27
I can reproduce this on the latest bits as well.  Looks like we regressed something since RTM :frowning:

**Comment by diryboy** [comment] 2015-11-11 00:37
Say if someone or me take a look and able to create PR to fix this week, will it be too late to be included in update 1? This could be really annoying.

**Comment by Pilchie** [comment] 2015-11-11 01:08
Not at this point.  We have what we believe will be our final build of Roslyn already, barring some significant hang/crash/data loss issue in a common scenario :frowning:

**Comment by matty-hall** [comment] 2016-02-23 09:15
Will this be in Update 2?  Both it and [7768](https://github.com/dotnet/roslyn/issues/7768) are maddening regressions from VS2013 that I bump into constantly.  Please!

**Comment by Pilchie** [comment] 2016-02-23 16:48
@matty-hall That's still the plan.

**Comment by Pilchie** [comment] 2016-03-01 22:31
Fixed by #9350.

**Closed by Pilchie** 2016-03-01 22:31 UTC
Labels: Area-IDE, Bug
