### ISSUE TITLE
Investigate why Interactive Window unit tests require xunit.appDomain=Required

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7976] opened 2016-01-15 02:35 UTC
Usually we disable AppDomain isolation to avoid running into #6358, however, when I attempted to do this for Interactive Window unit tests in #7940, lots of tests failed with 

```
MESSAGE:
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
+++++++++++++++++++
STACK TRACE:
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog() at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition) at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition) at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition) at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality) at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportCore[T](String contractName) at System.ComponentModel.Composition.Hosting.ExportProvider.GetExport[T](String contractName) at System.ComponentModel.Composition.Hosting.ExportProvider.GetExport[T]() at Microsoft.VisualStudio.InteractiveWindow.UnitTests.InteractiveWindowTestHost..ctor(Action`1 stateChangedHandler) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\InteractiveWindow\EditorTest\InteractiveWindowTestHost.cs:line 29 at Microsoft.VisualStudio.InteractiveWindow.UnitTests.HistoryTests..ctor() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\InteractiveWindow\EditorTest\HistoryTests.cs:line 26
```

I've seen the interactive window tests fail 3 or 4 times with #6358 in the past week, we should fix this.

**Comment by davkean** [comment] 2016-01-27 04:10
@ManishJayaswal Can you please assign this out? We're still hitting this and it falls under the 48 hour rule.

**Comment by ManishJayaswal** [comment] 2016-01-27 05:20
@amcasey can you take a look?

**Comment by amcasey** [comment] 2016-01-27 18:25
Confirmed: that change breaks all but one InteractiveWindow test on my box.  Investigating why.

**Comment by amcasey** [comment] 2016-01-27 18:59
Observation: It works under TestDriven.NET, but not directly under xunit.
Observation: this stack frame seems suspicious if our goal is to use a single AppDomain:
```
[AppDomain (xunit.console.x86.exe, #1) -> AppDomain (xunit.runner.utility.desktop, #2)]	
```

**Comment by amcasey** [comment] 2016-01-27 19:03
https://xunit.github.io/docs/configuring-with-xml.html: "Note that only desktop runners (and desktop unit tests) can use app domains, so this value will be ignored when used with non-desktop runners or with unit tests that are not targetting the desktop CLR."

**Comment by amcasey** [comment] 2016-01-27 19:04
My mistake: the scripting stuff is portable, but the window stuff is not.

**Comment by amcasey** [comment] 2016-01-27 19:06
This might be the same issue: https://github.com/xunit/xunit/issues/592

**Comment by amcasey** [comment] 2016-01-28 03:04
Here's a reduced test that reproduces the problem outside of roslyn:
```
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System.ComponentModel.Composition.Hosting;
using Microsoft.VisualStudio.Utilities;
using Xunit;

namespace Microsoft.VisualStudio.InteractiveWindow.UnitTests
{
    public class DummyTests
    {
        [Fact]
        public void DummyTest()
        {
            var catalog = new AssemblyCatalog(typeof(Microsoft.VisualStudio.Platform.VSEditor.EventArgsHelper).Assembly);
            var exportProvider = new CompositionContainer(catalog, CompositionOptions.DisableSilentRejection | CompositionOptions.IsThreadSafe);
            var contentTypeRegistryService = exportProvider.GetExport<IContentTypeRegistryService>().Value;
        }
    }
}
```

**Comment by davkean** [comment] 2016-01-28 05:09
What's the underlying exception?

**Comment by amcasey** [comment] 2016-01-28 17:28
It's resolving assemblies differently with the flag set (and missing some).  I have the fuslog diff, if you want.

**Comment by amcasey** [comment] 2016-01-28 18:56
@bradwilson, this seems like it might be a limitation of xunit, but I can't tell if it's by design.  Any thoughts?  I have a standalone repro if you'd like to investigate for yourself.

**Comment by bradwilson** [comment] 2016-01-28 20:26
If it's a dup of the referenced issue above, then there's nothing we can do. Without an app domain, there are a lot of things not under our control (probing path, configuration file, etc.).

**Comment by amcasey** [comment] 2016-01-28 22:36
@bradwilson if I understand correctly, you're saying that xunit depends on having control over app domains to tweak assembly resolution and setting `xunit.appDomain` to `denied` interferes with that.  Is that right?

@davkean how do we want to proceed if we can't disable appdomain creation?  Add a test that sleeps for 10 seconds to work around the EventListener race?

**Comment by bradwilson** [comment] 2016-01-29 02:37
>  if I understand correctly, you're saying that xunit depends on having control over app domains to tweak assembly resolution and setting xunit.appDomain to denied interferes with that. Is that right?

We end up with an explicitly loaded assembly to get things kicked off if the app domain can't load it implicitly: https://github.com/xunit/xunit/blob/master/src/common/AssemblyHelper.cs

This generally works fine for us without separate app domains, but it is different load behavior than when separate app domains are in play (implicit vs. explicit load context). This should allow any implicit dependencies that sit alongside the test assembly to "just work" because they will end up in the same load context.

There's nothing we can do about anything related to configuration (the most critical of which tends to be binding redirects).

**Comment by bradwilson** [comment] 2016-01-29 02:41
It's also worth mentioning that the ability to turn off app domains w/ desktop unit tests is relatively new, and there is always the possibility that there are bugs hiding inside the behavior. For example, we know that trying to mix app domain and non-app domain tests into the same test run exhibits some unexpected behavior.

**Comment by amcasey** [comment] 2016-01-30 03:39
Thanks, @bradwilson, for the explanation.  We're going to try to do some more investigation on this end to try to confirm that that's what's happening and we'll get back to you if we find otherwise.

**Comment by amcasey** [comment] 2016-02-01 17:59
Updating tags now that we have a workaround.

**Comment by amcasey** [comment] 2017-06-02 20:01
@ManishJayaswal, can you please unassign me?  I appear not to have permission.

**Comment by tmat** [comment] 2017-06-02 22:43
This is no longer relevant.

**Closed by tmat** 2017-06-02 22:43 UTC
Labels: Area-Interactive, Test
