### ISSUE TITLE
Bad code generation -- needless and unavoidable allocation

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#66314] opened 2023-01-08 15:19 UTC
**Version Used**: 
VS 17.5 Preview 2.0, .Net 7

**Steps to Reproduce**:

You can find the smallest code I could get to reproduce the problem [here](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAOgBEAnCAd1gHMBuAWACgtdDSLqCAVAUwA8AXekxz4CAOQCuYbiSgBjAM5D0AJjyNm+ACxCNK7AEF+AGwgKAojH4kAntgDe2AL6MS3OQHsSCbAusS5fmwANXd+LxUoAApYIIANOGxY7ABNAEplfQAxDysibgU5WQAHfihcxntGbBrcAGYkq2wAZSgAL24HbCpuQV9emmdGFwY/EgCggCEPXhVK6tr0BoAzYw8IIIAZbmWgxx6+hQGhhlr67FX1oM4PYq6DwaO+kbOlkLCIlvbO/eORkdU2AA4iQPOQIMBjNweAIJG4jKYFHUiPNTosGgizJZrHYDAgEFlQWAAJKQHpRSZQfiQO5QMncRLJSgIfgAC0ZTVZ3CgVFZ/ES+BUAB5QoEIlAAHzYciyfjcQVpbAAXilCB2EAkxkEw0YehYAHZUWc3BAELljHYQWCIVCYfw4dxMUiiNhgBA5ABrah2h1O5XYGDcchRDILGoms0wC3YIjyMq5CC2IVRHJ5ApFKClcowC65fj5QolePwbByVmJ0ustKJKJO7G2bDcKy2RKi8IkSLYYpQXjcYytDppKXLPN15tQAr+wPB0No8PcU3muzNazUHIkSBBfCYdebqdBkNCY0LyPRynUiB3OVgYqkiA9I+1YqyABuG06tZMWObdibONbHwdlAXY9n2A7cIqQK9FkmrGGOOJRGWFZlokqb5umRbZrmaaFpmxZpGGDiEWcUDLNgUQAIQjlY8GyAUXC2FB/DBBAxgSNwURRNR6G4VmuSJGW1bYB4EhBG+JAXLBtE2GkBFzmcRHyQptRodhQRKgGB4pnmWQQGAUAWmkMCwYk3EFhmfEwAQ4GJCCl6svICgAKowFSBAAAqgcYs7Kcp4m+P6ZZcB4K6yDAVCHsRvnTLMlYxf6arLBqWq6EpvnLFJX4WD+/pRG6nrenw9rwllBB4gSRJ3uS163vSiSYPViQbIi7keAoVJYSqUXKVUaW+YsOD+VQ/p2cUDmKAQhIeCS9JRDVVUQY+/XKVQXBFQASk2aphVQAASyQaWZGF4dm1nfNgQoaXgDQAPzYHam0wNt1D7VYZ3hVC57uTInm9sYIJQASVLYCA90bVtMgvbEBAAMJQomnA2MU3AA0D2p9ctq1sOQoXUFECimXmiSTOMChcgoBAAOoOXKAmsjFBDbLsdMMzcxQCngO5eJuPnLTUThCYlyX8LzykvL56D6pJxhwVl9Y2EtJxOEAA===). 

Notice in the function `GetFullAtlasEntry` that there's an allocation at the beginning of the function (unexpected), regardless if the dictionary cache is hit or not, then a second allocation inside if the cache is missed to build the lambda object to further build the cache entry (expected).

**Expected Behavior**:

I would expect an allocation only if the dictionary cache doesn't already contain the entry.

**Actual Behavior**:

There's always an allocation of a compiler-generated type, regardless of anything else.

**Additional Notes**:

This might seem minor, but this particular function is called multiple times (2-3) for each character drawn (many) to screen on each frame (144x). Overall, this contributed to hundreds of thousands of allocations per 30 seconds, of an amount of ~15MB. This was very, *very* bad. And completely hidden, the C# code as written doesn't imply that such an allocation is even possible.

As a work around, I split the function into two, the `if` and `return` portion, and the inner block portion. This reduced the main function allocations to 0 (as expected) and the inner function allocations to 1 (again as expected). This is down from the 2 allocations in the original generated code.

**Comment by jcouv** [comment] 2023-01-11 18:09
This is a known issue (here's an earlier report: https://github.com/dotnet/roslyn/issues/20777). We don't do much analysis/optimization with closure allocations. Our current recommendation is to use a local function to control the scope of the allocation.
I'll go ahead and close as duplicate of https://github.com/dotnet/roslyn/issues/20777

**Closed by jcouv** 2023-01-11 18:09 UTC
Labels: Area-Compilers, Code Gen Quality, untriaged
