### ISSUE TITLE
OperationCanceledException during Formatting

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#28024] opened 2018-06-20 17:56 UTC
A customer found this in their activity log after editing JS/TS in a session with responsiveness issues.

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(EditorCommandArgs args, Action nextHandler, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(ReturnKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass14_1`1.&lt;Execute&gt;b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

My guess is that JS/TS formatting was too slow and either the user or a timeout attempted to cancel the operation.  Perhaps OperationCanceledException is not supposed to bubble out of a command handler?

**Comment by amcasey** [comment] 2018-06-20 17:56
I don't know what the user impact was, but I'm guessing this was a NFW and not a crash.

**Comment by heejaechang** [comment] 2018-06-24 02:52
I don't believe we own command handler anymore? @olegtk shouldn't command handler takes care of cancellation exception?

tagging @dpoeschl as well. 

@jinujoseph I don't think it is our bug.

**Comment by heejaechang** [comment] 2018-06-24 02:54
@jinujoseph it is dup of the closed bug?

**Comment by jinujoseph** [comment] 2018-06-24 06:47
dupe of https://github.com/dotnet/roslyn/issues/28032

**Closed by jinujoseph** 2018-06-24 06:47 UTC
Labels: Area-IDE, Bug, Tenet-Reliability
