### ISSUE TITLE
IAssemblySymbol.TypeNames are not fully qualified

### ISSUE THREAD

**Issue by DevMatthias** [dotnet/roslyn#24784] opened 2018-02-12 17:20 UTC
**Version Used**:
15.5.3

**Steps to Reproduce**:
This code is in the context of a DiagnosticAnalyzer
```
context.RegisterCompilationStartAction(compilationContext =>
   {
	   var assembly = compilationContext.Compilation.Assembly;
	   var typeNames = assembly.TypeNames;
	   var type = assembly.GetTypeByMetadataName(typeNames.First());
   });
```

**Expected Behavior**:
I'm trying  to get an INamedTypeSymbol from an assembly and I would expect that TypeNames is returning fully qualified names that can be used with GetTypeByMetadataName().

**Actual Behavior**:
TypeNames returns just plain type names (even doubles if the assembly contains a type twice in different namespaces) and GetTypeByMetadataName() returns always null because the name is not fully qualified.

If the behavior is by design I would be glad to hear another way to get the fully qualified name to use with GetTypeByMetadataName() later on. The example above is simplified and the type is in an referenced assembly and not in the currently analyzed code.

**Comment by CyrusNajmabadi** [comment] 2018-02-12 21:12
> TypeNames returns just plain type names

By design.  This is intended to just be the plain names of the types.

> If the behavior is by design I would be glad to hear another way to get the fully qualified name to use with GetTypeByMetadataName() later on

So, it sounds like you want to get type names, just so you can get the actual types with that name later.  If so... why the indirection.  Why not just get the type you need by walking the Compilation or IAssembly symbol directly?  

'GetTypeByMetadataName' is for use with the names you get back for a System.Type when you have *its* fully qualified name for something.  In general, we don't have the same thing for Roslyn types, because why would you need to "get back to" the type, if you already have the type to begin with?

**Comment by DevMatthias** [comment] 2018-02-13 10:09
> So, it sounds like you want to get type names, just so you can get the actual types with that name later. If so... why the indirection. Why not just get the type you need by walking the Compilation or IAssembly symbol directly?

I'm trying to get a type in an _referenced_ assembly and 'TypeNames' sounds pretty direct for me. Seems SymbolVisitor can do the job to give me the information I need.

Thx for help.

**Comment by CyrusNajmabadi** [comment] 2018-02-13 10:11
> I'm trying to get a type in an referenced assembly

I'm still confused.  So you have a referenced assembly... but in order to get one of its types (using a metadata name), you need to get one of its types first to build that metadata name.  

Something seems kinda wonky here.  Why do you need to build the type name in the first place?

**Comment by CyrusNajmabadi** [comment] 2018-02-13 10:13
> Seems SymbolVisitor can do the job to give me the information I need.

Note: i don't believe SymbolVisitor actually builds Metadata-Names.  It builds strings that overlap metadata names for *some* subset of types.  But it doesn't produce metadata names for all strings.  

In other words, given an INamedTypeSymbol from that assembly, it cannot necessarily produce the 'metadata name' string you would use with GetTypeByMetadataName.

**Comment by DevMatthias** [comment] 2018-02-13 10:20
I have to find some types that follow a naming pattern in the referenced assemblies and have to ensure that the members are unique over all matching types. So the analyzer is checking the current compilation target and ensures that it will not violate the rules. See it as some kind of hierarchy without having class inheritance.

I'm totally fine with 'INamedTypeSymbol' because I have to access the member only and plain names are fine at this point. I just needed a way to get the 'INamedTypeSymbol', filtern them and access their 'INamedTypeSymbol' for further processing.

**Comment by DevMatthias** [comment] 2018-02-13 10:34
I'm not building up strings anymore. I wrote my own 'SymbolVisitor' and did something like that to get the types I want.

`SymbolVisitor.Visit(IAssemblySymbol.GlobalNamespace)`

**Comment by CyrusNajmabadi** [comment] 2018-02-13 17:43
You might want to close this out then :)

**Comment by jcouv** [comment] 2018-02-14 07:09
Sounds like the issue is resolved. I'll go ahead and close.
Feel free to re-open if not the case.

**Closed by jcouv** 2018-02-14 07:09 UTC
Labels: Area-Compilers, Resolution-By Design
