### ISSUE TITLE
Static method resolution in a non-ambiguous context fails to compile

### ISSUE THREAD

**Issue by kensykora** [dotnet/roslyn#4302] opened 2015-08-03 15:52 UTC
When I have a class that has overloaded method signatures with default values, trying to access a method in a static context versus an object context, the compiler seems to take issue with trying to access the static method. Here's an example:

https://dotnetfiddle.net/TuBjZl

```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		Foo.Bar();
	}
}

public class Foo
{
	public void Bar() {
	}
	
	public static void Bar(string arg1 = "", int arg2 = 0) {
	}
}
```

Compiler returns error:  `Compilation error (line 7, col 3): An object reference is required for the non-static field, method, or property 'Foo.Bar()'`

It's very clear in this situation that I'm trying to access the static method, but the instance-level method is preventing that from happening. This is easily worked around by simply calling `Foo.Bar("")`, but I don't feel that this should be necessary.

**Comment by gafter** [comment] 2015-08-07 18:37
This behavior is currently mandated by the language specification.

There is a proposal to make this work for C# 7. See #250 point 1. I'll treat this as a duplicate of #250.

**Closed by gafter** 2015-08-07 18:37 UTC
Labels: Area-Compilers
