### ISSUE TITLE
Intellisense cannot be shown when the caret is between two dots

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#32547] opened 2019-01-17 00:22 UTC
In VS 2019 Preview 1.1 (and I think 1), when you backspace and retype a dot but there's another dot ahead of the caret, VS doesn't show intellisense anymore. Alt+Right also stops working while the caret is between the two dots.

Sometimes I see a very brief flash of a tiny light-colored square over the editor when intellisense fails to show, like a window opening and closing immediately.

VS2019:
![vs2019](https://user-images.githubusercontent.com/8040367/51287093-e6064b00-19c3-11e9-9817-48f0fd520e1e.gif)

VS2017:
![vs2017](https://user-images.githubusercontent.com/8040367/51286808-907d6e80-19c2-11e9-9d6c-2c1db8f6f621.gif)

I'm typing nonsense for demo purposes in the file I had open, but the same thing happens everywhere.

I've tripped over it several times a day every day I've been using the preview. I assume ranges had something to do with this, and I tried to reconcile myself to it for the past month on that basis, but I just can't deal with it. I hope this change wasn't intentional. This is a common thing for me to do when refactoring, fixing changed names after things move, etc.

**Comment by CyrusNajmabadi** [comment] 2019-01-17 01:36
This should be fixed.  It's lkely a supression for `..` is causing this.  However, that suppression should happen on the second dot, not the first.

**Comment by ivanbasov** [comment] 2019-02-01 19:32
It seems this is caused by support of ranges like 1..10. I talked to the compiler team. They confirmed that two dots in "this..ToString()" are parsed as RangeExpression. Then, CreateContextWorker in CSharpSyntaxContext called from a completion provider does set proper flags to the context while locating on dots. It seems we should correct the context while located on the first dot of the range expression.

**Comment by CyrusNajmabadi** [comment] 2019-02-01 19:39
FWIW, i am hitting this *all the time now* and it's driving me nuts :)

**Comment by ivanbasov** [comment] 2019-02-01 19:46
@CyrusNajmabadi , totally agree. Should be a high priority.

**Closed** 2019-02-06 18:57 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense
