### ISSUE TITLE
Update "Building" instructions to reflect new branch information

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#9939] opened 2016-03-21 16:57 UTC
We need to update the branch info here:
**https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging**

**Comment by DavidArno** [comment] 2016-03-21 18:04
Duplicate of #9558

**Comment by jasonmalinowski** [comment] 2016-05-17 20:31
@kuhlenh, what still needs to be done here?

**Closed** 2016-08-25 00:01 UTC
Labels: Area-Infrastructure, Documentation
