### ISSUE TITLE
Visual Studio 2019 RC file closed after executing "rename file to xxx.cs" action

### ISSUE THREAD

**Issue by valdisiljuconoks** [dotnet/roslyn#34349] opened 2019-03-22 05:42 UTC
**Version Used**: 
VS 16.0 RC3

**Steps to Reproduce**:

1. Add new class file `Class1.cs` with type `Class1` inside
2. Rename `Class1` to `Class2`
3. Open Quick Actions menu and choose "Rename file to Class2.cs"

**Expected Behavior**:
New `Class2.cs` file remains still open in IDE.

**Actual Behavior**:
File is closed and file one under is open in preview (if this feature is enabled).

**Comment by jinujoseph** [comment] 2019-03-26 18:05
@dpoeschl isn't this is fixed?

**Comment by dpoeschl** [comment] 2019-03-26 20:27
@valdisiljuconoks Thanks for the report!

This is fixed by https://github.com/dotnet/roslyn/pull/33733. The fix will be available in a future Update to Visual Studio 2019.

**Comment by dpoeschl** [comment] 2019-03-26 20:28
Also marking as a duplicate of https://github.com/dotnet/roslyn/issues/16253

**Closed by dpoeschl** 2019-03-26 20:28 UTC
Labels: Area-IDE, Bug
