### ISSUE TITLE
Html.DisplayFor use null conditional operator ?.

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/roslyn#56062] opened 2021-09-01 16:45 UTC
Hello everyone.
Please register your wish.

https://github.com/dotnet/aspnetcore/issues/35991

```

@foreach (var item in Model)
{
<td>
@Html.DisplayFor(modelItem => item.Employee?.Name) <-- is Null 
</td>

```

![image](https://user-images.githubusercontent.com/25795145/131711049-f88bb7d5-f85d-41d3-b938-60eb3d6ce26b.png)

**Comment by jinujoseph** [comment] 2021-09-07 07:44
ref https://github.com/dotnet/csharplang/issues/2545

**Comment by jaredpar** [comment] 2021-09-09 15:16
Closing as this behavior is "by design" in the compiler today. The language does not support `?.` inside of an expression tree. The referenced csharplang issue tracks the language supporting that feature.

**Closed by jaredpar** 2021-09-09 15:16 UTC
Labels: Area-Compilers, Feature Request, untriaged
