### ISSUE TITLE
IDE0007 on ambugious type return but built-in type

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#21997] opened 2017-09-08 22:18 UTC
**Version Used**: VS2017.3.3

**Steps to Reproduce**:

1. Create an EditorConfig with the following settings:
```
# Demand var for built in types, such as int num = 5
csharp_style_var_for_built_in_types     = true : warning
# Demand var when the type is obvious, such as List<int> thing = new List<int>();
csharp_style_var_when_type_is_apparent  = true : warning
# Suggest the real type when the type is not apparent, such as var thing = GetThing();
csharp_style_var_elsewhere              = false : warning
```
2. Write some code which returns a built-in type
```
static string ReturnString() => "test";

void Test()
{
    string testVal = ReturnString();
}
```

**Expected Behavior**:
No warning, as the return type of ReturnString is not apparent.

**Actual Behavior**:
IDE0007 thrown, suggesting I change the type of testVal to `var`

I dug around and found #14051 which appears to be the opposite of the issue I'm seeing. 

It appears that the setting for `var_for_built_in_types` is taking precedence over `var_elsewhere`, which I do not believe should be the case. `var_for_built_in_types` in [the documentation](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#var) talks about instances of things like `var i = 5;`, which also falls under the scope of 'when type is apparent' in our philosphy on code style. It doesn't talk about more complicated situations where the return type of a function is a built-in type, which presumably would fall soley under the scope of the `when_type_is_apparent` and `var_elsewhere` rules.

Therefore, it appears there's a gap in coverage with these rules. Situations where the type is apparent, such as `var derp = 5` should (in theory) fall under 'apparent type', but are superceded by the built in type rule. Meanwhile, situations with `var derp = ReturnsAString()` fall under non-apparent type, but are also superceded by the built_in_type rule.

If I remove the built_in_type rule alltogether but leave the other two rules as above I still see IDE0007 show up for what are otherwise ambugious type returns.

What I *want* is to use var, except in places where the type information isn't visible in front of you. We have a large amount of old code that has mysterious and interesting return types which we would like to enforce being required. There doesn't appear to be a combination of these rules that lets that happen.

(Sidebar: Why does the built_in_types rule exist? What makes those types special compared to the other two rules? Situations like `var derp = "string hello"` have a very obvious type that can be inferred looking at the code, whereas `string derp = ThisIsAnAmbiguousFunctionCall()` has no obvious type present. Yet both of these situations are treated specially because of the built_in_types rule. Would it be better to have a third `none` option for the built_in_types rule that would allow the other two rules to take precedence?)

**Comment by dpoeschl** [comment] 2017-09-26 20:27
Thanks for the bug report @CliffChapman. I agree with your arguments and your expectations seem correct to me. Tagging @kuhlenh for additional opinions on how we should proceed from here.

**Comment by Cellivar** [comment] 2017-09-26 20:55
I tagged her in person a few hours ago at Ignite, I believe her comment was "Woah thats weird!"

The `none` option for the built_in_types rule that I mentioned would preserve backwards compatibility of how people have their current setups working while still allowing that particular rule to be dropped in cases like my own.

**Comment by Cellivar** [comment] 2018-06-15 19:33
I presume there hasn't been any progress on this?

**Comment by kuhlenh** [comment] 2018-06-18 15:02
@jinujoseph I keep hearing about this bug. Is there a way we can get it moved to a milestone for us to fix?

**Comment by sharwell** [comment] 2018-06-18 15:48
Duplicate of #23714

**Closed** 2018-06-18 15:50 UTC
Labels: Area-IDE, Feature Request
