### ISSUE TITLE
Overload resolution based on generic restrictions

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#7459] opened 2015-12-13 15:45 UTC
Since we don't have explicitly nullable reference types in C# 6.0, I had to resort to this to implement fluent safe indexing into an array:

``` c#
        public static T GetC<T>(this T[] array, int index)
            where T : class
        {
            if (array ==null 
                || index >= array.Length 
                || index < 0) {
                return null;
            }
            return array[index];
        }

        public static T? GetS<T>(this T[] array, int index)
            where T : struct
        {
            if (array == null
                || index >= array.Length
                || index < 0) {
                return null;
            }
            return array[index];
        }
```

I cannot name both methods `Get`, since overload resolution only takes unconstrained parameter types into account. I could use an `Option<T>` monad, of course.

This specific case will be resolved if C# 7.0 gets explicitly nullable reference types, but I imagine there might be other cases where it might make sense to take generic parameter restrictions into account when making sure there are no overload conflicts, especially if we get more advanced generic parameter restrictions in C# 7.0 as well.

**Comment by svick** [comment] 2015-12-13 18:42
I think this is a duplicate of #250, item 2.

**Comment by orthoxerox** [comment] 2015-12-13 20:32
@svick Looks like so.

**Comment by orthoxerox** [comment] 2015-12-14 05:09
On second thought, it's not a duplicate. #250 is about a call-site error, but I am getting a declaration-site error.

**Comment by alrz** [comment] 2015-12-14 06:56
If in CLR, constraints are not part of a method signature, then this is a CLR change, right? Or you are suggesting that different method names should be generated under the hood?

**Comment by gafter** [comment] 2015-12-14 15:53
C# does not let you declare two methods with the same signature. I don't think we would be likely to relax that restriction.

**Comment by Thaina** [comment] 2016-09-23 09:28
I think difference generic constraint should be method signature

At least for keyword constraint like class and struct that we got error when put both together

**Comment by gafter** [comment] 2019-05-06 22:39
This is a [`coreclr`](https://github.com/dotnet/coreclr) restriction, which would have to be changed for the language to permit this.  If you would like to pursue it, please reopen a new issue there.

**Closed by gafter** 2019-05-06 22:39 UTC
Labels: Area-Language Design, Discussion
