### ISSUE TITLE
System.ObjectDisposedException : Cannot access a disposed object. Object name: 'HubClient'.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52003] opened 2021-03-20 00:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SystemObjectDisposedException-:-Cannot-/1261873?preview=true)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Version 16.8.1]
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'HubClient'.
   at Microsoft.ServiceHub.Client.HubClient.ThrowIfDisposed()
   at async Microsoft.ServiceHub.Client.HubClient.GetPipeAsync(<Unknown Parameters>)
   at async Microsoft.ServiceHub.Client.HubClient.RequestServiceAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.ServiceHubRemoteHostClient.RequestServiceAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

! [image.png] (https://aka.ms/dc/image?name=B08c8de2dab5f4ca997d7e48fa3fa6852637413763509026101_20201119-152228-image.png&tid=08c8de2dab5f4ca997d7e48fa3fa6852637413763509026101)

---
#### Feedback Bot on 11/19/2020, 05:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/19/2020, 10:50 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Vadims Podans on 11/28/2020, 02:50 AM: 

<p>I can confirm this issue. Happens constantly after updating to 16.8+ versions. Happens when do mass refactorings with copy/paste actions. Say, split class into subclasses, copy code block from one file, paste to another, follow tooltip to import references, boom, unrecoverable error is raised.</p>

#### Vadims Podans on 11/28/2020, 03:10 AM: 

<p>The issue is described here as well: <a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1256184/intellisense-crashes-after-pasting-code-to-new-fil.html">IntelliSense crashes after pasting code to new file - Developer Community (visualstudio.com)</a>. Exact what I'm experiencing. Funny thing, Microsoft closed that issue as duplicate, but referenced issue has nothing common with this one.</p>

#### Feedback Bot on 11/30/2020, 11:32 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Gen Lu [MSFT] on 11/30/2020, 00:03 PM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=300964">Vadims Podans</a> this exception is the symptom which might have potentially many different causes. Based on the log attached, the feedback issue you linked is caused by a “KeyNotFoundException”, while issue reported here is caused by “ArgumentOutOfRangeException”. Could you please file a feedback next time you saw this error again? It will help us determine if you are seeing a new issue. Thanks</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment] 2021-03-20 00:03
This is a duplicate of #44299 and #36672

**Closed by genlu** 2021-03-20 00:03 UTC
Labels: Area-IDE, untriaged
