### ISSUE TITLE
Suggest @-prefix identifier

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#22011] opened 2017-09-09 20:21 UTC
**Version Used**: 

Visual Studio 15.3.3

**Steps to Reproduce**:

Input a type name ending with a keyword, for example `JObject`.

**Expected Behavior**:

When suggesting part of type name as an identifier, the keyword should be recognized and added with an `@`-prefix, like `@object`.

**Actual Behavior**:

The raw keyword suggested as an identifier, like `object`.

**Comment by MaStr11** [comment] 2017-09-12 11:53
I think this was already fixed with #20922. I can't reproduce the behavior with the latest version of roslyn:
![2017-09-12 13_47_13-](https://user-images.githubusercontent.com/24472128/30324466-725645c8-97c1-11e7-88a9-a53a3177d805.png)

**Comment by alrz** [comment] 2017-09-12 12:38
Would be nice to just suggest keywords after `@` (where we can't infer any other names like method name).

**Comment by dpoeschl** [comment] 2017-09-18 18:19
Correct, appears to be fixed in 15.4 for me.

**Closed** 2017-10-16 23:10 UTC
Labels: Area-IDE, Bug, help wanted

**Comment by dpoeschl** [comment] 2017-10-16 23:12
@alrz Are there good examples where that keyword suggestion would be useful? If you think there's a scenario there, feel free to file another issue to track it. Thanks!
