### ISSUE TITLE
`Convert to raw string` refactoring is available for incompatible C# versions

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#63592] opened 2022-08-25 14:10 UTC
**Version Used**:
VS 17.4 Preview 1

**Steps to Reproduce**:
```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
```
```cs
var str = $$"You cannot cast me to a raw string!";
```

**Expected Behavior**:
`Convert to raw string` refactoring is not available

**Actual Behavior**:
![devenv_xxuCp2cfup](https://user-images.githubusercontent.com/70431552/186687479-d79a0d45-67c2-489a-bdd5-bb24ebfbdf77.gif)

**Comment by CyrusNajmabadi** [comment] 2022-09-07 16:50
Closing out as by design.  This is a refactoring.  It's fine to suggest new features.  Indeed, we think people will hear about features and want to try them out in this fashion.  Once you do, you'll get a nice message telling you that it's not compatible and allowing you to upgrade your lang version if so.

**Closed by CyrusNajmabadi** 2022-09-07 16:50 UTC
Labels: Area-IDE

**Comment by svick** [comment] 2022-09-15 10:12
@CyrusNajmabadi 

> Once you do, you'll get a nice message telling you that it's not compatible and allowing you to upgrade your lang version if so.

Wouldn't this leave you in the unsupported configuration of `<TargetFramework>net6.0</TargetFramework><LangVersion>11</LangVersion>`? Is directing people towards unsupported configurations really the right way to go?

**Comment by CyrusNajmabadi** [comment] 2022-09-15 14:00
We should direct you to a supported config. If we do not, the issues would be there, not with allowing someone to try out raw strings easily.
