### ISSUE TITLE
Error in IntroduceVariableCodeRefactoringProvider

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#29393] opened 2018-08-20 05:55 UTC
Unfortunately I don't have repro steps only the log:

```
ERROR [2018-08-16 11:26:17Z]: Roslyn error: Extension_Exception IntroduceVariableCodeRefactoringProvider : 'end' must not be less than 'start'
Parameter name: end
  at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds (System.Int32 start, System.Int32 end) [0x00028] in /_/src/Compilers/Core/Portable/Text/TextSpan.cs:191 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].GetExpressionUnderSpan (Microsoft.CodeAnalysis.SyntaxTree tree, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x000b7] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:201 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].TryInitialize (Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x00045] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:67 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].Generate (TService service, Microsoft.CodeAnalysis.SemanticDocument document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x00008] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:47 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+<IntroduceVariableAsync>d__17[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].MoveNext () [0x000a7] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs:61 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.CodeAnalysis.CodeRefactorings.IntroduceVariable.IntroduceVariableCodeRefactoringProvider+<ComputeRefactoringsAsync>d__0.MoveNext () [0x00076] in /_/src/Features/Core/Portable/CodeRefactorings/IntroduceVariable/IntroduceVariableCodeRefactoringProvider.cs:26 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<GetRefactoringFromProviderAsync>d__8.MoveNext () [0x000a0] in /_/src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs:143 
```

-----
VSTS issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665111

**Comment by jinujoseph** [comment] 2018-08-23 18:46
@JoeRobich  is this dupe of https://github.com/dotnet/roslyn/issues/28665 ?

**Comment by JoeRobich** [comment] 2019-01-22 23:17
This seems to be the same bug as https://github.com/dotnet/roslyn/issues/28665

**Closed** 2019-01-22 23:17 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
