### ISSUE TITLE
Remove BoundExpressionExtensions.GetTypeAndNullability and GetNullableAnnotation

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#33941] opened 2019-03-07 16:50 UTC
Remove `BoundExpressionExtensions.GetTypeAndNullability` and `BoundExpressionExtensions.GetNullableAnnotation`.

The methods are only used for setting the nullability of inferred locals in initial binding, but initial binding should not infer nullability.

**Comment by jcouv** [comment] 2019-03-09 00:33
Closing as duplicate of https://github.com/dotnet/roslyn/issues/33925

**Closed** 2019-03-14 22:24 UTC
Labels: 4 - In Review, Area-Compilers, New Language Feature - Nullable Reference Types
