### ISSUE TITLE
List of anonymous tuple peek defintion goes to struct

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27936] opened 2018-06-17 09:21 UTC
When declaring a List of anonymous tuple; if I initialize it with members, go to definition no longer works. It takes me to the definition of the Tuple

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/270855/list-of-anonymous-tuple-peek-defintion-goes-to-str.html
VSTS ticketId: 631815_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-06-19 16:35
![image](https://user-images.githubusercontent.com/1408396/41611219-d2ddfa92-73b4-11e8-9720-cf00301cad2f.png)

**Comment by CyrusNajmabadi** [comment] 2023-02-09 21:57
Dupe of https://github.com/dotnet/roslyn/issues/29523

**Closed by CyrusNajmabadi** 2023-02-09 21:57 UTC
Labels: Bug, help wanted, Area-IDE, Area-Compilers, Developer Community
