### ISSUE TITLE
An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created starting version 6.0.300

### ISSUE THREAD

**Issue by abatishchev** [dotnet/roslyn#61783] opened 2022-05-11 01:44 UTC
### Describe the bug

Starting version **6.0.300** build in AzDO fails with an error:

```
#[error]CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\__t\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```

### Further technical details

Build YAML definition:

```yml
- task: UseDotNet@2
  displayName: 'Install .NET 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    performMultiLevelLookup: true
```

Task output before it worked:

```
Tool to install: .NET Core sdk version 6.x.
Found version 6.0.202 in channel 6.0 for user specified version spec: 6.x
Version 6.0.202 was not found in cache.
Successfully installed .NET Core sdk version 6.0.202.
```

After it stopped:

```
Tool to install: .NET Core sdk version 6.x.
Found version 6.0.300 in channel 6.0 for user specified version spec: 6.x
Version 6.0.300 was not found in cache.
Successfully installed .NET Core sdk version 6.0.300.
```

**Comment by marcpopMSFT** [comment] 2022-06-08 21:08
@jaredpar another case of analyzers that need to be retargeted to the 4.0.0 version of the compiler or have a better error.

**Comment by RikkiGibson** [comment] 2022-07-08 18:11
We are working on improving the diagnostic experience here in dotnet/roslyn#61252

**Comment by jcouv** [comment] 2022-07-08 18:12
Closing as duplicate of https://github.com/dotnet/roslyn/issues/61252

**Closed by jcouv** 2022-07-08 18:12 UTC
Labels: untriaged
