### ISSUE TITLE
ubuntu_16_debug_prtest failed with Segmentation Fault

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#30374] opened 2018-10-08 15:57 UTC
coreapp2.0/Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll failed with Segmentation fault

build logs: https://ci.dot.net/job/dotnet_roslyn/job/dev16.0.x/job/ubuntu_16_debug_prtest/115/

```
[m/mnt/j/workspace/dotnet_roslyn/dev16.0.x/ubuntu_16_debug_prtest/build/scripts/tests.sh: line 55: 78242 Segmentation fault      (core dumped) ${runner} "${xunit_console}" "${file_name[@]}" -xml "${log_file}" -parallel none "${@:4}"
```

**Comment by jaredpar** [comment] 2018-10-08 16:06
Closing a a dupe of https://github.com/dotnet/roslyn/issues/29940

**Closed by jaredpar** 2018-10-08 16:06 UTC
