### ISSUE TITLE
Crash when extracting method

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5720] opened 2015-10-06 17:17 UTC
```
CLR: Managed code called FailFast, saying "System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.VisualStudio.Text.Utilities.FrugalList`1.get_Item(Int32 index)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapToSourceSnapshot(Int32 position)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToInsertionPoint(SnapshotPoint position, PointTrackingMode trackingMode, Predicate`1 match)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.IBufferGraphExtensions.MapUpOrDownToBuffer(IBufferGraph bufferGraph, SnapshotPoint point, ITextBuffer targetBuffer)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextViewExtensions.GetCaretPoint(ITextView textView, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetCaretPoint(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.RecomputeTagsForeground()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.<>c__DisplayClass1_0.<SafeStartNew>b__0()"
```

**Comment by amcasey** [comment] 2015-10-06 17:17
FYI @jmarolf

**Comment by amcasey** [comment] 2015-10-06 17:19
1. Check out https://github.com/amcasey/roslyn/tree/ReproGH5720
 1. Open src/Compilers/CSharp/Portable/Binder/Imports.cs
 1. In ```AddLookupSymbolsInfo``` extract the two foreach loops into their own method.

**Comment by jmarolf** [comment] 2015-10-06 17:22
Thanks @amcasey

**Comment by Pilchie** [comment] 2015-10-08 20:13
Looks like a dupe of Internal bug 142856?

**Closed by Pilchie** 2015-10-08 20:13 UTC
Labels: Area-IDE, Bug

**Comment by amcasey** [comment] 2015-10-08 20:15
Agreed, but I won't be able to verify until we move to Update 1.
