### ISSUE TITLE
Add global using as quick action.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57452] opened 2021-10-28 22:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-global-using-as-quick-action/1562113)._

---
Starting from C# 10.0 global usings was introduced. Typically, global usings are placed Usings.cs file, but quick actions only allow to add using per file. 
If there would be quick actions allows to add required namespace as global using to Usings.cs file, it would be super handy.

! [image.png] (https://aka.ms/dc/image?name=B2401d5e8da1f42078c11bde4e9a37ecd637707110109112522_20211025-002248-image.png&tid=2401d5e8da1f42078c11bde4e9a37ecd637707110109112522)

---
#### Feedback Bot on 10/25/2021, 02:28 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by jinujoseph** [comment] 2021-11-04 17:35
Duplicate of #55895

**Closed by jinujoseph** 2021-11-04 17:35 UTC
Labels: Area-IDE, Developer Community
