### ISSUE TITLE
IDE0063 "using statement can be simplified" code fix results in invalid code (build error) 

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#58113] opened 2021-12-04 13:10 UTC
**Version Used**: Visual Studio 17.0.1

**Steps to Reproduce**:

Paste the following code:

```csharp
using System;
using System.Collections.Generic;

static void Repro()
{
    {
        // Any branch Roslyn can't predict is fine
        if (new Random().Next() > 0)
        {
            goto End;
        }

        using (var _ = new List<int>().GetEnumerator())
        {
        }
    }

    End:
    return;
}
```

**Expected Behavior**:

Nothing should happen and no code fixes should be proposed, this code is fine.

**Actual Behavior**:

IntelliSense suggests that the "using statement can be simplified", and applying the code fix rewrites that `using` declaration into a `using` statement. This results in a build error though on that `goto End` statement, with error CS8648 saying "a goto cannot jump to a location after a using declaration".

**Comment by CyrusNajmabadi** [comment] 2021-12-04 16:51
This seems odd. @jcouv do you know why this would not be allowed by the compiler?

**Comment by jcouv** [comment] 2021-12-04 19:18
Agreed. The `using` declaration is equivalent to the `using` statement. [This](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAFgG5NMCA2fQ3AJQFMAHAJwHsAKASkwG9NcBuPhkGjcAenG4AgjACeuYMwgwAxgAs6rAM4AbOTFyqVAcgAuuFvQAmUVRajbcAM1j1+YgVGe52MegDudCrWrGBcAHQAcvQAHmZcuAB8uNjcIp5CHpmCAOasZqy4AKIw1qQZngC+ZJViOLgAbhDMuAD6uAC8uP5BADKOZgA8sGZJkQDi9GalAK5g9MqFzFwVojUY2SVlIFsIAOwVVUA) should not be an error.
Tagging @chsienki to confirm

**Comment by Youssef1313** [comment] 2021-12-06 05:44
@CyrusNajmabadi @jcouv See [LDM](https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/meetings/2018/LDM-2018-12-03.md#goto-and-using-declarations).

**Comment by Youssef1313** [comment] 2021-12-06 06:07
Duplicate of https://github.com/dotnet/roslyn/issues/39637

**Comment by CyrusNajmabadi** [comment] 2021-12-06 16:03
@Youssef1313 that doesn't apply here. 

> When gotoing a label in the same statement list as a using var, the goto must not have a using var syntactically between the goto and the label.

The label is not in the same statement list as the using var.  :-)

**Comment by sharwell** [comment] 2022-01-20 00:26
Duplicate of #39637

**Closed by sharwell** 2022-01-20 00:26 UTC
Labels: Bug, Area-Compilers

**Comment by Youssef1313** [comment] 2022-01-20 06:09
@sharwell This was stated as a compiler issue while #39637 is an IDE issue. Can you reopen?
