### ISSUE TITLE
Structure guide line info should not display custom attributes

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15342] opened 2016-11-18 01:15 UTC
I think it would be more useful to display the line with declaration name.

![image](https://cloud.githubusercontent.com/assets/41759/20414827/60c54d22-ace9-11e6-8e1d-b96f49705254.png)

**Comment by Pilchie** [comment] 2016-11-18 01:17
Dupe of https://github.com/dotnet/roslyn/issues/14985 (fixed already)

**Closed by Pilchie** 2016-11-18 01:17 UTC
Labels: Area-IDE
