### ISSUE TITLE
Missing expected nullable mismatch warnings around method constraints check

### ISSUE THREAD

**Issue by davidroth** [dotnet/roslyn#33169] opened 2019-02-06 09:19 UTC
**Version Used**: 
VS 2019 - Preview 2

In Preview2, if I declare a generic method with a nullable type constraint `class?` for the type `T`, no warning is shown, even if one generic parameter has the non-nullable type constraint `class` for `T`:

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/338856/52331055-70583280-29f7-11e9-8909-8e71070e29a8.png)

**Expected Behavior**:

I think a warning should be prompted with the squiggle surrounding the following block `where T : class?`:

Proposal:
`The constraint 'class?' cannot be used in the generic method 'Class1.Method<T>'. Nullability of type argument 'T' doesn't match 'class' constraint of 'Class1.Samle<T>'.`

**Comment by jaredpar** [comment] 2019-02-12 23:42
Thanks for reporting. This is a duplicate of #32953 which was just recently fixed.

**Closed by jaredpar** 2019-02-12 23:42 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
