### ISSUE TITLE
rule severity does not overwrite rule options and default analyzer severity

### ISSUE THREAD

**Issue by pownkel** [dotnet/roslyn#72413] opened 2024-03-06 02:29 UTC
**Version Used**: dotnet 8.0.201

**Steps to Reproduce**:

1. Create a new C# console project with the following settings:
```
<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
<AnalysisLevel>latest</AnalysisLevel>
<AnalysisMode>AllEnabledByDefault</AnalysisMode>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```
2. Add the following code to the main file:
```
using System;

namespace ConsoleApp1
{
    public class Program
    {
        private static void Main()
        {
            Console.WriteLine("Hello world!");
        }
    }
}
```
3. Add a .editorconfig with the following:
```
root = true
dotnet_analyzer_diagnostic.severity = warning
csharp_style_expression_bodied_methods = true:warning
dotnet_diagnostic.IDE0022.severity = suggestion
```
4. Build the project

**Diagnostic Id**: Happens for any rule (this repro shows IDE0022 as an example)

**Expected Behavior**:
the line `dotnet_diagnostic.IDE0022.severity = suggestion` overrides the previous settings and no IDE0022 errors appear (this was the behavior up until about a month ago, and then our builds started breaking with no changes on our end. I'm unsure what component updated that changed this. I suspect it may have been related to the Visual Studio update to 17.9.0, but it also happens on command-line builds.)

**Actual Behavior**:
IDE0022 errors do appear in the build. Strangely, this only happens if *both* `dotnet_analyzer_diagnostic.severity` and `csharp_style_expression_bodied_methods` are set to `warning`. Otherwise, the `suggestion` level severity for the individual rule is honored.

**Comment by sharwell** [comment] 2024-03-06 17:33
Duplicate of #72094

**Closed by sharwell** 2024-03-06 17:33 UTC
Labels: Area-Analyzers, untriaged
