### ISSUE TITLE
Cannot rename namespace "Foo.Bar" to "Baz"

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#54076] opened 2021-06-14 07:13 UTC
**Version Used**: Version 17.0.0 Preview 2.0 [31412.12.main]

**Steps to Reproduce**:

1. Open a class where the namespace contains more than one level
2. Select a level other than the first
3. Invoke rename

**Expected Behavior**:

The rename allows modifying that level and above, which would support adding/removing a level.

**Actual Behavior**:

Only the selected level can be renamed.

---

Use cases:

1. Merging levels (`Foo.Bar` -> `Baz`)
1. Promoting level (`Foo.Bar` -> `Bar`)

Neither of these are possible today.

**Comment by CyrusNajmabadi** [comment] 2021-06-14 16:41
These are challenges as the can move other symbols up/down the lookup hierarchy, and supporting downstream updates and conflict resolution in those cases can be hard :-)

If someone wants to try their have at this, I have no problem with that!

**Comment by drewnoakes** [comment] 2021-06-16 13:29
> These are challenges as the can move other symbols up/down the lookup hierarchy, and supporting downstream updates and conflict resolution in those cases can be hard :-)

I would expect these conflicts to be rare. In such cases I'd be happy for the refactoring to fail and let me know why. We'd be no worse off in those rare cases than we are today.

**Comment by CyrusNajmabadi** [comment] 2021-06-16 13:59
> I would expect these conflicts to be rare. 

Sure. But that still makes those cases very relevant for the person doing the refactoring. 

> In such cases I'd be happy for the refactoring to fail and let me know why. 

Sure. But that with itself is quite complex. But, as I said, if someone wanted to take a crack at this, we'd likely take it. It's just an inordinate amount of work which has continually made it less valuable to do over other more pressing work.

**Comment by jinujoseph** [comment] 2021-06-16 18:18
Duplicate of #3583

**Closed by jinujoseph** 2021-06-16 18:18 UTC
Labels: Area-IDE
