### ISSUE TITLE
Flaky test: 'TestAsOperator_SpecErrorCase'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46430] opened 2020-07-29 22:37 UTC
https://github.com/dotnet/roslyn/blob/7a836c8e5a069c4b7dbac865712407e825c4af9b/src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs#L5614

Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=750347&view=ms.vss-test-web.build-test-results-tab&runId=23262980&resultId=114110&paneView=debug

Xunit log: 
```
    Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxBinderTests.TestAsOperator_SpecErrorCase [FAIL]
      System.BadImageFormatException : Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x800700E1)
      Stack Trace:
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
           at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
        /_/src/Test/Utilities/Portable/Platform/CoreClr/TestExecutionLoadContext.cs(58,0): at Roslyn.Test.Utilities.CoreClr.TestExecutionLoadContext.LoadImageAsAssembly(ImmutableArray`1 mainImage)
        /_/src/Test/Utilities/Portable/Platform/CoreClr/TestExecutionLoadContext.cs(89,0): at Roslyn.Test.Utilities.CoreClr.TestExecutionLoadContext.Execute(ImmutableArray`1 mainImage, String[] mainArgs, Nullable`1 expectedOutputLength)
        /_/src/Test/Utilities/Portable/Platform/CoreClr/CoreCLRRuntimeEnvironment.cs(85,0): at Roslyn.Test.Utilities.CoreClr.CoreCLRRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput)
        /_/src/Test/Utilities/Portable/CompilationVerifier.cs(219,0): at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures)
        /_/src/Test/Utilities/Portable/CommonTestBase.cs(148,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify)
        /_/src/Test/Utilities/Portable/CommonTestBase.cs(88,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        /_/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs(785,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(CSharpTestSource source, IEnumerable`1 references, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, CSharpCompilationOptions options, CSharpParseOptions parseOptions, EmitOptions emitOptions, TargetFramework targetFramework, Verification verify)
        /_/src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs(5649,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxBinderTests.TestAsOperator_SpecErrorCase()
```

**Comment by Youssef1313** [comment] 2020-09-07 09:37
See https://github.com/dotnet/runtime/issues/11759

**Comment by sharwell** [comment] 2020-11-20 16:47
Duplicate of #49519

**Closed by sharwell** 2020-11-20 16:47 UTC
Labels: Area-Compilers, Flaky, Test
