### ISSUE TITLE
False possible dereference of a null reference - equality to an expression known to be not null

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#32493] opened 2019-01-15 17:42 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.1
VisualStudio.16.Preview/16.0.0-pre.1.1+28408.50
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
class C
{
  void M(string? s)
  {
    if (s == "")
    {
      s.ToString();
    }
  }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgoGFGBvRiipgCwUAsgAomARgAMAfgpQAlLwo8GfPgEsAZhVFQKAXgMUARCaVr1q9eqgA6ACoB7AMowEG3AHNRCgNzKfAC+yiEMQUA=

**Expected Behavior**:
No warnings. `s` should be known to be not null since it is equal to an expression which is known to be not null.

**Actual Behavior**:
`warning CS8602: Possible dereference of a null reference.`

**Comment by jcouv** [comment] 2019-01-30 21:48
Yes, we need special knowledge of the `==(object, object)` operator (and `!=`). We discussed annotating such equality operators with special attributes.
Relates to https://github.com/dotnet/roslyn/issues/26761

**Comment by jcouv** [comment] 2019-01-30 21:53
I'll go ahead and close as duplicate of https://github.com/dotnet/roslyn/issues/27928

**Closed by jcouv** 2019-01-30 21:53 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
