### ISSUE TITLE
TestRunner throws up a DialogBox "You must change signature" 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#43745] opened 2020-04-28 13:55 UTC
Occasionally run into the following issue, when using `test` command on `roslyn`.

Screen capture of dialog box.
![SignatureChange](https://user-images.githubusercontent.com/900107/80488797-d1e72280-8956-11ea-924b-7ecbe173c53d.png)
When it appears an I click `OK` , have to do this about 13 times before it closes. No test failures.

Suspect it may be occur during `Language Service` test
```
Microsoft.VisualStudio.LanguageServices.UnitTests.dll.1                     FAILED 00:21:33.2873976`
```
**Note FAILED as killed the process**
```
"C:\Users\Adam\.nuget\packages\xunit.runner.console\2.4.1-pre.build.4059\tools\net472\xunit.console.x86.exe" "D:\roslyn-AdamSpeight2008\artifacts\bin\Microsoft.VisualStudio.LanguageServices.UnitTests\Debug\net472\Microsoft.VisualStudio.LanguageServices.UnitTests.dll" -class "<PrivateImplementationDetails>+__StaticArrayInitTypeSize=24" -class "<PrivateImplementationDetails>+__StaticArrayInitTypeSize=5" -class "Microsoft.CodeAnalysis.Editor.UnitTests.CallHierarchy.CallHierarchyTests" -class "Microsoft.VisualStudio.Imaging.Interop.ImageMoniker" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.AbstractTextViewFilterTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.AnalyzerDependencyCheckerTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.BasicEditorConfigGeneratorTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.ChangeSignature.ChangeSignatureViewModelTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.ClassView.SyncClassViewTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1+SetterAction`1" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAccessorFunctionTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeDelegateTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeEnumTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeEventTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeFunctionTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeImportTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeInterfaceTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeNamespaceTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeParameterTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodePropertyTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeStructTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeVariableTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CSharpFileCodeModelTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.EventCollectorTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.ExternalCodeClassTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.ExternalCodeFunctionTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.ExternalCodeParameterTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.ExternalCodePropertyTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.RootCodeModelTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.SyntaxNodeKeyTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.MethodXML.MethodXMLTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAccessorFunctionTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeClassTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeDelegateTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeEnumTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeEventTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeFunctionTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeImportTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeInterfaceTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeNamespaceTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeParameterTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodePropertyTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeStructTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeVariableTests" -class "Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.EventCollectorTests"  -html "D:\roslyn-AdamSpeight2008\artifacts\TestResults\Debug\Microsoft.VisualStudio.LanguageServices.UnitTests.dll.1.html" -noshadow -verbose
```
stack of process `
```
ntoskrnl.exe!KeSynchronizeExecution+0x5b46
ntoskrnl.exe!KeWaitForMutexObject+0x1c2d
ntoskrnl.exe!KeWaitForMutexObject+0xab4
ntoskrnl.exe!KeWaitForMutexObject+0x255
ntoskrnl.exe!RtlClearBitsEx+0x15a7
ntoskrnl.exe!KeWaitForMutexObject+0x3828
ntoskrnl.exe!KeWaitForMutexObject+0x1cc8
ntoskrnl.exe!KeWaitForMutexObject+0xab4
ntoskrnl.exe!KeWaitForMultipleObjects+0x287
ntoskrnl.exe!ObWaitForMultipleObjects+0x2a9
win32kfull.sys!NtUserWin32kSysCallFilterStub+0x6a2
win32kfull.sys!NtUserMsgWaitForMultipleObjectsEx+0x3c1
ntoskrnl.exe!_setjmpex+0x7c08
wow64win.dll+0x186f4
wow64win.dll+0x580a
wow64.dll!Wow64SystemServiceEx+0x153
wow64cpu.dll!TurboDispatchJumpAddressEnd+0xb
wow64cpu.dll!BTCpuSimulate+0x9
wow64.dll!Wow64LdrpInitialize+0x26a
wow64.dll!Wow64LdrpInitialize+0x127
ntdll.dll!LdrInitShimEngineDynamic+0x3133
ntdll.dll!memset+0x1edf5
ntdll.dll!LdrInitializeThunk+0x63
ntdll.dll!LdrInitializeThunk+0xe

```

Trying also to capture a dump.

**Comment by dpoeschl** [comment] 2020-04-28 20:30
Thanks for filing this issue @AdamSpeight2008. I'm going to close this one as a dupe of https://github.com/dotnet/roslyn/issues/43709. I'm fixing it asap.

**Closed** 2020-04-28 20:30 UTC
Labels: Area-Infrastructure, Bug, Contributor Pain
