### ISSUE TITLE
Can we move the Workspaces layer to .NET 4.6?

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3166] opened 2015-05-29 00:06 UTC
Does anyone have a scenario where they need to use Roslyn and 4.5.2 is available but 4.6 is not?  It would be nice if we could use `Array.Empty` and update `AsyncLazy` to use a non-throwing API.

**Comment by amcasey** [comment] 2015-05-29 00:06
FYI @pharring @jasonmalinowski

**Comment by amcasey** [comment] 2015-05-29 00:07
Related to #628.

**Comment by JoshVarty** [comment] 2015-05-29 03:08
I'm using the Workspaces stuff with people who have only installed VS2013. I believe this means I can only assume they've got up to .Net 4.5.1 installed. (I'm basing this on: https://msdn.microsoft.com/en-ca/vstudio/dn250998.aspx)

I think OzCode is supporting VS2013 as well.

**Comment by pharring** [comment] 2015-05-29 03:47
@JoshVarty Thanks for the info. Note that, as of PR #1632 (March 30th), your users will need to have 4.5.2 installed. Most users should already have 4.5.2 because it was pushed out via Windows Update earlier this year.

Note that this is tagged for milestone 1.1, so we're definitely not changing it for VS 2015 RTM (stabilization branch)
We anticipate that 4.6 will be pushed out via Windows Update, shortly after VS 2015 RTM. Once, that happens, if we haven't already moved, I think we'd want to revisit this. I guess the question is whether we can move sooner than that in the "master" branch, since we've already started 1.1 work there.

**Comment by JoshVarty** [comment] 2015-05-29 04:11
@pharring Did #1632 make it into RC? (I see it was made before some RC commits, but I don't know how to track down whether or not it was actually merged in)

If you guys are confident that 4.6 will be pushed out via Windows update by the time 1.1 releases, switching now sounds reasonable to me. :)

**Comment by jasonwilliams200OK** [comment] 2015-05-29 09:00
> I don't know how to track down whether or not it was actually merged in

**`git bisect`** is the answer:

man page: https://www.kernel.org/pub/software/scm/git/docs/git-bisect.html
How to use git bisect: http://stackoverflow.com/q/4713088
In-action example: https://github.com/sass/libsass/issues/1216#issuecomment-102664393

PS: git is more than *just* a source-control. It is like a whole Operating System! :computer:

**Comment by pharring** [comment] 2015-05-29 14:45
It should be noted that the main Workspaces assembly, Microsoft.CodeAnalysis.Workspaces.dll, is portable and so targets the portable framework 4.5. There's a strong desire to move that to CoreCLR 4.6, along with the rest of the compiler layer, when that framework becomes available.

The desktop assembly, Microsoft.CodeAnalysis.Workspaces.Desktop.dll (containing MSBuildWorkspace, primarily), currently targets desktop 4.5.2 although I don't believe that made it into Dev14 RC. I'm checking (and, no, I'm not using git bisect). The simplest way to check is with ildasm and look for the TargetFrameworkAttribute on the assembly.

**Comment by pharring** [comment] 2015-05-29 15:12
Confirmed: The change to 4.5.2 did NOT make it into Dev14 RC.

**Comment by jaredpar** [comment] 2015-05-29 17:00
The POR is to move Workspaces and below to 4.6 in the future branch at some point very soon after RTM.  I don't think we can move it to 4.6 in master due to the potentially for breaking customers.

**Comment by Pilchie** [comment] 2016-09-22 16:06
Moving to compilers - all of the VS and workspaces code already targets 4.6.  I think you want to update the portable pieces to netstandard 2.0 and the non-portable to 4.6.1 in RC though?

**Comment by jaredpar** [comment] 2016-09-22 16:10
@Pilchie NetStandard is portable so I don't get your portable / non-portable break down.

**Closed** 2017-02-07 21:23 UTC
Labels: Area-Compilers, Feature Request
