### ISSUE TITLE
Visual Studio crashes when attempting to match a tuple using var and then filter on the newly declared variable

### ISSUE THREAD

**Issue by Synopt** [dotnet/roslyn#17321] opened 2017-02-23 11:46 UTC
**Version Used**: VisualStudio/15.0.0-RC.4+26206.0

**Steps to Reproduce**: 

1. Start with:

```
class Repro
{
    void M()
    {
        var t = (1, 2);

        switch (t)
        {
            case (int x, int y) when x == 1:
                break;
                
            default:
                break;
        }
    }
}
```

2. Change `(int x, int y)` to `(var x, int y)` on line 9.

**Expected Behavior**: Visual Studio not to crash

**Actual Behavior**: Visual Studio crashes

**Comment by gafter** [comment] 2017-02-24 23:22
This is caused by the Extract Method refactoring, which is attempting to extract a declaration expression into a new method. The syntax tree that it builds is incorrect; it is a syntax tree that the parser would never build. So I'm reassigning this to the IDE team.

Having said that, I'll make the compiler more resilient to this situation.

**Comment by gafter** [comment] 2017-03-04 16:58
OK, the compiler has been changed so that it will not not crash when the IDE does this. But the IDE should not be producing such bad trees. Assigning to the IDE team.

**Comment by CyrusNajmabadi** [comment] 2023-11-22 18:14
Could not find any combination of extract method selections that did anything wrong here.  closing out as we've heard nothing else on this topic.

**Closed by CyrusNajmabadi** 2023-11-22 18:14 UTC
Labels: Bug, Area-IDE, New Language Feature - Pattern Matching, New Language Feature - Tuples
