### ISSUE TITLE
Unable to open .editorconfig files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59113] opened 2022-01-27 18:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-open-editorconfig-files/1568626)._

---
[severity:It's more difficult to complete my work]
Attempting to add a new .editorconfig file to either Project or Solution results in a crash.  This is using either the Default or .Net templates

---
#### Feedback Bot on 11/1/2021, 08:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/2/2021, 01:09 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Jonathon Marolf [MSFT] on 11/2/2021, 01:19 PM: 

<p>fixed in this pull request: <a target='_blank' href="https://github.com/dotnet/roslyn/pull/57234">https://github.com/dotnet/roslyn/pull/57234</a></p>

#### Feedback Bot on 11/2/2021, 01:19 PM: 

<p>A fix for this issue has been internally implemented and is being prepared for release. We’ll update you once it becomes available for download.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:59
duplicate of https://github.com/dotnet/roslyn/issues/58611

**Closed by jmarolf** 2022-03-18 21:59 UTC
Labels: Bug, Area-IDE, Tenet-Reliability, Feature - Editor Config UI
