### ISSUE TITLE
Unable to enable experimental language features through project files

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/roslyn#7509] opened 2015-12-15 21:29 UTC
As just discussed in the Gitter channel, I want to enable an experimental language feature, and start debugging that in Visual Studio. However, as mentioned by @jasonmalinowski, that's currently not possible.

Steps I've taken (on VS 2015 Update 1):
 * checked out the `future` branch, and built that
 * started debugging the `VisualStudioSetup` project

When creating a numeric literal with an underscore, I got the following diagnostic:

> Feature 'digit separators' is only available in 'experimental' language version.

I've tried to enable this by adding the following command line argument `/feature:digitSeparators` to `devenv.exe`. However, that only triggered the command line arguments help window of Visual Studio, so that doesn't work.

**Comment by Pilchie** [comment] 2015-12-18 17:54
We need to make this happen so that the closed project system bits ship ASAP.

**Comment by jasonmalinowski** [comment] 2015-12-18 21:23
I'm guessing you want this to work (via the hacks described internally) atop Update 1 without further patched bits, and also work properly atop Update 2, and both work in master?

**Comment by Pilchie** [comment] 2015-12-18 21:53
At least the latter, and ideally the former if it's not too expensive.

**Comment by Pilchie** [comment] 2016-01-23 22:14
Dupe of #7812

**Closed by Pilchie** 2016-01-23 22:14 UTC
Labels: Area-IDE, Bug, Urgency-Soon
