### ISSUE TITLE
VS crash when selecting a Source Generators-generated member from NavBar

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#49884] opened 2020-12-09 22:48 UTC
**Version Used**: 
16.8.2

**Steps to Reproduce**:

1. Open this solution in VS: https://github.com/SergeyTeplyakov/StructRecordsGenerator/blob/main/samples/StructRecordGeneratorSample/StructRecordGeneratorSample.sln
2. Open this file https://github.com/SergeyTeplyakov/StructRecordsGenerator/blob/main/samples/StructRecordGeneratorSample/StructRecordGeneratorSample/Program.cs
3. Select == operator from the members navbar drop down

**Expected Behavior**:
Shows the generated source

**Actual Behavior**:
VS crashes

**Comment by KirillOsenkov** [comment] 2020-12-09 22:49
@jasonmalinowski is this known? I can get a stack if needed

**Comment by jasonmalinowski** [comment] 2020-12-09 23:15
It should be fixed in 16.9 Preview 2 (the public preview).

**Comment by jasonmalinowski** [comment] 2020-12-09 23:17
Expected to be a dupe of #45449; @KirillOsenkov if you see failures with the current public preview or internal dogfooding build let me know, then something is still up.

**Closed by jasonmalinowski** 2020-12-09 23:17 UTC
Labels: Area-IDE, untriaged

**Comment by jasonmalinowski** [comment] 2020-12-09 23:18
And I should say there's one other report of this happening even _after_ those fixes in #49795; I was unable to reproduce that myself so if the stack here matches that then well, maybe we have a better repro!
