### ISSUE TITLE
Option to Fold/Collapse the Catch part of the Try-Catch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48279] opened 2020-10-03 17:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1183964/option-to-foldcollapse-the-catch-part-of-the-try-c.html)._

---
I would love to be able to collapse the catch part of the Try-Catch in my code

---
#### Feedback Bot on 9/15/2020, 03:09 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2020-10-06 17:15
Duplicate of #39797

**Closed by jinujoseph** 2020-10-06 17:15 UTC
