### ISSUE TITLE
Hyperlinks in editor tooltips and error list should be clickable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53696] opened 2021-05-26 16:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hyperlinks-in-editor-tooltips-and-error-/1430583)._

---
More and more hyperlinks are being used in error messages, analyzers, deprectation warnings in the editor experiences.  These can involve short-but-longish URLs that aren't necessarily easy to copy/memorize, etc. but link to critical documentation.  These links should be inferred and made interactive to launch on click external browser.

---
#### Feedback Bot on 5/24/2021, 08:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2021-06-02 18:25
Duplicate of #27139

**Closed by jinujoseph** 2021-06-02 18:25 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
