### ISSUE TITLE
CS8019 occurs in the <auto-generated/> files in .net core projects.

### ISSUE THREAD

**Issue by meteogish** [dotnet/roslyn#32327] opened 2019-01-10 12:12 UTC
**Version Used**: 
VS 2017 15.9.4-15.9.5

**Steps to Reproduce**:
Please check this [repo ](https://github.com/meteogish/CodeAnalysisTest) I've created.

or:

1. 

Use VS 2017
Enable [full solution analysis](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code?view=vs-2017).
Create an empty ASP Net Core 2.1 project from a template.
Create NUnit-Tests .net core project from a template.

2.
Add ruleset file to solution folder with CS8019 rule turned on to Warning or an Error.

3. 
In each csproj in PropertyGroup add those lines:
`
    <CodeAnalysisRuleSet>$(SolutionDir)Test.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFrameworkMonikerAssemblyAttributesFileClean>False</TargetFrameworkMonikerAssemblyAttributesFileClean>
    <TargetFrameworkMonikerAssemblyAttributesPath>$(SolutionDir)SharedAssemblyAttributes.cs</TargetFrameworkMonikerAssemblyAttributesPath>
`

Here we are using this [workaround ](http://stackoverflow.com/a/35553079/1108891) for eliminating CS8019 analysis on AssemblyAttributes generated files.

But in the Error list you should notice CS8019 errors/warnings and some of them refer to auto-generated files placed in the /obj folder.

![image](https://user-images.githubusercontent.com/11160217/50966452-387fcd00-14d5-11e9-91fa-b6c2102c6757.png)

![image](https://user-images.githubusercontent.com/11160217/50966518-741a9700-14d5-11e9-9f6d-569092d4973e.png)

![image](https://user-images.githubusercontent.com/11160217/50966551-8563a380-14d5-11e9-8541-1a82dca785df.png)

According to [this comment](https://github.com/dotnet/roslyn/issues/24976#issuecomment-406873296)  CS8019 does not exclude those generated files. I even can not suppress the errors to GlobalSuppressions.cs file because it is CS (c# compiler level errors)

Is there a workaround for it like we have for AssemblyInfo files?
Is there a solution to suppress those errors only for those files or maybe there is something I am doing wrong here?

**Comment by sharwell** [comment] 2019-01-10 18:11
Duplicate of #22579

**Comment by sharwell** [comment] 2019-01-10 18:11
🔗 See #28773 for the proposed long-term solution, with an implementation in #29704

**Closed by sharwell** 2019-01-10 18:11 UTC
