### ISSUE TITLE
Squiggles.ErrorTagGeneratedForSimpleError failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6932] opened 2015-11-20 16:14 UTC
Similar to https://github.com/dotnet/roslyn/issues/6866. Has not yet been skipped as I'm at home:

```
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.ErrorTagGeneratedForSimpleError (from Roslyn.Services.Editor.VisualBasic.UnitTests)

Failing for the past 1 build (Since Failed#1392 )
Took 0.22 sec.
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.VB$StateMachine_3_ErrorTagGeneratedForSimpleError.MoveNext() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\EditorFeatures\VisualBasicTest\Squiggles\ErrorSquiggleProducerTests.vb:line 34 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
```

**Comment by davkean** [comment] 2015-11-20 16:15
Brett, this is similar to https://github.com/dotnet/roslyn/issues/6866, can you take a look at both?

Both of them fall under 48 hours flaky test rule.

**Comment by dpoeschl** [comment] 2015-11-20 20:43
@brettfo I looked at this with @CyrusNajmabadi, and we believe this is indeed a dupe of  #6866. Closing this one.

**Closed by dpoeschl** 2015-11-20 20:43 UTC
Labels: Area-IDE, Flaky, Test
