### ISSUE TITLE
VS suffix variable name with "Attribute" when renaming a variable

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#63499] opened 2022-08-20 18:18 UTC
**Version Used**: '4.4.0-1.22403.13 (ebbf56c2)'. Language version: preview.

**Steps to Reproduce**:

- Create a local variable
- Start renaming it
- End the name with "Attribute"

=> The IDE show another "Attribute" suffix

[Recording.webm](https://user-images.githubusercontent.com/509220/185760971-67bed1f5-c650-450f-a278-7c4d16be2e83.webm)

- Validate the renaming and the additional "Attribute" suffix is removed (as expected)

**Expected Behavior**:

Roslyn doesn't append the "Attribute" suffix

**Actual Behavior**:

The "Attribute" suffix is added

**Comment by svick** [comment] 2022-08-20 18:41
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/35253.

**Closed by svick** 2022-08-20 18:41 UTC
Labels: Area-IDE, untriaged
