### ISSUE TITLE
Reduce Roslyn.RazorCSharp file size in AppData\Local\Temp\VSLogs

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/roslyn#52048] opened 2021-03-22 14:47 UTC
**Version Used**: 
I'm using Visual Studio Version 16.10.0 Preview 1.0
**Steps to Reproduce**:

1. Use the Roslyn Razor Language Server
2. Notice huge VS*.Roslyn.RazorCSharp.*.svclog files

I currently have several of those trace files in the above-mentioned directory, two of which are large, with one file being 3.6 GB and another 2.13 GB.

Is there any way for Visual Studio to reduce the file size of those files? I'd be willing to upload a huge file somewhere if you want me to.

**Comment by CyrusNajmabadi** [comment] 2021-04-06 06:07
> Is there any way for Visual Studio to reduce the file size of those files? I'd be willing to upload a huge file somewhere if you want me to.

Yes please.  can you zip and put up on any file sharing system (google drive, etc.)?  Ping me and i'll copy and take a look.  THanks!

**Comment by dantronik-markus** [comment] 2021-04-06 09:57
@CyrusNajmabadi I uploaded the file here: https://easyupload.io/am30qo

**Comment by CyrusNajmabadi** [comment] 2021-04-06 16:38
@dantronik-markus Can you give a rough estimate about how many files you had open at this time?

**Comment by dantronik-markus** [comment] 2021-04-06 16:42
The file is from this morning and not that much changed in terms of open files since this morning. I currently have about 100 tabs open in Visual Studio.

**Comment by CyrusNajmabadi** [comment] 2021-04-06 16:43
> The file is from this morning and not that much changed in terms of open files since this morning. I currently have about 100 tabs open in Visual Studio.

I see.

Ok.  That's likely a big root of the issue here.  WIll rope in the appropriate people.

**Comment by CyrusNajmabadi** [comment] 2021-04-06 16:46
@veler This is a fallout of some of hte decisions we made earlier on how often to poll in VS for document diags.  In the current scenario, teh customer has 100+ docs open, but would only be interacting with a very small set of them.

In a situation like this, Roslyn itself doesn't do the aggressive diag work for anything but the active document (or maybe just the visible docs, i don't remember...).  It would be great if we could tweak the throttling algorithm to much more aggressively throttle for things that are not visible.  In roslyn, it's fine if you make an edit, and the errors for other open (but not visible) docs are delayed by upwards of a second and a half.  

That would likely cut out around 99.9% of the messages here, which would be beneficial on many fronts.  Thanks!

**Comment by dantronik-markus** [comment] 2021-08-16 10:10
I noticed that the files in the VSLogs directory are now much smaller with the latest preview. Did anything change on your side or is this just a coincidence?

**Comment by LarryC42** [comment] 2021-08-28 11:17
I'm running 16.11.0 and have 46gb and 21gb log files in here.  Is it safe to delete them?  Is there a way to limit the size?

**Comment by istvanek** [comment] 2021-09-13 06:34
I have also big VSLogs folder in my user Temp folder - it has filled all free disc space.
How to turn this VS logging off?
I use Visual Studio 2019 16.11.2.

Marek

**Comment by CyrusNajmabadi** [comment] 2021-09-13 22:32
Closing this out because of https://github.com/dotnet/roslyn/pull/55071.  @dibarbet @NTaylorMullen please reopen if that would not have covered this case.

**Closed by CyrusNajmabadi** 2021-09-13 22:32 UTC
Labels: Area-IDE, Concept-Continuous Improvement

**Comment by dantronik-markus** [comment] 2021-09-14 16:14
@CyrusNajmabadi Which version of Visual Studio would that PR be applied to?

**Comment by dantronik-markus** [comment] 2021-09-14 16:15
I'm assuming 17.1 preview 3, since that's the milestone in question?

**Comment by GGG-KILLER** [comment] 2021-09-25 03:52
I'm using 17.0 preview 4.1 and have been having to delete these files every day.
![image](https://user-images.githubusercontent.com/5892127/134756975-8d60315a-848f-43e0-893b-a9cf06d4be73.png)
The PR mentioned should be in P4.1 shouldn't it? They're making me run out of disk space very quickly and often.

**Comment by freegemini** [comment] 2022-05-01 17:10
**VS 17.1.6** The problem is still not solved, I suppose. The total volume of files reached 5 GB sometimes ...

![изображение](https://user-images.githubusercontent.com/50248192/166156504-150d224f-c89a-4585-8df9-7119b924c56b.png)
