### ISSUE TITLE
Record ToString shows no difference between null or an empty string

### ISSUE THREAD

**Issue by Turnerj** [dotnet/roslyn#51772] opened 2021-03-10 09:35 UTC
**Version Used**: To be honest, NFI - whatever comes with the latest version of Visual Studio (v16.9). If I knew how to find out, I'll let you know.

**Steps to Reproduce**:

1. Create a record class with a string property
2. Create one instance with the property as `null`
3. Create another instance with the property as `string.Empty`
4. Call `ToString` on both and look at the output

**Expected Behavior**:

Visually be able to determine that one is `null` vs the other being an empty string.

**Actual Behavior**:

Both display nothing which seems that both are `null`.

**Background:**

This caught me out during test where I was calling `Assert.AreEqual(recordA, recordB)`. MSTest calls `ToString` on the objects when showing they weren't equal.

Basically, I got this and had no idea what was actually wrong.

> Assert.AreEqual failed.
Expected:<VersionDetails { MajorVersion = 1, MinorVersion = 2, PatchVersion = 4, PreRelease = , BuildMetadata = , CommitHash = abcdef, CommitHeight = 0, IsTaggedRelease = True }>.
Actual:<VersionDetails { MajorVersion = 1, MinorVersion = 2, PatchVersion = 4, PreRelease = , BuildMetadata = , CommitHash = abcdef, CommitHeight = 0, IsTaggedRelease = True }>. 

It had me going around in circles checking if strings in records were compared by reference or by value. Honestly, nearly was just going to scrap using records because I thought it was broken - only by chance did I use the debugger in the tests and see through VS that one property was `null` and one was an empty string.

All I'm thinking that is necessary is just adding double quotes around strings when calling `ToString` on a record.

**Comment by CyrusNajmabadi** [comment] 2021-03-10 10:02
I'm going to close this as by design.  This is the .net behavior for strings, and appears in any sort of context where string printing occurs.  It's also consistent with how things like anonymous types and other entities print themselves.  If we wanted to change this, it would likely go through the runtime deciding on different forms of printing strings out.

**Comment by CyrusNajmabadi** [comment] 2021-03-10 10:03
Another core point: dotnet/roslyn is for the compiler implementation.  Here, the compiler is doing the right thing by implementing the spec as written.  If you wanted the spec to be changed, you'dneed to start a discussion over at dotnet/csharplang about this topic.  Thanks!

**Closed by CyrusNajmabadi** 2021-03-10 10:02 UTC
Labels: Area-Compilers, untriaged

**Comment by Turnerj** [comment] 2021-03-10 10:36
Thanks for responding on this fast!

> This is the .net behavior for strings, and appears in any sort of context where string printing occurs. It's also consistent with how things like anonymous types and other entities print themselves.

This is the first time I think I've specifically noticed something like this. I guess I'm not usually comparing the string outputs of two types. Never realised that anonymous types even had a ToString override!

> If you wanted the spec to be changed, you'dneed to start a discussion over at dotnet/csharplang about this topic.

Ouch. From what you said, I get _why_ that is the case but I can imagine it being pretty difficult to change and will take a sweet long time. It sucks because this is a rough edge case to hit with no real indication on what is going wrong unless you already knew about this seemingly quirky behaviour.

I wonder why no one thought it would have been a good idea in the spec to have it be in quotes given the possible ambiguity. Given things like ToString are helpful for debugging/logs, not being able to tell the difference between two completely different values seems like a big oversight.
