### ISSUE TITLE
Uninvestigated and non-trivial test failures ignored for the purposes of codeflow

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#28436] opened 2018-07-10 21:14 UTC
Integration
https://github.com/dotnet/roslyn/pull/28408 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x-vs-deps/job/windows_debug_vs-integration_prtest/4/ (unclear)
https://github.com/dotnet/roslyn/pull/28433 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2659/ (timeout?)
https://github.com/dotnet/roslyn/pull/28433 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.8-preview4-vs-deps/job/windows_debug_vs-integration_prtest/16/ (hang?)
https://github.com/dotnet/roslyn/pull/28495 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_release_vs-integration_prtest/6/
https://github.com/dotnet/roslyn/pull/28445 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_release_vs-integration_prtest/5/ (4 seemingly actual failures)
https://github.com/dotnet/roslyn/pull/28495 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_debug_vs-integration_prtest/6/ (4 seemingly actual failures, _different_ from the above 4)
https://github.com/dotnet/roslyn/pull/28439 - https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_vs-integration_prtest/275/ (3 more failures, different from the above 8)

Ubuntu
https://github.com/dotnet/roslyn/pull/28433 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.8-preview4-vs-deps/job/ubuntu_16_mono_debug_prtest/14/

**Comment by jasonmalinowski** [comment] 2018-07-13 00:13
@dpoeschl @jinujoseph @sharwell So who is investigating these then?

**Comment by dpoeschl** [comment] 2018-07-13 21:23
@jinujoseph @sharwell Pointing out these actual (but flaky) failures:
#28445 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_release_vs-integration_prtest/5/ (4 seemingly actual failures)
#28495 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_debug_vs-integration_prtest/6/ (4 seemingly actual failures, different from the above 4)
#28439 - https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_vs-integration_prtest/275/ (3 more failures, different from the above 8)

**Comment by sharwell** [comment] 2018-07-13 21:43
> #28445 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_release_vs-integration_prtest/5/ (4 seemingly actual failures)

* WorkspacesDesktop.RenamingOpenFiles: Fixed in #28516 by 9f4af51e29f9f6994f2bddc039db470f6d6305e3
* Other three: ProcDump stole focus and broke `SendInput`

> #28495 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_debug_vs-integration_prtest/6/ (4 seemingly actual failures, different from the above 4)

* VS crashed but we don't currently capture dumps in this case. Recovery tends to be poor due to bugs in the harness.

> #28439 - https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_vs-integration_prtest/275/ (3 more failures, different from the above 8)

* Same as previous

**Comment by dpoeschl** [comment] 2018-07-18 16:37
Adding another one:
https://github.com/dotnet/roslyn/pull/28627 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x-vs-deps/job/windows_release_vs-integration_prtest/11/

**Comment by dpoeschl** [comment] 2018-07-18 16:38
Some more:
https://github.com/dotnet/roslyn/pull/28626 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2791/

**Comment by sharwell** [comment] 2018-07-18 20:31
> #28627 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x-vs-deps/job/windows_release_vs-integration_prtest/11/

This is #26442, #26443, #26444

> #28626 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2791/

Something crashed, leaving tests in an unknown state where some failed. Considering this a duplicate of #28169.

**Comment by dpoeschl** [comment] 2018-07-19 00:10
https://github.com/dotnet/roslyn/pull/28635 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2796/
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyReorderParameters
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyRemoveParameter
```

https://github.com/dotnet/roslyn/pull/28635 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/2814/
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty
```

**Comment by dpoeschl** [comment] 2018-07-19 00:11
https://github.com/dotnet/roslyn/pull/28636 - https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_vs-integration_prtest/289/
```
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlProperty
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.AddClickHandler
```

https://github.com/dotnet/roslyn/pull/28636 - https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_release_vs-integration_prtest/287/
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.FastDoubleInvoke
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.ClassificationInPreviewPane
```

**Comment by dpoeschl** [comment] 2018-07-19 03:30
https://github.com/dotnet/roslyn/pull/28682 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x/job/windows_debug_vs-integration_prtest/10/
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.OrderFixesByCursorProximityLeft
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpEncapsulateField.EncapsulateThroughLightbulbIncludingReferences
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.ApplyEditorConfigAndFormatDocument
```

**Comment by dpoeschl** [comment] 2018-07-19 19:45
https://github.com/dotnet/roslyn/pull/28691 - https://ci.dot.net/job/dotnet_roslyn/job/dev15.8.x-vs-deps/job/windows_debug_vs-integration_prtest/39/
```
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.TestMyIntelliSense
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.RenameControl
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpRename.VerifyRenameCancellation
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpRename.VerifyCrossProjectRename
```

**Comment by sharwell** [comment] 2018-09-21 21:46
Resolving as duplicate of the various linked issues.

**Closed by sharwell** 2018-09-21 21:46 UTC
Labels: Area-IDE, Flaky, Test
