### ISSUE TITLE
CS8618 warns when assigning field via property

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#41227] opened 2020-01-27 07:17 UTC
```cs
#nullable enable
class C
{
    private string p;

    C(string p)
    {
        this.P = p;
    }

    string P { get => p; set => p = value; }
}
```

**Comment by RikkiGibson** [comment] 2020-01-27 23:52
Same root cause as #32358 I think. When the compiler analyzes an assignment to `P` in the constructor it simply does not know that there is any connection between setting `P` and setting `p`.

If you need a workaround you can just assign to `this.p` and avoid the warning. Obviously this is not sufficient if your setter does validation or something like that, but may help some people in the short term.

**Comment by jcouv** [comment] 2021-02-09 22:51
Not much we can do here (cross method analysis is out-of-scope). One possible mitigation for users is to add `Debug.Assert(field is not null);` in the body of the constructor.
I'll go ahead and close as by-design.

**Closed by jcouv** 2021-02-09 22:51 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
