### ISSUE TITLE
How to change internal options (disable access checks)?

### ISSUE THREAD

**Issue by Denis535** [dotnet/roslyn#47276] opened 2020-08-31 10:13 UTC
I'm doing something like architecture overview for third party library. And I need to make list of all (public and non-public) types from that library. Of course I could use string literals for non-public types but it's horrible (( **So, I need to disable access checks.**

Roslyn has options (`MetadataImportOptions.All`, `BinderFlags.IgnoreAccessibility`) to allow it but `BinderFlags` is internal.
So, I need to override `Csc` task and change those options before running compiler.

I have a few questions. I hope you can help me.

1) I created my task class inherited from the original `Microsoft.CodeAnalysis.BuildTasks.Csc`. And immediately I faced one stupid problem. I can't reference it)) What NuGet package does this class contain?))

2) How to change internal options?
Now I think I should use Cecil and add next code into constructor of [```Microsoft.CodeAnalysis.CSharp.CommandLine.Csc```](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/Csc.cs) and then run it. Is there an easier way?

```
Arguments.CompilationOptions = Arguments.CompilationOptions
    .WithMetadataImportOptions(MetadataImportOptions.All)
    .WithTopLevelBinderFlags(BinderFlags.IgnoreAccessibility);
```

3) How to modifier the language service options? I was seeing [ProjectSystem](https://github.com/dotnet/project-system) but didn't understand anything.

P.s. There was [PR](https://github.com/dotnet/roslyn/pull/20870) but it was rejected.

**Comment by svick** [comment] 2020-08-31 12:44
An approach that worked for me was to use the `IgnoresAccessChecksToAttribute` mentioned in the PR you linked to through [aelij/IgnoresAccessChecksToGenerator](https://github.com/aelij/IgnoresAccessChecksToGenerator).

**Comment by sharwell** [comment] 2020-08-31 15:52
Duplicate of #20870

**Comment by sharwell** [comment] 2020-08-31 15:53
@Denis535 the language team reviewed this request a couple years ago and determined that this feature will not be directly supported by the C# language. Notes were provided in a link from https://github.com/dotnet/roslyn/pull/20870#issuecomment-351493055.

**Closed by sharwell** 2020-08-31 15:52 UTC

**Comment by Denis535** [comment] 2020-08-31 20:57
@sharwell I think this is not a duplicate. [20870](https://github.com/dotnet/roslyn/pull/20870) was pull request. My issue is question how to do it (or something) without direct Roslyn support.

Can you tell how can I use `Microsoft.CodeAnalysis.BuildTasks.Csc` in my project? I honestly don't understand how to import it to my project.
