### ISSUE TITLE
Master branch fails to build

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#7797] opened 2016-01-06 11:14 UTC
Followed steps at https://github.com/dotnet/roslyn/blob/future/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md

```
D:\Bart\Source\Repos\roslyn>msbuild /v:m /m Roslyn.sln
Microsoft (R) Build Engine version 14.0.24720.0
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.DiaSymReader.PortablePdb -> D:\Bart\Source\Repos\roslyn\Binaries\De
  bug\Microsoft.DiaSymReader.PortablePdb.dll
  PdbUtilities -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Roslyn.Test.PdbUti
  lities.dll
  CSharpSyntaxGenerator -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\CSharpSyn
  taxGenerator.exe
  CompilersBoundTreeGenerator -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Bou
  ndTreeGenerator.exe
  CSharpErrorFactsGenerator -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\CShar
  pErrorFactsGenerator.exe
  VisualBasicSyntaxGenerator -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\VBSy
  ntaxGenerator.exe
  VisualBasicErrorFactsGenerator -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\
  VBErrorFactsGenerator.exe
  CodeAnalysis -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.CodeAnal
  ysis.dll
  RunTests -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\RunTests.exe
  CSharpCodeAnalysis -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.Co
  deAnalysis.CSharp.dll
  BasicCodeAnalysis -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.Cod
  eAnalysis.VisualBasic.dll
  CompilerTestResources -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Roslyn.Co
  mpilers.Test.Resources.dll
  InteractiveWindow -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.Vis
  ualStudio.InteractiveWindow.dll
  Workspaces -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.CodeAnalys
  is.Workspaces.dll
  csc -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\csc.exe
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(1819,5): warning MSB3106: Assembly strong name "C:\Users\Bart\.nuget\packages\
System.Runtime.Loader\4.0.0-beta-23401\ref\dotnet\System.Runtime.Loader.dll" is
 either a path which could not be found or it is a full assembly name which is
badly formed. If it is a full assembly name it may contain characters that need
 to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quo
te("), Apostrophe('), Backslash(\). [D:\Bart\Source\Repos\roslyn\src\Scripting\
Core\Scripting.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(1819,5): warning MSB3106: Assembly strong name "C:\Users\Bart\.nuget\packages\
System.Runtime.Loader\4.0.0-beta-23401\ref\dotnet\System.Runtime.Loader.dll" is
 either a path which could not be found or it is a full assembly name which is
badly formed. If it is a full assembly name it may contain characters that need
 to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quo
te("), Apostrophe('), Backslash(\). [D:\Bart\Source\Repos\roslyn\src\Scripting\
Core\Scripting.csproj]
  Workspaces.Desktop -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\Microsoft.Co
  deAnalysis.Workspaces.Desktop.dll
  VBCSCompiler -> D:\Bart\Source\Repos\roslyn\Binaries\Debug\VBCSCompiler.exe
Hosting\AssemblyLoader\CoreAssemblyLoaderImpl.cs(7,22): error CS0234: The type
or namespace name 'Loader' does not exist in the namespace 'System.Runtime' (ar
e you missing an assembly reference?) [D:\Bart\Source\Repos\roslyn\src\Scriptin
g\Core\Scripting.csproj]
Hosting\AssemblyLoader\CoreAssemblyLoaderImpl.cs(37,44): error CS0246: The type
 or namespace name 'AssemblyLoadContext' could not be found (are you missing a
using directive or an assembly reference?) [D:\Bart\Source\Repos\roslyn\src\Scr
ipting\Core\Scripting.csproj]
Hosting\AssemblyLoader\CoreAssemblyLoaderImpl.cs(49,41): error CS0115: 'CoreAss
emblyLoaderImpl.LoadContext.Load(AssemblyName)': no suitable method found to ov
erride [D:\Bart\Source\Repos\roslyn\src\Scripting\Core\Scripting.csproj]
Hosting\AssemblyLoader\CoreAssemblyLoaderImpl.cs(55,33): warning CS0109: The me
mber 'CoreAssemblyLoaderImpl.LoadContext.LoadFromStream(Stream, Stream)' does n
ot hide an inherited member. The new keyword is not required. [D:\Bart\Source\R
epos\roslyn\src\Scripting\Core\Scripting.csproj]
Hosting\AssemblyLoader\CoreAssemblyLoaderImpl.cs(60,33): warning CS0109: The me
mber 'CoreAssemblyLoaderImpl.LoadContext.LoadFromAssemblyPath(string)' does not
 hide an inherited member. The new keyword is not required. [D:\Bart\Source\Rep
os\roslyn\src\Scripting\Core\Scripting.csproj]
```

Tried to run package restore multiple times and cleared local package cache. Keep getting this error.

**Comment by jmarolf** [comment] 2016-01-06 14:36
@tmat Looks like System.Runtime.Loader only has versions 4.0.0-beta-23409 and 4.0.0-beta-23516 on  nuget.org, do you know why its expecting 4.0.0-beta-23401?

**Comment by davkean** [comment] 2016-01-08 17:18
@bkoelman Are you still running into this?

**Comment by davkean** [comment] 2016-01-08 17:33
Looks like this could be the cause: https://github.com/dotnet/roslyn/issues/7797.

**Comment by tmat** [comment] 2016-01-08 20:27
Fixed by  #7848.

**Closed** 2016-01-08 20:28 UTC
Labels: Area-Interactive, Contributor Pain

**Comment by bkoelman** [comment] 2016-01-11 11:52
@davkean Tried from latest sources. Command-line build succeeds now, but command-line unit tests fail:

```
  Errors Roslyn.Compilers.UnitTests.dll:
      Microsoft.CodeAnalysis.UnitTests.RealParserTests.TestSpecificDoubles [FAI
  L]
      Microsoft.CodeAnalysis.UnitTests.RealParserTests.TestSpecificFloats [FAIL
  ]
  Command: C:\Users\Bart\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit
  .console.x86.exe "Binaries\Debug\Roslyn.Compilers.UnitTests.dll" -xml "Binari
  es\Debug\xUnitResults\Roslyn.Compilers.UnitTests.dll.xml" -noshadow -verbose
  xUnit output: Binaries\Debug\xUnitResults\Roslyn.Compilers.UnitTests.dll.out.
  log
      Microsoft.CodeAnalysis.UnitTests.RealParserTests.TestSpecificDoubles [FAI
  L]
      Microsoft.CodeAnalysis.UnitTests.RealParserTests.TestSpecificFloats [FAIL
  ]
```
...
```
  Test failures encountered: 00:33:15.8593697
d:\Bart\Source\Repos\roslyn\BuildAndTest.proj(80,5): error MSB3073: The command
 "Binaries\Debug\RunTests.exe C:\Users\Bart\.nuget\packages\xunit.runner.consol
e\2.1.0\tools  -xml Binaries\Debug\ConvertToAutoPropertyVB.UnitTests.dll Binari
es\Debug\ImplementNotifyPropertyChangedCS.UnitTests.dll Binaries\Debug\Implemen
tNotifyPropertyChangedVB.UnitTests.dll Binaries\Debug\Microsoft.Build.Tasks.Cod
eAnalysis.UnitTests.dll Binaries\Debug\Microsoft.CodeAnalysis.CSharp.Scripting.
Desktop.UnitTests.dll Binaries\Debug\Microsoft.CodeAnalysis.CSharp.Scripting.Un
itTests.dll Binaries\Debug\Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.d
ll Binaries\Debug\Microsoft.CodeAnalysis.Scripting.UnitTests.dll Binaries\Debug
\Microsoft.CodeAnalysis.VisualBasic.Scripting.Desktop.UnitTests.dll Binaries\De
bug\Microsoft.CodeAnalysis.VisualBasic.Scripting.UnitTests.dll Binaries\Debug\M
icrosoft.DiaSymReader.PortablePdb.UnitTests.dll Binaries\Debug\Roslyn.Compilers
.CompilerServer.UnitTests.dll Binaries\Debug\Roslyn.Compilers.CSharp.CommandLin
e.UnitTests.dll Binaries\Debug\Roslyn.Compilers.CSharp.Emit.UnitTests.dll Binar
ies\Debug\Roslyn.Compilers.CSharp.Semantic.UnitTests.dll Binaries\Debug\Roslyn.
Compilers.CSharp.Symbol.UnitTests.dll Binaries\Debug\Roslyn.Compilers.CSharp.Sy
ntax.UnitTests.dll Binaries\Debug\Roslyn.Compilers.CSharp.WinRT.UnitTests.dll B
inaries\Debug\Roslyn.Compilers.UnitTests.dll Binaries\Debug\Roslyn.Compilers.Vi
sualBasic.CommandLine.UnitTests.dll Binaries\Debug\Roslyn.Compilers.VisualBasic
.Emit.UnitTests.dll Binaries\Debug\Roslyn.Compilers.VisualBasic.Semantic.UnitTe
sts.dll Binaries\Debug\Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll Binari
es\Debug\Roslyn.Compilers.VisualBasic.Syntax.UnitTests.dll Binaries\Debug\Rosly
n.ExpressionEvaluator.CSharp.ExpressionCompiler.UnitTests.dll Binaries\Debug\Ro
slyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll Binaries\Debug\Ros
lyn.ExpressionEvaluator.VisualBasic.ExpressionCompiler.UnitTests.dll Binaries\D
ebug\Roslyn.ExpressionEvaluator.VisualBasic.ResultProvider.UnitTests.dll Binari
es\Debug\Roslyn.InteractiveHost.UnitTests.dll Binaries\Debug\Roslyn.Interactive
Window.UnitTests.dll Binaries\Debug\Roslyn.Services.CSharp.UnitTests.dll Binari
es\Debug\Roslyn.Services.Editor.CSharp.UnitTests.dll Binaries\Debug\Roslyn.Serv
ices.Editor.CSharp.UnitTests2.dll Binaries\Debug\Roslyn.Services.Editor.UnitTes
ts.dll Binaries\Debug\Roslyn.Services.Editor.UnitTests2.dll Binaries\Debug\Rosl
yn.Services.Editor.VisualBasic.UnitTests.dll Binaries\Debug\Roslyn.Services.Uni
tTests.dll Binaries\Debug\Roslyn.Services.VisualBasic.UnitTests.dll Binaries\De
bug\Roslyn.VisualStudio.CSharp.UnitTests.dll Binaries\Debug\Roslyn.VisualStudio
.Services.UnitTests.dll" exited with code 1.
```

**Comment by davkean** [comment] 2016-01-11 18:30
@bkoelman Please file a bug with the test failure details inside Roslyn.Compilers.UnitTests.dll.xml.
