### ISSUE TITLE
VB completion disappears when I use uppercase characters

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#37229] opened 2019-07-15 18:02 UTC
**Version Used**: 16.1.6, 16.3 preview 1

**Steps to Reproduce**:

1. In a VB file, type "Tae"

**Expected Behavior**:
IntelliSense to select "TypeAccessException"

**Actual Behavior**:
IntelliSense closes
![vbCompletionBroken](https://user-images.githubusercontent.com/1673956/61237646-c1c7c480-a6ef-11e9-8d0b-f09190fceffb.gif)
Roslyn's `IAsyncCompletionItemManager.UpdateCompletionListAsync` returns null, but it shouldn't.

**Working scenario:**
If you use only lowercase and type "tae", IntelliSense will behave as expected:
![vbCompletionGood](https://user-images.githubusercontent.com/1673956/61237655-c4c2b500-a6ef-11e9-9c5a-d3c460e4a08d.gif)

**Comment by sharwell** [comment] 2019-07-16 13:45
It is not a bug that IntelliSense does not select TypeAccessException in this case. The pattern matcher only allows lowercase word boundary matches if the entire string typed by the user is lowercase. For the mixed case scenario shown above, the completion item would need a word starting with `d` (case insensitive) followed by a word starting with `ae` (case insensitive).

**Comment by paul1956** [comment] 2019-07-16 21:25
VB, as you know, is a case insensitive language. It should not matter what case I type in. when seeing this behavior I mistakenly thought Intellisense just supported C# matching, the suability was missed by me and obviously other developers..

**Comment by CyrusNajmabadi** [comment] 2019-07-16 22:13
It's unrelated to the case sensitivity of hte language.  It's a way for the pattern to provide enough *signal* (and not noise) to relate it to the actual cased-named it will be matched against.

We want to avoid lots of false positives.  And if you write some combo of cap/lower but then are ok with those matching any arbitrary original char, then this can lead to too many matches and matches that are far less intuitive.

It's also extremely perf intensive since we effectively have to check *everything* and can't build any sorts of indices to match against.

**Comment by paul1956** [comment] 2019-07-17 00:22
That doesn't change the fact that users are confused seeing no results and until this thread I had no idea what the issue was. Now that I know I can easily work with it, how are others doing to discover the behavior?

**Comment by CyrusNajmabadi** [comment] 2019-07-17 00:39
> Now that I know I can easily work with it, how are others doing to discover the behavior?

Google?

**Comment by paul1956** [comment] 2019-07-17 00:48
What Google query will tell me this, especially if I don't know to search. Seems like it would be better to add this to the What's new, of VS 2019 that includes VB Core 3.0 release along with all the other stuff VB programmers are going to need to know to get their application to work with it. The more I read Git issues the more I learn about VB :-)

**Comment by CyrusNajmabadi** [comment] 2019-07-17 00:54
> Seems like it would be better to add this to the What's new, of VS 2019

This feature has been around for many releases of VS.  It's not new.  

This was the spec'ed, intentional, behavior for how to map between search patterns and cased-names in varying domains (case insensitive, case sensitive, pascal cased, camel cased, snaked cased, etc.).  

IIRC, there have been published docs on this already.  Furthest back i can find is in 2010: https://blogs.msdn.microsoft.com/zainnab/2010/02/09/using-the-new-intellisense-pascal-case/

**Comment by CyrusNajmabadi** [comment] 2023-02-10 21:05
Closing out as this is working as intended.

**Closed by CyrusNajmabadi** 2023-02-10 21:05 UTC
Labels: Area-IDE, Feature Request, Need Design Review, IDE-IntelliSense
