### ISSUE TITLE
dotnet format erases trailing comments when migrating to file scoped namespace

### ISSUE THREAD

**Issue by dlosch** [dotnet/roslyn#57735] opened 2021-11-12 15:33 UTC
When using `dotnet format` (6.0.252703+68bc36719088c86b0ff01334039b0611741b8276) with an .editorconfig to migrate old style namespace declarations to file scoped namespaces, trailing comments are removed from files.

(I am not sure whether this the designed behavior or whether this can be manipulated by settings in the .editorconfig)

1. File with a old-style namespace declaration

```
namespace TestProjects.Lib {

    // this comment remains in the file
    //public interface ITest {
    //    int ExecutionCount { get; }
    //}


    public class Class1  {
        public int ExecutionCount => throw new NotImplementedException();
    }

    // all trailing comments are removed by dotnet format
    //public class ClassRemovedByDotnetFormat  {
    //}
}
```
2. Add `.editorconfig` with at least
`csharp_style_namespace_declarations = file_scoped:warning`

3. run `dotnet format` on project/solution

Result: this removes the trailing comments and emits this (commented declaration of `ClassRemovedByDotnetFormat` is missing)
```
namespace TestProjects.Lib;

// this comment remains in the file
//public interface ITest {
//    int ExecutionCount { get; }
//}


public class Class1
{
    public int ExecutionCount => throw new NotImplementedException();
}

```

**Comment by JoeRobich** [comment] 2021-11-12 20:40
Moved to Roslyn since dotnet-format simply applies the Roslyn codefix.

**Comment by CyrusNajmabadi** [comment] 2021-11-12 20:49
This is a dupe.  Not sure where the dupe is.

**Comment by sharwell** [comment] 2021-12-01 19:12
This isn't an exact duplicate of #57564, but it was fixed at the same time.

**Closed** 2021-12-01 19:12 UTC
Labels: Bug, help wanted, Area-IDE
