### ISSUE TITLE
Solution Explorer does not show VB derived types

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#5496] opened 2015-09-28 20:22 UTC
![image](https://cloud.githubusercontent.com/assets/9797472/10147563/7d5017ea-65e3-11e5-9e77-9792633d54b7.png)
navigate to [AbstractGenerateMemberCodeFixProvider](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeFixes/GenerateMember/AbstractGenerateMemberCodeFixProvider.cs,14) and view derived types.

![image](https://cloud.githubusercontent.com/assets/9797472/10147599/c2f1422e-65e3-11e5-8d43-e3184dd3d479.png)
Only C# types are shown, even though several VB classes also derive from AbstractGenerateMemberCodeFixProvider

**Comment by Pilchie** [comment] 2015-09-29 16:45
From #5514, I think the problem is that the IDE code isn't calling `FindSourceDefinition` on the symbol.

**Comment by brettfo** [comment] 2015-11-07 00:01
Dupe of #4973.

**Closed by brettfo** 2015-11-07 00:01 UTC
Labels: Area-IDE, Bug
