### ISSUE TITLE
C# Editor: references number location realated with attributes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63868] opened 2022-09-08 21:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Editor:-references-number-location-re/10136082)._

---
Currently numbers of references appear below of the element attributes.
On my opinion should be the other way around since the attributes also define the element 

On the example below between the "Serializable" and the "public class ..." is the number of references and for me the be fisrt the number of references.

![References.PNG](https://aka.ms/dc/image?name=B5dbfb7aff3e9422c8ba3609e7d91f321637975728822973663_References.PNG&tid=5dbfb7aff3e9422c8ba3609e7d91f321637975728822973663)

Thanks in advance.

---
#### Feedback Bot on 8/31/2022, 08:29 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2022-09-08 22:19
This is a codelens request.  And i believe is by design.  Indeed, originally it started the other way, but was changed due to overwhelming feedback initially that this stuff should attach to the signature, and not to things like attribute/doc comments.

**Comment by CyrusNajmabadi** [comment] 2022-09-08 22:20
I'm gonig to preemptively close this as we've had codelens for 10+ years, had a ton of feedback to do it the current way, and have heard nothing in the following time to change it.  There just isn't the demand to justify this change IMO.

**Closed by CyrusNajmabadi** 2022-09-08 22:20 UTC
Labels: Area-IDE, 0 - Backlog
