### ISSUE TITLE
Rename reports false conflict for equivalent reduced symbols

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#6124] opened 2015-10-18 13:19 UTC
_astoudningly evil corner case_

Source:

**ProjectA**:

``` C#
public static class Y {
    public static void M(this int v, int extra = 0) { }
}
```

**ProjectB** (references ProjectA):

``` C#
class X { }
class C {
    const int X = 0;
    C() {
        Y.M(X);
    }
}
```

Renaming `Y` to `X` will report an unresolvable conflict at `X.M(X)`, even though the compiled output of that statement [isn't changed at all by the rename](http://tryroslyn.azurewebsites.net/#f:>ilr/MYGwhgzhAEDC0G8BQ1XWAewHYQC7QEst8ANaAXmgAYBuFNANwwIBNoBBACgEpFoSAdAFlOJbjWgBfeqiatoAIR58AmsNHipSaUjxhcBYOnBRoKxDOgAHAK4AjEIeh6DRuWxG4AFgRhF8DAA0hMTQAKYAHrgATmAU1LwIWtJAAAA=)

**Comment by dpen2000** [comment] 2015-12-03 03:01
Is this fixed now? I can't reproduce in VS 2015 Update 1

**Comment by CyrusNajmabadi** [comment] 2023-02-07 01:01
Subsumed in https://github.com/dotnet/roslyn/issues/66730.

**Closed by CyrusNajmabadi** 2023-02-07 01:01 UTC
Labels: help wanted, Area-IDE, Feature Request, Pedantic ;), Feature - Rename
