### ISSUE TITLE
Proposal: non-removable 'using' operator

### ISSUE THREAD

**Issue by WrongBit** [dotnet/roslyn#41259] opened 2020-01-28 08:16 UTC
When you use VS help on removing unused 'using's, some of 'em should **not** be removed, because they are used in a different configuration (RELESE, DEBUG, etc), but not needed in current one.
I suggest some mark for such using 'never remove it!'. Suggestions:

    using Abc.Def;// KEEP!

    [Keep]using Abc.Def;

    using! Abc.Def;

We have many variants.
OFFTOP: usings are such a clumsy idea! Why they are not kept at project level? Why they are needed in every single file? (I speak not about ambiguous cases)

**Comment by CyrusNajmabadi** [comment] 2020-01-28 18:43
> Why they are needed in every single file? (I speak not about ambiguous cases)

Because then your code changes meaning based on config settings to your compiler.

**Comment by jinujoseph** [comment] 2020-01-28 20:47
Duplicate of #24084

**Closed by jinujoseph** 2020-01-28 20:47 UTC
Labels: Area-IDE, Feature Request, IDE-Formatter
