### ISSUE TITLE
[Refactoring] Extract Resource

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#25497] opened 2018-03-15 17:54 UTC
This would be a refactoring that allows you to select a hard-coded string in a .cs or .xaml file and use the lightbulb menu to move it to a .resx file (existing or new). 

Look into handling existing resource keys with same value and comments as well.

**Comment by alrz** [comment] 2018-04-18 16:47
Dupliacte of https://github.com/dotnet/roslyn/issues/16624

**Comment by jinujoseph** [comment] 2018-08-16 22:52
closed as dupe of  https://github.com/dotnet/roslyn/issues/16624

**Closed by jinujoseph** 2018-08-16 22:52 UTC
Labels: Area-IDE, Feature Request
