### ISSUE TITLE
CodeGeneration produces unnecessary parentheses

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#26586] opened 2018-05-03 14:22 UTC
**Version Used**: master

**Steps to Reproduce**:

Attempt to run CodeGeneration tests like:

https://github.com/dotnet/roslyn/blob/ef11fa5e23c823ecf76e401e0b35747d43b57169/src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs#L130-L138

**Expected Behavior**: The test passes.

**Actual Behavior**:

```
Test Name:	Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1
Test FullName:	Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1
Test Source:	C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\ExpressionGenerationTests.cs : line 129
Test Outcome:	Failed
Test Duration:	0:00:04,771

Result StackTrace:	
at Roslyn.Test.Utilities.AssertEx.Fail(String message) in C:\code\roslyn\src\Test\Utilities\Portable\Assert\AssertEx.cs:line 341
   at Roslyn.Test.Utilities.TokenUtilities.AssertTokensEqual(String expected, String actual, String language) in C:\code\roslyn\src\Test\Utilities\Portable\Syntax\TokenUtilities.cs:line 45
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.AbstractCodeGenerationTests.Test(Func`2 nodeCreator, String cs, String vb) in C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\AbstractCodeGenerationTests.cs:line 31
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1() in C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\ExpressionGenerationTests.cs:line 131
Result Message:	
Unexpected token.  Actual '^(^ 1 ) + ' Expected '^1^ + 2  '
Actual:
(1) + (2)
```

The test failure seems to be caused by unnecessary parentheses.

**Comment by Paxxi** [comment] 2018-07-22 16:31
I'm interested in taking care of this issue.

**Comment by sharwell** [comment] 2018-07-22 16:49
@Paxxi Awesome, let us know if you have questions 😄

**Comment by CyrusNajmabadi** [comment] 2018-07-22 18:58
FWIW: This is by design.  SyntaxGeneration adds parentheses blindly in order to ensure there is no ambiguity concern.  It's then the responsibility of Simplifier.ReduceAsync to remove parentheses that aren't necessary.

**Comment by CyrusNajmabadi** [comment] 2018-07-22 21:00
> Or are you saying it might be a waste of time to take this further because it might break things? If that's the case then I guess the fix is to update the tests to match the current behavior.

Yup.  I'm saying that the current behavior is intentional  We don't want to duplicate the parentheses removing logic that we already have fleshed out deeply in the Simplifier.  I would just update the expected code in the test.

**Comment by sharwell** [comment] 2018-07-23 03:02
> I would just update the expected code in the test.

Can we add a test next to the original which calls the simplifier (so it's easy for a reader to see how to make the parentheses go away)?

**Comment by CyrusNajmabadi** [comment] 2018-07-23 03:21
We could change the core test function to run the simplifier as well, and have that provided with all tests.  But that would be a fair bit of effort to have to go update all the tests . might be worth it though.

**Comment by Paxxi** [comment] 2018-07-23 05:21
I don't mind if it's a bit of work, I'm doing this to learn about the codebase so poking around in a lot of tests is a good way to do that 😄 
I could use some hint though, when looking at how the simplifier is used it seems to be aimed at higher level usage. The [Reduce methods](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Simplification/Simplifier.cs,130) are all async and takes a `Document`. Is there another way to do the simplification or what would be the best way to approach this?

Regarding the [Parenthesize method](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs,296) is there ever a reason to add parenthesis for character literals or identifier names? It seems unnecessary but I'm assuming I'm missing something.

**Comment by CyrusNajmabadi** [comment] 2018-07-23 05:48
> Regarding the Parenthesize method is there ever a reason to add parenthesis for character literals or identifier names? It seems unnecessary but I'm assuming I'm missing something.  

It's hard to tell in isolation, because it requires knowing every bit of precedence in the language.  But here's an example of why it can be bad to remove parentheses even around something 'safe' like an identifier name:

```c#
F((a) < b, c > (d + e))
```

You have parens around an 'a' and it's in a binary expression (like 'CreateAddExpression', except in this case it's a less-tahn expression).

However, if you remove these parens, then you'll break this code.  Because you end up with:  


```c#
F(a < b, c > (d + e))
```

But this will now parse as a generic invocation of "a" with type arguments, "b" and "c", with argument "d + e".

This is why we split the concerns here.  The generator just produces code that is safe.  And the Simplifier figures out if it's actually ok.

**Comment by CyrusNajmabadi** [comment] 2018-07-23 05:54
> I could use some hint though, when looking at how the simplifier is used it seems to be aimed at higher level usage. The Reduce methods are all async and takes a Document. Is there another way to do the simplification or what would be the best way to approach this?

I would look at SimplifierAPITests to see examples of how this can be done.

Let me know if you need more help here :)

**Comment by Paxxi** [comment] 2018-07-23 06:02
Thanks! That makes sense.

**Comment by CyrusNajmabadi** [comment] 2018-07-23 19:24
You're welcome! :)

**Comment by CyrusNajmabadi** [comment] 2020-03-07 23:12
Fixed with https://github.com/dotnet/roslyn/pull/28831

**Closed by CyrusNajmabadi** 2020-03-07 23:12 UTC
Labels: Area-IDE, Bug, help wanted
