### ISSUE TITLE
The "'var' preferences" "elsewhere" setting to "Prefer 'var'" does not fire

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#17040] opened 2017-02-08 21:40 UTC
**Version Used**: d15rel 26206.0

It does fire in the opposite direction, if you use var but say to prefer explicit type.

![image](https://cloud.githubusercontent.com/assets/235241/22758495/cf56415a-ee03-11e6-9541-f19ef0959799.png)

**Comment by zaytsev-victor** [comment] 2018-04-24 04:34
@dpoeschl it seems that it is a dupe of https://github.com/dotnet/roslyn/issues/23711

Can't reproduce it in VS2017 15.6.6. Should be fixed in https://github.com/dotnet/roslyn/pull/23718

**Comment by CyrusNajmabadi** [comment] 2023-11-22 18:16
i can't repro this either.  closing out.

**Closed by CyrusNajmabadi** 2023-11-22 18:16 UTC
Labels: Bug, Area-IDE
