### ISSUE TITLE
Code-style-analyzers should opt-out of running in generated code.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14989] opened 2016-11-04 19:34 UTC
I'm getting lots of messages about fixes to be made in files like BoundNodes.xml.generated.cs (like 'use object initializer).  These generated files should be skipped.

**Comment by Pilchie** [comment] 2016-11-04 21:58
I think this is a dupe.

**Comment by Pilchie** [comment] 2016-11-14 21:36
Dupe of #14638

**Closed by Pilchie** 2016-11-14 21:36 UTC
Labels: Area-IDE
