### ISSUE TITLE
Intellsense left hand talk to right

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38931] opened 2019-09-27 22:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/730687/intellsense-left-hand-talk-to-right.html)._

---
There are a number of rules and tools to help the developer. One of these is being able to add a missing USING reference. Another is enforcing rules about where a USING statement should appear in a code file. PLEASE make it so the two understand each other. It's really annoying to have an automatically added 'anything' immediatley become a problem.

---
#### Jane Wu [MSFT] on 9/11/2019, 11:44 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-10-01 18:32
Duplicate of #35803

**Closed by jinujoseph** 2019-10-01 18:32 UTC
Labels: Area-IDE, Resolution-Duplicate
