### ISSUE TITLE
Navigate to decompiled sources fails to load XML documentation for ImmutableArray

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#24177] opened 2018-01-11 16:27 UTC
**Version Used**: 15.6 Preview 2

**Steps to Reproduce**:

1. Add a reference to **System.Collections.Immutable**
1. Add the following code:

    ```csharp
    var array = ImmutableArray.Create(1);
    ```

1. Navigate to `ImmutableArray`

**Expected Behavior**:

XML documentation comments are shown in the decompiled result.

**Actual Behavior**:

The following message appears at the top of the file:

```csharp
/// Exception while reading XmlDoc: System.Xml.XmlException: The 'br' start tag on line 507 position 385 does not match the end tag of 'p'. Line 507, position 391.
///   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
///   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
///   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
///   at System.Xml.XmlTextReaderImpl.ParseEndElement()
///   at System.Xml.XmlTextReaderImpl.ParseElementContent()
///   at System.Xml.XmlTextReaderImpl.Read()
///   at System.Xml.XmlTextReader.Read()
///   at System.Xml.XmlTextReaderImpl.Skip()
///   at System.Xml.XmlTextReader.Skip()
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider..ctor(String fileName)
///   at ICSharpCode.Decompiler.Documentation.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
///   at ICSharpCode.Decompiler.CSharp.Transforms.AddXmlDocumentationTransform.Run(AstNode rootNode, TransformContext context)
```

**Comment by siegfriedpammer** [comment] 2018-03-23 16:04
How are we supposed to parse invalid XML? Any suggested libraries or code samples? How does VS handle this case? Thanks!

**Comment by svick** [comment] 2018-03-24 13:09
The invalid XML seems to be caused by the same issue as https://github.com/dotnet/corefx/issues/26263, which has already been fixed. When I look at the XML file in System.Collections.Immutable 1.4.0 on NuGet (the latest version there), I see the malformed XML. But when I look at version 1.5.0-preview3-26323-09 on [.Net Core MyGet](https://dotnet.myget.org/gallery/dotnet-core), it has correct XML.

So, I think this issue will fix itself once a new version of System.Collections.Immutable is published to NuGet.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 19:42
Closing out as the underlying issue was fixed.

**Closed by CyrusNajmabadi** 2024-10-19 19:42 UTC
Labels: Bug, Area-IDE
