### ISSUE TITLE
VS 2017 RC: "View Directed Syntax Graph" does not appear when right-clicking a node in the Syntax Visualizer

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#15691] opened 2016-12-06 00:06 UTC
**Version Used**: 1.3.0.60420 (latest from https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK)

**Steps to Reproduce**:

1. Download Visual Studio 2017 RC
2. Install the .NET Compiler Platform SDK from the link above
3. Open any C# project
4. Open the Syntax Visualizer and right click one of the syntax elements

**Expected Behavior**: There should be a "View Directed Syntax Graph" option at the top of the menu.

**Actual Behavior**: There is an empty section there instead.

![](http://i.imgur.com/zlgjsNS.png)

Is this a known issue? I'm just getting started with Roslyn, so I'm not sure if I've done anything wrong. Thanks!

**Comment by Pilchie** [comment] 2016-12-12 21:22
Moving to SDK and Samples.

I suspect that this might be because your VS install doesn't include the diagramming components necessary to support that option.

@jmarolf - what do you think?

**Comment by jmarolf** [comment] 2016-12-13 00:53
@Pilchie thats my guess but I'll take a look

**Comment by jwooley** [comment] 2017-02-23 03:02
Confirmed that using the installer's "Individual Features" and selecting the "Code Map" option enables this feature again.
![image](https://cloud.githubusercontent.com/assets/365256/23243072/823996ae-f94a-11e6-86de-6a4c210a895e.png)

**Comment by jmarolf** [comment] 2017-12-15 12:21
Issue moved to [dotnet/roslyn-sdk #65](https://github.com/dotnet/roslyn-sdk/issues/65) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jmarolf** 2017-12-15 12:21 UTC
Labels: Area-SDK and Samples

**Comment by JoshuaTerry** [comment] 2018-05-07 15:13
Any idea where this has moved to now?  Code Map is no longer and option.
![image](https://user-images.githubusercontent.com/22823725/39709387-add56e7c-51e7-11e8-8fa8-70e7c1755b38.png)

**Comment by jwooley** [comment] 2018-05-07 16:42
The DGML Editor tools aren’t installed by default when installing VS. You need to add the DGML editor component. See https://github.com/dotnet/roslyn/issues/15691.
