### ISSUE TITLE
Calling interpolated string handler method on ref parameter (or ref local) causes compilation error

### ISSUE THREAD

**Issue by addabis** [dotnet/roslyn#56624] opened 2021-09-22 21:39 UTC
A regression that breaks an existing code that uses `StringBuilder`.

**Version Used**: 
.NET 6.0 RC1 (Roslyn 4.0)

**Steps to Reproduce**:

Our codebase uses `StringBuilder`, but it is reproducible with any [InterpolatedStringHandler].

Use the following:
```
using System.Runtime.CompilerServices;

namespace Test;

class Program
{
    static void Main()
    {
        Test test = new Test();
        Foo("test", ref test);
    }

    static void Foo(string name, /* CAUSE! */ ref Test state)
    {
        state.Append($"{name}");
    }
}

class Test
{
    public void Append([InterpolatedStringHandlerArgument("")] ref MyInterpolatedStringHandler handler)
    {
    }
}

[InterpolatedStringHandler]
struct MyInterpolatedStringHandler
{
    public MyInterpolatedStringHandler(int literalLength, int formattedCount, Test stringBuilder)
    {
    }

    public void AppendFormatted<T>(T value)
    {
        Console.WriteLine("Hit");
    }
}
```

**Expected Behavior**:

Should compile and execute the `AppendFormatted` method, which is the behavior when `ref` is removed from the `state` parameter.

**Actual Behavior**:

Compilation error:
```
error CS1615: Argument 3 may not be passed with the 'ref' keyword
```

(this means argument 3 of the `MyInterpolatedStringHandler` ctor, i.e. the instance of `Test`, )

The same happens if the method is invoked on a ref local.

**Comment by svick** [comment] 2021-09-24 09:53
Hi Daniel,

this looks like a duplicate of https://github.com/dotnet/roslyn/issues/56579.

**Comment by addabis** [comment] 2021-09-24 11:07
> Hi Daniel,
> 
> this looks like a duplicate of #56579.

Thanks, it seems like that.

I guess the selected overload should depends on presence of `ref` - valued overload in InterpolatedStringHandler, i.e. in my case:

**Comment by addabis** [comment] 2021-09-24 11:44
> Hi Daniel,
> 
> this looks like a duplicate of #56579.

Thanks, it seems like that.

I think there is a slight difference though - in case of `out` parameters you cannot use the overload with `[InterpolatedStringHandler]` (at least not for value types).

In case of `ref`, if there is an appropriate ctor on the `[InterpolatedStringHandler]` (in above example it would be `(int, int, ref Test)`) the overload can still be used.

**Comment by 333fred** [comment] 2021-09-28 19:21
This is unrelated to #56579. This is intended behavior: if you're passing `Test` by ref, you need to accept it by `ref` in your handler constructor. Generally, it all needs to match up: it's likely you're introducing a bug if you haven't made it line up.

**Comment by addabis** [comment] 2021-09-28 19:32
@333fred I'm not sure you've taken into account the whole description. The above code is just an example, I'm having problems with `StringBuilder` on an existing codebase.

```
public void Visit<TValue>( string name, TValue value, ref StringBuilder state )
{
    // The following line results in build error.
    state.Append( $"{typeof( TValue )} {name} = {value}; " );
}
```

If this is intended behavior, the problem is in `AppendInterpolatedStringHandler` in BCL, which does not have an appropriate overload.

**Comment by 333fred** [comment] 2021-09-28 20:06
@stephentoub we may want to add a `ref` overload for `Append` to deal with this. The other option would be to revisit the rules around ref, but I'm concerned that in cases where you have a struct, not having these strict rules will result in unintended bugs.

**Comment by stephentoub** [comment] 2021-09-28 20:10
> we may want to add a ref overload for Append to deal with this

Can you elaborate?  What overload are you proposing?

**Comment by 333fred** [comment] 2021-09-28 20:34
An overload to the `AppendInterpolatedStringHandler` constructor that takes the `StringBuilder` by ref instead of by value, to deal with the case where a user calls `Append` on a `StringBuilder` that was passed by ref instead of by value.

**Comment by stephentoub** [comment] 2021-09-28 20:44
> An overload to the AppendInterpolatedStringHandler constructor that takes the StringBuilder by ref instead of by value, to deal with the case where a user calls Append on a StringBuilder that was passed by ref instead of by value.

What happens then in the repro when the line:
```C#
static void Foo(string name, /* CAUSE! */ ref Test state)
```
is changed to be:
```C#
static void Foo(string name, /* CAUSE! */ in Test state)
```
?  Doesn't the same issue arise?  And we can't add both ref and in overloads.

**Comment by 333fred** [comment] 2021-09-28 21:09
Here's what I'm imagining the BCL scenario should look like:

```cs
using System.Runtime.CompilerServices;

namespace Test;

class Program
{
    static void Main()
    {
        Test test = new Test();
        Foo1("test", ref test);
    }

    static void Foo1(string name, /* CAUSE! */ ref Test state)
    {
        state.Append($"{name}");
    }

    static void Foo2(string name, /* CAUSE! */ in Test state)
    {
        state.Append($"{name}");
    }

    static void Test(in Test test) { }
}

class Test
{
    public void Append([InterpolatedStringHandlerArgument("")] ref MyInterpolatedStringHandler handler)
    {
    }
}

[InterpolatedStringHandler]
struct MyInterpolatedStringHandler
{
    public MyInterpolatedStringHandler(int literalLength, int formattedCount, in Test stringBuilder)
    {
    }
    public MyInterpolatedStringHandler(int literalLength, int formattedCount, Test stringBuilder)
    {
    }

    public void AppendFormatted<T>(T value)
    {
        Console.WriteLine("Hit");
    }
}
```

Now, there is currently a bug where `Foo1` fails to compile because `ref` isn't being allowed to match `in` in the constructor, but that's a separate compiler bug. A single `in` overload for the handler should fix the overloads once I fix the compiler bug.

**Comment by stephentoub** [comment] 2021-09-28 21:10
I also don't understand why this is an issue.  I can write:
```C#
using System.Text;

public class C
{
    public void M(ref StringBuilder sb) => new AppendInterpolatedStringHandler(sb);
}

public struct AppendInterpolatedStringHandler
{
    public AppendInterpolatedStringHandler(StringBuilder sb){}
}
```
without issue... why does the compiler not bind successfully in a similar case when it's generating that ctor invocation as part of the lowering for the handler construction?

**Comment by 333fred** [comment] 2021-09-28 21:37
@stephentoub and I talked about this offline. On the one hand, the rule as specified currently can help protect against bugs from differing refkinds on value structs. On the other hand, we think the current user experience leaves something to be desired for handler authors and is somewhat inconsistent. We'll run the idea of allowing the refkind variance here by LDM and see what they think.

**Closed** 2021-10-02 03:04 UTC
Labels: Bug, Area-Compilers, New Feature - Interpolated String Improvements
