### ISSUE TITLE
Don't run the nullable walker when the feature is not enabled

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33912] opened 2019-03-06 23:06 UTC
In a body of code where there are no warnings enabled for the nullable feature, we should not run the nullable walker.

**Comment by jcouv** [comment] 2019-06-17 21:26
Accidentally opened a replacement for this. Closing as dupe of https://github.com/dotnet/roslyn/issues/36131

**Closed by jcouv** 2019-06-17 21:26 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Tenet-Performance
