### ISSUE TITLE
Parser regression involving async

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#13171] opened 2016-08-15 14:07 UTC
**Version Used**: master

**Steps to Reproduce**:

1. Compile attached sample

```csharp
using System;
using System.Threading;

class X
{
	void ParserError (IAsyncResult ar)
	{
		var async = ar.AsyncState as ThreadStart;
		async.EndInvoke (ar);
	}
}
```

**Expected Behavior**:

No parser error

**Actual Behavior**:

(9,19): error CS1001: Identifier expected
(9,19): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
(9,19): error CS1003: Syntax error, '[' expected
(9,23): error CS1003: Syntax error, ']' expected

**Comment by svick** [comment] 2016-08-15 15:03
Is this a duplicate of https://github.com/dotnet/roslyn/issues/13090?

**Comment by jaredpar** [comment] 2016-08-15 20:53
@svick is correct this is a duplicate.  We have a fix in progress for this bug.

**Closed by jaredpar** 2016-08-15 20:53 UTC
