### ISSUE TITLE
File is continuously parsed and never seems to finish.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/roslyn#14617] opened 2016-10-19 15:07 UTC
**Version Used**: 
Latest (VS2015)

**Steps to Reproduce**:
1. Open https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Repositories/Configuration/Indexes/EventIndex.cs 
2. Make any changes to the mappings or just view them. 
3. Watch cpu go nuts and never stop.

**Expected Behavior**:
Source should be parsed and cached and return quickly.

**Actual Behavior**:
The cpu gos crazy, I just left visual studio open for 20 minutes while doing nothing on the vm and the cpu never stopped  or went below 30%. I've been experiencing this issue for a long time, I thought it was resharper and then I dug into this issue with them and they pointed me here :).

![screen shot 2016-10-19 at 10 03 47 am](https://cloud.githubusercontent.com/assets/1020579/19524444/5d24e83e-95e3-11e6-9f6c-ed61b7321144.png)

<img width="654" alt="screen_shot_2016-10-19_at_3 58 59_pm" src="https://cloud.githubusercontent.com/assets/1020579/19524622/f99c0170-95e3-11e6-9603-fd9e8ad76455.png">

![screen shot 2016-10-19 at 10 09 31 am](https://cloud.githubusercontent.com/assets/1020579/19524682/2963c898-95e4-11e6-80af-ad258ef05124.png)

**Comment by niemyjski** [comment] 2016-10-19 15:12
It's worth noting that I have tried with both c# solution analysis on and off and it's still an issue.

**Comment by niemyjski** [comment] 2016-10-19 17:00
I just installed VS15 and am also seeing this behavior with basic install (no addins). I reported with profiling

**Comment by gafter** [comment] 2016-10-19 17:43
Not sure if this is a compiler or IDE issue, but compilers seems a reasonable place to assume for purposes of investigation.

**Comment by niemyjski** [comment] 2016-10-19 18:00
Just loading my solution always seemed to use a ton of cpu usage and it seems to be getting worse (over the past 1-2 years). I always thought it was background services / vs plugins until recently it became so unbearable when I open my index settings (contains tons of expressions) it would get really really bad. I decided to look into it further. I've experienced this in VS2013,2015 and 2016 now.

**Comment by AlekseyTs** [comment] 2016-11-21 22:56
I am not able to reproduce high CPU utilization. Tried opening solution and the file in 
- Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3 Microsoft .NET Framework Version 4.6.01055 
- Microsoft Visual Studio Enterprise 15 Preview 3 Version 15.0.25421.0 PREVIEW Microsoft .NET Framework Version 4.6.01055

@niemyjski Could you provide precise repro steps or, perhaps, share the profiling data?

**Comment by AlekseyTs** [comment] 2016-12-29 19:01
@niemyjski Could you, please, provide precise repro steps or, perhaps, share the profiling data? Otherwise, we will have to close this issue as "No Repro".

**Comment by AlekseyTs** [comment] 2017-01-06 18:25
Closing as "Not Reproducible".

**Closed by AlekseyTs** 2017-01-06 18:25 UTC
Labels: Area-Compilers, Bug, Need More Info, Perf-Epic
