### ISSUE TITLE
Implement interface creates members in undesired way

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#6783] opened 2015-11-14 11:10 UTC
When I execute Implement interface I expect it to add all the members at the end of class.

What I want is to put all the members in some region to group them by implemented interface.
Instead members are generated in some "smart" way which breaks my scenario and I have to find this members in some other regions.

In a perfect scenario if there are regions in a class it have to ask me where to put this generated members.
At least current behavior must me configurable so I can disable it and has all the members generated at the end of class.

**Comment by HellBrick** [comment] 2015-11-14 13:03
I agree. There was a "surround generated code with region" option in previous version of VS, it would be nice to have it back and use it to control this behavior. If it's enabled, I think it would be perfect to place the generated members inside a corresponding region *in the same order they are declared in in the interface*.

**Comment by dpoeschl** [comment] 2015-11-15 02:06
Related: https://github.com/dotnet/roslyn/issues/4671

**Comment by Pilchie** [comment] 2017-01-19 03:41
This is a duplicate of https://github.com/dotnet/roslyn/issues/4939

**Closed by Pilchie** 2017-01-19 03:41 UTC
Labels: Area-IDE, Bug
