### ISSUE TITLE
[Test failure] vs-integration System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20567] opened 2017-06-30 14:51 UTC
windows_debug_vs-integration_prtest [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5698/) in https://github.com/dotnet/roslyn/pull/20563
```
xunit produced no error output but had exit code 1
```
Roslyn.VisualStudio.IntegrationTests.dll.out.log:
```
  Finished:    Roslyn.VisualStudio.IntegrationTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
```
See also https://github.com/dotnet/roslyn/issues/15497.

**Comment by Pilchie** [comment] 2017-06-30 16:04
@jasonmalinowski @jaredpar what is the latest on this discussion?

**Comment by jaredpar** [comment] 2017-06-30 16:10
@cston and I chatted about this yesterday and came up with a theory. Essentially there is a thread / task which gets spawned during the test run, doesn't complete but then finishes after xunit unloads the AppDomain running our test code. It fits the symptoms. 

That theory hasn't come with a great way to find out which thread is at fault though.

**Comment by Pilchie** [comment] 2017-07-03 20:11
Can you think of a way we can track this down?

**Comment by jasonmalinowski** [comment] 2017-07-03 20:19
This is a dupe of #15497 which is our primary tracking bug. @sharwell if you want to help @cston out let's use that parent bug.

**Closed by jasonmalinowski** 2017-07-03 20:19 UTC
Labels: Area-IDE, Flaky, Test
