### ISSUE TITLE
ArgumentOutOfRangeException in SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpansForPreviousTree

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23074] opened 2017-11-08 17:41 UTC
When editing C# code, the frequently IDE raises the following error (since 15.5 pre1):

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpansForPreviousTree[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, ITextSnapshot lastSnapshot, Document lastDocument, List`1 classifiedSpans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpans[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, List`1 classifiedSpans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags[TClassificationService](NormalizedSnapshotSpanCollection spans, HostLanguageServices languageServices, IClassificationDelegationService`1 delegationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/145998/systemargumentoutofrangeexception-when-editing-c-c.html
VSTS ticketId: 521343_
_These are the original issue comments:_

Jérôme Laban on 11/7/2017, 06:17 AM (27 hours ago): <p>Here's a detailed log of the error.</p>

Jinu Joseph [MSFT] on 11/8/2017, 08:56 AM (44 min ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

**Comment by freemstr** [comment] 2017-11-09 14:43
The issue is reported in VS 15.5, I encounter this in 15.4.3 which makes it a production issue,
any workaround is appreciated.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)

**Comment by jinujoseph** [comment] 2017-11-13 18:07
Also reported [here](https://developercommunity.visualstudio.com/content/problem/146608/exception-in-editor-1.html)

**Comment by dpoeschl** [comment] 2017-12-07 20:47
Just encountered this in a 15.6 build of 27108.4002.vsuvscore

**Comment by jinujoseph** [comment] 2018-01-24 19:52
@freemstr we were not able to repro this with latest version of VS 15.6 
Can you try with the latest version and provide the repro steps for us to investigate pls

**Comment by gundermanc** [comment] 2018-02-06 07:09
Just hit a few times today in d15.6 27404.0. I don't have any specific repro yet, but there are a few files in the editor solution that seemed to be risk factors for hitting it.

``

**Comment by sharwell** [comment] 2018-02-15 13:49
:link: Also seen here: https://developercommunity.visualstudio.com/content/problem/196749/servicehubhostclr-high-cpu-usage.html

**Comment by jasonmalinowski** [comment] 2018-02-16 01:34
FYI that #24883 _might_ fix this bug. Not sure. I am seeing debug asserts in linked file editing scenarios, and that might point to missync issues causing this bug. Somebody would have to give a better chance at reproing this in linked file cases.

**Comment by jasonmalinowski** [comment] 2018-02-22 18:35
Going to close this believing that #24883 is the right fix for it.

**Closed by jasonmalinowski** 2018-02-22 18:35 UTC
Labels: Area-IDE, Bug, Developer Community, _Product-level triaged

**Comment by okarpov** [comment] 2020-02-23 08:24
still the same under VS 2019 Community 16.4.5


When you copy a few rows of an html element style from google chrome developer toolbar and 
paste it into VS 


<entry>
    <record>5400</record>
    <time>2020/02/23 08:14:50.994</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: span&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.EditorHelpers.ProjectionBufferHelper.MapToViewBuffer(IBufferGraph bufferGraph, ITextBuffer primaryBuffer, ITextBuffer secondaryBuffer, ITextRange range)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.EditorHelpers.ProjectionBufferHelper.MapToViewBuffer(ITextView textView, ITextBuffer secondaryBuffer, ITextRange range)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Commands.PasteCommandHandler.SelectSpanForFormatting(Int32 startPosition, Int32 endPosition, ITextBuffer textBuffer, ITextView textView)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Commands.PasteCommandHandler.FormatAfterPaste(Int32 startPosition, Int32 endPosition, ITextBuffer subjectBuffer, ITextView textView)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Commands.PasteCommandHandler.ExecuteCommand(PasteCommandArgs args, Action nextCommandHandler, CommandExecutionContext executionContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;Execute&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

**Comment by CyrusNajmabadi** [comment] 2020-02-23 17:48
@okarpov That seems to be a different issue.  The stacks are not the same at all.  Can you file a different bug (through VS' feedback mechanism)?

**Comment by okarpov** [comment] 2020-02-23 18:00
> @okarpov That seems to be a different issue. The stacks are not the same at all. Can you file a different bug (through VS' feedback mechanism)?

ok, thx
