### ISSUE TITLE
Bypass Find panel when search returns only one other result

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#61010] opened 2022-04-28 12:38 UTC
**Version Used**: 

Version 17.3.0 Preview 1.0 [32427.455.main]

**Steps to Reproduce**:

```c#
partial class C
{
    int _field;

    C(int param)
    {
        _field = param; // FAR on "param" should go two lines up
    }
}

partial class C // Go to definition on "C" should jump to the C on line one
{}
```

**Expected Behavior**:

Invoking these operations should bypass any kind of result list when there is only one (other) candidate, moving the caret directly.

This:
- Is faster for the developer
- Preserves previous Find results
- Keeps the input focus directly in the editor

**Actual Behavior**:

A tool window pops open, takes the input focus, loads, renders. You look, parse and interact, away from the editor.

This feels less streamlined and responsive than a direct jump would be.

**Comment by CyrusNajmabadi** [comment] 2022-04-28 14:43
Here's the problem. We don't know there's only one result. There may be many.  The operation is literally searching, and is streaming the results in as it finds them  

So We only know there's one once the search is *over*. So the search may take 10 seconds, with one result near immediately, and another 9.9 seconds later. 

We need a way to convey that the search is ongoing and then complete, and a place to have the results of it turns out there are many. 

If the operation just returned all the results at once this would be easy. But it would also mean having to wait the entire time for all of them to come in.

**Comment by sharwell** [comment] 2022-04-28 18:15
@CyrusNajmabadi do you see any need to bring this one to review? I don't see a significant need to change the behavior here since the command name isn't "Go To Reference".

**Comment by CyrusNajmabadi** [comment] 2022-04-28 19:02
I'm find not bringing this to review.

**Comment by drewnoakes** [comment] 2022-04-28 21:09
I understand the explanation here, but the feature exists in other IDEs today (and is wonderful) so it is definitely technically possible.

As a developer, I'm going to have to wait for all results to appear to understand them properly anyway.

The decision to open a tool window could be deferred until a second result was found.

**Comment by CyrusNajmabadi** [comment] 2022-04-28 21:13
How do those other tools work?  Say the find takes 20 seconds.  What is your experience in that time while the computation is happening?

**Comment by CyrusNajmabadi** [comment] 2022-04-28 21:17
> As a developer, I'm going to have to wait for all results to appear to understand them properly anyway.

FWIW, i strongly disagree with this.  I will commonly do FAR operations and then start working on some of the results i care about, even while the rest of the results come in.  

> The decision to open a tool window could be deferred until a second result was found.

This is potentially possible, with caveats though.  One core benefit of the window is that it really is decoupled.  So i can (and do) continue to do work, whiel the results are there for me to go and use in teh future even as i edit.  If i start a FAR operation, i do want to be able to edit/move/etc. and have the results arrive, without having my navigation be interrupted by this feature now saying: "oh i found the first resutl 10 second in, time to take you there". :-/

**Comment by drewnoakes** [comment] 2022-04-28 21:22
I'll check when I'm at a computer in a bit, but from memory there's no feedback during the wait, but the delay is rarely long enough for me to notice, even in large solutions. Maybe if parsing is ongoing then an indication that the feature isn't ready is displayed.

In VS most searches are also very fast. For the pathological case (or the ongoing parsing case) we could time out after some period and show a tool window just to provide feedback.

Having a tool window for a single result is needlessly disruptive to flow. If you haven't experienced what I'm talking about, I can share my screen so you can see and feel it.

**Comment by davidwengier** [comment] 2022-04-29 02:32
One thing isn't clear to me @drewnoakes: Why did you invoke FAR and not Go To Def?

To me, when I use FAR its because I know there are possibly more than one result, and having the tool window to act as my todo list is a good thing. If FAR sometimes navigated it would probably be jarring, and if it always navigated, it would probably be disruptive (as it doesn't know if where its taking me too is where I want to go)

When I expect one result and a quick navigation, I use Go to Def, and that does exhibit the behaviour you're talking about, where it only pops the window if there is more than one.

**Comment by davidwengier** [comment] 2022-04-29 03:53
> From your team's perspective it may seem very different

I think its different from the command perspective to. ie Go To vs Find. Perhaps what you're really asking for is a new feature for a "Go to Reference(s)" command.

> Because I want to be able to invoke it on a definition too, which currently is a no-op.

I'll we'll just have to agree to disagree. If I was executing FAR on a parameter (or any other definition) then having the list of things that reference that in a tool window is what I would want. If there is one, its just a shorter list.

I agree with you about wanting VS to read my mind as to whether to replace an existing find window, vs keeping the previous one (because I _never_ remember to click Keep Results!)

**Comment by CyrusNajmabadi** [comment] 2024-11-22 01:26
Closing out as by design.  Note that we have updated certain features (like go-to-impl) to navigate to a single item if we only get one and we get it in time.

However, this is very much not in scope for 'far' as this is not a 'go' command, it's a 'find' command.  Finding, and then having the reuslt to be able to continually use and navigate to while you are will working is a core part of this.

**Closed by CyrusNajmabadi** 2024-11-22 01:26 UTC
Labels: Area-IDE, Resolution-By Design, IDE-Navigation
