### ISSUE TITLE
Issues with formatting and whitespace around !! annotation

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59580] opened 2022-02-16 18:32 UTC
**Version Used**: 
Version 17.2.0 Preview 2.0 [32207.482.main]

Blocks dogfooding.

Attempted to use `!!` in Roslyn.sln:

1) Compiler reports error when whitespace is in between parameter name and `!!`:
![image](https://user-images.githubusercontent.com/41759/154332331-92432b3f-a1a7-4abb-b6e5-f5777eff44fd.png)

2) Formatter reports warning (#58798):
![image](https://user-images.githubusercontent.com/41759/154332192-f8bd8d6c-cf96-4cbe-9772-c41035c5ab9d.png)

**Comment by tmat** [comment] 2022-02-16 18:33
@RikkiGibson

**Comment by RikkiGibson** [comment] 2022-02-16 18:36
This looks like a duplicate of #58798

**Comment by tmat** [comment] 2022-02-16 18:37
Note - the first one isn't a formatter issue.

**Comment by RikkiGibson** [comment] 2022-02-16 18:41
It does seem like a whitespace-insensitive language should not error in scenario (1) :)

**Comment by Youssef1313** [comment] 2022-03-06 08:21
> It does seem like a whitespace-insensitive language should not error in scenario (1) :)

Even more interestingly, it **does** already parse with the whitespaces *only if* the type is nullable, e.g:

```csharp
#nullable enable

public class C {
    public void M(string? x  !!) { // no error. Remove `?` and boom
    }
}
```

**Comment by Youssef1313** [comment] 2022-03-06 09:05
There are already tests:

https://github.com/dotnet/roslyn/blob/e6ce86ce5dd83f68d51cf9ea64d2ce5f0b86e349/src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs#L7727-L7766

https://github.com/dotnet/roslyn/blob/e6ce86ce5dd83f68d51cf9ea64d2ce5f0b86e349/src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs#L7936-L7975

The two tests are exactly the same. One of them can be deleted as a cleanup.

But these tests existed before the feature was merged in `main`. An interesting repro in SharpLab:

1. Start with

    ```csharp
    #nullable enable

    public class C {
        public void M(string? x  !!) { // no error.
        }
    }
    ```

2. Remove `?`. Boom, error.
3. Refresh SharpLab. No error.

Is it incremental parsing issue?

**Comment by Youssef1313** [comment] 2022-03-06 09:30
Here is a test :)

https://github.com/Youssef1313/roslyn/commit/eef482eccfd389537f0b1fc3b4ba33ba0a606923

**Closed** 2022-03-08 01:52 UTC
Labels: Language-C#, Area-Compilers, Feature - Param Null Checking
