### ISSUE TITLE
Bad "unused field" warning for interface-implementing event

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#32281] opened 2019-01-09 06:35 UTC
**Version Used**: 
Visual Studio 2019 Preview 1.1

**Steps to Reproduce**:
```csharp
interface I
{
    event Action E;
}

class C : I
{
    public event Action E;
}

class D : I
{
    event Action I.E
    {
        add { }
        remove { }
    }
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
`C.E`: warning CS0067: The event 'C.E' is never used, after compiling
`D.E`: warning IDE0051: Private member 'D.I.E' is unused, after typing

**Comment by sharwell** [comment] 2019-01-10 18:15
📝 Note that CS0067 on `C.E` is not a bug. I'm keeping this issue open for the IDE0051 report.

**Comment by mavasani** [comment] 2019-01-10 18:19
Dupe of https://github.com/dotnet/roslyn/issues/30965 - fixed in Dev16 Preview2

**Closed by mavasani** 2019-01-10 18:19 UTC
Labels: Area-IDE, Bug

**Comment by davidwengier** [comment] 2020-09-16 23:29
> 📝 Note that CS0067 on C.E is not a bug.

@sharwell Why not? Is there an explanation for this somewhere? I was about to log an issue.

**Comment by sharwell** [comment] 2020-09-16 23:38
@davidwengier you need to use this syntax to avoid the warning

```
public​ ​event​ ​Action​ ​E { add { } remove { } }
```

**Comment by davidwengier** [comment] 2020-09-16 23:54
Yes, and I can just use the "full syntax" properly and maintain a field for the event handler, and the warning goes away, but that doesn't answer the question of why its by design that the event is unused. It actually makes this feel like more of a bug to me, since it clearly demonstrates that the error has nothing to do with events, but with the compiler complaining about its own generated code.

I'm assuming this has all been discussed before somewhere, I'm just curious to read the justifications and can't find any issue.

**Comment by sharwell** [comment] 2020-09-17 02:38
@dotnet/roslyn-compiler for answer to above

**Comment by jcouv** [comment] 2020-09-17 03:15
If you write `public event Action E;` there is a private field and only `C` will be able to invoke it. If code in `C` invokes `E()` then the warning goes away. If such code doesn't exist, then nobody can invoke it.
Yes, the generated add/remove accessors use that field, but they don't count. I didn't dig into the code to see how that's done, but it makes sense to me.

If you write `public​ ​event​ ​Action​ ​E { add { } remove { } }` there is no private field, so no problem (no unused field).

**Comment by davidwengier** [comment] 2020-09-17 07:57
I can see the argument that its unused, I guess I just don't think its worth warning for when implementing interface members. If I rewrite the event to the expanded form with no bodies the warning does indeed go away, but also if I change my code in future to trigger the event, I need to remember to update it back to the compact form if I want those events to actually fire.

**Comment by svick** [comment] 2020-09-17 13:21
@davidwengier 

> if I change my code in future to trigger the event, I need to remember to update it back to the compact form if I want those events to actually fire

[The compiler will give you a handy reminder in the form of a compile-time error.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABATARgFgAoEmAO2GjgEMBjCAAgEkSBvExrxiSSx7PlyMAogG4SAXxIk8jAMKMQLdp27YAzDz7ABQ0YzaMaKFIcmMoEALYB7SOcbTi3Rmq7YALIwBiACgBKd0Ng1xFAiRduZ0kgA===)

**Comment by davidwengier** [comment] 2020-09-17 13:39
That is surprising.

**Comment by svick** [comment] 2020-09-17 20:21
@davidwengier Why is it surprising? If you specify the accessors, the compiler doesn't generate the backing field, so it doesn't make sense for you to be able to raise the event. I believe it's been like that since C# 1.0, and it's similar to the much more recent `get`-only properties: a `get`-only property with a body can't be set, while one without a body can (in the constructor).

**Comment by davidwengier** [comment] 2020-09-17 22:05
> Why is it surprising?

Only because I didn't know that was how it worked, and don't have a deep understanding of how events get generated. eg, I assumed (before your comments) that this would work:

```
using System;
public class C 
{
    private EventHandler _handler;
    
    public event EventHandler E
    { 
        add
        {
            _handler += value;
        }
        remove
        {
            _handler -= value;
        }
    }
    
    void M()
    {
        E?.Invoke(null, EventArgs.Empty);
    }
}
```

I still think its erroneous that the compiler is complaining about the event I need to have to satisfy my interface, just because I never need to invoke it :P
