### ISSUE TITLE
csharp_space_between_method_call_parameter_list_parentheses is not respected when formatting code

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#33231] opened 2019-02-08 01:31 UTC
**Version Used**: 
Visual Studio Community v15.9.6

**Steps to Reproduce**:

1. Clone https://github.com/yaakov-h/SteamKit/tree/editorconfig (the editorconfig branch of the repo)
2. Open SteamKit2/SteamKit2.sln
3. Open a file such as CMClient.cs that has spaces between parameter lists and their surrounding parentheses
4. Press Ctrl+K Ctrl+D to reformat the document.

**Expected Behavior**:

The spaces between the parameter lists and their surrounding parentheses are preserved, e.g.:

```csharp
Debug.Assert( connection == null );
```

**Actual Behavior**:

The spaces between the parameter lists and their surrounding parentheses are removed, e.g.:

```csharp
Debug.Assert(connection == null);
```

**Additional Notes**:

The same also happens to `csharp_space_between_method_declaration_parameter_list_parentheses`.

**Comment by sharwell** [comment] 2019-02-08 03:59
`true:error` is not a valid value for this setting. It only allows the values `true` and `false`, and when an unrecognized other value is found it defaults to the default value `false`. Marking this as a duplicate of #19055 (show a warning for editorconfig with invalid values, since those values are ignored).

**Closed by sharwell** 2019-02-08 03:59 UTC

**Comment by yaakov-h** [comment] 2019-02-08 04:02
The documentation could probably do with an update then, to explain that severities do not apply to all rules.

**Comment by sharwell** [comment] 2019-02-08 04:06
They do currently specify this: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#formatting-conventions

However, it's pretty obvious that users would have a hard time finding this and it's certainly not intuitive. The analyzer to provide a warning when things aren't right would be a big help all around.
