### ISSUE TITLE
Outline collapse with "# region xyzzy" shows "n xyzzy" instead of "xyzzy"

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4653] opened 2015-08-19 18:30 UTC
Load the following code in VS and collapse the region. It shows "n xyzzy".

```cs
namespace Whatever
{
    class Program
    {
        # region xyzzy
        static void MainXX(string[] args)
        {
        }
        #endregion
    }
}
```

**Comment by Pilchie** [comment] 2015-08-19 20:46
Dupe of #4105 (already fixed after VS RTM).

**Closed** 2015-08-19 20:46 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
