### ISSUE TITLE
Exceptions in analyzers are silently ignored, except for once.

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4462] opened 2015-08-10 16:20 UTC
Repro steps (VS2015 RTM):

1. Reset the Roslyn experimental hive:

```devenv /rootSuffix Roslyn /updateConfiguration```
```devenv /rootSuffix Roslyn /resetUserData```
2. Create new analyzer project
3. In DiagnosticAnalyzer.cs, method Initialize(), replace existing code with:
```throw new Exception("TestError");```
4. F5 to start second instance
5. In second instance, open a default ConsoleApplication project and see the Exception in the first instance get hit. Resume with F5
6. The second instance now has message AD0001 in Error List:

```The User Diagnostic Analyzer 'Analyzer2.Analyzer2Analyzer' threw an exception of type 'System.Exception' with message 'TestError'.```
7. Close the second instance.
8. Restart from step 4, but observe that the message AD0001 from step 6 will never appear anymore. Not even when restarting the first instance; not even when another analyzer project is created! Only the hive reset from step 1 brings it back (once).

**Comment by bkoelman** [comment] 2015-08-31 10:50
It turns out this was caused by me upgrading nuget packages in my analyzer project to newer versions. After reverting those, all worked as expected again.

**Comment by bkoelman** [comment] 2015-08-31 12:09
I jumped to conclusions too soon. Reopening, as the issue still occurs.

**Comment by mavasani** [comment] 2015-09-04 17:54
Thanks @bkoelman. I was able to repro the issue and in fact was able to dig out an older bug with the exact same repro: https://github.com/dotnet/roslyn/issues/1521#issuecomment-88027573. Here is the snippet from that comment (which I was again able to repro):

_When I attached a debugger, I see that analyzer exception diagnostic is in fact generated and reported to AbstractHostDiagnosticUpdateSource, but error list event handler isn't hooked up to DiagnosticSource yet, causing this diagnostic not to reach the error list.
Another interesting fact is that if I delete the ".vs" directory for the C# project in Sln2 and repeat step 5. then the analyzer exception diagnostic does indeed show up in error list._

@heejaechang can you please take a look at this, as it seems like your fix for #1521 has regressed? Not sure if there is an easy way to add a regression test for this.

**Comment by mavasani** [comment] 2015-09-04 17:58
I should correct my previous comment: _"older bug with the exact same repro"_.
#1521 in fact has different repro steps but probably the same root cause.

**Comment by heejaechang** [comment] 2015-09-18 08:44
@mavasani I can't repro this. can you show me this tomorrow?

**Comment by heejaechang** [comment] 2015-09-22 12:21
@mavasani I dont think it is the connection race rather initialize method never called except the first time.

**Comment by bkoelman** [comment] 2015-09-22 12:36
From what I recall, it occured also when an exception was thrown from analyzer ctor or a field initializer. Also from RegisterCompilationStartAction callback I'm not sure; I can verify if that helps you.

**Comment by heejaechang** [comment] 2015-09-28 19:45
fix checked in. closing this

**Closed by heejaechang** 2015-09-28 19:45 UTC
Labels: Area-Analyzers, Bug
