### ISSUE TITLE
Compiler crashes in VS15.3, analyzer throws NullReferenceException in master, when call local function from nested lambda

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn#21543] opened 2017-08-16 05:46 UTC
I found the issue #16895 that mentioning compiler crash caused by local function and nested lambda. But  I can build that issue's code successfully in VS15.3 so I think this issue is different issue.

**Version Used**: VS2017 15.3.0, master(d67a95f1c01dc7064a47caecf02326a060292649)([demo at  sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsAmfABQQHsBzBCMSgb0vz/1gQYASwDGhACz4AsnBgALJigAUxOhFEimAOwCU+LvgC+lXv0Ejx2KdIjDty3Wb48K/d/nsx8ANwgAbAFc4fABefFxyNw8+WQUlZUcwgD5nD1cYmP8mUQDHKMyPa3xs3P9HNMKMwsyAYR0oJn84ADoAdQRheAAZezhlPyC4XQKamLjFFSTQ1Oix92r5zNK8kcr5ozW5mpNt903Rvl3doA===))

**Steps to Reproduce**:
```cs
using System;

class Program
{
    static void Method(Action action) { }

    static void Main()
    {
        int value = 0;
        Method(() =>
        {
            local();
            void local()
            {
                Console.WriteLine(value);
                Method(() =>
                {
                    local();
                });
            }
        });
    }
}
```

**Expected Behavior**:
I can build the above code without any errors and warnings.

**Actual Behavior**:
If I build the above code in VS15.3, the build failed due to `"csc.exe" exited with code -2146232797`.
I found a stack trace in `eventvwr.msc` -> `Windows Logs` -> `Application` -> `.NET Runtime`:
```
Application: csc.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitLocalLoad(BoundLocal local, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitDelegateCreation(BoundExpression node, BoundExpression receiver, Boolean isExtensionMethod, MethodSymbol method, TypeSymbol delegateType, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitDelegateCreationExpression(BoundDelegateCreationExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, UseKind useKind)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCoreWithStackGuard(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(BoundStatement statement)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement(BoundSequencePoint node)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl()
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitLocalLoad(Microsoft.CodeAnalysis.CSharp.BoundLocal, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitDelegateCreation(Microsoft.CodeAnalysis.CSharp.BoundExpression, Microsoft.CodeAnalysis.CSharp.BoundExpression, Boolean, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitDelegateCreationExpression(Microsoft.CodeAnalysis.CSharp.BoundDelegateCreationExpression, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(Microsoft.CodeAnalysis.CSharp.BoundCall, UseKind)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCoreWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(Microsoft.CodeAnalysis.CSharp.BoundStatement)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement(Microsoft.CodeAnalysis.CSharp.BoundSequencePoint)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundStatement>)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl()
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain, Boolean, Boolean, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan>)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
   at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

If I build the above code in master, the build succeeded but I get the following warning(same warning occurs 5 times):
```
warning AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

**Comment by Tan90909090** [comment] 2017-09-01 13:43
I found an another issue #20577. It seems to very similar to this issue.
Should I close this issue?

**Comment by JiriZidek** [comment] 2017-09-01 14:28
Looks like it is enough, that local function contains a kind of lambda:

```
        void CrashesCSC() {
            using(var ctx = new DbDataContext()) {
                var now = DateTime.Now;
                var loggedAgentsCount = (from a in ctx.Agents where !a.Deleted && !a.Template && a.Activity != Agent_Activity.Logoff select a).Count();
                var oliWithRanking = (from oli in ctx.OutboundListImports
                                      where !oli.Deleted && oli.Active &&
                                      oli.OutboundList.RankBatch != null && oli.OutboundList.Activity == OutboundList_Activity.Scheduled
                                      select oli).ToList();
                foreach(var oli in oliWithRanking) {
                    var batchSize = oli.OutboundList.RankBatch.Value * loggedAgentsCount / 100 + 1;
                    void SkipToFirstRank() {
                        var first = (from oc in ctx.OutboundCalls
                                     where oc.CallResult == OutboundCall_CallResult.Scheduled && oc.CallPhase == OutboundCall_CallPhase.Enqueue &&
                                     oc.OutboundListImportId == oli.OutboundListImportId && oc.ScheduleTime <= now && oc.Rank != null
                                     orderby oc.Rank
                                     select oc).FirstOrDefault();
                        oli.RankBarrier = batchSize;
                    }
                }
                ctx.SubmitChanges();
            }
        }

        void PassesCSC() {
            using(var ctx = new DbDataContext()) {
                var now = DateTime.Now;
                var loggedAgentsCount = (from a in ctx.Agents where !a.Deleted && !a.Template && a.Activity != Agent_Activity.Logoff select a).Count();
                var oliWithRanking = (from oli in ctx.OutboundListImports
                                      where !oli.Deleted && oli.Active &&
                                      oli.OutboundList.RankBatch != null && oli.OutboundList.Activity == OutboundList_Activity.Scheduled
                                      select oli).ToList();
                foreach(var oli in oliWithRanking) {
                    var batchSize = oli.OutboundList.RankBatch.Value * loggedAgentsCount / 100 + 1;
                    void SkipToFirstRank() {
                        //var first = (from oc in ctx.OutboundCalls
                        //             where oc.CallResult == OutboundCall_CallResult.Scheduled && oc.CallPhase == OutboundCall_CallPhase.Enqueue &&
                        //             oc.OutboundListImportId == oli.OutboundListImportId && oc.ScheduleTime <= now && oc.Rank != null
                        //             orderby oc.Rank
                        //             select oc).FirstOrDefault();
                        oli.RankBarrier = batchSize;
                    }
                }
                ctx.SubmitChanges();
            }
        }

```

**Comment by svick** [comment] 2017-09-01 15:59
Since the code compiles on `master`, I think this is another duplicate of https://github.com/dotnet/roslyn/issues/19033.

Regarding the analyzer `NullReferenceException`, I think that's a completely separate issue, possibly in SharpLab, so I have reported it as https://github.com/ashmind/SharpLab/issues/176.

**Closed** 2017-09-15 20:53 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
