### ISSUE TITLE
CSharpRenameTrackingCodeFixProvider NullReferenceException when renaming a C# interface

### ISSUE THREAD

**Issue by danlyons-softek** [dotnet/roslyn#27804] opened 2018-06-13 21:40 UTC
**Version Used**: 
`Version 15.7.3`

I was attempting to rename an interface in the solution.  I first tried the rename refactor, but every time I tried to apply the change, it would change the name back to the original.  I then renamed it manually, attempted to apply the rename code fix, and the following error occurred:
```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.Finders.NamedTypeSymbolReferenceFinder.DetermineDocumentsToSearchAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.CreateProjectToDocumentMapAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindRenamableReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.AddLocationsReferenceSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.FindAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.Renamer.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolWorkerAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

**Comment by jinujoseph** [comment] 2018-07-05 09:47
reported [here ](https://developercommunity.visualstudio.com/content/problem/286147/csharprenametrackingcodefixprovider-throws-excepti.html) also

**Comment by JoeRobich** [comment] 2019-02-01 00:02
This is a duplicate of https://github.com/dotnet/roslyn/issues/23889

**Closed by JoeRobich** 2019-02-01 00:02 UTC
Labels: Area-IDE, Bug, Developer Community
