### ISSUE TITLE
Improve Visual Basic smart indent for argument lists

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#25371] opened 2018-03-09 16:10 UTC
This is a follow up to #25323 and PR #25344 for discussion.

Currently, in argument lists, VB smart indentation tries to indent to the start of the first argument on the previous line. For example:

``` VB
Sub M()
    Method(a,
           |
End Sub
```

and...

``` VB
Sub M()
    Method(a,
        b,
        |
End Sub
```

However, this has a strange effect when the arguments span multiple lines:

``` VB
Sub M()
    Method(a +
        b, c +
        d,
           |
End Sub
```

This should be improved to use the following rules:

1. For the first line break inserted after the first argument in a list, indent to the start of the first argument.
2. For subsequent line breaks, indent to the start of the first token on the previous line.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 19:39
Closing out as we're not touching these VB experiences due to regression risk.  Note that there are refactorings now to go and fixup the indentation for all the arguments.

**Closed by CyrusNajmabadi** 2024-10-19 19:39 UTC
Labels: Area-IDE, 0 - Backlog
