### ISSUE TITLE
.editorconfig rules for private const fields don't seem to apply

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/roslyn#35860] opened 2019-05-21 23:46 UTC
**Version Used**: 

Visual Studio Enterprise 2019 Preview 16.2.0 Preview 1.0

**Steps to Reproduce**:

1. Download the attached editorconfig.txt and rename it to .editorconfig
[editorconfig.txt](https://github.com/dotnet/roslyn/files/3204962/editorconfig.txt)
2. Create a project with some private const fields
3. Name the fields in the UPPERCASE_WITH_UNDERSCORES format

**Expected Behavior**:

VS should suggest that I change these names to PascalCase

**Actual Behavior**:

VS doesn't suggest anything

**Comment by AdamYoblick** [comment] 2019-05-21 23:48
@jasonmalinowski confirmed that this is not a dupe of https://github.com/dotnet/roslyn/issues/35488

**Comment by jasonmalinowski** [comment] 2019-05-21 23:49
FYI to @dpoeschl or @sharwell.

**Comment by sharwell** [comment] 2019-05-22 00:12
Duplicate of #23706

**Closed by sharwell** 2019-05-22 00:12 UTC
