### ISSUE TITLE
'Convert switch statement to switch expression' (IDE0066) throws away comments

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#38744] opened 2019-09-18 09:12 UTC
example:

``` c#
using System;

static class P
{
    static void Main()
    {
        string input = Whatever();
        int size;
        // IDE0066 here
        switch(input)
        {
            case "abc": size = 12; break; // because magic
            case "def": size = 42; break; // important comment
            default: size = -1; break; // everything else
        }
        Console.WriteLine(size);
    }

    static string Whatever() => throw new NotImplementedException();
}
```

expected output:

``` c#
        var size = input switch
        {
            "abc" => 12, // because magic
            "def" => 42, // important comment
            _ => -1, // everything else
        };
```

actual output:

``` c#
        var size = input switch
        {
            "abc" => 12,
            "def" => 42,
            _ => -1,
        };
```

Note: I haven't thought through what this should do in the general case where comments could be on multiple lines, but; comments are important - throwing them away seems bad.

**Comment by sharwell** [comment] 2019-09-24 19:24
Duplicate of #36877

**Closed by sharwell** 2019-09-24 19:24 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, help wanted
