### ISSUE TITLE
Problem with using common .editorconfig file (imported in csproj) in Visual Studio 2019 Preview 4

### ISSUE THREAD

**Issue by hugoqribeiro** [dotnet/roslyn#38782] opened 2019-09-20 15:00 UTC
**Version Used**: 

Visual Studio 2019 Preview 4
Microsoft.CodeAnalysis.FxCopAnalyzers v2.9.4

**Steps to Reproduce**:

I want to streamlime code analysis and the respetive rules accross multiple projects and teams.

We used to do that by having a NuGet package that imported analyzers to projects (Microsoft.CodeAnalysis.FxCopAnalyzers and StyleCop.Analyzers) and defined a ruleset to define how each rule was handled by VS (error, warning, etc.).

I have been trying to setup this using a common .editorconfig file instead of the ruleset. The problem is that settings like the following just seem to be ignored when the .editorconfig file is imported from a shared folder.

```
dotnet_diagnostic.CA1062.severity = error
```

For the purpose of testing this, I have a very simple scenario that illustrates the problem.

The .editorconfig file is as follows:

```
[*.cs]
dotnet_diagnostic.CA1062.severity = error
#dotnet_code_quality.null_check_validation_methods = NotNull
```

Now this file is imported in a csproj like this:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <Import Project="..\..\_Shared\Build.props" />
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.4">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
```

Build.props is like this:

```
<Project>
    <PropertyGroup>
    <SkipDefaultEditorConfigAsAdditionalFile>true</SkipDefaultEditorConfigAsAdditionalFile>
    </PropertyGroup>
    <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)\.editorconfig')" >
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\.editorconfig" />
    </ItemGroup>
</Project>
```

**Expected Behavior**:

The following code is supposed to trigger an **error on CA1062** (validation of input):

```
public int Calculate(InputData input)
{
    SmartGuard.NotNull(nameof(input), input);
    if (this.Multiply)
    {
        return input.Value * 2;
    }
    else
    {
        return input.Value + 2;
    }
}
```

**Actual Behavior**:

But the result is a **warning**, which means that `CA1062.severity` is being ignored.

Now, if I change .editorconfig and uncomment the second line:

```
[*.cs]
dotnet_diagnostic.CA1062.severity = error
dotnet_code_quality.null_check_validation_methods = NotNull
```

The error goes way which means that `null_check_validation_methods` is being considered.

Why is that `CA1062.severity` is being ignored?

**Comment by sharwell** [comment] 2019-09-20 15:09
.editorconfig is a file format shared across several different products (https://editorconfig.org). The format is defined as applying to files in the same folder as the .editorconfig file and files in subfolders of that location. It is not possible to apply .editorconfig settings to files located elsewhere.

In other words, .editorconfig only works if you can create a relative path from the .editorconfig to the target source file without using `..`.

/cc @mavasani @agocke

**Comment by hugoqribeiro** [comment] 2019-09-20 17:47
Hi.

How is that so if the second setting is being considered?
Also this doc explicitly states that it can be done: [https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019](link).

No?

**Comment by mavasani** [comment] 2019-09-20 18:02
@hugoqribeiro 

I hope the below note on that page and the note at end of [this section](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#enabling-editorconfig-based-configuration-for-a-project) clarifies this is temporary support which is only applicable to FxCop analyzers package:

```
Note:

The arbitrary shared location of the EditorConfig file described here applies only to configuring FxCop analyzers. For other settings, such as indentation and code style, the EditorConfig file must always be placed in the project folder or a parent folder.
```

**Comment by hugoqribeiro** [comment] 2019-09-20 18:13
I understand that (altough it is not good because most of us use VS in large dev teams where it does not make any sense having different projects applying different coding standards).

Neverthess here I am trying to configure the severity level of an FxCop analyzer rule (CA1062). Is this not “configuring FxCop analyzers”? Am I misunderstanding something?

I’m not messing with tabs or spaces or anything like that.

I have read issues talking about “soft deprecating rulesets”. That can only be done if editorconfig supports the same behaviors in VS (as it already does when the file is “inside the project”).

**Comment by mavasani** [comment] 2019-09-20 18:15
> Neverthess here I am trying to configure the severity level of an FxCop analyzer rule (CA1062). Is this not “configuring FxCop analyzers”? Am I misunderstanding something?

The support listed in https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md and https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019 only applies to configuring analyzer _options_, not the severity.

**Comment by hugoqribeiro** [comment] 2019-09-20 19:10
But that is **only when** the file is imported, right?
Will it be fixed in the near future?

**Comment by mavasani** [comment] 2019-09-28 21:44
> That can only be done if editorconfig supports the same behaviors in VS (as it already does when the file is “inside the project”).

This feature request is already covered in last bullet item for https://github.com/dotnet/roslyn/issues/38042. Marking this issue as a duplicate of that feature request.

**Closed by mavasani** 2019-09-28 21:44 UTC
Labels: Area-IDE, Question
