### ISSUE TITLE
Simply opening .editorconfig file makes significant changes to the file for C# settings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68683] opened 2023-06-19 15:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Simply-opening-editorconfig-file-makes-/10394452)._

---
[severity:It bothers me. A fix would be nice]
1. Create a new C# project.  Add an empty .editorconfig file.
2. Open the .editorconfig file (by default, it opens in a designer)
3. Note that all settings show as coming from Visual Studio Settings in the Location column.
4. Close the file immediately.  The file is dirty so you're prompted to save changes.

Expected:
No prompt, as I haven't changed anything.

Actual:
Click save, then open the file again in the text editor, it has 74(!) lines of settings added.  If I open the file again in the designer, now it shows a bunch of these settings (but not all of them) coming from my .editorconfig file instead of from VS settings.

This is annoying in projects where there is an existing .editorconfig file, as simply opening the file to view the existing settings makes a significant edit to the file, and the editorconfig designer doesn't show what has changed (it just shows the file as dirty, but all settings come from Visual Studio Settings).  You have to close, save, and diff to see the changes that VS is making automatically.

I first noticed this behavior in 17.6.x, but didn't file an issue until now, so it's not a recent regression.

---
#### Feedback Bot on 6/18/2023, 10:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jeanplevesque** [comment] 2023-10-02 13:19
I have the same problem and it's frustrating.
In my case I have an existing .editorconfig file. When I just open it using the Visual Studio UI editor and save without touching anything, multiple lines are changed (about 10 lines are added in various locations).

**Comment by sharwell** [comment] 2024-03-06 17:37
Duplicate of #59325

**Closed by sharwell** 2024-03-06 17:37 UTC
Labels: Area-IDE, Feature - Editor Config UI, Editor Config
