### ISSUE TITLE
C# IntelliSense does not respect newlines in doc comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26503] opened 2018-04-30 08:21 UTC
For any long &quot;summary&quot; comment, hovering over the type/method seems to strip all newlines.
This makes it very difficult to read if you have a long/verbose comment.

Using &quot;para&quot; isn't really much of an option as:
1. It adds 2 newlines (not just 1)
2. I don't want to have to add &quot;para&quot; open and close tags everywhere.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/239537/c-intellisense-does-not-respect-newlines-in-doc-co.html
VSTS ticketId: 605850_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-04-30 12:03
This is normal behavior in XML. Changing the behavior is likely to negatively impact the experience for developers who expect the XML to behave as it currently does. However, we might consider reducing the size of the paragraph-separating space that appears when `<para>` elements are used.

Additional notes:

* Multiple paragraphs should not be appearing in the `<summary>` element. When used, it's typically serving as a workaround for the fact that the `<remarks>` and `<example>` elements are treated as nearly non-existent by the IDE.
* The request to have paragraphs without `<para>` is likely a duplicate of dotnet/csharplang#891 and/or dotnet/csharplang#878.

**Comment by jinujoseph** [comment] 2018-06-19 16:23
Tentatively marking as By Design 
We will taking this for review and will update with final conclusion.

**Comment by sharwell** [comment] 2018-08-13 21:49
Today's design review confirmed that this behavior is **By Design** according to the current definition of the language. Note that it may be possible to implement an analyzer that inserts the `<para>` elements. I don't know of one that's readily available today, but you may be interested in https://github.com/openstacknetsdk/OpenStackNetAnalyzers/pull/18 and/or https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/610 as a starting point.

**Closed by sharwell** 2018-08-13 21:49 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review, Resolution-By Design
