### ISSUE TITLE
[Proposal] Generic Constraint: enum

### ISSUE THREAD

**Issue by whoisj** [dotnet/roslyn#3258] opened 2015-06-02 17:03 UTC
It would be ideal if generics could be written as the following (use-case provided):
```
public static void DefinedEnum<T>(T value, string name)
    where T: enum
{
    if (!Enum.Defined(typeof(T), value))
        throw new ArgumentException("Value is undefined", name);
}
```

**Comment by HaloFour** [comment] 2015-06-02 17:15
Dupe of #262.

**Closed** 2015-06-04 20:28 UTC
Labels: Area-Language Design, Resolution-Duplicate, Verification Not Required
