### ISSUE TITLE
CSharpNavigateTo integration test failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#11622] opened 2016-05-27 21:55 UTC
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/31/

```
14:52:00 Test: CSharpNavigateTo started: 5/27/2016 9:51:47 PM
14:52:00 	Executing action [5/27/2016 9:51:47 PM] StartTarget
14:52:00 Begin Waiting for Apex Communication
14:52:00 	Executing action [5/27/2016 9:51:47 PM] AddProject
14:52:00 	Executing action [5/27/2016 9:51:57 PM] AddItem
14:52:00 	Executing action [5/27/2016 9:51:57 PM] OpenFile
14:52:00 DEBUG: executed DTE command File.OpenFile.
14:52:00 DEBUG: start polling for code window
14:52:00 DEBUG: polling complete
14:52:00 	Executing action [5/27/2016 9:51:57 PM] SetEditorText
14:52:00 	Executing action [5/27/2016 9:51:58 PM] CloseFile
14:52:00 --------------------------------
14:52:00 System.Exception: The text that we thought we were saving isn't what we saved!
14:52:00    at Roslyn.VSHosting.Test.CloseFileAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\Actions\VisualStudio\CloseFileAction.cs:line 60
14:52:00    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
14:52:00    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
14:52:00 ================================
```

**Comment by Pilchie** [comment] 2016-06-02 16:53
Tag @jasonmalinowski - this is your diagnostic about the text not saving correctly!

**Comment by jasonmalinowski** [comment] 2016-06-27 17:48
Duplicate of #11622.

**Comment by jasonmalinowski** [comment] 2016-07-05 18:23
We're tracking this issue over at #9602.

**Closed by jasonmalinowski** 2016-07-05 18:23 UTC
Labels: Area-IDE, Flaky
