### ISSUE TITLE
Quick Fix for inconsistent accessibility diagnostics

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#16632] opened 2017-01-19 21:49 UTC
This should be recursively applied to CS0050 through CS0061 diagnostics.

Could be generalized as "Change accessibility" refactorings.

**Comment by Pilchie** [comment] 2017-02-16 18:50
Actually, this is a duplicate of #10337.

**Comment by Pilchie** [comment] 2017-02-16 18:50
Actually, no this is slightly different

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:08
Closing as we have decided this is not something we want to invest in.

**Closed by CyrusNajmabadi** 2024-10-22 19:08 UTC
Labels: Area-IDE, Feature Request
