### ISSUE TITLE
Exception when add #nulable enable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32483] opened 2019-01-15 16:51 UTC
Visual studio throws an exception when adding &quot;#nullable enable&quot; directive. Here is exception and stack trace.

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.Formatting.FormattingDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Unexpected false'.	ConsoleApp7		1	Active	Analyzer 'Microsoft.CodeAnalysis.Formatting.FormattingDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ConsoleApp7
SyntaxTree: C:\Users\Libor\source\repos\ConsoleApp7\ConsoleApp7\Program.cs

System.InvalidOperationException: Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Analyze(SyntaxTriviaList list, AnalysisResult&amp; result)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Leading(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.CreateLeadingTrivia(SyntaxToken token)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetOriginalTriviaData(TokenData token1, TokenData token2)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetColumn(TokenData tokenData, Func`3 triviaDataGetter)
   at Microsoft.CodeAnalysis.Formatting.FormattingContext.AddAnchorIndentationOperation(AnchorIndentationOperation operation)
   at Roslyn.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source, Action`1 action)
   at Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.&lt;&gt;c__DisplayClass14_0.&lt;FormatAsync&gt;b__0(Task`1 task)
   at Microsoft.CodeAnalysis.Formatting.TaskExecutor.SynchronousExecutor.ContinueWith[T1,T2](Task`1 previousTask, Func`2 nextAction, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.&lt;FormatAsync&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.&lt;FormatIndividuallyAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Formatting.Formatter.&lt;GetFormattedTextChangesAsync&gt;d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.Formatter.GetFormattedTextChanges(SyntaxNode node, Workspace workspace, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeStyle.FormattingAnalyzerHelper.AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context, DiagnosticDescriptor descriptor, Workspace workspace, OptionSet options)
   at Microsoft.CodeAnalysis.Formatting.FormattingDiagnosticAnalyzer.AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.&lt;&gt;c.&lt;ExecuteSyntaxTreeActionsCore&gt;b__49_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/411190/exception-when-add-nulable-enable.html
VSTS ticketId: 753485_
_These are the original issue comments:_

David Lowndes on 12/18/2018, 05:21 AM (28 days ago): I've got this with every project where I've tried building as C# 8 with nullable reference types enabled.
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-01-15 17:51
@ryzngard dupe of https://github.com/dotnet/roslyn/issues/32080 ?

**Comment by ryzngard** [comment] 2019-01-15 18:35
Yup same issue. The user reporting is on version `16.0.28408.50`, when P2 hits it should be fixed.

**Closed by ryzngard** 2019-01-15 18:35 UTC
Labels: Area-IDE, Bug, Developer Community
