### ISSUE TITLE
Status/plan for support of NuGet packages (project.json) in Workspace API

### ISSUE THREAD

**Issue by zuraff** [dotnet/roslyn#6068] opened 2015-10-16 13:51 UTC
Hi,
can you please tell me what is the current status/future plans for support of parsing project.json files by Workspace API ? Are NuGet dependencies stored in project.json file resolved ? Is the API capable to tell which *.dlls are effectively referenced by a project through NuGet dependencies ?

Thanks

**Comment by Pilchie** [comment] 2015-10-22 03:46
There is no status or plan as of now.  Inside Visual Studio, these are added to the VisualStudioWorkspace using the existing shims.  In other hosts (for example OmniSharp) people have their own implementations of workspace that do support DNX more directly.

See also #3824, which I'm going to mark this a duplicate of.

**Closed by Pilchie** 2015-10-22 03:46 UTC
Labels: Area-IDE, Question
