### ISSUE TITLE
Option to make using directive global.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63956] opened 2022-09-12 20:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-to-make-using-directive-global/10110952)._

---
With the introduction of [global using directives](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives) in C#10 I think it would be useful if there was an option for the editor to detect using directives that are present in every, or almost every, class and offer the following options:
1. Make one directive `global` and remove the others
2. Create a new file `GlobalUsings`, add the directive there with the `global` modifier and remove the directive from the other files.

I think this can be a code style rule, so it can be set to either `Information`, `Warning`, `Error` or `Refactor only` so developers can see it suggested by the editor or as a "Quick Action" or an option in the right-click menu, like "Remove and sort usings".

In my opinion the code style rule would be most efficient as it could volunteer the information that a certain `using` is appearing in every file, which I don't think many people would notice by themselves and thus won't take action on their own using "Quick Actions" or the right-click menu.

---
#### Feedback Bot on 8/3/2022, 08:05 PM: 

(private comment, text removed)

**Comment by arkalyanms** [comment] 2022-09-13 18:02
@sharwell Did this already come up in the design meeting?

**Comment by sharwell** [comment] 2022-09-14 13:20
Duplicate of #55895

**Closed by sharwell** 2022-09-14 13:20 UTC
Labels: Area-IDE, untriaged
