### ISSUE TITLE
ObjectBinderSnapshot Index out of bounds if Deserialization is the first operation

### ISSUE THREAD

**Issue by RaicuRobert** [dotnet/roslyn#27226] opened 2018-05-29 19:11 UTC
**Version Used**: 
 2.1.300-preview2-008324
**Steps to Reproduce**:

Run this as a test alone, sorry that it looks messy but i have no experience in testing and the code area seems to have a problem with my array of bytes.
Please run the test alone so the error can occur. If you use any SyntaxTree before it will not cause an error.  Nothing that affects the ObjectBinder can run before if you want to reproduce it.
```
[Fact]
        public void DeserializeSyntaxNode()
        {
            /* This test must be ran ALONE to fail!
                eqivalent to 
                var x = @"using System;";
                var tree = CSharpSyntaxTree.ParseText(x);
                var root = tree.GetRoot();
                var bytes;
                using (MemoryStream ms = new MemoryStream())
                {
                    root.SerializeTo(ms);
                    bytes = ms.ToArray();
                }
                It is important that we do not use the CSharpSyntaxTree as it populates the ObjectBinder.
             */
           byte[] bytes = new byte[]{ 170,9,2,7,0,0,0,136,34,0,2,6,0,0,0,139,34,2,3,0,0,0,181,32,0,2,0,0,0,0,92,33,6,1,32,0,0,2,5,0,0,0,168,33,2,4,0,0,0,60,33,6,6,83,121,115,116,101,109,2,2,0,0,0,20,32,0,0,2,2,0,0,0,48,33};
            
            using (MemoryStream ms = new MemoryStream(bytes))
            {
                ms.Seek(0, SeekOrigin.Begin);
                CSharpSyntaxNode.DeserializeFrom(ms);
            }
        }
```

**Expected Behavior**:
A SyntaxNode being returned by CSharpSyntaxNode.DeserializeFrom.
**Actual Behavior**:
If you debug the test case you will see that without the SyntaxTree the ObjectBinder does not get populated.
If we run CSharpSyntaxNode.DeserializeFrom we will see that it creates a ObjectReader which in the constructor  does this `_binderSnapshot = ObjectBinder.GetSnapshot();`. The problem is that if our first operation is deserialization and we did not use any SyntaxTree before, the ObjectBinder has no registered type readers. This means the ObjectBinderSnapshot we have have is empty and when we do something like this later in the code `var typeReader = _binderSnapshot.GetTypeReaderFromId(this.ReadInt32());` at the function ReadObject() of ObjectReader it crashes

**Edit 1:** 
Seems that this error might be known and worked around inside the CSharpSyntaxTree as the first property is `internal static readonly SyntaxTree Dummy = new DummySyntaxTree();`. I guess that this would fix the same problem when the first operation would be serialization by populating the ObjectBinder. Sadly i do not have time to investigate any further for now.
![Stack](https://user-images.githubusercontent.com/15961860/40681055-b9937348-6390-11e8-9940-fc2fa3ced973.JPG)

**Comment by svick** [comment] 2018-05-29 20:44
This approach where serialization uses indexes to some not fully deterministic data structure seems very brittle to me. Maybe `SerializeTo` and `DeserializeFrom` are not meant to be used across processes like this?

If that's the case, their documentation should make that clear.

If they are meant to be used across processes, then I think fixing this would require more than just ensuring `ObjectBinder` is populated.

**Comment by RaicuRobert** [comment] 2018-05-29 21:37
I tried something else. Seems that this is not the way you should use it but it's not specified.
I serialized this 
` using System;
namespace xx{
class Ada{}}`
 into a byte array then ran 
`var tree = CSharpSyntaxTree.ParseText("");
            var root = tree.GetRoot();` 
before deserializeing which should populate the ObjectBinder whith the default types. But it threw the same exception. 
I guess that while the the text is parsed also some custom types are created for xx and Ada which cannot be inferred from the byte array.
But then when would be DeserializeFrom be useful when you need the source code for it to work?

**Comment by RaicuRobert** [comment] 2018-05-29 21:43
@jasonmalinowski Do you know someone who could shed some light on this?

**Comment by RaicuRobert** [comment] 2018-05-30 12:11
Upon further inspection it seem that this would be the case. The ObjectBinder is not populated with the needed type readers. 
If i start with deserializing the bytes for `using System; namespace xx{ class Ada{}}` it will cause the exception. 
BUT!
If i fist serialize a unrelated piece of code `using System; namespace ans{ class acls{}}` then deserialize `using System; namespace xx{ class Ada{}}` it works just fine.

**Comment by svick** [comment] 2018-05-30 12:31
It's not about whether it's populated, it's also about *how* it's populated. Consider this modification of your test:

```c#
byte[] bytes = new byte[]{ 170,9,2,7,0,0,0,136,34,0,2,6,0,0,0,139,34,2,3,0,0,0,181,32,0,2,0,0,0,0,92,33,6,1,32,0,0,2,5,0,0,0,168,33,2,4,0,0,0,60,33,6,6,83,121,115,116,101,109,2,2,0,0,0,20,32,0,0,2,2,0,0,0,48,33};

using (MemoryStream ms = new MemoryStream(bytes))
{
    CSharpSyntaxTree.ParseText("class A {}");

    CSharpSyntaxNode.DeserializeFrom(ms);
}
```

When you run this code, it throws:

```
Unhandled Exception: System.InvalidOperationException: Unexpected value 'Object' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind kind) in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 323
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxIdentifier..ctor(ObjectReader reader) in /_/src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxToken.SyntaxIdentifier.cs:line 34
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxIdentifier.<>c.<.cctor>b__0_0(ObjectReader r) in /_/src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxToken.SyntaxIdentifier.cs:line 14
   at Roslyn.Utilities.ObjectReader.ReadObject() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 606
   at Roslyn.Utilities.ObjectReader.ReadValue() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 168
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax..ctor(ObjectReader reader) in /_/src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs:line 20595
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax.<>c.<.cctor>b__45_0(ObjectReader r) in /_/src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs:line 20663
   at Roslyn.Utilities.ObjectReader.ReadObject() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 606
   at Roslyn.Utilities.ObjectReader.ReadValue() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 168
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax..ctor(ObjectReader reader) in /_/src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs:line 18402
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax.<>c.<.cctor>b__27_0(ObjectReader r) in /_/src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs:line 18440
   at Roslyn.Utilities.ObjectReader.ReadObject() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 606
   at Roslyn.Utilities.ObjectReader.ReadValue() in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 168
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.DeserializeFrom(Stream stream, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs:line 202
   at Program.Main() in C:\code\tmp\coreapp\Program.cs:line 22
```

To me, this shows that it's trying to deserialize it wrong, because `ObjectBinder` was populated in different order.

**Comment by RaicuRobert** [comment] 2018-05-30 12:43
Wouldn't this be caused because the first thing in the byte array is a namespace and no namespace type reader is registered by parsing `class A {}`?

**Comment by RaicuRobert** [comment] 2018-06-03 04:15
@tmat Can anyone help?

**Comment by jasonmalinowski** [comment] 2018-06-06 02:13
I think @heejaechang might be the expert here. I don't know much of anything about how this works.

**Comment by heejaechang** [comment] 2018-06-06 02:30
this is by design. I can't remember all details on top of my head (it has been so long since I looked this area). but tree requires readers saved in memory to de-serialize stream back to tree.

this also means, we can't serialize tree in 1 appdomain and de-serialize in another app domain. also we can't serialize tree and then deserialize it from other process.

I am +1 on removing this restrictions. 

anyway, I believe it is done this way by design. tagging @mattwar who made this change.

**Comment by RaicuRobert** [comment] 2018-06-06 13:37
Wouldn't this be fixable by loading the corresponding readers into memory based on their byte representation? Like when it checks using a byte for a type reader and then accesses it instead of throwing an error it could do a null check and load the corresponding one. I could try to come up with a fix but sometime next month as i have my bachelor's thesis to finish now. Is there a class or enum where the bytes representations are stored for the corresponding types?

**Comment by heejaechang** [comment] 2018-06-06 17:40
let me tag @dotnet/roslyn-compiler or @jcouv since the code is actually in compiler side. probably they are best person on how to remove the restriction.

**Comment by kalberes** [comment] 2018-10-26 12:05
@jcouv 
Any news when this is going to be fixed. We in Dynamics Business Central would like to use this feature very much where we transform from our own AL compilation output to c#  AST bytes (instead of c# text), store them and create .net assemblies out of them.

**Comment by jcouv** [comment] 2018-10-26 14:01
Tagging @jaredpar while I'm out of office

**Comment by jaredpar** [comment] 2018-10-26 16:58
@gafter can you comment on this?

**Comment by kalberes** [comment] 2018-12-27 13:57
@gafter would you please mind  a comment here. Will this be fixed? We would still like to use very much the possibility of having (not only in memory) serialized AST-s.

**Comment by CyrusNajmabadi** [comment] 2023-02-09 21:41
Closing out as this is by design.  We explicitly do *not* support deserialization of these outside of hte process that serialized them.   It legit cannot work (especially as we do things like write down indices of the particular serializers (which will depend on hte order of the objects we serialize)).  This is just a core part of the design here.

**Closed by CyrusNajmabadi** 2023-02-09 21:41 UTC
Labels: Bug, Area-IDE
