### ISSUE TITLE
[Feature] Yield return sub-sequence, yield return multiple items, yield SelectMany

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#7630] opened 2015-12-20 22:42 UTC
It feels intuitive to have a simple construct that will allow yielding a sub-sequence of items rather than one   item at a time. Currently this involves writing a loop manually or using LINQ.

This is something that people were asking for in past: http://stackoverflow.com/questions/3851997/yield-return-many

Typical suggested syntax (copied from link above):

```csharp
public static IEnumerable<T> PreorderTraversal<T>(this BinaryTree<T> root)
{
    if (root == null) yield break;
    yield return root.Item;
    yield foreach root.Left.PreorderTraversal();
    yield foreach root.Right.PreorderTraversal();
}
```

F# knows this as ```yield!``` apparently: http://theburningmonk.com/2011/09/fsharp-yield-vs-yield

**Comment by dsaf** [comment] 2015-12-20 22:51
I guess there could be an ```async``` version too #261.

**Comment by alrz** [comment] 2015-12-21 00:57
Right here #5018, #15.

**Comment by gafter** [comment] 2015-12-21 05:09
Duplicate of #15.

**Closed by gafter** 2015-12-21 05:09 UTC
