### ISSUE TITLE
Code Fix for IDE0067 makes code not compile (sometimes?)

### ISSUE THREAD

**Issue by Eilon** [dotnet/roslyn#36480] opened 2019-06-14 22:37 UTC
**Version Used**: 
VS2019 16.2.0 Preview 2.0
.NET Core (tried with 2.1 and 3.0 Preview 5)

**Steps to Reproduce**:

1. Create new .NET Core project (console, class lib, etc.)
2. Add this code:
```c#
using System;

class Program
{
    static void Main()
    {
        var x = new FooDisposable();

        var y = x.GetSomething();

        Console.WriteLine(y);
    }

    public class FooDisposable : IDisposable
    {
        public int GetSomething() => 1;
        public void Dispose() => throw new NotImplementedException();
    }
}
```
3. Accept the code fix suggestion to wrap `x` in a `using` statement for the `new FooDisposable()` expression:
![image](https://user-images.githubusercontent.com/202643/59542216-8c924180-8eb9-11e9-8e65-3468b0a1b030.png)
4. It generates invalid code:
```c#
        using (var x = new FooDisposable())
        {
            var y = x.GetSomething();
        }

        Console.WriteLine(y); // 'y' is no longer in scope here
```

NOTE: For some reason I can't always get this code fix to show up. Sometimes it shows up, sometimes it doesn't, with the exact same code. If I undo/redo/edit the code I can toggle it, but not consistently.

**Expected Behavior**:
I thought code fixes should generate working code - at least in relatively trivial cases? E.g.:
```c#
        using (var x = new FooDisposable())
        {
            var y = x.GetSomething();
            Console.WriteLine(y); // 'y' is still in scope
        }
```

**Actual Behavior**:
Invalid code is generated

**Comment by CyrusNajmabadi** [comment] 2019-06-15 15:34
tagging @jnm2

**Comment by jnm2** [comment] 2019-06-15 17:25
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/35237 which is assigned to @JoeRobich for 16.2.

**Comment by Eilon** [comment] 2019-06-16 02:49
Ah yes it does look the same as https://github.com/dotnet/roslyn/issues/35237. I searched for `IDE0067` and didn't find it.

**Comment by jinujoseph** [comment] 2019-06-19 19:31
Duplicate of #35237

**Closed by jinujoseph** 2019-06-19 19:31 UTC
