### ISSUE TITLE
NRE in MisplacedUsingDirectivesDiagnosticAnalyzer 

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#41521] opened 2020-02-09 00:20 UTC
**Version Used**: 3.4.0 nupkg

I believe `options` needs to be checked for null before the `options.GetOption` call on line 91:

https://github.com/dotnet/roslyn/blob/82f2e2541478e239dc4b04f231e90dc2b3dcb422/src/Features/CSharp/Portable/MisplacedUsingDirectives/MisplacedUsingDirectivesDiagnosticAnalyzer.cs#L88-L92

Based on this stack trace:

```
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.<GetPreferredPlacementOptionAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.GetPreferredPlacementOptionAsync(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.AnalyzeCompilationUnitNode(SyntaxNodeAnalysisContext context)
```

And the fact that `context.Node` and `context.Options` were not null:

![image](https://user-images.githubusercontent.com/8040367/74094014-59d03580-4aa8-11ea-8b98-f70aef63431d.png)

**Comment by CyrusNajmabadi** [comment] 2020-02-09 00:25
How did you run into this?  All documents should have options during normal workspace processing.

**Comment by jnm2** [comment] 2020-02-09 00:51
I used the `Compilation.WithAnalyzers` extension method:

```cs
var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);

var compilationWithAnalyzers = semanticModel.Compilation.WithAnalyzers(
    analyzers,
    document.Project.AnalyzerOptions,
    cancellationToken);

var (syntaxDiagnostics, semanticDiagnostics) = await (
    compilationWithAnalyzers.GetAnalyzerSyntaxDiagnosticsAsync(semanticModel.SyntaxTree, cancellationToken),
    compilationWithAnalyzers.GetAnalyzerSemanticDiagnosticsAsync(semanticModel, filterSpan, cancellationToken)
).ConfigureAwait(false);
```

**Comment by jnm2** [comment] 2020-02-09 00:54
The document and project were obtained using `originalSolution`:

```cs
MSBuildLocator.RegisterDefaults();

using var workspace = MSBuildWorkspace.Create();

var originalSolution = await workspace.OpenSolutionAsync(solutionPath);
```

**Comment by jnm2** [comment] 2020-02-09 01:18
I'm paring down a repro.

**Comment by jnm2** [comment] 2020-02-09 01:24
Self-contained repro:

##### Program.cs

<details>

```cs
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.MSBuild;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

public static class Program
{
    public static async Task Main()
    {
        MSBuildLocator.RegisterDefaults();

        using (var workspace = MSBuildWorkspace.Create())
        {
            var solution = await workspace.OpenSolutionAsync(@"C:\Users\Joseph\Source\Repos\RoslynRepro\RoslynRepro.sln");
            var project = solution.Projects.First();
            var document = project.Documents.First();

            var csharpFeaturesAssembly = Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features");
            var csharpFeaturesAnalyzerReference = new AnalyzerFileReference(
                csharpFeaturesAssembly.Location,
                new SingleAnalyzerAssemblyLoader(csharpFeaturesAssembly));

            var analyzers = csharpFeaturesAnalyzerReference.GetAnalyzers(project.Language)
                .Where(instance => instance.GetType().Name == "MisplacedUsingDirectivesDiagnosticAnalyzer")
                .ToImmutableArray();

            var semanticModel = await document.GetSemanticModelAsync();

            var compilationWithAnalyzers = semanticModel.Compilation.WithAnalyzers(
                analyzers,
                new CompilationWithAnalyzersOptions(
                    project.AnalyzerOptions,
                    onAnalyzerException: (exception, analyzer, diagnostic) => Console.WriteLine(exception.ToString()),
                    concurrentAnalysis: true,
                    logAnalyzerExecutionTime: false));

            await compilationWithAnalyzers.GetAnalyzerSemanticDiagnosticsAsync(semanticModel, filterSpan: null, CancellationToken.None);
        }
    }

    private sealed class SingleAnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
    {
        private readonly Assembly assembly;

        public SingleAnalyzerAssemblyLoader(Assembly assembly)
        {
            this.assembly = assembly;
        }

        public void AddDependencyLocation(string fullPath)
        {
        }

        public Assembly LoadFromPath(string fullPath)
        {
            if (!string.Equals(fullPath, assembly.Location, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException($"This assembly loader must only load '{assembly.Location}'.");

            return assembly;
        }
    }
}
```


##### Repro.csproj

<details>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.6" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.4.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="3.4.0" />
  </ItemGroup>

</Project>
```

**Comment by jnm2** [comment] 2020-02-09 01:42
Also, compare this other analyzer which I happened to notice is doing the null check:

https://github.com/dotnet/roslyn/blob/5858196e0196bcfaf9887e28efdfd500a9fda122/src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs#L216-L220

**Comment by sharwell** [comment] 2020-02-12 20:44
Duplicate of #41523

**Closed by sharwell** 2020-02-12 20:44 UTC

**Comment by jnm2** [comment] 2020-02-12 23:20
@sharwell Why should other analyzers be checking for null and this analyzer not be consistent with that?
