### ISSUE TITLE
C# crash on 'in' keyword with (omitted) optional method argument

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/roslyn#29486] opened 2018-08-24 03:58 UTC
`Error MSB6006: "csc.exe" exited with code -2146232797`.

Self explanatory; see snippet.

**Roslyn 2.9.0.63208  C# 7.3** (2.9.0-beta8-63208-01, `958f2354`)
VisualStudio.15.Release/15.8.1+28010.2003 

    /// Roslyn crash on C# 'in' keyword with optional method argument
    /// Error MSB6006: "csc.exe" exited with code -2146232797.
    /// .NET 4.7.2  x64
    /// CSharp 'latest' mode (7.3)
    /// Roslyn compiler version 2.9.0.63208 (958f2354)
    
    using System;
    
    static class Program
    {
        static void Main()
        {
            var rg = new Object[1];
            M(rg, in rg[0]);
        }
        //        ^-- crash requires both 'in'
        //                 and optional args ---v
        static void M<T>(T[] rg, in T t, int i = 0) { }
    }

----

<pre>
DEBUG BUILD OUTPUT --
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\csc.exe
    /noconfig          /unsafe+               /nowarn:1701,1702,2008  /nostdlib+
    /platform:AnyCPU   /errorreport:prompt    /warn:4                 /define:DEBUG;TRACE
    /errorendlocation  /preferreduilang:en-US /highentropyva+         /debug+
    /debug:full        /filealign:512         /optimize-              /subsystemversion:6.00
    /target:exe       /utf8output             /deterministic+         /langversion:latest
    /ruleset: ...
    /reference:"...\v4.7.2\mscorlib.dll"
    /reference:"...\v4.7.2\System.Core.dll"
    /reference:"...\v4.7.2\System.dll"
    /out:obj\Debug\ConsoleApp25.exe
        Program.cs
        Properties\AssemblyInfo.cs
        "C:\Users\glenn-actual\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
        obj\Debug\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs
        obj\Debug\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
        obj\Debug\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs

Using shared compilation with compiler from directory:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn
Microsoft (R) Visual C# Compiler version 2.9.0.63208 (958f2354)
Copyright (C) Microsoft Corporation. All rights reserved.

...\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5):
error MSB6006: "csc.exe" exited with code -2146232797.
Done executing task "Csc" -- FAILED.
</pre>

**Notes:**
 - No crash if a value is supplied for the optional argument.
 - No crash if the method has no optional argument.
 - No crash if the `in` keyword is omitted at the ***callsite***.
 - No crash if the method argument (and thus callsite) are not designated with `in`.

**Comment by glenn-slayden** [comment] 2018-08-24 04:03
**_Simplified_**: Generic static class (shown above) is not required do demonstrate this problem:

	using System;

	static class Program
	{
		static void Main()
		{
			var rg = new Object[1];
			M(rg, in rg[0]);
		}
		static void M(Object[] rg, in Object t, int i = 0) { }
	}

**Comment by jhinder** [comment] 2018-08-24 08:41
This is a duplicate of #29371.

To get a call stack when the compiler crashes, you can build your project on the command line (`dotnet build`).

**Comment by glenn-slayden** [comment] 2018-08-24 17:52
Further simplification. Crash:

    static void Main()
    {
        var rg = new Object[1];
        M(in rg[0]);    // or, also crashes without published 'rg':  M(in (new Object[1])[0]);
    }
    static void M(in Object t, int i = 0) { }

Also crashes:

    static Object x;
    static void Main() => M(in x);
    static void M(in Object t, int i = 0) { }


No crash:

    static void Main()
    {
        var y = default(Object);
        M(in y);
    }
    static void M(in Object t, int i = 0) { }

As noted by @jhinder, this _does_ seem to implicate lowering (at least to my layperson understanding), since the difference in these contrasts relates to whether the 'in' ref is published on the callsite frame or not. In the first two examples, neither any array element of `rg` nor static `x` has frame instantiation, whereas in the last example, `y` does.

**Comment by jaredpar** [comment] 2018-08-26 20:51
This looks like a dupe of the `in` bug that @agocke is working on. Will let him verify.

**Comment by jaredpar** [comment] 2018-08-27 15:05
@glenn-slayden there are actually a couple of `in` bugs here, including #29371 and one filed internally. @agocke is leading the investigation though and letting him dupe them out if it's an overlap.

**Comment by agocke** [comment] 2018-08-30 06:58
Yeah, this is a dup of https://github.com/dotnet/roslyn/issues/29371. The root cause of this bug is that we have a helper that's used in a lot of places that wasn't updated to handle all the cases of the `in` modifier, so there are a lot of ways this bug can show up. The fix should address all of them at once, so I'm going to close this one as a duplicate.

**Closed by agocke** 2018-08-30 06:58 UTC
Labels: Area-Compilers, Bug
