### ISSUE TITLE
Quick Actions and Refactorings should be diabled for code with the GenereatedCode Attribute.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40307] opened 2019-12-11 22:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/832003/quick-actions-and-refactorings-should-be-diabled-f.html)._

---
<p>VS2017: I generate a data access partial class. Every time I use Quick Actions and Refactoring to create a method stub, it places the method stub in the generated partial class even though this is clearly marked GeneratedCode. 1. Don't do this. Solution 2. Put the new stub in another partial class which is not marked with the CodeGenerated attribute. 3. If no partial class is available then offer to create it, or refuse the action. 4. Offer a choice of location if more than one partial class is available. </p>

---
#### Michael Heath on 11/23/2019, 03:39 PM: 

<p>Thank you!</p>

#### Visual Studio Feedback System on 11/25/2019, 01:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 18:50
Closing out as by design.  Particular actions/refactorings are supposed to check for this.  We can fix those on a case by case basis if reported.

**Closed by CyrusNajmabadi** 2024-10-21 18:50 UTC
Labels: Bug, Area-IDE, Developer Community, Need Design Review
