### ISSUE TITLE
Certain intermixes of braceless and braced usings seems to result in unbalanced try/finally sequence points

### ISSUE THREAD

**Issue by bartonjs** [dotnet/roslyn#61119] opened 2022-05-03 23:08 UTC
**Version Used**: Sharplab.io's target of `C# Next: Attributes on local functions` (because `main` doesn't load)

**Steps to Reproduce**:

[Sample in sharplab.io](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBsD2BjK7VhwB22MAlpkarDAmcHDCgDQwhnrMAmIA1AD4ABAEwBGALAAoQQGYABMmjoIXOSLkB1OkwCeckHICSAETLIADpmRRgyqQG8pc53PN0AbrAhrRABjkA+kRQALYQANxOLlHOspraEDoAFADKtGREAOZywWEAlDFyjpIupYG53gC8OaERhQC+hYVxggAscqYWVhBJBSUuxWUugqIAnElBtXmR/c6NkvNSLcJyAMJFzcLChYNDav5aZLpyUHLVRBAA7vFHiUkARFD304WlggcJesBnOVc3ug9gM8Zns5K9hv4kodjtgfhdrtC7vdsM8+qDdqDYmMHgBRdwQBA6GAACwymQA5Mg5OgyPiAITA8FzBpSepAA==)

```C#
using System;
public sealed class Writey : IDisposable
{
    private string _name;
    
    public Writey(String name)
    {
        _name = name;
    }
    
    public void Dispose()
    {
        Console.WriteLine(_name);
    }
}

public class C {
    public static void Main()
    {
        using Writey a = new Writey("a");
        using Writey b = new Writey("b");
        
        using (Writey c = new Writey("c"))
        {
            Console.WriteLine("Everything's live!");
        }
    }
}
```

Switch sharplab to the Run tab:

**Expected Behavior**:  The program runs, and prints "Everything's live! / c / b / a"

**Actual Behavior**:  InvalidProgramException

Looking at the emitted IL, and comparing to making the "b" block use a braced using (so one braceless followed by two braced) shows that the sequencing on the leave.s instructions changes.  The two braceless followed by one braced appears to try to exit past "b"s finally block.

```msil
// Methods
    .method public hidebysig static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2070
        // Code size 85 (0x55)
        .maxstack 1
        .locals init (
            [0] class Writey,
            [1] class Writey,
            [2] class Writey
        )

        IL_0000: nop
        IL_0001: ldstr "a"
        IL_0006: newobj instance void Writey::.ctor(string)
        IL_000b: stloc.0
        .try
        {
            IL_000c: ldstr "b"
            IL_0011: newobj instance void Writey::.ctor(string)
            IL_0016: stloc.1
            .try
            {
                IL_0017: ldstr "c"
                IL_001c: newobj instance void Writey::.ctor(string)
                IL_0021: stloc.2
                .try
                {
                    IL_0022: nop
                    IL_0023: ldstr "Everything's live!"
                    IL_0028: call void [System.Console]System.Console::WriteLine(string)
                    IL_002d: nop
                    IL_002e: nop
                    IL_002f: leave.s IL_003c
                } // end .try
                finally
                {
                    // sequence point: hidden
                    IL_0031: ldloc.2
                    IL_0032: brfalse.s IL_003b

                    IL_0034: ldloc.2
                    IL_0035: callvirt instance void [System.Private.CoreLib]System.IDisposable::Dispose()
                    IL_003a: nop

                    // sequence point: hidden
                    IL_003b: endfinally
                } // end handler

                IL_003c: leave.s IL_0054
            } // end .try
            finally
            {
                // sequence point: hidden
                IL_003e: ldloc.1
                IL_003f: brfalse.s IL_0048

                IL_0041: ldloc.1
                IL_0042: callvirt instance void [System.Private.CoreLib]System.IDisposable::Dispose()
                IL_0047: nop

                // sequence point: hidden
                IL_0048: endfinally
            } // end handler
        } // end .try
        finally
        {
            // sequence point: hidden
            IL_0049: ldloc.0
            IL_004a: brfalse.s IL_0053

            IL_004c: ldloc.0
            IL_004d: callvirt instance void [System.Private.CoreLib]System.IDisposable::Dispose()
            IL_0052: nop

            // sequence point: hidden
            IL_0053: endfinally
        } // end handler

        IL_0054: ret
    } // end of method C::Main
```

Note that IL_002f goes to IL_003c (an instruction right after the finally) but IL_003c has a `leave.s` targeting IL_0054 (the exit `ret`), instead of a location after the next finally.  Changing "b" to a braced using makes the cascade correct.

---

Very recent builds of the compiler may be doing something different... I was initially helping investigate something with this code pattern when it looked like the call to `b.Dispose()` was merely being skipped (and changing it to a braced using fixed it).

**Comment by 333fred** [comment] 2022-06-01 20:47
@bartonjs I cannot reproduce this issue outside of sharplab, which usually means that it's a bug with the IL editing that sharplab adds for various display features (cc @ashmind). On my machine, code runs without an issue. I also see different IL generated for this test:

```il
{
  // Code size       76 (0x4c)
  .maxstack  1
  .locals init (Writey V_0, //a
                Writey V_1, //b
                Writey V_2) //c
  IL_0000:  ldstr      ""a""
  IL_0005:  newobj     ""Writey..ctor(string)""
  IL_000a:  stloc.0
  .try
  {
    IL_000b:  ldstr      ""b""
    IL_0010:  newobj     ""Writey..ctor(string)""
    IL_0015:  stloc.1
    .try
    {
      IL_0016:  ldstr      ""c""
      IL_001b:  newobj     ""Writey..ctor(string)""
      IL_0020:  stloc.2
      .try
      {
        IL_0021:  ldstr      ""Everything's live!""
        IL_0026:  call       ""void System.Console.WriteLine(string)""
        IL_002b:  leave.s    IL_004b
      }
      finally
      {
        IL_002d:  ldloc.2
        IL_002e:  brfalse.s  IL_0036
        IL_0030:  ldloc.2
        IL_0031:  callvirt   ""void System.IDisposable.Dispose()""
        IL_0036:  endfinally
      }
    }
    finally
    {
      IL_0037:  ldloc.1
      IL_0038:  brfalse.s  IL_0040
      IL_003a:  ldloc.1
      IL_003b:  callvirt   ""void System.IDisposable.Dispose()""
      IL_0040:  endfinally
    }
  }
  finally
  {
    IL_0041:  ldloc.0
    IL_0042:  brfalse.s  IL_004a
    IL_0044:  ldloc.0
    IL_0045:  callvirt   ""void System.IDisposable.Dispose()""
    IL_004a:  endfinally
  }
  IL_004b:  ret
}
```

**Comment by ashmind** [comment] 2022-06-06 06:03
Thanks for reporting, this is now fixed (on SharpLab side). Note that Roslyn branches don't immediately get the latest code, so the error might persist in `main` and other branches for a few days.

**Comment by 333fred** [comment] 2022-06-16 21:30
@carlossanlop I'm told you were the original reporter of the bug. Do you have more context from the original repro?

**Comment by jaredpar** [comment] 2022-06-24 20:34
Closing. Can re-open if we get a stable repro.

**Closed by jaredpar** 2022-06-24 20:34 UTC
Labels: Bug, Area-Compilers, Need More Info
