### ISSUE TITLE
Analyzer called twice with same RecordDeclaration SyntaxNode

### ISSUE THREAD

**Issue by sid-6581** [dotnet/roslyn#50989] opened 2021-02-03 22:49 UTC
**Version Used**: 

VS 16.8.4

**Steps to Reproduce**:

Create an analyzer from the VS analyzer template and update NuGet packages. In the test project, set the reference assembly used by the tests to Net50 for record support.

Use the following analyzer code:

```cs
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class TestAnalyzerAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor Rule = new DiagnosticDescriptor("TT0001", "Test", "Test", "Test", DiagnosticSeverity.Warning, true, "Test");
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Rule);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxNodeAction(AnalyzeSyntaxNode, SyntaxKind.RecordDeclaration);
    }

    private static void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
    {
        var record = (RecordDeclarationSyntax) context.Node;
        context.ReportDiagnostic(Diagnostic.Create(Rule, record.GetLocation()));
    }
}
```

And the following unit test:

```cs
[TestMethod]
public async Task TestMethod1()
{
    var test = @"public record A(int X, int Y);";
    var expected = Verify.Diagnostic().WithLocation(1, 1);
    await Verify.VerifyAnalyzerAsync(test, expected);
}
```

**Expected Behavior**:

One diagnostic is emitted for the record declaration.

**Actual Behavior**:

`AnalyzeSyntaxNode` is called twice for the same `RecordDeclaration` node, resulting in the unit test failing and reporting two identical diagnostics:

```
Diagnostics:
// /0/Test0.cs(1,1): warning TT0001: Test
VerifyCS.Diagnostic().WithSpan(1, 1, 1, 31),
// /0/Test0.cs(1,1): warning TT0001: Test
VerifyCS.Diagnostic().WithSpan(1, 1, 1, 31),
```

Edit: Forgot to mention that this does not happen with any other SyntaxKind I've tried. I have 6 other analyzers with the same basic structure for the analyzer itself and the tests, and none of them give duplicate diagnostics, it has only happened with `RecordDeclaration` so far. This also holds even when the other tests have an identical record declaration in them.

**Comment by mavasani** [comment] 2021-12-24 07:51
Duplicate of https://github.com/dotnet/roslyn/issues/53136

**Closed by mavasani** 2021-12-24 07:51 UTC
Labels: Bug, Area-Analyzers
