### ISSUE TITLE
Better implementation for Abstract Class

### ISSUE THREAD

**Issue by Anjmao** [dotnet/roslyn#7202] opened 2015-12-03 11:17 UTC
Lets say I have this class
```c#
    public abstract class RoslynBase
    {
        public RoslynBase(string name){}

        public abstract void Run();
    }
```
Now I create my class. 
```c#
    public class MyRoslyn : RoslynBase
    {
    }
```
Now I can use roslyn code fix to implement my abstract class.
```c#
    public class MyRoslyn : RoslynBase
    {
        public override void Run()
        {
            throw new NotImplementedException();
        }
    }
```
But wait. Where is constructor for MyRoslyn which is required ?. I think it should be implemented like this.

```c#
    public class MyRoslyn : RoslynBase
    {
        public MyRoslyn(string name): base(name)
        {

        }

        public override void Run()
        {
            throw new NotImplementedException();
        }
    }
```

In our project we have tons of abstract Command classes and I used this feature a lot with resharper.

**Comment by sharwell** [comment] 2015-12-03 14:40
The language requires that th eclass contain a method with th efollowing signature:

```
public override void Run()
```

However, the language does not require any particular constructor.

:thought_balloon: I thought there was a refactoring already supported which added an appropriate chaining constructor. If that isn't the case, it would make sense to create one. You could then use the refactoring for constructors separately from the refactoring for abstract classes.

**Comment by Pilchie** [comment] 2015-12-03 17:35
@CyrusNajmabadi did already add the generate chaining constructor, but we could consider this.  One question that came up was what if the base class has multiple constructors?  SHould we generate chaining versions of all of them?

**Comment by Anjmao** [comment] 2015-12-04 11:02
@Pilchie I think IDE should allow to select constructor which you want to generate, at least this is how it works in resharper and it make sense.

**Comment by CyrusNajmabadi** [comment] 2015-12-04 20:25
Hey guys: GenerateConstructor provides the ability to generate one or all base class constructors today:

![image](https://cloud.githubusercontent.com/assets/4564579/11600480/bf26360e-9a81-11e5-9e8e-5f1cba21ee6a.png)

I agree with @sharwell .  ImplementAbstractClass should probably not be generating constructors.  For one, we don't know which should be generated. It's not always the case that you want all of them.  It's not even the case that you want/need one of them.  i.e. your base class might have:

```c#
public Base(int i) { ... }
```

but your derived may need:

```c#
public Derived(string s): base(...) { }
```

This is different from abstract methods where you are *required* to provide overriding implementations with exact matching signatures in your derived type.

As such, i'm closing this as by design.  We don't want "implement abstract class" doing this, and there is already a really convenient way to generate these with "Generate constructor" if and when you decide you want simple forwarding constructors in your base type.

**Closed by CyrusNajmabadi** 2015-12-04 20:26 UTC
Labels: Area-IDE, Feature Request
