### ISSUE TITLE
Incorrect indentation of list pattern cases in switch expressions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72465] opened 2024-03-08 15:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-indentation-of-list-pattern-ca/10607341)._

---
[severity:It bothers me. A fix would be nice]
Just now, I noticed that list patterns inside switch expressions no longer indent properly.  Instead, the patterns line-up with the opening/closing braces.  Cases which _aren't_ list patterns indent normally, and it seems list patterns appearing after said cases _do_ intent normally.

Simple Example:
```
object input = null;

var output = input switch
{
    "a" => 1,
    1 => 2,
    _ => new int?()
};

object[] input2 = null;

var output2 = input2 switch
{
[1, 2, 3] => 1,
[2, 3] => 2,
    _ when output > 1 => 3,
    [3, 4] => 3,
    _ => new int?()
};
```

Note: if I move the `_ when output > 1` case to the top, all list patterns are indented.  If I move it down, the `[3, 4]` case ceases indenting.  I can manually fix indentation, but as soon as I format the document (which I currently trigger on save), it goes back to how it is pictured in the example.

I primarily interact with list patterns while coding `IMultiValueConverter` implementations, which isn't very often, so I don't know precisely when this started happening, though my gut feeling is it started sometime after updating to 17.9.x.  I was just now on 17.9.1, noticed there was an update to 17.9.2, and ran the update, but it's still a problem.

Note also that I can go back to older converters which have proper indentation, and I've confirmed the format document command will now mangle the indentation.

---
#### Feedback Bot on 3/4/2024, 09:28 PM: 

(private comment, text removed)
#### Daniel P. Lyons on 3/5/2024, 10:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SunnieShine** [comment] 2024-03-09 02:13
#72196

**Comment by sharwell** [comment] 2024-03-11 20:07
Duplicate of #72196

**Closed by sharwell** 2024-03-11 20:07 UTC
Labels: Area-IDE, untriaged
