### ISSUE TITLE
The is pattern matching on constraint type

### ISSUE THREAD

**Issue by Meir017** [dotnet/roslyn#20672] opened 2017-07-06 15:38 UTC
**Version Used**: 
Visual Studio 2017 
Version 15.2 (26430.14) Release

**Steps to Reproduce**:
The following code works:
````csharp
public class Person { }
public class Parent : Person { }
public class Program
{
    public static void Test<TPerson>(TPerson person) where TPerson : Person
    {
        if(person is Parent)
        {
             var parent = person as Parent;
        }
    }
}
````
The following code raises an error `An expression of type TPerson cannot be handled by a pattern of type Parent`:
````csharp
public class Person { }
public class Parent : Person { }
public class Program
{
    public static void Test<TPerson>(TPerson person) where TPerson : Person
    {
        if(person is Parent parent)
        {
        }
    }
}
````

**Comment by sharwell** [comment] 2017-07-06 15:48
This looks like a duplicate of #16195. It is my understanding that the restriction on this use case was removed as part of the work on C# 7.1 (which ships with version 15.3).

**Closed by sharwell** 2017-07-06 15:48 UTC
