### ISSUE TITLE
Extract Interface ... creates file with interface but does not navigate to it.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35531] opened 2019-05-06 17:25 UTC
VSF_TYPE_MARKDOWN## Steps to reproduce
- Create class
- Press Ctrl + '.'.
- Select 'Extract interface... '
- Press Ok in dialog
## Result
- File with interface is created but it is not being navigated to.
## Expected
- Fil with interface is created, opened and selected.

This works in VS 2017 but in VS 2019 it stopped working. Same issue in multiple PCs.

I have found this issue when I was trying to implement custom refactroing by inheriting **CodeActionWithOptions** which returns **DocumentNavigationOperation** and nothing happened.
I have checked roslyn source codes for extract interface which does the same thing I found out that it does not work for 'Extract interface' either.

## Maybe useful information
I have inherited **DocumentNavigationOperation** and debugged **Apply** method. I could see that document id I am using for navigation is different then the one which exists in workspace parameter of method.
For some reason it changed during **ApplyChangesOperation**. Maybe it can help you.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/556922/extract-interface-creates-file-with-interface-but.html
VSTS ticketId: 881201_
_These are the original issue comments:_

Visual Studio Feedback System on 5/4/2019, 08:19 PM (38 hours ago): We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-05-06 18:16
Tentatively marking this as **By Design**. I will update it with details and the conclusion following our team design review.

**Comment by sharwell** [comment] 2019-05-06 21:30
After review, we have marked this as a regression bug. In particular, the following was not an intentional change:

> This works in VS 2017 but in VS 2019 it stopped working

In addition, based on the investigation by the user, it sounds like we may have additional bugs related to the way document IDs are handled when documents are added by a code fix or refactoring.

**Comment by Przemyslaw-W** [comment] 2021-04-01 11:02
any news?

**Comment by ryzngard** [comment] 2022-12-27 23:09
I looked at this today, and found why it broke at least. Looks like document id is not preserved for the newly added document so navigation to that ID would fail. 

@jasonmalinowski any thoughts on a new approach here? AFAIK we can't use the new symbol because the compilation would be different. We could try with symbolkey and resolve I guess...

https://github.com/dotnet/roslyn/blob/887d11b028ce77c377ff37e38fb0886ec14229e9/src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs#L1005-L1007

**Comment by jasonmalinowski** [comment] 2023-01-03 23:40
@ryzngard We could just add that support back -- that was removed as a part of a (very large) refactoring and was intended ot be cleaned up, but just wasn't. But yes, we could re-resolve the symbol and navigate that way.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:57
Closing out due to low feedback and arguably completely fine current behavior.

**Closed by CyrusNajmabadi** 2024-11-06 02:57 UTC
Labels: Bug, Area-IDE, Developer Community, Regression, IDE-CodeStyle, Feature - Extract Interface
