### ISSUE TITLE
Suggestions for setting 'var' preferences code style in C# editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67403] opened 2023-03-21 16:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggestions-for-setting-var-preference/10299109)._

---
# [Overview]
Please improve the code style setting for "Prefer 'var'" in Visual Studio's C# editor.

# [Visual Studio version]
Microsoft Visual Studio Community 2022 (64-bit) Version 17.5.1

# [Problems]
When I set the `Prefer 'var'` setting in the code style of the C# editor, Visual Studio sometimes makes suggestions that I don't want.

The specific code style settings are as follows.
- Preferences location: `Tools > Options > Text Editor > C# > General > 'var' preferences`
- Settings: `Prefer 'var'`

![01-settings.png](https://aka.ms/dc/image?name=B539576b87041457bb639d25adba39ef3638134416453648028_01-settings.png&tid=539576b87041457bb639d25adba39ef3638134416453648028)

For example, with this setting, the C# editor suggests the following: (type-A)
`string str = "Hello";` => `var str = "Hello";`

But the C# editor also suggests: (type-B)

`TryParse(str, out int value1, out int value2)` => `TryParse(str, out var value1, out var value2)`

![02-main-screen.png](https://aka.ms/dc/image?name=B74c5aebde8d24c82a2affd02848899a4638134418205223475_02-main-screen.png&tid=74c5aebde8d24c82a2affd02848899a4638134418205223475)

I think suggestions like type-A are useful.
However, given that method overloads may be added in the future, fixes like type-B can lead to method call confusion.
So I feel that suggestions like type-B are inappropriate.

# [Suggestion of solution]
I'm not sure if suggestions like type-B are useless for all users. At least I don't see much benefit from a fix like type-B.
Therefore, in the C# code style setting, I think that at least the setting of whether to make suggestions like type-A and the setting of whether to make suggestions like type-B should be separated.

If it seems that there are no users who need proposals like type-B, I think it would be fine to stop making proposals like type-B.

# [Sample code]
Specific sample code is shown below.
Please note that this is code to explain the above problem, and the processing content is sloppy.
```
using System;

namespace Experiment
{
    internal class Test
    {
        public static (bool result, int value1, long value2) DoTest()
        {
            //
            // Visual Studio's c# editor suggests the following:
            //
            //   "string str" => "var str"
            //     * I expect it.
            //
            //   "bool result1" => "var result1"
            //     * I expect it.
            //
            //   "bool result2" => "var result2"
            //     * I expect it.
            // 
            //   "out int intValue1" => "out var intValue1"
            //     * I don't expect it.
            //
            //   "out long longValue1" => "out var longValue1"
            //     * I don't expect it.
            //

string str = "Hello";
            bool result1 = TryParse(str, out int intValue1, out int intValue2);
            bool result2 = TryParse(str, out long longValue1, out long longValue2);

return (result1 && result2, intValue1 / intValue2, longValue1 / longValue2);
        }

public static bool TryParse(string input, out int value1, out int value2)
        {
            throw new NotImplementedException();
        }

public static bool TryParse(string input, out long value1, out long value2)
        {
            throw new NotImplementedException();
        }
    }
}

```

---
#### Feedback Bot on 3/6/2023, 00:16 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2024-11-23 01:00
Closing as this is working as intended.

**Closed by CyrusNajmabadi** 2024-11-23 01:00 UTC
Labels: Area-IDE, Feature Request, IDE-CodeStyle
