### ISSUE TITLE
Compiler message should be silent if an explicit type variable is correctly assigned a LINQ generic type result

### ISSUE THREAD

**Issue by RebeccaVH** [dotnet/roslyn#47172] opened 2020-08-27 00:12 UTC
Description
Currently the compiler message list includes prompts to 
	use 'var' rather than explicit type 
when assigning a LINQ query result for a generic type (ToList() returning List<T>, ToDictionary() returning Dictionary<T, K>).

Expected behavior: this should not be prompted or be the reverse with compiler message prompting to 
	use 'explicit type' rather than var
when assigning a LINQ query result for a generic type (ToList() returns List<T>, ToDictionary returns Dictionary<T, K>) to a var since one cannot tell what T and K are from looking at the LINQ query.

 Expected Good code (no compiler message)
      List<someType> someTypesList = someCollection.Concat(someOtherCollection).ToList();
	
  Not as good code (no compiler message or: use 'explicit type' instead of var)
     var formattedStrings = someCollection.Select(someFormatDelegate).ToList();

To reproduce:
   List<someType> someTypesList = someCollection.Concat(someOtherCollection).ToList();
   (Currently getting compiler message: use 'var' instead of explicit type)

**Comment by sharwell** [comment] 2020-08-27 00:40
Duplicate of #29657

**Closed by sharwell** 2020-08-27 00:40 UTC
