### ISSUE TITLE
Inline temporary variable ignores try block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41594] opened 2020-02-12 00:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/911704/inline-temporary-variable-ignores-try-block.html)._

---
Before

```c#
string Test()
{
    var s = "";

try
    {
        s = "foo";
    }
    catch
    {
    }

return s; // "foo"
}
```

After

```c#
string Test()
{
    var s = "";

try
    {
        s = "foo";
    }
    catch
    {
    }

return "";
}
```

---
#### Visual Studio Feedback System on 2/10/2020, 02:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2020-02-12 23:16
This is by design (and unrelated to try-statements).  The feature even tells you what is happening:

![image](https://user-images.githubusercontent.com/4564579/74386323-77ecad00-4daa-11ea-8dde-020deaf143b5.png)

Specifically, `""` cannot be introduced onto the right-hand-side of the `s = "foo";` line.  that would make `"" = "foo";` which is strictly illegal.  We detect this, mark this as a conflict in the preview, and don't change that line.

**Comment by CyrusNajmabadi** [comment] 2022-10-27 00:37
Closing out as this is intentional.

**Closed by CyrusNajmabadi** 2022-10-27 00:37 UTC
Labels: Bug, help wanted, Area-IDE
