### ISSUE TITLE
CTP6 crash

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#893] opened 2015-02-26 11:51 UTC
VS 2015 CTP6 crashed with unhandled exception:

System.ArgumentNullException
Value cannot be null.
Parameter name: v
   at System.Windows.PresentationSource.CriticalFromVisual(DependencyObject v, Boolean enable2DTo3DTransition)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbQuickInfoPlaceHolder.get_IsMouseOverAggregated()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.MouseTrackingQuickInfoPresenter.IsMouseOverInteractiveContent(IQuickInfoSession2 quickInfoSession)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.MouseTrackingQuickInfoPresenter.ShouldClearToolTipOnMouseMove(MouseEventArgs e)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.MouseTrackingQuickInfoPresenter.DismissIfMouseOutsideOfVisualSpan(MouseEventArgs e)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.MouseTrackingQuickInfoPresenter.OnMouseMoveContainer(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by DustinCampbell** [comment] 2015-02-26 14:56
I just saw encountered the same crash on my home machine when hovering over a diagnostic squiggle in the editor. The squiggle was also on a symbol, and there was a little flicker as the editor tried to display two Quick Info tooltips: one for the symbol and one for the diagnostic. And, of course, the diagnostic had a code fix as well, so the editor attempted to display the light bulb next to the tooltip.

I've got a dump with the heap but it's too large to upload. I'll put it on a USB key and put it on an internal share when I get into the office.

**Comment by DustinCampbell** [comment] 2015-02-26 14:57
I'm applying the "Area-Analyzers" and "Area-IDE" labels, but it could ultimately turn out to be a VS editor bug.

**Comment by DustinCampbell** [comment] 2015-02-26 15:44
Dump is in \\mlangfs1\public\dustinca\Dumps\Crash_Issue_893_DustinCa.dmp

**Comment by Pilchie** [comment] 2015-02-26 15:55
This looks like a duplicate of an internal on the VS editor team (1129765).

**Closed by Pilchie** 2015-02-26 15:55 UTC
Labels: Area-Analyzers, Area-IDE, Bug, Resolution-Duplicate
