### ISSUE TITLE
Live Share - Support Empty -> Nonempty Workspace

### ISSUE THREAD

**Issue by daytonellwanger** [dotnet/roslyn#39475] opened 2019-10-23 22:54 UTC
Live Share recently added a feature for empty workspace sharing. After sharing an empty workspace, the host may then open a solution/folder. Today, Roslyn will not update its remote workspace to reflect the added solution/folder, which results in the absence of many language feature, e.g. FAR and go to def. Roslyn should subscribe to a "workspace roots changed event" and update the remote workspace appropriately.

**Comment by dibarbet** [comment] 2020-01-02 20:24
Closing as dupe of https://github.com/dotnet/roslyn/issues/40362

**Closed by dibarbet** 2020-01-02 20:24 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
