### ISSUE TITLE
Improve cast simplification for pointer conversions and explicit numeric casts in checked/unchecked context

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2987] opened 2015-05-21 19:15 UTC
#2932 conservatively disables cast simplification in presence of pointer conversions and explicit checked/unchecked expressions and statements.

Post 1.0, we should replace these conservative checks with correctly attempting to deduce whether or not cast removal has any semantic changes. This issue tracks that work.

**Comment by CyrusNajmabadi** [comment] 2020-03-30 03:15
I'm going to close this out in #42883.  I fundamentally think we do cast-simplification backwards.  IN other words, it's *appropriate* to be conservative.  We should only make changes that we know are safe.  (And you can see from the dozens of issues i'm fixing, we don't do that).  If anything, we should have a reverse issue: namely that we're not conservative enough and it causes a lot of problems for us.

**Comment by sharwell** [comment] 2020-03-30 03:38
@CyrusNajmabadi Thanks for the clarification here! I'm going to label this as **By Design**, and we can address future safe cases as they are identified.

**Closed** 2020-03-30 09:21 UTC
Labels: Area-IDE, Feature Request, Resolution-By Design
