### ISSUE TITLE
'DiagnosticSuppressor' doesn't work at all when targeting IDEXXXX diagnostics

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#76111] opened 2024-11-27 06:33 UTC
**Version Used**: 4.12.0-3.24558.5 (21192bfc)

**Overview**

This issue is blocking https://github.com/microsoft/CsWinRT/pull/1878. It seems that diagnostic suppressors are not invoked at all by Roslyn when targeting IDEXXXX diagnostics. If I take the same exact suppressor and just change the suppressed id to some CSXXXX diagnostic, then it is invoked as expected. When I change it back to IDEXXXX, it stops working again. Interestingly enough, it does run in a unit test, but not in a real project. I tried both when referencing a .dll from a NuGet package, as well as with a local project reference. `ReportSuppressions` is never called.

**Steps to Reproduce**:

1. Use a suppressor like this:

```csharp
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class CollectionExpressionIDE0300Suppressor : DiagnosticSuppressor
{
    public static readonly SuppressionDescriptor CollectionExpressionIDE0300 = new(
        id: "CsWinRT2001",
        suppressedDiagnosticId: "IDE0300",
        justification:
            "Using collection expressions when targeting 'IEnumerable<T>', 'ICollection<T>', 'IList<T>', 'IReadOnlyCollection<T>', " +
            "or 'IReadOnlyList<T>', when the collection expression is not empty, is not AOT compatible in WinRT scenarios");

    /// <inheritdoc/>
    public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions { get; } = [CollectionExpressionIDE0300];

    /// <inheritdoc/>
    public override void ReportSuppressions(SuppressionAnalysisContext context)
    {
        Debugger.Launch();
        Debugger.Break();
    }
}
```

2. Reference it in a project
3. Cause the diagnostic to be produced, eg. in this case via:

```csharp
int[] x = new[] { 1, 2, 3 };
```

4. Observe that `ReportSuppressions` is never invoked at all.

I can provide logs or anything else needed.

**Expected Behavior**:

The suppressor should work as expected.

**Actual Behavior**:

The suppressor is never invoked at all when targeting IDEXXXX diagnostics.

**Comment by JoeRobich** [comment] 2024-11-27 06:44
Duplicate of https://github.com/dotnet/roslyn/issues/75399. This is fixed by https://github.com/dotnet/roslyn/pull/75684. The fix will be in the next 17.12 servicing release as well as 17.13 previews.

**Closed by JoeRobich** 2024-11-27 06:44 UTC
Labels: Resolution-Duplicate, Area-Analyzers, untriaged
