### ISSUE TITLE
'CSharpWrappingCodeRefactoringProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61642] opened 2022-06-01 23:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpWrappingCodeRefactoringProvider-/10057310)._

---
'CSharpWrappingCodeRefactoringProvider' encountered an error and has been disabled: 

```
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.CSharp.Wrapping.SeparatedSyntaxList.CSharpParameterWrapper.PositionIsApplicable(SyntaxNode root,Int32 position,SyntaxNode declaration,Boolean containsSyntaxError,BaseParameterListSyntax listSyntax)
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.TryCreateComputerAsync[TListSyntax,TListItemSyntax]()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractWrappingCodeRefactoringProvider.ComputeRefactoringsAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync()
```

In my project I am using compiler directives such as:

```csharp
#if NETCOREAPP
        await
#endif
        using var command = ....
```

Maybe that's the problem?
I am also using ReSharper, but this does not look like a ReSharper issue to me.

I see many similar issues with CodeFixProviders stopped working, but not for this specific one.

---
#### Feedback Bot on 5/30/2022, 05:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-06-02 04:21
Duplicate of https://github.com/dotnet/roslyn/issues/61362

**Comment by jasonmalinowski** [comment] 2022-06-06 22:04
Closing since it's indeed a duplicate.

**Closed as not planned** 2022-06-06 22:04 UTC
Labels: Bug, help wanted, Area-IDE, Investigation Required
