### ISSUE TITLE
Go to Definition from C# to F# shows VB Metadata

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#19031] opened 2017-04-26 23:47 UTC
**Version Used**:  VS 15.2

**Steps to Reproduce**:

1. Clone or download this repo: https://github.com/cartermp/15.2-E2E
2. Build everything.
3. In `E2E.API/Controllers/ValuesController`, invoke Go to Definition on the call to `PigLatin.ToPigLatin`.

**Expected Behavior**:

Since we don't support Go to Definition between C# and F#, either:

a. A failure
b. Metadata generated in C#.

**Actual Behavior**:

Metadata is generated in Visual Basic .NET.

![go-to-def-from-csharp](https://cloud.githubusercontent.com/assets/6309070/25461819/09827136-2aa0-11e7-9101-774d83466872.gif)

**Comment by 0xd4d** [comment] 2017-04-27 00:43
Perhaps related: https://github.com/dotnet/roslyn/issues/16818

**Comment by Pilchie** [comment] 2017-04-28 21:17
We don't currently support Go To def from C# to F# (See https://github.com/dotnet/roslyn/issues/8105 for that).  Presumably the metadata as source service just picks VB if it doesn't know what the source language, but we should be generating C#.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 22:26
Closing as dupe of https://github.com/dotnet/roslyn/issues/8105.  F# should hopefully be supporting this soon.

**Closed by CyrusNajmabadi** 2022-10-28 22:26 UTC
Labels: Bug, Area-IDE
