### ISSUE TITLE
VB MemberSemanticModel and InitializerSemanticModel track only the first field symbol for field declarations with As New

### ISSUE THREAD

**Issue by msJohnHamby** [dotnet/roslyn#8187] opened 2016-01-26 21:43 UTC
For VB field declarations of the form:
    Private F1, F2 As New T()
InitializerSemanticModel, with help from MemberSemanticModel, loses track of the symbol for F2 and creates a field initialization bound node with only the symbol for F1. Symbols for both F1 and F2 should be included.

The assumption that a given initializer applies to only one symbol seems pretty well baked into the semantic model code, but is not correct.

**Comment by mavasani** [comment] 2016-01-27 16:21
I haven't looked at SemanticModel code for quite a while now. Probably @AlekseyTs or someone else from compiler team may want to take a look.

**Comment by AlekseyTs** [comment] 2016-01-27 18:15
@JohnHamby Could you explain what is the negative effect for the consumer of the API? Consider adding a skipped unit-test demonstrating this.

**Comment by JohnHamby** [comment] 2016-01-27 18:23
The symptom is that the IFieldInitializer implementation exposed by an As New field declaration presents only the first declared field in its InitializedFields property. In reviewing the recent PR that added IOperation support for explicitly marking initialized field declarations, @AlekseyTs pointed out the need to present all such fields.

**Comment by srivatsn** [comment] 2016-02-26 23:53
It sounds weird to have RegisterOperationBlockAction return multiple blocks and if this is a concern only for some corner cases then can we instead have a single block and property called AdditionalBlocks for the corner cases?

**Comment by JohnHamby** [comment] 2016-02-29 06:22
I was confused during the triage meeting. This issue isn't the reason for having multiple code blocks in OperationBlockStartAnalysisContext and OperationBlockAnalysisContext.

**Comment by jinujoseph** [comment] 2017-07-03 23:43
dupe of https://github.com/dotnet/roslyn/issues/17813

**Closed by jinujoseph** 2017-07-03 23:43 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
