### ISSUE TITLE
Add quick fix to generate a field and initialize from a constructor parameter

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#15648] opened 2016-12-02 22:27 UTC
Generate constructor works the other way, but it would be nice to be able to generate a field and an assignment to it after adding a parameter to a constructor.

```C#
class C
{
    public C(string f)
    {
    }
}
```

With the caret in `string f`, we should be able to generate a field and initialize it.

**Comment by alrz** [comment] 2016-12-10 09:34
Re "Generate constructor works the other way" I couldn't find in VS2015U3, how can I use that?

**Comment by CyrusNajmabadi** [comment] 2016-12-12 00:55
Select a bunch of fields/properties.  Hit ```ctrl-<dot>```.

**Comment by alrz** [comment] 2016-12-12 07:18
Well that wasn't my first guess, although it makes sense when you know how to do it. Wouldn't it be better to put it on the unassigned field and suggest to initialize (all) fields in the (possibly existing) constructor?

**Comment by CyrusNajmabadi** [comment] 2016-12-12 07:35
There are many different types of interaction models and entry-points that could help improve things here.

From the field.  From the constructor.  From the parameter.  It would be nice to continually improve in this area.

**Comment by alrz** [comment] 2016-12-12 09:06
>There are many different types of interaction models and entry-points

@CyrusNajmabadi It seems that currently we don't have any analyzer that works on various entry points? I think these kinds of analyzers belong to a different category, namely "code generation". Perhaps we need a separate menu for all applicable code generation options related to a portion of code e.g. a type.

**Comment by alrz** [comment] 2017-01-19 20:01
Probably a duplicate of #8925.

**Closed** 2017-04-04 22:36 UTC
Labels: 0 - Backlog, Area-IDE, Feature Request
