### ISSUE TITLE
.Net 6 string interpolation for Int32 using a format specifier

### ISSUE THREAD

**Issue by edubsi** [dotnet/roslyn#57948] opened 2021-11-09 13:43 UTC
### Description
Some tests regarding the string interpolation for an int were failing after the project upgrade to net6.0 

A minimal reproducible example of the Test would be

        [Fact]
        public void StringInterpolation()
        {
            const int utf32 = 129412;
            var result = $"\\x{{{utf32:x8}}}";
            Assert.Equal("\\x{0001f984}", result);
        }

 The test was passing before the project upgrade and is now failing. The Assert output for the test:

      Assert.Equal() Failure
                   ↓ (pos 3)
      Expected: \x{0001f984}
      Actual:   \x{x8}}
                   ↑ (pos 3)

### Configuration
MacOs with dotnet SDK 6.0.100 and target framework net6.0

### Regression?
The test is passing if you target net5.0 . The workaround would be to use `toString("x8")` which works as expected.

**Comment by CyrusNajmabadi** [comment] 2021-11-23 21:42
Dupe of https://github.com/dotnet/roslyn/issues/57750

**Closed by CyrusNajmabadi** 2021-11-23 21:42 UTC
Labels: untriaged
