### ISSUE TITLE
Switch expression that returns lambda crashes VS right after typing open brace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39350] opened 2019-10-17 17:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/761865/switch-expression-that-returns-lambda-crashes-vs-r.html)._

---
<p>Paste following code to crash VS:<br>
<code>var x = ((Func&lt;int, decimal&gt;)(0 switch { 0 =&gt; _ =&gt; {}}))(0);</code></p>

---
#### Visual Studio Feedback System on 10/7/2019, 01:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:45 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 10/9/2019, 11:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by agocke** [comment] 2019-10-17 17:10
@jcouv Could you take a look at this? It looks like it may be a relatively simple problem in the symbol formatter

**Comment by jcouv** [comment] 2019-10-17 17:35
Will do

**Comment by jcouv** [comment] 2019-10-21 19:31
Turns out this issue was already reported and fixed.
Closing as duplicate of https://github.com/dotnet/roslyn/issues/39082

**Closed by jcouv** 2019-10-21 19:31 UTC
Labels: Area-Compilers, Bug
