### ISSUE TITLE
Include enough information in AD0001 (when an analyzer throws) to be able to disable & file a bug

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30660] opened 2018-10-23 00:21 UTC
I've got the following error in my error list:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices
ISymbol: FuncWithOut (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.GetUsedNamedTypes(INamedTypeSymbol namedType, Compilation compilation, CancellationToken cancellationToken, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.<>c__DisplayClass11_0.<Initialize>b__1(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__39_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

This is blocking my build, but there's not enough information in the error to be able to file a bug & disable the analyzer. Please include the analyzer ID & the full identity of the assembly it comes from.

**Comment by jinujoseph** [comment] 2018-10-23 08:33
dupe of https://github.com/dotnet/roslyn/issues/24346 ?

**Comment by davkean** [comment] 2018-10-23 10:15
This is slightly different, that bug is talking about the stack trace via csc, I'm asking for enough information to _disable_ and file a bug; analyzer ID, and the full identity of the assembly it comes from.

**Comment by sharwell** [comment] 2018-10-26 18:53
📝 Note: information required to disable the analyzer would include all other diagnostic IDs reported by the same analyzer. If any of the IDs is enabled, the analyzer could be active.

**Comment by taori** [comment] 2019-01-31 11:03
Truely odd bug. My IDE showed some expandable node in the error list with a stack trace so i didn't save a screenshot and later i came back to this:

![grafik](https://user-images.githubusercontent.com/5545184/52050225-32b75d80-2550-11e9-9861-05f3e328a648.png)

reported by CSC, non expandable. I guess that's what OP is talking about.

**Comment by jinujoseph** [comment] 2019-03-09 01:51
reported at [DC ](https://developercommunity.visualstudio.com/content/problem/480180/analyzer-exception-hard-to-report-and-hide.html)

**Comment by sharwell** [comment] 2019-05-02 05:31
Design review conclusion:

1. Update the AD0001 implementation to report scenario-specific information to help with narrowing down the cause. Examples for some types of analyzer callbacks can be seen in [vs-threading](https://github.com/Microsoft/vs-threading/blob/f7230a9fc3599f5e00817c1a6d30691d80916fb4/src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs#L26-L81).
2. Further update the AD0001 implementation to list all diagnostic IDs that need to be disabled in order to prevent the offending analyzer from running.

**Closed** 2020-02-04 01:23 UTC
Labels: Area-Analyzers, Bug, Developer Community, Resolution-Fixed
