### ISSUE TITLE
Remove `ConversionsBase.IncludeNullability`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#30807] opened 2018-10-26 22:50 UTC
Remove nullability from `ConversionsBase` if possible, and consider nullability in conversions in `NullableWalker` only.

See also https://github.com/dotnet/roslyn/issues/27124.

**Comment by cston** [comment] 2018-10-26 22:51
cc @gafter

**Comment by jcouv** [comment] 2019-01-30 21:34
Relates to https://github.com/dotnet/roslyn/issues/27124 (Replace `ConversionsBase.IncludeNullability` with diagnostic bag)

**Comment by jaredpar** [comment] 2019-02-12 21:12
Closing as a dupe of #27124

**Closed by jaredpar** 2019-02-12 21:12 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types

**Comment by jaredpar** [comment] 2019-02-15 22:05
Fixing resolution as this is different. @cston and I chatted a bit and decided this wasn't a realistic goal here. I mistaken lumped it in with the other discussions around the nullability in this type.
