### ISSUE TITLE
Roslyn.sln fails to build with WarnOnError=true

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14112] opened 2016-09-27 20:14 UTC
I'm getting these warnings now in the OOP projects:

```
C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(190
2,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be reso
lved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\GitHub\roslyn-i
nternal\Open\src\VisualStudio\RemoteHostClientMock\RemoteHostClientMock.csproj]

C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(190
2,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be reso
lved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\GitHub\roslyn-i
nternal\Open\src\VisualStudio\Core\Test.Next\VisualStudioTest.Next.csproj]
```

I believe both of these are heejae's new assemblies.

Note that these have occasionally been breakign the build on Jenkins.  I'm not sure why it doesn't consistentl ybreak (but maybe  it has to do with Node reuse and if that node has that option set).

**Comment by CyrusNajmabadi** [comment] 2016-09-27 20:14
Tagging @heejaechang @panopticoncentral @srivatsn

**Comment by jasonmalinowski** [comment] 2016-09-28 21:03
I think @heejaechang or @mattwar are already working on this?

**Comment by mattwar** [comment] 2016-09-28 21:46
Yes, this is similar to what I am looking at..

**Comment by mattwar** [comment] 2016-10-19 16:06
Jared is the one trying to rid the build of these now.

**Comment by jaredpar** [comment] 2016-10-19 16:34
This is a dupe of https://github.com/dotnet/roslyn/issues/13980

**Closed by jaredpar** 2016-10-19 16:34 UTC
Labels: Area-Analyzers, Bug
