### ISSUE TITLE
borders for selected reference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75123] opened 2024-09-16 15:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/borders-for-selected-reference/10726472)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:problem started since VS 2022]
For code references (Shift+F12) when a line from references was selected in addition to navigating to the page with that code, earlier versions of visual studio used to either highlight or show a border around that line also, similar to how "find All" feature (ctrl+shift+F) still does. 
It is not doing that anymore [per picture], it highlights all such references in all open windows, but does not show me which is the line I have now selected. It makes me have to manually match the filename and line number myself.
There might be screwdriver icon to the left, but often it is overwritten by other icons and also there would be one of the same icon in every open window. A border around the line, similar to how it works in "Find all" would be very helpful.

![image.png](https://aka.ms/dc/image?name=B0f4a0312ecec4df7b3b1acbe7cffd599638597140478817099_20240819-202727-image.png&tid=0f4a0312ecec4df7b3b1acbe7cffd599638597140478817099)

---
#### Feedback Bot on 8/19/2024, 09:12 PM: 

(private comment, text removed)
#### Feedback Bot on 8/21/2024, 01:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2024-09-16 15:12
@kayle observed the following:

> Did Roslyn make an intentional change to select the reference when navigating? This hides the Editor's 'current line highlighter' feature. If the selection is empty, we show the current line highlight. I'm happy to ask PMs if we would prefer to have the highlight for single-line selections which would also address this feedback.

Based on this, I have narrowed down the cause of this regression to #71959, where the unification of some navigation features resulted in text getting selected in some scenarios where previously it was not.

**Comment by CyrusNajmabadi** [comment] 2024-11-26 03:02
Closing out as intentional.

**Closed by CyrusNajmabadi** 2024-11-26 03:02 UTC
Labels: Area-IDE, Regression, untriaged
