### ISSUE TITLE
When should variance be permitted for nullable type arguments?

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#36894] opened 2019-06-29 23:01 UTC
I encountered the following couple of scenarios just now:

```cs
#nullable enable

using System.Threading.Tasks;

public class C {
    public Task<string?> M1() {
        // warning CS8619: Nullability of reference types in value of type
        // 'Task<string>' doesn't match target type 'Task<string?>'.
        return Task.FromResult("hello");
    }

    public void M2(Task<string?> task) { }
    public void M3()
    {
        // warning CS8620: Argument of type 'Task<string>' cannot be used for
        // parameter 'task' of type 'Task<string?>' in 'void C.M2(Task<string?> task)'
        // due to differences in the nullability of reference types.
        M2(Task.FromResult("hello"));
    }
}
```

I see a few fixes users can do for this:
1. change to `Task.FromResult("hello")!`
2. change to `Task.FromResult<string?>("hello")`
3. `Task.FromResult((string?)"hello")` ~~(this gets marked as redundant by the IDE)~~

It feels like there should be some way to allow nullable variance of certain type parameters so that such workarounds aren't necessary. Interface types can have `in`/`out` modifiers on their type parameters but this doesn't work for types like `Task<T>`.

**Comment by RikkiGibson** [comment] 2019-06-30 15:51
If this is a scenario where we'd rather have users make a change to their code to get rid of the warning, perhaps we could pick an option that feels like a best practice (option 2?) and make a code fix for it

**Comment by jcouv** [comment] 2019-07-10 16:58
The problem is that `Task<T>`  is invariant (no `in` or `out` on `T`). In the common case (which you describe above), it is tempting to do something special, but it would lead to some unsafety (missed warnings) in some other cases... :-(

**Comment by alrz** [comment] 2019-08-29 13:49
could we use a special attribute on the type parameter so this is possible also for user code (not just task)? classes dont support in/out variance but the compiler could at least make it possible for nullability

**Comment by tmat** [comment] 2019-12-12 23:43
@jcouv Why is `Task<T>` invariant though (conceptually)? I only see API that returns (`TResult Result { get; }`), not any that would set the value the result. If I convert an instance of `Task<string>` to `Task<string?>` I can't now make it return `null` if it previously returned non-null values only, can I?

**Comment by sharwell** [comment] 2019-12-12 23:44
@tmat It's invariant due to a language limitation that variance only applies to interfaces and delegates.

**Comment by tmat** [comment] 2019-12-13 00:06
@sharwell Yes, I understand we currently have this limitation. I was asking if there is a reason why it couldn't be conceptually since @jcouv indicated it might not be safe. If it's just language limitation then the ask is to remove such limitation in some shape or form. E.g. adding an attribute on the type parameter.

**Comment by jasonmalinowski** [comment] 2019-12-13 00:59
This whole thread might also be a :+1: for finally adding an ITask<T> that has a covariant `T Result` and nothing further, since you sometimes want that too. Not that I don't want the nullable analysis to also be smarter here, but we've been working around the lack of *that* for years too...

**Comment by RikkiGibson** [comment] 2019-12-13 01:33
I think that it might be possible to add such an attribute, but checking it might be tricky. `Task<T>` does have internal API to write to the Result field, so I imagine you'd have to suppress warnings.

**Comment by jaredpar** [comment] 2021-02-10 01:24
Closing as this is tracked with the `Task<T>` covariance language proposal. 

https://github.com/dotnet/csharplang/issues/3950

**Closed by jaredpar** 2021-02-10 01:24 UTC
Labels: Area-Compilers, Area-Language Design, New Language Feature - Nullable Reference Types
