### ISSUE TITLE
Generic class operators derived from interface seems broken

### ISSUE THREAD

**Issue by timdoke** [dotnet/roslyn#40042] opened 2019-11-27 21:31 UTC
Let's say I have a CaseInsensitiveConcurrentDictionary.  The intention of it is to be interchangeable with regular Dictionary implementations -- where, we always use the interface IDictionary<T, T> to interact with either.  Both Dictionary and ConcurrentDictionary implement IDictionary interface members.

The class looks like this:

    public class CaseInsensitiveDictionary<TValue>
        : ConcurrentDictionary<string, TValue>
    {
        public CaseInsensitiveDictionary()
            : base(StringComparer.InvariantCultureIgnoreCase)
        {
        }

        private CaseInsensitiveDictionary(IDictionary<string, TValue> attributes)
            : this()
        {
            AddRange(attributes);
        }

        public void Add(string key, TValue value)
        {
            this.TryAdd(key, value);
        }

        public void AddRange(IDictionary<string, TValue> entries)
        {
            foreach (var item in entries)
            {
                this.TryAdd(item.Key, item.Value);
            }
        }

        public static CaseInsensitiveDictionary<TValue> Create(IDictionary<string, TValue> attributes = null)
        {
            if (attributes == null)
            {
                return new CaseInsensitiveDictionary<TValue>();
            }
            return new CaseInsensitiveDictionary<TValue>(attributes);
        }

        public static implicit operator Dictionary<string, TValue>(CaseInsensitiveDictionary<TValue> data)
        {
            return new Dictionary<string, TValue>(data);
        }

        public static implicit operator CaseInsensitiveDictionary<TValue>(Dictionary<string, TValue> data)
        {
            return Create(data);
        }

    }

`  

Let's say then that we are trying to implicitly convert the ConcurrentDictionary to and from a dictionary.  To test, I wrote these methods:

        public void FromDictionaryToCaseInsensitiveDictionaryTest()
        {

            Dictionary<string, string> dc2 = new Dictionary<string, string>();
            dc2.Add("test1", "test1 value");

            var dc3 = (CaseInsensitiveDictionary<string>)dc2;
            Console.WriteLine("FromDictionaryToCaseInsensitiveDictionaryTest success");
        }

        public void FromIDictionaryToCaseInsensitiveDictionaryTest()
        {
            IDictionary<string, string> dc2 = new Dictionary<string, string>();
            dc2.Add("test1", "test1 value");

            var dc3 = (CaseInsensitiveDictionary<string>)dc2;

            Console.WriteLine("FromIDictionaryToCaseInsensitiveDictionaryTest success");
        }

        public void FromCaseInsensitiveDictionaryToDictionaryTest()
        {

            var dc2 = new CaseInsensitiveDictionary<string>();
            dc2.Add("test1", "test1 value");

            var dc3 = (Dictionary<string, string>)dc2;

            Console.WriteLine("FromCaseInsensitiveDictionaryToDictionaryTest success");

        }

The first (FromDictionaryToCaseInsensitiveDictionaryTest) and third methods (FromCaseInsensitiveDictionaryToDictionaryTest) work fine and correctly use the operators.

The second one fails with this exception: System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' to type 'OpenToken.CaseInsensitiveDictionary`1[System.String]'.'
.  In my opinion, FromIDictionaryToCaseInsensitiveDictionaryTest should work because the type is CaseInsensitiveDictionary and implements IDictionary.  If I do NOT have the first conversion operator, the first test method fails with this exact same error message, 

With this evidence, it seems to me that something is missing when the runtime is looking for the appropriate operator.  FromIDictionaryToCaseInsensitiveDictionaryTest should work either from the Dictionary operator or automatically work because it implements the IDictionary interface.  (I cannot create an operator for IDictionary conversion because that is illegal).  

Please let me know if this is expected behavior and if there is some workaround for it.  This issue seems to be present in all versions of C#.

Thanks!

**Comment by terrajobst** [comment] 2019-11-27 22:05
@timdoke 

The behavior is by design:

```C#
        IDictionary<string, string> dc2 = new Dictionary<string, string>();
        dc2.Add("test1", "test1 value");

        var dc3 = (CaseInsensitiveDictionary<string>)dc2;
```

`dc2` has the static type `IDictionary<string, string>`. The compiler won't let you assign for that reason, e.g. this won't compile:

```C#
        CaseInsensitiveDictionary<string> dc3 = dc2;
```

(because you only have an implicit conversion from `Dictionary<string, string>` to CaseInsensitiveDictionary<string>, not from the interface).

When you do an explicit cast, the compile will honor user defined conversion operators, but the compiler can only look up operators that exist on either the source or the destination. And neither `CaseInsensitiveDictionary<,>` nor `IDictionary<,>` define any conversions for and `IDictionarty<,>` to `CaseInsensitiveDictionary<,>`. Hence, it falls back to a dynamic cast that will only succeed if a derivative of `CaseInsensitiveDictionary<,>` would implement `IDictionary<,>`.

Does that make sense?

**Comment by huoyaoyuan** [comment] 2019-11-27 22:08
OK I can answer you. 
Given C# is a statically typed language, which operator get called is decided at compile type, by delcared type of variables. 

> With this evidence, it seems to me that something is missing when the runtime is looking for the appropriate operator. 

Runtime doesn't look for operators. 

> I cannot create an operator for IDictionary conversion because that is illegal

A type cannot define user-cast syntax to its base/interface, because direct cast will be always used. Generally the cast syntax is only intended to be used on sealed plain types.

The general guideline is using extension method called `ToXXX` to present such conversion, like `ToHashSet`.

**Comment by timdoke** [comment] 2019-11-27 23:00
@terrajobst I'm probably misunderstandingg, but I can't create an implicit operator from IDictionary because ConcurrentDictionary already implements that interface..  Changing it to implement IDictionary is redundant and does nothing..  Creating an implicit operator from IDictionary gives a compilation error (not runtime error like the above example)..

So... It sounds like this is impossible with an implicit converter.. I need it to be implicit because it's working with external source code.. 

For the most part, the implicit operator from CaseInsensitiveDictionary to Dictionary seems to work for my case, but I wanted to be safe and have the reverse operator.

Am I understanding you correctly @huoyaoyuan and @terrajobst?  Thanks for the replies!

It sounds like I'm out of luck unless there some trick I can do with a Toxxx method to give a hint to the compiler?

**Comment by timdoke** [comment] 2019-11-28 06:05
I read these answers again.. A couple times.. So, I think what I'm hearing, is the implicit conversion would work from CaseInsensitiveDictionary to ConcujrrentDictionary (obviously though because it's the base class).. I can't write an explicit converter because that is not allowed from the Dictionary implementation,, since it is actually an IDictionary declaration, which is not allowed because it's already inherently implemented..; An explicit converter (as I had in test one) was really implicit -- my color coding just didn't show me (at that time) the explicit conversion was redundant..  Test one really just fell back to implicit conversion -- which makes sense because I didn't have an explicit operator..

It at least seems strange I get the exact same runtime error (when I run the second test with an explicit conversion attempt) as I would in the first test when no explicit or implicit operator exists..    I think the error in scenario two should at least convince me it's a failure for a different reason..  The error message, without the operator in scenario one is identical to the error message I'm getting in scenario two.

I would almost think, for cases like this, ideally it should fall back onto the operator of the implemented type instead of the declared type, for this type of scenario, if one doesn't exist for the declared type.. After all, in this case, it is impossible to create an operator against IDictionary... Please let me know if I understand this correctly now.. Thanks!

**Comment by huoyaoyuan** [comment] 2019-11-28 08:28
> ideally it should fall back onto the operator of the implemented type instead of the declared type

Which operator get called is totally decided at compile time. There's no "implemented type" to use.

Using user-defined operator or conversion isn't supposed in such scenario. The suggested API shape should be:
https://source.dot.net/#System.Linq/System/Linq/ToCollection.cs,3b25ba121f03ed73,references

**Comment by gafter** [comment] 2019-12-02 22:10
Closing as by design (this is the specified/required behavior of the C# language)

**Closed by gafter** 2019-12-02 22:10 UTC
Labels: Area-Compilers
