### ISSUE TITLE
Missing items in Task List

### ISSUE THREAD

**Issue by sianko** [dotnet/roslyn#50084] opened 2020-12-21 10:06 UTC
**Version Used**: 16.8.2

**Steps to Reproduce**:
(It happens quite often but not always.)

1. Open a C# solution
2. Open Task List

**Expected Behavior**: All built-in and custom tokens should be displayed.

**Actual Behavior**: 
[Often] Built-in tokens are displayed but custom tokens are missing.
[Less often] The list is empty so neither built-in nor custom tokens are displayed.

Related issue: #43788 

I enclose the screens which shows what steps are required to refresh the list.
After I modify the file, all tokens from this file appear in Task List but tokens from other files are still missing.

Restarting Visual Studio partially helps because all built-in tokens are displayed properly but custom tokens are still missing. Similarly, custom tokens from a single file will be displayed, after I modify the file (any modification, not necessarily the comment).

![VS_TaskList_bug](https://user-images.githubusercontent.com/5628456/102763689-52411480-437a-11eb-9e53-8f72247eda2c.png)

**Comment by gdignard** [comment] 2021-01-10 23:17
This problem has been raised a few times and it tends to get flagged as a duplicate of the bug with custom tasks being ignored.

This is the parsing of built-in tasks markers like TODO not being conducted at solution startup.

Some projects will get correctly parsed and their markers will appear in the task list while other projects will not.

As @sianko stated, sometimes NO projects get parsed and the task list appears empty.

I haven't experienced where a project is only partially parsed; rather the project will either have all its markers or none of them.

**Comment by CyrusNajmabadi** [comment] 2021-01-11 04:42
Yes. But the issue was fixed. So far, everything filing the issue has reported it in a version of VS that does not have the fix.

**Comment by gdignard** [comment] 2021-01-12 00:14
Do you have the issue number? My searches haven't found any issue other than problems relating to the custom task markers.

**Comment by mavasani** [comment] 2022-01-04 14:41
This issue has been fixed in 16.10

**Closed by mavasani** 2022-01-04 14:41 UTC
Labels: Bug, Area-IDE, Investigation Required
