### ISSUE TITLE
Nullable reference not recognized

### ISSUE THREAD

**Issue by ddobric** [dotnet/roslyn#48552] opened 2020-10-13 06:34 UTC
Following code produces the annotation below:

```
var lib = new ClassLibrary1.MyLib();
Console.WriteLine(lib.Prop1[0]);
```
![image](https://user-images.githubusercontent.com/1756871/95823747-70f9ae00-0d2e-11eb-9032-2cd2e1730eaa.png)

The property looks like:

```
 public class MyLib
    {
        [AllowNull]
        public string Prop1 { get; set; } = null;

        [DisallowNull]
        public string Prop2 { get; set; } = String.Empty;

        [return: MaybeNull ]
        //[return: NotNull]
        public string DoIt(string? inp)
        {
            return inp;
        }
    }

```

The annotated information is not correct and the application throws null ref exception. 

### RT Version
Using 5.0.100-rc.1.20452.10

**Comment by Joe4evr** [comment] 2020-10-13 13:25
`[AllowNull]`/`[DisallowNull]` only affect input, aka the setter (or more specifically, the implicit setter parameter `value`). As far as the compiler thinks, the getter will return a non-null value, so it doesn't see fit to warn.

In this particular case, the author of the code should make their annotations accurate. 🙃

**Comment by jaredpar** [comment] 2020-10-13 16:46
Closing as this behavior is "By Design" as @Joe4evr noted

**Closed by jaredpar** 2020-10-13 16:46 UTC
Labels: Area-Compilers, untriaged
