### ISSUE TITLE
Misplaced indent guides

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#30300] opened 2018-10-03 23:19 UTC
**Version Used**: 2.10.0-beta2-63318-05+750236a7562d8fd0d5efe311c52ae0703093165f

🔗 Also filed as [AB#1302761](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1302761)

**Steps to Reproduce**:

```CSharp
class MyClass
{
    object RootNode;

    public MyClass()
    {
        this.RootNode = new Node(
            name: "name",
            expandByDefault: true)
        {
            ItemId = 1,
        };
    }
}
```
**Actual Behavior**:

![image](https://user-images.githubusercontent.com/10508071/46444683-f30a7180-c727-11e8-8da0-0d6daa765b6a.png)

Seems likely to be related to the object initializer.

**Comment by sharwell** [comment] 2018-10-09 16:38
@olegtk We had a bug to replace our current block structure tagger with a new API, but now I can't remember the name of the new API or find the Roslyn bug suggesting we update. Can you give us a hint? :smile:

**Comment by olegtk** [comment] 2018-10-09 16:50
@gundermanc

**Comment by gundermanc** [comment] 2018-10-09 16:55
This is related to #24067 and #16395, both of which can be fixed by #26445. Essentially we just need Roslyn to switch over to the IStructureTag API and correctly implement all members.

Today, Roslyn gives us incorrect spans and we do a best effort guess at what you want. IIRC Cyrus had an ask to change the behavior of the API to make your side easier.

**Comment by CyrusNajmabadi** [comment] 2018-10-09 19:09
Yes.  This should be done at the editor level.  The issue here is that the structure line is inherently a view-oriented construct.  i.e. it's dependent on things like "how big is a tab, versus how big are spaces".  I recall coming up with a heuristic the editor coudl apply that worked for 100% of all C#/VB/JS/TS cases.  So it would be great if that were taken.

IIRC, it was simply taking the left-most (in view coordinates) column between the start/end points and using that as the column to draw in.  Or it was something very similar to that.  @gundermanc do you remember?

**Comment by gundermanc** [comment] 2018-10-10 20:54
Filed a bug for this ask for D16 P2. I'll update the thread once we have the behavior changed. I _think_ that the migration to IStructureTag doesn't need to block on this change. Without it, you should get similar behavior to what is there today, albeit with correct tooltips in VS.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:02
What do you mean by "with correct tooltips in VS"?
Thanks!

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:04
@gundermanc ^

**Comment by gundermanc** [comment] 2018-10-10 21:05
Typo... correct tooltips in VB.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:30
Sorry... i feel like i'm dense.  What is the relation between VB and this issue?  THanks @gundermanc

**Comment by gundermanc** [comment] 2018-10-10 21:36
#24067, #16395, and #26445 are all bugs that are caused by Roslyn returning incorrect spans to the IBlockTag API. Returning correct spans in IStructureTag can fix all of these issues, even without an editor side change to assume the GuideLineHorizontalAnchor as the left-most endpoint of the span.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:43
> Returning correct spans in IStructureTag can fix all of these issues

Could you explain what you mean by the "correct spans"?  From my recollection of past convos, the idea of what was a 'correct span' was inherently what was difficult as languages generally do not have an understanding of this information in order to answer that question.

For example, the 'correct span' ends up changing depending on things like *ui settings arond how big a tab is*.  However, languages generally do not have, or do not care, about how the final UI will render a tab.  They simply want to say: here is my block, and the relevant start/end bit for it.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:45
Or are you saying: if roslyn literally took the existing IBlockTag info from today and instead just returned it in IStructureTag, things would just work?  If so, i'm happy to make that change.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 21:52
Ok.  trying this out.  will report back soon on effectiveness.

**Comment by gundermanc** [comment] 2018-10-10 21:59
#24067 can be fixed using IStructureTag or IBlockTag so long as you give us the spans we expect. 'StatementSpan' should be the header of the block ( `if (cond)`), but Roslyn currently gives us the entire span of the block (from 'i' to '}'). I believe that this will also fix #16395 but it has been a while since I looked.

This issue can be fixed by editor or by Roslyn by picking a different horizontal anchor. There is nothing stopping Roslyn from picking the left most point of the span. The tab size is already exposed as an EditorOption on the buffer. We can add this behavior in editor but it will take a while to round trip and no one else has asked for it.

**Comment by CyrusNajmabadi** [comment] 2018-10-10 22:06
> but Roslyn currently gives us the entire span of the block (from 'i' to '}')

Because that's the conceptual thing being collapsed.  It's also so we can show useful stuff on hover like:

![image](https://user-images.githubusercontent.com/4564579/46768679-03799980-cc9e-11e8-8cb5-d3d59fdbf919.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-10 22:06
Switching impl doesn't seem to have helped.  I still get this:

![image](https://user-images.githubusercontent.com/4564579/46768707-1b511d80-cc9e-11e8-9816-97215df135b0.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-10 22:36
> but Roslyn currently gives us the entire span of the block (from 'i' to '}')

I also tried manually tweaking this (for that `new Node(`) case above.  i changed the header span to stop being from `new to }` and made it from `new` to the start of the outlining span.  But i still get:

![image](https://user-images.githubusercontent.com/4564579/46769880-08404c80-cca2-11e8-8b26-956e26916c22.png)

It's unclear to me what the language is even supposed to be computing here for these values.  The old values made a ton of sense.  One span was what you actually wanted to outline.  i.e.:

![image](https://user-images.githubusercontent.com/4564579/46769903-1f7f3a00-cca2-11e8-962f-a3aaf265f96e.png)

The other is what you wanted to be seen once the outlining guy was collapsed.  i.e. https://github.com/dotnet/roslyn/issues/30300#issuecomment-428749962

**Comment by gundermanc** [comment] 2018-10-11 00:07
>  The old values made a ton of sense.
The old values were incorrectly populated. They only worked because there was a check for Roslyn that would do more or less the right thing by mangling the spans given. The underlying heuristic behavior hasn't changed as long as you provide only the StatementSpan and the OutliningSpan. This problematic heuristic is what is choosing the 'n' in new as the horizontal column for the adornment. To address this issue, you need to either write some code that picks a different horizontal anchor.

Per [IStructureTag docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.tagging.structuretag?view=visualstudiosdk-2017), the important fields are:
- HeaderSpan: Defines the text shown for this method in the tooltip (if omitted, there will be no structure tip entry for this block)
- OutliningSpan: Defines the text that is to be collapsed by the outlining adornment (if omitted, there will be no outlining)
- Guide​Line​Horizontal​Anchor​Point: Defines the column to which the structure guide is aligned (if omitted, we infer using the heuristic below).
- GuideLineSpan: Defines the vertical extent of the structure guide (if omitted, we use the OutliningSpan).

Without specifying Guide​Line​Horizontal​Anchor​Point, we use the same heuristic as with the IBlockTags
```
// There are three cases to consider for the starting x-point of the block:
            // 1)       if (foo) {
            //          |                           // Line goes here
            //
            // 2a)      if (foo)
            //          {
            //          |                           // Line goes here
            //
            // 2b)      if (foo)
            //              {
            //              |                       // Line goes here
            //
            // 3)       if (bar &&
            //              foo) {
            //          |                           // Line goes here
            // In all cases, find the position of the first non-whitespace character on the line.
```
This heuristic is naïve and assumes that the header span should start at the 't' like it does in the core editor's indent-based StructureTagger. Since the block you're giving us has a header that isn't aligned with the '{', you need to give us a character aligned with the '{' curly brace to get the line aligned with the curlies.

C++ LS gives us '}' so that the guide is always aligned with the close curly.

You can do the same thing, but anyone who writes:

```
if (true)
{
    ...}

```

will get a brace 'reaching up' from the close curly.

I can add the left-most end-point logic that you are requesting to the editor but it will take time to make it out the door.

If you wanted a solution with a faster turn-around, you can implement this same logic by checking the index of the start and end points of the GuideLineSpan in their respective ITextSnapshotLines.

The mixed-tabs-spaces scenario is rare, but you can handle that as well by getting the `DefaultOptions.TabSize` option value from the options on the ITextBuffer and then using it to calculate the indent of each as a count of fixed width spaces.

**Comment by CyrusNajmabadi** [comment] 2018-10-11 00:34
> I can add the left-most end-point logic that you are requesting to the editor but it will take time to make it out the door.

That would be awesome.

>The mixed-tabs-spaces scenario is rare, but you can handle that as well by getting the DefaultOptions.TabSize option value from the options on the ITextBuffer and then using it to calculate the indent of each as a count of fixed width spaces.

I would definitely like to *never* be in the job of not having to do that sort of hting.  IMO, it's much cleaner for the languages to speak in terms of language concepts, and just have the final presentation system make these determinations. 

--

> you need to give us a Guide​Line​Horizontal​Anchor​Point aligned with the '{' curly brace to get the line aligned with the curlies.

Hrmm... that seems odd.  Wouldn't that screw things up for cases lke:

```c#
if (...) { 
```

If it was aligned with that {, then wouldn't that cause problems?

--

```c#
C++ LS gives us '}' so that the guide is always aligned with the close curly.

You can do the same thing
```

This is not done at a layer that has any language knowledge.  we don't know what the actual language constructs are or if things like > are actually important.

--

> You can do the same thing, but anyone who writes:

```
if (true)
{
    ...}
```

That case *definitely* comes up.  Specifically with something like xml-blocks.  i.e.:

```vb
<book>blah
    blah blah blah
    blah blah blah</book>
```

We can't assume the end of the block will always be to the left of things.  In that case we'd want that to be:

```vb
<book>blah
|    blah blah blah
|    blah blah blah</book>
```

**Comment by gundermanc** [comment] 2018-10-11 00:51
> That would be awesome.

I'll try to change this for 16.0 P2. Note that being a platform change, there is inherent risk that we'll regress all of the rest of our partners by changing behaviors that many teams have come to depend on.

>I would definitely like to never be in the job of not having to do that sort of thing :-) IMO, it's much cleaner for the languages to speak in terms of language concepts, and just have the final presentation system make these determinations.

The problem here is that there is no language concept that defines clearly where the guide should be aligned. With curly brace languages in particular, the desired behavior is very much a function of code formatting, which we as a platform have no way of knowing, hence the explicit positioning baked into the API.

The language knowing about presentation concepts is nothing new. Roslyn's block tags today contain a hosted ITextView. I was responsible for killing a similar feature in Quick Info and it was met with very strong pushback. I wonder what is the difference in simply adding a condition to pick one of two points in a span?

**Comment by CyrusNajmabadi** [comment] 2018-10-11 02:17
> Roslyn's block tags today contain a hosted ITextView. I was responsible for killing a similar feature in Quick Info and it was met with very strong pushback.

I'm not sure what the pushback in QuickInfo was for.  I'd be hugely supportive of the editor doing this :)  

It seems like a great thing to support.  Indeed, we regressed this recently because of some new feature where we can't just show the user real source code in QI windown and instead have to simulate it by stringing together colorized bits of text.  IIRC, this was done for some new VS collaborative feature.  I know i wasn't happy that this regressed, and i would be thrilled if the editor could bring this back with native support! :)

**Comment by CyrusNajmabadi** [comment] 2018-10-11 02:18
> I'll try to change this for 16.0 P2. Note that being a platform change, there is inherent risk that we'll regress all of the rest of our partners by changing behaviors that many teams have come to depend on.

Thanks so much.  If that's a concern, perhaps this could be an opt-in option to the API?

**Comment by CyrusNajmabadi** [comment] 2018-10-11 02:58
@gundermanc I tried to even see how the guideLineHorizontalAnchor value might work.  Even when i hardcode it in as some left-most column (in this case column 9), i still get the wrong output:

![image](https://user-images.githubusercontent.com/4564579/46778079-e0171480-ccc6-11e8-8c41-55791349a8ff.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-11 03:18
Oh wait.  I thought this was in column coordinates.  Maybe it's just a random point in the file?

**Comment by gundermanc** [comment] 2018-10-11 16:42
Yep, it's a point in the current snapshot. Try giving the same point that you used for OutliningSpan.End and see what happens.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:19
Closing out as this is not an issue with Roslyn, but an issue with the editor (which has the data, and the information about the view to make this determination).  I closed another issue on this today @olegtk .  Up to you guys on what you'd want to do here.

**Closed by CyrusNajmabadi** 2024-11-06 02:19 UTC
Labels: Bug, Area-IDE
