### ISSUE TITLE
Naming Rules should not apply to Main()

### ISSUE THREAD

**Issue by Foxtrek64** [dotnet/roslyn#43677] opened 2020-04-25 06:39 UTC
**Version Used**: 16.5.4 (VS version)

I have a custom naming rule that targets async methods and applies a rule that says they must have an "Async" suffix.

This custom rule works great and gently reminds me to name async methods according to our design specifications. However, this rule is also applied to `Program.Main()`. This can be bypassed by manually suppressing the rule, but I feel like the `Main()` method should be exempt from all naming rules. We already have a similar exemption in place for interface implementations, recognizing that the names of these methods are similarly outside of the user's control.

**Comment by jasonmalinowski** [comment] 2020-05-05 00:15
The question that was brought to design review was if we should be precise and check only for the Main() method that's actually the entry point, or just match on any method that _could_ be the entry point. @mavasani mentioned we have other analyzers that have to do similar tests. We concluded that if there's a usable API for the actual entrypoint and it's easy to do let's do that, if not we'll just match on any potential Main() method.

**Comment by sharwell** [comment] 2020-08-18 19:36
Duplicate of #36385

**Closed by sharwell** 2020-08-18 19:36 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-CodeStyle
