### ISSUE TITLE
IDE0046 suggestion: option to ignore else-if statements

### ISSUE THREAD

**Issue by Drake53** [dotnet/roslyn#69312] opened 2023-08-01 16:30 UTC
Consider the following code:
```csharp
if (expr1)
{
    return Foo1();
}
else if (expr2)
{
    return Foo2();
}
else if (expr3)
{
    return Foo3();
}
else
{
    return Bar();
}
```

IDE0046 will tell me to turn the last (else)if-else statement into a conditional expression:
```csharp
if (expr1)
{
    return Foo1();
}
else if (expr2)
{
    return Foo2();
}
else
{
    return expr3 ? Foo3() : Bar();
}
```

A single conditional expression is still readable, however the rule will now fire recursively until the entire if-elseif-elseif has been converted into conditional expressions:
```csharp
return expr1 ? Foo1() : expr2 ? Foo2() : expr3 ? Foo3() : Bar();
```

In this situation I'd prefer if the rule would simply ignore this code.

**Comment by cremor** [comment] 2024-05-07 09:48
I think this is a duplicate of #59135

**Comment by Farenheith** [comment] 2024-05-23 12:23
I agree with adding an option. In #59135 it fell on a personal preference discussion, but I think it should be looked at a team guideline view:
* If the team defines that in this case, we should use if/else, it'd be nice to enforce it through linting;
* If the team defines it should be ternary, then, enforcing it it'd also be nice.

Having all the team following the same style greatly improve code review quality, as the code changes tend to be less spamming,

**Comment by CyrusNajmabadi** [comment] 2024-11-23 04:38
Closing as dupe of https://github.com/dotnet/roslyn/issues/59135.

**Closed by CyrusNajmabadi** 2024-11-23 04:38 UTC
Labels: Area-IDE, Feature Request
