### ISSUE TITLE
csharp_style_var_when_type_is_apparent breaks when awaiting a generic type

### ISSUE THREAD

**Issue by mslukebo** [dotnet/roslyn#64902] opened 2022-10-21 21:39 UTC
**Version Used**:  net6.0, netcoreapp3.1

**Summary**:

When specifying `csharp_style_var_when_type_is_apparent: true`, the formatter thinks `await Task.Run(() => SomeMethodThatReturnsAGenericallyTypedResult())`'s type is "apparent" and `await`ing the value forces you to use `var`

**Steps to Reproduce**:

1. Create a new solution and add an `.editorconfig` whose content is
```
[*.cs]
csharp_style_var_when_type_is_apparent = true:warning
```

2. In `Program.cs`, paste the following code:
```cs
using System.Collections.Generic;
using System.Threading.Tasks;

public class Program
{
    public static async Task Main()
    {
        object test1 = DoSomeWork();
        object test2 = await Task.Run(() => DoSomeWork());

        IEnumerable<object> test3 = DoSomeWorkGeneric();
        IEnumerable<object> test4 = await Task.Run(() => DoSomeWorkGeneric());
    }

    public static object DoSomeWork()
    {
        return new object();
    }

    public static IEnumerable<object> DoSomeWorkGeneric()
    {
        return new List<object>();
    }
}
```

**Expected Behavior**:

All four of the variables should require specifying the type, yielding no warnings in the above code.

**Actual Behavior**:

 `test4`'s type has a warning that says it should use `var`:

![image](https://user-images.githubusercontent.com/68865158/197292025-bc8f7277-080c-48fd-9258-a27397a3faae.png)

**Comment by jasonmalinowski** [comment] 2022-11-02 18:01
@CyrusNajmabadi @sharwell Before I triage out: does this request match your expectation for what "is apparent" is supposed to do here? I know it's not as well specced as we'd like...

**Comment by CyrusNajmabadi** [comment] 2022-11-02 18:17
Neither of these cases seem apparant to me.  THere's nothing on the RHS that makes me understand what the type should be.

**Comment by jasonmalinowski** [comment] 2022-11-02 18:30
@CyrusNajmabadi That was my thought, but wasn't sure if there was some funky logic here.

**Comment by CyrusNajmabadi** [comment] 2024-11-30 03:31
Closing out as by design.  These cases are not apparent.

**Comment by mslukebo** [comment] 2024-12-02 16:13
@CyrusNajmabadi  closing this as "by design" because "these cases are not apparent" appears like a misunderstanding of the bug report.

It is agreed that all 4 cases are "not apparent." The issue is the linter **thinks** `test4` **is** apparent, and wants you to use `var`.

**Closed** 2024-12-03 15:42 UTC
Labels: Area-IDE
