### ISSUE TITLE
Visual Studio should take global using directives (e.g. ImplicitUsings) into account when creating new C# files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60912] opened 2022-04-22 19:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-should-take-ImplicitUsings/10020348)._

---
[severity:It bothers me. A fix would be nice]
0

I have a C# 10 project with  enabled:
 
```
10
    enable
```

With this in place, VS will gray-out many common namespaces in code files and offer to remove them.

However, when I create a new C# file it still imports all of the now-unnecessary using statements by default:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyNamespace
{
    internal class Class1
    {
    }
}
```

The new file should omit the unnecessary using statements so I don't have to go in and remove them each time.

---
#### Feedback Bot on 4/22/2022, 02:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-04-22 21:02
This is not Roslyn. This is the sdk and templates.

**Comment by Youssef1313** [comment] 2022-04-23 15:56
@CyrusNajmabadi Wouldn't that be handled by `INewDocumentFormattingService`?

**Comment by CyrusNajmabadi** [comment] 2022-04-23 16:39
I don't believe so, no.  I don't think INewDOcumentFormattingService would know anything about things like global usings.   It runs at a time when those may not exist at all.  It's much more about stylistic things (like matching formatting).

**Comment by Youssef1313** [comment] 2022-04-23 16:44
I thought the new document service (or any other part of the IDE) can do that once https://github.com/dotnet/roslyn/issues/59088 is fixed.

Also this looks like a duplicate of https://github.com/dotnet/roslyn/issues/59922 (found #59922 linked to #59088 when looking through it)

**Comment by CyrusNajmabadi** [comment] 2022-04-23 16:57
I don't believe so.  At the point of doing things like making a nwe project, we may be told about those files prior to even knowing that things like global-using exist.  Another way to think about it is that hte global-using file may get added asynchronously afterwards.

**Comment by CyrusNajmabadi** [comment] 2022-04-23 16:57
Indeed.  Clsing as dupe of https://github.com/dotnet/roslyn/issues/59922

**Closed by CyrusNajmabadi** 2022-04-23 16:57 UTC
Labels: Area-IDE, untriaged
