### ISSUE TITLE
DebuggerDisplay is ineffective in Dictionary<TKey, TValue>

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#28938] opened 2018-07-30 09:35 UTC
**Version Used**: VS2017 15.7.5

**Steps to Reproduce**:

1. Type codes:
```C#
class Program
{
    static void Main()
    {
        Data dat = new Data("demo", 3);
        List<Data> list = new List<Data> { dat };
        Dictionary<Data, Data> dic = new Dictionary<Data, Data>() { { dat, dat } };
    }
}
[DebuggerDisplay("{Text}")]
class Data
{
    public Data(string text, int num)
    {
        Text = text;
        Num = num;
    }

    public string Text { get; set; }

    public int Num { get; set; }

    public override string ToString()
    {
        return Num.ToString();
    }
}
```
2. Debug it and break in the end of 'Main'

**Expected Behavior**: Always show 'demo'

**Actual Behavior**: show '3' in 'dic'

**Comment by sharwell** [comment] 2018-07-31 16:46
Duplicate of #24670

**Closed by sharwell** 2018-07-31 16:46 UTC
Labels: Area-Interactive, Interactive-Debugging
