### ISSUE TITLE
Endless popup error messages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70025] opened 2023-09-19 21:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Endless-popup-error-messages/10451603)._

---
[severity:It's more difficult to complete my work]
While typing get popup error messages continually making visual studio really annoying to use.
Here is the latest one's stack dump.

```
StreamJsonRpc.RemoteInvocationException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__21.MoveNext()
RPC server exception:
System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
      at Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(Document document, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ComputeDesignerAttributeCategoryAsync(Boolean hasDesignerCategoryType, Project project, DocumentId documentId, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.<>c__DisplayClass9_0.<<ComputeChangedDataAsync>g__ComputeDesignerAttributeDataAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ComputeChangedDataAsync(Project project, Document specificDocument, AsyncLazy`1 lazyProjectVersion, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ScanForDesignerCategoryUsageAsync(Project project, Document specificDocument, ICallback callback, AsyncLazy`1 lazyProjectVersion, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ProcessProjectAsync(Project project, Document specificDocument, Boolean useFrozenSnapshots, ICallback callback, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ProcessSolutionAsync(Solution solution, DocumentId priorityDocumentId, Boolean useFrozenSnapshots, ICallback callback, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync(Func`2 implementation, CancellationToken cancellationToken)
```

---
#### Feedback Bot on 8/28/2023, 11:37 PM: 

(private comment, text removed)
#### Feedback Bot on 9/19/2023, 02:42 PM: 

(private comment, text removed)

---
#### Feedback Bot solved on 8/29/2023, 00:31 AM, 0 votes: 

<p>Thanks for taking the time to report this issue! It seems to us that it’s describing the same thing as <a target='_blank' href="https://developercommunity.visualstudio.com/t/Continual-error-popups-making-VS-unusabl/10451611">another one</a>. We’ve closed this one as a duplicate and transferred all votes from this ticket to the other one. Please follow along on the linked ticket to communicate with the team, see updates on status, and help provide any needed diagnostic info. For more information, see our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

**Comment by mavasani** [comment] 2023-11-02 10:47
Duplicate of #67442

**Closed by mavasani** 2023-11-02 10:47 UTC
Labels: Area-Analyzers
