### ISSUE TITLE
Proposal: allow anonymous types to implement interfaces

### ISSUE THREAD

**Issue by claq2** [dotnet/roslyn#2016] opened 2015-04-15 17:58 UTC
The most immediate benefit would be for unit testing. For a simple DTO-type interface, i.e. only containing properties, I would like to type something like:

    var dto = new { FirstName = "Joey", LastName = "Shabadoo", Valid = true} : IPersonDto;
    var person = new Person(dto); // Person's cctor takes an IPersonDto
    Assert.That(person.FullName, Is.EqualTo("Joey Shabadoo");
or

    Save(dto); // Checks Valid property

then it would save a few lines of setting up a mock or creating a test class.

The anonymous type would only implement the getters of the interface's properties even if they are writable. Compilation would still fail if you try to set values on the anonymous type, and throw an exception if you try to set values using a reference to the interface.

**Comment by svick** [comment] 2015-04-15 18:02
This is a duplicate of #13, only with different syntax.

**Comment by dsaf** [comment] 2015-08-27 12:40
Specifying the implemented interface in the very end is definitely not in C# spirit.

**Closed** 2015-09-13 02:54 UTC
Labels: Area-Language Design, Feature Request, Resolution-Duplicate
