### ISSUE TITLE
'ExtractMethodCodeRefactoringProvider' encountered an error and has been disabled when selecting a line

### ISSUE THREAD

**Issue by mihemihe** [dotnet/roslyn#23880] opened 2017-12-20 20:35 UTC
**Version Used**: 
The one shipped with Visual Studio 15.5.2

**Steps to Reproduce**:

Just hanging around a switch case (byte) with hundreds of cases. It happens when I go to the end of a line, and I shift + Home to select the entire line. 

 This is an excerpt:

 				case 0x70: return $"MOV    M,B";
                case 0x71: return $"MOV    M,C";
                case 0x72: return $"MOV    M,D";
                case 0x73: return $"MOV    M,E";
                case 0x74: return $"MOV    M,H";
                case 0x75: return $"MOV    M,L";
                case 0x76: return $"HLT";
                case 0x77: return $"MOV    M,A";
                case 0x78: return $"MOV    A,B";
                case 0x79: return $"MOV    A,C";
                case 0x7A: return $"MOV    A,D";
                case 0x7B: return $"MOV    A,E";
                case 0x7C: return $"MOV    A,H";
                case 0x7D: return $"MOV    A,L";
                case 0x7E: return $"MOV    A,M";
                case 0x7F: return $"MOV    A,A";
                case 0x80: return $"ADD    B";
                case 0x82: return $"ADD    D";
                case 0x83: return $"ADD    E";
                case 0x85: return $"ADD    L";
                case 0x86: return $"ADD    M";
                case 0x87: return $"ADD    A";

I get a toast notification:

'ExtractMethodCodeRefactoringProvider' encountered an error and has been disabled.

This is the stack trace:
System.InvalidOperationException : Matrix does not contain Key 'C7'.
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

There is a copy of the file here:

https://github.com/mihemihe/mihemulator8080/blob/master/mihemulator8080/InstructionFetcher.cs

I have just pushed a failing version in a commit with notes "Issue Roslyn"

**Comment by jinujoseph** [comment] 2018-01-08 19:07
dupe of https://github.com/dotnet/roslyn/issues/23352

**Closed by jinujoseph** 2018-01-08 19:07 UTC
Labels: Area-IDE
