### ISSUE TITLE
Please add a Complexity Score above each method.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39787] opened 2019-11-12 21:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/800546/please-add-a-complexity-score-above-each-method.html)._

---
My company's development team struggles with knowing when to refactor code.  A complexity score above each method would help to identify when its time to evaluate refactoring.

To me a complexity score is nothing more than how many decision points there are in a given method.  

Take a look at this VS Code plugin that does this:
https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-codemetrics

I think this is probably simple enough for the Visual Studio team to make a part of their offering.  Or make it a plugin somehow.  

I think this would work if you were to put this right next to the reference counts.

So for example:

1 reference | **4 complexity** | Author, 30 days ago | 1 author, 1 change
public int MyFunction(){...}

I love the way the VS Code gives the developer the ability to customize the parameters as well.  To take it further, it would be great for a team lead to define it team wide as well.

Complexity is our organizations #1 issue and tools like this go a long way to help.

---
#### Visual Studio Feedback System on 10/31/2019, 07:41 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mavasani** [comment] 2019-11-12 22:38
I believe this is already supported through [Code Metrics](https://docs.microsoft.com/visualstudio/code-quality/code-metrics-values).

There are 3 different ways you can compute, view and/or enforce code metrics. See https://docs.microsoft.com/visualstudio/code-quality/how-to-generate-code-metrics-data for details.

**Comment by mavasani** [comment] 2020-01-06 19:29
Design meeting notes:

Conclusion: We already have CodeMetrics support from VS and command line: https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019. Point customer to the above documentation. Check if this suffices for them. Otherwise they can potentially write their own CodeLens extension.

**Comment by irperez** [comment] 2020-11-21 16:50
I believe I was the one who gave this feedback.  I do realize we have code metrics tools.  The problem is those values are not in the face of our developers.  They won't go out of their way to run this tool.

What I wanted was that the complexity value gets calculated for them on top of each method like below:
1 reference | **4 complexity** | Author, 30 days ago | 1 author, 1 change
public int MyFunction(){...}

Think of this as eagerly loading that complexity instead of the developer fetching the complexity by demand.

**Comment by ploeh** [comment] 2021-11-24 08:58
I agree with @irperez. This needs to be immediately visible information, which is also the reason I created #49579. The fact that you can run the tool doesn't help, because after running the tool, you then have to dig through its output to find the method you're currently looking at.

We're talking [nudging](https://en.wikipedia.org/wiki/Nudge_theory), here.

**Comment by CyrusNajmabadi** [comment] 2022-11-01 18:38
Dupe of https://github.com/dotnet/roslyn/issues/49579.

**Comment by CyrusNajmabadi** [comment] 2022-11-01 18:38
Closing out.  This is out of scope for roslyn.  Other tools can do this.  If the results are not ideal, that should be taken up with those teams.

**Closed by CyrusNajmabadi** 2022-11-01 18:38 UTC
Labels: Area-Analyzers, Resolution-By Design, Feature Request, Developer Community
