### ISSUE TITLE
C#9 method with function pointer parameter generate invalid xml documentation

### ISSUE THREAD

**Issue by Doraku** [dotnet/roslyn#49285] opened 2020-11-11 16:24 UTC
Hopefully this is the right place for such issue as I see similar issues about xml documentation generation.

**Version Used**: Microsoft Visual Studio Community 2019 16.8.0

**Steps to Reproduce**:
Add a method with a function pointer parameter in a project which generate xml documentation
```
namespace Dummy
{
    public class DummyClass
    {
        /// <summary>
        /// dummy method with function pointer parameter
        /// </summary>
        /// <param name="_">dummy</param>
        /// <param name="function">dummy</param>
        public unsafe void DummyMethodFunctionPointer(int _, delegate*<void> function) => function();
    }
}
```

**Expected Behavior**: 
Generate the correct name in the xml documentation file
```
        <member name="M:Dummy.DummyClass.DummyMethodFunctionPointer(System.Int32,delegate*)">
            <summary>
            dummy method with function pointer parameter
            </summary>
            <param name="_">dummy</param>
            <param name="function">dummy</param>
        </member>
```

**Actual Behavior**:
Note the missing function pointer parameter
```
        <member name="M:Dummy.DummyClass.DummyMethodFunctionPointer(System.Int32,)">
            <summary>
            dummy method with function pointer parameter
            </summary>
            <param name="_">dummy</param>
            <param name="function">dummy</param>
        </member>
```

**Comment by jinujoseph** [comment] 2020-11-17 21:18
Duplicate of #46674

**Closed by jinujoseph** 2020-11-17 21:18 UTC
