### ISSUE TITLE
Roslyn build Restore.cmd fails if a parent directory name contains $ character

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#32044] opened 2018-12-28 22:10 UTC
**Version Used**: 
e4a4a214aa0b0f79c87384e26b8e9ef07d7bb181

**Steps to Reproduce**:

1. Clone Roslyn into a directory that contains `$`, in my case `$TC` 
2. Run .\Restore.cmd

**Expected Behavior**:
Restore works.

**Actual Behavior**:
`$TC` is interpreted as a variable name and is substituted with an empty value:
```
& : The term 'D:\\work\142fd509662c8cdc\!roslyn\sources\dotnet\eng\build.ps1' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:3
+ & "D:\$TC\work\142fd509662c8cdc\!roslyn\sources\dotnet\eng\build.ps1" ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\\work\142fd5...t\eng\build.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Potential Fix**:
Change interpolating quotes `"` to non-interpolating `'`:
```
powershell -ExecutionPolicy ByPass -NoProfile -command "& '%~dp0eng\build.ps1' -restore %*"
```

**Comment by jaredpar** [comment] 2019-01-01 21:20
Thanks for reporting. This is a duplicate of #20929

**Closed by jaredpar** 2019-01-01 21:20 UTC
Labels: Area-Infrastructure
