### ISSUE TITLE
Error List in VS is not updated for VB code, squiggles are not displayed

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#49542] opened 2020-11-21 15:30 UTC
When I am working in Roslyn solution in VB code, error list is not updated based on the edits. Old errors that already were fixed are displayed, new errors are not displayed. Explicitly building/re-building project doesn't help. Often, in those rare cases when I am lucky and expected errors are displayed in the error list, squiggles are not displayed at the expected locations. This makes almost impossible to write code in VB. I am using 16.9.0 Preview 2.0 [30709.259.main].

**Comment by paul1956** [comment] 2020-11-21 23:23
This started in Preview 1, the errors only show up in Output Window. Warnings cause by violations from editorConfig are also not displayed until the file with the issue is opened, don't know if this is related or a separate issue.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 17:50
Closing out as these components were entirely removed/replaced

**Closed by CyrusNajmabadi** 2024-10-22 17:50 UTC
Labels: Bug, Area-IDE
