### ISSUE TITLE
IDE0044 'Add readonly modifier' reported on field exposed by reference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36758] opened 2019-06-25 22:08 UTC
VSF_TYPE_MARKDOWNWhen implementing a ref property, Visual Studio 16.1.3 suggests adding the readonly modifier to the backing field:

```
class Foo
{
    private int _bar; // IDE0044 Add readonly modifier
    public ref int Bar => ref _bar;
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/617707/ide0044-add-readonly-modifier-reported-on-field-ex.html
VSTS ticketId: 935990_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 01:19 AM (37 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-07-02 18:11
Duplicate of #33009

**Closed by jinujoseph** 2019-07-02 18:11 UTC
Labels: Area-IDE, Resolution-Duplicate
