### ISSUE TITLE
Add GetInteriorSymbols API for IMethodSymbols

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11349] opened 2016-05-16 22:48 UTC
There is no good way to get interior symbols on a method symbol today.  Its currently impossible for completion to do it performantly with out a speculative SemanticModel

Notes: https://github.com/dotnet/roslyn/issues/11193

**Comment by rchande** [comment] 2016-05-18 17:40
Worked around in https://github.com/dotnet/roslyn/pull/11398/

**Comment by gafter** [comment] 2016-08-10 16:53
By design, the interior symbols of a symbol are only stable within a particular `SemanticModel`. So this would have to be an API on the `SemanticModel` of the enclosing symbol.

It is not just for method symbols. Even a field's initializer can declare locals (out variables or pattern variables).

**Comment by CyrusNajmabadi** [comment] 2022-10-28 20:12
Not sure what the driving scenario is for this.  Even if the compiler added this, i'm not sure where we'd use this or how we'd measure that it benefitted us.  Closing out.

**Closed by CyrusNajmabadi** 2022-10-28 20:12 UTC
Labels: Concept-API, Area-Compilers, Feature Request
