### ISSUE TITLE
Visual Studio stops responding to keyboard input

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26284] opened 2018-04-20 15:21 UTC
Seemingly random, but in HTML markup, the IDE refuses input from the keyboard and mouse.  If I go out side the markup - at the bottom of the page it accepts input.  But if you go back to the markup it refuses to let you edit or create new markup.

In the attached recording the IDE did start taking input.   I had entered a number of returns and other random characters prior to the input returning to normal.

I would say the problem persists for about 5 to 10 minutes before returning to normal.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/237182/visual-studio-stops-responding-to-keyboard-input.html
VSTS ticketId: 603468_
_These are the original issue comments:_

Candy Zhang [MSFT] on ‎4‎/‎20‎/‎2018, 03:11 AM (7 hours ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-04-20 15:26
The performance trace shows the following assertion failing:
https://github.com/dotnet/roslyn/blob/f76e5ed82fd095ab6d5f489bc3fdf3b4f3b9f145/src/EditorFeatures/Core/Shared/Extensions/ITextViewExtensions.PerSubjectBufferProperty.cs#L32

```
+ microsoft.codeanalysis.workspaces.ni![COLD] Roslyn.Utilities.Contract.ThrowIfTrue(Boolean, System.String)
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextViewExtensions+PerSubjectBufferProperty`2[System.__Canon,System.__Canon].GetOrCreateValue(System.__Canon, Microsoft.VisualStudio.Text.ITextBuffer, System.Object, System.Func`3, System.__Canon ByRef)
+ microsoft.codeanalysis.editorfeatures.ni!Controller.GetInstance
+ microsoft.codeanalysis.editorfeatures.ni!AsyncCompletionService.TryGetController
+ microsoft.codeanalysis.editorfeatures.ni!AbstractCompletionCommandHandler.TryGetController
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.TryGetControllerCommandHandler[System.__Canon](System.__Canon, Microsoft.VisualStudio.Commanding.ICommandHandler ByRef)
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.GetCommandStateWorker[System.__Canon](System.__Canon, System.Func`1)
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.VisualStudio.Commanding.IChainedCommandHandler.GetCommandState(Microsoft.VisualStudio.Text.Editor.Commanding.Commands.ToggleCompletionModeCommandArgs, System.Func`1)
+ microsoft.visualstudio.text.ui.ni!Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.GetCommandState[System.__Canon](Microsoft.VisualStudio.Commanding.ICommandHandler, System.__Canon, System.Func`1)
+ microsoft.visualstudio.platform.vseditor.ni!Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass13_0`1[System.__Canon].<GetCommandState>b__0()
+ microsoft.visualstudio.editor.implementation.ni!Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.GetCommandState[System.__Canon](System.Func`3, System.Guid ByRef, UInt32, Microsoft.VisualStudio.OLE.Interop.OLECMD[], IntPtr)
+ microsoft.visualstudio.editor.implementation.ni!CommandHandlerServiceAdapter.QueryToggleCompletionModeStatus
+ microsoft.visualstudio.editor.implementation.ni!CommandHandlerServiceAdapter.QueryVisualStudio2000Status
+ microsoft.visualstudio.editor.implementation.ni!CommandHandlerServiceAdapter.QueryStatus
+ Microsoft.VisualStudio.LanguageServices!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget+<>c__DisplayClass106_0`1[System.__Canon].<GetCommandState>g__executeNextCommandTarget\|0()
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.GetCommandState[System.__Canon](System.Collections.Generic.IList`1>, System.__Canon, System.Func`1)
+ microsoft.codeanalysis.editorfeatures.ni!Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.GetCommandState[System.__Canon](Microsoft.VisualStudio.Utilities.IContentType, System.__Canon, System.Func`1)
+ Microsoft.VisualStudio.LanguageServices!AbstractOleCommandTarget.GetCommandState
+ Microsoft.VisualStudio.LanguageServices!AbstractOleCommandTarget.QueryToggleConsumeFirstModeStatus
+ Microsoft.VisualStudio.LanguageServices!AbstractOleCommandTarget.QueryVisualStudio2000Status
+ Microsoft.VisualStudio.LanguageServices!AbstractOleCommandTarget.QueryStatus
+ microsoft.visualstudio.web.html.implementation.ni!OleToCommandTargetShim.Status
+ Microsoft.Html.Editor!HtmlMainController.Status
+ microsoft.visualstudio.web.html.implementation.ni!CommandTargetToOleShim.QueryStatus
+ microsoft.visualstudio.editor.implementation.ni!CommandChainNode.InnerQueryStatus
+ microsoft.visualstudio.editor.implementation.ni!CommandChainNode.QueryStatus
+ JetBrains.Platform.VisualStudio.Core!IOleCommandTarget.QueryStatus
+ microsoft.visualstudio.editor.implementation.ni!CommandChainNode.InnerQueryStatus
+ microsoft.visualstudio.editor.implementation.ni!CompoundTextViewWindow.QueryStatus
+ microsoft.visualstudio.platform.windowmanagement.ni!DocumentObjectSite.QueryStatus
+ microsoft.visualstudio.platform.windowmanagement.ni!WindowFrame.QueryStatus
+ microsoft.visualstudio.ole.interop.ni!DomainBoundILStubClass.IL_STUB_COMtoCLR(IntPtr, Int32, IntPtr, Int32)
```

I also see some exceptions thrown in ReSharper code, but it's not clear whether or not that would impact this scenario.

**Comment by kaofishy** [comment] 2018-06-15 19:33
I have experienced the same issue but while editing C++ files. It's very random with no discernable cause. Every other application responds to keyboard input just fine, and restarting the IDE fixes the issue.

**Comment by anandtpatel** [comment] 2018-09-02 20:42
I had resharper installed. After uninstalling resharper and reboot VS. Now it working fine.

**Comment by mybadstudios** [comment] 2020-06-04 16:20
Still happening to me in VS 2019.. Jut happened again a few minutes ago. Anyone know why this is happening yet? I can solve the issue by just closing VS and restarting it but why is this happening? Is there some shortcut I can press to get input working again or should I just continue to turn VS "off and on again" ?

**Comment by AAdewunmi** [comment] 2021-02-09 17:15
I'm having the same problem with Visual Studio; it has stopped responding to keyboard input for my index.html file.

**Comment by AAdewunmi** [comment] 2021-02-10 08:28
I found a fix which works, perfectly.
The problem is caused by an installed extension.
Solution: Use 'Help: Start Extension Bisect' from Command Palette to try to identify the cause. 
<img width="289" alt="Screenshot 2021-02-10 at 08 10 00" src="https://user-images.githubusercontent.com/15172744/107484120-e3ae5500-6b79-11eb-8470-1988ca896387.png">

**Comment by CyrusNajmabadi** [comment] 2024-10-22 16:35
Closing out as reports indicate this is in different components/extensions from roslyn.  Would be good if the editor said which componet threw the exception and recovered, but this is out of bounds for us.

**Closed by CyrusNajmabadi** 2024-10-22 16:35 UTC
Labels: Area-IDE, Developer Community
