### ISSUE TITLE
[Test Failure] Build Timed Out in prtest/mac/dbg/unit32 on PR #6983

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7194] opened 2015-12-02 23:11 UTC
this is timeout on mono.

...

PR: [#6983](https://github.com/dotnet/roslyn/pull/6983) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/1605/

**Issue 1: Build Timed Out**
The build timed out, or was forcible aborted after reaching the maximum length. View the log right before the flagged timeout message to see what was happening.

**Comment by heejaechang** [comment] 2015-12-02 23:12
@davkean @jaredpar @amcasey I am not sure how I should investigate mono timeout. can someone provide me some pointer?

**Comment by jaredpar** [comment] 2015-12-02 23:26
This is a duplicate of #6407

**Closed by jaredpar** 2015-12-02 23:26 UTC
Labels: Area-Infrastructure, Contributor Pain
