### ISSUE TITLE
MemberSemanticModel.GetQueryEnclosingBinder needs serious overhaul 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10466] opened 2016-04-11 18:41 UTC
The logic in the function is fragile in error recovery cases and in some cases might use a binder from a wrong query lambda. For example, from the one preceding the binding failure if binder haven't reached the lambda we are asking for. In presence of match expressions, it becomes very important to get the binder from the right lambda because, if we fail to find a binder for a match case section, binding would crash. And we won't find the binder if we are dealing with a root binder for a different lambda. Perhaps the fix should involve some changes in the binding of query expressions, it should probably keep creating lambdas for query clauses even after an error has been encountered. Alternatively, semantic model should be smart enough to recover by creating the lambdas on the fly.

**Comment by gafter** [comment] 2016-04-12 03:10
Can you please provide a test case for this issue?

**Comment by AlekseyTs** [comment] 2016-04-12 03:32
If you change AdjustStartingNodeAccordingToNewRoot to do nothing, many tests will start failing, including those that are not pattern matching related. By debugging the test the problems should become apparent.

**Comment by AlekseyTs** [comment] 2016-04-12 03:35
Alternatively, you can revert changes made to MemberSemanticModel.GetQueryEnclosingBinder in https://github.com/dotnet/roslyn/pull/10348 and observe pattern matching test failures.

**Comment by AlekseyTs** [comment] 2016-06-17 18:54
A bunch of test for Out Variable Declarations also demonstrate the issue. The unit-tests are marked with this issue and the affected test code that had to be disabled has a comment referencing this issue.

**Comment by gafter** [comment] 2016-06-20 18:10
@AlekseyTs @jaredpar Not sure how you prioritized and assigned this.

**Comment by AlekseyTs** [comment] 2016-06-20 18:18
This looks looks like a preexisting problem with queries, SemanticModel cannot reliably locate a query lambda with the given position. Obviously, locating a binder for a nested scope would fail too. I tried to apply a quick patch, but it feels like the problem is more fundamental. I would suggest to assign this issue to a developer who added support for queries into the compiler because that developer would have the most context for addressing the issue. I believe that would be the most efficient way, given the time and resources constraints.

**Comment by AlekseyTs** [comment] 2016-06-21 05:21
Assigning to @jaredpar for prioritization and assignment to a dev.

**Comment by AlekseyTs** [comment] 2016-06-21 05:23
Initially this issue was opened in relation to pattern declarations.

**Comment by AlekseyTs** [comment] 2016-09-21 17:30
@jaredpar I am moving this bug to RC, per our offline discussion. I believe the fix for this issue won't be trivial. Note that there is a bunch of existing unit-tests for "Out Vars" and "Pattern Matching" affected by this bug. They are marked with a WorkItem attribute, but are not skipped. The affected validation code in the unit-tests is disabled and accompanied with a comment referring to this issue.

**Comment by gafter** [comment] 2016-09-30 01:22
There are a number of places in the tests that are marked with this issue. In many cases the tests are wrong. For example, in OutVarTests.cs method Scope_Query_05(), case `y1`: the code attempts to assert that `y1` is not a reference to an out variable, but the code declares both a local and a duplicate out variable by that name in that scope. Similarly for OutVarTests.cs method Scope_Query_05(), case `y3`.

In many other cases it appears that the behavior of the SemanticModel is correct, though perhaps not ideal from the user's point of view. This is an effect arising from the language specification's treatment of a degenerate final select clause, compounded by a particular kind of error arising in the programs that exhibit the "problem".

In the case of a final select clause that simply names the range variable, the final select clause is elided from being translated into a query, and the identifier is deemed to be bound to that name in the context of the preceding query clause.

For example, consider a query

```cs
from x in e
where M(x)
select x
```

Here the final `x` has no real semantic meaning in the program, according to the language specification. It is simply elided from the translation, and the query becomes `e.Where(x => M(x))`. For the purposes of the semantic model, we consider the `x` to be inside the lambda here, since that gives the closest to correct meaning.

Now consider an erroneous query that exhibits the problem reported herein

```cs
from x in e
where M(out var x)
select x
```

This is defined by the language specification as meaning `e.Where(x => M(out var x))`. Here the definition of the out variable `x` shadows the lambda parameter. So inside the lambda (which is where we interpret `x` to give it *some* meaning) the meaning of `x` is a reference to the out argument.

Tests that fail in this way can be modified to not run afoul of this specified behavior by changing the final select expression to something like `x+1`.

The tests that are marked as failing due to this issue will have to be analyzed one-by-one to determine the problem. It is clear that there are a number of unrelated problems in both the tests and possibly in the implementation as well. For each of them I'll either fix the issue or file a separate issue summarizing it.

**Comment by AlekseyTs** [comment] 2016-09-30 03:18
> For example, in OutVarTests.cs method Scope_Query_05(), case y1: the code attempts to assert that y1 is not a reference to an out variable, but the code declares both a local and a duplicate out variable by that name in that scope. Similarly for OutVarTests.cs method Scope_Query_05(), case y3.

The expectations of the test are correct and here is why. Both Out Variable Declarations are supposed to declare a local in the block that surrounds the query. However, locals with same names are already declared earlier in the block, this makes Out Var declaration duplicate in the same scope. In such cases a name reference always resolves to the declaration that is syntactically first. This is how binding works and this is how semantic model should behave, otherwise it would present a picture that is very different from what the compiler has. Locals might have different types, etc.
BTW, the test is passing now for these two cases, I'll make necessary changes to the test.

**Comment by gafter** [comment] 2016-09-30 19:56
@jaredpar Assigning back to you for now. Please let me know when you'd like to discuss the priority of this.

**Comment by AlekseyTs** [comment] 2016-09-30 21:12
I looked a little bit closer at some of the failing scenarios, a common theme is that, when information is extracted from bound nodes (GetSymbolInfo, for example), then SemanticModel gives expected information back. However, when information extraction involves finding the right Binder (LookupNames, LookupSymbols), the information is wrong. What makes things worse, different APIs return inconsistent information. GetSymbolInfo returns a symbol that LookupSymbols doesn’t return, etc. It appears that the query lambda is bound and is part of the bound tree, but MemberSemanticModel.GetQueryEnclosingBinder is simply failing to locate the lambda in order to get the Binder from it, however SemanticModel has no trouble locating bound nodes from that lambds by using standard way of getting them (GetBoundNodes internal API, or an equivalent).
 
MemberSemanticModel.GetQueryEnclosingBinder uses its own algorithm to locate a query lambda node. It probably would be worth investigating if usage of GetBoundNodes API instead could make it more robust.

**Comment by gafter** [comment] 2016-10-06 22:59
I suspect some of the cause of this is the interaction of the bound node cache with `BoundQueryClause.UnoptimizedForm`, which was designed to assist with `SemanticModel` behavior in the final `select` clause and certain `group by` clauses.

**Closed** 2016-12-15 15:38 UTC
Labels: 3 - Working, Area-Compilers, Bug, Language-C#, New Language Feature - Out Variable Declaration, New Language Feature - Pattern Matching
