### ISSUE TITLE
BasicWinForms.Change control property in code test is possibly flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10610] opened 2016-04-15 05:28 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/593/

Regression

BasicWinForms.Change control property in code (from (empty))

Failing for the past 1 build (Since Failed#593 )
Took 12 sec.
add description
Stacktrace

MESSAGE:
Exception has been thrown by the target of an invocation.
+++++++++++++++++++
STACK TRACE:
Server stack trace: at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(RemoteInvoker invoker, RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 105 at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(IRemoteUIThreadInvokerService invoker, RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 78 at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeOn(IRemoteUIThreadInvokerService invoker, Action action) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 52 at Microsoft.Test.Apex.Hosts.MarshallableApexObject.UIInvoke(Action action) in f:\dd\src\Omni\Apex\Framework\Hosts\MarshallableApexObject.cs:line 425 at Roslyn.VSHosting.Test.InProcessAPI.PlaceCaret(String marker, Int32 charsOffset, Int32 occurrence, Boolean extendSelection, Boolean selectBlock) in d:\j\workspace\dotnet_roslyn---a1c78f15\Closed\Hosting\Test\Actions\VisualStudio\Utilities\InProcessAPI.cs:line 94 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Roslyn.VSHosting.Test.InProcessAPI.PlaceCaret(String marker, Int32 charsOffset, Int32 occurrence, Boolean extendSelection, Boolean selectBlock) at Roslyn.VSHosting.Test.PlaceCursorAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---a1c78f15\Closed\Hosting\Test\Actions\VisualStudio\PlaceCursorAction.cs:line 41 at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139 at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36

**Comment by Pilchie** [comment] 2016-04-15 16:56
Dupe of https://github.com/dotnet/roslyn/issues/7643 (they both hit the same issue).

**Closed by Pilchie** 2016-04-15 16:56 UTC
Labels: Area-IDE, Language-VB, Test
