### ISSUE TITLE
Exclude folder from namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58678] opened 2022-01-06 21:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Exclude-folder-from-namespace/1615150)._

---
I have folder and when create new class and not include that folder in namespace.
It is impossible with Resharper but I am not using Resharper in Visual Studio and I think I think developers like me are a lot.

---
#### Feedback Bot on 12/16/2021, 00:15 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by eMuonTau** [comment] 2022-05-26 11:53
Duplicate of #45494

**Comment by PPenglis** [comment] 2022-09-25 20:45
It would be good to allow this to be disabled but there is also a mixed case, Maybe you want to create a namespace with subfolders. 

Project/    {RootNamespace}
Project/Library/   {RootNamespace.Library}
Project/Library/GroupOfClasses1 {RootNamespace.Library}
Project/Library/GroupOfClasses2 {RootNamespace.Library}

Depending if this per folder setting is actually stored or not. If its not:
If you are adding a new source file to a folder VS should respect existing classes in that folder. If every class is part of the namespace make it follow the folder pattern.
If it is not and just used as a folder VS should just use the parent namespace. 
In the folders properties we should be able to see how Visualstudio is treating the folder.
When we compile it should come up with a warning if there is mixed used. for the previous cases where files were added to new namespaces but not wasn't intended and the rest of the project was not. 

If the setting is stored, central file in the project folder that includes or excludes folders from including their namespace. 
Then each folder can be explicitly included or excluded from the naming convention. 
The folder icons in VS should show this difference.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 04:46
Closing due to lack of broader feedback on this topic.

**Closed by CyrusNajmabadi** 2024-10-25 04:46 UTC
Labels: Area-IDE, Feature Request, Developer Community, Need Design Review
