### ISSUE TITLE
Incorrect 'IDE0004 cast is redundant' which offers a meaningless fix

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#21960] opened 2017-09-07 11:45 UTC
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02053
```

**Steps to Reproduce**:

Paste the following code into VS:
```cs
static class Program
{
  static void Main(string[] args)
  {
    switch ((int?)default)
    {
      default:
        break;
    }
  }
}
```

**Expected Behavior**:
No 'IDE0004 cast is redundant' warning as it obviously isn't redundant.

**Actual Behavior**:
`(int?)` cast is marked as redundant but the offered fix just adds parentheses around default literal. 

I don't see how the parentheses  could affect cast redundancy but Roslyn indeed doesn't think that the cast is redundant if the default literal is wrapped with parentheses.

![image](https://user-images.githubusercontent.com/5566206/30161751-9010977a-93da-11e7-89da-c694c28c5d4f.png)

**Comment by dpoeschl** [comment] 2017-09-18 17:09
I don't see the same thing happening in other contexts, like `var x = (int?)default;`.  However, there is a weird parentheses simplification problem happening in other contexts too. Removing the unnecessary cast in `var str = ""; if (str == (string)default) { }` leaves the remaining `(default)` in parentheses.

**Comment by DustinCampbell** [comment] 2017-09-18 19:02
I'm thinking about poaching this if that's OK.

**Comment by sharwell** [comment] 2017-09-18 19:16
@DustinCampbell Everything assigned to me but marked **up-for-grabs** is poachable 👍

**Comment by DustinCampbell** [comment] 2017-09-18 19:18
snatched away

**Comment by DustinCampbell** [comment] 2017-09-18 22:02
FWIW, the problem is specific to the switch expression. The code that detects whether a cast can be removed considers the "outer" type of the cast expression -- that is, the type of the context that the cast expression is contained within. For a switch statement expression, that should be null, as in "no type". However, the redundant cast detection code does something a [bit cheesy](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs#L368):

```C#
var outerType = GetOuterCastType(cast, semanticModel, out var parentIsOrAsExpression) ?? castTypeInfo.ConvertedType;
```

So, `outerType` ends up being the type of the cast (i.e. `System.Int32?`) rather than `null`. So, the logic afterward assumes that it's an identity cast.

**Comment by DustinCampbell** [comment] 2017-09-18 22:44
Sigh... this whole mess needs rewritten. :-S

**Comment by CyrusNajmabadi** [comment] 2020-04-27 02:51
Duple of https://github.com/dotnet/roslyn/issues/20211

**Closed by CyrusNajmabadi** 2020-04-27 02:51 UTC
Labels: Area-IDE, Bug, help wanted
