### ISSUE TITLE
?. infers non-nullable struct

### ISSUE THREAD

**Issue by Forgind** [dotnet/roslyn#70842] opened 2023-11-15 20:19 UTC
**Version Used**: 

**Steps to Reproduce**:

1. Create a C# file with this code:
<img width="214" alt="image" src="https://github.com/dotnet/roslyn/assets/12969783/d520835b-4c4c-499b-95f0-fe24071604ec">

**Expected Behavior**:
t?.f?.s should behave the same as putting t?.f in q then calling q?.s. Specifically, they should both be valid.

**Actual Behavior**:
<img width="324" alt="image" src="https://github.com/dotnet/roslyn/assets/12969783/3801b607-efe0-4121-8fc0-01416aeb5a85">

**Comment by CyrusNajmabadi** [comment] 2023-11-15 20:41
Closing out as by design.   `.f?.s`  is what is evaluated if `t` is not null.  That evaluation grabs `f` off of the non-null `t`, which returns just a struct instance.  It's not legal (or desired to be legal) to then call `?.s` on a struct.  Structs can't be null, so it's properly an error if someone tries to use the null-prop operator on them.

Note: when you break up the lines you're getting entirely different semantics from what `t?.f?.s` means.  The semantcs of the the later lines are the same as if you had written: `(t?.f)?.s`.  And, in that case, you'll note that the second `?.` is now legal.  That's because you're now saying "access 'f' off of 't' if 't' is non-null.  otherwise give me null".  And that's what the `(...)` evaluates out to.  Since you can get `null` there, allowing `?.s`  off of it is legal.

**Closed by CyrusNajmabadi** 2023-11-15 20:41 UTC
Labels: Area-Compilers, untriaged
