### ISSUE TITLE
"Fix all in solution" will only fix up projects with the same language as the project the fix was invoked in.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15201] opened 2016-11-13 00:47 UTC
Issue seems to be with this code:

FixAllContext.DiagnosticProvider.cs
```c#
                            projectsToFix = project.Solution.Projects
                                .Where(p => p.Language == project.Language)
                                .ToImmutableArray();
```

**Comment by CyrusNajmabadi** [comment] 2016-11-13 00:48
@mavasani Do you know why this is?  This prevents cross language fixing across VB and C#.

**Comment by mavasani** [comment] 2016-11-13 01:26
This has always been the design of fix all. I think there was an issue listing the difficulties of cross language fix all, let me try to find that one for you.

**Comment by mavasani** [comment] 2016-11-13 01:43
https://github.com/dotnet/roslyn/issues/1011.
I think there was another backlog item in our pre-github days in Devdiv2 server which probably had the details, this issue just mentions this as a missing feature.

**Comment by CyrusNajmabadi** [comment] 2016-11-13 03:22
Hrmm... i'm not sure i'm seeing what the difficulty would be :)   But maybe this was before we did so much work to unify things across VB/C#.  I'll see about enabling this soon :)

**Comment by Pilchie** [comment] 2016-11-14 23:56
If this is easy, go for it, but otherwise I don't think it's that high priority.  AFAIK, this is the first time anyone has ever even noticed.

**Comment by CyrusNajmabadi** [comment] 2017-04-10 16:05
Something for you to noodle on as you look at Fix-all.

**Comment by Pilchie** [comment] 2017-04-10 16:06
Note - I think we can continue to live with this for 15.3.

**Comment by jrmoreno1** [comment] 2020-05-28 20:40
I may be the only person since Cyrus to try this, but I just spent a fair amount of time trying to figure out where I had gone wrong, as I took the "Solution" button at it's word.

**Comment by jrmoreno1** [comment] 2020-06-01 01:22
This does seem to be roughly as simple as @CyrusNajmabadi  indicated, I have it working by just removing some code from FixAllContext and FixAllContextHelper, need to figure out if I can fix the UI (shows C# or VB depending upon the initial project, although the changes are solution wide)

**Comment by jrmoreno1** [comment] 2020-06-01 03:49
I can have the UI to show a open file glyph instead of the VB or C#  glyph it currently shows.

**Comment by jrmoreno1** [comment] 2020-06-06 21:42
the preview for suppression just doesn't pass in the language, guess that would be the thing to do.

**Comment by sharwell** [comment] 2020-08-12 19:05
Duplicate of #1011

**Closed by sharwell** 2020-08-12 19:05 UTC
Labels: Area-IDE, Feature Request, help wanted
