### ISSUE TITLE
nameof in attribute produces empty string

### ISSUE THREAD

**Issue by jl0pd** [dotnet/roslyn#52013] opened 2021-03-20 03:33 UTC
**Version Used**: 
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.113 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
```
**Steps to Reproduce**:

1.  Create source generator that adds property
2.  Create test that will have attribute referencing generated property via `nameof`
3. Inspect `AttributeData.ConstructorArguments`

**Expected Behavior**:

Arguments have property name in form `MemberNotNullAttribute("GeneratedProp")`

**Actual Behavior**:

Argument is an empty string `MemberNotNullAttribute("")`

**Sample**

Repo with complete example https://github.com/jl0pd/RoslynSourceGeneratorNameof

Sample class
```csharp
using System.Diagnostics.CodeAnalysis;
public partial class MyClass
{
    [MemberNotNull(nameof(GeneratedProp))]
    void Foo()
    {}

    public static void Main() {}
}
```

Source generator code, [link](https://github.com/jl0pd/RoslynSourceGeneratorNameof/blob/9837fc58b76a561023170342c01d846aa58035fa/RoslynSourceGeneratorNameof/MyBuggyGenerator.cs#L41)
```csharp
if (method.GetAttributes().FirstOrDefault(ad => SymbolEqualityComparer.Default.Equals(ad.AttributeClass, notNull)) is AttributeData ad)
{
    ImmutableArray<TypedConstant> args =  ad.ConstructorArguments; // actual {System.Diagnostics.CodeAnalysis.MemberNotNullAttribute("")}
    if (args[0].Value is "")                                       // should be {System.Diagnostics.CodeAnalysis.MemberNotNullAttribute("GeneratedProp")}
    {
        throw new Exception("here's bug!");
    }
}
```

**Comment by Youssef1313** [comment] 2021-03-20 13:32
Before the source is generated, I think the nameof argument will be an error, causing the binder to resolve the name as empty string. Let me check if swapping `CheckSyntaxForNameofArgument` and `HasAnyErrors` checks fixes this:

https://github.com/dotnet/roslyn/blob/0902d19aaba441d98fe5432274e5a2554353cc8d/src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs#L1838

**Comment by Youssef1313** [comment] 2021-03-20 14:10
I haven't yet dug into this, but I believe it will cause INameOfOperation to have a value on error cases:

```csharp
public class C
{
    private const string X = nameof(Y); // INameOfOperation will have ConstantValue="Y".
}
```

@333fred Is that okay? Otherwise, it seems very tricky (to me at least) to get the binder know if the argument *will* be valid after source is generated.

**Comment by 333fred** [comment] 2021-03-20 16:10
I'm not certain that we shouldn't just close this as by design, to be honest. @AlekseyTs, do you have thoughts? On the one hand, we can say that yeah, the meaning is unambiguous, if an error. On the other hand, that thing you're asking for does not exist, so the symbol model should reflect that.

**Comment by AlekseyTs** [comment] 2021-03-23 15:54
> do you have thoughts? On the one hand, we can say that yeah, the meaning is unambiguous, if an error. On the other hand, that thing you're asking for does not exist, so the symbol model should reflect that.

The symbol model is not involved here, in my opinion. We are not asking for SymbolInfo on the argument of the `nameof` we are asking its constant value, which is always known for syntactically valid argument and SemanticModel/IOperation should reflect that. For example, check out implementation of BindNameOfExpression in VB. How and whether that is going to affect the attribute info is another story. I would be fine with it's current behavior for erroneous use.

**Closed** 2021-03-26 19:59 UTC
Labels: Area-Compilers, untriaged
