### ISSUE TITLE
Typing in Razor files breaks C# incrementality resulting in high CPU & memory usage

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#59818] opened 2022-02-28 22:47 UTC
**Overview**:
Razor IDynamicFileInfoProvider output is fed into SourceGenerators which breaks C# incrementality and significantly impacts performance.

**Version Used**: All

**Steps to Reproduce**:

1. Create a Blazor server application
2. Open Index.razor

**Expected Behavior**:
Generated output from Index.razor is not fed into Json SourceGenerators

**Actual Behavior**:
Generated output from Index.razor is fed into Json SourceGenerators

**Additional Notes**:
@sharwell and I were investigating customer reports of high CPU utilization in Razor scenarios. Turns out Razor files (they emit larger C# files) are always fed into the Json, Logging & any other source generator. This in turn results in a lot of extra CPU churn for Razor projects. After digging into some traces we can see HEAVY allocations in the Roslyn service hub process from the realization of red trees from the Razor files:

![image](https://user-images.githubusercontent.com/2008729/156070724-02f1f427-ae1e-4cc9-a1d7-146a58bf0a18.png)

One implementation note we should think of is that we also have a [counter issue](https://github.com/dotnet/roslyn/issues/59780) where the Regex generators in .NET 7 do not run on Razor output resulting in the new Regex .NET 7 capabilities missing.

/cc @jasonmalinowski

**Comment by NTaylorMullen** [comment] 2022-02-28 23:03
Related VS Feedback issues: https://developercommunity.visualstudio.com/t/Editing-Blazor-files-consumes-all-CPU-fo/1676170

**Comment by jcouv** [comment] 2022-03-02 05:45
Assigning to @chsienki to triage.

**Comment by NTaylorMullen** [comment] 2022-03-08 23:46
Another: https://developercommunity.visualstudio.com/t/VS-2022---Blazor-Development-Experience/1684379

**Comment by jcouv** [comment] 2022-03-11 00:27
From discussion with @chsienki, the issue is that `IDynamicFiles` generated by Razor are visible to other source generators.
Some options:
1. migrating legacy to Razor to source generators (unlikely in short-term)
2. add some kind of filtering

**Comment by jasonmalinowski** [comment] 2022-04-14 22:39
This made it in for 17.2 Preview 4.

**Closed by jasonmalinowski** 2022-04-14 22:39 UTC
Labels: Bug, Area-Compilers, New Feature - Source Generators

**Comment by Mike-E-angelo** [comment] 2022-04-26 20:54
Thank you all very much for all your diligent and amazing work out there.  It is greatly appreciated and respected. 🙏
