### ISSUE TITLE
Xml doc comment munging param names

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#26292] opened 2018-04-20 21:32 UTC
Consider the following code:

``` csharp
class Program
{
    /// <summary>
    /// Text
    /// </summary>
    /// <param name="MS-Example">More text</param>
    static void Main(string[] args)
    {
    }
}
```

When this is built with XML doc comment generation enabled the name of the `param` field will be munged to `MS-Example-Example`. 

``` xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ConsoleApp16</name>
    </assembly>
    <members>
        <member name="M:ConsoleApp16.Program.Main(System.String[])">
            <summary>
            Text
            </summary>
            <param name="MS-Example-Example">More text</param>
        </member>
    </members>
</doc>
```

This also affects `.` as a separator in the name attribute, as seen in [AB#1272292](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1272292).

**Comment by AlekseyTs** [comment] 2018-04-20 22:50
This doesn’t appear to be a new issue, I can reproduce it with compiler built on 2016-10-20.

**Comment by AlekseyTs** [comment] 2018-04-20 22:54
Warnings from Roslyn:
```
(6,22): warning CS1572: XML comment has a param tag for 'MS', but there is no parameter by that name
(7,31): warning CS1573: Parameter 'args' has no matching param tag in the XML comment for 'Program.Main(string[])' (but other parameters do)
```

Warnings from native compiler:
```
(6,22): warning CS1572: XML comment on 'Program.Main(string[])' has a param tag for 'MS-Example', but there is no parameter by that name
(7,31): warning CS1573: Parameter 'args' has no matching param tag in the XML comment for 'Program.Main(string[])' (but other parameters do)
```

It appears there is a difference in what compilers consider as a parameter name 'MS' vs.  'MS-Example'.

**Comment by sharwell** [comment] 2018-04-25 11:06
Is there a way to get this to occur for a parameter name? The example uses `MS-Example`, but that is not a parameter name.

**Comment by arisewanggithub** [comment] 2018-08-10 15:02
Is there any update to this bug? This also blocks our swagger onboarding.

**Comment by sharwell** [comment] 2018-08-10 15:47
@arisewanggithub Can you provide an example of how this impacts you? The example shown in the original issue filed above contains a seemingly-meaningless documentation comment. I'm trying to better understand how this can occur in real world scenarios.

**Comment by jasonmalinowski** [comment] 2018-08-16 23:27
@arisewanggithub But your name of your parameter is not "MS-CV", right? The part we're not getting is why param names that aren't parameter names are being used.

**Comment by CyrusNajmabadi** [comment] 2018-08-16 23:35
> We want to onboard to swagger

What is 'swagger'? I only know it in the context of AWS API Gateway.

**Comment by sharwell** [comment] 2022-03-01 16:55
Resolving this one as **Won't Fix**. Parameter names with a `.` are not valid syntax. Generally an issue like this would fall under diagnostic clarity if there is a problem with the reported error message, but this is slightly different as it's a request to implement support for functionality which is not valid under the rules of the language.

**Closed by sharwell** 2022-03-01 16:55 UTC
Labels: Bug, Resolution-Won't Fix, Area-Compilers

**Comment by arisewanggithub** [comment] 2022-03-01 17:18
@sharwell, I think - is a valid character in http headers. What do you mean "parameter names with a . or - are not valid syntax. ", by which standard?

**Comment by sharwell** [comment] 2022-03-01 17:26
@arisewanggithub The C# standard:
https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/documentation-comments.md#d310-paramref

**Comment by sharwell** [comment] 2022-03-03 18:42
@TobiasKnauss The issue you linked includes the following syntax in a documentation comment:

```xml
<paramref name="i_range.LowerValue"/>
```

Per the links in https://github.com/dotnet/roslyn/issues/26292#issuecomment-1055679737, `i_range.LowerValue` is not a valid C# parameter name and thus cannot be used in the `name` attribute of `<paramref>`.

**Comment by TobiasKnauss** [comment] 2022-03-04 13:28
@sharwell Okay, it may not be valid syntax, but the compiler still creates something from it, which comes very close. This appears to me as if the compiler actually knows what to do, but just does it wrong, maybe due to a bug. If it was completely invalid, then the compiler should not have added the properties in any way to the output.
It would be nice if this syntax was allowed and the compiler worked as intended by me.
