### ISSUE TITLE
Is it correct to use Microsoft.Extensions.DependencyModel6.0 in the current net5.0 project?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#57625] opened 2021-11-08 09:23 UTC
Hello. I seem to find a bug?

**Version Used**: 

| project or library | version |
| -- | -- | 
| dotnet |  5.0 |
|Microsoft.CodeAnalysis.CSharp.Workspaces | 3.11.0 |
| Microsoft.Extensions.DependencyModel |  6.0  |

**Steps to Reproduce**:

1. In my project, try to use roslyn to compile a piece of code as follows.
2. All references are from the `Microsoft.Extensions.DependencyModel` class library, and upgrade its v5.0 to v6.0.
2. Run the program Or [Unit test](https://github.com/dotnetcore/Natasha/blob/master/test/NatashaUT/CSharp9/C9SyntaxTest.cs#L64-L89)

Get Dependency :
```c#
IEnumerable<string> paths = DependencyContext
                    .Default
                    .CompileLibraries.SelectMany(cl => cl.ResolveReferencePaths());

Parallel.ForEach(
                    paths,
                    asm => referencesCache[Path.GetFileNameWithoutExtension(asm)] = MetadataReference.CreateFromFile(asm));
```
Roslyn compile( Compilation.Emit() ) code:
```c#
public static class Nf1d476d825ba4b65b38f0604549f446c
{
    [System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public static System.Int32 Invoke()
    {
        return 1;
    }
}
```
**Expected Behavior**:

No exception and compile succeed.

**Actual Behavior**:

Error : 
> CS0433 类型“SkipLocalsInitAttribute”同时存在于“System.Text.Encodings.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”和“System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”中

**Comment by svick** [comment] 2021-11-08 09:52
The assemblies System.Text.Encodings.Web and System.Text.Json should not be publicly exposing the `SkipLocalsInitAttribute` type, though they do contain it as `internal` (in certain configurations). Are you doing something to access `internal` members of those assemblies?

**Comment by NMSAzulX** [comment] 2021-11-08 09:59
@svick No, that code is program-generated code, it looks normal. 
But my library will generate a refs folder, which contains a lot of dlls, could this be the cause of the problem?

**Comment by svick** [comment] 2021-11-08 10:51
As far as I can tell, [you are](https://github.com/dotnetcore/Natasha/blob/a135/src/Natasha.CSharp/Natasha.CSharp.Engine/Component/Compiler/NatashaCSharpCompiler.cs#L79).

If I copy that part of your code, I can get the same error as you. But whether you use `IgnoreAccessibility` or not, the fix is the same: on frameworks like .Net Core 3.1, if you want to use `SkipLocalsInitAttribute`, you should include it in the compilation yourself. The code for that could be as simple as:

```c#
namespace System.Runtime.CompilerServices
{
    public sealed class SkipLocalsInitAttribute : Attribute { }
}
```

If you continue using `IgnoreAccessibility`, you're going to get a warning like:

> warning CS0436: The type 'SkipLocalsInitAttribute' in 'SkipLocalsInitAttribute.cs' conflicts with the imported type 'SkipLocalsInitAttribute' in 'System.Text.Encodings.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in 'SkipLocalsInitAttribute.cs'.

But I think you can ignore that.

**Comment by jaredpar** [comment] 2021-11-08 17:28
Closing as this behavior is "By Design" as discussed in the comments.

**Closed by jaredpar** 2021-11-08 17:28 UTC
Labels: Area-Compilers, untriaged

**Comment by NMSAzulX** [comment] 2021-11-09 02:32
@svick  I'm sorry I ignored the important configuration of the compilation option. Thank you for your answer.
 I experiment with it.  `(uint)CompileFlags - CompilerBinderFlags.IgnoreAccessibility;`  It works well!
