### ISSUE TITLE
Analyzer proposal: mark anonymous functions as static

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/roslyn#52840] opened 2021-04-16 13:34 UTC
## Cause

An anonymous function that does not capture state from the enclosing scope is not marked as `static`.

## Rule description

Lambdas and anonymous methods can be marked with the `static` modifier, to disallow capture of locals or instance state. Adding the `static` modifier to an anonymous function does not change the meaning of the program.

By applying this code fix, it can be ensured that future modifications to a program do not result in unexpected retention of captured objects or unexpected additional allocations.

## Additional context
* https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/static-anonymous-functions
* https://github.com/dotnet/csharplang/issues/275

**Comment by CyrusNajmabadi** [comment] 2021-04-22 17:02
We explicitly decided not to do this as it would clutter up code that is intended to be terse unilaterally.  `static` is intentionally intended to be a user controlled system whereby they annotate the lambdas tehy do not want capturing to ensure that no captures exist and no regressions happen in the future.  It is not considered a 'better way' to do lambdas, or a pattern we would push people to use for all lambdas (even when applicable).

**Comment by NTaylorMullen** [comment] 2021-04-26 21:58
Conclusion: Represent the fix under a different diagnostic ID and have it hidden by default.

**Comment by Youssef1313** [comment] 2021-05-11 17:23
@NTaylorMullen based on the design meeting notes, wouldn't it be better to offer it as a refactoring then?

**Comment by CyrusNajmabadi** [comment] 2024-10-22 17:17
Closing out as not planned.

**Closed by CyrusNajmabadi** 2024-10-22 17:17 UTC
Labels: help wanted, Area-IDE, Area-Analyzers, Feature Request
