### ISSUE TITLE
Find all references Goto Next/Prev Location doesn't work as excpected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24027] opened 2018-01-04 01:49 UTC
Hi,
I think it should work similarly as navigating between the items of a find in files session. After getting the result, toolwindow gets the focus and hittting F8 (Goto next location) should open up the next result's document. The caret is placed where the match is found and it is blinking (got the input focus). Hitting the F8 again would open up the next document with blinking caret etc.
In case of find all references after getting the results and hitting F8 VS opens up the corresponding document the current line marker is set also but doesn't get the input focus, the caret is not visible. Repetitively hitting F8 usually gives the same result, sometimes the caret is visible but usually not. It is a bit annoying given it is not clear where the reference was found and no chance to start typing without using the mouse. 
Thanks,
Marcell

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/157226/find-all-references-goto-nextprev-location-doesnt.html
VSTS ticketId: 530519_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎12‎/‎3‎/‎2017, 05:07 AM (31 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Tomas Karban on ‎12‎/‎6‎/‎2017, 06:27 AM (28 days ago): <p>I have the same problem, VS2017 15.5.0 running on Windows 7. After F8 the editor does not have proper focus. I cannot type, but Delete/Backspace work... which is strange. Double-clicking on the item in the result window works as expected -- brings focus to the editor (blinking cursor at the right location).</p>

_These are the original issue solutions:_
(no solutions)

**Comment by 0xd4d** [comment] 2018-08-17 16:37
Dupe of #26565.

Still not fixed in 15.8 :thumbsup:

**Comment by CyrusNajmabadi** [comment] 2023-11-22 20:31
Dupe of https://github.com/dotnet/roslyn/issues/26565

**Closed by CyrusNajmabadi** 2023-11-22 20:31 UTC
Labels: Area-IDE, Developer Community
