### ISSUE TITLE
Code fix for `csharp_prefer_braces = true` adds blank line if another statement follows

### ISSUE THREAD

**Issue by jameschensmith** [dotnet/roslyn#70697] opened 2023-11-03 16:56 UTC
**Version Used**: `1.39.10-net6.0`

**Steps to Reproduce**:

1. Have a C# file which includes something like the following:
    ```c#
    if (true)
        Console.WriteLine();
    Console.WriteLine();
    ```
2. In EditorConfig, set `csharp_prefer_braces = true` 
3. Run quick fix to add braces (or `dotnet format`)

**Diagnostic Id**: `IDE0011`

**Expected Behavior**:

```c#
if (true)
{
    Console.WriteLine();
}
Console.WriteLine();
```

**Actual Behavior**:

```c#
if (true)
{
    Console.WriteLine();
}

Console.WriteLine();
```

**Comment by CyrusNajmabadi** [comment] 2023-11-04 00:43
The code that is generated is the code I expect.

**Comment by CyrusNajmabadi** [comment] 2024-12-08 05:45
Closing as by design.

**Closed by CyrusNajmabadi** 2024-12-08 05:45 UTC
Labels: Bug, Area-IDE
