### ISSUE TITLE
Move Type to Matching File removes unnecessary usings

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#14095] opened 2016-09-27 05:00 UTC
![image](https://cloud.githubusercontent.com/assets/1402694/18860666/5e6fecb8-8434-11e6-826e-6250f1871b3d.png)

2 unexpected things happen here:
1. My code preview shows my unnecessary usings (at first I thought it was going to bring those over to my new file, but now I see it is because of (2)).
2. Executing this refactoring removes said unnecessary usings.

**Comment by dpoeschl** [comment] 2016-09-29 18:27
Let's wait to see if there are more complaints about this. This happens because we try to do the right thing and remove newly-unused usings, we're just doing too much.

**Comment by CyrusNajmabadi** [comment] 2016-09-30 07:11
This is a poor experience, and i've noticed it myself:

1. We're moving a type, so we should show you the file contents of the file that will be added, not what's being ripped out of this file.  Alternatively, we could show no preview at all.  I'm not a fan of the preview here as it tends to be ginormous and distractin.
2. It's definitely by design that the usings get trimmed.  Moving types can often lead to a bunch of usings in both files that are just no longer relevant for their current type.  This helps tidy things up so you don't have to go and manually do it in both files.

**Comment by miloush** [comment] 2016-10-12 12:01
I came here to complain about the removed usings too. I would much prefer if after the quick action, either both files or at least the source file would have the same list of usings as before. I am happy to clear the unused ones if needed, it's not that complicated.

You are basically saying that it is wrong that project/file templates contain usings that are not used by default, and I would disagree with that. For example, new WPF Window contains these:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
```
of which only `System.Windows` is used initially. If I happen to sketch a type in the file and when it gets elaborated enough, move it to a separate file as I just did, it removes all these usings, and adding e.g. event handlers creates fully qualified parameters everywhere and raises the bar for the number of types I need to know from top of my head to actually write any useful code.

Move to file and remove usings are two different actions. I usually remove usings when I consider the file to be more or less done. Moving types around on the other hand, happens in the middle of refactoring the code and like in the case above, the source file might be in the early stage where many of the usings are yet to be used. The same way you could argue that people don't usually create a blank type just for the purpose of moving it into a new file (they might start doing so with this fantastic quick action), but do it when the type is more or less done, so removing the usings in the target file might be reasonable.

So I am against mixing these stages in a single action. Or create 'move and remove usings' action. It might be "the right thing to do" but not at the point where you are moving types, at least for me.

I don't mind not seeing a preview for this one. If there is a need for preview, I would prefer it to be the way it currently is, because the preview is (or was so far) what happens in the current file. Having a preview showing an excerpt from a non-existing file is a bit confusing; but as I said both ways are easily understandable from the context. You could also show both.

**Comment by kuhlenh** [comment] 2017-06-19 17:43
@CyrusNajmabadi @dpoeschl  Along the same lines, for "remove unnecessary variable" we also remove all the whitespace? I'm not sure if it's a problem, it's just that I'm not expecting it to happen. A fix in my mind is a 1-to-1 mapping not 1-to-many (at least with the title of the fix). 

![image](https://user-images.githubusercontent.com/1402694/27298015-e9d08b96-54db-11e7-8e37-0c24b4904fc2.png)

**Comment by CyrusNajmabadi** [comment] 2017-06-20 03:12
@kuhlenh Whitespace is always tricky.  Any decision can be wrong depending on user expectations.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 17:03
Closing out due to lack of customer feedback on this issue.

**Closed by CyrusNajmabadi** 2024-10-21 17:03 UTC
Labels: Bug, Area-IDE
