### ISSUE TITLE
Mono Linux exits with SIGABRT

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6259] opened 2015-10-23 07:00 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/474/consoleFull#1513664531933ca3d2-9c4f-4be8-b489-132a498fda66

Stack:
```
22:43:57 We don't know how many blocks we have?
22:43:57 Stacktrace:
22:43:57 
22:43:57   at <unknown> <0xffffffff>
22:43:57   at (wrapper managed-to-native) string.FastAllocateString (int) <IL 0x0000d, 0xffffffff>
22:43:57   at string.Concat (string,string) [0x00032] in /home/andy/code/mono/external/referencesource/mscorlib/system/string.cs:3257
22:43:57   at System.Runtime.Remoting.TypeInfo.CanCastTo (System.Type,object) [0x00074] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting/TypeInfo.cs:103
22:43:57   at System.Runtime.Remoting.Proxies.RemotingProxy.CanCastTo (System.Type,object) [0x0005a] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Proxies/RemotingProxy.cs:176
22:43:57   at (wrapper runtime-invoke) <Module>.runtime_invoke_bool__this___object_object (object,intptr,intptr,intptr) <IL 0x00070, 0xffffffff>
22:43:57   at <unknown> <0xffffffff>
22:43:57   at (wrapper managed-to-native) object.__icall_wrapper_mono_marshal_isinst_with_cache (object,intptr,intptr) <IL 0x0000f, 0xffffffff>
22:43:57   at (wrapper castclass) object.__isinst_with_cache (object,intptr,intptr) <IL 0x00038, 0xffffffff>
22:43:57   at Xunit.TestMessageVisitor.DoVisit<TSource_REF> (Xunit.Abstractions.IMessageSinkMessage,System.Func`3<Xunit.TestMessageVisitor, TSource_REF, bool>) <IL 0x00001, 0x00047>
22:43:57   at Xunit.TestMessageVisitor.OnMessage (Xunit.Abstractions.IMessageSinkMessage) <IL 0x001fa, 0x00dcf>
22:43:57   at Xunit.XmlAggregateVisitor.OnMessage (Xunit.Abstractions.IMessageSinkMessage) <IL 0x0000f, 0x00046>
22:43:57   at (wrapper runtime-invoke) <Module>.runtime_invoke_bool__this___object (object,intptr,intptr,intptr) <IL 0x00066, 0xffffffff>
22:43:57   at <unknown> <0xffffffff>
22:43:57   at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices.InternalExecute (System.Reflection.MethodBase,object,object[],object[]&) <IL 0x00010, 0xffffffff>
22:43:57   at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject,System.Runtime.Remoting.Messaging.IMethodCallMessage) [0x000c2] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting/RemotingServices.cs:150
22:43:57   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x0001f] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Messaging/StackBuilderSink.cs:59
22:43:57   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00016] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Messaging/ServerObjectTerminatorSink.cs:53
22:43:57   at System.Runtime.Remoting.Lifetime.LeaseSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00007] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Lifetime/LeaseSink.cs:52
22:43:57   at System.Runtime.Remoting.ClientActivatedIdentity.SyncObjectProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00041] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting/ServerIdentity.cs:191
22:43:57   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00023] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Messaging/ServerContextTerminatorSink.cs:50
22:43:57   at System.Runtime.Remoting.Contexts.CrossContextChannel.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00041] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Contexts/CrossContextChannel.cs:57
22:43:57   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage (System.Runtime.Remoting.Messaging.IMessage) [0x00015] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Channels/ChannelServices.cs:394
22:43:57   at System.AppDomain.ProcessMessageInDomain (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]&,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&) [0x0001f] in /home/andy/code/mono/mcs/class/corlib/System/AppDomain.cs:1369
22:43:57   at (wrapper remoting-invoke-with-check) System.AppDomain.ProcessMessageInDomain (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]&,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&) <IL 0x0003d, 0xffffffff>
22:43:57   at System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage) [0x00008] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Channels/CrossAppDomainChannel.cs:199
22:43:57   at (wrapper runtime-invoke) <Module>.runtime_invoke_CrossAppDomainSink/ProcessMessageRes_object_object (object,intptr,intptr,intptr) <IL 0x0006e, 0xffffffff>
22:43:57   at <unknown> <0xffffffff>
22:43:57   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <IL 0x0001c, 0xffffffff>
22:43:57   at System.AppDomain.InvokeInDomainByID (int,System.Reflection.MethodInfo,object,object[]) [0x00017] in /home/andy/code/mono/mcs/class/corlib/System/AppDomain.cs:966
22:43:57   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage) [0x0002e] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Channels/CrossAppDomainChannel.cs:235
22:43:57   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke (System.Runtime.Remoting.Messaging.IMessage) [0x000ea] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Proxies/RemotingProxy.cs:100
22:43:57   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy,System.Runtime.Remoting.Messaging.IMessage,System.Exception&,object[]&) [0x000a5] in /home/andy/code/mono/mcs/class/corlib/System.Runtime.Remoting.Proxies/RealProxy.cs:194
22:43:57   at (wrapper runtime-invoke) <Module>.runtime_invoke_object_object_object_intptr&_intptr& (object,intptr,intptr,intptr) <IL 0x00078, 0xffffffff>
22:43:57   at <unknown> <0xffffffff>
22:43:57   at (wrapper managed-to-native) object.__icall_wrapper_mono_remoting_wrapper (intptr,intptr) <IL 0x0000e, 0xffffffff>
22:43:57   at (wrapper remoting-invoke) Xunit.Abstractions.IMessageSink.OnMessage (Xunit.Abstractions.IMessageSinkMessage) <0xffffffff>
22:43:57   at (wrapper xdomain-invoke) Xunit.Abstractions.IMessageSink.OnMessage (Xunit.Abstractions.IMessageSinkMessage) <0xffffffff>
22:43:57   at Xunit.Sdk.MessageBus.DispatchMessages () <0x0005d>
22:43:57   at Xunit.Sdk.MessageBus.ReporterWorker () <0x0002b>
22:43:57   at Xunit.Sdk.XunitWorkerThread/<>c.<.ctor>b__1_0 (object) <0x00032>
22:43:57   at System.Threading.ThreadHelper.ThreadStart_Context (object) <0x000e7>
22:43:57   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x002aa>
22:43:57   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00023>
22:43:57   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) <0x000a3>
22:43:57   at System.Threading.ThreadHelper.ThreadStart (object) <0x0007f>
22:43:57   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <IL 0x0005a, 0xffffffff>
22:43:57 
22:43:57 Native stacktrace:
22:43:57 
22:43:57 	mono() [0x4a1dd8]
22:43:57 	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f3b149d9340]
22:43:57 	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f3b1463acc9]
22:43:57 	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f3b1463e0d8]
22:43:57 	mono() [0x62ce86]
22:43:57 	mono() [0x62cc73]
22:43:57 	mono() [0x62cd29]
22:43:57 	mono() [0x5ef044]
22:43:57 	mono() [0x5e8040]
22:43:57 	mono() [0x5e8315]
22:43:57 	mono() [0x5ea916]
22:43:57 	mono() [0x5dddea]
22:43:57 	mono() [0x5cc986]
22:43:57 	[0x405640da]
22:43:57 
22:43:57 Debug info from gdb:
22:43:57 
22:43:57 
22:43:57 =================================================================
22:43:57 
Got a SIGABRT while executing native code. This usually indicates
22:43:57 a fatal error in the mono runtime or one of the native libraries 
22:43:57 used by your application.
22:43:57 =================================================================
22:43:57 
22:43:58 
./cibuild.sh: line 235: 62462 Aborted                 (core dumped) mono $MONO_ARGS $xunit_runner Binaries/$BUILD_CONFIGURATION/$i.dll -xml Binaries/$BUILD_CONFIGURATION/xUnitResults/$i.dll.xml -noshadow
```

**Comment by davkean** [comment] 2015-10-23 14:52
@agocke I thought we were done with Mono and now only on CoreCLR? Or am I missing something?

**Comment by davkean** [comment] 2015-10-23 14:52
tag @dotnet/roslyn-infrastructure 

If not, we're hitting a lot of Mono issues.

**Comment by tannergooding** [comment] 2015-10-23 15:54
@davkean, I believe we are mostly off Mono, but not entirely. @agocke would have more details.

**Comment by agocke** [comment] 2015-10-23 21:17
@davkean This one's because we're running the unit tests on Mono

**Comment by borgdylan** [comment] 2015-10-25 10:08
CoreCLR does not run on all the cpu architectures that it should support. This means mono is here to stay for the time being. So it is better not to do any changes that will surely break on mono.

**Comment by davkean** [comment] 2015-12-11 17:32
Not a lot we can do with this - other than live with it.

**Comment by jaredpar** [comment] 2015-12-11 17:51
Eventually #7139 will fix this error for us. That should be completed in the update 2 timeframe.

**Comment by davkean** [comment] 2016-02-26 06:06
Dupe of https://github.com/dotnet/roslyn/issues/6407

**Closed by davkean** 2016-02-26 06:06 UTC
Labels: Area-Infrastructure, Contributor Pain, Flaky, Flaky-ExceptionGranted
