### ISSUE TITLE
CS8762 on !string.IsNullOrEmpty return value

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#44526] opened 2020-05-22 21:19 UTC
I added the `NotNullWhen(returnValue: true)` attribute to an `out` string parameter in a method that returns a boolean.

If the very last return consists of `!string.IsNullOrEmpty(s)`, CS8762 gets unexpectedly triggered with this message:

> CS8762: Parameter '<paramName>' must have a non-null value when exiting with 'true'

Example:
```cs
using System.Diagnostics.CodeAnalysis;
public class C
{
    public bool TryMethod(
        int x,
        [NotNullWhen(returnValue: true)] out string s)
    {
        s = null;       
        if (x > 0)
        {
            s = x.ToString();
        }      
        return !string.IsNullOrEmpty(s);
    }
}
```
I found this while working on the `dotnet/roslyn-analyzers` repo.
I tried to create a SharpLab repro, but it's not getting triggered there.

**Comment by jcouv** [comment] 2020-07-25 05:09
I confirmed that the problem doesn't repro on [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAEQEsIBzAOwHtZCBjKXAYQoBM4BBMiAGwE8pCoAbgCwAKADEZAK5cuEYFzgY4nBXDEoAzFgBMGBmIDeYjKazbgFClwwAVBDwCycGAAsWAChNmfhMjAwADwAabx9TAG0AOQoYKJkuAHVXFQ8UAHYANW4pOBAMGARcgEoAXQwKKQCcNAB+DChisIxjUXCzKAwAXgxpWUF2jGbfADMMD0CMAD4MNCa2wdbB8M6ewNxbCgBlQr8SD2KRBfaAX3bhswyMAEIa3ABJKHjZAHkEAFEwAAcYHg9Go4+E5iE5AA=).

@carlossanlop Please check the `IsNullOrEmpty` API that you're using. You are likely using a target framework where that method had not yet been marked with a nullability attribute.

**Comment by carlossanlop** [comment] 2020-07-27 03:57
@jcouv I specified at the end of my description the following:

>  _I tried to create a SharpLab repro, but it's not getting triggered there._

But I can repro it if I copy-paste the code snipped in my description into any cs file in the dotnet/roslyn-analyzers project, which, as far as I recall, uses .NET Core 3.1.

You can test this yourself.

**Comment by jcouv** [comment] 2020-07-28 03:26
@carlossanlop I tried this in roslyn-analyzers and looked at the IsNullOrEmpty method.
It comes from:
```
#region Assembly System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\jcouv\.nuget\packages\system.runtime\4.3.0\ref\netstandard1.3\System.Runtime.dll
```
which lacks the nullability attribute that would make it work.

I'll go ahead and close the issue.

**Closed by jcouv** 2020-07-28 03:26 UTC
Labels: Area-Compilers, Bug, Concept-Null Annotations, New Language Feature - Nullable Reference Types, Resolution-Not Reproducible

**Comment by sharwell** [comment] 2020-07-28 04:02
Duplicate of #37995
