### ISSUE TITLE
string param = default shown as string param = null in virtual methods when overridden

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35847] opened 2019-05-21 18:19 UTC
VSF_TYPE_MARKDOWNHi

I have a method

`protected override U CreateReply&lt;U&gt;(IContent content, Guid relationGuid = default, string code = default, string name = default)`

when overridden in a sub-class, it looks like this

`protected override U CreateReply&lt;U&gt;(IContent content, Guid relationGuid = default, string code = null, string name = null)`

It would be nice if optional string parameters declared as default is also set to default (instead of null) when overridden.

Probably not a big issue, other than &quot;cosmetic&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/570557/string-param-default-shown-as-string-param-null-in.html
VSTS ticketId: 893747_
_These are the original issue comments:_

Frode Gilberg on 5/16/2019, 03:38 AM (5 days ago): Correction. The first code-sample should be virtual (not override). Typing mistake
Visual Studio Feedback System on 5/16/2019, 10:58 PM (4 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2019-05-21 20:35
Yes.  The symbolic model doesn't keep track of the initial expression, just the value.  So, when generating this, we emit in the form we think is the most idiomatic for the language.  For reference types, that's simply `null`.  It's simple, clear, and has worked well since optional params were added.

`default` is used for for things like structs where there's no existing convenient literal (like 0/false/etc.), and `default(SomeStruct)` would be extremely verbose.

**Comment by sharwell** [comment] 2019-05-29 02:10
Tentatively marking this as **By Design**. I will update with the conclusion following the team design review.

**Comment by sharwell** [comment] 2019-06-17 18:33
Design review conclusion:

The current behavior _was_ by design, but we talked a bit more on whether it would be a reasonable change to use the behavior requested above. In the end, we concluded that the current behavior is still by design for the following reasons:

* It's not possible to distinguish between `default` and `null` for reference types for signatures defined in metadata
* The constant expressions used in initializers might reference other constants, including cases where `using static` directives impact the names

The current behavior allows the use of a normalized form when presenting information which helps avoid pitfalls associated with all the various edge cases.

**Closed by sharwell** 2019-06-17 18:33 UTC
Labels: Area-IDE, Feature Request, Need Design Review, Resolution-By Design
