### ISSUE TITLE
we need test for EditorConfigDocumentOptionsProvider

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#26396] opened 2018-04-25 21:19 UTC
looks like only test we have right now is integration tests. but it would be nice if we have some unit tests.

**Comment by heejaechang** [comment] 2018-04-25 21:26
no I am not creating whole unit test hardness for EditorConfigDocumentOptionsProvider. if there was one already I would add one, but there is none exist currently. also we are soon getting new editorconfig work from compiler which will make us to rewrite a lot of these, so we will probably wait until that work comes. until then, integration test is the test for this feature I believe.

**Comment by CyrusNajmabadi** [comment] 2018-04-25 21:29
> until then, integration test is the test for this feature I believe.

Can you point me to the integration test that validates the new code you are writing works properly? I don't see it in the PR.

**Comment by CyrusNajmabadi** [comment] 2018-04-25 21:30
> if there was one already I would add one, but there is none exist currently.

That seems like a sure fire way to never get tests written for an area :)    And that doesn't seem healthy for our code.  It seems regrettable that no one wrote unit tests here.  But we should still at least not continue down that path just because the original author skipped out on testing.  We should at least have an integration test to validate this behavior.  Or, better yet, have a real unit test.  Otherwise, there is absolutely nothing actually ensuring that:

1. this code actually works.
2. nothing regresses this behavior in the future.

**Comment by heejaechang** [comment] 2018-04-25 21:31
nope. we don't have specific test that covers it. like we don't have unit test for code in VS layers or our integration test not touching all those cases in VS layer. it is done manually.

**Comment by heejaechang** [comment] 2018-04-25 21:31
that is why this issue is created so that we can add unit tests.

**Comment by CyrusNajmabadi** [comment] 2018-04-25 21:46
Who does the manual testing?  Is this given to CTI?

> or our integration test not touching all those cases in VS layer. 

I mean... this is not a good thing :)  I would prefer we not perpetuate the problem

> that is why this issue is created so that we can add unit tests.

Is there a good reason we don't jsut roll that into the PR that actually is fixing the issue?  AFACT, it would not be hard to test.  You just need to make a workspace, have a mock ICodingConventionsManager, and hten validate that when those events fire:

1. you get a new solution snapshot.
2. some set of features rerun and get up to date data.  Perhaps a single analyzer.

This seems like a few dozen lines of code to write, and would give a lot of confidence in the fix, as well as ensuring that no regressions happen.

**Comment by heejaechang** [comment] 2018-04-25 21:53
tagging @jinujoseph

**Comment by CyrusNajmabadi** [comment] 2024-10-19 22:29
Closing out.

**Closed by CyrusNajmabadi** 2024-10-19 22:29 UTC
Labels: Area-IDE, Test
