### ISSUE TITLE
SemanticsModel.GetSynbolInfo throws a NullRefereceException for a particular symbol.

### ISSUE THREAD

**Issue by benutomo-dev** [dotnet/roslyn#69434] opened 2023-08-09 06:23 UTC
NullRefereceException on SemanticsModel.GetSynbolInfo when an extension method with the same name exists in multiple files in the file scope.

**Version Used**: 

dotnet sdk 7.0.400

Microsoft Visual Studio Community 2022 Version 17.7.0

**Steps to Reproduce**:

1.  git clone "https://github.com/benutomo-dev/NullRefereceExceptionAtGetSymbolInfo.git"
2.  Open "NullRefereceExceptionAtGetSymbolInfo.sln".
3.  Set startup project to "NullRefereceExceptionAtGetSymbolInfoAnalyzer" and select "NullRefereceExceptionAtGetSymbolInfo" for target project.
4.  Begin debug.

**Exception detail (japanese locale)**:

```
System.NullReferenceException
  HResult=0x80004003
  Message=オブジェクト参照がオブジェクト インスタンスに設定されていません。
  Source=Microsoft.CodeAnalysis.CSharp
  スタック トレース:
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, MethodSymbol method, ImmutableArray`1 typeArguments, TypeSymbol receiverType, CSharpCompilation compilation)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.MergeReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, SingleLookupResult singleResult, ImmutableArray`1 typeArguments, TypeSymbol receiverType, LookupResultKind& resultKind, CSharpCompilation compilation)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetReducedAndFilteredMethodGroupSymbols(Binder binder, BoundMethodGroup node)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetMethodGroupSemanticSymbols(BoundMethodGroup boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, LookupResultKind& resultKind, Boolean& isDynamic, ImmutableArray`1& methodGroup)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSemanticSymbols(BoundExpression boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, SymbolInfoOptions options, Boolean& isDynamic, LookupResultKind& resultKind, ImmutableArray`1& memberGroup)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
   場所 Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
   場所 Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   場所 Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   場所 NullRefereceExceptionAtGetSymbolInfoAnalyzer.Analyzer.DetectDiscardOfCollectionOperationResult(SyntaxNodeAnalysisContext context) (C:\Users\kajodev\source\repos\NullRefereceExceptionAtGetSymbolInfo\NullRefereceExceptionAtGetSymbolInfoAnalyzer\Analyzer.cs):行 39

```

**Diagnostic Id**:

**Expected Behavior**:

Execution completes without exception.

**Actual Behavior**:

An NullReferecneException is raised inside the GetSymbolInfo method.

**Etc**:

Class1.cs and Class2.cs included in the project generate an internal error when opened in VS.

<img width="689" alt="image" src="https://github.com/dotnet/roslyn/assets/52617232/dae5a1b2-ba88-4d0e-b74c-62d925aeed91">

Below is a stack trace of the CodeLens.

```
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   場所 StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, MethodSymbol method, ImmutableArray`1 typeArguments, TypeSymbol receiverType, CSharpCompilation compilation)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.MergeReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, SingleLookupResult singleResult, ImmutableArray`1 typeArguments, TypeSymbol receiverType, LookupResultKind& resultKind, CSharpCompilation compilation)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetReducedAndFilteredMethodGroupSymbols(Binder binder, BoundMethodGroup node)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetMethodGroupSemanticSymbols(BoundMethodGroup boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, LookupResultKind& resultKind, Boolean& isDynamic, ImmutableArray`1& methodGroup)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSemanticSymbols(BoundExpression boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, SymbolInfoOptions options, Boolean& isDynamic, LookupResultKind& resultKind, ImmutableArray`1& memberGroup)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
      at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferenceCache.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.FindReferencesInTokensAsync(ISymbol symbol, FindReferencesDocumentState state, ImmutableArray`1 tokens, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.FindReferencesInDocumentUsingIdentifierAsync(ISymbol symbol, String identifier, FindReferencesDocumentState state, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.OrdinaryMethodReferenceFinder.FindReferencesInDocumentAsync(IMethodSymbol symbol, FindReferencesDocumentState state, FindReferencesSearchOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_0.<<ProcessDocumentAsync>g__ProcessDocumentAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, MetadataUnifyingSymbolHashSet symbols, Dictionary`2 symbolToGlobalAliases, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, MetadataUnifyingSymbolHashSet symbols, Dictionary`2 symbolToGlobalAliases, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IStreamingFindReferencesProgress progress, IImmutableSet`1 documents, FindReferencesSearchOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IFindReferencesProgress progress, IImmutableSet`1 documents, FindReferencesSearchOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.FindAsync[T](Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Func`2 onResults, Func`2 onCapped, Int32 searchCap, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.GetReferenceCountAsync(Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Int32 maxSearchResults, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<>c__DisplayClass3_0.<<GetReferenceCountAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.GetReferenceCountAsync(Checksum solutionChecksum, DocumentId documentId, TextSpan textSpan, Int32 maxResultCount, CancellationToken cancellationToken)
```

**Comment by svick** [comment] 2023-08-09 06:50
This is a duplicate of https://github.com/dotnet/roslyn/issues/67940.

**Closed by svick** 2023-08-09 06:50 UTC
Labels: Area-Compilers, untriaged
