### ISSUE TITLE
Improve nullable reference type detection of captured variables

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49458] opened 2020-11-18 00:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/400362/improve-nullable-reference-type-detection-of-captu.html)._

---
<p>Given the following C# 8 method:</p><pre>public Task&lt;bool&gt; ExistsAsync(string? id) {
  var query = _context.Packages;
  if (id != null) {
    query = query.Where(p =&gt; p.Id == id);
  }
  return await query.AnyAsync();
}</pre><p></p><p>For this code snippet, C# 8 gives the warning &quot;Possible dereference of a null reference&quot;. I'm guessing this is because I could set `id` to `null` after the `if` statement. Should the compiler warn for this code snippet? It's not clear how to fix this, but this is what I came up with:</p><p></p><pre>public Task&lt;bool&gt; ExistsAsync(string? id) {
  var query = _context.Packages;
  if (id != null) {
    var idNotNull = id;
    query = query.Where(p =&gt; p.Id == idNotNull);
  }
  return await query.AnyAsync();
}</pre>

---
#### Jane Wu [MSFT] on 12/6/2018, 06:14 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  You will hear from us in about a week on our next steps.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

**Comment by jaredpar** [comment] 2020-11-24 17:46
Closing as I could not reproduce this behavior in the current compiler. If you still see this in VS16.8 could you please provide a minimal sample here that repros the problem?

**Closed by jaredpar** 2020-11-24 17:46 UTC
Labels: Area-Compilers, untriaged
