### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by jakeswenson** [dotnet/roslyn#2202] opened 2015-04-23 04:17 UTC
When running the 1.0.0-rc1 on our build machines (installed from the Microsoft.Net.Compilers nuget package) we're getting errors from the csc2.exe  & csc.exe.

  ```
D:\replaced\.build\packages\Microsoft.Net.Compilers.1.0.0-rc1\tools\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\replaced.dll /subsystemversion:6.00 /target:library /utf8output Properties\AssemblyInfo.cs "C:\Users\replaced\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
  
  Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
     at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)
     at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.PushLeft(SortedInt32KeyNode`1 node)
     at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator..ctor(SortedInt32KeyNode`1 root)
     at System.Collections.Immutable.ImmutableDictionary`2.Enumerator..ctor(SortedInt32KeyNode`1 root, Builder builder)
     at System.Collections.Immutable.ImmutableDictionary`2.GetEnumerator()
     at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 arrayIndex)
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<>c__DisplayClass0.<_ctor>b__1()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<_ctor>b__4()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at System.Lazy`1.get_Value()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.GetMergedReferenceDirectives()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.get_ReferenceDirectives()
     at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)
     at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
     at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
     at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
     at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBoundReferenceManager()
     at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.CSharp.targets(316,9): error MSB6006: "csc.exe" exited with code 255. 
```

with csc2.exe we're getting 
`error MSB6006: "csc2.exe" exited with code -1073741568. `

this doesn't look like the same issue as #969. Any ideas?

**Comment by jakeswenson** [comment] 2015-04-23 04:20
Roslyn is probably not the right place for this. Found this issue https://github.com/dotnet/corefx/issues/320 and related #110

will try the kb install from there.

**Comment by jakeswenson** [comment] 2015-04-23 04:23
Closing until i try the kb update.

**Comment by jakeswenson** [comment] 2015-04-23 14:43
@theoy any word on when we can get access to rc2? or some pre-rc2-release with the fix for this?

**Comment by Pilchie** [comment] 2015-04-23 14:54
@jakeswenson You can pick up our nightly package builds from https://www.myget.org/F/roslyn-nightly.

**Comment by jakeswenson** [comment] 2015-05-04 22:19
@Pilchie i have tried the latest public drop (1.0.0-rc2) and it is still failing with

```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
     at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)
     at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.PushLeft(SortedInt32KeyNode`1 node)
     at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator..ctor(SortedInt32KeyNode`1 root)
     at System.Collections.Immutable.ImmutableDictionary`2.Enumerator..ctor(SortedInt32KeyNode`1 root, Builder builder)
     at System.Collections.Immutable.ImmutableDictionary`2.GetEnumerator()
     at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 arrayIndex)
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<>c__DisplayClass5_0.<.ctor>b__0()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<.ctor>b__5_3()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at System.Lazy`1.get_Value()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.GetMergedReferenceDirectives()
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at Microsoft.CodeAnalysis.CSharp.DeclarationTable.get_ReferenceDirectives()
     at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)
```

**Comment by jakeswenson** [comment] 2015-05-04 22:20
```
D:\replaced\.build\packages\Microsoft.Net.Compilers.1.0.0-rc2\tools\csc2.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+
```
```
C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.CSharp.targets(316,9): error MSB6006: "csc2.exe" exited with code 255.
```

**Comment by Pilchie** [comment] 2015-05-04 22:22
tag @jaredpar

**Comment by jakeswenson** [comment] 2015-05-05 17:03
fyi, i'm going to lose my repro, as I requested to have our build machines upgraded to 4.5.2...

**Comment by jaredpar** [comment] 2015-05-06 01:28
@jakeswenson what version of .Net are you currently using that is about to be upgrade?

**Comment by jaredpar** [comment] 2015-05-06 01:28
@VSadov does this ring a bell.

**Comment by jakeswenson** [comment] 2015-05-06 15:29
@jaredpar let me find that out for you.

**Comment by jakeswenson** [comment] 2015-05-06 15:52
@jaredpar clrver says:
> Microsoft (R) .NET CLR Version Tool  Version 4.0.30319.17929
> Copyright (c) Microsoft Corporation.  All rights reserved.
>
> Versions installed on the machine:
> v2.0.50727
> v4.0.30319

csc (from the installed framework) returns

> Microsoft (R) Visual C# Compiler version 4.0.30319.18408
>
> for Microsoft (R) .NET Framework 4.5
> Copyright (C) Microsoft Corporation. All rights reserved.

so my guess is that it's vanilla 4.5

There was supposedly a fix for this in immutable collections (see linked items i mentioned) but i'm guessing that didn't make it into the rc2 package?

**Comment by jaredpar** [comment] 2015-05-06 16:00
@jakeswenson that appears to be the case.  Even though the immutable collections fix was submitted in February we didn't sync up to it until just last month.  

> https://github.com/dotnet/roslyn/commit/7bb52b2d2951237ebf9c267618559fee2954f183#diff-ddd170fccec95221f27b3ae2052bdbf3

There were several internal integration issues that made it difficult to consume the newer version because of the API changes (most of which were authored by me :frowning: ). Newer drops of Microsoft.Net.Compilers will have the patched version of the immutable collections and avoid this.  

Going to close on it being a dupe of #110.  Please re-open if my analysis is off here.

**Comment by jakeswenson** [comment] 2015-05-06 16:01
@jaredpar sounds good. That means the nightlys will have it, right?

**Closed by jaredpar** 2015-05-06 16:00 UTC
Labels: Area-Compilers

**Comment by jaredpar** [comment] 2015-05-06 16:01
@jakeswenson yes.

**Comment by VSadov** [comment] 2015-05-06 16:45
yes it is a dupe of  #110 
And yes nightlies should have newer Immutable.Collections which should not cause the problem.

**Comment by jakeswenson** [comment] 2015-05-11 20:32
@jaredpar @Pilchie are nightly packages not retained? Seems like this package is nolonger available?
https://www.myget.org/F/roslyn-nightly/Packages(Id='Microsoft.Net.Compilers',Version='1.0.0-rc3-20150505-04')

This is very problematic when trying to get this working on the build machines.

**Comment by jaredpar** [comment] 2015-05-11 21:22
@jakeswenson we only keep the last ~10 builds on our MyGet feed.  There is a size restriction by default on MyGet and that is about as much as we can fit on there. 

Could you copy them down locally or throw them on a share where the build machines could get access?

**Comment by jakeswenson** [comment] 2015-05-11 22:24
@jaredpar OK, as long as this is expected. i'll look into workarounds. Can't wait for a public drop fixing this though... :smile:
