### ISSUE TITLE
There's no way to get a display string for a NamedType with access modifiers

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn#38950] opened 2019-09-30 09:18 UTC
**Version Used**: 

Microsoft.CodeAnalysis.CSharp (2.10.0)
Microsoft.CodeAnalysis.VisualBasic (2.10.0)

**Steps to Reproduce**:

Create a class:

```csharp
public class GenericType<U, V>
    where U : struct
    where V : class, System.IDisposable
{
    public System.Collections.Generic.IEnumerable<U> Method(V v) => null;
}
```

Declare a display format like this:

```csharp
private static SymbolDisplayFormat DeclarationDisplayFormat =
    new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
            genericsOptions:
                SymbolDisplayGenericsOptions.IncludeTypeParameters|
                SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                SymbolDisplayGenericsOptions.IncludeVariance,
            memberOptions:
                SymbolDisplayMemberOptions.IncludeParameters |
                SymbolDisplayMemberOptions.IncludeType |
                SymbolDisplayMemberOptions.IncludeRef |
                SymbolDisplayMemberOptions.IncludeModifiers |
                SymbolDisplayMemberOptions.IncludeAccessibility |
                SymbolDisplayMemberOptions.IncludeExplicitInterface |
                SymbolDisplayMemberOptions.None,
            extensionMethodStyle:
                SymbolDisplayExtensionMethodStyle.Default,
            parameterOptions:
                SymbolDisplayParameterOptions.IncludeName |
                SymbolDisplayParameterOptions.IncludeType |
                SymbolDisplayParameterOptions.IncludeParamsRefOut |
                SymbolDisplayParameterOptions.IncludeDefaultValue |
                SymbolDisplayParameterOptions.IncludeExtensionThis |
                SymbolDisplayParameterOptions.None,
            propertyStyle:
                SymbolDisplayPropertyStyle.ShowReadWriteDescriptor,
            localOptions:
                SymbolDisplayLocalOptions.IncludeType |
                SymbolDisplayLocalOptions.IncludeRef |
                SymbolDisplayLocalOptions.None,
            kindOptions:
                SymbolDisplayKindOptions.IncludeMemberKeyword |
                SymbolDisplayKindOptions.IncludeTypeKeyword,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
```

Call, `symbol.ToDisplayString(DeclarationDisplayFormat)` on the symbol for the class.

**Expected Behavior**:

`public class GenericType<U, V> where U : struct where V : class`

**Actual Behavior**:

`class GenericType<U, V> where U : struct where V : class`

**Comment by JosefPihrt** [comment] 2019-10-01 14:09
A duplicate of #28297

**Closed** 2019-10-01 18:10 UTC
Labels: Area-Compilers
