### ISSUE TITLE
Cannot Create New Code Fix Project

### ISSUE THREAD

**Issue by ajvnd** [dotnet/roslyn#48739] opened 2020-10-18 09:50 UTC
**Visual Studio 2019 16.7.6**

**Steps to Reproduce**:

choose File > New > Project... to display the New Project dialog.
Under Visual C# > Extensibility, choose Analyzer with code fix (.NET Standard).

**Expected Behavior**:
create new code fix project

**Actual Behavior**:
error dialog : the path is not of a legal form code

**Comment by sharwell** [comment] 2020-10-19 21:23
Duplicate of dotnet/roslyn-sdk#583

**Closed by sharwell** 2020-10-19 21:23 UTC
Labels: Area-IDE, untriaged
