### ISSUE TITLE
stacktrace explorer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41557] opened 2020-02-10 21:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/908301/stacktrace-explorer.html)._

---
Would be useful to add a stacktrace explorer/tool where i can paste a stacktrace collected from external logs or reported but and be able to navigate to the code accordingly,
Resharper has a similar feature. VS support to navigate to teh code from stacktrace only when the stacktrace is coming from a test, here i don't have a test, but a stractrace in the clipboard. 
see https://www.jetbrains.com/help/resharper/Reference__Windows__Stack_Trace_Explorer.html

---
#### Visual Studio Feedback System on 2/5/2020, 05:50 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by saratcmar** [comment] 2021-05-27 19:30
![VS_StackView2](https://user-images.githubusercontent.com/58489726/119885653-f2c9d080-bee6-11eb-86ad-1ae194427634.JPG)
![VS_StackView1](https://user-images.githubusercontent.com/58489726/119885656-f3626700-bee6-11eb-9fde-e94f3bfff2e5.JPG)
The easiest part with resharper stack view tool is that i can copy a stack from logs in a editor and just move focus to the VS instances. It automatically opens the stack explorer with ability to click on the function or on the line number (not available in this example) and navigate to code within the solution. Couple this with ability to navigate to implementation via decompiled code for external libraries, i can continue my navigation from stack to other libraries as well.

**Comment by ryzngard** [comment] 2021-09-10 05:44
There's a current implementation going through UX review tomorrow. This will be ready for next IDE Design review. See #56315 for current UX experience

**Comment by alrz** [comment] 2021-09-10 08:54
Will this be available in a failed test results?

**Comment by ryzngard** [comment] 2021-09-10 18:32
@alrz Test execution should already have a more formal stack trace with clickable links. AFAIK since it has context to the [StackFrame](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stackframe?view=net-5.0) it doesn't need to worry about parsing and deserializing the string output. This is for cases where we've already lost that context and try to rebuild it

**Comment by ryzngard** [comment] 2021-09-13 19:31
# General Design

## Parsing

Parsing will be done on a line by line basis, such that each line is considered the string split of ` \n` . This has 2 benefits: 

1. If extra text is copied in the clipboard we can still correctly identify items to navigate
2. I no expected input is seen, we can still show the user the contents that we tried to parse.

The parser for each line is extensible to handle more cases, but for now we will support the following forms of input: 


### Dotnet StackTrace Output

[Dotnet StackTrace](https://docs.microsoft.com/en-us/dotnet/api/system.environment.stacktrace?view=net-5.0#remarks) is a well documented output form. This is what usually happens when a StackTrace is serialized to string format, and what we believe the most common use case will be. 

The form is defined as: 
```
at FullClassName.MethodName(MethodParams) in FileName :line LineNumber
```

The user will be able to click on `FullClassName` to navigate to the class, `MethodName(MethodParams)` to navigate to the method, and ` FileName :line LineNumber` to navigate to the file at the specified line. The `FileName` section is optional, and we will parse correctly without it.

### Debugger CallStack Window

Another acceptable form is copying from the Debugger CallStack window directly. This should be supported since the output is generally well formed, but we do not believe the usage of this will be high. It does provide a more complete experience though.

The CallStack window text copies as such: 

```
ModuleName!FullClassName.MethodName(MethodParams)
```

The user will be able to click `FullClassName` to navigate to the class, and `MethodName(MethodParams)` to navigate to method. No filename information is included by default. ModuleName will be ignored for now, but could provide information in the future to help differentiate symbols. 

## Showcase of UX

This is a showcase of the UX for discussion purposes and is subject to change: 

![3428a5ea-2147-4b91-9ae8-14561b491b65](https://user-images.githubusercontent.com/475144/132805465-26c0aa2a-6eaf-439e-808c-ee3153a00f0c.gif)

**Comment by NTaylorMullen** [comment] 2021-09-20 21:07
### Design Meeting Notes

![image](https://user-images.githubusercontent.com/2008729/134075849-38a67f51-baec-4603-a57d-816a2bea952d.png)


@ryzngard For the textual content (not picture) of the notes grab them from [the one note page](https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook%20-%20New&wd=target%28Productivity%2FDesignNotes.one%7C880CC013-DE86-4132-9498-4103CFFCE58A%2F9%5C%2F20%5C%2F2021%7C75617FE6-939F-4D91-AF2A-0EEC5E545439%2F%29
onenote:https://microsoft.sharepoint.com/teams/managedlanguages/files/Team%20Notebook/Roslyn%20Team%20Notebook%20-%20New/Productivity/DesignNotes.one#9/20/2021&section-id={880CC013-DE86-4132-9498-4103CFFCE58A}&page-id={75617FE6-939F-4D91-AF2A-0EEC5E545439}&end). GitHub wasn't formatting well 😄

**Comment by ryzngard** [comment] 2021-09-20 23:21
Categorizing items from design review: 

### UX 
* [ ] Provide better display for async code
* [ ] View as columns

### Discoverability
* [ ] Add "Open in Stack Trace Viewer" to right click menu
* [ ] Automatically open if stack trace is in the clipboard when VS is opened

### Navigation
* [ ] Change to use "Go to definition" as code for navigating to a symbol
* [ ] Double click anywhere on line take you to most specific symbol available 

### VS Integration
* [ ] Use Debugger "go to file" API 
* [ ] Investigate reusing "Call stack" view 
* [ ] Work with Test Explorer 
* [ ] Automatically work on Output Window 
* [ ] Click inside comments/string with stack traces without having to open tool

### Experience Polish
* [ ] Decode common newline characters (copy from activitylog.xml log for example) 
* [ ] Handle event viewer output
* [ ] Enable RichNav for symbol resolution

**Comment by ryzngard** [comment] 2021-11-11 22:17
Marking this as closed. Future improvements are in the works but the bulk of the issue is done and shipping in 17.1 Preview 2

**Closed by ryzngard** 2021-11-11 22:17 UTC
Labels: Area-IDE, Feature Request, Need Design Review, Dev17 IDE Priority
