### ISSUE TITLE
OpenSolutionAsync - first 5 projects have empty Documents

### ISSUE THREAD

**Issue by piotr-polanski** [dotnet/roslyn#19978] opened 2017-06-02 05:12 UTC
Microsoft.CodeAnalysis: 2.1.0 

I have solution with 29 projects and after using OpenSolutionAsync only last 24 projects have Documents in them. I tried to hook up to WorspaceFailed event, but it didn't fired.

Any help will be appreciated.
Source code can be found here:
https://github.com/piotr-polanski/EyeOfBeholder/blob/develop/EyeOfBeholder.Uml/UmlEntitiesExtractor.cs

**Comment by Pilchie** [comment] 2017-06-02 17:22
@piotr-polanski can you try the 2.3 packages?  More logging was added to `WorkspaceFailed` then.

**Comment by piotr-polanski** [comment] 2017-06-02 18:19
@Pilchie I've tried erlier with 3.0 and there was nothing...

**Comment by Pilchie** [comment] 2017-06-02 18:21
Can you share one of the projects that gets no documents with us?  (It can be privately over email if you don't want to post here).

**Comment by piotr-polanski** [comment] 2017-06-02 18:23
unfortunately no. Company policy...

**Comment by dlech** [comment] 2017-06-07 18:07
I'm seeing a similar issue in docfx. Unfortunately, I can't reproduce with a simple test case. But, here is how you can observe the problem in docfx itself:

1. Clone https://github.com/dotnet/docfx
2. Clone https://github.com/docascode/docfx-seed
3. Open `All.sln` in the docfx repository in Visual Studio
4. In Visual Studio, select the `docfx` project and open the properties.
5. On the debug page, set Working Directory to the location where you cloned docfx-seed

    ![image](https://user-images.githubusercontent.com/963645/26893311-90a12d3c-4b80-11e7-8f5f-55a9899c2312.png)

6. Create a breakpoint at [src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs:202](https://github.com/dotnet/docfx/blob/0fed632c81d3129e748097dbe4298ffae76f1c30/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs#L202)

7. Run the docfx project and wait for it to hit the breakpoint.
8. Inspect the `project` variable and note that it has no documents.

    ![image](https://user-images.githubusercontent.com/963645/26893749-d7230ed2-4b81-11e7-8f02-4f01baebba55.png)

9. Continue iterating the loop and notice that the other two projects also have no documents.

**Comment by dlech** [comment] 2017-06-07 18:24
I added a listener to `WorkspaceFailed` as suggested and got:

> {[Failure] Msbuild failed when processing the file 'C:\Users\david\Documents\Junk\docfx-seed\src\SampleClass1\CatLibrary\CatLibrary.csproj' with message: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.}

**Comment by dlech** [comment] 2017-06-07 19:00
After adding the System.Threading.Tasks.Dataflow 4.5.24 nuget package, I get:

> {[Failure] Msbuild failed when processing the file 'C:\Users\david\Documents\Junk\docfx-seed\src\SampleClass1\CatLibrary\CatLibrary.csproj'}

Then I upgrade all of the Microsoft.CodeAnalysis.* packages from 2.0.0 to 2.3.0-beta1 and got the more informative message:

> Msbuild failed when processing the file 'C:\Users\david\Documents\Junk\docfx-seed\src\SampleClass1\CatLibrary\CatLibrary.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (71, 5): The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

So, I tried to install Microsoft.Build.Utilities.Core 14.0.0, but this version does not exist on nuget.

I guess I will keep digging...

**Comment by Pilchie** [comment] 2017-06-07 19:08
@dlech: that sounds like an indication that you need to have binding redirects to redirect things to their 15.1 version.  https://github.com/dotnet/roslyn/issues/2779 has some info, though the version numbers to redirect to are wrong now.

**Comment by dlech** [comment] 2017-06-07 19:17
BTW, the docfx project uses Microsoft.Build.Utilities.Core 15.1.548 from nuget. Any bright ideas for resolving this versioning issue?

**Comment by Pilchie** [comment] 2017-06-07 20:12
@dlech You need to look at the *assembly version* of those assemblies and use it as the target in the binding redirects described in #2779.

**Comment by dlech** [comment] 2017-06-07 21:36
Thanks for the advice. I was able to fix the error by manually editing `docfx.exe.config` and adding...

```

    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Conversion.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Tasks.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Utilities.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="14.0.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
````

Now, to figure out how to get it to do that automatically...

**Comment by Pilchie** [comment] 2017-06-07 21:44
@dlech Adding an `app.config` file to your project (or editing the existing one), should cause the build to copy it to the output directory and rename it, etc.

**Comment by dlech** [comment] 2017-06-07 22:56
Thank you once again. It looks like OpenSolutionAsync() is working correctly now.

I think we can conclude that, at least in my case, the problem is caused by the fact that docfx is trying to use a mix of nuget and system dlls.

FWIW, I ran my patched version of docfx on another project and got a new error...

> [Failure] Msbuild failed when processing the file 'C:\Users\david\Documents\GitHub\Dandy.Lms\src\Bytecodes.Test\Bytecodes.Test.csproj' with message: C:\Users\david\.nuget\packages\microsoft.packaging.tools\1.0.0-preview1-25301-01\build\Microsoft.Packaging.Tools.targets: (60, 5): The "HandlePackageFileConflicts" task could not be instantiated from the assembly "C:\Users\david\.nuget\packages\microsoft.packaging.tools\1.0.0-preview1-25301-01\build\desktop/Microsoft.Packaging.Tools.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.DotNet.Build.Tasks.HandlePackageFileConflicts' to type 'Microsoft.Build.Framework.ITask'.

I think this game could go on forever, so I'm going to have to give up for now.

**Comment by rogeralsing** [comment] 2017-07-08 11:41
I am having the same problem, I've tried with the current prerelease bits and problem is still there.
https://github.com/rogeralsing/ProjectExodus

Trying to open this solution: https://github.com/AsynkronIT/protoactor-dotnet

All the multi target projects report 0 documents.

**Comment by matkoch** [comment] 2017-09-23 14:16
@matkoch

**Comment by AlexeiScherbakov** [comment] 2017-09-24 21:34
I have same problem with latest NuGet packages:
Microsoft.Build - 15.3.409
Microsoft.Build.Tasks.Core - 15.3.409
Microsoft.CodeAnalysis - 2.3.2

MsBuildWorkspace diagnostic message:
Msbuild failed when processing the file '*.csproj' with message: Не удалось загрузить файл или сборку "System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.

If I manually add this package - all .net core projects are loaded without warning, but they are empty.

All worked before Visual Studio 2017 Update 3.

**Comment by HamedFathi** [comment] 2020-05-17 08:24
Unfortunately, I have this problem too

I created a simple console application via `dotnet new console`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

Then I wrote a block of code in another application to get the compilation result by Roslyn

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.8.0" />
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="3.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="3.6.0-4.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.6.0-4.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.6.0-4.final" />
    <PackageReference Include="Microsoft.Build" Version="16.5.0" />
    <PackageReference Include="PowerArgs" Version="3.6.0" />
  </ItemGroup>

</Project>
```

```cs
var workspace = MSBuildWorkspace.Create();
workspace.LoadMetadataForReferencedProjects = true;
var project = workspace.OpenProjectAsync(@"C:\...\Desktop\sample\sample.csproj").Result;
var compilation = project.GetCompilationAsync().Result;
```

But length of Documents is empty so I wrote another block of code to find out what was the problem

```cs
var diagnostics = workspace.Diagnostics;
foreach (var diagnostic in diagnostics)
{
    Console.WriteLine(diagnostic.Message);
}
```
The error is:
```
Msbuild failed when processing the file 'C:\...\Desktop\sample\sample.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\...\Desktop\sample\sample.csproj
```

My dotnet core info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

What should I do to get result?

**Comment by smaudet** [comment] 2021-03-16 16:06
Just a hunch but this happened to me, this bug seems maybe related: https://github.com/dotnet/roslyn/issues/41331

I have MSBuild 14.0 installed in my GAC, so even with the MSBuild.Build.Locator installed (the new api to look for 15.0 + versions) it was defaulting to 14.0. For some strange reason some of my projects are using tools version 15, others are using 14 - the ones using 14 worked, the ones using 15 did not - I had *also* installed the 15.0 version of msbuild tools using nuget. However, it seemed like this actually disabled the build locator. For me what is (currently) working is to use the Build Locator with 14.0 installed in GAC - this seems to function as desired - msbuild is able to parse and use 14.0 projects with 14.0 tools and 15.0 projects using the build locator tools.

Why it works this way at all is beyond me - I presume there's legacy stuff in MS build which makes sandboxing the versions difficult, but I would have preferred if the build locator could just "magically" locate *all* versions of the tooling and then apply per project...

**Comment by CyrusNajmabadi** [comment] 2023-11-22 18:38
Maybe a misconfigred msbuild?  Does the msbuild workspace return any diagnostics?

**Closed by CyrusNajmabadi** 2023-11-22 18:38 UTC
Labels: Bug, Area-IDE
