### ISSUE TITLE
VS is unresponsive during a build.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11863] opened 2016-06-08 20:30 UTC

**Comment by Pilchie** [comment] 2016-06-22 18:22
Can we get a trace and find out why VS is not handling messages?

**Comment by AdamSpeight2008** [comment] 2016-06-22 19:01
Could related to Issue #11942 on the Priorioty level used.

**Comment by AdamSpeight2008** [comment] 2016-08-01 18:00
@Pilchie
Does the change in the milestone, indicate that the issue is fixed?

**Comment by Pilchie** [comment] 2016-08-01 18:08
No, if it was fixed, it would be closed.  It means that we won't hold the Preview 4 milestone for this.

**Comment by CyrusNajmabadi** [comment] 2020-03-02 19:16
No data provided here.  Closing out.

**Closed by CyrusNajmabadi** 2020-03-02 19:16 UTC
Labels: Area-IDE, Bug, Perf-Epic
