### ISSUE TITLE
No completion when typing break after case with pattern matching

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#19482] opened 2017-05-13 22:14 UTC
**Version Used**: 
VS 2017 Update 2

**Steps to Reproduce**:

In a C# file, paste this code:

```
class C
{
    void M()
    {
        switch (foo)
        {
            case Bar bar:
                $$
            default: break;
        }
    }
}
```

Type break where the $$ is.

**Expected Behavior**:
Completion offering "break".

**Actual Behavior**:
No completion.

**Comment by CyrusNajmabadi** [comment] 2017-05-14 20:33
Dupe of https://github.com/dotnet/roslyn/issues/15348

**Closed by CyrusNajmabadi** 2017-05-14 20:33 UTC
Labels: Area-IDE, Bug
