### ISSUE TITLE
VB implement abstract class adds NullableAttributes

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#60963] opened 2022-04-26 18:23 UTC
**Version Used**: 
Version 17.3.0 Preview 1.0 [32421.362.main]

**Steps to Reproduce**:

1. Create VB project referencing C# project
```VB
Public Class D
    Inherits C
End Class
```

```C#
#nullable enable
public abstract class C
{
    public abstract C? F(C? arg1, C arg2);
}
```

3. 
![image](https://user-images.githubusercontent.com/41759/165366906-2dd78b61-9f89-47f3-a972-c956470a480c.png)

**Comment by Youssef1313** [comment] 2022-04-27 06:14
Duplicate of https://github.com/dotnet/roslyn/issues/42920

**Closed** 2022-04-28 18:23 UTC
Labels: Resolution-Duplicate, Area-IDE
