### ISSUE TITLE
Accessing an unitialized array throws a NullReferenceException but at the wrong line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42994] opened 2020-04-01 19:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/969914/accessing-an-unitialized-array-throws-a-nullrefere.html)._

---
Consider the following code to reproduce:

```
static string[] SomeArray = null;

static void Main(string[] args)
{
    SomeArray[1] = string. Empty; // Line #15
    DoSomething(); // Line #16
}
static void DoSomething() { }

```

Obviously, `SomeArray` is never initialized and trying to access it (at line #15) would throw a NullReferenceException. However, the debugger shows the exception at the next line (line #16) and the stack trace is as follows:

`>	ConsoleApp1.exe! ConsoleApp1.Program.Main(string[] args) Line 16	C#`

I was able to reproduce this on both VS2017 and VS2019.

---
#### Visual Studio Feedback System on 3/31/2020, 00:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by YairHalberstadt** [comment] 2020-04-02 13:38
Is this a debug or release build?

**Comment by jcouv** [comment] 2020-04-03 15:29
I can repro this (16.6p2, Debug configuration for the project). The highlight for the breakpoint currently shows `DoSomething()` which is incorrect.
It could be a sequence point or a debugger issue.

**Comment by jcouv** [comment] 2020-04-03 16:01
Tagging @cshung 
FYI @gafter @chuckries 

I verified that the sequence points are produced as I expect (see repro below).
This feels much like this previously reported issue: https://github.com/dotnet/roslyn/issues/33995 where the thrown exception is shown one instruction too late.

``` csharp
        [Fact, WorkItem(42994, "https://github.com/dotnet/roslyn/issues/42994")]
        public void Repro()
        {
            string source = @"
class C
{
    static string[] SomeArray = null;

    static void M()
    {
        SomeArray[1] = string. Empty;
        DoSomething();
    }
    static void DoSomething() { }
}
";
            var compilation = CompileAndVerify(source);

            compilation.VerifyIL("C.M",
@"
{
  // Code size       18 (0x12)
  .maxstack  3
  // sequence point: SomeArray[1] = string. Empty;
  IL_0000:  ldsfld     ""string[] C.SomeArray""
  IL_0005:  ldc.i4.1
  IL_0006:  ldsfld     ""string string.Empty""
  IL_000b:  stelem.ref
  // sequence point: DoSomething();
  IL_000c:  call       ""void C.DoSomething()""
  // sequence point: }
  IL_0011:  ret
}
", sequencePoints: "C.M", source: source);
        }
```

**Comment by cshung** [comment] 2020-04-07 23:10
@dotnet/dotnet-diag

**Comment by tommcdon** [comment] 2020-04-08 17:08
@mikem8361 seems similar to https://github.com/dotnet/runtime/issues/34226

**Comment by mikem8361** [comment] 2020-04-08 17:11
Yes, it is. This issue could be linked to that one and closed.

**Comment by jcouv** [comment] 2020-04-08 20:16
Thanks. Closing as duplicate of https://github.com/dotnet/runtime/issues/34226

**Closed by jcouv** 2020-04-08 20:16 UTC
Labels: Area-Compilers, Area-External
