### ISSUE TITLE
Limit "Go to all" results to improve performance

### ISSUE THREAD

**Issue by saul** [dotnet/roslyn#18253] opened 2017-03-28 18:06 UTC
"Go to all" currently causes a UI freeze of around 10 seconds on my machine when I try to search for something broad like "a". Even if I have a particularly narrow search, the freeze is still very noticeable.

I originally thought this was because we were doing an async as RunSyncronously, but it turns out 99.9% of the time is spent in WPF UpdateLayout. I assume this is because we're returning a huge number of results - it makes more sense if we 'cap' the number of results we return to the top 50 or so.

We've tried filtering the results to exact matches on the F# side, but it hasn't made much of a dent in the UI freeze. See https://github.com/Microsoft/visualfsharp/pull/2716.

See also https://github.com/Microsoft/visualfsharp/issues/2710 for the original F# issue.

#### Repro steps

1. Open VisualFSharp.sln
2. Go to all > Search "a"
3. See the UI freeze

#### Expected behavior

No UI freeze

#### Actual behavior

UI is frozen for many seconds

#### Related information

![image](https://cloud.githubusercontent.com/assets/64654/24376804/1e1f8f48-1335-11e7-9ae2-cb0a8368c74e.png)

**Comment by jasonmalinowski** [comment] 2017-03-28 21:09
In Theory(tm) we'll only be creating UI elements for the elements actually being shown...does it look like that's not happening?

**Comment by jasonmalinowski** [comment] 2017-03-28 21:11
This might be a semi-dupe or related to #8260 but this one actually has info.

**Comment by saul** [comment] 2017-03-28 21:21
I mean looking at the UI thread freeze and the stack trace of where the time was spent, it certainly looks like the UI elements aren't created on the fly.

**Comment by Pilchie** [comment] 2017-03-29 02:18
@rchande have you had a chance to look at the traces you had for this in C#? Is this the same issue, and should we just be moving this to the platform team?

**Comment by CyrusNajmabadi** [comment] 2017-03-29 04:20
When i profiled i saw a ton of perf taken by requests for glyphs.  If the platform is asking us for all the glyphs for all the items, that would definitely explain why things have gotten so much slower.

**Comment by rchande** [comment] 2017-03-29 15:44
@CyrusNajmabadi What's the name of the API we implement for getting glyphs? I'm not seeing anything like that in my trace. I see:
* Lots of time serializing symbols
* Lots of GC time

So probably need to serialize fewer symbols (why would we do that?) and generally reduce allocations in this path.

**Comment by rchande** [comment] 2017-03-29 16:04
We allocate a lot of strings in the `     |  || ||+ microsoft.codeanalysis.features!Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService+SearchResult.ConstructSecondarySortString(class Microsoft.CodeAnalysis.Document,value class Microsoft.CodeAnalysis.FindSymbols.DeclaredSymbolInfo)
` path.

**Comment by rchande** [comment] 2017-03-29 16:04
We also allocate a lot of strings from the `PatternMatcher` calling string.substring.

**Comment by rchande** [comment] 2017-03-29 16:05
Our largest set of string allocations comes from reading in texts:
```C#
Name
     |  |+ mscorlib.ni!String.CtorCharArrayStartLength
     |  ||+ microsoft.visualstudio.platform.vseditor.ni!Microsoft.VisualStudio.Text.Implementation.SimpleTextStorageLoader+<DoLoad>d__4.MoveNext()
     |  |||+ microsoft.visualstudio.platform.vseditor.ni!SimpleStringRebuilder.Create
     |  ||| + microsoft.visualstudio.platform.vseditor.ni!BufferFactoryService.CreateTextBuffer
     |  |||  + microsoft.visualstudio.platform.vseditor.ni!BufferFactoryService.CreateTextBuffer
     |  |||   + microsoft.codeanalysis.editorfeatures.ni!EditorTextFactoryService.CreateText
     |  |||    + microsoft.codeanalysis.workspaces.desktop.ni!Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+TemporaryStorageService+TemporaryTextStorage.ReadText(System.Threading.CancellationToken)
     |  |||     + microsoft.codeanalysis.workspaces.desktop.ni!Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+TemporaryStorageService+TemporaryTextStorage+<>c__DisplayClass11_0.<ReadTextAsync>b__0()
```

**Comment by rchande** [comment] 2017-03-29 16:07
This delegate allocated by the platform shows up http://index/?query=navigatetosearchoperation.additemworker&rightProject=Microsoft.VisualStudio.Shell.UI.Internal&file=Packages%5CNavigateTo%5CNavigateToSession_SearchOperation.cs&line=200

**Comment by Pilchie** [comment] 2017-03-29 16:43
What are we reading texts for?  The *idea* is that we have enough info in the declaration table to produce the non-UI requirements for matches without allocating symbols, and it's only for things that are displayed that we need to realize symbols/read texts/etc.

Maybe we added something to the sort string that is requiring us to fetch symbols or syntax again?

**Comment by rchande** [comment] 2017-03-29 19:54
It looks like we're running analyzers at the same time (DesignerCategoryAttributeAnalyzer). The tree serialization could be part of that. Is there a mechanism we could use to suspect solution crawler while we navigate? @heejaechang

**Comment by heejaechang** [comment] 2017-03-29 20:01
@rchande tree serialization is not related to DesignerCategoryAttributes. so I don't think it matter.. and I know goto realize and create symbols on UI thread if I remember correctly, so that could be the issue.

anyway, for your question, you can use this service - http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Notification/IGlobalOperationNotificationService.cs,a6a744255f7fe6a5,references - to pause solution crawler.

**Comment by davidroth** [comment] 2017-06-08 14:53
Go to all is painfully slow in our solution and frequently causes nasty UI freezes for several seconds. 
Considering that this functionality is used hundreds of times a day, I am a bit disappointed that this is targeted for 15.6 only.

**Comment by Pilchie** [comment] 2017-06-08 14:56
The core editor team is also looking at this, and may have a fix for 15.3.  @hemchans - any update on that investigation?

**Comment by hemchans** [comment] 2017-06-08 16:38
@AmadeusW is looking at this as part of 15.3 Bug 404590: NavigateTo/GoTo performance is very slow on Roslyn.sln.

**Comment by heejaechang** [comment] 2017-06-08 17:00
@CyrusNajmabadi @Pilchie @hemchans somehow, cyrus's work to make navigate to to run on OOP removed all those UI freeze.

**Comment by Pilchie** [comment] 2017-06-08 17:04
I think the issue is that the platform is asking for the display strings of all the items.  Since @CyrusNajmabadi made that get computed OOP, we just won't return results to the platform until we have them.

**Comment by hemchans** [comment] 2017-06-08 17:07
@Pilchie @CyrusNajmabadi did Cyrus' changes get into 15.3 yet? Or is that 15.6 work?

**Comment by Pilchie** [comment] 2017-06-08 17:26
It's not *yet* in 15.3, but the plan is to have it there with an option to enable, but off by default.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 19:16
My changes just went in, behind a user-facing flag.  We're hoping to get enough dogfooding coverage to be able to just flip the switch on it.  We also have hooked this up to an A/B flag so we can enable after shipping if we have high enough confidence on it.

**Comment by rchande** [comment] 2017-07-21 16:37
@CyrusNajmabadi @Pilchie Did Cyrus' change get in? Can we close this?

**Comment by Pilchie** [comment] 2017-07-21 17:14
We can close this - the platform took a change to limit results centrally.

**Closed by Pilchie** 2017-07-21 17:14 UTC
Labels: Area-IDE, Bug, Tenet-Performance
