### ISSUE TITLE
using latest visual studio update 2 rc debugger variable context stopped working

### ISSUE THREAD

**Issue by 1amirjalai** [dotnet/roslyn#10163] opened 2016-03-29 12:15 UTC
**Version Used**: 
latest stable version on visual studio update 2 rc

**Steps to Reproduce**:

1. install visual studio update 2 rc
2. create new project using asp.net mvc core template
3. debug the app

**Expected Behavior**:
To be able to debug the asp.net application
![expected](https://cloud.githubusercontent.com/assets/2786675/14107395/2336f45c-f5cd-11e5-9ecc-9372e99c07c6.jpg)

**Actual Behavior**:

I can't explore context of variable inside visual studio editor or immediate windows i get the following error in immediate windows

![actual](https://cloud.githubusercontent.com/assets/2786675/14107459/8e4621e6-f5cd-11e5-9141-17d7acb7df5a.jpg)

error CS0103: The name 'myvariable' does not exist in the current context

http://stackoverflow.com/questions/36284093/visual-studio-2015-update-2-rtm-and-rc-debugging-context-not-available

**Comment by ManishJayaswal** [comment] 2016-04-26 01:16
This was caused by a debugger issue which I believe has been fixed in Update 2 RTM.

**Closed by ManishJayaswal** 2016-04-26 01:16 UTC
Labels: Area-Interactive

**Comment by 1amirjalai** [comment] 2016-04-26 05:55
a patch has been released
http://stackoverflow.com/questions/36284093/visual-studio-2015-update-2-rtm-and-rc-debugging-context-not-available
