### ISSUE TITLE
TestDefaultDiagnosticProviderRemove is flaky

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#46230] opened 2020-07-22 20:57 UTC
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#739651](https://dev.azure.com/dnceng/public/_build/results?buildId=739651)|#46176|1|
|[#739718](https://dev.azure.com/dnceng/public/_build/results?buildId=739718)|#46179|1|
|[#739874](https://dev.azure.com/dnceng/public/_build/results?buildId=739874)|#46183|1|
|[#739896](https://dev.azure.com/dnceng/public/_build/results?buildId=739896)|#45800|1|
|[#740061](https://dev.azure.com/dnceng/public/_build/results?buildId=740061)|#46194|1|
|[#740083](https://dev.azure.com/dnceng/public/_build/results?buildId=740083)|#46138|1|
|[#740155](https://dev.azure.com/dnceng/public/_build/results?buildId=740155)|#45806|1|
|[#740370](https://dev.azure.com/dnceng/public/_build/results?buildId=740370)|Rolling|1|
|[#740378](https://dev.azure.com/dnceng/public/_build/results?buildId=740378)|Rolling|1|
|[#740397](https://dev.azure.com/dnceng/public/_build/results?buildId=740397)|Rolling|1|
|[#740404](https://dev.azure.com/dnceng/public/_build/results?buildId=740404)|#46189|1|
|[#740484](https://dev.azure.com/dnceng/public/_build/results?buildId=740484)|#44447|1|
|[#740543](https://dev.azure.com/dnceng/public/_build/results?buildId=740543)|#46199|1|
|[#740831](https://dev.azure.com/dnceng/public/_build/results?buildId=740831)|Rolling|1|
|[#741237](https://dev.azure.com/dnceng/public/_build/results?buildId=741237)|Rolling|1|
|[#741316](https://dev.azure.com/dnceng/public/_build/results?buildId=741316)|Rolling|1|
|[#741604](https://dev.azure.com/dnceng/public/_build/results?buildId=741604)|#46219|1|
|[#741683](https://dev.azure.com/dnceng/public/_build/results?buildId=741683)|#46038|1|

### Configurations
- Windows Desktop Debug Test32
- Windows Desktop Debug Test64
- Windows Desktop Release Test32
- Windows Desktop Release Test64
- Windows Desktop Spanish

**Comment by jaredpar** [comment] 2020-07-22 20:58
FYI @sharwell, @JoeRobich

**Comment by 333fred** [comment] 2020-07-24 20:56
This test has failed 21 times in the past 14 days, and has a pass rate of 97.87%. I'm adding it to https://github.com/dotnet/roslyn/pull/46310.

**Comment by sharwell** [comment] 2020-07-24 21:02
@tmat This test has been disabled in #46310, so a fix should be implemented ASAP to prevent regressions.

**Comment by sharwell** [comment] 2020-07-29 15:48
Duplicate of #45877

**Closed** 2020-07-30 04:51 UTC
Labels: Area-IDE, Disabled Test, Flaky, Test, Urgency-Now
