### ISSUE TITLE
IDE0052 suggests changes that would break the desired behavior of some programs

### ISSUE THREAD

**Issue by Treit** [dotnet/roslyn#56666] opened 2021-09-23 23:36 UTC
The code in the sample application located at the repo below illustrates a problem with the IDE0052 rule that suggests removing private members that are never read:

https://github.com/Treit/StaticTimerFieldIssue.git

In this case, heeding this suggestion breaks the program. The System.Threading.Timer object will become garbage collected and no longer fire after its initial invocation, when the desired behavior is to keep it running for the lifetime of the program. In order to ensure it does not become garbage collected, we must assign it to a private member to keep a reference to it alive.

**Comment by CyrusNajmabadi** [comment] 2021-09-24 17:17
In this case, you should suppress the diagnostic.  The analyzer is correct that it is never read by your program.  If you still need it aroudn for some other aux purpose, then suppression tells the analyzer you know what you're doing and this code is good.

tagging @mavasani if he has additional thoughts here.

**Comment by mavasani** [comment] 2021-09-24 17:25
Duplicate of #32956?

**Comment by CyrusNajmabadi** [comment] 2021-09-24 18:08
yup.   def a dupe.

**Closed** 2021-09-25 16:41 UTC
Labels: Area-IDE, untriaged
