### ISSUE TITLE
Decompile uses C# syntax for Visual Basic projects resulting in broken navigation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26669] opened 2018-05-07 02:58 UTC
1. 
``` VB
Imports System.Windows.Forms

Module Module1
    Private ReadOnly _CF_UNICODE As String = DataFormats.UnicodeText ' <- Decompile this

End Module

```

Expected: For the file to be decompiled in VB and to navigate to UnicodeText
Actual: The file is in C# syntax and it fails to navigate

_Copied from original issue: dotnet/project-system#3519_

**Comment by sharwell** [comment] 2018-05-07 10:16
Possible duplicate of #25159

**Comment by sharwell** [comment] 2018-05-07 10:18
:memo: The disassembler does not support VB as an output language. When this experimental feature is enabled, the target of a metadata navigation is expected to show disassembled C# code currently. #24349 is a higher-level issue to improve this experience.

**Comment by davkean** [comment] 2018-05-07 12:49
Even if it was C#, I would still expect navigation to work, which it does not.

**Comment by CyrusNajmabadi** [comment] 2018-05-07 16:53
What i'm not quite understanding is why we're creating a VB project to put this decompiled C# file into.  Why not create a C# project instead?  Then things should work properly.

**Comment by CyrusNajmabadi** [comment] 2018-05-07 16:58
Here's an example of the problem:

![image](https://user-images.githubusercontent.com/4564579/39713860-1c555214-51dd-11e8-866c-be085c8b28cd.png)

A **VB** project for System.Runtime was created, but all the code is C#, so literally all IDE features are completely broken.  Basic classification isn't even there.  I can totally understand not supporting decompilation into VB since we just don't have that.  But given that constraint, we should not be generating a VB project and placing the code into that.

**Comment by CyrusNajmabadi** [comment] 2018-05-18 23:38
Looks like a dupe of https://github.com/dotnet/roslyn/issues/26329

**Comment by sharwell** [comment] 2018-05-19 03:11
Duplicate of #26329

**Closed by sharwell** 2018-05-19 03:11 UTC
Labels: Area-IDE, Bug
