### ISSUE TITLE
Compatibility between Microsoft.Code.Anaysis and netCore apps

### ISSUE THREAD

**Issue by ddydeveloper** [dotnet/roslyn#20299] opened 2017-06-17 13:40 UTC
I tried to use Microsoft.CodeAnalysis Workspaces s in netCore app, unfortunately i had errors. 

This is my project github repository reference:
https://github.com/ddydeveloper/Roslyn.ApiClient.Codegen/tree/dev/src/Roslyn.Codegen
Problem in the file with path: 

> src/Roslyn.Codegen.WorkspaceParser/ApiClientParser.cs

  (Commented code)

**Version Used**: 
1. netCore 1.1 class library
2. Microsoft.CodeAnalysis 2.2.0 package

**Steps to Reproduce**:
1. Create a netCore 1.1 class library application
2. Add Microsoft.CodeAnalysis 2.2.0 nuget package
3. Add using directive into code in netCore app class:
`using Microsoft.CodeAnalysis.MsBuild;`

**Expected Behavior**:
Usign Microsoft.CodeAnalysis.MsBuild directive without any problems

**Actual Behavior**:
Had error: The type or namespace name "MsBuild" does not exists in the namespace   Microsoft.CodeAnalysis

For another think I had not blocking error with Microsoft.Composition package (included reference) compatibility. It can be fixed by addind System.Composition package reference but I'm not sure that it is the right way.

Did anybody have such problems?

**Comment by Pilchie** [comment] 2017-06-19 16:51
`MSBuildWorkspace` and related types are .NET Framework only right now, and don't work on .NET Core.

For the 2.2. packages, you can add a `<PackageReferenceFallback>` for Microsoft.Composition.  That issue should be fixed in the recent 2.3 based packages though.

**Comment by nothrow** [comment] 2017-06-19 17:27
Isn't this basically duplicate of https://github.com/dotnet/roslyn/issues/16040 ?

**Comment by Pilchie** [comment] 2017-06-19 20:18
The second half is, but that is only about System.Composition, not also using `MSBuildWorkspace`.

**Comment by ddydeveloper** [comment] 2017-06-20 09:17
@Pilchie, thanks! I supposed that MSBuildWorkspace does't work on .Net Core right now. I'll try to write same project on Net Framework 4.6.1. Is it planned to implement compatibility with .Net Core?

@nothrow yes, it is duplicate. I closed with issue and will wait 2.3 version!

**Comment by Pilchie** [comment] 2017-06-20 16:52
@DustinCampbell can answer better than me (probably next week, as he's on vacation right now).  .NET Core is tricky, since MSBuild requires running tasks, so a .NET Core app can't load projects targeting .NET Framework, since the .NET Framework tasks won't run on .NET Core.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 22:07
Closing out due to lack of feedback in 7 years.

**Closed by CyrusNajmabadi** 2024-10-18 22:07 UTC
Labels: Area-IDE, Feature Request
