### ISSUE TITLE
Autocomplete favors class member over local variable

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14064] opened 2016-09-25 23:08 UTC
**Version Used**: 2.0.0.60923

**Steps to Reproduce**:

```C#
namespace ConsoleApplication1
{
    class Program
    {
        class C { public string P { get; set; }  }

        public Program()
        {
            C[] names = new C[0];
            foreach (var name in names)
            {
               Test(n|
            }
        }

        public string Name { get; set; }
        public void Test(string a, string b) { }
    }
}
```

**Expected Behavior**:
`name` to be preselected in the autocomplete list.

**Actual Behavior**:
`Name` is preselected. 
Even if `name.P` is passed as the first parameter, it should make `name` remembered choice for the future, but this is not the case, `Name` gets preselected again for the second parameter too. Even in the case of `Test(name` hitting Ctrl+Space selects `Name`.

(note that if `a` is not a `string` but e.g. `object`, it does not repro.)

**Comment by miloush** [comment] 2016-09-25 23:30
This might be the same issue, but it repros without the `Name` property if the `Test`'s parameter is called `Name` (which is easier to spot since it does not compile).

(My original scenario had all of `Name` property, `Name` method parameter and `C.Name` property.)

**Comment by dpoeschl** [comment] 2016-09-29 22:11
@rchande Is this due to target typing? This is probably a dupe of #14085

**Comment by Pilchie** [comment] 2016-10-17 19:30
@rchande or @CyrusNajmabadi can one of you take a look and see if it's a dupe?

**Comment by rchande** [comment] 2016-10-18 02:35
Yep, dupe of https://github.com/dotnet/roslyn/issues/14056

**Closed by rchande** 2016-10-18 02:35 UTC
Labels: Area-IDE
