### ISSUE TITLE
Pattern-based lookup for `await using` doesn't recognize `IAsyncEnumerable.DisposeAsync` that returns an awaitable type

### ISSUE THREAD

**Issue by akarpov89** [dotnet/roslyn#34822] opened 2019-04-07 21:41 UTC
**Version Used**: 
Compiler version: '3.0.19.17001 (1deafee3)'

**Steps to Reproduce**:
Compile the following code:
```csharp
using System;
using System.Runtime.CompilerServices;

public class C
{
    public async void M(IAsyncDisposable arg)
    {   
        await using (var x = arg) {} // error
        await using (var z = new C()) {} // ok
    }
    
    public Awaitable DisposeAsync() => default;
}

namespace System
{
    public class Awaitable : INotifyCompletion
    {
        public Awaitable GetAwaiter() => default;
        public void GetResult() {}
        public void OnCompleted(Action continuation) {}
        public bool IsCompleted => true;
    }

    public interface IAsyncDisposable
    {
        Awaitable DisposeAsync();
    }
}
```

**Expected Behavior**:
Compiles without errors for both `await using`s

**Actual Behavior**:
The error CS0656: Missing compiler required member 'System.IAsyncDisposable.DisposeAsync' is emitted on first `await using`.

/cc @jcouv

**Comment by jcouv** [comment] 2019-04-08 07:55
This is expected. The `IAsyncDisposable` interface is well-known and must have a specific shape. 

If you want to implement pattern-based disposal, do not name your interface `IAsyncDisposable`.
I'll let @chsienki confirm while I'm away.

**Comment by akarpov89** [comment] 2019-04-08 08:34
@jcouv @chsienki I see, but it's not consistent with `await foreach` which allows `IAsyncEnumerator<T>.MoveNextAsync` to return awaitable type:

The following code compiles without errors:
```csharp
using System.Collections.Generic;
using System.Runtime.CompilerServices;

public class C
{
    public async void M(IAsyncEnumerable<int> xs)
    {
        await foreach (var x in xs) {}
    }
}

namespace System.Collections.Generic
{
    public class Awaitable : INotifyCompletion
    {
        public Awaitable GetAwaiter() => default;
        public bool GetResult() => true;
        public void OnCompleted(Action continuation) {}
        public bool IsCompleted => true;
    }

    public interface IAsyncEnumerable<T>
    {
        IAsyncEnumerator<T> GetAsyncEnumerator();
    }
    
    public interface IAsyncEnumerator<T>
    {
        T Current { get; }
        Awaitable MoveNextAsync();
    }
}
```

**Comment by chsienki** [comment] 2019-04-08 18:46
This really is by design, although the reasoning is a little obtuse:

`await foreach` looks up in a _pattern_-first approach, then falls back to looking up via known interface.
This is a design decision to match the way a regular `foreach` works. In your example, `Awaitable MoveNextAsync()` is a valid pattern match; the interface isn't even considered and the code compiles.

`await using` reverses the lookup: it first looks up in an _interface_-first approach, and then falls back to a pattern match. This is consistent with other parts of the language, and ensures that `IAsyncDisposable` works largely the same as `IDisposable` in being interface based, but allows falling back to an optional pattern match (pattern-based _synchronous_ dispose was dropped in C#8.0 for everything but `ref structs`, but the design would function the same way and may come back in future versions of the language). 

In your initial example, implementing `IAsyncDisposable` means the await using statement will look up the disposal method via interface, but the interface definition doesn't match what the compiler is expecting and you get a compilation error. In the future it would be expected that `IAsyncDisposable` would ship 'in box' with the BCL, meaning it wouldn't be possible to get into this situation. 

I'm going to close this issue as by-design, as the compiler is doing the correct thing based on the language rules. However, please feel free to open an issue on https://github.com/dotnet/csharplang, if you feel the order of lookup for `await using` should be reconsidered.

**Closed by chsienki** 2019-04-08 18:46 UTC
Labels: Area-Compilers, New Language Feature - enhanced using
