### ISSUE TITLE
More user-friendly error when writing `unchecked` to declare an unchecked user-defined operator

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#61305] opened 2022-05-13 15:39 UTC
Just tried the checked user-defined operator feature out, and I think it would be nice to have a more specific error when a user types:
```csharp
public static int operator unchecked +(int left, int right);
//                         ~~~~~~~~~
```
Saying that unchecked operators do not require the modifier. Currently, multiple unrelated errors are being shown, and parsing breaks miserably:
![image](https://user-images.githubusercontent.com/8298332/168272401-47704cbc-b1ac-4d15-a5dc-7b83ad74e87d.png)

*Originally posted [here](https://github.com/dotnet/roslyn/issues/59458#issuecomment-1125945652)*

**Comment by jcouv** [comment] 2022-05-13 15:49
That'll definitely be better.
Closing as duplicate of https://github.com/dotnet/roslyn/issues/60394

**Closed by jcouv** 2022-05-13 15:49 UTC
Labels: Area-Compilers, untriaged

**Comment by AlFasGD** [comment] 2022-05-13 16:01
By the way, shouldn't this be added to the test plan for this feature? That's where I looked for to find whether the issue is known.

**Comment by jcouv** [comment] 2022-05-13 17:17
@AlFasGD Added link in test plan. Working on a fix now
