### ISSUE TITLE
Compiler reports error CS0618 'member' is obsolete even when the containing member is obsolete itself

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#66409] opened 2023-01-13 17:21 UTC
**Version Used**: 

Version 17.6.0 Preview 1.0 [33311.366.main]

**Steps to Reproduce**:

Checkout roslyn ([jcouv update:] after PR https://github.com/dotnet/roslyn/pull/64160), remove `#pragma` at `src/Workspaces/Core/Portable/Workspace/Solution/Project.cs(103,57)` and build.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=134784&view=logs&j=8814095f-efe3-5baf-5d58-2cf73e00e570&t=e3cc1cfd-62ab-5bae-1790-02d10c3feaa0&l=33

Tracks TODO in code.

**Comment by Youssef1313** [comment] 2023-01-14 09:28
https://github.com/dotnet/roslyn/blob/70b0832098e052508c6724055e23a739f2666bdf/src/Workspaces/Core/Portable/Workspace/Solution/Project.cs

I'm not seeing `#pragma`s in the file?

I couldn't get a minimal repro from the description too:

```csharp
using System;

[Obsolete]
public class MyObsolete { }


public class C
{
    // containing type is obsolete, and no warning here (correct behavior)
    public MyObsolete S { get; }

    
    [Obsolete]
    // containing method is obsolete, no warning on parameter or return type.
    public MyObsolete M(MyObsolete s)
    {
         // containing method is obsolete, no warning here too.
        MyObsolete s2;
        
        return localFunction(new());
        
        MyObsolete localFunction(MyObsolete s3) => new();
    }
}
```

**Comment by tmat** [comment] 2023-01-15 17:06
The pragmas are added here: https://github.com/dotnet/roslyn/pull/64160

**Comment by jjonescz** [comment] 2023-01-27 11:10
Seems to be fixed in main, it's only reproducible in Default compiler version in SharpLab when there's an interpolated string:

https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE8QbQHkAjAZwHsAbAUwBcqAKAEgCIAFCZgSgF1EB6PogBOVALZkAblUSNENMogBmASwAecgBbSA7gEMhAO2UGA5tlwJkEAAyJ2iALwA+O2ADc5nIVKVaDNmBc3J7ISCA2ro4uzMweMAC+QA=

```cs
using System;
public class C {
    [Obsolete($"P1")] // remove $ to fix the warning
    public string P1 => P2;
    [Obsolete("P2")]
    public string P2 => "";
}
```

**Comment by Youssef1313** [comment] 2023-01-27 11:13
@jjonescz Oh, if specific to interpolated strings, then fixed by https://github.com/dotnet/roslyn/pull/64612

**Closed** 2023-02-14 17:04 UTC
Labels: Area-Compilers, untriaged
