### ISSUE TITLE
Automatically wrap a long line upon hitting a semicolon

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59911] opened 2022-03-03 15:56 UTC
When completing a long statement (typing semicolon), ReSharper will wrap the line automatically. It isn't perfect and sometimes needs to be refined after-the-fact, but the automatic formatting is helpful.  We are aware of both the built in word-wrap (which is very arbitrary) and the _Ctrl+.->Wrap every argument->Indent all arguments_ quick fix (which requires manual intervention and only handles argument lists).

**Comment by CyrusNajmabadi** [comment] 2022-03-03 16:31
Dupe of https://github.com/dotnet/roslyn/issues/15406

**Closed by CyrusNajmabadi** 2022-03-03 16:31 UTC
Labels: Area-IDE, untriaged

**Comment by sharwell** [comment] 2023-06-13 14:39
Duplicate of #15406
