### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p1 on PR #703

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9805] opened 2016-03-16 18:11 UTC
PR: [#703](https://github.com/dotnet/roslyn-internal/pull/703) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/226/

**1 Test Failures:**
BasicWinForms.Change control property in code

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicWinForms.xml

**Comment by davkean** [comment] 2016-03-16 18:30
Dupe of https://github.com/dotnet/roslyn/issues/7643.

**Closed** 2016-03-17 02:07 UTC
Labels: Area-Infrastructure, Bug, Contributor Pain
