### ISSUE TITLE
VB enum matching issues

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#9313] opened 2016-02-29 23:05 UTC
Two errors with matching using enums (VS 2015 update 1)

        Public Enum e1
            o1
            o2
        End Enum

        Public Enum e2
            o3
            o4
        End Enum

        Public Sub s1(e1 As e1, p1 As String)
        End Sub

        Public Sub s1(s1 As String, p1 As String)
        End Sub

        Public Sub s2(e2 As e2, p2 As String)
        End Sub

        Public Sub test()
            s1(e1.o1, 1) ' show error here. Should match to s1 with enum as first parameter, without errors
            s2(e1.o1, "") ' no error hehe. Should be error because of using incorrect enum 
        End Sub

**Comment by HaloFour** [comment] 2016-03-01 00:22
Both error with `Option Strict On`.

Seems that with `s1` it fails because there are multiple implicit conversions that could be performed and it can't/won't automatically select any of them.

```
BC30519	Overload resolution failed because no accessible 's1' can be called without a narrowing conversion:
    'Public Sub s1(e1 As Program.e1, p1 As String)': Argument matching parameter 'p1' narrows from 'Integer' to 'String'.
    'Public Sub s1(s1 As String, p1 As String)': Argument matching parameter 's1' narrows from 'Program.e1' to 'String'.
    'Public Sub s1(s1 As String, p1 As String)': Argument matching parameter 'p1' narrows from 'Integer' to 'String'.
```

And `s2` doesn't fail because, with `Option Strict` disabled, VB.NET allows for implicit conversion between enum types.

**Comment by vbcodec** [comment] 2016-03-01 21:02
@HaloFour 
But these possible conversion should be limited only to second parameter, while first is stated explicitly.
As for second case, there should be implicit conversion from digits, numeric variables, strings, etc, bot not from other enum, despite it can be easily interpreted as integer. Other enum have different meaning, and such calls are probably wrong design / logic./ typing errors

**Comment by HaloFour** [comment] 2016-03-01 21:30
@vbcodec

> But these possible conversion should be limited only to second parameter, while first is stated explicitly.

Seems that the overload resolution of the compiler disagrees with you and as long as you're willing to coerce some arguments that you're also willing to coerce them all.

> As for second case, there should be implicit conversion from digits, numeric variables, strings, etc, but not from other enum, despite it can be easily interpreted as integer. Other enum have different meaning, and such calls are probably wrong design / logic./ typing

Perhaps, but at the end of the day an `enum` is still just a number.

These issues are resolved by simply enabled `Option Strict On`, which in my opinion should be a requirement to be allowed to program in VB.NET at all.

Unless either of these cases is a regression from a previous version of the compiler I doubt that anything will be done to change the behavior, especially in the second case where making the compiler "more strict" would be a breaking change.

**Comment by miloush** [comment] 2016-03-02 22:24
Also note that C# allows to unbox enum type into its underlying type or any other enum type (with the same underlying type), which was even explicitly stated in CLI specification until version 3. This looks consistent with that behaviour.

**Comment by jaredpar** [comment] 2016-03-06 15:33
I believe this behavior is by design as @HaloFour noted.  @AlekseyTs can you verify.

**Comment by AlekseyTs** [comment] 2016-09-21 20:54
Correct the behavior is by design. According to the language specification (section 8.9 Narrowing Conversions), there is a narrowing conversion **"From an enumerated type to another enumerated type"**.

**Closed by AlekseyTs** 2016-09-21 20:54 UTC
Labels: Area-Compilers, Language-VB, Question
