### ISSUE TITLE
Tab Button Problem After Sentence "Exit For"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47286] opened 2020-08-31 16:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1167702/tab-button-problem-after-sentence-exit-for.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
When I type Exit For and press the button Tab in order to write a comment, it appears as below:
Exit For index = 1 To 10

Next

But What I wanted was:
Exit For       ' Comment

I know it's an automatic filling sentence but I don't think anyone want an automatic filling after "exit for"
Could you please fix it?

---
#### Feedback Bot on 8/31/2020, 00:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-09-02 21:33
This is caused by the snippet engine handling the <kbd>Tab</kbd> key after the text `for`. Tentatively marking this as **By Design** but will update following design review.

**Comment by sharwell** [comment] 2020-09-08 22:11
We took this to a design review today and determined that the current behavior is **By Design**. Currently the snippet evaluation process does not have the ability to filter by context at this level, so we have no direct way to resolve this. As a starting point, see #44122 for a different direction we could take to start introducing context sensitivity for snippets.

**Closed by sharwell** 2020-09-08 22:11 UTC
Labels: Area-IDE, Bug, Need Design Review, Resolution-By Design
