### ISSUE TITLE
Allow if-def inside /// code summaries 

### ISSUE THREAD

**Issue by dotMorten** [dotnet/roslyn#10264] opened 2016-04-01 19:41 UTC
**Version Used**: 6 / VS2015.1

**Steps to Reproduce**:

1. Create the following property with doc in a class:
```csharp
        /// <summary>
        /// Turns the GPS on or off
        /// </summary>
        /// <remarks>
        /// <para>Will turn on the system location service.</para>
#if NETFX_CORE
        /// <para>Make sure you have enabled the location capability in your appx manifest.
        /// See https://msdn.microsoft.com/en-us/library/windows/apps/br211423.aspx
        /// for more information
        /// </para>
#elif __ANDROID__
        /// <para>
        /// Make sure you have enabled location in your app manifest. 
        /// See http://developer.android.com/guide/topics/manifest/manifest-intro.html 
        /// for more information.
        /// </para>
#endif
        /// </remarks>
        public bool IsGpsEnabled { get; set; }
```
2. Enable XML documentation generation 
3. Build

**Expected Behavior**:
No build warnings. XML is generated with platform specific remarks. This allows me to add a couple of platform specific remarks. Currently you have to if-def the entire code summary section, causing a lot of documentation to be duplicated. 

**Actual Behavior**:
Several build warnings
```
warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'remarks'.'
1>\Class1.cs(25,13,25,14): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
1>\Class1.cs(9,18,9,24): warning CS1591: Missing XML comment for publicly visible type or member 'Class1'
1>\Class1.cs(11,9,11,10): warning CS1587: XML comment is not placed on a valid language element
```
And the generated XML:

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary1</name>
    </assembly>
    <members>
        <!-- Badly formed XML comment ignored for member "P:ClassLibrary1.Class1.IsGpsEnabled" -->
    </members>
</doc>
```

**Comment by dotMorten** [comment] 2016-05-24 01:24
Just realized this is a duplicate of https://github.com/dotnet/roslyn/issues/96#issuecomment-221141359

**Comment by jaredpar** [comment] 2016-07-21 00:19
Sorry for the delay.  This issue got lost in the shuffle.  Agree this is a duplicate of #96 and closing as such.

**Closed by jaredpar** 2016-07-21 00:19 UTC
Labels: Area-Compilers, Bug
