### ISSUE TITLE
Dogfooding crash in memory mapped files

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20170] opened 2017-06-12 15:25 UTC
**Version Used**: 
VS 2017 Preview 15.3 P 2, + latest Roslyn signed VSIX: 2.3.06181101

**Steps to Reproduce**:

1. Had Roslyn.sln open, rebased my branch to get the latest changes from master (but there weren't any).

**Actual Behavior**:
VS Crash.  

**Dump:**
`"\\mlangfs1\public\kevinpi\TemporaryStorageAccessDenied.dmp"`

**Callstack:**
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+MemoryMappedInfo+SharedReadableStream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.<ReadValue>b__25_0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

**Comment by sharwell** [comment] 2017-06-12 15:29
Duplicate of #19761

**Closed by sharwell** 2017-06-12 15:29 UTC
Labels: Area-IDE, Bug, Tenet-Reliability
