### ISSUE TITLE
[Request] QuickInfo for namespace documentation (on hover + member-list)

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#46443] opened 2020-07-30 09:28 UTC
**Version Used**: 
Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 4.0

**Steps to Reproduce**:

1. Create a new `*.cs` file
2. Add a triple slash `/` one line over the `namespace` keyword
3. Write between a text between `/// <summary>` and `/// </summary>`
4. Hover over the latest namespace word (most right)

**Code**:

```csharp
/// <summary>
/// All view-models from MVVM should be here
/// </summary>
namespace Test.Mvvm.ViewModel
{
}
```

**Expected Behavior**:
Show the namespace documentation when
* hover over the namespace
* when the namespace selected, in the member list

**Actual Behavior**:
* Documentation isn't shown on hover
![2020-07-30 11_23_58-PowerCalculator - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/88906025-3fa53200-d257-11ea-99c8-79f8708f9e93.png)
* Documentation isn't shown in the member list
![2020-07-30 11_24_56-PowerCalculator - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/88906129-5ba8d380-d257-11ea-9c9e-d4f901873c6b.png)

Possible problems:
* Different documentations inside different files for the same namespace

**Comment by CyrusNajmabadi** [comment] 2020-07-30 18:47
Namespaces are not a valid xml location.  You can see warning for that in the IDE:

![image](https://user-images.githubusercontent.com/4564579/88961876-79c40300-d25a-11ea-8027-4f5153fa709f.png)

If you wanted this to change, it would have to come through a language change at dotnet/csharplang.

**Comment by sharwell** [comment] 2020-08-04 17:12
Duplicate of https://github.com/dotnet/csharplang/issues/315

**Closed by sharwell** 2020-08-04 17:12 UTC
Labels: Area-IDE
