### ISSUE TITLE
[C# Interactive] Exceptions thrown before namespace declarations are used cause CSI to forget the declarations

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#11043] opened 2016-05-04 01:02 UTC
**Version Used**: 
Update 2 - 25123.00
**Steps to Reproduce**:
Open csi and run the following few lines:

```
Console.Write("test");
throw new Exception();
Console.Write("test");
```

Note that it outputs the lines of "test" successfully both times.
Now reset csi via #reset and run the following:

```
throw new Exception();
Console.Write("test");
```

**Expected Behavior**:
It should throw the exception from the first line and output "test in the latter.
**Actual Behavior**:
The compiler is unable to output test due to 'Console' not existing in the current context.

![image](https://cloud.githubusercontent.com/assets/10537189/15002726/2ad5e27a-1159-11e6-9162-c277c276e433.png)

**Comment by mattscheffer** [comment] 2016-05-04 01:03
@ManishJayaswal  FYI

**Comment by ManishJayaswal** [comment] 2016-05-06 23:57
is this a dupe of #6580 ?

**Comment by tmat** [comment] 2016-05-19 02:57
Dup of https://github.com/dotnet/roslyn/issues/10883

**Closed by tmat** 2016-05-19 02:57 UTC
Labels: Area-Interactive, Bug
