### ISSUE TITLE
Auto-fixing `void` to `async Task` drops task's return value

### ISSUE THREAD

**Issue by SteveDesmond-ca** [dotnet/roslyn#57881] opened 2021-11-18 19:57 UTC
### Describe the problem you are trying to solve

I just got burned by this:

```cs
public static class Program
{
    public static void Main()
        => await ExitCode();

    private static Task<int> ExitCode()
        => Task.FromResult(1);
}
```

Run the auto-fixer to convert `void Main()` into an `async` method. The resulting code is:
```cs
public static class Program
{
    public static async Task Main()
        => await ExitCode();

    private static Task<int> ExitCode()
        => Task.FromResult(1);
}
```

The code compiles and runs, but I would expect the exit code to be 1. Instead it's 0, because the auto-fixer that turns `void Main()` into `async Task` doesn't include the return type of what's being `await`ed.

I get that `Task<T>` inherits `Task`, and therefore this is valid code, but it's really unintuitive why the program returns an exit code of 0.

I would expect the auto-fixer to convert it to:
```cs
public static class Program
{
    public static async Task<int> Main()
        => await ExitCode();

    private static Task<int> ExitCode()
        => Task.FromResult(1);
}
```

### Describe suggestions on how to achieve the rule

I think the fixer that converts `void` to `async Task` should also include the type, if the underlying await contains one.

I'd also love to see a warning/suggestion when `Task<T>` is silently converted to `Task` and therefore the task's return value is dropped.

### Additional context

I understand that this addition for all tasks might be too broad, so if that's the case just for `Program.Main()` would solve this specific case of exit codes being swallowed.

**Comment by CyrusNajmabadi** [comment] 2021-11-19 16:24
But your code was 'void' before. So you already were dropping the value. Our presumption here is that your sync version is correct and should inform the async version. 

Note: if you had `int Main`, you would have ended up with `Task<int>`

**Comment by SteveDesmond-ca** [comment] 2021-11-19 21:37
If I say `void GetNumber() => 1;` I get a fixer that converts `GetNumber()` from `void` to `int`, as expected, so it feels a little weird that just because it's `async` it no longer does what I want.

I think my "I'd also love to see..." from above is actually my bare minimum request: can we get a warning, or at the very least a suggestion, when doing something like this?
```cs
async Task GetValue() => await Task.FromResult(123);
```

**Comment by CyrusNajmabadi** [comment] 2021-11-20 20:30
> I think my "I'd also love to see..." from above is actually my bare minimum request: can we get a warning, or at the very least a suggestion, when doing something like this?

I think you could suggest an analyzer like that over at dotnet/roslyn-analyzers.

**Comment by CyrusNajmabadi** [comment] 2021-11-20 20:33
> If I say void GetNumber() => 1; I get a fixer that converts GetNumber() from void to int, as expected, so it feels a little weird that just because it's async it no longer does what I want.

But you literally had *void*.  THe issue here is not with the void/non-void, it's with void/Task-like.  

Consider something like:

```
void AppendText(string text)
    => _sb.Append(text);
```

if i change that to be async, i should get:

```
async Task AppendText(string text)
{
    await ...
    _sb.Append(text);
}
```

I should not get:

```
async Task<StringBuilder> AppendText(string text)
{
    await ...
    return _sb.Append(text);
}
```

If it was void before, it's *extremely* strange to make it non-void-Task as that means the non-returning function now returns something when made async.

**Comment by SteveDesmond-ca** [comment] 2021-11-21 00:32
That makes sense, though I think there's some nuanced differences in our examples around perceived intention. I just created dotnet/roslyn-analyzers#5744 as suggested, which is probably a happy middle ground.

**Comment by dibarbet** [comment] 2021-12-06 22:27
Design review conclusion:

We will accept a change to add a third code action to return Task<expression return> to the list.  We will not modify the existing code action as the expression may have been potentially ignored.

We would also like to look at propagating the return type with other improvements to the unused return code fixes (along with better suppressions for framework methods).

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:50
Closing out as by design.  The return value was dropped before and after.  This is intentional preserving of that behavior with the change ot async.

**Closed by CyrusNajmabadi** 2024-10-22 18:50 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement
