### ISSUE TITLE
IntelliSense does not suggest anything when inside a collection expression

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#70760] opened 2023-11-10 09:27 UTC
**Version Used**:
Visual Studio 2022
Version 17.8.0 Preview 7.0

Roslyn (C# Tools)
4.8.0-3.23524.11+f43cd10b737b6343956dee421cff8c50b602c788
Commit f43cd10b737b6343956dee421cff8c50b602c788

**Steps to Reproduce**:

1. Begin typing a collection expression with the `[` character
2. Optional: Begin typing the name of any symbol or keyword you would expect to appear (`new`, `string`, `Field`, etc.)
3. Also applies after a comma of a collection expression (e.g. `[string.Empty, |` with `|` indicating the cursor)

[Example template](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGED2AbbEDGMAlpgHYAyRMECU2yAPgAIAMABEwIwAsA3ALAAoIUwDMHAExt0QgN5C2ijuK6iAPFxYA+NgFkAFAEoFS+YKUWOAdjYBtE4oC+Qx0A=)

**Expected Behavior**:
The expected symbols appear as suggestions for completion.

**Actual Behavior**:
No completion suggestions appear at all.

**Comment by sharwell** [comment] 2023-11-10 18:51
Duplicate of #70677

**Comment by Rekkonnect** [comment] 2023-11-10 18:53
Missed it because of the wording, will link the PR there too

**Closed** 2023-11-16 19:56 UTC
Labels: Area-IDE, untriaged
