### ISSUE TITLE
InvalidOperationException when backspacing a selection in a previous submission

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4777] opened 2015-08-25 17:08 UTC
```
> { }
> 
```

Select the close brace and hit backspace.

```
---------------------------
Microsoft Visual Studio
---------------------------
Nullable object must have a value.
---------------------------
OK   
---------------------------
```

**Comment by ManishJayaswal** [comment] 2015-09-15 23:22
duplicate of #4177

**Closed by ManishJayaswal** 2015-09-15 23:22 UTC
Labels: Area-Interactive, Bug, Interactive-Scripting

**Comment by genlu** [comment] 2015-09-24 00:58
Fixed by https://github.com/dotnet/roslyn/pull/5339
