### ISSUE TITLE
do not add async to a void method

### ISSUE THREAD

**Issue by pgroene** [dotnet/roslyn#60467] opened 2022-03-29 22:58 UTC
**Version Used**: vs17.1

**Steps to Reproduce**:

1. void method
2. add await somewhere in the method
3. async is added before the void

**Expected Behavior**:
nothing happens

**Actual Behavior**:
async was added

adding a async to a void method will lead to issues

**Comment by Youssef1313** [comment] 2022-03-30 08:08
There is a related PR #55983

**Comment by CyrusNajmabadi** [comment] 2022-03-30 14:29
`async` is required by the language in order to support the `await` keyword. It's literally not allowed otherwise :-)

That said, we've heard from some that even if that's the case they would prefer it not be added. I would be ok with an option here.

**Comment by sharwell** [comment] 2022-03-30 17:43
Duplicate of #55975

**Closed by sharwell** 2022-03-30 17:43 UTC
Labels: Resolution-Duplicate, Area-IDE
