### ISSUE TITLE
Show redundant `else` keywords as redundant

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#30522] opened 2018-10-15 14:27 UTC
Unnecessary syntax is normally displayed as faded. I would expect the `else` keyword here to be faded with a fix to remove, since it is redundant:

```c#
if (foo == 1)
{
    return;
}
else if (foo == 2)
{
    // ...
}
```

Does this seem like it would merit a code style rule?

**Comment by CyrusNajmabadi** [comment] 2018-10-15 17:41
On the fence about this.  THis is pushing a pretty opinionated style on people.  With a way to turn this off, i think this would be ok :)

**Comment by alrz** [comment] 2018-10-15 20:05
> pushing a pretty opinionated style on people

I think it's ok just as a piece of information, not that we're suggesting you should remove it. take unused parameters for example, it might not be possible to remove the parameter from the current method (e.g. in case of an override), but it's nice to know that a parameter is not used throughout the body.

**Comment by CyrusNajmabadi** [comment] 2018-10-15 20:13
> it might not be possible to remove the parameter from the current method (e.g. in case of an override), but it's nice to know that a parameter is not used throughout the body.

Note: i actually *really* dislike this behavior.  Because it tends to actually distract me a bunch.  If i see that it's faded, then i feel like i want to make that go away.  But when i can't, that means i'm left in a state of distraction with no way to rectify it.  

This is not hypothetical either.  I've run into this with other tools in other languages.  Perhaps *another* metaphor can be used.  But making me look at stuff i can't actually fix is really up there in annoyance level.

**Comment by sharwell** [comment] 2018-10-29 14:00
Tentatively marking this as **Won't Fix**, but leaving it open pending a review of this proposed resolution. Should we decide to not implement this feature within Roslyn itself, it would still be possible to implement the feature as a separate analyzer and code fix.

**Comment by alrz** [comment] 2019-01-12 19:11
>But making me look at stuff i can't actually fix is really up there in annoyance level.

I think, in those cases (context: fading out unused parameters that cannot be removed) we can only fade out the name.

**Comment by CyrusNajmabadi** [comment] 2020-03-08 03:36
@sharwell can we take to review?  i would like to close this out.

My bar for this is effectively: would we take a PR from this to have this new behavior.  I don't believe we would in roslyn itself.  As such, having the issue isn't helpful.

**Closed** 2022-10-31 21:23 UTC
Labels: Resolution-Won't Fix, Area-IDE, Feature Request, Need Design Review
