### ISSUE TITLE
Proposal: Type initializer should be able to discard member name in certain cases

### ISSUE THREAD

**Issue by Jalalx** [dotnet/roslyn#55505] opened 2021-08-09 10:43 UTC
## Background and Motivation

Lets say you have to classes and want to copy properties from one to another:
```csharp
public class Order 
{
    public int Id { get; set; }
    public DateTime CreationTime { get; set; }
    public decimal TotalAmount { get; set; }
    public string AnotherProperty { get; set;}
    public string YetAnotherProperty { get; set;}

    public NestedOrderInfo Info { get; set; }

    public class NestedOrderInfo 
    {
       public int AndAnotherProperty  { get; set; }
    }
}

public class OrderSummary
{
    public int Id { get; set; }
    public decimal TotalAmount { get; set; }
    public int AndAnotherProperty  { get; set; }
}
```
now if you want to copy from Order to OrderSummary, in new proposed syntax, all you need to do is referencing the properties with exactly the same name, like this:
```csharp
Order order = new Order();
//...

// new suggested syntax:
OrderSummary orderSummary = new OrderSummary { order.Id, order.TotalAmount, order.Info.AndAnotherProperty };
// Which in current C# version reponds with: error CS1922: Cannot initialize type 'OrderSummary' with a collection initializer because it does not implement 'System.Collections.IEnumerable'
```
Also, there should be a support for mixed mode:
```csharp
// new suggested syntax:
OrderSummary orderSummary = new OrderSummary { Id = order.Id, order.TotalAmount, order.Info.AndAnotherProperty };
```

And in this scenario, compiler should generate a certain error because `Id` is assigned more than once:
```csharp
// new suggested syntax:
OrderSummary orderSummary = new OrderSummary { Id = 1, order.Id }; // error CSXXXX: Member `Id` is set mode than once...
```

In the current C# version, you need to implement like this which is a bit verbose.
```csharp
// currently it's like this:
OrderSummary orderSummary = new OrderSummary 
{ 
    Id = order.Id, 
    TotalAmount = order.TotalAmount, 
    AndAnotherProperty = order.Info.AndAnotherProperty 
};
```
C# currently supports the same feature for anonymous types, why not extending it to named types? Also, the new syntax does not introduce any breaking change and is backward compatible.

Please let me know what you think.

**Comment by Youssef1313** [comment] 2021-08-09 10:55
- The suggested syntax is going to be ambiguous with collection initializers (as the current error message suggests).
- The language proposals are opened in dotnet/csharplang instead of dotnet/roslyn (in case you don't have a very detailed proposals, you can open it first as a discussion)

**Comment by svick** [comment] 2021-08-09 10:57
I'm going to close this as a duplicate of https://github.com/dotnet/csharplang/discussions/4961.

**Closed by svick** 2021-08-09 10:57 UTC
Labels: Concept-API, Feature Request, Area-Language Design, untriaged
