### ISSUE TITLE
Null warning not reported for constant member

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#23698] opened 2017-12-10 21:58 UTC
`const string A = null;` should generate `warning: cannot convert null to non-nullable reference`:
```
class C
{
    const string A = null;
}
```

**Comment by jaredpar** [comment] 2019-04-09 19:15
@chsienki this is likely similar to the attribute work that you did for enabling nullable analysis.

**Comment by jaredpar** [comment] 2019-04-09 21:34
Looks like this is a duplicate of #29995

**Closed by jaredpar** 2019-04-09 21:34 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
