### ISSUE TITLE
IEnumerable<T> covariance does not work with ValueTuple (object)

### ISSUE THREAD

**Issue by allanchao** [dotnet/roslyn#21752] opened 2017-08-26 02:45 UTC
**Version Used**: 
.net 4.6.2, visual studio 15.3.2, C# 7.1

**Issue**:
Covariance is supported for IEnumerable<T> and IEnumerable<U> where T : U. However it doesn't work for the new ValueTuple types... not even with object.  See demo code below.

**Steps to Reproduce**:

```
List<string> strings = new List<string>() { "abc" };
Console.WriteLine(strings[0] is object); // true - string is an object
Console.WriteLine(strings is IEnumerable<object>); // true - covariance of IEnumerable<string> works
List<(string, int)> valueTuples = new List<(string, int)>() 
{
	("hello", 2)
};
Console.WriteLine(valueTuples[0] is object); // true - valuetuple is an object
Console.WriteLine(valueTuples is IEnumerable<object>); // false - covariance of IEnumerable<(...)> fails

Console.WriteLine(valueTuples is System.Collections.IEnumerable); // true it is an IEnumerable, but not IEnumerable<T>?
```

**Expected Behavior**:
outputs 
```
true
true
true
true
true
```

**Actual Behavior**:
outputs
```
true
true
true
false
true
```

**Comment by akarpov89** [comment] 2017-08-26 06:20
@allanchao That's not a bug. Variance applies only to type arguments of reference types. 
You can read Eric Lippert's [blog post](https://blogs.msdn.microsoft.com/ericlippert/2009/03/19/representation-and-identity/) to learn more.

**Comment by sharwell** [comment] 2017-08-26 23:21
This may be a bit unintuitive given that it's not obvious that `(int, string)` is a value type. But overall this behavior aligns with the long-standing behavior of covariance when using value types. I'm resolving this issue as by design, but if you have a specific question about how to best use tuple types in an application which led to this question, feel free to ask it as a follow-up. :smile:

**Closed by sharwell** 2017-08-26 23:21 UTC
Labels: Area-Compilers, New Language Feature - Tuples, Resolution-By Design
