### ISSUE TITLE
Fuzzy matching adds a using to a namespace even though it's already the current namespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10912] opened 2016-04-27 16:00 UTC
``` C#
namespace Namespace
{
    class Program
    {
        static void Main(string[] args)
        {
            Bar bar = new Bar();
        }
    }


    class BarService
    {
    }
}

```

![image](https://cloud.githubusercontent.com/assets/1103906/14858826/6f99dffe-0c56-11e6-9aef-18876bfd4f23.png)

**Comment by Pilchie** [comment] 2016-04-27 17:53
Dupe of https://github.com/dotnet/roslyn/issues/9597, though now we *also* have the spell check fix, so maybe we shouldn't offer add using at all?

**Closed** 2016-04-27 17:54 UTC
Labels: Area-IDE, Resolution-Duplicate
