### ISSUE TITLE
No diagnostic ID in the error list for analyzer diagnostics on 15.5 RTW

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#23588] opened 2017-12-05 18:15 UTC
**Version Used**: 
Install latest VS2017.5 RTW:
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

**Steps to Reproduce**:

1. `git clone https://github.com/shadowsocks/shadowsocks-windows.git`
2. Open the root solution file in VS (if you get prompted to change the target framework to v4.6.1, click ok).
3. Add latest NuGet package for FxCopAnalyzers from https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers to the solution
4. Restore packages for solution
5. Enable Full solution analysis for C#
6. Close and re-open VS
7. Open solution and immediately click "Rebuild" solution command before full solution analysis completes (error list should still be showing `Error List ...`). Note that if you wait for full solution analysis to complete before doing a rebuild, you get the expected behavior.

**Expected Behavior**:
CA diagnostics in error list have non-empty error IDs.
![image](https://user-images.githubusercontent.com/10605811/33622947-374db9c8-d9a4-11e7-8f0c-8e8f284fc0c3.png)

**Actual Behavior**:
CA diagnostics in error list have empty error ID.
![image](https://user-images.githubusercontent.com/10605811/33623073-a220dfaa-d9a4-11e7-9f8b-b239139de3dc.png)

I verified that output window does have diagnostics with expected IDs:
![image](https://user-images.githubusercontent.com/10605811/33623132-d40543bc-d9a4-11e7-9d4e-ec18e515ce3f.png)

**Comment by mavasani** [comment] 2017-12-05 18:16
Tagging @jinujoseph and @mattscheffer 

@heejaechang, this looks like a recent regression in our de-duping logic? I will add you to our email thread.

**Comment by heejaechang** [comment] 2017-12-05 19:21
@mavasani will it eventually get fixed? or stay that way? it looks like we didn't know we can handle such errors and let default project system error provider to handle the issue. I know where the issue is. I can fix it if we want to.

**Comment by mavasani** [comment] 2017-12-05 20:23
> will it eventually get fixed? or stay that way?

For me, after getting the repro, if I wait for some more time and do another rebuild, the issue does not repro. @mattscheffer Can you also verify?

Additionally, the original repro steps doesn't seem to cause it to repro on larger solutions like RoslynAnalyzers, where rebuild itself takes more than few seconds. So, likely the root cause is what you described offline, build is finishing before our new error list provider/solution is initialized. If that is the case, this is not a very high priority issue (unless @mattscheffer can get it to repro consistently across different solutions and/or rebuilds). We should still fix it in 15.6 if possible.

**Comment by Gav-Brown** [comment] 2018-02-28 22:41
Hi, just to say that using Analyzers.2.6.0 on VS 15.5.7 this is still an issue, at least on my small project that builds quickly. It makes setting up a new project and testing the Analysers quite hard. The ability to suppress the error is also disabled (I assume due to no ID).

**Comment by heejaechang** [comment] 2018-02-28 22:50
this will be quite hard to fix. the problem is IDE analyzer and build are 2 different thing. when you build, it spawn completely new process to build outside of VS. if VS still doesn't have all data for the solution including analyzers, there is not much VS can do.

to fix this, we need to block build from working/finishing until VS has all solution data (including analyzers) which will be bad experience for users. since users now not only can't use VS until solution is fully initialized, they can't even build.

tagging @jinujoseph @mavasani @Pilchie

**Comment by Gav-Brown** [comment] 2018-02-28 23:14
StyleCop.Analysers.1,0.0 work fine, just new Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.0 (and other packages this deploys) seem to have this issue.

**Comment by heejaechang** [comment] 2018-03-01 00:11
@Gav-Brown could be different issue. can you provide repro solution?

**Comment by mavasani** [comment] 2018-03-01 00:21
@heejaechang @Gav-Brown I think the issue might be the one with compilation end action analyzers - https://github.com/dotnet/roslyn-analyzers/issues/1559. Stylecop analyzers doesn't have compilation end action analyzers, but FXCop analyzers has quite a few of them. 

@Gav-Brown Can you try if enabling full solution analysis and check if it fixes your problem? https://msdn.microsoft.com/en-us/library/mt709421.aspx

**Comment by heejaechang** [comment] 2018-03-01 00:25
it could be. but build/live error deduplication doesn't care about analyzer type but just diagnostic Ids. the fact that error code is missing indicates that VS think errors from build doesn't belong to us that only can happen if we don't know about those error ids.

**Comment by Gav-Brown** [comment] 2018-03-01 09:31
1. Create a new C# .NET 4.7.1 Class Library (dll) project
2. Add the NuGet packages for Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.0 and StyleCop.Analyzers.1.0.0. Note i use 1.0.0 not 1.0.2 as it doesn't appear to work.
3. Paste the follow code into Class1.cs

```
using System.Threading; // Triggers SA1200, SA1633

namespace TestAnalysers
{
    /// <summary>
    /// Triggers SA1649 as file is called "Class1.cs".
    /// </summary>
    public sealed class Test
    {
        /// <summary>
        /// Triggers CA1001.
        /// Triggers CA1823 which appears in "Output" but not "Error List".
        /// </summary>
        private ManualResetEvent someEvent = new ManualResetEvent(initialState: false);

        /// <summary>
        /// Triggers CA1822.
        /// </summary>
        public void Dispose()
        {
        }
    }
}
```

4. Build
5. Everything works fine except rule CA1823 only appears in the Output window and not the Error List
6. Enable "Full Solution Analysis" and rebuild
7. Now CA1823 appears in the Error List (after a short delay) but should appear without "Full Solution Analysis"
8. However, there are also duplicates for SA1652 and SA1633

So far all IDs have appeared and the "Suppress" context menu is visible.
I'll go back to my project at home this evening and try to create a cut down example from that to show the IDs not appearing.

**Comment by Gav-Brown** [comment] 2018-03-01 19:23
My apologies. It turned out I had the delete the .vs folder for the solution to get the analysers to fully register. After this everything is working fine.  This will probably not affect most users as I use a common.props file to ensure all my projects get Code Analysis and StyleCop turned on, but this requires periodic flushing of the Visual Studio cache to fix odd things like this.

Not fully wasted time though. Looks like

1. CA1823 missing from Error List
2. Duplicate SA1652 and SA1633 when Full Solution Analysis is on

are potentially worth discussing, probably as part of #1559.

Thanks for the help.

**Comment by heejaechang** [comment] 2018-03-01 19:59
thank you. let me take a look.

...

the issue with .vs file could be either a bug related to this
![image](https://user-images.githubusercontent.com/1333179/36866597-8d450d36-1d47-11e8-9866-df0d6b4146e0.png)
(if you turn this option off, and it never repro, please open a bug again here)

or versioning issue in cache in .vs (cache not being invalidated even if analyzer/solution is changed).
for the latter issue, can you describe how you are testing your stuff? we might be able to figure out why cache doesn't get invalidated.

**Comment by Gav-Brown** [comment] 2018-03-01 21:09
Thanks, i'll give the Allow parallel flag a try.

With regards to the .vs cache. I'm not too worried. I added the analysers by hand to a common.props file which each .csproj imports. When loading the .sln it correctly ran these analysers but didn't show them under "references" for each project and hence "broke" the functionality with the IDs in the error list. I know VS has general issues about detecting changes in a shared common.props file as it expects changes directly in the .csproj file which was not the case here. So all in all, i'm happy with deleting the .vs folder if I change this file. Other more minor changes to this file don't need the .vs folder to be deleted, just major ones like this.

**Comment by CyrusNajmabadi** [comment] 2023-11-22 20:26
Haven't seen this issue arise again.  Closing out.

**Closed by CyrusNajmabadi** 2023-11-22 20:26 UTC
Labels: Bug, Area-IDE, Area-Analyzers
