### ISSUE TITLE
Invalid "Collection initialization could be simplified" fix for collections with explicit ICollection.Add implementation

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#24285] opened 2018-01-17 13:05 UTC
**Version Used**: 15.5.3, 15.5.4

**Steps to Reproduce**:
```cs
    public class Test
    {
        public ICollection<Test> Collection;

        public void TestIt()
        {
            // fix proposed here
            Collection = new LinkedList<Test>();
            Collection.Add(this);
        }
    }
```

**Expected Behavior**:
no fix proposed

**Actual Behavior**:
incorrect code generated
```cs
public class Test
    {
        public ICollection<Test> Collection;

        public void TestIt()
        {
               // Error CS1061 'LinkedList<Test>' does not contain a definition for 'Add' and no extension method 'Add' accepting a first argument of type 'LinkedList<Test>' could be found (are you missing a using directive or an assembly reference?)
            Collection = new LinkedList<Test>
            {
                this
            };
        }
    }
```

**Comment by sharwell** [comment] 2018-01-17 15:40
Duplicate of #23672

**Closed by sharwell** 2018-01-17 15:40 UTC
