### ISSUE TITLE
C# suggested parameter name is PascalCased

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38774] opened 2019-09-19 21:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/735864/c-suggested-parameter-name-is-pascalcased.html)._

---
What steps will reproduce the problem?
1. Write out a method signature including parameters.
2. After typing a parameter type, press space.

What is the expected output? What do you see instead?

I expect the C# language service to suggest a parameter name based on the type name in camelCase.
Instead, it shows it to me in PascalCase.

.NET naming has a very strong precedent for using camelCase for parameter names. C# used to do this properly, but it seems to have regressed recently.
See screenshot.

---
#### Visual Studio Feedback System on 9/16/2019, 08:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2019-09-24 19:36
Duplicate of #36248

**Closed by jinujoseph** 2019-09-24 19:36 UTC
Labels: Area-IDE, Bug
