### ISSUE TITLE
unknown hard error visual studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24088] opened 2018-01-07 15:56 UTC
when I have been editing my code , sometimes I have got this message &quot;unknown hard error&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/173286/unknown-hard-error-visual-studio.html
VSTS ticketId: 544141_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-01-07 15:57
The underlying issue here is a hard crash:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
  at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
  at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.TaggerProvider.ProduceTags(TaggerContext`1 context, DocumentSnapshotSpan spanToTag)
  at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.TaggerProvider.ProduceTagsAsync(TaggerContext`1 context, DocumentSnapshotSpan spanToTag, Nullable`1 caretPosition)
  at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.<ProduceTagsAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__83.MoveNext()
Stack:
  at System.Environment.FailFast(System.String, System.Exception)
  at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
  at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
  at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
  at Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
  at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
  at System.Threading.Tasks.Task.Execute()
  at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
  at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
  at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
  at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
  at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
  at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
  at System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
  at System.Threading.Tasks.Task.FinishContinuations()
  at System.Threading.Tasks.Task.FinishStageThree()
  at System.Threading.Tasks.Task.FinishStageTwo()
  at System.Threading.Tasks.Task.Finish(Boolean)
  at System.Threading.Tasks.Task`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
  at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
  at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessInnerTask(System.Threading.Tasks.Task)
  at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessCompletedOuterTask(System.Threading.Tasks.Task)
  at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeCore(System.Threading.Tasks.Task)
  at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
  at System.Threading.Tasks.Task.FinishContinuations()
  at System.Threading.Tasks.Task.FinishStageThree()
  at System.Threading.Tasks.Task.FinishStageTwo()
  at System.Threading.Tasks.Task.Finish(Boolean)
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
  at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by sharwell** [comment] 2018-01-07 15:59
Duplicate of #21301

**Closed by sharwell** 2018-01-07 15:59 UTC
Labels: Area-IDE, Bug, Tenet-Reliability
