### ISSUE TITLE
missing CS4014 warning when calling async func parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63436] opened 2022-08-16 18:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/missing-CS4014-warning-when-calling-asyn/10120044)._

---
having this code:

```
public static void Met1(Func<Task> prm1)
{
    prm1();
}
```
the line `prm1();` should get a warning from VS, that the call is not awaited and green underline like here for example, this works, here I get a CS4014 warning: 

```
Func<Task> getAsyncFunc = () => Task.CompletedTask;

getAsyncFunc();

```

---
#### Feedback Bot on 8/15/2022, 02:33 AM: 

(private comment, text removed)
#### Gen Lu [MSFT] on 8/15/2022, 04:50 PM: 

(private comment, text removed)
#### Valentin Plamadeala on 8/16/2022, 04:17 AM: 

(private comment, text removed)
#### Gen Lu [MSFT] on 8/16/2022, 11:21 AM: 

(private comment, text removed)
#### Valentin Plamadeala on 8/16/2022, 11:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jaredpar** [comment] 2022-08-22 18:20
This behavior is "By Design". The compiler only warns when types / members which are explicitly marked as `async` are not called with `await`. It doesn't do this for every `Task` like returning API.

**Closed by jaredpar** 2022-08-22 18:20 UTC
Labels: Area-Compilers, untriaged
