### ISSUE TITLE
[Test Failure] VSSDK Build error (+1 more) in prtest/win/dbg/unit32 on PR #8424

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8501] opened 2016-02-09 20:39 UTC
PR: [#8424](https://github.com/dotnet/roslyn/pull/8424) *Code Model: Don't crash when adding element, deleting its text and then adding it again* by @DustinCampbell
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3558/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Samples\CSharp\ConvertToAutoProperty\ConvertToAutoPropertyCS.csproj]

**Issue 2: Compile Error**

**Comment by davkean** [comment] 2016-02-09 23:38
Dupe of #8498

**Closed by davkean** 2016-02-09 23:38 UTC
Labels: Bug
