### ISSUE TITLE
Compilation failed with an explicit event block and primary constructor

### ISSUE THREAD

**Issue by ruxo** [dotnet/roslyn#71669] opened 2024-01-17 01:25 UTC
**Version Used**: C# 12 (.NET 8.0.1)

**Steps to Reproduce**:

1. Create a C# console project 
2. Use following code

```csharp
Console.WriteLine("Hello, World!");

interface ITest
{
    event Action SomeAction;
}

sealed class Test(ITest otherTest) : ITest
{
    public event Action SomeAction {
        add => otherTest.SomeAction += value;
        remove => otherTest.SomeAction -= value;
    }
}
```

**Expected Behavior**:
The program should be compilable.

**Actual Behavior**:
A `NullReferenceException` is thrown during the compilation.

The error snippet is following:
```
PS C:\temp\Test> dotnet build
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Process terminated. System.NullReferenceException: Object reference not set to an instance of an object. [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.get_ParameterCount() [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.InMethodBinder.LookupSymbolsInSingleBinder(LookupResult result, String name, Int32 arity, ConsList`1 basesBeing Resolved, LookupOptions options, Binder originalBinder, Boolean diagnose, CompoundUseSiteInfo`1& useSiteInfo) [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsInternal(LookupResult result, String name, Int32 arity, ConsList`1 basesBeingResolved, Look upOptions options, Boolean diagnose, CompoundUseSiteInfo`1& useSiteInfo) [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsWithFallback(LookupResult result, String name, Int32 arity, CompoundUseSiteInfo`1& useSiteI nfo, ConsList`1 basesBeingResolved, LookupOptions options) [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.LookupIdentifier(LookupResult lookupResult, SimpleNameSyntax node, Boolean invoked, CompoundUseSiteInfo` 1& useSiteInfo) [C:\temp\Test\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.IdentifierUsedAsValueFinder.CheckIdentifier(Binder enclosingBinder, IdentifierNameSyntax id) [C:\temp\Te st\Test.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.IdentifierUsedAsValueFinder.CheckIdentifiersInNode(CSharpSyntaxNode node, Binder binder) [C:\temp\Test\T est.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.CapturedParametersFinder.GetCapturedParameters(SynthesizedPrimaryConstructor primaryConstructor) [C:\tem p\Test\Test.csproj]
...
```

**Comment by jaredpar** [comment] 2024-01-18 03:09
@AlekseyTs is this a dupe of #71400

**Comment by AlekseyTs** [comment] 2024-01-19 00:43
> is this a dupe of #71400

It looks like it is.

**Closed** 2024-01-19 01:10 UTC
Labels: Area-Compilers, untriaged
