### ISSUE TITLE
[BUG] When upgrading to dev kit the source generators no longer work.

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68590] opened 2023-06-13 17:53 UTC
From vscode-dotnettools created by [michaelstaib](https://github.com/michaelstaib): microsoft/vscode-dotnettools#37  

### Describe the Issue

I have a project with a source generator which worked with Visual Studio full, Rider and VSCode omnisharp... after upgrading this no longer works. If I build with `dotnet build` I have no errors but the intellisense does not recognise generated code.

### Steps To Reproduce

1. `dotnet new install hotchocolate.templates`
2. `dotnet new graphql`
3. `dotnet build`
4. `code .`

In the program.cs the extension method `AddTypes` has squiggles. This method is created by the source generator.

### Expected Behavior

Source generators work like in the previous version.

### Environment Information

- OS macOS

**Comment by jasonmalinowski** [comment] 2023-07-13 01:04
@michaelstaib: I'm unable to reproduce this with v2.0.249 of the C# extension and v0.2.100 of the C# Dev Kit extension on macOS. Any chance if you're still seeing it reproduce? Generators are expected to work so if something is broken it's something a bit more subtle. There was one fix that went out today that fixed some references not loading in some situations, so it's possible that's the cause here.

**Comment by michaelstaib** [comment] 2023-08-10 16:09
It works with the newest bits.

**Comment by jasonmalinowski** [comment] 2023-08-10 17:13
@michaelstaib I'll close this as fixed again, if you see it again just reactivate and we'll dig further!

**Closed** 2023-08-10 17:12 UTC
Labels: Bug, Area-IDE, New Feature - Source Generators, VSCode
