### ISSUE TITLE
Extract Method refactoring ignores Prefer 'this.' Code Style preference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33618] opened 2019-02-22 23:14 UTC
<p>When Code Style preference is set to Prefer 'this.' regarding method access, using refactoring command Extract Method produces a method call that is not qualified with 'this.'.<br><br>This is a minor issue but it produces code review issues if one forgets to correct it after using Extract Method.<br><br>Otherwise, Extract Method works mostly brilliantly and I love it!</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/466353/extract-method-refactoring-ignores-prefer-this-cod.html
VSTS ticketId: 800730_
_These are the original issue comments:_

Visual Studio Feedback System on 2/22/2019, 04:01 AM (13 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by miloush** [comment] 2019-02-23 10:53
I believe this is duplicate of #14077

**Comment by sharwell** [comment] 2019-02-23 14:28
@miloush It's definitely related to it, but I'm not quite ready to call it a duplicate.

**Comment by miloush** [comment] 2019-02-23 15:47
@sharwell Right, it is more like a duplicate of what I intended, i.e. "all refactoring should follow the 'Preference' choice in Code Style > General" while the referenced one seems to be on the way to be resolved as "generate constructor refactoring should follow Code Style > Naming".

**Closed** 2024-12-11 07:51 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community, IDE-CodeStyle, Feature - Extract Method
