### ISSUE TITLE
XmlDoc containing a "<u>" element is not visible

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#50348] opened 2021-01-08 23:21 UTC
**Version Used**: 

VS 16.9.0 Preview 2.0

**Steps to Reproduce**:

````c#
        /// <summary>
        /// <list type="bullet">
        /// <item>test</item>
        /// <item>test <u>test</u></item>
        /// </list>
        /// </summary>
        static void A()
        {
        }
````

![image](https://user-images.githubusercontent.com/509220/104074456-304eeb00-51de-11eb-9703-b27217620626.png)

**Expected Behavior**:

It shows the text from the XML comment

**Actual Behavior**:

The text is not rendered

**Comment by sharwell** [comment] 2021-01-11 15:15
@AmadeusW I can't find any difference between what we do for `<em>` (which works):

https://github.com/dotnet/roslyn/blob/1223006dad529b84b0a9d81c4dcee239fe87b772/src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs#L363-L367

https://github.com/dotnet/roslyn/blob/1223006dad529b84b0a9d81c4dcee239fe87b772/src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs#L199-L202

And what we do for `<u>` (which does not work):

https://github.com/dotnet/roslyn/blob/1223006dad529b84b0a9d81c4dcee239fe87b772/src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs#L373-L377

https://github.com/dotnet/roslyn/blob/1223006dad529b84b0a9d81c4dcee239fe87b772/src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs#L209-L212

**Comment by sharwell** [comment] 2021-01-11 15:16
I did see the following gold bar when I attempted to reproduce this, but I'm not sure it's related:

```
System.InvalidOperationException: Specified value of type 'System.Windows.TextDecorationCollection' must have IsFrozen set to false to modify.
   at System.Windows.Freezable.WritePreamble()
   at System.Windows.TextDecorationCollection.AddWithoutFiringPublicEvents(TextDecoration value)
   at System.Windows.TextDecorationCollection.Add(IEnumerable`1 textDecorations)
   at Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.WpfClassifiedTextElementViewElementFactory.CreateViewElement[TView](ITextView textView, Object model)
   at Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.ViewElementFactoryService.&lt;&gt;c__DisplayClass6_0`1.&lt;CreateViewElement&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)
```

**Comment by meziantou** [comment] 2021-01-11 15:18
I got the same once! After restarting VS, I've never seen the gold bar again.

**Comment by sharwell** [comment] 2021-01-11 18:46
Duplicate of AB#1260514

**Comment by sharwell** [comment] 2021-01-11 18:46
Here's the public link for the internal issue: https://developercommunity2.visualstudio.com/t/VB-2019-bug-NullReferenceException:-Obj/1295208

**Closed by sharwell** 2021-01-11 18:46 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense, Investigation Required, help wanted
