### ISSUE TITLE
Get no completion for property members if they appear before an await statement

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23798] opened 2017-12-15 02:29 UTC
``` C#
using System;
using System.IO;
using System.Threading.Tasks;

class Program
{
    private Stream _stream;

    private async Task Method()
    {
        _stream.CanTimeout.$

        await _stream.WriteAsync(null, 10, 10);

    }
}

```

1. CTRL+Space at $

Expected: Completion window
Actual: Nothing

**Comment by davkean** [comment] 2017-12-15 02:30
Above is a contrived example, this is my real scenario:
``` C#
        private async Task OnActiveConfigurationsChanged(IProjectVersionedValue<IConfigurationGroup<ProjectConfiguration>> e)
        {
            
            foreach (ProjectConfiguration configuration in e.Value)
            {

                _project.Services.$

                await _project.LoadConfiguredProjectAsync(configuration)
                              .ConfigureAwait(false);

                
            }
        }
```

**Comment by davkean** [comment] 2017-12-15 02:32
What's interesting is that if I start typing a the name of a member, such as `To` - then the completion window does appear.

**Comment by jcouv** [comment] 2017-12-15 04:12
Probably has to do with how the incomplete code gets parsed. See [parse tree](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGAfAAgBgARYCMA3ALABQuBhAdAJIDyZl+RArMxVgEzUDsFAN4U8ovAAcEASwBuEeHgDKMBHAhg8AfVir1ncmInS5CrAA4CANjwBZODAAWAewAmACgCUIscIOGx2ipqYDQAwhAAdgAqUmBwTgCuMDQU3v4EAJxaOsE0AOrS8ACCUACeEQDGbhEJADa1SHiEOI3NHvqGAL4UnUA===) (you can expand the tree on the right-hand-side and see portions of code highlighted on the left).

**Comment by davkean** [comment] 2017-12-15 04:17
Yep, it's parsing the following as a LocalDeclaration:

``` C#
_stream.CanTimeout.

        await _stream
```

**Comment by CyrusNajmabadi** [comment] 2017-12-15 20:03
We have the following code in the parser to try to avoid this problem:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L9381

we may need to expand on this to support more cases.

**Comment by sharwell** [comment] 2019-03-28 13:28
Duplicate of #4474

**Closed by sharwell** 2019-03-28 13:28 UTC
Labels: Area-Compilers, Concept-Diagnostic Clarity
