### ISSUE TITLE
Visual Studio 2017 Crashes when attempting to expand ASP.Net Web Application project

### ISSUE THREAD

**Issue by NoelAbrahams** [dotnet/roslyn#19438] opened 2017-05-11 17:09 UTC
**Version Used**: 

Visual Studio Community 2017 Preview (2) Version 15.3 (26507.0-Preview)

**Steps to Reproduce**:

1. File -> New -> Project > ASP.Net Web Application (.NET Framework) > Empty project.
2. Right click on the project and add new JavaScript file.
3. Close the solution.
4. Reopen the solution.
5. Double click on the project "WebApplication1".
6. VS Crashes.

**Expected Behavior**:
 VS (fingers-crossed) does not crash and expands the project to display the files.

**Actual Behavior**:

VS crashes. Note: This problem only seems to affect ASP.Net Web Application Projects. If, in the same solution, say for example a NodeJS console application was added then there is no error. It's possible that some dependency was not installed, but there is no indication about the source of the problem.

From the event log:

```
Log Name:      Application
Source:        .NET Runtime
Date:          11/05/2017 17:59:55
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Foobar
Description:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.SingleOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.HierarchyItemToProjectIdMap.TryGetProjectId(Microsoft.VisualStudio.Shell.IVsHierarchyItem, System.String, Microsoft.CodeAnalysis.ProjectId ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersFolderItemProvider.CreateCollectionSourceCore(Microsoft.VisualStudio.Shell.IVsHierarchyItem, Microsoft.VisualStudio.Shell.IVsHierarchyItem)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersFolderItemProvider.CreateCollectionSource(Microsoft.VisualStudio.Shell.IVsHierarchyItem, System.String)
   at Microsoft.Internal.VisualStudio.PlatformUI.AttachedCollectionSourceProvider`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Microsoft.VisualStudio.Shell.IAttachedCollectionSourceProvider.CreateCollectionSource(System.Object, System.String)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService+<>c__DisplayClass19_0.<AggregateItemsSource>b__0(System.Lazy`2<Microsoft.VisualStudio.Shell.IAttachedCollectionSourceProvider,Microsoft.VisualStudio.Utilities.IOrderable>)
   at System.Linq.Enumerable+WhereSelectListIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.VisualStudio.PlatformUI.AggregateAttachedCollectionSource..ctor(System.Object, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.IAttachedCollectionSource>)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.AggregateItemsSource(System.Object, System.String)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.GetOrCreateCollectionSource(System.Object, System.String)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotNavigationEntry.ConvertItemToCollectionSource(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.ConvertItemToCollectionSource(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionAdapter.AdaptItem(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.CollectionAdapter`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Initialize(System.Collections.IEnumerable)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionAdapter..ctor(System.Collections.IEnumerable, Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionConverter.Convert(System.Object, System.Type, System.Object, System.Globalization.CultureInfo)
   at System.Windows.Data.BindingExpression.TransferValue(System.Object, Boolean)
   at System.Windows.Data.BindingExpression.Activate(System.Object)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt)
   at System.Windows.Data.BindingExpression.AttachOverride(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   at System.Windows.Data.BindingExpressionBase.OnAttach(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.Data.BindingOperations.SetBinding(System.Windows.DependencyObject, System.Windows.DependencyProperty, System.Windows.Data.BindingBase)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.RealizeChildNodesCore()
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.ExpandInternal()
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.OnIsExpandedChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeViewItem.set_IsExpanded(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.InvokeItem(System.Windows.Input.InputDevice)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.OnMouseLeftButtonDown(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.ContentElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-11T16:59:55.691426300Z" />
    <EventRecordID>62033</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Foobar</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.SingleOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1&lt;System.__Canon&gt;)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.HierarchyItemToProjectIdMap.TryGetProjectId(Microsoft.VisualStudio.Shell.IVsHierarchyItem, System.String, Microsoft.CodeAnalysis.ProjectId ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersFolderItemProvider.CreateCollectionSourceCore(Microsoft.VisualStudio.Shell.IVsHierarchyItem, Microsoft.VisualStudio.Shell.IVsHierarchyItem)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersFolderItemProvider.CreateCollectionSource(Microsoft.VisualStudio.Shell.IVsHierarchyItem, System.String)
   at Microsoft.Internal.VisualStudio.PlatformUI.AttachedCollectionSourceProvider`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Microsoft.VisualStudio.Shell.IAttachedCollectionSourceProvider.CreateCollectionSource(System.Object, System.String)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService+&lt;&gt;c__DisplayClass19_0.&lt;AggregateItemsSource&gt;b__0(System.Lazy`2&lt;Microsoft.VisualStudio.Shell.IAttachedCollectionSourceProvider,Microsoft.VisualStudio.Utilities.IOrderable&gt;)
   at System.Linq.Enumerable+WhereSelectListIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1&lt;System.__Canon&gt;)
   at Microsoft.VisualStudio.PlatformUI.AggregateAttachedCollectionSource..ctor(System.Object, System.Collections.Generic.IEnumerable`1&lt;Microsoft.VisualStudio.Shell.IAttachedCollectionSource&gt;)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.AggregateItemsSource(System.Object, System.String)
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.GetOrCreateCollectionSource(System.Object, System.String)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotNavigationEntry.ConvertItemToCollectionSource(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView.ConvertItemToCollectionSource(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionAdapter.AdaptItem(System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.CollectionAdapter`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Initialize(System.Collections.IEnumerable)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionAdapter..ctor(System.Collections.IEnumerable, Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+ItemCollectionConverter.Convert(System.Object, System.Type, System.Object, System.Globalization.CultureInfo)
   at System.Windows.Data.BindingExpression.TransferValue(System.Object, Boolean)
   at System.Windows.Data.BindingExpression.Activate(System.Object)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt)
   at System.Windows.Data.BindingExpression.AttachOverride(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   at System.Windows.Data.BindingExpressionBase.OnAttach(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.Data.BindingOperations.SetBinding(System.Windows.DependencyObject, System.Windows.DependencyProperty, System.Windows.Data.BindingBase)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.RealizeChildNodesCore()
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.ExpandInternal()
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeView+TreeNode.OnIsExpandedChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at Microsoft.Internal.VisualStudio.PlatformUI.VirtualizingTreeViewItem.set_IsExpanded(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.InvokeItem(System.Windows.Input.InputDevice)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.OnMouseLeftButtonDown(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.ContentElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>
```

**Comment by NoelAbrahams** [comment] 2017-05-11 18:00
To add some extra info:

* If the project is already expanded when the solution is closed, then after reloading the solution, everything works as normal.
* If the project was collapsed when the solution is closed, then after reloading the solution, double-clicking on the project causes the crash reported above.
* If instead of double-clicking, the rotating triangle is used, then there is no crash; the triangle rotates but non of the files in the project are visible.

**Work-around**
Before closing the solution, click on the root solution node in the explorer and repeatedly press "*" until all projects are expanded.
* Now close the solution.
* Next day, after breakfast, open the solution again, just collapses everything using the "Collapse All" icon and carry on working until tea time.

This looks like such a fundamental problem, that I suspect there is something wrong in my setup, or else surely this would have come up in your tests.

Is there a work-around for this, other than the hack I've posted?

**Comment by Pilchie** [comment] 2017-05-11 23:53
@tmeschter: You're already looking at this right?  Can you port to the project-system repo?

**Comment by NoelAbrahams** [comment] 2017-05-12 15:52
I've now started getting this after reloading following a crash:

![image](https://cloud.githubusercontent.com/assets/1106823/26006145/4bd5fdba-3733-11e7-8d97-f393af9af0f2.png)

Should this issue be moved to the TypeScript repo?

**Comment by tmeschter** [comment] 2017-05-12 16:04
@Pilchie @NoelAbrahams There have been a couple of related issues; off hand I can't tell if this is one of those or a new one.

The fix will most likely need to be on the Roslyn side, so I'd like to keep it here for now.

**Comment by tmeschter** [comment] 2017-06-21 21:50
I'm unable to repro this on d15rel 26620.0.

**Comment by tmeschter** [comment] 2017-06-21 21:53
@NoelAbrahams I believe this is a duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems?id=441171&_a=edit, which has already been fixed. I'm going to close this issue; please feel free to reactivate if you still see this occurring.

**Closed by tmeschter** 2017-06-21 21:53 UTC
Labels: Area-External, Bug, Tenet-Reliability

**Comment by NoelAbrahams** [comment] 2017-07-07 18:18
This appears to have been fixed in Preview 3. Thanks.
