### ISSUE TITLE
Interpolation can be simplified: creates compile error on PadLeft with variable length

### ISSUE THREAD

**Issue by roy192** [dotnet/roslyn#42884] opened 2020-03-29 21:21 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2019
Version 16.5.1

**Steps to Reproduce**:
Use a PadLeft inside the curly braces of an interpolated string with a length that isn't constant.
```csharp
int length = int.Parse(Console.ReadLine());
Console.WriteLine($"{"hello".PadLeft(length)} world");
```

This then gives a lightbulb suggesting to simply this: 
![image](https://user-images.githubusercontent.com/6928846/77860673-ab777f80-7210-11ea-939c-2192a75d0ce8.png)

But this gives me a compilation error:
![image](https://user-images.githubusercontent.com/6928846/77860689-c813b780-7210-11ea-92ec-b57f8a14bb92.png)

**Expected Behavior**:
No lightbulb, because this can't be simplified (a comma and then the length doesn't work when the length isn't a constant)

**Actual Behavior**:
An incorrect suggestion, that creates a compile error.

**Comment by CyrusNajmabadi** [comment] 2020-03-30 00:50
Fixed with https://github.com/dotnet/roslyn/pull/42249

**Comment by CyrusNajmabadi** [comment] 2020-03-30 00:51
Dupe of https://github.com/dotnet/roslyn/issues/42247

**Closed by CyrusNajmabadi** 2020-03-30 00:50 UTC
