### ISSUE TITLE
Publish official final stable packages for 3.8.0 (VS 16.8 / .NET 5.0)

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#49296] opened 2020-11-11 21:12 UTC
See https://www.nuget.org/packages/microsoft.codeanalysis

They are still not there.

Need that pronto plz 🙏 

Thanks!

**Comment by khellang** [comment] 2020-11-12 14:18
Duplicate of #49281?

**Closed** 2020-11-12 15:35 UTC
Labels: Area-Infrastructure, untriaged
