### ISSUE TITLE
WinForms designer no longer allows generic base form type

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4987] opened 2015-09-03 22:44 UTC
FWIW, it's not clear that we ever allowed this. At least, it doesn't work in VS 2013 and the Code Model implementation hadn't really changed since VS 2010.

**Comment by xal1983** [comment] 2015-09-24 21:07
Hi Dustin,
I think the issue is a different one. This github issue was created based on the following in connect:
https://connect.microsoft.com/VisualStudio/feedback/details/1664523/typedescriptionprovider-ignored-when-base-class-is-generic

You are correct assuming that generic base classes were never allowed directly in windows forms designers. Neither were abstract classes.

There was a mechanism that worked very well for enabling these scenarios though, which consisted in defining a custom TypeDescriptionProvider in the base form so that the windows forms designer could create an instance of the base class. This is fairly well documented for abstract classes, but generic classes had other complications. I eventually worked around those limitations and came up with a type provider that enabled every scenario. It has worked pretty much since vs2005 (although I had to make some tweaks for vs2010 forward).

The problem seems to be that in VS2015 the type description provider is completely ignored for generic base classes (although it works for non-generic abstract classes). I realized this by attaching a debugger from a 2nd instance of VS and adding a breakpoint in the constructor of the provider.

I created a small sample project that showcases this problem. You can see that if you open it in VS2013 it works fine and fails in 2015. Make sure you compile the project before opening the designers. You can download that from the link to connect provided.

This is currently blocking our team from moving to VS2015 because we have a large framework that was built relying on this functionality to work. Please, help a fellow musician! :)

**Comment by DustinCampbell** [comment] 2015-09-29 14:41
Thanks for the extra information Andrés. Very helpful!

**Comment by xal1983** [comment] 2015-09-29 14:59
Thank YOU for looking into this!

**Closed** 2015-09-30 13:34 UTC
Labels: Area-IDE, Bug

**Comment by MikeGCCC** [comment] 2015-10-12 12:09
We have had this issue.
See https://connect.microsoft.com/VisualStudio/feedback/details/1660664
So this had worked for us before we installed Visual Studio 2015.
Then after installing VS 2015 it stopped working on VS 2013 on that machine as well, quite a few of our developers have now installed VS 2015.

So this is a basic way of having it happen...

'Write code like this for 2 separate forms in 2 separate files
'File1.vb
Public Class Form1
    Inherits baseForm(Of String)

End Class

'File2.vb
Public Class baseForm(Of T)
    Inherits Form

End Class 

In the real life example, we use a DataRow type and then lots of code on a data entry form works with the dataRow.
So for example:
Public Class StudentDetailsForm
    Inherits CCCbaseDetailsForm(Of StudentDetailRow, StudentDataSet)


End Class

We have 100s of details forms that work like this and all did work until VS 2015 was installed.

We would really like this fixing.

Thanks,
Mike G

**Comment by DustinCampbell** [comment] 2015-10-12 12:13
@MikeGCCC, this problem is already fixed, but the change did not make it in time for the VS 2015 Update 1 CTP that was just released. It should be in the next release of VS 2015 Update 1.

**Comment by MikeGCCC** [comment] 2015-10-12 12:18
Excellent news. Thanks v much.

**Comment by ErwinLackner** [comment] 2019-11-05 06:46
Hi @xal1983,
can you give me some information about your mentioned "every scenario" solution for Windows Forms Designer + generic base classes?  I wanted to look at your provided sample project from the connect link, but the link isn't available anymore.  

Thanks
Erwin

**Comment by xal1983** [comment] 2019-11-05 16:29
Hi Erwin,
I'll paste the code here for enabling this behavior. However, I would first like to recommend that you don't use it. I've built a framework with a set of base classes and forms and controls that use this approach and while it has worked for many years, I've always lived in fear of when a new version of VS would come out that would break that. It is super hacky and has its downsides, for instance, sometimes it won't open the designers and you need to make sure you clean solution, restart vs without any designers open and rebuild.
If I had to do it all over again, I would probably go with a more mvvm like approach, using generics/abstract in the viewmodel instead of the form and use interfaces to communicate between the two.

Anyhow, here's what you were looking for, this is VB specific, There might be some differences in requirements for c#, at least there used to be different ways of obtaining the list of inherited controls, but I think that may not be the case anymore (vb used to expose controls as properties instead of fields - there is some commented code that used to deal with that). Keep in mind, the last time I touched this code was 10 years ago, but it works today in VS 2019:
[MagicAttributes.txt](https://github.com/dotnet/roslyn/files/3809941/MagicAttributes.txt)

And this is how you would use it, off the top of my head:
`
<ConcreteClass(GetType(FakeBaseForm)), _
TypeDescriptionProvider(GetType(GeneralConcreteClassProvider)), _
GenericConcreteClass(GetType(BaseForm(Of )))> _
Public Class BaseForm(Of T)
Inherits Form
Public Property Value As T
End Class

 Friend Class FakeBaseForm
        Inherits GenericEditableBase(Of String)

    End Class


Public Class YourRealForm
Inherits BaseForm(Of SomeClass)
End Class

`

Once again, it is a nice experiment, and it was a lot of fun working on this, but if you plan on building something that you can reliably use in the future, I recommend not going this route. It may very well break in .net 5.

Cheers!
