### ISSUE TITLE
Whitespaces in format specifiers of raw strings are not trimmed

### ISSUE THREAD

**Issue by saltukkos** [dotnet/roslyn#69333] opened 2023-08-02 13:21 UTC
**Version Used and steps to reproduce**: 
[Sharplab](https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrjagPYB2AznQDYCmAdAPICuALpwDqAJwCW/dgBkxDdqQAkAIhXUa6jZs0AVABbtEAY14iR7Bv0QATAIaTENhlcT8xAWwNimiNVr//MABE7dm13LgA5OgB3AC4rK05iYk4AT3TU3wDsmgAJXNi3NwBfLJyclSVyAG4ynDq0RhYOHgFhcUkZOVJKhvKtPQNjU3NLW3tHZ1cPRC8+/o0MAAZ4xOS0jPmFvIKi0phtipUAGkRgyTCPTijomthffeKgA=)

**Expected Behavior**:
I expect whitespaces in the format specifier to be trimmed according to raw string literals rules.

**Actual Behavior**:
Format specifier preserves all whitespaces and this leads to different behavior of string interpolation and string.Format - like methods.

So the next code
```
        Console.Out.WriteLine($"""
                               The current date and time is 
                               {DateTime.Now:dd.MM.yyyy
                               HH:mm}.
                               """);
```
prints
```
The current date and time is 
02.08.2023
                               15:10.
```

While the next code
```
        Console.Out.WriteLine("""
                              The current date and time is
                              {0:dd.MM.yyyy
                              HH:mm}.
                              """, DateTime.Now);
```
prints 

```
The current date and time is
02.08.2023
15:10.
```

To achieve the expected behavior with string interpolation I have to format raw string like this:
```
        Console.Out.WriteLine($"""
                               The current date and time is
                               {DateTime.Now:dd.MM.yyyy
HH:mm}.
                               """);
```

Is it by design? 

[jcouv:] Relates to test plan https://github.com/dotnet/roslyn/issues/55306

**Comment by CyrusNajmabadi** [comment] 2023-08-02 14:08
It's currently by design. Whitespace in format specifiers is significant.  We do not manipulate it at all. 

That said, this def seems wonky. A case could be made to*potentially* trim the format specifier prefix. That said, this would be a breaking change, and likely difficult to get now that raw strings have been out so long :-/

**Comment by jcouv** [comment] 2023-08-07 21:06
Closing as by-design

**Closed by jcouv** 2023-08-07 21:06 UTC
Labels: Area-Compilers, Resolution-By Design, untriaged
