### ISSUE TITLE
Intellisense unavailable when inserting a new line before a line that begins with `await`

### ISSUE THREAD

**Issue by mqudsi** [dotnet/roslyn#30736] opened 2018-10-24 22:37 UTC
**Version Used**: 
15.9 Preview 4

**Steps to Reproduce**:

1. Have an async method
2. Have a line that starts with `await `
3. Insert a line above it, type in a variable name followed by the `.` to trigger member completions

**Expected Behavior**:
It terminates the intellisense context at the new line, and presents a list of member variables to complete from.

**Actual Behavior**:
The `await` on the next line breaks the intellisense, as show below. If that new line were inserted _after_ the `await ...` line, it would be fine. 

![image](https://user-images.githubusercontent.com/606923/47465634-5cbfed80-d7b3-11e8-9508-f1568ec8c183.png)

If a semicolon is first inserted, intellisense is fine:

![image](https://user-images.githubusercontent.com/606923/47465675-80833380-d7b3-11e8-870c-c1a33794d5e8.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-25 03:44
This is likely because hte code is parsed as `_db.Inventory.await _db`.  In other words, it looks like the declaration of a variable called `_db` of type `_db.Inventory.await`.  Because it looks like a namespace/type context, you get nothing after `.Inventory` since that's not a type that can be found.

**Comment by CyrusNajmabadi** [comment] 2018-10-25 03:46
Best place to debug into is CSharpRecommendationService.GetSymbolsOffOfName

**Comment by sharwell** [comment] 2019-03-28 13:29
Duplicate of #4474

**Closed by sharwell** 2019-03-28 13:29 UTC
Labels: Area-IDE, Bug, help wanted
