### ISSUE TITLE
GoTo order for types and members is wrong when doing camel case search

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#24191] opened 2018-01-11 21:44 UTC
**Version Used**: VS 2017 15.6 Preview2

**Steps to Reproduce**:

1. Create a new C# console app
2. Add 2 new classes to the project: EditorActiveComponentHostStub and EditorCommandHandlerService
3. Ctrl+T, search ECHS

**Expected Behavior**: I'm looking for **E**ditor**C**ommand**H**andler**S**ervice class and ECHS matches it with exact camel case match, so I expect both file and class to be top results. EditorActiveComponentHostStub also matches ECHS term, but with partial camel case match so I expect it to lower in the result list.

The expected result order **is:**
**E**ditor**C**ommand**H**andler**S**ervice.cs (file)
**E**ditor**C**ommand**H**andler**S**ervice (class)
**E**ditorActive**C**omponent**H**ost**S**tub.cs (file)
**E**ditorActive**C**omponent**H**ost**S**tub (class)

**Actual Behavior**: EditorCommandHandlerService class is on the bottom of the result list:
**E**ditor**C**ommand**H**andler**S**ervice.cs (file)
**E**ditorActive**C**omponent**H**ost**S**tub.cs (file)
**E**ditorActive**C**omponent**H**ost**S**tub (class)
**E**ditor**C**ommand**H**andler**S**ervice (class)

**Proposed fix:** Roslyn NavigateTo provider should use (new in VS 2017 15.6) NavigateToItem constructor, which accepts Microsoft.VisualStudio.Text.PatternMatching.PatternMatchKind and allows to report more specific match kind.

**Comment by sharwell** [comment] 2018-01-11 22:06
Semi-duplicate of #23089?

**Comment by jinujoseph** [comment] 2018-01-11 22:07
related but not dupe

**Comment by CyrusNajmabadi** [comment] 2018-01-11 22:21
@olegtk Does your PatternMatchKind have the Roslyn forms: CamelCaseExact CamelCasePrefix and the like?  Would you want to just contribute the fix to roslyn itself?

**Comment by olegtk** [comment] 2018-01-11 22:27
@chborl is already working on this issue, I just filed this to track it (as we decided #23089 is actually about a different matter).

**Closed** 2018-01-20 01:30 UTC
Labels: Area-IDE, Resolution-Fixed
