### ISSUE TITLE
[Proposal] VB-like "with" opeartor

### ISSUE THREAD

**Issue by WrongBit** [dotnet/roslyn#6553] opened 2015-11-04 13:24 UTC
We all boring of code like this:

```
var MyVeryDescriptiveVariable = new SomeClass();
MyVeryDescriptiveVariable.Field = 1;// OK, can be done in initializer
MyVeryDescriptiveVariable.Event += meth();// why THIS cannot be done in initializer??
MyVeryDescriptiveVariable.Fun();
```

And languages like VB & Delphi many years enjoy with "WITH" operator:

```
with(var MyVeryDescriptiveVariable = new SomeClass(), OtherVar) {
    .Field1 = .Field2;// it was MyVeryDescriptiveVariable.Field1 = OtherVar.Field2
    .Event += meth();// meth() w/o dot means method from outer scope
    MyVeryDescriptiveVariable.Fun();// ambiguous methods are called with full name
}
```

I think this is useful operator, which simpify code and takes not so much efforts to realise.

**Comment by HaloFour** [comment] 2015-11-04 14:24
Dupe of #133

This has been requested since long before C# went 1.0 and the designers already weighed in on it many, many times. Going back to 2004: [Why doesn't C# have VB.NET's 'with' operator](http://blogs.msdn.com/b/csharpfaq/archive/2004/03/11/why-doesn-t-c-have-vb-net-s-with-operator.aspx)?

My opinion is that `with` has no purpose. You can get the same semantics by assigning an expression to a simple short-name variable within a specific scope. Then you can at least continue to refer to the result of the expression, which you cannot do with `with` which is additional functionality actually requested of VB.NET.

**Comment by WrongBit** [comment] 2015-11-04 17:10
It's not a "dupe", you got it wrong. My "with" assume you can use operator everywhere, not only in initialization. And my "with" supports multiple objects to shortcut.
Second, by your link I read only this:

"Many people, including the C# language designers, *believe that*..."

Sorry, but "beliefs" they can leave for wife - I need technical explanation what is wrong when you need to type less code (what in most cases INCREASES readability - one of reasons why C uses {} instead of "begin-end").

>  You can get the same semantics by assigning an expression to a simple short-name variable

Partly I agree, but you talk about just piece of code in curlies - what about external code? Why I should waste my lines just to say "var z = MyVeryDescriptiveVariable"? Code is not a dustbin, it should be short, clear and express only algorithm related stuff. May be those "c# language designers" first should talk to Niclaus Wirth? Sure he has enough reasons why his language contains "with" which still not understandable by "modern designers". ;]

**Comment by HaloFour** [comment] 2015-11-04 17:54
> It's not a "dupe", you got it wrong.

You're right, it's not an exact dupe.  I didn't find another `with` proposal in my short search but it has come up a couple of times, at least on CodePlex:  [586692](http://roslyn.codeplex.com/discussions/586692), [579415](http://roslyn.codeplex.com/discussions/579415), [544179](http://roslyn.codeplex.com/discussions/544179)

> And my "with" supports multiple objects to shortcut.

That sounds like a terrible idea.  Anyone reading that code will not be able to immediately gleam which members refer to which instance.

> Sorry, but "beliefs" they can leave for wife

I'd ask what you mean by that but I'm pretty sure that I don't want an explanation.

>  I need technical explanation what is wrong

I'll paraphrase a Neil Gafter quote, "There never has to be a reason to not do something."

> May be those "c# language designers" first should talk to Niclaus Wirth?

I'm sure that Anders Hejlsberg has at least a passing acquaintance of Niclaus Wirth and his work.  C# ain't Pascal, though.

**Comment by WrongBit** [comment] 2015-11-04 19:14
> it has come up a couple of times, at least on CodePlex

THIS is another proof people *need* "with". This feature doesn't look so impressive compared to Pattern Matching, but "designers" had enough time for 12 years(!) to implement "with".

> Anyone reading that code will not be able to immediately gleam which members refer to which instance

You refer to code which is initially had to be written w/o "with". Same as "obfuscated C code". Normally you'll use "with" with a single object, but there is no obstacles to make it multiple. It's not a problem of "designers" HOW operator will be used - their task is IMPLEMENT this feature.

> C# ain't Pascal, though.

C# is not "functional" too, but immediately borrowed "lambdas" once people made hype of it! So what? Is it reason don't improve language at all? We HAVE to improve c#, since it's still has a lot of places for "boilerplate" or just boring typing (remember DependencyProperties?).

**Comment by HaloFour** [comment] 2015-11-04 19:43
> but "designers" had enough time for 12 years(!) to implement "with".

They've considered it multiple times over 15 years and decided each time that it wasn't worth it.  This isn't a sin of omission.  They aren't waiting to get around to it.  They considered it, listed it's cons and then decided that it wasn't worth it, justifying that decision more than once in various blog posts.

> It's not a problem of "designers" HOW operator will be used - their task is IMPLEMENT this feature.

It's certainly their job to determine how it will be used.  It's their decision whether or not the identified use cases are deserving of a language change and it's their decision how that language change is actually implemented, if at all.  For that it needs to meet an exceptionally high bar, starting with whether or not the problem use case is actually a problem or if alternative solutions are too onerous.  Every new feature is a massive liability.  It needs to demonstrate a massive amount of value in order to make it worthwhile.

**Comment by WrongBit** [comment] 2015-11-04 21:27
> They ... decided that it wasn't worth it,

In other words, they confirm own incompetency: many times feature was requested, but somebody with ram intellect cannot realise it have to be implemented - he thinks he alone is smarter than thousands of developers. OK, I got what you said!

> It's certainly their job to determine how it will be used.

Relax, it's already "determined" by at least TWO development teams: in VB and in Delphi - STILL NOT ENOUGH???

**Comment by HaloFour** [comment] 2015-11-04 21:33
> Relax, it's already "determined" by at least TWO development teams: in VB and in Delphi - STILL NOT ENOUGH???

C# isn't VB nor Delphi.  Nor should it be.  All languages don't need to have every feature from every other language.

> In other words, they confirm own incompetency

> somebody with ram intellect

Should I be claiming that Delphi's designers are totally incompetent for not implementing every feature from APL and COBOL?  No, I shouldn't.  It would be *incredibly* rude for me to do so.

**Comment by WrongBit** [comment] 2015-11-04 21:45
> All languages don't need to have every feature from every other language.

Right. But they should implement features REQUESTED BY DEVELOPERS. Requested MANY TIMES. Even being "mister super senior hyper developer" I never dare to decide for thousands people "you don't need that feature" - but C# team can! Too much power in incompetent hands?....

**Comment by jakesays** [comment] 2015-11-04 22:09
@WrongBit many times is not enough to justify pleasing a handful of VB programmers.

**Comment by paulomorgado** [comment] 2015-11-05 00:00
@WrongBit, you might be surprised to know that when the question is asked, MORE DEVELOPERS REQUES THAT THE RESOURCES BE USED IN SOMETHING MORE USEFUL.

I could throw almost all of your rude insults back at you but I won't.

I'll just say that if [someone](https://en.wikipedia.org/wiki/Anders_Hejlsberg "Anders Hejlsberg") was cleaver enough to put it in __Delphi__ and not in __C#__, he must have had his reasons.

**Comment by alrz** [comment] 2015-11-05 15:01
The example in the original post is not like what is mentioned in #133. This seems more like a duplicate of #5365 rather that #133.
```cs
var MyVeryDescriptiveVariable = new SomeClass() {
    Field = 1,
    Event += meth(),
    Fun()
};
```

**Comment by gafter** [comment] 2017-03-23 21:48
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing the least recently active language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I think this issue is close enough to https://github.com/dotnet/csharplang/issues/307 that discussion can continue there, but you are welcome to open a new issue in `csharplang` if that makes more sense to you.

**Closed by gafter** 2017-03-23 21:48 UTC
Labels: 0 - Backlog, Area-Language Design

**Comment by gafter** [comment] 2017-04-28 22:50
See also https://github.com/dotnet/csharplang/issues/512
