### ISSUE TITLE
BasicGoToDefinition failing on master win vsi p0

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9615] opened 2016-03-09 18:51 UTC
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/960/console

**Comment by TyOverby** [comment] 2016-03-09 19:27
@davkean

**Comment by davkean** [comment] 2016-03-10 16:54
Dupe of this: https://github.com/dotnet/roslyn/issues/6863

**Closed by davkean** 2016-03-10 16:54 UTC
Labels: Area-IDE, Flaky, Test, Urgency-Now
