### ISSUE TITLE
Intellisense doesn't show a const class member

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#23740] opened 2017-12-12 10:55 UTC
**Version Used**: 
VS 15.5.0

**Steps to Reproduce**:
```cs
using System.Collections.Generic;
class Test
{
    private const int max = 6;
    private readonly Queue<int> queue;
    private void foo(int a)
    {
        while (queue.Count > 6)
            queue.Dequeue();
        if (queue.Count < 6)
            return;
    }
}
```
When you replace the `6` in `foo` with `max`, IntelliSense will offer it in case of the `while` loop, but not in case of the `if`.

**Expected Behavior**:
Both times, there should be an Intellisense list showing `max`.

**Actual Behavior**:

![intellisense-without-class-member](https://user-images.githubusercontent.com/1947968/33880854-3920f2e4-df33-11e7-9b66-6aba6bf899b2.gif)

**Comment by dpoeschl** [comment] 2017-12-20 04:06
Thanks for the bug report. That seems really bad, but I haven't been able to reproduce the error here. Can you tell if it looks like I'm doing anything differently:

![constrepro](https://user-images.githubusercontent.com/235241/34190839-e1023436-e4f7-11e7-9b75-8e71786d9744.gif)

**Comment by Tragetaschen** [comment] 2017-12-20 16:31
This was quite some back and forth: I copied the sample code to the original file where I saw it (not including the `using`) and immediately saw the behavior. Then I "Add Class"ed a new file, copied the code in and it worked as you are showing.

Long story short, here is the revised reproduction:
```csharp
using System.Collections.Generic;
using System.Linq; // comment out to have the correct behavior
class Test
{
    private const int max = 6;
    private readonly Queue<int> queue;
    private void foo(int a)
    {
        while (queue.Count > 6)
            queue.Dequeue();
        if (queue.Count < 6)
            return;
    }
}
```
Note the additional, unused using.

**Comment by Tragetaschen** [comment] 2017-12-21 13:39
Maybe it's relevant: This is in a `netstandard2.0` project
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by Tragetaschen** [comment] 2017-12-27 08:27
Is IntelliSense trying to autocomplete Linq's generic `Count<T>()` method instead of the comparison?

**Comment by dpoeschl** [comment] 2018-01-04 20:39
@Tragetaschen Thanks for tracking this down. Yes, it looks like that's what's happening and I can reproduce the failure now with that using.

**Comment by CyrusNajmabadi** [comment] 2020-03-06 06:18
THe problem is that there is a *genuine* accessible generic extension method called `.Count` here.  i.e.

![image](https://user-images.githubusercontent.com/4564579/76057725-35dd0400-5f2f-11ea-8749-1c1b810e070c.png)

So intellisense opts for this being a 'types-only' context.  

Will have to see if we can revise that in the case that there's an existing non-generic instance member in scope as well.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:31
We would take a focused community pr here.

**Comment by genlu** [comment] 2024-12-11 19:35
no longer repro, seems to be fixed now.

**Closed by genlu** 2024-12-11 19:35 UTC
Labels: Bug, help wanted, Area-IDE
