### ISSUE TITLE
Error: Microsoft.Net.Compilers is only supported on MSBuild v16.3 and above

### ISSUE THREAD

**Issue by JesperNoerregaard** [dotnet/roslyn#40130] opened 2019-12-04 07:27 UTC
**Version Used**: Microsoft.Net.Compilers 3.4.0

**Steps to Reproduce**:

1. Update package Microsoft.Net.Compilers from 3.3.1 to 3.4.0 in project A (.Net Framework 4.8 MVC 5 Web App)
2. Build MSTest project that references project A (.Net Framework 4.8 class library)

**Expected Behavior**: No error message

**Actual Behavior**: Error message "Microsoft.Net.Compilers is only supported on MSBuild v16.3 and above."

It seems that inside "Microsoft.Net.Compilers.Props" the variable $(MSBuildToolsVersion) evaluates to "Current". Hence the condition "'$(MSBuildToolsVersion)' &lt; '16.3'" is not met

**Comment by JesperNoerregaard** [comment] 2019-12-04 09:12
Oh, this was created minutes after #40129 - sorry for the duplicate

**Comment by erikbra** [comment] 2019-12-04 12:40
Same issue here. Works on 3.3.1

**Comment by sharwell** [comment] 2019-12-04 20:05
Duplicate of #40129

**Closed by sharwell** 2019-12-04 20:05 UTC
Labels: Area-Compilers
