### ISSUE TITLE
Some msbuild properties get corrupted before being passed to Roslyn analyzers 

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#56180] opened 2021-09-03 21:01 UTC
In my analyzer (source generator, actually), I'm calling: `context.AnalyzerConfigOptions.GlobalOptions.TryGetValue`

This produces a string that is truncated just before the first semicolon that appears in the string as set in the msbuild file. This is unexpected and interferes with my attempt to pass multiple files in a single value. 

@JoeRobich found that [the .editorconfig specification](https://editorconfig-specification.readthedocs.io/#id4) has this to say:

> Inserting a # or ; after non-whitespace characters in a line (i.e., inline) shall neither be parsed as a comment nor as part of the section name, pair (defined below) key or value in which it was inserted. This may change in the future; thus, is not recommended.

Roslyn converts msbuild properties to .editorconfig files. Evidently without properly escaping the values so that an .editorconfig reader can recreate the original strings.

**Comment by chsienki** [comment] 2021-09-07 16:36
Thanks @AArnott. Closing as a dupe of https://github.com/dotnet/roslyn/issues/43970

**Closed by chsienki** 2021-09-07 16:36 UTC
Labels: Bug, Area-Compilers
