### ISSUE TITLE
Rename session abruptly terminated (broken code, shared project)

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3352] opened 2015-06-05 22:14 UTC
1. Sync to https://github.com/amcasey/roslyn/commit/abbca4925361489c1418a25102372f330e537081
1. Open roslyn.sln
1. Open ExpressionEvaluator\Core\Source\ResultProvider\Formatter.TypeNames.cs in the ResultProviderTestUtilities head
1. On line 305 (```sawInvalidIdentifier = !IsIdentifier(identifier);```), invoke rename on ```IsIdentifier```.  New name is ```IsValidIdentifier```.

After either the "I" or the "s", Rename starts reporting unresolvable conflicts and the green highlight around the identifier disappears.  The next keystroke cancels the rename session since it is not in one of the highlighted regions.

Possibly related to #3351

**Comment by amcasey** [comment] 2015-06-05 22:14
FYI @dpoeschl

**Comment by Pilchie** [comment] 2015-06-09 21:50
Can you take a look and try to figure out what the cause of this is?

**Comment by dpoeschl** [comment] 2015-06-09 22:01
The first thing I'd check is whether this continues reproing if you change the assembly name of one of the same-named assemblies (see notes in #3351)

**Comment by dpoeschl** [comment] 2015-06-09 22:04
When @amcasey & I looked through this, the rough cause was the linked file diff merging tracking spans failing to track for one of the document changes -- try debugging through the linked-file stuff in [OpenTextBufferManager.ApplyConflictResolutionEdits](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/InlineRenameSession.OpenTextBufferManager.cs,aeb2268bc3784f9f).

**Comment by balajikris** [comment] 2015-06-10 17:17
Thanks for the notes @dpoeschl. 
* Confirmed that it does **not repro** on changing one of the assembly names.

**Comment by balajikris** [comment] 2015-06-10 20:53
This is basically happening because of #3351 . One of the references in the shared document (one which has common assembly name) comes back with span of length 0 after linked file diff merging and things go wrong right after that.

**Comment by balajikris** [comment] 2015-06-10 21:23
closing this as a dupe of 3351. Will add a note to 3351 for verifying this as well, when the fix for that is available.

**Closed by balajikris** 2015-06-10 21:23 UTC
Labels: Area-IDE, Bug

**Comment by balajikris** [comment] 2015-06-22 22:24
**Note**: This surfaces as a customer scenario in Asp.NET vNext Apps (Console Application Package), because the 2 projects (DNX 4.5.1 and DNX Core 5.0) produce target assembly with same name.

1. File -> New Project -> Console Application (Package)
2. Add a reference to Main method from within itself.
3. Rename Main from either the declaration or reference.
4. Rename is terminated midway.
