### ISSUE TITLE
Testhook is unable to expand item inside Solution Explorer

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8434] opened 2016-02-06 00:14 UTC
The Solution Explorer vsi test is failing in the latest ml standalone run becuase it is unable to expand the class item inside of the solution explorer. Throws an invalidcastexception. Full log is below:

Test: SolutionExplorer started: 2/5/2016 2:19:34 PM
     Executing action [2/5/2016 2:19:34 PM] StartTarget
 Begin Waiting for Apex Communication
     Executing action [2/5/2016 2:19:34 PM] AddProject
     Executing action [2/5/2016 2:19:44 PM] AddItem
     Executing action [2/5/2016 2:19:44 PM] OpenFile
  Scenario: C# Progression Provider
     Executing action [2/5/2016 2:19:44 PM] SetEditorText
     Executing action [2/5/2016 2:19:44 PM] ExpandItem
 --------------------------------
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.PlatformUI.SolutionPivotTreeView' to type 'Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeView'.
    at Roslyn.VSHosting.Test.EditorNugget.<>c__DisplayClass60_0.<GetRootNodes>b__0()
    --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Delegate.DynamicInvokeImpl(Object[] args)
    at System.Delegate.DynamicInvoke(Object[] args)
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByFunc(Object[] values)
    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
 ================================

**Comment by DustinCampbell** [comment] 2016-02-09 17:17
Is this a dupe of the issue that the Analyzers node isn't showing? cc @natidea

**Comment by natidea** [comment] 2016-02-11 00:27
This does not appear related -- I have not seen this exception before. In any case that bug is being fixed by #8554 so we'll know if this problem goes away.

**Comment by natidea** [comment] 2016-03-14 18:36
The Analyzer node issue is now fixed, and is not directly related to this. However this is likely related to the work to determine exchange type dependencies #9096

**Comment by mattscheffer** [comment] 2016-03-25 18:54
A number of new tests are all additionally failing to this as of ML 25124.01
AnalyzersNode.xml
CodeAnalysisRulesetEditor.xml
CodeAnalysisRulesetFile.xml
CSharpSendToInteractive.xml

**Comment by Pilchie** [comment] 2016-04-04 20:55
Dropping to "urgency-soon", since this is in standalone runs.

**Comment by TyOverby** [comment] 2016-04-28 20:19
@mattscheffer What is needed to reproduce this failure?  I've tried getting a dev15 machine on XLab, but I can't repro it there.

Do you have a maddog machine that I could log on to that produced the failure?

**Comment by mattscheffer** [comment] 2016-04-28 20:37
Sure, I'll send an email with info.

**Comment by jaredpar** [comment] 2016-09-09 14:42
Is this bug still relevant?  Hasn't been touched in over four months.

**Comment by mattscheffer** [comment] 2016-09-09 17:13
Not with the effort to move integration tests to Willow. If it fails there too then we can reopen the bug.

**Closed** 2016-09-09 17:20 UTC
Labels: Area-IDE, Test, Urgency-Soon
