### ISSUE TITLE
Acquiring compilations when source generators are involved can significantly impact language features (i.e. completion)

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#55578] opened 2021-08-12 20:38 UTC
# Background & Problem

When investigating a customer reported issue of C# completion behaving slowly I started to peel the onion as to what was going on. Turns out source generators were taking up a significant portion of time which in-turn block language features like completion:

![OpO1Re3Txu](https://user-images.githubusercontent.com/2008729/129265699-34963f91-d41e-49db-92e1-3f6cfb5ee83e.gif)

After profiling the issue and digging through Roslyn's source generator runners I found that source generator calculations were consuming nearly 93% of the time for completion:
![image](https://user-images.githubusercontent.com/2008729/129265449-3365b035-0a98-4ff5-9a67-e6ca1d26a96f.png)

Digging into some specific generators I also found that Razor's incremental source generator was also taking up roughly 53% of the time:
![image](https://user-images.githubusercontent.com/2008729/129265100-315b92d3-7092-4cc8-989d-8bd54777bab7.png)

# Solution

Given source generators are a public extension point now and many of them will be written in days to come we need to ensure our language features continue to work even in the presence of slower generators. @sharwell had some ideas about the language feature performance interaction in this area and proposed:

1. We'd have a "frozen partial compilation" which would have partial frozen semantics avoid source generator execution. It'd assume the last known SG output is still the correct one to prevent us from re-running the SG aggressively. Consider the case of an analyzer that takes 20 seconds to run: for the first 20 seconds, APIs defined by source generators would not appear in high-profile features like completion. After that we'd update models for generators every 20s (assuming they can run fast enough).

**Comment by sharwell** [comment] 2021-08-16 17:24
It looks like frozen partial semantics already behaves as described here. The stacks I've found so far indicate certain features on low-latency paths are failing to use frozen partial semantics.

**Comment by seanjbsol** [comment] 2021-08-17 23:02
Can I just thank you all for looking into this. Much appreciated!

**Comment by jasonmalinowski** [comment] 2021-09-07 22:57
Also assigning this bug to @genlu: the one known piece of work remaining here _for completion_ is to ensure we get tests added for catching the completion regression around partial semantics. We think this can be closed out once that's complete.

**Closed** 2021-09-22 01:19 UTC
Labels: Bug, Area-IDE, Area-Performance, Investigation Required
