### ISSUE TITLE
Definite assignment versus StructLayout(LayoutKind.Explicit)

### ISSUE THREAD

**Issue by ilexp** [dotnet/roslyn#10319] opened 2016-04-04 19:04 UTC
**Version Used**: Visual Studio Community 2015. Just the regular download, not a preview.

**Steps to Reproduce**:

Compile the following code:
```C#
public struct Vector2
{
	public float X;
	public float Y;
}

[StructLayout(LayoutKind.Explicit)]
public struct Vector3
{
	[FieldOffset(0)]
	public float X;
	[FieldOffset(sizeof(float))]
	public float Y;
	[FieldOffset(sizeof(float) * 2)]
	public float Z;
	
	[FieldOffset(0)]
	public Vector2 Xy;

	public Vector3(float x, float y, float z)
	{
		this.X = x;
		this.Y = y;
		this.Z = z;
	}
}
```
It will fail with the following error:
```
error CS0171: Field 'Vector3.Xy' must be fully assigned before control is returned to the caller
```

**Expected Behavior**:

Due to the explicit struct layout, all fields are assigned. Despite being not actually required, I suspect that doing a double assignment could affect performance in a slightly negative direction. Maybe the compiler could take a look at the explicit struct layouts and data types in order to deduce that the struct has been fully assigned?

**Actual Behavior**:

See the error above.

-------

This is probably not a bug, but expected behavior - yet I think that it might be a neat thing if an explicit struct layout would be considered by the compiler to allow performance optimizations like the above. 

The following alternative compiles, but probably isn't as efficient and doesn't have the benefit of direct access to data:
```C#
public struct Vector3
{
	public float X;
	public float Y;
	public float Z;

	public Vector2 Xy
	{
		get { return new Vector2(this.X, this.Y); }
		set { this.X = value.X; this.Y = value.Y; }
	}

	public Vector3(float x, float y, float z)
	{
		this.X = x;
		this.Y = y;
		this.Z = z;
	}
}
```

**Comment by HaloFour** [comment] 2016-04-04 19:27
Did you try the following:

```cs
    public Vector3(float x, float y, float z)
    {
        this.Xy = default(Vector2);
        this.X = x;
        this.Y = y;
        this.Z = z;
    }
```

I'd think that the JIT compiler could optimize out that extraneous assignment.

**Comment by ilexp** [comment] 2016-04-04 20:22
I'm not much of an assembly wizard, but here's what the Disassembly window in VS shows in release mode.

With the `Xy` field:
```
			Vector3 test = new Vector3(1, 2, 3);
01092DC6  lea         edi,[ebp-14h]  
01092DC9  xorps       xmm0,xmm0  
01092DCC  movq        mmword ptr [edi],xmm0  
01092DD0  fld1  
01092DD2  fstp        dword ptr [ebp-14h]  
01092DD5  mov         dword ptr [ebp-10h],40000000h  
01092DDC  mov         dword ptr [ebp-0Ch],40400000h  
```

Without the `Xy` field:
```
			Vector3 test = new Vector3(1, 2, 3);
00A32DBA  fld1  
00A32DBC  fstp        dword ptr [ebp-8]  
00A32DBF  mov         dword ptr [ebp-0Ch],40000000h  
00A32DC6  mov         dword ptr [ebp-10h],40400000h  
```

Doesn't look like the default assignment for `Xy` gets optimized away entirely, or I would expect the disassembly to look the same.

**Comment by ilexp** [comment] 2016-04-04 20:26
Here's the same in IL.

With the `Xy` field:
```
.method public hidebysig specialname rtspecialname 
	instance void .ctor (
		float32 x,
		float32 y,
		float32 z
	) cil managed 
{
	// Method begins at RVA 0x2050
	// Code size 34 (0x22)
	.maxstack 8

	IL_0000: ldarg.0
	IL_0001: ldflda valuetype VectorTest.Vector2 VectorTest.Vector3::Xy
	IL_0006: initobj VectorTest.Vector2
	IL_000c: ldarg.0
	IL_000d: ldarg.1
	IL_000e: stfld float32 VectorTest.Vector3::X
	IL_0013: ldarg.0
	IL_0014: ldarg.2
	IL_0015: stfld float32 VectorTest.Vector3::Y
	IL_001a: ldarg.0
	IL_001b: ldarg.3
	IL_001c: stfld float32 VectorTest.Vector3::Z
	IL_0021: ret
} // end of method Vector3::.ctor
```

Without the `Xy` field:
```
.method public hidebysig specialname rtspecialname 
	instance void .ctor (
		float32 x,
		float32 y,
		float32 z
	) cil managed 
{
	// Method begins at RVA 0x2050
	// Code size 22 (0x16)
	.maxstack 8

	IL_0000: ldarg.0
	IL_0001: ldarg.1
	IL_0002: stfld float32 VectorTest.Vector3::X
	IL_0007: ldarg.0
	IL_0008: ldarg.2
	IL_0009: stfld float32 VectorTest.Vector3::Y
	IL_000e: ldarg.0
	IL_000f: ldarg.3
	IL_0010: stfld float32 VectorTest.Vector3::Z
	IL_0015: ret
} // end of method Vector3::.ctor
```

**Comment by HaloFour** [comment] 2016-04-04 22:59
I'd expect that the IL would contain those opcodes, but I didn't know if the JIT might be aggressive enough to optimize them away.  But there are probably valid scenarios where the memory location of the struct isn't preinitialized thus making that assignment necessary, or it's just not a scenario that has been considered.  Anywho, just looking to see if there was a workaround to your issue.  I doubt that the C# compiler really considers potential field overlap when it comes to ensuring that a struct is fully initialized by a constructor which would make this a feature request.

**Comment by mburbea** [comment] 2016-04-05 20:00
What about the classic (and horribly confusing):
```csharp
    public Vector3(float x, float y, float z)
    {
        this = default(Vector3);
        this.X = x;
        this.Y = y;
        this.Z = z;
    }
```

**Comment by ilexp** [comment] 2016-04-06 16:35
The disassembly of that one still looks a lot bigger than the one without the additional assignment:

```
			Vector3 test = new Vector3(1, 2, 3);
00D134C6  lea         edi,[ebp-14h]  
00D134C9  xor         eax,eax  
00D134CB  xorps       xmm0,xmm0  
00D134CE  movq        mmword ptr [edi],xmm0  
00D134D2  add         edi,8  
00D134D5  stos        dword ptr es:[edi]  
00D134D6  fld1  
00D134D8  fstp        dword ptr [ebp-14h]  
00D134DB  mov         dword ptr [ebp-10h],40000000h  
00D134E2  mov         dword ptr [ebp-0Ch],40400000h  
```

Performance being one of the main reasons of implementing `Xy` access like this in the first place, this doesn't seem to be a good workaround.

**Comment by gafter** [comment] 2016-04-11 02:47
This would reequire a change to the language spec, so reclassifying as a language issue.

**Comment by orthoxerox** [comment] 2016-04-11 06:42
Duplicate of #7323

**Closed** 2016-04-11 16:34 UTC
Labels: 0 - Backlog, Area-Language Design
