### ISSUE TITLE
Generic Enums (Not sure if this is the right place for this)

### ISSUE THREAD

**Issue by chassq** [dotnet/roslyn#21813] opened 2017-08-30 13:24 UTC
Recently I was trying to implement something like a Generic Enum Property. I looked at Enum and TEnum but they did not seem to provide what I needed. Is there any work to make Enums more flexible to work with (a la Java)? Thanks!

**Comment by svick** [comment] 2017-08-30 14:33
Could you explain exactly what do you mean? How would the "generic enum property" look like and what would it do?

**Comment by AdamSpeight2008** [comment] 2017-08-30 15:06
Is what you need anything like [CSharpLang # 104](https://github.com/dotnet/csharplang/issues/104)?

**Comment by chassq** [comment] 2017-08-31 08:58
I believe that would be the general idea.

**Comment by sharwell** [comment] 2017-08-31 12:08
This appears to be a duplicate of dotnet/csharplang#274, dotnet/csharplang#297, and/or dotnet/csharplang#104, depending on how @chassq was planning to use these types.

**Closed** 2017-08-31 12:10 UTC
Labels: Area-Language Design, Resolution-Duplicate

**Comment by chassq** [comment] 2017-08-31 12:49
I think it does. Thanks for the response!
