### ISSUE TITLE
Preview never shows if you drop the inline lightbulb

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18849] opened 2017-04-20 04:43 UTC
Build: VisualStudio.15.int.vsuwpt/15.2.0-Preview+26410.1.vsuwpt

This could be related to: https://github.com/dotnet/roslyn/issues/18596

If you drop the inline lightbulb like called out in the video, the preview never shows and just spinning donuts forever:

``` C#
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Lamda(() =>
            {
                Console.WriteLine("Foo");

            });
        }

        public static void Lamda(Func<Task> asyncMethod)
        {

        }
    }
}
```

![previewnevershows](https://cloud.githubusercontent.com/assets/1103906/25213887/426c999a-25d7-11e7-87e8-b92ee2b34430.gif)

**Comment by davkean** [comment] 2017-04-20 04:43
The preview shows if you use the lightbulb in the margin.

**Comment by Pilchie** [comment] 2017-05-25 02:16
@olegtk Have you heard of anything like this?

**Comment by olegtk** [comment] 2017-05-25 06:48
Nope. Is it reproducible? I installed vsuwpt 26519.0 and cannot repro. I'm not even getting that huge green squiggle either.

**Comment by sharwell** [comment] 2017-05-25 07:04
I've seen this before but couldn't ever reproduce it when I wanted to.

**Comment by olegtk** [comment] 2017-05-25 07:25
We do log the time it took to create a preview so I will look at telemetry tomorrow. Having a memory dump at this state might be useful too. Conceptually we just await ISuggestedAction.GetPreviewAsync() and show the spinner meantime.

**Comment by davkean** [comment] 2017-05-25 07:28
The span that the warning occurs on has changed - it used to cover the entire lambda, and I can't repro.

I did repro this though, lightbulb will show in following if you hover over => and it will never show? Can't remember if I've filed this one before?
``` C#
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Lamda(() =>
            {
                Console.WriteLine("Foo");

            });
        }

        public static void Lamda(Func<Task> asyncMethod)
        {

        }
    }
}
```

**Comment by sharwell** [comment] 2017-05-25 07:28
@olegtk Do you log the time if they cancel before the preview appears? When this occurred for me I let it sit for a long time, maybe minutes, before just cancelling it.

**Comment by davkean** [comment] 2017-05-25 07:35
Filed https://github.com/dotnet/roslyn/issues/19772 to track the new bug, I've repro'd the above (original) issue a few times - it looks like the conditions have changed since I tested this, so I don't think it's a good representation of the repro anymore. need to find another repro.

**Comment by Pilchie** [comment] 2017-05-25 15:51
@davkean - we (@cyrusnajmabadi) deliberately changed the span of some lambda related errors so they weren't huge and obscuring of other issues *in* the lambdas.

Does that mean this should be closed in favor of #19772 until we get a repro?

**Comment by davkean** [comment] 2017-05-26 00:29
This bug is different to #19772, if someone wants a repro go back a build before the spans changed - I wonder if that's related.

**Comment by dpoeschl** [comment] 2017-09-26 21:28
@olegtk @davkean Has this still been happening? Do we know of any other feedback or fixes since this was last discussed?

**Comment by olegtk** [comment] 2017-09-26 21:36
no, we haven't seen any other feedback like this.

**Comment by davkean** [comment] 2017-09-26 23:07
I still see it occasionally on 15.3.

**Comment by CyrusNajmabadi** [comment] 2023-11-22 18:22
Havne't seen this in many years, and tehse systems were heavily rewritten.  closing out.

**Closed by CyrusNajmabadi** 2023-11-22 18:22 UTC
Labels: Bug, Area-IDE
