### ISSUE TITLE
Incorrect CS8170 when calling [UnscopedRef] method to assign to a fixed local

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63529] opened 2022-08-22 23:36 UTC
> **NOTE:** possibly related to #63524.

**Version Used**:  4.4.0-2.22419.1 (ae566380)

**Steps to Reproduce**:

1. Paste the following code:
```csharp
ref struct A
{
    unsafe void Foo()
    {
        fixed (byte* p = GetSpan())
        {

        }
    }

    [UnscopedRef]
    Span<byte> GetSpan() => default;
}
```

**Expected Behavior**:

The code should compile fine, as the method is directly assigned to a pointer, which should not be tracked.
Effectively, I'd expect the compiler to treat this as if I was assigning to a `scoped` local first and then pinning that.

**Actual Behavior**:

The build fails with:

> "error CS8170: Struct members cannot return 'this' or other instance members by reference"

![](https://user-images.githubusercontent.com/10199417/186037851-ae0ad97f-4872-49b7-9ade-9734ae53cc48.png)

**Comment by jaredpar** [comment] 2022-08-30 03:49
Guessing this is a duplicate of #63524 but will let @cston confirm

**Comment by AlekseyTs** [comment] 2022-09-01 21:01
It looks like this behavior is By Design due to the same reason explained at https://github.com/dotnet/roslyn/issues/63524#issuecomment-1232041859.

**Closed by AlekseyTs** 2022-09-01 21:01 UTC
Labels: Bug, Area-Compilers, New Language Feature - Ref Fields
