### ISSUE TITLE
Errors in ErrorList pane on lines with #line pragma doesn't navigate to the source file

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#34950] opened 2019-04-12 00:10 UTC
**Version Used**: 
VS 16.1 Preview 1

**Steps to Reproduce**:

1. `dotnet new console`
2. Replace content of `Main` method with
```cs
        static void Main(string[] args)
        {
#line 2 "Test.txt"
            Console.WriteLin("Hello World!"); // Intentional typo to show error
#line default
        }
```
3. Create a file called `Test.txt` and put some content in it.

**Expected Behavior**:
Error shows in error list. Double clicking it navigates to `Test.txt`

**Actual Behavior**:
Error shows in error list. Double clicking it navigates to `Program.cs` or does nothing.
This happens on both live and build errors

Note: Putting a breakpoint in `Test.txt` and F5ing correctly hits that breakpoint. So it's not a file path issue.

cc @heejaechang

**Comment by heejaechang** [comment] 2019-05-02 18:59
@ajaybhargavb this is by design. we could change behavior for build if we want. let me talk with other people whether we want to change this behavior.

**Comment by heejaechang** [comment] 2019-05-02 19:09
@ajaybhargavb can you give us your scenario and what you are trying to do. I will bring this to design discussion.

**Comment by heejaechang** [comment] 2019-05-02 19:17
this is how we work currently.

```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
#line 2 "Test.txt"
            Console.WriteLin("Hello World!"); // Intentional typo to show error
#line default
        }
    }
}
```

we show squiggles like this

![image](https://user-images.githubusercontent.com/1333179/57100279-60d54680-6cd3-11e9-9982-e58ad1e7313d.png)

we show errors in error list like this for live error
![image](https://user-images.githubusercontent.com/1333179/57100330-86625000-6cd3-11e9-8388-c94770a0efea.png)

if one double click the item, it goes to where the squiggle is.

we show errors in the error list like this for build error
![image](https://user-images.githubusercontent.com/1333179/57100459-d6d9ad80-6cd3-11e9-9184-7bfabdf5dc54.png)

if one double click the item, it goes no where.

...

duplicated item is a bug - https://github.com/dotnet/roslyn/issues/35448

but except that, other is by design. 

need to decide whether we want to change design and how.

**Comment by ajaybhargavb** [comment] 2019-05-02 20:49
> if one double click the item, it goes to where the squiggle is.

I don't understand why this is by design. Isn't the whole point of adding a line pragma is so that the diagnostics and breakpoints actually point to the file specified in the pragma?

**Comment by heejaechang** [comment] 2019-05-02 21:58
@ajaybhargavb could be. people will either lose squiggle or squiggle show up in original location but error list show mapped location but, that might be completely fine for people. squiggle won't show up since we can't currently show our squiggle in some random file we don't own.

but that is the current design. our current design could be wrong, but that is how it is now. 

...

except for those bug, what it currently does is trying to move users to where it can actually fix the issue.

**Comment by sharwell** [comment] 2019-05-13 15:18
This went to a design review 6 May 2019. We reached the following conclusion:

* Double-clicking an item in the error list should navigate to the location mentioned in the error. For the items in this issue, the navigation should take the user to the *mapped* source location.
* Squiggles should continue to appear in the unmapped source location.
* We would like the ability to show squiggles and allow the user to use the light bulb features from additional files (and mapped source locations), but this is not currently implemented. We are leaving it as a separate feature request.

**Comment by CyrusNajmabadi** [comment] 2024-10-20 19:35
Closing out as these experiences were entirely rewritten.

**Closed by CyrusNajmabadi** 2024-10-20 19:35 UTC
Labels: Bug, help wanted, Area-IDE
