### ISSUE TITLE
Roslyn should have better support for document rename.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#13448] opened 2016-08-29 23:18 UTC
**Issue**
Currently tracking a document rename requires listening for a document removal and subsequent document add event from the workspace.

**Suggestion**
The workspace should expose a DocumentRenamed event and provide some method for renaming a Document.

**Comment by balajikris** [comment] 2016-08-29 23:24
+1, We also need a RenameDocument() api. Currently rename document to match type name refactoring achieves this by RemoveDocument() and AddDocument().

**Comment by mattwar** [comment] 2016-09-02 18:26
Do you also want change events for other properties on document, like FilePath and Folders?  Typically this level of detail is not exposed via separate events and we rely on DocumentChanged event.

@tannergooding is the reason you are needing to listen for remove & add events is due to @balajikris claim that renames current need to be implemented as remove & add document requests?  Or is for any rename being pushed down by project system?

**Comment by Pilchie** [comment] 2016-11-02 22:56
Duplicate of #6261

**Closed by Pilchie** 2016-11-02 22:56 UTC
Labels: Area-IDE, Concept-API
