### ISSUE TITLE
MisplacedUsingDirectivesDiagnosticAnalyzer crashes with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39715] opened 2019-11-07 03:44 UTC
**Version Used**: 
Version 16.5.0 Preview 1.0 [29506.167.master]

**Steps to Reproduce**:

``` C#
namespace Microsoft.VisualStudio.ProjectSystem.Build
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.ComponentModel.Composition;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Build.Execution;
    using Microsoft.Build.Framework;
    using Microsoft.VisualStudio.ProjectServices;
    using Microsoft.VisualStudio.Threading;

    /// <summary>
    /// Standard implementation of the <see cref="IDesignTimeBuildServiceBridge"/> service.
    /// </summary>
    [Export(typeof(IDesignTimeBuildManagerService))]
    [Export(typeof(IDesignTimeBuildManagerServiceInternal))]
    [Export(typeof(IDesignTimeBuildCacheParticipant))]
    [AppliesTo(ProjectCapabilities.AlwaysApplicable)]
    [Order(int.MaxValue)]
    internal partial class DesignTimeBuildManagerService : IDesignTimeBuildManagerServiceInternal, IDesignTimeBuildCacheParticipant
    {
[...]
   }
```

```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'.	Microsoft.VisualStudio.ProjectSystem.Implementation		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Implementation
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Build\DesignTimeBuildManagerService.cs
SyntaxNode: namespace Microsoft.VisualStudio ... [NamespaceDeclarationSyntax]@[301..30792) (6,0)-(646,1)

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.SequenceEqualComparer.Equals(List`1 x, List`1 y)
   at Microsoft.CodeAnalysis.ConcurrentCache`2.TryAdd(TKey key, TValue value)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(String sourcePath)
   at Microsoft.CodeAnalysis.ProjectState.WorkspaceAnalyzerConfigOptionsProvider.GetOptions(SyntaxTree tree)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.GetFilteredDiagnostic(Diagnostic diagnostic, Compilation compilation, AnalyzerOptions analyzerOptions)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass117_0.<GetDiagnosticSink>b__0(Diagnostic diagnostic, DiagnosticAnalyzer analyzer, Boolean isSyntaxDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.AnalyzerDiagnosticReporter.AddDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.ReportDiagnostics(SyntaxNodeAnalysisContext context, DiagnosticDescriptor descriptor, IEnumerable`1 usingDirectives, CodeStyleOption`1 option)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by sharwell** [comment] 2019-11-07 19:44
Duplicate of #39599

**Closed by sharwell** 2019-11-07 19:44 UTC

**Comment by davkean** [comment] 2019-11-07 21:52
Whoops already reported this.,
