### ISSUE TITLE
[Test Failure] MSBuild Error in windows_vsi_p2_open_prtest on PR #12097

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12507] opened 2016-07-14 00:43 UTC
PR: [#12097](https://github.com/dotnet/roslyn/pull/12097) *refactor how we do completion set filtering.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/257/

**Issue 1: MSBuild Error**
error MSB3073: The command ""d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Tools\ibcmerge\ibcmerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p---5fa6ff52\Open\Binaries\Obj\ServicesVisualStudio\Release\Microsoft.VisualStudio.LanguageServices.dll" -incremental "d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\OptimizationData\Microsoft.VisualStudio.LanguageServices.pgo"" exited with code -1. [d:\j\workspace\windows_vsi_p---5fa6ff52\Open\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]

**Comment by tannergooding** [comment] 2016-07-14 02:33
Duplicate of #12508

**Closed by tannergooding** 2016-07-14 02:33 UTC
Labels: Bug, Resolution-Duplicate
