### ISSUE TITLE
Incorrect fix offered for mixing declarations and expressions in a deconstruction

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#29040] opened 2018-08-02 23:11 UTC
I'm seeing this on current dogfood build and in 15.8.x branch

1) Create a console app and add this code

```csharp
class Program
    {
        static void Main(string[] args)
        {
            (var x, var) = (1,);
        }
    }
```
2) hover over the diagnostic on `(var x, var)` and see message "A deconstruction cannot mix declaration and expressions on the left-hand-side"

3) Click on Show Potential Fixes and see "Use explicit type instead of var" as a suggested fix.

This doesn't fix the issue of mixing declarations and expressions, so it shouldn't be offered.

**Comment by jcouv** [comment] 2018-08-05 06:03
I think the refactoring (UseExplicitType) is unrelated to the diagnostic. It is not meant to fix the diagnostic, but rather just make types explicit (in this case `var` -> `int`.
Seems by-design.

**Comment by sharwell** [comment] 2018-08-07 16:44
Resolving as by design. Please feel free to raise it at a future design review if you think of a way to improve the clarity of this interaction. 👍

**Closed by sharwell** 2018-08-07 16:44 UTC
Labels: Area-IDE
