### ISSUE TITLE
"Find All References" does not find all the associated references of namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74718] opened 2024-08-12 14:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-All-References-does-not-find-all-/10718733)._

---
\[severity:I’m unable to use this version\]  
As you can see in the attached screenshot - “Find All References” only found “usings” of a given namespace, but “ClippingUtility” class that is defined under that namespace, as well as some other classes - are not present in the search.  
This is a critical issue for my workflow.

upd:
This bug is only present in "Project Then Definition" grouping, as far as I observe. "Project then Containing Type" for example - does not produce such issue.

---
#### Feedback Bot on 8/8/2024, 10:10 PM: 

(private comment, text removed)
#### Alessio T on 8/10/2024, 10:14 AM: 

(private comment, text removed)
#### Sam Harwell on 8/12/2024, 09:18 AM: 

<p>Hi <a target='_blank' href="https://developercommunity.visualstudio.com/user/29047/profile">Alessio T</a>,</p>
<p>Can you file a separate issue for your feedback. The current issue is only being handled by the C# language team, and I have no way in the tooling to redirect a comment within the larger issue over to the C++ team.</p>
<p>Thank you,<br>
Sam Harwell</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-08-12 22:10
It's unclear what the issue is here.  The picture the user showed seems reasonable:

![Image](https://github.com/user-attachments/assets/79cadddf-13e6-4368-aaf0-4815b33913e8)

**Comment by CyrusNajmabadi** [comment] 2024-08-13 16:43
@LVNov Gotcha.  Thanks for the clarification!

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:40
Closing out as unplanned.  Find references finds symbol references.  Not references to symbols related to that symbol

**Closed by CyrusNajmabadi** 2024-11-26 02:40 UTC
Labels: Bug, Area-IDE, Navigation-FAR
