### ISSUE TITLE
AV in the Roslyn C# compiler while binding attributes

### ISSUE THREAD

**Issue by lingamy** [dotnet/roslyn#6534] opened 2015-11-03 19:25 UTC
I'm using VS 2015 Update RC build for doing COSMOS development. While writing code, VS crashes. I found the following entry (Event ID 1026) in the event log

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Roslyn.Compilers.CSharp.SourceAssemblySymbol.DetectAttributeAndOptionConflicts(Roslyn.Compilers.DiagnosticBag)
   at Roslyn.Compilers.CSharp.SourceAssemblySymbol.ValidateAttributeSemantics()
   at Roslyn.Compilers.CSharp.SourceAssemblySymbol.ForceComplete(Roslyn.Compilers.CSharp.SourceLocation, System.Threading.CancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.GetSourceDeclarationDiagnostics(System.Threading.CancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.GetDiagnostics(Roslyn.Compilers.CompilationStage, System.Threading.CancellationToken)
   at ScopeCompiler.FrontEnd.RoslynWarmUpEnvironment.CreateCompilation()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by jaredpar** [comment] 2015-12-02 15:42
Thanks for reporting this issue.

Does this reproduce reliably?  We've seen occasional reports of this issue and have been unable to identify the root cause nor can we reproduce it locally.

**Comment by jaredpar** [comment] 2016-03-30 20:07
Closing for now.  Please reopen if you're able to give us a repro for this.

**Closed by jaredpar** 2016-03-30 20:07 UTC
Labels: Area-Compilers, Bug, Need More Info, Tenet-Reliability
