### ISSUE TITLE
Missing quick fixes before members

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#7980] opened 2016-01-15 11:43 UTC
I finally managed to find a simple repro I believe:
1. Create a new WPF application project.
2. Go to MainWindow.xaml.cs.
3. Type `WebClient` in front of `MainWindow`'s constructor, like this:

``` C#
public partial class MainWindow : Window
{
    WebClient|
    public MainWindow()
    {
        InitializeComponent();
    }
}
```

At this point, a quick fix for CS0246 should be offered to resolve `WebClient` (i.e. add `using System.Net`). Actual results: no quick fix (probably because CS0246 is not generated at all).

I am not sure what triggers the issue, the same thing in console application works and under certain circumstances in WPF projects too. Anyway, I believe the _add using_ option was available at this point in previous versions.

**Comment by Pilchie** [comment] 2016-01-15 17:34
Thanks for the report.  It looks like this worked in VS2015 RTM, then was regressed in Update 1, but is now working again in internal builds.  @CyrusNajmabadi Can you verify that we have good test coverage here?

**Comment by CyrusNajmabadi** [comment] 2016-01-19 22:39
This is failing because of: https://github.com/dotnet/roslyn/issues/7536

We need to fix the issue that we don't get errors for incomplete members so that this works.

**Comment by Pilchie** [comment] 2016-01-22 03:00
I could have sworn I saw this work with the latest bits...

**Comment by DustinCampbell** [comment] 2016-02-22 21:45
This is a regression that we shipped in Update 1. I get that we'd like a compiler fix for it with #7536, but that's been pushed to 2.0. Is there a fix we can make now to fix the regressed behavior and then drive for the right fix later?

**Comment by CyrusNajmabadi** [comment] 2016-03-31 00:45
ping @gafter This is the same issue.  We don't report semantic errors on incomplete members.

**Comment by CyrusNajmabadi** [comment] 2016-04-19 19:07
Assigning to gafter as this involved binding incomplete members.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 19:38
This is working for me:

![image](https://user-images.githubusercontent.com/4564579/198718585-65fc059a-b1d7-4e90-a933-a1195fe5b655.png)

**Closed by CyrusNajmabadi** 2022-10-28 19:38 UTC
Labels: Bug, help wanted, Area-IDE, Area-Compilers
