### ISSUE TITLE
CS0165 no longer working with null propagation operator

### ISSUE THREAD

**Issue by OskarKlintrot** [dotnet/roslyn#49283] opened 2020-11-11 12:25 UTC
**Version Used**: .NET 5, Visual Studio 16.8 (not sure what the exact Roslyn-version is, sorry)

**Steps to Reproduce**:

```csharp
public sealed class HttpClientAuthorizationDelegatingHandler : DelegatingHandler
{
	private readonly IHttpContextAccessor? _httpContextAccessor;

	public HttpClientAuthorizationDelegatingHandler(IHttpContextAccessor? httpContextAccessor = null)
	{
		_httpContextAccessor = httpContextAccessor;
	}

	protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		if (_httpContextAccessor?.HttpContext?.Request.Headers.TryGetValue("Authorization", out var authHeader) == true)
		{
			var auth = authHeader.ToString().Split(' '); // This compiles in .NET Core 3.1.9 but generates CS0165 in .NET 5.0.0

			// Yada yada yada
		}

		return base.SendAsync(request, cancellationToken);
	}
}
```

Changing the if-statement to this will make it compile in .NET 5:

```csharp
_httpContextAccessor is not null
&& _httpContextAccessor.HttpContext is not null
&& _httpContextAccessor.HttpContext.Request.Headers.TryGetValue("Authorization", out var authHeader)
```

**Expected Behavior**:

Compiles just as in .NET 3.1.9

**Actual Behavior**:

Generates CS0165

**Comment by huoyaoyuan** [comment] 2020-11-11 13:59
Have you tried changing `== true` to `?? false`?
I'm not sure what the exact behavior of nullable boolean conditional analysis, but remember that it has been mentioned several times.

**Comment by OskarKlintrot** [comment] 2020-11-11 14:02
@huoyaoyuan Now I tried `_httpContextAccessor?.HttpContext?.Request.Headers.TryGetValue("Authorization", out var authHeader) ?? false` but I get the same error. Or warning, I realized I have Treat Warnings As Errors turned on.

**Comment by huoyaoyuan** [comment] 2020-11-11 14:06
> Or warning

Analysis of definitive assignment generates error anyway.

**Comment by RikkiGibson** [comment] 2020-11-18 00:28
It's not expected that variables assigned on the right side of a `?.` are definitely assigned outside of the `?.`.

https://github.com/dotnet/csharplang/discussions/801

If you could provide a sample project where it compiles successfully in .NET Core 3 with an `if (obj?.M(out var x) == true) { x.M(); }` type scenario, but fails to compile in .NET 5, that would be really helpful. (including a global.json in the project would help to pin down the exact SDK version where this used to work)

**Comment by jaredpar** [comment] 2020-11-24 17:43
Closing ashe expectation is that this should never have worked (by design). There are efforts to make this work though but they won't come out until at least post-C# 9.

**Closed by jaredpar** 2020-11-24 17:43 UTC
Labels: Area-Compilers, Bug, Regression, untriaged
