### ISSUE TITLE
C# compiler should report CS0165 and the correct identifier when returning an uninitialized struct captured in a closure of a local method

### ISSUE THREAD

**Issue by kswoll** [dotnet/roslyn#22904] opened 2017-10-29 20:51 UTC
**Version Used**: 
Visual Studio 15.4.1

**Steps to Reproduce**:

Try to compile this code:
```
Struct M() 
{
	Struct s;
	
	Struct Return()
	{
		return s;
	}

	try
	{
		s = new Struct();
		return Return();
	}
	catch (Exception)
	{
		return Return();
	}
}

struct Struct
{
	TimeSpan timeSpan;
}
```

**Expected Behavior**:
For the compiler to report:

> CS0165 Use of possibly unassigned variable `s`

Identifying the `return Return();` line inside the `catch` block.

**Actual Behavior**:

The compiler reports:

> CS0170 Use of possibly unassigned field `_ticks`

I believe the current behavior is a bug as the error message is very confusing since I didn't have any field `_ticks` in my code.

**Comment by jcouv** [comment] 2017-10-31 02:14
This is very strange indeed. [Repro link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACgjYEBXAYxgwGUZyqiBvIgSABUBLMOGgBwgA7DDG68BggoQwyMRWbXqVqAWQAUASjmFWLHazoNqUKazYGlVDACU4MMgkGbze1m5QB2DCfMBfIub0AJ4u5qxQGAC8GIJwAO6KRpqm7l629o7JfuYUEDAUABYYagCiAB4UcHyiAPaCGqH6rJ42dg5OGin+Ot2+QA==).

```C#
using System;

struct Struct
{
	TimeSpan timeSpan;
    
    Struct M() 
	{
		Struct s;
	
		Struct Return()
		{
			return s;
		}

		try
		{
			s = new Struct();
			return Return();
		}
		catch (Exception)
		{
			return Return(); // error CS0170: Use of possibly unassigned field '_ticks'
		}
	}
}
```

**Comment by jcouv** [comment] 2017-10-31 02:14
@VSadov Does this issue ring a bell by any chance?

**Comment by TessenR** [comment] 2017-10-31 11:26
@jcouv Take a look at https://github.com/dotnet/roslyn/issues/14097. I believe that this is a consequence of tracking structs piecewise. Technically the error is correct as you have a single unassigned field `_ticks` nested in `timeSpan` field. The message could be better for usages which don't have a single assigned field though.

**Comment by VSadov** [comment] 2017-11-07 19:30
Looks like this is a scenario specific to local functions. Normally we would give an error on the whole struct if none of the fields is assigned.

**Comment by agocke** [comment] 2017-11-07 20:02
Actually, this is a duplicate of https://github.com/dotnet/roslyn/issues/13103. Closing as duplicate.

**Closed by agocke** 2017-11-07 20:02 UTC
Labels: Area-Compilers
