### ISSUE TITLE
[Bug]: Renaming `record` property symbol from `record` definition does not apply refactor to property pattern expressions

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#70917] opened 2023-11-21 16:03 UTC
### Version Used

* Compiler version: '4.9.0-1.23530.4 (79d1884d)'
* VSCode: 1.84.2, 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, x64
* C# extension: v2.10.28, C# Dev Kit extension: v1.1.12

### Steps to Reproduce

1. Open or create any C# project.
2. Create a `record` and create a property pattern on any of its properties;
    ```cs
    R? r = default;
    _ = r is { Foo: _ };

    record R(string? Foo);
    ```
3. Select the `Foo` symbol *in the `record` definition* and attempt to rename it.

### Expected Behavior

The appearance of `Foo` in the property pattern is also renamed.

### Actual Behavior

The appearance of `Foo` in the property pattern is not renamed, resulting in `CS0117` ('R' does not contain a definition for 'Foo').

### Additional Information

The behavior is correct for regular `class` properties.

**Comment by 333fred** [comment] 2023-11-21 23:40
Duplicate of https://github.com/dotnet/roslyn/issues/44560.

**Closed by 333fred** 2023-11-21 23:40 UTC
Labels: Area-Compilers, untriaged
