### ISSUE TITLE
Go to implementation command, should view open source code

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/roslyn#24559] opened 2018-01-31 13:05 UTC
**Version Used**: 
VS Community 15.5.1

**Steps to Reproduce**:
VS code editor has a "Go to implementation" context menu command. I suggest you allow this command to view the open source code of the requested Item. I need to look at the source code frequently, when documentations are poor to understand what is going on. The viewed source code should appear in VS as a code page, and contain a link to the gethub issues page to report any problems or suggestions.

**Expected Behavior**:
View the open source code.

**Actual Behavior**:
This sympole has no implementaions

Edit:
I'm talking about all. Net open source here in github. I was dealing with the Vector<T> class. Documentsion is poor, and trying to open the html page for vector.cs here in github was a nightmare because it's huge. There is no link to download the source code of one class, or even a namespace. I only can download the CoreFX projec! So, I thought what if Vs.net code editor can browse to it directly, but it can't. This samll feather can integrate open source projects with Vs.net, encouraging developers to participate.

Github can provide a search request url that accepts the full name of a class and returns the link to opebn source file containing it. This way Vs.net code editor can download the requested file and view it, eather in design mode, or in debugging mode. It will be nice if you give us the ability to choose to trace the execution of this source code or just step over it. Also, the code page that results from the "Go to definition" command can have a "goto implementation" command to vieew the source code from there.

**Comment by CyrusNajmabadi** [comment] 2018-02-02 01:03
>  I suggest you allow this command to view the open source code of the requested Item

This is how the feature works :)

> This sympole has no implementaions

That's because we couldn't find any implementations.  If we can't find any implementations there's no "source code of the requested item" we could "open" for you.

**Comment by jmarolf** [comment] 2018-02-02 02:53
@MohammadHamdyGhanem I assume you want us to decompile the source if there is none to navigate to?

**Comment by jcouv** [comment] 2018-02-02 06:07
I suspect the suggestion is that GoToImplementation should download the open-source code (from github or elsewhere on the web, determined somehow) and open that.
For example, if you use NewtonSoft's Json.NET as a nuget package, actual source (rather than decompiled source) should be opened when you invoke GoToImplementation.

I wonder if this is something that package/library authors can already achieve, either with source link or embedded source. It's possible that source link works when debugging, but not when simply editing.

**Comment by MohammadHamdyGhanem** [comment] 2018-02-02 10:21
Sorry if I was not clear. @jcouv made it crystal clear. I'm talking about all. Net open source here in github. I was dealing with the Vector<T> class. Documentsion is poor, and trying to open the html page for vector.cs here in github was a nightmare because it's huge. There is no link to download the source code of one class, or even a namespace. I only can download the CoreFX projec! So, I thought what if Vs.net code editor can browse to it directly, but it can't. This samll feather can integrate open source projects with Vs.net, encouraging developers to participate.

**Comment by MohammadHamdyGhanem** [comment] 2018-02-02 10:42
> I wonder if this is something that package/library authors can already achieve, either with source link or embedded source. It's possible that source link works when debugging, but not when simply editing.

Github can provide a search request url that accepts the full name of a class and returns the link to opebn source file containing it. This way Vs.net code editor can download the requested file and view it, eather in design mode, or in debugging mode. It will be nice if you give us the ability to choose to trace the execution of this source code or just step over it. Also, the code page that results from the "Go to definition" command can have a "goto implementation" command to vieew the source code from there.

**Comment by MohammadHamdyGhanem** [comment] 2019-02-08 05:52
@CyrusNajmabadi @jmarolf @jcouv @jinujoseph 
Now that MS owns Github, it is easy to implement this command, and make it easier for us to jumb to the source code of any built-in class. Please do it.

**Comment by CyrusNajmabadi** [comment] 2019-02-08 06:47
@MohammadHamdyGhanem I don't see what difference it makes if MS owns Github.

**Comment by ufcpp** [comment] 2019-02-08 06:52
[SourceLink](https://github.com/dotnet/sourcelink)?

**Comment by jinujoseph** [comment] 2019-02-08 07:23
cc @tmat

**Comment by jcouv** [comment] 2019-02-08 09:00
Yes, this should work with SourceLink now. This should be done by individual package owners.

**Comment by MohammadHamdyGhanem** [comment] 2019-02-08 10:35
@CyrusNajmabadi 
You didn't get my idea till now. Suppose I'm using System.Math.Round() and want to look to its source code. Instead of searching githup, I want to right-click the Round Method in my code, and click Go to Implementation to open the source code dirctly in a new tab in Vs.net,  have all the editor support and tool tips, even set break points! When I first asked for it, maybe it was difficult to get support from githup, but now MS can do any necessary changes to github it self to make it easy to send a reguest with just a full qualified method name to navigate directly to its source without making any change in the. Net source code itself.

**Comment by sharwell** [comment] 2019-02-08 15:39
Duplicate of #24349

**Closed by sharwell** 2019-02-08 15:39 UTC
Labels: Area-IDE, Feature Request

**Comment by MohammadHamdyGhanem** [comment] 2019-02-08 16:29
@sharwell
This is different. #24349 wants to decompile the assebly, and I want to get the code from Github source code.

**Comment by sharwell** [comment] 2019-02-08 18:54
@MohammadHamdyGhanem Prior to attempting to decompile, that issue says we should attempt to locate and use the original source code when possible. This includes but isn't limited to sources linked to GitHub.

**Comment by jmarolf** [comment] 2019-02-09 00:51
@MohammadHamdyGhanem 	see [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) and [here](https://github.com/ctaggart/SourceLink).  I believe what you want is for all the .NET assemblies that Microsoft ships to support SourceLink.  @tmat 	I believe SourceLink is used automatically now for all .NET Core builds correct?

**Comment by tmat** [comment] 2019-02-09 00:58
Yes.

**Comment by tmat** [comment] 2019-02-09 00:59
BTW, corrected Source Link link in your comment to: http://github.com/dotnet/sourcelink

**Comment by sharwell** [comment] 2019-02-09 04:18
@jmarolf Note that SourceLink *only* supports debugging scenarios. It doesn't help the normal editing experience scenarios suggested in this issue at all.

**Comment by tmat** [comment] 2019-02-09 16:24
@sharwell Currently. There is no reason it couldn't be used outside of debugging session.
