### ISSUE TITLE
Don't build doc-only changes

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#50261] opened 2021-01-05 19:56 UTC
I feel like this is a dupe of something but just can't find the original if it exists. @jmarolf or @Youssef1313 may know.

I think we can without too much difficulty write a small task which executes on PR runs of roslyn-ci. It would work by:

1. Getting the list of files changed in the latest commit from git. This has all the files changed in the PR since it is simply a merge commit of the PR changes into the base branch.
2. Verifying whether any of the files are not contained in our "exception" list, which may for example include `.md` files, files under `docs/` folder, etc.
3. If all the files are contained in the exception list, i.e. the changes are documentation-only, we instantly pass the build and set some kind of variable in the pipeline run which allows us to just skip the subsequent test jobs.

**Comment by Youssef1313** [comment] 2021-01-05 20:13
I feel like this is a dupe of something but just can't find the original if it exists.

They are #46504 and #46590

**Closed** 2024-05-23 18:02 UTC
Labels: Area-Infrastructure, Contributor Pain
