### ISSUE TITLE
No intellisense after using typeof(T) in a Select statement

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#4918] opened 2015-09-01 17:22 UTC
__Steps to reproduce__
1. Copy code below:
2. Expected that the next line intellisense's suggests more LINQ operations, it does not happen in VS 2015.
3. Pressing F12 on GetValue crashes VS too.

```C#
using System.Linq;
using System.Text;

public static class LazyToStringExtension
{
    public static string LazyToString<T>(this T obj) where T : class
    {
        StringBuilder sb = new StringBuilder();
        typeof(T)
            .GetProperties(System.Reflection.BindingFlags.Public)
            .Select(x => x.GetValue(obj))
            .
    }
}
```

Internal bug: 1207218

_Comment in Bug_
>It seems that there is some problem inferring the type of the Select after a typeof.  Hovering over GetValue doesn't show anything, select doesn't have it's return type inferred, etc.
> If I extract a local for the typeof(T), then this works as expected.

**Comment by dpoeschl** [comment] 2015-09-01 17:58
I don't think GTD is causing the crash. When I successfully invoke GTD on ```GetValue```, it just says it cannot navigate to the symbol. Sometimes, however, I click on ```GetValue``` in preparation to GTD, but before I get the chance, VS crashes with this:

```   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.AbstractDocumentHighlightsService.<GetTagsForReferencedSymbolAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.<ProduceTagsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__81.MoveNext()
```

(Also, updated the repro text to include usings. :smile:)

**Comment by balajikris** [comment] 2015-09-02 01:27
`.Select(x => x.$$GetValue(obj))` : crash in HR happens sometimes with caret as shown.

I feel that the crash in HR, the gracefully handled failure in GTD stems from the original root issue that we encounter a problem in inferring type of select.

**Highlight Refs** code could also do better error handling here.. Replicated from [AbstractDocumentHighlightService](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/ReferenceHighlighting/AbstractDocumentHighlightsService.cs,25)

we call `FindSymbolAtPosition` and return if symbol is null. If not, we call `GetSymbolToSearchAsync` and proceed to create tags, `GetTagsForReferencedSymbolAsync` which asserts the symbol is not null.. But `GetSymbolToSearchAsync` could return `null` too and we should check for `null` again. For some reason `currentSemanticModel == semanticModel` was false at `GetSymbolToSearchAsync`
 
~~~C#
           var symbol = SymbolFinder.FindSymbolAtPosition(semanticModel, position, solution.Workspace, cancellationToken: cancellationToken);
            if (symbol == null)
            {
                return SpecializedCollections.EmptyEnumerable<DocumentHighlights>();
            }
 
            symbol = await GetSymbolToSearchAsync(document, position, semanticModel, symbol, cancellationToken).ConfigureAwait(false);
 
            // Get unique tags for referenced symbols
            return await GetTagsForReferencedSymbolAsync(symbol, ImmutableHashSet.CreateRange(documentsToSearch), solution, cancellationToken).ConfigureAwait(false);
        }
~~~

**Comment by balajikris** [comment] 2015-09-02 01:35
`.Select(x$$ => x.GetValue(obj))` : with caret as shown, we hit another Assert.

Debug.Assert(this.GetMemberModel(lambda) == null, "Did not find a unique LambdaSymbol for lambda in member.");
   
 ~~~	

Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaParameterSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax parameter, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax lambda, System.Threading.CancellationToken cancellationToken) Line 598	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaParameterSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax parameter, System.Threading.CancellationToken cancellationToken) Line 558	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax declarationSyntax, System.Threading.CancellationToken cancellationToken) Line 540	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax declarationSyntax, System.Threading.CancellationToken cancellationToken) Line 1813	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 4469	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetDeclaredSymbolForNode(Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 358	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.ModelExtensions.GetDeclaredSymbol(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 135	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService.GetDeclaredSymbol.AnonymousMethod__0(Microsoft.CodeAnalysis.SyntaxNode node) Line 130	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.CodeAnalysis.SyntaxNode, <>f__AnonymousType3<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.ISymbol>>.MoveNext() Line 285	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<<>f__AnonymousType3<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.ISymbol>, Microsoft.CodeAnalysis.ISymbol>.MoveNext() Line 282	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.CodeAnalysis.ISymbol>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> source) Line 950	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService.GetDeclaredSymbol(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxToken token, System.Threading.CancellationToken cancellationToken) Line 134	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSymbolsEnumerable(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.LanguageServices.ISemanticFactsService semanticFacts, Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.SyntaxToken token, bool bindLiteralsToUnderlyingType, System.Threading.CancellationToken cancellationToken) Line 112	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.ISymbol>.MoveNext() Line 282	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.CodeAnalysis.ISymbol>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> source) Line 950	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSymbolAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, bool bindLiteralsToUnderlyingType, System.Threading.CancellationToken cancellationToken) Line 48	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSymbolAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, System.Threading.CancellationToken cancellationToken) Line 30	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsAsync(Microsoft.CodeAnalysis.Document document, int position, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Document> documentsToSearch, System.Threading.CancellationToken cancellationToken) Line 25	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context, Microsoft.VisualStudio.Text.SnapshotPoint position, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Document document) Line 139	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context) Line 114	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context) Line 570	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.RecomputeTagsAsync(object oldState, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>> oldTagTrees, System.Threading.CancellationToken cancellationToken) Line 553	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct) Line 294	C#

~~~

**Comment by balajikris** [comment] 2015-09-02 03:34
I have PR #4942 out which addresses my first comment:
> Highlight Refs code could also do better error handling in AbstractDocumentHighlightService

We still need to fix other issues here.

**Comment by Pilchie** [comment] 2015-09-02 14:30
Can you file separate bugs for the compiler about the root cause issues?

**Comment by balajikris** [comment] 2015-09-11 18:27
Hardened our HR code here and filed separate bugs for the compiler team for the actual underlying issue. Closing this bug.

**Closed by balajikris** 2015-09-11 18:27 UTC
Labels: Area-IDE, Bug
