### ISSUE TITLE
Word selection malfunctions in invalid suffixed numeric literals

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50380] opened 2021-01-11 18:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Word-selection-malfunctions-in-invalid-s/1292550)._

---
[severity:It bothers me. A fix would be nice]
1. Open VS and Create a new c# file
2. Fill it with this text (doesn't matter whether it's in a class and method): 2bop
3. Put the cursor after the 2
4. Hit ctrl+del (should be Edit.WordDeleteToEnd) twice and watch what happens
5. That was all normal, it was the control case
6. use this text instead: 2mop
7. Put the cursor after the 2
8. Hit ctrl+del; notice "mop" isn't deleted but only m. That's because it thinks it's in the middle of the "2m" token. However, it isn't such a valid token. Well, it isn't a valid identifier either. But I expect it to be treated as nothing special. Or rather, a valid identifier-like token.
9. Repeat the experiment with a2mop. This works as expected since it doesn't look like a number.
10. Repeat the experiment with "2mop". This works as expected for obvious reasons.

here is a similar problem. Put the cursor at the start of these and hit ctrl+del
1. 3333aaaa444bbbbbb -- this is treated as two words
2. dddd3333aaaa444bbbbbb -- this is treated as one word.

I call these similar because the editor thinks a number (with garbage after it rendering it an invalid number) is two words.

You can see the problem besides using ctrl+del by double-clicking words and using ctrl+right -- the same algorithm is employed for word splitting in all cases. 

I tested this in vs2015 and the same problem was evident.

EXPECTED:
What I'm expecting here is for the logic that identifies suffixed numeric literals to require some non-alphanumeric text succeeding it

---
#### Feedback Bot on 12/20/2020, 11:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-01-12 00:17
Related to (but not duplicate of) https://github.com/dotnet/roslyn/issues/50279

**Comment by CyrusNajmabadi** [comment] 2021-01-12 00:32
Feels strange. We'd be updating the lexer to have to have this odd heuristic in the case of invalid code.  Today the logic is simple, the lexer consumes as much as it can to a legal token, and repeats.  Now, it will have to revise that for certain tokens just so an editor deletion feature is happier.

**Comment by jinujoseph** [comment] 2021-01-12 20:44
Added in design review to discuss whats the desired behavior for ctrl delete

**Comment by CyrusNajmabadi** [comment] 2023-03-07 23:52
Closing out as we haven't heard about this elsewhere, and the system is behaving in what i would expect to be a normal fashion.  The jumping is between language words, which in this case happens to consider this as two words.  This is pretty clear as well with how things are squiggled:

![image](https://user-images.githubusercontent.com/4564579/223582085-5cb4fe2e-09a1-450a-9350-1ce81a0469a6.png)

I also actually think teh current behavior is *desirable* as you can jump to the problem spot and start editing there (For example, adding a space or something else).

**Closed by CyrusNajmabadi** 2023-03-07 23:52 UTC
Labels: Bug, Area-IDE, Need Design Review
