### ISSUE TITLE
VS_VERSIONINFO is corrupted if [AssemblyTrademark] is empty

### ISSUE THREAD

**Issue by martincostello** [dotnet/roslyn#7820] opened 2016-01-07 10:40 UTC
I have a custom static analyser that is used to verify compiled assemblies against various business standards (is it strong named, is the Authenticode signature valid, etc.), and part of the analyser includes reading the `VS_VERSIONINFO` data out of the portable executable to check the Win32 file information is correct.

I've noticed that if the `[AssemblyTrademark]` attribute is empty (i.e. `[assembly: AssemblyTrademark("")]`), the `LegalTrademarks` value returns garbage, which then in turn breaks the alignment of values beyond it in the structure, causing more garbage values and the reading of the structure to terminate early.

Below is the expected information that should be read from the binary compiled from [this AppVeyor build](https://ci.appveyor.com/project/experiandataquality/swashbuckle) represented as an `IDictionary<String, string>` output to the Visual Studio Immediate Window.

**Expected Result**:

```
Count = 11
    [0]: {[Comments, An Experian Data Quality-branded wrapper on top of Swashbuckle.]}
    [1]: {[CompanyName, Experian Data Quality]}
    [2]: {[FileDescription, Experian.DataQuality.Swashbuckle]}
    [3]: {[FileVersion, 1.0.0.0]}
    [4]: {[InternalName, Experian.DataQuality.Swashbuckle.dll]}
    [5]: {[LegalCopyright, Copyright (c) Experian Ltd., 2015.]}
    [6]: {[LegalTrademarks, ]}
    [7]: {[OriginalFilename, Experian.DataQuality.Swashbuckle.dll]}
    [8]: {[ProductName, Experian.DataQuality.Swashbuckle]}
    [9]: {[ProductVersion, 1.0.0.0]}
    [10]: {[Assembly Version, 1.0.0.0]}
```

**Actual Result**:

```
Count = 9
    [0]: {[Comments, An Experian Data Quality-branded wrapper on top of Swashbuckle.]}
    [1]: {[CompanyName, Experian Data Quality]}
    [2]: {[FileDescription, Experian.DataQuality.Swashbuckle]}
    [3]: {[FileVersion, 1.0.0.0]}
    [4]: {[InternalName, Experian.DataQuality.Swashbuckle.dll]}
    [5]: {[LegalCopyright, Copyright (c) Experian Ltd., 2015.]}
    [6]: {[LegalTrademarks, r]}
    [7]: {[riginalFilename, E]}
    [8]: {[rian.DataQuality.Swashbuckle.dll, b!ProductName
```

The same code compiled on a machine with Visual Studio 2013 (and not Visual Studio 2015) has the correct version information, so it looks like an issue with the Roslyn compiler's implementation.

I get the same problem compiling locally on a Windows 7 SP1 x64 machine, so it isn't specific to AppVeyor.

The raw bytes of the `VS_VERSIONINFO` section (at least the best that I can represent them here) are below.

From looking at the bytes, I _think_ that there's an extra null character being emitted when the value is blank.

**Expected**:

```
0035ea50h: 00 00 00 00 00 00 00 00 A4 04 34 00 00 00 56 00 ; ........¤.4...V.
0035ea60h: 53 00 5F 00 56 00 45 00 52 00 53 00 49 00 4F 00 ; S._.V.E.R.S.I.O.
0035ea70h: 4E 00 5F 00 49 00 4E 00 46 00 4F 00 00 00 00 00 ; N._.I.N.F.O.....
0035ea80h: BD 04 EF FE 00 00 01 00 00 00 01 00 00 00 00 00 ; ½.ïþ............
0035ea90h: 00 00 01 00 00 00 00 00 3F 00 00 00 00 00 00 00 ; ........?.......
0035eaa0h: 04 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 ; ................
0035eab0h: 00 00 00 00 44 00 00 00 01 00 56 00 61 00 72 00 ; ....D.....V.a.r.
0035eac0h: 46 00 69 00 6C 00 65 00 49 00 6E 00 66 00 6F 00 ; F.i.l.e.I.n.f.o.
0035ead0h: 00 00 00 00 24 00 04 00 00 00 54 00 72 00 61 00 ; ....$.....T.r.a.
0035eae0h: 6E 00 73 00 6C 00 61 00 74 00 69 00 6F 00 6E 00 ; n.s.l.a.t.i.o.n.
0035eaf0h: 00 00 00 00 00 00 B0 04 04 04 00 00 01 00 53 00 ; ......°.......S.
0035eb00h: 74 00 72 00 69 00 6E 00 67 00 46 00 69 00 6C 00 ; t.r.i.n.g.F.i.l.
0035eb10h: 65 00 49 00 6E 00 66 00 6F 00 00 00 E0 03 00 00 ; e.I.n.f.o...à...
0035eb20h: 01 00 30 00 30 00 30 00 30 00 30 00 34 00 62 00 ; ..0.0.0.0.0.4.b.
0035eb30h: 30 00 00 00 98 00 40 00 01 00 43 00 6F 00 6D 00 ; 0...˜.@...C.o.m.
0035eb40h: 6D 00 65 00 6E 00 74 00 73 00 00 00 41 00 6E 00 ; m.e.n.t.s...A.n.
0035eb50h: 20 00 45 00 78 00 70 00 65 00 72 00 69 00 61 00 ;  .E.x.p.e.r.i.a.
0035eb60h: 6E 00 20 00 44 00 61 00 74 00 61 00 20 00 51 00 ; n. .D.a.t.a. .Q.
0035eb70h: 75 00 61 00 6C 00 69 00 74 00 79 00 2D 00 62 00 ; u.a.l.i.t.y.-.b.
0035eb80h: 72 00 61 00 6E 00 64 00 65 00 64 00 20 00 77 00 ; r.a.n.d.e.d. .w.
0035eb90h: 72 00 61 00 70 00 70 00 65 00 72 00 20 00 6F 00 ; r.a.p.p.e.r. .o.
0035eba0h: 6E 00 20 00 74 00 6F 00 70 00 20 00 6F 00 66 00 ; n. .t.o.p. .o.f.
0035ebb0h: 20 00 53 00 77 00 61 00 73 00 68 00 62 00 75 00 ;  .S.w.a.s.h.b.u.
0035ebc0h: 63 00 6B 00 6C 00 65 00 2E 00 00 00 4C 00 16 00 ; c.k.l.e.....L...
0035ebd0h: 01 00 43 00 6F 00 6D 00 70 00 61 00 6E 00 79 00 ; ..C.o.m.p.a.n.y.
0035ebe0h: 4E 00 61 00 6D 00 65 00 00 00 00 00 45 00 78 00 ; N.a.m.e.....E.x.
0035ebf0h: 70 00 65 00 72 00 69 00 61 00 6E 00 20 00 44 00 ; p.e.r.i.a.n. .D.
0035ec00h: 61 00 74 00 61 00 20 00 51 00 75 00 61 00 6C 00 ; a.t.a. .Q.u.a.l.
0035ec10h: 69 00 74 00 79 00 00 00 6A 00 21 00 01 00 46 00 ; i.t.y...j.!...F.
0035ec20h: 69 00 6C 00 65 00 44 00 65 00 73 00 63 00 72 00 ; i.l.e.D.e.s.c.r.
0035ec30h: 69 00 70 00 74 00 69 00 6F 00 6E 00 00 00 00 00 ; i.p.t.i.o.n.....
0035ec40h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035ec50h: 2E 00 44 00 61 00 74 00 61 00 51 00 75 00 61 00 ; ..D.a.t.a.Q.u.a.
0035ec60h: 6C 00 69 00 74 00 79 00 2E 00 53 00 77 00 61 00 ; l.i.t.y...S.w.a.
0035ec70h: 73 00 68 00 62 00 75 00 63 00 6B 00 6C 00 65 00 ; s.h.b.u.c.k.l.e.
0035ec80h: 00 00 00 00 30 00 08 00 01 00 46 00 69 00 6C 00 ; ....0.....F.i.l.
0035ec90h: 65 00 56 00 65 00 72 00 73 00 69 00 6F 00 6E 00 ; e.V.e.r.s.i.o.n.
0035eca0h: 00 00 00 00 31 00 2E 00 30 00 2E 00 30 00 2E 00 ; ....1...0...0...
0035ecb0h: 30 00 00 00 6A 00 25 00 01 00 49 00 6E 00 74 00 ; 0...j.%...I.n.t.
0035ecc0h: 65 00 72 00 6E 00 61 00 6C 00 4E 00 61 00 6D 00 ; e.r.n.a.l.N.a.m.
0035ecd0h: 65 00 00 00 45 00 78 00 70 00 65 00 72 00 69 00 ; e...E.x.p.e.r.i.
0035ece0h: 61 00 6E 00 2E 00 44 00 61 00 74 00 61 00 51 00 ; a.n...D.a.t.a.Q.
0035ecf0h: 75 00 61 00 6C 00 69 00 74 00 79 00 2E 00 53 00 ; u.a.l.i.t.y...S.
0035ed00h: 77 00 61 00 73 00 68 00 62 00 75 00 63 00 6B 00 ; w.a.s.h.b.u.c.k.
0035ed10h: 6C 00 65 00 2E 00 64 00 6C 00 6C 00 00 00 00 00 ; l.e...d.l.l.....
0035ed20h: 6A 00 23 00 01 00 4C 00 65 00 67 00 61 00 6C 00 ; j.#...L.e.g.a.l.
0035ed30h: 43 00 6F 00 70 00 79 00 72 00 69 00 67 00 68 00 ; C.o.p.y.r.i.g.h.
0035ed40h: 74 00 00 00 43 00 6F 00 70 00 79 00 72 00 69 00 ; t...C.o.p.y.r.i.
0035ed50h: 67 00 68 00 74 00 20 00 28 00 63 00 29 00 20 00 ; g.h.t. .(.c.). .
0035ed60h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035ed70h: 20 00 4C 00 74 00 64 00 2E 00 2C 00 20 00 32 00 ;  .L.t.d...,. .2.
0035ed80h: 30 00 31 00 35 00 2E 00 00 00 00 00 2C 00 02 00 ; 0.1.5.......,...
0035ed90h: 01 00 4C 00 65 00 67 00 61 00 6C 00 54 00 72 00 ; ..L.e.g.a.l.T.r.
0035eda0h: 61 00 64 00 65 00 6D 00 61 00 72 00 6B 00 73 00 ; a.d.e.m.a.r.k.s.
0035edb0h: 00 00 00 00 20 00 00 00 72 00 25 00 01 00 4F 00 ; .... ...r.%...O.
0035edc0h: 72 00 69 00 67 00 69 00 6E 00 61 00 6C 00 46 00 ; r.i.g.i.n.a.l.F.
0035edd0h: 69 00 6C 00 65 00 6E 00 61 00 6D 00 65 00 00 00 ; i.l.e.n.a.m.e...
0035ede0h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035edf0h: 2E 00 44 00 61 00 74 00 61 00 51 00 75 00 61 00 ; ..D.a.t.a.Q.u.a.
0035ee00h: 6C 00 69 00 74 00 79 00 2E 00 53 00 77 00 61 00 ; l.i.t.y...S.w.a.
0035ee10h: 73 00 68 00 62 00 75 00 63 00 6B 00 6C 00 65 00 ; s.h.b.u.c.k.l.e.
0035ee20h: 2E 00 64 00 6C 00 6C 00 00 00 00 00 62 00 21 00 ; ..d.l.l.....b.!.
0035ee30h: 01 00 50 00 72 00 6F 00 64 00 75 00 63 00 74 00 ; ..P.r.o.d.u.c.t.
0035ee40h: 4E 00 61 00 6D 00 65 00 00 00 00 00 45 00 78 00 ; N.a.m.e.....E.x.
0035ee50h: 70 00 65 00 72 00 69 00 61 00 6E 00 2E 00 44 00 ; p.e.r.i.a.n...D.
0035ee60h: 61 00 74 00 61 00 51 00 75 00 61 00 6C 00 69 00 ; a.t.a.Q.u.a.l.i.
0035ee70h: 74 00 79 00 2E 00 53 00 77 00 61 00 73 00 68 00 ; t.y...S.w.a.s.h.
0035ee80h: 62 00 75 00 63 00 6B 00 6C 00 65 00 00 00 00 00 ; b.u.c.k.l.e.....
0035ee90h: 34 00 08 00 01 00 50 00 72 00 6F 00 64 00 75 00 ; 4.....P.r.o.d.u.
0035eea0h: 63 00 74 00 56 00 65 00 72 00 73 00 69 00 6F 00 ; c.t.V.e.r.s.i.o.
0035eeb0h: 6E 00 00 00 31 00 2E 00 30 00 2E 00 30 00 2E 00 ; n...1...0...0...
0035eec0h: 30 00 00 00 38 00 08 00 01 00 41 00 73 00 73 00 ; 0...8.....A.s.s.
0035eed0h: 65 00 6D 00 62 00 6C 00 79 00 20 00 56 00 65 00 ; e.m.b.l.y. .V.e.
0035eee0h: 72 00 73 00 69 00 6F 00 6E 00 00 00 31 00 2E 00 ; r.s.i.o.n...1...
0035eef0h: 30 00 2E 00 30 00 2E 00 30 00 00 00 00 00 00 00 ; 0...0...0.......
```

**Actual**:

```
0035e850h: 00 00 00 00 00 00 00 00 A8 04 34 00 00 00 56 00 ; ........¨.4...V.
0035e860h: 53 00 5F 00 56 00 45 00 52 00 53 00 49 00 4F 00 ; S._.V.E.R.S.I.O.
0035e870h: 4E 00 5F 00 49 00 4E 00 46 00 4F 00 00 00 00 00 ; N._.I.N.F.O.....
0035e880h: BD 04 EF FE 00 00 01 00 00 00 01 00 00 00 1E 00 ; ½.ïþ............
0035e890h: 00 00 01 00 00 00 1E 00 3F 00 00 00 00 00 00 00 ; ........?.......
0035e8a0h: 04 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 ; ................
0035e8b0h: 00 00 00 00 44 00 00 00 01 00 56 00 61 00 72 00 ; ....D.....V.a.r.
0035e8c0h: 46 00 69 00 6C 00 65 00 49 00 6E 00 66 00 6F 00 ; F.i.l.e.I.n.f.o.
0035e8d0h: 00 00 00 00 24 00 04 00 00 00 54 00 72 00 61 00 ; ....$.....T.r.a.
0035e8e0h: 6E 00 73 00 6C 00 61 00 74 00 69 00 6F 00 6E 00 ; n.s.l.a.t.i.o.n.
0035e8f0h: 00 00 00 00 00 00 B0 04 08 04 00 00 01 00 53 00 ; ......°.......S.
0035e900h: 74 00 72 00 69 00 6E 00 67 00 46 00 69 00 6C 00 ; t.r.i.n.g.F.i.l.
0035e910h: 65 00 49 00 6E 00 66 00 6F 00 00 00 E4 03 00 00 ; e.I.n.f.o...ä...
0035e920h: 01 00 30 00 30 00 30 00 30 00 30 00 34 00 62 00 ; ..0.0.0.0.0.4.b.
0035e930h: 30 00 00 00 98 00 40 00 01 00 43 00 6F 00 6D 00 ; 0...˜.@...C.o.m.
0035e940h: 6D 00 65 00 6E 00 74 00 73 00 00 00 41 00 6E 00 ; m.e.n.t.s...A.n.
0035e950h: 20 00 45 00 78 00 70 00 65 00 72 00 69 00 61 00 ;  .E.x.p.e.r.i.a.
0035e960h: 6E 00 20 00 44 00 61 00 74 00 61 00 20 00 51 00 ; n. .D.a.t.a. .Q.
0035e970h: 75 00 61 00 6C 00 69 00 74 00 79 00 2D 00 62 00 ; u.a.l.i.t.y.-.b.
0035e980h: 72 00 61 00 6E 00 64 00 65 00 64 00 20 00 77 00 ; r.a.n.d.e.d. .w.
0035e990h: 72 00 61 00 70 00 70 00 65 00 72 00 20 00 6F 00 ; r.a.p.p.e.r. .o.
0035e9a0h: 6E 00 20 00 74 00 6F 00 70 00 20 00 6F 00 66 00 ; n. .t.o.p. .o.f.
0035e9b0h: 20 00 53 00 77 00 61 00 73 00 68 00 62 00 75 00 ;  .S.w.a.s.h.b.u.
0035e9c0h: 63 00 6B 00 6C 00 65 00 2E 00 00 00 4C 00 16 00 ; c.k.l.e.....L...
0035e9d0h: 01 00 43 00 6F 00 6D 00 70 00 61 00 6E 00 79 00 ; ..C.o.m.p.a.n.y.
0035e9e0h: 4E 00 61 00 6D 00 65 00 00 00 00 00 45 00 78 00 ; N.a.m.e.....E.x.
0035e9f0h: 70 00 65 00 72 00 69 00 61 00 6E 00 20 00 44 00 ; p.e.r.i.a.n. .D.
0035ea00h: 61 00 74 00 61 00 20 00 51 00 75 00 61 00 6C 00 ; a.t.a. .Q.u.a.l.
0035ea10h: 69 00 74 00 79 00 00 00 6A 00 21 00 01 00 46 00 ; i.t.y...j.!...F.
0035ea20h: 69 00 6C 00 65 00 44 00 65 00 73 00 63 00 72 00 ; i.l.e.D.e.s.c.r.
0035ea30h: 69 00 70 00 74 00 69 00 6F 00 6E 00 00 00 00 00 ; i.p.t.i.o.n.....
0035ea40h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035ea50h: 2E 00 44 00 61 00 74 00 61 00 51 00 75 00 61 00 ; ..D.a.t.a.Q.u.a.
0035ea60h: 6C 00 69 00 74 00 79 00 2E 00 53 00 77 00 61 00 ; l.i.t.y...S.w.a.
0035ea70h: 73 00 68 00 62 00 75 00 63 00 6B 00 6C 00 65 00 ; s.h.b.u.c.k.l.e.
0035ea80h: 00 00 00 00 32 00 09 00 01 00 46 00 69 00 6C 00 ; ....2.....F.i.l.
0035ea90h: 65 00 56 00 65 00 72 00 73 00 69 00 6F 00 6E 00 ; e.V.e.r.s.i.o.n.
0035eaa0h: 00 00 00 00 31 00 2E 00 30 00 2E 00 33 00 30 00 ; ....1...0...3.0.
0035eab0h: 2E 00 30 00 00 00 00 00 6A 00 25 00 01 00 49 00 ; ..0.....j.%...I.
0035eac0h: 6E 00 74 00 65 00 72 00 6E 00 61 00 6C 00 4E 00 ; n.t.e.r.n.a.l.N.
0035ead0h: 61 00 6D 00 65 00 00 00 45 00 78 00 70 00 65 00 ; a.m.e...E.x.p.e.
0035eae0h: 72 00 69 00 61 00 6E 00 2E 00 44 00 61 00 74 00 ; r.i.a.n...D.a.t.
0035eaf0h: 61 00 51 00 75 00 61 00 6C 00 69 00 74 00 79 00 ; a.Q.u.a.l.i.t.y.
0035eb00h: 2E 00 53 00 77 00 61 00 73 00 68 00 62 00 75 00 ; ..S.w.a.s.h.b.u.
0035eb10h: 63 00 6B 00 6C 00 65 00 2E 00 64 00 6C 00 6C 00 ; c.k.l.e...d.l.l.
0035eb20h: 00 00 00 00 66 00 21 00 01 00 4C 00 65 00 67 00 ; ....f.!...L.e.g.
0035eb30h: 61 00 6C 00 43 00 6F 00 70 00 79 00 72 00 69 00 ; a.l.C.o.p.y.r.i.
0035eb40h: 67 00 68 00 74 00 00 00 43 00 6F 00 70 00 79 00 ; g.h.t...C.o.p.y.
0035eb50h: 72 00 69 00 67 00 68 00 74 00 20 00 A9 00 20 00 ; r.i.g.h.t. .©. .
0035eb60h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035eb70h: 20 00 4C 00 74 00 64 00 2E 00 2C 00 20 00 32 00 ;  .L.t.d...,. .2.
0035eb80h: 30 00 31 00 35 00 2E 00 00 00 00 00 2A 00 01 00 ; 0.1.5.......*...
0035eb90h: 01 00 4C 00 65 00 67 00 61 00 6C 00 54 00 72 00 ; ..L.e.g.a.l.T.r.
0035eba0h: 61 00 64 00 65 00 6D 00 61 00 72 00 6B 00 73 00 ; a.d.e.m.a.r.k.s.
0035ebb0h: 00 00 00 00 00 00 00 00 72 00 25 00 01 00 4F 00 ; ........r.%...O.
0035ebc0h: 72 00 69 00 67 00 69 00 6E 00 61 00 6C 00 46 00 ; r.i.g.i.n.a.l.F.
0035ebd0h: 69 00 6C 00 65 00 6E 00 61 00 6D 00 65 00 00 00 ; i.l.e.n.a.m.e...
0035ebe0h: 45 00 78 00 70 00 65 00 72 00 69 00 61 00 6E 00 ; E.x.p.e.r.i.a.n.
0035ebf0h: 2E 00 44 00 61 00 74 00 61 00 51 00 75 00 61 00 ; ..D.a.t.a.Q.u.a.
0035ec00h: 6C 00 69 00 74 00 79 00 2E 00 53 00 77 00 61 00 ; l.i.t.y...S.w.a.
0035ec10h: 73 00 68 00 62 00 75 00 63 00 6B 00 6C 00 65 00 ; s.h.b.u.c.k.l.e.
0035ec20h: 2E 00 64 00 6C 00 6C 00 00 00 00 00 62 00 21 00 ; ..d.l.l.....b.!.
0035ec30h: 01 00 50 00 72 00 6F 00 64 00 75 00 63 00 74 00 ; ..P.r.o.d.u.c.t.
0035ec40h: 4E 00 61 00 6D 00 65 00 00 00 00 00 45 00 78 00 ; N.a.m.e.....E.x.
0035ec50h: 70 00 65 00 72 00 69 00 61 00 6E 00 2E 00 44 00 ; p.e.r.i.a.n...D.
0035ec60h: 61 00 74 00 61 00 51 00 75 00 61 00 6C 00 69 00 ; a.t.a.Q.u.a.l.i.
0035ec70h: 74 00 79 00 2E 00 53 00 77 00 61 00 73 00 68 00 ; t.y...S.w.a.s.h.
0035ec80h: 62 00 75 00 63 00 6B 00 6C 00 65 00 00 00 00 00 ; b.u.c.k.l.e.....
0035ec90h: 36 00 09 00 01 00 50 00 72 00 6F 00 64 00 75 00 ; 6.....P.r.o.d.u.
0035eca0h: 63 00 74 00 56 00 65 00 72 00 73 00 69 00 6F 00 ; c.t.V.e.r.s.i.o.
0035ecb0h: 6E 00 00 00 31 00 2E 00 30 00 2E 00 33 00 30 00 ; n...1...0...3.0.
0035ecc0h: 2E 00 30 00 00 00 00 00 38 00 08 00 01 00 41 00 ; ..0.....8.....A.
0035ecd0h: 73 00 73 00 65 00 6D 00 62 00 6C 00 79 00 20 00 ; s.s.e.m.b.l.y. .
0035ece0h: 56 00 65 00 72 00 73 00 69 00 6F 00 6E 00 00 00 ; V.e.r.s.i.o.n...
0035ecf0h: 31 00 2E 00 30 00 2E 00 30 00 2E 00 30 00 00 00 ; 1...0...0...0...
```

**Comment by martincostello** [comment] 2016-01-07 14:45
I've also found the same issue with ```Microsoft.QualityTools.Testing.Fakes.dll``` that ships with Visual Studio 2015 (version ```14.0.23107.0```) which has ```[assembly: AssemblyTrademark("")]``` too from inspection with .NET Reflector.

**Comment by TyOverby** [comment] 2016-12-05 22:58
@martincostello I've attempted to repro this bug with the following:

```c#
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyVersion("1.9.0")]
[assembly: System.Reflection.AssemblyProduct("My Repro Product")]
namespace N {}
```

```
csc repro.cs /target:library
```

But the dll that is produced contains no contamination.

Could you please try to repro again and see if this bug was inadvertently fixed in the meantime?

**Comment by TyOverby** [comment] 2016-12-05 23:59
branch with repro file here: https://github.com/TyOverby/roslyn/tree/7820-assembly-trademark

**Comment by martincostello** [comment] 2016-12-06 14:20
@TyOverby Yeah, I can't reproduce this anymore either. Unfortunately I no longer have access to the original project where I discovered the issue, so if there was a more complex set of criteria that caused it to manifest itself and the issue is still there I can't determine it.

**Comment by TyOverby** [comment] 2016-12-06 19:07
Since I can't really do anything else on my end, I'm going to close this until someone hits it again.  

Interestingly, there's been a unit test testing the empty string in AssemblyTrademark for a very long time. http://source.roslyn.io/#Roslyn.Compilers.CSharp.Emit.UnitTests/Attributes/AttributeTests_Assembly.cs,482

Is it possible that your compiler was pre-roslyn?

**Comment by martincostello** [comment] 2016-12-07 18:03
I might be reading it wrong, but it looks like that test is testing the attribute is emitted into the IL, not that it's in the ```VS_VERSION_INFO``` Win32 resource structure?

**Comment by TyOverby** [comment] 2016-12-08 22:44
@martincostello Looking back at your "actual" hex dump, I don't see what is wrong with the trademarks section.  At the very least, it behaves how I would expect it to.  

All that your "expected" section does is create a single-character string `" "` instead of it being empty.

Here are some annotations that I took on your "actual" hex dump.

![image](https://cloud.githubusercontent.com/assets/573215/21030565/268718a2-bd97-11e6-8933-b6f1db5cc61e.png)

**Comment by TyOverby** [comment] 2017-01-18 21:55
Closing because neither the customer nor I are able to reproduce the bug.  On top of that the actual compiler behavior appears to be within spec.

**Closed by TyOverby** 2017-01-18 21:55 UTC
Labels: Area-Compilers, Bug, Tenet-Compatibility
