### ISSUE TITLE
[API Proposal]: In-object fixed size arrays in safe context

### ISSUE THREAD

**Issue by Wojmik** [dotnet/roslyn#55772] opened 2021-08-20 21:42 UTC
### Background and motivation

In structs fixed-size buffers can be declared as part of a struct itself but it requires unsafe context and it is struct feature only. Those limitations successfully discourage almost everyone from using them, they are used almost only in interoperate with operating system or native code.
Today we have Memory&lt;T&gt; and interior pointers and we can make step further and allow declaration in-object constant-size arrays as part of the classes and structs without unsafe context. All building blocks are already in place.
Those arrays would be part of an object itself, not a reference to another object (array).
There are plenty of use cases when small fixed size arrays at the class level are needed.
For example: `"Test".AsSpan().IndexOfAny(beggingForInObjectArray)` or some small buffers on not thread safe classes - e.g. classes reading or writing something to Stream.
You can use stackalloc but it has to be zeroed (at least in safe context) or constantly initialized by the same data. You can also use ordinary array but it is another allocation and some performance penalty.

### API Proposal

```C#
namespace MyNamespace
{
  class MyClass
  {
    readonly Memory<T> InObjectArray1 = fixed T[16];
    readonly Memory<object> InObjectArray2 = fixed object[] { new object(), new object (), new object (), };
    readonly ReadOnlyMemory<char> InObjectArray3 = fixed char[] { '\"', '\r', '\n', ',', };
  }
}
```
Size of in-object array has to be compile time constant.
Readonly keyword to indicate that `InObjectArray1` can't change what is pointing to.
Can be declared as Memory&lt;T&gt; or ReadOnlyMemory&lt;T&gt;.

### API Usage

Used everywhere where ordinary Memory&lt;T&gt; or ReadOnlyMemory&lt;T&gt; can be used.
```C#
var index = "Sample text\r\nSecond line".AsSpan().IndexOfAny(InObjectArray3.Slice(1, 2));
```     

### Risks

Don't see any.

**Comment by GrabYourPitchforks** [comment] 2021-08-20 21:56
Doing this for arbitrary _T_ instead of known-unmanaged types like _byte_, _char_, etc. would require significant runtime changes. (It's the same reason you can't `stackalloc T[...]` for arbitrary _T_.)

Additionally, using `[ReadOnly]Memory` for this would be problematic due to the design of the type. But doing this for `[ReadOnly]Span` would be feasible. In fact, I believe this could be done entirely as a sleight-of-hand by the compiler.

```cs
// user writes this (looks like a field)
public class MyClass
{
    public fixed Span<byte> MyByteSpan[20];
}

// compiler actually generates this (turns into a property)
public class MyClass
{
    private _SomeCompilerGeneratedNonsense _someBackingField;

    public Span<byte> MyByteSpan => MemoryMarshal.CreateSpan(ref _someBackingField.Data, 20);

    private struct _SomeCompilerGeneratedNonsense
    {
        internal fixed byte* Data[20];
    }
}
```

**Comment by Wojmik** [comment] 2021-08-20 22:27
I'm surprised that T is so difficult. After all `fixed Memory<T> MyArray[3]` on the object level is equivalent of:
```c#
class MyClass
{
  T MyArray_0;
  T MyArray_1;
  T MyArray_2;
}
```
But even simple types would be useful.
I proposed `[ReadOnly]Memory` because I thought that `[ReadOnly]Span` cannot be part of class (anything that can live on heap).

**Comment by GrabYourPitchforks** [comment] 2021-08-20 22:35
> After all `fixed Memory<T> MyArray[3]` on the object level is equivalent of...

It's a bit more nuanced than that, especially when we start talking about how the VM lays out objects or how the GC walks objects during collections. It's probably a tractable problem, but it's something that would absolutely require support from the runtime.

> I thought that `[ReadOnly]Span` cannot be part of class

You're correct, but if you look at the "compiler actually generates this" part of my sample you'll see that there's never a span field anywhere in the class. There's a span _property_, which is totally legal.

**Comment by Wojmik** [comment] 2021-08-20 22:57
I get your point about Span. It is very clever trick by the way 😉. Sadly Span would reduce some of usability, it cannot be used with async methods like ReadAsync / WriteAsync of Stream 😟

**Comment by ufcpp** [comment] 2021-08-21 00:27
see [Fixed Sized Buffers proposal](https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/proposals/fixed-sized-buffers.md) in [https://github.com/dotnet/csharplang](csharplang)

**Comment by 333fred** [comment] 2021-08-24 21:32
This is a duplicate of the proposal ufcpp linked, which is tracked by https://github.com/dotnet/csharplang/issues/1314. Closing out.

**Closed by 333fred** 2021-08-24 21:32 UTC
Labels: Resolution-Duplicate, Area-Language Design
