### ISSUE TITLE
Classify redefined record member declarations and implicit interface implementations

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#47735] opened 2020-09-16 05:23 UTC
(moved from #46985)

There are certain members in a record that can be replaced by user code, such as

- `Equals(ContainingType)`, 
- `EqualityContract`, 
- positional record's properties, etc.

Currently there's no indication that the member correctly matched by name/signature and replaced the compiler-generated one, or otherwise it's just another member on it's own.

It's a lot like `new`/`override` but this is none of them, it merely works by matching the name and signature.

Since there is no way for compiler to report it or otherwise make it apparent I think the IDE could help here.

This also applies to implicit interface implementations. For that R# has an indicator that distinguish these 

![image](https://user-images.githubusercontent.com/3105979/93295309-f0fd2880-f801-11ea-9831-018dcc563235.png)

and a little bit of info on hover.

/cc  @CyrusNajmabadi

**Comment by sharwell** [comment] 2020-10-14 19:39
This seems to be covered by https://github.com/dotnet/roslyn/issues/32149#issuecomment-705091980

**Comment by sharwell** [comment] 2020-10-14 19:40
@alrz any objection to treating this as a duplicate of the broader request?

**Comment by alrz** [comment] 2020-10-14 19:47
That's exactly what I've been asking for but I think it wouldn't include record members. those need special treatment since they are not considered an "override" and are not part of inheritance chain.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 21:12
Closing due to lack of feedback

**Closed by CyrusNajmabadi** 2024-10-21 21:12 UTC
Labels: Area-IDE, Concept-Continuous Improvement, New Language Feature - Records
