### ISSUE TITLE
Code metrics code lens

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49579] opened 2020-11-23 23:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Code-metrics-code-lens/1264847)._

---
<p>I'd often like to see the value of a code metric, such as <strong>cyclomatic complexity</strong> or <strong>lines of code</strong> for a method <em>while I'm looking at the method</em>.</p> <p>Ideally, I'd like this information to be visible on the screen together with the code I'm looking at, for example as a <em>code lens</em> (is that the name?).</p> <p>I know that I can use the <em>Calculate Code Metrics</em> feature to calculate all the metrics for a project or the entire solution, but then I have to dig through the <em>Code Metrics Result</em> to find the method in question. That's hardly the path of last resistance if I'm already looking at the method.</p> <p>If a code lens is too much to ask for, I'd like a command or keyboard shortcut that would enable me to navigate from the method in the code editor to that method in the <em>Code Metrics Result</em> window.</p>

---
#### Martin Clausen on 11/21/2020, 06:59 AM: 

<p>This is a great idea. As this might be quite resource intensive for some codebases you should be able to switch this on/off in the right click menu/via short-cut. Some kind of "running" indicator might be good too.</p>

#### Attila Bertók on 11/22/2020, 02:53 AM: 

<p>Could an extension make this possible?</p><p>https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/CodeLensOopSample</p><p>I love the idea, and I'd be willing to look into this.</p>

#### Feedback Bot on 11/23/2020, 01:05 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-12-01 19:55
Duplicate of #39787

**Closed by sharwell** 2020-12-01 19:55 UTC
Labels: Area-IDE, Feature Request
