### ISSUE TITLE
VS crash in microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+_AddSemanticClassificationsAsync_d__5.MoveNext

### ISSUE THREAD

**Issue by ikeras** [dotnet/roslyn#4227] opened 2015-07-30 16:27 UTC
Repro:

1) type something like:
  
protected override void DisposeManagedResources()
{
  this.themeService?.ThemeChange // type this line

  base.DisposeManagedResources();
}

Result:

http://watson/BucketDetails?iBucket=128882364743&EventType=122

2453ca50 02f29ef6 microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.FailFast.OnFatalException+0x26
2453ca5c 02f26b0d microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report+0x45
2453ca70 5fb728cc microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled+0x32cebc
2453ca78 5f855b9f microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+_AddSemanticClassificationsAsync_d__5.MoveNext+0x15f
2453dbe8 5e649b87 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.GetEventSymbol+0x50c20f
2453dbfc 5e13d8b3 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.CheckEventValueKind+0x23
2453dc28 5e012669 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.CheckValueKind+0xc9
2453dc40 5e01235e microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.CheckValue+0x4e
2453dcbc 1264b5cd microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindConditionalAccessExpression+0x8d
2453dcf8 5e606d4c microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal+0x5f545c
2453dd44 5e0118c0 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression+0x20
2453dd64 5e1379ad microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindCompoundAssignment+0x5d
2453dfe8 5e011ae9 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal+0x1f9
2453e034 5e0118c0 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression+0x20
2453e054 5e0356b0 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement+0x20
2453e080 5e0327d5 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement+0x65
2453e094 5e0e99bc microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel+IncrementalBinder.BindStatement+0x3c
2453e0a8 5e0e53f0 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind+0x40
2453e0c4 5e0e9976 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind+0x26
2453e0d8 5e0e457c microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes+0x14c
2453e13c 5e0e440a microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode+0xa
2453e144 5e0e3f37 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes+0x47
2453e168 5e0e1554 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker+0x34
2453e194 5e0e0a42 microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker+0x52
2453e200 5e0dfd2b microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo+0x4b
2453e21c 5dfe254c microsoft_codeanalysis_csharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo+0x2c
2453e230 615d5afa microsoft_codeanalysis_csharp_workspaces_ni!Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax+0x3a
2453e258 615d5aa9 microsoft_codeanalysis_csharp_workspaces_ni!Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode+0x29
2453e268 5f8568ea microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+Worker.ClassifyNode+0xba
2453e2b8 5f856724 microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+Worker.ProcessNodes+0x134
2453e368 5f856541 microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+Worker.Classify+0xf1
2453e3d0 5f855b34 microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService+_AddSemanticClassificationsAsync_d__5.MoveNext+0xf4
2453e430 1fa78b2a mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Classification.AbstractClassificationService+_AddSemanticClassificationsAsync_d__5,_Microsoft.CodeAnalysis.Workspaces]]+0x42
2453e484 5f82d239 microsoft_codeanalysis_workspaces_ni!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync+0x89
2453e4fc 5f3b8ea9 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Implementation.Classification.AbstractEditorClassificationService.AddSemanticClassificationsAsync+0xc9
2453e544 5f3b8c13 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationTaggerProvider+TagProducer+_ProduceTagsAsync_d__3.MoveNext+0x243
2453e5a8 5f3b8991 mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder_1[[System.__Canon,_mscorlib]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationTaggerProvider+TagProducer+_ProduceTagsAsync_d__3,_Microsoft.CodeAnalysis.EditorFeatures]]+0x3d
2453e600 5f3b893b microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationTaggerProvider+TagProducer.ProduceTagsAsync+0x7b
2453e678 5f3ad0a6 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.AbstractSingleDocumentTagProducer_1[[System.__Canon,_mscorlib]].ProduceTagsAsync+0xa6
2453e6c4 5f3b4b09 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource_1+_RecomputeTagsAsync_d__32[[System.__Canon,_mscorlib]].MoveNext+0xb9
2453e718 5f3b4a13 mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource_1+_RecomputeTagsAsync_d__32[[System.__Canon,_mscorlib]],_Microsoft.CodeAnalysis.EditorFeatures]]+0x5f
2453e774 5f3b49a0 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource_1[[System.__Canon,_mscorlib]].RecomputeTagsAsync+0x90
2453e800 5f3c83d8 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1[[System.__Canon,_mscorlib]].__n__0+0x28
2453e828 5f3b82ab microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1+_RecomputeTagsAsync_d__5[[System.__Canon,_mscorlib]].MoveNext+0x34b
2453e974 5f3b7f27 mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1+_RecomputeTagsAsync_d__5[[System.__Canon,_mscorlib]],_Microsoft.CodeAnalysis.EditorFeatures]]+0x5f
2453e9d0 5f3b7eb5 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1[[System.__Canon,_mscorlib]].RecomputeTagsAsync+0xc5
2453eaac 5f3b7a7d microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1+_RecomputeTagsAsync_d__4[[System.__Canon,_mscorlib]].MoveNext+0x20d
2453eb84 5f3b782f mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1+_RecomputeTagsAsync_d__4[[System.__Canon,_mscorlib]],_Microsoft.CodeAnalysis.EditorFeatures]]+0x5f
2453ebe0 5f3b77bc microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource_1[[System.__Canon,_mscorlib]].RecomputeTagsAsync+0xac
2453ec94 5f3b4903 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource_1+__c__DisplayClass25_0[[System.__Canon,_mscorlib]]._RecomputeTagsForeground_b__0+0x33
2453eca4 5f3a9447 microsoft_codeanalysis_editorfeatures_ni!Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue+__c__DisplayClass11_0._EnqueueBackgroundTask_b__0+0x17
2453eca8 7159272e mscorlib_ni!System.Threading.Tasks.ContinuationResultTaskFromTask_1[[System.__Canon,_mscorlib]].InnerInvoke+0x4e
2453ecbc 715a2570 mscorlib_ni!System.Threading.Tasks.Task.Execute+0x30
2453ece0 715a29ba mscorlib_ni!System.Threading.Tasks.Task.ExecutionContextCallback+0x1a
2453ece4 7151a3e4 mscorlib_ni!System.Threading.ExecutionContext.RunInternal+0xb4
2453ed50 7151a326 mscorlib_ni!System.Threading.ExecutionContext.Run+0x16
2453ed64 715a2838 mscorlib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal+0xd8
2453edc8 715a2724 mscorlib_ni!System.Threading.Tasks.Task.ExecuteEntry+0xb4
2453edd8 715a266c mscorlib_ni!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem+0xc
2453eddc 7155f953 mscorlib_ni!System.Threading.ThreadPoolWorkQueue.Dispatch+0x153
2453ee2c 7155f7fa mscorlib_ni!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback+0xa

**Comment by jaredpar** [comment] 2015-07-31 19:48
Thanks for taking the time to file this bug! 

Looks like this is a duplicate of #4028.  Going to let that one be the primary.

**Closed by jaredpar** 2015-07-31 19:48 UTC
Labels: Area-Compilers
