### ISSUE TITLE
"async" detection refactoring bug

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#68945] opened 2023-07-09 17:53 UTC
**Version Used**: 
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.4

**Steps to Reproduce**:
Use this code:
```
namespace ConsoleApp19 {
    internal class Program {

        static Task OuterAsync() { 
            
            static Task InnerAsync() { 
                return Task.CompletedTask;
            }

            //type "async" here and InnerAsync will become async instead of OuterAsync
        
        }

    }
}
```
**Expected Behavior**:
OuterAsync should become async.

**Actual Behavior**:
InnerAsync becomes async.

![Untitled Project](https://github.com/dotnet/roslyn/assets/13609558/0205c3e5-01c8-4e6b-b33d-bffbd62b1530)

**Comment by Youssef1313** [comment] 2023-07-09 17:57
Duplicate of https://github.com/dotnet/roslyn/issues/67952

**Closed** 2023-07-11 02:10 UTC
Labels: Area-IDE, untriaged
