### ISSUE TITLE
Lightbulb quick refactor for moving strings to resources file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38268] opened 2019-08-24 00:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/400372/lightbulb-quick-refactor-for-moving-strings-to-res.html)._

---
<p>It would be super convenient to have a quick refactor to move string literals to a project's resource file (e.g. Resources.resx).</p>

---
#### Jane Wu [MSFT] on 12/6/2018, 06:15 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  You will hear from us in about a week on our next steps.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

**Comment by dpoeschl** [comment] 2020-02-13 22:24
@vatsalyaagrawal @sharwell Can we mark this as a dupe of https://github.com/dotnet/roslyn/issues/16624?

**Comment by sharwell** [comment] 2020-02-14 00:57
Duplicate of #16624

**Closed by sharwell** 2020-02-14 00:57 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review
