### ISSUE TITLE
Environment Variables inside .rsp files

### ISSUE THREAD

**Issue by LostTime76** [dotnet/roslyn#53753] opened 2021-05-28 17:19 UTC
## Background and Motivation

I have a custom scripting host scenario (.csx files) where it would be beneficial to be able to specify paths inside .rsp files that include environment variables. Right now, it does not look like this is supported. My host passes a bunch of references to the compiler before it runs the script, and I would like those references to be automatically available in intellisense for something like vscode.

Omnisharp vscode supports scripting scenarios where you can now specify a rspFilePath attribute in omnisharp.json, which basically tells it what assemblies and usings have been added to the script from the script host. When you open the script in vscode, it lists the correct intellisense given the references. However, each /r: in the .rsp file must be either a relative path or absolute path. If my assembly reference is installed to a location on the local machine which can vary by machine (and OS), hardcoding an absolute path for the reference is not an option. Instead, the user could define environment variables on their machine that could be used in the path resolution.

Imagine I have a custom script host that is installed to C:/program files/blah blah. This directory contains assemblies that are added as referenced assemblies to the script compilation before the script is run. It would be beneficial if, for example, vscode omnisharp intellisense could work and discover those references. Currently, omnisharp has added the rspFilePath attribute in omnisharp.json that allows intellisense to work for custom script runners. However, it is using the default roslyn rsp file parsing to discover the references. Environment variables in each /r: statement in the rsp file are seemingly not supported.

## Proposed API

Propose to allow a cross platform way of specifying environment variables inside .rsp files for (at least) /r: statements. I don't care about syntax or any of that, only that the feature is supported, so you guys can figure that out. Whether its $(TEST_ENV_VAR)/path or %TEST_ENV_VAR%/path makes no differences to me.

## Usage Examples

Assuming $(VAR) syntax, inside the .rsp files, allow:

/r:$(SCRIPT_HOST_INSTALL_LOC)/bin/myasm.dll
/r:"$(OTHER_VAR_HERE)/$(YET_ANOTHER_VAR)/blah blah/myasm2.dll"

## Risks

Seems like an easy feature to support, but I am in no way involved in the innards of the roslyn code base, that is built by a bajillion (probably smarter) coders than myself. Therefore, I have no reference point to state any risks or issues that may be encountered.

**Comment by jaredpar** [comment] 2021-07-13 15:24
There are existing ways to use environment variables and arguments to control how the C# compiler resolves references (`-lib` for example). They seem fairly designed for the scenario that you are describing here. Is there a reason that they don't work?

**Comment by LostTime76** [comment] 2021-07-13 16:30
In this scenario, I am using the omnisharp VSCode plugin for C# editor features. That plugin has some configuration settings, one of which is specifying an rspFile path to tell the plugin about usings and assemblies it doesn't know about through its default handling. When the plugin parses the rspFile, it does so using the roslyn API, so this is not an omnisharp problem as omnisharp is using the functionality provided by roslyn. I asked this question over on the omnisharp repo issues and got the response: "Can't do anything, because we just use the Roslyn API, go bug them".

I don't control how the C# compiler resolves references, nor do I invoke the compiler directly. Omnisharp uses the roslyn API for editor features, therefore it controls how it resolves references. However, in the name of code reuse, it is using the roslyn API instead of parsing rspFiles itself, so I still think this is a roslyn issue.

This is a feature request to allow environment variables inside rspFile parsing. If I have a (scripting) project that needs to know about assemblies that do not come within the project repo, providing an absolute path for /r references inside an rspFile is unacceptable as it would only work on a single machine. Imagine those assemblies are installed in some directory on a user's machine, possibly through nuget. I should be able to tell the user: "Hey, make sure your assemblies are installed and this environment variable with the path is defined, and that enables the editor features."

Pardon my ignorance, but as you parse line by line each /r: reference inside the rspFile, you have a nice little .NET API called Env.ExpandEnvironmentVariables where you can pass the argument of the /r: line as a string and out pops a resolved reference relative to the given user's machine. I am sure its not as simple as this, but can you explain to me why this change would not be that simple?

**Comment by jaredpar** [comment] 2021-07-14 16:16
>  If I have a (scripting) project that needs to know about assemblies that do not come within the project repo, providing an absolute path for /r references inside an rspFile is unacceptable as it would only work on a single machine

That is why the compiler has the `-libpath` option. It allows for specifying additional paths the compiler should look to resolve references with are not fully qualified. 

> Pardon my ignorance, but as you parse line by line each /r: reference inside the rspFile, you have a nice little .NET API called Env.ExpandEnvironmentVariables where you can pass the argument of the /r: line as a string and out pops a resolved reference relative to the given user's machine. I am sure its not as simple as this, but can you explain to me why this change would not be that simple?

Just because a change is simple doesn't mean we should do it. Even simple changes have to be maintained, tested and accounted for in scenarios like performance. 

Consider that a change like this concretely impacts at a minimum determinism. At the moment environment variables do not significantly factor into the deterministic nature of our compilation. That allows us a lot of simplifications when we are modeling for security and reliability. The ability to arbitrarily expand any environment variable as a part of command line processing means literally every environment variable must be considered potentially a part of the deterministic compilation input. That's not really acceptable for the scenarios in which determinism matters.

**Comment by LostTime76** [comment] 2021-07-14 16:46
Can you please provide a reference point wherein doing an expansion of environment variables on string command line arguments yields depreciable results? If we are talking milliseconds added for a giant input list, I would say that it doesn't matter all that much. 

Consider these cases:

1. You make the call to expand all environment variables on the inputs as they exist today, which means those inputs do not include environment variables. Since the inputs do not contain the variables, expansion will be fast. Even for a large number of string inputs, it only adds a few milliseconds to the compilation time
2. You make the call to expand all environment variables on degenerate inputs, where the user has rspFiles set up with variables depending on each other (I don't know if that's possible, not an environment variable expert). For a large number of inputs, it adds a lot more time to the compilation - tens of milliseconds. In this case, the user is making an active decision to do something like this for ease of use or whatever and they don't care about the tradeoff. If they do, then they don't use the feature or find another way.
3. You make the call to expand all environment variables on simple inputs that contain 1 or 2 top level variables in each input (no reference dependencies. This turns into something similar to case 1 without much of a performance loss.

I am pretty sure -libpath is not what I am looking for and does not fall into my usage scenario especially if it doesn't accept environment variables. Remember, this discussion is about me not wanting to hardcode absolute paths in shared files inside repositories.

**Comment by jaredpar** [comment] 2021-07-14 17:19
> I am going to assume that by "determinism" you are referring to the fact you can't put your finger on how long compilation will take if you have to expand degenerate environment variables.

No. The term "determinism" refers to the ability to reproduce a build with byte for byte equivalence given the same set of inputs. This is a core property of the C# compiler and one that many systems depend on. Suddenly introducing environment variables, and not just a limited set but all environment variables, to the set of inputs to consider for determinism would break those scenarios. It also violates other principles. 

There would definitely be an impact to performance aspect to builds. Most notably it would significantly impact our ability to compile code in the compiler server environment (which is **the** most important factor in build throughput). The compiler server executes all compilations in the same process. In order to have environment variable support in RSP we would need a mechanism for sharing the process wide state amongst threads processing them.

**Comment by jaredpar** [comment] 2021-07-14 17:20
Closing because it's not realistic given our current requirements and tools to support environment variables in RSP files. It breaks at the minimum determinism and the compiler server infrastructure. 

Can keep the convo going about ways to unblock this scenario but environment variables in RSP isn't a change we'd be willing to take.

**Closed by jaredpar** 2021-07-14 17:20 UTC
Labels: Area-Compilers, Concept-API, Feature Request, Need More Info

**Comment by LostTime76** [comment] 2021-07-14 17:29
Excuse me? I don't think that's how this is supposed to work. I asked a direct question. Please explain and prove this "minimum determinism" you are quoting and why additional STRING processing in MEMORY would be an issue for non degenerate expansion scenarios.

Telling me that a second round of string processing on non degenerate environment variables is going to break "determinism" is not an acceptable answer. If the user provides degenerate use cases, they literally had to understand the scenario and go out of their way to construct it. In this case, they understand the tradeoffs.

I am sorry, but you need to provide an explanation here. If its as simple as pointing me towards documentation that supports your claim, then it should be easy to do that.

**Comment by jaredpar** [comment] 2021-07-14 17:36
>  Please explain and prove this "minimum determinism" you are quoting and why additional STRING processing in MEMORY would be an issue for non degenerate expansion scenarios.

I gave a basic summary of determinism above but you can find more information here:

- https://github.com/dotnet/roslyn/blob/main/docs/compilers/Deterministic%20Inputs.md
- https://reproducible-builds.org/

The issue is not about string processing and memory. It's about understanding what inputs for a build factor into the output of the build. The compiler, because of it's commitment to deterministic output, requires that all inputs to the compilation be specifically listed on the command line to the build. Items like environment variables are not listed and not considered part of the input to the build. 

Accepting this proposal means that we would need to consider all environment variables in the process to be a part of the deterministic input to a compilation. That has a number of implications, including to security, that we are simply not willing to accept. The compiler made a deliberate decision to keep environment variables out of determinism and this proposal doesn't cross the threshold necessary to change that decision.

> What I mind is some rascal deciding a usage or feature doesn't fit into HIS world view and then just trying to slide an opposing scenario under the rug.

Please keep the conversation here in line with our [Code of Conduct](https://dotnetfoundation.org/about/code-of-conduct). Particularly the use of name calling here.

**Comment by LostTime76** [comment] 2021-07-14 17:51
> Consider that a change like this concretely impacts at a minimum determinism. At the moment environment variables do not significantly factor into the deterministic nature of our compilation. That allows us a lot of simplifications when we are modeling for security and reliability. The ability to arbitrarily expand any environment variable as a part of command line processing means literally every environment variable must be considered potentially a part of the deterministic compilation input. That's not really acceptable for the scenarios in which determinism matters.

If you are referring to this explanation, I apologize for being a user of the compiler and not someone who intimately knows the design and design decisions of the compiler to understand such an explanation. "Security" "reliability", and "minimum determinism" were the buzzwords thrown around. 

> Please keep the conversation here in line with our Code of Conduct. Particularly the use of name calling here

I was not under the impression calling somebody a rascal was name calling. Nonetheless, you took it as derogatory when it was not meant to be, but I guess you grepped my intended meaning. In this context: one who sees a different world view and thinks they know better, because morale high ground, or just that I higher than thou because I work on X or at Y.

Anyhow, It sounds like it was a deliberate design decision, which is definitely a valid reason. I was asking for the explanation, that's it. I generally don't disregard thought out design decisions from other people; however, I can't tolerate when things get brushed under the rug, which seemed to be happening here. I just wanted a valid explanation. Done
