### ISSUE TITLE
"Formatting pasted text..." popup not disappearing

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#63129] opened 2022-08-02 09:52 UTC
**Version Used**: Version 17.4.0 Preview 2.0 [32801.270.main]

**Steps to Reproduce**:

Paste code. Paste some more code. Then a third time:

![image](https://user-images.githubusercontent.com/350947/182346152-330b69f0-f843-4e42-b2e3-cff2586a1ab1.png)

**Expected Behavior**:

Popup disappears when it is completed.

**Actual Behavior**:

Popups linger until you actually press <kbd>Esc</kbd>.

**Comment by davidwengier** [comment] 2022-08-02 11:46
Noticed this today too. It's kinda funny when you get a few of these, and they overlap, and/or overlap with the "adding missing usings" indicator.

/cc @olegtk and @kayle as I think perhaps the editor is showing the background work indicator, not Roslyn.

**Comment by olegtk** [comment] 2022-08-02 16:17
sounds like a bug, route it to the editor please.

**Comment by olegtk** [comment] 2022-08-02 16:58
This is fixed, but still pending insertion into VS repo.

**Comment by CyrusNajmabadi** [comment] 2022-08-02 17:11
Fixed with https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/414278

**Closed by CyrusNajmabadi** 2022-08-02 17:11 UTC
Labels: Area-IDE, untriaged

**Comment by CyrusNajmabadi** [comment] 2023-06-13 17:09
@randykroeger You can control that here:

![image](https://github.com/dotnet/roslyn/assets/4564579/7e0916c2-fac1-423a-b7eb-e60b7ed5f3e2)

**Comment by randykroeger** [comment] 2023-06-14 14:01
Thank you.   I was not looking in that part of the options but the text editor options.

Still would think it better to disable new options as opposed to automatically having them enabled.  For those of us that have been developing for 20+ years, it is less frustrating when migrating to the next release of VS.

Randy
________________________________

**Comment by CyrusNajmabadi** [comment] 2023-06-14 14:03
Format on paste is not a new option. It's been the behavior of vs for over 18 years :-)

**Comment by randykroeger** [comment] 2023-06-14 14:06
Haha.  Yes. That is true.  And now I am needing to work in Javascript within VS, which before I used CDN files.  However, I don't remember the little flash label that pops up telling me it is formatting.  🙂   That appears to be new and not necessary.   Formatting never seemed to have such a performance degradation that you needed a popup.

Randy
________________________________

**Comment by randykroeger** [comment] 2023-06-14 14:11
FYI.... My apologies for misleading you in my response.  The issue is not with the C# code files but the Javascript formatting.  Not enough coffee here, is my claim.

Javascript editing is where I see this crazy popup and turned off the following with no real affect.

[cid:2fdb8daf-a094-4df4-8842-b29eda55f972]
________________________________

**Comment by CyrusNajmabadi** [comment] 2023-06-14 14:16
You can ask Microsoft/typescript for an option to disable this feature. :-)

**Comment by randykroeger** [comment] 2023-06-14 14:18
That would be nice.   I will add that along with my other asks of winning a lottery.  haha..

Randy
________________________________

**Comment by CyrusNajmabadi** [comment] 2023-06-14 14:20
I'm being serious. They're a sibling team to us, and asking for an option is entirely reasonable, and something they would do. You can also expedite by helping them with the pr if you are so inclined.

**Comment by randykroeger** [comment] 2023-06-14 14:25
True.   I do apologize for the joke.  These days, I just don't feel that MS listens but develops base on their own internal decisions.  I read some of the articles where people post issues and see they (MS) close things without good investigation, or they tell people they posted in the wrong forum and then close it.  There is a feeling of "you're speaking to closed ears", so to speak.

I have made suggestions in the past with no success.

I truly am impressed, that out of millions of developers, you have responded to me personally!  I can tell you that you have given me some hope.   I can post a suggestion.

Randy
________________________________

**Comment by CyrusNajmabadi** [comment] 2023-06-14 14:31
Both Roslyn and typescript are very responsive to feedback, and make hundreds to thousands of changes based on it :-)

It's also open source. So we have a healthy community of contributors who submit changes themselves for this that bother them, but which are currently at lower priority than the with being done that is being asked for by larger parts of the community and ecosystem. 

I'd recommend being involved in our discords and seeing if that interests you. Discord.gg/csharp and https://aka.ms/dotnet-discord are good starts :-)

**Comment by randykroeger** [comment] 2023-06-14 14:34
Thank you!  You are correct.  I will take a look into the open source more to help contribute.

Randy
________________________________
