### ISSUE TITLE
VB and C# implementation of SemanticModel.GetOperation uses different GetOperationOptions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#17861] opened 2017-03-14 22:43 UTC
C# uses GetOperationOptions.Lowest: http://index/?rightProject=Microsoft.CodeAnalysis.CSharp&file=Compilation%5cCSharpSemanticModel.cs&line=471

VB uses GetOperationOptions.Highest: http://index/?leftProject=Microsoft.CodeAnalysis.VisualBasic&leftSymbol=dq9n3dzezrn6&file=Compilation%5CSemanticModel.vb&line=143

This will affect what bound node/IOperation is returned when there are multiple bound nodes for the same syntax. We need to rationalize why this difference across langauges and whether we need to expose this Options to the public API.

**Comment by mavasani** [comment] 2017-03-14 22:43
Tagging @dotnet/analyzer-ioperation

**Comment by mavasani** [comment] 2017-03-15 18:58
Classic case of this is an expression with an implicit conversion - we will have same syntax mapped to multiple bound nodes (IOperation) and the user should be given the flexibility to specify whether they want the lowest or highest IOperation associated with the syntax based on what analysis they are performing.

**Comment by 333fred** [comment] 2017-03-21 22:08
This difference is actually the cause of #17917. When using `Highest`, the `BoundNode` that the using visitor receives hasn't had its variables bound yet, and accessing throws a null pointer exception.

**Comment by jinujoseph** [comment] 2017-07-19 18:02
**Design Team Meeting**

We should mimic what ever [FindNode](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNode.cs,1973a2affa06beb8) does. Basically have an API which allows users to say "Find me the node for this span"  and in case of multiple nodes for a span, an option to specify if they need the highest/lowest.

**Comment by jinujoseph** [comment] 2017-09-27 22:44
delete this enum http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpSemanticModel.cs,cb181c146ad48a0e it's not been used and close this issue

**Comment by jinujoseph** [comment] 2017-09-29 21:27
This is done

**Closed** 2017-09-29 21:27 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation, _Product-level triaged
