### ISSUE TITLE
Generate class (in new file) is suggested again after the class has been created

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#10987] opened 2016-04-29 19:02 UTC
**Version Used**: 
Visual Studio 2015 Update 2

**Steps to Reproduce**:
1. Write some code that uses classes that do not exist.
2. Press CTRL+. and execute "Generate class |...| in new file".
3. Press CTRL+. again on the same position.

**Expected Behavior**:
GenerateClass is not suggested as a refactoring/code fix again. New created type is immediately compiled and type information is immediately available in the current file.

**Actual Behavior**:
If pressing CTRL+. again on the (before) missing type, GenerateClass is suggested for a code fix again, whereas the new type is syntax highlighted correctly. You can press CTRL+. again and again, doesn't matter how long you are waiting. 

The refactoring/code fix disappears in that moment when you move the cursor (e.g. to another line and then move back to the token). That problem does not occur for GenerateClass (in the same class) or GenerateNestedClass.

![createclassinnewfile_codefix_still_provided_after_execution](https://cloud.githubusercontent.com/assets/2900224/14926693/9dd3e39e-0e4d-11e6-8de1-e4b76d51292e.png)

**Comment by SergeyZhurikhin** [comment] 2016-05-01 13:24
I Disagree!
I tried as an example:
```C#
object o = null;
if (o is C1)
{

} 
```
VS 2015 E RU U2

**Comment by Pilchie** [comment] 2016-05-06 16:49
We were able to reproduce this, but don't think it's terrible since it does go away as soon as the caret is moved.

**Comment by robinsedlaczek** [comment] 2016-05-11 22:38
Yes, I agree. But just for the last bits of great quality. :)

**Comment by CyrusNajmabadi** [comment] 2022-10-28 20:10
This doesn't repro for me.  After generating the type, i get appropriate lightbulb (without having to move caret):

![image](https://user-images.githubusercontent.com/4564579/198723513-146c1f9a-d340-445d-b139-8d475fb9bfff.png)


Closing out.

**Closed by CyrusNajmabadi** 2022-10-28 20:10 UTC
Labels: Bug, help wanted, Area-IDE
