### ISSUE TITLE
[Test Failure] MSBuild Error in prtest/win/dbg/unit32 on PR #9798

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9801] opened 2016-03-16 15:46 UTC
PR: [#9798](https://github.com/dotnet/roslyn/pull/9798) *Merge future-stabilization into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5254/

**Issue 1: MSBuild Error**
error MSB3026:  Could not copy "C:\Users\dotnet-bot\.nuget\packages\Microsoft.CodeAnalysis.Test.Resources.Proprietary\1.2.0-beta1-20160105-04\lib\net45\Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll" to "d:\j\workspace\roslyn_prtest---345e02d2\Binaries\Debug\Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'd:\j\workspace\roslyn_prtest---345e02d2\Binaries\Debug\Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll' because it is being used by another process. [d:\j\workspace\roslyn_prtest---345e02d2\src\Test\Utilities\Portable.FX45\TestUtilities.FX45.csproj] -&gt; 15:12:29.816    18&gt;C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5):

**Comment by davkean** [comment] 2016-03-16 15:57
Duplicate of https://github.com/dotnet/roslyn/issues/8975

**Closed by davkean** 2016-03-16 15:57 UTC
Labels: Bug
