### ISSUE TITLE
conversion from block namespace to inline delete commented code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63769] opened 2022-09-02 17:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/conversion-from-block-namespace-to-inlin/10137007)._

---
\[severity:Other\]  
The reproduction is simple :

1.  Create a class
2.  Comment out the whole class (/\*\*/ or //)
3.  add semicolon to namespace

result : VS auto delete the braces but also the commented lines.

Before :  
![image](https://user-images.githubusercontent.com/4564579/188205977-0e8ec610-e05e-4382-8019-4e1dd5725649.png)

After:  
![image](https://user-images.githubusercontent.com/4564579/188206000-67589f48-479f-446c-9b9a-b41aa7b49268.png)

After playing around the bug, it is more nasty than i though :

before
![image](https://user-images.githubusercontent.com/4564579/188206025-e473288b-11ea-411c-aee4-dbcf9683e465.png)

After
![image](https://user-images.githubusercontent.com/4564579/188206038-a3c5cfa1-e233-41c7-a274-782d3a0d7658.png)

So comments directly inside the namespace are deleted. **In large file, this is not noticeable.**
Now, if there a space or newline after the namespace close brace, it work as excepted, not deleting comment.

The storie behind this : I wanted to get my code actualy build, this class was a test and had errors, so i commented out all the class and while i was there wanted to get an inline namespace for it.  
The intend was to get back to this class work later.

Severity is other, but deleting code is a nasty bug.

Cheers,  
Julien

---
#### Feedback Bot on 9/1/2022, 06:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-09-02 17:36
Dupe of https://github.com/dotnet/roslyn/issues/57564

**Closed by CyrusNajmabadi** 2022-09-02 17:36 UTC
Labels: Bug, Area-IDE

**Comment by uzinable** [comment] 2022-09-03 08:59
if namespace close brace is the last char of the file, bug still do his nasty things, im on VS2022
I looked at the tests done for this and almost all have a newline.

_Double comment, but I don't know how to be noticed from Closed issue._
