### ISSUE TITLE
Invalid "CS0165: Use of unassigned local variable"

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#18576] opened 2017-04-10 16:26 UTC
**Version Used**: 

> Microsoft Visual Studio Enterprise 2017
> Version 15.1 (26403.0) Release
> VisualStudio.15.Release/15.1.0+26403.0
> Microsoft .NET Framework
> Version 4.6.01586

**Steps to Reproduce**:

Try to compile next method:

```cs
private static int Parse(string text, IFormatProvider formatProvider) {
  int result;
  if(formatProvider != null && Int32.TryParse(text, NumberStyles.Integer, formatProvider, out result)) {
    return result;
  } else if(formatProvider == null && Int32.TryParse(text, out result)) {
    return result;
  } else {
    return result; // error CS0165: Use of unassigned local variable 'result' here
  }
}
```

**Expected Behavior**:

Really, `result` initialized in first `TryParse` or in second `TryParse`, depended on `formatProvider == null`. I think, compiler can prove that `result` was initialized after `else if`.  May be, comparisons `formatProvider == null` and `formatProvider == null` is not mutually exclusive?

Is analysis like required for this too complicated? May be, the complexity of the analysis is determined by language specification?

**Actual Behavior**:

> `error CS0165: Use of unassigned local variable 'result'`

**Comment by SkyGen** [comment] 2017-04-10 18:03
What assignment would be made if it couldn't parse the text?

**Comment by gafter** [comment] 2017-04-10 19:47
@SkyGen `Int32.TryParse` is specified to place `0` in the result if the parse fails.

@ViIvanov The compiler is obeying the language specification for definite assignment, which requires an error be produced for this code. The specification does not permit the compiler to track whether or not variables are known to be null or not based on previous tests. Making the compiler do that would require a change to the language specification, but no such change has been proposed.

I am closing this as by design.

**Closed by gafter** 2017-04-10 19:47 UTC
Labels: Area-Compilers, Resolution-By Design
