### ISSUE TITLE
Language service shows non-accessible protected setters inside object initializers

### ISSUE THREAD

**Issue by lmcarreiro** [dotnet/roslyn#32839] opened 2019-01-26 15:25 UTC
**Version Used**:

Visual Studio Enterprise 2017 version 15.9.4 / VisualStudio.15.Release/15.9.4+28307.222
C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

**Steps to Reproduce**:

1. Write an abstract class A with a public property that has a public getter and a protected setter.
2. Write a non-abstract class B that inherits from A.
3. In a class C that doesn't inherit from A or B, instantiate a class B and hit [Ctrl]+[Space] inside the object initializer.

**Expected Behavior**:
Do not show properties with protected setters.

**Actual Behavior**:
Showing properties with protected setters.

![image](https://user-images.githubusercontent.com/13019179/51789038-f492f600-216b-11e9-84cd-fa46689d7722.png)

```cs
namespace X
{
    class Y
    {
        Animal[] animals = new Animal[]
        {
            new Dog
            {
                Name = "Leo", // error
            },
            new Dog
            {
                /* [Ctrl]+[Space] here */
            }
        }
    }

    abstract class Animal
    {
        public string Type { get; }
        public string Name { get; protected set; }
    }

    class Dog : Animal
    {

    }
}
```

**Comment by sharwell** [comment] 2019-01-29 18:58
Duplicate of #22816

**Closed by sharwell** 2019-01-29 18:58 UTC
Labels: Area-IDE
