### ISSUE TITLE
Can't get leading trivia of method parameter when analyzing cSharp.

### ISSUE THREAD

**Issue by pauldotknopf** [dotnet/roslyn#18953] opened 2017-04-24 18:26 UTC
**Version Used**:  Microsoft.CodeAnalysis.CSharp 2.1.0

**Steps to Reproduce**:

```c#
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace TestCSharpParser
{
    class Program
    {
        static void Main(string[] args)
        {
            var cSharp = BuildCSharpClass(@"T.GetString(/*comment 1*/""test""/*comment 2*/)");
            Parse(cSharp);
        }

        static void Parse(string contents)
        {
            var tree = CSharpSyntaxTree.ParseText(contents);

            var root = tree.GetCompilationUnitRoot();

            var invocationNodes = root.DescendantNodes(descendIntoTrivia: true)
                .OfType<InvocationExpressionSyntax>()
                .ToArray();

            foreach (var node in invocationNodes)
            {
                var name = "";
                if (node.Expression.Kind() == SyntaxKind.SimpleMemberAccessExpression)
                    name = ((MemberAccessExpressionSyntax)node.Expression).Name.Identifier.Text;
                else if (node.Expression.Kind() == SyntaxKind.IdentifierName)
                    name = ((IdentifierNameSyntax)node.Expression).Identifier.Text;
                else
                    // unsupported
                    continue;

                if (name == "GetString")
                {
                    if (node.ArgumentList.Arguments.Count < 1) continue;
                    
                    var textArguement = node.ArgumentList.Arguments[0];

                    if (textArguement.HasLeadingTrivia)
                    {
                        foreach (var comment in textArguement.GetLeadingTrivia())
                        {
                            Console.WriteLine(comment.ToFullString());
                        }
                    }

                    if (textArguement.HasTrailingTrivia)
                    {
                        foreach (var comment in textArguement.GetTrailingTrivia())
                        {
                            Console.WriteLine(comment.ToFullString());
                        }
                    }
                }
            }
        }

        static string BuildCSharpClass(string methodInvocation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("namespace Test");
            sb.AppendLine("{");
            sb.AppendLine("public class TestClass");
            sb.AppendLine("{");
            sb.AppendLine("public TestClass()");
            sb.AppendLine("{");
            sb.AppendLine($"System.Console.WriteLine({methodInvocation});");
            sb.AppendLine("}");
            sb.AppendLine("}");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
```

**Expected Behavior**:

```
> /*comment 1*/
> /*comment 2*/
```

**Actual Behavior**:

```
> /*comment 2*/
```

**Comment by CyrusNajmabadi** [comment] 2017-04-24 18:50
"/*comment 1*/" is not the leading trivia of the parameter.  It is the trailing trivia of the ```(``` token.  :)

This is very much 'by design' given our invariants around tokens/trivia in our trees.  But it can definitely be 'surprising'.

**Comment by CyrusNajmabadi** [comment] 2017-04-24 18:52
If you want your intutive idea on what the 'leading trivia' would be, you'd need to get the previous token, and include it's trailing trivia *if* the previous token was on the same line as you.

**Comment by CyrusNajmabadi** [comment] 2017-04-24 19:05
@gafter Closing as by-design.  Let me know if you have any issues with that resolution.

**Closed by CyrusNajmabadi** 2017-04-24 19:05 UTC
Labels: Area-Compilers, Resolution-By Design

**Comment by gafter** [comment] 2017-04-25 03:35
@CyrusNajmabadi Thank you!
