### ISSUE TITLE
IDE0044 is incorrectly suggested for pointer fields used with address-of operator

### ISSUE THREAD

**Issue by nathan-alden-sr** [dotnet/roslyn#38287] opened 2019-08-26 02:10 UTC
**Version Used**: 

Visual Studio Community 2019 Preview 16.3.0 Preview 2.0

**Steps to Reproduce**:

Visual Studio incorrectly suggests making the following field `readonly`. Fields used with the address-of operator should presumably not be made `readonly`.
```
public unsafe class Brushes
{
    private readonly DisposableCollection _disposables = new DisposableCollection();
    private ID2D1SolidColorBrush* _opaqueWhite;

    public ID2D1SolidColorBrush* OpaqueWhite => _opaqueWhite;

    public void ReleaseDeviceResources()
    {
        _disposables.RemoveAllDisposables();
    }

    public void InitializeDeviceResources(ID2D1RenderTarget* renderTarget)
    {
        ReleaseDeviceResources();

        fixed (ID2D1SolidColorBrush** opaqueWhite = &_opaqueWhite)
        {
            var opaqueWhiteColor = new DXGI_RGBA { r = 1, g = 1, b = 1, a = 1 };

            renderTarget->CreateSolidColorBrush(&opaqueWhiteColor, null, opaqueWhite);

            _disposables.AddDisposables(
                new DisposableIUnknown((IUnknown*)_opaqueWhite));
        }
    }
}
```

**Expected Behavior**:

IDE0044 is never suggested.

**Actual Behavior**:

IDE0044 is incorrectly suggested.

See related issue #38286.

**Comment by CyrusNajmabadi** [comment] 2023-02-01 19:55
I'm not actually understanding the problem here.  The code is unsafe, so it can do whatever it wants.  The safe portions of hte code though are not writing to the field, so it can be made readonly.

**Comment by RikkiGibson** [comment] 2023-02-01 20:48
We do expect to be able to take a pointer to a readonly field and mutate it.

You could say there's an element of "communicating intent" here, that the author wants it to be non-readonly to make it clear that this thing can change, but you could also say "unsafe is unsafe".

**Comment by CyrusNajmabadi** [comment] 2023-02-01 20:50
I say "unsafe is unsafe" :)

**Comment by CyrusNajmabadi** [comment] 2023-02-14 01:40
Closing out as working as intended.  Unsafe code is unsafe and can do whatever it wants (similar to reflection).

**Closed by CyrusNajmabadi** 2023-02-14 01:40 UTC
Labels: Bug, help wanted, Area-IDE, untriaged, Feature - IDE0044
