### ISSUE TITLE
Bad sequence points when an if statement is last in a method, and the controlled statement is throw

### ISSUE THREAD

**Issue by hardcodet** [dotnet/roslyn#11267] opened 2016-05-12 15:12 UTC
**Version Used**: dnxcore50

**Steps to Reproduce**:

Have a look at this method that has two identical if statements:

```
public async Task Foo()
{
    int x = 199 + 1;
    if (x == 500)
    {
        throw new AggregateException("WTF");
    }

    await Task.FromResult(1);

    int y = 199 + 1;
    if (y == 500)
    {
        throw new AggregateException("WTF");
    }


    //await Task.FromResult(1);
}
```

The second if statement here evaluates to true for now obvious reason and the exception is thrown - there seems to be a compiler issue. In order for the exception not to be thrown (the statement evaluating to false), the second await can be uncommented, or the throw within the if replaced by something else.

(you will have to set a breakpoint in the attached sample - I think the exception just occurs on a background thread and this doesn't surface)

Repro attached.

[WebApplication1.zip](https://github.com/dotnet/roslyn/files/261610/WebApplication1.zip)

**Expected Behavior**:

Booleans evaluated correctly.

**Actual Behavior**:

False boolean expression evaluated as true. Exception not hitting through to caller.

**Comment by svick** [comment] 2016-05-12 17:59
As I already mentioned in dotnet/corefx#8475, I can't reproduce the exception being incorrectly thrown. What I can reproduce is the `throw` line being incorrectly shown as active in the VS debugger, presumably due to incorrect PDB (see [some more details on that issue](https://github.com/dotnet/corefx/issues/8475#issuecomment-218775819)).

@hardcodet You mentioned this caused a unit test to fail, can you share that failing unit test?

**Comment by tmat** [comment] 2017-04-19 01:23
This was fixed by https://github.com/dotnet/roslyn/pull/16803. Doesn't repro with the latest compiler.

**Comment by tmat** [comment] 2017-04-19 01:23
@jcouv FYI

**Closed by tmat** 2017-04-19 01:23 UTC
Labels: Area-Interactive, Bug, Interactive-Debugging
