### ISSUE TITLE
incorrect fix for IDE0007 when calling method with implicit generic parameters

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#24017] opened 2018-01-03 14:44 UTC
**Version Used**:  15.5.2

**Steps to Reproduce**:

1. Run quick fix for "use 'var' instead of explicit type" on `out DateTimeKind` this code:

```csharp
void Test()
{
    Assert.IsTrue(Enum.TryParse("Local", out DateTimeKind result) && result == DateTimeKind.Local);
}
```

**Expected Behavior**:

either suggestion does not apply in this case or:

```csharp
void Test()
{
    Assert.IsTrue(Enum.TryParse<DateTimeKind>("Local", out var result) && result == DateTimeKind.Local);
}
```

**Actual Behavior**:

```csharp
void Test()
{
    Assert.IsTrue(Enum.TryParse("Local", out var result) && result == DateTimeKind.Local);
}
```

Error: CS0411

**Comment by bbarry** [comment] 2018-01-03 15:09
Diagnostic is https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs

A change by @CyrusNajmabadi https://github.com/dotnet/roslyn/commit/d20c7b91ca73500ce8e3f44ab9ff632b04f34a1e appears to attempt to fix this (I cannot clone to add a test here and verify)? It looks like this change is not in the current version of VS.

**Comment by CyrusNajmabadi** [comment] 2018-01-03 15:24
The change went into master in november: https://github.com/dotnet/roslyn/pull/23135

It's quite possible it isn't in the version of VS you're using.

**Comment by sharwell** [comment] 2018-01-04 17:38
Duplicate of #23250

**Closed by sharwell** 2018-01-04 17:38 UTC
Labels: Area-IDE
