### ISSUE TITLE
GetDeclaredSymbol returns null for EventFieldDeclarationSyntax

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [dotnet/roslyn#53353] opened 2021-05-12 10:10 UTC
Microsoft.CodeAnalysis.CSharp: 3.8.0-5.final

**Steps to Reproduce**:
1. Register for SyntaxKind.EventFieldDeclaration
2. Call GetDeclaredSymbol(this SemanticModel semanticModel, MemberDeclarationSyntax declarationSyntax, CancellationToken cancellationToken = default) for SyntaxNode

**Expected Behavior**:
Return the declared symbol.
**Actual Behavior**:
Returns null.

I checked and the symbol exists. The context.ContainingSymbol is the DeclaredSymbol in this case.

**Comment by Youssef1313** [comment] 2021-05-12 11:23
An EventFieldDeclarationSyntax can contain multiple declarators. That's why `GetDeclaredSymbol` returns null.

https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L1482-L1485

It could be adjusted to not return null when it contains a single declarator, similar to what's done in other places:

https://github.com/dotnet/roslyn/blob/609a704f60034dff48176e734d543bee7608a357/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs#L1987-L1997

Not sure if it's worth doing so.

**Comment by CyrusNajmabadi** [comment] 2021-05-12 17:51
Closing out as by design.   

> It could be adjusted to not return null when it contains a single declarator, similar to what's done in other places:

I would push back against this.  This has been a large source of bugs.  I would prefer we are just entirely consistent here.  You call on the declarator.  That's clear and can be done in all cases. :)

**Closed by CyrusNajmabadi** 2021-05-12 17:51 UTC
Labels: Area-Compilers, untriaged
