### ISSUE TITLE
IDE0007 and IDE0008 configuration only offers prefer one or the other.  We need a "developer's choice".

### ISSUE THREAD

**Issue by johndog** [dotnet/roslyn#57734] opened 2021-11-12 20:35 UTC
**Version Used**:  

Reported by the compiler:

`Microsoft (R) Visual C# Compiler version 3.11.0-4.21403.6 (ae1fff34)`

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/22213780/141010259-939cea13-1011-4e13-9251-c7ff884860fb.png)

1. Configure 'var preferences' for 'Elsewhere' to prefer explicit types
2. Encounter a situation in which a var type is better.  For example, a function returning a named tuple would introduce redundancy to explicitly declare the type, and var is much safer (no risk of swapping the names/assignments).
3. Use var instead for capturing the return value for all call-sites of the function, while using explicit types for other cases.
3. Discover that there is no way to get the IDE to stop analyzing these cases and pointing out errors for all instances of (for example) tuple-returning functions, without making it stop reporting on IDE0007 and IDE0008 altogether.

**Conclusion**:  If the analyzer can't always offer granular analysis, which the vague 'elsewhere' category indicates, then it needs to offer a way to ignore whether or not var is used defer to the developer.

**Comment by CyrusNajmabadi** [comment] 2021-11-12 20:48
>Discover that there is no way to get the IDE to stop analyzing these cases and pointing out errors for all instances of (for example) tuple-returning functions, without making it stop reporting on IDE0007 and IDE0008 altogether.

It feels like this is the right approach anyways.  It sounds like you are saying: this really depends on how i feel about any particular piece of code.  In which case, you are not asking for automated verification, and disabling makes sense.

>  then it needs to offer a way to ignore whether or not var is used defer to the developer.

If you set this to 'refactoring only' then we ignore what you've written and will surface no hints/warnings/errors.  We, of course, will still let you quickly change things in the lightbulb so you can swap easily when you decide you like one more than the other.

**Comment by johndog** [comment] 2021-11-12 22:00
> It feels like this is the right approach anyways. It sounds like you are saying: this really depends on how i feel about any particular piece of code. In which case, you are not asking for automated verification, and disabling makes sense.

I only want to disable automated verification for the "elsewhere" cases.

Roslyn can recognize cases where 1) a built-in type is used, and 2) some subset of cases where it decides that a type is obvious.  If it can recognize these cases consistently, I have no problem with a rule that enforces them one way or another.  Although I still don't know why one would have to choose one or the other for both of these.  3 different settings: 'Developer Preference' should be an option for any or all of the three.

The final category of "all other cases" is chock full of obvious cases that the compiler doesn't recognize.  So if you care about "obviousness" -- a domain of humans -- and not just "obviousness according to the compiler", then this has to be left up to the developer to decide.  

Having all three of them lumped together in IDE0007 and IDE0008 means the good has to be thrown out with the bad.  Furthermore, even though there are settings for configuring the behavior of the different categories in the IDE, there is no actual way to **disable** them in the IDE, even if I wanted to disable them all.  

> If you set this to 'refactoring only' then we ignore what you've written and will surface no hints/warnings/errors. We, of course, will still let you quickly change things in the lightbulb so you can swap easily when you decide you like one more than the other.

This presents for me in the form of red squiggles that I can never make go away, at least not without turning off all 'var' enforcement.  I need those squiggles to go away.

**Comment by CyrusNajmabadi** [comment] 2021-11-12 22:22
> I only want to disable automated verification for the "elsewhere" cases.

Sure.  If you have that set to 'refactoring only' you should get no automated verification.

>  'Developer Preference' should be an option for any or all of the three.

Setting each to 'refactoring only' is saying just that.

>  there is no actual way to disable them in the IDE, even if I wanted to disable them all.

Again, 'refactoring only' is disabled.  It means you won't be presented with any validation.  Instead, you just see the option in the lightbulb to speed things up in case that's what you personally wanted to do and you'd like us to just do it for you more quickly.

> This presents for me in the form of red squiggles 

Red squiggles means that you, or someone else, has set this to 'error', possibly through the use of .editorconfig.  In that case, we are abiding by the express wishes of that setting and reporting accordingly.  You'd have to either remove the respective .editorconfig setting here, or ask the maintainer to do that.

**Comment by johndog** [comment] 2021-11-12 22:52
Okay, you are mostly right; I searched the project and found no such configuration, but on your insistence I searched again and found the editor config.

Unfortunately, there's still a bug.  It is presented as an error, but it's configured as a "warning":

    csharp_style_var_elsewhere = false:warning 

But it shows nonetheless in the 2019 IDE as an error.  I tried deleting this line from the .editorconfig; that made the Errors go away.  I then tried configuring it as a warning again in the IDE, and the errors returned immediately:

![image](https://user-images.githubusercontent.com/22213780/141578778-e890aeaa-6333-4863-91e2-9bf28f817ba5.png)

**Comment by CyrusNajmabadi** [comment] 2021-11-13 01:16
Does something in the project set 'treat warnings as errors'?

**Comment by johndog** [comment] 2021-11-13 03:46
I tried to find something relevant in IDE options, couldn't find any evidence of configurable options there.  

A search of the codebase for the word "warnings" turns up a few of these:

    <MSBuildTreatWarningsAsErrors>false</MSBuildTreatWarningsAsErrors>

But that's it.  So unless it defaults to true, I'm not sure how it could be a configuration issue.  I also don't know how to get more visibility into the cause.

**Comment by sharwell** [comment] 2021-11-18 01:27
It looks like a .editorconfig or a .ruleset is setting the value of `dotnet_diagnostic.IDE0008.severity` and overriding the more specific values you were trying to set with the `false:warning` syntax.

**Comment by CyrusNajmabadi** [comment] 2024-11-13 22:30
Closing as working as intended.

**Closed by CyrusNajmabadi** 2024-11-13 22:30 UTC
Labels: Question, Area-IDE, Feature - IDE0008, Feature - IDE0007
