### ISSUE TITLE
Accepting completion list time 'parameter' does not include the ':' from the presented text in the completion item

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61412] opened 2022-05-19 19:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Accepting-completion-list-time-paramete/10045382)._

---
When accepting a parameter in the completions list the : is not included in the inserted text. This bothers me every time I insert the name of the parameter to have named parameters in my functioncall:

![image.png](https://aka.ms/dc/image?name=B2f8278a136c14535bee23a107b14e875637884407420508267_20220517-201900-image.png&tid=2f8278a136c14535bee23a107b14e875637884407420508267)

I would like to have the xxxx + : inserted when I accept the completion item.

It just bothers me, it is not regressed, but I would like to get what I select.

---
#### Feedback Bot on 5/18/2022, 00:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2022-05-19 19:20
Duplicate of #32204

**Closed by sharwell** 2022-05-19 19:20 UTC
Labels: Area-IDE, untriaged
