### ISSUE TITLE
Quick action Inline temporary variable can create expensive code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43312] opened 2020-04-13 16:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/987320/quick-action-inline-temporary-variable-can-create.html)._

---
Usually I will include a temporary variable for a good reason. If a temp (the thing called "temp" in the screenshot) is the result of an expensive piece of code (e.g. an IEnumerable<T> whose cost I can't control), which is cached with ToList(), then inlining it is a bad idea. It will result in running the enumeration more than once; there isn't even a guarantee that it is idempotent as I can't control what comes from a remote access from one moment to the next. The Quick action should come with a health warning.

---
#### David Brooks on 4/12/2020, 07:30 PM: 

<p>I should have been clearer: the reason this is an incorrect substitution is the .ToList() at the end of a chain of methods in the Enumerable class, which immediately runs any preceding iterations. Would also be true of ToArray(), Aggregate() etc. If the chain ends in a deferred-execution IEnumerable, then inlining isn't so wrong, just wasteful because of the extra IEnumerable objects that have to be created.</p><p>And because of the non-idempotent issue (I love that word) "expensive" in the title should also say "and incorrect".</p><p>I uploaded sample code and a screenshot of the substitution, but can't see them.</p>

#### Visual Studio Feedback System on 4/13/2020, 02:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-04-13 16:46
This is similar to #31780

**Comment by DavidWBrooks** [comment] 2020-04-13 22:59
Transfer from the feedback system seems to have lost my screenshot.

Although I haven't read all of the long commentary on 31780, it seems to be only about performance (LINQ functions versus classic code). My point is that the refactoring in this rule can _also_ give different results, because an IEnumerable<T> is not guaranteed to return the same result on re-run. Given:
   var tmp = ExpensiveIEnumerable().Where(MyDelegate).ToList();
   DoSomething(tmp); DoSomethingElse(tmp);
it is not only worse performance, with more allocations, but can give different results, if changed to:
   DoSomething(ExpensiveIEnumerable().Where(MyDelegate).ToList());
   DoSomethingElse(ExpensiveIEnumerable().Where(MyDelegate).ToList());
The purpose of the ToList() is to say I do _not_ want to re-run the two iterations. It's for both performance and the possible side-effects of the concatenated enumeration.

One comment near the end of 31780 is germane: light bulbs are just suggestions and you have to think about them intelligently and possibly discard them. If so, can I have a "don't show this suggestion again" option? And I actually doubt the utility of "inline a temp variable" at all; my temp variables are always either functional in this way, or just to aid comprehension.

**Comment by CyrusNajmabadi** [comment] 2022-11-02 19:22
Closing out.  This is by design.  The user said they wanted to inline the initializer at all the use sites.  So that was what was done.  If the user doesn't want that expensive work to be performed multiple times, then they should not inline the initializer.

**Closed by CyrusNajmabadi** 2022-11-02 19:22 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community, Need Design Review
