### ISSUE TITLE
Tuple style isn't recognized in interpolated strings

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#17307] opened 2017-02-22 21:09 UTC
If I have a string.Format with tuples and their implicit names, I correctly get the Suggestion dots (as configured in my EditorConfig) letting me know to use the explicit tuple name:

![image](https://cloud.githubusercontent.com/assets/1402694/23232252/6798d350-f8ff-11e6-88f9-801e106bd307.png)
![image](https://cloud.githubusercontent.com/assets/1402694/23232417/09d11894-f900-11e6-97ce-1c45d8753004.png)

However, if I convert my string.Format to an interpolated string, I don't get the Suggestion anymore...

![image](https://cloud.githubusercontent.com/assets/1402694/23232282/7d62effe-f8ff-11e6-8332-fda5050de222.png)

Repro code:
```csharp
public (int a, int b) Stuff() => (5, 3);
public string DoStuff()
{
     var stuff = Stuff();
     return $"{stuff.Item1}, {stuff.Item2}";
}
```

**Comment by CyrusNajmabadi** [comment] 2017-02-23 20:09
This appears to be an IOperation bug.  We never get called back for the FieldReferenceExpressions inside the interpolated string.  

Tagging @ManishJayaswal .  Manish, can you assign this appropriately to someone who can fix this issue?

**Comment by mavasani** [comment] 2017-04-19 23:07
This is dupe of https://github.com/dotnet/roslyn/issues/18300

**Closed by mavasani** 2017-04-19 23:07 UTC
Labels: Area-Analyzers, Area-IDE, Bug, New Feature - IOperation, Urgency-Soon
