### ISSUE TITLE
VB static member intellisense shows conversion operators 

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21242] opened 2017-08-01 23:42 UTC
Type the code below, invoking completion as shown:

![image](https://user-images.githubusercontent.com/201340/28851570-441a74e0-76d8-11e7-8f00-f5e9f5a5b959.png)

This seems fishy that we show that. It seems that completing it does work (kinda), but other things like highlight references acts strange too.

**Comment by CyrusNajmabadi** [comment] 2023-02-03 18:26
I'm going to close this out as not a bug.  VB actually allows the methods to be called in this named fashoin (wacky, i know).  Given we've heard nothing from users about this actually being as problem, i'm more amenable to keeping this and not breaking anyone's workflow versus changing anything here.

**Closed by CyrusNajmabadi** 2023-02-03 18:26 UTC
Labels: Bug, help wanted, Area-IDE
