### ISSUE TITLE
The pre-selected "Suggest Name" for parameters has inconistent casing and violates .editorconfig

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#59562] opened 2022-02-15 12:45 UTC
**Version Used**: 17.0.6

**Steps to Reproduce**:

```csharp
public class Test
{
    public void M(/* add Parameters here**)
    { }
}
```
and an `.editorconfig` with this
https://github.com/dotnet/roslyn/blob/main/.editorconfig#L120-L127
(I have "warning" instead of suggestion)

The first parameter is of type `Test` and the suggested name is `Test` with a capital `T`. This violates the .editorconfig and gets a squiggle.
The second parameter is of type `IEnumerable<Test>` and the suggested name is `tests` - great!
The third parameter is of type `IComparable` and the suggested name is `comparable` - great!
The fourth parameter is of type `CancellationToken` and the suggested name is `CancellationToken` - squiggle.

**Expected Behavior**:
All suggested names should start with a lower case letter.

**Actual Behavior**:
As described above, but what's worse is that any kind muscle memory is currently worthless here. It used to be that I could very quickly complete parameters, but as it is now I continuously have to check, go back to fix, or choose the first (correct) list entry manually.

![suggested-name-inconsistent](https://user-images.githubusercontent.com/1947968/154064556-07b9dc73-3595-4909-916c-dc1d3cd28967.gif)

**Comment by Youssef1313** [comment] 2022-02-15 13:42
Probably already fixed in https://github.com/dotnet/roslyn/pull/59401.

**Comment by sharwell** [comment] 2022-02-16 04:30
Duplicate of #36248

**Closed by sharwell** 2022-02-16 04:30 UTC
Labels: Area-IDE, untriaged

**Comment by sharwell** [comment] 2022-02-16 04:31
In case it wasn't obvious from the pull request, here's the conflicting rule that was generating the unwanted names:

https://github.com/dotnet/roslyn/blob/0098764330d1e22c43ead6065e4ed5f8aae09195/.editorconfig#L138-L145
