### ISSUE TITLE
Target-typed new IntelliSense shouldn't work on language version not supporting it

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#55369] opened 2021-08-03 06:29 UTC
**Version Used**: 

17.0 P2.1

**Steps to Reproduce**:

On a C# 8.0 project:

![image](https://user-images.githubusercontent.com/31348972/127968315-efb99d77-a94f-4180-96e0-b9e6dc7b34e1.png)

**Expected Behavior**:

IntelliSense not showing

The current behavior isn't bad too, and I can see argument for it. So feel free to close if you prefer the current behavior.

**Comment by CyrusNajmabadi** [comment] 2021-08-03 06:46
Yeah.  In general we dont' punish you for using features when not allowed.  IDE features should still work, but the user gets an appropriate error telling them what the problem is.  Closing out as by-design, and in line with how the rest of roslyn works.

**Closed by CyrusNajmabadi** 2021-08-03 06:46 UTC
Labels: Area-IDE, untriaged
