### ISSUE TITLE
Cannot insert a breakpoint at a const field or local.

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#7392] opened 2015-12-10 11:32 UTC
When inserting a breakpoint on a variable declaration that includes `const`, the status bar says "A breakpoint could not be inserted at this location" and no breakpoint is inserted (evidently).

Consider the following snippet:

``` csharp
class MyClass
{
    private int x = 5; // Can have breakpoint
    private const int y = 5; // Can't have breakpoint

    void MyMethod()
    {
        int a = 5; // Can have breakpoint
        const int b = 5; // Can't have breakpoint
    }
}
```

Confirmed affected versions: VS 2015, VS 2015 Update 1

**Comment by HaloFour** [comment] 2015-12-10 11:43
There is no IL generated for constant declarations so I wouldn't expect that you would be able to attach a breakpoint to their location in source.  I don't have VS2013 in front of me but I don't believe that this is a change in behavior.

**Comment by Vannevelj** [comment] 2015-12-10 11:56
I only have very basic knowledge of IL but isn't the `nop` code something that can remedy this? I thought it was meant to help the debugger break in areas it normally can't.

**Comment by HaloFour** [comment] 2015-12-10 12:19
@Vannevelj Yes, the `nop` opcode can be used for that, but the C# compiler has not generally used it to bind to non-executable lines of source.  That seems to have been a conscious decision made by the C# team.  The VB.NET compiler does quite aggressively emit `nop` opcodes for every line of source, although it seems that VS2015 does not permit setting breakpoints on non-executable lines either.

**Comment by SaxxonPike** [comment] 2015-12-10 16:22
Does it make sense that a `const` statement "executes" in the same way as other code? I always figured it was evaluated once at compile time and is substituted everywhere else, which would indicate it's not actually executed at all.

Not to disagree with your statement, of course. I'm trying to understand the situation better.

**Comment by HaloFour** [comment] 2015-12-10 16:46
@SaxxonPike As you've described it doesn't execute like other code, due to the fact that it's evaluated at compile-time.  The variable `b` never exists, the compiler does evaluate the expression during compile time and replaces all uses of that identifier with the result directly.

There is no technical limitation as to why it's not permitted to set such a breakpoint.  Given that VB.NET does emit the necessary `nop` opcodes and VS2015 still doesn't permit those breakpoints this seems to have been by design.  There's really nothing to gain by being able to set those breakpoints, but it would be nice if the IDE could at least put the breakpoint on the next executable line rather than just complaining about it.

**Comment by tmat** [comment] 2015-12-10 17:33
We don't place breakpoints on constructs that don't produce IL. Another example is 
```
int x;
```

As stated we could however emit ```nop``` in debug mode. Another option would be to find the closest next statement and place breakpoint there (e.g. next line).

**Comment by SaxxonPike** [comment] 2015-12-14 15:36
I could see this being helpful where you have a block of code that looks somewhat like this:
```csharp
var x = SomeFunctionThatReturnsAnInt();
const int y = 3;
var z = x + y;
```
I've seen in production code where a `const` is located in the middle of other code simply because it makes sense to have the constant nearby where it is used (if it's really only used in a small place.) I typically like to debug by putting a breakpoint on the statement immediately after what I want to know the result of. Just having to know to put the breakpoint on line 3 is a little barrier to working faster, I think.

I think this would be a pretty nifty addition.

**Comment by tmat** [comment] 2017-09-10 20:27
Closing as I don't think we are going to change the design in foreseeable future.

**Closed by tmat** 2017-09-10 20:27 UTC
Labels: Area-Interactive, Feature Request, Interactive-Debugging

**Comment by kmelodi** [comment] 2017-10-31 08:09
Set 'Configuration Manager' => Debug
