### ISSUE TITLE
NRE in CSharpProjectFile.GetReferences

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#7206] opened 2015-12-03 16:42 UTC
Targetsite
```
{Void GetReferences(CSharpCompilerInputs, Microsoft.Build.Execution.ProjectInstance, System.Collections.Generic.IEnumerable`1[Microsoft.CodeAnalysis.MetadataReference] ByRef, System.Collections.Generic.IEnumerable`1[Microsoft.CodeAnalysis.Diagnostics.AnalyzerReference] ByRef)}
```
Source
```
Microsoft.CodeAnalysis.Workspaces.Desktop
```
Stacktrace
```
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.GetReferences(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject, IEnumerable`1& metadataReferences, IEnumerable`1& analyzerReferences)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.CreateProjectFileInfo(CSharpCompilerInputs compilerInputs, ProjectInstance executedProject)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<LoadProjectAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<GetOrLoadProjectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__34.MoveNext()
```

VS Version Info
```
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA613
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA613
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA613
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Tools   1.5.103
An extension for making it easier to write Visual Studio extensions

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Msiler   1.0
MSIL Code Viewer for Visual Studio 2013

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio
```
-----
repo

```vb.net
Module Module1

    Sub Main()
        Dim SLN = "C:\Users\Adam\Downloads\roslyn-master\Compilers.sln"
        Dim res = <results></results>
        Dim sw As New Diagnostics.Stopwatch
        Dim ws = MSBuild.MSBuildWorkspace.Create()
        Dim tsk = ws.OpenSolutionAsync(SLN) ` <-- Exception happens here.
        tsk.Wait()
        Dim soln = tsk.Result
        For Each p In soln.Projects
            If p.Language <> LanguageNames.VisualBasic Then Continue For
            Dim pn = <Project name=<%= p.Name %> path=<%= p.OutputFilePath %>></Project>
            Console.WriteLine($"{p.Name} [{p.OutputFilePath}])")
            For Each d In p.Documents
                If d.SourceCodeKind = SourceCodeKind.Regular Then
                    Dim st As SourceText = d.GetTextAsync.Result
                    sw.Restart()
                    Dim sn = SyntaxFactory.ParseSyntaxTree(st)
                    sw.Stop()
                    Dim tn = <doc timing=<%= sw.ElapsedMilliseconds %> name=<%= d.Name %>/>
                    pn.Add(tn)
                End If
            Next
            res.Add(pn)
        Next
        Console.WriteLine(res.ToString)
        Console.ReadKey()
    End Sub

End Module
```

**Comment by AdamSpeight2008** [comment] 2015-12-03 16:47
Note: If I run this code with the SLN set to its own solution file, it works.

**Comment by AdamSpeight2008** [comment] 2015-12-03 17:41
@Pilchie  Don't think this is an issue with IDE, but the workspace.

**Comment by gafter** [comment] 2015-12-03 17:52
Note: this is blocking progress on #6305

**Comment by mattwar** [comment] 2015-12-03 19:06
This is a known problem that was fixed long ago.  It was caused by merger of C# and VB msbuild code into the same dll (workspace desktop), which caused a by-pass for a check to see if the language associated with the project being loaded existed in the MEF composition.  The actual exception can no longer occur, because the GetReferences API that is throwing the null ref no longer exists as that code was refactored long ago too.  Instead, you should be getting a different exception (if you run on newer roslyn, post RTM 1.0) that tells you that the language is unknown.  

The actual cause is that the VB or C# workspace dll is not installed where the rest of roslyn is. These are loaded dynamically at runtime, and it is otherwise correct for one or the other to be missing.

**Comment by Pilchie** [comment] 2015-12-03 21:03
The IDE Team owns the workspace API.  See https://github.com/dotnet/roslyn/wiki/Labels-used-for-issues for how we use labels.

**Comment by AdamSpeight2008** [comment] 2015-12-03 21:54
@mattwar  I'm using the latest public update available to the community edition.

**Comment by mattwar** [comment] 2015-12-04 00:14
@AdamSpeight2008 You don't need to fix. You just need to have the C# & VB workspace dll's in the directory of your app at runtime.

**Comment by gafter** [comment] 2015-12-06 23:00
@AdamSpeight2008 Since you have been reporting the output of this program to us, I am closing this as solved.

**Closed by gafter** 2015-12-06 23:00 UTC
Labels: Area-IDE, Bug, Contributor Pain

**Comment by AdamSpeight2008** [comment] 2015-12-06 23:42
If you build as a VB project and don't include a reference to the C# code analysis dll
*There isn't any indication that you do need to reference it.*
 Then you get that runtime error.

**Comment by mattwar** [comment] 2015-12-07 03:16
You'll only get the error if you are attempting to open a project for a language whose workspace dll is not in the same directory as your exe. So if you are only opening VB projects and you have the vb dll's but not the C# dll's it should work without error.  It's easiest if your app has a direct reference to both C# and VB dll's and have those dll's automatically copied to your application output directory.
