### ISSUE TITLE
Completion completes items innapropriately when trying to type range `..` operator.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#49185] opened 2020-11-05 00:38 UTC
For example:

![image](https://user-images.githubusercontent.com/4564579/98182968-f6025e00-1ebb-11eb-9633-a5fe5c4d1aaa.png)

Code:

```c#
    void Foo(ReadOnlySpan<char> url)
    {
        int startIndex = 0, endIndex = 0;
        var span = url[startIndex]  //<-- type `..` after startIndex
    }
```

This completes out an item, rather than allowing the user to type a range operator.  We likely need something akin to 'suggestion' mode here like we do for lambdas.  In other words, if this is a context where a range is legal, then jump into suggestion mode after an `int/Index` as they might be creating one of those.

**Comment by genlu** [comment] 2020-11-05 01:33
Hmm, I thought this was fixed by @ivanbasov a long time ago. Will take a look.

**Comment by Youssef1313** [comment] 2020-11-05 11:37
@genlu Yep, that was in #35749. Which is already tested:

https://github.com/dotnet/roslyn/blob/a13ee2c8204dc055047acbf4e7b9cfb0d2afb8bd/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb#L6219-L6243

**Comment by Youssef1313** [comment] 2020-11-05 16:37
Added test in #49191, but cannot reproduce the issue in the test.

**Comment by sharwell** [comment] 2020-11-05 16:43
@CyrusNajmabadi it looks like you have IntelliCode enabled, which modifies the way completion is shown. Can you try reproducing with that extension disabled?

**Comment by genlu** [comment] 2020-11-05 18:24
FYI @vivlimmsft

**Comment by vivlimmsft** [comment] 2020-11-10 00:03
This looks like a duplicate of #44862. I think this is an issue with IntelliCode's completion provider, and opened internal bug 1244362.

I meant to open a bug when this was reported a month ago, but I must've forgotten to. Sorry about that!

**Comment by sharwell** [comment] 2020-11-10 04:51
Duplicate of #44862

**Closed** 2020-11-10 04:51 UTC
Labels: Area-IDE, IDE-IntelliSense, Resolution-Not Reproducible
