### ISSUE TITLE
??= operator in C# 8 marks parameter as unused

### ISSUE THREAD

**Issue by Trojaner** [dotnet/roslyn#36079] opened 2019-05-31 01:55 UTC
Expected Behaviour: 
Parameters reassigned with ??= should be marked as used and referenced.

Actual Behaviour:
Parameters reassigned with ??= are marked as unused.

Screenshot 1: Parameter "user" is marked as "used" when not using ??= but the conventional way instead
![grafik](https://user-images.githubusercontent.com/1809172/58676206-0970d780-8360-11e9-8c94-cef72a5cc1c3.png)

Screenshot 2: Parameter "user" is marked as "unused" when using ??=
![grafik](https://user-images.githubusercontent.com/1809172/58676217-168dc680-8360-11e9-811a-c50fd5b1d5a1.png)

(Note: the "user" variable is referenced in code after the screenshots)

**Comment by jcouv** [comment] 2019-05-31 17:36
What version of VS are you using?
Might you be able to provide a self-contained code snippet to repro the issue?

I've tried the following in 16.2p2 and did not see the problem:
![image](https://user-images.githubusercontent.com/12466233/58723854-efe78400-838f-11e9-9ef7-7f6f25b3e104.png)

**Comment by jcouv** [comment] 2019-05-31 17:44
FYI @333fred

**Comment by Trojaner** [comment] 2019-05-31 17:46
> What version of VS are you using?
16.0.2

**Comment by 333fred** [comment] 2019-05-31 21:43
@mavasani, is this something that you fixed in later versions of VS?

**Comment by mavasani** [comment] 2019-05-31 21:44
Yes, should be fixed in 16.1

**Comment by 333fred** [comment] 2019-05-31 21:45
Probably a dupe of https://github.com/dotnet/roslyn/issues/33949.

**Comment by 333fred** [comment] 2019-05-31 21:46
@Trojaner can you see if the issue repros in 16.1?

**Comment by jcouv** [comment] 2019-05-31 21:46
Ok. I think we can call this confirmed and fixed. We can close
Thanks!

**Closed by jcouv** 2019-05-31 21:46 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
