### ISSUE TITLE
Code using collection expression that compiled in .NET 8/.NET 9 preview.1 produces CS9215 in .NET 9 preview.2

### ISSUE THREAD

**Issue by martincostello** [dotnet/roslyn#72668] opened 2024-03-22 12:15 UTC
**Version Used**: .NET SDK 9.0.100-preview.2.24157.14

**Steps to Reproduce**:

<details>

<summary>Repro.csproj</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
```

</details>

<details>

<summary>Repro.cs</summary>

```csharp
namespace CS9215Repro;

public class Repro
{
    public static TheoryData<Func<string>> TestCases()
    {
        return
        [
            new(() => "a"),
            new(() => "b"),
            new(() => "c"),
        ];
    }

    [Theory]
    [MemberData(nameof(TestCases))]
    public void Test(Func<string> generator)
    {
        var value = generator();
        Assert.NotNull(value);
    }
}
```

</details>

**Diagnostic Id**: `IDE0028`

**Expected Behavior**:

The code compiles.

**Actual Behavior**:

The code produces an CS9215 error in .NET 9 preview 2:

```console
❯ dotnet build
Restore complete (0.3s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  Repro failed with errors (0.4s)
    C:\Coding\martincostello\_scratch\Repro.cs(8,9): error CS9215: Collection expression type must have an applicable instance or extension method 'Add' that can be called with an argument of iteration type 'object[]'. The best overloaded method is 'TheoryData<Func<string>>.Add(Func<string>)'. [C:\Coding\martincostello\_scratch\Repro.csproj]
    C:\Coding\martincostello\_scratch\Repro.cs(8,9): error CS1503: Argument 1: cannot convert from 'object[]' to 'System.Func<string>' [C:\Coding\martincostello\_scratch\Repro.csproj]
    C:\Coding\martincostello\_scratch\Repro.cs(9,13): error CS8754: There is no target type for 'new(lambda expression)' [C:\Coding\martincostello\_scratch\Repro.csproj]
    C:\Coding\martincostello\_scratch\Repro.cs(10,13): error CS8754: There is no target type for 'new(lambda expression)' [C:\Coding\martincostello\_scratch\Repro.csproj]
    C:\Coding\martincostello\_scratch\Repro.cs(11,13): error CS8754: There is no target type for 'new(lambda expression)' [C:\Coding\martincostello\_scratch\Repro.csproj]

Build failed with errors in 1.3s
```

With .NET SDK 8.0.203, it compiles:

```console
❯ dotnet build
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Repro -> C:\Coding\martincostello\_scratch\bin\Debug\net8.0\Repro.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.43
```

Additionally, if the code is changed to the below so it compiles with .NET 9 preview 2:

```csharp
public static TheoryData<Func<string>> TestCases()
{
    return new()
    {
        () => "a",
        () => "b",
        () => "c",
    };
}
```

then an IDE0028 warning suggests refactoring it to use collection expressions. Applying the code fixer then generates the following code, which does not compile with .NET 8 or 9:

```csharp
public static TheoryData<Func<string>> TestCases()
{
    return
    [
        () => "a",
        () => "b",
        () => "c",
    ];
}
```

Either the compiler has regressed and no longer compiles the valid code, or the IDE0028 analyser should not suggest changing the code to something that won't compile and/or the analyzer should generate code that does compile.

**Comment by jaredpar** [comment] 2024-03-26 20:37
Duplicate of #72098

**Closed by jaredpar** 2024-03-26 20:37 UTC
Labels: Area-Compilers, untriaged
