### ISSUE TITLE
The project context navigation bar doesn't cause classification to update.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5343] opened 2015-09-18 21:45 UTC
**Short project setup (internal only)**:
1. Copy the `Closed\Test\Files\SharedProjectCS` directory from our internal sources to another location (e.g., Desktop.)
2. Open `TestProj.sln`.
3. Open `Class2.cs` from the shared project.

**Long project setup (manual)**:
1. Create a new Windows app.
2. Add a new WindowsPhone app to the solution.
3. Add a shared project to the solution that both Windows and WindowsPhone apps reference.
4. Add a file to the shared project with the body:

``` C#
namespace TestNamespace
{
    public class TestClass
    {
        #if WINDOWS_PHONE_APP
        public void PhoneMethod(bool b) { }
        #elif WINDOWS_APP
        public void WinMethod(int i) { }
        #endif
    }
}
```

**Rest of the repro steps**:
1. With the shared file open, verify that changing the project context navigation bar causes the classification inside the `#if/#elif/#endif` block to change.
2. Close the shared file.
3. Re-open the shared file.
4. Change the project context navigation bar.

**Result**:
The classification no longer changes.

_(This failure is visible in the internal-only `CSharpSharedProjects` integration test.)_

**Comment by Pilchie** [comment] 2015-09-21 16:19
This used to work.  Did your recent tagger changes lose the event that fires this here.

**Comment by CyrusNajmabadi** [comment] 2015-10-05 18:50
I don't think this shouldn't be related to anything I did.  First, the syntactic classifier is its own little tagger microcosm.  It's all hand written and doesn't use any of the normal tagger infrastructure.  Second, the semantic classifier still listens for ```OnDocumentActiveContextChanged``` (which I presume is the event that tells you when the project context changes).

I'll have to investigate to figure out what's going on here.

**Comment by CyrusNajmabadi** [comment] 2015-10-07 20:07
This works for me *if* I use the constant WINDOWS_UWP instead of WINDOWS_APP.  We get the appropriate notification that the context has changed.  So it just appears to be a different constant name now.  Here are the constants defined in the Windows app:

![image](https://cloud.githubusercontent.com/assets/4564579/10349639/5a544cee-6cf4-11e5-83e7-5735f6c01dc5.png)

So... it seems like this is working "as intended" form the LS perspective.  Now whether or not WINDOWS_APP should be defined is another matter and may need to be investigated.

**Comment by brettfo** [comment] 2015-10-09 16:39
It looks like our test is using old constants and needs to be updated to use `WINDOWS_UWP` instead of `WINDOWS_APP` and I can work on that, but there's still the issue where after re-opening the shared file, switching the context dropdown doesn't cause the `#region`s to be updated until the file is closed and re-opened.

**Comment by Pilchie** [comment] 2015-10-15 22:39
We've been looking at this a bit, and think that David has more context

**Comment by CyrusNajmabadi** [comment] 2015-10-16 00:10
I aready created a fix and test FYI :)

**Comment by dpoeschl** [comment] 2015-11-02 07:44
A bunch of things aren't getting cleaned up when a shared file is closed, including the Workspace's _bufferToDocumentInCurrentContextMap. A quickly thrown together _bufferToDocumentInCurrentContextMap cleaning mechanism does make this repro work correctly. The known ```HierarchyEventSink``` proliferation problem is also involved here in a way that causes multiple workspace events when the context is triggered, but just fixing _bufferToDocumentInCurrentContextMap makes sure those repeated events fire with the right Document. We'll need to fix both issues soon, but the _bufferToDocumentInCurrentContextMap is more urgent as it has obvious customer impact.

**Comment by davkean** [comment] 2015-12-09 00:16
Please note that CSharpSharedProjects is currently disabled because of this.

**Comment by dpoeschl** [comment] 2016-05-02 20:59
From internal bug 194709:

Here’s a repro in VS 2015 Update 1:
 
1.       Open a solution that has a shared project used by two platforms
2.       Open a shared file, select “platform A” at the top of the editor window
3.       Close that editor window
4.       Build the solution in a way that the compilation output window has error in a shared file, for the platform that was not selected at step 2 (Platform B)
5.       Open the shared file by double clicking the line in the output window
6.       The editor window should open by default in “Platform A”
7.       Try changing to “platform B”, then click in the editor’s text zone
8.       Notice that the platform selector reverts back to “Platform A”

**Comment by mavasani** [comment] 2016-11-07 19:57
Note: This also affects cross targeting CPS projects- we need to fix this for RC.2. @srivatsn

**Comment by Pilchie** [comment] 2017-01-20 16:37
Moving to 2.1 as we still haven't heard feedback about this.

**Comment by davkean** [comment] 2017-02-09 01:04
Feedback here: https://github.com/dotnet/roslyn-project-system/issues/1013.

**Comment by davkean** [comment] 2017-02-09 01:10
The internal bug 194709 is also from external feedback.

**Comment by onovotny** [comment] 2017-02-09 03:52
I see that this bug is pretty old. I realize it's too late for 2017 RTM but please don't keep pushing it back, please see if you can get it into the first update.

It makes it really hard to work with cross-compiled projects when the context is missing.

**Comment by NickCraver** [comment] 2017-02-22 00:10
Echoing Oren here, in getting this every day and it's extremely annoying. It turns Visual Studio into notepad for the #ifdef sections that it bugs on. Please give this bug the severity of the impact it has.

**Comment by mavasani** [comment] 2017-02-23 23:17
Marking as Urgency soon, we have got large number of feedback requests about this.

**Comment by mavasani** [comment] 2017-02-28 00:11
@dpoeschl I investigated this further and have a working fix. I am going to grab this bug from you and request a PR review from you :)

**Closed** 2017-03-02 21:05 UTC
Labels: Area-IDE, Bug, Disabled Test, Urgency-Soon
