### ISSUE TITLE
CodeLens marker for inheritance relations (derived types for classes and interfaces, overriden methods, for methods)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44492] opened 2020-05-21 18:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1014536/code-lens-marker-for-inheritance-relations-derived.html)._

---
Code lens shows "references" markers for types and methods, but that is too broad of a category. I would find it more helpful if it also showed inheritance relationshipes between types, and overriden methods. It would cut the time I waste finding those by hand.

---
#### Visual Studio Feedback System on 5/4/2020, 02:23 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment] 2020-05-21 18:38
Perhaps we can revisit the gutter icons for this experience. Similar to @sharwell's extension to show icons for the following:

1.	Inherited 
2.	Inherited + Override 
3.	Implementation 
4.	Implementation + Override

**Comment by sharwell** [comment] 2020-05-21 19:58
Duplicate of #32149

**Closed by sharwell** 2020-05-21 19:58 UTC

**Comment by CyrusNajmabadi** [comment] 2020-05-21 21:43
> Perhaps we can revisit the gutter icons for this experience. 

Yes please.  My original impl provides ways in teh gutter to navigate teh full inheritance hierarchy (i.e. you could walk up and down it).  I would love to have that again.

**Comment by mikadumont** [comment] 2020-05-21 23:05
Working with UX to get the icons approved for this.
