### ISSUE TITLE
Proposal: Create the output assembly when there are compilation errors

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#305] opened 2015-02-08 11:30 UTC
When refactoring a large codebase, you will occasionally get into situations when there will be a few days before you have resolved all errors, and many lines will need to be commented out just in order to make the source code compile so it can be tested.

My idea is to create a compiler switch -errors-as-warnings which would cause an output assembly to be generated regardless of warnings, with all instances of errors replaced with throw new CompilationErrorException(...). Example:
```
class C {
    public static void Main() {
        blah();
    }
}
```
could be emitted as if the program was
```
class C {
    public static void Main() {
        throw new CompilationErrorsException("CS0103", "The name 'blah' does not exist in the current context");
    }
}
```

I think this feature could potentially alleviate or even eliminate one of the biggest advantages dynamic languages might have over C#.

(from http://roslyn.codeplex.com/discussions/573979)

**Comment by gafter** [comment] 2015-10-17 00:19
This is particularly useful for generating a *reference assembly* when there are errors in the sources. It allows more efficient cross-project builds in the IDE, and it supports producing reference assemblies from "skeleton" source.

**Comment by jaredpar** [comment] 2015-11-30 21:11
Thank you for reporting this issue.  It does look like a duplicate of the reference assembly proposal.  Letting that be the main tracking issue going forward.

https://github.com/dotnet/roslyn/issues/2184

**Closed by jaredpar** 2015-11-30 21:11 UTC
Labels: Area-Compilers, Feature Request
