### ISSUE TITLE
Auto formatting C# code with list assignments does not indent correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73541] opened 2024-05-17 13:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-formatting-C-code-with-list-assign/10659494)._

---
[severity:It bothers me. A fix would be nice]
If I auto format code with an assignment of an enumerable like a List, both the brace preferences (keep braces on same/new line) and the content indentation is ignored.

Example:
When I auto format this code
![Unformatted.png](https://aka.ms/dc/image?name=Bcc8d5c556c6d43d0971ba82abdd72f8b638513714546769595_Unformatted.png&tid=cc8d5c556c6d43d0971ba82abdd72f8b638513714546769595)

I'm getting this result
![Formatted.png](https://aka.ms/dc/image?name=B439b36a3f2494948a867760508cf19f7638513714825870036_Formatted.png&tid=439b36a3f2494948a867760508cf19f7638513714825870036)

Both the old syntax with {} as well as the new [] syntax fails but slightly differently.

I don't have any editor config and I'm using C# default style preference.

Switching between space and tab indentation makes non difference.

---
#### Feedback Bot on 5/15/2024, 08:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment] 2024-06-19 01:04
Believe this is a duplicate of https://github.com/dotnet/roslyn/issues/8269
We currently don't format inside collection initalizers.

**Closed by dibarbet** 2024-06-19 01:04 UTC
Labels: Area-IDE, untriaged
