### ISSUE TITLE
Stop throwing XmlException for GetDescriptionAsync 

### ISSUE THREAD

**Issue by skadefro** [dotnet/roslyn#40531] opened 2019-12-20 14:52 UTC
**Version Used**: 3.4.0.0

**Steps to Reproduce**:
1. Create an AdhocWorkspace
2. Add a project and a simple c# or VB document
3. GetDescriptionAsync for each suggestion from completionService.GetCompletionsAsync results in a first chance System.Xml.XmlException exception per result, slowing down UI significantly.
Example project for both VB and C# provided at https://github.com/skadefro/IntelliTest

**Expected Behavior**:
No XmlException getting thrown and catched
**Actual Behavior**:
A first chance System.Xml.XmlException is thrown and catched per result

**Comment by sharwell** [comment] 2019-12-20 14:54
Duplicate of #38779

**Closed by sharwell** 2019-12-20 14:54 UTC
