### ISSUE TITLE
Struct record have unexpected initialization behavior

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#68125] opened 2023-05-06 21:07 UTC
App:

```csharp
ScrollData one = new(Direction.LeftToRight);
ScrollData two = new();
ScrollData three = new(Direction.RightToLeft);

Console.WriteLine(one);
Console.WriteLine(two);
Console.WriteLine(three);


public record struct ScrollData(Direction Direction = Direction.RightToLeft, bool CanReset = true);

public enum Direction
{
    RightToLeft,
    LeftToRight
}
```

Result:

```
ScrollData { Direction = LeftToRight, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = False }
ScrollData { Direction = RightToLeft, CanReset = True }
```

If I change to class structs, I get the expected behavior.

```
ScrollData { Direction = LeftToRight, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = True }
```

Am I missing something about the way record structs (or structs in general) work? I see the same behavior with .NET 7 and 8 (using the .NET 8 SDK). I didn't try with .NET 6.

**Comment by cston** [comment] 2023-05-07 00:12
When the type is declared as a `struct`, `new()` binds to the implicit parameterless constructor rather than the explicit constructor, even though the explicit constructor has all optional parameters. When declared as a `class`, there is no parameterless constructor, so `new()` binds to the explicit constructor, with optional parameter values.

**Comment by CyrusNajmabadi** [comment] 2023-05-07 00:53
Closing out as by design.  Longstanding behavior of structs.

**Closed by CyrusNajmabadi** 2023-05-07 00:53 UTC
Labels: Area-Compilers, untriaged

**Comment by richlander** [comment] 2023-05-07 04:58
Thanks! Didn't know that. TIL.
