### ISSUE TITLE
ITypeSymbol.NullableAnnotation is NotAnnotated for System.Linq.Enumerable.FirstOrDefault's return type

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#75119] opened 2024-09-14 10:43 UTC
When running an analyzer on a project targeting .NET Standard 2.0, and checking the return type of a invocation of FirstOrDefault (`TSource FirstOrDefault<TSource>(this IEnumerable<TSource> source)`), LastOrDefault or SingleOrDefault, then I get NullableAnnotation = NotAnnotated . I was under the impression that .NET Standard 2.0 pre-dated NRT and therefore assumed that NullableAnnotation would be None in this situation.

The same thing is observed inside Visual Studio 17.11.2: If I call FirstOrDefault on for example an array of strings, assign the return value to a variable and hover of the variable, then VS says "is not null here". If I change target framework to e.g. .NET 8.0, it changes to the expected "may be null here".

Could you shed some light on the situation? How come NotAnnotated is returned? This seems like a bug somewhere to me.

**Comment by bjornhellander** [comment] 2024-10-01 19:39
Absolutely! The easiest to show is the behavior in VS, which I assume has the same root cause as the NullableAnnotation property being NotAnnotated in the analyzer. Maybe we can start there at least?

![image](https://github.com/user-attachments/assets/1a380d42-e2ee-4d5e-8273-698bb092a288)

This is from a small .net standard 2.0 class library.

The tooltip is obviously wrong. I expected no tooltip at all.

Now, this example is compiled with `<Nullable>enable</Nullable>` in the csproj. If I remove that, then the tooltip is no longer shown. But I would have assumed that the compiler should "know that it doesn't know" even with `<Nullable>enable</Nullable>`.

This is all under the assumption that there should be no nullability info available for this method when compiling against .net standard 2.0.

**Comment by jaredpar** [comment] 2024-10-01 21:34
Here is the sample that I'm using here: 

```csharp
    var code = """
        using System;
        using System.Collections.Generic;
        using System.Linq;
        public class C
        {
            string M(IEnumerable<string> e)
            {
                var s = e.FirstOrDefault();
                return s;
            }
        }
        """;

    var syntaxTree = CSharpSyntaxTree.ParseText(code);
    var compilation = CSharpCompilation.Create(
        "scratch",
        new[] { syntaxTree },
        [Basic.Reference.Assemblies.NetStandard20.References.netstandard]);

    var context = compilation.GetSemanticModel(syntaxTree);
    var node = syntaxTree
        .GetRoot()
        .DescendantNodes()
        .OfType<MemberAccessExpressionSyntax>()
        .First(x => x.Name.Identifier.Text == "FirstOrDefault");

    var info = context.GetSymbolInfo(node);
    if (info.Symbol is IMethodSymbol methodSymbol)
    {
        Console.WriteLine(methodSymbol.ReturnType.NullableAnnotation);
    }
    Console.WriteLine();
```

When I do this I get the result of `None` which is what I would expect here. I suspect that there is something subtly different about your setup that is causing `NotAnnotated` to appear here. Likely using a difference reference assembly?

**Comment by bjornhellander** [comment] 2024-10-02 05:43
I had a problem with how you got the MetadataReference, but got it working with slightly different code. Here it is as a test case:

```
[TestClass]
public class AbcTests
{
    [TestMethod]
    public async Task T1()
    {
        var code = """
    #nullable enable

    using System;
    using System.Collections.Generic;
    using System.Linq;
    public class C
    {
        string M(IEnumerable<string> e)
        {
            var s = e.FirstOrDefault();
            return s;
        }
    }
    """;

        var syntaxTree = CSharpSyntaxTree.ParseText(code);
        var compilation = CSharpCompilation.Create(
            "scratch",
            new[] { syntaxTree },
            await ReferenceAssemblies.NetStandard.NetStandard20.ResolveAsync(LanguageNames.CSharp, default).ConfigureAwait(false));

        var context = compilation.GetSemanticModel(syntaxTree);
        var node = syntaxTree
            .GetRoot()
            .DescendantNodes()
            .OfType<MemberAccessExpressionSyntax>()
            .First(x => x.Name.Identifier.Text == "FirstOrDefault");

        var info = context.GetSymbolInfo(node);
        Assert.IsNotNull(info.Symbol);
        var methodSymbol = (IMethodSymbol)info.Symbol;
        Assert.AreEqual(NullableAnnotation.None, methodSymbol.ReturnType.NullableAnnotation);
    }
}
```

Notice the `#nullable enable` that I added in the tested source. This fails as it is. Passes if I remove it again.

**Comment by jaredpar** [comment] 2024-10-02 15:52
@RikkiGibson, @cston why does the annotation change here based on the presence of `#nullable enable`? This is from metadata so that surprised me a bit.

**Comment by RikkiGibson** [comment] 2024-10-02 16:53
I think what is happening is:
- when nullable analysis is enabled, the argument's type becomes `IEnumerable<string!>!`.
- then, call to `FirstOrDefault` is reinferred and gets a return type of `string!`.
- the reinferred symbol is stored and returned from the public APIs.

#44063 and several other issues track improvements to handling of oblivious nullability, which possibly could be leveraged here, because the return type `T` in the original definition of this `FirstOrDefault` is oblivious.

**Comment by jaredpar** [comment] 2024-10-02 17:22
Ah yes, it's cause we end up substituting a type which is `NotAnnotated` and that is why the return flips. This behavior is overall "By Design" so closing but can follow up on ways to get to the other  info in the linked issue.

**Closed by jaredpar** 2024-10-02 17:22 UTC
Labels: Area-Compilers, untriaged

**Comment by RikkiGibson** [comment] 2024-10-02 21:59
One solution that many library devs have been using is to multi-target to a recent framework like `net8.0` or higher in addition to netstandard. Then, the newer framework build will give you nullable warnings from the standard library.
