### ISSUE TITLE
Make Visual Studio suggest explicit type instead of var when ToList is called

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31020] opened 2018-11-07 18:11 UTC
Migrated from <a href="http://visualstudio.uservoice.com/forums/121579/suggestions/18612712">Visual Studio IDE UserVoice forum</a> <br><br> Currently when the .editorconfig or the Visual Studio settings say that the code should prefer var when the type is apparent Visual Studio suggest that I change code like this

List test = Enumerable.Range(1, 2).Select(i =&gt; i.ToString()).ToList();

I should use var because the type is apparent. It does this even when I have code like GetItems().ToList(); While calling ToList makes it apparent that the type is a List it is not the List that I care about, it is the T. This is a clearly a case where if the type should be explicit (assuming the user set csharp_style_var_when_type_is_apparent = true). Please provide a fix to this behavior. In addition code like this

MessageProcessorBase messageProcessor = MessageProcessorBase.GetMessageProcessor(eventType);

Now triggers a suggestion to use var. While the type is indeed mentioned on the right I am calling a static method and it may have returned something else.

Please change this behavior or provide additional option for this corner cases so users can configure them as they see fit.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/351488/make-visual-studio-suggest-explicit-type-instead-o.html
VSTS ticketId: 700567_
_These are the original issue comments:_

Fiona Niu[MSFT] on 10/9/2018, 10:45 PM (28 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about two weeks on our next steps.</p>

**Comment by kendrahavens** [comment] 2018-11-07 18:17
The first case mentioned using:
 `List<string> test = Enumerable.Range(1, 2).Select(i => i.ToString()).ToList();`
is fixed in Visual Studio 2017 Update 15.8.
![image](https://user-images.githubusercontent.com/8293542/48151424-19b34f00-e276-11e8-8408-4823aec3b101.png)


The MessageProcessorBase example still behaves as described above.

**Comment by CyrusNajmabadi** [comment] 2018-11-07 18:20
@kendrahavens I think the request is asking for the opposite.  I believe the person filing the bug feels like that the type should **not** be considered apparent, and should be `List<string>` in this case.  

This issue is already being tracked here: https://github.com/dotnet/roslyn/issues/29657

**Comment by sharwell** [comment] 2018-11-07 18:54
Duplicate of #29657

**Closed by sharwell** 2018-11-07 18:54 UTC
