### ISSUE TITLE
CodeLens reference count ignores InternalsVisibleTo

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#1721] opened 2015-04-01 04:38 UTC
Environment: VS2015 CTP6, Windows 8.1, x64.

If a member in assembly A1 is only visible to assembly A2 due to `[assembly:IntervalsVisibleTo("A2")]` then the CodeLens reference count won't include references from A2 to members of A1.

Sample code (would attach a zip file, but it's not supported):

Library assembly (a class library)

```csharp
[assembly:InternalsVisibleTo("Client")]
namespace Library
{
    internal class Sample
    {
        internal static void FindMe() {}
    }
}
```

Client assembly (a console app)

```csharp
using Library;

namespace Client
{
    class Program
    {
        static void Main(string[] args)
        {
            Sample.FindMe();
        }
    }
}
```

It builds fine, and VS definitely knows what `FindMe` refers to - F12 goes to the right place - but while either `Sample` or `FindMe` is internal, CodeLens shows 0 references. Change them both to be public, and CodeLens shows 1 reference.

**Comment by Pilchie** [comment] 2015-04-01 05:03
Interesting. @balajik can you take a look?  @jonskeet was seeing this with CTP6.

**Comment by Pilchie** [comment] 2015-04-01 05:04
What?  Why is you handle @jskeet?  That's just wrong :smile:

**Comment by balajikris** [comment] 2015-04-01 17:14
Yep, interesting, I'll take this :smiley:

**Comment by balajikris** [comment] 2015-04-09 00:36
Hmm, the specified example seems to work for me in the latest drops. screenshot below. @jskeet do you mind emailing me (<balajik@microsoft.com>) the zip?  It is possible that I'm missing something here, as I do not recall any changes around this from CTP6 to date :smile: 


![image](https://cloud.githubusercontent.com/assets/4213867/7058347/307e6c56-de15-11e4-8928-cb66f0676f2c.png)

**Comment by jskeet** [comment] 2015-04-09 06:16
Thanks @balajikris - will email you now. Here are my corresponding screenshots for the four different variants of accessibility (class and method). The screenshots were taking with R# active, but turning R# off completely doesn't change the CodeLen results, so I don't *think* it's related to that.

![internal-public](https://cloud.githubusercontent.com/assets/17011/7061318/34002b80-de88-11e4-95e6-b3f4456fb416.png)
![public-internal](https://cloud.githubusercontent.com/assets/17011/7061319/3422e44a-de88-11e4-9ac5-100fd41b709e.png)
![public-public](https://cloud.githubusercontent.com/assets/17011/7061320/3446f1be-de88-11e4-9dee-31338d7c2dcc.png)
![internal-internal](https://cloud.githubusercontent.com/assets/17011/7061321/346b61c0-de88-11e4-93fc-e5b93cc5a32f.png)

**Comment by balajikris** [comment] 2015-04-09 15:53
Thanks @jskeet . I did verify that codelens works well on the solution you shared. Must have been fixed by one of our recent changes to codelens.=

**Closed** 2015-04-09 15:54 UTC
Labels: Area-IDE, Bug

**Comment by balajikris** [comment] 2015-04-09 22:28
I was able to reproduce this on CTP6 and from the exception that was being thrown, I was able to ascertain that this was happening due to the same root cause issue that caused [connect bug 1165799](https://connect.microsoft.com/VisualStudio/feedback/details/1165799/connect-excessive-disk-io-usage-in-microsoft-alm-shared-remoting), which is one of the things we fixed after CTP6.
