### ISSUE TITLE
Allow shorthand/inferred assignment of class fields

### ISSUE THREAD

**Issue by HakanL** [dotnet/roslyn#20819] opened 2017-07-12 05:42 UTC
I have a framework where I create "scenes" in C#, basically to describe a business process. I have these as classes and in them I define a bunch of fields to be used inside the class to operate on the business process (it's actually controlling DMX lights with the description of what should happen to the lights (the field variables) in the scene throughout the various class methods). So I have code like this:

    public class MyScene
    {
        AnalogInput3 masterVolume = new AnalogInput3(persistState: true, defaultValue: 1.0);
        Controller.Subroutine sub3dfxRandom = new Controller.Subroutine();
    
        public void Execute()
        {
            masterVolume.Set(0.5);
        }
    }

**My suggestion is to allow the use of `var` instead of having to have the class type in here twice**, like we can do on stack variables, etc. So the code could be like this instead:

        var masterVolume = new AnalogInput3(persistState: true, defaultValue: 1.0);
        var sub3dfxRandom = new Controller.Subroutine();

Less typing, easier to read, less risk of error, and the compiler could easily infer the type.

Optionally it could also be used with readonly and access modifiers:

        readonly var masterVolume = new AnalogInput3(persistState: true, defaultValue: 1.0);
        private readonly var sub3dfxRandom = new Controller.Subroutine();

The goals of these classes (in my example) are to be as easy to read as possible (DSL), and allow the developer to focus on the functions of the scene with as little "plumbing" as possible.

**Comment by Joe4evr** [comment] 2017-07-12 06:37
Dupe of #2114, #4423, #11551, and now tracked at dotnet/csharplang#601 (where language proposals *should* go).

**Closed** 2017-09-08 23:40 UTC
Labels: Area-Language Design
