### ISSUE TITLE
VS 2022 & VS 2019 Color Scheme Change in Settings of one version of VS causes the same change in another VS version!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63337] opened 2022-08-11 18:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022--VS-2019-Color-Scheme-Change-in/10109669)._

---
[severity:It bothers me. A fix would be nice]
If I change VS color scheme in the settings of one version of VS (e.g. 2022), the same chage appears after I launch another VS version (e.g. 2019) and vice versa.

---
#### Feedback Bot on 8/2/2022, 06:09 PM: 

(private comment, text removed)
#### Feedback Bot on 8/4/2022, 00:13 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JoeRobich** [comment] 2022-08-11 18:08
This is expected behavior. The Editor Color Scheme setting is synced in the same way that Fonts and Colors changes are synced.

**Comment by CyrusNajmabadi** [comment] 2022-08-11 21:44
Closing out as by design.

**Closed by CyrusNajmabadi** 2022-08-11 21:44 UTC
Labels: Area-IDE, untriaged
