### ISSUE TITLE
Compiler incorrectly interprets ?? operator and reports CS8602 on later dereference

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#38791] opened 2019-09-21 14:09 UTC
**Version Used**: .NET Core SDK 3.0.100-rc1-014190

**Steps to Reproduce**:

```
git clone https://github.com/aarnott/Nerdbank.Streams.git
cd Nerdbank.Streams
git checkout efceb295908f8d5fe1904ed139347fcf12c0871e
dotnet build src
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

```
StreamPipeReader.cs(128,97): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
StreamPipeWriter.cs(98,97): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
MultiplexingStream.Channel.cs(252,25): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
MultiplexingStream.Channel.cs(592,21): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
MultiplexingStream.Channel.cs(252,25): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
StreamPipeWriter.cs(98,97): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
StreamPipeReader.cs(128,97): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
MultiplexingStream.Channel.cs(592,21): warning CS8602: Dereference of a possibly null reference. [D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Nerdbank.Streams.csproj]
```

Each of these warnings comes after a `??` operator. For example:

```cs
            if (this.flushCancellationSource?.IsCancellationRequested ?? true)
            {
                this.flushCancellationSource = new CancellationTokenSource();
            }

            using (var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, this.flushCancellationSource.Token))
```

The compiler flags the last dereference of `this.flushCancellationSource` as a possible null dereference even though the if check above guarantees otherwise.

**Comment by RikkiGibson** [comment] 2019-09-22 19:30
The fix for this is not in .NET Core 3/16.3, sorry. It will ship in 16.4. Same root cause as #37394.

**Closed by RikkiGibson** 2019-09-22 19:30 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-Duplicate
