### ISSUE TITLE
.NET Compiler Platform SDK DISABLED. 2.0.0.6140902 is not compatible with VS 2017 15.5.2

### ISSUE THREAD

**Issue by ramoneeza** [dotnet/roslyn#24122] opened 2018-01-09 11:40 UTC
Downloaded Roslyn.SDK from Marketplace is disabled in Visual Studio 2017 15.5.2

**Steps to Reproduce**:

1. Uninstall Roslyn.SDK
2. Download Roslyn.SDK from Marketplace (Version 2.0.0.6140902)
3. Start Visual Studio (Version 2017 15.5.2)

**Expected Behavior**:
.NET Compiler Platform enables and Roslyn Visualized Window enabled.

**Actual Behavior**:

Yellow icon:  This extension is disabled. Incompatible with Visual Studio.
![2018-01-09 12_40_06-extensiones y actualizaciones](https://user-images.githubusercontent.com/891592/34719244-4bf967b2-f53a-11e7-9707-05e64657d610.png)

**Comment by sharwell** [comment] 2018-01-09 15:14
Duplicate of external issue dotnet/roslyn-sdk#75

**Closed by sharwell** 2018-01-09 15:14 UTC
