### ISSUE TITLE
IntroduceVariableCodeRefactoringProvider error

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#24003] opened 2018-01-02 22:22 UTC
```
System.AggregateException : One or more errors occurred. ---> Unexpected Null
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.InvalidOperationException : Unexpected Null
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value,String message)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.InitializeOpenBuffers(SnapshotSpan triggerSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession..ctor(InlineRenameService renameService,Workspace workspace,SnapshotSpan triggerSpan,IInlineRenameInfo renameInfo,IWaitIndicator waitIndicator,ITextBufferAssociatedViewService textBufferAssociatedViewService,ITextBufferFactoryService textBufferFactoryService,IEnumerable`1 refactorNotifyServices,IAsynchronousOperationListener asyncListener)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService.StartInlineSession(Document document,TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.TryNavigateToLocationOrStartRenameSession(Workspace workspace,Solution oldSolution,Solution newSolution,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
```

**Version Used**: Visual Studio 15.5.2

**Steps to Reproduce**:

1. In this piece of code
``` C#
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "8"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "useAggregate"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "aggregationLevel"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:Avoid Excessive Locals")]
        [System.Web.Mvc.HttpPost]
        public virtual async Task<JsonResult> GetPerimetersList([FromUri]AggregationLevel aggregationLevel, [FromUri]int? universeId, [FromUri]string fromPage, [FromUri]int? status, [FromUri]bool? useAggregate, [FromBody]string textFilter, [FromUri]IList<int> scopeId, [FromUri]bool? autoLoaded, [FromUri]ThirdPartyDataModel thirdPartyDataModel, [FromBody]FilterForAxis filterForAxis, [FromUri] int? refresh, [FromUri] int? timeLevel, [FromUri] bool? stacked, [FromUri] bool? navigation)
        {
            string message = null;
            string messagethir = null;
            string email = User.Identity.Name;
            User user = await UserService.FindUserByEmailAsync(email);
            var universe = new Universe();

            switch (fromPage)
            {
                case "Reliability":
                    LoggerHelper.AddDataLogHistory(email, TenancyMapping.CustomerName, ActionList.SetScopeReliability, await UserService.GetAbsorbentProfileAsync(email));
                    break;
                case "History":
                    LoggerHelper.AddDataLogHistory(email, TenancyMapping.CustomerName, ActionList.SetScopeHistory, await UserService.GetAbsorbentProfileAsync(email));
                    break;
                case "Enrichments":
                    LoggerHelper.AddDataLogHistory(email, TenancyMapping.CustomerName, ActionList.SetScopeEnrichments, await UserService.GetAbsorbentProfileAsync(email));
                    break;
                case "Consensus":
                    LoggerHelper.AddDataLogHistory(email, TenancyMapping.CustomerName, ActionList.SetScopeConsensus, await UserService.GetAbsorbentProfileAsync(email));
                    break;
                case "Stability":
                    LoggerHelper.AddDataLogHistory(email, TenancyMapping.CustomerName, ActionList.SetScopeStability, await UserService.GetAbsorbentProfileAsync(email));
                    break;
                default:
                    break;
            }

            // TODO: Use StringBuilder
            if (status == null)
            {
                message += $"{fromPage}/All";
                messagethir += $"{fromPage}/All";
            }
            if (status == 2)
            {
                message += $"{fromPage}/ToValidate";
                messagethir += $"{fromPage}/ToValidate";
            }
            if (status == 3)
            {
                message += $"{fromPage}/NotTreated";
                messagethir += $"{fromPage}/NotTreated";
            }
            if (status == 4)
            {
                message += $"{fromPage}/Validated";
                messagethir += $"{fromPage}/Validated";
            }
            //For Simulation
            if (status == 1)
            {
                message += $"{fromPage}/All";
                messagethir += $"{fromPage}/All";
            }
            if (status == 5)
            {
                message += $"{fromPage}/Configured";
                messagethir += $"{fromPage}/Configured";
            }
            if (status == 6)
            {
                message += $"{fromPage}/ToConfigure";
                messagethir += $"{fromPage}/ToConfigure";
            }
            //For Universe
            if (useAggregate == true)
            {
                message += " NoUniverse"; //you have to add the new Perimeter
                messagethir += " NoUniverse";
            }
            if (universeId != null)
            {
                message += " UniverseId:" + universeId;
                messagethir += " WithUniverse";
            }
            if (!string.IsNullOrEmpty(textFilter))
            {
                message += " Filter:" + textFilter;
            }

            //refresh universeScope
            if (universeId > 0)
            {
                universe = await UserService.GetUniverseAsync((int)universeId);
                if (refresh > 0)
                {
                    await UserService.RefreshUniverseAsync(universe);
                }
                //refresh current unit && currency
                user.CurrentUnit = universe.DefaultUnit;
                user.CurrentCurrency = universe.Currency;
                await UserService.EditUserAsync(user);
            }

            ColibriPage page = GetCurrentColibriPage(fromPage);
            IList<AsideMenuPerimeter> asideMenuPerimeter = new List<AsideMenuPerimeter>();
            //IDictionary<PerimeterFilter, int> counted = new Dictionary<PerimeterFilter, int>();
            IList<ColibriScope> scopes = new List<ColibriScope>();
            //IList<object> perimetersCounted = new List<object>();
            string description = string.Empty;
            var userUniverses = await UserService.GetAvailableUniversesAsync(user, page, false); // UserService.GetUniverses(user);
            var isOwner = false;
            var selectedUniverse = 0;
            bool isSku = false;
            bool isThirdPartyData = false;
            string format = "MMM yy";
            int dateLevel = (timeLevel == null) ? 3 : (int)timeLevel; // Default value is 3 (for Month)
            double? highChartTicks = null; // Default value is 3 (for Month)
            bool fromNavigation = navigation ?? false;
            if ((userUniverses.Any()
             && ((universeId != null && !(useAggregate ?? false))
             || (!(useAggregate ?? false) && scopeId == null)))
             || (fromNavigation && !(useAggregate ?? false)))
            {
                selectedUniverse = universeId ?? userUniverses.First().UniverseId;

                isOwner = userUniverses.Any(u => u.UniverseId == selectedUniverse);

                universe = await UserService.GetUniverseAsync(selectedUniverse);
                //refresh current unit && currency
                if (selectedUniverse != universeId)
                {
                    user.CurrentUnit = universe.DefaultUnit;
                    user.CurrentCurrency = universe.Currency;
                    await UserService.EditUserAsync(user);
                }

                if ((universe.Axis1Level <= 1 || universe.Axis1Level == null) &&
                    (universe.Axis2Level <= 1 || universe.Axis2Level == null) &&
                    (universe.Axis3Level == 1 || universe.Axis3Level == null) &&
                    (universe.Axis4Level == 1 || universe.Axis4Level == null))
                {
                    isSku = true;
                }
                if (universe.Axis1Level != null)
                {
                    message += " AxisLevels:" + universe.Axis1Level;
                }
                if (universe.Axis2Level != null)
                {
                    message += "/" + universe.Axis2Level;
                }
                if (universe.Axis3Level != null)
                {
                    message += "/" + universe.Axis3Level;
                }
                if (universe.Axis4Level != null)
                {
                    message += "/" + universe.Axis4Level;
                }

                isThirdPartyData = universe.ThirdPartyDataDescription.Any();

                if (universe.TimeLevel != null)
                {
                    if (timeLevel == null)
                    {
                        dateLevel = universe.TimeLevel.Value;
                    }
                    format = await TimeLevelService.GetTimeFormatByLevelAsync(dateLevel);
                    highChartTicks = await TimeLevelService.GetHighChartsTicksByLevelAsync(dateLevel);
                }
                description = universe.Description ?? string.Empty;
                description = description.Replace("\n", "<br/>");
                if (isOwner || scopeId != null)
                {
                    int firstScope = 0;
                    if (scopeId != null && scopeId.Count() > 0)
                    {
                        firstScope = scopeId[0];
                    }
                    if (isOwner)
                    {
                        var scopeOfUniverse = await PerimeterService.GetScopeOfUniverseAsync(user,
                            selectedUniverse, textFilter, status ?? 1, fromPage,
                            TenancyMapping.ConnectionString);
                        if (scopeId != null && scopeId.Count() > 0)
                        {
                            scopes = scopeOfUniverse.Where(s => !scopeId.Contains(s.ScopeId))
                                                    .ToList();
                        }
                        else
                        {
                            scopes = scopeOfUniverse.ToList();
                        }
                    }

                    if (await UserService.CheckAuthorizationAsync(user, firstScope, fromPage != "Enrichments"))
                    {
                        if (scopeId != null && scopeId.Count() > 0)
                        {
                            for (int i = 0; i < scopeId.Count(); i++)
                            {
                                var scope = scopeId[i];
                                ColibriScope oneScope = await PerimeterService.GetOneScopeAsync(scope, TenancyMapping.ConnectionString);
                                if (oneScope != null)
                                {
                                    scopes.Insert(0, oneScope);
                                    //scopes.Add(oneScope);

                                }
                            }
                            //scopes = scopes.Reverse().ToList();
                        }
                    }
                }
            }
            else if (scopeId != null)
            // && !fromNavigation)
            {
                description = "Notification view";
                foreach (int scId in scopeId)
                {
                    if (await UserService.CheckAuthorizationAsync(user, scId, fromPage != "Enrichments"))
                    {
                        ColibriScope oneScope = await PerimeterService.GetOneScopeAsync(scId, TenancyMapping.ConnectionString);
                        if (oneScope != null)
                        {
                            scopes.Add(oneScope);
                        }
                    }
                }
            }
            else if ((useAggregate ?? false) && aggregationLevel != null)
            {
                description = "Aggregation view";
                /*if (!UserService.IsUserInProfile(user.Email, ColibriProfile.SenorForecaster))
                {
                    IList<int> minLevels = UserService.GetAccreditationsMinLevels(user, fromPage);
                    if (aggregationLevel.Axis1Level != 0) { aggregationLevel.Axis1Level += minLevels[0] - 1; }
                    if (aggregationLevel.Axis2Level != 0) { aggregationLevel.Axis2Level += minLevels[1] - 1; }
                    if (aggregationLevel.Axis3Level != 0) { aggregationLevel.Axis3Level += minLevels[2] - 1; }
                    if (aggregationLevel.Axis4Level != 0) { aggregationLevel.Axis4Level += minLevels[3] - 1; }
                }*/
                if (aggregationLevel.Axis1Level <= 1 && aggregationLevel.Axis2Level <= 1 &&
                    aggregationLevel.Axis3Level <= 1 && aggregationLevel.Axis1Level <= 1)
                {
                    isSku = true;
                }

                // TODO: Use StringBuilder
                if (aggregationLevel.Axis1Level != 0)
                {
                    message += " AggregationLevels:" + aggregationLevel.Axis1Level;
                }
                if (aggregationLevel.Axis2Level != 0)
                {
                    message += "/" + aggregationLevel.Axis2Level;
                }
                if (aggregationLevel.Axis3Level != 0)
                {
                    message += "/" + aggregationLevel.Axis3Level;
                }
                if (aggregationLevel.Axis4Level != 0)
                {
                    message += "/" + aggregationLevel.Axis4Level;
                }

                //counted = PerimeterService.CountAggregatePerimetersForEachStatus(user, aggregationLevel, string.Empty, (PerimeterFilter)(status ?? 1), fromPage, TenancyMapping.ConnectionString);
                scopes = await PerimeterService.GetAggregateScopeOfUniverseAsync(user, aggregationLevel, textFilter, (PerimeterFilter)(status ?? 1), fromPage, TenancyMapping.ConnectionString, filterForAxis);
            }
            string messagesec = null;
            messagesec += fromPage;

            if (autoLoaded == null || autoLoaded == false)
            {
                LoggerHelper.AddLogNoAggregation(TenancyMapping.CustomerName, messagethir, HttpContext.User.Identity.Name);
            }
            LoggerHelper.BusinessLogger.Info($"[{TenancyMapping.CustomerName}]: {User.Identity.Name}, {DateTime.Now}, Context: {message}");
            //foreach (var count in counted)
            //{
            //    perimetersCounted.Add(new
            //    {
            //        key = count.Key.ToString(),
            //        value = count.Value
            //    });
            //}

            var targetHash = string.Empty;
            var itemId = 0;

            foreach (var scope in scopes)
            {
                var codes = ScopeHelper.GetAxisCodes(scope);
                var url = string.Empty;
                for (int i = 0; i < codes.Count - 1; i++)
                {
                    url += codes[i] + "_";
                }
                url += codes[codes.Count - 1];

                asideMenuPerimeter.Add(new AsideMenuPerimeter
                {
                    Disabled = false,
                    UniverseId = selectedUniverse,
                    ScopeId = scope.ScopeId,
                    HasConfiguration = fromPage == "Simulation" && await ForecastService.FindForecastConfigurationAsync(scope.ScopeId, universeId ?? 0, false) != null,
                    Label = ScopeHelper.GetScopeRepresentation(scope, ", "),
                    SeparetedLabels = ScopeHelper.GetScopeRepresentation(scope, "<%> "),
                    PerimeterIds = ScopeHelper.GetAxisIds(scope),
                    PerimeterCodes = codes,
                    UrlEncode = HttpUtility.UrlEncode(url).ToUpper(CultureInfo.CurrentCulture),
                    Status = scope.Status,
                    ItemId = itemId,
                });
                itemId++;

                /*if (scopeId != null && scopeId.Count() > 0 && scope.ScopeId == scopeId[0])
                {
                    targetHash = HttpUtility.UrlEncode(url).ToUpper(CultureInfo.CurrentCulture);

                }*/
                if (fromNavigation && (scopeId != null && scopeId.Count() > 0 && scopeId.Contains(scope.ScopeId)))
                {
                    targetHash += HttpUtility.UrlEncode(url).ToUpper(CultureInfo.CurrentCulture);
                    targetHash += '&';
                }
                else if (scopeId != null && scopeId.Count() > 0 && scope.ScopeId == scopeId[scopeId.Count() - 1])
                {
                    targetHash = HttpUtility.UrlEncode(url).ToUpper(CultureInfo.CurrentCulture);
                }

            }
            ScopeIdList scopeList = new ScopeIdList();
            if (scopeId != null && scopeId.Count() > 0)
            {
                var selectedScopesName = asideMenuPerimeter.Where(amp => scopeId.Contains(amp.ScopeId)).Select(amp => amp.Label).ToList();
                var selectedScopesCode = asideMenuPerimeter.Where(amp => scopeId.Contains(amp.ScopeId)).Select(amp => '#' + amp.UrlEncode).ToList();
                scopeList.ScopeIds = scopeId;
                scopeList.ScopeNames = selectedScopesName;
                scopeList.ScopeCodes = selectedScopesCode;

            }
            for (int i = 0; i < asideMenuPerimeter.Count; i++)
            {
                for (int j = 0; j < asideMenuPerimeter[i].PerimeterCodes.Count; j++)
                {
                    asideMenuPerimeter[i].PerimeterCodes[j] = asideMenuPerimeter[i].PerimeterCodes[j].Replace("\"", "'");
                }
            }

            ViewBag.FromPage = fromPage;
            List<double> timeIds = new List<double>();
            if (fromPage == "ThirdPartyData")
            {
                var startDate = new DateTime(thirdPartyDataModel.StartTime.Ticks);
                if (startDate == new DateTime(1, 1, 1))
                {
                    startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                }
                for (var i = 0; i < thirdPartyDataModel.ThirdPartyDataDuration; i++)
                {
                    timeIds.Add(DateHelper.CreateTimestamp(startDate.AddMonths(i)));
                }
            }

            //var axisInformation = PerimeterService.GetAxisHierarchy(user, TenancyMapping.ConnectionString, aggregationLevel, PerimeterCacheService.FindPerimeters(TenancyMapping.CustomerName));
            // TODO: Fix when default unit is null
            UnitConfiguration unitConfiguration = (await SettingsService.GetUnitByIdAsync((int)universe.DefaultUnit));
            // TODO: Fix when currency is null
            ExchangeRate exchangeRate = (await SettingsService.GetExchangeRateByIdAsync((int)universe.Currency));
            return new JsonResult()
            {
                Data = new AsideMenuPerimeterModel
                {
                    Perimeters = asideMenuPerimeter,
                    SelectedUniverse = selectedUniverse,
                    UniverseOwner = isOwner,
                    IsSku = isSku,
                    //AxisInformation = axisInformation,
                    IsThirdPartyData = isThirdPartyData,
                    DateFormat = format,
                    DateLevel = dateLevel,
                    HighChartTicks = highChartTicks,
                    Description = "<strong>Description : </strong><br/>" + description,
                    TargetHash = targetHash,
                    TimeIds = timeIds,
                    SelectedScope = scopeList,
                    Stacked = stacked,
                    // SelectedScopeIds = scopeId,
                    //Scopes = scopes,
                    DefaultUnit = selectedUniverse == 0 ? 0 : (await UserService.GetUniverseAsync(selectedUniverse)).DefaultUnit ?? 0,
                    DefaultUnitCurrencyUniverse = universe.DefaultUnit != null
                        ? unitConfiguration.Name
                        : universe.Currency != null
                            ? exchangeRate.Label
                            : universe.UniverseId == 0
                                ? UnitHelper.GetDefaultUnitName(user,
                                    await SettingsService.GetAllUnitsConfigurationAsync(),
                                    await SettingsService.GetAllExchangeRateAsync())
                                : Resources.Resource.Quantity,
                    UnitCurrencyUniverseId = universe.DefaultUnit != null
                        ? "Unit-" + unitConfiguration.UnitRow.ToString(CultureInfo.CurrentCulture)
                        : universe.Currency != null
                            ? "Currency-" + exchangeRate.CurrencyId
                            : universe.UniverseId == 0
                                ? UnitHelper.GetDefaultUnitValue(user)
                                : "Unit-0",

                },
                MaxJsonLength = int.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
            };
        }
```

2. When I select `(useAggregate ?? false)` and try to introduce local for all occurrences
3. It fails and disables this refactoring

**Expected Behavior**:
Local variable introduced successfully

**Actual Behavior**:
Local variable is created but I cannot rename it

**Comment by sharwell** [comment] 2018-01-08 19:45
Duplicate of #7364, though possibly with a more reliable repro case

**Closed by sharwell** 2018-01-08 19:45 UTC
Labels: Area-IDE, Bug
