### ISSUE TITLE
Intellisense telling me to "Add 'this' or 'Me' qualification" to List initializer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30837] opened 2018-10-30 12:49 UTC
Given the following example C# class, visual studio will advise me to &quot;Add 'this' or 'Me' qualification&quot; with a squiggly under `foo` and `bar` in the list initialisation (see attached). 

```
public class Foo
{
    public void Bar()
    {
        string foo = "foo";
        string bar = "bar";

        List&lt;string&gt; list = new List&lt;string&gt;()
        {
            foo,
            bar
        };
    }
}
```

This is clearly wrong as none of the objects references are instance members. I do not want to flat out disable that advice, but this is causing a lot of noise in the error list.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/370799/intellisense-telling-me-to-add-this-or-me-qualific.html
VSTS ticketId: 719977_
_These are the original issue comments:_

BenM on ‎10‎/‎30‎/‎2018, 07:26 AM (23 min ago): <p>Not sure what happened with the example code, lets try again:</p><pre>public class Foo
\{
    public void Bar()
    \{
        string foo = "foo";
        string bar = "bar";
        List&lt;string&gt; list = new List&lt;string&gt;() 
        \{
            foo,
            bar
        };
    }
}
&lt;br&gt;</pre>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-11-06 18:38
Duplicate of #28091

**Closed by sharwell** 2018-11-06 18:38 UTC
Labels: Area-IDE
