### ISSUE TITLE
When you add using with Ctrl + . sometimes the using directive is not in correct order #400 

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn#9236] opened 2016-02-26 15:34 UTC
Moved from https://github.com/aspnet/Tooling/issues/400 originally posted by @ivaylokenov

If you have documentation summary on the class, and add new using with Ctrl + . operation, sometimes you may receive the following result:

```c#
    using Builders.Routes;
    using Internal.Application;    /// <summary>
                                   /// Starting point of the ASP.NET MVC testing framework, which provides a way to specify the test case.
                                   /// </summary>
    public static class MyMvc
    {
```

Documentation is not on a new line and the usings may not be sorted. Sometimes it is working, sometimes it does not and I am not quite sure on which conditions it fails.

**Comment by CyrusNajmabadi** [comment] 2016-02-26 19:24
Do you have an actual repro.  What was hte code before this change?  Which using is the one that you added?  What code did you have inside MyMVC that you used to trigger 'add using' on?

**Comment by ivaylokenov** [comment] 2016-02-28 09:18
@CyrusNajmabadi I do not have repro currently as the issue occurs quite "randomly". If I see it again, I will copy the code here so you can investigate.

**Comment by ivaylokenov** [comment] 2016-02-28 11:00
@CyrusNajmabadi Found one.

Initial code - `IMemoryCache` is not recognised:
```c#
namespace MyTested.Mvc.Builders.Data
{
    using Contracts.Data;

    /// <summary>
    /// Some random documentation.
    /// </summary>
    public class MemoryCacheTestBuilder : IAndMemoryCacheTestBuilder
    {
        public MemoryCacheTestBuilder(IMemoryCache memoryCache)
        {

        }

        public IMemoryCacheTestBuilder AndAlso()
        {
            return this;
        }
    }
}
```

I run Ctrl + . to add` IMemoryCache`'s using. Result is (new line is not added after usings):
```c#
namespace MyTested.Mvc.Builders.Data
{
    using Contracts.Data;
    using Microsoft.Extensions.Caching.Memory;
    /// <summary>
    /// Some random documentation.
    /// </summary>
    public class MemoryCacheTestBuilder : IAndMemoryCacheTestBuilder
    {
        public MemoryCacheTestBuilder(IMemoryCache memoryCache)
        {

        }

        public IMemoryCacheTestBuilder AndAlso()
        {
            return this;
        }
    }
}
```

I add another dependency - for example `ISession`. Everyting works fine (although new line is not added again):
```c#
namespace MyTested.Mvc.Builders.Data
{
    using Contracts.Data;
    using Microsoft.AspNetCore.Http.Features;
    using Microsoft.Extensions.Caching.Memory;
    /// <summary>
    /// Some random documentation.
    /// </summary>
    public class MemoryCacheTestBuilder : IAndMemoryCacheTestBuilder
    {
        public MemoryCacheTestBuilder(IMemoryCache memoryCache, ISession session)
        {

        }

        public IMemoryCacheTestBuilder AndAlso()
        {
            return this;
        }
    }
}
```

However, if I first add `ISession` and then `IMemoryCache`, result is this one:
```c#
namespace MyTested.Mvc.Builders.Data
{
    using Contracts.Data;
    using Microsoft.AspNetCore.Http.Features;
    using Microsoft.Extensions.Caching.Memory;    /// <summary>
                                                  /// Some random documentation.
                                                  /// </summary>
    public class MemoryCacheTestBuilder : IAndMemoryCacheTestBuilder
    {
        public MemoryCacheTestBuilder(IMemoryCache memoryCache, ISession session)
        {

        }

        public IMemoryCacheTestBuilder AndAlso()
        {
            return this;
        }
    }
}
```

**Comment by Giftednewt** [comment] 2016-02-28 11:20
@ivaylokenov @CyrusNajmabadi 
Based on that repo it looks like a dupe of #5499

**Closed** 2016-04-04 23:44 UTC
Labels: Area-IDE, Bug
