### ISSUE TITLE
Test ExternalDiagnosticUpdateSourceTests.TestExternalDiagnostics_RaiseEvents is failing

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6023] opened 2015-10-15 20:49 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/86/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Diagnostics/ExternalDiagnosticUpdateSourceTests/TestExternalDiagnostics_RaiseEvents/

**Comment by tmat** [comment] 2015-10-15 20:58
@tannergooding Has this failure also been fixed?

**Comment by srivatsn** [comment] 2015-10-19 19:16
Per Manish, @heejaechang was in a recent discussion about this issue. Is this fixed now?

**Comment by heejaechang** [comment] 2015-10-19 23:44
@srivatsn let me take a look, not sure what the issue is.

**Comment by heejaechang** [comment] 2016-01-15 11:08
this unit test has been running. so, I think it no longer repro. please re-activate if it repro again.

**Closed by heejaechang** 2016-01-15 11:08 UTC
Labels: Area-Analyzers, Bug, Test
