### ISSUE TITLE
InvalidOperationException while typing

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#49411] opened 2020-11-16 21:20 UTC
This is reported in an existing 16.8 feedback but it's actually a different problem
https://developercommunity2.visualstudio.com/t/Constant-Intellisense-crashes-in-VS-2019/1256398?preview=true&viewtype=all#T-N1257329

```
System.InvalidOperationException : Unexpected false at Roslyn.Utilities.Contract.Fail(String message) 
at Microsoft.CodeAnalysis.SemanticModelReuse.AbstractSemanticModelReuseLanguageService`4.TryGetSpeculativeSemanticModelAsync(SemanticModel previousSemanticModel,SyntaxNode currentBodyNode,CancellationToken cancellationToken) 
at async Microsoft.CodeAnalysis.SemanticModelReuse.SemanticModelReuseWorkspaceServiceFactory.SemanticModelReuseWorkspaceService.TryReuseCachedSemanticModelAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.SemanticModelReuse.SemanticModelReuseWorkspaceServiceFactory.SemanticModelReuseWorkspaceService.ComputeUpdatedMapAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.SemanticModelReuse.SemanticModelReuseWorkspaceServiceFactory.SemanticModelReuseWorkspaceService.ReuseExistingSpeculativeModelAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.ReuseExistingSpeculativeModelAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.CSharp.Completion.Providers.KeywordCompletionProvider.CreateContextAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.RecommendCompletionItemsAsync[TContext](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetUnionItemsFromDocumentAndLinkedDocumentsAsync[T](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.ProvideCompletionsAsync[TContext](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>) 
at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>) 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jinujoseph** [comment] 2020-11-17 20:44
Duplicate of https://github.com/dotnet/roslyn/issues/49413

**Closed by jinujoseph** 2020-11-17 20:44 UTC
Labels: Area-IDE, Bug
