### ISSUE TITLE
Calling non `readonly` method on `ref readonly` variable is allowed and Compiler creates a copy, making changes invisible to the user without any warning

### ISSUE THREAD

**Issue by BoyBaykiller** [dotnet/roslyn#74259] opened 2024-07-03 16:36 UTC
```cs
struct S
{
    public int V = 0;
    public S() { }

    public void Set()
    {
        V = 2;
    }
}

static void Main()
{
    S local = new S();

    ref readonly S refLocal = ref local;
    // refLocal.V = 2; // Disallowed, as expected
    refLocal.Set(); // Allowed, not expected

    Console.WriteLine(local.V);    // 0
    Console.WriteLine(refLocal.V); // 0
}
```

There are two interesting things going on in the code snippet:
1. We can change the field `V` of `refLocal`, through the method `Set()`, even though it is marked `ref readonly`
2. The compiler creates a hidden copy of `local` and calls `Set()` on it making the changes to `V` invisible to the user (see [sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBBmABM3AYVwG9NcLcBnAFwCcBXAYxtwGVzKyNLf89YrAGq4AvLgAMAbk59+7ABQBKUrgC+mWXxz4ALOwCmNZVt7c5ckeKQyeFjXYoOtCFADY9uALLQYJx6SmlGy4ADYA9kwQoWK4MAYA7opKtkEUdAYAZrgZEAAm4TChAJ7sOVkAMpHRsRnZEVGhthblmVWNAHRsRsqpAbyuAJwKDdEdQim4APRTkmn4KMN17WMTUtOzEloOakA=))

This behaviour not only makes `ref readonly` inconsistent, it's also easy to write bugs with because the changes become invisible and there isn't any warning.

---
It should not be allowed to call methods not marked as `readonly` on `ref readonly` variables (just like in C++).

**Comment by CyrusNajmabadi** [comment] 2024-07-03 18:44
Closing out as by design.  Blocking this would break a ton of code.  The compiler and language are properly abiding by all the rules of your code.  You have a readonly varaible.  So the compiler ensures it will not be mutated.  

Not being mutated doesn't mean you can't perform operations on it.  It just means that the storage of that struct won't actually mutate.  

> This behaviour not only makes ref readonly inconsistent,

This is consistent with how 'readonly' has worked since 1.0 of the language.  

> it's also easy to write bugs with because the changes become invisible and there isn't any warning.

Adding a warning would def break as lots of code certainly calls non-readonly methods on readonly variables today (consider all the readonly fields out there, and how many millions of methods exist that are not marked 'readonly').

That said, if you want a warning here, you could definitely easily write an analyzer that looks for this issue in your codebase and flags it for you as a domain specific problem you want to avoid.

**Closed by CyrusNajmabadi** 2024-07-03 18:44 UTC
Labels: Area-Compilers, untriaged

**Comment by huoyaoyuan** [comment] 2024-07-08 03:03
Analyzer proposal at https://github.com/dotnet/roslyn-analyzers/issues/3523
