### ISSUE TITLE
Decompilation cannot navigate to xUnit's "Assert.Single"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25245] opened 2018-03-06 02:07 UTC
1. Create a new Console Application
2. Install **xUnit 2.1.0** NuGet package
3. Turn on decompilation
4. Right-click on `Assert.Single` and choose **Go to Definition**

``` C#
using System;
using Xunit;

namespace ConsoleApp191
{
    class Program
    {
        static void Main(string[] args)
        {
            Assert.Single("foo", "c");
        }
    }
}

```

**Expected:** Caret to be placed on Assert.Single 
**Actual:** Assert class is decompiled but caret is at the top of the class

~Other methods work, just not this one.~ Actually looks like it cannot navigate to any of these methods on Assert.

**Comment by sharwell** [comment] 2018-03-07 11:47
Duplicate of #25246

**Closed** 2018-03-07 11:47 UTC
Labels: Area-IDE, Resolution-Duplicate
