### ISSUE TITLE
OperationVisitor cannot handle NoneOperation

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/roslyn#69837] opened 2023-09-06 21:12 UTC
**Version Used**: 4.7

**Steps to Reproduce**:

1. Write an `OperationVisitor` and have it run on a `Microsoft.CodeAnalysis.Operations.NoneOperation` (for example code that contains a [collection expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions).

**Expected Behavior**:

The visitor is able to handle the `NoneOperation`. This can be achieved (somewhat in order of my personal preference)
- by making `OperationVisitor.VisitNoneOperation` public and overridable
- or by making `OperationVisitor.VisitNoneOperation` call `OperationVisitor.DefaultVisit`.

This is important for analyzers that expect to be able to use a visitor to fully explore an operation tree.

Right now this must be handled with something like:

```cs
        public override EvaluatorResult<object?> Visit(IOperation? operation, object? argument)
        {
            if (operation.Kind == OperationKind.None)
            {
                // Handle
            }
```
which requires overriding the `Visit` method.

**Actual Behavior**:

The visitor swallows silently the `NoneOperation` resulting in an operation's subtree not being explored.

**Comment by genlu** [comment] 2023-09-08 00:22
@mavasani @333fred I think the idea is `None` represents new language construct w/o an operation implementation yet, so we intentionally do not expose it via visitor API to avoid people accidentally depend on things that might change. Is that correct?

**Comment by 333fred** [comment] 2023-09-08 21:36
That is correct. `NoneOperation` is intended for temporary scenarios, and (aside from a few niche language constructs that have not had sufficient motivation to correctly represent in IOperation to date) the final version of language features do not ship with `OperationKind.None`. We don't have an `INoneOperation` interface and don't intend on making one.

**Comment by matteo-prosperi** [comment] 2023-09-08 22:08
I understand the reasoning behind this. But it still would make sense for making `OperationVisitor.VisitNoneOperation` call `OperationVisitor.DefaultVisit`.
That would give a chance to the analyzer/generator to gracefully handle the presence of an unknown language construct.

**Comment by 333fred** [comment] 2023-09-08 22:15
I'd be somewhat worried about the behavioral breaking change there. Some users may already be working around this, and changing it may cause nodes to be double visited in such cases.

**Comment by CyrusNajmabadi** [comment] 2023-09-12 16:11
I agree with fred.  `None` really is special here.  It's teh catch-all for "these are unsupported nodes" which is different from "here's the default way of handling expected/supported nodes".   I do *not* think they should go down the same path.  Instead, if something wants to handle 'none', it should be done explicitly as it really is special.

**Comment by 333fred** [comment] 2023-09-12 18:04
@AlekseyTs, do you have any other opinions here? Otherwise, I will close this out as by design.

**Comment by AlekseyTs** [comment] 2023-09-12 18:46
> Otherwise, I will close this out as by design.

Sounds reasonable to me.

**Closed** 2023-09-12 20:06 UTC
Labels: Area-Analyzers, Area-Compilers
