### ISSUE TITLE
Local methods and delegates aren't populating ParameterInfo.DefaultValue

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#53478] opened 2021-05-18 01:15 UTC
### Description

`ParameterInfo.DefaultValue` isn't available with local methods (and I'm guessing delegates as well). In [this ASP.NET Core feature](https://github.com/dotnet/aspnetcore/issues/32375) we want to use the default value information to make decisions about how a delegate will be called. e.g. use the default value when calling the method if no other value is available.

```cs
[Fact]
public void DefaultValueTest()
{
    void TestAction([FromRoute] int foo1 = 5)
    {
    }

    var method = GetType().GetMethod(nameof(TestAction), BindingFlags.Instance | BindingFlags.NonPublic)!;
    var p1 = method.GetParameters();
    Console.WriteLine(p1[0].HasDefaultValue);
    Console.WriteLine(p1[0].DefaultValue);
    // true
    // 5

    var d = (Action<int>)TestAction;
    var p2 = d.Method.GetParameters();
    Console.WriteLine(p2[0].HasDefaultValue);
    Console.WriteLine(p2[0].DefaultValue);
    // false
    // DBNull.Value
}

private void TestAction([FromRoute] int foo1 = 5)
{
}
```

### Configuration

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

### Regression?

No

**Comment by jkotas** [comment] 2021-05-18 02:22
Roslyn does not emit the default values, so reflection does not return them.

**Comment by cston** [comment] 2021-05-18 03:41
Thanks @JamesNK.

This looks like a duplicate of https://github.com/dotnet/roslyn/issues/51518 which is being addressed in https://github.com/dotnet/roslyn/pull/53402.

**Comment by Youssef1313** [comment] 2021-05-18 06:44
Indeed. I added a test for this issue in #53402

**Closed** 2021-06-07 17:58 UTC
Labels: Area-Compilers, untriaged
