### ISSUE TITLE
When implementing an interface, methods should already have "inheritdoc" 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47436] opened 2020-09-03 22:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1018415/when-implementing-an-interface-methods-should-alre.html)._

---
When I implement an interface in a new class and ask VS to implement the missing methods, I would hope VS would also see which ones have comments and automatically add "/// <inheritdoc/>" at the top of those methods. If I'm pulling an interface, it should already be documented from the parent class.

Even if I change their design, having some documentation exposed to the methods is better than none.

---
#### Feedback Bot on 5/6/2020, 03:58 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-09-04 00:13
Methods which implement an interface member automatically inherit documentation (i.e. they have an implicit `<inheritdoc/>` if no other comment is provided) starting with version 16.4.

**Comment by sharwell** [comment] 2020-09-04 00:13
Duplicate of #7862

**Comment by sharwell** [comment] 2020-09-04 00:13
📝 See https://github.com/dotnet/roslyn/issues/7862#issuecomment-570670412 for an example screenshot

**Closed by sharwell** 2020-09-04 00:13 UTC
