### ISSUE TITLE
Ref Struct Uncertain complain: CS8347	Cannot use a result of ....  in this context because it may expose variables referenced by parameter 'source' outside of their declaration scope

### ISSUE THREAD

**Issue by vzabavnov** [dotnet/roslyn#66191] opened 2023-01-03 00:44 UTC
**dotnt 7. C# 11**: 

**Steps to Reproduce**:

```
public ref struct TheRefStruct1<T> where T : unmanaged
{
    public TheRefStruct2<T> GetRefStruct1()
    {
// => gives an error        
//Severity	Code	Description	Project	File	Line	Suppression State
// Error	CS8347	Cannot use a result of 'TheRefStruct2<T>.TheRefStruct2(in TheRefStruct1<T>)' in this context because it may //expose variables referenced by parameter 'source' outside of their declaration scope

            return new TheRefStruct2<T>(this);
    }

// => no error    !!!!!!!!!!!
      public TheRefStruct2<T> GetRefStruct2() => new(this);
}
```

logically - both methos GetRefStruct1 and GetRefStruct2 - the same. but GetRefStruct1 generate error. 
This error appears in dotnet 7, in dotnet 6 - no errors in both cases

**Comment by jcouv** [comment] 2023-01-03 05:18
@vzabavnov Your code snippet seems incomplete (doesn't define `TheRefStruct2`). I tried filling in the blanks based on the information provided, but I didn't observe a difference between those two methods (both report an error).
See [sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIGYAEAnAUwDMcBnBPAVwGMEcAVACwICViBlCmhARgB56APhwB3ZoQY4QOSjEgwIAcwIATALAAoAN6acenNgbM2RTlVoAmAcIDiBBCbPceACgCUu/To37ffjADsODAEIkasHFyW1i4IjFCkbgDcnnoAvpqpBrhMEaZRCFZCOHYOkeaF7jgAvMIhIrHxiSkaGRqahoQk5BXhjgVFwmIEEvRSMnIQCsrq2jiphrn9FRYusH3lztb4iThaOG1pQA=) repro.

Please let me know whether my repro is missing something.
As for the difference in behavior between dotnet 7 (errors reported) and dotnet 6 (no errors), I believe that is expected. See this [section of the breaking changes](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#instance-method-on-ref-struct-may-capture-unscoped-ref-parameters).

**Comment by ufcpp** [comment] 2023-01-03 05:51
Isn't this the same as https://github.com/dotnet/roslyn/issues/64045#issuecomment-1272144759 ?

> The bug is specific to usage of target typed new and expression-bodied members together.

Note: This bug has been already [fixed in VS 17.5](https://github.com/dotnet/roslyn/pull/64976).

**Comment by jcouv** [comment] 2023-01-03 07:23
Indeed. Thanks. Closing as duplicate of fixed bug

**Closed by jcouv** 2023-01-03 07:23 UTC
Labels: Bug, Area-Compilers, Resolution-Not Reproducible

**Comment by vzabavnov** [comment] 2023-01-03 13:37
Excellent! thanks
