### ISSUE TITLE
VS2022 Sync namespaces from solution explorer also makes other changes. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69884] opened 2023-09-11 18:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Sync-namespaces-from-solution-exp/10460517)._

---
\[severity:It bothers me. A fix would be nice\]  
“Sync Namespaces” from solution explorer seems to also add/remove "this." prefixes from code. This creates unnecessary churn when reviewing changes in source control. 

It should just arrange the namespaces in the files and not touch anything else - if I want to refactor other areas of the code I’ll do that explicitly in a separate pass. 

---
#### Feedback Bot on 9/7/2023, 08:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2023-09-25 13:04
Duplicate of #34707

**Closed by sharwell** 2023-09-25 13:04 UTC
Labels: Area-IDE, untriaged
