### ISSUE TITLE
Case Statement Intellisense Suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37063] opened 2019-07-09 00:10 UTC
<p>When enumerations are used in case statements intellisense should only provide those that aren't already implemented.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/538659/case-statement-intellisense-suggestions.html
VSTS ticketId: 850096_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/19/2019, 00:03 AM (80 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment] 2019-07-09 17:45
📝 When implementing this feature, make sure that cases that have a `when` expression do not get excluded from IntelliSense for subsequent cases (at least not when the expression is not known to have the value `true`)

**Comment by CyrusNajmabadi** [comment] 2019-07-10 00:07
This is explicitly by design. That's because it's legal to write:

```c#
switch (e)
{
    case E.A: // ...
    case E.A | E.B: // ...
}
```

Around 15 years ago or so we actually tried this and had to undo it because of user feedback that this was interfering with typing stuff like the above.

The recommended approach now is to use the refactoring which adds missing 'case' sections to a switch.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 17:51
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-21 17:51 UTC
Labels: help wanted, Area-IDE, Feature Request, Developer Community, IDE-IntelliSense
