### ISSUE TITLE
Cannot rename a tuple element in a declaration

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23754] opened 2017-12-13 03:05 UTC
``` C#
    class Program
    {
        static void Main(string[] args)
        {
            var input = GetInput();

            Console.WriteLine(input.time);
        }

        private static (DateTime time, string path) GetInput()
        {
            return default((DateTime, string));
        }
    }
```

1. Attempt to rename "time" in GetInput and all consumptions to be renamed

**Expected:** To be able to rename
**Actual:**

```
---------------------------
Microsoft Visual Studio
---------------------------
You cannot rename this element.
---------------------------
OK   
---------------------------
```

**Comment by jcouv** [comment] 2017-12-14 04:48
Dupe of https://github.com/dotnet/roslyn/issues/14115 ?

**Comment by jinujoseph** [comment] 2018-01-08 18:33
closed as dupe of #14115

**Closed by jinujoseph** 2018-01-08 18:33 UTC
Labels: Area-IDE
