### ISSUE TITLE
c#: generate async override when autocompleting override statement for SomeMethodAsync

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37656] opened 2019-08-01 17:20 UTC
when you override a base. SomeMethodAsync method, after hitting enter when typinv override a stub is generated.
This stub should (optionally) be generated as an async method, perhaps as a second choice for the selection.
this way, one neither needs to extend the base call with a ContinueWith() call nor has to manually rewrite the method header to be async. both actions appear to be the common case when overriding ... Async methods.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/663614/c-generate-async-override-when-autocompleting-over.html
VSTS ticketId: 953696_
_These are the original issue comments:_

Jane Wu [MSFT] on 7/29/2019, 02:35 AM (3 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by CyrusNajmabadi** [comment] 2019-08-01 17:35
@jinujoseph this does make a bunch of sense.

**Comment by ryzngard** [comment] 2019-08-12 22:25
Design Review: Currently is by design. There's a refactoring to add async to a method if await is used, and we believe that is sufficient for the current scenario. This avoids selection when generating method, but still provides a clean solution for async to be added if needed.

**Comment by sharwell** [comment] 2020-03-24 19:30
Duplicate of #27181

**Closed by sharwell** 2020-03-24 19:30 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review, Resolution-By Design
