### ISSUE TITLE
 CSharpLinkedFile.xml is failing on the future-stabilization branch

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9460] opened 2016-03-03 22:59 UTC
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future-stabilization_win_vsi_p2/4/console

**Comment by dpoeschl** [comment] 2016-03-09 09:16
No build artifacts. :crying_cat_face:

**Comment by dpoeschl** [comment] 2016-03-09 09:17
Please reopen the next time this happens and we have build artifacts. For now I don't see anything actionable in just the log.

**Comment by davkean** [comment] 2016-03-09 18:58
We hit this again: https://github.com/dotnet/roslyn/issues/9602.

**Comment by davkean** [comment] 2016-03-10 17:08
Dupe of https://github.com/dotnet/roslyn/issues/9602

**Closed by davkean** 2016-03-10 17:08 UTC
Labels: Area-IDE, Flaky, Test, Urgency-Now
