### ISSUE TITLE
Contributors should be able to clone, Open Roslyn.sln and build

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6336] opened 2015-10-26 21:20 UTC
This issue is tracking the following story:

> Contributors should be able to clone github.com/dotnet/roslyn, Open Roslyn.sln, build and everything should just work
- [x] Stop failing design-time builds if packages are not restored. Owner: **@Pilchie** Resolved in #6298.
- [ ] Make sure all projects either directly or indirectly depend on the toolset packages
- [ ] Don't show downstream errors in ErrorList if root projects fail (ie avoid ~100,000 errors in Error List). Owner **@jasonmalinowski**
- [ ] Make sure end-to-end works on clean machine (try Azure VM with preinstall VS)
- [ ] Update wiki

**Comment by davkean** [comment] 2015-10-26 21:21
tag @agocke @jasonmalinowski @Pilchie @jaredpar as they might be interested in this.

**Comment by jasonmalinowski** [comment] 2015-10-26 22:04
Thank you @davkean for filing this.

**Comment by onovotny** [comment] 2015-10-26 22:07
:+1: wish all projects would have these goals

**Comment by paul1956** [comment] 2015-10-26 22:41
@ Davkean If I might add, one tested starting point should be the Microsoft Azure image that includes Visual Studio. That way anyone can reproduce the results.

**Comment by davkean** [comment] 2015-10-26 22:43
Thanks @paul1956, add that to the list. I happen to be in an Azure image with VS as we speak. :)

**Comment by paul1956** [comment] 2015-10-26 23:18
@davkean please make it the default Azure image that includes VS not one you created.

**Comment by AdamSpeight2008** [comment] 2015-10-27 17:43
If `master` has the latest bits (not necessarily stable), at least have a branch / snapshot of `master` that is guaranteed to build and pass all of the test. So that contributors have a known good state to base their work on. Thus if now fails to build or fails tests, that they know it something that they've introduced.

**Comment by davkean** [comment] 2015-10-27 17:49
@AdamSpeight2008 We expect all branches to build and pass tests (or have Skip'd tests for failing ones). Problem is, some of our infrastructures changes have make some of our flaky test failures a little more prevalent. Until we have that under control (we're trying really hard to drive these down to zero in the next week or two), be sure to keep abreast of current issues, here: https://github.com/dotnet/roslyn/labels/Contributor%20Pain.

**Comment by ManishJayaswal** [comment] 2015-10-28 06:23
@davkean  assigning this to you to track progress.

**Comment by diryboy** [comment] 2015-10-29 03:02
:+1: Can VS nuget extension be updated? So nuget.exe can be deleted from the git tree.

**Comment by davkean** [comment] 2015-10-29 04:19
It's not enough to update the NuGet extension, all those checkboxes need to be checked before we can use NuGet inside of VS to restore packages.

**Comment by diryboy** [comment] 2015-10-29 05:41
Then, can VS nuget be disabled at solution level by some magic config file?

**Comment by davkean** [comment] 2015-10-29 14:45
I don't know @yishaigalatzer or @emgarten? Can we disable auto-package restore for a particular solution?

**Comment by yishaigalatzer** [comment] 2015-10-29 15:14
You should, the setting is saved in nuget.config

Sent from my Windows Phone
________________________________

**Comment by davkean** [comment] 2015-10-29 15:30
Awesome, will look into this today.

Sent from my Windows Phone
________________________________

**Comment by jasonmalinowski** [comment] 2015-12-10 01:06
(this was closed by GitHub since it saw the issue mentioned in my PR when I ported @davkean's change.)

**Comment by jasonmalinowski** [comment] 2018-03-30 00:08
Enough changed here that this is no longer useful.

**Closed by jasonmalinowski** 2018-03-30 00:08 UTC
Labels: Area-Infrastructure, Feature Request, Story
