### ISSUE TITLE
Interpret string interpolation as constant expression if it can be defined during compile time

### ISSUE THREAD

**Issue by ice1e0** [dotnet/roslyn#30503] opened 2018-10-14 09:40 UTC
**Version Used**: 2.9.0.63208 / VS2017 15.8.6

When I use a [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) for a string field in a attribute definition, I get the following error:
`An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type`

But when I use only _interpolated expressions_ which are constant (can be interpreted during compile time), I think the compiler should be able to handle this.

### Samples:
``` csharp
[Display(Name = $"My constant test {12345}")] // using a numberic static value
public string MyProperty { get; set; }
```
``` csharp
public const int MyConstValue = 12345;

[Display(Name = $"My constant test {MyConstValue}")] // using a const value
public string MyProperty { get; set; }
```
``` csharp
public class MyClass
{
    [Display(Name = $"{nameof(MyClass)}_{nameof(MyProperty)}")] // using the 'nameof(..)' function
    public string MyProperty { get; set; }
}
```

### Other sample
![image](https://user-images.githubusercontent.com/26678883/46914905-5efc9d80-cfa4-11e8-89bb-392743f6970d.png)

**Comment by svick** [comment] 2018-10-14 11:17
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/384.

**Comment by jaredpar** [comment] 2018-10-16 01:43
Closing as a duplicate.

**Closed by jaredpar** 2018-10-16 01:43 UTC
