### ISSUE TITLE
Adding/Removing space when toggling line comments

### ISSUE THREAD

**Issue by Lord-Turmoil** [dotnet/roslyn#73796] opened 2024-05-31 05:16 UTC
> This issue was originally posted in [Provide VS Code-like toggle comment in Visual Studio](https://developercommunity.visualstudio.com/t/Provide-VS-Code-like-toggle-comment-in-V/1073008) of Developer Community.

## Summary

As Visual Studio 2022 Preview introduced `Ctrl + /` as the default shortcut for toggling line comments, it reminds me of this long-existing issue that is quite annoying.

In Visual Studio, the behavior of toggling line comment will not add space between `//` and the code and will not trim the space when uncommenting the code if there is any.

```
//int a = 1;
 int a = 1;
```

However, Visual Studio Code and other IDEs like JetBrains will, which I think could be better.

```
// int a = 1;
int a = 1;
```

This small detail significantly impacts the overall code style and requires extra effort to manually add or remove spaces in Visual Studio.

## Proposed Feature

I suppose there shouldn't be any technical problem, just an editor action to add/remove the space when toggling a line comment.

**Comment by sharwell** [comment] 2024-06-05 20:23
I don't have strong thoughts about what to do for the Toggle Comment command. However, for Edit.CommentSelection, I don't believe we should make this change as it will negatively impact StyleCop users who invoke this command twice to comment out code blocks with `////` and simultaneously distinguish them from commented text.

**Comment by CyrusNajmabadi** [comment] 2024-06-05 22:00
I'd prefer to not change this at all. My whole substantially more feedback

**Comment by CyrusNajmabadi** [comment] 2024-11-26 01:43
Closing out as unplanned.  This is working as intended.

**Closed by CyrusNajmabadi** 2024-11-26 01:43 UTC
Labels: Area-IDE, Feature Request
