### ISSUE TITLE
Inappropiate proposal about redundant conversion for event parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46351] opened 2020-07-27 16:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1125490/inappropiate-proposal-about-redundant-conversion-f.html)._

---
For the following code the IDE remarks, that for Bar(CInt(Dec)) the conversion to Integer can be removed because of redundancy.
For the method calls there is no proposal - and this is right, because the conversion is necessary.

```
Private Sub Foo()
	Dim Dec As Decimal
	RaiseEvent Bar(CInt(Dec))
	Bar1(CInt(Dec))
	Bar2(CInt(Dec))
End Sub

Event Bar(Baz As Integer)

Private Sub Bar1(Baz As Integer)
End Sub

Private Function Bar2(Baz As Integer) As Boolean
	Return True
End Function
```

---
#### Feedback Bot on 7/26/2020, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by paul1956** [comment] 2020-07-28 02:06
Dup of #45102 and fixed in #45102

**Comment by sharwell** [comment] 2020-07-28 19:15
Duplicate of #44516

**Comment by sharwell** [comment] 2020-07-28 19:16
Thanks @paul1956 ! I wasn't sure what to search for but you knew 👍

**Closed by sharwell** 2020-07-28 19:15 UTC
Labels: Area-IDE, Bug, Developer Community, Resolution-Fixed
