### ISSUE TITLE
Change Signature: removing parameter leaves empty line in xml doc comments

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8153] opened 2016-01-25 15:26 UTC
Ported from internal bug 125787
1. paste the following code.  Invoke remove parameter on `Foo`, remove `x`, Apply

``` VB
''' <summary>
''' ssss <see cref="Foo(Integer, String)"/>
''' </summary>
''' <param name="x">x x x </param>
''' <param name="y">y y y </param>
Sub Foo(x As Integer, y As String)
End Sub
```

**Expected**: no empty xml doc comment line
**Actual**:

``` VB
''' <summary>
''' ssss <see cref="Foo(String)"/>
''' </summary>
''' <param name="y">y y y </param>
''' 
Sub Foo(y As String)
End Sub
```

**Comment by dpen2000** [comment] 2016-02-05 22:55
@dpoeschl This also happens with C# code like this:
```
/// <summary>
/// 
/// </summary>
/// <param name="a"></param>
/// <param name="b"></param>
void Foo(string a, string b)
{ }
```
I can fix this one. Question though. Consider the y parameter xml comment line looks like this:
```
''' some other leading comment <param name="y">y y y </param>
```
Or this:
```
''' <param name="y">y y y </param> some other trailing comment
```

Should we remove the entire line in both of these cases? Or preserve the line because we don't know those comments should be removed?

**Comment by camillemarie** [comment] 2020-04-03 20:09
Bumping this as the bug still exists.
I can reproduce it in this version:

 - Microsoft Visual Studio Enterprise 2019
   - Version 16.5.0
   - VisualStudio.16.Release/16.5.0+29911.84

 - Microsoft .NET Framework
    - Version 4.8.03752

**Comment by CyrusNajmabadi** [comment] 2024-10-21 20:14
Closing out as we are not likely to change thse vb experiences.

**Closed by CyrusNajmabadi** 2024-10-21 20:14 UTC
Labels: Bug, help wanted, Area-IDE
