### ISSUE TITLE
Extract Method in file with top-level statements results in compile error

### ISSUE THREAD

**Issue by CosminSontu** [dotnet/roslyn#65465] opened 2022-11-16 17:58 UTC
**Version Used**: 
Visual Studio 2022 v17.4.1
**Steps to Reproduce**:

1. Open file with top-level statements that has at least a record declaration
2. Apply ExtractMethod refactoring (edit: via VS Keyboard shortcut "Ctrl-R,M" in my case)
3. Build your project, you get CS8803

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Expected Behavior**:
Method is placed before any namespace and/or type declaration.
**Actual Behavior**:
Method is placed at the end of the file causing CS8803 compiler error

**Comment by Youssef1313** [comment] 2022-11-16 18:00
Similar to https://github.com/dotnet/roslyn/issues/49649. But not sure if the root cause is the same.

**Comment by CyrusNajmabadi** [comment] 2022-11-16 19:41
Could you please supply a repro @CosminSontu   e.g. a snippet of code, and the span you were applying the refactoring to?  Thanks!

**Comment by Youssef1313** [comment] 2022-11-16 19:47
@CyrusNajmabadi 

```csharp
using System;

if (args[0] == "")
{
    Console.WriteLine();
}

record C;
```

The refactoring isn't offered when not in a nested construct it seems? not sure if that's a bug.
and this specific bug only reproduces when there are using statements.

**Comment by Youssef1313** [comment] 2022-11-16 19:49
Note: Extract local function is already offered and does the right thing. Extract method shouldn't be offered in the first place for top-level statements.

That might be already done, but not done properly (since we already don't offer when the selection is a global statement syntax - though we should consider nested constructs too)

**Comment by Youssef1313** [comment] 2022-11-16 19:53
https://github.com/dotnet/roslyn/blob/d35a6cb849e44e98e5387c8d702aa8db0f6fb4f9/src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs#L111-L115

Here we only check if the direct selection parent is global statement. We should go higher up in the tree.

**Comment by CosminSontu** [comment] 2022-11-17 10:13
In my case I had a record defined at the end of the top-level statements file. The Ctrl-R-M refactoring created the extracted the extracted method at the end of the file ( after the pre-existing record declaration ). Moving the method declaration above the record declaration fixed the aforementioned compiler error.

**Comment by Youssef1313** [comment] 2022-11-17 10:14
@CosminSontu Did you also see an "Extract local function" refactoring that already does the right thing?

**Comment by CyrusNajmabadi** [comment] 2024-12-13 18:56
Fixed with https://github.com/dotnet/roslyn/pull/76402

**Closed by CyrusNajmabadi** 2024-12-13 18:56 UTC
Labels: Area-IDE
