### ISSUE TITLE
NavigateTo not finding symbols.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10367] opened 2016-04-06 15:44 UTC
Search for 'SwitchStatementSyntax' in roslyn.

Actual:
No results come up.  

Expected: 
Results

I believe this is because SwitchStatementSyntax is defined in a generated file.  But so what?  It should still show up in NavigateTo.  That's the entire purpose of navigate to.

**Comment by balajikris** [comment] 2016-04-07 17:23
+1 for this. I also find it hard after we blocked generated files. /cc @brettfo

**Comment by Pilchie** [comment] 2016-04-08 21:59
Duplicate of #8009.

**Closed by Pilchie** 2016-04-08 22:00 UTC
Labels: Area-IDE, Resolution-Duplicate
