### ISSUE TITLE
IOperation: It looks like there is no way to represent member/collection initializer via ITypeParameterObjectCreationExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8886] opened 2016-02-18 20:09 UTC
```
    Shared Sub Test(Of T As {New, Class1})()
        Dim x = New T With {.P1 = 1}
    End Sub
```

**Comment by mavasani** [comment] 2017-07-07 22:28
Dupe of https://github.com/dotnet/roslyn/issues/20491

**Closed by mavasani** 2017-07-07 22:28 UTC
Labels: Area-Analyzers, Bug, Concept-API, New Feature - IOperation, Urgency-Soon
