### ISSUE TITLE
CS1580 fired with a paramater that is generic and nullable (xml doc)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38401] opened 2019-08-29 23:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/589446/cs1580-fired-with-a-paramater-that-is-generic-and.html)._

---
I'm using VS2019 16.1.1 (in VS2017 15.9.12 this does not happen)
The app is using .net core 2.2, and the analyzers Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.2
StyleCop.Analyzers 1.1.118 

I have method with this definition:

```
public static bool HasValue&lt;T&gt;(this T? source) where T : struct
```

and in a xml doc I have this:

<pre>
/// &lt;summary&gt;
/// Internally uses &lt;see cref=&quot;TypeValidations.HasValue{T}(T?) &quot;/&gt;.
/// &lt;/summary&gt;
</pre>

In VS2019 this fires the error:

> Error	CS1580	Invalid type for parameter T? in XML comment cref attribute: 'TypeValidations.HasValue{T}(T?) '

If I change the documentation to `TypeValidations.HasValue{T}(Nullable{T})`  now I got an analyzer error (SA1125) telling me that I should use the shorthand notation for nullable types.

---
#### Visual Studio Feedback System on 5/30/2019, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/10/2019, 02:19 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 6/10/2019, 04:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment] 2019-08-30 00:19
Seems like maybe a duplicate of #33782. Tagging @jcouv

**Comment by jaredpar** [comment] 2019-09-09 21:29
Closing as a duplicate.

**Closed by jaredpar** 2019-09-09 21:29 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
