### ISSUE TITLE
Null-safe navigation and null-coalescing break the out variable initialization detection

### ISSUE THREAD

**Issue by kodfodrasz** [dotnet/roslyn#33559] opened 2019-02-21 14:01 UTC
**Version Used**: 

C# 7.3

Excerpt from Visual Studio About dialog (items suspected to be relevant)
~~~
Microsoft Visual Studio Enterprise 2017 
Version 15.9.2
VisualStudio.15.Release/15.9.2+28307.108
Microsoft .NET Framework
Version 4.7.03056
C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
~~~

**Steps to Reproduce**:

 1. given the following example:

~~~csharp
                var place = new
                {
                     Metadata = (IDictionary<string, string>)null
                };
                // ...
                var sb = new StringBuilder();
                // ...
                if(place.Metadata?.TryGetValue("erpid", out var erpid) ?? false)
                {
                    sb.Append(" | ");
                    sb.Append("erpid=");
                    sb.Append(erpid);
                }
~~~

where `Metadata` is `IDictionary<string,string>` typed nullable member of place.

 2. I get Error `CS0165` `Use of unassigned local variable 'erpid'`
 ![image](https://user-images.githubusercontent.com/3705124/53173213-8402bc00-35e7-11e9-9a66-d62eef17d4a0.png)
 3. code does not compile

**Expected Behavior**:

`erpid` is initialized in the scope, as the expression can be evaluated at compile time to determine that the `erpid` variable will be initialized in the scope.

Example code compiles correctly.

**Actual Behavior**:

Null-safe navigation and null-coalescing break the out variable initialization detection.

**Comment by kodfodrasz** [comment] 2019-02-21 14:09
The following rewrite of the code compiles properly:
~~~csharp
                if(place.Metadata != null && place.Metadata.TryGetValue("erpid", out var erpid))
                {
                    sb.Append(" | ");
                    sb.Append("erpid=");
                    sb.Append(erpid);
                }
~~~

**Comment by gafter** [comment] 2019-02-21 15:06
I believe this is by spec as the language has no concept of definitely assigned when non null.

**Comment by gafter** [comment] 2019-03-26 17:26
Closing as by design.

**Closed by gafter** 2019-03-26 17:26 UTC
Labels: Area-Compilers
