### ISSUE TITLE
Typing generic local function requires fighting with auto-completion

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#13480] opened 2016-08-31 10:34 UTC
Place caret inside method M in following code snippet:
```cs
class C
{
    public void M()
    {

    }
}
```

and start typing this text: T M\<T\>(T t) => t;

you will end up with following code:
```cs
class C
{
    public void M()
    {
        ToString M<ToString>(T t) => t;
    }
}
```

because auto-completion offers you to complete ToString when you type return type and type parameter. It also auto-completes preselected item as you continue typing even if you don't interact with auto-completion popup at all.

If you want to end up with correct code you have to decline auto-completion by pressing 'esc' multiple times during typing a single line.

Also, completing 'ToString' in angle brackets looks bizarre and doesn't make any sense.

**Comment by Pilchie** [comment] 2016-08-31 17:55
Do you have some extension installed?  If not, can you be more detailed  about *exactly* where you typed and in what order?  We normally add a speculative `T` to the completion list just to prevent this.  See http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp.Features/R/713d36f956e0b8d6.html.

**Comment by TessenR** [comment] 2016-08-31 18:19
This is VS 15 Preview 4

It was a fresh installation. I didn't install any extension manually but it looks like it has some preinstalled extensions like `Roslyn language services`. Do you need a list of them?

ShouldShowSpeculativeTCompletionItemAsync has some checks but I guess neither of them allows speculative T completion inside a method body.
```cs
  syntaxTree.IsMemberDeclarationContext
  syntaxTree.IsGlobalMemberDeclarationContext
  syntaxTree.IsGlobalStatementContext
  syntaxTree.IsDelegateReturnTypeContext
```
Unfortunately local functions can be generic and are declared inside methods/ctors/properties etc

Screencast:
![t](https://cloud.githubusercontent.com/assets/5566206/18140534/a6326fec-6fbe-11e6-8e7e-90822992973c.gif)

**Comment by Pilchie** [comment] 2016-08-31 18:22
Perfect - thanks for the gif.  I missed the word "local" in the issue title.  My guess is that this provider I linked above doesn't realize it should show in this case.

Moving to compiler to update for new language feature.

**Comment by agocke** [comment] 2016-09-13 21:21
@TessenR Yup the problem is that we haven't yet updated completion to understand local functions. I'm going to try to fix this ASAP, it's very annoying.

Thanks for reporting!

**Comment by TessenR** [comment] 2016-10-07 12:30
@agocke 
Thanks, for the fix..

However, as far as i can see this pull request doesn't fix the issue entirely.
There problem with first 'ToString' instead of local function's return type can't be fixed by recognizing the local function earlier in parsing.
E.g. I want to type following local function:
```cs
T Local<T>() => default(T);
```
Unfortunately, the very first 'T' (which denotes return type of this local function) is corrected to 'ToString'.

This can't be fixed by changes in parsing since when I hit 'space' there is nothing that can possibly be parsed as local function. I.e.:
```cs
class C
{
  void M()
  {
    T
```

I can't verify it in VS itself, but this test is red:
```cs
      [Fact]
      [Trait(Traits.Feature, Traits.Features.Completion)]
      [Test.Utilities.CompilerTrait(Test.Utilities.CompilerFeature.LocalFunctions)]
      public async Task CompletionForSpeculativeT()
      {
        var markup = @"
class C
{
    void M()
    {
        $$";

        await VerifyItemExistsAsync(markup, @"T");
      }
```
with following output:
```No expected item was found.
Existing items: C, Equals, GetHashCode, GetType, M, MemberwiseClone, Microsoft, ReferenceEquals, System, ToString```

Do you have any plans to support this scenario?

**Comment by Pilchie** [comment] 2016-10-07 15:15
Agree with @TessenR here - I suspect you'll need to adjust the [`SpeculativeTCompletionProvider`](http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp.Features/a.html#713d36f956e0b8d6) to support typing generic local functions.

**Comment by agocke** [comment] 2016-10-07 16:12
@Pilchie @TessenR You're absolutely right, but this is in a separate area of the code base, so I was going to fix it when I fix the other completion providers in this area. For instance, we should also see `void`, `async`, and `unsafe` in that completion list.

See https://github.com/dotnet/roslyn/issues/8617 for details.

**Comment by Pilchie** [comment] 2016-10-07 16:17
Okay - but given that this bug is *explicitly* about typing the return type of a generic local function it seems disingenuous to close it with a fix for something else...

**Closed** 2016-10-17 22:53 UTC
Labels: Area-Compilers, Bug
