### ISSUE TITLE
Removing unused usings should remove the extra line between copyright and namespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23568] opened 2017-12-04 23:09 UTC
1. 
``` C#
// Copyright

using System;

namespace ConsoleApp122
{
    class Program
    {
    }
}
```

2. Remove unused usings

**Expected:** 

``` C#
// Copyright

namespace ConsoleApp122
{
    class Program
    {
    }
}
```

**Actual:**

``` C#
// Copyright


namespace ConsoleApp122
{
    class Program
    {
    }
}
```

**Comment by CyrusNajmabadi** [comment] 2017-12-04 23:50
This seems very minor.  In practice who has no namespaces in their C# program *and* has a copyright clause...

Doesn't seem like a realistic scenario.

**Comment by davkean** [comment] 2017-12-04 23:51
We do: https://github.com/dotnet/project-system/pull/3016. I'm sure Roslyn also does.

**Comment by tannergooding** [comment] 2017-12-05 00:00
Yeah, this is a fairly common scenario and I've hit it a number of times.

It is also hit when you have the 'separate using statements' option enabled.

**Comment by CyrusNajmabadi** [comment] 2017-12-05 00:09
Fair enough. I was thinking that the moment you did anything interesting you would need some namespaces. But i can see how simple interfaces, without any code, that just use built-in primitive types could hit this.

Seems reasonable to fix then :) Def something the community could pick up. @sharwell Could you add the right tags? Thanks!

**Comment by zaytsev-victor** [comment] 2017-12-06 17:22
@sharwell it is duplicate of #17032, but since it already has a PR, I think #17032 should be closed as duplicate.

**Closed** 2018-08-02 07:12 UTC
Labels: Area-IDE, Bug, help wanted
