### ISSUE TITLE
Finalizer constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36258] opened 2019-06-08 05:48 UTC
<p>With the code below the TestClass finaliser is called despite the fact that the constructor is never called. This happens with -toolsversion:4.0 but not for 3.5 or 2.0.</p> <p>FinaliserBug.cs:</p> <pre>namespace FinaliserBug
{
    class TestClass
    {
        public TestClass(string arg) { System.Console.WriteLine(&quot;constructor&quot;); }
        ~TestClass() { System.Console.WriteLine(&quot; finaliser &quot;); }
    }

class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine(&quot;begin&quot;);
            try
            {
                new TestClass(args[args. Length]);
                System.Console.WriteLine(&quot;constructed&quot;);
            }
            catch
            {
                System.Console.WriteLine(&quot;bang!&quot;);
            }
            System.Console.WriteLine(&quot;end&quot;);
        }
    }
}
</pre><p>FinaliserBug.msbuild:</p><pre>&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
  &lt;ItemGroup&gt;
    &lt;Compile Include=&quot;FinaliserBug.cs&quot; /&gt;
  &lt;/ItemGroup&gt;
  &lt;Target Name=&quot;Build&quot;&gt;
    &lt;Csc Sources=&quot;@(Compile)&quot;/&gt;  
  &lt;/Target&gt;
&lt;/Project&gt;
</pre><p>Build:</p><pre>C:\Temp\FinaliserBug&gt;c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild -toolsversion:4.0 FinaliserBug.msbuild
Microsoft (R) Build Engine version 4.7.3190.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18/05/2019 12:48:13 PM.
Project &quot;C:\Temp\FinaliserBug\FinaliserBug.msbuild&quot; on node 1 (default targets).
Build:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /out:FinaliserBug.exe FinaliserBug.cs
Done Building Project &quot;C:\Temp\FinaliserBug\FinaliserBug.msbuild&quot; (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.16
</pre><p>Actual output:</p><pre>C:\Temp\FinaliserBug&gt;FinaliserBug.exe
begin
bang!
end
 finaliser 
</pre><p>Expected output:</p><pre>C:\Temp\FinaliserBug&gt;FinaliserBug.exe
begin
bang!
end
</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/573390/finalizer-constructor.html
VSTS ticketId: 895482_
_These are the original issue comments:_

Sascha Sanches on 5/18/2019, 01:30 AM (20 days ago): <p>Hi,</p><p>the argument args[args.Length] will cause an exception. The index is one too large: indexing the array is normally from 0 to .Length - 1 inclusive.</p>

Visual Studio Feedback System on 5/19/2019, 07:21 PM (19 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by svick** [comment] 2019-06-08 14:57
This sounds like a duplicate of https://github.com/dotnet/coreclr/issues/2478.

**Comment by gafter** [comment] 2019-07-09 21:44
Closing as dup of dotnet/coreclr#2478.

**Closed by gafter** 2019-07-09 21:44 UTC
Labels: Area-Compilers, Resolution-External
