### ISSUE TITLE
InvalidOperationException in OpenTextBufferManager.OnTextBufferChanged during InlineRename in Razor

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#20906] opened 2017-07-15 20:53 UTC
**Version Used**: 15.3.0 Preview 4

**Steps to Reproduce**:

1. In Razor page, initiate rename of C# variable, e.g. of `item` in
```C#
@foreach (var item in Model.Items)
```
2. Eventually backspace everything to get into
```C#
@foreach (var | in Model.Items)
```

**Expected Behavior**: No errors.

**Actual Behavior**: Editor extension exception in ActivityLog:
```
System.InvalidOperationException: Sequence contains more than one element
 at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
 at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

Might be related to #18277 which I am also experiencing here.

**Comment by Pilchie** [comment] 2017-07-17 17:00
That exception is one of the ones listed in #18277.

This appears to be a duplicate of #18277

**Closed** 2017-07-17 17:08 UTC
Labels: Area-IDE, Bug
