### ISSUE TITLE
Convert if to switch could unify duplicate cases

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#21105] opened 2017-07-25 16:24 UTC
(same in C#)
Consider an if block with multiple identical cases. Since it inspects the condition and the block already, convert if to switch could avoid generating identical conditions/blocks

ex:
```VB
        If x = 4 Then
            x = 1
        ElseIf x = 5 Then
        ElseIf x = 4 Then
            x = 1

        End If
```
becomes 
```VB

        Select Case x
            Case 4             x = 1
            Case 5
            Case 4             x = 1
        End Select
```
but could also be shortened to
```VB
        Select Case x
            Case 4             x = 1
            Case 5
        End Select
```

**Comment by alrz** [comment] 2017-07-25 16:57
Also https://github.com/dotnet/roslyn/issues/20989

**Comment by Pilchie** [comment] 2017-07-25 22:00
Duplicate of #20981.

**Closed** 2017-07-25 22:01 UTC
Labels: Area-IDE, Bug, Depth Testing, Resolution-Duplicate
