### ISSUE TITLE
SourceGenerators: MSBuild property (and metadata?) values are (potentially) truncated before being passed to Generator

### ISSUE THREAD

**Issue by DoctorVanGogh** [dotnet/roslyn#72592] opened 2024-03-19 12:13 UTC
**Version Used**: 
 4.9.0-3.24121.1 (a98c90d5)
 
**Steps to Reproduce**:

1.  Write a source generator which consumes a MSBuild property
    ```cs
      ...
      public class FooGen : IIncrementalGenerator {
          public void Initialize(IncrementalGeneratorInitializationContext context) {
              var pipeline = context.AnalyzerConfigOptionsProvider
                  .Select(
                      (acop, _) => acop.GlobalOptions.TryGetValue("build_property.Foo", out string s) ? s : null
                  );
    
              context.RegisterSourceOutput(
                  pipeline, 
                  (SourceProductionContext ctx, string property) => throw new Exception($"Property value was: '{property}'"));
          }
      }
      ...
    ```
     (Using an exception instead of actual source output for brevity)
2. Consume the source generator in another project
3. Ensure the property value is visible to the generator
    ```xml
      <ItemGroup>
        <CompilerVisibleProperty Include="Foo" />
      </ItemGroup>
    ```
4. Set the property value **and have it contain a `;` character**
    ```xml
      <PropertyGroup>
          <Foo>Wiz;Bang</Foo>
      </PropertyGroup>
    ```
5. Build the consuming project.

**Expected Behavior**:
A property value **identical to what is available in MSBuild** - Here exception from the generator with a message of 

  ... Exception was of type 'Exception' with message 'Property value was: Wiz;**Bang**'.

**Actual Behavior**:
A property value **that is truncated at the first use of the `;`character** - Here exception from the generator with a message of 

  ... Exception was of type 'Exception' with message 'Property value was: Wiz'.
  
 ---  
 It _seems_ as if property values get truncated at `;` characters before getting passed to the generator. The [Incremental Generators Cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md#consume-msbuild-properties-and-metadata) does not mention any **forbidden** characters ;)

I have **not** tested if the same issue occurs when using MSBuild Metadata (aka `build_metadata.FooItem.BarMetedata`) but would very much assume so.

_This is quite the annoying bug because it is not unreasonable to want to pass ItemGroups to a generator, and setting a property to a simple `<Foo>@(SomeGroup)</Foo>` serializes the item group with `;`as separator._

I'm assuming this is happening because the analyzer gets fed with some `key1=...;key2=...;...` format, internally using `;` as a separator, and the MSBuild to generator transition does not (cannot?) properly escape semicolons before building that format.  

---
Minimal Repo Solution:
[AnalyzerMsBuildPropertyIssues.zip](https://github.com/dotnet/roslyn/files/14650158/AnalyzerMsBuildPropertyIssues.zip)

**Comment by gtbuchanan** [comment] 2024-05-31 13:33
I just encountered something similar using the built-in `ProjectDir` property (i.e. `build_property.projectdir`). The path was truncated at the first `#` character. I'm not sure if this is related. I cannot reproduce it in a unit test by passing the prop manually with `AnalyzerConfigOptionsProvider`. I've adapted the repro solution to work with my use case. You should see the same behavior when you unzip it to a directory with the name `C#`:

[AnalyzerMsBuildPropertyIssues.zip](https://github.com/user-attachments/files/15514355/AnalyzerMsBuildPropertyIssues.zip)

**Comment by sharwell** [comment] 2024-05-31 14:09
Duplicate of #44596

**Closed by sharwell** 2024-05-31 14:09 UTC
Labels: Bug, Area-Compilers, New Feature - Source Generators
