### ISSUE TITLE
'IDE0002: Name can be simplified' produces a non beneficial diagnostic in certain contexts

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#11460] opened 2016-05-20 19:44 UTC
In the example below, a diagnostic is provided which suggests 'simplifying' some code from `CheckBox.IsCheckedProperty` to `System.Windows.Controls.Primitives.ToggleButton.IsCheckedProperty`.

This 'simplification' results in a non-simplified name being provided in the fix and additionally requires an additional namespace to be added to the usings for the full 'simplification' to occur.

I would expect that either the suggested fix comes fully simplified (in this case a using would be added and the code would change to `ToggleButton.IsCheckedProperty` -or- a fix is not suggested in this scenario.

![image](https://cloud.githubusercontent.com/assets/10487869/15439962/9c0b60ba-1e87-11e6-9db4-90ceebaa5d7b.png)

**Comment by Pilchie** [comment] 2016-11-02 21:32
Dupe of https://github.com/dotnet/roslyn/issues/11820?

**Comment by tannergooding** [comment] 2017-07-07 16:29
Definitely a dupe. This bug came first but feel free to close whichever you feel provides less information ;)

**Comment by CyrusNajmabadi** [comment] 2022-10-28 20:13
This fixer was rewritten, and i wasn't able to reproduce the above behavior.  Clsoing out.

**Closed by CyrusNajmabadi** 2022-10-28 20:13 UTC
Labels: Bug, Area-IDE

**Comment by geniuszxy** [comment] 2023-07-31 11:05
> This fixer was rewritten, and i wasn't able to reproduce the above behavior. Clsoing out.

My Visual Studio version is 17.6.4, this problem as well as #11820 still exist, would you mind to confirm them again?

![123123](https://github.com/dotnet/roslyn/assets/2471200/5c522d68-f295-400c-9d1e-b4fb50047b00)
