### ISSUE TITLE
Weird pattern matching behavior

### ISSUE THREAD

**Issue by CorrM** [dotnet/roslyn#63560] opened 2022-08-24 12:24 UTC
**Version Used**: 
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
C:\Program Files\dotnet\sdk\6.0.302\Roslyn\bincore\csc.dll

**Steps to Reproduce**:
Why this code compiles
```csharp
public static void MakePropertyValue<T>(T val)
{
    if (val is Span<byte> || val is ReadOnlySpan<byte>)
    {
    }
}
```
but this code can't compiles!
```csharp
public static void MakePropertyValue<T>(T val)
{
	if (val is Span<byte> or ReadOnlySpan<byte>)
    {
    }
}
```

**Expected Behavior**:
Compile !

**Actual Behavior**:
Error CS8121 : An expression of type 'T' cannot be handled by a pattern of type 'Span<byte>'.
Error CS8121 : An expression of type 'T' cannot be handled by a pattern of type 'ReadOnlySpan<byte>'.

**Comment by svick** [comment] 2022-08-27 13:49
Your first example compiles, but doesn't work the way you want, and you get warnings about that:

> warning CS0184: The given expression is never of the provided ('Span\<byte>') type

This is because the `is` operator doesn't work for `ref struct`s like `Span<T>`, see https://github.com/dotnet/roslyn/issues/63085.

As for why one is a warning and the other an error, I suspect this is because the `is` type test is an old feature that works the way it always did, but pattern matching is a new feature, so it can be stricter. Though per https://github.com/dotnet/roslyn/issues/63085#issuecomment-1228726575, this might change in the future.

In effect, I think this issue can be closed as a duplicate of https://github.com/dotnet/roslyn/issues/63085.

**Closed** 2022-08-27 14:16 UTC
Labels: Area-Compilers, untriaged
