### ISSUE TITLE
When renaming a GeneratedRegex method, keystrokes are duplicated, and pressing backspace commits the renaming instead of backspacing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68777] opened 2023-06-26 12:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-renaming-a-GeneratedRegex-method-k/10394346)._

---
[severity:It's more difficult to complete my work]
I have a source-generated regex (with the [GeneratedRegex] attribute).  If I press F2 and try to rename the method, after a few keystrokes, all subsequent keystrokes are duplicated.  If I press backspace to try to correct the duplicates, instead of backspacing, it just commits the renaming with whatever was in the text field.  I'm able to rename other methods and variables in this solution without encountering this issue.

---
#### Feedback Bot on 6/18/2023, 11:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2023-07-31 13:05
Duplicate of #68880

**Closed by sharwell** 2023-07-31 13:05 UTC
Labels: Area-IDE, Feature - Rename
