### ISSUE TITLE
A lone semicolon in a top level statement in VS 16.11 will cause the app to terminate without errors

### ISSUE THREAD

**Issue by alberk8** [dotnet/roslyn#58465] opened 2021-12-21 09:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

aspnet core will execute with the following message.  There is no compilations error and Analyze and Clean Up Code also does not pick up on the dangling semicolon.

```
D:\Staging\Test\WebApplication1\WebApplication1\bin\Debug\net5.0\WebApplication1.exe (process 25668) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

### Expected Behavior

Fail to compile with error message pointing to the offending semicolon.

### Steps To Reproduce

1) Create an ASP.NET Core Web API project from template
2) Go to WeatherForecastController.cs
3)  Press F5

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
; // <= ### Add This ####
```

### .NET Version

5.0.13

**Comment by CyrusNajmabadi** [comment] 2021-12-22 17:25
> Expected Behavior

> Fail to compile with error message pointing to the offending semicolon.

I believe this is our behavior now (we updated the language for the case). Can you check the asp case on a recent 17.x build to see?

**Comment by sharwell** [comment] 2021-12-22 17:25
Duplicate of #53472

**Comment by sharwell** [comment] 2021-12-22 17:26
I marked this as a duplicate of a similar issue which has already been fixed by the compiler.

**Closed by sharwell** 2021-12-22 17:25 UTC
Labels: Area-Interactive, untriaged

**Comment by MariovanZeist** [comment] 2021-12-22 17:33
@CyrusNajmabadi 
17.0.4 doesn't have this behavior, and works as expected (generating a compile error)
I only saw it fail on 16.11.8.

**Comment by alberk8** [comment] 2021-12-23 00:48
I also can confirm that this only happen in VS 2019 and on a fresh created project in VS2022 it does display the error message.  But opening an existing project created in VS 2019 in VS 2022 will fail like it is reported (no error but exit 0).
