### ISSUE TITLE
visualbasicaddimportcodefixprovider encountered an error and has been disabled...

### ISSUE THREAD

**Issue by lmkz** [dotnet/roslyn#4395] opened 2015-08-06 22:46 UTC
Both my colleague and I have had this message appear in Visual Studio 2015 randomly several times recently:

visualbasicaddimportcodefixprovider encountered an error and has been disabled...

![image](https://cloud.githubusercontent.com/assets/13561008/9125116/6cebfa24-3cf1-11e5-93ce-935f0a9a67c3.png)

**Comment by NaxAlpha** [comment] 2015-08-07 06:43
I also get this issue, it occurs randomly

**Comment by obelink** [comment] 2015-08-17 18:58
Same here... happens randomly.

**Comment by BlackMael** [comment] 2015-08-19 02:39
I also get this error/warning randomly and quite often.  I get it at least once every hour or two at most.

**Comment by jmarolf** [comment] 2015-08-19 20:39
If someone could run visual studio as `devenv.exe /log` and then respond back here with the call stack from the activity log it would be a big help.

**Comment by Pilchie** [comment] 2015-08-20 15:22
Wait, I don't understand.  #4656 is specifically only about C# fixes, and this bug is specifically about the VB fixer.  How could that PR fix this issue?

**Comment by BlackMael** [comment] 2015-08-21 02:35
Maybe someone got the issue number wrong. 

That fix thinks it fixes this issue but explicitly states the issue doesn't occur for VB, which is a little contrary to this issue.

**Comment by jmarolf** [comment] 2015-08-21 05:18
yep, sorry.  my mistake

**Comment by jmarolf** [comment] 2015-08-27 00:54
@BlackMael can you reproduce this reliably? would it be possible for you to run `devenv.exe /log` and paste the stack trace from the activity log?

**Comment by BlackMael** [comment] 2015-08-27 10:24
I'll give that a try...

**Comment by BlackMael** [comment] 2015-08-29 13:41
Bother.  The issue hadn't appeared for a few days and then yesterday it did occur but I wasn't ready with "/log".  I'll restart with "/log" by default for a while so hopefully I'll catch the issue on Monday (31 August)

**Comment by jmarolf** [comment] 2015-08-31 05:07
@BlackMael Thanks for trying!

**Comment by dpoeschl** [comment] 2015-09-04 22:28
Unable to reproduce on our side. If anyone is able to get a stack trace (using devenv /log), or repro steps, or any hints as to how to make this happen, please let us know and we will reactivate this bug and investigate. Thanks!

**Comment by PFCKrutonium** [comment] 2015-09-14 23:04
Where can I find the log, I just logged it.

**Comment by BlackMael** [comment] 2015-09-14 23:06
It's the ActivityLog.xml in C:\Users\[YourLogin]\AppData\Roaming\Microsoft\VisualStudio\14.0

**Comment by PFCKrutonium** [comment] 2015-09-14 23:10
https://www.dropbox.com/s/6p8rbq29pbyt2ef/ActivityLog%20-%20Copy.xml?dl=1

**Comment by PFCKrutonium** [comment] 2015-09-14 23:12
https://www.mediafire.com/?0t2qdw0oyi8upuc

**Comment by jmarolf** [comment] 2015-09-14 23:17
Thanks @PFCKrutonium ! got the call stack.

```
Unable to cast object of type &apos;Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax&apos; to type &apos;Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax&apos;.&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxFactsService.GetExpressionOfMemberAccessExpression(SyntaxNode node)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddImport.VisualBasicAddImportCodeFixProvider.IsViableExtensionMethod(IMethodSymbol method, SyntaxNode expression, SemanticModel semanticModel, ISyntaxFactsService syntaxFacts, CancellationToken cancellationToken)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.&lt;&gt;c__DisplayClass26_0.&lt;FilterForExtensionMethods&gt;b__0(IMethodSymbol method)&#x000D;&#x000A;  
 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()&#x000D;&#x000A;  
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#x000D;&#x000A;  
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.FilterForExtensionMethods(SemanticModel semanticModel, ISet`1 namespacesInScope, ISyntaxFactsService syntaxFacts, SyntaxNode expression, IEnumerable`1 symbols, CancellationToken cancellationToken)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.&lt;GetNamespacesForMatchingExtensionMethodsAsync&gt;d__21.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.&lt;RegisterCodeFixesAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;  
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&lt;PerformActionAsync&gt;d__2.MoveNext()
```

**Comment by PFCKrutonium** [comment] 2015-09-14 23:26
Is it okay if I remove those links now?

**Comment by jmarolf** [comment] 2015-09-14 23:27
@PFCKrutonium go for it.

**Comment by PFCKrutonium** [comment] 2015-09-14 23:27
Thanks @jmarolf :D

**Comment by PFCKrutonium** [comment] 2015-09-16 19:40
Excellent, now how do I update my local version of VS? Should I just wait for MS to release an update?

**Comment by jmarolf** [comment] 2015-09-16 21:26
Unfortunately there is no way for you to deploy an updated version to VS today.  We hope to have this working soon.  In the meantime, you will need to wait for the next VS update :(

**Comment by PFCKrutonium** [comment] 2015-09-16 21:28
Will do, thanks!

**Comment by BlackMael** [comment] 2015-11-11 21:45
Probably too late now but I finally got an activity log moments after the issue occurring again.  Had a long period there where the issue stopped popping up. The last couple of days it has been occurring a lot!


[Activity.xml.txt](https://github.com/dotnet/roslyn/files/32343/Activity.xml.txt)

**Comment by jmarolf** [comment] 2015-11-11 21:53
@BlackMael Looks like the exact callstack that @PFCKrutonium reported, which gives me confidence Update 1 should fix your problem.
```
    Unable to cast object of type "Microsoft.CodeAnalysis.VisualBasic.Syntax.AssignmentStatementSyntax" to type "Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax".   
    at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxFactsService.GetExpressionOfMemberAccessExpression(SyntaxNode node)   
    at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddImport.VisualBasicAddImportCodeFixProvider.IsViableExtensionMethod(IMethodSymbol method, SyntaxNode expression, SemanticModel semanticModel, ISyntaxFactsService syntaxFacts, CancellationToken cancellationToken)   
    at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<>c__DisplayClass26_0.<FilterForExtensionMethods>b__0(IMethodSymbol method)   
    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()   
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)   
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   
    at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.FilterForExtensionMethods(SemanticModel semanticModel, ISet`1 namespacesInScope, ISyntaxFactsService syntaxFacts, SyntaxNode expression, IEnumerable`1 symbols, CancellationToken cancellationToken)   
    at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<GetNamespacesForMatchingExtensionMethodsAsync>d__21.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   
    at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<RegisterCodeFixesAsync>d__16.MoveNext()--- End of stack trace from previous location where exception was thrown ---   
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
    at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```

**Comment by BlackMael** [comment] 2015-11-12 00:01
Thank you @jmarolf. I'm gleefully looking forward to Update 1 :dancers:

**Comment by aussiealf** [comment] 2016-07-09 08:25
I still get this with VS 2015 Update 2 and Update 3, seems I might be the only one? I thought it may have been a problem with DX CodeRush but looking at this might be related to VS itself. Will try and run with the /log switch and see if I can catch it.

**Comment by spettifer** [comment] 2016-07-25 10:44
@aussiealf I've just experienced this in VS2015 Update 3 as well. Never seen it before but then I've not used VB in a few years. Will try and catch it at some point.

**Comment by intexx** [comment] 2016-10-06 19:49
It's happening frequently for me when using `System.Timers.Timer` with `System.Timers` imported on the project's References tab. It occurs during IntelliSense when I type the `.` after `Timer` (the name of the field in my console app's `Main` module).

**Comment by jmarolf** [comment] 2016-10-06 23:42
@intexx can you run visual studio with `devenv.exe /log` and then check `C:\Users[YourLogin]\AppData\Roaming\Microsoft\VisualStudio\14.0`

**Comment by intexx** [comment] 2016-10-06 23:45
Yes, I'll try this. Unfortunately, however, I told VS to 'Enable and Ignore.' I haven't seen the message since, but in this case I'd like to.

Is there a way to undo that 'ignore?'

**Comment by jmarolf** [comment] 2016-10-07 00:15
restarting visual studio resets it.  It only enable-and-ignores for the current session.

**Comment by intexx** [comment] 2016-10-07 00:23
Got it.

Restarted, added /log switch, but now it's no longer reproducing (have a ton of other errors I didn't know about, though). Will leave the switch active and report back here should it occur again.

**Comment by jmarolf** [comment] 2016-10-07 04:51
@intexx thanks

**Comment by elachlan** [comment] 2016-11-15 01:52
I am getting the error on Update 3,
`<entry>
    <record>650</record>
    <time>2016/11/15 01:47:54.823</time>
    <type>Error</type>
    <source>VisualBasicAddImportCodeFixProvider</source>
    <description>Unable to cast object of type &apos;Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE.PEMethodSymbol&apos; to type &apos;Microsoft.CodeAnalysis.INamedTypeSymbol&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.HasAccessibleStaticFieldOrProperty(ISymbol symbol, String fieldOrPropertyName)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.&lt;&gt;c__DisplayClass31_0.&lt;GetNamespacesForMatchingFieldsAndPropertiesAsync&gt;b__0(SymbolResult`1 sr)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()&#x000D;&#x000A;   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#x000D;&#x000A;   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.&lt;GetNamespacesForMatchingFieldsAndPropertiesAsync&gt;d__31.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.&lt;DoAsync&gt;d__14.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.&lt;WaitForTasksAsync&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.&lt;FindResultsInUnreferencedMetadataSymbolsAsync&gt;d__38.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.&lt;FindResultsAsync&gt;d__35.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.&lt;FindResultsAsync&gt;d__33.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.&lt;RegisterCodeFixesAsync&gt;d__32.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&lt;PerformActionAsync&gt;d__2.MoveNext()</description>
  </entry>`

**Comment by elachlan** [comment] 2016-11-16 06:10
So "PEMethodSymbol" is a "MethodSymbol" and doesn't implement the "INamedTypeSymbol" interface.

I suggest changing "HasAccessibleStaticFieldOrProperty" in `roslyn/src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs`

From:
`var namedType = (INamedTypeSymbol)symbol;`
To:
`var namedType = symbol as INamedTypeSymbol;`

This will stop the exception when casting.

**Comment by Pilchie** [comment] 2016-11-17 00:41
@jmarolf can you take another look at this?

**Comment by Pilchie** [comment] 2016-11-17 00:41
@elachlan do you know what code file you had open when your triggered this?  Can you share any of it with us?

**Comment by elachlan** [comment] 2016-11-17 01:00
Unfortunately I can't share the code. Is there a way for me to test it locally to narrow down the cause? 

I seem to get them randomly on the same code file. I was working on converting old VBA code to new vb.net code, so there was lots of code errors. The frequency seems to have reduced now I have less errors in the document.

I have tried copying the original code into a new project to see if I can get it to reproduce reliably there, but It hasn't worked so far.

**Comment by elachlan** [comment] 2016-11-17 03:47
I got it to reproduce. Its a bit complicated in my case though.

The error occurs while using intellisense.

I have a property on my form for an instance of a class called Logic. This class inherits from a base class called LogicBase. It contains a method called "BuildCode". 

When I trigger intellisense on the form code and type "Logic.bu" to filter the results and then have the selection on "BuildCode", it triggers the error.

I can also trigger the error by hovering over "Logic.bu" to trigger the "Show potential code fixes" popup.

Hope that helps.

**Comment by elachlan** [comment] 2016-11-22 06:15
Is there enough detail there? I can try and track it down a little more. But so far my attempts to reproduce it in a separate solution have no worked. 

If someone can explain what that particular piece of code is supposed to be doing, I might be able to narrow it down further.

**Comment by Pilchie** [comment] 2016-11-23 01:54
I'll defer to @jmarolf to comment further, but keep in mind that this is the Thanksgiving holiday week here in the US, and many people are out on vacation right now.

**Comment by jmarolf** [comment] 2016-11-23 09:45
@elachlan thanks, I'll try out the repro.

**Comment by jmarolf** [comment] 2016-12-03 17:20
@elachlan I can't get this to repro, can you give me the code for LogicBase.vb and Logic.vb?

**Comment by kakins** [comment] 2016-12-04 14:57
I'm experiencing the same issue, but with multiple "provider" errors, such as SimplifyTypeNamesCodeFixProvider.  I have tried everything from disabling ReSharper to reverting to VS settings from a month ago where everything was working fine.

**Comment by CyrusNajmabadi** [comment] 2016-12-04 21:17
@kakins Please open a new issue.  This issue is about a crash in "visualbasicaddimportcodefixprovider".  If you're experiencing crashes in other CodeFixProviders, then we'll want to track them separately.

**Comment by elachlan** [comment] 2016-12-04 21:42
@jmarolf I will try and isolate it today by copying them into a new project. I will then remove functions one by one until I see a change.

**Comment by jmarolf** [comment] 2016-12-12 21:55
@elachlan have you had any time to try and get a repro for this?

**Comment by elachlan** [comment] 2016-12-12 22:02
I found something just now as I was typing. I'll keep digging and let you know.

It wasn't reproducing, even when I copied all the files over. But then I added our data access project to the solution and it throws the error right away.

**Comment by elachlan** [comment] 2016-12-12 22:42
Here is what I managed to get to reproduce the issue. It doesn't make any sense to me.
[codefixprovider_repro.zip](https://github.com/dotnet/roslyn/files/647440/codefixprovider_repro.zip)

**Comment by jmarolf** [comment] 2016-12-12 23:29
@elachlan thanks so much!

**Comment by intexx** [comment] 2016-12-13 04:23
I can repro it using the code @elachlan provided.

It crashes when I strike any character on the keyboard after the period (.), but only when the `Logic` property isn't qualified with `Me`.

In other words, this doesn't produce the error:

    Me.Logic.T

Nor does this:

    Dim oLogic As New Logic
    oLogic.T

But this does:

    Logic.T

It also doesn't seem to matter whether `Logic` is a property or a field. And it occurs whether or not the `Logic` class is wrapped in the `TestApp.Forms` namespace.

HTH

**Comment by elachlan** [comment] 2016-12-13 04:32
If you remove the TestApp.Data project it won't error. It will only error when it is added. To get it to error out, I had to copy an existing project and remove its code. 

I don't think its a code issue, but maybe a setting on the project file?

**Comment by jmarolf** [comment] 2016-12-14 06:36
@elachlan I can repro this on Visual Studio 2015 Update 3 and get the same call stack but I cannot repro this on Visual Studio 2017 RC.  I looks like the error was fixed in the metadata reader.

**Closed by jmarolf** 2016-12-14 06:36 UTC
Labels: Area-IDE, Bug

**Comment by elachlan** [comment] 2016-12-14 06:46
@jmarolf Thanks for following up on this.
