### ISSUE TITLE
is operator with pattern matching not work as expertly

### ISSUE THREAD

**Issue by sajadafaghiy** [dotnet/roslyn#70379] opened 2023-10-13 18:21 UTC
**Version Used**: 4.8.0

**Steps to Reproduce**:

1. Create new console application and paste below code:
```csharp
internal class Program
{
    static void Main(string[] args)
    {
        int y;
        Point point = new()
        {
            X = -1,
            Y = -1
        };

        if (point is { X: < 0, Y: < 0 } validPoint)
        {
            // If both x or z are less than 0, the point is assumed not to be valid and return.
            return;
        }

        // Here the point is valid and the program should continue,
        // but the compiler gives error CS0165
        Console.WriteLine(validPoint);
    }

    public class Point
    {
        public int X { get; set; }

        public int Y { get; set; }

        public override string ToString()
        {
            return $"x: {X}, y: {Y}";
        }
    }
}
```

**Diagnostic Id**: CS0165
Error  CS0165  Use of unassigned local variable 'validPoint'

**Expected Behavior**:
Can continue the process of running the program without errors.

**Actual Behavior**:
The error [CS0165](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0165) prevents the program from running.

**Comment by DoctorKrolic** [comment] 2023-10-13 21:15
I think you misunderstand how assignment patterns work. `validPoint` is assigned to if and only if the whole pattern is matched. Therefore in your example `validPoint` actually contains invalid point with `X` and `Y` `< 0` and only inside `if` block

**Comment by CyrusNajmabadi** [comment] 2023-10-13 21:24
Closing out as by design.  Since the pattern failed, 'validPoint' is not definitely assigned in the 'else' section.

**Closed by CyrusNajmabadi** 2023-10-13 21:24 UTC
Labels: Area-Compilers, untriaged
