### ISSUE TITLE
Need a simpler searching of word variants, when typing letters.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47807] opened 2020-09-17 19:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1179049/need-a-simpler-searching-of-word-variants-when-typ.html)._

---
<p>Eng:</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/155571-%d0%b1%d0%b5%d0%b7%d1%8b%d0%bc%d1%8f%d0%bd%d0%bd%d1%8b%d0%b8.png"> Image:155571-безымянныи.png</a></p><p>Now the searching of word variants (when typing letters) occurs according to some incomprehensible algorithm ...
Please, make the MOST SIMPLE searching of words while typing (containing the same order in the searched word)!
Due to the fact that now the operation of the existing word searching algorithm is not clear, the functionality of the existing algorithm is actually not used!</p> <p>RU:</p><p>Сейчас подборка вариантов слов (при наборе букв) происходит по какому-то непонятному алгоритму...
Пожалуйста, сделайте САМУЮ ПРОСТУЮ подборку вариантов слов при наборе букв (содержащей тот же порядок в искомом слове)!
В связи с тем, что сейчас не понятна работа существующего алгоритма подбора слов - функциональность существующего алгоритма фактически не используется!</p> <p>VS 2019 (16.7.3)</p>

---
#### Feedback Bot on 9/10/2020, 03:37 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-09-17 21:53
@sharwell this is a dupe of the issue where someone wants to write an all lower-case string and have it match as long as all the characters can be found in order in the target name.  I couldn't find the original bug though.  If you remember which it is, can you dupe this against it?

**Comment by sharwell** [comment] 2020-09-17 22:11
Duplicate of #46677

**Closed** 2020-09-17 22:12 UTC
Labels: Resolution-Duplicate

**Comment by CyrusNajmabadi** [comment] 2020-09-17 22:50
Thanks!
