### ISSUE TITLE
[Compilers] Generated IL for is check against constant

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#20642] opened 2017-07-05 15:03 UTC
**Version Used**: 
d8c89de9bf165693a92f31bcef036bebd031780f

**Steps to Reproduce**:

1. Check the code/IL gen here https://gist.github.com/Therzok/6562398fb9a1fe87b407bda9d1c6a3db
2. Or here: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBuAWACh8jiA6AJQFcA7GNMOOgSTcQHsADgGVEANzQBjOFAqUqOAEwEAshDQsAwhmhQqAbyoECk/i1gENMAmACep89YC8BAKxzjsCO0lEALKrqLAAUJHgA2gC6BBAIAOZQAJRGBIaUAJDpVgQAHgQuAMxymWgAZgTBeWhQNvZmsImpVFSZAL4p7ZSdQA=
3. See that the generated IL is inefficient

**Expected Behavior**:
If a value type implements IEquatable<T>, I'd assume that `IEquatable<T>.Equals (T other)` would be used on the left expression with the right expression as a parameter. This could be done via `EqualityComparer<T>.Default.Equals (T a, T b)`

**Actual Behavior**:
`object.Equals(object, object)` is being used, which leads to inefficient code when using value types.

**Comment by gafter** [comment] 2017-07-05 16:22
This scenario doesn't look very realistic. Why would the user's source code use pattern-matching here instead of `==`? And why should the generated code use either of those methods when it could use a single IL equality instruction as if you had written `==`?

**Comment by gafter** [comment] 2017-07-05 16:24
Duplicate of https://github.com/dotnet/roslyn/issues/12813

**Comment by Therzok** [comment] 2017-07-05 16:53
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is

I came to this example by looking at docs for the is keyword. Albeit it explicitly states object.Equals is used, not sure why it's shown as an example. Possibly this should be filed under docs, if it is so by design.

**Comment by gafter** [comment] 2017-07-05 17:41
The spec does say

> The constant [sic] expression is evaluated as follows:
> - If expr and constant are integral types, the C# equality operator determines whether the expression returns `true` (that is, whether `expr == constant`).
> - Otherwise, the value of the expression is determined by a call to the static `Object.Equals(expr, constant)` [sic] method.

Two errors here: first, it isn't a constant expression, it is a pattern-matching expression.

Second, we do the operand of `Object.Equals` in the opposite order.

This bug report is that we fail to do the first bullet correctly. Reopening.

**Comment by gafter** [comment] 2018-03-18 00:08
Closing as a dup of #12813

**Closed by gafter** 2018-03-18 00:08 UTC
Labels: Area-Compilers, Bug, New Language Feature - Pattern Matching, Tenet-Performance
