### ISSUE TITLE
Locals introduced by `var` pattern are not properly colorized

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61700] opened 2022-06-04 07:59 UTC
**Version Used**:
https://github.com/dotnet/roslyn/commit/b1fbb442e69354081785032f9fbe65f8eb09d33f

**Steps to Reproduce**:
```cs
var a = string.Empty;

if (a is var anotherVar)
{
    Console.WriteLine(anotherVar);
}
``` 

**Expected Behavior**:
`anotherVar` is colorized as local in both cases

**Actual Behavior**:
![devenv_wIvL635l4r](https://user-images.githubusercontent.com/70431552/171990388-e88bc4c0-1da6-4286-99c9-19fc6419345f.png)

**Comment by Youssef1313** [comment] 2022-06-04 09:05
There is a PR already: https://github.com/dotnet/roslyn/pull/59735

**Comment by Youssef1313** [comment] 2022-06-04 09:09
Duplicate of https://github.com/dotnet/roslyn/issues/59484

**Comment by DoctorKrolic** [comment] 2022-06-04 09:16
I'll left this open for now, so roslyn team members can see it and probably pay a bit more attention to the opened PR

**Comment by CyrusNajmabadi** [comment] 2022-06-04 16:37
Closing out as dupe. Thanks!

**Closed by CyrusNajmabadi** 2022-06-04 16:37 UTC
Labels: Area-Compilers, untriaged
