### ISSUE TITLE
Imports Statement breaks compiler

### ISSUE THREAD

**Issue by bellenberger1** [dotnet/roslyn#8764] opened 2016-02-16 22:12 UTC
We had a project where a developer used the syntax of "Imports <alias> = <namespace>" in a vb file. The issue was the value for <namespace> was something that didn't exist. The line produced a warning but the project would still compile in 2010. In 2015, building the project it will produce "vbc.exe" exited with code -2146232797 error. If you take out the "<alias> =" in the imports statement, the project will compile in 2015.

I attached a sample project to demonstrate what was going on. 

[ImportsTest.zip](https://github.com/dotnet/roslyn/files/133348/ImportsTest.zip)

**Comment by jaredpar** [comment] 2016-03-04 19:14
Thanks for reporting.  This looks to be a duplicate of #7236.  This fix will appear in VS 2015 Update 2.

**Closed by jaredpar** 2016-03-04 19:14 UTC
Labels: Area-Compilers
