### ISSUE TITLE
Implement interface abstractly creates concrete explicit members when existing member names conflict with interface member names

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63947] opened 2022-09-12 17:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Implement-interface-abstractly-creates-c/1696666)._

---
[severity:It bothers me. A fix would be nice]
Suppose you have this code:

```csharp
public interface IInterface
{
    string? Name { get; }
}
public abstract class Class1
    : IInterface
{
    public string[] Name { get; }

public Class1(
        string[] name)
    {
        Name = name;
    }
}
```

The line with `: IInterface` shows this error:

* `error CS0738: 'Class1' does not implement interface member 'IInterface.Name'. 'Class1.Name' cannot implement 'IInterface.Name' because it does not have the matching return type of 'string'`

The Quick Actions (codefixes) on that line include the option “Implement interface abstractly”:

! [Implement interface abstractly] (https://i.imgur.com/LYeVj2M.png)

However, when I run that Quick Action (codefix), I get the following result:

```csharp
public interface IInterface
{
    string? Name { get; }
}
public abstract class Class1
    : IInterface
{
    public string[] Name { get; }
    string? IInterface.Name { get; }

public Class1(
        string[] name)
    {
        Name = name;
    }
}
```

That is, the interface is implemented concretely as the added property is an auto-implemented property instead of an abstract property. Instead, I would expect code like the following to be generated.

```csharp
public interface IInterface
{
    string? Name { get; }
}
public abstract class Class1
    : IInterface
{
    public string[] Name { get; }
    string? IInterface.Name => Name1;
    protected abstract string? Name1 { get; }

public Class1(
        string[] name)
    {
        Name = name;
    }
}
```

I expect this code because the strategy of creating new properties with numbers when conflicts are encountered is used by Quick Actions like “Replace 'GetName' with property”:

! [“Replace 'GetName' with property” Quick Action] (https://i.imgur.com/B6NbIiC.png)

---
#### Feedback Bot on 3/20/2022, 05:16 AM: 

(private comment, text removed)
#### Fire Zhang [MSFT] on 3/23/2022, 00:48 AM: 

(private comment, text removed)
#### Nathan Phillip Brink (binki) on 3/23/2022, 07:01 AM: 

(private comment, text removed)
#### Fire Zhang [MSFT] on 3/23/2022, 06:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:17
This is working as intended.  Wehn we cannot actually implement hte member abstractly, we implement it explicitly as that's the only feasible way to implement it.  Note that `protected abstract string? Name1 { get; }` is not an actual implementation of hte interface method.  It's some new bridge method the user is using to try to allow for overriding behavior. But it exists outside of the interface inheritance hierarchy.

**Comment by binki** [comment] 2022-09-12 19:24
What I expect from the implement abstractly CodeFix is nonconcrete implementations. If I were to derive a class from it, everything which I had elected to have abstract implementations should cause a compiler error.

The results above are surprising because the output of the CodeFix is a fully implemented (albeit autoimplemented) property. It would be better for it to not create that property in the first place (preserving the compile-time error), less bad but OK for it to create `string? IInterface.Name { get => throws new NotImplementedException(); }` (turning a compile time error into a runtime error), but quite bad for it to create something which compiles without requiring the developer (converting a compile-time error into a fully silent bug).

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:27
> What I expect from the implement abstractly CodeFix is nonconcrete implementations

There can't be non-concrete implementations of this particular interface method though due to teh collusino with the existing method.  The interface method must be explicit.  At that point though, the strategy you would like to take for your inheritance (outside of the inheritance of the interface method itself) is up to you :)

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:28
> It would be better for it to not create that property in the first place (preserving the compile-time error), less bad but OK for it to create string? IInterface.Name { get => throws new NotImplementedException(); }

You can control this with this setting i believe:

![image](https://user-images.githubusercontent.com/4564579/189739143-55b55e2e-9f1f-4e9e-a762-d7a98f67bf73.png)

We will tehn generate a throwing member.

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:29
> but quite bad for it to create something which compiles without requiring the developer (converting a compile-time error into a fully silent bug).

The use of 'prefer auto props' was added because of much feedback from people saying they'd rather just have this be an auto-prop more often than a throwing member they have to fix.  Both options are available depending on your preference.

**Comment by binki** [comment] 2022-09-12 19:36
For normal properties, auto properties makes a lot of sense. For explicit interface implementations, that almost never makes sense. Explicit interface implementations are almost always supposed to be glue to different concrete members. I’d expect that not to follow the same rules wrt auto props as nonexplicit members.

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:38
> For normal properties, auto properties makes a lot of sense. For explicit interface implementations, that almost never makes sense. Explicit interface implementations are almost always supposed to be glue to different concrete members.

I don't have any data indicating to me that that is the case.  There are many people who just implement explicitly as the standard way they prefer to implement, keeping the interface members out of the surface area of their concrete type, so they are only available through the interface.  Those people have just as much a need for normal auto-props as anyone else.

> I’d expect that not to follow the same rules wrt auto props as nonexplicit members.

I posit that will just be confusing as users will say "hey, i asked to generate it explicitly, and i said i wanted auto-props, and you ignored that".

**Comment by binki** [comment] 2022-09-12 19:41
> > For normal properties, auto properties makes a lot of sense. For explicit interface implementations, that almost never makes sense. Explicit interface implementations are almost always supposed to be glue to different concrete members.
> 
> I don't have any data indicating to me that that is the case. There are many people who just implement explicitly as the standard way they prefer to implement, keeping the interface members out of the surface area of their concrete type, so they are only available through the interface. Those people have just as much a need for normal auto-props as anyone else.

Ah, interesting. For me, I mostly end up with explicit interface implementations when that is required (e.g., due to a name collision) in which case I would never want a discrete concrete member but always implementation via another member. I.e., as glue—just like how implicit interface implementation works under the hood.

I still think that the fact that the CodeFix is clearly labeled “abstract” that it creating a concrete member is wrong. I’d rather it not create that member at all. Would such a change be possible? I still think that my original solution of creating the differently-numbered property has a precedent in the “Replace 'GetName' with property” CodeFix. And it would be more useful and actually doing the expected thing since I asked for abstract members…

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:44
> I still think that the fact that the CodeFix is clearly labeled “abstract” that it creating a concrete member is wrong.

The philosophy of this fixer (since introduced back in 2005) was: get you to a state where you implement the interface.  It has knobs to control the default way to do that, but it may have to fall back to the only means possible when those knobs are not compatible with the the rest of your type as exists at the present.  

In other words, it means "generate abstractly when possible, but fall back to whatever is necessary when not".  unfortunately, that doesn't fit on a bumper-sticker, so we have to reduce it down to a more manageable morsel.  As above though, we've had this behavior for nearly 17 years now, and you're the first to object to it :)

>  I’d rather it not create that member at all. Would such a change be possible?

Generally speaking, no.  That would likely be much more confusing for users.  e.g. "i asked you to implement this interface, and now i'm still getting the error that this member isn't implement.  gaaah!  and now i have to go find out the signature of the things missing and manually write them all out.  this is soooo annoying. :("

**Comment by CyrusNajmabadi** [comment] 2022-09-12 19:45
> I still think that my original solution of creating the differently-numbered property has a precedent in the “Replace 'GetName' with property” CodeFix. And it would be more useful and actually doing the expected thing since I asked for abstract members…

**Comment by CyrusNajmabadi** [comment] 2024-11-22 04:29
Closing out due to lack of any more feedback on this.  This is working as intended.

**Closed by CyrusNajmabadi** 2024-11-22 04:29 UTC
Labels: help wanted, Area-IDE, Feature Request
