### ISSUE TITLE
Multiple enumerations of IEnumerable Warning

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50408] opened 2021-01-12 22:00 UTC
Analyzer warning for multiple enumerations of an IEnumerable<T>.

![image](https://user-images.githubusercontent.com/46729679/104379285-1fec8800-54de-11eb-80c4-2820e58f2c96.png)

Other example: 

``` 
IEnumerable<string> cards = GetCards();
foreach (var card in cards)
    Console.WriteLine("Added " + card);
var allCards= new StringBuilder();
foreach (var card in cards)
    allCards.Append(card + " ");
``` 
Assuming that GetCards() returns an IEnumerable<string>, this is enumerating the collection twice in the two foreach statements. 

The code fix can convert the sequence to an array or a list at variable initialization:

```
List<string> cards = GetCards().ToList();
```

**Comment by Youssef1313** [comment] 2021-01-13 04:59
This may fit more in roslyn-analyzers for performance analyzers.

**Comment by mikadumont** [comment] 2021-01-13 16:54
> This may fit more in roslyn-analyzers for performance analyzers.

Yes, placing it here initially so we can go over it in our design meeting.

**Comment by sharwell** [comment] 2021-01-19 21:24
@mavasani should we move this to roslyn-analyzers for triage there?

**Comment by mavasani** [comment] 2021-01-19 21:42
@sharwell We already have https://github.com/dotnet/roslyn-analyzers/issues/3133, so seems this can be closed as a duplicate.

**Comment by sharwell** [comment] 2021-01-19 21:50
Duplicate of dotnet/roslyn-analyzers#3133

**Closed by sharwell** 2021-01-19 21:50 UTC
Labels: Area-Analyzers, Feature Request, Need Design Review
