### ISSUE TITLE
dotnet format fails with "Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0...'. The system cannot find the file specified."

### ISSUE THREAD

**Issue by korDen** [dotnet/roslyn#68115] opened 2023-05-05 18:04 UTC
Freshly installed Visual Studio 2022 Preview.

dotnet add package Microsoft.CodeAnalysis installs version 4.5
dotnet add package Microsoft.CodeAnalysis  -v 4.6 FAILS with 

error: NU1102: Unable to find package Microsoft.CodeAnalysis with version (>= 4.6.0)
error:   - Found 141 version(s) in nuget.org [ Nearest version: 4.6.0-1.final ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error: Package 'Microsoft.CodeAnalysis' is incompatible with 'all' frameworks in project 'C:\Users\korDen\source\repos\WebApplication1\WebApplication1\WebApplication1.csproj'.

Somehow 4.6.0-1.final is NOT considered to be >= 4.6.0
(same with dotnet add package Microsoft.Net.Compilers.Toolset)

Installing 4.6.0-1.final doesn't help either, dotnet format still fails with 

Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

**Comment by huoyaoyuan** [comment] 2023-05-05 19:09
Per SemVer, 4.6.0-final.1 is lower than 4.6.0 because it has preview label. Roslyn 4.6.0 is not yet released (together with VS17.6 stable).

Note that assembly version and NuGet package version aren't necessarily the same, and the former can't have non-number part.

The package referenced by your project shouldn't be loaded by `dotnet format`. It should load the one in your SDK.

The suggestion is to check version of `dotnet format` tool first, and check `dotnet --info` under your project. The issue should probably be reported to dotnet/format repo.

**Comment by jcouv** [comment] 2023-05-06 16:51
Tagging @JoeRobich to advise. The latest version I see on nuget.org is `4.6.0-1.final`, but I would have expected to see `4.6.0` there too.

**Comment by JoeRobich** [comment] 2023-05-08 18:24
@jcouv VS 17.6 is still in preview so there is no 4.6.0 package to install because it has not released.

As for the dotnet-format issue, the 7.0.x branch of dotnet-format needs to have a more recent Roslyn inserted. It is still on 4.5 which is why it is unable to locate 4.6.0. @sharwell

**Comment by alexdresko** [comment] 2023-06-01 14:19
@JoeRobich I'm having the same problem and I'm on VS 17.6.2 official.

**Comment by JoeRobich** [comment] 2023-06-01 15:56
@alexdresko This issue will be resolved with the next release of dotnet SDKs. Marking as duplicate of https://github.com/dotnet/sdk/issues/32598

**Closed by JoeRobich** 2023-06-01 15:56 UTC
Labels: Resolution-Duplicate, Question, Area-Infrastructure, untriaged

**Comment by alexdresko** [comment] 2023-06-01 18:56
@JoeRobich Is there a way for me to get back to the previous SDK? Can I uninstall, then reinstall? I don't want to break things anymore than they are on my machine.
