### ISSUE TITLE
Closing a document brings back stale diagnostics

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70042] opened 2023-09-20 21:02 UTC
**Version Used**: 

* Analysis scope set to Open Documents via solution explorer
* LSP pull diagnostics enabled

**Steps to Reproduce**:

1. Introduce a build warning
2. Build the project
3. Open the document with the build warning
4. Fix the build warning
5. Close the document with the build warning

**Expected Behavior**:

* After step (2), the warning appears in the error list
* After step (4), the warning disappears from the error list

**Actual Behavior**:

* After step (2), the warning appears in the error list
* After step (4), the warning disappears from the error list
* After step (5), the warning reappears in the error list

**Comment by CyrusNajmabadi** [comment] 2023-09-20 21:18
@AmadeusW @kayle

**Comment by kayle** [comment] 2023-09-21 14:33
What would you expect if you close the file in step 5 without saving?

**Comment by CyrusNajmabadi** [comment] 2023-09-21 16:29
> What would you expect if you close the file in step 5 without saving?

the diagnostic would be gone.  you'd have to rebuild to get it again.  we don't track the impacts of mutations (it's nearly impossible, since any change anywhere can have impacts on diagnostics everywhere).

so you might change code in a different file which fixes the diag in this file, save it, then not save *this* file that contains the diagnostic.  That shouldn't bring the diagnostic back.  

This is the experience in roslyn today, and it's fine.  Things always move *forward*.  Builds represent results for an event in the past.  And even if varying changes happen (or get tossed) past that point, it still represents the past, and may have to to be rerun to represent the present.

**Comment by kayle** [comment] 2023-09-26 13:49
The latest dogfooding build should now match the expected behavior.

**Comment by CyrusNajmabadi** [comment] 2023-09-26 16:46
Thanks @kayle !

**Comment by mavasani** [comment] 2023-10-10 11:21
@kayle @CyrusNajmabadi The original issue described by @sharwell seems to be fixed in the latest build. However, I am seeing duplicate and stale diagnostics with Full solution analysis enabled. See the repro below:

![LSP_FSA](https://github.com/dotnet/roslyn/assets/10605811/da86b00f-4cfb-4904-9933-edbd92ae7adc)

**Comment by kayle** [comment] 2023-10-10 14:24
Thanks @mavasani - I can fix that issue.

What do you expect after closing the document? Currently the warning will go away until the next workspace request regenerates it.

**Comment by CyrusNajmabadi** [comment] 2023-10-10 14:47
> Currently the warning will go away until the next workspace request regenerates it.

That is my expectation.  "Latest wins". So the document superseded the workspace. Until workspace runs again, the warning will be gone.

**Comment by CyrusNajmabadi** [comment] 2023-10-20 18:36
@kayle  can you link to your PR for this?  I'd like to close this out.  Thanks!

**Comment by kayle** [comment] 2023-10-20 19:29
https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/503146?_a=files

**Comment by CyrusNajmabadi** [comment] 2023-10-23 19:53
Fixed with [https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/503146](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/503146?_a=files).  Thanks!

**Closed by CyrusNajmabadi** 2023-10-23 19:53 UTC
Labels: Area-Analyzers
