### ISSUE TITLE
RenameSymbolAsync doesn't rename the symbol in the implementing class

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46663] opened 2020-08-10 07:19 UTC
If I rename a method parameter in an interface through RenameSymbolAsync, it doesn't get updated in the implementing class.

For example:

```csharp
public interface I
{
    void MyMethod(string oldName); // Rename this to newName
}

public class C : I
{
    public void MyMethod(string oldName) { }
}
```

The result is:

```csharp
public interface I
{
    void MyMethod(string newName); // Rename this to newName
}

public class C : I
{
    public void MyMethod(string oldName) { }
}
```

I was expecting it to be:

```csharp
public interface I
{
    void MyMethod(string newName); // Rename this to newName
}

public class C : I
{
    public void MyMethod(string newName) { }
}
```

Found this while writing code fix in roslyn-analyzers repo. (https://github.com/dotnet/roslyn-analyzers/pull/3706)

**Comment by sharwell** [comment] 2020-08-10 14:37
I'm fairly certain this is by design. Code fix implementations can manually located and rename related symbols, but are not required to.

**Comment by Youssef1313** [comment] 2020-08-10 14:42
@sharwell Thanks for reply.

Was there any reason in designing that API not to rename the related symbols?
It would be much easier if that work is done inside the RenameSymbolAsync method.

**Comment by CyrusNajmabadi** [comment] 2020-08-10 20:56
This was by design as cascading here was felt to be innapropriate when we originally tried it.  i.e. people wanted the scope of change here to not include optional things like this.  We considered an option for it, but there wasn't much demand.  I would likely take a PR here that added a programattic option to the rename api to do this.

**Comment by Evangelink** [comment] 2020-09-29 08:05
So what's the recommended way to rename the symbols? It seems we can do something using the workspace but as far as I understand this isn't available from the roslyn-analyzers code-fixes.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 03:53
Closing out as this is by design.

**Closed by CyrusNajmabadi** 2024-10-25 03:53 UTC
Labels: Area-IDE, Concept-API, Resolution-By Design, Feature - Rename
