### ISSUE TITLE
Can't resolve/generate types for an unnamed field/method

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13211] opened 2016-08-16 23:56 UTC
``` C#

using System;

namespace Microsoft.VisualStudio.ProjectSystem.LanguageServices
{
    internal class CommandLineParser
    {
        public CommandLineArguments$

    }
}
```

Press CTRL+. at the $
__Expected:__ To be prompted to resolve or generate types.
__Actual:__ Nothing

The compiler already knows that this is a type, so not sure what's stopping these features from working:

```
CS0103	The name 'CommandLineArguments' does not exist in the current context.	
```

**Comment by davkean** [comment] 2016-08-17 00:51
Is this a regression? It feels like I'm hitting this a lot today. //cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2016-08-17 01:01
Debugged through this.  We never get called into AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync.  Maybe an analyzer engine issue?

**Comment by davkean** [comment] 2016-08-17 15:21
tag @heejaechang @mavasani

**Comment by mavasani** [comment] 2016-08-17 15:29
Is the relevant intellisense diagnostic generated? If so, this might be an issue with the code fix engine.

**Comment by heejaechang** [comment] 2016-08-18 06:48
this might be same issue as this
https://github.com/dotnet/roslyn/issues/12651
https://github.com/dotnet/roslyn/pull/13242

**Comment by srivatsn** [comment] 2016-10-21 06:39
Still seeing this.

**Comment by mavasani** [comment] 2016-10-27 17:29
This also repros in Dev14 (and probably even earlier). We don't get a code fix here because of syntax errors, you haven't even completed the declaration. If you type `public CommandLineArguments$ foo` then the code fix is indeed offered.

**Comment by CyrusNajmabadi** [comment] 2016-10-27 18:01
This used to work, and even if it didn't work in Dev14, it *should* work.  CodeActions are present in all sorts of error code, and users like the "Forward typing" approach where they are in the middle of typing legal code, but still want to invoke code actions along the way.

**Comment by mavasani** [comment] 2016-10-27 18:02
This doesn't meet the RC bar though.

**Comment by CyrusNajmabadi** [comment] 2016-10-27 18:04
That's fine.  I'm going to test this out on previous VSs to see where this regressed.  Note: my guess is that the root cause here is the usage of "incomplete member" and the compiler not binding those.  This is, IMO, an innapropriate parse here.  This should either just be a FieldDeclaration with a missing name, or the compiler needs to bind IncompleteMembers.

**Comment by mavasani** [comment] 2016-10-27 18:33
I quickly checked under the debugger and both the analyzer and debugger engine are fine. [AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync](http://index/?query=AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync&rightProject=Microsoft.CodeAnalysis.Features&file=CodeFixes%5CGenerateMember%5CAbstractGenerateMemberCodeFixProvider.cs&line=32) gets invoked with 1 target name, but it doesn't return any code actions.

**Comment by CyrusNajmabadi** [comment] 2016-10-27 18:42
Investigating

**Closed** 2016-10-28 20:56 UTC
Labels: Area-IDE, Bug

**Comment by davkean** [comment] 2016-11-15 02:13
@CyrusNajmabadi Would your code change have also fixed Resolve type?

**Comment by CyrusNajmabadi** [comment] 2016-11-15 02:14
i don't know what you're asking :)

**Comment by davkean** [comment] 2016-11-15 02:16
For my repro, I wanted for "Resolve namspace" code action to appear. Does it after your change?

**Comment by CyrusNajmabadi** [comment] 2016-11-15 02:23
Do you mean 'Add-Using'?  If so, yes that should work.
