### ISSUE TITLE
CS1584, CS1658 produced on cref to method with function pointer parameter

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#50559] opened 2021-01-16 16:16 UTC
**Version Used**: VS 16.9 Preview 4 (30912.315.main)

C# apparently cannot take a cref to a method where the full signature is specified if the signature contains a function pointer type.
Note that C# will even _suggest_ via completion the syntax that then produces two warnings.

![d063ac82-472b-486c-935e-b44df9ca84c5](https://user-images.githubusercontent.com/3548/104816918-70fcc480-57db-11eb-875f-7c1b18217f39.gif)

**Steps to Reproduce**:

[Sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGSAmIDUAfAAQCYBGAWAChiACABQEkA7ANwHsBrOSgb0uv+oB6YdQA8AS0YALROJiZWAY2qKEcAGbUAvNQBEADQAUmOABs4AcwjwAVNQCujSIwgW4mANoBleYoinTAF1uAgAWGyRqMIjqSRgAXwBKXUEAPj4BOMQXUyiSADYHRigIdThYxhhqAE1DRO1U6hgpBFYAd2pGOA6AOVYYejAAB3MwOEr3AFEAD0U4IZhxVkY6gG5KDP4shBy8wscSsoqqoxNzK1si51d3b19/INFoyOfjxvp1AGEH4AhFdnqWkazVaHS6vX6gxGcDGE0wMzmCyWK0S6wo8UoQA===)

```cs
using System;
class PInvoke
{
    /// <inheritdoc cref = "X(delegate* unmanaged[Stdcall]{void*, void*, int})"/>
    internal static unsafe int Y() => throw new NotImplementedException();

    internal static unsafe int X(delegate* unmanaged[Stdcall]<void*, void*, int> IfCallback) => throw new NotImplementedException();
}
```

**Expected Behavior**:

No warnings

**Actual Behavior**:

```
Severity	Code	Description	Project	File	Line
Warning	CS1658	) expected. See also error CS1026.	GenerationSandbox.Tests (net472), GenerationSandbox.Tests (net5.0), GenerationSandbox.Tests (netcoreapp3.1)	D:\git\CsWin32\test\GenerationSandbox.Tests\Exp.cs	25
Warning	CS1584	XML comment has syntactically incorrect cref attribute 'X(delegate* unmanaged[Stdcall]{void*, void*, int})'	GenerationSandbox.Tests (net472), GenerationSandbox.Tests (net5.0), GenerationSandbox.Tests (netcoreapp3.1)	D:\git\CsWin32\test\GenerationSandbox.Tests\Exp.cs	25
```

**Comment by svick** [comment] 2021-01-16 21:45
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/48363.

**Comment by jaredpar** [comment] 2021-01-20 23:14
Agree that looks like a dupe. That had fallen off my radar though. Got it properly triaged and closing this out as a dupe of it.

**Closed by jaredpar** 2021-01-20 23:14 UTC
Labels: Area-Compilers, Bug
