### ISSUE TITLE
CLI: Task failed because "" was not found.

### ISSUE THREAD

**Issue by ektrah** [dotnet/roslyn#22257] opened 2017-09-21 18:00 UTC
**Version Used**:

* Microsoft.NETCore.Compilers --version 2.6.0-beta1-62119-06

2.6.0-beta1-62107-06 with `InitialTargets="MakeCompilerScriptsExecutable"` [removed](https://github.com/dotnet/roslyn/issues/21970) exhibits the same problem. The last working version seems to be 2.6.0-beta1-62106-06.

**Steps to Reproduce**:

1. docker run -it --rm microsoft/dotnet:2.0-sdk
2. mkdir ~/project
3. cd ~/project
4. dotnet new console
5. dotnet add package Microsoft.NETCore.Compilers --version 2.6.0-beta1-62119-06 --source https://dotnet.myget.org/F/roslyn/api/v3/index.json
6. dotnet build

**Expected Behavior**:

No error.

**Actual Behavior**:

> /root/.nuget/packages/microsoft.netcore.compilers/2.6.0-beta1-62119-06/tools/Microsoft.CSharp.Core.targets(84,5): error MSB3082: Task failed because "" was not found. [/root/project/project.csproj]

Most likely related to https://github.com/dotnet/roslyn/pull/21673.

Might be because $(CscToolPath) is empty and $(CscToolExe) contains the full path:

$(CscToolExe) = "/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh"  
$(CscToolPath) = ""

(And shouldn't it use the RunCsc script from the package?)

cc @khyperia

**Comment by khyperia** [comment] 2017-09-21 18:49
I'm pretty sure this is fixed in master, by a crazy coincidence. The problem was (I think) that this PR https://github.com/dotnet/roslyn/pull/21673 `build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props` removed the overrides for CscToolPath. However, the merge of `ref readonly` https://github.com/dotnet/roslyn/commit/b23943ed6da7c9542c0a213fde102feab0a11bb6 brought in those lines again. This merge occurred last night, and is in no nuget package right now (I think). I think the Linux package may be broken though (when it's built on windows), due to a bad merge forgetting to re-add `InitialTargets="MakeCompilerScriptsExecutable"`.

Thanks for the bug report - it has quite a complicated root cause!

**Comment by ektrah** [comment] 2017-09-27 09:13
I can confirm that 2.6.0-beta1-62126-01 works.

I'm not sure if the `chmod +x` is necessary, so I guess either `InitialTargets="MakeCompilerScriptsExecutable"` should be added back or the `MakeCompilerScriptsExecutable` target be removed.

**Comment by jcouv** [comment] 2017-09-29 17:26
@khyperia Can this be resolved, or is there an action item?

**Comment by khyperia** [comment] 2017-09-29 17:46
@jcouv The original issue can be resolved. There is the additional issue mentioned that `MakeCompilerScriptsExecutable` should be fully added/removed, but that's a tangent.

**Comment by jcouv** [comment] 2017-09-29 19:07
Thanks. I'll let you make sure there is a tracking issue for the tangent.
Closing this one

**Closed by jcouv** 2017-09-29 19:07 UTC
Labels: Area-Compilers
