### ISSUE TITLE
Calling this() from struct constructor removes nullable warnings

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#38332] opened 2019-08-28 07:47 UTC
**Version Used**: master

**Steps to Reproduce**:

Compile the following:

```csharp
#nullable enable
public struct C
{
    string _a;
    object _b;
    
    public C(string a) : this()
    {
        _a = a;
    }
    
    public C(object b) : this()
    {
        _b = b;
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAZgtgXwGMYKBhRgG9GFURSYBGAAwUA+hADcIsQHtgAKzg85wJQzEVlo1vwAUkmRACUFEBRgALAJZRTVoxWH6DY+RQC8FIoeAL4eHiZ8pmqa2sA2do4ubh5ePr7AARS6oYxhDEA==

I use this pattern to implement a form of discriminated unions, and so this pattern is not rare in my code base. I imagine I'm not the only one.

**Expected Behavior**:

warning CS8618: Non-nullable field '_b' is uninitialized. Consider declaring the field as nullable.
warning CS8618: Non-nullable field '_a' is uninitialized. Consider declaring the field as nullable.

**Actual Behavior**:

No warning

**Comment by YairHalberstadt** [comment] 2019-08-28 18:28
> But it feels like we should make the warnings consistent with an equivalent constructor that has this = default at the beginning instead of a 'this()' clause. Such a constructor also produces no uninitialized field warnings.

Perhaps then this should wait till a more general solution for structs comes along, perhaps something like https://github.com/dotnet/csharplang/issues/2328.

**Comment by jaredpar** [comment] 2019-09-06 18:15
@MadsTorgersen to my understanding this is behaving as intended at the moment. Do you agree?

**Comment by jaredpar** [comment] 2019-09-09 20:46
Closing as this is "by design". If we want to change this behavior we should start a discussion in csharplang about it.

**Closed by jaredpar** 2019-09-09 20:46 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
