### ISSUE TITLE
Auto add async to method signature feature improvement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63081] opened 2022-07-29 21:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-add-async-to-method-signature-featu/10088036)._

---
IDE:Visual Studio 2022 17.3.0 Preview 2.0

Case 1:
Current:
`
public void RunAsync() {
    RunSomethingAsync() // -->add .await
}
`
Result:
`
public async void RunAsync() {
    await RunSomethingAsync();
}
`
Expect:
`
public async Task RunAsync() /* -->change return type 'void' to 'Task'  */ { 
    await RunSomethingAsync();
}
`

Case 2:
Current:
`
public string GetAsync() {
    return GetStringAsync() // -->add .await
}
`
Result:
`
public async string GetAsync() {
    return await GetStringAsync();
}
`
Expect:
`
public async Task GetAsync() /* -->change return type 'string' to 'Task'  */ {
    return await GetStringAsync();
}
`

---
#### Feedback Bot on 7/5/2022, 11:00 PM: 

(private comment, text removed)

**Comment by rdragon** [comment] 2023-08-02 18:39
This would be a nice improvement. It would also solve the issue explained [here](https://stackoverflow.com/questions/71551799/what-feature-automatically-adds-async-to-a-method-signature-in-vs2022) about Visual Studio automatically creating `async void` methods.

By the way, for case 2 the expected result is of course a method returning `Task<string>` instead of `Task`, just like it's written in the [original post](https://developercommunity.visualstudio.com/t/Auto-add-async-to-method-signature-featu/10088036).

**Comment by sharwell** [comment] 2023-11-23 23:20
Duplicate of #55975

**Closed by sharwell** 2023-11-23 23:20 UTC
Labels: Area-IDE, Need Design Review
