### ISSUE TITLE
Create a perf test for compiling latest Roslyn solution with analyzers

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#621] opened 2015-02-18 01:14 UTC
We should have a perf test that compiles the latest roslyn.sln which will include the latest roslyn analyzers. We can’t use that as a gate for anything because as more code and more analyzers are added the trend will increase but if there are sudden spikes, because of say some AnalyzerDriver changes we can spot them. Currently we don’t have any way of doing that. I believe we have a test that builds a frozen copy of roslyn with a frozen copy of analyzers but that's a very old set of analyzers which are rather simplistic.

**Comment by amcasey** [comment] 2015-03-18 01:09
It might be interesting to use "no analyzers" as a baseline.  On my box it's 4-10 times as fast.

**Comment by KevinH-MS** [comment] 2015-10-12 21:10
Moving -> Milestone 1.2 (we don't *need* this for 1.1)

**Comment by mavasani** [comment] 2015-11-19 22:50
Assigning to @basoundr, our perf representative.

Balaji, I think we may want to add this perf test pretty soon. We plan to do bunch of analyzer framework improvements for 1.2 milestone, including new performance enhancements/features. A performance test for build with analyzers will surely be very helpful in guarding against regressions + also understanding any perf benefits from the changes.

**Comment by sharwell** [comment] 2015-11-29 04:56
[comment so I'm notified of updates]

**Comment by KevinH-MS** [comment] 2016-02-22 00:40
Moving this to 1.3, as I don't believe we're going to get to this in the 1.2 timeframe.

**Comment by mavasani** [comment] 2016-05-16 23:40
We already have a test for this in place `CSharpPerfBuildWithThirdPartyAnalyzersTemplate` - it is currently disabled because our new perf infrastructure (CPC) doesn't seem to support performance tao actions which are not event based. See [here](https://github.com/dotnet/roslyn-internal/blob/master/Closed/Test/PerformanceTests/Perf/tests/CSharp/csharp_diagnostic_tests.csx#L57)

**Comment by mavasani** [comment] 2016-05-23 23:58
Moving to @basoundr to enable the perf test with CPC infrastructure.

**Closed** 2016-06-24 17:39 UTC
Labels: 2 - Ready, Area-Analyzers, Feature Request, Tenet-Performance, Test
