### ISSUE TITLE
Roslyn fails to detect nullability problems in C# 10 interpolated string handlers

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#57412] opened 2021-10-27 11:11 UTC
**Version Used**: 
```
Branch main (26 Oct 2021)
Latest commit a4ec465 by Gen Lu:
Merge pull request #57338 from genlu/FixWarning

Fix 'AssemblyVersion overridden by auto-generated version' warning in build
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;

#nullable enable

string? s = null;
M(s, $"");

void M<T>(T t1, [InterpolatedStringHandlerArgument("t1")] CustomHandler c) {}

public partial struct CustomHandler
{
  public CustomHandler(int literalLength, int formattedCount, string t , out bool success) : this()
  {
    t.ToString();
      
    _builder = new();
    success = true;
  }
}

[System.Runtime.CompilerServices.InterpolatedStringHandler]
public partial struct CustomHandler
{
  private readonly StringBuilder _builder;
  public CustomHandler(int literalLength, int formattedCount, out bool success)
  {
    success = true;
    _builder = new();
  }
  public bool AppendLiteral(string literal)
  {
    _builder.AppendLine("literal:" + literal);
    return true;
  }
  public bool AppendFormatted(object o, int alignment = 0, string? format = null)
  {
    _builder.AppendLine("value:" + o?.ToString());
    _builder.AppendLine("alignment:" + alignment.ToString());
    _builder.AppendLine("format:" + format);
    return true;
  }
  public override string ToString() => _builder.ToString();
}

namespace System.Runtime.CompilerServices
{
  [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
  public sealed class InterpolatedStringHandlerAttribute : Attribute
  {
    public InterpolatedStringHandlerAttribute()
    {
    }
  }
}

public class CultureInfoNormalizer
{
  public static void Normalize()
  {
    CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
  }
}

namespace System.Runtime.CompilerServices
{
  [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
  public sealed class InterpolatedStringHandlerArgumentAttribute : Attribute
  {
    public InterpolatedStringHandlerArgumentAttribute(string argument) => Arguments = new string[] { argument };
    public InterpolatedStringHandlerArgumentAttribute(params string[] arguments) => Arguments = arguments;
    public string[] Arguments { get; }
  }
}

namespace System.Diagnostics.CodeAnalysis
{
  [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue)]
  public sealed class MaybeNullAttribute : Attribute
  {
  }
}

```

**Expected Behavior**:
Warning for a nulalble argument to the `CustomHandler`'s non-nullable parameter `string t`

**Actual Behavior**:
No warnings at all in the program above. It crashes with a `NullReferenceException` at runtime

**Comment by 333fred** [comment] 2021-11-04 17:16
Duplicate of https://github.com/dotnet/roslyn/issues/54583.

**Closed by 333fred** 2021-11-04 17:16 UTC
Labels: Bug, Area-Compilers, New Language Feature - Nullable Reference Types
