### ISSUE TITLE
Keep all using imports within namespace

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33296] opened 2019-02-11 18:18 UTC
Customer request:

> My team code style is to keep all using imports within the scope of the namespace. VS 2017 auto import throws them wherever it wants. Sometimes inside the namespace, sometimes outside this scope (I think based on precedence of where they already exist?) 

> I’d like to select a checkbox (like I can in ReSharper) import in deepest nested scope. Matching my team’s code style should be trivial with the help of an IDE. 

Our only editorconfig settings for imports are [organizing and sorting usings](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#usings). This would be a new editorconfig rule.

**Comment by sharwell** [comment] 2019-02-11 18:28
Duplicate of #27179

**Comment by jinujoseph** [comment] 2019-02-11 18:29
@kendrahavens , @JoeRobich 
this is dupe of https://github.com/dotnet/roslyn/issues/27179

**Closed by sharwell** 2019-02-11 18:28 UTC
