### ISSUE TITLE
`GetService<VisualStudioWorkspace>()` throws `InvalidCastException`

### ISSUE THREAD

**Issue by ionoy** [dotnet/roslyn#25550] opened 2018-03-17 06:43 UTC
**Version Used**: 
Visual Studio 15.4.4
`Microsoft.VisualStudio.LanguageServices` package (any other than 2.4.0)

**Steps to Reproduce**:
1. Create a Visual Studio extension project (Package)
2. `Install-Package Microsoft.VisualStudio.LanguageServices`
3. 
```
var componentModel = (IComponentModel)Package.GetGlobalService(typeof(SComponentModel));
var workspace = componentModel.GetService<VisualStudioWorkspace>();
```
**Expected Behavior**:
This should give me an instance of `VisualStudioWorkspace`

**Actual Behavior**:
`Unable to cast object of type 'Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace' to type 'Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace'` is thrown

I realize that this cast exception happens because built-in `LanguageServices` version differs from the one installed by NuGet. But how can I target users with different Visual Studio versions if any version mismatch causes the exception?

**Comment by ryzngard** [comment] 2019-06-17 23:41
There's a good explanation of how this works on [StackOverflow](https://stackoverflow.com/q/25606632) which should get you on the right track on how to handle multiple Visual Studio versions. I'm closing this issue, but feel free to re-open if you have more questions.

**Closed by ryzngard** 2019-06-17 23:41 UTC
Labels: Area-IDE, Concept-API, Question

**Comment by ionoy** [comment] 2019-06-18 11:49
I'm not sure the provided answer works with Roslyn language services though. Say I want to analyze C# 8.0 syntax which is only supported by VS2019 and newer Roslyn NuGet packages. But I still want to have a fallback for users that are on VS2017 using C# 7.2.

In this case, I'm not able to target the lowest version of VS (2017) because I won't have access to the C# 8.0 Roslyn API.

Maybe I'm missing something, though. Please advise.

Thanks!

**Comment by sharwell** [comment] 2019-06-18 11:57
> Say I want to analyze C# 8.0 syntax which is only supported by VS2019 and newer Roslyn NuGet packages. But I still want to have a fallback for users that are on VS2017 using C# 7.2.

StyleCop Analyzers accomplishes this through an elaborate and manually-maintained light-up layer.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/StyleCop.Analyzers/StyleCop.Analyzers/Lightup

**Comment by ionoy** [comment] 2019-06-18 12:29
Do I understand correctly, that this light-up layer is a wrapper layer over the Roslyn API that depends on some older Roslyn version? Honestly, it seems like a hell of a thing to initially write. Your second suggestion seems like an easier option. 

Still, I would like to know if there is an official stance on this issue. If there isn't one, then I'll go a multiple assembly road, I guess.

**Comment by sharwell** [comment] 2019-06-18 12:31
@ionoy The official stance on the issue is new versions of Visual Studio continue to support older versions of the API (backward compatible), but old versions of Visual Studio have and will not officially support newer versions of the API (*not* forward compatible).

**Comment by ionoy** [comment] 2019-06-18 12:33
OK, got it. Thanks for the help!
