### ISSUE TITLE
'Make local function static' removes empty line above local function

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#35854] opened 2019-05-21 21:57 UTC
**Version Used**: VS 16.1 and C#8 preview

**Steps to Reproduce**:

1. `Ctrl+.` on `LocalFunc` and hit `Make local function static`

```C#
using System;
namespace ConsoleApp9 {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello World!");

            int LocalFunc() => 123;
        }
    }
}
```

**Expected Behavior**:

The empty line above the local function is preserved

```C#
using System;
namespace ConsoleApp9 {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello World!");

            static int LocalFunc() => 123;
        }
    }
}
```

**Actual Behavior**:

The empty line above the local function is removed

```C#
using System;
namespace ConsoleApp9 {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello World!");
            static int LocalFunc() => 123;
        }
    }
}
```

**Comment by jinujoseph** [comment] 2019-05-22 18:00
Duplicate of #35489

**Closed by jinujoseph** 2019-05-22 18:00 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, help wanted
