### ISSUE TITLE
Nullable flow analysis confused by bitwise or

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42900] opened 2020-03-30 13:07 UTC
**Version Used**: 
3.6.0-2.20167.1+926207070b0c62d6a76aec4627ec26dee17870bb

**Steps to Reproduce**:
```C#
#nullable enable
using System;
public class C {
    public int M(object obj1, object obj2) {
        if ((obj1 is null) | (obj2 is null))
        {
            throw new ArgumentNullException();
        }
        
        return obj1.GetHashCode() + obj2.GetHashCode();
    }
}
``` 

**Expected Behavior**:
No warnings.

**Actual Behavior**:
Issues `warning CS8602: Dereference of a possibly null reference.` on both `obj1.GetHashCode()` and `obj2.GetHashCode()`.

**Comment by RikkiGibson** [comment] 2020-03-31 00:19
Very similar to #37344. At the time we decided this behavior was by design.

**Comment by jcouv** [comment] 2020-03-31 16:36
Closing as duplicate. Maybe we could address this case...

**Closed by jcouv** 2020-03-31 16:36 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
