### ISSUE TITLE
Implicit cast operator not compiling outside assembly when using in modifier

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#23945] opened 2017-12-27 11:53 UTC
https://stackoverflow.com/questions/47983027/implicit-cast-operator-not-compiling-outside-original-assembly

**Version Used**: VS 2017 15.5.2

**Steps to Reproduce**:

See original question on StackOverflow here: https://stackoverflow.com/questions/47983027/implicit-cast-operator-not-compiling-outside-original-assembly

1. Create a .NET Standard library and a new struct with an implicit casting operator that takes its argument with the new C# 7.2 `in` modifier.
2. Create another library/application that references the library above, and try to use that implicit casting operator
3. Notice it won't compile and you'll see the following error:
> error CS0029: Couldn't implicitly convert the type 'MyTestType' into 'MyCastingType'

**Expected Behavior**:

The implicit cast should work the same regardless of the parent assembly. If it's present for the type and it works inside the original assembly, it should behave the same in other assemblies. Note that apparently removing the `in` modifier in the cast operator parameter solves the problem, so this might be a bug with the new C# 7.2 feature.

**Actual Behavior**:

The code doesn't compile from assemblies other than the one where the type is defined, and VS shows that CS0029 error above.

**Comment by ufcpp** [comment] 2017-12-27 15:38
https://github.com/dotnet/roslyn/issues/23689

**Comment by Sergio0694** [comment] 2017-12-27 16:12
@ufcpp Whoops, missed that issue before, glad to hear it's already been investigated and fixed in the upcoming VS 15.6 version! 😄

**Comment by jcouv** [comment] 2017-12-27 23:14
@Sergio0694 You can install a preview of 15.6 and confirm the issue is resolved.
I'll go ahead and resolved as duplicate of #23689 (thanks @ufcpp). 
Feel free to re-open if still causing problems.

**Closed by jcouv** 2017-12-27 23:14 UTC
