### ISSUE TITLE
Completion not working with missing leading underscore (in some cases)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18131] opened 2017-03-23 22:42 UTC
**Version Used**: VS2017

I can't come up with a standalone repro, but if you open Roslyn.sln and go to Editor_OutOfProc and pick any method and type `inp`, the `_inProc` field is not in the list.

**Comment by sharwell** [comment] 2017-03-24 02:55
I can reproduce this with the following:

```csharp
class Program2
{
    static int _myProgram;

    static void Main2(string[] args)
    {
        myp|
    }
}
```

**Comment by sharwell** [comment] 2017-03-24 02:56
Assigning @CyrusNajmabadi since this is likely related to the ongoing work in #18138.

**Comment by CyrusNajmabadi** [comment] 2017-03-26 23:26
I haven't looked closely enough.  But i'm thinking that _ should not be treated as a word character and should be a word separate from the perspective of the pattern matcher.

**Comment by CyrusNajmabadi** [comment] 2017-03-28 17:34
Tagging @grabalon as well.

**Comment by CyrusNajmabadi** [comment] 2017-04-10 13:56
Fixed with https://github.com/dotnet/roslyn/pull/18540

**Closed by CyrusNajmabadi** 2017-04-10 13:56 UTC
Labels: Area-IDE, Bug
