### ISSUE TITLE
Using Formatter.Fomat from CoreCLR

### ISSUE THREAD

**Issue by ayende** [dotnet/roslyn#18167] opened 2017-03-25 07:18 UTC
**Version Used**: 

VS 2017

**Steps to Reproduce**:

1.  I want to format some code on CoreCLR
2. Trying to add NuGet reference to Microsoft.CodeAnalysis.CSharp.Workspaces fails

**Expected Behavior**:

Should be able to do add the reference and then use `Formatter.Format`

**Actual Behavior**:

Gets an error.

```
  GET https://api.nuget.org/v3/registration1-gz/microsoft.codeanalysis.csharp.workspaces/index.json
  OK https://api.nuget.org/v3/registration1-gz/microsoft.codeanalysis.csharp.workspaces/index.json 167ms
Restoring packages for C:\Work\ravendb-4.0\src\Raven.Server\Raven.Server.csproj...
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / ubuntu.14.04-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (ubuntu.14.04-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / ubuntu.16.04-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (ubuntu.16.04-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win10-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win10-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win10-x86. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win10-x86).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win7-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x86. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win7-x86).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win8-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win8-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win8-x86. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win8-x86).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win81-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win81-x64).
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win81-x86. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1 (win81-x86).
Package restore failed. Rolling back package changes for 'Raven.Server'.
Time Elapsed: 00:00:04.5577429
========== Finished ==========
```

**Comment by sharwell** [comment] 2017-03-25 13:39
:memo: This appears to be a duplicate of #16040.

**Comment by Pilchie** [comment] 2017-03-25 19:03
Yes, it does seem to be a duplicate - there are workarounds to allow NuGet to use the package anyway.

**Closed by Pilchie** 2017-03-25 19:03 UTC
Labels: Area-IDE, Resolution-Duplicate

**Comment by ayende** [comment] 2017-03-25 20:50
@Pilchie what are those workarounds?

**Comment by Pilchie** [comment] 2017-03-27 00:06
From the first comment on #16040: 

>Having a dependency on Microsoft.Composition requires the project to have

>`<PackageTargetFallback>portable-net45+win8</PackageTargetFallback>`
(imports in the project.json world)
