### ISSUE TITLE
Runtime Exception : Unable to cast object of type 'Microsoft.VisualStudio.ComponentModelHost.ComponentModel' to type 'Microsoft.VisualStudio.ComponentModelHost.IComponentModel'.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#36583] opened 2019-06-19 14:45 UTC
**Version Used:**
3.1.0

 **Visual Studios Version Used  :** 
Visual Studios 2017 Community Version 15.9.13

**Steps to Reproduce:**

Create a .VSIX project using Visual Studios 2017 Community Version 15.9.13

Add Nuget References to following:
```
Microsoft.CodeAnalysis (3.1.0.0)
Microsoft.VisualStudio.LanguageServices(3.1.0.0)
Microsoft.VisualStudio.ComponentModelHost (16.0.0.0)
```

Following code is used for getting the current solution instance:
```
var componentModel = (Microsoft.VisualStudio.ComponentModelHost.IComponentModel)Microsoft.VisualStudio.Shell.Package.GetGlobalService(typeof(Microsoft.VisualStudio.ComponentModelHost.SComponentModel));
VisualStudioWorkspace workspace = componentModel.GetService<VisualStudioWorkspace>();
```

When we run the .VSIX package in debug mode and try to run the above code an exception is thrown : **System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.VisualStudio.ComponentModelHost.ComponentModel' to type 'Microsoft.VisualStudio.ComponentModelHost.IComponentModel'.**

**Important points:**

**I am trying to build a .vsix for VS 2017**.
I am having Visual Studios 2015 Update 3 Community version, Visual Studios 2017 Community Version 15.9.13 and Visual Studios 2019 (2) Version 16.1.1 installed on my machine.

The Microsoft.VisualStudio.LanguageServices dll and Microsoft.VisualStudio.ComponentModelHost.dll  has Copy Local option set to True.

The GAC entries that i can see are as below:

  ```
Microsoft.VisualStudio.ComponentModelHost, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
  Microsoft.VisualStudio.ComponentModelHost, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
  Microsoft.VisualStudio.ComponentModelHost.Implementation, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
  Microsoft.VisualStudio.ComponentModelHost.Implementation, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
```

**Expected Behavior:**
The current Solution should be loaded in the VisualStudioWorkspace reference.

**Actual Behavior:**
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.VisualStudio.ComponentModelHost.ComponentModel' to type 'Microsoft.VisualStudio.ComponentModelHost.IComponentModel'.

**Comment by sharwell** [comment] 2019-06-19 15:08
Microsoft.CodeAnalysis 3.x cannot be used in Visual Studio 2017.

**Comment by sharwell** [comment] 2019-06-19 15:09
Duplicate of #25550

**Closed by sharwell** 2019-06-19 15:09 UTC

**Comment by abhijitparkhi1983** [comment] 2019-06-19 15:34
Thanks @sharwell for a quick reply. 
Can u pls let me know a link which talks about the Vs version and compatible codeanalysis version ? 
What is the final version supported by Vs2017 ?

**Comment by sharwell** [comment] 2019-06-19 16:18
The code analysis minor versions should correspond to Visual Studio minor versions. For example, 2.3.x should work with 15.3.x, and 2.9.x should work with Visual Studio 15.9.x.

**Comment by abhijitparkhi1983** [comment] 2019-06-19 17:05
Thanks @sharwell 

The way there is minimum version of Microsoft.CodeAnalysis for a given VS, is there any such limitation on the .NET Framework version that can be used ?
Like say for example, I have Visual Studios 2017 Version 15.9.13. My project is based on .NET Framework 4.7.2.
In this case, will the Code Analysis version 2.9.x will work with .NET Framework 4.7.2 or is there any limitation ?
