### ISSUE TITLE
IDE0059 (Remove redundant assignment) incorrectly copies leading trivia

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48070] opened 2020-09-25 22:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1195636/quick-action-offers-bad-code-recommendation.html)._

---
I do not know how to reproduce as this is the first time I have seen it BUT as can be seen in the attached screenshot it SHOULD be offering to remove the **_= null_** initialization but instead offers to add an **_#endregion_** instead which produces a compile error.

---
#### Feedback Bot on 9/23/2020, 08:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/25/2020, 02:42 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-09-25 22:59
Sample code:

```csharp
void Method()
{
    #region
    int value = 3;
    #endregion

    object x = null;
    object y = new object();

    x = new object();
    Console.WriteLine(x);
}
```

Apply IDE0059 code fix to the declaration of `object x`.

### Expected result

```csharp
void Method()
{
    #region
    int value = 3;
    #endregion

    object y = new object();

    object x = new object();
    Console.WriteLine(x);
}
```

### Actual result

```csharp
void Method()
{
    #region
    int value = 3;

    #endregion
    object y = new object();

    #endregion

    object x = new object();
    Console.WriteLine(x);
}
```

**Comment by CyrusNajmabadi** [comment] 2020-09-25 23:23
Image of issue:

![image](https://user-images.githubusercontent.com/4564579/94323621-6035f380-ff4b-11ea-8ce4-d5e2384b1180.png)

**Comment by CyrusNajmabadi** [comment] 2020-09-25 23:24
Up for grabs if anyone is interested.  Usually this is a mistake taking trivia from another construct and copying it around.

**Comment by MartynJones87** [comment] 2020-10-01 07:44
I'd like to take a stab at fixing this issue please @CyrusNajmabadi

**Comment by MartynJones87** [comment] 2020-10-02 17:06
Hello @CyrusNajmabadi Tackling this issue is so far proving to be a steep learning curve for me for my first time in the roslyn codebase!

I think I've narrowed down where the issue is happening to this local method: https://github.com/dotnet/roslyn/blob/0bd72a7c005b59ddb5aba1c11d34c2a9b9315e9c/src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs#L660-L683

This is the `InsertLocalDeclarationStatement` method within the `FixAllValueAssignedIsUnusedDiagnosticsAsync` method.

I think the issue is with this block:

```
else if (insertionNode is TStatementSyntax)
                {
                    // If the insertion node is being removed, keep the leading trivia with the new declaration.
                    if (nodesToRemove.Contains(insertionNode) && !processedNodes.Contains(insertionNode))
                    {
                        // declarationStatement = declarationStatement.WithLeadingTrivia(insertionNode.GetLeadingTrivia());
                        // Mark the node as processed so that the trivia only gets added once.
                        processedNodes.Add(insertionNode);
                    }
                    editor.InsertBefore(insertionNode, declarationStatement);
                }
```

which appears to be copying the leading trivia onto the newly insterted statement (and so copying the #endregion), but, I tried removing the leading trivia but that broke several other tests and it caused comments in leading trivia to be dropped.

@CyrusNajmabadi Could you please point me in the direction of some docs that will assist me or some advice please? I feel like I'm not too far away (although I might be miles off!) Thanks very much!

**Comment by CyrusNajmabadi** [comment] 2020-10-02 17:10
i'm traveling today so can't really help.  but you're on the right track.  i think the idea here is that you'll need to filter that set of GetLeadingTrivia to only include the trivia after any directives (if there are any).  :)

**Comment by MartynJones87** [comment] 2020-10-02 17:12
Magic! Thank you very much, I'll work on that. Safe travels! Thank you again @CyrusNajmabadi :-)

**Comment by CyrusNajmabadi** [comment] 2020-10-02 18:32
Note: this is in code *shared* between C# and VB.  If you find yourself needing language-specific checks, the two most common ways to do it are:

1. use ISyntaxFactsService for asking *simple* syntactic questions that have clearly defined uniform meaning across both languages (i.e. "is this a single-line-comment?").  Do not put complex logic here.  i.e. this is not a grab bag for a specific feature to place it's custom feature-specific logic into.
2. use abstract methods and have the subclasses provide the language specific impls of that.  as much as possible keep common logic in this base class.

LMK if you need more help.  there is good help also available at gitter.im/roslyn and discord.gg/csharp (#roslyn).  Def leave questions there and people will answer usually within a day (or much faster if they're actively watching).  Ping me and i'll def look.

**Comment by MartynJones87** [comment] 2020-10-05 13:12
Hello @CyrusNajmabadi Thank you for your feedback on the PR.
I am trying to address the points you raised, but I can no longer build the solution, getting the following error:

![image](https://user-images.githubusercontent.com/1846942/95083706-c3c2dc80-0714-11eb-8211-e98cfbf2161f.png)

Is there a standard set of steps that I could try to get it building again? Thanks very much!

**Comment by CyrusNajmabadi** [comment] 2020-10-05 13:59
Never seen that before. Try killing that process and rebuilding

**Comment by MartynJones87** [comment] 2020-10-07 16:37
I'm really struggling with this. I've tried everything I can think of; I've deleted and re-cloned to a different folder on disk, killing any lingering VBCSCompiler and MSBuild processes, pulling from master in case a fix has been made, different terminals. Just keep getting the same error:

```
Build FAILED.

CSC : error CS2012: Cannot open 'C:\GitHubRepos\roslyn\artifacts\obj\VBCSCompiler\Debug\net472\ref\VBCSCompiler.exe' fo
r writing -- 'Access to the path 'C:\GitHubRepos\roslyn\artifacts\obj\VBCSCompiler\Debug\net472\ref\VBCSCompiler.exe' i
s denied.' [C:\GitHubRepos\roslyn\src\Compilers\Server\VBCSCompiler\VBCSCompiler.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:13.67
Build failed.
```

Does anybody else have anything else I can try? Thanks very much!

**Comment by CyrusNajmabadi** [comment] 2020-10-07 16:52
Can you just use `handle.exe` to see what is locking this?  https://docs.microsoft.com/en-us/sysinternals/downloads/handle
?

**Comment by MartynJones87** [comment] 2020-10-07 17:14
It doesn't appear to be anything locking the file, but the file doesn't exist within that folder:
![image](https://user-images.githubusercontent.com/1846942/95364534-da119980-08c8-11eb-8c1d-3d4a4ea97469.png)

**Comment by MartynJones87** [comment] 2020-10-07 17:20
There is a little more information in the build errors within VS:
![image](https://user-images.githubusercontent.com/1846942/95365207-c0248680-08c9-11eb-82f7-0ef3007b0b29.png)

**Comment by CyrusNajmabadi** [comment] 2020-10-07 17:33
Have you rebooted?  What does 'handle.exe' say is locking the file?  Can you close VS and trying building outside of it?

**Comment by MartynJones87** [comment] 2020-10-07 17:45
I have rebooted several times. I've also built from the command line and get the same error.

I've also cleared the Nuget cache and restored again in case something in there was corrupt. 

Handle is not reporting anything locking the VBCSCompiler.exe file.

**Comment by CyrusNajmabadi** [comment] 2020-10-07 19:45
Antivirus? Some random user mode driver?  I'm honestly not sure what could be going on.  Windows appears to be saying the file is locked, but the tools that tell you what is locking it appear to say nothing is locking it.  Potentially busted windows install?

Have you tried a different git directory to work out of?

**Comment by MartynJones87** [comment] 2020-10-08 08:29
Bingo! Antivirus it was. I spent so long trying to fix that it I was looking in the wrong place! Thank you very much for your patience, I'll get back to making the fix now.

**Closed** 2021-01-05 07:21 UTC
Labels: Area-Analyzers, Concept-Continuous Improvement, IDE-CodeStyle, help wanted
