### ISSUE TITLE
IntelliSense Does not disable for space bar

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37565] opened 2019-07-30 01:42 UTC
When Using Intellisense, the space bar executes an unwanted outcome while typing text.  There must be an option to disable the spacebar from autocompleting terms.

_This issue has been moved from https://developercommunity.visualstudio.com/idea/565770/intellisense-does-not-disable-for-space-bar.html
VSTS ticketId: 890425_
_These are the original issue comments:_

Sara Shi [MSFT] on 5/13/2019, 00:00 AM (77 days ago): We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature. It will allow other developers to easily find it and engage on it.
Jane Wu [MSFT] on 5/13/2019, 02:14 AM (77 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-07-31 00:00
Duplicate of #37088

**Closed by jinujoseph** 2019-07-31 00:00 UTC
Labels: Area-IDE
