### ISSUE TITLE
IDE0007 false positive

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#23705] opened 2017-12-11 00:11 UTC
**Version Used**: VS 15.5 Community

**Steps to Reproduce**:

```csharp
class ClassName
{
    void Bar<T>(out T value)
    {
        Bar(out T value2); // IDE0007

        value = default(T);
    }
}
```

**Comment by sharwell** [comment] 2017-12-11 13:20
Duplicate of #23250

**Closed by sharwell** 2017-12-11 13:20 UTC
