### ISSUE TITLE
[Test Failure] Test Failures (+1 more) in prtest/win/dbg/unit64 on PR #9605

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9609] opened 2016-03-09 17:54 UTC
PR: [#9605](https://github.com/dotnet/roslyn/pull/9605) *Merge stabilization into future-stabilization* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4995/

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Issue 2: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

I am not sure which tests are failed.

**Comment by davkean** [comment] 2016-03-09 18:03
Log: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4995/artifact/Binaries/Debug/xUnitResults/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.dll.out.log

Dupe of https://github.com/dotnet/roslyn/issues/9490

**Closed by davkean** 2016-03-09 18:03 UTC
Labels: Bug
