### ISSUE TITLE
System.AccessViolationException when calling FindImplementationForInterfaceMember

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [dotnet/roslyn#47187] opened 2020-08-27 13:03 UTC
**Versions Used**: 
.Net: 5.0.100-preview.8.20417.9

**Steps to Reproduce**:

After we upgraded our build pipeline to use **.Net 5.0.100-preview.8.20417.9** instead of **5.0.100-preview.7.20366.6** the following exception (thrown by one of our analyzers) is intermittently failing the build:

```
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol.get_ExplicitInterfaceImplementations() [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.GetExplicitInterfaceImplementations(Microsoft.CodeAnalysis.CSharp.Symbol) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.MakeExplicitInterfaceImplementationMap() [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.GetExplicitImplementationForInterfaceMember(Microsoft.CodeAnalysis.CSharp.Symbol) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationForInterfaceMember(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean ByRef) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationAndDiagnosticsForInterfaceMember(Microsoft.CodeAnalysis.CSharp.Symbol, Boolean, Boolean ByRef) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMemberInNonInterfaceWithDiagnostics(Microsoft.CodeAnalysis.CSharp.Symbol, Boolean) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMember(Microsoft.CodeAnalysis.CSharp.Symbol) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.FindImplementationForInterfaceMember(Microsoft.CodeAnalysis.ISymbol) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at SonarAnalyzer.Helpers.SymbolHelper+<>c__DisplayClass5_0`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetInterfaceMember>b__1(System.__Canon) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Linq.Enumerable.TryGetFirst[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>, Boolean ByRef) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at SonarAnalyzer.Helpers.SymbolHelper.GetInterfaceMember[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon) [D:\a\1\s\sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\SonarAnalyzer.CSharp.csproj]
```

Source code: https://github.com/SonarSource/sonar-dotnet/blob/734df7968037387faade9353c7aedd1a77c010a0/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs#L92

**Comment by RikkiGibson** [comment] 2020-09-04 00:22
This is likely related to #46575. You may be able to work around it by adding a reference to a recent nightly Microsoft.Net.Compilers.Toolset (see [documentation](https://github.com/dotnet/roslyn/blob/master/docs/wiki/NuGet-packages.md)).

**Comment by costin-zaharia-sonarsource** [comment] 2020-09-04 07:18
> This is likely related to #46575. You may be able to work around it by adding a reference to a recent nightly Microsoft.Net.Compilers.Toolset (see [documentation](https://github.com/dotnet/roslyn/blob/master/docs/wiki/NuGet-packages.md?rgh-link-date=2020-09-04T00%3A22%3A27Z)).

Thanks @RikkiGibson. We will probably wait until RC1 is published and try to use that.

**Comment by RikkiGibson** [comment] 2020-09-14 00:52
Closing as a duplicate of #46575. Thank you for reporting.

**Closed by RikkiGibson** 2020-09-14 00:52 UTC
Labels: Area-Compilers, Bug, Tenet-Reliability
