### ISSUE TITLE
ObjectReader possibly creates too many tasks

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#33136] opened 2019-02-05 11:59 UTC
**Version Used**: 
2.10.0-beta2-63410-10 (but looks like it's the same in 3.0.0-beta2-19055-09)

**Steps to Reproduce**:

1. Type in VSMac
2. Observe a lot of threads being started and finished

**Expected Behavior**:
ObjectReader should not be spinning tasks up recursively here: https://source.roslyn.io/#Microsoft.CodeAnalysis/Serialization/ObjectReader.cs,144

The thread creation is for these threadpool items.

**Actual Behavior**:
There's 2 scenarios which come to mind which can end up creating a lot of threads:
a) recursionDepth 50 -> 49 -> 50 -> 49 -> 50, etc.
b) recursionDepth 50 -> ... -> 100 -> ... -> 150 (creates nested task, this should definitely be eliminated)

**Comment by sharwell** [comment] 2019-02-05 17:31
Duplicate of #23331

**Closed by sharwell** 2019-02-05 17:31 UTC
