### ISSUE TITLE
Nullability state reported on LHS of assignment appears to be the state from before the assignment rather than after.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#41488] opened 2020-02-07 18:36 UTC
**Version Used**:  16.5P3 29802.114.master

**Steps to Reproduce**:

1. Paste C#

```C#
using System;

#nullable enable

class C
{
    void M()
    {
        string? local = null;
        if (local != null)
        {
            Console.WriteLine(local.Length);
            local = null;    // Expected: local to be maybe-null. Actual: QI says "'local' is not null here"
            local = "test";  // Expected: local to be not-null.   Actual: QI says "'local' may be null here"
        }
    }
}
```

2. Use QuickInfo on the two commented assignments of `local`

Here's a screenshot of this where green identifiers mean QI would show "is not null here" and orange means "may be null here"

![image](https://user-images.githubusercontent.com/235241/74055795-92cbb580-4995-11ea-98e9-a7d966083bd0.png)

**Comment by dpoeschl** [comment] 2020-02-07 18:38
Discussed this with @333fred in the context of compound assignments, but noticed it happening here as well with simple assignments.

**Comment by jasonmalinowski** [comment] 2020-04-06 19:06
@dpoeschl @333fred I see the compiler approach for fixing this issue was closed out of an API design concern. What's the next step for this issue? I can think of a few things off the top of my head, I'm sure there's more:

1. Have the IDE detect if you're doing quick info over an assignment, and change the wording in the Quick Info to clarify the information being shown is before the assignment.
2. Have the IDE detect if you're doing quick info over an assignment, and instead show the information from binding the right hand side of the assignment.

**Comment by 333fred** [comment] 2020-04-06 19:17
Either of those options will work. I'd prefer the latter, personally, but I'll leave that up to you to decide.

**Comment by sharwell** [comment] 2020-04-08 18:52
Duplicate of #42897

**Closed by sharwell** 2020-04-08 18:52 UTC
Labels: Area-IDE, Concept-API
