### ISSUE TITLE
Hit nullability assert compiling roslyn with roslyn.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#51461] opened 2021-02-25 00:47 UTC
Hit this assert:

```
Debug.Assert(_analyzedNullabilityMap.ContainsKey(expression), $"Did not find {expression} `{expression.Syntax}` in the map.");
```

At:

```
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VerifyExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression expression, bool overrideSkippedExpression) Line 50	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 57	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(ref int recursionDepth, Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 212	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 72	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement node) Line 9113	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 3232	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 74	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList<Microsoft.CodeAnalysis.CSharp.BoundStatement>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> list) Line 22	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock node) Line 9057	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 2867	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 74	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitLambda(Microsoft.CodeAnalysis.CSharp.BoundLambda node) Line 9571	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundLambda.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 7002	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 58	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(ref int recursionDepth, Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 212	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 72	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitBadExpression(Microsoft.CodeAnalysis.CSharp.BoundBadExpression node) Line 91	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBadExpression.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 684	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 58	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(ref int recursionDepth, Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 212	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 72	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitLocalDeclaration(Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration node) Line 9073	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 2968	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 74	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList<Microsoft.CodeAnalysis.CSharp.BoundStatement>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> list) Line 22	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock node) Line 9057	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 2867	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 74	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody node) Line 9678	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 7842	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 74	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Verify(System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.CSharp.BoundExpression, (Microsoft.CodeAnalysis.NullabilityInfo Info, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol Type)> analyzedNullabilityMap, Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager snapshotManagerOpt, Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 39	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation, Microsoft.CodeAnalysis.CSharp.Symbol symbol, Microsoft.CodeAnalysis.CSharp.BoundNode node, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.NullableWalker.VariableState initialState, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, bool createSnapshots, bool requiresAnalysis) Line 1170	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation, Microsoft.CodeAnalysis.CSharp.Symbol symbol, Microsoft.CodeAnalysis.CSharp.BoundNode node, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.NullableWalker.VariableState initialState, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, bool createSnapshots, out Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager snapshotManager, ref System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.Symbol> remappedSymbols) Line 1125	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(Microsoft.CodeAnalysis.CSharp.BoundNode boundRoot, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, bool createSnapshots, out Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager snapshotManager, ref System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.Symbol> remappedSymbols) Line 304	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary.__rewriteAndCache|131_1(ref Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<>c__DisplayClass131_0 value) Line 2029	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary() Line 1990	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 2072	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 540	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, out Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode bindableNode, out Microsoft.CodeAnalysis.CSharp.BoundNode lowestBoundNode, out Microsoft.CodeAnalysis.CSharp.BoundNode highestBoundNode, out Microsoft.CodeAnalysis.CSharp.BoundNode boundParent) Line 1359	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) Line 1237	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) Line 219	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) Line 564	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 4856	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 4955	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 108	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 21	C#
 	Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.exe!Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Generator.GenerateForDocument(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.Host.HostLanguageServices languageServices, Microsoft.CodeAnalysis.Options.OptionSet options, Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.ResultSetTracking.IResultSetTracker topLevelSymbolsResultSetTracker, Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Writing.ILsifJsonWriter lsifJsonWriter, Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Graph.IdFactory idFactory) Line 164	C#
 	Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.exe!Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Generator.GenerateForCompilation.AnonymousMethod__0(Microsoft.CodeAnalysis.SyntaxTree syntaxTree) Line 58	C#
```

Uploading dump.

**Comment by CyrusNajmabadi** [comment] 2021-02-25 00:47
@jcouv

**Comment by CyrusNajmabadi** [comment] 2021-02-25 00:48
The expression we're trying to analyze is: `i.RegisterForSyntaxNotifications(() => new TestSyntaxReceiver(tag: 0, callback: (a) => { if (a is AssignmentExpressionSyntax) throw exception; }))`

**Comment by CyrusNajmabadi** [comment] 2021-02-25 00:49
Note: if i ignore the assert, i can tons more.  Including scary ones like:

![image](https://user-images.githubusercontent.com/4564579/109086322-3894b400-76c0-11eb-9a5f-8c23df05216e.png)

**Comment by CyrusNajmabadi** [comment] 2021-02-25 01:09
Dump is at https://microsoft.sharepoint.com/:u:/t/ManagedLanguagesIDE/ESYj0VoV8BBBpW0IddZoWdEB29MiAFkJ3L-kdu1gtFUK4w?e=yCELag

**Comment by jcouv** [comment] 2021-02-25 01:10
Closing as dupe of https://github.com/dotnet/roslyn/issues/51403

**Comment by 333fred** [comment] 2021-03-03 22:41
I don't believe it's a dupe. Code sample for this:

```cs
public class C
{
    public C(int i) {}

    static void M1()
    {
        C c = new C(() => { M2(); });
    }
    static void M2()
    {}
}
```

**Closed** 2021-03-09 18:35 UTC
Labels: Area-Compilers
