### ISSUE TITLE
Collection expressions generate collection with a base type instead of derived

### ISSUE THREAD

**Issue by jancabadaj** [dotnet/roslyn#76515] opened 2024-12-19 09:28 UTC
Synthesized readonly collection types  `<>z__ReadOnlyList<T>` and  `<>z__ReadOnlyArray<T>` are always generated with base type, which results in unexpected difference in behavior between collection expressions and legacy initializer syntax.

**Steps to Reproduce**:
In the following example, collections generated with collection expression syntax are `<>z__ReadOnlyList<Base>` and `<>z__ReadOnlyArray<Base>`, while the legacy syntax results in `Derived[]`
```csharp
using System.Collections.Generic;
using static System.Console;

class Base{}

class Derived: Base{}

class C
{
    public static (bool, bool) F(IEnumerable<Base> p)
    {
        return (p is IEnumerable<Base>, p is IEnumerable<Derived>);
    }
}

class Program
{
    static void Main() 
    {
        WriteLine(C.F(new[] {new Derived()})); // (True, True)
        WriteLine(C.F(new[] {new Derived(), new Derived()})); // (True, True)

        WriteLine(C.F([new Derived()])); // (True, False)
        WriteLine(C.F([new Derived(), new Derived()])); // (True, False)
    }
}
```

**Expected Behavior**:
The behavior should be the same regardless of which syntax is used.

**Comment by huoyaoyuan** [comment] 2024-12-19 09:35
The behavior is expected, and intentionally different from the old syntax. Collection expression infers its type from target type (outer scope), instead inner elements. Another example:

```csharp
Test([1, 2, 3]); // valid
Test(new[] { 1, 2, 3 }); // invalid

static void Test(byte[] a) { }
```

**Comment by CyrusNajmabadi** [comment] 2024-12-19 16:36
Closing as by design.

**Closed** 2024-12-19 16:36 UTC
Labels: Area-Compilers, untriaged
