### ISSUE TITLE
Custom Task List Tokens no longer working in VS 2019 16.6.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44593] opened 2020-05-27 16:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1041405/custom-task-list-tokens-no-longer-working-in-vs-20.html)._

---
[regression] [worked-in:16.5]
A custom token, like 'EXAMPLE' that annotates a comment line is no longer listed in the task list.  The built in tokens do work.

---
#### Visual Studio Feedback System on 5/21/2020, 03:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2020-05-27 16:55
Dupe of https://github.com/dotnet/roslyn/issues/43788

**Closed by CyrusNajmabadi** 2020-05-27 16:55 UTC

**Comment by mellevsen** [comment] 2020-06-09 03:22
Will apparently be fixed in v16.7​ rf. https://github.com/dotnet/roslyn/pull/44873

**Comment by SezMe** [comment] 2021-03-30 20:33
"Apparently" not.  At 16.9.3 it is still broken.

**Comment by mellevsen** [comment] 2021-03-31 09:02
Agreed, sadly. The Task List contains items from open documents only. So how are we supposed to find which files to open, if our Tasks are not discovered by VS until we open them?! Ridiculous.

**Comment by jmarolf** [comment] 2021-03-31 10:38
> The Task List contains items from open documents only.

to fix this turn on full solution analysis: https://docs.microsoft.com/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code
