### ISSUE TITLE
Peek Definition in C# ignores Language Version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32360] opened 2019-01-10 23:22 UTC
With right-click, peek definition (Alt+F12), the nullable reference types feature is reported as not being supported?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/411186/peek-definition-in-c-ignores-language-version.html
VSTS ticketId: 753476_
_These are the original issue comments:_

johnm on 12/18/2018, 02:10 AM (23 days ago): <p>Not sure what happened to my attachments - peeking at code in the same solution, targeting C# 8, displays an error in the peek definition window, stating that nullable reference types are not supported in C# 7.3 (none of the projects in the solution targets this version).</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jasonmalinowski** [comment] 2019-05-10 17:17
This is a duplicate of #30326.

**Closed by jasonmalinowski** 2019-05-10 17:17 UTC
Labels: Area-IDE, Bug, Developer Community, New Language Feature - Nullable Reference Types
