### ISSUE TITLE
IDE0044 conflicts with CA2104: Do not declare read only mutable reference types

### ISSUE THREAD

**Issue by twest820** [dotnet/roslyn#29637] opened 2018-09-01 14:39 UTC
**Version Used**: Visual Studio 2017 15.8.2 

**Steps to Reproduce**:
```C#
        public class Foo
        {
            private Bar bar; // IDE0044: Make field readonly

            public Foo()
            {
                this.bar = new Bar();
            }

            private class Bar
            {
                public int Mutable { get; set; }
            }
        }
```

**Expected Behavior**: Microsoft issues consistent guidance on best practices for C# coding. Generating an IDE0044: Make field readonly on fields which are of reference type likely contradicts [CA2014](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types?view=vs-2017).

**Actual Behavior**: Based on discussion of CA2104 in #27212, it appears the Roslyn team is reversing the best practices established for use of readonly in the .NET 2.0 coding guidelines. Some quick testing suggests CA2104 has been removed, possibly between VS 15.6 and 15.8. As such, Visual Studio and docs.microsoft.com are out of sync with each other. This is a confusing way to roll out a change and greater clarity on Microsoft's position would be helpful. The pattern in the repro steps is a common one so the reversal of 13 years of guidance leads to a substantial number of code points where the readonly keyword has to be added to clear IDE0044 messages.

I know Microsoft developers and technical writers often work rather independently but, in this case, a trip down the hall wouldn't be excessive. CA2104 and CA2105 derive from quite a bit of discussion back in 2004 and, considering that historical context, I'm surprised not to turn up a blog post from the Roslyn team explaining the change of position.

**Comment by CyrusNajmabadi** [comment] 2018-09-01 18:42
> Actual Behavior: Based on discussion of CA2104 in #27212, it appears the Roslyn team is reversing the best practices established for use of readonly in the .NET 2.0 coding guidelines. 

The .net 2.0 guideline is non-sensical.  Being a mutable reference-type has no bearing on whether or not a field/variable/whatever of that type should be read-only or not.  This part of the escription is correct:

> The read-only modifier ... prevents the field from being replaced by a different instance of the reference type. However, the modifier does not prevent the instance data of the field from being modified through the reference type.

That is true.  But there is not justification for why that is a problem and why should *not* do this.  The purpose of 'readonly' has never been to prevent an instance being modified.  It's to prevent a variable being overwritten.  Telling people they should not do something which is perfectly sensible and works exactly as intended is strange.

> This is a confusing way to roll out a change and greater clarity on Microsoft's position would be helpful.

Perhaps consider passing along this feedback to dotnet/roslyn-analyzers.  They might have a good idea how to go get these docs and whatnot updated.

**Comment by twest820** [comment] 2018-09-01 19:39
Hmm, looking around a bit, from remarks by @srivatsn in [roslyn-analyzers/issues/793](https://github.com/dotnet/roslyn-analyzers/issues/793) it looks like docs.microsoft.com may have been diverged from VS for much of its existence. It might be best to gather a list of discarded/deprecated/obsolete CA rules and push the whole thing over to docs. This, I suspect, is probably something Microsoft's customers prefer pay Microsoft for rather than looking to volunteer their time on. From the outside it's unclear to me which team would be the most natural owner, but that's something y'all can figure out easily enough. There's certainly precedent with deprecated APIs and indicating what's available in which .NET versions.

> Telling people they should not do something which is perfectly sensible and works exactly as intended is strange.

Might I suggest stepping back a bit from the semantic detail of the readonly keyword? When CA2104 and 2105 were introduced I removed readonly from code in essentially the places I'm now adding it, so it's not like I need convincing one way or the other on this issue. However, developers which aren't as close to the language definition easily interpret readonly in a deep, rather than shallow, sense and don't necessarily spot the other interpretation. The .NET 2.0 guidelines derive from acknowledgement of this and discussion across DevDiv about how best to deal with it.

The circumstance isn't unique to readonly. C# offers similar ambiguity with [ICloneable](https://docs.microsoft.com/en-us/dotnet/api/system.icloneable) and [Object.MemberwiseClone()](https://docs.microsoft.com/en-us/dotnet/api/system.object.memberwiseclone), for example, and lacks some of C++'s precision around const *, * const, and const * const. Those of us not involved in early C# specification or .NET core development can say not our mistake/not our problem. But it seems to me such an approach doesn't create much opportunity for improvement.

**Comment by CyrusNajmabadi** [comment] 2018-09-01 19:44
> However, developers which aren't as close to the language definition easily interpret readonly in a deep, rather than shallow, sense and don't necessarily spot the other interpretation. The .NET 2.0 guidelines derive from acknowledgement of this and discussion across DevDiv about how best to deal with it.

I can see that argument.  However, my concern is that that rule actively made things worse, especially for people who did understand the language.  For those that did not understand, i'm skeptical it made things better.  :)

> Hmm, looking around a bit, from remarks by @srivatsn in roslyn-analyzers/issues/793 it looks like docs.microsoft.com may have been diverged from VS for much of its existence. It might be best to gather a list of discarded/deprecated/obsolete CA rules and push the whole thing over to docs.

Seems reasonable to me.  However, i think dotnet/roslyn-analyzers would have hte best insight on how to do that.  None of these docs are related to the dotnet/roslyn project itself.  Whereas dotnet/roslyn-analyzers actually concerned itself with providing the modern CA analyzers impl.  So i'm hoping they know who to talk to about these docs.  :)

**Comment by sharwell** [comment] 2018-09-03 15:03
:memo: CA2104 is only supposed to get reported for externally-visible fields. Externally-visible fields are already excluded from IDE0044 analysis.

**Comment by sharwell** [comment] 2018-09-06 16:53
@mavasani Do you know if CA2104 is filtered to externally-visible fields?

**Comment by mavasani** [comment] 2018-09-06 17:02
@sharwell CA2104 has not been ported to roslyn-analyzers, primarily due to the fact that the rule can be very noisy. See https://github.com/dotnet/roslyn-analyzers/issues/793#issuecomment-206621893. If we were to decide to port it, then I agree that it ought be done only for externally visible fields.

**Comment by sharwell** [comment] 2018-09-06 17:07
Based on that, it sounds like there is no current or proposed overlap between IDE0044 (applies only to private fields) and CA2104 (applies only to exposed fields). I'm tentatively marking this as **Won't Fix** but will bring it to a design review and update with the results before closing.

**Comment by sharwell** [comment] 2018-09-14 01:46
We concluded a few things in the design meeting:

1. Since IDE0044 (private only) and CA2104 (exposed only) do not overlap, there is no current conflict.
2. If in the future IDE0044 considered exposed fields, we would prefer to implement the analysis to the most accurate allowable extent, even if that goes against CA2104.
3. A documentation bug should be filed to update the description of CA2104, as it doesn't seem to be a consistent point of guidance anymore (a legacy rule that is likely to be removed over time, but still exists in some form today which is confusing to users).

**Closed by sharwell** 2018-09-14 01:46 UTC
Labels: Area-Analyzers, Resolution-By Design, Concept-Diagnostic Clarity, Feature - IDE0044

**Comment by jinujoseph** [comment] 2018-09-14 17:46
cc @gewarren to help with documentation part

**Comment by gewarren** [comment] 2018-09-24 19:06
@sharwell @jinujoseph Can you clarify how the CA2104 guidance should be updated? https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types?view=vs-2017

**Comment by gewarren** [comment] 2018-11-02 01:06
@jinujoseph @mavasani I updated the CA2104 topic to include the following paragraph. Was this the change that was requested, or was the change to say that the rule is deprecated?

"This rule may inadvertently show a violation for a type that is, in fact, immutable. In that case, it is safe to suppress this rule. The rule checks the type against a finite list of types that are known to have immutable semantics, and it considers anything else mutable."

**Comment by gewarren** [comment] 2018-11-02 04:59
Thank you @sharwell. I added a note that the rule is obsolete. Can someone review the staged article?

https://review.docs.microsoft.com/en-us/visualstudio/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types?view=vs-2017&branch=pr-en-us-3207

**Comment by mavasani** [comment] 2018-11-02 12:52
@gewarren LGTM

**Comment by sharwell** [comment] 2018-11-02 13:43
👍

**Comment by jinujoseph** [comment] 2018-11-04 09:57
LGTM

**Comment by kinloongTong** [comment] 2019-05-15 06:48
@sharwell @jinujoseph, @mavasani  for CA2104, should the implementation change the list of a known mutable type, rather obsolete it?

"> FxCop's implementation of CA2104 basically had a list of type that were known to have immutable semantics and it considered anything else mutable. It didnt really check for immutability of a type which requires complicated analysis. We've decided to not reimplement CA2104 as an analyzer (see #716) since in it's current form it is very noisy."

**Comment by sharwell** [comment] 2019-05-15 12:25
@kinloongTong CA2104 was deemed incorrect for both immutable types and mutable types.
