### ISSUE TITLE
Suggest exceptions to catch with try-catch block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41015] opened 2020-01-16 19:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/885897/suggest-exceptions-to-catch-with-try-catch-block.html)._

---
Add a feature to provide suggestions of all the possible Exceptions for catch in case of writing a code in the try block.
For more info, here is a Stackoverflow question with similar suggestion for Resharper:
https://stackoverflow.com/questions/41819897/can-resharper-2016-1-c-suggest-exceptions-to-catch-with-a-try-catch-block

This feature also might be useful especially when some custom exceptions are thrown which are usually are meant to be caught, so, after detecting and suggesting the possible exceptions it might also suggest to catch at least the custom ones.

---
#### Visual Studio Feedback System on 1/16/2020, 00:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by paul1956** [comment] 2020-01-16 20:44
As part of this it would be great if there was an easy way to catch a specific Roslyn/Custom exception, right now you get a number and string but there is no easy way (that I know) to translate that something I can add to a Catch statement, also a way to ignore ignore errors where the finally block will provide a reasonable response. This has to do with # CA1031: Do not catch general exception types.

**Comment by oliverjanik** [comment] 2020-05-14 01:31
Coming up with a list of all possible exceptions that a try block can throw would help immensely to help write correct and well behaved libraries without hunting through documentation. 

Even more important a dependency throws exceptions you're not aware of and they bubble up to your consumer and effectively become part of your public API.

**Comment by paul1956** [comment] 2020-06-24 23:23
There was some discussion on Gitter that "we cannot give precise answers about "what exceptions may be thrown"" so why is there a Analysis Rule CA1031 that recommends "Do not catch general exception types" with no help on what you should trap? It seems like this would always need to be ignored. Would a rule/fix be better if it detected that I tried to catch some specific exceptions but there is still one catch all case. This fix should create specific fixes that it could detect for obvious issues like a list of IOExceptions on Open File as an example.  This would  be a work in process forever but would be much better then what we have today where I have no idea what the specific exception might be and how to catch it. Maybe the solution is a website where error exceptions are kept with their definitions and an example catch statement as least for Roslyn and DotNet Core to start.

**Comment by CyrusNajmabadi** [comment] 2020-06-25 19:10
> so why is there a Analysis Rule CA1031 that recommends "Do not catch general exception types" 

Because this will generally mask bugs.

> with no help on what you should trap?

You should trap exceptions that are expected as part of normal non-error control flow, and only when you can do something sensible with them.  If you don't know which exceptions to trap, you very very likely should not be trying to catch them.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 04:32
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-11-06 04:32 UTC
Labels: Area-IDE, Feature Request, Developer Community
