### ISSUE TITLE
[Feedback] EditorConfigDocumentOptionsProvider crashes while opening document

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31825] opened 2018-12-16 03:12 UTC
I had multiple crashes while trying to save the current source (C#).
It is a big concern seeing VS crashing while editing a very simple project.
The solution is composed of a shared project, two netstandard libraries, one netcore project targeting both net472 and netcoreapp2.1, one net472 console and a test project (all C#).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/409318/vs2019-not-stable.html
VSTS ticketId: 752419_

```
Fault Bucket: 1390201738414104916
Hashed Bucket: ce2ec2443cb51b55834afd1d904da154
```

**Comment by davkean** [comment] 2018-12-16 03:13
```

Message: System.ArgumentException: An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.Workspace_DocumentOpened(Object sender, DocumentEventArgs e)
   at Microsoft.CodeAnalysis.Workspace.<>c__DisplayClass198_1.<RaiseDocumentOpenedEventAsync>b__1(EventHandler`1 handler)
   at Roslyn.Utilities.EventMap.Registry`1.Invoke(Action`1 invoker)
   at Roslyn.Utilities.EventMap.EventHandlerSet`1.RaiseEvent(Action`1 invoker)
   at Microsoft.CodeAnalysis.Workspace.<>c__DisplayClass198_0.<RaiseDocumentOpenedEventAsync>b__0()
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass2_0.<SafeContinueWith>g__continuationFunction|0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass6_0`1.<SafeContinueWith>g__outerFunction|0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>g__outerFunction|0(System.Threading.Tasks.Task)
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.Workspace_DocumentOpened(System.Object, Microsoft.CodeAnalysis.DocumentEventArgs)
   at Microsoft.CodeAnalysis.Workspace+<>c__DisplayClass198_1.<RaiseDocumentOpenedEventAsync>b__1(System.EventHandler`1<Microsoft.CodeAnalysis.DocumentEventArgs>)
   at Roslyn.Utilities.EventMap+Registry`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Action`1<System.__Canon>)
   at Roslyn.Utilities.EventMap+EventHandlerSet`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].RaiseEvent(System.Action`1<System.__Canon>)
   at Microsoft.CodeAnalysis.Workspace+<>c__DisplayClass198_0.<RaiseDocumentOpenedEventAsync>b__0()
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass2_0.<SafeContinueWith>g__continuationFunction|0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>g__outerFunction|0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioTaskSchedulerFactory+JoinableTaskFactoryTaskScheduler+<>c__DisplayClass5_0+<<QueueTask>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by davkean** [comment] 2018-12-16 03:13
tag @heejaechang

**Comment by sharwell** [comment] 2018-12-18 15:43
I hit this several times this morning but couldn't figure out a specific set of steps to reproduce.

**Comment by jinujoseph** [comment] 2019-01-03 00:45
also reported at [here ](https://developercommunity.visualstudio.com/content/problem/403108/vs-crashed-and-restarted-when-switching-branch.html)

**Comment by jasonmalinowski** [comment] 2019-01-03 18:31
This is also being see in Watson [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742115). @sharwell I'm giving you the Watson as well.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 18:12
Closing out due to lack of prism hits and that we heavily refactored this.

**Closed by CyrusNajmabadi** 2024-10-21 18:12 UTC
Labels: Bug, Area-IDE, Tenet-Reliability, Developer Community
