### ISSUE TITLE
ASP.NET MVC files in "App_Code" folder get *two* contexts, and many extra errors in error list

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#3068] opened 2015-05-24 20:44 UTC
Roslyn appears to get confused and create two Intellisense contexts for just one project in this solution. One of them are incompletely initialized, resulting in several inappropriate errors in the error list.

Repro steps:

1. Git clone https://github.com/AArnott/IronPigeon.git (I'm at HEAD ce8a9d0ee, which is `master` at the moment)
2. Open `src\IronPigeon.sln` using VS2015
3. Build the IronPigeon.Relay project (NuGet package restore will jump in, which is fine). The build should be successful. But the error list will eventually populate with about 13 errors from the `InboxOwnerAuthorize.cs` file. 
4. Open the `InboxOwnerAuthorize.cs` file. Notice that the context switcher dropdown shows the IronPigeon.Relay project *twice*.
5. Also notice if you bring up Intellisense on any of the errors that Roslyn reports that the type is both available and not available for the "two heads" which are actually the same project.

This repros on D14REL 22823.1 and on a separate machine with VSPro_Platform 22915.00

**Comment by dpoeschl** [comment] 2015-05-24 23:44
This repros on our current basedrop as well.

**Comment by dpoeschl** [comment] 2015-05-25 00:11
I'm not sure where this should be fixed, but here's what I've found so far:

Within the IronPigeon.Relay project, this only repros for files in the ```App_Code``` folder. The Roslyn Solution object contains two relevant projects:
1. The full project:
    * Assembly name: IronPigeon.Relay
    * Contains 32 documents, *including* the App_Code documents
    * References IronPigeon and IronPigeon.Desktop
2. The App_Code-only project
    * Assembly name: 1_App_Code
    * Contains 2 documents, only the App_Code documents
    * References IronPigeon, IronPigeon.Desktop and IronPigeon.Relay

If the App_Code folder is renamed to anything else, like  "Not_App_Code", then the problem goes away.

I don't know all the details, but I believe normal processing of files in the App_Code folder of web projects is to create projects for them when they're opened and remove those projects when they're closed (and for those files not to contribute to their containing project). It seems like this behavior is indeed happening for the files in this folder, but they are *also* contributing to their containing project here. This causes these files to appear in two Roslyn projects with the same file path, which we use as a key to consider them "linked", and the rest flows from there (though we really shouldn't be seeing some of the IntelliSense Warning Icons in this case, but that might be fixed by a recent fix from @rchande).

**Comment by jasonmalinowski** [comment] 2015-05-25 00:43
This can sometimes happen if people converted a Web *Site* to a Web *Application* inappropriately, resulting in the build confusion. If the solution is opened in VS 2013, what happens? Does it actually run?

**Comment by AArnott** [comment] 2015-05-25 01:28
@jasonmalinowski  VS2013 does not repro the problem.

**Comment by dpoeschl** [comment] 2015-05-29 19:24
[Summarizing offline discussions]

The files in the App_Code folder are marked with Build Action = "Compile", which means they will be included in the project assembly in VS and in assembly built at runtime by ASP.Net, so the two contexts in the navbar is not unexpected, and this reproduces with your project in VS2013 Update4.

When we switch these files to Build Action = "Content", then we still see the same errors ("System.Linq can't be found", etc) in both Roslyn and VS2013. The remaining difference is that Roslyn is showing these errors when in "Compile" while VS2013 did not, but we suspect that VS2013 wasn't showing these errors when the Build Action was "Compile" due to limitations of real-time errors in the IDE in Dev12.

I'd suggest either 
1. Renaming the folder if you don't intend on having ASP.Net generate the assembly for these files at runtime
2. If you do intend on having ASP.Net generate the assembly for these files at runtime, then switch the Build Action to "Content" and then fix up those errors (the same ones that appear in Dev12 when marked as "Content").

**Closed** 2015-05-29 19:30 UTC
Labels: Area-IDE, Bug, Resolution-By Design
