### ISSUE TITLE
`DisallowNull` not respected with unconstrained generics

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#40141] opened 2019-12-04 21:23 UTC
```cs
using System;
using System.Diagnostics.CodeAnalysis;
#nullable enable
public class C<T> {
    public void M(T t) {
        M2(t); // Should warn, doesn't
    }
    
    public void M2([DisallowNull] T t) {}
}
```

**Comment by jcouv** [comment] 2019-12-12 00:55
Took a quick look. The problem is that we don't have a type to represent `[DisallowNull] T`.

So in `VisitArgumentConversionAndInboundAssignmentsAndPreConditions`, `ApplyLValueAnnotations` doesn't tighten the target type. `T` with `DisallowNull` just produces a `T`.
Will need to think about how to fix that...

``` csharp
  var stateAfterConversion = VisitConversion(
                            conversionOpt: conversionOpt,
                            conversionOperand: argumentNoConversion,
                            conversion: conversion,
                            targetTypeWithNullability: ApplyLValueAnnotations(parameterType, parameterAnnotations),
                            operandType: resultType,
                            checkConversion: true,
                            fromExplicitCast: false,
                            useLegacyWarnings: false,
                            assignmentKind: AssignmentKind.Argument,
                            parameterOpt: parameter,
                            extensionMethodThisArgument: extensionMethodThisArgument,
                            stateForLambda: result.StateForLambda);
```

**Comment by jcouv** [comment] 2020-01-29 00:26
This was fixed recently. I'll go ahead and close the issue.

``` csharp
        [Fact]
        public void DisallowNull_Parameter_01()
        {
            // Warn on misused nullability attributes (F2, F3, F4)? https://github.com/dotnet/roslyn/issues/36073
            var source =
@"using System.Diagnostics.CodeAnalysis;
class Program
{
    static void F1<T>([DisallowNull]T t) { }
    static void F2<T>([DisallowNull]T t) where T : class { }
    static void F3<T>([DisallowNull]T? t) where T : class { }
    static void F4<T>([DisallowNull]T t) where T : struct { }
    static void F5<T>([DisallowNull]T? t) where T : struct { }
    static void M1<T>(T t1)
    {
        F1(t1); // 0
    }
...
````

**Closed by jcouv** 2020-01-29 00:26 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
