### ISSUE TITLE
Support standard input in the interactive window

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6666] opened 2015-11-10 01:04 UTC
Currently, the host doesn't redirect standard input, so all consumers receive nothing.

**Comment by amcasey** [comment] 2015-11-10 01:04
1.3 pending feedback.

**Comment by KevinH-MS** [comment] 2015-12-23 22:18
@genlu would you be able to look at this?

**Comment by genlu** [comment] 2016-01-04 19:02
@KevinH-MS I will take a look this week. So we are trying to fix this in 1.2?

**Comment by KevinH-MS** [comment] 2016-01-04 19:36
It seems like enough people have run into this that we should try to address it for 1.2 (via e-mail and the referenced issue above).  @ManishJayaswal , please chime in if that doesn't sound like the right priority.

**Comment by genlu** [comment] 2016-05-16 18:07
#7743 is related.

**Comment by ManishJayaswal** [comment] 2016-10-14 23:03
closing this as it is a dupe of #7743

**Closed by ManishJayaswal** 2016-10-14 23:03 UTC
Labels: Area-Interactive, Feature Request, Interactive-ScriptingIDE
