### ISSUE TITLE
Remove usings when needed inside a #if block

### ISSUE THREAD

**Issue by mnash1** [dotnet/roslyn#3446] opened 2015-06-11 16:08 UTC
If you have the following and then use the remove all usings from solution option when the current configuration is set to release, it will remove the using System even though its needed for debug.

```
using System;

public class Foo
{
  public statis int Bar(int x, int y)
  {
    int sum = x + y;
# if DEBUG


Console.WriteLine(sum);

# endif


return sum;


  }
}
```

**Comment by HaloFour** [comment] 2015-06-11 16:57
Would be nice if it were smart enough to know that it could wrap those `using` directives in their own `#if` directive.

I wonder how the compiler could work around the fact that what appears in those conditional directives can be complete garbage, unrecognizable by the compiler.  I assume Roslyn doesn't even attempt to parse that code, but it would have to in order to know whether or not there may be code in there that would require those `using` statements.

**Comment by Pilchie** [comment] 2015-06-12 16:36
One thing we've considered for this sort of problem is to create roslyn "documents" for all of the project configurations, and union results of them together, much the way we now union results from different projects for files included in multiple projects.

That would be a significant amount of work though, and it's not clear that people actually use `#if` enough to make it worth it.

**Comment by HaloFour** [comment] 2015-06-12 16:48
That would require creating a document for each possible combination of compiler directive symbols, no?

```cs
#if FOO
// content
#endif
#if BAR
// content
#endif
#if BAZ
// content
#endif
```

Would require the compiler to attempt to generate 12 documents?

**Comment by Pilchie** [comment] 2015-06-12 17:02
Ideally, I think we would do it based on configurations defined in the .csproj, not based on all possible preprocessor directives.

**Comment by mnash1** [comment] 2015-06-25 20:27
It might be enough to simply take into account some of the in built compiler directives like #if DEBUG vs #if ANYTHING_I_WANT

As far as how much people are using it, we mostly use it for logging that we really really don't want to run other than on our dev machines when we are running debug builds.

Most logging systems allow you to set log levels debug, warn, error, etc, however sometimes you want things that are even more granular than debug and that's usually when you are debugging on your own machine.  On top of that simply constructing the logging can add a significant overhead to the application and the #if obviously keeps that from happening if used correctly.

Other than that I don't use #if for anything else.

**Comment by Pilchie** [comment] 2015-06-25 20:32
DEBUG is not known to the compiler - it's only known to the common C# targets in MSBuild.

**Comment by sharwell** [comment] 2019-02-11 20:07
Also reported here: https://developercommunity.visualstudio.com/content/problem/448920/remove-and-sort-using-command-doesnt-support-if-pr.html

**Comment by dehghani-mehdi** [comment] 2019-04-15 10:16
Any update here?

**Comment by sharwell** [comment] 2019-04-15 16:27
Duplicate of #24084

**Closed by sharwell** 2019-04-15 16:27 UTC
Labels: Area-IDE, Feature Request
