### ISSUE TITLE
IDE0058 - Questionable behavior when the return value of some functions is discarded

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#50439] opened 2021-01-13 20:50 UTC
```csharp
static void F(StringBuilder sb)
{
    sb.AppendLine("Hello");
}
```

triggers IDE0058. There are many similar cases where it's typical to discard a result and the suggestion is a nuisance. Though deciding for which cases it's valuable to have the suggestion is a different matter...

Some other examples I ran into:

* `Interlocked.Increment`
* `MethodBase.Invoke` if the target method happens to be `void`-returning
* `bool`-returning `Remove` methods for collections if one doesn't care whether the item was found or not
* `bool`-returning `Add` methods, like the case above
* `Visit` methods for an expression visitor that just does an analysis rather than a rewrite

The majority of warnings (> 80%) that were a nuisance to suppress (and thus led me to disabling IDE0058 altogether) had to do with `Append` and `AppendLine`, though there were a handful of places where a "fluent" pattern of chaining `Append*` calls was possible.

**Comment by bartdesmet** [comment] 2021-01-13 20:54
FWIW, the C++ approach of `[[nodiscard]]` does have some merits because APIs clearly state when the result of a method call (or an instance of a type marked as such) shall not be dropped. Maybe such metadata would be worth having (at the expense of having to annotate a ton of APIs, which has to be weighed against the benefits; there's of course prior art with the whole `#nullable` business), which would be a much bigger discussion than an analyzer of course. The converse attribute "safe to discard" could be an alternative.

**Comment by mavasani** [comment] 2021-04-19 10:30
Duplicate of https://github.com/dotnet/roslyn/issues/47832. Please add your suggestions to that issue. Thanks!

**Closed by mavasani** 2021-04-19 10:30 UTC
Labels: Resolution-Duplicate, Area-IDE, Concept-Continuous Improvement

**Comment by Jehoel** [comment] 2021-07-22 17:36
@bartdesmet Regarding `Interlocked.Increment`, I understand that when the `ref` parameter is a field (or in a closure) then you need to use the return value and not the `ref` parameter. 

As for the other cases you point out, you're meant to assign to the _discard variable_: `_ = list.Add(123);`  as that explicitly signifies intent to discard the result.

The issue I created #47832 concerns the cases where the discard-value is truly superfluous, namely when dealing with methods that `return this`, I don't intend my suggestion for suppressing possibly-unintentionally-discarded results.
