### ISSUE TITLE
Using statements in C# optional

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49327] opened 2020-11-12 19:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Some-of-my-suggestions/1241705?preview=true)._

---
<p>1. Can we have the using statement in C# the same as C++ (without the braces { }, or make it optional?)</p> <p>2. We have cshtml and cs bundled together in PageModel, can we bundle a JS file together with that page as well? Since 90% of the pages will require some JavaScripts, and putting those files in a separate folder is a bit difficult to manage especially when the project grow larger.</p>

---
#### Feedback Bot on 11/3/2020, 00:02 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-11-12 22:26
Dupe of https://github.com/dotnet/csharplang/issues/137.

**Closed by CyrusNajmabadi** 2020-11-12 22:26 UTC
Labels: Area-IDE, untriaged
