### ISSUE TITLE
Code fix adding access modifier removes "extern"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35735] opened 2019-05-15 21:32 UTC
VSF_TYPE_MARKDOWNFor a static extern method (P/Invoke), I get the suggestion to add an access modifier. When I use it, the &quot;private&quot; is added but the &quot;extern&quot; is removed. This breaks the code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/564842/code-fix-adding-access-modifier-removes-extern.html
VSTS ticketId: 891487_
_These are the original issue comments:_

Visual Studio Feedback System on 5/13/2019, 01:08 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-05-22 18:27
Duplicate of #29561

**Closed by jinujoseph** 2019-05-22 18:27 UTC
Labels: Area-IDE, Developer Community, Resolution-Duplicate
