### ISSUE TITLE
Method/property intellisense tooltips should show contents of <exception> XML tags.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39788] opened 2019-11-12 22:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/800099/methodproperty-intellisense-tooltips-should-show-c.html)._

---
''' &lt;summary&gt;
''' Retrieves the ADO.NET connection string.
''' &lt;/summary&gt;
''' &lt;param name=&quot;session&quot;&gt;The session state.&lt;/param&gt;
''' &lt;returns&gt;The ADO.NET connection string.&lt;/returns&gt;
''' &lt;exception cref=&quot;Exception&quot;&gt;if the connection string was not found.&lt;/exception&gt;
&lt;Extension()&gt;
Public Function GetConnectionString(ByVal session As HttpSessionState)\
...
End Function

So now if I hover over `GetConnectionString` I get a nice tooltip but for the exception it just says Exception, and the contents of the &lt;exception&gt; tag are nowhere to be found. It would be nice to have this in the tooltip, e.g. &quot;Exception if the connection string was not found.&quot;

This feature request applies to both VB and C#, but the example I have at the moment is VB.

---
#### Visual Studio Feedback System on 10/31/2019, 07:41 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2019-11-12 22:10
Duplicate of #1515

**Closed by sharwell** 2019-11-12 22:10 UTC
