### ISSUE TITLE
IDE0090 incorrectly gets suggested in multi-targeted projects

### ISSUE THREAD

**Issue by magnusbakken** [dotnet/roslyn#52727] opened 2021-04-19 09:36 UTC
**Version Used**:
Visual Studio 16.9.1

**Steps to Reproduce**:
1. Create a project that multi-targets two framework versions, e.g. .NET 4.8 and .NET 5.0.
2. Create a class in the multi-targeted project that includes a line like this: `private object o = new object();`
3. Run the suggested code fix that converts the line to `private object o = new();`

![multi-target-code-fix](https://user-images.githubusercontent.com/284189/115213966-5a2f7c00-a102-11eb-8584-6382d54e6b2b.gif)

This is very similar to #38048 and #49925, so I assume it's a general issue.

**Expected Behavior**:
The code fix is invalid for .NET 4.8 (unless you've overridden the language version), so I would expect the code fix not to get suggested at all, although I've gathered from the related issues that this is difficult to handle.

**Actual Behavior**:
The code fix gets executed, and afterwards you'll have a compilation error.

**Comment by Youssef1313** [comment] 2021-04-19 10:26
It's indeed a general issue. Even to third-party analyzers. See https://github.com/dotnet/roslyn-analyzers/issues/4998#issuecomment-813487643 for detailed explanation.

For your case, I suggest you either use C# 9 for all TFMs or disable the analyzer for this project.

**Comment by sharwell** [comment] 2021-04-20 17:59
Since this analyzer is behaving as intended, I'm going to mark this issue as a duplicate of #49925 since it has more details about the overall expectations in this space.

**Comment by sharwell** [comment] 2021-04-20 17:59
Duplicate of #49925

**Closed by sharwell** 2021-04-20 17:59 UTC
Labels: Resolution-Duplicate, Area-IDE
