### ISSUE TITLE
Microsoft.Net.Compilers overwrites referenced version of System.ValueTuple

### ISSUE THREAD

**Issue by czb182** [dotnet/roslyn#20278] opened 2017-06-16 19:59 UTC
Unsure if this is issue with microsoft.net.compilers nuget package, or msbuild

**Version Used**: Microsoft.Net.Compilers 2.1.0, System.ValueTuple 4.3.1, msbuild 14.0

**Steps to Reproduce**:

1. Create Legacy Asp.net MVC App (5.2.3 in my case) 
2. Add Nuget reference to both Nuget Package Above 
3. msbuild /p:OutDir=C:\dir1 /p:DeployOnBuild=false /p:WebPublishMethod=FileSystem
4. contents of system.valuetuple along with other files get copied to C:\dir1
5. many dll's from tools directory of microsoft.net.compilers, including system.valuetuple get copied into C:\somedir, overwriting version referencing in system.valuetuple nuget package

**Expected Behavior**:
microsoft.net.compilers should probably have dependency on system.valuetuple nuget packages, and maybe other ones too

**Actual Behavior**:
blindly overwrites existing properly referencing version of system.valuetuple with one hidden in tools directory of microsoft.net.compilers

**Comment by jaredpar** [comment] 2017-06-16 23:36
> microsoft.net.compilers should probably have dependency on system.valuetuple nuget packages, and maybe other ones too

The Microsoft.Net.Compilers package is a tool NuGet package vs. an API one. It doesn't list any dependencies because no one should reference the binaries here. Instead it's meant to deploy a functioning version of the compiler. 

> blindly overwrites existing properly referencing version of system.valuetuple with one hidden in tools directory of microsoft.net.compilers

Based on this description it sounds like contents of the Microsoft.Net.Compilers package is being deployed into the same directory as your web application dependencies. That is definitely going to cause some problems as dependencies will end up clashing (as you're seeing here). 

My understanding is that legacy apps tend to deploy Microsoft.Net.Compilers into a sub-directory, generally `bin\roslyn` instead of simply `bin`.  Is there a reason you're not doing that here? 

CC @Jinhuafei

**Comment by czb182** [comment] 2017-06-19 20:10
msbuild was basically dump contents of microsoft.net.compilers into bin folder directly instead of roslyn folder.  I fixed by modifying msbuild parameters to add ones in bold
/p:WebPublishMethod=FileSystem **/p:UseWPP_CopyWebApplication=true /p:PipelineDependsOnBuild=false**

I found these properties by examining "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets"

now msbuild correctly puts contents of tools directory in package into roslyn folder in bin.  Seems like this is bug with msbuild webapplication targets file

**Comment by jcouv** [comment] 2017-06-27 17:42
Assigned to @jaredpar who is driving an effort to rationalize nuget packages and document proper usage.

**Comment by jaredpar** [comment] 2017-07-07 18:39
CC @Jinhuafei

Are you aware of this issue? This behavior does seem to be in error but it's more in the Web code than compiler. 

Perhaps this is the cause of the long standing issue around partial deployments generating Watson bugs.

**Comment by Jinhuafei** [comment] 2017-07-07 19:54
If the Roslyn bits are not deployed to bin\Roslyn folder, you will see "Could not find a part of the path ...". While in the Watson bugs, it complains specific dll can not be loaded.

**Comment by jaredpar** [comment] 2017-07-08 00:50
@Jinhuafei in this case the user is seeing the compiler bits deployed to the same folder as the application. In that case it's possible to get mixed versions because the app and compiler are basically stomping over each others files. That could lead to the version mismatch issues.

**Comment by Jinhuafei** [comment] 2017-07-10 22:41
The properties you passed to msbuild may change the msbuild execution pipeline. We only covers most common msbuild scenarios. AFAIK, the right way to publish a web app from msbuild is something like this.

msbuild /t:rebuild /p:DeployOnBuild=true /p:PublishProfile=FolderProfile.pubxml

**Comment by czb182** [comment] 2017-07-11 15:47
I tried using only /p:OutDir or /p:OutputPath as msbuild parameters, which still triggers publish, but I still get behavior of it dumping roslyn folder into bin folder.  I wanted to avoid using publish profiles so that I could leave build configuration in TFS and out of solution.  For now I will continue to rely on /p:UseWPP_CopyWebApplication=true /p:PipelineDependsOnBuild=false which seems to trigger a different and more correct publish behavior.

**Comment by jaredpar** [comment] 2017-07-20 16:48
@czb182 can you share out your build logs? Add the following parameters to your command line build `/fl /flp:v=diag`. That will produce a file msbuild.log in the same directory. If you could share that out it would help track down what is going on here.

**Comment by czb182** [comment] 2017-07-21 20:04
created new asp.net mvc web application project.  built with msbuild /p:OutDir=C:\Tmp2 /fl /flp:v=diag
has same incorrect behavior as i described
uploaded msbuild.log as msbuild.txt

[msbuild.txt](https://github.com/dotnet/roslyn/files/1166623/msbuild.txt)

**Comment by jaredpar** [comment] 2017-07-21 20:50
@czb182 thanks for providing that file.

I've dug through this a bit and I don't see that MSBuild is overwriting the files here. I dug through the copy behavior for two files in particular here: System.ValueTuple.dll and Microsoft.CodeAnalysis.dll. For both files every copy / write in the log is properly placing them in the sub-directory `roslyn`  for both `c:\Tmp2` and the WebApplication2 bin directory. Nothing seems amiss there. 

I tried reproducing this with the steps that you listed and was unable to do so. Feel like there is a missing step there as I ended up with the 1.3 Roslyn compiler. That doesn't include System.ValueTuple. as we didn't take the dependency until 2.0. Did you change any of the config files to get a newer compiler here?

**Comment by Jinhuafei** [comment] 2017-07-21 20:53
@czb182 sounds like same issue as https://github.com/aspnet/RoslynCodeDomProvider/issues/2. Also, I created a [PR](https://github.com/aspnet/RoslynCodeDomProvider/pull/11/files) to fix this issue. If you can give it a try, that will be great.

**Comment by czb182** [comment] 2017-07-24 13:38
@jaredpar I forgot to mention i updated nuget packages, so that it got latest compiler (2.3.1).
 You can find System.ValueTuple.dll being incorrectly copied to bin folder in line 10121.
  Copying file from "C:\Users\mirec\Documents\Visual Studio 2017\Projects\WebApplication2\packages\Microsoft.Net.Compilers.2.3.1\tools\System.ValueTuple.dll" to "C:\Tmp2\_PublishedWebsites\WebApplication2\bin\System.ValueTuple.dll". (TaskId:46)

@Jinhuafei i will try

**Comment by czb182** [comment] 2017-07-24 14:39
@Jinhuafei I pulled down branch, did local build and used that built nuget package.  Did not help.  Attaching msbuild log.

Line 10581
Copying file from "C:\Users\mirec\Documents\Visual Studio 2017\Projects\WebApplication2\packages\Microsoft.Net.Compilers.2.3.1\tools\System.ValueTuple.dll" to "C:\Tmp2\_PublishedWebsites\WebApplication2\bin\System.ValueTuple.dll". (TaskId:47)

[msbuild.txt](https://github.com/dotnet/roslyn/files/1170130/msbuild.txt)

**Comment by jaredpar** [comment] 2017-07-24 16:04
@czb182 

>  I forgot to mention i updated nuget packages, so that it got latest compiler (2.3.1).

How do you do this? I tried a few different ways and didn't get the upgrade I was expecting. Can you share out the relevant lines in packages.config?

**Comment by Jinhuafei** [comment] 2017-07-24 16:53
@czb182 Looks like the codedomProvider you built doesn't have the change I made. I shared the package [here](https://app.box.com/s/5h0f9km4eaktb30qd2gzl1ui430umg6w). Can you give it a try?

**Comment by czb182** [comment] 2017-07-24 18:59
@jaredpar steps i took

1. VS2017 -> New Project (ASP.NET Web Application (.NET Framework) 4.6.1 -> MVC
2. VS2017 -> Manage Nuget Packages - > Update All
3. Developer Command Prompt for VS2017 -> msbuild /p:OutDir=C:\Tmp2 /fl /flp:v=diag

check here
https://github.com/czb182/test-roslyn-web-app

**Comment by czb182** [comment] 2017-07-24 19:03
@Jinhuafei I just tested your updated package on that test repo i published above and it is working : )

**Comment by Jinhuafei** [comment] 2017-07-24 20:13
Great! The new package should be released soon.

**Comment by jaredpar** [comment] 2017-07-24 21:24
@Jinhuafei which fix was included in this package? Curious to see what changed. Want to better undestand the flow here.

**Comment by Jinhuafei** [comment] 2017-07-24 23:19
@jaredpar Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props change in [this PR](https://github.com/aspnet/RoslynCodeDomProvider/pull/11/files#diff-2d089bf0f70173dd8c1fa0c5d225ce3a)

**Comment by jaredpar** [comment] 2017-07-31 18:22
Closing as we seem to have identified the issue.

**Closed by jaredpar** 2017-07-31 18:22 UTC
Labels: Area-Compilers, New Language Feature - Tuples

**Comment by Jinhuafei** [comment] 2017-08-04 16:35
@czb182  DotNetCompilerPlatform 1.0.6 is released on nuget.org
