### ISSUE TITLE
Bitwise operators crash intellisense documentation

### ISSUE THREAD

**Issue by DJAntivenom** [dotnet/roslyn#74782] opened 2024-08-13 09:24 UTC
## Environment information ##

**VSCode version**: 1.92.0
**C# Extension**: 2.34.12
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.7 [\<redacted\>/config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.7~x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>

## Steps to reproduce

1. Create an xml documentation comment for a function, class or similar.
2. Add the `<code>` tag
3. Add the bitwise-and operator
4. Hover over the name of the function
5. See error

### Example
```csharp
/// <summary>
/// This is a nice function
/// <para/>
/// Here is an example of how to use it:
/// <code>
/// if ((NiceFunction() & 0b001) > 0)
/// {
///     ...
/// }
/// </code>
/// </summary>
public byte NiceFunction() { ... }
```

## Expected  behavior
An intellisense window with a simplified version of the generated documentation should appear.

## Actual behavior
Intellisense somehow fails and no documentation at all is displayed, not even the first paragraph.

## Additional context
The problem is the `&`. If it is removed the generation works.

**Comment by CyrusNajmabadi** [comment] 2024-08-15 23:28
`&` is not legal in xml as it is the start of an xml code.  You need to do something like `&amp;`.

**Comment by dibarbet** [comment] 2024-08-15 23:42
Ah, yup that works.  Going to close this as by design then since the XML comment is incorrectly formatted.

XML ref - https://www.w3.org/TR/xml/

**Closed by dibarbet** 2024-08-15 23:42 UTC
Labels: Area-IDE, untriaged

**Comment by DJAntivenom** [comment] 2024-08-16 10:37
Oh, I didn't know that. Thanks for help :heart:
