### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p3 on PR #9378

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9385] opened 2016-03-02 01:14 UTC
PR: [#9378](https://github.com/dotnet/roslyn/pull/9378) *Improve the Generate-Variable code-actions menu experience.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/391/

**1 Test Failures:**
CSharpReplClassification.1) Verify color of some tokens

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpReplClassification.xml

**Comment by Pilchie** [comment] 2016-03-02 16:01
Dupe of #9392

**Closed by Pilchie** 2016-03-02 16:01 UTC
Labels: Bug
