### ISSUE TITLE
FailFast due to NullReferenceException when GetCompilationAsync returns null from an F# project

### ISSUE THREAD

**Issue by dsyme** [dotnet/roslyn#21719] opened 2017-08-24 17:00 UTC
**Description**: 

See https://github.com/Microsoft/visualfsharp/pull/3499#issuecomment-324688765

``GetCompilationAsync`` returns ``null`` for F# projects.  All calls to ``GetCompilationAsync`` need to be checked throughout the Roslyn codebase to make sure we are guarding against the possiblity of a ``null`` return.

**Version Used**: master

**Steps to Reproduce**:

1. Get https://github.com/dsyme/visualfsharp/commit/c107a1645fffdbad0af01fe040a55d59fbdc6200 
2. ``build vs debug``
3.  open VisualFSharp.sln
3. compile & launch
3. open VisualFSharp.sln in the launched VS using the new bits
3. Turn off ``Options --> Text Editor --> F# --> Performance --> In-memory project references``
3. exit
3. compile & launch
3. open ``vsintegration\src\FSharp.ProjectSystem.Base\Project\ProjectOptions.cs``
3. Go to a symbol with the caret

**Expected Behavior**:

all ok

**Actual Behavior**:

FailFast exception due to a NulLReferenceException at [this line](https://github.com/dotnet/roslyn/blob/aeeec402a2f223580f36c298bbd9d92ffc94b330/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentProjectsFinder.cs#L320)

**Comment by dsyme** [comment] 2017-08-24 17:05
Two comments

- Please, can we avoid the use of FailFast in cases like this?  We don't mind if a C# editor feature degrades when something goes slightly wrong via F# project references

- There are [a huge number of calls to GetCompilationAsync in Roslyn, 354 of them....](https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=GetCompilationAsync&type=)  Perhaps we can find a way to make it a stub implementation for F# projects, though I fear there are too many internals to do this....

**Comment by CyrusNajmabadi** [comment] 2017-08-25 19:49
Fixed with https://github.com/dotnet/roslyn/pull/21721

**Closed by CyrusNajmabadi** 2017-08-25 19:50 UTC
Labels: Area-IDE

**Comment by CyrusNajmabadi** [comment] 2017-08-25 19:53
> We don't mind if a C# editor feature degrades when something goes slightly wrong via F# project references

A core problem is that we do not know what the issue was that caused the problem.  Being 'resilient' or 'gently degrading' is something we've tried in the past with terrible results.  What tends to happen is that moments later VS ends up hard crashing due to some down-the-line issue, and we're left scratching our heads wondering what on earth was the root cause.  

The project system has been an enormous source of headaches for that exact reason over hte years.  

> There are a huge number of calls to GetCompilationAsync in Roslyn, 354 of them.... Perhaps we can find a way to make it a stub implementation for F# projects, though I fear there are too many internals to do this....

Roslyn is already highly robust here as TS/JS do not support this API, and we have to be resilient to them.  We're just now hitting a few missed cases due to F# having more functionality than TS/JS (i.e. supporting actual P2P refs with C# projects).  We'll certainly have a few bugs to shake out there no matter what.  With some paired work between the teams i'm certain we can get things in good workign order shortly.  I know the IDE team would be happy to work with @brettfo on just iterating rapidly here to squash out all the remaining issues.

**Comment by dsyme** [comment] 2017-09-01 23:17
@CyrusNajmabadi Thanks!  That all makes sense - though I do wish there was another way besides FailFast (e.g. "Send dump to Microsoft and continue work, disabling this message for rest of session")

**Comment by tmat** [comment] 2017-09-01 23:23
@dsyme There is -- Non-Fatal Watson report. We use it pretty extensively: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/InternalUtilities/FatalError.cs,86d34e79b41227cb,references

**Comment by dsyme** [comment] 2017-09-01 23:30
@tmat Lovely.  Your mission, if you choose to accept it, is to replace all FailFast with that, pleeeeease :)

**Comment by tmat** [comment] 2017-09-01 23:33
@dsyme I wouldn't say all of them can be replaced. We need to know that we can recover at the point. If some state might be corrupted then it's better to just crash. In many places we work with immutable objects so we can just throw away any calculated state and recover easily. Not not everywhere. In general, I think any code that cancellable is also likely (or should be) recoverable from an unexpected exception, as it already needs to handle cancellation exceptions.
