### ISSUE TITLE
No Code Styles can be changed in the Visual Studio Options dialog

### ISSUE THREAD

**Issue by walterlv** [dotnet/roslyn#44741] opened 2020-06-01 05:24 UTC
**Version Used**: 

Visual Studio: 16.6.0

**Steps to Reproduce**:

Please open visual studio and go to `Tools` -> `Options` -> `Text Editor` -> `C#` -> `Code Style` -> `General`. We'll talk about the settings of all the coding styles.

1. Change any of the code styles, e.g. the preference and the severity.
2. You'll see that any changed settings are surrounded by a red adorner.
3. Click OK to save and close this dialog.

![the Code Style dialog](https://user-images.githubusercontent.com/9959623/83378424-3e988580-a40b-11ea-9c22-c0690ac85853.png)

**Expected Behavior**:

We expect that the coding styles take effect. But...

**Actual Behavior**:

1. All the coding styles don't work as if they have not been set before.
2. Open the dialog again and you'll find that all the settings we have just changed are lost.

**See Also**

Do all the above again and restart Visual Studio, you'll see that the changes are still lost and can never be back. This is the main difference to this issue: https://github.com/dotnet/roslyn/issues/37484 .

I've also reported this issue to the @vsfeedback system because I don't know whether if it is a Visual Studio bug or a Roslyn bug. See here: <https://developercommunity.visualstudio.com/content/problem/1058097/no-code-styles-can-be-changed-in-the-visual-studio.html>

**Comment by sharwell** [comment] 2020-06-01 14:34
Duplicate of #43812

**Closed by sharwell** 2020-06-01 14:34 UTC
