### ISSUE TITLE
Can't bang away warning when nullability of constraint type doesn't match 

### ISSUE THREAD

**Issue by safern** [dotnet/roslyn#36510] opened 2019-06-17 18:06 UTC
```cs
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

#nullable enable

public class C {
    public int FooMethodIComparer<T, TComparer>(T value, TComparer comparer) where TComparer : IComparer<T>?
    {
        if (comparer == null)
        {
            return FooMethodIComparable(value, new Foo<T, Comparer<T>>(value, Comparer<T>.Default));
        }
        
        // warning CS8631: The type 'TComparer' cannot be used as type parameter 'TComparer' in 
        // the generic type or method 'Foo<T, TComparer>'. Nullability of type argument 
        // 'TComparer' doesn't match constraint type 'System.Collections.Generic.IComparer<T>'.
        return FooMethodIComparable(value, new Foo<T, TComparer>(value, comparer));
    }
    
    public int FooMethodIComparable<T, TComparable>(T value, TComparable comparable) where TComparable : IComparable<T>
    {
        
        return comparable.CompareTo(value);
    }
}

public class Foo<T, TComparer> : IComparable<T> where TComparer : IComparer<T>
{
	private readonly T _value;
    private readonly TComparer _comparer;
    
    public Foo(T value, TComparer comparer)
    {
    	_value = value;
        _comparer = comparer;
    }

    public int CompareTo(T other) => _comparer.Compare(_value, other);
}
```

I think people should be allowed to bang this warning away on the generic type use

 ```cs
return FooMethodIComparable(value, new Foo<T, TComparer!>(value, comparer));
```

Gives a syntax error. So this forces me to either use a pragma warning disable, or make my class `Foo<T, TComparer>` to accept an `IComparer<T>?` and then bang away the call to `_comparer!.Compare(_value, other)` because I know `_comparer` will not be null.

Also, when I'm creating the instance of this class, the compiler can identify that `TComparer` is will not be null at the callsite because I'm doing a null check on it:
```cs
if (comparer == null)
{
    return FooMethodIComparable(value, new Foo<T, Comparer<T>>(value, Comparer<T>.Default));
}

return FooMethodIComparable(value, new Foo<T, TComparer>(value, comparer));
```

[Repro can be found here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMAWAblwOIwDoAlAVwDsYBLMOWgYQHswADmwA2iAMqIAbmwDGcKJRy4AxM0bDhEYKMJxmW0bioBmYmkLdCAb1yE7xU21aEAYr14BZODAAWvACYAknyCEAiIADwAKgA0hFEhAmGIAHwAFFGEkhDCjHBxCfxJ4QiEMkXJCACUhADuPohw8YmVhCCEwRUl0SkA/Lb2Njj2I4RsAGaEaeWhJYQAvPOEahpVA6PW6xv2KADsru5evgGdswZwadm5+ctwtQe80XEt3VEp6Vd5z12Rb7QAInBxhB1DAqlVFNtCABfLYjOE7fZuTzePxBF7nS45L63e7Ip7NH4ID7Ym4zYqIcGQ+yw4b2LYoRzOZFHNGnYrnAmFM7aODpTKfG7cjm8spdc41eqNQk8nTtdlhTlvLZDKEIux7MWyrgvOBRXhY64Qra02kmMwPLm64ltDoY3k9OoNcIyimleXWnq4IYASAECDY2XghHCEH8vGYwgAnvFCAB9QXUuz+wMQYOh8ORmPC1px8mVJOEBmmZEZLKkgrWrVutZ0uyq+w+hOkhbl66FkZ5omt/MlQtmusOMbOXX6su8XyUhYpeO9xA8H5pZvXOIT53GnDQoA===)

So maybe the warning on `FooMethodIComparable(value, new Foo<T, TComparer>` should never be produced?

cc: @dotnet/nullablefc @cston

**Comment by jaredpar** [comment] 2021-02-10 00:55
Closing as this behavior is currently "By Design". The null forgiving operator today is only allowed in an expression context, not in a type context. Not opposed to this but we'd need to make this a language change proposal on dotnet/csharplang.

**Closed by jaredpar** 2021-02-10 00:55 UTC
Labels: Area-Compilers, Area-Language Design, Feature Request, New Language Feature - Nullable Reference Types
