### ISSUE TITLE
VsCrash when trying to create . EditorConfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59112] opened 2022-01-27 18:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VsCrash-when-trying-to-create-EditorCon/1632224)._

---
I don'T know how to reproducte it.
before it crashed, my installation (Windows 10 AND VS2022) were in French, 
then I changed the VS2022 language studio in English and I restarted VS2022.
then I tried to create a . EditorConfig. then I got thoses message, I'm sending the error and the log file.

---
#### Feedback Bot on 1/9/2022, 07:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/10/2022, 10:13 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:59
duplicate of https://github.com/dotnet/roslyn/issues/58611

**Closed by jmarolf** 2022-03-18 21:59 UTC
Labels: Area-Analyzers, Tenet-Reliability, Feature - Editor Config UI
