### ISSUE TITLE
Infinite loop when parsing a method body and possible throw exceptions

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#11724] opened 2016-06-02 20:33 UTC
**Branch**: future

**Steps to Reproduce**:

1. Set the following C# code in an editor:

``` C#
class C
{
    int M()
    {
        var i = M$$
        throw new System.Exception();
    }
}
```

2. Where `$$` represents the cursor's current location, type `(`.

**Actual Behavior**:
Eventual OOM coming from [`LanguageParser.cs`](https://github.com/dotnet/roslyn/blob/future/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L9385-L9401) lines 9385-9401.  In short, `this.CurrentToken.Kind` is `ThrowKeyword` which causes the second branch of the `if` statement to evaluate to `true` (via `IsPossibleArgumentExpression()` but no token was consumed so `list` keeps getting missing commas and missing argument expressions added.

**Comment by Pilchie** [comment] 2016-06-02 22:14
Tag @jaredpar

**Comment by gafter** [comment] 2016-06-03 19:51
@agocke This is probably residue from the "throw expression" implementation, which is your feature.

**Comment by mavasani** [comment] 2016-07-12 23:19
This looks like a dupe of https://github.com/dotnet/roslyn/issues/12197

**Comment by gafter** [comment] 2016-07-12 23:47
@mavasani Yes, it is, although technically that bug is a dup of this one.

**Closed by gafter** 2016-07-12 23:47 UTC
Labels: Area-Compilers, Bug, Language-C#, Tenet-Reliability
