### ISSUE TITLE
"Format document" no longer removes unused using directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35559] opened 2019-05-07 17:57 UTC
VSF_TYPE_MARKDOWNIn the previous version of Visual Studio, &quot;Format document&quot; (or CTRL+E, D) would format the code and also remove unnecessary using directives. 

In VS2019 the unnecessary using directives are no longer being removed.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/550620/format-document-no-longer-removes-unused-using-dir.html
VSTS ticketId: 858086_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 10:56 PM (7 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-05-14 21:43
Duplicate of #34751

**Comment by sharwell** [comment] 2019-05-14 21:43
This feature was replaced with a Code Cleanup feature for 2019. See https://github.com/dotnet/roslyn/issues/34751#issuecomment-480934321.

**Closed by jinujoseph** 2019-05-14 21:43 UTC
Labels: Area-IDE, Resolution-Duplicate
