### ISSUE TITLE
[Possibly Missing Specification?] XML-Documentation of "delegate*<>" method parameters produces Warnings

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#60135] opened 2022-03-12 10:52 UTC
### Version Used:
- C# Tools   `4.2.0-1.22108.11+a29b6ae89a8885856e4c55a0e92ba056e1530458` (a29b6ae89a8885856e4c55a0e92ba056e1530458)
- .NET SDK `6.0.200`
- VisualStudio.17.Preview/`17.2.0-pre.1.0+32210.308`
  **HOWEVER, this is also reproducible on sharplab.io**

### Steps to Reproduce:
```csharp
/* L01 */ static unsafe class C
/* L02 */ {
/* L03 */     static void M<T>(delegate*<T> ptr) { }
/* L04 */ 
/* L05 */     static void M(delegate*<void> ptr) { }
/* L07 */ 
/* L08 */     /// <inheritdoc cref="C.M{T}(delegate*{T})"/>
/* L09 */     static void M() { }
/* L10 */ }
```
[Also available on sharplab.io](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABAjANgAIBXAOwGcBDOCQ7AJkIGEBYAKAG93Ce6C6ALIQCyAHgAqAPgAUKCABsIAc0rAIAKgmTCAB2BQAlIQ6EAvt14WeeItiHDZC5ao2i72vYeNmrhXwHpAwlEYUgALaBhgFAB7AGNCOKgIOABeACImADphDnFTR0UVNXU80wN0/0lfG0ERaSMTczZTIA=)

### Expected Behavior:
Error- and warning-free compilation.

### Actual Behavior:
I receive the following warnings on line `8`:

> warning CS1584: XML comment has syntactically incorrect cref attribute 'C.M{T}(delegate*{T})'
> warning CS1658: ) expected. See also error CS1026.

This error occurs regardless on whether one writes
```csharp
/// <inheritdoc cref="C.M{T}(delegate*{T})"/>
```
or
```csharp
/// <inheritdoc cref="C.M(delegate*{void})"/>
```
This therefore does not seem to be an issue with the generic method type parameters or their usage inside the declaration of the parameter `ptr`.

----------------------
I am now wondering: Is this an issue inside the C# language specs or inside the Roslyn compiler?

**Comment by Unknown6656** [comment] 2022-03-12 10:53
I also opened a discussion on `csharplang` (https://github.com/dotnet/csharplang/discussions/5914) in order to facilitate the cross-repo discussion.

**Comment by svick** [comment] 2022-03-12 11:06
This is a duplicate of https://github.com/dotnet/roslyn/issues/50559, which in turn was closed as a duplicate of https://github.com/dotnet/roslyn/issues/48363.

**Closed by svick** 2022-03-12 11:06 UTC
Labels: Area-Compilers, untriaged

**Comment by Unknown6656** [comment] 2022-03-13 07:18
Thanks @svick! I have to admit, that I somehow have missed https://github.com/dotnet/roslyn/issues/48363.
