### ISSUE TITLE
Quick Action to replace auto property with fully implemented one

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#21159] opened 2017-07-27 05:41 UTC
**Version Used**: 2.3.2.61921

**Steps to Reproduce**:
Invoke quick actions on
```C#
public string Foo { get; private set; }
```

**Actual Behavior**: Replace 'Foo' with methods. I don't remember ever needing that one.

**Expected Behavior**: A quick action to change the code into
```C#
private string _foo;
public string Foo
{
    get { return _foo; } 
    private set { _foo = value; } 
}
```
subject to formatting settings.

(I'm somehow convinced this has been discussed here before but cannot find the issue.)

**Comment by CyrusNajmabadi** [comment] 2017-07-27 06:57
@chborl is working on that here: https://github.com/chborl/roslyn/tree/refactorfieldtofullproperty

**Comment by Pilchie** [comment] 2017-07-27 21:19
Duplicate of #18267.

**Closed** 2017-07-27 23:47 UTC
Labels: Area-IDE, Feature Request
