### ISSUE TITLE
[request] Ability to sort CompletionItem by type inheritance

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#16685] opened 2017-01-23 07:43 UTC
Just like monodevelop feature. I think it useful when we have large class with many inheritance like unity3D's MonoBehaviour. We should have a way to switch between sorting mode

And, if possible, should be like monodevelop that could always switch anytimes

**Comment by Pilchie** [comment] 2017-02-07 00:06
We have so far resisted allowing sorting by anything other than alphabetical, but I definitely understand wanting to see things from a particular layer in the hierarchy.

Tagging @kuhlenh @rchande @CyrusNajmabadi for thoughts here.

**Comment by Thaina** [comment] 2017-02-07 01:12
@Pilchie  I was investigate myself and it seem it should be done on roslyn derivative for IDE, such as omnisharp. roslyn should be as is

But the problem I found is, It seem like CompletionItem return from roslyn does not contains type that item came from. So I can't sort it in omnisharp (I try to made pull request on omnisharp)

So, is there a type, or at least typename that I could do reflection easier that came along with CompletionItem? If it not exist could it possible to add it into roslyn?

**Comment by Thaina** [comment] 2017-02-08 02:00
@DustinCampbell I mean the ability to sort completion should not be implemented in roslyn directly. Instead we should get completion list unsorted and sort it or manipulate it in the host process

Ability to manipulate collection should be independent to collection in my opinion

**Comment by DustinCampbell** [comment] 2017-02-08 02:05
@Thaina: I don't think that's feasible. The data that comes back for the `CompletionService` wouldn't have enough information to sort in such a manner. Adding a type name is possible but following up with reflection on those type names would be extremely expensive.

In general, we try to avoid forcing hosts to do that level of sorting because it is error prone. If we want to unify the core C# editing experience across many hosts, we need to take burden off the hosts, not add it.

**Comment by Thaina** [comment] 2017-02-08 02:11
@DustinCampbell If so then, that why I was request that CompletionItem return from roslyn should add more information, but let omnisharp manipulate that collection

Also the `host` I mean is omnisharp.exe, not omnisharp-vscode. So omnisharp.exe would be able to provided across all omnisharp-xxx am I right?

I think CompletionService should return CompletionItem with TypeInfo. Then omnisharp has config to sort it, then return to omnisharp-vscode or other host request it

**Comment by Thaina** [comment] 2017-02-08 02:13
ps. Also this feature is what I talk about there >>> https://github.com/dotnet/roslyn/issues/15974#issuecomment-277447347

**Comment by DustinCampbell** [comment] 2017-02-08 02:19
When we say "host", we mean anything hosting a Roslyn workspace. That includes OmniSharp, Visual Studio, Visual Studio for Mac, and many others. That "host" could do many things, such as populate editor presentation APIs (such as in Visual Studio), or service up language service information over a protocol like OmniSharp.

Note: I think you're getting a little bogged down by implementation. Why would CompleitionSerivce return a CompletionItem with TypeInfo? There's no need to use reflection here. Remember that this is *Roslyn*, which already has a rich symbol API for representing types, methods and any other symbols handled by the C# language.

**Comment by Thaina** [comment] 2017-02-08 03:10
@DustinCampbell I wish roslyn would return typeinfo with CompletionItem so omnisharp (and other host) would be able to group/sort/hidden or make any decision on its own. In this case is sorting and grouping by its declaration type

As I said, I think list in general should be able to sort by custom logic anytimes. Should not implement fixed sorting logic on its own. But should provide information for outside logic instead

**Comment by xCyborg** [comment] 2019-03-29 12:22
I hope someone is on this

**Comment by genlu** [comment] 2024-12-11 19:19
This is a duplicate of https://github.com/dotnet/roslyn/issues/19256

**Closed by genlu** 2024-12-11 19:19 UTC
Labels: Area-IDE, Feature Request
