### ISSUE TITLE
Spurious rename conflict

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#995] opened 2015-03-03 21:43 UTC
Invoke Rename (don't actually need to change name) on the first "nextAction" reference (not definition).  Three unresolvable conflicts are reported, some in other methods.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication84
{
    class Program
    {
        static void Main(string[] args)
        {
        }

        internal delegate void SuccessCompletionRoutine(DkmEvaluationResult result);
        internal delegate void ExceptionCompletionRoutine(Exception exception);

        private void StoreResultAndContinue(DkmEvaluationResult result, ArrayBuilder<EvalResultDataItem> rows, DkmEvaluationResult[] results, int index, int numRows, WorkList workList, DkmInspectionContext inspectionContext, DkmStackWalkFrame stackFrame, Action nextAction)
        {
            results[index] = result;
            index++;
            if (index < numRows)
            {
                workList.ContinueWith(() => GetEvaluationResultsAndContinue(rows, results, index, numRows, workList, inspectionContext, stackFrame, nextAction)); // Invoke Rename on "nextAction"
            }
            else
            {
                nextAction();
            }
        }

        private void GetEvaluationResultsAndContinue(ArrayBuilder<EvalResultDataItem> rows, DkmEvaluationResult[] results, int index, int numRows, WorkList workList, DkmInspectionContext inspectionContext, DkmStackWalkFrame stackFrame, Action nextAction)
        {
            if (index >= numRows)
            {
                nextAction();
            }
            else
            {
                CreateEvaluationResultAndContinue(rows[index], workList, inspectionContext, stackFrame,
                    result => ContinueWithExceptionHandling(
                        () => StoreResultAndContinue(result, rows, results, index, numRows, workList, inspectionContext, stackFrame, nextAction),
                        e =>
                        {
                            // If we fail to store a result, just stop enumerating rows (rather than attempting to store
                            // an error message in the current row, etc).  This is because it may have been the act of
                            // indexing into the results store that threw (so it would just throw again here).  The user
                            // experience is less than ideal (there's no real indication that something went wrong),
                            // however, it seems like it's better to enumerate/display some rows than none.  We will
                            // receive a non-fatal Watson report in this case, so the problem won't go unnoticed.
                            nextAction();
                        }));
            }
        }

        private static void ContinueWithExceptionHandling(Action action, ExceptionCompletionRoutine exceptionCompletionRoutine)
        {
            try
            {
                action();
            }
            catch (Exception e)
            {
                exceptionCompletionRoutine(e);
            }
        }

        private void CreateEvaluationResultAndContinue(EvalResultDataItem dataItem, WorkList workList, DkmInspectionContext inspectionContext, DkmStackWalkFrame stackFrame, SuccessCompletionRoutine successCompletionRoutine)
        {
        }

        private class ArrayBuilder<T>
        {
            public EvalResultDataItem this[int x]
            {
                get
                {
                    return null;
                }
            }
        }

        private class EvalResultDataItem
        {
        }

        private class WorkList
        {
            internal void ContinueWith(Action a)
            {
                throw new NotImplementedException();
            }
        }

        private class DkmInspectionContext
        {
        }

        private class DkmStackWalkFrame
        {
        }
    }

    internal class DkmEvaluationResult
    {
    }
}

```

**Comment by amcasey** [comment] 2015-03-03 21:44
FYI @dpoeschl

**Comment by Pilchie** [comment] 2015-03-04 15:47
I wonder if this is the same underlying issue as http://roslyn.codeplex.com/workitem/181?

Tag @slaks

**Comment by amcasey** [comment] 2015-03-04 17:42
@Pilchie Possibly.  It definitely seems important that the parameter is captured by a lambda.  I'd also like to note that my repro is reduced from real Roslyn code.

**Comment by Pilchie** [comment] 2015-03-04 17:49
@amcasey I saw that, which is why I kept this one active :smile:.  If there are real cases where this is happening, we should investigate.

**Comment by SLaks** [comment] 2015-03-06 00:59
I'm not sure how related this is to my earlier issue.

I don't think I've _ever_ seen Rename show unresolvable conflicts with the original name ;)

**Comment by dpoeschl** [comment] 2015-04-20 16:10
Closing as duplicate of #1729 which is simpler and has a nice screenshot.

**Closed** 2015-04-20 16:10 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
