### ISSUE TITLE
Suppress in source as an attribute should be one option

### ISSUE THREAD

**Issue by RobSiklos** [dotnet/roslyn#33724] opened 2019-02-27 20:52 UTC
Porting from https://github.com/dotnet/roslyn-analyzers/issues/1902, as suggested in https://developercommunity.visualstudio.com/content/problem/471804/suppress-in-source-option-for-suppressing-errors-a-1.html

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
#### Package Version

v2.6.3
#### Diagnostic ID

All code analysis rules.
#### Repro steps

    1. Create a project which violates some CA rule.

    2. Compile.

    3. Use quick action "Suppress > In Source..."

    4. Notice that it uses `#pragma disable … #pragma enable` pair.

#### Expected behavior

I would expect that "suppress in source..." would insert `[SuppressMessage]` attribute, same as "suppress in suppression file" does. `[SuppressMessage]` attribute can be placed on members, too, like this:

[SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "")]

At least, it should be an option:

    * Suppress > In source as a #pragma directive...

    * Suppress > In source as an attribute...

    * Suppress > In suppression file...

**Comment by RobSiklos** [comment] 2019-02-27 20:55
I would actually prefer that (where possible), the attribute be used rather than the pragma. Pragma makes the code look so ugly, and also can't enforce a justification like the attribute can.

**Comment by mavasani** [comment] 2019-02-27 20:55
Also pasting the comment from the original issue:

_This was considered during the initial implementation of the suppression code fix provider. However, it was felt that this was adding too many alternatives to do the same operation. It was decided that we will provide one fix to suppress "inline" in source using pragmas (which would also be applicable to compiler diagnostics) and one fix to suppress in source adding suppress message attributes to a global suppressions file that does not pollute the current source file. As a workaround for local suppress message attribute suppression, which is uncommon, user can generate the global one, then cut and paste the generated attribute to the desired symbol and remove the `Target` and `Scope` strings in the attribute._

We have a workaround which was considered acceptable at the time of implementation, given the less frequent usage of locally applied suppress message attribute. This issue tracks adding a supported code fix for it

**Comment by RobSiklos** [comment] 2019-02-27 21:01
@mavasani I would question the statement that using local suppress message attribute suppression is uncommon. After so many years of it being the default behaviour in VS when locally suppressing a CA warning, I'm sure that plenty of projects (Roslyn included) have this.

**Comment by sharwell** [comment] 2019-02-28 18:40
Duplicate of #17218

**Closed by sharwell** 2019-02-28 18:40 UTC
