### ISSUE TITLE
IBCMerge sporatically fails

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12636] opened 2016-07-20 18:51 UTC
PR: [#1180](https://github.com/dotnet/roslyn-internal/pull/1180) *Revert previous integration change now that open side has gone through.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_prtest/385/

**Issue 1: MSBuild Error**
error MSB3073: The command ""d:\j\workspace\windows_vsi_p---9267604d\Closed\Tools\ibcmerge\IBCMerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p---9267604d\Open\Binaries\Obj\EditorFeatures\Release\Microsoft.CodeAnalysis.EditorFeatures.dll" -incremental "C:\Users\dotnet-bot\.nuget\packages\RoslynDependencies.OptimizationData\1.3.0-beta5-60518-02\content\OptimizationData\Microsoft.CodeAnalysis.EditorFeatures.pgo"" exited with code -1. [d:\j\workspace\windows_vsi_p---9267604d\Open\src\EditorFeatures\Core\ep3fwyrh.tmp_proj]

**Comment by mavasani** [comment] 2016-07-20 23:16
Hit this in couple of vsi runs:
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/292/

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/296/

Marking this Urgency-Now

**Comment by mavasani** [comment] 2016-07-20 23:33
And both retest attempts also failed:

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/294/

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/298/

**Comment by mavasani** [comment] 2016-07-20 23:35
Tagging @KevinH-MS as this seems same as https://github.com/dotnet/roslyn/issues/11868

**Comment by jasonmalinowski** [comment] 2016-07-22 16:59
This is also failing internal signed builds as well.

**Comment by mavasani** [comment] 2016-07-25 16:46
Failed again:
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit32_prtest/362/

**Comment by KevinH-MS** [comment] 2016-07-25 17:03
@tannergooding the new (debug) version of ibcmerge is checked in, right?

**Comment by tannergooding** [comment] 2016-07-25 17:10
Yes

**Comment by KevinH-MS** [comment] 2016-07-25 17:12
Okay, I will start syncing the sources to see if we can figure out what's going wrong now...

**Comment by KevinH-MS** [comment] 2016-07-25 17:14
Actually, I take that back.  What I'm going to do is just disable ibcmerge for PR builds.  It only matters for signed builds.

**Comment by KevinH-MS** [comment] 2016-07-25 17:20
Can you point me to that failure so I can compare?  Thanks

**Comment by tannergooding** [comment] 2016-07-25 17:49
@jasonmalinowski knows which build, although it may have since been deleted.

**Comment by mavasani** [comment] 2016-08-05 23:29
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_unit64_prtest/423/

I have actually seen this failure bunch of times in the PRs over the last week. @KevinH-MS any updates on this?

**Comment by KevinH-MS** [comment] 2016-08-08 18:01
I still haven't seen a link to a failure in a signed build, so I'll just go ahead and do what I said (disable this for PR builds to mitigate the issue).

**Closed** 2016-08-08 18:52 UTC
Labels: Area-Infrastructure, Bug, Contributor Pain, Urgency-Now

**Comment by jasonmalinowski** [comment] 2016-08-09 16:47
@KevinH-MS: @tannergooding said he saw this failing in signed builds, so this feels like a workaround instead of a fix for me. In any case, do we still understand the root cause here? Are we still pursuing a long-term fix for the issue?

**Comment by tannergooding** [comment] 2016-08-09 17:06
@jasonmalinowski, I only said it failed in a signed build because I was told by you (in Slack) that it had failed there.
