### ISSUE TITLE
Generic parameter constrained to implement true, false, &, |, operators in separate interfaces still generates CS0217 or CS0218 error

### ISSUE THREAD

**Issue by Charlieface** [dotnet/roslyn#74000] opened 2024-06-14 10:27 UTC
**Version Used**:
Compiler version: '4.6.0-3.23259.8 (c3cc1d0c)'. Language version: latest (11.0).

**Steps to Reproduce**:

1. Create an interface that implements the `true` and `false` operators
```cs
public interface ITruthOperators<TSelf>
    where TSelf : ITruthOperators<TSelf>
{
    static abstract bool operator true(TSelf value);

    static abstract bool operator false(TSelf value);
		
    static abstract TSelf operator !(TSelf value);

    static abstract TSelf TruthyIdentity { get; }

    static abstract TSelf FalseyIdentity { get; }
}
```
2. Create a _separate_ interface that implements the `&` and `|` operators. `System.Numerics.IBitwiseOperators` can also be used for this.

3. Create a generic function, where the type parameter is constrained `T : ITruthOperators<T>, IBitwiseOperators<T, T, T>`
```cs
public T IsTrue<T>(T left, T right) where T : ITruthOperators<T>, IBitwiseOperators<T, T, T>
{
    return left && right;
}
```
[**SharpLab repro**](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABAJgEZiSAGLEigOgDk4BbDAJwEsBjAZwDcxAJBix1AMz0y9CgHZiAb1HkyolUTEMAnAAoARAAkMSAPZYA6mc4JgBgJTCtAX1GrpAFSwBJfp844DAAeTwA+PW9MADMAFwAaLG8eAHMAC1iHLAB3NK5sbxBfALhYtIB5AAcuZFibflCwxJ8AIW5Y7O5+DCqaus4Gz0ShpLCNURESeSwY2KwAMnmsVIznETctDyTff0CMMkbImYw44eXudMycvM4CrCKfErLezlr6g/DxoiwfrEnp2YLJYrWJrDbEX70Lw7EoYSSHKInBLbEFZXL5bYPJ4VaqvfqDJq+NodLo9XFvAYfMZaTSQ/7HOJA86XMHuLQkaF+WEAFgRDORyQuGTRNzuWMCz3J+PhnxpEN+9MBi2Zq1EG3BpGk3BgsS40WQvGwjwlOL69VCAGVTNFqSJ0bcklaENF7sUTS8KYMnTblKoKAA2LBofixV68OaoMxmBBYMxSmxYUNBSLerAAN2QCCCTmIfsDwdDBojUZjcbNnCw+oQ3RT1vTmezaxEeaDqBDYbmnlTZbxCYAhLXnfWsxgc0QWwWO4669iAJ4+YC4WLtWdYJRYFIYUFYDWTAOt9tF6dDgBime688XOpXa43W8EO+IGo5WG1us4+sNbtKpt7lMt1phK6rTtJ03QeviAHOsM3owYBoj2gUqbij+EHvFBPpEJoe75m2hbhlgkbRrG8YVkmGCDi6GYjmOE54VORGlqRlbnhRXZ1tRjYTHRh4EexQ49hSWADvxVENqOzg8fhnapnOC5Lje66btuu4MLhvEyXWZ7Vhgl4KbEq5Kfej5EM+Wo6nqBpGsSYFkuW/AfN6tqIceLoPDZpJof+onUthakHtJrkkeWCyUfycFDqiknfL8/mTkeonBX+WAQGFswRS6UW5jFPxxfRCXdsxAB6aVIhlKqZNFkJ5RpQWCf0WAAH5hZxElPtlL5vpZX7GqhpH8DKTkIaKQUoZK9mDfBWFSQxJZJUJ5EteJtHsvu8UEYx80NVWNaJa1Y4SKt6mBYl9X9ktNHRThAVTolclXsuBm3spD6qWt+V8am2kXvJ15PUZKncUdN0FXWZ0VvMpWnEFWXjjlcjHbdhUhaliXpTDQqVdl1XvbVp3FVDAqprD8q5bjJ3I8lzV7ctzguEAA=)

**Expected Behavior**:

Compiles OK.

**Actual Behavior**:
```
CS0217: In order to be applicable as a short circuit operator a user-defined logical operator ('IBitwiseOperators<T, T, T>.operator &(T, T)') must have the same return type and parameter types
```
This is nonsensical and not to spec. [The language spec at 12.14.3](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12143-user-defined-conditional-logical-operators) states:
> When the operands of `&&` or `||` are of types that declare an applicable user-defined operator `&` or operator `|`, both of the following shall be true, where `T` is the type in which the selected operator is declared:
>
> *   The return type and the type of each parameter of the selected operator shall be `T`. In other words, the operator shall compute the logical AND or the logical OR of two operands of type `T`, and shall return a result of type `T`.
> *   `T` shall contain declarations of operator true and operator false.
>
> A binding-time error occurs if either of these requirements is not satisfied. Otherwise, the `&&` or `||` operation is evaluated by combining the user-defined operator true or operator false with the selected user-defined operator:
> _etc_

The type that is relevant here is the generic parameter `T`, not `IBitwiseOperators` itself. The compiler appears to be lifting the interface constraint out incorrectly as the actual type, in order to verify the binding in the spec.
____
**Further attempts**:

1. Basing `ITruthOperators<TSelf>` off `IBitwiseOperators<TSelf, TSelf, TSelf>` doesn't help, even though interface inheritance means the inherited methods are part of the derived interface. This indicates the compiler is doing a `BindingFlags.DeclaredOnly`-style check, to no apparent reason.
```cs
public interface ITruthOperators2<TSelf> : IBitwiseOperators<TSelf, TSelf, TSelf>
    where TSelf : ITruthOperators2<TSelf>
```
```cs
public T IsTrue2<T>(T left, T right) where T : ITruthOperators2<T>
```
Reversing that so it became `IBitwiseOperators2 : ITruthOperators` also doesn't help.

2. Reimplementing `IBitwiseOperators` with a single generic parameter also doesn't help. This indicates this is not a confusion of the three different type parameters of `IBitwiseOperators` itself. (This would have been incorrect if so, as it's reified as `IBitwiseOperators<T, T, T>` and therefore all the parameters and the return type are the same).
```cs
public interface IBitwiseOperators2<TSelf>
    where TSelf : IBitwiseOperators2<TSelf>
{
    static abstract TSelf operator &(TSelf left, TSelf right);

    static abstract TSelf operator |(TSelf left, TSelf right);

    static abstract TSelf operator ^(TSelf left, TSelf right);

    static abstract TSelf operator ~(TSelf value);
}
```
```cs
public T IsTrue3<T>(T left, T right) where T : ITruthOperators<T>, IBitwiseOperators2<T>
```
It gets a completely different error, also nonsensical:
```
CS0218: In order for 'IBitwiseOperators2<T>.operator &(T, T)' to be applicable as a short circuit operator, its declaring type 'IBitwiseOperators2<T>' must define operator true and operator false
```

3. **The only thing that worked** was to place both `&`, `|` operators **and** the `true`, `false` operators in the same interface declaration:
```cs
public interface ITruthOperators3<TSelf>
    where TSelf : ITruthOperators3<TSelf>
{
    static abstract bool operator true(TSelf value);

    static abstract bool operator false(TSelf value);
		
    static abstract TSelf operator !(TSelf value);

    static abstract TSelf TruthyIdentity { get; }

    static abstract TSelf FalseyIdentity { get; }
		
    static abstract TSelf operator &(TSelf left, TSelf right);

    static abstract TSelf operator |(TSelf left, TSelf right);

    static abstract TSelf operator ^(TSelf left, TSelf right);

    static abstract TSelf operator ~(TSelf value);
}
```
```cs
public T IsTrue4<T>(T left, T right) where T : ITruthOperators3<T>
```
____
Relevant [Github issue](https://github.com/dotnet/runtime/issues/103141#issuecomment-2156213529), proposing `System.Numerics.ITruthOperators`. This bug appears to be a blocking issue sans the above final workaround which is not ideal.

**Comment by jaredpar** [comment] 2024-06-14 16:49
Going to rewrite this sample to use `U` to make it less confusing when comparing to the word in the language specification

```csharp
public U IsTrue<U>(U left, U right) where U : ITruthOperators<U>, IBitwiseOperators<U, U, U>
{
    return left && right;
}
```

Going to the spec discussion

> This is nonsensical and not to spec. [The language spec at 12.14.3](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12143-user-defined-conditional-logical-operators) states:

>> When the operands of && or || are of types that declare an applicable user-defined operator & or operator |, both of the following shall be true, where T is the type in which the selected operator is declared:

>> ...

> The type that is relevant here is the generic parameter T, not IBitwiseOperators itself. The compiler appears to be lifting the interface constraint out incorrectly as the actual type, in order to verify the binding in the spec.

Disagree. The `T` referred to in the spec is `IBitwiseOperators<...>` as that is where the operators `&/|` are _declared_. It is not `U`. This is why the code you provided errors about missing `true` and `false` operators: they are not declared where the language expects them. The compiler is behaving correctly here. 

There is one error in the sample I'm unclear on. Condensed it down to the following: 

```csharp
public class Program2
{
    public T IsTrue1<T>(T left, T right) where T : IExample1<T>
        => left && right;

    public T IsTrue2<T>(T left, T right) where T : IExample2<T, T>
        // error CS0217: In order to be applicable as a short circuit operator a user-defined logical 
        // operator ('IExample2<T, T>.operator &(T, T)') must have the same return type and parameter
        // types
        => left && right;
}

public interface IExample1<T>
	where T: IExample1<T>
{
    static abstract bool operator true(T value);
    static abstract bool operator false(T value);
    static abstract T operator &(T left, T right);
    static abstract T operator |(T left, T right);
}

public interface IExample2<T1, T2>
	where T1: IExample2<T1, T2>
{
    static abstract bool operator true(T1 value);
    static abstract bool operator false(T1 value);
    static abstract T2 operator &(T1 left, T2 right);
    static abstract T2 operator |(T1 left, T2 right);
}
```

Based on these two samples it _seems_ like the analysis is being done on the declared operators not on the specific instantiation. Unsure if that is by design or an issue of implementation. 

@AlekseyTs, @cston curious on your thoughts here.

**Comment by AlekseyTs** [comment] 2024-06-14 17:05
> Based on these two samples it seems like the analysis is being done on the declared operators not on the specific instantiation.

I think this is intentional, the declaration should use "a self constrained" type parameter as the return type of the operator in order to be able to use it in the context.

**Comment by jaredpar** [comment] 2024-06-14 17:07
Closing as "By Design" based on the analysis.

**Closed by jaredpar** 2024-06-14 17:07 UTC
Labels: Area-Compilers, untriaged

**Comment by jaredpar** [comment] 2024-06-14 17:33
> The actual presence of those interfaces is not really relevant to the discussion, 

Sorry but it is. The language and compiler define these operations in terms of how and where they are declared.

If you feel strongly about this you could propose a design on csharplang. At the moment though, the behavior here is in line with the language specification.

**Comment by AlekseyTs** [comment] 2024-06-14 18:29
Yes the overload resolution works the same way, but, when we are talking about a short-circuiting form,  there are extra requirement for the operators chosen. This is documented at https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/expressions.md#11133-user-defined-conditional-logical-operators:

>When the operands of `&&` or `||` are of types that declare an applicable user-defined `operator &` or `operator |`, both of the following shall be true, where `T` is the type in which the selected operator is declared:
>
>- The return type and the type of each parameter of the selected operator shall be `T`. In other words, the operator shall compute the logical AND or the logical OR of two operands of type `T`, and shall return a result of type `T`.
>- `T` shall contain declarations of `operator true` and `operator false`.
>
>A binding-time error occurs if either of these requirements is not satisfied.

For operators declared in interfaces the "shall be `T`" requirement is relaxed to include a "self-constraint" type parameter of the interface (in addition to the interface type itself).

**Comment by AlekseyTs** [comment] 2024-06-18 11:10
Unfortunately the proposal is incomplete, i.e. it doesn't capture all the decisions made during design discussions. We didn't do a good job of maintaining proposals as complete specifications at the time.

For conversion operators, for example, I see dedicated sections in the proposal describing when and how do conversions declared in interfaces get into the set of candidates. There are no similar sections for binary and unary operators. However, here is a comment that I found in source code in relation to both of them:

>            // From https://github.com/dotnet/csharplang/blob/main/meetings/2017/LDM-2017-06-27.md:
>            // - We only even look for operator implementations in interfaces if one of the operands has a type that is
>            // an interface or a type parameter with a non-empty effective base interface list.
>            // - We should look at operators from classes first, in order to avoid breaking changes.
>            // Only if there are no applicable user-defined operators from classes will we look in interfaces.
>            // If there aren't any there either, we go to built-ins.
>            // - If we find an applicable candidate in an interface, that candidate shadows all applicable operators in
>            // base interfaces: we stop looking.

I hope this helps.

**Comment by AlekseyTs** [comment] 2024-06-18 17:58
> although it only seems to be dealing with normal operators, not short-circuiting.

There are no special rules for resolving short-circuiting operators. The resolution happens against corresponding bit-wise operators using regular rules for binary operators and, if the resolution is successful, extra restrictions are applied to the result. An ability to declare operators in interfaces didn't change that. 

> I guess it depends whether you feel the compiler's current implementation necessarily reflects the proposal, or whether you feel the compiler's current implementation by definition is the design.

The proposal wasn't nearly as detailed to be able to ask the question. I feel that the implementation reflects the design as it evolved while we were working on the feature and reflects design decisions that were made.

> I would venture to say it doesn't meet the original intention, at least for short-circuiting operators, but who knows at this point?

You can certainly like or dislike the design, find it intuitive or not, etc. Saying that "it doesn't meet the original intention" is somethin different though. Unless, of course, you can provide a reference to the document that clearly states the intent in a form that is detailed enough to perform a comparison.

**Comment by AlekseyTs** [comment] 2024-06-19 14:14
> Well those extra restrictions involve another lookup for true and false operators, so it's an open question whether that lookup should be on the same type or whether overload resolution should start from scratch.

This isn't an open question. It was answered way before an ability to define operators in interfaces was introduced, which doesn't change anything in this regard. What happens and what operators are used is clearly specified at https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/expressions.md#11133-user-defined-conditional-logical-operators, in my opinion.

> I guess you'd just expect the code to reduce x && y; into something like x ? y : x and for x || y to reduce to x ? x : y (without recalculating x) which does indeed compile, and it's surprising that short-circuiting does not.

The reductions is not what you expect, its clearly specified at https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/expressions.md#11133-user-defined-conditional-logical-operators.

> So how can we ever report a compiler bug?

I do not see any problem with that. You don't have to be certain that a behavior is a bug before opening an issue. The issue is getting triaged/investigated and then team makes a determination how to classify the issue. If you are not satisfied with the result of the triage, you can, of course, push back. The best chance for that is to either quote an official spec for language or the feature, or quote an explicit LDM decision from notes and demonstrating that the behavior doesn't follow the design. An opinion what a proposal could say, but didn't say, isn't good enough, in my opinion. Especially in cases when we have clearly recorded design decisions made by LDM.

> what do I do now if I want to push this forward?

To push what forward?

If you want to propose different language rules, you can submit a proposal at https://github.com/dotnet/csharplang, the whole process and what to expect is described at https://github.com/dotnet/csharplang/blob/main/README.md.

If you want to revert the resolution for this issue, you need to provide a concrete proof that the behavior doesn't follow the design. Keep in mind, it is very common for the final design of a feature to be very far from the original proposal, even when proposal is detailed. Not to mention a situation, when the original proposal doesn't provide any details on the subject at all.

We looked at the reported issue with an open mind and determined that compiler behaves according to the feature design. According to the design decisions we have made during the feature development. The behavior is not an accident, which would constitute a bug.

**Comment by jaredpar** [comment] 2024-06-20 23:11
> If you want to propose different language rules, you can submit a proposal at https://github.com/dotnet/csharplang,

I want to reinforce this message. The compiler is operating according to the specified behavior today hence there is no bug here. 

If you do not find this behavior desirable and want a change, the path forward is submitting a proposal for changing how the language works. Then pushing it through the language change process to try and get approval on it.
