### ISSUE TITLE
API shape of IUsingStatement

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22625] opened 2017-10-09 23:54 UTC
right now, IUsingStatement's shape is this

```csharp
    /// <summary>
    /// Represents a C# using or VB Using statement.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IUsingStatement : IOperation
    {
        /// <summary>
        /// Body of the using, over which the resources of the using are maintained.
        /// </summary>
        IOperation Body { get; }
 
        /// <summary>
        /// Declaration introduced by the using statement. Null if the using statement does not declare any variables.
        /// </summary>
        IVariableDeclarationStatement Declaration { get; }
 
        /// <summary>
        /// Resource held by the using. Can be null if Declaration is not null.
        /// </summary>
        IOperation Value { get; }
    }
```

we have 2 design questions.

1. should Declaration use IVariableDeclarationStatement rather than IVariableDeclaration
2. should Declaration and Value be merged?

related to https://github.com/dotnet/roslyn/issues/22561 (https://github.com/dotnet/roslyn/pull/22435#issuecomment-334762937)

**Comment by heejaechang** [comment] 2017-10-09 23:58
since using statement can have multiple variable declarations such as below

```vb
Using c1 As C = New C, c2 As C = New C'BIND:"Using c1 As C = New C, c2 As C = New C"
            Console.WriteLine(c1)
        End Using
```
but IVariableDeclaration can't support 2 initializers, we don't have option but using IVariableDeclerationStatement unless we change shape of those APIs.

**Comment by 333fred** [comment] 2017-10-10 05:45
dupe of https://github.com/dotnet/roslyn/issues/22279.

**Closed by 333fred** 2017-10-10 05:45 UTC
Labels: Area-Analyzers, Discussion, New Feature - IOperation
