### ISSUE TITLE
Intellisense doesn't work on pointers in the context of parameters

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#58081] opened 2021-12-02 20:11 UTC
**Version Used**:

| Visual Studio | Compiler Version | Verdict |
|---------------|------------------|---------|
| 2022 Latest Preview (17.1.0p1.1) | '4.1.0-1.21551.6 (e4419d6f)'. Language version: 9.0 | Broken |
| 2022 Latest (17.0.2) | '4.0.1-1.21568.1 (6ab66011)'. Language version: 9.0 | Broken |
| 2019 Latest (16.11.7) | '3.11.0-4.21403.6 (ae1fff34)'. Language version: 9.0 | Broken |
| 2017 Latest (15.9.41) | '2.10.0.0 (b9fb1610)'. Language version: default | Works |

**Steps to Reproduce**:

1. Create a new class library and populate a file with the following code:

```csharp
public struct Test1
{
    public int X;
    public int Y => throw null;
    public void Method() => throw null;
}

public unsafe static class TestClass
{
    public static void TestMethod(Test1* a)
    {
        //a->
    }
}
```

2. Compile and observe code compiles successfully
3. Uncomment the line in `TestMethod` and attempt to query Intellisense after the `->` by pressing Ctrl+Space

**Expected Behavior**:

Intellisense offers suggestions for `X`, `Y`, `Method`, `GetHashCode`, etc. IE:

![image](https://user-images.githubusercontent.com/278957/144493695-ec3efa31-c152-4c98-95d1-6d6e4ddeb183.png)

**Actual Behavior**:

Nothing happens, no completion list appears.

Occasionally it will instead auto-complete to something nonsensical like in the screenshot below:

![image](https://user-images.githubusercontent.com/278957/144493544-7a4b7fb5-3429-49fd-98ff-20f877d1a22e.png)

--------------------------

Intellisense still works just fine for locals, fields, properties, and method return values. (As seen in the expected behavior screenshot.

Works fine in Visual Studio 2017. I'm almost certain it worked in 2019 at some point.

I just downloaded 2022 stable specifically to test this issue, so it's all default settings and no extensions. (Maybe worth noting: I did however remove all the optional components since I'm low on disk space.)

**Comment by PathogenDavid** [comment] 2022-01-28 19:21
I ended up finding some time to look into this myself, PR here: https://github.com/dotnet/roslyn/pull/59143

**Comment by sharwell** [comment] 2022-02-10 00:23
Duplicate of #54919

**Closed by sharwell** 2022-02-10 00:23 UTC
Labels: Bug, Area-IDE, IDE-IntelliSense, IntelliSense-Completion
