### ISSUE TITLE
After updating Roslyn from 1.3.2 to 2.0.0, SemanticModel.GetSymbolInfo or GetDeclaredSymbol for Primitive types returns NULL

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#18142] opened 2017-03-24 11:58 UTC
**Earlier Version Used**:
1.3.2
 
**Updated Version which is now getting Used**: 
2.0.0

**Steps to Reproduce**:

1. Environment used : **Visual Studios 2015 Community version**
2. When using **Roslyn version 1.3.2**, **SemanticModel.GetSymbolInfo** for a Primitive type node, say **int**, **semanticModel.GetSymbolInfo(node).Symbol** was returning **System.Int32**.
3. When we upgraded Roslyn to **version 2.0.0** through Visual Studios 2015's **Manage Nuget Packages for Solution**, **SemanticModel.GetSymbolInfo** for a Primitive type node, say **int**, **semanticModel.GetSymbolInfo(node).Symbol** returns NULL.
4. Note:  
      1.  **Document.GetSemanticModelAsync().Result** is the code used for getting the **SemanticModel**.
      2. The Document object intern has been created using **workspace.OpenSolutionAsync(solutionPath).Result** 
      3. **SemanticModel.Compilation.References** returns empty list for version 2.0.0.

**Expected Behavior**:
With version 2.0.0, **semanticModel.GetSymbolInfo(node).Symbol** for a Primitive Type node, say **int**, should return a non NULL value with **System.Int32**.

**Actual Behavior**:
With version 2.0.0, **semanticModel.GetSymbolInfo(node).Symbol** returns NULL for a Primitive Type Node, say **int**.

**Comment by CyrusNajmabadi** [comment] 2017-03-24 13:52
Please provide a complete repro project so that we can investigate this.  Thanks!

**Comment by abhijitparkhi1983** [comment] 2017-03-25 16:53
@CyrusNajmabadi ,

I was trying to attach a 10MB zip file with the code. But github says "We don't support the file type."
Wonder how can i attach my code. So I am adding the code below as text. 
I have installed following nuget's for the below code:

1. Install-Package Microsoft.CodeAnalysis
2. Install-Package Microsoft.Net.Compilers
3. Install-Package Microsoft.Build.Tasks.Core
4. Install-Package Microsoft.Build

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.MSBuild;
using System;

namespace Roslyn_Walker_Test
{
    public class CodeToWalk
    {
        int i = 10;

        public double Test(bool isValid)
        {
            if (isValid)
                return 10.00;
            else
                return 20.00;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            //Relative path of the same solution which has this particular file.
            var solutionPath = @"\Roslyn_Walker_Test_Code\Roslyn_Walker_Test_Code.sln";
            var workspace = MSBuildWorkspace.Create();
            Solution solution = workspace.OpenSolutionAsync(solutionPath).Result;

            foreach (var project in solution.Projects)
            {
                foreach (var document in project.Documents)
                {
                    WalkDocument(document);
                }
            }

        }

        private static void WalkDocument(Document document)
        {
            var decendendNodes = document.GetSyntaxRootAsync().Result;
            var sementicModel = document.GetSemanticModelAsync().Result;

            SyntaxWalker syntaxWalker = new SyntaxWalker(sementicModel);
            syntaxWalker.Visit(decendendNodes);
        }
    }

    public class SyntaxWalker : CSharpSyntaxWalker
    {
        private SemanticModel sementicModel;

        public SyntaxWalker(SemanticModel sementicModel)
        {
            this.sementicModel = sementicModel;
        }

        public override void VisitCompilationUnit(CompilationUnitSyntax node)
        {
            base.VisitCompilationUnit(node);
        }
        
        public override void VisitPredefinedType(PredefinedTypeSyntax node)
        {
            //HERE symbolInformation is NULL when we use Roslyn Version 2.0.0.
            ISymbol symbolInformation = sementicModel.GetSymbolInfo(node).Symbol
                                        ?? sementicModel.GetDeclaredSymbol(node);

            if(symbolInformation != null)
            {
                Console.WriteLine(symbolInformation.ToDisplayString());
            }
        }
    }
}

```

**Comment by abhijitparkhi1983** [comment] 2017-03-27 07:21
@CyrusNajmabadi, 
I have uploaded the code at following link:

https://www.dropbox.com/sh/x0al5alppkjxfdo/AACBYsvScWh0pPlvWmmh_zOEa?dl=0

I have added two code bases, one with Version 1.3.2 which works well and the another with Version 2.0.0 which does not work.

I am running both these codes bases using Visual Studios 2015 Community Version under .NET Framework 4.6.1.

Looking forward to help from the Roslyn team

**Comment by abhijitparkhi1983** [comment] 2017-03-29 05:29
@CyrusNajmabadi @jaredpar 

Roslyn Team, please let me know if the team was able to access the codebase which I have shared. 
Looking forward to further communication from the Roslyn Team

**Comment by CyrusNajmabadi** [comment] 2017-03-29 05:32
I can access the link.  But i don't believe anyone has even been assigned to look at this yet :)

**Comment by abhijitparkhi1983** [comment] 2017-03-31 09:08
@Pilchie @jaredpar @CyrusNajmabadi 

Roslyn Team, it will be very helpful if the team can help me out on this. Its a blocker for me right now.

**Comment by cston** [comment] 2017-03-31 16:42
@abhijitparkhi1983 I tried your sample above with 1.3.2 and 2.0.0. With both versions, `GetSymbolInfo(node).Symbol` returned non-`null` for all predefined types and `GetDeclaredSymbol(node)` returned `null` for all.

For instance, with a slightly modified `VisitPredefinedType`:
```
var s1 = model.GetSymbolInfo(node).Symbol;
var s2 = model.GetDeclaredSymbol(node);

Console.WriteLine("{0}: GetSymbolInfo() = {1}, GetDeclaredSymbol() = {2}",
    node.GetText(),
    s1 == null ? "<null>" : s1.ToDisplayString(),
    s2 == null ? "<null>" : s2.ToDisplayString());
```
I get the following:
```
>1.3.2\bin\Debug\ConsoleApplication1.exe
        int : GetSymbolInfo() = int, GetDeclaredSymbol() = <null>
double : GetSymbolInfo() = double, GetDeclaredSymbol() = <null>
bool : GetSymbolInfo() = bool, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
string: GetSymbolInfo() = string, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>

>2.0.0\bin\debug\ConsoleApplication1.exe
        int : GetSymbolInfo() = int, GetDeclaredSymbol() = <null>
double : GetSymbolInfo() = double, GetDeclaredSymbol() = <null>
bool : GetSymbolInfo() = bool, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
string: GetSymbolInfo() = string, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
```
Let me know if I've overlooked something. Thanks.

**Comment by abhijitparkhi1983** [comment] 2017-04-03 05:38
Thanks for the reply @cston 

Are you running these applications using Visual Studios 2017 ?
FYI, I am running these applications using Visual Studios 2015 community version.

I modified my code the way you have and following is the output I am getting:
```
>1.3.2\bin\Debug\ConsoleApplication1.exe
         int : GetSymbolInfo() = int, GetDeclaredSymbol() = <null>
double : GetSymbolInfo() = double, GetDeclaredSymbol() = <null>
bool : GetSymbolInfo() = bool, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
string: GetSymbolInfo() = string, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = void, GetDeclaredSymbol() = <null>
```
```
>2.0.0\bin\debug\ConsoleApplication1.exe
        int : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
double : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
bool : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
string: GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
void : GetSymbolInfo() = <null>, GetDeclaredSymbol() = <null>
```
Is there some pre-requisite which I am missing?
Can you please let me know if I am missing any nuget package looking at the .dlls refereed?

**Comment by cston** [comment] 2017-04-03 14:55
I tested with VS 2015 Update 3 (csc.exe reports version 1.3.1.60616). For 2.0.0, I believe I installed NuGet packages { Microsoft.Build, Microsoft.Build.Tasks.Core, Microsoft.CodeAnalysis.CSharp.Workspaces }.

**Comment by abhijitparkhi1983** [comment] 2017-04-04 02:24
@cston 

If we check on the .dll references in the project which I have shared for Version 2.0.0, we will observe that all the above three packages are installed : 
 **Microsoft.CodeAnalysis.CSharp.Workspaces Version 2.0.0 (Runtime Version v4.0.30319)**
 **Microsoft.Build Version 15.1.0.0 (Runtime Version v4.0.30319)**
 **Microsoft.Build.Tasks.Core Version 15.1.0.0 (Runtime Version v4.0.30319)** 

I am not sure if there is any impact of the **csc.exe reports version**
I have **Microsoft Visual Studios Community 2015 Version 14.0.25431.01 Update 3** with **Microsoft .NET Framework Version 4.6.01055**

Is there any limitation of the Community Version? 
Am I missing any thing very basic? 

Looking forward to further communication.

**Comment by cston** [comment] 2017-04-05 22:10
@abhijitparkhi1983 What are the values of `CandidateReason` and `CandidateSymbols` on the `SymbolInfo` returned from one of the `GetSymbolInfo()` calls, say the first call for `int`? And what is the runtime type of the `SemanticModel` instance? Thanks.

**Comment by abhijitparkhi1983** [comment] 2017-04-06 09:17
@cston 

For **sementicModel.GetSymbolInfo(node)**, following are the values for the required attributes:

1. **CandidateReason**: None.
2. **CandidateSymbols**: Length = 0.

What do u mean by **Run-time Type of SemanticModel Instance**? Do u mean to say SemanticModel's **Compilation.ObjectType** ??

One important point to note: 
1. **SemanticModel.Compilation.References returns Empty List for version 2.0.0.** 
2. While **SemanticModel.Compilation.References returns below List for version 1.3.2**:

```
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Microsoft.CSharp.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.DataSetExtensions.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll'	
Assembly Path='C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll'

```

Looking forward to further communication.

**Comment by cston** [comment] 2017-04-06 15:59
Perhaps the issue is with the project. I created C# Console Application targeting 4.6.1 for both 1.3.2 and 2.0.0. What project type did you create for 2.0.0?

**Comment by abhijitparkhi1983** [comment] 2017-04-06 16:45
Hello @cston 
We have created a console application as well with 4.6.1 as a target framework for both 1.3.2 and 2.0.0.
You can check out on the project which I have shared at https://www.dropbox.com/sh/x0al5alppkjxfdo/AACBYsvScWh0pPlvWmmh_zOEa?dl=0

**Comment by cston** [comment] 2017-04-06 22:29
Thanks @abhijitparkhi1983. I compiled and ran your 2.0.0 project with Microsoft Visual Studio Community 2015 14.0.25431.01 Update 3. `symbolInformation` was non-`null`:
```
int
double
bool
void
string
void
void
void
```

**Comment by abhijitparkhi1983** [comment] 2017-04-07 04:05
Thanks @cston 

I think thats the point. On my side, it works for Roslyn Version 1.3.2 and does not for Roslyn Version 2.0.0. 
So there has to be some additional installation/package required for Roslyn Version 2.0.0 to work well for the above mentioned scenario.
If the code which I have shared with the team works for Version 2.0.0 as it is on your side, that means there isn't any package related issue. All the required packages are refereed in the project. 

So my suspect is I am missing on some installation specifically required for Roslyn Version 2.0.0 to run smoothly.
Please let me know your views. I am kind of stuck with this scenario and would look forward to get this thing resolved as early as possible.

Looking forward to hear from you.

**Comment by abhijitparkhi1983** [comment] 2017-04-10 06:19
@cston , @CyrusNajmabadi , @Pilchie 
Looking forward to updates on this thread

**Comment by cston** [comment] 2017-04-10 14:04
@abhijitparkhi1983 Would you mind including the compiled exe in the 2.0.0 drop? I could compare that to what I compiled.

**Comment by abhijitparkhi1983** [comment] 2017-04-11 04:07
@cston , I have uploaded the required compiled exe which is using Version 2.0.0 at the following location: https://www.dropbox.com/s/m3cc1me9c4ofuqh/Roslyn_Version_2_0_0_WithExe.zip?dl=0.

Hope this will be helpful.

**Comment by cston** [comment] 2017-04-11 19:49
@abhijitparkhi1983 Your binary looks essentially identical to the release exe I built locally, and the program reports the same results: that is non-`null` values for `GetSymbolInfo()` in each case.

**Comment by abhijitparkhi1983** [comment] 2017-04-12 05:26
@cston  so what could be a possible issue? Where should I look for the issue. 
Is there any additional installation required?

Especially the below behavior is strange.
**SemanticModel.Compilation.References returns Empty List for version 2.0.0.
While SemanticModel.Compilation.References returns below List for version 1.3.2** 

Can we get any clue out of this?

**Comment by cston** [comment] 2017-04-12 14:09
Perhaps run in the debugger, and enable "Break When Thrown" for all CLR Exceptions. Are any exceptions thrown or is anything unexpected reported to the Output Window?

**Comment by abhijitparkhi1983** [comment] 2017-04-12 17:08
@cston  
Nops. Nothing different after making the above settings. 
I dont see any exceptions in the Output Window.

Any thing else that I should be looking out for??

**Comment by cston** [comment] 2017-04-12 20:20
@abhijitparkhi1983, I apologize, I am able to repro the issue on a VM with only VS2015 Community edition installed. (Previously, I had tested this on a VM with both VS2015 Community and VS2017.) We'll investigate further. Thanks for reporting this issue.

**Comment by abhijitparkhi1983** [comment] 2017-04-13 04:03
@cston Thanks. Looking forward to further communication.

**Comment by cston** [comment] 2017-04-13 05:33
@abhijitparkhi1983 We're still investigating the issue. In the meantime, @DustinCampbell suggested that installing [VS2017 Build Tools ](https://www.visualstudio.com/downloads/?q=build+tools) may be a work around. Please note, that will install the latest MSBuild and Roslyn compilers.

**Comment by abhijitparkhi1983** [comment] 2017-04-13 05:39
@cston Thanks for the update. Will install the VS2017 Build Tools and try to check it out.
In the mean time, I would also like to bring to the notice of the team that the above mentioned behavior can be reproduced for even Roslyn Version 1.3.2  on a machine which has no Visual Studios 2015 Setup.

This is a kind of test machine where we have **VS2015 Build Tools** installed along with .NET Framework 4.0, .NET Framework 4.6.0 and .NET Framework 4.6.1 installed. 
The Roslyn Related Packages are there in the Release folder pointing to Roslyn Version 1.3.2.

We could observe exactly the same behavior like mentioned in the above thread.
Inputs on this behavior would be helpful as well.

**Comment by Pilchie** [comment] 2017-04-13 15:46
>This is a kind of test machine where we have VS2015 Build Tools installed along with .NET Framework 4.0, .NET Framework 4.6.0 and .NET Framework 4.6.1 installed.
The Roslyn Related Packages are there in the Release folder pointing to Roslyn Version 1.3.2.

Note that you need to install the 4.6.1 *Targeting Pack* as well as the 4.6.1 *runtime*. The former contains the reference assemblies that developers use to compile against, the latter contains the actual runtime assemblies production machines can deploy to run against.  Installing the runtime doesn't install the targeting pack.

**Comment by abhijitparkhi1983** [comment] 2017-04-13 16:34
@Pilchie thanks for your input. Will try to install the 4.6.1 Targeting Pack as well as 4.6.1 runtime. 
I am a  bit confused with this. So does this mean that Visual Studios 2015 Community version installation  installs the 4.6.1 Targeting Pack?

**Comment by Pilchie** [comment] 2017-04-13 17:21
Yes, Visual Studio typically installs several targeting packs.

**Comment by abhijitparkhi1983** [comment] 2017-04-14 16:20
Thanks @Pilchie 

@DustinCampbell Looking forward to further updates on this issue

**Comment by abhijitparkhi1983** [comment] 2017-04-17 09:52
@Pilchie I tried installing  4.6.1 Targeting Pack **NDP46-TargetingPack-KB3045566.exe**.
But the results are the same as mentioned above. It has not resolved the qualified path issue.
Am I missing any thing ?

**Comment by abhijitparkhi1983** [comment] 2017-04-20 11:31
@Pilchie @DustinCampbell 

Please let me know if we have any update on this issue thread.

**Comment by abhijitparkhi1983** [comment] 2017-04-26 11:32
@Pilchie @DustinCampbell @cston 

Please let me know if we have any update on this issue thread.

**Comment by Pilchie** [comment] 2017-05-23 00:26
Can you try using the NuGet packages from our [myget feed](https://dotnet.myget.org/gallery/roslyn), and subscribing to the `WorkspaceFailed` event.  That should give more information about why msbuild evaluation is failing.

**Comment by abhijitparkhi1983** [comment] 2017-05-25 11:53
Hello @Pilchie 

I tried the NuGet package from the feed which you have provided. Especially the **Install-Package Microsoft.CodeAnalysis -Version 3.0.0-dev-61717-03 -Source https://dotnet.myget.org/F/roslyn/api/v3/index.json** package.

I retested the scenario which I have described above for version 2.0.0/2.0.1 and its working well with version 3.0.0 the way it works for version 1.3.2.

I am not sure why should I be subscribing to **WorkspaceFailed** event ?

**Comment by MattGertz** [comment] 2017-06-30 19:58
Mondo escrow triage: moving out, but if we have a actionable fix that meets the Escrow bar, please tag me.

**Comment by dpoeschl** [comment] 2017-09-21 19:59
Major triage: moving out. 

@abhijitparkhi1983 are you still having problems here?

@DustinCampbell should we reassign this?

**Comment by abhijitparkhi1983** [comment] 2017-09-26 07:22
@dpoeschl 

We still have this issue with the said versions. Its not applicable for the latest version though.

**Comment by CyrusNajmabadi** [comment] 2020-03-15 08:06
> We still have this issue with the said versions. Its not applicable for the latest version thou

Given the following, it sounds like something that has been fixed in current builders.  Closing out.

**Closed by CyrusNajmabadi** 2020-03-15 08:06 UTC
Labels: Area-IDE, Question

**Comment by miyu** [comment] 2020-04-08 08:02
@CyrusNajmabadi this was not fixed in latest build for me. I found a manual workaround as follows (this might help you repro in future, as this bug still exists & affects developers). See my notes here: https://github.com/dotnet/roslyn/issues/36072#issuecomment-610809322
