### ISSUE TITLE
Breaking change involving method group conversion and new "betterness" rules in Overload Resolution.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#6560] opened 2015-11-04 21:01 UTC
```
using System;
using System.Threading.Tasks;

class C
{
    public static void Main()
    {
    }

        public void CallMethods()
        {
            RunTaskOnUIThread(() => MethodReturnsVoid());
            RunTaskOnUIThread(MethodReturnsVoid);
        }

        public static Task RunTaskOnUIThread(Action action)
        {
            return Task.FromResult(0);
        }

        public static Task RunTaskOnUIThread(Func<Task> action, bool checkThread = false)
        {
            return Task.FromResult(0);
        }

        private void MethodReturnsVoid()
        {
        }
}
```

Compiles without errors in VS2013.
Reports the following error in VS2015:
```
(13,31): error CS0407: 'void C.MethodReturnsVoid()' has the wrong return type
```

I believe the break is caused by the new rule that a void returning delegate type is worse than a non-void returning delegate type.

**Comment by AlekseyTs** [comment] 2015-11-23 18:36
CC @MadsTorgersen

**Comment by gafter** [comment] 2015-12-30 06:31
It appears the break is caused by an intentional change in overload resolution. It needs to be resolved in the language design meeting (i.e. it is a language design issue), not in the compiler. The compiler is behaving as specified.

**Comment by AlekseyTs** [comment] 2016-01-11 22:43
@gafter, Please verify.

**Comment by gafter** [comment] 2016-01-13 01:12
Reopening so I can document the change.

**Closed** 2016-01-21 01:07 UTC
Labels: 3 - Working, Area-Compilers, Bug, Language-C#, Resolution-Fixed, Tenet-Compatibility, Verified
