### ISSUE TITLE
Incorrect indentation between a regular comment and member of a class

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21032] opened 2017-07-21 17:03 UTC
**Version Used**: 26717.1.d15rel

**Steps to Reproduce**:

1. Paste C# code

```C#
class Program
{
    // Must be a comment here, not code. Press Enter twice starting here $$

    public int x; // Must be code after
}
```

2. At the `$$`, press Enter twice

**Expected Behavior**: After each Enter, the caret should be in indented 4 positions

**Actual Behavior**: After the second Enter, the caret is indented 8 positions

**Comment by dpoeschl** [comment] 2017-07-21 17:08
(The same scenario doesn't repro the problem inside a method body)

**Comment by Pilchie** [comment] 2017-07-21 17:27
Duplicate of #3321.

**Closed by Pilchie** 2017-07-21 17:27 UTC
Labels: Area-IDE
