### ISSUE TITLE
Broken Tao Test: BasicGenerateTypeDialog

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#14735] opened 2016-10-25 22:08 UTC
The BasicGenerateTypeDialog VSI Test is failing on this line: https://github.com/dotnet/roslyn-internal/blob/6bb2fb17ebab81584b68877184f753991fc51e3a/Closed/Hosting/RoslynTaoActions/IntegrationTests/BasicGenerateTypeDialog.xml#L37. It appears that the file isn't being found.

```
System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at EnvDTE._DTE.ExecuteCommand(String CommandName, String CommandArgs)
   at Roslyn.VSHosting.Test.OpenFileAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p08ba736a3\Closed\Hosting\Test\Actions\VisualStudio\OpenFileAction.cs:line 82
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 36
```

Example:
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1076/artifact/Open/Binaries/Release/Exes/EditorTestApp/VSIntegrationTestLogs/BasicGenerateTypeDialog.html

Started failing with this run: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1059/

@CyrusNajmabadi @jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by 333fred** [comment] 2016-10-25 22:09
Failed on every run since 1059 except 1065.

**Comment by Pilchie** [comment] 2016-11-07 21:35
Duplicate of #12412

**Closed by Pilchie** 2016-11-07 21:35 UTC
Labels: Area-IDE, Bug
