### ISSUE TITLE
SyntaxGenerator (C#) produces inconsistent type expressions

### ISSUE THREAD

**Issue by axel-habermaier** [dotnet/roslyn#9828] opened 2016-03-17 11:56 UTC
`SyntaxGenerator.TypeExpression` produces inconsistent output when used with primitive types. For instance, `SyntaxGenerator.TypeExpression(SpecialType.System_Int32)` produces `int`, whereas `SyntaxGenerator.TypeExpression(symbolForSystemInt32)` produces `System.Int32`. This is inconsistent because all other types (as far as I've seen, at least) are prefixed with `global::`.

`syntaxGenerator.TypeExpression(symbolForSystemInt32)` should either generate `int` or `global::System.Int32`. Similar for all other primitive types. Particularly, I do _not_ care whether `int` or `global::System.Int32` is generated; `System.Int32`, however, should definitely _not_ be generated.

I came across this issue when generating code for a solution that declares another non-top-level `System` namespace; while this certainly is not good practice, it can definitely happen. The issue is particularly annoying as it makes using certain convenience methods impossible: For instance, `SyntaxGenerator.ParameterDeclaration(IParameterSymbol)` is also affected by this problem.

The following example demonstrates this issue.

**Version Used**: 

NuGet Package `Microsoft.CodeAnalysis.CSharp.Workspaces`, version 1.1.1

**Steps to Reproduce**:

Run the following code in a console application with the `Microsoft.CodeAnalysis.CSharp.Workspaces` package installed:

``` csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Editing;

class Program
{
    static void Main(string[] args)
    {
        var workspace = new AdhocWorkspace();
        var syntaxGenerator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);

        var compilation = CSharpCompilation.Create("test",
            references: new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });

        var typeSymbol = compilation.GetTypeByMetadataName("System.Type");
        var intSymbol = compilation.GetTypeByMetadataName("System.Int32");

        Console.WriteLine(syntaxGenerator.TypeExpression(SpecialType.System_Int32).ToFullString());
        Console.WriteLine(syntaxGenerator.TypeExpression(intSymbol).ToFullString());
        Console.WriteLine(syntaxGenerator.TypeExpression(typeSymbol).ToFullString());
    }
}
```

**Expected Behavior**:

The program outputs:

```
int
global::System.Int32
global::System.Type
```

**Actual Behavior**:

The program outputs:

```
int
System.Int32 <--- No!
global::System.Type
```

**Workaround**

The following code works around this problem:

``` csharp
public static SyntaxNode GlobalTypeExpression(this SyntaxGenerator syntaxGenerator,  ITypeSymbol type)
{
    switch (type.SpecialType)
    {
        case SpecialType.System_Object:
        case SpecialType.System_Boolean:
        case SpecialType.System_Char:
        case SpecialType.System_SByte:
        case SpecialType.System_Byte:
        case SpecialType.System_Int16:
        case SpecialType.System_UInt16:
        case SpecialType.System_Int32:
        case SpecialType.System_UInt32:
        case SpecialType.System_Int64:
        case SpecialType.System_UInt64:
        case SpecialType.System_Decimal:
        case SpecialType.System_Single:
        case SpecialType.System_Double:
        case SpecialType.System_String:
            return syntaxGenerator.TypeExpression(type.SpecialType);
        default:
            return syntaxGenerator.TypeExpression(type);
    }
}
```

**Comment by axel-habermaier** [comment] 2016-03-22 08:12
@DustinCampbell: So this is a confirmed bug that you would like someone to fix? What would be the resolution: Language keywords like ``int`` or .NET type names like ``global::System.Int32``?

**Comment by DustinCampbell** [comment] 2016-03-22 12:35
In our view, the correct behavior is the behavior described in the "Expected Results" above.

Yes, this is up for grabs. If you're interested in submitting a fix, go for it!

**Comment by tvand7093** [comment] 2016-06-26 20:52
For anyone else out there, this seems to be fixed in the current master branch. I'm guessing this was fixed as part of some other issue and this one just got left behind :)

**Comment by Evangelink** [comment] 2019-12-16 11:12
I confirm what @tvand7093 said. I just made a test with v3.4.0 and the actual display is what is listed in the expected. @DustinCampbell the issue can probably be closed.

**Comment by CyrusNajmabadi** [comment] 2020-03-02 03:37
Closing out as this has been confirmed to be fixed.

**Closed by CyrusNajmabadi** 2020-03-02 03:37 UTC
Labels: Area-IDE, Bug, help wanted
