### ISSUE TITLE
"Prefer block" option should have a  third option "prefer no-braces when inner statement is single line"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19451] opened 2017-05-11 23:41 UTC
i.e. some people want:

```c#
if (x)
    return;
```

But would never want

```c#
    if (x)
       foreach (var ...)
          try
          {
          }
          finally
          {
          }
```

**Comment by CyrusNajmabadi** [comment] 2017-08-11 18:53
Similarly, i can see wanting to say "prefer if *entire statement* is not on a single line".  i.e. it's ok to have:

```C#
if (foo) return;
```

but not

```C#
if (foo)
    return;
```

**Comment by sharwell** [comment] 2019-05-07 13:27
Duplicate of #31032

**Closed by sharwell** 2019-05-07 13:27 UTC
Labels: Area-IDE, Feature Request
