### ISSUE TITLE
[Test Failure] RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent_1  in prtest/win/dbg/unit64 on PR #649

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9550] opened 2016-03-08 05:04 UTC
PR: [#649](https://github.com/dotnet/roslyn-internal/pull/649) *Merge stabilization into master* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit64/746/

**Comment by jasonmalinowski** [comment] 2016-03-08 18:13
This is a dupe of #9308, since that PR doesn't yet include the public side changes.

**Closed by jasonmalinowski** 2016-03-08 18:13 UTC
Labels: Area-Infrastructure, Bug, Contributor Pain
