### ISSUE TITLE
Intellisense incorrectly lists extension methods with type constraints on all types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38115] opened 2019-08-19 23:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/695953/intellisense-incorrectly-lists-extension-methods-w.html)._

---
[regression] [worked-in:16.3.0 Preview 1.0]
Intellisense lists extension methods with the type constraints on all types, while it should only list it for types that match the constraint.

To reproduce:
```c#
public static class EnumExtensions
{
    public static bool ExampleExtensionMethod&lt;TEnum&gt;(this TEnum value) where TEnum : unmanaged, System.Enum =&gt; true;
}

public static class Program
{
    public static void Main()
    {
        var obj = new object();
        obj. // look at intellisense, ExampleExtensionMethod will be listed while it should't.
    }
}
```

---
#### Visual Studio Feedback System on 8/16/2019, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-08-20 19:45
duplicate of #37780

**Closed by vatsalyaagrawal** 2019-08-20 19:45 UTC
Labels: Developer Community
