### ISSUE TITLE
Usings used only for required for doc comments are considered unnecessary

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#20976] opened 2017-07-19 17:23 UTC
**Version Used**: 
VS d15rel 26617.01

**Steps to Reproduce**:
Create a C# file where the only reference to a namespace comes through a doc comment.

`using System;
using System.Collections.Generic;   // Not considered necessary

namespace ConsoleApp1
{
    class Program
    {
        /// <summary>
        /// Turns args into a <see cref="List{T}"/>
        /// </summary>
        static void Main(string[] args)
        {
            Console.WriteLine(args.Length);
        }
    }
}`

**Expected Behavior**:
All usings are considered required

**Actual Behavior**:
Usings used only by doc comments are considered unnecessary and will be removed by the remove/sort usings command.

Lightbulbs suggesting adding the using if you don't have it.

**Comment by Pilchie** [comment] 2017-07-19 17:42
This is a duplicate of #2773.

This isn't an issue if you actually enable xml doc comment generation.

**Closed** 2017-07-19 17:43 UTC
Labels: Resolution-Duplicate

**Comment by dpugh** [comment] 2017-07-19 17:54
Ah, there can be a noticeable delay between changing the option in the project file (5+ seconds for a small project) which is why I thought the necessity of the using wasn’t affected by the project setting.
