### ISSUE TITLE
IntelliSense errors for dependency references in newly created Service Fabric project

### ISSUE THREAD

**Issue by dnegstad** [dotnet/roslyn#32554] opened 2019-01-09 23:28 UTC
Regression in 16.0.

1. Launch the new project dialog
2. Create a Service Fabric Application project
3. Select the .NET Core Actor Service template from the New Service Fabric Service dialog
4. Wait for the solution to load and dependencies to restore
5. Check the Error List window and ensure the filter is set to show IntelliSense errors

Expected:
No IntelliSense errors should be reported (dependencies are restored and all references are resolvable).

Actual:
All references to dependencies (NuGet, SDK, or Project references) in the primary service project (Actor1 by default) are flagged as IntelliSense errors.

The errors are only reported for the newly created project and don't reappear after closing and re-opening the solution or unloading and reloading the specific project the errors are associated with. A full build succeeds without any errors or warnings, but doesn't clear the IntelliSense errors.

**Comment by davkean** [comment] 2019-01-17 04:41
Moved this to Roslyn.

**Comment by jasonmalinowski** [comment] 2019-01-17 22:33
Ah, then this is going to be a dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750094. I guess that template is at some point removing a project-to-project reference that was converted from a metadata reference. When the conversion happens back to a file reference, we aren't creating watchers for it, and once a design time build refreshes to remove that reference, we blow up on that point.

**Closed** 2019-01-25 05:16 UTC
Labels: 4 - In Review, Area-IDE, Bug, Regression

**Comment by jasonmalinowski** [comment] 2019-01-25 05:17
@dnegstad Thanks for the report, this fix should be in Preview 3.
