### ISSUE TITLE
[Test Failure] No identified problem in prtest/lin/dbg/unit32 on PR #10846#issuecomment-214511678

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10860] opened 2016-04-25 21:41 UTC
PR: [#10846#issuecomment-214511678](https://github.com/dotnet/roslyn/pull/10846#issuecomment-214511678) *Populate switch tweaks* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6507/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

12:54:13 Unhandled Exception: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
12:54:13  (Exception from HRESULT: 0x8007001F)
12:54:13    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
12:54:13    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
12:54:13    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
12:54:13    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
12:54:13  (Exception from HRESULT: 0x8007001F)
12:54:13    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
12:54:13    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
12:54:13    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
12:54:13    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()

**Comment by Pilchie** [comment] 2016-04-26 14:38
@JohnHamby Is this something you were already looking at?

**Comment by JohnHamby** [comment] 2016-04-26 17:06
No, this is news to me. Is figuring this out a Tiger thing?

**Comment by jmarolf** [comment] 2016-04-26 18:30
No, Viper monitors PRs and Jenkins builds

**Comment by jasonmalinowski** [comment] 2016-08-25 00:22
This was a dupe of #10838.

**Closed by jasonmalinowski** 2016-08-25 00:22 UTC
Labels: Area-Infrastructure, Bug
