### ISSUE TITLE
Bug529989_RenameCSharpIdentifierToInvalidVBIdentifier failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9568] opened 2016-03-08 16:29 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_future_win_dbg_unit32/lastCompletedBuild/testReport/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/RenameEngineTests+VisualBasicConflicts/Bug529989_RenameCSharpIdentifierToInvalidVBIdentifier/

```
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 0)\r\nExpected: B\u0061r\r\nActual: ProgramCS\r\n ↑ (pos 0)
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLocationReplacedWith(Location location, String replacementText, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn_future---ea06c229\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 203 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLabeledSpansAre(String label, String replacement, Nullable`1 type, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn_future---ea06c229\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 134 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.VisualBasicConflicts.Bug529989_RenameCSharpIdentifierToInvalidVBIdentifier() in d:\j\workspace\roslyn_future---ea06c229\src\EditorFeatures\Test2\Rename\RenameEngineTests.VisualBasicConflicts.vb:line 2333
```

**Comment by davkean** [comment] 2016-03-08 16:30
https://github.com/dotnet/roslyn/issues/9565, https://github.com/dotnet/roslyn/issues/9566 and https://github.com/dotnet/roslyn/issues/9568 all look related.

**Comment by jasonmalinowski** [comment] 2016-03-08 18:12
This is a dupe of #9308.

**Closed by jasonmalinowski** 2016-03-08 18:12 UTC
Labels: Area-IDE, Flaky, Test
