### ISSUE TITLE
FAR, GTD broken for inaccessible symbol

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2544] opened 2015-05-06 00:47 UTC
### Simplified repro added by @brettfo:
Find all references fails to find the inaccessible method D.M() when there are overloads.  Commenting out one of them, e.g., `//private void M(double d) { }` allows it to find the symbol.  This same scenario works in VB.

``` C#
class C
{
    private void M(D d)
    {
        d.[|M|](1);
    }
}

class D
{
    private void M(int i) { }
    private void M(double d) { }
}
```

Part of the issue appears to be that the call to [`model.GetSymbolInfoWorker()`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L173) results in a `SymbolInfo` with no bound symbol and no candidate symbols which ultimately leads to FAR and GTD failing.

Added a test for VB [here](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb#L870) and a skipped test for C# [here](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb#L895).

### Original repro by @tmat:
Repro: %internal_share%\public\tomat\Bugs\2544\Repro.zip
1) Unzip (contains Roslyn.sln with some changes). 
2) Open src\Tools\Source\MetadataVisualizer\Program.cs
3) Go to line 203:
```C#
_writer.WriteLine($"Method {visualizer.Literal(method.Name)} (0x{MetadataTokens.GetToken(methodHandle):X8})");
```

Literal is not accessible, but I should be able to go to its definition.

**Comment by tmat** [comment] 2015-05-06 00:48
Repro: %internal_share%\public\tomat\Bugs\2544\Repro.zip
1) Unzip (contains Roslyn.sln with some changes). 
2) Open src\Tools\Source\MetadataVisualizer\Program.cs
3) Go to line 203:
```C#
_writer.WriteLine($"Method {visualizer.Literal(method.Name)} (0x{MetadataTokens.GetToken(methodHandle):X8})");
```

Literal is not accessible, but I should be able to go to its definition.

**Comment by Pilchie** [comment] 2015-05-06 18:05
Find all references is expected, but Go to Definition should definitely work (so you can get there and change the accessibility).

**Comment by brettfo** [comment] 2015-05-06 21:52
As an update, the problem is that we can't find a symbol when the method is private _and_ there are overloads.  E.g., a simplified repro below:

``` C#
class C
{
    private void M()
    {
        new D().[|M|](1);
    }
}

class D
{
    private void M(int i) { }
    private void M(double d) { }
}
```

GoToDefinition will fail because there are two definitions of the method M(), but if one of the methods is commented out, e.g., `//private void M(double d) { }` then the navigation succeeds.  Also, this doesn't repro in VB; it's only a C# failure.

**Comment by Pilchie** [comment] 2015-05-06 22:00
Hmm, I repro'd this with a single private field as well.

**Comment by brettfo** [comment] 2015-05-06 23:46
Re-assigning to compiler for triage.

**Comment by AlekseyTs** [comment] 2015-10-14 20:20
@tmat Please verify.

**Closed** 2015-10-14 20:19 UTC
Labels: 4 - In Review, Area-Compilers, Bug
