### ISSUE TITLE
xunit produced no error output but had exit code 1

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#9456] opened 2016-03-03 20:48 UTC
Opening this issue to investigate failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4797/. All the tests seem to have passed in the build, but xunit still returns with code 1 and no logs for investigation.

_xUnit returned error code without errors_
_xunit produced no error output but had exit code 1_

**Comment by davkean** [comment] 2016-03-03 21:18
It has logs:
```
12:39:41   Command: C:\Users\dotnet-bot\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe "Binaries\Debug\Roslyn.InteractiveWindow.UnitTests.dll" -xml "Binaries\Debug\xUnitResults\Roslyn.InteractiveWindow.UnitTests.dll.xml" -noshadow -verbose
12:39:41   xUnit output: Binaries\Debug\xUnitResults\Roslyn.InteractiveWindow.UnitTests.dll.out.log
12:39:41 
```

Which points to: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4797/artifact/Binaries/Debug/xUnitResults/Roslyn.InteractiveWindow.UnitTests.dll.out.log

Which states:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

Basically a dupe of https://github.com/dotnet/roslyn/issues/8936

**Closed by davkean** 2016-03-03 21:18 UTC
Labels: Area-Infrastructure
