### ISSUE TITLE
Unsuitable code suggestion in ExpandoObject

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32482] opened 2019-01-15 16:51 UTC
On version 15.7
When you declare an object of type ExpandoObject a code suggestion will show up to simplify the object initialization. This will not work as expected because the class members are dynamic and they are late binding

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/411147/unsuitable-code-suggestion-in-expandoobject.html
VSTS ticketId: 753395_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-01-15 18:17
Possible dupe of #18847

**Comment by CyrusNajmabadi** [comment] 2020-03-08 21:03
Fixed with https://github.com/dotnet/roslyn/pull/17860

**Closed by CyrusNajmabadi** 2020-03-08 21:03 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
