### ISSUE TITLE
csharp target typed conditionals regression for integer literal exressions(?). Breaks code targeting langversion=9.0

### ISSUE THREAD

**Issue by binki** [dotnet/roslyn#51871] opened 2021-03-14 22:46 UTC
**Version Used**: Visual Studio 16.9.1 or 4c3ffcbfe7f99f89cc2d350fae777711417caac8

**Steps to Reproduce**:

1.
```csharp
DoSomething(true);

static ushort DoSomething(bool condition) => condition ? 0 : (ushort)7;
```

```csharp
X.DoSomething(true);

static class X {
    static T StaticCast<T>(T value) => value;
    public static ushort DoSomething(bool condition) => StaticCast<ushort>(condition ? 0 : (ushort)7);
}
```

**Expected Behavior**:

Compiles. E.g., what happens if you use Visual Studio 16.8.6. Currently, [Constant Interpolated String branch](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmqAxgZlVNsgDQwgJyYA+AEQIBlAgFsIMABZ0AFNTgQAlAG4AsACgtAAQCMANgAEcZNIIIYR4WMkz5wAsSNNMZdDHTNlRgLwA+F2Z3T2YjAH4jAAYjECM5U3NLZQB2DU0gA=) (9177f9653bce4b96ca60ca1629331c3df29a5801) is an example of it still working.

**Actual Behavior**:

```
error CS0266: Cannot implicitly convert type 'int' to 'ushort'. An explicit conversion exists (are you missing a cast?)
```

Fails to compile with an error. E.g., what happens if you use Visual Studio 16.9.1. Currently, [Generic attributes branch](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQHMIDsIIJYDGqsM+wcMKANDCAnFgD4AiA9gMqsC2EMAFnizoAFKTgQAlAG4AsACh5AAQCMANgAEcZH1YIY6tpx79BI4K1YAbdQVZYAJnhh47E9QF4AfDbuPnd9QB+dQAGdRB1YS0dPQkAdlk5IA=) (4c3ffcbfe7f99f89cc2d350fae777711417caac8) is an example of a broken one.

**Comment by CyrusNajmabadi** [comment] 2021-03-15 00:36
@jaredpar I believe this is a known, intentional breaking change to fix an unintentional spec deviation

**Comment by Youssef1313** [comment] 2021-03-15 06:21
Indeed. This unfortunately was accidentally allowed in .NET 5.0.103 and VS 16.8, and the current behavior is the expected. See #49598.

Duplicate of #51674, #51624, #51597, and #51689

**Comment by binki** [comment] 2021-03-15 14:40
Thanks for referencing that pull request, that explains the behavior I’m seeing and helps me understand the feature better.

I did do a cursory look/search for “conditional” in the release notes and didn’t find this. Is this documented?

The hard thing is that some devs might continue using the older version of Visual Studio and wonder why, if the code compiles for them, it doesn’t compile for those on latest.

**Comment by binki** [comment] 2021-03-15 14:41
And the older version of VS which allowed this has been out for a while, I understand.

**Comment by jaredpar** [comment] 2021-03-15 14:46
Duplicate of #49598.

The breaking change documentation was updated with #51754

**Closed by jaredpar** 2021-03-15 14:46 UTC
Labels: Area-Compilers, untriaged
