### ISSUE TITLE
Automatic backing field generation for properties

### ISSUE THREAD

**Issue by aserre** [dotnet/roslyn#8151] opened 2016-01-25 14:41 UTC
Add a special "field" keyword similar to "value" in properties, to auto-generate a backing field of the same type as the property. Only generate the backing field if the keyword is present.

```csharp
public string SomeProperty = "Hello World"
{
    get { return field; }
    set
    {
        if (value != null) // some custom logic
            field = value;
    }
}
```

instead of :

```csharp
public string SomeProperty
{
    get { return _SomeProperty; }
    set
    {
        if (value != null)
            _SomeProperty = value;
    }
}

private string _SomeProperty = "Hello World";
```

**Comment by HaloFour** [comment] 2016-01-25 17:26
This is a dupe of #850 and probably a couple of other proposals.

Note that the documented purpose of auto-implemented properties is to offer a concise syntax when no additional logic is necessary in the accessor methods.  If you need additional logic then you can already accomplish this with the full property syntax.  How many variations of syntax do properties really need?

**Comment by alrz** [comment] 2016-01-25 20:05
Dupe of #7614.

**Closed** 2016-01-26 17:57 UTC
Labels: Area-Language Design, Resolution-Duplicate

**Comment by jnm2** [comment] 2020-04-04 13:00
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
