### ISSUE TITLE
Configuring analyzers via .editorconfig fails if not in project or open in editor

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#44851] opened 2020-06-04 05:23 UTC
**Version Used**: 16.7

**Steps to Reproduce**:

1. Open the attached console app project: [ConsoleApp242.zip](https://github.com/dotnet/roslyn/files/4727658/ConsoleApp242.zip)
2. In Program.cs, click on line 10, and open the lightbulb menu
3. Try to use any of the "Configure" options to change the .editorconfig file

**Expected Behavior**:
The .editorconfig file is modified appropriately

**Actual Behavior**:
The .editorconfig file is not modified and the lightbulb doesn't go away. This is more annoying in projects where the specific analyzer raises an error or a warning.

You can workaround the issue by either having the .editorconfig file open in a tab in Visual Studio, or including the .editorconfig file in the project with:
```
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
```

I suspect this is partly by design, as the above project file modification is what is done if Roslyn has to create the .editorconfig file, but the behaviour is still a bit annoying because Roslyn clearly knows the .editorconfig file is present, as it doesn't try to recreate it, and will honour code styles specified in it.

**Comment by mavasani** [comment] 2020-07-08 13:06
Duplicate of https://github.com/dotnet/roslyn/issues/44851

**Closed by mavasani** 2020-07-08 13:06 UTC
Labels: Area-Analyzers, Bug
