### ISSUE TITLE
Implementing INotifyPropertyChanged on record crashes Roslyn compiler

### ISSUE THREAD

**Issue by TitusRie** [dotnet/roslyn#50430] opened 2021-01-13 16:32 UTC
**Version Used**: Visual Studio 2019 Version 16.8.3

**Steps to Reproduce**:

1. Create new project Class Library .Net Core
2. Change TargetFramework to netstandard2.1 and LangVersion to 9:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9</LangVersion>
  </PropertyGroup>
</Project>
```

3. Add record with INotifyPropertyChanged:
```
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
namespace ClassLibrary1
{
    public record Class1:INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    }
}
```

4. Build the project

**Expected Behavior**: Compiled project

**Actual Behavior**: Visual Studio crashes with the following Build Output:
```
Build started...
1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : Process is terminated due to StackOverflowException.
1>Done building project "ClassLibrary1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Youssef1313** [comment] 2021-01-13 16:34
Duplicate of https://github.com/dotnet/roslyn/issues/50198

**Closed** 2021-01-13 19:25 UTC
Labels: Area-Compilers, untriaged
