### ISSUE TITLE
Inserting new preprocessor directives or pasting changes the indentation of other preproccessor directives at the same level in a file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23329] opened 2017-11-21 14:36 UTC
When you start to insert a new preprocessor directive, the editor moves other preprocessor directives in your code around. This affects other directives at the same level in the file (before and after), and not just previous related directives (such as #region/#endregion and #if/#endif).

The style formatting rules aren't precise enough to allow for the indentation rules I want on my directives (essentially, follow the indentation level of the code block the directive is in. #if/#endif always tries to hug the left margin). So, I try to format it myself. However, whenever I add a new one in, the editor undoes all this work. If you notice it, you can immediately undo it with Ctrl+Z, but if you don't it can add a lot of extra work to maintain that formatting.

To reproduce it:
1. add a few directives to a file. Do a few to show that it's not just formatting the end of a preprocessor block.
2. Select the entire section of code and hit TAB a few times to change the indentation.
3. Hit enter to start a new line.
4a. Enter a # symbol and watch it all rearrange itself.
 - OR -
4b. Paste something in that level of code. Even a comment. The directives still move.

Expected behavior:
The editor should not edit any lines beyond the one currently being edited with the exception of block formatting. In that case, only the block itself (and its contents) should be edited. In the case of pre-processor directives, the &quot;block&quot; should only be the area between related directives. Other directives at the same level should not be affected, as they're different blocks. In the event that someone wants to format multiple blocks, they can select all of it, or edit the containing block.

Caveats:
methods can sometimes interrupt the behavior in that directives on the other side of that method (block?) may not be affected. The provided example code shows this. All of this is on 15.4.1.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/140858/inserting-new-preprocessor-directives-or-pasting-c.html
VSTS ticketId: 517298_
_These are the original issue comments:_

Matt Newell on ‎10‎/‎30‎/‎2017, 01:37 PM (21 days ago): <p>Also, not sure why it's tagged "crash" as it doesn't crash.</p>

Jinu Joseph [MSFT] on ‎11‎/‎1‎/‎2017, 03:30 PM (19 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Matt Newell on ‎11‎/‎1‎/‎2017, 04:39 PM (19 days ago): <p>Understood. I imagine you've got higher priority stuff to deal with than formatting issues. I've also got another minor issue to report on preprocessor directives in that typing the full directive as opposed to using tab completion demonstrates different formatting behavior. But that's even more minor, so I'm saving it until I've got time to type it up. Good luck, and let me know when you've had time to look into it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment] 2017-11-21 16:04
Dupe of https://github.com/dotnet/roslyn/issues/2487?

**Comment by weltkante** [comment] 2018-09-06 09:53
Yes a duplicate but if you close this one it's worth updating #2487 since it's kinda derailed into discussion and nobody cares anymore about the very real usability bug described here.

**Comment by sharwell** [comment] 2018-09-06 12:02
Duplicate of #2487

**Closed by sharwell** 2018-09-06 12:02 UTC
Labels: Area-IDE, Bug, Developer Community, Language-C#, help wanted
