### ISSUE TITLE
IDE0300 fix-all skips first diagnostic in a cascading ternary

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#71522] opened 2024-01-06 20:53 UTC
**Version Used**: 
Version 17.9.0 Preview 3.0 [34431.11.main]

**Steps to Reproduce**:
```C#
int value = 3;
M(value is 1 ? new[] { "1" } :
  value is 2 ? new[] { "2" } :
  value is 3 ? new[] { "3" } :
  new[] { "4" });

static void M(string[] args) { }
```

**Diagnostic Id**:
IDE0300

**Expected Behavior**:
Four IDE0300 diagnostics issued. Selecting the last one and choosing to fix-all fixes all of them:
```C#
int value = 3;
M(value is 1 ? ["1"] :
  value is 2 ? ["2"] :
  value is 3 ? ["3"] :
  ["4"]);

static void M(string[] args) { }
```

**Actual Behavior**:
Four IDE0300 diagnostics issued. Selecting the last one and choosing to fix-all fixes the last three but not the first:
```C#
int value = 3;
M(value is 1 ? new[] { "1" } :
  value is 2 ? ["2"] :
  value is 3 ? ["3"] :
  ["4"]);

static void M(string[] args) { }
```
cc: @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2024-01-07 18:42
This si super wacky.  Not sure at all why this is failing.  We end up in the compiler asking if `string[]` is equal to `string[]` and the compiler says no.  The reason for this is that one version is `string[]` and the other is `string![]`.  Very unclear what we shoudl do here.  investigating further.

**Comment by CyrusNajmabadi** [comment] 2024-01-07 18:46
@cston @RikkiGibson  is there a reason that when we ask for the type of `new[] { "1" }` we get `string[]`, but when we ask about `["1"]` we get `string![]`?

**Comment by CyrusNajmabadi** [comment] 2024-01-08 05:28
@cston @RikkiGibson I have a potential workaround for the issue: https://github.com/dotnet/roslyn/pull/71528

That PR adds tests showing hte problem, and showing the workaround.  However:

1. i really don't like it.  it feels very skeezy and hacky.
2. even coming up with the workaround was a challenge.  All sort of other changes i made to nullable equality ended up breaking other features (like EnC).  IMO, this should be fixed at the semantic-model level *or* a strong justification should be given as to why we get the type `string[]` (in a nullable enabled context) instead of `string![]` like with arrays.

**Comment by CyrusNajmabadi** [comment] 2024-01-08 23:55
Reactivating to allow compiler to track this.  But giving over to @RikkiGibson .

**Comment by RikkiGibson** [comment] 2024-07-16 23:37
Here's the core scenario
```cs
#nullable enable
var b = false;
var arr = b ? ["1"] : new[] { "2" };
```
Observations:
1. GetTypeInfo on the `new[]` expression gives us an `ElementTypeWithAnnotations` with `NullableAnnotation.NotAnnotated`.
2. GetTypeInfo on the collection-expr gives us an `ElementTypeWithAnnotations` with `NullableAnnotation.None`.

Also, the `new[]` expression in initial binding has "oblivious" element nullability. This makes sense as its nullability is filled in during nullable flow analysis and those results fetched when the public API is used. When I change it to `new string[] { ... }` the expression has "NotAnnotated" nullability in initial binding and the bug does not repro. This probably flows right through to the best-common-type result and therefore the converted type of the collection-expr.

My guess is that we are not storing the updated nullability of the collection-expr properly in order to allow use through the public APIs. Will look a little more deeply in that area later this week.

**Comment by RikkiGibson** [comment] 2024-07-23 18:13
Also, I think there are actual null safety issues which have the same root cause. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzggPgYhgVwDZ4TB4CmABCTEaQLABQAAgMxkMBMZAwmQN71kDWLBgEYADAG0AumQCyIgBTAA9srxlgASl79BegG4QATmWMmAvBrIB+MhIBEI+zJBkYJAO7TeZe23tkAL4A3Lp6AmYSYjKWuATBZAD0iWRgUCgosADmZB7GMNlh4QwA7KZGRqF0eoH0Rcys4t6ybEqq6lo61eEChiZmZLGe3jy+/kFVPREVg1a2Dk4u5ZVFepHRs3F4Ccm5+dlcAMoAHABsbACsrpwQMDDKCGQAxsow+iRGj1tkeFAIHxB1AhlG5XgBaLbUchGEgAMw+lCe5AQAE8AA4kAB0q0EpWWk0EtTogSAA)

```cs
#nullable enable
public class C {
    public string[] M1(bool b) {
        var arr = b ? ["1"] : new[] { "2" };
        arr[0] = null; // missing warning
        return arr;
    }

    public string[] M2(bool b) {
        var arr = new[] { "2" };
        arr = b ? ["1"] : arr;
        arr[0] = null; // warning CS8625: Cannot convert null literal to non-nullable reference type.
        return arr;
    }
}
```

**Comment by jnm2** [comment] 2024-08-07 15:00
Would https://github.com/dotnet/roslyn/issues/74667 be connected? It's a missing warning on `[.. maybeNull]`.

**Comment by RikkiGibson** [comment] 2024-08-07 15:43
I think no, this is just about collection exprs being given the wrong type in nullable analysis. There is an open issue somewhere for lack of nullable analysis of spreads.

**Closed** 2024-08-15 00:41 UTC
Labels: Bug, Area-Compilers, New Language Feature - Nullable Semantic Model, untriaged
