### ISSUE TITLE
Code formatting roaming setting are not roaming

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#15438] opened 2016-11-22 00:23 UTC
I was testing LUT and saw that LUT roaming settings were not roaming. @tmat  mentioned to me that he was using the Roslyn options infrastructure so I then tried Roslyn options and they were also not roaming.

Disclaimer that I changed the setting on one machine, closed solution and VS and then started VS on another machine after a gap of about 3-4 minutes. I am not sure how long it takes for the roaming setting to "roam" but I tries this 3-4 times and not once were the settings roaming. I did however check that I was signed is using the same Microsoft account on both machines.

**Comment by ManishJayaswal** [comment] 2016-11-22 00:23
FYI @jasonmalinowski

**Comment by Pilchie** [comment] 2016-11-22 17:02
Clearing milestone for triage.

**Comment by Pilchie** [comment] 2016-11-22 18:58
I have been seeing inconsistent roaming of all of my settings, including ones that have nothing to do with Roslyn.  Let's follow up with the platform team to see what kind of logging we can investigate to figure out what's happening here.

**Comment by Pilchie** [comment] 2017-01-11 23:55
Can you confirm that this is a dupe of the System.Collections.Immutable binding redirect issue?

**Comment by ManishJayaswal** [comment] 2017-01-12 06:02
@Pilchie I don't think we had changed S.C.I when I filed this issue?

**Comment by jmarolf** [comment] 2017-01-12 06:21
@ManishJayaswal currently settings don't roam because the VS out of proc component that syncs settings depends on S.C.I 1.2.0 while 1.2.1 is what gets installed and the OOP does not have binding redirects

**Comment by ManishJayaswal** [comment] 2017-01-12 06:30
Yes I get that. All I was saying that SCI was probably not the reason when I originally saw this issue. So there may be other issues lurking in here as well causing some of these settings to not roam.

**Comment by tmat** [comment] 2017-01-12 07:11
It seems that we do very bad job in surfacing errors in implementation. We must be swallowing (assembly load) exceptions if the only manifestation of a missing binding redirect is a feature not working as it's supposed to. I would rather have VS crash than silently ignore such a catastrophic failure as a failed assembly load.

**Comment by Pilchie** [comment] 2017-01-20 01:04
I don't think there is anything IDE can do here without a repro.  If you can get a repro, please follow-up with the connectedservices team.

**Closed by Pilchie** 2017-01-20 01:04 UTC
Labels: Area-IDE, Bug
