### ISSUE TITLE
VS unresponsive during FAR

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2876] opened 2015-05-18 22:34 UTC

**Comment by tmat** [comment] 2015-05-18 22:35
ETL trace and memory dump: %internal_share%\public\tomat\Bugs\2876

**Comment by tmat** [comment] 2015-05-18 23:14
@pharring FYI

**Comment by Pilchie** [comment] 2015-05-19 14:59
Can you take a look at the ETL and see what's up here?  We should have a cancellable ThreadedWaitDialog up.

**Comment by rchande** [comment] 2015-05-20 22:13
@tmat According to the dump, we have the wait dialog up and it's showing some animation. Do you have any repro guidance?

**Comment by tmat** [comment] 2015-05-20 22:19
@rchande Not really, I was just working in Roslyn.sln looking for various public APIs in the compiler related to scripting. I don't think I saw any dialog. The UI was frozen.

**Comment by rchande** [comment] 2015-05-28 20:16
@heejaechang in @tmat's trace/dump, it looks like FAR and Solution Crawler are both serializing tons of trees, so he spends like 80% of the trace time in the GC. How hard do you think it would be to suspend Solution Crawler during FAR?

**Comment by rchande** [comment] 2015-06-01 16:09
HeeJae is working on something that fixes this. @heejaechang can you close this once your change is in stabilization?

**Comment by heejaechang** [comment] 2015-06-01 18:59
#2986

it should be fixed if root cause was this

**Comment by heejaechang** [comment] 2015-06-01 19:00
done

**Closed by heejaechang** 2015-06-01 18:59 UTC
Labels: Area-IDE, Bug, Performance
