### ISSUE TITLE
ServiceHub fails to share CompilationTracker instances or otherwise synchronize dependent project parsing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59218] opened 2022-02-02 16:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ServiceHubRoslynCodeAnalysisServiceexe/1632535)._

---
Quite often while working on Paint.NET, which has around 600,000 lines of mostly C# code, RoslynCodeAnalysisService will just burn a CPU core forever and ever, and use anywhere from 17 to 30GB of memory. I just created a DMP file where I caught it using 45GB !!! of memory on my 64GB system. While this is happening, code colorizing and other things don't work very well. It usually chills out after awhile but it happens _all the time_. I haven't yet discerned a pattern for why/when it happens.

I sent a 20GB DMP file to @DavidKean about a month ago, but I haven't heard back.

---
#### dotpdn on 1/9/2022, 08:32 PM: 

(private comment, text removed)
#### Feedback Bot on 1/9/2022, 08:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/18/2022, 10:33 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment] 2022-02-04 02:15
@tmat @sharwell @CyrusNajmabadi Since this is assigned to pretty much all of us at some point, and we did discuss some solutions for this in the past, what's the plan for who is actually going to try some of them?

**Comment by rickbrew** [comment] 2022-02-04 02:59
btw source/solution is available for MSFT employees, just let me know when/if you need it. Including the source generators that seem to be inflaming the situation.

**Comment by jasonmalinowski** [comment] 2022-02-07 19:02
@rickbrew Thanks; the issue is more or less independent of the project structure I think. I think the big difference with generators is the lack of sharing is now just much more apparent than before.

**Comment by CyrusNajmabadi** [comment] 2022-02-07 19:10
@jasonmalinowski what sort of 'sharing' are you thinking about?

**Comment by jasonmalinowski** [comment] 2022-02-07 19:49
@CyrusNajmabadi So if I recall from the prior conversation here a few things did jump out:

When we're synchronizing individual projects rather than the entire solution, we cache on a per-project basis. So if we sync over project A, we stick that in a dictionary keyed with A; if we then sync over B that depends on A, we instead are trying to reuse our past cached solution for B, which also may have A out of date. We won't try to reuse anything from A. That instance is also not cached for when there is a full solution sync later, which might try to use a different instance.

My gut is saying we should only ever have a single cached solution and the per-project one gets removed. The algorithm for a partial and full sync is tweaked to say "we have now a set of checksums for the *projects* we want up to date", and we simply update those, leaving other projects potentially stale a bit. But that means that pulling A forward and then pulling A+B forward later means A is being reused.

If multiple features also ask for a remote solution at the same time with the same checksum, do we make any attempt to share the synchronization process there too? Like have them waiting for a common AsyncLazy or something?

**Comment by CyrusNajmabadi** [comment] 2022-02-07 19:54
i like that.

**Comment by rickbrew** [comment] 2022-03-12 17:30
This bug is really interfering with my work -- I have to restart VS2022 at least once per hour to flush out RoslynCodeAnalysisService. Everything in the IDE just becomes so slow... anything Intellisense related, especially. Rename symbol, Find All References, Extract class to file, and even Find in Files. These are critical to have fast, and I'm constantly have to sit and wait while VS just hangs for 30 - 120 second at a time, and RCAS.exe gobbles up 10s of GB of memory for 10s of minutes at a time.

So I really really really hope this does land for 17.2.

**Comment by CyrusNajmabadi** [comment] 2022-03-12 19:55
@rickbrew definitely try out the latest previews.  if you're still encountering errors, please file traces.  Thanks! :)

**Comment by rickbrew** [comment] 2022-03-12 20:34
Alright I'll see if I can get that working ...

**Comment by rickbrew** [comment] 2022-03-13 16:39
Looks like this is still happening in the preview -- it was working really well for awhile, but then I had to disable IntelliCode because it was hanging VS for over 2 minutes. Now, RoslynCodeAnalysisService is currently using up 42GB of memory and burning the CPU up.

How do I submit a trace?

**Comment by rickbrew** [comment] 2022-03-13 16:52
I have a memory dump, and an ETL trace captured with WPR. Compressing thing up now, ready to send it wherever you need it.

**Comment by rickbrew** [comment] 2022-03-16 23:16
This bug is definitely not gone, I'm still having to restart VS2022 17.2 Preview 2 at least every hour

**Comment by CyrusNajmabadi** [comment] 2022-03-17 04:05
@rickbrew just collect using the steps here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md#performance-issues

**Comment by jasonmalinowski** [comment] 2022-03-29 00:15
I know there was also some suspicion by @sharwell whether there was also some LSP impact here and found some other badness. @dibarbet and I were chatting about some unrelated issues and we also realized that for LSP, we produce separate Solution snapshots in-proc to operate on that are synced with didChange; there we are going to be potentially running generators more than once in-proc unnecessarily. I don't think we'd see that as extra OOP work since the checksums should line up, but that's another avenue for investigation too.

**Comment by rickbrew** [comment] 2022-04-12 17:59
This really isn't fixed in the slightest for 17.2 Preview builds. I've been trying to gather traces as per @CyrusNajmabadi 's suggestion but it's just proven to be too difficult -- either RoslynCodeAnalysisService decides to immediately quiet down, or the system is just way too bogged down for VS to get it done.

Can I just submit ETL traces and memory dumps? Those I can collect fine. I'm having to restart VS2022 a minimum of once per hour, otherwise it just gobbles up all of my system resources. This is _destroying_ my productivity.

**Comment by CyrusNajmabadi** [comment] 2022-04-12 18:10
> Can I just submit ETL traces and memory dumps? 

Sure.  ETL traces would be good.

**Comment by rickbrew** [comment] 2022-04-12 18:57
> > Can I just submit ETL traces and memory dumps?
> 
> Sure. ETL traces would be good.

Where should I submit them? Into the original VS Hub Issue? It's closed ...

**Comment by CyrusNajmabadi** [comment] 2022-04-12 18:59
You can feel free to link here.  And we can look.

**Comment by jasonmalinowski** [comment] 2022-04-13 18:03
I think there might be a bit of miscommunicaiton here: @CyrusNajmabadi I had assigned this to you too since https://github.com/dotnet/roslyn/pull/60575 and https://github.com/dotnet/roslyn/pull/60465 largely achieved what our goal was here. And both of those fixes are in 17.3 Preview 1 so @rickbrew once that goes out you'll be able to try them there. (Checking whether I can just share that schedule...)

**Closed** 2022-04-15 21:08 UTC
Labels: Area-IDE, Concept-Design Debt, Concept-OOP

**Comment by rickbrew** [comment] 2022-04-18 00:15
<img width="590" alt="image" src="https://user-images.githubusercontent.com/10873410/163737424-ab3eecfb-a5cc-4200-b5b8-914ac4e90eb7.png">

This is the sort of thing I keep seeing, for reference :-\ Hopefully fixed soon ... 17.3 previews, right?

**Comment by CyrusNajmabadi** [comment] 2022-04-18 01:10
@rickbrew please file an issue with a trace. There's no way for us to know what might be the cause there.

**Comment by rickbrew** [comment] 2022-04-18 03:57
Yup, planning to the next time I catch it in the act

**Comment by rickbrew** [comment] 2022-04-19 16:08
@CyrusNajmabadi I've got a fresh ETL trace and memory dump for you. https://www.getpaint.net/files/zip/test/RoslynCASBug_2022-04-18.7z

Please let me know when you've downloaded it so I can remove the file

**Comment by CyrusNajmabadi** [comment] 2022-04-19 16:42
hey @rickbrew i've downloaded it.  You can delete it.  Thanks!

**Comment by CyrusNajmabadi** [comment] 2022-04-19 16:50
@rickbrew I've looked at your trace and confirmed it is the problematic area we've already identified.  That area should hopefully be fixed (or highly mitigated) with the following PRs:

https://github.com/dotnet/roslyn/pull/60575
https://github.com/dotnet/roslyn/pull/60638
https://github.com/dotnet/roslyn/pull/60749
https://github.com/dotnet/roslyn/pull/60761
https://github.com/dotnet/roslyn/pull/60779
https://github.com/dotnet/roslyn/pull/60787

The net effect of these PRs is to prevent the 'fork bomb' type problem that was occurring between VS and our ServiceHub process (aka "OOP") where OOP would have a snapshot of the state of our VS solution, and then would have that snapshot be forked N times over (where N is high) where each fork would then redo the compilation work when N features called into it.

Now, both on the outgoing message side from VS, and the processing side in OOP, we have all these concurrent features attempt to share as much as possible to remove (or highly limit) the amount of forking necessary on the OOP side.  Preliminary testing showed a large benefit and i hope it will improve things for you.

**Comment by rickbrew** [comment] 2022-04-19 18:26
Okay sounds great, I look forward to the fix 😎 So these fixes will be available starting with 17.3 Preview 1 ?

If you need a solution to test with, let me know -- repo access is already set up for MSFT employees

**Comment by jasonmalinowski** [comment] 2022-04-19 18:43
@rickbrew Yes, fixes will be in 17.3 Preview 1.

**Comment by rickbrew** [comment] 2022-05-16 23:49
@CyrusNajmabadi @jasonmalinowski After having used 17.3 Pre1 for about a week I'm happy to report **_THIS BUG IS FIXED_** 😁😁😁 I no longer have to restart VS2022 over 10 times per day. Thanks so much!

**Comment by CyrusNajmabadi** [comment] 2022-05-17 01:06
Glad to hear that @rickbrew  :)

**Comment by thegrahamking** [comment] 2022-06-07 11:55
When is 17.3 scheduled for release?

**Comment by rickbrew** [comment] 2022-06-07 19:40
@thegrahamking , based on the previous releases 
- 17.0 in November 2021
- 17.1 in February 2022
- 17.2 in May 2022

My non-authoritative guess is sometime in August

**Comment by alessandrofrancesconi** [comment] 2022-09-19 05:06
I'm working with VS2022 17.3.4 on Windows x64, 8 GB RAM, and servicehub.roslyncodeanalysisservice.exe keeps using lots of RAM after some minutes of work:

![image](https://user-images.githubusercontent.com/1595223/190952487-fe662a29-723a-45eb-9a43-fb7349607cff.png)

I've tried to record dumps/traces, but it is 2 GB big, any advice on where to upload it?

**Comment by CyrusNajmabadi** [comment] 2022-09-19 05:14
@alessandrofrancesconi those numbers do not look add at all.  2.1 GB for service hub is fine.  If you want to report a trace though, use VSFeedback here: 

![image](https://user-images.githubusercontent.com/4564579/190953393-5470c10a-a543-4bb1-a2a1-fd32741b49a8.png)

You can add traces to that.  BUt, as above, nothing seems out of the ordinary with that ram usage for VS.

**Comment by alessandrofrancesconi** [comment] 2022-09-21 07:20
> those numbers do not look add at all. 2.1 GB for service hub is fine.

Actually it seems very strange to me. With 8 GB RAM (minimum system requirements for VS is still 4GB) and no other "frontend" apps apart from Edge, these numbers make development very difficult. At a certain point both Memory and SSD Disk reaches 100% too, I suppose due to swapping, slowing down every operation.

Also I believe this "high" Memory occupation is pretty recent... I never had this kind of issue with 17.2.x. May this be due to a new feature? In case please advice on how to disable it.

**Comment by CyrusNajmabadi** [comment] 2022-09-21 07:23
@alessandrofrancesconi please file an issue using the instructions above.  Or follow the instructions here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md

We can then look at your traces and see if anything is amiss, or if this is normal.
