### ISSUE TITLE
CSharpToBasic test has recurring failure

### ISSUE THREAD

**Issue by jfleisher** [dotnet/roslyn#26205] opened 2018-04-17 18:48 UTC
Skipping because of recurring failure:
master/job/windows_release_vs-integration/53/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpGenerateTypeDialog/CSharpToBasic/

**Comment by sharwell** [comment] 2018-04-20 18:59
Duplicate of #26037

**Closed by sharwell** 2018-04-20 18:59 UTC
Labels: Area-IDE, Flaky, Resolution-Duplicate
