### ISSUE TITLE
Problem with C# lambda expression auto-formatting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36201] opened 2019-06-06 03:39 UTC
VSF_TYPE_MARKDOWNI'm writing a C# lambda expression somewhat like this:

```csharp
    static Action action(() =>
    {
        doThings();
    });
```
At least that's how I meant it. I had typed it like this:
```csharp
    static Action action( () => // with a space right here
    {
        doThings();
    });
```
When I deleted and retyped the semicolon at the end to auto format it, this happened:
```csharp
    static Action action(() =>
   {
       doThings();
   });
```
It shifts all of the text over by as many spaces as there are between the two `(`s, I tested it. This wasn't a difficult bug to deal with, but I thought I'd report it, because I'm fairly sure this is unintended.

Thanks to whoever read through this.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/597221/problem-with-c-lambda-expression-auto-formatting.html
VSTS ticketId: 909893_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-06-06 04:15
Duplicate of #31416

**Closed by sharwell** 2019-06-06 04:15 UTC
