### ISSUE TITLE
NRE when building csc.exe

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#7782] opened 2016-01-05 02:26 UTC
Here's console output:
```
17:16:46 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta1-20151231-01\tools\Microsoft.CSharp.Core.targets(67,5): error MSB3883: Unexpected exception:  [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\CSharp\csc\csc.csproj]
17:16:47 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta1-20151231-01\tools\Microsoft.CSharp.Core.targets(67,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\CSharp\csc\csc.csproj]
17:16:47 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta1-20151231-01\tools\Microsoft.CSharp.Core.targets(67,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\CSharp\csc\csc.csproj]
```

The error occurs in http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2525/

**Comment by davkean** [comment] 2016-01-06 17:50
Duplicate of https://github.com/dotnet/roslyn/issues/7470

**Closed by davkean** 2016-01-06 17:50 UTC
Labels: Area-Compilers, Bug, Contributor Pain
