### ISSUE TITLE
Preserve broken expression in variable of a foreach

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15759] opened 2016-12-08 08:51 UTC
Although this is a syntax error

```cs
foreach (M(e1, e2) in e3) ...
```

We do not currently preserve the binding of the expression `M(e1, e2)` in the initial bound trees. Although there are no symptoms of this (we handle the scoping of expression variables properly, and build binders as needed, and the semantic model binds the expression if and when needed so it works in all of the usual ways), we should bind and preserve it during initial binding for consistency with the design principles of the initial bound tree.

This is somewhat complicated by #13270, as we *do* have a (improper) representation of parts of the expression in some circumstances. We will have to either fix #13270, or tease apart the redundant parts so as to avoid producing a DAG (rather than a tree) in the initial bound tree. The simplest approach would be to fix #13270 and then address this, if anything remains of it. Another approach would be to have mutually exclusive parts of the bound node, one for the `BoundForEachDeconstructStep` (if it remains in the bound tree) and a new field just to preserve a broken expression in this location.

**Comment by 333fred** [comment] 2018-03-30 17:56
Duplicate of #19996

**Closed by 333fred** 2018-03-30 17:56 UTC
Labels: Area-Compilers, Bug, Concept-Design Debt, New Language Feature - Tuples
