### ISSUE TITLE
"Use auto property" across a document/project only fixes a few instances per class

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#26527] opened 2018-05-01 05:11 UTC
**Steps to Reproduce**:

``` C#
internal struct StringFormat
{
    private readonly object _argument1; <! -- Use auto property for "Document"
    private readonly object _argument2;
    private readonly object _argument3;
    private readonly object[] _arguments;

    public object Argument1
    {
        get { return _argument1; }
    }

    public object Argument2
    {
        get { return _argument2; }
    }

    public object Argument3
    {
        get { return _argument3; }
    }

    public object[] Arguments
    {
        get { return _arguments; }
    }
}
``` 

**Expected Behavior**:
``` C#

internal struct StringFormat
{
    public object Argument1 { get; }

    public object Argument2 { get; }

    public object Argument3 { get; }

    public object[] Arguments { get; }
}

```

**Actual Behavior**:

``` C#

internal struct StringFormat
{
    private readonly object _argument3;

    public object Argument1 { get; }

    public object Argument2 { get; }

    public object Argument3
    {
        get { return _argument3; }
    }

    public object[] Arguments { get; }
}

```

If I remove all but Argument3 & Arguments, it won't do "Arguments".

**Comment by sharwell** [comment] 2018-06-14 11:49
Probable conflict detected by the batch fixer. Should be fixed by using a document-based custom fix all provider.

**Comment by CyrusNajmabadi** [comment] 2018-06-14 19:13
Note: at one point i looksed into a custom fix-all provider here. But it was def non-trivial as each fix needs to make solution-wide changes (due to hte renames and whatnot that occur).  It's def possible, but would take a fair bit of work. 

One possibility would be to make something similar to the batch-fixer, but just recognize hte common sorts of edits that occur next to each other with this fix-provider (i.e. removing a lot of fields in a row).

**Comment by CyrusNajmabadi** [comment] 2018-06-14 20:21
Tagging @mavasani 

I've debugged through this, and this is one of those cases where batch fixer struggles a lot.  Effectively, the problem is that for each 'fix' we we ask the editor to describe the 'minimal' edit that happened.  And then we try to 'merge' all the edits together if possible.

However, in this case, we run into edits we dont' think are mergable.  Specifically, when we are trying to apply the 'use autoprop for _argument3' we end up with the following change:

▶ | change | {TextChange: { [573..614), "" }} | Microsoft.CodeAnalysis.Text.TextChange

Effectively, a delete of aobut 40 characters.  however, we also see that there is another existing edit that looks like:

▶ | overlappingSpans[0] | {TextChange: { [542..583), "" }} | Microsoft.CodeAnalysis.Text.TextChange

In this case, another delete of about 40 characters.  These deletions overlap, and so the batch fixer conservatively assumes it has no idea what is going on and bails out.

--

It feels like it *could* be possible to try to support this in the case we have two edits that are *both* completely deleting, but are overlapping.  In this case, we would simply need to figure out what part of the new deletion was not already represented in the cumulative changes, and add int.  In this case, because we already have the delete of ```542...583```, we'd only need to add in the deletion of ```583...614```.

This would now accurately represent what was going on.  Doing the math might be a bit of a PITA.  But it seems possible.  

@mavasani Do you have any thoughts here on what other options there might be?

**Comment by mavasani** [comment] 2022-11-29 10:16
Tagging @stephentoub who hit the same issue in attempting to author a new code fixer. Definitely confusing experience as only someone who knows about this limitation of batch fixer will be able to workaround by using the document based fix all provider.

**Closed** 2024-11-07 23:33 UTC
Labels: Bug, help wanted, Area-IDE
