### ISSUE TITLE
Default constraint is not discoverable, relevent error messages should be improved

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#48971] opened 2020-10-28 07:25 UTC
**Version Used**: current master on SharpLab (aa038a8)

**Steps to Reproduce**:

[Attempt to override a method that uses nullable annotations on unconstrained type parameters:](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AxAHYCuANuRMOXAARzHW0CwAUO9bAhAMYx0AAgCY6AIXYBvdnVlCAzHS4we/IQBY6AWQA8AFQB8ACj0B+OgA8AlAG52AX3bsRdACJ0Q4qTLmDFAewwEBEwAE3pBTV1DE3NrH1lpNjk6RzY0oA)

```c#
#nullable enable

abstract class B
{
    public abstract void M<T>(T? x);
}

class D : B
{
    public override void M<T>(T? x)
    {
    }
}
```

This does not compile and, as I understand it, [the correct fix is to use the new `default` constraint](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AxAHYCuANuRMOXAARzHW0CwAUO9bAhAMYx0AAgCY6AIXYBvdnVlCAzHS4we/IQBY6AWQA8AFQB8ACj0B+OgA8AlAG52AX3bsRdACJ0Q4qTLmDFAewwEBEwAE3pBTV1DE3NrOgB3AAtEej0POnDsCAoYH1lpNjk6RzZSoA):

```c#
class D : B
{
    public override void M<T>(T? x) where T : default
    {
    }
}
```

**Actual Behavior**:

Confusing error messages that make it sound like nullable annotations are not allowed on unconstrained type parameters:

>    error CS0115: 'D.M<T>(T?)': no suitable method found to override
>    error CS0534: 'D' does not implement inherited abstract member 'B.M<T>(T?)'
>    error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'

**Expected Behavior**:

Error message that makes it clear what's going on and suggests using the `default` constraint. Ideally, there should also be a code fix for this.

I think that the `default` constraint is a fairly obscure feature and that users are going to need help finding it. I know I did.

**Comment by cston** [comment] 2020-11-13 01:49
See also https://github.com/dotnet/roslyn/issues/46458.

**Comment by RikkiGibson** [comment] 2021-04-26 17:25
Closing as duplicate of #46458

**Closed by RikkiGibson** 2021-04-26 17:25 UTC
Labels: Area-Compilers, Concept-Diagnostic Clarity, Resolution-Duplicate
