### ISSUE TITLE
Generate method CodeFix shows same fix for two different diagnostics

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1899] opened 2015-04-09 22:57 UTC
it looks like when a line contains two unknown identifier, it shows same fix for two different diagnostic.

and bad thing is it can't get to the other one.

**Comment by heejaechang** [comment] 2015-04-09 22:58
![image](https://cloud.githubusercontent.com/assets/1333179/7078765/3237e86c-ded1-11e4-8d30-0ded04416491.png)

**Comment by heejaechang** [comment] 2015-04-09 23:00
Context.User, here User is type from metadata.

**Comment by shyamnamboodiripad** [comment] 2015-04-24 19:02
```
class Program
{
    void M()
    {
        var x = this;
        x.DoesNotExist(); System.Exception.DoesNotExist2();
    }
}
```

Above code does not run into the problem but below code does.
```
class Program
{
    void M()
    {
        var x = this;
        x.DoesNotExist(System.Exception.DoesNotExist2());
    }
}
```

Also problem seems specific to types from metadata like ```System.Exception``` above. Below code does not run into this problem.

```
class Program
{
    void M()
    {
        var x = this;
        var y = this;
        x.DoesNotExist(y.DoesNotExist2());
    }
}
```

**Comment by shyamnamboodiripad** [comment] 2015-04-27 23:32
@heejaechang please verify this

**Comment by lgolding** [comment] 2015-06-03 20:50
This is partly fixed. When you hover over the first undefined symbol on the line, it displays the correct diagnostic, and it offers only one fix:

![1899-lgolding-1](https://cloud.githubusercontent.com/assets/11762653/7970971/771048f8-09f6-11e5-8c70-dbda77d85f78.png)

The fix works correctly. When you hover over the second undefined symbol, it again displays the correct diagnostic:

![1899-lgolding-2](https://cloud.githubusercontent.com/assets/11762653/7971029/c2d4e118-09f6-11e5-94c9-4786a3c000ac.png)

The problem is that it also displays a light bulb, which offers a fix for the *first* undefined symbol:

![1899-lgolding-3](https://cloud.githubusercontent.com/assets/11762653/7971068/1c9e64da-09f7-11e5-9347-6ebb98a956b3.png)

This is wrong. The second diagnostic should not display a light bulb, since there is no fix for this issue.

**Comment by jmarolf** [comment] 2016-01-14 00:26
No reproducible
![untitled](https://cloud.githubusercontent.com/assets/9797472/12312203/5f1b91e0-ba12-11e5-80d5-48426e210883.png)
.  

![untitled2](https://cloud.githubusercontent.com/assets/9797472/12312192/462e8a34-ba12-11e5-9bfc-3b4099356531.png)

**Closed by jmarolf** 2016-01-14 00:26 UTC
Labels: Area-IDE, Bug

**Comment by lgolding** [comment] 2016-01-14 16:23
Yup, looks like it's fixed. Thanks @jmarolf.
