### ISSUE TITLE
Differences detected in solution checksum

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#48564] opened 2020-10-13 18:20 UTC
**Version Used**: 16db183

🔗 https://dev.azure.com/dnceng/public/_build/results?buildId=850293

**Steps to Reproduce**:

Integration tests

**Actual Behavior**:

```
10/13/2020 15:36:10 Coordinated Universal Time: Error : 1 :[devenv:11412] Unexpected exception: StreamJsonRpc.RemoteInvocationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__133`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__10`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 114
RPC server exception:
System.InvalidOperationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs:line 14
      at System.Diagnostics.TraceInternal.Fail(String message)
      at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 525
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 89
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 135
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetSolutionAsync>d__12.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 213
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs:line 38
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 69
```

**Comment by mavasani** [comment] 2020-10-13 19:05
Can you please provide a repro in a branch which has pre-ISB based OOP? This was fixed in 16.7 or 16.8 and seems to have popped up with ISB changes in 16.9.

@jinujoseph @vatsalyaagrawal Its become increasingly hard to investigate things because I don't know if a bug exists due to ISB fragility/bugs or real product bugs elsewhere. Right now, I have no trust in ISB based OOP, and feel we should revert ISB changes everywhere except a private branch, that is thoroughly tested and dogfooded privately by the IDE team, so we push it out only once we have enough confidence in that feature. Trying to push ISB aggressively bit us once in 16.8, and keeping this on by default in 16.9 is hurting dogfooding (@davkean reported a related issue on Teams channel yesterday) and investigating issues like this one (I don't know if this was a known bug just uncovered somehow in 16.9 OR is some other underlying issue in ISB layer itself).

I am going to hold off on investigating this issue, as it was fixed earlier and did not repro for a long time until ISB changes went it.

**Comment by tmat** [comment] 2020-10-13 20:18
@mavasani What PR fixed this earlier? This shouldn't be related to ISB changes. The issues with ISB we have been having are in the platform (StreamJsonRpc, ServiceBroker).

**Comment by mavasani** [comment] 2020-10-13 20:23
@tmat I believe the last fix here was https://github.com/dotnet/roslyn/pull/46566, which was in 16.8P2. The assert hasn't shown up since then on 16.8.

**Comment by sharwell** [comment] 2020-10-13 21:12
![image](https://user-images.githubusercontent.com/1408396/95916840-209a4480-0d5e-11eb-92e7-47b7059f6f39.png)

**Comment by sharwell** [comment] 2020-10-13 21:14
Here's the `_changedOptionKeysSerializable` for `mismatch2`:

![image](https://user-images.githubusercontent.com/1408396/95916979-5f2fff00-0d5e-11eb-8600-6f6cfd958837.png)

Here's the ones for `mismatch3`:

![image](https://user-images.githubusercontent.com/1408396/95917028-740c9280-0d5e-11eb-9e4a-8012dcf0257e.png)

**Comment by mavasani** [comment] 2020-10-14 16:25
Thanks for adding the test @sharwell. However, based on the investigation noted in https://github.com/dotnet/roslyn/pull/48583/files#r504809883, the scenario in the test is not possible from Visual Studio, so this seems like a test + API consumer issue, hence cannot be a root cause of any dogfooding feedback issues from customers.

I will work on a fix as we still want Roslyn API consumer scenario to work, but I think we should fix the integration test infrastructure to avoid invoking `WithChangedOption` with existing option values, to match the product usage of this API.

**Closed** 2020-10-16 06:48 UTC
Labels: Area-IDE, Bug, Concept-OOP, Integration-Test, Regression, Urgency-Soon
