### ISSUE TITLE
Changing function with async Task from expression body to block body generates return

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27140] opened 2018-05-25 07:40 UTC
If a function has async Task, and I use the quick fix (ctrl+.) to convert it into a body block, visual studio assume that the function returns something because of the Task and adds a return in the block.

For example, lets say i use this code:

     public async Task Logout() => await HttpContext.SignOutAsync();

Using ctrl + . if i select the &quot;use body blocks for methods&quot; option, I get this: 

        public async Task Logout()
        {
            return await HttpContext.SignOutAsync();
        }

However, async Task shouldn't return anything.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/190905/changing-function-with-async-task-from-expression.html
VSTS ticketId: 559892_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment] 2018-05-25 13:29
duplicate of #25202

**Comment by sharwell** [comment] 2018-05-25 13:33
Duplicate of #25202

**Closed by sharwell** 2018-05-25 13:33 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
