### ISSUE TITLE
Project.FilePath is null for Project class instance created for Word 2013 or 2016 VSTO AddIn

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#30429] opened 2018-10-10 10:00 UTC
**Version Used**: 
15.8.6

**Steps to Reproduce**:

1. Create new Word 2013 or 2016 VSTO AddIn c# project
2. Obtain roslyn Project class instance for this newly created project

**Expected Behavior**:
Project.FilePath should contain correct data

**Actual Behavior**:
Project.FilePath is null

**Comment by jinujoseph** [comment] 2018-10-11 17:47
cc @jasonmalinowski

**Comment by jasonmalinowski** [comment] 2018-10-31 20:54
We've realized this is happening because the VSTO project system extensions are causing the language service's request for the project path to fail. We're still not entirely sure whether that's because the language service's call is invalid at that point (the VSTO project system is failing because it's not expecting the call yet), whether VSTO is incorrectly rejecting the call, or because the language service should be answering that question a different way to start.

**Comment by jasonmalinowski** [comment] 2020-02-21 22:01
Closing this now in favor of the internal bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1070444 which is assigned to the VSTO team and the external feedback item https://developercommunity.visualstudio.com/content/problem/859535/go-to-definitionf12-on-a-reference-project-opens-m.html which actually has the same root cause (although it's not obvious from it.)

**Closed by jasonmalinowski** 2020-02-21 22:01 UTC
Labels: Area-IDE, Bug
