### ISSUE TITLE
MSbuild.desktop always rebuilding, even when nothing has changed.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#10847] opened 2016-04-25 20:00 UTC
Everytime i build i get this message from the IDE:

11>Project 'MSBuildTask.Desktop' is not up to date. Copy to output file 'C:\GitHub\roslyn-internal\Open\Binaries\Shared\Microsoft.CSharp.Core.targets' missing from output location.
11>------ Build started: Project: MSBuildTask.Desktop, Configuration: Debug Any CPU ------

**Comment by CyrusNajmabadi** [comment] 2016-06-29 03:32
I'm still getting this.  Current issue is:

8>------ Build started: Project: xUnit.net, Configuration: Debug Any CPU ------
9>Project 'CodeAnalysis' is not up to date. Missing input file 'c:\github\roslyn-internal\open\binaries\obj\immutable\debug\immutable.dll'

Basically all builds are full builds because CodeAnalysis is always rebuilding.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 03:38
Here's teh current issue i'm seeing:

9>Project 'CodeAnalysis' is not up to date. Missing input file 'c:\github\roslyn-internal\open\binaries\obj\immutable\debug\immutable.dll'.7>  InteractiveWindow -> C:\GitHub\roslyn-internal\Open\Binaries\Debug\Microsoft.VisualStudio.InteractiveWindow.dll


Note: i have no idea what "immutable.dll" even is.  However, there is a "Immutable.dll.pcbm" in that folder.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 03:39
Note: i'm putting this back in area-compilers as this affects how Microsoft.CodeAnalysis.dll is getting built.    There appears to be something wrong with teh authoring of this project.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 03:45
@davkean Since about mid-late april incremental builds have been nonfunctional.  I've tracked this back to the introduction of this commit:  4aef0b061cac6875dd8741d62e88f2ada72d3341

This introduced a project that stated:

```<Import Project="..\..\..\build\Targets\ProducesNoOutput.Imports.targets" />```

However, other projects (like Microsoft.CodeAnalysis.dll) depend on it.  As such, Microsoft.CodeAnalysis reports that its dependency is missing, rebuilds itself and causes everything else to rebuild.  Can you take a look at thsi, or let me know how we can address this?  Not being able to incrementally build is a pretty severe impact on dev productivity.

Thanks!

**Comment by CyrusNajmabadi** [comment] 2016-06-29 06:44
Also, if i try to put a dummy "immutable.dll" file in that location, then rebuilds still happen, just with this message: 9>Project 'CodeAnalysis' is not up to date. Missing input file ''.

**Comment by davkean** [comment] 2016-06-29 08:00
First all of, it's important to separate the "update-to-date" of the deployment projects, such as Immutable, from the "update-to-date" of CodeAnalysis. It is expected that Immutable will always be out of date, however, this should not cause downstream projects to also be out-of-date.

As far as I remember the project system does not use dependencies as input as part of its update-to-date, _if_ their target path returns an empty string. Because it thinks that the Immutable project returns an dll called Immutable.dll indicates to me that either that changed or the project system is getting its hands on the target path through some other means.

We've got a very similar/exact approach over in http://github.com/dotnet/roslyn-project-system and I've just tested this we're not experiencing the same issue.  All of our downstream projects (bar the VSIX) are considered up-to-date even though our deployment projects are not.

A couple of questions:

1) Is it only CodeAnalysis that is out-of-date? Or is every project that depends on Immutable also out-of-date?
2) Does it occur with any of the other dependencies projects? ie Are there other projects that don't depend on Immutable suffering from the same problem with one of the other dependencies projects?
3) What VS version are you using? I'm testing a recent build of VS 15.
4) Did you sync back to my exact changes and repro the issue with it then with the exact same message? (I believe up-to-date was broken for CodeAnalysis at the time for other reasons, other than my changes)

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:06
> Is it only CodeAnalysis that is out-of-date?

No.  Other projects show things like this:

```
12>Project 'Workspaces (Workspaces\Workspaces)' is not up to date. Missing input file 'c:\github\roslyn-internal\open\binaries\obj\composition\debug\composition.dll'.
```

> Or is every project that depends on Immutable also out-of-date?

I'm not certain.  I don't know what else depends on Immutable.

>What VS version are you using?

I'm on VS2015 U3.  I was on U2 originally when this problem originally happened.

note: this has happened across machines, and across reinstalls of VS.  It happens in open and it happens in closed.  It has persisted for roughly two months now.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:08
> Did you sync back to my exact changes and repro the issue with it then with the exact same message? 

I can try this.  But hte timing is extremely suspect.  Right after your change went it i started being unable to do incrementally build.  The messages displayed by VS about what needs to be rebuilt are precisely depending on the outputs of these projects that were added.

**Comment by davkean** [comment] 2016-06-29 08:19
Look at the original post above you filed - notice has a different cause to the one you are saying is now occurring. While the symptom is the same, I don't believe the cause is. Up-to-date worked, bar a few projects (which were broken for other reasons), when I checked in my changes. The same changes which I ported to http://github.com/dotnet/roslyn-project-system also work. I'd like a little more confirmation that 1) we didn't make any changes recently that started breaking all projects and 2) we didn't make any changes to the product that caused this to start to appear.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:30
So, with the commit prior to your change things work fine.  If i'm fully built and i make a change in, say, EditorFeatures and i rebuild then i see the following:

1>Project 'EditorFeatures (EditorFeatures\EditorFeatures)' is not up to date. Input file 'c:\github\roslyn-internal\open\src\editorfeatures\core\implementation\intellisense\completion\controller_commit.cs' is modified after output file ''.
1>------ Build started: Project: EditorFeatures (EditorFeatures\EditorFeatures), Configuration: Debug Any CPU ------

i.e. VS didn't even bother with the unrelated projects, and the very first project it decided to start rebuilding was the one i edited.
After that it goes and rebuilds downstream dependencies.



Now, if i go to the last of your commits: a07cddd026fe49391a4a9d532d900df1e2e9e480
And i do the same behavior as above, then i get the follwing output:

6>Project 'CodeAnalysis' is not up to date. Missing input file 'c:\github\roslyn-internal\open\src\dependencies\immutable\obj\debug\immutable.dll'.
6>------ Build started: Project: CodeAnalysis, Configuration: Debug Any CPU ------

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:39
Basically, within this range is when things went awry:

![image](https://cloud.githubusercontent.com/assets/4564579/16445992/2d03adb2-3d9a-11e6-9f07-fb758e06b1f8.png)

**Comment by davkean** [comment] 2016-06-29 08:42
Okay, so it's a pretty good indication that it's related to my change. What I don't understand, is why this occurs for you - but not me, or in other solutions with the same changes. We haven't yet ruled out product changes, when you complained about the update-to-date being broken the first time, it definitely did not have the same cause.

I'm trying to sync Roslyn, what's your verbosity for Project and Solutions -> Build and Run -> Project Verbosity? Even though I've set U2DCheckVerbosity in the registry, I can get the project system to output the reasons for a build.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:44
I'm currently at: 

![image](https://cloud.githubusercontent.com/assets/4564579/16446140/faeec0e0-3d9a-11e6-8f4a-3036340bcde0.png)

**Comment by CyrusNajmabadi** [comment] 2016-06-29 08:56
> What I don't understand, is why this occurs for you - but not me

This is the story of my development life :)

**Comment by davkean** [comment] 2016-06-29 09:01
Meh, trying to download NuGet packages over wifi, and it's taken over 10 minutes to restore toolset project. I'm going to bed, I'll pick this up the morning.

**Comment by davkean** [comment] 2016-06-29 16:40
I can repro this in VS 2015 Update 3. I cannot repro this in a recent build of VS "15". @jasonmalinowski Did we make any changes around update-to-date checks or retrieving output paths from referencing projects recently that might have caused this to now become a problem?

**Comment by davkean** [comment] 2016-06-29 16:51
Yep, something definitely changed or regressed in Update 3. I just did a build of Roslyn in VS 2015 Update 3 and recent VS "15" preview bits. The former exhibits the behavior above where effectively every project is out-of-date, whereas with the later only 16 projects rebuild (the majority of which are the dependencies projects, which is expected), the others are due to real up-to-date bugs in the projects.

**Comment by jasonmalinowski** [comment] 2016-06-29 17:14
We didn't make any intentional changes in Update 3. At one point I saw a bunch of rebuilding always happening for me, but once I tried to debug it, the problem went away. :-(

**Comment by davkean** [comment] 2016-06-29 18:01
@CyrusNajmabadi I'm going to move this to IDE - it appears that this might be a behavior change in csproj, and hence you guys should start with it.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 19:28
I've debugged through this a bit, and the general issue is the following:

1. The UpToDate check thinks that the empty file "" is an input to the project.
2. We later try to get file info for this file and fail.  So the project is rebuilt.

Now, the reason the empty file is in the list of inputs happens in this stack:

```
>	csproj.dll!CCscMSBuildHostObject::GetInputs(CVxStringArray & rgInputs) Line 1305	C++
 	csproj.dll!CCscMSBuildHostObject::IsUpToDateEx(short * pvbUpToDate, int fIncludeAllProjectItems, CUpToDateLogger * pLogger) Line 1246	C++
 	csproj.dll!CCSharpBuildCompiler::IsUpToDate(int * pbUpToDate, int fIncludeAllProjectItems, CUpToDateLogger * pLogger) Line 1794	C++
 	csproj.dll!CVsProjBuildableProjectCfg::StartUpToDateCheck(IVsOutputWindowPane * pIVsOutputWindowPane, unsigned long dwOptions) Line 463	C++
```

The code in question is:

```c++
    CVxTypedPtrMap<CVxMapStringToPtrNoCase, CString, CReferenceItem*>* pRefsInCompiler = m_pReferenceItemManager->GetItemsCurrentlyInCompiler();
    p = pRefsInCompiler->GetStartPosition();
    while (p)
    {
        CReferenceItem* pItem = NULL;
        pRefsInCompiler->GetNextAssoc(p, strKey, pItem);
        ASSERT(pItem);
        if (pItem)
        {
            rgInputs.Add(strKey);
```

From looking at the history and talking to Jason, nothing has really changed here (in the UpTodate check at least).  it seems like this code is not equipped to handle dependencies on projects that don't actually produce output.

Right now the experience is just *super painful*.  Every time you want to build anything, then everything is rebuilt.  If you want to f5 to debug *even when you haven't changed anything* then everything is rebuilt.

@davkean Can we make it so that we don't have projects that don't product output?  Could they instead produce some form out of output so that the building/F5 scenario is addressed.

Thanks!

**Comment by davkean** [comment] 2016-06-29 20:11
You're debugging the wrong point, you need to debug why CodeAnalysis thinks it's out of date. Above is expected as I've mentioned a bunch of time above.

**Comment by CyrusNajmabadi** [comment] 2016-06-29 20:19
That's exactly what i was debugging :)   This was the call to "IsUpToDateEx" specifically for the CodeAnalysis project. 

> you need to debug why CodeAnalysis thinks it's out of date. 

 The reason it is thought to be not up to date is because it's "inputs" list contains the empty string, and the empty string is always considered to be not-uptodate because of the following code:

```c++
BOOL VspGetFileTime(_In_z_ LPCWSTR wszFile, _Out_opt_ FILETIME* pftCreation, _Out_opt_ FILETIME* pftLastAccess, _Out_opt_ FILETIME* pftLastWrite)
{
    WIN32_FILE_ATTRIBUTE_DATA fd;
    if (::GetFileAttributesEx(wszFile, GetFileExInfoStandard, &fd))
    {
        if (pftCreation) *pftCreation = fd.ftCreationTime;
        if (pftLastAccess) *pftLastAccess = fd.ftLastAccessTime;
        if (pftLastWrite) *pftLastWrite = fd.ftLastWriteTime;

        return TRUE;
    }

    return FALSE;
}
```

**Comment by ljw1004** [comment] 2016-07-02 00:40
> What I don't understand, is why this occurs for you - but not me, or in other solutions with the same changes

Just to confirm, I see it too (using VS2015 Update3)

**Comment by jasonmalinowski** [comment] 2016-07-13 19:40
With #12462 most of the remaining issues are fixed. There's still one project (DeployCoreClrTestRuntime) that will fail but I can't fix that because attempting to work around one bug triggers another bug. The PR lists all the tracking bugs for the underlying issues.

**Closed by jasonmalinowski** 2016-07-13 19:40 UTC
Labels: Area-IDE, Contributor Pain

**Comment by MelbourneDeveloper** [comment] 2016-12-20 05:13
I'm getting this issue in Visual Studio 2015. Is this fixed in the next version? Is there a way I can get this fixed in Visual Studio 2015?

**Comment by davkean** [comment] 2016-12-20 05:34
@MelbourneDeveloper You are running into this for *your* projects or Roslyn projects? This bug is tracking the issues within this repo - if you are running into this issue with your project, see: https://blogs.msdn.microsoft.com/kirillosenkov/2014/08/04/how-to-investigate-rebuilding-in-visual-studio-when-nothing-has-changed/
