### ISSUE TITLE
Installing the compilers NuGet package plus the CompilerExtension VSIX results in conflicts

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#9538] opened 2016-03-07 21:54 UTC
**Steps to Reproduce**:
1. Open an ASP.NET web app 
2. Try to build

**Expected Behavior**:
Website builds with no errors.

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/1402694/13584475/a67ba722-e46b-11e5-84f8-e69a2569633a.png)

**Comment by kuhlenh** [comment] 2016-03-07 21:55
@jaredpar for FYI because he also ran into this

**Comment by DustinCampbell** [comment] 2016-03-09 17:52
@jasonmalinowski, could you verify that this is fixed with your changes to the project system, and/or fix it?

**Comment by jasonmalinowski** [comment] 2016-03-11 01:02
Looking at the full errors if I reproduce on an Update 1 + InstallDogfood machine:

    C:\Users\jasonmal\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\e10y1sp3.tyn\Microsoft.CSharp.Core.targets(88,11): error MSB4064: The "Features" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
    C:\Users\jasonmal\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\e10y1sp3.tyn\Microsoft.CSharp.Core.targets(67,5): error MSB4063: The "Csc" task could not be initialized with its input parameters. 

And if I turn on a diagnostic log:

    1>Using "Csc" task from assembly "F:\Projects\LinqToSqlTest\WebApplication1\packages\Microsoft.Net.Compilers.1.0.0\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll".

So it seems if you have both the NuGet package *and* the VSIX installed, we pick the targets from one and the task from the other, which promptly explodes like you'd expect it to. We should fix this (probably soonish even) because we should be able to trust that the experience we see day-to-day reflects what customers will see, but this is not something customers will see.

I've also confirmed that a machine with today's Update 2 build on a clean VM that this doesn't reproduce just to confirm my theory matches reality.

Moving to 1.3.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:12
Closing out due to lack of reports.

**Closed by CyrusNajmabadi** 2024-10-19 21:12 UTC
Labels: Bug, help wanted, Area-IDE
