### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3 is failing

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21795] opened 2017-08-29 20:09 UTC
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/1503/

```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3
      Assert.Contains() Failure
      Not found: 
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
                      D d = delegate (int x)
                      {
                          return 2 * x;
                      };
                  }
              };
          }
      }
      In value:  
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
      
                  }
              };
          }
      }
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpFormatting.cs(202,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3()
```

**Comment by AlekseyTs** [comment] 2017-08-29 21:40
This failure looks related https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/1504/
```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody2
      Assert.Contains() Failure
      Not found: 
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
                      Action<int> b = n =>
                      {
                          Console.Writeline(n);
                      };
                  }
              };
          }
      }
      In value:  
      using System;
      class Program
      {
          static void Main()
          {
              Action a = () =>
              {
                  using (null)
                  {
      
                  }
              };
          }
      }
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpFormatting.cs(159,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody2()
```

**Comment by dpoeschl** [comment] 2017-09-11 18:04
Probably a dupe of https://github.com/dotnet/roslyn/issues/21559, @rchande ?

**Closed by dpoeschl** 2017-09-11 18:04 UTC
Labels: Area-IDE, Test, Urgency-Soon
