### ISSUE TITLE
Add angle-brackets automatically for generic arguments

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59914] opened 2022-03-03 16:07 UTC
Typing “var x = new Li” followed by choosing List<> from the drop-down should add “st<|>” where | is the cursor.

Ideally, parentheses should also be added automatically for method calls when a method is chosen from the Intellisense drop-down.

**Comment by CyrusNajmabadi** [comment] 2022-03-03 16:30
Dupe of https://github.com/dotnet/roslyn/issues/55085

**Closed as completed by CyrusNajmabadi** 2022-03-03 16:30 UTC
Labels: Area-IDE, untriaged
