### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.ImplicitReferenceConflictTests.RenameMoveNextInVBCausesConflictInForEach failure

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9693] opened 2016-03-11 18:11 UTC
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit64/738/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp/ImplicitReferenceConflictTests/RenameMoveNextInVBCausesConflictInForEach/

Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.ImplicitReferenceConflictTests.RenameMoveNextInVBCausesConflictInForEach (from Roslyn.Services.Editor.UnitTests2)

Failing for the past 1 build (Since Failed#738 )
Took 35 ms.
add description
Stacktrace

MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLocationReferencedAs(Location location, RelatedLocationType type) in d:\j\workspace\roslyn-intern---152f0ee2\Open\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 219 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLabeledSpansAre(String label, String replacement, Nullable`1 type, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn-intern---152f0ee2\Open\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 139 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.ImplicitReferenceConflictTests.RenameMoveNextInVBCausesConflictInForEach() in d:\j\workspace\roslyn-intern---152f0ee2\Open\src\EditorFeatures\Test2\Rename\CSharp\ImplicitReferenceConflictTests.vb:line 95

**Comment by jasonmalinowski** [comment] 2016-03-11 18:17
Also cross language, dupe of #9308.

**Closed** 2016-03-11 18:18 UTC
Labels: Area-IDE, Flaky
