### ISSUE TITLE
For non-annotated APIs please assume reference types returned could be null

### ISSUE THREAD

**Issue by dotMorten** [dotnet/roslyn#47481] opened 2020-09-05 01:38 UTC
**Version Used**: netcoreapp3.1 / VS16.7.2

**Steps to Reproduce**:
1. Create a .NET Core WPF project (which isn't null-annotated).
2. Create a ContentPresenter.
3. Access the ContentPresenter.Content property and use it without a null-check. For example: `var stringValue = new ContentPresenter().Content.ToString();`
4. Notice that no nullabilty warning is presented. This despite intellisense literally tells me that's its default value.

![image](https://user-images.githubusercontent.com/1378165/92294032-1d997200-eedd-11ea-97b6-01c2efb8e640.png)

**Expected Behavior**:
Return-values from non-annotated APIs assume reference types could be null.
Perhaps a specific warning that I can always choose to turn off?

**Actual Behavior**:
Analyzer insists this isn't null and never will be. However it'll still allow me to assign it to null: `new ContentPresenter().Content = null;`

In general it would be nice to be able to use nullability annotations but not blindly assume things can't be null when using APIs not annotated yet.

**Comment by miloush** [comment] 2020-09-06 13:35
Your intellisense screenshot does not really correspond to your repro code, the `Content` could have been assigned before from a source that is known to be not null. The "default is null" is coming from the documentation, the compiler does not know anything about that. I am not saying you are wrong but maybe a more self-contained bit of code would help to understand what's wrong.

**Comment by sharwell** [comment] 2020-09-06 14:58
There are two requests here:

1. Assume oblivious values may be null: this is not possible. One of the reasons why nullable reference types took so long to ship is time spent answering exactly this question. Assuming the values may be null is technically more accurate, but it produced such an overwhelming burden on developers that no one would ever be able to transition code to use the new feature.
2. Quick Info shows oblivious values as not null: this is a duplicate of #36983

**Comment by sharwell** [comment] 2020-09-06 14:58
Duplicate of #36983

**Closed by sharwell** 2020-09-06 14:58 UTC

**Comment by dotMorten** [comment] 2020-09-06 15:08
Thanks Sam. I understand the problem for #1. Moved my comment over to the linked issue.
