### ISSUE TITLE
code cleanup fix expression-bodied members does not work

### ISSUE THREAD

**Issue by JieCarolHu** [dotnet/roslyn#27374] opened 2018-06-02 02:22 UTC
example:

```csharp
        public int DoubleTheValue(int someValue)
        {
            return someValue * 2;
        }
```

After code cleanup, it should be 

```csharp
public int DoubleTheValue(int someValue) => someValue * 2;
```

**Comment by sharwell** [comment] 2018-06-02 06:08
Duplicate of #19089 

Fix is in code review now

**Closed by sharwell** 2018-06-02 06:08 UTC
