### ISSUE TITLE
IDE0031: Null check can be simplified used on Expression is not valid

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#17623] opened 2017-03-08 10:20 UTC
**Version Used**: 
Visual Studio 2017 RTM (Visual Studio/15-RTW+26228.4)
**Steps to Reproduce**:

1. Have an Expression Lambda method with a nullable check in it
2. VS 2017 suggests using IDE0031 (Null check can be simplified)
3. Auto apply fix as suggested by VS 2017 (Null type propagation)

**Expected Behavior**:
IDE0031 is not suggested
**Actual Behavior**:
IDE0031 is suggested and results in broken code after application:
-> CS8072	An expression tree lambda may not contain a null propagating operator.

Repro source:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace IDE0031Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            var test = new Test<DTO>();
            test.Method(t => t.NullableGuid != null ? t.NullableGuid.ToString() : null); // works
            test.Method(t => t.NullableGuid?.ToString()); // broken, transformed from above with IDE0031
        }
    }

    class DTO
    {
        public Guid? NullableGuid { get; set; }
    }

    class Test<T>
    {
        public void Method(Expression<Func<T, string>> functor)
        {
        }
    }
}

```

**Comment by Pilchie** [comment] 2017-03-08 21:10
Is this a dupe of something that we fixed already?

**Closed** 2017-03-09 00:01 UTC
Labels: Area-IDE, Bug
