### ISSUE TITLE
'IDE0027 Use expression body for accessors' removes newline after getter

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#17119] opened 2017-02-13 22:55 UTC
**Version Used**: VS2017RC.4

**Steps to Reproduce**:

1. Add code
```C#
namespace N {
	class Program {
		public int Prop1 {
			get { return field; }
			set { field = value; }
		}
		int field;
	}
}
```

2. `Ctrl+.` + `Enter` at `get`

**Expected Behavior**:

```C#
namespace N {
	class Program {
		public int Prop1 {
			get => field;
			set { field = value; }
		}
		int field;
	}
}
```

**Actual Behavior**:

```C#
namespace N {
	class Program {
		public int Prop1 {
			get => field; set { field = value; }
		}
		int field;
	}
}
```

**Comment by 0xd4d** [comment] 2017-02-14 00:32
Same thing with normal methods:

```C#
using System;
namespace N {
	class Program {
		public static void Main() {
		}
		public void Method1() { throw new NotImplementedException(); }
		public void Method2() { throw new NotImplementedException(); }
		public void Method3() { throw new NotImplementedException(); }
		public void Method4() { throw new NotImplementedException(); }
		public void Method5() { throw new NotImplementedException(); }
	}
}
```

=>

```C#
using System;
namespace N {
	class Program {
		public static void Main() {
		}
		public void Method1() => throw new NotImplementedException(); public void Method2() => throw new NotImplementedException(); public void Method3() => throw new NotImplementedException(); public void Method4() => throw new NotImplementedException(); public void Method5() => throw new NotImplementedException();
	}
}
```

**Comment by Pilchie** [comment] 2017-02-15 18:22
I'm pretty sure this is a dupe of #16386.

**Comment by CyrusNajmabadi** [comment] 2017-02-26 22:00
Fixed with https://github.com/dotnet/roslyn/pull/16987

Converting the accessor produces this now:

![image](https://cloud.githubusercontent.com/assets/4564579/23344129/c7ec3fe2-fc2b-11e6-8426-dbca37419684.png)


For methods i get:

![Uploading image.png…]()

**Closed by CyrusNajmabadi** 2017-02-26 22:00 UTC
Labels: Area-IDE, Bug
