### ISSUE TITLE
Quick info should (please) show error/warning/suggestion icons

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27211] opened 2018-05-28 16:34 UTC
It would be really nice if quick info showed an icon with each diagnostic (error/warning/suggestion), possibly even the diagnostic id - just like in the lighbulb preview window, as opposed to plain text. It would be easier to quickly see the relevant information if there's a suggestion or warning in addition to an error.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/261665/quick-info-should-please-show-errorwarningsuggesti.html
VSTS ticketId: 622942_
_These are the original issue comments:_

Šimon Koníček on 5/26/2018, 02:51 AM (2 days ago): <p>This is what I imagine it would look like:</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/30769-quickinfo1.png"> </p><p>or</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/30770-quickinfo2.png"></p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-05-28 16:55
This is a pretty cool idea. So far I like it. 😄

**Comment by Neme12** [comment] 2018-05-28 19:21
I intentionally created this in Developer Community and not Roslyn because I thought it wasn't Roslyn itself that's responsible for adding diagnostics to quick info (has that changed?) - I asked this on a related issue and @jinujoseph confirmed: https://github.com/dotnet/roslyn/issues/26022#issuecomment-382188019 (you may notice that I tried to sneak this suggestion into that issue originally :smile:) Was I wrong in thinking that? Sorry if I created this in the wrong place.

I also thought this change would apply to any language in VS, not just Roslyn-based ones.

**Comment by gundermanc** [comment] 2018-06-06 17:16
Btw, filed a similar issue on the IDE side to do this for everyone: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/607721

If we go down this route, I'd prefer to do it in the platform so we can unify the look for all languages.

**Comment by Neme12** [comment] 2018-09-22 12:53
@gundermanc Thanks. Are there any updates on that issue? Do you think there's a chance this could be considered for 16.0?

@kuhlenh also expressed she'd like to do something similar in https://github.com/dotnet/roslyn/issues/24566#issuecomment-365662307:
> One thing I've been wanting to do is add the 'error icon' into the hover Quick Info to make the error message stand out more.

**Comment by Neme12** [comment] 2018-09-22 12:56
🤔 Huh, I really don't know how this happened... I don't think I have the privileges to do that? Oops

![image](https://user-images.githubusercontent.com/11444821/45917437-7ea61780-be77-11e8-801f-c27b6641ec46.png)

**Comment by gundermanc** [comment] 2018-09-24 17:08
This issue is currently assigned to our PM, Andrew Cheung, for further investigation. I have forwarded this to him to get some input.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 18:22
Closing out as external.  This is for editor/platform.

**Closed by CyrusNajmabadi** 2024-10-21 18:22 UTC
Labels: Area-IDE, Feature Request, Developer Community, Need Design Review, IDE-IntelliSense
