### ISSUE TITLE
CS8751 (internal compiler error) attempting to call function pointer, that returns ref struct

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn#49760] opened 2020-12-02 23:40 UTC
**Version Used**:  .NET 5.0 release; also 3bc4ff8

**Steps to Reproduce**:

```csharp
unsafe ref struct BorrowedReference {
    static readonly delegate* unmanaged[Cdecl]<BorrowedReference> test;
    static BorrowedReference Test() => test();
    readonly int pointer;
}
```
[SharpLab link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+ArgHZQTZwAECc2lsChAxjJQEID2CCHA7nABMASrURxiTKgG8AsAChKiygAEAjADZqcCAI7EANrkoC4+uAHMI8AFSUSkYhHOCA2gGETTfQF0APJ24+QREKGgk4AD5KeFgAbnklFQ12Lh5+YVEwyUoAFThYAAoASkoAXiiYmGL4hSUaHT1DSkxiVgAHDhb4BBqAXyA=)

**Expected Behavior**:
Should compile

**Actual Behavior**:
> error CS8751: Internal error in the C# compiler.

in `Test() => test();`

**Comment by jaredpar** [comment] 2020-12-07 17:46
Thanks for reporting but this appears to be a duplicate of #49315

**Comment by lostmsu** [comment] 2020-12-07 19:03
@jaredpar this is about `ref struct` returns, not returning structs by `ref`. And the error is different.

There's a new test being added for this issue after the other one was fixed, and it appears to be failing: https://github.com/dotnet/roslyn/pull/49831

**Closed** 2020-12-11 01:14 UTC
Labels: 4 - In Review, Area-Compilers, Bug, New Feature - Function Pointers

**Comment by lostmsu** [comment] 2021-01-14 17:31
Will this fix land before .NET SDK 6 in second half of 2021?

**Comment by 333fred** [comment] 2021-01-14 18:17
It should be in VS 16.9.
