### ISSUE TITLE
The UpdaterService test is flaky

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#46255] opened 2020-07-23 18:06 UTC
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#741836](https://dev.azure.com/dnceng/public/_build/results?buildId=741836)|Rolling|1|
|[#742047](https://dev.azure.com/dnceng/public/_build/results?buildId=742047)|#46210|1|
|[#742073](https://dev.azure.com/dnceng/public/_build/results?buildId=742073)|#46229|1|
|[#742078](https://dev.azure.com/dnceng/public/_build/results?buildId=742078)|Rolling|1|
|[#742108](https://dev.azure.com/dnceng/public/_build/results?buildId=742108)|#46233|1|
|[#742242](https://dev.azure.com/dnceng/public/_build/results?buildId=742242)|Rolling|2|
|[#742430](https://dev.azure.com/dnceng/public/_build/results?buildId=742430)|#46234|1|
|[#742466](https://dev.azure.com/dnceng/public/_build/results?buildId=742466)|#46026|1|
|[#742550](https://dev.azure.com/dnceng/public/_build/results?buildId=742550)|Rolling|1|
|[#742551](https://dev.azure.com/dnceng/public/_build/results?buildId=742551)|Rolling|1|
|[#742560](https://dev.azure.com/dnceng/public/_build/results?buildId=742560)|#44447|1|
|[#742614](https://dev.azure.com/dnceng/public/_build/results?buildId=742614)|#45348|2|
|[#742716](https://dev.azure.com/dnceng/public/_build/results?buildId=742716)|#45348|1|
|[#742765](https://dev.azure.com/dnceng/public/_build/results?buildId=742765)|Rolling|1|
|[#742784](https://dev.azure.com/dnceng/public/_build/results?buildId=742784)|#45993|2|
|[#743055](https://dev.azure.com/dnceng/public/_build/results?buildId=743055)|#44447|1|
### Configurations
- Windows Desktop Debug Test32
- Windows Desktop Debug Test64
- Windows Desktop Release Test32
- Windows Desktop Release Test64
- Windows Desktop Spanish

**Comment by jaredpar** [comment] 2020-07-23 18:06
@sharwell, @JoeRobich fyi

**Comment by sharwell** [comment] 2020-07-23 18:45
I'm fairly sure that these issues have the same root cause:

#45877
#46230
#46255 (this issue)

**Comment by 333fred** [comment] 2020-07-24 18:13
This has failed 42 times in the last 14 days and has a pass rate of 95.66%.

**Comment by sharwell** [comment] 2020-07-24 18:19
@tmat This test is being disabled in #46310 so it needs to be fixed ASAP

**Comment by sharwell** [comment] 2020-07-26 21:32
This failure is caused by a race condition between four operations:

1. The "Update" operation, where `_workspace.CurrentSolution` is changed
2. The "Enqueue" operation, where `SolutionChecksumUpdater` handles the `WorkspaceChanged` event
3. The "Wait" operation, where `SolutionChecksumUpdater` waits for work
4. The "Execute" operation, where `SolutionChecksumUpdater` processes work

I derived a sequence for deterministic failure by working back from the following observations:

1. The call to `WaitAsync` in `IdleProcessor.ProcessAsync` is not located within an async operation. Specifically there is an unprotected region of code between these two lines:

    https://github.com/dotnet/roslyn/blob/183b5aa49c2516db4b04f4b4bef40764dbb0d571/src/Features/Core/Portable/SolutionCrawler/IdleProcessor.cs#L90-L92

2. The "Execute" operation always calls `_workspace.CurrentSolution.State.GetChecksumAsync`, which means the final "Execute" operation in the failed sequence completed before the last "Update" operation.

From (2), we know that the fourth "Enqueue" operation completed before the third "Wait" operation (i.e. the fourth enqueue operation returned early from the `_event.CurrentCount` check. We also know that the third "Execute" operation was never performed, which means the third "Enqueue" operation failed to assign a new token to `_lastToken`.

This leads to the following sequence:

1. Second "Wait" operation (ensures `_event.CurrentCount` is 0 and `_lastToken` is not null)
1. Third "Enqueue" operation (requires `_event.CurrentCount` is 0, ensures `_lastToken` is not null and `_event.CurrentCount` is 1)
1. Second "Execute" operation (requires `_lastToken` is not null, ensures `_lastToken` is null)
1. Fourth "Update" operation (ensures `_workspace.CurrentSolution.State.GetChecksumAsync` has not been called)
1. Fourth "Enqueue" operation (requires `_event.CurrentCount` is 1, takes no action)
1. Third "Wait" operation (requires `_lastToken` is null)

During the final step of this sequence, there is no pending work for either the `Workspace` or `SolutionChecksumUpdater` waiters, so the test proceeds to completion without reaching the required call to `GetChecksumAsync`.

**Comment by CyrusNajmabadi** [comment] 2020-07-27 18:06
WHat are you feelings on just burning this to the ground and replacing with something much simpler, versus patching in place like you've done?  This seems liek a super complex beast for what is conceptually such a simple component (i.e. a throttled, pausable, sequence of work).

**Comment by sharwell** [comment] 2020-07-27 18:26
I feel confident the PR I submitted resolves the race condition here, and time would be better spent on resolving the other issues from https://github.com/dotnet/roslyn/issues/46255#issuecomment-663171156 than rewriting this.

**Closed** 2020-07-29 03:26 UTC
Labels: Area-IDE, Disabled Test, Flaky, Urgency-Now
