### ISSUE TITLE
intellisense does not show base class library while typing in XML comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49078] opened 2020-10-30 17:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/intellisense-does-not-show-base-class-li/1238781?preview=true)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.7.7 or 16.7.6]
While commenting code in a <see cref tag where the method has a parameter of type string, byte, or any other value type without `using System;` Intellisense does not show those types and instead selects another type.

For example, a method with the signature
`MyMethod(HttpStatusCode, string?) `

commenting the code in the see tag `<see cref="HttpStringResponse{TError}(HttpStatusCode, strin)"/>`,  while typing string it only shows these  types:
DownloadStringCompletedEventArgs
DownloadStringConpletedEventHandler
UploadStringCompletedEventHandler

And more like that.

If I add `using System;` in the class, Intellisense now shows string, but also, I got two errors, IDE0005 and CS8019.

---
#### Feedback Bot on 10/29/2020, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/30/2020, 09:52 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-10-30 18:01
The easiest way to reproduce this issue is the following:

```csharp
/// <seealso cref="$$" />
class C { }
```

### Expected behavior

`string` appears in the completion list at the position indicated by `$$`.

### Actual behavior

`string` does not appear in the completion list. A `using System;` directive must be added before it appears.

**Comment by CyrusNajmabadi** [comment] 2024-11-11 20:20
Closing out due to lack of broad feedback on this.

**Closed by CyrusNajmabadi** 2024-11-11 20:20 UTC
Labels: Bug, help wanted, Area-IDE, IDE-IntelliSense
