### ISSUE TITLE
Exception from Roslyn analyzer

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8700] opened 2016-02-14 17:46 UTC
The following exception caused my Roslyn build (with changes) to fail after a large merge operation.

```none
  CSC : error AD0001: Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added.'. [D:\Roslyn-Patterns\src\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj]
```

THIS IS NOT HELPFUL. There is no obvious way to determine what the problem is.

**Comment by gafter** [comment] 2016-02-14 18:23
@jaredpar This is blocking my merge from future into features/patterns.

**Comment by jaredpar** [comment] 2016-02-14 20:40
@gafter do you have a link to a commit where this repros?  Have you tried attaching and seeing where the exception is coming from?

**Comment by mavasani** [comment] 2016-02-16 18:44
Seems a dupe of https://github.com/dotnet/roslyn-analyzers/issues/829

**Comment by srivatsn** [comment] 2016-03-11 00:08
Closing as dupe.

**Closed by srivatsn** 2016-03-11 00:08 UTC
Labels: Area-Analyzers, Bug
