### ISSUE TITLE
Go to Type Definition

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#15286] opened 2016-11-16 16:55 UTC
From @kieranmo:

There are situations in the language where is difficult to navigate to the type of a thing. For example, lambda parameters. Soon, tuples will have a similar problem. I.e. what does F12 do on `var` in this case?

```C#
var (x, y, z) = GetData();
```

We need a way to navigate from `x`, to the type of `x`. Likewise, for lambda arguments:

```C#
Console.CancelKeyPress += (a, b) =>
{
    Console.Write($"Hello {a}"); 
}
```

If the caret is on the reference to `a` inside the body of the lambda, how can I get to the type of `a`?

From @DustinCampbell: We need a new feature here! Let's do it!

**Comment by vbcodec** [comment] 2016-11-16 17:29
It was in previous versions o VS, but for unknown reasons was removed. Bring it back.

**Comment by DustinCampbell** [comment] 2016-11-16 17:30
To be fair, it was only in VB. This is an ask for C# as well.

**Comment by Pilchie** [comment] 2016-11-16 18:13
Duplicate of https://github.com/dotnet/roslyn/issues/2505

**Closed by Pilchie** 2016-11-16 18:13 UTC
Labels: Area-IDE

**Comment by DustinCampbell** [comment] 2016-11-16 18:15
I hope you've captured the information in this issue in the one you duped it against. There are scenarios here that make this a much more interesting feature request.

**Comment by Pilchie** [comment] 2016-11-17 00:19
Yep - I made a note to make sure and come look here.
