### ISSUE TITLE
Inline Rename breaks if any open document has text unavailable

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#30] opened 2015-01-18 20:25 UTC
`InlineRenameSession.InitializeOpenBuffers` calls `document.TryGetText` instead of `GetTextAsync`.

If the DocumentState's textSource is a `RecoverableTextAndVersion` rather than a constant source, this won't return a text and will break the rename.

Typing into a document sets the text to a constant version, so this doesn't usually happen.

It consistently happens for me in a TextView with both C# and VB buffers from the same workspace (eg, my Markdown editor); unless all open Roslyn buffers either have had keystrokes or have the cursor (which triggers `UpdateText` fromGetOpenDocumentInCurrentContextWithChanges), it will fail in that method.

As an aside, I can't get rename  to work anyway within VS; I need a `Host` workspace for `IDocumentNavigationService` (internal) to allow the rename, but I need a non-`Host` or the VS version of `ITextUndoHistoryWorkspaceService` will refuse to operate at all with my custom workspace class.
Ironically, rename works fine in custom hosts outside VS (VSEmbed), because I can skip the VS.LangServices layer entirely, except for `IDocumentNavigationService` to allow the rename

**Comment by Pilchie** [comment] 2015-01-19 19:13
I believe it's the case that in our implementation we ensure that there is a `ConstantValueSource` for all files that are open.  Is this something that your host should be ensuring?

**Comment by SLaks** [comment] 2015-01-19 19:16
My host code is https://github.com/madskristensen/WebEssentials2015/blob/master/EditorExtensions/Markdown/Classify/RoslynEmbedder.cs#L83-L86

Is that wrong?

**Comment by mattwar** [comment] 2015-01-19 19:23
All open documents get `PreservationMode.PreserveIdentity` which translates to using `ConstantValueSource<TextAndVersion>` in the `DocumentState` class, which keeps a strong reference to the `TextAndVersion`, so `TryGetText `should always succeed on those.   However, `InlineRenameSession.InitializeOpenBuffers` operates on a solution that is the result of a call to `GetOpenDocumentInCurrentContextWithChanges()`, which forces that document to have its text based on the snapshot that initiated the rename, in case it was not already, but that update to the document also used `PreservationMode.PreserveIdentity`, so it too should always succeed a `TryGetText` call.

**Comment by Pilchie** [comment] 2015-01-19 19:25
@mattwar I think the `TryGetText` can fail if we've never observed the text at all in the `DocumentState` class, even if we have a `ConstantValueSource`.

**Comment by SLaks** [comment] 2015-01-19 19:30
@Pilchie No; http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/TextDocumentState.cs,127

**Comment by SLaks** [comment] 2015-01-19 19:34
@mattwar If I understood my breakpoints correctly, the original document did not have a ConstantValueSource.  
Until I made any kind of edit, I think `GetOpenDocumentInCurrentContextWithChanges` would keep the original source, triggering this issue.

**Comment by mattwar** [comment] 2015-01-19 19:35
It seems like we force observation of the text during the call to Workspace.OnDocumentOpened.

**Comment by SLaks** [comment] 2015-01-19 19:36
I think the problem is http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/TextDocumentState.cs,58; you should either change that to create a CVS, or change the VS hosting layer to _immediately_ replace it with a CVS (by calling WithText), as opposed to waiting for activity in the buffer.

**Comment by SLaks** [comment] 2015-01-19 19:37
@mattwar That doesn't seem to be helping; I call that immediately on every buffer.

**Comment by mattwar** [comment] 2015-01-19 19:39
Okay, if you start with a document with a TextLoader that has a SourceText (not a file), and then you call OnDocumentOpened with the same SourceText, we don't end up changing the preservation mode, so the DocumentState does end up with a RecoverableTextAndVersion.  Instead, we should always call WithDocumentText just to change the preservation mode.

**Comment by SLaks** [comment] 2015-01-19 19:41
Yes; that's exactly what I meant.

**Comment by mattwar** [comment] 2015-01-19 19:48
I'm fixing it now.

**Comment by SLaks** [comment] 2015-01-19 19:50
So basically remove http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Editor.cs,403

**Comment by balajikris** [comment] 2015-01-19 20:25
this looks very similar to another issue we were tracking internally (1084052, where it showed up during a rename in project buffer scenario). from my notes in the bug "the issue is that we're using a recoverable syntax tree and text for an open document, whereas we should always be using a strong version of tree and text if the document is open in the editor"..

**Comment by mattwar** [comment] 2015-01-19 20:36
@Slaks, yes basically that. Thought I'm pushing the equality test down into the next if.

**Comment by mattwar** [comment] 2015-01-20 22:04
This is fixed as of commit 157cf3726b2d304ab43bdc7511171a202a6c4844.

**Closed** 2015-01-20 23:56 UTC
Labels: Area-IDE, Bug
