### ISSUE TITLE
TypeScript would like a way to know if two Documents have the same SourceText content.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#3235] opened 2015-06-01 22:14 UTC
TypeScript would like a way to know if two Documents have the same SourceText content.

The TypeScript-VS component works by grabbing the contents of Documents and passing them over to a JSEngine where are actual LS live and does its work.  When the "Script-Side LS" runs, it calls back to the managed side saying "Here are the 'versions' of the documents i have.  If anything has changed on the Managed-Host side let me know."    

Currently, we are using VersionStamp for this purpose.  This was working well until we ran into a rather unfortunate limitation of VersionStamp.  Namely, if you have two Documents, in different Projects, that both point to the same file on disk, then you will _always_ get a different VersionStamp.  This is because each VersionStamp in this scenario gets a different 'GobalVersion' that ensures that they are different.

Now, in some TypeScript projects it's common to have the same file referenced from multiple projects.  Because our existing way of asking "is this the same file?" didn't work, it means that we would copy that file's contents and store them in our Script-Side-LS multiple times.  This caused a large increase in memory for these types of projects.  Also, in all TypeScript projects there is at least one file commonly shared between them.  Namely our lib.d.ts file.  This file is quite large (>1MB), and so it adds up quite a bit when it is included everywhere.

In order to address this, TypeScript needs a mechanism whereby we can get some 'token' for a SourceText/Document that has the following properties:
1. If the contents of the source text change, the token _must_ be different.
2. As much as possible the token should stay the same if the contents are the same.  (But this doesn't need to be perfect, just better than VersionStamp).
3. The amortized cost of getting a token should be low.
4. It should be cheap to check if tokens are equivalent.

Here's a simple, but inefficient example of something that could work as a token:
1. The file contents.  :-)

Obviously if the file contents changed, then the token would be different.  Also if the token was the same then the contents would be the same.  Of course, this would be a very bad token as it would require sending over the entire contents of the file on each call to our script side. And it would cause a very expensive 'equals' check to verify the 'tokens'.  Thus, condition '4' wouldn't be met.

An alternate approach which we propose (and have tested out), is for the Roslyn side to basically expose SourceText.GetChecksum.  This is currently an internal method in the compilers layer, but would serve our needs well.  Right now it meets the above 4 criteria.
1. If the contents of hte file change, the tokens will be different.  (Ok... technically not a guarantee.  but so unlikely as to never matter in practice).
2. If the contents stay the same, the token will be the same.
3. The amortized cost is low.  The first hit costs a bit (on our machines it looks like we can do about 50MB/s), but then is cached in the source text.  So subsequent calls are no-ops.
4. Checking if two tokens are the same is quite cheap.  Sha1 is 20 bytes, which is really simple to check.

Right now, because this call is internal (and because things are late in the game for VS2015 RTM), we're going to be implementing this solution on our end.  However, it seems unfortunate to have to duplicate this logic when there is a perfectly good system on Roslyn's end.

Also, it does seem like this should be part of our public API.  The hash is something we include in things like the PDB.  So it's something i can imagine people wanting for interesting debugging scenarios.

**Comment by CyrusNajmabadi** [comment] 2015-06-01 22:14
@vladima   @heejaechang   @tmat   To consider.

**Comment by heejaechang** [comment] 2015-06-01 22:29
@dpoeschl David, is linked file actually point to 2 different SourceText or same one? version is stored in VersionAndText so we might need to do something still, but probably easier if it shares same SourceText.

**Comment by CyrusNajmabadi** [comment] 2015-06-01 22:51
Note: this is not actually a 'linked file'.  These are just two Documents that have the same FilePath.  We're using ```DocumentProvider.TryGetDocumentForFile``` to get the Document.  Not sure how to use that API to get a 'linked file' (let alone if a linked file would solve the VersionStamp problem in the first place).

**Comment by dpoeschl** [comment] 2015-06-01 23:19
From the roslyn perspective, documents are "linked" if they share the same file path, and they share the same SourceTextContainer (TextBufferContainer) / SourceText when open. (You can construct a Solution that contains two "linked" Documents with different contents. This may be useful during larger refactorings, etc. When the Solution is applied back to the Workspace, then the changes are merged.)

/cc @jasonmalinowski & @mattwar, as they were discussing similar stuff earlier today

**Comment by CyrusNajmabadi** [comment] 2015-06-02 00:42
@dpoeschl 

I don't believe hte SourceTextContainer would be the same in our scenario.  These are files on disk.  Looking through the roslyn code, it doesn't look like they get the same container.  Should they?

**Comment by mattwar** [comment] 2015-06-02 01:20
Only if the host has done something to make them the same. I believe this may be true in VS workspace for open documents, since the is only ever one text buffer for linked documents. Otherwise I would expect it is not true in general.

**Comment by CyrusNajmabadi** [comment] 2015-06-02 01:51
Ok.  That matches my expectation as well.  Anyone have any other ideas on how to address this issue?  Otherwise, i'd definitely push for exposing GetChecksum.

**Comment by jasonmalinowski** [comment] 2015-06-02 17:23
Exposing GetChecksum seems reasonable. @tmat, was there any particular reason other than "nobody needs it yet" it wasn't made public?

**Comment by CyrusNajmabadi** [comment] 2015-06-02 20:09
@jasonmalinowski 

It's actually not hard for us to call into the runtime to get a hash for the contents of the source text.   The most painful part is getting a Stream for the SourceText.  Right now we have a copy of SourceTextStream that we're using.  But it's super ugly to have a copy of all that complex code.  If SourceText exposed something like "GetStream" on itself then that would also be good enough for our needs.

Technically, we could also accomplish this by just getting the ToString of the source text and then getting the bytes from it.   But this would be at least one large allocation, and we really don't want that (esp. if it makes it to the LOH).  Having a streaming API over the SourceText seems totally clean, and makes this super easy.  We then don't have to expose GetChecksum if we don't want to.

Thoughts?

Thanks!

**Comment by jasonmalinowski** [comment] 2015-06-02 20:13
Well, you have to be very careful here: "getting the source text and getting the bytes from it" is not a well-defined operation once you have fun with encodings. Realize that the checksum of the byte stream on disk doesn't uniquely ensure text, only the pair of (checksum, encoding) is.

You'd still want to use GetChecksum anyways since in VS there's special-case handling (or should be) where we can fetch the checksums from the editor. VS maintains them in some cases for us.

**Comment by mattwar** [comment] 2015-06-02 20:22
Can you just use SourceText.ContentEquals?  It already compares the checksums (if they exist) as a short circuit to comparing actual text.

**Comment by CyrusNajmabadi** [comment] 2015-06-02 20:51
@mattwar We don't have the old source text.  Furthermore, what we do have is on our *script* side (i.e. on a JS engine on the JS heap).  Asking if the contents are the same would involve getting the entire text, and moving it from one engine to the other (either from JS to .Net or vice-versa).  This would be extremely expensive and would not scale.

Hence why we want a 'token' to indicate if the file is the same.  Right now the checksum works the best.

**Comment by CyrusNajmabadi** [comment] 2015-06-02 20:52
@jasonmalinowski Oh, we agree.  That's why we'd like Roslyn to provide the stream/checksum.  We'd like you guys to worry about those niggling issues.  I wasn't aware of the fact that VS does checksums as well.  In that case, we'd def like the Checksum route :)

**Comment by mattwar** [comment] 2015-06-04 20:40
We can expose the checksum we have.  Its an ImmutableArray<byte>.  The problem is that this API will throw if Encoding is null, which happens with source texts that did not originate from a disk file.  The same is true for the stream over SourceText.  I don't think this will make a happy public API experience.

**Comment by CyrusNajmabadi** [comment] 2015-06-04 20:54
What about changing it to TryGetChecksum?

**Comment by mattwar** [comment] 2015-06-04 21:30
That's possible, if a little clumsy.

**Comment by mattwar** [comment] 2016-11-22 22:44
GetChecksum() is public now.  It will use the default encoding (UTF8 no BOM) if no encoding is known.

**Closed by mattwar** 2016-11-22 22:44 UTC
Labels: 0 - Backlog, Area-IDE, Feature Request
