### ISSUE TITLE
[Test Failure] <description> in prtest/win/vsi/p0 on PR #9259

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9262] opened 2016-02-26 23:01 UTC
PR: [#9259](https://github.com/dotnet/roslyn/pull/9259) *Fix devenv /build and devenv /upgrade* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/344/

Nuget restore failed

**Comment by davkean** [comment] 2016-02-27 03:15
Dupe of https://github.com/dotnet/roslyn/issues/9159.

We never ported this to stabilization. I will if it's stable over the weekend.

**Closed by davkean** 2016-02-27 03:15 UTC
Labels: Bug
