### ISSUE TITLE
BadImageFormatException after calling a type inferred local function using dynamic dispatch

### ISSUE THREAD

**Issue by ahutcheson** [dotnet/roslyn#21370] opened 2017-08-08 13:53 UTC
**Version Used**: 
Visual Studio Professional 2017 15.2 (26430.16) Release
Visual C# Compiler version 2.2.0.61624

**Steps to Reproduce**:
```C#
public enum FooType
{
    A,
    B,
}

public abstract class Foo
{
    public int Id { get; set; }
}

public class AFoo : Foo { }

public class BFoo : Foo { }

public TFoo GetFoo<TFoo>(int id)
    where TFoo : Foo, new()
{
    return GetFooSet<TFoo>().SingleOrDefault(f => f.Id == id);
}

public Foo GetFooUsingLocalFunction(int id, FooType fooType)
{
    var type = GetType(fooType);
    dynamic dummy = Activator.CreateInstance(type);
    return GetFooFromPrototypeLocalFunction(dummy);

    Foo GetFooFromPrototypeLocalFunction<TFoo>(TFoo prototype)
        where TFoo : Foo, new()
    {
        return GetFoo<TFoo>(id);
    }
}

public Foo GetFooUsingRegularMethod(int id, FooType fooType)
{
    var type = GetType(fooType);
    dynamic dummy = Activator.CreateInstance(type);
    return GetFooFromPrototypeRegularMethod(id, dummy);
}

private Foo GetFooFromPrototypeRegularMethod<TFoo>(int id, TFoo prototype)
        where TFoo : Foo, new()
{
    return GetFoo<TFoo>(id);
}

private IQueryable<TFoo> GetFooSet<TFoo>() where TFoo : Foo, new()
{
    return Enumerable.Range(1, 10)
        .Select(i => new TFoo { Id = i, })
        .AsQueryable();
}

private static Type GetType(FooType fooType)
{
    switch (fooType)
    {
        case FooType.A: return typeof(AFoo);
        case FooType.B: return typeof(BFoo);
    }

    throw new ArgumentOutOfRangeException(nameof(fooType));
}
```

**Expected Behavior**:
Calling GetFooUsingLocalFunction should behave the same as GetFooUsingRegulatMethod

**Actual Behavior**:
Calling GetFooUsingLocalFunction throws a BadImageFormatException

System.BadImageFormatException occurred
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by jcouv** [comment] 2017-08-24 06:33
FYI @agocke for triage. Thanks

**Comment by svick** [comment] 2017-08-24 12:30
Here is simplified code that still seems to reproduce the issue:

```c#
class C
{
    void GetFooUsingLocalFunction()
    {
        dynamic dummy = null;
        GetFooFromPrototypeLocalFunction(dummy);

        void GetFooFromPrototypeLocalFunction<TFoo>(TFoo prototype)
        {
        }
    }
}
```

[When I try to decompile it in SharpLab](https://sharplab.io/#v2:D4AQTABAwgsAUAb3hFEQBYIHECmAXAMQHsiBVAZwEsA7AcwBkiBjAQwBsQBWPSo6gCgCUyVEjioJEACYBPaiwC2lJtICuChTIgBeCNVVs2AbhGTs+YkQIAnIgoAKtvETwyADjkasO3XgKnqmoImcKaSGOaEJDZ2ji4u7p7M7Fw8fAA8ACqWAHz82SQQbk4JHsLiZhBilRAAvmH1cLVAA), it causes a `NullReferenceException` in `Mono.Cecil.SignatureReader.GetGenericParameter`. I think that could help identifying what the issue is.

**Comment by agocke** [comment] 2017-08-24 19:36
Looks like a dup of https://github.com/dotnet/roslyn/issues/21317. Should be fixed in master.

**Closed by agocke** 2017-08-24 19:36 UTC
Labels: Area-Compilers
