### ISSUE TITLE
Consolidate many quick fixes to simplify class creation.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38923] opened 2019-09-27 20:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/656674/consolidate-many-quick-fixes-to-simplify-class-cre.html)._

---
<p>When I create a new class in my project, it usually needs a handful of dependencies injected via constructor. Right now I do that by typing out a constructor parameter, pushing Alt-Enter to bring up &quot;Quick Fixes&quot;, then choosing the &quot;create and initialize field&quot; or &quot;create and initialize property&quot; fix as appropriate.</p> <p>C# record types and representative constructors have spent at least half a decade in spec Hell, but I think the IDE has the tools to do this:</p> <ol>
<li>Create a new type.</li> <li>Type all of the constructor parameters.</li> <li>When I Alt-Enter and choose Quick Fixes, I want a &quot;create and initialize all&quot; quick fix that does what it says for any parameters that aren't currently initialized.</li></ol> <p>For example, suppose I had this constructor:</p> <pre>public Example(IDependency dependency, ILogger logger) {}</pre> <p>After the quick fix, this would be the result if I chose &quot;create and initialize all as fields&quot;.</p> <pre>private readonly IDependency _dependency;
private readonly ILogger _logger;

public Example(IDependency dependency, ILogger logger)
{
    _dependency = dependency;
    _logger = logger;
}
</pre><p>Similar options would exist for properties. I'd use this many times daily.</p>

---
#### Jane Wu [MSFT] on 7/23/2019, 01:53 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment] 2020-03-10 02:11
Dupe of https://github.com/dotnet/roslyn/issues/35665

**Closed by CyrusNajmabadi** 2020-03-10 02:11 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review
