### ISSUE TITLE
Compiler Deficiency: ConditionalAttribute not allowed for local functions

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#47455] opened 2020-09-04 07:40 UTC
**Version Used**: 
Whatever comes with VS 16.7.2.

**Steps to Reproduce**:

1. Create a class. Let's call it `C`.
2. Create a method in `C`. Let's call it `method1`.
3. Create a local function in `method1`. Let's call it `method2`.
4. Decorate `method1` with `[Conditional("DEBUG")]`.
4.1 Note how this produces no errors (given correct `using`'s).
5. Decorate `method2` with `[Conditional("DEBUG")]`.

**Expected Behavior**:
No CS8783. Conditional applied as per user-expectations.

**Actual Behavior**:
After step 5, produces CS8783, claiming "must be 'static' in order to use the Conditional attribute".

According to documentation at
 https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions

"Local functions are private methods"
without any mention that statement would only apply to `static` local function.

Since a local function, regardless of static or not, is a `method`, it follows they should allow the attempted attribute decoration.

That the compiler generates helper-class(es) for local non-static functions is not a valid excuse for not handling this scenario.

**Comment by PathogenDavid** [comment] 2020-09-04 15:34
[This is currently by-design](https://github.com/dotnet/csharplang/blob/ac14d87c16f28535299060d510fb4f647029a765/proposals/csharp-9.0/local-function-attributes.md):

> A local function can be made conditional in the same sense as a [conditional method](../../spec/attributes.md#the-conditional-attribute) by decorating it with a `[ConditionalAttribute]`. **A conditional local function must also be `static`.** All restrictions on conditional methods also apply to conditional local functions, including that the return type must be `void`.

(Emphasis mine.)

There [was a brief discussion of this](https://github.com/dotnet/csharplang/pull/3198#discussion_r393952497) when the spec was reviewed. It sounds like there's some concern with how conditional capturing local functions could affect things.

If you want to see this changed, you should leave a comment on the language feature issue https://github.com/dotnet/csharplang/issues/1888

**Comment by CyrusNajmabadi** [comment] 2020-09-04 16:15
Closing out as by design. If you would like the design to be changed please create a proposal at dotnet/csharplang. Thanks!

**Closed by CyrusNajmabadi** 2020-09-04 16:15 UTC
