### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit64 on PR #files - TestNamedType_InDependentProjectVBRefsCSharp

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9367] opened 2016-03-01 21:19 UTC
this failures looks like not related to my change.

PR: [#files](https://github.com/dotnet/roslyn/pull/9360/files) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4637/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestNamedType_InDependentProjectVBRefsCSharp

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment] 2016-03-07 00:40
Dupe of https://github.com/dotnet/roslyn/issues/9308

**Closed by davkean** 2016-03-07 00:40 UTC
Labels: Area-Infrastructure, Contributor Pain
