### ISSUE TITLE
Cannot paste tabs into editor anymore

### ISSUE THREAD

**Issue by levicki** [dotnet/roslyn#69124] opened 2023-07-20 11:14 UTC
Consider this code:
```
[StructLayout(LayoutKind.Sequential, Pack = 1)]
private struct WFSPINATTRIBUTES
{
	[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
	public byte[]		KeyUsage; // note two tabs
	public byte Algorithm;
	public byte ModeOfUse;
	public UInt32 CryptoMethod;
}
```
Steps to reproduce the issue:

1. Paste the code into editor then press Ctrl+Z to undo reformatting of tabs to spaces
2. Select the two tabs between `byte[]` and `KeyUsage` and press Ctrl+C
3. Select space between `byte` and `Algorithm` and press Ctrl+V

Expected behavior:
 - Space replaced by two tabs from the clipboard

Actual behavior:
 - Nothing happens

I don't want to disable reformat on paste because sometimes it is useful, but I don't want this overzealous, tab hating, behavior. Would it be possible to at least tone down the reformatter just a bit, so it doesn't reformat pasted text if it is just whitespace and / or below the certain (short) length?

**Comment by arkalyanms** [comment] 2023-08-02 22:57
@sharwell is this core editor?

**Comment by sharwell** [comment] 2023-08-03 15:00
This is a behavior introduced by Visual Studio 2015. See #24031

**Comment by levicki** [comment] 2023-08-04 03:44
> This is a behavior introduced by Visual Studio 2015. See #24031

It's not a behavior because that would imply it was intentional and / or desireable &mdash; it's a side-effect of adding Roslyn and a negative one just like every other tab formatting issue ever reported.

**Comment by sharwell** [comment] 2023-08-07 15:05
Duplicate of #24031

**Closed by sharwell** 2023-08-07 15:05 UTC
Labels: Area-IDE, IDE-Formatter

**Comment by levicki** [comment] 2023-08-07 18:46
@sharwell Great work guys, keep working on your pet projects and not supporting customers. That's gonna end up really well.
