### ISSUE TITLE
"Use Collection Expressions" suggestion still appears even with multiple target frameworks, including those that target C# versions without support for collection expressions

### ISSUE THREAD

**Issue by winscripter** [dotnet/roslyn#75807] opened 2024-11-07 18:40 UTC
This applies to all suggestions that assist with usage of collection expressions (IDE0300, IDE0301, IDE0302, IDE0303, IDE0304, IDE0305).

**Version Used**: .NET 8.0.403, Visual Studio 2022 Community 17.11.5, Windows 11 23H2 (Build 22631.2861)

**Steps to Reproduce**:

1. Create a blank class library targeting .NET 8
2. Double click on the project itself in Solution Explorer in order to modify the csproj file
3. Replace this:
```xml
<TargetFramework>net8.0</TargetFramework>
```
with:
```xml
<TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
```
If any .NET frameworks except &gt;= .NET 8.0 are not present on the device, it is okay to specify any older framework(s) as long as it targets a C# version that does not feature Collection Expressions.

After saving the csproj file, you may also experience this or more errors. Click `Reload faulted project(s)` or `Reload projects` on either of these yellow banners:
![Image](https://github.com/user-attachments/assets/bee943d5-d718-4acc-a267-985d1ffe10db)

4. Add a new source file, for example, `Foo.cs`, and paste this code:
```cs
// These usings aren't necessary if implicit usings are enabled (they are by default).
using System.Collections.Generic;
using System.Linq;

namespace AnyNamespaceHere
{
    internal static class Foo
    {
        public static IEnumerable<string> GetEmptyStringEnumerable()
            => Enumerable.Empty<string>();
    }
}
```

Notice this line:
```cs
=> Enumerable.Empty<string>();
```
Under `.Empty`, are three dots. When we hover over them, Visual Studio reports an information "IDE0301: Collection initialization can be simplified". Our project targets multiple frameworks, including .NET 8.0 which supports collection expression.

When we press Ctrl + . to show potential fixes, we don't see any potential fixes related to fixing this IDE0301 information.

If we change `=> Enumerable.Empty<string>();` to `=> [];` in order to fix the IDE0301 information, Visual Studio reports two errors:
![Image](https://github.com/user-attachments/assets/8d5315b7-e72f-4357-b158-9861f116992f)

This results in a confusion: the project targets .NET 8.0, 7.0, and 6.0. .NET 8.0 is the only framework that supports C# 12 which introduces collection expressions, because of this Roslyn reports the IDE0301 information. But if we manually fix this to "[]", the IDE0301 information is gone, but also, two errors are reported because while this is a fix for .NET 8 due to it being the only framework in the project that supports C# 12, it is not the case for .NET 7.0 and 6.0.

Because of this, I believe the IDE0301 information should not be reported at all if the project targets framework(s) that do not target C# 12 or later by default.

**Diagnostic Id**: [IDE0301](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0301) (Use collection expression for empty), [IDE0300](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300) (Use collection expression for array), [IDE0302](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0302) (Use collection expression for stackalloc), [IDE0303](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0303) (Use collection expression for Create()), [IDE0304](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0304) (Use collection expression for builder), [IDE0305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0305) (Use collection expression for fluent).

**Expected Behavior**: IDE0301 (and other diagnostics related to collection expressions) should not be reported at all because there are target frameworks that target C# versions which do not support collection expressions.

**Actual Behavior**: IDE0301 (and other diagnostics related to collection expressions) is reported because there is a target framework that supports a C# version that supports collection expressions, however, other target frameworks don't.

**Comment by CyrusNajmabadi** [comment] 2024-11-07 19:27
Diagnostics are computed on a per-compilation level and have no knowledge of any other compilations (this information is literally not available when the analyzer runs).  

This has been the design for analyzers since their inception, and there are no easy ways around this.  Note that you will get the same expereince building from the command line for any diagnostics you have elevated.  There is no way for the analyzers to know that there is some *other* config where they may not apply.

**Comment by CyrusNajmabadi** [comment] 2024-11-26 03:39
Closing as by design (this is how all analyzers work)

**Closed by CyrusNajmabadi** 2024-11-26 03:39 UTC
Labels: Area-IDE, untriaged
