### ISSUE TITLE
Nuget restore on Linux fails with FileLoadException:

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10725] opened 2016-04-20 17:21 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_future_lin_dbg_unit32/211/console

```
Restore CrossPlatform.sln
10:17:36 
10:17:36 
10:17:36 Unhandled Exception: 
10:17:36 Unhandled Exception: Unhandled Exception:System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
10:17:36  (Exception from HRESULT: 0x8007001F)
10:17:36    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
10:17:36    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
10:17:36    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
10:17:36    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
10:17:36  (Exception from HRESULT: 0x8007001F)
10:17:36    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
10:17:36    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
10:17:36    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
10:17:36    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop() 
10:17:36 System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
10:17:36  (Exception from HRESULT: 0x8007001F)
10:17:36    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
10:17:36    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
10:17:36    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
10:17:36    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()
10:17:37 Restore failed
```

**Comment by jasonmalinowski** [comment] 2016-08-25 00:23
This was a dupe of #10838.

**Closed by jasonmalinowski** 2016-08-25 00:23 UTC
Labels: Area-Infrastructure
