### ISSUE TITLE
Interactive Window Unit Test Flaky 

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#7991] opened 2016-01-15 20:53 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2751/consoleFull#14857372926baeffce-8504-4013-981e-7f26b5265816

[The PR](https://github.com/dotnet/roslyn/pull/7934#issuecomment-172045526) that kicked off this build made no code changes.

**Comment by davkean** [comment] 2016-01-16 02:28
Dupe of https://github.com/dotnet/roslyn/issues/7976.

**Closed by davkean** 2016-01-16 02:28 UTC
Labels: Area-Interactive, Bug, Flaky, Resolution-Duplicate, Test
