### ISSUE TITLE
VS replaces DateTime with Date

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39172] opened 2019-10-09 22:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/759557/vs-replaces-datetime-with-date.html)._

---
[regression]
If you type (in VB.Net):

mydatetimevariable = new datetime(

it is automatically replaced by:

mydatetimevariable = New Date()

---
#### Visual Studio Feedback System on 10/7/2019, 02:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2019-10-15 19:48
This may be intentional behavior inside the line commit handling for VB. `Date` is a VB-specific alias for `DateTime`, so it may recognize the framework type and automatically substitute the language-specific type.

**Comment by CyrusNajmabadi** [comment] 2024-10-20 20:21
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-20 20:20 UTC
Labels: Area-IDE, Developer Community
