### ISSUE TITLE
Code analysis settings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37849] opened 2019-08-08 23:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/488819/code-analysis-settings.html)._

---
<p>I miss the location where I can alter the code analysis settings in visual studio 2019 Version 16.0.0. Preview 4.2 on my .net core project</p><p>Would be nice to understand where it has gone to. </p>

---
#### Jane Wu [MSFT] on 3/14/2019, 02:21 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by mavasani** [comment] 2019-08-19 14:34
This is a duplicate of https://developercommunity.visualstudio.com/content/problem/317861/code-analysis-settings-doesnt-load.html. Quoting couple of comments from that thread which should be helpful:

_Let me provide some background here. We originally fixed the issue filed here, so that the Code Analysis settings page would correctly work for solution with NetCore/NetStandard project. However, further down the line we identified a bunch of issues with this property page:_

_1) This page has quite a few functional and accessibility bugs, has very less customer usage telemetry and is highly undiscoverable._

_2) This page is not as rich as the functionality available in the per-project Code Analysis properties page tab, which is available for both C++ projects and .NET projects based on older csproj format. For .NET projects based on newer project file format (including netcore/netstanard projects), https://github.com/dotnet/project-system/issues/266 tracks adding the same property page. Please vote on that issue if that is the desired piece for you._

_Based on the above factors, we decided to deprecate this page._

_Let me try to summarize the recommendations for existing users of the Code Analysis Settings page:_

_1) Sharing a ruleset across multiple/all projects in a solution or a repo: Follow the approach suggested in https://developercommunity.visualstudio.com/comments/435584/view.html and define a property group with CodeAnalysisRuleSet property in a shared props/targets file or Directory.props/Directory.targets file._

_2) Viewing or updating ruleset for a specific project: Use the much richer per-project Code Analysis property page, which is available for C++ projects and .NET projects based on older project file format. For .NET projects based on newer project file format (including netcore/netstanard projects), https://github.com/dotnet/project-system/issues/266 tracks adding the same property page. Please vote and/or comment on that issue if that is the desired piece for you so its prioritized appropriately._

**Closed by mavasani** 2019-08-19 14:34 UTC
Labels: Area-Analyzers, Question
