### ISSUE TITLE
Intellisense mismatches "i" letter when current culture is Turkish (tr-TR)

### ISSUE THREAD

**Issue by alatas** [dotnet/roslyn#29938] opened 2018-09-17 13:57 UTC
**Version Used** : 15.8.4

In Turkish, i and I characters are different. i is the lowercase form of İ, and I is the uppercase form of ı. Because of this disparity, Intellisense mismatches "i" letter when system culture is set to Turkish (tr-TR). 

When you type "if", Intellisense match any word starts with i but not I (ex. "If"). When you type "if" and space, it changes "if" to smth else that matches first but not "If". 

It becomes very annoying especially in VB, because "if" starts with uppercase in VB. That does not cause much problem in C#.

I identified the source code, found the problem and corrected it. It's needed to change string match culture to invariant. I will open a pull request and refer to this issue.

**Comment by CyrusNajmabadi** [comment] 2018-09-17 16:59
Interesting.  Tagging @dpoeschl @Pilchie .  I know we have special handling in the IDE *exactly* for turkish-i.  So i'm wondering what we got wrong here.  For example, we have tests for AlwaysUseEnglishUSCultureWhenFixingVariableNames_TurkishDottedI or TestMatchDottedUpperTurkishI.  

@alatas None of the team speaks Turkish, so it would be great if you could help us understand what about the current turkish handling code is wrong, and what the right way is to do things that appropriately works across other cultures and for turksh.

Thanks!

**Comment by alatas** [comment] 2018-09-17 19:58
@CyrusNajmabadi 
thank you for your comment. I looked only intellisense completion code and found that string comparison made with ["CurrentCulture".](https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/Core/Portable/Completion/CompletionService.cs#L152) It causes the problem in Turkish. Because as I told, I and i are two different letter in Turkish as "If" and "if" are different words in Turkish.

I changed this line to "InvariantCulture" and the problem goes away. But, this fix may cause new problems with another culture. I didn't run the tests against this fix yet. I will analyze your special handling code for Turkish and try to offer a better solution for this problem.

**Comment by CyrusNajmabadi** [comment] 2018-09-17 20:01
@alatas Thank you *so* much!  That would be super helpful as no one on the team speaks/reads turkish, and so we've had to do our best here based on bug reports of the past.  Having someone actually work with us to help us here would be fantastic.

It would be especially useful to know if our existing tests are actually demonstrating "good" behavior.  Or if they're actually validating existing behavior which is actually not doing things properly.

If we can get this 'right' once and for (especially with appropriate test coverage) that would be phenomenal!

**Comment by CyrusNajmabadi** [comment] 2018-09-17 20:02
@jinujoseph This has been an area we've traditionally struggled with.  Can this be assigned to someone who has time to work with the community on this.  It would definitely be good to have immediate attention on this while @alatas is available to share his insight and his valuable time.  

Thanks!

**Comment by CyrusNajmabadi** [comment] 2018-09-17 20:05
@sharwell @dpoeschl and @tmeschter  as well for community/internalization/globalization pillars.

**Comment by CyrusNajmabadi** [comment] 2018-09-17 20:14
There are several places that we likely need to examine for correctness:

https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/Core/Portable/Completion/CompletionService.cs#L152
https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Controller.Session_FilterModel.cs#L382
https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Controller.Session_FilterModel.cs#L496
https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/EditorFeatures/Core.Wpf/Completion/Presentation/RoslynCompletionSet.cs#L242-L243

Note: we have specific code in completion to try to bridge the worlds between the user's culture, and the fact that APIs are almost always written with a latin script.  That code is here:

https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/Core/Portable/Completion/CompletionHelper.cs#L101-L111

It may be hte case that that code is incorrect and screwing things up. Or it may be the case that that code is doing the right thing, and these *other* locations need to do something similar.

**Comment by dpoeschl** [comment] 2018-09-18 18:16
Thanks for the report @alatas! Like Cyrus said, we'd really love to get this right. It would seem we _thought_ we got it right (by the presence of passing unit tests that Cyrus mentioned), but are probably mistaken. If you're able to help us get it right, that would be amazing too. Cyrus offered some starting points for investigation, and we should definitely add some unit tests for the cases where our current approach is known to be insufficient. That might be a good starting point regardless -- even if we don't get this fixed right away, documenting _scenarios_ that are broken in the form of skipped unit tests would be super valuable.

FYI @tmeschter for the Globalization aspect / input / tracking.

**Comment by alatas** [comment] 2018-10-09 09:32
@dpoeschl @CyrusNajmabadi 
I created a new pull request #30391. I changed and test the lines we discussed before. And I also reviewed the Turkish related tests. I added new ones and synced all of them between C# and VB. Some older tests were only added to C#, not VB. 

It's now working as expected in Turkish culture settings.

**Comment by Neme12** [comment] 2018-10-09 10:07
I think @alatas is saying that the fact that completion uses current culture for comparison is the problem, because the vast majority of APIs (and all language constructs) are in English, so you'd expect English rules to apply to it. Is that correct?

**Comment by gafter** [comment] 2018-10-09 16:59
String matching should *not* use the invariant culture. That culture has bugs that will never be fixed because it is, *ahem*, invariant.

See `https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CaseInsensitiveComparison.cs` for one correct approach.

**Comment by rjmholt** [comment] 2018-11-06 19:32
@gafter Can you elaborate on those bugs -- is there a writeup somewhere describing what the issues are and what the best approach is for getting around them without rewriting encoding and localisation libraries?

**Comment by guneyozsan** [comment] 2018-11-12 12:19
For me auto-completion works well but new field name suggestions when declaring a field are incorrect. It was working fine until a couple of months ago.

I also like to provide my system settings because even though my system and OS lanugage is English and only region setting is Turkish (set only for date format and time zone actually) I still suffer from this problem. This is pretty frustrating as I frequently have to delete auto-completions and retype them.

**My Windows 10 settings:**
Region: Turkey
Windows display language: English
Keyboard: Turkish Q (added under English language).

For example on Visual Stuido 2017 C#,

**What happens is:**
- Typing `private Image` incorrectly suggests `ımage` instead of `image` as field name (unexpected and incorrect).
![intellisense-image-bug-3](https://user-images.githubusercontent.com/19275187/48345854-460e0780-e68a-11e8-9e53-68e16c6d6b84.jpg)
- Typing `private i` suggests correct class names that start with `I` (eg. `Image`)
![intellisense-image-bug-1](https://user-images.githubusercontent.com/19275187/48345885-5f16b880-e68a-11e8-9993-ea3775fa75cf.jpg)
- Typing `private ı` suggests correct class names that start with `I` (eg. `Image`) (incorrect for English as ı does not exist in English but helpful).
![intellisense-image-bug-2](https://user-images.githubusercontent.com/19275187/48345895-65a53000-e68a-11e8-8bbe-9088ea0585f3.jpg)

**Expected behavior is:**
- Typing `private Image` should suggest `image` as field name.
- Typing `private i` should suggest `Image` as field name.
- Typing `private ı` should not suggest any class names (but helpful if it does so it is open to debate).

**Discussion:**
I think the confusion here is the behavior expected is different for the conversion of the direction. That is, for a Turkish user typing English on a Turkish keyboard: 
- `ı` to `I` is the expected and helpful behavior. As there is no `İ` in English, converting `i` to `I` instead of `İ` is good,
- but `I` to `ı` is unexpected and frustrating behavior (as there is no `ı` in English, **converting** `I` to `ı` instead of `i` is bad).

So I think,
** For auto-completion:**
- `lower case` to `UPPER CASE` must use results from culture `en-US`, invariant or similar behavior, and should include results for `tr-TR`, but `tr-TR` is not necessary.
- `UPPER CASE` to `lower case` must use culture `en-US`, invariant or similar behavior.

** For field name suggestions when declaring fields:**
- Both way conversion between `lower case` and `UPPER CASE` must use culture `en-US`, invariant or similar behavior.

I don't get why culture `tr-TR` is subject to this feature on a system with English language just because region settings and keyboard is Turkish.

**Closed** 2019-10-23 23:24 UTC
Labels: Area-IDE, Bug, Tenet-Globalization
