### ISSUE TITLE
CodeCompletion and internal classes

### ISSUE THREAD

**Issue by Serg2DFX** [dotnet/roslyn#7771] opened 2016-01-04 20:04 UTC
Hello, guys!
It seems strange to use internal classes in "Microsoft.CodeAnalisys.Completion".
It seems to me that this functionality should be open.

**Comment by davkean** [comment] 2016-01-08 18:04
@Serg2DFX By default we don't automatically make all types public.

What are you trying to do with these APIs? This will help us prioritize, and help us design something appropriate for your situation.

**Comment by Serg2DFX** [comment] 2016-01-08 21:18
I saw an example of autocompletion in c # with Roslyn (https://github.com/aelij/roslynpad).
I replaced the nested assembly to nuget packages. But found that the changed classes visibility.

At the moment I am looking at two ways to solve:
1. Make a fork of the project and change the visibility roslyn have used classes.
2. Make a fork and add the assembly attribute [assembly: InternalsVisibleTo (...

Maybe it's not the best solution.

**Comment by Pilchie** [comment] 2016-01-11 17:10
Dupe of #3538.

**Closed by Pilchie** 2016-01-11 17:10 UTC
Labels: Area-IDE, Feature Request
