### ISSUE TITLE
Complete IDE binding failure for type in PCL in Reflection call

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1720] opened 2015-04-01 01:26 UTC
The `SemaphoreLight` symbol in [this line](https://github.com/SLaks/DroidMaster/blob/193b31902e8bbc05f584fc3762441fd95e58449a/DroidMaster/Core/SshDeviceScanner.cs#L21) gets no IDE recognition.

IntelliSense completes the symbol, and it's highlighted as a class, but it has no quick info, no parameter help, and no IntelliSense if you add a `.` after the constructor call.

The issue only happens at that exact callsite; not for other (even extremely similar) references to the type.  No errors are shown, no exceptions are thrown within the IDE, and the code compiles and runs fine.

**Comment by SLaks** [comment] 2015-04-01 01:27
This happens across VS restarts and on multiple machines.

**Comment by Pilchie** [comment] 2015-05-01 02:25
@SLaks: does this still repro after applying the workaround for the PCL Facade referencing issue?

**Comment by SLaks** [comment] 2015-05-01 02:37
Yes, and also on yesterday's RC build.

**Comment by Pilchie** [comment] 2015-05-01 02:38
Okay, thanks for the confirmation.

**Comment by brettfo** [comment] 2015-05-04 16:02
The call to `semanticModel.GetSymbols()` in AbstractSemanticQuickInfoProvider.cs::BindTokenAsync() is returning an empty set.  Re-assigning to compiler for the symbol binding failure with a simplified repro.

Paste the following in a C# editor and place the cursor over the symbol marked by `[|` and `|]` to invoke quick info.  Result; no symbols were found which means no quick info.

``` C#
class C
{
    public C(int i)
    {
        typeof(C).GetField("").SetValue(null, new [|C|](0));
    }
}
```

**Comment by SLaks** [comment] 2015-05-04 16:04
That's fascinating.
Does it really need the `int i` parameter?

**Comment by brettfo** [comment] 2015-05-04 16:07
No, the parameter isn't required but I decided to keep it in the repro because it makes it a little more obvious that something went wrong.  Also, this appears to be a C#-only issue; the symbols are appropriately resolved in VB.

**Comment by SLaks** [comment] 2015-05-04 16:15
What do you mean?

I wonder if this has something to do with the WinRT TypeInfo APIs, since this seems to be specific to calls to Reflection.

**Comment by brettfo** [comment] 2015-05-04 16:40
It doesn't appear to be WinRT-specific because it also repros from a normal C# console application.  I suspect it has something to do with the shape of the parse tree, possibly stemming from the root of the expression being the `typeof` operator.  Trying a similar case with `nameof` (e.g., `nameof(C).CompareTo(new C())`) works as expected, but parsing `nameof` results in a very different tree than parsing `typeof` (by design since `nameof` is parsed as a normal function invocation then special-cased later on where `typeof` is it's own expression type.)

**Comment by TyOverby** [comment] 2017-02-03 20:48
This was a bug in typeof binding that has since been fixed.  I added a regression test at https://github.com/dotnet/roslyn/pull/14209

**Closed by TyOverby** 2017-02-03 20:48 UTC
Labels: Area-Compilers, Bug, Concept-API, Investigation Required
