### ISSUE TITLE
Primary ctor parameter writes should be assumed necessary even if not read later in the method

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#68904] opened 2023-07-06 22:39 UTC
**Version Used**: VS 17.7.0 Preview 2.0

**Steps to Reproduce**:

```cs
class MyClass(int value)
{
    public int Get()
    {
        var x = value;
        value++; // IDE0059: unnecessary assignment of a value to 'value'
        return x;
    }
}
```

**Expected Behavior**: No diagnostic. Behavior should be similar to if a field 'int value' were explicitly declared in 'MyClass'.

**Actual Behavior**: IDE0059 is reported

Relates to https://github.com/dotnet/roslyn/issues/65697

**Comment by RikkiGibson** [comment] 2023-08-01 21:00
Ping @arkalyanms @dotnet/roslyn-ide for triage

**Comment by arkalyanms** [comment] 2023-08-01 21:12
Starting with Cyrus for first look.

**Comment by mavasani** [comment] 2023-09-01 03:29
Duplicate of #69643. Verified that this was fixed with #69748

**Closed by mavasani** 2023-09-01 03:29 UTC
Labels: Area-IDE, Feature - IDE0059
