### ISSUE TITLE
Inline temporary variable removes comment.

### ISSUE THREAD

**Issue by thorgeirk11** [dotnet/roslyn#1863] opened 2015-04-08 13:04 UTC
I encountered this when I was inlining a variable with alot of comments around it:

```CSharp
{
    var myList = new List<int>();
    var temp = myList;

    //Important comment.
    temp.Add(1);
    temp.Add(2);
}
```
When I inline the foo temp variable the important comment gets removed.

![image](https://cloud.githubusercontent.com/assets/2693474/7045676/b8d11890-ddef-11e4-8ebb-7ece41e40eb6.png)

**Comment by balajikris** [comment] 2015-04-08 16:42
reproes with latest code from dotnet/master

**Comment by Pilchie** [comment] 2015-04-08 16:52
Similar to #1017.

**Comment by brettfo** [comment] 2015-04-08 17:26
Confirmed, dupe of #1017.

**Closed by brettfo** 2015-04-08 17:26 UTC
Labels: Area-IDE, Bug
