### ISSUE TITLE
Copilot 

### ISSUE THREAD

**Issue by ts295983632** [dotnet/roslyn#62049] opened 2022-06-21 08:11 UTC
任务失败：激活语言客户端：Copilot 
任务失败， 并显示消息：Request 
start Service failed with message：Failed 
to load message bundle.See console for 
details.(Error Kind：Error HResult： 
80131500)

**Comment by davidwengier** [comment] 2022-06-21 11:04
This repository does not have anything to do with Copilot unfortunately, so I'm going to close this as a duplicate of https://github.com/github-community/community/discussions/17934

**Closed by davidwengier** 2022-06-21 11:04 UTC
Labels: Area-IDE, untriaged
