### ISSUE TITLE
Only base positional Record parameters shown as used

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#47174] opened 2020-08-27 04:16 UTC
**Version Used**: visual studio 16.8 preview 2

**Steps to Reproduce**:

```csharp
    public record Base(int I) { }
    public record Derived(string S) : Base(42) { }
```

**Expected Behavior**:
both `I` and `S` are shown as used.

**Actual Behavior**:
IDE0060:
Remove unused parameter 'S' if it is not part of a shipped public API

**Comment by jcouv** [comment] 2020-09-15 02:04
Closing as duplicate of https://github.com/dotnet/roslyn/issues/47142

**Comment by jcouv** [comment] 2020-09-15 02:05
Ah, my bad. Different issue (misread IDE1006 and IDE0060). Re-opened.

**Closed** 2020-09-19 22:04 UTC
Labels: Area-IDE, Bug, New Language Feature - Records, Urgency-Soon
