### ISSUE TITLE
Nullable analysis fails assertions when running on Roslyn.sln in debug build

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#51403] opened 2021-02-22 23:33 UTC
Version 16.10.0 Preview 1.0 [31015.32.main]

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Visited 30 nodes, expected to visit 25



   at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Verify(ImmutableDictionary`2 analyzedNullabilityMap, SnapshotManager snapshotManagerOpt, BoundNode node) in D:\R3\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 43

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, Boolean requiresAnalysis) in D:\R3\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1170

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols) in D:\R3\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1125

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, VariableState nullableInitialState, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) in D:\R3\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1724

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in D:\R3\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1038

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in D:\R3\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 524

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0() in D:\R3\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 414

   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\R3\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 139

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by RikkiGibson** [comment] 2021-02-23 19:39
One project where building with a debug bootstrap compiler causes this issue is `Microsoft.CodeAnalysis.EditorFeatures.UnitTests.dll`.

**Comment by CyrusNajmabadi** [comment] 2021-02-25 01:07
This is affecting my ability to dogfood roslyn :)

**Comment by CyrusNajmabadi** [comment] 2021-02-25 01:07
Uploading dump now.

**Comment by jcouv** [comment] 2021-02-25 01:10
See https://github.com/dotnet/roslyn/issues/51461 for more details (dump, assertion, triggering syntax).

**Comment by CyrusNajmabadi** [comment] 2021-02-25 01:11
Dump is here in case it is needed: https://microsoft.sharepoint.com/:u:/t/ManagedLanguagesIDE/ESYj0VoV8BBBpW0IddZoWdEB29MiAFkJ3L-kdu1gtFUK4w?e=yCELag

**Comment by jaredpar** [comment] 2021-03-03 16:40
@333fred can you get to the bottom of the asserts here? Once you have a fix for this I can add a small change to the PR that allowed this assert gap to get merged into the code base.

**Comment by 333fred** [comment] 2021-03-03 22:41
Alright, so looking at @CyrusNajmabadi's heap dump I've created a repro. However, there's an important thing here: that's bad code. Cyrus's backtrace includes a bad expression involving overload resolution failure, which likely isn't the same issue as this where the bootstrap build fails. I'll keep looking into this one to see if I can find a repro involving good code, but at first guess I don't think they're necessarily related (especially since Cyrus's case hits an earlier assert than Tomas's does).

**Comment by 333fred** [comment] 2021-03-03 23:02
@RikkiGibson I was unable to reproduce by building current master (24c3b8ca4a7) with `.\build -bootstrap`. Is there a heap dump somewhere or other instructions?

**Comment by RikkiGibson** [comment] 2021-03-03 23:14
You may need to specify -bootstrapConfiguration Debug

**Comment by 333fred** [comment] 2021-03-04 01:45
I've tracked down the cause of this bug, which is mishandling of target-typed conditional expressions in the nullable walker. Among other things, it causes this code to not warn:

```cs
using System;
#nullable enable
public class C {
    public void M(bool b) {
        Func<string> s = b ? () => null : () => "";
        s().ToString();
    }
}
```

**Comment by 333fred** [comment] 2021-03-04 01:46
It also appears to affect other target-typed scenarios like switch expressions, this does not warn either:

```cs
using System;
#nullable enable
public class C {
    public void M(bool b) {
        Func<string> s = b switch { true => () => null, false => () => "" };
        s().ToString();
    }
}
```

**Comment by 333fred** [comment] 2021-03-04 02:24
Very likely the same cause as https://github.com/dotnet/roslyn/issues/49735

**Closed** 2021-03-19 21:01 UTC
Labels: Area-Compilers, Bug, Language-C#, New Language Feature - Nullable Reference Types
