### ISSUE TITLE
CodeFormatter crashes during 'ExplicitThis' phase when running on Roslyn.sln.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14806] opened 2016-10-29 00:22 UTC
C:\GitHub\codeformatter [master ≡]> .\bin\CodeFormatter\Debug\CodeFormatter.exe /nounicode /copyright:c:\temp\copyright.txt C:\GitHub\roslyn-internal\Open\Roslyn.sln /rule:FormatDocument,ReadonlyFields,FieldNames,FormatDocument,ExplicitVisibility,Copyright
Roslyn.sln
        Syntax Pass
        Local Semantic Pass

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.Lookup(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupBasicName(LookupResult lookupResult, IdentifierNameSyntax basicNameSyntax, Binder binder, DiagnosticBag diagBag, Boolean& reportedAnError)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupTypeOrNamespaceSyntax(LookupResult lookupResult, TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean& reportedAnError, Boolean unwrapAliases, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceComplexParameterSymbol.CreateFromSyntax(Symbol container, ParameterSyntax syntax, String name, SourceParameterFlags flags, Int32 ordinal, Binder binder, CheckParameterModifierDelegate checkModifier, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.DecodeParameterList(Symbol container, Boolean isFromLambda, SourceMemberFlags modifiers, SeparatedSyntaxList`1 syntax, ArrayBuilder`1 params, CheckParameterModifierDelegate checkModifier, DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.DecodeParameterList(Symbol container, Boolean isFromLambda, SourceMemberFlags modifiers, ParameterListSyntax syntaxOpt, DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNonPropertyAccessorMethodSymbol.GetParameters(SourceModuleSymbol sourceModule, DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNonPropertyAccessorMethodSymbol.EnsureSignature()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNonPropertyAccessorMethodSymbol.get_ReturnType()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-0._Lambda$__1(NamespaceOrTypeSymbol typeOrNamespace)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__80-1._Lambda$__0()
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by CyrusNajmabadi** [comment] 2016-10-29 00:23
Looks like some sort of bug in our Type-Circuilarity detection logic.

**Comment by CyrusNajmabadi** [comment] 2016-12-16 21:51
Shouldn't this be assigned to someone so it gets looked at?  @gafter @jaredpar ?

**Comment by TyOverby** [comment] 2017-06-12 22:02
I believe that this is a duplicate of https://github.com/dotnet/roslyn/issues/10211

**Comment by TyOverby** [comment] 2017-06-12 22:33
Closing as duplicate of https://github.com/dotnet/roslyn/issues/10211

**Closed by TyOverby** 2017-06-12 22:33 UTC
Labels: Area-Compilers, Bug
