### ISSUE TITLE
VS2019 C# Interactive Window garbled

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#49491] opened 2020-11-19 06:27 UTC
**Version Used**: 
![image](https://user-images.githubusercontent.com/4510984/99629528-182add00-2a73-11eb-8672-179affa640d8.png)

**Steps to Reproduce**:

1. Just open interactive window.

**Expected Behavior**:

Show the readable words.

**Actual Behavior**:

Show a part of garbled.

**Screenshot**

![image](https://user-images.githubusercontent.com/4510984/99629662-54f6d400-2a73-11eb-89a0-553f241bdfa7.png)

**Comment by jinujoseph** [comment] 2020-12-09 19:49
Duplicate of #48874

**Closed by jinujoseph** 2020-12-09 19:49 UTC
Labels: Area-Interactive, untriaged
