### ISSUE TITLE
BUG! VS Randomly Inserts Intellisense into my code NOT where I'm editing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51702] opened 2021-03-05 18:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/BUG-VS-Randomly-Inserts-Intellisense-in/1344821)._

---
<p>[severity:I’m unable to use this version] [regression] [worked-in:Unsure.  Started about 10 days ago.]<br>
When editing javascript block in a .CSHTML page, Intellisense will randomly insert characters into random locations in my code, breaking the code.<br>
This is somewhat random, </p><p>Usually I don’t catch the insert happening, and when the build breaks, I find these random keywords inserted in the middle of some other line of code.</p><p>See attached video</p>

---
#### Feedback Bot on 2/21/2021, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/22/2021, 10:24 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Mine Starks [MSFT] on 2/22/2021, 10:50 AM: 

<p>Thanks for the report. I can confirm that I can repro this bug locally. We will continue to investigate.</p>

#### Feedback Bot on 2/26/2021, 10:48 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by uniqueiniquity** [comment] 2021-03-05 18:44
I can repro with current bits in 16.10.
When the item is committed, our implementation of Microsoft.CodeAnalysis.Completion.CompletionProvider.GetChangeAsync doesn't get invoked.
However, an exception occurs with the following stack when the item's text is inserted: 
<description>System.ArgumentException: The specified ITextSnapshot doesn&apos;t belong to the correct TextBuffer.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.Commit(IAsyncCompletionSession session, Document document, CompletionService completionService, ITextBuffer subjectBuffer, CompletionItem roslynItem, TextSpan completionListSpan, Nullable`1 commitCharacter, ITextSnapshot triggerSnapshot, CompletionRules rules, String filterText, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.TryCommit(IAsyncCompletionSession session, ITextBuffer subjectBuffer, CompletionItem item, Char typeChar, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.&lt;&gt;c__DisplayClass111_2.&lt;CommitItem&gt;b__4()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow, Predicate`1 exceptionToIgnore, Predicate`1 exceptionToHandle)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>

**Comment by minestarks** [comment] 2021-03-05 19:42
More notes and repro under https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1281332 - please note this is a regression from 16.7.

**Comment by minestarks** [comment] 2021-03-09 19:34
@jinujoseph any chance this can be investigated soon? The attached ticket has some video and the experience is rather bad.

**Comment by genlu** [comment] 2021-03-11 01:51
@minestarks  Hmm, I tried it a few times, but couldn't repro it with the code provided in the feedback item with 16.10.0 Preview 2.0 [31109.395.main]


![cshtml](https://user-images.githubusercontent.com/788783/110723462-ed52c900-81c8-11eb-9b3f-a71078302828.gif)

**Comment by minestarks** [comment] 2021-03-11 01:56
@genlu do you have the new Razor language service  turned off in the Preview Features pane? It’s on by default in internal builds but this only repros with the old one.

**Comment by genlu** [comment] 2021-03-11 19:37
@minestarks Yup, that's it. I can repro it now, investigating

**Comment by ErikvdBurgwal** [comment] 2021-03-31 07:32
Hi @genlu , how is your investigations proceeding? 
I hope you are close to a resolution, as this issue is creating bugs in my code every week..
Thanks!

**Comment by Shortdude18** [comment] 2021-04-08 14:45
Hello, 
I am also seeing the issue happen when visual studio tries to complete for this block of code in CSHTML/RAZOR
 $.ajax({
url: '@Url.Action("ProcessPayment","Home")', 
  })
After entering '@Ur' and pressing tab for visual studio intellisense to select the 'Url' item, an exception is thrown at the top ribbon advising "the specified ITextsnapshot doesn't belong to the correct TextBuffer", and what i was typing ('@Ur') is thrown into the code about 10 lines down randomly. Which causes the code of course to break.  Thanks for looking into it!

**Comment by furkanekinci** [comment] 2021-05-07 19:22
![B7370f89ca6cd45b5bc49c460fab507be637557997532460831_3mKz9](https://user-images.githubusercontent.com/1109518/117498280-44cfa400-af82-11eb-8b6f-b1a19074b5ad.gif)

After first occursion of issue, following exception message appear above the tabs (_maybe not related_):

> An exception of type **_ArgumentOutOfRangeException_** has been encountered. This may be caused an extension.

![Bb7d4177844914af3a10f8229c0b7ba62637557998062456475_ilakE](https://user-images.githubusercontent.com/1109518/117498284-45683a80-af82-11eb-9cbc-f29f2a227ee9.png)

**Comment by CyrusNajmabadi** [comment] 2021-05-07 19:26
can you give us the callstack of that exception?  You should be able to find that by cliking on that blue text.  Also paging @NTaylorMullen

**Comment by furkanekinci** [comment] 2021-05-07 19:35
@CyrusNajmabadi clicking exception shows following message box.

![devenv_AxZ64sPdE0](https://user-images.githubusercontent.com/1109518/117499703-44d0a380-af84-11eb-8248-34f85ac646cb.png)

Log file content zipped as attached
[Activity Monitor Log_xml.zip](https://github.com/dotnet/roslyn/files/6443904/Activity.Monitor.Log_xml.zip)

I hope it helps,

**Comment by NTaylorMullen** [comment] 2021-05-07 20:19
Looks like CoreEdit's commit manager is exploding somehow. Also @CyrusNajmabadi for clarity, this is the old Razor editor and it's using projections if it helps

**Comment by DanielKeeley** [comment] 2021-07-12 14:31
When I am writing in cshtml, intellisense suggests an autocomplete, I press enter and it usually completes my word for me. Randomly though it doesn't complete my word, I later find that it has actually placed the completed word in a random place in the document, either at the end of a line or in-between text.
![image](https://user-images.githubusercontent.com/87320487/125305445-3f962900-e326-11eb-8553-f9cb5ddbae77.png)

**Comment by Shortdude18** [comment] 2021-07-12 15:02
Yep, i'm still seeing this as well, very frustrating especially when it
adds the text in the middle of a literal string.

**Comment by ErikvdBurgwal** [comment] 2021-07-12 17:47
Yes, me too. I can confirm that it still happens with v16.10.3, it broke my code today.

**Closed** 2021-07-30 19:03 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense, Investigation Required
