### ISSUE TITLE
Compiler & VS crash repro

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#39566] opened 2019-10-29 17:17 UTC
**Version Used**:  VS 16.3.5 (also tested with 16.3.6, same result)

**Steps to Reproduce**:

Use the following code. I cut out a whole bunch of it, and what's left seems necessary, I couldn't find another line to delete and keep the compiler crashing.

```c#
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1 {
    public class Class1 {
        static Class1 () {
            using var conn = new Connection ("");

            using (var cmd = new Command ("", conn)) {
                X = Convert.ToInt32 (cmd.ExecuteScalar ());
            }

            new Thread (() => {
                using var conn = new Connection ("");
                while (true) {
                    DebugRIDItem[] GetDebugRIDItems (string tableType) {
                        using var dt = new DataTable ();
                        var adapter = new Adapter ("", conn);
                        return null;
                    }
                }
            });

        }

        public static int X { get; set; }
    }

    public class DebugRIDItem { }
    public class CIOSSettings { public static bool IOSDebugLog { get; set; } }
    public class Connection : IDisposable {
        public Connection (string s) { }
        public void Dispose () { }
    }

    public class Command : IDisposable {
        public Command (string s, Connection c) { }
        public object ExecuteScalar () => null;
        public void Dispose () { }
    }

    public class Adapter : IDisposable {
        public Adapter (string s, Connection c) { }
        public void Dispose () { }
    }

}
```

**Comment by myblindy** [comment] 2019-10-29 17:38
I should mention this was compiled under .Net Framework 4.6.2, not .Net Core. I edited the project manually with `<LangVersion>preview</LangVersion>`, to use the C# 8 `using` variable modifier. 

I'm fairly certain it behaves identically on .Net Core with C# 8 too, but I've only tested it on .Net Framework.

**Comment by agocke** [comment] 2019-10-29 23:32
Looks like this has been fixed in master. If you try VS 16.4 Preview does the issue still happen?

**Comment by myblindy** [comment] 2019-10-30 19:10
I don't know, I don't really want to install a preview VS version just to test this, I've had dreadful experiences with every preview VS since 16 at work.

If you're certain it's fixed, feel free to close this issue, but maybe also consider adding this as an unit test to prevent regressions.

**Comment by jaredpar** [comment] 2020-04-02 22:42
Confirmed this is fixed in latest.

**Closed by jaredpar** 2020-04-02 22:42 UTC
Labels: Area-Compilers, Test
