### ISSUE TITLE
SemaphoreSlimExtensions.DisposableWait fails to suppress COM message pump

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50021] opened 2020-12-16 22:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Debugger-waiting-for-validating-breakpoi/1218491)._

---
[severity:I'm unable to use this version of Visual Studio]
During debugging my solution the debugger stopped responding with a message "Validating breakpoint location..."

---
#### Feedback Bot on 10/13/2020, 10:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/15/2020, 11:18 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-12-16 22:24
The hang occurred because the following call does not suppress the COM message pump:

https://github.com/dotnet/roslyn/blob/0046fbc9554ba8971be852c8a1356de2d24d1ca3/src/Compilers/Core/Portable/InternalUtilities/SemaphoreSlimExtensions.cs#L15

A solution similar to `NoMessagePumpSyncContext` from microsoft/vs-threading should be employed to guarantee that waits on the main thread do not allow code to reenter the thread during the wait.

**Comment by CyrusNajmabadi** [comment] 2023-01-31 23:13
@sharwell You know the most about this.  So on you to decide if we take this, or decide not to and close it out.

**Comment by sharwell** [comment] 2023-02-03 19:24
@CyrusNajmabadi This is a true product bug with a known root cause and solution approach. Unless we have a short term plan to remove SemaphoreSlimExtensions altogether, we should fix this.

**Comment by CyrusNajmabadi** [comment] 2023-02-03 19:28
Ok.  Can you please assign a milestone for us to do this in.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 18:20
Closing out due to lack of response.

**Closed by CyrusNajmabadi** 2024-10-25 18:20 UTC
Labels: Bug, help wanted, Area-IDE, Tenet-Reliability, Developer Community
