### ISSUE TITLE
Roslyn fails to report nullability warning for `default` assignment to a tuple with non-nullable components

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#45200] opened 2020-06-15 20:21 UTC
**Version Used**: 

```
Branch master (14 Jun 2020)
Latest commit c0c192d by CyrusNajmabadi:
Merge pull request #45150 from Kuinox/master

Fix MakeMethodAsynchronous on ValueTask without generics.
```

**Steps to Reproduce**:

```cs
#nullable enable
class C
{
    public static void Main() => M().Item1.ToString();
    public static (C, C) M() => default;
}
```

**Expected Behavior**:
Warning for `=> default` because it returns a tuple with `null` components

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by jasonmalinowski** [comment] 2020-08-19 22:43
Duplicate of #38957.

**Closed by jasonmalinowski** 2020-08-19 22:43 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
