### ISSUE TITLE
Async method with no awaits does not require a state machine class

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#3815] opened 2015-07-02 20:44 UTC
An async method with no awaits can be emitted as return Task.Completed; or return Task.FromResult(expr); rather than generating a state machine class.

**Comment by stephentoub** [comment] 2015-07-02 21:06
It would need to handle exceptions, special-casing cancellation.  It would need to correctly handle ExecutionContext, ensuring changes don't propagate out. And it would either lose out on or need to implement task caching for basic values like the runtime does for async state machines.

**Comment by tmat** [comment] 2015-07-02 22:18
Perhaps we just need to special case scripts to avoid changing exception semantics. It doesn't make much sense to optimize this only for real async methods (as opposed to both async methods and scripts).

**Comment by svick** [comment] 2015-07-02 23:21
This sounds like a duplicate of #3659.

**Closed** 2015-08-07 22:50 UTC
Labels: Area-Compilers, Resolution-Duplicate
