### ISSUE TITLE
Nullable warnings for contravariant interface implementations

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#35817] opened 2019-05-20 18:54 UTC
**Version Used**: 
3.2.0-beta1-19266-05+04c76c9d58c7911e2fd199da145cd97bbf283438

**Steps to Reproduce**:
```C#
#nullable enable
class Program : IFoo
{
    static void Main() { }

    public bool MyEquals(object? o) => true;
}

interface IFoo
{
    bool MyEquals(object o);
}
```

**Expected Behavior**:
Compiles without warning.

**Actual Behavior**:
```
warning CS8614: Nullability of reference types in type of parameter 'o' doesn't match implicitly implemented member 'bool IFoo.MyEquals(object o)'.
```

**Comment by RikkiGibson** [comment] 2019-05-23 00:35
Dupe of #35227

**Closed** 2019-06-19 00:09 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-Duplicate
