### ISSUE TITLE
Missing space between "internal" access modifier and "class" keyword when creating a new C# class when using File Scoped Namespaces as a VS default.

### ISSUE THREAD

**Issue by nicktheone** [dotnet/roslyn#60345] opened 2022-03-23 18:53 UTC
**Version Used**: 
Microsoft Visual Studio Community 2022 (64 bit) - Current
Versione 17.1.1

**Steps to Reproduce**:

1. Create a new .NET 6 Console app.
2. Change the default namespace handling in VS (not with an .editorconfig file) from Block to File Scoped.
3. Create a new class from right-click on project>add>class...

**Expected Behavior**:
VS should generate a correctly worded file like so:
```namespace PriceChecker;
internal class Class1
{
}
```

**Actual Behavior**:
VS generates a file with a missing space/typo like so:
```namespace PriceChecker;
internalclass Class1
{
}
```

**Comment by Youssef1313** [comment] 2022-03-23 19:02
Fixed in https://github.com/dotnet/roslyn/pull/59091

**Comment by jinujoseph** [comment] 2022-04-06 20:03
Duplicate of https://github.com/dotnet/roslyn/issues/58974

**Closed by jinujoseph** 2022-04-06 20:03 UTC
Labels: Area-IDE, untriaged
