### ISSUE TITLE
Surprising `OverflowException` when casting `IntPtr` to uint-enum.

### ISSUE THREAD

**Issue by matthid** [dotnet/roslyn#42642] opened 2020-03-20 23:56 UTC
**Version Used**: VS 2019

**Steps to Reproduce**:

1. Compile and run

```csharp
    enum WindowStyles : uint
    {
        WS_POPUP = 0x80000000,
        WS_CLIPSIBLINGS = 0x04000000
    }

    class Program
    {
        static WindowStyles CastIntPtr(IntPtr t) => (WindowStyles)t;

        static void Main(string[] args)
        {
            CastIntPtr(new IntPtr(0x84000000L)); // System.OverflowException
        }
    }
```

**Expected Behavior**:

Program exits without error.

**Actual Behavior**:

Program throws `System.OverflowException`.

**Description**:

I wanted to report this because I found that very surprising. I guess the compiler assumes `Explicit(IntPtr to Int32)` is a better conversion than `Explicit(IntPtr to Int64)` and adds a cast to `(int)` before then casting to `uint`. This leads to the `OverflowException`.

What's especially surprising is that if you add a workaround (either `unchecked()` or an explicit cast to `(long)`). The IDE/SonarQube will tell you that it is not required when in reality the behavior will differ.

My suggestion would be to either fix this in the compiler (is this even possible?) or add the explicit conversions to IntPtr (if this would even help here). 

If this is expected behavior please leave a brief reasoning and feel free to close this issue.

Maybe related: #25021 #42457 #42560

**Comment by jcouv** [comment] 2020-03-23 03:09
Accidentally assigned to Chuck, but this is `uint` not `nint`...

**Comment by jaredpar** [comment] 2020-08-25 22:52
This behavior is "By Design". There is an explicit conversion from pretty much any numeric primitive type to any `enum` type. These are treated by essentially doing an explicit conversion between the numeric type and the underlying type of the `enum`. 

Given that `IntPtr` provides an implicit conversion to `int` the explicit conversion is legal here. At runtime though the `IntPtr` is overflowing trying to convert the value to `int` (which is also within the design of that type).

**Closed by jaredpar** 2020-08-25 22:52 UTC
Labels: Area-Compilers, Bug

**Comment by matthid** [comment] 2020-08-25 23:27
@jaredpar Agreed and that's what I thought, but I still feel that - when looking at the code - that something is wrong here. This is almost impossible to catch. Is it only me that feels like something needs fixing somewhere (even if it is not the compiler..)? Or has the ship pretty much sailed on this one?

**Comment by jaredpar** [comment] 2020-08-25 23:42
In terms of the language there is really nothing to be fixed here. These are the rules for how conversions have worked since pretty much C# 1.0. There is also nothing inherently wrong either with the conversions being applied here though (given the general way in which `enum` work). 

The behavior that is surprising, at least to me, is how `IntPtr` treats values like this. Why for instance does it chose to throw here which effectively means it executes in a `checked` context, when most operations do not do this? There are other cases where the overflow behavior in `IntPtr` has taken me by surprise. 

At the same time though, that ship has definitely sailed. It's unlikely the runtime team would take any changes here. Particularly so with C# 9 where we have the `nint` and `nuint` types which replace many uses of `IntPtr` like this one.

**Comment by CyrusNajmabadi** [comment] 2020-08-26 16:40
> Is it only me that feels like something needs fixing somewhere (even if it is not the compiler..)? Or has the ship pretty much sailed on this one?

You could always write an analyzer to try to find these and notify you about them

**Comment by matthid** [comment] 2020-08-26 16:55
@CyrusNajmabadi Yes, but then people will most likely already have wasted their time BEFORE installing that analyser. I don't think this can be reasonably solved outside of Microsoft, hence the issue.

But to be honest I'm fine with the answer provided
