### ISSUE TITLE
Code Style - Prefer braces when multiple lines does not show any warnings.

### ISSUE THREAD

**Issue by DasOhmoff** [dotnet/roslyn#43299] opened 2020-04-12 18:52 UTC
Hello, I have configured my code style in the following way:
![image](https://user-images.githubusercontent.com/16063186/79076970-23a86f80-7cfe-11ea-9802-1ac7caa663b2.png)

As you can see, I want to receive a warning there are unnecessary braces in a single line statement. For example in an single line if statement. But this does not seem to be working. Notice the following code:
![image](https://user-images.githubusercontent.com/16063186/79077079-edb7bb00-7cfe-11ea-8a2b-390e53841677.png)

As you can see, there are unnecessary braces, but no warning as given. I would love to receive a warning when there are unnecessary braces (just like the code style settings say).

Thank you for your help :)

**Comment by CyrusNajmabadi** [comment] 2020-04-12 18:57
@DasOhmoff We have no codestyle that pushes for *less* braces.  Instead, we specify the requirements for when braces are necessary.  

We could potentially reconsider this if there's enough demand for it.

**Comment by DasOhmoff** [comment] 2020-04-13 11:26
True, but there is code style that pushes the use of expression bodies (for example for methods, properties, etc.), which has some kind of similarity (avoiding brackets). It would be great to have this feature, thanks for you support!

**Comment by sharwell** [comment] 2020-04-14 19:58
Duplicate of #29606

**Closed by sharwell** 2020-04-14 19:58 UTC
Labels: Area-IDE, Feature Request
