### ISSUE TITLE
CodeLens causing extremely slow diagnostics/squiggle refresh in the IDE in latest VS2019 16.9 intpreview dogfood builds

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#49061] opened 2020-10-29 23:42 UTC
**Version Used**: Version 16.9.0 Preview 2.0 [30628.207.main] - Today's VS dogfood build from IntPreview channel

**Steps to Reproduce**:

1. Enlist into Roslyn repo
2. restore
3. Open Roslyn.sln
4. Open https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs
5. Wait for few minutes for error list/background processes to settle down, to avoid any unwanted noise in the repro - ideally wait for ServiceHub.RoslynCodeAnalysisService.exe to go to 0 CPU.
6. Go to the below line in the file and make repeated edits that remove and add back the comma character `,` at below line: https://github.com/dotnet/roslyn/blob/d613476f7ea7719ec68ad28025fa0f41ed29563c/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L551

**Behavior**:
consistent 5-10 seconds of refresh time for squiggles/error list after each edit

![With_CodeLens](https://user-images.githubusercontent.com/10605811/97643514-243bf580-1a05-11eb-9a7e-f6f97df5b0d4.gif)

7. Disable CodeLens from Tools/Options
8. Restart VS
9. Repeat the steps 3-6 above

**Behavior (with CodeLens disabled)**:
instantaneous refresh for squiggles/error list after each edit

![Without_CodeLens](https://user-images.githubusercontent.com/10605811/97643612-6e24db80-1a05-11eb-94af-54ccbeb3cfe0.gif)

**Comment by CyrusNajmabadi** [comment] 2020-10-29 23:46
@mavasani do you have a perf trace of what we're doing at this point?  is CodeLens/OOP churning CPU?

**Comment by mavasani** [comment] 2020-10-29 23:48
Yes, I can share it with you offline. It is basically doing FAR stuff for 50% of inclusive stacks

Name | Exc % | Exc | Inc %
-- | -- | -- | --
mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].SetResult(System.__Canon) | 0.0 | 16 | 50.8
mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.Finders.FinderLocation]].Start(!!0&) | 0.0 | 1 | 49.1
microsoft.codeanalysis.workspaces.ni!AbstractReferenceFinder.FindReferencesInTokensAsync | 0.0 | 0 | 47.6
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder+<FindReferencesInTokensAsync>d__20.MoveNext() | 0.1 | 37 | 47.6
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1+<GetValueAsync>d__15[System.__Canon].MoveNext() | 0.0 | 16 | 45.8


Name | Exc % | Exc | Inc %
-- | -- | -- | --
mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].SetResult(System.__Canon) | 0.0 | 16 | 50.8
mscorlib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.Finders.FinderLocation]].Start(!!0&) | 0.0 | 1 | 49.1
microsoft.codeanalysis.workspaces.ni!AbstractReferenceFinder.FindReferencesInTokensAsync | 0.0 | 0 | 47.6
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder+<FindReferencesInTokensAsync>d__20.MoveNext() | 0.1 | 37 | 47.6
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1+<GetValueAsync>d__15[System.__Canon].MoveNext() | 0.0 | 16 | 45.8

**Comment by CyrusNajmabadi** [comment] 2021-01-28 18:51
I don't really see any way to improve this.  Codelens is literally invoking FAR here to show information.  That FAR operation is very expensive by its very nature.  In this case, the user is in Microsoft.CodeAnalysis.  That's a project that's referenced by effectively all other roslyn projects.  They're also changing a public type.  So we need to go try to find refs for this in all other projects.  This itself would not be too bad, except that roslyn is a mixed C#/VB solution.  So in order to check potential downstream results, we end up needing to build many skeleton assemblies between those different lang projects.

My suggestion would be to just note that codelens is a very expensive system.  Or get the codelens guys to only issue their updates one diagnostics have completed.

**Comment by CyrusNajmabadi** [comment] 2021-01-28 18:52
@jinujoseph do we have a good codelens contact to discuss this issue with?

**Comment by jinujoseph** [comment] 2021-01-28 18:56
@olegtk  ?

**Comment by olegtk** [comment] 2021-01-29 00:11
Me is probably the best contact. I would suggest 2 things:
1. CodeLens is by design low priority and async indicator, so it's OK to delay or deprioritize expensive calculations, if user really need references ASAP they can invoke FAR.
2. CodeLens also has very limited display abilities, e.g. it never shows more than 99 references. Perhaps you can abandon calculation earlier if number of references exceeds the threshold.

**Comment by CyrusNajmabadi** [comment] 2021-01-29 01:55
I don't see anything we could do here for 16.9

**Comment by sharwell** [comment] 2021-03-04 00:42
This was fixed by #51395

**Closed by sharwell** 2021-03-04 00:42 UTC
Labels: Area-IDE, Bug, Regression, Tenet-Performance
