### ISSUE TITLE
[Test Failure] BasicVenus.Script Block: Commit and Smart Indent On Moving out of current line 

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#8866] opened 2016-02-18 01:30 UTC
Failure in https://github.com/dotnet/roslyn/pull/8832
Failing Build: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/281/

**Comment by Pilchie** [comment] 2016-02-19 03:54
From the log, it's possible that VS crashed :(

**Comment by balajikris** [comment] 2016-02-19 19:25
I don't see any signs of crash from the above link.

Initial thoughts - Line commit didn't happen on moving out of current line afterall, from comparing Actual vs Expected text.

~~~
14:25:24  Scenario: Script Block: Commit and Smart Indent On Moving out of current line
14:25:24 	Executing action [2/17/2016 10:15:33 PM] OpenFile
14:25:24 	Executing action [2/17/2016 10:15:33 PM] PlaceCursor
14:25:24 	Executing action [2/17/2016 10:15:34 PM] InsertText
14:25:24 	Executing action [2/17/2016 10:15:34 PM] WaitForWorkspace
14:25:24 	Executing action [2/17/2016 10:15:34 PM] PlaceCursor
14:25:24 	Executing action [2/17/2016 10:15:34 PM] SendKeys
14:25:24 	Executing action [2/17/2016 10:15:34 PM] ExecuteCommand
14:25:24 	Executing action [2/17/2016 10:15:34 PM] VerifyEditorContainsText
14:25:24 --------------------------------
14:25:24 System.Exception: Actual and expected items don't match:
14:25:24 Expected: 
14:25:24 <script runat="server">
14:25:24     Sub Foo()
14:25:24         Dim i As Integer = 100
14:25:24     End Sub
14:25:24 </script>
14:25:24 Actual: <%@ Page Language="VB" AutoEventWireup="false" CodeFile="Default.aspx.vb" Inherits="_Default" %>
14:25:24 
14:25:24 <!DOCTYPE html>
14:25:24 
14:25:24 <script runat="server">
14:25:24     Sub Foo()
14:25:24                  dim i as integer = 100
14:25:24     End Sub
14:25:24 </script>
14:25:24     
14:25:24 <html xmlns="http://www.w3.org/1999/xhtml">
14:25:24 <head runat="server">
14:25:24     <title></title>
14:25:24 </head>
14:25:24 <body>
14:25:24     <form id="form1" runat="server">
14:25:24     <div>
14:25:24     
14:25:24     </div>
14:25:24     </form>
14:25:24 </body>
14:25:24 </html>
~~~

**Comment by DustinCampbell** [comment] 2016-03-03 17:08
@brettfo -- is this a dupe of issue #9241?

**Comment by brettfo** [comment] 2016-03-03 18:05
Yes this is the same issue.  Closing this in favor of the other since I already have a PR out to make diagnosing the issue easier (see dotnet/roslyn-internal#626).

**Closed by brettfo** 2016-03-03 18:05 UTC
Labels: Area-IDE, Contributor Pain, Flaky, Test, Urgency-Soon
