### ISSUE TITLE
add more unit tests for batch fixer

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3404] opened 2015-06-09 20:02 UTC
see #320 for more detail.

basically, we need a way unit tests for batch fixer covering many corner cases.

**Comment by Pilchie** [comment] 2015-06-09 21:35
@heejaechang Can you give some examples?

**Comment by heejaechang** [comment] 2015-06-09 22:20
@mavasani is probably better person to explain. I am also pending PR that I am working on to move Batch Fixer to Enc differ rather than inc parser differ.

**Comment by mavasani** [comment] 2015-06-10 15:11
@Pilchie This work item is mainly about adding more unit tests for [this](http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/7b663f5bd0de566c.html) API in the batch fixer that merges batch of code actions into a single code action for fix all. Tests should cover the below cases (currently we just have a single regression test for #320):

1. If batch of code actions have overlapping fix spans, then the batch fixer should pick a subset of non-overlapping code actions and merge them for the fix all fix.
2. For case 1, the batch fixer should always be deterministic in the subset selected, so that we offer the same fix all fix every time user does a ctrl + dot for same sources.
3. For cases such as #320 our [differ](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,495) did a bad job at identifying syntax tree text changes, causing non-conflicting code actions to be deemed as conflicting, and hence the FixAll did not fix all the fixable diagnostics. Matt Warren fixed the couple of bugs in SyntaxTree.GetTextChanges that were repro-able by #320 but we may want more tests around this to verify the functionality of our current differ/new differ that HeeJae is working on.

**Comment by Pilchie** [comment] 2015-06-10 16:29
Thanks - just wanted to get some details, since otherwise bugs like this tend to sit for a while and then get closed when no one can remember what tests people wanted to add or why.

**Comment by sharwell** [comment] 2015-08-20 19:13
We [run the `FixAllProvider`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/Verifiers/CodeFixVerifier.cs#L90) for all of our code fix tests in StyleCopAnalyzers. I'm not sure how many that is exactly, but it's not a particularly small number.

If you change our `CustomFixAllProviders.BatchFixer` to return the standard batch fixer, it will highlight a number of tests which don't currently work well with it. Just be aware that we have [a guard](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/Verifiers/CodeFixVerifier.cs#L82) to catch mistakes on this. :wink:

**Comment by CyrusNajmabadi** [comment] 2022-10-28 18:27
The batch fixer was rewritten, with many tests added for it for corner cases in text manipulation (e.g. overlapping text, abutting text, etc.).  Closing out.

**Closed by CyrusNajmabadi** 2022-10-28 18:27 UTC
Labels: Area-IDE, Test, Concept-Continuous Improvement
