### ISSUE TITLE
InvalidProgramException when running in x64

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#968] opened 2015-03-02 20:04 UTC
The following program will throw an AggregateException containing an InvalidProgramException when run in x64. When running the program as x86, everything is fine.

Here is a link to a project demonstrating the error; https://dl.dropboxusercontent.com/u/34113139/InvalidProgramException.zip. Run the x86 configuration and it works, switch to x64 and the error appears.

Program:
```
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace RoslynTest {
	class Program {
		static void Main(string[] args) {
			var syntaxTree = CSharpSyntaxTree.ParseText(@"class C { static int x = 0; }");

			var compilation = CSharpCompilation.Create("Test", new[] { syntaxTree }, new[] { MetadataReference.CreateFromAssembly(typeof(object).Assembly) }, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
			foreach (var d in compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error)) {
			}

			Console.WriteLine("Done");
		}
	}
}
```

Actual output:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Collections.Immutable.ImmutableHashSet`1.HashBucket.Enumerator.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Enumerator.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstantEvaluationHelpers.CreateGraph(Dictionary`2 graph, SourceFieldSymbolWithSyntaxReference field, Boolean earlyDecodingWellKnownAttributes)
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstantEvaluationHelpers.OrderAllDependencies(SourceFieldSymbolWithSyntaxReference field, ArrayBuilder`1 order, Boolean earlyDecodingWellKnownAttributes)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceFieldSymbolWithSyntaxReference.GetConstantValue(ConstantFieldsInProgress inProgress, Boolean earlyDecodingWellKnownAttributes)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass2.<ForceComplete>b__4(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at RoslynTest.Program.Main(String[] args) in d:\Projects\RoslynTest\Program.cs:line 13
```

**Comment by theoy** [comment] 2015-03-05 21:51
Looks like a dupe of dotnet/corefx/issues/320! The fix is available, we'll be picking up the new version of immutable soon (already have this scheduled).

**Closed** 2015-03-05 21:51 UTC
Labels: API, Area-Compilers, Bug, Resolution-Duplicate, Resolution-External

**Comment by taotao2014** [comment] 2015-05-18 11:35
I have the same problem, how to solve？？？, Thank you very much。
