### ISSUE TITLE
Inline refactoring isn't offered at usages of temporary variable

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#26608] opened 2018-05-03 22:18 UTC
**Version Used**: 
15.8 Int Preview 1

**Steps to Reproduce**:

1. Create C# project, as shown below
2. Set caret on 'foo' in 'Console.Write(foo);'
3. Press Ctrl+.

```csharp
        static void Main(string[] args)
        {
            string foo = "sfsf";

            Console.Write(foo);
        }
```

**Expected Behavior**:
LightBulb offers inline temporary variable 'foo' refactoring.

**Actual Behavior**:
Inline variable refactoring is only offered if you set the caret inside of the 'foo' in the variable declaration.

**Justification**
Since the temporary variable has to be declared before it can be used, I think the most likely scenario in which I'd use this fixer is 1) I create the temporary variable 2) I use it 3) I realize the variable is unneeded and want to inline it. It seems more useful to support inlining the variable at its usage than supporting it at its declaration.

**Comment by sharwell** [comment] 2018-05-03 22:27
Duplicate of #21892

**Closed by sharwell** 2018-05-03 22:27 UTC
Labels: Resolution-Duplicate
