### ISSUE TITLE
VS crashes itself shortly after opening solution with .NET Core and UWP project

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#17178] opened 2017-02-16 16:35 UTC
d15rel 26214.0

After opening a solution from my MRU and switching to another app, several seconds later VS crashed itself. Here is the info from the Event Viewer:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalDocument(IVisualStudioHostDocument document, Boolean isCurrentContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalFile(String additionalFilePath, Func`2 getIsInCurrentContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.<>c__DisplayClass38_0.<AddAdditionalFile>b__0()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.<>c__DisplayClass13_0.<ExecuteForegroundAction>b__0(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass3_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass7_0`1.<SafeContinueWith>b__0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass7_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalDocument(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostDocument, Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalFile(System.String, System.Func`2<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostDocument,Boolean>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject+<>c__DisplayClass38_0.<AddAdditionalFile>b__0()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject+<>c__DisplayClass13_0.<ExecuteForegroundAction>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass3_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass7_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

```
Faulting application name: devenv.exe, version: 15.0.26214.0, time stamp: 0x58a35a53
Faulting module name: Microsoft.CodeAnalysis.Workspaces.ni.dll, version: 2.0.0.61413, time stamp: 0x9e3296eb
Exception code: 0x80131623
Fault offset: 0x0068a3c7
Faulting process id: 0x2af4
Faulting application start time: 0x01d28871f3e2c44d
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.C8fd77a78#\c29dc0e2cc995f45125b7a9ba10c43b0\Microsoft.CodeAnalysis.Workspaces.ni.dll
Report Id: a8be1064-d69a-4cf2-b8e4-448b8cfd9174
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by AArnott** [comment] 2017-02-16 16:38
This repro'd the next time I opened the solution as well. So just in case it's something in my `.vs` folder, I've zipped up the entire repro solution so you can open it and hopefully it crashes.

[MoneyMan.zip](https://github.com/dotnet/roslyn/files/780782/MoneyMan.zip)

**Comment by AArnott** [comment] 2017-02-16 16:40
It crashed a 3rd time in a row, so I deleted the .vs folder, and it crashed a 4th time anyway.

**Comment by Pilchie** [comment] 2017-02-16 17:44
This actually belongs on roslyn-project-system.

**Comment by mavasani** [comment] 2017-02-16 17:46
Yes it is a dupe of https://github.com/dotnet/roslyn-project-system/issues/1563, for which I have a PR out. @AArnott I'll send you a VSIX based on my PR to verify it fixes the crash for your solution

**Closed** 2017-02-16 17:54 UTC
Labels: Area-External, Bug, Resolution-Duplicate, Tenet-Reliability

**Comment by AArnott** [comment] 2017-02-16 18:25
Thanks
