### ISSUE TITLE
Sorting using instruction doesn't sort properly in middle of preprocessor directives

### ISSUE THREAD

**Issue by Enderlook** [dotnet/roslyn#44103] opened 2020-05-09 01:01 UTC
Not exactly sure if this is a problem of Roslyn or VS, but I have understood that VS compiler (and so code refactoring) is Roslyn, so...

**Version Used**: C# Tools 3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e 
(I took that from VS -> Help -> About Microsoft Visual Studio)

**Steps to Reproduce**:

1. Write something like this:
```cs
using System;
#if !EXAMPLE
using Microsoft.CSharp.RuntimeBinder;
#endif
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
        var a = new List<int>();
        var b = new CSharpArgumentInfo();
    }
}
```
2. Press "Run Code Cleanup" in Visual Studio (provided you have the "Sort usings" fixer included).

**Expected Behavior**:
```cs
#if !EXAMPLE
using Microsoft.CSharp.RuntimeBinder;
#endif

using System;
using System.Collections.Generic;

// [...]
```

**Actual Behavior**:
```cs
using System;

#if !EXAMPLE
using Microsoft.CSharp.RuntimeBinder;

#endif
using System.Collections.Generic;

// [...]
```

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:58
Closing as by design.

**Closed by CyrusNajmabadi** 2024-10-21 19:58 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Need Design Review
