### ISSUE TITLE
RenameMoveNextInVBToUpperCaseOnlyCausesConflictInCSForEach failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9565] opened 2016-03-08 16:23 UTC
Branch: Master
Build: http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit32/922/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp/ImplicitReferenceConflictTests/RenameMoveNextInVBToUpperCaseOnlyCausesConflictInCSForEach/

```
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLocationReferencedAs(Location location, RelatedLocationType type) in d:\j\workspace\roslyn_master---340ee19b\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 219 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.AssertLabeledSpansAre(String label, String replacement, Nullable`1 type, Boolean isRenameWithinStringOrComment) in d:\j\workspace\roslyn_master---340ee19b\src\EditorFeatures\Test2\Rename\RenameEngineResult.vb:line 139 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.ImplicitReferenceConflictTests.RenameMoveNextInVBToUpperCaseOnlyCausesConflictInCSForEach() in d:\j\workspace\roslyn_master---340ee19b\src\EditorFeatures\Test2\Rename\CSharp\ImplicitReferenceConflictTests.vb:line 149
```

**Comment by davkean** [comment] 2016-03-08 16:30
https://github.com/dotnet/roslyn/issues/9565, https://github.com/dotnet/roslyn/issues/9566 and https://github.com/dotnet/roslyn/issues/9568 all look related.

**Comment by jasonmalinowski** [comment] 2016-03-08 18:12
This is a dupe of #9308.

**Closed by jasonmalinowski** 2016-03-08 18:12 UTC
Labels: Area-IDE, Flaky, Test
