### ISSUE TITLE
Proposal: Allow extension methods for operators

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/roslyn#14268] opened 2016-10-04 18:42 UTC
With the addition of Ref locals to C# 7, a lot of new possibilities have been created. One of the biggest I can think of is allow reference wrappers to struct types. For certain things, this can be very nice. However, to place a struct in that reference wrapper, you would always have to new the wrapper, unless you implement an implicit conversion in the structure. However, in some cases the structure class is not known, so you cannot create that conversion. Looking through the IL generated by an extension method and an implicit operator, it looks like both pieces of code look the same. 

My proposal would be to allow extension methods to extend operators in order to make this an easier case. It does not look like these would require a new version of the CLR.

**Comment by svick** [comment] 2016-10-04 18:59
I'm not sure I completely understand what you're proposing, but it sounds like this is a duplicate of a part of https://github.com/dotnet/roslyn/issues/11159.

**Comment by gafter** [comment] 2019-05-06 22:50
Closing for lack of follow-up.  Please reopen in `csharplang` if you're still interested in pursuing this.

**Closed by gafter** 2019-05-06 22:50 UTC
Labels: Area-Language Design
