### ISSUE TITLE
new line option before/after the arrow when using an expression body for a method/property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46603] opened 2020-08-06 21:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1132571/new-line-option-beforeafter-the-arrow-when-using-a.html)._

---
I want the option to add a new line before(or after) the arrow when using an expression body for a method (or property).

Currently, the following code using long type names will not break on a new line.
One line is too long.
```
public static System.Collections.Generic.IList<Guid> CreateList() => new  System.Collections.Generic.List<Guid>();
```

If possible, I would like to see a line break before(or after) an arrow.
(The first line is the same as in the block body!)
```
public static System.Collections.Generic.IList<Guid> CreateList()
    => new System.Collections.Generic.List<Guid>();
```

My editorconfig is below.
```
csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_members_in_anonymous_types = true
csharp_new_line_between_query_expression_clauses = true
```

Thanks.

---
#### Feedback Bot on 7/31/2020, 02:40 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment] 2021-05-04 19:00
Duplicate of https://github.com/dotnet/roslyn/issues/21631.

**Comment by LyskOnGithub** [comment] 2021-09-15 13:02
I found this open feature request when I googled how to do that exact thing, wrap the line before the arrow operator when using expression bodied methods. Later I discovered that ReSharper has a formatting rule like this, so if you use RS this might be a workaround for anyone waiting for this to be implemented in VS natively.

The RS rules are

`[resharper_]csharp_wrap_before_arrow_with_expressions, 
[resharper_]wrap_before_arrow_with_expressions`

You can also find them in Extensions > ReSharper > Options > Code Editing > C# > Formatting Style > Line Breaks and Wrapping > Arrangement of Expression Bodied Members

Hope this helps. Cheers.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:19
Handled by:

![Image](https://github.com/user-attachments/assets/9e21a590-a764-46c7-a4e1-790bfca8aece)

**Closed by CyrusNajmabadi** 2024-10-22 18:19 UTC
Labels: Area-IDE, Feature Request, IDE-Formatter
