### ISSUE TITLE
[Regression in 16.1] Static field naming rules have started applying to constants

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#35488] opened 2019-05-03 07:47 UTC
This is a regression in 16.1. 

We have different rules for static fields vs consts, in 16.1 the former has started enforcing the latter.

**Version Used**: 
VS 15.9: No warning
VS 16.0: No warning
VS 16.1: Warning

**Steps to Reproduce**:

.editorconfig
```
dotnet_naming_rule.parameters_must_be_camel_cased.symbols                                             = parameter_symbols
dotnet_naming_rule.parameters_must_be_camel_cased.style                                               = camel_case_style
dotnet_naming_rule.parameters_must_be_camel_cased.severity                                            = warning

dotnet_naming_rule.constants_must_be_pascal_cased.symbols                                             = constant_symbols
dotnet_naming_rule.constants_must_be_pascal_cased.style                                               = pascal_case_style
dotnet_naming_rule.constants_must_be_pascal_cased.severity                                            = warning

dotnet_naming_rule.private_static_fields_must_be_camel_cased_and_prefixed_with_s_underscore.symbols   = private_static_field_symbols
dotnet_naming_rule.private_static_fields_must_be_camel_cased_and_prefixed_with_s_underscore.style     = camel_case_and_prefix_with_s_underscore_style
dotnet_naming_rule.private_static_fields_must_be_camel_cased_and_prefixed_with_s_underscore.severity  = warning

dotnet_naming_rule.private_instance_fields_must_be_camel_cased_and_prefixed_with_underscore.symbols   = private_field_symbols
dotnet_naming_rule.private_instance_fields_must_be_camel_cased_and_prefixed_with_underscore.style     = camel_case_and_prefix_with_underscore_style
dotnet_naming_rule.private_instance_fields_must_be_camel_cased_and_prefixed_with_underscore.severity  = warning

# Symbols
dotnet_naming_symbols.externally_visible_symbols.applicable_kinds                                     = class,struct,interface,enum,property,method,field,event,delegate
dotnet_naming_symbols.externally_visible_symbols.applicable_accessibilities                           = public,internal,friend,protected,protected_internal,protected_friend,private_protected

dotnet_naming_symbols.interface_symbols.applicable_kinds                                              = interface
dotnet_naming_symbols.interface_symbols.applicable_accessibilities                                    = *

dotnet_naming_symbols.parameter_symbols.applicable_kinds                                              = parameter
dotnet_naming_symbols.parameter_symbols.applicable_accessibilities                                    = *

dotnet_naming_symbols.constant_symbols.applicable_kinds                                               = field
dotnet_naming_symbols.constant_symbols.required_modifiers                                             = const
dotnet_naming_symbols.constant_symbols.applicable_accessibilities                                     = *

dotnet_naming_symbols.private_static_field_symbols.applicable_kinds                                   = field
dotnet_naming_symbols.private_static_field_symbols.required_modifiers                                 = static,shared
dotnet_naming_symbols.private_static_field_symbols.applicable_accessibilities                         = private

dotnet_naming_symbols.private_field_symbols.applicable_kinds                                          = field
dotnet_naming_symbols.private_field_symbols.applicable_accessibilities                                = private

# Styles
dotnet_naming_style.camel_case_style.capitalization                                                   = camel_case

dotnet_naming_style.pascal_case_style.capitalization                                                  = pascal_case

dotnet_naming_style.camel_case_and_prefix_with_s_underscore_style.required_prefix                     = s_
dotnet_naming_style.camel_case_and_prefix_with_s_underscore_style.capitalization                      = camel_case

dotnet_naming_style.camel_case_and_prefix_with_underscore_style.required_prefix                       = _
dotnet_naming_style.camel_case_and_prefix_with_underscore_style.capitalization                        = camel_case

dotnet_naming_style.pascal_case_and_prefix_with_I_style.required_prefix                               = I
dotnet_naming_style.pascal_case_and_prefix_with_I_style.capitalization                                = pascal_case
```

``` C#
    class Program
    {
        private const string Bar = "Foo";
        
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```

**Expected Behavior**:
No warning

**Actual Behavior**:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE1006	Naming rule violation: Missing prefix: 's_'	ConsoleApp413	C:\Users\davkean\Source\Repos\ConsoleApp413\ConsoleApp413\Program.cs	8	Active

```

**Comment by sharwell** [comment] 2019-05-06 19:07
`static` has always applied to `const` (#15428). The bug here is that `constants_must_be_pascal_cased` is defined before `private_static_fields_must_be_camel_cased_and_prefixed_with_s_underscore`, but the latter is getting enforced for these fields.

**Comment by sharwell** [comment] 2019-05-10 14:53
This was caused by the remapping here:

https://github.com/dotnet/roslyn/blob/1fcbc512b725598c1ee72f4036728b801c14cc79/src/EditorFeatures/Core.Wpf/Options/LegacyEditorConfigDocumentOptionsProvider.DocumentOptions.cs#L37-L46

The output of the remapping uses `ImmutableDictionary<TKey, TValue>`, which does not have the same iteration order as the input `Dictionary<TKey, TValue>`, thereby breaking an internal assumption in the parsing logic for naming conventions. https://github.com/dotnet/roslyn/issues/23391#issuecomment-348169125

**Comment by jasonmalinowski** [comment] 2019-05-16 17:01
This has been merged into 16.1. Thanks @davkean for filing the issue -- the repro steps were helpful as another isolated case than testing on our big repos.

**Closed by jasonmalinowski** 2019-05-16 17:01 UTC
Labels: Area-IDE, Bug, Regression

**Comment by AdamYoblick** [comment] 2019-05-21 23:03
@jasonmalinowski I just run into this issue locally. Does the latest vs2019 preview build have this fix?

**Comment by jasonmalinowski** [comment] 2019-05-21 23:09
Today we released _both_ 16.1 "not a preview" and 16.2 Preview 1. Both have the fix.

**Comment by AdamYoblick** [comment] 2019-05-21 23:10
Awesome, thanks so much :)

**Comment by mcflux** [comment] 2021-06-21 13:14
This is still a thing. I'm getting this still in the version 16.10.0 of Visual Studio

**Comment by sharwell** [comment] 2021-06-21 14:29
@mcflux This issue describes a scenario that no longer applies in 16.10. We rewrote the ordering support for naming rules in 16.2 (#36366). If you are running into problems, can you file a new issue for this?
