### ISSUE TITLE
Semantic classification and other features  fail in VS for no apparent reason

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#59506] opened 2022-02-11 22:39 UTC
```
StreamJsonRpc.RemoteInvocationException: The method or operation is not implemented.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.NotImplementedException: The method or operation is not implemented.
      at Microsoft.CodeAnalysis.SolutionState.GeneratedFileReplacingCompilationTracker.Fork(SolutionServices solutionServices, ProjectState newProject, CompilationAndGeneratorDriverTranslationAction translate, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionState.CreateCompilationTrackerMap(ProjectId changedProjectId, ProjectDependencyGraph dependencyGraph)
      at Microsoft.CodeAnalysis.SolutionState.ForkProject(ProjectState newProjectState, CompilationAndGeneratorDriverTranslationAction translate, ProjectDependencyGraph newDependencyGraph, ImmutableDictionary`2 newFilePathToDocumentIdsMap, Boolean forkTracker)
      at Microsoft.CodeAnalysis.SolutionState.UpdateDocumentState(DocumentState newDocument, Boolean textChanged, Boolean recalculateDependentVersions)
      at Microsoft.CodeAnalysis.SolutionState.WithDocumentText(DocumentId documentId, SourceText text, PreservationMode mode)
      at Microsoft.CodeAnalysis.Solution.WithDocumentText(DocumentId documentId, SourceText text, PreservationMode mode)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentAsync(TextDocument document, DocumentStateChecksums oldDocumentChecksums, DocumentStateChecksums newDocumentChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentsAsync(Project project, ProjectStateChecksums projectChecksums, IEnumerable`1 existingTextDocumentStates, ChecksumCollection oldChecksums, ChecksumCollection newChecksums, Func`3 addDocuments, Func`3 removeDocument)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectAsync(Project project, ProjectStateChecksums oldProjectChecksums, ProjectStateChecksums newProjectChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, HashSet`1 oldChecksums, HashSet`1 newChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, ChecksumCollection oldChecksums, ChecksumCollection newChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.CreateSolutionAsync(Checksum newSolutionChecksum)
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetProjectSubsetSolutionAsync>g__GetProjectSubsetSolutionSlowAsync|15_0(Solution baseSolution, AssetProvider assetProvider, Checksum solutionChecksum, ProjectId projectId, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass18_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

**Comment by CyrusNajmabadi** [comment] 2022-02-11 23:56
@jasonmalinowski Terrifying.

**Comment by jasonmalinowski** [comment] 2022-02-11 23:58
@CyrusNajmabadi Duplicate of #57082.

**Closed by jasonmalinowski** 2022-02-11 23:58 UTC
Labels: Area-IDE, untriaged
