### ISSUE TITLE
Sporadic NullReferenceException in CSharpDataSetDataTableInSerializableObjectGraphAnalyzer

### ISSUE THREAD

**Issue by changov** [dotnet/roslyn#69945] opened 2023-09-14 04:53 UTC
### Analyzer

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)
**Version**: 7.0.0

The .NET SDK is v6.0.413.

### Describe the bug

We build the same code on Windows and Linux. The Linux build is crashing often with this:
```log
 332:17>CSC : error AD0001: Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Security.CSharpDataSetDataTableInSerializableObjectGraphAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/__w/1/s/src/subsystems/scheduler/scheduler.global/scheduler.global.csproj]
 332:17>Exception occurred with following context:
         Compilation: Microsoft.Azure.AISC.Scheduler.Global
         IOperation: Invocation
         SyntaxTree: /__w/1/s/src/subsystems/scheduler/scheduler.global/ScheduleBuilder/ResourcesToScaleDownSelector.cs
         SyntaxNode: JsonConvert.DeserializeObject<RunningResource ... [InvocationExpressionSyntax]@[9317..9409) (154,44)-(154,136)
         System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.AddTupleTypeName(INamedTypeSymbol symbol)
         at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.AddNameAndTypeArgumentsOrParameters(INamedTypeSymbol symbol)
         at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.MinimallyQualify(INamedTypeSymbol symbol)
         at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.VisitNamedTypeWithoutNullability(INamedTypeSymbol symbol)
```

The target source code is this:
```cs
                    if (state.ScaledDownResources?.TryGetValue(resourceLookupKey, out RunningResource? candidateResource) != true)
                    {
                        // make a copy of this resource as TryScaleDownResource method will mutate the object.
                        candidateResource = JsonConvert.DeserializeObject<RunningResource>(JsonConvert.SerializeObject(runningResource));
                    }
```

(The location reference spans the JsonConvert.DeserializeObject() call.)

There is this at the top of the source file:
```cs
#nullable enable
```

The project settings are these:
```xml
    <AnalysisLevel>6</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
```

At AnalysysLevel=4 there is no crash. (Not sure about 5.)

Other projects have the same settings, and we have lots of calls to  JsonConvert.DeserializeObject(), but only this one causes the crash.

Getting more diagnostics would be very hard since the build runs in a dedicated build environment, in a complex pipeline. But we have the full MSBuild log at least.

**Comment by mavasani** [comment] 2023-09-14 04:59
Moving to Roslyn repo as the NRE seems to be coming from `Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.AddTupleTypeName(INamedTypeSymbol symbol)` in the compiler layer.

**Comment by jjonescz** [comment] 2023-09-14 08:17
Probably the same issue as https://github.com/dotnet/roslyn/issues/53943.

**Comment by jaredpar** [comment] 2023-09-18 17:50
Resolving as dupe and moving that issue back to 17.8

**Closed by jaredpar** 2023-09-18 17:50 UTC
Labels: Area-Compilers, untriaged

**Comment by jaredpar** [comment] 2023-11-01 16:24
@changov are you able to reproduce this crash on a more modern SDK like .NET 7 or 8? This bug's been reported a few times on older SDKS like 5.0.400 and 6.0.0 but we are unable to reproduce the crash on more modern compilers / SDKs. If there is a repro on .NET 7 or later I'd like to work with you to get a repro so we can root cause this bug. Otherwise the data is starting to look like it's fixed in more recent compilers.

**Comment by changov** [comment] 2023-11-02 06:22
Unfortunately, it'll be quite a while before we move beyond .Net 6. I tried to isolate the repro in a small test project, but I couldn't get the analyzer crash. The real source file is rather large and depends on lots of other things.
