### ISSUE TITLE
AnalyzerDriver.GetOperationsToAnalyze throws assert "Expected operation with kind 'Invocation' to be the root operation with null 'Parent', but instead it has a non-null Parent with kind 'ExpressionStatement'" on incomplete C# code

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#43106] opened 2020-04-06 15:17 UTC
**Version Used**: 16.6 Preview 3

**Steps to Reproduce**:

1. Paste C#:

```C#
class B
{
    // Haven't typed { } on the next line yet
    public B() : this(1) 

    public B(int a) { } 
}
```

**Expected Behavior**: No asserts
**Actual Behavior**: Assert:

<details>
<summary>Expected operation with kind 'Invocation' to be the root operation with null 'Parent', but instead it has a non-null Parent with kind 'ExpressionStatement'</summary>
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass14_0.<TryExecuteDeclaringReferenceActions>g__getOperationsToAnalyzeWithStackGuard|4(ImmutableArray`1 operationBlocksToAnalyze)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass14_0.<TryExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|3()

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean should......
</details>

**Comment by dpoeschl** [comment] 2020-04-06 15:19
FYI @mavasani

**Comment by mavasani** [comment] 2020-04-06 15:25
Thanks @dpoeschl - seems to be a dupe of https://github.com/dotnet/roslyn/issues/26217#issuecomment-429138417

**Comment by CyrusNajmabadi** [comment] 2020-04-06 21:13
Can we fix thsi?  It' two years now.  The assert is both frustrating and concerning.

Either it's valid, and we should fix it.   Or it's invalid and it makes dogfooding very painful, in which case is should be removed.

**Comment by mavasani** [comment] 2020-04-06 21:25
I will disable this assert for now - there has been no real user scenario that has shown to be affected due to this violation. I will have a PR out soon...

**Comment by mavasani** [comment] 2020-04-06 23:00
https://github.com/dotnet/roslyn/pull/43129

**Closed** 2020-04-08 21:43 UTC
Labels: 4 - In Review, Area-Analyzers, Bug
