### ISSUE TITLE
Faulty inline temp variable suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#34169] opened 2019-03-15 19:50 UTC
Original code:

```csharp
var response = new byte[4];
int byteCount = m_rs485.Read(response, 0, 5);
if (byteCount != 5 || response[3] != (byte)STATUS.SUCCESS) retVal = false;
```

VS suggested refactoring:

```csharp
int byteCount = m_rs485.Read(new byte[4], 0, 5);
if (byteCount != 5 || (new byte[4])[3] != (byte)STATUS.SUCCESS) retVal = false;
```

Bad idea!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/479229/faulty-inline-temp-variable-suggestion.html
VSTS ticketId: 811326_
_These are the original issue comments:_

Visual Studio Feedback System on 3/6/2019, 01:00 AM (9 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-04-01 15:25
Tentatively marking this as **By Design**, but will update following the design review.

**Comment by CyrusNajmabadi** [comment] 2019-04-02 15:12
Historical note: this was the intent of the feature.  If you ask to inline... then we inline :)

**Comment by sharwell** [comment] 2019-04-02 19:48
In design review we agreed that this is the by-design behavior of this refactoring.

**Closed by sharwell** 2019-04-02 19:48 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, Need Design Review, Resolution-By Design
