### ISSUE TITLE
Use explicit type on var should only convert to nullable if ever set to nullable

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#42898] opened 2020-03-30 07:27 UTC
**Version Used**: VS 16.6 preview 1

**Steps to Reproduce**:

copy the following code into your IDE:

```csharp
#nullable enable
public class C
{
    string M()
    {
        var str = "hello";
        return str;
    }
}
```

Make sure settings prefer explicit type.
On var select the use explicit type code fix

**Expected Behavior**:
Since `str` is never set to anything nullable:
`string str = "hello";`

**Actual Behavior**:
`string? str = "hello";`

**Comment by sharwell** [comment] 2020-03-30 15:06
Duplicate of #41243

**Closed by sharwell** 2020-03-30 15:06 UTC
