### ISSUE TITLE
Potential bug in .NET SDK 6.0.400-preview.22351.4 compiler

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#62354] opened 2022-07-03 12:29 UTC
**Version Used**: Locally: ``6.0.400-preview.22301.10``, On Github Actions: ``6.0.400-preview.22351.4``

**Steps to Reproduce**:

This small codebase should be enough to reproduce it: <https://github.com/AraHaan/remora-extensions>.

(I would try sharplab but I fear it might not be as up to date with the version of the compiler that the CI automatically installs using the .NET Install scripts)

**Expected Behavior**:
For https://github.com/AraHaan/remora-extensions/blob/main/AraHaan.Remora.Extensions/Hosting/Host.cs#L34 to compile just fine in CI just like it does locally on my computer.

**Actual Behavior**:
Compiler error triggers on this line in CI, however locally it compiles just fine: https://github.com/AraHaan/remora-extensions/blob/main/AraHaan.Remora.Extensions/Hosting/Host.cs#L34
The interface used in that code: https://github.com/AraHaan/remora-extensions/blob/main/AraHaan.Remora.Extensions/Hosting/IBotServiceConfigurator.cs

More Details:

```
/home/runner/work/remora-extensions/remora-extensions/AraHaan.Remora.Extensions/Hosting/Host.cs(34,28): error CS8920: The interface 'IBotServiceConfigurator' cannot be used as type argument. Static member 'IBotServiceConfigurator.BeforeConfigure(Assembly)' does not have a most specific implementation in the interface. [/home/runner/work/remora-extensions/remora-extensions/AraHaan.Remora.Extensions/AraHaan.Remora.Extensions.csproj]
```

**Comment by Youssef1313** [comment] 2022-07-03 12:38
I think this was intentional. See https://github.com/dotnet/csharplang/issues/5955.
It should be documented as a breaking change if it's not already.

**Comment by CyrusNajmabadi** [comment] 2022-07-03 15:22
Closing as by design.

**Closed by CyrusNajmabadi** 2022-07-03 15:22 UTC
Labels: Area-Compilers, untriaged
