### ISSUE TITLE
Breadcrumb for ".NET Compiler Platform SDK" should not appear in Visual C# root

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13418] opened 2016-08-26 23:09 UTC
As part of the work to clean up the templates, we're only putting the core templates (App entry points + one library) in the Visual C# root. 

The breadcrumb for the platform SDK should not appear in the root:

![image](https://cloud.githubusercontent.com/assets/1103906/18022857/7e77413c-6ba7-11e6-807d-8609ef4dfc60.png)

**Comment by Pilchie** [comment] 2016-08-29 16:21
Agree that this should show up only under the `Extensibility` node.

**Comment by jmarolf** [comment] 2016-12-09 20:10
Dupe of https://github.com/dotnet/roslyn/issues/15311

**Closed by jmarolf** 2016-12-09 20:10 UTC
Labels: Area-IDE, Bug
