### ISSUE TITLE
C# IOperation factory sets incorrect BinaryOperatorKind for && and || operators

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#23956] opened 2017-12-28 16:30 UTC
Here is an existing test:
```
        [CompilerTrait(CompilerFeature.IOperation)]
        [Fact, WorkItem(17601, "https://github.com/dotnet/roslyn/issues/17601")]
        public void IIfstatementWithMultipleCondition()
        {
            string source = @"
using System;
class P
{
    private void M()
    {
        int m = 9;
        int n = 7;
        int p = 5;
        /*<bind>*/if (m >= n && m >= p)
        {
            Console.WriteLine(""Nothing is larger than m."");
        }/*</bind>*/
    }
}
";
            string expectedOperationTree = @"
IConditionalOperation (OperationKind.Conditional, Type: null) (Syntax: 'if (m >= n  ... }')
  Condition: 
    IBinaryOperation (BinaryOperatorKind.And) (OperationKind.BinaryOperator, Type: System.Boolean) (Syntax: 'm >= n && m >= p')
      Left: 
        IBinaryOperation (BinaryOperatorKind.GreaterThanOrEqual) (OperationKind.BinaryOperator, Type: System.Boolean) (Syntax: 'm >= n')
          Left: 
            ILocalReferenceOperation: m (OperationKind.LocalReference, Type: System.Int32) (Syntax: 'm')
          Right: 
            ILocalReferenceOperation: n (OperationKind.LocalReference, Type: System.Int32) (Syntax: 'n')
      Right: 
        IBinaryOperation (BinaryOperatorKind.GreaterThanOrEqual) (OperationKind.BinaryOperator, Type: System.Boolean) (Syntax: 'm >= p')
          Left: 
            ILocalReferenceOperation: m (OperationKind.LocalReference, Type: System.Int32) (Syntax: 'm')
          Right: 
            ILocalReferenceOperation: p (OperationKind.LocalReference, Type: System.Int32) (Syntax: 'p')
  WhenTrue: 
    IBlockOperation (1 statements) (OperationKind.Block, Type: null) (Syntax: '{ ... }')
      IExpressionStatementOperation (OperationKind.ExpressionStatement, Type: null) (Syntax: 'Console.Wri ...  than m."");')
        Expression: 
          IInvocationOperation (void System.Console.WriteLine(System.String value)) (OperationKind.Invocation, Type: System.Void) (Syntax: 'Console.Wri ... r than m."")')
            Instance Receiver: 
              null
            Arguments(1):
                IArgumentOperation (ArgumentKind.Explicit, Matching Parameter: value) (OperationKind.Argument, Type: null) (Syntax: '""Nothing is ... er than m.""')
                  ILiteralOperation (OperationKind.Literal, Type: System.String, Constant: ""Nothing is larger than m."") (Syntax: '""Nothing is ... er than m.""')
                  InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
                  OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
  WhenFalse: 
    null
";
            var expectedDiagnostics = DiagnosticDescription.None;

            VerifyOperationTreeAndDiagnosticsForTest<IfStatementSyntax>(source, expectedOperationTree, expectedDiagnostics);
        }
```

**Expected Behavior**:
    IBinaryOperation (BinaryOperatorKind.**ConditionalAnd**) (OperationKind.BinaryOperator, Type: System.Boolean) (Syntax: 'm >= n && m >= p')

**Actual Behavior**:
    IBinaryOperation (BinaryOperatorKind.**And**) (OperationKind.BinaryOperator, Type: System.Boolean) (Syntax: 'm >= n && m >= p')

**Comment by AlekseyTs** [comment] 2017-12-28 16:31
CC @dotnet/analyzer-ioperation

**Comment by Joe4evr** [comment] 2017-12-30 07:42
This begs the question of what `IOperation` really represents. Is it the source code, or what the code translates into? If it's the latter, then this is by design, because `bool && bool` translates into `bool & bool` for perf reasons. This behavior can be demonstrated by using two malformed `bool`s and printing out the result of `&&`ing them together [like so](https://dotnetfiddle.net/j7TrEd).

**Comment by 333fred** [comment] 2018-01-02 18:23
I would say that IOperation tries to represent the semantics of the source code. In this case, I'd view perf optimizations such as that to be an implementation detail, and so we should be representing the original intentions of the code. We do have plans to eventually allow more lowered trees after rewrites and optimizations, but that isn't relevant here.

**Comment by 333fred** [comment] 2018-03-26 21:38
This was fixed in https://github.com/dotnet/roslyn/pull/24263. When `features/dataflow` is merged back to a shipping branch, this bug can closed.

**Closed** 2018-06-21 17:37 UTC
Labels: Area-Compilers, Language-C#, New Feature - IOperation
