### ISSUE TITLE
VS2017 does not show examples based upon the documentation spec.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#29661] opened 2018-09-04 16:50 UTC
**Version Used**: The version from the latest version of VS2017 preview.

**Steps to Reproduce**:
There is not really any steps to reproduce other than having a method that has the ``<example><code></code></example>`` tags in it's documentation.

**Expected Behavior**:
For something like this to appear in the function tooltip:
![](https://user-images.githubusercontent.com/287848/45044370-32359c00-b070-11e8-9f56-bba3249759d4.png)

**Actual Behavior**:
This instead just shows the function's summary and exceptions without the text for the possible reasons of the exceptions, which I also would like changed to include those reasons in the tooltips as well so one does not have to dive into the developer's documentations online or their assembly's metadata manually to see it.

See https://github.com/dotnet/csharplang/issues/1835 for more details.

**Comment by BhaaLseN** [comment] 2018-09-04 18:01
Related #26504?

**Comment by sharwell** [comment] 2018-09-04 18:13
Duplicate of #26504

**Closed by sharwell** 2018-09-04 18:13 UTC
