### ISSUE TITLE
Code fix "use pattern match" messes with #region lines

### ISSUE THREAD

**Issue by ygoe** [dotnet/roslyn#35789] opened 2019-05-17 15:55 UTC
**Version Used**: 
Visual Studio 2017 15.9.12

**Steps to Reproduce**:

1. Write the code below
2. Apply the suggested code fix "use pattern match"

```
#region Sample

var str = obj as string;
if (str != null)
{
}

#endregion
```

**Expected Behavior**:

```
#region Sample

if (obj is string str)
{
}

#endregion
```

**Actual Behavior**:

```
#region Sample

#region Sample

if (obj is string str)
{
}

#endregion
```

If there is an `#endregion` line directly preceding the `#region` line (ignoring empty lines), this `#endregion` is inserted between the two `#region` lines.

All in all a pretty confusing experience. I'll better undo that code fix and write it myself. I don't trust the broken fix to not change something else in a place where I don't see it. (Like the cshtml formatting does all the time before you turn it off.)

**Comment by Youssef1313** [comment] 2021-04-01 19:41
I can't reproduce this in SharpLab on `main` branch.

**Comment by CyrusNajmabadi** [comment] 2022-10-26 22:08
This doesn't repro for me either:

I get:

![image](https://user-images.githubusercontent.com/4564579/198147849-6bd8993a-c96c-4867-9884-2a0f3d0bd1d5.png)


Closing out.

**Closed by CyrusNajmabadi** 2022-10-26 22:08 UTC
Labels: Bug, help wanted, Area-IDE, IDE-CodeStyle
