### ISSUE TITLE
Operator False(C#) and IsFalse(VB) are not generated as IOperation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9309] opened 2016-02-29 21:47 UTC
For example, `x` in the expression `x && y` inthe following C# code should be equivalent to `x.IsFalse()`, but it's not generate as an operation.

``` cs
public struct S
{
    private int value;
    public S(int v)
    {
        value = v;
    }
    public static S operator &(S x, S y)
    {
        return new S(x.value + y.value);    
    }
    public static bool operator true(S x)
    {
        return x.value > 0;
    }
    public static bool operator false(S x)
    {
        return x.value <= 0;
    }
}

class C
{
    public void M()
    {
        var x = new S(-1);
        var y = new S(1);
        if (x && y) { }
    }
}
```

Here's VB code for this issue:

``` vb
Module Module1
    Structure S8
        Public Shared Narrowing Operator CType(x As S8) As Boolean
            System.Console.WriteLine("Narrowing Operator CType(x As S8) As Boolean")
            Return Nothing
        End Operator

        Public Shared Operator IsTrue(x As S8) As Boolean
            System.Console.WriteLine("IsTrue(x As S8) As Boolean")
            Return False
        End Operator

        Public Shared Operator IsFalse(x As S8) As Boolean
            System.Console.WriteLine("IsFalse(x As S8) As Boolean")
            Return False
        End Operator

        Public Shared Operator And(x As S8, y As S8) As S8
            Return New S8()
        End Operator
    End Structure

    Sub Main()
        Dim x As New S8
        Dim y As New S8

        If x AndAlso y Then
        End If
    End Sub
End Module
```

**Comment by jinujoseph** [comment] 2018-06-23 00:30
dupe of userdefinedConditionallogicalbinaryoperator

**Comment by mavasani** [comment] 2018-06-25 23:27
Dupe of https://github.com/dotnet/roslyn/issues/19925

**Closed by mavasani** 2018-06-25 23:27 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation, _Product-level triaged
