### ISSUE TITLE
Having  garbled characters in C# interactive

### ISSUE THREAD

**Issue by RamType0** [dotnet/roslyn#49311] opened 2020-11-12 12:44 UTC
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.8.0
**Steps to Reproduce**:

1. Open C# interactive in Visual Studio.

**Expected Behavior**:
No garbled characters.
**Actual Behavior**:
Many garbled characters.
![image](https://user-images.githubusercontent.com/39725073/98941481-05bf1980-2530-11eb-8098-a7bc20213d20.png)

**Comment by huoyaoyuan** [comment] 2020-11-13 13:40
Duplicate of #48874

**Closed** 2020-11-17 20:59 UTC
Labels: Area-Interactive, untriaged
