### ISSUE TITLE
Feature request: expose C# project default namespace to analyzers

### ISSUE THREAD

**Issue by oatkins** [dotnet/roslyn#5252] opened 2015-09-15 20:51 UTC
Unlike VB, the C# compiler doesn't have the concept of a default namespace. There *is* a default namespace *project* setting, but this doesn't affect the compiler at all. It's simply used by Visual Studio to determine how to generate new files from templates.

This feature request is to expose the default namespace, when available, to analyzers. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1481 for why this would be valuable.

**Comment by lgolding** [comment] 2015-09-21 17:49
The feature request #3798 (which would make MSBuild properties such as default namespace available to analyzers by way of the `AnalyzerOptions` object) would address this scenario. Closing this item as duplicate of that one.

**Closed** 2015-09-21 17:49 UTC
Labels: Area-Analyzers, Feature Request, Resolution-Duplicate
