### ISSUE TITLE
Maybe `null` warning when value cannot be `null`

### ISSUE THREAD

**Issue by dougbu** [dotnet/roslyn#36535] opened 2019-06-18 02:23 UTC
## Version Used
Used the 3.0.0-preview7-27812-08 SDK and related `dotnet` tooling for repro.

## Steps to Reproduce
1. Create a console application containing the following in its `Program` class:
    ``` c#
    #nullable enable
        static void Main(string[] args)
        {
            string? one = Environment.GetEnvironmentVariable("one");
            string? two = Environment.GetEnvironmentVariable("two");
            if (one == null && two == null)
            {
                Console.WriteLine("both null");
            }
            else if (one != null && two != null)
            {
                Console.WriteLine("both non-null");
            }
            else if (one != null)
            {
                Console.WriteLine("one is non-null");
            }
            else
            {
                Console.WriteLine(two.Length);
            }
        }
    #nullable disable
    ```
2. update to a recent SDK using global.json:
    ``` json
    {
      "sdk": {
        "version": "3.0.100-preview5-011568"
      }
    }
    ```
3. build the project (`dotnet build`)

## Expected Behavior
Compiles cleanly

## Actual Behavior
Emits a warning (which in the original case becomes an error due to `/p:TreatWarningsAsErrors=true"`)
```
Program.cs(26,35): warning CS8602: Dereference of a possibly null reference. [...\NullableCon
sole\NullableConsole.csproj]
```
The complaint is about the `two` variable dereference though `two` cannot be `null` at line 26 because `one` is `null` and the `one == null && two == null` is handled earlier.

### See also
- Discussion started at https://github.com/aspnet/AspNetCore/pull/11201#discussion_r294103926
- Repro project available at https://github.com/dougbu/NullableConsole

### CC
 @jaredpar @jasonmalinowski @agocke @jcouv

**Comment by jcouv** [comment] 2019-06-19 00:33
I think the root cause here is that we analyze and track locals independently.
As far as the analysis of `two` is concerned the code looks like this:
```C#
        if (something && two == null)
        {
        }
        else if (somethingElse && two != null)
        {
        }
        else if (somethingElse)
        {
        }
        else
        {
            Console.WriteLine(two.Length); // two may be null here
        }
```

The nullability analysis correctly concludes that `two` may be null in the last branch. I agree it's unfortunate.

@agocke @gafter Unless you see how we could do better here, I would close this issue as by-design.

**Closed** 2021-02-10 00:51 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-By Design
