### ISSUE TITLE
[Test Failure] Compile Error (+1 more) in prtest/win/dbg/unit32 on PR #8223

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8493] opened 2016-02-09 19:38 UTC
PR: [#8223](https://github.com/dotnet/roslyn/pull/8223) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3539/

**9 Test Failures:**
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBAsyncTests.LocalCapturedInBetweenSuspensionPoints_Debug
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBAsyncTests.LocalNotCapturedInBetweenSuspensionPoints_Release
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBAsyncTests.LocalCapturedInBetweenSuspensionPoints_Release
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBAsyncTests.LocalNotCapturedInBetweenSuspensionPoints_Debug
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBTests.ImportsInAsyncLambda
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBTests.ImportsInAsync
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBIteratorTests.LocalCapturedAndHoisted
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBIteratorTests.LocalHoistedAndNotCapture
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PDB.PDBIteratorTests.IteratorWithLiftedMultipleSameNameLocals

**Issue 1: Compile Error**

**Issue 2: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment] 2016-02-09 20:24
Dupe of https://github.com/dotnet/roslyn/issues/8494

**Closed by davkean** 2016-02-09 20:24 UTC
Labels: Area-Infrastructure, Contributor Pain, Urgency-Now
