### ISSUE TITLE
Request: make SymbolDisplayCompilerInternalOptions public

### ISSUE THREAD

**Issue by suprak** [dotnet/roslyn#4304] opened 2015-08-03 17:25 UTC
It would be useful to have internal compiler options be configurable as well.

This is useful for our scenario because we are trying to match symbols resolved by Roslyn with those from PerfView traces in Production.

**Comment by RikkiGibson** [comment] 2022-11-29 23:39
Duplicate of #1891

**Closed by RikkiGibson** 2022-11-29 23:39 UTC
Labels: Resolution-Duplicate, help wanted, Concept-API, Area-Compilers, Feature Request
