### ISSUE TITLE
Add documentation for experimental formatting rules (IDE2000 - IDE2006)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65770] opened 2022-12-05 09:15 UTC
<html>
<body>

IDE2000 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2000 | Avoid multiple blank lines
-- | -- | --
IDE2001 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2001 | Embedded statements must be on their own line
IDE2002 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2002 | Consecutive braces must not have blank line between them
IDE2003 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2003 | Blank line required between block and subsequent statement
IDE2004 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2004 | Blank line not allowed after constructor initializer colon
IDE2005 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2005 | Blank line not allowed after conditional expression token
IDE2006 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2006 | Blank line not allowed after arrow expression clause token

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by mavasani** [comment] 2022-12-05 09:17
I have created a single issue for all these rules as I am unsure if we want to document these or not. My instinct says that because we are shipping them in the box, we should document them (and deprecate or remove the documentation once the rules no longer ship). Not having documentation documentation for these rules doesn't feel like a good experience. Thoughts @CyrusNajmabadi?

**Comment by Youssef1313** [comment] 2022-12-05 09:42
Related: https://github.com/dotnet/roslyn/issues/60539

**Comment by CyrusNajmabadi** [comment] 2022-12-05 17:09
Dupe of https://github.com/dotnet/roslyn/issues/65760

**Closed by CyrusNajmabadi** 2022-12-05 17:09 UTC
Labels: help wanted, Area-IDE, Feature Request, Documentation
