### ISSUE TITLE
Improve spell-check

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33163] opened 2019-02-06 01:13 UTC
**Version Used**: VS 2019 Preview 2.1
Copying a customer request.

**Steps to Reproduce**:
```csharp
const string connnectionString = "TBD";
```

**Expected Behavior**:
Get codefix to correct typo in `connnectionString` to `connectionString` or add the new word to a dictionary as an accepted spelling.

**Actual Behavior**:
No spell check.

**Comment by sharwell** [comment] 2019-02-06 14:59
Duplicate of #24963

**Closed by sharwell** 2019-02-06 14:59 UTC
Labels: Area-IDE, Feature Request, IDE-CodeStyle, Need Design Review
