### ISSUE TITLE
VBCSCompiler: Infinite build time

### ISSUE THREAD

**Issue by Reris** [dotnet/roslyn#69672] opened 2023-08-23 14:03 UTC
Currently we can't use the C# compiler with our existing code, because it never finishes.
I've found the issue in our generic types, which are used to combine many irregular properties for on-the-fly code generation.
The most recent compiler update ends in an infinite compilation time. At least for humans. :)

Thank you for fixing this or suggest any configuration tipps to disable this new behavior.

**Version Used**: 
August 2023 release, 4.7.0

**Steps to Reproduce**:

1.  Create Generic typed with lots of generic type arguments
2. Build

Example:
Plain .net console app,
Uncomment more types to see the exponential growth

```c#
// See https://aka.ms/new-console-template for more information

var x = new Caddy<string, string> { Name = "World", Item1 = "Hello" };
Console.WriteLine($"{x.Item1}, {x.Name}!");


public class Caddy<TOwner>
{
    public TOwner Name { get; set; } = default!;
}

public class Caddy<TOwner, T1> : Caddy<TOwner>
{
    public T1 Item1 { get; set; } = default!;
}

public class Caddy<TOwner, T1, T2> : Caddy<TOwner, T1>
{
    public T2 Item2 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3> : Caddy<TOwner, T1, T2>
{
    public T3 Item3 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4> : Caddy<TOwner, T1, T2, T3>
{
    public T4 Item4 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5> : Caddy<TOwner, T1, T2, T3, T4>
{
    public T5 Item5 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6> : Caddy<TOwner, T1, T2, T3, T4, T5>
{
    public T6 Item6 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7> : Caddy<TOwner, T1, T2, T3, T4, T5, T6>
{
    public T7 Item7 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8> : Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7>
{
    public T8 Item8 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9> : Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8>
{
    public T9 Item9 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> : Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9>
{
    public T10 Item10 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>
{
    public T11 Item11 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>
{
    public T12 Item12 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>
{
    public T13 Item13 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>
{
    public T14 Item14 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>
{
    public T15 Item15 { get; set; }
}
/*

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>
{
    public T16 Item16 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>
{
    public T17 Item17 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>
{
    public T18 Item18 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>
{
    public T19 Item19 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>
{
    public T20 Item20 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20>
{
    public T21 Item21 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21>
{
    public T22 Item22 { get; set; }
}

public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22>
{
    public T23 Item23 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23>
{
    public T24 Item24 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24>
{
    public T25 Item25 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25>
{
    public T26 Item26 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26>
{
    public T27 Item27 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28>:
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27>
{
    public T28 Item28 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29> : 
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28>
{
    public T29 Item29 { get; set; }
}


public class Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23,T24, T25, T26, T27, T28, T29, T30> :
    Caddy<TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, 23, T24, T25, T26, T27, T28, T29>
{
    public T30 Item30 { get; set; }
}

*/
```

**Expected Behavior**:
Compilation of ALL types in a usable time frame.

**Actual Behavior**:
Exponential time increase with each added generic type argument

**Comment by jjonescz** [comment] 2023-08-24 10:34
Thanks for reporting this. Looks like a duplicate of https://github.com/dotnet/roslyn/issues/69515.

**Closed by jjonescz** 2023-08-24 10:34 UTC
Labels: Area-Compilers, untriaged
