### ISSUE TITLE
Introduce constant copies trivia twice

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1016] opened 2015-03-04 18:28 UTC
Ported from TFS WorkItem: **1065689**

---

**Repro Steps:**

Select highlighted text and Ctrl + . and invoke fix to introduce local constant, where `[|` and `|]` denote the start/end of the highlight:

``` VB
Private Function GetX() As Object
    Return [|"c d
" + ' comment
"a
b" ' comment|]
End Function
```

Notice that the second comment ends up getting inserted twice:

``` VB
Private Function GetX() As Object
    Const V As String = "c d
" + ' comment
"a
b" ' comment
    Return V ' comment
End Function
```

**Revisions:**
1) Created By Shyam Namboodiripad (10/16/2014 11:52:37 PM)

---

2) Edited By Brett Forsgren (11/5/2014 10:37:14 AM)

Resolved with changeset 1366956: When introducing a variable, don't duplicate the trivia.

---

3) Edited By Shyam Namboodiripad (11/14/2014 12:38:51 PM)

We no longer copy the trivia twice. However, the second comment is not being carried along to the extracted local (even though I include this comment in my selection). Instead this comment is tacked on to the end of the return statement which seems wrong

---

4) Edited By Kevin Pilch-Bisson (2/16/2015 12:21:36 PM)

I'm willing to live with this for RTM, but can you port to GitHub and put in the &quot;Unknown&quot; milestone and add the &quot;Up for grabs&quot; tag.

---

**Comment by keyboardDrummer** [comment] 2016-09-14 10:40
@shyamnamboodiripad You mention the comment is 'tacked on the end of the return statement'. However, the comment was already at the end of the return statement before the refactoring.

I guess since the return expression and the return statement both end at the same location, but the expression starts later, you could say the comment is closer to the expression than the statement, thus you want the comment to move with the expression and not stay with the statement. Is that your reasoning?

Or is it simply that because you selected the comment as well that you want it to move with the expression?

**Comment by Neme12** [comment] 2018-03-25 04:27
Can't reproduce.

**Comment by Youssef1313** [comment] 2021-03-06 17:51
I can't reproduce as well. This probably was fixed in past. @jinujoseph Should this be closed?

**Comment by CyrusNajmabadi** [comment] 2022-02-04 17:26
I don't repro this.  I get:

![image](https://user-images.githubusercontent.com/4564579/152574685-0f8ac767-ff09-4982-b902-1455a8ade676.png)

Closing out.

**Closed by CyrusNajmabadi** 2022-02-04 17:26 UTC
Labels: Bug, help wanted, Area-IDE
