### ISSUE TITLE
Collection initialiser of struct via extension method should compile when using ref this

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#25862] opened 2018-03-31 14:35 UTC
**Version Used**:

VS 15.6.4, LangVersion 7.2

**Steps to Reproduce**:

Given:

```c#
public struct MyStruct : IEnumerable
{
    public int Sum { get; set; }

    IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
}

public static class MyStructExtensions
{
    public static void Add(this MyStruct s, int i) => s.Sum += i;
}
```

The following code compiles and prints zero twice, as a copy is modified:

```c#
var s1 = new MyStruct();
s1.Add(1);

var s2 = new MyStruct { 1 };

Console.WriteLine(s1.Sum);
Console.WriteLine(s2.Sum);
```

7.2 introduces `ref this`. However if you add a `ref` modifier to the `this` parameter, the `s2` construction no longer compiles:

> CS1510: A ref or out value must be an assignable variable

The first form compiles and prints one.

**Expected Behavior**:

Should be able to compile second form.

**Actual Behavior**:

The second form won't compile.

**Comment by jcouv** [comment] 2018-03-31 17:00
Tagging @VSadov

**Comment by jaredpar** [comment] 2018-08-31 16:40
Looks like this is fixed now. 

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUKRZQHQDCA9hhnAMYxoOAOyh1GAZgoAmMmzIBvBmWUVJRACxkAsgAoAlAqUrjANwgIyUSmQC8ZIXADu2gJ4BlGAgCu/fWKssAILY2DqUemIMZhZQMnYOzlrunj4wCmTWAL5ixpkMefQMRJKw3vyuHmVpIMziDIr0xsVkaEJpbl5g6QDmcDDUln0DBUbKAJIAokKdiBAwHBZU4iwA4n1TMwhzC/q2AHxkMAAWCBzOCWQAchwwY2AADjxgcG1w2BMAHrxw9wLCfvkGEU1JQAGzSCopfifeAiQQieqjVTMcEaMjBULHNBQSFVSxIFptFoGGwHKAsDpdPB2NBiTJAA==

We should add a test to ensure this behavior persists.

**Comment by alrz** [comment] 2018-08-31 16:44
I think the issue is with a `ref` extension: [modified example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWACg9CiA6AYQHsAbZuAYxgEtGA7KclQDMhAEz56+AN6V8cwiOwAWfAFkAFAEpplAJC6AbhAT4o4gLz5ecAO5qAngGUYCAK6dp+IvgC+g+b6UPpSU2CKwbh6qTi7uMPggNEKUMhQBYfhcvPGOrmCeAOZwMCSmxaXBFLLyAJIAorx5iBAwjCbEQrQA4sUNTQgtbVr45gB8+DAAFgiMdtZ2AHKMMDVgAA5sYHDZcCh1AB7scGvcfFqClaGKRABsYg7OkTAH8Pw8/CnVchnEd8r4AEEUCh1Ag4AAzCaTLhQB6xDxQJCZbKZbRjUy0XL5dCWLgXIA==)

**Comment by jaredpar** [comment] 2018-08-31 16:45
@alrz indeed it is. My mistake.

**Closed** 2018-10-19 19:38 UTC
Labels: Area-Compilers, Bug
