### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit32 on PR #9208

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#9349] opened 2016-03-01 19:03 UTC
PR: [#9208](https://github.com/dotnet/roslyn/pull/9208) *don't assume all reference spans in an inline rename session are projected into the current view* by @brettfo
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4598/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent_1

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by brettfo** [comment] 2016-03-01 19:04
Could be related to my PR.  Assigning myself and investigating.

**Comment by davkean** [comment] 2016-03-01 19:09
Could be a dupe of https://github.com/dotnet/roslyn/issues/9298.

**Comment by jasonmalinowski** [comment] 2016-03-01 19:31
Closing in favor of #9308

**Closed by jasonmalinowski** 2016-03-01 19:31 UTC
Labels: Bug, Flaky, Urgency-Soon
