### ISSUE TITLE
Ctrl+. to configure severity not write into .editorconfig file

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#52763] opened 2021-04-20 03:47 UTC
**Version Used**: VS 16.9.4

**Steps to Reproduce**:

1. Create a c# project and a method `void foo () { }`
2. Put caret in `foo` and press `ctrl + .`
3. In menu, navigate to `disable or configure... > configure xxx severity > None` and click

![image](https://user-images.githubusercontent.com/12094247/115334493-0f7b3600-a1ce-11eb-9263-9993997b169c.png)

**Expected Behavior**:
append a `dotnet_diagnostic.xxx.severity = none` into the `.editorconfig` file.

**Actual Behavior**:
`.editorconfig` file no change.

But if open the `.editorconfig` file before, it work.

**Comment by Youssef1313** [comment] 2021-04-20 06:04
Duplicate of https://github.com/dotnet/roslyn/issues/45417

**Closed** 2021-04-20 17:46 UTC
Labels: Area-IDE, untriaged
