### ISSUE TITLE
"Derived Types" in Solution Explorer doesn't show all types

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7972] opened 2016-01-14 23:39 UTC
1. Open Roslyn in Roslyn. I was running the Update 1 bits, and was synced to 4f7ee0f0ec0189f91d6ad06e7a090374a5b93216.
2. Find Workspace.cs, and expand the file to see the class in Solution Explorer.
3. Right click on the class, choose Derived Types.

*Expected:* I should see many types, since we have many derivations.
*Actual:* I see just this:

![image](https://cloud.githubusercontent.com/assets/201340/12341226/e9c0e47c-bad4-11e5-966e-4c7d087b7b82.png)

**Comment by Pilchie** [comment] 2016-01-14 23:45
Dupe of #4973?

**Closed** 2016-01-15 17:14 UTC
Labels: Area-IDE, Bug
