### ISSUE TITLE
IDE0001 incorrect when converting to nullable reference type

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#37980] opened 2019-08-14 13:14 UTC
**Version Used**: `VisualStudio.16.int.d16.3/16.3.0-pre.3.0+29213.96.d16.3` with `Microsoft.Net.Compilers` package version 3.3.0-beta3-19407-05

**Steps to Reproduce**:

```c#
class C
{
    public Task<string?> M(string s)
    {
        return Task.FromResult<string?>(s);
        //                    ^^^^^^^^^ IDE0001 Name can be simplified
    }
}
```

Removing the code marked as redundant gives:

```c#
class C
{
    public Task<string?> M(string s)
    {
        return Task.FromResult(s);
        //     ^^^^^^^^^^^^^^^^^^ CS8619 'Task<string>' does not match 'Task<string?>'
    }
}
```

**Expected Behavior**:

No diagnostic.

**Actual Behavior**:

Diagnostic.

**Comment by CyrusNajmabadi** [comment] 2019-08-14 19:02
Tagging @jasonmalinowski

**Comment by jasonmalinowski** [comment] 2019-08-14 19:39
This is conveniently the exact bug @ryzngard was looking at.

**Comment by ryzngard** [comment] 2019-08-14 19:49
Yup. Dupe of #33079

**Closed by ryzngard** 2019-08-14 19:49 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, New Language Feature - Nullable Reference Types, Resolution-Duplicate, help wanted

**Comment by drewnoakes** [comment] 2019-08-14 22:14
Thanks for duping. I did search but failed to find the other bug. That's from back in February, yet we've only just started seeing this on recent builds.

**Comment by davkean** [comment] 2019-08-28 06:48
@ryzngard Before I dupe this, did you also fix the cast version as called out in: https://github.com/dotnet/roslyn/issues/38331?

**Comment by ryzngard** [comment] 2019-09-03 18:53
@davkean  yup, cast is handled correctly as well. Manually tested today with `return Task.FromResult((string?)"something");` and didn't see any simplification.
