### ISSUE TITLE
Show CodeLens for field

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#44254] opened 2020-05-14 15:30 UTC
`public string Description = ".....";`

When I modify the value of `Description`, I want to view its history value by git, but there's no CodeLens for field, so I can't view the field history by git.

**Comment by sharwell** [comment] 2020-05-14 15:44
Duplicate of #23908

**Comment by sharwell** [comment] 2020-05-14 15:44
@CreateAndInject this is effectively a duplicate of a previous issue. I'm going to widen the title of the other issue so it's clear both apply.

**Closed by sharwell** 2020-05-14 15:44 UTC
