### ISSUE TITLE
C# IntelliSense no longer have an option to only trigger on "Enter or Tab"

### ISSUE THREAD

**Issue by zinvob** [dotnet/roslyn#5200] opened 2015-09-13 18:33 UTC
There is nothing worse than an editor that autorandomly put in words that you did not enter. Default behaviour in 2015 now autoselect IntelliSense no matter how different the word selected is when you press space. So I could be typing "from <space>" starting a linq query, and suddenly the editor has changed it to "RemoveTextFromCardSupplierName<space>". Sometimes it selects what I want it to select, but this has random behaviour, and force me to always read what IntelliSense wants to enter. Reading this and pressing Esc every time it select wrong are very annoying and slows down my writing bigtime.  I would go as far as to say that the complete IntelliSense experience is ruined, and I really only want to turn the whole thing off.

Please give us back the "Only use Tab or Enter to commit" for C#. It's available for JavaScript, but not C# any more.

This is a very urgent issue.

**Comment by sharwell** [comment] 2015-09-13 18:44
Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd> to toggle this mode on and off.

**Comment by zinvob** [comment] 2015-09-13 18:56
Thanks, this really saved my day. But is this not a very hidden feature? Easy now when I know about it, but how could anyone know about this from using the IDE?

**Comment by diryboy** [comment] 2015-09-14 06:15
>  I could be typing "from " starting a linq query, and suddenly the editor has changed it to "RemoveTextFromCardSupplierName".

Typing spaces and operators to commit and get nice format is always a big :+1: for me to use VS. The accident you described here looks more like a bug to me, as the fully matched item should be preferred. Was there a "from" item in the list?

**Comment by zinvob** [comment] 2015-09-14 06:36
If the IntelliSense was always correct, then this would be a plus. But this will never be the case. In the case above, the IntelliSense did not even detect that it was inside a linq query, there was no "from" in the list. But this occur in many areas. Even if those areas was fixed, you always have people like me who don't finish up the uses list and resolve it after typing to auto add in uses (cost less than jumping up to the header to write it). It cost me nothing to press enter to select IntelliSense, because that will be consistent and fixed behaviour. The auto select is fluid and random. It could work when you write slow if you always look at the IntelliSense. If you write fast, you will not be able to read the IntelliSense before it's to late.

**Comment by Pilchie** [comment] 2015-09-14 14:46
@zinvob: Please let us know the specific case where `from` was missing from the list if you can recall it, as our goal is never to have valid entries missing from the list.

**Comment by Pilchie** [comment] 2015-09-14 16:46
We think adding an option here that would be persisted and roam would be a good idea.

**Comment by lorcanmooney** [comment] 2015-09-21 22:54
I'd also like to see this, but for slightly different reasons. When I write code, it doesn't always happen in the order the compiler would like to see, more stream-of-consciousness. I routinely type out assignments and use variable as parameters before I've actually declared them. More often than not VS2015 "corrects" these references some other pre-existing identifier. Compounding this, whatever fragment matching algorithm is used seems to be much more lenient than in VS2013 (a good thing in most other cases).  
For now I've found turning IntelliSense off to be a better experience.

**Comment by Pilchie** [comment] 2015-09-21 23:00
As @sharwell suggests, I would try "Suggestion Mode" IntelliSense, by hitting  <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd>, or pressing the toolbar button:

![suggestionmode](https://cloud.githubusercontent.com/assets/312835/10007409/d3869ca2-6079-11e5-895e-68d3a2d8db75.png)

**Comment by zinvob** [comment] 2015-09-24 07:02
Extra sidenote: When using Suggestion Mode, it's not possible to press "Enter" to select IntelliSense, I have to use Tab or press up/down arrowkeys first. So even Suggestion Mode is not as it used to be.

Rule of thumb: Any automatic typing behaviour in the IDE must have a setting to be turned off, and have this remembered when restarting the IDE.

Another big frustration for me is automatic end bracket and end ", I can't find any way to turn those off. I often wrap codelines inside IF after they are written, so when I complete the IF and press { I always get } that needs to be deleted before moving to the end of the code to write }. Same could happen with ". It's not smart enough to be automatic, it never will be.

**Comment by diryboy** [comment] 2015-09-24 11:07
I remembered that in old version of VS the commit characters are configurable, but since I prefer the current aggressive mode, I'm ok with this, well, except when working with VB in unfamiliar codebase.

I believe automatic brace completion can be turned off from Options > Text Editor > C# > General

**Comment by zinvob** [comment] 2015-09-25 08:25
I thought that only turned off the {}. Works good enough now. Brace completion could actually work for most situations if they also supported automatic adding of start brace.
Example:
if (somecondition)
code
code
<- enter }
auto behaviour traverse back to find first logical place for brace start and format ends up with
if (somecondition)
{
  code
  code
}

This will cover my normal usage. I wrap existing code or write new.

**Comment by Joe4evr** [comment] 2015-09-25 08:37
@zinvob When you write `if` and double `tab`, the IDE will automatically insert the snippet
```
if (true)
    {

    }
```
with the cursor selecting `true`, so you can immediately write your condition. When you then press Enter, it'll move the cursor into the braces. Does that sound like the kind of behavior you want?

**Comment by zinvob** [comment] 2015-09-25 08:46
No, this will not cover when I want to wrap existing code inside an IF. But the functionality I described will.Lets say I have

code1
code2
code3
code4

Then I want to put code2 and code3 inside an IF. Then I could insert "if (condition)" between code1 and code2, move down and insert } between code3 and code4 and have the start brace added. If this is implemented, normal auto add close bracket will not annoy because I don't need to write the start bracket in this case.

**Comment by diryboy** [comment] 2015-09-25 09:26
You can select the lines and press <kbd>Ctrl</kbd> + <kbd>K</kbd>, <kbd>Ctrl</kbd> + <kbd>S</kbd>, then type `if` and choose

**Comment by zinvob** [comment] 2015-09-25 09:59
dirtyboy: Could help maybe if the "if" wrap could be connected directly to a shortcut. But still will not help for the last scenario I described, adding extra code to a oneliner if. It also gives more work, selecting the text and walk down the different menu sections to find "if". I will use less time just writing if even when I have to delete the } bracket and write } at the end instead of doing this select, shortcuts, find if in menus and then write the contain part of if.

**Comment by balajikris** [comment] 2015-09-28 20:49
I've forked off the Brace completion related discussion into a new issue, since its a completely different feature and this issue seems to have been opened mainly for Intellisense. Thanks for the feedback, the idea to support auto adding open brace is interesting :smile:

**Comment by lorcanmooney** [comment] 2015-09-30 20:02
@Pilchie This definitely is an improvement (when I remember to turn it on) but as @zinvob says, using the return key is no longer an option. This is hardwired into my muscle memory by now, and is one reason these sort of changes are really frustrating.  
One other little thing I've noticed is that in suggestion mode, the entry isn't highlighted, it just has single pixel outline. This has been surprisingly disconcerting. I've repeatedly had to do a double take to make sure what I actually want will be inserted.  
Given time I'm sure I'll get used to these, but I hope the team gives adequate consideration to the impact of changes like these, and the years of muscle memory such changes instantly invalidate.

**Comment by Pilchie** [comment] 2015-09-30 21:26
Can people elaborate on what option is missing?  This is the IntelliSense options page for VS2013:

![image](https://cloud.githubusercontent.com/assets/312835/10207103/3cfa0c76-677f-11e5-8d45-034d27eec9b6.png)

What did people change to get the behavior they claim is lacking now?

**Comment by Pilchie** [comment] 2015-09-30 21:27
I assume you uncheck committed by pressing the space bar and clearing the list of commit characters?

**Comment by lorcanmooney** [comment] 2015-09-30 22:05
Yes, that's exactly how I had it set.  
Personally I'll be happy if/when the suggestion mode becomes sticky. An option to use Enter for completion in that mode would be nice, but obviously I'll learn to live without it.  
Please don't take this as criticism, it's just feedback which may or may not be useful to the team when assessing the impact of what otherwise seems like a small change.

**Comment by zinvob** [comment] 2015-10-01 09:44
This is also how I had it set. Your option for Enter or Tab inside Javascript would be the best fit though. I'm used to using Enter as the select button (makes it the same for all development environments). How you want to do this is up to you, but if you just want to have the suggestion mode, make it remember if it's on or off when you close down the environment and also have Enter for commit.

It would be nice to have some consistency in the IntelliSense settings, so I would prefer the option provided in JavaScript for normal IntelliSense mode.

**Comment by diryboy** [comment] 2015-10-01 10:07
I used to use all the VS2013 listed commit chars, plus enter for unfamiliar codebase, saving a lot of keystrokes for me, I have to turn this on for JavaScript every time before using any new VS installation, haha

**Comment by Dunkhan** [comment] 2018-10-24 10:44
So to summarise this issue: 

There is a problem that suggestion mode state is not persistent and needs to be turned on every time the user starts the application.

It was pointed out https://github.com/dotnet/roslyn/issues/5200#issuecomment-144547545 that there are quite powerful persistent settings for regulating this behaviour. 

For some reason the issue was never closed, nor was any fix proposed or implemented.

During the 3 years since this was reported, all persistent settings under "Selection in completion list" have been removed, meaning the user now has less control over the behaviour of auto-complete than in previous versions.

Suggestion mode state is still not persistent and needs to be turned on every time the user starts the application.

People who do not wish to have auto-complete automatically insert code into their work, or to control when and how it does this, have to constantly remember to turn on suggestion mode every day. People who want finer control are out of luck.

**Comment by zinvob** [comment] 2019-03-07 09:13
Why is this still an issue? They destroyed IntelliSense with 2017, and never fixed it. This should be of high priority. It's a daily frustration when suggestion mode suddenly is not active and random tekst is entered into the editor while writing. NEVER should you be locked to write "a." and get something else. People that want this annoyance may select it, but it should not be forced on you. Number >1< priority of an editor should be that you can be 100% certain that what you type is what get's written.

This is 100 times more important than any of the new features in 2019..

**Comment by zinvob** [comment] 2019-03-07 09:17
This is not a feature request, it's a bug. It worked properly before, but you ruined it in 2017, and it's still there in 2019.

**Comment by Dunkhan** [comment] 2019-05-15 12:12
Suggestion mode is now persistent in 2019. That does not resolve this issue but it makes it much less frustrating.

**Comment by sharwell** [comment] 2019-05-15 12:20
@zinvob my understanding from the final comment is the issue has been corrected for Visual Studio 2019.

1. The requested option is available under **Edit &rarr; IntelliSense &rarr; Toggle Completion Mode**
2. The option persists across Visual Studio restarts

This option is provided by the core Visual Studio editor, and we are just using it. If both of the above items are correct, then the current behavior would be by design *but* if you find it not usable I would recommend you [submit a feedback item](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) requesting the option move to a better location and/or be renamed so it's easier to find. The menu placement is handled by a different team in Visual Studio, and the feedback item would be the best way to make sure they see that request.

**Closed** 2021-09-16 02:02 UTC
Labels: Area-IDE, Feature Request, Need More Info, fabric-bot-test
