### ISSUE TITLE
Build should fail when EditorConfig rules are violated

### ISSUE THREAD

**Issue by pyce-lb** [dotnet/roslyn#49635] opened 2020-11-26 17:12 UTC
**Version Used**:
- VS version: 16.8.2
- Build Engine version: 16.8.0+126527ff1
- SDK version: 5.0.100

**Steps to Reproduce**:

_.editorconfig_
```
root = true

# All files
[*]

#### Core EditorConfig Options ####

# New line preferences
end_of_line = crlf
trim_trailing_whitespace = true

#### C# Coding Conventions ####

# 'using' directive preferences
csharp_using_directive_placement = inside_namespace:error
```
_Program.cs_
```
using System;

namespace NET5.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine("Hello World!");                       
        }
    }
}
```
_ConsoleApp.csproj_
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>

    <!--Has no effect in this scenario-->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
```

**Expected Behavior**:
Given the example code above building the project from command-line or through VS should fail with one (or more) errors.

**Actual Behavior**:
_VS Output (Build) window_
```
1>------ Rebuild All started: Project: ConsoleApp, Configuration: Debug Any CPU ------
1>ConsoleApp -> C:\ConsoleApp\ConsoleApp\bin\Debug\net5.0\ConsoleApp.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
_Command Prompt (dotnet build)_
```
C:\ConsoleApp\ConsoleApp>dotnet build ConsoleApp.csproj
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp -> C:\ConsoleApp\ConsoleApp\bin\Debug\net5.0\ConsoleApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.87
```

**Comment by jinujoseph** [comment] 2020-12-01 19:31
Duplicate of https://github.com/dotnet/roslyn/issues/33558

**Closed by jinujoseph** 2020-12-01 19:31 UTC
Labels: Area-Analyzers, Feature Request

**Comment by pyce-lb** [comment] 2020-12-04 19:10
> 
> 
> Duplicate of #33558

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/33558#issuecomment-690347050_
> I am going to close this issue as no further feature work is required, **please file separate Rolsyn issue(s) for anything that does not work as expected** and doc issues at the above page if you need more clarity on documentation.

**Comment by mavasani** [comment] 2020-12-04 19:14
@pyce-lb Kindly read the `Severity` section at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/language-rules#option-format. That para also references the github issue that tracks deprecating the editorconfig option syntax for specifying severity as part of option specification, which is not understood by the compiler.

**Comment by mavasani** [comment] 2020-12-04 19:16
Additionally, please follow the steps at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/overview#code-style-analysis for correct way to enforce code style rules on build. Specifically, note the step 2, you will need to specify `dotnet_diagnostic.IDxxxx.severity = warning" or `dotnet_diagnostic.IDxxxx.severity = error", where `xxxx` is the diagnostic ID, to enable build enforcement.

**Comment by pyce-lb** [comment] 2020-12-04 19:44
@mavasani thank you for your quick response!
If I understand correctly there is no way to set the severity for some naming rules to error and for some others to silent separately yet still enforce the build to fail if any of the rules with severity level error are violated because they are "handled" by the same IDxxxx rule, in this case [IDE1006 (Naming rule violation)](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#rule-id-ide1006-naming-rule-violation); am I correct?
If yes, are there any plans to be able to handle the severity levels for such naming rules or code style options separately yet still enforce them during build?

**Comment by mavasani** [comment] 2020-12-04 19:50
> If I understand correctly there is no way to set the severity for some naming rules to error and for some others to silent yet still enforce the build to fail if any of the rules with severity level error are violated because they are "handled" by the same IDxxxx rule, in this case IDE1006 (Naming rule violation); am I correct?

Yes, that is true. One thing that might work for you is set `dotnet_diagnostic.ID1006.severity = warning` so the compiler enables naming styles analyzer on build, and then override specific naming style option syntax to different severity per rule, say `dotnet_naming_rule.types_should_be_pascal_case.severity = suggestion` or `dotnet_naming_rule.types_should_be_pascal_case.severity = error`. Latter is more specific configuration and should override the `dotnet_diagnostic` based severity entry, which is primarily needed to indicate to the compiler to turn on this analyzer on command line builds.
