### ISSUE TITLE
Sourcelink does not debug merged partial classes

### ISSUE THREAD

**Issue by daltzctr** [dotnet/roslyn#74787] opened 2024-08-16 17:00 UTC
**Version Used**: 
.NET 8.0.303

**Steps to Reproduce**:

1. Create a project that targets multiple platforms (MAUI)
2. Create a reference to a partial class inside of a library with sources.
3. `Ctrl + Click` into it and you only get the definition for the base partial class, not the merged class.

https://github.com/user-attachments/assets/a2f997e0-bc50-471f-9560-d75e1503977c

**Expected Behavior**:

I would expect `Ctrl + Click` to go to the merged partial class based on the current selected platform (Windows vs Android, etc).

**Actual Behavior**:

It only shows the base partial class, which is pretty useless for debugging external code that makes use of partial classes.

**Comment by davidwengier** [comment] 2024-11-26 02:45
This is by design. Since SourceLink shows actual source code as originally written by the developer, the notion that it would show "merged" source doesn't make sense. Turning off SourceLink and navigating to decompilation is probably more what you want here.

**Closed by davidwengier** 2024-11-26 02:45 UTC
Labels: Area-IDE
