### ISSUE TITLE
ThreadAbortException caught without rethrow

### ISSUE THREAD

**Issue by rominator1983** [dotnet/roslyn#8800] opened 2016-02-17 14:29 UTC
I posted an issue in https://github.com/dotnet/coreclr/issues/3155 but it looks like this is a Roslyn/C#-6 issue after all.

Following is the wrapped up description from https://github.com/dotnet/coreclr/issues/3155

Colleagues of mine had an isse with a ThreadAbortException (used heavily in ASP.NET)
The exception was caught in a catch-block "catch (ThreadAbortException)" or "catch (Exception)". As you know the exception has to be rethrown by the runtime after the finally block even if there is no "throw;"-statement in the catch-block. This was not the case on a testing machine which resulted in unexpected behaviour.
The build was done with   AnyCPU, 64-bit AppPool

This happened with a C#6-build (Release-Configuration, AnyCPU), .NET 4.5.x-Runtime (Target). It ws tested on an IIS in a 64-Bit App-Pool. This does not happen with C#5-Builds of VS 2013.
So it seems like a problem with the C#6-Output (or the Roslyn-Output in general)
We do not have a repro-sample at the moment since this happened on a testing-machine in a complicated try/catch-scenario.

The work-around was to add a "throw;"-statement in the "catch (ThreadAbortException)"-block. This should not be needed! This behaviour can be problematic if there is a "catch (Exception)"-block without a "throw;".
This can obiously break the standard ASP.NET-behaviour and cause havoc in IIS!

Can anyone look into this?

Thank you and kind regards

**Comment by VSadov** [comment] 2016-02-17 18:01
This would need an example of "complicated try/catch-scenario". Such issues could be hard to reproduce based on description.

4.5.x JITs have subtle bugs in this area and it is possible to step into those bugs either in VS2013 or VS2015. 
Since 2015 optimizes more aggressively it would be easier to hit the bug in 2015. There is compensating code in 2015 that detects and avoids problematic cases, but it is possible it can be circumvented with some convoluted mix of try/catch/finally/goto.
I am afraid we could be dealing with such case here.

**Comment by MichaelKetting** [comment] 2016-02-24 07:06
@VSadov We are currently working on a repro but yes, it isn't that easy. e.g. it looks like it might only happen in IIS, or at least, it requires a specific thread/catch nesting that's more complicated than the scenarios we spiked in the console application repro.

**Comment by jaredpar** [comment] 2016-03-04 20:35
I'm curious why this is being filed as an issue against Roslyn.  The CoreCLR issue identified the root behavior as a RyuJIT bug.  Roslyn's participation was to no longer generate the IL pattern that exposed the RyuJIT bug.  The IL emitted by Roslyn was itself valid, it just exacerbated the underlying issue.   That work was completed prior to Roslyn RTM hence I'm unsure what this issues is intended to track.

https://github.com/dotnet/roslyn/commit/800424953aafb7ec0efbe573bd3105141ace2d03#diff-39b235f45425a68082796f69f494d282

**Comment by MichaelKetting** [comment] 2016-03-04 21:16
It was never a CoreCLR issue. It was only filed over there because CoreCLR was mistaken for the .NET 4.5.2 CLR. 

The issue can only be reproduced on a system that uses .NET 4.5 x64 without RyuJIT installed, provided that the code was compiled with Roslyn.

**Comment by jaredpar** [comment] 2016-03-04 21:23
> It was never a CoreCLR issue. It was only filed over there because CoreCLR was mistaken for the .NET 4.5.2 CLR.

The CoreCLR team identified the original issue as a bug in the JIT.  Perhaps they mislabeled it as RyuJIT.  But @jkotas did positively identify this as a known bug in desktop CLR which repro'd prior to 4.6.  Given the information in your bug it seems likely this is the issue he identified.  

It's possible there is a Roslyn bug here, although it seems unlikely.  But I would expect in such a case that we've emitted unverifiable code.  That should be relatively easy to detect if you have a repro we can look at.

**Comment by MichaelKetting** [comment] 2016-03-05 12:51
@jaredpar Thanks for persisting on this. I managed to miss jkotas's response on the other thread and am sorry for that. I'll quote it here to make tracking this easier by consolidating the threads. I hope that's all right. 

by @jkotas in https://github.com/dotnet/coreclr/issues/3155#issuecomment-185316493
> This looks related to a known issue that was fixed in .NET Framework 4.6.
> 
> Roslyn C# compiler used to generate a slightly different IL code for complex exception handling clauses. It exposed bugs in how JITed code deals with thread abort handling. This issue was fixed both:
> 
> * In RyuJIT: Generate code that handles thread abort properly (https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L7805)
> * In Roslyn: Do not generate the IL code that exposes the JIT bug (https://github.com/dotnet/roslyn/blob/7acf8dd1a6db27faf922db16bd2de133d9860769/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs#L607).
> 
> The JIT fix was done by @BruceForstall (TFS bug #1088278), the Roslyn fix was done by @VSadov (TFS bug #1088278).
> 
> Can you check whether the Roslyn compiler that you are using contains the above fix?

We're haven't been able yet to do a repro that doesn't include 100MB of dll's yet hosted in IIS, but jkotas' response on this already having been fixed might be a clue. I will have to track the exact versions down when I'm back in the office next week, but I believe we repro'ed it both with a build using the MSBuild Tools 2015 as well as a dev-build done with Visual Studio 2015 Update 1 since that was what was current when we found the issue. As I said, I will need to verify with my colleagues the exact versions installed.

In the mean time, @jkotas, I'm not sure how the TFS revision numbers link to the release versions of Visual Studio 2015 and the MSBuild Tools. Help there would be very much appriciated.

Best regards, Michael

**Comment by jkotas** [comment] 2016-03-06 08:15
These fixes are included in .NET Framework 4.6 and VS2015.

**Comment by MichaelKetting** [comment] 2016-03-06 09:12
Thanks for confirming this. This means we definitely found additional issues since I know we have the RTM versions installed at the very least.

**Comment by MichaelKetting** [comment] 2016-03-07 14:43
Okay, the test machine used .NET 4.5.1 (v4.5.50938). 
One build machine used MSBuild Tools 2015 (v14.0.23107.10) and a direct call to MSBuild.
The other build machine used Visual Studio 2015 Update 1 (v14.0.24720.00 Update 1)

A repro in .NET 4.5.2 wasn't done (yet) but I took away from this discussion that the fix is only in .NET 4.6 so the patch level of .NET 4.5 shouldn't matter.

**Comment by VSadov** [comment] 2016-03-08 19:23
From what I see, we have a case where there is a snippet in your code that when compiled with Roslyn compiler, hits a bug in JIT64 in 4.5

This kind of bugs are typically not contextual. The surrounding 100Mb of code is most likely irrelevant, but there is a convoluted combination of  try/catch/switch/goto or some other control flow that is supposed to operate with ThreadAborts and which causes this behavior.

I see the following options to go forward:
1 - you can try switching to 4.6 and see if that helps (not sure if it is feasible on your side)
2 - Roslyn compiler is changed to workaround the bug in JIT64 from 4.5 when compiling the snippet.
3 - the snippet is modified to no longer hit the bug

For the 2 and 3 we need to know how the unfortunate snippet looks like. 
There is already code in the compiler to detect cases which could hit the JIT bug, but for whatever reason yours is getting through.

**Comment by MichaelKetting** [comment] 2016-03-09 16:38
@VSadov Yes, so far, your analysis is correct.

Going forward:
1) Yes, exactly. We still have customers using .NET 4.5 and can't just change the requirements of our product version in between major upgrades.

2) That's what we're hoping for once we can reproduce it in a smaller sample :)

3) That's easy, theoretically. We just have to add 'throw' statements where they are missing in case of a ThreadAbortException. The problem is that this is something no one had to watch out till now and would have to be an continuing effort across all our projects. So, that's not our preferred way out of this.

Now, for the snippet: We've been trying to build a repro but all bottom-up approaches have failed so far. We're now at the point where we will start cutting away from the 100MB solution until the problem disappears and we figure out what the repro was missing. 

Also, the assembly where the 'throw' was missing does not produce any warnings or errors in peverify.

**Comment by MichaelKetting** [comment] 2016-03-10 08:52
Okay, I have sort of good news. While the bug is still elusive, we where able to determine that it doesn't happen with Visual Studio 2015 Update 1.

Complete version spec:
Issues exists:
MSBUILD.exe: 14.0.23107.0
CSC.exe: 1.0.0.50618
(aka MSBuild Tools 2015 RTM)

Issue resolved:
MSBUILD.exe 14.0.24723.2
CSC.exe: 1.1.0.51204
(aka Visual Studio Update 1)

Now, for the next problem: The official download for the MSBuild Tools (https://www.microsoft.com/en-us/download/details.aspx?id=48159) does not offer a version newer than the RTM version. We now have to manually copy the MSBuild folder from a Visual Studio 2015 Update 1 installation onto our build agents. @VSadov  Could you please point me to the download for MSBuild Tools 2015 Update 1 so we can track the installed version in an offical manner (i.e. via Programs & Features dialog / the Registry)?

@jkotas I also looked into the fix you mentioned (https://github.com/dotnet/roslyn/blob/7acf8dd1a6db27faf922db16bd2de133d9860769/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs#L607) and noticed that it's date is January 2016, well after both the RTM and the Update 1 release. Am I correct in assuming that this fix is not actually included in any released version of MSBuild Tools? Which in turn means that some other fixe between RTM and Update 1 solved this, although I have no idea which one :)

**Comment by MichaelKetting** [comment] 2016-03-31 07:39
The installer for MSBuild Tools 2015 Update 2 is now available: https://www.visualstudio.com/downloads/download-visual-studio-vs (you need to drill down into "Tools for Visual Studio 2015" -> "Microsoft Build Tools 2015" or use this download link: https://go.microsoft.com/fwlink/?LinkId=615458)

I think this issue can be resolved now.

**Comment by jaredpar** [comment] 2016-05-09 17:13
Closing per comment.

**Closed by jaredpar** 2016-05-09 17:13 UTC
Labels: Area-Compilers, Need More Info

**Comment by MichaelKetting** [comment] 2016-07-18 09:15
@jkotas / @VSadov I would like to please re-open this issue. It turns out that the bug wasn't fixed with Update 1 (or Update 2, Update 3), but due to the complexities of the reproduction, there was a false negative when testing for this problem.

I've now been able to set up a repro-sample that contains the minimum logic to sensibly show the issue: https://github.com/MichaelKetting/RoslynIssueReproduction/tree/Roslyn-8800-ThreadAbortExceptionNotRethrownAfterCatch

I also added a Readme to explain the setup, the bug (the stuff in WebApplication), and a bit about what's going on in the code that showcases the issue. I think you should mostly need the first two bits, the code in WebLibrary itself is mostly there to provide underlying logic in which the issue manifests itself. If you need more/better details on what's going on in the code, I can certainly provide them, but given that's it's a WebForms + stateful web application infrastruture, I was trying to keep the focus on where I think the issue actually happens not the hubbub around it.

Best regards, Michael

**Comment by MichaelKetting** [comment] 2016-07-19 05:44
@jaredpar I'd like to please re-open this issue (please see previous comment for details).

Thanks, Michael

**Comment by jaredpar** [comment] 2016-07-19 05:47
@MichaelKetting why specifically should we reopen the Roslyn issue though?  Based on all of the samples we've seen Roslyn isn't at fault.  There was some legal IL we emitted previously that wasn't handled well by the JIT.  We've since added a work around and as far as I can tell we are still emitting that work around correctly.  Hence if the issue is still showing up it would seem to be a CLR bug and better tracked in their repo.

Note: I haven't had a chance to look at your specific repo yet though (will do so later).  But if the IL doesn't have the appropriate work around could you paste it here so we can analyze what is going on?

**Comment by MichaelKetting** [comment] 2016-07-19 06:26
@jaredpar Thanks for the quick reply!

Ah, I see, I wasn't aware of that but simply went with the exclusion principle regarding what has changed. 

So, just to summarize, Roslyn is triggering a pre-existing bug in 64bit .NET 4.5 CLR that has since been fixed in 64bit .NET 4.6 CLR and isn't triggered by the old non-Roslyn C# compiler?

I'm quite happy to repost this in the correct CLR repo if that's where this will belong. Erm..., which one is it? Or rather, is the .NET 4.5 CLR actually on Github or just handled via Connect?

Regarding the IL: Sure, I can post some of the sample's IL, namely the method where the throw-statement is actually missing, but part of the problem is, that it needs the entire stack from the running web application to manifest itself. (Please note that if I remove the finally block, the bug will not manifest itself.)
```
    public override void Execute (WxeContext context)
    {
      try
      {
        base.Execute (context);
      }
      catch (ThreadAbortException)
      {
        // re-throw is missing, with C# 6 and .NET 4.5, the exception will not get re-thrown if there is a finally-block after this catch-block.
      }
      finally
      {
        // Prevent optimization
        Trace.Assert (context != null);
      }
    }
```

C# 6:
```
.method public hidebysig virtual instance void Execute(class [WebLibrary]Remotion.Web.ExecutionEngine.WxeContext context) cil managed
{
    .maxstack 2
    L_0000: ldarg.0 
    L_0001: ldarg.1 
    L_0002: call instance void [WebLibrary]Remotion.Web.ExecutionEngine.WxeFunction::Execute(class [WebLibrary]Remotion.Web.ExecutionEngine.WxeContext)
    L_0007: leave.s L_0016
    L_0009: pop 
    L_000a: leave.s L_0016
    L_000c: ldarg.1 
    L_000d: ldnull 
    L_000e: cgt.un 
    L_0010: call void [System]System.Diagnostics.Trace::Assert(bool)
    L_0015: endfinally 
    L_0016: ret 
    .try L_0000 to L_0009 catch [mscorlib]System.Threading.ThreadAbortException handler L_0009 to L_000c
    .try L_0000 to L_000c finally handler L_000c to L_0016
}
```

C# 5:
```
.method public hidebysig virtual instance void Execute(class [WebLibrary]Remotion.Web.ExecutionEngine.WxeContext context) cil managed
{
    .maxstack 2
    L_0000: nop 
    L_0001: nop 
    L_0002: ldarg.0 
    L_0003: ldarg.1 
    L_0004: call instance void [WebLibrary]Remotion.Web.ExecutionEngine.WxeFunction::Execute(class [WebLibrary]Remotion.Web.ExecutionEngine.WxeContext)
    L_0009: nop 
    L_000a: nop 
    L_000b: leave.s L_0012
    L_000d: pop 
    L_000e: nop 
    L_000f: nop 
    L_0010: leave.s L_0012
    L_0012: nop 
    L_0013: leave.s L_0025
    L_0015: nop 
    L_0016: ldarg.1 
    L_0017: ldnull 
    L_0018: ceq 
    L_001a: ldc.i4.0 
    L_001b: ceq 
    L_001d: call void [System]System.Diagnostics.Trace::Assert(bool)
    L_0022: nop 
    L_0023: nop 
    L_0024: endfinally 
    L_0025: nop 
    L_0026: ret 
    .try L_0001 to L_000d catch [mscorlib]System.Threading.ThreadAbortException handler L_000d to L_0012
    .try L_0001 to L_0015 finally handler L_0015 to L_0025
}
```
 
Best regards, Michael

**Comment by jkotas** [comment] 2016-07-19 09:27
Full .NET Framework is handled via connect or Microsoft support. It is not on github. 

Requests for backports of bug fixes to older versions of .NET Framework typically require high-enough level of Microsoft support contract. Unless you have Microsoft support contract, I think that upgrading to 4.6.x is your best way forward.

**Comment by MichaelKetting** [comment] 2016-07-19 09:49
@jkotas Thanks for the info! We're a Gold Partner with enough remaining Support Calls :) You don't happen to have a reference ID I could insert into the support call?

Regarding upgrade: The problem is the customer installation base. We planned on supporting .NET 4.5 and .NET 4.6 simultanously. Without this fix, this means we need to decide to stay on C#5 for the time being to remain completely safe.

**Comment by jkotas** [comment] 2016-07-19 11:58
> You don't happen to have a reference ID 

This is related to bug 1088278 in the internal bug database.

cc @cmckinsey @BruceForstall FYI - potential DTS bug related to thread abort handling.

**Comment by MichaelKetting** [comment] 2016-07-19 12:00
Thanks!

**Comment by BruceForstall** [comment] 2016-07-19 17:28
@russellhadley fyi
