### ISSUE TITLE
Go to All doesn't find methods with dot

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32687] opened 2019-01-23 02:30 UTC
Go to All used to find methods using dot syntax, like ClassName.MethodName.

Repro steps:
1.Create a Console App Project
2. Open Edit->Go To->Go To All (Or press 'Ctrl+F')
3.Enter Program.Main, Go To All doesn't find methods. But after deleting last character 'n', Go To All can find the result.
Expect: Enter Program.Main, Go To All can find the result.

![d15ac2a6-da5c-4e05-8576-0ba23d98b98b](https://user-images.githubusercontent.com/12449387/51578881-ef842d00-1e73-11e9-8e93-9fb38e6d0bb1.gif)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/335046/go-to-all-doesnt-find-methods-with-dot.html
VSTS ticketId: 683494_
_These are the original issue comments:_

Sara Shi [MSFT] on 9/14/2018, 02:20 AM (130 days ago): <p><strong>Thanks for taking the time to report this issue to us. We’ve created a bug for this issue as internal tracking. The status on this Developer Community item will be updated as that bug is resolved. Thanks again for your feedback.</strong> </p>
_These are the original issue solutions:_
(no solutions)

**Comment by verelpode** [comment] 2019-04-05 20:21
I experience the same problem as that person described.  In VS 2019 16.0.0, when I click Edit menu -> Go To -> Go To All (or rather when I hit the hotkey for that command), then the **"Go to All"** flyout appears in the upper right, and if I type in a class name, it works, but if I type in `MyTestClass.ToString` then it fails to find the method/member.  Even if I deselect **"Current Document"** and click on **"Members"** or type in `m MyTestClass.ToString`, then it still says "No results found".

If I leave out the class name and type in `m ToString` and deselect "Current Document", then it finds `ToString` in every class and struct, but that's unhelpful in this case because the results show hundreds of ToString methods but I wanted to go to the method in the class `MyTestClass` (not in the current document).

Thanks for considering improvements to "Go to All".  It's a very useful feature that I use frequently, but it would be more useful if I could type in `MyTestClass.ToString`.

**Comment by CyrusNajmabadi** [comment] 2019-04-05 20:26
Works fine for me:

![image](https://user-images.githubusercontent.com/4564579/55654502-70ca3b00-57a6-11e9-90ce-4ffb71092b33.png)

**Comment by verelpode** [comment] 2019-04-05 20:35
That's surprising, so I tried it again, and I discovered that the problem is more serious than simply a missing feature, because now I see that it works **intermittently**.   Currently I don't see the exact pattern of what one must do in order to reproduce the bug, however I noticed that if **copy & paste** `MyTestClass.ToString` into the "Go to All" window, then it works, but if I type in the exact same text character-by-character, then it only works sometimes.

Finding **nested classes/structs** is also problematic.  I typed in `MyTestClass.MyNestedClass` and it found nothing, so then I copied & pasted the exact same text into "Go to All" and then it found the nested class.

**Comment by CyrusNajmabadi** [comment] 2019-04-05 20:47
I think that may be this issue: https://github.com/dotnet/roslyn/issues/23051

Not sure why it was closed.  @sharwell is there an issue trackign the flakey NavTo issue that's been around a while?

**Comment by verelpode** [comment] 2019-04-05 21:15
Yes it could be #23051, or it could be the following.  Just now I discovered repro steps.  Observe the difference in behavior that occurs when you wait **BEFORE** typing the dot versus when you wait **AFTER** typing the dot.

Type in `MyTestClass` (without dot) then WAIT several seconds until the GUI stops changing, then continue typing, meaning type `.ToString` so that the complete becomes `MyTestClass.ToString`.  It says "No results found".

Now do it again but type the dot immediately and wait AFTER the dot.  Type in `MyTestClass.` (WITH dot) then WAIT several seconds then type `.ToString`.  The method is found correctly.

**Comment by CyrusNajmabadi** [comment] 2020-03-08 21:17
Fixed with https://github.com/dotnet/roslyn/pull/42059

**Closed by CyrusNajmabadi** 2020-03-08 21:17 UTC
Labels: Area-IDE, Bug, Developer Community
