### ISSUE TITLE
SynaxClassifier exception typing directive at end of file

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#24410] opened 2018-01-24 00:01 UTC
**Version Used**: 
Latest IntPreview (d15.6 - 27319.1 )

**Steps to Reproduce**:

1. Open Compilers.sln in `dev15.6.x`.
2. Open C:\Code\roslyn\src\Compilers\Core\Portable\CorLightup.cs.
3. Go to the end of the file, add a couple of newlines and type `#error version`

**Actual Behavior**:
Dialog box about extension error.  Activity log has:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpansForPreviousTree[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, ITextSnapshot lastSnapshot, Document lastDocument, List`1 classifiedSpans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpans[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, List`1 classifiedSpans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags[TClassificationService](NormalizedSnapshotSpanCollection spans, HostLanguageServices languageServices, IClassificationDelegationService`1 delegationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()
 --- 
End of stack trace from previous location where exception was thrown
 --- 
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---
```

**Comment by jinujoseph** [comment] 2018-03-19 21:28
also tracked [here ](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/486581)

**Comment by JieCarolHu** [comment] 2018-04-05 18:26
Cannot repro this issue on the latest 15.7 (27603)

![image](https://user-images.githubusercontent.com/17056651/38384490-22589acc-38c4-11e8-8f55-93ae8474e367.png)

**Comment by sharwell** [comment] 2018-04-30 13:04
Probable duplicate of #23074

**Closed** 2018-04-30 13:04 UTC
Labels: Area-IDE, Bug, Resolution-Not Reproducible
