### ISSUE TITLE
Format Code doesn't work for objects inside a list initialization

### ISSUE THREAD

**Issue by akshita31** [dotnet/roslyn#24151] opened 2018-01-10 18:28 UTC
**Version Used**: 
Visual Studio Enterprise 2017 Int Preview
Version 15.6.0 Preview 1.0
.NET Framework Version 4.7.02556

**Steps to Reproduce**:
Create following code in a function:

```
            List<Document> documents = new List<Document>()
            {
                new Document { Id="Id1", FileName="Document1"},
                    new Document { Id = "Id2", FileName = "Document2" },
                new Document { Id = "Id3", FileName = "Document3" },
                new Document { Id = "Id4", FileName = "Document4" },
            };
```

Press "Format Document" shortcut - on windows is Ctrl +K ,Ctrl +D

**Expected Behavior**:
All `new Document (...)` objects should have the same alignment and spaces should be fixed.

The code should looks as follow:

```
            List<Document> documents = new List<Document>
            {
                new Document { Id = "Id1", FileName = "Document1" },
                new Document { Id = "Id2", FileName = "Document2" },
                new Document { Id = "Id3", FileName = "Document3" },
                new Document { Id = "Id4", FileName = "Document4" },
            };
```

**Actual Behavior**:
No action. Objects initialized inside documents list stay in the same position.
Also spaces in first abject `new Document { Id="Id1", FileName="Document1"},` does not change.

Alignment works for the top level of object initialization. When I move `List<Document> documents = new List<Document>` by one tabulator in the example above, code formatting works properly.

**Comment by Pilchie** [comment] 2018-01-10 18:50
Dupe of https://github.com/dotnet/roslyn/issues/779.

**Closed** 2018-01-16 08:00 UTC
Labels: Area-IDE, Resolution-Duplicate
