### ISSUE TITLE
windows_vsi_p3_prtest timing out

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#16741] opened 2017-01-25 12:32 UTC
Following error is given in the dump taken when execution times out
```
Tag count mismatch: 
Expected: 1
Actual: 0
Current editor text:
class C
{
}
```

**Comment by jmarolf** [comment] 2017-01-25 12:33
found in https://github.com/dotnet/roslyn-internal/pull/1527

**Comment by tmeschter** [comment] 2017-02-07 00:24
What have I done to deserve all the integration test failures?

**Comment by Pilchie** [comment] 2017-02-07 00:33
You *currently* have the most context, but we should farm them out to multiple people for separate root causes.

**Comment by tmeschter** [comment] 2017-02-07 15:34
We no longer have logs. I see no further failures of this sort. Closing this as "Not Repro".

**Closed by tmeschter** 2017-02-07 15:34 UTC
Labels: Area-IDE, Bug, Test
