### ISSUE TITLE
Code Generator diagnostic only appears when build

### ISSUE THREAD

**Issue by tonyhallett** [dotnet/roslyn#54173] opened 2021-06-17 17:34 UTC
Visual Studio 16.9.1
Code analysis 3.9.0 ( I had issues with 3.10.0 )

**Steps to Reproduce**:

In source generator 
![image](https://user-images.githubusercontent.com/11292998/122439019-2d2d0780-cf93-11eb-9f1c-616bd439e584.png)

With diagnostic from
```
var buildLocation = invocation.GetLocation();
Diagnostic.Create(
                    new DiagnosticDescriptor("MoqProtectedTyped2", "Build should be followed by Setup or Verify", "Build should be followed by Setup or Verify", "MoqProtectedTyped", DiagnosticSeverity.Warning, true, "Build should be followed by Setup or Verify"), buildLocation
                );
```

**Expected Behavior**:

Diagnostic is immediately reported in visual studio

**Actual Behavior**:

Only reported when build the project using the code generator and then can only be removed ( when resolved ) by building again.

https://user-images.githubusercontent.com/11292998/122446429-906e6800-cf9a-11eb-8265-b204e8cf921f.mp4

Also my diagnostic is not showing a category.  Is there a well known category class I should be using ?

Please advise.

**Comment by Siphonophora** [comment] 2022-03-27 21:57
@sharwell I'm a bit surprised this is in the backlog. I'm running into this on a project I am working on where getting feedback to the users through diagnostics will be quite important, and I think it will be confusing or frustrating if that won't work.

As a cross check I tried this using the CommunityToolkit.MVVM generator, and its very easy to repo by adding that generator and dropping in this code. https://github.com/CommunityToolkit/dotnet/blob/5cea66b4f8582dc71c37db13485d724f8abb0218/tests/CommunityToolkit.Mvvm.SourceGenerators.UnitTests/Test_SourceGeneratorsDiagnostics.cs#L23-L36

Are there any suggested work arounds for this? Maybe there is a way to hand off these diagnostics to an analyzer which could emit them properly (but without re-doing all the analysis the generator had to do)?

If there aren't work arounds, could the priority be increased?

Thanks

**Comment by sharwell** [comment] 2022-03-29 22:34
Duplicate of #49664

**Closed by sharwell** 2022-03-29 22:34 UTC
Labels: Bug, Area-Analyzers, New Feature - Source Generators
