### ISSUE TITLE
Roslyn incorrectly updates variable state to not nullable for readony string member

### ISSUE THREAD

**Issue by trivalik** [dotnet/roslyn#48728] opened 2020-10-17 19:43 UTC
**Version Used**: 
Visual C# Compiler Version 3.7.0-6.20459.4 (7ee7c540)

**Steps to Reproduce**:
Use code below and create `SurveyQuestion` class.

```
    #nullable enable
    public class SurveyQuestion
    {
        public string QuestionText { get; }

        public SurveyQuestion()
        {
            QuestionText.ToString();
            QuestionText = "";
        }
    }
```

**Expected Behavior**:
Warning for possible null dereference of `QuestionText` for calling `ToString`. In TooltipText in Visual Studio should be show that it is null!
**Actual Behavior**:
No warning at compile time. In TooltipText in Visual Studio shows that it is not null!

maybe related to #48605

**Comment by RikkiGibson** [comment] 2020-10-18 00:16
Duplicate of #41306.

This is fixed in VS 16.8/.NET 5. Thanks for reporting!

**Closed by RikkiGibson** 2020-10-18 00:16 UTC
Labels: Area-Compilers, untriaged
