### ISSUE TITLE
VisualStudioOptionsProcessor holds on to command-line string causing heap growth

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#37212] opened 2019-07-14 04:26 UTC
On a large .NET Core-based solution I'm analyzing, about 2.7% of the heap (or 55Mb) is taken up by VisualStudioOptionsProcessor. The issue seems to be that the class holds on to a string that contains the entire command-line, which in the case of .NET Core projects can be extremely long due to all the framework reference parameters. This seems to be somewhat unnecessary as the only reason it appears we hold on to the string is so that if a ruleset file changes we can update the current diagnostic settings. It seems like we could simply remember only what diagnostic settings were specified on the command-line and use that to calculate the effective diagnostic settings instead when a ruleset file changes, without holding on to the entire string.

**Comment by jasonmalinowski** [comment] 2019-09-10 17:33
Just to check @panopticoncentral, we did find one bug where we were leaking the OptionsProcessor itself which would have been causing more strings to be held around than usual. It was happening if the project got unloaded. Any idea if the scenario you were testing might have been triggering that too?

(That's not to say that we can't make this better directly, but that fix might also help the scenario too...)

**Comment by panopticoncentral** [comment] 2019-09-10 18:38
I don't think so. `CPSProject` is holding a direct reference, so I don't think it's a leak. And we're only testing solution open at this point.

**Comment by jasonmalinowski** [comment] 2019-10-02 23:56
@panopticoncentral:

So we can easily eliminate Roslyn holding onto the string; the one downside though is it would mean any time you call IWorkspaceProjectContext.SetOptions we will have to reparse the string and reapply it each time – right now we fast-path recognizing the string being applied is the same one as the prior one, and if so we just no-op. I don’t know immediately how expensive that might be if we remove that optimization or how often you might call this. Any idea if that’s a problem on your end? It’s easy enough to measure if you have a specific scenario you’d like me to test. 

I’m also wondering if we’re better off being smarter here. The reason these command line strings are so large is because they contain /r switches with full paths to all references and analyzers, and relative file paths to all the source files. But the hilarious bit is we don’t actually use that since the project system is passing us those item groups directly. The build task produces the item group that contains each element, and those are what are being concatenated to call into this API. The build task could easily annotate each parameter with a “what is this” sort of thing – say whether this is a switch, reference, source file, analyzer path, etc, and then your CompileDesignTime target could just filter out the ones that it doesn’t need. That’d drastically reduce the size of the string by a few orders of magnitude which would also save all the allocation and processing cost. It would mean updating the build task but that’s a pretty straightforward change.

Thoughts? The first fix is indeed easy and I’m happy to make that, it just means we’re potentially processing unnecessarily large strings even more than we were before.

**Comment by panopticoncentral** [comment] 2019-10-04 22:30
I guess the question is what you want your interfaces to look like? There was a point where we were discussing moving towards a model where the project system would only pass the command-line string and Roslyn would figure everything out from that, but I don't know if that was Svet's dream or something the Roslyn team thought was a good idea. If we don't think we care so much about doing that, then yes I think it would be a reasonable idea to mark the command-line args with a "type" of argument and then filter out the ones that are just going to be ignored. The references are the real problem, so that would probably fix things off the bat.

**Comment by sharwell** [comment] 2019-12-05 22:49
@jasonmalinowski Do we only store it for that check? If so we can store a hash of it.

**Comment by jasonmalinowski** [comment] 2019-12-05 22:51
@sharwell, of course, my question was trying to see if we can avoid recomputing the hash of a huge string that we don't really use fully in the first place.

**Comment by sharwell** [comment] 2019-12-05 22:56
It seems like storing the hash is cheap, so we end up with one of the following:

1. We don't need the check (this fast path isn't used in practice). Storing the hash is unnecessary, but it's so small it doesn't matter.
2. We need this check (we rely on this fast path in practice). Calculating the hash is fast and providing measurable benefits. After the evaluations we did for the SHA1&rarr;SHA256 change, I'm not concerned about the cost of calculating this hash as long as we use the incremental hashing pooled instances.

**Comment by sharwell** [comment] 2019-12-05 23:15
@panopticoncentral So unfortunately, with the current options architecture it will be difficult to remove this string. The _contents_ of a ruleset file affect the way this string is parsed, so whenever a ruleset changes we have to use the original string to get back to a good state. We could avoid storing this string (and store a hash instead) if the project isn't using any `/ruleset` arguments, but I question how much that will really help large solutions.

**Comment by jasonmalinowski** [comment] 2019-12-05 23:17
So the best approach might be to hold onto the hash of the original string, _and_ the split string, minus the file and /reference arguments we can toss. For the .NET Core projects specifically that will drastically reduce the size of the command line string.

**Comment by sharwell** [comment] 2019-12-06 01:06
@dotnet/roslyn-compiler If we wanted to implement this "cleanly", I believe we would need an API that filters out all source files and `/r` arguments from a given collection of command line arguments, and returns the resulting command line arguments. We could store this collection for reparsing in since we don't use that part of the result.

**Comment by jaredpar** [comment] 2019-12-06 17:57
Even with that solution though we're still going to be producing a new `string` instance every time.

IIRC the project system essentially ends up storing all of the options as a key value pair collection. Or at least an un-ordered set of options. What if we provided an API to parse the command line from a collection of `string` options vs. forcing the creating of a complete single `string` before hand?

**Comment by jmarolf** [comment] 2019-12-06 18:04
yeah, the project system already has a data structure to store the commandline args. We should just pass that in. Or if the project system data structure is insufficient we should change it.

**Comment by panopticoncentral** [comment] 2019-12-06 18:11
Rather than playing games with the command-line string, when I looked at this originally it seemed to me a better way to go was simply to remove the need for reparsing the command-line when a ruleset changed. My thought was that Roslyn would instead just remember which warnings/errors were configured on the command-line  as it was parsing and then use that information when the ruleset file changed. It's basically the equivalent of what we're doing already, we're just keeping the record in a very inefficient way at the moment. Then there isn't the messing around with the command-line string.

**Comment by CyrusNajmabadi** [comment] 2020-02-25 23:43
I looked into the compiler/ruleset/commandlineparser changes to make this better.  I'm *very* wary about making changes to that.  It's complex and gnarly logic and i'm very worried aobut changing it in some way that causes subtle regressions in a very critical place.  

An alternate approach i'd like to propose is that we simply persist this command line to our persistence service using our IChecksummedPersistentStorage service.  This is beneficial because the system can easily store a pair of data (i.e. the command line and hte checksum of hte command line).

This solves all the needs i can see.

First, we can still easily see if anything changed by comparing the last persisted command line checksum against the incoming one.  Second, if the ruleset changes and we need to get at the previous commandline, we can just pull it out of the persistent store.  

This would allow us to dump this large string from memory in a pretty simple fashion.

**Comment by sharwell** [comment] 2020-02-25 23:47
@CyrusNajmabadi We could also serialize it to the temporary storage service (memory mapped files) to avoid SQLite overhead for data we don't need after restart.

**Comment by CyrusNajmabadi** [comment] 2020-02-25 23:48
> @CyrusNajmabadi We could also serialize it to the temporary storage service (memory mapped files) to avoid SQLite overhead for data we don't need after restart.

That would work for me.

**Comment by davkean** [comment] 2020-02-26 03:08
@CyrusNajmabadi These command-lines can also end up the LOH for large projects - would Roslyn be in place to handle this as an IEnumerable<string>? We manually have to join the command as a single string on our side. That way we just avoid the LOH for them.

**Comment by CyrusNajmabadi** [comment] 2020-02-26 05:01
> would Roslyn be in place to handle this as an IEnumerable? We manually have to join the command as a single string on our side. That way we just avoid the LOH for them.

Yes, it would be pretty trivial on our side to support this as an `IEnumerable<string>` (since that's the first thing ew do with the string passed in anyways).  Main issue is what new interface we would need to expose the method you'd be calling to pass this in.  Any ideas on that?

**Comment by davkean** [comment] 2020-02-26 05:15
We can extend that existing interface (overload SetOptions) - it's private handshake between a few internal projects and none of them extend it, only Roslyn, so won't break anyone.

**Comment by CyrusNajmabadi** [comment] 2020-02-26 06:39
@davkean Sounds great!  Should we create a new issue for that?  Or would you prefer to keep it here?

**Comment by jasonmalinowski** [comment] 2020-02-26 18:17
Changing the interface is tracked as #32594.

**Closed** 2020-02-27 02:06 UTC
Labels: Area-IDE, Concept-Continuous Improvement
