### ISSUE TITLE
Navigation: Support forward and backward slashes in Navigate To

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10275] opened 2016-04-01 23:25 UTC
Filed on behalf of a customer from interviews.

**Comment by DustinCampbell** [comment] 2016-04-04 16:00
Is there a description of what the expected behavior should be?

**Comment by Pilchie** [comment] 2016-04-08 21:14
I assume this is intended for finding file names?  If so, we should file against the VS Platform team, since they own the file name provider.

**Comment by DustinCampbell** [comment] 2016-04-14 16:46
Let's start with filing this on the Platform team.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 20:01
Tagging @olegtk @veler .  Closing this out on the roslyn side.

**Closed by CyrusNajmabadi** 2022-10-28 20:01 UTC
Labels: Area-IDE, Feature Request, 0 - Backlog
