### ISSUE TITLE
IDE display for `var` does not abbreviate

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18196] opened 2017-03-27 18:07 UTC
When I hover over `var`, the tooltip does not use abbreviated names for built-in types.

![image](https://cloud.githubusercontent.com/assets/3804346/24370722/4ad19a98-12dd-11e7-8ff5-bd29fe269062.png)

When I hover over a variable, the tooltop does use abbreviated names for built-in types.

![image](https://cloud.githubusercontent.com/assets/3804346/24370768/72d6f588-12dd-11e7-9ce3-99ed78e436f0.png)

I would expect these to be consistent.

**Comment by rchande** [comment] 2017-03-29 20:45
Looking at the implementation, the reason they differ is because we use different display formats for locals and for types.

**Comment by CyrusNajmabadi** [comment] 2023-02-07 19:09
CLosing out as by design.  The reason for this is that we assume when someone is looking at the type itself, they want the full type info (including namespaces) where the type is from.  But when the type is just a piece of some larger construct (like a local), we don't want all the full names to be overwhelming.  So we simplify them based on the usings in scope.

**Closed by CyrusNajmabadi** 2023-02-07 19:09 UTC
Labels: Bug, Area-IDE
