### ISSUE TITLE
NullReferenceException when creating workspaces/solutions in parallel

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#16184] opened 2017-01-02 04:46 UTC
**Version Used**: 
1.3.2

**Steps to Reproduce**:

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Host.Mef;
using Microsoft.CodeAnalysis.Text;
using Xunit;

public class Tests {
    [Fact]
    public void Workspaces_CanBeCreatedConcurrently() {
        var tasks = new List<Task>();
        for (var i = 0; i < 5; i++) {
            tasks.Add(Task.Run(() => {
                var hostServices = MefHostServices.Create(MefHostServices.DefaultAssemblies);
                var projectId = ProjectId.CreateNewId();
                var projectInfo = ProjectInfo.Create(
                    projectId, VersionStamp.Create(), "_", "_", LanguageNames.CSharp
                );
                var documentId = DocumentId.CreateNewId(projectId);
                var sourceText = SourceText.From("");

                var workspace = new AdhocWorkspace(hostServices);
                workspace.CurrentSolution
                    .AddProject(projectInfo)
                    .AddDocument(documentId, "_", sourceText);
            }));
        }
        Task.WaitAll(tasks.ToArray());
    }
}
```

**Expected Behavior**:
Test is successful.

**Actual Behavior**:
```
One or more errors occurred. (Object reference not set to an instance of an object.)
Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Tests.Workspaces_CanBeCreatedConcurrently() in D:\Development\VS 2015\MirrorSharp\MirrorSharp.Tests\UpdogTests.cs:line 28
   at Microsoft.CodeAnalysis.Workspace.get_Options()
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService..ctor(HostLanguageServices languageServices)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CreateLanguageService(HostLanguageServices provider)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
   at Microsoft.CodeAnalysis.ProjectState.FixProjectInfo(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.ProjectState..ctor(ProjectInfo projectInfo, HostLanguageServices languageServices, SolutionServices solutionServices)
   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo)
   at Tests.<>c.<Workspaces_CanBeCreatedConcurrently>b__0_0()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by mattwar** [comment] 2017-01-04 23:31
I've not been able to reproduce this problem.

**Comment by mattwar** [comment] 2017-01-05 00:38
@ashmind  I've tried up to 500 iterations.  I've tried it using the same host services instance or creating a new one each time like you do.

**Comment by ashmind** [comment] 2017-01-05 01:09
@mattwar OK just tried and I can reproduce it on another machine.
Here is a command line test I did (same code):
[RoslynWorkspaceIssue.zip](https://github.com/dotnet/roslyn/files/686198/RoslynWorkspaceIssue.zip)

This machine's .NET version is 4.6.1 I believe.

```
*Versions*
v2.0.50727  2.0.50727.4927  SP2
v3.0  3.0.30729.4926  SP2
v3.5  3.5.30729.4926  SP1
v4
  Client  4.6.01055
  Full  4.6.01055
v4.0
  Client  4.0.0.0

*Updates*
Microsoft .NET Framework 4 Client Profile
  KB2468871
  KB2468871v2
  KB2478063
  KB2533523
  KB2544514
  KB2600211
  KB2600217
Microsoft .NET Framework 4 Extended
  KB2468871
  KB2468871v2
  KB2478063
  KB2533523
  KB2544514
  KB2600211
  KB2600217
Microsoft .NET Framework 4 Multi-Targeting Pack
  KB2504637  Update for  (KB2504637)
```

**Comment by mattwar** [comment] 2017-01-05 18:55
@ashmind  good news, I've reproduced your problem with your solution, 4.6.1 runtime and roslyn 1.3.2.  I haven't tracked down the true cause yet, but you can work around the problem by only creating one instance of the host service instead of one for each of the workspaces.

**Comment by mattwar** [comment] 2017-01-05 21:47
From debugging 1.3.2, the problem is occurring because portable MEF is initializing the OptionService instance with nulls for the imported constructor arguments.  This leads to null ref exception.  This only seems to happen when more than one composition is being used in parallel.  Regardless, it happens on the invocation of the importing constructor.  If two compositions are constructed and used in sequence, then this problem does not happen.  Yet, if two compositions are constructed and used in parallel (separate threads), then the call to the OptionService constructor will be invoked with null arguments.  Not sure why.

**Comment by mattwar** [comment] 2017-01-05 21:51
This problem is not occurring in current bits.  The OptionService has since been changed to not operate using an importing constructor.  The code paths are very different.  Not sure if MEF itself was fixed in the interim or we are just not using it the same way.

**Comment by mattwar** [comment] 2017-01-05 22:07
It does look like we still use importing constructor in GlobalOptionService which is imported by the new OptionService, so the problem would still exist in current Roslyn if nothing else changed.  I'm assuming this bug was fixed in a newer version of MEF (Microsoft.Composition) that Roslyn now references.

**Closed** 2017-01-05 22:21 UTC
Labels: Area-IDE, Concept-API, Resolution-Fixed

**Comment by ashmind** [comment] 2017-01-05 22:52
@mattwar Thanks for the research!

**Comment by NTaylorMullen** [comment] 2018-01-08 19:57
Using 2.6.10-beta1-62023-02 and still seeing this issue:

![image](https://user-images.githubusercontent.com/2008729/34689646-213966c8-f46b-11e7-931d-1e5d70c80298.png)

**Comment by ashmind** [comment] 2018-03-31 06:33
@mattwarr Same issue still occurs in 2.7.0 (same as #24260?).
