### ISSUE TITLE
Local function can access a variable before initialization

### ISSUE THREAD

**Issue by RytisLT** [dotnet/roslyn#24644] opened 2018-02-05 16:58 UTC
**Version Used**: 
Visual Studio 15.5.5
**Steps to Reproduce**:

    internal class Program
    {
        private static void Main(string[] args)
        {
            var result = GuessWhatWillHappen();
            Console.WriteLine($"Is result null? {result == null}");
            Console.ReadLine();
        }

        private static string GuessWhatWillHappen()
        {
            SetStringValue();
            string foo = null;

            void SetStringValue()
            {
                foo = "bar";
            }

            return foo;
        }
    }

**Expected Behavior**:
"Cannot use local variable 'foo' before it is declared" or runtime error cannot access uninitialized variable 'foo'.

**Actual Behavior**:
When local funcion SetStringValue is called the foo is assigned the value of "bar" then the foo initialization code is reached and it is set to null

**Comment by HaloFour** [comment] 2018-02-05 17:07
This looks like the expected behavior to me given the way local functions are hoisted.  The local function wouldn't be allowed to read `foo`, at least not before assigning it.  But the variable would be in scope.

**Comment by RytisLT** [comment] 2018-02-05 17:13
Yep, reading the variable first causes CS0165: Use of unassigned local variable. Still it's super weird that initialization of the variable overwrites value that has been set by a local function. I would expect that writing variable without initialization would also result in a compiler error.

**Comment by gafter** [comment] 2018-02-05 22:49
This is a little weird, and I admit it might have been better if we had defined things such that the invocation of `SetStringValue()` gives an error reporting that it uses the variable `foo` before its declaration. But I don't see a case for changing things now to make it an error. That would needlessly break existing programs, such as this one:

``` c#
    private static string GuessWhatWillHappen()
    {
        SetStringValue();
        string foo;
        return foo;

        void SetStringValue()
        {
            foo = "bar";
        }
    }
```

@agocke What do you think? Do you think this is rare enough that we can/should change it?

**Comment by agocke** [comment] 2018-02-05 22:55
This was by-design, although it is a little weird. It gets worse though. This is also legal (and by design):

```csharp
using System;
public class C {
    public void M() {
        object o = null;
        switch (o)
        {
            case 0:
                Local();
                break;
            case int x:
                void Local() { x = 0; }
                break;
        }
    }
}
```

At this point, I think we've adapted the philosophy, "don't complicate the definite assignment analysis." Essentially, if the analysis concludes its safe, don't get in the user's way. I think it may be too late to go back on that now.

**Closed** 2018-02-05 23:07 UTC
Labels: Area-Compilers, New Language Feature - Local Functions, Resolution-By Design
