### ISSUE TITLE
Time for diagnostics to update in a file has regressed in vs2019

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#31539] opened 2018-12-05 00:50 UTC
Feels like it's about a second slower than it normally should be.  It's *very* noticible, especially switching back and forth between VS2017 and 2019.

**Comment by CyrusNajmabadi** [comment] 2018-12-05 02:45
Actually, it's more lke 3-4 seconds slower.  Super bad.  It feels like we're up to like 5 seconds for diagnostics.

**Comment by sharwell** [comment] 2018-12-05 15:05
@jasonmalinowski Do we already have a bug filed for this?

**Comment by jasonmalinowski** [comment] 2018-12-05 20:36
Yes, this is a dupe of #30993 which we expect is fixed by #31265.

**Comment by jasonmalinowski** [comment] 2018-12-05 20:36
Unfortunately, the fix is not in Preview 1.

**Closed by jasonmalinowski** 2018-12-05 20:36 UTC
Labels: Area-IDE, Tenet-Performance

**Comment by Neme12** [comment] 2018-12-05 20:38
It's super bad, I'm switching back to 2017 :confused:

**Comment by CyrusNajmabadi** [comment] 2018-12-05 20:51
Great.  Thanks for letting me know.  Hopefully this will be in a preview coming soon.
