### ISSUE TITLE
GUI Editor for editorconfig files doesn't work.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58614] opened 2022-01-04 22:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/GUI-Editor-for-editorconfig-files-doesn/1600499)._

---
[severity:It bothers me. A fix would be nice]
When opening an .editorconfig file from solution explorer, the new gui editor crashes with "IntelliSense finished initializing, but an error occurred when attempting to load the document" (see attached screenshot).

On closing this error page, an attempting to re-open the same file, it loads in the normal text editor.

---
#### Nick. N on 12/1/2021, 01:27 AM: 

<p>Just a quick update (as i can’t edit the original post):</p>
<p>I forgot to add, that this issue only happens when the .editorconfig file is added at a solution level, ie: to “Solution Items” and resides in the same directory as the solution file (with projects in a seperate directory).</p>
<p>I also may have been mistaken about there being a gui editor? as if the .editorconfig file is added to a single project, it opens fine, however in the text editor.</p>

#### Feedback Bot on 12/1/2021, 02:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/3/2021, 09:34 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2022-01-04 23:16
related to https://github.com/dotnet/roslyn/issues/58615

**Comment by jmarolf** [comment] 2022-03-18 22:00
duplicate of https://github.com/dotnet/roslyn/issues/58615

**Closed by jmarolf** 2022-03-18 22:00 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - Editor Config UI
