### ISSUE TITLE
AddMissingReference.AddMissingReferenceTests.AddProjectReferenceBetweenMixedLanguages2 failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9567] opened 2016-03-08 16:25 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit32/920/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddMissingReference/AddMissingReferenceTests/AddProjectReferenceBetweenMixedLanguages2/

```
Stacktrace

MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_12_TestAddProjectReferenceAsync.MoveNext() in d:\j\workspace\roslyn_master---0938d3a7\src\EditorFeatures\Test2\Diagnostics\AbstractCrossLanguageUserDiagnosticTest.vb:line 147 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddMissingReference.AddMissingReferenceTests.VB$StateMachine_10_AddProjectReferenceBetweenMixedLanguages2.MoveNext() in d:\j\workspace\roslyn_master---0938d3a7\src\EditorFeatures\Test2\Diagnostics\AddMissingReference\AddMissingReferenceTests.vb:line 89 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by dpoeschl** [comment] 2016-03-08 17:27
@davkean Another xlang bug that you can probably get rid of now.

**Comment by jasonmalinowski** [comment] 2016-03-08 18:13
This is a dupe of #9308.

**Closed** 2016-03-08 18:51 UTC
Labels: Area-IDE, Flaky, Test
