### ISSUE TITLE
'CSharpWrappingCodeRefactoringProvider' encountered an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62379] opened 2022-07-05 19:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpWrappingCodeRefactoringProvider-/10083833)._

---
VS2022 Pro, x-64, v17.2.5

System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.CSharp.Wrapping.SeparatedSyntaxList.CSharpParameterWrapper.PositionIsApplicable(SyntaxNode root,Int32 position,SyntaxNode declaration,Boolean containsSyntaxError,BaseParameterListSyntax listSyntax)
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.TryCreateComputerAsync[TListSyntax,TListItemSyntax]()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractWrappingCodeRefactoringProvider.ComputeRefactoringsAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync()

---
#### Feedback Bot on 6/29/2022, 10:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-07-05 23:48
Duplicate of https://github.com/dotnet/roslyn/issues/61362

**Comment by vatsalyaagrawal** [comment] 2022-07-13 19:18
Duplicate of #61362

**Closed by vatsalyaagrawal** 2022-07-13 19:18 UTC
Labels: Area-IDE, untriaged
