### ISSUE TITLE
C# Code Formatting is messed up

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31016] opened 2018-11-07 16:13 UTC
Would like to paste the text as seen in hte editor but certain from previous postss all formatting I might putin will get stripped.  Ths was all working fine until updating yesterday to 15.8.1, which in general seem like the quality for editing has really gone down.

Within a namespace i created a classs, would expect it t be one tab stop in.  I tried to replace sapces with '.'   and each member variable should be on a new line...

```csharp
// actual formatting by VS
public class MyClassName
{
    public string Project { get; set; }
    public string Milestone { get; set; }
    public string SerialNumber     { get; set; }
public string Type { get; set; }
public string ReceivedDate     { get; set; }
        public string IsDistributed { get; set; }
public string IsReturned { get; set; }
public string CurrentOwner { get; set; }
public string IsOriginalOwner { get; set; }     
    }
```

```csharp
// Expected                          
    public class MyClassName
    {
        public string Project           { get; set; }
        public string Milestone         { get; set; }
        public string SerialNumber     { get; set; }
        public string Type              { get; set; }
        public string ReceivedDate     { get; set; }
        public string IsDistributed     { get; set; }
        public string IsReturned        { get; set; }
        public string CurrentOwner      { get; set; }
        public string IsOriginalOwner   { get; set; }
    }
```

I notice you took a screen shot,  once i saw that i did a build and tried to show &quot;0 Errors&quot;...   There are no errors and the code runs.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/320944/c-code-formatting-is-messed-up.html
VSTS ticketId: 671204_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎9‎/‎4‎/‎2018, 02:10 AM (64 days ago): <p>Thank you for your feedback! Tried to copy the piece of code provided with 15.8.2 and every thing seems to be formatted as expected. Could you try to repro this on a small project ? or could you check if you are using any other extension for formatting ?   We look forward to hearing from you!</p>

Jinu Joseph [MSFT] on ‎10‎/‎26‎/‎2018, 06:55 PM (11 days ago): <p>Thank you for your feedback! Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to repro it, please provide us with more info! Thank you for helping us build a better Visual Studio!</p>

Daniel Doris on ‎10‎/‎29‎/‎2018, 01:26 PM (8 days ago): <p>Seems no change in 15.8.2, the formatting is still messed up and not really getting what is expected.  Not sure what more information is needed here.  The setting to preserve spaces is set on i.e. "Preserve spaces inside uniform initialization and initializer lists".  Seems the formatting at times can be somewhat inconsistent at times in the formatting, but if messed up would i expect it to be consistent?<br><br>Would expect the spacing in the inter-token spacing to be preserved.   While the html here isn't the best to show it but everything is lined up vertically before being formatted,  the  leading spaces before the '\{get ; set'}" is *ALWAYS* gets removed.   What does "preserve spaces" mean?   <br><br>What is expected, I normally line text up on the same column all the public is on column 9, string column 17, variable names 25,  and the opening brace column 41.   Upon formatting all the spacing previously put in with VS 2017 15.8.2 is gone.  How are you not able to repro  this?</p>

Daniel Doris on ‎10‎/‎29‎/‎2018, 01:33 PM (8 days ago): <p>Should also mentioned there are a couple other places spacing isn't "preserved". If i have aunction with named parameters, all spacing after the ":" for the parameter name is stripped and removed and replaced with one space.  Also all my linq statement get messed up, format them as desired and reformat *splat* all the formatting as desired is gone.   Sorry what does "preserve" spacing mean?</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-11-07 16:23
I have two observations so far:

1. I am not able to reproduce this issue when "Automatically format on paste" is disabled
2. I do not see a formatting option to preserve spaces between a property name and the opening brace, so it appears the formatter does not support the formatting style requested

Please let me know if there is another option I am missing. Otherwise, this appears to be a duplicate of #28729.

> … "Preserve spaces inside uniform initialization and initializer lists" ...

I can't find any references to this in the IDE or in searches online.

**Comment by sharwell** [comment] 2018-11-07 19:35
@ZooDoo4U Does unchecking "Automatically format on paste" resolve this issue for you?

> That said I’m really starting to see some odd one-off issues in the editor as of late,

It would really help if these could be filed as individual issues, so we can review/triage/address them separately. #24499 shows an example of how to report one of these in a way that's particularly easy to discuss.

**Comment by ZooDoo4U** [comment] 2018-11-07 20:37
Perhaps an image for the expected and actual and attached one.   What setting can i use to preserve the spacing?    Read through my previous comments thought  I had what was desired set.    This was from only creating a file from scratch, not pasted code.

![codeformat](https://user-images.githubusercontent.com/11509268/48159366-d236be00-e289-11e8-8386-a8605dc88114.png)

**Comment by sharwell** [comment] 2018-11-07 20:40
> What setting can i use to preserve the spacing?

You can turn off all formatting triggers (same page as "Automatically format on paste"), which covers most scenarios where the formatting would be altered. There may be some remaining cases where formatting is still altered.

**Comment by ZooDoo4U** [comment] 2018-11-07 20:48
Which settings are those?    Thought i've turned all formatting off...
![c_format_options](https://user-images.githubusercontent.com/11509268/48159899-5473b200-e28b-11e8-8e74-f8007a6168ce.PNG)

**Comment by sharwell** [comment] 2018-11-07 22:14
@ZooDoo4U Yes, it looks like you have all *available* formatting options turned off. With those settings, it should not be reformatting code that you paste in the editor. However, there may be other cases that do trigger formatting, and those can be filed as separate bugs.

**Comment by ZooDoo4U** [comment] 2018-11-07 22:39
Not sure where it was ever commented the code was pasted in?  Mentioned a couple times the code was typed in, and not pasted.   When you do a reformat document or reformat selection, where 've tried my best with the option in VS to "ignore spacing in initializers" or "Preserved whitespace"  the reformat document and/or reformat selection removes the spacing desired.

**Comment by sharwell** [comment] 2018-11-07 22:45
> When you do a reformat document or reformat selection,

You will not be able to use these commands with the formatting behavior you've described as the desired outcome. The following are known bugs related to this scenario:

* #28729: Requesting ability to automatically place things in columns
* #8263: Requesting ability to disable the formatter altogether

We would like to create an API allowing users to provide a custom formatting engine to replace (or augment) the one we use today, which would allow better control over certain highly-opinionated styles that do not fit within the bounds of what the current formatter is capable of handling.

**Closed** 2021-09-16 02:00 UTC
Labels: Area-IDE, Feature Request, Need More Info, Developer Community, fabric-bot-test
