### ISSUE TITLE
Move Type refactor action uses reversed folder path in Core projects

### ISSUE THREAD

**Issue by magnusbakken** [dotnet/roslyn#18627] opened 2017-04-12 10:27 UTC
**Version Used**:
Visual Studio 2017 (build 26403.3)

**Steps to Reproduce**:

1. Create a new .NET Core project. I've tested with ASP.NET Core and CLI projects.
2. Create the folder structure A > B > C inside the project (i.e. B inside A, C inside B).
3. Put a file called D.cs in the C folder, and have it contain two empty root level classes called D and E.
4. Use the refactor action "Move type to E.cs" on the E class.

**Expected Behavior**:
A file called E.cs should be created next to D.cs at the path A/B/C.

**Actual Behavior**:
E.cs is instead created at C/B/A/E.cs. In other words the path is in the wrong order, as if the code pushes the folders on a stack and forgets to reverse them at the end.

The same thing affects the Extract Interface action, and possibly other actions that create new files, if there are any. It also happens if class E is nested inside D. In that case you get the options "Move type to E.cs" and "Move type to D.E.cs", both of which are generated at the wrong path.

In all cases the namespace generated for the file is correct (i.e. ProjectName.A.B.C), even though the path is wrong.

**Comment by magnusbakken** [comment] 2017-04-12 10:55
Demonstration:

![refactorfolderproblem](https://cloud.githubusercontent.com/assets/284189/24954341/43dba81a-1f7f-11e7-9bc1-b21e7f5eefc9.gif)

**Comment by Pilchie** [comment] 2017-04-12 20:51
@srivatsn / @davkean - this sounds like `Folders` in the wrong order for .NET Core project system.

**Comment by davkean** [comment] 2017-04-13 00:37
Yeah, dupe of https://github.com/dotnet/project-system/issues/1760:

**Closed by davkean** 2017-04-13 00:37 UTC
Labels: Bug
