### ISSUE TITLE
'Remove redundant assignment' should mark the assignment syntax as unnecessary, not the variable name

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#42868] opened 2020-03-28 19:13 UTC
This keeps confusing me. It makes the message look like it's saying the variable itself is unnecessary.

Minimal repro (`_` indicates faded text):

```cs
class C
{
    int M()
    {
        // ℹ IDE0059 Unnecessary assignment of a value
        //  ↓_____________
        var someVariable = 100;

        someVariable = 200;
        return someVariable;
    }
}
```

Looks like this:

![image](https://user-images.githubusercontent.com/8040367/77831619-a928fe80-7106-11ea-8e3d-4c0963e4f2a9.png)

Expected:

```cs
class C
{
    int M()
    {
        // ℹ IDE0059 Unnecessary assignment of a value
        //               ↓____
        var someVariable = 100;

        someVariable = 200;
        return someVariable;
    }
}
```

**Comment by sharwell** [comment] 2020-03-30 15:07
Duplicate of #36202

**Closed by sharwell** 2020-03-30 15:07 UTC

**Comment by jnm2** [comment] 2020-03-30 15:17
Thanks! I'm going to start looking harder first.

**Comment by kelicto** [comment] 2022-05-20 01:26
It speaks more specifically, and I agree. Although you can block it in the .editconfig configuration, you can only change it yourself.
