### ISSUE TITLE
A "Self" Type Identifier

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6939] opened 2015-11-20 20:21 UTC
A "Self" Type Identifier
---------------------

The "Self" Type Identifier `@` would be an alias for the class, structure or interface (including generic type parameters), in which it is stated. Like how `this` is an alias to the current instance of the type. 

**Example**
So the following usage example. The sourcecode would display
```C#
class Foo<T0, T1>
{ class Bar<T0>
  {
    class Baz<T1>
    {
      @ Method(@ x, @ y){}
    }
    
    @ Method(@ x, @ y){}
  }

  @ Method(@ x, @ y){}
}
```
but it would effectively be compiled as.
```C#
class Foo<T0, T1>
{ class Bar<T0>
  {
    class Baz<T1>
    {
      Baz<T1> Method(Baz<T1> x, Baz<T1> y){}
    }
    
    Bar<T0> Method(Bar<T0> x, Bar<T0> y){}
  }

  Foo<T0,T1> Method(Foo<T0, T1> x, Foo<T0, T1> y){}
}
```

```VB.net
Class Foo<T0, T!>
  Class Bar<T0>
    Class Baz<T1>
    
      Method(x As @, y As @) As @
    End Class
    
    Method(x As @, y As @) As @

  End Class

  Method( x As @, y As @) As @

End Class
```
and in VB.net
```VB.net
Class Foo<T0, T1>
  Class Bar<T0>
    Class Baz<T1>
    
      Function Method(x As Baz<T1>, y As Baz<T1>) As Baz<T1>
    End Class
    
    Function Method(x As Bar<T0>, y As Bar<T0>) As Bar<T0>

  End Class

  Function Method( x As Foo<T0, T1>, y As Foo<T0, T1>) As Foo<T0, T1>
End Class
```

**Comment by svick** [comment] 2015-11-20 21:35
What's the point? To save some typing? I'm not sure that's worth making the code more confusing.

Also, `this` isn't really an alias, there is no other way to write code like `return this;`.

**Comment by AdamSpeight2008** [comment] 2015-11-20 22:03
**var**
Say that if we could use `var` instead `var Method( var x, var y )` 
* The *input* `var` would be the "Self" alias.
* The *output* `var` would be the inferred return type, which could be different.

By having a *short* way of stating of "whatever my class type is, use that.". 

**this**
`this Method(this x, this y)` would be confusing as is the method an extension method.

**Footnote**

` * Method( * x, * y)` like a footnote.

**Comment by SolalPirelli** [comment] 2015-11-21 14:10
Dupe of #155, no? (along with #311 and #2322)

**Comment by orthoxerox** [comment] 2015-11-23 07:49
@svick @SolalPirelli It's more of #311 alone, so you wouldn't have to use CRTP as in `class Foo : IEquatable<Foo>`, but `IEquatable` would require you to implement `bool Equals(thistype other)` instead.

**Comment by gafter** [comment] 2016-10-27 19:38
Dup of https://github.com/dotnet/roslyn/issues/311

**Closed by gafter** 2016-10-27 19:38 UTC
Labels: Area-Language Design, Discussion
