### ISSUE TITLE
C# Code Style Options (general) are not correctly saved

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58609] opened 2022-01-04 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Code-Style-Options-general-are-not-/1606601)._

---
[severity:It's more difficult to complete my work]
When I set the option <Text Editor><C#><Code Style><General><Qualify field access with this> to the value 'Refactoring Only' and save this option, it seems to be there when I close the page and reopen the option page.
But when I close again and reopen my changed value is replaced with the orignal value.
From there on it always give met the original value.

See screenshot in attach.

---
#### Feedback Bot on 12/7/2021, 07:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/8/2021, 09:35 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:56
duplicate of https://github.com/dotnet/roslyn/issues/54556

**Closed by jmarolf** 2022-03-18 21:56 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - Editor Config UI
