### ISSUE TITLE
Null parameters C# 12 (.net 8) Primary Constructors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71083] opened 2023-12-04 19:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Null-parameters-C-12-net-8-Primary-C/10528820)._

---
[severity:It bothers me. A fix would be nice]
While I viewed the search it appears that issue has been closed, not sure why as the problem still exists in the release version of VS (17.8.2).

Essentially when viewing parameters passed in through Primary Constructors the debugger displays them as null, however, this doesn't prevent them from working, which implies it's only the debugger that shows it as null. I've added a small file showing the parameter as null, this is being injected via the primary constructor (I would have used add screenshot but couldn't get it to work)

[VS_Null_Primary_Constructor_Parameters.png](https://aka.ms/dc/file?name=B8abc0d465e7d44089a3ab2fb05c80b4f638368483780435353_VS_Null_Primary_Constructor_Parameters.png&tid=8abc0d465e7d44089a3ab2fb05c80b4f638368483780435353)

---
#### Feedback Bot on 11/29/2023, 07:13 PM: 

(private comment, text removed)
#### 2770684262 on 12/3/2023, 06:57 AM: 

(private comment, text removed)
#### Terje Sandstrom (AAD) on 12/4/2023, 10:35 AM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2023, 11:56 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2023-12-04 19:58
Dupe of https://github.com/dotnet/roslyn/issues/70730

**Closed by CyrusNajmabadi** 2023-12-04 19:58 UTC
Labels: Area-IDE, untriaged
