### ISSUE TITLE
[Feature Request]: Highlight TODO comments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47376] opened 2020-09-02 15:04 UTC
It would be nice if TODO comments are highlighted in a different color. If this is accepted, I'll be glad to implement this, but will need a starting point on how this should be done.

**Comment by sharwell** [comment] 2020-09-02 16:47
Duplicate of #25619

**Closed by sharwell** 2020-09-02 16:47 UTC

**Comment by Youssef1313** [comment] 2020-09-02 16:49
@sharwell The other issue is closed, is this tracked internally?

**Comment by sharwell** [comment] 2020-09-02 16:58
Yes there is an internal tracking bug.

/cc @olegtk for another report of this feature request
