### ISSUE TITLE
EditorBrowsable on internal members

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#51269] opened 2021-02-17 17:33 UTC
This is a slight variation of issue #4434 as requested by @sharwell  

**Version Used**: VS 16.8

**Steps to Reproduce**:
Put `EditorBrowsableState.Never` on an `internal` property.
In the same project, trigger Intellisense looking for that property (it will show up).

**Expected Behavior**:
The behavior described by MSDN doc is actually working (so that's not a _bug_): `EditorBrowsable` attribute is ignored inside 
the assembly where the code is defined.

This rule is in place for a good reason (as pointed out by @CyrusNajmabadi): if you build a lib you may want to see every properties listed when working on it, even if you hide some from your consumers.

My context is generated code and that's more of a grey area (is it for external consumers or is it an implementation detail of the generated code?).

That being said, the property in question is `internal` and so there's no ambiguity. 
An `internal` property is _only_ visible from the same assembly.
`EditorBrowsable` on such a property is useless unless applied to the assembly where it's defined.

So I suggest that the expected behavior here is to respect `EditorBrowsable` in the defining assembly for `internal` members.

**Actual Behavior**:
The property shows up in Intellisense, as `EditorBrowsable` is ignored in the defining assembly.

**Comment by CyrusNajmabadi** [comment] 2021-02-17 18:26
> That being said, the property in question is internal and so there's no ambiguity.
An internal property is only visible from the same assembly.

Unless you have the `InternalsVisibleTo` property set.

**Comment by jods4** [comment] 2021-02-17 19:55
> Unless you have the InternalsVisibleTo property set.

Yes.
That's a pretty special scenario, hopefully rare? (mostly tests?)

**Comment by jods4** [comment] 2021-02-17 20:16
Here's another take on this:

I came here from the context of code generation.

Sometimes generated code wants to hide its implementation details the same way a library would.
Except in a library it's by design easy to hide `internal` stuff, whereas in generated code the consumer has access to everything but `private` members.

With C# 9 source generator, we can expect this situation to be more common than before.

Maybe we just need a new `EditorBrowsableState.Private` value for those cases?
It would mean: _Like never but also in declaring assembly?_

**Comment by CyrusNajmabadi** [comment] 2021-02-17 22:12
> That's a pretty special scenario, hopefully rare? (mostly tests?)

**Comment by CyrusNajmabadi** [comment] 2021-02-17 22:14
I would not be opposed to a new option here with EditorConfig to suppress tehse even from source in the same project.  @jasonmalinowski  can you drive?

**Comment by sharwell** [comment] 2021-02-17 23:25
Microsoft.CodeAnalysis.Collections contains an entire namespace of internal types that we don't want to show up in IntelliSense.

**Comment by sharwell** [comment] 2021-02-17 23:28
> a new option here with EditorConfig to suppress tehse even from source in the same project

This would not be sufficient for handling the cases where we would want to use this feature.

**Comment by jasonmalinowski** [comment] 2021-02-18 01:30
I'm wondering if some of the cases here are really working around the lack of a friend style scoping in C# not unlike C++. Because even if EditorBrowseable were to work, you probably still don't want people calling into it _anyways_ and playing with implementation details...

**Comment by lsoft** [comment] 2021-03-17 06:46
> Maybe we just need a new EditorBrowsableState.Private value for those cases?
> It would mean: Like never but also in declaring assembly?

because of SGs, we actually need it, without a doubt. The scenario: SG produces the following code:
```
//SG produced part of the class
public partial class MyClass
{
    public void Good_Public_Method_Fell_Free_To_Call_It_From_AnyWhere()
    {
          ...
          Private_Special_Method_No_Value_For_Outside_Calls_Its_Name_Is_Random_From_Case_To_Case_0f453653cd235a();
          ...
    }

   private void Private_Special_Method_No_Value_For_Outside_Calls_Its_Name_Is_Random_From_Case_To_Case_0f453653cd235a()
   {
   }
}
```

As an author of SG I **know** it exactly, that `Private_Special_Method_No_Value_For_Outside_Calls_Its_Name_Is_Random_From_Case_To_Case_0f453653cd235a` has no value at all to call it from everywhere else, except from `Good_Public_Method_Fell_Free_To_Call_It_From_AnyWhere`. More, its name will change after recompilation! No sense to use it except from SG-produced compilation unit.

I want to hide this method completely. `EditorBrowsableState.Private` looks as good solution.

Thanks!

**Comment by sharwell** [comment] 2021-03-17 13:49
> More, its name will change after recompilation!

Side note: this can cause quite a lot of pain. It should only occur if absolutely unavoidable (i.e. there is no clear way it's possible to have the same input produce the same output), and certainly never be done intentionally.

**Comment by lsoft** [comment] 2021-03-17 14:05
(@sharwell got it! Thank you. I will try to fix it. is there any place where I can read more about this idempotency? I am interested in the reasons. I heard that non-idempotent SG-produced code may cause some troubles with intellisense, but not enough to understand it at 100%)

**Comment by lsoft** [comment] 2021-12-24 16:41
Looks like there is no consensus about design yet. Probably, MS folks can push it forward, because community opinions are posted, and the final decision can take these opinions into account. Hmm?

**Comment by svick** [comment] 2021-12-24 17:13
File private visibility (https://github.com/dotnet/csharplang/issues/5529) is an approach that should solve the source generator issues.

**Comment by sharwell** [comment] 2023-03-08 14:43
Reopening. File visibility solves some, but not all issues here.

**Comment by sharwell** [comment] 2023-03-08 14:45
@CyrusNajmabadi If you want to convince me otherwise, I'm interested to see how the members of this namespace:
https://github.com/dotnet/roslyn/tree/main/src/Dependencies/Collections/Internal

Could be restricted to only be visible from these sources:
https://github.com/dotnet/roslyn/tree/main/src/Dependencies/Collections

This package is distributed as source code, so `EditorBrowsable` does not work for consumers.

**Comment by IS4Code** [comment] 2024-03-11 23:20
I cannot be convinced that `file` visibility is the best solution for source generators, when it needs the newest language version and only works on top-level declarations, as opposed to a custom attribute which would work on everything, everywhere.

**Comment by CyrusNajmabadi** [comment] 2024-03-12 00:16
> I cannot be convinced that file visibility is the best solution for source generators, when it needs the newest language version and only works on top-level declarations, as opposed to a custom attribute which would work on everything, everywhere.

This is on the backlog and has had no movement in years.  Realistically, one approach works today, while the other likely would not get any attention for years.  How you define "best solution" ultimately comes down to if you care about something that works for some scenarios and which you can use right now, versus wanting to solve all your scenarios but not having anything that works for many more years.

**Comment by MrGadget1024** [comment] 2024-04-26 11:47
My issue https://github.com/dotnet/roslyn/issues/71210 got closed as duplicate of this.

I come here trying to hide many ShouldSerializeFoo public methods from Intellisense.  These must be public for XmlSerializer to work, but should never be called directly from code elsewhere, either in the same project, or in the same solution.

Surely there could be an IDE option to honor `EditorBrowsableState.Never` within same solution or even same project that I can turn on?

**Comment by nathan130200** [comment] 2024-09-01 23:12
What about `friend` declarations like in C++. So we can specify which classes/fields/methods can see our internal/private fields.

```cs
class TcpClient
{
  // ... implementation ...
}

class Socket
{
  // ... implementation ...

  friend class TcpClient; // now TcpClient can see all private fields.
}
```

https://en.cppreference.com/w/cpp/language/friend

**Comment by jasonmalinowski** [comment] 2024-09-03 20:43
@nathan130200 Language features are discussed over on the csharplang repo, and there's some conversation about similar features here: https://github.com/dotnet/csharplang/discussions/2073

**Comment by Drake53** [comment] 2024-09-11 18:34
I don't think it's a good idea to add `EditorBrowsableState.Private`. When I look at the name, I expect it to behave as `EditorBrowsableState.Never` currently does, so it will only add confusion when it seems like private and never should be switched around. Of course it's possible switch them around, but that would be a breaking change for those who rely on the way `EditorBrowsableState.Never` currently behaves.

I think a better solution would be to add a new attribute as suggested in https://github.com/dotnet/roslyn/issues/71210 which actually works as advertised. The only question then is which name to give to this new attribute.

**Comment by CyrusNajmabadi** [comment] 2024-11-11 21:15
Closing as not planned.  We are not changing EB.  And language requests shoudl go to csharplang.

**Closed by CyrusNajmabadi** 2024-11-11 21:15 UTC
Labels: Area-IDE, Feature Request
