### ISSUE TITLE
BasicLineSeparator.xml test is flaky

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#10963] opened 2016-04-29 00:19 UTC
build: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/669/

PR: https://github.com/dotnet/roslyn/pull/10950

tags looks like didn't produced at the expected time.

**Comment by jasonmalinowski** [comment] 2016-04-29 00:20
@Pilchie was looking at this.

**Comment by Pilchie** [comment] 2016-04-29 00:58
Dupe of #10916

**Closed by Pilchie** 2016-04-29 00:58 UTC
