### ISSUE TITLE
NullReferenceException instead of CS0165 in definite assignment

### ISSUE THREAD

**Issue by n9** [dotnet/roslyn#51996] opened 2021-03-19 20:15 UTC
**Version Used**: 

3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3

**Steps to Reproduce**:

```
using System;

var foo = "something";

if (!(foo is { } bar) || bar.Length == 0) // ok
{
    Console.WriteLine("bar");
}
  
if (foo is not { } baz || baz.Length == 0) // NullReferenceException
{
    Console.WriteLine("baz");
}
```

[SharpLab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHgNwEMwACAMwHtLSBeUgIgGdKBbAU2AAsBLKAcwYBuPHh7lSACgCEkqjR5NSAb1IBfUgCMSASlLJkWkgDoAMuwHc69AAw68yvKWelUmAJySG2sAx0jcNSdSMQk5alJFUihKYBV1IwAvfUNtRLMLfitaW3tcR1wXVw8vNL8AtSA=)

**Expected Behavior**:

Either no runtime exception (preferable), or CS0165.

**Actual Behavior**:

`NullReferenceException` in runtime.

**Comment by RikkiGibson** [comment] 2021-03-21 03:58
I wasn't able to reproduce the problem in [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBQG4TIAEAZgPZN0C8dARAM5NgCmCABawA5pwDcFClAZ0AFAEJ5zVlG50A3nQC+dYLQCUdXLn20AdABl+MUcPYcADIYqaKdT3XzEAnPM4DZE5DKXIdDzoZORUWOnU6GCYELV1zAC8TMwN061t7IUc6FzdIzx9/QIh0kLCdIA=) on the main branch.

**Comment by jaredpar** [comment] 2021-07-09 14:48
Duplicate of #49272

**Closed by jaredpar** 2021-07-09 14:48 UTC
Labels: Area-Compilers, untriaged
