### ISSUE TITLE
.net core memory leak with CodeAnalysis.Scripting

### ISSUE THREAD

**Issue by yoda07** [dotnet/roslyn#52075] opened 2021-03-23 11:06 UTC
**Version Used**: 
dotnet core 5.0.201
**Steps to Reproduce**:

I found a memory leak problem in my project, after debugging it with looking into DMP file now I am sure the problem is with an object named List<Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader+AssemblyIdentityAndLocation>[ here is the object with problems](https://i.stack.imgur.com/Sq2E9.png). The highlight row in the picture says it detects there is a loop. But I am not sure where the class InteractiveAssemblyLoader is used. Did anyone encounter the same problem? Thanks!

**Comment by jinujoseph** [comment] 2021-03-23 19:15
Duplicate of #52076

**Closed by jinujoseph** 2021-03-23 19:15 UTC
Labels: Area-Interactive
