### ISSUE TITLE
Seemingly flakey VB renaming tests 

### ISSUE THREAD

**Issue by lameox** [dotnet/roslyn#40580] opened 2019-12-24 20:36 UTC
**Steps to Reproduce**:

1. Run Test Suite
2. Get some failing tests reported like [here](https://dev.azure.com/dnceng/public/_build/results?buildId=464563&view=ms.vss-test-web.build-test-results-tab&runId=14784826&resultId=155520&paneView=debug)
3. Re-run tests against the same code
4. All tests pass

**Expected Behavior**:
Tests should either always fail or always succeed

**Actual Behavior**:
Tests fail seemingly at random

**Comment by sharwell** [comment] 2020-01-14 20:44
Duplicate of #29483

**Closed by sharwell** 2020-01-14 20:44 UTC
Labels: Area-IDE, Flaky, Test
