### ISSUE TITLE
Warning depending on static elements order - NullReferenceException

### ISSUE THREAD

**Issue by PDukan** [dotnet/roslyn#28178] opened 2018-06-28 10:17 UTC
**Version**:
Microsoft Visual Studio Community 2017 Version 15.7.4
Microsoft .NET Framework Version 4.7.03056
C# Tools v2.8.3-beta6-62923-07

**Example code**: 
_Build in Debug configuration!_
```c#
namespace StaticObjectNullRef
{
    class ExampleClass1
    {
        int ArraySize = StrArray.Length;
        static string[] StrArray = { "" };
    }

    class ExampleClass2
    {
        static string[] StrArray = { "" };
        static int ArraySize = StrArray.Length;
    }

    class ExampleClass3
    {
        static int ArraySize = StrArray.Length;
        static string[] StrArray = { "" };
    }

    class Program
    {
        static void Main(string[] args)
        {
            var obj1 = new ExampleClass1(); // Class's static parts created first, then used at a dynamic part
            var obj2 = new ExampleClass2(); // Class's static parts created (and used) after each other
            var obj3 = new ExampleClass3(); // NullReferenceException
        }
    }
}
```

**Expected Behavior**:
Warning about the usage of an uninitialized object's property.

**Actual Behavior**:
NullReferenceException at the creation of the first instance.

**Comment by jhinder** [comment] 2018-06-28 18:57
> Microsoft (R) Visual C# Compiler version 1.0.0.50618

The current stable compiler version (Visual Studio 2017, version 15.7.4) is 2.8.3.62923; Roslyn 1.0 is over 2.5 years old now and was shipped as part of Visual Studio 2015 RTM, according to the [Git tag](https://github.com/dotnet/roslyn/releases/tag/version-1.0.0).

I've tried running this code with the latest compiler version, and it doesn't throw any exception.

**Comment by PDukan** [comment] 2018-06-29 06:37
Thank you jhinder! I correct it.
(After a fast search for "how to get roslyn version" I got the next page which misled: https://stackoverflow.com/questions/33556331/how-to-get-roslyn-version-used-by-visual-studio-code-analysis )

**Comment by jhinder** [comment] 2018-06-29 07:48
I've also found out why it didn't crash for me: my repro project was a .NET Core 2.0 app, and it seems like .NET Core doesn't call the type initializer (static constructor) when calling the constructor.

If you mark `ExampleClass3.ArraySize` as public and add the line `var x = ExampleClass3.ArraySize;` to Main, it will also throw a `TypeInitializerException` on .NET Core.

**Comment by jcouv** [comment] 2018-06-29 22:50
Thanks for the details, I can repro.

From what I can tell, the language [spec](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#static-and-instance-fields) does not mention that diagnostics should be produced in such a case. 
As far as the compiler is concerned, I think this is also expected as we don't do flow analysis on fields. 
Tagging @gafter to confirm.

PS: As @jhinder pointed out, the exception occurs at a different point in execution on Desktop and on Core, but from discussion with runtime folks that is expected.
```
ExampleClass3 obj3 = new ExampleClass3(); // NullReferenceException here on Desktop
var x = ExampleClass3.ArraySize; // NRE here on Core
```

**Comment by CyrusNajmabadi** [comment] 2018-06-29 22:51
> but from discussion with runtime folks that is expected.

Can a little clarity on that be provided?  Is that because the runtime doesn't really make any guarantees here about ordering of these sorts of ops?  Thanks!

**Comment by jcouv** [comment] 2018-06-29 23:07
Here's my understanding (we can ping David for more details, if needed):
The IL spec says that depending on the "before init" flag, the static constructor should be called early (ie. on initialization or static reference, if the flag is missing), or "late" (if the flag is set).
"Late" is fuzzily defined and Desktop tends to do it early anyways, while Core is more predictable and does it as late as possible.

In the [repro scenario](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRWQTwHYGNXIxJQC2yANDCAJYA25AJiANQA+AsAFBfXYwQJsUWgAIAAgCYRAUQAepAA60IAYVoZkAZi4BvLiIPjN4gIwA2EbxgiAgggRRMAZWoAvCCIC8Ip0TsPMADoAGQhsAHMYAAsAbn1DBQRqADdYDzFzUwAGAG0AXR8/e0cvER0RACIKkQBfOM4ariA==), the static constructor crashes and the "before init" flag is set. 
On Desktop, the static constructor is invoked early (when the type is first instantiated). On core, the static constructor is delayed until the static field is first accessed.

**Comment by jaredpar** [comment] 2018-08-30 20:01
Closing as C# is behaving as designed here. 

CC @davidwrighton in case he wants to look at this as an issue / change to address in CoreClr.

**Closed by jaredpar** 2018-08-30 20:01 UTC
Labels: Area-Compilers, Resolution-By Design

**Comment by PDukan** [comment] 2018-08-31 08:59
As @jcouv written, this is not a proper operation according to the C# spec. That means the C# spec is wrong and need to be changed?
Because in this case the classes don't have any static constructor and the fields was not used, hence the field initializers were executed.

I suggest in this case to execute the static field initializer just at the first usage of the field. That will mean:
 - just when ArraySize is used, they initializer will be executed,
 - the execution of the initializer will mean the usage of another static field,
 - therefore first the StrArray initializer will be executed.

**Comment by jhinder** [comment] 2018-08-31 15:30
> the classes don't have any static constructor

Not technically correct. The compiler creates a static constructor if the type has static fields with initializers. The order of field initialization in the static constructor matches the order in which the fields appear in the source text ([C# spec](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#static-field-initialization)).

**Comment by jaredpar** [comment] 2018-08-31 16:54
@PDukan why do you feel it's not operating according to the spec. There is no user defined static constructor hence only the second sentence is applicable 

> Otherwise, the static field initializers are executed at an implementation-dependent time prior to the first use of a static field of that class.

This is implementation-dependent and hence order is not guaranteed.

**Comment by PDukan** [comment] 2018-09-01 13:16
@jaredpar : Okay, then it is according to the spec.
But it's not logical. It will be correct, if a static field initializer is executed just at the first usage of static field. Because some static fields maybe never used in the code, and now - according to the spec - their initializer (which could be any complex code) will compiled (which results bigger executable), and executed (which results slower code) unnecessary.
So, you are right, and in this case, first the specification needs to be changed from:
> The variable initializers are executed in the textual order in which they appear in the class declaration. 
to:
> A static field initializer has to be executed before the first usage of the static field.
