### ISSUE TITLE
"Fix all in document" doesn't work for "Use expression bodies" refactoring

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#24698] opened 2018-02-07 23:14 UTC
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/35946578-3108a9fe-0c19-11e8-9a87-b8bafc52f96d.png)

**Steps to Reproduce**:

1. Open TestMessageProvider.cs in Roslyn.sln (commit 000735ee9c887c644e02c7b8bfb5ae44b06b4621)
2. Invoke "Use expression bodies" on one of the methods or properties
3. Select Fix all in document.

**Expected Behavior**:

Refactoring applied to all methods/properties in the document.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/35946647-7885b79a-0c19-11e8-96a1-fadee37716ce.png)

**Comment by sharwell** [comment] 2018-02-07 23:33
Probable duplicate of #19089

**Closed** 2018-05-17 17:49 UTC
Labels: Area-IDE, Resolution-Duplicate
