### ISSUE TITLE
SolutionState.CompilationTracker: An item with the same key has already been added

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#27558] opened 2018-06-07 05:34 UTC
**Version Used**: 
2.8.2

**Steps to Reproduce**:

1. Download and extract the attached repro
2. Open _Repro\Repro.sln_ and run. You will see that the code executes against the target solution without error.
3. Open _Target\Target.sln_ and build it.
4. Open _Repro\Repro.sln_ and run. You will see that the code now errors with the below exception.

#24991 seems closely related, but it wasn't boiled down to a minimal repro and has perhaps not been addressed as a result. I also want to tag @daveaglick because I'm using Buildalyzer here, since the projects are SDK-style. I'm _fairly_ certain that's irrelevant and that Roslyn should be loading the project regardless. At the very least, Roslyn should be giving a useful error.

**Expected Behavior**:

The project should load without error.

**Actual Behavior**:

```
System.ArgumentException
                  HResult = 0x80070057
  Message = An item with the same key has already been added.Key: Microsoft.CodeAnalysis.CSharp.CSharpCompilationReference
   Source = System.Private.CoreLib
  StackTrace:
                at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.< FinalizeCompilationAsync > d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.< BuildCompilationInfoFromScratchAsync > d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.< GetOrBuildCompilationInfoAsync > d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.< GetCompilationSlowAsync > d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Repro.Program.< Main > d__0.MoveNext() in C:
                \Users\kent\Repository\RoslynBuildalyzerRepro\Repro\Repro\Program.cs:line 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Repro.Program.< Main > (String[] args)
```

[RoslynBuildalyzerRepro.zip](https://github.com/dotnet/roslyn/files/2079038/RoslynBuildalyzerRepro.zip)

**Comment by jcouv** [comment] 2018-06-08 00:10
Tagging @DustinCampbell for triage

**Comment by sharwell** [comment] 2019-09-03 21:40
Duplicate of #22537

**Closed by sharwell** 2019-09-03 21:40 UTC
Labels: Area-IDE, Bug
