### ISSUE TITLE
Renaming project in solution explorer crashes VS

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#16035] opened 2016-12-20 21:34 UTC
**Version Used**: ML\26019.00

**Steps to Reproduce**:

1. Run Preinstall
2. Install .NET Desktop Dev
3. Create a new C# Console App solution
4. Rename the project

**Actual Behavior**: VS Crashes

```
>     Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 152  C#
Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task task, object continuationFunction) Line 396          C#
               mscorlib.dll!System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() Line 73     C#
               mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498      C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861              C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827            C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767             C#
        mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 91      C#
               mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 219        C#
          mscorlib.dll!System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task task, bool needsProtection) Line 263       C#
               mscorlib.dll!System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task completedTask, bool bCanInlineContinuationTask) Line 371          C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3642              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.TaskExtensions.VoidResult>.TrySetException(object exceptionObject) Line 606            C#
mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.TrySetFromTask(System.Threading.Tasks.Task task, bool lookForOce) Line 7285                C#
mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.InvokeCore(System.Threading.Tasks.Task completingTask) Line 7209            C#
mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.Invoke(System.Threading.Tasks.Task completingTask) Line 7185            C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3633              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetException(object exceptionObject) Line 606            C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(System.Exception exception) Line 662         C#
               Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor.ProcessAsync() Line 99  C#
               [Resuming Async Method]           
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090               C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070                C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810        C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetException(object exceptionObject) Line 606            C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(System.Exception exception) Line 662         C#
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.SolutionChecksumUpdater.ExecuteAsync() Line 60  C#
               [Resuming Async Method]           
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090               C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070                C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810        C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetException(object exceptionObject) Line 606            C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(System.Exception exception) Line 662         C#
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.SolutionChecksumUpdater.SynchronizePrimaryWorkspaceAsync(System.Threading.CancellationToken cancellationToken) Line 129         C#
               [Resuming Async Method]           
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090               C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070                C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810        C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetException(object exceptionObject) Line 606            C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(System.Exception exception) Line 662         C#
Microsoft.VisualStudio.LanguageServices.Next.dll!Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcClient.InvokeAsync(string targetName, object[] arguments) Line 47               C#
               [Resuming Async Method]           
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090               C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070                C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810        C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetException(object exceptionObject) Line 606         C#
         mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<object>.SetException(System.Exception exception) Line 662         C#
               StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.InvokeCoreAsync<object>(int? id, string targetName, System.Collections.Generic.IReadOnlyList<object> arguments, System.Threading.CancellationToken cancellationToken) Line 493         C#
               [Resuming Async Method]           
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090               C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070                C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288                C#
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123       C#
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810        C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617              C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363   C#
               mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336      C#
               mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263                C#
               mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetException(object exceptionObject) Line 606         C#
               mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<object>.TrySetException(System.Exception exception) Line 164         C#
StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.InvokeCoreAsync.AnonymousMethod__0(StreamJsonRpc.JsonRpcMessage response) Line 468           C#
               StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.HandleRpcAsync(string json) Line 771               C#
               StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync.AnonymousMethod__0()       C#
               mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 680 C#
               mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498      C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861              C#
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954          C#
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902                C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827            C#
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767             C#
               mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704       C#
               mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820            C#
               mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161             C#

```

**Comment by Pilchie** [comment] 2016-12-31 22:49
Looking at the async methods being resumed, this seems to be solution checksum related.  @heejaechang is it a dupe of something you've fixed?

**Comment by heejaechang** [comment] 2017-01-03 21:17
dupe of https://github.com/dotnet/roslyn/pull/15963

**Closed by heejaechang** 2017-01-03 21:17 UTC
Labels: Area-Analyzers
