### ISSUE TITLE
[Test Failure] VSSDK Build error (+1 more) in prtest/win/dbg/unit32 on PR #8070

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8079] opened 2016-01-21 20:24 UTC
PR: [#8070](https://github.com/dotnet/roslyn/pull/8070) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2991/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Samples\CSharp\ConvertToAutoProperty\ConvertToAutoPropertyCS.csproj]

**Issue 2: Compile Error**

**Comment by davkean** [comment] 2016-01-21 21:55
https://github.com/dotnet/roslyn/issues/8077

**Comment by davkean** [comment] 2016-01-21 21:55
Dupe of https://github.com/dotnet/roslyn/issues/8077, I mean.

**Closed by davkean** 2016-01-21 21:55 UTC
Labels: Area-Infrastructure, Contributor Pain
