### ISSUE TITLE
Add Option for #region to be on left or indented like labels are in options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58687] opened 2022-01-06 22:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Option-for-region-to-be-on-left-or-/1618759)._

---
Visual Studio :
 options/c#/Formatting/Indention: Add section for regions just like Labels

region labels ,#region/#endregion, are auto indented after editing it would be nice if they had an option just like labels.
I personally like them on the left just like labels to quickly see/expand/contract code blocks. 
 It is frustrating to move them to the left and after some editing have them jump back indented and then they are lost in the code almost negating the reason for them .

---
#### Feedback Bot on 12/21/2021, 06:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Danny Cohen on 1/6/2022, 10:09 AM: 

<p>C# WinForms solution.<br>
I uninstalled all non builtin extensions.<br>
I deleted .editorconfig.<br>
My #regions always auto indent one tab to the right.<br>
I want them to be on the left most column.<br>
Other preprocessor directives works as intended.<br>
My settings are set properly.<br>
Is it a bug ? A feature ?</p>

**Comment by sharwell** [comment] 2022-01-06 22:08
Duplicate of #12305

**Closed by sharwell** 2022-01-06 22:08 UTC
Labels: Area-IDE, untriaged
