### ISSUE TITLE
"go to definition" generated from metadata renders [NullableAttribute]

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#35436] opened 2019-05-02 02:50 UTC
**Version Used**: 
16.1.0 Preview 2.0 [28822.285.d16.1

**Steps to Reproduce**:
Create an assembly that uses nullable annotations.  Then reference that assembly from a project, use a symbol from it, and go to definition.  Rather than seeing nullable annotations, the compiler-generated attributes show up:
![image](https://user-images.githubusercontent.com/2642209/57054586-6dba5180-6c63-11e9-96c9-bb9623e17d69.png)

cc: @dotnet/nullablefc

**Comment by jcouv** [comment] 2019-05-06 14:08
Indeed
Duplicate of https://github.com/dotnet/roslyn/issues/30327 (MetadataAsSource doesn't recognize NullableAttribute). This is tracked as part of our backlog of IDE work for nullable (https://github.com/dotnet/roslyn/projects/43).

**Closed by jcouv** 2019-05-06 14:08 UTC
