### ISSUE TITLE
Lambda type parameter lowering for implicit cast to ReadOnlySpan<T> appears to be incorrect

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/roslyn#31685] opened 2018-12-11 01:58 UTC
**Version Used**: 
Don't know. I know it happened as of the build of Roslyn that was used to compile several of the most recently released versions of ML.NET (0.7 and 0.8)

**Steps to Reproduce**:

1. Build the https://github.com/dotnet/machinelearning repo
2. Examine Microsoft.ML.Transforms.dll
3. Examine the  lambda body associated with  Microsoft.ML.Transforms.Conversions.HashJoiningTransform.ComposeGetterVecToVec<TSrc>.
4. The translation of the lambda incorrectly handles the method generic parameter associated with the implicit conversion to a ReadOnlySpan.

The problematic line of code is line 563 of HashJoiningTransform.cs ( see https://github.com/dotnet/machinelearning/blob/521acad830408b43175821575f5f774629aeafe7/src/Microsoft.ML.Transforms/HashJoiningTransform.cs ) 

**Expected Behavior**:

The above C# line is translated into
```
IL_0084:  call       valuetype [System.Memory]System.ReadOnlySpan`1<!0> valuetype [System.Memory]System.ReadOnlySpan`1<!0>::op_Implicit(!0[])
```

**Actual Behavior**:
```
IL_0084:  call       valuetype [System.Memory]System.ReadOnlySpan`1<!0> valuetype [System.Memory]System.ReadOnlySpan`1<!!0>::op_Implicit(!0[])
```
Note... the difference is that the broken line specifies a method generic parameter not the necessary type generic parameter.

**Comment by gafter** [comment] 2018-12-11 02:09
I'm guessing there is a missing alpha conversion somewhere in lambda lowering, possibly in a recently added bound node for the span conversion.  See https://github.com/dotnet/roslyn/issues/2549 and its fix https://github.com/dotnet/roslyn/pull/2698 for a previous but related issue.

**Comment by gafter** [comment] 2018-12-12 01:34
It is possible it is the bound stackalloc node that is not properly translated.

**Comment by gafter** [comment] 2018-12-12 01:48
See https://github.com/dotnet/roslyn/issues/2549 for a hint as to the likely affected area.

**Comment by eerhardt** [comment] 2019-01-04 18:37
Adding some information to this bug from https://github.com/dotnet/coreclr/issues/21791 (which is probably a duplicate of this bug):

Just an FYI - this bug was worked around in ML.NET by https://github.com/dotnet/machinelearning/pull/1892. So it isn't blocking ML.NET. Just something we ran into, and were able to work around by using a different approach.

**Comment by gafter** [comment] 2019-01-05 01:08
The problematic code was placed into the compiler in https://github.com/dotnet/roslyn/pull/24621

Generally speaking, user-defined conversions must be removed from the bound trees before lambda lowering so that types are rewritten.  If we want a special operation to convert from an array to a readonly span, we need a special bound node for that.  We tried to reuse an existing node where there is no mechanism for rewriting the conversion, thus this issue.

**Comment by gafter** [comment] 2019-01-05 23:14
For anyone who runs into this, the workaround is to make a static helper method that converts from `T[]` to `ReadOnlySpan<T>`, and call that instead of using the implicit conversion.

**Closed** 2019-05-07 21:46 UTC
Labels: 3 - Working, Area-Compilers, Bug
