### ISSUE TITLE
FAR doesn't list all references from file linked into multiple project

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#66558] opened 2023-01-26 18:45 UTC
To repro, try find-all-references on [UnifiedSuggestedActionsSource.GetFilterAndOrderCodeRefactoringsAsync](https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs,905e090bb0802f94,references) in Roslyn.sln, and only reference from one of the enclosing project (EF.Wpf and Ef.Cocoa) is listed (interestingly, the sourceroslyn.io link shows both )

<img width="1870" alt="image" src="https://user-images.githubusercontent.com/788783/214921871-23c092f2-fd87-4e27-9a29-4cf9d7ad30f3.png">

**Comment by CyrusNajmabadi** [comment] 2023-08-07 17:34
Right.  This is by design.  It was felt to be suboptimal to show the results multiple times, all in the same file/location *just* for all the different projects it was linked into.  We *used* to do that, and people were very nhappy that they would get N results that were all functionally identical.

With TFMs we at least have a reasonable way to show the user the result (i.e. `MS.CA.Features (netstandard2.0, netcore6.0)` etc.).  With *different* projects altogether, it's much less clear what would be a better way to show this.

I'll leave it to you if you think of something we could do here that would be suitable.

**Comment by CyrusNajmabadi** [comment] 2024-10-15 21:28
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-15 21:28 UTC
Labels: Bug, Area-IDE, Navigation-FAR
