### ISSUE TITLE
Editorconfig rule to keep both braces on dedicated lines or both braces in original line

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#20886] opened 2017-07-14 17:01 UTC
What I really want is to enforce that either each brace is the only thing on its line, or both braces are in line with the preceding characters.

```c#
// Yes
public void Foo()
{
}

// No
public void Foo() {
}

// Yes
public void Foo() { }
```

Could we have a way to specify this?

**Comment by jnm2** [comment] 2017-07-14 17:03
Let me revise that. I want to allow `new { Foo = true }`.

**Comment by jnm2** [comment] 2017-07-14 17:05
Actually what I really want is to enforce that either each brace is the only thing on its line, or both braces are in line with the preceding characters.

**Comment by sharwell** [comment] 2017-07-14 22:05
Is this not covered by `csharp_preserve_single_line_blocks`?

**Comment by sharwell** [comment] 2017-07-14 22:08
:memo: There is currently no *enforcement* for the behavior of the formatter as applied to documents, but the expectation is the enforcement will be based on its behavior: a diagnostic occurs if and only if the formatter changes something when you run Format Document. So if you are currently able to configure the formatter behavior to do what you want, then we can reasonably expect that you will also see your desired behavior when we enable enforcement for it.

**Comment by jnm2** [comment] 2017-07-14 22:08
Ideally I could configure an error level. Is that the way `csharp_preserve_single_line_blocks` would behave if it had a `true:error`?

**Comment by jnm2** [comment] 2017-07-14 22:10
In other words, `public void Foo() {` would result in a red squiggly on the `{` with the message "Braces must be the only character in the line or else the both both be on the same line as the preceding characters"?

**Comment by sharwell** [comment] 2017-07-14 22:15
> Ideally I could configure an error level.

Yes, this is what I mean by enforcement. My question is which of the following are you requesting:

1. The code style cannot be configured in a way to make the formatter behave properly for your project (when you run Format Document manually)
2. The code style *can* be configured to make the Format Document command run properly, but there is no way to find cases where a file isn't currently formatted properly, and no messages appear if you write new code that doesn't follow the prescribed format

**Comment by jnm2** [comment] 2017-07-14 22:18
I'm requesting the second.

**Comment by sharwell** [comment] 2017-07-14 22:30
@kuhlenh I would have expected an existing issue to cover enforcing the formatter spacing. Is that not the case?

**Comment by Pilchie** [comment] 2017-07-17 16:53
This is a duplicate of #7067.

**Closed** 2017-07-17 17:07 UTC
Labels: Area-IDE, Feature Request
