### ISSUE TITLE
Build is working in VS 2019, but failing using VS 2017 / .NET CLI / Rider

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36282] opened 2019-06-10 20:35 UTC
VSF_TYPE_MARKDOWNI'm aware what kind of compiler is used in VS 2019. We have a situation, where build is failing on VS 2017 / .NET CLI / Rider, but is working fine on VS 2019. I have prepared a simple solution for &quot;easy to reproduce&quot; problem.

1. Download Test.7z
2. Unpack
3. Build using:
a) VS 2019 - will work
b) VS 2017 - will fail
c) Rider - will fail
d) .NET CLI (`dotnet build Test.sln`)- will fail

With following errors:
&gt;Build FAILED.
&gt;Class1.cs(22,18): error CS0121: The call is ambiguous between the following methods or properties: 'AsyncResultExtensionsRightOperand.Ensure(Result, Func&lt;Task&lt;bool&gt;&gt;, string)' and 'ResultExtensions.Ensure(Result, Func&lt;bool&gt;, string)' [Test\ Test.csproj]
&gt;    0 Warning(s)
&gt;    1 Error(s)
&gt;Time Elapsed 00:00:01.08

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/599156/build-is-working-in-vs-2019-but-failing-using-vs-2.html
VSTS ticketId: 911332_
_These are the original issue comments:_

sygnowski.p on 6/7/2019, 05:29 AM (3 days ago): I've created a repository with example code in GitHub:  https://github.com/sygnowskip/build-problem 
Jeff Schwartz [MSFT] on 6/7/2019, 03:36 PM (2 days ago): <p>Thank you <a rel="user" href="https://developercommunity.visualstudio.com/users/165367/df688de8-3d38-4599-a530-0d93562c4a9e.html" nodeid="165367">@sygnowski.p</a> for the feedback and repro.  I have a few additional questions...  Are you seeing these all fail on the same machine or different machines?  What version of the SDK are you using?  (dotnet --list-sdks)</p><p>I gave your repro a try on 2.1.601 and the issue did not repro, but on 2.1.202 it did.  Have you tried updating to the latest 2.1, or 2.2 version?</p><p>https://dotnet.microsoft.com/download/dotnet-core/2.1</p>

Pawel Sygnowski on 6/7/2019, 11:28 PM (2 days ago): <p>I've tested it on two machines:</p><ul><li>Windows 10 with following SDKs installed:<br>2.1.300<br>2.1.403<br>2.1.500<br>2.1.505<br>2.1.700<br>2.2.100</li><li>Mojave macOS with following SDKs installed:<br>1.0.0-preview2-1-003177<br>1.0.1<br>2.0.0<br>2.1.403<br>2.1.505<br>2.2.101<br>2.2.107</li></ul>And the same issue is on both of them (also, I've asked few of my friends to build this and they have the same issue, but I don't know which SDK's they have on their machines).<br><br><p>As you suggest, I've installed the newest available .NET Core SDK - 2.2.300.</p><p>I've tested it again using the newest SDK and the results are:</p><ul><li>VS 2019 16.1.2 - build is working fine</li><li>Rider 2019.1.2 - build is working fine</li><li>.NET CLI - build is working fine</li><li>VS 2017 15.9.12 - build is still not working, with the same issue as above</li></ul>

Visual Studio Feedback System on 6/9/2019, 08:19 PM (17 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Jeff Schwartz [MSFT] on 6/10/2019, 09:01 AM (4 hours ago): <p><a rel="user" href="https://developercommunity.visualstudio.com/users/165386/444ee3ff-b973-6f10-ad3d-04c9f042ea7b.html" nodeid="165386">@Pawel Sygnowski</a> thank you for all the details.  I am glad to hear the latest SDK is working in all but VS 2017.  This question may be better answered on https://github.com/dotnet/sdk.  I am going to also move it to my colleague on the SDK team.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment] 2019-06-10 20:40
@gafter It looks like the code at https://github.com/sygnowskip/build-problem produces an overload resolution ambiguity in C# 7.0, but succeeds in C# 7.3. I can't remember, did we intentionally improve betterness between 7.0/7.3? And should there be an error about language version requirements if a new tie-breaker is used?

**Comment by gafter** [comment] 2019-06-12 18:44
See https://github.com/dotnet/csharplang/issues/98.  This looks like the one about the delegate return type.  Since it is done in semantic analysis, it is not easy to produce a language version error.  It would have to rebind the invocation under the new rules to know that it would work (not be ambiguous) that way.  We didn't do that, so we don't give a language version error.

**Comment by jcouv** [comment] 2019-06-19 18:05
@gafter It sounds like the observed behavior is by design. Good to close this issue then?

**Comment by jcouv** [comment] 2019-07-12 19:32
@gafter It sounds like the observed behavior is by design. Good to close this issue then?

**Closed** 2019-07-12 20:43 UTC
Labels: Area-Compilers, Bug, Resolution-By Design
