### ISSUE TITLE
Method group invocation syntax resolves Enumerable rather than Queryable

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#55325] opened 2021-08-01 09:14 UTC
Not sure to what extent this is by-design: it seems like when a LINQ operator is used with method group syntax, the enumerable version is resolved instead of the queryable one.

```c#
class Program
{
    public static void Main()
    {
        IQueryable<int> ints = new[] { 1, 2, 3}.AsQueryable();

        var x = ints.Select(i => Foo(i)); // Queryable.Select is resolved, and x is correctly typed as IQueryable<int>
        var y = ints.Select(Foo); // Enumerable.Select is resolved, and y is typed as IEnumerable<int>
    }

    static int Foo(int x) => x;
}
```

Seen on dotnet SDK 6.0.100-preview.7.21377

**Comment by svick** [comment] 2021-08-01 09:30
I believe this is the expected behavior. [The section *Anonymous function conversions*](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions?WT.mc_id=DOP-MVP-5002735#anonymous-function-conversions) of the C# spec says:

> A lambda expression `F` is compatible with an expression tree type `Expression<D>` if `F` is compatible with the delegate type `D`.

But [the *Method group conversions* section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions?WT.mc_id=DOP-MVP-5002735#method-group-conversions) says no such thing.

So since there is no conversion from a method group to an `Expression<T>`, only `Exnumerable.Select` is applicable in the second example, which is why it is chosen. Maybe this code should produce a warning?

**Comment by roji** [comment] 2021-08-01 18:22
This seems like quite a pit of failure, with IDE suggestions to replace lambdas with method groups where possible... A warning definitely seems appropriate.

**Comment by svick** [comment] 2021-08-01 18:36
@roji Yeah, I think it would be a good idea to disable that suggestion for `Expression<T>`.

**Comment by CyrusNajmabadi** [comment] 2021-08-01 19:49
Yeah, that suggestion should not be active there

**Comment by slavanap** [comment] 2021-08-07 14:53
@roji 
Such var type deduction logic is by design because Foo is a delegate in original code block. Alternative solution would be

```c#
class Program
{
    public static void Main()
    {
        IQueryable<int> ints = new[] { 1, 2, 3 }.AsQueryable();

        var fooCompiled = Foo.Compile();
        var x = ints.Select(i => fooCompiled(i));
        var y = ints.Select(Foo);
    }

    static readonly Expression<Func<int, int>> Foo = x => x;
}
```

`.Compile()` here is for demo purpose only, not for  production code. If one would need to chain expressions I have written a NuGet package for such purpose. (slavanap.Expressions).

--
Totally agree with Area-IDE.

**Comment by roji** [comment] 2021-08-07 19:35
Aside from not suggesting at the IDE level, I'd also consider @svick's suggestion above of issuing a warning for this.

**Comment by slavanap** [comment] 2021-08-07 19:48
Not sure about the warning, but an analyser can catch that.
On the other side `IQueryable<T>` inherits `IEnumerable<T>`, which makes IEnumerable extensions applicable to it, but if there's a need to enforce Queryable extensions then there's always a way to call them explicitly or to always supply Expression type into a function. I.e. [these 2 methods won't compile](https://dotnetfiddle.net/7efZV4).

```c#
public static void Main() {
    // Method #1
    {
        IQueryable<int> ints = new[] { 1, 2, 3 }.AsQueryable();
        var x = Queryable.Select(ints, i => Foo(i));
        var y = Queryable.Select(ints, Foo);
    }
			
    // Method #2
    {
        IQueryable<int> ints = new[] { 1, 2, 3}.AsQueryable();
        var x = ints.Select(i => Foo(i));
        var y = ints.Select(Expr.New(Foo));
    }
}

static int Foo(int x) => x;
```

**Comment by roji** [comment] 2021-08-07 22:30
> there's a need to enforce Queryable extensions then there's always a way to call them explicitly or to always supply Expression type into a function

The problem isn't with having a workaround - lambda syntax can always be used etc. It's more about the pit of failure of users accidentally invoking Enumerable.Select when Queryable.Select was intended (see https://github.com/dotnet/efcore/issues/25377)

**Comment by slavanap** [comment] 2021-08-07 23:08
@roji, sometimes there's a need to enumerate stream of SQL response synchronously. What you're suggesting is to show unnecessary warning in such scenarios and violate initial design of `IQueryable<T>` being inherited from `IEnumerable<T>`. Rather the warning can be shown in EF Core on an attempt of GetEnumerator() call on an entity set which is represented by `IQueryable<T>` typed object. Previously there were similar issues of calling untranslatable to SQL delegates which resulted in full records from the database. Even with this
https://github.com/dotnet/efcore/issues/25377#issuecomment-890357152

You're suggesting to pull full row (blog.rating is selected) instead of loading just chosen fields. In my opinion we need to teach users to leverage Expressions rather then adding warnings which violate interfaces design.

Answer on how to effectively leverage Expression generic is in the first part of my answer https://github.com/dotnet/roslyn/issues/55325#issuecomment-894664569

**Comment by roji** [comment] 2021-08-08 08:38
> sometimes there's a need to enumerate stream of SQL response synchronously.

Of course - and System.Linq already provides AsEnumerable for explicitly expressing enumeration of queryables rather than adding a node to the translated expression tree; that would be the way to avoid the warning/diagnostic. Similar diagnostics already exist in scenarios which have a high risk of being problematic: CA2007 proposes adding explicit ConfigureAwait when awaiting Tasks, while CA1310/CA1307 proposes adding explicit StringComparison values. In both these cases, the code producing the diagnostic isn't necessarily wrong or incorrect, but there's a high likelihood of trouble justifying the diagnostic (not necessarily at warning level by default).

At the end of the day, looking at it purely from the perspective of a dev writing C# code, `Select(i => Foo(i))` is equivalent to `Select(Foo)` - the latter is a terser alternative to the former (to the point where the IDE suggests that simplification). This Queryable/Enumerable resolution behavior is one instance where this breaks down, and can be quite a pit of failure... Ideally the C# itself would allow method groups to be resolved to Expression, but changing that isn't feasible.

**Comment by CyrusNajmabadi** [comment] 2021-08-11 20:23
@jinujoseph This would be a good issue to use for someone to look at to investigate and work on a fix for. Thanks!

**Comment by CyrusNajmabadi** [comment] 2021-08-18 19:02
> This seems like quite a pit of failure, with IDE suggestions to replace lambdas with method groups where possible... A warning definitely seems appropriate.

@roji  can you clarify this?  I don't believe there is any roslyn feature that is suggesting that you simplify this lambda.  Can you provide a screenshot for this, along with what error code/message you're getting here?  I'm going to preemptively close this out as i think it might be another tool you're using.  If it turns out to be roslyn, we can reopen this.

**Closed by CyrusNajmabadi** 2021-08-18 19:02 UTC
Labels: Area-IDE, Concept-Continuous Improvement

**Comment by CyrusNajmabadi** [comment] 2021-08-18 19:04
> This Queryable/Enumerable resolution behavior is one instance where this breaks down, and can be quite a pit of failure... 

We would not be able to change this as it would be a massive breaking change.  You could also write an analzyer here to look for this and warn you if it's a pattern you want to ban from your own codebases.

**Comment by roji** [comment] 2021-08-18 19:18
@CyrusNajmabadi you're right, upon further examination the IDE suggestion to convert to method group came from Resharper/Rider, and it turns out that they also turn off that suggestion for queryables. They also issue a diagnostic for this ("IQueryable is possibly unintentionally used as IEnumerable").

The only actionable thing I do see here is adding that diagnostic to Roslyn, as Resharper/Rider do and as @svick suggested above.

**Comment by CyrusNajmabadi** [comment] 2021-08-18 19:56
I don't see it being possible ot add a diagnostic here because of hte massive breaking change.  HOwever, tagging @jaredpar as a potential warning wave possibility.  I would say this wouldnt' be in roslyn either.  It would be up tot he BCL to decide if they wanted to chekc for this and have a suggestion on how to fix this up.
