### ISSUE TITLE
Relax CS0841 for the nameof operator.

### ISSUE THREAD

**Issue by mburbea** [dotnet/roslyn#7274] opened 2015-12-07 15:19 UTC
I'm currently working on some code that generates some expression trees and it would be useful when declaring parameter expressions to give them the names of the local variables that they are being assigned to for debugging purposes.
Currently the following code fails:
```csharp
var keys = Expression.Parameter(typeof(string[]), nameof(keys));
//
Error	CS0841	Cannot use local variable 'keys' before it is declared
```

A workaround is to do the following:
```
ParameterExpression keys;
keys = Expression.Parameter(typeof(string[]), nameof(keys));
```

But that's verbose and ugly. I'd prefer if I could just `nameof` on the same line as I declare the variable.

**Comment by dpen2000** [comment] 2015-12-07 18:28
This is a duplicate of #7031

**Closed** 2015-12-07 20:43 UTC
Labels: Area-Language Design, Resolution-Duplicate

**Comment by jrmoreno1** [comment] 2016-05-03 00:40
@mburbea : I think the ugliness comes from having the assignment on a second line, which is unnecessary.

    ParameterExpression keys = Expression.Parameter(typeof(string[]), nameof(keys));

reads just fine to me.
