### ISSUE TITLE
`using static` doesn't work for extension methods

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#67438] opened 2023-03-22 14:29 UTC
```
using System;
using static Test.Utils;

namespace Test
{
    public static class Utils
    {
        public static void Test1(this string str)
        {
            Array.Sort(new string[1], Test2);
        }

        public static int Test2(this string x, string y) => x.CompareTo(y);
    }
}

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Test1("a"); // Build failed
            Array.Sort(args, Test2); // Build failed
        }
    }
}
```

**Comment by svick** [comment] 2023-03-23 11:39
This is the correct behavior according to [the spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#1354-using-static-directives) (emphasis mine):

> Within member declarations in a compilation unit or namespace body that contains a *using_static_directive*, the accessible nested types and static members (**except extension methods**) contained directly in the declaration of the given type can be referenced directly.

This issue is also a duplicate of https://github.com/dotnet/roslyn/issues/31715.

**Closed by svick** 2023-03-23 11:39 UTC
Labels: Area-Compilers, untriaged
