### ISSUE TITLE
Renaming a copied Public class CHANGES original Class to NEW name. in Blend Visual Studio 2019

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#40779] opened 2020-01-07 18:24 UTC
@MJackson9595 commented on [Sun Jan 05 2020](https://github.com/dotnet/docs/issues/16539)

I copied one public class then repasted it in same folder and global namespace.

expected this error.  to show BEFORE I renamed the public class I copied to a different name.

WHAT I did NOT expect was Visual Studio 2019  to HELP by changing BOTH the public class and name of the member StartProgram () in the Original class to match the renamed class.

Blend for visual studios 2019 seems to be determined to change EVERY occurrence of a global namespace and member of that namespace to whatever I changed the COPIED names to.  Unable to find any way to tell Visual Studio blend 2019 to in this case do NOT change every occurrence of name in the project.   It is a great feature, when you realize you have just come up with a much better "name" then the one you  have been using so far.  But that is not the case here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62919633-6041-2d18-0b0c-ff1c8e690495
* Version Independent ID: 19a252b9-f0d8-ec57-1014-00ad6e5de9b3
* Content: [Compiler Error CS0101](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0101#feedback)
* Content Source: [docs/csharp/misc/cs0101.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0101.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by ryzngard** [comment] 2020-01-17 18:54
@MJackson9595 @BillWagner  from my understanding of this issue, it's by design. I don't really know how we'd distinguish between the "right" and "wrong" symbol if they both have the same fully qualified name. 


I'm closing as by design, but feel free to reopen if you have more information to share or ideas on how we could improve this experience.

**Closed by ryzngard** 2020-01-17 18:54 UTC
Labels: Area-IDE, Bug

**Comment by MJackson9595** [comment] 2020-01-23 01:27
NOT WHAT I SAID WAS PROBLEM.  SORRY IF I WAS NOT CLEAR.  I have a standard (for one job, as to what ALL public classes in that project must have. )  when  I copied that (template of mine only for that project) pasted it as A New class I expected to be able to rename copied class WITHOUT at same time having the original class RENAMED TO SAME AS NEW PUBLIC CLASS.   HOPE now what is the issue.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ryzngard** [comment] 2020-01-23 01:38
@MJackson9595 I still don't fully understand. Could you provide a small set of example code of the setup prior to the rename?

**Comment by ryzngard** [comment] 2020-01-23 01:53
For example, here was my understanding of the problem: 

`PublicClass.cs`

```csharp
public class PublicClass { } 
```

Copy that into a new file called `OtherClass.cs`

```csharp
public class PublicClass { }
```

Now try to rename `PublicClass` in `OtherClass.cs`, it also renames `PublicClass` in `PublicClass.cs`.

It sounds like that's not the problem though.
