### ISSUE TITLE
Visual Studio Editor Classifier partly broken because ISignature is casted to Signature

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#7332] opened 2015-12-08 20:07 UTC
# summary

when creating a new signature help (at least for c#), an exception occurs and prevents the new signatures from being displayed in Visual Studio.
# error location (probably)

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/IntelliSense/SignatureHelp/Presentation/SignatureHelpPresenter.SignatureHelpPresenterSession.cs
line: 161
# reproduction
## source

I happened to follow this walkthrough to get additional signature help not for text files but for c# files:
https://msdn.microsoft.com/en-us/library/ee334194.aspx?cs-save-lang=1&cs-lang=csharp to create a custom signature help provider.
## needed steps (quoting from the MSDN walkthrough)

Attached to this issue are the .cs files that have to be put into the project after these steps:
1. Create a C# VSIX project. (In the New Project dialog, select Visual C# / Extensibility, then VSIX Project.) Name the solution SignatureHelpTest.
2.Add an Editor Classifier item template to the project. For more information, see Creating an Extension with an Editor Item Template.
3.Delete the existing class files.
4.Add the following references to the project, and make sure CopyLocal is set to false:
- Microsoft.VisualStudio.Editor
- Microsoft.VisualStudio.Language.Intellisense
- Microsoft.VisualStudio.OLE.Interop
- Microsoft.VisualStudio.Shell.14.0
- Microsoft.VisualStudio.TextManager.Interop
## Here is what I changed (already included in the attached files)
- the ContentType attributes value to "csharp" (of which i did not find a documentation) 
- and changing "add" to "WriteLine" to make it useful
- and after uncommenting the textViewAdapter.AddCommandFilter command to not show an additional signature help box,
## Then this happened

two signatures are being added to the WriteLine (from 19 to 21). As soon as I want to change to the 20th or 21st signature, a TypeCastException is being thrown  stating that TestSignature shall be casted to Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Presentation.Signature.

There are two places in the roslyn reference source where such a cast happens, of which only one occurs in the event handler "OnSelectedSignatureChanged" (right after what I tried to do). Here, the new signature is being casted to Signature (which, sadly, is internal) to access the signature map.
Therefore I think that there is the cause of this unwanted behaviour.
# suggested fix

if the new signature help item is not managed by roslyn, it might be okay not to do anything further in OnSelectedSignatureChanged so just surround line 161ff with an if clause checking whether the ISignature is Signature. 
If this leads to a lack of text highlighting in the appearing items, one has to figure something out, bit it would surely be better not to have highlighting than not to see the syntax help (or wrap something around the one provided by roslyn)

**Comment by AdmiralSnyder** [comment] 2015-12-08 20:15
I appended .txt to the file names because githup doesn't allow .cs files. strange.
[TestSignatureHelpCommandProvider.cs.txt](https://github.com/dotnet/roslyn/files/55993/TestSignatureHelpCommandProvider.cs.txt)
[TestSignatureHelpSource.cs.txt](https://github.com/dotnet/roslyn/files/55994/TestSignatureHelpSource.cs.txt)
[TestSignatureHelpSourceProvider.cs.txt](https://github.com/dotnet/roslyn/files/55995/TestSignatureHelpSourceProvider.cs.txt)
[TestParameter.cs.txt](https://github.com/dotnet/roslyn/files/55997/TestParameter.cs.txt)
[TestSignature.cs.txt](https://github.com/dotnet/roslyn/files/55996/TestSignature.cs.txt)
[TestSignatureHelpCommandHandler.cs.txt](https://github.com/dotnet/roslyn/files/55998/TestSignatureHelpCommandHandler.cs.txt)

**Comment by AdmiralSnyder** [comment] 2015-12-08 20:16
Close and comment is not a good label for a button that closes an issue...

**Comment by Pilchie** [comment] 2015-12-10 17:31
This is similar to a bug that @rchande has looked at around other people who extend Completion Lists, but perhaps easier to fix as suggested above.

**Comment by brettfo** [comment] 2016-02-03 21:27
The change to use `ISignature` instead of `Signature` is easy enough, but I'd like to understand your scenario a bit better so I can wrap my head around the context.  What is your end goal in adding items to signature help?

**Comment by rchande** [comment] 2016-02-03 21:40
This is analogous to the bugs we have in completion when an extension implements `ICompletionSource`. Basically, we assume that all the items at the presentation layer (CompletionSet/CompletionItems or ISignatures) were provided by us and are therefore our implementation.

The fix for SignatureHelp would be to actually check if the newly selected `ISignature` is actually a `Signature`. If it isn't , we'll need a way to encode that we have items in the current session, but that the currently selected item isn't our. IIRC, a lot of our highlighting/parameter indicating code is based on accessing the underlying symbol being presented, so we'd probably have to disable that. I'm not sure if the editor offers a fallback solution.

**Comment by AdmiralSnyder** [comment] 2016-02-03 22:52
Currently, I want to reduce xml comment duplication by displaying the xml comment of base classes / interfaces to the user when the derived class / method doesn't have an xml comment, thus saving lots of useless copy/paste. In a later step, the IntelliSense comments should be enriched with information from analyzers, like centralized usage hints depending e.g. on argument types.

**Comment by rchande** [comment] 2016-02-03 23:22
Hm, I feel like we've talked about the first thing (showing base documentation on derived things) before. Maybe we should just implement that in Roslyn.

**Comment by Pilchie** [comment] 2016-02-04 03:29
cc @dpoeschl who was talking about this in the team room the other day.  We might have a duplicate of that issue.

**Comment by AdmiralSnyder** [comment] 2016-02-04 12:32
Even if you implement the xml comment "inheritance", currently, we have a documented feature (additional editor classifiers) that currently doesn't work. 

And adding custom additional info to the IntelliSense output seems like a very nice extension point, so fixing this bug seems desirable nonetheless, doesn't it?

**Comment by AdmiralSnyder** [comment] 2017-03-30 06:46
Is there a way i could test the change to possibly make a pull request?

**Comment by Pilchie** [comment] 2017-03-31 17:35
@AdmiralSnyder see https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md

**Comment by CyrusNajmabadi** [comment] 2023-11-21 23:16
Closing out as this is working as intended.

**Closed by CyrusNajmabadi** 2023-11-21 23:16 UTC
Labels: Bug, Area-IDE, 0 - Backlog
