### ISSUE TITLE
Remove string.Format() if nameof() is used

### ISSUE THREAD

**Issue by dbeuchler** [dotnet/roslyn#17356] opened 2017-02-24 14:04 UTC
For some strings it is usefull to use the `nameof()`-Operator but the resulting `string.Format()` is not really needed.

**Exsample**
Exceptions can be defined like this: 
`throw new InvalidCastException($"The type cannot be casted to {nameof(IMyInterface)}");`

**Version Used**: Visual Studio 2015 Update 3, .NET Framework 4.5.2

**Expected Behavior**:
The compiler should remove the `string.Format()`-Method and use the string itself.
`throw new InvalidCastException("The type cannot be casted to IMyInterface");`

**Actual Behavior**:
The result of the compiler is: 
`throw new InvalidCastException(string.Format("The type cannot be casted to {0}", "IMyInterface"));`

````
IL_001f: nop
IL_0020: ldstr "The type cannot be casted to {0}"
IL_0025: ldstr "IMyInterface"
IL_002a: call string [mscorlib]System.String::Format(string, object)
IL_002f: newobj instance void [mscorlib]System.InvalidCastException::.ctor(string)
IL_0034: throw
````

**Comment by svick** [comment] 2017-02-24 15:18
This is a duplicate of https://github.com/dotnet/roslyn/issues/11259.

**Closed** 2017-02-24 15:34 UTC

**Comment by IanKemp** [comment] 2018-12-13 09:12
Not a duplicate - this deals with only the very specific case of `nameof`.
