### ISSUE TITLE
IntelliSense doesn't recognize auto-generated classes in referenced project

### ISSUE THREAD

**Issue by nvborisenko** [dotnet/roslyn#65044] opened 2022-10-27 12:53 UTC
**Version Used**: Version 17.4.0 Preview 5.0

**Test Solution to Reproduce**: [MyCompany.MyConsoleApp.zip](https://github.com/dotnet/roslyn/files/9879415/MyCompany.MyConsoleApp.zip)

**Steps to Reproduce**:

1. Open solution in Visual Studio
2. Open `Program.cs` and `MyPage.po.yml` files in editor
3. Change the content of `MyPage.po.yml` file (e.g. _123_ to _123456_ to trigger source generation)
4. Return back to `Program.cs`

**Expected Behavior**: Solution is built, no intellisense issues.

**Actual Behavior**: Solution is built successfully, but there is intellisense issue: definition couldn't be found.

![image](https://user-images.githubusercontent.com/22616990/198286888-1c780fca-88b3-4679-9531-367568a68456.png)

`Ya()` is extension method which is auto-generated in `MyCompany.Library` project by incremental source generator in `MyCompany.Library` namespace. This issue is not only about extension methods, looks like all auto-generated stuff cannot be found.

![image](https://user-images.githubusercontent.com/22616990/198289077-fc4711a8-50fd-4271-905b-c47f87d4e6b1.png)

where `MyCompany.Library.MyPage` is produced by generator.

> Note: Restarting Visual Studio helps to get the errors rid away, but once we trigger generation process the errors return back.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 20:42
Closing out as by design.  The file needs to be saved to get us to rerun.

**Closed by CyrusNajmabadi** 2024-10-25 20:42 UTC
Labels: Area-IDE, New Feature - Source Generators
