### ISSUE TITLE
.NET Compiler Platform SDK not usable on Visual Studio 2017

### ISSUE THREAD

**Issue by couven92** [dotnet/roslyn#30285] opened 2018-10-03 12:16 UTC
**Version Used**: 
.NET Compiler Platform SDK, version `2.0.0.6140902` (Marketplace Item Name: [`VisualStudioProductTeam.NETCompilerPlatformSDK`](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK))

Visual Studio 2017 Community `15.8.6`

**Steps to Reproduce**:

1. Download the .NET Compiler Platform SDK from [Marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.NETCompilerPlatformSDK)
2. Install the downloaded VSIX
3. Upon first launch after installation Visual Studio immediately fires a Warning Message box (picture below)
4. Visual Studio then restarts with the extension disabled. The extensions is thus completely unusable.

![image](https://user-images.githubusercontent.com/8759693/46409519-32c85d80-c716-11e8-8fdb-d7492dbc9551.png)

> The following extension is disabled because the installed version is not compatible with Visual Studio Community 15.0.28010.2041.

Incredibly the Visual Studio version number in the message box does not match the version number actually reported in the `About Microsoft Visual Studio` dialog (in `Help`->`About`)

**Comment by couven92** [comment] 2018-10-03 12:19
The issue is also present in Visual Studio Community 2017 Preview, version `15.9.0 Preview 3.0`

**Comment by svick** [comment] 2018-10-03 12:35
I believe that in VS 2017, you're not supposed to use that extension. Instead, you should install the SDK using the VS installer.

I think the description of the extension should be updated to explain that.

**Comment by sharwell** [comment] 2018-10-03 13:40
Duplicate of dotnet/roslyn-sdk#80

**Closed by sharwell** 2018-10-03 13:40 UTC
