### ISSUE TITLE
SyntaxFactory.Token(SyntaxKind.InterpolatedVerbatimStringStartToken) C# don't fill the token text

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#33713] opened 2019-02-27 11:32 UTC
**Version Used**: 
Visual Studio 2019 Preview 3
**Steps to Reproduce**:

1. SyntaxFactory.Token(SyntaxKind.InterpolatedVerbatimStringStartToken)

**Expected Behavior**:
Token text and value should contains text $@"
**Actual Behavior**:
Token text and value is empty

SyntaxFactory.Token(SyntaxKind.InterpolatedStringStartToken) fill text and value correctly.

**Comment by gafter** [comment] 2019-02-27 17:35
@jcouv I think this may be fallout from the change to permit both `$@` and `@$`

**Comment by jcouv** [comment] 2019-02-27 17:40
I'll investigate asap.

**Comment by jcouv** [comment] 2019-02-28 01:54
Confirmed the new behavior is expected.
This compat break is due to the feature that allows interpolated verbatim strings to start with `@$"` instead of `$@"`. Because this token could now take two forms, we can no longer give a default answer when asked for the text of such token.

Sorry about that. The compat break was not properly documented. I should have added it to the compat break list. I'll file a PR to correct that.

**Comment by jcouv** [comment] 2019-02-28 04:09
Correction: I'm looking into a possible fix, but I need to confirm with the team whether it is correct.

**Comment by Droni** [comment] 2019-02-28 06:48
Hm. It seems to me that creating a token with a certain type, which, when generating a code, will not put anything in its place in the code, is very wrong behavior. You can, for example, leave the old behavior by default. And give the opportunity to use new behavior.

**Comment by jcouv** [comment] 2019-03-02 23:46
Fixed in 16.1p1. Thanks for reporting this. Sorry for the regression.

**Closed** 2019-03-02 23:46 UTC
Labels: Area-Compilers, Bug
