### ISSUE TITLE
Slow response when editing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24481] opened 2018-01-26 13:17 UTC
While editing VS2017 frequently freezes

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/188907/slow-response-when-editing.html
VSTS ticketId: 558041_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-01-26 13:19
This appears to be caused by allocations dominated by this stack:

![image](https://user-images.githubusercontent.com/1408396/35441475-3f1a0c72-0269-11e8-98ab-78e22ab93d04.png)

**Comment by CyrusNajmabadi** [comment] 2022-10-29 00:32
Closing out as this part of the ysstem was heavily revised since hten and we haven't gotten any more traces indicating an issue here.

**Closed by CyrusNajmabadi** 2022-10-29 00:32 UTC
Labels: Bug, help wanted, Area-IDE, Tenet-Performance, Developer Community
