### ISSUE TITLE
Code Style: Have the ability to share and enforce a common formatting scheme

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10285] opened 2016-04-01 23:44 UTC
Filed on behalf of a customer from interviews.

Would be interesting to see if multiple customers want to separate formatting rulesets from naming/etc.

**Comment by bojanrajkovic** [comment] 2016-04-02 07:13
Shared formatting rules would be fantastic even if only at the solution level. If it could be done at the project level, even better. We've used various extensions' support for this in the past (Rebracer, R#), but something integrated would be best.

**Comment by DustinCampbell** [comment] 2016-04-06 16:04
Isn't this technically a duplicate of this backlog item: #7061? Should we consolidate and have crisp work items here?

**Comment by Pilchie** [comment] 2016-04-08 21:24
Closing in favor of #7061.

**Closed by Pilchie** 2016-04-08 21:24 UTC
Labels: Area-IDE, Feature Request, Resolution-Duplicate
