### ISSUE TITLE
`LambdaExpression` operation missing when a lambda expression is used for delegate creation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8347] opened 2016-02-02 21:55 UTC
For example, in the following code snippet, `(s, e) => { }` is not recogonized as a `LambdaExpression`:

``` cs
Mumble += new MumbleEventHandler((s, e) => { });
```

It is mistakenly recognized as a `MethodBindingExpression`.

There's a testscase for this bug:
src\compilers\csharp\test\semantic\diagnostics\operationanalyzertests.cs

**Comment by mavasani** [comment] 2017-05-08 21:27
Dupe of https://github.com/dotnet/roslyn/issues/8884#issue-134680222.

Will be fixed by https://github.com/dotnet/roslyn/pull/19307

**Closed by mavasani** 2017-05-08 21:27 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
