### ISSUE TITLE
IDE Feature Request: Local functions in Go-To-All

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#54519] opened 2021-07-01 17:42 UTC
**Brief description:**

When I to Go-To-All (particularly in a single file) I'd like to see local function symbols there as well. I'll often see a comment I need to address in a code review and want to go to that exact function, but have to then find the outer function because the local function symbol doesn't appear.

**Languages applicable:**

C#

**Comment by CyrusNajmabadi** [comment] 2021-07-01 20:59
I'm not certain why local functions would be different from locals here.  Both/eitehr seem reasonable here.

**Comment by sharwell** [comment] 2021-07-01 21:09
Duplicate of #39083

**Closed by sharwell** 2021-07-01 21:09 UTC
Labels: Area-IDE, Feature Request, untriaged

**Comment by 333fred** [comment] 2021-07-01 22:38
Thanks Sam. My search-fu wasn't up to snuff.

> I'm not certain why local functions would be different from locals here. Both/eitehr seem reasonable here.

Locals _might_ make it a bit too cluttered, but that's definitely something we can experiment with.
