### ISSUE TITLE
MSBuildWorkspace: Exception : Unable to cast object of type 'Microsoft.CodeAnalysis.BuildTasks.Csc' to type 'Microsoft.Build.Framework.ITask'.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#24691] opened 2018-02-07 14:08 UTC
**Version Used**: 2.6.1 

**Steps to Reproduce**:

1. Create console app using VS 2015 and add nuget reference to Microsoft.CodeAnalysis (.NET framework 4.6.1)
2. On the same machine, VS 2017 comunity version is also installed.
3.  Try to call below program: 

```
using (var workspace = MSBuildWorkspace.Create())
{
     Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
     workspace.LoadMetadataForReferencedProjects = true;
 }
```
here the **projectPath** is a path of .csproj file.

**Expected Behavior**:
`workspace.OpenProjectAsync(projectPath).Result;` should run successfully and open the project.

**Actual Behavior**:
`Unable to cast object of type 'Microsoft.CodeAnalysis.BuildTasks.Csc' to type 'Microsoft.Build.Framework.ITask'.
`
**Stack Trace:**
 `  at Microsoft.Build.Shared.TaskLoader.CreateTask(LoadedType loadedType, String taskName, String taskLocation, Int32 taskLine, Int32 taskColumn, LogError logError, AppDomainSetup appDomainSetup, Boolean isOutOfProc, AppDomain& taskAppDomain)`

**Additional Info**:

Following are the nuget packages refereed

```
<package id="Microsoft.Build" version="15.5.180" targetFramework="net461" />
  <package id="Microsoft.Build.Framework" version="15.5.180" targetFramework="net461" />
  <package id="Microsoft.Build.Tasks.Core" version="15.5.180" targetFramework="net461" />
  <package id="Microsoft.Build.Utilities.Core" version="15.5.180" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Common" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.CSharp.Features" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Features" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.VisualBasic" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Features" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.Net.Compilers" version="2.6.1" targetFramework="net461" developmentDependency="true" />
```

**Comment by abdelkader27** [comment] 2018-02-20 15:59
Hi,

I'm getting the same issue. is there any information if this issue will be fixed.

thanks,

Abdelkader.

**Comment by jnm2** [comment] 2018-04-02 16:50
I ran into this because I had turned off Just My Code so that I could detect internally-handled FileLoadExceptions to figure out which package references I needed in order for the solution to not be empty. If you turn Just my Code back on, this issue will disappear.

**Comment by jnm2** [comment] 2018-04-02 16:53
Also, for the record, these are the only package references I needed:

```xml
    <PackageReference Include="Microsoft.Build" Version="15.6.82" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.6.82" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.7.0" />
```

**Comment by DustinCampbell** [comment] 2018-04-10 20:08
FWIW, the way to fix this is not really obvious. Essentially, the problem is that your application includes versions of the `Microsoft.Build.*` assemblies that are not compatible with the tasks that the project being loaded use. Unfortunately, this problem is exacerbated by the fact that the `Microsoft.CodeAnalysis.Workspaces.Common` package (which includes the `MSBuildWorkspace` type) pulls those packages and assemblies into your project.

If you want to get this working, there are two things to do:

1. Delete the `Microsoft.Build.*` assemblies from your build output.
2. Use the `Microsoft.Build.Locator` NuGet package to find and register an instance of MSBuild for `MSBuildWorkspace` to use.

This has the effect of loading the `Microsoft.Build.*` assemblies that `MSBuildWorkspace` needs from the registered instance of MSBuild. These should be compatible with the tasks that are used by the project you're trying to load.

Take a look at my reply here for more detail: https://github.com/dotnet/roslyn/issues/26029#issuecomment-380164421.

Also, in that issue, the customer created a GitHub repo demonstrating the problem. I went ahead and submitted a PR that shows how to fix the issue in that repo here: https://github.com/FizzerWL/ErrorRepro/pull/1. I hope that PR will be instructive to you too.

**Comment by IanKemp** [comment] 2018-04-19 12:06
@DustinCampbell's fix did not entirely work for me - even after doing what he suggested, `ReflectionTypeLoadException`s were being thrown because `Microsoft.CodeAnalysis.Workspaces.Desktop` 2.7.0.0 was trying to load `Microsoft.Build.Framework`, `Microsoft.Build`, and `Microsoft.Build.Tasks.Core` versions 15.1.0.0, but the versions in my Visual Studio installation directory were 15.8.65.37198.

Th additional step to make it all work was to add `bindingRedirects` to point to the versions of `Microsoft.Build.*` from my Visual Studio install.

To be honest, this whole process is terrible and messy and painful and totally bloody unnecessary; even finding this issue was a chore in and of itself. This is **NOT** the experience I'm used to with Microsoft tools, and it's extremely disappointing. When will this hoop-jumping be fixed?

**Comment by marcelstuder** [comment] 2018-06-21 08:21
I had the same issues and was able to reproduce/resolve the problem in this project: [sample-project](https://github.com/marcelstuder/findreferences) - see commit history

Adding BindingRedirects and the `Microsoft.Build.Locator` nuget pacakge as stated above by  @DustinCampbell resolved my issues

**Comment by CyrusNajmabadi** [comment] 2020-03-06 07:54
Issue was reported resolved.

**Closed by CyrusNajmabadi** 2020-03-06 07:54 UTC
Labels: Area-IDE, Bug
