### ISSUE TITLE
[Bug?] Rename Incorrectly renames original.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8126] opened 2016-01-23 04:31 UTC
If you copy an existing class (either by copying the file, or cut and pasting) Then rename the copy.
It renames the original and where it is referred.
```vb.net
Class Example

End Class
Class Example ' <- Rename

End Class
```
**Expected**
```vb.net
Class Example2 ' <- Incorrectly Renamed also.

End Class
Class Example2 ' <- Renamed

End Class
```
**Actual**
```vb.net
Class Example

End Class
Class Example2 ' <- Renamed Correctly

End Class
```
**Possible Fix**
Add an option to restrict the renaming to just this object definition..

**Comment by davkean** [comment] 2016-01-23 19:17
@AdamSpeight2008 you are entering rename mode on the second class for what reason? To update references to itself?

What I mean is if you have the following:

``` VB
Class Example
    Sub New()
        Dim e as new Example()
    End Sub
End Class
Class Example
    Sub New()
        Dim e as new Example()
    End Sub
End Class
```
Are you hoping for the following result:

```VB
Class Example
    Sub New()
        Dim e as new Example()
    End Sub
End Class
Class Example2
    Sub New()
        Dim e as new Example2()
    End Sub
End Class
```

Otherwise, what would be the point of enter rename mode on the second class?

**Comment by AdamSpeight2008** [comment] 2016-01-24 11:18
@davkean That's a possible option, restricted renaming to this class.

**Comment by Pilchie** [comment] 2016-01-26 17:16
This is a duplicate of #7291.

**Closed by Pilchie** 2016-01-26 17:16 UTC
Labels: Area-IDE
