### ISSUE TITLE
Invalid Inline variable declaration code fix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37415] opened 2019-07-22 22:57 UTC
<pre>class Foo
{
    public Bar Bar;
}
class Bar
{
    public int Value;
}

public static int Test(out int bar) =&gt; throw new NotImplementedException();

public void Inline()
{
    int bar; // This can be inlined
    _ = new Foo()
    {
        Bar =
        {
            Value = Test(out bar)
        }
    };
}</pre><p>When using the code-fix to apply inline variable declaration on the variable `bar` in the `Inline` function, the generated code will be `Value = Test(out intbar)` instead of `Value = Test(out int bar)` (note the missing space).</p><p>This only happens when using nested initializer syntax.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/517656/invalid-inline-variable-declaration-code-fix.html
VSTS ticketId: 839184_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 00:56 AM (105 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-07-22 22:58
Repro in 16.3.P2

**Comment by CyrusNajmabadi** [comment] 2019-07-22 23:11
@heejaechang something in the formatter?

**Comment by jinujoseph** [comment] 2019-07-23 17:46
Duplicate of #35993

**Closed by jinujoseph** 2019-07-23 17:46 UTC
Labels: Developer Community, Resolution-Duplicate
