### ISSUE TITLE
RenameTagProducerTests.CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34221] opened 2019-03-18 21:54 UTC
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=126806&view=ms.vss-test-web.build-test-results-tab)

```
Assert.Equal() Failure
Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[173..176), [266..269)]
Actual: List<Span> [[173..176), [266..269), [266..269)]
```

**Comment by sharwell** [comment] 2019-03-18 22:23
I reduced this test to the following to attempt to reproduce this...

```vb
<WpfTheory, IterationData(15000)>
<Trait(Traits.Feature, Traits.Features.Rename)>
Public Async Function CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict(iteration As Integer) As Task
    Using workspace = CreateWorkspaceWithWaiter(
            <Workspace>
                <Project Language="C#" CommonReferences="true">
                    <Document>
                        class Goo
                        {
                            int bar;
                            void M(int [|$$goo|])
                            {
                                var x = [|goo|];
                                bar = 23;
                            }
                        }
                    </Document>
                </Project>
            </Workspace>)

        Dim renameService = workspace.GetService(Of InlineRenameService)()
        Dim session = StartSession(workspace)

        Await VerifySpansBeforeConflictResolution(workspace, renameService)
    End Using
End Function
```

**Comment by sharwell** [comment] 2019-03-19 17:27
I suspected `conflictResolutionRenameTrackingSpans` was getting modified at some point, so I set a `FailFast` in the implementation and hit the following after nearly 30,000 iterations:

```
Application: testhost.x86.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Failed
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+OpenTextBufferManager.ApplyConflictResolutionEdits(Microsoft.CodeAnalysis.Editor.IInlineRenameReplacementInfo, Microsoft.CodeAnalysis.LinkedFileMergeSessionResult, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Document>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyReplacements(Microsoft.CodeAnalysis.Editor.IInlineRenameReplacementInfo, Microsoft.CodeAnalysis.LinkedFileMergeSessionResult, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+<<QueueApplyReplacements>b__66_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at Roslyn.Test.Utilities.DispatcherExtensions.DoEvents(System.Windows.Threading.Dispatcher)
   at Roslyn.Test.Utilities.AsynchronousOperationListenerExtensions+<>c.<WaitAllDispatcherOperationAndTasksAsync>b__0_0()
   at Microsoft.CodeAnalysis.Shared.TestHooks.AsynchronousOperationListenerProvider+<WaitAllAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Shared.TestHooks.AsynchronousOperationListenerProvider+<WaitAllAsync>d__13, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<WaitAllAsync>d__13 ByRef)
   at Microsoft.CodeAnalysis.Shared.TestHooks.AsynchronousOperationListenerProvider.WaitAllAsync(System.String[], System.Action)
   at Roslyn.Test.Utilities.AsynchronousOperationListenerExtensions.WaitAllDispatcherOperationAndTasksAsync(Microsoft.CodeAnalysis.Shared.TestHooks.IAsynchronousOperationListenerProvider, System.String[])
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTestHelpers+VB$StateMachine_10_WaitForRename.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTestHelpers+VB$StateMachine_10_WaitForRename, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_10_WaitForRename ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTestHelpers.WaitForRename(Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_34_GetTagsOfType.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_34_GetTagsOfType, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_34_GetTagsOfType ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.GetTagsOfType(Microsoft.VisualStudio.Text.Tagging.ITextMarkerTag, Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace, Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_8_VerifyTaggedSpansCore, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_8_VerifyTaggedSpansCore ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VerifyTaggedSpansCore(Microsoft.VisualStudio.Text.Tagging.TextMarkerTag, Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace, Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.Span>)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_1_VerifyEmptyTaggedSpans.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_1_VerifyEmptyTaggedSpans, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_1_VerifyEmptyTaggedSpans ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VerifyEmptyTaggedSpans(Microsoft.VisualStudio.Text.Tagging.TextMarkerTag, Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace, Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_6_VerifySpansBeforeConflictResolution.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_6_VerifySpansBeforeConflictResolution, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_6_VerifySpansBeforeConflictResolution ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VerifySpansBeforeConflictResolution(Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace, Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_18_CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests+VB$StateMachine_18_CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict, Microsoft.CodeAnalysis.EditorFeatures2.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](VB$StateMachine_18_CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict ByRef)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict(Int32)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CallTestMethod(System.Object)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], xunit.execution.desktop, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<InvokeTestMethodAsync>b__1>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4, xunit.execution.desktop, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AggregateAsync>d__4 ByRef)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeTestMethodAsync>b__0()
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9, xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__9 ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], xunit.execution.desktop, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<InvokeTestMethodAsync>d__48<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeTestMethodAsync(System.Object)
   at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(System.Object)
   at Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], xunit.execution.desktop, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<RunAsync>b__47_0>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<RunAsync>b__47_0()
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__10`1<System.Decimal> ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.Decimal>>)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].RunAsync()
   at Roslyn.Test.Utilities.WpfTestRunner+<>c__DisplayClass5_0+<<InvokeTestMethodAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Roslyn.Test.Utilities.WpfTestRunner+<>c__DisplayClass5_0+<<InvokeTestMethodAsync>b__0>d, Roslyn.Services.Test.Utilities, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<InvokeTestMethodAsync>b__0>d ByRef)
   at Roslyn.Test.Utilities.WpfTestRunner+<>c__DisplayClass5_0.<InvokeTestMethodAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Roslyn.Test.Utilities.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at Roslyn.Test.Utilities.StaTaskScheduler+<>c__DisplayClass8_1.<.ctor>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by RikkiGibson** [comment] 2019-05-28 16:57
VisualBasic_FixupSpanDuringResolvableConflict_NeedsEscaping is failing sometimes as well. Is the root cause the same? Did you fix this in a branch a few weeks ago @sharwell?

**Comment by JoeRobich** [comment] 2019-06-04 23:26
Seeing this in Roslyn Signed Builds - [Test Logs](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2734805&view=ms.vss-test-web.test-result-details)

**Comment by sharwell** [comment] 2019-06-11 16:33
Duplicate of #29483

**Closed by sharwell** 2019-06-11 16:33 UTC
Labels: 4 - In Review, Area-IDE, Flaky, Test
