### ISSUE TITLE
Cannot cast to `nint` or `nuint` right after getting the address of a symbol

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#62798] opened 2022-07-20 19:23 UTC
**Version Used**: Version 17.3.0 Preview 4.0

**Steps to Reproduce**:

1. Have an unmanaged symbol whose address you can get
2. Try to use the following expression: `(nint)&variable` (same applies for `nuint`

[SharpLab repro](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBMIGMD2A7DCMKOAGxgBoYQE48AfO5KSAAgAEAWVgYSVggARIiXIAKAJQBYAFABvWayWsAlnhgcA7ADUopOBFYBeVgAYA3IuUA3KAlbA4YSAgAKONTAj2TYvJ4kAMnYdPQNLGQBfIA==) (includes error that unsafe cannot be used without the flag, ignorable)

**Expected Behavior**:
Understands that it's not an attempt to use the binary `&` operator

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/8298332/180064085-f69effcd-670c-41ca-8971-9f652da75fd2.png)

**Workaround**:
You have to wrap the entire address-of expression into parentheses:
```csharp
(nint)(&variable)
```

**Details**:
The same applies to other types too that aren't non-contextual keywords: `IntPtr` and `UIntPtr` are included too.

**Comment by Youssef1313** [comment] 2022-07-20 20:00
See https://github.com/dotnet/csharplang/issues/5247 for a similar discussion

**Comment by RikkiGibson** [comment] 2022-07-21 03:16
It feels unfortunate that the expression `(int)&variable` is a cast because the parser knows that `int` must be a type, much like `(global::MyType)&variable`, but `(MyType)&variable` doesn't work because `MyType` might be a variable. It ends up feeling a bit arbitrary in practice. That said, I'm not sure there's anything we can do at this point to improve it.

**Comment by CyrusNajmabadi** [comment] 2022-07-21 15:09
Closing out as currently by design.  Roslyn is behaving properly here.  If we wanted this to be changed, it would have to come as a language change proposal in dotnet/csharplang that revised the disambiguation rules here.

**Closed by CyrusNajmabadi** 2022-07-21 15:09 UTC
Labels: Question, Area-Compilers, Resolution-By Design, Resolution-Answered, untriaged
