### ISSUE TITLE
"csc.exe" exited with code -532462766

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25948] opened 2018-04-05 05:32 UTC
I got a new computer and installed VS 15.6.2
This did not happen in 
VS 15.5.7

Application: csc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.Cryptography.CryptographicException
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32)
   at System.Security.Cryptography.Utils._ImportKey(System.Security.Cryptography.SafeProvHandle, Int32, System.Security.Cryptography.CspProviderFlags, System.Object, System.Security.Cryptography.SafeKeyHandle ByRef)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(System.Security.Cryptography.RSAParameters)
   at Microsoft.CodeAnalysis.SigningUtilities.CalculateRsaSignature(System.Collections.Generic.IEnumerable`1&lt;System.Reflection.Metadata.Blob&gt;, System.Security.Cryptography.RSAParameters)
   at Microsoft.CodeAnalysis.PortableStrongNameProvider+&lt;&gt;c__DisplayClass9_0.&lt;SignPeBuilder&gt;b__0(System.Collections.Generic.IEnumerable`1&lt;System.Reflection.Metadata.Blob&gt;)
   at System.Reflection.PortableExecutable.PEBuilder.Sign(System.Reflection.Metadata.BlobBuilder, System.Reflection.Metadata.Blob, System.Func`2&lt;System.Collections.Generic.IEnumerable`1&lt;System.Reflection.Metadata.Blob&gt;,Byte[]&gt;)
   at System.Reflection.PortableExecutable.ManagedPEBuilder.Sign(System.Reflection.Metadata.BlobBuilder, System.Func`2&lt;System.Collections.Generic.IEnumerable`1&lt;System.Reflection.Metadata.Blob&gt;,Byte[]&gt;)
   at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1&lt;System.IO.Stream&gt;, System.Func`1&lt;System.IO.Stream&gt;, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, System.Nullable`1&lt;System.Security.Cryptography.RSAParameters&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1&lt;System.IO.Stream&gt;, System.Func`1&lt;System.IO.Stream&gt;, System.Func`1&lt;System.IO.Stream&gt;, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, Boolean, System.Nullable`1&lt;System.Security.Cryptography.RSAParameters&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Func`1&lt;System.Object&gt;, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean, Boolean, System.String, System.Nullable`1&lt;System.Security.Cryptography.RSAParameters&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(Microsoft.CodeAnalysis.TouchedFileLogger, Microsoft.CodeAnalysis.Compilation ByRef, System.Collections.Immutable.ImmutableArray`1&lt;Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer&gt;, System.Collections.Immutable.ImmutableArray`1&lt;Microsoft.CodeAnalysis.AdditionalTextFile&gt;, System.Collections.Immutable.ImmutableArray`1&lt;Microsoft.CodeAnalysis.EmbeddedText&gt;, Microsoft.CodeAnalysis.DiagnosticBag, System.Threading.CancellationToken, System.Threading.CancellationTokenSource ByRef, Boolean ByRef, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver ByRef)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter, Microsoft.CodeAnalysis.ErrorLogger, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc+&lt;&gt;c__DisplayClass1_0.&lt;Run&gt;b__0(System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`2&lt;System.IO.TextWriter,Int32&gt;)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(System.String[], Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(System.String[], Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1&lt;System.String&gt;, Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1&lt;System.String&gt;, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/218055/cscexe-exited-with-code-532462766.html
VSTS ticketId: 585862_
_These are the original issue comments:_

Jared Payne on 3/19/2018, 09:51 AM (16 days ago): <p>As a debug step on the project I turned off the "sign the assembly"  and the build worked correctly. I was using a .snk file to sign the assembly.</p>

Andy Gocke [MSFT] on 4/2/2018, 01:02 PM (2 days ago): <p>Do you know what parameters you used to generate the snk file? That would be helpful.</p>
Jared Payne on 4/2/2018, 02:31 PM (2 days ago): <p>In the Project &gt; Properties &gt; Signing  I have selected "Sign the assembly" and selected a strong name key file<br>As a diagnostic step I turned off "Sign the assembly" and the project build without errors</p>

_These are the original issue solutions:_

Jared Payne solved on 4/2/2018, 02:29 PM (2 days ago), 0 votes: <p>In the Project Properties under Signing I selected  "Sign the assembly" and chose a strong name key file</p><p>As a diagnostic step I turned off signing the assembly and the build worked properly.</p>

Jared Payne solved on 4/2/2018, 02:33 PM (2 days ago), 0 votes: <p>I do not know How the snk file was generated it has not been updated.</p>

**Comment by jaredpar** [comment] 2018-08-30 23:14
Closing as we'ev been unable to reproduce this issue.

**Closed by jaredpar** 2018-08-30 23:14 UTC
Labels: Area-Compilers
