### ISSUE TITLE
Csc.dll exited with code 139 on ARM64 device

### ISSUE THREAD

**Issue by rszemplinski** [dotnet/roslyn#37106] opened 2019-07-10 14:56 UTC
**Version Used**: 
dotnet sdk 2.2.301

**Steps to Reproduce**:

1. Build project on Ubuntu 16.04 ARM64 machine

**Expected Behavior**:
Build Successful

**Actual Behavior**:
Build failed

```
/home/ubuntu/dotnet/sdk/2.2.301/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/home/ubuntu/nodester/Engine/ThirdParty.Data/Nodester.Engine.ThirdParty.Data.csproj]
/home/ubuntu/dotnet/sdk/2.2.301/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/home/ubuntu/nodester/Common/Nodester.Common.csproj]

Build FAILED.

/home/ubuntu/dotnet/sdk/2.2.301/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/home/ubuntu/nodester/Engine/ThirdParty.Data/Nodester.Engine.ThirdParty.Data.csproj]
/home/ubuntu/dotnet/sdk/2.2.301/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/home/ubuntu/nodester/Common/Nodester.Common.csproj]
    0 Warning(s)
    2 Error(s)
```

**Comment by jcouv** [comment] 2019-07-10 16:33
@davidwrighton Could you take a look at this?
@rszemplinski Could you provide some form of repro (a small self-contained project would be best)?

**Comment by attilaodry** [comment] 2019-08-07 04:14
I have the same issue on a Lenovo C330 arm based chrome os running linux.
The problem is the architecture, I just tried to complie the hello world demo app from .net site.

~/work/test/hellocsharp$ dotnet build
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 136.77 ms for /work/test/hellocsharp/hellocsharp.csproj.
/opt/dotnet-sdk-2.2-arm64/sdk/2.2.401/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/work/test/hellocsharp/hellocsharp.csproj]

Build FAILED.

/opt/dotnet-sdk-2.2-arm64/sdk/2.2.401/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/work/test/hellocsharp/hellocsharp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:10.00

**Comment by attilaodry** [comment] 2019-08-07 04:36
addition: same device using latest .NET 3.0 (instead of 2.2) works without any problem, installed as system global (/usr/share/dotnet).

**Comment by rszemplinski** [comment] 2019-08-07 12:22
Oops, yeah my apologies. I upgraded to .NET Core 3.0 and everything worked perfectly.

**Comment by jcouv** [comment] 2019-08-07 17:08
@rszemplinski I'll go ahead and close since the problem appears to be fixed in .NET Core 3.0. Thanks

**Closed by jcouv** 2019-08-07 17:08 UTC
Labels: Area-Compilers, Area-External, Blocked

**Comment by Jon2G** [comment] 2022-04-27 05:04
Im facing this issue in Net6.0 sdk 6.0.200
Ubuntu Armx64

**Comment by jcouv** [comment] 2022-04-27 05:14
@Jon2G Could you open a new issue and provide some details on your recent repro? If this is consistent for you, I wonder if there's a way to get a crash dump or some log that would get a clue beyond an error code. Thanks
