### ISSUE TITLE
Variables that are generated from non-nullable types are typed as nullable

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41604] opened 2020-02-12 06:57 UTC
**Version Used**: 
This may be regressed in 16.5, but I don't have the version installed.
Version 16.6.0 Preview 1.0 [29811.143.master]

**Steps to Reproduce**:

``` C#
using System;

#nullable enable

namespace ConsoleApp190
{
  class Program
  {
    static void Main(string[] args)
    {
      var foo = GetFoo(); // <-- "Use explicit type instead of var" code fix
    }

    private static string GetFoo()
    {
      return string.Empty;
    }
  }
}

```

**Expected Behavior**:
``` C#
      string foo = GetFoo();
```
**Actual Behavior**:
``` C#
      string? foo = GetFoo();
```

I'm seeing this in a bunch of code fixes, so please tell if this is a different fix per code fix and I'll file the others.

**Comment by sharwell** [comment] 2020-02-12 13:35
Duplicate of #41243

**Closed by sharwell** 2020-02-12 13:35 UTC
