### ISSUE TITLE
add analyzer option pages that controls which analyzers run only opened files and all files

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#13642] opened 2016-09-06 23:15 UTC
currently we use effective severity to determine whether we are going to run diagnostic analyzers only for opened files or all files. but that only works because currently severity is per compilation. on going work to make editor config part of compilation will break that (since now diagnostic can have different effective severity per files)

so we no longer can use effective severity as a way to determine what analyzers to run on opened files and what not.

we need explicit control from users for it. so we need UI for users to set those.

**Comment by heejaechang** [comment] 2016-09-06 23:15
@srivatsn can you assign it to right person?

**Comment by sharwell** [comment] 2018-05-03 15:13
Duplicate of #12713

**Closed by sharwell** 2018-05-03 15:13 UTC
Labels: Area-Analyzers, Feature Request
