### ISSUE TITLE
Default analyzer template does not work reliably

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#8067] opened 2016-01-21 08:43 UTC
I'm on VS 2015 Update 1 and doing following steps:
* Create a new project based on the analyzer with codefix template
* Remove the test and vsix projects, build the analyzer project
* Create a new WinForms project (in a new VS instance)
* Add the analyzer (by selecting the DLL built in step 2)

I'd expect 4 warnings but only get 3, the warning for the Form1 class is missing.

* Then I close the project and VS instance
* Change the analyzer to report as an error instead of an warning and rebuild
* Open the WinForms project again (in a new VS instance)

I'd expect 4 errors. I get 4 errors in the compile output but only 3 errors in the error list. Again the Form1 class is missing from the error list.

(Might be related to issue #3748 since the Form1 class is partial? But note that Settings and Resources classes are also partial and for these the analyzer works, so I'm not sure if its the same cause.)

**Comment by srivatsn** [comment] 2016-03-11 00:04
@mavasani - can you verify that this is fixed now?

**Comment by mavasani** [comment] 2016-04-29 23:16
Verified no repro in Update2.

**Comment by weltkante** [comment] 2016-05-02 07:03
@mavasani  @srivatsn  I can still repro this in Update2 but it requires some more work (in particular closing/opening Form1 documents in the IDE). At some point the Analyzer message about Form1 is gone and doesn't come back. I'll try to determine a sequence of actions which reliably reproduces the behavior.

**Comment by weltkante** [comment] 2016-05-02 07:17
in addition to the steps in the first report:
* close all files then open both Form1.cs and Form1.Designer.cs in the code editor
* close VS with Form1.cs editor being active
* start VS, notice that 4 Analyzer messages are displayed (doesn't matter whether you set it to warning or error)
* switch to Form1.Designer.cs tab
* notice that the Form1 Analyzer message is gone

Besides the obvious bug of losing the Analyzer message I also noticed that when I first start VS the Analyzer message for Form1 does appear in the error list but it **does not** appear in the code editor as squiggles (it does for the other Analyzer messages). That's probably another hint that this issue isn't entirely fixed.

**Comment by weltkante** [comment] 2016-05-02 07:21
Note that this is not the only way to lose the Analyzer message, you can get it happen without Form1.Designer.cs in a code editor, just with Form1.cs in code and designer view, but I couldn't figure out how to reproduce it reliably.

Another observation: when all 3 are open (Form1.cs code editor, Form1.designer.cs code editor and Form1.cs designer) then the Analyzer message appears as squiggles only in Form1.Designer.cs and not in the main Form1.cs file.

So there is definitely still bugs and confusion going on with Analyzers and partial classes.

**Comment by mavasani** [comment] 2016-05-02 16:59
Thanks @weltkante - I was able to repro your new scenario with the latest bits. Seems like some race condition for computing open file diagnostics for partial types. I am investigating further.

**Comment by mavasani** [comment] 2016-05-02 17:43
So I was able to create a simpler repro and identify the root cause. The primary issue here seems to be that the ordering of the locations returned in `Symbol.Locations` is indeterministic between different compilations with same inputs, causing analyzer that just uses `symbol.Locations[0]` to report diagnostic on different location for partial types. This causes IDE diagnostic engine logic that merges open file and full project diagnostics to sometimes miss reporting diagnostics (we use different compilations to compute open file and full project diagnostics). Adding @heejaechang as this repros even on v2 engine.

**Repro steps:**
1. Unzip the repro project - 
[WindowsFormsApplication1.zip](https://github.com/dotnet/roslyn/files/245584/WindowsFormsApplication1.zip)
2. Open the solution in VS and let for full solution analysis to complete - i.e. 4 diagnostics to show up in error list
3. One of the analyzer diagnostics will have location either in Form1.cs or Form1.designer.cs - this seems to vary every time I open the solution, due to the issue I mentioned above.
4. First open Form1.designer.cs and than Form1.cs (right click on Form1.cs and View Code).

**Got:** The 4th diagnostic will disappear for majority of the times, and never appear in error list again until both Form1.cs and Form1.designer.cs are both closed. If you are unable to repro, then close all open files, and repeat steps 2-4.

**Reason:** When we try to compute diagnostics for newly opened file, we use a fresh compilation. If we open 2 files with partial type definitions, such that diagnostic analysis on both the compilations report diagnostic on the non-active file, this diagnostic will never show up.

I think we ought to make `Symbol.Locations` have a deterministic ordering for all compilations with same inputs. Otherwise, even command line builds can generate inequivalent analyzer diagnostics between builds with same compiler inputs. @gafter @jaredpar Any thoughts?

**Comment by mavasani** [comment] 2016-05-02 18:45
Opened https://github.com/dotnet/roslyn/issues/11015 to track the underlying issue

**Comment by heejaechang** [comment] 2016-05-02 21:06
I think this should be fixed in compiler layer. I don't think we want to sort all symbol locations to make it deterministic in our side.

**Comment by mavasani** [comment] 2016-05-16 22:37
NOTE: Please verify that https://github.com/dotnet/roslyn/issues/3748#issuecomment-218400083 is also fixed when closing this bug.

FYI @weltkante

**Comment by mavasani** [comment] 2016-05-16 22:38
FYI @tvsonar

**Comment by mavasani** [comment] 2016-06-10 21:27
I verified that this issue is fixed with underlying issue #11015 being fixed.

However, https://github.com/dotnet/roslyn/issues/3748#issuecomment-218400083 is still not fixed, but that is *by-design* due to incorrect analyzer implementation. I'll add a comment to https://github.com/dotnet/roslyn/issues/3748 about the same.

**Closed by mavasani** 2016-06-10 21:27 UTC
Labels: Area-Analyzers, Blocked, Bug
