### ISSUE TITLE
Switch optimizations aren't applied to pattern matching

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#58246] opened 2021-12-10 03:36 UTC
**Version Used**: 
https://github.com/dotnet/roslyn/commit/9f8250964a72d53efe2d04fc0b2b07a48f04a45c

**Steps to Reproduce**:
```C#
public class C
{
    public bool M1(Values v) =>
        v switch
        {
            Values.Zero or Values.One or Values.Two or Values.Three or Values.Four => true,
            _ => false,
        };
    
    public bool M2(Values v) =>
        v is Values.Zero or Values.One or Values.Two or Values.Three or Values.Four;
}

public enum Values
{
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six
}
``` 

**Expected Behavior**:
Both M1 and M2 producing code equivalent to:
```C#
    public bool M1(Values v)
    {
        if ((uint)v <= 4u)
        {
            return true;
        }
        return false;
    }
```

**Actual Behavior**:
M1 optimizes the five checks into a single range comparison, but M2 is compiled into 5 distinct comparisons:
```C#
    public bool M1(Values v)
    {
        if ((uint)v <= 4u)
        {
            return true;
        }
        return false;
    }

    public bool M2(Values v)
    {
        if (v != 0 && v != Values.One && v != Values.Two && v != Values.Three)
        {
            return v == Values.Four;
        }
        return true;
    }
```

**Comment by alrz** [comment] 2022-02-17 14:15
https://github.com/dotnet/roslyn/issues/45679 dupliacte?

**Comment by jcouv** [comment] 2022-04-15 08:01
Indeed. Closing as duplicate of https://github.com/dotnet/roslyn/issues/45679
@stephentoub I'll tag on that other issue so you automatically follow it. Will triage it shortly.

**Closed by jcouv** 2022-04-15 08:01 UTC
Labels: Bug, Area-Compilers, New Language Feature - Pattern Matching, Code Gen Quality, untriaged
