### ISSUE TITLE
IDE0056 cannot be inverted / works only when preferring index-from-end operator

### ISSUE THREAD

**Issue by Ravigneaux1** [dotnet/roslyn#69054] opened 2023-07-15 16:33 UTC
**Version Used**: 

- .NET SDK 7.0.304
- Microsoft Visual Studio Community 2022 (64-bit), version 17.6.4

**Steps to Reproduce**:

1. Create a project with `<EnforceCodeStyleInBuild>` and `<TreatWarningsAsErrors>` both set to `true`

2. Create an `.editorconfig` file within the same directory with the following contents:

   ~~~ini
   [*.cs]
   dotnet_diagnostic.IDE0056.severity = warning
   csharp_style_prefer_index_operator = false:warning
   ~~~

3. Add the following code to a method of `Program.cs` (or any other class):

   ~~~csharp
   string[] names = { "Archimedes", "Pythagoras", "Euclid" };

   var name1 = names[^1];
   var name2 = names[names.Length - 1];
   ~~~

**Diagnostic Id**:

[`IDE0056`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0056)

**Expected Behavior**:

Usage of the [index-from-end operator](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#index-from-end-operator-) in the assignment of `name1` raises warning `IDE0056`, offering to use calculation-based indexing, as used in the assignment of `name2`, as a quick fix.

**Actual Behavior**:

Usage of the index-from-end operator does **not** raise warning `IDE0056`. When changing option `csharp_style_prefer_index_operator` to `true:warning`, however, the warning is raised as expected for the indexing in the assignment of `name2`.

**Comment by CyrusNajmabadi** [comment] 2023-07-15 17:47
Closing out as by design. 'false: doesn't mean 'invert'. It means "do not offer to convert". With most of our style choices, the feature is there to help move you forward to the idiomatic forms the language has added, not to hold one back.

**Closed by CyrusNajmabadi** 2023-07-15 17:47 UTC
Labels: Area-Analyzers, untriaged

**Comment by Ravigneaux1** [comment] 2023-07-15 21:03
@CyrusNajmabadi, thank you very much for the prompt review! I have to add a remark, though...

Isn't the documentation misleading, then? 🤔 The specification of [`csharp_style_prefer_index_operator`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0056#csharp_style_prefer_index_operator) states the following for option value `false`:

   > Prefer not to use the `^` operator when calculating an index from the end of a collection

   In my humble opinion, the description should read _"No preference for usage of the `^` operator"_ (or something like that) if the intention of the value `false` truly is to disable the style rule - which, in my understanding, is actually done by setting the rule's severity to `none`.

There are several other rules for which the documentation literally states that option value `false` will prefer the opposite. I'm quite confused now...

**Comment by CyrusNajmabadi** [comment] 2023-07-15 22:37
Definitely good doc feedback!

**Comment by Ravigneaux1** [comment] 2023-07-15 22:53
> Definitely good doc feedback!

If I find time, I will open a new issue for that. Thanks for pointing this out! Looks like I've spent some days' work based on a wrong assumption 😅
