### ISSUE TITLE
IDE0030 incorrect code fix

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#16762] opened 2017-01-26 02:25 UTC
**Version Used**: 
VS2017RC 15.0.26020.0
**Steps to Reproduce**:

input sample code in IDE:
```C#
class A
{
    string bar;
    int Foo(int i)
    {
        return bar == null ? -1 : bar[i];
    }
}
```
**Expected Behavior**:
code fix to
```C#
return bar?[i] ?? -1;
```
**Actual Behavior**:
```C#
return bar?[i];
```

**Comment by Pilchie** [comment] 2017-01-26 03:16
Tagging @CyrusNajmabadi, but I think this is a dupe and already fixed in the latest bits.

**Comment by huoyaoyuan** [comment] 2017-01-26 04:06
Noticed #16387 and #15511. I haven't tested the latest version, but hope you to have an eye on the `x?.y??default` pattern.

**Comment by CyrusNajmabadi** [comment] 2017-02-07 05:56
This has been fixed, and we no longer offer this invalid change.   As for your expected behavior, we welcome PRs. :)

**Closed by CyrusNajmabadi** 2017-02-07 05:56 UTC
Labels: Area-IDE, Bug
