### ISSUE TITLE
'Convert to for' disappears when struct member is invoked on the foreach variable

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#32739] opened 2019-01-24 16:47 UTC
**Version Used**: VS 2019 Preview 2.0

```cs
var test = new[] { new Foo() };
foreach (var foo in test)
{
    _ = foo.SomeProperty; // Remove `.SomeProperty` and 'Convert to for' comes back
    // Calling a struct method also scares it away.
    // Interestingly, calling .ToString() does not scare it away so long as it is `Object.ToString`
    // that is being called and not a struct override.
}

struct Foo
{
    public string SomeProperty { get; }
}
```

**Expected Behavior**: 'Convert to for' should be available. Otherwise I'm going to have to do this by hand, which has been nearly exclusively the case for me.

I don't care if the semantics change. Even if the struct was mutable and even if it mutated during calls in the loop body, that's not going to stop me from needing access to `i` and wanting to do this particular refactoring to get there.

**Actual Behavior**: Refactoring is not offered.

**Comment by CyrusNajmabadi** [comment] 2019-01-24 18:21
I could imagine this being 'by design' in a very 'strict' sense (given the concern that a read of the prop could count as a mutation).  That said, this is likely overly strict and prevents the refactoring for working 100% fine in huge numbers of cases involving structs.

Given this is a refactoring, we should likely relax our check here.

**Comment by sharwell** [comment] 2019-01-24 21:18
:memo: this may be able to leverage the analyzer notion of immutable struct types that we use for Make Field Readonly.

**Comment by jnm2** [comment] 2019-01-24 22:18
Right. The fact that there may be a subtle change does not mean I want Roslyn to suddenly leave me on my own to do the same thing by hand, with no potential guidance about the subtlety. The need to refactor hasn't gone away.

**Comment by Neme12** [comment] 2019-02-23 19:29
Why would the refactoring change semantics? The `foo` iteration variable stores a copy of the struct so we can't mutate the original struct in the array anyway.

**Comment by Neme12** [comment] 2019-02-23 19:31
We can always generate the following:
```c#
for (var i = 0; i < test.Length; i++)
{
    var foo = test[i];
    _ = foo.SomeProperty;
}
```

**Comment by Paxxi** [comment] 2019-03-05 06:57
I'm interested in this one.
I started to investigate it yesterday and now I'm curious about the data flow analysis. It marks any property access of a struct as a write to the struct. https://github.com/dotnet/roslyn/blob/95a6f7b98afab2c9c14cce4d0b8298374624a645/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs#L1093 is the method in question. Is this done for a specific reason or is there a bug here?

I'm thinking the solution here would be to remove the data flow analysis completely as any result would be ignored if this is to support structs as well.

**Comment by CyrusNajmabadi** [comment] 2020-03-22 03:04
Fixed with https://github.com/dotnet/roslyn/pull/34384

**Closed by CyrusNajmabadi** 2020-03-22 03:04 UTC
Labels: Area-IDE, Bug, help wanted
