### ISSUE TITLE
"Move type to Foo.cs" refactoring brings too much code along for the ride

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#30751] opened 2018-10-25 04:20 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2017
v15.8.8

**Steps to Reproduce**:

1. Create an empty .NET Framework Class Library project
2. Add the below code to the file
3. Set the cursor to line 3, column 21, ch 21
4. Press Ctrl+.
5. Select "Move type to Foo.cs"
6. Open Foo.cs

Code:

```csharp
namespace Parent
{
    public class Foo
    {
    }

    public class Bar
    {
    }
}


#region Baz
#if Baz

namespace Parent.Child
{
    public class Baz
    {
    }
}

#endif
#endregion
```

**Expected Behavior**:

Class1.cs:

```csharp
namespace Parent
{
    public class Bar
    {
    }
}


#region Baz
#if Baz

namespace Parent.Child
{
    public class Baz
    {
    }
}

#endif
#endregion
```

Foo.cs:

```csharp
namespace Parent
{
    public class Foo
    {
    }
}
```

**Actual Behavior**:

Class1.cs:

```csharp
namespace Parent
{

    public class Bar
    {
    }
}


#region Baz
#if Baz

namespace Parent.Child
{
    public class Baz
    {
    }
}

#endif
#endregion
```

Foo.cs:

```csharp
namespace Parent
{
    public class Foo
    {
    }
}


#region Baz
#if Baz

namespace Parent.Child
{
    public class Baz
    {
    }
}

#endif
#endregion
```

**Comment by d-dizhevsky** [comment] 2018-10-30 22:01
Seems like this just copies everything that is outside of the namespace to the new file. Also reproducible in VS Code on Mac OS. Going to give this a shot but don't know where to start yet.

**Comment by genlu** [comment] 2019-01-08 02:05
@d-dizhevsky Are you still working on this? 
No pressure :) I'm just looking at existing bugs and see if there's something I can pick up.

**Comment by d-dizhevsky** [comment] 2019-01-09 00:41
@genlu not really as I was not able to debug that part of a compiler on macos due to some wpf dependencies. Feel free to take it :)

**Comment by genlu** [comment] 2019-01-09 01:15
@d-dizhevsky Ah, I see. OK, I will give it a try then.

**Comment by genlu** [comment] 2019-01-12 00:09
I just took a closer look, this is actually the expected behavior, as everything in `#if` is treated as trivia when symbol is undefined. There's no way for IDE to handle that since the text isn't even parsed by compiler as code. In general, this is not a well supported scenario in IDE, many features rely on users to handle the cases like this. For, example, placing `#if` at certain location might help:

```cs
namespace Parent
{
    public class Foo
    {
    }

    public class Bar
    {
    }
}


#region Baz

namespace Parent.Child
{
#if Baz
    public class Baz
    {
    }
#endif
}

#endregion
```

**Comment by genlu** [comment] 2019-01-12 00:11
@yaakov-h Resolving this as by-design

**Closed** 2019-01-12 00:11 UTC
Labels: Area-IDE, Bug, Resolution-By Design
