### ISSUE TITLE
Auto Formatting Column Mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59921] opened 2022-03-03 17:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-Formatting-Column-Mode/1682901)._

---
[severity:I'm unable to use this version]
There are occasions where it is nice to be able to arrange your code into columns.

Would it be possible to add a feature to Visual Studio so you can designate a region or whole file to columns formatting?

When auto formatting runs it will automatically arrange each line into columns delimited by (e.g. comma)

```
# AutoFormatRegion(Column, ",")
   MyFunction("Bob"         ,  "Davidson"   , 18)  
   MyFunction("William"     ,  "Smith"      , 18)  
   ...
# EndAutoFormatRegion
```

---
#### Feedback Bot on 3/3/2022, 02:14 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment] 2022-03-09 19:44
Duplicate of #28729

**Closed by jinujoseph** 2022-03-09 19:44 UTC
Labels: Area-IDE, untriaged
