### ISSUE TITLE
VB Overrides completion is very slow (~10s) for subtypes of InternalSyntax.VisualBasicSyntaxVisitor

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3969] opened 2015-07-15 20:36 UTC
1. In Compilers\VisualBasic\Test\Syntax\Parser\ParseXml.vb, add the following declaration within the `ParseXml` type:

``` VB
Private Class Visitor : Inherits InternalSyntax.VisualBasicSyntaxVisitor
End Class
```
1. In the body of the new type, type `Overrides` and hit Ctrl-Space to bring up Completion.

It takes roughly 10 seconds (on a fast machine) for the dialog to appear.

It looks like roughly half of the CPU time is spent trying to compute the minimally-qualified name.  Presumably, this is because every name in the `InternalSyntax` namespace conflicts with a name in the parent namespace (also in scope).

**Comment by amcasey** [comment] 2015-07-15 20:36
FYI @rchande

**Comment by AdamSpeight2008** [comment] 2015-07-15 23:38
@amcasey 
Am I right in thinking that has nothing to do with `Compilers\VisualBasic\Test\Syntax\Parser\ParseXml.vb` but either`InternalSyntax.VisualBasicSyntaxVisitor` or the is it `CompletionList`?

**Comment by amcasey** [comment] 2015-07-16 00:06
@AdamSpeight2008 I suspect the only thing that matters about the setting (i.e. ```ParseXml.vb```) is that the parent namespace of ```InternalSyntax``` is in scope.

```InternalSyntax.VisualBasicSyntaxVisitor``` is interesting because it is large and because its members reference many symbols that require non-trivial simplification.

I would be surprised to learn that the Completion code is to blame (beyond the fact that it asks for simplified names).

**Comment by rchande** [comment] 2015-08-31 16:59
@amcasey On my machine, it takes about 2 blinks of the caret for the completion list to show up. Is there a different repro?

**Comment by rchande** [comment] 2015-08-31 17:43
Never mind, @amcasey , I was looking at the wrong parsexml.vb.

**Comment by rchande** [comment] 2015-08-31 22:16
As Andrew mentions, the bulk of the time is spent computing minimal display strings.

One possible mitigation that @dpoeschl and I discussed is to not minimally qualify names once we're displaying a certain number of members (30? 50? 100?). In those cases,  we could also try something like not qualifying names at all, unless we find multiple items with the same text, in which case we could quality only those items.

Otherwise, I imagine we'd probably want some variation of ISymbolDisplayService that can be instructed to cache results.

What do you think @Pilchie @DustinCampbell?

**Comment by dpoeschl** [comment] 2015-08-31 22:23
For the proposed heuristic @rchande described above, we mean that we could not minimally qualify them for the initial completion list item's display text. But, we could still correctly qualify the text that shows up in the quickinfo off the completion item. 

With override completion, we're already doing more codegen than is visible in the completion list display text, so the display text is mostly there to help you pick the one you want rather than to show you exactly what text will be inserted into the editor. Exact text is nice, but inexact text when the there are lots of override-able members seems acceptable to me.

**Comment by DustinCampbell** [comment] 2015-09-01 14:14
Out of curiosity, how many overloads are we talking about here? Also, because performing minimal qualification multiple times in the same location requires tons of duplicate work, I think a facility for caching would be generally useful.

**Comment by rchande** [comment] 2015-09-01 16:59
We're talking thousands of overloads. The time scales linearly with the number of overloads, so our experience is probably okay when there are only hundreds.

**Comment by DustinCampbell** [comment] 2015-09-01 23:20
Thousands? I know it's generated, but does ```InternalSyntax.VisualBasicSyntaxVisitor``` really have that many?

**Comment by Pilchie** [comment] 2015-09-04 03:38
Is it the case that we're simplifying the same names all the time?  I hate to say it, but is it time for a Compilation + context + symbol -> SimplifiedName cache?

**Comment by DustinCampbell** [comment] 2015-09-04 03:45
We talking about that earlier. Seems like a good place for something. The primary concern is whether we should just add a cache with our own policy or whether we should add an API for the consumer to provide a cache so they can control policy.

**Comment by Pilchie** [comment] 2015-09-04 03:52
Time for another `ConditionalWeakTable` that stores these for the life of the compilation?  The problem is all the different contexts...

**Comment by DustinCampbell** [comment] 2015-09-04 03:56
Yes, since each caller might want a different location and because some callers might want a cache of 100's or 1000's of items, it seemed interesting to allow the caller to control the caching policy -- much like you can do with advanced text formatting in WPF.

**Comment by rchande** [comment] 2015-09-04 17:12
Worse still, callers can use different formats.

**Comment by dpoeschl** [comment] 2016-01-08 22:41
Encountering the same problem in cref completion. In Roslyn.sln it takes ~2 seconds to show the completion list in a cref.

**Comment by DustinCampbell** [comment] 2016-02-23 00:06
@rchande -- do we plan to do anything here for 1.2?

**Comment by rchande** [comment] 2016-09-19 20:45
@mavasani FYI that we added the Tenet-Performance label for this. However, it's a very limited scenario so we'd like to move it to `2.1`. I'm optimistically moving it, but feel free to move it back if you feel it meets the bar.

**Comment by mavasani** [comment] 2016-09-19 20:46
@rchande Agreed - this doesn't seem to meet the bar.

**Comment by rchande** [comment] 2016-09-19 20:55
Removing Tenet labeling.

**Comment by mavasani** [comment] 2016-11-16 19:44
I am hitting this on latest Dev15-RC bits with the following repro steps:

Steps to reproduce:

1. Get a latest Dev15 RC build OR install the latest Roslyn VSIX. I installed \\cpvsbuild\drops\Roslyn\Roslyn-Signed\dev15-rc2\Release\20161115.7\Vsix\Roslyn.Deployment.Full.Next\Roslyn.Deployment.Full.Next.vsix on d15rel 15.0.25903.2
2. Open VS and turn off CodeLens and Full solution analysis for C# and VB (this is just to avoid noise from servicehub process in the ETL trace)
3. Open Roslyn.sln in VS
4. Open source file: src\VisualStudio\Core\Def\Implementation\Workspace\VisualStudioDocumentTrackingService.cs
5. Add cref comment to public constructor of this type and try to invoke completion within it by pressing Ctrl + space.

**Got:** around 10 seconds of pause, which is consistent when I dismiss the completion list and invoke it again.

CPU stacks for the trace shows we are spending 60% of inclusive stacks in SymbolDisplay.ToMinimalDisplayParts()
```
Name                                                                         Exc %  Exc Inc %
microsoft.codeanalysis.csharp.features!CrefCompletionProvider.CreateItem      0.4   57   64.5
microsoft.codeanalysis.csharp!SymbolDisplay.ToMinimalDisplayParts             0.0   4     62.9

**Comment by CyrusNajmabadi** [comment] 2020-03-14 07:01
This no longer repros:

![notrepro](https://user-images.githubusercontent.com/4564579/76677063-eded5b00-6586-11ea-90bd-bf08ae00abc8.gif)

**Closed by CyrusNajmabadi** 2020-03-14 07:01 UTC
Labels: Area-IDE, Bug, Tenet-Performance
