### ISSUE TITLE
Allow unit test compilation to be configured

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#2809] opened 2015-05-15 22:44 UTC
The compilation object used by the unit test base class DiagnosticVerifier creates a compilation object under that covers that includes a small set of references. So for example, if I have an analyzer that checks to see if a class derives from System.Xml.XmlDocument, the test will fail (even though the analyzer actually works) because the compilation used in the unit test does not have a reference to System.XmlDocument.

I can work around that by adding an additional MetadataReference in DiagnosticVerifier.Helper.cs. But it would be nice if this -- and similar configuration of the compilation object -- were exposed as an API from the DiagnosticVerifier base class. So, for example, I could say:

    AddMetadataReference(typeof(XmlDocument));

You might expose some sort of scaffolding object on which options like this could be set, or expose the option setters directly as APIs on the base class, as above.

**Comment by srivatsn** [comment] 2015-05-15 22:53
This is a dupe of #2369

**Closed by srivatsn** 2015-05-15 22:53 UTC
