### ISSUE TITLE
Provide an editor option to create interpolated ($-prefixed) strings by default

### ISSUE THREAD

**Issue by Treit** [dotnet/roslyn#53996] opened 2021-06-10 17:58 UTC
When writing C# code, it would be helpful to have an option such that when a user types a double-quote character to create a string literal, an interpolated string is created by default. In other words, the IDE would automatically prefix the the string literal with the '$' symbol.

I find that a majority of the time I am writing a string literal I end up going back and changing it to an interpolated string. Having the editor take care of this for me would make for a significantly nicer experience.

Since there is no overhead to a $-prefixed string that does not contain substitution parameters, it seems there would be little downside. Removing the $ symbol in the very rare cases I do not want string interpolation would not be much of a burden, and of course this feature would be optional.

**Comment by CyrusNajmabadi** [comment] 2021-06-10 18:55
CLosing out.  You don't need to do the above.  Instead, you can just add your curlies to the string.  And, at that point, the lightbulb will be available to help you trivially convert without navigating:

![image](https://user-images.githubusercontent.com/4564579/121581534-c764dc80-c9e2-11eb-9b3d-ee645cbc2775.png)

**Comment by Treit** [comment] 2021-06-10 19:05
> CLosing out. You don't need to do the above. Instead, you can just add your curlies to the string. And, at that point, the lightbulb will be available to help you trivially convert without navigating:
> 
> ![image](https://user-images.githubusercontent.com/4564579/121581534-c764dc80-c9e2-11eb-9b3d-ee645cbc2775.png)

That seems to wrap the curly-braces in more curly-braces. That then requires even more typing to remove the extra curly braces. . It's also quite a few more keystrokes to type the curly braces, then press ctrl+., then down arrow a few times to get to the 'Convert to interpolated string' item, then press enter...and then end up with double-curly-braces instead of the actual curly braces, which is not what is desired at all.

I want this:
```cs
int i = 0;
string s = $"{i}";
Console.WriteLine(s);
```

What you suggested results in this:

```cs
int i = 0;
string s = $"{{i}}";
Console.WriteLine(s);
```

The first outputs '0' and the second outputs '{s}'.

So I don't see how your suggested work-around solves the original issue of making it more ergonomic to get interpolated strings.

**Comment by ryanbrandenburg** [comment] 2021-08-02 21:26
Design Meeting Notes:
Lets add a chord `Ctrl+{`, which causes conversion of the current string to an interpolated string.
Leave the existing refactoring as-is.

**Comment by sharwell** [comment] 2023-01-23 19:32
Also requested here:
https://developercommunity.visualstudio.com/t/When-user-types--to-start-a-string-in/10175837

**Comment by sharpninja** [comment] 2023-01-23 19:41
> CLosing out. You don't need to do the above. Instead, you can just add your curlies to the string. And, at that point, the lightbulb will be available to help you trivially convert without navigating:
> 
> ![image](https://user-images.githubusercontent.com/4564579/121581534-c764dc80-c9e2-11eb-9b3d-ee645cbc2775.png)

This is not a helpful suggestion.  It requires extra steps you must remember to do EVERY time you create a string.

**Comment by sharpninja** [comment] 2023-01-23 19:43
> Design Meeting Notes: Lets add a chord `Ctrl+{`, which causes conversion of the current string to an interpolated string. Leave the existing refactoring as-is.

Why does this have to require extra effort?  Why not a setting to apply the developers preferred behavior?  I rarely create a string that isn't interpolated.

**Comment by sharwell** [comment] 2023-01-23 21:24
@sharpninja We need a feature that works for a broad group of users. For highly specific use cases (e.g. someone who always wants to create interpolated strings), I'd recommend creating a Visual Studio extension to handle typing the `"` character.

**Comment by sharpninja** [comment] 2023-01-24 19:42
> @sharpninja We need a feature that works for a broad group of users. For highly specific use cases (e.g. someone who always wants to create interpolated strings), I'd recommend creating a Visual Studio extension to handle typing the `"` character.

<rant on>I posted this as a Visual Studio feature, not as a Roslyn feature.  "Feedback Bot" decided it was a duplicate of this and closed my feature request.  Horrible customer service!</rant>

**Comment by CyrusNajmabadi** [comment] 2024-10-25 18:16
Closing out due to lack of broader feedback on this.  We understand the scenarios and request.  But we're explicitly choosing to keep the current behavior.

**Closed by CyrusNajmabadi** 2024-10-25 18:16 UTC
Labels: Area-IDE, Feature Request
