### ISSUE TITLE
Flaky Test CSharp_FixupSpanDuringResolvableConflict_ReferenceConflict

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#37834] opened 2019-08-08 18:00 UTC
Error:
```
Assert.Equal() Failure
Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[24..27), [66..69), [72..75)]
Actual:   List<Span> [[24..27), [66..69), [66..69), [72..75), [72..75)]
```
https://dev.azure.com/dnceng/public/_build/results?buildId=300070&view=ms.vss-test-web.build-test-results-tab&runId=8529978&resultId=100368&paneView=debug
Failed in https://github.com/dotnet/roslyn/pull/37826, which makes no code changes and could not have caused this.

Looking at the test history from the past 2 weeks, the FixupSpan tests seem to be flaky in general, as almost all the failures are various fixupspan tests.
![image](https://user-images.githubusercontent.com/2371880/62726234-a177e680-b9cb-11e9-8b54-bfb059a4fcf1.png)

@jinujoseph for triage.

**Comment by RikkiGibson** [comment] 2019-08-08 19:34
Related to #29483

**Comment by jinujoseph** [comment] 2019-08-09 23:02
https://github.com/dotnet/roslyn/pull/34254

**Comment by sharwell** [comment] 2019-09-06 18:26
Duplicate of #29483

**Closed by sharwell** 2019-09-06 18:26 UTC
Labels: 4 - In Review, Area-IDE, Bug, Test
