### ISSUE TITLE
SymbolKey loses nullability information

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#38061] opened 2019-08-16 21:29 UTC
When using `ISymbol.GetSymbolKey()` if the symbol is an `ITypeSymbol` the nullability information is lost.  Possibly related to #30326

**Comment by CyrusNajmabadi** [comment] 2022-11-01 17:44
Closing out.  This is by design.  Symbolkey very much is intended to have a metadata/binary-view of things.  Nullability isn't relevant there.  If it needed, the feature-lvel code needs to handle that.

**Closed by CyrusNajmabadi** 2022-11-01 17:44 UTC
Labels: Area-IDE, Concept-Continuous Improvement, New Language Feature - Nullable Reference Types
