### ISSUE TITLE
'Move type to new file' quick fix/refactoring doesn't work correctly in shared projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65099] opened 2022-10-28 19:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Move-type-to-new-file-quick-fixrefact/10184637)._

---
If we have a shared project like this

![image.png](https://aka.ms/dc/image?name=B7927b196a4514bb2ba9c48e460184d1b638025418882691625_20221028-091807-image.png&tid=7927b196a4514bb2ba9c48e460184d1b638025418882691625)

and I choose the quick fix to move SharedClass2 into a new file

![image.png](https://aka.ms/dc/image?name=B68e76c68d6c24d0893445ae26a010dfd638025419612395444_20221028-091920-image.png&tid=68e76c68d6c24d0893445ae26a010dfd638025419612395444)

I would expect SharedClass2.cs to be in SharedProject, but instead it ends up in one of the other projects

![image.png](https://aka.ms/dc/image?name=Baa8ddf5441c14f59b2201b9b3d7a27c8638025420141357826_20221028-092013-image.png&tid=aa8ddf5441c14f59b2201b9b3d7a27c8638025420141357826)

---
#### Feedback Bot on 10/28/2022, 02:46 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2022-10-28 20:48
Duplicate of #62360

**Closed by ryzngard** 2022-10-28 20:48 UTC
Labels: Resolution-Duplicate, Area-IDE, untriaged
