### ISSUE TITLE
Nullable Optional Tuple Parameter Crashes Visual Studio 2019

### ISSUE THREAD

**Issue by C26000** [dotnet/roslyn#41989] opened 2020-02-27 18:39 UTC
I'm using Visual Studio 2019 with C#8 and when I try to add this code:

`public void CalcularTodo((Contexto, bool)? cargarDetalles = (null, false)) { }
`
It brings down Visual Studio 2019, every time. That syntax is probably incorrect but it shouldn't do that.

If I keep it wihout the nullable ? it justs gives me a compiler error but doesn't close Visual Studio 2019

`public void CalcularTodo((Contexto, bool) cargarDetalles = (null, false)) { }`

**Comment by RikkiGibson** [comment] 2020-02-28 00:33
I can't repro this in Visual Studio 16.4.5. Could you please tell us the version number in `Help > About Visual Studio` in the menu bar?

**Comment by C26000** [comment] 2020-02-28 02:02
Hello,

This is the version I have:
Microsoft Visual Studio Community 2019
Versión 16.4.5

**Comment by RikkiGibson** [comment] 2020-02-28 17:47
(not certain whether this bug relates to nullable reference types or not, but tagging it anyway.)

Since I don't have the declaration of `Contexto` I tried making this similar-ish example:

```cs
#nullable enable
class C
{
	public void M((C, bool)? param = (null, false)) { }
}
```

Could you please share additional details about the scenario that causes the crash? Perhaps a zip file containing a minimal reproduction of the bug or a [crash dump](https://github.com/dotnet/roslyn/blob/master/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md)?

**Comment by C26000** [comment] 2020-02-28 18:46
I tried your class and it doesn't produce the problem.  I made some tests but apparently the bug is very specific to my classes. That method is inside an abstract generic class Factura<E, M> so things may be very specific to my case but still is a very serious bug that may affect randomly other users.

My project is open source so if you can clone it it would be the most direct way of testing it in the same case scenario.

This is the project page https://github.com/C26000/SimpleOps and here you find the class that has method with the problem: https://github.com/C26000/SimpleOps/blob/master/SimpleOps/Modelo/Abstractas/Factura.cs

Just change

`public bool CalcularTodo(Contexto? ctx = null, bool cargarDetalles = false, bool cargarEntidadEconómica = false, bool cargarProductos = false)`

for

`public void CalcularTodo((Contexto, bool)? cargarDetalles = (null, false))
`
And it inmmediatly crashes.

**Comment by RikkiGibson** [comment] 2020-02-28 18:55
Thanks, will take a look :)

**Comment by RikkiGibson** [comment] 2020-02-28 23:15
Thanks for reporting this bug. I can repro this with 16.4.5 but not 16.5-preview2 or 16.6-preview2.

If you install the [Visual Studio public preview](https://visualstudio.microsoft.com/vs/preview/) you should no longer experience the bug.

Stack:
```
Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSpecialType(Microsoft.CodeAnalysis.SpecialType)
Microsoft.CodeAnalysis.CSharp.LocalRewriter.GetDefaultParameterValue(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol, Microsoft.CodeAnalysis.ThreeState, Microsoft.CodeAnalysis.CSharp.LocalRewriter, Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.DiagnosticBag)
Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArgumentsEvaluate(Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray<int>, bool)
Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArguments(Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression>, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind>, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol>, System.Collections.Immutable.ImmutableArray<int>, bool, bool, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol)
Microsoft.CodeAnalysis.CSharp.NullableWalker.ReinferMethodAndVisitArguments(Microsoft.CodeAnalysis.CSharp.BoundCall, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithState)
Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall)
Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor)
Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression)
Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression)
Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(ref int, Microsoft.CodeAnalysis.CSharp.BoundExpression)
...
[Call Stack Truncated]
```

This may be an instance of #39868. Will close this issue as a duplicate.

**Closed by RikkiGibson** 2020-02-28 23:15 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
