### ISSUE TITLE
Issue: var does not handle Generic anonymous functions

### ISSUE THREAD

**Issue by pmunin** [dotnet/roslyn#15661] opened 2016-12-04 01:18 UTC
**Expected Behavior**:
```
var selector = (Node n) => {
     return new {Node = n, ChildrenCount = n.Children.Count };
}
```
**Actual Behavior**:
```
public static class Workaround
{
    public static Func<T1,TResult> Function<T1,TResult>(Func<T1,TResult> func)
    {
        return func;
    }
}

///...

var selector = Workaround.Function( (Node n) => {
     return new {Node = n, ChildrenCount = n.Children.Count };
});

```

**Comment by HaloFour** [comment] 2016-12-04 01:42
Dupe of #14 which was already closed.

In short, delegates are all different types according to the CLR and they are incompatible with each other even if their signature matches.  The C# language has no special knowledge of any specific delegate types, including the `Func<...>` or `Action<...>` delegate families.  If lambda inference were to decide to use `Func<...>`, assuming that could be done unambiguously, assigning that to a variable or parameter of a different-but-compatible signature would involve wrapping the delegate with another delegate.  That doubles the overhead when invoking the delegate, each call costing about the same as a virtual instance method call, which isn't a lot but can add up in aggregate.

**Comment by aluanhaddad** [comment] 2016-12-07 07:03
I still think this is worth reconsidering, especially if collection literals are on the table, because they will also have to somewhat arbitrarily target clandestine types that are conventionally used.

> If lambda inference were to decide to use Func<...>, assuming that could be done unambiguously, assigning that to a variable or parameter of a different-but-compatible signature would involve wrapping the delegate with another delegate.

But isn't the suggestion here to only use Func<....> when it would otherwise be an error?

**Comment by CyrusNajmabadi** [comment] 2022-11-08 17:15
Closing out.  This is legal now in the language.

**Closed by CyrusNajmabadi** 2022-11-08 17:15 UTC
Labels: Area-Language Design
