### ISSUE TITLE
WellKnownFixAllProviders.BatchFixer does not apply fixes in auto-generated code

### ISSUE THREAD

**Issue by handerss-tibco** [dotnet/roslyn#69739] opened 2023-08-28 14:13 UTC
The `WellKnownFixAllProviders.BatchFixer` does not perform any of the registered code fixes on code marked as auto-generated, despite the analyzer being configured to analyze auto-generated code. This can easily be reproduced by creating an analyzer configured to analyze auto-genrated code and a code fix provided which uses `WellKnownFixAllProviders.BatchFixer` as its `FixAllProvider`. Trying to apply the fix in a file marked with `// <auto-generated/>` fails when trying to apply the fix for the entire document, project, or solution. It also fails if trying to apply the fix via `dotnet format`.

I would not expect a `FixAllProvider` to determine in which files the diagnostics should be fixed, instead I would expect it to apply the fix for all diagnostic provided.

I have created a minimal reproducible example here: https://github.com/handerss-tibco/batch-fixall-generated

SDK info:

```
.NET SDK:
 Version:   7.0.307
 Commit:    7b77e35a2b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.307\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4
```

Package versions:

```xml
<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.6.0" />
```

**Comment by handerss-tibco** [comment] 2023-08-28 14:32
I realize the reproducible example does not use the latest packages, I'll upgrade and re-open if the problem persists.

**Comment by handerss-tibco** [comment] 2023-08-29 06:09
I have upgraded the packages in the reproducible example and the issue persists.

**Comment by CyrusNajmabadi** [comment] 2023-08-29 21:45
I believe this is by design. Fixing auto-generated code is not valuable as the code will be regenerated and will blow away the changes. 

What's the scenario where this should be done.

**Comment by handerss-tibco** [comment] 2023-08-30 05:58
The scenario is simply that `// <auto-generated/>` has been added to code which isn't auto-generated to silence warnings. Guessing this was done when an older project got migrated to newer analyzer (or analyzers at all), or something similar.

I was just surprised that a CodeFixProvider or a FixAllProvider would filter out diagnostics that it has been requested to and can fix. There's nothing in the documentation to indicate this (AFAICT). However, I can see the reasoning for this design too.

Feel free to close if you don't think it's a good design decision to support this scenario.

**Comment by CyrusNajmabadi** [comment] 2023-08-30 16:05
Thanks. Closing out. In the cases I would remove the errant `auto-generated` tags.

**Closed by CyrusNajmabadi** 2023-08-30 16:05 UTC
Labels: Area-IDE, untriaged
