### ISSUE TITLE
Unspecified error when opening Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1457] opened 2015-03-21 00:25 UTC
A dialog saying "unspecified error" shows up many times (once for each project?) when opening Roslyn.sln. Seems like data in .vs directory is corrupted. Repo including the .vs dir is in %internal_share%\tomat\Bugs\1457\Roslyn.zip

**Comment by Pilchie** [comment] 2015-03-23 15:10
Dupe of an internal issue from another team.  @jasonmalinowski has details I believe.

**Closed by Pilchie** 2015-03-23 15:10 UTC
Labels: Area-IDE, Bug
