### ISSUE TITLE
Analyzer diagnostic messages printed to error list, but not in build output

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#2980] opened 2015-05-21 17:16 UTC
This repros on VSPro_Platform 22919.00

1. Create a new C# console application
2. Run these commands in the Package Manager Console:

        install-package Microsoft.Net.ToolsetCompilers -version 1.0.0-rc2-20150415-05
        install-package StyleCop.Analyzers -version 1.0.0-alpha006

3. Rebuild

**EXPECTED**
3 analyzer warning messages added to the error list *and* printed in the build output window.

**ACTUAL**
3 analyzer warning messages added to the error list but the build output window shows no such warnings.
Command line builds similarly show no warnings.

**Error List** 

Severity Code | Description | Project | File
-------- | ----- | ----- | ---- 
Warning SA1600 | Elements must be documented | ConsoleApplication1   | C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
Warning SA1400 | Element 'Main' must declare an access modifier | ConsoleApplication1 |  C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
Warning SA1400 | Element 'Program' must declare an access modifier | ConsoleApplication1 | C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
 
**Build output window**
> All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Any CPU ------
1>  ConsoleApplication1 -> C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by mavasani** [comment] 2015-05-21 21:58
@AArnott @tmeschter @JohnHamby I was able to get a repro for this.

The issue is the StyleCop analyzers package has an analyzer (at least one) with an enabled by default rule, but doesn't register any actions (it has a TODO comment for adding implementation). This wasn't handled properly in our compiler analyzer driver and it was crashing out without executing any analyzers! I plan to:

1. Send a PR out for the fix, which is essentially a null check at one place.
2. Open a post 1.0 work item to bubble up such exceptions in analyzer driver as diagnostics instead of swallowing them up.

Once again, thanks a lot @AArnott for diligently following up on this, setting up repros and helping us iron out these issues. Very much appreciated!

**Comment by mavasani** [comment] 2015-05-21 23:35
Fixed by https://github.com/dotnet/roslyn/commit/96bbb86dd1f216cef0d7a8500b063b76c6b7366b in stabilization branch.

**Closed by mavasani** 2015-05-21 23:35 UTC
Labels: Area-Analyzers, Bug

**Comment by AArnott** [comment] 2015-05-22 17:17
Yay. Thanks, @mavasani
