### ISSUE TITLE
windows-1251 Cyrillic variable names problem

### ISSUE THREAD

**Issue by valeri2** [dotnet/roslyn#4298] opened 2015-08-03 14:26 UTC
I have a problem when compiling source files encoded in windows-1251 with variable names in Cyrillic. The compiler begins issuing an error message: **error BC30037: the Character is not valid**.

As I found out when the encoding of the source file is not UTF8, the compiler tries to read the file using encoding windows-1252. Because of this a compile-time error occurs.

src\Compilers\Core\Portable\ EncodedStringText.cs:

```
/// <summary>
/// Encoding to use when UTF-8 fails. If available, we use CodePage 1252. If not, we use Latin1.
/// </summary>
private static readonly Encoding s_defaultEncoding = GetDefaultEncoding();

private static Encoding GetDefaultEncoding()
{
    try
    {
        return PortableShim.Encoding.GetEncoding(1252);
    }
    catch (NotSupportedException)
    {
        return Encoding.GetEncoding(name: "Latin1");
    }
}
```

**Comment by sharwell** [comment] 2015-08-03 15:13
This sounds like another report of #4264.

**Comment by jaredpar** [comment] 2015-08-03 15:18
Thanks for reporting.  This does appear to be a duplicate of #4264.  Going to let that bug be the primary tracker.

**Closed by jaredpar** 2015-08-03 15:18 UTC
Labels: Area-Compilers
