### ISSUE TITLE
Partial method filled in by source generator still getting red squigglies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#58976] opened 2022-01-20 20:07 UTC
**Version Used**: 
Version 17.1.0 Preview 3.0 [32113.165.d17.1]

**Steps to Reproduce**:

1. Install a .NET 7 SDK, e.g. https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
2. Create a new Console App project in VS.
3. Edit the .csproj to change net6.0 to net7.0.
4. Change the contents of Program.cs to:
```C#
using System.Text.RegularExpressions;

Console.WriteLine(C.Create().IsMatch("abc"));

partial class C
{
    [RegexGenerator("abc")]
    public static partial Regex Create();
}
```
5. Rebuild.
6. Right click on Create and select Go To Definition.

**Expected Behavior**:
No red squigglies.

**Actual Behavior**:
Build succeeds, Go To Definition works fine, but the method is still red squiggled
![image](https://user-images.githubusercontent.com/2642209/150413870-649eec2f-69ab-4898-a938-b5ab022df447.png)

cc: @jasonmalinowski

**Comment by stephentoub** [comment] 2022-01-20 20:07
cc: @joperezr, @danmoseley

**Comment by jasonmalinowski** [comment] 2022-01-20 20:19
It's quite possible this is a duplicate of the issue that @sharwell and I have been looking at in the MAUI context but another repro that doesn't involve MAUI is interesting; much of what we were seeing in the MAUI case implied we may have had issues with MAUI targets but that won't apply here, obviously.

**Comment by Youssef1313** [comment] 2022-01-20 21:46
Duplicate of https://github.com/dotnet/roslyn/issues/58913

**Comment by jasonmalinowski** [comment] 2022-01-22 02:17
I strongly suspect this will be fixed by https://github.com/dotnet/roslyn/pull/58990; a quick attempt to debug this caused my debugger to hang, but it looked like the regex generator was being pulled in later after other generators were present.

**Closed** 2022-01-22 02:18 UTC
Labels: Area-IDE, untriaged
