### ISSUE TITLE
Decompilation only decompiles "public" API

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25248] opened 2018-03-06 02:20 UTC
1. Create a new Console Application
2. Install **xUnit 2.1.0** NuGet package
3. Turn on decompilation
4. Right-click on `Assert.Contains` and choose **Go to Definition**

``` C#
using System;
using Xunit;

namespace ConsoleApp191
{
    class Program
    {
        static void Main(string[] args)
        {
            Assert.Contains("foo", "c");
        }
    }
}

```

Get:
``` C#
                public static void Contains<T>(T expected, IEnumerable<T> collection, IEqualityComparer comparer)
		{
			//IL_0005: Unknown result type (might be due to invalid IL)
			//IL_0006: Expected O, but got Unknown
			//IL_0026: Unknown result type (might be due to invalid IL)
			//IL_0029: Expected Ref, but got Unknown
			Assert.GuardArgumentNotNull("comparer", (object)(?)comparer);
			Assert.GuardArgumentNotNull("collection", collection);
			IEnumerator<T> enumerator = ((IEnumerable<?>)collection).GetEnumerator();
			try
			{
				while (((IEnumerator)enumerator).MoveNext())
				{
					T current = ((IEnumerator<?>)enumerator).get_Current();
					if (((IEqualityComparer)(?)comparer).Equals((!0)expected, (!0)current))
					{
						return;
					}
				}
			}
			finally
			{
				if (enumerator != null)
				{
					((IDisposable)enumerator).Dispose();
				}
			}
			throw new ContainsException(expected, collection);
		}
```

5. On Assert.GuardArgumentNotNull, choose Go To Definition

**Expected:** To navigate to GuardArgumentNotNull
**Actual:** 
```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot navigate to the symbol under the caret.
---------------------------
OK   
---------------------------
```

**Comment by sharwell** [comment] 2018-03-06 04:02
> Unknown result type (might be due to invalid IL)

This is related to #24178. It is almost certainly caused by a failure to locate a transitive-referenced assembly, but I'm not treating it as a duplicate since the specific assembly and reason it's missing is likely different.

**Comment by sharwell** [comment] 2018-03-07 11:44
Duplicate of #25246

**Closed** 2018-03-07 11:47 UTC
Labels: Area-IDE, Resolution-Duplicate
