### ISSUE TITLE
Obsolete-Attribute on awaitable's type GetAwaiter method is a breaking change

### ISSUE THREAD

**Issue by gh3x78E** [dotnet/roslyn#11361] opened 2016-05-17 08:44 UTC
_I have asked this previously on [stackoverflow.com](http://stackoverflow.com/questions/34204623/obsolete-attribute-on-awaitables-type-getawaiter-method-is-a-breaking-change) without getting any response, therefore I thought this might be a better place to ask._

I have implemented my own awaitable type by providing the following four instance members:
`public bool IsCompleted { get; }`
`public void OnCompleted(Action continuation);`
`public AwaitResult GetResult();`
`public object GetAwaiter();`

Because that was all the compiler was asking me for in order to accept
`MyAwaitableType obj = new MyAwaitableType();`
`await obj;`

I marked all of them with 
`[Obsolete("Do not use in code.", true)]`

so that whenever any of the members is called from code instead of using await it results in a build error. Using the Obsolete-Attribute in this scenario is not the way it is intended for – yet I don't know any better way (anxious to hear a better solution if there is one), but it worked fine with the C# compiler included in Visual Studio 2012.

I opened the solution unchanged in Visual Studio 2015 and it seems that the C# compiler got a bit pickier because it complains about the obsoleteness of the GetAwaiter method and shows squiggles underneath the `await obj` statement.

Getting rid of the error is easy, however I would love to know why the compilers seems to access the GetAwaiter method now in a regular manner compared to what it did in Visual Studio 2012 (possibly over reflection?). My understanding is that whether a type is awaitable is a pattern-matching-based (the four required members exist or not) and not an interface-implemented-based issue.

**Comment by HaloFour** [comment] 2016-05-17 11:11
You could use the following to hide the method from Intellisense:

```cs
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
```

Doesn't prevent the method from being explicitly called, but at least should help keep developers from accidentally calling it.  Not that there's is anything dangerous about calling into the awaitable pattern directly.

As for `ObsoleteAttribute`, the team has generally avoided adding new warning/error scenarios so this is probably a regression.  But I'll let them speak to that and as to whether the behavior will be changed.

**Comment by ljw1004** [comment] 2016-05-26 17:34
I think this is "by design".

@gh3x78E, the instance methods you listed are correct but it's important to put them in the right place:
```csharp
class MyAwaitable
{
    public MyAwaiterType GetAwaiter();
}

class MyAwaiterType
{
    public bool IsCompleted { get; }
    public void OnCompleted(Action continuation);
    public AwaitResult GetResult();
}
```

Those for methods are what allow someone to await something:
```csharp
var x = await GetMyAwaitable();
```

But consider what happens to folks who wish to invoke GetMyAwaitable but are in a *synchronous* context? The standard pattern is for them to invoke GetAwaiter manually:
```csharp
static void Main()
{
   MainAsync().GetAwaiter().GetResult();
}

static async Task MainAsync()
{
   ...
}
```

You should leave your GetAwaiter non-obsoleted in order to support this scenario.


(Also: I think it's good that it's now possible to obsolete the awaitability of something! If you have a type, and it used to be awaitable before, but you no longer want folks to await it, then you'd want to put an [Obsolete] attribute on it and have this attribute be reported.)

**Comment by gh3x78E** [comment] 2016-06-13 12:25
@ljw1004 I understand that my placement of the Obsolete-Attribute is something I should really reconsider. Thank you for the explanation.

**Comment by jaredpar** [comment] 2016-07-21 17:19
Closing per @ljw1004 explanation.

**Closed by jaredpar** 2016-07-21 17:19 UTC
Labels: Area-Compilers, Bug, Question, Tenet-Compatibility
