### ISSUE TITLE
Extract method should extract into local function

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#18239] opened 2017-03-28 07:59 UTC
**Version Used**: 
Visual Studio/15.0.0-RTW+26228.4

**Steps to Reproduce**:
See Actual behavior.

**Expected Behavior**:
Extract method refactoring should extract into local function if selection contains local function invocations.

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/9047283/24394624/f4c9c8e4-139c-11e7-90e7-f4e576bd030f.png)

**Comment by Pilchie** [comment] 2017-03-29 02:07
Duplicate of https://github.com/dotnet/roslyn/issues/16288.

**Comment by Pilchie** [comment] 2017-03-29 02:08
Oh, I see that this is a little different - this is when the selection contains a reference to another local function...

**Comment by cartermp** [comment] 2019-09-17 20:58
Ran into this one today.

![image](https://user-images.githubusercontent.com/6309070/65079024-22bf8300-d953-11e9-883b-6a1635f49208.png)

Then:

![image](https://user-images.githubusercontent.com/6309070/65079055-2eab4500-d953-11e9-8f68-804575762d48.png)

**Comment by CyrusNajmabadi** [comment] 2020-03-02 06:32
This is hte current behavior now:

![image](https://user-images.githubusercontent.com/4564579/75651071-7d505100-5c0c-11ea-87dd-9e4dc48bc326.png)

**Closed by CyrusNajmabadi** 2020-03-02 06:32 UTC
Labels: Area-IDE, Bug
