### ISSUE TITLE
NFW in introduce variable. top 2 from 15.9

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35352] opened 2019-04-29 22:56 UTC
```
Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32,Int32)
Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.GetExpressionUnderSpan(SyntaxTree,TextSpan,CancellationToken)
Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.TryInitialize(TextSpan,CancellationToken)
Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.Generate(TService,SemanticDocument,TextSpan,CancellationToken)
Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.<IntroduceVariableAsync>d__17.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.CodeAnalysis.CodeRefactorings.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.<ComputeRefactoringsAsync>d__0.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext()
```

...

https://features.vsdata.io/investigatefault?mt=MAC_ADDRESS_HASHES&et=FAULT&sd=2019-03-29&ed=2019-04-28&pn=vs&fn=ide/vbcs/nonfatalwatson&en=nonfatalwatson&fh=bcfbe09d-ba6b-44c6-a257-e56ab226236d&bl=d15.9$15.9.28307.586$15.9.11$visualstudio.15.release&bl=d15.9$15.9.28307.557$15.9.10$visualstudio.15.release&bl=d15.9$15.9.28307.518$15.9.9$visualstudio.15.release&bl=d15.9$15.9.28307.481$15.9.8$visualstudio.15.release&bl=d15.9$15.9.28307.423$15.9.7$visualstudio.15.release&bl=d15.9$15.9.28307.344$15.9.6$visualstudio.15.release&bl=d15.9$15.9.28307.280$15.9.5$visualstudio.15.release&bl=d15.9$15.9.28307.222$15.9.4$visualstudio.15.release&bl=d15.9$15.9.28307.145$15.9.3$visualstudio.15.release&bl=d15.9$15.9.28307.108$15.9.2$visualstudio.15.release&bl=d15.9$15.9.28307.105$15.9.1$visualstudio.15.release&bl=d15.9$15.9.28307.53$15.9.0$visualstudio.15.release&ex=devenv&ut=external

https://watsonportal.microsoft.com/CabSearch?DateTimeFormat=UTC&MaxRows=100&P3=vs.ide.vbcs.nonfatalwatson&P4=system.argumentoutofrange&P5=microsoft.codeanalysis&P6=microsoft.codeanalysis.text.textspan.frombounds

cab 
https://watsonportal.microsoft.com/Failure?FailureSearchText=b7f0dd5d-567e-45cb-6ee4-8cec0becc658#

**Comment by jinujoseph** [comment] 2019-06-13 21:13
looks like dupe of https://github.com/dotnet/roslyn/issues/27949

**Closed by jinujoseph** 2019-06-13 21:13 UTC
Labels: Area-IDE, Bug
