### ISSUE TITLE
Compiler warns about using not-null `string` in `ValueTuple` declared as `string?` in `switch` statement

### ISSUE THREAD

**Issue by las-nsc** [dotnet/roslyn#61487] opened 2022-05-24 17:44 UTC
**Version Used**: 
LangVersion 10, VS2022 17.2.0

**Steps to Reproduce**:
```
public static (string? token, int index)[] GetTokens(string? value, int defaultIndex) => value?.Split(',') switch
{
    null => new[] { (null, defaultIndex) },
    { Length: 1 } => new[] { (value, defaultIndex) },
    { } multiple => multiple.Select((id, idx) => (id, idx)).ToArray(),
};
```

**Expected Behavior**:
Compiles without warnings.

**Actual Behavior**:
Doesn't compile, and has warnings.

Error: 
`CS0826` `No best type found for implicitly-typed array`
Reason: Can't work out `ValueTuple` type from `return` type in `null` case
Workaround: Cast `null` to `string?`

Warnings: 
`CS8619` `Nullability of reference types in value of type '(string, int)[]' doesn't match target type '(string?, int)[]'.`
Reason: Using a not-null `string` for a `string?` tuple in Single and Multiple cases
Workaround: Dammit operators at the end of those cases. 

I acknowledge that the Error is less likely to get fixed, and isn't the main point of this issue, but I find it annoyingly inconsistent that it can work out the tuple type to cause a warning, but it can't do the same for the implicit type. Separate issue at https://github.com/dotnet/csharplang/discussions/6175

Apologies if issues already exist for this, I did a search but nothing obviously related appeared.

Minimal reproduction: [NRT-Tuple-Bug.zip](https://github.com/dotnet/roslyn/files/8764988/NRT-Tuple-Bug.zip)

**Comment by Neme12** [comment] 2022-05-25 20:28
This seems like by design. `new[]` only considers the types of the elements in the array, not the target type, so when you just put `null` in the tuple, it has no idea what the type is supposed to be - it could be anything. Same with the warnings as well. In the first warning, `value` is considered not null at that point because the only way you could get to that point is if the `Split` method was called, which happens only when `value` is not null. With the second warning, `id` is considered non-null because `Split` returns an array of non-nullable strings.

**Comment by CyrusNajmabadi** [comment] 2022-05-26 16:54
> It would be nice if new[] could consider the target type if there is one rather than trying to determine the type based on the content (since that is far more likely to be what the programmer wants).

We cannot do that as that would be a large breaking change.

> The main point is, surely ValueTuple<string, int>[] could be 'cast' (interpreted) as ValueTuple<string?, int>[] with no problem, because it has become more nullable? 

This is not safe, and so it must be an explicit cast.  Consider the following:

```c#
ValueTuple<string, int>[] array = ...;
ValueTuple<string?, int>[] nullableArray = array;
nullableArray[0] = (null, 0);
```

Now you've just place a 'null' into 'array' unsafely.  The reverse is also unsafe.

**Comment by Neme12** [comment] 2022-05-26 16:59
> _It would be nice_ if `new[]` could consider the target type if there is one rather than trying to determine the type based on the content (since that is far more likely to be what the programmer wants).

Sure, it would be nice, but that's not how the language works. `new[]` has always only considered the types of values *within*. The compiler behaves correctly there. If you'd like to discuss or propose new or enhanced language features, https://github.com/dotnet/csharplang is the right place. Target type new (`new()`) works based on the target type and could be useful here, but unfortunately it's not allowed for arrays.

> The main point is, surely `ValueTuple<string, int>[]` could be 'cast' (interpreted) as `ValueTuple<string?, int>[]` with no problem, because it has become _more_ nullable? It not going the other way is perfectly sensible.

I understand that the warnings annoying in this case and that the proper fix for this (casting both `value` and `id` to `string?`) feels like you just have to do that to silence the compiler because it doesn't understand something, but again, this is how the language currently works.

Also, note that converting `ValueTuple<string, int>[]` to `ValueTuple<string?, int>[]` *could* be a problem - the fact that it is more nullable (basically upcasting) doesn't mean that it will be fine in all cases. Consider code like this:

```c#
using System;

var array = new (string s, int i)[]
{
    ("hello", 1),
};

var castedArray = ((string? s, int i)[])array!;

castedArray[0] = (null, 1);

// Hm, not I added null to the same array where the tuple item was supposed to be non nullable - if I do array[0].s,
// it returns null, even though the type says that it's not nullable.
Console.WriteLine(array[0].s is null);
```

This wouldn't be a problem if you had something like an immutable array or `IEnumerable` instead - in that case, you wouldn't get a warning because `IEnumerable` is covariant - it's declared as `IEnumerable<out T>`, which means that you can do conversions to a less derived type.

Arrays are actually special cased to be covariant too in the runtime - this was a decision in .NET Framework before generics and custom covariance even existed. So C# could certainly allow you to do nullability changes like this in arrays if the language was changed. But most people now think that array covariance was a mistake - it introduced a whole lot of problems, and an example similar to what I showed above would blow up at runtime if it was converted to an actual base type array, not just a nullability difference, which doesn't exist at runtime.

**Comment by las-nsc** [comment] 2022-05-26 17:31
I see your point with your example, that since they're not readonly, after casting it would allow you to misuse it. I did try with `IEnumerable<T>` but that doesn't work either, I guess it makes sense because the items are not readonly, only the overall array/list/whatever structure.

Regarding the type inference, it _does_ work very similarly for `new()`, so I'm just a little surprised that this isn't supported. I guess it's similar to how constructor generic inferrence isn't supported?

**Comment by Neme12** [comment] 2022-05-26 17:35
> Regarding the type inference, it _does_ work very similarly for `new()`

No, it doesn't, that's the point. `new[]` only considers the types of things you add inside `{ }`, whereas `new()` only considers the type of variable you're it passing it to. It's basically the opposite. That's why you can use `var` with `new[]`, but not with `new()`.

**Comment by las-nsc** [comment] 2022-05-26 17:42
That's my point though, it could be using the target type that is arguably more useful, which is something the language does do, just not for arrays currently. I know it doesn't do it that way now, otherwise I wouldn't be bringing it up!

After thinking a bit futher I came up with a moderately better way of writing the code:
```
... => (string?[]?)value?.Split(',') switch
{
    null => new[] { (default(string), defaultIndex) },
    { Length: 1 } single => new[] { (single[0], defaultIndex) },
    { } multiple => multiple.Select((id, idx) => (id, idx)).ToArray(),
};
```

**Comment by Neme12** [comment] 2022-05-26 18:09
> That's my point though, it could be using the target type that is arguably more useful, which is something the language does do, just not for arrays currently. I know it doesn't do it that way now, otherwise I wouldn't be bringing it up!

This is a repo for the compiler though, not for discussing the language itself. If the compiler behaves correctly according to the language spec, there's no issue here. For discussing and proposing changes to the language, the right place is https://github.com/dotnet/csharplang.

**Comment by las-nsc** [comment] 2022-05-27 08:57
https://github.com/dotnet/csharplang/discussions/6175

**Comment by Neme12** [comment] 2022-05-27 16:52
I think someone from the compiler should still confirm that there's no bug here though. I'm not an expert and definitely don't know all the intricacies of nullable.

**Comment by jaredpar** [comment] 2022-08-15 16:52
Yes this is by design.

**Closed by jaredpar** 2022-08-15 16:52 UTC
Labels: Area-Compilers, untriaged
