### ISSUE TITLE
Script generation slows down after many compilation/execution cycles

### ISSUE THREAD

**Issue by Ablu** [dotnet/roslyn#33380] opened 2019-02-14 08:43 UTC
**Version Used**: 2.10.0 / master

**Steps to Reproduce**:

Tested with .NET Framework 4.7.2

*Example Program:*
``` csharp
            var watch = new Stopwatch();
            watch.Start();
            for (int i = 0; i < 5000; ++i)
            {
                var script = CSharpScript.Create<int>("1", ScriptOptions.Default);
                int foo = script.RunAsync().Result.ReturnValue;
                if (i % 250 == 0)
                {
                    watch.Stop();
                    Console.WriteLine(watch.ElapsedMilliseconds);
                    watch.Restart();
                }
            }
```

**Expected Behavior**:

Compilation time stays within a certain border, outputted numbers do not increase.

**Actual Behavior**:

Compilation time keeps increasing

Output of program:

```
1263
2435
2487
2509
2615
2665
2684
2711
2774
2824
2932
2971
3016
3046
3105
3172
3229
3374
3434
3410
```

**Comment by sharwell** [comment] 2019-02-14 11:52
Duplicate of #10164

**Comment by sharwell** [comment] 2019-02-14 11:52
I profiled the scenario described above and verified that the increase in time directly corresponds to additional time spent in the assembly loader as the number of loaded assemblies continues to grow.

**Closed by sharwell** 2019-02-14 11:52 UTC
Labels: Area-Interactive, Bug, Interactive-ScriptingLogic

**Comment by Ablu** [comment] 2019-02-14 12:24
We have been aware of the memory "leak" related to loading assemblies. However, we do not understand why doing repetitive compilations grow in runtime. Why does it have to load an increased number of assemblies in each step? I would have assumed that the number of loaded / generated assemblies is constant for each run. So (just out of interest), why does the assembly loader need more time if the number of already loaded assemblies is higher?

**Comment by sharwell** [comment] 2019-02-14 13:03
@Ablu The number of assemblies per iteration remains the same, but the time it takes to load a single assembly grows.

**Comment by Ablu** [comment] 2019-02-14 13:09
> @Ablu The number of assemblies per iteration remains the same, but the time it takes to load a single assembly grows.

@sharwell is that a .NET Framework restriction, or due to a design decision in Roslyn? Because we used a Mono compiler service based solution in the past, which did not seem to suffer from the increased load time (at least not at this level). The memory leak was the same there of course.

**Comment by sharwell** [comment] 2019-02-14 13:11
My measurements were showing the time increase deep inside the .NET Framework assembly loader. If you were able to reproduce the same issue in .NET Core, the best place to file a bug would be [dotnet/coreclr](https://github.com/dotnet/coreclr).

**Comment by Ablu** [comment] 2019-02-14 13:16
Ok. Thanks for the input! Indeed we did not observe the same behaviour in .NET Core (while the general script performance seems to be worse, the execution time stayed constant there).

I will try to see what Mono does different here. I will report once I found anything!

**Comment by sharwell** [comment] 2019-02-14 13:17
> (while the general script performance seems to be worse, the execution time stayed constant there).

I was just coming back to say this was my exact observation! 😄

**Comment by sharwell** [comment] 2019-02-14 13:24
@Ablu The slow script execution on .NET Core is an issue with Roslyn. Can you open a new issue for that and I'll add the details?

**Comment by Ablu** [comment] 2019-02-14 13:27
I can do that, however, I am currently not at my work computer (where I have the examples and numbers ready). I can open the issue on monday!

**Comment by Ablu** [comment] 2019-02-18 10:20
Just adding the results of my research:

Mono (MCS) seems to directly emit (using `System.Reflection.Emit`) assemblies rather than generating a `byte[]` which is then loaded using `Assembly.Load`.

For Roslyn this seems to be out-of-scope: #10881
