### ISSUE TITLE
Bad IL format from Memory Stream

### ISSUE THREAD

**Issue by scalablecory** [dotnet/roslyn#39390] opened 2019-10-18 18:24 UTC
_From @lpeixotoo on Friday, October 18, 2019 12:51:39 AM_

# Bad IL format from Memory Stream

Hello guys,

I'm trying to run a basic compilation sample by 

- Compiling a source code;
- Emiting it into a memory stream;
- Loading and Invoking;

using a docker environment with:

- NET Core SDK (reflecting any global.json):
  Version:   3.0.100
 Commit:    04339c3a26
- Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

# General

I've based myself in this [article](https://joshvarty.com/2016/01/16/learn-roslyn-now-part-16-the-emit-api/).

A reproducible repository can be found [here](https://github.com/lpeixotoo/assembly-core).

## Sample Code

For a quick follow up, here's my code

```c#
using System;
using System.IO;                           
using System.Reflection;                   
using Microsoft.CodeAnalysis;              
using Microsoft.CodeAnalysis.CSharp;       
using Xunit;

namespace DotNetLib                        
{                                          
    public  class Lib                
    {                                      
                                           
        [Fact]                                   
        public int Compile()
        {                                  

           var tree = CSharpSyntaxTree.ParseText(@"
           using System;
           public class MyClass
           {
               public static void Main()
               {
                   Console.WriteLine(""Hello World!"");
               }
           }");
           
           var mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
           var compilation = CSharpCompilation.Create("MyCompilation",
               syntaxTrees: new[] { tree }, references: new[] { mscorlib });
           
           //Emit to stream
           var ms = new MemoryStream();
           var emitResult = compilation.Emit(ms);

           //Load into currently running assembly. Normally we'd probably
           //want to do this in an AppDomain
           var ourAssembly = Assembly.Load(ms.GetBuffer());
           var type = ourAssembly.GetType("MyClass");
           
           //Invokes our main method and writes "Hello World" :)
           type.InvokeMember("Main", BindingFlags.Default | BindingFlags.InvokeMethod, null, null, null);
 	       return 0;                          
        }
    }                                      
}

```

Am i doing something wrong?

_Copied from original issue: dotnet/core#3654_

**Comment by scalablecory** [comment] 2019-10-18 18:24
_From @vcsjones on Friday, October 18, 2019 1:32:29 PM_

I don't know much about Roslyn, but the use of `GetBuffer` on `MemoryStream` is usually suspicious to me. This returns the internal buffer of the memory stream, which may (probably) contains unwritten garbage data at the end. 

Try using `ToArray()` instead of `GetBuffer()` on your memory stream.

**Comment by scalablecory** [comment] 2019-10-18 18:24
_From @lpeixotoo on Friday, October 18, 2019 1:37:34 PM_

@vcsjones 

I've used `ToArray()` for Assembly loading, the error still persists. I've tried to set the memory stream to the beginning also. Same error.

**Comment by scalablecory** [comment] 2019-10-18 18:24
_From @lpeixotoo on Friday, October 18, 2019 3:01:47 PM_

It happens specifically when `Console.Writeline` are in "to-be-compiled" code.

**Comment by sharwell** [comment] 2019-10-23 19:55
Duplicate of #39470

**Closed by sharwell** 2019-10-23 19:55 UTC
Labels: Area-IDE, Bug
