### ISSUE TITLE
When starting VS I get error below, with no solution file.

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5061] opened 2015-09-07 23:27 UTC
I have tried repairing Visual Studio from "Add Remove Programs" and disabling most extensions.

![image](https://cloud.githubusercontent.com/assets/12789369/9723736/3e2c5946-557d-11e5-8f7a-1503c5f16361.png)

![image](https://cloud.githubusercontent.com/assets/12789369/9723723/15a0f568-557d-11e5-83ec-1624ddf8c4a9.png)

Plus when I do load a solution I can't click on the Errors Window without all of Visual Studio just crashing and wanting to restart.

**Comment by Pilchie** [comment] 2015-09-08 21:16
@markw-t @olegtk Is this something you guys should look at?

**Comment by olegtk** [comment] 2015-09-08 21:56
That reminds me this bug (which we fixed in VS 2015 and VS2013 Update5): https://connect.microsoft.com/VisualStudio/feedback/details/1171345/exception-when-opening-editor 

@paul1956 which VS version do you have installed?

**Comment by paul1956** [comment] 2015-09-08 22:12
Release 2015 enterprise, I have uninstalled, reinstalled. It also fails in /safemode and with /resetsettings and /resetuserdata. This started after opening new VB project that includes Analyzer and Diagnostic with NuGet and VSIX. Now no project works. The error details is the same as shown by @Olegtk

**Comment by olegtk** [comment] 2015-09-08 22:20
@paul1956 can you please try cleaning up your %temp% folder? The issue is essentially that when you have too many temp files, Path.GetTempFileName() fails.

**Comment by paul1956** [comment] 2015-09-08 23:17
Seems like visual Studio could have output a better error message so we don't have to waste days thinking we did something wrong. The message is about extensions. I will try deleting temp files tonight.

**Comment by olegtk** [comment] 2015-09-09 00:07
Yeah, I wish Path.GetTempFileName() would provide a better error message when it fails. 

But in VS, you shouldn't ever see this error at all. It's a bug, which was fixed in VS2013 Update5, but unfortunately the fix didn't make it into VS2015. We will fix it in VS2015 Update1. Thanks for reporting it, @paul1956!

**Comment by paul1956** [comment] 2015-09-09 03:35
https://connect.microsoft.com/VisualStudio/feedback/details/1171345/exception-when-opening-editor  claims it is fixed in VS 2015 and Microsoft Customer Support does not seem to know about this issue, they recommend the steps I tried above. Now I am trying to get my IDE environment back to where I was before resetting and uninstalling everything.

**Closed** 2015-09-09 03:35 UTC
Labels: Area-External

**Comment by markw-t** [comment] 2015-09-10 01:05
@paul1956 thanks for pointing the problem with the Connect item out; I'll correct that. We believed that the issue had been resolved but as @olegtk points out the fix did not make it into VS2015 RTM. It will be in Update 1. Did deleting the temp files work for you as a workaround meanwhile?

**Comment by paul1956** [comment] 2015-09-10 03:27
Deleting all the tmp files allowed me to continue to work with VS 2015. But something really needs to be done about the message below (from VS 2013, VS 2015 gives identical message with 12 replaced by 14). VS know exactly what extension is causing the error when it is an extension, asking me to search an XML file and trying to figure which Extension is misbehaving is a huge waste of time, as is disabling each extensions until the message goes away. And in the case of this issue, a red hearing, since the issue has nothing to do with any extension. Also the Microsoft support utilities to collect VS and OS logs also relies on creating a temporary file so also crash when the temp directory runs out of numbers. As you move more and more of Visual Studio to Extensions this problem gets worse, plus even today there are a lot of extensions and can't coexist with other one so not only do I need to figure out which one caused this issue, I then need to find the conflicting one as well.

![image](https://cloud.githubusercontent.com/assets/12789369/9779396/ea8e4024-572f-11e5-9ea6-3f169ed78156.png)

**Comment by dhusemann** [comment] 2015-09-10 03:50
Will plus on @paul1956 request have spent the last 3 days chasing the same thing.
