### ISSUE TITLE
VB compiler crash: IndexOutOfRangeException in SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#11098] opened 2016-05-05 20:14 UTC
Build 60325 from stabilization branch

Crash dump:
%internal_share%\public\tomat\Bugs\11098

VS crashed when opening Roslyn.sln with some unrestored packages and a lot of errors in task list.

Stack:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 2249
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\BaseTypeAnalysis.vb:line 226
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\BaseTypeAnalysis.vb:line 235
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\BaseTypeAnalysis.vb:line 94
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceNamedTypeSymbol.vb:line 1359
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics() in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\NamedTypeSymbol.vb:line 858
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceNamedTypeSymbol.vb:line 1506
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\TypeSymbol.vb:line 393
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Lookup.vb:line 702
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Lookup.vb:line 578
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Lookup.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\NamedTypeBinder.vb:line 77
   at Microsoft.CodeAnalysis.VisualBasic.Binder.Lookup(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder.vb:line 153
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupBasicName(LookupResult lookupResult, IdentifierNameSyntax basicNameSyntax, Binder binder, DiagnosticBag diagBag, Boolean& reportedAnError) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Symbols.vb:line 867
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupTypeOrNamespaceSyntax(LookupResult lookupResult, TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean& reportedAnError, Boolean unwrapAliases, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Symbols.vb:line 640
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Symbols.vb:line 334
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeFieldType(ModifiedIdentifierSyntax modifiedIdentifierSyntax, Binder binder, DiagnosticBag diagnostics, Boolean isConst, Boolean isWithEvents, Boolean ignoreTypeSyntaxDiagnostics) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberFieldSymbol.vb:line 153
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.GetDeclaredType(DiagnosticBag diagBag) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberFieldSymbol.vb:line 96
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeType(DiagnosticBag diagBag) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberFieldSymbol.vb:line 75
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.get_Type() in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberFieldSymbol.vb:line 62
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFieldSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceFieldSymbol.vb:line 52
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 294
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceNamedTypeSymbol.vb:line 102
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 281
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-0._Lambda$__1(NamespaceOrTypeSymbol typeOrNamespace) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 638
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.VisitTypesAndNamespacesWithin(NamespaceOrTypeSymbol ns, Action`1 visitor, ConcurrentStack`1 tasks, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 698
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetAllDeclarationErrors(CancellationToken cancellationToken, Boolean& hasExtensionMethods) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 633
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.GetAllDeclarationErrors(CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceAssemblySymbol.vb:line 1138
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1926
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 2209
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1350
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1714
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1543
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1484
   at Microsoft.CodeAnalysis.MetadataOnlyImage.Create(ITemporaryStorageService service, Compilation compilation, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\MetadataOnlyImage.cs:line 41
   at Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(Solution solution, ProjectReference projectReference, Compilation finalCompilation, VersionStamp version, CancellationToken cancellationToken) in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\MetadataOnlyReference.cs:line 80
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<GetMetadataOnlyImageReferenceAsync>d__34.MoveNext() in F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.CompilationTracker.cs:line 776
```

**Comment by jaredpar** [comment] 2016-05-17 13:45
@TyOverby believe this is a bug that you already fixed.  Can you take a look and dupe as appropriate.

**Comment by TyOverby** [comment] 2016-05-17 16:45
Duplicate of https://github.com/dotnet/roslyn/issues/10211

Fixed in https://github.com/dotnet/roslyn/pull/10331

**Closed by TyOverby** 2016-05-17 16:45 UTC
Labels: Area-Compilers, Bug
