### ISSUE TITLE
Syntax walker doesn't visit using directives in the middle and at the end of the script

### ISSUE THREAD

**Issue by cfgj** [dotnet/roslyn#16452] opened 2017-01-12 00:27 UTC
**Version Used**:  Microsoft.CodeAnalysis.CSharp.Scripting 2.0.0-rc2

**Code**:
```cs
public class CustomWalker : CSharpSyntaxWalker
{
    public override void Visit(SyntaxNode node)
    {
        Console.WriteLine(node.Kind());
        base.Visit(node);
    }
}

var options = new CSharpParseOptions(LanguageVersion.CSharp6, DocumentationMode.Parse, SourceCodeKind.Script, null);
var tree = CSharpSyntaxTree.ParseText(@"
    using System.Text;
    using System;
    var a = 1;
    using System.Collections.Generic;", options);

new CustomWalker().Visit(tree.GetRoot());
```
**Expected Behavior**: using directive visited thrice.
**Actual Behavior**: using directive visited twice. Why?

**Comment by gafter** [comment] 2017-01-12 01:10
I suggest checking the syntax errors on the tree to see what the problem is.

**Comment by CyrusNajmabadi** [comment] 2017-01-12 01:49
These 'usings' are likely attached as skipped tokens.  It's not legal or representable with our current syntactic model.

**Comment by cfgj** [comment] 2017-01-12 11:42
My bad ( : I got this error: `CS1529 A using clause must precede all other elements defined in the namespace except extern alias declarations`. I thought that usings at the end of script are legal in script mode. Thanks for help.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 21:31
Closing out as this is working as intended.

**Closed by CyrusNajmabadi** 2022-10-28 21:31 UTC
Labels: Area-Interactive
