### ISSUE TITLE
Problem with {} brackets not linking up properly.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59951] opened 2022-03-04 20:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-with--brackets-not-linking-up-/1683182)._

---
[severity:It's more difficult to complete my work]

![Bc5a96282500c44009d6602523e7216b7637819286958625329_20220303-082455-image](https://user-images.githubusercontent.com/1408396/157516840-03aca880-327d-45a1-b7ec-28ea2e071d55.png)

Bracket #1 is linking up with bracket #3 when it should be bracket #1 with #4 and bracket #2 with #3.
Everything I do does not solve the problem and sending the code to someone else and running it on their computer works perfectly fine. I have uninstalled and reinstalled many times but for whatever reason it never works.

Here is image of full code:

![B32ab828c9354426b80c6a5887ba47862637819290581149719_20220303-083055-image](https://user-images.githubusercontent.com/1408396/157516900-bb3c1ddc-c712-4789-971b-66ed31380860.png)

---
#### Feedback Bot on 3/3/2022, 10:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2022-03-09 19:29
I'm guessing this issue is caused by the following invalid `;`:
![image](https://user-images.githubusercontent.com/1408396/157517049-e5a38b25-5744-47d6-81a9-46d49c7abae7.png)

**Comment by CyrusNajmabadi** [comment] 2024-10-25 05:54
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-25 05:54 UTC
Labels: Bug, Area-IDE, Investigation Required, Developer Community
