### ISSUE TITLE
Binary addition of interpolated strings mangles the string

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/roslyn#55461] opened 2021-08-06 09:49 UTC
**Version Used**: 

.NET `6.0.100-rc.1.21405.1` (`6.0.100-rc.1.21403.66` works fine)

**Steps to Reproduce**:

Test code:

```csharp
using System;

class App {
	public static void Main (string[] args)
	{
		var t = new T ();
		Console.WriteLine (t.A ());
		Console.WriteLine ();
		Console.WriteLine (t.B ());
	}
}

class T {
	public float R0C0 = 1;
	public float R1C0 = 2;
	public float R0C1 = 3;
	public float R1C1 = 4;

	public string A ()
	{
		return
			$"({R0C0}, {R0C1})\n" +
			$"({R1C0}, {R1C1})";
	}

	public string B ()
	{
		return
@$"({R0C0}, {R0C1})
({R1C0}, {R1C1})";
	}
}
```

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

Save & run with `dotnet run`

**Expected Behavior**:

Output should be:

```
(1, 3)
(2, 4)

(1, 3)
(2, 4)

```

The first interpolated string is badly mangled.

**Actual Behavior**:

```
)
3, 1()4, 2(

(1, 3)
(2, 4)
```

This is a regression in this range: https://github.com/dotnet/roslyn/compare/3a06c12480787c39e37354dd5d171fa6d91dece1...38582c4d3f32679e5cc29bf86c4bde012ed2baee

From the PR description, this seems like a likely culprit: https://github.com/dotnet/roslyn/pull/55059

**Comment by Youssef1313** [comment] 2021-08-06 12:44
cc @333fred

**Comment by Youssef1313** [comment] 2021-08-06 12:46
I can't reproduce in `main` branch via [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBUQAQCCADvdQN4UCQ+AzNfsQGw8ALNQCy0GNQAUvAAwBtALrUIyAOYBnAJTtW5NmwBuK6gmoBeajACmAd2oAVKZoDc7DsQCcUhADpaTlzdeL0lAvXcQ3wAhANc9AF8KRMpyGkddDm4AMwAbAHsIUwAlGQBhGXNqYjjM6lyC4uJyysIarjr8wuoS0uJKzjbszsbeysE49nbZOicdIIB2NzYAEgAiSWYemXi4Fh7ieM0AHRhV6mwltY2ipu3dzaaDzVWa5MnuaZjQufD8RdT8FdNmU7nsyk8KNdbjs9o9Di92MlkkA).

**Comment by 333fred** [comment] 2021-08-06 14:05
@jaredpar to assign this out, since I'm on vacation. There's probably an arraybuilder.reverse missing in the local rewriter somewhere.

**Closed** 2021-08-10 18:50 UTC
Labels: Bug, Area-Compilers, New Feature - Interpolated String Improvements

**Comment by jcouv** [comment] 2021-08-10 18:52
Fixed by https://github.com/dotnet/roslyn/pull/55494 in 17.0p4
