### ISSUE TITLE
Partial Classes exhibit strange results in Find All References

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#8450] opened 2016-02-07 01:56 UTC
If you open Find All References on a partial class, it will show identical root nodes for the definitions (without even the filenames), and show all references under the last root.
It doesn't even group references in the same file under that file's node (though I'm not sure if that'd be better).

It should at least show the filenames in the root nodes; I'm not sure if it should show multiple roots at all.
<strike>IIRC, pre-Roslyn VS would show an equivalent listing on F12 (which Roslyn does not do).</strike>

![image](https://cloud.githubusercontent.com/assets/313894/12870458/c8633018-cd13-11e5-80a5-8d0d2b4758ed.png)

**Comment by SLaks** [comment] 2016-02-07 01:58
On further experimentation, Roslyn does skips FSR disambiguation on F12 iff one of the definitions is in `.Designer.cs`

**Comment by SLaks** [comment] 2016-02-07 02:03
Ah; http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Extensibility/Navigation/NavigableItemFactory.cs,32

**Comment by Pilchie** [comment] 2016-02-08 17:16
This is a dupe of #1634

**Closed** 2016-02-08 17:16 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
