### ISSUE TITLE
Extract Method C7 crash

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#30538] opened 2018-10-16 18:04 UTC
Was editing and got:

```
System.InvalidOperationException : Matrix does not contain Key 'C7'.
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

This was in:

![image](https://user-images.githubusercontent.com/4564579/47037248-4a9adb00-d133-11e8-8804-f733ba60b3a2.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-16 18:04
Tagging @heejaechang

**Comment by jinujoseph** [comment] 2018-10-16 19:57
dupe of https://github.com/dotnet/roslyn/issues/29536 ?

**Comment by CyrusNajmabadi** [comment] 2018-10-16 20:03
@jinujoseph Looks like it.  Can there be any movement on this?  It seems to be highly reported by customers (as you've linked to).  What does telemetry say for hits here?

**Comment by heejaechang** [comment] 2018-10-16 23:02
this is a dup

**Closed by heejaechang** 2018-10-16 23:02 UTC
