### ISSUE TITLE
Auto-generated AssemblyInfo files in obj directory should be ignored by analyzers under full solution analysis

### ISSUE THREAD

**Issue by bordecal** [dotnet/roslyn#24976] opened 2018-02-21 15:25 UTC
**Version Used**: 
Visual Studio 2017 Enterprise (15.5.7)

**Steps to Reproduce**:

1. Create a Visual Studio solution with SDK-style C# project(s) that are configured with rule CS8019 enabled.
2. Build the solution without full solution analysis enabled.
3. Enable [full solution analysis](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code).
4. Rebuild the solution.

**Expected Behavior**:
CS8019 violations should not be reported for the generated AssemblyInfo files in the project obj directories at either step 2 or step 4 since the files contain `<auto-generated>` headers.

**Actual Behavior**:
CS8019 violations are reported for the generated AssemblyInfo files in the project obj directories under full solution analysis (step 4).

**Comment by Gav-Brown** [comment] 2018-07-02 19:23
CS8019 violations also appear for all:

1. **WPF .g.cs** files
2. Every project via **...\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs**. 

I'm using VS 15.7.4.

**Comment by jinujoseph** [comment] 2018-07-22 07:47
refer [link](https://developercommunity.visualstudio.com/content/problem/214189/could-not-find-file-tempnnetframework.html)

**Comment by sharwell** [comment] 2018-07-22 15:05
Duplicate of #22579

**Comment by sharwell** [comment] 2018-07-22 15:06
@bordecal @Gav-Brown Note that compiler diagnostics (the ones starting with CS) do not filter by generated files, by design. There is no way to increase the severity of CS8019 without causing problems when you build. We are planning to add a new feature which is *not* CS8019 to provide this analysis in a future release.

**Closed by sharwell** 2018-07-22 15:06 UTC
Labels: Area-Analyzers, Developer Community

**Comment by Gav-Brown** [comment] 2018-07-22 15:12
@sharwell Cheers Sam

**Comment by mkamoski** [comment] 2020-01-13 12:42
This is still a bug in Visual Studio 2019 16.4.2 as of now.

**Comment by sharwell** [comment] 2020-01-13 16:37
@mkamoski I am not aware of a bug in this space. If you are experiencing an issue with this diagnostic, can you file a new issue with the details?
