### ISSUE TITLE
Proposal: Redundant type repetition in comparison expressions

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#4582] opened 2015-08-16 03:14 UTC
A proposal for reducing redundancy in comparison expressions.

```csharp
public enum MyEnum : int
{
	A = 1,
	B = 2,
	C = 3
}

var x = MyEnum.C;

if (x == MyEnum.A || x == MyEnum.B)
```
into

```csharp
if (x == (MyEnum.A || MyEnum.B))

or

if (x == { MyEnum.A || MyEnum.B })

or

if (x == MyEnum.{ A || B })

if ((int)x == { 1 || 2 })

// leave the cast, because the enum is extending int
if (x == { 1 || 2 })

```

**Comment by HaloFour** [comment] 2015-08-16 12:00
Duplicate of #136.

**Comment by biqas** [comment] 2015-08-16 12:04
@HaloFour 
Was not aware of this thx.

**Closed** 2015-08-16 12:18 UTC
