### ISSUE TITLE
Bug in NormalizeWhitespace - doc comments

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#68857] opened 2023-07-02 17:52 UTC
**Version Used**: 

**Steps to Reproduce**:
Execute the following [code](https://dotnetfiddle.net/E3mfvK):

```csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

var tree = ParseSyntaxTree(
"""
	/**
     * <X>
	   </X>
     */
    [XXX]
    partial class SomeClass
    {
        
    }

"""
);

Console.WriteLine(tree.GetRoot().NormalizeWhitespace().ToFullString());
```

**Expected Behavior**:

Some string like:
```csharp
/**
<X></X>
*/
[XXX]
partial class SomeClass
{
    
}
```

**Actual Behavior**:

```csharp
///
/// <X>
///</X>
//////[XXX]
partial class SomeClass
{
}
```

**Comment by bernd5** [comment] 2023-07-05 10:55
Yes, I had already a look in the source.
The current implementation handles only single line doc comments more or less corectly.

The attribute is commented out (or even worse the class/namespace...) for multiline doc comments because the final `DocumentationCommentExterior` is changed to `\\\`.

See: https://github.com/dotnet/roslyn/blob/5a1cc5f83e4baba57f0355a685a5d1f487bfac66/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L1072

Multi line comments doc comments should remain multi line doc comments in my eyes. But I would be okay if not.

I started to fix it - but how to handle "space-only" `DocumentationCommentExterior` e.g. in:

````csharp
/**
    <Z />
*/
```

The syntax tree has the following structure:
```csharp
DocumentationCommentTrivia(
                            SyntaxKind.MultiLineDocumentationCommentTrivia,
                            List<XmlNodeSyntax>(
                                new XmlNodeSyntax[]{
                                    XmlText()
                                    .WithTextTokens(
                                        TokenList(
                                            XmlTextNewLine(
                                                TriviaList(
                                                    DocumentationCommentExterior("/**")),
                                                "\n",
                                                "\n",
                                                TriviaList()))),
                                    XmlNullKeywordElement()
                                    .WithLessThanToken(
                                        Token(
                                            TriviaList(
                                                DocumentationCommentExterior("    ")), // <-- this one?
                                            SyntaxKind.LessThanToken,
                                            TriviaList()))
                                    .WithName(
                                        XmlName(
                                            Identifier("Z"))),
                                    XmlText()
                                    .WithTextTokens(
                                        TokenList(
                                            XmlTextNewLine(
                                                TriviaList(),
                                                "\n",
                                                "\n",
                                                TriviaList())))}))
                        .WithEndOfComment(
                            Token(
                                TriviaList(
                                    DocumentationCommentExterior("*/")),
                                SyntaxKind.EndOfDocumentationCommentToken,
                                TriviaList())))
```

**Comment by jcouv** [comment] 2023-07-05 21:17
Closing as duplicate of https://github.com/dotnet/roslyn/issues/68201 (thanks @svick).  Please add details there if needed. Thanks

**Closed by jcouv** 2023-07-05 21:17 UTC
Labels: Bug, Area-Compilers, untriaged
