### ISSUE TITLE
Avoid initializing fields to `null` in IL

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#35906] opened 2019-05-23 15:11 UTC
The compiler should avoid generating IL for fields that are explicitly initialized to `null`.

This is particularly important for non-nullable fields because it may be necessary to explicitly initialize those fields with `= null!` to suppress the nullable warning. The compiler should not generate extra code for those cases.

```C#
class Program
{
    object Field = null!;
}
```
The IL for `Program..ctor` (from ildasm):
```
  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       15 (0xf)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  ldnull
    IL_0002:  stfld      object Program::Field
    IL_0007:  ldarg.0
    IL_0008:  call       instance void [mscorlib]System.Object::.ctor()
    IL_000d:  nop
    IL_000e:  ret
  }
```

**Comment by jaredpar** [comment] 2021-02-10 00:50
Verified that in HEAD the behavior is the same with or without the `!`. Based on that I'm closing as "By Design". 

The reasoning is from the NRT Spec:

> The postfix ! operator has no runtime effect - it evaluates to the result of the underlying expression. Its only role is to change the null state of the expression to "not null", and to limit warnings given on its use.

Given this should have no runtime effect the code gen should be the same for `= null` or `= null!`. That is the current behavior hence believe we are operating correctly here. 

Good news is that on Release we don't emit the actual `null` assignment :smile:

**Closed by jaredpar** 2021-02-10 00:50 UTC
Labels: Area-Compilers, Area-Language Design, New Language Feature - Nullable Reference Types
