### ISSUE TITLE
cw tab tab shortcut not working for console.writeline in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37049] opened 2019-07-08 19:29 UTC
There are. I can't seem to get cw tab tab to pull up the cw. snippet. The snippet exists in my C # folder (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC#\Snippets\1033\Visual C#) and I am using the C # 2005 keyboard mapping scheme for my VB project. And also installed vs 2015 community to see if it would work there, but nope. Year advice would be appreciated.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/498785/cw-tab-tab-shortcut-not-working-for-consolewriteli.html
VSTS ticketId: 823456_
_These are the original issue comments:_

Visual Studio Feedback System on 3/19/2019, 11:23 PM (110 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2019-07-09 17:58
It appears this snippet doesn't exists for VB.
Adding it is blocked on #31879

**Comment by Nukepayload2** [comment] 2019-07-11 08:25
If you add `cw` as a custom code snippet for VB, and then type "cw{Tab}", the VB text editor will insert "ChrW".

**Comment by VBAndCs** [comment] 2021-12-20 22:21
I added this sneppit and it works fine. it would be helpful if it comes as a part of VS.NET:
```xml
<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
    <CodeSnippet Format="1.0.0">
        <Header>
            <Title>Console.WriteLine</Title>
            <Author>M. Hmdy Ghanem</Author>
		   <Shortcut>?</Shortcut>
        </Header>
        <Snippet>
            <Code Language="VB">
                <![CDATA[Console.WriteLine(]]>
            </Code>
        </Snippet>
    </CodeSnippet>
</CodeSnippets>
```

**Comment by VBAndCs** [comment] 2021-12-20 22:32
@Nukepayload2 
After writing cw, you need to press Esc to dismiss the auto completion list before pressing Tab, otherwise the editor will convert cw to ChrW!
one solution to avoid this, is to change the snippet shortcut to cwl, or any other shortcut that has no corresponding auto-completion word. I go for cw to be the same as C#.

**Comment by VBAndCs** [comment] 2021-12-20 23:38
@sharwell  
It would be better if intellisense can take snippets shortcuts into account, so we don't have to dismiss the auto complition list first.

**Comment by CyrusNajmabadi** [comment] 2021-12-20 23:49
@VBAndCs as discussed offline, we'd likely take a contribution here.

**Comment by sharwell** [comment] 2021-12-21 18:23
> @sharwell It would be better if intellisense can take snippets shortcuts into account, so we don't have to dismiss the auto complition list first.

It already does, as long as you enable VB completion support for snippets:
![image](https://user-images.githubusercontent.com/1408396/146979701-bfb45918-1d05-40b1-8201-0769b52f2d57.png)

**Comment by VBAndCs** [comment] 2021-12-21 19:53
@sharwell 
This is a pleasant surprise. It works fine. Thanks.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:00
Closing as by design.

**Closed by CyrusNajmabadi** 2024-10-22 19:00 UTC
Labels: Area-IDE, Feature Request, Blocked, Developer Community
