### ISSUE TITLE
Refactor: Rename does not rename entries in GlobalSuppresssion file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39833] opened 2019-11-14 22:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/671046/refactor-rename-does-not-rename-entries-in-globals.html)._

---
When using Analyzers and you have opted to suppress errors via the GlobalSuppressions.cs file and you then perform a rename on a file that has been referenced in that file it is not updated. This results in all the suppressed errors returning. You then have to either reapply the suppression (which will cause duplicates) or manually edit the file with the correct names.

---
#### Visual Studio Feedback System on 8/1/2019, 04:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/1/2019, 00:15 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment] 2019-11-14 22:15
I believe this is as per the current design/support - references to symbols from global suppress message attributes are not recognized and/or updated by FAR/Rename. This would require new feature support.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 04:03
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-25 04:03 UTC
Labels: help wanted, Area-IDE, Feature Request, Developer Community, Feature - Rename
