### ISSUE TITLE
Roslyn calls Environment.FailFast rather than throwing exceptions in VS

### ISSUE THREAD

**Issue by GrahamTheCoder** [dotnet/roslyn#41724] opened 2020-02-15 16:10 UTC
**Version Used**: master: dcc7ce3e448eb4f1b84f00e1d87136435f5e048e

**Steps to Reproduce**:
1. Be in the visual studio app domain (or probably anywhere that has run  Microsoft.CodeAnalysis.VisualBasic.CommandLine.Run(...))
2. Call Simplifier.ReduceAsync in a way that will trigger an exception (e.g. the code from https://github.com/dotnet/roslyn/pull/41721)

**Expected Behavior**:
An exception is thrown, catchable by the code calling Simplifier.ReduceAsync
(except perhaps in severe corruption or security scenarios)

**Actual Behavior**:
Process ends due to Environment.FailFast still being hooked up from compiler call.

**Details**:
I'm seeing this within Visual Studio when calling the simplifier from a VS extension. I'm not calling the compiler myself directly, but I assume that Visual Studio is doing so within the same VS process. This surprises me a bit because I thought that the compiler always runs via a separate process, so maybe I'm missing some detail. There is the additional oddity that I can't find an entry in the event log for these cases. The only way I can avoid this is by using a [some horribly brittle reflection](https://github.com/icsharpcode/CodeConverter/blob/26d0623141589ca5460d177bd670b04fd85b8ff2/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L171-L196).

Every time this issue gets mentioned in this repo I could see, someone fixes or gives a workaround for the bug which caused the exception, but not the fundamental problem. This is apparently a [known situation with a big conversation](https://github.com/dotnet/roslyn/issues/19880#issuecomment-305264368) around it, but I just wanted to flag up as its own issue since that comment was nearly 3 years ago.

**Small improvements**
* The easiest improvement for this is to confine the error handler code to the compiler usage (i.e. unregister the handler afterwards). This obviously wouldn't deal well with concurrency.
* Run the simplifiers on some code from a few open source solutions (perhaps even roslyn itself) to discover some of the bugs in them (many of which will currently trigger a VS crash)

**Medium solution**
Start using ExceptionUtilities.Unreachable only for cases where you have some reasoning / solid testing that indicates the code is unreachable.
Introduce `ExceptionUtilties.CatchAll` to distinguish other cases of "hope this doesn't happen".

Then replace all
```csharp
try
{
    ...
}
catch (Exception e) when (FatalError.ReportUnlessCanceled(e))
{
    throw ExceptionUtilities.Unreachable;
}
```

with

```csharp
try
{
    ...
}
catch (Exception e) when (FatalError.ReportWithoutCrashUnlessCanceled(e))
{
    throw ExceptionUtilities.CatchAll;
}
```

**Bigger picture**
Isn't there any library call that could just take a memory dump of the running process (e.g. `dotnet-dump collect --process-id ...`) and report it without exiting the process?

**Comment by jinujoseph** [comment] 2020-02-19 20:16
Duplicate of #32785

**Closed by jinujoseph** 2020-02-19 20:16 UTC
Labels: Area-IDE
