### ISSUE TITLE
'var' preference feedback

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50798] opened 2021-01-26 19:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/var-preference-feedback/1307022)._

---
[severity:It bothers me. A fix would be nice]
I am using the Visual Studio 2019, windows 10. I would like to share some feedbacks on [`var` preferences](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008), and seek any recommendations if you have any.

For `csharp_style_var_for_built_in_types`, I like setting it to `false` for using built-in types like `var x = 5` where the type is clear to developers, but it also allows using `var` for returning built-in type from methods like `var x = this. GetValue()` when `GetValue()` returns a built-in type. It is unclear to determine which built-in type the variable could be in the later case, and the type is often not mentioned in the method names.

Additional, setting `csharp_style_var_when_type_is_apparent` to true doesn't work for casting cases such as `var x = (int)this. GetValue()`. I believe casting does explicitly mentions the type on the right hand side, and should be recognizes as valid cases like `var x = new Customer();` Also, `var a = FileExtension.GetExtension(fileName)` should violate the rule as it is calling the method of `FileExtension`, no type is explicitly mentioned on the right hand side for the method returning type.

---
### Original Comments
(no comments)

**Comment by jinujoseph** [comment] 2021-01-26 21:16
First part is a Duplicate of #23714

**Comment by sharwell** [comment] 2021-01-26 21:19
The second paragraph is partially a duplicate of #47704 and partially a duplicate of #29657.

I recommend following up in the linked issues if there are any additional details you wanted to add. 👍

**Closed by sharwell** 2021-01-26 21:19 UTC
Labels: Area-IDE, Bug, Developer Community

**Comment by CyrusNajmabadi** [comment] 2021-01-27 04:21
> Additional, setting csharp_style_var_when_type_is_apparent to true doesn't work for casting cases such as var x = (int)this. GetValue()

If this is a case, this is bug.  The type should be considered apparent there.
