### ISSUE TITLE
Escape scope analysis won't work with primary constructors

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#68610] opened 2023-06-14 12:25 UTC
**Version Used**: 

main branch

**Steps to Reproduce**:

The following struct compiles fine:
```
public ref struct WithRefField
{
  public readonly ref readonly int X;

  public WithRefField(ref int x)
  {
    X = ref x;
  }
}
```
But it won't compiles in a primary constructor form:
```
public ref struct WithRefField(ref int x)
{
  public readonly ref readonly int X = ref x;
}
```

> Error CS9077 : Cannot return a parameter by reference 'x' through a ref parameter; it can only be returned in a return statement

**Expected Behavior**:

Both forms compile fine

**Comment by AlekseyTs** [comment] 2023-06-16 13:04
Looks like a dupe of #67371.

**Closed as completed by AlekseyTs** 2023-06-16 13:04 UTC
Labels: Bug, Resolution-Duplicate, Area-Compilers, Feature - Primary Constructors
