### ISSUE TITLE
VS2022 Lightbulb configure severity of Analyzer did not change editorconfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57490] opened 2021-10-31 19:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Lightbulb-configure-severity-of-A/1566535)._

---
When I use the lightbulb suggestion to configure the severity of IDE0059 the change was not saved to my editorconfig file.

Steps to reproduce
1. Create a new Console app targeting dotnet 6.0
2. Insert the following lines
```cs
var cat = "foo";
cat = "dog";
```
3. Use the lightbulb suggestion to resolve CS0219 (this is successful and creates and editorconfig file)
4. Use the lightbulb suggestion on the variable `cat` from the line `cat = "dog"` to change the severity of IDE0059 to *warning*
5. Open the `.editorconfig` file and observe that there is only one line in the file

```
dotnet_diagnostic. CS0219.severity = none
```

https://user-images.githubusercontent.com/9797472/139598269-e2cefc60-bfa2-400e-a26f-bf81dce8ed7a.mp4

---
#### Feedback Bot on 10/28/2021, 08:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/29/2021, 10:20 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-11-01 14:55
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/45417

**Closed** 2022-02-25 11:56 UTC
Labels: Bug, Resolution-Duplicate, Area-Analyzers, Developer Community, New Feature - Editor Config
