### ISSUE TITLE
SyntaxTree pattern matching

### ISSUE THREAD

**Issue by exyi** [dotnet/roslyn#7946] opened 2016-01-14 08:08 UTC
I'd like to use something like pattern matching in NRefactory. Is there anything like that? Or any plans for it?

**Comment by Pilchie** [comment] 2016-01-14 17:05
It's not something that we're considering at the moment.  See also issue #6618.

**Comment by CyrusNajmabadi** [comment] 2020-03-14 10:19
Closing out as dupe of https://github.com/dotnet/roslyn/issues/6618

**Closed by CyrusNajmabadi** 2020-03-14 10:20 UTC
Labels: Area-IDE, Concept-API, Feature Request
