### ISSUE TITLE
GetHashCode generator doesn't take into account checked environment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24093] opened 2018-01-08 02:11 UTC
If the compiler needs to &quot;check for arithmetic overflow/underflow&quot;, the GetHashCode code generator should generate code within an &quot;unchecked&quot; scope.

It could even do this independently on the compiler setting, such that the code just keeps working when changing the compiler setting later.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/176727/gethashcode-generator-doesnt-take-into-account-che.html
VSTS ticketId: 546722_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by MaStr11** [comment] 2018-01-09 10:54
This is the method than needs to be changed:
[ICodeDefinitionFactoryExtensions_CreateGetHashCodeMethod.cs](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Shared/Extensions/ICodeDefinitionFactoryExtensions_CreateGetHashCodeMethod.cs#L43)
This method currently doesn't mentions overflows in checked environments at all. @CyrusNajmabadi did most of the changes in commit f6eaea66. He may can answer why that problem wasn't taken into account.  

Albeit there is a problem with VB to consider: It doesn't support checked/unchecked (see the stackoverflow thread [Overriding GetHashCode in VB without checked/unchecked keyword support?](https://stackoverflow.com/questions/4654227/overriding-gethashcode-in-vb-without-checked-unchecked-keyword-support) for details). I think that's also why there aren't any `Checked` or `Unchecked` methods on SyntaxGenerator.

IMHO this is best solved by providing language specific implementations. And I fear that the VB version would be quite different from the C# version and needs to be well designed before it can be implemented here. There are some implementations given in the stackoverflow thread above but some of them can't be used (need an extra struct), are using a long as intermediate value or might be not well balanced.

**Comment by sharwell** [comment] 2018-01-09 15:07
Duplicate of #24035

**Closed by sharwell** 2018-01-09 15:07 UTC
Labels: Area-IDE, Bug, help wanted

**Comment by CyrusNajmabadi** [comment] 2018-01-09 22:19
>  He may can answer why that problem wasn't taken into account.

Simple answer: i didn't think of it :)
