### ISSUE TITLE
Code style:  built-in types rule trumps apparent type rule, when type is not apparent

### ISSUE THREAD

**Issue by dtivel** [dotnet/roslyn#36133] opened 2019-06-03 20:59 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.2.0 Preview 3.0 [29002.38.d16.2stg]
VisualStudio.16.IntPreview/16.2.0-pre.3.0+29002.38.d16.2stg
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA784
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.2.154.3618
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.154.3618
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.154.3618
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.154.3618
Azure Functions and Web Jobs Tools

C# Tools   3.2.0-beta2-19277-03+50ce8972ca70993faaa7c130a19cfd174452ee68
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61905.20080
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10529.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.0-beta2-19277-03+50ce8972ca70993faaa7c130a19cfd174452ee68
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19277.5+42c125e3cbb5cb06256a413c4e742199fb0df1f3
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Steps to Reproduce**:

1.  Use these .editorconfig rules:
```
csharp_style_var_elsewhere = false:warning
csharp_style_var_for_built_in_types = true:warning
csharp_style_var_when_type_is_apparent = true:warning
```
2.  Open this file:
```
using System.Collections.Generic;
using System.Reflection;

class A
{
    internal Dictionary<string, int> B { get; }
}

class C
{
    private void D(A a, PropertyInfo e)
    {
        /*1*/ var f = false;

        foreach (/*2*/ var g in a.B.Keys)
        {
        }

        /*3*/ var h = e.GetValue(this);
    }
}
```

**Expected Behavior**:
`csharp_style_var_when_type_is_apparent` will trump the `csharp_style_var_for_built_in_types` rule.
* /\*1\*/ will not warn, because the type is apparent.
* /\*2\*/ and /\*3\*/ will warn because the types are not apparent.

Irrespective of whether or not a type is built in, the goal is to encourage use of `var` when the type is apparent but encourage use of the explicit type when the type is not apparent.

**Actual Behavior**:
The `csharp_style_var_for_built_in_types` rule trumps the `csharp_style_var_when_type_is_apparent` rule.

No warnings are generated.

**Comment by CyrusNajmabadi** [comment] 2019-06-03 21:16
OMG.  HAI DAMON!

**Comment by CyrusNajmabadi** [comment] 2019-06-03 21:19
> Actual Behavior:
>
> The csharp_style_var_for_built_in_types rule trumps the csharp_style_var_when_type_is_apparent rule.

I believe this is actually considered by design.  As long as it's a built-in type, then 'var' is used, regardless of anything else.   Otherwise, someone would end up with:

```c#
foreach (string g in a.B.Keys)
```

And would say "but... i said i want 'var' for *built-in* types.  WTF!?"

Agreed that this is an area where two rules may be at odds.  But we took teh position (ages) ago that hte 'built-in' rule took precedence.  

Tagging @sharwell just to see if he feels this needs to go to design review.  However, my feeling is that we couldnt' change this behavior now because it would be too destabalizing.  We could *maybe* add a new option though that could encode the behavior you want.

**Comment by dtivel** [comment] 2019-06-03 21:32
Hi, Cyrus.  :)

I think being able to disable the built-in types rule would be ideal, since the goal is to use `var` only when the type is apparent, irrespective of the type being built-in or not.

**Comment by CyrusNajmabadi** [comment] 2019-06-03 21:34
Yeah, that's good feedback. And we could potentially support that with something like `csharp_style_var_for_built_in_types=not_applicable`   or  `csharp_style_var_for_built_in_types=disabled`   or something like that.  To @sharwell for a design meeting to think about an appropriate solution (if one would be provided).  

Thanks!

**Comment by sharwell** [comment] 2019-06-04 12:10
Duplicate of #23714

**Closed by sharwell** 2019-06-04 12:10 UTC

**Comment by CyrusNajmabadi** [comment] 2019-06-04 16:51
@sharwell note that the issue you duped against says it will go to the next design meeteing and will be updated with the results.  However, the results (if this happened) were not posted to the issue.  can you update accordingly?  Thanks!
