### ISSUE TITLE
RequiredAttribute ErrorMessageString Bug

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#54812] opened 2021-07-14 07:49 UTC
**Version Used**: 
Visual Studio 2019; .NET Framework 4.8; C# 8.0;

ErrorMessageString is readonly. So, it should not update value.

And haven't Called error code:
`ErrorMessageString = string.Format(ErrorMessageString, propertyDisplayName);`

Called code:
`ErrorMessage = string.Format(ErrorMessageString, propertyDisplayName);`

Auto update 'ErrorMessageString', why?

Reference:
![image](https://user-images.githubusercontent.com/23723575/125582965-c54fd2c2-fcd9-48ae-8e94-ab06d24b2798.png)

**Comment by jaredpar** [comment] 2021-07-14 16:23
> ErrorMessageString is readonly. So, it should not update value.

The issue is unspecific but I'm assuming that `RequiredAttribute` here is [System.ComponentModel.DataAnnotations.RequiredAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=net-5.0). If so then `ErrorMessage` is not `readonly` but instead a `get only` property. That is indeed updated based on the contents of `ErrorMessage`. as you can see [here](https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/ValidationAttribute.cs,95) 

Closing as this appears to be "by design". Moving to `dotnet/runtime` though as this is a BCL issue, not a C# compiler one.

**Closed by jaredpar** 2021-07-14 16:23 UTC
Labels: Area-Compilers, untriaged
