### ISSUE TITLE
Regex parser produces different messages in .NET 6

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#61232] opened 2022-05-10 23:35 UTC
Tracking issue for TODO and disabled tests in code.

**Comment by CyrusNajmabadi** [comment] 2022-05-11 00:16
Related issue:

https://github.com/dotnet/roslyn/issues/61215

**Comment by CyrusNajmabadi** [comment] 2024-11-22 01:32
Dupe of https://github.com/dotnet/roslyn/issues/61215

**Closed by CyrusNajmabadi** 2024-11-22 01:32 UTC
Labels: Area-IDE, Concept-Design Debt, Disabled Test
