### ISSUE TITLE
Regression? Rename and Anonymous Types

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#17219] opened 2017-02-17 20:47 UTC
VS 2017 RC, Feb 7th update.

Consider this:
```csharp
var x = 42;
return new { x };
```
Answer is, obviously: `{ x = 42 }`.

With 2017 RC, renaming `x` to `y` gives:
```csharp
var y = 42;
return new { y };
```
Answer becomes: `{ y = 42 }`.

The return type has unexpectedly changed.
I seem to recall (am I wrong?) that in VS 2015 the result was:
```csharp
var y = 42;
return new { x = y };
```
Renaming `x` to `y` but keeping the returned shape identical.
The latter behavior seems more correct to me.

**Comment by timopomer** [comment] 2017-02-19 13:19
what is the `new {}` syntax supposed to do? just curious

**Comment by jods4** [comment] 2017-02-19 15:18
@timopomer Creates an [anonymous type](https://msdn.microsoft.com/en-us/library/bb397696.aspx)

**Comment by Pilchie** [comment] 2017-08-07 22:13
Also reported in https://developercommunity.visualstudio.com/content/problem/80546/rename-not-work-if-its-used-by-another-anonymousty.html

**Comment by CyrusNajmabadi** [comment] 2024-11-05 21:14
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-11-05 21:14 UTC
Labels: Bug, Area-IDE, Feature - Rename
