### ISSUE TITLE
NFW while typing in REPL

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6383] opened 2015-10-28 01:29 UTC
Type the following in REPL:

```C#
> #r "C:\Users\{user}\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe"
> using Xunit.ConsoleClient;
> Program.Main("")
```

``` 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.VerifyDiagnostics(Microsoft.CodeAnalysis.SemanticModel model) Line 186	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics.AnonymousMethod__17_3(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver _1, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer _2) Line 153	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateType stateType, bool supportsSemanticInSpan, System.Func<Microsoft.CodeAnalysis.VersionStamp, Microsoft.CodeAnalysis.VersionStamp, bool> versionCheck, System.Func<Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>>> getDiagnostics, Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver analyzerDriverOpt) Line 289	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.VersionStamp textVersion, Microsoft.CodeAnalysis.VersionStamp syntaxVersion, Microsoft.CodeAnalysis.VersionStamp semanticVersion) Line 147	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.VersionStamp textVersion, Microsoft.CodeAnalysis.VersionStamp syntaxVersion, Microsoft.CodeAnalysis.VersionStamp semanticVersion) Line 120	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync() Line 78	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, bool includeSuppressedDiagnostics, System.Threading.CancellationToken cancellationToken) Line 463	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, bool includeSuppressedDiagnostics, System.Threading.CancellationToken cancellationToken) Line 167	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.TryAppendDiagnosticsForSpanAsync.AnonymousMethod__0() Line 137	C#
```

**Comment by tmat** [comment] 2015-10-28 02:10
@cston @ManishJayaswal

**Comment by cston** [comment] 2015-11-02 18:59
Duplicate of #6104.

**Closed** 2015-11-02 19:05 UTC
Labels: Area-Compilers, Area-Interactive, Interactive-Scripting
