### ISSUE TITLE
[Source Generator]: AnalyzerConfigOptions.GetOptions(AdditionalFile) does not work if file path in the project is not-normalized

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#50090] opened 2020-12-21 19:08 UTC
**Version Used**: 
3.9.0-2.20521.12

**Steps to Reproduce**:

1. Checkout this commit: https://github.com/pranavkm/roslyn-sdk/commit/f65237491b7e71e67c66e446e6263e9520991cec
2. Build the GeneratedDemo sample

**Expected Behavior**:
Build should succeed

**Actual Behavior**:
The source generator throws an error because options for `People.csv` file is missing. I suspect it's because the path in the editor config is normalized, but the lookup for the options does is not normalized:

```
[D:/temp/roslyn-sdk/samples/CSharp/SourceGenerators/GeneratedDemo/People.csv]
build_metadata.AdditionalFiles.CsvLoadType = Startup
build_metadata.AdditionalFiles.CacheObject = 
```

vs

`D:\temp\roslyn-sdk\samples\CSharp\SourceGenerators\GeneratedDemo\..\GeneratedDemo\People.csv.`

RazorSDK supports linked files outside the project directory which is how this bug was discovered.

**Comment by chsienki** [comment] 2021-01-14 19:05
This is essentially a dupe of https://github.com/dotnet/roslyn/issues/43371 fixing that will solve this.

**Closed by chsienki** 2021-01-14 19:05 UTC
Labels: Area-Compilers, Bug, New Feature - Source Generators
