### ISSUE TITLE
Getting the semantic model for a document throws AggregateException when a project contains a duplicate reference

### ISSUE THREAD

**Issue by ap0llo** [dotnet/roslyn#14386] opened 2016-10-08 22:35 UTC
**Version Used: 1.3.2**: 

**Steps to Reproduce**:

1. Create a MSBuildWorkspace
2. Open a solution with a project that contains a duplicate project reference (like this one https://gist.github.com/ap0llo/1ae386f85465faa257cc47db9a299c13)
3. Try to get the semantic model for a document 

```
var workspace = MSBuildWorkspace.Create();
var solution = workspace.OpenSolutionAsync(solutionPath).Result;

foreach (var project in solution.Projects)
{
	foreach (var document in project.Documents)
	{
		var semanticModel = document.GetSemanticModelAsync().Result;
	}
}
```

**Expected Behavior**:
I think the duplicate reference should either be ignored (as msbuild does not seem to have a problem with duplicate references) or a more specific exception should be thrown so it can be determined more easily what the problem is

**Actual Behavior**:
An AggregateException wrapping a TaskCanceledException with no inner exception is thrown, which makes finding the error difficult. 
I was able to identify why the task is being canceled. In SolutionState.FinalizeCompilationAsync() an ArgumentException is thrown because a duplicate key is added to the metadataReferenceToProjectId dictionary

**Comment by Pilchie** [comment] 2016-10-10 16:53
Dupe of https://github.com/dotnet/roslyn/issues/12101.

**Closed by Pilchie** 2016-10-10 16:53 UTC
Labels: Area-IDE
