### ISSUE TITLE
snippet not working before "using" statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53917] opened 2021-06-07 16:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/snippet-not-working-before-using-state/1441762)._

---
[severity:It bothers me. A fix would be nice]
Lets say I created a snippet to help me type macro pair. 

```
#if _SOMETHING_

#endif
```

at the top of a c# file.

If the file already has 'using' statement at line 2 and I try to trigger the snippet at line 1, the snippet will failed. 
The hint will always be 'using' or 'extern' even if I type the snippet shortcut in full.  

```
Ln 1.                                    // try to insert snippet here will fail.
Ln 2. using System.IO;

```

---
#### Feedback Bot on 6/6/2021, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2021-06-07 17:24
Yes.  This is by design.  We originally had snippets here, but we got overwhelming feedback that that made the VS experience much worse because people almost never wanted snippets there, but it the clean and simple 'using' list was now cluttered with snippet goop.

**Comment by fantasyz** [comment] 2021-06-07 23:00
I guess I am the 1% that want snippets support here. Can an option be added to turn this logic off? Or add extra property to the snippet definition so that particular snippet can bypass this restriction?

**Comment by CyrusNajmabadi** [comment] 2021-06-07 23:49
>Or add extra property to the snippet definition so that particular snippet can bypass this restriction?

This would be problematic as this would now appear for everyone.

I just checked and even though the `#if` doesn't show up the list, we still support invoking it using `tab`:

![image](https://user-images.githubusercontent.com/4564579/121101230-4c1be480-c7b0-11eb-8cce-6adf8a40078b.png)

So i'd say this is working as intended.  We do not clutter the list with undesired completions.  But you can still invoke it to get the expanded for.

**Comment by CyrusNajmabadi** [comment] 2021-06-07 23:51
Actually, i can't even repro the bug as reported:

![image](https://user-images.githubusercontent.com/4564579/121101325-7a012900-c7b0-11eb-9bb3-62eed23f3bcd.png)

Even though i'm above hte using statements, we properly still give you proper completion here once you type the `#`.   Going to close out unless the steps can be clarified on what the core problem is here.  Thanks!

**Comment by fantasyz** [comment] 2021-06-07 23:53
![ifue test](https://user-images.githubusercontent.com/3223242/121101515-8e840680-c82e-11eb-8938-a16acf4a7538.gif)

**Comment by CyrusNajmabadi** [comment] 2021-06-07 23:57
Can you add `#` to your snippet?

**Comment by fantasyz** [comment] 2021-06-07 23:58
> 
> 
> > Or add extra property to the snippet definition so that particular snippet can bypass this restriction?
> 
> This would be problematic as this would now appear for everyone.

The extra property, say "ignore invoke location", is suppose to be set only for the special snippet like this one I am talking about. By default, other user will not be affected as normal snippet are using the default behavior. Only snippet override this setting could be invoked anywhere.

**Comment by fantasyz** [comment] 2021-06-08 00:03
> 
> 
> Can you add `#` to your snippet?

Although I could add the '#' to the shortcut, even if it work, it can only be considered a workaround.
Snippet is about getting things done in the easiest form and typing the '#' is doubling the effort to invoke the the snippet in this case...

**Comment by CyrusNajmabadi** [comment] 2021-06-08 00:07
Reactivating and placing on backlog.

**Comment by fantasyz** [comment] 2021-06-08 00:09
btw, I think the extra property like "ignore invoke location" is a good addition. It improve flexibility without breaking things. As I observed in the past, "insert before the using statement "it is not the only case snippet not working correctly. Sometimes it is happening somewhere else. I don't remember the exact case but I think I could be trying to insert a fragment of code inside a statement.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 17:25
Closing out as we are not investing in legacy snippet scenarios.

**Closed by CyrusNajmabadi** 2024-10-22 17:25 UTC
Labels: Area-IDE, 0 - Backlog
