### ISSUE TITLE
Smart Variable Naming doesn't suggest names for List<T>

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#19046] opened 2017-04-27 17:07 UTC
![image](https://cloud.githubusercontent.com/assets/1402694/25495142/07515e18-2b31-11e7-9b19-407f004021a1.png)

I would expect it to suggest something like `stops1` (because I already have a local `stops`) or `listOfStops` here. Instead, nothing is suggested.

**Comment by miloush** [comment] 2017-05-02 19:38
Unless I am not getting it from the picture, this looks like a new feature of suggesting variable names?

**Comment by Pilchie** [comment] 2017-05-22 22:06
Dupe of #17987.

**Closed by Pilchie** 2017-05-22 22:06 UTC
Labels: Area-IDE, Bug
