### ISSUE TITLE
Add accessibility modifier quick fix removes extern

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#32138] opened 2019-01-03 22:30 UTC
**Version Used**: VS 2019 Preview 1

**Steps to Reproduce**:

1. Use .editorconfig that requires accessibility modifiers
2. Put this in a class:

```csharp
[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
static extern int GetCurrentPackageFullName(ref int packageFullNameLength, StringBuilder packageFullName);
```

3. Run the quick fix "Add accessibility modifiers"

**Expected Behavior**:
```csharp
[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
private static extern int GetCurrentPackageFullName(ref int packageFullNameLength, StringBuilder packageFullName);
```

**Actual Behavior**:

```csharp
[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
private static int GetCurrentPackageFullName(ref int packageFullNameLength, StringBuilder packageFullName);
```
The `extern` was removed.

**Comment by sharwell** [comment] 2019-01-03 22:36
Duplicate of #29561

**Comment by Neme12** [comment] 2019-01-03 22:36
Duplicate of #29561

**Comment by Neme12** [comment] 2019-01-03 22:37
Damn, @sharwell was 2 seconds earlier :smile:

**Closed** 2019-01-03 22:36 UTC

**Comment by sharwell** [comment] 2019-01-03 22:38
:trollface:
