### ISSUE TITLE
Intermittent test TestGetCodeFixWithExceptionInFixableDiagnosticIds2

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#21533] opened 2017-08-15 22:32 UTC
```
Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.CodeFixServiceTests.TestGetCodeFixWithExceptionInFixableDiagnosticIds2
System.Exception : 1 exception(s) were thrown during test.\r\nNote: exceptions may have been thrown by another test running concurrently with\r\nthis test.  This can happen with any tests that share the same ExportProvider.\r\nExamining individual exception stacks may help reveal the original test and source \r\nof the problem.\r\n\r\nException 0:\r\nSystem.ArgumentException: The specified NormalizedSnapshotSpanCollection extends beyond the end of the TextSnapshot.\r\n   at Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection..ctor(ITextSnapshot snapshot, IList`1 spans)\r\n   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToFirstMatch(SnapshotSpan span, SpanTrackingMode trackingMode, Predicate`1 match)\r\n   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToBuffer(SnapshotSpan span, SpanTrackingMode trackingMode, ITextBuffer targetBuffer)\r\n   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextBuffer targetBuffer)\r\n   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextSnapshot targetSnapshot)\r\n   at Microsoft.VisualStudio.Text.AdornmentLibrary.TextMarkers.Implementation.TextMarkerVisualManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)\r\n   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)\r\n\r\n\r\n---- System.ArgumentException : The specified NormalizedSnapshotSpanCollection extends beyond the end of the TextSnapshot.
   at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
   at Microsoft.CodeAnalysis.Workspace.Dispose()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.CodeFixServiceTests.<GetDefaultFixesAsync>d__6.MoveNext() in C:\Roslyn\src\EditorFeatures\Test\CodeFixes\CodeFixServiceTests.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.CodeFixServiceTests.<TestGetCodeFixWithExceptionInFixableDiagnosticIds2>d__4.MoveNext() in C:\Roslyn\src\EditorFeatures\Test\CodeFixes\CodeFixServiceTests.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection..ctor(ITextSnapshot snapshot, IList`1 spans)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToFirstMatch(SnapshotSpan span, SpanTrackingMode trackingMode, Predicate`1 match)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToBuffer(SnapshotSpan span, SpanTrackingMode trackingMode, ITextBuffer targetBuffer)
   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextBuffer targetBuffer)
   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextSnapshot targetSnapshot)
   at Microsoft.VisualStudio.Text.AdornmentLibrary.TextMarkers.Implementation.TextMarkerVisualManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by Pilchie** [comment] 2017-08-16 17:43
@olegtk @dpugh - have you ever seen this before?

```
  at Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection..ctor(ITextSnapshot snapshot, IList`1 spans)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToFirstMatch(SnapshotSpan span, SpanTrackingMode trackingMode, Predicate`1 match)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToBuffer(SnapshotSpan span, SpanTrackingMode trackingMode, ITextBuffer targetBuffer)
   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextBuffer targetBuffer)
   at Microsoft.VisualStudio.Text.Implementation.MappingSpan.GetSpans(ITextSnapshot targetSnapshot)
   at Microsoft.VisualStudio.Text.AdornmentLibrary.TextMarkers.Implementation.TextMarkerVisualManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by Pilchie** [comment] 2017-08-17 19:05
Duplicate of #20106

**Comment by Pilchie** [comment] 2017-08-17 19:07
Maybe not the same, will leave open for now.

**Comment by jasonmalinowski** [comment] 2022-06-16 19:01
Unable to find any recent failures in runfo; closing this as stale.

**Closed by jasonmalinowski** 2022-06-16 19:01 UTC
Labels: Bug, Area-IDE, Test
