### ISSUE TITLE
with statement

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#7322] opened 2015-12-08 10:05 UTC
Recently I pretty often start seeing patterns like:

``` csharp
class MyClass
{
  public Type1 Field1 { get; set; }
  public Type2 Field2 { get; set; }
  // ...
  public MyClass WithField1(Type1 field1)
  {
    Field1 = field1;
    return this;
  }
  // ...
}
```

This seems pretty weird to repeat yourself million times

Should we provide pascal like operator for this?

``` csharp
class MyClass
{
  public Type1 Field1 { get; set; }
  public Type2 Field2 { get; set; }
}

// somewhere in the code (we do have initializer for the constructor but what later?):
MyClass c = new MyClass();
with (c)
{
   .Field1 = something1;
   .Field2 = something2;
   // ...
}
```

**Comment by GeirGrusom** [comment] 2015-12-08 11:52
var c = new MyClass { Field1 = something1, Field2 = something2 };

Already works, but this obviously doesn't work with immutable types, but I think there already is a issue for that.

**Comment by HaloFour** [comment] 2015-12-08 12:15
Dupe of #133, #951 and #6553 to varying degrees.

The `With*` property pattern is a different beast, though, particularly since it returns a reference to the class to facilitate chaining but it doesn't necessarily return the reference to the current instance, which facilitates incremental building of immutable objects.

**Comment by dsaf** [comment] 2015-12-09 11:26
@GeirGrusom That's right #229.

**Comment by gafter** [comment] 2015-12-15 01:42
Also possibly a dup of #5172

**Comment by gafter** [comment] 2017-03-20 20:04
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Closed by gafter** 2017-03-20 20:04 UTC
Labels: Area-Language Design, Discussion, Resolution-Duplicate
