### ISSUE TITLE
Completion support for conditional constants

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#47328] opened 2020-09-01 06:09 UTC
By default, legacy and SDK-based projects provide "built-in" conditional constants that are given to projects by default. 

In legacy, this was easier to remember as it was "DEBUG" or "RELEASE".
In SDK-based projects, this is much harder to remember as there are more.  For example if you are targeting .NET Framework 4.5, you get: `NETFRAMEWORK`; `NET45`; `DEBUG` (Debug) and `NETFRAMEWORK`; `NET45`; `RELEASE` (Release). With OS support coming in .NET 5.0, even more will be added.

It would be so helpful if we just provided completion for them so that I don't have to look at the command-line args we pass to the compiler to figure them out.

![image](https://user-images.githubusercontent.com/1103906/91800872-27b53980-ec6d-11ea-9a76-b8538aee5e6d.png)

Stretch goal would be to combined them across all "contexts" similar to API completion so that you see a union of them all when targeting multi-frameworks.

**Comment by Youssef1313** [comment] 2020-09-01 18:33
Should this also show the defined constants in `<DefineConstants>` in *csproj* file?
or only a hard-coded set of values?

**Comment by jinujoseph** [comment] 2020-09-08 18:02
Duplicate of #11499

**Closed by jinujoseph** 2020-09-08 18:02 UTC
Labels: Area-IDE, IDE-IntelliSense, help wanted

**Comment by sharwell** [comment] 2020-09-08 18:04
> Stretch goal would be to combined them across all "contexts" similar to API completion so that you see a union of them all when targeting multi-frameworks.

📝 I wouldn't call this a stretch goal. It seems like one of the primary user scenarios for the feature. 😄
