### ISSUE TITLE
Different output when using source generators and deterministic compilation

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/roslyn#52035] opened 2021-03-21 13:53 UTC
**Version Used**: 

```
 Version:   5.0.201
 Commit:    a09bd5c86c

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295
```
**Steps to Reproduce**:

```
git clone -n https://github.com/zkSNACKs/WalletWasabi.git
git checkout 5167183296e2d6a53d73f127e423e1953976a6c7

cd WalletWasabi

dotnet tool install --global ilspycmd --version 7.0.0.6372-preview3
```

```
git clean -xdf

dotnet publish c:\DOWNLOADS\GitHub-Forks\WalletWasabi\WalletWasabi.Fluent.Desktop\WalletWasabi.Fluent.Desktop.csproj -r win7-x64 --configuration Release --force --self-contained true --output c:/Users/wiesl/Downloads/mk1 --disable-parallel --no-cache /p:VersionPrefix=1.1.113.3 /p:DebugType=none /p:DebugSymbols=false /p:ErrorReport=none /p:DocumentationFile="" /p:Deterministic=true /p:RestoreLockedMode=true /flp:v=diag /flp:logfile="c:/Users/wiesl/Downloads/log1.log"

ilspycmd c:\Users\wiesl\Downloads\mk1\WalletWasabi.Fluent.dll > c:\Users\wiesl\Downloads\WalletWasabi.Fluent.dll.out1.txt
```

```
git clean -xdf

dotnet publish c:\DOWNLOADS\GitHub-Forks\WalletWasabi\WalletWasabi.Fluent.Desktop\WalletWasabi.Fluent.Desktop.csproj -r win7-x64 --configuration Release --force --self-contained true --output c:/Users/wiesl/Downloads/mk2 --disable-parallel --no-cache /p:VersionPrefix=1.1.113.3 /p:DebugType=none /p:DebugSymbols=false /p:ErrorReport=none /p:DocumentationFile="" /p:Deterministic=true /p:RestoreLockedMode=true /flp:v=diag /flp:logfile="c:/Users/wiesl/Downloads/log2.log"

ilspycmd c:\Users\wiesl\Downloads\mk2\WalletWasabi.Fluent.dll > c:\Users\wiesl\Downloads\WalletWasabi.Fluent.dll.out2.txt
```

**Expected Behavior**:

The compilation output is same every time published.

**Actual Behavior**:

The compilation output is not the same every time published.

![image](https://user-images.githubusercontent.com/2297442/111907300-fb200e00-8a54-11eb-88dc-54a8bfc26273.png)

**Comment by jaredpar** [comment] 2021-03-22 15:23
Thanks for taking the time to report this issue. 

Unfortunately it doesn't seem like this is a bug in Roslyn but rather that the source generator itself has non-deterministic behavior. The intent is for all generators and analyzers to be deterministic but there is nothing we can do to enforce that they are deterministic. Happy to help the authors work through there issues here and see if there is anything we need to make clearer in our API but closing as there isn't much work to do in the compiler. 

If it turns out there is a bug in the compiler here can re-open and use this to track.

**Comment by wieslawsoltes** [comment] 2021-03-22 18:16
> Unfortunately it doesn't seem like this is a bug in Roslyn but rather that the source generator itself has non-deterministic behavior. 

The generated code is the same every time:

`AccessModifier.cs`
```c#
// <auto-generated />

namespace WalletWasabi.Fluent
{
    public enum AccessModifier
    {
        None = 0,
        Public = 1,
        Protected = 2,
        Private = 3,
        Internal = 4
    }
}
```

https://github.com/zkSNACKs/WalletWasabi/blob/9681880883a77492fdf5e565e163e868fa789c58/WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs#L33-L45

https://github.com/zkSNACKs/WalletWasabi/blob/9681880883a77492fdf5e565e163e868fa789c58/WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs#L63-L65

The difference is in the output dll after publish, the order or code is different, especially apparent when we generate properties and the resulting dll has different order after different publish run with same inputs.

**Comment by wieslawsoltes** [comment] 2021-03-22 18:30
Another example:
### 2a.txt
```C#
	public class BroadcastTransactionViewModel : RoutableViewModel
	{
		[AutoNotify]
		private string _transactionId;

		[AutoNotify]
		private Money? _totalInputValue;

		[AutoNotify]
		private Money? _totalOutputValue;

		[AutoNotify]
		private int _inputCount;

		[AutoNotify]
		private int _outputCount;

		[AutoNotify]
		private Money? _networkFee;

		[AutoNotify]
		private string _inputCountString;

		[AutoNotify]
		private string _outputCountString;

		public string TransactionId
		{
			get
			{
				return _transactionId;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _transactionId, value, "TransactionId");
			}
		}

		public Money? TotalInputValue
		{
			get
			{
				return _totalInputValue;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _totalInputValue, value, "TotalInputValue");
			}
		}

		public Money? TotalOutputValue
		{
			get
			{
				return _totalOutputValue;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _totalOutputValue, value, "TotalOutputValue");
			}
		}

		public int InputCount
		{
			get
			{
				return _inputCount;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _inputCount, value, "InputCount");
			}
		}

		public int OutputCount
		{
			get
			{
				return _outputCount;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _outputCount, value, "OutputCount");
			}
		}

		public Money? NetworkFee
		{
			get
			{
				return _networkFee;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _networkFee, value, "NetworkFee");
			}
		}

		public string InputCountString
		{
			get
			{
				return _inputCountString;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _inputCountString, value, "InputCountString");
			}
		}

		public string OutputCountString
		{
			get
			{
				return _outputCountString;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _outputCountString, value, "OutputCountString");
			}
		}

		public static NavigationMetaData MetaData { get; } = new NavigationMetaData
		{
			Title = "Broadcaster",
			Caption = "Broadcast your transactions here",
			IconName = "live_regular",
			Order = 5,
			Category = "General",
			Keywords = new string[13]
			{
				"Transaction Id", "Input", "Output", "Amount", "Network", "Fee", "Count", "BTC", "Signed", "Paste",
				"Import", "Broadcast", "Transaction"
			},
			NavBarPosition = NavBarPosition.None,
			NavigationTarget = NavigationTarget.DialogScreen
		};


		public override string Title
		{
			get
			{
				return MetaData.Title;
			}
			protected set
			{
			}
		}

		public override NavigationTarget DefaultTarget => MetaData.NavigationTarget;

		public override string IconName => MetaData.IconName;

		public BroadcastTransactionViewModel(BitcoinStore store, Network network, TransactionBroadcaster broadcaster, SmartTransaction transaction)
		{
			BitcoinStore store2 = store;
			TransactionBroadcaster broadcaster2 = broadcaster;
			SmartTransaction transaction2 = transaction;
			base..ctor();
			BroadcastTransactionViewModel broadcastTransactionViewModel = this;
			Title = "Broadcast Transaction";
			Money nullMoney = new Money(-1L);
			TxOut nullOutput = new TxOut(nullMoney, Script.Empty);
			PSBT pSBT = PSBT.FromTransaction(transaction2.Transaction, network);
			TxOut[] array = pSBT.Inputs.Select((PSBTInput x) => x.PrevOut).Select(new Func<OutPoint, TxOut>(GetOutput)).ToArray();
			TxOut[] array2 = pSBT.Outputs.Select((PSBTOutput x) => x.GetCoin().TxOut).ToArray();
			Transaction originalTransaction = pSBT.GetOriginalTransaction();
			_transactionId = originalTransaction.GetHash().ToString();
			_inputCount = array.Length;
			_inputCountString = " input" + TextHelpers.AddSIfPlural(_inputCount) + " and ";
			_outputCount = array2.Length;
			_outputCountString = " output" + TextHelpers.AddSIfPlural(_outputCount) + ".";
			_totalInputValue = (array.Any((TxOut x) => x.Value == nullMoney) ? null : array.Select((TxOut x) => x.Value).Sum());
			_totalOutputValue = (array2.Any((TxOut x) => x.Value == nullMoney) ? null : array2.Select((TxOut x) => x.Value).Sum());
			_networkFee = (((object)TotalInputValue == null || (object)TotalOutputValue == null) ? null : (TotalInputValue - TotalOutputValue));
			IObservable<bool> canExecute = from x in this.WhenAnyValue((BroadcastTransactionViewModel x) => x.IsBusy)
				select !x;
			base.NextCommand = ReactiveCommand.CreateFromTask((Func<Task>)async delegate
			{
				try
				{
					await broadcaster2.SendTransactionAsync(transaction2);
					broadcastTransactionViewModel.Navigate().To(new SuccessBroadcastTransactionViewModel());
				}
				catch (Exception ex)
				{
					Logger.LogError(ex, "WalletWasabi.Fluent\\ViewModels\\TransactionBroadcasting\\BroadcastTransactionViewModel.cs", 92);
					await broadcastTransactionViewModel.ShowErrorAsync(broadcastTransactionViewModel.Title, ex.ToUserFriendlyString(), "It was not possible to broadcast the transaction.");
				}
			}, canExecute, (IScheduler?)null);
			EnableAutoBusyOn(base.NextCommand);
			TxOut GetOutput(OutPoint outpoint)
			{
				if (!store2.TransactionStore.TryGetTransaction(outpoint.Hash, out var sameStx))
				{
					return nullOutput;
				}
				return sameStx.Transaction.Outputs[outpoint.N];
			}
		}

		public static void RegisterAsyncLazy(Func<Task<RoutableViewModel?>> createInstance)
		{
			NavigationManager.RegisterAsyncLazy(MetaData, createInstance);
		}

		public static void RegisterLazy(Func<RoutableViewModel?> createInstance)
		{
			NavigationManager.RegisterLazy(MetaData, createInstance);
		}

		public static void Register(RoutableViewModel createInstance)
		{
			NavigationManager.Register(MetaData, createInstance);
		}
	}
```

### 2b.txt
```C#
	public class BroadcastTransactionViewModel : RoutableViewModel
	{
		[AutoNotify]
		private string _transactionId;

		[AutoNotify]
		private Money? _totalInputValue;

		[AutoNotify]
		private Money? _totalOutputValue;

		[AutoNotify]
		private int _inputCount;

		[AutoNotify]
		private int _outputCount;

		[AutoNotify]
		private Money? _networkFee;

		[AutoNotify]
		private string _inputCountString;

		[AutoNotify]
		private string _outputCountString;

		public static NavigationMetaData MetaData { get; } = new NavigationMetaData
		{
			Title = "Broadcaster",
			Caption = "Broadcast your transactions here",
			IconName = "live_regular",
			Order = 5,
			Category = "General",
			Keywords = new string[13]
			{
				"Transaction Id", "Input", "Output", "Amount", "Network", "Fee", "Count", "BTC", "Signed", "Paste",
				"Import", "Broadcast", "Transaction"
			},
			NavBarPosition = NavBarPosition.None,
			NavigationTarget = NavigationTarget.DialogScreen
		};


		public override string Title
		{
			get
			{
				return MetaData.Title;
			}
			protected set
			{
			}
		}

		public override NavigationTarget DefaultTarget => MetaData.NavigationTarget;

		public override string IconName => MetaData.IconName;

		public string TransactionId
		{
			get
			{
				return _transactionId;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _transactionId, value, "TransactionId");
			}
		}

		public Money? TotalInputValue
		{
			get
			{
				return _totalInputValue;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _totalInputValue, value, "TotalInputValue");
			}
		}

		public Money? TotalOutputValue
		{
			get
			{
				return _totalOutputValue;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _totalOutputValue, value, "TotalOutputValue");
			}
		}

		public int InputCount
		{
			get
			{
				return _inputCount;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _inputCount, value, "InputCount");
			}
		}

		public int OutputCount
		{
			get
			{
				return _outputCount;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _outputCount, value, "OutputCount");
			}
		}

		public Money? NetworkFee
		{
			get
			{
				return _networkFee;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _networkFee, value, "NetworkFee");
			}
		}

		public string InputCountString
		{
			get
			{
				return _inputCountString;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _inputCountString, value, "InputCountString");
			}
		}

		public string OutputCountString
		{
			get
			{
				return _outputCountString;
			}
			set
			{
				this.RaiseAndSetIfChanged(ref _outputCountString, value, "OutputCountString");
			}
		}

		public BroadcastTransactionViewModel(BitcoinStore store, Network network, TransactionBroadcaster broadcaster, SmartTransaction transaction)
		{
			BitcoinStore store2 = store;
			TransactionBroadcaster broadcaster2 = broadcaster;
			SmartTransaction transaction2 = transaction;
			base..ctor();
			BroadcastTransactionViewModel broadcastTransactionViewModel = this;
			Title = "Broadcast Transaction";
			Money nullMoney = new Money(-1L);
			TxOut nullOutput = new TxOut(nullMoney, Script.Empty);
			PSBT pSBT = PSBT.FromTransaction(transaction2.Transaction, network);
			TxOut[] array = pSBT.Inputs.Select((PSBTInput x) => x.PrevOut).Select(new Func<OutPoint, TxOut>(GetOutput)).ToArray();
			TxOut[] array2 = pSBT.Outputs.Select((PSBTOutput x) => x.GetCoin().TxOut).ToArray();
			Transaction originalTransaction = pSBT.GetOriginalTransaction();
			_transactionId = originalTransaction.GetHash().ToString();
			_inputCount = array.Length;
			_inputCountString = " input" + TextHelpers.AddSIfPlural(_inputCount) + " and ";
			_outputCount = array2.Length;
			_outputCountString = " output" + TextHelpers.AddSIfPlural(_outputCount) + ".";
			_totalInputValue = (array.Any((TxOut x) => x.Value == nullMoney) ? null : array.Select((TxOut x) => x.Value).Sum());
			_totalOutputValue = (array2.Any((TxOut x) => x.Value == nullMoney) ? null : array2.Select((TxOut x) => x.Value).Sum());
			_networkFee = (((object)TotalInputValue == null || (object)TotalOutputValue == null) ? null : (TotalInputValue - TotalOutputValue));
			IObservable<bool> canExecute = from x in this.WhenAnyValue((BroadcastTransactionViewModel x) => x.IsBusy)
				select !x;
			base.NextCommand = ReactiveCommand.CreateFromTask((Func<Task>)async delegate
			{
				try
				{
					await broadcaster2.SendTransactionAsync(transaction2);
					broadcastTransactionViewModel.Navigate().To(new SuccessBroadcastTransactionViewModel());
				}
				catch (Exception ex)
				{
					Logger.LogError(ex, "WalletWasabi.Fluent\\ViewModels\\TransactionBroadcasting\\BroadcastTransactionViewModel.cs", 92);
					await broadcastTransactionViewModel.ShowErrorAsync(broadcastTransactionViewModel.Title, ex.ToUserFriendlyString(), "It was not possible to broadcast the transaction.");
				}
			}, canExecute, (IScheduler?)null);
			EnableAutoBusyOn(base.NextCommand);
			TxOut GetOutput(OutPoint outpoint)
			{
				if (!store2.TransactionStore.TryGetTransaction(outpoint.Hash, out var sameStx))
				{
					return nullOutput;
				}
				return sameStx.Transaction.Outputs[outpoint.N];
			}
		}

		public static void RegisterAsyncLazy(Func<Task<RoutableViewModel?>> createInstance)
		{
			NavigationManager.RegisterAsyncLazy(MetaData, createInstance);
		}

		public static void RegisterLazy(Func<RoutableViewModel?> createInstance)
		{
			NavigationManager.RegisterLazy(MetaData, createInstance);
		}

		public static void Register(RoutableViewModel createInstance)
		{
			NavigationManager.Register(MetaData, createInstance);
		}
	}
```

# diff 2a.txt 2b.txt
```patch
26a27,58
> 		public static NavigationMetaData MetaData { get; } = new NavigationMetaData
> 		{
> 			Title = "Broadcaster",
> 			Caption = "Broadcast your transactions here",
> 			IconName = "live_regular",
> 			Order = 5,
> 			Category = "General",
> 			Keywords = new string[13]
> 			{
> 				"Transaction Id", "Input", "Output", "Amount", "Network", "Fee", "Count", "BTC", "Signed", "Paste",
> 				"Import", "Broadcast", "Transaction"
> 			},
> 			NavBarPosition = NavBarPosition.None,
> 			NavigationTarget = NavigationTarget.DialogScreen
> 		};
> 
> 
> 		public override string Title
> 		{
> 			get
> 			{
> 				return MetaData.Title;
> 			}
> 			protected set
> 			{
> 			}
> 		}
> 
> 		public override NavigationTarget DefaultTarget => MetaData.NavigationTarget;
> 
> 		public override string IconName => MetaData.IconName;
> 
122,153d153
< 
< 		public static NavigationMetaData MetaData { get; } = new NavigationMetaData
< 		{
< 			Title = "Broadcaster",
< 			Caption = "Broadcast your transactions here",
< 			IconName = "live_regular",
< 			Order = 5,
< 			Category = "General",
< 			Keywords = new string[13]
< 			{
< 				"Transaction Id", "Input", "Output", "Amount", "Network", "Fee", "Count", "BTC", "Signed", "Paste",
< 				"Import", "Broadcast", "Transaction"
< 			},
< 			NavBarPosition = NavBarPosition.None,
< 			NavigationTarget = NavigationTarget.DialogScreen
< 		};
< 
< 
< 		public override string Title
< 		{
< 			get
< 			{
< 				return MetaData.Title;
< 			}
< 			protected set
< 			{
< 			}
< 		}
< 
< 		public override NavigationTarget DefaultTarget => MetaData.NavigationTarget;
< 
< 		public override string IconName => MetaData.IconName;
```

**Comment by wieslawsoltes** [comment] 2021-03-22 18:44
The OptimisePrivacyViewModel class above is made from 3 different partial classes:

### the original class in OptimisePrivacyViewModel.cs

```C#
using NBitcoin;
using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reactive.Concurrency;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Threading.Tasks;
using ReactiveUI;
using WalletWasabi.Blockchain.TransactionBroadcasting;
using WalletWasabi.Blockchain.TransactionBuilding;
using WalletWasabi.Fluent.ViewModels.Navigation;
using WalletWasabi.Wallets;

namespace WalletWasabi.Fluent.ViewModels.Wallets.Send
{
	[NavigationMetaData(Title = "Optimise your privacy")]
	public partial class OptimisePrivacyViewModel : RoutableViewModel
	{
		private readonly TransactionInfo _transactionInfo;
		private readonly Wallet _wallet;
		private readonly BuildTransactionResult _requestedTransaction;

		[AutoNotify] private ObservableCollection<PrivacySuggestionControlViewModel> _privacySuggestions;
		[AutoNotify] private PrivacySuggestionControlViewModel? _selectedPrivacySuggestion;
		[AutoNotify] private bool _exactAmountWarningVisible;
		private PrivacySuggestionControlViewModel? _defaultSelection;

		public OptimisePrivacyViewModel(Wallet wallet,
			TransactionInfo transactionInfo, TransactionBroadcaster broadcaster, BuildTransactionResult requestedTransaction)
		{
			_wallet = wallet;
			_requestedTransaction = requestedTransaction;
			_transactionInfo = transactionInfo;

			this.WhenAnyValue(x => x.SelectedPrivacySuggestion)
				.Where(x => x is { })
				.Subscribe(x => ExactAmountWarningVisible = x != _defaultSelection);

			_privacySuggestions = new ObservableCollection<PrivacySuggestionControlViewModel>();

			NextCommand = ReactiveCommand.Create(() =>
			{
				Navigate().To(new TransactionPreviewViewModel(wallet, transactionInfo, broadcaster, SelectedPrivacySuggestion!.TransactionResult));
			}, this.WhenAnyValue(x => x.SelectedPrivacySuggestion).Select(x => x is { }));
		}

		protected override void OnNavigatedTo(bool inHistory, CompositeDisposable disposables)
		{
			base.OnNavigatedTo(inHistory, disposables);

			if (!inHistory)
			{
				RxApp.MainThreadScheduler.Schedule(async () =>
				{
					IsBusy = true;

					var intent = new PaymentIntent(
						_transactionInfo.Address,
						MoneyRequest.CreateAllRemaining(subtractFee: true),
						_transactionInfo.Labels);

					if (_requestedTransaction.SpentCoins.Count() > 1)
					{
						var smallerTransaction = await Task.Run(() => _wallet.BuildTransaction(
							_wallet.Kitchen.SaltSoup(),
							intent,
							FeeStrategy.CreateFromFeeRate(_transactionInfo.FeeRate),
							allowUnconfirmed: true,
							_requestedTransaction
								.SpentCoins
								.OrderBy(x => x.Amount)
								.Skip(1)
								.Select(x => x.OutPoint)));

						_privacySuggestions.Add(new PrivacySuggestionControlViewModel(
							_transactionInfo.Amount.ToDecimal(MoneyUnit.BTC), smallerTransaction,
							PrivacyOptimisationLevel.Better, "Improved Privacy"));
					}

					_defaultSelection = new PrivacySuggestionControlViewModel(
						_transactionInfo.Amount.ToDecimal(MoneyUnit.BTC), _requestedTransaction,
						PrivacyOptimisationLevel.Standard);

					_privacySuggestions.Add(_defaultSelection);

					var largerTransaction = await Task.Run(() => _wallet.BuildTransaction(
						_wallet.Kitchen.SaltSoup(),
						intent,
						FeeStrategy.CreateFromFeeRate(_transactionInfo.FeeRate),
						true,
						_requestedTransaction.SpentCoins.Select(x => x.OutPoint)));

					_privacySuggestions.Add(new PrivacySuggestionControlViewModel(
						_transactionInfo.Amount.ToDecimal(MoneyUnit.BTC), largerTransaction,
						PrivacyOptimisationLevel.Better, "Improved Privacy"));

					SelectedPrivacySuggestion = _defaultSelection;

					IsBusy = false;
				});
			}
		}
	}
}
```

and two auto-generated by source generators:

### AutoNotifyGenerator output in OptimisePrivacyViewModel_AutoNotify.cs

```C#
// <auto-generated />
#nullable enable
using ReactiveUI;

namespace WalletWasabi.Fluent.ViewModels.Wallets.Send
{
    public partial class OptimisePrivacyViewModel
    {
        public System.Collections.ObjectModel.ObservableCollection<WalletWasabi.Fluent.ViewModels.Wallets.Send.PrivacySuggestionControlViewModel> PrivacySuggestions
        {
            get => _privacySuggestions;
            set => this.RaiseAndSetIfChanged(ref _privacySuggestions, value);
        }
        public WalletWasabi.Fluent.ViewModels.Wallets.Send.PrivacySuggestionControlViewModel? SelectedPrivacySuggestion
        {
            get => _selectedPrivacySuggestion;
            set => this.RaiseAndSetIfChanged(ref _selectedPrivacySuggestion, value);
        }
        public bool ExactAmountWarningVisible
        {
            get => _exactAmountWarningVisible;
            set => this.RaiseAndSetIfChanged(ref _exactAmountWarningVisible, value);
        }
    }
}
```

### NavigationMetaDataGenerator output in OptimisePrivacyViewModel_NavigationMetaData.cs

```C#
// <auto-generated />
#nullable enable
using System;
using System.Threading.Tasks;
using WalletWasabi.Fluent.ViewModels.Navigation;

namespace WalletWasabi.Fluent.ViewModels.Wallets.Send
{
    public partial class OptimisePrivacyViewModel
    {
        public static WalletWasabi.Fluent.NavigationMetaData MetaData { get; } = new()
        {
            Title = "Optimise your privacy"
        };
        public static void RegisterAsyncLazy(Func<Task<RoutableViewModel?>> createInstance) => NavigationManager.RegisterAsyncLazy(MetaData, createInstance);
        public static void RegisterLazy(Func<RoutableViewModel?> createInstance) => NavigationManager.RegisterLazy(MetaData, createInstance);
        public static void Register(RoutableViewModel createInstance) => NavigationManager.Register(MetaData, createInstance);
        public override string Title {get => MetaData.Title; protected set {} } 
    }
}
```

**Comment by CyrusNajmabadi** [comment] 2021-03-22 20:49
@wieslawsoltes can you move those to gists (or something else) so as to not clutter up the discussion?

**Comment by jaredpar** [comment] 2021-03-22 22:25
I was able to reproduce this locally. At least I can see the `enum` move around in the final binary, not seeing them get deleted. That would be explained if we had some non-determinism in how we processed generators within a single generator assembly. The intent is to guard against that but possible we missed a case. Going to look into it further.

**Comment by wieslawsoltes** [comment] 2021-03-23 07:08
> @wieslawsoltes can you move those to gists (or something else) so as to not clutter up the discussion?

Moved to gist, updated the comments with appropriate links to gist files.

https://gist.github.com/wieslawsoltes/dec51eda107d36561dff40030cd2eb52

**Closed** 2021-04-01 18:11 UTC
Labels: Area-Compilers, Bug, Concept-Determinism, New Feature - Source Generators
