### ISSUE TITLE
VS can't determine which Nuget package needed for fully qualified classnames

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41595] opened 2020-02-12 00:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/911709/vs-cant-determine-which-nuget-package-needed-for-f.html)._

---
I copied some code into a new project that included a reference to Microsoft.CodeAnalysis.CSharp.SymbolDisplay. The required Nuget package wasn't installed so there was an error about an unresolved reference - but Visual Studio couldn't automatically suggest what Nuget package was needed until I removed the namespace ("Microsoft.CodeAnalysis.CSharp").  This seems odd - if anything it should be easier to determine the required package if the namespace is provided too!

---
#### Visual Studio Feedback System on 2/9/2020, 07:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:00
Closing as by design, and that nuget is not investing in this space.

**Closed by CyrusNajmabadi** 2024-10-22 18:00 UTC
Labels: Bug, help wanted, Area-IDE
