### ISSUE TITLE
Invalid "IDE0062 Local function can be made static" when local function calls a local function that captures a struct parameter

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40259] opened 2019-12-09 20:39 UTC
**Version Used**: 16.4.0

```cs
using System;

class C
{
    struct S
    {
        int f;
    }

    void M(S p)
    {
        LocalFunction2();

        void LocalFunction1() => Console.WriteLine(p);

        // IDE0062 Local function can be made static
        //   ↓
        void LocalFunction2() => LocalFunction1();
    }
}
```

After applying the suggested fix:

```cs
    void M(S p)
    {
        LocalFunction2();

        void LocalFunction1() => Console.WriteLine(p);

        // CS8421 A static local function cannot contain a reference to 'LocalFunction1'.
        //                              ↓
        static void LocalFunction2() => LocalFunction1();
    }
```

**Comment by RikkiGibson** [comment] 2019-12-11 01:16
Even if `LocalFunction1` didn't capture any parameters, it seems like it should be disallowed in general to call a non-static local function from a static local function. /cc @agocke @cston

**Comment by jnm2** [comment] 2019-12-11 02:52
I could see the logic for the purposes of fix-all, though.

**Comment by CyrusNajmabadi** [comment] 2020-03-13 00:29
@agocke Debugged through this, it's super weird.  The code that changes the behavior here is:

https://github.com/dotnet/roslyn/blob/3b7504dbd500f97d036e161d2170c7a95894a621/src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs#L31

Specifically, when we analyze the LocalFunctionStatement for `Function2` it returns an empty array for `CapturedInside`.  

However, if we change `struct S` to `class S`, then analyzedataflow returns the `S p` parameter as being captured by the function.

It's honestly not something i understand, but it seems super weird.  In both cases the parameter should be captured in the same way, right?  Assigning to compiler as this appears to be entire within a compiler api call.

**Comment by V0ldek** [comment] 2020-05-23 02:30
@CyrusNajmabadi I think I tracked this thing down. During definite assignment pass variables that are read inside a local function are stored as part of the state. What happens during the analysis of the call from `LocalFunction2` to `LocalFunction1` is, sensibly, a check of all variables read in `LocalFunction1`.

The unexpected behaviour for a `struct S` stems from the fact that definite assignment for structs is tracked piecewise (#15585).

https://github.com/dotnet/roslyn/blob/3b7504dbd500f97d036e161d2170c7a95894a621/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.LocalFunctions.cs#L88-L119

The `if` statement branches depending whether the type is a `struct` or a `class`. If it's a `struct` all of its fields are marked as read, **but the variable itself is not**. The data flow pass for `LocalFunction2` sees that the field `f` is read, but fields aren't captured so its only checked for definite assignment.

You can even see that by turning `p` into a local:

```csharp
void M()
{
    S p;

    // CS0170: Use of possibly unassigned field 'f'
 //↓
    LocalFunction2();

    void LocalFunction1() => Console.WriteLine(p);


    void LocalFunction2() => LocalFunction1();
}
```

The reported error is for the field `f` specifically, not the variable `p`. This behaviour is intended, I believe, as in case of there being more fields only the ones actually not definitely assigned would be reported.

This is still a bug, however, as the reported `Captured` properties of this data flow analysis are inaccurate. Note that the captures are correct when they are checked with `LocalFunction1` as the target range. The incorrect behaviour when checking `LocalFunction2` stems from the logic of this loop inside `VisitLocalFunctionUse`:

https://github.com/dotnet/roslyn/blob/3b7504dbd500f97d036e161d2170c7a95894a621/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.LocalFunctions.cs#L39-L49

A possible fix would be to, in the above loop, do a similar check with `IsTrackableStructType` for each parameter, get its fields and check if any are read, recursively. This doesn't appear to impact performance much, as basically same work is already performed by the `RecordReadInLocalFunction` method anyway, but I might be wrong.

As for the actual issue, I initially wanted to agree with @RikkiGibson that `MakeLocalFunctionStaticHelper` shouldn't suggest changing methods to `static` if they call non-static locals, but what if I want to do something wild like:

```csharp
public class C
{
    int M()
    {
        return LocalFunction1(0);

        int LocalFunction1(int x) => x > 1000 ? x : LocalFunction2(x + 1);

        int LocalFunction2(int x) => x > 1000 ? x : LocalFunction1(2 * x);
    }
}
```

This code is perfectly legal and either both or none of the local functions can be declared as static. We'd have to heavily redo this analyzer to recognize chains of possible make-`static` actions instead of looking at methods individually.

**Comment by CyrusNajmabadi** [comment] 2020-05-23 03:48
Tagging @gafter .  Thanks for the analysis @V0ldek !

**Comment by CyrusNajmabadi** [comment] 2022-11-01 18:55
I don't see this now:

![image](https://user-images.githubusercontent.com/4564579/199315244-28610e89-fab3-4820-bb07-9e63eebb9a4e.png)

**Closed by CyrusNajmabadi** 2022-11-01 18:55 UTC
Labels: Bug, help wanted, Area-Compilers
