### ISSUE TITLE
Visual Studio 2022 IntelliSense not working for added NamingRules

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57874] opened 2021-11-19 01:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-IntelliSense-not-work/1585737)._

---
I crated naming style:

![image](https://user-images.githubusercontent.com/1408396/142521045-88f1a072-82e2-4cbe-b954-8fad52c96527.png)

Next I add this naming rule here for fields:

![image](https://user-images.githubusercontent.com/1408396/142521057-c72c2f43-fec8-4c1e-b4c8-5e2ab82e8a30.png)

So the problem is when I use IntelliSense to generate field for this it's not suggested or generated properly according to the naming rule:

![image](https://user-images.githubusercontent.com/1408396/142521070-bf37d54f-872a-48be-af3f-c6579b060f81.png)

This works fine in Visual Studio 2019.

---
#### Feedback Bot on 11/16/2021, 10:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/18/2021, 09:49 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-12-01 18:50
💭 This may be a situation where code style analyzers are enabled in build. When code style analyzers are enabled in the build, settings in Tools&rarr;Options... are intentionally ignored to ensure the build-time behavior and IDE behavior are the same.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 16:56
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-25 16:56 UTC
Labels: Bug, Area-IDE, Developer Community
