### ISSUE TITLE
Renaming a field causes the file to be renamed too

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#61591] opened 2022-05-31 01:44 UTC
**Version Used**: 

Version 17.3.0 Preview 2.0 [32530.83.main]

**Steps to Reproduce**:

1. Create a new .NET project
2. Add a field to a type
3. Rename the field

![rename-bug](https://user-images.githubusercontent.com/350947/171076465-79528398-b859-4ad2-94f0-9805a11c1aec.gif)

This does not seem to be limited to fields. I renamed a nested class and it renamed the file as well.

**Expected Behavior**:

Only the field is renamed.

**Actual Behavior**:

The field and the file are renamed.

**Comment by davidwengier** [comment] 2022-05-31 02:15
Duplicate of https://github.com/dotnet/roslyn/issues/60294

**Closed by davidwengier** 2022-05-31 02:15 UTC
Labels: Bug, Area-IDE, untriaged
