### ISSUE TITLE
IOperation: There is no way to get to conversion applied to the Primary expression of INullCoalescingExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8852] opened 2016-02-18 00:04 UTC

**Comment by jinujoseph** [comment] 2017-07-04 00:27
Needed for V1 ?

**Comment by CyrusNajmabadi** [comment] 2017-07-12 21:09
I think this could be punted to V2.

**Comment by jinujoseph** [comment] 2018-06-23 00:41
Merge to single issue

**Comment by mavasani** [comment] 2018-06-25 23:43
Dupe of https://github.com/dotnet/roslyn/issues/23325

**Closed by mavasani** 2018-06-25 23:43 UTC
Labels: Area-Analyzers, Area-Interactive, Bug, New Feature - IOperation, _Product-level triaged
