### ISSUE TITLE
Improve debugging experience of iterator properties

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#69827] opened 2023-09-06 00:47 UTC
Iterator properties (containing `yield return`) don't display well in the debugger. For example, the [ClaimsPrincipal.Claims](https://github.com/dotnet/runtime/blob/26e0f8225a2919944e9e50e87e3b0e296cf20a41/src/libraries/System.Security.Claims/src/System/Security/Claims/ClaimsPrincipal.cs#L223-L235) property shows the generated method name:

![image](https://github.com/dotnet/roslyn/assets/303201/f12f24df-b7d7-4d9e-97d9-3d3405aabbb7)

Showing the generated method name is ugly and not useful to anyone debugging this type.

It would be better if the enumerable property was like collections and displayed a count. For example, `Claims: Count = 5`. Unfortunately, there is no way to place `DebuggerDisplayAttribute` on the generated type.

Another option could be to place `DebuggerDisplayAttribute` on the property, but that doesn't work because of a Roslyn bug: https://github.com/dotnet/roslyn/issues/4134

Finally, `DebuggerTypeProxyAttribute` on the property's parent type can work by the type proxy converting the enumerable value into a `List<T>`, but it's a heavy solution. You have to define all the properties on the type in the proxy. And the proxy doesn't work in scenarios where the type can be inherited because the proxy hides new properties on the derived class.

Help come up with a good solution for the debug display of iterator properties.

**Comment by tmat** [comment] 2023-09-06 01:15
Displaying count seems problematic as the debugger would need to execute the enumerator (unlike for collections which usually know the number of elements).

**Comment by JamesNK** [comment] 2023-09-06 01:46
One option could be to stop counting after a certain number, e.g. `Count = 1000+`. But that does feel a little hacky, and automatically executing a bunch of enumerable properties automatically will probably hurt performance.

It would be nice if there was a solution that Just Worked, but a way to customize the debugger display would be fine. Either a way to put a DebuggerDisplay attribute on the generated class returned by the property or [fix DebuggerDisplay on properties](https://github.com/dotnet/roslyn/issues/4134).

**Comment by tmat** [comment] 2023-09-06 01:54
Yes, making DebuggerDisplay work would be good.

**Comment by jcouv** [comment] 2023-09-06 17:19
@tmat Should we resolve this as duplicate of https://github.com/dotnet/roslyn/issues/4134 (DebuggerDisplay issue) then?

**Comment by tmat** [comment] 2023-09-06 19:55
Yes, it can be resolved as dup.

**Closed** 2023-09-06 22:18 UTC
Labels: Interactive-Debugging, Resolution-Answered

**Comment by JamesNK** [comment] 2023-09-06 23:29
I'm fine with this being marked as a dup. But I'd like a timeline to fix the other issue. It's 8 years old 😱

**Comment by tmat** [comment] 2023-09-07 01:19
This area has not been prioritized for a while. We'd accept PR though.
