### ISSUE TITLE
Expand Selection: Select all internal block content before selecting enclsoing braces

### ISSUE THREAD

**Issue by justcla** [dotnet/roslyn#28341] opened 2018-07-06 22:25 UTC
When using Expand Selection, after selecting a single line in a block, the next Expand operation should select all the internal content of the block - but not the enclosing braces.

Example. From this:
![image](https://user-images.githubusercontent.com/17131343/42402575-88edc212-8130-11e8-9db8-a6507c615a42.png)

To this:
![image](https://user-images.githubusercontent.com/17131343/42402586-99bdcb64-8130-11e8-88ab-606efb4765a9.png)

The current implementation expands from the single line to the enclosing block - including the braces, which is really annoying and not very helpful.
![image](https://user-images.githubusercontent.com/17131343/42402610-ba5c2dc0-8130-11e8-9972-612028bb758e.png)

**Comment by CyrusNajmabadi** [comment] 2018-07-06 22:29
> which is really annoying and not very helpful.

Can you expand on this?  Why is this not helpful?  What is the actual user operation that is happening?  If i want to take this body and copy it to something else... wouldn't i want this selection?  

--

Note: this seems like a dupe of your parameter bug.  Basically, it sounds like you're asking for: when on an item in a list, expand to the full list first (not counting delimeters), then expand to delimeters after that.

**Comment by justcla** [comment] 2018-07-06 22:33
Correct. Similar issue. But this time with braces. The other one was parenthesis.

Usually, when copying the body of the method, people are interested in copying the contents - not including the braces. You can easily paste the contents into another method or block, but if it copies the braces, it's not so easy or elegant.

**Comment by CyrusNajmabadi** [comment] 2018-07-06 22:37
> Usually, when copying the body of the method, people are interested in copying the contents - not including the braces. 

Let's chat on gitter.  I'm not actually certain how we come to that conclusion.   :)

> You can easily paste the contents into another method or block, but if it copies the braces, it's not so easy or elegant.

Right, each has their pros and cons.  I think i can get behind your approach though.  because a user can still end up selecting the entire construct, just by expanding twice.  It's just unclear to me if that will be too annoying.

**Comment by justcla** [comment] 2018-07-06 22:41
> I think i can get behind your approach though. because a user can still end up selecting the entire construct, just by expanding twice.

Thank you. That's critical. I want this behavior because I'm not in the habit of pasting curly braces every time I insert code. A user CAN get the braces with one more invocation if they want, but I am UNABLE to get the selection that I want.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 20:29
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-19 20:29 UTC
Labels: Area-IDE, Feature Request, Need Design Review
