### ISSUE TITLE
Converting DateTime into String results in Input String not in Correct Format

### ISSUE THREAD

**Issue by hemantsathe** [dotnet/roslyn#59640] opened 2022-02-18 02:46 UTC
**Version Used**: 
.Net Core 5/6

**Steps to Reproduce**:

1.  Following code in VB.Net gives runtime error while it worked correctly in .Net Framework
```
Dim input As Object = #2022/12/15 12:00:00 AM#
Dim s As String = Date.Parse(input, CultureInfo.CurrentCulture).ToString("yyyy-MMM-dd")
Console.WriteLine(s)
```

From this code the conversion to Integer causes exception at runtime. This code correctly converted the object to DateTime and converted to String instead of Integer. This code also works if we declare the "input" variable as implicitly (w/o "As Object") or explicitly ("As Date or As DateTime"). However, we have hundreds business user written code snippets using similar code which we are migrating from .Net Framework to .Net 5 and this is giving us runtime errors. 

**Expected Behavior**:
This results in a very simple IL as follows:
```
        IL_0000: ldc.i8 638066592000000000
        IL_0009: newobj instance void [mscorlib]System.DateTime::.ctor(int64)
        IL_000e: box [mscorlib]System.DateTime
        IL_0013: call string [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToString(object)
        IL_0018: call class [mscorlib]System.Globalization.CultureInfo [mscorlib]System.Globalization.CultureInfo::get_CurrentCulture()
        IL_001d: call valuetype [mscorlib]System.DateTime [mscorlib]System.DateTime::Parse(string, class [mscorlib]System.IFormatProvider)
        IL_0022: stloc.0
        IL_0023: ldloca.s 0
        IL_0025: ldstr "yyyy-MMM-dd"
        IL_002a: call instance string [mscorlib]System.DateTime::ToString(string)
        IL_002f: call void [mscorlib]System.Console::WriteLine(string)
        IL_0034: ret
```
**Actual Behavior**:
This code results in following IL for the `ToString("yyyy-MM-dd")` call
```
IL_0083: callvirt instance string [System.Private.CoreLib]System.Object::ToString()
IL_0088: ldstr "yyyy-MMM-dd"
IL_008d: call int32 [Microsoft.VisualBasic.Core]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
IL_0092: callvirt instance char [System.Private.CoreLib]System.String::get_Chars(int32)
IL_0097: call string [Microsoft.VisualBasic.Core]Microsoft.VisualBasic.CompilerServices.Conversions::ToString(char)
IL_009c: call void [System.Console]System.Console::WriteLine(string)
IL_00a1: ret
```

**Comment by jcouv** [comment] 2022-02-25 17:52
@cston From chat with Jared, we suspect this may be specific to early .NET Core. Could you confirm and advise?

**Comment by cston** [comment] 2022-03-09 07:27
With .NET Framework 4.8, there is a single applicable overload for the call to `Date.Parse(input, CultureInfo.CurrentCulture)`, so the expression has a compile-time type of `System.DateTime`.
```vb
Function Parse(s As System.String, provider As System.IFormatProvider) As System.DateTime
```

With .NET 5 and .NET 6, there are two applicable overloads for `Date.Parse(input, CultureInfo.CurrentCulture)`, so the expression is late-bound and has a compile-time type of `System.Object`.
```vb
Function System.DateTime.Parse(s As System.ReadOnlySpan(Of System.Char),
    Optional provider As System.IFormatProvider = Nothing,
    Optional styles As System.Globalization.DateTimeStyles = System.Globalization.DateTimeStyles.None)
    As System.DateTime
Function System.DateTime.Parse(s As System.String, provider As System.IFormatProvider) As System.DateTime
```

As a result, with .NET 5 and .NET 6, the subsequent `.ToString("yyyy-MMM-dd")` is bound as a call to `Object.ToString()` followed by a call to `String.Chars(index As Integer)` with `"yyyy-MMM-dd"` converted to an `Integer`.

(A similar conversion error occurs with .NET Framework 4.8 if the `Date.Parse()` result is cast to `System.Object`.)

@hemantsathe, to resolve the issue, consider casting the `Date.Parse()` expression to `System.DateTime` explicitly:
```
Dim d As Date = Date.Parse(input, CultureInfo.CurrentCulture)
Dim s As String = d.ToString("yyyy-MMM-dd")
```

**Comment by cston** [comment] 2022-03-09 17:54
Closing as the current behavior is by design with late binding.

**Closed by cston** 2022-03-09 17:54 UTC
Labels: Bug, Language-VB, Area-Compilers
