### ISSUE TITLE
Incorrect possible null reference argument while using null coalescing operator

### ISSUE THREAD

**Issue by nelsonprsousa** [dotnet/roslyn#50487] opened 2021-01-14 22:16 UTC
**Version Used**:  C# 8, Visual Studio 16.8.3

**Steps to Reproduce**:

```csharp
// query.Experiments is an IEnumerable<string>
if (!query.Experiments?.Any() ?? true)
{
	return default!;
}

//if (query.Experiments == null || !query.Experiments.Any())
//{
//    return default!;
//}

var experiments = GetAvailableExperimentParticipations(query.Experiments);
```

**Expected Behavior**:
I was expecting that query.Experiments couldn't be possible null when calling `GetAvailableExperimentParticipations` method.

**Actual Behavior**:
We are receiving the following warning:
Warning	CS8604	Possible null reference argument for parameter 'experiments' in 'IEnumerable<string> GetExperimentParticipationsQueryHandler.GetAvailableExperimentParticipations(IEnumerable<string> experiments)'.

If we use the commented code the warning do not appear, just like we expect.

**Comment by RikkiGibson** [comment] 2021-01-15 20:06
To date, nullable analysis of conditional accesses like these has worked by seeing a conditional access contained in some kind of comparison, such as `==`, `!=`, `is`, or `??`, and "reaching down" into the conditional access to find out how the StateWhenTrue/StateWhenFalse should be affected. But we don't "reach down" past logical operators down into the conditional accesses.

You can work around this in your code by using `query.Experiments?.Any() != true` instead.

This scenario is of interest in dotnet/csharplang#4240. Any improvements of this nature made in definite assignment would likely be "inherited" by nullable analysis.

This does make me consider whether we really should introduce a "StateWhenNull" to the spec and implementation which can be propagated more conventionally, instead of special-casing certain syntax forms. I'm not sure whether a "StateWhenNotNull" would also be needed, or if "clever" application of the StateWhenTrue and StateWhenFalse would suffice. I'm not sure what would be the magnitude of the change needed in spec and implementation. @AlekseyTs.

**Comment by jaredpar** [comment] 2021-01-22 14:10
Closing as this behavior is currently "By Design" and we should move discussion to the linked C# proposal for fixing.

**Closed by jaredpar** 2021-01-22 14:10 UTC
Labels: Area-Compilers, untriaged
