### ISSUE TITLE
CS8603 for explicit interface implementation

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31867] opened 2018-12-17 17:39 UTC
**Version Used**: 
VS2019 Preview 1

**Steps to Reproduce**:
```C#
using System.Collections;
using System.Collections.Generic;

public struct Enumerator<T> : IEnumerator<T>
{
    object IEnumerator.Current => Current;

    public T Current => throw null;
    public void Dispose() => throw null;
    public bool MoveNext() => throw null;
    public void Reset() => throw null;
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Program.cs(6,35,6,42): warning CS8603: Possible null reference return.

**Comment by cston** [comment] 2018-12-17 22:05
If `T` is a nullable type (say, `object?` or `int?`), the return value `=> Current` will be treated as nullable.

**Comment by Pilchie** [comment] 2018-12-17 22:13
So, what are my options for writing an unconstrained Enumerator?

**Comment by cston** [comment] 2018-12-17 22:39
Perhaps change the nullability of the explicit implementation return type:
```c#
object? IEnumerator.Current => Current;
```

**Comment by Pilchie** [comment] 2018-12-17 22:46
What do you know?  That does work.  Very unintuitive though it makes sense...

**Comment by jaredpar** [comment] 2019-01-02 18:06
Closing as this behavior is "By Design".

**Closed by jaredpar** 2019-01-02 18:06 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
