### ISSUE TITLE
Bug with Local Functions (compilator crash)

### ISSUE THREAD

**Issue by istupakov** [dotnet/roslyn#18884] opened 2017-04-21 18:49 UTC
**Version Used**: 

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Steps to Reproduce**:

1. Create console .net core app (netcoreapp1.1) 
2. Write next code

```
using System;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        Func<string, Task> app = s => Task.CompletedTask;
        try
        {
            int i = 1;

            void readFunc()
            {
                var newReadTask = Console.In.ReadLineAsync();
                newReadTask.ContinueWith(task => { readFunc(); app(task.Result); });
            }
        }
        finally
        {
        }
    }
}
```

3. Build project.

**Expected Behavior**:
Build success.

**Actual Behavior**:
Compilator fail!

C:\Program Files\dotnet\sdk\1.0.3\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "C:\Program Files\dotnet\sdk\1.0.3\Roslyn\RunCsc.cmd" exited with code -2146232797.

**Comment by agocke** [comment] 2017-04-24 19:30
This appears to be another duplicate of https://github.com/dotnet/roslyn/issues/16895 and no longer repros in master. Closing as dup.

**Closed by agocke** 2017-04-24 19:30 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
