### ISSUE TITLE
Unable to implement interface event on class with primary constructor and custom event accessors.

### ISSUE THREAD

**Issue by cbaxter** [dotnet/roslyn#72207] opened 2024-02-21 16:50 UTC
**Version Used**: 
MSBuild version 17.9.4+90725d08d for .NET
Visual Studio version  17.9.0

**Steps to Reproduce**:
When attempting to create a process wrapper and bubbling i[ legacy events; unable to compile code that uses a primary constructor and custom event accessors without crashing. 

1. Compile [Sample Program](https://sharplab.io/#v2:CYLg1APgAgDABFAjAOgCIEsCGBzAdgewGcAXdAY0IG4BYAKDt0wFsBTQgB0zJbgGVn2AGxZ0A3nTiS46XMRYAnRoIQAmBIgDsEqeNpT96gGwIALHACymGQApexeTOwBtALpxM87IQCU2g3F1/fyQATmsAIgAJFkFBfAAaOAB1fHlBYABCcO8aPSCAXzo/Axk5RUxlQhYKlmBVOAAFeXxuQkIk+Ux2dgVrJpa2QjgAV1xgBUEAT0d+1p84EDgASVnB4v1AoP0oAGY4FgA3Flk4AFEj2UjMMeF5M4APdDlgdaDNrf9MYDrREbGJ6a4bCrNrIU6PZ5wMAAXjgBwqwxYlDghTyHwM8hYTHwRwCf3GaUBwOaczBENqcAAtLD4YJEcjUejJIyCkU0QZdtJZAoAGZcHgrElrdkbV7+Q7HYhnC7EK43BQPJ61XJbFnMuiooA)

``` csharp
using System.Diagnostics;

namespace Sample
{
    internal class Program
    {
        static void Main(String[] args)
        {
            Console.WriteLine("Hello, World!");
        }

        internal sealed class ProcessWrapper(Process underlyingProcess) : IProcess
        {
            public event EventHandler Exited
            {
                add { underlyingProcess.Exited += value; }
                remove { underlyingProcess.Exited -= value; }
            }
        }

        public interface IProcess
        {
            event EventHandler Exited;
        }
    }
}
```

NOTES:
* Code compiles if `IProcess` inteface not implemented 
  * e.g., `internal sealed class ProcessWrapper(Process underlyingProcess) //: IProcess`
* Code compiles if `underlyingProcess` variable from primary constructor is explicitly assigned to property.
  * e.g.,  `private Process UnderlyingProcess { get; } = underlyingProcess`

**Diagnostic Id**:

n/A

**Expected Behavior**:
Code Compiles without error.

**Actual Behavior**:

**Visual Studio**
<img width="912" alt="image" src="https://github.com/dotnet/roslyn/assets/1178905/dce94409-4b05-43cc-94cc-2421ec99f3d5">

**dotnet msbuild**
> MSBuild version 17.9.4+90725d08d for .NET
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Process terminated. System.Null
ReferenceException: Object reference not set to an instance of an object. [C:\Projects\ThrowAway\ConsoleApp1\ConsoleApp
1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CS
harp.Symbols.MethodSymbol.get_ParameterCount() [C:\Projects\ThrowAway\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CS
harp.InMethodBinder.LookupSymbolsInSingleBinder(LookupResult result, String name, Int32 arity, ConsList`1 basesBeingRes
olved, LookupOptions options, Binder originalBinder, Boolean diagnose, CompoundUseSiteInfo`1& useSiteInfo) [C:\Projects
\ThrowAway\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CS
harp.Binder.LookupSymbolsInternal(LookupResult result, String name, Int32 arity, ConsList`1 basesBeingResolved, LookupO
ptions options, Boolean diagnose, CompoundUseSiteInfo`1& useSiteInfo) [C:\Projects\ThrowAway\ConsoleApp1\ConsoleApp1\Co
nsoleApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CS
harp.Binder.LookupSymbolsWithFallback(LookupResult result, String name, Int32 arity, CompoundUseSiteInfo`1& useSiteInfo
, ConsList`1 basesBeingResolved, LookupOptions options) [C:\Projects\ThrowAway\ConsoleApp1\ConsoleApp1\ConsoleApp1.cspr
oj]
...

**Comment by jaredpar** [comment] 2024-02-21 17:37
Closing as a dupe of #71400

**Closed by jaredpar** 2024-02-21 17:37 UTC
Labels: Area-Compilers, untriaged
