### ISSUE TITLE
[Nullable] Get asked to simplify cast needed to remove nullable warning

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38331] opened 2019-08-28 06:45 UTC
**Version Used**: 

**Steps to Reproduce**:

``` C#
#nullable enable

class Bar
{       
       protected override Task<string?> FindFileAsync(IProjectTreeProvider provider, IProjectTree root)
       {
               return Task.FromResult((string?)"");
                                       _______
       }
}

```
**Expected Behavior**:
No simplification

**Actual Behavior**:
Get prompted to simplify as indicated. If follow through with simplification, get a warning:

```
Warning	CS8619	Nullability of reference types in value of type 'Task<string>' doesn't match target type 'Task<string?>'.	Microsoft.VisualStudio.ProjectSystem.Managed	C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\SpecialFileProviders\AbstractFindByNameSpecialFileProvider2.cs	26	Active
```

**Comment by davkean** [comment] 2019-08-28 06:49
Similar to https://github.com/dotnet/roslyn/issues/37980 but a cast.

**Comment by jasonmalinowski** [comment] 2019-08-28 21:19
Closing this as a dupe of #37980; the system was generally unaware of nullability prior to that fix. @davkean the build with the fix was only inserted yesterday so you likely didn't have the fix at the time.

**Closed by jasonmalinowski** 2019-08-28 21:19 UTC
