### ISSUE TITLE
Renaming / refactoring positional record properties does not working when renamed in the parameter list.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60353] opened 2022-03-23 23:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming--refactoring-positional-record/1696408)._

---
[severity:I'm unable to use this version]
Renaming / refactoring positional record's properties in the parameter list does not work. It does not highlight and rename these properties in record's methods.
On the other hand when I refactor these names in methods, then it workds - renaming is reflected in record's positional parameters.

Example: 

record Dog(string Name) // renaming Name here does NOT work. Also highlighting Name here does NOT highlight Name in the Bark() method.
{
    public void Bark() => Console.WriteLine(Name);
}

---
#### Feedback Bot on 3/20/2022, 05:10 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-03-24 08:24
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/44560?

**Comment by ryzngard** [comment] 2022-03-25 21:33
Needed to double check if these issues still repro. Looks like rename when selecting the record property declaration doesn't work but rename when selecting other locations does. 

![image](https://user-images.githubusercontent.com/475144/160203453-d7cf1e4e-edb7-4c14-9e4c-7ba4e64eb4f4.png)

vs 

![image](https://user-images.githubusercontent.com/475144/160203483-8ec604b7-6753-4dee-9ecc-7abc70930cd1.png)


Agreed this is a dupe of #44560

**Closed by ryzngard** 2022-03-25 21:33 UTC
Labels: Area-IDE, untriaged
