### ISSUE TITLE
"Show items from unimported namespaces" and "resolve usings" inserts imports in wrong location when "inside_namespace"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#40976] opened 2020-01-15 04:51 UTC
**Version Used**: 
Version 16.5.0 Preview 3.0 [29714.123.master]

**Steps to Reproduce**:

```
[*.cs]
csharp_using_directive_placement = inside_namespace:error
``` 

``` C#
namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package
{
    internal class SolutionExplorerService
    {
        private Lazy< // <!-- Resolve using

        public SolutionExplorerService()
        {
        }
    }
}

```
**Expected Behavior**:
``` C#
namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package
{
    using System;

    internal class SolutionExplorerService
    {
        private Lazy<

        public SolutionExplorerService()
        {
        }
    }
}

```

**Actual Behavior**:
``` C#
using System;

namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package
{
    internal class SolutionExplorerService
    {
        private Lazy<

        public SolutionExplorerService()
        {
        }
    }
}

```

**Comment by Dreamescaper** [comment] 2020-01-15 09:17
Duplicate of https://github.com/dotnet/roslyn/issues/35803

**Comment by JoeRobich** [comment] 2020-07-29 23:35
Agree this is a duplicate of https://github.com/dotnet/roslyn/issues/35803. Progress can be tracked on that issue.

**Closed by JoeRobich** 2020-07-29 23:35 UTC
Labels: Area-IDE, Bug, help wanted
