### ISSUE TITLE
There is a typo in "Configure Code Cleanup"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60773] opened 2022-04-15 17:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/There-is-a-typo-in-Configure-Code-Clean/10003790)._

---
[severity:It bothers me. A fix would be nice]
There is a typo in "Configure Code Cleanup"
"Apply namespace matches folder preferences"
folder instead of folded
detail is shown in the screenshot in "additional attachments"

![image](https://user-images.githubusercontent.com/754264/163635632-16813598-5c15-4404-b923-b95f5e185a05.png)

---
#### Feedback Bot on 4/6/2022, 03:09 AM: 

(private comment, text removed)
#### Feedback Bot on 4/8/2022, 09:13 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment] 2022-04-15 21:50
Duplicate of https://github.com/dotnet/roslyn/issues/60213

**Closed by davidwengier** 2022-04-15 21:50 UTC
Labels: Area-IDE, untriaged
