### ISSUE TITLE
ExtractMethodCodeRefactoringProvider crashes after a local function is pasted into a method

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#18481] opened 2017-04-05 23:09 UTC
**Version Used**: VS 2017

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Here is the code I was writing at the time:

```cs
        [Theory]
        public void Multiply(Term term, int coefficient)
        {
            void Verify(Term product)
            {
                Assert.Equal(coefficient * term.Coefficient, product.Coefficient);
                Assert.Equal(term.Exponent, product.Exponent);[|]
            }

            var product = coefficient * term;

            // Multiplication should be commutative.
            product = term * coefficient;
            Assert.Equal()
        }
```

I had just deleted the two `Assert.Equal` statements from below `var product = ...` and pasted them into the body of the local function when the crash happened.

If it's relevant, here is the code for the `Term` class in my project. Luckily it's largely self-contained:

```cs
    public struct Term
    {
        private Term(int coefficient, int exponent)
        {
            Coefficient = coefficient;
            Exponent = exponent;
        }

        public static implicit operator Term(int value)
            => new Term(coefficient: value, exponent: 0);

        public static Term operator *(Term left, Term right)
            => new Term(
                coefficient: checked(left.Coefficient * right.Coefficient),
                exponent: checked(left.Exponent + right.Exponent));

        public static Term X(int exponent) => new Term(1, exponent);

        public int Coefficient { get; }

        public int Exponent { get; }

        public bool IsConstant => Exponent == 0;

        public Term Pow(int exponent)
            => new Term(
                coefficient: Coefficient.Pow(exponent),
                exponent: checked(Exponent * exponent));
    }
```

**Comment by jcouv** [comment] 2017-04-06 06:25
FYI @agocke

**Comment by Pilchie** [comment] 2017-04-06 21:05
Duplicate of #17165

**Closed by Pilchie** 2017-04-06 21:05 UTC
Labels: Area-IDE, Bug
