### ISSUE TITLE
Unnecessarily lifted field in async state machine

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#13759] opened 2016-09-13 13:06 UTC
**Version Used**: 
2.0.0.60620

**Steps to Reproduce**:
Compile this code:

``` C#
using System.IO;
using System.Threading.Tasks;

class Program
{
    public static void Main() { }

    public static async Task Repro1(Stream source, Stream destination)
    {
        byte[] buffer = new byte[0x1000];
        int bytesRead;
        while ((bytesRead = await source.ReadAsync(buffer, 0, buffer.Length)) != 0)
        {
            await destination.WriteAsync(buffer, 0, bytesRead);
        }
    }

    public static async Task Repro2(Stream source, Stream destination)
    {
        byte[] buffer = new byte[0x1000];
        while (true)
        {
            int bytesRead = await source.ReadAsync(buffer, 0, buffer.Length);
            if (bytesRead == 0) break;
            await destination.WriteAsync(buffer, 0, bytesRead);
        }
    }
}
```

**Expected Behavior**:
The async state machine does not have a field for `bytesRead`.

**Actual Behavior**:
In Repro2, as expected, the async state machine does not lift `bytesRead` to the state machine.  But in Repro1, it does lift `bytesRead` to the state machine, even though the value of `bytesRead` doesn't need to be preserved across an await.

**Comment by gafter** [comment] 2016-09-13 16:43
When debug is enabled, we lift all variables that are in scope after an await. In `Repro1`, `bytesRead` is in scope after the await. But not in `Repro2`. So I think this is by design.

Does that explain it?

**Comment by stephentoub** [comment] 2016-09-13 16:57
> So I think this is by design

Scope shouldn't be relevant, at least not from a theoretical perspective (in Repro2, ```bytesRead``` is still in scope after the await until the closing brace, it's just not used, hence the compiler can avoid lifting it).  We only need to lift fields to the state machine if they're written before an await and read after the await such that its value needs to be preserved across a possible suspension.  In this case, the compiler should be able to see that the value of ```bytesRead``` need not be preserved across an await, since any value it would carry over after an await is immediately overwritten.

Maybe that's more sophisticated than C#'s flow analysis supports, but it seems like it should be doable.

**Comment by gafter** [comment] 2016-09-13 21:47
@stephentoub We consider a variable "used" if it might be inspected using the debugger (when debug is enabled).

Are you observing this behavior when compiling _without_ debug support?

**Comment by stephentoub** [comment] 2016-09-13 21:49
> Are you observing this behavior when compiling without debug support?

Yes, this is in a release build.

**Comment by gafter** [comment] 2018-01-09 22:03
Fixed in https://github.com/dotnet/roslyn/pull/23930

**Closed by gafter** 2018-01-09 22:03 UTC
Labels: Area-Compilers, Bug, Concept-Code Quality Improvement, Resolution-Fixed, Tenet-Performance
