### ISSUE TITLE
"Introduce local" quick action menu shouldn't show "for all occurrences" when there is only one occurrence

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#51333] opened 2021-02-19 11:14 UTC
### Repro steps

1. Select an expression that only appears once in scope
2. Invoke Quick Action menu (<kbd>Ctrl</kbd>+<kbd>.</kbd>)

### Actual behaviour

Menu appears as:

![image](https://user-images.githubusercontent.com/350947/108497134-1df8be80-72ff-11eb-8dd5-58b8f11b778a.png)

### Expected behaviour

Given there is only one occurrence of the selected expression, the second menu item should not be present.

### Rationale

Every time I see _both_ actions, I assume the selected expression actually appears more than once, and that multiple substitutions will be made.

There's more informational content for the user if the second item appears conditionally. For example, if it appears when you expected the selection to be unique in that scope, you might take pause and re-assess the intended refactoring with a larger scope in mind.

**Comment by sharwell** [comment] 2021-02-24 20:52
📝 If we make a change here, we should ensure that we are not slowing down the initial display of the menu to account for this analysis. It's better to show an extra option (or an option that ends up taking no action) than to have a slow UX.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 16:40
Closing as by design.  It's too expensive to do the analysis at display time.

**Closed by CyrusNajmabadi** 2024-10-22 16:40 UTC
Labels: Area-IDE, Concept-Continuous Improvement
