### ISSUE TITLE
Please expose Compilation.GetBestTypeByMetadataName as a public API

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52399] opened 2021-04-03 20:16 UTC
###### [This issue clones [https://github.com/dotnet/roslyn/issues/52118](https://github.com/dotnet/roslyn/issues/52118) but without asking for two things in one]

The existing API, Compilation.GetTypeByMetadataName, ceases to work in unpredictable situations where one of the compilation's references internally declares a type with the same name which is never visible to the compilation. This is a pitfall that hurts code generation. For example, if my code fix provider wants to pass ObsoleteAttribute to SyntaxGenerator, I might grab the symbol using GetTypeByMetadataName. This will mysteriously begin failing if a user begins targeting `net5.0-windows` where `System.DirectoryServices` gets automatically referenced, declaring its own internal ObsoleteAttribute. (Repro shown at https://github.com/dotnet/roslyn/issues/52037).

Roslyn itself is banning the use of Compilation.GetTypeByMetadataName in all its own analyzers: https://github.com/dotnet/roslyn/issues/43341

`Best` is short, but `Accessible` or `Visible` might be more self-explanatory. You're getting the single type that is accessible anywhere within the compilation, if there is exactly one.

**Comment by jnm2** [comment] 2021-04-20 16:40
Am I as a consumer then on the hook for applying InternalsVisibleTo or else risking generating code with ambiguity errors?
What about internal types in the same compilation along with public types in references?

**Comment by sharwell** [comment] 2021-04-20 16:44
> Am I as a consumer then on the hook for applying InternalsVisibleTo or else risking generating code with ambiguity errors or picking the wrong type symbol to examine?

Yes, but `SemanticModel` already has API to do this.

**Comment by 333fred** [comment] 2021-04-20 16:45
Perhaps `includeInternal` isn't quite right, maybe `includeInaccessable` is? By default, we would include anything that the current compilation has access to, including private inner types defined in the current compilation and anything visible via IVT, and then if `includeInaccessible` is true we'd truly include everything?

**Comment by sharwell** [comment] 2021-04-20 16:47
My preference is to not include the `includeInternal` parameter at all (or a variant), which will reduce caching overhead in the shared compiler code.

**Comment by 333fred** [comment] 2021-04-20 16:51
> My preference is to not include the `includeInternal` parameter at all (or a variant), which will reduce caching overhead in the shared compiler code.

How so?

**Comment by jnm2** [comment] 2021-04-20 16:52
I want a helper that is dead simple for the majority case where people are thinking in terms of "is this the same type symbol that I would get if I emitted this full name." If it's even two lines long, now it's a burden to call this for a bunch of type symbols in a row.

**Comment by jnm2** [comment] 2021-04-20 16:55
> it would be easy for the average analyzer author to implement an appropriate "best" policy given the new API.

@sharwell This is not clearly defined for me. Could you list one or two policies that could make sense that differ from "is this the same type symbol that I would get if I emitted this full name" in a way that an average analyzer author might need?

**Comment by CyrusNajmabadi** [comment] 2021-04-20 17:16
I think the onus is on to not on create an api here, but provide the right guidance and examples on how to use it effectively for the myraid cases we use the existing api for (incorrectly).  I think we should be scenario driven here in terms of identifying what we see in both our own analyzers, and those of customers, and we should then validate the APIs we produce against that.

In this case, i really don't even know if GetTypesByMetadataName is sufficient.  Nor do i think this part is great:

> That is easy enough to filter on by the consumer true.

I think the problem is that customers (including IDE) don't really know how they are supposed to filter these properly.  In general, what they are trying to do is simulate how they *think* the compiler works.  But how it works is effectivelya  black box, so usage of these apis is already a heuristic to try to mimic that.  If we could actually have the compiler expose functionality that exposed how it actually does tehse tasks, that would take out the guesswork and hte pushing of responsibility to those who aren't really going to know what to do with it.

--

As an example, i believe this has come up many a time to ask: does this symbol have such and such attribute on it.  Currently, many parts of our codebase answer that question by checking type symbol equality.  However, i've heard from others that this is not actually correct and not hte way the compiler does it itself.  So even if i have GetTypesByMetadataName, i don't think that will be sufficient as i don't even know if that will provide me with the results that would allow me to interrogate a symbol to tell if the compiler believes it has a certain attribute on it.  For this sort of case, perhaps exposing how the compiler actually does things here would be preferred?

**Comment by jaredpar** [comment] 2021-04-21 01:07
@CyrusNajmabadi 

> I think the onus is on to not on create an api here, but provide the right guidance and examples on how to use it effectively for the myraid cases we use the existing api for (incorrectly).

I agree we need to provide guidance. I think the are a few probing questions that generally get to the core of what customers and we can construct guidance around that. 

> As an example, i believe this has come up many a time to ask: does this symbol have such and such attribute on it. Currently, many parts of our codebase answer that question by checking type symbol equality. However, i've heard from others that this is not actually correct and not hte way the compiler does it itself. So even if i have GetTypesByMetadataName, i don't think that will be sufficient as i don't even know if that will provide me with the results that would allow me to interrogate a symbol to tell if the compiler believes it has a certain attribute on it. For this sort of case, perhaps exposing how the compiler actually does things here would be preferred

The attribute one has come up a bit recently, particularly with the runtime team, and it revealed once again different customer requirements. In some cases customers want to know if it's binding to an exact attribute (not any type with this FQN but a very specific instance of that type). In some cases customers just want to find any attribute with that FQN (don't care which type with the FQN it is just that it has that FQN). Each of these scenarios would change the approach we recommend for solving the problem. 

This is also why a one size fits all isn't going to work. No matter which one we pick we're going to end up excluding the other customer here. Instead I think we're much better off with the approach I outlined. It puts the problem square in the customers face so they know that they need to change the question they're asking. 

Pretty much every customer I've chatted with has been a bit surprised when I brought up that FQN are not unique. One of those once you ask they immediately say "oh yeah, makes sense" but not the type of question they thought to ask themselves. Unless they are faced with this reality they're likely to end up making decisions that don't line up with what their actual goals are.

**Comment by jaredpar** [comment] 2021-04-21 01:07
@jnm2 


> I want a helper that is dead simple for the majority case where people are thinking in terms of "is this the same type symbol that I would get if I emitted this full name." 

I wish it were this simple but this is a fundamentally ambiguous scenario and customers have different expectations on how they want the ambiguity resolved. Attempting to solve for the majority is just excluding a different set of customers and asking them to solve it on their own. Why should we exclude them just because they represent the < 50% use case?

Instead I would like to focus on giving the tools that let customers with the different expectations and scenarios solve the problems they need to solve. 

> If it's even two lines long, now it's a burden to reinvent

That is setting a bar that allows for only one outcome.

**Comment by jnm2** [comment] 2021-04-21 13:12
@jaredpar I like that focus. I'm not asking for exclusion, just for helpers on top of whatever is exposed for the large percentage cases. And I only know about one case which means this "one policy of many" concept is really hard to talk about. Can you list out the top few scenarios so I can catch up?

> That is setting a bar that allows for only one outcome.

I think there can be wiggle room and it doesn't have to be an absolute statement, but I gave the reasoning for why I think this should be strongly considered.

**Comment by arturohernandez10** [comment] 2021-07-19 20:42
This strikes me as an odd discussion. There are so many for the status quo without providing a reasonable alternative.

        // Summary:
        //     Gets the type within the compilation's assembly and all referenced assemblies
        //     (other than those that can only be referenced via an extern alias) using its
        //     canonical CLR metadata name.
        //
        // Returns:
        //     Null if the type can't be found.

Why not at least add a few words to this summary. As a costumer my expectation is any unexpected result should be made more prominent. Clearly ```the type can't be found```. Why not say ```Null if 1)______, 2)____ ```. Just be transparent and own up to your API.

**Comment by CyrusNajmabadi** [comment] 2021-07-19 23:23
@arturohernandez10 This is all open source.  PR's welcome for areas people are passionate about.

**Comment by 333fred** [comment] 2021-11-16 20:16
I'm going to close this out in favor of https://github.com/dotnet/roslyn/issues/57802, which is how we would like to move forward in this space.

**Closed by 333fred** 2021-11-16 20:16 UTC
Labels: Concept-API, Area-Compilers, Feature Request
