### ISSUE TITLE
Proposal: Support for static classes to implement from interfaces

### ISSUE THREAD

**Issue by gigajew** [dotnet/roslyn#36852] opened 2019-06-28 00:16 UTC
I have this issue where I need a static class to implement from an interface. Appearently the IL has support for it but C# compiler / language does not.

```c#
public class Program {
  public static void Main(string[] argv) {
    LittleEndian.WriteUInt(new MemoryStream(), (ushort)2);
  }
}

public interface Endianness {
  void WriteUInt16(Stream stream, ushort value);
}
public class LittleEndian : Endianness {
  public void WriteUInt16(Stream stream, ushort value) {
    stream.WriteByte((byte)(value & 0xff));
    stream.WriteByte((byte)((value >> 8) & 0xff));
  }
}
```

**Comment by canton7** [comment] 2019-06-28 07:25
Duplicate of https://github.com/dotnet/csharplang/issues/2619

**Closed** 2019-07-09 20:41 UTC
Labels: Area-Compilers
