### ISSUE TITLE
I need an "Indent Namespace Contents" preference for C# Text Editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53725] opened 2021-05-27 20:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-need-an-Indent-Namespace-Contents-pr/1433229)._

---
The C# text editor always indents namespace contents.  There is no preference to disable this.  Why not?  The C++ text editor already gives us this preference.  Why does the C# editor not do so?

I want to be able to make my C# code look like this without Visual Studio warning me about "IDE0055: Fix formatting"

```
namespace MyCompany.Module1
{
public class SomeClass  // Do not indent class
{
    public void DoSomething() {}
}
}
```

Please give us this option.  Also in an EditorConfig format would help

---
#### Feedback Bot on 5/27/2021, 02:15 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2021-06-02 18:11
Duplicate of #24129

**Closed by jinujoseph** 2021-06-02 18:11 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community, Need Design Review
