### ISSUE TITLE
VB compiler incorrectly parses paths in `/embed` switch containing `,`

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#30586] opened 2018-10-18 16:42 UTC
Both
`vbc /debug:portable program.vb /embed:a,b.vb` and 
`vbc /debug:portable program.vb /embed:"a,b.vb"`

result in errors:

```
vbc : error BC2001: file 'C:\Temp\a' could not be found
vbc : error BC2001: file 'C:\Temp\b.vb' could not be found
```

This issue is not limited to command line. The problem is also with `vbc` task:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>vb</RootNamespace>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedFiles Include="a,b.vb" />
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/41759/47170389-bd828e00-d2ba-11e8-9f76-af44a00e77d1.png)

This is a problem since .NET SDK uses comma in generated file name:
`.NETStandard,Version=v2.0.AssemblyAttributes.vb`

**Comment by jaredpar** [comment] 2018-10-29 15:35
What is the expected behavior here?

**Comment by tmat** [comment] 2018-10-29 16:07
Not treat `,` as a path separator.

**Comment by AArnott** [comment] 2018-12-07 16:19
See also #31611 which talks about the `Sources` input specifically. So this problem is shared across both inputs.

**Comment by AArnott** [comment] 2018-12-07 17:32
OK, so that one was a dupe of this. 

But *this* issue is becoming more important IMO because of the recommendation to embed untracked source files in the portable PDB. I can get a new VB project to repro the failure just by adding two lines:

```diff
 <Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
     <OutputType>Exe</OutputType>
     <RootNamespace>b</RootNamespace>
     <TargetFramework>netcoreapp2.2</TargetFramework>
+     <EmbedUntrackedSources>true</EmbedUntrackedSources>
   </PropertyGroup>

   <ItemGroup>
+     <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="All" />
   </ItemGroup>

 </Project>
```

**Closed** 2018-12-29 07:48 UTC
Labels: Area-Compilers, Need More Info
