### ISSUE TITLE
SymbolFinder does not find generated symbols

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#63375] opened 2022-08-13 05:36 UTC
**Version Used**: 4.3.0

**Steps to Reproduce**:

1. Create a workspace with a source-generated symbol and no user-defined source trees.
2. Attempt to use `SymbolFinder` to find the generated symbol

**Expected Behavior**:

Symbol is found.

**Actual Behavior**:

Symbol is not found. `SymbolFinder` appears to not attempt searching source-generated documents at all.

**Comment by CyrusNajmabadi** [comment] 2024-11-22 04:16
Closing out as by design.  All these systems work off of indices cached for real documents.  We have no bandwidth or desire to update them for SG scenarios, which goes under the bucket of IDE only doing minimal work to support SG cases.

**Closed by CyrusNajmabadi** 2024-11-22 04:16 UTC
Labels: Bug, Area-IDE, IDE-Navigation
