### ISSUE TITLE
Light bulb suggest to remove a parameter

### ISSUE THREAD

**Issue by GW-Lab** [dotnet/roslyn#34641] opened 2019-04-01 17:36 UTC
VB 16 RC4

make a XML variable with a embeded vb variable see picture:

Don't suggest to remove the parameter
![URI-Parameter](https://user-images.githubusercontent.com/49092462/55347520-67468780-54b5-11e9-927e-4c2c2a15f1b1.png)

**Comment by jinujoseph** [comment] 2019-04-02 18:30
Duplicate of #33898

**Closed by jinujoseph** 2019-04-02 18:30 UTC
Labels: Area-IDE, Resolution-Duplicate
