### ISSUE TITLE
IDE0009: Fix all occurrences in Document not working

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/roslyn#17943] opened 2017-03-17 20:08 UTC
**Version Used:** 
Visual Studio 15.0.0.0+26228.9

**Steps to Reproduce**:
1. Goto `Options -> Text Editor -> C# -> Code Style -> General` and make sure all of the `'this.' preferences` are set to `Prefer 'this.'`
2. Create a new C# project.
3. Add multiple private fields to a class and try to reference them without the `this.` qualifier.
4. `Ctrl+.` on one of the fields (which should show you the `IDE0009` code fix)
5. Select `Fix all occurrences in Document`

**Expected Behavior**:
All of the fields should be qualified with `this.`

**Actual Behavior**:
Nothing happens. It doesn't add `this.` to any of the variable references.

Something to note, applying a single code fix (not Fix all occurrences in X) works. Also, other CodeFixes work. I seem to only be having this issue in IDE0009.

**Comment by CyrusNajmabadi** [comment] 2017-03-17 22:03
Do you have a repro file we can look at?

**Comment by CyrusNajmabadi** [comment] 2017-03-27 00:42
Sam, can you take a look?

**Comment by sharwell** [comment] 2017-05-25 06:50
I believe this is a duplicate of one or more specific scenarios described in #17183. Thank you for taking time to report this @ChristopherHaws. All of these reports were a big help in finally coming up with concrete ways to reproduce this frustrating issue. 👍

**Closed by sharwell** 2017-05-25 06:50 UTC
Labels: 4 - In Review, Area-IDE, Bug
