### ISSUE TITLE
REQUEST:  Allow generic parameter types to participate in overload resolution

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#10142] opened 2016-03-28 10:01 UTC
**Version Used**: 
Visual Studio 2015 Update 1

**Steps to Reproduce**:
Create a new console project with the following code:
````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Collections;

namespace ConsoleApplication14 {
    class Program {
        public static T Foo<T>() where T : ICollection {
            return default(T);
        }

        public static T Foo<T>() where T : IDictionary {
            return default(T);
        }


        static void Main(string[] args) {
        }
    }
}
````

**Expected Behavior**:
The program should compile because the two Foo's are differentiated by T.

**Actual Behavior**:
I get the error:
Type 'Program' already defines a member called 'Foo' with the same type parameters.

**Comment by HaloFour** [comment] 2016-03-28 12:22
This would require changes to the CLR as it does not recognize the generic type constraints as being a part of the method signature and therefore does not allow defining duplicate methods with the same argument types but with different constraints.  C# inherits that limitation.

**Comment by svick** [comment] 2016-03-28 14:27
I think this is a duplicate of #7459.

**Closed** 2016-03-29 19:51 UTC
Labels: Area-Language Design, Resolution-Duplicate
