### ISSUE TITLE
Code fix doesn't see changes in document/project/solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25642] opened 2018-03-21 01:33 UTC
Trying to invoke the &quot;Require accessibility modifier&quot; code fix shows a preview for a single item but then does not see/fix changes for a document/project/solution.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/217391/code-fix-doesnt-see-changes-in-documentprojectsolu.html
VSTS ticketId: 585383_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment] 2018-03-21 01:35
Repro steps 

Here’s a concrete repro:

1.	Clone https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
2.	Checkout the code-style branch
3.	Open the solution in VS 2017 15.7 Preview 1
4.	In the Core project, in the Extensions folder, open up FileSystemExtensions.cs
5.	Notice that it’s internal static class…
6.	Put the cursor on line 6 (the where the modifier is), see the lightbulb.

Here’s the issues:
1.	Text says “Add accessibility modifiers.” The rule is configured to omit them if default, so will do a remove in this case. The wording needs a way to change based on the configured code style rule setting.
 
![image](https://user-images.githubusercontent.com/12449387/37691202-690fd34e-2c6d-11e8-8665-fe31dced8d29.png)

2.	If you perform the single action, it works.
3.	Undo to get back to the unmodified doc
4.	Click the lightbulb again and select Fix all occurrences in document.
 
![image](https://user-images.githubusercontent.com/12449387/37691214-721fbf08-2c6d-11e8-8b88-f37afa8ea2fc.png)

5.	Same thing happens for project/solution.

**Comment by crypto-rsa** [comment] 2018-05-17 12:04
Same issue happens for other code fixes, too.
For example if there is an `.editorconfig` file with the line
`csharp_style_expression_bodied_properties = true:suggestion`

then in a file with
```
private int _a;
private int _b;

public int A
{
    get => _a;
}

public int B
{
    get => _b;
}
```

I can convert `A` to an expression-bodied property using the code fix, but when I click _Fix all occurrences in Document_ in the preview window, only the _No Changes_ item appears in the list.

**Comment by sharwell** [comment] 2018-05-17 17:41
Duplicate of #19089

**Closed by sharwell** 2018-05-17 17:41 UTC
Labels: Area-IDE, Bug
