### ISSUE TITLE
C# interactive producing incorrect results

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51030] opened 2021-02-05 20:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-interactive-producing-incorrect-resul/1330629)._

---
[severity:I'm unable to use this version]
The following expression incorrectly returns "0" when evaluated in C# interactive:
TimeSpan.FromSeconds(0.00005). Ticks

It should return 500, as it does when called in a normal .NET process.

If my calculator started producing the wrong values I would throw it in the trash. I don't want to throw C# interactive in the trash.

---
#### Feedback Bot on 2/4/2021, 10:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MarkPflug** [comment] 2021-02-05 20:37
TimeSpan.FromSeconds(0.0005).Ticks
produces 10000, should be 5000
TimeSpan.FromSeconds(0.005).Ticks
Correctly produces 50000

Wish I could see a pattern, but I don't.

**Comment by ufcpp** [comment] 2021-02-06 05:31
Seems like this is a problem of .NET Framework.

```cs
using System;

Console.WriteLine(TimeSpan.FromSeconds(0.000005).Ticks);
Console.WriteLine(TimeSpan.FromSeconds(0.00005).Ticks);
Console.WriteLine(TimeSpan.FromSeconds(0.0005).Ticks);
```

The result is

```cs
0
0
10000
```

in net48 and

```cs
50
500
5000
```

in net5.0.

In C# Interactive, you can use .NET Core by using `#reset core` directive.

```cs
> #reset core
Resetting execution engine.
> TimeSpan.FromSeconds(0.00005).Ticks
500
```

**Comment by ufcpp** [comment] 2021-02-06 05:37
https://docs.microsoft.com/en-us/dotnet/api/system.timespan.fromseconds?view=net-5.0

According to the document saying "the specification is accurate to the nearest millisecond", this is by design and the result in .NET 5 is rather incorrect.

**Comment by ufcpp** [comment] 2021-02-06 05:51
see: https://github.com/dotnet/runtime/issues/13230#issuecomment-613214316

**Comment by MarkPflug** [comment] 2021-02-06 15:28
Sounds like this is dotnet/runtime issue then. Hope they choose to update the docs and not revert the change in behavior. I can think of no reason that API shouldn't offer resolution down to the tick for situations like this. Rounding to the millisecond would make it less useful.

Anyway, good to know the scope of the issue and that I can continue to depend on the interactive window. Thanks for investigating and thanks for the pointer about "#reset core", wasn't aware of that feature.

**Comment by CyrusNajmabadi** [comment] 2021-02-06 17:50
Closing out as this is not an issue with interactive and the underlying cause is known and already tracked with the right team.

**Closed by CyrusNajmabadi** 2021-02-06 17:50 UTC
Labels: Area-Interactive, untriaged
