### ISSUE TITLE
IOperation tree for invocation expression syntax with binding errors has no IInvocationExpression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18069] opened 2017-03-22 18:29 UTC
1. Paste the following code in ETA:
```Imports System

Class Program
    Private Shared Sub Main(args As String())
        Console.WriteLine2()
    End Sub
End Class
```
2. Get the IOperation tree for invocation with semantic errors:
```
IOperation tree for "Console.WriteLine2()"

IInvalidExpression (OperationKind.InvalidExpression, Type: ?, IsInvalid)
  IInvalidExpression (OperationKind.InvalidExpression, Type: ?, IsInvalid)
    IOperation:  (OperationKind.None)
```

There is no IInvocationExpression, only invalid expression. Not super critical, but we good to have for IDE error case scenarios.

**Comment by mavasani** [comment] 2017-03-22 18:29
Tagging @dotnet/analyzer-ioperation

**Comment by mavasani** [comment] 2017-03-22 18:39
Another scenario, IOperation tree for the invocation below has no IIInvocationExpression:
```
Class Program
    Private Shared Sub Main(args As String())
        F(String.Empty)'BIND:"F(String.Empty)"
    End Sub

    Private Sub F()
    End Sub
End Class
```

```
IOperation tree for "F(String.Empty)"

IInvalidExpression (OperationKind.InvalidExpression, Type: System.Void, IsInvalid)
  IOperation:  (OperationKind.None)
  IFieldReferenceExpression: System.String.Empty As System.String (Static) (OperationKind.FieldReferenceExpression, Type: System.String)
```

**Comment by AlekseyTs** [comment] 2017-03-27 21:51
VB compiler creates BoundCall node only for success cases.

**Comment by AlekseyTs** [comment] 2017-03-27 21:54
I am not sure if IOperation behavior should be different, across both languages.

**Comment by mavasani** [comment] 2017-03-27 21:56
Yes, that was the source of confusion - C# does generate a BoundCall with HasErrors = true.

**Comment by AlekseyTs** [comment] 2017-03-27 22:00
I think it would be simpler to expose IInvocation... only when overload resolution succeeds.

**Comment by CyrusNajmabadi** [comment] 2017-03-28 16:52
Ideally, this would work like GetSymbolInfo does.  Namely that you can get the correct symbol if there is one, or you can get the candidate set of symbols when there isn't.

In other words, i should get  a similar level of error tolerance and exposed information that i get with SemanticModel.GetXXXInfo through the IOperation tree as well.  Not sure how possible that is though.

**Comment by genlu** [comment] 2017-07-13 20:50
Related to #18722

**Comment by jinujoseph** [comment] 2017-09-29 21:05
dupe of #18722

**Closed by jinujoseph** 2017-09-29 21:05 UTC
Labels: 3 - Working, Area-Analyzers, Bug, Language-VB, New Feature - IOperation
