### ISSUE TITLE
ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68971] opened 2023-07-11 02:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ExtractInterfaceCodeRefactoringProvider-/10410407)._

---
I am getting the following error:

ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled. 

I can reenable the ExtractInterfaceCodeRefactoringProvider, but the issue keeps reoccurring.

the stacktrace is.

System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,SyntaxTree syntaxTree)
   at async Microsoft.CodeAnalysis.Shared.Utilities.AnnotatedSymbolMapping.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToNewFileAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)

The class I am trying to create an interface for is using CommunityToolkit.Mvvm code generators - perhaps there is an issue in the interplay between [ObservableProperty] and ExtractInterfaceCodeRefactoringProvider.

The class is for which I am trying to create an interface is:

internal partial class ShellViewStateService : BaseService
    {
        [ObservableProperty]
        private string _lastLoggedInUsername = string. Empty;

[ObservableProperty]
        private bool _ribbonIsEnabled = false;

[ObservableProperty]
        private object? _currentView;

public ShellViewStateService(ILogger<ShellViewStateService> logger, IMediator mediator, IMessenger messenger, JoinableTaskFactory joinableTaskFactory) : base(logger, mediator, messenger, joinableTaskFactory)
        {
        }

//Methods
        public Task SwitchToViewAsync(ViewModelBase view)
        {
            RibbonIsEnabled = true;
            CurrentView = view; 
            return Task.CompletedTask;
        }
    }

---
#### Feedback Bot on 7/9/2023, 08:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2023-07-11 04:58
Duplicate of https://github.com/dotnet/roslyn/issues/68748

**Closed** 2023-08-22 22:26 UTC
Labels: Area-IDE, untriaged
