### ISSUE TITLE
Document outline should distinguish members with multiple overloads

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#65713] opened 2022-12-02 00:36 UTC
**Version Used**: 17.5.0 Preview 1.

**Steps to Reproduce**:

1. Create multiple constructors with different signatures.

**Actual:**

<img width="133" alt="image" src="https://user-images.githubusercontent.com/201340/205188198-660ac306-3fb3-4753-8a33-6f2f1926bf3c.png">

**Expected:** It'd be nice if we had some signatures to distinguish in this case. I could understand to avoid noise we'd only show the signature if there was in fact an overload.

**Comment by CyrusNajmabadi** [comment] 2022-12-02 00:44
Well, we also shouldn't show 'ctor'... Genuinely confused as i thought this was just exposing the information from the LSP outlining model, and that shouldn't be using .ctor either.

Def worries me as this indicates we're using semantics here, where we should be using syntax.

**Comment by jasonmalinowski** [comment] 2022-12-02 18:26
I'm guessing we're using symbols to get the symbol name; I'm not sure we have a helper for "here's a syntax node, give me the name directly without just doing GetDeclaredSymbol"

**Comment by CyrusNajmabadi** [comment] 2022-12-02 18:52
> I'm guessing we're using symbols to get the symbol name; I'm not sure we have a helper for "here's a syntax node, give me the name directly without just doing GetDeclaredSymbol"

We def have that.  It's how NavTo works :)

**Comment by jasonmalinowski** [comment] 2022-12-02 18:56
Ah, duh, of course.

**Comment by sharwell** [comment] 2023-05-04 23:37
I'm not able to reproduce this, so I'm guessing it was fixed by #65641

**Closed by sharwell** 2023-05-04 23:37 UTC
Labels: Bug, Area-IDE, Navigation-Document Outline
