### ISSUE TITLE
Yielding in catch blocks not supported in async iterators

### ISSUE THREAD

**Issue by Daniel15** [dotnet/roslyn#39583] opened 2019-10-30 06:07 UTC
Imagine something like:
```cs
public async IAsyncEnumerable<string> DoStuff()
{
	await foreach (var reply in CallSomeApi())
	{
		yield return "Message: " + reply;
	}
}
```

Where `CallSomeApi` is actually some streaming API that provides an `IAsyncEnumerable` (for example, `.ResponseStream.ReadAllAsync()` on a gRPC streaming response).

Say `CallSomeApi` can throw exceptions, for example:
```cs
private static async IAsyncEnumerable<string> CallSomeApi()
{
	yield return "foo";
	await Task.Delay(100);
	throw new Exception("Something bad happened");
}
```

How am I supposed to handle exceptions thrown by CallSomeApi?

My initial naive thought was something like this:
```cs
public async IAsyncEnumerable<string> DoStuff(
	[EnumeratorCancellation] CancellationToken cancellationToken
)
{
	try
	{
		await foreach (var reply in CallSomeApi().WithCancellation(cancellationToken))
		{
			yield return "Message: " + reply;
		}
	}
	catch (Exception ex)
	{
		yield return "Error: " + ex.Message;
	}
}
```

But this throws [CS1626](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1626):
```
Error	CS1626	Cannot yield a value in the body of a try block with a catch clause
```

(jcouv edit): Relates to https://github.com/dotnet/csharplang/issues/765

**Comment by Daniel15** [comment] 2019-11-01 07:39
For what it's worth, I ended up using channels (`Channel.CreateUnbounded`) rather than async streams, to work around this issue. My use case was for [SignalR server-to-client streaming](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.0#server-to-client-streaming) which supports both `IAsyncEnumerable<T>` and `ChannelReader<T>`. Ended up with code like this instead:

```cs
public async Task DoStuff(ChannelWriter<string> writer)
{
	try
	{
		await foreach (var reply in CallSomeApi().WithCancellation(cancellationToken))
		{
			writer.WriteAsync('Message: ' + reply);
		}
	}
	catch (Exception ex)
	{
		writer.WriteAsync("Error: " + ex.Message);
	}
}
```

**Comment by gafter** [comment] 2019-11-06 19:03
The specification for async iterators does not call out this as being an error, so it is a bug (possibly in the specification, possibly in the compiler)

**Comment by jcouv** [comment] 2019-12-06 22:39
I was about to file a championed issue for this to move it forward, but in thinking about it more, I'm not sure I like it.
The problem is that catch blocks can be executed during disposal, and in such case there is nowhere to yield items to.

As far as C# 8.0 specification, I think this is [covered](https://github.com/dotnet/roslyn/blob/master/docs/features/async-streams.md) by:
> It is a compile-time error for a yield return statement to appear anywhere in a try statement that contains any catch clauses.

**Comment by jcouv** [comment] 2019-12-07 00:11
Neal pointed out offline that my concern with yielding items during disposal may be unfounded. I need to think about this more. (my example doesn't [work](https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABATARgLACgUGYACdQgYUIG9dCbiiUAOYjAFgDoBJAQQgE8A7AMYBRfgFcAtgFMATmABGAGykAeAJb9gAPkIBZABQBKQtVpUctS4WAzepq5XsPaNuxeeXzHjygwZiAOyEGADchAD04cz+sGoQYIqKAPYA7lKwhBrWtoRKSYIA1oQpasAAFoRghIJgwIIVgopgYhBSTh4Avu3OAGYaCYpu3mbdw+UyqYT8UimEwgAeglIADsBqSfxGIaNWXe4Oex41dRX6C0ur6/zGFISHtHsdQA))

Jared pointed out offline that it is good to keep rules for iterators and async-iterators aligned. Something more to think about.

**Comment by thomassuckow** [comment] 2020-03-06 19:20
I ended up using https://github.com/Dasync/AsyncEnumerable in C#8 because I can try catch how I expect to be able to.
Namely I need to prevent iterating over another Iasynciterable from propagating an exception as I aggregate from multiple places.

Oversimplified:
```c#
while(something) {
  var foo = NextFoo();
  var asyncItems = foo.DoSomething();
  try {
    await foreach (var item in asyncItems)
    {
      yield return item;
    }
  } catch(Exception e) {
    //Record the exception and continue
  }
}
```

**Comment by AartBluestoke** [comment] 2020-07-07 02:04
noting that removing this constraint is now a championed issue : https://github.com/dotnet/csharplang/issues/2949

**Comment by Euan-McVie** [comment] 2020-11-16 14:29
Found this while trying to work out solution for same issue.
For reference I have solved using:
```cs
IAsyncEnumerator<TResult> enumerator = stream.GetAsyncEnumerator();
TResult result;
bool hasResult = true;
while (hasResult)
{
    try
    {
        hasResult = await enumerator.MoveNextAsync().ConfigureAwait(false);
        if (hasResult)
            result = enumerator.Current;
        else
            result = null;
    }
    catch (TException ex)
    {
        result = mapFailureFunc(ex);
    }
    if (result != null)
        yield return result;
}
```
where `mapFailureFunc` "knows" how to translate an exception into a TResult

**Comment by Bouke** [comment] 2022-04-05 06:57
@Euan-McVie You should also dispose the enumerator (async).

**Comment by CyrusNajmabadi** [comment] 2022-11-08 17:35
@jcouv this is currently marked as by-design?  Can we close this out?  I presume we'd need a language change here anyways to move forward on this.

**Comment by jcouv** [comment] 2022-11-08 17:37
Yes. Closing as duplicate/moved to https://github.com/dotnet/csharplang/issues/2949 (championed issue)

**Closed by jcouv** 2022-11-08 17:37 UTC
Labels: Bug, Area-Compilers, Resolution-By Design, New Feature - Async Streams
