### ISSUE TITLE
NullReferenceException at SourceMethodSymbol.CalculateLocalSyntaxOffset (on a Mac)

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#16174] opened 2017-01-01 09:08 UTC
**Version Used**: 2.0.0.60620

**Steps to Reproduce**:
Not sure if this scenario is even supported. I'm trying to compile a modified version of monodevelop on Visual Studio for Mac. MCS had an issue with type-forwarding assemblies, so I switched to MSBuild with Roslyn (by modifying the Microsoft.CSharp.Mono.targets file). Most projects in the solution compiled fine, except for MonoDevelop.Ide, which produced the following exception:

```
  System.ExecutionEngineException: System.NullReferenceException: Object reference not set to an instance of an object
    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMethodSymbol.CalculateLocalSyntaxOffset (System.Int32 localPosition, Microsoft.CodeAnalysis.SyntaxTree localTree) [0x00007] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.SynthesizedStateMachineMethod.CalculateLocalSyntaxOffset (System.Int32 localPosition, Microsoft.CodeAnalysis.SyntaxTree localTree) [0x00006] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GetLocalDebugName (Microsoft.CodeAnalysis.ILocalSymbolInternal local, Microsoft.CodeAnalysis.CodeGen.LocalDebugId& localId) [0x0004c] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.DefineLocal (Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol local, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntaxNode) [0x00156] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0006d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0009d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0000c] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement (Microsoft.CodeAnalysis.CSharp.BoundSequencePoint node) [0x0002d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0008b] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0009d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl () [0x00027] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate () [0x00000] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody (Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, System.Int32 methodOrdinal, Microsoft.CodeAnalysis.CSharp.BoundStatement block, System.Collections.Immutable.ImmutableArray`1[T] lambdaDebugInfo, System.Collections.Immutable.ImmutableArray`1[T] closureDebugInfo, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol stateMachineTypeOpt, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator variableSlotAllocatorOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain importChainOpt, System.Boolean emittingPdb) [0x000c0] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods (Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState) [0x000fa] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType (Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType) [0x0043d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0 () [0x00000] in <44ba953d41aa43dd9b6e6c27ec08c729>:0  ---> System.NullReferenceException: Object reference not set to an instance of an object
    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMethodSymbol.CalculateLocalSyntaxOffset (System.Int32 localPosition, Microsoft.CodeAnalysis.SyntaxTree localTree) [0x00007] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.SynthesizedStateMachineMethod.CalculateLocalSyntaxOffset (System.Int32 localPosition, Microsoft.CodeAnalysis.SyntaxTree localTree) [0x00006] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GetLocalDebugName (Microsoft.CodeAnalysis.ILocalSymbolInternal local, Microsoft.CodeAnalysis.CodeGen.LocalDebugId& localId) [0x0004c] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.DefineLocal (Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol local, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntaxNode) [0x00156] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0006d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0009d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0000c] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement (Microsoft.CodeAnalysis.CSharp.BoundSequencePoint node) [0x0002d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0008b] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock (Microsoft.CodeAnalysis.CSharp.BoundBlock block) [0x0009d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement (Microsoft.CodeAnalysis.CSharp.BoundStatement statement) [0x0007e] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl () [0x00027] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate () [0x00000] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody (Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, System.Int32 methodOrdinal, Microsoft.CodeAnalysis.CSharp.BoundStatement block, System.Collections.Immutable.ImmutableArray`1[T] lambdaDebugInfo, System.Collections.Immutable.ImmutableArray`1[T] closureDebugInfo, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol stateMachineTypeOpt, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator variableSlotAllocatorOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain importChainOpt, System.Boolean emittingPdb) [0x000c0] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods (Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState) [0x000fa] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType (Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType) [0x0043d] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0 () [0x00000] in <44ba953d41aa43dd9b6e6c27ec08c729>:0 
```
[Full stack trace](https://github.com/dotnet/roslyn/files/679948/stacktrace.txt)

The same code compiles fine in Visual Studio 2017.

**Comment by gafter** [comment] 2017-01-02 00:29
Can you please provide sources that crash when compiled?

**Comment by aelij** [comment] 2017-01-03 06:43
The codebase is pretty big so I've tried to isolate the problematic project:
https://www.dropbox.com/s/0y5a4nrzmx9pzgz/main.zip?dl=0
This should have all the required assemblies to build it (there's a solution in src/core/MonoDevelop.Ide).

The full code is essentially the main branch in this fork: https://github.com/aelij/monodevelop

**Comment by jcouv** [comment] 2017-01-15 05:11
This stacktrace reminds me of https://github.com/dotnet/roslyn/issues/10611 (and duplicate https://github.com/dotnet/roslyn/issues/11649). The issue was with a reference to `base` in an iterator method. It was fixed in dev15 preview 4 (in July).
If my understanding of the build numbers is correct, the present issue was repro'ed on a build from 6/20 (pre-dating the fix) but did not repro in VS2017 (presumably preview 4 or later).

@aelij In your setup, how did you get Roslyn? Could you try using a more recent version or package?

**Comment by aelij** [comment] 2017-01-15 05:22
It was the Roslyn build that was included with Mono/MSBuild 4.8 beta that VS for Mac installed. I got version number directly from the `Microsoft.CodeAnalysis` assembly under

/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/

Not sure how I can change packages. Perhaps there's a newer drop of Mono 4.8 I could try.

**Comment by aelij** [comment] 2017-01-15 05:57
The latest Mono beta has the same version of Roslyn as above. Where can I get a newer build of Roslyn for mono (binaries)? I can try to replace the files.

**Comment by jcouv** [comment] 2017-01-15 16:09
@marek-safar may have some insights. I'm not too familiar with Mono yet. 
The question is: what is the plan/cadence for updating the Roslyn build within Mono? Or is there a documented way to update Roslyn in place in Mono 4.8 beta?

**Comment by jcouv** [comment] 2017-01-20 00:11
@marek-safar The question is: what is the plan/cadence for updating the Roslyn build within Mono? Or is there a documented way to update Roslyn in place in Mono 4.8 beta?

**Comment by marek-safar** [comment] 2017-01-20 13:47
@aelij is this error reliably reproducible or does it happen randomly ?

@jcouv this Roslyn version comes from bundled msbuild Roslyn not actual Roslyn used in Mono.
https://github.com/Microsoft/msbuild/blob/xplat/src/.nuget/project.json and it was bumped to recent version only 2 weeks ago.

**Comment by aelij** [comment] 2017-01-20 15:45
@marek-safar Always happens in that solution.

**Comment by jcouv** [comment] 2017-01-20 17:42
@aelij Would you mind looking at the properties on the `csc.exe` that is involved in your repro? In particular, 6 to 8 letters from the Commit Hash would be great.
For me, that looks like this:
![image](https://cloud.githubusercontent.com/assets/12466233/22159193/a55dd7be-def4-11e6-93c7-f60ec1250ac2.png)
This will let me confirm whether your binary has the fix from a previous similar issue (#10611).

**Comment by aelij** [comment] 2017-01-20 19:12
It's not on a Windows machine, so I can't view the properties, but here's the file... [csc.exe.zip](https://github.com/dotnet/roslyn/files/720253/csc.exe.zip) (Located in `/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe`)

I just tried looking for base calls in iterators. When I commented these lines the compilation succeeded:
```csharp
foreach (var r in base.OnGetContents (type))
    yield return r;
```
So it must be the same bug.

If you'd like me to try a newer build just let me know where I can get one for Mono.

**Comment by jcouv** [comment] 2017-01-20 19:32
@aelij Thanks for the info. Looking at the `csc.exe` you provided, it is definitely an old version pre-dating the fix (dates from June, but the fix was only checked in July).
![image](https://cloud.githubusercontent.com/assets/12466233/22162500/ca55054c-df03-11e6-8395-c08c9b4c2f4c.png)

@marek-safar can advise on how to refresh the package with msbuild and csc within mono.

**Comment by marek-safar** [comment] 2017-01-20 22:08
@jcouv As I wrote earlier the change/fix was pushed 2 weeks ago now it just has to bubble up through our release queue.

https://github.com/Microsoft/msbuild/commit/803d46910bfb4b30766f64967c82934f58da0e63
Although whether it's good Roslyn version I don't know

**Comment by jcouv** [comment] 2017-01-20 22:15
Thanks for the clarification. The version linked by Marek above does contain the compiler fix (ie. version "2.0.0-rc3-61110-06" of Microsoft.Net.Compilers is good).

@aelij I'll close this issue as I'm pretty sure this was already fixed in the compiler. Please wait til Mono makes it available and feel free to re-open if it could still repro at that point. Thanks!

**Closed by jcouv** 2017-01-20 22:15 UTC
Labels: 3 - Working, Area-Compilers, Bug, _Product-level triaged
