### ISSUE TITLE
Error Activating the Razor Language Server After Editing Razor File and Moving to C# File

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/roslyn#49445] opened 2020-11-13 18:15 UTC
![image](https://user-images.githubusercontent.com/14852843/99106329-131ce800-25b2-11eb-9895-affdc381b213.png)

1. Edit Counter.razor
2. Move to & edit in Program.cs

Expected: Normal editing
Actual: RZLS seems to have crashed

Note; repro doesn't happen 100% of the time.

```
System.InvalidOperationException: The language server has not yet shutdown.at Roslyn.Utilities.Contract.Fail(String message)at 
Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.AbstractInProcLanguageClient.ActivateAsync(CancellationToken token)at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<OnRpcDisconnected>d__92.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

[VS Main Local]
[30713.9]

**Comment by NTaylorMullen** [comment] 2020-11-17 19:07
@dibarbet transferring this to Roslyn. There's a good chance this is an LSP platform issue but I don't see why they would be trying to re-activate either so I'm slightly suspect of Roslyn's pre-loading behavior.

**Comment by dibarbet** [comment] 2020-11-17 19:09
@NTaylorMullen this is a dupe of https://github.com/dotnet/roslyn/issues/49329

**Comment by dibarbet** [comment] 2020-11-17 22:48
Nevermind, @davidwengier is correct and this is not a dupe - my bad!

**Comment by dibarbet** [comment] 2020-11-17 22:49
The LSP logs here will be useful - it looks like we get called to shutdown, then restarted before we fully shutdown

**Comment by TanayParikh** [comment] 2020-11-18 03:12
ActivityLog

```
System.InvalidOperationException: The language server has not yet shutdown.at Roslyn.Utilities.Contract.Fail(String message)at 
Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.AbstractInProcLanguageClient.ActivateAsync(CancellationToken token)at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<OnRpcDisconnected>d__92.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   

Razor C# Language Server Client 
```

Sent you the LSP logs.

**Comment by dibarbet** [comment] 2020-11-20 22:52
https://github.com/dotnet/roslyn/issues/49528 causes the yellow bar.

The root cause of the shutdown is we're getting asked about non-generated-razor documents in an LSP server that only knows about generated razordocuments.  This is supposed to be handled via client name we set on our server - the LSP client should only be asking our server about buffers that have a matching client.

**Comment by dibarbet** [comment] 2021-02-01 19:14
fixed by https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/289294

**Closed by dibarbet** 2021-02-01 19:14 UTC
Labels: Area-IDE, Bug, CloudEnv
