### ISSUE TITLE
Productivity: Completion should have a way to see items there is no using/reference for

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7053] opened 2015-11-25 20:12 UTC

**Comment by dfkeenan** [comment] 2016-04-23 02:23
This would be pretty good. For example extension methods. I always for get to add the using statement for "System.Data.Entity" which gives you a bunch more extension methods for Entity Framework.

I think it definitely needs some visual cue as to whether or not a using and/or reference needs to be added.  Also need to be careful about how much is included.  With fuzzy matching you could include a whole bunch of symbols which might be more confusing than helpful.  I am not sure how the filtering/fuzzy matching is done. Some sort of distance function i.e. Levenshtein distance? But for symbols that are not already accessible there should probably be some minimum match quality before a symbol is included. Maybe this could be user configurable.

Or am I just making things more complicated than they need to be??

**Comment by Pilchie** [comment] 2016-05-10 15:27
@dfkeenan I think we'll definitely have to be careful, and provide some indication that a significant operation (adding a nuget package, reference, or using) is also going to happen.  I'm less excited about the idea of making the match quality a user configurable thing though...

**Comment by dfkeenan** [comment] 2016-05-10 23:18
@Pilchie I was just throwing ideas out there.  As long as the match quality threshold is well balanced there is no need to make it user configurable.

**Comment by jankratochvilcz** [comment] 2016-09-27 09:09
Would love to see this bumped :-). After not using Resharper for a month now, this is definitely the most important feature I miss, it speeds up writing code a ton!

**Comment by sunxinzhe2012** [comment] 2017-06-13 09:07
@DustinCampbell   this feature is so important for us, nearly two years since this issues created,do you have any plans? so thanks!

**Comment by DustinCampbell** [comment] 2017-06-13 13:51
@Pilchie, @kuhlenh: We made several IntelliSense improvements for D15 and D15.3. Is this moving further up our list now?

**Comment by sunxinzhe2012** [comment] 2017-07-12 03:47
@DustinCampbell @Pilchie @kuhlenh any news?cry cry cry......

**Comment by kuhlenh** [comment] 2017-07-12 16:36
@sunxinzhe2012 added the milestone. This is definitely near the top of our backlog :)

**Comment by sunxinzhe2012** [comment] 2017-07-13 02:25
@kuhlenh  oh yeah,good job,tk u and your team!

**Comment by sujaysarma** [comment] 2017-07-28 18:11
+1 on this as per mail thread.

**Comment by rchande** [comment] 2017-10-03 22:54
Thoughts:
* Add Using builds up some table of type -> namespace. We would probably want completion to pull from the same data. I'm not sure if that table is built up incrementally and stored forever, or if we only add entries when Add Using requests the namespace for a missing type.
* To avoid showing a massive and cluttered list, we might want to add items without usings once there are no filter matches (or something). We don't currently have a mechanism for doing this. Eg, list starts out showing only locals, the user doesn't find a match and we retrigger the list to include locals and class member

**Comment by onovotny** [comment] 2017-10-11 19:38
Is there anything that can be done to get this pulled into 15.5 or another 15.x release? This is the last major thing I use ReSharper for...

**Comment by CyrusNajmabadi** [comment] 2017-10-11 22:06
@rchande 

> Add Using builds up some table of type -> namespace

I don't think such a table would be necessary.  We could certainly just populate the list with the known typenames that the AssemblySymbol already exposes.  Then, we could lazily find that type for the description when it is shown.  

Now, if we want to also show the import that will be added, we would need to know the containing namespace for the type.

This is not currently easily exposed, but it could be if we update the declaration-table at the compiler layer appropriately.  i.e. the compiler knows exactly what namespace the type is in when it builds the TypeNames collection.  We could have a TypeName-to-Container map that gets created as well and exposed from assembly symbols.

The benefit here is that this is already in the declaration table, is extremely cheap, and is easy to keep up to date.  Importantly, it does not cause symbols to be created, and it does not require walking the entire symbol.

**Comment by CyrusNajmabadi** [comment] 2017-10-11 22:08
> To avoid showing a massive and cluttered list, we might want to add items without usings once there are no filter matches

That.  Or there could be a new chord that creates this sort of list.  i.e. instead of ctrl-space, ctrl-shift-space.

Also, i'm skeptical that "a massive and cluttered list" is actually a problem.  Today, it's easy to get into a situation where you have a dozen or so imports, and the list already contains 10k+ entries.  At this point the list is already massive and cluttered.  So having more entries doesn't really change anything.  I think what is relevant is that the list not feel cluttered once the user starts filtering things down.  And that will take a bit of experimentation to see if there actually is an issue or not.   My gut tells me 'no'.  But we'd need to see.

**Comment by onovotny** [comment] 2017-10-11 22:30
I would not want an extra chord. I like the way R# presents the types that need an import -- the types are there:

`FrobModel (MyProduct.Models)`. The parentheses only exists for types that are not in scope, so it's obvious. The namespace is not used in camelCase/PascalCase filtering, it's just for display.

I don't think type pollution would be a problem.

Limiting to only being after the filter is expired also impedes discovery. The whole point is that I don't know/fully remember the type name (or am too lazy to use the import).

The completion should add the using statement too (if that wasn't already obvious).

**Comment by CyrusNajmabadi** [comment] 2017-10-11 22:55
> Limiting to only being after the filter is expired also impedes discovery. 

Discovery seems hard no matter what.  Your list will have 100s of thousands of items in it.  How do you discover anything of value in that, unless you are filtering down to things you think are are relevant?

**Comment by CyrusNajmabadi** [comment] 2017-10-11 22:55
> The completion should add the using statement too (if that wasn't already obvious).

That is the feature :)

**Comment by CyrusNajmabadi** [comment] 2017-10-11 22:57
> I would not want an extra chord. I like the way R#  ...

I'm a bit confused.  Resharper does this through chording.  They have "basic completion": https://www.jetbrains.com/help/resharper/Coding_Assistance__Code_Completion__Symbol.html and "import symbol completion" https://www.jetbrains.com/help/resharper/Coding_Assistance__Code_Completion__Type_Name.html

You can configure if import_symbol_completion is included in basic_completion or not.  

This provides flexibility for users who may want this, but may also want our existing behavior.

**Comment by olegtk** [comment] 2017-10-11 23:14
Would the list also include all types in NuGet packages (you already collect them for the LightBulb anyway)?

**Comment by onovotny** [comment] 2017-10-11 23:25
Here's what I have:

![image](https://user-images.githubusercontent.com/1427284/31471585-7b49caee-aeb7-11e7-9a43-b4e16caaa3b5.png)

The completion behavior is around getting an exact match or not.
It shows imported types first: 
![image](https://user-images.githubusercontent.com/1427284/31471976-dca6c970-aeb9-11e7-91ac-ce849626f8dc.png)

Then ones it can see in the transitive closure of packages/projects:
![image](https://user-images.githubusercontent.com/1427284/31471991-f3d2ceaa-aeb9-11e7-9adf-fc530ba344bb.png)


It should not include NuGet packages, that would be too noisy.

**Comment by sujaysarma** [comment] 2018-02-19 06:41
This one seems to have been implemented. @Pilchie I have emailed you about this a few minutes ago. It works in Microsoft (R) Roslyn C# Compiler version 2.7.0.62608.

**Comment by onovotny** [comment] 2018-02-19 14:00
@sujaysarma what exactly works and in what version of VS?

**Comment by sujaysarma** [comment] 2018-02-19 14:13
This feature. 

Recognizing keywords from unreferenced libraries, 
Doing that lexically (through spelling-mistakes and all)
Providing the suggestion to add the appropriate Nuget package / assembly / using statement as required

I dont know the version it was first implemented in. I noticed it in Roslyn C# Compiler v2.7.0.62608 (as shipped with VS 2017 15.6.0 Preview 5.0.)

**Comment by onovotny** [comment] 2018-02-19 14:17
Suggesting types in NuGet packages has been there for a while. The feature here is to have types from referenced assemblies, but not yet in scope, appear in the IntelliSense and have the using statement automatically added. That has not been implemented yet, AFAIK. It's not about the quick-fix after you finish typing the symbol.

**Comment by sujaysarma** [comment] 2018-02-19 14:24
@onovotny My comment is not in reference to the discussion you've been having here, I am referencing something a discussion I had with @Pilchie on email.

**Comment by Neme12** [comment] 2018-10-29 18:50
from https://github.com/dotnet/roslyn/issues/30462#issuecomment-434003255, @CyrusNajmabadi :
> @genlu Possibly. Though i would strongly ask that that be a different keybinding to include in the list. THe 'auto-add imports' feature exists in VSCode with TypeScript and it's very frustrating. It often makes things appear that i wouldn't want to import, but it's hard to realize that it's not a real member. You then end up with random imports later that you ahve to get rid of and then refix the code.

I agree. I find this very frustrating in other IDEs when they automatically add imports that I didn't intend to use. I hope there will be a separate key / button / completion-list for this.

**Comment by Neme12** [comment] 2018-10-29 18:55
Maybe there could be space for another toggle button at the bottom of the completion list:
![image](https://user-images.githubusercontent.com/11444821/47673281-70ed5b80-dbb4-11e8-8ddf-5396b9773952.png)
(although it should probably stand out more or be visually separated from the other buttons)

**Comment by genlu** [comment] 2019-02-25 21:10
So based on the discussions (both here and we had internally), it seems people generally agree on what this feature would do, i.e. show unimported types in completion list (as well as extension methods in a unimported type, when in appropriate context) and add using when such an item is selected. It's just a matter of how to trigger it that we are still arguing.

Looking at the screenshot from @onovotny above:
1. resharper provides a separate shortcut for "import completion"
2. resharper provides an option to show "import completion" items in basic completion list, which basically replace basic completion with "import completion"

These seems reasonable and should provide enough flexibility to address the triggering issue for many people. Additionally, I like @Neme12's proposal of an additional filter in the "import completion" list. it would be helpful for users using"import completion" as their basic completion list but want to browse only available types occasionally. So I'm inclining to adopt them all in this feature in VS. Thoughts?

**Comment by genlu** [comment] 2019-02-25 21:54
> This is not currently easily exposed, but it could be if we update the declaration-table at the compiler layer appropriately. i.e. the compiler knows exactly what namespace the type is in when it builds the TypeNames collection. We could have a TypeName-to-Container map that gets created as well and exposed from assembly symbols.

@CyrusNajmabadi I like this idea, it would avoid many potential perf issues of approaches that rely on creating symbols. However there's a couple issues:
1.  we don't know if the type is actually accessible in current context
2.  this doesn't provide "import completion" for extension methods.

I don't know how declaration table works, will need to take a look. But it seems the issue above could be addressed by additional flags for each type name (e.g. is it static/internal/protected/private/etc.), and creating/caching symbols for at least some of those types would be unavoidable.

**Comment by CyrusNajmabadi** [comment] 2019-02-25 22:32
>     2\. this doesn't provide "import completion" for extension methods.

This will likely require a different approach. And it's likely going to be expensive.  Essentially, you'll have to check every extension method in the world to see "are you applicable to me?".  

> I don't know how declaration table works, will need to take a look. But it seems the issue above could be addressed by additional flags for each type name (e.g. is it static/internal/etc.)

yes.  it's likely there could be syntactic information placed in the decl table to help out.  

>  and creating/caching symbols for at least some of those types would be unavoidable.

I don't know what it means by 'caching', but it's extremely scary :)

**Comment by onovotny** [comment] 2019-02-26 13:31
> resharper provides an option to show "import completion" items in basic completion list, which basically replace basic completion with "import completion

One thought here, and certainly the usability team can decide this, but Resharper has this option enabled by default as it aides in discovery productivity. People can clearly disable that if they don't like it though, but I have no data, anecdotal or otherwise, on what people actually do.

**Comment by genlu** [comment] 2019-02-28 18:17
@CyrusNajmabadi 
> yes. it's likely there could be syntactic information placed in the decl table to help out.

I have been hacking around DeclarationTable and implemented a prototype for a type-only import completion, it seems all the information needed to create a `ConmpletionItem` can be all obtained from syntactic info from DT (w/o creating any symbols), which is very promising. However, this doesn't help us at all for declarations from PE. Will discuss with compiler folks to explore this further.

> This will likely require a different approach. And it's likely going to be expensive. Essentially, you'll have to check every extension method in the world to see "are you applicable to me?".

Yup, this likely will be a separate provider backed by some sort of map.

@onovotny 
> ... but Resharper has this option enabled by default as it aides in discovery productivity

agreed, people will definitely noticed it if turned on by default ;) 
And as you said, if we do so, then sorting and the ability to filter them out with a keyboard shortcut would be very important.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 18:26
> However, this doesn't help us at all for declarations from PE. Will discuss with compiler folks to explore this further. FYI @jcouv

IDE already does metadata reading to create indices for metadata.  I would recommend you either reuse the existing indices, or just take the same path to build whatever appropriate index you need for your use case. 

THe major benefit here is that you don't need to recompute much since metadata rarely changes.  You then use the index primarily, and you only look up symbols as necessary (i.e. when a user selects the item in the completion list) to save on cost.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 18:26
> Yup, this likely will be a separate provider backed by some sort of map

I'm not certain waht that means.  what is 'some sort of map'?

**Comment by genlu** [comment] 2019-02-28 18:34
> IDE already does metadata reading to create indices for metadata.

@jcouv mentioned something similar might exist in compiler too. 

> I'm not certain waht that means. what is 'some sort of map'?

I haven't thought about this much yet. But it seems at minimum we'd need to keep track of what extension methods are available, grouped by extended types and projects. (maybe using something like `SymbolKey`?)

Also 
> Then, we could lazily find that type for the description when it is shown.

It would definitely make it simpler if we can lazily get the description by asking for a symbol, instead of creating and tagging the text up front. But I'm not familiar with how we interact with editor. Is a lazy API even available today?

**Comment by onovotny** [comment] 2019-02-28 18:45
Not sure how the pieces all fit together, but I also think it's important that this work with XAML-based editors -- the xml prefixes. That's another area where IntelliSense includes the types not directly in scope and it's extremely helpful to have it complete/insert the right namespaces.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 18:49
> grouped by extended type

I'm not sure what that would mean.  But it sounds expensive.  You'd have to go realize all the symbols for the extended type.  avoiding the symbolic construction here across the universe of all types is key.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 18:49
> Not sure how the pieces all fit together, but I also think it's important that this work with XAML-based editors -- the xml prefixes. That's another area where IntelliSense includes the types not directly in scope and it's extremely helpful to have it complete/insert the right namespaces

@onovotny that's totally unrelated.  You'll have to take it up with whoever owns the xml editor experiences.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 18:52
> @jcouv mentioned something similar might exist in compiler too.

Last time i checked, there wasn't much interest in exposing any lower level metadata info from the compiler.

>  Is a lazy API even available today?

Yes.  Computation of completion-item descriptions is already done lazily and in an async fashion today.  This is supported in a first-class manner in teh Roslyn completion API.  I can point you to whatever info you need here if you can't find it :)

**Comment by genlu** [comment] 2019-02-28 19:02
> ast time i checked, there wasn't much interest in exposing any lower level metadata info from the compiler.

Hmm.. we will see how it goes

> I'm not sure what that would mean. But it sounds expensive. You'd have to go realize all the symbols for the extended type. avoiding the symbolic construction here across the universe of all types is key.

I don't think that would be necessary. DeclarationTable already has information whether a type declaration contains member with extension method syntax. We only need to construct symbols for those members. Maybe this can be done on background as solution crawler?

>  I can point you to whatever info you need here if you can't find it :)

Thanks! It might be easier for me to turn my head and talk to @ivanbasov  :)

**Comment by CyrusNajmabadi** [comment] 2019-02-28 19:08
> DeclarationTable already has information whether a type declaration contains member with extension method syntax. We only need to construct symbols for those members. Maybe this can be done on background as solution crawler

There are a *lot* of extension methods.  This is not cheap :)

>Maybe this can be done on background as solution crawler

This needs to be done as part of completion, with the solution snapshot you are currently working with.  So that means it needs to be fast.  We can build indices that are easy to maintain (i.e. the decl table, or hte IDE metadata tables) such that we can then usse that index to limit what we examine in the solution.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 19:08
Note: happy to discuss more in gitter.  it might be more conducive.

**Comment by onovotny** [comment] 2019-02-28 20:04
Not sure what the perf impact is, but there's an extension that attempts to do some of this here:
https://marketplace.visualstudio.com/items?itemName=Dreamescaper.IntelliSenseExtender
https://github.com/Dreamescaper/IntelliSenseExtender

There are some good ideas in it about the way its suggestions are prioritized.

**Comment by CyrusNajmabadi** [comment] 2019-02-28 20:20
Note: perf is *the* feature here.  Completion is under an extremely tight budget, and generally there has been very little headroom for growth (unless VS has changed it's min cpu requirements).  We have to be very careful here as slowdowns are very perceptible and impactful.

It's important to understand that completion is a *blocking* feature in roslyn.  so if you end up putting in something slow, it will deeply impact the user.  That's because we want muscle memory to work.  so you need to be able to type `Con.WL<tab>` and have that always come out with `Console.WriteLine`.  So, when completion is computed/committed, it's always doing the full computation (once the project is loaded).  That way you can get the same results consistently.  Because you may type anything else after this (including things that bring up new completoin lists), these contents themselves need to be computed and committed into the tree.

Because of this, there is likely only 5-10ms total headroom to do all this new work.

**Comment by duki994** [comment] 2019-03-01 08:31
@CyrusNajmabadi

This performance feature is already implemented in many IDEs and tools via startup caching of system assemblies of respective SDK used (.NET Core 2.2 for example).
Let's say you cache types and their respective namespaces on start of project.
Then fuzzy search on cached table.

I think JetBrains products already do this kind of stuff in a similar way.
There's also extension for file search caching for Visual Studio Code which relies on similar principle.

Both ideas implemented in largely different languages (Java and JavaScript) with different programming perspective.


My standpoint is to cache types and respective namespaces when starting a workspace (in any editor or IDE supporting Roslyn) and provide statistics based completion.
Also there can be a flag or switch for this feature, because for very large solutions caching will slow down workload.

**Comment by CyrusNajmabadi** [comment] 2019-03-01 08:51
@duki994 

> This performance feature is already implemented in many IDEs

Many IDEs do this in a manner that blows past the perf goals that Roslyn and VS have.  There are a wide range of machines that VS has to support, and there are strict budgets here.  

>  via startup caching of system assemblies of respective SDK used (.NET Core 2.2 for example).

1. you have to build those caches.  part of the discussion i'm having with @genlu  (which we took to gitter) was on how we could do that effectively.
2. caching of assemblies is something Roslyn already does.  But it only helps for metadata info.  It doesn't help for source info.  There needs to be an efficient mechanism for that.

> Let's say you cache types and their respective namespaces on start of project.
> Then fuzzy search on cached table.

Yes.  This is exactly what i'm conversing with gen on.  How such an index could work.  Specifically, what data it would contain.  When it would be built.  When it would get updated.  How that data would lead to accurate results being proferred for things like extension methods, etc.

--

The point i'm making is that this needs to be done in a manner so that these values can be offered in completion, but in a way that does not affect perf goals.  So, the entirety of searching any index and figuring out what needs to be shown, will likely have a hard cap of 5ms.  In that amount of time, a lot of effort needs to be put into figuring out what shape the caches/indices will have, figuring out how to efficiently query them, and figuring out how to efficiently keep them up to date.  

Note that this is particularly problematic for extension methods.  Imagine a solution where there are 10,000 extension methods available.  When you bring up completion on an arbitrary expr `...expr<dot>`, how can you efficiently (i.e. in less than 5ms) find all the relevant extension methods and add them to the completion list.

**Comment by Dreamescaper** [comment] 2019-03-03 20:06
Hi guys! I've created extension mentioned higher, and decided to share some thoughts here.

I simply traverse all available types starting from GlobalNamespace, and while that's obviously suboptimal, that turned out to be not the slowest part.
Most of the time I spend creating CompletionItem objects.

So having project with ~12k types available total ProvideCompletionsAsync method execution is ~80ms, and of that ~50ms takes to create CompletionItem object. And half of that time takes to create ImmutableDictionary with 2 items for Properties.

That doesn't apply to extension methods, obviously - there I check every single type, filter by MightContainExtensionMethods, and then check every single method. On same project it takes ~40ms for ProvideCompletionsAsync method execution, and creating CompletionItems does not make a difference - there's usually up to 200 methods added.



Maybe it would make sense to add those unimported completions without blocking IntelliSense - show all usual items as fast as possible, and add unimported whenever they are ready. That would make sense if all unimported completions would be sorted _after_ regular ones - to avoid items order breaking when they are added (and it is less clutter in such way, imho)

**Comment by CyrusNajmabadi** [comment] 2019-03-03 21:03
> Maybe it would make sense to add those unimported completions without blocking IntelliSense 

Possibly.  Though: 

1. This means that muscle memory may suffer.
2. It's not clear to me if the completion experience will be acceptable.  

Let's consider 2.  Imagine if itmes are being added to the list as it's up.  What happens with the selection in hte list?  Should it change as new items are added (and may match better what the user typed)?  If so, that means you might go to commit an item, but then commit something else.  If not, that means you'd need some other way to find and select the new items (like typing/removing some chars).

**Comment by duki994** [comment] 2019-03-04 08:10
@CyrusNajmabadi 

Muscle memory isn't a problem. In my colleagues experience, and many other's experience, it's not a problem.

#### A very biased view
Because when we think of feature, we will start typing what we thought. And usually all those tools that are statistics ordering based (more CPU and memory though) and those are only ordering based work really good and seem intuitive. Statistics on working on neural level beats muscle memory always. period.

I always error out when using stock IntelliSense in VS based on roslyn. Always choose wrong completion item. Once I used extension based on statistics that completes IntelliSense (IntelliCode in experimental stage) I never had error. Neither all of my colleagues. It's just that neural thinking patterns beat muscle memory in our hands. Statistics is just a tool that best does the job at the expense of some performance.


#### Brainstorming
Actually any kind of order is needed. Brain will accommodate that change really fast. In less then a day.
From performance perspective only sort needs to be added. Binary/Ordinal sort is fastest afaik.

I'd write performance critical code in pure C, but there is probably no way Roslyn can incorporate that (maybe via wrappers, but wrappers are perf critical on small running tasks).

**Comment by jnm2** [comment] 2019-03-04 12:38
> It's just that neural thinking patterns beat muscle memory in our hands.

Muscle memory is literally the same thing as "neural thinking patterns."

**Comment by jnm2** [comment] 2019-03-04 12:47
@duki994 

> It's just that neural thinking patterns beat muscle memory in our hands.

Muscle memory is literally the same thing as "neural thinking patterns."

Having switched cold-turkey from QWERTY to touch-typed COLEMAK, I can vouch for the slowness of change in muscle memory. It's *possible* to be consciously aware of every slight motor movement in my fingers, think through it, and override it—it's just painfully slow. For two months there, I was constantly forced out of the zone because as soon as I was in it, I started typing what looked like Welsh.

I've had similar experiences on a smaller scale with the ordering of Ctrl+. refactorings. I have to say though, my expectations frequently don't match reality when I autocomplete without waiting to visually verify the selected intellisense memory. I have to erase and try again and the second time, stop typing until I see what intellisense came up with before typing the next punctuation character. This means that I have only very weak muscle memory for intellisense compared to something like Ctrl+. However, I'm sure there are people with very strong muscle memory for intellisense.

**Comment by Dreamescaper** [comment] 2019-03-04 14:09
@jnm2
Personally I don't understand how proper muscle memory for types IntelliSense might develop.
I mean - list is always different depending on current usings, referenced projects etc.
So I always need to visually validate what is pre-selected.

So IMHO - muscle memory considerations are not that critical here, at least for types.
(It probably applies better for methods)

**Comment by CyrusNajmabadi** [comment] 2019-03-04 18:52
> Muscle memory isn't a problem. In my colleagues experience, and many other's experience, it's not a problem.

It is a problem.  We've broken this stuff in the past.  And we get feedback across the board when it happens.  The Roslyn team itself complains, as does internal users at MS.  And, when external people encounter this, they complain too.

Heck, we're fixing several muscle-memory problem introduced this release (including by me) by taking critical 16.0 fix instead of waiting for 16.1.  That's because lots of feedback has already come in how the IDE is not behaving in the manner users have grown accustomed to.  

--

Please do not marginalize this problem.  The IDE team has decades of info showing how negatively this can impact people, and it is taken seriously.

**Comment by CyrusNajmabadi** [comment] 2019-03-04 18:55
> Personally I don't understand how proper muscle memory for types IntelliSense might develop.
I mean - list is always different depending on current usings, referenced projects etc.
So I always need to visually validate what is pre-selected.

People grow very accustomed to how things like search/filtering behave, and they build up enough experience to be able to internalize "if i write these N characters, then i will get the right results 100% of the time in my projects".  Those `N` characters then become the `effective shorthand name` for any potential symbol (or sequence of symbols) for the user.  

Disregarding this is not acceptable.  We know this happens *first hand*.  When we break it, we start getting reports almost immediately from people saying "you have regressed the typing experience i have grown to depend on".  

To make it absolutely clear: we consider this part of hte deliverable for IntelliSense.  It's not something tacked on, and it's not something we change lightly.

**Comment by genlu** [comment] 2019-03-11 19:16
Notes for design meeting discussion:

1. Need a separate shortcut for import-completion
2. Need an option to show import-completion items in basic completion list
3. Need a new filter in completion list to quickly hide/show import-completion items
4. What would be the default mode?
5. Sorting. We will show in scope items above import-completion items (for those with identical matching score)
6. Behavior when data required by import-completion isn't fully available. For example, it might take some time to build the index to filter extension methods from scratch. We might just silently not showing items for extension methods in this case.

**Comment by heejaechang** [comment] 2019-03-26 04:08
@gnelu let me know if you want to have a prototype in with feature flags and get people feedbacks from dogfooding before we bake in too much based on speculations including perf optimization based on speculations.

we can also do A/B testing to find out what options is actually improving typing experiences.

once we have a basic covered (80%) with 20% effort, we should start dogfooding and get telemetry and incrementally improve features based on feedbacks and telemetry/usage data.

**Comment by CyrusNajmabadi** [comment] 2019-03-26 15:40
FYI @heejaechang we're actually just profiling the scenario.  So the changes are being driven by non speculative information. Thanks!

**Comment by genlu** [comment] 2019-03-26 23:41
@heejaechang Thanks, I will sync with you offline to learn how I can take advantage of feature flag.

**Comment by Dreamescaper** [comment] 2019-04-13 22:17
One concern after testing PR from @genlu .
Currently all completion items are sorted alphabetically - both unimported and regular ones. And it makes regular items of much lower priority. 
E.g. if I have property `ListOfNames`, and I start typing `Li`, I see bunch of items like `LicenceSomething` from some unimported namespace. So I need to type much more to have target item pre-selected or even visible.
I would expect that regular items have higher priority, than unimported ones - probably they should be sorted after regular ones, not sure if there's other options.

wdyt?

**Comment by onovotny** [comment] 2019-04-13 22:32
I agree that in scope items should be before the unimported ones. And the namespace of the unimported one should be in parenthesis of the list to show where it’s coming from.

**Comment by genlu** [comment] 2019-04-15 16:42
@Dreamescaper Thanks for the feedback! And I agree with you, we need to prioritize in-scope symbols in completion list to make it usable. I will fix that. Other other hand, have you noticed any perf regression in typing (which has been the main focus of the PR, so I'm curious)?

@onovotny Are you suggesting to add parenthesis to the greyed-out namespace text?

![image](https://user-images.githubusercontent.com/788783/56150034-c222b900-5f62-11e9-8748-8730c962a134.png)

**Comment by onovotny** [comment] 2019-04-15 16:46
> @onovotny Are you suggesting to add parenthesis to the greyed-out namespace text?

Yes, for two reasons:

1. I think it may help make it more clear that it's not currently in scope. It's a bigger visual indicator, especially when the completion window is narrower.
2. That's what ReSharper does, likley for the prior reason

**Comment by genlu** [comment] 2019-04-15 16:59
OK, I will take your feedback in to account. Thanks! :)

**Comment by genlu** [comment] 2019-04-17 04:19
Completion for unimported types is implemented by #34808. Currently we only have an option to enable/disable it in completion list. New short cut OR new filter will come in a later update (but not both, and we are still debating internally which way to go).

**Comment by genlu** [comment] 2019-04-17 04:21
@onovotny FYI I didn't add parenthesis to namespace in current implementation. Will wait for more feedbacks until making a final decision.

**Comment by jnm2** [comment] 2019-04-17 13:05
@genlu If you don't prefer parentheses, what about something like `+System.Collections.Immutable` to make it clearer that autocompleting that item will be adding a using directive?

**Comment by genlu** [comment] 2019-04-17 16:57
@jnm2 I thin that's reasonable too

**Comment by Dreamescaper** [comment] 2019-04-18 10:35
@genlu 
Found minor issue with type completions. Used sort text (`"~{0}~{1}"`) makes type with shorter name go after longer one, e.g. now 'SomeTypeWithLongerName' < 'SomeType'.
Probably smth like `"~{0} {1}"` or `"~{0}!{1}"` should be used.

**Comment by genlu** [comment] 2019-04-18 19:53
@Dreamescaper Ah, I see. Will fix. Thanks!

**Comment by Dreamescaper** [comment] 2019-04-19 14:09
Found another usability issue.
For some reason it tends to pre-select import completions over regular one.
![image](https://user-images.githubusercontent.com/17177729/56427836-ee716900-62c5-11e9-92a7-b2d03e09fad0.png)

**Comment by CyrusNajmabadi** [comment] 2019-04-19 16:51
Great catch @Dreamescaper .  Def something we'll want to look into improving @genlu .  Completion items rules have a match priority.  We might want to make these negative to indicate they have less priority than a match with any normal (`0`) item.

**Comment by genlu** [comment] 2019-04-20 00:45
@CyrusNajmabadi Making the match priority for import items lower probably wouldn't help in this particular case, I think the reason that the import item is considered a better match is because it doesn't have the `<>` suffix, [CompareMatch](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionHelper.cs,214) uses the entire display text which includes the suffix.

**Comment by genlu** [comment] 2019-04-20 00:50
@Dreamescaper I have created a bug to track this #35163

**Comment by CyrusNajmabadi** [comment] 2019-04-20 01:15
> CompareMatch uses the entire display text which includes the suffix.

That seems strange to me.  We likely need to rethink some of the logic here :)

**Comment by genlu** [comment] 2019-04-23 17:53
Since the change for type only import completion was merged, I'm closing this long running issue. #35059 and #35060 are used to track the remaining feature work. Feel free to comment on this issue or open new issues if you have any feedback for this feature. Thanks!

**Closed by genlu** 2019-04-23 17:53 UTC
Labels: Area-IDE, Feature Request, InternalAsk

**Comment by YairHalberstadt** [comment] 2019-05-22 13:01
I started using this today and it's fantastic!

Thanks for all your hard work!

**Comment by chucker** [comment] 2019-05-22 16:24
Pretty cool indeed. Should we file problems we encounter as separate issues?

**Comment by genlu** [comment] 2019-05-22 17:06
@YairHalberstadt @chucker 
Thanks for trying this new feature out :) 
And yes, creating new issues for any feedback/bug is preferred, but I will keep an eye on this thread as well.

**Comment by oliverjanik** [comment] 2019-06-28 08:38
How do I enable this feature? What version of VS will this be in?

**Comment by chucker** [comment] 2019-06-28 19:20
@oliverjanik it's shipping (as opt-in) in VS 2019 16.1. https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#net-productivity
