### ISSUE TITLE
Version of roslyn included in VS 2015 CTP 6 results in missing PublicKeyToken in a reference

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/roslyn#2175] opened 2015-04-22 05:56 UTC
Running this https://github.com/Particular/docs.particular.net/tree/master/samples/encryption/basic-encryption/Version_3.3 in VS 2015 CTP 6 results in a `FileLoadException`

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Additional information: Could not load file or assembly
'NServiceBus.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. 
(Exception from HRESULT: 0x80131040)
```

This is because Roslyn incorrectly includes a reference that is missing the strong name for `NServiceBus.Core`. Here are the resulting references

```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
NServiceBus.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null
NServiceBus, Version=3.3.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
```

I note that in version 0.7.4032713 of Roslyn this problem does not manifest. So applying this to every project

    Install-Package Microsoft.Net.ToolsetCompilers -Pre

Results in the references being correct

```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
NServiceBus.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
NServiceBus, Version=3.3.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
```

And the project running correctly.

### So why raise this issue if it is fixed? 

I want to ensure that this is a known issue that has been knowingly fixed so we can be certain no regression occurs in a future version.

I also want to know if there is something specific about `NServiceBus.Core.dll` that is causing the problem to manifest for that assembly.

**Comment by Pilchie** [comment] 2015-10-23 16:44
Looks like this was an issue with an older compiler that is now fixed?

**Comment by gafter** [comment] 2015-10-24 19:23
@SimonCropp Would you care to contribute a unit test or regression test to Roslyn?

**Comment by SimonCropp** [comment] 2015-10-24 21:53
@gafter other than the full repro i could not isolate a specific test

**Comment by gafter** [comment] 2015-10-26 00:42
As this is not reproducible in VS2015 RTM, closing.

**Closed by gafter** 2015-10-26 00:42 UTC
Labels: API, Area-Compilers
