### ISSUE TITLE
Intellisense suggests an overridden property twice when used as attribute argument

### ISSUE THREAD

**Issue by roydukkey** [dotnet/roslyn#12544] opened 2016-07-15 00:45 UTC
**Version Used**:

Microsoft Visual Studio Community 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
[Full IDE Report](https://gist.github.com/roydukkey/67ef3cc4e65b915a91c14310e828066e)

**Steps to Reproduce**:
1. Create new 'Class Library (.NET Core)' project
2. Add the following attribute definitions:
   
   ``` csharp
   class BaseAttribute : Attribute
   {
       public virtual string Name { get; set; }
   }
   
   class DerivedAttribute : BaseAttribute
   {
       public override string Name { get; set; }
   }
   ```
3. Add `[Derived()]` attribute to something
4. Delete `(` and retype `(` to enable Intellisense suggestion.

**Expected Behavior**:

Intellisense should show only the override property information.

**Actual Behavior**:

![untitled](https://cloud.githubusercontent.com/assets/1509616/16860127/146cf752-4a03-11e6-94a2-9c1312534797.png)

**Comments**

This issue is also found on [StackOverflow](http://stackoverflow.com/questions/35532304) and #9398.

**Comment by Shiney** [comment] 2016-08-07 13:43
In the code this feature is called SignatureHelp not Intellisense.

**Comment by mikkelbu** [comment] 2018-06-15 20:13
@gafter, @DustinCampbell This looks like a duplicate of #23664 (or vice versa).

**Closed** 2020-03-02 05:47 UTC
Labels: Area-IDE, Bug, help wanted
