### ISSUE TITLE
IntelliSense adds unneeded generic arguments when writing a generic type name if the arguments are already present 

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#7805] opened 2016-01-06 18:27 UTC
**Repro**:

Declare the following class:

```csharp
class A<T> { }
```

Then write the following code in a method:

```csharp
A<int> a = new <int>();
```

Position the caret right before the second `<` character, invoke IntelliSense (e.g. `Alt+Enter`).

**Expected result**:

IntelliSense should suggest some form of `A` that, when selected, results in the following:

```csharp
A<int> a = new A<int>();
```

**Actual result**:

IntelliSense suggests `A<int>`; selecting that option results in the following (clearly incorrect) code:

```csharp
A<int> a = new A<int><int>();
```

The correct option is also suggested (as `A<>`) and works correctly if manually selected, but the incorrect option is selected by default.

---

Some context, since this does seem a bit far-fetched: I was editing a property after changing it from `List<int>` to `HashSet<int>`, and I wanted to fix an invocation of `new List<int>()`, so I selected `List`, deleted it, then begain to type `Ha...` and accepted the IntelliSense suggestion, which produced invalid code.

**Comment by rchande** [comment] 2016-01-08 22:13
Generally, IntelliSense tries to ignore text to the right of the caret position. If you invoke the completion list within an identifier token, it will replace the identifier, but in this case you're invoking it to the left of the less than token, so it would be really unusual for us to replace the "<int>".

I suppose we could try to build that particular heuristic into the code that does completion after "new", but I worry we would wind up with something that sometimes overwrote code you wanted left in place. 
I'm disinclined to make a change that tries to edit the text to the right.

We could perhaps disable "new" completion if there are tokens to the right of the caret, but that would make your rewriting task even harder--right now, if you delete all of "List<int>", "new" completion will do the rest of the work for you.
Thoughts @Pilchie @DustinCampbell?

**Comment by rchande** [comment] 2016-02-02 21:58
@SolalPirelli I'm closing this as "By Design".

**Closed by rchande** 2016-02-02 21:58 UTC
Labels: Area-IDE, Bug
