### ISSUE TITLE
Ref assignments do not update nullable state of assigned variable

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31903] opened 2018-12-18 14:11 UTC
**Version Used**: 

Branch master (28 Oct 2018)
Latest commit bfade8 by Sam Harwell:
Merge pull request #30815 from eladeyal-intel/patch-1

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
public class C {
    public void M(string? p) {
        ref string? v = ref p;
        string s = "";
        v = ref s;
        v.ToString();
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYBuRpgZnYAmCgGEKAb0YVp7AUwAsFALIAKTiwD8FAA4BKCVJlGEcAGbsOmigDcKAXgonz2ngyNH1FKPYoAiX67uMrYOTl6BQTYAdAAqAPYAyjAIAJa4AOYquhHSAL6MuUA

**Expected Behavior**:

No warnings

**Actual Behavior**:

```
warning CS8602: Possible dereference of a null reference.
```

**Comment by jaredpar** [comment] 2019-01-02 17:44
Thanks for filing. This appears to be a dupe of #29954 (CC @jcouv)

**Closed by jaredpar** 2019-01-02 17:44 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
