### ISSUE TITLE
"Indent open and close braces" doesn't affect switch section block

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#20009] opened 2017-06-04 23:14 UTC
When "Indent open and close braces" is unchecked:

**Actual:**
```cs
case 5: 
    {
    }
```
**Expected:**
```
case 5: 
{
}
```

**Comment by CyrusNajmabadi** [comment] 2017-06-04 23:26
What is the following set to:
![image](https://cloud.githubusercontent.com/assets/4564579/26766253/9f5a47ea-4942-11e7-9700-2b63304816b2.png)

?

**Comment by alrz** [comment] 2017-06-04 23:30
@CyrusNajmabadi That indents the whole section,


            switch (a)
            {
                case 1:
                    {
                    }
            }

vs.

            switch (a)
            {
            case 1:
                {
                }
            }

**Comment by CyrusNajmabadi** [comment] 2017-06-04 23:34
Er, sorry:

![image](https://cloud.githubusercontent.com/assets/4564579/26766301/bd6c31de-4943-11e7-8e23-cc4bbd8e164c.png)

**Comment by alrz** [comment] 2017-06-04 23:39
It doesn't indent the block when unchecked but it also leaves statements unindented as well.

How can I have these at the same time:
```cs
case 5 
{
    break;
}
case 6:
    break;
```

**Comment by CyrusNajmabadi** [comment] 2017-06-04 23:43
i don't think we have any facility for that.  Tagging @heejaechang to see how hard it would be to have an option for this.

**Comment by heejaechang** [comment] 2017-06-05 19:47
@basoundr actually added those options. so tagging him to see whether we have an option for it. about supporting what @alrz asking, It should be a matter of just adding one more option if it doesnt already exist.

**Comment by basoundr** [comment] 2017-06-05 21:56
Yes, we cannot do something like that today with the available options. We will need to add an option to support something like this. Don't sure what a good name would be too. "Case Content without braces"?

**Comment by alrz** [comment] 2017-06-05 21:58
Indent case blocks (defaults to true for back-compat)

**Comment by Pilchie** [comment] 2017-06-06 22:17
Also reported https://developercommunity.visualstudio.com/content/problem/65219/visual-studio-2017-c-switch-case-braces-do-not-pre.html.

Are we sure this isn't a regression?  It feels like braces used to be special cased there.

**Comment by miloush** [comment] 2017-06-08 16:53
I am pretty sure the default settings have been always the way reported, i.e. indented with regards to `case`.

It would have been pretty awkward 
```C#
case 1:
    blabla();
{
    foo();
}
    break;
```

unless you are thinking there was a special exception for when the whole case block is marked with braces only. Either way, if it helps, it behaves the same in VS 2010 - as reported.

**Comment by alrz** [comment] 2017-06-16 21:32
> unless you are thinking there was a special exception for when the whole case block is marked with braces only.

Exactly.

**Comment by alrz** [comment] 2017-06-16 21:35
I was looking into it, as it turns out, trivia ain't trivial.

**Comment by tannergooding** [comment] 2017-06-16 21:36
I logged an issue on this over a year ago, it is currently `up for grabs`:
https://github.com/dotnet/roslyn/issues/12304

**Comment by tannergooding** [comment] 2017-06-16 21:38
There might even be a slightly abandoned PR that fixes this (haven't dug back into to validate that is the case, but my convo with @CyrusNajmabadi seems to indicate that was the case): https://github.com/dotnet/roslyn/pull/13264

**Comment by alrz** [comment] 2017-06-16 21:41
Thanks! I think this doesn't really need another option so it should be fixed without public API changes.

**Comment by tannergooding** [comment] 2017-06-16 21:42
Whether or not it gets a new option really depends on whether changing the formatting of existing users using one of the existing options is considered `breaking` (I imagine it may be).

**Comment by alrz** [comment] 2017-06-16 21:53
Yeah, it probably is. But from that CR, it sounds like another option may not be desirable either. 😕

**Comment by tannergooding** [comment] 2017-06-16 22:00
@Pilchie, could you chime in on the "appropriate" direction to take here?

Is adding a new option (like #13264) was doing appropriate? If so, should we ping @viceroypenguin and see if he wants to either pick it back up or hand it off to someone else to complete?

Otherwise, can we determine what does need to be done here so that we can move in the correct direction?

**Comment by CyrusNajmabadi** [comment] 2017-06-16 22:50
It would definitely be breaking.  We have a behavior today around these options and how blocks are handled in a switch.  People may like this behavior and may not want it changed.  I'm totally fine with a new option around this.

**Comment by CyrusNajmabadi** [comment] 2017-06-16 22:52
I think this shoudl be pretty easy to implement.  I'll try to whip up a solution here.

**Comment by CyrusNajmabadi** [comment] 2017-06-16 22:58
open question, what if you say "i don't want blocks indented in case sections, but i do want normal statements indented", what happens with the following:

```c#
switch
{
    case 0:
    {
    }
        break;
}
```

Seems like that would be pretty ugly.  It feels like teh rule is effectively "don't indent if the first statement of a case is a block".  So you'd get:

```c#
switch
{
    case 0:
    {
    }
    break;
}
```

But if you had other statements first, it would be:

```c#
switch
{
    case 0:
        Console.WriteLine();
        {
        }
        break;
}
```

**Comment by alrz** [comment] 2017-06-16 23:07
I was thinking that we should not indent only if the *whole* section is a block. In your example, if we have more statements after block, it won't look quite right.

**Comment by tannergooding** [comment] 2017-06-16 23:52
I'm not sure how frequently users have case statements that are a mix of blocks and not blocks, but "don't indent if the first statement of a case is a block" is probably the best behavior here. At least, I think it looks the most atheistically pleasing for the case where users are mixing (as you gave in your examples above).

Case statements are the only statement (at least that I can think of right now) where you don't have to "explicitly" define the block for multi-line statements. So, I think if the user doesn't define them (At least in my mind), they are effectively there "implicitly". If the user does define them, then we shouldn't implicitly define them ourselves

That is, the following case statements should indent "identically".
```C#
case 0:
    Console.WriteLine();
    {
    }
    break;
```
and
```C#
case 0:
{
    Console.WriteLine();
    {
    }
    break;
}
```

The only case where this breaks down is if the user doesn't define everything within the block. I think in that case, you don't indent as well, because it just looks bad otherwise:
```C#
case 0:
{
    Console.WriteLine();
}
break;

case 0:
{
    Console.WriteLine();
}
Console.WriteLine();
{
    break;
}
```

vs

```C#
case 0:
{
    Console.WriteLine();
}
    break;

case 0:
{
    Console.WriteLine();
}
    Console.WriteLine();
    {
        break;
    }
```

**Comment by alrz** [comment] 2017-06-17 00:01
I think we should leave the case of mixed statement/block as is
```
case 0:
    {
        Console.WriteLine();
    }
    break;

case 1:
    {
       Console.WriteLine();
    }
    Console.WriteLine();
    {
        break;
    }
```

Even if the `break` is the only statement outside of the block it wont look ok
```
case 0:
{
}
break;
case 1: 
```
I'd *prefer* we only do this if the whole section is a single block, but it works for me either way. :+1:

**Comment by CyrusNajmabadi** [comment] 2017-06-17 00:30
PR ready.  Working on tests right now.

**Comment by Pilchie** [comment] 2017-06-19 21:40
Tagging @kuhlenh too.  I generally hate adding options, but I do think this one would be nice.

I still believe that in VS2005 when I wrote formatting that I did special case blocks at the beginning of case statements without an option though :)

**Comment by CyrusNajmabadi** [comment] 2017-06-24 21:11
Fixed with https://github.com/dotnet/roslyn/issues/20292

**Closed by CyrusNajmabadi** 2017-06-24 21:11 UTC
Labels: 4 - In Review, Area-IDE, Feature Request
