### ISSUE TITLE
CSharpRemoveUnreachableCodeDiagnosticAnalyzer contributing to Perf regression during test discovery

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22580] opened 2017-10-06 17:06 UTC

**Comment by sharwell** [comment] 2017-10-06 19:30
The performance overhead here is caused by allocations of a single element array in the following property, adding up to ~3GiB in the performance trace I saw:

https://github.com/dotnet/roslyn/blob/86fd17e9b49160ef72fc1c4001ffceab275e4118/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs#L584-L590

The property is used to define the `Symbol.IsDefinedInSourceTree` method:

https://github.com/dotnet/roslyn/blob/86fd17e9b49160ef72fc1c4001ffceab275e4118/src/Compilers/CSharp/Portable/Symbols/Symbol.cs#L687

The method was then used an equal number of times from the following locations (1GiB allocations each case):

https://github.com/dotnet/roslyn/blob/9da689b5e705672c050bbac63bccd896ba4aefbb/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L2185

https://github.com/dotnet/roslyn/blob/9da689b5e705672c050bbac63bccd896ba4aefbb/src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs#L928

https://github.com/dotnet/roslyn/blob/9da689b5e705672c050bbac63bccd896ba4aefbb/src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs#L243

**Comment by sharwell** [comment] 2017-10-06 19:31
➡️ The initial course of action here is making `Symbol.IsDefinedInSourceTree` a non-allocating method.

**Comment by sharwell** [comment] 2017-10-06 19:35
:memo: Conceptually this new non-allocating method will need to be available outside the compiler core, in order to address issues like #22114.

**Comment by CyrusNajmabadi** [comment] 2017-10-06 22:07
IsDefinedInSourceTree is virtual, and it seems like it could be appropriately overridden as necessary.

**Comment by sharwell** [comment] 2017-10-09 19:26
I'm modifying the return type of `IsDefinedInSourceTree` to be a new value type `SyntaxReferenceCollection`, which allows the benefit to apply in many places where it's used.

**Comment by sharwell** [comment] 2017-11-29 14:55
Closing this as a duplicate of #23462.

**Closed by sharwell** 2017-11-29 14:55 UTC
Labels: Area-IDE, Tenet-Performance, Urgency-Soon
