### ISSUE TITLE
Missing implementation for inline arrays via collection expression

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#69236] opened 2023-07-26 15:09 UTC
**Version Used**: 4.8.0-1.23362.5

**Steps to Reproduce**:
write code like:

```csharp
Buffer dict = [1, 2, 3];

[System.Runtime.CompilerServices.InlineArray(3)]
public struct Buffer
{
    private object _element0;
}
```

**Diagnostic Id**:
CS9174:  Cannot initialize type 'Buffer' with a collection literal because the type is not constructible.

**Expected Behavior**:
No compile error. Lowered (ignoring inline array to span conversion) to maybe something like:

```csharp
Buffer dict = new Buffer();
Span<object> __temp = dict;
__temp[0] = 1;
__temp[1] = 2;
__temp[2] = 3;

[System.Runtime.CompilerServices.InlineArray(3)]
public struct Buffer
{
    private object _element0;
}
```

**Actual Behavior**:
Compile error (see Diagnostic Id)

**Comment by CyrusNajmabadi** [comment] 2023-07-26 15:11
@cston We'd expect thsi to work right?

**Comment by cston** [comment] 2023-07-26 16:27
Yes, it seems reasonable to allow inline arrays as collection expression target types. See https://github.com/dotnet/roslyn/issues/68927.

**Comment by cston** [comment] 2023-08-19 17:36
Closing as duplicate of https://github.com/dotnet/roslyn/issues/68927. Thanks for reporting this @bernd5.

**Closed by cston** 2023-08-19 17:36 UTC
Labels: Bug, Area-Compilers
