### ISSUE TITLE
Intellisence doesn't show method argument when Use expression body for methods

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#37325] opened 2019-07-18 12:41 UTC
**Version Used**: 16.1.6
![pic](https://user-images.githubusercontent.com/2529999/61457892-e2b44200-a99b-11e9-8155-8a26b02b2109.png)
![image](https://user-images.githubusercontent.com/2529999/61458065-58201280-a99c-11e9-9247-673d2097f9c6.png)

**Comment by AmadeusW** [comment] 2019-08-09 16:10
I think that your issue is caused by incorrect setup of the DebuggerTextView when working with expression bodied methods.

Suppose we have a regular method, and user set the breakpoint is over the same piece of code.
```
static void Test(string argument)
{
    Console.WriteLine(argument);XXX
}
```
I recall that the debugger text view is set to display code marked as XXX, where `argument` is in scope.

I suspect that with expression bodied methods, XXX falls outside of the scope of the method, where `argument` is invalid:
```
static void Test(string argument) => Console.WriteLine(argument);XXX
```

My naïve solution would be to rewrite the method to include braces, such that XXX remains in scope.

**Comment by ivanbasov** [comment] 2019-08-10 00:28
Investigated the issue more. It seems there is not problem with the DebuggerTextView and the ApplicableToSpan which is calculated properly.

I made a comparison between a expression-bodied method and a block method in the same situation:
1. https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs#L47
is true for a breakpoint in a block body because IsStatementContext == true

2. Let us assume we fixed issue 1. Then, we would go here
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs#L1529
for symbols. The parameter symbol not returned here.

@gafter , @jcouv and @dotnet/roslyn-compiler please take a look.

**Comment by CyrusNajmabadi** [comment] 2024-10-20 19:55
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-20 19:55 UTC
Labels: Bug, Area-IDE, Area-Compilers, IDE-IntelliSense
