### ISSUE TITLE
StreamJsonRpc.RemoteInvocationException: This program location is thought to be unreachable.

### ISSUE THREAD

**Issue by fantasyz** [dotnet/roslyn#61165] opened 2022-05-06 14:45 UTC
I seeing this almost every day. Seems to be related to find-reference feature.

* C# Unity project
* Visual Studio 2022, 17.1.6
* Windows 10

```
StreamJsonRpc.RemoteInvocationException: This program location is thought to be unreachable.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: This program location is thought to be unreachable.
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.FindReferencesProgressAdapter.<OnDefinitionFoundAsync>d__13.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ReportGroupsAsync>d__13.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.<FindReferencesAsync>d__15.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteFindUsagesService.<>c__DisplayClass3_0.<<FindReferencesAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__15.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2022-05-09 16:15
@ryzngard Could you help me try to find dumps for this?  I still haven't found a good way for prism to seem to get me any.

**Comment by dteske25** [comment] 2022-05-20 13:19
Running into this frequently as well - let me know if there's any info I can provide to help resolve!

**Comment by theolivenbaum** [comment] 2022-06-02 08:45
Happens to me multiple times a day :(

**Comment by ryzngard** [comment] 2022-06-08 20:28
[Internal link](https://prism.vsdata.io/failure/?query=c%3AAbstractFindUsagesService%20fe%3Aide%2Fvbcs%2Fnonfatalwatson&eventType=fault&failureType=hits&failureHash=71e9f9ac-88f3-d02d-0ea7-5d1fe8d8b5f8) for related failure. Assigning back to @CyrusNajmabadi for now

**Comment by CyrusNajmabadi** [comment] 2022-08-23 23:57
Closing out as dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1569045

**Closed by CyrusNajmabadi** 2022-08-23 23:57 UTC
Labels: Area-IDE, Investigation Required

**Comment by d00lar** [comment] 2022-10-20 10:54
co what is the solution ? i have 
401 - Uh-oh, you do not have access. on this @CyrusNajmabadi  link

**Comment by ryzngard** [comment] 2022-10-20 19:43
The public feedback is https://developercommunity.visualstudio.com/t/Find-references-stops-working-due-to-err/10092298

**Comment by d00lar** [comment] 2022-10-21 05:29
so for me it is still happening in lassed vs updated right now.

**Comment by ryzngard** [comment] 2022-10-21 20:47
@d00lar can you provide more information following https://github.com/dotnet/roslyn/blob/main/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md , the original issue was due to a satellite process crashing. You can also use VS to file feedback using `Help > Send Feedback > Report a Problem` and that will make it to our team.

**Comment by ryzngard** [comment] 2022-10-21 20:47
@d00lar oh if it's blazor wasm it might be a separate issue. `Help > Send Feedback > Report a Problem` is probably the next step to help us investigate.
