### ISSUE TITLE
Inline Rename: Cannot type "." when renaming namespace

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/roslyn#38918] opened 2019-09-27 17:55 UTC
**Version Used**: 3.3

**Steps to Reproduce**:

1. Right-click a namespace in any C# file.
2. Select "Rename" menu item.
3. Type a new namespace that include a "." character.

**Expected Behavior**:

You can type or paste a "." character as long as it is a valid namespace string.

**Actual Behavior**:

You cannot type a "." character. If you attempt to paste one, the outline becomes red, and the popup in the corner of the editor says "The new name is not a valid identifier."

**Bonus**: In an ASP.NET Core app, if you hit return anyway at this point, a yellow bar appears indicating that a `NotSupportedException` has been raised.

```
    <description>System.NotSupportedException: Changing document &apos;C:\Users\sandy\source\repos\WebApplication1\WebApplication1\Pages\_ViewImports.g.cs&apos; is not supported.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyRename(Solution newSolution, IWaitContext waitContext)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IWaitContext waitContext, Boolean previewChanges)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.&lt;&gt;c__DisplayClass76_0.&lt;Commit&gt;b__0(IWaitContext waitContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Boolean showProgress, Action`1 action)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.Commit(Boolean previewChanges)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(ReturnKeyCommandArgs args, CommandExecutionContext context)&#x000D;&#x000A;   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;Execute&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

In a simple console app, you can hit return and the namespace rename will be successful.

**Comment by sharwell** [comment] 2019-09-27 18:21
Duplicate of #3583

**Closed by sharwell** 2019-09-27 18:21 UTC
