### ISSUE TITLE
ArgumentOutOfRangeException during extract method 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4635] opened 2015-08-18 21:00 UTC
Crash dump:
```
%internal_share%\public\tomat\Bugs\4635
```

Stack trace

```
"Specified argument was out of the range of valid values.\r\nParameter name: index"

   at Microsoft.VisualStudio.Text.Utilities.FrugalList`1.get_Item(Int32 index) in f:\dd\src\Platform\Text\Util\TextDataUtil\FrugalList.cs:line 254
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapToSourceSnapshot(Int32 position) in f:\dd\src\Platform\Text\Impl\TextModel\Projection\ProjectionSnapshot.cs:line 483
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToInsertionPoint(SnapshotPoint position, PointTrackingMode trackingMode, Predicate`1 match) in f:\dd\src\Platform\Text\Impl\TextModel\Projection\BufferGraph.cs:line 168
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.IBufferGraphExtensions.MapUpOrDownToBuffer(IBufferGraph bufferGraph, SnapshotPoint point, ITextBuffer targetBuffer) in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Extensions\IBufferGraphExtensions.cs:line 66
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextViewExtensions.GetCaretPoint(ITextView textView, ITextBuffer subjectBuffer) in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Extensions\ITextViewExtensions.cs:line 34
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetCaretPoint(ITextView textViewOpt, ITextBuffer subjectBuffer) in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.cs:line 153
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.RecomputeTagsForeground() in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:line 288
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker() in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\ForegroundNotification\ForegroundNotificationService.cs:line 116
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground() in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\ForegroundNotification\ForegroundNotificationService.cs:line 90
   at Roslyn.Utilities.TaskFactoryExtensions.<>c__DisplayClass1_0.<SafeStartNew>b__0() in F:\Builds\5433\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\Core\Portable\Utilities\TaskFactoryExtensions.cs:line 30
```

**Comment by tmat** [comment] 2015-08-18 21:02
Might be a bug in the editor.

**Comment by balajikris** [comment] 2015-08-18 21:10
thanks - dupe of #4251. I'm just about to look at it. Its a bug somewhere in light bulbs and is reproducible via extract method codeaction. @tmat - Please use Extract method command (CTRL + R, M) to unblock yourself until this gets fixed.

**Closed** 2015-08-18 21:12 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
