### ISSUE TITLE
CompletionItem.Create has a non-source compatible change

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#12744] opened 2016-07-26 17:41 UTC
**From API Review**

There is a change to `CompletionItem.Create` which is binary compatible but not source compatible.  The new overload is lacking the `TextSpan` parameter with default value in order to maintain source compatibility with customers.

**Comment by CyrusNajmabadi** [comment] 2016-11-30 20:21
@jaredpar We've looked at this and we're not quite sure why this is necessary.  We're explicitly trying to make this break if you recompile (also why we have the Obsolete attribute with 'error: true').  We've preserved binary compat, but if the user recompiles we want them to have to update their code.

> The new overload is lacking the TextSpan parameter with default value in order to maintain source compatibility with customers.

We feel this is intentional.  If we added the TextSpan parameter, then that would defeat the purpose of the new API (which is to have the user pass in this value).  Also, if we added the parameter in, we'd have precisely the same API signature that we had before :)

**Comment by CyrusNajmabadi** [comment] 2016-12-16 21:54
@jaredpar Need info on you as to what the issue is and what the expected way to fix it would be.  Kevin and I looked at this and can't identify a problem.

**Comment by jaredpar** [comment] 2016-12-19 18:09
During the API review we came to the conclusion that a source breaking change wasn't acceptable here.  That is the reason I ended up filing the bug to track the issue.  If we want to force a user breaking change then we need to explicitly run that through the compat council.

**Comment by CyrusNajmabadi** [comment] 2016-12-19 18:40
Ok.  Let's go through the compat council then.  The point is precisely to deprecate the old API (with Obsolete(error=true)).  People using source should have to change what they call.

**Comment by Pilchie** [comment] 2017-01-09 23:38
Tagging @dotnet/roslyn-compat-council for approval on this change - we deliberately added the `[Obsolete]` attribute with `IsError=true` to this API, because it will no longer operate as expected.

Note this is far from the only public API that has been marked Obsolete in 2.0...

**Comment by Pilchie** [comment] 2017-01-11 23:54
Closing as won't fix, as I've heard no reply here or in email

**Closed by Pilchie** 2017-01-11 23:54 UTC
Labels: Area-IDE, Bug, Concept-API
