### ISSUE TITLE
Switch on pattern throws NullReferenceException

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn#16180] opened 2017-01-02 00:48 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26014.0 D15REL
netstandard1.4

**Steps to Reproduce**:

Call this method:
```
private static RuntimeTransition BuildRuntimeTransition(TransitionBase transitionBase, IEnumerable<RuntimeStateBase> runtimeStates)
{
    switch (transitionBase)
    {
        case Transition transition:
            return new RuntimeTransition(
                transition.Name,
                runtimeStates?.Single(s => s.Name == transition.Target.Name),
                transition.Action,
                null);
        case InternalTransition transition:
            return new RuntimeTransition(
                transition.Name,
                null,
                transition.Action,
                transition.Guard);
        case ExternalTransition transition:
            return new RuntimeTransition(
                transition.Name,
                runtimeStates?.Single(s => s.Name == transition.Target.Name),
                transition.Action,
                transition.Guard);
        default:
            throw new ArgumentOutOfRangeException(
                nameof(transitionBase), 
                $"Invalid transition type: {transitionBase.GetType().FullName}");
    }
}
```

The method can be found [here](https://github.com/paulomorgado/StateMachineExplorations/blob/e987a5ffcf3edc1923ffacb91cd71482ea9bbd17/src/StateMachineExplorations/Definitions/RuntimeBuilder.cs#L108-L135) and a test that calls into it [here](https://github.com/paulomorgado/StateMachineExplorations/blob/e987a5ffcf3edc1923ffacb91cd71482ea9bbd17/tests/StateMachineExplorationTests/Definitions/IfElseStateTests.cs).

**Expected Behavior**:
Selects the correct branch.

**Actual Behavior**:
Throws `NullReferenceException` in the `switch (transitionBase)` line.

**Comments**

Refactoring the code to this:
```

private static RuntimeTransition BuildRuntimeTransition(TransitionBase transitionBase, IEnumerable<RuntimeStateBase> runtimeStates)
{
    if (transitionBase != null)
    {
        {
            if (transitionBase is Transition transition)
            {
                return new RuntimeTransition(
                    transition.Name,
                    runtimeStates?.Single(s => s.Name == transition.Target.Name),
                    transition.Action,
                    null);
            }
        }

        {
            if (transitionBase is InternalTransition transition)
            {
                return new RuntimeTransition(
                    transition.Name,
                    null,
                    transition.Action,
                    transition.Guard);
            }
        }

        {
            if (transitionBase is ExternalTransition transition)
            {
                return new RuntimeTransition(
                    transition.Name,
                    runtimeStates?.Single(s => s.Name == transition.Target.Name),
                    transition.Action,
                    transition.Guard);
            }
        }
    }

    throw new ArgumentOutOfRangeException("transitionBase", string.Format("Invalid transition type: {0}", transitionBase.GetType().FullName));
}
```

works as expected.

Decompiling the code with .NET Reflector 9.0 gives me this code:

```
private static RuntimeTransition BuildRuntimeTransition(TransitionBase transitionBase, IEnumerable<RuntimeStateBase> runtimeStates)
{
    TransitionBase base2 = transitionBase;
    if (base2 != null)
    {
        Transition transition = base2 as Transition;
        if (transition != null)
        {
            <>c__DisplayClass3_0 class_;
            class_.transition = transition;
            return new RuntimeTransition(class_.transition.Name, (runtimeStates != null) ? ((ITransitionTarget) Enumerable.Single<RuntimeStateBase>(runtimeStates, new Func<RuntimeStateBase, bool>(class_.<BuildRuntimeTransition>b__0))) : null, class_.transition.Action, null);
        }
        InternalTransition transition2 = base2 as InternalTransition;
        if (transition2 != null)
        {
            InternalTransition transition5 = transition2;
            return new RuntimeTransition(transition5.Name, null, transition5.Action, transition5.Guard);
        }
        ExternalTransition transition3 = base2 as ExternalTransition;
        if (transition3 != null)
        {
            <>c__DisplayClass3_1 class_2;
            class_2.transition = transition3;
            return new RuntimeTransition(class_2.transition.Name, (runtimeStates != null) ? ((ITransitionTarget) Enumerable.Single<RuntimeStateBase>(runtimeStates, new Func<RuntimeStateBase, bool>(class_2.<BuildRuntimeTransition>b__1))) : null, class_2.transition.Action, class_2.transition.Guard);
        }
    }
    throw new ArgumentOutOfRangeException("transitionBase", $"Invalid transition type: {transitionBase.GetType().FullName}");
}
```

I don't know why the need for the `<>c__DisplayClass3_0` and `<>c__DisplayClass3_1` but they seem to be causing this issue.

**Comment by svick** [comment] 2017-01-02 18:09
I think this might be a duplicate of https://github.com/dotnet/roslyn/issues/16066.

**Closed** 2017-01-02 18:39 UTC
Labels: Area-Compilers, Resolution-Duplicate

**Comment by paulomorgado** [comment] 2017-01-03 22:23
I was able to work around the problem by extracting the code in the `case`s to other methods:

```
private static RuntimeTransition BuildRuntimeTransition(TransitionBase transitionBase, IEnumerable<RuntimeStateBase> runtimeStates)
{
    switch (transitionBase)
    {
        case Transition transition:
            return BuildRuntimeTransition(runtimeStates, transition);
        case InternalTransition transition:
            return BuildInternalRuntimeTransition(transition);
        case ExternalTransition transition:
            return BuildExternalRuntimeTransition(runtimeStates, transition);
        default:
            throw new ArgumentOutOfRangeException(
                nameof(transitionBase),
                $"Invalid transition type: {transitionBase.GetType().FullName}");
    }
}
```
