### ISSUE TITLE
Exception on Mono: Msbuild failed when processing the file '.csproj' with message: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#21609] opened 2017-08-18 16:35 UTC
**Version Used**: 
Roslyn Version 2.3.1
Mono Version 5.2.0
Ubuntu Version 16.04

**Steps to Reproduce**:

1. I am trying to run the following code on Ubuntu using Mono:
```
var workspace = MSBuildWorkspace.Create();
Project currentProject = workspace.OpenProjectAsync(projectPath).Result;

```
2.  When we run the above code, we get following exception: **Msbuild failed when processing the file '.csproj' with message: Operation is not supported on this platform**.

**Expected Behavior**:
The code should run.

**Actual Behavior**:
Exception Msbuild failed when processing the file '.csproj' with message: Operation is not supported on this platform.

**Comment by Pilchie** [comment] 2017-08-21 16:06
Can you get the callstack of the exception?

**Comment by abhijitparkhi1983** [comment] 2017-08-22 06:58
I dont get a direct exception. 
I had attached a **WorkspaceFailed** event in which the **WorkspaceDiagnosticEventArgs.Diagnostic.Message** gives following message: **[Failure] Msbuild failed when processing the file '/home/user/Roslyn/RoslynTest.csproj' with message: Operation is not supported on this platform.**

Also if we check on the **Documents.Count** it returns **0** but the above .csproj has couple of documents.

**Comment by DustinCampbell** [comment] 2017-08-22 11:15
MSBuild will eat your exception unless you break on it. In VS4Mac, you can create a breakpoint to stop on `System.Exception` or any subtype. In VS, you can change your exception settings to break on all CLR exceptions.

**Comment by DustinCampbell** [comment] 2017-08-22 11:30
This is a duplicate of https://github.com/dotnet/roslyn/issues/20848.

**Comment by abhijitparkhi1983** [comment] 2017-08-23 14:00
@DustinCampbell , I tried changing exception settings to break on all CLR exceptions using VS 2015, built the source and replaced the built binary on the Ubuntu machine and tried running the application using Mono. But I dont see any more error message than the one which I have mentioned above.

Please let me know if I am missing on some thing here.

**Comment by DustinCampbell** [comment] 2017-08-23 14:29
Those settings don't change how the binary is built, they affect how the VS debugger runs. In other words, changing the settings, building the binary and then copying it somewhere else to run wouldn't have any effect.

On Ubuntu, you could use MonoDevelop to debug the application.

**Comment by abhijitparkhi1983** [comment] 2017-08-23 16:48
Ok, let me check out on MonoDevelop. Have never used it. Will get back to you on this one

**Comment by CyrusNajmabadi** [comment] 2024-10-18 22:01
Closing out as we haven't heard any issues on this in 7 years.

**Closed by CyrusNajmabadi** 2024-10-18 22:01 UTC
Labels: Bug, Area-IDE
