### ISSUE TITLE
Static local functions cannot reference locally defined constants.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37336] opened 2019-07-18 19:05 UTC
If a function in which a local function is defined has locally defined constants, IDE0062 will appear suggesting to make the local function static.

However, doing so will produce CS8421: A static local function cannot contain a reference to 'LocalConstant'.

Since constants are... well, constant, it should not quite matter where -- or how many times -- they are defined as long as they are in scope. Probably the compiler would have to re-generate these local constants or hoist them from the outer function to the class that receives the local functions and just fixup the references whether they appear in the local function or the function in which they are defined.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/637299/static-local-functions-cannot-reference-locally-de.html
VSTS ticketId: 943805_
_These are the original issue comments:_

Visual Studio Feedback System on 7/9/2019, 03:43 AM (9 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by Therzok** [comment] 2019-07-18 19:30
Dupe of #36091

**Comment by jinujoseph** [comment] 2019-07-18 23:27
thanks @Therzok

**Closed by jinujoseph** 2019-07-18 23:27 UTC
Labels: Developer Community
