### ISSUE TITLE
VS ignores change of extension

### ISSUE THREAD

**Issue by DzonnyDZ** [dotnet/roslyn#5009] opened 2015-09-04 13:12 UTC
Consider following steps (VS2015):
1. Create a new C# project, Console Application .NET 4.6
2. Right-click on the project in Solution Explorer | Add | New Item | Visual C# Items / General | Application Configuration File
3. Change the content of the newly added App1.config to class Aaa{}
4. Save the file
5. Rename the file in Solution Explorer to App1.cs (confirm change of extension)
6. Close the file
7. Open it again from Solution Explorer

![bug](https://cloud.githubusercontent.com/assets/2221259/9684286/e0a69ad8-5316-11e5-9198-8122cfd5ade2.png)

After such a change of extension, Visual Studio still treats the file as XML (and reports errors that the file does not have proper XML syntax) and despite the Build Action has changed to Compile it does not compile it. The only thing that helps is to restart Visual Studio. Among the things that do _not_ help are:
- Exclude the file from project and include it again
- Unload project and reload it
- Close solution and open it again

**Comment by Pilchie** [comment] 2016-01-25 17:25
Is this a dupe of #8048?

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:15
Closing due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-19 21:15 UTC
Labels: Bug, Area-IDE
