### ISSUE TITLE
Options|Text Editor|C#|Code Style|Formatting|Spacing – some of shows do not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54532] opened 2021-07-01 18:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/OptionsText-EditosCCode-StyleFormat/1280922)._

---
[severity:Other]
Some of available options in the Spacing have broken shows so upon checking or unchecking nothing changes in the sample preview windows.
![Spacing.gif](https://aka.ms/dc/image?name=B4757c544d5e94d46818908eb9cdadc04637430280375734396_Spacing.gif&tid=4757c544d5e94d46818908eb9cdadc04637430280375734396)

---
#### Feedback Bot on 12/8/2020, 10:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/9/2020, 09:37 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/22/2021, 11:50 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Wenwen Fan [MSFT] on 6/14/2021, 11:31 PM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce on the latest release build, if still occur, please provide detailed name for the option.</p>

#### Jiří Čepelka on 6/15/2021, 00:49 AM: 

<p>Yes, this issue still exists. I am not going to write down all the options since I believe it is job of your side to make list of bugs and hand over it to the engineering team.</p>
<p>You can see some of them in the GIF. It can take about 5 to 10 minutes at maximum to check them all and write failing ones down. Sorry.</p>

#### Wenwen Fan [MSFT] on 6/15/2021, 07:55 PM: 

<p>Thank you for replying. We verify on VS2019 build 16.10.1, do check and un-check, all options are working normally on  preview window, and we tried twice on different PC, we could not reproduce. Could you please have a try with the latest release build and disable all extensions.</p>

#### Jiří Čepelka on 6/16/2021, 00:50 AM: 

<p>Unpleasant news for either of us. I tried 16.10.2, normal channel, with disabled extensions but still for:</p>
<p><em>○ Set other spacing options</em></p>
<p><em>• Insert space within parentheses of expressions<br>
• Insert space within parentheses of type cast<br>
• Insert space after cast</em></p>
<p><em>○ Set spacing for brackets</em></p>
<p><em>• Insert space before open square bracket<br>
• Insert space within empty square brackets<br>
• Insert space within square brackets</em></p>
<p>preview does not work.</p>
<p>What data can help to identify the problem?</p>

#### Wenwen Fan [MSFT] on 6/16/2021, 11:16 PM: 

<p>We still could not reproduce on 16.10.2 release build and 16.11.0 Preview 2.0, and could not reproduce on colleague’s PC, please repair your VS or re-install to have a try.</p>

#### Jiří Čepelka on 6/17/2021, 01:42 AM: 

<p>The one who seeks finds… So I successfully identified one condition.</p>
<p>Please tick <em>Set other spacing options/Ignore spaces in declaration statements</em>; then you are having the behavior. I tried also on my home PC installation so this is not specific for installation or machine.</p>

#### Wenwen Fan [MSFT] on 6/17/2021, 02:01 AM: 

<p>Still could not reproduce with “Set other spacing options/Ignore spaces in declaration statements” on build 16.10.2, please refer to attachments, thank you.<br>
<img src="https://aka.ms/dc/image?name=Bdd8d359d1ab54484b937397b7a6f4174637595172369560866_verify.png&amp;tid=dd8d359d1ab54484b937397b7a6f4174637595172369560866" alt="verify.png"></p>

#### Jiří Čepelka on 6/17/2021, 02:07 AM: 

<p>You have to tick up the <em>Set other spacing options/Ignore spaces in declaration statements</em> option. Then you have to try options I have listed down beforehand in communication.</p>
<p>I did not find previous post misleading but still, now it is clear.</p>

#### Wenwen Fan [MSFT] on 6/17/2021, 02:23 AM: 

<p>Thank you for your detailed information. We could reproduce with steps in your latest comments. This issue has been escalated for further investigation.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-07-02 07:20
Duplicate of https://github.com/dotnet/roslyn/issues/53332.

**Comment by jmarolf** [comment] 2022-03-18 21:26
closing as duplicate of https://github.com/dotnet/roslyn/issues/53332

**Closed by jmarolf** 2022-03-18 21:26 UTC
Labels: Bug, Area-IDE, Developer Community, IDE-CodeStyle
