### ISSUE TITLE
Fix IntelliSense in VB.NET With Blocks

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47975] opened 2020-09-23 16:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1194111/fix-intellisense-in-vbnet-with-blocks.html)._

---
[severity:It’s more difficult to complete my work]

In a VB.NET `With` block such as the following, IntelliSense doesn’t work for child elements unless the parent is included (which defeats the whole purpose of a `With` block):

```
With oLabel
   oLabel.Text = "Some text" <- IntelliSense displayed
  .Text = "Some other text" <- IntelliSense not displayed
End With
```

<p>This is a long-standing issue that is very annoying during debugging and which I really would love to see fixed.</p>

---
#### Feedback Bot on 9/23/2020, 02:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2020-10-12 17:33
I cannot reproduce:

![image](https://user-images.githubusercontent.com/31348972/95774882-93a1ad80-0cc1-11eb-9503-525a6bb7c676.png)

Am I misunderstanding the issue?

**Comment by CyrusNajmabadi** [comment] 2020-10-12 17:37
Closing absent a provided a repro case.

**Closed by CyrusNajmabadi** 2020-10-12 17:37 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense, help wanted

**Comment by paul1956** [comment] 2020-10-12 23:10
@CyrusNajmabadi I believe the issue is in the immediate window "very annoying during debugging", but this issue does not say that.
