### ISSUE TITLE
vbc.exe throws ArgumentNullException when no source file is passed on command line

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#8477] opened 2016-02-09 00:40 UTC
```
C:\Temp>vbc /debug:full /target:library
Microsoft (R) Visual Basic Compiler version 42.42.42.42
Copyright (C) Microsoft Corporation. All rights reserved.


Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: paths
   at System.IO.Path.Combine(String[] paths)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken
 cancellationToken) in C:\R1\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 426
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in C:\R1\
src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Vbc.<>c__DisplayClass1_0.<Run>b__0(TextWriter textWriterOut, TextWr
iter _) in C:\R1\src\Compilers\VisualBasic\vbc\Vbc.cs:line 26
   at Roslyn.Utilities.ConsoleUtil.RunWithOutput[T](Boolean utf8Encoding, Func`3 func) in C:\R1\src\Compilers\Helpers\Co
nsoleUtil.cs:line 22
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Vbc.Run(String clientDirectory, String sdkDirectory, String[] args,
 IAnalyzerAssemblyLoader analyzerLoader) in C:\R1\src\Compilers\VisualBasic\vbc\Vbc.cs:line 26
   at Microsoft.CodeAnalysis.BuildTasks.BuildClient.RunWithConsoleOutput(IEnumerable`1 originalArgs, String clientDir, S
tring workingDir, String sdkDir, IAnalyzerAssemblyLoader analyzerLoader, RequestLanguage language, Func`5 fallbackCompil
er) in C:\R1\src\Compilers\Core\MSBuildTask\BuildClient.cs:line 83
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(String[] args, String[] extraArgs) in C:\R1\src\Compil
ers\VisualBasic\vbc\Program.cs:line 20
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(String[] args) in C:\R1\src\Compilers\VisualBasic\vbc\
Program.cs:line 17
```

**Comment by TyOverby** [comment] 2016-02-11 00:21
This has to be a regression right?  Does anyone know what change caused this?

**Comment by jaredpar** [comment] 2016-02-11 17:08
@TyOverby it's definitely a regression.  No idea what caused it but definitely want to know as a part of fixing this bug how this change happened.

**Comment by TyOverby** [comment] 2016-02-12 02:09
The `\debug:full` is not necessary, but `target:library` **is** necessary to reproduce.

**Comment by TyOverby** [comment] 2016-02-12 02:21
The reason for this is we only fail fast  if [the output kind is Application](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L1141)

**Comment by TyOverby** [comment] 2016-02-12 18:48
I've added a "fix" at https://github.com/dotnet/roslyn/pull/8634.  However, VB has some really weird behavior around target:library and `recurse`. 

I couldn't find an invocation of `vbc` with `recurse` that actually worked, so I'm unable to test that.

**Comment by jaredpar** [comment] 2016-02-19 22:10
closed via https://github.com/dotnet/roslyn/pull/8863

**Closed by jaredpar** 2016-02-19 22:10 UTC
Labels: Area-Compilers, Bug
