### ISSUE TITLE
Flaky test 'TestDefaultDiagnosticProviderAll'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46413] opened 2020-07-29 13:51 UTC
https://github.com/dotnet/roslyn/blob/1386d0fdd719f0a141d46315582f5b2724719299/src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb#L143

Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=749582&view=ms.vss-test-web.build-test-results-tab&runId=23240534&resultId=202015&paneView=debug

Xunit log:

```
Microsoft.VisualStudio.LanguageServices.UnitTests.Diagnostics.DefaultDiagnosticUpdateSourceTests.TestDefaultDiagnosticProviderAll [STARTING]
      
      Expected:
      CS1002
      CS0246
      Actual:
      CS1002
      CS1002
      CS0246
      CS0246
      Differences:
          CS1002
      ++> CS1002
          CS0246
      ++> CS0246
      
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/Test/Utilities/Portable/Assert/AssertEx.cs(442,0): at Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector)
        /_/src/Test/Utilities/Portable/Assert/AssertEx.cs(425,0): at Roslyn.Test.Utilities.AssertEx.SetEqual(IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector)
        /_/src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb(177,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.Diagnostics.DefaultDiagnosticUpdateSourceTests.VB$StateMachine_4_TestDefaultDiagnosticProviderAll.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.VisualStudio.LanguageServices.UnitTests.Diagnostics.DefaultDiagnosticUpdateSourceTests.TestDefaultDiagnosticProviderAll [FINISHED] Time: 1.6519875s
```

**Comment by sharwell** [comment] 2020-07-29 15:26
This is likely the same problem as the two previous issues filed for the same test class.

**Comment by RikkiGibson** [comment] 2020-07-29 15:33
I wasn't able to find any issues by searching for "TestDefaultDiagnosticProviderAll" or "DefaultDiagnosticUpdateSourceTests". Could you please help me find the previous issues filed for this failure?

**Comment by sharwell** [comment] 2020-07-29 15:45
#45877 and #46230

**Comment by sharwell** [comment] 2020-07-29 15:45
Duplicate of #45877

**Closed by sharwell** 2020-07-29 15:45 UTC
Labels: Area-IDE, Flaky, Test
