### ISSUE TITLE
Warning IDE0044 - not valid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38777] opened 2019-09-19 22:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/734633/warning-ide0044-not-valid.html)._

---
The following class gives a warning on the field Foo &quot;IDE0044 Make field readonly&quot; which seems invalid.
Public Class Class1
    Private Foo(10) As Integer    ' or Dim Foo

Public Sub Bar()     ' or Private Sub
        Foo(0) = 1
    End Sub
End Class

Also the &quot;Quick Actions&quot; provided are not valid, for example making it a property.

---
#### Visual Studio Feedback System on 9/16/2019, 02:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2019-09-19 22:13
`Make field readonly` is a valid code aciton to provide.  It's fine to have a readonly array whose contents are mutated later on.

**Comment by IBrooke** [comment] 2019-09-19 23:46
I have to disagree with your reply.  In what way is that warning valid?  I don't want the field to be readonly, you may consider it "fine" to have that in programs but I don't, it's confusing for me and even more confusing for people who come after me.  The field is not readonly, I don't want it to be labelled readonly and I see no reason for it to be so. I see no reason why that warning is being raised. I guess I'll just have to suppress the warning but I'm not happy doing that.

**Comment by CyrusNajmabadi** [comment] 2019-09-19 23:55
You said that the suggestion "seems invalid".   I'm pointing out that there isn't anythin invalid about the suggestion.  As the field is never written to, it can be made readonly.

>  I don't want the field to be readonly,

Then disable the feature that suggests this:

![image](https://user-images.githubusercontent.com/4564579/65289077-20e5f300-dafe-11e9-9c88-94526b503c1c.png)

>  it's confusing for me

What's confusing about it?  Thanks!

> The field is not readonly

Right... but it can be made readonly, which is what the suggestion is letting you know.  Making things readonly is generally thought of as *less* confusing because now you can be certain this field won't be accidentally or unintentionally overwritten in a way you don't expect.

**Comment by IBrooke** [comment] 2019-09-20 00:09
"_Making things readonly is generally thought of as less confusing because now you can be certain this field won't be accidentally or unintentionally overwritten in a way you don't expect._"
My point exactly, especially as it doesn't (according to your earlier reply) prevent it being overwritten.  "_What's confusing about it?_"   If someone looks at that code in the future and sees the field being overwritten how are they supposed to know if the readonly tag is wrong or if the code overwriting the field is wrong?  I will never consider it valid for the compiler to suggest a field be marked readonly when that field is being overwritten,  that is contradictory and contradictory code is confusing.

**Comment by CyrusNajmabadi** [comment] 2019-09-20 00:15
>  If someone looks at that code in the future and sees the field being overwritten how are they supposed to know if the readonly tag is wrong or if the code overwriting the field is wrong?

Neither are wrong.  A readonly array doesn't mean individual elements are not writable.  That's been the semantics of VB (and C#) from when they got this keyword.

> , that is contradictory 

There is nothin contradictory here.  The field is not writable.  Hence it is readonly.  The contents of hte array (which are not the field itself) are writable.  This is VB and .net semantics for arrays and fields, and have been since .net was created.

>  I will never consider it valid

You can disable the feature if you so wish.  I have pointed out above.  Note though that the feature is behaving appropriately as per the actual semantics of hte language and how it's worked for nearly 20 years now :)

**Comment by jmarolf** [comment] 2019-09-20 00:25
I do think its an interesting idea to have a codefix that suggests changing say `IList<T>` to `IReadonlyList<T>`. I do think beginners don't immediately grasp that `readonly` does not make the object immutable (though maybe the fix really needs to be in a new language feature like records...)

**Comment by sharwell** [comment] 2019-09-24 19:42
Duplicate of #29637

**Closed by sharwell** 2019-09-24 19:42 UTC
Labels: Resolution-Duplicate, Question, Area-IDE, Developer Community, Feature - IDE0044
