### ISSUE TITLE
IDE0009 should not nag in static context

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#26893] opened 2018-05-16 08:33 UTC
Repro code:

```cs
namespace RoslynSandbox
{
    using System;

    [Obsolete(nameof(Value))]
    class Foo
    {
        public int Value { get; set; }
    }
}
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0009	Add 'this' or 'Me' qualification.	RoslynSandbox(net461)	C:\Git\RoslynSandbox\RoslynSandbox\Foo.cs	5	Active
```

**Comment by davidwengier** [comment] 2018-06-04 23:08
Opened PR to fix this.

**Comment by AArnott** [comment] 2018-07-18 21:47
This is more critical in 15.8 because Format Document applies this as part of bulk fixing everything.

**Comment by CyrusNajmabadi** [comment] 2018-07-19 02:49
FormatDocument will not apply this as part of bulk fixing.  The default set of fixers will only be "remove/sort" usings i believe.

**Comment by sharwell** [comment] 2018-07-19 02:56
@CyrusNajmabadi It doesn't apply it by default, but the option is available and if it gets turned on it will generate broken code for users.

**Comment by CyrusNajmabadi** [comment] 2018-07-19 03:10
@sharwell Of course.  I was only responding to the concern about what 15.8 does.  This will not be on by default, and is thus not "more critical" IMO.  It's about equally critical as it would be for anyone performing the fix-all (which seems more likely to hit given that's a direct user flow that doesn't involve changing options).

**Comment by AArnott** [comment] 2018-07-19 03:31
AFAIK 15.8 was the first release that hits this bug without explicitly trying to apply the IDE0009 code fix (which I rarely do since I type `this.` everywhere myself or apply it to just one line). But I *do* use Format Document *a ton*. Further, with today's intpreview update, Format Document popped up an InfoBar saying that Format Document wasn't configured yet, and drove me to Configure it, which popped up the dialog where I saw all the options. So while it may not be the default, the checkbox to change that is basically thrown in the customer's face, and it looks attractive. So it's a very prominent option so we can't put too much weight on "it's not the default".

For now, I've turned the option back off so it doesn't keep breaking me. But I hope the above is a compelling argument for why Format Document in 15.8 *has* made this more impactful.

**Comment by davidwengier** [comment] 2018-07-19 03:40
I have a PR open for this fix (#27459). @CyrusNajmabadi you asked for a couple of more test cases in your review, which I added a little while ago. Is there something else I can do to help get this resolved for everyone?

Even if there are still a few edge cases missed by my change, it still might be a net win to merge it in time for 15.8, as I don't believe it introduces any _new_ problems.

**Comment by CyrusNajmabadi** [comment] 2018-07-19 03:47
@davidwengier I'd def like to test attributes in basically all circumstances.  It honestly seems like a better fix would be to check if we were in an atttribute and not qualify then.

**Comment by CyrusNajmabadi** [comment] 2018-07-19 04:10
I've proposed my fix here: https://github.com/dotnet/roslyn/pull/28685

It's slightly different in that is directly checks specifically if we're in an attribute, and never offers to qualify with ```this.```.  I think it's conceptually cleaner and more clear as to what it's doing.

**Comment by sharwell** [comment] 2018-07-19 12:01
We also have #28091 and #28509 that would impact usability of Format Document.

**Comment by sharwell** [comment] 2018-07-19 12:02
Duplicate of #23803

**Closed by sharwell** 2018-07-19 12:02 UTC
Labels: 4 - In Review, Area-IDE, Bug
