### ISSUE TITLE
Language Feature Discussion: Allow Lambda Expressions In Method Attribute Initialiser

### ISSUE THREAD

**Issue by TheOpenDevProject** [dotnet/roslyn#10496] opened 2016-04-12 02:00 UTC
***Proposed syntax***
```C#
public class CustomController : Controller{

[CustomAuth(CustomProperty = ((Func<T>)((this) => {/*Insert complex code here*/ }))()]
public void MethodName(){

}

}
```

***Why?***
There are times where a developer needs to pass the current context to the Method Attribute initialiser to get data out.

This might be completely impossible so I would love to hear the discussion.

**Comment by jaredpar** [comment] 2016-04-12 04:47
Closing as a dupe of #2466.  

As @HaloFour pointed out, the types of expressions allowed in attribute constructors is very limited. Essentially it's just constant values.  A lambda expression won't work here because it requires execution at runtime to complete.

**Closed by jaredpar** 2016-04-12 04:47 UTC
