### ISSUE TITLE
Cannot `foreach` over a variable passed by `ref` when `GetEnumerator` implemented as a by-ref extension method

### ISSUE THREAD

**Issue by hamarb123** [dotnet/roslyn#72004] opened 2024-02-08 11:55 UTC
If an extension method for `GetEnumerator` takes `this` by `ref` (not `in`), then it's impossible to use.

**Version Used**: 

Sharplab.io main (20 Jan 2024)
Also reproduced with the compiler included with .NET SDK 8.0.100.

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;
public class C
{
    public void M(ref S12 s)
    {
        foreach (var x in s) { }
    }
}
public struct S12
{
}
public static class Extensions
{
	public static IEnumerator<int> GetEnumerator(this ref S12 value) => throw null;
}
```

[Link](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwAYACDHAFgG5CMBmcrUgYUIG9DTvzGNLSAWQAUAJwCmAM1IBlHMwDOASi49OBHptKSA9hIgBjABalhANwijSAD1KxSy0u1IBfVdzcFPDBwlEBXAwRZeQ5Cbz4cADYmUgBRawRxGAUoHRSwggBIHwoYgEk4mH8wcVEIBD0AHlgEAD5SAHFxBCKSsoq9YQQjKAVSCWk5ZgsUf3ElUgBeBp7RHQB3UmKUFFovIA===)

**Diagnostic Id**:

error CS1510: A ref or out value must be an assignable variable

**Expected Behavior**:

Compiles.

**Actual Behavior**:

Gives an error.

**Comment by jjonescz** [comment] 2024-02-21 17:54
Closing as by design. Spec would need to be changed in https://github.com/dotnet/csharplang and approved by LDM first.

**Closed by jjonescz** 2024-02-21 17:54 UTC
Labels: Bug, Area-Compilers
