### ISSUE TITLE
Line length formatting to be apart of EditorConfig

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57263] opened 2021-10-20 16:34 UTC
Direct customer ask copying here:

> Ability to set max line length and define the wrapping behavior for the formatter. I would appreciate if we can have an editorconfig for native VS that will enforce these style guides, plus producing deterministic (opinionated, so there is no debate) and nicely wrapped code that respects the line length limit.

> resharper_csharp_insert_final_newline = true
resharper_csharp_max_line_length = 100
resharper_csharp_wrap_after_declaration_lpar = true
resharper_csharp_wrap_after_invocation_lpar = true
resharper_csharp_wrap_arguments_style = chop_if_long
resharper_csharp_wrap_chained_method_calls = chop_if_long
resharper_csharp_wrap_extends_list_style = chop_if_long
resharper_csharp_wrap_parameters_style = chop_if_long
resharper_outdent_dots = true
resharper_wrap_array_initializer_style = chop_if_long
resharper_wrap_before_first_type_parameter_constraint = true
resharper_wrap_lines = true

**Comment by jinujoseph** [comment] 2021-10-20 17:15
Duplicate of #15406

**Closed by jinujoseph** 2021-10-20 17:15 UTC
Labels: Area-IDE, Feature Request, IDE-Formatter
