### ISSUE TITLE
Caret jumps to end of line when i type semicolon

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37792] opened 2019-08-07 17:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/672094/caret-jumps-to-end-of-line-when-i-type-semicolon.html)._

---
In the following code if I attempt to insert a semicolon immediately after the right most curly brace and before the comma the caret will jump to the end of the line and insert it before the EOL semicolon. I know that this is not correct code, but I thought i should bring it to your attention because it's a bug in the text editor.

```
        public static void SubmitWorkOnQueue(Action action, string description)
        {
            workQueue.Enqueue((() => { action }, description));
        }
```

After typing in the semicolon, the line will be ..

```
workQueue.Enqueue((() => { action }, description)); ;
```

---
#### Visual Studio Feedback System on 8/2/2019, 03:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-08-07 17:15
Repro in 16.3.Preview2

**Comment by sharwell** [comment] 2024-01-08 17:22
Depending on what the user is trying to do, this is either a duplicate of #37874 or #52299.

**Closed by sharwell** 2024-01-08 17:22 UTC
Labels: Bug, Area-IDE, Developer Community
