### ISSUE TITLE
Configure code style does nothing, does not apply to editorconfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63216] opened 2022-08-04 19:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Configure-code-style-does-nothing-does-/10111126)._

---
[severity:It's more difficult to complete my work]
![image](https://user-images.githubusercontent.com/754264/182945858-557df26a-9b91-4c87-8baa-18b8adec7b55.png)

This option does nothing, I get no feedback of what happened, it does not change the rule.

I have a editorconfig file on my project.

Configuring the code style or the severity simply don't work and there's no way to tell why.

---
#### Feedback Bot on 8/4/2022, 01:17 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-08-08 17:37
Duplicate of https://github.com/dotnet/roslyn/issues/45417

**Closed** 2022-08-08 19:14 UTC
Labels: Area-IDE, untriaged
