### ISSUE TITLE
AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat Null Reference Info Bar

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22324] opened 2017-09-25 19:56 UTC
From: https://developercommunity.visualstudio.com/content/problem/117219/microsoftcodeanalysisconverttointerpolatedstringab.html

```
at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Parametri sconosciuti>)
at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Parametri sconosciuti>)
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by a11smiles** [comment] 2017-12-11 18:20
I too am getting this: 

    System.NullReferenceException : Object reference not set to an instance of an object.
    at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
    at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
    at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Neme12** [comment] 2018-05-20 08:11
Could this be a duplicate of #20943? Is there any repro of this?

**Comment by Neme12** [comment] 2018-05-20 08:33
@jinujoseph Can you please check?

**Comment by Neme12** [comment] 2018-05-22 16:05
I don't know how this works so I'm sorry to bother but is there any repro/code attached to the feedback item so we can make sure it is the same issue as #20943? If not, can we just assume that because the stack trace is the same and close this as a duplicate? @jinujoseph

**Comment by jnm2** [comment] 2019-01-28 02:02
I'm hitting this.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:48
Closing out due to lack of prism hits.

**Closed by CyrusNajmabadi** 2024-10-19 21:48 UTC
Labels: Bug, Area-IDE
