### ISSUE TITLE
Unable to change context for shared project files after closing and re-opening documents

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#14586] opened 2016-10-18 17:21 UTC
**Version Used**: 
Dev14 Update3 (also repros on Dev15 Preview5)

**Steps to Reproduce**:
1.  Open the attached solution:
   [SharedProject2.zip](https://github.com/dotnet/roslyn/files/536915/SharedProject2.zip)
2. Open source file Class1.cs in the SharedProject2 - verify the navigation bar shows ConsoleApplication1 and ConsoleApplication2 (SharedProject2 is referenced by both these desktop apps).
3. Change the navigation bar context for the source file between ConsoleApplication1 and ConsoleApplication2 - as expected, the context changes fine and the defines specific to the project are respected.
4. Close and reopen Class1.cs.
5. Attempt to repeat step3

**Expected Behavior**:
Same as prior to closing and re-opening the source file - context switches between owning projects.

**Actual Behavior**:
Context doesn't switch between owning projects and the navigation bar always switches back to ConsoleApplication1. Repeating steps 4 and 5 multiple times doesn't help. Only closing and reopening the solution fixes the behavior (until the file is closed again).

**NOTE**: This scenario is also reproing for dotnet core cross targeting projects (which mimic shared project functionality).

**Comment by mavasani** [comment] 2016-10-18 17:23
Tagging @srivatsn as an FYI

**Comment by Pilchie** [comment] 2016-11-07 19:53
Dupe of https://github.com/dotnet/roslyn/issues/5343 I think.

**Closed by Pilchie** 2016-11-07 19:53 UTC
Labels: Area-IDE, Bug
