### ISSUE TITLE
snippets do not expand for #region and #if 

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#56618] opened 2021-09-22 18:57 UTC
**Version Used**: 

![image](https://user-images.githubusercontent.com/4510984/134404904-b665a2ff-0368-4e43-aa88-4a41e94c41ce.png)

**Steps to Reproduce**:

1. Type `#region`
2. Press `Tab` on the keyboard
3. Press `Tab` on the keyboard
4. Press `Tab` on the keyboard
5. Press `Tab` on the keyboard
6. Press `Tab` on the keyboard
7. Press `Tab` on the keyboard
8. Press `Tab` on the keyboard
9. Press `Tab` on the keyboard
10. Press `Tab` on the keyboard

**Expected Behavior**:

https://www.youtube.com/watch?v=II_5C9mfS9Q&ab_channel=CoffeeNCode

**Actual Behavior**:

![ipMVmg9Roi](https://user-images.githubusercontent.com/4510984/134404977-294ed85f-6b32-44d1-9bbe-b9c7f47ba05d.gif)

**Comment by Youssef1313** [comment] 2021-09-22 19:13
It looks like you're pressing a "space" after typing `#region`? You just need to hit tab twice.

**Comment by Youssef1313** [comment] 2021-09-22 19:37
@GF-Huang Do you mean you're expecting it to work even with a space after "#region"? I don't think snippets are designed to work this way. If it works for you without the extra space, then I believe this is by design.

Note: I'm not a Microsoft employee - so you may want to wait for someone from Roslyn team to confirm.

**Comment by GF-Huang** [comment] 2021-09-22 19:39
> @GF-Huang Do you mean you're expecting it to work even with a space after "#region"? I don't think snippets are designed to work this way. If it works for you without the extra space, then I believe this is by design.
> 
> Note: I'm not a Microsoft employee - so you may want to wait for someone from Roslyn team to confirm.

I never type `space`, I never press `space`, the `space` was generated by the `tab` key, that's what you see.

**Comment by jmarolf** [comment] 2021-09-22 20:18
I can reproduce this in 16.11. This appears to be an editor bug, the `#region` snippet is never expanded. @olegtk was anything about snippet handling changed recently?

**Comment by Youssef1313** [comment] 2021-09-22 20:24
Doesn't seem to repro in 17.0 P4 for me

![region](https://user-images.githubusercontent.com/31348972/134416253-a6d3b6cd-9a9f-40ab-9ba1-725e9992fd77.gif)

**Comment by olegtk** [comment] 2021-09-22 20:33
@AmadeusW ?

**Comment by Youssef1313** [comment] 2021-09-22 20:46
@jmarolf It didn't reproduce for me in 16.11.3.

![region_16_11](https://user-images.githubusercontent.com/31348972/134419300-07631090-4c21-4a36-a874-e469e557c99f.gif)

**Comment by jmarolf** [comment] 2021-09-22 20:57
It does for me it I type at the end of a bracket:
![region_bug](https://user-images.githubusercontent.com/9797472/134420771-18836b36-ef58-42d1-abe1-2e8c7ad271be.gif)

Microsoft Visual Studio Enterprise 2019
Version 16.11.3

**Comment by huoyaoyuan** [comment] 2021-09-23 15:19
It doesn't reproduce for me on either 16.11 or 17.0P4

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:56
Closing as we are not investing in legacy snippets behavior.

**Closed by CyrusNajmabadi** 2024-10-22 19:56 UTC
Labels: Bug, Area-IDE, Investigation Required
