### ISSUE TITLE
Proposal : parametrized "new" constraints

### ISSUE THREAD

**Issue by 6opoDuJIo** [dotnet/roslyn#2404] opened 2015-04-30 14:07 UTC
I'd like to be able to have constraint type parameters with specific constructor structure, like this : 
```csharp
    T FOO<T> () where T : new (string, string,int)
    {
         return new T("a1", "a2", 255);
    }
```
In some cases it would be useful, like above.

**Comment by Joe4evr** [comment] 2015-04-30 14:58
Dupe of #2206.

**Comment by 6opoDuJIo** [comment] 2015-04-30 15:39
Got it. Closed.

**Closed** 2015-04-30 15:39 UTC
