### ISSUE TITLE
Completion from unimported namespace doesn't show if typed quickly after opening a file

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#50364] opened 2021-01-10 19:46 UTC
I'm not sure about the exact reproducing condition, but I face this many times when I open a new file and start to type quickly.

Once the completion list is shown, it will not update to contain unimported types for further typing. The workaround is to delete the initial character and wait for 2 seconds.

I remember I didn't face with this at the beginning of this feature. Some update at about 16.7 suddenly breaks my typing habit that relies on this feature.

**Comment by sharwell** [comment] 2021-01-10 21:34
This was a required behavior in order to meet performance expectations for typing in a newly-opened file. It would be nice to start the background computation necessary to support this feature before a character is typed, but it might not be possible to cover all cases.

**Comment by huoyaoyuan** [comment] 2021-01-11 06:48
I know it should be lazy, but I'd expect:
- There's something to indicate "IntelliSense is collecting things"
- Don't require me to retype when it's available

**Comment by Dreamescaper** [comment] 2021-01-11 16:15
Probably same as https://github.com/dotnet/roslyn/issues/44175 .
And I certainly agree that currently it's very confusing.

**Comment by genlu** [comment] 2021-01-12 22:25
>    There's something to indicate "IntelliSense is collecting things"

This is something we are considering. However, there

> Don't require me to retype when it's available

You shouldn't need to retype it. Can you dismiss the completion and invoke again (either ctrl + space or ctrl + j)? You can also use the "expander" button to force the load (alt + a or ctrl + j when completion list is shown)

**Comment by huoyaoyuan** [comment] 2021-01-13 05:51
> Can you dismiss the completion (esc) and invoke again (either "ctrl + space" or "ctrl + j")? You can also use the "expander" button to force the load ("alt + a" or "ctrl + j" when completion list is shown)

This is a solution, but I don't memorize these shortcuts. Thank you for pointing out these. Maybe there should be more help for discovering them.

**Comment by genlu** [comment] 2021-01-14 20:09
Close this as duplicate of #44175, I agree this is an issue need to be addressed either via some UI element to make users aware of the situation or some pre-load logic that would avoid it in most of the cases.

**Closed by genlu** 2021-01-14 20:09 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-IntelliSense
