### ISSUE TITLE
Code cleanup during formatting: Remove unnecessary usings - Give option not to remove system namspace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38383] opened 2019-08-29 17:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/351777/code-cleanup-during-formatting-remove-unnecessary.html)._

---
Migrated from <a href="http://visualstudio.uservoice.com/forums/121579/suggestions/35606437">Visual Studio IDE UserVoice forum</a> <br><br> There are few namespace (For C#) like commonly used:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

It would be helpful if code cleanup doesn't remove the &quot;System&quot; namespaces as they might be used eventually, but it should remove other namespace if it is not used.

---
#### Jane Wu [MSFT] on 10/15/2018, 03:24 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about&nbsp;five business days&nbsp;on our next steps.</p>
#### Andrew Cheung [MSFT] on 1/11/2019, 01:04 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by kendrahavens** [comment] 2019-08-29 17:11
Note: This was also a uservoice (3 votes) and devcomm had 2 votes.

**Comment by vatsalyaagrawal** [comment] 2019-09-03 21:59
@Joey is this a duplicate?

**Comment by CyrusNajmabadi** [comment] 2019-09-04 00:19
This is definitely by design.  At one point we didn't remove this, but people complained that "of course, i asked you to remove unused things, so why didn't you remove it?".  It's easy and safe to remove. If the user then needs to reference some type from System, they can both write it and `add using`, or just select the item from the completion list (which will add the import).

**Comment by DesrosiersC** [comment] 2020-08-14 14:38
It is a must for me to be able to exclude some usings from the cleanup. Mostly those that have a lot of extension methods in them. It breaks my flow to have to always add back System.Ling and System.Collections.Generic.

**Comment by AndreasHoffmann2** [comment] 2021-03-16 11:14
There should be a list of usings somewhere in the preferences that should always be kept.

**Comment by CyrusNajmabadi** [comment] 2024-11-29 05:12
Closing out as by design. We tried this once and the feedback was huge that we should not special case.

**Closed by CyrusNajmabadi** 2024-11-29 05:12 UTC
Labels: Area-IDE, Feature Request, Developer Community
