### ISSUE TITLE
MaybeNull seems not working in method body

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#40061] opened 2019-11-29 04:40 UTC
**Version Used**: .NET Core 3.0.101/.NET Core 3.1 preview 3

**Steps to Reproduce**:

```csharp
[MaybeNull] public T Test => default;
```
or
```csharp
public T Test
{
    [return: MaybeNull]
    get
    {
        return default;
    }
}
```
or
```csharp
[return: MaybeNull] public T Test() => default;
```
or
```csharp
[return: MaybeNull] string Test() => null;
```

**Expected Behavior**:
Nothing happen.

**Actual Behavior**:
warning CS8653: A default expression introduces a null value when 'T' is a non-nullable reference type.  
warning CS8603: Possible null reference return.

**Comment by huoyaoyuan** [comment] 2019-11-29 10:30
This is by design for now. See https://github.com/dotnet/roslyn/issues/30953#issuecomment-509334985 .

**Comment by jcouv** [comment] 2019-12-11 00:48
Closing as duplicate of https://github.com/dotnet/roslyn/issues/36039 (Should nullability attributes affect method bodies and OHI?)

**Closed by jcouv** 2019-12-11 00:48 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Nullable Reference Types
