### ISSUE TITLE
Different ruleset between project code analysis settings an analyzers

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#4460] opened 2015-08-10 15:07 UTC
Original filed by @hvanbakel as https://github.com/dotnet/roslyn-analyzers/issues/259.

From original bug:
>I've got this strange situation where the Analyzers use a different ruleset from the project. 
>If I go into project properties -> Code Analysis -> RuleSet it has ruleset A.
>If I right-click the analyzers node -> open active ruleset -> ruleset B
>
>Is this on purpose? I have seen this work correctly as well (using the same ruleset).
>
>For what it's worth, I'm using an imported props file which sets the ruleset. It works fine in the >project properties, here it always references the correct one.

**Comment by tmeschter** [comment] 2015-08-10 15:10
@hvanbakel Could you provide more details on how you're setting the rule set in the .props file, and how that .props file is included in your project? This may be an issue with how MSBuild and Visual Studio interact, so the more details the better.

**Comment by hvanbakel** [comment] 2015-08-10 17:25
I'll be as detailed as I can be. The scenario is as follows, I have a tree of nuget packages that contain analyzers, assume the following tree
- Common
  - Production
  - Testing

Every package in this tree has a ruleset. This ruleset is inserted into the project through a .props file. What nuget does out of the box, when you install Production for example, is install all the props in the order in which the packages are installed. As a result the Common.props file will be referenced first followed by the Production.props. 

Visual studio will take the first ruleset it finds to run the analyzers with, so I added an install script which removes any existing props import from the project file. As a result, only the props file of the final (leaf) node will be added. This works perfectly for the project properties, I can see the proper ruleset is considered and this one is checked when building. 

However, on some occasions, I'm seeing the analyzers using a ruleset which is not of the leaf node. So it will be using Common as opposed to Production. Which is a problem since some analyzers which are brought in by Production and disabled in its ruleset are now in the project but not disabled.

I do not have a scenario for reproduction unfortunately, like I said it's not happening on every occasion but I would expect the analyzers to use the same logic for determining the ruleset.

**Comment by hvanbakel** [comment] 2015-08-10 17:28
What I just found out is that taking a solution which has this problem, copy it to a new location and opening it in that new location fixes the problem. So it looks like Visual Studio is somehow caching/keeping track of the ruleset to use, and it's not doing so on disk.

**Comment by mavasani** [comment] 2015-10-12 22:40
Moving this out of 1.1 as a workaround exists and we probably need deeper investigation around what part of the cache is getting corrupted.

**Comment by hvanbakel** [comment] 2015-10-12 22:42
@mavasani could you at least give a pointer as to what type of cache is used and where it is so it can be flushed if we run into this?

**Comment by mavasani** [comment] 2015-11-03 23:35
@hvanbakel - My earlier comment was not quite right. I meant to say that "something looks broken, here and we need to investigate that further" - I don't know if we do any caching for rulesets or not.

**Comment by mavasani** [comment] 2016-02-08 19:56
We have replaced the analyzer driver in Update1 - if you are still able to repro this on Update1 bits (even if intermittently), kindly re-activate. I'll get in touch with you to get a repro solution.

**Closed by mavasani** 2016-02-08 19:56 UTC
Labels: Area-Analyzers, Bug
