### ISSUE TITLE
Verify alt interpolated verbatim strings with VirtualChars

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29172] opened 2018-08-08 22:56 UTC
Follow up on PR https://github.com/dotnet/roslyn/pull/28927 interacting with new C# 8 feature.

**Comment by Neme12** [comment] 2018-11-13 20:42
tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2018-11-13 20:55
Sorry, it's unclear what this issue is referring to.

**Comment by jcouv** [comment] 2018-11-13 21:00
It's verifying that we get the same desired behavior with `@$"..."` strings as we do with `$@"..."` strings:
![image](https://user-images.githubusercontent.com/4564579/43352532-ecb43e66-91f2-11e8-96a9-92eccc30717d.png)

**Comment by jcouv** [comment] 2018-11-13 21:00
Fixed the label to "Test".

**Comment by Neme12** [comment] 2018-11-13 21:01
@gafter marked another issue as a duplicate of this: #30135

**Comment by CyrusNajmabadi** [comment] 2018-11-13 21:07
Ah sure.  Sounds good to me.

**Closed** 2019-02-14 02:00 UTC
Labels: Area-Compilers, Test
