### ISSUE TITLE
Option to put summary on a single line in xml documentation comments when I type triple ///

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47791] opened 2020-09-17 17:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1187457/option-to-put-summary-on-a-single-line-in-xml-docu.html)._

---
This was recently suggested [here](https://developercommunity.visualstudio.com/content/idea/1035288/about-single-line-xml-comment-of-c.html) but was sent to [GitHub](https://github.com/dotnet/roslyn/issues/43710) as a Roslyn feature.  I don't think that was the right move, so I'm suggesting it again.
_
When I type ///, the IDE expands that into
_
/// <summary>
///
/// </summary>
_
It is very uncommon for me to write a summary that takes more than 1 line and I don't want it to take up 3 when 1 will do, so I almost ALWAYS then have to delete the extra /// and new line characters to set it to
_
/// <summary>|</summary>
_
I don't care what I am adding the XML documentation to -- I just want a single option to have it ALWAYS do the single line version (we'll have to keep the 3 line version because I'm sure other people like that).
Please add an option in
Tools -> Options -> Text Editor -> C# -> Advanced under "Editor Help" next to "Generate XML documentation comments for ///"
that allows me to choose whether it generates a 3 line summary (current behavior) or a single line (new behavior).

---
#### Feedback Bot on 9/17/2020, 02:35 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by PathogenDavid** [comment] 2020-09-18 04:30
> This was recently suggested [here](https://developercommunity.visualstudio.com/content/idea/1035288/about-single-line-xml-comment-of-c.html) but was sent to [GitHub](https://github.com/dotnet/roslyn/issues/43710) as a Roslyn feature. I don't think that was the right move, so I'm suggesting it again.

Roslyn is what implements a lot of the Visual Studio features you know and love, so this is almost certainly the right place.

This is a duplicate of #43710 (which OP already seems to have found.)

**Comment by CyrusNajmabadi** [comment] 2020-09-18 08:04
Closing as dupe of #43710 .  thanks!

**Closed by CyrusNajmabadi** 2020-09-18 08:04 UTC
