### ISSUE TITLE
SA1313 analyzer throws InvalidCastException

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#5171] opened 2015-09-11 18:52 UTC
SA1313 throws an exception on the following code:
```csharp
Action<int> foo = _ => { };
```

with stack trace
```
   bei StyleCop.Analyzers.NamingRules.SA1313ParameterNamesMustBeginWithLowerCaseLetter.NameMatchesAbstraction(ParameterSyntax syntax, SemanticModel semanticModel) in SA1313ParameterNamesMustBeginWithLowerCaseLetter.cs:Zeile 94.
```

because syntax.Parent is a SimpleLambdaExpressionSyntax and not a ParameterListSyntax

**Comment by sharwell** [comment] 2015-09-11 18:55
Duplicate of DotNetAnalyzers/StyleCopAnalyzers#1442 :expressionless: and fixed in the latest release.

**Closed** 2015-09-11 18:59 UTC
