### ISSUE TITLE
Inferred nullability of `Nullable<T>` is lost in type arguments' inference

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#35984] opened 2019-05-27 17:17 UTC
**Version Used**: 

Branch master (22 May 2019)
Latest commit 04252e by Neal Gafter:
Unskip passing tests. (#35856)

Fixes #35611

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
public class C {
    public void M(int? i, string? s) {
        i = 5;
        s = "";

        // both variables cannot contain null, no warnings
        s.ToString();
        i.Value.ToString();
        
        // assign variables with their inferred types
        s = Id(s);
        i = Id(i);

        // s is still not null whereas i became nullable
        s.ToString();
        i.Value.ToString();
    }
    
    public T Id<T>(T t) => t;
}
```

**Expected Behavior**:
No warnings.

**Actual Behavior**:
`warning CS8629: Nullable value type may be null.` at the last line of `M`.

It seems that unlike reference nullable types inferred nullability of `Nullable<T>` does not affect type arguments' inference.

**Comment by AlekseyTs** [comment] 2019-06-13 18:03
I think the current behavior is in line with LDM decisions.
CC @MadsTorgersen

**Comment by jcouv** [comment] 2019-06-19 00:22
I agree that the current behavior is by design.
For the `int?` we infer `i = Id<int?>(i);` so it is possible (based on the API signature) that a null is assigned to `i` at that point.
I'll go ahead and close. Thanks

**Closed by jcouv** 2019-06-19 00:22 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Nullable Reference Types
