### ISSUE TITLE
Positional records should track properties' states throguh constructors and deconstruction methods

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#49741] opened 2020-12-02 17:59 UTC
**Version Used**: 
```
Branch master (1 Dec 2020)
Latest commit 195cc4b by Manish Vasani:
Merge pull request #49120 from huoyaoyuan/foreach-var

Do not cast when refactoring 'foreach var'
```

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable

var r = new R("", "");
r.s1.ToString();
r.s2.ToString();
var (s1, s2) = r;
s1.ToString();
s2.ToString();

record R(string? s1, string? s2);

namespace System.Runtime.CompilerServices
{
  public static class IsExternalInit { }
}
```

**Expected Behavior**:
No warnings. The compiler knows I'm passing a non-nullable arguments to the positional record's parameters and it generated a constructor that just passes them to the corresponding properties

**Actual Behavior**:
`r.s1.ToString();`
`r.s2.ToString();`
`s1.ToString();`
`s2.ToString();`
All have `CS8602: Dereference of a possibly null reference.` warnings

**Notes**
The compiler already does a similar trick with `new ValueTuple<...>(...)` and `new Nullable<...>(...)` and tracks the assignments from arguments to `.ItemN` and `.Value` properties
Positional records look very similar and it's not convenient when I lose nullability information just by packing a couple of values in a record or deconstructing them into separate variables.
It's understandable that the compiler currently doesn't know whether a constructor will pass parameters' values to properties with the same names but I think Roslyn can annotate members it generated itself and which therefore have known behavior. 

Another approach could be implementing a new `[MemberNotNullIfNotNull(paramName)]` annotation that would solve a more general case of any constructor that just propagates parameters to properties. In this case the compiler can just emit it for the constructors it generates in positional records.

**Comment by jaredpar** [comment] 2020-12-07 18:22
@RikkiGibson @jcouv think this is an interesting one to think about. I share the intuition about this matching tuples. Is there a reason that we didn't give records the same flavor of behavior here?

**Comment by jcouv** [comment] 2020-12-07 18:34
@jaredpar I agree. This is an oversight.

I took another look to see what issues we have around nullability in records:
- tracking through deconstruction (OP)
- warning on custom methods with incorrect nullability (https://github.com/dotnet/roslyn/projects/57#card-45466552)
- synthesizing methods with proper nullability (https://github.com/dotnet/roslyn/issues/47627)

Note: we properly track through `with` already.

**Comment by TessenR** [comment] 2020-12-07 18:57
@jcouv I originally assumed that the current behavior is because it might be impossible to distinguish the following records from their metadata. Please correct me if I'm wrong and it's actually possible.

```
record R1(string? x, string? y);

record R2
{
  public R2(string? x, string? y) { }
  public string? x { get; init; }
  public string? y { get; init; }
  public void Deconstruct(out string? x, string? y) => x = y = null;
}
```

For `R1` tracking members through its constructor and deconstruction method makes sense but for `R2` there are no guarantees about its implementation.

Are there any plans already on how this will be handled? I can think of a few options:
- marking compiler-generated members with some attribute
- assuming all records are well-behaving and nobody will write `R2` as in this comment
- introducing annotations that could solve a more general case for any constructor / deconstruction such as `[MemberNotNullIfNotNull(memberName)]` / `[NotNullIfMemberNotNull(memberName)]` and generate them for the compiler's implementation of ctor/deconstruction. This one won't track nested slots though. However it will make it possible to annotate any constructor / deconstruction method that just assigns parameters to known members and returns known members' values from deconstruction which might come handy in other scenarios not tied to records or compiler-known types such as tuples.

**Comment by jcouv** [comment] 2020-12-07 19:05
@TessenR Nullability analysis already doesn't distinguish auto-properties from custom properties, which certain implementations could break ([example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGSAmIDUAfAAQCYBGAWACgBiAOwFcAbBiYBuAAjhpbcoIGZ2xdgGF2Ab0rtpQwQRIAGAPzsAChPYBzODADc7KDv0BfKTIFDFK1UQ3aYGggHZ29JiYM6Nx9qYoz2M2kLAgAWdgBZAAoASgkggLV2AF5XRgZdBIDVADoAFQB7AGUYBABLGk1YzP9E6SyZGxT2ACIWmrrpG3zi0oqqmI6ZP2MgA=)). 
I think it's reasonable to rely on assumptions for `Deconstruct` too.

It's more edge-case, but technically, you could have a custom implementation of `ValueTuple` or `Nullable` which breaks the compiler's assumptions as well ;-)

**Comment by TessenR** [comment] 2020-12-07 19:14
Yeah, I know, there are many assumptions in the analysis that might not be valid ツ

I wonder though what pattern will you suggest for constructor/deconstruction? The same name for members/parameters? Will it be limited to records in this case? Sound useful in other places as well. I personally have some types in solutions I work with where the additional checks / suppresses are required because deconstruction loses information about already checked members that it returns. However different naming conventions for members and parameters might make using it a bit cumbersome. "Case-insensitive the same name" might cover most scenarios.

**Comment by RikkiGibson** [comment] 2020-12-07 19:28
This is a dupe of #44763 which stalled out because we don't have a way to identify the primary constructor from metadata.

**Comment by jaredpar** [comment] 2020-12-07 19:33
Good catch. Will dupe and let's have discussion over there.

**Comment by TessenR** [comment] 2020-12-07 19:33
@RikkiGibson @jaredpar Well, this one also raises the same question about the deconstruction method ツ But I hope you'll just add it to #44763

**Closed by jaredpar** 2020-12-07 19:33 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, New Language Feature - Records, untriaged

**Comment by RikkiGibson** [comment] 2020-12-07 19:51
Ah! Yeah, I think we could try to recognize a well-known Deconstruct implementation and use the property flow state to determine the output state. The same issues as with primary constructors may apply.
