### ISSUE TITLE
Pressing Enter in .cs File Throttles CPU 25-30% for Over 30 Seconds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52751] opened 2021-04-19 23:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pressing-Enter-in-cs-File-Throttles-CPU/1400509)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.10.1]
Please see the attached recording.  Simply pressing the Enter button several times spikes the CPU to over 30% and then oscillates between 25-30% for 30-40 seconds.

---
#### DragonSpark on 4/16/2021, 09:32 AM: 

<p>Note that this may be related to <a target='_blank' href="https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587">https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587</a> but that has typically shown the grief in <code>.razor</code> files.  Here this issue is occurring within a <code>.cs</code> file which is new/different in my experience.</p>

#### Feedback Bot on 4/19/2021, 00:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-04-19 23:17
The root cause of this is 6,904 Workspace_Recoverable_RecoverRoot operations are resulting in 104,394 threads being created by the ObjectReader trampoline:

https://github.com/dotnet/roslyn/blob/3abea95fa70ae426e50397515f665f80bb33d5a9/src/Compilers/Core/Portable/Serialization/ObjectReader.cs#L190-L205

At face value, this situation could be viewed as just another duplicate of #23331. However, a closer look at the events reveals some low hanging fruit for substantial optimization. Of 104,394 threads created in 47 seconds, 103,743 (99.4%) are created by thread 36708, which means this thread is repeatedly creating a new thread, waiting for it to complete, and then creating another new thread instead of reusing the previous one.

<details>
<summary>Expand for screenshot showing a large number of threads created by one RecoverRoot operation</summary>

![image](https://user-images.githubusercontent.com/1408396/115314542-3ed86700-a12a-11eb-92a0-edb7b1258833.png)

</details>

By ensuring that a single `ObjectReader` instance creates the minimum number of additional threads (e.g. by placing the threads in a `Stack<SingleThreadedTaskScheduler>` for the duration of the reader, or by creating a `ThreadLocal<SingleThreadedTaskScheduler>` to make all trampolines from the same source thread use the same target thread, we would dramatically improve performance in the near term.

**Closed** 2021-05-11 04:09 UTC
Labels: 4 - In Review, Area-IDE

**Comment by CyrusNajmabadi** [comment] 2021-05-11 20:25
> Does that mean this fix won't be available until 16.11.x preview

That is correct.

**Comment by sharwell** [comment] 2021-05-11 20:28
Hi @Mike-E-angelo, unfortunately that is correct. This change impacted a lower level component so we are required to give it a bit more bake time to help ensure it doesn't cause any problems during deployment. It should be included in 16.11 Preview 1, which is the earliest point we were able to target once the issue was understood.

To the earlier comment, we're happy we could get this fixed. Sometimes it's hard to find the underlying performance issues in a product this big, but we really try to figure them out for cases where users are able to submit targeted performance recordings like you did. 👍
