### ISSUE TITLE
IDE0032  C# Use auto property [volatile and readonly properties]

### ISSUE THREAD

**Issue by MaximG1234** [dotnet/roslyn#26324] opened 2018-04-22 15:44 UTC
**Version Used**: 
VS 2017 15.6.6 - Compiler Version 4.7.2556.0

**Steps to Reproduce**:

1. Paste private readonly string _myrandomvar = "blah."; into class header
2. Paste private volatile bool _myboolean= false; into class header.

**Expected Behavior**:
No warning as nether of these properties can be expressed as a C# auto-property.

**Actual Behavior**:
IDE0032  C# Use auto property warning and blur out generated.

**Comment by benaadams** [comment] 2018-04-22 16:03
First `readonly` one could?
```csharp
private string _myrandomvar { get; } = "blah.";
```
Don't think the second one could as `volatile` couldn't be captured

**Comment by Neme12** [comment] 2018-04-22 19:49
Could you please provide a full sample so that we can reproduce this? It doesn't appear if you only have a field.

**Comment by Neme12** [comment] 2018-04-22 19:56
I'm seeing the correct behavior with readonly which is to generate a getter-only auto property as @benaadams pointed out.

**Comment by Neme12** [comment] 2018-04-22 19:57
The issue with volatile fields was fixed in #25431 and should be available in 15.8.

**Comment by sharwell** [comment] 2018-06-19 16:47
Duplicate of #25379

**Closed by sharwell** 2018-06-19 16:47 UTC
Labels: Area-IDE

**Comment by Neme12** [comment] 2018-06-20 09:00
@sharwell It's possible the `readonly` part of this is a duplicate of #25408 - the setter is always created when multitargeting.
