### ISSUE TITLE
.editorconfig File Editor Has Issue if No .cs Files Exist

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58610] opened 2022-01-04 22:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/editorconfig-File-Editor-Has-Issue-if-N/1612091)._

---
Here's what I did:

* I created a new console application (though I'm guessing this behavior doesn't matter what the project type is).
* I deleted the Program.cs file
* I right-clicked on the solution, and selected "Add New File"
* I created ".editorconfig" (using the "Text File" template)
* I double-clicked on the new .editorconfig file to edit it.

At this point, I would have expected to see the EditorConfig UI editor display, but I get an error instead:

! [image.png] (https://aka.ms/dc/image?name=Ba23c8147697446c48c58f082d546ba6d637750214953646691_20211213-134453-image.png&tid=a23c8147697446c48c58f082d546ba6d637750214953646691)

If I add a .cs file to the project, then the editor comes up as expected.

---
#### Feedback Bot on 12/13/2021, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/15/2021, 09:45 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 22:10
duplicate of https://github.com/dotnet/roslyn/issues/60235

**Closed by jmarolf** 2022-03-18 22:10 UTC
Labels: Bug, Area-Analyzers, Feature - Editor Config UI
