### ISSUE TITLE
Crash in solution sync with transitive reference

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#52578] opened 2021-04-12 18:42 UTC
_Originally posted by @Kevin-Andrew in https://github.com/dotnet/roslyn/issues/50257#issuecomment-818013011_

I go this error today. Coincidentally enough, it also seemed to appear right after I opened a file from the Solution Explorer, after just having opened a very large solution (147 projects with over 6,500 files). So Visual Studio was still very busy doing a lot of background work.

Here is the stack trace:
```
StreamJsonRpc.RemoteInvocationException: The project already transitively references the target project.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: The project already transitively references the target project.
      at Microsoft.CodeAnalysis.Solution.CheckCircularProjectReferences(ProjectId projectId, IReadOnlyCollection`1 projectReferences)
      at Microsoft.CodeAnalysis.Solution.WithProjectReferences(ProjectId projectId, IEnumerable`1 projectReferences)
      at Microsoft.CodeAnalysis.Project.WithProjectReferences(IEnumerable`1 projectReferences)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<UpdatePrimaryBranchSolutionAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteAssetSynchronizationService.<>c__DisplayClass2_0.<<SynchronizePrimaryWorkspaceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()
```
![image](https://user-images.githubusercontent.com/22459191/114439566-f6dfa000-9b7d-11eb-9ee0-af4c27038321.png)

**Comment by jasonmalinowski** [comment] 2021-04-12 18:51
So I don't quite know how the sync code is working here, but it looks like we're taking an old snapshot and trying to update it to match the in-proc version. But there is some implicit ordering that might be necessary there: if the old snapshot has two projects A and B where A references B, and we want to update it to a snapshot where B references A, then we need to remove the project references before adding references, or else we may have a moment where we have a circular reference.

**Comment by jasonmalinowski** [comment] 2021-04-12 18:53
Also just FYI to whoever looks at this bug that I changed the exception that's thrown in https://github.com/dotnet/roslyn/commit/84f1d7f61f9ad9cbe0005aed1ca4db2820c03bbc to make it clear that this was a circular reference exception which wasn't obvious by the really pithy exception message.

**Comment by sharwell** [comment] 2021-04-21 14:29
We could also create a partial order for projects according to their references in the _new_ solution, and update dependencies before updating a project. For the comment above, this would mean B gets updated first until the change that reverses the reference, at which point A gets updated first which breaks the cycle before it occurs.

**Comment by vdevappa** [comment] 2021-05-12 18:07
So, they closed my case:

https://developercommunity.visualstudio.com/t/streamjsonrpcremoteinvocationexception-the-project/1415417

Because they said mine is a duplicate of this one.

However, I just want to note that a month or so ago, I went through the trouble of creating a utility to analyze all the project files to see if I had any circular references.

It could not find any. I've double checked this - not sure why it thinks there is a circular dependency, but there is none in reality.

**Comment by jasonmalinowski** [comment] 2021-09-01 17:42
Another likely duplicate: https://developercommunity.visualstudio.com/t/Yellow-bar-error-when-switching-to-x64-b/1473761

**Comment by sharwell** [comment] 2021-10-04 22:34
Also filed as AB#1355334

Also filed as AB#1393945

**Closed** 2022-01-14 06:10 UTC
Labels: Bug, Area-IDE, Tenet-Reliability
