### ISSUE TITLE
C# semantic snippet inserts wrong line endings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67739] opened 2023-04-11 14:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-constructor-snippet-inserts-wrong-lin/10330013)._

---
[severity:It bothers me. A fix would be nice]
Steps:
1. Open a ".cs" file with CRLF line endings.
2. Inside a class, use the constructor snippet by typing "ctor" [AB#1784598](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1784598) and pressing tab.
    * Also applies to "prop" [AB#1758367](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1758367)
    * Also applies to "cw" [AB#1826432](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1826432)

Expected behaviour: the generated constructor respects the document line endings, and uses CRLF.
Actual behaviour: the generated constructor uses LF for the line endings.

---
#### Feedback Bot on 4/3/2023, 07:54 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/4/2023, 04:22 AM: 

(private comment, text removed)
#### Trinidad Sibajas Bodoque on 4/4/2023, 00:25 PM: 

(private comment, text removed)
#### Trinidad Sibajas Bodoque on 4/4/2023, 00:28 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/4/2023, 04:28 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/6/2023, 03:03 AM: 

(private comment, text removed)
#### Feedback Bot on 4/10/2023, 09:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tamasgonczi-tresorit** [comment] 2023-07-31 13:53
hi, do you have an ETA for fixing this strange behavior?

**Comment by JonasTickster** [comment] 2023-12-11 10:14
When will this be fixed? It is extremely annoying!

**Comment by Dean-NC** [comment] 2023-12-13 20:14
Still broken in 17.8.3

**Comment by CyrusNajmabadi** [comment] 2023-12-13 21:40
@JonasTickster @Dean-NC This bug is still open.  :)

Note: if you'd be interested in contributing a fix, we'd be happy to take it.  :)

**Comment by LeeIsMe77** [comment] 2023-12-22 16:51
I really love how the team is quick to add a bug, and extremely slow to fix it.  These are the kinds of things that make people want to move to Ryder.

Any update?

**Comment by CyrusNajmabadi** [comment] 2023-12-22 17:14
> I really love how the team is quick to add a bug, and extremely slow to fix it.  These are the kinds of things that make people want to move to Ryder.
> 
> Any update?

@LeeIsMe77 I don't repro this, and we haven't really changed anything here. 

That said, we'd be happy to take a fix from you if you're able to make a repro and find something in Roslyn that is causing this.

**Comment by LeeIsMe77** [comment] 2023-12-23 20:35
> > I really love how the team is quick to add a bug, and extremely slow to fix it.  These are the kinds of things that make people want to move to Ryder.
> > Any update?
> 
> @LeeIsMe77 I don't repro this, and we haven't really changed anything here.
> 
> That said, we'd be happy to take a fix from you if you're able to make a repro and find something in Roslyn that is causing this.

The response we broke it but you can fix it yourself is obviously Microsofts forte with all issues now, and I can't help but feel alienated as of late being a windows-first .NET developer. So question: is your team directly working on Visual Studio, or just the Roslyn compiler?  Because I reported this directly from Visual Studio and was triaged here, while simultaneously closing my ticket, and so have a number of other people dating back to June.  If this is the wrong place to report it, great - but that response is everything to hate about Microsofts embrace of open source.

**Comment by CyrusNajmabadi** [comment] 2023-12-23 20:43
> The response we broke it

It's very possible something else broke this. As I mentioned, we haven't been able to repro this. So it's likely something strange about a particular configuration (maybe with extensions)

> but you can fix it yourself 

This is the benefit of open source though. As a team with limited resources, we will not be able to get to all issues. While we done many thousands a year, that still won't address everything hit by everyone. An open source world makes it so that you have control here and can invest in areas that we may not be able to resolve for quite some time (assuming this even is in Roslyn in the first place). 

> So question: is your team directly working on Visual Studio, or just the Roslyn compiler?

Both. Roslyn Powers many things in the vs experience. However, something like snippets still goes through many layers. And many components (including other extensions) can get involved and cause subtle breaks. 

> but that response is everything to hate about Microsofts embrace of open source.

Prior to us being open source, there was no recourse on a bug we could not repro. It was simply unfixable.  At least on the open source world the community can work on improvements, and we will happily work with you on that and will happily take contributions. If you hate that about our open source philosophy, that's not something we can really do anything about.

**Comment by CyrusNajmabadi** [comment] 2023-12-23 21:05
Oh, good news.  @akhera99 thinks we have a repro for this.  :)  That will def help with tracking down what the offending issue :)

**Comment by LeeIsMe77** [comment] 2023-12-23 21:21
> Oh, good news. @akhera99 thinks we have a repro for this. :) That will def help with tracking down what the offending issue :)

Thank you for the update, and thank @akhera99 for the reproduction. 

I don't intend to sound angry at you, but the past several years dealing with agile release cycles, guinea pig testing on users with experimental features, and various other issues that impact expected behaviors and productivity across Microsoft (like the atrocious file explorer revamp with async issues) are making it very frustrating to remain a happy developer.

**Comment by CyrusNajmabadi** [comment] 2023-12-24 03:21
I don't believe the prior methods were better. Quality was worse, and you had to then wait 3 years sometimes hoping for a fix to your issue to come. And if it didn't meet the bar, that was that. No recourse at all. :-/

I remember those days. The situation presently is much much better :-)

**Comment by Dean-NC** [comment] 2023-12-24 04:18
For me, endings are changed from `CRLF` to `Mixed` as shown in VS lower-right, because my file starts out CRLF and the constructor snippet adds lines with `LF`, causing it to be mixed. I can reproduce it constantly in 17.8.3. It doesn't happen to me on properties using `prop`.

**Comment by andy-smith-work** [comment] 2024-01-10 20:42
Here's a workaround that I'm using.  I edited the `ctor.snippet` file in `C:\Program Files\Microsoft Visual Studio\2022\Professional\VC#\Snippets\1033\Visual C#` and changed the `<Title>` and `<Shortcut>` from `ctor` to `cstr`.  I can type `cstr` + TAB to insert the constructor, and the file stays CRLF.

It seems like there is something overriding the `ctor` snippet file, because `ctor` still works and changes the file to Mixed line endings.  

Before changing the shortcut in the snippet file, I added some extra code inside the constructor.   Typing `ctor` + TAB did not insert the extra code and changed the file to Mixed.  However, typing `ctor` + ESC + TAB inserted the contents from the snippet file, including the extra code, and left the file as CRLF.

(VS2022 Pro, v17.8.4)

**Comment by madmox** [comment] 2024-01-12 10:21
Issue still exists in `17.8.4`.

> Before changing the shortcut in the snippet file, I added some extra code inside the constructor. Typing ctor + TAB did not insert the extra code and changed the file to Mixed. However, typing ctor + ESC + TAB inserted the contents from the snippet file, including the extra code, and left the file as CRLF.

Oh, that's a nice workaround. Just type `ctor` + ESC + TAB rather than `ctor` + TAB.

The bug probably has to do with intellisense overriding the normal behavior then, because when I disable intellisense completion list (`Tools -> Options -> Text Editor -> C# -> IntelliSense -> disable "Show completion list after a character is typed"`), then `ctor` + TAB. behaves as expected (consistent line endings).

**Comment by sharwell** [comment] 2024-01-12 14:20
@LeeIsMe77 Thanks for working with us here! I know the open-source approach is strange when you first start interacting with it, but over my career (20 years now) it seems to be essentially the same as the way closed-source projects handle these issues. The only difference in closed-source is members of the public don't have access to see the comments where someone said the team doesn't have resources available to fix an issue.

These days I think I'm more frustrated every time I hit a bug or limitation in closed source software where I _know_ I'm hitting an edge case but even if I volunteer my time there is simply no way for me to fix the issue for them. Even worse, there are several cases over the past couple years where the company wouldn't even let me talk to a software developer about it at all (for filing a bug report).

**Comment by akhera99** [comment] 2024-11-13 21:39
Fixed in VS

**Closed by akhera99** 2024-11-13 21:39 UTC
Labels: Area-IDE, New Feature - Semantic Snippets

**Comment by sharwell** [comment] 2024-12-10 17:11
Here's the internal PR for reference:
https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/526751

Fixed in 17.10 Preview 2
