### ISSUE TITLE
[Test Failure] Unobserved OperationCancelledException in prtest/win/dbg/eta on PR #616

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9361] opened 2016-03-01 20:43 UTC
PR: [#616](https://github.com/dotnet/roslyn-internal/pull/616) *Reference VS MEF Via NuGet* by @Pilchie
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/677/

```
11:38:05 System.AggregateException: Exceptions found in the exception log ---> Microsoft.Cci.PeWritingException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
11:38:05    at System.Threading.CancellationToken.ThrowOperationCanceledException()
11:38:05    at System.Threading.CancellationToken.ThrowIfCancellationRequested()
11:38:05    at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& pdbIdOffsetInPortablePdbStream, Int32& entryPointToken, MetadataSizes& metadataSizes) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\MetadataWriter.cs:line 2119
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 135
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 97
11:38:05    --- End of inner exception stack trace ---
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 101
11:38:05    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1869
11:38:05    --- End of inner exception stack trace ---
11:38:05    at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16
11:38:05    at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
11:38:05 --- End of stack trace from previous location where exception was thrown ---
11:38:05    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:38:05    at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
11:38:05    at Roslyn.Hosting.Test.EditorTestAppAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 147
11:38:05    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
11:38:05    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
11:38:05 ---> (Inner Exception #0) Microsoft.Cci.PeWritingException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
11:38:05    at System.Threading.CancellationToken.ThrowOperationCanceledException()
11:38:05    at System.Threading.CancellationToken.ThrowIfCancellationRequested()
11:38:05    at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& pdbIdOffsetInPortablePdbStream, Int32& entryPointToken, MetadataSizes& metadataSizes) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\MetadataWriter.cs:line 2119
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 135
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 97
11:38:05    --- End of inner exception stack trace ---
11:38:05    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 101
11:38:05    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1869<---
```

**Comment by davkean** [comment] 2016-03-07 00:39
Dupe of https://github.com/dotnet/roslyn/issues/9308

**Closed by davkean** 2016-03-07 00:39 UTC
Labels: Bug, Contributor Pain
