### ISSUE TITLE
SymbolFinder.FindImplementedInterfaceMembersAsync documentation is confusing and inaccurate

### ISSUE THREAD

**Issue by Stevie-O** [dotnet/roslyn#34588] opened 2019-03-29 15:12 UTC
The documentation for `SymbolFinder.FindImplementedInterfaceMembersAsync` is sparse, but the summary is:
> Find symbols for declarations that implement members of the specified interface symbol

That's not what it does.  What it does is:

> Find interface members that the specified symbol implements.

As an added bonus, if you actually pass the symbol for an interface, you get a NullReferenceException (presumably when the code tries to use `symbol.ContainingType.TypeKind`.)

**Comment by CyrusNajmabadi** [comment] 2019-03-29 20:04
> That's not what it does. What it does is:
>    Find interface members that the specified symbol implements.

Right, as per it's name.  It "Finds" the "Implemented Interface Members" of the current symbol you're on.

**Comment by CyrusNajmabadi** [comment] 2019-03-29 20:04
>documentation is confusing and inaccurate

Feel free to submit a PR that improves things here.  Thanks!

**Comment by CyrusNajmabadi** [comment] 2022-02-08 01:59
No movement by customer.  Closing out as by design.

**Closed by CyrusNajmabadi** 2022-02-08 01:59 UTC
Labels: help wanted, Area-IDE, Documentation
