### ISSUE TITLE
Visual Studio 2019 crashing when click RMB on rule in Analyzers' dependencies.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40720] opened 2020-01-03 16:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/549993/visual-studio-2019-crashing-when-click-rmb-on-rule.html)._

---
Visual Studio 2019 crashing when I added too many analyzers to project.

Steps to reproduce:
-  Create .NET Standard library with setup:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreAnalyzers" Version="0.2.0-dev" />
    <PackageReference Include="AsyncFixer" Version="1.1.6" />
    <PackageReference Include="codecracker.CSharp" Version="1.1.0" />
    <PackageReference Include="DotNetAnalyzers.DocumentationAnalyzers.Unstable" Version="1.0.0.59" />
    <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2" />
    <PackageReference Include="ErrorProne.NET.Structs" Version="0.1.2" />
    <PackageReference Include="IDisposableAnalyzers" Version="2.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="2.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="2.9.2" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="16.0.102" />
    <PackageReference Include="NuGet.CommandLine" Version="4.9.4" />
    <PackageReference Include="Puma.Security.Rules" Version="2.1.0" />
    <PackageReference Include="RefactoringEssentials" Version="5.6.0" />
    <PackageReference Include="Roslynator.Analyzers" Version="2.0.0" />
    <PackageReference Include="Roslynator.CodeFixes" Version="2.0.0" />
    <PackageReference Include="SecurityCodeScan" Version="3.2.0" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.1.1.114" />
    <PackageReference Include="Wintellect.Analyzers" Version="1.0.6" />
    <PackageReference Include="xunit.analyzers" Version="0.10.0" />

    <PackageReference Update="NETStandard.Library" PrivateAssets="all" />
  </ItemGroup>

</Project>
```
- Click RMB on any rule in analyzers window.

This produces event as below:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersCommandHandler.UpdateSeverityMenuItemsChecked()
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersCommandHandler.UpdateDiagnosticContextMenu()
   at Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.ContextMenuController.ShowContextMenu(System.Collections.Generic.IEnumerable`1<System.Object>, System.Windows.Point)
   at Microsoft.Internal.VisualStudio.PlatformUI.ContextMenuController.ShowContextMenu(System.Collections.Generic.IEnumerable`1<Microsoft.Internal.VisualStudio.PlatformUI.IContextMenuPattern>, System.Windows.Point, System.Func`2<Microsoft.Internal.VisualStudio.PlatformUI.IContextMenuPattern,Microsoft.Internal.VisualStudio.PlatformUI.IContextMenuController>)
   at Microsoft.Internal.VisualStudio.PlatformUI.ContextMenuController.ShowContextMenu(System.Collections.Generic.IEnumerable`1<Microsoft.Internal.VisualStudio.PlatformUI.IContextMenuPattern>, System.Windows.Point)
   at Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeView.OnContextMenuOpening(System.Windows.Controls.ContextMenuEventArgs)
   at System.Windows.FrameworkElement.OnContextMenuOpeningThunk(System.Object, System.Windows.Controls.ContextMenuEventArgs)
   at System.Windows.Controls.ContextMenuEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.ContentElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.ContentElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Controls.PopupControlService.RaiseContextMenuOpeningEvent(System.Windows.IInputElement, Double, Double, Boolean)
   at System.Windows.Controls.PopupControlService.ProcessMouseUp(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(System.Object, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(System.Windows.Input.ProcessInputEventHandler, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

---
#### Visual Studio Feedback System on 4/29/2019, 00:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/1/2019, 10:08 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 12/31/2019, 00:23 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2020-01-08 21:01
@mavasani can you see if this repros and if so should this be on PS

**Comment by mavasani** [comment] 2020-01-08 21:03
> Microsoft.VisualStudio.LanguageServices.Implementation.SolutionExplorer.AnalyzersCommandHandler.UpdateSeverityMenuItemsChecked

@jinujoseph it is owned by our team. We would need the crash dump though.

**Comment by mavasani** [comment] 2020-01-08 21:04
Ah, I see the dump is attached to the DC feedback ticket.

**Comment by mavasani** [comment] 2020-01-10 23:42
This is a duplicate of https://github.com/dotnet/roslyn/issues/36304, which was fixed few months ago. I noticed from the developer community ticket that you are VS2019 build `16.0.28803.202`. Can you please move to the latest VS2019 16.4 release build? That has the fix for this crash.

**Closed by mavasani** 2020-01-10 23:42 UTC
Labels: Area-IDE, Bug
