### ISSUE TITLE
[Bug] Primary constructor doesn not hadle structural equality for struct Equals()

### ISSUE THREAD

**Issue by MadL1me** [dotnet/roslyn#70963] opened 2023-11-25 00:55 UTC
**Version Used**: 

SDK.NET:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20
 
 Env: 
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/
 
 Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71
 
**Steps to Reproduce**:

1. Create `struct` type with primary constructor
2. Try to call `Equals()` on 2 different objects
3. Return true, because compiler thinks it is not used the parameter for `stuct`

Reproduction Repo: https://github.com/MadL1me/PrimaryConstructorExample/tree/main 

**Expected Behavior**:

Compiler should add fields/properties if it is a `struct` type, even if the primary constructor parameter is not used. 

It is not very convinient for developer experience and creates confusion, because now we need to remember that somtimes the field adds, sometime its just not.

The example above should return `False`.

**Actual Behavior**:

Compiler does not add field from primary constructor, because it is not used in the code of the struct. However, the properties are used by reflection of `ValueType.Equals()` default implementation.

The example above returns `True`.

**Comment by DoctorKrolic** [comment] 2023-11-25 10:26
Nop, this behavior is by design. Primary constructors on non-record types capture parameter value as a field only if the parameter is used in places, where it requires storage, e.g. in an instance method. This is implemented this way so you can assign primary constructor parameters to other members (e.g. initialize a property from a primary constructor parameter) and not create implicit double storage. Yes, this design has it flaws, the main one as you've described is the lack of transparency whether the field is captured or not, but the way it works gives developers a lot more flexibility and control over how primary constructor's parameters are used

**Comment by CyrusNajmabadi** [comment] 2023-11-25 17:34
Closing out. This is by design. These are not records, they are structs. Primary constructors do not create fields in structs unless you use them.  That's very intentional.

**Closed** 2023-11-25 17:34 UTC
Labels: Area-Compilers, untriaged
