### ISSUE TITLE
Convert var to explicit type introduces spurious nullable type

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#42126] opened 2020-03-03 03:19 UTC
**Version Used**: master

**Steps to Reproduce**:

```c#
#nullable enable

IEnumerable<string> strings = Array.Empty<string>();

foreach (var s in strings)
{
}
```

Invoke "Use explicit type instead of 'var'" on the foreach variable declaration.

**Expected Behavior**:

```c#
foreach (string s in strings)
{
}
```

**Actual Behavior**:

The `string?` type is used:

```c#
foreach (string? s in strings)
{
}
```

**Comment by sharwell** [comment] 2020-03-03 04:39
Duplicate of #41243

**Closed** 2020-03-03 21:53 UTC
Labels: Resolution-Duplicate
