### ISSUE TITLE
Closure causes anonymous type to allocate even if unused

### ISSUE THREAD

**Issue by Drawaes** [dotnet/roslyn#22589] opened 2017-10-07 13:29 UTC
**Version Used**: 
Latest netcore and 2.0
**Steps to Reproduce**:

1. Method that has a closure at the bottom of method
2. Add an if statement and pass in false to exit early
3. The anonymous type is created and allocated even though the code is never touched

**Expected Behavior**:
Only allocate if the type is actually needed

**Actual Behavior**:
Type is allocated everytime

[Repro Code Solution](https://github.com/Drawaes/dotnetXperiments/blob/master/WhyUAllocate/WhyUAllocate/TestClass.cs)

When disassembling with ILdasm you can clearly see the problem (it news the annon type at the top of the method)

![image](https://user-images.githubusercontent.com/16406969/31308272-df0a6af6-ab6b-11e7-8cd0-7f17d138933b.png)

This was noticed during refactoring of SslStream internal classes

/cc @benaadams @stephentoub  - This was the allocation seen during testing

**Comment by mellinoe** [comment] 2017-10-21 05:57
I've hit this in a library of mine as wele.

**Comment by svick** [comment] 2018-02-20 11:40
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/20777.

**Comment by jaredpar** [comment] 2018-08-31 23:39
Closing as a dupe of #20777

**Closed by jaredpar** 2018-08-31 23:39 UTC
Labels: Area-Compilers
