### ISSUE TITLE
Why assign Func using ternary operator give me Error ?

### ISSUE THREAD

**Issue by leandromoh** [dotnet/roslyn#16743] opened 2017-01-25 15:56 UTC
Why the statements 1 and 2 compile, but 3 give me the following error ?

> Error CS0173 Type of conditional expression cannot be determined because there is no implicit conversion between 'lambda expression' and 'lambda expression

1. `var func = step >= 0 ? (Func<int, int, bool>)((a, b) => a >= b) : (a, b) => a <= b;`
2. `var func = step >= 0 ? new Func<int, int, bool>((a, b) => a >= b) : (a, b) => a <= b;`
3. `Func<int, int, bool> func = step >= 0 ? (a, b) => a >= b : (a, b) => a <= b; `

**Comment by zippec** [comment] 2017-01-25 17:26
@leandromoh Because in order to successfully determine type of ternary expression both branches must be of the same type or one must be implicitly convertible to the other. Expressions "target" does not contribute to type inference anywhere in C# as far as I know.
Similar problem:
```C#
public T GetValue<T>(string name);
public void Process(int value);
...
Process(GetValue("index")) //Fails to compile even though T could be inferred to be int
```
However there have been some proposals. I would love to see them implemented.

**Comment by zspitz** [comment] 2019-08-01 15:19
This is a duplicate of #36430.

**Comment by leandromoh** [comment] 2021-03-14 17:54
resolved with C# 9 feature "Target-typed conditional expressions".

both examples works

1) 
```c#
var func = true
    ? (Func<int, int>)(a => a + 1) 
    : a => a - 1;
``` 
2)
```c#
Func<int, int> func = true 
    ? a => a + 1 
    : a => a - 1;
```

**Closed** 2021-03-14 17:54 UTC
Labels: Area-Language Design, Language-C#, Question
