### ISSUE TITLE
Setting not persisted: Completion list after delete

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#16393] opened 2017-01-10 17:24 UTC
**Version Used**: 2.0.0.61308

_Text Editor > C# > IntelliSense > Show completion list after a character is deleted_ setting does not seem to be preserved.

1. Export settings
2. Change the setting above
3. Import the exported setting

**Expected Behavior**: The setting to be restored to the state at the time of export

**Actual Behavior**: Setting not influenced by the import

**Comment by Pilchie** [comment] 2017-01-20 18:07
https://github.com/dotnet/roslyn/issues/16247

**Comment by Pilchie** [comment] 2017-01-20 18:08
Oops - actually a duplicate of https://github.com/dotnet/roslyn/issues/14810.

**Closed by Pilchie** 2017-01-20 18:08 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
