### ISSUE TITLE
No results for some C#/VB options in quick launch

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#26579] opened 2018-05-03 00:47 UTC
**Version Used**: 2.8.0-beta4 (15.8 P1 Int Preview)

**Steps to Reproduce**:

1. Ctrl+Q (open Quick Launch)
2. Search for 'Decompiler'

Alternatively:
1. Tools > Options
2. Search for 'Decompiler'

**Expected Behavior**:
There should be a search result for the page containing the _Tools > Options > Text Editor > C# > Advanced > Enable Navigation to decompiled sources_ option.

**Actual Behavior**:
No results in quick launch:
![image](https://user-images.githubusercontent.com/5387680/39555642-aa2b140e-4e2f-11e8-9022-5bcfd8969e08.png)

No results in options dialog:
![image](https://user-images.githubusercontent.com/5387680/39555704-2f180c26-4e30-11e8-9c1a-d522a1d16abb.png)

The fix is quite simple and just involves updating [this line](https://github.com/dotnet/roslyn/blob/0923887afc2fb1858ad2e0742752f49d96714149/src/VisualStudio/CSharp/Impl/VSPackage.resx#L144-L146), its VB analog, and all of its localized versions with keywords for every supported C# and VB option.

I've only tested the 'decompiler' feature but given how obscure quick launch knowledge is, odds are there are other C# and VB options that don't have keywords, so I'd take some time to try searching for all C#/VB commands.

To prevent similar bugs in the future, I'd add a comment indicating this requirement to the [C# Options Page](https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml) and to its VB analog.

Given the density of Tools Options, if an option isn't searchable, its discoverability is severely limited.

**Comment by jinujoseph** [comment] 2018-06-20 16:17
Duplicate of #27171

**Closed by jinujoseph** 2018-06-20 16:17 UTC
Labels: Area-IDE
