### ISSUE TITLE
Narrowing conversion required for future `Option Strict On` should not be marked as redundant when `Option Strict Off` at least by default

### ISSUE THREAD

**Issue by tats-u** [dotnet/roslyn#73176] opened 2024-04-22 13:14 UTC
**Version Used**: 

SharpLab main (20 Jan 2024)

**Steps to Reproduce**:

1. Create a new VB project (console app or class library is easier)
2. Create a `Function` that takes a `Double` argument and returns `Integer`
3. Implement it using `CInt`

```vbnet
Imports System
Public Class C
    Public function M(a As double) As integer
        Return CInt(a * 180.0 / Math.PI)
    End Function
End Class
```

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

https://sharplab.io/#v2:EYLgtghglgdgNAGxAN2AHwJJgA4HsBOALgM4AEAygJ7GECmYAsAFAAKArsAlAMakDCCCMTJ9mpcaXacepAGZsY3QlFwxSAWQAUEUgEEyAE1wcEtAJR6ysOgHNa+MRKcAlWoTb41fDDELbSAFSkAIwAHAAMAHThpAD0GhCEABaRLBhmjuIAojAGpABiCkoqMMw5eQJCxEA===

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

IDE0004

**Expected Behavior**:

No suggestions by default

**Actual Behavior**:

IDE0004 for `CInt`, which can be omitted for the time being but will be required when switched to `Option Strict On` in the future

**Comment by sharwell** [comment] 2024-04-22 13:32
I'm undecided on this one. @AlekseyTs do you have thoughts on what the desired behavior here is?

**Comment by tats-u** [comment] 2024-04-22 14:00
Such narrowing conversions may be marked as redundant like widening ones by modifying `.editorconfig` (e.g. "forcibly mark even mark narrowing conversions as redundant"), in my opinion.
And an important background is the default value of `Option Strict` is Off.

**Comment by AlekseyTs** [comment] 2024-04-22 17:03
> do you have thoughts on what the desired behavior

No

**Comment by sharwell** [comment] 2024-04-22 17:40
I'm going to close this as By Design for two reasons:

1. The historical argument provided by @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/73176#issuecomment-2070223131
2. On review, I found that changing the code from `Option Strict Off` to `Option Strict On`, a code fix is provided for the new compiler error `BC30512` that inserts the exact same `CInt` cast that was previously removed.

**Closed by sharwell** 2024-04-22 17:40 UTC
Labels: Area-IDE, Language-VB, IDE-CodeStyle, untriaged, Feature - IDE0004

**Comment by tats-u** [comment] 2024-04-23 11:03
That's disapointing. Do you have a plan to prevent the Analyzer from marking such conversions as redundant by configuring `.editorconfig` (not by default but just optional)?

**Comment by CyrusNajmabadi** [comment] 2024-04-23 13:37
@tats-u you can use editorconfig to disable analyzers on any files you don't want them running on.  That is already supported today.

**Comment by tats-u** [comment] 2024-04-23 14:15
@CyrusNajmabadi It disables the detection of widening conversions, unconditionally redundant, in designated files, too, of course, doesn't it?

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0004

I mean, I have wanted to know whether you have the plan to allow Analyzer to disable *only* narrowing conversion detection *without disabling* wideing ones detection by *optional* configuration (e.g. `.editorconfig` & i.e. not by default).

**Comment by CyrusNajmabadi** [comment] 2024-04-23 14:26
> I mean, I have wanted to know whether you have the plan to allow Analyzer to disable only narrowing conversion detection

No. There is no plan to ever do that. 

Generally speaking, we add flexibility and options when there is a reasonable customer demand. This usually means some significant percentage of the user base asking for it. Absent that, we do not add one-off options every time a single person asks for it. That path is untenable and leads to massive explosion in complexity.  

As the feature is working as intended, and we've gotten zero pieces of feedback on the behavior in the entire time roslyn had been around, and the feature has worked the way, we will not be changing anything here. Thanks!

**Comment by tats-u** [comment] 2024-04-23 14:42
That's a shame, but I'm glad to hear about your plan about this feature.

**Comment by tats-u** [comment] 2024-04-23 15:25
If this weren't used as a part of Visual Studio, I won't send such an issue and would focus on C#.
