### ISSUE TITLE
MoveTypeCodeRefactoringProvider does not work on new project system

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#16138] opened 2016-12-29 16:35 UTC
**Version Used**: Visual Studio 2017 RC2

**Steps to Reproduce**:

1.  Create a netstandard project that uses the new project system
2. Change the name of the class to be different from the filename
3.  Invoke MoveTypeCodeRefactoringProvider

**Expected Behavior**:
File is renamed

**Actual Behavior**:
refactoring fails
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.RemoveDocumentCore(DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentRemoved(DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass19_0.<InvokeCoreAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Pilchie** [comment] 2016-12-31 23:05
Same issue as https://developercommunity.visualstudio.com/content/problem/3086/rename-file-to-nullreferenceexception.html (internal VSO bug 293456).  Feel free to close that as a dupe of this.

**Comment by Pilchie** [comment] 2017-01-20 20:33
Dupe of #16546.

**Closed by Pilchie** 2017-01-20 20:33 UTC
Labels: Area-IDE, Bug
