### ISSUE TITLE
[Proposal] typeof as C++11 decltype

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#3281] opened 2015-06-03 16:03 UTC
Sometimes I want to write something like

```
internal class Class
{
    private readonly IReadOnlyList<int> values;

    internal Class(typeof(values) values)
    {
        this.values = values;
    }
}
```

or

```
internal class Class
{
    private IReadOnlyList<int> values;

    internal void SetValues(typeof(values) values)
    {
        this.values = values;
    }
}
```

Let's on compilation real type will be substituted

```
internal class Class
{
    private readonly IReadOnlyList<int> values;

    internal Class(IReadOnlyList<int> values)
    {
        this.values = values;
    }
}
```

or

```
internal class Class
{
    private IReadOnlyList<int> values;

    internal void SetValues(IReadOnlyList<int> values)
    {
        this.values = values;
    }
}
```

**Comment by dimaaan** [comment] 2015-06-03 18:29
Use type aliases for that.
`using MyList =IReadOnlyList<int>`

**Comment by KalitaAlexey** [comment] 2015-06-03 18:59
@dimaaan I know about aliases, but more clear way will be to use typeof.

**Comment by dimaaan** [comment] 2015-06-03 19:55
@KalitaAlexey More clear way to do what? 
Could you provide an example where decltype can give some profit.
What i see is: 
1. that code harder to understand (we have to check `values` type to get ctor paratemer type)
2. It don't makes code shorted
3. changing type of `values` can lead to unexpected behavior when method is overridden.
4. it does not save us from refactoring, when type is changed

**Comment by HaloFour** [comment] 2015-06-03 21:04
I agree.  This doesn't appear to solve anything that aliasing doesn't already solve.  You example is doubly confusing since you have both a field and a parameter named `values` so the `typeof` expression seems circularly referential.

**Comment by aluanhaddad** [comment] 2015-07-03 11:32
I would like to add that ```decltype``` is a very powerful C++11 feature, but the example scenario does not illustrate this. The main usecase of ```decltype```, as far as I understand, is compile time computation of types which depend on other types as in the following C++:
``` C++
template <class T, class U>
auto add(T x, U y) -> decltype(x + y) {
    return x + y;
}
```

**Comment by HaloFour** [comment] 2015-07-03 12:00
@aluanhaddad

That is definitely a more compelling scenario, but I'm still not sure it makes much sense for C# given the lack of compile-time templates.

**Comment by aluanhaddad** [comment] 2015-07-03 12:16
@HaloFour I agree

**Comment by alrz** [comment] 2015-10-03 07:12
Combining #259 and #58 is another way to work this around.
```cs
internal class Class
{
    using ValueList = IReadOnlyList<int>;

    private ValueList values;

    internal void SetValues(ValueList  values)
    {
        this.values = values;
    }
}
```

**Comment by wizzardmr42** [comment] 2015-12-29 09:09
Can I add that this would be incredibly useful for keeping foreign key ref types in sync in EF and for filter model classes in MVC that reference EF types.  See #7715 where I explained in more detail.

**Comment by ViIvanov** [comment] 2016-01-02 23:38
@dimaaan, @HaloFour,

For example, `using alias directive` can not help with generics:

```cs
class Class<T>
{
    private readonly IReadOnlyList<T> values;

    internal Class(IReadOnlyList<T> values)
    {
        this.values = values;
    }
}
```

**Comment by HaloFour** [comment] 2016-01-02 23:41
That's what #3993 intends to fix.

**Comment by DerpMcDerp** [comment] 2016-02-24 05:09
Here's a less advanced example representing something programmers run into every day in C#:

```C#
var foo = whatever();
// the compiler already knows the type of foo, why should I have to specify it?
var asdf = new List<decltype(foo)>();
asdf.Add(foo);
```

If you wanted to do the above today, you'd have to write something like a wrapper method taking a dummy parameter, e.g.

```C#
private static List<T> MakeListOf<T>(T ignored) {
	return new List<T>();
}

var foo = whatever();
var asdf = MakeListOf(foo);
asdf.Add(foo);
```

The wrapper method usually gets obscured by making it do other stuff, i.e.

```C#
private static List<T> MakeListFrom<T>(T value) {
	var ret = new List<T>();
	ret.Add(value);
	return ret;
}

var foo = whatever();
var asdf = MakeListFrom(foo);
```

Which is how current C# produces the illusion that this feature isn't necessary.

**Comment by aluanhaddad** [comment] 2016-02-24 05:29
@DerpMcDerp

```c#
var asdf = new [] { foo }.ToList();
```

**Comment by jsphadetula** [comment] 2016-07-05 12:20
//Converting an enum value to its underlying type value
TIntegralValue GetValue<TIntegralValue>(EnumType enumValue)
{
     return (typeof(Enum.GetUnderlyingType(EnumType)) enumValue;
}

The sad part is Enum.GetUnderlyingType() is only evaluated at runtime. I think this points to the lack of compile time computation in C#

**Comment by gafter** [comment] 2017-03-24 23:53
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.

**Closed by gafter** 2017-03-24 23:53 UTC
Labels: Area-Language Design, Discussion, Feature Request
