### ISSUE TITLE
codelens detects wrong author

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23026] opened 2017-11-06 10:02 UTC
After moving a file I am marked as the author of every method in that file.  This is not what `git annotate` would say (it knows the file was just renamed).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/142868/codelens-detects-wrong-author.html
VSTS ticketId: 518703_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by robert-j-engdahl** [comment] 2017-11-06 10:11
Just wanted to add that I was the original creator of this issue via VS feedback (and I am on github too).

**Comment by jinujoseph** [comment] 2017-11-17 02:42
also tracked   [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/526044)

**Comment by sandeepchads** [comment] 2017-11-17 04:26
​Hi Robert, I apologize for the issue you are facing. I acknowledge that CodeLens does not handle renames very well however looking at the other work on our backlog, we are unable to prioritize this request now. We will keep tracking this issue and will let you know if we prioritize it in future. I apologize for the inconvenience.

**Comment by heejaechang** [comment] 2017-11-17 12:29
@jinujoseph this is not the part we own. I think we need to contact code lens team to find out who owns this part?

**Comment by jinujoseph** [comment] 2017-11-17 16:25
@sandeepchads i am closing this as dupe of [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/526044)

**Closed by jinujoseph** 2017-11-17 16:25 UTC
Labels: Area-External, Area-IDE, Developer Community
