### ISSUE TITLE
move GetEffectiveSeverity to DiagnosticDescriptor

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#2598] opened 2015-05-08 15:22 UTC
this is very common operation people want to do on Severity. since Severity is owned by DiagnosticDescriptor, we should provide this functionality from the descriptor.

**Comment by heejaechang** [comment] 2015-05-08 15:22
assigned to @mavasani

**Comment by mavasani** [comment] 2015-05-08 15:29
:+1: We have also had requests from public customers about this API.

**Comment by tmeschter** [comment] 2015-05-08 15:35
@mavasani @heejaechang The problem is that GetEffectiveSeverity depends on a whole bunch of other inputs that have nothing to do with `DiagnosticDescriptor`. Determining the effective severity is really a host-specific operation.

**Comment by sharwell** [comment] 2015-05-08 15:40
@tmeschter Location of this functionality doesn't really make a difference, provided it is readily accessible from within a call to `DiagnosticAnalyzer.Initialize`. Obviously documentation will be a big part of this regardless of where the API is.

**Comment by mavasani** [comment] 2015-05-08 16:01
@tmeschter Agreed, the API could lie on DiagnosticDescriptor but would need to take Compilation/CompilationOptions as an argument or could probably be on compilation itself and ask it to give the effective severity of descriptor, if a diagnostic created through it were to be reported on that compilation. Basically, we should be able to share code between the GetEffectiveSeverity method that HeeJae added and the ones here: http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp/R/94397cbfa794a94c.html and here: http://source.roslyn.io/Microsoft.CodeAnalysis.VisualBasic/R/229e7387fc56a8af.html

Code in all three of these places seems very identical, and we should avoid bugs due to inadvertent differences that might get introduced in future in these implementations.

**Comment by heejaechang** [comment] 2015-05-08 17:49
@mavasani @tmeschter @sharwell I think effective severity can have several variations. one that only based on CompilerOptions (good for finding out ones that already suppressed or hidden), one that based on location (good for finding out diagnostics that got suppressed individually). and it looks like there is a case where effective severity needs some info from host as well. (I dont know what the case is though, @tmeschter ?)

anyway, so we might not be able to provide completely generic implementation, but we should provide building blocks to code that easily. the two I mentioned (option and location based one) can be provided I believe.

**Comment by sharwell** [comment] 2015-05-08 17:51
@heejaechang The one that matters for analyzer performance is catching cases where an analyzer is completely suppressed for a compilation.

**Comment by heejaechang** [comment] 2015-05-08 17:53
@sharwell same for hidden case for closed files. running simplifier analyzer whole solution increase time to go through whole solution several times.

**Comment by mavasani** [comment] 2015-05-14 20:51
Moving to 1.1 milestone as this is more of API cleanup work. @ManishJayaswal @srivatsn please let me know if you disagree.

**Closed** 2015-06-24 17:44 UTC
Labels: Area-Analyzers, Enhancement
