### ISSUE TITLE
Decompiler doesn't handle malformed XML

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25300] opened 2018-03-07 05:48 UTC
``` C#
/// Exception while reading XmlDoc: System.Xml.XmlException: The 'p' start tag on line 835 position 2 does not match the end tag of 'th'. Line 835, position 89.
///   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
///   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
///   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
///   at System.Xml.XmlTextReaderImpl.ParseEndElement()
///   at System.Xml.XmlTextReaderImpl.ParseElementContent()
///   at System.Xml.XmlTextReaderImpl.Read()
///   at System.Xml.XmlTextReader.Read()
///   at System.Xml.XmlTextReaderImpl.Skip()
///   at System.Xml.XmlTextReader.Skip()
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider..ctor(String fileName)
///   at ICSharpCode.Decompiler.Documentation.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
///   at ICSharpCode.Decompiler.CSharp.Transforms.AddXmlDocumentationTransform.Run(AstNode rootNode, TransformContext context)
namespace System.Collections.Generic
{
	public interface IEnumerable<out T> : IEnumerable
	{
		new IEnumerator<T> GetEnumerator();
	}
}
```

**Comment by sharwell** [comment] 2018-03-07 11:38
Duplicate of #24177

**Closed by sharwell** 2018-03-07 11:38 UTC
