### ISSUE TITLE
Naming Rules Not Working

### ISSUE THREAD

**Issue by RLashofRegas** [dotnet/roslyn#45450] opened 2020-06-25 05:41 UTC
**Version Used**: 
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
"Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="3.8.0-1.20319.4"
"Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0"

**Steps to Reproduce**:

1. clone https://github.com/RLashofRegas/RobinLashofRegas.com
2. switch to branch naming-rules
3. in .editorconfig where it has the Naming Conventions header paste naming rules from the [roslyn .editorconfig](https://github.com/dotnet/roslyn/blob/82aac2c7169b20fff42c5db5444e62a1726f78ce/.editorconfig#L64)
4. restart editor
5. Navigate to src/services/BlogAPI/Startup.cs, naming rules should flag `CORS_POLICY_NAME` but they don't.

**Expected Behavior**:
constants_should_be_pascal_case rule should flag `CORS_POLICY_NAME` for violating the naming rule

**Actual Behavior**:
No suggestion is made.

I have tried enabling IDE1006 because I saw it in the screenshot [here](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019#example). I also tried in both VS Code and Visual Studio 2019 (latest version) with no luck in either.

I'm sure I must be doing something wrong because it seems to be working for other projects so any help is appreciated :)

**Comment by jmarolf** [comment] 2020-06-29 18:09
@RLashofRegas I do not see any naming styles in the editorconfig linked [here](https://github.com/RLashofRegas/RobinLashofRegas.com/blob/ea66b244069fb5e9cf6b35107f5a0d4edfd8a527/.editorconfig#L243)

**Comment by RLashofRegas** [comment] 2020-06-30 06:11
@jmarolf As mentioned in the repro steps I was testing with the naming rules from the [roslyn .editorconfig](https://github.com/dotnet/roslyn/blob/82aac2c7169b20fff42c5db5444e62a1726f78ce/.editorconfig#L64)

**Comment by sharwell** [comment] 2020-07-01 22:51
Duplicate of #23706

**Closed by sharwell** 2020-07-01 22:51 UTC
Labels: Area-IDE, Bug, Investigation Required
