### ISSUE TITLE
VS 2019 Disables Extension on Add Missing Usings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36317] opened 2019-06-11 16:47 UTC
VSF_TYPE_MARKDOWN
Visual Studio 2019 is crashes when I press &quot;Ctrl + Space&quot; and higlight &quot;Add missing usings&quot;.  This disables the feature from the context menu.  I was trying to added the missing using for  `DuplicateKeyException` from `System.Data.Linq.DuplicateKeyException`
```
System.NotImplementedException : The method or operation is not implemented.
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.GetChangesForCodeActionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.ApplyFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.AddMissingImportsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsRefactoringProvider.AddMissingImports(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unknown Parameters&gt;)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/516580/vs-2019-disables-extension-on-add-missing-usings.html
VSTS ticketId: 838562_
_These are the original issue comments:_

Visual Studio Feedback System on 4/4/2019, 00:38 AM (68 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/4/2019, 01:46 AM (68 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

sethg on 4/4/2019, 11:12 AM (67 days ago): Not that it changes the issue, but I did find that System.Data.Linq.DuplicateKeyException was not the actual exception I was looking for.
_These are the original issue solutions:_
(no solutions)

**Comment by JoeRobich** [comment] 2019-06-11 16:48
Duplicate of  https://github.com/dotnet/roslyn/issues/34398

**Closed by JoeRobich** 2019-06-11 16:48 UTC
