### ISSUE TITLE
Error writing debug information on NanoServer

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/roslyn#8348] opened 2016-02-02 22:19 UTC
I get the following error when compiling a HelloWorld .NetCore project on NanoServer.

C:\app\error CS0041: Unexpected error writing debug information -- 'Retrieving the COM class factory for component with CLSID {0AE2DEB0-F901-478B-BB9F-881EE8066788} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).'

**Repro Steps:**
1. There are a couple options to setup a NanoServer
    - https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker?f=255&MSPPError=-2147217396#hyper-v-container
    - http://blogs.technet.com/b/nanoserver/archive/2015/12/24/nano-server-developer-experience-visual-studio-2015-update-1-and-above.aspx
2. Install dotnet cli
    - copy https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest/dotnet-win-x64.latest.zip onto your NanoServer
    - point the DOTNET_HOME variable to the dotnet directory 
    - add the dotnet\bin directory to the path
3. md app
4. cd app
5. dotnet new
6. dotnet restore
7. dotnet -v build

**Results**
Running c:\program files\dotnet\bin\csc.exe "-noconfig" "@C:\app\obj\Debug\dnxcore50\dotnet-compile-csc.rsp" fails with the following error:
C:\app\error CS0041: Unexpected error writing debug information -- 'Retrieving the COM class factory for component with CLSID {0AE2DEB0-F901-478B-BB9F-881EE8066788} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).'

The following is a dump of the passed rsp file:
-d:DEBUG
-d:TRACE
-d:DNXCORE50
-nowarn:CS1701
-nowarn:CS1702
-nowarn:CS1705
-nostdlib
-nologo
-debug:full
"c:\app\output\dotnet-compile.assemblyinfo.cs"
-out:"C:\app\bin\Debug\dnxcore50\app.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\Microsoft.Win32.Primitives\4.0.1-rc3-23720\ref\dotnet5.4\Microsoft.Win32.Primitives.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.AppContext\4.1.0-rc3-23720\ref\dotnet5.6\System.AppContext.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Collections\4.0.11-rc3-23720\ref\dotnet5.4\System.Collections.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Collections.Concurrent\4.0.11-rc3-23720\ref\dotnet5.4\System.Collections.Concurrent.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Console\4.0.0-rc3-23720\ref\dotnet5.4\System.Console.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Diagnostics.Debug\4.0.11-rc3-23720\ref\dotnet5.4\System.Diagnostics.Debug.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Diagnostics.Process\4.1.0-rc3-23720\ref\dotnet5.5\System.Diagnostics.Process.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Diagnostics.Tools\4.0.1-rc3-23720\ref\dotnet5.1\System.Diagnostics.Tools.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Diagnostics.Tracing\4.0.21-rc3-23720\ref\dotnet5.4\System.Diagnostics.Tracing.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Globalization\4.0.11-rc3-23720\ref\dotnet5.4\System.Globalization.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Globalization.Calendars\4.0.1-rc3-23720\ref\dotnet5.4\System.Globalization.Calendars.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.IO\4.1.0-rc3-23720\ref\dotnet5.4\System.IO.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.IO.FileSystem\4.0.1-rc3-23720\ref\dotnet5.4\System.IO.FileSystem.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.IO.FileSystem.Primitives\4.0.1-rc3-23720\ref\dotnet5.4\System.IO.FileSystem.Primitives.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Linq\4.0.1-rc3-23720\ref\dotnet5.1\System.Linq.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Net.Primitives\4.0.11-rc3-23720\ref\dotnet5.4\System.Net.Primitives.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Net.Sockets\4.1.0-rc3-23720\ref\dotnet5.4\System.Net.Sockets.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Reflection\4.1.0-rc3-23720\ref\dotnet5.4\System.Reflection.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Reflection.Extensions\4.0.1-rc3-23720\ref\dotnet5.1\System.Reflection.Extensions.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Reflection.Primitives\4.0.1-rc3-23720\ref\dotnet5.1\System.Reflection.Primitives.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Reflection.TypeExtensions\4.1.0-rc3-23720\ref\dotnet5.4\System.Reflection.TypeExtensions.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Resources.ResourceManager\4.0.0\ref\dotnet\System.Resources.ResourceManager.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime\4.0.21-rc3-23720\ref\dotnet5.4\System.Runtime.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime.Extensions\4.1.0-rc3-23720\ref\dotnet5.4\System.Runtime.Extensions.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime.Handles\4.0.1-rc3-23720\ref\dotnet5.4\System.Runtime.Handles.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime.InteropServices\4.0.21-rc3-23720\ref\dotnet5.4\System.Runtime.InteropServices.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime.InteropServices.RuntimeInformation\4.0.0-rc3-23720\ref\dotnet5.2\System.Runtime.InteropServices.RuntimeInformation.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Runtime.Numerics\4.0.1-rc3-23720\ref\dotnet5.2\System.Runtime.Numerics.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Text.Encoding\4.0.11-rc3-23720\ref\dotnet5.4\System.Text.Encoding.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Text.Encoding.Extensions\4.0.11-rc3-23720\ref\dotnet5.4\System.Text.Encoding.Extensions.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Text.RegularExpressions\4.0.11-rc3-23720\ref\dotnet5.4\System.Text.RegularExpressions.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Threading\4.0.11-rc3-23720\ref\dotnet5.4\System.Threading.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Threading.Tasks\4.0.11-rc3-23720\ref\dotnet5.4\System.Threading.Tasks.dll"
-r:"C:\windows\system32\config\systemprofile\.nuget\packages\System.Threading.Timer\4.0.1-rc3-23720\ref\dotnet5.3\System.Threading.Timer.dll"
"C:\app\Program.cs"

**Comment by tmat** [comment] 2016-02-03 06:33
@tannergooding This has likely the same root cause as you observed. We need to include Microsoft.DiaSymReader.Native binaries in dotnet cli if we are gonna support building Windows PDBs on Windows.

FYI @ManishJayaswal

**Comment by tmat** [comment] 2016-02-18 02:25
@tannergooding Could you point to the fix and close this issue?

**Comment by ManishJayaswal** [comment] 2016-04-26 02:04
I believe this was fixed by https://github.com/dotnet/cli/pull/1209

**Closed by ManishJayaswal** 2016-04-26 02:04 UTC
Labels: Area-Interactive, Interactive-Debugging
