### ISSUE TITLE
Adding a reference to Microsoft.CodeAnalysis.CSharp.Scripting to an ASP.NET Core Web Application breaks Razor views.

### ISSUE THREAD

**Issue by DAlumbaugh** [dotnet/roslyn#20873] opened 2017-07-13 22:20 UTC
**Version Used**: 
.NETCore.App 1.1.2 and 2.0 Preview 2

**Steps to Reproduce**:
Add reference Microsoft.CodeAnalysis.CSharp.Scripting (any 2.0 version) to an ASP.NET Core Web Application

**Expected Behavior**:  Razor views still render correctly

**Actual Behavior**:  System.ArgumentException: Must include private members unless emitting a ref assembly.

```
Parameter name: IncludePrivateMembers
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by Pilchie** [comment] 2017-07-14 14:34
Tagging @tmat

**Comment by PureWeen** [comment] 2017-07-14 21:57
I'm seeing this issue specifically when I update

Microsoft.CodeAnalysis.CSharp to version 2.3.0

Version 2.2.0 works fine for me

**Comment by tmat** [comment] 2017-07-14 22:25
Interesting. The difference between 2.2.0 and 2.3.0 is that the latter is pure netstandard 1.3 package with no fallback. Not sure why would that be significant though.

**Comment by mintyben** [comment] 2017-07-17 09:30
I see the same issue as @PureWeen.
Looking at the deps.json after upgrading to Microsoft.CodeAnalysis.CSharp 2.3.0 it also updates Microsoft.CodeAnalysis.Common to 2.3.0. These two are the only packages that are different

If I make both of these 2.2.0 then the issue goes away.

**Comment by kieronlanning** [comment] 2017-07-18 07:00
Same problem. Rolled back, and all was good.

**Comment by codeape2** [comment] 2017-07-21 16:25
Have the same problem with TargetFramework=net462

**Comment by danielcrabtree** [comment] 2017-07-22 15:14
I had the same problem with Microsoft.CodeAnalysis.CSharp v2.3.1. Rolling back to v2.2.0 worked.

**Comment by kieronlanning** [comment] 2017-07-23 06:05
I have the same problem targeting .NET Core 1.1 (no other targets).l

**Comment by ignatandrei** [comment] 2017-08-01 22:57
Same problem. And same solving - going back to 2.2.0

**Comment by tmat** [comment] 2017-08-02 01:25
I have just tried with VS 15.3.0 Preview 7.0, Microsoft.CodeAnalysis.Scripting package v2.3.1 and the Web App targets netcoreapp2.0: adding a package reference and running script works well.  

Can anyone who can reproduce the issue share a project where it's broken?

**Comment by PureWeen** [comment] 2017-08-02 02:48
[RoslynExceptionCodeAnalysisScripting.zip](https://github.com/dotnet/roslyn/files/1192532/RoslynExceptionCodeAnalysisScripting.zip)

I'm running VS 15.2 and don't have any netcore 2.0 bits installed so it's hard to say if your preview bits are what's making it better

but the attached project is giving me the exception
All I did with this was add a site from the "Add new site" template and then added the packages.

It compiles but just crashes on startup for me
```
System.ArgumentException: Must include private members unless emitting a ref assembly.

Parameter name: IncludePrivateMembers

   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)

   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)

   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)

   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)

   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)

   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)

   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)

   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)

   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)

   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by filipw** [comment] 2017-08-07 14:32
@tmat looks like this is caused by this PR https://github.com/dotnet/roslyn/pull/19478/files#diff-9ab09861519e8dfab2c0787cad46ab15R2089 and a stricter validation added there

I bet it would work if the problematic type `Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService` did something like `var emitOptions = new EmitOptions().WithEmitMetadataOnly(false).WithIncludePrivateMembers(true)`

FWIW, if you want a repro, get the ScriptingInWebAppDemo project from https://github.com/filipw/csharp-scripting-demos/tree/master/ScriptingInWebAppDemo, start the server and navigate to root.

**Comment by tmat** [comment] 2017-08-07 16:38
@filipw Thanks, I can reproduce now.

**Comment by tmat** [comment] 2017-08-07 16:40
@jaredpar @jcouv This is caused by the breaking change in the default parameter value in EmitOptions ctor: ```bool includePrivateMembers = false```.

**Comment by jcouv** [comment] 2017-08-07 17:00
Thanks for the ping @tmat. I think I let one of your emails on this slip by when I came back from trip.
I'll stop by to discuss.

**Comment by jcouv** [comment] 2017-08-08 23:53
Assigned the issue (and the ask-mode PR) to @jaredpar for follow-up while I'm away. Thanks!

**Comment by ntgnst** [comment] 2017-08-10 13:52
Microsoft.CodeAnalysis.CSharp 2.2.0 is not compatible with EF Core 2.0 ? Any solution

**Comment by jcouv** [comment] 2017-09-01 03:05
Mitigation checked into 15.4 preview 3.

**Closed** 2017-09-01 20:59 UTC
Labels: 4 - In Review, Area-Compilers, Bug, Tenet-Compatibility

**Comment by daveaglick** [comment] 2017-10-11 15:26
I just hit this. I see a fix was included in the tooling for 15.4, but will a new set of packages also go out to NuGet soon? I'm consuming Razor and Roslyn as libraries.

**Comment by jcouv** [comment] 2017-10-12 00:02
I expect the packages for 15.4 RTM to be published on nuget this week.
