### ISSUE TITLE
Add a "add breakpoint" in the context menu when clicking on a margin of an overridden member

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57229] opened 2021-10-19 00:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-add-breakpoint-in-the-context-me/1555954)._

---
With Visual Studio 2022, overridden members in C# have a new button in the margin to go to the definition of the member in the base class. However, this makes it extremely difficult to place breakpoint on these lines, which requires pixel precision as to not click on the override origin button. A compromise could be to extend the size of the button to completely cover the area in the margin for a breakpoint and add a "Add breakpoint" option to the menu. If a breakpoint is already present, the option would be "Remove breakpoint"

---
#### Feedback Bot on 10/18/2021, 02:08 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by Youssef1313** [comment] 2021-10-19 11:08
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/55056, which was fixed?

**Closed as completed** 2021-10-20 17:33 UTC
Labels: Area-Interactive
