### ISSUE TITLE
InvalidProgramException caused by when (false) exception filter

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#19568] opened 2017-05-16 21:20 UTC
**Version Used**: master

**Steps to Reproduce**:

[Try to run the following code](https://tryroslyn.azurewebsites.net/#b:master/f:%3Easmr/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUHgYwBsBDEEGAYTwG88YGYAHYAIyLAJhROU5gBuAezAATGAFkSkABQBKeozq5GqmMgBOCRWpjLdu5AAsNQgO4wIqCwFEAHgVRM+QiPJwqDAXx1qCvAiMYMyNUCBgZADMSIhBUBU9dfW9fH1wvIA=):

```c#
using System;

class C
{
    public static void Main()
    {
        try
        {
            throw new Exception();
        }
        catch when (false)
        {
        }
    }
}
```

**Expected Behavior**: Program crashes due to unhandled `Exception`.

**Actual Behavior**: Program crashes due to `InvalidProgramException`:

> InvalidProgramException: Common Language Runtime detected an invalid program.

Comparing the IL for the above program and one with `when (true)`, which doesn't throw `InvalidProgramException`, shows:

`when (false)`:

```cil
.try
{
  IL_0000: newobj       instance void [mscorlib]System.Exception::.ctor()
  IL_0005: throw        
}
filter
{
  IL_0006: pop          
  IL_0007: ldc.i4.0     
  IL_0008: ldc.i4.0     
  IL_0009: cgt.un       
  IL_000b: endfilter    
}
{
  IL_000d: pop          
  IL_000e: leave.s      IL_0010
}
```

`when (true)`:

```cil
.try
{
  IL_0000: newobj       instance void [mscorlib]System.Exception::.ctor()
  IL_0005: throw        
}
filter
{
  IL_0006: pop          
  IL_0007: ldc.i4.1     
  IL_0008: ldc.i4.0     
  IL_0009: cgt.un       
  IL_000b: endfilter    
}
{
  IL_000d: pop          
  IL_000e: leave.s      IL_0010
}
IL_0010: ret    
```

Notice the added `ret` at the end. I think the missing `ret` could be the cause of this issue.

This is probably not something one would write in production code, so this issue might not be that important. But such code might be useful to easily "comment out" a `catch`.

**Comment by sharwell** [comment] 2017-05-17 02:45
Thank you for taking the time to report this. You are correct that this is a bug; it's a duplicate of #18678 which I've been watching recently. :smile:

**Closed** 2017-05-17 02:45 UTC
Labels: Resolution-Duplicate

**Comment by svick** [comment] 2017-05-17 10:55
@sharwell Thanks. I searched for `InvalidProgramException` and didn't find anything. Guess I should have been more thorough. 🙂

**Comment by sharwell** [comment] 2017-05-17 12:18
@svick It's fine. I'd rather see a duplicate than miss out on something. Plus we've had cases where someone included details in the duplicate (and yours is quite detailed here) which were essential to solving the bug.
