### ISSUE TITLE
[IDE0040 : Explicit visibility] CodeFix breaks the code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31108] opened 2018-11-11 17:39 UTC
In VS 15.8.9 

Hi,

While looking at the possiblities the new EditorConfig and Code-Styles add to consistency, I think I stumble upon a bug with the rule about explicit visibility.

The rule in question (IDE0040) can be set to warn about leaving implicit visibility in the code and give the possibliity to fix it automaticaly.

But the codefix on external declaration, while adding the visibility, deletes the &quot;extern&quot; declaration, leaving the file unbuildable.

So the codefix actually broke the code :(

![image](https://user-images.githubusercontent.com/12449387/48316232-bf77fe00-e595-11e8-8f3f-6ad14f6275bb.png)

**Comment by sharwell** [comment] 2018-11-11 19:28
Duplicate of #29561

**Closed by sharwell** 2018-11-11 19:28 UTC
