### ISSUE TITLE
crash during code analysis -- RenameTracking

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31883] opened 2018-12-17 23:38 UTC
<p>crash during automated test run.  crashed after around 8 hours.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/405103/crash-during-code-analysis-rename.html
VSTS ticketId: 748636_
_These are the original issue comments:_

sean on 12/11/2018, 09:30 AM (6 days ago): <p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/51819-devenvexe19864.zip">devenvexe19864.zip</a></p>

sean on 12/12/2018, 11:42 AM (5 days ago): <p>crashed last night also -- in Editor RenameTracking while a modal dialog is being displayed.</p><p>callstack attached as text file because the reporting system won't allow it to be pasted into this window due to it being greater than 10000 characters: <a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/52071-callstack.txt">callstack.txt</a></p><p>full heap dump is also attached: <a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/52072-v16p-w10-20181212-1325dmp.zip">v16p-w10-20181212-1325dmp.zip</a></p>

sean on 12/17/2018, 01:16 PM (4 hours ago): <p>Another crash during RenameTracking</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/52765-v16p-w10-20181215-1257.zip">v16p-w10-20181215-1257.zip</a></p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-12-17 23:39
Stack trace:

```
 	[Managed to Native Transition]	
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 207	C#
>	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task task, object continuationFunction) Line 480	C#
 	mscorlib.dll!System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() Line 73	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2756	C#
 	mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 92	C#
 	mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued) Line 219	C#
 	mscorlib.dll!System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task task, bool needsProtection) Line 263	C#
 	mscorlib.dll!System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task completedTask, bool bCanInlineContinuationTask) Line 371	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3642	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.TaskExtensions.VoidResult>.TrySetException(object exceptionObject) Line 606	C#
 	mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.TrySetFromTask(System.Threading.Tasks.Task task, bool lookForOce) Line 7285	C#
 	mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.InvokeCore(System.Threading.Tasks.Task completingTask) Line 7209	C#
 	mscorlib.dll!System.Threading.Tasks.UnwrapPromise<System.Threading.Tasks.TaskExtensions.VoidResult>.Invoke(System.Threading.Tasks.Task completingTask) Line 7185	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3633	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo() Line 2336	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) Line 2263	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetException(object exceptionObject) Line 606	C#
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(System.Exception exception) Line 677	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession..ctor.AnonymousMethod__1(System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TriggerIdentifierKind> t) Line 80	C#
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageA@4()	Unknown
 	VA_X.dll!DispatchMessageAHook(tagMSG * lpMsg) Line 670	C++
 	VA_X.dll!CWnd::CreateRunDlgIndirect(const DLGTEMPLATE * lpDialogTemplate, CWnd * pParentWnd, HINSTANCE__ * hInst) Line 474	C++
 	VA_X.dll!CDialog::DoModal() Line 633	C++
 	VA_X.dll!VADialog::DoModal() Line 177	C++
 	VA_X.dll!Refactor(unsigned int flag, const char * orgSymscope, const char * newName, tagPOINT * ppt) Line 4685	C++
 	[Inline Frame] VA_X.dll!Refactor(RefactorFlag) Line 81	C++
 	[Inline Frame] VA_X.dll!FillVAContextMenuWithRefactoring::__l2::<lambda_1f97cef15e263afc4fb82df76fa5172e>::()::__l5::<lambda_5da420b59edbb623f99a0b35c1753668>::operator()() Line 4998	C++
 	[Inline Frame] VA_X.dll!std::_Invoker_functor::_Call(FillVAContextMenuWithRefactoring::__l2::<lambda_1f97cef15e263afc4fb82df76fa5172e>::()::__l5::<lambda_5da420b59edbb623f99a0b35c1753668> &)	C++
 	[Inline Frame] VA_X.dll!std::invoke(FillVAContextMenuWithRefactoring::__l2::<lambda_1f97cef15e263afc4fb82df76fa5172e>::()::__l5::<lambda_5da420b59edbb623f99a0b35c1753668> &)	C++
 	[Inline Frame] VA_X.dll!std::_Invoker_ret<void,1>::_Call(FillVAContextMenuWithRefactoring::__l2::<lambda_1f97cef15e263afc4fb82df76fa5172e>::()::__l5::<lambda_5da420b59edbb623f99a0b35c1753668> &)	C++
 	VA_X.dll!std::_Func_impl_no_alloc<<lambda_5da420b59edbb623f99a0b35c1753668>,void>::_Do_call()	C++
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	VA_X.dll!DispatchMessageWHook(tagMSG * lpMsg) Line 282	C++
 	msenv.dll!CMsoCMHandler::EnvironmentMsgLoop(void)	Unknown
 	msenv.dll!CMsoCMHandler::FPushMessageLoop(unsigned long)	Unknown
 	msenv.dll!SCM::FPushMessageLoop(class SCMI *,unsigned long,void *)	Unknown
 	msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long,unsigned long,void *)	Unknown
 	msenv.dll!CMsoComponent::PushMsgLoop(unsigned long)	Unknown
 	msenv.dll!VStudioMainLogged(void)	Unknown
 	msenv.dll!_VStudioMain()	Unknown
 	devenv.exe!util_CallVsMain(struct MAINPARAM *,int *)	Unknown
 	devenv.exe!CDevEnvAppId::Run(unsigned short *,int)	Unknown
 	devenv.exe!_WinMain@16()	Unknown
 	devenv.exe!__scrt_common_main_seh()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector..cctor.AnonymousMethod__20_0(object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	VAX.Interop.dll!WholeTomatoSoftware::VisualAssist::Interop::RefactoringMenuItem::Invoke() Line 906	C++
 	VaCodeInspectionsAsync.dll!o1.Invoke() Line 78	Unknown
 	VaCodeInspectionsAsync.dll!p8.a.Execute(object parameter) Line 39	Unknown
 	PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
```

**Comment by sharwell** [comment] 2018-12-17 23:42
Here's the exception that led to the crash:

```
Exception type:   System.Collections.Generic.KeyNotFoundException
Message:          The given key was not present in the dictionary.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    008FEC44 72CE8826 mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].get_Item(System.__Canon)+0xc2efd6
    008FEC50 262841B4 UNKNOWN!Microsoft.VisualStudio.LanguageServices.Implementation.InlineRename.VisualStudioInlineRenameUndoManagerServiceFactory+InlineRenameUndoManager.ApplyCurrentState(Microsoft.VisualStudio.Text.ITextBuffer, System.Object, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.ITrackingSpan>)+0x2c
    008FECA8 2628341A UNKNOWN!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+OpenTextBufferManager.ApplyReplacementText(Boolean)+0x19a
    008FED00 26280D70 UNKNOWN!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+OpenTextBufferManager.SetReferenceSpans(System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Text.TextSpan>)+0x320
    008FED98 3E6ACD3C UNKNOWN!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.SetReferenceLocations(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Editor.InlineRenameLocation>)+0x2a4
    008FEE04 3E6ACA62 UNKNOWN!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.RaiseSessionSpansUpdated(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Editor.InlineRenameLocation>)+0x1a
    008FEE14 2628CD13 UNKNOWN!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+<<UpdateReferenceLocationsTask>b__33_0>d.MoveNext()+0x1a3
```

**Comment by JoeRobich** [comment] 2019-01-15 00:37
The exception for 2 of the dumps was the following:

```
Exception type:   System.NullReferenceException
Message:          Object reference not set to an instance of an object.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    012FD67C 22F7F1E7 Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+StateMachine.UpdateTrackingSessionIfRenamable()+0x17
    012FD690 2DADF63E Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TrackingSession+<>c__DisplayClass15_0+<<-ctor>b__1>d.MoveNext()+0x16e
```

**Comment by sharwell** [comment] 2019-01-15 16:54
Duplicate of #30661

**Comment by sharwell** [comment] 2019-01-15 16:56
@JoeRobich The NullReferenceException is a duplicate of #30661. Are you saying you found a separate bug as well?

**Comment by JoeRobich** [comment] 2019-01-15 19:11
@sharwell I agree the NRE looks to be the same. The KeyNotFound seems to be a separate issue tho.

**Closed** 2019-01-17 01:54 UTC
Labels: 4 - In Review, Area-IDE, Bug, Developer Community, Tenet-Reliability, help wanted
