### ISSUE TITLE
CS8600 after linq Where to filter non null values.

### ISSUE THREAD

**Issue by boulix3** [dotnet/roslyn#39586] opened 2019-10-30 13:16 UTC
Hello,

**Version Used**: 
Visual studio 2019 16.4.0 Preview 2.0

Project file : 
- LangVersion : 8.0
- Nullable : enable
- TargetFramework : netcoreapp3.1

**Steps to Reproduce**:

```csharp
            var nonNullNames = items.Where(x => x.Name != null);
            string name = nonNullNames.First().Name;
```
**Expected Behavior**:
There should be no warning.

**Actual Behavior**:
CS8600 Converting null literal or possible null value to non-nullable type.

**Comment by sharwell** [comment] 2019-10-30 13:20
As far as I can tell, it is not possible to annotate this method for use without any warning. If you were using the null check on the items in the enumeration itself (e.g. `items.Where(x => x != null)`) then you could use an extension method to help out. However, for this case I believe you would need to use a suppression operator:

```csharp
string name = nonNullNames.First().Name!;
```

**Comment by boulix3** [comment] 2019-10-30 13:35
What about this case : 
```csharp
            string?[] array = new string?[] { "a", "b", null, "c" };
            var nonNullItems = array.Where(x => x != null);
            string firstNonNull = nonNullItems.First();
```
There is still a warning. Did you mean I should implement my own extension method to get rid of the warning?

**Comment by sharwell** [comment] 2019-10-30 13:58
@boulix3 I was leaving it open for a member of the compiler and/or language design team to see as well 👍

**Comment by YairHalberstadt** [comment] 2019-10-30 14:42
For your particular case the following should work:
```csharp 
     var nonNullNames = items.Select(x => x.Name).WhereNotNull();
     string name = nonNullNames.First();
```

**Comment by RichardP-Pinnacle** [comment] 2023-08-27 10:13
Looks ghastly but using the null forgiving operator one way or another will work:-
` var nonNullNames = items.Where(x => x.Name != null).Select(x => x.Name!);`

**Comment by sharwell** [comment] 2024-03-08 15:43
Duplicate of #37468

**Closed by sharwell** 2024-03-08 15:43 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Nullable Reference Types
