### ISSUE TITLE
Incorrect suggestion to convert type to var in foreach

### ISSUE THREAD

**Issue by cbo425** [dotnet/roslyn#18336] opened 2017-03-31 00:03 UTC
**Version Used**:  VS 2017

**Steps to Reproduce**:

1. Copy/Paste C# code:
```C#
using System.Text.RegularExpressions;

class C
{
    void M()
    {
        var matches = Regex.Matches("", "");
        foreach (Match match in matches)
        {
            var groups = match.Groups;
        }
    }
}
```
2. In Tools Options, set Var Preference Elsewhere to 'Prefer var' and Severity to Warning

**Expected Behavior**:
No suggestion to convert `Match` to `var` in the foreach

**Actual Behavior**:
Suggestion to convert `Match` to `var` results in `match` being of type `object` , so the `Groups` property is not available.

**Comment by Pilchie** [comment] 2017-03-31 17:54
Dupe of https://github.com/dotnet/roslyn/issues/14052.

**Closed by Pilchie** 2017-03-31 17:54 UTC
Labels: Area-IDE, Bug
