### ISSUE TITLE
C# Ability to assign to readonly fields from constructor-invoked methods.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35868] opened 2019-05-22 00:17 UTC
<p>To simplify a constructor, I sometimes separate some of the functionality into private methods.</p> <p>Unfortunately, this doesn't work if I'm assigning to readonly fields.</p> <p>It would be nice if the compiler was able to determine that these private methods are only being invoked from the constructor and allow me to assign to readonly fields from within.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/567798/c-ability-to-assign-to-readonly-fields-from-constr.html
VSTS ticketId: 892542_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/15/2019, 01:08 AM (6 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by canton7** [comment] 2019-05-22 08:03
Duplicate of https://github.com/dotnet/csharplang/issues/1871?

**Comment by gafter** [comment] 2019-07-09 22:17
Closing as a dup of the language feature request dotnet/csharplang#1871

**Closed by gafter** 2019-07-09 22:17 UTC
Labels: Area-Compilers, Developer Community
