### ISSUE TITLE
Recommendations in incomplete sub cause VS crash

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#7606] opened 2015-12-18 22:10 UTC
Step 1. Create an incomplete sub by typing the code below and deleting the `End Sub` that is automatically inserted.

```
Sub Main()
    |
```

Step 2. Make sure to press ESC to disable current completions. Type any char (for example `a`). High chance VS crashes. Otherwise type backspace and repeat step 2.

**Comment by KevinH-MS** [comment] 2015-12-21 18:49
@drognanar, can you add a callstack?  (will help with routing the issue)

Thanks

**Comment by drognanar** [comment] 2015-12-21 19:01
Firstly an assertion fails: `Debug.Assert(IsInTree(token.Parent))`. Call stack:

```
>	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.FindInitialNodeFromPosition(Integer position) Line 644	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetEnclosingBinder(Integer position) Line 75	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbolsInternal(Integer position, Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceOrTypeSymbol container, String name, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, Boolean useBaseReferenceAccessibility) Line 1837	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbols(Integer position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) Line 1611	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbolsCore(Integer position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) Line 3175	Basic
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.LookupSymbols(int position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, string name, bool includeReducedExtensionMethods) Line 442	C#
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetUnqualifiedSymbolsForExpressionOrStatementContext(Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext context, Boolean filterOutOfScopeLocals, System.Threading.CancellationToken cancellationToken) Line 128	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetSymbolsWorker(Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext context, Boolean filterOutOfScopeLocals, System.Threading.CancellationToken cancellationToken) Line 62	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetRecommendedSymbolsAtPositionWorker(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, Integer position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 31	Basic
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPosition(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 22	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Recommendations.Recommender.GetRecommendedSymbolsAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 23	C#
 	Microsoft.CodeAnalysis.VisualBasic.Features.dll!Microsoft.CodeAnalysis.VisualBasic.Completion.Providers.SymbolCompletionProvider.GetSymbolsWorker(Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.AbstractSyntaxContext context, Integer position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 20	Basic
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetSymbolsWorker(int position, bool preselect, Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.AbstractSyntaxContext context, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 249	C#
```

Then a null reference exception occurs in `GetEnclosingBinderInternal` (because the assertion above fails loop does not terminate before `current` becomes `Nothing`). Call stack:
```
>	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetEnclosingBinderInternal(Microsoft.CodeAnalysis.VisualBasic.Binder memberBinder, Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode binderRoot, Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode node, Integer position) Line 1212	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetEnclosingBinder(Integer position) Line 75	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbolsInternal(Integer position, Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceOrTypeSymbol container, String name, Microsoft.CodeAnalysis.VisualBasic.LookupOptions options, Boolean useBaseReferenceAccessibility) Line 1837	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbols(Integer position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) Line 1611	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.LookupSymbolsCore(Integer position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) Line 3175	Basic
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.LookupSymbols(int position, Microsoft.CodeAnalysis.INamespaceOrTypeSymbol container, string name, bool includeReducedExtensionMethods) Line 442	C#
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetUnqualifiedSymbolsForExpressionOrStatementContext(Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext context, Boolean filterOutOfScopeLocals, System.Threading.CancellationToken cancellationToken) Line 128	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetSymbolsWorker(Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext context, Boolean filterOutOfScopeLocals, System.Threading.CancellationToken cancellationToken) Line 62	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Recommendations.VisualBasicRecommendationService.GetRecommendedSymbolsAtPositionWorker(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, Integer position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 31	Basic
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPosition(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 22	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Recommendations.Recommender.GetRecommendedSymbolsAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) Line 23	C#
```

**Comment by davkean** [comment] 2015-12-21 23:44
@gafter This looks to be compiler due to the first assert, feel free to assign it back it if it isn't.

**Comment by TyOverby** [comment] 2016-09-23 23:02
@drognanar I'm unable to repro.  Can you confirm that this is still happening to you?

**Comment by jaredpar** [comment] 2017-01-09 14:40
Closing for now as we are unable to reproduce the bug.  Please ping us if you are able to reproduce on more recent builds.

**Closed by jaredpar** 2017-01-09 14:40 UTC
Labels: Area-Compilers, Bug, Language-VB
