### ISSUE TITLE
SyntaxFactory.ParseArgumentList() does not provide parentheses by default

### ISSUE THREAD

**Issue by jega327** [dotnet/roslyn#13858] opened 2016-09-16 15:50 UTC
**Version Used**: 
v1.3.2 of Microsoft.CodeAnalysis.CSharp NuGet package

**Steps to Reproduce**:

1. Execute the following sample code to create a `ConstructorInializerSyntax` with an argument using
a) SyntaxFactory.ParseArgumentList()
b) SyntaxFactory.ParseArgumentList() followed by .With*ParenToken()
c) SyntaxFactory.ArgumentList().

```
            ConstructorInitializerSyntax ciWithParseArgList = SyntaxFactory.ConstructorInitializer(
                SyntaxKind.ThisConstructorInitializer,
                SyntaxFactory.ParseArgumentList("arg"));

            ConstructorInitializerSyntax ciWithParseArgListAndParenTokens = SyntaxFactory.ConstructorInitializer(
                SyntaxKind.ThisConstructorInitializer,
                SyntaxFactory.ParseArgumentList("arg")
                    .WithOpenParenToken(SyntaxFactory.Token(SyntaxKind.OpenParenToken))
                    .WithCloseParenToken(SyntaxFactory.Token(SyntaxKind.CloseParenToken)));

                ConstructorInitializerSyntax ciWithArgList = SyntaxFactory.ConstructorInitializer(
                SyntaxKind.ThisConstructorInitializer,
                SyntaxFactory.ArgumentList(
                        SyntaxFactory.SeparatedList<ArgumentSyntax>(new List<ArgumentSyntax>() {
                            SyntaxFactory.Argument(SyntaxFactory.ParseExpression("arg")) })));

            string s = "Using SyntaxFactory.ParseArgumentList():\r\n" + ciWithParseArgList.ToFullString()
                + "\r\n\r\nUsing SyntaxFactory.ArgumentList() but .With*ParenToken():\r\n" + ciWithParseArgListAndParenTokens.ToFullString()
                +"\r\n\r\nUsing SyntaxFactory.ArgumentList():\r\n" + ciWithArgList.ToFullString();
```

**Expected Behavior**:

Opening and closing parentheses in `ConstructorInitializerSyntax.ToFullString()` by all variants.

**Actual Behavior**:

Opening and closing parentheses are missing if the `ArgumentListSyntax` is created using `SyntaxFactory.ParseArgumentList()` only.

**Comment by svick** [comment] 2016-09-16 16:58
I think this is the expected behavior. Since argument list does include parentheses, you should provide them in your string to parse too. I.e. the right code is: `SyntaxFactory.ParseArgumentList("(arg)")`.

And I think `SyntaxFactory.ParseWhatever(s).ToFullString() == s` should be always `true`, your proposal would break that.

Also note that the result of `ParseArgumentList("arg")` does include `OpenParenToken` and `CloseParanToken`, except they are marked as missing. And calling `GetDiagnostics()` on the argument list gives:

> (1,1): error CS1003: Syntax error, '(' expected
> (1,4): error CS1026: ) expected

**Comment by jega327** [comment] 2016-09-19 09:07
Thank you very much for this explanation.

I agree to the equality constraint and was not aware of `GetDiagnostics()`. I guess I will just write a helper method to shorten my source code.

**Closed** 2016-09-19 09:07 UTC
Labels: Area-Compilers, Concept-API
