### ISSUE TITLE
Show "Add new in front of exception" in IntelliSense window for throw XXException()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42042] opened 2020-02-29 03:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/548349/show-add-new-in-front-of-exception-in-intellisense.html)._

---
<p>Regarding errornous code like this:</p> <pre>throw NameOfTheException(); // &quot;new&quot; is missing</pre> <p>In the IntelliSense window (option+enter) Visual Studio for Mac will suggest to generate a method called Exception.</p> <p>I think it would be nice, to suggest to just add new in front of the Exception class. Maybe add some check, whether there is an actual exception class called NameOfTheException before suggesting so.</p> <p>Maybe suggest to add the new keyword and generate a class, if there is no exception class called NameOfTheException.</p>

---
#### Jane Wu [MSFT] on 4/28/2019, 01:55 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Jordan Matthiesen [MSFT] on 6/26/2019, 05:37 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by CyrusNajmabadi** [comment] 2020-02-29 04:28
this is a good idea :)

**Comment by sharwell** [comment] 2020-03-05 00:32
Marking this as up for grabs. The expected behavior here is to provide a code fix for specific compiler errors, and offer to add `new` in front of it. This would apply to `throw Exception()`, and also to variable declarations. The errors to identify include:

* CS1955: Non-invocable member 'Name' cannot be used like a method
* CS1525: Invalid expression term 'object'

```
Exception e = Exception(); // CS1955
object value = object(); // CS1525
```

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:27
Closing due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-21 19:27 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement
