### ISSUE TITLE
SymbolFinder can't translate framework type symbols if original compilation targets different framework

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#45404] opened 2020-06-23 21:08 UTC
For example, compilation c1 targeting net472 and c2 targeting netstandard, and c1 reference c2. If we get type symbol for string from c2 and and want to find its equivalent in c1 via `SymbolFinder.FindSimilarSymbols`, it will fail because those types are from different assemblies. Here's the symbolkey for both

`{1 (D "String" (N "System" 0 (N "" 0 (U (S "netstandard" 4) 3) 2) 1) 0 0 (% 0) 0)}`
`{1 (D "String"(N "System" 0(N "" 0(U(S "mscorlib" 4) 3) 2) 1) 0 0(% 0) 0)}`

Case like this should be handled by SymbolFinder.

**Comment by tmat** [comment] 2020-06-23 21:21
Are we properly following type-forwarders?

**Comment by genlu** [comment] 2020-06-23 21:39
I don't think so, the resolution would fail in the example above. Although in my scenario, I can workaround this by setting`ignoreAssemblyKey` to true for resolution and still get correct result.

**Comment by sharwell** [comment] 2020-06-23 21:50
> Are we properly following type-forwarders?

There is no type-forwarding relationship between the types in the example above.

**Comment by sharwell** [comment] 2020-06-23 21:58
This isn't really a bug. It's more an improvement that allows for type equivalence mappings in cases where there is no relationship between the types.

I would propose that we allow two type symbols to be considered "similar" if the following holds:

1. The only difference between the two is the assembly
2. One of the following is true:
    1. One of the symbols resolves _to the second_ in its context when type forwarders are considered (this could occur in either direction)
    1. The assemblies for the symbols are mutually exclusive (i.e. the first assembly does not appear in the second compilation, and the second assembly does not appear in the first compilation)

There are still some edge cases where this would not work, e.g. the net472 inclusion of nullability attributes in Microsoft.CodeAnalysis would not map to the framework types in netcoreapp3.1. However, I do believe it would work for most cases. I would be interested to hear alternative proposals.

**Comment by genlu** [comment] 2020-06-23 22:27
I think the two conditions you proposed make sense. But mutual exclusion is impossible to check given just a symbolkey, since you don't have the original compilation to verify that.

**Comment by CyrusNajmabadi** [comment] 2020-06-23 23:09
Note that translation across compilations with different frameworks was never in scope of what symbolkey was intended for.  It was either for:

1. re-resolving the same symbol in the same compilation.  (i.e. what OOP does).
2. re-resolving the symbol in a later version of the same compilation.  i.e. trying to track a symbol forward in a compilation across unrelated edits.
3. resolving top level symbols across VB/C#.  Technically you could hit the targetting issue, but it would normally be pretty unlikely for our use cases which would only be looking at the lang symbols themselves.  

I believe someone added the `ignoreAssembly` flag to help out with the retargetting case.  I also think that once you have retargeting involved it's likely going to be the case that you can jsut match by FQN and get good enough results. i.e. if you have System.String in one compilation, then having that match System.String in another is likely going to be rigth in the 99.99% case, and caring about the 0.01 case isn't really relevant.  This is esp. true as the existing logic means that we fail in all the majority and minority case instead of only failing in teh minority case.

**Comment by genlu** [comment] 2020-06-23 23:46
`ignoreAssembly` does the work, but it's not performant enough to meet my requirement for completion. I did experiment which triggers completion for unimproted extension methods 5 times in Roslyn.sln, with `ignoreAssembly` on and off. Avg overhead per completion session is ~150ms.

![image](https://user-images.githubusercontent.com/788783/85478241-bbcd9b00-b570-11ea-8e6e-5ced71280817.png)

**Comment by CyrusNajmabadi** [comment] 2022-11-02 19:33
Closing out as there does nto appear to be a driving reason to change this and it's not assigned to any milestone.

**Closed by CyrusNajmabadi** 2022-11-02 19:33 UTC
Labels: Area-IDE, Concept-Continuous Improvement
