### ISSUE TITLE
[Test Failure] xUnit returned error code without errors (+1 more) in prtest/win/dbg/unit64 on PR #7672

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7690] opened 2015-12-23 22:39 UTC
PR: [#7672](https://github.com/dotnet/roslyn/pull/7672) *Guard against being passed bad symbols or expressions* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2382/

**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Issue 2: Test Failures**
There were test failures, see Test Results above.

Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll exited with code 1

**Comment by dpoeschl** [comment] 2015-12-23 22:59
```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
  Discovered:  Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
  Starting:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.SuppressCopy1
    Microsoft.CodeAnalysis.Scripting.Test.EventListenerCrash_Workaround.WaitFor10Seconds
    Microsoft.CodeAnalysis.UnitTests.GlobalAssemblyCacheTests.AssemblyAndGacLocation
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.Errors
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.XmlDocComments_SpecificCulture
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.SuppressCopy_ShadowCopyDirectory
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.DisposalOnFailure
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.Modules
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.GetMetadata
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.Copy
    Microsoft.CodeAnalysis.Scripting.Hosting.UnitTests.MetadataShadowCopyProviderTests.SuppressCopy_Framework
    Microsoft.CodeAnalysis.UnitTests.GlobalAssemblyCacheTests.GetAssemblyIdentities
    Microsoft.CodeAnalysis.UnitTests.GlobalAssemblyCacheTests.GetAssemblyIdentities [SKIP]
      https://github.com/dotnet/roslyn/issues/6179
  Finished:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

**Comment by dpoeschl** [comment] 2015-12-23 23:00
Dupe of https://github.com/dotnet/roslyn/issues/6358. I believe @davkean had thoughts on getting this error surfaced through our build logs (and therefore the Jenkins failure indications) again.

**Closed** 2015-12-23 23:00 UTC
Labels: Bug, Flaky, Test
