### ISSUE TITLE
ITypeSymbol AllInterfaces not reporting code generated Interfaces in some cases

### ISSUE THREAD

**Issue by crwsolutions** [dotnet/roslyn#64447] opened 2022-10-03 19:31 UTC
**Version Used**: C# 6.0

**Steps to Reproduce**:

1. Start a new library project. Import nuget: sourcedepend and AutomaticInterface
2. Use the following code (GenerateAutomaticInterface is generating interfaces automatically):
```csharp
[InjectTransient]
[GenerateAutomaticInterface]
public class Class1 : IClass1
{ }

[InjectTransient]
public class Class2 : IClass2
{ }

public partial interface IClass2
{ }

[GenerateAutomaticInterface]
[InjectTransient]
public class Class3 : IClass2, IClass3
{ }
```
Generate GenerateAutomaticInterface Attribute via the lightbulp in a new file, so that it all compiles.

**Expected Behavior**:

In the generated class GeneratedServicesExtension of nuget sourcedepend the following line should be added:
```csharp
services.AddTransient<IClass1, InterfaceProblemMagWeg.Class1>();
```
**Actual Behavior**:
This line is missing. 

**Analysis**
If I debug the package (sourcedepend), the following line gives the problem:
```csharp
foreach (var interf in ((ITypeSymbol)symbol).AllInterfaces)
```
the interface is in the ITypeSymbol.BaseType property and not in the AllInterfaces collection. So that is the underlying reason that the sourcedepend generator is missing the interface. I think this is a bug and not something they can solve.

The Class2 situation is correct. (interface is manual). When I debug this, the interface is in the Allinterfaces collection and not in the ITypeSymbol.BaseType property (which contains object)

The Class3 situation is also correct, although one of the interfaces is generated. So when another interface is added, the problem is suddenly solved.

**Comment by CyrusNajmabadi** [comment] 2022-10-03 19:46
> the interface is in the ITypeSymbol.BaseType property 

Can you look and see if it's .TypeKind is TypeKind.ErrorType?

**Comment by Youssef1313** [comment] 2022-10-03 19:55
Your code defines an `IClass2`, but not `IClass1`. Where does `IClass1` come from?

**Comment by crwsolutions** [comment] 2022-10-04 13:51
> 

Thats generated by that [GenerateAutomaticInterface], this is generated:

```csharp
//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace InterfaceProblemMagWeg
{
    [GeneratedCode("AutomaticInterface", "")]
    public partial interface IClass1
    {
    }
}
```

**Comment by crwsolutions** [comment] 2022-10-04 13:56
> > the interface is in the ITypeSymbol.BaseType property
> 
> Can you look and see if it's .TypeKind is TypeKind.ErrorType?

Yes it is

**Comment by crwsolutions** [comment] 2022-10-04 14:04
> I guess this explains the problem. Source generators can't depend on the output of each others. This is a known limitation.

Ok, I can imagine that stacking generators is very complicated, but it is remarkable that it does work when an generated interface is combined with a manual interface. So it is not a very hard limitation.

**Comment by Youssef1313** [comment] 2022-10-04 14:07
> it does work when an generated interface is combined with a manual interface

Do you mean a partial interface, where one part is generated and the other is not? In that case, the generator still doesn't know about the part that's generated, and the symbol is only resolved because of the non-generated partial. This is a very different case.

**Comment by crwsolutions** [comment] 2022-10-04 14:15
> > it does work when an generated interface is combined with a manual interface
> 
> Do you mean a partial interface, where one part is generated and the other is not? In that case, the generator still doesn't know about the part that's generated, and the symbol is only resolved because of the non-generated partial. This is a very different case.

My example in the topic start shows all manual code there is. So IClass3 is completely generated and there is no manual part. I was surprised at that too that that didn't give the same problem.

**Comment by jaredpar** [comment] 2022-10-10 21:23
Closing as generator ordering is not yet supported so this is working as intended

**Closed by jaredpar** 2022-10-10 21:23 UTC
Labels: Area-Compilers, untriaged
