### ISSUE TITLE
BasicExpressionEvaluator.EvaluatePrimitiveValues flakeyness

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20815] opened 2017-07-12 00:57 UTC
Failed here: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6198/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicExpressionEvaluator/EvaluatePrimitiveValues/

```
Stacktrace

MESSAGE:
System.Runtime.InteropServices.COMException : Operation not supported. Unknown error: 0x8971003c.
+++++++++++++++++++
STACK TRACE:
Server stack trace: at EnvDTE.Debugger.StepOver(Boolean WaitForBreakOrEnd) at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd) at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd) at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Debugger_OutOfProc.StepOver(Boolean waitForBreakOrEnd) at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.Dispose(Boolean disposing) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicExpressionEvaluator.cs:line 149 at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs:line 30 at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by dpoeschl** [comment] 2017-07-25 17:41
Dupe of https://github.com/dotnet/roslyn/issues/20979 (which is newer but has more context)

**Closed by dpoeschl** 2017-07-25 17:41 UTC
Labels: Area-Interactive, Test
