### ISSUE TITLE
'Change signature' preview reference changes doesn't work

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62825] opened 2022-07-21 09:47 UTC
Using https://github.com/dotnet/roslyn/commit/deabaa7744075fec2b2688872576561259761552

Go to https://github.com/dotnet/roslyn/blob/deabaa7744075fec2b2688872576561259761552/src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs#L72

Invoke "Change signature" and remove the unused `language` parameter, check the "Preview reference changes" checkbox.

Note that changes are written to disk directly without a preview.

**Comment by sharwell** [comment] 2023-03-22 17:18
Duplicate of #4608

**Closed by sharwell** 2023-03-22 17:18 UTC
Labels: Bug, help wanted, Area-IDE
