### ISSUE TITLE
[Bug] Redundant line break before { in property getter with attribute applied

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#6415] opened 2015-10-29 11:57 UTC
I have a code below in my .cs file:
```cs
class Program
{
    public int Property
    {
        get { return 0; }
    }
}
```
After inserting a [DebuggerStepThrough] to the getter and formatting document (Menu Edit, Advanced, Format Document) I have
```cs
class Program
{
    public int Property
    {
        [System.Diagnostics.DebuggerStepThrough]
        get
        { return 0; }
    }
}
```

**Comment by Pilchie** [comment] 2015-10-29 16:36
This is a duplicate of #4720, which should be fixed in VS2015 Update 1 RTM.

**Closed by Pilchie** 2015-10-29 16:36 UTC
Labels: Area-IDE, Bug

**Comment by ViIvanov** [comment] 2015-10-30 13:19
Thank you!

I'm sorry for posting duplicate, will try to search deeper next time.

**Comment by Pilchie** [comment] 2015-10-30 16:23
No problem - I'd rather get duplicate reports than not hear about bugs so they go unfixed.
