### ISSUE TITLE
CA1823 warning disappears after navigation

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#23406] opened 2017-11-27 23:13 UTC
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1410

**Version Used**: 
D15rel 27123.00
**Steps to Reproduce**:
1. Clone https://github.com/shadowsocks/shadowsocks-windows
2. Install Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.0-beta1-62322-01 from https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.0-beta1-62322-01#
3. Enable CA1810 for code analysis and build the project.
4. Navigate to the only CA1823 warning which points to line 106 in UnitTest.cs
private static object locker = new object();
The warning is valid as a FAR doesn't pull up any other instances of locker.

**Expected Behavior**:
The warning stays.
**Actual Behavior**:
The warning disappeared either after navigating to the warning location or running a FAR to check if the warning was valid.

**Comment by jinujoseph** [comment] 2017-11-29 00:15
related to #23407

**Comment by jinujoseph** [comment] 2018-01-23 02:11
closed as dupe of #23407

**Closed by jinujoseph** 2018-01-23 02:11 UTC
Labels: Area-Analyzers, Bug
