### ISSUE TITLE
ToString() in Intellisense should include the () by default.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50338] opened 2021-01-08 20:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ToString-in-Intellisense-should-includ/1299982)._

---
The **ToString()** static method is used numerous times while testing. For convenience, the **intellisense**  should include the parenthesis by default to make the life of the programmer much easier.

---
#### Feedback Bot on 1/4/2021, 00:42 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by PathogenDavid** [comment] 2021-01-10 18:47
If this is added, for the love of muscle memory please make it optional.

**Comment by sharwell** [comment] 2021-01-10 21:32
Duplicate of #12363

**Closed by sharwell** 2021-01-10 21:32 UTC

**Comment by sharwell** [comment] 2021-01-10 21:33
This request is a portion of the discussion in #12363. For example, see https://github.com/dotnet/roslyn/issues/12363#issuecomment-747183276.
