### ISSUE TITLE
[Proposal] Allow passing constructor directly to methods accepting delegate

### ISSUE THREAD

**Issue by ghord** [dotnet/roslyn#1724] opened 2015-04-01 09:28 UTC
Given class definition:

```
public class Foo
{
    public Foo(string str) { ... }
  
    public static Foo FromString(string str) => new Foo(str);
}
```
and method

`void Test(Func<string, Foo> fooFactory)`

You can pass method group as parameter, and compiler selects best method to use - both `Test(str => Foo.FromString(str));` and `Test(Foo.FromString);` are valid.

Unfortunately, with constructor it only accepts `Test(str => new Foo(str))` syntax.

My proposal is to allow passing of constructor as method group like this:

`Test(new Foo); //uses constructor of Foo`

It would help making C# more consistent and remove unnecessary lambda expression.

**Comment by HaloFour** [comment] 2015-04-01 10:19
This would be a dupe of #140 .

It could be syntax candy but the net effect would have to be the same as constructors aren't invoked like normal methods.

**Comment by gafter** [comment] 2015-04-02 17:51
Closing as a dup of #140

**Closed by gafter** 2015-04-02 17:51 UTC
Labels: Area-Compilers, Area-Language Design, Feature Request
