### ISSUE TITLE
'ExtractMethodCodeRefactoringProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44214] opened 2020-05-13 16:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1027598/extractmethodcoderefactoringprovider-encountered-a-25.html)._

---

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetCallSiteContainerFromExpression()
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetOutermostCallSiteContainerToProcess(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethod(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

---
#### Visual Studio Feedback System on 5/12/2020, 08:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/12/2020, 08:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-05-20 19:09
💭 Possibly related to #41478, though the exception is a bit different

**Comment by verelpode** [comment] 2020-06-12 10:45
Me too.  ExtractMethodCodeRefactoringProvider crashes on me every second or third day, and this has been happening ever since the feature was introduced (last year I think).  I've submitted multiple bug reports about it, along with other people experiencing the same problems, but these bug reports have been marked as "fixed" and closed, but ExtractMethodCodeRefactoringProvider continues to crash frequently for one reason or another.  (Currently I'm using VS 16.6.2.)

I wish for an option to disable ExtractMethodCodeRefactoringProvider entirely, permanently.  I never use this feature, and I'm never going to use it, but despite the fact that I never use it, I still have to suffer frequent messages reporting that it crashed yet again.  

**It crashes again and again and again, multiple times every week of every month, ever since it was first introduced.**

It is quite a strange and surprising situation when you don't even use something but still suffer its crashes.  
It is like a buggy app was installed in your computer, and you NEVER EVER open this app, but nevertheless the app still crashes frequently, even though you never run the app!!

Therefore please allow us to switch off the ExtractMethodCodeRefactoringProvider.

**Comment by verelpode** [comment] 2020-06-12 11:01
Instead of a fancy feature such as ExtractMethodCodeRefactoringProvider, guess what I'd actually love to have.  Guess what my greatest biggest `#1` wish is.

You're probably expecting a huge and difficult wish, but no, my greatest wish is for the bare essentials.  Above all else, I wish for merely the basics.

At this point, a bunch of people would reply:
> _"What are you talking about?  Visual Studio already has all the basics!"_

No, it doesn't.  For the last 5-10 years, Visual Studio has lacked the basic essential ability to add and remove files from a ".csproj" in a reliable manner.

Again a bunch of people would reply:
> _"What are you talking about?  Visual Studio already allows you to add and remove files from a .csproj!"_

No, it doesn't.  Not reliably.  _Hundreds_ of times during the last 5-10 years, I've been forced to repeat this workaround/hack for multiple different .csproj's:
1. Close the .sln.
2. Delete the hidden ".vs" folder.
3. Reopen the .sln.

Visual Studio has only a buggy unreliable ability to add and remove files from a .csproj.  Visual Studio often causes corrupt or incorrect data in the ".vs" folder, and this breaks Roslyn, intellisense, etc, until the ".vs" folder is deleted.

For a long time now, every damn week of every month, I'm forced to delete one or more ".vs" folders yet again, and in addition, suffer the frequent crashing of ExtractMethodCodeRefactoringProvider despite never using it.

Thus my greatest wish is to have the basics, the bare essentials.  Meanwhile an extraordinary amount of effort goes into fixing ExtractMethodCodeRefactoringProvider while the bare essentials continue to be ignored, even after a decade of waiting :-(

**Comment by verelpode** [comment] 2020-06-12 11:40
Here is another example of the bizarre situation where so much effort goes into ExtractMethodCodeRefactoringProvider while the basic essentials are ignored for many years:

Rosyln and/or Visual Studio doesn't handle the basic essential issue of which C# classes are included or excluded in an app.  It is shocking to see, even after so many years, over a decade, Visual Studio _still_ forces C# developers to perform **tedious manual management** of the inclusion and exclusion of C# classes.

Long ago, back when I began my career, back in the Wild Wild West days when we wrote programs using C++ and Win16 (later renamed to Win32), the situation was horrific.  It was a nightmare.  Nowadays the situation has greatly improved.  However, even back then when software engineering was a horrific nightmare of C++ and Win32, Visual Studio **automatically handled the inclusion and exclusion of classes**.

When C# was introduced, it delivered many advantages, but unfortunately a few of the basic essentials were lost.  This loss was reasonable for a limited amount of time, but now it has been over a decade and Visual Studio and/or Roslyn is _still_ missing the automatic inclusion and exclusion of classes.  Visual C++ had it, and still has it, but Visual Studio's C# compiler is still missing it.

Do you remember Microsoft Foundation Classes (MFC) from the Wild Wild West days, long ago?  If you used this class library, _or any other class library_, Visual C++ automatically managed the inclusion and exclusion of classes.   It did not require you to manually tediously add and remove individual .cpp files according to which MFC classes you do and don't use in a particular app.

You just simply added the entire class library to your project, and Visual C++ automatically selected the classes that your app actually uses, and excluded the rest.  _There was no requirement to manually manage this tedious aspect._

In contrast, when you use Roslyn / Visual Studio to make a C# app, then overall yes it is a huge improvement over C++ Wild West, but it is _still_ lacking the basic essential ability to automatically include the classes that your app actually uses and exclude the rest.

When Visual Studio produces your output .exe file from your .csproj, overall it's very smart and impressive, but one aspect is shockingly dumb:  When your .csproj uses, for example, 3 different class libraries, Visual Studio dumps EVERY class into your output .exe file!  It dumps HUNDREDS OF UNUSED CLASSES into your .exe file!  It's unbelieveable.  

Visual Studio forces you to manually analyze hundreds of .cs files in order to determine which ones you should include and exclude from your .csproj.  For a large commercial project, this is a huge amount of tedious work, and just when you think you finally finished doing it, you have to start the whole task again because you made many changes to the latest version of your app.  Visual C++ handled this automatically for you, whereas for C# it still doesn't, even after so many years.

So here is a very good plan:
Stop wasting so much time and energy on ExtractMethodCodeRefactoringProvider, and instead implement the basic bare essentials.  For now, remove the ExtractMethodCodeRefactoringProvider component until some future point in time, AFTER the basic essentials have been completed.

**Comment by verelpode** [comment] 2020-06-12 15:00
Oh my god, only 3 hours later after I posted my message, it happened again -- see following stack trace.  When will it end?!  Please give us a setting to permanently switch off this buggy component from hell (ExtractMethodCodeRefactoringProvider).  This happened with VS 16.6.2.
I'm never going to use this "feature" because I've had such a terrible long-term experience with it that I will never be able to **trust** it enough to use it on code for customers.

In order to have such an unusually terrible long-term history of never-ending failures (even after Microsoft's repeated attempts to fix it), this ExtractMethodCodeRefactoringProvider must surely be very poorly designed and written.  

**What would our customers think if they knew I used such an untrustworthy buggy tool on their sensitive code?**

It would be irresponsible of me to risk damage to our customers by using such a badly written tool that might mangle sensitive source code, and who knows what else.  

It cannot be trusted.  It would be unprofessional and irresponsible of us to use such a bug-infested component on sensitive source code for our customers.  This is the last straw.  This ExtractMethodCodeRefactoringProvider is now officially **blacklisted** from our development practices, now and in future, permanently.  Please allow us to switch it off permanently.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node,Boolean invoked,Boolean indexed,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindEmbeddedBlock(BlockSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalFunctionStatement(LocalFunctionStatementSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder,CSharpSyntaxNode node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder,CSharpSyntaxNode node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node,CSharpSyntaxNode& bindableNode,BoundNode& lowestBoundNode,BoundNode& highestBoundNode,BoundNode& boundParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node,SymbolInfoOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node,SymbolInfoOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Simplification.SimplificationHelpers.GetOriginalSymbolInfo(SemanticModel semanticModel,SyntaxNode expression)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.NameSimplifier.TrySimplify(NameSyntax name,SemanticModel semanticModel,OptionSet optionSet,TypeSyntax& replacementNode,TextSpan& issueSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.ExpressionSimplifier.TryReduceExplicitName(ExpressionSyntax expression,SemanticModel semanticModel,TypeSyntax& replacementNode,TextSpan& issueSpan,OptionSet optionSet,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.ExpressionSimplifier.TrySimplify(ExpressionSyntax expression,SemanticModel semanticModel,OptionSet optionSet,ExpressionSyntax& replacementNode,TextSpan& issueSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.SimplifyName(SyntaxNode node,SemanticModel semanticModel,OptionSet optionSet,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyNode[TNode](TNode node,SyntaxNode newNode,SyntaxNode parentNode,Func`5 simplifier)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyExpression[TExpression](TExpression expression,SyntaxNode newNode,Func`5 simplifier)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitIdentifierName(IdentifierNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitAliasQualifiedName(AliasQualifiedNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitAliasQualifiedName(AliasQualifiedNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.AliasQualifiedNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitQualifiedName(QualifiedNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpNameReducer.Rewriter.VisitQualifiedName(QualifiedNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.VisitNodeOrToken(SyntaxNodeOrToken nodeOrToken,SemanticModel semanticModel,Boolean simplifyAllDescendants)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.<>c__DisplayClass10_1.<ReduceAsync>b__0[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.ReduceCoreAsync[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.ReduceAsync[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.Simplifier.ReduceAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractLocalFunctionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by sharwell** [comment] 2020-06-12 15:25
> Therefore please allow us to switch off the ExtractMethodCodeRefactoringProvider.

This feature request is tracked by #4032

> Visual Studio has lacked the basic essential ability to add and remove files from a ".csproj" in a reliable manner

We can't really do anything about this in dotnet/roslyn. I would recommend filing an issue either through [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) or on [dotnet/project-system](https://github.com/dotnet/project-system/), especially if you have a way to reproduce this.

>  lacking the basic essential ability to automatically include the classes that your app actually uses and exclude the rest

I would recommend filing a new feature request for this. I wasn't able to find any open issues requesting it, so it's possibly not tracked at all.

> NullReferenceException  ... FindConditionalAccessNodeForBinding

This issue is #41895, which is a separate bug from this issue.

**Comment by verelpode** [comment] 2020-06-16 10:42
Here is another example of the problem of doing fun work instead of finishing the basic essentials.  This example isn't the responsibility of Roslyn, but it helps demonstrate how pervasive and serious the problem is.  Since the dawn of time, C++ had `memcmp` and `memset` functions.  The equivalents of these basic functions were missing in the C# .NET Framework for nearly 2 decades after the C# language was introduced!  These basic essentials were ignored for **17 years**!!  

Thankfully, now there exists `System.MemoryExtensions.SequenceEqual` and `System.Array.Fill`, but it took an awful long time for these basic essentials to finally arrive.  The basics should have been completed within a year or two of the release of C# 1.0.  It's unreasonable to expect customers to wait decades for the basic essentials.

UWP is also a major case of ignoring the basic essentials for many years.  The catastrophic failure of UWP caused billion-dollar losses for Microsoft, and it was blamed on developers not appreciating the security features of UWP.  In reality, people like me **loved** the security features of UWP.  The real problem was that UWP was perpetually stuck in alpha phase.  It was called a "release" version but actually it was an alpha version.  A feature-complete beta version of UWP was never released.  Today I'm still waiting for a genuine (meaning feature-complete) beta version of UWP to be released.

I admit I'm also guilty of choosing to do fun work instead of the boring basic essentials, but I procrastinate for a few months whereas Microsoft procrastinates for a decade or two.

**ExtractMethodCodeRefactoringProvider = procrastination.**  It's more fun to mess around with ExtractMethodCodeRefactoringProvider than to finally finish the basic essentials in Visual Studio.  The essentials are far more valuable but they're _boring_, whereas ExtractMethodCodeRefactoringProvider has little value but is _interesting_ to try to write.

**Comment by verelpode** [comment] 2020-06-16 12:49
@sharwell
Could you please consider abiding by the [GitHub Community Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines)?   The "mark as off-topic" feature in GitHub is intended for marking off-topic messages -- that's why it's called "off-topic".  It's inappropriate to misuse this feature for the purpose of shooting the messenger who delivered the bad news.  The professional manner of dealing with problems is to fix the problems, not just sweep them under the carpet and hope they disappear -- that doesn't work.

The problems needs to be addressed in an objective manner, not an emotional manner.  When a message gives you the feeling "I don't like this message; this message gives me a bad feeling", it's inappropriate to deal with these emotional feelings by misusing the "mark as off-topic" feature.

**Comment by CyrusNajmabadi** [comment] 2020-06-16 16:35
Hi @verelpode, i've hidden your comments for being off-topic.  Roslyn issues are intended solely for reporting bugs or feature requests for the Roslyn project.  Please keep your responses focused on that.

You are welcome to your opinions, but please find a more suitable location to voice them.  For example, there are many blog platforms you could use to share your views on the .net ecosystem and the choices made by these teams.  Or, if you would prefer a more chat-oriented venue, there is gitter.im/dotnet/roslyn or dotnet/runtime, and there is is discord.gg/csharp.  

Future off-topic posts will be hidden, and will result in potential consequences for continued behavior that doesn't follow our repo guidelines. 

Thanks much!

Thanks much!

**Comment by jnm2** [comment] 2020-12-10 02:16
Hit this in 16.8.3. I think I might have been selecting statements that were temporarily pasted directly inside a namespace, but I'm not sure.

**Comment by Youssef1313** [comment] 2021-04-29 21:25
Possible dupe of https://github.com/dotnet/roslyn/issues/35435.

FYI @akhera99 to get both issues closed with your PR.

**Comment by sharwell** [comment] 2021-07-09 15:13
Duplicate of #54713

**Closed by sharwell** 2021-07-09 15:13 UTC
Labels: Area-IDE, Bug, Developer Community, IDE-CodeStyle, help wanted
