### ISSUE TITLE
Response file with spaces in analyzer path throw source file not found

### ISSUE THREAD

**Issue by JurjenBiewenga** [dotnet/roslyn#39777] opened 2019-11-12 14:38 UTC
**Version Used**:  2.9.1.65535 (Unity 2019.1.10f1)

**Steps to Reproduce**:

1. Create csc.rsp file
2. Add an analyzer argument with spaces in the path (I'm currently passing multiple analyzers with the last one having spaces)
3. Compile with the csc.rsp file

Example csc.rsp file:
```cs
-doc:Library/ScriptAssemblies/CleVR.PlayModeTests.Utilities.xml
-a:C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files (x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll
-ruleset:C:\CleVR\VisualStudio\Analyzers\CleVRUnity.ruleset
-additionalfile:C:\CleVR\VisualStudio\Analyzers\stylecop.json
```

**Expected Behavior**:
Successful compilation with the given analyzer used.

**Actual Behavior**:
```cs
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\Files' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\(x86)\Microsoft' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\Visual' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\Studio' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\Tools' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\for' could not be found.
error CS2001: Source file 'C:\git\fram\utilities\Unity.Utilities\Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll' could not be found.
```

**Comment by sharwell** [comment] 2019-11-27 23:03
@gafter moved back to compilers. The error here is CS2001 (related to source files, not to analyzers).

**Comment by jaredpar** [comment] 2019-12-14 01:02
This behavior is "By Design". Paths in the response file must be quoted if paths include spaces.

**Comment by JurjenBiewenga** [comment] 2019-12-14 08:21
I've tried these variations of passing the arguments and none of them work seem to work properly.

```-a:C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files(x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll
-a:"C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files(x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll"
-a:\"C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files(x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll\"
"-a:C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files(x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll"
\"-a:C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.dll;C:\CleVR\VisualStudio\Analyzers\StyleCop\StyleCop.Analyzers.CodeFixes.dll;C:\Program Files(x86)\Microsoft Visual Studio Tools for Unity\16.0\Analyzers\Microsoft.Unity.Analyzers.dll\"```

The [SplitCommandIntoArguments](http://sourceroslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/CommandLineUtilities.cs,7ca550d25eeed46b) method parses the `"a:path"` variation properly but it still ends up being parsed wrong at some other place.

**Comment by jaredpar** [comment] 2019-12-16 17:14
Re-closing. This behavior is "By Design" as stated above. 

The indivdiual paths need to be quoted here, not the group of  paths as an item. It's probably much easier in this case to just specify `/analyzer` multiple times, once per analyzer, with quotes around the path.

**Closed by jaredpar** 2019-12-16 17:14 UTC
Labels: Area-Compilers, Resolution-By Design
