### ISSUE TITLE
Invalid implicit cast of async lambda expression to Action

### ISSUE THREAD

**Issue by SvenVranckx** [dotnet/roslyn#73745] opened 2024-05-28 19:33 UTC
**Version Used**:  Visual Studio 2022 17.9.3

**Steps to Reproduce**:

```csharp
public async Task Run(Action action)
{
    action.Invoke();
    await Task.CompletedTask;
}

public async Task Execute()
{
    try
    {
        await Run(async () => 
        {
            await Task.CompletedTask;
            throw new Exception();
        });
    }
    catch (Exception)
    {
    }
}
```

**Expected Behavior**:

The compiler should raise a syntax error on the line that calls the `Run` method

**Actual Behavior**:

The compiler implicitly converts the async lambda expression to `Action` when calling `Run`.
As a result of this, the `Run` method will now run the async lambda expression as an unawaited task
The exception that is thrown by the lambda expression is unhandled and the application crashes

**Comment by CyrusNajmabadi** [comment] 2024-05-28 19:41
I'm not getting why this is invalid.  From my reading of the lang spec.  This is fine.  The lambda can be converted to an Action, so this is legal.

--

It might be seomthing you could want an analyzer to warn on.

**Comment by VulumeCode** [comment] 2024-05-28 20:13
Why is that possible, but not this? 

![image](https://github.com/dotnet/roslyn/assets/2590984/09f0f2ec-f53d-4aca-ad21-7f238cc2991d)

**Comment by CyrusNajmabadi** [comment] 2024-05-28 20:25
because a `Func<T>` is not an `Action`.  However, in your code you don't have a `Func<T>`.  You have a lambda-expression.  Lambda expressions have broad covertibility to both Func and Action. For example, consider the following:


```c#
HashSet<string> set = ...;

DoWork(() => set.Add("foo"));

void DoWork(Action action)
{
    try { action(); } catch { }
}
```

We want `() => set.Add("foo")` to be convertible to an Action here.  After all, there's no reason it shouldn't be.  All Action says is "i take no args, and return no value".  So, even though `set.Add` returns a `bool` we want to allow this to convert, versus saying `Func<bool>` is not convertible to an `Action`.

**Comment by CyrusNajmabadi** [comment] 2024-05-28 20:28
This is also why you can have lambdas which throw, which are then convertible to `Func<>` as well.  The lamba doesn't ever return the return value that the Func needs.  But that's not important.  What's important is that any *reachable* end point of hte lambda abides by the return type.  As there are no reachable endpoints teh lambda is compatible.

**Comment by SvenVranckx** [comment] 2024-05-28 20:28
I think that the `async` keyword in the lambda expression should be an indication that this is not just an expression returning `Task` or `Task<T>`, but that it needs some special attention.

A compiler warning might be a good start

**Comment by CyrusNajmabadi** [comment] 2024-05-28 20:34
I'll let compiler decide if htey want a warning wave here (it would have to be done in a wave as this will definitely break existing code).  

If they dont', it would need to be a request to roslyn-analyzers.  Personally i see nothing wrong with this.  People may be creating a list of callbacks, some of which want to operate internally asynchronously.  THat's a normal pattern.  For example, event handlers to do thsi when they get their synchronous invocations, but enqueue work into a queue which may itself be synchronous or asynchronous.

**Comment by SvenVranckx** [comment] 2024-05-28 20:45
I understand. But using an async lambda as Action is guaranteed to be an unawaited task. Visual Studio does show a warning wave whenever a simple async method call lacks the `await` keyword. This could be treated as a special case of that warning

**Comment by huoyaoyuan** [comment] 2024-05-30 17:46
`async void` is a thing. The most typicall usage of it is using as delegates that does't accept task, like this:

```csharp
event EventHandlet ButtonClick;

void InitializeEvents()
{
    ButtonClick += async (sender, args) =>
    {
        await DoSomeRequestAsync();
        SomeText.Text = "Done";
    };
}
```

This pattern is often used in GUI frameworks, for WinForms and WPF.

**Comment by jaredpar** [comment] 2024-06-05 17:17
> But using an async lambda as Action is guaranteed to be an unawaited task.

Correct but this is a case the language supports today. There are similar cases like `async void` which are equally dangerous that are explicitly part of the language design. The transition to `async` was unfortunately messy and the language had to make allowances for edge cases like this to make the transition successful. 

>  Visual Studio does show a warning wave whenever a simple async method call lacks the await keyword. This could be treated as a special case of that warning

That would be a _massive_ breaking change to the ecosystem. Even having it as a warning wave would result in lots of churn in applications

Closing as this behavior is by design.

**Closed by jaredpar** 2024-06-05 17:17 UTC
Labels: Area-Compilers, untriaged
