### ISSUE TITLE
Rename does not change text in #region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45532] opened 2020-06-29 21:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1090759/rename-does-not-change-text-in-region.html)._

---
[regression]
I am not sure the last version in which this function worked.  I belive in an earlier 16.7 or 16.6

See the attached screen capture.

I have just completed a right click rename fo the class name.  It was ScheduleTime.
I right clicked.
Chose rename
checked  top 3 boxes
Typed the new name
Hit enter.
Notice that the ScheduleTime in the #region statements did not change.

---
#### Visual Studio Feedback System on 6/27/2020, 08:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2020-07-01 22:22
@sharwell confirmed that this works in 15.9 and is also working in 16.7.preview3

**Comment by sharwell** [comment] 2020-07-01 22:25
📝 Note that the inline rename preview makes it _look_ like this operation is working. It is only when you hit Apply that it fails to make the full set of expected changes.

**Comment by jinujoseph** [comment] 2020-07-01 22:26
cc @ryzngard fyi

**Comment by SOHODeveloper** [comment] 2020-07-08 12:33
Not to start a war, but at one point, the rename did work.  Cannot say how far back it was.  The new VS versions come fast and furiously. :-)

**Comment by CyrusNajmabadi** [comment] 2024-10-25 03:52
Closing out due to lack of broad feedback about this being an issue.

**Closed by CyrusNajmabadi** 2024-10-25 03:52 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, Developer Community, IDE-CodeStyle, Feature - Rename
