### ISSUE TITLE
See/Seealso tag completion should not insert > into attributes

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#4164] opened 2015-07-28 09:36 UTC
Consider the following code, $$ means the caret

```C#
/// <summary>
/// $$
/// </summary>
static void Main( string[] args )
{
}
```

Type `<see>` results `<see cref=">$$"/>`, but I expect `<see cref="$$"/>`

**Comment by Pilchie** [comment] 2015-07-30 17:27
Duplicate of #721.

**Closed** 2015-07-30 17:28 UTC
Labels: Area-IDE, Bug
