### ISSUE TITLE
The outline box of the inline rename is misleading

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#6121] opened 2015-10-18 05:38 UTC
It looks like a snippet field to me, but hitting <kbd>Enter</kbd> doesn't "commit".
![image](https://cloud.githubusercontent.com/assets/159110/10562714/48930a30-759c-11e5-9517-2542c108a349.png)

 In VS2013 there was a little underline, and I can associate that with <kbd>Ctrl</kbd> + <kbd>.</kbd>, I understand that little underline can be too subtle for somebody to spot, could be the reason why changed to lightbulb in VS2015.

But, can this outline be changed to full underline so it doesn't look like a snippet field?

**Comment by dpoeschl** [comment] 2015-10-18 19:52
@diryboy What theme do you have installed? By default, the Rename Tracking outline tag is dotted.

**Comment by diryboy** [comment] 2015-10-18 23:35
No I did not change the theme or install any plugin that changes theme, it's the default Blue theme with dark background color, I just changed the Foreground Color of Rename Tracking to red as I changed to a dark background.

**Comment by Pilchie** [comment] 2015-10-19 16:50
I believe the issue here is that if you change the color, it loses the dotted state of the marker.  Tagging @olegtk and @martw-t.

**Comment by Pilchie** [comment] 2015-10-19 16:52
@dpoeschl Can you follow-up to confirm?

**Comment by dpoeschl** [comment] 2015-10-19 16:54
Right, I totally forgot about that. Even applying the default dark theme color causes it to lose the dotted border. Sorry for the misunderstanding @diryboy.

**Comment by diryboy** [comment] 2015-10-19 23:37
So you are changing the border to dotted? That's ok. Thanks.

**Comment by dpoeschl** [comment] 2015-10-20 17:00
In the light/blue themes, the border is already dotted. The problem is with the VS platform theming capabilities, which don't allow us to theme the *color* for the dark theme without inadvertently dropping the dotted style. Would adding the dotted style be enough of a distinction to avoid the snippets confusion? Here's what it looks like in the blue theme:

![image](https://cloud.githubusercontent.com/assets/235241/10614863/63de4afe-7711-11e5-8f24-87eb2546cc08.png)

**Comment by diryboy** [comment] 2015-10-20 23:57
Not immediately but acceptable as there is some different, need time to correct, because color is changable between VS instances, some remote desktop instance are shared and won't allow me to change. I originally wanted it to be underline.

I'm using blue theme with editor background color changed to dark, not dark theme that makes everything in VS dark.

**Comment by Pilchie** [comment] 2016-01-25 17:38
@dpoeschl can this be fixed on the Roslyn side or does it require editor changes?  If the latter, is there an issue tracking that work?

**Comment by dpoeschl** [comment] 2017-06-15 16:42
@diryboy Thanks again for the report. The editor will allow the color to be changed while retaining the border dash style as of 15.3. From the above conversation, it sounds like that will be satisfactory?

**Closed by dpoeschl** 2017-06-15 16:42 UTC
Labels: Area-IDE, Feature Request

**Comment by diryboy** [comment] 2017-06-16 00:47
Yes, thanks.
