### ISSUE TITLE
VisualBasicSyntaxRewriter.Visit throws InvalidOperationException

### ISSUE THREAD

**Issue by didemg** [dotnet/roslyn#9019] opened 2016-02-22 21:31 UTC
VB syntax rewriter throw invalidoperationException
Simple code:

``` vb
 var vbTree = VisualBasicSyntaxTree.ParseText(text);
                        var vbComp = VisualBasicCompilation.Create(
                            fileName,
                            options: new VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
                            syntaxTrees: new[] { vbTree },
                            references: vbRefs);

var vbModel = vbComp.GetSemanticModel(vbTree);
var vbVisitor = new VBExprBinder(vbModel);
vbVisitor.Visit(vbTree.GetRoot());
var vbRewriter = new VBToStringInserter(vbModel);
var newVBRoot = (VisualBasicSyntaxNode)vbRewriter.Visit(vbTree.GetRoot());
```

VBToStringInserter:

```
internal class VBToStringInserter : VisualBasicSyntaxRewriter
    {
        private SemanticModel model = null;

    internal VBToStringInserter(SemanticModel model)
    {
        this.model = model;
    }

    public override SyntaxNode VisitInvocationExpression(InvocationExpressionSyntax node)
    {
        var specialType = SpecialType.None;
        var type = model.GetTypeInfo(node).Type;
        if (type != null)
        {
            specialType = type.SpecialType;
        }

        node = (InvocationExpressionSyntax)base.VisitInvocationExpression(node);
        return node;
    }
```

```
Unexpected value 'OperatorStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.CreateBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, Binder containingBinder) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 393
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position, Binder containingBinder) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 132
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.BinderFactoryVisitor.vb:line 247
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.VisitParameter(ParameterSyntax node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.BinderFactoryVisitor.vb:line 198
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16207
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.MakeBinder(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 50
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderAtOrAbove(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 94
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForPosition(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 87
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 163
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(VisualBasicSyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 170
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionTypeInfo(ExpressionSyntax node, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 288
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetTypeInfoWorker(ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 297
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 287
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetTypeInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\VisualBasicExtensions.vb:line 1365
   at SPOT.Transformer.VBToStringInserter.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\RoslynCode\VBToStringInserter.cs:line 19
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26623
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitBinaryExpression(BinaryExpressionSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 4057
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.BinaryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 28430
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitEqualsValue(EqualsValueSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2546
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.EqualsValueSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16004
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitParameter(ParameterSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2567
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16207
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 171
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitParameterList(ParameterListSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2078
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 11499
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitOperatorStatement(OperatorStatementSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2240
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.OperatorStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 13326
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitOperatorBlock(OperatorBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2008
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.OperatorBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 10839
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in 

d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNamespaceBlock(NamespaceBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1595
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6849
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1499
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6104
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at SPOT.Transformer.SourceFileProcessor.Process(String filePath, Stream contentsStream, String& details, String passStatus, String failStatus) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\RoslynCode\SourceFileProcessor.cs:line 68

```

[QueryParser.zip](https://github.com/dotnet/roslyn/files/141456/QueryParser.zip)

**Comment by OmarTawfik** [comment] 2017-02-20 18:57
@didemg can you please attach the value of `text` and `vbRefs` in your sample code?
The file attached is a C# parser. Not sure how it is related to the VB crash.

**Comment by OmarTawfik** [comment] 2017-02-24 21:34
Update: we don't have a repro anymore, but I believe it is a duplicate of #14688.
I'll re-open if we find more info.

**Closed by OmarTawfik** 2017-02-24 21:34 UTC
Labels: Area-Compilers, Bug
