### ISSUE TITLE
lifted comparison codegen can be improved

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#17261] opened 2017-02-20 19:00 UTC
In the codegen of lifted comparison operators some conditional branches seem unnecessary. 
They only serve to shortcircuit trivial bool operators over locals - that does not seem very profitable.

We should do something like in: https://github.com/dotnet/corefx/pull/15941
( Also check https://github.com/dotnet/corefx/pull/17535 if that is better )

Example:

We emit lifted equality for `left` and `right` as:

```cs
bool? result = (left.GetValueOrDefault() == right.GetValueOrDefault()) ?
                                                  ( left.HasValue == right.HasValue ) :
                                                   false;
```
A more efficient  would be:

```cs
bool? result = (left.GetValueOrDefault() == right.GetValueOrDefault()) & 
                                           (left.HasValue == right.HasValue);

```

**Comment by gafter** [comment] 2017-02-21 03:21
@VSadov Can you please spell out the issue (what kind of source, what IL do we generate now, and what IL would be better)?

**Comment by VSadov** [comment] 2017-03-01 00:50
added examples to the bug

**Comment by isc30** [comment] 2018-02-26 09:14
In case no newcomer wants this one, I can take care

**Comment by CyrusNajmabadi** [comment] 2018-02-26 09:46
Do you mean:

```c#
bool? result = (left.GetValueOrDefault() == right.GetValueOrDefault()) && 
                                           (left.HasValue == right.HasValue);
```

Instead of

```c#
bool? result = (left.GetValueOrDefault() == right.GetValueOrDefault()) & 
                                           (left.HasValue == right.HasValue);
```

?

It seems odd to use & as i thought it was not short-circuiting.  Why do the second part of the check if the first has already failed?

**Comment by CyrusNajmabadi** [comment] 2018-02-26 10:01
Hrmm.  i don't repro this locally. The IL i see generated seems to be of the form:

```
var v = left.HasValue == right.HasValue ? left.HasValue ? left.GetValueOrDefault() == right.GetValueOrDefault()) : false : false;
```

**Comment by CyrusNajmabadi** [comment] 2018-02-26 18:52
Gotcha.  Then that makes a lot of sense!

**Comment by isc30** [comment] 2018-03-01 07:51
How can I see the generated IL for this?

**Comment by Joe4evr** [comment] 2018-03-01 08:21
@isc30 You should check out [SharpLab](https://sharplab.io/).

**Comment by isc30** [comment] 2018-03-01 18:09
Thanks @Joe4evr 

I'm getting this for built-in types:

```
left.GetValueOrDefault() == right.GetValueOrDefault()
    && left.HasValue == right.HasValue;
```

I wasn't able to reproduce any of your cases tho. If you could create an example in **sharplab.io**  so we see what's the generated IL and how can be optimized would be great.

https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgoGYECY4DCcA3hnOXGRdnAEYD29ANnAEICuAlkwC4CSAOwAUAShJUKFTgJ4B+OJ3gBeOLjTpJASGlyFiOCoHsmTdZMkTzUAOwLlKziksBfS5ZoNmhJgEMAzn6i4hrm5EjwAMbKcABEAO70cTFmoXAAyjwATtIA5nAR+obGppYWIaE2+fb5TuVwrujOQA==

**Comment by svick** [comment] 2018-03-01 19:33
@isc30 That's the same as the example in the original post, since `a && b` is the same as `a ? b : false`.

If you look at [the IL](https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQMDMSBMCAwggN5YKUIVW4IBGA9oxAgEICukwAkgHYAKAJRkaVKmD7AA/AjCIAvAnwZM4gJCSZc5AiV8OECKvHixpmAHY5ipWDTmAvlkdA===), you will see the unnecessary conditional branch as `beq.s`.

Basically, this issue is about changing from `&&` to `&`.

**Comment by isc30** [comment] 2018-03-01 21:48
okay, this makes a lot of sense! thanks for the explanation

**Comment by alrz** [comment] 2018-03-30 18:15
Seems to be fixed in master. 
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGF8BvS/Dw24Aex4Bt8AWQAUASwB2MAPz4xSOVNkArAJSt2nLdgDsc/AF4D+ZeQpaAvpQtA

**Comment by svick** [comment] 2018-03-31 12:10
@alrz I still see `&&` (and not `&`) in the decompiled C# (and `beq.s` in the IL), so I don't think this was fixed. What makes you think otherwise?

**Comment by alrz** [comment] 2018-03-31 12:11
>What makes you think otherwise?

My vision loss.

**Comment by alrz** [comment] 2018-03-31 13:53
To be clear, the final codegen would look like this:
```cs
// We rewrite x == y as 
//
// tempx = x; 
// tempy = y;
// result = (tempx.GetValueOrDefault() == tempy.GetValueOrDefault()) &
//          (tempx.HasValue == tempy.HasValue);
//
// and x != y as
//
// tempx = x; 
// tempy = y;
// result = (tempx.GetValueOrDefault() != tempy.GetValueOrDefault()) ||
//          (tempx.HasValue != tempy.HasValue);
//
// Otherwise, we rewrite x OP y as
//
// tempx = x;
// tempy = y;
// result = (tempx.GetValueOrDefault() OP tempy.GetValueOrDefault()) &&
//          (tempx.HasValue & tempy.HasValue);
//
```
@VSadov can you confirm?

**Comment by alrz** [comment] 2018-03-31 13:55
Or we don't need short circuiting operators in all cases?

**Comment by isc30** [comment] 2018-04-03 16:29
why `||` and not `|`?

**Comment by VSadov** [comment] 2018-04-05 01:15
@alrz @isc30  - yes like that, and yes with regular `|` and `&`  - to be branchless.

It also makes sense to use DeMorgan dual of the `#2`  to avoid `!=` . The IL emit will have to use `ceq` and negate for the `!=`, but the following will have to negate only once, so it is a bit more compact:

```
// and x != y as
//
// tempx = x; 
// tempy = y;
// result = !((tempx.GetValueOrDefault() == tempy.GetValueOrDefault()) &
//          (tempx.HasValue == tempy.HasValue));
```

**Closed** 2018-04-06 23:00 UTC
Labels: Area-Compilers, Area-Performance, Bug, Concept-Code Quality Improvement, Language-C#, good first issue, help wanted
