### ISSUE TITLE
Formatter inserts newline before property initializer

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1637] opened 2015-03-27 13:15 UTC
Source:

```C#
class X {
	int C { get; }
	= "".Count(c => {
		return true;
	});
}
```

I found no way to prevent the formatter from adding the newline before the `=`.

**Comment by Pilchie** [comment] 2015-03-27 20:49
Dupe of #1298.

**Closed by Pilchie** 2015-03-27 20:49 UTC
Labels: Area-IDE, Bug
