### ISSUE TITLE
Allow Options With Folder Structure When Creating a Diagnostic or Refactoring Extension

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#192] opened 2015-01-31 16:00 UTC
If I create a project like a class library in a solution, the template creates that one project within the solution's folder. For example, if I have a solution called Solution1, and I create ClassLibrary1 within that solution, a ClassLibrary1 folder is created within the Solution1 folder, and ClassLibrary1's assets are within the ClassLibrary1 folder.

When I create a diagnostic, an intermediate folder is created. For example, making Diagnostic1 creates a Diagnostic1 folder under Solution1, and then the Diagnostic1, Diagnostic1.Test, and Diagnostic1.Vsix folders are under Diagnostic1. Also, the template automatically creates a test project. While I'm personally an advocate for tests, I think the user should have the option to make it. Also, don't append ".Test"; I usually name my test assemblies ".Tests" and the user should control over the naming of their assets.

I'd like it if the template gave the user more control over the location of the generated projects on disks along with their names.

(This currently exists with the VS2015 CTP5 templates and has been the case for some time).

**Comment by jmarolf** [comment] 2015-03-03 23:47
Looked into how we could fix this.  [Looks like this is a common issue for templates](http://stackoverflow.com/questions/3882764/issue-with-visual-studio-template-directory-creation).  I would need to defer the project create logic to our own wizard, which would call the DTE apis directly.  Not hard, but not as easy as checking a box.

**Comment by davkean** [comment] 2015-10-21 06:26
Untagging, removing the milestone so that this goes through triage.

**Comment by srivatsn** [comment] 2015-10-21 17:11
In order to provide options to configure the location of tests and to provide the option to skip generating the test projects and to get the opportunity to name the test project, we would need a wizard. That's a feature and not a bug. Moving this to the backlog.

**Comment by jmarolf** [comment] 2017-12-15 12:31
Issue moved to [dotnet/roslyn-sdk #74](https://github.com/dotnet/roslyn-sdk/issues/74) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jmarolf** 2017-12-15 12:31 UTC
Labels: Area-Analyzers, Feature Request
