### ISSUE TITLE
Identified as a template, resulting in the completion of the list is not human

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42727] opened 2020-03-24 17:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/957607/identified-as-a-template-resulting-in-the-completi-8.html)._

---
Example:
using System.Collections.Generic;
using System.Linq;
...
void Func(){
  List<int> list = new List<int>();
  int max = 127;
  int n = list. Count < m//HERE
}
...

When you enter the tag HERE, you will find that IDE identify this as requiring a type as a template, but I may not actually want to.
Maybe this is what I want: int n = list. Count < max ? list.Count : max;
As you know, an Count<TSource>() method is automatically extended after Linq assembly is included. So, the comlete list (the word in Chinese is "完成列表") will not give me what I want.

So I would like to propose some improvement programs to improve the efficiency of work:
1. A case should be identified and a complete complete list given.
2. Then, in the example above, when I enter a a, at the HERE or when there is no recommended result to complete the list, I should try searching for the result in a complete complete list.
3. To identify this situation, when both '<' and '>' are present, the type that can be used for the template is recommended; when only '<' are present, a complete complete list is given.

Please, try to make it, thanks!
Expect Visual Studio to become better!

---
#### Visual Studio Feedback System on 3/23/2020, 03:40 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-03-24 17:17
Dupe of https://github.com/dotnet/roslyn/issues/25572

**Closed by CyrusNajmabadi** 2020-03-24 17:17 UTC
