### ISSUE TITLE
Dialog asking to rename the class has inverted buttons

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39410] opened 2019-10-21 13:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/784920/dialog-asking-to-rename-the-class-has-inverted-but.html)._

---
[regression] [worked-in:not sure the version]
When renaming a source file for a class in any C# project, Visual Studio asks to rename the type name as well.
Attached you can find the picture of the dialog box asking to rename the file.

Dialog text:
&quot;You are renaming a file. Would you also like to perform a rename in this project of all references to the code element 'Class1'?&quot;

If I press Yes, the rename operation is **NOT** done.
If I press No, the type is renamed.
The Yes and No actions are inverted.

Please restore the old, correct behavior

---
#### Visual Studio Feedback System on 10/20/2019, 10:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by raffaeler** [comment] 2019-10-21 13:14
Thanks for moving it here. I am never sure whether is better to post directly here or on the devcommunity website...

**Comment by sharwell** [comment] 2019-10-21 13:18
@raffaeler Either way works. It's much easier to move an issue from developer community to GitHub (when necessary) than the other way around, but the downside is occasionally an issue won't get triaged to the right team. For a performance-related issue, you definitely want to start with developer community.

**Comment by raffaeler** [comment] 2019-10-21 13:21
Thanks Sam, I was pretty sure it was a "UI" problem since the button handlers are just swapped.
I always believed this repo was only dealing with "compiler as a service" and not the UI stuff.

**Comment by ryzngard** [comment] 2019-10-21 19:58
Confirmed repro on 16.4P2. 

This is one of those weird areas where we don't actually own the UI. I'm going to reopen the feedback and triage to the correct team to let them handle it. Apologies about the bouncing back and forth @raffaeler 

cc/ @jmarolf @davkean

**Closed by ryzngard** 2019-10-21 19:58 UTC
Labels: Area-IDE, Bug

**Comment by sharwell** [comment] 2019-10-21 19:59
Obviously even we sometimes have trouble figuring out where things go 😆

**Comment by raffaeler** [comment] 2019-10-21 20:02
@sharwell At least, this times, it makes sense to me :)

**Comment by davkean** [comment] 2019-10-21 22:24
This has been fixed in recent builds.
