### ISSUE TITLE
Roslyn formatter should offer an option to enforce a maximum number of columns per line

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#47158] opened 2020-08-26 18:56 UTC
One feature I am missing in Visual Studio is being able to automatically enforce a maximum line length. That is, if a line of code is too long, it automatically gets broken up into multiple lines. I often find myself writing very long lines of code (up to 200 columns). However, I don't want to have to think about arranging and breaking up the code. This bad habit is enforced through very large monitors.

TL/DR: Please add support similar to clang-format options like `ColumnLimit` and the `Align*` and `BreakBefore*` group of options. (see https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
The reason I don't want to use clang-format is because it does not support all C# language features (for example LINQ clauses are not arranged nicely).

Example 1)

Parameter lists/declarations should automatically be split into multiple lines and indented/aligned properly.

Before clang-format:
![image](https://user-images.githubusercontent.com/344204/91343464-e4764900-e7dc-11ea-9d0b-5ae859523503.png)

After clang-format:
![image](https://user-images.githubusercontent.com/344204/91343501-efc97480-e7dc-11ea-9278-23e0bd14cc75.png)

Example 2)

Expressions, conditions and comments should be split into multiple lines and indented/aligned properly.

Before clang-format:
![image](https://user-images.githubusercontent.com/344204/91344118-cbba6300-e7dd-11ea-8a0c-a10b138aedc4.png)

After clang-format:
![image](https://user-images.githubusercontent.com/344204/91344266-03c1a600-e7de-11ea-99db-0cb4f420cbd7.png)

**Comment by sharwell** [comment] 2020-08-26 19:03
I've seen many implementations of this feature for many languages, with many different sets of options and behaviors. Across them, there has only been one universal constant: the result of using the feature is always worse than just turning it off. While I believe it is possible to implement a line-break feature that works well, finding a novel implementation to produce this result in practice is going to be a massive undertaking.

**Comment by sharwell** [comment] 2020-08-26 19:07
Note that the use of tabs for indentation and spaces for alignment is not currently supported by the Roslyn formatter, but is covered by https://github.com/dotnet/roslyn/issues/24031#issuecomment-444067640.

**Comment by jmarolf** [comment] 2020-08-27 04:46
related to https://github.com/dotnet/roslyn/issues/15406 and https://github.com/dotnet/format/issues/246

**Comment by jmarolf** [comment] 2020-08-27 05:08
So enforcing a _hard limit_ on line length is not actually possible in the language due to:

- existing indentation rules: what if the user is 20 levels of indentation deep and therefore goes over the desired column width? Basically anywhere enforcing a column limit would violate another style rule we would need to decide who take precedence
- literals (especially string literals): while we could attempt to split string literals that exceed the column width it seems that this could potentially be re-writing the users code more than they intend

Here is a simple (and incomplete) proposal:

- syntax
  - If an expression exceeds the column width the entire expression should be re-flowed for consistency
  - re-flowing syntax to the next line should (in general) increase the indentation by one
  - member access expressions
    - should not increase indentation as long as they are part of the same set of member access expressions
  - lambda and delegate expressions
    - should increment the indentation again and be put on a new line only if the column length is exceeded. Otherwise they should be considered a part of the member access expression
  - parameter lists
    - we have several schemes of wrapping parameter lists. if none are specified as preferred by the user in their editorconfig we should set one as the default.
- trivia
  - multi-line comments: This is the easy case they can be moved anywhere, use normal wrapping rules
    - Remove all new lines in multi-line comment
    - Find the closest word the the column limit and insert a new line
    - reflow comment to current indentation level
    - repeat for new line
  - single line comments: I would just punt these in the initial implementation. The only other option would be attempting to convert them to multiline comments as described above which would likely be changing more than the user wants.

**Comment by sharwell** [comment] 2020-08-27 05:20
@jmarolf I thought there was a duplicate but I couldn't find it. Can you copy your proposal to #15406?

**Comment by sharwell** [comment] 2020-08-27 05:20
Duplicate of #15406

**Closed by sharwell** 2020-08-27 05:20 UTC
Labels: Area-IDE, Feature Request, IDE-Formatter, Need Design Review

**Comment by siegfriedpammer** [comment] 2020-08-27 05:21
> So enforcing a _hard limit_ on line length is not actually possible in the language due to:
> 
> * existing indentation rules: what if the user is 20 levels of indentation deep and therefore goes over the desired column width? Basically anywhere enforcing a column limit would violate another style rule we would need to decide who take precedence
> * literals (especially string literals): while we could attempt to split string literals that exceed the column width it seems that this could potentially be re-writing the users code more than they intend

For me, there is no need to modify single tokens/literals. If a single token + indentation exceeds the column limit, I would expect the formatter to break after that token. The only exception would be semicolons, these should be kept on the same line as the last token.

I like your proposal a lot. Thank you!
