### ISSUE TITLE
Inaccurate IDE0051 Messages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40956] opened 2020-01-14 18:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/875313/inaccurate-ide0051-messages.html)._

---
Using this code:
https://github.com/DragonSpark/Framework/blob/5a9801baf55beb255d11068fe0c4237fe88f59ac/DragonSpark.Application.Hosting.Server.Testing.Application/HelloWorldControllerTests.cs

IDE0051 messages occur that state the methods in the class are not used, when in fact, they are.

https://i.imgur.com/LrENm63.png

---
#### Visual Studio Feedback System on 1/5/2020, 11:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/13/2020, 11:24 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-01-14 20:51
Duplicate of #37050

**Closed by sharwell** 2020-01-14 20:51 UTC
Labels: Area-IDE, Bug, help wanted
