### ISSUE TITLE
`AssemblyLoading_DependencyInDifferentDirectory_Delete` fails locally

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#61451] opened 2022-05-22 15:06 UTC
```
Assert.Equal() Failure
               ↓ (pos 5)
Expected: Delta.2: Gamma: Test G\r\n
Actual:   Delta: Gamma: Test G\r\n
               ↑ (pos 5)

Stack trace:
   at Microsoft.CodeAnalysis.UnitTests.ShadowCopyAnalyzerAssemblyLoaderTests.AssemblyLoading_DependencyInDifferentDirectory_Delete() in C:\Users\PC\Desktop\Roslyn\src\Compilers\Core\CodeAnalysisTest\ShadowCopyAnalyzerAssemblyLoaderTests.cs:line 142
```

I ran tests using `./build.cmd -testCompilerOnly -testCoreClr`

**Comment by jcouv** [comment] 2022-05-24 17:49
Relates to https://github.com/dotnet/roslyn/issues/60766

**Comment by RikkiGibson** [comment] 2022-05-25 19:21
Can repro. Weird that this is only happening locally.

**Comment by RikkiGibson** [comment] 2022-05-25 19:23
It feels like there's some kind of "test rot" happening with local coreclr tests. Things keep diverging. In the past we saw breaking changes in string comparison surface locally but not in CI. Is something wrong with our CI configuration that's causing things to run in a different way than we expect?

**Comment by jcouv** [comment] 2022-06-21 19:38
@Youssef1313 I suspect the problem is that the test runs on a different version of the runtime when running in CI than when running locally. We're discussing how to log this information (runtime version used) to confirm.

**Comment by jaredpar** [comment] 2023-07-10 16:53
Closing as this should not be happening after the re-vamp of the assembly loading tests. Please let me know if this continues.

**Closed by jaredpar** 2023-07-10 16:53 UTC
Labels: Bug, Area-Compilers, Test
