### ISSUE TITLE
Intellisense incorrectly work in C# lambda excpressions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32481] opened 2019-01-15 16:49 UTC
If you quickly type the text inside lambda function, the Intellisense shows wrong suggestions.

Please see the video from the link below:

http://take.ms/plpka

Let me know if you need additional details.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/394868/intellisense-incorrectly-work-in-c-lambda-excpress.html
VSTS ticketId: 737177_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by AndrewAdov** [comment] 2020-09-04 09:31
It looks like on the latest Version 16.8.0 Preview 2.1 problem is not reproduced anymore. I think the issue can be closed.

**Comment by CyrusNajmabadi** [comment] 2020-09-04 20:05
Closing out as the original reporter says this is no longer an issue.  Unfortunately, the video is missing, so i cannot validate the original case myself.

**Comment by CyrusNajmabadi** [comment] 2020-09-04 20:06
Thanks for the info @AndrewAdov

**Closed by CyrusNajmabadi** 2020-09-04 20:05 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
