### ISSUE TITLE
Visual Studio Auto Complete Error with Collection Expressions

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#72872] opened 2024-04-04 10:25 UTC
**Version Used**: 
17.9.4

**Steps to Reproduce**:

1.  Use this code:
```
using System.Collections.Immutable;

namespace ConsoleApp15 {

    public record Parent {
        public ImmutableArray<Child>? Children { get; init; }
    }

    public record Child {
        public string? Id { get; init; }
    }

    
    internal class Program {

        public string ProgramProp { get; set; }

        void Main(string[] args) {


            var V1 = new Parent() {
                Children = [
                    new(){
                        //Put cursor HERE and press Control+Space
                    },
                ],
            };

        }
    }
}
```

2.  Place your cursor inside the ```new() {  }``` code.
3. Press Control+Space
4. You'll notice that the suggested properties are coming from Program not from Child.

Here's a screen shot:

![image](https://github.com/dotnet/roslyn/assets/13609558/d4bfb8a2-58fe-49d0-a48a-64ffb41eac1c)

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:
N/A

**Expected Behavior**:
The member list from Child is shown.

**Actual Behavior**:
The member list from Parent is shown.

**Comment by Rekkonnect** [comment] 2024-04-05 00:33
Didn't #72400 cover this?

**Comment by CyrusNajmabadi** [comment] 2024-04-05 00:38
Don't know, did it @Rekkonnect  ? :)

**Comment by Rekkonnect** [comment] 2024-04-05 00:41
My issue was specifically about arrays, not any type taking advantage of immutable arrays. And the PR closing that issue only added a unit test on which you commented that the test could be broken by passing while not behaving as intended.

Pretty weird stuff

**Comment by CyrusNajmabadi** [comment] 2024-04-05 00:53
>  that the test could be broken by passing while not behaving as intended.

Right.  My preference is that these test files be considered legacy, and new tests be in a different location. That doesn't mean the test doesn't work, just that it's not as guaranteed a test as those using the new harness.

**Comment by CyrusNajmabadi** [comment] 2024-04-05 00:53
> Pretty weird stuff

?  Not sure what's weird :)

**Comment by Rekkonnect** [comment] 2024-04-05 11:08
I dug some more and this appears to be specific to `ImmutableArray<T>`, and probably types exposing their custom collection builder implementation. On arrays, `List<T>`, `HashSet<T>` and `SortedSet<T>`, the suggestions appear correctly in 17.9.5.

**Comment by Rekkonnect** [comment] 2024-04-06 01:03
This issue is a byproduct of the compiler not providing enough information about the bound element type of the collection expression when the semantic model is queried about the type info for the constructor node.

See the above closed PR for notes and the necessary workaround to retrieve the element type.

Maybe open a separate issue to specifically show the bug on the results of `GetTypeInfo` on `SemanticModel`?

**Closed** 2024-09-26 20:34 UTC
Labels: Bug, help wanted, Area-IDE

**Comment by TonyValenti** [comment] 2024-09-26 20:41
Thanks to everyone who got this fixed!
