### ISSUE TITLE
VS 2022 : saving 'Code Style' option is not correct

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58608] opened 2022-01-04 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-:-saving-Code-Style-option-is-/1605394)._

---
[severity:It's more difficult to complete my work]
When I save the options-screen after I have changed eg. 'Text Editor'-'C#'-'Code Style'-'General'-<qualify this access with this> to 'warning' and I reopen the option screen it shows the correct changed value.
But if I close th options-screen and reopen it again it comes back with the original value.

And I think if you change other settings in the same session as you have changed the 'Code Style'-'General' they will also be reset.

Stumbled upon it after my 'Spacing'-settings where not correct after I have made my changes.

(see included recording in Attached Files)

---
#### Feedback Bot on 12/6/2021, 06:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/8/2021, 09:34 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:56
duplicate of https://github.com/dotnet/roslyn/issues/54556

**Closed by jmarolf** 2022-03-18 21:56 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - Editor Config UI
