### ISSUE TITLE
char constant in Linq Queryable expression is converted to int

### ISSUE THREAD

**Issue by ayende** [dotnet/roslyn#58886] opened 2022-01-16 12:03 UTC
**Version Used**: 

C# 9.0

**Steps to Reproduce**:

The following code ( https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0BhA9gG2wUwGMAXAS0wDsBnAblgWQgBZa4kVUAZE8gRxboDMyMInSIA3rETTEUmSCHhEASSJ4AthORCCACwCGAJ0QA1fdmqIAvnOm3tKgIoBXPIYCe+gEb4APKo0APkQAWQAKZRc3Tx88fzV1YJIEygBKCXsZZAB2RGSNSlQAdV03PDCADwBeQIrUM2xEKqrEAHIvVtSWLJsYKyA= )

```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public class C {
    
    public class Item { public char Val; }
    
    public IQueryable<Item> M(IQueryable<Item> items) {
        return items.Where(x=>x.Val == 'b');
    }
}
```

**Expected Behavior** vs **Actual Behavior**:

The constant value should be using `char` and the value `'b'`, but is it using `int` and the value 98.

Here is the output of the compiler:

```
    public IQueryable<Item> M(IQueryable<Item> items)
    {
        ParameterExpression parameterExpression = Expression.Parameter(typeof(Item), "x");
        BinaryExpression body = Expression.Equal(Expression.Convert(Expression.Field(parameterExpression, FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/)), typeof(int)), Expression.Constant(98, typeof(int)));
        ParameterExpression[] array = new ParameterExpression[1];
        array[0] = parameterExpression;
        return Queryable.Where(items, Expression.Lambda<Func<Item, bool>>(body, array));
    }
```

That means that we can't detect the constant value properly in queries, see also: https://github.com/ravendb/ravendb/issues/13473

**Comment by Youssef1313** [comment] 2022-01-16 13:56
Similar to https://github.com/dotnet/roslyn/issues/29396, which was closed as "by design".

**Comment by jcouv** [comment] 2022-02-17 01:54
Closing as duplicate of https://github.com/dotnet/roslyn/issues/29396 (thanks @Youssef1313 for spotting)

**Closed by jcouv** 2022-02-17 01:54 UTC
Labels: Area-Compilers, untriaged
