### ISSUE TITLE
Proposal: ??= operator

### ISSUE THREAD

**Issue by manixrock** [dotnet/roslyn#8894] opened 2016-02-18 22:04 UTC
Null-coalescing assignment operator, or fallback operator.

Allows this:

```
myNullableVariable = myNullableVariable ?? c;
```

To be re-written as this:

```
myNullableVariable ??= c;
```

It would be quite useful for lazy-initialized properties:

```
Person LoveMatch => mLoveMatchCache ?? mLoveMatchCache = Suitors.First(s => ComplexMatchingAlgorithm(s));
private Person mLoveMatchCache;
```

To become easier to write and understand:

```
Person LoveMatch => mLoveMatchCache ??= Suitors.First(s => ComplexMatchingAlgorithm(s));
private Person mLoveMatchCache;
```

It would also allow for variable fallbacks:

```
Person FindMatch(Person person, IEnumerable<Person> friends = null) {
    friends ??= FindFriends(person);
    // ...
}
```

It would work mush like the other assignment operators. Of course, the right-hand side of the operation would only be executed if the left-hand side is null.

**Comment by HaloFour** [comment] 2016-02-18 22:51
Dupe of (already closed as wont-fix) #205

**Closed** 2016-02-26 09:54 UTC
Labels: Area-Language Design
