### ISSUE TITLE
Link docs to Visual Studio Error List panel

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [dotnet/roslyn#49734] opened 2020-12-02 05:30 UTC
Compiler errors should have links on Error List to this page directly instead of searching on bing and redirecting the searched pages' list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca54606-498a-322e-299b-65da435baaaa
* Version Independent ID: 5994ce99-309e-0f0e-78db-1d3b23435feb
* Content: [Compiler Error CS0563](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0563)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0563.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0563.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2020-12-02 18:31
Wasn't this fixed?

**Comment by sharwell** [comment] 2020-12-09 19:35
Duplicate of #46829

**Closed by sharwell** 2020-12-09 19:35 UTC
Labels: Area-IDE
