### ISSUE TITLE
Index From End Operator Causing Error MSB6006 "csc.exe" exited with code -2146232797

### ISSUE THREAD

**Issue by StruanT** [dotnet/roslyn#39861] opened 2019-11-18 05:17 UTC
VS2019 Version 16.3.9.
Console App targeting .NET Core 3.0

> MSB6006 "csc.exe" exited with code -2146232797

When trying to build this...

```
using System;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        IList<int> list = new int[1];
        list[^1] = list[^1] + 1; //<-This line works fine
        list[^1] += 1; //<-Errors During Build 
    }
}
```

**Comment by svick** [comment] 2019-11-18 10:35
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/37789, which should be fixed in VS 16.4, which is currently in preview. Can you try using VS preview, to see if your issue is indeed fixed?

**Closed** 2020-06-26 07:42 UTC
Labels: Area-Compilers, Bug, Resolution-Duplicate
