### ISSUE TITLE
It looks like some of the OrganizeImports tests are either flaky, or culture dependent when executed on CoreClr

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#58867] opened 2022-01-14 18:49 UTC
```
✘ Microsoft.CodeAnalysis.VisualBasic.Workspaces.UnitTests.OrganizeImports.OrganizeImportsTests.TestCaseSensitivity
Error:
Assert.Equal() Failure
                                   ↓ (pos 334)
Expected: ···Imports CC\r\nImports ア\r\nImports ｱ\r\nImports あ\r\nImports アア\r\nImpo···
Actual:   ···Imports CC\r\nImports あ\r\nImports ｱ\r\nImports ああ\r\nImports あｱ\r\nImp···
                                   ↑ (pos 334)

✘ Microsoft.CodeAnalysis.VisualBasic.Workspaces.UnitTests.OrganizeImports.OrganizeImportsTests.TestCaseSensitivity
Error:
Assert.Equal() Failure
                  ↓ (pos 8)
Expected: Imports ア\r\nImports ｱ\r\nImports あ\r\nImports アア\r\nImpo···
Actual:   Imports あ\r\nImports ｱ\r\nImports ああ\r\nImports あｱ\r\nImp···
                  ↑ (pos 8)

 Microsoft.CodeAnalysis.CSharp.Workspaces.UnitTests.OrganizeImports.OrganizeUsingsTests.CaseSensitivity26ms
Error:
Assert.Equal() Failure
                ↓ (pos 6)
Expected: using ア;\r\nusing ｱ;\r\nusing あ;\r\nusing アア;\r\nusing ···
Actual:   using あ;\r\nusing ｱ;\r\nusing ああ;\r\nusing あｱ;\r\nusing···
                ↑ (pos 6)

✘ Microsoft.CodeAnalysis.CSharp.Workspaces.UnitTests.OrganizeImports.OrganizeUsingsTests.CaseSensitivity17ms
Error:
Assert.Equal() Failure
                                     ↓ (pos 305)
Expected: ···;\r\nusing CC;\r\nusing ア;\r\nusing ｱ;\r\nusing あ;\r\nusing アア;\r\nusing ···
Actual:   ···;\r\nusing CC;\r\nusing あ;\r\nusing ｱ;\r\nusing ああ;\r\nusing あｱ;\r\nusing···
                                     ↑ (pos 305)

```

**Comment by RikkiGibson** [comment] 2022-01-14 22:17
@jaredpar could this be related to changes to string comparison in core?

**Comment by AlekseyTs** [comment] 2022-01-14 22:47
> could this be related to changes to string comparison in core?

Everything is possible, but I think a culture dependency is more likely. The base line is captured for some specific culture, but the test doesn't make sure that the culture is always current.

**Comment by Youssef1313** [comment] 2022-01-15 05:29
Duplicate of https://github.com/dotnet/roslyn/issues/58834

**Closed** 2022-01-20 00:40 UTC
Labels: Area-IDE, Test, untriaged
