### ISSUE TITLE
Adding semicolon at end of generic statement in Razor within @{...} can result in a broken experience

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#34088] opened 2019-03-13 22:06 UTC
this is port of vso issue filed
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/819598/

...

![image](https://user-images.githubusercontent.com/1333179/54317826-88e0dd00-45a1-11e9-9f7e-39bfa768d12f.png)

Steps to reproduce:
https://i.imgur.com/vOJ39F4.gifv

This also ends up being an issue in C# but of course less common given the presence of XML tags:
https://i.imgur.com/yceCKxG.gifv

**Comment by heejaechang** [comment] 2019-03-13 22:06
tagging @chborl @sharwell @jinujoseph

**Comment by heejaechang** [comment] 2019-03-13 22:08
I believe some part of it is addressed by @chborl - https://github.com/dotnet/roslyn/commit/88a9e235d75a18ed94eb215162aa665f91ae67ff

**Comment by jinujoseph** [comment] 2019-03-15 01:08
adding notes from taylor 
![image](https://user-images.githubusercontent.com/12449387/54401262-33313100-4684-11e9-90b0-77b4b1d7dae9.png)

**Comment by chborl** [comment] 2019-03-15 21:32
The first issue is a duplicate of https://github.com/dotnet/roslyn/issues/33851 and is fixed in #33883

The second issue has a different cause, so I opened https://github.com/dotnet/roslyn/issues/34176 to track it.  

Closing this issue, please see other issues for further info.

**Closed** 2019-03-25 19:28 UTC
Labels: Area-IDE, Bug, Need Design Review
