### ISSUE TITLE
VS crashes when inlining temporary variable

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#2593] opened 2015-05-08 01:57 UTC
When using "Inline temporary variable" in VB, the following exception is thrown, crashing VS.

This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.

StackTrace "   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<InitializeFlavored>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<Initialize>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.<OnMenuItemGotKeyboardFocus>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)"	string

Dump available at:

\\marolf-server\public\Dumps\inline_crash.dmp

**Comment by Pilchie** [comment] 2015-05-08 18:08
Tag @shyamnamboodiripad. Can you take a look at this?  Does it look like the Roslyn lightbulb code, or the editor?

**Comment by shyamnamboodiripad** [comment] 2015-05-08 18:36
@Pilchie, @jmarolf this looks like a dupe of internal TFS bug 1166482 that I fixed via PR #2591 yesterday. This was a crash that was being caused because we were returning uninitialized ```ImmutableArray<SuggestedActionSet>``` to the platform's light bulb code in cases where our light bulb provider handled exceptions thrown from a Roslyn code fix / refactoring.

This crash should be fixed now. However, the underlying issue that causes Inline Rename to throw needs to be fixed. Otherwise we will display an info bar and trigger non fatal Watson for this and disable the Inline Rename fix for the remainder of the user's session...

**Comment by Pilchie** [comment] 2015-05-08 19:30
Can you take a look at the inline rename exception?

**Comment by dpoeschl** [comment] 2015-05-08 19:42
@Pilchie It was a typo by @shyamnamboodiripad that he's now fixed. The error is in Inline Temp, not Inline Rename. Removing assignment & milestone for triage.

**Comment by Pilchie** [comment] 2015-05-08 19:43
In that case, can *you* take a look @balajikris?

**Comment by balajikris** [comment] 2015-05-08 19:45
:grin: sure

**Comment by balajikris** [comment] 2015-05-08 21:49
@jmarolf - do you have a repro for this? There is nothing in the dump that points to the exception thrown by InlineTemp. The only exception i see is the ImmutableArray thing which @shyamnamboodiripad  fixed.  none of the stackframes have anything interesting or to do with inline temp.  without a repro, i'm afraid this isn't actionable.

**Comment by Pilchie** [comment] 2015-05-08 22:04
I found this exception in the dump:

```
0:000> !pe 721cb610 
Exception object: 721cb610
Exception type:   System.NullReferenceException
Message:          Object reference not set to an instance of an object.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    0FCCE01C 22C5947A Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.RewriteExtensionMethodInvocation(Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.SymbolDisplayFormat)+0xc2
    0FCCE0F4 22C592BA Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.RewriteExtensionMethodInvocation(Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax, Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.IMethodSymbol)+0x42
    0FCCE128 22C58ED9 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.VisitInvocationExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax)+0x2d1
    0FCCE174 413BDB8D Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[[System.__Canon, mscorlib]](Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1<System.__Canon>)+0xd
    0FCCE180 4146D32A Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1[[System.__Canon, mscorlib]].Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x52
    0FCCE190 22C57827 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x27
    0FCCE1A0 46291C64 Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMemberAccessExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax)+0x3c
    0FCCE1E4 22C589CB Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.VisitMemberAccessExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax)+0x53
    0FCCE25C 2C67753D Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[[System.__Canon, mscorlib]](Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1<System.__Canon>)+0xd
    0FCCE268 4146D32A Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1[[System.__Canon, mscorlib]].Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x52
    0FCCE278 22C57827 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x27
    0FCCE288 46291C64 Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMemberAccessExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax)+0x3c
    0FCCE2CC 22C589CB Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.VisitMemberAccessExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax)+0x53
    0FCCE344 2C67753D Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[[System.__Canon, mscorlib]](Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1<System.__Canon>)+0xd
    0FCCE350 4146D32A Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1[[System.__Canon, mscorlib]].Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x52
    0FCCE360 22C57827 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x27
    0FCCE370 46298998 Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitConditionalAccessExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.ConditionalAccessExpressionSyntax)+0xf0
    0FCCE3B4 2C677A98 Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.Syntax.ConditionalAccessExpressionSyntax.Accept[[System.__Canon, mscorlib]](Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1<System.__Canon>)+0x10
    0FCCE3C0 4146D32A Microsoft_CodeAnalysis_VisualBasic!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1[[System.__Canon, mscorlib]].Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x52
    0FCCE3D0 22C57827 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService+Expander.Visit(Microsoft.CodeAnalysis.SyntaxNode)+0x27
    0FCCE3E0 22C57777 Microsoft_CodeAnalysis_VisualBasic_Workspaces!Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expand(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxAnnotation, System.Func`2<Microsoft.CodeAnalysis.SyntaxNode,Boolean>, Boolean, System.Threading.CancellationToken)+0x107
    0FCCE420 22C57217 Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.Simplification.Simplifier.Expand[[System.__Canon, mscorlib]](System.__Canon, Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.Workspace, System.Func`2<Microsoft.CodeAnalysis.SyntaxNode,Boolean>, Boolean, System.Threading.CancellationToken)+0x7f
    0FCCE454 22C570FD Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.Simplification.Simplifier+<ExpandAsync>d__2`1[[System.__Canon, mscorlib]].MoveNext()+0x155
    0FCCE554 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCE564 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCE570 5B04857A mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)+0x1a
    0FCCE574 22C565AA Microsoft_CodeAnalysis_VisualBasic_Features!Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider+VB$StateMachine_18_CreateExpressionToInlineAsync.MoveNext()+0x5aa
    0FCCE734 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCE744 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCE750 5B04857A mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)+0x1a
    0FCCE754 22C5229D Microsoft_CodeAnalysis_VisualBasic_Features!Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider+VB$StateMachine_10_InlineTemporaryAsync.MoveNext()+0x4d5
    0FCCEAA4 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCEAB4 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCEAC0 22C5139D Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.CodeActions.CodeAction+<GetChangedSolutionAsync>d__9.MoveNext()+0xe5
    0FCCEB94 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCEBA4 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCEBB0 22C510EA Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.CodeActions.CodeAction+<ComputeOperationsAsync>d__7.MoveNext()+0xe2
    0FCCEC88 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCEC98 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCECA4 22C50C25 Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.CodeActions.CodeAction+<ComputePreviewOperationsAsync>d__8.MoveNext()+0xe5
    0FCCED78 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCED88 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCED94 22C505FA Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.CodeActions.CodeAction+<GetPreviewOperationsAsync>d__6.MoveNext()+0xea
    0FCCEE94 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0FCCEEA4 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0FCCEEB0 4136FE06 Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction+<>c__DisplayClass10_0+<<GetPreviewOperationsAsync>b__0>d.MoveNext()+0xee
    0083ECE8 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0083ECF8 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0083ED04 4136F1AB Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction+<GetPreviewResultAsync>d__14.MoveNext()+0x123
    0083ECD0 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    0083ECE0 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    0083ECEC 4136EDB1 Microsoft_CodeAnalysis_EditorFeatures!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction+<>c__DisplayClass17_0+<<GetPreviewAsync>b__0>d.MoveNext()+0xf1
    1D39EB3C 5B048619 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x5d
    1D39EB4C 5B0485B7 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    1D39EB58 4136EA9D Microsoft_CodeAnalysis_Workspaces!Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions+<PerformFunctionAsync>d__3`1[[System.__Canon, mscorlib]].MoveNext()+0x125
```

**Comment by balajikris** [comment] 2015-05-08 22:07
@Pilchie - thanks :astonished: How did you manage that? I tried `!dumpheap -type System.Exception` and there _tons_ of them that i'd never parse through them all.

**Comment by Pilchie** [comment] 2015-05-08 22:12
I parsed through them :smile:

**Comment by Pilchie** [comment] 2015-05-08 22:13
though I actually just did `!dumpheap -stat`, then `findstr /v Exception`, then removed the things that were arrays and generics manually in vim.

**Comment by balajikris** [comment] 2015-05-08 22:28
Thanks, looking. That wasn't as bad as the one I tried..

**Comment by balajikris** [comment] 2015-05-11 17:05
Found a repro:
```VB
Imports System.Runtime.CompilerServices

Module M
    <Extension()>
    Public Function Something(cust As C) As IEnumerable(Of String)
        Throw New NotImplementedException()
    End Function
End Module

Class C
    Private Function GetAssemblyIdentity(types As IEnumerable(Of C)) As Object
        For Each t In types
            Dim $$assembly = t?.Something().First()
            Dim identity = assembly?.ToArray()
        Next
        Return Nothing
    End Function
End Class
```

**Comment by balajikris** [comment] 2015-05-26 20:47
The underlying problem is that `RewriteExtensionMethodInvocation` does not handle conditional access expressions. obj.Something() vs obj?.Something(). After that's addressed, we may (not likely though) still need to do some work to make InlineTemp here, but we need expand/reduce working correctly here. sending over to the diagnostics team to have a look.

**Comment by balajikris** [comment] 2015-05-26 20:49
tagging @srivatsn @mavasani for triage/inputs.

**Comment by mavasani** [comment] 2015-06-04 18:38
Fixed with https://github.com/dotnet/roslyn/commit/b770795f046fa7c8561b1a57a447f754a17c2a0d

**Comment by mavasani** [comment] 2015-06-04 18:39
Assigning to @tmeschter to verify close this issue, as he has already buddy tested this fix.

**Closed by mavasani** 2015-06-04 18:38 UTC
Labels: Area-Analyzers, Bug

**Comment by tmeschter** [comment] 2015-06-15 20:15
Verified that the repro provided by @balajikris works as I would expect it to, and results in no exceptions.
