### ISSUE TITLE
How to install Microsoft.CodeAnalysis.CSharp in .NET Core, Microsoft.Composition is still a problem !!!

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/roslyn#17775] opened 2017-03-13 08:36 UTC
Hello

Why do we have problem with "Microsoft.Composition" even after upgrade Roslyn to version 2 ?
I think someone should change "Microsoft.Composition" to "System.Composition" for working on .NET Core !!!!!!!

**Install-Package Microsoft.CodeAnalysis.CSharp.Workspaces** needs **System.Composition 1.0.31** for working on .NET Core.

please fix it.

**Comment by Pilchie** [comment] 2017-03-15 18:43
You can fix this by setting [`PackageTargetFallback`](https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#packagetargetfallback) until we get the change to System.Composition done.

In the meantime, this is a duplicate of https://github.com/dotnet/roslyn/issues/16040

**Closed by Pilchie** 2017-03-15 18:43 UTC
Labels: Area-IDE
