### ISSUE TITLE
Roslyn API broke in upgrade from .NET SDK 7.0.302 to 7.0.304

### ISSUE THREAD

**Issue by urikanonov** [dotnet/roslyn#68638] opened 2023-06-15 14:21 UTC
**Version Used**: 
.NET SDK: 7.0.304

Nugets:
- Microsoft.CodeAnalysis.CSharp.Workspaces.4.6.0
- Microsoft.CodeAnalysis.Workspaces.MSBuild.4.6.0
- Microsoft.Build.Locator.1.5.5

**Steps to Reproduce**:

1. Unpack the zip: [RoslynIssueRepro.zip](https://github.com/dotnet/roslyn/files/11758698/RoslynIssueRepro.zip)
2. Open RoslynIssueRepro.sln
3. Run Runner/Program.cs and see that it succeeds without errors
4. Run the UnitTest called "Test" under UnitTests/SanityTest.cs and see that it fails with a compilation eror

**Expected Behavior**:
For the UnitTest that runs the same code as "Runner" to succeed.
This *worked* in .NET SDK 7.0.302 but **broke after updating to .NET SDK 7.0.304**

**Actual Behavior**:

Test method UnitTests.SanityTest.Test threw exception: 
System.Exception: Failed loading project. ToAnalyze (C:\XXX\RoslynIssueRepro\ToAnalyze\ToAnalyze.csproj - (ProjectId, #e87e3af8-a2c1-4fa3-a7b2-7f9dfca37580 - C:\XXX\RoslynIssueRepro\ToAnalyze\ToAnalyze.csproj)).
ReferencedAssemblyNames (0):
  
MetadataReferences (0):
  
AnalyzerReferences (2):
  Microsoft.CodeAnalysis.CSharp.NetAnalyzers
  Microsoft.CodeAnalysis.NetAnalyzers
AllProjectReferences (0):
  
Errors (7):
  C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(3,18): error CS0518: Predefined type 'System.Object' is not defined or imported
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(5,23): error CS0518: Predefined type 'System.Object' is not defined or imported
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(7,24): error CS0518: Predefined type 'System.Object' is not defined or imported
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(7,24): error CS0246: The type or namespace name 'Dictionary<,>' could not be found (are you missing a using directive or an assembly reference?)
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(7,35): error CS0518: Predefined type 'System.String' is not defined or imported
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(7,43): error CS0518: Predefined type 'System.Int32' is not defined or imported
 C:\XXX\RoslynIssueRepro\ToAnalyze\TestClass.cs(3,18): error CS1729: 'object' does not contain a constructor that takes 0 arguments
    at Analyzer.SolutionAnalyzer.OpenAsync(String[] projectPaths) in C:\XXX\RoslynIssueRepro\Analyzer\SolutionAnalyzer.cs:line 49
   at Analyzer.SolutionAnalyzer.AnalyzeAsync(String[] projectPaths) in C:\XXX\RoslynIssueRepro\Analyzer\SolutionAnalyzer.cs:line 88
   at UnitTests.SanityTest.Test() in C:\XXX\RoslynIssueRepro\UnitTests\SanityTest.cs:line 27
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

Debug Trace:
Located MSBuild.
Name: .NET Core SDK
DiscoveryType: DotNetSdk
MSBuildPath: C:\Program Files\dotnet\sdk\7.0.304
Version: 7.0.304
VisualStudioRootPath: C:\Program Files\dotnet\sdk\7.0.304
Loading project C:\XXX\RoslynIssueRepro\ToAnalyze\ToAnalyze.csproj
Load progress: Project: ToAnalyze.csproj, Operation: Evaluate, Elapsed: 00:00:00.7270356, Framework: 
Load progress: Project: ToAnalyze.csproj, Operation: Build, Elapsed: 00:00:00.1242794, Framework: 
Load progress: Project: ToAnalyze.csproj, Operation: Resolve, Elapsed: 00:00:00.1486210, Framework: net6.0

**Comment by rainersigwald** [comment] 2023-06-15 18:24
Workaround:

```diff
diff --git a/UnitTests/UnitTests.csproj b/UnitTests/UnitTests.csproj
index 540e3fe..1392909 100644
--- a/UnitTests/UnitTests.csproj
+++ b/UnitTests/UnitTests.csproj
@@ -7,6 +7,7 @@
 
   <ItemGroup>
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.1" />
+    <PackageReference Include="NuGet.Frameworks" Version="6.6.1" />
     <PackageReference Include="MSTest.TestAdapter" Version="1.3.2" />
     <PackageReference Include="MSTest.TestFramework" Version="1.3.2" />
   </ItemGroup>
```

**Comment by sharwell** [comment] 2023-06-16 16:11
Duplicate of https://github.com/microsoft/vstest/issues/3154

**Closed by sharwell** 2023-06-16 16:11 UTC
Labels: Area-Compilers
