### ISSUE TITLE
Getting thousands of naming-style violations with latest VS build

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#35736] opened 2019-05-15 21:41 UTC
I'm seeing this error over basically the entirety of my codebase:

![image](https://user-images.githubusercontent.com/4564579/57811498-419cd700-771f-11e9-8605-3eb740661bae.png)

To get an idea, this is now upwards of tens of thousands of messages:

![image](https://user-images.githubusercontent.com/4564579/57811526-52e5e380-771f-11e9-99d0-823b4060d21f.png)

It effectively makes messages useless and very much clitters up the entire UI since nearly 100% of all our fields in all our projects are marked this way.  

This is def a regression and doesn't match our editorconfig rules (which state that private fields should begin with underscore). 

I'm running:

![image](https://user-images.githubusercontent.com/4564579/57811589-77da5680-771f-11e9-9f8d-348c8087e947.png)

I can provide more details if necessary.  But i really would like this fixed asap.  Thanks!

**Comment by sharwell** [comment] 2019-05-15 22:26
Duplicate of #35488

You even just reviewed the PR to fix this 😆

**Comment by sharwell** [comment] 2019-05-15 22:27
You even just reviewed the PR to fix this 😆

**Closed by sharwell** 2019-05-15 22:26 UTC

**Comment by jasonmalinowski** [comment] 2019-05-15 22:32
@sharwell I requested Cyrus file this, because now we have non-dogfooding customers hitting it. ;-)
