### ISSUE TITLE
Intermittent test failure: Microsoft.CodeAnalysis.Editor.UnitTests.Structure.BlockStructureServiceTests.TestSimpleLambda

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21423] opened 2017-08-10 17:01 UTC
```
MESSAGE:
System.IndexOutOfRangeException : Index was outside the bounds of the array.
+++++++++++++++++++
STACK TRACE:
at System.Collections.Generic.List`1.get_Item(Int32 index) 
at System.AggregateException..ctor(String message, IList`1 innerExceptions) 
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Flatten(ICollection`1 exceptions) 
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
at Microsoft.CodeAnalysis.Editor.UnitTests.Structure.BlockStructureServiceTests.<TestSimpleLambda>d__0.MoveNext() in q:\roslyn\src\EditorFeatures\Test\Structure\BlockStructureServiceTests.cs:line 39
 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/8828/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Structure/BlockStructureServiceTests/TestSimpleLambda/

**Comment by Pilchie** [comment] 2017-08-14 17:53
Duplicate of #21388

**Closed by Pilchie** 2017-08-14 17:53 UTC
Labels: Area-IDE, Flaky, Test
