### ISSUE TITLE
Disable live code analysis

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60892] opened 2022-04-21 21:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Disable-live-code-analysis/10009824)._

---
I followed https://docs.microsoft.com/en-us/visualstudio/code-quality/disable-code-analysis?view=vs-2022 because I was lead to believe that Live Code Analysis could be disabled.

Of course the instructions don't apply to .net projects. Only .Net Core (why? it's useless for me as live code analysis)

Then there is half written instructions for .Net at the bottom of that article that assume you ALREADY KNOW HOW TO EDIT MSBUILD. Dude... like what do you expect a user to think?

I can't type 2 characters of a variable without it freaking out about errors. I don't care. I know how to write code. I don't need this [Redacted]. I want it off.

Right now I am writing code in notepad++ and pasting it in. I only needed to use visual studio for one quick project.. Hopefully I won't have to use it again for a long time. This is absolutely miserable.

---
### Original Comments
(no comments)

**Comment by sharwell** [comment] 2022-04-28 18:45
Duplicate of #29123

**Closed by sharwell** 2022-04-28 18:45 UTC
Labels: Area-Analyzers

**Comment by jinujoseph** [comment] 2022-04-28 18:46
cc @mavasani for info

**Comment by sharwell** [comment] 2022-04-28 18:48
Developer mode is our primary tracking issue for a new feature that allows a user to quickly and easily turn off the error presentation and allow focusing on just typing.
