### ISSUE TITLE
Snippet completion is incorrectly offered for member completion list items.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5973] opened 2015-10-14 21:35 UTC
UPDATE: This now tracks the issue reported at https://github.com/dotnet/roslyn/issues/5973#issuecomment-295457046

**Old Issue**

With the cursor at '`$$`' type '`E`':

``` C#
class C
{
    public void Exception()
    {
        new C().$$ // <- cursor is here
    }
}
```

**RESULT:**
The tool tip for the completion item shows:

```
void C.Exception()
Note: Tab twice to insert the 'Exception' snippet.
```

And hitting tab twice inserts the exception snippet, which is not what should happen here.

**EXPECTED:**
The "Tab twice" text shouldn't be displayed nor should the snippet actually insert.

**Comment by Pilchie** [comment] 2015-10-15 16:31
The tab insertion is purely textual (and has been since VS2005), so this is the expected behavior.  The snippet files themselves don't have a way of indicating what syntactic construct they are valid in.

**Comment by Pilchie** [comment] 2017-04-19 21:43
Also reported in https://developercommunity.visualstudio.com/content/problem/27418/tabbing-on-the-exception-symbol-in-a-catch-uses-th.html, with an interesting twist.  This is a case where bracematching could have worked.

@dpoeschl Thoughts on re-ordering command handling of `TAB` between snippet expansion and brace matching navigation?

**Comment by dpoeschl** [comment] 2017-04-19 22:15
It means the "Press Tab twice" thing will be a lie, but if you're in a brace matching session you almost certainly aren't trying to expand a snippet, so I'm fine with it.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 21:16
Closing out given lack of customer feedback.

**Closed by CyrusNajmabadi** 2024-10-18 21:16 UTC
Labels: Bug, help wanted, Area-IDE
