### ISSUE TITLE
C# overrides are defaulting to expressions. Useless! Please revert!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49038] opened 2020-10-29 15:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-overrides-are-defaulting-to-expressio/1230412?preview=true)._

---
When overriding a method from the base class, Visual Studio is inserting useless expression statements that create more work for the user.

```csharp
public override void OnAdded(IScreenObject host) => base. OnAdded(host);
```

That statement is pointless and **must** be changed by a user. If they want to keep the base call, they must convert the expression to a normal code block and add more code. If they want more than one statement, they must convert the expression to a normal code block. The only way this is useful is if the coder is going to use a single line of code. This is a big assumption to make. I don't know why this change was introduced but it's creating a lot of work and it honestly doesn't make sense to me. Properties, sure, methods, no.

---
#### Feedback Bot on 10/23/2020, 00:29 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-10-29 16:20
By default, expression bodied members are _not_ used for methods:

https://github.com/dotnet/roslyn/blob/28b4508467cdc2ad2af7cb2f52c74cc73515a7e8/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L151-L152

For the project in question, the behavior has been overridden by one of the following two options:

### .editorconfig may have been configured

Set `csharp_style_expression_bodied_methods` to **false** to restore the default behavior:

```
# Prefer method-like constructs to have a block body
csharp_style_expression_bodied_methods = false:none
```

### Tools &rarr; Options may have been configured

📝 This only applies if **.editorconfig** has not been configured.

![image](https://user-images.githubusercontent.com/1408396/97602001-0603d480-19c8-11eb-8026-8cc2ca2263ff.png)

**Comment by CyrusNajmabadi** [comment] 2020-10-29 16:21
1. Switching to block-style can be done by just hitting ctrl-dot and asking to convert to a statement form.
2. this is controlled by this option, which is set to 'never' by default.  User has likely changed the default, which impacts these features as they want to emit using the style the user asked for:

![image](https://user-images.githubusercontent.com/4564579/97602077-1ddb5880-19c8-11eb-901d-184a9032c6eb.png)

**Comment by sharwell** [comment] 2020-10-29 16:21
Duplicate of #38514

**Closed by sharwell** 2020-10-29 16:21 UTC
Labels: untriaged
