### ISSUE TITLE
TestGetSyntaxRootAsyncDoesNotKeepRootAlive is flaky

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#14996] opened 2016-11-04 20:44 UTC
Here's the PR that ran into this #14980 
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/5618/

```
Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestGetSyntaxRootAsyncDoesNotKeepRootAlive
      Reference should have been released but was not.
      Expected: False
      Actual:   True
      Stack Trace:
        q:\roslyn\src\Test\Utilities\Desktop\ObjectReference.cs(60,0): at Roslyn.Test.Utilities.ObjectReference`1.AssertReleased()
        q:\roslyn\src\Workspaces\CoreTest\SolutionTests\SolutionTests.cs(951,0): at Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestGetSyntaxRootAsyncDoesNotKeepRootAlive()
```

**Comment by jasonmalinowski** [comment] 2016-11-05 01:06
Duplicate of #13433 but clearly we don't have the test disabled. #15022 to do such disabling.

**Closed by jasonmalinowski** 2016-11-05 01:06 UTC
Labels: Contributor Pain, Flaky
