### ISSUE TITLE
Assertion failed in `SourceEventSymbol.GetAttributesBag`

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#29406] opened 2018-08-20 22:12 UTC
It did not repro locally or in other branches, so I suspect there is a thread-safety issue that causes flakiness.
I don't know the root cause yet. This code is very typically of other `GetAttributesBag` implementations...
I've seen this problem once (in PR https://github.com/dotnet/roslyn/pull/29322), but I don't think it's specific to that PR. 

```C#
        private CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
        {
            if ((_lazyCustomAttributesBag == null || !_lazyCustomAttributesBag.IsSealed) &&
                LoadAndValidateAttributes(OneOrMany.Create(this.AttributeDeclarationSyntaxList), ref _lazyCustomAttributesBag))
            {
                DeclaringCompilation.SymbolDeclaredEvent(this);
                var wasCompletedThisThread = state.NotePartComplete(CompletionPart.Attributes);
                Debug.Assert(wasCompletedThisThread);
            }

            return _lazyCustomAttributesBag;
        }

```

```
14:32:19    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
14:32:19    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributesBag() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs:line 184
14:32:19    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetDecodedWellKnownAttributeData() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs:line 214
14:32:19    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.get_NonNullTypes() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs:line 352
14:32:19    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbolWithAnnotations.get_IsNullable() in /_/src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs:line 293
```

CC @cston @AlekseyTs

**Comment by cston** [comment] 2018-08-20 22:18
Is this a duplicate of https://github.com/dotnet/roslyn/issues/28954?

**Comment by jaredpar** [comment] 2018-09-12 16:47
Confirmed it's a dupe of #28954

**Closed by jaredpar** 2018-09-12 16:47 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
