### ISSUE TITLE
One instance object being able to change another instance object's private property

### ISSUE THREAD

**Issue by akshays2112** [dotnet/roslyn#49390] opened 2020-11-16 06:30 UTC
**Version Used**: 

C# 9 (Possibly prior versions too. Will require more testing.

**Steps to Reproduce**:

1. Run the following C# code in a console project::

```
namespace TestBrokenEncapsulation
{
    public class TestClass1
    {
        string x = "abc";

        public void test(TestClass1 a)
        {
            a.x = "hjk";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            TestClass1 x = new TestClass1();
            TestClass1 y = new TestClass1();
            Console.WriteLine($"Before:: x.x={x.getX()} and y.x={y.getX()}");
            x.test(y);
            Console.WriteLine($"After:: x.x={x.getX()} and y.x={y.getX()}");
        }
    }
}
```
**Expected Behavior**:
Should error out due to encapsulation being broken.

**Actual Behavior**:
Breaks encapsulation.

**Comment by svick** [comment] 2020-11-16 07:24
This behavior is correct according to [the specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#accessibility-domains), so I don't think there's anything to fix here.

As I understand it, encapsulation is not about isolating objects from each other, it's about isolating parts of your program from each other. That way, you can know that only code in this class can use its `private` members, which in turn makes it easier to ensure your code is correct or to refactor it. Preventing access to other instances of the same type wouldn't help with that, but it would make some common patterns harder to express.

**Comment by akshays2112** [comment] 2020-11-16 08:11
Ok given that it is by spec/design. How about giving a special new access modifier that isolates one object instance from corrupting/modifying another object instance of the same class. While many things are the law they might not necessarily be good at all :P.

**Comment by huoyaoyuan** [comment] 2020-11-16 09:03
https://github.com/dotnet/csharplang/discussions/2718

**Comment by akshays2112** [comment] 2020-11-16 09:27
Thank you @huoyaoyuan. Good someone noticed this horrible design problem.

I do not have such problems in my code as I never code like this.

Just wanted to help the others who follow processes and do not understand.

Cheers.

Closing issue.

**Comment by akshays2112** [comment] 2020-11-16 09:51
Upon looking more into dotnet/csharplang#2718 it is different as it is a suggestion. This issue is a design problem/bug. I am not filing as issue dotnet/csharplang#2718 for a design suggestion but as a design bug/problem.

Reopening the issue until senior people close it by themselves.

Cheers. Peace out I have done my good deed. All yours @MadsTorgersen

**Comment by akshays2112** [comment] 2020-11-16 10:10
Also @MadsTorgersen if this goes into the CLR then I am willing to the typing labor of refiling the issue where it belongs.

**Comment by akshays2112** [comment] 2020-11-16 10:19
Also it is not a good idea to bypass property getters and setters in foreign objects which hold different references to resources with code based sanity checks. I can list lots of problems due to this issue.

**Comment by huoyaoyuan** [comment] 2020-11-16 10:29
> it is different as it is a suggestion. This issue is a design problem/bug.

It was an issue. It's converted into discussion because people didn't get agreement.

**This fall in the scope of custom analyzer.** For private members, all the usage must be through source, not metadata. There can be an analyzer finding `[InstancePrivateAttribute]`, and reporting error for misusage.

Per discussion in dotnet/csharplang#2718 , people **don't think this is a big problem in practice**. You can share your thoughts, but don't just say 'it's should be implemented' just based on your opinion.

Finally, don't tag the language designer in such a way. They will take decision based on the discussions in the csharplang repo.

I'd suggest you to go to dotnet/csharplang#2718 , and talk about *what problem you've met without this feature*.

**Comment by akshays2112** [comment] 2020-11-16 13:15
I did not say it should be implemented. I do not make decisions. I pointed out a bug. Again I understand that the community feels and the program manager does to that this does not require fixing which is your decision to make.

I said something should be done about it. Which it seems to be done already that this is a non-issue and will stay this way which is again your decision to make.

Finally why tag a manager or potential decision maker because if there are plans to say push to compete for C# to be used in mission critical systems this could lead to crashes.
A potential hypothetical crash scenario by mistake of course in a say a hypothetical medical (life or death) embedded system that has low resources where one would use unmanaged code.
What if, again hypothetical, said unmanaged code is using a private variable outside its scope or passed in indirectly and that is again hypothetically and accidentally clear or corrupted?

Would you consider such a Use Case as acceptable.

Would you think something should be done about it?

This is all I am saying. What you decided to do is up to you I have no control or say over it all I can do is flag it post it.

I get unsatisfactory answers then I escalate to the manager who can close, delete my request at all.

I am only trying to report a bug/problem issue. I am not part of the team. I am merely a user of C#.

Again I apologize for any and all perceived trouble I have caused which was not my intent at all.

**Comment by huoyaoyuan** [comment] 2020-11-16 14:38
> I pointed out a bug.

There's nothing bug. **`private` was designed to be 'class' not 'instance' since the first version, and so does C++, so does Java.** It just doesn't fit your expectation.

**Comment by CyrusNajmabadi** [comment] 2020-11-16 14:52
Closing out as by design. If you'd like to start a discussion about a way to make this sort of thing impossible, feel free. 

Note: class-based encapsulation is extremely prevalent. This has been how this (and many other languages) have worked since their origin. If you want to make this not allowed, you'll have to work very hard to convince people that this perspective has merit.

**Closed by CyrusNajmabadi** 2020-11-16 14:52 UTC
Labels: Area-Compilers, untriaged

**Comment by CyrusNajmabadi** [comment] 2020-11-16 14:54
> Unlike the dead article from 1 year ago I have supplied simple code that shows the bug problem. 

You show one instance able to mutate another instance of the same type. This does not seem like a problem/bug. Indeed, that's exactly the definition of what private means

**Comment by akshays2112** [comment] 2020-11-16 15:09
Will do. Thanks for the decision and closing it.

**Comment by akshays2112** [comment] 2020-11-18 04:48
If possible, @CyrusNajmabadi, can you please talk to the documentation people and close the original issue I first raised which came about by reading the C# documentation. Asking this since you have authority to close out issues.

I will post that there too. As this issue was addressed differently and not dismissed so there seems to be a communication gap between you and your documentation team.
 
https://github.com/dotnet/docs/issues/20801

**Comment by akshays2112** [comment] 2021-07-14 08:49
In self defense as I am still being discussed in real life whether I have any intelligence and know software and deserve a job at all I did need to mention how this could be used to hack and steal information.

If a hacker can introduce in the manner I explained a class of the same type they can get access to any data held in this manner by any objects of the same type.

Will not supply example code as I do not want to promote this sort of style of questionable intent.

@MadsTorgersen and other team members who need to be aware of this.

**Comment by CyrusNajmabadi** [comment] 2021-07-14 17:07
Types are not a security boundary. If an attacker is running in the same process as you, they can read all this memory no matter what.

**Comment by akshays2112** [comment] 2021-11-30 18:11
Fair enough on the attacker front.

However, people using such kinds of code can accidentally write code which causes problems.

At this point, I am satisfied with the current solution of having the Analyzer check for such a scenario in the code.
