### ISSUE TITLE
I`m having problems using Collection Expressions after the latest update of Visual Studio 2022 Preview 3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71843] opened 2024-01-29 13:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Im-having-problems-using-Collection-Exp/10571684)._

---
[regression] [worked-in:17.9 Preview 3]
After Visual Studio 2022 17.9 Preview 3 I got a problem on my code that is using Collection Expressions.
When I try to load the assemblies of my project it throws an exception in this line:

List<Assembly> assemblies = [.. AppDomain.CurrentDomain.GetAssemblies()];

If I switch to: 

List<Assembly> assemblies = AppDomain.CurrentDomain.GetAssemblies().ToList();
it works just fine.

In Visual Studio 2022 17.9 Preview 2 it works just fine, and Visual Studio 2022 (The normal version works fine too)

---
#### Feedback Bot on 1/28/2024, 08:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by cston** [comment] 2024-01-29 16:25
The exception is `ArrayTypeMismatchException` (see [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwBYBuYsyvAOgCUBTAMwBt2BjBFAD2MekWIAZKAGcEAHgCC06ezDBuATwB85CMtXqo7aeQC85ANrNm5BQAc7AESGRYzAMKpkydjATPXGGYAcXYEJRU1biNpAAoASgBdMSA=)). 

@RikkiGibson, is this a duplicate of https://github.com/dotnet/roslyn/issues/71720?

**Comment by RikkiGibson** [comment] 2024-01-29 18:41
Yes I think so.

**Comment by RikkiGibson** [comment] 2024-01-30 19:15
Duplicate of #71720

**Closed by RikkiGibson** 2024-01-30 19:15 UTC
Labels: Area-IDE, untriaged
