### ISSUE TITLE
Maybe a bug: Inner InvalidProgramException when dealing with `dynamic` and .ToList()

### ISSUE THREAD

**Issue by Daynvheur** [dotnet/roslyn#56372] opened 2021-09-14 09:57 UTC
Hello,

I've run into some gitter chat to solve a conversion question, and playing with it got me a `TargetInvocationException`, having an inner `InvalidProgramException` that seemed valuable to report.
The code that ran into an exception is this one:
```cs
#define activate_linq

using System.Collections;
using System.Collections.Generic;
#if activate_linq
using System.Linq;
#endif

List<short> filtres = new () {4};
var _ = filtres.MyCast<int>()
    #if activate_linq
    .ToList()
    #endif
    ;

public static class CastExtension
{
    public static IEnumerable<TR> MyCast<TR>(this IEnumerable e)
    {
        foreach (dynamic o in e)
        {
            //string d; // <- TargetInvocationException when commented (while activate_linq is defined).
            yield return o;
        }
    }
}
```

When `activate_linq` is defined and there is no operation (other than `yield return`) in the `foreach`, an exception is thrown:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at CastExtension.MyCast[TR](IEnumerable e)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at _Program.<Main>$(String[]_ args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SharpLab.Container.Execution.ExecuteCommandHandler.ExecuteAssembly(Byte[] assemblyBytes) in D:\a\SharpLab\SharpLab\source\Container\Execution\ExecuteCommandHandler.cs:line 57
   at SharpLab.Container.Execution.ExecuteCommandHandler.Execute(ExecuteCommand command) in D:\a\SharpLab\SharpLab\source\Container\Execution\ExecuteCommandHandler.cs:line 25
```

The exception is **not** thrown when:
- `.ToList()` is not called after `MyCast<int>()`
or
- There is anything (even uselessly) done in the `foreach` body (though a blank semi-colon does not prevent the exception)

I tried [another setting](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8DEGApgGaxEAEEAxglAG4QJED6ANrAI4CwAUHwAEATAEZBABgoCRAOgDCAezZsitKApgBnANwSpIgCy7e+KCSprGzdlz3SZAGS7H8RGBjN8+TzQgA8mgAWCsgIAHwUZGwIyESaFAC8FDBEAO4UABQAlBQA3gYAvsaMyBQsiZFQ0bGaMgCyAJ5yEL4sAPIYfrDh2RQA9H0UCMGoAOaBFI3NrQAiCl0wPTlQ8WQpfBSbFKbmNHRWrBwwPLxbFDIAKgo+CNkbW67unqdbxoIAzPoAbFJCFNMIACiAA9mFp1DA+Ll7psBJ9pD9pO8/BcAEoRKYtBAsOYo9EZYYrfSfIhZGF5clnEghIg0CYZDANGAQMBQagUBQUWAUUmUs5baQiKQAdkyaKyihg9CIoXkgQgMFGRAuDQADkQMgo4EM1UQFCQMuKssZ+Vs+ZtqbE6ZkFMAAFaqBAcrkwHlkl6ms6CkVi1ESjTS2VyeWK5W6zXahC6/WGv3G8kFcnkuHfYl4jFNLHtTposIEwJEpFu8nQj38y206j020O2jO7m8sue/p9b0CUWx/1SmUIOUKpUq9URnXqmNGlsUC4QZBKhAASSlCmoTAhIOoRFVdA05v5Js9O4r1oZTJZbPrrsbza9IiF7d9XcDveD/bDQ61I71BqNe82id4BSAA==) with `yield return (TR)Convert.ChangeType(o, typeof(TR));`, and the result did not narrowed down the exception throwing case.

Is this inner `InvalidProgramException` exception intended?

**Comment by jaredpar** [comment] 2021-09-14 15:02
Thanks for taking the time to file this issue. Unfortunately I'm unable to reproduce it. 

Here is the example code up on sharplab and it all configurations it's executing without issue. Could you identify what is different about this repro and the sample you used that caused the exception to be thrown? 

https://sharplab.io/#v2:C4LgTgrgdgPgxAEwKYDMCWUkAICGBjYNANx2CQH0AbDARwFgAoRgAQAYtmBGAOgGEB7SpSQE0/KAGcA3C3ZcALDIZw0KXKJJkqtWRx4AZWkrhIoCVY0aGJwADwSAFvzDAAfFnSVgYJBKwBeLEwAdywACgBKLABveQBfJRIwLHIAjzQvHwluAFkAT14cG1sMN0jGLEqsFTV8Qk0Kaih6BiqsbgAVfmtgctaqkzMLfsqlLm4uAE4wgCIHJB8ZiKUWAGY9ADYOACYsQpsAUQAPMkkxKEZoiqrmda4trlXbDoAld3z9u1fXMOAHND8jywSAi10qVxGbQ8ziQ+Ac4QQeSgOAAtmg8Fh+FgMMDQZC2hCoUS9OwEFIsAB6ClYWwAWiwHRwYAA5khgABJKBEfh4UjnY54JAAB0I4iwwXmUCweH4KJRpjICHCEoy2DqxFIjVo2L8yHQmAQEW4YOJlS4nA4AHZMUpTXETfaGHEgA==

**Comment by canton7** [comment] 2021-09-14 15:06
I don't know whether it's the same issue, but this causes an InvalidProgramException on sharplab, only on `main`, only in Debug:

```cs
C.Test(new int[1]);

public class C 
{
    public static string Test(int[] pi)
    {   
        string result = null;
        for(int i = 0; i < pi.Length; i++)
        {
            int b = pi[0];
            b = pi[0];
            result = pi[0].ToString();
        }

        return result;
    }
}
```

[Link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xALANwUUDCAdACoCmAzggAUMHgHcasBAG1iAXQCULchXwBmOoRpsaFAN4UahuuvoA2OsVq8BgyVNk0ADlHkGjuo26NH6tZP1QAGwQaAF4aGCDApW9vADMAe2RbGBCoMJoqJgkaAB4nKA4AGR4YAHMEAAtsqGxsV3JY9y8mo0kaYAznKSpZGNbvTvDu3v6Bw38+IJDhqB7ZbgSAZQRkWDLBRRbvAF9WRtb8AHYaSemxmj3yHaA)

**Comment by canton7** [comment] 2021-09-14 15:11
@jaredpar It seems you need to set the branch to `main`, and comment out the line which has a comment on it: [See here](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8DEGApgGaxEAEEAxglAG4QJED6ANrAI4CwAUHwAEADBQEBGAHQBhAPZs2RWlBkwAzgG5BI8QBZNvfFBJUljZuy5bRkgDJd9+IjAxG+fO6oQAeVQAsZyAgAfBRkbAjIRKoUALwUMEQA7hQAFACUFADeOgC++ozIFCyxoVDhkaoSALIAnlIQnl6wwel8FO0UhsY0dGasHDA8vB0UEgAqMh4IrcMdjs6us+364hLiAJwpAES+RJFbafqCAMzWAGyiAEwU9Z4AogAezGrKMHyZbR0Cp+IX4sdeMYAJRCtVu3mBQRSCF8UGi/woRDSn3aHyWI1CASINF8qQwNRgEDAUGoFBkFFgiOR6JGaIx9IoAHpGdYRBh1EyWV4ALQUMYQZAAcyICAAkjB6DJqExXo9qEQAA50FQURK7GAUagyMBgJzMDCpNVlSg9BhMfpcCnRYhkBIYNISFEM9riMSiADsZP0zpyTt9vByQA=)

**Comment by jaredpar** [comment] 2021-09-14 15:13
@canton7 thanks, I can see both examples now. 

In the second sample the issue is the following line:

```
b = pi[0]
```

If that is removed then the exception goes away. That's a bit odd though. Hard to think through what we could be doing wrong there. 

@333fred PTAL

**Comment by canton7** [comment] 2021-09-14 15:15
@jaredpar if remove any of those lines, or change the loop to be `i < 1`, or remove the ToString, or not return a value, or return from inside the loop, or anything else I could think of, the issue goes away!

**Comment by Daynvheur** [comment] 2021-09-15 16:50
For what it's worth, the exception is not always thrown depending on SharpLab's container state:
![image](https://user-images.githubusercontent.com/4216815/133475664-891a96aa-e953-412c-9c7e-ec9760e51c40.png)

**Comment by Daynvheur** [comment] 2021-09-16 10:47
In the motivation of helping you to spot the source, I've replicated the exception with a [tighter code](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8AqApgM4IAUAlANwAEA9HfhMgOaEICSMAbgPYDGEBFF4wAogA9+hAA7DRAWABQyhjQAihADbtCNUXuBaIMANY0tsPWWDbeAdzg0IwXt0JPeyGggAWUYn0YQgofXhoMAOATDB9fPUlpOREYADplZQABABYaIlJKZQBvZRoymgAzLzJYBBooGgBeGgBGWgaAPlaqClLykqVyofqYOogmmgAGKj7hkbrgCenZ4dqafiWZwbmaTJbJmmQSVC065oPU/F4AZQRkWBZKLaGAX2UXoA): The exception is not thrown when there are less than 3 blank lines between the `Test` call and declaration, and @canton7's lines removal/changes still apply.
```cs
Test(); //TargetInvocationException

// Delete one blank line (below, above, or this one) to disband the Exception.

void Test()
{
    for(int i = 1; i > 1;)
    {
        int a = 0;
        int b = 0;
        int c = 0;
        string result = 0 .ToString();
    }
}
```

_As much interested am I on this subject, I don't want to annoy with meaningless updates, so I'll mute for a moment, keeping an eye for an eventual fix._

**Comment by canton7** [comment] 2021-09-21 13:18
Another one:

```cs
public class C {
    public static async Task Main() {
        var tasks = new Task[] { Task.FromException(new Exception("BOOM")) };
        await Task.WhenAny(Task.Delay(TimeSpan.FromSeconds(0.1)));
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xAdACoAWyAphBrAOYDcFanWIBWAeUEBmOoRoBhGgG8KNVXWn0AbHQAcdbQFloMABQBKJSrXWAbhGQ0EEAM4BrZzQC8NGOwDu+gDaALpK+gwAYsgA9mAAogAeAMbsAA4IUNGmvgGJKemZpgBEAEIA8mUGRWYWAL7i1tb4AJzhAOos7DAAgjAAnib4mgwAIuwANhADTFBg7ADKqRAwkTFg8+xJWRjOJlQMxDVmDWq1FLVAA).

Note how `tasks` isn't used...

**Comment by 333fred** [comment] 2021-09-21 21:40
I haven't been able to reproduce this anywhere outside of sharplab. In particular, the example from @Daynvheur makes me strongly suspect that something is going on with Sharplab's instrumentation (that annotates what values are being passed/returned from functions). @ashmind, would you be able to take a look and confirm whether this is the case?

**Comment by ashmind** [comment] 2021-09-21 22:25
Thanks for pinging me!

I'll take a look a bit later (and I didn't have time to read the full thread yet), however by default I expect 95% `InvalidProgramException` that come out of SharpLab to be a SharpLab instrumentation problem.

**Comment by Daynvheur** [comment] 2021-10-05 14:41
Hello!
I'm unable to reproduce the exception on any of the linked code extracts. Should this Issue be closed?

**Comment by 333fred** [comment] 2021-10-05 17:08
@ashmind did you get a chance to look at this?

**Comment by jaredpar** [comment] 2021-10-05 18:07
Closing for now as I think it's reasonable to assume this is a bug in sharplab rewriting. If it turns out not to be then we can re-activate and investigate.

**Closed by jaredpar** 2021-10-05 18:07 UTC
Labels: Bug, Area-Compilers, untriaged
