### ISSUE TITLE
Editor Crash on Renaming Type Parameter

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9673] opened 2016-03-10 22:00 UTC
**Version Used**: 
VS2015 Update 2 RC 14.0.25029

**Steps to Reproduce**:

Given following code fragment:
```CSharp
public partial class Foo<ObjT> {}
partial class Foo<ObjT> {}
```
Attempting to rename `ObjT` causes a crash

**Comment by Pilchie** [comment] 2016-03-10 22:20
Dupe of #7440,  fixed by @dpoeschl.

**Closed by Pilchie** 2016-03-10 22:20 UTC
Labels: Area-IDE, Bug
