### ISSUE TITLE
CSharpAddMissingImportsRefactoringProvider thrown ArgumentOutOfRangeException in FindTokenCore

### ISSUE THREAD

**Issue by arturek** [dotnet/roslyn#35982] opened 2019-05-27 13:12 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.2.0 Preview 1.0
VisualStudio.16.Preview/16.2.0-pre.1.0+28917.182
Microsoft .NET Framework
Version 4.8.03761

**Steps to Reproduce**:
It happened after inserting a whole method into a new class. Apart from missing using directives the whole code was correct.

**Actual Behavior**:

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position,Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.Shared.Utilities.CommonFormattingHelpers.ConvertToTokenPair(SyntaxNode root,TextSpan textSpan)
   at Microsoft.CodeAnalysis.Shared.Utilities.CommonFormattingHelpers.<ConvertToTokenPairs>d__2.MoveNext()
   at Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.FormatIndividually(SyntaxNode node,OptionSet options,IEnumerable`1 rules,IList`1 spansToFormat,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.Format(SyntaxNode node,IEnumerable`1 spans,OptionSet options,IEnumerable`1 rules,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.CleanUpNewLinesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.CleanUpNewLinesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.ApplyFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.AddMissingImportsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsRefactoringProvider.AddMissingImports(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by nathanielcook** [comment] 2019-08-16 18:15
Am seeing what I think is the same issue in the log all the time with Visual Studio for Mac Version 8.2.1 (build 19)
Format happens on save, and sometimes the code is in a state that causes this. After it happens, code syntax highlighting stops working in that window until I close the window and reopen it.
```
ERROR [2019-08-16 11:10:06Z]: An unhandled exception has occurred. Terminating Visual Studio? False
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
  at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore (System.Int32 position, System.Boolean findInsideTrivia) [0x00039] in /_/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs:1298 
  at Microsoft.CodeAnalysis.SyntaxNode.FindToken (System.Int32 position, System.Boolean findInsideTrivia) [0x00000] in /_/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs:852 
  at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxTokenExtensions.FindTokenFromEnd (Microsoft.CodeAnalysis.SyntaxNode root, System.Int32 position, System.Boolean includeZeroWidth, System.Boolean findInsideTrivia) [0x00000] in /_/src/Workspaces/Core/Portable/Shared/Extensions/SyntaxTokenExtensions.cs:78 
  at Microsoft.CodeAnalysis.Shared.Utilities.CommonFormattingHelpers.GetFormattingSpan (Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.Text.TextSpan span) [0x00022] in /_/src/Workspaces/Core/Portable/Shared/Utilities/CommonFormattingHelpers.cs:376 
  at Microsoft.CodeAnalysis.Editor.Shared.Utilities.CommonFormattingHelpers.GetFormattingSpan (Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.Text.TextSpan span) [0x00000] in /_/src/EditorFeatures/Core/Shared/Utilities/CommonFormattingHelpers.cs:15 
  at Microsoft.CodeAnalysis.Editor.CSharp.Formatting.CSharpEditorFormattingService.GetFormattingChangesAsync (Microsoft.CodeAnalysis.Document document, System.Nullable`1[T] textSpan, System.Threading.CancellationToken cancellationToken) [0x00137] in /_/src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs:103 
  at MonoDevelop.CSharp.Formatting.CSharpFormatter.OnTheFlyFormatImplementation (MonoDevelop.Ide.Editor.TextEditor editor, MonoDevelop.Ide.Editor.DocumentContext context, System.Int32 startOffset, System.Int32 length) [0x0005b] in /Users/vsts/agent/2.154.3/work/1/s/monodevelop/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs:122 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at MonoDevelop.Ide.DispatchService+GtkSynchronizationContext+TimeoutProxy.HandlerInternal (System.IntPtr data) [0x00014] in /Users/vsts/agent/2.154.3/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs:77 
```

**Comment by jinujoseph** [comment] 2019-10-10 00:26
Duplicate of https://github.com/dotnet/roslyn/issues/38708

**Closed by jinujoseph** 2019-10-10 00:26 UTC
Labels: Area-IDE, Bug
