### ISSUE TITLE
Redirect the temp directory on non-windows platforms

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7847] opened 2016-01-08 01:03 UTC
Windows Jenkins runs redirect the temp directory under the enlistment so that (a) it'll be included in the build artifacts and (b) it won't accumulate in the real temp directory.  Linux and Mac runs should do the same. 

We believe that `Path.GetTempPath` checks `TMPDIR` on Linux (and Mac?).

**Comment by AdamSpeight2008** [comment] 2016-01-08 16:21
Possible dupe of #6497

**Comment by jaredpar** [comment] 2016-01-08 16:36
Can you be more specific here?  Specifically what are you trying to redirect: an environment variable, symlink directories, etc ...

**Comment by AdamSpeight2008** [comment] 2016-01-08 16:53
@jaredpar In my case I want the temp directory that Roslyn uses to be expressed as an environment variable. So it can be changed (without effecting Roslyn). It would also likely address @amcasey's issue as well. Or it could supplied as a compiler parameter `-Temp "/Foo/Bar/Baz"`

**Comment by amcasey** [comment] 2016-01-08 18:09
@jaredpar Ideally, we'd like everything that would have gone under the temp folder as part of a test run to end up in a directory under the enlistment.  However, I believe the key goal is to relocate the temporary files (assemblies, scripts, etc) created by the unit tests.  Since the unit tests call `Path.GetTempPath`, changing the return value of that method (which we seem to be able to do by setting `TMPDIR`) should suffice.

**Comment by jaredpar** [comment] 2016-01-08 18:13
> we'd like everything that would have gone under the temp folder as part of a test run to end up in a directory under the enlistment.

This is what I'm curious about though: which temp folder?  There are a number of ways we grab temp folders in our runs:

1. Directly use `/tmp` as it's the standard temp folder on Unix. 
2. Use the `TMP / TMPDIR` environment variable. 
3. Use higher level APIs like `Path.GetTempPath`.

Which of these are we proposing to change with this bug and how do we propose to fix it? 

In particular I'm concerned about item 1.  Making this a per run item would significantly slow down our builds as we cache our Azure blobs here.

**Comment by amcasey** [comment] 2016-01-08 18:29
The main goals of this bug are:

 1. Make Linux and Mac consistent with Windows
 1. Have access to temporary files created by unit tests without remoting into the test machines
 1. Not run out of space or unique names in the temporary folder

If I understand our Windows implementation correctly, we set a new value for `%TEMP%` which affects both our scripts and our programmatic use of `Path.GetTempPath`.  Anecdotally, I believe I've seen the Azure blob end up in the new temp folder, possibly defeating caching.  I haven't had a chance to investigate.

**Comment by amcasey** [comment] 2016-01-08 18:31
@jaredpar Is this the sort of thing you're trying to avoid? [Nuget zip under binaries directory.](http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_master_win_dbg_unit64/623/artifact/Binaries/Temp/)

**Comment by jaredpar** [comment] 2016-01-08 18:42
@amcasey no.  What I'm worried about is having to re-download the Azure blob zip files on every run.  It can be a source of throughput issues.  

If the goal is to have our log files I think that redirecting the `%TEMP%` variable should be enough.  The items we directly put into `/tmp` from our scripts doesn't have any real value for the log files.

**Comment by AdamSpeight2008** [comment] 2016-01-08 18:58
Wouldn't supplying a temp folder to use (compiler parameter) help? Then audit to source for usage of `Path.GetTempPath` to use something like `CompilerSettings.TempPath`

**Comment by AdamSpeight2008** [comment] 2016-01-08 21:33
`GetTempPath` is currently reference 16 times in the source.
```
Find all "GetTempPath", Find Results 1, Entire Solution, ""
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Core\CodeAnalysisTest\SimpleAnalyzerAssemblyLoaderTests.cs(29):            var path = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName() + ".dll");
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Server\VBCSCompiler\DesktopCompilerServerHost.cs(21):        private static readonly IAnalyzerAssemblyLoader s_analyzerLoader = new ShadowCopyAnalyzerAssemblyLoader(Path.Combine(Path.GetTempPath(), "VBCSCompiler", "AnalyzerAssemblyLoader"));
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Shared\ShadowCopyAnalyzerAssemblyLoader.cs(41):                _baseDirectory = Path.Combine(Path.GetTempPath(), "CodeAnalysis", "AnalyzerShadowCopies");
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(347):GetTempPath(); // using static not exposed
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(364):                // (6,1): error CS0103: The name 'GetTempPath' does not exist in the current context
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(365):                // GetTempPath(); // using static not exposed
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(366):                Diagnostic(ErrorCode.ERR_NameNotInContext, "GetTempPath").WithArguments("GetTempPath").WithLocation(6, 1),
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(395):GetTempPath(); // using static not exposed
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(450):                // a.csx(17,1): error CS0103: The name 'GetTempPath' does not exist in the current context
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(451):                // GetTempPath(); // using static not exposed
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(452):                Diagnostic(ErrorCode.ERR_NameNotInContext, "GetTempPath").WithArguments("GetTempPath").WithLocation(17, 1),
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Semantic\Semantics\InteractiveUsingTests.cs(467):GetTempPath(); // global using static exposed
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Portable\Errors\Errors.vb(541):        'ERR_UnableToGetTempPath = 30698
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Shared\TempFiles\TempRoot.cs(17):            Root = Path.Combine(Path.GetTempPath(), "RoslynTests");
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\WinRT\Metadata\WinMdDumpTest.cs(452):                string fileExpected = Path.Combine(Path.GetTempPath(), "roslyn_winmd_dump.expected.txt");
  H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\WinRT\Metadata\WinMdDumpTest.cs(453):                string fileActual = Path.Combine(Path.GetTempPath(), "roslyn_winmd_dump.actual.txt");
  Matching lines: 16    Matching files: 7    Total files searched: 3743

```

**Comment by davkean** [comment] 2016-01-14 23:30
@AdamSpeight2008 This bug is not tracking adding a parameter/environment variable to the compiler. That would not satisfy the requirement above, as there's a lot more than the compiler involved in the build environment.

**Closed** 2018-03-29 23:29 UTC
Labels: Area-Infrastructure, Feature Request
