### ISSUE TITLE
NullReferenceException when analyzing project inside VS

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#16294] opened 2017-01-06 13:18 UTC
AD0002 is reported with the following message:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0002	Analyzer driver threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	CSharpWorkspace		1	Active	Analyzer driver threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.BoundCall.<>c__DisplayClass29_0.<DeriveArgument>b__0(BoundExpression argument)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArgument(Int32 parameterIndex, Int32 argumentIndex, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, ImmutableArray`1 argumentRefKinds, ImmutableArray`1 parameters, SyntaxNode invocationSyntax)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArguments(ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, ImmutableArray`1 argumentsToParameters, ImmutableArray`1 argumentRefKinds, ImmutableArray`1 parameters, SyntaxNode invocationSyntax)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder()
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitInvocationExpression(IInvocationExpression operation)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclaration(IVariableDeclaration operation)
   at Microsoft.CodeAnalysis.Semantics.VariableDeclaration.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclarationStatement(IVariableDeclarationStatement operation)
   at Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(IBlockStatement operation)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.DescendantsAndSelf(IOperation operation)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
-----
'.
```

**Version Used**:  Visual Studio 2015 Update 3

**Steps to Reproduce**:

1. Install some analyzer VSIX. (It happened to me with SonarLint, but it's most probably not specific to that one.)
2. Open the Roslyn.sln
3. Enable full solution analysis
4. Wait for all the issues to show up

**Comment by OmarTawfik** [comment] 2017-01-06 22:58
@tvsonar no repro with `SonarLint.VSIX-2.8.1.241.vsix` and `VS.14.0.25431.01` :( Can you please share the versions of the vsix/VS you're using?

**Comment by tvsonar** [comment] 2017-01-09 08:02
@OmarTawfik Sorry, I thought it would come up with all versions. I was building locally this VSIX: https://github.com/SonarSource-VisualStudio/sonaranalyzer-dotnet/tree/master/src/SonarAnalyzer.Vsix (this has the same SonarLint analyzers) and deployed it to the experimental instance. There shouldn't be a lot of difference compared to `SonarLint.VSIX-2.8.1.241.vsix`, but I built the debug version and the assemblies were not signed.

**Comment by OmarTawfik** [comment] 2017-01-20 01:55
@tvsonar no repro still with it trying to open Roslyn master. If you've a minute, can you please mention if:
1. This bug reproduces consistently as well on the current master with VS 2017? or is it just VS 2015?
2. Did it ever reproduce with a smaller project/sample?

This information could significantly expedite the process of fixing it.
Thanks for the info so far :)

**Comment by OmarTawfik** [comment] 2017-01-20 18:19
Note to self: it might also be related to #8920.

**Comment by tamasvajk** [comment] 2017-01-23 10:16
@OmarTawfik This happens on a different machine too with the current master of Roslyn. I don't even have SonarLint installed on this machine. 

Here's the VS Info:
```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90000-04501-AA696
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90000-04501-AA696
Microsoft Visual Basic 2015

Visual C# 2015   00322-90000-04501-AA696
Microsoft Visual C# 2015

Visual C++ 2015   00322-90000-04501-AA696
Microsoft Visual C++ 2015

Visual F# 2015   00322-90000-04501-AA696
Microsoft Visual F# 2015

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Image Optimizer   3.6.103
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Trailing Whitespace Visualizer   2.5.82
Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace

TypeScript   2.0.2.0
TypeScript tools for Visual Studio

Visual Studio Tools for Unity   2.8.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VSColorOutput   2.4
Color output for build and debug windows - http://mike-ward.net/vscoloroutput
```

I couldn't repro this with VS2017.

**Comment by OmarTawfik** [comment] 2017-01-24 00:03
Closing as neither of us could repro on VS2017. We should re-open it if we have a repro on latest/master.

**Comment by jods4** [comment] 2017-02-10 21:46
@OmarTawfik Just sayin': it still repro on Feb. 7th update. You definitely have a bug here.
My call stack is exactly the same.

**Comment by OmarTawfik** [comment] 2017-02-10 22:30
@jods4 do you have a consistent repro? same vsix or a different one?
Can you please provide the vsix and the build number and I'll reactivate it?

**Comment by jods4** [comment] 2017-02-10 23:16
Ah I did not see the vsix part under the description.
It showed up in my errors just by working on a ASP.NET Core C# app. I have not installed anything yet on top of a fresh VS 2017 RC, Feb 7th install.

**Comment by OmarTawfik** [comment] 2017-02-13 20:54
@jods4 is it possible to share the code snippet that is crashing?

**Comment by jods4** [comment] 2017-02-13 21:13
Unfortunately not, it's a complex large closed-source solution :(
And I am not sure what triggers the error, I just noticed it.

I don't know if it can be related or not but I disabled Lightweight solution loading and since then several problems I had disappeared. For example I have not noticed that specific error since then, despite working on the solution quite a lot.

**Comment by OmarTawfik** [comment] 2017-04-03 18:02
@AlekseyTs could this be related to #17072?

**Comment by AlekseyTs** [comment] 2017-04-03 18:10
> could this be related to #17072? 

It could.

**Comment by OmarTawfik** [comment] 2017-04-03 19:00
@tvsonar @tamasvajk @jods4 
Judging from same trace and behavior, and since I could not repro it on the latest bits from master as well, I'm goign to close this as duplicate. The fix should go out in the first quarterly release of VS 2017.
You can also try it out locally now by using a nuget package from the nightly build on master.
I'm going to close it for now. Please feel free to re-open if you have another repro using the latest bits.

**Closed by OmarTawfik** 2017-04-03 19:00 UTC
Labels: 3 - Working, Area-Compilers, Bug
