### ISSUE TITLE
Auto Format fails for multi-line collection initializers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31251] opened 2018-11-19 13:22 UTC
Auto format fails for multi-line collection initializers. The only way to auto format a collection initializer is to remove all linebreaks, format it, then place linebreaks back in.

Auto format works for multi-line indexer and property initializers.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/250421/auto-format-fails-for-multi-line-collection-initia.html
VSTS ticketId: 614284_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎5‎/‎20‎/‎2018, 02:50 AM (183 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Joakim Thulin on ‎11‎/‎3‎/‎2018, 09:18 AM (15 days ago): I have this problem too, a little annoying
Jinu Joseph [MSFT] on ‎11‎/‎3‎/‎2018, 09:36 PM (15 days ago): <p><a rel="user" href="https://developercommunity.visualstudio.com/users/54842/b66ca0b1-a48e-45e3-b936-d959fd9bb594.html" nodeid="54842">@Joakim Thulin</a> could you pls provide us with a repro code snippet ? This will really help us with the investigation</p>

Joakim Thulin on ‎11‎/‎16‎/‎2018, 04:22 AM (3 days ago): <p>Sure, see attached screenshot.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/48562-beforeafter.png"></p>

Joakim Thulin on ‎11‎/‎4‎/‎2018, 05:10 AM (15 days ago): <p>Sure, see attached screenshot.<a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/46866-beforeafter.png">beforeafter.png</a></p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-11-20 18:12
Duplicate of #779

**Closed by sharwell** 2018-11-20 18:12 UTC
