### ISSUE TITLE
After moving all Diagnostics from PCL to VSIX Project, I get same error on every Diagnostic

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5861] opened 2015-10-10 22:18 UTC
All code is in one VSIX project. The errors only show up when you build the project.
```
Error Method 'get_SupportedDiagnostics' in type 'VBCodeRefactoring.Usage.UriAnalyzer' from assembly 'VBCodeRefactoring.Vsix, Version=2.0.5761.26877, Culture=neutral, PublicKeyToken=70174ec4ec31f8a5' does not have an implementation.
```
Every Diagnostic implements
```
        Public Overrides ReadOnly Property SupportedDiagnostics() As ImmutableArray(Of DiagnosticDescriptor)
            Get
                Return ImmutableArray.Create(Rule)
            End Get
        End Property

```
This repeats for every Diagnostic with only the name of the type changing

I get a similar error for CodeFix Providers
```
Error		Method 'get_FixableDiagnosticIds' in type 'VBCodeRefactoring.Design.EmptyCatchBlockCodeFixProvider' from assembly 'VBCodeRefactoring.Vsix, Version=2.0.5761.26877, Culture=neutral, PublicKeyToken=70174ec4ec31f8a5' does not have an implementation.		
```

I also get 6 very strange partial errors that start with "at" at the end of the list
```
Error		at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
Error		at System.Reflection.RuntimeModule.GetTypes()		
Error		at System.Reflection.Assembly.GetTypes()	
Error		at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode)	
Error		at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
Error		at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
```

**Comment by paul1956** [comment] 2015-10-10 23:41
The problem was something in the build was referring to the only PCL code. Renaming the Root Namespace solved the issue.

**Comment by paul1956** [comment] 2015-10-10 23:43
I prematurely closed this issue.

**Comment by mavasani** [comment] 2015-10-19 05:23
@paul1956 I am unable to repro this. Can you please let me know how did you setup your vsixmanifest file? VS IDE requires your to provide an analyzer asset of type File in the following format:
```
<Asset Type="Microsoft.VisualStudio.Analyzer" d:Source="File" Path="Analyzer1.dll" />
```
Did you specify the path to the temporarily generated Analyzer1.dll from obj folder? Otherwise, I don't see how you can specify the analyzer asset if your diagnostic analyzer is defined in the same project. 

Additionally, may I know what is your scenario behind getting rid of the separate assembly with the analyzer? Note that you will eventually need the analyzer to be packaged in a separate assembly, so you cannot get away with having no assembly file here.

**Comment by mavasani** [comment] 2015-10-19 05:25
I am resolving this as by design - you cannot avoid packaging the analyzer in a separate assembly. Kindly re-open if you disagree.

**Closed by mavasani** 2015-10-19 05:25 UTC
Labels: Area-Analyzers, Bug

**Comment by paul1956** [comment] 2015-10-19 05:34
The reason I did it is because my analyzer needed to read a file in the solution where I store some options. The VSIX provided the button logic to set the options and can update a class in the PCL library when the option changes but I could not figure out how to initialize the option.  I agree with your By Design but there has to be a way for the PCL to get options since other add-in seem to have them.

By first try was just to change the PCL to a regular library so I could do file IO, but that turns out not to help because the class library can't find the Solution.in the file system.
