### ISSUE TITLE
[Loc Unit Test Failure ] Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.BrokenOutStream [FAIL]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10026] opened 2016-03-23 20:44 UTC
Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.BrokenOutStream [FAIL]

```
  Expected:
      Diagnostic(ErrorCode.ERR_PeWritingFailure).WithArguments("I/O error occurred.")
  Actual:
      // error CS8104: An error occurred while writing the output file.
      Diagnostic(ErrorCode.ERR_PeWritingFailure).WithArguments("I/O ƒGƒ‰[‚ª”-¶‚µ‚Ü‚µ‚½B").WithLocation(1, 1)
  Diff:
  ++>     Diagnostic(ErrorCode.ERR_PeWritingFailure).WithArguments("I/O ƒGƒ‰[‚ª”-¶‚µ‚Ü‚µ‚½B").WithLocation(1, 1)
  -->     Diagnostic(ErrorCode.ERR_PeWritingFailure).WithArguments("I/O error occurred.")
  Expected: True
  Actual:   False
  Stack Trace:
       êŠ Xunit.Assert.True(Nullable`1 condition, String userMessage)
       êŠ Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
       êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests.BrokenOutStream()
```

**Comment by jinujoseph** [comment] 2016-03-23 20:44
This are for standalone 
 please contact @mattscheffer for more information

**Comment by jaredpar** [comment] 2016-09-09 15:15
@jasonmalinowski this has the same root cause as #10025

**Comment by jaredpar** [comment] 2017-02-08 20:55
Resolving as a dupe.

**Closed by jaredpar** 2017-02-08 20:55 UTC
Labels: Area-Compilers, Bug, Tenet-Localization
