### ISSUE TITLE
Auto Format: Don't align end-of-line comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33068] opened 2019-02-02 00:19 UTC
<p>I use auto-formatting to format my C# code in Visual Studio, but I find it extremely annoying how it insists on aligning end-of-line comments (those starting with //) from multiple consecutive lines horizontally with each other.  It drives me crazy when this situation arises which is frequent enough for me to post this suggestion.  Please add an option to allow me to turn off this annoying behavior!</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/432260/auto-format-dont-align-end-of-line-comments.html
VSTS ticketId: 774369_
_These are the original issue comments:_

Jane Wu [MSFT] on 1/22/2019, 02:10 AM (10 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by sharwell** [comment] 2019-02-04 13:45
Duplicate of #29482

**Closed by sharwell** 2019-02-04 13:45 UTC
Labels: Resolution-Duplicate, Developer Community
