### ISSUE TITLE
Support exceptions in naming rules

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#46708] opened 2020-08-11 14:09 UTC
**Version Used**: VS 16.7

I have a rule making all private methods lowerCamelCase but I want an exception for `Main` method.
There should be an option to make an exception for rules

```cs
# Lower camelCase private methods style
dotnet_naming_rule.private_methods_lower_camel_case.symbols=private_methods
dotnet_naming_rule.private_methods_lower_camel_case.style=lower_camel_case
dotnet_naming_rule.private_methods_lower_camel_case.severity=suggestion
dotnet_naming_symbols.private_methods.applicable_kinds=method
dotnet_naming_symbols.private_methods.applicable_accessibilities=private
```

**Comment by CyrusNajmabadi** [comment] 2020-08-13 22:42
> but I want an exception for Main method.

We should not ever be trying to apply naming styles to the Main method.

**Comment by jinujoseph** [comment] 2020-08-18 19:36
Duplicate of #36385

**Closed by jinujoseph** 2020-08-18 19:36 UTC
Labels: Area-IDE, help wanted
