### ISSUE TITLE
Find All References does not find uses of default ctor

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#27201] opened 2018-05-27 19:56 UTC
In the code below, find-all-references does not find the use of A() in B.

``` c#
class A
{
    static void Main() { }
    public A() { }
    public A(int i) : this() { }
}

class B : A
{
}
```

![image](https://user-images.githubusercontent.com/3804346/40590056-5363a1c2-61ad-11e8-9567-bda5cccad02f.png)

**Comment by CyrusNajmabadi** [comment] 2018-05-29 16:30
Agree with the 'needs design review'.  We could potentially give the default constructor of 'B' as an 'implicit' reference location.  Our API certainly supports that concept.  

If you had an explicit constructor for 'B' do we show that as a reference?

**Comment by gafter** [comment] 2018-05-30 21:45
> If you had an explicit constructor for 'B' (but without an explicit 'base') do we show that as a reference?

No.

**Comment by dpoeschl** [comment] 2018-10-22 20:13
Design Meeting Notes:
- We could do this as Cyrus describes above, but don't think it's a high priority. @gafter Is there a particular refactoring scenario driving this request?

**Comment by sharwell** [comment] 2021-06-21 18:53
Duplicate of #11049

**Closed by sharwell** 2021-06-21 18:53 UTC
Labels: Area-IDE, Concept-Continuous Improvement
