### ISSUE TITLE
`await` completion in C# `void` method doesn't change `void` to `Task` when adding `async`

### ISSUE THREAD

**Issue by tlmii** [dotnet/roslyn#70866] opened 2023-11-16 18:48 UTC
**Version Used**: Version included in VS 2022 17.9 Preview 1

**Steps to Reproduce**:

1. In a Blazor app, add a non-async, void-returning EventCallback handler in your C# code and reference it via the relevant EventCallback Parameter in the .razor code (e.g. add an OnClick handler to a button)
2. Modify the body of the method added in step 1 by typing out a call to `await Task.Delay(1000);`.
3. Notice that the signature of the method has been changed from `void` to `async void` and there are no errors or warnings in the IDE or build output at either the callsite in razor or the method signature in C#.

(note that this is just one example where the trap you fall into is easy to hit, but there are likely others)

**Expected Behavior**:

Since the generally accepted guidance is to avoid `async void` methods whenever possible (with some limited exceptions for event handlers, etc), I would expect that doing the above steps would either:

1. NOT add the async, so that I am prompted with squiggles/warnings/errors to correct my signature and I can take note of changing the entire signature correctly, OR
2. Change `void` to `Task` in addition to adding `async` so that I am in the more-likely-correct state for that method and if it conflicts with the callsite I will get squiggles/warnings/errors that lead me to address it there as well.

**Actual Behavior**:

`async` is added, but there are no squiggles/warnings/errors telling me that I _likely_ need to change something else as well. 

I just fell into this trap in https://github.com/dotnet/aspire/pull/819 (See https://github.com/dotnet/aspire/pull/819#discussion_r1395303542) where I converted an existing void method to `async` and let VS handle that and didn't notice that I should do more. Frankly saying I let VS handle it is probably too strong - VS handled it without me even really noticing, and I _really_ didn't notice because there weren't the expected squiggles/warnings/errors after adding await calls to a non-async method.

Of course, ultimately its on me (and my reviewers) to notice these things and I will now be more careful in the future. And I know there were previous discussions about this when the feature was implemented. But it feels like from a tooling perspective we could do better to not guide users right into the trap so I figured it was worth bringing up again.

**Comment by CyrusNajmabadi** [comment] 2023-11-16 18:49
Yup.  We should likely fix this.  `async void` is an anti pattern we should avoid.

**Comment by sharwell** [comment] 2023-11-23 23:20
Duplicate of #55975

**Closed by sharwell** 2023-11-23 23:20 UTC
Labels: Area-IDE, untriaged
