### ISSUE TITLE
devenv crash on Release mode if project compiled from devenv.com

### ISSUE THREAD

**Issue by wpanja** [dotnet/roslyn#13979] opened 2016-09-22 15:04 UTC
**Version Used**: 

Visual Studio 2015 Update 3

**Steps to Reproduce**:
1.  While compiling this C# project (\elements\Share\CaseShare\Roslyn\Src) using this switch devenv.com <soln name>.sln /REBUILD Release ; devenv.exe crashes
2.  With Debug version and msbuild version it succeeds
3.  End user uses HP Fortify SCA so he cannot use msbuild
4.  Happens with VS 2015 Update 3

**Expected Behavior**:
devenv.exe should not crash

**Actual Behavior**:
devenv crashes with the following error and below details

```
CLR: Managed code called FailFast, saying "System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32 cookie)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(Object sender, EventArgs e)
   at Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()
   at Microsoft.CodeAnalysis.Workspace.<>c__DisplayClass199_0.<RegisterText>b__0()
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass2_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass6_0`1.<SafeContinueWith>b__0(Task t)"

eax=00000000 ebx=77c40820 ecx=00000002 edx=00000000 esi=00000000 edi=00000000
eip=77b7c4fc esp=05b9da0c ebp=05b9dad8 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
ntdll!NtTerminateProcess+0xc:
77b7c4fc c20800          ret     8

0:009> !pe
Exception object: 02fd1108
Exception type:   System.ExecutionEngineException
Message:          <none>
InnerException:   System.ArgumentException, Use !PrintException fcec4567 to see more.
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131506

0:009> !PrintException /d 13bef904
Exception object: 13bef904
Exception type:   System.ArgumentException
Message:          Value does not fall within the expected range.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    00000000 00000001 Microsoft_VisualStudio_LanguageServices_ni!Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32)+0x2
    05B9F4C4 0BEC10C5 Microsoft_VisualStudio_LanguageServices_ni!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(System.Object, System.EventArgs)+0x55
    05B9F4E4 0C418CC2 Microsoft_CodeAnalysis_Workspaces_ni!Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()+0x32
    05B9F4F0 0C418C8F Microsoft_CodeAnalysis_Workspaces_ni!Microsoft.CodeAnalysis.Workspace+<>c__DisplayClass199_0.<RegisterText>b__0()+0xf
    05B9F4F4 0C3BCC00 Microsoft_CodeAnalysis_Workspaces_ni!Roslyn.Utilities.TaskExtensions+<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(System.Threading.Tasks.Task)+0x10
    05B9F4F8 0C3BA120 Microsoft_CodeAnalysis_Workspaces_ni!Roslyn.Utilities.TaskExtensions+<>c__DisplayClass2_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task)+0x10
    05B9F4FC 0C3BA0AF Microsoft_CodeAnalysis_Workspaces_ni!Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)+0x1f

StackTraceString: <none>
HResult: 80070057


//Stack

0:009> !clrstack
OS Thread Id: 0x2f20 (9)
Child SP       IP Call Site
05b9e354 77b7c4fc [GCFrame: 05b9e354] 
05b9e3b4 77b7c4fc [HelperMethodFrame_2OBJ: 05b9e3b4] System.Environment.FailFast(System.String, System.Exception)
05b9e438 0b4b51b6 Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) 
05b9e444 0b4b5175 Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1) 
05b9e458 0c752a60 Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception) 
05b9e460 0c3ba0cd Roslyn.Utilities.TaskExtensions+c__DisplayClass6_0`1[[System.Boolean, mscorlib]].b__0(System.Threading.Tasks.Task) 
05b9e4e0 6c99120c [ExceptionFilterFrame: 05b9e4e0] 
05b9e54c 6c99120c [GCFrame: 05b9e54c] 
05b9f3a8 6c99120c [HelperMethodFrame: 05b9f3a8] 
DomainNeutralILStubClass.IL_STUB_CLRtoCOM(UInt32)
05b9f45c 0bec10c5 [InlinedCallFrame: 05b9f45c] Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32)
05b9f4c4 0bec10c5 Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(System.Object, System.EventArgs) 
05b9f4e4 0c418cc2 Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents() 
05b9f4f0 0c418c8f Microsoft.CodeAnalysis.Workspace+c__DisplayClass199_0.b__0() 
05b9f4f4 0c3bcc00 Roslyn.Utilities.TaskExtensions+c__DisplayClass14_0.b__1(System.Threading.Tasks.Task) 
05b9f4f8 0c3ba120 Roslyn.Utilities.TaskExtensions+c__DisplayClass2_0.b__0(System.Threading.Tasks.Task)
05b9f4fc 0c3ba0af Roslyn.Utilities.TaskExtensions+c__DisplayClass6_0`1[[System.Boolean, mscorlib]].b__0(System.Threading.Tasks.Task) 
05b9f51c 0e9fe545 System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib]].InnerInvoke() 
05b9f52c 6bbaa786 System.Threading.Tasks.Task.Execute() 
05b9f550 6bbaab02 System.Threading.Tasks.Task.ExecutionContextCallback(System.Object) 
05b9f554 6bb4a417 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
05b9f5c0 6bb4a366 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
05b9f5d4 6bbaa984 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) 
05b9f638 6bbaa8a0 System.Threading.Tasks.Task.ExecuteEntry(Boolean) 
05b9f648 6bbaa7e0 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() 
05b9f64c 6bbeebef System.Threading.ThreadPoolWorkQueue.Dispatch() 
05b9f69c 6bbeeaba System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() 
05b9f8c4 6c991396 [DebuggerU2MCatchHandlerFrame: 05b9f8c4]
```

**Comment by Pilchie** [comment] 2016-09-22 16:28
@jmarolf can you take a look?  Does this seem similar to any of the other `devenv /build` scenarios we've looked at?

**Comment by jmarolf** [comment] 2016-09-23 01:11
@wpanja This doesn't repro on Visual Studio "15".  Creating a repro machine with Visual Studio 2015 Update 3.  Do you have a dump for this crash?

**Comment by jmarolf** [comment] 2016-09-23 02:05
@wpanja I don't get a crash on 2015 Update 3.  Are there some other extensions that are installed on the users machine? 

```
C:\Users\jmarolf\Downloads\Src>devenv.com [REDACTED].sln /rebuild RELEASE

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio expires in 29 days.
1>------ Rebuild All started: Project: DomainModel, Configuration: Release Any CPU ------
```

**Comment by wpanja** [comment] 2016-09-23 05:35
@jmarolf I believe the command window turns white after 10 seconds and the command ends abruptly without building it successfully as well.

Procdump does not capture anything on second chance however it changes the behavior of the build; if we attach procdump -ma -e -w devenv.exe, we get the verbose output which is here and it lists these exceptions \\elements\Share\CaseShare\roslyn\Src\devenv.txt

The dumps are here at \\elements\Procdump
 ```

D:\Procdump>procdump.exe -ma -e -w devenv.exe
 
Press Ctrl-C to end monitoring without terminating the process.
 
[14:50:51] Exception: 04242420
[14:50:52] Exception: E06D7363.PAVEEFileLoadException@@
[14:50:52] Exception: E06D7363.msc
[14:50:52] Exception: E06D7363.PAVEEFileLoadException@@
[14:50:52] Exception: E06D7363.msc
[14:50:52] Exception: E06D7363.PAVEEFileLoadException@@
[14:50:52] Exception: E06D7363.msc
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:53] Exception: E0434352.CLR
[14:50:56] Exception: 80040154
[14:50:56] Exception: E06D7363.?AVCException@TNL@@
[14:50:56] Exception: E0434352.CLR
[14:50:57] Exception: E0434352.CLR
[14:51:03] Exception: E06D7363.PAVEEFileLoadException@@
[14:51:03] Exception: E06D7363.msc
[14:51:03] Exception: E06D7363.PAVEEFileLoadException@@
[14:51:03] Exception: E06D7363.msc
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:04] Exception: E0434352.CLR
[14:51:05] The process has exited.
[14:51:05] Dump count not reached.

I do get multiple dumps if attach proc dump with -e 1 

D:\Procdump>procdump.exe -ma -e 1 -w -n 50 devenv.exe
 
Press Ctrl-C to end monitoring without terminating the process.
 
CLR Version: v4.0.30319
 
[14:28:56] Exception: E0434F4D.System.Net.WebException ("The request was aborted: The request cache-only policy does not all
[14:28:56] Dump 1 initiated: D:\Procdump\devenv.exe_160908_142856.dmp
[14:28:56] Dump 1 writing: Estimated dump file size is 288 MB.
[14:28:57] Dump 1 complete: 288 MB written in 1.1 seconds
[14:28:57] Exception: E0434F4D.System.Net.WebException ("The request was aborted: The request cache-only policy does not all
[14:28:57] Dump 2 initiated: D:\Procdump\devenv.exe_160908_142857.dmp
[14:28:58] Dump 2 writing: Estimated dump file size is 288 MB.
[14:28:58] Dump 2 complete: 288 MB written in 0.8 seconds
[14:28:58] Exception: E0434F4D.System.Net.WebException ("The request was aborted: The request cache-only policy does not all
[14:28:58] Dump 3 initiated: D:\Procdump\devenv.exe_160908_142858.dmp
[14:28:58] Dump 3 writing: Estimated dump file size is 288 MB.
[14:28:59] Dump 3 complete: 289 MB written in 0.8 seconds
[14:28:59] Exception: E0434F4D.System.Net.WebException ("The request was aborted: The request cache-only policy does not all
[14:28:59] Dump 4 initiated: D:\Procdump\devenv.exe_160908_142859.dmp
[14:28:59] Dump 4 writing: Estimated dump file size is 288 MB.
[14:29:00] Dump 4 complete: 289 MB written in 0.8 seconds
[14:29:00] Exception: E0434F4D.System.Net.WebException ("The request was aborted: The request cache-only policy does not all
[14:29:00] Dump 5 initiated: D:\Procdump\devenv.exe_160908_142900.dmp
[14:29:00] Dump 5 writing: Estimated dump file size is 288 MB.
[14:29:01] Dump 5 complete: 289 MB written in 0.8 seconds
[14:29:01] Exception: E0434F4D.System.Net.WebException ("The remote server returned an error: (306) Unknown.")
[14:29:01] Dump 6 initiated: D:\Procdump\devenv.exe_160908_142901.dmp
[14:29:01] Dump 6 writing: Estimated dump file size is 289 MB.
[14:29:01] Dump 6 complete: 289 MB written in 0.7 seconds
[14:29:01] Exception: E0434F4D.System.Net.WebException ("The remote server returned an error: (306) Unknown.")
[14:29:01] Dump 7 initiated: D:\Procdump\devenv.exe_160908_142901-1.dmp
[14:29:02] Dump 7 writing: Estimated dump file size is 289 MB.
[14:29:02] Dump 7 complete: 289 MB written in 0.8 seconds
[14:29:02] Exception: E0434F4D.System.Net.WebException ("The remote server returned an error: (306) Unknown.")
[14:29:02] Dump 8 initiated: D:\Procdump\devenv.exe_160908_142902.dmp
[14:29:03] Dump 8 writing: Estimated dump file size is 289 MB.
[14:29:03] Dump 8 complete: 289 MB written in 0.8 seconds
[14:29:08] Exception: E0434F4D.System.ArgumentException ("The string cannot be null or contain only whitespace characters.")
[14:29:08] Dump 9 initiated: D:\Procdump\devenv.exe_160908_142908.dmp
[14:29:08] Dump 9 writing: Estimated dump file size is 415 MB.
[14:29:09] Dump 9 complete: 416 MB written in 1.5 seconds
[14:29:10] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:10] Dump 10 initiated: D:\Procdump\devenv.exe_160908_142910.dmp
[14:29:10] Dump 10 writing: Estimated dump file size is 418 MB.
[14:29:11] Dump 10 complete: 418 MB written in 1.4 seconds
[14:29:16] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:16] Dump 11 initiated: D:\Procdump\devenv.exe_160908_142916.dmp
[14:29:16] Dump 11 writing: Estimated dump file size is 463 MB.
[14:29:17] Dump 11 complete: 463 MB written in 1.5 seconds
[14:29:17] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:22] Dump 12 initiated: D:\Procdump\devenv.exe_160908_142917.dmp
[14:29:22] Dump 12 writing: Estimated dump file size is 463 MB.
[14:29:23] Dump 12 complete: 463 MB written in 1.5 seconds
[14:29:23] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:23] Dump 13 initiated: D:\Procdump\devenv.exe_160908_142923.dmp
[14:29:24] Dump 13 writing: Estimated dump file size is 463 MB.
[14:29:25] Dump 13 complete: 463 MB written in 1.4 seconds
[14:29:25] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:25] Dump 14 initiated: D:\Procdump\devenv.exe_160908_142925.dmp
[14:29:25] Dump 14 writing: Estimated dump file size is 462 MB.
[14:29:27] Dump 14 complete: 463 MB written in 1.8 seconds
[14:29:27] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:27] Dump 15 initiated: D:\Procdump\devenv.exe_160908_142927.dmp
[14:29:27] Dump 15 writing: Estimated dump file size is 462 MB.
[14:29:28] Dump 15 complete: 463 MB written in 1.5 seconds
[14:29:28] Exception: E0434F4D.System.ArgumentNullException ("Value cannot be null.")
[14:29:28] Dump 16 initiated: D:\Procdump\devenv.exe_160908_142928.dmp
[14:29:29] Dump 16 writing: Estimated dump file size is 462 MB.
[14:29:30] Dump 16 complete: 463 MB written in 1.6 seconds
[14:29:30] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:30] Dump 17 initiated: D:\Procdump\devenv.exe_160908_142930.dmp
[14:29:31] Dump 17 writing: Estimated dump file size is 462 MB.
[14:29:32] Dump 17 complete: 462 MB written in 1.8 seconds
[14:29:32] Exception: E0434F4D.System.Threading.Tasks.TaskCanceledException ("A task was canceled.")
[14:29:32] Dump 18 initiated: D:\Procdump\devenv.exe_160908_142932.dmp
[14:29:33] Dump 18 writing: Estimated dump file size is 462 MB.
[14:29:34] Dump 18 complete: 463 MB written in 1.6 seconds
[14:29:34] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:34] Dump 19 initiated: D:\Procdump\devenv.exe_160908_142934.dmp
[14:29:34] Dump 19 writing: Estimated dump file size is 462 MB.
[14:29:35] Dump 19 complete: 463 MB written in 1.5 seconds
[14:29:35] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:35] Dump 20 initiated: D:\Procdump\devenv.exe_160908_142935.dmp
[14:29:36] Dump 20 writing: Estimated dump file size is 462 MB.
[14:29:37] Dump 20 complete: 463 MB written in 1.6 seconds
[14:29:37] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:37] Dump 21 initiated: D:\Procdump\devenv.exe_160908_142937.dmp
[14:29:38] Dump 21 writing: Estimated dump file size is 462 MB.
[14:29:39] Dump 21 complete: 463 MB written in 1.6 seconds
[14:29:39] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:39] Dump 22 initiated: D:\Procdump\devenv.exe_160908_142939.dmp
[14:29:39] Dump 22 writing: Estimated dump file size is 462 MB.
[14:29:40] Dump 22 complete: 463 MB written in 1.6 seconds
[14:29:40] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:40] Dump 23 initiated: D:\Procdump\devenv.exe_160908_142940.dmp
[14:29:41] Dump 23 writing: Estimated dump file size is 462 MB.
[14:29:42] Dump 23 complete: 463 MB written in 1.7 seconds
[14:29:42] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:42] Dump 24 initiated: D:\Procdump\devenv.exe_160908_142942.dmp
[14:29:44] Dump 24 writing: Estimated dump file size is 462 MB.
[14:29:45] Dump 24 complete: 463 MB written in 3.2 seconds
[14:29:45] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:45] Dump 25 initiated: D:\Procdump\devenv.exe_160908_142945.dmp
[14:29:46] Dump 25 writing: Estimated dump file size is 463 MB.
[14:29:48] Dump 25 complete: 463 MB written in 2.4 seconds
[14:29:48] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:48] Dump 26 initiated: D:\Procdump\devenv.exe_160908_142948.dmp
[14:29:49] Dump 26 writing: Estimated dump file size is 463 MB.
[14:29:54] Dump 26 complete: 463 MB written in 5.5 seconds
[14:29:54] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:29:54] Dump 27 initiated: D:\Procdump\devenv.exe_160908_142954.dmp
[14:29:55] Dump 27 writing: Estimated dump file size is 463 MB.
[14:30:04] Dump 27 complete: 463 MB written in 9.4 seconds
[14:30:04] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:04] Dump 28 initiated: D:\Procdump\devenv.exe_160908_143004.dmp
[14:30:04] Dump 28 writing: Estimated dump file size is 463 MB.
[14:30:10] Dump 28 complete: 463 MB written in 6.0 seconds
[14:30:10] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:10] Dump 29 initiated: D:\Procdump\devenv.exe_160908_143010.dmp
[14:30:10] Dump 29 writing: Estimated dump file size is 463 MB.
[14:30:27] Dump 29 complete: 463 MB written in 17.5 seconds
[14:30:27] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:27] Dump 30 initiated: D:\Procdump\devenv.exe_160908_143027.dmp
[14:30:28] Dump 30 writing: Estimated dump file size is 462 MB.
[14:30:36] Dump 30 complete: 463 MB written in 8.5 seconds
[14:30:36] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:36] Dump 31 initiated: D:\Procdump\devenv.exe_160908_143036.dmp
[14:30:36] Dump 31 writing: Estimated dump file size is 462 MB.
[14:30:46] Dump 31 complete: 463 MB written in 10.4 seconds
[14:30:46] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:46] Dump 32 initiated: D:\Procdump\devenv.exe_160908_143046.dmp
[14:30:47] Dump 32 writing: Estimated dump file size is 463 MB.
[14:30:54] Dump 32 complete: 463 MB written in 7.4 seconds
[14:30:54] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:30:54] Dump 33 initiated: D:\Procdump\devenv.exe_160908_143054.dmp
[14:30:54] Dump 33 writing: Estimated dump file size is 463 MB.
[14:31:01] Dump 33 complete: 463 MB written in 7.7 seconds
[14:31:02] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:31:02] Dump 34 initiated: D:\Procdump\devenv.exe_160908_143102.dmp
[14:31:02] Dump 34 writing: Estimated dump file size is 463 MB.
[14:31:10] Dump 34 complete: 463 MB written in 8.0 seconds
[14:31:10] Exception: E0434F4D.System.ArgumentException ("Value does not fall within the expected range.")
[14:31:10] Dump 35 initiated: D:\Procdump\devenv.exe_160908_143110.dmp
[14:31:10] Dump 35 writing: Estimated dump file size is 463 MB.
[14:31:17] Dump 35 complete: 463 MB written in 7.8 seconds
[14:31:18] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:31:18] Dump 36 initiated: D:\Procdump\devenv.exe_160908_143118.dmp
[14:31:19] Dump 36 writing: Estimated dump file size is 463 MB.
[14:31:24] Dump 36 complete: 464 MB written in 5.5 seconds
[14:31:24] Exception: E0434F4D.System.OperationCanceledException ("The operation was canceled.")
[14:31:24] Dump 37 initiated: D:\Procdump\devenv.exe_160908_143124.dmp
[14:31:25] Dump 37 writing: Estimated dump file size is 464 MB.
[14:31:31] Dump 37 complete: 464 MB written in 7.1 seconds
[14:31:31] Exception: E0434F4D.System.InvalidOperationException ("Unexpected false")
[14:31:32] Dump 38 initiated: D:\Procdump\devenv.exe_160908_143131.dmp
[14:31:32] Dump 38 writing: Estimated dump file size is 464 MB.
[14:31:59] Dump 38 complete: 464 MB written in 27.6 seconds
[14:32:00] Exception: E0434F4D.BREAKPOINT
[14:32:00] Dump 39 initiated: D:\Procdump\devenv.exe_160908_143200.dmp
[14:32:00] Dump 39 writing: Estimated dump file size is 464 MB.
[14:32:09] Dump 39 complete: 464 MB written in 9.8 seconds
[14:32:09] Exception: E0434F4D.BREAKPOINT
[14:32:10] Dump 40 initiated: D:\Procdump\devenv.exe_160908_143209.dmp
[14:32:10] Dump 40 writing: Estimated dump file size is 464 MB.
[14:32:17] Dump 40 complete: 464 MB written in 7.2 seconds
[14:32:17] The process has exited.
[14:32:17] Dump count not reached.

```

**Comment by jmarolf** [comment] 2016-10-14 21:26
@wpanja can you get me a virtual machine that this reproduces on?  I can't get this to happen on any of my update 3 VM.

**Comment by jmarolf** [comment] 2016-11-11 04:17
Closing this as I cannot repro with the given solution on RC

**Closed by jmarolf** 2016-11-11 04:17 UTC
Labels: Area-IDE, Bug, Investigation Required

**Comment by nil4** [comment] 2016-12-03 12:01
I am getting this same issue on VS 2015 Enterprise Update 3 with HP Fortify 16.11, during a command-line build (`devenv.com Solution /build /debug`). Here is the event log entry:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32 cookie)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(Object sender, EventArgs e)
   at Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()
   at Microsoft.CodeAnalysis.Workspace.<>c__DisplayClass199_0.<RegisterText>b__0()
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass2_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass6_0`1.<SafeContinueWith>b__0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(System.Object, System.EventArgs)
   at Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()
   at Microsoft.CodeAnalysis.Workspace+<>c__DisplayClass199_0.<RegisterText>b__0()
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass2_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by nil4** [comment] 2016-12-03 12:05
Not sure if related, but earlier in the event log a few WER entries related to Visual studio are found. One with the message TestWindowPackage.Initialize failed with exception *System.ArgumentNullException: Value cannot be null.* (SetSite failed for package [TestWindowPackage]). A few more telemetry parameters are logged, but since this machine is not connected to the internet, I will include them here:
```
Telemetry event 'vs/core/packageloadfailure' properties:
   [VS.Core.PackageLoadFailure.Description] = ''
   [DataModel.Fault.IsSampled] = 'True'
   [DataModel.Type] = 'Fault'
   [DataModel.Fault.Description] = 'End package load [TestWindowPackage]'
   [VS.Core.PackageLoadFailure.HRESULT] = '0x80004003'
   [DataModel.Fault.BucketParam1] = 'devenv.exe'
   [DataModel.Fault.BucketParam2] = '14.0.25420.1'
   [DataModel.Fault.BucketParam3] = ''
   [DataModel.Fault.BucketParam4] = 'vs/core/packageloadfailure'
   [DataModel.Fault.BucketParam5] = '[TestWindowPackage]'
   [DataModel.Fault.BucketParam6] = ''
   [DataModel.Fault.BucketParam7] = ''
   [DataModel.Fault.BucketParam8] = 'CVsPackageMgr::CVsPackageInfo::LogHr'
   [DataModel.Fault.BucketParam9] = '0'
   [DataModel.Fault.BucketParam10] = 'None'
```

**Comment by wpanja** [comment] 2017-01-03 12:43
@jmarolf @Pilchie 

The issue is reproducible in VS 2017 RC as well.
Repro machine Details has been shared in the internal thread.

**Comment by jmarolf** [comment] 2017-01-13 22:18
confirmed fixed by https://github.com/dotnet/roslyn/pull/14783
