### ISSUE TITLE
Can't configure spacing in enums with .editorconfig

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#45781] opened 2020-07-08 14:38 UTC
I configure my `.editorconfig` to warn about IDE0055 formatting issues:

```
# IDE0055: Fix formatting
dotnet_diagnostic.IDE0055.severity = warning
```

However, there doesn't seem to be any spacing option allowing me to say that multiple spaces in enum definitions for the purposes of alignment is not an issue; the following produces a warning, and I don't want it to:

```
private enum HashAlgorithm : int {
    Sha512 = 0,
    Md5    = 1,
}
```

**Comment by jez9999** [comment] 2020-08-10 14:30
Sure wish someone would pick this one up!  Would be easy to implement I think.

**Comment by sharwell** [comment] 2020-08-10 14:42
Duplicate of #38241

**Closed by sharwell** 2020-08-10 14:42 UTC
Labels: Area-IDE, Feature Request, IDE-CodeStyle
