### ISSUE TITLE
Tooltips generated from XML comments should specify the cause of an exception.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51159] opened 2021-02-11 17:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Tooltips-generated-from-XML-comments-sho/1325119)._

---
For instance, if I have this method:

```csharp
/// <summary>
/// Crashes the program.
/// </summary>
/// <exception cref="InvalidOperationException">when the C# compiler doesn't like you. Which is always.</exception>
public object Crash()
{
	throw new InvalidOperationException("The compiler doesn't like you.");
}
```

Then the generated tooltip from the XML comments correctly indicates that `InvalidOperationException` can be thrown, but it is missing the contents of the `<exception>` tag which state when the exception will be thrown. This would be useful information to have when consuming an API, so I can tell what would trigger an exception, which would inform me as to whether I need to catch it and what to do when I do catch it.

---
#### Feedback Bot on 1/31/2021, 10:44 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2021-02-11 17:54
Duplicate of #1515

**Closed by sharwell** 2021-02-11 17:54 UTC
Labels: untriaged
