### ISSUE TITLE
Ctrl+. on a long // comment (or on on of a number of // comment lines) distibutes the comment over multiple lines

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38512] opened 2019-09-05 17:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/689733/ctrl-on-a-long-comment-or-on-on-of-a-number-of-com.html)._

---
Let's say you have:

```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fermentum semper orci. Fusce non diam magna. Vestibulum quis est eget massa suscipit commodo. Integer lacinia ultrices aliquam. Cras tempor lacus malesuada, volutpat sem at, blandit ligula.
```
or
````
// Lorem ipsum dolor sit amet,
// consectetur adipiscing elit. In fermentum semper orci. Fusce non diam magna.
// Vestibulum quis est eget massa suscipit commodo. Integer lacinia ultrices aliquam. Cras tempor lacus malesuada, volutpat sem at, blandit ligula.
````
... and you press Ctrl+.

Two options should be available: &quot;Tidy using //&quot; and &quot;Tidy using /**/&quot;

Both options distribute the comment using .editorconfig to determine the maximum characters per line, resulting in (for example):

````
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
// fermentum semper orci. Fusce non diam magna. Vestibulum quis
// est eget massa suscipit commodo. Integer lacinia ultrices
// aliquam. Cras tempor lacus malesuada, volutpat sem at,
// blandit ligula.
````

---
### Original Comments
(no comments)

**Comment by JoeRobich** [comment] 2019-09-05 17:30
Duplicate of https://github.com/dotnet/roslyn/issues/36069

**Closed by JoeRobich** 2019-09-05 17:30 UTC
