### ISSUE TITLE
GeneratorExecutionContext.ReportDiagnostic prints nothing when DiagnosticSeverity is set to Info in source generator

### ISSUE THREAD

**Issue by AxelHu** [dotnet/roslyn#50574] opened 2021-01-18 02:02 UTC
I'm trying to use .net 5 new feature source generator to generate some stuff before compilation.

GeneratorExecutionContext.ReportDiagnostic prints nothing when DiagnosticSeverity is set to Info, it's fine for Error and Warning. #30637 may be related and the answer there is "By Design".

Can it change now since source generator is available to everyone using .net 5? I do want to print some message when some files are generated, and I don't want to display every message in Error/Warning.

**Comment by Youssef1313** [comment] 2021-01-18 10:44
ReportDiagnostic shouldn't be the correct way to do that. This requires logging API. Possibly duplicate of #50208

**Comment by jaredpar** [comment] 2021-01-22 14:23
> GeneratorExecutionContext.ReportDiagnostic prints nothing when DiagnosticSeverity is set to Info

That behavior is "By Design". The "Info" diagnostic doesn't display by default in MSBuild. Has to be at least severity level Warning to do that. This isn't related to source generators but rather just a function of the compiler.

**Comment by chsienki** [comment] 2021-01-25 18:50
Yes, this is by design of how diagnostics work. #50208 tracks adding a more general logging API for these use cases.

**Closed by chsienki** 2021-01-25 18:50 UTC
Labels: Area-Compilers, New Feature - Source Generators, untriaged

**Comment by HHobeck** [comment] 2024-12-29 12:31
> That behavior is "By Design". The "Info" diagnostic doesn't display by default in MSBuild. Has to be at least severity level Warning to do that. This isn't related to source generators but rather just a function of the compiler.

Hi @jaredpar and @Youssef1313,

Can you please give some more information why this design decision was made? I have the problems to show info messages in the error list explorer when no document is open in Visual Studio (see Link [1]). I'm wondering for what the `DiagnosticSeverity.Hidden` is good for if not for this? In my understand this should make the different whether a info message is shown or not. When I open the dedicated document the info message annotated with `DiagnosticSeverity.Info` or `DiagnosticSeverity.Hidden` are shown. Seems to me more like a bug.

Thank you for your help.

Link[1]: [Why does my C# analyzer not display messages (DiagnosticSeverity.Info)](https://stackoverflow.com/questions/71711488/why-does-my-c-sharp-analyzer-not-display-messages-diagnosticseverity-info)

**Comment by jaredpar** [comment] 2025-01-05 18:31
> Can you please give some more information why this design decision was made?

This is simply [a part of how msbuild][msbuild] recognizes diagnostic messages: only those prefixed with error / warning will be recognized as messages to be displayed. 

> I'm wondering for what the DiagnosticSeverity.Hidden is good for if not for this?

A hidden diagnostic is basically a way for the compiler to communicate information to the compiler host (VS, VS Code, workspaces, etc... ) but not the user. It is a channel for the compiler to communicate items like unnecessary usings, unnecessary references, etc ... Then the host can decide how, or if, it wants to display that to the user.

[msbuild]: https://github.com/dotnet/msbuild/blob/34c4f2bcc50620744da98c36582f71fea97652a1/src/Shared/CanonicalError.cs#L67

> ? I have the problems to show info messages in the error list explorer when no document is open in Visual Studio (see Link [1])

That is more of a question for the IDE than compiler: @CyrusNajmabadi, @jasonmalinowski

**Comment by CyrusNajmabadi** [comment] 2025-01-05 18:41
> That is more of a question for the IDE than compiler: 

These options control how diagnostics work: 

![Image](https://github.com/user-attachments/assets/1f8a6d14-3148-47cb-a752-1b5b8791dbbd)

By default we only show for open documents.  Showing for anything more is not recommended as it is *much* slower and uses *much* more cpu and memory.

**Comment by HHobeck** [comment] 2025-01-19 07:42
@jaredpar and @CyrusNajmabadi Thank you very much for your response. It makes sense. On additional question I would like to ask you because I have implemented this rule and want to ensure that I have done everything right: 

The setting for NSDEPCOP07 is not applying when changing the severity in the .editorconfig. But on the other hand, the setting for NSDEPCOP01 is considered.  Of course, the different is that NSDEPCOP01 is reported on file level and NSDEPCOP07 on project level. Do you have an idea why!?

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/9a54de71-35be-4153-9ad1-894234569eaa" />

Link [1]: https://github.com/realvizu/NsDepCop/blob/a8968e7aa32a5106b5960c5d75ad22d39af8c1f3/source/NsDepCop.Analyzer/RoslynAnalyzer/NsDepCopAnalyzer.cs#L188

**Comment by Youssef1313** [comment] 2025-01-19 08:02
@HHobeck That is by design. EditorConfig applies to files, but your diagnostic doesn't have a location. Did you try a GlobalConfig file instead to see if it works?

**Comment by HHobeck** [comment] 2025-01-19 08:15
> [@HHobeck](https://github.com/HHobeck) That is by design. EditorConfig applies to files, but your diagnostic doesn't have a location. Did you try a [GlobalConfig](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig) file instead to see if it works?

I have tested it right now and it works with global configuration files. @Youssef1313 I'm happy, thank you very much for your support.

<img width="1227" alt="Image" src="https://github.com/user-attachments/assets/61df4636-578b-43cf-96fd-5c46f2bd74fb" />
