### ISSUE TITLE
"Rename file to match type" doesn't work in .NET Standard

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#34917] opened 2019-04-10 21:58 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.1.0 Preview 1.0 [28809.33.d16.1]
VisualStudio.16.IntPreview/16.1.0-pre.1.0+28809.33.d16.1

**Steps to Reproduce**:

1. Create a .NET Standard project
2. Open Class1.cs
3. Change type identitifer to Class2.cs

**Expected Behavior**:

In .NET Framework (legacy project system) two fixers show up, one to rename the file to match the type name and one to rename the type to match the filename:

![image](https://user-images.githubusercontent.com/5169960/55916253-b5881480-5ba0-11e9-9d04-b47e62390f64.png)

**Actual Behavior**:

In .NET Standard (CPS) only the option to rename the type to match the filename shows up:

![image](https://user-images.githubusercontent.com/5169960/55916257-bae55f00-5ba0-11e9-86e1-47c62d2014e2.png)

Not sure that's a Roslyn bug or a CPS bug.

**Comment by terrajobst** [comment] 2019-04-10 21:59
@jinujoseph @davkean

**Comment by Pilchie** [comment] 2019-04-10 22:08
Partially dependent on https://github.com/dotnet/project-system/issues/2544

**Comment by trinhpapa** [comment] 2019-07-06 03:11
I have encountered a similar problem, and have long used visual studio 2017 for work. When will this error be fixed?

**Comment by petterek** [comment] 2020-02-14 09:46
As far as I can understand this is still an issue.. WHY!!!!

**Comment by sharwell** [comment] 2020-02-14 15:07
Duplicate of #24560

**Closed by sharwell** 2020-02-14 15:07 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, help wanted
