### ISSUE TITLE
Cannot load Microsoft.CodeAnalyzers

### ISSUE THREAD

**Issue by dansiegel** [dotnet/roslyn#54942] opened 2021-07-19 19:51 UTC
**Version Used**: 
3.11.0-3-final

**Steps to Reproduce**:

Note that I only began having these issues after updating.

I currently have .NET 6 preview 6 installed and am running the latest releases of VS stable/preview & VS 2022

1. Create a Generator
```cs
public class MyGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        Debugger.Launch();
    }
}
```
2. Reference the Generator Project via a ProjectReference from another project in the same solution.
```xml
<ItemGroup>
  <ProjectReference Include="..\MyGeneratorProject\MyGeneratorProject.csproj"
                    OutputItemType="Analyzer" 
                    ReferenceOutputAssembly="false" />
</ItemGroup>
```
3. Build the other project

**Expected Behavior**:

Generator from local Analyzer project should generate code in another project where it is referenced with a ProjectReference.

**Actual Behavior**:

No source code is generated. A build warning shows the Generator could not be created.

```
An instance of the analyzer MyProject.MyGenerator cannot be created from {path to dll}: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31b3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

**Comment by dansiegel** [comment] 2021-07-24 02:58
It actually seems this is broader than my own generators as I am seeing this with the basic analyzers that get loaded...

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.UseSystemHashCode.UseSystemHashCodeDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	MyProject (netstandard2.0)	C:\repos\MyProject\src\MyProject\CSC	1	N/A

```

**Comment by edwin-alvarez** [comment] 2021-08-28 05:36
Having the same problem.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by Youssef1313** [comment] 2021-08-28 06:41
3.11 works with VS 16.11

**Comment by jmarolf** [comment] 2021-09-08 21:32
duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5458 we need to let the user know that they are building with a mis-match of the compiler between the SDK and Visual Studio

**Closed by jmarolf** 2021-09-08 21:32 UTC
Labels: Bug, Area-Analyzers
