### ISSUE TITLE
A Source Generator should add code to the compilation of a WPF application when one of the app's XAML files is declaring an app-local namespace

### ISSUE THREAD

**Issue by dev-mano** [dotnet/roslyn#49658] opened 2020-11-29 20:11 UTC
**Versions Used**: 

VS versions 16.8.2 and 16.9.0 Preview 1.0
Microsoft.CodeAnalysis.Analyzers version 3.3.1
Microsoft.CodeAnalysis.CSharp.Workspaces version 3.8.0

**Steps to Reproduce**:

1. Create a new project using the 'WPF App (.NET)' template in VS
2. Add a source generator to the project as described in the [Source Generators Cookbook](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md)
3. Manually add code to the app that depends on code generated by the source generator in order to compile correctly, e.g. by implementing an interface like INotifyPropertyChanged, as shown in the Source Generators Cookbook examples.
4. Compile the project.

**Expected Behavior**:

The source generator adds code to the compilation and the build succeeds.

**Actual Behavior**:

The build emits error messages due to missing code that the source generator was supposed to generate, but didn't.
The build will succeed though if the following, not used 'local' namespace declaration is removed from app.xaml:
`	xmlns:local="clr-namespace:NameOfWpfApp"`

The behavior is the same for these flavors of .NET used by the test app: .NET Core 3.1, .NET 5, .NET Framework 4.7.2.

**Comment by jaredpar** [comment] 2020-12-01 13:07
@chsienki is the same WPF issue that we are fixing for 16.9?

**Comment by chsienki** [comment] 2020-12-02 22:33
Yes, this is the same issue as https://github.com/dotnet/wpf/issues/3404 

This isn't a roslyn issue, but a WPF one. Closing as a dupe of the above issue.

**Comment by chsienki** [comment] 2020-12-02 22:35
Yes. Dupe of

**Closed** 2020-12-02 22:35 UTC
Labels: Area-Compilers, untriaged
