### ISSUE TITLE
Locals should be in scope on closing brace of async methods

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2336] opened 2015-04-28 18:57 UTC
![code](https://cloud.githubusercontent.com/assets/6464209/7377822/adc1239c-ed9d-11e4-8391-dbe4b2b9b051.PNG)

**RESULTS**
![actual](https://cloud.githubusercontent.com/assets/6464209/7377831/ba6d2118-ed9d-11e4-95a0-9e53139db34b.PNG)

**EXPECTED**
![expected](https://cloud.githubusercontent.com/assets/6464209/7377839/c496c644-ed9d-11e4-9c64-6ab7d26001e9.PNG)

**Comment by KevinH-MS** [comment] 2015-04-28 18:58
This is not a regression from previous versions of the compiler/debugger, but it would be good to make async lambdas work the same as normal methods.

**Comment by AdamSpeight2008** [comment] 2015-04-28 19:14
Isn't it defining the end of the scope? If you move the cursor one char to the left you should still see the local `y := 42`

**Comment by KevinH-MS** [comment] 2015-04-28 19:21
Yes, for normal methods and lambdas, the locals are considered "in scope" when the IP in the debugger is on the closing curly brace of the method body (Note: left/right of the brace is not significant here, because you only have the ability to set a breakpoint with a "line-level" granularity here).

**Comment by ManishJayaswal** [comment] 2015-04-30 20:38
this is a dupe of internal bug 1154113

**Comment by amcasey** [comment] 2015-04-30 20:51
According to the internal bug, this happens for non-lambda async methods as well.

**Comment by amcasey** [comment] 2015-05-18 04:18
The custom debug info for the local indicates that its scope corresponds to the try-block of the synthesized try-catch in the MoveNext method.  However, the final sequence point (i.e. for the closing brace) is on the first statement after the try-catch.

My intuition is that the scope is correct and the sequence point should be moved.  Thoughts, @tmat?

**Comment by amcasey** [comment] 2015-05-18 04:21
Dev12 has the sequence point in the same place and scopes the local to the entire MoveNext method (rather than the try-block), so I guess my intuition was wrong. :)

**Comment by amcasey** [comment] 2015-05-18 04:45
The scope and sequence point appear to be the same in VB, but the locals appear when stopped on ```End Function```.  Maybe there's code to compensate for this (apparent) bug?

**Comment by amcasey** [comment] 2015-05-18 17:38
Modifying the scopes in ```ScopeInfo.GetHoistedLocalScopes``` seems impractical since there's no distinction (that I can see) between real try-catches and synthesized ones.  Maybe the locals should be associated with different scopes before we even get there?

**Comment by amcasey** [comment] 2015-05-18 21:48
I made a quick and dirty change that promotes the outermost ```BoundStateMachineScope``` to the method level and confirmed that it resolves the problem in the EE.  Now I need to find a clean way to make that happen without rewriting a just-constructed tree (or depending on its exact shape).

**Closed** 2015-05-19 18:46 UTC
Labels: Area-Interactive, Bug, Interactive-Debugging

**Comment by amcasey** [comment] 2015-05-19 19:31
@KevinH-MS Can you please verify?
