### ISSUE TITLE
.NET Core 2.0: BC35000: Requested operation is not available -- For To loop with Object counter.

### ISSUE THREAD

**Issue by Imisnew2** [dotnet/roslyn#22227] opened 2017-09-20 18:43 UTC
**Version Used**: 
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Steps to Reproduce**:
mkdir test
cd test
dotnet new console --language=vb
dotnet add package Microsoft.VisualBasic
(edit Program.vb to contain the code below)
dotnet build

== Program.vb ==
```
Imports System

Module Program
    Sub Main(args As String())
        For counter As Object = 1 To 10 Step 1.5
        Next
    End Sub
End Module
```

**Expected Behavior**:
Build succeeds

**Actual Behavior**:
Program.vb(5,9): error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.ObjectFlowControl+ForLoopControl.ForLoopInitObj' is not defined.
Program.vb(5,9): error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.ObjectFlowControl+ForLoopControl.ForNextCheckObj' is not defined.

**Additional Notes**:
I've added '--verbosity d' to dotnet build and verified that the 'RunVbc.sh' script gets the Microsoft.VisualBasic.dll passed to it. I've also verified that Microsoft.VisualBasic.dll contains the symbol with that name. Perhaps I'm doing something wrong? Note that I can use other methods from Microsoft.VisualBasic like 'ChrW'. I can't find any answers elsewhere, so posting it here.

**Comment by jcouv** [comment] 2017-09-22 16:14
From discussion with Jared, adding the package should not be needed.

When I repro without the `Microsoft.VisualBasic` package, I see that the `.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\Microsoft.VisualBasic.dll` assembly is properly referenced and as far as I can tell it contains the required API. 
I'll debug the compiler to see why that API was rejected.

**Comment by jcouv** [comment] 2017-09-22 20:20
Looking at the command-line options to `vbc.exe`, there is not only a reference to `.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\Microsoft.VisualBasic.dll`, there is also a `/vbruntime*` flag.
That indicates that the VB core runtime will be used (so supporting types for operations that require late binding, like object loop, are not included).

When I run the same command without `/vbruntime*`, I get some errors about some other missing types (see below). If I add `/define:"_mytype=""empty"""`, then the compilation succeeds.

I mentioned this to @AnthonyDGreen and it is a known issue that he is driving. I'll let him reply with more information on how to work around.

```
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.ApplicationServices.ApplicationBase' is not defined.
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.Devices.Computer' is not defined.
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.ApplicationServices.User' is not defined.
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.ApplicationServices.User' is not defined.
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.MyGroupCollection' is not defined.
```

FYI @AlekseyTs (thanks for the help too)

**Comment by AnthonyDGreen** [comment] 2017-09-22 20:49
@Imisnew2,

Thanks for reporting this. It looks like a consequence of the decision to support only the embedded VB runtime (the most portable VB runtime) for v1 of .NET Core support. The version of the VB runtime that is included in the .NET Framework is monolithic and has a lot of dependencies on the full framework and Windows. We're investigating now how to refactor the desktop VB runtime in such a way as to enable developers such as yourself to make more granular tradeoffs between added functionality and reduced portability. Hopefully I'll have more to announce on that front within the next month or so. In the meantime can you confirm whether you found this issue while migrating an existing code base or an accident of exploratory testing?

**Comment by Imisnew2** [comment] 2017-12-19 22:17
@AnthonyDGreen I found this while writing some tests, so it wasn't in actual code. Thanks for looking into this, though.

**Comment by jcouv** [comment] 2018-02-20 22:34
Tagging @KathleenDollard

**Comment by jaredpar** [comment] 2018-09-05 15:45
This is a duplicate of #28044. That uber bug covers this and other runtime features missing from .NET Core version of MS.VB.dll.

**Closed by jaredpar** 2018-09-05 15:45 UTC
Labels: Area-Compilers, Language-VB
