### ISSUE TITLE
Automatic completion of ToString override should make return non-nullable

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#34604] opened 2019-03-29 22:54 UTC
Prerequsite: https://github.com/dotnet/roslyn/issues/23268

See long discussion on https://github.com/dotnet/coreclr/pull/23466

It appears System.Object will return `string?`. If that decision is changed, this can be closed.

Part of the rationale of that decision is that subclasses can override and indicate that they do not return null. We should encourage new subclasses to do that by having an appropriate completion.

**Steps to Reproduce**:

1. Create a new project in VS
2. Enable nullable reference types
3. Reference a corefx where `Object.ToString()` returns `string?
4. Create a new type in the project and have it complete a ToString override

``` C#
class Foo
{
   // Put cursor here and type `override ToString [TAB]`
}
````

**Expected Behavior**:

The new override is generated with signature `public override string ToString()`

**Actual Behavior**:

The new override is generated with signature `public override string? ToString()`

**Comment by jaredpar** [comment] 2019-03-29 23:20
Dupe of #30317

**Closed by jaredpar** 2019-03-29 23:20 UTC
