### ISSUE TITLE
Don't restrict Peek Definition to showing only method signatures

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#61401] opened 2022-05-19 06:47 UTC
Peek Definition is currently hard coded to show signatures only, so it will never show Source Link, Embedded or Decompiled source. This makes the experience not inline with, and worse than, Go to Definition.

---
_Originally posted by @Varorbc in https://github.com/dotnet/roslyn/issues/61398#issuecomment-1131264689_
Why is the effect of peek definition and go to definitions different?

![image](https://user-images.githubusercontent.com/5714438/169224571-05ac96c2-91f2-4132-97a4-26a4cf3e8e49.png)
![image](https://user-images.githubusercontent.com/5714438/169224252-bed1ec2c-0566-489b-858c-b0895564e318.png)

**Comment by sharwell** [comment] 2022-05-19 19:27
Duplicate of #23480

**Closed by sharwell** 2022-05-19 19:27 UTC
Labels: Area-IDE, Need Design Review, Navigation-SourceLink

**Comment by davidwengier** [comment] 2022-05-19 23:20
Thanks @sharwell!

Wish I'd known that existed before, I reckon I've made at least 3 or 4 separate commits to preserve the current behaviour, thinking it was desired.
