### ISSUE TITLE
Freshly created editorconfig gets duplicated rules added when file is open in VS

### ISSUE THREAD

**Issue by ltlombardi** [dotnet/roslyn#72382] opened 2024-03-04 15:56 UTC
**Version Used**: 
Visual studio community Version 17.9.0
**Steps to Reproduce**:

1. Add editorconfig to VS. It gets added with default rules. Or use the one I provide
2. Click on editorconfig file to edit it, and VS opens the GUI form editor, and immediately edits the file, adding duplicated rules

![image](https://github.com/dotnet/roslyn/assets/898124/6ccd2d4b-aff2-4b12-9cef-fd7118073e6e)
![image](https://github.com/dotnet/roslyn/assets/898124/b27ecf00-8282-451b-af2d-04ab73a4dcb7)
[editorconfig.zip](https://github.com/dotnet/roslyn/files/14483984/editorconfig.zip)
**Expected Behavior**:
VS is adding duplicated rules to the file
**Actual Behavior**:
No duplicated rules is added. Nothing should be added or changed without user input

**Comment by sharwell** [comment] 2024-03-06 17:37
Duplicate of #59325

**Closed by sharwell** 2024-03-06 17:37 UTC
Labels: Area-IDE, untriaged
