### ISSUE TITLE
String Interpolation highlight issue

### ISSUE THREAD

**Issue by deepumi** [dotnet/roslyn#17108] opened 2017-02-13 13:37 UTC
**Version Used:**
VS 2017, VS 2015
C# 6.0 

String interpolation does not highlight argument(s) if a string contains colon character ":". Please refer the screenshot for more info.

**Actual Behavior**

![image](https://cloud.githubusercontent.com/assets/554039/22885405/4a8eef22-f1c7-11e6-8689-cb4584217a4f.png)

**Expected Behavior**

![image](https://cloud.githubusercontent.com/assets/554039/22885433/770ced9c-f1c7-11e6-976a-7534098e4508.png)

**Comment by jnm2** [comment] 2017-02-13 16:15
This has bothered me for ages. :') `{key}` should keep the underline (blue if possible) but be white.

**Comment by 0xd4d** [comment] 2017-02-13 17:51
It happens because the text editor has a URL classifier that uses a color that has a higher priority than most other colors. It has no idea about any programming languages and just highlights anything that looks like a link.

A workaround if you don't like to see any highlighted links: disable "Enable single-click URL navigation" in Text Editor / C# / General.

**Comment by deepumi** [comment] 2017-02-13 17:56
@0xd4d I am talking about the argument highlighting issue not the URL.

**Comment by 0xd4d** [comment] 2017-02-13 17:58
@deepumi it's becuase of the URL classifier that the arguments are blue. Its color has higher priority than the other colors you see above. End result: blue text.

**Comment by YotaXP** [comment] 2017-02-15 17:51
Perhaps, but `{key}` should not be interpreted as being part of the URL itself when inside an interpolated string, as any attempt to navigate to it will almost certainly fail.

**Comment by Pilchie** [comment] 2017-02-15 18:19
I have internal bug 172884 tracking this as well, and @dpugh suggested:

> •	Import your own tagger provider instances and find a IUrlTagger with metadata that matches the original tagger (content type == text, tag type == IUrlTag, name == “UrlTagger”). Use this provider to create an instance of the original tagger when you create your specialized tagger.
•	In your tagger implementation, pass any GetTags() call on to the original tagger.
•	Examine the returned tags and exclude any that contain a $.

**Comment by miloush** [comment] 2017-02-15 18:30
Or provide C#/VB aware URL tagger and deprecate the language-agnostic one? Perhaps Roslyn could opt out of it completely rather than going through the results and removing them afterwards, that sounds a bit like waste of user's time to me.

**Comment by deepumi** [comment] 2017-02-15 18:33
Can't  Roslyn ignore colon character  **":"**?

**Comment by miloush** [comment] 2017-02-15 18:35
@deepumi Roslyn is not doing it currently at all, it's a global Visual Studio feature.

**Comment by deepumi** [comment] 2017-02-15 18:36
@miloush Oh! got it. Thank you.

**Comment by sharwell** [comment] 2019-05-22 18:26
Duplicate of #5863

**Closed by sharwell** 2019-05-22 18:26 UTC
Labels: Area-IDE, Bug
