### ISSUE TITLE
CSharpUpgradeProjectCodeFixProvider crashed when upgrading a .Net Core project

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#19712] opened 2017-05-22 23:37 UTC
**Version Used**: 
vs preview 26510.0
roslyn 2.3.0.6170310

**Steps to Reproduce**:

1. Create a .Net Core project
2. Add code that uses C# 7.1 features, e.g.
```
        public ImmutableArray<int> Numbers => default;
```
3. Use quick action to upgrade this project to c# langeuage version latest (or 7.1)

**Expected Behavior**:
Upgrade succeed

**Actual Behavior**:
Crash with following stack trace
```
System.AggregateException : One or more errors occurred. ---> Unable to cast object of type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectConfigProperties' to type 'VSLangProj80.CSharpProjectConfigurationProperties3'.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.InvalidCastException : Unable to cast object of type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectConfigProperties' to type 'VSLangProj80.CSharpProjectConfigurationProperties3'.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyParseOptionsChanged(ProjectId projectId,ParseOptions options)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

**Comment by Pilchie** [comment] 2017-05-23 15:24
Dupe of https://github.com/dotnet/project-system/issues/2137.

**Closed** 2017-05-23 16:28 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
