### ISSUE TITLE
Editorconfig: dotnet_sort_system_directives_first not working

### ISSUE THREAD

**Issue by GerjanOnline** [dotnet/roslyn#17658] opened 2017-03-09 09:53 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Productivity Power Tools 2017 

![image](https://cloud.githubusercontent.com/assets/1153419/23744700/89a28b6e-04b5-11e7-9ec4-06b3e3c065ee.png)

**Steps to Reproduce**:

1.  Add .editorconfig file to solution (which creates a Solution folder with .editorconfig file in it)
2.  Set the following:
```
# Dotnet code style settings:
[*.{cs,vb}]
# Sort using and Import directives with System.* appearing first
dotnet_sort_system_directives_first                        = true
```
3.  Close all editors / files
4.  Put a System using as a last using statement
5.  Press CTRL + K, CTRL + D and CTRL + S (Format and Remove/Sort usings on Save)

**Expected Behavior**:
The usings should be sorted, with the System directives as first

**Actual Behavior**:
It is not sorting the usings. It seems it is respecting the following settings:

![image](https://cloud.githubusercontent.com/assets/1153419/23744850/249068c6-04b6-11e7-9e89-33ba98dcdc7d.png)

**Related** 
In Visual Studio there is also an Code Style node in C# > Options. 

![image](https://cloud.githubusercontent.com/assets/1153419/23744501/c117c826-04b4-11e7-8771-9032044dbd97.png)

1. Where are these styles stored?
2. How does this relate to my .editorconfig file? Will it be synchronized?

According to me, its not. This makes it really confusing. Same for C# > Tabs and C# > Advanced settings, that seems not synchronized

**Comment by Pilchie** [comment] 2017-03-09 17:20
Tagging @kuhlenh, @olegtk, @jasonmalinowski, @markw-t

The settings in Tools\Options should be saved to your VS account, and roamed.  The overall design of EditorConfig is a supersedes model though, so if you have an editorconfig file, it should honored *instead* of the values in Tools\Options.

In this case, when you open a .cs file, do you see a message in the status bar at the bottom indicating that your preferences are being overridden?  Also, what exact directory is the .editorconfig created in relative to the .cs file?

**Comment by markw-t** [comment] 2017-03-09 17:30
As @Pilchie notes,  the design of .editorconfig is that it supersedes your local tools\options values, because your codebase's conventions (as expressed in the file) are of a higher priority than your personal preferences. You should see a notification in the status bar whenever you open a file under the control of .editorconfig, if the .editorconfig file applies. One further thing to note is that at present, .editorconfig file changes to convention won't show up in files you have open at the time you make a change to the .editorconfig; you need to close and reopen those files to see the new setting take effect.

**Comment by kuhlenh** [comment] 2017-03-09 17:35
@Pilchie: @GerjanOnline has found a bug that is for Sort System Directives first only. That specific setting doesn't get applied for some reason. I thought I had filed that bug already, but I can't seem to find it...

**Comment by GerjanOnline** [comment] 2017-03-10 09:46
Thanks @kuhlenh

**Comment by stevenaw** [comment] 2019-03-17 12:28
Perhaps someone else could confirm, but this seemed to work as expected for me recently, when configuring a project and using VS 2017 Community Edition v15.9.7

**Comment by sharwell** [comment] 2019-03-17 13:58
This should be fixed in 15.8 and newer.

**Closed by sharwell** 2019-03-17 13:58 UTC
Labels: Area-IDE, Bug

**Comment by nevinvalsaraj** [comment] 2019-09-04 12:36
I am facing the exact same issue that @GerjanOnline faced with `dotnet_sort_system_directives_first = true` rule. 

However I have some additional observations:
- Run Default Code Cleanup(Ctrl+K, Ctrl+E), behavior is correctly superseded by '.editorconfig' when different from the value set in Tools->Option->TextEditor-> C# -> Advanced -> "Place 'System' directives first when sorting usings".
- Format Document (Ctrl+K, Ctrl+D) doesn't seem to respect this rule (i.e move System directives above automatically) set in either `.editorconfig` or in Options or both.

@sharwell I see that this issue was closed with `Resolution-Not Reproducible` tag. If this issue has been identified and solved since, kindly help me figure out where I'm wrong / re-open the issue otherwise - I'll be happy to provide more details.

**Comment by jasonmalinowski** [comment] 2019-09-04 17:55
@nevinvalsaraj: which version of Visual Studio are you running? Feel free to open a new issue so we can debug yours -- there's enough complexity to how .editorconfigs get processed that any number of things can go wrong but cause the same symptoms.

**Comment by nevinvalsaraj** [comment] 2019-09-05 07:26
@jasonmalinowski I'm using VS 2019 Version 16.2.3
Sure, I'll go ahead and open a new one and reference this issue.
