### ISSUE TITLE
Unexpected result with string interpolation

### ISSUE THREAD

**Issue by jhgbrt** [dotnet/roslyn#56061] opened 2021-09-01 12:32 UTC
**Version Used**: 
dotnet 6.0.100-preview.7.21379.14
C# 10

**Steps to Reproduce**:
Compile and run the console program below. When compiled as a net6 console app in VS2022 preview 3.1, it produces an unexpected result 

var output = $"FOO {nameof(R)}  BAR " + $" {f(nameof(R))} BAZ ";
Console.WriteLine(output);
string f(string s) => s;
public class R
{
}

**Expected Behavior**:
Expected output:  "FOO R BAZ R BAR"

**Actual Behavior**:
actual  output:  "BAR RFOO  BAZ R"

**Comment by svick** [comment] 2021-09-01 12:44
This is a duplicate of https://github.com/dotnet/roslyn/issues/55461. The problem has already been fixed, and you should see the fix once preview 4 is released.

**Closed by svick** 2021-09-01 12:44 UTC
Labels: Area-Compilers, untriaged

**Comment by jhgbrt** [comment] 2021-09-01 13:11
looks like it's already fixed in current rc2 ( 6.0.100-rc.2.21451.14)

**Comment by jhgbrt** [comment] 2021-09-01 13:11
> This is a duplicate of #55461. The problem has already been fixed, and you should see the fix once preview 4 is released.

Indeed, verified with the nightly build of rc2.
