### ISSUE TITLE
C# Intellisense suggest symbols for #define and related directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46601] opened 2020-08-06 21:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1132014/c-intellisense-suggest-symbols-for-define-and-rela.html)._

---
`#define` (and `#undef`) in C# can only take after them a single token which must elsewhere in the file be used as an argument to `#if`/`#elif` somewhere in the same file to be meaningful, so those tokens could be suggested when writing those directives. Similarly `#if`/`#elif` could have the tokens referenced by `#define`/`#undef` (or the project file) as suggestions.

---
#### Feedback Bot on 7/31/2020, 02:41 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-08-06 22:51
Duplicate of #11499

**Closed by sharwell** 2020-08-06 22:51 UTC
