### ISSUE TITLE
Improve error recovery for `partial file class`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62434] opened 2022-07-06 20:07 UTC
Swapping `partial` and `file` ordering should produce error CS0267: The 'partial' modifier can only appear immediately before 'class', 'record', 'struct', 'interface', or a method return type.

Currently, `partial file class C { }` produces the following:

```
error CS1002: ; expected
error CS0246: The type or namespace name 'partial' could not be found (are you missing a using directive or an assembly reference?)

```

**Comment by RikkiGibson** [comment] 2022-07-07 00:37
See #61025

**Comment by jcouv** [comment] 2022-07-07 16:46
Closing as duplicate of https://github.com/dotnet/roslyn/issues/61025

**Closed by jcouv** 2022-07-07 16:46 UTC
Labels: Area-Compilers, untriaged
