### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain crash in Visual Studio Update 1

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#10252] opened 2016-04-01 17:19 UTC
**Version Used**: 
Visual Studio 14.0.24720.00

**Steps to Reproduce**:

1. Open Visual Studio
2. Open Compilers.sln from the Roslyn repository

**Expected Behavior**:

Roslyn.sln should open

**Actual Behavior**:

```
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>
System.IndexOutOfRangeException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Index was outside the bounds of the array.</Message><StackTrace>   
at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.Lookup(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupBasicName(LookupResult lookupResult, IdentifierNameSyntax basicNameSyntax, Binder binder, DiagnosticBag diagBag, Boolean&amp;amp; reportedAnError)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupTypeOrNamespaceSyntax(LookupResult lookupResult, TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean&amp;amp; reportedAnError, Boolean unwrapAliases, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeFieldType(ModifiedIdentifierSyntax modifiedIdentifierSyntax, Binder binder, DiagnosticBag diagnostics, Boolean isConst, Boolean isWithEvents, Boolean ignoreTypeSyntaxDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.GetDeclaredType(DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeType(DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.get_Type()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFieldSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-0._Lambda$__1(NamespaceOrTypeSymbol typeOrNamespace)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.VisitTypesAndNamespacesWithin(NamespaceOrTypeSymbol ns, Action`1 visitor, ConcurrentStack`1 tasks, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetAllDeclarationErrors(CancellationToken cancellationToken, Boolean&amp;amp; hasExtensionMethods)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.GetAllDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyImage.Create(ITemporaryStorageService service, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(Solution solution, ProjectReference projectReference, Compilation finalCompilation, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.&amp;lt;GetMetadataOnlyImageReferenceAsync&amp;gt;d__31.MoveNext()</StackTrace><ExceptionString>System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.Lookup(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, HashSet`1&amp;amp; useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupBasicName(LookupResult lookupResult, IdentifierNameSyntax basicNameSyntax, Binder binder, DiagnosticBag diagBag, Boolean&amp;amp; reportedAnError)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.LookupTypeOrNamespaceSyntax(LookupResult lookupResult, TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean&amp;amp; reportedAnError, Boolean unwrapAliases, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(TypeSyntax typeSyntax, Binder binder, DiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeFieldType(ModifiedIdentifierSyntax modifiedIdentifierSyntax, Binder binder, DiagnosticBag diagnostics, Boolean isConst, Boolean isWithEvents, Boolean ignoreTypeSyntaxDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.GetDeclaredType(DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.ComputeType(DiagnosticBag diagBag)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberFieldSymbol.get_Type()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFieldSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-0._Lambda$__1(NamespaceOrTypeSymbol typeOrNamespace)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.VisitTypesAndNamespacesWithin(NamespaceOrTypeSymbol ns, Action`1 visitor, ConcurrentStack`1 tasks, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetAllDeclarationErrors(CancellationToken cancellationToken, Boolean&amp;amp; hasExtensionMethods)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.GetAllDeclarationErrors(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyImage.Create(ITemporaryStorageService service, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(Solution solution, ProjectReference projectReference, Compilation finalCompilation, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.&amp;lt;GetMetadataOnlyImageReferenceAsync&amp;gt;d__31.MoveNext()</ExceptionString></Exception></TraceRecord>
```

**Comment by TyOverby** [comment] 2016-04-01 18:13
Info from modules window
	
```
Microsoft.CodeAnalysis.CSharp.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.CSharp.dll	Yes	No	Skipped loading symbols.		278	1.01.0.51109	11/9/2015 5:23 PM	22BE0000-23657000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.CSharp.dll	C:\Users\tyoverby\.nuget\packages\Microsoft.Net.Compilers\1.2.0-rc\tools\Microsoft.CodeAnalysis.CSharp.dll	Yes	No	Skipped loading symbols.		284	1.02.0.60220	7/1/2067 1:43 PM	23A60000-23E5C000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll	Yes	No	Skipped loading symbols.		279	1.01.0.51109	11/9/2015 5:25 PM	17A30000-17AD3000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.CSharp.Features.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.CSharp.Features.dll	Yes	No	Skipped loading symbols.		300	1.01.0.51109	11/9/2015 5:23 PM	28CA0000-28DF1000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.CSharp.Workspaces.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.CSharp.Workspaces.dll	Yes	No	Skipped loading symbols.		280	1.01.0.51109	11/9/2015 5:23 PM	17AE0000-17C4E000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.dll	Yes	No	Skipped loading symbols.		270	1.01.0.51109	11/9/2015 5:22 PM	22490000-22BDD000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.dll	C:\Users\tyoverby\.nuget\packages\Microsoft.Net.Compilers\1.2.0-rc\tools\Microsoft.CodeAnalysis.dll	Yes	No	Skipped loading symbols.		285	1.02.0.60220	10/29/2085 7:56 PM	23850000-23A3C000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.EditorFeatures.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.EditorFeatures.dll	Yes	No	Skipped loading symbols.		140	1.01.0.51109	11/9/2015 5:23 PM	12E30000-131FA000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.EditorFeatures.Text.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.EditorFeatures.Text.dll	Yes	No	Skipped loading symbols.		292	1.01.0.51109	11/9/2015 5:23 PM	282A0000-282BB000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.Features.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.Features.dll	Yes	No	Skipped loading symbols.		143	1.01.0.51109	11/9/2015 5:23 PM	13B70000-13F62000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.VisualBasic.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.VisualBasic.dll	Yes	No	Skipped loading symbols.		291	1.01.0.51109	11/9/2015 5:24 PM	26260000-26E82000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.dll	Yes	No	Skipped loading symbols.		308	1.01.0.51109	11/9/2015 5:25 PM	0C9F0000-0CAB0000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.VisualBasic.Features.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.VisualBasic.Features.dll	Yes	No	Skipped loading symbols.		306	1.01.0.51109	11/9/2015 5:24 PM	24DE0000-24F88000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll	Yes	No	Skipped loading symbols.		293	1.01.0.51109	11/9/2015 5:24 PM	294F0000-2968B000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.Workspaces.Desktop.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.Workspaces.Desktop.dll	Yes	No	Skipped loading symbols.		276	1.01.0.51109	11/9/2015 5:22 PM	17870000-178CA000	[5404] devenv.exe	[1] DefaultDomain	
	Microsoft.CodeAnalysis.Workspaces.dll	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.Workspaces.dll	Yes	No	Skipped loading symbols.		142	1.01.0.51109	11/9/2015 5:22 PM	13550000-13B6D000	[5404] devenv.exe	[1] DefaultDomain	

```

**Comment by TyOverby** [comment] 2016-04-01 18:13
Looks like a dupe of https://github.com/dotnet/roslyn/issues/10211

**Comment by jaredpar** [comment] 2016-04-01 22:11
Confirmed this on my machine which has a vanilla update 1 installation:

- Sync to https://github.com/dotnet/roslyn/commit/6ac83f31f550f3766630144449ce92fdd015dfad
- Open Compilers.sln
- Wait

Eventually it will crash with the stack that @TyOverby  provided.

**Comment by jaredpar** [comment] 2016-04-04 15:08
Marking as dupe and letting #10211 be the primary.

**Closed by jaredpar** 2016-04-04 15:08 UTC
