### ISSUE TITLE
Incorrect behavior with newline with comments

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#16933] opened 2017-02-03 21:15 UTC
**Version Used**: 15.0.0-RC.3+26127.0

**Steps to Reproduce**:

1. Paste following code in VS.
```CSharp
public class C
{
    private void Method()
    {
        if (true)
        {
            //Press Enter Here Twice->
            //var stronglyTypedHandlers = from handler in _commandHandlers
            //                            where handler is ICommandHandler<T>
            //                            where handler.Metadata.ContentTypes.Any(contentType.IsOfType)
            //                            select handler.Value as ICommandHandler<T>;
        }
    }
}
```

2. Place caret at end of first comment line
3. Press Enter twice
4. The first enter is handled correctly, the second is not.

![image](https://gyazo.com/b6ce961f19833c1bf98149dc981850e0.gif)

**Comment by JoshVarty** [comment] 2017-02-03 21:16
Just a note: This issue is not present in TextMate grammars for C#.

I suspect this is related to the changes we made for smart indentation.

**Comment by Pilchie** [comment] 2017-02-07 00:47
Duplicate of https://github.com/dotnet/roslyn/issues/3321.

**Closed by Pilchie** 2017-02-07 00:47 UTC
Labels: Area-IDE

**Comment by JoshVarty** [comment] 2017-02-07 01:06
FWIW the behavior here is the opposite of #3321 (Although the underling bug may be the same)

#3321 insert 4 extra spaces.
This one is missing 4 spaces.
