### ISSUE TITLE
Suppress Warning CS6800 when the System Type.GetType(..) method's parameter throwOnError (bool) contains a true value

### ISSUE THREAD

**Issue by johndkane** [dotnet/roslyn#66025] opened 2022-12-15 01:13 UTC
### The Issue

The issue is the [System.Type.GetType](https://learn.microsoft.com/en-us/dotnet/api/system.type.gettype?view=net-7.0#system-type-gettype(system-string-system-boolean)) method flags nullability warning `CS8600 - Converting null literal or possible null value to non-nullable type.` when the `throwOnError: bool ` parameter is set to `true` to throw an exception when the Type is not found. In this case, a null value will never be returned so application of `CS8600` is unnecessary.

A workaround is to explicitly apply the null forgiving operator !, or use pragma warning suppression to explicitly suppress this warning for this case. However these workarounds are unnecessary if the suggested analyzer is incorporated.

#### Example
`var t = Type.GetType(typeName: nodeTypeString, throwOnError: true)!;
`
### Suggestion

Incorporate an analyzer that suppresses CS8600 for this use case. 

### Additional Notes

The `GetType` documentation describes the `throwOnError` parameter as:

> **throwOnError**
> [Boolean](https://learn.microsoft.com/en-us/dotnet/api/system.boolean?view=net-7.0)
> true to throw an exception if the type cannot be found; false to return null. Specifying false also suppresses some other exception conditions, but not all of them. See the Exceptions section.

**Comment by Youssef1313** [comment] 2022-12-15 08:01
https://github.com/dotnet/csharplang/issues/2835

**Comment by jcouv** [comment] 2022-12-31 20:18
Thanks @Youssef1313 
Closing as duplicate of https://github.com/dotnet/csharplang/issues/2835

**Closed by jcouv** 2022-12-31 20:18 UTC
Labels: Area-Compilers, untriaged
