### ISSUE TITLE
IDE0008 adds incorrect nullable annotation for ref argument

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42763] opened 2020-03-25 15:26 UTC
**Version Used**: 
C# Tools 3.6.0-2.20167.1+926207070b0c62d6a76aec4627ec26dee17870bb

**Steps to Reproduce**:
```C#
#nullable enable
class Program
{
    static void Main() => new Program().Caller();

    void Caller()
    {
        var thisRef = this;
        Callee(ref thisRef);
    }

    static void Callee(ref Program o) { }
}
```

**Expected Behavior**:
Running IDE0008 on the `var thisRef = this;` produces `Program thisRef = this;`.

**Actual Behavior**:
Running IDE0008 on the `var thisRef = this;` produces `Program? thisRef = this;`.

**Comment by sharwell** [comment] 2020-03-26 15:49
Duplicate of #41243

**Closed by sharwell** 2020-03-26 15:49 UTC
