### ISSUE TITLE
InvalidOperationException in ExtractMethodCodeRefactoringProvider

### ISSUE THREAD

**Issue by elachlan** [dotnet/roslyn#22759] opened 2017-10-19 00:10 UTC
**Version Used**: 
Visual Studio Community 2017 v 15.4.0
Visual Basic 2017 - 00369-60000-00001-AA072 

**Steps to Reproduce**:
I am unsure how I produced the error. But I was working with a foreach loop.

**Expected Behavior**:
No Exception.

**Actual Behavior**:
Exception:

```
System.InvalidOperationException : Sequence contains no elements
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionResult.GetLastStatementUnderContainer()
at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicMethodExtractor.VisualBasicAnalyzer.GetFlowAnalysisNodeRange()
at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetDataFlowAnalysisData(SemanticModel model)
at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by elachlan** [comment] 2018-02-19 01:40
Received the error again highlighting some code in a broken "with" block:

```
Microsoft Visual Studio Community 2017 
Version 15.5.5
VisualStudio.15.Release/15.5.5+27130.2026
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA072
Microsoft Visual Basic 2017
```

```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionResult.GetLastStatementUnderContainer()
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicMethodExtractor.VisualBasicAnalyzer.GetFlowAnalysisNodeRange()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetDataFlowAnalysisData(SemanticModel model)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2018-02-19 03:12
Can you provide the source code you had when this happened?

**Comment by elachlan** [comment] 2018-02-19 03:19
I highlighted everything below Asset_TextEdit to delete it after removing the starting "With". It seems reliably reproducible.

```
                With Account_SearchLookUpEdit
                    .EditValue = 
                End With

                Asset_TextEdit
                .Enabled = True
                End With
```

**Comment by jinujoseph** [comment] 2018-05-20 07:02
Also reported at [link](https://developercommunity.visualstudio.com/content/problem/251357/vs-1571-extractmethodcoderefactoringprovider-encou.html)

**Comment by Muhomorik** [comment] 2018-05-28 09:00
Is there any update on this? 
Error still exists in 15.7.2 (7 months later).
ActivityLog says it is a System.NullReferenceException.

**Comment by genlu** [comment] 2019-01-22 20:32
@elachlan I couldn't trigger the "extract method" refactoring using the code below (`[|` and `|]` is used to show the selection, it's not part of the code), did I miss anything? 
```vb
Public Class Class1
    Public Sub Foo()
        Dim x = New Bar()
        Dim y = New Bar()

        With x
            .Field = 
        End With

        y
        [|.Field = 2
        End With|]

    End Sub

End Class

Public Class Bar
    Public Field As Integer
End Class
```

@Muhomorik `NullReferenceException` might be something different. Could you please share the stacktrace (a repro would be even better)?

**Comment by elachlan** [comment] 2019-01-31 01:12
@genlu Thanks for looking at this. I haven't run into this error in a long time and I have been using with statements pretty regularly.

**Comment by jinujoseph** [comment] 2019-02-04 09:04
@Muhomorik do you have a repro for this issue ?

**Comment by Muhomorik** [comment] 2019-02-04 09:33
@genlu, @jinujoseph I am not having this issue since 15.9.4 or something.
I don't think you would get any good repo because I could get that error by moving the pointer at a new line.
For me it it fine to close this issue, I will report it again in case it occurs via the VS feedback.

**Comment by jinujoseph** [comment] 2019-02-04 10:02
thanks for quick response @Muhomorik .

**Closed by jinujoseph** 2019-02-04 10:02 UTC
Labels: Area-IDE, Bug, Developer Community, Need More Info

**Comment by verelpode** [comment] 2019-04-12 23:12
Should this issue be reopened?  Today with VS 2019 16.0.0, I experienced ExtractMethodCodeRefactoringProvider "Sequence contains no elements", with the following code.

Might be relevant:  The following code was unfinished at the time when the ExtractMethodCodeRefactoringProvider  error occurred, thus this code snippet does not compile.  "endOrdinal" is used but it is an unassigned local variable -- _maybe_ that is a necessary for reproduction of the bug.

```
public void TestMethod(int inOrdinal, int inCount)
{
    unchecked {
        int oldUsedCount = (int)fUsedCount;
        int endOrdinal;
        if (!XXXXX(inOrdinal, inCount, oldUsedCount)) XXXXXX();
        if (inCount == 0) return;
        T[] ary = this.fItemArray;
        System.Array.Copy(ary, endOrdinal, ary, inOrdinal, oldUsedCount - endOrdinal);

        int newUsedCount = oldUsedCount - inCount;
        this.fUsedCount = (uint)newUsedCount;
        System.Array.Clear(ary, newUsedCount, inCount);

        // A comment was here.
        // Another comment was here.
    } // unchecked
}
```

```
'ExtractMethodCodeRefactoringProvider' encountered an error and has been disabled.
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.WrapInCheckStatementIfNeeded(IEnumerable`1 statements)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.CreateMethodBody(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateMethodDefinition(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

See also [#17971](https://github.com/dotnet/roslyn/issues/17971).
