### ISSUE TITLE
ExtractMethodCodeRefactoringProvider crashes with System.InvalidCastException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50769] opened 2021-01-26 01:04 UTC
🔗 See [AB#1269217](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1269217)

_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ExtractMethodCodeRefactoringProvider-cra/1318605)._

---
[severity:It bothers me. A fix would be nice]

While editing code in VS2019:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Retargeting.RetargetingAssemblySymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol'.
   at Microsoft.CodeAnalysis.CSharp.DefiniteAssignmentPass.. ctor(CSharpCompilation compilation,Symbol member,BoundNode node,EmptyStructTypeCache emptyStructs,Boolean trackUnassignments,HashSet`1 initiallyAssignedVariables)
   at Microsoft.CodeAnalysis.CSharp.UnassignedVariablesWalker.Analyze(CSharpCompilation compilation,Symbol member,BoundNode node,Boolean convertInsufficientExecutionStackExceptionToCancelledByStackGuardException)
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_UnassignedVariables()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_DataFlowsIn()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_Succeeded()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.AnalyzeReadWrite()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_Captured()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(Boolean bestEffort,SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap,IDictionary`2& variableInfoMap,List`1& failedVariables)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 1/24/2021, 10:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jaredpar** [comment] 2021-02-02 14:25
@AlekseyTs tentatively put this in 16.9 as it didn't come with a repro and hence unclear how severe this is. Based on how common the repro is we should punt to 16.10.

**Comment by daviburg** [comment] 2021-02-02 17:22
I attached an issue reproduction recording from the VS feedback tool when reporting this. Does it not show up?

**Comment by AlekseyTs** [comment] 2021-02-02 23:55
I don't think this issue is actionable. There is something special about the scenario, otherwise there were a lot of complains about Extract Method refactoring not working. In order to figure out the root cause, we would either need a crash dump with heap, or reliable repro steps.

**Comment by daviburg** [comment] 2021-02-03 04:37
Sorry to hear. How may I generate a crash dump with heap next time this problem surfaces?

**Comment by AlekseyTs** [comment] 2021-02-03 15:06
@sharwell Is Watson report sent automatically in cases like this? Is there a way to locate it? Are there other ways to debug the refactoring crash?

**Comment by AlekseyTs** [comment] 2021-02-05 16:14
Closing as "No Repro" for now.

**Closed by AlekseyTs** 2021-02-05 16:14 UTC
Labels: Area-Compilers, Bug, Developer Community, Resolution-Not Reproducible
