### ISSUE TITLE
"'using' statement can be simplified" breaks code if used in a multi-targetted project

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/roslyn#38048] opened 2019-08-16 17:42 UTC
**Version Used**: 
Visual Studio 16.3.0 Preview 2

**Steps to Reproduce**:

1. create a multi-targetted project (e.g. class library)

```
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.0; netstandard21; net472</TargetFrameworks>
  </PropertyGroup>
```

2. add code with using statement

     using (var scope = ... blah){ ... }

3. accept suggestion to use simple using statement
4. try to compile - get error

> Error	CS8370	Feature 'using declarations' is not available in C# 7.3. Please use language version 8.0 or greater.	

**Expected Behavior**:
No suggestion

**Actual Behavior**:
Accepting  suggestion causes error and breaks build.

**Comment by sharwell** [comment] 2019-08-17 05:31
@cartermp this is a hole in the target language inference feature. Refactorings don't have knowledge of other targets, yet other targets can impact their final validity.

@PhilPJL the solution here is to explicitly set the target language version in the project file. Set it to 8 to use C# 8 (refactoring will be offered, and will work for all targets), or 7.3 to use C# 7.3 (refactoring will not be offered).

**Comment by cartermp** [comment] 2019-08-17 15:47
The ideal resolution here is to drop the `net472` feature, as C# 8 isn't intended to be used on .NET Framework. Provided your tools have the latest preview compiler, then the .NET Core and .NET Standard targets will work.

**Comment by miloush** [comment] 2019-08-17 15:53
I disagree. The ideal resolution is fix the language inference feature. There is nothing wrong with compiling C# 8 on .NET Framework.

Actually the ideal resolution is to not infere language version and let the user set the version like it used to be.

**Comment by miloush** [comment] 2019-08-17 16:00
Similarly, if two projects with different language version, either inferred or explicit, share the same source file (as a linked file), the refactoring will be suggested when opened in the C# 8 project even though it breaks build of the other project if executed.

**Comment by PhilPJL** [comment] 2019-08-17 17:33
I think a linked file is a bit more of special case, and there I would be happy to disable the suggestion or set the C# version explicitly.  For multi-target projects I agree that the ideal  resolution is fix the language inference feature.
Due to the fact that EF 6.3 needs either .NET Framework 4.x or .NET Standard 2.1 (and in fact needs .NET Core 3 so the migration tools work), we're forced to multi-target our data projects, which then forces referencing projects to be multi-targeted also.  Nothing's ever simple unfortunately.

**Comment by sharwell** [comment] 2019-08-20 04:01
@cartermp The underlying problem here is the automatic selection of multiple different versions of the C# language for a single build, all without any action taken by the user. .NET Core 3 is the first time this has ever occurred, and the problems are worsened by the fact that the only UI for correcting this situation was eliminated from the project system UI. The project system and build design fails to account for IDE features with multi-targeting.

**Comment by cartermp** [comment] 2019-08-20 04:16
> The project system and build design fails to account for IDE features with multi-targeting.

Oh, I agree. I wrote a design doc describing how multi-TFM could be addressed in the IDE all-up, and the cost of reasonable progress on that front would have meant abandoning the .NET Core 3 release. We're likely stuck with the sub-par experience today until the project system is no longer on the critical path for the platform.

> We can't just say it's no longer an option.

Note that I had careful wording here. It's an _ideal_ solution, not necessarily a practical one for someone right now. But we do not want to encourage use of C# 8 in a state where only a subset can actually work, as the feedback we got in previews was that this was horribly confusing to deal with. Appending that kind of thing to the already challenging problem of balancing an in-between world of .NET Framework and .NET Core isn't necessarily going to make things easier either.

Given that this is highly likely to be the way forward for C# 9 and beyond, I think the appropriate thing is to utilize the data about highest supported language version to gate IDE fixers for new features. Probably not possible to get into the 16.3 release, but it's likely to be a dimension to consider moving forward.

**Comment by miloush** [comment] 2019-08-20 04:42
> .NET Core 3 is the first time this has ever occurred

While that's true for multi-targeting, it's not for linked files. I don't know how common is multi-targeting vs. linked files (which I use a lot), but there is an experience precedence, making this issue not a regression.

If there is a will for compromise, I suggest this issue can be addressed in the future, but keep the compiler version selectable by the user. Being it buried in Advanced settings of the build properties is not exactly encouraging users, and it provides a workaround for the multi-targeting case.

I would even argue it's not a workaround, it's the very purpose of the language version selection - dealing with cases where automatic inference would be too costly to get it right.

The engineering cost here is to revert to an already tested code letting users select the version. I haven't heard yet a single example of who benefits from removing the option.

**Comment by sharwell** [comment] 2021-04-26 19:56
Since this analyzer is behaving as intended, I'm going to mark this issue as a duplicate of #49925 since it has more details about the overall expectations in this space.

**Closed by sharwell** 2021-04-26 19:56 UTC
Labels: Bug, Resolution-Duplicate, Area-IDE, IDE-CodeStyle
