### ISSUE TITLE
Codespaces quick info is not classified

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44349] opened 2020-05-18 20:28 UTC
![image](https://user-images.githubusercontent.com/4564579/82256591-797ac380-990b-11ea-90bf-d382bae98aeb.png)

**Comment by jinujoseph** [comment] 2020-05-21 06:35
Duplicate of [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128690)

**Closed by jinujoseph** 2020-05-21 06:35 UTC
Labels: Area-IDE, CloudEnv
