### ISSUE TITLE
IDE0009 claims `this.` must precede reference to local method in delegate constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38773] opened 2019-09-19 21:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/726242/ide0009-claims-this-must-precede-reference-to-loca.html)._

---
[regression] [worked-in:16.3]
What steps will reproduce the problem?

1. Have an .editorconfig file with `dotnet_style_qualification_for_method = true:warning`
1. Define a local method
2. Use that local method name as the argument to a delegate constructor.

What is the expected output? What do you see instead?

I expect no warnings.

I see an IDE0009 warning saying I must qualify the local method reference with `this.`.
Yet of course if I add `this.` then there's an error because local methods must not be qualified that way.

---
#### Visual Studio Feedback System on 9/8/2019, 11:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AArnott** [comment] 2019-09-19 22:32
dupe of #38043

**Closed** 2019-09-24 19:35 UTC
Labels: Area-IDE
