### ISSUE TITLE
IDE0063 removes comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40185] opened 2019-12-05 23:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/836609/ide0063-removes-comments.html)._

---
When converting a block using statement to a simple using statement, Visual Studio deletes any trailing comments that were in the block (i.e. comments are only preserved if they're followed by code). My expectation is that IDE0063 should preserve everything that was in the using block.

---
#### Visual Studio Feedback System on 11/27/2019, 07:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2019-12-05 23:42
Marking as a good first issue. Trivia from the using block is not maintained. Feel free to reach out if you take up this issue and would like help.

**Comment by jinujoseph** [comment] 2019-12-10 21:01
Duplicate of #37678

**Comment by jinujoseph** [comment] 2019-12-10 21:02
cc @ryzngard for info

**Closed by jinujoseph** 2019-12-10 21:01 UTC
Labels: Area-IDE, Bug, Developer Community, New Language Feature - enhanced using, good first issue, help wanted
