### ISSUE TITLE
Proposal: add `else` block to `foreach` if no items are iterated

### ISSUE THREAD

**Issue by EBrown8534** [dotnet/roslyn#16815] opened 2017-01-28 19:55 UTC
Consider the following ASP.NET Razor sample:

    <div class="content">
        @foreach (var item in Model
            .Items
            .Where(x => x.Name != null)
            .OrderByDescending(x => x.Added))
        {
            <div class="item">
                @item.Name
            </div>
        }
    </div>

If one wishes to check that the collection would first return items it requires adding another level of testing to the Razor:

    <div class="content">
        @if (Model.Items.Count(x => x.Name != null) > 0)
        {
            foreach (var item in Model
                .Items
                .Where(x => x.Name != null)
                .OrderByDescending(x => x.Added))
            {
                <div class="item">
                    @item.Name
                </div>
            }
        }
        else // We didn't actually find anything
        {
            <div class="none">
                No items
            </div>
        }
    </div>

You could propose two major solutions currently supported by the language to solve this issue:

First: create an intermediary variable in the view:

    <div class="content">
        @{
            var filteredCollection = Model.Items.Where(x => x.Name != null);
            if (filteredCollection.Count() > 0)
            {
                foreach (var item in filteredCollection.OrderByDescending(x => x.Added))
                {
                    <div class="item">
                        @item.Name
                    </div>
                }
            }
            else // We didn't actually find anything
            {
                <div class="none">
                    No items
                </div>
            }
        }
    </div>

Obviously this is not a pure solution: our view contains a local variable and requires a local variable if using this solution for each and every location we wish to operate on a collection in this manner with.

The second solution would be to add the `filteredCollection` to the model being passed to the view, then simply:

    <div class="content">
        @if (Model.ItemsWithName.Count() > 0)
        {
            foreach (var item in Model.ItemWithName.OrderByDescending(x => x.Added))
            {
                <div class="item">
                    @item.Name
                </div>
            }
        }
        else // We didn't actually find anything
        {
            <div class="none">
                No items
            </div>
        }
    </div>

This increases maintenance with the model, and requires this to be somehow derived from the model. (If it's a simple filter on another collection in the model that's easy enough, but the more complex our conditions become the more maintenance on the model is required.)

---

I propose we add an `else` block to be added directly after a `foreach` block which would only execute if **no items were iterated**.

    <div class="content">
        @foreach (var item in Model
            .Items
            .Where(x => x.Name != null)
            .OrderByDescending(x => x.Added))
        {
            <div class="item">
                @item.Name
            </div>
        }
        else // We didn't actually iterate anything
        {
            <div class="none">
                No items
            </div>
        }
    </div>

This would be most helpful in ASP.NET applications where custom object sorting and filtering is more likely to be common and the potential to display a 'no items to display' message is much higher.

**Comment by jnm2** [comment] 2017-01-28 20:01
I've had the same wish, and in the same circumstances. I wonder if it could just be Razor sugar or if it would really be helpful in C# itself.

**Comment by HaloFour** [comment] 2017-01-29 00:00
Dupe of #135.

**Comment by jnm2** [comment] 2017-01-29 00:06
Can you link the actual dupe?

**Comment by HaloFour** [comment] 2017-01-29 00:07
@jnm2 Oops, typo.  #134  (I'll fix the original comment too)

**Comment by jnm2** [comment] 2017-01-29 00:08
@HaloFour This isn't a dupe if it's implemented as Razor sugar

**Comment by eyalsk** [comment] 2017-01-29 00:39
@jnm2 Then why it needs to be implemented at the language? they can add a special syntax and deal with it themselves.

**Comment by jnm2** [comment] 2017-01-29 00:40
> @jnm2 Then why it needs to be implemented at the language? they can add a special syntax and deal with it themselves.

Correct, it would go in a different repo.

**Comment by alrz** [comment] 2017-01-29 04:21
There's no such thing as "razor sugar". Razor passes code sections as-is to the generated view class.

**Comment by jnm2** [comment] 2017-01-29 04:29
@alrz Razor *is* sugar 😆
This doesn't seem that complex to add to the parser that separates C# and HTML.

**Comment by initram** [comment] 2017-01-30 10:56
For a lot of cases you can use the extension method DefaultIfEmpty(), where you can provide an element to return if the IEnumerable is empty.

**Comment by Thaina** [comment] 2017-01-31 05:37
We should just let else + any keywords format in the same line. And you should swap logic for empty on top

```C#
if(array.IsNullOrEmpty())
{
    // default logic
}
else foreach(var obj in array)
{
    // iter logic
}
```

It already valid syntax just formatter make it annoying separate line

**Comment by Thaina** [comment] 2017-01-31 05:54
On a second thought. if no one mind this syntax just it conflict with valid syntax we can just tweak any syntax

```C#
foreach if(var foo in bar)
{
    Console.WriteLine(foo);
}
else Console.WriteLine("no foos in the bar");

// or

if foreach(var foo in bar)
{
    Console.WriteLine(foo);
}
else Console.WriteLine("no foos in the bar");

// or for

for(var foo in bar) // introduce in to work in for in addition to ;;
{
    Console.WriteLine(foo);
}
else Console.WriteLine("no foos in the bar");

// or colon

for(var foo : bar) // introduce in to work in for in addition to ;;
{
    Console.WriteLine(foo);
}
else Console.WriteLine("no foos in the bar");
```

**Comment by TonyValenti** [comment] 2017-01-31 10:41
Wow!  What an elegant solution!  I love this proposal. I've always just resorted to doing something like having an extra count variable and then IFing off it. I really like this suggestion a lot.

**Comment by alrz** [comment] 2017-01-31 11:19
If this is common in Razor, you could use a partial view or even an action result filter. If there is a use case outside ASP.NET MVC, that could be also addressed with similar mechanisms., depending on problem domain.

**Comment by jcouv** [comment] 2017-10-22 04:03
I'll move this to csharplang (where language design is now discussed). Thanks

**Comment by jcouv** [comment] 2017-10-22 04:03
Issue moved to [dotnet/csharplang #1025](https://github.com/dotnet/csharplang/issues/1025) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jcouv** 2017-10-22 04:03 UTC
Labels: Area-Language Design, Discussion
