### ISSUE TITLE
Rename namespaces.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36910] opened 2019-07-01 21:54 UTC
VSF_TYPE_MARKDOWNCan you add a way to rename namespaces in Visual Studio?
Not the one which offers to rename only one part of it but a feature to rename the entire namespace and change its depth.

For instance, I would like to rename the namespace of a class &quot;Company.Project.Subfolder.MyClass&quot; to &quot;Company.Project.MyClass&quot;, or &quot;OtherCompany.OtherProject.MyClass&quot;.

Thanks!

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/627968/rename-namespaces.html
VSTS ticketId: 940134_
_These are the original issue comments:_

Jane Wu [MSFT] on 7/1/2019, 04:03 AM (10 hours ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by kendrahavens** [comment] 2019-07-01 21:54
This isn't exactly what this request is, but we do have a fairly new 'Move contents to namespace' refactoring that can move the contents in the current namespace block to another namespace. 

https://docs.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-namespace (The doc mentions moving a type to a new namespace, but the same refactoring appears on namespaces.)

This refactoring does, however, leave other blocks that use that namespace name untouched so it does not move the entire namespace.

**Comment by sharwell** [comment] 2019-07-02 17:54
Duplicate of #3583

**Closed by sharwell** 2019-07-02 17:54 UTC
Labels: Area-IDE, Developer Community, Feature Request, IDE-CodeStyle
