### ISSUE TITLE
Find and access "referenced project" Compilations and AdditionalDocuments in ServiceHub.RoslynCodeAnalysisService

### ISSUE THREAD

**Issue by etvorun** [dotnet/roslyn#67219] opened 2023-03-07 17:07 UTC
## Background and Motivation

As part of moving XAML intellisense into Roslyn LSP layer we need ability to run XAML code analyzers in ServiceHub.RoslynCodeAnalysisService.exe. While analyzing content of *.xaml file it needs to find other *.xaml files, from the same or different project. Example:
[MyApp]\Views\Details.xaml
```
<UserControl ...>
  <UserControl.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source='AppStyles.xaml'/>  <!-- in the same project -->
        <ResourceDictionary Source='/MyLib;component/ControlStyles.xaml'/> <!-- in project which builds MyLib.dll -->
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </UserControl.Resources>
 <Button Style='{StaticResource MyStyle}'/>
```
When analyzing XAML, we might need to look into *.xaml files pointed by `Source='AppStyles.xaml'` and `Source='/MyLib;component/ControlStyles.xaml'`. The latter case requires finding a compilation which represents project which builds MyLib.dll.

## Proposed API
To be determined by Roslyn team.

**Comment by etvorun** [comment] 2023-03-07 17:07
@jasonmalinowski (cc @mgoertz-msft) this is a follow up on our discussion about moving XAML intellisense into Roslyn LSP layer.

**Comment by CyrusNajmabadi** [comment] 2023-03-07 18:13
I'm def nervous about all this.  A core compiler concept is that it is disconnected from a project.  Such things may not, for example, exist at all when doing a normal build. 

We've explicitly avoided exposing this for years for many other scenarios.  I'm concerned why we're potentially changing that now.

**Comment by jasonmalinowski** [comment] 2023-03-08 00:33
@etvorun To clarify: is this asking us to add some support in Roslyn OOP to do something like you're already doing today, or for new support? As @CyrusNajmabadi calls out: knowing about additional files from other projects is not something we do in our traditional analyzer design, because it's hard to even make work (much less efficiently).

**Comment by tmat** [comment] 2023-03-08 01:56
@etvorun When the referenced project that contains `/MyLib;component/ControlStyles.xaml` is compiled, is the information that you need to retrieve from that xaml file not present in some form in the generated `.dll` or `.pdb`?

**Comment by etvorun** [comment] 2023-03-09 16:20
@jasonmalinowski @tmat all this is needed in LSP layer to support XAML intellisense completion for resource references, e.g. `<Button Background='{StaticResource ...}'`

About `/MyLib;component/ControlStyles.xaml`. ControlStyles.xaml is no different that MyData.cs. You need to show C# itntellisense for MyData when project is unbuilt or MyData.cs has been modified since last build.

**Comment by mgoertz-msft** [comment] 2023-03-09 18:08
@CyrusNajmabadi, @jasonmalinowski, @tmat You can close this as the LSP [RequestContext](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/RequestContext.cs) gives us access to everything for Intellisense and the analyzer context is limited by design.

**Comment by CyrusNajmabadi** [comment] 2023-03-09 18:56
Works for me.

**Closed by CyrusNajmabadi** 2023-03-09 18:56 UTC
Labels: Area-Analyzers, Concept-API, Feature Request, untriaged
