### ISSUE TITLE
Go To Member not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32511] opened 2019-01-16 03:17 UTC
When using the Go To Member filter &quot;m&quot; no members are found.
Members show up when searching for symbols, or &quot;all&quot; prefixing with the type name.

Examples:
&quot;m SomeMethod&quot; gives no results.
&quot;SomeMethod&quot; gives the method, but also a lot of non-relevant results
&quot;# SomeMethod&quot; gives the method, but also a lot of non-relevant results
&quot;SomeType.SomeMethod&quot; gives the method, but also a lot of non-relevant results

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/401830/go-to-member-not-working.html
VSTS ticketId: 743097_
_These are the original issue comments:_

Ladislav Burkovsky on 12/7/2018, 08:03 AM (39 days ago): same here
Rock Li [MSFT] on 12/11/2018, 08:51 PM (35 days ago): <p>Thanks for taking the time to report this issue to us. We’ve created a bug for this issue as internal tracking. The status on this Developer Community item will be updated as that bug is resolved. Thanks again for your feedback.&nbsp;</p>
Jonathan Sheely on 12/12/2018, 09:16 AM (34 days ago): +1 Still broken in Preview 1
Aaron on 1/4/2019, 10:53 AM (11 days ago): <p>Still broken in Preview 1.1</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-01-16 03:18
@jasonmalinowski When I tested this issue, the problem occurred when the Navigate To dialog was filtering to the current document. I'm guessing the underlying problem is the failure to track the current document, in which case this should already be fixed. Can you confirm?

**Comment by jasonmalinowski** [comment] 2019-01-16 04:37
@sharwell I didn't realize Navigate To would filter to the current document at all. It sounds like that's not what the user expected either?

**Comment by jasonmalinowski** [comment] 2019-01-16 04:39
Ah, it turns it on when you do prefix with an 'm'. Good theory then. I'll test tomorrow.

**Comment by mkholt** [comment] 2019-01-16 07:15
> @sharwell I didn't realize Navigate To would filter to the current document at all. It sounds like that's not what the user expected either?

I'm the original reporter. I can confirm that it member ("m") search in the open document does not work in 2019 Preview 1.1, but that member ("m") search without the filter does return members.
However, filtering to the current document is absolutely the place where I, personally, use member search the most to navigate the open document.

**Comment by jasonmalinowski** [comment] 2019-01-16 18:53
Yes, this was fixed by #31265. The problem would have been that since we couldn't figure out the active document (because that service was broken), we would have filtered to nothing. Confirmed fixed in Preview 2.

**Closed by jasonmalinowski** 2019-01-16 18:53 UTC
Labels: Area-IDE, Bug, Developer Community, Regression
