### ISSUE TITLE
NuGet failure in CI: "The project file could not be loaded. Root element is missing."

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#19912] opened 2017-05-31 20:09 UTC
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4841/console

```
C:\Users\dotnet-bot\.nuget\packages\Microsoft.VSSDK.BuildTools\15.0.26124-RC3\build\Microsoft.VsSDK.BuildTools.props : error MSB4025: The project file could not be loaded. Root element is missing. [D:\j\workspace\windows_relea---8a39a417\build\Toolset\Toolset.csproj]
16:36:18 Command failed to execute: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\msbuild.exe /warnaserror /nologo /m /nodeReuse:false /consoleloggerparameters:Verbosity=minimal /filelogger /fileloggerparameters:Verbosity=normal /p:UseShippingAssemblyVersion=true /p:InitialDefineConstants=BOOTSTRAP build\Toolset\Toolset.csproj /p:Configuration=Release /fileloggerparameters:LogFile=D:\j\workspace\windows_relea---8a39a417\Binaries\Bootstrap.log
16:36:18 System.Management.Automation.RuntimeException: Command failed to execute: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\msbuild.exe /warnaserror /nologo /m /nodeReuse:false /consoleloggerparameters:Verbosity=minimal /filelogger /fileloggerparameters:Verbosity=normal /p:UseShippingAssemblyVersion=true /p:InitialDefineConstants=BOOTSTRAP build\Toolset\Toolset.csproj /p:Configuration=Release /fileloggerparameters:LogFile=D:\j\workspace\windows_relea---8a39a417\Binaries\Bootstrap.log
16:36:18 Build step 'Execute Windows batch command' marked build as failure
```

**Comment by jasonmalinowski** [comment] 2017-06-01 23:43
Dupe of #19882.

**Closed by jasonmalinowski** 2017-06-01 23:43 UTC
Labels: Area-Infrastructure
