### ISSUE TITLE
Visual Studio intellisense for C# class files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52504] opened 2021-04-08 19:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-intellisense-for-C-class-/1371489)._

---
Hello, 

I understand that the Visual Studio intelli-sense system works by interpreting the first character typed for a word, and lists out possible key words/class-names/functions/properties beginning with that character in a list, so that the user can easily pick one, instead of typing the entire word. 

Also as of now, I observe that these probable matching words are listed in the alphabetical order.

For example, when we create a new C# class file, and try to add reference to a namespace, we first key in the character
'u' with the intention of typing  'using', but instead of listing the word 'using' as the first option here, the intelli-sense system 
suggests the key word 'ushort' as the first possible option, as that comes ahead of 'using' in the alphabetical order.

But I assume most people types the word 'using' more number of times any day,  than the word 'ushort' while writing C# code.

Hence, I suggest you to modify the criteria by which you order the items in the drop-down list that appears as intelli-sense, in such a way that,  the most commonly used C# key words or class names or function/property names appear earlier than the lesser frequently used ones.  I believe you could be already having such a count of most used key words and functions by Visual Studio users around the world.

This may also be made as an optional setting change, so that those users who prefer the alphabetical listing can still use that if they wish.

Thank you for reading my suggestion. Kindly excuse if this does not makes sense, or is already an option.

Thank You.

---
#### Feedback Bot on 3/16/2021, 08:11 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2021-04-08 21:14
This was fixed.  We prioritize `using`:

![image](https://user-images.githubusercontent.com/4564579/114097101-7155aa80-9874-11eb-86cc-c66bb827fb9b.png)

No clue what the PR was called though...

**Comment by sharwell** [comment] 2021-04-09 06:17
Duplicate of #44459

**Closed by sharwell** 2021-04-09 06:17 UTC
Labels: Resolution-Duplicate, Area-IDE
