### ISSUE TITLE
Incorrect refactoring results when using local functions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19497] opened 2017-05-14 21:51 UTC
**Version Used**: 15.0

Originally reported by [Mike Heckenbach](https://developercommunity.visualstudio.com/content/problem/38579/certain-quick-actions-create-incorrect-modificatio.html):

> In VS2017, I found that if I have a local function declared inside of a lambda function, and I use either the quick action "introduce local [constant|variable] for ..." or the quick action "extract method" on an expression which is inside the lambda, all references to the local function get a qualifier added to them which is the name of the enclosing class. But, the local function isn't a member of the class, so the resulting program is invalid.
>
> Minimal example code:
> ```csharp
> class Program
> {
>     void a()
>     {
>         Action action = () =>
>         {
>             int test() => 3;
>             int x = 5;
>             int y = test();
>         };
>     }
> }
> ```
>
> If you select the text "5" (note: or a more complicated single expression), and choose either "introduce local constant for '5'" or "extract method", the quick action also causes the line "int y = test();" to be transformed to "int y = Program.test();", eg:
>
> ```csharp
> class Program
> {
>     void a()
>     {
>         Action action = () =>
>         {
>             int test() => 3;
>             const int V = 5;
>             int x = V;
>             int y = Program.test();
>         };
>     }
> }
> ```
> 
> Other notes:
> * If "Action action = () =>" is removed, ie, no lambda function, then the quick actions don't modify the reference to test.
> * If "Action action = () =>" is changed to "void action()", ie, changing the lambda to a local function, then the quick actions don't modify the reference to test.
> * If "int test() => 3;" is changed to "Func<int> test = () => 3;", ie, changing the local function to a lambda, then the quick actions don't modify the reference to test.
> * If using the quick actions on an expression that is not located inside the lambda (even if the expression is inside the same method), then the quick action doesn't modify the reference to test.
> * If test() is declared with curly braces instead of shorthand syntax, the problem persists.
> * If the lambda is instead passed to another function, or invoked directly without assigning it to a variable ("action" in this example), the problem persists.
> * Other references to test, for example "Func<int> z = test;" or "otherFunction(test)" also have an incorrect qualifier added to them.
>   * although apparently nameof(test) is not modified.
>
> Possible related and/or additional bug:
>
> * If "introduce local constant for '3'" is used on the 3 (or a more complex expression), then test remains unqualified, however the line "int test() => 3;" is removed entirely with no replacement code, meaning test becomes undefined.
> * but this doesn't occur when "extract method" is used: if "extract method" is used, the first bug mentioned above is invoked on references to test.

This is closely related to, but does not appear to be a duplicate of, #18347.

**Comment by Pilchie** [comment] 2017-05-15 21:25
Tagging @agocke

**Comment by Neme12** [comment] 2018-03-25 03:59
Can't reproduce.

**Comment by CyrusNajmabadi** [comment] 2020-03-15 08:51
Fixed with https://github.com/dotnet/roslyn/pull/42072

**Closed by CyrusNajmabadi** 2020-03-15 08:51 UTC
Labels: Area-IDE, Bug

**Comment by sharwell** [comment] 2020-03-17 13:15
@CyrusNajmabadi Make sure to set the resolution label and milestone when closing issues.
