### ISSUE TITLE
Opening a document from a project with unresolved nuget references opens it in Misc files project

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1890] opened 2015-04-09 17:37 UTC
1. clone any github project that has nuget references, but do not resolve nuget references just yet.
2. open a document from this project.

**Actual**:
Document opens as a Misc files project. No errors in error list.

**Expected**: 
Document opens in the correct project context and squiggles show up for members that have missing references.

cc @dpoeschl

**Comment by dpoeschl** [comment] 2015-04-09 17:45
When we last investigated this, the failure to find the references halted msbuild before it could tell us about the files in the project, which is why open in Misc Files until you fix the references. I'm not sure why they do this, or if there's some historical reason (maybe they're trying to save us from having to show hundreds of thousands of errors and squiggling everything)? Any ideas @jasonmalinowski or @Pilchie?

**Comment by Pilchie** [comment] 2015-04-10 17:29
Unfortunately, no, I don't have any context here :frowning:

**Comment by jasonmalinowski** [comment] 2015-04-10 18:40
I'm not aware of any historical reason for this -- and missing file references shouldn't cause the entire intellisense build pipeline to fail...those should just be treated as yellow-triangle "missing" references in solution explorer but other stuff should still work.

**Comment by Pilchie** [comment] 2015-04-23 00:56
Is this really any NuGet reference, or is it specific to Roslyn?  I wonder if it's because we use tasks/targets in the toolset compiler.

**Comment by jasonmalinowski** [comment] 2015-04-23 00:59
Even if it was specific to Roslyn, I'm not sure why Roslyn would break -- if our toolset isn't active it'd fall back to the system-installed toolset which should be sufficient for the intellisense build.

**Comment by jasonmalinowski** [comment] 2015-05-28 00:53
So testing with a small project, if there's only references missing, the design time build doesn't fail. But if there's any inclusion of props or targets, the NuGet-inserted bits that fail the build when the .targets or .props are missing completely fail the design time build. Since Roslyn consumes the toolset compiler in each of our projects, this breaks it.

@yishaigalatzer: did something change here with what NuGet places inside project files for this scenario? Otherwise this really isn't new AFAIK.

**Comment by yishaigalatzer** [comment] 2015-05-28 05:15
Nothing that I know of. Does this behave differently if you open the project in visual studio 2013?

**Comment by Pilchie** [comment] 2015-06-09 21:28
Moving to 1.1, since we think this is specific to the way that Roslyn.sln projects error when we don't find targets.

**Comment by Pilchie** [comment] 2015-09-02 00:28
Confirmed by looking at designtime build logs that this is happening because of our custom targets:

```
Target "EnsureGlobalNuGets" in file "D:\Code\Roslyn\Open\build\Targets\VSL.Settings.targets":
  Task "Error"
    D:\Code\Roslyn\Open\build\Targets\VSL.Settings.targets(104,5): error : This project requires the Microsoft.Net.Compilers NuGet package to build. Use NuGet Package Restore to download the required files ("powershell .nuget\NuGetRestore.ps1"). The missing file is "D:\Code\Roslyn\Open\packages\Microsoft.Net.Compilers.1.1.0-beta1-20150825-02\build\Microsoft.Net.Compilers.props".
  Done executing task "Error" -- FAILED.
Done building target "EnsureGlobalNuGets" in project "CompilerTestResources.csproj" -- FAILED.
```

**Comment by jasonmalinowski** [comment] 2015-09-02 18:23
Shouldn't we change the condition then? For the sake of design time it doesn't matter if our toolset compiler is being used...

**Comment by Pilchie** [comment] 2015-09-03 15:15
Yes, good idea.

**Comment by Pilchie** [comment] 2015-09-03 21:41
Moving back to @jasonmalinowski, since we are now on project.json.  This means that the DesignTimeBuild now fails in "ResolveNuGetPackageAssets", which will be fixed in "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets" soon.

**Comment by DustinCampbell** [comment] 2016-02-23 00:21
@jasonmalinowski, this is looking pretty stale. Any update?

**Comment by Pilchie** [comment] 2016-11-02 01:11
Let's try to look at this when we move to <PackageReference> over project.json.

**Comment by davkean** [comment] 2017-11-27 22:21
Stale and no longer occurs.

**Closed by davkean** 2017-11-27 22:21 UTC
Labels: Area-Project System, Bug
