### ISSUE TITLE
CSharpWinForms.Change control property in code

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7643] opened 2015-12-21 20:42 UTC
PR: [#7635](https://github.com/dotnet/roslyn/pull/7635) _Merge master into future_ by @roslyn-bot
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/142/

**1 Test Failures:**
CSharpWinForms.Change control property in code

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpWinForms.xml

![2015-12-21_18-08-44_68 - file1 before opening file2](https://cloud.githubusercontent.com/assets/9797472/11941948/fb96128a-a7e7-11e5-83e7-67a52c32fb54.png)

![2015-12-21_18-08-44_80 - after opening file2](https://cloud.githubusercontent.com/assets/9797472/11941963/1b0aba08-a7e8-11e5-963f-b1aae25520a8.png)

![2015-12-21_18-16-18_24 - exception system reflection targetinvocationexception](https://cloud.githubusercontent.com/assets/9797472/11941968/1f5e90de-a7e8-11e5-9cc0-e7b55ed063d9.png)

Bounty

**Comment by jmarolf** [comment] 2015-12-21 20:43
```
10:23:02 CSharpWinForms.xml
10:23:02 End - list of failing integration tests.
10:23:06 VS integration tests failed
10:23:06 ================================================================================
10:23:06 Dumping the log file for the last TAO test.  It may or may not include a failure.
10:23:06 ================================================================================
10:23:06 Test: Workspaces started: 12/21/2015 6:26:22 PM
10:23:06 	Executing action [12/21/2015 6:26:22 PM] DeleteFileOnDisk
10:23:06 	Executing action [12/21/2015 6:26:22 PM] StartTarget
10:23:06 Begin Waiting for Apex Communication
10:23:06 	Executing action [12/21/2015 6:26:22 PM] SetFeatureOption
10:23:06 	Executing action [12/21/2015 6:26:22 PM] SetFeatureOption
10:23:06  Scenario: Add Documents
10:23:06 	Executing action [12/21/2015 6:26:22 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:26:33 PM] AddNewDocument
10:23:06 	Executing action [12/21/2015 6:26:33 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:26:33 PM] CloseSolution
10:23:06  Scenario: Open C# solution then VB solution
10:23:06 	Executing action [12/21/2015 6:26:33 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:26:44 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:26:44 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:26:44 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:26:44 PM] PlaceCursor
10:23:06 	Executing action [12/21/2015 6:26:44 PM] VerifyTokenType
10:23:06 	Executing action [12/21/2015 6:26:50 PM] CloseFile
10:23:06 	Executing action [12/21/2015 6:26:50 PM] CloseSolution
10:23:06 	Executing action [12/21/2015 6:26:50 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:27:00 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:27:00 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:00 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:01 PM] PlaceCursor
10:23:06 	Executing action [12/21/2015 6:27:01 PM] VerifyTokenType
10:23:06 	Executing action [12/21/2015 6:27:06 PM] CloseFile
10:23:06 	Executing action [12/21/2015 6:27:06 PM] CloseSolution
10:23:06  Scenario: Project Properties
10:23:06 	Executing action [12/21/2015 6:27:06 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:27:17 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:27:17 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:17 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:17 PM] PlaceCursor
10:23:06 	Executing action [12/21/2015 6:27:17 PM] InvokeQuickInfo
10:23:06 	Executing action [12/21/2015 6:27:17 PM] VerifyQuickInfo
10:23:06 	Executing action [12/21/2015 6:27:17 PM] SetProjectProperty
10:23:06 	Executing action [12/21/2015 6:27:17 PM] InvokeQuickInfo
10:23:06 	Executing action [12/21/2015 6:27:17 PM] VerifyQuickInfo
10:23:06 	Executing action [12/21/2015 6:27:17 PM] CloseSolution
10:23:06  Scenario: Metadata Reference
10:23:06 	Executing action [12/21/2015 6:27:18 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:27:28 PM] AddReference
10:23:06 	Executing action [12/21/2015 6:27:28 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:27:28 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:28 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:28 PM] PlaceCursor
10:23:06 	Executing action [12/21/2015 6:27:28 PM] VerifyTokenType
10:23:06 	Executing action [12/21/2015 6:27:34 PM] RemoveReference
10:23:06 	Executing action [12/21/2015 6:27:34 PM] CloseSolution
10:23:06  Scenario: Project Reference
10:23:06 	Executing action [12/21/2015 6:27:34 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:27:45 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:27:55 PM] AddProjectReference
10:23:06 	Executing action [12/21/2015 6:27:55 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:27:55 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:55 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:56 PM] AddItem
10:23:06 	Executing action [12/21/2015 6:27:56 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:56 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:56 PM] RemoveProjectReference
10:23:06 	Executing action [12/21/2015 6:27:56 PM] CloseSolution
10:23:06  Scenario: Persistence Service
10:23:06 	Executing action [12/21/2015 6:27:56 PM] ExcludeScenarioInHost
10:23:06 	Executing action [12/21/2015 6:27:56 PM] SetFeatureOption
10:23:06 	Executing action [12/21/2015 6:27:56 PM] WriteFile
10:23:06 	Executing action [12/21/2015 6:27:56 PM] WriteFile
10:23:06 	Executing action [12/21/2015 6:27:56 PM] WriteFile
10:23:06 	Executing action [12/21/2015 6:27:56 PM] OpenProject
10:23:06 	Executing action [12/21/2015 6:27:56 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:27:57 PM] SetEditorText
10:23:06 	Executing action [12/21/2015 6:27:57 PM] SaveFile
10:23:06 	Executing action [12/21/2015 6:27:57 PM] WaitForDiagnostics
10:23:06 	Executing action [12/21/2015 6:28:05 PM] CloseSolution
10:23:06 	Executing action [12/21/2015 6:28:06 PM] OpenProject
10:23:06 	Executing action [12/21/2015 6:28:07 PM] WaitForDiagnostics
10:23:06 	Executing action [12/21/2015 6:28:14 PM] CloseSolution
10:23:06 	Executing action [12/21/2015 6:28:15 PM] DeleteFileOnDisk
10:23:06 	Executing action [12/21/2015 6:28:15 PM] SetFeatureOption
10:23:06 	Executing action [12/21/2015 6:28:15 PM] SetFeatureOption
10:23:06 	Executing action [12/21/2015 6:28:15 PM] CloseTarget
10:23:06 Test finished: 12/21/2015 6:28:15 PM
10:23:06 	Executing action [12/21/2015 6:28:15 PM] CloseTarget
10:23:06 Closing VS. force Close = True, closeVsToFreeHandles = False
10:23:06 
10:23:06 ================================================================================
10:23:06 Dumping logs of all failed TAO tests.
10:23:06 ================================================================================
10:23:06 ================================================================================
10:23:06  Dumping log file d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Open\Binaries\Release\VSIntegrationTestLogs\CSharpWinForms.txt
10:23:06 Test: CSharpWinForms started: 12/21/2015 6:16:13 PM
10:23:06 	Executing action [12/21/2015 6:16:13 PM] StartTarget
10:23:06 Begin Waiting for Apex Communication
10:23:06  Scenario: Add a control
10:23:06 	Executing action [12/21/2015 6:16:13 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:14 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:14 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:15 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:15 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:15 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:15 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:15 PM] CloseSolution
10:23:06  Scenario: Change control property
10:23:06 	Executing action [12/21/2015 6:16:16 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:16 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:16 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:16 PM] WinFormsEditControlProperty
10:23:06 		Property 'Text' changed to 'NewButtonText' successfully.
10:23:06 	Executing action [12/21/2015 6:16:16 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:16 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:17 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:17 PM] CloseSolution
10:23:06  Scenario: Change control property in code
10:23:06 	Executing action [12/21/2015 6:16:17 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:17 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:17 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:17 PM] WinFormsEditControlProperty
10:23:06 		Property 'Text' changed to 'ButtonTextGoesHere' successfully.
10:23:06 	Executing action [12/21/2015 6:16:18 PM] WinFormsVerifyControlProperty
10:23:06 	Executing action [12/21/2015 6:16:18 PM] CloseFile
10:23:06 	Executing action [12/21/2015 6:16:18 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:18 PM] VerifyEditorContainsText
10:23:06 --------------------------------
10:23:06 System.Exception: Actual and expected items don't match:
10:23:06 Expected: this.SomeButton.Text = "ButtonTextGoesHere";
10:23:06 Actual: namespace TestProj
10:23:06 {
10:23:06     partial class Form1
10:23:06     {
10:23:06         /// <summary>
10:23:06         /// Required designer variable.
10:23:06         /// </summary>
10:23:06         private System.ComponentModel.IContainer components = null;
10:23:06 
10:23:06         /// <summary>
10:23:06         /// Clean up any resources being used.
10:23:06         /// </summary>
10:23:06         /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
10:23:06         protected override void Dispose(bool disposing)
10:23:06         {
10:23:06             if (disposing && (components != null))
10:23:06             {
10:23:06                 components.Dispose();
10:23:06             }
10:23:06             base.Dispose(disposing);
10:23:06         }
10:23:06 
10:23:06         #region Windows Form Designer generated code
10:23:06 
10:23:06         /// <summary>
10:23:06         /// Required method for Designer support - do not modify
10:23:06         /// the contents of this method with the code editor.
10:23:06         /// </summary>
10:23:06         private void InitializeComponent()
10:23:06         {
10:23:06             this.components = new System.ComponentModel.Container();
10:23:06             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
10:23:06             this.Text = "Form1";
10:23:06         }
10:23:06 
10:23:06         #endregion
10:23:06     }
10:23:06 }
10:23:06 
10:23:06 
10:23:06 
10:23:06    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
10:23:06    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
10:23:06    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
10:23:06 ================================
10:23:06 
10:23:06 
10:23:06 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Open\Binaries\Release\Screenshots\2015-12-21_18-16-18_24 - Exception System.Reflection.TargetInvocationException.png
10:23:06 	Executing action [12/21/2015 6:16:18 PM] CloseSolution
10:23:06  Scenario: Add a Click() Handler
10:23:06 	Executing action [12/21/2015 6:16:18 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:19 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:19 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:19 PM] WinFormsEditControlEvent
10:23:06 		Handler 'ExecuteWhenButtonClicked' added for event 'Click' successfully.
10:23:06 	Executing action [12/21/2015 6:16:19 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:19 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:20 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:20 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:20 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:20 PM] CloseSolution
10:23:06  Scenario: Rename the control
10:23:06 	Executing action [12/21/2015 6:16:20 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:21 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:21 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:21 PM] WinFormsEditControlProperty
10:23:06 		Property 'Text' changed to 'ButtonTextValue' successfully.
10:23:06 	Executing action [12/21/2015 6:16:21 PM] WinFormsEditControlEvent
10:23:06 		Handler 'SomeButtonHandler' added for event 'Click' successfully.
10:23:06 	Executing action [12/21/2015 6:16:21 PM] WinFormsEditControlProperty
10:23:06 		Property 'Name' changed to 'SomeNewButton' successfully.
10:23:06 	Executing action [12/21/2015 6:16:21 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:21 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:21 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:21 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:21 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:21 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:21 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:21 PM] CloseSolution
10:23:06  Scenario: Remove event handler
10:23:06 	Executing action [12/21/2015 6:16:21 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:22 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:22 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:22 PM] WinFormsEditControlEvent
10:23:06 		Handler 'FooHandler' added for event 'Click' successfully.
10:23:06 	Executing action [12/21/2015 6:16:22 PM] WinFormsEditControlEvent
10:23:06 		Handler '' added for event 'Click' successfully.
10:23:06 	Executing action [12/21/2015 6:16:22 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:22 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:22 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:22 PM] CloseSolution
10:23:06  Scenario: Change Accessibility
10:23:06 	Executing action [12/21/2015 6:16:22 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:23 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:23 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:23 PM] WinFormsEditControlProperty
10:23:06 		Property 'Modifiers' changed to 'Public' successfully.
10:23:06 	Executing action [12/21/2015 6:16:23 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:23 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:23 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:23 PM] CloseSolution
10:23:06  Scenario: Delete a control
10:23:06 	Executing action [12/21/2015 6:16:23 PM] AddProject
10:23:06 	Executing action [12/21/2015 6:16:24 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:24 PM] WinFormsAddControl
10:23:06 		Control 'SomeButton' added successfully.
10:23:06 	Executing action [12/21/2015 6:16:24 PM] WinFormsDeleteControl
10:23:06 		Control 'SomeButton' deleted successfully.
10:23:06 	Executing action [12/21/2015 6:16:24 PM] ExecuteCommand
10:23:06 	Executing action [12/21/2015 6:16:24 PM] OpenFile
10:23:06 	Executing action [12/21/2015 6:16:25 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:25 PM] VerifyEditorContainsText
10:23:06 	Executing action [12/21/2015 6:16:25 PM] CloseSolution
10:23:06 	Executing action [12/21/2015 6:16:25 PM] CloseTarget
10:23:06 Test finished: 12/21/2015 6:16:25 PM
10:23:06 	Executing action [12/21/2015 6:16:25 PM] CloseTarget
10:23:06 Closing VS. force Close = True, closeVsToFreeHandles = False
10:23:06 
10:23:06 ================================================================================
```

**Comment by DustinCampbell** [comment] 2015-12-21 21:45
Note that I'm out of the office for 3 weeks. If this needs looked at soon, somebody else will need to take a look.

**Comment by davkean** [comment] 2015-12-21 22:40
@DustinCampbell Dude, you can't look at this on the plane? Isn't this the whole point of git so devs don't have holidays anymore? :)

**Comment by DustinCampbell** [comment] 2015-12-21 22:57
err... no. Not on a plane. Just separating life and work as appropriate.

**Comment by davkean** [comment] 2015-12-21 23:13
@brettfo Can you take a loop? This test looks like it might be still flaky, I believe Dustin made some changes to make it easier to diagnose.

**Comment by davkean** [comment] 2015-12-22 17:37
This failed again: http://dotnet-ci.cloudapp.net/view/roslynpr/job/roslyn-internal_prtest_win_vsi_p3/lastFailedBuild/consoleFull#42085259261aefe2b-268e-4e71-8c03-11b4c0acbfbc

**Comment by brettfo** [comment] 2015-12-22 22:23
In both logs, the failure is that `Form1.Designer.cs` doesn't contain the expected line in `InitializeComponent()` after a button's `Text` property is set (and verified twice.)  I can't repro this (even with pegging my CPU and dropping the test process's priority to below normal) which makes me think it's a race in either regenerating the backing file or flushing it to disk.

@DustinCampbell, is there an event we can listen to for generated files being refreshed?  If not, @tannergooding had an idea of trying to force regeneration by building the project.

**Comment by DustinCampbell** [comment] 2015-12-23 00:41
Hey @brettfo -- that's exactly my analysis from looking at it briefly. Would forcing a save of the designer cause it to flush deterministically?

**Comment by brettfo** [comment] 2016-02-12 19:20
Looking through all available Jenkins logs I haven't seen any failures of this test (logs go back 2 weeks.)  Optimistically closing and it can be re-opened if more failures are found.

**Comment by genlu** [comment] 2016-02-14 03:24
Sorry guys, I believe I just hit this again.
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/147/

**Comment by CyrusNajmabadi** [comment] 2016-02-20 00:58
I also hit this:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/292/console

**Comment by davkean** [comment] 2016-02-20 19:25
And again: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/281/

**Comment by davkean** [comment] 2016-02-20 19:26
Please do not close this until we've either made a change to fix this, or made a change to better diagnose this.

**Comment by davkean** [comment] 2016-02-20 19:29
We have put Update 1 on the machine, so things might be differently setup or there might be more timing issues.

**Comment by jmarolf** [comment] 2016-03-03 20:56
failed in https://github.com/dotnet/roslyn-internal/pull/630
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/181/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpWinForms.txt

**Comment by brettfo** [comment] 2016-03-03 21:01
I'm going to yield to @DustinCampbell on this one; given that force~~-choking~~-saving or building doesn't solve this, is there an event we can listen to, short of adding calls to `Thread.Sleep()` or polling?

**Comment by davkean** [comment] 2016-03-16 18:30
Hit this again: https://github.com/dotnet/roslyn/issues/7643

**Comment by davkean** [comment] 2016-03-16 18:31
@Pilchie @DustinCampbell Can we please assign this to someone?

**Comment by MattGertz** [comment] 2016-03-28 14:02
Please reassign.

**Comment by jaredpar** [comment] 2016-06-23 17:54
@Pilchie this is sttill makred as Urgency-Now and hasn't been updated in 3 months.  Can we get an update on this issue?

**Comment by Pilchie** [comment] 2016-06-23 18:22
Believed to be the same underlying issue as the navigation tests where the file is not saving correctly on close.

@jasonmalinowski any chance to look at related logs for failures in other tests yet?

**Comment by jasonmalinowski** [comment] 2016-06-23 18:27
I haven't been able to look at the other ones yet, no. 😦

**Comment by Pilchie** [comment] 2016-07-19 20:09
Dropping to urgency-soon, since the offending scenario is disabled.  We believe the root cause is the same as the issue in #9602.

**Comment by Pilchie** [comment] 2017-01-07 00:54
Moving to 2.1, as we won't address this in escrow.

**Comment by Pilchie** [comment] 2017-03-30 01:54
This is currently enabled [here](http://source.roslyn.io/#Roslyn.VisualStudio.IntegrationTests/VisualBasic/BasicWinForms.cs,984ac5e6dcf3b537) and [here](http://source.roslyn.io/#Roslyn.VisualStudio.IntegrationTests/CSharp/CSharpWinForms.cs,978ed1eef27109ae)

**Closed by Pilchie** 2017-03-30 01:54 UTC
Labels: Area-IDE, Flaky, Test, Urgency-Soon
