### ISSUE TITLE
Very edge case ActivityLog.xml dialog in InlineRename

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#34866] opened 2019-04-09 15:00 UTC
**Version Used**: 
Any.

**Steps to Reproduce**:

1. Start renaming
2. Make multi-selection
3. Type something

**Expected Behavior**:
No exception.
**Actual Behavior**:
Exception happen:
```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

I found this by looking at code... It's super unlikely user would do multiselection while renaming variable...

**Comment by sharwell** [comment] 2019-04-11 20:18
Duplicate of #34903

**Comment by sharwell** [comment] 2019-04-11 20:19
Decided not to make this a duplicate since this one is much easier to resolve than #34903

**Closed by sharwell** 2019-04-11 20:18 UTC
Labels: Area-IDE, Bug, help wanted
