### ISSUE TITLE
Generate field/property have inconsistent ordering between constructor argument and assignment

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19240] opened 2017-05-04 01:31 UTC
If I go via constructor parameter, property is listed first:

![image](https://cloud.githubusercontent.com/assets/1103906/25687879/3333e780-30bd-11e7-8b66-ad0328b7a237.png)

If I go via assignment, field is listed first:

![image](https://cloud.githubusercontent.com/assets/1103906/25687875/26c13868-30bd-11e7-8889-b39f3c715931.png)

**Comment by CyrusNajmabadi** [comment] 2017-05-04 01:51
This is by design as well.  Assignment actually orders based on what type of symbol you probably meant (with a lowercase name preferring field, and uppercase name preferring property).  However, in the case where we're *creating* the symbol entire, and we're creating the name on the fly, we have no preferred ordering, and we default to suggesting properties first over fields.

**Comment by davkean** [comment] 2017-05-04 01:55
@CyrusNajmabadi Makes sense, never noticed the order differed based on case, that's nifty.

I have a bunch of these things were the defaults/order never seem to match my preference, not sure what to do with bugs like this. I always prefer fields over properties.

**Comment by CyrusNajmabadi** [comment] 2017-05-04 01:56
Not sure what to do either.  I always prefer readonly things :)  Maybe some sort of system that learns.  We can assign to @kuhlenh to figure out if there's anything we could do here :)

**Comment by davkean** [comment] 2017-05-04 01:58
@CyrusNajmabadi Yeah, something similar to what adding a using does (does sorted order if it's already sorted), looks at the code and says "hey he tends to use read-only fields in this class, let's default to that"

**Comment by davkean** [comment] 2017-05-04 02:00
I'll close this one though as it's not really an actionable bug.

**Comment by CyrusNajmabadi** [comment] 2017-05-04 02:00
That's a great idea.  The code already tries to infer where to put the member based on your other parameters/initialization statements.   We could definitely try to infer prop vs field.

**Comment by CyrusNajmabadi** [comment] 2017-05-04 02:00
Reopening.  I think we can do better here in the non-empty type case.  I think we'll end up just picking a default when you have nothing for us to go off of.

**Comment by CyrusNajmabadi** [comment] 2017-05-10 19:33
Improved things a bit here: https://github.com/dotnet/roslyn/pull/19291

I'm happy with this overall.  if you find yourself wanting more heuristicy improvements, let us know!

**Closed by CyrusNajmabadi** 2017-05-10 19:33 UTC
Labels: Area-IDE, Bug
