### ISSUE TITLE
C#: 'new' completion doesn't work for field above attribute

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8261] opened 2016-01-30 00:11 UTC
``` C#
using System;

class B
{
    object o = new // <-- press SPACE here
    [CLSCompliant(true)]
    int x;
}
```

It looks to me like the parse tree is in a shape that we don't expect. The attribute gets treated as the `[]` in an implicit array creation expression.

**Comment by DustinCampbell** [comment] 2016-02-02 17:17
This came through VS Feedback

**Comment by rchande** [comment] 2017-01-05 23:44
Dupe of https://github.com/dotnet/roslyn/issues/15804

**Closed by rchande** 2017-01-05 23:44 UTC
Labels: Area-IDE, Bug
