### ISSUE TITLE
Error with flow analysis when working with null coalescing and ternaries

### ISSUE THREAD

**Issue by Dispersia** [dotnet/roslyn#41369] opened 2020-02-03 18:40 UTC
**Version Used**: 
dotnet core 3.1

**Steps to Reproduce**:
```
var dict = new Dictionary<string, string>();
var temp = dict?.TryGetValue("test", out var val) ?? false
      ? val
      : "not found";
```

**Expected Behavior**:
 Should evaluate to not found

**Actual Behavior**:
 val errors with "use of unassigned local variable". There should be no way it gets to the true statement without it being defined in this scenario

**Comment by jcouv** [comment] 2020-02-03 21:27
Tagging @AlekseyTs since relates to analysis of out vars.

**Comment by AlekseyTs** [comment] 2020-02-03 21:40
@jcouv How exactly this relates to out vars?

**Comment by jcouv** [comment] 2020-02-03 21:48
@AlekseyTs The issue is whether the out var was assigned in a complex conditional expression.

**Comment by AlekseyTs** [comment] 2020-02-03 21:53
Neither coalesce, nor conditional access are relational operators. The ```dict?.TryGetValue("test", out var val) ?? false``` is also not a constant expression. There is also the following statement in the language specification: "In other words, for purposes of control flow analysis, a non-constant expression of a given type is considered to have any possible value of that type."

**Comment by AlekseyTs** [comment] 2020-02-03 21:55
> The issue is whether the out var was assigned in a complex conditional expression.

Are you saying that the issue is not observed with a regular out argument? Otherwise, we can say that this issue relates to a constructor invocation because it is used in the code sample.

**Comment by jcouv** [comment] 2020-02-03 22:06
> Are you saying that the issue is not observed with a regular out argument? 

I have not tried. That'd be an interesting thing to do.

**Comment by RikkiGibson** [comment] 2020-02-03 22:17
It seems like when the receiver contains a conditional access, the 'out' arguments to a call do not become definitely assigned. I suspect this is the specified behavior.

```cs
public class C
{
    void M1(out string s)
    {
        s = "a";
    }
    
    public static void M2(C c)
    {
        string s;
        c?.M1(out s);
        _ = s.ToString(); // error CS0165: Use of unassigned local variable 's'
    }
}
```

**Comment by RikkiGibson** [comment] 2020-02-03 22:20
To work around this I suggest changing the code to something like this:

```cs
var dict = new Dictionary<string, string>();
var temp = dict != null && dict.TryGetValue("test", out var val)
      ? val
      : "not found";
```

**Comment by RikkiGibson** [comment] 2021-05-14 20:44
This issue will be fixed by the "improved definite assignment" feature in C# 10. dotnet/csharplang#4465 #51463 

The feature branch actually currently handles this scenario. [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsC2AHBB7ANwgBNViIx0A7dGCVKZZdAcyswipgB8BiKuABtBUYIIgACTqPEBYAFAKAAgAYJSgIwAWANwKFBKAgnF0AYxgSAvBKoQA7hIAi5mOjxUjATwA8mlQA06hoqAHwAFACUevL+EnQ41iauAPwAdAAqCF4A4hAwAGpQgnAQ4QBEdMgw5UF4cJaGxoaCkRIpKRJgxcgQChIDg50t/YMDIBLlVHiWYPVUxOUxQA==).

**Closed by RikkiGibson** 2021-05-14 20:44 UTC
Labels: Area-Compilers
