### ISSUE TITLE
When the IPropertyInitializer's Target value is an indexed property or ref returning method, there is no way to get the arguments specified to that target

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18712] opened 2017-04-14 19:46 UTC
Reported by @evildour Refer dotnet/roslyn-analyzers#1142 (comment)

**Comment by evildour** [comment] 2017-04-16 03:37
Note: the issue title (as well as my original comment) is wrong. It should say "When the **IAssignmentExpression**'s Target value..."

However, I just tried this out and this is actually not the case in general: for normal assignments to indexed properties and ref returning methods (I had just made an assumption about this part), you actually can get the arguments from the `IAssignmentExpression.Target` value. I tried by analyzing the three assignments in this code:

```csharp
void Foo()
{
    var x = new [] { 1, 2, 3 };
    x[1] = 5;
    GetElement(0, x) = 9;
    var y = new Dictionary<int, int>();
    y[1] = 5;
}

ref int GetElement(int index, int[] array)
{
    return ref array[index];
}
```

It is only when looking at the IAssignmentExpression of an object creation expression's member initialization of an indexed property that you cannot get the arguments for the index. It can be reproduced with this code:

```csharp
var tree = CSharpSyntaxTree.ParseText(@"
using System.Collections.Generic;
class C
{
    void Foo()
    {
        var x = new Dictionary<int, int> { [1] = 2 };
    }
}
",
CSharpParseOptions.Default.WithFeatures(
    new[] { new KeyValuePair<string, string>("IOperation", "true") }));
var compilation = CSharpCompilation.Create(
    "out.dll",
    new[] { tree },
    new[] { MetadataReference.CreateFromFile(typeof(int).Assembly.Location) },
    new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
var semanticModel = compilation.GetSemanticModel(tree);
var objectCreationExpression =
    tree.GetRoot().DescendantNodes().OfType<ObjectCreationExpressionSyntax>().First();
var operation = (IObjectCreationExpression)semanticModel.GetOperation(objectCreationExpression);
foreach (var initializer in operation.MemberInitializers)
{
    var assignmentTarget = ((IAssignmentExpression)semanticModel.GetOperation(initializer.Syntax)).Target;
    // assignmentTarget only implements IOperation and so the index arguments cannot be obtained.
}
```

Note, however, that getting the IAssignmentExpression is only possible due to #18710 so this code will not work once that is fixed. In addition, if #18709 is fixed, one can get the arguments directly from `initializer`, so this may not be worth fixing.

**Comment by mavasani** [comment] 2017-07-07 19:26
Should get fixed with https://github.com/dotnet/roslyn/pull/20689

**Closed** 2017-07-12 16:00 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation, Urgency-Soon
