### ISSUE TITLE
[Regression] Unused using classifier does not run after you paste

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4724] opened 2015-08-21 21:39 UTC
Repro on latest installdogfood:

1. File -> New C# Console Application
2. Open Program.cs (Make note the unused usings are "greyed" out)
3. Select the entire source file, copy and then paste over the entire buffer

Expected: Unused usings to still greyed out
Actual: Unused usings are not greyed out, but "Remove unnecessarily usings" lightbulb still appears

**Comment by Pilchie** [comment] 2015-08-22 02:37
I've been seeing a lot of issues with diagnostics in general (things not cleaning up until I make a subsequent edit, etc).  I wonder if it's related to the new diagnostic analyzer engine.

@mavasani

**Comment by mavasani** [comment] 2015-08-22 07:04
Yes, that is pretty likely culprit. I'll take a look at this bug, @pilchie please let me know if you have repros for other issues.

**Comment by DustinCampbell** [comment] 2015-08-22 14:51
I don't think that's the problem here. In this case, the light bulb is there but the usings are not faded. So, the diagnostic is there but the UI treatment is missing. Smells like the tagger issue that Cyrus just submitted #4735 for.

**Comment by davkean** [comment] 2015-08-22 16:27
Yep, same thing. As called out in repro, light bulb is still present just no faded usings.

**Comment by mavasani** [comment] 2015-08-22 17:49
Great, thanks. 

Kevin, if you have any other repros for stale diagnostics, then please let me know.

**Comment by Pilchie** [comment] 2015-08-22 19:57
Will do. I definitely saw strangeness yesterday, will try to isolate some of it into a repro.

**Comment by CyrusNajmabadi** [comment] 2015-08-22 21:34
Yup.  This was caused by my large tagger refactoring.  Fortunately it was very simple to fix.  PR is out with: https://github.com/dotnet/roslyn/pull/4735

**Comment by davkean** [comment] 2015-08-23 03:52
Unrelated to this bug, I've also seen stale squiggles - I've been unable to repro consistently. When I get into that state would a dump or Jason's extension be good enough to figure out what's going on?

**Comment by CyrusNajmabadi** [comment] 2015-08-23 18:16
@davkean It's likely the same issue.  But the Diagnostic-Classifier and the Diagnostic-Squiggler share the same abstract base class I fixed in the linked PR.  As such, they both have the same ref counting issue.

**Closed** 2015-08-24 21:24 UTC
Labels: Area-IDE, Bug
