### ISSUE TITLE
'CS8602 Dereference of a possibly null reference' in a local function

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#39362] opened 2019-10-17 19:04 UTC
**Version Used**: New in VS 16.4p2, not present in 16.4p1 or 16.3.5

The local function is never called from a point where `value` might be null:

```cs
class C
{
    void M()
    {
        string? value = null;
        value = "Hi";

        LocalFunction();

        void LocalFunction()
        {
            // CS8602 Dereference of a possibly null reference.
            // ↓
            value.ToString();
        }
    }
}
```

**Comment by RikkiGibson** [comment] 2019-10-17 20:57
Looks like a dupe of #38548. /cc @agocke

Thanks for reporting @jnm2!

**Closed by RikkiGibson** 2019-10-17 20:57 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types, Resolution-Duplicate
