### ISSUE TITLE
CSharpWinForms.ChangeControlProperty is flakey

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19858] opened 2017-05-30 03:47 UTC
See https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/4779/

**Comment by Pilchie** [comment] 2017-05-30 16:29
Dupe of #19191.

**Closed by Pilchie** 2017-05-30 16:29 UTC
