### ISSUE TITLE
New line setting for C# switch expression is missing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39504] opened 2019-10-24 22:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/785993/new-line-setting-for-c-switch-expression-is-missin.html)._

---
I hope that &quot;Place open brace on new line for switch expression&quot; setting will be added to 
&quot;Options -&gt; Text Editor -&gt; C# -&gt; Code Style -&gt; Formatting -&gt; New Lines -&gt; New line options for braces&quot;.

Visual Studio now formats the switch expression as follows.

```cs
int value = sample switch
{
    EnumSample.A =&gt; 0,
    EnumSample.B =&gt; 1,
    _ =&gt; 2,
};
```

But I want to format as follows.

```cs
int value = sample switch {
    EnumSample.A =&gt; 0,
    EnumSample.B =&gt; 1,
    _ =&gt; 2,
};
```

---
#### Visual Studio Feedback System on 10/21/2019, 11:04 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2019-10-24 23:00
Duplicate of #36913

**Closed by sharwell** 2019-10-24 23:00 UTC
