### ISSUE TITLE
Introduce local for incomplete expression generates code with errors

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#28526] opened 2018-07-13 23:46 UTC
Ported from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646487
Affected Branch: [27907.0.d15.8]
Affected Build: 15.8.0 Preview 4.0
Affected Product Language: 

Steps to reproduce:

1. Input in method in C# class following:
var a = 1 +
2. Place cursor after plus
3. Open Quick Actions

Expected: there are no introduce local options for incomplete expression
Actual: there are introduce local and introduce local for all options available

4. Choose "Introduce local for '1 +'

Actual: code with errors is generated

[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/ETEY1x9-oM9Gu3kUOPD-tGkBk4DC-zr0w-xmwooQumOsDA?e=nXCqQn)

**Comment by jhinder** [comment] 2018-07-14 11:08
I cannot access the repro gif after logging in with my Microsoft/live.com account. The error site says something about the user not being found in the directory (or something similar, I get a translated site).

**Comment by CyrusNajmabadi** [comment] 2018-07-15 17:47
Introduce-local should probably not accept trees with syntax-errors *if* there is no selection on the part of the user.

**Comment by Neme12** [comment] 2018-07-15 19:00
I guess I don't really see what the issue is here. Yes, the resulting code has an error but so does the original. There's no new error introduced.

**Comment by CyrusNajmabadi** [comment] 2018-07-15 19:15
My primary concern is that the feature is offered in the first place.  if i have ```1 + $$```, then bringing up 'introduce local' isn't really even a valid thing to do in the first place.

The intent of introduce local started as "user should be able to select some sub-expr and make an expression".  it expanded out to also include "and if they're on a basic term, allow making a local for that as well" based on some feedback we got.  But it was never "show up when you're on non-existent code.

IMO, the feature is simply not working as intended.  Sometimes that's ok, if there's value in teh deviation.  But there's no value here, and i also consider just being in the lightbulb list a negative as it distracts and interferes with people bringing up the list for other purposes.

**Comment by v-rodudi** [comment] 2018-08-30 08:46
JFYI: ticket author @v-rodudi won't be available after 9/4 so please ask repro-related questions before this date if they are. 
![introduce-local-for-incomplete-expression](https://user-images.githubusercontent.com/38646068/44840720-58130900-ac4a-11e8-92de-60baeea8c1cf.gif)

**Comment by CyrusNajmabadi** [comment] 2022-10-31 19:54
I don't repro this.  Closing out.

**Closed by CyrusNajmabadi** 2022-10-31 19:54 UTC
Labels: Bug, help wanted, Area-IDE
