### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicChangeSignatureDialog.VerifyCodeRefactoringOffered Is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17398] opened 2017-02-26 07:49 UTC
Failed in [this](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/434) run

```
Stacktrace

MESSAGE:
System.Runtime.InteropServices.COMException : Command "View.ShowSmartTag" is not available.
+++++++++++++++++++
STACK TRACE:
Server stack trace:
    at EnvDTE._DTE.ExecuteCommand(String CommandName, String CommandArgs)
    at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c.<ShowLightBulb>b__25_0()
    at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.Invoke(Action callback) 
    at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.ShowLightBulb()
    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) 

    Exception rethrown at [0]: 
    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) 
    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) 
    at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.ShowLightBulb() 
    at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.InvokeCodeActionList() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractEditorTest.cs:line 164 
    at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicChangeSignatureDialog.VerifyCodeRefactoringOffered() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicChangeSignatureDialog.cs:line 31
```

**Comment by Pilchie** [comment] 2017-02-27 18:09
Duplicate of #17393

**Closed by Pilchie** 2017-02-27 18:09 UTC
Labels: Area-IDE, Flaky, Resolution-Duplicate
