### ISSUE TITLE
IOperation: VB - BoundOmittedArgument as an argument of BoundCall should probably be surfaced as IArgument ...

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8794] opened 2016-02-17 03:06 UTC
with value equivalent to the node produced by LocalRewriter.VisitOmittedArgument.

**Comment by jinujoseph** [comment] 2017-07-04 00:29
@genlu already done ?

**Comment by jinujoseph** [comment] 2017-09-29 21:07
dupe of https://github.com/dotnet/roslyn/issues/21292

**Closed by jinujoseph** 2017-09-29 21:07 UTC
Labels: Area-Analyzers, Bug, Language-VB, New Feature - IOperation
