### ISSUE TITLE
Improve `nameof` completion

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60669] opened 2022-04-09 13:42 UTC
The only possible syntax of `nameof` is `nameof(some_name)`. So, it would be nice if:

**Start code:**
```csharp
var a = name$$
```
Apply `nameof` completion

**Expected result:**
```csharp
var a = nameof($$)
```

**Actual result:**
```csharp
var a = nameof$$
```

`$$` respresents cursor position.

The same for VB and its `NameOf`

**Comment by davidwengier** [comment] 2022-04-10 07:48
Not sure why this would be different from https://github.com/dotnet/roslyn/issues/12363, but if this is to be implemented it should only be done if we can confirm that editor overtyping of the opening paren works as expected, and automatic brace completion is turned ON.

**Comment by DoctorKrolic** [comment] 2022-04-10 08:06
It is different. Implement brace completion in member calls is harder, because there are edge cases, for instance, where method is treated as delegate, and brace completion is not needed. In `nameof`, as I said, `nameof(some_name)` is the only possible syntax.

> editor overtyping of the opening paren works as expected, and automatic brace completion is turned ON.

Really? There is no other way to control cursor position when inserting completion?!

**Comment by davidwengier** [comment] 2022-04-10 08:36
My comment about brace completion is not about controlling the cursor, it's about people like me who only want the close parens to be inserted in the editor when we specifically type them, or perform some other non-regular-typing gesture like Tab+Tab.

> `nameof(some_name)` is the only possible syntax

https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUAG4TIAEMEYApgPYBmtAvLQEQAWTADaCWPANwV8xAJwAKBs3YBKMUA=== 😛

**Comment by DoctorKrolic** [comment] 2022-04-10 08:55
Uh, this is a contextual keyword...

However, in the given example completion item is not a keyword completion:
![devenv_PRzPt3tTbH](https://user-images.githubusercontent.com/70431552/162610474-d888f6fd-d9f7-4152-94a7-d3e9a71faeaf.png)
![devenv_Aix54BWNAX](https://user-images.githubusercontent.com/70431552/162610524-9e0445ff-3890-405e-8508-2a00f4fa521f.png)
_Icons are different here and completion items, I believe, are comming from different providers._

**Comment by davidwengier** [comment] 2022-04-10 09:17
I wasn't thinking about implementation, so maybe this falls out of the current design, that's cool. I have basically no idea how completion works anyway.

I'm just flagging it as something to consider (and would probably want to see a test for it, if this gets done), lest someone saw the "only possible syntax" and thought they didn't have to at least consider it.

**Comment by DoctorKrolic** [comment] 2022-04-10 09:23
> only possible syntax

Before working with roslyn I thought that the list of contextual keywords is very small. I was suprised to know, that almost all (or even all, not sure here) keywords, that are not from C# v1 are contextual. I still forget it when saying something like this 🙂

**Comment by sharwell** [comment] 2022-04-19 19:01
Duplicate of #12363

**Comment by sharwell** [comment] 2022-04-19 19:02
This is effectively a duplicate of #12363. Syntactically, `nameof` is just a method invocation, and the new completion mode for method invocations is covered by #12363.

**Closed by sharwell** 2022-04-19 19:01 UTC
Labels: Area-IDE, untriaged
