### ISSUE TITLE
Removing unused variables doesn't update the IDE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35943] opened 2019-05-24 17:24 UTC
VSF_TYPE_MARKDOWNCS0649 warning that you can remove variables that are not used doesn't always update the IDE. See screenshot.
The variables were removed but the IDE still thinks they are there.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/581662/removing-unused-variables-doesnt-update-the-ide.html
VSTS ticketId: 898309_
_These are the original issue comments:_

Visual Studio Feedback System on 5/24/2019, 03:14 AM (7 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-05-24 17:28
Reproduces on 16.1

```
namespace BugTriageApp
{
    class Program {
        Hashtable table;  // CS0649  

        public void Func(object o, string p)
        {
            //table = new Hashtable();  
            table[p] = o;
        }

        public static void Main() { }
    }
}
```

1. Compiling code above gives warning CS0649 "Field 'Program.table' is never assigned to, and will always have its default value null"
2. Uncomment the line to create HashTable object. 

Expected Behavior: The warning should go away.

Observed Behavior: The warning stays

Note: the warning goes away after rebuilding the solution.

**Comment by jasonmalinowski** [comment] 2019-06-24 17:53
@vatsalyaagrawal Why the Need Design Review tag on this one? This appears to just be a bug.

**Comment by Dean-NC** [comment] 2019-10-22 18:54
I logged a developercommunity.visualstudio.com bug that was closed, and they referred me to this roslyn issue. This issue doesn't sound like mine, so here's mine...please verify it's the same underlying issue that you're tracking.

[](https://developercommunity.visualstudio.com/content/problem/782389/warning-that-field-is-never-assigned-to-and-will-a.html)

```
class Class1
{
	Dictionary<int, Options> _accountList;
	
	public void Work()
	{
		Load();

		_accountList.TryGetValue(3, out Options myOpts);

		if (myOpts != null)
		{

		}
	}

	private void Load()
	{
		_accountList.Add(1, null);
	}
}
```

1. Add the code for Class1.cs above to a project, and save the file/project.
2. Build the project using the main menu “Build”, then choosing “Build project”. You should now get a green squiggly underline for the declaration of _accountList, saying that field _accountList is never assigned, and will always have the default value.
3. In the Load() method, before the _accountList.Add line, add a new line: _accountList = new Dictionary<int, Options>();
4. Save the file. The green squiggly warning does not go away until you build the project again.

If my issue is different, please let me know so I can have my bug report re-opened.
Thanks.

**Comment by Dean-NC** [comment] 2020-01-03 16:43
Any update??

**Comment by CyrusNajmabadi** [comment] 2020-03-09 03:41
@mavasani i can't repro either of hte cases above.  My guess is that this is something you may hve fixed. If so, can you close this out?

**Comment by Dean-NC** [comment] 2020-03-09 13:57
This happens in 16.5 preview 5:
https://developercommunity.visualstudio.com/content/problem/942326/squiggly-line-not-cleared-on-refactoring-method-si.html

**Comment by Dean-NC** [comment] 2020-07-14 13:10
The code I posted above on Oct. 22, 2019 still reproduces for me on **16.6.0**, but I'm not sure now if the behavior is correct or not. If I close the solution, delete the .vs/bin/obj folders, open the solution, open the class1.cs file, and let it sit, there are no warnings. When compiling, I get the CS0649 warning. Then, I un-comment the line to assign the dictionary and save the file. The warning does not go away. It will go away when I build.
So, the warning shows only when compiling, and goes away when compiling. Since the warning only shows when first compiling, then I guess it's correct to go away when compiling??

**Comment by mavasani** [comment] 2020-07-14 13:18
`CS0649` is a build-only diagnostic, hence we do not update it during live analysis/intellisense. This has been the behavior in VS for as long as I know (at least a decade). There is no way to fix/change this behavior in the IDE side. We would need to change the compiler layer to start reporting `CS0649` in `semanticModel.GetDiagnostics()` instead of `compilation.GetDiagnostics()`, which seems an expensive amount of code churn for a behavior that has been present for a long time.

I think we have to close this issue as by design.

**Comment by premradhakrishnan** [comment] 2022-10-04 08:07
Still having the issue on version 17.3.1. If the issue cannot be fixed, could something be appended at the end of the error message to say something like "Project may need to be rebuild..". This might give developers a hint and save debugging time. The general behavior of Visual Studio has always been that when code is updated errors or warnings disappear if the fix is correct. It is very counter intuitive when this doesn't happen and therefore I think any steps to improve UX will be appreciated by the community.

**Comment by Dean-NC** [comment] 2022-10-04 19:26
Mavasani's comment on Jul 14, 2020 seems to be correct, that complaints like "is never assigned to, and will always have its default value null" will go away (if you fixed it) not when saving the file, but when building. With older Visual Studio (2015 and older) & .NET framework, saving the file would cause these complaints to get updated, but now it's only during build.

**Comment by CyrusNajmabadi** [comment] 2022-10-04 19:34
We have never had any special behavior on save afaik.  It's unclear to me how that would have affected things.

**Comment by Dean-NC** [comment] 2022-10-05 18:02
I could be mistaken & mis-remembering older VS versions. I'm good on this now.

**Comment by CyrusNajmabadi** [comment] 2023-02-10 18:50
Closing out as this is working as intended.  This is a build-only diagnostic.  It only goes away on the next build.

**Closed by CyrusNajmabadi** 2023-02-10 18:50 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community
