### ISSUE TITLE
error MSB6006: "csc.dll" exited with code 139

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#26505] opened 2018-04-30 15:18 UTC
**Version Used**: 
the version embedded in the dotnet SDK version 2.2.100-preview1-008633 (daily build)

**Steps to Reproduce**:

1. edit nuget.config file: <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
2. navigate to any folder u like and using "dotnet new console" to create a .net core 2.1 console application
3. dotnet build

note: my system is ubuntu 16.04 ARM64

**Expected Behavior**:
successfully build.

**Actual Behavior**:
.../sdk/2.2.100-preview1-008633/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/nvidia/Desktop/test/test.csproj]

build log:s (with -v diag)
[log.txt](https://github.com/dotnet/roslyn/files/1961082/log.txt)

**Comment by jcouv** [comment] 2018-05-03 02:59
@hez2010 Here's what I'd recommend you try:

Here are some steps to see the reason for the compilation failing:
1. run the problematic `build` command, but add the option for binary logging `/bl` (for example, `dotnet build /bl`)
2. assuming this reproduced the issue, open the `msbuild.binlog` file with the [binary log viewer](https://github.com/KirillOsenkov/MSBuildStructuredLog).
3. the log viewer should show the failed `Csc` task (as shown below)
4. you can view and copy the command-line arguments to a text file `repro.rsp`, removing the first two chunks (the first one for "dotnet.exe" and the second one for "csc.dll")
5. re-use those two chunks to run `dotnet.exe csc.dll @repro.rsp`
6. this should repro, but also print out the compiler diagnostics

![image](https://user-images.githubusercontent.com/12466233/36326802-42886daa-1311-11e8-87bd-14c52067fcb9.png)

Tagging @livarcocc, in case he has something to add. Livar, are there any known issues where CLI doesn't print out the compiler diagnostics? I thought there was one, but it had been fixed.

**Comment by jcouv** [comment] 2018-06-04 23:27
I didn't hear back on my request for additional information, so I'll go ahead and close the issue.
The problem of the error details not getting displayed was fixed in the compiler (https://github.com/dotnet/roslyn/pull/27349) and we'll have to wait for that fix to make its way into the CLI.
If the problem still occurs, please open an issue with more details. Thanks

**Closed by jcouv** 2018-06-04 23:27 UTC
Labels: Area-Compilers

**Comment by kxxt** [comment] 2018-07-06 10:20
I got this error , too.

I found this url to download dotnetcore sdk , and tried it on arm64  :
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-linux-arm64-binaries 

I can run dotnetcore apps which I complied on Windows , but when I tried to build a helloworld app , an error occured:
"error MSB6006: "csc.dll" exited with code 139"

**Comment by jcouv** [comment] 2018-07-06 18:43
@xclud I will try to find out how to get a stacktrace from a crashed process on Linux.
Is there any chance you could try and repro on windows? (the troubleshooting experience is easier there)

@kxxt Would you be able to share a crash dump of this crash (since you said it was on Windows)? Here are some [instructions](https://github.com/dotnet/roslyn/wiki/Troubleshooting-tips#using-a-registry-setting) for turning that one. Then you can share via any online drive. Thanks

**Comment by hez2010** [comment] 2018-07-07 08:35
@jcouv Actually this issue only occurs on Linux ARM64 system and currently I don't have the environment to repo it. You can try executing "dotnet build" on Linux ARM64, I think this issue will 100% repo.

**Comment by maxbl4** [comment] 2018-07-20 05:15
Have the same issue. Just installed dotnet sdk 2.1.302 on a fresh Debian 9 arm64. And any try to build a project results in error from this topic

**Comment by gauravagarwal28** [comment] 2018-08-09 05:45
I have the same issue on my Jetson TX2 (arm64 - ubuntu 16.04).

**Comment by xclud** [comment] 2018-09-22 23:54
@jcouv I do not face any issues on Windows. I compile for windows on windows and also cross-compile on windows for linux (x64 and arm64). No problem at all.

To me, the problem happens only when i compile on my raspberry pi.

**Comment by olgierdd** [comment] 2018-09-29 07:33
I have the same issue on ROCK64 V2 4G RAM. I can build project, run dotnet restore. When I run dotnet run for console application I am getting: /home/rock64/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/rock64/dev/myApp/myApp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by Olivia-Blundell** [comment] 2018-09-29 14:51
```
/opt/dotnet-sdk-2.1.402/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139.

Build FAILED.
```

Ubuntu 16.04 AARCH64

**Comment by gauravagarwal28** [comment] 2018-10-01 05:28
@olgierdd and @Olivia-Blundell 

Please provide log your issue at:
https://github.com/dotnet/coreclr/issues/19578

This is the coreclr repo of dotnet. The issue is still open. You may find a better response there.

**Comment by hyzx86** [comment] 2018-10-04 09:08
I  have the same problem ,my project run on androd Linux Deploy

Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.9.65-perf+ armv8l)

 * Documentation:  https://help.ubuntu.com/
Ubuntu 16.04 LTS [running via Linux Deploy]
Last login: Thu Oct  4 13:24:51 2018 from 127.0.0.1
root@localhost:~#

build error:

Restore completed in 63.74 ms for /home/android/gitCodes/myGit/OrchardCore/test/OrchardCore.Tests.Pages/OrchardCore.Application.Pages/OrchardCore.Application.Pages.csproj.
/home/dotnet/sdk/2.1.403/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/android/gitCodes/myGit/OrchardCore/src/OrchardCore/OrchardCore.BackgroundTasks.Abstractions/OrchardCore.BackgroundTasks.Abstractions.csproj]
/home/dotnet/sdk/2.1.403/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/android/gitCodes/myGit/OrchardCore/src/OrchardCore/OrchardCore.Data.Abstractions/OrchardCore.Data.Abstractions.csproj]
/home/dotnet/sdk/2.1.403/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/android/gitCodes/myGit/OrchardCore/src/OrchardCore/OrchardCore.XmlRpc.Abstractions/OrchardCore.XmlRpc.Abstractions.csproj]
/home/dotnet/sdk/2.1.403/Roslyn/Microsoft.CSharp.Core.targets(52,5): error M

**Comment by s-sergio** [comment] 2022-03-16 03:51
![dotnet6](https://user-images.githubusercontent.com/60017741/158513202-69d4ccbc-d1bc-4f35-8cd8-fd0fca9de66e.jpg)

similar error with the new new dotnet6

`root@localhost:~# neofetch
            .-/+oossssoo+/-.               root@localhost
        :+ssssssssssssssssss+:           --------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.10 aarch64
    .ossssssssssssssssssdMMMNysssso.       Host: samsung SM-N986B
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-faked
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 7 hours, 4 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1099 (dpkg), 1 (pkg)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.8
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Adwaita [GTK3]
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Icons: Adwaita [GTK3]
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: proot
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   CPU: (8) @ 2.002GHz
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 7529MiB / 10900MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        :+ssssssssssssssssss+:
            .-/+oossssoo+/-.

root@localhost:~# dotnet --version
6.0.201
root@localhost:~# cd Documents/Source/HelloWorld/
root@localhost:~/Documents/Source/HelloWorld# dotnet build HelloWorld.csproj
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/root/.dotnet/sdk/6.0.201/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 139. [/root/Documents/Source/HelloWorld/HelloWorld.csproj]

Build FAILED.

/root/.dotnet/sdk/6.0.201/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 139. [/root/Documents/Source/HelloWorld/HelloWorld.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:23.67`

**Comment by AlexanderZhelnin** [comment] 2023-04-01 07:57
arm64 android termux
dotnet7 does not start
dotnet6 when I launch "dotnet build" then "dotnet/sdk/6.0.407/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 139."

**Comment by jcouv** [comment] 2023-04-03 19:58
@AlexanderZhelnin Please open a new issue. The error code reported here is generic so will not help to narrow down the specific crash that you're encountering. 
If possible, please capture a crash dump ([instructions](https://github.com/dotnet/roslyn/blob/main/docs/wiki/Troubleshooting-tips.md#capturing-a-crash-dump)). That would be very helpful at least to get the stacktrace of the issue.

**Comment by michalwalewski** [comment] 2023-04-26 13:15
Same as @AlexanderZhelnin,

I've tested
arm64 android termux (proot-login debian bulls-eye)
dotnet7 does not start
dotnet6 when I launch "dotnet build" or "dotnet run" then "dotnet/sdk/6.0.407/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 139."
and 
dotnet5 when I launch "dotnet build" or "dotnet run" error MSB6006: "csc.dll" exited with code 139."

The only dotnet that works on arm64 android termux with proot-login debian bulls-eye is dotnet core 3.0.

@jcouv your instruction is for windows machine. We are trying to run dotnet in Linux arm64 environment. 
What files or log files will be useful for you to tackle this dotnet CSC.dll problem ? Thx

**Comment by jcouv** [comment] 2023-04-26 14:14
@michalwalewski One of the following would help for a crash: 1. a small self-contained repro of the crash (sharplab-style), or 2. a dump of the crash. A stacktrace is a third option but in many cases isn't sufficient to corner the issue.

**Comment by michalwalewski** [comment] 2023-04-26 15:16
@jcouv I will try to give as much details as I can with full instruction on what steps I've made this evening.
