### ISSUE TITLE
C# 6 compiler creates null Members property for Expressions

### ISSUE THREAD

**Issue by nicholasbergesen** [dotnet/roslyn#16925] opened 2017-02-03 11:21 UTC
This was originally posted as an issue on the Entity Framework project, but I was redirected here, to the Roslyn compiler.

The original post can be found here: https://entityframework.codeplex.com/workitem/2852?FocusElement=CommentTextBox

This is a copy paste of what can be found in the link above:

> In our project we use a mixture between “Table per type” and “Table per hierarchy” inheritance models. In our inheritance hierarchy certain sub-classes map their additional properties to columns in the base table, whereas others have their additional properties mapped to separate linked tables. When using a combination of these two models we need to send through “x => new { }” as the property mapping expression for the table containing the discriminator column to prevent duplicate mapping of the same column on a child table due to inheritance. Sending through the property would cause entity framework to try and map it to the table twice and throw an exception.
> 
> Example of above mentioned scenario
> ```
> public class ShapeMap : EntityTypeConfiguration<Shape>
> {
>     public const string Discriminator = "ShapeTypeID";
> 
>     public ShapeMap()
>     {
>         Map(m => {
>             m.ToTable("Shape");
>         });
> 
>         this.HasKey(t => t.ID);
>         this.Property(t => t.ID).HasColumnName("ID")
>             .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
>     }
> }
> 
> public class SquareMap : EntityTypeConfiguration<Square>
> {
>     public SquareMap()
>     {
>         Map(m => {
>             m.ToTable("Shape");
>             m.Requires(ShapeMap.Discriminator).HasValue((long)ShapeTypeEnum.Square);
>             m.Properties(x => new { });
>         });
>         Map(m => {
>             m.ToTable("Square");
>         });
> 
>         this.HasKey(t => t.ID);
>         this.Property(t => t.ID).HasColumnName("ID");
> 
>         this.Property(t => t.Height)
>             .HasColumnName("Height");
> 
>         this.Property(t => t.Width)
>             .HasColumnName("Width");
>     }
> }
> 
> public class Shape
> {
>     public Shape()
>     {
>     }
> 
>     public long ID { get; set; }
>     public ShapeTypeEnum? ShapeTypeID { get; set; }
> }
> 
> public class Square : Shape
> {
>     public Square()
>     {
>     }
> 
>     public int Width { get; set; }
>     public int Height { get; set; }
> }
> 
> public enum ShapeTypeEnum
> {
>     Shape = 0,
>     Square = 1
> }
> 
> ```
> 
> The problem with using “x => new { }” as the expression for the discriminator column property expression in C# 6 is that the compiler creates an expression which has a body with a null Members value, whereas in C# 5 the “x => new { }” expression would create an expression with an empty list. You can test this with this code:
> 
> System.Linq.Expressions.Expression<Func<object, object>> checkMyMembers = x => new { };
> 
> Visual Studio 2015
>  ![Image](http://s18.postimg.org/z42ljz9vt/2015.jpg)
> 
> Visual Studio 2013
>  ![Image](http://s23.postimg.org/taa11nnrv/2013.jpg)
> 
> The problem with C# 6 creating a null value on the Members property is that entity framework doesn’t perform a null check on Members before trying to query the collection. This happens in the HasDefaultMembersOnly method in the ExpressionExtension class. As a result a null exception is thrown when using “x => new { }” as an expression to map properties. The code in question is shown below:
> 
> ```
> private static bool HasDefaultMembersOnly(
>             this NewExpression newExpression, IEnumerable<PropertyPath> propertyPaths)
>         {
>             DebugCheck.NotNull(newExpression);
>             DebugCheck.NotNull(propertyPaths);
> 
>             return !(newExpression.Members
>                     .Where(
>                         (t, i) =>
>                         !string.Equals(t.Name, propertyPaths.ElementAt(i).Last().Name, StringComparison.Ordinal))
>                     .Any());
>         }
> ```
> 
> 
> Adding a null check to the members property seems to fix the problem
> ```
> private static bool HasDefaultMembersOnly(
>             this NewExpression newExpression, IEnumerable<PropertyPath> propertyPaths)
>         {
>             DebugCheck.NotNull(newExpression);
>             DebugCheck.NotNull(propertyPaths);
> 
>             return !(newExpression.Members != null && newExpression.Members
>                         .Where(
>                             (t, i) =>
>                             !string.Equals(t.Name, propertyPaths.ElementAt(i).Last().Name, StringComparison.Ordinal))
>                         .Any());
>         }
> ```

Regards

Nicholas Bergesen

**Comment by svick** [comment] 2017-02-03 17:26
I'm not sure this is actually a bug in Roslyn:

1. The fact is that `Members` can return `null`. I think that EF should guard against that by adding the null check, as you suggested.
2. It seems that `Expression.New(ctor, args).Members` returns `null`, while `Expression.New(ctor, args, null).Members` returns an empty collection. This is confusing behavior, but it's not something Roslyn can control. (Roslyn can control which of the two it generates, but I'm not sure that's something that's worth changing.) I suggest you start a discussion about this on [the corefx repo](https://github.com/dotnet/corefx) (that's technically only for .Net Core, but changes there can be ported over to .Net Framework and I think it's easier to use than the proper channel for reporting bugs in .Net Framework, which is Microsoft Connect).

**Comment by gafter** [comment] 2017-02-03 19:40
I agree there may be an issue for the corefx repo, but the fact of the matter is that the Roslyn compiler generates incompatible code for an expression tree in these circumstances, and it should probably be fixed in the Roslyn compiler even if corefx is fixed too, because Roslyn-generated code can still be run on older platforms that do not have any corefx fix for this issue.

**Comment by jaredpar** [comment] 2017-03-09 23:20
Thanks for reporting this.  It appears to be a duplicate of #12297.  Going to let that be the primary issue tracking this bug.

**Closed by jaredpar** 2017-03-09 23:20 UTC
Labels: Area-Compilers, Bug, Tenet-Compatibility
