### ISSUE TITLE
Top-level statement completion interferes with 'using' directives

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44459] opened 2020-05-21 00:11 UTC
**Version Used**: features/SimplePrograms

🔗 This issue is very similar to #43439. It should be fixed in a similar way, except the match priority should only be altered in the global statement context where a `using` directive is applicable.

📝 A disabled test for this behavior is added in #44402.

**Steps to Reproduce**:

1. Type `us` in an empty document
2. Press <kbd>Tab</kbd>

**Expected Behavior**:

```
using
```

**Actual Behavior**:

```
ushort
```

**Comment by CyrusNajmabadi** [comment] 2020-05-27 20:15
In your PR you mentino: > and it's questionable whether we will do this in the future.

Could you clarify this?  Why would we not do this?

**Comment by sharwell** [comment] 2020-05-27 20:19
After discussion with @jasonmalinowski, we realized that the relative order of these keywords has _always_ applied since `using` statements and `ushort` were always allowed in method bodies.

1. A change to ordering at the top level could interfere with method bodies.
2. We have never heard reports about problems typing `using` within a method body, even though `ushort` would be preferred for the prefix `us` _and_ using statements are likely more commonly typed than `ushort`.

At this point, it doesn't seem like a change is necessary.

**Comment by CyrusNajmabadi** [comment] 2020-05-27 20:40
i'm not certain i buy the premise that what happens in a method body applies to how people type outside of it.  Similarly there may be people that have never written a `using` in a method but have written hundreds of using-directives.  I do agree that `ushort` feels super unlikely to want to write, but that is even more motivation for me that it not interfere with any existing customers who might be writing `u<Tab>` or `us<Tab>` at teh top level.

That said, i'm also ok with waiting to hear about things.  We heard about `null/nint` immediately, so we can see if the same holds true for `using/ushort`.

**Comment by alrz** [comment] 2020-05-28 09:48
IMO `using` is far more common in top-level *and* method body than `ushort` anywhere else.

**Comment by sharwell** [comment] 2020-09-10 16:31
> IMO using is far more common in top-level and method body than ushort anywhere else.

@alrz I agree, and this is exactly why it seemed fine to deprioritize this. If users didn't have a problem with the relative priority of `using` and `ushort` inside method bodies _where `using` was already more common_, then it seems to reason that the same situation applied to top-level statements would also not be a problem.

**Comment by MichalStrehovsky** [comment] 2021-02-10 12:04
I hit this issue with the top-level ushort very often. Only today it reached the level of annoying me to the level of asking in the C# Discord where to file this only to find the issue is already here. So if you're looking for people hitting this, here I am.

Seems like nobody gave this issue a thumbs up yet, so I'm starting it. Hopefully more people who hit this will follow.

**Comment by KirillOsenkov** [comment] 2021-02-10 17:53
ushort in method bodies has been annoying me for years

**Comment by CyrusNajmabadi** [comment] 2021-02-10 20:30
Ok.  I keep running into this.  I think we shoudl do somethnig about this.  @vatsalyaagrawal Can you assign to someone to look at?

**Closed** 2021-02-11 01:51 UTC
Labels: 4 - In Review, Area-IDE, Bug, IDE-IntelliSense, IntelliSense-Completion, New Language Feature - Simple Programs
