### ISSUE TITLE
Not getting Rename file to

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37469] opened 2019-07-25 09:37 UTC
In one sln:
![image](https://user-images.githubusercontent.com/1640096/61863513-0a416800-aed0-11e9-8e70-a2651e2bc0b5.png)

In another sln it works:
![image](https://user-images.githubusercontent.com/1640096/61863598-365ce900-aed0-11e9-85c7-ba482462d272.png)

Both are identical with:

```cs
namespace N
{
    public static partial class C1
    {
        public static class C2
        {
        }
    }
}
```

In a file named `WrongName.cs`

I could not narrow down a repro, tried restarting VS etc but no dice.

**Comment by CyrusNajmabadi** [comment] 2019-07-25 18:05
I believe this may be a CPS limitation.

**Comment by JohanLarsson** [comment] 2019-07-31 17:10
What is CPS?

**Comment by jmarolf** [comment] 2019-07-31 17:20
project system silliness. @dpoeschl 	I thought this was fixed on the project system side.  Are their still issues?

**Comment by dpoeschl** [comment] 2019-07-31 17:49
@jmarolf http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,393

```C#
internal override bool CanRenameFilesDuringCodeActions(CodeAnalysis.Project project)
            => !IsCPSProject(project);
```

I believe the Project System is fixed to support it, but this check stops it from working. We _should_ be able to remove that check (and add an integration test?) now.

**Comment by penenkel** [comment] 2019-08-25 13:32
May be a duplicate of #24560.

**Comment by jmarolf** [comment] 2019-08-25 16:47
@ryzngard considering inline rename works in CPS I assume this will as well?

**Comment by Felix-Dev** [comment] 2020-01-11 17:35
I still have no [Rename file to] quick action available in Visual Studio 16.4 for .NET Core 3.1 projects (works fine for .NET Framework and UWP projects). Any updates on when this issue will be resolved?

**Comment by quetzalcoatl** [comment] 2020-01-20 09:28
@Felix-Dev see issue 24560, it's probably the oldest copy

**Comment by sharwell** [comment] 2020-02-14 15:07
Duplicate of #24560

**Closed by sharwell** 2020-02-14 15:07 UTC
Labels: Area-IDE, Bug, Developer Community
