### ISSUE TITLE
IDE0078 fixer works incorrectly for certain types of conditions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51742] opened 2021-03-08 17:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0078-fixer-works-incorrectly-for-cert/1356170)._

---
We have a condition as follows:

```csharp
void Foo(Exception ex) {
    if (ex.Message != null && ex.InnerException != null) { }
}
```
I get an `IDE0078 Use pattern matching` message for the specified line, but the quick fix produces the following code, which doesn't have the same meaning:

```csharp
void Foo(Exception ex) {
    if (ex.InnerException is not null and not null) { }
}
```

---
#### Feedback Bot on 3/4/2021, 00:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### null on 3/4/2021, 10:41 PM: 

<p>when i update my vs to 16.9.0,then i get the suggustion:</p>
<p><img src="https://aka.ms/dc/image?name=B175b8de040834317a8a01d8397b221ff637505241551832648_$%7DX0JB3O8H%25%7BP%60K" alt="$}X0JB3O8H%{P`K)XGD1KG1.png">XGD1KG1.png&amp;tid=175b8de040834317a8a01d8397b221ff637505241551832648)</p>
<p>then i saw that:</p>
<p>![6{835GK(AFREG94F39J]N7W.png](<a target='_blank' href="https://aka.ms/dc/image?name=B15829b819b29478a81cea1f27db41bb1637505241660165269_6%7B835GK(AFREG94F39J%5DN7W.png&amp;tid=15829b819b29478a81cea1f27db41bb1637505241660165269)">https://aka.ms/dc/image?name=B15829b819b29478a81cea1f27db41bb1637505241660165269_6{835GK(AFREG94F39J]N7W.png&amp;tid=15829b819b29478a81cea1f27db41bb1637505241660165269)</a></p>
<p>that:</p>
<p><img src="https://aka.ms/dc/image?name=B26432561c5fa406594742693c643f40d637505241834129030_S0IFSDH" alt="S0IFSDH)@QW04T7A5L(UHVT.png">@QW04T7A5L(UHVT.png&amp;tid=26432561c5fa406594742693c643f40d637505241834129030)</p>
<p>that:</p>
<p><img src="https://aka.ms/dc/image?name=B89e7fa44745b449d853073766db833ae637505241988387808_ZTR%5B%5DHQ@C" alt="ZTR[]HQ@C)29{IKEP(TY~UK.png">29%7BIKEP(TY~UK.png&amp;tid=89e7fa44745b449d853073766db833ae637505241988387808)</p>
<p>and so on…</p>

#### Rodolfo Tedeschi on 3/4/2021, 11:15 PM: 

<p>This is another example of the same issue.</p>
<pre><code>byte[] <span class="hljs-built_in">list</span> = Array.Empty();
<span class="hljs-keyword">bool</span> value = <span class="hljs-built_in">list</span>.Length &gt; <span class="hljs-number">0</span> &amp;&amp; <span class="hljs-built_in">list</span>[<span class="hljs-number">0</span>] == <span class="hljs-number">0</span>;
</code></pre>
<p>This code produces the following suggestion:</p>
<pre><code><span class="hljs-keyword">bool</span> value = <span class="hljs-built_in">list</span>[<span class="hljs-number">0</span>] is &gt; <span class="hljs-number">0</span> <span class="hljs-keyword">and</span> <span class="hljs-number">0</span>;   
</code></pre>

#### 南 超 on 3/4/2021, 11:20 PM: 

<p>when i update my vs to 16.9.0,then i get the suggestion:</p>
<p><img src="https://aka.ms/dc/image?name=B77c6dfe3ef724d9383fba8a3c5540765637505253699821658_1.png&amp;tid=77c6dfe3ef724d9383fba8a3c5540765637505253699821658" alt="1.png"></p>
<p>and then i follow them i saw that:</p>
<p><img src="https://aka.ms/dc/image?name=B07c42506195d4e2d8597efceadecc204637505252887343475_3.png&amp;tid=07c42506195d4e2d8597efceadecc204637505252887343475" alt="3.png"><br>
)</p>
<p>that:</p>
<p><img src="https://aka.ms/dc/image?name=B20d67fbbe5d84e2d85389b5f268c9249637505253868952306_4.png&amp;tid=20d67fbbe5d84e2d85389b5f268c9249637505253868952306" alt="4.png"></p>
<p>that:</p>
<p><img src="https://aka.ms/dc/image?name=B4a654d64a4d54e39bbe47e7a1b363f4e637505254051969381_5.png&amp;tid=4a654d64a4d54e39bbe47e7a1b363f4e637505254051969381" alt="5.png"></p>
<p>and so on…</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-03-08 18:45
Duplicate of https://github.com/dotnet/roslyn/issues/51691

**Comment by CyrusNajmabadi** [comment] 2021-03-09 07:36
Closing a dupe, thanks.

**Closed** 2021-03-09 07:37 UTC
Labels: Area-IDE, Resolution-Duplicate, untriaged
