### ISSUE TITLE
Support New OS

### ISSUE THREAD

**Issue by alanking10105555** [dotnet/roslyn#29720] opened 2018-09-07 10:07 UTC
The OS runs on machine that has compute, has memory, has IO. The OS runs a new kind of assembly code. This kind of assembly code has a format that is minimal and portable.

### Assembly Format
multiple **instruction**

### Instruction Format
[**label**:] **operation** **source1** **source2** **destination**

**label** is location of the instruction.
**operation** is the do of the instruction.
**source1**, **source2**, destination are variable.

**variable**
is one of the type in this list:
Bool
Int
String
Array

**operation** is one of the do in this list:
new
and
or
not
count
add
subtract
multiply
divide
equal
bigger
smaller
append
subscript
call
return
goto
in
out

In this assembly format, .NET do file operation with the in and out operations.

**Comment by alanking10105555** [comment] 2018-09-07 10:19
This assembly format is minimal and complete.

**Comment by sharwell** [comment] 2018-09-07 12:27
Duplicate of #29520

**Closed by sharwell** 2018-09-07 12:27 UTC
