### ISSUE TITLE
Source generator diagnostics are not showing up in VS Quick Info

### ISSUE THREAD

**Issue by ChrisTorng** [dotnet/roslyn#58435] opened 2021-12-09 05:27 UTC
### Description

For this sample:

    public class Outer
    {
        internal class Inner
        {
            public string? Name { get; init; }
        }
    
        [JsonSerializable(typeof(Inner))]
        internal partial class InnerJsonContext : JsonSerializerContext
        { }
    }
    
    [JsonSerializable(typeof(Outer.Inner))]
    public partial class OuterInnerJsonContext : JsonSerializerContext
    { }

The `OuterInnerJsonContext` is ok, but `InnerJsonContext` has 3 compiler errors:

* CS0534: 'Outer.InnerJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'
* CS0534: 'Outer.InnerJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
* CS7036: There is no argument given that corresponds to the required formal parameter 'options' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)'

But my requirement is make the `Inner` class `private`, because it should be hidden. So the `OuterInnerJsonContext` is not applicable.

I have a [repro](https://github.com/ChrisTorng/JsonSourceGenerator) in [Outer.cs](https://github.com/ChrisTorng/JsonSourceGenerator/blob/main/Net60Tests/Outer.cs) showing this issue. Uncomment to see the compiler errors.

### Reproduction Steps

1. Clone [repro](https://github.com/ChrisTorng/JsonSourceGenerator), open with Visual Studio.
2. Open [Net60Tests\Outer.cs](https://github.com/ChrisTorng/JsonSourceGenerator/blob/main/Net60Tests/Outer.cs)
3. Build without error, tests pass.
4. Uncomment all, then 3 errors appear on `InnerJsonContext`.

### Expected behavior

It compiles without errors, and tests pass.

### Actual behavior

`InnerJsonContext` has 3 compiler errors:

* CS0534: 'Outer.InnerJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'
* CS0534: 'Outer.InnerJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
* CS7036: There is no argument given that corresponds to the required formal parameter 'options' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)'

### Regression?

Don't know.

### Known Workarounds

Make `Inner` class `internal` instead of `private`, then add `OuterInnerJsonContext` class outside of `Outer` class.

### Configuration

.NET 6.0, Visual Studio 2022 17.1.0 Preview 1.0.

### Other information

Don't know.

**Comment by jasonmalinowski** [comment] 2021-12-21 01:18
At first I thought this was a direct dupe of the work that's on me, but what's a bit odd is @layomia is implying that there are squiggles appearing, but we're not getting quick info for them...which isn't a combo I would have imagined we could hit.

**Comment by layomia** [comment] 2021-12-21 01:28
@jasonmalinowski I have not seen squiggles produced by source generator diagnostics. The issue is we are getting neither squiggles nor Quick Info.

**Comment by jasonmalinowski** [comment] 2021-12-21 02:02
@layomia Oh, then I misunderstood, if you're only seeing error list entries but not squiggles nor quick info, the yeah, that's a likely dupe of the work on me to finish wiring that up.

**Comment by terrajobst** [comment] 2022-01-04 01:14
> You reproduction is also producing the following warning:
> 
> ```
> CSC : warning SYSLIB1032: Derived 'JsonSerializerContext' type 'InnerJsonContext' specifies JSON-serializable types. The type and all containing types must be made partial to kick off source generation.
> ```
> 
> And that is the root of your issue. While you have declared `InnerJsonContext` as partial its containing class is not partial. Once I mark `Outer` as partial the compiler errors go away.

Does this indicate that this should have really been an error?

**Closed** 2022-04-20 21:52 UTC
Labels: Area-IDE
