### ISSUE TITLE
Add language settings command to editor context menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46630] opened 2020-08-07 18:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1124164/add-language-settings-command-to-editor-context-me.html)._

---
<p>Make it easy to get to the language options directly from the editor context menu. It's too cumbersome to open <strong>Tools -&gt; Options</strong> and then navigate to the right place for e.g. the C# language settings</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/148094-langauge-settings.png"> Image:148094-langauge-settings.png</a></p>

---
#### Feedback Bot on 7/23/2020, 07:03 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-08-13 22:24
I'm tentatively marking this as **By Design**, but will update with the final conclusion following the next design meeting.

**Comment by jasonmalinowski** [comment] 2020-08-24 18:24
We discussed this in the our design meeting and decided that putting in the _menu_ was a bit too aggressive for this: space in that menu is at a premium, and we have to be very strict with what we let into the menu. We didn't think this met the bar for that.

However, we agreed that this experience really isn't very good, and started brainstorming places we might want to use instead. VS Code places a link to editor settings in the status bar, and since we already have a status bar showing some information we might be able to leverage that. We filed https://developercommunity.visualstudio.com/idea/1152931/have-an-option-to-navigate-to-c-language-settings.html to follow up with the main VS platform team about that approach.

**Closed by jasonmalinowski** 2020-08-24 18:24 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review, Resolution-By Design
