### ISSUE TITLE
'System.NullReferenceException' at Roslyn.Diagnostics.Analyzers.EquatableAnalyzer.IsObjectEqualsOverride

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2831] opened 2015-05-16 08:08 UTC
Saw the below info diagnostic in my error list:

Severity	Code	Description	Project	File	Line	Detail Description
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.EquatableAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	EditorServicesTest		1	Analyzer 'Roslyn.Diagnostics.Analyzers.EquatableAnalyzer' threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
>   at Roslyn.Diagnostics.Analyzers.EquatableAnalyzer.IsObjectEqualsOverride(IMethodSymbol methodSymbol, INamedTypeSymbol objectType)
   at Roslyn.Diagnostics.Analyzers.EquatableAnalyzer.<>c__DisplayClass11_0.<AnalyzeSymbol>b__0(IMethodSymbol m)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Roslyn.Diagnostics.Analyzers.EquatableAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context, INamedTypeSymbol objectType, INamedTypeSymbol equatableType)
   at Roslyn.Diagnostics.Analyzers.EquatableAnalyzer.<>c__DisplayClass10_0.<InitializeCore>b__0(SymbolAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass26_0.<ExecuteSymbolActions>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze, Action`3 onAnalyzerException, CancellationToken cancellationToken)'.

**Comment by lgolding** [comment] 2015-07-31 19:29
Added unit tests to the analyzer, and protected null references in `IsObjectEqualsOverride`, but could not reproduce.

**Comment by lgolding** [comment] 2015-09-03 00:42
@mavasani Manish, is it OK with you if I close this? I added some null reference protection and unit tests, but could not reproduce.

**Comment by mavasani** [comment] 2015-09-03 03:21
Yes, sounds fine to me Larry.

**Closed** 2015-09-03 04:47 UTC
Labels: Area-Analyzers, Bug, Resolution-Not Reproducible
