### ISSUE TITLE
"Remove unused parameter" doesn't handle VB's addressof

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#32228] opened 2019-01-08 03:57 UTC
**Version Used**: 

**Steps to Reproduce**:

1. 

``` VB
New PropertyControlData(VsProjPropId110.VBPROJPROPID_Prefer32Bit, "Prefer32Bit", chkPrefer32Bit, AddressOf Prefer32BitSet, AddressOf Prefer32BitGet)
```

``` VB
Protected Function Prefer32BitGet(control As Control, prop As PropertyDescriptor, ByRef value As Object) As Boolean ' <--- Fires
End Function
```

``` VB
Public Class PropertyControlData

    Public Sub New(id As Integer, name As String, FormControl As Control, setter As SetDelegate, getter As GetDelegate)
    End Sub

End Class

Public Delegate Function GetDelegate(control As Control, prop As PropertyDescriptor, ByRef value As Object) As Boolean
```

**Expected Behavior**:
No message

**Actual Behavior**:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'prop'	Microsoft.VisualStudio.Editors	E:\project-system2\src\Microsoft.VisualStudio.Editors\PropPages\BuildPropPageBase.vb	129	Style	Active

```

**Comment by mavasani** [comment] 2019-01-12 00:35
@sharwell Tentatively marked as by design, but we should bring this up at the next design meeting.

**Comment by mavasani** [comment] 2019-01-28 20:09
We have decided to implement the suggestion [here](https://github.com/dotnet/roslyn/issues/32851#issuecomment-458260431):

_We might also want a naming convention for things we just ignore. i.e. `int _` or `int _1`, `int _2`, `int _3` etc. That way users can have a reasonable way to say "yes... i know this parameter is here. but please ignore it", without the huge suppression directive you need otherwise._

**Closed** 2019-01-29 18:36 UTC
Labels: 4 - In Review, Area-IDE, Bug
