### ISSUE TITLE
IDE inserts wrong indent

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#13097] opened 2016-08-11 17:26 UTC
**Version Used**: VS2015 Update3

**Steps to Reproduce**:

![wrongindent](https://cloud.githubusercontent.com/assets/3316258/17598135/edf4c580-5fad-11e6-9b7e-d5e774289e0d.gif)

This is the starting file:

```cs
using System;

// Hello

class Class1
{
    // Hello

    int f() => 1;

}
```

What I do is position the cursor at the end of either `// Hello` and press ENTER twice.

**Expected Behavior**:

It should line up my cursor underneath the preceding `//`

**Actual Behavior**:

It lines up my cursor indented by 4.

**Comment by ljw1004** [comment] 2016-08-11 17:27
Just to add -- this is currently my no. 1 annoyance with VS. I have to fix up my caret all the time and it's really annoying.

**Comment by Pilchie** [comment] 2016-08-11 17:29
Dupe of https://github.com/dotnet/roslyn/issues/3321 - feel free to send a PR 😜

**Closed by Pilchie** 2016-08-11 17:29 UTC
