### ISSUE TITLE
Poor codegen for collection expression spread on nullable sources

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#74624] opened 2024-07-31 20:33 UTC
**Version Used**: 4.11.0-ci (sharplab main)

**Steps to Reproduce**:

[Sharplab link](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYB0AZWBHAbgFgAoZNdAFmJNIwDYKkBtAXRQFkAKDAZgB4MSAHwoAHgEpSAb1Ip5aAOwpmmTOID8mAOoALAKYAnfVzEoAvKLNQAzihgB7AC72ArgBt3E1jQC+QA)

**Expected Behavior**:

Something like this (with no intermediate list):

```csharp
return (x != null)
    ? Enumerable.Where(x, <>c.<>9__0_1 ?? (<>c.<>9__0_1 = new Func<string, bool>(<>c.<>9.<<Main>$>b__0_1)).ToArray()
    : [];
```

**Actual Behavior**:

This:

```csharp
List<string> list = new List<string>();
list.AddRange((x != null) ? Enumerable.Where(x, <>c.<>9__0_1 ?? (<>c.<>9__0_1 = new Func<string, bool>(<>c.<>9.<<Main>$>b__0_1))) : null);
return list.ToArray();
```

cc. @RikkiGibson

**Comment by RikkiGibson** [comment] 2024-07-31 22:33
This looks like a general issue when spreads of unknown length are used in a collection-expression targeting array type.

There is likely a dupe of this bug somewhere under the "Code Gen Quality"+"Collection Expressions" issue tags.

**Comment by jaredpar** [comment] 2024-08-05 21:38
Looks like a dupe of #71755

**Closed by jaredpar** 2024-08-05 21:38 UTC
Labels: Area-Compilers, Code Gen Quality, untriaged, New Feature - Collection Expressions
