### ISSUE TITLE
Implicit call to base constructor with optional parameter

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#39250] opened 2019-10-12 12:55 UTC
**Version Used**: 
C# 8 compiler

**Steps to Reproduce**:
Write this code:

```csharp
class Base
{
    public Base(int x = 0) { }
}

class Derived : Base { }
```

**Expected Behavior**:

I would expect this code to fail to compile. `Base` doesn't have a default constructor, so `Derived` should be required to explicitly call a base constructor. The fact that the base class constructor has an optional parameter shouldn't change that.

**Actual Behavior**:

The code compiles. The compiler implicitly emits a call to `base(0)`:

```il
IL_0000:  ldarg.0     
IL_0001:  ldc.i4.0    
IL_0002:  call        Base..ctor
IL_0007:  ret         
```
---
Is this behavior intentional or is it a bug ?

**Comment by thomaslevesque** [comment] 2019-10-12 15:25
In the C# 5 specification (which is the latest full specification AFAIK) says, in §10.11.4 (emphasis mine):

> If a class contains no instance constructor declarations, a default instance constructor is automatically provided. **That default constructor simply invokes the parameterless constructor of the direct base class.**

But in this case, there's not parameterless constructor in the base class.

So I *think* it's a bug... or at least an unintentional feature, since I don't see any downside to this behavior.

**Comment by CyrusNajmabadi** [comment] 2019-10-12 19:11
> So I think it's a bug...

It's not a bug.  It comes down to how "invokes the parameterless constructor of the direct base class".  That is interpretted to mean you get:

```c#
class Derived : Base
{
    public Derived() : Base() { }
}
```

There we are invoking the parameterless constructor.  Now, as it happens, overload resolution then takes that invocation and actually binds it to the actual constructor with default params.

The idea here is that, like with many things in the language, things are effectively specified as  pattern, and hten the remainder of the language rules  take effect.

**Comment by thomaslevesque** [comment] 2019-10-13 13:22
> The idea here is that, like with many things in the language, things are effectively specified as pattern, and hten the remainder of the language rules take effect.

That's one way to look at it. But things relying on patterns are usually explicitly called out in the spec, and it's not the case here.

Anyway, it's not a serious issue (or even an issue at all), but it made me curious...

**Comment by gafter** [comment] 2019-10-14 19:17
The ECMA specification says

> 15.11.5 Default constructors
> If a class contains no instance constructor declarations, a default instance constructor is automatically provided. That default constructor simply invokes a constructor of the direct base class, as if it had a constructor initializer of the form base(). 

These revisions have not been incorporated into our copy of the specification, but when they are the compiler and specification will be in alignment.

**Closed by gafter** 2019-10-14 19:17 UTC
Labels: Area-Compilers

**Comment by thomaslevesque** [comment] 2019-10-14 19:58
@gafter thanks! I didn't think to look at the ECMA spec
