### ISSUE TITLE
GetSpeculativeSymbolInfo throws InvalidOperationException

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#41355] opened 2020-02-01 18:13 UTC
**Version Used**:  3.5.0-beta2-final

**Steps to Reproduce**:
```
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Test
{
    internal static class Program
    {
        internal static async Task Main()
        {
            const string source = @"
using System;
using System.Collections.Generic;

#nullable enable

public static class C
{
    public static bool Try<T>(this IEnumerable<T>? source, out int count)
    {
        throw new NotImplementedException();
    }

    public static bool M<T>(this IEnumerable<T>? source)
    {
        if (Try(source, out int count))
        {
        }

        throw new NotImplementedException();
    }
}
";
            using (Workspace workspace = new AdhocWorkspace())
            {
                var metadataReferences = AppContext
                    .GetData("TRUSTED_PLATFORM_ASSEMBLIES")
                    .ToString()
                    .Split(';')
                    .Select(f => MetadataReference.CreateFromFile(f));

                var project = workspace.CurrentSolution
                    .AddProject("Test", "Test", LanguageNames.CSharp)
                    .WithMetadataReferences(metadataReferences);

                project = project.WithParseOptions(((CSharpParseOptions)project.ParseOptions).WithLanguageVersion(LanguageVersion.CSharp8));

                var document = project.AddDocument("Document", SourceText.From(source));
                var semanticModel = await document.GetSemanticModelAsync().ConfigureAwait(false);
                var tree = await document.GetSyntaxTreeAsync().ConfigureAwait(false);
                var root = await tree.GetRootAsync().ConfigureAwait(false);

                var invocation = root.DescendantNodes().OfType<InvocationExpressionSyntax>().First();
                var newInvocation = SyntaxFactory.ParseExpression("source.Try(out int count)");

                SymbolInfo symbolInfo = ModelExtensions.GetSpeculativeSymbolInfo(
                    semanticModel,
                    invocation.SpanStart,
                    newInvocation,
                    SpeculativeBindingOption.BindAsExpression);
            }
        }
    }
}
```

**Expected Behavior**:
No exception

**Actual Behavior**:
```
System.InvalidOperationException: 'This program location is thought to be unreachable.'

This exception was originally thrown at this call stack:
	Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(Microsoft.CodeAnalysis.CSharp.Syntax.DeclarationExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag)
	Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(Microsoft.CodeAnalysis.CSharp.Syntax.DeclarationExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag)
	Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, bool, Microsoft.CodeAnalysis.RefKind)
	Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Microsoft.CodeAnalysis.DiagnosticBag, ref bool, ref bool, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, bool, bool)
	Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag)
	Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, bool, bool)
	Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, bool, bool)
	Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSpeculativelyBoundExpression(int, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.SpeculativeBindingOption, out Microsoft.CodeAnalysis.CSharp.Binder, out System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbol>)
	Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSpeculativelyBoundExpression(int, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.SpeculativeBindingOption, out Microsoft.CodeAnalysis.CSharp.Binder, out System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbol>)
	Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(int, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.SpeculativeBindingOption)
```

**Comment by sharwell** [comment] 2020-02-02 18:29
Duplicate of #39993

**Closed by sharwell** 2020-02-02 18:29 UTC
