### ISSUE TITLE
Incorrect `IDE0007 use 'var' instead of explicit type` in invalid foreach statement

### ISSUE THREAD

**Issue by yume-chan** [dotnet/roslyn#14051] opened 2016-09-24 15:52 UTC
**Version Used**: 

Commit 2886ad14e06953a7d73c29fd79b7b8baa6b36cf0 (Not latest, but very new)

**Steps to Reproduce**:
1. In Code Style settings, change `'var' preference` to `Prefer 'var'` and set severity to something not `None`.
2. Paste the code snippet:

``` C#
foreach (var a in Equals(null, null)) { }
```

**Expected Behavior**:

There is no explicit type, thus no `IDE0007`.

**Actual Behavior**:

`IDE0007 use 'var' instead of explicit type` on `var a`.

**Comment by CyrusNajmabadi** [comment] 2016-11-04 19:57
I'm hitting htis as well with this case:

![image](https://cloud.githubusercontent.com/assets/4564579/20020366/321de48a-a28e-11e6-80d5-b9f70b8bd333.png)

I think the issue is that we're probably getting no type, or an error type.  In these cases, we should not offer the fix.

**Comment by marcospgp** [comment] 2021-08-04 11:05
Getting the same issue here:

![image](https://user-images.githubusercontent.com/3464445/128170575-1274dc07-7047-4d05-a657-50fbc274d1e1.png)

**Comment by CyrusNajmabadi** [comment] 2021-08-04 15:48
@marcospgp can you provide a sample of your code where you are seeing this?

**Comment by marcospgp** [comment] 2021-08-06 20:38
```
        private void DrawSphere(Vector3 position, float blackness) {
            GameObject sphere = GameObject
                .CreatePrimitive(PrimitiveType.Sphere);

            sphere.transform.position = position;
            sphere.transform.localScale = Vector3.one * 0.25f;

            Renderer r = sphere.GetComponent<Renderer>();

            r.material.color = Color.Lerp(
                Color.white,
                Color.black,
                blackness
            );
        }
        ```
        
        This is the code in the screenshot @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2021-08-07 00:23
I don't understand the issue.  The OP says that the preference is set to 'prefer var'.  So i would expect 'var' to be suggested here.  I don't see what your code has to do with 'invalid foreach statement's

**Comment by CyrusNajmabadi** [comment] 2021-08-07 00:24
@marcospgp I don't understand the issue. The OP says that the preference is set to `prefer var`. So i would expect 'var' to be suggested here. I don't see what your code has to do with `invalid foreach statement`s.

**Comment by marcospgp** [comment] 2021-08-07 14:41
@CyrusNajmabadi I may have misunderstood the original issue, but I have:

`csharp_style_var_when_type_is_apparent = true:error`

but in the code shown above the type is not apparent - I do not have `<GameObject>` anywhere, the issue likely coming from the fact that I'm calling a method on the `GameObject` class.

Maybe the string matching should look for `<GameObject>` strictly, not just `GameObject` after the `=`? I'm not sure if that's how it's working at the moment though.

**Comment by CyrusNajmabadi** [comment] 2021-08-07 16:56
What is the definition of CreatePrimitive?

**Comment by marcospgp** [comment] 2021-08-08 11:56
@CyrusNajmabadi https://docs.unity3d.com/ScriptReference/GameObject.CreatePrimitive.html

![image](https://user-images.githubusercontent.com/3464445/128631129-01c4a79e-6eed-4e9b-8d32-45251b764f87.png)

**Comment by CyrusNajmabadi** [comment] 2021-08-08 14:26
As a factory method, this type is apparent. It's the same at Int32.Parse, or XDocument.Load. Factory methods that create instances of the type they are called in don't need an explicit type when 'use var if apparent' since the type is apparent.

**Comment by marcospgp** [comment] 2021-08-11 09:09
@CyrusNajmabadi Correct me if I'm wrong, but factory methods are a design pattern and not a formal specification. Given that the type is not mentioned explicitly anywhere in the declaration, and that the methods can have any name, I wouldn't say that the type is apparent.

**Comment by CyrusNajmabadi** [comment] 2021-08-11 13:35
> are a design pattern and not a formal specification.

Yes. And as a common and sensible pattern, the type is apparent. If you ask anyone: what does XDocument.Load return they will tell you: an XDocument. 

> Given that the type is not mentioned explicitly anywhere in the declaration

It is. `GameObject.XXX`. 

> I wouldn't say that the type is apparent.

This has been the definition on how this works for 10+ years. It was based on actually surveying developers and asking what were the cases where types were apparent, and even explicitly asking them if cases likes this should count. The vast vast majority (possibly universal, but I don't remember now), thought it should.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 20:59
Closing out.  The original foreach case doens't repro.

**Closed by CyrusNajmabadi** 2022-10-28 20:59 UTC
Labels: Bug, Area-IDE
