### ISSUE TITLE
Language Support: Anonymous Derivations

### ISSUE THREAD

**Issue by prasannavl** [dotnet/roslyn#1960] opened 2015-04-13 22:46 UTC
Anonymous derivation for classes and interfaces, providing the illusion of direct instantiation of interfaces, base classes, etc.

```C#
public interface IRandom {
 void SayHello();
 string GetString();
}
```

Its is impossible to use the existing `new` operator without colliding with current semantics. But introducing another keyword has its own problems, and compatibilities issues. Instead, simply use the new keyword, but as the constraint form, `new()` except that it takes an argument of syntax ` typeName { InitializationExpression }` where the expression similar to the class initialization syntax, except that, all functions, are described as expressions. 

```c#
new(IRandom { 
  SayHello = () => {
     Console.WriteLine("Hello!");
  },
  GetString = Func<string> => {
  return "Hello";
},
})
```
The Funcs aren't really funcs. They get translated into real methods by Roslyn. This is only used for the expression definition.

The above is a compile-time factor. This can also be extended to be done at run-time with a new overload, that takes a `type` as parameter, there-by providing the language with direct interface instantiation-like semantics.

**Comment by HaloFour** [comment] 2015-04-13 23:41
This would be a dupe of #13 and #1728.

**Comment by gafter** [comment] 2015-04-14 02:51
Closing as a dup of #13.

**Closed by gafter** 2015-04-14 02:51 UTC
Labels: Area-Language Design, Feature Request
