### ISSUE TITLE
File-Scoped Namespace should always have a fix all option available 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#58673] opened 2022-01-06 19:30 UTC
A user should always have an option to apply a fix all for this code style to their code base.

**Comment by Youssef1313** [comment] 2022-01-06 19:38
Possibly duplicate of https://github.com/dotnet/roslyn/issues/32461.

**Comment by CyrusNajmabadi** [comment] 2022-01-06 19:41
I disagree.  Say you have set "file scoped namespaces are an error".  Then i don't think a fix-all should be available.

We have discussed refactorings having fix-alls when appropriate (which @Youssef1313 has linked to).  This should fall under this bucket IMO.   We should just do that work, and then have this be part of the fallout.

**Comment by CyrusNajmabadi** [comment] 2024-11-13 22:39
Closing out as speculative.  If this needs to happen, then we should assign a dev/milestone.

**Closed by CyrusNajmabadi** 2024-11-13 22:39 UTC
Labels: Area-IDE, Feature Request
