### ISSUE TITLE
Quick Actions and Refactoring - Implementing Interface dumps a ton of "NotImplementedExceptions" after EVERY interface member

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24609] opened 2018-02-02 14:47 UTC
This is pretty ridiculous. I get it, these aren't implemented, but I don't need the hassle of choosing to go through and remove every single exception or having to load the interface and copy over the member definitions. It's ESPECIALLY stupid because any getter-setter property gets two of these giant freaking exceptions for both getter and setter.

It's so bulky and stupid. I don't know who thought it'd be a good idea.

Give us an option to just add them in without all the exceptions.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/175005/quick-actions-and-refactoring-implementing-interfa.html
VSTS ticketId: 545636_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎1‎/‎7‎/‎2018, 06:51 PM (25 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-02-02 14:48
This is related to #5898. Currently an option is provide to control the behavior for generated properties. This issue concerns the design and implementation of a broader option covering all generated members.

/cc @kuhlenh

**Comment by CyrusNajmabadi** [comment] 2018-02-02 23:17
FWIW, i like this behavior.  If we don't spit out the throws, then you will get uncompilable code, meaning now you have a huge swath of issues to fix up before your code will even compile.  The current approach allows hte code to be generated, but keeps you in a compilable state, allowing you to then implement the methods on-demand when useful to you.  For example, i use this with EditAndContinue to then go fill out the bodies while running the program.

It's also worth noting that this has been the implement-interface behavior since *v1* (i.e. 13+ years now), and there's been very little feedback that this code-gen strategy is actually a problem.

About all we've actually changed here (because there was a fair amount of feedback) was to not add 'using System' when we did this and to instead just fully qualify "throw new System.NotImplementedException()" if "using System" was not in the file.

**Comment by sharwell** [comment] 2018-02-02 23:25
Other IDEs take a slightly different approach, where the default behavior is to essentially `return default;` in each generated method. Out-variables would also be assigned default values in an approach like this.

**Comment by sharwell** [comment] 2018-02-02 23:28
It sounds like the most frustrating aspect of current behavior is actually already addressed. The following selection would prevent the throwing of exceptions from generated properties:

![image](https://user-images.githubusercontent.com/1408396/35759321-81dd5a20-083e-11e8-8d48-ba207d3072ce.png)

**Comment by CyrusNajmabadi** [comment] 2018-02-02 23:29
That has the downside of not being able to run in the debugger and break the moment you hit unimplemented code.  Something i very much take advantage of :)

That said, i would not have an issue with adding an option to allow for that sort of behavior.  Of course, i really don't see it being much of an improvement if you have

```
int Foo() 
{
    return 0;
}

// vs

int Foo() 
{
    throw new NotImplementedException();
}
```

In both cases you need to go delete that line to put in the real logic you care about.

**Comment by CyrusNajmabadi** [comment] 2018-02-02 23:32
> Out-variables would also be assigned default values in an approach like this.

That's what makes it seem actually worse.  Now instead of a single simple statement that makes the code compilable, *and* which provides a good debugging loop, we may have to generate many statements that you still have to go fixup to do things right.

--

Note: the option was really added because that's how VB had done things, and we regressed that behavior. As i'm not a fan of having C# and VB have different behavior that can't be brought in sync, i made the option for C# as well.

Properties also seemed an acceptable area to remove the throw as auto-props are actually a common way to implement an interface.  i.e. with props there's actually a simple and reasonable impl that has a reasonable likelihood of being what the user would want.  With other members it doesn't seem like that would be hte case.  i.e. i think it would be incredibly rare that a user would want the implemented member to just be "SomeType Foo() { return default; }```.

**Comment by CyrusNajmabadi** [comment] 2018-02-02 23:36
Note that the large part of the complaint seems to be about:

> It's ESPECIALLY stupid because any getter-setter property gets two of these giant freaking exceptions for both getter and setter.

This is addressed by the option we already have.

I'm not really sure i buy the complaint about the rest of the members given that you're going to have to go deal with all the implementations anyway, and my belief is that the majority of non-property interface members will need real logic in their implementations.  So this behavior makes sense as the default for our generation features.

**Comment by sharwell** [comment] 2018-02-05 02:06
> This is addressed by the option we already have.

Yes, that's what I was saying above. For me, the current generation behavior is a reasonable safeguard against shipping unreviewed and likely incorrect code. 

For now I'm going to close this as By Design, but if someone wants to work on a proposal for a modified feature that preserves long term correctness of a program with less work for the developer then I would be interested see it.

**Closed by sharwell** 2018-02-05 02:06 UTC
Labels: Area-IDE, Developer Community, Discussion
