### ISSUE TITLE
ToolsError build failures in 'prodcon/corefx/release/2.1/' - '20180903.01'

### ISSUE THREAD

**Issue by alexperovich** [dotnet/roslyn#29670] opened 2018-09-04 21:46 UTC
@dotnet-mc-bot commented on [Mon Sep 03 2018](https://github.com/dotnet/core-eng/issues/4146)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2000094
  - **Agent:** DDVSOLINUXAGE011
  - **Error log:** /root/corefx-2000094/packages/microsoft.netcore.compilers/2.8.0-beta2-62719-08/tools/Microsoft.CSharp.Core.targets(0,0): error MSB3883: Unexpected exception:  [/root/corefx-2000094/src/Microsoft.CSharp/ref/Microsoft.CSharp.csproj]...

@jcagme, @markwilkie

---

@alexperovich commented on [Tue Sep 04 2018](https://github.com/dotnet/core-eng/issues/4146#issuecomment-418528466)

This is an issue in the microsoft.netcore.compilers package version 2.8.0-beta2-62719-08

**Comment by jaredpar** [comment] 2018-09-05 15:43
Here is the error message text

```
2018-09-03T07:32:56.6170715Z /root/corefx-2000094/packages/microsoft.netcore.compilers/2.8.0-beta2-62719-08/tools/Microsoft.CSharp.Core.targets(52,5): error : System.AggregateException: One or more errors occurred. (The system cannot open the device or file specified : 'root.F.asUJAshs63EKTWX06qvk4CFN5.client') ---> System.IO.IOException: The system cannot open the device or file specified : 'root.F.asUJAshs63EKTWX06qvk4CFN5.client' [/root/corefx-2000094/src/Microsoft.CSharp/ref/Microsoft.CSharp.csproj]
2018-09-03T07:32:56.6208376Z /root/corefx-2000094/packages/microsoft.netcore.compilers/2.8.0-beta2-62719-08/tools/Microsoft.CSharp.Core.targets(52,5): error : at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew) [/root/corefx-2000094/src/Microsoft.CSharp/ref/Microsoft.CSharp.csproj]
2018-09-03T07:32:56.6248194Z /root/corefx-2000094/packages/microsoft.netcore.compilers/2.8.0-beta2-62719-08/tools/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.RunServerCompilationCore(RequestLanguage language, List`1 arguments, BuildPathsAlt buildPaths, String pipeName, String keepA
```

This a dupe of #24124. The latest compiler toolset has a fix for this problem.

**Closed by jaredpar** 2018-09-05 15:43 UTC
