### ISSUE TITLE
AsyncIteratorWithParameter test failure

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#47156] opened 2020-08-26 17:26 UTC
CI run: https://dev.azure.com/dnceng/public/_build/results?buildId=786889&view=ms.vss-test-web.build-test-results-tab&runId=24799158&resultId=102610&paneView=debug

Error message:

```cs
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.ThrowInvalidOperationException()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.CompletionSentinel(Object _)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.InvokeContinuation()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
   at C.M(Int32 parameter)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at C.M(Int32 parameter)
   at C.Main()
   at C.Main()
   at C.<Main>()
```

It appears that an exception was thrown when executing the code compiled in the test. /cc @jcouv

**Comment by jcouv** [comment] 2020-08-26 17:31
@jaredpar, I recall you mentioned a flaky issue with async-streams recently due to our set of referenced assemblies. Does it look the same?

**Comment by jaredpar** [comment] 2020-08-29 06:03
No this is different than the issue that I was referring to. That reproduces with assembly load errors when executing the program.

**Comment by sharwell** [comment] 2021-04-22 01:05
Duplicate of #34207

**Closed by sharwell** 2021-04-22 01:05 UTC
Labels: Area-Compilers, Flaky, Test
