### ISSUE TITLE
C# comment <summary> showing in collapsed mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28093] opened 2018-06-25 07:12 UTC
Using c# comments

 /// &lt;summary&gt;
        /// Import
        /// &lt;/summary&gt;
        /// &lt;param name=&quot;fileStream&quot;&gt;&lt;/param&gt;
        /// &lt;returns&gt;&lt;/returns&gt;
        Task&lt;long&gt; Import(Stream fileStream);

In collpased mode it shows
/// &lt;summary&gt; Import

The &lt;summary&gt; portion shouldn't be seen

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/276820/c-comment-showing-in-collapsed-mode.html
VSTS ticketId: 635931_
_These are the original issue comments:_

DotnetShadow on 6/19/2018, 04:13 PM (5 days ago): This issue seems to affect c# Interface onl
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-06-25 07:28
As far as i know, this is veyr much by-design.  We've been doing things this way in c# for years now. 

(unless i'm not understanding what the person is reporting).

**Comment by sharwell** [comment] 2018-06-26 16:15
Tentatively marking this as **By Design**. Will update or close based on the outcome of a design review.

**Comment by sharwell** [comment] 2018-09-14 01:37
I confirmed in the design meeting that this is the expected behavior for this feature.

**Closed by sharwell** 2018-09-14 01:37 UTC
Labels: Area-IDE, Developer Community, Need Design Review, Resolution-By Design
