### ISSUE TITLE
Task.Result and Task.Wait design flaw leads to deadlock in high loaded applications

### ISSUE THREAD

**Issue by AqlaSolutions** [dotnet/roslyn#13611] opened 2016-09-05 21:32 UTC
Run this application:

https://gist.github.com/AqlaSolutions/f8c993bfad32dc9be11703fea4e01422

It simulates network engine receiving requests and calling synchronously `IConnection.OnRequestReceived`.  This method calls async method and then synchronously processes the result retrieved with `Task.Result`. The async method may take up to 700 ms.

During run the simulation will decrease time between requests until deadlock occurs - after that point  currently awaiting requests will never be completed.

This example proves that absolutely any call to `Task.Result` or `Task.Wait` (before task completion) from `ThreadPool` thread will work for some time but will eventually deadlock your application in truly high load scenario. Using these methods from `ThreadPool` thread for waiting is always a mistake and should be disallowed (but I understand that it will not happen for compatibility reasons).

What do you think? May be some workarounds inside .NET TP? Prioritize continuations over new tasks?

**Comment by benaadams** [comment] 2016-09-05 21:42
`Task.Result` and `Task.Wait` block the current thread you should use `await`

The workaround if you are blocking threadpool threads is to set threadpool minthreads to a high number; though that isn't very scalable.

The main workaround is to not use blocking methods in threadpool threads.

**Comment by AqlaSolutions** [comment] 2016-09-05 21:47
@beannaich, 

1. I can't use await, because external network engine provides synchronous interface
2. `Task.Result` is just not recommended. When you put it there it actually looks like it works ok and I think many people do that.

**Comment by benaadams** [comment] 2016-09-05 21:51
You are basically hobbling the threadpool with 
```
ThreadPool.SetMinThreads(2, 200);
ThreadPool.SetMaxThreads(10, 200);
```
try
```
ThreadPool.SetMinThreads(200, 200);
ThreadPool.SetMaxThreads(1000, 200);
```
and you probably won't have any problems; though its not a good solution

**Comment by AqlaSolutions** [comment] 2016-09-05 21:55
@benaadams, I set TP to low threads number to show the problem. It will also happen on 200 and 1000 threads but it will just take more time and will require modifying the simulation code for more requests. In a real app you will never want to set max threads to such big numbers because it will produce too much threads and make your app very very slow.

**Comment by HaloFour** [comment] 2016-09-05 23:49
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

In short, don't mix async and sync.  "Async all the way down."  If you can't fit in that model you're kind of stuck.

As for the potential of changing this, those would all be BCL concerns, not language concerns.  C# doesn't know nor care about `ThreadPool` or `Task`.  Check out the https://github.com/dotnet/corefx repo.

**Comment by benaadams** [comment] 2016-09-05 23:57
> I use NHibernate everywhere in our project and it's blocking. It's impossible to not use.

Raise an issue with NHibernate? A blocking call will block a thread and as you've pointed out the issues with that.

**Comment by AqlaSolutions** [comment] 2016-09-05 23:59
@HaloFour, when "you can't fit" almost everyone suggests to "just use `.Result` here". They all know about "not mixing" but `.Result` looks like exactly for mixing. This deadlock is not obvious and someone may never encounter it during testing.

**Comment by HaloFour** [comment] 2016-09-06 00:37
If NH thinks that DB I/O time is best spent blocking threads then you should seriously find another solution as they are clearly criminally incompetant.  If they're the ones recommending to "just use .Result" that further validates my opinion.  MS docs very clearly state to not do this, as does every article they've written on the subject.

**Comment by benaadams** [comment] 2016-09-06 00:44
If you have to shoot yourself in the foot use `.GetAwaiter().GetResult()` rather than `.Result`, it will give a better exception if something went wrong.

**Comment by CyrusNajmabadi** [comment] 2016-09-06 01:53
Roslyn does not appear to be the right repo for this issue.

**Comment by terrajobst** [comment] 2016-09-06 02:08
@AqlaSolutions

Unless you think the problem is in the code generated by the Roslyn compiler, you should close this issue and file a new one against the `Task` APIs which are part of the http://github.com/dotnet/corefx repository.

**Closed** 2016-09-06 07:42 UTC

**Comment by AqlaSolutions** [comment] 2016-09-06 08:02
https://github.com/dotnet/corefx/issues/11463

**Comment by terrajobst** [comment] 2016-09-06 22:02
Thanks!
