### ISSUE TITLE
Add ChangeSignature refactoring for record primary constructor

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#45961] opened 2020-07-14 13:01 UTC
It should be possible to reorder parameters of a record primary constructor, just like it is for normal methods.
This should be careful to effect usage of the deconstructor as well.

**Comment by jcouv** [comment] 2020-09-02 20:16
Duplicate of https://github.com/dotnet/roslyn/issues/44558

**Closed by jcouv** 2020-09-02 20:16 UTC
Labels: Area-IDE, Concept-Continuous Improvement, New Language Feature - Records
