### ISSUE TITLE
VBCSCompiler uses a lot of CPU when idle in OSX

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn#24216] opened 2018-01-12 22:52 UTC
**Version Used**: 

**Steps to Reproduce**:

1.  dotnet new console
2. dotnet build

**Expected Behavior**:
A VBCSCompiler process is created but sits idle when no compilation is being done.

**Actual Behavior**:
A VBCSCompiler process is created and according to Activity Monitor uses about 110% of CPU all the time. I can hear the fans on my Mac running non-stop even when there is nothing else going on in it. Checking activity monitor I can see the dotnet process spinning. The one that hosts the VBCSCompiler.

**Comment by jcouv** [comment] 2018-01-13 21:40
Tagging @jaredpar

**Comment by jaredpar** [comment] 2018-01-16 16:07
Closing as a dupe of #24137.

**Closed by jaredpar** 2018-01-16 16:07 UTC
Labels: Area-Compilers
