### ISSUE TITLE
Naming style rules for 'type_parameter' are not functioning as I would expect

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#19727] opened 2017-05-23 20:01 UTC
I have defined the following naming style rules:
```
dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.severity = suggestion
dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.style = pascal_case_prefixed_with_t
dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.symbols = type_parameters

dotnet_naming_style.pascal_case_prefixed_with_t.capitalization = pascal_case
dotnet_naming_style.pascal_case_prefixed_with_t.required_prefix = T

dotnet_naming_symbols.type_parameters.applicable_kinds = type_parameter
```

With this rule, I am getting a suggestion that `public bool Equals(MyClass other)` be replaced with `public bool Equals(MyClass TOther)`.

However, I would not expect that a suggestion is provided for the above code. Instead, I would expect it to provide a suggestion in the case of `public class MyClass<MyParameter>` (where it would suggest `public class MyClass<TMyParameter>`).

**Comment by tannergooding** [comment] 2017-05-23 20:02
This is impacting both LightBulb and Completion.

**Comment by tannergooding** [comment] 2017-05-23 20:06
1. Install VS 2017 Preview 1 (this also repros in D15PreRel 26521.01)
2. Create a new C# Class Library (.NET Framework, .NET Standard, or .NET Core)
3. Close the Class1.cs file
4. Add a new solution file ".editorconfig"
5. Set its contents to the following
```
###############################################################################
# Top-most EditorConfig file
###############################################################################
root = true

###############################################################################
# Set dotnet naming rules to:
#    suggest async members be pascal case suffixed with Async
#    suggest interfaces be pascal case prefixed with I 
#    suggest private and internal fields be camel case and prefixed with underscore
#    suggest public and protected declarations be pascal case
#    suggest type parameters be pascal case prefixed with T
###############################################################################
[*.cs]
dotnet_naming_rule.async_members_should_be_pascal_case_suffixed_with_async.severity = suggestion
dotnet_naming_rule.async_members_should_be_pascal_case_suffixed_with_async.style = pascal_case_suffixed_with_async
dotnet_naming_rule.async_members_should_be_pascal_case_suffixed_with_async.symbols = async_members

dotnet_naming_rule.interfaces_should_be_pascal_case_prefixed_with_i.severity = suggestion
dotnet_naming_rule.interfaces_should_be_pascal_case_prefixed_with_i.style = pascal_case_prefixed_with_i
dotnet_naming_rule.interfaces_should_be_pascal_case_prefixed_with_i.symbols = interfaces

dotnet_naming_rule.private_and_internal_fields_should_be_camel_case_prefixed_with_underscore.severity = suggestion
dotnet_naming_rule.private_and_internal_fields_should_be_camel_case_prefixed_with_underscore.style = camel_case_prefixed_with_underscore
dotnet_naming_rule.private_and_internal_fields_should_be_camel_case_prefixed_with_underscore.symbols = private_and_internal_fields

dotnet_naming_rule.public_and_protected_declarations_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.public_and_protected_declarations_should_be_pascal_case.style = pascal_case
dotnet_naming_rule.public_and_protected_declarations_should_be_pascal_case.symbols = public_and_protected_declarations

dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.severity = suggestion
dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.style = pascal_case_prefixed_with_t
dotnet_naming_rule.type_parameters_should_be_pascal_case_prefixed_with_t.symbols = type_parameters

###############################################################################
# Set dotnet naming styles to define:
#   camel case prefixed with _
#   pascal case
#   pascal case prefixed with I
#   pascal case prefixed with T
#   pascal case suffixed with Async
###############################################################################
[*.cs]
dotnet_naming_style.camel_case_prefixed_with_underscore.capitilization = camel_case
dotnet_naming_style.camel_case_prefixed_with_underscore.required_prefix = _

dotnet_naming_style.pascal_case.capitilization = pascal_case

dotnet_naming_style.pascal_case_prefixed_with_i.capitilization = pascal_case
dotnet_naming_style.pascal_case_prefixed_with_i.required_prefix = I

dotnet_naming_style.pascal_case_prefixed_with_t.capitilization = pascal_case
dotnet_naming_style.pascal_case_prefixed_with_t.required_prefix = T

dotnet_naming_style.pascal_case_suffixed_with_async.capitilization = pascal_case
dotnet_naming_style.pascal_case_suffixed_with_async.required_suffix = Async

###############################################################################
# Set dotnet naming symbols to:
#   async members
#   private and internal fields
#   public and protected declarations
#   type parameters
###############################################################################
[*.cs]
dotnet_naming_symbols.async_members.required_modifiers = async

dotnet_naming_symbols.interfaces.applicable_kinds = interface

dotnet_naming_symbols.private_and_internal_fields.applicable_accessibilities = private, internal
dotnet_naming_symbols.private_and_internal_fields.applicable_kinds = field

dotnet_naming_symbols.public_and_protected_declarations.applicable_accessibilities = public, protected

dotnet_naming_symbols.type_parameters.applicable_kinds = type_parameter
```
6. Open the Class1.cs file
7. Set its contents to the following
```C#
using System;

public class MyClass<MyParameter> : IEquatable<MyParameter>
{
    public bool Equals(MyParameter other)
    {
        throw new NotImplementedException();
    }
}
```

**Expected Behavior**
A naming suggestion should be provided to change `public class MyClass<MyParameter>` to `public class MyClass<TMyParameter>`

**Actual Behavior**
A naming suggestion is provided to change `public bool Equals(MyParameter other)` to `public bool Equals(MyParameter TOther)`

**Comment by Pilchie** [comment] 2017-05-24 20:41
Dupe of https://github.com/dotnet/roslyn/issues/18121.

**Closed by Pilchie** 2017-05-24 20:41 UTC
Labels: Area-IDE, Bug
