### ISSUE TITLE
CS8107 Feature 'nullable reference types' is not available in C# 7.0. Please use language version 8.0 or greater

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31666] opened 2018-12-10 19:17 UTC
This error reported for this sequence of code 

        public static byte[] ConvertToByteArray(object value)
        {
            return
                value is byte[] ? (byte[])value :
                value == null ? null :
                    Util.Convert.ToByteArray(value);
        }

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/400852/cs8107-feature-nullable-reference-types-is-not-ava.html
VSTS ticketId: 742071_
_These are the original issue comments:_

Alexey Kuznetsov on 12/7/2018, 01:15 AM (3 days ago): The similar problem.The code the something like that:object value = new string[0];object resultValue = value is string[]? value as string[] : new[] \{ value.ToString() };Lang c#7. Works in VS 2017.
_These are the original issue solutions:_
(no solutions)

**Comment by jaredpar** [comment] 2018-12-10 19:20
@cston isn't this a dupe of the conditional parsing bug you fixed for preview 2?

**Comment by cston** [comment] 2018-12-10 20:42
@jaredpar, yes this is the parsing bug fixed in https://github.com/dotnet/roslyn/pull/31050.

**Closed** 2018-12-10 21:39 UTC
Labels: Area-Compilers, Bug
