### ISSUE TITLE
Code Lens reference count is broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32738] opened 2019-01-24 15:44 UTC
Reported in Build :15.0.26206.0 

Pick any class that is used directly in code. Extract an interface for this class and pick some properties/methods to be part of the interface. Open the interface. Even though the interface is not referenced anywhere except by the implementing class, all properties and methods on the interface have multiple references. It looks like it is showing references to the properties/methods of any classes implementing the interface instead of actual references that use the interface. At best this is somehow useful to some people, at worst it's just plain wrong. Certainly it's not a reference. 

At the very least there should be an option to disable this behavior, or to show either/both &quot;strict&quot; and &quot;loose&quot; references.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/20609/code-lens-reference-count-is-broken.html
VSTS ticketId: 418871_
_These are the original issue comments:_

Morten Mertner on 7/19/2018, 06:15 AM (189 days ago): It's great to see that these issues are being monitored and acted upon. Or wait...
Alexander Martens on 8/8/2018, 09:56 AM (169 days ago): <p>The other Issue I saw on this were closed as by design. It's awful. Why on earth should every IDisposable Dispose() be linked...</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-01-24 18:23
Tentatively marked as **By Design** and will update with more information from the design review meeting.

**Comment by sharwell** [comment] 2019-02-26 14:49
The current CodeLens behavior is by design. However, keep in mind that we have recently done many improvements to the Find All References experience, which we anticipate will better meet the needs of users interested in finding particular kinds of references. When using Find All References, you can right click the columns and choose **Show Columns &rarr; Kind** to see the new reference kind designations.

![image](https://user-images.githubusercontent.com/1408396/53421515-634db400-39a3-11e9-9371-a9a25009f5d9.png)

**Closed by sharwell** 2019-02-26 14:49 UTC
Labels: Area-IDE, Developer Community, Need Design Review, Resolution-By Design
