### ISSUE TITLE
Remove Unused References: Support assembly references

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#59834] opened 2022-03-01 04:50 UTC
**Version Used**: VS2022 17.0.6

**Steps to Reproduce**:

1. Create a sdk style project, target framework is net48
2. Add some assembly reference
3. Use "Remove Unused References"

**Expected Behavior**:
Remove Unused References

**Actual Behavior**:
Nothing removed

**Comment by CyrusNajmabadi** [comment] 2024-10-22 20:18
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-22 20:18 UTC
Labels: Area-IDE, Feature Request
