### ISSUE TITLE
Strange bug about const

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#35519] opened 2019-05-05 11:34 UTC
**Version Used**: 16.0.3

**Steps to Reproduce**:

1. Type this code:
```
    class Program
    {
        const int length = 5;

        static void Main(string[] args)
        {
            int len = 2;
            if (len < length)
                Console.WriteLine("OK");
        }
    }
```
2. Find All References for `length`

result:
![bug](https://user-images.githubusercontent.com/2529999/57193341-83ce5780-6f6c-11e9-8fa7-423756d8257f.png)

**Expected Behavior**: `if (len < length)`

**Actual Behavior**: `if (len < )`

**Comment by JoeRobich** [comment] 2019-05-07 14:15
This is a duplicate of https://github.com/dotnet/roslyn/issues/34307 and is fixed in 16.1 preview 2

**Closed by JoeRobich** 2019-05-07 14:15 UTC
Labels: Area-IDE, Bug
