### ISSUE TITLE
[Bug] Default value for parameter of generic type in local functions

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#21447] opened 2017-08-11 11:37 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16

**Steps to Reproduce**:

1. Create a default ConsoleApp and write code:
```cs
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        TValue GetValueOrDefaultLocal<TKey, TValue>(IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, int y = 10, TValue defaultValue = default(TValue))
        //                                                                                                        Highlighted: ^~~~~~~~~~~^           ^~~~~^
            => dictionary != null && dictionary.TryGetValue(key, out var value) ? value : defaultValue;
    }

    TValue GetValueOrDefault<TKey, TValue>(IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue = default(TValue))
        => dictionary != null && dictionary.TryGetValue(key, out var value) ? value : defaultValue;
}
```
2. Compile it.
3. Type-level method compiled successfully, but local method compiled with two errors.

**Expected Behavior**: Code compiled sucessfully.
**Actual Behavior**: I have errors in output:
> 1>C:\…\ConsoleApp2\Program.cs(7,151,7,157): error CS0246: The type or namespace name 'TValue' could not be found (are you missing a using directive or an assembly reference?)
> 1>C:\…\ConsoleApp2\Program.cs(7,128,7,140): error CS1750: A value of type 'TValue' cannot be used as a default parameter because there are no standard conversions to type 'TValue'

**Comment by alrz** [comment] 2017-08-11 12:27
I can't repro in VS 15.3 Preview 7.0.

**Comment by sharwell** [comment] 2017-08-11 13:41
Appears to be a duplicate of #17719.

**Closed** 2017-08-11 13:41 UTC
