### ISSUE TITLE
CompilationOptions.Platform is not giving the configuration option used for msbuild

### ISSUE THREAD

**Issue by msbasanth** [dotnet/roslyn#29369] opened 2018-08-17 17:43 UTC
**Version Used**: 
Roslyn v2.6.0

**Steps to Reproduce**:
If msbuild configuration (x64) and <PlatformTarget> tag matches we are getting correct CompilationOptaions.Platform inside our analyzer implementation.
Observations:
1. If msbuild is configuration is x64/Debug & <PlatformTarget> tag in the corresponding PropertyGroup in csproj is AnyCpu. Inside analyzer implementation SemanticModel.Compilation.Options is giving Platform as 'AnyCpu32BitPreferred' 
2. Another scenario <PlatformTarget> was not present in the ProjectGroup of interest (Debug|x64), here CompilationOptions.Platform evaluated to “AnyCPU”. 

**Expected Behavior**:
I am using CompilerOptions for finding the correct PropertyGroup in CSPROJ for retrieving OutputPath.

**Actual Behavior**:

So unable to relay on Compilation.Options to retrieve actual configuration platform/optimizationlevel used in msbuild.
Is there any other way I can get the platform option currently used for compilation (msbuild)?

Regards
Basanth

**Comment by jaredpar** [comment] 2018-08-20 15:18
> I am using CompilerOptions for finding the correct PropertyGroup in CSPROJ for retrieving OutputPath.

I believe you are referring to `CompilationOptions.Platform` here. That is controlled by the MSBuild property `$(PlatformTarget)` not `$(Configuration)` or `$(Platform)`. 

> So unable to relay on Compilation.Options to retrieve actual configuration platform/optimizationlevel used in msbuild. 

Can you specify which MSBuild property you are looking for here? It's unclear from your question.

**Comment by msbasanth** [comment] 2018-08-20 17:02
Yes, I was referring to CompilationOptions.Platform.

I wanted retrieve the PropertyGroup used in the current compilation for retrieving OutputPath from it.
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
 </PropertyGroup>

i.e. I have 6 combinations of Platform and Configuration in our CSPROJs

1. 'Debug|AnyCPU'
2. 'Debug|x86'
3. 'Debug|x64'
4. 'Release|AnyCPU'
5. 'Release|x86'
6. 'Release|x64'

E.g. When I am building [msbuild $(Configuration) & $(Platform)] with 'Debug x64', how can I retrieve Platform & Configuration of the current compilation from Roslyn Analyzer implementation. So that I can read the corresponding PropertyGroup (CSPROJ) and OutputPath inside it.

Thanks
Basanth

**Comment by jaredpar** [comment] 2018-08-20 21:14
> how can I retrieve Platform & Configuration of the current compilation from Roslyn Analyzer implementation.

I don't think there is really a way here. The compiler is primarily focused on providing the analyzer with compilation options here. The properties in MSBuild can in many cases be inferred from compiler options. However there is is not necessarily a 1:1 relationship here and it's not a goal of analyzers to provide such properties. 

Moving to analyzers and CC @jinujoe but my suspicion is that this is "By Design".

**Closed** 2021-09-16 02:01 UTC
Labels: Area-Analyzers, Need More Info, fabric-bot-test
