### ISSUE TITLE
Extract Method changes 'using var' semantic to 'out parameter' semantic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39329] opened 2019-10-16 19:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/760023/extract-method-changes-using-var-semantic-to-out-p.html)._

---
Using 'Extract Method' in a block containing 'using var' causes the resulting method to assign the variables to out parameters and contains no using expression.

---
#### Visual Studio Feedback System on 10/6/2019, 11:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:04 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2019-10-16 19:23
Verified in 16.4 preview 2 with the below code

### Before
```C#
    public class Goo : IDisposable
    {
        void M2() { }
        void M3() { }
        string S => "S";

        void M()
        {
            using var g = new Goo();
            var s = g.S;
            g.M2();
            g.M3();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
```

### After
```C#
    public class Goo : IDisposable
    {
        void M2() { }
        void M3() { }
        string S => "S";

        void M()
        {
            Goo g = NewMethod();
        }

        private static Goo NewMethod()
        {
            var g = new Goo();
            var s = g.S;
            g.M2();
            g.M3();
            return g;
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by RikkiGibson** [comment] 2019-10-16 20:13
The expectation is that the `Goo g = NewMethod();` would change to `using Goo g = NewMethod()`, right?

**Comment by ts2do** [comment] 2019-10-17 16:53
Here's the expected result of extracting the entire body from method M:
```csharp
    public class Goo : IDisposable
    {
        void M2() { }
        void M3() { }
        string S => "S";

        void M()
        {
            NewMethod();
        }

        private static void NewMethod()
        {
            using var g = new Goo();
            var s = g.S;
            g.M2();
            g.M3();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by davidwengier** [comment] 2019-11-22 04:18
> The expectation is that the Goo g = NewMethod(); would change to using Goo g = NewMethod(), right?

My expection is that, as above, NewMethod() wouldn't have a return type at all. I've been running into this a lot in some code I've got doing a lot of SkiaSharp drawing, and the problem is clearer IMO when there are multiple things with usings:

Before:
```
        private void M()
        {
            using var x1 = new System.IO.MemoryStream();
            using var x2 = new System.IO.MemoryStream();
            using var x3 = new System.IO.MemoryStream();
        }
```

After extracting the all 3 lines to a method:
```
 		private void M()
        {
            MemoryStream x1, x2, x3;
            NewMethod(out x1, out x2, out x3);
        }

        private static void NewMethod(out MemoryStream x1, out MemoryStream x2, out MemoryStream x3)
        {
            x1 = new System.IO.MemoryStream();
            x2 = new System.IO.MemoryStream();
            x3 = new System.IO.MemoryStream();
        }
```

It's not that the usings are gone, though obviously thats not good, its that the analysis thinks the variables are used outside of the selection, even though all of the method contents were selected.

**Comment by ts2do** [comment] 2019-11-26 02:21
After further consideration, it seems like an extremely complex construct to handle properly.

Consider this method:
```csharp
(T, T, T) Method<T>(IEnumerable<T> source1, IEnumerable<T> source2, IEnumerable<T> source3)
{
    using IEnumerator<T> enumerator1 = source1.GetEnumerator();
    using IEnumerator<T> enumerator2 = source2.GetEnumerator();
    using IEnumerator<T> enumerator3 = source2.GetEnumerator();

    enumerator1.MoveNext();
    enumerator2.MoveNext();
    enumerator3.MoveNext();

    return (enumerator1.Current, enumerator2.Current, enumerator3.Current);
}
```

If you try to extract all but the last line of the method body, you would end up with something akin to this:
```csharp
(T, T, T) Method<T>(IEnumerable<T> source1, IEnumerable<T> source2, IEnumerable<T> source3)
{
    IEnumerator<T> enumerator1 = null;
    IEnumerator<T> enumerator2 = null;
    IEnumerator<T> enumerator3 = null;

    try
    {
        ExtractedMethod(source1, source2, source3, out IEnumerator<T> enumerator1, out IEnumerator<T> enumerator2, out IEnumerator<T> enumerator3);

        return (enumerator1.Current, enumerator2.Current, enumerator3.Current);
    }
    finally
    {
        try
        {
            enumerator3?.Dispose();
        }
        finally
        {
            try
            {
                enumerator2?.Dispose();
            }
            finally
            {
                enumerator1?.Dispose();
            }
        }
    }
}

void ExtractedMethod<T>(IEnumerable<T> source1, IEnumerable<T> source2, IEnumerable<T> source3, out IEnumerator<T> enumerator1, out IEnumerator<T> enumerator2, out IEnumerator<T> enumerator3)
{
    IEnumerator<T> enumerator1 = null;
    IEnumerator<T> enumerator2 = null;
    IEnumerator<T> enumerator3 = null;

    try
    {
        enumerator1 = source1.GetEnumerator();
        enumerator2 = source2.GetEnumerator();
        enumerator3 = source3.GetEnumerator();

        enumerator1.MoveNext();
        enumerator2.MoveNext();
        enumerator3.MoveNext();
    }
    catch
    {
        try
        {
            enumerator3?.Dispose();
        }
        finally
        {
            try
            {
                enumerator2?.Dispose();
            }
            finally
            {
                enumerator1?.Dispose();
            }
        }
        throw;
    }
}
```

This would be the correct handling for such an operation. The code would get even uglier if any of the variables used a type that chose to explicitly implemented `IDisposable`, because, while `using` supports direct invocation of such methods, boxing to `IDisposable` is required if translating to the try-finally equivalent.

The only adequate solution I see is to either not show the 'Extract Method' quick action or reject the request with an error when the code selection doesn't span to the closing bracket ending the using var expressions within the selection. Anything else would clearly cause a lot of unexpected code generation.

**Comment by jnm2** [comment] 2020-07-25 19:02
Another repro:

```cs
using System.Collections.Generic;

class C
{
    bool M(IEnumerable<int> p)
    {
        [|using var x = p.GetEnumerator();
        return x.MoveNext();|]
    }
}
```

🛠 Extract method:

```cs
using System.Collections.Generic;

class C
{
    bool M(IEnumerable<int> p)
    {
        IEnumerator<int> x;
        return NewMethod(p, out x);
    }

    private static bool NewMethod(IEnumerable<int> p, out IEnumerator<int> x)
    {
        x = p.GetEnumerator();
        return x.MoveNext();
    }
}
```

**Comment by jnm2** [comment] 2020-07-25 19:03
The danger is that you might forget to put the `using` token back.

**Closed** 2024-12-10 01:45 UTC
Labels: Bug, help wanted, Area-IDE, Developer Community, IDE-CodeStyle, Feature - Extract Method
