### ISSUE TITLE
[Request] Strike-out and dim obsolete/deprecated elements in code completion

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#47140] opened 2020-08-26 07:38 UTC
Hello,

The code completion in VS code strike out and dim obsolete/deprecated and non-standard elements in code completion.
I would be nice when the code completion in Visual Studio have this too.

## Non-standard elements VS code
![2020-08-26 09_09_58-● basicElements css - Website - Visual Studio Code](https://user-images.githubusercontent.com/17874713/91272447-07bcdc00-e77c-11ea-8274-e844717f5afc.png)

## Deprecated element in Visual Studio
![2020-08-26 09_14_28](https://user-images.githubusercontent.com/17874713/91272884-bcef9400-e77c-11ea-9c7d-c81335db9b1f.png)

**Comment by RikkiGibson** [comment] 2020-08-26 13:22
I think we can do the Visual Studio side in Roslyn but the VS Code side may require an issue in https://github.com/omnisharp/omnisharp-vscode

**Comment by CyrusNajmabadi** [comment] 2020-08-27 18:15
@olegtk @gundermanc does the VS editor api for completion allow for strikethrough?

**Comment by sharwell** [comment] 2020-08-27 18:25
Duplicate of #26488

**Closed by sharwell** 2020-08-27 18:25 UTC
Labels: Area-IDE, Feature Request

**Comment by olegtk** [comment] 2020-08-27 19:07
no such support, but great idea. There is a way to provide additional icons (called attribute icons), I think you use those to indicate when a completion item is not available in some project targets. But I agree it would be nice to add strikethrough support. Any other presentation variants you would like to have? Please create a suggestion bug for the editor, @jinujoseph 
Thanks!

**Comment by jinujoseph** [comment] 2020-09-01 07:59
Suggestion bug tracked [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1192226)
