### ISSUE TITLE
Text editor option for preprocessor directives missing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58681] opened 2022-01-06 22:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Text-editor-option-for-predecessor-direc/1610607)._

---
The following Text Editor option for C++ should be also provided for C#:
Code Style/Formatting/Indentation/Position of preprocessor directives
- One indent to the left
- Move to the leftmost column
- **Leave intended**

In my code files, #If/#else/#elif/#endif are always at column 1. But #region/#endregion are intended according to the code block. When I enter another #if, the #regions are shifted to column 1 too. This is what I want to suppress.

---
#### Feedback Bot on 12/12/2021, 11:14 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment] 2022-01-13 23:53
duplicate of #12306

**Closed by jinujoseph** 2022-01-13 23:53 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community
