### ISSUE TITLE
Unnecessary defensive copy in collection spread for ROS nullability change

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#76303] opened 2024-12-06 18:51 UTC
**Version Used**: 
17.13.0 Preview 1.0

**Steps to Reproduce**:

```csharp
internal static string CombineWithSlash(ReadOnlySpan<string> pathElements)
{
    return string.Join('/', [.. pathElements]);
}
```
Where `string.Join`'s second parameter is a `ReadOnlySpan<string?>`

[Sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwYQwb2Q2IwEsA7AFwFMAncgQwBss4A2VgBlwHsBbAEYVqAdVKUAFgGUmDAM4SAFACVqDYAHlyTAJ5SADg3IAeKHE4A+DIckBRJtT7UqcgJREShJCR9YA7FwAdABSPBSKAOQA9BEANBgA2oGBNhL2js6UcgC6rgDcHsQAvshFQA=).

**Expected Behavior**:

It is always safe to convert a `ReadOnlySpan<U>` to a `ReadOnlySpan<T>` when `U` inherits from `T` (and neither are value types).
On .NET 9, this can be turned into `string.Join('/', ReadOnlySpan<string?>.CastUp(pathElements))`. The nullability case here can be suppressed, since it's known to be safe.

**Actual Behavior**:

As per sharplab above: `return string.Join('/', new ReadOnlySpan<string>(pathElements.ToArray()));`

**Comment by RikkiGibson** [comment] 2024-12-08 19:06
Thanks for filing this issue.

The [first class spans](https://github.com/dotnet/csharplang/blob/main/proposals/first-class-span-types.md#variance) feature adds a covariant implicit conversion for `ReadOnlySpan` which is equivalent to calling `CastUp`. With this, you will be able to just change `[.. pathElements]` to `pathElements` and carry on.

We are not planning to change codegen here for a few reasons, most prominent being that `ReadOnlySpan` only means _you_ can't mutate it. Someone with a mutable reference to the same memory can, e.g.:

```cs
int[] arr = [1,2,3];
ReadOnlySpan<int> ros1 = arr; // reference
ReadOnlySpan<int> ros2 = [..arr]; // copy
arr[0] = 4;
Console.Write(ros1[0]); // expect '4'
Console.Write(ros2[0]); // expect '1'
```

Closing as by design for the above reasons.

**Closed by RikkiGibson** 2024-12-08 19:06 UTC
Labels: Area-Compilers, untriaged
