### ISSUE TITLE
invalid IDE0028 (explicit interface implementation)

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#23672] opened 2017-12-08 14:28 UTC
**Version Used**: 

VS 15.5.0

**Steps to Reproduce**:

1. 

```cs
using System.Collections.Generic;
using System.Dynamic;

class Program
{
    static void Main()
    {
        // ExpandoObject doesn't have public Add method. Its Add is explicit implementation of IDictionary.
        IDictionary<string, object> obj = new ExpandoObject();
        obj.Add("string", "v");
        obj.Add("int", 1);
        obj.Add("object", new { X=1, Y=2 });
    }
}
```

2. IDE0028 Quick Action

```cs
IDictionary<string, object> obj = new ExpandoObject
{
    // Error CS1061 'ExpandoObject' does not contain a definition for 'Add'
    { "string", "v" },
    { "int", 1 },
    { "object", new { X = 1, Y = 2 } }
};
```

**Expected Behavior**:

No IDE0028 suggestion.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3760955/33769767-bb3b59c6-dc6e-11e7-8216-75a3e8771a6e.png)

**Comment by sharwell** [comment] 2017-12-08 14:45
This is similar to (but not a duplicate of) #23368.

**Closed** 2018-05-04 18:51 UTC
Labels: Area-IDE, Bug, help wanted
