### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit32 on PR #8799

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8827] opened 2016-02-17 19:53 UTC
PR: [#8799](https://github.com/dotnet/roslyn/pull/8799) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3958/

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by natidea** [comment] 2016-02-17 22:50
Duplicate of #8807

**Closed by natidea** 2016-02-17 22:50 UTC
Labels: Area-Infrastructure, Contributor Pain, Resolution-Duplicate
