### ISSUE TITLE
MemberNotNull on local functions doesn't work

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#49234] opened 2020-11-09 02:50 UTC
**Version Used**: 
https://github.com/dotnet/roslyn/commit/770eabf816f9c0be05d9af1475235f3edb237685

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFBUACATAIy0AMhNDAdACICWEA5mgD2sHgGMoHAMJCAJnACCpLAE8oPKAG4WbTgBUAFgjgRZPNP23VKNAMxs6hKVQDeVQh8IAHBDwBuEPCEQsAAVnBiMAD8hAD6IaFWnoTungDaALJwYMCIAHJCMHnYWAAUpGBwQgBmpfFhAJQNALqpHnbBYREwhBmlDW2EbpTJyTQA7HEJhFExAJJoPDB8WDwAXnD9SaMeg8mZ2bkIBUUl5RCVNXUJTa0jO53hkYQLSyvrmwP3O8MPo/WhQgAXkIaDgAHdHt0tnsHhMpmFtjsAL6DVGUdFUCpwKBeCBiIjsbh8QQiZYSaRyRTKNQaVyDei9Q75QrFHAKGAwXzADBBECEDlcng8+CDX5w+xZHIs07sznc3mbdisbENIbo5Lo5FAA=
```C#
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Threading;

public class C
{
    private object? _obj;
    
    [MemberNotNull(nameof(_obj))]
    public object M()
    {
        return _obj ?? Initialize();
        
        [MemberNotNull(nameof(_obj))]
        object Initialize()
        {
            _obj = new object();
            return _obj;
        }
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    class MemberNotNullAttribute : Attribute
    {
        public MemberNotNullAttribute(string name) {}
    }
}
``` 

**Expected Behavior**:
No warnings.

**Actual Behavior**:
```
warning CS8774: Member '_obj' must have a non-null value when exiting.
```

**Comment by Youssef1313** [comment] 2020-11-09 06:57
Related to (or probably duplicate of) #47896

**Comment by jaredpar** [comment] 2020-11-09 15:34
Duping to #47896 (thanks @Youssef1313)

**Closed by jaredpar** 2020-11-09 15:34 UTC
Labels: Area-Compilers, untriaged

**Comment by waltdestler** [comment] 2021-11-26 19:37
This issue still repros as-is (after deleting the custom MemberNotNullAttribute) for me in .NET 6.0.100 even though the issue it duplicates is closed as fixed. Should I open a new issue for it or do you want to reopen this one?

**Comment by Youssef1313** [comment] 2021-11-26 19:56
@waltdestler #56256 is reopened now.
