### ISSUE TITLE
'Convert switch statement to expression' breaks code.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#36876] opened 2019-06-28 19:51 UTC
Conversion on:

```c#
                long target;
                try
                {
                    switch (origin)
                    {
                        case SeekOrigin.Begin:
                            target = offset;
                            break;

                        case SeekOrigin.Current:
                            target = checked(offset + position);
                            break;

                        case SeekOrigin.End:
                            target = checked(offset + length);
                            break;

                        default:
                            throw new ArgumentOutOfRangeException(nameof(origin));
                    }
                }
                catch (OverflowException)
                {
                    throw new ArgumentOutOfRangeException(nameof(offset));
                }

                if (target < 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(offset));
                }
```

Produced:

```c#
                try
                {
                    var target = origin switch
                    {
                        SeekOrigin.Begin => offset,

                        SeekOrigin.Current => checked(offset + position),

                        SeekOrigin.End => checked(offset + length),

                        _ => throw new ArgumentOutOfRangeException(nameof(origin)),
                    };
                }
                catch (OverflowException)
                {
                    throw new ArgumentOutOfRangeException(nameof(offset));
                }

                if (target < 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(offset));
                }
```

**Comment by jinujoseph** [comment] 2019-07-02 18:16
@jasonmalinowski  Is this a Duplicate of #36608

**Comment by alrz** [comment] 2019-07-02 19:57
I think not. this is about the use after switch (should not move decl). #36608 is about the common type.

**Closed** 2019-10-03 19:13 UTC
Labels: Area-IDE, Bug
