### ISSUE TITLE
[Bug]: Wrong type is used from parent namespace

### ISSUE THREAD

**Issue by gaborposz** [dotnet/roslyn#66995] opened 2023-02-22 17:00 UTC
### Issue Description

I have an assembly named _Namespace.dll_. It contains a type:
```
namespace Namespace
{
    public class MyType
    {
        public static void WhereAreYouFrom()
        {
            Console.WriteLine("I'm from Namespace.");
        }
    }
}
```

I have another assembly, named _Namespace.Core.dll_. It contains another type with the same name, but in a different namespace:
```
namespace Namespace.Core
{
    public class MyType
    {
        public static void WhereAreYouFrom()
        {
            Console.WriteLine("I'm from syngo.Namespace.Core.");
        }
    }
}
```

I have a consumer project, named _Namespace.NastyUsingsExample.exe_, that is referencing both assemblies.
It wants to use `MyType` from the `Namespace.Core` namespace, e.g.:

```
using Namespace.Core;

namespace Namespace.NastyUsingsExample
{
    public class Program
    {
        public static void Main()
        {
            MyType.WhereAreYouFrom();
            Console.ReadKey();
        }
    }
}
```

I expect that `Namespace.Core.MyType` is used here, as I have an explicit using for the `Namespace.Core` namespace, yet the `Namespace.MyType` will be used, because my `Program` class is also in the same `Namespace` namespace.

Or at least, I would expect an error, if the type is ambiguous. E.g.:
_Error	CS0104	'MyType' is an ambiguous reference between 'Namespace' and 'Namespace.Core'_

Of course, the actual problem is very easy to fix, but we are migrating several thousands of project files from the old project file format to the new SDK based format, and - due to the changed "transitive project references" behavior - now more types are visible than before, and it might happen, that we do not notice that a different type is used. So far we found only one occurence where a wrong Resource manager was picked up, but we only noticed it because of a failing test, so we are concerned that there might be more...

### Steps to Reproduce

Repro is attached:
[NastyUsingsExample.zip](https://github.com/dotnet/msbuild/files/10806366/NastyUsingsExample.zip)

### Expected Behavior

The type from the explict namespace should be used, or at least an "ambiguous reference" error should be thrown.

### Actual Behavior

Unexpected type is used.

**Comment by gaborposz** [comment] 2023-02-22 17:13
> This is configurable via the property [`DisableTransitiveProjectReferences`](https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props#disabletransitiveprojectreferences), if it's causing you problems.

Yes it is, but it will not completely solve the problem, because if Namespace.dll is directly referenced, then DisableTransitiveProjectReferences will not make any difference.

The real root cause is rather that there is - with the new SDK based format - an "automatic" using added for the parent namespace of `Namespace.NastyUsingsExample.Program`.

**Comment by CyrusNajmabadi** [comment] 2023-02-22 17:24
> I expect that Namespace.Core.MyType is used here, as I have an explicit using for the Namespace.Core namespace, yet the Namespace.MyType will be used, because my Program class is also in the same Namespace namespace.

> Or at least, I would expect an error, if the type is ambiguous. E.g.:
Error CS0104 'MyType' is an ambiguous reference between 'Namespace' and 'Namespace.Core'

This is by design.  We look up in the containing namespace first before looking through usings in the outer namespace.  You can fix this in a couple of ways:

1. you can move the using-statement inside the namespace.  Now it takes precedence.
2. You can use a using-alias to give a different name to the particular type.

**Comment by CyrusNajmabadi** [comment] 2023-02-22 17:24
Closing as by design as the compiler is workign exactly as the language is specified.  If you would like a language change, those go to dotnet/csharplang.

**Closed by CyrusNajmabadi** 2023-02-22 17:24 UTC

**Comment by gaborposz** [comment] 2023-02-23 10:09
@CyrusNajmabadi: I understand that it can be fixed easily, but as I wrote, we are migrating from the old csproj format to the new [SDK based format](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview), and this behavior has clearly changed with it: With the old format the types were not looked up in the containing namespaces!

If it's really the C# language, then why has it changed with the csproj format? Is the new csproj format implicitly changes the C# language version?

**Comment by CyrusNajmabadi** [comment] 2023-02-23 13:40
> and this behavior has clearly changed with it:

These lookup rules have not changed.
