### ISSUE TITLE
Bug in test runner for buildandtest

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#10878] opened 2016-04-26 04:34 UTC
![image](https://cloud.githubusercontent.com/assets/3804346/14807052/606bee8e-0b2d-11e6-9a51-541c76cd8afa.png)

**Comment by gafter** [comment] 2016-04-26 04:34
@jaredpar I think this might be yours?

**Comment by jaredpar** [comment] 2016-04-26 05:45
Looks like a duplicate of #10718 

https://github.com/dotnet/roslyn/issues/10718

**Closed by jaredpar** 2016-04-26 05:45 UTC
Labels: Area-Compilers
