### ISSUE TITLE
Completion for enums doesn't work anymore

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#15186] opened 2016-11-12 00:11 UTC
In the following code typing a space after typing ```=``` or ```case``` in locations indicated by ```$``` should preselect ```Foo``` but it doesn't.

```C#
    enum Foo { A,B,C }

    class Program
    {
        static void Main(string[] args)
        {
            Foo f =$
            switch (f)
            {
                case$
            }

        }
    }
```

VS build d15rel/15.0.25909.2

**Comment by Pilchie** [comment] 2016-11-14 23:54
Duplicate of https://github.com/dotnet/roslyn/issues/14813

**Closed by Pilchie** 2016-11-14 23:54 UTC
Labels: Area-IDE, Resolution-Duplicate
