### ISSUE TITLE
Spurious CS8620 with enum and default method parameter

### ISSUE THREAD

**Issue by HolyPrapor** [dotnet/roslyn#52655] opened 2021-04-15 09:10 UTC
**Version Used**: 
dotnet: 5.0.202
Nullables are enabled

**Steps to Reproduce**:

```
public enum TestEnum
{
    First,
    Second,
    Third
}

public void MethodWithDefaultParameter(TestEnum? parameter = TestEnum.Second)
{
    
}
```

**Error**:
```
[CS8620] Argument of type 'int' cannot be used for parameter 'parameter' of type 'TestEnum?' in 'void MethodWithDefaultParameter(TestEnum? parameter = 1)' due to differences in the nullability of reference types.
```

**Expected Behavior**:
This used to compile without error, so I would expect it to continue to.

**Actual Behavior**:
Fails with the error above.

**Comment by Youssef1313** [comment] 2021-04-15 10:16
Duplicate of https://github.com/dotnet/roslyn/issues/51622 which was fixed in https://github.com/dotnet/roslyn/pull/51631.

**Closed** 2021-04-15 11:53 UTC
Labels: Area-Compilers, untriaged
