### ISSUE TITLE
EE - Incorrect evaluation of expression involving struct with enum property

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#3614] opened 2015-06-22 10:30 UTC
Please see http://screencast.com/t/PmT2RUaFzf
```IsF1Set(...)``` call is evaluated in Watch window to false - it should be evaluated to true.
Calling ```(s.Flags & F.F1) == F.F1``` gives proper results. Switching ```S``` to be class also fixes issue. I am using RC bits.

Here is relevant repro code:
```
using System;

namespace IncorrectEvaluation 
{
    class Program 
    {
        static void Main(string[] args) 
        {
            var s = new S() { Flags = F.F1 };
            if(IsF1Set(s)) 
            {

            }
        }

        private static bool IsF1Set(S s) 
        {
            return (s.Flags & F.F1) == F.F1;
        }
    }

    [Flags]
    enum F 
    {
        None = 0,
        F1 = 1,
        F2 = 2,
    }

    struct S 
    {
        public F Flags { get; set; }
    }
}
```

**Comment by Przemyslaw-W** [comment] 2015-07-03 10:02
FYI - still reproducible with 14.0.23023.0 D14REL bits

**Comment by Przemyslaw-W** [comment] 2015-07-14 09:25
FYI - still reproducible with 14.0.23103.0 D14REL bits

**Comment by KevinH-MS** [comment] 2015-10-05 20:18
@pnelsonmsft the IL generated by the EE looks sane:
```
.method assembly hidebysig specialname static 
        bool  '<>m0'(string[] args) cil managed
{
  // Code size       7 (0x7)
  .maxstack  1
  .locals init (valuetype [CSConsoleApplication]IncorrectEvaluation.S V_0,
           valuetype [CSConsoleApplication]IncorrectEvaluation.S V_1,
           bool V_2)
  IL_0000:  ldloc.0
  IL_0001:  call       bool [CSConsoleApplication]IncorrectEvaluation.Program::IsF1Set(valuetype [CSConsoleApplication]IncorrectEvaluation.S)
  IL_0006:  ret
} // end of method '<>x'::'<>m0'
```
Are you investigating a possible issue in VIL?

**Comment by KevinH-MS** [comment] 2015-10-06 03:44
If I add a Debug.WriteLine to IsF1Set, the value seems unitialized (large, positive integer).

**Comment by KevinH-MS** [comment] 2015-10-07 19:57
The issue is in the core debugger and they have a fix that is being tested.  Moving to Milestone 1.2 to verify/close.

**Comment by ManishJayaswal** [comment] 2015-10-07 21:21
This is a dupe of internal debugger bug 151194

**Closed by ManishJayaswal** 2015-10-07 21:21 UTC
Labels: Area-Interactive, Interactive-Debugging
