### ISSUE TITLE
Edit.Duplicate command does not insert trailing newline between original and duplicated code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73891] opened 2024-06-07 12:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-behavior-of-the-EditDuplicate/10677677)._

---
[severity:It bothers me. A fix would be nice]
When using the `Edit.Duplicate` command keyboard shortcut, there is no newline after the original code scope.
This happens when you try to duplicate more than one line of code.

The following attachment demonstrates the essence of the problem:

![B962a1026efae4a958c006496dc1500ed638532946964522618_vs-duplicate-bug](https://github.com/dotnet/roslyn/assets/1408396/2431f7a5-7fff-4a7e-b8a8-a9185b624e6e)

---
#### Feedback Bot on 6/6/2024, 09:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2024-06-07 12:52
This is a case where the command did exactly what it said it would do, but not what the user wanted. The selection did not contain a newline after `}` or a newline before `for`, so when the code was duplicated it put those two tokens on the same line.

**Comment by sharwell** [comment] 2024-06-07 17:15
I think it's reasonable to assume that if the last selected line is a non-empty line that is fully selected except for the trailing newline, the duplicated code should be placed on the line after it.

**Comment by mstepanov214** [comment] 2024-06-08 08:50
@sharwell
After some thought, I agree with this statement:
> This is a case where the command did exactly what it said it would do

The command works according to its name. Therefore, I believe that I have not defined the problem quite correctly.

I use the `Edit.Duplicate` command as an analog to the `editor.action.copyLinesDownAction` from VS Code. It's not exactly the same thing. Perhaps it would be better to suggest implementing another command with the required functionality. I don't know.

**Comment by ToddGrun** [comment] 2024-06-12 22:23
This is implemented by vs-platform in their DuplicateSelectionCommandHandler and the corresponding implementation in EditorOperations.DuplicateSelection. It does feel like there is some room for improvement here. @olegtk -- Do you know if this is a known issue or whether we should create a bug?

**Comment by olegtk** [comment] 2024-06-12 23:46
It's actually by design and VS Code behaves the same way (although I don't remember why).
You are supposed to select the lines including line ending like this, then it would be duplicated as you expect.

![Image](https://github.com/dotnet/roslyn/assets/27849/b76cc918-aa12-4dad-9ce0-1d141e627be4)

I'll reactivate the original ticket and move it to the Editor to continue the discussion, you can close this issue now.

**Closed** 2024-06-12 23:49 UTC
Labels: Area-IDE
