### ISSUE TITLE
Range indexer does not show usages of the underlying method.

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#51443] opened 2021-02-24 11:05 UTC
**Version Used**:  VS16.8.3 / .net 5 compiler

**Steps to Reproduce**:

Add the following code:

```cs
var substring = "12345"[1..3];
var subarray = new[] { 1, 2, 3, 4, 5 }[1..3];
```

Try to use the "Find all References" feature to find usages of `string.Substring()` / `RuntimeHelpers.GetSubArray()`.

**Expected Behavior**:

Finding usages of the underlying methods should show the lines that use the range indexer.

**Actual Behavior**:

Usages are not shown.

**Comment by jinujoseph** [comment] 2021-02-24 20:32
Duplicate of #41310

**Closed by jinujoseph** 2021-02-24 20:32 UTC
Labels: Area-IDE, Bug, New Language Feature - Range
