### ISSUE TITLE
Record struct initialization behavior differs from record classes

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#68126] opened 2023-05-06 21:09 UTC
App:

```csharp
ScrollData one = new(Direction.LeftToRight);
ScrollData two = new();
ScrollData three = new(Direction.RightToLeft);

Console.WriteLine(one);
Console.WriteLine(two);
Console.WriteLine(three);


public record struct ScrollData(Direction Direction = Direction.RightToLeft, bool CanReset = true);

public enum Direction
{
    RightToLeft,
    LeftToRight
}
```

Result:

```
ScrollData { Direction = LeftToRight, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = False }
ScrollData { Direction = RightToLeft, CanReset = True }
```

I'm specifically wondering/unsure of why `CanReset = False` in the second line. I would expect it to be `true`, like the other two lines.

If I change to class structs, I get the expected behavior.

```
ScrollData { Direction = LeftToRight, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = True }
ScrollData { Direction = RightToLeft, CanReset = True }
```

Am I missing something about the way record structs (or structs in general) work? I see the same behavior with .NET 7 and 8 (using the .NET 8 SDK). I didn't try with .NET 6.

**Comment by cston** [comment] 2023-05-07 01:15
Duplicate of https://github.com/dotnet/roslyn/issues/68125?

**Closed** 2023-05-09 05:34 UTC
Labels: Area-Compilers, untriaged
