### ISSUE TITLE
IDE0009: Add 'this' or 'Me' qualification fires on object initializer.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#23381] opened 2017-11-26 23:55 UTC
**Version Used**: 
VS 2017 15.5 P4

**Steps to Reproduce**:

1. Enable the option to qualify field references with `this`. 
2. Paste this code:
```C#
class C
{
    void M()
    {
        new C { P = 42 };
    }

    int P;
}
``` 

**Expected Behavior**:
No diagnostic.

**Actual Behavior**:
A diagnostic is offered, and applying the fix breaks the code.

**Comment by Pilchie** [comment] 2017-11-27 16:02
Dupe of https://github.com/dotnet/roslyn/issues/22776...

**Comment by jinujoseph** [comment] 2017-11-27 18:01
closing as dupe of #22776

**Closed by jinujoseph** 2017-11-27 18:01 UTC
Labels: Area-IDE, Bug
