### ISSUE TITLE
Trying to download preview version of packages from MS public NuGet feed is returning ERROR 403: Time-Limited URL validation failed

### ISSUE THREAD

**Issue by iXab3r** [dotnet/roslyn#71448] opened 2024-01-02 21:24 UTC
**.NET 7/8 CLI (same issue from VS/Rider)**
In my project, I'd want to use preview versions of some of **Microsoft.CodeAnalysis** packages.
[README.md](https://github.com/dotnet/roslyn/blob/main/README.md) lists multiple feeds. one of which hosts these packages (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json).

**Problem:**
Listing packages from this repository works just fine, new version is shown in packages list, etc. The problem occurs when cli/ide tries to **download** **nupkg** file during restoration step.
Here is the error which is shown in IDE:
`Response status code does not indicate success: 403 (Forbidden).
Failed to download package 'Microsoft.CodeAnalysis.CSharp.Workspaces.4.9.0-3.23629.3' from 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.codeanalysis.csharp.workspaces/4.9.0-3.23629.3/microsoft.codeanalysis.csharp.workspaces.4.9.0-3.23629.3.nupkg`

Trying to manually navigate to [aforementioned link](https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.codeanalysis.csharp.workspaces/4.9.0-3.23629.3/microsoft.codeanalysis.csharp.workspaces.4.9.0-3.23629.3.nupkg) shows
`ERROR 403: Time-Limited URL validation failed`

Is there some additional authentication step needed to get access to preview versions of packages? I've gone through previous issues and it seems that there were some infrastructure updates recently, but, mid-december, packages were still available https://github.com/dotnet/roslyn/issues/71226

**Comment by sharwell** [comment] 2024-01-02 21:28
Duplicate of #71447

**Closed by sharwell** 2024-01-02 21:28 UTC
Labels: Area-Infrastructure, untriaged
