### ISSUE TITLE
CodeStyle Tools Options window : Make preview window resizable

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#13575] opened 2016-09-02 21:27 UTC
make it resizable and also choose a better default size

**Comment by Pilchie** [comment] 2017-01-19 01:17
Apparently we didn't catch that #15685 is a dupe of this.  Closing this instead, since the PR at https://github.com/dotnet/roslyn/pull/16557 references #15685.

**Closed by Pilchie** 2017-01-19 01:17 UTC
Labels: Area-IDE, Bug
