### ISSUE TITLE
Indentation is not enforced for collection initializers with .editorconfig

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#46667] opened 2020-08-10 14:33 UTC
My `.editorconfig` file has:

```
[*.cs]
dotnet_diagnostic.IDE0055.severity = warning
# 4-space indentation
indent_style = space
indent_size = 4
```

Yet this `.cs` file code does not produce a warning:

```
            var testObj = new List<string> {
    "Foo",
    "Bar"
            };
```

**Comment by sharwell** [comment] 2020-08-10 14:35
Duplicate of #8269

**Closed by sharwell** 2020-08-10 14:35 UTC
