### ISSUE TITLE
Link to download PDF on wiki is dead

### ISSUE THREAD

**Issue by renzet** [dotnet/roslyn#28521] opened 2018-07-13 18:34 UTC
On the wiki page [Roslyn Overview](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview) the link to download the page as PDF leads to [codeplex](https://www.codeplex.com/Download?ProjectName=roslyn&DownloadId=822125) and is no longer working.

**Comment by jinujoseph** [comment] 2018-07-17 16:21
to be duped

**Comment by sharwell** [comment] 2018-07-17 16:22
Duplicate of #25989

**Closed by sharwell** 2018-07-17 16:22 UTC
Labels: Documentation
