### ISSUE TITLE
C# Interactive. #reset doesn't leave an empty editor line after use

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#4368] opened 2015-08-05 23:54 UTC
Using #reset to clear the reset the execution environment seems to keep the current input line after executing.

![image](https://cloud.githubusercontent.com/assets/10537189/9100597/bb2bea2a-3b91-11e5-940d-c5805b882996.png)

Run the command and it outputs the following:
![image](https://cloud.githubusercontent.com/assets/10537189/9100614/f050128a-3b91-11e5-8cfd-6420434bc0bb.png)

It appears to keep the #reset and the line break used to run the command. It continues to expand by an additional line each time you hit enter.

![image](https://cloud.githubusercontent.com/assets/10537189/9100629/214ef374-3b92-11e5-9111-d7b48423320c.png)

I would expect it to leave an empty input line after execution like the rest of the REPL commands.

**Comment by ManishJayaswal** [comment] 2015-08-14 00:10
this is a dupe of #4121 which has been fixed.

**Closed by ManishJayaswal** 2015-08-14 00:10 UTC
Labels: Area-Interactive, Bug, Interactive-Scripting
