### ISSUE TITLE
C# compiler should emit CS0161 for expression-bodied async iterator methods

### ISSUE THREAD

**Issue by Soothsilver** [dotnet/roslyn#38366] opened 2019-08-29 07:36 UTC
**Version Used**: csc 3.3.0-beta3-19407-03 (d961190a)

**Steps to Reproduce**:

```csharp
public static async System.Collections.Generic.IAsyncEnumerable<int> GenerateSequence() 
     => await Task.FromResult(0);
```

**Expected Behavior**:
A compiler error message along the lines of "GenerateSequence(): not all code paths return a value"

**Actual Behavior**:
Compiler error CS7038 Failed to emit module '{0}'.

**Comment by RikkiGibson** [comment] 2019-08-29 17:04
I think this is a duplicate of #38201.

**Closed** 2019-09-04 20:56 UTC
Labels: Area-Compilers, New Feature - Async Streams, Resolution-Duplicate
