### ISSUE TITLE
OpenSourceDebug - wrong assemblies loaded

### ISSUE THREAD

**Issue by christopherpaul** [dotnet/roslyn#1781] opened 2015-04-03 17:17 UTC
Following on from #928.

When I debug the OpenSourceDebug project, the original compiler assemblies are loaded instead of the ones from my build.

These are the steps I went through:
* I started with an Azure VS2015 CTP6 VM
* Installed the SDK (& opened VS to set up license)
* Cloned Roslyn repo (master, commit 121900f9)
* Restored nuget packages for RoslynLight.sln (command line)
* Build & test (command line, as per https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging)
* Opened RoslynLight.sln in VS
* Set OpenSourceDebug as the startup project
* Build all
* Debug (F5)
* In the under-debug VS instance, created a new C# command-line project
* At this point, the debugger popped up this dialog:
![image](https://cloud.githubusercontent.com/assets/6624896/6985527/5fb7f81c-da2c-11e4-9399-0df8eda65ed7.png)
* In the debugger's Modules window, observed the status of the Roslyn assemblies:
![image](https://cloud.githubusercontent.com/assets/6624896/6985555/b4d14268-da2c-11e4-9e61-b4f7eeb20ef0.png)

Note that the Roslyn assemblies are showing as having loaded from the installed VS2015 location, so I'm not actually debugging the code from my build.

**Comment by romanov** [comment] 2015-04-04 06:37
https://github.com/dotnet/roslyn/issues/1041 ?

**Comment by christopherpaul** [comment] 2015-04-04 11:38
@romanov Yes, I saw that issue too, but my assumption was that all the compiler/code analysis assemblies would lie below the "Workspaces layer" and should therefore be deployable and debuggable in the Roslyn hive. So I *think* this is a separate issue.

**Comment by jasonmalinowski** [comment] 2015-04-06 20:22
It might still be related, it's hard to say. It's not clear to me if issue #1041 was specifically about a Workspace change being undeployable, or more generally that all ability to make changes is broken. :-/

**Comment by petr-k** [comment] 2015-05-10 12:26
@jaredpar If that's the unfortunate case, is there an *unsupported* way of doing this?

**Comment by jaredpar** [comment] 2015-05-11 15:00
Sorry I've let this issue languish but I've been heads down on RTM issues for the last month or so.  I set aside some time to take a look at it early this week.

**Comment by alexsorokoletov** [comment] 2015-05-15 05:40
Thank you!

**Comment by jaredpar** [comment] 2015-05-20 15:45
Some updates ...

The OpenSourceDebug project essentially works by doing the following:

1. Build the workspaces layer and below with the version number 42.42.42.42. 
2. Copy all of the DLLs in the workspace layer into a location under `%LOCALAPPDATA%`
3. Insert code base and version redirects into devenv.exe.config for the Roslyn hive to get VS to load those binaries instead of the ones in the VS install directory. 

@jasonmalinowski, @KevinRansom and I spent a couple hours looking into why this wasn't working yesterday.  The root cause is we aren't inserting the correct version redirects.  Hence at F5 time VS is still looking for binaries with the version 1.0.0.0.  Fixing this is non-trivial because we are competing against other redirections of the same assembly.  We generally worked out how to fix this but this caused us to realize there is another issue here. 

Several of our DLLs in the workspace layer have `InternalsVisibleTo` for DLLs in the Visual Studio layer.  While we've been careful about changing any public contracts in the workspaces layer, we have freely modified our internal contracts.  This has resulted in some breaks between the code base at master and code base shipped in VS 2015RC.  In particular we deleted a few types that the VS layer was depending on.  Hence even if we fix the above problem the solution won't be consumable by anyone running the VS 2015RC.

As such we've decided to move this issue out past the 1.0 release.  After that our code base should be in sync and fixing this will provide value.  At the same time we can start working on a more stable, and full F5 experience.

**Comment by christopherpaul** [comment] 2015-05-21 17:42
@jaredpar Thanks for the update.

**Comment by alexsorokoletov** [comment] 2015-05-22 09:39
@jaredpar I tried doing these redirects on my own (back there, not with current master) and it was quite hard. I had to sit with reflector and xml editor and write each and every redirect on my own.
Is there a ready working "redirects" template?

**Comment by diryboy** [comment] 2015-07-31 07:28
Same here with VS2015 Community RTM on Win8.1 x64. Is milestone 1.1 means that this issue is expected to be fixed on VS2015 Update 1?

**Comment by lorcanmooney** [comment] 2015-09-30 20:13
Has any progress been made on this? Is it still planned for 1.1?  
There are a couple of up-for-grabs issues I'd like to try my hand at, but without the instant gratification of seeing my changes in VS it's hard to get motivated :-)

**Comment by jasonmalinowski** [comment] 2015-09-30 20:21
Yep, it's still planned for 1.1. The work being pursued though isn't an improvement on the Roslyn side as much as it's increasing some flexibility in the VS extension loading to make this work more smoothly. That's why you're not really seeing any progress here -- the work is being done by another team in the core VS codebase.

**Comment by lorcanmooney** [comment] 2015-09-30 20:45
Thanks for the clarification. I'm looking forward to playing with it!

**Comment by ManishJayaswal** [comment] 2015-10-28 06:02
Assigning to @jasonmalinowski  as he is verifying the fix to make sure this works.

**Comment by davkean** [comment] 2015-11-20 19:07
@jasonmalinowski Can we mark this as done?

**Comment by filipw** [comment] 2015-11-20 19:59
meaning it works now in the latest source?

**Comment by jasonmalinowski** [comment] 2015-11-20 20:06
Well, the latest source in master has been updated to deal with this, but it requires support from Visual Studio Update 1 which isn't shipping until the 30th. @davkean, I'd recommend we leave it active until then so it's not confusing for people that it's closed but not something they can use.

**Comment by jasonmalinowski** [comment] 2015-11-30 18:30
All the work has been merged into Update 1, and Update 1 is releasing today. At this point this work is now complete. For all those who wanted to try making changes and seeing them in Visual Studio, install Update 1, sync to the latest in master, and give it a shot!

**Closed by jasonmalinowski** 2015-11-30 18:30 UTC
Labels: Area-Infrastructure, Interactive-Debugging

**Comment by filipw** [comment] 2015-11-30 18:45
excellent!

**Comment by alexsorokoletov** [comment] 2015-12-04 17:31
finally! :fireworks:
