### ISSUE TITLE
Make AdHoc workspaces load without having to install other packages Microsoft.CodeAnalysis.Elfie and Esent.Interop

### ISSUE THREAD

**Issue by m0sa** [dotnet/roslyn#15603] opened 2016-11-30 05:47 UTC
**Version Used**: 
Roslyn - 2.0.0-rc
Composition 1.0.27

**Steps to Reproduce**:

1. Create new project
2. Install-Package Microsoft.CodeAnalysis.CSharp.Workspaces -Version 2.0.0-rc 
3. call `new AdhocWorkspace(DesktopMefHostServices.DefaultServices);`

**Expected Behavior**:
The Workspace gets created with successfully loaded MEF parts from available assemblies.

**Actual Behavior**:

The WithAssemblies call [expects all](https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Composition.TypedParts/src/System/Composition/Hosting/ContainerConfiguration.cs#L203) the exported types to [load successfully](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.gettypes(v=vs.110).aspx#Anchor_1), even those that require `Microsoft.CodeAnalysis.Elfie` and `Esent.Interop`, so we get this exception:

```
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.RuntimeAssembly.get_DefinedTypes()
at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
```

the offending loads show up in fusion log:

```
Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  ....
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.CodeAnalysis.Elfie, Version=0.10.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///....
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

=== Pre-bind state information ===
LOG: DisplayName = Esent.Interop, Version=1.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///....
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
```

**Workaround**:

Create container configuration with parts that actually load, [e.g.](https://github.com/StackExchange/StackExchange.Precompilation/blob/dev/roslyn-v2/StackExchange.Precompilation.Build/Compilation.cs#L143):

```
var parts = new List<Type>();
foreach (var a in assemblies)
{
    try
    {
        parts.AddRange(Assembly.Load(a).GetTypes());
    }
    catch (ReflectionTypeLoadException thatsWhyWeCantHaveNiceThings)
    {
        parts.AddRange(thatsWhyWeCantHaveNiceThings.Types);
    }
}
parts.RemoveAll(x => x == null);

var container = new ContainerConfiguration().WithParts(parts).CreateContainer();
var host = MefHostServices.Create(container);
var workspace = new AdhocWorkspace(host);
```

**Comment by CyrusNajmabadi** [comment] 2016-12-16 21:55
@tannergooding Did you fix this through https://github.com/dotnet/roslyn/pull/15870 ?

**Comment by Pilchie** [comment] 2016-12-16 23:00
No.  Now .NET Core projects will get the workspace which will explode during compilation because Esent and Elfie aren't present.

**Comment by tannergooding** [comment] 2016-12-17 03:00
.NET Core will need to have a different fix, since Esent and Elfie are Desktop only at the time.

**Comment by Pilchie** [comment] 2017-01-19 22:25
Moving to @mattwar we'll have to think about this for .NET Core.

**Comment by mattwar** [comment] 2017-01-19 22:48
Why is this code using the desktop host services?  AdHocWorkspace works just fine without needing to specify any host services. The workspaces desktop dll depends on esent and elfie.

**Comment by Pilchie** [comment] 2017-01-19 22:56
Are those services actually in the desktop dll, such that AdHocWorkspace works fine on .NET Core?  That would be great.

**Comment by mattwar** [comment] 2017-02-16 23:21
You have to have the desktop dll to even reference the DesktopMefHostServices type.  You do not need DesktopMefHostServices to use AdHocWorkspace, however.  But if you do reference desktop dll then you have taken dependency on esent and elfie. 

I do not entirely understand why these dependencies are needed here in the desktop dll.  I believe they used to be only in VS layer, but HeeJae moved them here so he could use them in OOP work without having to invent a new project to put them in.

**Comment by mattwar** [comment] 2017-02-28 21:46
I think the problem is that the workspace package includes the desktop dll and the dependency on Elfie and Esent.

**Comment by CyrusNajmabadi** [comment] 2020-03-15 01:36
We moved Elfie down tot he EditorFeatures layer in https://github.com/dotnet/roslyn/pull/19109 and https://github.com/dotnet/roslyn/pull/18034

**Closed by CyrusNajmabadi** 2020-03-15 01:36 UTC
Labels: Area-IDE, Bug
