### ISSUE TITLE
C# Dictionary key initializer statement can throw a surprising KeyNotFoundException (by omitting 'new T')

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/roslyn#73177] opened 2024-04-22 16:14 UTC
**Version Used**: 

I think I'm using C# version 10? In VS 2022.
When I look at build output I see

`27>    Microsoft (R) Visual C# Compiler version 4.9.0-3.24121.1 (a98c90d5)`

**Steps to Reproduce**:

Compile this code in a C# console app targeting .net 6 or .net 8 (happens for either).

```csharp
 using Xunit;

Console.WriteLine("Hello, World!");
await new Foo().QuorumIsLostWhenImUnhealthyAndAllTheHealthyStatusesAreStale();

class Foo
{

    /// <summary>
    /// This is a safeguard against the health checks failing on the other nodes in the cluster
    /// and making their last health status blob 'stale' when they fail to update it.
    /// </summary>
    [Fact]
    public async Task QuorumIsLostWhenImUnhealthyAndAllTheHealthyStatusesAreStale()
    {
        var testStartTime = DateTimeOffset.Now;
        WhenItIsAThreeNodeCluster();
        WhenHealthStatusIs(new Dictionary<int, Health>
        {
            [0] = new Health
            {
                status = Health.HealthStatus.Healthy,
                timeOfLastHealthCheck = testStartTime.Subtract(TimeSpan.FromMinutes(5)), // Stale
                timeOfLastReboot = null
            },
            [1] = new Health
            {
                status = Health.HealthStatus.Healthy,
                timeOfLastHealthCheck = testStartTime.Subtract(TimeSpan.FromMinutes(5)), // Stale
                timeOfLastReboot = null
            },
            [2] =
                {
                    status = Health.HealthStatus.Healthy,
                    timeOfLastHealthCheck = testStartTime.Subtract(TimeSpan.FromMinutes(5)), // Stale
                    timeOfLastReboot = null
                }
        });
    }

    private void WhenHealthStatusIs(Dictionary<int, Health> dictionary)
    {
    }

    private void WhenItIsAThreeNodeCluster()
    {
    }
}

public interface IConfig
{
}

public class Health : IConfig
{
    public HealthStatus status;

    public ClusterLeaderHealthCheckStatus clusterLeaderHealthCheckStatus;

    public DateTimeOffset? timeOfLastHealthCheck;

    public DateTimeOffset? timeOfLastReboot;

    public enum HealthStatus
    {
        Healthy,
        Unhealthy
    }

    public enum ClusterLeaderHealthCheckStatus
    {
        Active,
        Inactive
    }

    public override string ToString()
        => $"status : {status}, clusterLeaderHealthCheckStatus : {clusterLeaderHealthCheckStatus}, Time of last health check: {timeOfLastHealthCheck}, Time of last reboot: {timeOfLastReboot}";
}
```

**Diagnostic Id**:

N/A

**Expected Behavior**:

Expected: does not throw. [Or possibly: does not compile, since that's better than a surprising runtime error, in my opinion]

Reason: I expect that the app shouldn't actually need to *read* the dictionary key 2, in order to run an initializer statement, which will *write* to the key 2.
And if the implementation for some reason _did_ need to read the value, then it should be doing so in a safe way that handles the possibility that item 2 is not already in the collection, and does not throw!

**Actual Behavior**:

Compiles, runs, then throws an exception.

Message: 
  System.Collections.Generic.KeyNotFoundException : The given key '2' was not present in the dictionary.

Stack Trace: 
  Dictionary`2.get_Item(TKey key)
  TestClass.TestMethod() line 301 // the line number of 'new Dictionary...'

**Comment by CyrusNajmabadi** [comment] 2024-04-22 16:21
Closing out.  This is exactly the expected behavior of the alnguage as specified.  `[0] = new Health` means "instantiate new value and assign into the 0'th index of teh destination".  Whereas `[2] = {` means "grab the value at the 2nd index, and then assign into it the specified property/value pairs within the initializer".

THese are two different sets of semantic intentionally available due to how different types of initialization apis work.

**Closed by CyrusNajmabadi** 2024-04-22 16:21 UTC
Labels: Area-Compilers, untriaged

**Comment by TimLovellSmith** [comment] 2024-04-22 16:30
@CyrusNajmabadi 
How is this actually a good feature of the language though?

It seems very unlikely to me that I'm going to write

```
= (new dictionary) {
   ["magic"] = {
     prop1 = val1;
   } 
}
```

and expect that the dictionary already contained key "magic", unless its a **very special dictionary class indeed**, as opposed to e.g. any of the commonly used ones from the framework.

**Comment by CyrusNajmabadi** [comment] 2024-04-22 16:38
> How is this actually a good feature of the language though?

It allows for two extremely common forms of initialization. The form where the client is expected to instantiate the values the final object holds onto, and the form where the final object instantiates them and wants the client to fill them in. :)

Both are used throughout the ecosystem.

> It seems very unlikely to me that I'm going to write

We do this all the time in roslyn.  As an example, our entire test suite is written that way.  :)

>  unless its a very special dictionary class indeed,

There are many cases of this.  So it's it's not 'very special'. It's just a domain specific choice that many APIs choose to use.
