### ISSUE TITLE
BasicRazor and CSharpRazor fail in Standalone B2B Dogfood runs

### ISSUE THREAD

**Issue by v-codeel** [dotnet/roslyn#6165] opened 2015-10-19 23:07 UTC
When trying to create an ASP.NET Web Application, the project creation fails, and an exception is thrown.

When performing the steps manually, I noticed that the option to add Application Insights was missing.

This issue seems to be only on the build-to-build runs.

Here's the stack trace:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ApplicationInsights.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    at Microsoft.VisualStudio.Web.Project.OneASPNETModel.get_IsApplicationInsightsEnabled()
    at Microsoft.VisualStudio.Web.Project.OneASPNETModel.GetRuleOptionsFromSettings()
    at Microsoft.VisualStudio.Web.Project.OneASPNETModel.StartCollectionPhase()
    at Microsoft.VisualStudio.Web.Project.OneASPNETModel.CreateProject(Solution solution)
    at Microsoft.Test.Apex.VisualStudio.Web.Project.CreateWebProjectTestService.CreateWebProject(IServiceProvider serviceProvider, Solution solution, NewWebProjectParameters parameters)
    at Microsoft.Test.Apex.VisualStudio.Web.Project.CreateWebProjectTestService.<>c__DisplayClass8_0.<CreateProject>b__0()
    --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Delegate.DynamicInvokeImpl(Object[] args)
    at System.Delegate.DynamicInvoke(Object[] args)
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values)
    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by ManishJayaswal** [comment] 2015-10-20 06:35
Dupe of internal bug 155838

**Closed by ManishJayaswal** 2015-10-20 06:35 UTC
