### ISSUE TITLE
Remove JTF.Run for razor mapping

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#47909] opened 2020-09-21 20:25 UTC
Once https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1216657 is fixed, we should remove the places where we added JTF.Run in https://github.com/dotnet/roslyn/pull/47104#discussion_r491255962

**Comment by sharwell** [comment] 2020-09-24 08:33
I'm not convinced the root cause analysis here is correct. Changing the code from a direct call to running inside a `Task.Run` (which the code did even before #47104) is a standard way to ensure `ConfigureAwait(true)` doesn't produce the described behavior.

**Comment by dibarbet** [comment] 2020-09-24 17:56
@sharwell Task.Run *does* work, as well as JTF.Run.  From discussing with Jason we decided to switch both to JTF.Run to be safe in case anyone else was trying to switch to the main thread underneath us.

**Comment by sharwell** [comment] 2020-09-24 17:57
If that's the case, can we close this issue as By Design (an alternative was available, but intentionally not used)?

**Comment by dibarbet** [comment] 2020-09-24 17:59
This issue is tracking us switching to just WaitAndGetResult without task.run or jtf.run, which should be possible once https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1216657 is fixed

**Comment by sharwell** [comment] 2020-09-24 18:05
LSP is external code which does not adhere to Roslyn's (unique) policy regarding UI thread dependencies. External code is broadly allowed to assume that callers will not use `Task.Result`, so even if there is a point in time where `WaitAndGetResult` works we would not be able to assume it remains true going forward.

**Comment by CyrusNajmabadi** [comment] 2024-11-11 20:09
Closing out as speculative.  if we need to do this assign to dev/milestone for this to be done in.

**Closed** 2024-11-29 07:25 UTC
Labels: Area-IDE, Concept-Continuous Improvement
