### ISSUE TITLE
VB.NET code window doesn't scroll to the handler when selecting a control from the drop-down

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39262] opened 2019-10-14 05:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/21762/vbnet-code-window-doesnt-scroll-to-the-handler-whe.html)._

---
In VS2013, in the VB.NET code window, selecting a control from the controls list drop-down would cause the code window to auto-scroll to the handler for that control, if that control only had one handler.

This behaviour is no longer present in VS2017 RC - you have to select the event from the events drop-down to make the code window scroll.

I've illustrated the problem in the following video:

https://youtu.be/PhGAI_jw9PY

I've also attached a test case.

As I explain in the video, when a control has multiple handlers, fair enough - it wouldn't know which section of the code to jump to.  But for buttons there's usually only one, and for other controls too - combo boxes for instance often only have a SelectedIndexChanged event.

It would be great to put the auto-scroll behaviour from VS2013 back in - it's a small thing but makes a significant difference over time.

---
#### Jane Wu [MSFT] on 8/9/2019, 03:17 AM: 

After 90 days of no priority changing activity, we’ve closed this report. We prioritize based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Closing low priority tickets helps us manage our workload and focus on problems that impact most users. If you still face this issue in our latest version, please report it as a new problem.

#### Paul Haffner on 10/9/2019, 03:44 PM: 

<p>How are we meant to vote on this issue if it has been closed? This is a serious question, because the issue I raised, which is admittedly a duplicate of this one, has just been answered with the seemingly ridiculous request that I could come to this issue and vote for it.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2019-10-14 15:59
Related to #31566

**Comment by sharwell** [comment] 2019-10-14 16:00
Related to #37854

**Comment by Alex-van-der-Peet** [comment] 2020-10-22 10:40
As far as I can find out, this has still not been resolved.

**Comment by gh658804** [comment] 2022-01-26 15:49
I came here to post the same thing but i discovered the current, and also [this](https://github.com/dotnet/roslyn/issues/31566) which seems to be a duplicate of the current issue. Nothing yet, in VS2019 at least.

Perhaps those 2 github issues should be merged...

**Comment by CyrusNajmabadi** [comment] 2022-01-26 17:21
this issue is currently on the backlog, meaning we don't have the resources available currently to address this ahead of all the rest of our scheduled work.  We would likely accept a community contribution here though.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:33
Closing as we are unlikely to change these experiences.

**Closed by CyrusNajmabadi** 2024-10-22 19:33 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community
