### ISSUE TITLE
Code Fix Service Gold Bar Error

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54264] opened 2021-06-21 20:34 UTC
![MicrosoftTeams-image](https://user-images.githubusercontent.com/46729679/122824215-3836af00-d295-11eb-98ef-22b29f024003.png)

Stack Trace: 

> System.TypeInitializationException : The type initializer for 'Microsoft.VisualStudio.SDK.Analyzers.VSSDK001DeriveFromAsyncPackageCodeFix' threw an exception. ---> System.FieldAccessException : Attempt by method 'Microsoft.VisualStudio.SDK.Analyzers.VSSDK001DeriveFromAsyncPackageCodeFix..cctor()' to access field 'Microsoft.VisualStudio.SDK.Analyzers.VSSDK001DeriveFromAsyncPackageAnalyzer.Descriptor' failed.
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK001DeriveFromAsyncPackageCodeFix..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK001DeriveFromAsyncPackageCodeFix.get_FixableDiagnosticIds()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetAndTestFixableDiagnosticIds(CodeFixProvider codeFixProvider)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c.<GetFixableDiagnosticIds>b__37_2(CodeFixProvider f)
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location,TKey key,Func`2 valueFactory)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass37_0.<GetFixableDiagnosticIds>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunction[T](IExtensionManager extensionManager,Object extension,Func`1 function,T defaultValue)

**Comment by mikadumont** [comment] 2021-06-21 20:35
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2021-06-21 20:43
@AArnott Do you know where crashes in VSSDK should go?

**Comment by AArnott** [comment] 2021-06-21 22:17
Here: https://github.com/microsoft/VSSDK-Analyzers/issues

This looks like a dupe of https://github.com/microsoft/VSSDK-Analyzers/issues/105 though, so I wonder what version of the analyzers this project was using. Maybe it doesn't have the fix.

**Comment by jinujoseph** [comment] 2021-06-25 00:56
Moved over to https://github.com/microsoft/VSSDK-Analyzers/issues/136

**Closed by jinujoseph** 2021-06-25 00:56 UTC
Labels: Area-Analyzers, untriaged
