### ISSUE TITLE
System.ComponentModel.EditorBrowsableState.Never does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37478] opened 2019-07-25 18:16 UTC
In VB, I write&lt;System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)&gt; above a subroutine or class, but it does not filter out the method/class from the intellisense list.  This does not seem to work in VS2015, 2017, 2019, but it does seem to work in VS2013.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/658751/systemcomponentmodeleditorbrowsablestatenever-does.html
VSTS ticketId: 951442_
_These are the original issue comments:_

Visual Studio Feedback System on 7/24/2019, 02:16 AM (33 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2019-07-25 18:18
I believe this is by design.  These attributes were intended to hide from *external* parties, not from your own code.  We changed teh design based on lots of feedback many years back, and made things consistent between C# and VB.

**Comment by sharwell** [comment] 2019-07-30 23:49
Tentatively marking this as **By Design**. Will update with the team conclusion after design review.

**Comment by ryzngard** [comment] 2019-08-12 22:07
From Design Review: @CyrusNajmabadi  statement is correct, this is intended for external parties. This can be achieved using local functions depending on scenario. If more improvements need to be made, please file a specific request to improve those areas. As of now, this is working as intended.

**Closed by ryzngard** 2019-08-12 22:07 UTC
Labels: Area-IDE, Bug, Developer Community, IDE-IntelliSense, Need Design Review, Resolution-By Design
