### ISSUE TITLE
Analyzer Errors should not be filtered out by /p:WarningLevel=0 when Ruleset Rule is set to Action=Error

### ISSUE THREAD

**Issue by alexander-anderson-salesforce** [dotnet/roslyn#61603] opened 2022-05-31 18:01 UTC
**Version Used**: 
Tried with two versions:
msbuild.exe 15.9.21.664
msbuild.exe 17.0.0.52104

**Steps to Reproduce**:
0. Create a basic template C# project
1. Hook up StyleCop as an Analyzer in your project
2. Configure a rule to report a build error when it is found
3. Create such an error in your code
4. Run msbuild /p:WarningLevel=0

**Expected Behavior**:
Because of setting the Rule to Error, I expected that my build would fail.

**Actual Behavior**:
The analyzer rule is getting suppressed and not reported.

====================
I did some additional investigation to try to understand exactly what is going on, and I'll detail that here:

- StyleCop diagnostics are marked with "WarningLevel=1" regardless of the ruleset settings.
- There's code (but I don't know when it is called in normal compilation) which compares the Diagnostic's warninglevel (in this case 1) to the compiler option's warninglevel (of 0), and if 1 > 0, then it sets the ReportDiagnostic to be ReportDiagnostic.Suppress
- There's directly subsequent code that results in the returned Diagnostic being set to null when we have ReportDiagnostic.Suppress

I used JetBrains dotPeek to dig into the dlls, though since both StyleCop and Roslyn are public in github, that's not strictly necessary.

[Example StyleCop DiagnosticDescriptor, with severity = Warning](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1014OpeningGenericBracketsMustBeSpacedCorrectly.cs#L37) 
[How that is being passed to the AnalysisContext](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1014OpeningGenericBracketsMustBeSpacedCorrectly.cs#L100)
[The FilterDiagnostic method in CSharpCompilationOptions](https://github.com/dotnet/roslyn/blob/df86b32122818d4dd9a7f0f357924e7fbfe66387/src/Compilers/CSharp/Portable/CSharpCompilationOptions.cs#L759)
[The Filter method in CSharpDiagnosticFilter](https://github.com/dotnet/roslyn/blob/abe7bede7b75ca12e828f6db3aa9daf6f54c6f95/src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs#L34)
[Call to GetDiagnosticReport](https://github.com/dotnet/roslyn/blob/abe7bede7b75ca12e828f6db3aa9daf6f54c6f95/src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs#L94)
[Comment calls out to specifically honor the WarningLevel first](https://github.com/dotnet/roslyn/blob/abe7bede7b75ca12e828f6db3aa9daf6f54c6f95/src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs#L175)

The context for why I am looking into this is because my wider team has a build setting of /p:WarningLevel=0 which is preventing my local team projects from having their StyleCop analyzer Errors enforced - and I am trying to investigate why that setting was preventing errors from being reported.

**Comment by sharwell** [comment] 2022-05-31 23:44
I believe this is by design. #22100 ensured that analyzers can be used for warning levels 1-3, but `/warn:0` is a special compiler flag that forces the compiler into "true compiler errors only" mode, which means analyzers cannot run.

**Comment by alexander-anderson-salesforce** [comment] 2022-06-01 18:14
Is there a supported way to

- Hide all warnings from analyzer + compiler
- Show all errors from analyzers

**Comment by alexander-anderson-salesforce** [comment] 2022-06-03 18:39
I've found documentation on WarningLevel specifically calls out that it suppress all Warnings (not Errors).

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings

**Comment by jaredpar** [comment] 2022-08-15 16:50
> Is there a supported way to

Not to my knowledge. Warnings and errors are already over configurable and there is no desire to add yet another configuration setting. Instead it's recommended that the existing knobs be used. 

Closing as the behavior here is by design.

**Closed by jaredpar** 2022-08-15 16:50 UTC
Labels: Area-Compilers, untriaged
