### ISSUE TITLE
Proposal: 'default' operator for structs

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#9040] opened 2016-02-23 09:24 UTC
Maybe it is a good idea if it was able to define a `default` operator for the `default` keyword, at least for structs.

``` C#
public struct Fraction
{
  public double Numerator;
  private double _divisor;
  public double Divisor
  {
    get => _divisor; // #7881
    set => _divisor = (value != default(double)) ? value : throw new ArgumentOutOfRangeException();
   }

  public static Fraction operator default()
  {
    Fraction value;
    value.Numerator = 1;
    value.Divisor = 1;
    }
  public Fraction()
  {
    this = default(Fraction);  // assigns the default to this 'instance'
  }
}
```

**Comment by alrz** [comment] 2016-02-23 09:40
Dupe of #71.

**Comment by DavidArno** [comment] 2016-02-23 09:54
This, hopefully, is fully covered by struct records in C# 7:

```cs
public struct Fraction(double numerator = 1, double divisor = 1);
```

And it will have the advantage of being immutable, unlike your example. As it states in the [Type Design Guidelines, "**DO NOT** define mutable value types"](https://msdn.microsoft.com/en-us/library/ms229031%28v=vs.110%29.aspx).

**Comment by lachbaer** [comment] 2016-02-23 09:59
Ah, I see. The document for record types was 404 last time I checked.

**Comment by gafter** [comment] 2017-03-20 20:19
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Closed by gafter** 2017-03-20 20:19 UTC
Labels: Area-Language Design, Discussion
