### ISSUE TITLE
Parsing Error with XML-Style Comments Inside Triple-Slash Documentation

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/roslyn#60700] opened 2022-04-12 07:30 UTC
VS2022 17.2.0 Preview 2.1

Please let me know if there is a more appropriate place to file this issue or if I'm totally bonkers with this.

XML-style comments inside triple-slash comments seem to parse incorrectly if the comment contains certain combinations of dashes and optionally bracketing whitespace. This can prevent documentation display on hover, in Intellisense, and cause incorrect syntax coloring.

### Repro

Add the following interface to a project:

```   
interface IFoo
{
    /// <summary>
    /// <!---->
    /// Hello, world!
    /// </summary>
    int Bar { get; }
}
```

Change the XML comment line to:

`    /// <!--  -- -->`
No summary on `Bar` hover.

`    /// <!--  - -->`
Summary on `Bar` hover.

`    /// <!----->`
No summary on `Bar` hover. Remaining triple-slash syntax colored as XML-style comment.

`    /// <!------>`
No summary on `Bar` hover. Remaining triple-slash comments colored correctly.

#### Context
I want to make rather robust triple-slash remarks a bit easier to read. Since breaking up triple-slash comments by region doesn't appear supported, I chose XML comments with dashes to box off headings.

**Comment by sharwell** [comment] 2022-04-19 18:57
`--` is not valid inside an XML comment.
https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-comments

> [For compatibility](https://www.w3.org/TR/2006/REC-xml11-20060816/#dt-compat), the string "--" (double-hyphen) must not occur within comments.

**Comment by sharwell** [comment] 2022-04-19 19:42
I know an issue was filed in the past to still show XML comments even when the content is invalid, but I can't seem to find it now.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 05:44
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-25 05:44 UTC
Labels: Question, Area-IDE, Concept-Continuous Improvement
