### ISSUE TITLE
XML docs for properties don't get their implicit "value" parameter added to intellisense

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19973] opened 2017-06-02 02:01 UTC
Properties:

![image](https://cloud.githubusercontent.com/assets/1103906/26707856/0a1065f6-478b-11e7-9e26-b3d18e19c7c4.png)

Methods:

![image](https://cloud.githubusercontent.com/assets/1103906/26707873/30257eca-478b-11e7-81e1-e1d4c93609c9.png)

**Comment by Pilchie** [comment] 2017-06-02 17:27
Does anything look at that xml doc?  I'm pretty sure quick info/sig help wouldn't show it.

**Comment by sharwell** [comment] 2017-06-02 19:04
@Pilchie Additional context:

1. This situation would also impact code within a `<summary>` element.
1. We have IntelliSense support for several XML doc comment features that don't appear in the IDE. An obvious example would be all other items that are already shown in the completion dropdown inside the `<exception>` element.
1. We have an active request to show the information from `<exception>` elements (#1515)

**Comment by sharwell** [comment] 2017-06-02 19:09
I cannot find any indication that `value` would be a parameter that can be referenced in this manner. The main item leading me to this conclusion is the way [`List<T>.Capacity`](https://msdn.microsoft.com/en-us/library/y52x03h2.aspx) is documented: the `value` parameter doesn't appear at all and the exceptions documentation simply refers to "a value".

@EWSoftware I lean towards closing this as "won't fix". Can you confirm that you would not expect to find a `<paramref name="value"/>` construct within the XML documentation for a property?

**Comment by EWSoftware** [comment] 2017-06-02 21:47
@sharwell I've always been of the opinion that `paramref` was for method parameters since it implies there's a matching `param` element.  I've never considered it for the implied `value` within property setters nor have I ever seen it used that way.  The `param` element doesn't show up on properties either and I wouldn't expect it to.  The Sandcastle presentation styles don't care either way since they just apply an italic style to it as part of the general set of inline elements.  However, I don't think it's necessary within IntelliSense.

**Comment by davkean** [comment] 2017-06-02 21:59
I'm 99% sure that this was a supported construct since both NDoc and Sandcastle days.

**Comment by EWSoftware** [comment] 2017-06-02 22:21
Supported, yes, but not by intent more by default due to the way the inline elements are handled when rendered.  No distinction is made for the member they appear on.  I'd question it's use in IntelliSense since there's really no `param` element to reference on a property.  I'd not expect IntelliSense support for `param` on a property for `value` either.

**Comment by sharwell** [comment] 2017-06-02 23:37
@Pilchie @CyrusNajmabadi Based on what I've seen in the past and feedback from @EWSoftware, my current recommendation is to close this issue as "working by design".

**Comment by sharwell** [comment] 2019-06-15 13:26
Tentatively marked as **By Design**. Will update after design review.

**Comment by sharwell** [comment] 2019-07-06 01:58
The design review meeting reached the same conclusion as above.

**Closed by sharwell** 2019-07-06 01:58 UTC
Labels: Area-IDE, Bug, Need Design Review, Resolution-By Design

**Comment by davkean** [comment] 2019-07-08 07:40
This pattern is used throughout the BCL, which is a fairly good indication that it is expected to work:

Here's an example: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.system-collections-ilist-item?view=netframework-4.8.

``` XML
   <member name="P:System.Collections.Generic.List`1.System#Collections#IList#Item(System.Int32)">
      <summary>Gets or sets the element at the specified index.</summary>
      <param name="index">The zero-based index of the element to get or set.</param>
      <returns>The element at the specified index.</returns>
      <exception cref="T:System.ArgumentOutOfRangeException">
              <paramref name="index" /> is not a valid index in the <see cref="T:System.Collections.IList" />.</exception>
      <exception cref="T:System.ArgumentException">The property is set and <paramref name="value" /> is of a type that is not assignable to the <see cref="T:System.Collections.IList" />.</exception>
    </member>
```
Having worked on the BCL for a very long time, we most definitely expected this to work as I've indicated above.
