### ISSUE TITLE
No Intellisense inside nameof when working with generics

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3193] opened 2015-05-30 04:34 UTC
Noticed this today in RC.

Repro:

 1. New ConsoleApplication 
 2. Replace Main with following

```CSharp
public static void Main()
{
    var myList = new List<int>() { 1 };
    var first = myList.First();
    var test = nameof(first.); //<- No Intellisense on this dot
}
```
 3. Observe no Intellisense on `first.` inside of `nameof`

Also occurs in `foreach` loops. (Where I first noticed it)

**Comment by Pilchie** [comment] 2015-05-31 19:39
Not actually generics related.  Dupe of #1663, which is already fixed.

**Closed by Pilchie** 2015-05-31 19:39 UTC
