### ISSUE TITLE
Renaming local variable with "Attribute" suffix inserts another "Attribute" in the name

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#39174] opened 2019-10-09 22:41 UTC
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/66525688-21ddc500-eaab-11e9-8021-34993d1ecfe1.png)

**Steps to Reproduce**:
 
```C#
class C
{
        void F()
        {
            C myAttribute = new C();
        }
}
```

Inline rename `myAttribute`.

**Expected Behavior**:

No `Attribute` duplication.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/41759/66525732-4043c080-eaab-11e9-9a31-afc7b5ee9753.png)

**Comment by RikkiGibson** [comment] 2019-10-10 17:26
dupe of #35253?

**Comment by jinujoseph** [comment] 2019-10-15 19:51
Duplicate of #35253

**Closed by jinujoseph** 2019-10-15 19:51 UTC
Labels: Area-IDE, Resolution-Duplicate
