### ISSUE TITLE
Incorrect suggestion when interpolating ReadOnlySpan<char> in a string.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#43956] opened 2020-05-03 23:54 UTC
If I want to interpolate a `ReadOnlySpan<char>` in a string, I have to call its `ToString()` method. The `ReadOnlySpan<char>` cannot be interpolated directly, or we get an error.
But Visual Studio does not give me the suggestion to call the `ToString()` method. And the problem is that if I add it manually (which gets rid of the error), VS gives me the suggestion to _simplify_ that call (remove `ToString()`) which clearly is incorrect since that would cause an error.

### Screenshots

Here's the code with the error:
![image](https://user-images.githubusercontent.com/1175054/80929113-63430400-8d5e-11ea-8537-9af988dc50a1.png)

Here's the incorrect suggestion given by VS:
![image](https://user-images.githubusercontent.com/1175054/80929119-68a04e80-8d5e-11ea-85c2-2d1b20edd1dd.png)

cc @mavasani

**Comment by CyrusNajmabadi** [comment] 2020-05-04 22:02
Dupe of https://github.com/dotnet/roslyn/issues/42936

**Closed by CyrusNajmabadi** 2020-05-04 22:02 UTC
