### ISSUE TITLE
Endless loop in 'Microsoft.CodeAnalysis.ChildSyntaxList.ItemInternal(SyntaxNode, int)'

### ISSUE THREAD

**Issue by RalfKoban** [dotnet/roslyn#57343] opened 2021-10-23 17:04 UTC
**Version Used**: 3.11.0

**Steps to Reproduce**:
I've written a codefix provider that returns a new document which somehow gets handled.

However - unfortunately - I'm not able to provide a repro, but I don't call `Microsoft.CodeAnalysis.ChildSyntaxList.ItemInternal()` directly inside my code (it seems to get called via `GetDocumentationCommentXml()`).

The codefix provider works on a `DocumentationCommentTriviaSyntax` and is coping with `XmlTextSyntax` elements (replacing them), so it might be that it creates wrong syntax nodes.

**Expected Behavior**:
`Microsoft.CodeAnalysis.ChildSyntaxList.ItemInternal()` quickly returns.

**Actual Behavior**:
The call seems to never return.
There is an endless loop inside the `while(true)` loop when attempting to find a slot.

According to the comment inside that method:
```c#
            // find a slot that contains the node or its parent list (if node is in a list)
            // we will be skipping whole slots here so we will not loop for long
            // the max possible number of slots is 11 (TypeDeclarationSyntax)
            // and typically much less than that
            //
            // at the end of this loop we will have
            // 1) slot index - slotIdx
            // 2) if the slot is a list, node index in the list - idx
            // 3) slot position - position
            while (true)
            {
                greenChild = green.GetSlot(slotIndex);
                if (greenChild != null)
                {
                    int currentOccupancy = Occupancy(greenChild);
                    if (idx < currentOccupancy)
                    {
                        break;
                    }

                    idx -= currentOccupancy;
                    position += greenChild.FullWidth;
                }

                slotIndex++;
            }
``` 
the loop should not take a long time because of the max. possible number of `11`.

However, when I paused in the debugger I saw that the local variable `slotIndex` is already negative.
As it was initially set to zero (`0`), it seems that there was an overflow.

When stepping through the code I saw that `greenChild` is set to `null` (as returned by `green.GetSlot(slotIndex)`), so the condition inside the if block will never be true and the complete while loop will therefore take forever.

**Comment by jcouv** [comment] 2022-05-14 04:52
Re-assigned to load-balance

**Comment by AlekseyTs** [comment] 2022-07-01 13:36
I think the problem is in the user code above https://github.com/dotnet/roslyn/issues/57343#issuecomment-951975628. It creates ```XmlTextSyntax``` node with no tokens, ```tokensForTexts``` is empty at the time. I think this isn't a right thing to do. A node cannot be based on absolutely nothing, it should have at least one token.

**Closed** 2022-07-01 13:37 UTC
Labels: Bug, Area-Compilers

**Comment by RalfKoban** [comment] 2022-07-02 06:27
From an API consumer's point of view I would like to be informed if I make a wrong usage of the API. If it is not allowed to provide no tokens when creating an `XmlTextSyntax`, I - as a proposal - would like to get an exception (such as an `ArgumentException`) thrown that points me on that invalid call so that I can fix it.

Unfortunately, in the current case I'll end in an endless loop later on inside Roslyn and I don't know where/what to fix.

**Comment by CyrusNajmabadi** [comment] 2022-07-02 14:27
The rule of Roslyn is that you must make the same trees that the parser would produce. Any other tree results in undefined behavior. 

Adding all the checks would be an enormous undertaking and would effectively mean duplicating all the behavior of the parser in another location. 

Our advice is thus: if generating an equivalent tree is too much of a burden, don't. Instead just generate the right text and run it through the parser so you get the right result. 

You can also do this like so: `SyntaxFactory.Parse(your constructed node.ToFullString())`
