### ISSUE TITLE
Embedded resource name cannot contain a comma

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#4343] opened 2015-08-05 01:57 UTC
If you have an Embedded Resource in a C# project, and the file name contains a comma, the compiler emits an error that resource visibility must be either 'public' or 'protected'.

I assume that the `/resource:filename[,identifier[,accessibility-modifier]]` argument ([docs](https://msdn.microsoft.com/en-us/library/c0tyye07(v=vs.140).aspx)) doesn't detect the end of the file name, and assumes that the comma in the filename indicates a new option segment.

Steps to reproduce:

1. Create a new C# project in VS2015 RTM
2. Add a new XML file named `My,DataFile.xml`
3. Change the data file's Build Action to `Embedded Resource`

Expected results:

1. Project compiles successfully.

Actual results:

    1>------ Build started: Project: EmbeddedResourceComma, Configuration: Debug Any CPU ------
    1>CSC : error CS1906: Invalid option 'EmbeddedResourceComma.My'; Resource visibility must be either 'public' or 'private'
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

This is a regression, it worked as expected in Visual Studio 2013.

**Comment by bkoelman** [comment] 2015-08-05 14:30
Duplicate of #4021?

**Comment by yaakov-h** [comment] 2015-08-06 07:44
Looks like a perfect duplicate. Should I close this?

**Comment by bkoelman** [comment] 2015-08-06 08:02
I think that would be best, yes. Thanks for reporting. You can Subscribe to
the other issue if you like. Then you'll get an email each time it changes.

**Closed** 2015-08-06 08:03 UTC
Labels: Area-Compilers
