### ISSUE TITLE
More style options for IDE0090 - Target-typed new expressions

### ISSUE THREAD

**Issue by hannahchan** [dotnet/roslyn#55305] opened 2021-07-31 03:32 UTC
This is just a feature request to add more options so that we can control style preferences for target-typed new expressions more finely.

Currently in .NET 5 / C# 9 the only options we have is;

```
csharp_style_implicit_object_creation_when_type_is_apparent
```

When set to `true`, a code clean up simplifies;

```C#
MyObject myObject = new MyObject();
```

to;

```C#
MyObject myObject = new();
```

However when set to `false` it doesn't do the reverse. This is annoying to developers who prefer;

```C#
var myObject = new MyObject();
```

There is another scenario where target-typed new expressions is preferred however syntax like the following is not;

```C#
var myObject = new MyObject(new());
```

Or;

```C#
MyObject myObject = new(new());
```

In the above examples, the type passed into the parameterised constructor is not apparent.

If would be nice to have a few more style options to address the above scenarios.

**Comment by CyrusNajmabadi** [comment] 2021-08-02 21:15
> However when set to false it doesn't do the reverse. 

Correct, the style options are there to help migrate code to newer idioms.  They don't, generally, force the other direction.  If you don't want to use the new pattern just don't use it (and turn the style option off).

> This is annoying to developers who prefer;

If you prefer the full form, then just write the full form, we're not stopping you :)  (and with the style option off, we won't prompt to change it).

> In the above examples, the type passed into the parameterised constructor is not apparent.

Correct.  If you set csharp_style_implicit_object_creation_when_type_is_apparent we never push to have you change to that (since, as you correctly point it, it's not apparent).  We've considered an option to suggest using this in all cases, but there hasn't really been feedback from anyone that they want that, so it's not even on our backlog.

**Comment by hannahchan** [comment] 2021-08-03 10:47
The reason I think the rule should be reversible is because the style rules for `var` are:

```
csharp_style_var_elsewhere
csharp_style_var_for_built_in_types
csharp_style_var_when_type_is_apparent
```

When used with code clean up tools such as [dotnet-format](https://github.com/dotnet/format), you can switch between different styles depending on whether the values are set to `true` or `false`.

This is inconsistent to how `csharp_style_implicit_object_creation_when_type_is_apparent` works.

Here's a scenario. Imagine that you have the following rules in your .editorconfig;

```
csharp_style_var_elsewhere = true:warning
csharp_style_var_for_built_in_types = true:warning
csharp_style_var_when_type_is_apparent = true:warning
```

And someone writes the following line of code;

```C#
MyObject myObject = new();
```

But the preferred styled is;

```C#
var myObject = new MyObject();
```

Code cleanup currently can't fix this up. The reviewers would need to locate all these instances and change them manually. Going the other way around currently works.

In regards to the style `MyObject myObject = new(new())`. I would like to vote for a rule that allows/disallows target-type expressions in the constructor. I know it's not in the backlog right now but maybe as target-type expressions are used more often more people will feel the same.

**Comment by CyrusNajmabadi** [comment] 2021-08-03 17:36
> The reason I think the rule should be reversible is because the style rules for var are:

This doesn't follow the 'var' styling intentionally.  Note: if you'd like a rule to prevent this lang feature, it woudl be really trivial to write your own analyzer here.

> Code cleanup currently can't fix this up.

In general, teh purpose of these features isn't to allow people to control every knob or disable new and useful language features.  For that, writing your own analyzer/fixer is the preferred way to go.  The purpose of these features is to allow a quick way to bulk move to new features that we have either already felt are ok to default to, or you can decide is ok.  

In this case, we felt that defaulting this to 'on' was appropriate as we got near unanimous sentiment that it was readable and clear and superior to the existing form.  If you don't like it though, just turn it off :)

**Comment by ChristopherHaws** [comment] 2023-01-04 20:59
Another scenario is the `Exception` type.

This statement:
```csharp
throw new Exception("Some exception...");
```

could be simplified to:
```csharp
throw new("Some exception...");
```

**Comment by CyrusNajmabadi** [comment] 2024-11-13 20:12
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-11-13 20:12 UTC
Labels: Area-IDE, Feature Request, Feature - IDE0090
