### ISSUE TITLE
Refactor "Move type to file" should re-evaluate file header template

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74703] opened 2024-08-09 21:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactor-Move-type-to-file-should-re-e/10718712)._

---
\[severity:It bothers me. A fix would be nice\]  
My editorconfig defines a file\_header\_template that includes the {filename} placeholder.

Consider a file `A.cs` that contains `class A` and `class B`. I want to move type `class B` to its own file.

Using the Quick actions and refactorings > `Move type to 'B.cs'` option, `class B` is cut from `A.cs` and located in a new file `B.cs` that isn’t opened afterwards (which is good). Alongside cutting `class B`, Visual Studio also _copies_ all comments at the top of `A.cs`, which happens to be the file header.

Since it copies those lines directly, the file header of `B.cs` will now claim to be for a file named `A.cs`. To fix that, I’ll need to manually open `B.cs` anyway and hit “Save” once, to re-apply the file\_header\_template settings, which will fix the file name in `B.cs`.

---
#### Feedback Bot on 8/8/2024, 10:25 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/9/2024, 02:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:37
Closing out as by design.  The file header is intentionally copied over.

**Comment by LWChris** [comment] 2024-12-04 10:07
Hi Cyrus,

when a template uses `{filename}`, copying the header over unchanged is guaranteed to be wrong. That's why I filed this bug report, to notify you of a case where your current behavior causes a problem (which requires three additional manual steps to mitigate).

So intentional or not, it is causing a bug, so right now closing this without explanation WHY it is intentional to keep the wrong template is completely illogical and impossible to understand.

1. You do <X>.
2. A bug report is filed "Doing <X> is causing a problem."
3. The report is closed only saying "We intentionally do <X>."

Please explain the reasoning behind this intention, i.e. what is the benefit of not re-evaluating (or offering a new opt-in setting to enable that)?

**Comment by CyrusNajmabadi** [comment] 2024-12-04 15:59
Sorry, should be dupe of https://github.com/dotnet/roslyn/issues/58660

**Closed by CyrusNajmabadi** 2024-12-04 15:59 UTC
Labels: Area-IDE

**Comment by LWChris** [comment] 2024-12-04 16:07
Thank you.
