### ISSUE TITLE
Unused local variable not getting grayed out

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn#54297] opened 2021-06-22 20:12 UTC
**Version Used**: 
Visual Studio Community 2019 16.10.2
Both:
.NET Framework 4.7.2 Console App and
.NET 5 Console App
The default compiler versions that come with those project templates.

**Steps to Reproduce**:
Given the piece of code in the screenshot below, the `companyId` variable does NOT get grayed out as unused:

![image](https://user-images.githubusercontent.com/4363170/122992360-159cb700-d3b7-11eb-8c88-1702cc6fe4fe.png)

`Entity` is just a simple class with a single property of type `Guid`.
The lambda on the line below has something to do with it. When I remove that line, or use the overload of `Enumerable.Any` with no parameters, the unused variable gets reported as expected.

**Expected Behavior**:
The `companyId` variable should get grayed out.

**Actual Behavior**:
It doesn't.

**Comment by Youssef1313** [comment] 2021-06-22 23:13
Duplicate of https://github.com/dotnet/roslyn/issues/52328.

**Closed** 2021-07-08 14:19 UTC
Labels: Area-Compilers, untriaged

**Comment by nadav-tenne-clinch** [comment] 2024-09-01 07:29
happen to me on version 17.11.2
