### ISSUE TITLE
Possibly null warning following Debug.Assert()

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#38019] opened 2019-08-15 20:18 UTC
When compiling with .NET Framework, the use of `Debug.Assert()` adds warnings rather than removing.
```C#
using System.Diagnostics;

class Program
{
    static void F(
        object x,
#nullable enable 
        object y)
    {
        Debug.Assert(x != null);
        Debug.Assert(y != null);

        x.ToString(); // warning: possibly null
        y.ToString(); // warning: possibly null
    }
}
```

**Comment by 0xd4d** [comment] 2019-08-15 20:48
Dupe of https://github.com/dotnet/roslyn/issues/37979

**Comment by jcouv** [comment] 2019-08-21 19:54
I think that's by design. `Debug.Assert` is not annotated in that implementation.

The same warning occurs if you write `_ = x != null;`. That's a pure null test, which implies that the value may be `null` (from a public API for example).

**Comment by jcouv** [comment] 2019-08-21 19:55
Closing as duplicate

**Comment by sharwell** [comment] 2019-08-21 19:55
Duplicate of #37979

**Closed** 2019-08-21 19:55 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-By Design, Resolution-Duplicate
