### ISSUE TITLE
VS2015 RC: IntelliSense randomly breaks, complaining about missing references

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#2700] opened 2015-05-13 01:18 UTC
In VS 2015 RC (did also happen in CTP 6, not sure if it started in CTP 6 or in the previous one) IntelliSense breaks apparently randomly, telling me that i must add references to system assemblies. This doesn't seem to affect nuget packages or my own libraries. Compiling still works fine but i get a ton of:
```
Error CS0012: The type "Attribute" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Dictionary<,>" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Enum" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Expression<>" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Linq.Expressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "HttpStatusCode" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "IDisposable" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "IEnumerable" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "IEnumerable<>" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "IOrderedEnumerable<>" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "MulticastDelegate" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Object" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Stream" is defined in an assembly that is not referenced. You must add a reference to assembly "System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Task<>" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS0012: The type "Uri" is defined in an assembly that is not referenced. You must add a reference to assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". 
Error CS1579: foreach statement cannot operate on variables of type "System.Collections.Generic.Dictionary" because "System.Collections.Generic.Dictionary" does not contain a public definition for 'GetEnumerator' 
Error CS1579: foreach statement cannot operate on variables of type "System.Collections.Generic.IEnumerable" because "System.Collections.Generic.IEnumerable" does not contain a public definition for 'GetEnumerator' 
Error CS1660: Cannot convert lambda expression to type 'TraceListener' because it is not a delegate type.
```
While i can't remember having gotten any error notification in CTP 6, VS 2015 RC told me that a plugin crashed, ActivityLog.xml shows:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at Microsoft.CodeAnalysis.CSharp.CodeFixes.AddMissingReference.AddMissingReferenceCodeFixProvider.<RegisterCodeFixesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```
The messagebox, accompanied by broken IntelliSense happened while i've switched a tab from XAML(WPF) to a CS file after VS spent some time being minimized.
The only way to restore IntelliSense is to restart VS, closing all tabs and reopening them doesn't help.

**Comment by jmarolf** [comment] 2015-05-13 01:27
I believe pull request #2607 will fix the IndexOutOfRangeException problem. However, a crashing analyzer shouldn't cause intellisense to break.

**Comment by Pilchie** [comment] 2015-05-13 17:04
The CS0012 errors are likely caused by the same issue as #1373.  This was fixed in MSBuild after the fork for RC, but you can work around it by adding:

```XML
<CheckForSystemRuntimeDependency>true</CheckForSystemRuntimeDependency>
```

To your .csproj file in the `<PropertyGroup>` at the top without any conditions.

**Closed by Pilchie** 2015-05-13 17:04 UTC
Labels: Area-IDE, Bug

**Comment by MattGertz** [comment] 2015-05-15 22:16
Verified dupe.
