### ISSUE TITLE
Useless "intellisense" messages during "build".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#27964] opened 2018-06-18 19:39 UTC
It seems like there a really high percentage chance on any build that i get this sort of message:

![image](https://user-images.githubusercontent.com/4564579/41558043-7fa35702-72f4-11e8-82e8-c8eed2c28d60.png)

1. i don't think this message has ever been useful to me.
2. this message seems spurious since i think the .g.cs file will is just being regenerated, so we'll be able to read it a moment later.
3. it's *obnoxious* that the "output" window switches to this while i'm in the middle of a build.

Can we do something about this?  Even if it's just fixing "3" so we don't actually switch over... that would likely be good enough.

Thanks! :)

**Comment by sharwell** [comment] 2018-06-19 10:13
We have another bug for this as well. I did an initial investigation to try and remove the writing of these messages to the output window, but was not successful. The same code is used for printing these errors and for some more serious cases, which rules out 3 and rules out simply removing the logging code. I finally concluded that this may be a symptom of a real product bug but haven't fixed it yet. Will dupe this later in the morning.

**Comment by CyrusNajmabadi** [comment] 2018-06-19 17:50
> The same code is used for printing these errors and for some more serious cases, which rules out 3 and rules out simply removing the logging code.

Can we telemetry this guy?  I'd lke to know how many times we hear about the 'serious' case vs the 'totally spurious and unhelpful case that is really annoying' case :)

**Comment by davkean** [comment] 2018-06-20 02:47
I'm waiting for someone to sign off on my PR: https://github.com/dotnet/roslyn/pull/26230 to prevent focus from being stolen.

**Comment by davkean** [comment] 2018-06-20 03:10
@CyrusNajmabadi I've confirmed that 3 above is fixed by my change, and I'm going to merge this in tomorrow.

**Comment by CyrusNajmabadi** [comment] 2018-06-21 18:05
@jasonmalinowski Could you give your thoughts on this specific issue.  This is about something i see when i explicitly invoke 'build'.  Some way through the build, the focus switches from the actual build output to the 'intellisense output' window.

**Comment by jasonmalinowski** [comment] 2018-06-21 20:15
Yeah, because there's all sorts of insane complexity around how WPF swaps files out here. For this, I'd say the right thing is to delete the window. :smile:

**Comment by jcouv** [comment] 2018-06-21 23:11
Relates to https://github.com/dotnet/roslyn/issues/23266

**Comment by davkean** [comment] 2018-06-21 23:43
Going to dup against https://github.com/dotnet/roslyn/issues/12202.

**Closed by davkean** 2018-06-21 23:43 UTC

**Comment by davkean** [comment] 2018-06-21 23:45
This issue is different from the one you are running into @jcouv. Your issue is a design-time build issue, this issue above is a timing issue due to communication between project system and Roslyn.
