### ISSUE TITLE
Linux builds are timing-out due to what appears to be a deadlock

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6210] opened 2015-10-21 15:01 UTC
[Log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/402/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52)

```
20:48:07   CSharpCompilerSyntaxTest -> /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Debug/Roslyn.Compilers.CSharp.Syntax.UnitTests.dll
20:48:11   BasicCompilerTestUtilities -> /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Debug/Roslyn.Compilers.VisualBasic.Test.Utilities.dll
20:48:19   vbc -> /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Debug/vbc.exe
20:48:25   BasicCommandLineTest -> /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Debug/Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll
22:39:02 
Build timed out (after 120 minutes). Marking the build as aborted.
```

@mavasani Can you look into this?

**Comment by davkean** [comment] 2015-10-21 15:04
Or rather, can we start with one of the @dotnet/roslyn-compiler team?

**Comment by mavasani** [comment] 2015-10-21 15:15
@agocke If you can help attach lldb to the hung process so I can attach with an ssh just like last time, I can take a look.

**Comment by gafter** [comment] 2015-10-21 16:00
This may be the recently fixed #6177 #6172

**Comment by mavasani** [comment] 2015-10-21 16:15
@gafter The log shows that we successfully built the toolset compilers from latest sources (which should have the AsyncQueue fix). We are seeing a hang when trying to build with these locally built toolset - the hang is in a VB project so looks strikingly similar to the prior deadlock. I can take a look once Andy can setup an ssh session for me.

**Comment by davkean** [comment] 2015-10-21 16:23
@mavasani @stephentoub says:

> In short, though, you want to use lldb-3.6
> e.g.
> lldb-3.6 ./corerun
> You key part is using sos, which is in the libsosplugin
> From in lldb-3.6, do:
> plugin load libsosplugin.so
> Once that's loaded, you have access to many of the SOS commands folks may be familiar with
> For example, you can use lldb to list the threads:
> thread list
> Then switch to a specific thread you want, e.g.
> thread select 8
> And then use SOS to view the managed call stack
> sos ClrStack
> SOS on Linux currently supports viewing the call stack, setting managed breakpoints, inspecting locals, IP2MD for converting addresses to method infos, etc.

**Comment by stephentoub** [comment] 2015-10-21 16:28
Debugging instructions are here:
https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md

**Comment by mavasani** [comment] 2015-10-21 16:33
Thanks @davkean @stephentoub. Andy walked me through the lldb/SOS commands couple of days back, and I used those to identify the root cause of the deadlock. However, he had done all the setup for me - I just had to ssh into the machine and it was already running lldb attached to the hung process, with the sos plugin loaded.

Given that this deadlock repros very rarely, we probably want to attach to an existing hung process rather then try to repro it again. So, my question is do we have the machine with hung compiler available, and if so what command should I use to ssh into it and attach lldb to a running process?

**Comment by davkean** [comment] 2015-10-21 16:39
Following up offline.

**Comment by mavasani** [comment] 2015-10-21 17:12
I was able to ssh to the Linux node, but it seems the hung process was aborted:
```
dotnet-bot@dci-ub-bld-14:~$ ps
  PID TTY          TIME CMD
16065 pts/0    00:00:00 bash
16090 pts/0    00:00:00 less
16097 pts/0    00:00:00 ps
dotnet-bot@dci-ub-bld-14:~$ 
```

Next time we see this repro, we should make sure not to abort the build and take the node offline - ping me and I'll take a look immediately.

**Comment by mavasani** [comment] 2015-10-21 17:14
Or probably just take a dump when it repros again, even that should suffice. I am closing this issue now.

**Closed by mavasani** 2015-10-21 17:14 UTC
Labels: Area-Compilers, Contributor Pain
