### ISSUE TITLE
Crash when pasting multiple tokens into a namespace rename

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#3204] opened 2015-05-31 16:38 UTC
Source:

```C#
namespace A { }
```

Enter rename for `A`, then paste `A.B`.

'Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.

```
>	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.RenameToken(Microsoft.CodeAnalysis.SyntaxToken oldToken, Microsoft.CodeAnalysis.SyntaxToken newToken, string prefix, string suffix)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.RenameAndAnnotateAsync(Microsoft.CodeAnalysis.SyntaxToken token, Microsoft.CodeAnalysis.SyntaxToken newToken, bool isRenameLocation, bool isOldText)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.CodeAnalysis.SyntaxToken>.Start<Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.<RenameAndAnnotateAsync>d__36>(ref Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.<RenameAndAnnotateAsync>d__36 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.RenameAndAnnotateAsync(Microsoft.CodeAnalysis.SyntaxToken token, Microsoft.CodeAnalysis.SyntaxToken newToken, bool isRenameLocation, bool isOldText)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.VisitToken(Microsoft.CodeAnalysis.SyntaxToken token)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIdentifierName(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept<System.__Canon>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<System.__Canon> visitor)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitQualifiedName(Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax.Accept<System.__Canon>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<System.__Canon> visitor)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept<System.__Canon>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<System.__Canon> visitor)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement<Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax>(Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList<Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax>(Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax> list)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept<System.__Canon>(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<System.__Canon> visitor)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor<Microsoft.CodeAnalysis.SyntaxNode>.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.AnnotateAndRename(Microsoft.CodeAnalysis.Rename.RenameRewriterParameters parameters)	Unknown
```

**Comment by SLaks** [comment] 2015-05-31 17:00
This appears to be from http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Rename/CSharpRenameRewriterLanguageService.cs,584

**Comment by Pilchie** [comment] 2015-05-31 19:35
@dpoeschl Just checked in a fix for this a couple of days ago.

**Comment by Pilchie** [comment] 2015-05-31 19:36
Duplicate of #1031.

**Closed by Pilchie** 2015-05-31 19:36 UTC
