### ISSUE TITLE
Csc is slow when processing inheritance chain of generic types

### ISSUE THREAD

**Issue by zarikadzer** [dotnet/roslyn#70169] opened 2023-09-28 15:40 UTC
**Version Used**: 
17.7.3+8ec440e68 (.NET 7.0.401 and higher)

**Steps to Reproduce**:
Compile the following code using MSBuild version 17.7.3+8ec440e68.
It's possible to use the latest Visual Studio 2022 as well.
```C#
class A<T> {}
class B<T> : A<T> {}
class C<T> : B<T> {}
class D<T> : C<T> {}
class E<T> : D<T> {}
class F<T> : E<T> {}
class G<T> : F<T> {}
class H<T> : G<T> {}
class I<T> : H<T> {}
class J<T> : I<T> {}
class K<T> : J<T> {}
class L<T> : K<T> {}
class M<T> : L<T> {}
class N<T> : M<T> {}
class O<T> : N<T> {}
class P<T> : O<T> {}
class Q<T> : P<T> {}
class R<T> : Q<T> {}
```

**Expected Behavior**:
The compilation process takes less than one second and is independent of the chain's length.

**Actual Behavior**:
The compilation process takes at least 24 seconds, and the duration may vary depending on the length of the chain.
![WindowsTerminal_2hCsslk72v](https://github.com/dotnet/roslyn/assets/9337044/e8eec12c-87c8-43dd-9469-5d68871b1f6f)
![devenv_fyteAce5ht](https://github.com/dotnet/roslyn/assets/9337044/452ee55d-edf2-49d6-9a0c-c4250b02520b)
![EXCEL_CjWuyysPnr](https://github.com/dotnet/roslyn/assets/9337044/4015e345-b282-411c-bbff-1a99c4c5cf70)

**Additional info**:
Previous versions of MSBuild work well.
![WindowsTerminal_AeWmm1kPn2](https://github.com/dotnet/roslyn/assets/9337044/d822a33c-ace6-4912-994b-292ff6fd6334)

**Comment by zarikadzer** [comment] 2023-09-29 09:24
MSBuild 17.4.1+9a89d02ff also works fine.

**Comment by JBeen** [comment] 2023-09-30 09:03
> MSBuild 17.4.1+9a89d02ff also works fine.

With that in mind, if you want .NET 7, you need to use 7.0.1
Versions depends: https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs

**Comment by zarikadzer** [comment] 2023-09-30 10:59
> > MSBuild 17.4.1+9a89d02ff also works fine.
> 
> With that in mind, if you want .NET 7, you need to use 7.0.1 Versions depends: https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs

It works for me while using the `dotnet build`, but I still face the problem using Visual Studio 2022 to build such code.

**Comment by zarikadzer** [comment] 2023-09-30 11:26
> > MSBuild 17.4.1+9a89d02ff also works fine.
> 
> With that in mind, if you want .NET 7, you need to use 7.0.1 Versions depends: https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs

It works for me while using the `dotnet build` (VSCode, Rider, console tools etc.), but I still face the problem using Visual Studio 2022 to build such code.
![WindowsTerminal_xgQHcOkzXo](https://github.com/dotnet/roslyn/assets/9337044/b9429286-4e3e-4cc1-8d5c-7a62f1f2521a)

**Comment by jaredpar** [comment] 2023-10-02 02:01
At a glance this looks like a dupe of #69515. @jjonescz can you take a look?

**Comment by JBeen** [comment] 2023-10-02 05:50
@zarikadzer Can you check this in 17.8 P2?
(https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview)

**Comment by jjonescz** [comment] 2023-10-02 09:06
Yes, this is a duplicate of https://github.com/dotnet/roslyn/issues/69515. Should be fixed in the next version of Visual Studio 17.7 and SDK 7 (although it currently seems to be stuck here https://github.com/dotnet/sdk/pull/35545); and already fixed in current previews of VS 17.8 and SDK 8.

**Closed by jjonescz** 2023-10-02 09:06 UTC
Labels: Bug, Area-Compilers

**Comment by zarikadzer** [comment] 2023-10-02 10:15
> @zarikadzer Can you check this in 17.8 P2? (https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview)

17.8 P2 works well with this stuff.

**Comment by zarikadzer** [comment] 2023-10-02 10:57
> Yes, this is a duplicate of #69515. Should be fixed in the next version of Visual Studio 17.7 and SDK 7 (although it currently seems to be stuck here [dotnet/sdk#35545](https://github.com/dotnet/sdk/pull/35545) so might be in the version after that); and already fixed in current previews of VS 17.8 and SDK 8.

I've tried the latest VS 17.8 and SDK 8 and I'm still facing this bug:
![image](https://github.com/dotnet/roslyn/assets/9337044/7e971707-5e10-498b-b76d-1b1b9a9760a0)

@jjonescz Could you please share the download link for the SDK8 that includes those fixes?

**Comment by jjonescz** [comment] 2023-10-02 11:31
@zarikadzer yes, sorry, it's actually fixed only in the next version of SDK 8 which isn't released yet. You can download a nightly version of SDK 8 here which should work: https://github.com/dotnet/installer?tab=readme-ov-file#table

**Comment by zarikadzer** [comment] 2023-10-02 13:35
> @zarikadzer yes, sorry, it's actually fixed only in the next version of SDK 8 which isn't released yet. You can download a nightly version of SDK 8 here which should work: https://github.com/dotnet/installer?tab=readme-ov-file#table

Finally, I've got the working environment! 
VS 17.8.0 Preview 2.0
SDK 8.0.100-rtm.23479.3 (MSBuild 17.8.1+585e09762)
![image](https://github.com/dotnet/roslyn/assets/9337044/a99ff7f5-f4b4-41da-b02e-41859280a354)

@jjonescz thx
