### ISSUE TITLE
TextStructureNavigator doesn't recognize string literals

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#3203] opened 2015-05-31 13:41 UTC
Double-clicking (or Ctrl+Clicking) the opening quote of a string literal token (any of the three kinds) should select the entire literal.  

This is a regression from 2013.

**Comment by Pilchie** [comment] 2015-06-01 22:03
Can you take a look at this?  Shouldn't it have been addressed by #945.

**Comment by SLaks** [comment] 2015-06-01 22:37
I tried this on the RC build, and it didn't work.

I don't see any code there to differentiate between Ctrl+Right and double-click (I don't even know how that's supposed to work)

**Comment by Pilchie** [comment] 2015-06-01 22:38
Tagging @jasonmalinowski who has also looked at the text structure navigator code.

**Comment by brettfo** [comment] 2015-06-01 23:04
To properly fix this, we need to be able to differentiate between keyboard (Ctrl+Right) and mouse (double-click) like @SLaks suggested.  We really need the code to look like this:

``` C#
if (doubleClicked)
{
    return token.Span;
}
else
{
    // do what we currently do
}
```

But unfortunately, that information is lost 7 frames above Roslyn in the editor code and the entry point to us is exactly the same.  What did we do to differentiate the two selection types in VS2013?

**Comment by Pilchie** [comment] 2015-06-01 23:06
In VS 2013, we didn't implement an ITextStructureNavigator. We used the old IVsTextFilter.GetWordExtent. Maybe we (or the editor) had more info in that codepath.

**Comment by jasonmalinowski** [comment] 2015-06-01 23:17
Based upon what I remember from when I last looked at the code in my cave while feasting on dinosaur meat, this only "worked" because when asked for the word extent for the position before the leading " in a string it returned the span of the entire token. @brettfo what do we return in that specific case right now?

(I also wasn't convinced this was a feature and not a bug in the first place.)

**Comment by brettfo** [comment] 2015-06-02 00:05
Currently we return the span of the opening quote character, and that's what's required to make keyboard navigation work.  If we return the span of the whole string then Ctrl+Right will move the cursor to after the closing quote, which is partly what I fixed in #945.

**Comment by jasonmalinowski** [comment] 2015-06-02 00:12
But I suspect Ctrl+Right also did that in VS2013 as well?

**Comment by SLaks** [comment] 2015-06-02 00:17
I'm reasonably certain that VS2013 did distinguish between Ctrl+Right and double-clicking the quote.

**Comment by brettfo** [comment] 2015-09-18 19:30
Note: this is also being tracked internally by bug 137236.

**Comment by GSPP** [comment] 2016-07-25 18:18
Note, that double-clicking the opening quote in the following code selects an insane region:

            var x = ("");

This selects: ("");

Another test case is double-clicking the closing quote.

Regardless of what past IDEs did double-clicking and Ctrl-clicking should do the same thing here.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:35
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-19 21:35 UTC
Labels: Bug, Area-IDE, Blocked
