### ISSUE TITLE
False "remove unused fields" & methods from XAML events

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#35429] opened 2019-05-02 00:30 UTC
**Version Used**: latest

**Steps to Reproduce**:

1. Clone https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
2. Look at the information roslyn detects

**Expected Behavior**:
It should not have suggestions for removing unused parameters from event handlers where the signature matters. It also misses one event entirely and sees it as unused.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1427284/57051494-c7b11c00-6c4f-11e9-8140-79f4393a6897.png)

**Comment by mavasani** [comment] 2019-08-19 22:25
Duplicate of https://github.com/dotnet/roslyn/issues/37483#issuecomment-522003292

**Comment by mavasani** [comment] 2019-08-21 00:02
Re-opening and tagging for design review so it can be discussed at next IDE design meeting.

**Comment by mavasani** [comment] 2019-08-21 00:02
Oops, meant to re-open the original against which this was duped.

**Closed by mavasani** 2019-08-21 00:02 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, Resolution-Duplicate
