### ISSUE TITLE
Having a certain number of (bool) arguments in base constructor call is causing CS0012 "The type ... is defined in an assembly that is not referenced."

### ISSUE THREAD

**Issue by maf1024** [dotnet/roslyn#16754] opened 2017-01-25 21:42 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

**Steps to Reproduce**:
Attempt to compile attached example sln:
[ConsoleApplication3151419.zip](https://github.com/dotnet/roslyn/files/730997/ConsoleApplication3151419.zip)

For readers that don't want to open files:
Basically there's this base class in ClassLibrary2 with two protected constructors:
```
namespace ClassLibrary2
{
   public class AbstractDog
   {
      protected AbstractDog(bool isNeutered, bool isHousebroken, bool isImaginary = false, bool isActuallyACat = false)
      {
      }

      protected AbstractDog(bool isNeutered, bool isHousebroken, ObscureThingConsoleApplicationNeedntKnowAbout thing)
      {
      }
   }
}

```
where `ObscureThingConsoleApplicationNeedntKnowAbout` is a class defined in a different assembly ClassLibrary1.

Then, in the console application project which is only referencing ClassLibrary2, three calls to the base constructor are made (via three separate classes):

```
namespace ConsoleApplication3151419
{
   class Program
   {
      static void Main(string[] args)
      {
         Console.WriteLine("Hello world");
      }
   }

   public class Beagle : AbstractDog
   {
      //compiles
      public Beagle()
         : base(true, true)
      {
      }
   }

   public class DiamondDog : AbstractDog
   {
      //doesn't compile
      public DiamondDog()
         : base(false, false, true)
      {
      }
   }

   public class Garfielf : AbstractDog
   {
      //compiles
      public Garfielf()
         : base(false, false, true, true)
      {
      }
   }
}

```

**Expected Behavior**:
Compiles.

**Actual Behavior**:

The usage of the base constructor having the same number of (bool) arguments as the second base constructor is apparently triggering an unexpected need to reference `ObscureThingConsoleApplicationNeedntKnowAbout`, producing compile error:

Error	CS0012	The type 'ObscureThingConsoleApplicationNeedntKnowAbout' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClassLibrary1...

**Comment by gafter** [comment] 2017-01-25 22:11
See also #9370 #13824 #15588

**Comment by jaredpar** [comment] 2017-03-09 23:14
Thanks for reporting.  Resolving as a duplicate of the issues @gafter listed.

**Closed by jaredpar** 2017-03-09 23:14 UTC
Labels: Area-Compilers, Bug, Tenet-Compatibility
