### ISSUE TITLE
VS C# Editor, Advanced, Editor Help, "Split string literals on enter" broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39040] opened 2019-10-03 21:30 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752445/vs-c-editor-advanced-editor-help-split-string-lite.html)._

---
&quot;Split string literals on enter&quot; has been broken since it was introduced, and still is in VS2019.

![image](https://user-images.githubusercontent.com/1408396/66427836-a5bf8080-e9c9-11e9-94bd-98508de86053.png)

Additionally, it's _completely_ broken if you use multi-carets. Then it doesn't even pretent to attempt to &quot;Split string literals on enter&quot;, it just splits and indents each caret without inserting quotes, totally destroying the string literal.

I can be more forgiving about the latter bug, since multi-caret was a later addition to the editor, &lt;rant_mode=&quot;on&quot;&gt;but please - stuff like this needs to be _checked_ before release&lt;rant_mode=&quot;off&quot;&quot;&gt;.
Anyway, it's a clear bug and needs to be fixed. Should be no more than a few minutes of work after the main bug has been fixed.

---
#### Visual Studio Feedback System on 9/28/2019, 09:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2019-10-08 19:49
The bad indentation caused by the indentation issue which is fixed by #38893. Leaving this open to address the multi-caret issue.

**Comment by tamlin-mike** [comment] 2019-10-10 13:09
Original issue reporter here.

First, a thank you to @CyrusNajmabadi and/or @sharwell, for adding the large comment in  TryGetSmartTokenIndentation (#38893). It helped me understand how this issue had come to be.

It also displayed how wrong that code is - which explains why Visual Studio still after decades can't get this stuff right. What follows could probably be seen as a bit of a rant, in the wrong place, but it's an issue that has been annoying the hell out of me for decades, and seeing that code was the final straw.

Let me try to explain what I'm talking about, and how it has, and continually is, hurting users (and probably yourselves, but since that's self-inflicted you won't get any sympathy from me).


Since the original exposé I wrote a few decades ago about this issue has vanished in the big empty, let me first point you towards an article that while not as in-depth, still explain some basics you need to learn:
https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces

To repeat and expand:

`Indentation` is used for semantical scope. For some languages (e.g. Python) even syntactical scope, but let's disregard that for now and stay with 3rd gen syntactically C-derivatives.
`Indentation` is measured in _level_, not hard-coded "number of whitespace" or "column number" or some other hard metric. Level.

You can use whatever you like for indentation; spaces or tab's. It doesn't matter, so long as they are not used as the unit of measurement for indentation - only the visual representation of it.

`Alignment` on the other hand is a purely cosmetic construct, and _that_ can indeed be measured as _relative offset_ from Indentation in "# of columns", "# spaces", or in certain cases even tab can work (1).

For a construct such as
```
  void a()                // line 1
  {                       // line 2
    string s = "aa\n" +   // line 3
               "bb\n";    // line 4
  }                       // line 5
```
There are both `Indentation` and `Alignment` concerns here, and to produce correct result both must be addressed.

`Indentation` is at lines 1, 2 and 5 one level.
At lines 3 and 4 it is two levels.
At line 4, the `Indentation` is _followed_ by `Alignment`, in this sample to make it match with the string constant starting quote of the previous line. Excluding the exception, the _only_ reliable way to apply `Alignment` is spaces - but that is only _after_ the `Indentation` has been applied.

Following these simple rules, it doesn't matter if Indentation is 0, 1 space, 2, spaces, tab-4, or even tab-20. The code will _always_ look correct (meaning: how the author intended it to look).

Going back to the original example (though displaying it as if indentation level was 2, whether it's tab-size 2 or 2 spaces):
```
  void fn_expected()
  {
    string s = "aa\n" +
      "bbaa\n" +
      "ccaa\n"; // cutting off here to reduce repetition
  }
```
If we expand this into the elements, it becomes
```
<ind1>void fn_expected()
<ind1>{
<ind2>string s = "aa\n" +
<ind2><algn1>"bbaa\n" +
<ind2><algn1>"ccaa\n"; // cutting off here to reduce repetition
<ind1>}
```
Of course a parser have to parse the code by looking at the _characters_, but the semantical element preceeding tokens on a line is, for all intent an purposes, an `Indentation` with a level, followed by zero or more `Alignment` spacings. Nowhere should a code transformation tool think of this as "character offset" - that's the completely wrong level, a non-semantical non-abstraction level. It would be like using a fixed-record-size flat database and refer to file offsets, when the correct represenation is record#. Should record size ever change, the code using hard-coded file offsets _will_ fail, and that is exactly what VS is doing.

(1) This example also displays one of the few cases where tab potentially _could_ be used for alignment without messing up, provided tab-size was less than 12.

Another scenario Visual Studio has never got right is when you need to break up a `for`:
```
  for (init; cond; inc)
```
Now imagine that for some reason one or more of those three elements become so long and unwieldly you need to break that up. What you probably would want is 
```
  for (init;
       cond;
       inc)
```
i.e.
```
<ind>for (init;
<ind><algn>cond;
<ind><algn>inc)
```
where again `ind` can be anything (it doesn't matter), while `algn` _must_ be 5 spaces (`strlen("for (")`). Under no circumstances should `algn` include any tab characters, even if the user uses tab for indentation. Yet this cardinal error is exactly the error Visual Studio does in any of the languages (of the category discussed here) I have ever tested in it, in every version for the last two decades. Instead of the proper code I displayed it becomes
```
<indN>for (init;
<indN+1>cond;
<indN+1>inc)
```
and therefore produces complete _crap_ results if you were using tab for indentation, and someone else looks at your code with a different tab setting. Hell, it even fails to align it properly for _you_ unless you for this example happened to be using tab=5 (which I have never seen used. Ever).

This is obviously only a subset of all the errors generated by this complete lack of separation of indentation vs. alignment.

It's _infuriating_ how bad this is, and how much time is wasted to fix up these editor-produced errors, and manually align what the editor definitely should do for you. It's if possible even worse in C#, where the editor slams you hard with "I know better than you. THIS is what you want!" for just about _any_ syntactical elements, and _no_ way to disable that #¤%/& auto-formatting even for scopes where it might be _vital_ for readability to retain alignment.


While I have very low expectations of Microsoft as a company, and specifically Visual Studio as a product in this area (again, decades without improvement can't be misinterpreted), maybe, just maybe, this have swayed an individual or two, maybe even educated them, and in a distant future maybe this education could result in the Visual Studio editor actually gaining a basic understanding of these issue, grow up, and stop thrashing users source code.

**Comment by CyrusNajmabadi** [comment] 2019-10-10 15:38
You could, you know, contribute a PR @tamlin-mike. :-)

This seems like an important issue to you. If you can provide a good solution it would likely be appreciated

**Comment by tamlin-mike** [comment] 2019-10-11 09:07
@CyrusNajmabadi 
> You could, you know, contribute a PR

Impossible, to the best of my knowledge.

Again my reply becomes almost a chapter in a book, but there are many contributing factors preventing anyone outside of Microsoft from fixing this.

To make it clear - the following isn't about _this_ github issue. It's a tangent.

Unfortunately, the issue is dictated, designed and implemented by and in proprietary parts, making it impossible for a third party to even suggest concrete fixes for this (and other core editor bugs and design errors), much less create PR's for.

Had it been possible, I would have more likely than not provided actionable design change proposals and code more than two decades ago.

As it's in proprietary code, Microsoft has effectively shielded that team from external input (there _is_ no contact info), making it impossible to provide feedback. For all I know, there could be a room full of clueless code-monekys doing this, believing "All is fine. Must be, since we get no complaints whatsoever", completely unaware they are cut off from the outside world (the customers/users).

It's also not a C#-only thing, where it could be fixed (or "fixed", depending on viewpoint) independently but only for C#; it's core editor behavior for all C-derivative languages.

It requires an attention to detail Microsoft seemingly is unable to even comprehend.

This (and other broken core editor behaviors) is clearly by design, by the "old Microsoft" people on the "inside", and those people requires a "business case" (i.e. a bag of money - the size of a small country's GNP no doubt) to even turn on the brain and start thinking about anything. Going from that to then consider something, and finally do something about it, is from my understanding effectively and completely impossible (unless you possess and are willing to part with said bag of money - something very, very few entities on this planet do).

The only hope remaining is that they retire, and some replacement have gotten enough insight and irritation about bad and buggy behavior and design they do something about it, but that's a process way out of our control, and will take a generation or more of employees on the "inside" to be replaced before anything is done about it. Provided it's even possible at all.

It will likely be way too late for me to ever experience, as I'll be since long dead and burned to ashes by then, but I write this with hope, no matter how small, it can help at least some in future generations.

It's sad, but "I reject your reality and substitute my own" doesn't work in this case. ;-)

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:13
> Impossible, to the best of my knowledge.

You can totally implement this here in Roslyn. :-)

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:14
> As it's in proprietary code, Microsoft has effectively shielded that team from external input (there is no contact info), making it impossible to provide feedback. 

Both Roslyn and editor take continual feedback and make changes in response to it for every release

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:18
> It requires an attention to detail Microsoft seemingly is unable to even comprehend.

So submit a pr yourself. 

I'm not Microsoft, but I address issues by opening prs and working with the teams (including the editor) to get them adopted. 

> and will take a generation or more of employees on the "inside" to be replaced before anything is done about it. 

Again, if you care so much, why not open a PR to improve things?  You've been willing to spend all this time complaining, so why not use that effort on something more constructive?  You even mention in your post that you don't think words will help. So perhaps consider taking action here. 

As someone with hundreds of external prs to Roslyn, I can tell you it's a very reasonable path to take.

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:22
> This (and other broken core editor behaviors) is clearly by design

Designs change. But usually through positive efforts and collaborative work. Rarely through just complaining about stuff. There are dozens of people working on improving or just plain revamping the designs of many parts of vs. It's just that they think those other parts are much more important and impactful to users. 

You can help out here by contributing your own time and effort demonstrating that this actually is something you feel is valuable enough and important enough to be considered. 

After all, why would you think someone else would find this important enough to take on if you aren't willing to do the same?

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:23
> It's sad, but "I reject your reality and substitute my own" doesn't work in this case. ;-)

I've written many components and systems in Roslyn that became core components of vs. I have first hand experience that this works. 

You can choose to reject reality, but that makes it seem as if you're not actually interesting in positive outcome and more interested in just complaining that people prioritize things differently than you.

**Comment by CyrusNajmabadi** [comment] 2019-10-11 15:25
Note: if you are interested in contributing, I recommend gitter.im/dotnet/Roslyn and the Roslyn discord channel as good places to go hash out ideas and collaborate on prs

**Comment by jmarolf** [comment] 2019-10-11 20:51
@tamlin-mike 	I don't want to be reductive but is it a fair summary to say that the problem is VS, all-up, handles mixed tabs and spaces poorly? If that is the case (echoing @CyrusNajmabadi) then this is fixable for a large section of .NET developers.  The formatter int this repository is fully open-sourced and is used across other languages at Microsoft to different extents.  If we fix the tabs and spaces behavior here it is likely that we could see adoption in other components.

**Comment by sharwell** [comment] 2019-10-22 23:38
@tamlin-mike I agree that tabs should not be used for character-level alignment. With that said, the indentation strategy used for alignment typically does not cause a problem:

1. The current formatter generally does not try to vertically align things. There are a few exceptions (e.g. LINQ), but not many.
2. Hard tabs rarely change width. You can take this one step further by setting `tab_width` in the .editorconfig file, e.g. antlr/antlr4#1984.

In addition to the sheer implementation difficulty of attempting vertical alignment, it turns out that developers who want to vertically-align code are _extremely_ opinionated while at the same time not agreeing with each other. To meet the diverse needs of this set of developers, our goal is to provide an extension point to the formatter (#31691) which is then used throughout the IDE features. Teams will be able to provide their own specific formatting rules without needing to explain those rules to other teams who will have very different opinions.

**Closed** 2019-10-31 16:23 UTC
Labels: 3 - Working, Area-IDE, Bug
