### ISSUE TITLE
F7 (switch to text-view) not working in .editor Config Editor in VIsual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58605] opened 2022-01-04 22:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F7-switch-to-text-view-not-working-in-/1594781)._

---
[severity:It bothers me. A fix would be nice]
Repro steps:

Launch VS 2022
Load a solution with an .editorconfig file in it. 
Open the .editorconfig file by double clicking it in the Solution Explorer
Press F7 (to view the code)
Result:
Doesn’t work

Expect:
F7 should show the text contents of the .editorconfig file

I attached a sample solution.

kind regards
 Nina

---
#### Feedback Bot on 11/24/2021, 05:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Nina Pollak on 11/25/2021, 11:37 PM: 

(private comment, text removed)
#### Feedback Bot on 11/29/2021, 09:56 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Fire Zhang [MSFT] on 12/9/2021, 06:48 PM: 

<p>Thank you for taking the time to log this issue!<br>
Did you still reproduce this issue in the latest stable version of Visual Studio2022(17.0.2)? I can’t repro it with the project you provided. If it still occurs, can you provide the diagnostic logs?<br>
Diagnostic logs can be turned on by going to Test -&gt; Options -&gt; Logging Level and setting it to Diagnostic. Once the problem is reproduced with the logs on, they are automatically attached to the feedback ticket.</p>

#### Nina Pollak on 12/13/2021, 10:31 AM: 

(private comment, text removed)
#### Fire Zhang [MSFT] on 12/15/2021, 10:40 PM: 

(private comment, text removed)
#### Nina Pollak on 12/16/2021, 03:00 AM: 

(private comment, text removed)
#### Fire Zhang [MSFT] on 12/16/2021, 06:18 PM: 

(private comment, text removed)
#### Feedback Bot on 12/28/2021, 11:53 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:30
duplicate of https://github.com/dotnet/roslyn/issues/53120

**Closed by jmarolf** 2022-03-18 21:30 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - Editor Config UI
