### ISSUE TITLE
Test TestRecoverableSyntaxTreeCSharp is flaky

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13788] opened 2016-09-14 17:31 UTC
The test `Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeCSharp` depends on GC behavior that is not guaranteed. I've seen it fail nondeterministically, for example

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/3542/

**Comment by AdamSpeight2008** [comment] 2016-09-14 18:33
@gafter I've seen the Visual Basic also fail flaky (see #13600). Which involved `TypeKind` so may narrow down the issue.

**Comment by gafter** [comment] 2016-09-14 18:48
The issue is that GC is not deterministic.

**Comment by natidea** [comment] 2016-09-16 18:35
Disabled test with #13857

**Comment by AdamSpeight2008** [comment] 2016-09-16 19:21
What about the VB test?

**Comment by CyrusNajmabadi** [comment] 2016-09-16 20:45
The VB test was also disabled. @jasonmalinowski introduced thsi and will take a look at it.

**Comment by jasonmalinowski** [comment] 2016-10-05 17:05
Dupe of #13433.

**Closed by jasonmalinowski** 2016-10-05 17:05 UTC
Labels: Area-IDE, Bug, Flaky, Test
