### ISSUE TITLE
Nullability annotations for variables are inferred incorrectly for deconstruction declarations

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31317] opened 2018-11-22 08:22 UTC
**Version Used**: 

Branch C# 8.0: Nullable reference type (29 Oct 2018)
https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md
Latest commit 2f8fef by AlekseyTs:
Compare Nullable modifiers while comparing type symbols by default. (#30770)

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
class C
{
    void M()
    {
        var s1 = default(string);
        var (s2, s3) = (default(string), s1);
        s1.ToString(); // warning CS8602: Possible dereference of a null reference.
        s2.ToString(); // no warning
        s3.ToString(); // no warning

        s1 = null;
        s2 = null; // warning CS8600: Converting null literal or possible null value to non-nullable type.
        s3 = null; // warning CS8600: Converting null literal or possible null value to non-nullable type.
    }
}
```

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAHwGIztd8IACCMvAgFgAUAAEATNwDCIgN4jui7qIAs3ALIAKAJQKl84UqPcAblATdkARm4BebgBMSUbDE2irABm0BuPcdNzbk1kcQAaSwBmbTtgpzAXLDcPbwjrX39jawA6agB7AGUYBABLMgBzHR9uAHoa7gB3czIy8ukCgA4ANk9xEG4ABTzkZBKuRwgkUj4qbjywbihudhxuKcmZiGzMo1DcwuLWqtr6sjzG5tadpWRI/aLSiuO65fOmhBaKkWvFa1iVrB+QwBSySewA6ovd6fNpSTo9Tz9KR5MgmSYwVrLDjcLAlGCTKBYOYWejDUbjAGBLBwHgwc5nMioAECWkMLY/KL/DiQ+rQzFw7qeRHSFFohAYipY1a4/EIQnE7ikkZjAhSolmam0+kopkcFncGBs7bAxQAXxEpqAA

**Expected Behavior**:

The variables `s2` and `s3` have `string?` type. Warnings for their dereference and no warnings for assigning null values to them.

**Actual Behavior**:

Roslyn infers that `s2` and `s3` are non-nullable.

**Notes**

Similar to https://github.com/dotnet/roslyn/issues/31298

**Comment by jcouv** [comment] 2018-11-24 05:19
Thanks. This is a known issue which we didn't get to yet. Closing as duplicate of https://github.com/dotnet/roslyn/issues/29618

**Closed by jcouv** 2018-11-24 05:19 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
