### ISSUE TITLE
GeneratedCodeAnalysisFlagsMap is slow being segmented dictionary

### ISSUE THREAD

**Issue by ninedan** [dotnet/roslyn#67909] opened 2023-04-21 01:40 UTC
**Version Used**: Microsoft Visual Studio\2022\Enterprise

**Steps to Reproduce**:

1. Build a .cs project using VS2022, capture an ETW trace

GeneratedCodeAnalysisFlagsMap is a segmented dictionary, accessed quite often through ShouldSkipAnalysisOnGeneratedCode check (using 4.2% CPU). The underlying segmented dictionary is quite slow in .Net framework, because segment size and shift can't be inlined by jit compiler. So it's slower than dictionary access, plus there are only 188 items in the dictionary, so no need to be segmented dictionary.

Suggestion: either switch to use normal dictionary, or change segmented dictionary implementation.

**Comment by CyrusNajmabadi** [comment] 2023-04-21 02:56
@ninedan can you please attach your trace?  Thanks!

**Comment by ninedan** [comment] 2023-04-21 03:19
Here is the caller stack:

![image](https://user-images.githubusercontent.com/19536938/233532856-cc9da247-9764-4053-a2cb-c3946288e0d1.png)

Here is the implementation:
![image](https://user-images.githubusercontent.com/19536938/233532719-b7ef6bed-1460-4f99-8a50-109f3fcb0b7a.png)

Assembly code:

!U 00007ffe`df7db3e0
preJIT generated code
Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_Item(Int32)
Begin 00007ffedf7db3e0, size 5b
00007ffe`df7db3e0 57              push    rdi
00007ffe`df7db3e1 56              push    rsi
00007ffe`df7db3e2 53              push    rbx
00007ffe`df7db3e3 4883ec30        sub     rsp,30h
00007ffe`df7db3e7 4889542428      mov     qword ptr [rsp+28h],rdx
00007ffe`df7db3ec 488bf2          mov     rsi,rdx
00007ffe`df7db3ef 418bf8          mov     edi,r8d
00007ffe`df7db3f2 488b19          mov     rbx,qword ptr [rcx]
00007ffe`df7db3f5 488bce          mov     rcx,rsi
00007ffe`df7db3f8 ff150293c5fe    call    qword ptr [Microsoft_CodeAnalysis_ni+0x74700 (00007ffe`de434700)] (Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_SegmentShift(), mdToken: 0000000006003526)
00007ffe`df7db3fe 8bc8            mov     ecx,eax
00007ffe`df7db400 8bc7            mov     eax,edi
00007ffe`df7db402 d3f8            sar     eax,cl
00007ffe`df7db404 3b4308          cmp     eax,dword ptr [rbx+8]
00007ffe`df7db407 732c            jae     Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_Item(Int32)+0x203405 (00007ffe`df7db435)
00007ffe`df7db409 4863c8          movsxd  rcx,eax
00007ffe`df7db40c 488b5ccb10      mov     rbx,qword ptr [rbx+rcx*8+10h]
00007ffe`df7db411 488bce          mov     rcx,rsi
00007ffe`df7db414 ff15ee92c5fe    call    qword ptr [Microsoft_CodeAnalysis_ni+0x74708 (00007ffe`de434708)] (Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_OffsetMask(), mdToken: 0000000006003527)
00007ffe`df7db41a 23c7            and     eax,edi
00007ffe`df7db41c 3b4308          cmp     eax,dword ptr [rbx+8]
00007ffe`df7db41f 7314            jae     Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_Item(Int32)+0x203405 (00007ffe`df7db435)
00007ffe`df7db421 4863c0          movsxd  rax,eax
00007ffe`df7db424 488d0440        lea     rax,[rax+rax*2]
00007ffe`df7db428 488d44c310      lea     rax,[rbx+rax*8+10h]
00007ffe`df7db42d 4883c430        add     rsp,30h
00007ffe`df7db431 5b              pop     rbx
00007ffe`df7db432 5e              pop     rsi
00007ffe`df7db433 5f              pop     rdi
00007ffe`df7db434 c3              ret
00007ffe`df7db435 e8fc03ddff      call    Microsoft_CodeAnalysis_ni+0x11eb836 (00007ffe`df5ab836) (Microsoft_CodeAnalysis_ni)
00007ffe`df7db43a cc              int     3

!U 00007ffe`df7db360
preJIT generated code
Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_SegmentShift()
Begin 00007ffedf7db360, size 37
00007ffe`df7db360 4883ec28        sub     rsp,28h
00007ffe`df7db364 48894c2420      mov     qword ptr [rsp+20h],rcx
00007ffe`df7db369 488b5130        mov     rdx,qword ptr [rcx+30h]
00007ffe`df7db36d 488b12          mov     rdx,qword ptr [rdx]
00007ffe`df7db370 488b4228        mov     rax,qword ptr [rdx+28h]
00007ffe`df7db374 4885c0          test    rax,rax
00007ffe`df7db377 750d            jne     Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.Collections.SegmentedArray`1[[Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2+Entry[[System.__Canon, mscorlib],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis]], Microsoft.CodeAnalysis]].get_SegmentShift()+0x2033d6 (00007ffe`df7db386)
00007ffe`df7db379 488d156320ab00  lea     rdx,[Microsoft_CodeAnalysis_ni+0x1ecd3e3 (00007ffe`e028d3e3)]
00007ffe`df7db380 ff15c2e1dcff    call    qword ptr [CLRStub[JumpStub]@7ffedf5a9548 (00007ffe`df5a9548)]
00007ffe`df7db386 488bc8          mov     rcx,rax
00007ffe`df7db389 488b05f8aac1fe  mov     rax,qword ptr [Microsoft_CodeAnalysis_ni+0x35e88 (00007ffe`de3f5e88)]
00007ffe`df7db390 4883c428        add     rsp,28h
00007ffe`df7db394 48ffe0          jmp     rax

get_Item itself should be inlined.

**Comment by CyrusNajmabadi** [comment] 2023-04-21 03:20
Hi @ninedan could you share the trace in it's entirety?  Thanks!

**Comment by genlu** [comment] 2023-04-26 18:52
@sharwell I think this is a duplicate of https://github.com/dotnet/runtime/issues/84094? Should be addressed by https://github.com/dotnet/roslyn/pull/67558 and https://github.com/dotnet/roslyn/pull/67921, right?

**Comment by sharwell** [comment] 2023-04-26 19:13
This was resolved by #67921

**Closed by sharwell** 2023-04-26 19:13 UTC
Labels: Area-Analyzers, untriaged
