### ISSUE TITLE
Better help information for built-in analysers

### ISSUE THREAD

**Issue by Im5tu** [dotnet/roslyn#29684] opened 2018-09-05 22:27 UTC
Source: https://twitter.com/Nick_Craver/status/1037457763817934851

Having the IDE go to Bing to search for results is a far from ideal situation. Would it be possible to make the analysers jump to a page in the docs, or on GitHub so that more friendly information can be displayed? Is this something that the community could contribute to if the structure to do so is in place?

**Comment by sharwell** [comment] 2018-09-05 23:33
Duplicate of #26717

**Closed by sharwell** 2018-09-05 23:33 UTC
