### ISSUE TITLE
Switch expressoins are marked as having formatting problems.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#36908] opened 2019-07-01 20:40 UTC
i.e.

![image](https://user-images.githubusercontent.com/4564579/60465319-a942af00-9c05-11e9-9473-30faee330391.png)

1. this is incorrect.  We don't want those switch expressions dedented as indicated. 
2. the 'fix' doesn't actually do anything.
3. this really clutters up the build log since there are hundreds of messages about this.

**Comment by CyrusNajmabadi** [comment] 2019-07-01 20:40
tagging @jasonmalinowski @dotnet/roslyn-ide Did we miss this when doing switch-expressions?

**Comment by JoeRobich** [comment] 2019-07-01 21:15
Other issues on this topic https://github.com/dotnet/roslyn/issues/35505 & https://github.com/dotnet/roslyn/issues/34962

**Comment by CyrusNajmabadi** [comment] 2019-07-01 21:20
The last comment on this was back in april: https://github.com/dotnet/roslyn/issues/34962#issuecomment-482771278

Is there any traction on fixing this?

**Comment by jasonmalinowski** [comment] 2019-07-01 21:32
Dupe of #36835. I'm not sure what happened here or if this just popped up. Oddly I couldn't figure out a way to resolve it, so I'm not sure if something is broken in a novel way.

**Closed by jasonmalinowski** 2019-07-01 21:32 UTC
