### ISSUE TITLE
Analyzer to flag a non-public class if it is not marked as sealed 

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23426] opened 2017-11-28 13:01 UTC

**Comment by benaadams** [comment] 2017-11-28 13:08
Only relevant if it has overridden methods?

**Comment by alrz** [comment] 2017-11-28 13:13
@benaadams Why? In my experience, sealed types generally have better `isinst` performance so I think this should be applied regardless of the presence of overriden methods.

**Comment by alrz** [comment] 2017-11-28 13:18
@benaadams Only relevant if only if it hasn't any derived class.

Further, we could use an option to produce warning if (public) types are not explicitly as non-sealed (with an attribute).

**Comment by benaadams** [comment] 2017-11-28 13:31
> Further, we could use an option to produce warning if (public) types are not explicitly as non-sealed (with an attribute).

Basically you are saying classes should always be sealed by default?

Non-sealed classes are very useful to side-car data which you can't do with composition; e.g. pass type to api, which then api passes elsewhere to get the data back out - without creating a global(ish) dictionary on with the object as key.

>  sealed types generally have better `isinst` performance

If you are using ` isinst` its a direct example of side-carring data on the `object` type (or the type's parent/hierarchy)

**Comment by alrz** [comment] 2017-11-28 13:37
>Basically you are saying classes should always be sealed by default?

This is what I'm trying to say: 

```cs
private class HasNoDerivedTypes {} // warning: the type can be sealed

public class HasNoDerivedTypes {} // optional warning
[NonSealed] public class HasNoDerivedTypes {} // explicit suppression 
```
Note: this is an IDE request.

**Comment by CyrusNajmabadi** [comment] 2017-11-28 20:41
I see.  It sounds like you want a suggestion that says to mark a class as sealed iff:

1. it has private accessibility.
2. it is not subclassed within the assembly.

If so, that seems reasonable.  Sounds like it would go in the roslyn-analyzers repo though. 

Note: afaict, there is no way to do this with the current analyzer system.  You'd need a CompilationEndAction so you could ensure that there were no subclasses.  But CompilationEndActions do not run by defualt for users.  Tagging @heejaechang

**Comment by jinujoseph** [comment] 2017-11-29 02:05
Tagging @mavasani , @dotnet/roslyn-analysis

**Comment by Youssef1313** [comment] 2022-03-18 12:43
Duplicate of https://github.com/dotnet/runtime/issues/49944

This analyzer will be implemented in dotnet/roslyn-analyzers repository, except for the "optional warning" part for public APIs. This is very unlikely to be useful.

@jinujoseph I believe this issue can be closed.

**Closed** 2022-03-18 14:43 UTC
Labels: Area-Analyzers, Feature Request
