### ISSUE TITLE
Pull member up takes #region but not #endregion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51530] opened 2021-02-27 00:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pull-member-up-takes-region-but-not-en/1348250)._

---
[severity:It bothers me. A fix would be nice]
When using the 'pull up member', it also takes the #region declaration that is above the member to the parent class, but not the matching #endregion.

So for example: 
https://i.imgur.com/LQ91HjO.png

If I use the pull up member: 
https://i.imgur.com/2Wtxsfv.png

Then I get an error about a missing #endregion: 
https://i.imgur.com/Bn4pABj.png

An easy fix would be to not include regions?

I also get an error about it being private... I wouldn't mind if it would automatically make it protected if it was private. But that's not the main issue here.

Also, I had to use imgur for the images, because the insert image button on developercommunity.visualstudio.com seems to give CORS errors (on firefox 78.7.1esr): 
https://i.imgur.com/VTCa14w.png

---
#### Feedback Bot on 2/25/2021, 01:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/26/2021, 09:35 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-02-27 00:10
Duplicate of #51531

**Closed by sharwell** 2021-02-27 00:10 UTC
Labels: Area-IDE, untriaged
