### ISSUE TITLE
Xamarin Not compatible with NetStandard

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10837] opened 2016-04-25 17:27 UTC
**Version Used**: 

**Steps to Reproduce**:

Create a new Class Library (Xamarin.Forms) 
By default it will support following TFM 

![x1](https://cloud.githubusercontent.com/assets/12449387/14792333/9c51d350-0ace-11e6-93e9-1bbc5846374f.JPG)
 
Now create a new portable class library (PCL) , pick the same TFM's to match the above class library

![b](https://cloud.githubusercontent.com/assets/12449387/14792424/f7b6a608-0ace-11e6-8429-ea478c9a10ab.JPG)

Reference PCL from Xamarin Class Library , every thing works.
Now remove the reference and change the PCL to target .NetStandard (.NetStandard1.1) 
Again reference the PCL from xamarin Class Library this time it throws compatibility issue.

![c](https://cloud.githubusercontent.com/assets/12449387/14792661/24f2f184-0ad0-11e6-9588-954556bb25b2.JPG)

**Expected Behavior**:

Xamarin Class Library should be able to reference PCL with .NetStandard

**Actual Behavior**:

Incompatibility Issue

**Comment by Pilchie** [comment] 2016-04-26 14:53
Is this something that can be fixed on the PCL side, or is it either NuGet or the Xamarin project flavor?

**Comment by rchande** [comment] 2016-04-26 17:27
I think this is a bug in NuGet--it reports that ".NETCore,Version=v5.0" is the lowest version of .NETCore in NetStandard1.0, which isn't right. Sent mail to @joelverhagen

**Comment by rchande** [comment] 2016-05-19 18:08
This should be fixed, can you verify?

**Comment by jinujoseph** [comment] 2016-05-24 23:56
The reference works with the above selection ..
But when you point the PCL to Netstandard (default picks .netstandard1.1) 
Build fails 

![image](https://cloud.githubusercontent.com/assets/12449387/15523583/62aa1d2e-21d0-11e6-9342-a585a78bfc73.png)

**Comment by rchande** [comment] 2016-05-26 21:24
Again, dupe of https://github.com/dotnet/roslyn/issues/11067

**Closed by rchande** 2016-05-26 21:24 UTC
Labels: Area-IDE, Bug, Urgency-Soon
