### ISSUE TITLE
Find All References doesn't display usages inside XML doc comments very well

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13811] opened 2016-09-14 23:34 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/18533593/10fcbab4-7a99-11e6-8c49-0f508ca27c76.png)

**Comment by davkean** [comment] 2016-09-14 23:35
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2016-09-14 23:36
Dupe of https://github.com/dotnet/roslyn/issues/13769

**Closed by CyrusNajmabadi** 2016-09-14 23:36 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
