### ISSUE TITLE
[language improvements] R language like optional parameter expression in VisualBasic

### ISSUE THREAD

**Issue by xieguigang** [dotnet/roslyn#16767] opened 2017-01-26 11:36 UTC
Hi, 

In current version of VisualBasic language, the math expression is not allowed in the optional parameter, For example, 

+ although the math expression ``1+1`` generates a constant result, but the parameter definition ``Optional a# = 1+1`` will be error.
+ although the math function like ``log(2, 2)`` is also generates a constant value result, but the parameter definition ``Optional b# = Math.Log(2, 2)`` will be error too.

This optional parameter expression language feature is one of my favoring in R language programming, and I hope this feature can be introduce into the VisualBasic too. Currently this R language like optional parameter expression can be **simulates using Linq Expression and Expression scripting, but it is still not so convenient and handy.**

![2017-01-26](https://cloud.githubusercontent.com/assets/9410171/22328694/845136b6-e3f8-11e6-8ef5-e73b55f39941.png)

You can found this R language like optional parameter expression simulation test at this source code file:
https://github.com/xieguigang/sciBASIC/blob/7fa7eede82b019c6b7dc608498a5d5c11442db2f/Data_science/Mathematical/Math/Test/Program.vb

```
a = 1
b = 2
x = (a+b)! * 100 = (1+2)! *100 = 3!*100 = (3*2)*100 = 600
y = 33
z = log(y) + 9 = log(33) + 9 = 12.4965
```

In my opinion, this R language like optional parameter expression is agree with the philosophy of VisualBasic language designing, By introduce this new optional parameter expression feature will makes the VisualBasic language more dynamics and handy for solving the problems.

**Comment by HaloFour** [comment] 2017-01-26 14:43
This would be the VB.NET equivalent to #13595.

**Comment by HaloFour** [comment] 2017-01-26 20:02
Just to note how optional parameters works in .NET, what happens is that the parameter is marked as optional and metadata is written with the constant value representing the default value of that parameter.  For specific supported primitive values that constant is stored in the metadata for the parameter, but both C# and VB.NET also support some additional types via special attributes.

When a supporting compiler sees an attempt to call a method with optional parameters that doesn't provide values for those parameters it extracts the constant value from the metadata and silently embeds that value directly at the call site.  So, given:

```vb
Public Sub Foo(Optional ByVal value As Integer = 123)
End Sub
```

If you try to call `Foo()` that is actually converted into `Foo(123)` during compilation.

This is important because if the default value for an optional parameter is changed in a library all of the existing programs using that library will continue to pass the original default value until they are recompiled.

In my opinion, attempting to expand the existing mechanism for default values to support arbitrary expressions is both overcomplicated and dangerous.

First, exactly how should those expressions be encoded as metadata?  The example above uses source, which is interesting but pretty much limits the support to only the consuming compiler.  That is unless you expect the C# compiler to be able to interpret and compile VB.NET default expressions and vice versa, but there are dozens of .NET languages so that would be completely impractical.  At best I think you could encode a blob containing a serialized expression tree, which could at least be language-agnostic.

Second, even with as simple as default parameters are today their behavior of embedding the value at the call site has been a known vector of versioning bugs.  If a library were to change the default value for whatever reason all of the consuming applications would still pass the original default value until they are recompiled.  If that change were to fix a bug then there's no way to easily update and fix that bug.  If the value were to be an expression and contain logic that considerably increases the likelihood that a bug will slip through.

So, again in my opinion, the only reasonable way to potentially address this would be for the compiler to automatically generate overloads representing each variant of the methods arguments, which then calculates the optional arguments and calls the next overload:

```vb
Public Class A
    Public Sub Foo(ByVal Optional x As Integer = Math.Pow(2, 3))
    End Sub
End Class

' compiles into

Public Class A
    Public Sub Foo(ByVal x As Integer)
    End Sub

    Public Sub Foo()
        Me.Foo(Math.Pow(2, 3))
    End Sub
End Class
```

This has two problems.

First, it's already perfectly legal to overload `Foo` with a method that accepts no parameters.  How would the compiler generate the appropriate overload if that were the case?

Second, what if there are multiple optional parameters with default values?  Let's say you had:

```vb
Public Class A
    Public Sub Foo(ByVal Optional x As Integer = Math.Pow(2, 2), ByVal Optional y As Integer = Math.Sqrt(x))
    End Sub
End Class
```

How exactly could overloads be generated for that?  You'd need four total methods, but two of those methods would share identical signatures, which isn't legal.

Anyway, just tossing out my two cents.  I think that the problem is interesting and there is merit to it,  but there are numerous concerns that would need to be addressed.

**Comment by jnm2** [comment] 2017-01-27 05:47
One possible solution would be for the compiler to generate methods to be called in lieu of a parameter. This solves the serialization problem, the versioning problem, and the different compilers problem:

```VB.NET
Foo(2, 3)

Public Class A
    Public Sub Foo(ByVal x As Integer, ByVal y as Integer, ByVal Optional z As Integer = x * y)
    End Sub
End Class
```

Desugars to:

```VB.NET
Foo(2, 3, Foo<z_default>(x, y))

Public Class A
    Public Sub Foo(ByVal x As Integer, ByVal y as Integer, <CompilerDefaultCalculation("Foo<z_default>")> ByVal z As Integer)
    End Sub
    <EditorBrowsable(EditorBrowsableState.Never)>
    Public Function Foo<z_default>(ByVal x As Integer, ByVal y as Integer) As Integer
        Return x * y
    End Sub
End Class
```

**Comment by jnm2** [comment] 2017-01-27 06:01
Anything that would be in scope in the body of the method would be in scope in the default expression.
Parameters can refer to each other as long as the dependency is not circular. Circular references should probably be disallowed, even though it would only fail if neither parameter is given a value at the call site.

```VB.NET
Foo(2, 3)

Public Class A
    Public Sub Foo(ByVal x As Integer, ByVal Optional y as Integer = z * 2, ByVal Optional z As Integer = x * x)
    End Sub
End Class
```

Desugars to:

```VB.NET
Dim x As Integer = 2
Dim z As Integer = Foo<z_default>(x)
Dim y As Integer = Foo<y_default>(z)
Foo(x, y, z)

Public Class A
    Public Sub Foo(ByVal x As Integer, <CompilerServices.DefaultCalculation("Foo<y_default>")> ByVal y as Integer, <CompilerServices.DefaultCalculation("Foo<z_default>")> ByVal z As Integer)
    End Sub
    <EditorBrowsable(EditorBrowsableState.Never)>
    Public Function Foo<y_default>(ByVal z As Integer) As Integer
        Return z * 2
    End Sub
    <EditorBrowsable(EditorBrowsableState.Never)>
    Public Function Foo<z_default>(ByVal x As Integer) As Integer
        Return x * x
    End Sub
End Class
```

**Comment by jnm2** [comment] 2017-01-27 06:05
I'm starting to want this for C#.

**Comment by xieguigang** [comment] 2017-01-27 07:02
Here is my points:

1. Such optional parameter expression feature was applied in R language successfully, most of the function definition in R language have this optional parameter expression, example as the ``heatmap.2`` function in R:
```R
# heatmap.2 {gplots}	
heatmap.2 (x,
    ...
    Colv=if(symm)"Rowv" else TRUE,
    reorderfun = function(d, w) reorder(d, w),
    notecex=1.0,
    notecol="cyan",
    na.color=par("bg"),
    tracecol="cyan",
    cexRow = 0.2 + 1/log10(nr),
    cexCol = 0.2 + 1/log10(nc),
    ...
    symkey = any(x < 0, na.rm=TRUE) || symbreaks,
    ...
)
```
So that, I think it is should'nt be a problem that if we worried about this new language feature may introduce bugs.

2. Such parameter expression feature can be implemented very easily using ``Linq Expression``, for example, here is a more simple version of the simulation:

#### Before apply
![qq 20170127145415](https://cloud.githubusercontent.com/assets/9410171/22362821/9a4417ba-e4a0-11e6-8d87-71709d63d4ec.png)

#### After apply
![qq 20170127145423](https://cloud.githubusercontent.com/assets/9410171/22362822/9ac7289e-e4a0-11e6-99de-41eaa0e400b6.png)

So I think this new feature wouldn't have too much technical problem that we implemented in roslyn compiler.

**Comment by HaloFour** [comment] 2017-01-27 12:35
R is a very different language by design and implementation.  The same concerns likely do not apply.

As for what you're demonstrating in VB.NET, it's effectively what I described in my first point, encoding the default values as strings of source.  That forces the compiler to have a compiler within the compiler to extract, calculate and embed the expression.  That also effectively eliminates any possibility of cross-language reuse.

**Comment by xieguigang** [comment] 2017-02-01 08:55
I have summarize this parameter expression in this article: [&lt;Optional Parameter Expression in VisualBasic>](https://www.codeproject.com/Articles/1167903/Optional-Parameter-Expression-in-VisualBasic)

**Comment by jnm2** [comment] 2017-02-01 15:52
@HaloFour So what's wrong with my non-expression-based solution?

**Comment by HaloFour** [comment] 2017-02-01 16:02
@jnm2 

I think that using attributes to refer consuming compilers to a mechanism through which the default value is calculated would be a lot cleaner than trying to embed the instructions for the compiler to recreate the expression locally.  However, I do have concerns.  This generated function then becomes a part of the public contract for that type.  Any generated name would have to be deterministic and such an algorithm likely become part of the language spec (at least for C#).  Any change to the name or signature would break existing consumers of the method.  Considering that the function would be required to accept dependency arguments as its own parameters that could mean that manipulating the expression would break compatibility even if the target method itself hasn't really changed.

Ultimately, I still prefer overloads.

**Comment by jnm2** [comment] 2017-02-01 16:07
@HaloFour Aren't there other publicly visible compiler generated members today? If public API is your only concern, they could be put in a static helper class.

**Comment by jnm2** [comment] 2017-02-01 16:09
@HaloFour It seems to be it would be good to decide on a good philosophy of public API and compiler generation because that would unblock many scenarios. For example, any public method that has an attrobute marking it compiler generated is not considered public API.

**Comment by HaloFour** [comment] 2017-02-01 16:18
@jnm2 

I don't believe that there are any instances of publicly-facing compiler generated types or members currently.  Anonymous types, iterators, async, auto-implemented properties, etc., all of the compiler generated chicanery is hidden in implementation details.  Unless you write some extremely fragile reflection code you're never likely to see, much less depend upon, any specific compiler generated names or internal signatures.

My concern is less that these generated functions are a part of a public API.  It's more that the compiler has to guarantee that these members are generated with identical signatures every single compilation otherwise consuming assemblies will break.  Take your example above, let's assume I want to change the parameter name from `x` to `px`.  Doing so wouldn't break any existing assemblies that depend upon my code since parameter names don't matter outside of reflection (yes, source might break if it uses named parameters, but that's a different concern).  However, if the name of the generated method changed from `Foo<x_default>` to `Foo<px_default>` then any assemblies that were already compiled which relied on the default value calculation would then fail with a `MissingMethodException` at run time.

**Comment by jnm2** [comment] 2017-02-10 06:11
@HaloFour I just read the record types proposal and caller-receiver default argument has similarities to what I proposed. https://github.com/dotnet/csharplang/blob/master/proposals/records.md#detailed-design

**Comment by HaloFour** [comment] 2017-02-10 12:23
@jnm2 

That only supports simple scalar values which the consumer would read from an accessible field/property and bind at the call site.  It does share some similarities with your concept, but it is significantly simpler and relies only on the declared public contract of the type, not introducing any other members which the consumer would have to use to derive those default values.

**Comment by jnm2** [comment] 2017-02-10 13:49
It shares the same issue: there will have to be metadata on the parameter telling the call site compiler what getter method to execute.
There aren't any generated members. Perhaps my proposal could take a page from that book and force you to cultivate the default parameter method manually since it is public and write your own attribute referring the call site compiler to the method you wrote.

**Comment by jnm2** [comment] 2017-02-10 13:51
You wouldn't have to write an attribute though. You could specify the method after the =, including binding other arguments to parameters in the default method.

**Comment by HaloFour** [comment] 2017-02-10 16:29
@jnm2 

Yes, there will have to be metadata, and that metadata will likely take the form of an attribute.  The attribute itself could be supplied by the BCL, as I assume will be the case with "wither" default values.

I could see your proposal expanded as you mention, using an accessible member as the source of the default value.  The caller would then embed the call to that function if the value was omitted.  That would probably work sufficiently well.  Assuming that the functions could accept the other argument values as parameters the compiler would still have to validate that cyclic references cannot happen.  The following should probably be a compiler error, if not at the declaration then at the callsite:

```cs
public class MyClass {
    public void DoSomething(int x = GetDefaultX(y), int y = GetDefaultY(x)) { ... }

    public static int GetDefaultX(int arg) { ... }
    public static int GetDefaultY(int arg) { ... }
}

var o = new MyClass();
o.DoSomething(); // ?
```

And honestly I'm still not sold that the complications are worth it over just overloading the method and handling default calculation yourself.

**Comment by jnm2** [comment] 2017-02-10 16:56
> And honestly I'm still not sold that the complications are worth it over just overloading the method and handling default calculation yourself.

Me neither, but once the proposal communication method is sorted let's see how it fits in the bigger scheme.

**Comment by jnm2** [comment] 2017-02-10 16:58
It could be as simple as not limiting to instance fields and properties. Any instance member, or any static member on any public type in the same assembly. At the very least, the metadata used to specify which field property could have this possible extension in mind.

**Comment by CyrusNajmabadi** [comment] 2022-11-08 17:21
Closing this out.  We're doing all language design now at dotnet/vblang.  If you're still interested in this idea let us know and we can migrate this over to a discussion in that repo.  Thanks!

**Closed by CyrusNajmabadi** 2022-11-08 17:21 UTC
Labels: Area-Language Design
