### ISSUE TITLE
Crash in VS due to an unexpected {"The point does not belong to a source snapshot of the projection snapshot"} System.ArgumentException

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#5969] opened 2015-10-14 20:27 UTC
Dump is available.

```
-                              $exception         {"The point does not belong to a source snapshot of the projection snapshot"}                System.ArgumentException
+                             Data       {System.Collections.ListDictionaryInternal}          System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
                                HResult -2147024809       int
                                HelpLink               null         string
+                             IPForWatsonBuckets      {0}          System.UIntPtr
+                             InnerException null         System.Exception
                                IsTransient          false      bool
                                Message              "The point does not belong to a source snapshot of the projection snapshot"     string
                                ParamName       null         string
                                RemoteStackTrace          null         string
                                Source  "Microsoft.VisualStudio.Platform.VSEditor"        string
                                StackTrace          "   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapFromSourceSnapshot(SnapshotPoint sourcePoint, PositionAffinity affinity)\r\n   at Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager`1.UpdateSpans_CallOnlyOnUIThread(NormalizedSnapshotSpanCollection changedSpanCollection, Boolean removeOldTags)\r\n   at Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager`1.UpdateInvalidSpans()\r\n   at Microsoft.CodeAnalysis.Editor.Implementation.LineSeparators.AdornmentManager`1.<>c__DisplayClass11_0.<OnTagsChanged>b__0()\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   at System.Windows.Threading.DispatcherOperation.InvokeImpl()\r\n   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Windows.Threading.DispatcherOperation.Invoke()\r\n   at System.Windows.Threading.Dispatcher.ProcessQueue()\r\n   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)\r\n   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)"  string
+                             TargetSite           {System.Nullable`1[Microsoft.VisualStudio.Text.SnapshotPoint] MapFromSourceSnapshot(Microsoft.VisualStudio.Text.SnapshotPoint, Microsoft.VisualStudio.Text.PositionAffinity)}    System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
+                             WatsonBuckets {byte[5616]}       object {byte[]}
                                _HResult              -2147024809       int
                                _className        "System.ArgumentException"   string
+                             _data    {System.Collections.ListDictionaryInternal}          System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
                                _dynamicMethods          null         object
+                             _exceptionMethod        {System.Nullable`1[Microsoft.VisualStudio.Text.SnapshotPoint] MapFromSourceSnapshot(Microsoft.VisualStudio.Text.SnapshotPoint, Microsoft.VisualStudio.Text.PositionAffinity)}    System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
                                _exceptionMethodString             null         string
                                _helpURL            null         string
+                             _innerException               null         System.Exception
+                             _ipForWatsonBuckets   {0}          System.UIntPtr
                                _message           "The point does not belong to a source snapshot of the projection snapshot"     string
                                _remoteStackIndex        0              int
                                _remoteStackTraceString             null         string
+                             _safeSerializationManager          {System.Runtime.Serialization.SafeSerializationManager}                System.Runtime.Serialization.SafeSerializationManager
                                _source                "Microsoft.VisualStudio.Platform.VSEditor"        string
+                             _stackTrace        {sbyte[384]}       object {sbyte[]}
                                _stackTraceString            null         string
+                             _watsonBuckets              {byte[5616]}       object {byte[]}
                                _xcode -532462766         int
+                             _xptrs   {0}          System.IntPtr
                                m_paramName                null         string
+                             Static members                
```

**Comment by Pilchie** [comment] 2015-10-22 04:26
@AlekseyTs #6173 looks like a dupe of this.  Do you remember if you were looking at a diff when this happened?

**Comment by davkean** [comment] 2015-10-22 04:35
Be sure to check out #6173 for the repro.

**Comment by CyrusNajmabadi** [comment] 2015-10-26 03:31
Fixed with https://github.com/dotnet/roslyn/pull/6272

**Closed by CyrusNajmabadi** 2015-10-26 03:31 UTC
Labels: Approved for next preview, Area-IDE, Bug, Tenet-Reliability
