### ISSUE TITLE
InteractiveCommandHandlerTests.TestCopyToInteractiveWithoutSelection fails in spainish run

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26441] opened 2018-04-27 00:02 UTC
In this [spainish run](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_spanish_unit32_prtest/597/)

The listener here:
https://github.com/dotnet/roslyn/blob/95d86bc7a884a1221718b3472ff28a7a3be044cf/src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs#L217

Fails to clean up

**Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Interactive.Commands.InteractiveCommandHandlerTests.TestCopyToInteractiveWithoutSelection** (from Roslyn.VisualStudio.CSharp.UnitTests)

```
MESSAGE:
System.TimeoutException : Failed to clean up listeners in a timely manner.
 ReportEntireFileChanged SyntacticClassificationTaggerProvider.TagComputer.cs 217
---- System.OperationCanceledException : Operación cancelada.
+++++++++++++++++++
STACK TRACE:
 en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest)
 en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__1()
 en Xunit.Sdk.ExecutionTimer.Aggregate(Action action)
 en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__0()
 en Xunit.Sdk.ExceptionAggregator.Run(Action code)
 ----- Inner Stack Trace -----
 en System.Threading.CancellationToken.ThrowOperationCanceledException()
 en System.Threading.CancellationToken.ThrowIfCancellationRequested()
 en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcherNoResult(Task task, CancellationToken cancellationToken)
 en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcher(Task task, CancellationToken cancellationToken)
 en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest)
```

**Comment by sharwell** [comment] 2018-04-27 20:33
Duplicate of #26144

**Closed by sharwell** 2018-04-27 20:33 UTC
