### ISSUE TITLE
using statement marked as not used when it is used inside comment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26318] opened 2018-04-22 02:10 UTC
While documenting a class, I added a triple-slash comment at its head and included a `<see cref="ModuleDeclarationBlock"/>` within it. This failed to autocomplete while typing and also didn't highlight correctly until the relevant using was added. However, the using statement added is greyed out and is removed if the &quot;Remove and Sort Usings&quot; option is used.

I appreciate that the using statement is only required to satisfy the requirements of a comment and is not used in any code, but I think it should not be flagged as unused since it has an impact on the appearance and usability of the editor.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/232794/using-statement-marked-as-not-used-when-it-is.html
VSTS ticketId: 599160_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-04-22 03:12
Duplicate of #2773

**Closed by sharwell** 2018-04-22 03:12 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
