### ISSUE TITLE
'Set / Open Active Rule Set' runs into problems when ruleset file is a linked file

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#1579] opened 2015-03-25 21:26 UTC
1. Add a rule set file as a linked file to a project
2. Right click the rule set file and click 'Set Active Rule Set' - the operation succeeds and there are no errors
3. Now click on References -> Analyzers -> 'Open Active Rule Set' for the project

**Observed:**
![capture](https://cloud.githubusercontent.com/assets/10579684/6835886/e6fdb520-d2fa-11e4-9fa7-0f26a27bbaa8.PNG)

Building the project from command line results in the following error -
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.VisualBasic.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "MyRules.ruleset".

Looks like we add the following property in the project. We should probably include relative path to the linked file in such cases instead?
    <CodeAnalysisRuleSet>MyRules.ruleset</CodeAnalysisRuleSet>

**Expected:** Linked rule set file should be opened with the 'Project' context drop down set to the above project. If this is an unsupported scenario then the 'Set Active Rule Set' option should not be offered for linked files - I think we should support this - allowing linked rule set files would make it easy to share a single rule set file between multiple projects via inside VS.

(Note: If we decide to support this, please test the case where the rule set is added under a top level solution folder and linked in to multiple projects. Double clicking on the rule set from the solution folder should populate the Project drop down with all projects that use this rule set - with the 'active' context set to '&lt;All&gt;'. Double clicking on the rule set from a particular project where it is linked should set the 'active' context to that project.)

**Comment by tmeschter** [comment] 2015-04-03 20:42
This is really two issues:

1. You can't use 'Open Active Rule Set' after 'Set Active Rule Set' when the rule set is a linked file.
2. If you open a rule set from a top-level solution folder it opens in the context of a project, rather than the <All> context.

I'm going to use this bug to track issue 1, and I've opened #1787 to track issue 2.

**Comment by tmeschter** [comment] 2015-04-17 15:02
Moving to @shyamnamboodiripad for verification.

**Comment by shyamnamboodiripad** [comment] 2015-05-16 00:02
I was able to repro the above issue on 5/11's build i.e. Above error dialog is still displayed if I try to 'open active ruleset file' when the ruleset file in use was actually a linked file in the current project (and I made it the active ruleset by right clicking on the linked file and saying 'Set as Active Ruleset'. 

Could this be a regression?

**Comment by tmeschter** [comment] 2015-05-18 16:17
@shyamnamboodiripad Dealing with relative paths and checking path equality is quite the pain. There's probably some case I simply didn't handle correctly.

**Comment by tmeschter** [comment] 2015-05-18 17:20
@shyamnamboodiripad I'm not able to reproduce this on the most recent bits. Could you provide more detailed repro steps? Or come find me in the office and we can go through it together.

**Comment by tmeschter** [comment] 2015-05-20 15:41
I'm going to double-check the following scenarios:

1. Rule set file in the same directory as the project file.
2. Rule set file one level above the project file.
3. Rule set file two levels above the project file.
4. Rule set file up two levels and then down in a subdirectory.
5. Rule set file one level below the project file.
6. Rule set file two levels below the project file.
7. Rule set file on a different directory.

**Comment by tmeschter** [comment] 2015-05-20 15:55
Adding a rule set two levels above the project file is problematic. We end up with `..\..\..\TwoLevelsUp.ruleset` instead of `..\..\TwoLevelsUp.ruleset`.

**Comment by tmeschter** [comment] 2015-05-21 15:53
Fixed by a5497dc3c9bc061c733ff35b0f72d5988bdac5ae.

**Closed by tmeschter** 2015-05-21 15:53 UTC
Labels: Area-Analyzers, Bug

**Comment by natidea** [comment] 2015-06-04 20:11
I've tried various scenarios, including adding ruleset as solution item, and linking it in various projects. No errors observed, though I did notice that ruleset was not always opened in 'All' context (#1787)
