### ISSUE TITLE
Non-nullable backing field of property marked uninitialized when property is assigned a value in constructor

### ISSUE THREAD

**Issue by Washi1337** [dotnet/roslyn#39291] opened 2019-10-15 15:21 UTC
**Version Used**: 
dotnet 3.0.100

**Steps to Reproduce**:

1. Run `dotnet new console` in an empty directory.
2. Enable nullable reference types by specifying `<Nullable>enable</Nullable>` in the `.csproj` file.
3. In `Program.cs`, paste in the following code:
```csharp
using System;

namespace ConsoleApp1
{
    internal static class Program
    {
        private static void Main()
        {
            var obj = new MyClass("Some name");
            Console.WriteLine(obj.Name);
        }
    }

    public class MyClass
    {
        private string _name;

        public MyClass(string name)
        {
            Name = name;
        }

        public string Name
        {
            get => _name;
            set
            {
                if (value == null)
                    throw new ArgumentNullException(nameof(value));
                if (value.Length > 10)
                    throw new ArgumentException("Name is too long.");

                _name = value;
            }
        }
    }

}
```
3. Run `dotnet build`

**Expected Behavior**:
A build without warnings.

**Actual Behavior**:
The build ends with the following warning:
```
warning CS8618: Non-nullable field '_name' is uninitialized. Consider declaring the field as nullable.
```

**Comment by RikkiGibson** [comment] 2019-10-15 20:21
This is by design at the moment, but perhaps indicates a need to support more indirect initialization patterns. Related to #39090. /cc @cston

**Comment by jaredpar** [comment] 2019-12-16 20:27
Closing as this is "By Design". It will be tracked under the uninitialized fields umbrella for consideration if we revisit this.

**Closed by jaredpar** 2019-12-16 20:27 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

**Comment by Washi1337** [comment] 2019-12-19 08:44
If it isn't possible to do this, what would be an alternative that would fit the idea of non nullable reference types?

**Comment by dynsim** [comment] 2022-01-13 11:21
@RikkiGibson: If this is by design, what would be the advised way to handle situations like these? Are there any alternatives to marking the backing field with the null-forgiving operator (e.g. `private string _name = null!` from the example above)?
