### ISSUE TITLE
Private field assigned in tuple notation should not produce IDE0044 (add readonly modifier)

### ISSUE THREAD

**Issue by thijmen321** [dotnet/roslyn#26868] opened 2018-05-15 20:30 UTC
**Version Used**: 15.7.1

**Steps to Reproduce**:

1. In any class (or struct for that matter), define a private field only assigned by a tuple, as shown in the example

```CS
class SomeClass
{
    // These fields both produce the "add readonly modifier" message
    private object A;
    private object B;

    public void AssignVariables()
    {
        (A, B) = MakeTuple();
    }

    public static (object, object) MakeTuple() => (new object(), new object()); // Just an example
}
```

**Expected Behavior**: This should not give the specified message

**Actual Behavior**: The message IDE0044 (add readonly modifier) is given, even though following this advice will result in an error
![](http://totally-not.a-sketchy.site/0a4a90.png)

**Comment by thijmen321** [comment] 2018-05-16 16:01
Seems like this was already fixed in https://github.com/dotnet/roslyn/pull/26303/commits/388efee57b16aedcab25703c971a79ee7dcc1ef3

**Comment by sharwell** [comment] 2018-05-16 16:13
Duplicate of 26264

**Closed** 2018-05-16 16:13 UTC
Labels: Resolution-Duplicate, Area-IDE, Feature - IDE0044
