### ISSUE TITLE
C# add usings use partial namespace when using statements are inside namespace blocks

### ISSUE THREAD

**Issue by yufeih** [dotnet/roslyn#12327] opened 2016-07-02 02:50 UTC
**Version Used**: Visual Studio 2015 Update 3

**Steps to Reproduce**:

![image](https://cloud.githubusercontent.com/assets/511355/16537845/59c6f08e-4042-11e6-93b6-b421ee443a17.png)

**Expected Behavior**:

Default to or have an option to output:

```
using System;
using Microsoft.ProductB;
```

**Actual Behavior**:

```
using System;
using ProductB;
```

**Comment by Pilchie** [comment] 2016-07-05 16:45
This is a duplicate of #3716, and will be fixed in a future release of VS "15" by #12152.

**Closed by Pilchie** 2016-07-05 16:45 UTC
