### ISSUE TITLE
Add automatically the semicolon (;) at the end when writing a new sentence in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49927] opened 2020-12-11 18:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-automatically-the-semicolon-;-at-t/1276914)._

---
Hi, it's only a suggestion for speed up when writting code in C#.
Because most of the sentence will ends with semicolon, why not to add it automatically?

Example:
If you write **var test** and press ENTER then the code shoudl be:
**var** test;

Thank you!
Guillermo

---
#### Feedback Bot on 12/3/2020, 09:45 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment] 2020-12-11 18:12
@sharwell

**Comment by sharwell** [comment] 2020-12-11 20:46
This is what we are designing <kbd>Shift</kbd>+<kbd>Enter</kbd> (Smart Break Line) for. 😄

**Comment by jinujoseph** [comment] 2020-12-15 20:57
Duplicate of https://github.com/dotnet/roslyn/issues/48857

**Closed by jinujoseph** 2020-12-15 20:57 UTC
Labels: Area-IDE, untriaged
