### ISSUE TITLE
non-nullability is not preserved

### ISSUE THREAD

**Issue by Spongman** [dotnet/roslyn#32458] opened 2019-01-15 00:20 UTC
```c#
public static Foo()
{
	Func<T, A0> Func<T, A0>(Func<T, A0> func) => func;
	var func = Func((int i) => default(string?));
	var val = func();
}
```

hover over the last `var` keyword. it shows `string`

i would expect `string?`

**Comment by Spongman** [comment] 2019-01-15 19:05
another one:
```c#
class Program
{
	static string? foo;

	static void Main()
	{
		var bar = foo;
	}
}
```
![image](https://user-images.githubusercontent.com/1088194/51203205-54101c80-18b5-11e9-802e-c7dbc7bbbd43.png)

**Comment by sharwell** [comment] 2019-01-29 19:05
Duplicate of #28524

**Closed by sharwell** 2019-01-29 19:05 UTC
Labels: Area-IDE, New Language Feature - Nullable Reference Types
