### ISSUE TITLE
Completion word breaking heuristics failing with leading _

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7912] opened 2016-01-12 22:31 UTC
``` C#
        void M()
        {
            int _testStuff;

        }
```

On the blank line, type `stuff` and `_testStuff` will be offered. 
Type `_stuff` and it will not be offered. I expect it to be offered.

**Comment by Pilchie** [comment] 2017-04-10 19:50
Dupe of #18131, and fixed in #18540

**Closed by Pilchie** 2017-04-10 19:50 UTC
Labels: Area-IDE, Bug
