### ISSUE TITLE
Resolve CS0535 for methods with Async suffix by auto-implementing async methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58218] opened 2021-12-09 20:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Resolve-CS0535-for-methods-with-Async-su/1592298)._

---
When choosing "Implement interface" to resolve CS0535 and the interface defines a method name with the Async suffix, the auto-implementation should have the async modifier by default.

---
#### Feedback Bot on 11/22/2021, 07:16 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 18:57
Closing out as by design.  If a user uses await inside the method, we add 'async' then

**Closed by CyrusNajmabadi** 2024-10-22 18:57 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, Developer Community
