### ISSUE TITLE
Compatibility check fails with portable class library (pointed to .NetStandard)

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#10485] opened 2016-04-11 22:58 UTC
Repro Steps 
- Create a .net class library (ClassLib1) with package.config (.Net Framework is 4.6 here) 
- Create a .net portable class library (ClassLib2) and point the Target Framework to .NetStandard 1.1
- Build both the projects
- Now reference ClassLib2 from ClassLib1 

Expected 
The reference should resolve file 

Actual 
you get a compatibility error 
![compatiblity](https://cloud.githubusercontent.com/assets/12449387/14444931/e7281686-fffd-11e5-8c42-24d30b924fd1.JPG)

Note:
If you change the Target of ClassLib2 to point it back to ""Target Portable Class Library Profile" "
The reference resolves correctly.

**Comment by jaredpar** [comment] 2016-04-14 18:24
@jinujoseph are there any work arounds to this failure?

**Comment by jinujoseph** [comment] 2016-04-14 23:16
I tried adding the reference manually as suggested by @rchande , it builds fine at that point but fails at run time with FileNotFoundException.

**Comment by rchande** [comment] 2016-05-19 18:10
Can you verify this?

**Comment by jinujoseph** [comment] 2016-05-24 23:44
Verified this on Verified this on build 14.0.25323.00 update 3 RC 

References work now 

But when you reference console application to incompatible class library ( make the reference to compatible lib and then change the Target to be incompatible) you get this warning in your build output 

![image](https://cloud.githubusercontent.com/assets/12449387/15523307/5bc4798e-21ce-11e6-96d7-71f2a51e0a48.png)

But then you reference a console application to pcl (.netstandard ) and make it incompatible , the warning is displayed only in the errorlist not in the build output 

![image](https://cloud.githubusercontent.com/assets/12449387/15523351/b7e9a126-21ce-11e6-8611-39fd8b59823d.png)


Expected ??

**Comment by rchande** [comment] 2016-05-26 21:25
Dupe of https://github.com/dotnet/roslyn/issues/11067

**Closed by rchande** 2016-05-26 21:25 UTC
Labels: Area-IDE, Bug
