### ISSUE TITLE
Print the exception documentation text to VS2019 tooltip on methods.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#43356] opened 2020-04-14 23:06 UTC
**Version Used**: 
What is in the VS2019 latest Preview.
**Steps to Reproduce**:

1. Create a method, could be anything that can throw an exception(s).
2. Document it and the exception(s) it can throw and the possible reasons it can throw.
3. The possible reasons it can throw is not printed in VS2019 forcing you to open up the method in metadata view (Or source view if in the same project as the affected method).

**Expected Behavior**:
VS2019 getting smart and start printing out the text in each documented exception that a method could throw.
So that way I can test and see if my exception documentation looks good (or fits with it well).

**Actual Behavior**:
No exception documentation is printed on the tooltip. Only the name of the exception is and not the: Exception name (colored) + documentation text for that documented exception.

![image](https://user-images.githubusercontent.com/15173749/79282232-aa865500-7e82-11ea-9903-65201ec4b5e9.png)
As this image shows above with a pictorial proof that this tooltip as it is at the moment really does suck. The method of mine in particular is being added to a local pre-release version of the next release of my zlib.managed package.

**Comment by sharwell** [comment] 2020-04-14 23:28
Duplicate of #1515

**Closed by sharwell** 2020-04-14 23:28 UTC
