### ISSUE TITLE
Cannot use MSBuildWorkspace in .NET Core Console Application

### ISSUE THREAD

**Issue by joeltankam** [dotnet/roslyn#28870] opened 2018-07-27 09:40 UTC
I'm moving a project from .Net Framework 4.6.1 to .Net Core and I have a problem with MSBuildWorkspace 

**Version Used**: 2.7.0

**Steps to Reproduce**:

1. Create a new .NET Core Console Application project (VS Professional 2017 Version 15.7.5,  .Net Core 2.1.202) 
2. Install nuget-packages for **Microsoft.CodeAnalysis**
3. In the main method write code:
`var workspace = MSBuildWorkspace.Create();`

**Expected Behavior**:

MSBuildWorkspace should compile by using Microsoft.CodeAnalysis.MSBuild.

**Actual Behavior**:

**Compilation error** :  'MSBuildWorkspace' could not be found (are you missing a using directive or an assembly reference?)
`Microsoft.CodeAnalysis.MSBuild` is not present under Microsoft.CodeAnalysis package.

**Comment by Tornhoof** [comment] 2018-07-27 10:56
https://github.com/dotnet/roslyn/issues/17974#issuecomment-393966038 might help.

**Comment by daveaglick** [comment] 2018-07-27 11:08
Yep, not .NET Standard/Core yet (from the thread @Tornhoof linked):

> Note that, because the MSBuild bits are still not available in .NET Standard/Core, your project has to target .NET Framework 4.6 or higher.

**Comment by joeltankam** [comment] 2018-07-27 11:20
Thanks @Tornhoof @daveaglick 
Is there any workaround ?

**Comment by jmarolf** [comment] 2018-07-27 16:16
> Is there any workaround ?

Today MSBuildWorkspace depends on the .NETFramework MSBuild.  If you need something for .NET Core you can use AdHocWorkspace like @daveaglick has done on https://github.com/daveaglick/Buildalyzer

**Comment by sharwell** [comment] 2018-07-31 16:57
Duplicate of #17974

**Comment by sharwell** [comment] 2018-07-31 16:58
@DustinCampbell Let me know if there's a better tracking issue for the xplat story of the new `MSBuildWorkspace` 👍

**Closed by sharwell** 2018-07-31 16:57 UTC

**Comment by EamonNerbonne** [comment] 2020-09-11 07:55
In case sometime finds this after some googling, to use MSBuildWorkspace on .net core you can follow these instructions: https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application - essentially adding a reference to `Microsoft.Build.Locator`; adding `ExcludeAssets="runtime"` to other `Microsoft.Build.???`  `<PackageReferences>`, and calling `MSBuildLocator.RegisterDefaults();` at the start of your program.
