### ISSUE TITLE
Initialize field from constructor

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#17007] opened 2017-02-07 23:32 UTC
_From @jchannon on July 20, 2016 9:52_

## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:1.3.1
C# Extension version:1.2.2
## Steps to reproduce

Add a new argument to a constructor
## Expected  behavior

Alt+Enter/Lightbulb option to "Initialize field from argument"
## Actual behavior

No options in lightbubl

_Copied from original issue: OmniSharp/omnisharp-vscode#591_

**Comment by DustinCampbell** [comment] 2017-02-07 23:32
To be fair, we'd like to have this in Visual Studio _and_ Visual Studio Code. :smile:

**Comment by DustinCampbell** [comment] 2017-02-07 23:32
_From @jchannon on July 20, 2016 14:57_

Go get Jetbrains drunk and steal their code when not looking 😉

**Comment by DustinCampbell** [comment] 2017-02-07 23:32
As their code isn't based on Roslyn, that's not too helpful. My point was that we'll likely add this at Visual Studio (hopefully in the near future) and then bring it to VS Code as part of that.

**Comment by Pilchie** [comment] 2017-02-15 17:59
Duplicate of https://github.com/dotnet/roslyn/issues/15648

**Closed** 2017-02-15 18:10 UTC
Labels: Area-IDE, Feature Request, Resolution-Duplicate
