### ISSUE TITLE
Go To Implementation shouldn't include abstract methods in "implementations"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41469] opened 2020-02-06 22:42 UTC
Unlike Go To Implementation on an interface method, Go To Implementation on an abstract method includes that method as part of its implementations.

**Steps to Reproduce**:

``` C#
    interface IFoo
    {
        void Method();
    }

    abstract class FooBase
    {
        public abstract void Method();
    }

    class Foo : FooBase, IFoo
    {
        public override void Method()
        {

        }
    }
```
1. Go To Implemention on IFoo.Method

-- _Navigates to `Foo.Method` as expected_ --

2. Go To Implementation on FooBase.Method

**Expected Behavior**:

Navigates to `Foo.Method()`

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1103906/73984927-f7831200-498d-11ea-956c-59fdc099f373.png)

**Comment by jmarolf** [comment] 2020-02-06 22:59
CC: @mikadumont

**Comment by sharwell** [comment] 2020-02-12 20:59
Duplicate of #26167

**Closed by sharwell** 2020-02-12 20:59 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Need Design Review
