### ISSUE TITLE
IDE extract method fails to handle some deconstruction scenarios.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15508] opened 2016-11-24 01:26 UTC
The IDE code is not resilient against arbitrary expressions appearing on the left-hand-side of a deconstruction. It tries to produce a zero-element tuple type, which causes an exception to be thrown.

This will be a problem after generalized deconstruction support is added to the compiler, even in error scenarios. I'll skip the two affected tests, `GenerateMethodTests.TestDeconstruction3` and `4`. The offending code is here, in `src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs`:

```cs
            private bool TryGetTupleTypesAndNames(
                SeparatedSyntaxList<ArgumentSyntax> arguments,
                out ImmutableArray<ITypeSymbol> elementTypes,
                out ImmutableArray<string> elementNames)
            {
                elementTypes = default(ImmutableArray<ITypeSymbol>);
                elementNames = default(ImmutableArray<string>);

                var elementTypesBuilder = ArrayBuilder<ITypeSymbol>.GetInstance();
                var elementNamesBuilder = ArrayBuilder<string>.GetInstance();
                try
                {
                    foreach (var arg in arguments)
                    {
                        var expr = arg.Expression;
                        if (expr.IsKind(SyntaxKind.DeclarationExpression))
                        {
                            AddTypeAndName((DeclarationExpressionSyntax)expr, elementTypesBuilder, elementNamesBuilder);
                        }
                        else if (expr.IsKind(SyntaxKind.TupleExpression))
                        {
                            AddTypeAndName((TupleExpressionSyntax)expr, elementTypesBuilder, elementNamesBuilder);
                        }
                    }

                    if (elementTypesBuilder.Contains(null))
                    {
                        return false;
                    }

                    elementTypes = elementTypesBuilder.ToImmutable();
                    elementNames = elementNamesBuilder.ToImmutable();
                    return true;
                }
                finally
                {
                    elementTypesBuilder.Free();
                    elementNamesBuilder.Free();
                }
            }
```

there appears to be an `else` missing when we test `expr.IsKind`. This causes the caller to attempt to produce a tuple type with an insufficient number of elements.

**Comment by AlekseyTs** [comment] 2016-11-30 05:39
It feels wrong that parser now produces single type tuple types or tuples. I believe language grammar doesn't allow such syntax. I think it should add a missing comma token and missing type/expression for the second element, this is what we do for other similar situations.

**Comment by gafter** [comment] 2016-11-30 07:48
@AlekseyTs Right you are. It is actually a bug in the IDE code. Revising the description. Tagging @CyrusNajmabadi and @jcouv who were the most recent authors of that code.

**Comment by gafter** [comment] 2016-11-30 07:56
See #15548 for the PR that skips the affected tests.

**Comment by jcouv** [comment] 2016-12-08 05:30
This issue looks like a dupe of https://github.com/dotnet/roslyn/issues/14304 (CreateTupleType API should allow for single-length tuples)

**Comment by sharwell** [comment] 2017-03-30 00:44
@gafter The tests you mentioned don't appear to actually be skipped. I'm having a hard time finding cases which produce an error. Do you have any more cases other than the following?

```csharp
void Foo()
{
    System.ValueTuple<int> y = System.ValueTuple.Create(1);
    y.Item1.ToString(); // Extract method for this line crashes the refactoring provider
}
```

**Comment by gafter** [comment] 2017-04-04 16:53
@sharwell Looking at the implementation of `TryGetTupleTypesAndNames`, it appears the missing `else` has been added, fixing this bug.

**Closed** 2017-04-07 19:55 UTC
Labels: Area-Compilers, Area-IDE, Bug, New Language Feature - Tuples
