### ISSUE TITLE
[C# Feature Request] Implicitly typed constructor calls

### ISSUE THREAD

**Issue by AustinBryan** [dotnet/roslyn#27000] opened 2018-05-20 21:34 UTC
**Instead of doing** `Dictionary<WeaponType, WeaponInformation> MyDict = new Dictionary<WeaponType, WeaponInformation>` 
**We can do this:** `Dictionary<WeaponType, WeaponInformation> MyDict = new();` **and the compiler will infer the type of the constructor to use.**

One of my favorite features from C# 7 is the new use of the `default` keyword. I love being able to just do something like:

```csharp
public struct Coord { int x, int y }
public Coord Coord = new Coord(5, 3);

public void ResetCoord() => Coord = default;
```

I'd like to do something like this for references:

```csharp
private Dictionary<WeaponType, WeaponInformation> myDict;
public Dictionary<WeaponType, WeaponInformation> MyDict=> myList ?? myList = default;
```

Except, for reference types, `default` is `null`, so this isn't getting much done, so I would have to do this: 

```csharp
private Dictionary<WeaponType, WeaponInformation> myDict;
public Dictionary<WeaponType, WeaponInformation> MyDict => myList ?? myList =
   new Dictionary<WeaponType, WeaponInformation>();
```

Which is very redundant, in the same way `default(Dictionary<WeaponType, WeaponInformation>)` used to be. 

So, my proposal, is could we instead do something like this:

```csharp
private Dictionary<WeaponType, WeaponInformation> myDict;
public Dictionary<WeaponType, WeaponInformation> MyDict => myList ?? myList = new;
```

The syntax could either by `new` or `new()`, but either way, it would just be shorthand for the current way of doing it, and the compiler would swap it out when it compiles, inferring the type from the local context. 

And, if the constructor had parameters, like:

```csharp
public Coord(int x, int y)
{
    X = x;
    Y = y;
} 
```
We could do:

```csharp
public Coord coord = new(4, 2);
```

Obviously something like:
```csharp
var coord = new(4, 2);
```
wouldn't be allowed as this would would have to be an anonymous type, and we already have a syntax for that. 

This would make code cleaner and less redundant, espically because `var` can only be used in so many places. Some of the places where this can be used to make code cleaner and shorter:
```csharp
// Before: 
public List<Dictionary<string, string>> MyBooks => myBooks ?? myBooks = 
   new List<Dictionary<string, string>>();
// After:
public List<Dictionary<string, string>> MyBooks => myBooks ?? myBooks = new();

// Before: 
PrintBooks(new List<Dictionary<string, string>>());
// After:
PrintBooks(new);

// Before:
public List<Dictionary<string, string>> MyBooks = new List<Dictionary<string, string>>();
// After:
public List<Dictionary<string, string>> MyBooks = new();
```

And yes, `PrintBooks(new)` doesn't tell the reader what type of variable `new`, but neither does `PrintBooks(default)`, but that's already in the language.

**Comment by HaloFour** [comment] 2018-05-20 21:38
https://github.com/dotnet/csharplang/issues/100

**Comment by jcouv** [comment] 2018-05-21 00:53
Indeed. Closing as duplicate of https://github.com/dotnet/csharplang/issues/100
Please continue the discussion over at csharplang (the roslyn repo is for compiler and IDE bugs, not language design). Thanks

**Closed by jcouv** 2018-05-21 00:53 UTC
