### ISSUE TITLE
Implementation of F# like "|>" pipe. 

### ISSUE THREAD

**Issue by prasannavl** [dotnet/roslyn#7736] opened 2015-12-30 16:51 UTC
F# has a "|>" pipe operator which ends being used everywhere. 
Its really nothing but a syntax sugar for reversing the order and piping (very loosely speaking)

That is, instead of 

`MeaningOfLife(AnotherFunction(SomeFunction(SomeOtherFunctionsThatTakesTheSum(Calculator.Sum(Calculator.Average(Enumerable.Range(1, 100)))))))`

one could write

```
Enumerable.Range(1, 100)
      |> Calculator.Average
      |> Calculator.Sum
      |> SomeOtherFunctionsThatTakesTheSum
      |> SomeFunction
      |> AnotherFunction
      |> MeaningOfLife
```

Its helps with the general thinking paradigm. While it really adds no value in terms of the amount of code written, the difference the syntax makes is amazingly significant, as its follows a natural mental model. And this becomes impeccable when it comes to scripting, as even non-fluent API cans be used with ease. 

And I don't even have to mention `Readability`. 

Any specific reason for C# to not borrow this from its beloved sibling?

Its a simple syntax sugar. I can't seem to think of many downsides apart from adapting the tooling.

**Comment by bondsbw** [comment] 2015-12-30 17:50
This is a duplicate of #5445

**Closed** 2016-01-03 15:11 UTC
