### ISSUE TITLE
IDE0034 C#7 v.latest: message "'default' can be simplified" is incorrect for struct

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#22962] opened 2017-11-01 20:32 UTC
In C#7 &quot;latest minor version,&quot; the suggested message &quot;'default' expression can be simplified&quot; is incorrectly given when a struct (value-type) is passed as an Object-typed function argument.

In other words, if you have...

    static void foo(Object z) { }

Then you cannot &quot;simplify&quot; the use of 'default(TimeSpan)' in the following because 'null' will be passed to the function instead of the boxed value-type.

    foo(default(TimeSpan));

This simplification is incorrectly suggested as a &quot;Message&quot; in the vs2017 Error List.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/141010/c7-vlatest-message-default-can-be-simplified-is-in.html
VSTS ticketId: 517409_
_These are the original issue comments:_

Glenn Slayden on 10/30/2017, 03:48 PM (45 hours ago): <p>In fact, the problem is quite a bit more pervasive. The incorrect suggestion <strong>IDE0034 </strong>is also given for the simple line of <strong>C#7</strong> code:</p><pre>Object x = default(TimeSpan);</pre><p>
Obviously, this is not at all the same as the simplification suggested by the vs2017 IDE...</p><pre>Object x = default;   // incorrect result of accepting suggestion IDE0034</pre><p>
In the latter case, `x` ends up as a true <em>null reference</em> (i.e. the actual binary bits in `x` are all zero), whereas in the original line (viz., prior to the incorrect application of <strong>IDE0034</strong>), `x` would end up referring to a <em>boxed value-type</em> in the GC heap.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2017-11-01 20:34
This appears to be a duplicate of #20856, which is fixed for 15.5 (Preview 1 and newer).

**Closed by sharwell** 2017-11-01 20:34 UTC
Labels: Area-IDE
