### ISSUE TITLE
Display exception explanations in tooltips

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54932] opened 2021-07-19 18:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Display-exception-explanations-in-toolti/1457858)._

---
Xml comments on C# methods in visual studio support listing the various exceptions that can occur from this function, allowing you to also input explanation of what that error is inside the exception element. This is great, except these exception comments do not display in the tooltip of function, only the exception type. I think it would be a great enhancement to display the exception comment within the tooltip.

! [image.png] (https://aka.ms/dc/image?name=B55d30304e718417890abb4c2620166e9637600082210326991_20210623-112339-image.png&tid=55d30304e718417890abb4c2620166e9637600082210326991)

---
#### Feedback Bot on 6/22/2021, 07:31 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment] 2021-07-19 18:36
Duplicate of https://github.com/dotnet/roslyn/issues/1515

**Comment by CyrusNajmabadi** [comment] 2021-07-20 05:56
Closing as a dupe.

**Closed by CyrusNajmabadi** 2021-07-20 05:56 UTC
Labels: Area-IDE, untriaged
