### ISSUE TITLE
Formatting rules ignored, indenting with spaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29682] opened 2018-09-05 20:42 UTC
Latest Visual Studio, related issues fixed, new bugs created. It will never end.

EditorConfig file is set to use tabs for indenting. Visual Studio is set up to do the same. Then open a .cs file, press Enter before an existing line and type &quot;try&quot;, press Enter. Then type &quot;{&quot; and press Enter. Now you see the line with the brace indented with spaces instead of tabs like all the lines around it, and even the line with the &quot;try&quot;.

Please fix *all* occurences of the issue that indenting happens with the wrong type, not just one in some special circumstances. There must be a single place in your code that indents new lines, and that must regard the current setting. No other code must do that in Visual Studio. Otherwise I'll still be reporting this bug in ten years.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/314320/formatting-rules-ignored-indenting-with-spaces.html
VSTS ticketId: 666159_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-09-05 20:48
Tagging @heejaechang .  Heejae, where do we need to go update to get indentation to support inserting tabs?

**Comment by heejaechang** [comment] 2018-09-06 01:13
I can't repro either. how can I follow up with the customer? I tried to write on the vso and it says I don't have permission?

**Comment by ygoe** [comment] 2018-09-06 08:31
That would be me. The original report was on Aug 17 with VS 15.8, so that was probably 15.8.0. Now I have 15.8.2 and can't reproduce it anymore. So it has probably been fixed already.

As I was asked about the project type and code language in another feedback item: I'm mostly working with (ASP) .NET Core 2.1 and C# these days. The project type sometimes makes (made) a difference on C# code formatting, especially with tabs and spaces. I can't see this being included in the feedback item. Maybe it would be a helpful addition for Visual Studio feedback to automatically capture that info.

**Comment by heejaechang** [comment] 2018-09-06 08:56
hi @ygoe thank you for the reply.

Right now, interactions with the razor is a bit messy due to the nature of the multiple languages being mixed on the same file (html/razor/script/C# or VB). 

especially when html and razor/C# is mix used like below

```
<div>
       @if (true)
      {
</div>
```

not straightforward on determining who should own formatting/indentation.  mainly due to this involves multiple parties (C# service, razor service, html service)

that being said, we are trying to clean up this messy interaction between multiple parties.

it will take some time, but we are working on it.

**Comment by ygoe** [comment] 2018-09-06 09:01
Oh, I wasn't writing a .cshtml file, just plain .cs code. I know that Razor formatting is broken to the point that it's unusable.

**Comment by heejaechang** [comment] 2018-09-06 09:03
ah.. that's interesting then... plain C# file, it shouldn't matter what project type it is...

**Comment by ygoe** [comment] 2018-09-06 10:03
@heejaechang Well, [it did](https://developercommunity.visualstudio.com/content/problem/279693/new-files-are-formatted-with-spaces-not-tabs.html). Fixed in 15.8 though. But maybe not completely, and maybe it comes back in a year or two. Most Microsoft people seem to use spaces for indenting and never test stuff with tabs.

**Comment by heejaechang** [comment] 2018-09-06 10:17
@ygoe sorry for the issue.

we do have tests to make sure our formatter works with tab correctly. but there can be always an issue somewhere that we didn't know about. 

it can be the formatter itself, or we might not be getting a right setting from option provider and get default option which is space. initial option load might got busted and not load persisted options and we end up use default option which is space and go on.

not saying so we are not going to do anything. but to do something about it, we will need some actionable data.

next time, can you provide something like repro steps or live repro solution or screenshots or video or dump or etl traces?

so we can try to repro the symptom and find out what we have broke or missed?

thank you

**Comment by ygoe** [comment] 2018-09-06 10:34
I do accept that there are bugs in software. It's just that daily productive use is often a better test case than predefined tests. I'm pretty sure that MS devs find a lot of bugs themselves just by using their products. That just doesn't include tab indenting issues because they're using spaces.

**Comment by heejaechang** [comment] 2018-09-06 11:15
@ygoe good point! can't say for whole MS, but at least the team I am working with I didn't see anyone using tab as default except when actually testing something around tab.

not sure how to increase dogfooding on tab though since many people/repo uses space as default code style..

**Comment by sharwell** [comment] 2018-09-06 11:59
@ygoe Thanks for following up 😄 

Marking as not reproducible for now.

**Closed by sharwell** 2018-09-06 11:59 UTC

**Comment by ygoe** [comment] 2018-09-11 11:57
I've just discovered another situation: There's a code fix that converts a private field with a public { get; } property into a single property. That thing also generates spaces. This time in a .NET 4.6.2. WPF project in C# code. VS 15.8.3.

**Comment by CyrusNajmabadi** [comment] 2018-09-11 17:00
@ygoe Can you open another issue on that discovery?

**Comment by ygoe** [comment] 2018-09-14 08:08
See #29879
