### ISSUE TITLE
Generated code added at cursor instead of end of file, visual basic

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#37738] opened 2019-08-05 23:41 UTC
**Version Used**: 
Visual Studio 2019 Version 16.3 Preview 1

**Steps to Reproduce**:
* In Visual Basic winforms projects you can generate the code for control events by selecting them from the right-hand navbar. (Note: I do not believe this option is available in C#)
![image](https://user-images.githubusercontent.com/8293542/62501286-000c4d00-b79f-11e9-8a1d-93eb7642dd9f.png)

**Expected Behavior**:
* Add code where cursor is in the document.

**Actual Behavior**:
* It adds the selected event control to the file at the bottom.
![image](https://user-images.githubusercontent.com/8293542/62501319-321daf00-b79f-11e9-9ec1-fed3a240c7e5.png)

Related undesired behavior when Regions are present:
https://github.com/dotnet/roslyn/issues/37339

**Suggestion**
> holding shift or Alt key while selecting the event from the drop down, or an option

**Comment by ryzngard** [comment] 2019-08-12 22:10
From Design Review: Current behavior is expected. Associating navbar actions with current cursor location is disassociated action, believed to be bad design. It's possible this could be solved with better placement of generated code, but not specifically tied to cursor. Needs a proposal to follow up.

**Comment by CyrusNajmabadi** [comment] 2024-10-20 19:56
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-20 19:56 UTC
Labels: Area-IDE, Feature Request, Need Design Review
