### ISSUE TITLE
InvalidOperationException in Microsoft.CodeAnalysis.Workspaces

### ISSUE THREAD

**Issue by MRatnam** [dotnet/roslyn#19248] opened 2017-05-04 06:06 UTC
VS2015 Update 3, v14.0.25420.1

1. Solution with 180 projects. Includes CodeAnalysis on many projects. The project is targeted at .NET 4.0 and previously worked without issue on VS2013 i.e. breaking change in Roslyn DLLs somehow. We are using Visual Studio Installer projects (i.e. compiling a .vdproj file). Probably ~ 120 projects are compiled when compiling this setup project.

> Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	devenv.exe
  Problem Signature 02:	14.0.25420.1
  Problem Signature 03:	57685d85
  Problem Signature 04:	Microsoft.CodeAnalysis.Workspaces
  Problem Signature 05:	1.3.4.60902
  Problem Signature 06:	e4ebe076
  Problem Signature 07:	278
  Problem Signature 08:	f
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.274.10
  Locale ID:	3081
  Additional Information 1:	7ab1
  Additional Information 2:	7ab131621a761fc79cfaad315b44af76
  Additional Information 3:	8e52
  Additional Information 4:	8e52f085ac7444f7bef020015eb0b172

I am not able to bundle source code samples due to a) size of solution, b) 3rd party control license dependencies, c) commercial confidence however can run tests/diagnostics as required.

**Comment by Pilchie** [comment] 2017-05-04 16:18
@MRatnam - can you see if:

1. There is a .NETRuntime event in your event log near that time?
2. There is a bucket id or failure hash in a Windows Error reporting event?

Also, if you could capture and share a crash dump (which will be big!), that would help too.  You should be able to get Windows Error Reporting to save full crash dumps locally for VS by adding the following to your registry:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\devenv.exe]
"DumpFolder"="C:\\Crashdumps"
"DumpCount"=dword:00000010
"DumpType"=dword:00000002
```

Thanks!

**Comment by Pilchie** [comment] 2017-05-04 16:19
Note - I can provide a OneDrive for Business shared folder to upload the dump to if you can capture one.  Go ahead and email me at kevinpi@microsoft.com

**Comment by MRatnam** [comment] 2017-05-04 23:12
I found this in Event Viewer. I also have a OneDrive for Business company account so should be able to provide that crash dump.

> Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32 cookie)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(Object sender, EventArgs e)
   at Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()
   at Microsoft.CodeAnalysis.Workspace.<>c__DisplayClass199_0.<RegisterText>b__0()
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass2_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass6_0`1.<SafeContinueWith>b__0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Shell.Interop.IVsRunningDocumentTable4.GetDocumentMoniker(UInt32)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace.Registration_WorkspaceChanged(System.Object, System.EventArgs)
   at Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents()
   at Microsoft.CodeAnalysis.Workspace+<>c__DisplayClass199_0.<RegisterText>b__0()
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__1(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass2_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Thanks very much for looking into this and the fast response.

**Comment by Pilchie** [comment] 2017-05-04 23:19
Tagging @jmarolf and @jasonmalinowski.  This looks like the issue fixed by https://github.com/dotnet/roslyn/pull/14783.  Did that make it into any VS2015 releases?

@MRatnam can you confirm that you're seeing this when you build on the command line with something like `devenv /build`?

**Comment by jasonmalinowski** [comment] 2017-05-04 23:39
```
>git tag --contains d0cd0e2c427e9a784f84c9c940be90f1a15e5039
Visual-Studio-2017
Visual-Studio-2017-RC3
Visual-Studio-2017-RC4
Visual-Studio-2017-Update-1
version-2.0.0
version-2.0.0-rc3
version-2.0.0-rc4
version-2.1.0
```

So no, 2017 only.

**Comment by MRatnam** [comment] 2017-05-05 00:09
@Pilchie Yes I can confirm this is when running via commandline `devenv /build`

**Comment by Pilchie** [comment] 2017-05-05 00:33
It sounds like using VS2017 is your best option then.

Resolving as a duplicate of https://github.com/dotnet/roslyn/issues/15134.

**Closed by Pilchie** 2017-05-05 00:33 UTC
Labels: Area-IDE, Bug, Tenet-Reliability

**Comment by MRatnam** [comment] 2017-05-05 00:41
@Pilchie Unfortunately we are unable to use VS2017 due to legacy components which are not supported. Our customers are large corporations with 5 year update cycles and we would not be in a position to update to VS2017 for probably around 12-24 months.
Is there a workaround for builds we can apply to VS2015?

**Comment by MRatnam** [comment] 2017-05-07 23:46
Shared crashdump via OneDrive to Kevin.

**Comment by Pilchie** [comment] 2017-05-08 16:01
We'll take a look at the crashdump to confirm it's the same issue.

For VS2015, if you have a support contract, you can talk to your contact about a requesting a hotfix, but we don't otherwise have a mechanism for shipping fixes for VS2015 right now.

**Comment by MRatnam** [comment] 2017-05-09 06:04
Ok thanks I'll chase that option up.

**Comment by Pilchie** [comment] 2017-05-09 18:25
I get a 404 when I try to access the OneDrive link you sent to me :-/

**Comment by Pilchie** [comment] 2017-05-10 03:03
Got the dump file, and it does indeed look like the same issue.  From the event log above, it was crashing [here](https://github.com/dotnet/roslyn/blob/version-1.3.1/src/VisualStudio/Core/Def/Implementation/ProjectSystem/MiscellaneousFilesWorkspace.cs#L218), but the dump is crashing on the previous [line](https://github.com/dotnet/roslyn/blob/version-1.3.1/src/VisualStudio/Core/Def/Implementation/ProjectSystem/MiscellaneousFilesWorkspace.cs#L217), which indicates that something is indeed racing and the document is getting removed from the RDT.

**Comment by MRatnam** [comment] 2017-05-10 05:16
Thanks for confirmation. I'll chase up with support.

**Comment by MRatnam** [comment] 2017-07-14 18:15
Just confirming MS is making a patch available for VS 2015 - VS14-KB3217593.exe
