### ISSUE TITLE
Incorrect caching of delegates inside lambdas inside generic local functions (or something like that)

### ISSUE THREAD

**Issue by andreasstolpmann** [dotnet/roslyn#53669] opened 2021-05-25 13:40 UTC
I'm not 100% sure that this actually a bug.  Also i don't know if it is a compiler problem. It is, however, very weird behavior and I'm hoping to get some help here.

**Version Used**: 
PS > dotnet --version
5.0.100

**Steps to Reproduce**:
```
public class A { }

public class B { }

public class Item
{
    public Func<Task> F { get; set; }
}

public class Program
{
    public static async Task Main(string[] args)
    {
        var p = new Program();
        p.CreateItems();

        foreach (var item in p.Items)
        {
            await item.F();
        }
    }

    public List<Item> Items { get; } = new List<Item>();

    public void CreateItems()
    {
        Item Create<T>()
        {
            return new Item
            {
                F = () =>
                {
                    return Task.Run(() =>
                    {
                        Console.WriteLine(typeof(T).Name + " " + Items.Count);
                    });
                }
            };
        }

        Items.Add(Create<A>());
        Items.Add(Create<B>());

        var item = new Item();
        item.F = () =>
        {
            item.F = null;
            return Task.CompletedTask;
        };

        Items.Add(item);
    }
}
```

**Expected Behavior**:
*Console Output:*
``` 
A 3
B 3
```
**Actual Behavior**:
*Console Output:*
```
A 3
A 3
```

This only happens in this exact combination of features:
* local function 
* async (If i change Func<Task> to Action everything is fine)
* Access to `this` from within the `Task.Run` part (In this case `Items.Count`)
* Access to `item`from within `item.F`

If "B"s function is called first the output is stuck with more "B"s. So it seems to me like one of the lambdas is reused despite being part of of different methods.

I'm happy to provide more feedback if you have any questions.

**Comment by svick** [comment] 2021-05-25 14:31
I think this is a bug caused by incorrect caching of delegates inside lambdas inside generic local functions (or something like that).

Consider this simplified example:

```c#
using System;

class A { }

class B { }

class Program
{
    static void Main()
    {
        var p = new Program();
        p.InvokeItems();
    }

    void InvokeItems()
    {
        Func<Action> Create<T>() => () => () => Console.WriteLine(typeof(T).Name + " " + this);

        Create<A>().Invoke().Invoke();
        Create<B>().Invoke().Invoke();

        int i = 42;
        Func<int> f = () => i;
    }
}
```

Here, [the lambda that produces the `Action` decompiles into](https://sharplab.io/#v2:D4AQTAjAsAUL4AICCCDeCC+t5gQITU2xkRAgHZZVYFaEyA2egFgQFkBDASwDsAKAJQ061GHXEIAbhwBOCAA4IAvAh4BTAO70KggNzCJCgHQBJHpID2AazUmALmoC2AZz0GicMXRCszlm/ZOrkJetKKGtCAArAA8ZGAAfAgAwjJqHA4xACoJgspJeUoFAvnaAJx8dgCe8moWAGZ8WQJGAHIcjmoIANQIAET9PQh2ABZczgL6nhEpaRlqMUi5LX7WaoKm5mtuoRKp6Zl4y5v+6ytbNjvu4rx2CFzKCMxgUzPRMbdJ9Y+FSVyvdCwMAwQA=):

```c#
internal Action <InvokeItems>b__2<T>()
{
    return <>9__3 ?? (<>9__3 = new Action(<InvokeItems>b__3<T>));
}
```

Notice that if there is a cached value for the `Action`, it is returned, even if the `T` does not match.

A modified version of this code can also cause `BadImageFormatException`:

```c#
using System;

class A { }

class B { }

class Program
{
    static void Main()
    {
        var p = new Program();
        p.InvokeItems();
    }

    void InvokeItems()
    {
        Func<Func<T>> Create<T>() => () => () =>
        {
            Console.WriteLine(this);
            return Activator.CreateInstance<T>();

        };

        Create<A>().Invoke().Invoke();
        Create<B>().Invoke().Invoke();

        int i = 42;
        Func<int> f = () => i;
    }
}
```

This throws:

```
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at Program.<>c__DisplayClass1_0.<InvokeItems>b__2[T]()
   at Program.InvokeItems() in C:\code\tmp\coreapp\Program.cs:line 24
   at Program.Main() in C:\code\tmp\coreapp\Program.cs:line 12
```

**Comment by andreasstolpmann** [comment] 2021-05-25 14:54
Thank you for that. I edited the title (using your words) to better reflect the problem.

**Comment by RikkiGibson** [comment] 2021-05-25 18:02
Possible duplicate of #44720?

**Comment by jaredpar** [comment] 2021-06-14 15:00
Agree this is a duplicate. Can verify that now that the fix is in the program completes correctly.

https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBUQAQCC1A3tQL4VWHUBCjLb5N+YgHYKDCtQnVBANikAWagFloMABQBKagF4AfNRgBTAO5ThGgHQBJGADcA9gGsDlhAbABnDQG4+k+dWt7Jxc3T3VxSTFyPz98AFYAHniEgBUdPQBhZAMIV1SdDW09Qt1qEp0ImMZKqslBAE5VBAALKHd1H2ja2KFqDAMAMwhUABsETu7mTpq/LJy82gL1K1tHAwtAte8ZyTncgwTOJZWg9eXNp23KLqrYBGoobWo5Qgna5Lu9Aafyh7eJVjkZhAA

**Closed by jaredpar** 2021-06-14 15:00 UTC
Labels: Area-Compilers, untriaged
