### ISSUE TITLE
DiagnosticData_GetText6 is failing in unit tests:

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20585] opened 2017-06-30 22:35 UTC
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/7629/consoleFull#-5160889422d31e50d-1517-49fc-92b3-2ca637122019

**Comment by CyrusNajmabadi** [comment] 2017-06-30 22:35
Tagging @heejaechang

**Comment by heejaechang** [comment] 2017-06-30 22:47
looks like some issue in TestWorkspace. same for all other tests.

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/7629/artifact/Binaries/Release/UnitTests/EditorServicesTest/xUnitResults/Roslyn.Services.Editor.UnitTests.dll.out.log

...
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticDataTests.DiagnosticData_GetText6
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test\Diagnostics\DiagnosticDataTests.cs(118,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticDataTests.<VerifyTextSpanAsync>d__9.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        q:\roslyn\src\EditorFeatures\Test\Diagnostics\DiagnosticDataTests.cs(75,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticDataTests.<DiagnosticData_GetText6>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by Pilchie** [comment] 2017-07-03 18:58
Dupe of https://github.com/dotnet/roslyn/issues/20370.

**Closed by Pilchie** 2017-07-03 18:58 UTC
