### ISSUE TITLE
Incorrect IDE0004 'Cast is redundant' on switch expression

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#42657] opened 2020-03-21 16:36 UTC
**Version Used**: VS 16.6-p1

There should be no prompt to remove the enum cast. Removing it would change the exception message.

`_` indicates faded text:

```cs
class C
{
    object M(int rawKind)
    {
        // ℹ IDE0004 Cast is redundant
        //     ____________
        return (SyntaxKind)rawKind switch
        {
            var kind => throw new NotImplementedException(kind.ToString()),
        };
    }
}
```

**Comment by jnm2** [comment] 2020-03-21 16:49
Here's a case where it shows up and performing the prompted removal breaks the compilation:

`_` indicates faded text:

```cs
class C
{
    object M(int rawKind)
    {
        // ℹ IDE0004 Cast is redundant
        //     ____________
        return (SyntaxKind)rawKind switch
        {
            CSSyntaxKind.BoolKeyword => 42,
        };
    }
}
```

**Comment by sharwell** [comment] 2020-03-30 01:53
Duplicate of #37953

**Closed** 2020-03-30 01:58 UTC
Labels: 4 - In Review, Area-IDE, Bug, IDE-CodeStyle
