### ISSUE TITLE
Nullability constraint warnings are not reported for method signatures

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#32539] opened 2019-01-16 22:23 UTC
No warnings reported for `C<object?>` in method signatures:
```C#
class C<T> where T : class
{
}

class Program
{
    static C<object?> F1() => throw null;

    static void F2(C<object?> c) { }
}
```

**Comment by jaredpar** [comment] 2019-02-08 21:10
Dupe of #32953

**Closed by jaredpar** 2019-02-08 21:10 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
