### ISSUE TITLE
Toggle Block Comment does not behave as expected

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#37580] opened 2019-07-30 17:59 UTC
[Original customer feedback on developer community](https://developercommunity.visualstudio.com/idea/589032/feature-add-in-reverse-comments-key-sequence.html)

**Version Used**: 
Visual Studio 2019 version 16.3 Preview 1

**Steps to Reproduce**:

1. Have multiple lines of code, one commented some uncommented:
```csharp
Console.WriteLine("Hello World 1");
//Console.WriteLine("Hello World 2");
```
2. Toggle Block Comment/Uncomment - (Ctrl+Shift+/)

**Expected Behavior**: Toggle the comment
```csharp
//Console.WriteLine("Hello World 1");
Console.WriteLine("Hello World 2");
```
**Actual Behavior**:
```csharp
/*Console.WriteLine("Hello World 1");
//Console.WriteLine("Hello World 2");*/
```

I believe this was a diversion from the original customer ask back when we started implementing the toggle comment commands as users can already use (Ctrl K, C) to comment the selection. Toggle block comment was meant to toggle the selection.

**Comment by dibarbet** [comment] 2019-07-30 19:31
2 general comments on this
1.  The command is specifically for toggle block comment, so it only acts on block comments.  I think it would be undesirable for this to also act on line comments, that would be a bit confusing.  So since nothing in the selection was commented in a block comment, there are no block comments to remove, so it adds a block comment.
As an aside, perhaps it would be worth discussing if a general "toggle comment" command that acts on all comments would be useful.
2.  During the design review for https://github.com/dotnet/roslyn/issues/34734 we did discuss swapping the commented areas, but we landed on just adding to the commented area.  See the "Adding single line comment(s)" section number 5.  IIRC we felt that when someone invoked toggle line comment on this selection
```cs
var i = 1;
var j = 2;
//k must be one less than the sum.
var k = i + j - 1;
```
that doing this would be a bad experience:
```cs
//var i = 1;
//var j = 2;
k must be one less than the sum.
//var k = i + j - 1;
```
The thought was that the user likely wanted the entire selection commented in this case.

**Comment by dibarbet** [comment] 2019-07-30 19:34
@kendrahavens 
As such I'd propose resolving this one by design (toggle block comment is behaving as expected), and/or edit this issue/create a new issue if we think that a command to reserve the commented areas would be useful.

**Comment by sharwell** [comment] 2019-07-31 00:03
Yes, the feature is behaving as designed. Operations on line comments can either use the **Uncomment Selection** command or the **Toggle Line Comment** command.

**Closed by sharwell** 2019-07-31 00:03 UTC
Labels: Area-IDE, Bug, Resolution-By Design
