### ISSUE TITLE
Incorrect 'name can be simplified' [replaces with var] 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#27210] opened 2018-05-28 16:24 UTC
1. Create new C# .NET Framework project.
2. Paste the following code:

```csharp
using System.Collections.Generic;

namespace N
{
    class Program
    {
        static void Main(string[] args)
        {
            var doubleList = new List&lt;double&gt;();
            foreach (var q in doubleList)
            {
            }
        }
    }
}
```

3. Notice that `doubleList` in `foreach` is greyed out.
4. Ivoke 'Quick actions' menu on it (Ctrl+.)
5. Notice that it suggests &quot;Simplify name 'doubleList'&quot;.
6. Accept the suggestion, notice that `doubleList` is replaces with `var` and the code now is invalid.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/258678/incorrect-name-can-be-simplified.html
VSTS ticketId: 620703_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Neme12** [comment] 2018-05-28 16:27
duplicate of #26923

**Comment by sharwell** [comment] 2018-05-28 16:57
Duplicate of #26923

**Closed by sharwell** 2018-05-28 16:57 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
