### ISSUE TITLE
Analyzer installation script fails to add assemblies with different versions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#6322] opened 2015-10-26 17:43 UTC
In sharwell/StyleCopAnalyzers@ca42b3ef1f7f5fb2beaaf774eb64d78423b1ac77, I made our analyzer assembly depend on _both_ Newtonsoft.Json 6.0.0.0 and Newtonsoft.Json 7.0.0.0. If either assembly fails to load with that specific version, half the analyzers which use stylecop.json will fail. (This branch simulates the behavior of multiple analyzer packages which depend on different versions of a common dependency, a requirement which has already appeared in DotNetAnalyzers/StyleCopAnalyzers#1624.)

When I installed the updated package (sharwell/StyleCopAnalyzers@da335ecf29eebd7e5c8daf9dfe437abdd209dcc5), you can see that the installation script failed to add both references to Newtonsoft.Json, even though they were [both present](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/StyleCop.Analyzers.nuspec#L25-L26) in the .nupkg file. As expected, a large number of warnings were reported in the IDE regarding failure to load analyzers. However, when I manually added the second reference (sharwell/StyleCopAnalyzers@557cac876e5666b109c30ef80970acff5b6d23ca), everything worked.

It looks like this is a bug in either the [installation script](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/tools/install.ps1) (which is pulled from straight from Roslyn) or in the project system.

**Comment by mavasani** [comment] 2015-10-26 18:13
Tagging @jmarolf, he is the expert on the installation script in the analyzer + codefix project. Jon, if you feel this is by design for the install script, it may be a bug on the nuget team or our project system.

**Comment by jessehouwing** [comment] 2015-10-26 18:59
When you manually add a reference to a newer assembly in the IDE (manually browse from the add analyzers submenu)  it replaces all rreference to that assembly with the one selected. 

In the IDE it would be much easier to understand if the dependent assemblies are listed under the actual analyzer like a designer.cs is  hidden under the user code file, or hidden altogether.

**Comment by jmarolf** [comment] 2015-10-26 19:48
@tmeschter Since he is the master of analyzer loading, and correct me if I am wrong here.

Its not that the analyzer fails to add the two assembles, its that the CLR thinks its already added and so it skips loading it.

**Comment by sharwell** [comment] 2015-10-26 19:57
@jmarolf 

> Its not that the analyzer fails to add the two assembles, its that the CLR thinks its already added and so it skips loading it.

The CLR has no trouble loading two different versions of the same dependency side-by-side. The example branch I was working in *required* the CLR do this, and it had no problem doing so both inside Visual Studio and for command line builds. The only problem is that the default installation script only results in one of the two required dependencies being declared in the project file. The other one had to be added by hand before the build would work.

**Comment by jmarolf** [comment] 2015-10-26 20:06
We add the assemblies in the root directory on [Line 14](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/tools/install.ps1#L14) and for the language specific assemblies on [Line 45](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/tools/install.ps1#L45).  @tmeschter do you have any ideas why the project system would ignore this?

**Comment by Pilchie** [comment] 2015-10-27 16:35
Tagging @davkean

**Comment by tmeschter** [comment] 2015-10-27 16:55
Since it works if the project files are updated by hand, my guess is an issue with the call to `AnalyzerReferences.Add` on [Line 14](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/tools/install.ps1#L14) or [Line 45](https://github.com/sharwell/StyleCopAnalyzers/blob/json6-concept/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/tools/install.ps1#L45).

That is, the problem may lie in the extensibility point and/or how it interacts with the project system, rather than with the project system itself.

**Comment by tmeschter** [comment] 2016-11-03 16:53
Oooookay, we really need to stop kicking this one down the road. It shouldn't be _that_ hard.

Things to consider:

1. The legacy project systems (csproj.dll/msvbprj.dll) probably check if the analyzer already exists by comparing just the file name, rather than the full path. This was probably lifted from the code for adding regular references, and was a reasonable choice when we thought we were going to pass analyzer dependencies to the compiler separate from the analyzer assemblies themselves. Anyway, it should be an easy change.
2. We need to check that the Workspace layer doesn't identify analyzer assemblies solely by their simple name, or things may go nutty when multiple items with the same name show up.
3. We need to check the VS layer as well. In particular, we need to make sure we don't break Solution Explorer support (including support for setting severity through the context menu), or rule set editor support.

**Comment by CyrusNajmabadi** [comment] 2024-11-05 20:17
Closing out due to lack of movement.

**Closed by CyrusNajmabadi** 2024-11-05 20:17 UTC
Labels: Bug, Area-IDE
