### ISSUE TITLE
C# Automatic String Interpolation Syntax "$"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63077] opened 2022-07-29 21:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Automatic-String-Interpolation-Syntax/10097147)._

---
This feature would automatically add"$" to the beginning of the double quotes.

Currently, if I type and opening double-quote, it will automatically append the closing double-quote

It would be nice if it would automatically add "$" to the beginning, as it does with the closing double quotes.

---
#### Feedback Bot on 7/18/2022, 00:26 AM: 

(private comment, text removed)

**Comment by sharwell** [comment] 2023-02-07 16:58
Duplicate of #53996

**Closed** 2023-02-07 17:06 UTC
Labels: Area-IDE, Feature Request, Need Design Review
