### ISSUE TITLE
IDE: Suppress warning is not available for multiple warning types

### ISSUE THREAD

**Issue by omghb** [dotnet/roslyn#63793] opened 2022-09-03 12:09 UTC
Visual Studio version: Visual Studio 2022 (17.3.2)

Visual Studio allows to suppress warnings (e.g. CA warnings) in Source or Suppression File. This works for some warnings but not for all.

I have created a GitHub repo to demonstrate this issue: https://github.com/omghb/VSSuppressInFileIssue

**Comment by Youssef1313** [comment] 2022-09-03 14:41
I didn't clone the repo, but from the screenshots it looks like the exact warning that you cannot suppress via lightbulb is CA1812?

CA1812 is a compilation-end analyzer, and it's (unfortunately) by-design that code actions for such analyzers are not calculated via lightbulb for performance reasons.

**Comment by omghb** [comment] 2022-09-03 14:58
In the provided sample project (repo) it is not possible to suppress CA1812 or CA5399 via lightbulb. 

Because of that it is not possible to suppress them with Visual Studio at all. In older Visual Studio versions it was possible to suppress warnings via Error List view but that's not working anymore.

This should just be an example. In our production code we set:
```xml
<AnalysisLevel>latest-all</AnalysisLevel>
```

But then a lot warnings pop up which cannot be suppressed via Visual Studio. Or is there another way than using the lightbulb to perform a suppression?

**Comment by Youssef1313** [comment] 2022-09-03 15:15
@omghb CA5399 too is a compilation-end analyzer:

https://github.com/dotnet/roslyn-analyzers/blob/a26d1a203d0116aa769bce0fd3a917cc70d88a66/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotDisableHttpClientCRLCheck.cs#L26-L34

- Not being able to suppress them via Error List is probably a bug, @mavasani do you know?
- Not being able to suppress them via lightbulb is by-design as far as I know.

**Comment by mavasani** [comment] 2022-09-03 16:13
@Youssef1313 both of them are by design.

**Comment by omghb** [comment] 2022-09-05 06:31
@Youssef1313 I understand that the lightpulb feature is critical to performance. But if **compilation-end analyzer** warnings cannot be suppressed at all with the Visual Studio IDE then this is a bug for me.

**Comment by Youssef1313** [comment] 2022-09-05 08:18
@omghb You should be able to suppress it by `.editorconfig`:

```ini
[*.cs]

# CA1812: Avoid uninstantiated internal classes
dotnet_diagnostic.CA1812.severity = none

```

**Comment by omghb** [comment] 2022-09-05 08:59
@Youssef1313 We use the approach with `.editorconfig` if we want to suppress warning types on a solution/project level.

But, we want to suppress single warning instances as well. We do this with the generated `SuppressMessage` attribute. And this is not possible with Visual Studio for the **compilation-end analyzer** warnings.

A lot of the `advanced` analyzer warnings are helpful but they are not smart enough to understand the code in their context. So we enable them. When we get a warning we review the affected code and decide if we want to suppress this single warning or not.

**Comment by Youssef1313** [comment] 2022-09-05 09:26
You can add `#pragma warning disable CA1812` above the line where you get the diagnostic and `#pragma warning restore CA1812` below the same line to disable a single warning instance.

If you want to manually add `SuppressMessage` attribute, that should work too.

**Comment by omghb** [comment] 2022-09-05 09:44
Our coding style tells us to avoid suppressions directly within the code as it adds additional lines which might distract from the implementation itself. So we avoid using `#pragma warning disable` and avoid putting the `SuppressMessage` attribute directly to the member.

Our approach is using the `GlobalSuppressions.cs` file that contains following lines (generated by Visual Studio):
```C#
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:VSSuppressInFileIssue.Demo.GetData(System.Uri,System.String)~System.Threading.Tasks.Task{System.String}")]
```

Writing these lines ourselves is very difficult because of the Target syntax.

**Comment by CyrusNajmabadi** [comment] 2022-09-05 15:41
> Our coding style tells us to avoid suppressions directly within the code as it adds additional lines which might distract from the implementation itself

Generally, we don't make changes to workaround arbitrary policy decisions that prevent using an existing viable option. That policy rule can always be relaxed.

**Comment by omghb** [comment] 2022-09-06 06:08
In the past (ok, quite some years ago 😃) it was possible to suppress **ALL** CA warnings in Visual Studio by using the `GlobalSuppression.cs` file. Nowadays, it still provides this suppression feature which works only for some of the warnings. In my opinion this is inconsistent and not understandable for us users/customers.

**Comment by mavasani** [comment] 2022-09-06 06:15
> @Youssef1313 I understand that the lightpulb feature is critical to performance. But if **compilation-end analyzer** warnings cannot be suppressed at all with the Visual Studio IDE then this is a bug for me.

Note that the all warnings **can** be suppressed by all of the supported suppression mechanisms: pragmas, global suppress message attributes and local suppress message attributes. The only part that is missing currently is tooling support that automatically generates one of these suppressions for you from the error list.

> In the past (ok, quite some years ago 😃) it was possible to suppress ALL CA warnings in Visual Studio by using the GlobalSuppression.cs file

This is still true today. We have tooling support to auto-generate this for most warnings. For the build-only diagnostics from the compiler and compilation-end analyzers, you can manually add these attributes and the diagnostic will be suppressed.

**Comment by mavasani** [comment] 2022-09-06 06:16
We already have an existing feature request for the tooling support requested here: https://github.com/dotnet/roslyn/issues/50035.

Closing this as a duplicate.

**Closed by mavasani** 2022-09-06 06:16 UTC
Labels: Area-Compilers, untriaged
