### ISSUE TITLE
Wrap argument code action not showing with target-typed new

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#52906] opened 2021-04-25 21:38 UTC
**Version Used**: VS 16.9.4

**Steps to Reproduce**:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            Program p1 = new(1, 2);
        }

        public Program(object o1, object o2) { }
    }
```

1. Hit ctrl+. on the arguments in the target-typed new.

**Expected Behavior**:

Wrap argument quickfix is shown

**Actual Behavior**:

No quickfix is shown.
![image](https://user-images.githubusercontent.com/2371880/116010446-d8dd5b00-a5d3-11eb-8b8c-545d5eaedfb5.png)

**Comment by Youssef1313** [comment] 2021-04-26 05:06
Duplicate of https://github.com/dotnet/roslyn/issues/50104

**Comment by jcouv** [comment] 2021-04-26 05:41
Closing as duplicate of #50104. Thanks @Youssef1313

**Closed by jcouv** 2021-04-26 05:41 UTC
Labels: Area-IDE, untriaged
