### ISSUE TITLE
VS 2017 RC - move type to file bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32428] opened 2019-01-13 10:27 UTC
Using the IDE feature move type to file on Form2 erroneously brings the #endregion directive surrounding a separate class above it. After the feature runs the code no longer compiles because of the broken regions. See attached screenshot.
![image](https://user-images.githubusercontent.com/12449387/51084211-f1632900-16da-11e9-8ee5-8c818b6e7842.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/14922/vs-2017-rc-move-type-to-file-bug.html
VSTS ticketId: 419697_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-01-14 18:53
Possible duplicate of #19613 and/or #23723

**Comment by nnpcYvIVl** [comment] 2019-01-15 00:20
@sharwell The referenced code in this ticket starts as valid but after the refactor fails to compile with a CS1038 #endregion directive expected. #23723 starts with code that doesn't compile and #19613 is marked as fixed in 15.3 except for formatting so perhaps this should be considered a unique issue?

```csharp
using System.ComponentModel;
using System.Windows.Forms;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        #region Stuff
        static class Stuff
        {

        }
        #endregion

        [DesignerCategory("")]
        class Form2 : Form
        {

        }
    }
}
```

**Comment by ryzngard** [comment] 2020-01-17 23:29
Moving to backlog. This is definitely worth fixing, but is not a critical bug.

**Comment by sharwell** [comment] 2022-01-04 23:41
Duplicate of #19613

**Closed by sharwell** 2022-01-04 23:41 UTC
Labels: Bug, Area-IDE, Developer Community
