### ISSUE TITLE
we need to decide order how we search operation from operation tree

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22180] opened 2017-09-18 20:46 UTC
right now, we traverse tree in preorder and return first IOperation that is explicit and point to same syntax node as the given node to GetOperation.

we probably need to decide exact order on how we search the given node in GetOperation.

...

we also need to decide order, IOperation.Children returns and IOperation.Decendants() returns.

**Comment by heejaechang** [comment] 2017-09-18 20:58
related to https://github.com/dotnet/roslyn/pull/21857

**Comment by heejaechang** [comment] 2017-09-18 21:16
related to #22020

**Comment by jinujoseph** [comment] 2017-09-18 22:10
@dotnet/analyzer-ioperation , tagging for discussion to take it for design meeting

**Comment by mavasani** [comment] 2017-09-21 23:28
Design decision: : Ensure Children are returned in **evaluation order**, not the *lexical order*. We should try to find cases where evaluation orders differ in languages for same construct, and bring such cases back for discussion to confirm the selected approach.

**Comment by jinujoseph** [comment] 2017-09-27 22:56
dupe of https://github.com/dotnet/roslyn/issues/22020

**Closed by jinujoseph** 2017-09-27 22:56 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
