### ISSUE TITLE
Roslyn serialize and deserialize trees while code cleanup consuming a lot of CPU

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#28621] opened 2018-07-17 19:31 UTC
more detail here
https://github.com/dotnet/roslyn/issues/28012#issuecomment-402867427

if we can do something to get rid of serializing and deserializing of a tree while code clean up, we should do that.

**Comment by heejaechang** [comment] 2018-07-17 19:34
we might need to add something like Solution.DisablePersistingTree so that tree never get serialized/deserialized to disk.

**Comment by sharwell** [comment] 2018-07-18 05:03
Deserialization only occurs if the tree is not available in memory, and the tree is only not available in memory if the WeakReference was collected by a compacting GC. Disabling persistence in this case has a high likelihood of resulting in OOM crashes.

**Comment by sharwell** [comment] 2018-07-18 05:04
> if we can do something to get rid of serializing and deserializing of a tree while code clean up, we should do that.

The one real option here is running Code Cleanup exclusively out of process, where we have 64-bit address space available.

**Comment by CyrusNajmabadi** [comment] 2018-07-18 06:39
> The one real option here is running Code Cleanup exclusively out of process, where we have 64-bit address space available.

I would very much like to see this done.  It's always been a bit unclear to me why we're doing anything diagnostic/fix related in-proc *except* where it is mandated because we need access to some sort of VS-only service.

On top of the benefits mentioned here, there's also the very real and significant benefit to VS by greatly reducing GC pressure, manifesting in much better editor latency and user responsiveness.

--

Ideally, for me, the only thing we'd have to do in-proc would be anything that needs a VS service.  Or, anything with such tight latency concerns that even the overhead of OOP would be a concern.  That latter category itself is exceedingly small, and 'Completion' is the only feature i suspect might be in it.

Moving Code-Cleanup and the rest of these features OOP would greatly decrease the in-situ footprint and help out VS.

**Comment by heejaechang** [comment] 2018-07-18 19:00
for this particular code clean up case, the solution is temporary, and it is not 1 solution having multiple documents changed which can potentially have a risk of OOM like rename, but multiple solutions, 1 document changed which won't increase the possibility of OOM since it go away as solution go away. for this particular case, persisting is actually waste of resource since new tree will be needed right away and after that no one will ever need it again.

...

unfortunately, OOP is 32 bit, we did AB testing to do 64bit which uses about 40% more memory and got killed by perf people. I will have another chance to push it soon thank for changing opinion around scalability vs VM usage. probably will end up OOP will become dynamic (meaning, VS might not have OOP or 32bit OOP or 64bit OOP) depends on a solution. but anyway, I dont know. but currently, it is 32bit.

...

there is marshaling cost of moving anything to OOP. for example, navigate to and find all reference, both in wild results, slower when running in VS. reason is even if actual running time is roughly same in both VS and OOP, OOP case it has cost of moving data between 2 process. and that makes OOP more slower. sure we can make those binary data form or ignore since number is not that big, but still slower. and right now, that is reason they get rejected to be on by default.

...

anyway, I still believe there is a merit to have a way to turn off tree serialization on a solution since in certain case, tree serialization is just waste.

**Comment by heejaechang** [comment] 2018-07-18 19:04
or we can ignore and just leave it as it is. if persistence is still there, it doesn't matter where it runs, it will still do serialization/deserialization and allocations and GC can run.

same argument I had for navigate to, find all references, cost is there but I dont think it is big enough to block things.

**Comment by CyrusNajmabadi** [comment] 2018-07-18 19:33
> OOP case it has cost of moving data between 2 proces

This cost is virtually non-existed for NavTo or FAR.  Both of those *only* stream over their results.  Which is basically tiny.  Even if thousands of results are returned, that's usually < 1mb, which is virtually instantaneous to send to/from OOP.  Again, this was actually measured and validated as part of the original OOP work.  So if transfer time is a problem now, then something has changed.

--

Also, we know that this sort of thing isn't actually bad because we have other LSs that not only do marshalling, but they do marshalling *twice.  i.e. when you're in typescript, we have to marshall to/from typescript (i.e. managed-to-js marshalling) *and* TS also has an OOP server.  So then they have to marshall from JS-in-proc to JS-out-of-proc.  Performance is totally fine and the costs of marshalling aren't relevant in the final times (which are dominated by the actual search time). 

It was very intentional in the design of these features that we weren't being chatty or sending over tons of data.  Instead, the request is simply sent over as a simple message. The other side computes the result (and does all the expensive stuff over there), and then just sends the result back as a cheap blob to be presented in the UI.

**Comment by CyrusNajmabadi** [comment] 2018-07-18 19:34
> anyway, I still believe there is a merit to have a way to turn off tree serialization on a solution since in certain case, tree serialization is just waste.

To start with... why serialize trees for the active project?  That just seems strange.  Basically it means that almost any request to the compilation that needs to go look at data in the project will cause this perf hit...

**Comment by heejaechang** [comment] 2018-07-18 19:44
you can try yourself. get trace between in VS and in OOP and compare. running features cost is roughly same. OOP case has cost of sending data over between 30-100ms depends on how much data it needs to send over. most of cost is in json conversion, so we could improve it by moving to binary form, but that's based on if we really care on those cost.

I looked old and new A/B testing result. result is same. both of them OOP is slower with about same 
 amount 30-100ms.

...

you don't need to convince me whether it is totally fine or not. I am at the side where this tree serialization is totally fine as well. including running nav and far on OOP. or running OOP on 64bit paying 40% more VM.

...

anyway, whether we need to tweak our tree serialization behavior or not, @sharwell  is our perf champ, so discuss with him on core architectural changes. and propose or make a prototype with data backing up that it is better than the existing one and present to the team and I guess team or @jinujoseph will decide whether the improvement is worth enough to take a risk on changing core part of Roslyn.

**Comment by heejaechang** [comment] 2018-07-18 19:53
I am saying this 

> you don't need to convince me whether it is totally fine or not. I am at the side where this tree serialization is totally fine as well. including running nav and far on OOP. or running OOP on 64bit paying 40% more VM.

since nobody. I mean nobody noticed (including complaining or talking about it) it while we silently test it by turning things on by default (99% on in A/B testing)

only people who looked matrix (such as trace or A/B scorecard or perf telemetry dashboard) can notice it. 

as long as numbers are in interaction class, I believe most people will never notice such things.

**Comment by CyrusNajmabadi** [comment] 2018-07-18 19:56
> I looked old and new A/B testing result. result is same. both of them OOP is slower with about same
amount 30-100ms.

30-100ms is literally irrelevant when it comes to a feature like NavTo or FAR.  :D

 100ms is already 1/3rd the cost to blink your eyes.   30ms is 1/10th the speed to blink.  :D 

> you don't need to convince me whether it is totally fine or not. I am at the side where this tree serialization is totally fine as well. including running nav and far on OOP. 

I'm a little unclear who needs to eb convinced then :)   We already did the A/B test for OOP something like a year ago.  @kuhlenh has the original data i believe.  The results were in line with our expectations and showed only improvements for users at no perceivable cost.  Is there something actually holding this back?

> since nobody. I mean nobody noticed (including complaining or talking about it) it while we silently test it by turning things on by default (99% on in A/B testing)
> only people who looked matrix (such as trace or A/B scorecard or perf telemetry dashboard) can notice it.

I'm definitely confused.  Are there people doing this?  We already did the A/B test and we already examined and understood the numbers.  That was a year ago.  Did someone come back and say that the numbers were now no longer acceptable, even though a year ago we assessed this and found it ok. :)

Note, i'm not arguing with you.  Sounds like we're both on the same side here.  My question is more around: what is holding this up since there doesn't actually seem to be a problem and the team *already* did this analysis and found the results more than good enough.  

Originally there was a concern about stability and perf.  But both have been shown to not be an issue (including "in the wild" real world testing).  So... why would we not just turn this on given the improvements it brings to VS?

**Comment by heejaechang** [comment] 2018-07-18 19:59
for navbar and FAR, you probably need to convince @kuhlenh  and @jinujoseph and @ManishJayaswal  since I believe they are the ones who decide whether we will make it on by default or not.

for OOP 64bit, probably divisional decision maker especially, perf team.

**Comment by jinujoseph** [comment] 2018-07-18 20:02
It's in my todo list to be followed up for perf  regression/exception and is targetted for 16.0

**Comment by CyrusNajmabadi** [comment] 2018-07-19 04:32
@jinujoseph Yaay.  Let me know if you need anything from me.

**Comment by sharwell** [comment] 2018-07-25 18:05
Duplicate of #23331

**Closed by sharwell** 2018-07-25 18:05 UTC
Labels: Area-IDE
