### ISSUE TITLE
At a los

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn#21672] opened 2017-08-22 22:46 UTC
This is probably not the place to post this issue, but it is almost impossible to get any acknowledgement through usual channels.

Basically why oh why oh why does Visual Studio STILL not provide the ability to report and remove unused assembly references in projects? Developers often modify code and projects in such a way that an assembly that was being used is actually no longer being used (no references to anything in the assembly any more).

But they are unaware and so the assembly remains referenced and when/if nuget packages are created that too then has a dependency on this no-longer-used assembly. That in turn can lead to version clashes etc etc etc.

Is there no way to get the Visual Studio team to address this? apparently its been around for years for VB !!!

**Comment by CyrusNajmabadi** [comment] 2017-08-23 01:27
Dupe of https://github.com/dotnet/roslyn/issues/6763

**Comment by CyrusNajmabadi** [comment] 2017-08-23 01:28
> Is there no way to get the Visual Studio team to address this? 

We'd happily take a contribution here :)

**Closed by CyrusNajmabadi** 2017-08-23 01:27 UTC

**Comment by Korporal** [comment] 2017-08-23 14:23
@CyrusNajmabadi - Hi, so this is where Visual Studio lives? I thought this repo was focused primarily on the C#/CB compilers? 

From the README page:

"_Roslyn provides open-source C# and Visual Basic compilers_" nowhere can I see any mention that Visual Studio itself is open source and situated in this repo.

I may be wrong, but I don't see how such a feature could be delivered if working purely on the compiler? Perhaps a Visual Studio extension...

**Comment by CyrusNajmabadi** [comment] 2017-08-23 17:51
@Korporal This is where the IDE support for VB and C# live.

**Comment by CyrusNajmabadi** [comment] 2017-08-23 17:51
> nowhere can I see any mention that Visual Studio itself is open source and situated in this repo.

VS is not open source.  However, the VB and C# IDE components of it are.
