### ISSUE TITLE
[VB] Make Autoselection less aggressive in certain situations.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10341] opened 2016-04-05 12:23 UTC
In VB the `:` character has different meaning based on context:
As a statement separator

``` vb
 statement_0 : statement_1 : statement_2
```

As a label marker

``` vb
  statements_before
label:
  statements_after
```

Writing a label is made difficult by the IDE aggressively presume I writing the first. Automatically inserting the space before the `:`, thus changing the meaning of what I wrote, from what I intended.
It should wait a little longer, to see if I type an `end of line character` before deciding.

**Comment by Pilchie** [comment] 2016-04-08 21:47
It sounds like the issue here is that we're invoking a format when an item is committed with : and we shouldn't...

**Comment by rchande** [comment] 2016-06-22 18:12
@AdamSpeight2008 I'm unable to reproduce what you described; can you provide more concrete repro steps? Thanks!

**Comment by AdamSpeight2008** [comment] 2016-06-22 18:58
@rchande 
I've attached a FLV demostrating an issue with trying to use labels in the IDE.
[LabelExample.zip](https://github.com/dotnet/roslyn/files/328558/LabelExample.zip)
I can't remember if this is the original issue i rose.

**Comment by AdamSpeight2008** [comment] 2016-08-03 22:49
Closing till I (or someone else) can produce the issue,

**Comment by AdamSpeight2008** [comment] 2016-11-14 23:54
When using the Roslyn Repo, it sometimes hard to use due to the auto-selection prioritizing non-language keywords (eg class names) over language keywords.
Eg Let's say I'm modifying `VisualBasicCommandLineParser` and I'm modifying and `If Then .. End If` into a `If ... Then ... Else ... End If`

Add in an `Else` the autocomplete produces `ElseBlockSyntax` not the expected `Else`

**Comment by gafter** [comment] 2017-06-07 18:58
@rchande Please move this to an open milestone.

**Comment by rchande** [comment] 2017-06-07 20:26
@Pilchie I moved this into 15.6, feel free to move earlier or later.

**Comment by Pilchie** [comment] 2017-06-07 20:30
@AdamSpeight2008 It looks like you re-opened this for a different case.  Can you file a new issue with detailed and clear repro steps?

**Closed by Pilchie** 2017-06-07 20:30 UTC
Labels: Area-IDE, Bug
