### ISSUE TITLE
Complete Statement should not move semicolons through "[" and "]"

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#33953] opened 2019-03-07 22:59 UTC
![completestatement](https://user-images.githubusercontent.com/5455484/53995100-e16b3280-40e8-11e9-8d15-5b4a09113e5e.gif)

1. Have a method with an attribute.
2. Try to define a field above the method.
3. Typing a semicolon moves it after the attribute which is confusing.

This happens because before the semicolon is typed, the `[Attribute]` is parsed as `ElementAccessExpression `and belongs to the field definition.

Source: https://developercommunity.visualstudio.com/content/problem/481019/atrocious-typing-help.html

I hope that the user used custom Roslyn bits and this is not shipped yet for 16.0 but need to verify with the user.

**Comment by ivanbasov** [comment] 2019-03-07 23:10
Confirmed with the customer. These are 16.1 bits 

Confirmed with the compiler team that the syntax tree in the intermediate state is correct.

**Comment by CyrusNajmabadi** [comment] 2019-03-07 23:57
> Confirmed with the compiler team that the syntax tree in the intermediate state is correct.

Note: we can and should consider tweaking the parse tree here.  THis affects a lot of features and would be nice to avoid.  The general rule would be:

1. if you parsed as an elementaccess, and
2. you're missing the semicolon, and
3. the element access is on a different line,
4. you're followed by a member construct

Then go back and finish the expression prior to the elemetn access.

**Comment by ivanbasov** [comment] 2019-03-08 00:10
> > Confirmed with the compiler team that the syntax tree in the intermediate state is correct.
> 
> Note: we can and should consider tweaking the parse tree here. THis affects a lot of features and would be nice to avoid. The general rule would be:
> 
> 1. if you parsed as an elementaccess, and
> 2. you're missing the semicolon, and
> 3. the element access is on a different line,
> 4. you're followed by a member construct
> 
> Then go back and finish the expression prior to the elemetn access.

Thank you, @CyrusNajmabadi ! Do you mean this should be fixed in the parser?
Tagging @AlekseyTs for design review

**Comment by CyrusNajmabadi** [comment] 2019-03-08 00:14
> Thank you, @CyrusNajmabadi ! Do you mean this should be fixed in the parser?

Depend on hte priority here.  If we're looking for a quick fix for 16.0, then definitely not.  I would not risk it.

If this is about the best long-term fix, then yes I would recommend changing the parser here.  This is effectively a decision about how the parser should behave in an error condition.  Currently, it behaves in a simple, though non-ideal fashion that ends up throwing off *many* downstream features.  I suggest improving the error-detection/recovery strategy here in a very targeted fashion.  We've done this numerous times before, so this doesn't really bother me.  The trick is to just be very careful with precisely what you're looking for.

--

Note: need to tweak the above set of rules slightly since you might have:

```c#
private const strings s = "abc"

[attr1][attr2]class C {}
```

Because of multiple attributes, we would need to walk up indexing expressions until we found one that started on a new-line.

**Comment by CyrusNajmabadi** [comment] 2019-03-08 00:41
Some information rules rules for the syntax tree are really:

1. if the code is correct, the syntax tree should reflect that.
2. if the code is incorrect, the syntax tree should try to reflect the most intuitive interpretation of what was written.

The latter rule is where things get tricky, and where you sometimes need some interesting error recovery strategies when the default parsing approach ends up screwing things up.

**Comment by sharwell** [comment] 2019-03-12 01:49
Duplicate of #33851

**Comment by sharwell** [comment] 2019-03-12 01:50
Summary: This situation is unrelated to the attribute syntax. Complete statement should have been disabled for the single reason that the caret was not within a matched pair of parentheses, braces, or brackets.

**Comment by jinujoseph** [comment] 2019-04-10 00:49
This still repro's in 16.1.Preview1

**Comment by chborl** [comment] 2019-04-10 01:37
After further investigation, this is a dup of https://github.com/dotnet/roslyn/pull/34706 which was fixed in https://github.com/dotnet/roslyn/pull/34706

**Closed** 2019-04-23 08:30 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense, Urgency-Soon
