### ISSUE TITLE
.editorconfig analyzer support appears to be flaky/broken in recent release

### ISSUE THREAD

**Issue by onyxmaster** [dotnet/roslyn#49597] opened 2020-11-24 14:25 UTC
**Version Used**: 
VS 16.8.2, built-in analyzers.

**Steps to Reproduce**:

This is a duplicate of non-repro of #49404, but I've got a video with repro for you: https://youtu.be/s4XpusV_Joo
The code is at https://github.com/onyxmaster/EditorConfigProblemTestApp 

@mavasani could you please take a look?

**Comment by mavasani** [comment] 2021-01-07 15:09
Duplicate of https://github.com/dotnet/roslyn/issues/49718

**Closed by mavasani** 2021-01-07 15:09 UTC
Labels: Area-Analyzers, Bug, Investigation Required, Resolution-Duplicate
