### ISSUE TITLE
Roslyn requires explicit type when type is apparent with cast

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#47704] opened 2020-09-15 13:34 UTC
**Brief description:**

```
csharp_style_var_elsewhere=false:suggestion
csharp_style_var_for_built_in_types=false:suggestion
csharp_style_var_when_type_is_apparent=true:suggestion
csharp_style_var_elsewhere=false:suggestion
```

```cs
public static int f(int r)
{
   var p = (int)r
   return p;
}
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0008	Use explicit type instead of 'var'
```

Expected: Use 'var'.

**Comment by jinujoseph** [comment] 2020-09-15 23:55
cc @sharwell

**Comment by sharwell** [comment] 2020-09-16 00:48
Duplicate of #23714

**Comment by CyrusNajmabadi** [comment] 2020-09-16 16:34
I'm reopening this one as i don't think this is a dupe.

**Comment by CyrusNajmabadi** [comment] 2020-09-16 16:35
Specifically, the case here has a cast.  And our code specifically thinks a cast makes the type apparent:

https://github.com/dotnet/roslyn/blob/1d69a1dcc301e52ca624db0292bc500f497d301f/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/TypeStyle/TypeStyleHelper.cs#L108-L115

So this should not recommend using an explicit type.

**Comment by osdm** [comment] 2020-10-19 07:33
@CyrusNajmabadi I guess the code in question is here. Basically it ignores apparent types at all if a type is intrinsic
[https://github.com/dotnet/roslyn/blob/a34f425d15b9acd35e749d99b31c682fbb8ddf4b/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseExplicitTypeHelper.cs#L30-L46](url)

[https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs#L78-L94](url)

**Comment by sharwell** [comment] 2020-10-19 12:42
@CyrusNajmabadi This is a duplicate of #23714. The fact that the type here is `int` takes precedence over whether or not the type is explicit (https://github.com/dotnet/roslyn/issues/23714#issuecomment-350705649). That issue specifically concerns this ordering.

**Closed by sharwell** 2020-10-19 12:42 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, Resolution-Duplicate

**Comment by CyrusNajmabadi** [comment] 2020-10-19 14:31
Sam's totally correct.   I missed that this was a "built in" type.
