### ISSUE TITLE
csharp_space_between_method_call_parameter_list_parentheses appears to have no effect inside object initializers

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#33238] opened 2019-02-08 04:34 UTC
**Version Used**: 
Visual Studio 2017 Community v15.9.6

**Steps to Reproduce**:

1. Create a new .NET Standard Class Library project
2. Replace the contents of `Class1.cs` with the following code:
```csharp
using System.Collections.Generic;
using System.Net;

namespace Tests
{
    public class IsolatedStorageServerListProviderFacts
    {
        public object ReadsUpdatedServerList(object foo)
        {
            var list = new List<object>()
            {
                CreateSocketServer(new IPEndPoint(IPAddress.Any, 1234)),
                CreateSocketServer(new IPEndPoint(IPAddress.Loopback, 4321))
            };

            return ReadsUpdatedServerList(list);
        }

        static object CreateSocketServer(object o) => throw null;
    }
}

```
3. Create a new Solution Item using the Text File template and make the file name `.editorconfig`
4. Add the following to the blank `.editorconfig` file:
```
root = true

[*]
indent_style = space
insert_final_newline = true
indent_size = 4

csharp_space_between_method_call_parameter_list_parentheses = true
```
5. Open `Class1.cs`
6. Press Ctrl+K then Ctrl+D to reformat the document

**Expected Behavior**:
```csharp
using System.Collections.Generic;
using System.Net;

namespace Tests
{
    public class IsolatedStorageServerListProviderFacts
    {
        public object ReadsUpdatedServerList(object foo)
        {
            var list = new List<object>()
            {
                CreateSocketServer( new IPEndPoint( IPAddress.Any, 1234 ) ),
                CreateSocketServer( new IPEndPoint( IPAddress.Loopback, 4321 ) )
            };

            return ReadsUpdatedServerList( list );
        }

        static object CreateSocketServer(object o) => throw null;
    }
}

```

**Actual Behavior**:
```csharp
using System.Collections.Generic;
using System.Net;

namespace Tests
{
    public class IsolatedStorageServerListProviderFacts
    {
        public object ReadsUpdatedServerList(object foo)
        {
            var list = new List<object>()
            {
                CreateSocketServer(new IPEndPoint(IPAddress.Any, 1234)),
                CreateSocketServer(new IPEndPoint(IPAddress.Loopback, 4321))
            };

            return ReadsUpdatedServerList( list );
        }

        static object CreateSocketServer(object o) => throw null;
    }
}

```

**Observations**:

The regular method call to `ReadsUpdatedServerList` has whitespace inserted around the parameter list, but the calls to `CreateSocketServer` and `IPEndPoint`'s constructor do not.

**Comment by sharwell** [comment] 2019-02-08 13:14
Duplicate of #8269

**Closed by sharwell** 2019-02-08 13:14 UTC

**Comment by sharwell** [comment] 2019-02-08 13:16
Also seems related to #21192, #30881
