### ISSUE TITLE
FindAllReferences should handle `Dispose` referenced in `using` and `foreach` statements

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28228] opened 2018-06-30 19:14 UTC
See comment in `ComputeImplicitReferenceConflictsAsync`: ` // TODO: handle Dispose for using statement and Add methods for collection initializers.`

Note, if this done at the same time or after C# 8.0, FAR should also account for `DisposeAsync` in async-foreach and async-dispose statements.

Relates to https://github.com/dotnet/roslyn/pull/28230

**Comment by jcouv** [comment] 2019-05-10 22:17
We should also handle the `using` declaration statement and the asynchronous variants of `using` statements and declarations.

I'm expecting Dispose and DisposeAsync to be referenced

```C#
using System;
using System.Threading.Tasks;

class C : IAsyncDisposable

{
    async Task M()
    {
        await using (var x = new C())
        {
        }

        await using var x2 = new C();
    }
    public ValueTask DisposeAsync() => throw new NotImplementedException();
}

class C2 : IDisposable
{
    void M()
    {
        using (var x = new C2())
        {
        }

        using var x2 = new C2();

    }
    public void Dispose() => throw new NotImplementedException();
}
```

**Comment by CyrusNajmabadi** [comment] 2023-02-09 22:11
@jcouv is there an api the compiler exposes to see what Dispose method a using binds to?

**Comment by CyrusNajmabadi** [comment] 2024-12-02 05:20
Dupe of https://github.com/dotnet/roslyn/issues/34107

**Closed by CyrusNajmabadi** 2024-12-02 05:20 UTC
Labels: Area-IDE, New Feature - Async Streams, New Language Feature - enhanced using
