### ISSUE TITLE
[17.1.5] Improvements to the new "Base types/implemented interfaces" view ("inheritance margin"?)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61022] opened 2022-04-28 22:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/1715-Improvements-to-the-new-Base-t/10021286)._

---
Seems there is a new tooltip in the bar to the left of C# source code, which displays for a class e.g. the base classes and interfaces. Is this the "Inheritance margin" found in the settings?

This new feature has potential. But see attached screenshot from one of our classes: we have a large inheritance hierarchy, and there are two things that I would like to improve.

![image](https://user-images.githubusercontent.com/1408396/168379881-d1769748-818e-4d88-8d70-15e8fd026fad.png)

**First**, the base types are sorted alphabetically. It would be better, if they were sorted in order of inheritance - maybe even idented?

**Second**: the interfaces are implemented on different base classes. Would be great to see the interfaces on the base classes that really implement them. It might even happen that the same interface is implemented multiple times on different levels of inheritance.

---
#### Feedback Bot on 4/23/2022, 06:23 PM: 

(private comment, text removed)
#### Feedback Bot on 4/25/2022, 00:04 PM: 

(private comment, text removed)
#### Fire Zhang [MSFT] on 4/26/2022, 02:30 AM: 

(private comment, text removed)
#### Shen Chen [MSFT] on 4/28/2022, 11:47 AM: 

(private comment, text removed)

**Comment by sharwell** [comment] 2022-05-13 19:53
The first suggestion is a duplicate of #53862. Can you provide additional details regarding what you wish to see for the second item?

**Closed** 2022-05-23 20:00 UTC
Labels: Area-IDE, Need More Info, IDE-Navigation, Navigation-Inheritance Margin
