### ISSUE TITLE
CodeLens Show References causes OOP to run out of memory

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#19767] opened 2017-05-25 03:08 UTC
**Version Used**: 15.3 Preview 1 running commit 732a69f10ea9a9a55414da3f4e4f2d23646230b7 in an experimental instance

**Steps to Reproduce**:

1. Set source control provider to None
1. Disable full solution analysis
1. Enable CodeLens, but disable all CodeLens features except Show References
1. Load Roslyn.sln

**Expected Behavior**:

Works.

**Actual Behavior**:

**ServiceHub.RoslynCodeAnalysisService32.exe** crashes with an `OutOfMemoryException`.

**Comment by sharwell** [comment] 2017-05-25 03:16
Reassigning to @dotnet/roslyn-analysis. Since Cyrus' work to move FAR out of process is not yet merged (#18939), there's no way that can be causing the problem.

**Comment by heejaechang** [comment] 2017-05-25 04:40
interesting. by any chance, have you saved a dump? and which file did you open in VS?

**Comment by CyrusNajmabadi** [comment] 2017-05-25 04:49
Dumb question: could this not just be another symptom of the memory mapped file leak?

**Comment by sharwell** [comment] 2017-05-25 05:03
> and which file did you open in VS?

I don't have a dump available from this machine, but this was trivially reproducible across a dozen different builds all day long. I had the following files open: AbstractSimplificationService.cs, then SymbolInfo.cs, then CandidateReason.cs.

> could this not just be another symptom of the memory mapped file leak?

@CyrusNajmabadi I couldn't rule that out; however, I tested with #19624 merged locally and it did not resolve the problem.

**Comment by Pilchie** [comment] 2017-05-30 17:47
@jinujoseph - can we try repro'ing this and investigate?  I wasn't seeing it, but it's blocking @sharwell's other investigations about OOMs.

**Comment by jinujoseph** [comment] 2017-05-30 18:07
Sure , Have asked @mattscheffer  to try to repro this, if he does then we can investigate this further.

**Comment by heejaechang** [comment] 2017-06-05 19:40
@sharwell do we have a dump? not sure why this suddenly happens..

**Comment by heejaechang** [comment] 2017-06-08 21:45
I couldn't repro the OOM following the described repro steps but I do see quite high memory usage opening many files that contains a lot of references (Code lens taking a while to get back with 99+ references) while OOP service other requests such as todo comments, designer attributes and etc.

this is due to  us caching everything while CodeLens running and if code lens happen to run long time and there are multiple code lens running, then there is possibility that we hold a lot of stuff in memory. and get OOM. I can confirm this by after code lens done running, if I force GC, memory goes down to 500-700MB which is about what I would expect for roslyn. this probably will go down even more once other things are done as well.

anyway, I see 4 ways to fix this.

1. move OOP to 64 bit.
2. improve our cache so that we no longer hold everything in memory blindly
3. throttle code lens so that it doesn't run a lot of search at once.
4. make code lens not to explicitly cache every projects it touches while running.

these 4 are not mutually exclusive. we can choose to do multiple of these. but if we need to choose one, I would support either doing (1) or (2) or both.

(1) is general scalability improvement over some higher VM usages due to 64bit.
(2) is just something we have to improve at some point so that we can have better scalability overall.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 21:54
Do we have any idea why CodeLens does '4'?

**Comment by heejaechang** [comment] 2017-06-08 21:57
because we wrote that way so that we can get better perf.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeLens/CodeLensReferencesService.cs,37

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:00
I don't get why the perf would be better.  FindRefs already properly walks projects so that they don't need to be cached.

**Comment by heejaechang** [comment] 2017-06-08 22:02
you mean FAR has its own cache so code lens won't need one? otherwise, parse tree or text read will go out from memory as soon as someone let the root node go. same for compilation.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:02
Note: that's why FindRefs itself doesn't do any of this caching.  And the normal FindRefs call the user makes is generally quite fast.

**Comment by heejaechang** [comment] 2017-06-08 22:03
so you suggest we simple don't enable cache for code lens?

**Comment by heejaechang** [comment] 2017-06-08 22:04
no idea on what it will impact on perf. it will certainly won't use as much memory, though.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:04
> you mean FAR has its own cache so code lens won't need one?

FindRefs was written to properly hold onto data while it's working so it would not need external caches.  Specifically:

It orders the projects it processes so that previously built projects are available when needed by a later project.

It splits projects into cliques, so that an entire clique can be let go when moving to the next clique.

When processing a project, we keep the compilation for just that project around.  Then we go process the documents in that project (in parallel i believe).  When processing a document, we we run all our analysis against that document once.  So once we're done with it, it can be let go because it's not needed anymore.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:05
> so you suggest we simple don't enable cache for code lens?

That would def be something i would want us to look at.  I had no idea CodeLens was doing this, or what purpose it serves.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:07
Basically, if caching projects was important/necessary/valuable here for perf, then i would expect that we woudl do it when the user actually did a "Find All Referneces" invocation themselves.

**Comment by heejaechang** [comment] 2017-06-08 22:11
well, I could prefer one can enable cache whenever one wants to do some solution wide operation and cache itself is smart enough to not OOM and coordinate things when multiple such operation run.

right now, who doing caching and when matter too much.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:19
That's also fine with me.  But, again, it seems weird htat CodeLens caches for FindReferences, then the *real* Find-References-Command doesn't even bother doing this.    

What i *could* see being valuable in the Codelens case is that it's going to need to perform several FARs (for all the symbols currently on screen).  in that case, perhaps caching could be valuable. However it doesn't seem to be doing that.  It's enabling the cache for a single FAR call, and then disposing the cache afterwards.  With that logic, it seems highly unnecessary.

**Comment by heejaechang** [comment] 2017-06-08 22:20
by the way, FAR does have its own cache. not workspace cache but its own cache. I added them when I improved perf of FAR from 12 seconds to < 1 second long time ago.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/FindReferences/FindReferenceCache.cs,17

that is why it probably didn't need workspace cache... but this cache works fine for 1 FAR, but for multiple FAR, workspace cache could help since it will let multiple code lens search to share data.

but anyway, we can try remove the cache and see whether perf get any impact.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:21
>  but for multiple FAR, workspace cache could help since it will let multiple code lens search to share data.

But we disable the cache after each individual search that code-lens does.

**Comment by heejaechang** [comment] 2017-06-08 22:21
workspace cache itself make sure cache is shared when multiple operation is running.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:27
> when multiple operation is running.

So the question I have is:

Are multiple operations running?  Or is it just one call to FAR at a time?

**Comment by CyrusNajmabadi** [comment] 2017-06-08 22:28
If it's multiple at at time, i can see the value here.  But, as you said, the cache certainly can't be designed such that it causes OOMs.

**Comment by Pilchie** [comment] 2017-06-08 22:33
In @sharwell's original repro, this was an OOM in the VS process, not the OOP process, right?

**Comment by heejaechang** [comment] 2017-06-08 22:39
@sharwell  said in the issue above.

ServiceHub.RoslynCodeAnalysisService32.exe crashes with an OutOfMemoryException.

**Comment by heejaechang** [comment] 2017-06-12 19:18
simple fix is in 15.6. but ultimately I think we can better cache which can't fit into 15.3. moving to 15.6

bug on better cache is already exist.

**Comment by sharwell** [comment] 2017-06-21 20:32
Removed **Urgency-Now** since the combination of several memory-related improvements has made this much more difficult to reproduce.

**Comment by CyrusNajmabadi** [comment] 2022-10-28 22:36
Closing out as we have no repro and the world now is extremely different from 2017 wrt to oop/memory/etc.

**Closed by CyrusNajmabadi** 2022-10-28 22:36 UTC
Labels: Bug, Area-Analyzers, Tenet-Reliability
