### ISSUE TITLE
Primary constructor parameter not listed among completions, if base class has the same parameter

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#71440] opened 2024-01-02 14:01 UTC
**Version Used**: VS 17.9.0 P2.0

**Steps to Reproduce**:
Source for `ProfileMigration`:

```cs
public abstract class ProfileMigration(
	BlobServiceClient blobServiceClient,
	ILogger logger,	
	IProgress<int> progress
)
```

It doesn't work with `blobServiceClient`, `logger` and `progress`:

![image](https://github.com/dotnet/roslyn/assets/9047283/1df2196d-a196-4e69-ae2c-7e207e48e8b9)

While it works with `clock`.

**Expected Behavior**:
List `blobServiceClient` and all parameters among the completions.

**Actual Behavior**:
`blobServiceClient` and other parameters which are passed to the constructor of the base class, and base class has the same parameters, are not listed among the completions, although they are recognized as parameters in the source text (and build successfully).

**Comment by CyrusNajmabadi** [comment] 2024-01-02 14:24
Closing out. This is by design. Once passed to the base class, the language considers the parameter owned by the base class. So any use of the parameter in the current type will result in a warning about potentially duplicating storage. 

The item is suppressed to prevent that warning. If you want to use the parameter, assign to a new field or property and reference that.

**Closed by CyrusNajmabadi** 2024-01-02 14:24 UTC
Labels: Area-IDE, untriaged
