### ISSUE TITLE
New preselection doesn't work if done before an attribute

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#13825] opened 2016-09-15 18:37 UTC
``` C#
        private readonly object _lock = new $

        [ImportingConstructor]
        public SourceItemHandler(UnconfiguredProject project, IPhysicalProjectTree projectTree)
        {
            Requires.NotNull(project, nameof(project));
            Requires.NotNull(projectTree, nameof(projectTree));

            _project = project;
            _projectTree = projectTree;
        }

```

At $ expected to get "object" preselected in the completion Window. I do not.

**Comment by rchande** [comment] 2016-09-19 21:15
Dupe of #8261

**Closed** 2016-09-19 21:15 UTC
Labels: Area-IDE, Bug
