### ISSUE TITLE
C# intellisense incorrectly highlights nameof keyword with a red squiggly inside of an interpolated string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24375] opened 2018-01-22 08:46 UTC
The C# editor intellisense is highlighting the nameof keyword inside of an interpolated string with a red squiggly even though the project builds just fine. Two examples of strings that fail are:

A screenshot of the problem has been attached, here is the code from the offending function:

```csharp
bool EmitValueAssignmentForObject(Type objType, ObjectValue value, Dictionary<Type, LocalBuilder> localVars, Action<ILGenerator> pushObjDelegate, out Action<ILGenerator> generateObjValuesDelegate)
{
    if(!objType.IsClass || objType.IsArray)
    {
        throw new ArgumentException("Invalid object type: " + objType.FullName);
    }

    if((value.Properties == null || value.Properties.Length == 0)
        && (value.ChildProperties == null || value.ChildProperties.Length == 0))
    {
        generateObjValuesDelegate = null;
        return false;
    }

    if(!_gtypes.TryGetValue(value.Type, out GTypeEntry typeEntry) || !(typeEntry is GTypeEntryComplex complexTypeEntry))
    {
        generateObjValuesDelegate = null;

        System.Diagnostics.Debug.WriteLine($"[{nameof(GTypeAssemblyBuilder)}] Failed to create default values for an object because its type ({value.Type}) could not be located.");

        return false;
    }

    generateObjValuesDelegate = (ilGen) =>
    {
        if(value.Properties != null && value.Properties.Length > 0)
        {
            foreach(var prop in value.Properties)
            {
                if(prop.Value != null && prop.Value.Item != null)
                {
                    if(complexTypeEntry.Fields.TryGetValue(FieldNameFromProperty(prop.Name), out FieldBuilder fieldBldr))
                    {
                        if(EmitStoreValueInField(complexTypeEntry.PendingType.FullName, fieldBldr, prop.Value, localVars, pushObjDelegate, out Action<ILGenerator> storeFieldDelegate))
                        {
                            storeFieldDelegate(ilGen);
                        }
                        else
                        {
                            System.Diagnostics.Debug.WriteLine($"[{nameof(GTypeAssemblyBuilder)}] Failed to create default value for property {prop.Name} in type {complexTypeEntry.PendingType.FullName} because its value type ({fieldBldr.FieldType.FullName}) was not compatible with default value type ({prop.Value.ItemElementName}).");
                        }
                    }
                    else
                    {
                        System.Diagnostics.Debug.WriteLine($"[{nameof(GTypeAssemblyBuilder)}] Failed to create default value for property {prop.Name} in type {complexTypeEntry.PendingType.FullName} because its field could not be located.");
                    }
                }
            }
        }

        if(value.ChildProperties != null && value.ChildProperties.Length > 0)
        {
#warning TODO: Add support for child properties
        }
    };

    return true;
}
```

![image](https://user-images.githubusercontent.com/1408396/35234690-9b7f76fa-ff67-11e7-84c5-7dd11a962766.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/181935/c-intellisense-incorrectly-highlights-nameof-keywo.html
VSTS ticketId: 551470_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-01-22 20:22
This looks like it could be a dupe of https://github.com/dotnet/roslyn/issues/23667
@sharwell ?

**Comment by sharwell** [comment] 2018-01-22 20:26
@CyrusNajmabadi That seems extremely likely.

**Comment by sharwell** [comment] 2018-01-22 20:26
Duplicate of #23667

**Closed by sharwell** 2018-01-22 20:26 UTC
Labels: Bug, Developer Community
