### ISSUE TITLE
Enforced sorting section by EditorConfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40744] opened 2020-01-04 02:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/842780/enforced-sorting-section-by-editorconfig.html)._

---
<p>TSLint provides options to enforce sorting, e.g. for <a href="https://palantir.github.io/tslint/rules/object-literal-sort-keys/" target=_blank>object literals</a> or <a href="https://palantir.github.io/tslint/rules/ordered-imports/" target=_blank>imports</a>. For the sake of maintainability and to reduce merge conflicts it would helpful being able to enforce ordering of special sections also in .NET code. E.g. consider a bunch of constants:</p><pre>public const string ActionByValue = nameof(ByValue);
public const string ActionFavorites = nameof(Favorites);
public const string ActionRecent = nameof(Recent);
</pre><p>Only if developers are forced to sort correctly mentioned advantages apply.</p><p>Would it be possible to create a special comment and a EditorConfig rule which enforces ordering? E.g. for EditorConfig: </p><pre>dotnet_sort_comment_enabled = true
</pre><p>and then in code:</p><pre>// #sort ^\s*public.*;\s*$
public const string ActionByValue = nameof(ByValue);
public const string ActionFavorites = nameof(Favorites);
public const string ActionRecent = nameof(Recent);
// #endsort
</pre><p>Using the optional regex filter parameter, one can define which lines are subject to sorting. This way comments could be added for which sorting does not make sense.</p><p>Notes:</p><ul><li>This feature will only develop its full potential when <a href="https://github.com/dotnet/roslyn/issues/33558#issuecomment-466009872" target=_blank>failing EditorConfig rules can be configured to break a build</a>.</li><li>If this request is out-of-scope: Is there another way to enforce such a rule using VS means only? (VS extensions could do it, but if one developer on a team does not have it installed, they could circumvent the rule)</li></ul><p></p>

---
#### Visual Studio Feedback System on 12/5/2019, 00:35 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### tarek124455 on 12/6/2019, 01:33 PM: 

<p> For the over from worked master data.</p>

**Comment by kendrahavens** [comment] 2020-01-04 02:55
Related to https://github.com/dotnet/roslyn/issues/4778

**Comment by jinujoseph** [comment] 2020-01-14 20:37
Duplicate of #4778

**Closed by jinujoseph** 2020-01-14 20:37 UTC
Labels: Area-IDE
