### ISSUE TITLE
VS2015 IDE Sluggishness: 5 to 10 seconds lag time when dealing with large volume of issues

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn#5316] opened 2015-09-17 19:06 UTC
@morrisjoe reporting on behalf of ALM MVP Terje Sandstrom 

User scenario: 80 c# projects in solution, with around 30000 warnings coming from a mix of built-in Roslyn compiler errors/warnings and 3rd party analyzers including ReSharper, CodeCracker & SonarLint. After user opened his solution (80 projects), and after a few analyzers started providing warnings in the error list, user double-clicked on an issue in Error List, then did not move the mouse or do anything, and several seconds later (10 sometimes) the file opened. Perf is so bad, that users have started disabling analyzers.

Terje has provided the required trace files. Several MSFT Engineers are involved in debugging and root causing issue. Last person commented on is MSFT Engineer (David Pugh). Root cause still TBD

**Comment by MattGertz** [comment] 2015-09-17 19:15
@pharring Paul, can you keep an eye/follow up on this -- we'll want to make progress on this one pretty quickly.  Please connect with David Pugh who is investigating.

**Comment by pharring** [comment] 2015-09-17 23:34
See #5203 
There are also two similar allocation issues on the IDE side.

**Comment by KevinH-MS** [comment] 2015-10-15 04:34
Moving to 1.2 to verify once internal bug 144429 is addressed.

**Comment by pharring** [comment] 2015-10-27 13:59
The internal bug mentioned above has been fixed and will be in update 1.

However, I'm not sure this completely addresses the original problem. Using the Roslyn solution as a proxy, we were unable to reproduce the original problem as reported. We did see large allocations sorting and updating the error list - that's what we've addressed already. But double-click seems to be fine.

**Comment by KevinH-MS** [comment] 2015-12-01 05:41
Closing and assigning back to @morrisjoe to verify...

**Closed by KevinH-MS** 2015-12-01 05:41 UTC
Labels: Area-Analyzers, Bug, Tenet-Performance
