### ISSUE TITLE
Invalid suggestion for "base.ToString()" in Interpolated string literal

### ISSUE THREAD

**Issue by RamType-0** [dotnet/roslyn#44058] opened 2020-05-07 21:38 UTC
![image](https://user-images.githubusercontent.com/39725073/81347118-76efc100-90f6-11ea-9dde-d3f626b4f1c0.png)

**Comment by sharwell** [comment] 2020-05-07 21:42
Duplicate of #42669

**Comment by sharwell** [comment] 2020-05-07 21:43
@RamType-0 this should be fixed for 16.6 Preview 3 and newer 👍

**Closed by sharwell** 2020-05-07 21:42 UTC
