### ISSUE TITLE
Razor generated classes show up in solution explorer

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#18881] opened 2017-04-21 17:37 UTC
**Version Used**: 
2.3.0.61612 of Microsoft.CodeAnalysis.CSharp (I assume you can determine the rest of the graph based off this guy. Let me know if you need more versions.)

**Steps to Reproduce**:

1. Create new empty ASP.NET Core web application
2. Add Index.cshtml to root.
3. Add Index.cshtml.cs to root (it'll show up as nested under the cshtml file.
4. Open Index.cshtml.

**Expected Behavior**:
Index.cshtml and Index.cshtml.cs are the only ones visible

**Actual Behavior**:
You see the generated C# file for Index.cshtml sitting there.
![image](https://cloud.githubusercontent.com/assets/2008729/25289252/a9800f94-267d-11e7-986b-fa37440ad5fc.png)

**Extra**:
I've tried adding `[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]` and `[global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]` decorations to the generated Razor class to hide the file; neither of those work. Talked offline with @Pilchie and @jasonmalinowski and this isn't something that's currently possible without changes to Roslyn.

/cc @rynowak @DamianEdwards

**Comment by DamianEdwards** [comment] 2017-04-21 17:40
This feature ships in 15.3 so we're looking for a fix in that timeframe.

**Comment by Pilchie** [comment] 2017-04-21 18:30
@damienedwards - what is different about this from the behavior in VS2015 and VS2017?

**Comment by DamianEdwards** [comment] 2017-04-21 19:35
The naming of Razor files this way is a new idiom as part of Razor Pages in 2.0

**Comment by Pilchie** [comment] 2017-06-19 16:35
Pulling back into 15.3 to investigate, since this appears to be a regression.

**Comment by jasonmalinowski** [comment] 2017-06-22 22:58
@NTaylorMullen: I'm unable to follow the repro steps to get the .cshtml.cs to be nested under the .cshtml file, much less repro the bug. It might have something to do with me creating 2.0 projects and being unable to build them:

```
1>c:\users\jasonmal\Source\Repos\WebApplication2\WebApplication2\WebApplication2.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0)
1>c:\users\jasonmal\Source\Repos\WebApplication2\WebApplication2\WebApplication2.csproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-002111-00 ]
1>c:\users\jasonmal\Source\Repos\WebApplication2\WebApplication2\WebApplication2.csproj : error NU1102:   - Found 6 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.1.2 ]
```

Help? This is with the internal build of 26621.2.d15rel.

**Comment by jasonmalinowski** [comment] 2017-06-22 23:21
OK, so any case, trying to answer "how did this ever work before":

If I create a regular good old fashioned MVC app and open a .cshtml file, the autogenerated secondary buffer file (i.e. the file that contains `public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic> {`) is pushed not into the main project for the project, but rather a second project that is created to contain the contained document. When we go looking to see if under a file there are classes to show, we just do [this](https://github.com/dotnet/roslyn/blob/35afa309845740382633230e7d8cdd6417e9d195/src/VisualStudio/Core/Def/Implementation/Progression/GraphBuilder.cs#L79-L93), which means we discover the first project that won't contain the .cshtml file "document", and never look at the second one because we just did FirstOrDefault.

@NTaylorMullen @DamianEdwards So what is this new feature? Does it mean there's always a generated document given to the language service whether it's open or not? Is the lack of a separate intellisense project here intentional or not?

Unfortunately your answers to the question won't motivate a "how is this supposed to work", since it was only working by pure accident in the first place, but it helps to know. :smile:

**Comment by rynowak** [comment] 2017-06-22 23:58
>So what is this new feature?

As far as I know, the fact that the generated document is *in the project* instead of a secondary project is true for all ASP.NET Core including 1.0

>Does it mean there's always a generated document given to the language service whether it's open or not?

The generated document only exists while it's open in the editor. This is a gap we plan to address but will not get to it soon.

> Is the lack of a separate intellisense project here intentional or not?

This is another gap we plan to address but will not get to it soon.

**Comment by jasonmalinowski** [comment] 2017-06-26 22:15
@rynowak Ah, you're right, that was behavior in 1.0 too.

So this might have been working by other accidental magic then: we get queried for the .cshtml file during project load, but since we don't recognize the file at that point we just bail and nothing will refresh it later. I suspect if you had the file already open and soon enough prior to the progression provider getting invoked you might see this.

There *is* a "is compiler generated" flag that used to filter out things from the solution explorer from the data set. We don't set that flag, but I have to dig quick through the old provider code to see what logic used to be used (if anything) for it as suddenly setting it might break other features.

**Comment by MattGertz** [comment] 2017-06-30 18:22
Mondo escrow triage:  keeping for now as it is a perceived regression.

**Comment by cyrusel** [comment] 2017-08-21 16:43
The problem still persists in .net core 2 and VS 2017 15.3 final release.

**Comment by rynowak** [comment] 2017-08-22 01:55
@jasonmalinowski - do you have any idea what the fix for this looks like? Is this entirely on your side or will we need to change something?

**Comment by jasonmalinowski** [comment] 2017-08-22 16:15
@rynowak Yeah, I think I have an idea, need to do some more checking to verify it doesn't break anything else. But it's a fix all on our side.

**Comment by dpoeschl** [comment] 2017-09-26 21:32
@jasonmalinowski What was your idea here? We could possibly load balance the fixing if you can explain what your idea was.

**Comment by jasonmalinowski** [comment] 2017-09-28 17:55
The solution explorer does recognize a "compiler generated" flag that it filters out, which we could set in this case. This flag was also set by the old providers, so I wanted to check what the old logic was to make sure that providing this wasn't going to break lots of things.

**Comment by cyrusel** [comment] 2017-12-13 08:08
The problem still persists in 15.5.1 :|

**Comment by Postlagerkarte** [comment] 2018-01-16 20:56
The problem still persists in 15.6.0 preview 1

**Comment by cyrusel** [comment] 2018-08-16 20:50
I can't believe it.. it's been more than 1 year and not fixed in 15.8..

**Comment by CyrusNajmabadi** [comment] 2023-02-07 19:13
@jasonmalinowski still an issue with Razor LSP?

**Comment by DamianEdwards** [comment] 2023-02-07 19:43
Doesn't repro for me anymore:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/249088/217348904-2c2f8c01-5a34-4f6f-ac5a-e0a49ed80e82.png">

**Closed** 2023-02-07 19:50 UTC
Labels: Bug, Area-IDE
