### ISSUE TITLE
C# - private implicit backing field for properties

### ISSUE THREAD

**Issue by HopefulToad** [dotnet/roslyn#31329] opened 2018-11-24 00:19 UTC
For properties where the backing field is (or should be) only used within the body of the property, I think it would be nice if there were an auto-implemented, implicit backing field that could be accessed using a keyword like `field`. For example:

```c#
public int MaxValue
{
    get => field; // Field is a contextual keyword, like value, used to access the implicit backing variable
    set
    {
        if (value < 0)
            throw new ArgumentException("MaxValue cannot be negative.")
        field = value;
    }
}
```

This saves the programmer from having to declare a backing variable that will only be used inside a property. Also, it makes it so that code _within_ a class has to go through the property to access the value rather than getting or setting the backing variable directly.

To prevent backing variables from being created for properties where they are not used, the compiler could simply not create the backing variable if "field" (or the equivalent key word) is never used in the property.

**Comment by jcouv** [comment] 2018-11-24 05:17
Closing as duplicate of existing csharplang issue. Thanks

**Closed by jcouv** 2018-11-24 05:17 UTC

**Comment by HopefulToad** [comment] 2018-11-24 07:32
Whoops! Sorry, I wasn't aware of the existence of that repository. And it looks like several people have already thought of and proposed identical or similar features.

**Comment by jnm2** [comment] 2018-11-24 12:50
> And it looks like several people have already thought of and proposed identical or similar features.

A new similar or identical issue is raised by a newcomer about every two weeks on average for most of the year. Seems like it's happening faster than it used to.  I hope that the popularity of this issue eventually gets the discussion into a meeting. @jcouv, is there anything we can do to help this happen?

**Comment by jnm2** [comment] 2020-04-04 13:00
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
