### ISSUE TITLE
'using' CodeActions not available if #line hidden is present anywhere in the file

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#40655] opened 2019-12-30 22:55 UTC
Repro steps:
1. `dotnet new console`
1. In Program.cs remove `using System;`
1. Hover over the now-broken Console.WriteLine and see that `using System;` is a CodeAction option.
1. Add `#line hidden` just below Console.WriteLine.
1. Repeat 3 and see that the `using System;` option is now gone.

This affects us because when Razor generates code for the C# portions of it `#line default` `#line hidden` and `#line X` are used.

CC @NTaylorMullen

**Comment by CyrusNajmabadi** [comment] 2020-01-02 16:28
This is by design.  the #line pattern indicates to us that the area we would add hte `using` to is hidden from the user (and thus out of their control and under the contorl of another tool).  I believe for this to work, you would need to add a `#line default` on the first line to inform the IDE that the `usings` section is visible to the user.  otherwise, based on how old tools worked, we will assume it was hidden.

**Comment by tmat** [comment] 2020-01-02 17:32
@CyrusNajmabadi I don't think this is by design. In the example above `#line hidden` is below the line that should offer the code action.

![image](https://user-images.githubusercontent.com/41759/71681869-c4bc7d00-2d42-11ea-8fd8-39e308e63e4e.png)

**Comment by CyrusNajmabadi** [comment] 2020-01-02 17:44
No... It's by design. This was the pattern other generators used. And we had to preserve compat with them

**Comment by CyrusNajmabadi** [comment] 2020-01-02 17:51
From our code, we say:

```c#
            return text.OverlapsHiddenPosition(span, (position, cancellationToken2) =>
                {
                    // implements the ASP.NET IsHidden rule
                    var lineVisibility = tree.GetLineVisibility(position, cancellationToken2);
                    return lineVisibility == LineVisibility.Hidden || lineVisibility == LineVisibility.BeforeFirstLineDirective;
                },
                cancellationToken);
```

So this is how ASP.net did things.  The workaround is to place a `#line` directive on line 0.

**Comment by tmat** [comment] 2020-01-02 18:04
OK, then I'd not call this by design, but rather a hack for legacy ASP.NET. Can we only use the hack when we are in legacy ASP.NET project? Because this is not how the compiler defines non-user code. It seems unfortunate to perpetuate incorrect behavior just because legacy ASP.NET didn't generate correct `#line` directives.

**Comment by CyrusNajmabadi** [comment] 2020-01-02 18:08
> OK, then I'd not call this by design, but rather a hack for legacy ASP.NET

I mean... it was the design of `#line`.  That's how they used it and how we always supported the concept.  Since this entered the IDE (and throughout roslyn) it's always worked this way.

> Can we only use the hack when we are in legacy ASP.NET project?

I'd much rather have everyone just use hte same pattern.  :)

Having to support multiple patterns is just extra complexity for all our code.  If something is the defacto pattern, i'd like to just have that.

--

Note: i strongly feel this way because IDE is always expected to deal with these teams changing behavior and hten supporting that behavior forever.  We have waaay too many cases where we end up having to have codepaths to support N different project systems, M different 'code-projection' systems, etc. etc.  The teams just move on, but IDE needs to absorb all the complexity forever.  It's a *large* maintenance burden that actively makes future work more costly to maintain.

**Comment by tmat** [comment] 2020-01-02 18:11
> All the teams (and IDE) agreed on this behavior. 

That's too bad, since the `#line` directive is definitely not defined this way :(.

**Comment by CyrusNajmabadi** [comment] 2020-01-02 18:12
> That's too bad, since the #line directive is definitely not defined this way :(.

Welcome to the old days of the project when Compiler and IDE didn't talk to each other and IDE had to reimplemet hte entire compiler API :D

**Comment by NTaylorMullen** [comment] 2020-01-06 18:42
Sorry for the late reply, I've been sick.

> I believe for this to work, you would need to add a `#line default` on the first line to inform the IDE that the `usings` section is visible to the user. otherwise, based on how old tools worked, we will assume it was hidden.

@CyrusNajmabadi I'm trying to understand where adding a `#line default` would make this work ever

![image](https://user-images.githubusercontent.com/2008729/71839230-8b03b300-306f-11ea-9da9-a21e611829af.png)

And just for context, in Razor file if you do `@{ Console.WriteLine("..."); }` it generates as the following boiler plate (does not allow usings directives):
```C#
#nullable restore
#line 23 "C:\Users\nimullen\source\repos\Preview1_31BlazorServerSide\Preview1_31BlazorServerSide\Pages\_Host.cshtml"
    Write(Console.WriteLine("..."));

#line default
#line hidden
#nullable disable
```

**Comment by CyrusNajmabadi** [comment] 2020-01-06 18:59
I'd have to debug through to see waht was up here.

**Comment by tmat** [comment] 2020-01-06 19:02
Somewhat unrelated but why switching to `default` and then immediately to `hidden`? `#line default` seems superfluous.
```
#line default
#line hidden
```

**Comment by NTaylorMullen** [comment] 2020-01-06 19:17
> Somewhat unrelated but why switching to `default` and then immediately to `hidden`? `#line default` seems superfluous.

Most likely an artifact of old Razor where the current VS Razor formatting engines expect our C# to look a certain way. We've tried changing the generated Razor C# in the past and have ended up paying dearly in the formatting front for the dumbest of reasons 😄

**Comment by NTaylorMullen** [comment] 2020-01-07 19:06
@CyrusNajmabadi just to clarify, that's definitely not expected right?

**Comment by CyrusNajmabadi** [comment] 2020-01-07 19:30
So this works for me:

![image](https://user-images.githubusercontent.com/4564579/71923047-fbc6d000-3140-11ea-88a1-9aa975c61408.png)

Looks like teh case that currently isn't supported is when there's *zero* usings in the file. however, that's never been the case for any asp generators using `#line`.  There are always *some* usings in scope.

You could def create a PR to fix this specific issue if it's a problem for you.  But i'm curious what the use case is where a templated language isn't even inserting `using System;` into the code for users.

**Comment by NTaylorMullen** [comment] 2020-01-07 19:48
Ooo interesting, definitely not a blocker when there's 0 usings. That's what I get for trying to get a "minimal" repro :smile:

At design time we can start generating a line default around our usings sections because it's not like you can debug over those anyhow. We can work with this! Feel free to close this issue as by design. Thanks for all the assistance everyone!

**Comment by CyrusNajmabadi** [comment] 2020-01-07 19:50
> Thanks for all the assistance everyone!

Definitely.  Glad we could reach an acceptable resolution here!

**Closed** 2020-01-08 20:51 UTC
Labels: Area-IDE, Resolution-By Design
