### ISSUE TITLE
Utf8String doesn't work with pattern matching

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#60747] opened 2022-04-14 17:44 UTC
**Version Used**: master

**Steps to Reproduce**:

I try to use pattern matching with Utf8String but seems that it is not yet supported.

https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTsAuACAMQHsiUAKAJQFMIATAeRgBsBPAZQAcIYAeYFnFQB8eAM4BKTAG9MeOXgQB2MWIDuUHAGMAFrPkyM8o3gBEAMxImArgA48AXhEoANHuOngEAE7W7jvEiuhu54APoOIgAMbngAvgDcmLGY2DD4xERIZJzcfALCYpIYBkZKKqLqWrrBciUh5pa2EXguMUYmnj5N/oFt8uH+0TVxiRjJWBi4hCQAzGT8ggDaALqF0jFlomoaOjF17g1Evs2tw+2dxz1BIWHNQ0YJSUA===

**Expected Behavior**:

Code can be compiled.

**Actual Behavior**:

error CS0150: A constant value is expected

**Comment by Youssef1313** [comment] 2022-04-14 18:10
This behavior is by design. A utf8 string isn't a constant (it's lowered to byte array creation). So it cannot be used in pattern matching. You also cannot assign it to a constant.

**Comment by jcouv** [comment] 2022-04-15 07:19
Tagging @AlekseyTs as FYI.
Closing as by design. We're tracking this language question in https://github.com/dotnet/roslyn/issues/58848 (under language design meeting "LDM" section).

**Closed by jcouv** 2022-04-15 07:19 UTC
Labels: Area-Compilers, untriaged
