### ISSUE TITLE
We need mixins/traits quickly!!

### ISSUE THREAD

**Issue by Meai1** [dotnet/roslyn#13157] opened 2016-08-14 09:28 UTC
Lets say you have a class Animal and a class Human
Both should be able to walk() and swim() so I wanna provide them both with a basic implementation for it. Let's say I already derive both from Entity and entities dont necessarily walk or swim so they shouldnt get both those methods.
What now? Impossible unless I duplicate the code in both Animal and Human or I create another class called, lets say Actor and put them in both Animal and Human composition style but then I always have to call:
myAnimal.actor.walk()
myAnimal.actor.swim()

There is no good solution in c#. Please fix!

Here is how it would look:
```
trait Tail {
     void wag() {}
}
trait Feet {
     void run() {}
}
trait Face {
     void smile() {}
}

class Animal has Tail, Feet, Face {
}

new Animal().smile();
```

**Comment by HaloFour** [comment] 2016-08-14 12:06
Dupe of #60.

**Comment by christianklauss** [comment] 2016-08-14 15:01
Traits can be implemented via source-generators so we don't necessarily need new language constructs.

**Comment by dsaf** [comment] 2016-08-15 08:23
> ...quickly...

:smile:

https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

My estimate is that it could happen in 3-6 years. Brownfield language development is not an easy thing.

**Comment by Meai1** [comment] 2016-08-15 15:40
all the other features are practically irrlevant when compared to the importance of mixins. We can live without local functions. Mixins however are a massive improvement in coding

**Comment by HaloFour** [comment] 2016-08-15 15:44
@Meai1 

Ask 25 different C# developers what the most important next feature should be and you'll get 50 different answers.  The team will prioritize and coordinate as they see fit.

Source generators, which may land in C# 8.0, will likely make it significantly easier to implement mixins and won't require separate syntax changes

**Comment by dsaf** [comment] 2016-08-15 16:05
@Meai1 pattern matching and tuples are substantial features, which are expected from any modern language with functional elements (e.g. Swift, Rust) except for sloppy ones (e.g. Go, TypeScript).

@HaloFour really?

**Comment by gafter** [comment] 2016-08-15 20:52
I'm a big fan of mixins (#60) too!

**Closed by gafter** 2016-08-15 20:52 UTC
