### ISSUE TITLE
Please allow to define static local variables in functions, like C/C++ 

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#10552] opened 2016-04-14 07:44 UTC
The static local variables can only be used in the functions which define them. C/C++ have this feature.
For example:
void foo()
{
static int call_times=0;
call_times++;
Console.Writeline("Function foo has been called {0} times", call_times);
}

**Comment by DavidArno** [comment] 2016-04-14 08:19
Static local variables are a way of maintaining state between calls to the same function. They are needed in C. They aren't needed in either C++ (though they exist there because of the origins of that language) or C#. You can achieve the same maintenance of state either through fields in object instances, or with static fields in a class.

**Comment by ygc369** [comment] 2016-04-14 08:32
@DavidArno 
I know what you said. But I think static local variable can make code more readable, it means this variable can only used in the specified function.

**Comment by DavidArno** [comment] 2016-04-14 10:23
```cs
public void Foo() => PrivateFoo.Foo();
private static class PrivateFoo
{
    private static int CallTimes;
    public static void Foo() => 
        Console.WriteLine($"Function Foo has been called {++CallTimes} times");
}
```

**Comment by axel-habermaier** [comment] 2016-04-14 12:01
@DavidArno: How is that more readable than

```csharp
public void Foo()
{
    static int callTimes = 0;
    Console.WriteLine($"Function Foo has been called {++callTimes} times");
}
```

**Comment by DavidArno** [comment] 2016-04-14 12:35
@axel-habermaier,

I'm not saying it's more readable. I'm saying that this functionality can already be achieved with the language, as is. 

Since it wraps global static state within a single, very hard to mock, single function, it's a pretty nasty implementation of the singleton anti-pattern. Changes to the language should enhance it. Simplifying the syntax around an already-implementable anti-pattern isn't my idea of enhancing a language.

**Comment by HaloFour** [comment] 2016-04-14 12:55
Note that VB.NET has always had this feature, it was inherited from VB5/6:

```vb
Public Sub Bar()
    Static CallTimes As Integer
    CallTimes += 1
    Console.WriteLine($"This method was called {CallTimes} times.")
End Sub
```

Just pointing that out.  I'm not endorsing the feature.  I'm personally not a fan of hiding shared state in the middle of a function like that.

**Comment by FrankHB** [comment] 2016-04-15 10:35
It should be noted that there are not too many differences between C and C++ in this area. In C++, static data members can have same duration class (static or thread-local) with namespace scope or block scope variables, the only differences are scoping (which has an effect on locality of names, i.e. information hiding), and (vs. block scope ones) the time of initialization. I'm not a fan of this feature but it is strange to allowing static fields while disallowing static local variables, since the latter actually always do better than the former in several cases due to the differences above.

Note the style to return a reference to a local static variable (delayed initialization, only when needed) is a variant of so-called [monostate pattern](http://c2.com/cgi/wiki?MonostatePattern), which is not quite the same to singleton pattern, but a better replacement in many cases, esp. after C++11, this can be thread-safe easily, while [the traditional singleton has a lot of problems (and very hard to do right) in C++, Java, C#, so on](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html).

**Comment by sunnycase** [comment] 2016-04-15 10:42
@FrankHB +1

**Comment by MgSam** [comment] 2016-04-15 17:47
Duplicate of https://github.com/dotnet/roslyn/issues/49

**Comment by DerpMcDerp** [comment] 2016-04-29 03:17
Perl's `state` keyword is superior to C++'s `static` keyword:

```C#
public static class Blah {
	private static void Foo() {
		System.Func<int> fn = () => {
			static int a = 0;
			return a++;
		};
		System.Console.Write("{0} {1} {2}", fn(), fn(), fn());
	}

	public static void Bar() {
		Foo();
		Foo();
	}
}
```

`Blah.Bar()` should print " 0 1 2 0 1 2" (i.e. behaves like Perl's `state`) instead of " 0 1 2 3 4 5" (i.e. behaves like C++'s `static`). In other words, if a static appears in a lambda, it should get initialized per instance of lambda rather than per group of lambas.

**Comment by HaloFour** [comment] 2016-04-29 12:27
@DerpMcDerp But also unnecessary given that you can just define `i` in the parent method and you automatically gain that functionality.

**Comment by DerpMcDerp** [comment] 2016-04-29 17:58
Except that defining `i` in the parent method initializes it when the parent method is called rather than when the lambda is called so it's not necessarily the same thing.

**Comment by HaloFour** [comment] 2016-04-29 18:33
@DerpMcDerp Considering how frequently such a problem is encountered and necessarily solved (read: never) I'd say that the few extra lines of code necessary to manage lazy initialization is a very small price to pay.  The net effect is identical anyway.

**Comment by FrankHB** [comment] 2016-05-04 06:33
@DerpMcDerp Terms in C# are generally not dynamic typed, so do variables in lambdas. So you are effectively overloading the `static` keyword with meaning that quite different with prior art, which may easily lead to more confusion.  If you need that feature, taking another keyword will be better.

And I don't think it is a good practice to modify the _local _ variables that has nothing to do with upvalues because you have too little control on them. They can only be the private state shared between lambdas. It seems that the more realistic need here is captured-by-copy variables, which fixes the variable binding when evaluating the lambda itself rather than calling, _and_ it can implement the private state. With explicit capture list of lambdas, this should be trivial. For example it is quite easy to initializing bound variable using the `[x = foo]` syntax in C++14. However, despite this can be very useful in C++ (esp. for a variable whose type meets `MoveConstructible` but not `CopyConstructible` and a copy of that variable is needed; otherwise you have to use some tricks like `bind` to work around), I don't see it is vital in C#. You simply don't have such fine-grained capture strategies to choose in C#.

**Comment by jrmoreno1** [comment] 2017-01-20 14:04
@DavidArno:

Your example isn't quite the same thing as VB's static...Not to mention creating a static class to hold a single value seems like too much work, most people are simply going to make it a regular instance field and leave a comment saying it should only be used in X and hope that is well enough.  Particularly since the value that you are creating is truly static (life time of the app) while VB's is scoped to a particular INSTANCE of a class and it's lifetime.

```
   public class NotTheSame 
   {
        public void Foo() => PrivateFoo.Foo();
        private static class PrivateFoo
        {
    	       static PrivateFoo() {
	       CallTimes = 600;
        }
        private static int CallTimes;
        public static void Foo() => 
            Console.WriteLine($"Function Foo has been called {++CallTimes} times");
    }

    var x1 = new NotTheSame();
    var x2 = new NotTheSame();
    x1.Foo();  // 601
    x2.Foo();  // 602
```

**Comment by NetMage** [comment] 2017-02-23 23:28
In the past it seems like the main arguments against adding this could all be applied to local functions as well, so now that they are included I would vote yes (obviously in C# 8 at this point) if there were formal voting.

**Comment by Ultrahead** [comment] 2017-05-02 00:17
I'd use static locals with recursion, but now local functions are included I can handle such use cases with them within the scope of each instance. But there could be cases where shared access among instances is needed, so it's a +1 for me (specially given that it's already present in VB).

**Closed** 2017-06-30 07:59 UTC
Labels: 0 - Backlog, Area-Language Design

**Comment by NetMage** [comment] 2017-06-30 13:51
Why is it still allowed to close issues without comments?

**Comment by sharwell** [comment] 2017-06-30 13:54
@NetMage Anyone is allowed to close their own issues

**Comment by NetMage** [comment] 2017-06-30 20:21
That would seem to be a problem - I open an issue, it is closed as Duplicate of someone else's issue. They close that issue and my interest in the issue is effectively lost.

**Comment by sharwell** [comment] 2017-06-30 21:29
@NetMage If this issue is of interest to you, I would recommend filing on dotnet/csharplang, since that's where proposals for changes to the language are getting filed now. I searched but didn't see a duplicate (doesn't mean one doesn't exist).

**Comment by syndrome** [comment] 2024-07-01 16:06
I don't quite understand how the original discussion involved. Having local static variables is merely a syntactic sugar.
For example
public class MyClass {

  void MyFunc() {
    static readonly MyType _cached;
    if(_cached is null) _cached = compute(...);
    // use _cached
  }

}

can be easily processed to an already supported pattern
public class MyClass {
  static readonly MyType _cached_MyFunc23873; // generated "unique identifier"

  void MyFunc() {
    if(_cached_MyFunc23873 is null) _cached_MyFunc23873 = compute(...);
    // use _cached_MyFunc23873
  }
}

I don't understand what's with the anti-pattern concerns mentioned above. The feature would offer a cognitive and organizational benefits by making sure a specific class field is accessible only to the function that declared it. Initialization and readonly modifier are not a concern, because this is only a syntactic sugar that guarantees a variable won't be used elsewhere (the field is strongly couples with a function). The point of guaranteeing uniqueness is to prevent clashes when two functions locally declare static variables which bear the same name.

I need to reiterate once more how strongly this affects the readability of a code that is vastly more complex than this example.
