### ISSUE TITLE
C# Interactive Crash - ValueTuple Pattern Match

### ISSUE THREAD

**Issue by StandishMan25** [dotnet/roslyn#18161] opened 2017-03-24 22:15 UTC
**Version Used**: 
Visual Studio Enterprise 2017 15.0.0+26228.9
.NET 4.6.01590
Default `System.ValueTuple` for C# Interactive

**Steps to Reproduce**:

1. Create new ValueTuple<List<int>, int>
`var val = (new List<int> {1, 2, 3, 4}, 5);`
2. Pattern match exact
`val is ValueTuple<List<int>, int>`
3. Should return true. Now pattern match against IEnumerable
`val is ValueTuple<IEnumerable<int>, int>`
4. Visual Studio crashes. It's occurred when closing the second >, or if replacing List to `IEnumerable`, crashing before I finish typing `IEnumerable`.

This appears to occur only when the actual `val` is using an `IEnumerable` because when testing with `(1, 2)` it seems to handle it ok, even when matching against `ValueTuple<IEnumerable<int>, int>`

**Expected Behavior**:
Expression evaluate to true.

**Actual Behavior**:
Visual Studio crashes.

**Gif of Behavior**
Apologies about the quality
![visual studio c interactive valuetuple pattern match crash](https://cloud.githubusercontent.com/assets/10331270/24315338/73d16502-10b4-11e7-99ab-4d488cf96451.gif)

**Comment by StandishMan25** [comment] 2017-04-12 16:30
As an update, the Interactive Window has crashed a few times when doing totally different things. I don't have a repro or even know what was going on in the main Visual Studio instance, but it appears to not solely be on pattern matching. I think it may have occurred when loading the Intellisense menu, but may be coincidence.

**Comment by weitzhandler** [comment] 2017-05-02 13:13
I'm also experiencing a crash.
I'm not sure I reproduce precisely, but here's my code:

    enum Gender { Male = 1, Female = 2 }
    var x = (Gender)3;
    x.ToString(); //crash

Anyway, I'd love to know how you recorded your screen like that, is this built in in Windows?

**Comment by StandishMan25** [comment] 2017-05-04 03:50
@weitzhandler it's an app called Screen to Gif, pretty sure this is the same one: http://www.screentogif.com

The gif above is kind of choppy because I cut a lot of frames before saving, I guess it can't handle that too well, but it's awesome otherwise.

**Comment by weitzhandler** [comment] 2017-05-04 10:09
@StandishMan25 Awesome thanks for sharing!

**Comment by tmat** [comment] 2017-05-16 18:42
This issue is not specific to interactive. Repro in regular .cs file:

![image](https://cloud.githubusercontent.com/assets/41759/26122525/b070f7a6-3a2c-11e7-92aa-4afeeef9df54.png)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected value 'ImplicitTuple' of type 'Microsoft.CodeAnalysis.CSharp.ConversionKind'



   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)

   at Microsoft.CodeAnalysis.CSharp.Binder.GetIsOperatorConstantResult(TypeSymbol operandType, TypeSymbol targetType, ConversionKind conversionKind, ConstantValue operandConstantValue)

   at Microsoft.CodeAnalysis.CSharp.Binder.ReportIsOperatorConstantWarnings(CSharpSyntaxNode syntax, DiagnosticBag diagnostics, TypeSymbol operandType, TypeSymbol targetType, ConversionKind conversionKind, ConstantValue operandConstantValue)

   at Microsoft.CodeAnalysis.CSharp.Binder.BindIsOperator(BinaryExpressionSyntax node, DiagnosticBag diagnostics)

   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)

   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)

   at Microsoft.CodeAna......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by tmat** [comment] 2017-05-16 18:42
@jaredpar FYI

**Comment by jcouv** [comment] 2017-05-20 18:41
This is a duplicate of https://github.com/dotnet/roslyn/issues/19310 which @gafter just fixed (as part of dev15.3).
Thanks @StandishMan25 for reporting the issue and @tmat for the stack trace (UnexpectedValue of ImplicitTuple in Binder.GetIsOperatorConstantResult).

**Closed by jcouv** 2017-05-20 18:41 UTC
Labels: Area-Compilers, Bug, Language-C#

**Comment by StandishMan25** [comment] 2017-05-20 21:33
Glad it's fixed, thanks @jcouv!
