### ISSUE TITLE
'GenerateConstructorCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#50765] opened 2021-01-25 23:52 UTC
**Version Used**: 352639e2

**Steps to Reproduce**:

Trying to edit code on a line that creates a new object.

**Expected Behavior**:

No gold bar reported.

**Actual Behavior**:

```
System.InvalidOperationException : Unexpected null
   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.GenerateConstructorHelpers.IsCompatible[TExpressionSyntax](ISemanticFactsService semanticFacts,SemanticModel semanticModel,IMethodSymbol constructor,ImmutableArray`1 expressions)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.GenerateConstructorHelpers.CanDelegateTo[TExpressionSyntax](SemanticDocument document,ImmutableArray`1 parameters,ImmutableArray`1 expressions,IMethodSymbol constructor)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.FindConstructorToDelegateTo(ImmutableArray`1 parameters,ImmutableArray`1 expressions,ImmutableArray`1 constructors,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.FindConstructorToDelegateTo(ImmutableArray`1 allParameters,ImmutableArray`1 allExpressions,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeDelegatedConstructor(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.GenerateAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.GenerateConstructorAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by sharwell** [comment] 2021-01-25 23:53
Possibly related to #49850, but not the same stack trace.

**Comment by jasonmalinowski** [comment] 2021-01-26 22:43
Yeah, #49850 added a null assert, and this is failing here. @sharwell do you have more specific repro steps? I can easily replace the ThrowIfNull with a return false, but it's not obvious to me how we are getting into that in the first place.

**Comment by jasonmalinowski** [comment] 2021-01-26 22:46
I might have a theory though...

**Comment by jasonmalinowski** [comment] 2021-01-26 23:03
Alright got a convoluted repro.

**Comment by jasonmalinowski** [comment] 2021-01-27 01:16
Marking this for 16.9 since this is a regression and an easily fixed one. @jinujoseph do we have a mop-up window for any last M2 approval fixes?

**Comment by jinujoseph** [comment] 2021-01-27 03:35
@jasonmalinowski  yes if you get this in by 1/27

**Closed** 2021-01-27 22:51 UTC
Labels: Area-IDE, Bug
