### ISSUE TITLE
C# doesn't allow for methods with optional `System.Half` parameters

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#70300] opened 2023-10-09 20:19 UTC
**Version Used**: 
4.8.0-1.23419.1

**Steps to Reproduce**:

1. Try to use `System.Half` in anywhere a constant is expected.
https://sharplab.io/#v2:D4AQTAjAsAULDaBZAngQQC7oE4EsBGArugKYAUpAEgIYA2AZgJQDMAdBACwMC6sITABOH4BhfgG9Y/KfwDGAewB2AZ3T9q9WQH0AFvwC8/VhwDck6X0Ht+iSrTr9dB2/WZtO4/gF8zUiyCuIEM72jvzBrhyMHt4w0oIC/tZgwQ76hm5RYl4+8ZbWTCmhRu5ZnnGwMbC8CWDWaJi4hCT8AFz8GNj4RMSwErHmAigdjd2Fdgw5fXFxFGnadqb9UjHlS7nq9rNZAObE6MbZcDCeQA==

**Diagnostic Id**:
- error CS0181: Attribute constructor parameter 'half' has type 'Half', which is not a valid attribute parameter type
- error CS0283: The type 'Half' cannot be declared const
- error CS0266: Cannot implicitly convert type 'double' to 'System.Half'. An explicit conversion exists (are you missing a cast?)
- error CS0133: The expression being assigned to 'C.c_h' must be constant
- error CS1736: Default parameter value for 'h' must be a compile-time constant
- error CS1736: Default parameter value for 'h' must be a compile-time constant
- error CS1750: A value of type 'float' cannot be used as a default parameter because there are no standard conversions to type 'Half'
- error CS1750: A value of type 'double' cannot be used as a default parameter because there are no standard conversions to type 'Half'

**Expected Behavior**:
Some way to use `Half` in these cases.

**Actual Behavior**:
`Half` is not supported for use as a default method parameter, constant, or attribute argument.

I don't have a strong use case for this, but it came up in source generator fix and I couldn't find any issue representing this gap.

**Comment by CyrusNajmabadi** [comment] 2023-10-10 06:28
Closing out as by design for Roslyn. Half is not something the language recognizes as special (like the other primitive types). 

For this to happen, we'd need to start with a discussion over at dotnet/csharplang, and a change too the language first.

**Closed** 2023-10-10 06:28 UTC
Labels: Area-Compilers, untriaged

**Comment by jcouv** [comment] 2023-10-11 18:17
Tagging @tannergooding. FWIW, I couldn't find any open csharplang proposal to treat `Half` as a built-in type that could be constant.

**Comment by tannergooding** [comment] 2023-10-11 18:48
I believe last time I had talked to @jaredpar and others it was basically left as "if enough interest exists, the language may consider it" and so no proposal was opened at the time.

**Comment by PavelCibulka** [comment] 2024-11-09 07:57
This would be nice.
