### ISSUE TITLE
The Project.FilePath for the Excel VSTO Add-in (C#) project is empty

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#40294] opened 2019-12-11 12:00 UTC
**Version Used**: 
16.4.0

**Steps to Reproduce**:

1. Create a new Excel VSTO Add-in (C#) project
2. Find the project in the Workspace.CurrentSolution

**Expected Behavior**:
the FilePath property for this project should contains the full path to the csproj file

**Actual Behavior**:
the FilePath property is null

**Comment by Droni** [comment] 2019-12-11 12:06
[Auth0.ExcelAddin.zip](https://github.com/dotnet/roslyn/files/3950206/Auth0.ExcelAddin.zip)

Attached the sample project

**Comment by Droni** [comment] 2019-12-11 14:06
Hm... It looks like the same issue https://github.com/dotnet/roslyn/issues/30429
Any progress?

**Comment by jasonmalinowski** [comment] 2019-12-24 03:12
Indeed this is a duplicate of #30429. I actually need to move that bug to the VSTO team, as this is a bug not on Roslyn _per se_. Roslyn tries asking those projects what the path is, and the API just throws. The fix needs to happen on their side.

**Closed by jasonmalinowski** 2019-12-24 03:12 UTC
Labels: Area-IDE, Bug, IDE-Project, Investigation Required
