### ISSUE TITLE
IDE0059 has misleading auto-fix name / incorrect preview with unnecessary ??= assignment

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38507] opened 2019-09-05 14:42 UTC
**Version Used**: 
3.4.0-beta1-19426-03+b18d90790da95b6862def56802fa4249e4868bb4

**Steps to Reproduce**:
```C#
class Program
{
    static void Main() { }

    static object M(object o) => o ??= new object();
}
```

**Expected Behavior**:
IDE0059 triggers about using `??=` instead of `??` here.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2642209/64352426-040fd280-cfca-11e9-9d74-bf86dfa9b11f.png)

The good news is the auto-fix will correctly substitute the "??" for the "??=".  However, two issues:
1) It names the auto-fix "Use discard _", even though it won't.
2) The preview doesn't show either the old or the new code being transformed.

**Comment by jinujoseph** [comment] 2019-09-10 17:45
incorrect preview is Duplicate of #38345

**Comment by sharwell** [comment] 2019-09-10 17:46
@mavasani I wasn't able to reproduce the IDE0059 diagnostic for this code. Can you verify?

**Comment by mavasani** [comment] 2019-09-10 17:58
@sharwell I am able to reproduce the issue on latest dogfood builds (note you have to target C# 8.0). As @stephentoub mentioned, the diagnostic is valid as there is indeed a redundant assignment. The applied code fix is also correct and handles redundant compound assignments from expression bodied members and return statements correctly. However, the code fix title is incorrect in these two contexts, it should instead be something like `Remove redundant assignment` for these cases. Let me see if this is easy to detect at code fix registration time to fix the title.

**Closed** 2020-01-11 05:04 UTC
Labels: 4 - In Review, Area-IDE, Bug
