### ISSUE TITLE
Intermittent build error in Syntax Generator tooling

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#7869] opened 2016-01-09 02:10 UTC
Sometimes when building Roslyn clean (after git clean -xdf) I get these errors:

                   "F:\SourcesToIndex\Roslyn\Roslyn.sln" (Rebuild target) (1) ->
                   "F:\SourcesToIndex\Roslyn\Open\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\Portable\BasicResultProvider.Portable.vbproj" (Rebuild target) (97:2) ->
                   (GenerateSyntaxModelGetText target) -> 
                     F:\SourcesToIndex\Roslyn\Open\build\Targets\GenerateCompilerInternals.targets(83,5): error MSB3073: The command ""F:\SourcesToIndex\Roslyn\Open\Binaries\Debug\VBSyntaxGenerator.exe" "..\..\..\..\..\Compilers\VisualBasic\Portable\Syntax\Syntax.xml" "F:\SourcesToIndex\Roslyn\Open\Binaries\Obj\BasicResultProvider.Portable\Debug\\Syntax.xml.Generated.vb" /gettext" exited with code 9009. [F:\SourcesToIndex\Roslyn\Open\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\Portable\BasicResultProvider.Portable.vbproj]

                   "F:\SourcesToIndex\Roslyn\Roslyn.sln" (Rebuild target) (1) ->
                   "F:\SourcesToIndex\Roslyn\Open\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\NetFX20\BasicResultProvider.NetFX20.vbproj" (Rebuild target) (121) ->
                     F:\SourcesToIndex\Roslyn\Open\build\Targets\GenerateCompilerInternals.targets(83,5): error MSB3073: The command ""F:\SourcesToIndex\Roslyn\Open\Binaries\Debug\NetFX20\..\VBSyntaxGenerator.exe" "..\..\..\..\..\Compilers\VisualBasic\Portable\Syntax\Syntax.xml" "F:\SourcesToIndex\Roslyn\Open\Binaries\Obj\BasicResultProvider.NetFX20\Debug\\Syntax.xml.Generated.vb" /gettext" exited with code 9009. [F:\SourcesToIndex\Roslyn\Open\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\NetFX20\BasicResultProvider.NetFX20.vbproj]

**Comment by KirillOsenkov** [comment] 2016-01-09 02:12
Build log:
https://www.dropbox.com/s/nwc1tzn7dvofs6m/RoslynBuildLogIssue7869.zip?dl=0

**Comment by davkean** [comment] 2016-01-15 05:04
9009 means "file not found" - maybe there's a timing issue here - VBSyntaxGenerator doesn't exist by the time this thing is generated.

**Comment by davkean** [comment] 2016-01-15 05:24
This is caused by BasicResultProvider.NetFX20 not having a dependency on VisualBasicSyntaxGenerator, thereby causing a race. There's no guarantee that the generator is built by the time this project is attempts to build.

Strangely, CSharpResultProvider.NetFX20 doesn't suffer from the same problem because it doesn't use the results of CSharpSyntaxGenerator.

Anyway, looks like a intex issue.

**Comment by davkean** [comment] 2016-01-15 05:25
tag @tmat

**Comment by davkean** [comment] 2016-01-27 04:21
@ManishJayaswal Can you please assign this out?

**Comment by ManishJayaswal** [comment] 2016-03-03 22:45
@KevinH-MS can you take a look at this?

**Closed** 2016-03-09 18:08 UTC
Labels: Area-Interactive, Flaky
