### ISSUE TITLE
C# compiler should compile a function pointer that returns a `ref struct` without CS8751.

### ISSUE THREAD

**Issue by ikorin24** [dotnet/roslyn#50500] opened 2021-01-15 01:33 UTC
**Version Used**: 

Microsoft Visual Studio Community 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
C# Tools 3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a

C# Lang Version 9.0

**Steps to Reproduce**:

Compile the following code.

```cs
public unsafe class Sample<T>
{
    private delegate*<Span<T>> _func;

    public Span<T> M()
    {
        return _func();
    }
}
```

**Expected Behavior**:

The compilation is successful.

**Actual Behavior**:

The compiler reports CS8751 "Internal error in the C# compiler." in the line of `return _func();`.

Not just `Span<T>`, any `ref struct` types cause the same error.

**Comment by jaredpar** [comment] 2021-01-21 00:07
Thanks for reporting. This appears to be a duplicate of #49760

**Closed by jaredpar** 2021-01-21 00:07 UTC
Labels: Area-Compilers, untriaged
