### ISSUE TITLE
Incorrect code analysis: IDE0059 Unnecessary assignment of a vlue to 'variable'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61347] opened 2022-05-16 19:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-code-analysis:-IDE0059-Unneces/10041850)._

---
[severity:Other]
Visual Studio is telling me that a variable assignment is unnecessary, and applying the suggested fix results in a compilation error. This C# code reproduces the issue:
```cs
    abstract class Foo
    {
        protected abstract void bar(out int v1, int v2);

        public Foo()
        {
            int a = 2;
            bar(out a, a);
        }
    }
```

The suggested change is to remove ` = 2`. This results in a compilation error, because the variable `a` is not assigned prior to its use in the call to `bar`.
Interestingly, if I mouse hover over the suggested fix to see a preview, there is a red squiggly line under the second a in the call to `bar` in the preview. The error is already seen by VS before the fix is applied to my code.

Certainly the code could be cleaned up a bit, e.g. by consolidating those two lines as `bar(out int a, 2);`, and such a suggestion would be welcome. But suggesting a change that won't even compile isn't nice.

A bit of a further complication in the code where I actually saw this: using `bar(out int a, 2);` doesn't always work. Here's an example:
```cs
    abstract class Foo
    {
        protected abstract void bar(out int v1, int v2);

        public Foo()
        {
            int a = 2;
        label1:
            bar(out a, a);
            if (a > 0) goto label1;   
        }
    }
```
Obviously the use of goto is bad, and I've already re-structured the code in a way that avoids this issue, so this isn't an important issue at all in my case. But I thought I'd report this bug anyway.

---
#### Feedback Bot on 5/15/2022, 07:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by svick** [comment] 2022-05-17 09:29
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/61347.

**Comment by RikkiGibson** [comment] 2022-05-20 17:59
@svick did you mean to refer to a different issue?

**Comment by svick** [comment] 2022-05-20 20:34
@RikkiGibson Sorry, yes, I meant https://github.com/dotnet/roslyn/issues/58564.

**Comment by RikkiGibson** [comment] 2022-05-20 20:41
Duplicate of #58564

**Closed by RikkiGibson** 2022-05-20 20:41 UTC
Labels: Bug, Resolution-Duplicate, help wanted, Area-IDE, IDE-CodeStyle

**Comment by Neme12** [comment] 2022-05-20 20:47
@svick @RikkiGibson  This doesn't look like a duplicate of that issue to me. In the other issue, the `out` parameter is marked as an unnecessary assignment, whereas here, it's the assignment at the declaration. Even if these issues have the same root cause, this is a different case and if this is closed in favor of that, the case in this issue should be mentioned in the other issue as well so that tests could be added for both cases and both should be verified when it's fixed.
