### ISSUE TITLE
Extern alias fails with forwarded types

### ISSUE THREAD

**Issue by morganbr** [dotnet/roslyn#27375] opened 2018-06-02 03:22 UTC
Using an ```extern alias``` namespace on a type reference where the aliased assembly has forwarded it to another assembly (that is passed to Roslyn as a reference) fails to resolve the type with an error that says to add a reference to the implementation assembly that's already referenced:
>error CS1069: The type name 'MyClass' could not be found in the namespace 'MyNamespace'. This type has been forwarded to assembly 'Implementation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' Consider adding a reference to that assembly.

**Version Used**: 2.7.0.62715 (db02128e) and 2.9.0.62911 (db548657)

**Steps to Reproduce**:

1. Create a class in Implementation.dll
```
namespace MyNamespace
{
    public class MyClass
    {
    }
}
```

2. Create a Forwarder.dll that forwards that class 
```
[assembly:TypeForwardedTo(typeof(MyNamespace.MyClass))]
```
3. Create a main dll or exe with the following an extern alias reference to MyClass:
```
extern alias Forwarder_Assembly;
class Program
{
    static void Main(string[] args)
    {
        Forwarder_Assembly::MyNamespace.MyClass myClass = new Forwarder_Assembly::MyNamespace.MyClass();
    }
}
```
4. Try to build the main exe with references to both the forwarder and implementation dlls and pointing the alias at the forwarder assembly:
```
csc Program.cs /r:Forwarder_Assembly=Forwarder.dll /r:Implementation.dll
```

**Expected Behavior**: The type reference resolves and program compiles (I'm not sure whether it should refer to the forwarder or implementation, but either is ok).

**Actual Behavior**: Error that says to add a reference to the implementation assembly that's already there:
>error CS1069: The type name 'MyClass' could not be found in the namespace 'MyNamespace'. This type has been forwarded to assembly 'Implementation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' Consider adding a reference to that assembly.

**Comment by cston** [comment] 2018-06-25 15:02
Currently forwarded types are not exposed as symbols from the forwarding assembly so lookup fails when the type is qualified with an alias to the forwarding assembly. Fixing this is likely to be a significant change. Closing as by design for now. @morganbr, please re-open this issue if it is blocking.

**Closed by cston** 2018-06-25 15:02 UTC
Labels: Area-Compilers, Bug

**Comment by morganbr** [comment] 2018-06-29 04:04
Confirmed we can work around this. In case anyone else hits this, we were able to work around it by referencing the Implementation.dll twice -- once with the alias and once without.
