### ISSUE TITLE
Light bulb incorrectly tries to simplify Nullable<T> in cref doc comments

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#1698] opened 2015-03-31 18:01 UTC
Repro
-----

``` C#
using System;

/// <summary>
/// <see cref="Nullable{T}"/>
/// </summary>
class C
{
}
```

or

``` VB
Imports System

''' <summary>
''' <see cref="Nullable(Of T)"/>
''' </summary>
Class C
End Class
```

The cref is incorrectly flagged as able to be simplified to `T?` in both languages where it should remain `Nullable{T}` or `Nullable(Of T)`.

**Comment by sharwell** [comment] 2015-04-04 06:50
Duplicate of #29.

**Comment by srivatsn** [comment] 2015-04-05 22:52
Closing this one - we'll use #29 to track this issue.

**Closed by srivatsn** 2015-04-05 22:52 UTC
Labels: Area-Analyzers, Bug
