### ISSUE TITLE
Type precedence in new operator [method parameter case]

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14084] opened 2016-09-26 21:21 UTC
**Version Used**: 2.0.0.606923

**Steps to Reproduce**:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            object o;
            string s;

            Test(new |
            o = s;
        }
        static void Test(TimeSpan t) { }
    }
}
```

**Expected Behavior**:
`TimeSpan` to be preselected in the autocomplete list.

**Actual Behavior**:
`string` preselected

I guess all the issues reported for declaration should also work in the case of a method parameter?
cf. #2836 #12755 #13402 
 /cc @balajikris @rchande

**Comment by rchande** [comment] 2016-11-22 22:14
This is not a dupe of the bugs listed in https://github.com/dotnet/roslyn/pull/15093 but is an error recovery issue. Note the lack of close paren in the object creation expression.

**Comment by miloush** [comment] 2016-12-08 17:00
Yeah, I have automatic brace completion off. The editing experience with this setting seems to be regressing dramatically from previous versions. :(

**Closed** 2017-01-06 23:38 UTC
Labels: Area-IDE
