### ISSUE TITLE
IntelliSense would only show suggestions based on matching type, not random suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59247] opened 2022-02-03 19:52 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-would-only-show-suggestions/1639466)._

---
As you can see, there are so many suggestions which the user will never choose because their type does not match.
They can be removed to prevent accidental choosing when typing very fast on keyboard especially in VS 2022 where IntelliSense is slower than in VS 2019.
! [visual studio suggestion.png] (https://aka.ms/dc/image?name=Beb37efbaf96c4f5290174f918593df38637780457552769075_visual_studio_suggestion.png&tid=eb37efbaf96c4f5290174f918593df38637780457552769075)

In the example below, you can see that only int can be assigned to int but random items are shown which the user will never choose.

---
#### Feedback Bot on 1/17/2022, 10:00 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment] 2022-02-03 19:59
These are all relevant as they may be hte start of some expressio that can return an int.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:42
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-22 19:42 UTC
Labels: Question, Area-IDE, Resolution-Answered, Developer Community
