### ISSUE TITLE
Tool to help locating C# global code causing CS7022 for the real Main()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54950] opened 2021-07-19 21:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Tool-to-help-locating-C-global-code-cau/1456406)._

---
Problem:  Accidental global c# 9 code can take over from main() and is nearly impossible to find.

With the new c# global code feature, any extra semicolon or pair of brackets {} outside of a name space will take over from Program { Main() {}} and become the new main method.  This will generate a CS7022 warning on the Main() method, which is good, but it is VERY difficult to find the global code that has taken over!    The code will compile and run and do absolutely nothing if there is an extra semicolon or {}.    Try dropping a pair of {} after the include statements but before the namespace in any file in a working application and just try and find the problem!  The more cs files you have, the harder the job is to find the problem.

There should be some way to search or navigate to the code that is acting as Main() for the application.  I would suggest that the CS7022 warning have a hint to take you to the real main code.  Maybe if main() worked like an overrides, the navigation could behave like class hierarchy navigation.

---
#### Feedback Bot on 6/21/2021, 07:52 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by RikkiGibson** [comment] 2021-07-20 03:24
We did address this for empty statements in #53472 but not for empty blocks, I think.

**Comment by jcouv** [comment] 2021-08-23 19:34
FYI @AlekseyTs . We've already made a fix for empty top-level statement (extra `;`), but this bug ran into a similar issue with an empty block `{}`.

**Comment by AlekseyTs** [comment] 2021-08-24 17:47
Debugger can be used to locate the global code. Pressing F10 in Visual Studio stops at the first statement, including an empty block.

**Comment by jcouv** [comment] 2021-09-28 18:23
Looks like the issue is resolved. I'll go ahead and close this issue. We'll keep an ear out for other folks running into a problem with empty block.

**Closed by jcouv** 2021-09-28 18:23 UTC
Labels: Area-IDE, Area-Compilers, New Language Feature - Simple Programs, untriaged
