### ISSUE TITLE
EditorBrowsable is useless for source generators to hide stuff

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#60080] opened 2022-03-10 03:31 UTC
**Version Used**: 
Version 17.2.0 Preview 2.0 [32303.453.main]

**Steps to Reproduce**:
Paste this and then start typing `SomeNamespace.`
```C#
using System.ComponentModel;

namespace SomeNamespace
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    internal class CoolTypeNotToBeUsed
    {
    }
}
``` 

**Expected Behavior**:
`CoolTypeNotToBeUsed` doesn't show up in IntelliSense.

**Actual Behavior**:
It shows up.
<img width="429" alt="image" src="https://user-images.githubusercontent.com/2642209/157583039-2372ec6a-cdb1-4e92-8e9b-e69773819fa4.png">

As it turns out, I shouldn't be surprised... the docs are pretty clear:
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=net-6.0
"Specifies that a property or method"... so, not a type
"In Visual C#, EditorBrowsableAttribute does not suppress members from a class in the same assembly."... so, yeah

But this makes EditorBrowsableAttribute useless for source generators that want to emit code that's not browsable by the rest of the library.

We should either change the meaning of EditorBrowsableState.Never in the IDE to actually mean "Never, not even in the same assembly", or we should add a new "NeverNotEvenInTheSameAssembly" state that does the right thing.

cc: @terrajobst, @jaredpar

**Comment by sharwell** [comment] 2022-03-10 19:31
Duplicate of #51269

**Closed by sharwell** 2022-03-10 19:31 UTC
Labels: Area-IDE, untriaged
