### ISSUE TITLE
Inline rename couldn't rename a file

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#56467] opened 2021-09-16 23:45 UTC
**Version Used**:  Version 17.0.0 Preview 5.0 [31715.371.main]

![image](https://user-images.githubusercontent.com/754264/133702518-412ea7e5-cf18-4346-866b-6adbbe1a4ac7.png)

```
System.Exception : Unable to check out the files from source control.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments(IEnumerable`1 documents)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyRename(Solution newSolution,IUIThreadOperationContext operationContext)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IUIThreadOperationContext operationContext,Boolean previewChanges)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(UIThreadOperationExecutionOptions executionOptions,Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.Commit(InlineRenameSession activeSession,ITextView textView)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ryzngard** [comment] 2021-09-22 20:08
@genlu we're hitting this multiple times. Can we revisit this design? What was the context we originally needed to have `Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments` ?

**Comment by genlu** [comment] 2021-09-22 21:34
I remember making changes to exclude editable document by querying `IDocumentService`, but it happens before passing documents to workspace for making edits. The error here is caused by querying a [VS service](https://devdiv.visualstudio.com/DevDiv/_git/VSTeamExplorer?path=/VSIntegration/Client/Git/Provider/Services/SccService/IVsQueryEditQuerySave2.cs), which is separate from `IDocumentService` and I don't know anything about. Maybe we should sync with the git provider team to discuss a potential mitigation for this.

**Comment by ryzngard** [comment] 2021-09-22 22:21
@genlu I see... IMO it'd be nice to just remove this check. The only thing that will happen without it is that the change will fail _if_ it actually can't be modified. Having this check only adds another point of failure for us.

**Comment by genlu** [comment] 2021-09-28 19:58
Maybe showing a warning in goldbar and skip the problematic file, instead of removing the check completely?

**Comment by DavidKarlas** [comment] 2021-11-02 06:56
@davidwengier let me guess, that file is referenced in multiple projects?
This is duplicate of https://github.com/dotnet/roslyn/issues/45031 that I listed nice repro steps and explanation of bug...
https://github.com/dotnet/roslyn/issues/45031#issuecomment-784889615

**Comment by davidwengier** [comment] 2021-11-02 09:19
I can't remember exactly, but looking at the nav bar, yes it seems like it would have been a multi-targeted project.

**Closed** 2021-11-12 22:45 UTC
Labels: Bug, Area-IDE
