### ISSUE TITLE
[Proposal] Void returning Func<T>

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#5037] opened 2015-09-05 08:09 UTC
`Func<T>` is a function that returns a `T` is fairly simple to understand, but is has the caveat that the `T` can not be `Void`. If `T` could be `Void` then `Action<>` would the equivalent to a `Func<Void>`

This would allow us to conceptually consider the proposed match expression (#5016) as a ` Func<...,T>`. Permitting it to also used a statement.
```c#
...
match ( ... )
{
  |: ... => foo();
  |: ... => bar();
  |: ... => baz();
  |: => meh();  
}();
...
```

One could write `return void;`, or it could be implicitly inferred.
```c#
  => void;
  => { return void };
  => { ...;
       return void
     };
  => { ... }
```

**Comment by HaloFour** [comment] 2015-09-05 18:29
What makes this different from #234 or #166?

`Func<T>` is just a standard delegate, like countless others (including the other 16 `Func<T, ...>` delegates that ship with the framework).

Are you asking to make `void`/`Void` a possible generic type argument?  Short of having a placeholder type like `System.Void` which would serve as a unit type I don't see how that would even approach being possible.  There is only one IL body for any given generic method and it must be valid regardless of the generic type arguments, but that's certainly not possible if one of those arguments if `void` as that interferes with how the method could interact with the evaluation stack.

Even if you were to treat `Func<T>` and `Action` as special cases among the massive ecosystem of delegates they could not be compatible as they have different requirements of the caller.  Invoking the former pushes a value onto the evaluation stack that the caller is required to at least pop in order to get equivalent semantics.

**Comment by gafter** [comment] 2015-09-06 05:32
Duplicate of #234

**Closed** 2015-09-06 05:32 UTC
Labels: Area-Language Design
