### ISSUE TITLE
Simplify Type Name on statics of derived types sometimes seems overly pedantic

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#12987] opened 2016-08-07 23:27 UTC
**Version Used**: 14.0.25421.03 Update 3

![image](https://cloud.githubusercontent.com/assets/235241/17466079/8140e68e-5cbb-11e6-963a-0692a78cb15b.png)

Is this intentional? The `Ellipse.` version is arguably more readable, since I'm dealing in Ellipses in the surrounding code. And I wouldn't want to turn off Simplify Type Name in its entirety to get around this.

**Comment by Pilchie** [comment] 2016-08-08 16:18
Related/dupe of #11820 and/or #11821

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:31
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-19 21:31 UTC
Labels: Bug, Area-IDE
