### ISSUE TITLE
Allow stepping through object init blocks

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/roslyn#63383] opened 2022-08-13 17:08 UTC
## Summary

Treat object init blocks as a series of separate steps for debugging purposes

## Background and Motivation

Given the powerful syntax for collections,etc., sometimes I end up compacting a lot of code into the init block, and currently it's only "one step" - no way to set a breakpoint in the middle, see where exactly an exception is raised from, etc. 

## Proposed Feature

```cs
var x = new Foo
{
  Prop = "abc",
  List = {
    new Bar
    {
      OtherProp = 123,
    }
  },
};
```
These new "steps" should be recognized (after `x = new Foo`):
- Set `Prop` (the `Foo` instance should be visible in Locals and/or Auto watch windows)
- `new Bar`
- Set `OtherProp` (the `Foo` and `Bar` instances should be visible in Locals and/or Auto watch windows)
- Add `Bar` to `List` (the `Foo` and `Bar` instances should be visible in Locals and/or Auto watch windows)

## Alternative Designs

N/A

**Comment by dibarbet** [comment] 2022-08-15 18:46
@tmat would this be a feature request on the debugger or us?

**Comment by dibarbet** [comment] 2022-08-15 18:48
duplicate of https://github.com/dotnet/roslyn/issues/27184

**Closed by dibarbet** 2022-08-15 18:48 UTC
Labels: Area-IDE, Feature Request, untriaged
