### ISSUE TITLE
[Failing Test] CSharpGotoDefinition.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15740] opened 2016-12-07 23:07 UTC
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/121/console

...

16:05:02  Scenario: Go To Definition with multiple results
16:05:02 	Executing action [12/9/2016 11:59:45 PM] SetEditorText
16:05:02 	Executing action [12/9/2016 11:59:45 PM] WaitForWorkspace
16:05:02 	Executing action [12/9/2016 11:59:45 PM] PlaceCursor
16:05:02 	Executing action [12/9/2016 11:59:45 PM] GoToDefinition
16:05:02 --------------------------------
16:05:02 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
16:05:02    at Roslyn.VSHosting.Test.RoslynInProcessAPI.DumpListContents(IVsSimpleObjectList2 objectList, List`1 result) in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 897
16:05:02    at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass113_0.<GetFindSymbolResults>b__0() in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 888
16:05:02    --- End of inner exception stack trace ---
16:05:02    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
16:05:02    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
16:05:02    at System.Delegate.DynamicInvokeImpl(Object[] args)
16:05:02    at System.Delegate.DynamicInvoke(Object[] args)
16:05:02    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values)
16:05:02    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
16:05:02 ================================
16:05:02 
16:05:02

**Comment by CyrusNajmabadi** [comment] 2016-12-10 00:17
Dupe of https://github.com/dotnet/roslyn/issues/15461

**Closed by CyrusNajmabadi** 2016-12-10 00:17 UTC
Labels: Area-IDE, Bug, Test
