### ISSUE TITLE
Using a property inside its own implementation should warn

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#40935] opened 2020-01-13 20:49 UTC
Original report from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1050548:

> I was having problem where my application would terminate unexpectedly without throwing an exception:
> 
> The target process exited with code -1073741819
> 
> I finally tracked it down to a typo in a property getter.
> 
> Here is a simplified snippet; as you can see I made a typo and switched on the value of MyProperty within the MyProperty getter:
> 
> ```csharp
> public double? MyProperty
> {
>    get
>    {
>       switch (MyProperty)
>       {
>       case 128:
>           ...
>       }
>    }
> }
> ```

**Comment by Youssef1313** [comment] 2022-07-02 17:00
Isn't is possible the property is called in its implementation under a certain condition that, at some point, stops the cycle?

I don't see why this would be different than a method called in its own implementation? A getter, at the end of the day, is a method.

**Comment by YoshiRulz** [comment] 2024-03-06 06:08
see also #9827

**Comment by CyrusNajmabadi** [comment] 2024-11-22 01:10
Dupe of https://github.com/dotnet/roslyn/issues/9827

**Closed by CyrusNajmabadi** 2024-11-22 01:10 UTC
Labels: Area-Compilers, Feature Request, New Feature - Warning Waves
