### ISSUE TITLE
Value origin and value destination views in Visual Studio

### ISSUE THREAD

**Issue by Avisharper** [dotnet/roslyn#49623] opened 2020-11-25 19:59 UTC
Visual studio is missing a very helpful view that allows tracking the origin or destination of a value.
This is especially effective when debugging to understand how a specific value in a method got there.
The view should be a tree view.
For value origin - the root is the variable/parameter we are searching on and the tree branches where each level is a potential code path from which the value could have originated - similar to a call stack.
For value destination the tree is the potential paths the value can be passed to different code paths.
Resharper has a similar feature

**Comment by jinujoseph** [comment] 2020-12-01 19:34
Duplicate of https://github.com/dotnet/roslyn/issues/25994

**Closed by jinujoseph** 2020-12-01 19:34 UTC
Labels: Area-Interactive
