### ISSUE TITLE
Roslyn does not load project documents in Visual Studio 15.3.2

### ISSUE THREAD

**Issue by Qrious** [dotnet/roslyn#21689] opened 2017-08-23 13:02 UTC
**Version Used**:  Visual Studio 15.3.2, Visual Studio 15.2
Nuget package: 2.3.1

I've created a minimal case for reproduction, this issue was first encountered with our internal company tooling that does no longer work after people upgrade to Visual Studio 15.3.2. 

The minimal sample app consists of two .Net 4.6.1 ConsoleApp's. The first one consists of a Hello World, while the other one uses roslyn to load documents from ConsoleApp. I've included screenshots of a machine running 15.2 with a working roslyndocuments, and a screenshot of a machine running 15.3 at which roslyndocuments does not work

This might be related to https://github.com/dotnet/roslyn/issues/21660 ?

**Steps to Reproduce**:
1. clone minimal case at https://github.com/Qrious/roslyndocuments
2. Run Roslynapp with Visual studio 15.2. It should show the files as shown in the Expected Behaviour screenshot below
3. Run Roslynapp with Visual studio 15.3.2.  It no longer shows any documents for the ConsoleApp project.

**Expected Behavior**:
![roslyn-15 2](https://user-images.githubusercontent.com/680327/29616662-866a8b28-8812-11e7-8bf6-fe61a16dd1d2.jpg)
**Actual Behavior**:
![roslyn-15 3 2](https://user-images.githubusercontent.com/680327/29617037-affeec26-8813-11e7-95a9-eba40c8160db.jpg)

**Comment by Qrious** [comment] 2017-08-23 14:02
After some further digging i found that this problem seems to be related to https://github.com/dotnet/roslyn/issues/21583.
The workaround mentioned in https://github.com/neuecc/MessagePack-CSharp/issues/108 works.

**Comment by Pilchie** [comment] 2017-08-23 16:21
FYI @DustinCampbell 

Closing this as a duplicate of #21583

**Closed** 2017-08-23 16:22 UTC
Labels: Area-IDE
