### ISSUE TITLE
TestSimpleInstanceProperty_VisualBasicToCSharp failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9249] opened 2016-02-26 19:10 UTC
```   Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateVariable.GenerateVariableCrossLanguageTests.TestSimpleInstanceProperty_VisualBasicToCSharp
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        src\EditorFeatures\Test2\Diagnostics\AbstractCrossLanguageUserDiagnosticTest.vb(42,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_4_TestAsync.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        src\EditorFeatures\Test2\Diagnostics\GenerateFromUsage\GenerateVariableCrossLanguageTests.vb(55,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateVariable.GenerateVariableCrossLanguageTests.VB$StateMachine_2_TestSimpleInstanceProperty_VisualBasicToCSharp.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by heejaechang** [comment] 2016-03-02 21:25
@srivatsn @Pilchie is this update 2 bug or regular bug?

**Comment by Pilchie** [comment] 2016-03-02 21:29
In general, we'd like to drive down flakiness in tests for 1.2 if possible, since it improves our ability to validate the release.

In this particular case, this is likely the same issue that @jasonmalinowski is already investigating

**Comment by davkean** [comment] 2016-03-07 00:41
Dupe of https://github.com/dotnet/roslyn/issues/9308

**Closed by davkean** 2016-03-07 00:41 UTC
Labels: Area-Analyzers, Flaky, Test
