### ISSUE TITLE
Track null state through ref assignments to ref ternaries

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33025] opened 2019-01-31 22:40 UTC
The following program produces no warnings

``` c#
#nullable enable

class Program
{
    static void Main(string[] args)
    {
        string? a = "", b = "";
        (args.Length == 0 ? ref a : ref b) = null;
        _ = a.Length; // expected warning possible null dereference
    }
}
```

**Comment by jcouv** [comment] 2019-03-20 00:05
Closing as duplicate of https://github.com/dotnet/roslyn/issues/33365

**Closed by jcouv** 2019-03-20 00:05 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
