### ISSUE TITLE
Type, implicitly castable to awaitable, can not be awaited

### ISSUE THREAD

**Issue by Eranikid** [dotnet/roslyn#34381] opened 2019-03-23 12:23 UTC
# Type, implicitly convertible to awaitable, can not be awaited

Check the follownig class:
```
public class SomeArbitraryClass
{
  public static implicit operator Task(SomeArbitraryClass someArbitraryClass)
  {
    return Task.CompletedTask;
  }
}
```
It is implicitly castable to `System.Threading.Task` class.
```
Task task = new SomeArbitraryClass();
await task;
```
This code works as expected, but this:
```
await new SomeArbitraryClass();
```
results in `[CS1061] 'SomeArbitraryClass' does not contain a definition for 'GetAwaiter'`. I expect, that a type, implicitly convertible to `Task`, or any other awaitable, should also be awaitable right away, without additional explicit cast.

Am I right, or is this expected behavior?

**Comment by svick** [comment] 2019-03-23 15:38
As far as I can tell, this is the expected behavior according to [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#awaitable-expressions):

> An expression `t` is awaitable if one of the following holds:
> 
> *  `t` is of compile time type `dynamic`
> *  `t` has an accessible instance or extension method called `GetAwaiter` with no parameters and no type parameters, and a return type `A` for which all of the following hold:
>    * `A` implements the interface `System.Runtime.CompilerServices.INotifyCompletion` (hereafter known as `INotifyCompletion` for brevity)
>    * `A` has an accessible, readable instance property `IsCompleted` of type `bool`
>    * `A` has an accessible instance method `GetResult` with no parameters and no type parameters

If you would like to propose changing that, then the right place is [the csharplang repo](https://github.com/dotnet/csharplang). Though I'm not sure how likely is it that such a proposal would be accepted, especially since implementing the required pattern in cases like this is quite simple:

```c#
public class SomeArbitraryClass
{
    public TaskAwaiter GetAwaiter() => Task.CompletedTask.GetAwaiter();
}
```

**Comment by gafter** [comment] 2019-03-26 16:49
Closing as by design.  If you'd like the language design changed, please open an issue in `csharplang`

**Closed by gafter** 2019-03-26 16:49 UTC
Labels: Area-Compilers, Language-C#
