### ISSUE TITLE
Consider not NGEN'ing System.Reflection.Metadata for Update 1

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#6394] opened 2015-10-28 17:44 UTC
This is to work around the known CLR stress bug with that assembly that hits VBCSCompiler.

**Comment by agocke** [comment] 2015-10-28 18:10
@jaredpar @VSadov We should decide on this pretty quickly for update 1.

BTW if the only symptom here is VBCSCompiler crashing then I think it's OK to leave it ngen'd. We will fall back to csc and the user shouldn't really notice. If it can result in VBCSCompiler deadlocking... more of a difficult decision. I would still probably say leave it how it is.

**Comment by VSadov** [comment] 2015-10-28 18:16
Is it going to result in random Watson noise?

**Comment by davkean** [comment] 2015-10-28 21:15
Is it random noise? Wouldn't it bolster the reason to fix it if everyone's hitting it?

**Comment by jaredpar** [comment] 2015-10-28 21:45
@davkean the CLR is actively working on a fix for this bug.  It's unlikely though to make it before we release update 1.  The decision is whether to disable it now, let the CLR fix make it out there, and the start NGEN again.  

I'm leaning towards leaving it NGEN'd for now.  This only reproduces under high stress scenarios that so far we've only been able to replicate in the DevDiv build lab (and not reliably).  I'm sure other customers have hit this but as @agocke points out even if this hits it crashes the server and it falls back to the normal command line compiler.

**Comment by pharring** [comment] 2015-10-28 21:50
@jaredpar We were seeing this at least once a week in the Roslyn perf lab too. Not exactly high stress.

**Comment by dpoeschl** [comment] 2015-11-05 00:23
@pharring @agocke @jaredpar What's the user-visible symptom (just echoing @agocke's thoughts from above). If it causes hangs then @mavasani may want to track this.

**Comment by davkean** [comment] 2015-11-20 03:25
Remove infrastructure, as this is a product bug. Assigning to compiler for now, but feel free to move it the feature team that will do the work.

**Comment by jaredpar** [comment] 2015-11-30 20:16
Won't fixing.  This is a shared DLL so we don't soley own the NGEN decision here.  This has only popped up in limited scenarios, and when it does popup, doesn't impact correctness.  

Will reconsider if we get customer feedback.

**Closed by jaredpar** 2015-11-30 20:16 UTC
Labels: Area-Compilers
