### ISSUE TITLE
IDE0017 Object initialization can be simplified not understanding editorconfig setting.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22802] opened 2017-10-22 07:03 UTC
[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/122440/ide0017-object-initialization-can-be-simplified-no.html)

Running VS 2017 15.3, with default application settings.  
In editorconfig at the root the solution we have set dotnet_style_object_initializer = false:warning

Still seeing IDE0017 Object initialization can be simplified as a suggestion (from default setting)

If change editorconfig to dotnet_style_object_initializer = true:warning

See IDE0017 Object initialization can be simplified as a warning.

It appears the dotnet_style_object_initializer = false:warning is not being observed in any circumstance.

**Comment by sharwell** [comment] 2017-10-22 11:56
I'm not able to reproduce this in C# or VB. It sounds like a duplicate of #15003.

**Comment by drewkg** [comment] 2017-10-22 12:08
I can no longer reproduce this in VS 2017 15.4.1, versions below this I could reproduce reliably in multiple solutions.

**Closed** 2017-10-22 12:16 UTC
Labels: Area-IDE, Bug, Developer Community, Resolution-Not Reproducible
