### ISSUE TITLE
Bootstrap build produces error about DisableSdkPath

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#32053] opened 2018-12-29 04:19 UTC
`build.cmd -bootstrap`

```
...
Build FAILED.

C:\repos\roslyn\artifacts\Bootstrap\tools\Microsoft.CSharp.Core.targets(68,10): error MSB4064: The "DisableSdkPath" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_xaaf1u5k_wpftmp.csproj]
C:\repos\roslyn\artifacts\Bootstrap\tools\Microsoft.CSharp.Core.targets(52,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.  [C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.Editor
Features.Wpf_xaaf1u5k_wpftmp.csproj]
```

Tagging @RikkiGibson @jaredpar as FYI

**Comment by rainersigwald** [comment] 2019-01-18 16:38
Looking at the binlog from https://github.com/dotnet/roslyn/pull/32473#issuecomment-455054522, I see:

```
...
06:50:39.162 40:24>Project "D:\Temp\breuerTobiasRoslyn\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj" (40:24) is building "D:\Temp\breuerTobiasRoslyn\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_atgkoygu_wpftmp.csproj" (162) on node 3 (_CompileTemporaryAssembly target(s)).
...
06:52:32.729   162>Target "CoreCompile: (TargetId:184)" in file "D:\Temp\breuerTobiasRoslyn\roslyn\artifacts\Bootstrap\tools\Microsoft.CSharp.Core.targets" from project "D:\Temp\breuerTobiasRoslyn\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_atgkoygu_wpftmp.csproj" (target "_CompileTemporaryAssembly" depends on it):
                   Building target "CoreCompile" completely.
                   Output file "D:\Temp\breuerTobiasRoslyn\roslyn\artifacts\obj\Microsoft.CodeAnalysis.EditorFeatures.Wpf\Debug\net472\Microsoft.CodeAnalysis.EditorFeatures.Wpf.xml" does not exist.
                   Set Property: NoWarn=;1701;1702;1705;1591;NU5125;1573;1591;1701;1701;1702
                   Using "Csc" task from assembly "C:\Users\breuer_to\.nuget\packages\microsoft.net.compilers\2.9.0-beta7-63018-03\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll".
...
06:52:32.743   162>D:\Temp\breuerTobiasRoslyn\roslyn\artifacts\Bootstrap\tools\Microsoft.CSharp.Core.targets(68,10): error MSB4064: The "DisableSdkPath" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [D:\Temp\breuerTobiasRoslyn\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_atgkoygu_wpftmp.csproj]
06:52:32.745   162>D:\Temp\breuerTobiasRoslyn\roslyn\artifacts\Bootstrap\tools\Microsoft.CSharp.Core.targets(52,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.  [D:\Temp\breuerTobiasRoslyn\roslyn\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_atgkoygu_wpftmp.csproj]
                   Done executing task "Csc" -- FAILED. (TaskId:155)
```

Looks like the targets override for bootstrap is working (the task is called with the new argument) but the UsingTask override from the NuGet package has somehow won over the override from the bootstrap stuff.

**Comment by rainersigwald** [comment] 2019-01-18 17:57
`microsoft.dotnet.arcade.sdk\1.0.0-beta.19064.4\tools\Settings.props` imports NuGet properties:

```xml
  <!--
    Import NuGet props to WPF temp projects (workaround for https://github.com/dotnet/sourcelink/issues/91) 
  -->
  <Import Project="$(_WpfTempProjectNuGetFilePathNoExt).props" Condition="'$(_WpfTempProjectNuGetFilePathNoExt)' != '' and Exists('$(_WpfTempProjectNuGetFilePathNoExt).props')"/>
```

Roslyn's Settings.props sets a `UsingTask` for `ValidateBootstrap` in the same task assembly, but defers to 
the bootstrap package to do the `Csc` task
https://github.com/dotnet/roslyn/blob/fc965b58756e08aa99e238cbf2e60afbfbedcae4/eng/targets/Settings.props#L130-L134



That comes after the NuGet import, so it should override
![image](https://user-images.githubusercontent.com/3347530/51401995-e6146100-1b11-11e9-9178-eedc91e77a4c.png)

And the .props has nice, straightforward file references that shouldn't be subject to delayed property override:

https://github.com/dotnet/roslyn/blob/8a34dfb2e06bdb4807c82419b5bb36e692967139/src/NuGet/Microsoft.Net.Compilers/build/Microsoft.Net.Compilers.props#L21-L28

So that all seems ok. Which isn't what I was expecting! Not sure what the problem is.

**Comment by TobiasBreuer** [comment] 2019-01-20 10:48
I think I'm getting closer and would like to share my current progress... 

After debugging MSBuild (current master of MSBuild) for a little while and getting my head around what is going on in there, I'm currently looking at `TaskRegistry` especially at `GetRelevantRegistrations` and `GetMatchingRegistration`.

In `GetMatchingRegistration` there are cases (meaning 155 times) where there are multiple (meaning exactly 2) candidates given in the taskRecords List for the tasks

- Microsoft.CodeAnalysis.BuildTasks.Csc and
- Microsoft.CodeAnalysis.BuildTasks.Vbc

Out of those 155 times where this happens, in 7 cases, the order of the candidates is "wrong" - where "wrong" in this case means, that the order is (The values show the Property `RegisteredTaskRecord.TaskFactoryAssemblyLoadInfo.AssemblyLocation`):
```
[0] "C:\Users\breuer_to\.nuget\packages\microsoft.net.compilers\2.9.0-beta7-63018-03\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll"
[1] "D:\Temp\breuerTobiasRoslyn\roslyn\artifacts\Bootstrap\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll"
```
In all other cases, the order is the other way round. 
These 7 cases are given when building the targets for the following projects:
```
- src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf_40112gsj_wpftmp.csproj
- src\VisualStudio\Core\Def\Microsoft.VisualStudio.LanguageServices_gztxr0cb_wpftmp.csproj
- src\VisualStudio\Core\Impl\Microsoft.VisualStudio.LanguageServices.Implementation_tvlqxaba_wpftmp.csproj
- src\VisualStudio\CSharp\Impl\Microsoft.VisualStudio.LanguageServices.CSharp_d2powiwz_wpftmp.csproj
- src\VisualStudio\VisualBasic\Impl\Microsoft.VisualStudio.LanguageServices.VisualBasic_gn1xndku_wpftmp.vbproj
- src\Test\Diagnostics\Roslyn.Hosting.Diagnostics_yevfvqi1_wpftmp.csproj
- src\VisualStudio\VisualStudioDiagnosticsToolWindow\Roslyn.VisualStudio.DiagnosticsWindow_13ktqd1u_wpftmp.csproj
```
And there are exactly 7 of such projects that have a _wpftmp_ suffix. So for every of these temporary projects created during the build, the order of "task factory candidates" is "wrong". 

As `GetMatchingRegistration` returns the first `record` for which `CanTaskBeCreatedByFactory` returns true, the build will fail for those 7 temporary projects. 

The question is now of course
- Why is it "wrong"  - and especially:
- Why is it that way only on certain machines and not for every environment...

I'm going to look further into this and see if I can narrow it down further - but I'm in no way an MSBuild expert  - so if you @rainersigwald have any idea on where to look next please let me know 😉. 

As I'm not an expert, please don't shot me for the following question: 
Shouldn't `CanTaskBeCreatedByFactory` also take the parameters of the task into account for checking if the factory can be used for the requested task? If this would be a reasonable extension for this check I could open up a PR for MSBuild with such functionality if desired.

**Comment by davkean** [comment] 2019-01-21 06:01
@Pilchie Did we file a bug on WPF temp project not picking up NuGet targets? Can we dupe this against it.

**Comment by jcouv** [comment] 2019-10-29 17:49
I'm still hitting this.

**Comment by jcouv** [comment] 2019-10-29 19:32
@jaredpar 
The issue with `build -bootstrap` I ran into this morning was fixed by adding `-restore`. Thanks Andy for the tip

**Comment by RikkiGibson** [comment] 2019-12-03 22:26
It sounds like this is resolved, so I will close this.

**Closed by RikkiGibson** 2019-12-03 22:26 UTC
Labels: Area-Infrastructure
