### ISSUE TITLE
"Create and assign [field|property]" quick fix generates Linux line endings on Windows machine/project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70685] opened 2023-11-02 22:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-and-assign-fieldproperty-qui/10502148)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.7.5]
After the latest update, I've noticed a pretty annoying behavior change in the "Create and assign [field|property]" quick fix, which I use extensively to add parameters to constructors in my code.

After applying the refactoring, the line ending on the constructor line is terminated with an LF only instead of CR/LF. This would be fine if either the system or the .editorconfig settings were configured this way, but I'm on a Windows machine, on a windows-based project, and my .editorconfig is explicitly configured to use 'crlf' line endings.

This forces me to close the tab and reopen it, so that Visual Studio then can show me the standard "line endings are mismatched" popup window and I can fix it and amend my changes.

---
#### Feedback Bot on 10/30/2023, 02:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by julealgon** [comment] 2024-01-25 15:21
Is there any ETA for triaging to happen on these issues?

**Comment by sharwell** [comment] 2024-01-25 15:26
I am not able to reproduce this so far.

**Comment by sharwell** [comment] 2024-01-29 14:49
> > Note that per #71659, it is not recommended that **.editorconfig** specify a value for `end_of_line`.
> 
> I'm a bit confused by this. The issue you linked doesn't seem to mention it not being recommended anywhere. Am I missing something?

#71659 is part of the follow-up to https://github.com/dotnet/roslyn/issues/55526#issuecomment-1165003397.

**Comment by sharwell** [comment] 2024-01-29 14:49
Duplicate of #67739

**Closed by sharwell** 2024-01-29 14:49 UTC
Labels: Area-IDE, untriaged
