### ISSUE TITLE
Can't debug CSharpCompilerSymbolTest

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#20288] opened 2017-06-16 21:51 UTC
**Version Used**: VS 15.3 Preview 2, Roslyn source from master (16ea994)

**Steps to Reproduce**:

Follow [the guide](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md) to debug a test in CSharpCompilerSymbolTest:

1. Run `Restore.cmd`.
2. Open `Roslyn.sln` in VS.
3. Set CSharpCompilerSymbolTest as the startup project.
4. Set a breakpoint for example on the first line of `VersionUnification_MultipleVersions` in `Compilation/ReferenceManagerTests.cs` (line 119).
5. Press F5 to Start debugging.

**Expected Behavior**:

All the tests are run, the breakpoint is hit.

**Actual Behavior**:

All the tests seem to be run, the breakpoint is *not* hit.

Debugging some other projects (e.g. CSharpCompilerSemanticTest) works fine.

Should this work? Is it possible that I'm doing something wrong? Or that there is something wrong with my machine?

**Comment by jaredpar** [comment] 2017-06-16 22:49
Thanks taking the time to report this. This is a dupe of #20189 which we are actively looking into.

**Closed by jaredpar** 2017-06-16 22:49 UTC
