### ISSUE TITLE
Generating overrides from C# to VB include broken <Nullable> attributes

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#56384] opened 2021-09-14 19:00 UTC
For example:

```vb
        Public Overrides Function GetFileBanner(<NullableAttribute(1)> root As SyntaxNode) As Immutable.ImmutableArray(Of SyntaxTrivia)
            Throw New NotImplementedException()
        End Function

        Public Overrides Function GetFileBanner(firstToken As SyntaxToken) As Immutable.ImmutableArray(Of SyntaxTrivia)
            Throw New NotImplementedException()
        End Function

        Public Overrides Function GetBannerText(<NullableAttribute(2)> documentationCommentTriviaSyntax As SyntaxNode, maxBannerLength As Integer, cancellationToken As Threading.CancellationToken) As String
            Throw New NotImplementedException()
        End Function
    End Class
```

First, these types are not defined here.  Second, they're not useful as nothing validates them.  We should strip out these attributes when generating VB.

**Comment by jinujoseph** [comment] 2021-09-15 17:21
Duplicate of #42920

**Closed by jinujoseph** 2021-09-15 17:21 UTC
Labels: Bug, Area-IDE
