### ISSUE TITLE
SigHelp shows incorrect signature

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#14241] opened 2016-10-03 13:00 UTC
**Version Used**: VS '15' Preview 4

**Steps to Reproduce**:

1. Add `Console.WriteLine("Hello, World");`
2. Move caret to somewhere inside the parameter list
3. Press Ctrl+Shift+Space to bring up Signature Help

**Expected Behavior**:

I expect to see the correct signature `WriteLine(string)`

**Actual Behavior**:

Seems like it picks the first method with the right number of params, `WriteLine(bool)` is shown instead.

![sighlp](https://cloud.githubusercontent.com/assets/1060731/19037654/aa60bbe6-8977-11e6-8667-1e294c4d763b.png)

Sometimes I'd like to quickly see which method it is or to read param docs and pressing Ctrl+Shift+Space is quicker than using the mouse or moving the caret to the method and pressing Ctrl+K,Ctrl+I.

**Comment by Pilchie** [comment] 2016-10-17 16:35
This is a duplicate of #6713

**Closed by Pilchie** 2016-10-17 16:35 UTC
Labels: Area-IDE, Resolution-Duplicate
