### ISSUE TITLE
Roslyn 1.3.2 fails to add any MetadataReferenece to any project for fly-man-/halcyon [MSBuildWorkspace]

### ISSUE THREAD

**Issue by vedun-z** [dotnet/roslyn#12675] opened 2016-07-22 15:19 UTC
Rolsyn 1.3.2 fails to add any MetadataReference to any project for https://github.com/fly-man-/halcyon. 

I've written a simple example that demonstrates such behavior: 
https://gist.github.com/vedun-z/d2aec4e4c337c199be771284e9f1b636

However, msbuild builds halcyon successfully. 

I use runprebuild2015.bat to generate solution file.

It seems that the problem appears in this code (CSharpProjectFileLoader.CSharpProjectFile.cs:47):

``` C#

 public override async Task<ProjectFileInfo> GetProjectFileInfoAsync(CancellationToken cancellationToken) {
               var compilerInputs = new CSharpCompilerInputs(this);
                var executedProject = await this.BuildAsync("Csc", compilerInputs, cancellationToken).ConfigureAwait(false);

                if (!compilerInputs.Initialized)
                {
                    // if msbuild didn't reach the CSC task for some reason, attempt to initialize using the variables that were defined so far.
                    this.InitializeFromModel(compilerInputs, executedProject);
                }

                return CreateProjectFileInfo(compilerInputs, executedProject);
            }


```

According to the comment, msbuild did't reach the CSC task so lets try to initialize compilerInputs manually. Method InitializeFromModel expects that executedProject.GetItems("ReferencePath") returns paths for MetadataReferences. However, for fly-man-/halcyon projects exectuedPath.Items contains only "Reference" items, so no MetadataReferences are added.  Do you have any ideas why msbuild do not add any "ReferencePath" items?

**Comment by Pilchie** [comment] 2016-07-25 16:49
`ReferencePath` items are populated by the `ResolveAssemblyReferences` task.  If you don't have any, then it likely means that your design time build is failing before you even get to RAR, let alone csc.  Can you hook up a logger to see why your build is failing in the first place.

**Comment by vedun-z** [comment] 2016-07-26 10:41
I think I figure out whats going on.  Unfortunately, ```MSBuildWorkspace.OpenSolutionAsync(solutionPath)``` doesn't do the same things as ```msbuild Solution.sln```. For example, ```OpenSolutionAsync()``` does not taking into account default values for Platform and Configuration Properties. 

Usually, ```.csproj``` file defines default values for Platform and Configuration like this:
```
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
```
However, the definitions can be missed, for example halcyon projects don't define a default value for a Platform property. As long as no Platform is defined,  msbuild cannot find a suitable pair ```$(Configuration)|$(Platform)```, so build fails. Generally, ```MSBuildWorkspace``` expects that build can fail, so it tries to recover build information from ```ProjectInstance```. But ```ProjectInstance``` is also incorrect for the same reason. As a result, ```OpenSoltuonAsync()``` returns ```Solution``` which projects do not have any MetadataReferences.

As a workaround, we can manually pass default build properties to MSBuildWorkpsace:

```cs
 Microsoft.Build.Construction.SolutionFile solutionFile = Microsoft.Build.Construction.SolutionFile.Parse(solutionPath);
string defaultConfiguration = solutionFile.GetDefaultConfigurationName();
string defaultPlatform = solutionFile.GetDefaultPlatformName();

var props = new Dictionary<string, string>();

if (defaultPlatform == "x64" || defaultPlatform == "x86")
{
         props["Platform"] = defaultPlatform;
}

            if (defaultPlatform == "Any CPU")
            {
                props["Platform"] = "AnyCPU";
            }
```

But a default Platform from Solution is not the same as Platform for a project. And I don't know how to handle some default values like "Mixed Platform" in the correct way.

So, the question is why OpenSolutionAsync() cannot do the same thing as default ```msbuild Solution.sln```?

**Comment by Pilchie** [comment] 2016-07-27 16:53
This is a dupe of https://github.com/dotnet/roslyn/issues/5389 I believe.

**Closed by Pilchie** 2016-07-27 16:53 UTC
Labels: Area-IDE, Question
