### ISSUE TITLE
[Feature Request] Quick Fix gets confused by property setting  {} blocks.

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#30520] opened 2018-10-15 12:56 UTC
(From VSTS  705108)

Steps to reproduce:

1. New Xamarin.iOS Project
2. Open ViewController.cs
3. Paste these lines after base.ViewDidLoad 

            UIButton button = new UIButton (new CoreGraphics.CGRect (0, 0, 0, 0))
            {
                Frame = new CoreGraphics.CGRect (1, 1, 1, 1)
            }
            View.AddSubview (button);

4. Note the missing ; after the property setting block.
5. Right click the red error on the last } and note both quick fixes are assuming {} are a block and not property setting (iterate using foreach or put inside using.

In this case, and in this case:

            button.Frame = new CoreGraphics.CGRect ()

We should offer "insert ;" option.

---- the user requests an insert ; code fix provider.

**Comment by Therzok** [comment] 2018-10-15 13:34
Possible dupe of https://github.com/dotnet/roslyn/issues/30238 ?

**Comment by sharwell** [comment] 2018-10-26 18:16
Duplicate of #30238

**Closed by sharwell** 2018-10-26 18:16 UTC
Labels: Area-IDE, Feature Request
