### ISSUE TITLE
Inserting a TAB after parenthesis completion moves the caret to outside of the parenthesis

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19975] opened 2017-06-02 03:07 UTC
This one is a little hard to explain, but any TAB after the editor has completed my parenthesis results in the caret being moved to outside of the parenthesis instead of inserting a TAB.

This looks caused by the automatic parenthesis completion, because if I repro this where VS doesn't complete my parenthesis then it doesn't occur

Here's a video:

![tab](https://cloud.githubusercontent.com/assets/1103906/26709100/80bc51e4-4793-11e7-8bff-0b1ac12815c3.gif)

1. Type: `[InlineData(1, `
2. Press `TAB`

**Expected:** Tab to be inserted
**Actual:** Caret moves beyond the the closed parenthesis

**Comment by davkean** [comment] 2017-06-02 03:11
This behavior seems very deliberate, so it might have been designed like this, what I don't like about it:

- It interrupts me entering that that exact construct above, I'm trying to make a table
- It's unobvious that I'm in a "special" mode. In other special modes, such as entering snippets, it's obvious that TAB does something special and I need to "escape" out of it.

**Comment by Pilchie** [comment] 2017-06-02 17:24
This is automatic brace completion, and I thought there was supposed to be a visual treatment that it is part of the session.  @olegtk Do you know if there is a UI treatment?

**Comment by olegtk** [comment] 2017-06-02 19:14
That seems to be by design, tab is by default moves caret out of brace completion session, past the closing brace. Roslyn is [doing the same for C#](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/EditorFeatures/Core/Implementation/AutomaticCompletion/BraceCompletionSessionProvider.BraceCompletionSession.cs#L255).

**Closed** 2018-03-07 20:14 UTC
Labels: Area-External, Resolution-By Design

**Comment by davkean** [comment] 2018-03-07 21:03
How do I disable this? In the above example, I'm writing a table and it's annoying that TAB is not inserting a TAB - especially given there is zero indication that TAB does not mean TAB.
