### ISSUE TITLE
C# Edit: u -> ushort but using

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51487] opened 2021-02-25 17:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Edit:-u---ushort-but-using/1341040)._

---
When you type a character "u" or "us" out of any namespace and under other "using XXX" of all, you must want to type "using" but "ushort", but when you first type it in a page it will automatic choose "ushort" but "using".
Although, this is a tiny problem of reduce efficiency, I hope it can be fix.
Thanks!

---
#### Feedback Bot on 2/17/2021, 11:22 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by Youssef1313** [comment] 2021-02-25 18:09
Should the order be swapped somehow, or shouldn't ushort and friends be recommended in this context in the first place?

**Comment by Youssef1313** [comment] 2021-02-25 19:51
This was already fixed in https://github.com/dotnet/roslyn/pull/51137

**Comment by Orange23333** [comment] 2021-02-27 06:27
Thanks!

**Comment by jinujoseph** [comment] 2021-03-02 20:26
Duplicate of #44459

**Closed by jinujoseph** 2021-03-02 20:26 UTC
Labels: Area-IDE
