### ISSUE TITLE
Help ! ,InvalidProgramException when running in x64

### ISSUE THREAD

**Issue by taotao2014** [dotnet/roslyn#2851] opened 2015-05-18 11:37 UTC
The following program will throw an AggregateException containing an InvalidProgramException when run in x64. When running the program as x86, everything is fine.

Here is a link to a project demonstrating the error; https://dl.dropboxusercontent.com/u/34113139/InvalidProgramException.zip. Run the x86 configuration and it works, switch to x64 and the error appears.

``` csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;


Program :
namespace RoslynTest {
    class Program {
        static void Main(string[] args) {
            var syntaxTree = CSharpSyntaxTree.ParseText(@"class C { static int x = 0; }");

            var compilation = CSharpCompilation.Create("Test", new[] { syntaxTree }, new[] { MetadataReference.CreateFromAssembly(typeof(object).Assembly) }, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
            foreach (var d in compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error)) {
            }

            Console.WriteLine("Done");
        }
    }
}
```

**Comment by VSadov** [comment] 2015-05-18 20:09
I have tried the repro sample with latest preview version of Microsoft.CodeAnalysis (which is 1.0.0-rc2), and both 32bit and 64bit configurations ran with not problems. In either Debug or Release.
It is possible that the issue was caused by some bug that has been fixed.

**Comment by taotao2014** [comment] 2015-05-19 00:39
hello VSadov,Do not use vs tool to run, run the exe file bin directory。

**Comment by taotao2014** [comment] 2015-05-19 10:26
VSadov，resolved, thank you 。

**Comment by VSadov** [comment] 2015-05-19 15:35
@taotao2014 - if you think the bug is fixed, could you close the issue? Thanks!

**Closed** 2015-05-19 23:21 UTC
Labels: Area-Compilers, Bug, Language-C#, Resolution-Not Reproducible
