### ISSUE TITLE
[release/7.0] Unhandled exception. System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn#63940] opened 2022-09-12 07:46 UTC
### Description

The automatic dependency flow for the release/7.0 branch - https://github.com/dotnet/winforms/pull/7753 - is [failing to build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=11613&view=logs&j=71ffe38c-ed83-5650-b269-3e2a870c2d94&t=fad00996-4079-5863-c72b-581eb696fd7e&l=126) with the latest build introduced in https://github.com/dotnet/winforms/commit/bf78399105aa9d058399f0a047e09fb5d4d2d032.
There are multiple errors of the same kind:
```
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error : Unhandled exception. System.NotImplementedException: The method or operation is not implemented. [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.LoggingMetadataFileReferenceResolver.GetHashCode() [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.ExistingReferencesResolver.GetHashCode() [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Roslyn.Utilities.Hash.Combine[T](T newKeyPart, Int32 currentKey) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CompilationOptions.GetHashCodeHelper() [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions.ComputeHashCode() [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CompilationOptions.GetHashCode() [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at System.Collections.Generic.HashSet`1.Add(T item) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.InputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.SourceOutputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsAndUpdateCompilation(Compilation compilation, Compilation& outputCompilation, ImmutableArray`1& diagnostics, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunGenerators(Compilation input, ParseOptions parseOptions, ImmutableArray`1 generators, AnalyzerConfigOptionsProvider analyzerConfigOptionsProvider, ImmutableArray`1 additionalTexts, DiagnosticBag generatorDiagnostics) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Boolean utf8Output, TextWriter textWriter, Func`2 func) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-1.22358.14\tasks\net6.0\Microsoft.CSharp.Core.targets(75,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) [D:\Development\dotnet-winforms\src\Accessibility\ver\Accessibility-version.csproj]
```

### Reproduction Steps

To repro the failure:
```
git clone https://github.com/dotnet/winforms.git
git checkout bf78399105aa9d058399f0a047e09fb5d4d2d032
.\build.cmd -c Release
```
The previous commit builds successfully:
```
git clone https://github.com/dotnet/winforms.git
git checkout 78debe60f5ad62d2036b77a432f11d718e636cff
.\build.cmd -c Release
```

### Expected behavior

Build succeeds :)

### Actual behavior

Build fails.

### Regression?

Yes

### Other information

Raising it here since a) there's nothing obvious in the call stack pointing to Windows Forms codebase, and b) to possibly gain a greater attention.

**Comment by jaredpar** [comment] 2022-09-12 18:58
This is the PR that fixes that crash

https://github.com/dotnet/roslyn/pull/63347

That was checked in some time ago though. I'm surprised you are still hitting it. It should not be present in the latest SDKs

@chsienki, @RikkiGibson

**Comment by jaredpar** [comment] 2022-09-14 23:51
Closing as a dupe of #63318. It looks like that fix didn't make it to that version of the SDK. It is checked in though and will flow to the next preview.

**Closed by jaredpar** 2022-09-14 23:51 UTC
Labels: Area-Compilers, untriaged
