### ISSUE TITLE
Bug with command line args on Windows+Mono

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/roslyn#11316] opened 2016-05-15 12:25 UTC
**Versions Used**: 
* Microsoft.Net.Compilers 1.2.1 (Visual C# Compiler version 1.2.0.60325)
* Microsoft.Net.Compilers 2.0.0-beta1 (Visual C# Compiler version 2.0.0.60317)
* Mono JIT compiler version 4.2.3 (Visual Studio built mono)

**Steps to Reproduce**:

Create a simple `Program.cs` file with a valid content. E.g:

```cs
public class Program
{
   public static void Main()
   {
      System.Console.WriteLine("Hello, World!");
   }
}
```

Try to compile it with Roslyn+Mono:

```
mono csc.exe Program.cs
```

**Expected Behavior**:

Successful compilation.

**Actual Behavior**:
```
> mono csc.exe Program.cs
Microsoft (R) Visual C# Compiler version 1.2.0.60325
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2015: 'D:\Microsoft.Net.Compilers.1.2.1\tools\csc.exe' is a binary file instead of a text file
```
```
> mono csc.exe Program.cs
Microsoft (R) Visual C# Compiler version 2.0.0.60317
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2015: 'D:\Microsoft.Net.Compilers.2.0.0-beta1\tools\csc.exe' is a binary file instead of a text file
```

**Comment by 0xd4d** [comment] 2016-05-15 13:35
Perhaps related to #6677

**Comment by jaredpar** [comment] 2016-07-19 04:41
Thanks for taking the time to report this.  @0xd4d is correct that this is a dupe of #6677.

**Closed by jaredpar** 2016-07-19 04:41 UTC
Labels: Area-Compilers, Bug, Community
