### ISSUE TITLE
CodeClass.AddFunction returning a strange object

### ISSUE THREAD

**Issue by moxley71** [dotnet/roslyn#6619] opened 2015-11-06 11:25 UTC
I am developing a plugin that converts project types.

At one point in the plug in, I need to copy the methods from one class to another:

```C#
// Assuming element is passed to the method as CodeFunction                         
CodeFunction func = (CodeFunction)element; 
fullName = func.FullName;
name = fullName.Split('.').Last();
fullType = func.Type.AsString;
CodeFunction functionVar = newCode.AddFunction(name, func.FunctionKind, func.Type, -1, func.Access);
```
However, whenever I try to access any of the methods or properties of functionVar, I get the following error:
```
An unhandled exception of type 'System.ArgumentException' occurred in WF2UPA.dll
Additional information: Value does not fall within the expected range.
```
I am trying to do this in Visual Studio Enterprise 2015 on Windows 10, however, if I run the same code in Visual Studio Premium 2013 on Windows 7, everything works.

**Comment by DustinCampbell** [comment] 2015-12-08 22:45
I took a look at this and was unable to reproduce the problem. I tried creating a VS extension with similar code to what you listed above and it worked as expected. FWIW, if the code above didn't work, several VS features would stop working properly, including the WinForms Designer. Would you be able to provide a more substantial code example of how your extension is using Code Model? Additionally, I searched the internet for "WF2UPA.dll" but the only references to that DLL are from this very bug report. Very strange!

**Comment by moxley71** [comment] 2015-12-10 16:22
Dustin,

Sorry, I should have been a little clearer. WF2UPA.dll is the plug in I am creating.
The plugin takes an existing project created as a WinForms project and then converts it to either a WPF or Universal Windows application. The problem occurs when the plugin attempts to recreate a function from the old project into the new.
As I said, under VS 2013, this works perfectly, but the error occurs when I try to create and run the .plugin under VS 2015.

**Comment by DustinCampbell** [comment] 2015-12-10 21:01
I'd be awesome if you could provide a bit more code. Maybe a small sample package that demonstrates the problem?

**Comment by DustinCampbell** [comment] 2016-04-19 22:51
Without no way to repro, I'm going to close this issue. I hope you were able to work around the problem in your code.

**Closed by DustinCampbell** 2016-04-19 22:51 UTC
Labels: Area-IDE, Bug, Resolution-Not Reproducible
