### ISSUE TITLE
Custom Attributes, allowing non-constant constructor parameters and generics

### ISSUE THREAD

**Issue by pmunin** [dotnet/roslyn#12377] opened 2016-07-07 16:29 UTC
It would be really nice to be able to do this in .NET:

```
[DefaultValue(new DateTime(2015,1,1))]
[Validate(dt=> dt>DateTime.Parse("2010/7/1") && dt<DateTime.Parse("2016/7/1"))]
public DateTime MyDateTime{get;set;}

```

It could also help a lot in unit tests, when you need to declare InlineDataAttribute (XUnit) for Theory unit test. You could create mock instances right in parameters of InlineDataAttribute.

Currently attributes only allow primitive types (DateTime, Decimal, lot of other types are not allowed). Trick with validation has to be workarounded via passing "validation method name" as a string constant, which is ugly, hard to refactor.

With current framework and C# version
[Validate(dt=> dt>DateTime.Parse("2010/7/1") && dt<DateTime.Parse("2016/7/1"))] will have to be [Validate(typeof(AttrConstructorParameters1))] with AttrConstructorParameters1 class implemented separately for each attribute declaration.

C# compiler could help generating that class (AttrConstructorParameters) dynamically transparently for developer, so he does not have to produce tons of typical hardly readable code.

So invisibly for developer eventually [Validate(v=> ...)] could be converted behind the scene to something like this:

```
[Validate(typeof(<AttrConstructParameters1>))] 
...//attribute target declaration

....

class AttrConstructorParameters1 //invisible (nested?) class created for each attribute declaration
{
    public Func<object, bool> Parameter1 = new Func<object,bool>( v=> ... );
}

```

There are bunch of invisible class generation happens for anonymous delegates, yield return, await,... Cannot it be used here similar way?

**Comment by Unknown6656** [comment] 2016-07-07 17:08
This proposal has mentioned in the following issues:
#953 
#2466
and partly menitoned in #11475 and in the comment sections of many other issues.

As far as I know, it's overall state could be marked as [`1 - Planning`](https://github.com/dotnet/roslyn/labels/1%20-%20Planning) or [`0 - Backlog`](https://github.com/dotnet/roslyn/labels/0%20-%20Backlog), meaning that it could be made possible either in the upcomming or next C# version (v7 or v8).

**Comment by pmunin** [comment] 2016-07-07 17:46
@Unknown6656 thanks for links. I'll still keep this issue here, because I'm providing simple way to achieve it with Roslyn

**Comment by dsaf** [comment] 2016-07-08 08:32
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/2401.

**Comment by gafter** [comment] 2017-03-24 23:50
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

This may be close enough to https://github.com/dotnet/csharplang/issues/343 that discussion can continue there.

**Closed by gafter** 2017-03-24 23:50 UTC
Labels: Area-Language Design, Discussion
