### ISSUE TITLE
Mac builds sporadically time out 

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#7987] opened 2016-01-15 18:47 UTC

**Comment by TyOverby** [comment] 2016-01-15 18:47
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2718/

**Comment by TyOverby** [comment] 2016-01-15 18:49
cc @davkean

**Comment by TyOverby** [comment] 2016-01-15 19:05
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2712/

**Comment by TyOverby** [comment] 2016-01-15 19:08
By looking at http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/buildTimeTrend, we can see that quite a few of the builds are timing out.

Out of 400 builds (since Dec 29), 30 of them time out.

**Comment by jaredpar** [comment] 2016-01-18 18:11
Duplicate of #6407.  It's the general Mono is timing out problem.

**Closed by jaredpar** 2016-01-18 18:11 UTC
Labels: Area-Compilers
