### ISSUE TITLE
AnalyzerEngine reporting OperationCanceledExceptions.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#30459] opened 2018-10-11 18:01 UTC
Not sure if this has already been reported/fixed.  But i'm getting these all over the place:

```
Severity	Code	Description	Project	File
Error	AD0001	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD001UseSwitchToMainThreadAsyncAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at C:\GitHub\roslyn\src\EditorFeatures\CSharp\Wrapping\CSharpParameterWrappingCodeRefactoringProvider.cs(55,31): System.OperationCanceledException The operation was canceled.. Syntax: token.Parent.GetAncestors()
                                          .FirstOrDefault(n => generator.GetParameterListNode(n) != null)'.	Microsoft.CodeAnalysis.CSharp.EditorFeatures	
```

Are we just catching all exeptions, and not ignoring System.OperationCanceledException?

**Comment by CyrusNajmabadi** [comment] 2018-10-11 18:01
Tagging @mavasani @heejaechang Thanks!

**Comment by mavasani** [comment] 2018-10-11 18:06
Dupe of https://github.com/dotnet/roslyn/issues/30264

**Closed by mavasani** 2018-10-11 18:06 UTC

**Comment by CyrusNajmabadi** [comment] 2018-10-11 18:09
Can you reopen @mavasani .  The duped bug was closed no-repro.  But this is obviously repro'ing for me :)

**Comment by mavasani** [comment] 2018-10-11 19:02
@CyrusNajmabadi Which branch? I believe @sharwell knows the branch where we moved to the correct VS Threading analyzers package.
