### ISSUE TITLE
Unable to open/restore New EditorConfig UI Editor after setting Source Code (Text) Editor as default editor

### ISSUE THREAD

**Issue by wilhelmmedetz** [dotnet/roslyn#55177] opened 2021-07-28 07:46 UTC
I accidentally set  "Source Code (Text) Editor" as the default editor for .editorconfig files in Visual Studio. After this I have found no possibility to open .editorconfig files with the new editorconfig UI editor in Visual Studio.

Is there any way to delete the default editor selection? I tried deleting it from the CurrentSettings.vssettings file - but this was ignored.

**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Version 16.10.4

**Steps to Reproduce**:

1. Select .editorconfig file in "Solution Explorer"
2. Open "Edit With" dialog, select "Source Code (Text) Editor"
3. Press "Set as Default" and "OK"

**Expected Behavior**:

There should be an entry for the "New EditorConfig UI Editor" in the "Open With" dialog box

**Actual Behavior**:

I can open .editorconfig files only in text editors. The New EditorConfig UI Editor is no available.

**Comment by alexanderjung-sdxag** [comment] 2022-02-17 12:49
Same here with VS 2022 Version 17.1.0.

**Comment by jmarolf** [comment] 2022-03-18 21:30
duplicate of https://github.com/dotnet/roslyn/issues/53120

**Closed by jmarolf** 2022-03-18 21:30 UTC
Labels: Bug, Area-IDE, Feature - Editor Config UI
