### ISSUE TITLE
[Test Failure] Test Failures (+1 more) in prtest/win/dbg/unit32 on PR #9667

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#9669] opened 2016-03-10 21:41 UTC
PR: [#9667](https://github.com/dotnet/roslyn/pull/9667) *Fix crash in Inline Rename (future-stabilization)* by @DustinCampbell
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5090/

Note: I'm putting this under Infrastructure but I'm not sure.

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Issue 2: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Comment by davkean** [comment] 2016-03-11 07:00
Dupe of https://github.com/dotnet/roslyn/issues/9490

**Closed by davkean** 2016-03-11 07:00 UTC
Labels: Area-Infrastructure, Bug, Test
