### ISSUE TITLE
Escape quotes when pasting into verbatim string C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41013] opened 2020-01-16 19:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/883317/escape-quotes-when-pasting-into-verbatim-string-c.html)._

---
When pasting into a verbatim string (@""), if the pasted contents contain quotes (such as in a JSON or XML snippet), it would be really nice to automatically escape that content.  For example:

string sample = @"";
<paste text:> { "foo": "bar" }

**Desired:**
string sample = @"{ ""foo"": ""bar"" }";

**Currently:**
string sample = @"{ "foo": "bar" }"; // and a slew of syntax errors to fix up...

---
#### Visual Studio Feedback System on 1/14/2020, 00:24 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-01-16 23:06
Duplicate of #31869

**Closed by sharwell** 2020-01-16 23:06 UTC
Labels: Developer Community
