### ISSUE TITLE
Suggestion: Warn that Delegate is not being invoked.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#31961] opened 2018-12-20 15:45 UTC
For example, in the following code.
```c#
public class Program
{
  public static void Main()
  {
    Act();
    Console.WriteLine("Hello World");
  }

  static Action Act()
  {
    return () => Console.Write("Act");
  }
}
```
Is should output
```
Act
Hello World
```
but is not because the action that is return by `Act` is never invoked.

We should have diagnostic that reports that the delegate is not being called. 
```csharp
public class Program
{
  public static void Main()
  {
    Act(); // ~~Act()~~ (Delegate not invoked).
    Console.WriteLine("Hello World");
  }

  static Action Act()
  {
    return () => Console.Write("Act");
  }
}
```

**Comment by CyrusNajmabadi** [comment] 2018-12-20 16:18
This feature already exists:

![image](https://user-images.githubusercontent.com/4564579/50296561-9ae23200-042f-11e9-848c-b28ea06ceaac.png)

![image](https://user-images.githubusercontent.com/4564579/50296570-a0d81300-042f-11e9-81ce-4b91d781a033.png)

You need to turn it on here: 

![image](https://user-images.githubusercontent.com/4564579/50296596-afbec580-042f-11e9-8e77-f1b211c8fcbd.png)

This is in `Text Editor | C# | Code Style | General | Expression Preferences`

**Comment by sharwell** [comment] 2018-12-20 18:11
Duplicate of #30777

**Closed by sharwell** 2018-12-20 18:11 UTC
Labels: Area-IDE, Feature Request
