### ISSUE TITLE
This error need to be correct or improved in a better way ?

### ISSUE THREAD

**Issue by anirudhagupta** [dotnet/roslyn#31437] opened 2018-11-29 12:03 UTC
I have a codebase in which parent class contain a method called Print()

` public override void Print(object sender, PrintPageEventArgs e)
        {
        }`

Now if I don't have a PrintPageEventArgs's namespace referenced in my .cs file it says "No suitable method found to override". This trick my mind to think that the print method doesn't exist in the base class (It might derived from the class which don't have Print() method to override) or  I am doing something wrong. When I add the namespace the problem get fixed.

what I am proposing here is simply giving an error for "please fix the namespace for this "PrintPageEventArgs". The current error "nothing to override" make confusion. I think I derived it from a class which doesn't have a print method to override.

I might be wrong here, My belief is showing the error to fix namespace instead of saying "Nothing to override".

**Comment by YairHalberstadt** [comment] 2018-12-16 20:57
I'm happy to give this a go. I presume that the solution would be:

If a valid override can be found by using a fully qualified name for the type of a parameter, suggest that you may have meant to use that type.

**Comment by svick** [comment] 2018-12-16 21:06
When I try to do this, [I get two errors](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4DsCGBbCBnADmgYwgAIA5AWACgBvK4+4gAQCZiAFWFYNtAcwgCikLgEEovbMWoBfOgzn0WxAEIKpagJCMAzMTAwowAK5oANkwAs7TsAAUAewBGAKwgFgxbBBQATaABprGC4efiFvYDEJYggASilZSgZiRMSqJQARYhAyADpVGjUdYntIKFg/SyCuBxc3Dy9fAOruPkFhSPFJOLVaJIZUoA=):

>    error CS0246: The type or namespace name 'PrintPageEventArgs' could not be found (are you missing a using directive or an assembly reference?)
>   error CS0115: 'D.Print(object, PrintPageEventArgs)': no suitable method found to override

The second one is the one you mentioned, but the first one says that you're missing a `using`, which is what you want. Is that not what you see?

**Comment by YairHalberstadt** [comment] 2018-12-16 21:11
I do as well.

Does Roslyn have a way of optionally suggesting a fix in an error based on  knowledge, and if so, would that be desirable here?

**Comment by gafter** [comment] 2018-12-16 23:53
> I'm happy to give this a go. I presume that the solution would be:

I think the solution would be to suppress the second diagnostic when we had an error binding the parameter types.

**Comment by YairHalberstadt** [comment] 2018-12-18 08:32
@gafter 

I have a pr containing a fix for this at https://github.com/dotnet/roslyn/pull/31895

I have tested this, but have not written any unit-tests, as I was unsure where they should go.

This is my first time contributing to Roslyn, so if there's anything I missed out, or got wrong, please let me know.

Thanks.

**Comment by YairHalberstadt** [comment] 2018-12-18 09:19
I haven't dealt with generic types properly, so closing the pull request for now

**Comment by YairHalberstadt** [comment] 2018-12-18 11:21
I have dealt with cases where the type could not be found, and I have dealt with arrays, where the element type of the array could not be found. 

However I have not dealt with cases where a generic type is a parameter and the generic type has a type argument which could not be found. I have found no way to detect if the type argument is an ErrorType in SourceMemberContainerTypeSymbol.CheckOverrideMember

**Comment by YairHalberstadt** [comment] 2018-12-18 11:39
I'm trying to do this:

```csharp
                        bool IsOrContainsErrorType(TypeSymbol symbol)
                        {
                            if (symbol.Kind == SymbolKind.ErrorType)
                                return true;

                            if (symbol.Kind == SymbolKind.ArrayType)
                                return IsOrContainsErrorType(((ArrayTypeSymbol)symbol).ElementType.TypeSymbol);

                            if(symbol.Kind == SymbolKind.NamedType)
                            {
                                var namedSymbol = (NamedTypeSymbol)symbol;
                                var typeArguments = namedSymbol.TypeArgumentsNoUseSiteDiagnostics;
                                foreach(var typeArgument in typeArguments)
                                {
                                    if (IsOrContainsErrorType(typeArgument.TypeSymbol))
                                        return true;
                                }
                            }

                            return false;
                        }
```

The issue is the typeArgument will have a kind of NamedType, even if it is in fact an ErrorType

**Comment by YairHalberstadt** [comment] 2018-12-19 09:22
Scrap that, it was an issue with the test method I was using.

**Closed** 2018-12-26 19:08 UTC
Labels: 4 - In Review, Area-Compilers, Concept-Diagnostic Clarity
