### ISSUE TITLE
Dynamic order of context menu's causes loss of producitivy

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48386] opened 2020-10-07 01:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1209037/dynamic-order-of-context-menus-causes-loss-of-prod.html)._

---
[severity:It's more difficult to complete my work]
I find I am struggling with the dynamic reordering of context menu items in the C# text editor.  The problem is that it forces me to have to read the context menu every time it opens instead of relying on muscle memory to quickly pick the action I want to perform. 

A workflow that I commonly use is to right click and add a field member to a class I am creating, however the "Create and Assign field '...'" jumps around, sometimes it is first, sometimes it is second, and sometimes its buried in a sub menu.  There seems to be no discernable pattern, it just appears "somewhere" unexpectedly almost every time. 

What often happens is that I add a property member by accident because I pick the option I think should be add a field to the class, which causes me to undo or fix, this wastes my time.   The next time I add a field I quickly click the first or second item (wherever it appeared the first time) and its now in a different order, or even in a sub-menu.  Also sometimes the option to add readonly field or property doesn't appear and it will marked it as readonly automatically when I don't actually want it to be readonly.

I have 20+ years of coding experience and use muscle memory a lot and having a context menu change nearly every time I open it is frustrating.  Taking time to have to reread the context menu is making the feature less appealing and I am often hand-coding instead of using IDE features because it is fatiguing to have to constantly "FIX" the IDE adding or changing code or changing the UI presentation all the time and causing you to pick the wrong feature out of habit.

I would like the context menu items to be fixed in place.  Content that doesn't belong in the current context can be removed, but the order of items in the list should be in the same order always.

---
#### Feedback Bot on 10/5/2020, 11:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/6/2020, 01:57 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-10-07 15:01
Duplicate of #48385

**Closed by sharwell** 2020-10-07 15:01 UTC
