### ISSUE TITLE
C# code crashes C# syntax highlighting and causes editor to act erratically.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61348] opened 2022-05-16 19:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-code-crashes-C-syntax-highlighting-a/10026543)._

---
[severity:It's more difficult to complete my work]
Create new C# project

add the code inside a function
>Assert.AreEqual(expectedArgNames.OrderBy(string=>s., ctx.ArgumentNames.Length);

It seems to crash the syntax highlighter and makes it imposible to move the caret in the effected area in order to fix it

---
#### Feedback Bot on 4/28/2022, 06:43 PM: 

(private comment, text removed)
#### Andrew Hall 🤘 [MSFT] on 5/2/2022, 11:57 AM: 

(private comment, text removed)
#### Simon Sprott on 5/11/2022, 02:49 AM: 

(private comment, text removed)
#### Feedback Bot on 5/10/2022, 10:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2022-05-16 19:42
Confirmed repro: 

![image](https://user-images.githubusercontent.com/475144/168669772-4eb5f963-61c3-48fc-94b5-257618848794.png)

**Comment by ryzngard** [comment] 2022-05-16 19:43
Min repro only requires the text `(string=>)` anything typed after doesn't seem to fix the syntax highlighting.

**Comment by Youssef1313** [comment] 2022-05-16 19:55
There was a recent parsing change around this.

https://github.com/dotnet/roslyn/pull/60825

**Comment by ryzngard** [comment] 2022-05-16 20:04
Closing as dupe of #60661

**Closed by ryzngard** 2022-05-16 20:04 UTC
Labels: Area-IDE, untriaged
