### ISSUE TITLE
Intellisense Drops async Modifier When Adding static Modifier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48880] opened 2020-10-23 16:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-Drops-async-Modifier-When-A/1230495?preview=true)._

---
[severity:It bothers me. A fix would be nice]
Intellisense suggests that I make this method static:

public async Task<IEnumerable<Ticket>> GetAsync()
{
//...
}

After accepting recommended fix:

public static Task<IEnumerable<Ticket>> GetAsync()

It didn't add the static modifier. It replaced the async modifier with the static modifier.

---
#### Feedback Bot on 10/22/2020, 10:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-04-20 12:26
Add static comes from CA1822, and it was fixed in https://github.com/dotnet/roslyn-analyzers/pull/2959.

@mavasani Should this get closed?

**Comment by mavasani** [comment] 2021-04-20 12:31
Thanks @Youssef1313. Duplicate of  https://github.com/dotnet/roslyn-analyzers/issues/2888

**Closed by mavasani** 2021-04-20 12:31 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-CodeStyle
