### ISSUE TITLE
Intermittent hang while running tests

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9838] opened 2016-03-17 16:23 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5274/

Could be Roslyn.Compilers.CSharp.Semantic.UnitTests,Roslyn.Services.Editor.UnitTests,Roslyn.Services.Editor.CSharp.UnitTests.dll or Roslyn.VisualStudio.Services.UnitTests.dll

**Comment by srivatsn** [comment] 2016-03-17 18:10
Likely a dupe of #7825. /cc @lgolding

**Comment by Pilchie** [comment] 2016-03-25 17:06
Moving to Area-Analyzers, since that's where #7825 is.

**Comment by srivatsn** [comment] 2016-04-25 22:00
Closing as dupe of #7825.

**Closed by srivatsn** 2016-04-25 22:00 UTC
Labels: Area-Analyzers, Test, Urgency-Now
