### ISSUE TITLE
Roslyn build issues error about .NET Core 2.0

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#20945] opened 2017-07-18 19:14 UTC
After upgrading to d15rel 26717.1, building Roslyn produces the following error. This is apparently an intentional change in the .NET SDK.

```C#
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET
.TargetFrameworkInference.targets(112,5): error : The current .NET SDK does not support targeting .NET Core 2.0.  Ei
ther target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\roslyn-interna
l\Open\src\Test\DeployCoreClrTestRuntime\DeployCoreClrTestRuntime.csproj]
```

**Comment by jasonmalinowski** [comment] 2017-07-25 17:37
@rchande @jaredpar This was worked around; is the belief at this point this behavior was by design and should be closed?

**Comment by jaredpar** [comment] 2017-07-25 18:31
It's by design but we're still doing the wrong thing. Basically we're relying on un-supported behavior at this point.

I met with SDK yesterday and sketched out what needs to change here. Essentially we need to move to CLI / SDK 2.0 which itself is a non-trivial move (have to depend on 15.3 as well). We shuold use this issue to track that work.

**Comment by jaredpar** [comment] 2017-11-17 17:24
This is fixed now.

**Closed by jaredpar** 2017-11-17 17:24 UTC
Labels: Area-Infrastructure, Bug
