### ISSUE TITLE
Consider reporting an error for 'static' modifier on 'record'

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#46450] opened 2020-07-30 17:19 UTC
Compile:
```C#
static record R;
```
Expected:
```
error CS0106: The modifier 'static' is not valid for this item
```
Actual:
```
(1,15): error CS0708: 'R.EqualityContract': cannot declare instance members in a static class
(1,15): error CS0708: 'GetHashCode': cannot declare instance members in a static class
(1,15): error CS0722: 'R': static types cannot be used as return types
(1,15): error CS0708: 'Equals': cannot declare instance members in a static class
(1,15): error CS1057: 'R.R(R)': static classes cannot contain protected members
(1,15): error CS1057: 'R.EqualityContract': static classes cannot contain protected members
(1,15): error CS1057: 'R.EqualityContract.get': static classes cannot contain protected members
```

**Comment by AlekseyTs** [comment] 2020-07-31 00:12
Dupe of https://github.com/dotnet/roslyn/issues/46348

**Closed by AlekseyTs** 2020-07-31 00:12 UTC
Labels: Area-Compilers, New Language Feature - Records
