### ISSUE TITLE
The Error List shows different results based on whether you've ever opened a source file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15760] opened 2016-12-08 08:58 UTC
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Change your VB code style settings to:
![image](https://cloud.githubusercontent.com/assets/1103906/21003545/17200750-bd80-11e6-9058-5a78ad4bd2bd.png)
6. Make sure Background Analysis is turned on for VB
7. Wait till Error List no longer has "..." after name
-- Error List should look something like --
![image](https://cloud.githubusercontent.com/assets/1103906/21003576/4dff3b6a-bd80-11e6-819f-ea045f4aa7f6.png)

7. Open src\Microsoft.VisualStudio.AppDesigner\ApplicationDesigner\ApplicationDesignerView.vb
8. Close that file

-- Error List should look something like (Notice that there's 22 more messages that have appeared) -- 

![image](https://cloud.githubusercontent.com/assets/1103906/21003625/887fae82-bd80-11e6-8cf9-f8661b17b043.png)

Very confused how or why messages show up the Error List? What exactly do I need to do to show *all* possible messages?

**Comment by davkean** [comment] 2016-12-08 09:03
tag @mavasani @heejaechang

**Comment by heejaechang** [comment] 2016-12-08 09:07
probably dupe of this - https://github.com/dotnet/roslyn/pull/15566

**Comment by davkean** [comment] 2016-12-08 09:09
Why isn't this fix in an RC2 build? It's pretty bad.

**Comment by heejaechang** [comment] 2016-12-08 09:21
hmmm it should be in RC2.

https://github.com/dotnet/roslyn/pull/15597

...

ah by the way, just remembered, simplify type name won't run in closed file unless its severity is warning/error since running those are just too expensive.

**Comment by davkean** [comment] 2016-12-08 09:24
That is *really*, *really* confusing. Why is that the design? My trust in the error list right now is at all time low.

**Comment by davkean** [comment] 2016-12-08 09:28
I employ you to play around with the project system repro - the number of messages in the Error List grows and changes based on the files you open. For example, open a source file, now these show up:

```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _timer	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\FileWatcher.vb	483	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryStrings	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	95	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryImages	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	96	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryIcons	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	97	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryAudio	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	98	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryFiles	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	99	Active
Message	IDE1006	Naming rule violation: These words must begin with upper case characters: _categoryOther	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceEditorView.vb	100	Active

```

**Comment by heejaechang** [comment] 2016-12-08 09:28
running simplify type name for all files on roslyn makes solution analysis time from around 10mins to over 1 hour, approaching 2 hours.

right now, we don't have a way to control each analyzer scope they run. it is either all analyzers run on all files or none of them runs.

so, kind of workaround for now.

...

so I think your confusion comes from simply type name message not being cleared when file is closed?

**Comment by heejaechang** [comment] 2016-12-08 09:32
hmmm.. I will take a look. but some questions.

1. did you close and re-open vs once you changed option (severity) ? 
2. does your rc2 drop have the fix? (you can confirm that by doing simply repo in console app - change option like you did above, and see whether that error shows in closed files)

**Comment by davkean** [comment] 2016-12-08 09:36
No my confusion is that I have no idea how or when messages appear in the Error List.

I just did a test:

1. Opened projectsystem.sln
--Notice there's 101 messages, 0 warnings, 0 errors
2. I opened a single source file, opened Find, entered "Namespace M", and then held down F3 for 5 minutes to open lots of files
3. Then File - Close All Documents
-- Notice there's 5449 messages --

You're suggesting that this is by design?

**Comment by heejaechang** [comment] 2016-12-08 09:40
depends. is message from simply type name? or from other analyzers as well? are those message also reported by FSA or not.

...

design should be message you get from opened files should be got from closed file as well if FSA is on. open file only message should go way when a file is closed.

**Comment by davkean** [comment] 2016-12-08 09:41
Simplify type name is one, but there's also naming violations.

As called out in the repo steps, background analysis is turn on.

**Comment by heejaechang** [comment] 2016-12-08 09:42
so, does your drop has the fix or not? it seems weird if your drop has the fix, those errors (except simplify type name) not reported by FSA.

**Comment by davkean** [comment] 2016-12-08 09:46
I have no idea if my build has the fix, this is a build from a couple of days ago.

**Comment by heejaechang** [comment] 2016-12-08 09:50
you can confirm whether your drop has the fix or not by doing simply repo in console app - change option like you did above, and see whether that error shows in closed files.

1. set option like above
2. create console app
3. add name style violation like above.
4. close the file
5. close the console app.
6. re-open the console app.
7. wait ... from error list to go away
8. check whether error shows up in error list.

if it does, then you have fix, otherwise, you don't.

...

my checked in to our rc2 branch. not sure whether it RIed and whether it went to ml branch or prerel branch.

**Comment by davkean** [comment] 2016-12-08 09:56
I can't get the async naming violation to even fire at all:

```
using System.Threading.Tasks;

public class Program
{
    static void Main(string[] args)
    {
    }

    public Task Foo()
    {
        return null;
    }
}


```

**Comment by heejaechang** [comment] 2016-12-08 10:00
that probably is question to ide team. @dotnet/roslyn-ide I believe they do some hackery to make IDE analyzer to show up in a project that doesn't support IOperation feature.

**Comment by heejaechang** [comment] 2016-12-08 10:13
sorry asking you to do bunch and me not doing. I was working on something. anyway, done with it start to play with project system code.

looks like the IDE1006 is also open file only - http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/Analyzers/NamingStyles/NamingStyleDiagnosticAnalyzerBase.cs,36

**Comment by heejaechang** [comment] 2016-12-08 10:15
and those diagnostics open file only analyzers reported are not cleared when file is closed. that looks like a bug.

**Comment by heejaechang** [comment] 2016-12-08 10:19
https://github.com/dotnet/roslyn/issues/15763

**Comment by davkean** [comment] 2016-12-08 10:23
Is this related: https://github.com/dotnet/roslyn/issues/15764

**Comment by heejaechang** [comment] 2016-12-08 10:29
could be. I probably look into these issue once I am done with primary workspace work I am doing.

**Comment by heejaechang** [comment] 2016-12-08 13:28
@davkean I made some fix to make sure open file only diagnostics to be removed when the file is closed.

https://github.com/heejaechang/roslyn/tree/openfileOnly

can you sync the change and see whether this reduces some confusion?

**Comment by Pilchie** [comment] 2016-12-12 21:53
See also https://github.com/dotnet/roslyn/issues/9712.

Tagging @CyrusNajmabadi and @kuhlenh and @dpoeschl.  We need to close on what our RTM story is going to be here ASAP.

**Comment by heejaechang** [comment] 2016-12-12 21:56
currently there are 2 open file only analyzers.

1. simplify type name analyzer (require perf to be better to run on all files)
2. naming style analyzers (options? not 100% sure why it is open file only)

only IDE analyzer can be open file only, so those 2 are only ones.

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/IBuiltInAnalyzer.cs,97a2fc692b31f993,references

**Comment by Pilchie** [comment] 2016-12-12 22:14
I suspect that the naming style analyzer would also have a significant performance impact in its current form.

**Comment by Pilchie** [comment] 2017-01-12 00:12
@CyrusNajmabadi Can you look at this in the context of the other `IBuilltinAnalyzer` thread?

**Comment by heejaechang** [comment] 2017-01-12 00:22
ya, this repro with IBuiltInAnalyzer not marked for IDE analyzer

**Comment by Pilchie** [comment] 2017-01-12 17:38
Moving to RTW, since the fix went there.  @CyrusNajmabadi @davkean can you confirm that the experience is better with the fix to the IBuildInAnalyzer issue?

**Comment by CyrusNajmabadi** [comment] 2017-01-12 17:42
Well.. it's certainly better in that it's no longer "broken".  I woudl say that we really should address the delays in the current experience though.  A 5 second delay makes it really feel like something is wrong.  I don't really see why we need to wait that long, and i think 2 seconds (or less) would be fine.  After all, all that's happening is a file is being closed.  We should be able to clear out the diagnostics from it extremely trivially when that happens.

@heejaechang What do you think?

**Comment by heejaechang** [comment] 2017-01-12 19:04
some error can't be cleared until full compilation is re-analyzed. so we can make some diagnostics can go away faster but not all.

currently, it is made to all go away same time.

**Comment by CyrusNajmabadi** [comment] 2017-01-12 19:05
Oh?  So it might even take more than 5 seconds if you have a larger project?  That seems like it will still be a pretty bad experience then.

**Comment by heejaechang** [comment] 2017-01-12 19:29
it has been like that for a while so. and we always said error list is not in stable state until "..." goes away.

...

this particular bug is regression from previous drop caused by us introducing IBuiltInAnalyzer.OpenFileOnly.  we had this behavior since dev14 with 5 seconds delay with "..." and didn't had feedback from users until diagnostic actually never go away.

**Comment by Pilchie** [comment] 2017-01-19 22:21
@CyrusNajmabadi Is this fixed by the `IBuiltInAnalyzer` PR?  Should this just be close?

**Comment by CyrusNajmabadi** [comment] 2017-05-16 01:46
Assigning to heejae.  I don't think there's anything actionable i can do here.

**Comment by CyrusNajmabadi** [comment] 2017-05-16 01:46
Any perf delays would need to be fixed in teh analyzer engine.

**Closed** 2020-02-04 01:56 UTC
Labels: 4 - In Review, Area-Analyzers, Bug
