### ISSUE TITLE
Code tooltip may need to show the attributes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55092] opened 2021-07-23 22:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-tooltip-may-need-to-show-the-attrib/1485059)._

---
I often use `[NotNullWhen(returnValue: true)]` onto a parameter, e.g.

```csharp
public static bool TryParse(string? str, [NotNullWhen(true)] out MyClass? result)
{
    // The implementation logic...
}
```

The tooltip may display the method like:

![B614499a6a89a4b0b960df6809c1489eb637626139661855745_QQ截图20210723131158](https://user-images.githubusercontent.com/46729679/126848050-95013f91-4b29-4585-b7b3-a9b659df504c.png)

```
Tooltip shows:
static bool TryParse(string? str, out MyClass? result)
```

I suggest that the code tooltip should also display the attribute usages onto the parameter in order that we can learn about the nullability better than the case without the attribute displaying.

```
Tooltip now shows:
static bool TryParse(string? str, [NotNullWhen(true)] out MyClass? result)
```

Thanks.

---
#### Feedback Bot on 7/22/2021, 10:51 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2021-07-28 18:54
Duplicate of #38358

**Closed by jinujoseph** 2021-07-28 18:54 UTC
Labels: Area-IDE, IDE-IntelliSense
