### ISSUE TITLE
SyntaxGenerator can't generate expression-bodied members

### ISSUE THREAD

**Issue by ali-hk** [dotnet/roslyn#16953] opened 2017-02-04 22:17 UTC
There's currently no supported mechanism for generating an expression-bodied member using SyntaxGenerator.

Ex.
public SomeType SomeProperty => _someValue;

**Comment by CyrusNajmabadi** [comment] 2017-02-04 22:21
Note: this is somewhat by design.  VB doesn't support expression-bodied members.  So it's not clear how this would work for them.  Is there a reason you can't just manually create the C# syntax?

**Comment by alrz** [comment] 2017-02-05 05:45
I suppose we can also accept expressions for C# and turn it to an expression-bodied member.

**Comment by ali-hk** [comment] 2017-02-05 19:09
It's possible to generate it manually, but since I'm writing a language-agnostic code refactoring and SyntaxGenerator is intended for just that purpose, it seems like it should be a supported scenario.

It seems to me that for VB it should simply generate a normal read-only property, which is essentially equivalent.

**Comment by CyrusNajmabadi** [comment] 2017-02-05 22:01
PRs welcome.

**Comment by CyrusNajmabadi** [comment] 2017-02-05 22:02
I can see allowing for an expression-body parameter as well.  For C# it would make a => property.  For VB, it will depend on if you're making a sub or func.  If it's a sub, it should just become an expression statement.  If it's a func, it should become a return statement.

**Comment by CyrusNajmabadi** [comment] 2022-02-04 19:28
API proposals need to go through our documented process for changes.  Having gotten no traction on this so far, i"m going to close this out.

**Closed by CyrusNajmabadi** 2022-02-04 19:28 UTC
Labels: Bug, help wanted, Area-IDE
