### ISSUE TITLE
CS9210 regression in .NET 8.0.200 SDK

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/roslyn#72170] opened 2024-02-19 17:35 UTC
**Version Used**: .NET 8.0.200

**Steps to Reproduce**:

1. Create a .NET 6.0 or .NET 7.0 project.
2. Define a local `ImmutableCollectionsMarshal.AsImmutableArray()` polyfill.
3. Build.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
```

```csharp
using System.Collections.Immutable;
using System.Runtime.CompilerServices;

namespace System.Runtime.InteropServices;

internal static class ImmutableCollectionsMarshal
{
    public static ImmutableArray<T> AsImmutableArray<T>(T[] array) => Unsafe.As<T[], ImmutableArray<T>>(ref array);
}
```

```csharp
using System.Collections.Immutable;

ImmutableArray<string> array = ["abc"];
```

**Diagnostic Id**: CS9210

**Expected Behavior**: builds successfully.

**Actual Behavior**:

```
Error CS9210 This version of 'ImmutableArray' cannot be used with collection expressions.
```

**This is a serious regression: this worked fine on .NET 8.0.101/8.0.102 but is now broken.**

This regression breaks OpenIddict (that uses an `ImmutableCollectionsMarshal` polyfil to use the collection expressions syntax with `ImmutableArray<T>` on older TFMs) very badly: https://github.com/openiddict/openiddict-core/actions/runs/7963331151/job/21738679005?pr=1988

**Comment by CyrusNajmabadi** [comment] 2024-02-19 17:58
1. @cston @RikkiGibson any idea what would have happened here?
2. I would nto have expected this to *ever* work fwiw.  `ImmutableArray<T>` on that tfm lacks the `[CollectionBuilder]` attribute that even indicates how it can be built.  So even if it compiled, it should have ended up with non-functioning code (as it should have just been calling `new ImmutableArray<T>()` to instantiate the array.

If this ever worked, it likely was a very unintentional set of circumstances that went against the lang spec.

**Comment by kevinchalet** [comment] 2024-02-19 18:07
> So even if it compiled, it should have ended up with non-functioning code (as it should have just been calling `new ImmutableArray<T>()` to instantiate the array.

Haha, I can guarantee you it was working fine (i.e not just compiling, but working fine at runtime).
OpenIddict uses the collection expressions syntax with `ImmutableArray<T>` everywhere and it's running flawlessly (on both .NET Framework and .NET 6.0/7.0) 🤣 

> If this ever worked, it likely was a very unintentional set of circumstances that went against the lang spec.

Hum, nope? See this test: https://github.com/dotnet/roslyn/pull/70411/files#diff-14905addfa8e2fa8f60fa6512958f1dcef5b5e9a201dc345fb77ed5bf289fa50R21769.

**Comment by CyrusNajmabadi** [comment] 2024-02-19 18:09
> Haha, I can guarantee you it was working fine

**Comment by kevinchalet** [comment] 2024-02-19 18:16
> What version of System.Collections.Immutable are you using?

On .NET Framework and .NET Standard, the `1.7.1` package: https://github.com/openiddict/openiddict-core/blob/e17e4ee9b2846f166d3049bc52079604c0cde94d/Directory.Packages.props#L48
On .NET, the inbox version (so `6.0.0` on .NET 6.0, `7.0.0` on .NET 7.0).

In all cases, none of these versions include a `[CollectionBuilder]`. Yet, it was working just fine with the previous SDK version 😃

**Comment by CyrusNajmabadi** [comment] 2024-02-19 18:24
> In all cases, none of these versions include a [CollectionBuilder]

> Haha, I can guarantee you it was working fine (i.e not just compiling, but working fine at runtime).

So, my comments above are approaching this from the perspective of the language design.  From the language design this would not have been expected to work at all.  Specifically, at the feature level, for `ImmutableArray<T> `to support collection expressions it has to either:

1. Have the `[CollectionBuilder(...)]` attribute on it.  This attribute indicates that the type can be instantiated with a contiguous block of memory.  This case does not apply here because, as you said, you do not have the `CollectionBuilder` attribute on the type.
2. Have the `collection initializer` shape.  Specifically, it has be constructible, and it must implement `IEnumerable<T>` and it must have some applicable `Add(T)` method.   This case *does* apply (unfortunately) to `ImmutableArray<T>`.  I say 'unfortunately' because going down this path ends up generating code like `new ImmutableArray<T>(); ... .Add(x); .Add(y);`, which totally blows up at runtime.

So, from the *language's* perspective, this was never expected to work.

--

Now, if you do have a `System.Collections.Immutable` with the `CollectionBuilder` attribute on it, then it *should* work.  And the compiler should also optimize this by going directively to `ImmutableCollectionsMarshal.AsImmutableArray` if it can find it.  But, again, this should only apply *if* the type is properly constructible. 

Note: it sounds like the compiler was very out of spec with the language.  I'm guessing a bug fix probably went in to bring things in line and it broke this unsupported behavior.

**Comment by kevinchalet** [comment] 2024-02-19 18:42
> So, from the _language's_ perspective, this was never expected to work.

Correct me if I'm wrong, but good old arrays don't have the special attribute on them, right? AFAIK, they also don't have the collection initializer shape and yet, things work just fine even on older TFMs. I guess arrays are special cased? If so, why wouldn't `ImmutableArray<T>` work the same way?

> Now, if you do have a System.Collections.Immutable with the CollectionBuilder attribute on it, then it should work. And the compiler should also optimize this by going directively to ImmutableCollectionsMarshal.AsImmutableArray if it can find it. But, again, this should only apply if the type is properly constructible.

Sure, it works fine when referencing a version that includes the special builder attribute (e.g on .NET 8.0), but this thread is only about versions that don't 😄 

> Note: it sounds like the compiler was very out of spec with the language. I'm guessing a bug fix probably went in to bring things in line and it broke this unsupported behavior.

Well, the test I linked earlier clearly mentioned that this scenario was possible by adding a local `ImmutableCollectionsMarshal.AsImmutableArray()` method. I wouldn't have adopted this syntax everywhere if it wasn't "officially" supported: 😭 

```
Can work around this error in downlevel scenarios by defining ImmutableCollectionsMarshal.AsImmutableArray
```

**Comment by CyrusNajmabadi** [comment] 2024-02-19 18:47
> Correct me if I'm wrong, but good old arrays don't have the special attribute on them, right? AFAIK, they also don't have the collection initializer shape and yet, things work just fine even on older TFMs. I guess arrays are special cased? 

Correct.  The entire list of supported types are:

1. Arrays.
2. Spans.
3. Collection initalizer types (types you'd previous do `new X { A, B, C }` with.
4. CollectionBuilder types.  
5. A core set of well known interface-types (those implemented by arrays).

That's it.

1. If so, why wouldn't `ImmutableArray<T>` work the same way?

Because it's not a special type to the language in any way *whatsoever*.  The lang has no concept it exists, or particularly cares about it.  Contrast that with the lang knowing deeply about arrays, to the point that it has dedicated syntax for it.  Or that the lang has deep understanding of Span types, including creating them with things like `stackalloc`, etc.

`ImmutableArray<T>` is just not special to us.  And we designed a way to make it work just fine, the `CollectionBuilder` attribute.  We also allowed the compiler to optimize how it emits things if it wants.  So if the compiler can see that `ImmutableArray<T>` has the `COllectionBuilder` attribute (and thus can be made from a contiguous sequence of elements), and it also sees this helper marshal'ing class, it is free to use that.  But that's a compiler decision, independent of whether or not the lang thinks this should be legal or not.

**Comment by kevinchalet** [comment] 2024-02-19 19:02
> Because it's not a special type to the language in any way whatsoever. The lang has no concept it exists, or particularly cares about it.

But nothing prevents changing that to treat `ImmutableArray<T>` like `IReadOnlyList<T>` or any of the similar types, right? It used to work, so there's no reason I couldn't be updated to work again?

I get that `ImmutableArray<T>` support might not be have been intended from a language perspective, but it's a scenario that used to work just fine and that was explicitly covered by two tests:
  - One test that asserted that the collection expressions syntax couldn't be used with a non-decorated `ImmutableArray<T>` if `ImmutableCollectionsMarshal.AsImmutableArray` wasn't polyfill-ed:

```csharp
[Fact]
public void ImmutableArray_06()
{
    string sourceA = """
        using System.Collections.Immutable;

        class Program
        {
            static void Main()
            {
                ImmutableArray<int> arr = [1, 2, 3];
                arr.Report();
            }
        }
        """;

    var comp = CreateCompilation(new[] { sourceA, s_collectionExtensions }, targetFramework: TargetFramework.Net60);
    comp.VerifyEmitDiagnostics(
        // 0.cs(7,35): error CS9210: This version of 'ImmutableArray<T>' cannot be used with collection expressions.
        //         ImmutableArray<int> arr = [1, 2, 3];
        Diagnostic(ErrorCode.ERR_CollectionExpressionImmutableArray, "[1, 2, 3]").WithArguments("System.Collections.Immutable.ImmutableArray<T>").WithLocation(7, 35));

    // Can work around this error in downlevel scenarios by defining ImmutableCollectionsMarshal.AsImmutableArray
    string sourceB = """
        using System.Collections.Immutable;

        namespace System.Runtime.InteropServices
        {
            public static class ImmutableCollectionsMarshal
            {
                // nb: the real implementation of this would use an unsafe cast
                public static ImmutableArray<T> AsImmutableArray<T>(T[] array) => ImmutableArray.Create(array);
            }
        }
        """;

    var verifier = CompileAndVerify(new[] { sourceA, sourceB, s_collectionExtensions }, targetFramework: TargetFramework.Net60, verify: Verification.Skipped, expectedOutput: IncludeExpectedOutput("[1, 2, 3],"));
    verifier.VerifyDiagnostics();
    verifier.VerifyIL("Program.Main", """
        {
            // Code size       34 (0x22)
            .maxstack  3
            IL_0000:  ldc.i4.3
            IL_0001:  newarr     "int"
            IL_0006:  dup
            IL_0007:  ldtoken    "<PrivateImplementationDetails>.__StaticArrayInitTypeSize=12 <PrivateImplementationDetails>.4636993D3E1DA4E9D6B8F87B79E8F7C6D018580D52661950EABC3845C5897A4D"
            IL_000c:  call       "void System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(System.Array, System.RuntimeFieldHandle)"
            IL_0011:  call       "System.Collections.Immutable.ImmutableArray<int> System.Runtime.InteropServices.ImmutableCollectionsMarshal.AsImmutableArray<int>(int[])"
            IL_0016:  box        "System.Collections.Immutable.ImmutableArray<int>"
            IL_001b:  ldc.i4.0
            IL_001c:  call       "void CollectionExtensions.Report(object, bool)"
            IL_0021:  ret
        }
        """);
}
```

  - One test that asserted that the collection expressions syntax could be used with a non-decorated `ImmutableArray<T>` if `ImmutableCollectionsMarshal.AsImmutableArray` was polyfill-ed:

```csharp
[Fact]
public void ImmutableArray_07()
{
    // Test an ImmutableArray<T> which implements only non-generic IEnumerable.
    string sourceA = """
        using System.Collections.Immutable;

        class Program
        {
            static void Main()
            {
                ImmutableArray<int> arr = [1, 2, 3];
            }
        }

        namespace System.Collections.Immutable
        {
            struct ImmutableArray<T> : IEnumerable
            {
                public void Add(T t) { }
                IEnumerator IEnumerable.GetEnumerator() => null;
            }
        }
        """;

    var comp = CreateCompilation(sourceA, targetFramework: TargetFramework.Mscorlib40);
    comp.VerifyEmitDiagnostics(
        // 0.cs(7,35): error CS9210: This version of 'ImmutableArray<T>' cannot be used with collection expressions.
        //         ImmutableArray<int> arr = [1, 2, 3];
        Diagnostic(ErrorCode.ERR_CollectionExpressionImmutableArray, "[1, 2, 3]").WithArguments("System.Collections.Immutable.ImmutableArray<T>").WithLocation(7, 35));
}
```

It seems very wrong to me to change the rules of the game without even mentioning it anywhere... specially in a .NET SDK patch version 😨 

Users - like me - have adopted this syntax and are now broken. It's far from being an ideal situation (to say the least), I hope you agree with that 😄

**Comment by CyrusNajmabadi** [comment] 2024-02-19 19:11
> But nothing prevents changing that to treat `ImmutableArray<T>` like `IReadOnlyList<T>` or any of the similar types, right? 

Sure.  But we'd need a very compelling argument to be made, *especially* as tehre is a surefire way to make it work: use the updated version of System.Collections.Immutable.

> It used to work

Sure.  But we fix bugs when we encounter them.  And we very much do this in a short period of time surrounding an initial release.

> so there's no reason I couldn't be updated to work again?

Correct.  It could be updated to work.  I'm just explaining that from a language perspective, it is appropriate that this not work today.

**Comment by CyrusNajmabadi** [comment] 2024-02-19 19:12
> So, to me, it was definitely supported by the compiler. It seems very wrong to change the rules of the game without even mentioning it anywhere... specially in a .NET SDK patch version 😨

> Users - like me - have adopted this syntax and are now broken. It's far from being an ideal situation (to say the least), I hope you agree with that 😄

I agree on both counts.  I have pulled in Chuck and Rikki to help here.

**Comment by kevinchalet** [comment] 2024-02-19 19:27
> Sure. But we'd need a very compelling argument to be made, _especially_ as tehre is a surefire way to make it work: use the updated version of System.Collections.Immutable.

Well, it definitely works but it's not really a perfect solution:
  - This requires mixing TFMs/package versions (e.g .NET 6.0 TFM + .NET 8.0 NuGet package), which isn't ideal (e.g it has implications regarding support policies).
  - Only `System.Collections.Immutable` 8.0.0 (and higher) offers `[CollectionBuilder]`. Yet, support for lots of older TFMs was dropped in `System.Collections.Immutable` 6.0.0, meaning you can't use the collection expressions syntax on old TFMs... a limitation that didn't exist in .NET 8.0.102 when referencing `System.Collections.Immutable` 1.7.1 (which is still fully supported).

> I agree on both counts. I have pulled in Chuck and Rikki to help here.

Thanks, much appreciated!

**Comment by CyrusNajmabadi** [comment] 2024-02-19 19:36
Just talked with Chuck.  We def think of this as a bug fix that brought the compiler more in line with the lang spec as intended.  Note: the use of S.C.I 8.0.0 seems totally reasonable to me.  Indeed, that's what we as roslyn do ourselves (And we target netstandard2.0).  

>  meaning you can't use the collection expressions syntax on old TFMs... 

This is a non-goal for the language.  People are welcome to try.  But these are all unsupported scenarios. 

> (e.g it has implications regarding support policies).

I believe that's also true using the latest language versions on prior tfms.  This is something i do not believe is supported as well.  

--

Tagging @jcouv @jaredpar for visibility.  Chuck and i plan to bring this to LDM next monday to discuss the situation.  From our perspective, this is working as intended.  However, it does manifest in a visible change in behavior for customers who were taking this approach in this narrow time window.  Will be bringing to discuss and determine if we want to keep things as is, or make any changes here.

Note: as per teh discussion above, an available workaround is simply for a user to reference the current S.C.I package.  If they do this, they'll be able to use collection exprs with immutablearrays.

**Comment by kevinchalet** [comment] 2024-02-19 19:47
> I believe that's also true using the latest language versions on prior tfms. This is something i do not believe is supported as well.

Well, I get it's not "officially" supported, but most language improvements are perfectly usable on older TFMs. Otherwise, projects like https://github.com/Sergio0694/PolySharp wouldn't exist 🤣 

> However, it does manifest in a visible change in behavior for customers who were taking this approach in this narrow time window. Will be bringing to discuss and determine if we want to keep things as is, or make any changes here.

Thanks. I'll wait for the final decision then 😄

**Comment by CyrusNajmabadi** [comment] 2024-02-19 19:49
> Well, I get it's not "officially" supported, but most language improvements are perfectly usable on older TFMs.

Right.  But our real position is: That's entirely unsupported.  If it works, great.  If not, tough.  And working/not-working might change at any moment for any reason.

> Otherwise, projects like [Sergio0694/PolySharp](https://github.com/Sergio0694/PolySharp) wouldn't exist 🤣

Sure.  But that's explicitly *not* supported.  It's a project that is welcome to exist and attempt to accomplish these tasks.  But we don't go out of our way to make it work, or prevent things like bug fixes from breaking it.

:)

**Comment by kevinchalet** [comment] 2024-02-19 19:58
>  But we don't go out of our way to make it work, or prevent things like bug fixes from breaking it.

As long as you're not actively trying to break such initiatives for no reason, I guess it's fine. It's great to be able to use recent language constructions even if you're not in a position to target the latest TFM (personally, I'd really love to see a super-LTS .NET "Core" version with more than just 3 years of support, but it's a completely another story 😄)

**Comment by KennethHoff** [comment] 2024-02-19 20:36
> Personally, I'd really love to see a super-LTS .NET "Core" version with more than just 3 years of support, but it's a completely different story 😄

I've always thought that 3 year LTS might as well be no LTS. They should do 1 LTS every 5 versions (v10, v15, and so on..) and have those be like 10 years instead. ( Granted, I always jump to the newest version as soon as possible, but if I weren't able to then 3 years isn't very long)... But ye, nothing to do with this issue.

**Comment by CyrusNajmabadi** [comment] 2024-02-19 20:42
> As long as you're not actively trying to break such initiatives for no reason,

We don't go out of our way just to break. However, if the compiler is out of spec with the language, we very much do break in a short interim period right after shipping as we discover bugs.

**Comment by jaredpar** [comment] 2024-02-21 15:40
> We don't go out of our way just to break. However, if the compiler is out of spec with the language, we very much do break in a short interim period right after shipping as we discover bugs.

Indeed that is the case. The year after we ship a feature we're free to _break_ new features in order to fix bugs, get in compliance with the intended behavior or correct design issues that customers find when using the feature in the wild. We very much try to avoid breaks whenever possible but they do happen from time to time and are often an unavoidable consequence. 

That first year also exists on a sliding scale: 

- Months 0-3: we have no qualms changing behavior. Feature is brand new, there will be bugs and we have to address them.
- Months 3-6: similar to Months 0-3 but we usually push back harder on taking the change because we realize there will be greater customer adoption hence greater impact. At the same time though, if it's a meaningful bug we'll generally push forward with a fix.
- Months 6-9: we will still break behavior but there needs to be a compelling reason to do so. The bug needs to be significant. The more core the scenario the more significant the bug needs to be. 
- Months 9-12: it needs to be a _very compelling_ bug for us to break scenarios at this point because adoption is likely quite significant. Taking breaks at this window in a core scenario is exceedingly rare.

This is the policy we've operated on since the start of C#. Even then these breaks tend to impact a small number of customers because we go to great lengths to ensure breaks are targeted and minimal.

> This requires mixing TFMs/package versions (e.g .NET 6.0 TFM + .NET 8.0 NuGet package), which isn't ideal (e.g it has implications regarding support policies).

Using collection expressions on `net6.0` is already in _not officially supported_ territory. If it works that's great but if it doesn't we're not going out of our way to fix it because it's unsupported. I understand a number of customers get frustrated with this policy but it is the policy that we operate on.

For this case in particular `ImmutableArray<T>` is not a type recognized by the compiler. It's no different than any other 3rd party collection type. The versions prior to 8.0 don't fully meet the requirements necessary for use in collection expressions hence there will be friction. The advice to customers, for `ImmutableArray<T>` and any other collection type, is that if you want to have versions that work well with collection expressions then you'll need to update to versions of the libraries that fully support the necessary patterns. 

Closing this as "By Design". The compiler is in compliance with the spec here and there aren't plans at the moment to change the spec to loosen these requirements.

**Closed by jaredpar** 2024-02-21 15:40 UTC
Labels: Area-Compilers, Resolution-By Design, untriaged

**Comment by kevinchalet** [comment] 2024-02-22 09:14
Not the outcome I wanted to hear, but at least it's crystal clear 😃 

> Months 0-3: we have no qualms changing behavior. Feature is brand new, there will be bugs and we have to address them.

Once bitten, twice shy. I'll certainly be way more careful (reluctant?) before adopting a new Roslyn feature in the future 👍🏻

**Comment by juharris** [comment] 2024-08-23 03:40
FWIW it worked in dotnetfiddle.net with .NET 8.0.0
![image](https://github.com/user-attachments/assets/91a4a0df-407b-4e19-96e7-e65070e1a3e1)

https://dotnetfiddle.net/LNW7iC

**Comment by kevinchalet** [comment] 2024-08-23 06:34
@juharris .NET 8.0's `ImmutableArray` version is decorated with `[CollectionBuilder]` so it indeed works... but this thread was about using that syntax with older versions, that are not decorated with `[CollectionBuilder]`.
