### ISSUE TITLE
"Introduce using statement" refactoring doesn't show up in the middle of a variable

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38540] opened 2019-09-06 01:35 UTC
**Version Used**: 

**Steps to Reproduce**:

This occurs for both C# and VB.

1.  CTRL+. at $

``` C#
using System;
using System.IO;

class Class1
{
    public static void Main()
    {
        Stream stream = G$etStream();

        Console.WriteLine(stream);
    }

    private static Stream GetStream()
    {
        return null;
    }
}

```

Expected: 
![image](https://user-images.githubusercontent.com/1103906/64394534-fe81bd80-d099-11e9-95f6-bc57634d5b52.png)

Actual:
Nothing, the refactoring isn't available

This is particularly odd when the CA00067 complains about the type not being disposed and covers the entire span of the variable, so you can suppress the warning but not introduce the fix.

**Comment by CyrusNajmabadi** [comment] 2019-09-06 22:54
tagging @petrroll .  This may be fixed by moving to his work.

tagging @jnm2 

The general thinking here is that 'initializers' are effectively unboundedly large expressions. And we very much (in the past at least) didn't want to to offer these sorts of options while you might be arbitrarily deep within some expression.  

That said, @petrroll's work has been around rethinking the logic here and at least making the features available, albeit potentially at lower and lower priorities in the fix-list depending on how far away you are from things.

**Comment by mavasani** [comment] 2019-10-22 18:45
Verified this still repros on latest 16.4 bits.

**Comment by mavasani** [comment] 2020-01-11 00:07
There is a unit test that validates the current behavior ensuring `Introduce using statement` is not offered in the middle of RHS of the declaration, but everywhere else on the declaration statement: https://github.com/dotnet/roslyn/blob/f5938f2c3595118ec0dc27a714a696c6b62a6897/src/EditorFeatures/CSharpTest/IntroduceUsingStatement/IntroduceUsingStatementTests.cs#L171-L185

IMO that seems like reasonable behavior, so this feels by design to me. Marking it for design review.

**Comment by CyrusNajmabadi** [comment] 2022-11-08 17:33
@mavasani you marked this as by-design?  can we close this out then?

**Comment by CyrusNajmabadi** [comment] 2023-02-14 01:49
Closing out as this is by design.  The objective is to not supply things in arbitrary expression portions that can become untenably large.  The original feature explicitly carved this out as intentional and i think it's valid to keep it this way.

**Closed by CyrusNajmabadi** 2023-02-14 01:49 UTC
Labels: Bug, help wanted, Area-IDE, Resolution-By Design, Need Design Review

**Comment by davkean** [comment] 2023-02-14 02:34
@CyrusNajmabadi @mavasani I find the resolution odd; you have a code fix that complains about the whole declaration and the thing that fixes it only shows up on part of it.

**Comment by CyrusNajmabadi** [comment] 2023-02-14 04:14
This is very standard for us. It's based heavily in the reverse feedback we got where we would show these things on the full span, and people were annoyed by the amount of items that were showing up everywhere.
