### ISSUE TITLE
Visual Studio reports incorrect type for nullable reference type when using `var`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35296] opened 2019-04-26 20:10 UTC
VSF_TYPE_MARKDOWNVisual Studio 2019 Preview, C# 8.0 beta, .NET Core 3.0 preview of some kind. Nullable reference types enabled through `&lt;NullableContextOptions&gt;enable&lt;/NullableContextOptions&gt;` in the `.csproj`.

For this code snippet:

```
string? meh = null;
var t = meh?.GetType(); // VS thinks t is Type
```

Visual Studio, on mouse hover over `t`, reports the type of `t` as `Type` and not `Type?`.

As far as I can tell, this is incorrect. `t` is of type `Type?` and behaves as expected. For example, an attempt to then assign it to a variable of `Type` will fail:

```
Type t2 = t; // warning, as expected
Type? t3 = t; // no warning, as expected
```

Here's my `.csproj`:

```
&lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;

  &lt;PropertyGroup&gt;
    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
    &lt;LangVersion&gt;8.0&lt;/LangVersion&gt;
    &lt;NullableContextOptions&gt;enable&lt;/NullableContextOptions&gt;
  &lt;/PropertyGroup&gt;

  &lt;PropertyGroup Condition=&quot;'$(Configuration)|$(Platform)'=='Debug|AnyCPU'&quot;&gt;
    &lt;WarningsAsErrors&gt;NU1605;CS8600;CS8602&lt;/WarningsAsErrors&gt;
  &lt;/PropertyGroup&gt;

&lt;/Project&gt;
```

Thanks!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/476671/visual-studio-reports-incorrect-type-for-nullable.html
VSTS ticketId: 807802_
_These are the original issue comments:_

Visual Studio Feedback System on 3/4/2019, 06:32 PM (52 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by 333fred** [comment] 2019-04-30 18:17
Dupe of https://github.com/dotnet/roslyn/issues/35296.

**Closed** 2019-04-30 18:29 UTC
Labels: Area-Compilers, New Language Feature - Nullable Semantic Model, Resolution-Duplicate
