### ISSUE TITLE
Roslyn NormalizeWhitespace messing with InterpolatedStringExpressionSyntax statements

### ISSUE THREAD

**Issue by sk78v** [dotnet/roslyn#39803] opened 2019-11-13 19:40 UTC
**Version Used**: Please see the packages.config. Microsoft.CodeAnalysis packages 2.6.0

**Steps to Reproduce**:

```
static void Main(string[] args)
        {
            var workspace = new Microsoft.CodeAnalysis.AdhocWorkspace();
            var projectId = Microsoft.CodeAnalysis.ProjectId.CreateNewId();
            var versionStamp = Microsoft.CodeAnalysis.VersionStamp.Create();
            var projectInfo = ProjectInfo.Create(projectId, versionStamp, "NewProject", "projName", Microsoft.CodeAnalysis.LanguageNames.CSharp);
            var newProject = workspace.AddProject(projectInfo);

            Console.WriteLine("i");
          
            var sourceText = SourceText.From(
              @"
                  using System;
                  using System.IO;
                  using System.Linq;
                  using System.Text;

                  namespace HelloWorld
                  {
                      class Program
                      {
                          static void Main(string[] args)
                          {
                              int i = 0;                           
                                
                              /**
                               Roslyn normalize whitespace issue
                              **/
                           var a = "1234";
                           var empSsn = $"{int.Parse(a):000000000}";
                          }

                      }
                  }");

            var document = workspace.AddDocument(newProject.Id, "NewFile.cs", sourceText);
            var syntaxRoot = document.GetSyntaxRootAsync().Result;

            var changedSyntaxRoot = syntaxRoot.NormalizeWhitespace();
            

            Console.Read();
        }
```

**Expected Behavior**:

```
 var empSsn = $"{int.Parse(a):000000000}";
```
**Actual Behavior**:

```
 var empSsn = $"{int.Parse(a): 000000000}";
```

Adds space after **Colon ":"**

**Comment by RikkiGibson** [comment] 2019-11-13 23:03
Does this repro in Microsoft.CodeAnalysis 3.3.1?

**Comment by sharwell** [comment] 2019-11-13 23:27
Duplicate of #24454

**Closed by sharwell** 2019-11-13 23:27 UTC
