### ISSUE TITLE
guard VSWorkspace from being disposed by third party plug in

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#11338] opened 2016-05-16 19:26 UTC
our VSWorkspace can be imported by any third party plug in VS and they can call VSWorkspace.Dispose.

once it is called, our VSWorksapce will be disposed even if VS is still alive and causes random crash after that.

I saw several watsons due to it (primaryWorkspace == null), and actually debugged through one of those issues with one of third party plug in provider (Alive - https://comealive.io/)

since it is publicly accessible object, I think we should guard Dispose of the workspace and make sure we are the only one who can call it.

**Comment by jasonmalinowski** [comment] 2016-05-27 23:54
Duplicate of #8232.

**Closed by jasonmalinowski** 2016-05-27 23:54 UTC
Labels: Area-IDE, Bug
