### ISSUE TITLE
C# Tuple is zeroed when accessed via collection

### ISSUE THREAD

**Issue by matthid** [dotnet/roslyn#37451] opened 2019-07-24 13:35 UTC
**Version Used**: Visual Studio 15.9.04012.0. File -> New -> Project -> Console (DotNet Core)

**Steps to Reproduce**:

1. Paste the following code:
    ```csharp
   using System;
   using System.Collections.Generic;
   
   namespace CompilerBugZero
   {
       class Program
       {
           static void Main(string[] args)
           {
               var hdl = FindHandle();
               if (IntPtr.Zero == hdl)
               {
                   throw new InvalidOperationException();
               }
           }
   
           static IntPtr FindHandle()
           {
               var candidates = new List<(IntPtr hwnd, string title, string className)>();
               candidates.Add((new IntPtr(123), "title", "className"));
   
               if (candidates.Count == 1)
               {
                   // Breakpoint here
                   return candidates[0].hwnd;
               }
   
               throw new InvalidOperationException();
           }
       }
   }

   ```

2. Set a breakpoint the line below `// Breakpoint here`
3. See how everything is Zero when it shouldn't: 
![image](https://user-images.githubusercontent.com/1866463/61797637-14a82700-ae28-11e9-9b1d-a764993d13f1.png)

   Note how the list still has the correct value but accessing `[0]` returns a zeroed tuple apparently.

**Expected Behavior**:
Debugger shows the correct values. Code works at runtime.

**Actual Behavior**:
Debugger doesn't show correct value. In fact in our real application I feel like we had the wrong behavior (ie `IntPtr.Zero`) at runtime. In the real application this happened in a PInvoke scenario. However, I couldn't reproduce this here. This might be a wrong positive, but worth considering when investigating this.

**Workaround**:

Change the code to

```diff
            if (candidates.Count == 1)
            {
                // Breakpoint here
-               return candidates[0].hwnd;
+               var t = candidates[0];
+               return t.hwnd;
            }
```

**Comment by tmat** [comment] 2019-07-24 15:58
I confirm this reproduces and it's likely bug in the EE. Very odd.

**Comment by 0xd4d** [comment] 2019-07-24 18:50
Looks like:

https://github.com/dotnet/roslyn/issues/29951
https://github.com/dotnet/roslyn/issues/34155

It eventually ended up here:

https://github.com/dotnet/coreclr/issues/25519

**Comment by tmat** [comment] 2019-07-24 19:18
@0xd4d Thanks for tracking it down. Closing as a dup of dotnet/coreclr#25519.

**Closed by tmat** 2019-07-24 19:18 UTC
Labels: Area-IDE, Interactive-Debugging
