### ISSUE TITLE
Convert to interpolated string escapes {} or is disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62988] opened 2022-07-27 19:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Convert-to-interpolated-string-escapes-/10102506)._

---
Create a string like `Console.WriteLine("Hello {name}")`. It is quite common to forget adding the $ in the beginning of the string. So now you hit Ctrl-. and run "Convert to interpolated string" instead of navigating to the beginning of the string to add $. But then all {} blocks are escaped like {{name}}, which is obviously wrong. If you instead have just a normal string, like `"Hello "` and want to convert to interpolated string before writing the {name} part, then the refactoring is not available. So I guess there are two "bugs" here:
1) Valid {} blocks are escaped when converted to Interpolated strings (I can't think of a case where I want that)
2) Convert to interpolated string is not possible for a "normal" string

---
#### Feedback Bot on 7/24/2022, 06:46 PM: 

(private comment, text removed)
#### Feedback Bot on 7/27/2022, 00:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2022-07-28 06:36
This was approved as a CAxxxx rule. See https://github.com/dotnet/roslyn-analyzers/issues/2767.

**Comment by vatsalyaagrawal** [comment] 2022-07-28 19:14
Duplicate of #2767

**Closed by vatsalyaagrawal** 2022-07-28 19:14 UTC
Labels: Area-IDE, untriaged
