### ISSUE TITLE
Warning reported returning `null` from async `Task<object?>`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#23702] opened 2017-12-10 22:19 UTC
`return null;` results in `warning: cannot convert null to non-nullable reference`:
```
using System.Threading.Tasks;
class C
{
    static async Task<object?> F()
    {
        return null;
    }
}
```

**Comment by sharwell** [comment] 2017-12-11 13:21
Duplicate of #23275

**Closed by sharwell** 2017-12-11 13:21 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
