### ISSUE TITLE
`Inline temporary variable` fixer on a reference-type `var` regresses nullability

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#69859] opened 2023-09-08 16:22 UTC
### Analyzer

Visual Studio does not expose a fixer's code, so I'm not sure

### Analyzer source

8.0.100-preview.7.23376.3

### Describe the bug

Given code such as 
``` csharp
var headers = FormHeaders();
Consume(headers);

private object FormHeaders() => throw null!;

private static void Consume(object obj) => throw null!;
```
### Expected behavior
Even if `var` is used, if nullability analysis knows the variable is non-null, then it shouldn't cast it to the nullable version
``` csharp
Consume(FormHeaders());

private object FormHeaders() => throw null!;

private static void Consume(object obj) => throw null!;
```

### Actual behavior
``` csharp
Consume((object?)FormHeaders()); // CS8604: Possible null reference argument

private object FormHeaders() => throw null!;

private static void Consume(object obj) => throw null!;
```

**Comment by DoctorKrolic** [comment] 2023-09-09 12:02
Duplicate of https://github.com/dotnet/roslyn/issues/65517

**Comment by jasonmalinowski** [comment] 2023-10-11 21:35
Closing as a duplicate then.

**Closed by jasonmalinowski** 2023-10-11 21:35 UTC
Labels: Resolution-Duplicate, Area-IDE
