### ISSUE TITLE
Feature Request for Intellisense

### ISSUE THREAD

**Issue by xCyborg** [dotnet/roslyn#26478] opened 2018-04-28 17:28 UTC
I hope you consider this very seriously, namely:

1- Deprecated members: strike-through and hide/show.

2- Inherited members: hide/show, hierarchy levels.

3- Local members: hide/show/show first.

4- Ability sort by priority or by type: right now everything is mixed and alphabetically sorted.

There needs to be more sorting options, like pushing deprecated members last or fields and properties first, etc.

5- Activate bold case or highlight option for certain types.

6- Option to show return types inside the list next to members.

7- Show quick info on mouse hover over the list.

This would make code editing and exploring in Visual Studio way more productive, fun and easy.

**Comment by jcouv** [comment] 2018-04-29 15:07
@xCyborg Thanks for the suggestions for improving Visual Studio.
Would it be possible for you to file separate issues for each of those suggestions, so that they can be reviewed and triaged individually, and provide a more detailed description? Thanks

Most of those suggestions were not clear to me. I'm not sure what is the scenario, or current vs. expected behavior. A little code example with comments would be extremely useful to describe each scenario.
Tagging @kuhlenh

**Comment by sharwell** [comment] 2018-04-29 18:10
* Deprecated members: moved to #26488
* Sorting: possible duplicate of #16685, #24226
* Return types: moved to #26489

I wasn't sure what to do with the other items from the information provided so far. Please feel free to open new issues for individual items if you don't see something covered by one of these issues.

**Closed by sharwell** 2018-04-29 18:10 UTC
Labels: Area-IDE, Feature Request
