### ISSUE TITLE
IsImplicit for multiple operation nodes with same syntax

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22069] opened 2017-09-12 15:21 UTC
For example, we need to decide if we should mark all but one node with same syntax as implicit within a translated query expression, see https://github.com/dotnet/roslyn/pull/21356#issuecomment-327916372, https://github.com/dotnet/roslyn/pull/21356#issuecomment-327687398, https://github.com/dotnet/roslyn/pull/21356#issuecomment-327688225, https://github.com/dotnet/roslyn/pull/21356#issuecomment-327688618, https://github.com/dotnet/roslyn/pull/21356#issuecomment-327691690

**Comment by mavasani** [comment] 2017-09-21 23:30
Design Decision: This seems like the correct invariant to maintain. We should bring back more specific cases where it cannot be satisfied or there is no easy decision about which node should be marked Explicit.

**Comment by mavasani** [comment] 2017-09-21 23:31
However, this work is blocked on us ensuring that IsImplicit is shown in test baseline by the dumper. Tag @jinujoseph

**Comment by jinujoseph** [comment] 2017-09-27 23:02
this is dupe of https://github.com/dotnet/roslyn/issues/22229

**Closed by jinujoseph** 2017-09-27 23:02 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
