### ISSUE TITLE
Methods with Optional String Parameters Won't Collapse

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73798] opened 2024-05-31 13:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Methods-with-Optional-String-Parameters-/10671970)._

---
[severity:It's more difficult to complete my work]
When a method specifically has an **Optional string parameter** being passed, the **ability to collapse that method in the IDE goes away**.  Methods with non-optional parameters collapse fine and methods with optional non-string parameters works fine.  Just optional strings break the collapse.  Highly unfortunate since I use Collapse to Definitions religiously and we use optional strings a lot throughout our API.

This started to happen 2 updates ago I believe (on 5/28/2024).

![OptionalStringParmBug](https://github.com/dotnet/roslyn/assets/1408396/ee4097c2-d01e-4233-9363-2c82102c26df)

Visual Studio 2022 x64
v17.10.1

---
#### Feedback Bot on 5/31/2024, 00:02 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2024-06-02 14:11
This is possibly a regression from #71064, specifically, the changes in `AbstractBlockStructureProvider`.

**Comment by genlu** [comment] 2024-06-05 20:17
Possible duplication of https://github.com/dotnet/roslyn/issues/73640

**Comment by ToddZondlo** [comment] 2024-07-01 23:00
Some additional information as this is more than the title suggests.  I see this in VB.Net but not C#.  It appears to be an issue when there is a string literal in the top line of the foldable section of code.

If x = “something” Then --wont fold

If someFunc(“something”) = True Then --won't fold with a string literal in the function call

Dim x as String = “something”
If y = x Then – will fold, as the literal isn’t used

Private Sub test (Optional s As String = “”) – wont fold

Same with:
Select Case “something” --wont fold, but unlikely to do this anyways
Private Sub test(Optional s As Object = “”)  -- won't fold even though it's an Object that has default string literal
Do While s <> “this”  -- won't fold

But this will fold since the literal is at the end of the control structure:
Do
Loop Until (s = “this”)

**Comment by Cosifne** [comment] 2024-07-19 17:45
Verified fixed in https://github.com/dotnet/roslyn/pull/74413
![image](https://github.com/user-attachments/assets/3b212c92-ac91-4d25-9996-62973737731e)

**Closed by Cosifne** 2024-07-19 17:45 UTC
Labels: Bug, help wanted, Area-IDE
