### ISSUE TITLE
Ignore NullableAttribute when implementing abstract class in VB

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48288] opened 2020-10-03 19:08 UTC
## Repro steps:

1. Create a VB class that inherits `SyntaxEditorBasedCodeFixProvider` in Roslyn solution.
2. Apply the codefix to implement the abstract class.

## Expected behavior

No NullableAttributes are added

## Actual behavior

NullableAttributes are added.

```vb
        Public Overrides ReadOnly Property FixableDiagnosticIds As <NullableAttribute({0, 1})> Immutable.ImmutableArray(Of String)
            Get
                Throw New NotImplementedException()
            End Get
        End Property

Protected Overrides Function FixAllAsync(document As Document, <NullableAttribute({0, 1})> diagnostics As Immutable.ImmutableArray(Of Diagnostic), editor As CodeAnalysis.Editing.SyntaxEditor, cancellationToken As Threading.CancellationToken) As Task
            Throw New NotImplementedException()
        End Function
```

**Comment by AnthonyDGreen** [comment] 2020-11-04 03:44
Is the reason for ignoring them because VB doesn't respect them or because they're redundant? If emitting or omitting the attributes would impact C# callers then it should probably be preserved since omitting it would silently change the intent (and binary). At a minimum the codefix should probably spit them out so that the VB implementer is _aware_ of the fact that removing them may impact callers in other languages. Simply dropping them makes this effective change to the method signature completely silent. Then in 6 months someone's reporting a bug about why their VB library that inherits their C# base class isn't showing up right in C#.

Having said that, whatever the behavior that's decided should be made consistent with `<OutAttribute>` _and_ `<DynamicAttribute>` for the same reason.

**Comment by Youssef1313** [comment] 2020-11-04 04:07
@AnthonyDGreen, `NullableAttribute` is not permitted in source and should be used by the compiler only.
See https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/docs/features/nullable-metadata.md

**Comment by sharwell** [comment] 2021-09-15 17:20
Duplicate of #42920

**Closed by sharwell** 2021-09-15 17:20 UTC
Labels: help wanted, Area-IDE, Language-VB, Concept-Continuous Improvement, New Language Feature - Nullable Reference Types
