### ISSUE TITLE
[Proposal] default(T) override

### ISSUE THREAD

**Issue by stefc** [dotnet/roslyn#5627] opened 2015-10-01 21:00 UTC
In generic code I often use default(T) for comparing or initalize a value. But in some code I not want to use the default(T) value as generated by the compiler. For example for default(double) I want to use double.NaN in some cases and not the 0.0. Or if the class have a singleton representation for Empty I want to use that singleton instead of the null Value. 

It would be nice that I can set the default(T) value in the declartion of such generic type 

<code>
class Abc <T> defaults T : double to double.NaN,  default T : Money to Money.Empty 
</code>

**Comment by orthoxerox** [comment] 2015-10-01 21:50
Duplicate of #71, which sadly has a wontfix resolution.

**Comment by HaloFour** [comment] 2015-10-02 00:45
The compiler doesn't generate a specific default value.  It only uses `initobj` which zeroes out whatever the location happens to be, which results in `0` for value types and `null` for reference types.  Without knowing the exact type the compiler wouldn't be able to generate any specific value or method call and in the case of generics the compiler will not know the exact type.  Since the IL for a generic method must be identical regardless of the generic type argument there'd be no way for the C# compiler to emit this conditionally overridden default.

**Comment by paulomorgado** [comment] 2015-10-02 00:47
`default(type)` corresponds to zeroing the entire memory used by the object. Changing that would need CLR changes.

What you seem to be looking for is some constraint on the type or static interfaces.

But you can work around that using a default value provider where you register those. Look at how [TypeDescriptor](http://referencesource.microsoft.com/#System/compmod/system/componentmodel/TypeDescriptor.cs) works.

**Comment by svick** [comment] 2015-10-02 15:40
@HaloFour If you have code like:

```c#
T F<T>()
{
    return default(T);
}
```

the compiler *could* transform it into (hopefully somehow avoiding the boxing):

```c#
T F<T>()
{
    if (typeof(T) == typeof(double))
    {
        return (T)(object)double.NaN;
    }
    else if (typeof(T) == typeof(Money))
    {
        return (T)(object)Money.Empty;
    }
    else
    {
        return default(T);
    }
}
```

I'm not sure doing something like this would be a good idea (actually, it probably wouldn't), but it is possible.

**Comment by HaloFour** [comment] 2015-10-02 15:51
@svick Requiring that the compiler embed effectively a table of all possible types and default combinations directly into the IL of every method that ever attempts to use `default(T)` even if they don't want to waste the cycles spinning over all of the possibilities?  Not to mention, once that's compiled, you can't define a new class with a new default and use it as a generic type argument.

At best you could have a factory function buried in `Microsoft.CSharp` that would be emitted into the IL and that factory would use a registered dictionary of types and their default values/factories which would be managed by static ctors on each type defining its own default value, but again, do you want to incur the cost of a method call and a dictionary lookup for something that should be doing nothing more than zeroing out the address?

**Comment by gafter** [comment] 2015-10-05 16:04
Dup of #71.

**Closed** 2015-10-05 16:03 UTC
Labels: Area-Language Design, Resolution-Duplicate
