### ISSUE TITLE
"Place 'System' directives first when sorting usings" setting does not roam across VS installs

### ISSUE THREAD

**Issue by jekelly** [dotnet/roslyn#18127] opened 2017-03-23 21:49 UTC
**Version Used**: Visual Studio 26228.0 
**Steps to Reproduce**:

1. Install VS
2. Sign in with a user account set for roaming (Environment->Synchronized Settings->Synchronize settings across devices when signed into Visual Studio)
3. Enable "Place 'System' directives first when sorting usings" in Tools->Options->Text Editor->C#->Advanced
4. Close VS
5. Install VS on another machine (or another channel of VS)
6. Log in with the same user account from step 2

**Expected Behavior**:
Place 'System' directives first when sorting usings should be enabled

**Actual Behavior**:
The setting is not enabled.

**Comment by Pilchie** [comment] 2017-03-25 19:09
Dupe of https://github.com/dotnet/roslyn/issues/16247.  @jmarolf what is the ID of the internal bug you filed about this?

**Closed by Pilchie** 2017-03-25 19:09 UTC
Labels: Area-IDE

**Comment by jmarolf** [comment] 2017-03-26 15:20
https://devdiv.visualstudio.com/DevDiv/_workitems?id=371401 Looks like it was closed while I wasn't looking.
