### ISSUE TITLE
Support trim_trailing_whitespace in .editorconfig in Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71343] opened 2023-12-19 15:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Support-trim_trailing_whitespace-in-edi/10482016)._

---
I am in the process of migrating to use .editorconfig with our team using Visual Studio 2022.

I'd like to use `trim_trailing_whitespace = true` but this does not currently seem to be supported by Visual Studio 2022.

I have tested my .editorconfig file is being picked up, which its.  Also when opening the .editorconfig with in Visual Studio and using the GUI interface there does not seem to be an option to set this.

Expected
when my .editorconfig contains `trim_trailing_whitespace = true` for a give file type any trailing white space is stripped on save from the appropriate files.

Actual:
Other .editorconfig options run on save (e.g. append `insert_final_newline`) but trailing whitespace remains.

---
#### Feedback Bot on 10/2/2023, 07:33 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2023-12-19 17:15
Closing out.  This is by design.  trim_trailing_whitespace changes the meaning of source code (since C# is whitespace sensitive).  So we cannot support it.  Our formatter already removes unnecessary whitespace, and can be turned on by setting the appropriate editor config value.

**Closed by CyrusNajmabadi** 2023-12-19 17:15 UTC
Labels: Area-IDE, untriaged

**Comment by grallbring** [comment] 2024-09-21 15:56
@CyrusNajmabadi May I ask why the official documentation at https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022 then states that `trim_trailing_whitespace` is supported?

**Comment by CyrusNajmabadi** [comment] 2024-09-21 19:20
> @CyrusNajmabadi May I ask why the official documentation at https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#supported-settings then states that `trim_trailing_whitespace` is supported?
> The documentation even specifically states:
> ```
> EditorConfig supports all Visual Studio-supported languages except for XML support EditorConfig editor settings.
> EditorConfig supports code style conventions including language, formatting, and naming conventions for C# and Visual Basic.
> ```

The core editor supports it. But it's still up to a particular language to interpret how to do properly. In the case of c#/vb it changes the meaning of our code, so we don't apply it. VS may apply it for many other languages where it is safe though.
