### ISSUE TITLE
Make fields generated in a primary constructor able to be readonly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74081] opened 2024-06-20 18:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Make-fields-generated-in-a-primary-const/10676270)._

---
Currently i we have the following snippet:

```
class Service(ISomeOtherService service) {
}
```

then the field `service` is not readonly, which is expected. However, I would like to mark this service field as `readonly` for example by doing this:

```
class Service(readonly ISomeOtherService service) {
}
```

or maybe, using an attribute:

```
class Service([readonly] ISomeOtherService service) {}
```

---
#### Feedback Bot on 6/5/2024, 02:38 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2024-06-20 20:51
Dupe of existing requests on csharplang.

**Closed** 2024-06-20 20:51 UTC
Labels: Area-IDE, untriaged
