### ISSUE TITLE
Switch expression with 'object' receiver type inconsistently casts int to double

### ISSUE THREAD

**Issue by rotemdan** [dotnet/roslyn#58634] opened 2022-01-05 12:05 UTC
**Version Used**: 
`6.0.0`

**Steps to Reproduce**:
```cs
var s = "a";

object result = s switch
{
	"a" => (int) 1234,
	"b" => 3.14,
	"c" => true,
	_ => throw new Exception("")
};

Console.WriteLine(result2.GetType().Name); // Prints "Int32"!
```

Compare with:
```cs
var s = "a";

object result = s switch
{
	"a" => (int) 1234,
	"b" => 3.14,
	_ => throw new Exception("")
};

Console.WriteLine(result2.GetType().Name); // Prints "Double"!
```

**Expected Behavior**:
Second example should behave like first, and not implicitly cast to `Double`, since it has an `object`-typed target.

**Actual Behavior**:
Second example implicitly casts to `Double`, costing me hours of unnecessary bug tracking to try to understand why some values in my program unexpectedly came out as `Double` instead of `Int` after I removed some cases from a simple `switch` expression.

**Comment by CyrusNajmabadi** [comment] 2022-01-05 12:21
This is by design. First, we check if there is a common type all the switch branches have. This is done by checking each branch and seeing if they can all convert to a type in another branch. If so, this is the type and the branches are converted to. 

If not, we then Target-type the switch, looking to see if there's a type in the surrounding context that each branch can be assigned to. 

So when you have all three branches, there is no common conversion for the branches (given int, double and bool). So we then target type each branch to object, giving them all distinct types. 

However, when you remove the bool branch then each branch *can* be converted to double, so that's the common type and that is used without looking for the target type.

**Closed by CyrusNajmabadi** 2022-01-05 12:21 UTC
Labels: Area-Compilers, untriaged

**Comment by rotemdan** [comment] 2022-01-05 12:30
@CyrusNajmabadi

Thanks for the quick reply. I don't think it is as straightforward as you describe. The first case wouldn't work unless I explicitly annotated the target type as `object`:

If I use `var` instead for `result`, I get a compile-time error:
```cs
var s = "a";

var result = s switch //  Error: No best type was found for the switch expression.
{
	"a" => (int) 1234,
	"b" => 3.14,
	"c" => true,
	_ => throw new Exception("")
};

Console.WriteLine(result2.GetType().Name); // Prints "Int32"!
```

Since having an explicit `object` receiver type seems to play an significant role in enabling this case, it becomes very confusing to have it ignored when the `bool` typed case is removed from the expression.

I don't think this behavior is intuitive or sensible. But I guess there's nothing I can do. It's unfortunate you've closed the issue so fast.

**Comment by CyrusNajmabadi** [comment] 2022-01-05 15:49
> I don't think this behavior is intuitive or sensible. But I guess there's nothing I can do. It's unfortunate you've closed the issue so fast.

The issue was closed because the compiler is working properly here as per the language spec. If you want the language to change you'll have to open a discussion over at GitHub.com/dotnet/csharplang. 

If the language is changed, then we'll update the compiler over here in Roslyn :-)

**Comment by CyrusNajmabadi** [comment] 2022-01-05 15:50
> The first case wouldn't work unless I explicitly annotated the target type as object:

Correct. Because now there is a "Target type". When you use 'var' there is no Target type.
