### ISSUE TITLE
[Concept] abstract enums

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#10098] opened 2016-03-25 15:03 UTC
abstract enums
-------------------

```C#
abstract enum E : int
{
  None = 0;
}

abstract enum E' : E
{
  None = 0, // Error: Already defined
  One  = 1
}

sealed enum E'' : E
{
  None = 2, // Error: Already defined
  One  = 1, // Error: Already defined
  Two  = 2
}
```
**Inherting from a `sealed enum`**
```c#
sealed enum F : E'' // Error: (E'') is sealed. Hence can not be inherited
{
 ...
} 
```

**Generic Constraints**
The CLR does allow constrained generics based on enums, just that it isn't (yet) expressible in C# or VB. 
```c#
Foo <T : {enum, E} >( T e )
{

}
```

**Existing `enum` construct**
```C#
enum Foo { ... }
```
 would be equivalent to
```C#
sealed enum Foo { ... }
``` 

**Casts**
All casting between `abstract enum` and a inherited enum,or vis-versa, must be explicit.

**Comment by HaloFour** [comment] 2016-03-25 17:42
Seems mostly like a dupe of #9120

**Closed** 2016-03-29 19:51 UTC
Labels: Area-Language Design, Resolution-Duplicate
