### ISSUE TITLE
IDE0060 Attribute Suppression is causing IDE0079

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61142] opened 2022-05-04 21:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0060-Attribute-Suppression-is-causing/10027813)._

---
I have the following code

```
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "This is required for the method to be implemented.")]
		public static implicit operator DbBooleanValue(DBNull value) => DbBooleanNull;
```

Which is resulting in:

Severity	Code	Description	Project	File	Line	Suppression State	Priority
Message	IDE0079	Remove unnecessary suppression	

If I remove it the IDE0060 comes back.

---
#### Feedback Bot on 5/1/2022, 03:44 AM: 

(private comment, text removed)
#### Feedback Bot on 5/4/2022, 01:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2022-05-13 19:40
Duplicate of #49669

**Closed by vatsalyaagrawal** 2022-05-13 19:40 UTC
Labels: Area-IDE, untriaged
