### ISSUE TITLE
It should be possible to get MetadataImportOptions.All via public API

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#6748] opened 2015-11-13 00:25 UTC
Currently, if you get symbols from metadata, the private members are not imported. Internally, there are `MetadataImportOptions.All`, but there is no way to specify those semantics via public API.

We are investigating using Roslyn to walk metadata for binary analysis scenarios and would need to be able to see the private members too.

cc @tmat

**Comment by tmat** [comment] 2015-11-13 00:29
The same API would be used by scripting (```#r!```).

**Comment by bkoelman** [comment] 2015-11-16 10:53
Duplicate of https://github.com/dotnet/roslyn/issues/5049?

**Comment by jaredpar** [comment] 2016-07-19 15:31
Pushing out after discussing with @nguerrera

**Closed** 2018-01-26 21:46 UTC
Labels: Area-Compilers, Concept-API, Feature Request, Interactive-ScriptingLogic, Resolution-Fixed, help wanted
