### ISSUE TITLE
LINQ operators disregard nullabilities

### ISSUE THREAD

**Issue by NextTurn** [dotnet/roslyn#44913] opened 2020-06-06 11:51 UTC
**Version Used**: Visual Studio 2019 Version 16.6.1

**Steps to Reproduce**:

```cs
#nullable enable

using System.Collections.Generic;
using System.Linq;

class MyClass
{
    static void Method()
    {
        _ = from MyClass item1 in Enumerate()
            select item1;

        foreach (MyClass item2 in Enumerate())
        //               ~~~~~ Warning	CS8600	Converting null literal or possible null value to non-nullable type.
        {
        }
    }

    static IEnumerable<MyClass?> Enumerate()
    {
        throw new NotImplementedException();
    }
}
```

**Expected Behavior**:

CS8600 is reported for both `item1` and `item2`.

**Actual Behavior**:

CS8600 is only reported for `item2`.

**Comment by jcouv** [comment] 2020-06-06 17:02
Thanks for reporting this. It's a known issue/gap at the moment. We're still trying to figure out how to address it.
Closing as duplicate of https://github.com/dotnet/roslyn/issues/29863 (Implement nullability analysis in LINQ queries)

**Closed by jcouv** 2020-06-06 17:02 UTC
