### ISSUE TITLE
Cancelling Ctrl+. operation causes a gold bar

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#41218] opened 2020-01-25 01:06 UTC
**Version Used:** Version 16.5.0 Preview 3.0 [29723.142.master], Roslyn 3.5.0-beta3-20063-01+1f921815c4544e703bf721cb8e6c86d5cf6bda63

1. Do Ctrl+. on something that causes our threaded wait dialog to appear.
2. Click cancel.

**Expected:** it cancels nicely.

**Actual:** you get a gold bar with this stack below. This likely means that we're throwing an OperationCancelledException with a cancellation token that isn't the one that was originally handed to us.

```
System.OperationCanceledException: The operation was canceled.
 at System.Threading.CancellationToken.ThrowOperationCanceledException()
 at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioWorkspaceStatusServiceFactory.Service.<WaitUntilFullyLoadedAsync>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.<>c__DisplayClass40_4.<TryGetSuggestedActionSets>b__1()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)
  --- End of stack trace from previous location where exception was thrown ---at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jasonmalinowski** [comment] 2020-01-25 01:35
FYI to @mavasani if this is a recent change.

**Comment by mavasani** [comment] 2020-02-25 04:11
Tagging @olegtk - this seems to have started happening since we moved to the new overload [ISuggestedActionsSource3.GetSuggestedActions](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FLanguage%2FDef%2FIntellisense%2FSuggestions%2FISuggestedActionsSource3.cs&_a=contents&version=GBmaster), which takes a `IUIThreadOperationContext` argument. #41458 is another example where we see an unhandled `OperationCanceledException` from this API invocation.

We are using the cancellation token from the passed in `IUIThreadOperationContext`, see [here](http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,171). @olegtk, do you see anything wrong in our usage of the context?

**Comment by olegtk** [comment] 2020-02-25 04:47
That's a known issue (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1070469). I believe it's caused by an editor change, I don't think you are doing anything wrong. FWIW we target 16.6 currently. CC @AmadeusW

**Comment by mavasani** [comment] 2020-02-25 04:48
Ah thanks @olegtk. I'll close this issue.

**Closed by mavasani** 2020-02-25 04:48 UTC
Labels: Area-IDE, Bug, Urgency-Soon

**Comment by mavasani** [comment] 2020-03-03 18:10
Also reported at https://developercommunity.visualstudio.com/content/problem/936144/vs-1650-preview-40-csharpaddimportcodefixprovider.html
