### ISSUE TITLE
Aliased type not colored in intellisense

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#21118] opened 2017-07-25 18:19 UTC
**Version Used**: 2.3.0.61907

**Steps to Reproduce**:

```C#
using BLA = Int32;

class Program
{
    List<BLA> l = new List<BLA>(|
}
```

**Expected Behavior**: The BLA in intellisense tooltip to have the same color as in the code editor.

**Actual Behavior**: The alias is not colored:
![untitled](https://user-images.githubusercontent.com/10546952/28587160-1b6e8028-716e-11e7-89d1-ae50ce66123f.png)

**Comment by CyrusNajmabadi** [comment] 2022-10-28 23:15
Dupe of https://github.com/dotnet/roslyn/issues/16353.

**Closed by CyrusNajmabadi** 2022-10-28 23:15 UTC
Labels: Bug, help wanted, Area-IDE
