### ISSUE TITLE
IntelliSense turns properties used as arguments into lowercase

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#49813] opened 2020-12-05 18:34 UTC
**Version Used**: VS 16.9.0 Preview 1

**Steps to Reproduce**:

1. Paste the following code:
```csharp
class Repro
{
    public int Length { get; }

    public void Test(Range x)
    {
    }
}
```
2. Try to type the following within `Test`:
```csharp
var (offset, length) = x.GetOffsetAndLength(Length);
```

**Expected Behavior**: you should be able to type that just fine.

**Actual Behavior**: IntelliSense will make `Length` lowercase in the argument, breaking the code.

**Screenshot**:

![yqytdKpaL1](https://user-images.githubusercontent.com/10199417/101260500-c8196f00-3730-11eb-9b15-f995ead34d5d.gif)

**Comment by genlu** [comment] 2021-02-23 18:53
@Sergio0694 Could you please check if `length` which was selected and committed is provided by IntelliCode (i.e. item prefixed with a star)?

**Comment by genlu** [comment] 2021-02-24 02:00
@Sergio0694 Quick question, since the keystroke isn't captured in the git, How did you commit the selected item "length"? 
![image](https://user-images.githubusercontent.com/788783/108933992-f5bfd700-7600-11eb-8dba-8898cecd3798.png)

**Comment by Sergio0694** [comment] 2021-02-24 02:24
Hi @genlu, I committed by just typing ")", since the autocomplete will just skip it and move ahead when that character is already present (though this is a bit bugged when there's multiple closed parentheses, will need to open another issue for that...). I also tested it again just now and the same happens if I commit with TAB as well. Hope this helps! 🙂

**Comment by genlu** [comment] 2021-02-24 19:30
Thanks @Sergio0694, I think I understand the cause of this now, a fix is under review. However, from your screenshot, the item "length" appears to be soft-selected. 
- Are you in "Suggestion Mode"?  Otherwise, it should be hard-selected like below

![image](https://user-images.githubusercontent.com/788783/109054376-a5915500-7692-11eb-94ce-f412addfd6f1.png)

- Also, typing ")" shouldn't commit a soft-selected item, not sure what's going on here since I can't repro it.

**Closed** 2021-03-03 19:53 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense
