### ISSUE TITLE
Compiler Service tests don't handle spaces

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9866] opened 2016-03-17 23:25 UTC
These tests fail on my enlistment which has spaces (because i enjoy pain):

```
Errors Roslyn.Compilers.CompilerServer.UnitTests.dll:
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_CS [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CscFallBackOutputUtf8 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileVbc [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Shared [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Bug1024619_01 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_VB [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Share [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Bug1024619_02 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileCsc [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.VbcFallbackUtf8 [FAIL]
  Command: C:\Users\davkean\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe "Binaries\Debug\Roslyn.Compilers.CompilerServer.UnitTests.dll"  -xml "Binaries\Debug\xUnitResult
  s\Roslyn.Compilers.CompilerServer.UnitTests.dll.xml" -noshadow -verbose
  xUnit output log: Binaries\Debug\xUnitResults\Roslyn.Compilers.CompilerServer.UnitTests.dll.out.log
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_CS [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CscFallBackOutputUtf8 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileVbc [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Shared [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Bug1024619_01 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_On_Shared_VB [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8Output_WithRedirecting_Off_Share [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Bug1024619_02 [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.Utf8OutputInRspFileCsc [FAIL]
      Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.VbcFallbackUtf8 [FAIL]
```

**Comment by davkean** [comment] 2016-03-17 23:25
tag @jaredpar

**Comment by jaredpar** [comment] 2018-01-04 21:20
Closing as a dupe of #20929

**Closed by jaredpar** 2018-01-04 21:20 UTC
Labels: Area-Compilers, Bug, Test
