### ISSUE TITLE
Index from the end doesn't work with string

### ISSUE THREAD

**Issue by llRandom** [dotnet/roslyn#34840] opened 2019-04-08 20:01 UTC
**Version Used**: .NET Core 3.0.100-preview3-010431, C# 8

**Steps to Reproduce**:

1. Compile the following code

        static void Main(string[] args)
        {
            var letter = "test"[^1];
        }

build succeeded

2. Launch the program

**Expected Behavior**: normal program execution

**Actual Behavior**: unhandled exception:

    System.InvalidProgramException
      HResult=0x8013153A
      Message=Common Language Runtime detected an invalid program.
      Source=<Cannot evaluate the exception source>
      StackTrace: <Cannot evaluate the exception stack trace>

If I use `"test".ToArray()[^1]` instead, it works fine.

**Comment by svick** [comment] 2019-04-15 18:29
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/34209.

**Comment by gafter** [comment] 2019-07-16 18:29
a duplicate of #34209.

**Closed by gafter** 2019-07-16 18:29 UTC
Labels: Area-Compilers, Bug, New Language Feature - Range
