### ISSUE TITLE
IDE0059 Quick Fix Duplicates Region

### ISSUE THREAD

**Issue by KylePolansky** [dotnet/roslyn#51401] opened 2021-02-22 21:47 UTC
**Version Used**: 
Visual Studio Version 16.8.5

**Diagnostic ID**: [IDE0059](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0059): `Remove unnecessary value assignment`

**Description of Bug**:
When applying a remove redundant assignment quick fix for IDE0059 where the affected code is between a [preprocessor region](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region), the region is duplicated when applying the quick fix.

**Steps to Reproduce**:
Build a project with the following boilerplate:
ClassLibrary1:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

.editorconfig
```markdown
[*.cs]
# IDE0059: Remove unnecessary value assignment
dotnet_diagnostic.IDE0059.severity = error
```

Class1.cs
```csharp
namespace ClassLibrary1
{
    public class Class1
    {
        public string ReturnEmptyString()
        {
            #region region1

            string returnValue = null;

            #endregion

            returnValue = string.Empty;
            return returnValue;
        }
    }
}
```

In Class1.cs, there is an IDE0059 on the line `string returnValue = null;`

Click on the yellow light bulb in Visual Studio and apply the "Return redundant assignment" quick fix.

After running the quick fix, the file looks like:

Class1.cs:
```csharp
namespace ClassLibrary1
{
    public class Class1
    {
        public string ReturnEmptyString()
        {

            #region region1

            #region region1

            #endregion

            string returnValue = string.Empty;
            return returnValue;
        }
    }
}
```

The line `string returnValue = string.Empty;` is transformed like expected, however, there is now an extra unwanted `#region region1`. The extra region causes a compilation error, and in large files with many regions, figuring out which extra region to remove can be tedious.

**Expected Behavior**:

An extra region should not be added with the IDE0059 quick fix.

**Actual Behavior**:

A region is added with the IDE0059 quick fix.

Edit: Simplified .csproj boilerplate

**Comment by Youssef1313** [comment] 2021-02-23 10:04
Related to (but not duplicate of): https://github.com/dotnet/roslyn/issues/45711

**Comment by DoctorKrolic** [comment] 2022-03-11 11:31
Can't repro in VS 2022 v17.2 Preview 1:
![devenv_Dvg8tYmVqX](https://user-images.githubusercontent.com/70431552/157858782-192e7748-1443-4796-9668-1d8430988064.gif)
The only thing, that is unexpected here, is a redundant blank line that gets inserted before the `#region region1`

**Comment by Youssef1313** [comment] 2022-03-11 11:41
Probably it got fixed by https://github.com/dotnet/roslyn/pull/48252
It would be good IMO if the extra blank line is removed too if the fix is going to be small.

**Comment by CyrusNajmabadi** [comment] 2022-03-11 15:07
Closing out as the main issue is fixed.  thanks! :)

**Closed by CyrusNajmabadi** 2022-03-11 15:07 UTC
Labels: Bug, help wanted, Area-IDE
