### ISSUE TITLE
CS8604 warning when using MaybeNullWhen and return value is assigned

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/roslyn#45587] opened 2020-07-01 15:29 UTC
**Version Used**: 8.0

**Steps to Reproduce**:

When calling a method with an `out` parameter annotated with `MaybeNullWhen`, the flow analyser seems to fail when the return value is assigned to a variable before being scrutinised.

Compile this code with `<Nullable>enable</Nullable>`:

```csharp
using System.Diagnostics.CodeAnalysis;

class Example
{
    void OK()
    {
        if (TryParse("foo", out var result))
        {
            DoSomething(result);
        }
    }
    void Warning()
    {
        var success = TryParse("foo", out var result);
        if (success)
        {
            DoSomething(result);
        }
    }
    bool TryParse(string s, [MaybeNullWhen(false)] out object result)
    {
        // dummy implementation
        result = default;
        return false;
    }
    void DoSomething(object item)
    {
    }
}
```

**Expected Behavior**:

No warning in either the `OK` or the `Warning` methods. (They self-evidently behave identically.)

**Actual Behavior**:

CS8604 warning ("Possible null reference argument for parameter 'item' in 'void Example.DoSomething(object item)'") inside the `Warning` method.

**Comment by RikkiGibson** [comment] 2020-07-01 20:03
Duplicate of #27011

**Closed by RikkiGibson** 2020-07-01 20:03 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-Duplicate
