### ISSUE TITLE
ref locals marked as redundant/never used

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#32957] opened 2019-01-30 16:55 UTC
**Version Used**: VisualStudio.16.Preview/16.0.0-pre.2.0+28522.59

Related to #32856

**Steps to Reproduce**:
```C#
static void Main(string[] args)
{
    int[] a = new int[4];

    ref int ra = ref a[0];
    ra = 4;

    Console.WriteLine(a[0]);
}
```

**Actual Behavior**: `IDE0059 Value assigned to 'ra' never` used on both lines containing `ra`.

The fixes are very wrong. The first line suggests

```C#
_ = ref a[0];
int ra = 4;
```
which not only changes the behavior but also does not compile, and the second line suggests removing self altogether as a redundant assignment, which also changes the behavior.

**Expected Behavior**:

I would argue assignments to ref locals should mark them as used and should never be marked as redundant (unless perhaps clearly overwritten by another value).

**Comment by mavasani** [comment] 2019-01-31 17:32
Duplicate of https://github.com/dotnet/roslyn/issues/32855

**Closed by mavasani** 2019-01-31 17:32 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle
