### ISSUE TITLE
Improve the IDE experience around delegates

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#49494] opened 2020-11-19 13:53 UTC
Today when using typed delegates (which still happens because they can be used to name arguments of functions) the IDE doesn't help you figure out what the signature of the delegate is:

![image](https://user-images.githubusercontent.com/95136/99674654-bd7e8a80-2a4c-11eb-8c03-49ebfcd45228.png)

To get useful parameter help for lambda syntax I need to type new (which is unnatural for a delegate):

![image](https://user-images.githubusercontent.com/95136/99674810-e9017500-2a4c-11eb-8464-0b321ee627f2.png)

Now I can see the delegate type takes nothing and returns an ISyntaxReceiver. We should have a way to make this show up by default or via some gesture without newing up the delegate type.

cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment] 2020-11-19 14:40
@jnm2 didn't you add this feature? :-)

**Comment by jnm2** [comment] 2020-11-19 16:15
I created a prototype, waited for feedback, and haven't had uninterrupted time to get back into it since then: https://github.com/dotnet/roslyn/issues/46190

**Comment by CyrusNajmabadi** [comment] 2020-11-19 17:51
Ok cool  :)

**Comment by jnm2** [comment] 2020-11-30 02:34
Tease:

![image](https://user-images.githubusercontent.com/8040367/100562264-1f2ec800-3289-11eb-9fb3-d49187f8cbb4.png)

![image](https://user-images.githubusercontent.com/8040367/100562286-3b326980-3289-11eb-80d1-fc1b86cc0f25.png)

**Comment by sharwell** [comment] 2020-12-09 19:48
Duplicate of #46190

**Closed by sharwell** 2020-12-09 19:48 UTC
Labels: Area-IDE, Feature Request, help wanted
