### ISSUE TITLE
The IDE does not respect 'open brace on new line' preferences for switch expressions.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38896] opened 2019-09-26 23:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/719582/the-ide-does-not-respect-open-brace-on-new-line-pr.html)._

---
The 'fix formatting' option and automatic formatting seem to really want to put the open brace on a new line in code such as the following:
```
allWires.Append(i switch {
	0 =&gt; &quot;CutFirstWire CutSecondWire&quot;,
	1 =&gt; &quot; CutThirdWire&quot;,
	2 =&gt; &quot; CutFourthWire&quot;,
	3 =&gt; &quot; CutFifthWire&quot;,
	_ =&gt; &quot;&quot;
});
```
This occurs even with `csharp_new_line_before_open_brace = none` specified in `.editorconfig`, and there is no option in the GUI for switch expressions. Such an option should be added.

---
#### Visual Studio Feedback System on 9/2/2019, 00:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by 20chan** [comment] 2019-09-27 03:42
+1 on this issue. Also there is no ways to change indent styles of switch expression in Visual Studio Options, only Allman.

**Comment by sharwell** [comment] 2019-09-27 15:48
This should probably be using the existing option `object_collection_array_initializers`.

**Comment by CyrusNajmabadi** [comment] 2019-09-27 16:06
I would personally expect this to be affected by the exact same option that covers switch statements. 

Having something called 'array_initializers' have an effect on switch expressions just seems super wacky

**Comment by sharwell** [comment] 2019-10-14 21:59
Duplicate of #36913

**Closed by sharwell** 2019-10-14 21:59 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-Formatter, help wanted
