### ISSUE TITLE
File line endings changed from LF to MIXED when writing brackets after if statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53004] opened 2021-04-28 23:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/File-line-endings-changed-from-LF-to-MIX/1330751)._

---
[severity:It's more difficult to complete my work]
When writing an if statement in a C# file that has unix line endings, it will change to mixed when the brackets are written (auto format).
Watch the video and look closely at the LF text in the editor, and how it changes to mixed as I'm writing.
It takes time to correct this every time VS decides to mix line endings, so a fix would be very nice.

I'd recommend the video, but here are steps to reproduce:
1 Open a .cs file which has line endings set as LF
2 write if &lt;enter> {
3 Now file has mixed line endings

---
#### Feedback Bot on 2/4/2021, 10:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/5/2021, 00:22 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-04-28 23:39
I was able to reproduce this with both of the following:

1. Type `if`, and then hit <kbd>Enter</kbd>, <kbd>{</kbd>, <kbd>Enter</kbd>
1. Type `if (true` and then hit <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Comment by Harteex** [comment] 2021-05-22 14:06
Just a note, this isn't limited to "if", but it happens all the time when the formatter does things.
Some more examples on how to reproduce:
1. Type <kbd>{</kbd>, and then hit <kbd>Enter</kbd>
2. Indent any line too much or too little, then format the document

**Comment by ju57u5** [comment] 2021-06-17 11:29
> 
> 
> Just a note, this isn't limited to "if", but it happens all the time when the formatter does things.
> Some more examples on how to reproduce:
> 
>     1. Type {, and then hit Enter
> 
>     2. Indent any line too much or too little, then format the document

3. Add missing using statements.

**Comment by AidanMcK** [comment] 2023-01-07 08:21
If either of these two settings are enabled, then line endings are changed from LF to CRLF after pressing enter after a "{" after an if statement:

- Text Editor -> C# -> Formatting -> General -> Automatically format when typing
- Text Editor -> All Languages -> General -> Automatic brace completion

If both these options are turned off the problem does not occur, but then one has to manually do the indentation which is a pain.

So the problem is still alive and kicking in Visual Studio Version 17.5.0 Preview 2.0.

**Comment by CyrusNajmabadi** [comment] 2023-01-07 13:27
@AidanMcK this is on our backlog. If you're interested in contributing a fix though, we'd be happy to work with you on that!

**Comment by CyrusNajmabadi** [comment] 2024-10-25 05:37
Closing out as we haven't gotten broad feedback on this.

**Closed by CyrusNajmabadi** 2024-10-25 05:37 UTC
Labels: Bug, help wanted, Area-IDE, IDE-Formatter
