### ISSUE TITLE
Value Tracking

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#34566] opened 2019-03-28 22:27 UTC
[Internal Ask]
aka. Inspect or Value Origin/Destination

**Version Used**: Visual Studio 2019

**Scenarios**:
> 1. If I change the value of this variable, what code in which methods will be impacted? 
> 2. We hit a NullReferenceException due to some parameter or other variable being null. How could this have happened? Where and from which methods could this value have come from? (The value doesn't have to be null, could be any other constant value, but null is probably the most common case)

**Expected Behavior**:
Visual Studio provides some way to open a separate window (keyboard shortcut or context menu) and you can inspect origin or destination of the value.

**Comment by sharwell** [comment] 2019-03-28 22:30
Possible duplicate of #25994?

**Comment by kendrahavens** [comment] 2019-03-28 22:31
I believe so. I'm following up for more details. I'd like to keep this issue open or at least update the name of the pre-existing issue. This was asked for by name twice from internal teams.

**Comment by sharwell** [comment] 2019-04-03 19:41
Duplicate of #25994

**Closed by sharwell** 2019-04-03 19:41 UTC
Labels: Area-IDE, Area-Interactive, Feature Request, InternalAsk
