### ISSUE TITLE
32-bit Integration Tests failing to upload servicehub logs

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50847] opened 2021-01-28 00:05 UTC
I'm seeing this failure constantly in seemingly only the 32-bit integration tests:

`Cannot find path 'F:\workspace\_work\1\s\artifacts\tmp\Release\servicehub\logs' because it does not exist.`

https://dev.azure.com/dnceng/public/_build/results?buildId=968638&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&s=d654deb9-056d-50a2-1717-90c08683d50a&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=780

https://dev.azure.com/dnceng/public/_build/results?buildId=968669&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=789

I know @jasonmalinowski has hit this at least once as well.

@sharwell, any ideas?

**Comment by 333fred** [comment] 2021-01-28 00:09
Some more hits:

https://dev.azure.com/dnceng/public/_build/results?buildId=968663&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=794
https://dev.azure.com/dnceng/public/_build/results?buildId=968583&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=777
https://dev.azure.com/dnceng/public/_build/results?buildId=968569&view=logs&j=922f7fe3-0735-5839-4d76-f6d8a5e047bd&t=d3c89a87-2123-56c4-3b91-63fa06060730&l=793
https://dev.azure.com/dnceng/public/_build/results?buildId=968418&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=806
https://dev.azure.com/dnceng/public/_build/results?buildId=968401&view=logs&j=9e93af80-e8ae-58aa-0f47-c3fff1766aa4&t=03df6b5c-2902-5a61-fef1-7cb300e3f14b&l=794
https://dev.azure.com/dnceng/public/_build/results?buildId=968346&view=logs&j=2453e3f2-953c-58ff-9884-5e26e6273c96&t=32da825c-c2ca-56bf-f86e-e88510cb3377&l=799

The pipeline has a 50% pass rate over the past 2 weeks, which is not good.

**Comment by sharwell** [comment] 2021-01-28 01:24
Duplicate of #50521

**Closed by sharwell** 2021-01-28 01:24 UTC
Labels: Area-Infrastructure, Urgency-Soon, untriaged
