### ISSUE TITLE
Intellisense moving current item to the top of the list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53557] opened 2021-05-20 20:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-moving-current-item-to-the-/1403253)._

---
<p>I love the new suggest popular items in the intellisense list (which move the most used items to the top of the list)<br>
but it has a big draw back</p>
<p>often when coding you will copy bits of code and then update them for different controls, classes etc</p>
<p>eg I have code like<br>
txtAttachmentsPath.Text = “”</p>
<p>I then copy the previous line (often using the awesome CTRL+D to duplicate it)<br>
and put my cursor at the end of the “txtAttachmentsPath” and press backspace<br>
the intellisense list shows up<br>
it used to jump alpahbetically to that spot in the list so i could easily change it to the next textbox item just pressing up or down arrow keys a few times</p><p><a href="https://aka.ms/dc/image?name=Ba32c530548e348f6b174a18e35889aed637494422790882066_vsintelliissue2.jpg&amp;tid=a32c530548e348f6b174a18e35889aed637494422790882066"> Image:image?name=Ba32c530548e348f6b174a18e35889aed637494422790882066_vsintelliissue2.jpg&amp;tid=a32c530548e348f6b174a18e35889aed637494422790882066</a></p>
<p>now it lists the current textbox at the top of the intellisense and the rest of them are way down in the list, this forces me to delete the whole textboxname and have to type txt to get the list to the position I want to browse.</p><p></p><p><a href="https://developercommunity2.visualstudio.com/storage/attachments/132361-vsintelliissue1.jpg"> Image:132361-vsintelliissue1.jpg</a></p><p><br>
so speed of finding the item I am after is greatly impacted</p>
<p>update: I did find a workaround if you put the cursor at the start of the “txtAttachmentsPath” and press CTRL + Space it does go to the correct spot in the list</p>
<p>can I suggest if you are deleting a character to show the intellisense list to forego the smart intellisense and just go to the item alphabetically<br>
like what happens in my above update line</p>
<p>I am coding in Visual Basic<br>
Microsoft Visual Studio Professional 2019<br>
Version 16.5.2</p>

---
#### Feedback Bot on 5/3/2020, 07:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/6/2020, 02:59 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 5/8/2020, 03:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/2/2020, 09:58 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 6/18/2020, 07:44 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Scott Ward on 6/18/2020, 07:50 PM: 

<p>hopefully this is worth considering, it effects my coding every single day as a full time developer</p><p>please don't get rid of the nice functionality visual studio used to have and make it less productive</p>

#### Rod Weir on 7/14/2020, 08:10 PM: 

<p>Agreed - would be good to restore the previous behaviour of the intellisense so that class properties etc are all displayed together (for easy picking) instead of moving the current one to the top of the list and then having to scroll down the list to find the others.</p>

#### Feedback Bot on 4/20/2021, 11:06 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2021-05-20 21:50
@genlu this is a dupe right?

**Comment by genlu** [comment] 2021-11-12 19:06
@CyrusNajmabadi I believe this is a dupe of https://github.com/dotnet/roslyn/issues/52721

I've been thinking, instead of changing the sorting from pattern match result back to alphabetical order, can we add a new pattern match kind `CommonPrefix` (plus the common prefix length), which would match "MyA" to "MyB" with common prefix length equal to 2. We can specify a minimal common prefix length to use when creating the pattern matcher too.

**Closed** 2021-11-12 19:06 UTC
Labels: Area-IDE, Concept-Continuous Improvement, IDE-IntelliSense
