### ISSUE TITLE
Making a virtual interface method abstract then implementing it results in MissingMethodException

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#70094] opened 2023-09-23 06:38 UTC
**Version Used**: 4.6.0-3.23259.8 (c3cc1d0c). .NET 7.0.304

**Steps to Reproduce**:

Compile and run the following. [SharpLab version](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHgWQB4BhAPgAoBKAbjz1QBYACYgFUquYHcALAUzD9mbZiGYBJZgF4yIgHQBpanXy4AllGCCAZgEMAxsKkBvZqgDM5zADZmAN3VhgEPQBtzLZVzOpMATgoAIgAjINpmAF8ovE1tMH0jZgAZMUlmX1tmPRCAZ2AwQ2BPSSUVGNwMZhI01N8rPzsmZm8ZOT9AoJJwmiigA)
```cs
M<C>();

void M<T>() where T : I => T.K();

interface I { public static virtual void K() { Console.WriteLine("b"); } }
interface L : I { static abstract void I.K(); }
class C : L { public static void K() => Console.WriteLine("C"); }
```

**Diagnostic Id**: N/A

**Expected Behavior**: "C" is written to stdout or compiler error.

**Actual Behavior**: MissingMethodException

**Comment by AlekseyTs** [comment] 2023-09-25 17:55
Possibly a dupe of https://github.com/dotnet/runtime/issues/80350

**Comment by jcouv** [comment] 2023-09-25 21:27
Looks like it. Closing as dupe of https://github.com/dotnet/runtime/issues/80350 (FWIW, that issue was closed and split into two new runtime issues)

**Closed by jcouv** 2023-09-25 21:27 UTC
Labels: Area-Compilers, untriaged
