### ISSUE TITLE
Unrecoverable VS error from invalid local function in top level statements

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#48200] opened 2020-09-30 18:12 UTC
**Version Used**: 
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 3.2
VisualStudio.16.Preview/16.8.0-pre.3.2+30524.135
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:

Paste the following code in VS. Note that this is the whole file i.e. there's no containing type or method
```cs
#nullable enable

        IEnumerable<T1> GetItems<T1>(IEnumerable<T1> input)
        {
           return null!;
        }
#nullable restore
```

**Expected Behavior**:
Error for not resolved `IEnumerable<T>`

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/5566206/94722964-b6969e00-0360-11eb-912e-4ab30541da09.png)

![image](https://user-images.githubusercontent.com/5566206/94722915-a4b4fb00-0360-11eb-8e54-276d6e60f0b5.png)

**Comment by jcouv** [comment] 2022-03-17 05:33
Looks like duplicate of https://github.com/dotnet/roslyn/issues/58521 which was fixed. Closing

**Closed by jcouv** 2022-03-17 05:33 UTC
Labels: Bug, Area-Compilers, New Language Feature - Simple Programs
