### ISSUE TITLE
Cannot navigate to System.ValueTuple

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#19192] opened 2017-05-02 22:30 UTC
**Version Used**: 

15.2

**Steps to Reproduce**:

1. Type the local declaration `System.ValueTuple<int, int> x;`
2. Click on `ValueTuple` and hit F12 (navigate to definition)

**Expected Behavior**:

Navigate to the definition of ``System.ValueTuple<T1, T2>`

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/3804346/25642043/2e1004f4-2f4c-11e7-80e9-21a3942dc188.png)

**Comment by Pilchie** [comment] 2017-05-03 19:27
Dupe of https://github.com/dotnet/roslyn/issues/17360.  (Fixed for 15.3)

**Closed by Pilchie** 2017-05-03 19:27 UTC
Labels: Area-IDE, Bug
