### ISSUE TITLE
FAR on Reflection references

### ISSUE THREAD

**Issue by wbalbal** [dotnet/roslyn#26069] opened 2018-04-10 16:41 UTC
**Version Used**:  2.7.0

**Steps to Reproduce**:

1. Use any kind of reflexion invocation of a type T in a project
2. try to find all references of T type using symbol finder

**Expected Behavior**:

It should give you all refenreces including those using reflexion

**Actual Behavior**:
Nope it didn't :/

**Comment by RipPer56** [comment] 2018-04-11 14:08
If i have a class Foo like this

Class Foo{  
     public string Name { get; set; }
     public Foo(string name)
     {
          Name = name;
     }
}

And whatever class using it like this for an exemple

     public static void Main(){ 
          var nameProperty =foo.GetType().GetProperty("Name");
          Console.WriteLine(nameProperty.GetValue());  
     }  

Roslyn don't get me this usage . It will get only explicit usages like :
var foo = new Foo("coucou");
foo.Name; //roslyn with find this invocation

**Comment by Joe4evr** [comment] 2018-04-11 14:39
![](https://i.imgur.com/jks6Qqr.png)

Refle**ct**ion (there is no 'x') is something that you do at your own risk by going out of your way to invoke something without letting the compiler bind to it. Because the compiler doesn't bind to it, it will also not be seen as being used.

**Comment by Neme12** [comment] 2018-04-11 14:58
There's no way for the compiler to do this. What do you suggest we do here?

```c#
 public static void Main(){ 
      var nameProperty =foo.GetType().GetProperty(Console.ReadLine());
      Console.WriteLine(nameProperty.GetValue());  
 }
```

Should we predict the future and find references based on what string you're going to pass in?

**Comment by Neme12** [comment] 2018-04-11 15:00
Note that this is not an uncommon scenario. In most cases when people use reflection, we can't know statically what the invocation is going to be. If you do, you don't need reflection.

**Comment by CyrusNajmabadi** [comment] 2018-04-11 17:28
Instead of this:

```c#
 public static void Main(){ 
      var nameProperty =foo.GetType().GetProperty("Name");
      Console.WriteLine(nameProperty.GetValue());  
 }  
```

Do this:

```c#
 public static void Main(){ 
      var nameProperty =foo.GetType().GetProperty(nameof(Foo.Name));
      Console.WriteLine(nameProperty.GetValue());  
 }  
```

It more clearly expresses your intent, and is also something the language and tooling understands.

**Comment by RipPer56** [comment] 2018-04-13 14:51
@CyrusNajmabadi the problem is that if someone's making a tool that anybody can use. So you won't have then a way to force the way they're using reflexion like you said

**Comment by CyrusNajmabadi** [comment] 2018-04-13 18:03
@RipPer56 Sorry, i don't know what that means.

**Comment by jmarolf** [comment] 2018-04-13 22:57
@RipPer56 The reason we can't show reflection use cases is we don't know how.  If you can describe an approach that would allow us to do that  we would happily implement it.

**Comment by CyrusNajmabadi** [comment] 2022-10-29 01:04
Closing out as by design.

**Closed by CyrusNajmabadi** 2022-10-29 01:04 UTC
Labels: Question, Area-IDE, Resolution-Answered, Concept-Design Debt, IDE-Navigation
