### ISSUE TITLE
Warning reported for dereference after first dereference with `!`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#31733] opened 2018-12-13 00:32 UTC
Should not report a warning for `x.GetHashCode()` since the previous dereference in `x!.ToString()` succeeded:
```C#
#nullable enable

class Program
{
    static void F(object? x)
    {
        _ = x!.ToString();
        _ = x.GetHashCode(); // warning: may be null
    }
}
```

**Comment by cston** [comment] 2018-12-14 16:01
Note, subsequent warnings would not be reported if https://github.com/dotnet/roslyn/issues/31732 is implemented.

**Comment by jcouv** [comment] 2018-12-31 23:03
Closing as duplicate of https://github.com/dotnet/roslyn/issues/31732

**Closed** 2019-01-03 00:54 UTC
Labels: 4 - In Review, Area-Compilers, Bug, New Language Feature - Nullable Reference Types
