### ISSUE TITLE
C# async functions hold onto memory beyond lifetime of function

### ISSUE THREAD

**Issue by samwebster** [dotnet/roslyn#64607] opened 2022-10-10 17:56 UTC
We are seeing problems where async functions are holding onto references thereby causing large amounts of memory not to be released. This is due to the way call stacks are effectively reversed for synchronous continuations. I think the below example shows that this can happen with parameters (which become fields in the state machine) and value types (which are not cleaned up unlike other locals). I've prototyped a fix for the parameter issue - https://github.com/dotnet/roslyn/commit/e4f30581725718f2dac231d58e44cdd8215736cd. Joint work with @lazy.

**Version Used**: 
6.0

**Steps to Reproduce**:

```
while (true)
{
    await Task1();
    Check(arrayInMem: false);
}

static bool Check(bool? arrayInMem = null)
{
    for (int i = 0; i < 10; i++)
        GC.Collect();
    var totalMem = GC.GetTotalMemory(true);
    var mem = totalMem > 1_000_000_000;
    var weakref = Program.WeakRef.TryGetTarget(out _);
    if (mem != weakref)
        throw new Exception("mem check and weakref checks do not match");
    if (arrayInMem.HasValue && (arrayInMem.Value ^ mem))
        throw new Exception($"Failed check, should have returned in mem = {arrayInMem.Value}");
    return mem;
}

static async Task Task1()
{
    await Task2();
    // this shows 'reversed' stack -> Console.WriteLine(Environment.StackTrace);
    // At this point a developer would reasonably expect the array to be collectable
    Console.BackgroundColor = Check() ? ConsoleColor.Red : ConsoleColor.Black;
    Console.Write(Check() ? "*" : ".");
    await Task.Yield(); // prevents mem leaking to Main
}

static async Task Task2()
{
    Check(arrayInMem: false);
    var localMem = new byte[1_000_000_000];
    Program.WeakRef.SetTarget(localMem);
    Check(arrayInMem: true);

    await Task3(localMem); // pass new byte[] { localMem[0] } here to stop testing parameters

    // this causes failures even when the parameter issue is fixed in the compiler
    ReturnsTuple(localMem); // comment this out to stop testing value types
}

static async Task<int> Task3(byte[] mem)
{
    await Task.Delay(1);
    return mem[0];
}

static (byte[], int[]) ReturnsTuple(byte[] mem)
{
    return (mem, new int[] { mem[0] } );
}

public partial class Program
{
    static WeakReference<byte[]?> WeakRef = new WeakReference<byte[]?>(null);
}
```

**Expected Behavior**:

Memory can be freed in Task1 as soon as Task2 completes so you would see a row of dots

**Actual Behavior**:

Memory is not freed until the Task.Yield breaks the synchronous continuations, so you see a row of red asterisks

**Comment by jaredpar** [comment] 2022-10-10 20:14
> I think the below example shows that this can happen with parameters (which become fields in the state machine) and value types (which are not cleaned up unlike other locals). 

The example doesn't really help explain the problem you're trying to fix. In general unused parameters never make it to a field capture. Only used parameters do. So under what circumstances do you think a parameter can be not added as a field where it is today? 

The decision to not `default` out value types on scope exit was a deliberate design decision. There are trade off boths ways and the decision was for the current behavior based on larger analysis.

**Comment by samwebster** [comment] 2022-10-11 08:51
The example shows that memory is being held longer than the spec says it should.

The first reason for this is that the parameter to Task3 becomes a field in the state machine. That field is never cleared and as the state machine is in the call stack when the main part of Task1 is being executed, the memory cannot be collected. https://github.com/dotnet/roslyn/commit/e4f30581725718f2dac231d58e44cdd8215736cd allows this to be verified.

The second reason is the value type on the stack in Task2 that contains a reference to the array because of the call to ReturnsTuple. Doesn't this need to be cleared to be compliant with the spec as it has become inaccessible once executing the main part of Task1? It can certainly cause memory issues in production that are very non-intuitive and tricky to track down.

**Comment by jaredpar** [comment] 2022-10-11 15:46
> The first reason for this is that the parameter to Task3 becomes a field in the state machine. That field is never cleared and as the state machine is in the call stack when the main part of Task1 is being executed, the memory cannot be collected. https://github.com/dotnet/roslyn/commit/e4f30581725718f2dac231d58e44cdd8215736cd allows this to be verified.

The parameter is used after an `await` hence it must be a part of the state machine. There are trade offs to clearing parameters upon exit of the state machine and the whole it was found to be a more pragmatic decision to not do so. Yes this sample demonstrates the negative impact of that decision but it also doesn't account for the positive ones (reduced CPU cycles from zeroing out memory that probably didn't need to be zero'd out). 

> The second reason appears to be the value type on the stack in Task2 that contains a reference to the array because of the call to ReturnsTuple. 

The local is alive for the duration of the method hence it's sensible for it to be alive for the duration of the `Task`. 

> Doesn't this need to be cleared to be compliant with the spec as it has become inaccessible once executing the main part of Task1? 

No. The spec never guarantees such behavior.

**Comment by samwebster** [comment] 2022-10-12 13:16
> The local is alive for the duration of the method hence it's sensible for it to be alive for the duration of the Task.

Yes, it's alive during Task2 but should not still be live during the continuation in Task1?

> No. The spec never guarantees such behavior.

If I'm looking in the right place, https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#79-automatic-memory-management, says:

> if neither the object nor any of its instance fields can be accessed by any possible continuation of execution, including the running of finalizers, the object is considered inaccessible and the object becomes eligible for collection.

The references holding the array in memory are inaccessible once we get to the continuation in Task1 aren't they?

**Comment by jaredpar** [comment] 2022-10-12 18:00
> Yes, it's alive during Task2 but should not still be live during the continuation in Task1?

The `Task` returned from `Task2` has a reference to the internal state machine and that is keeping the references alive. This is a side effect of how the continuations are setup. The only way to prevent this is to clear out all state in the state machine on successful exit. Again that was considered and rejected do to the trade offs involved. 

> If I'm looking in the right place, https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#79-automatic-memory-management, says:

Yes that is the spec. It's a mix of describing the runtime though vs. the language. But nothing there covers this scenario and demands there is a spec violation. The closest is this line:

> If neither the object nor any of its instance fields can be accessed by any possible continuation of execution, other than the running of finalizers, the object is considered no longer in use and it becomes eligible for finalization.

In this case the fields are strongly held in memory through references so from the perspective of GC and runtime they are live and not collectible. Yes the locals have left the traditional C# scope and that puts it in a gray area but `async` is not unique here. The same type of behavior can be observed with iterators, lambdas, linq, etc ... Any code where C# does rewriting under the hood and creates an object to encapsulate the state can result in unexpected lifetime extension of locals. That is not considered a spec violation or bug. The compiler / runtime do as much as possible to remove these but there are always gaps you can find if you poke in the right places.

> The references holding the array in memory are inaccessible once we get to the continuation in Task1 aren't they?

There are references remaining. Consider this is the rough continuation code that completes `await Task2()`. 

```csharp
if (num != 0)
{ 
   ...
}
else
{
    awaiter2 = <>u__1;
    <>u__1 = default(TaskAwaiter);
    num = (<>1__state = -1);
}
awaiter2.GetResult();
Console.BackgroundColor = (<<Main>$>g__Check|0_0(null) ? ConsoleColor.Red : ConsoleColor.Black);
```

Here `awaiter2` is the `TaskAwaiter` that has a reference to the `Task` that points to the `Task2` state machine. Yes indeed after that `awaiter2.GetResult()` call occurs the local is no longer referenced and logically eligible for collection. 

At the same time though that does not mean the JIT will actually mark it as eligible for collection. Determining if a local is eligible for collection is a non-trivial computational problem. The JIT is very good at this in many scenarios but it can easily get in a state where either it can't prove a local is no longer reachable or it decides it's not computationally worth the effort to make that determination. Generally the complexity of these methods mean that locals are not marked as eligible for collection as compared to non async methods. This is not a bug or spec violation though, it is simply the behavior of the runtime.

**Closed by jaredpar** 2022-10-12 18:00 UTC
Labels: Area-Compilers, untriaged
