### ISSUE TITLE
't! = s' should be an error.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#29903] opened 2018-09-14 22:18 UTC
```
        // PROTOTYPE(NullableReferenceTypes): 't! = s' should be an error.
        [Fact]
        public void SuppressNullableWarning_Assignment()
        {
            var source =
@"class C
{
    static void Main()
    {
        string? s = null;
        string t = string.Empty;
        t! = s;
        t! += s;
        (t!) = s;
    }
}";
            var comp = CreateCompilation(
                new[] { source, NonNullTypesTrue, NonNullTypesAttributesDefinition },
                parseOptions: TestOptions.Regular8,
                options: TestOptions.ReleaseExe);
            comp.VerifyDiagnostics(
                // (7,14): warning CS8601: Possible null reference assignment.
                //         t! = s;
                Diagnostic(ErrorCode.WRN_NullReferenceAssignment, "s").WithLocation(7, 14),
                // (9,16): warning CS8601: Possible null reference assignment.
                //         (t!) = s;
                Diagnostic(ErrorCode.WRN_NullReferenceAssignment, "s").WithLocation(9, 16)
                );
        }
```

**Comment by jcouv** [comment] 2018-09-17 20:11
Duplicate of https://github.com/dotnet/roslyn/issues/27522

**Closed** 2019-01-30 01:35 UTC
Labels: 4 - In Review, Area-Compilers, Bug, Language-C#, New Language Feature - Nullable Reference Types
