### ISSUE TITLE
Using navbar to go to location in SG files insta kills VS

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#49795] opened 2020-12-04 22:21 UTC
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineNumberFromPosition(Int32)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineNumberFromPosition(Int32)
   at Microsoft.CodeAnalysis.Text.Extensions+SnapshotSourceText+LineInfo.IndexOf(Int32)
   at Microsoft.CodeAnalysis.Text.Extensions+SnapshotSourceText+LineInfo.GetLineFromPosition(Int32)
   at Microsoft.CodeAnalysis.Shared.Extensions.SourceTextExtensions.GetLineAndOffset(Microsoft.CodeAnalysis.Text.SourceText, Int32, Int32 ByRef, Int32 ByRef)
   at Microsoft.CodeAnalysis.Shared.Extensions.SourceTextExtensions.GetLinesAndOffsets(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.Text.TextSpan, Int32 ByRef, Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Extensions.SourceTextExtensions.GetVsTextSpanForSpan(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.Text.TextSpan)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SourceGeneratedFileManager+OpenSourceGeneratedFile.NavigateToSpan(Microsoft.CodeAnalysis.Text.TextSpan)
   at Microsoft.VisualStudio.LanguageServices.Implementation.SourceGeneratedFileManager.NavigateToSourceGeneratedFile(Microsoft.CodeAnalysis.SourceGeneratedDocument, Microsoft.CodeAnalysis.Text.TextSpan)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToLocation(Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.DocumentId, System.Func`2<Microsoft.CodeAnalysis.Document,Microsoft.CodeAnalysis.Text.TextSpan>, System.Func`2<Microsoft.CodeAnalysis.Text.SourceText,Microsoft.VisualStudio.TextManager.Interop.TextSpan>, Microsoft.CodeAnalysis.Options.OptionSet)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToPosition(Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.DocumentId, Int32, Int32, Microsoft.CodeAnalysis.Options.OptionSet)
   at Microsoft.CodeAnalysis.Editor.Extensibility.NavigationBar.AbstractNavigationBarItemService.NavigateToVirtualTreePoint(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Editor.Shared.Utilities.VirtualTreePoint)
   at Microsoft.CodeAnalysis.Editor.Extensibility.NavigationBar.AbstractNavigationBarItemService.NavigateToSymbolItem(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Editor.Extensibility.NavigationBar.NavigationBarSymbolItem, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.NavigationBar.CSharpNavigationBarItemService.NavigateToItem(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Editor.NavigationBarItem, Microsoft.VisualStudio.Text.Editor.ITextView, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.NavigateToItem(Microsoft.CodeAnalysis.Editor.NavigationBarItem, Microsoft.CodeAnalysis.Document, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.CodeAnalysis.Editor.INavigationBarItemService, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.ProcessItemSelectionSynchronously(Microsoft.CodeAnalysis.Editor.NavigationBarItem, System.Threading.CancellationToken)
```

**Comment by jasonmalinowski** [comment] 2020-12-07 23:50
@CyrusNajmabadi Do you recall what you were trying to navigate to, or which generated file you were viewing? I'm unable to reproduce if I'm working in the generated files for the Roslyn repo which I presume you were working in. If a dump is available that'd also be helpful.

**Comment by CyrusNajmabadi** [comment] 2020-12-07 23:59
I think I first did a go to def on RecordDeclarationSyntax. I read in a non generated part. I then tried to use the nav bar to go to a prop in the other part, and it died

**Comment by jasonmalinowski** [comment] 2020-12-08 00:00
And I should comment that our navigation code in general is _really_ sketchy, because there's stuff like:

https://github.com/dotnet/roslyn/blob/5959af0c07350269c706e9cfedead5196bec558a/src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs#L348-L372

So it's possible some guards need to be put in place...

**Comment by jasonmalinowski** [comment] 2020-12-08 00:01
@CyrusNajmabadi Ah, that worked. Thanks, investigating.

**Comment by jasonmalinowski** [comment] 2020-12-08 00:07
Ah spoke too soon -- that reproduced the bug that was fixed in https://github.com/dotnet/roslyn/pull/49680. :-/

**Comment by jasonmalinowski** [comment] 2020-12-08 00:09
Yeah no repro with a newer build. 😢

**Comment by jasonmalinowski** [comment] 2021-01-07 19:55
Closing as no repro, but if we see this one again please reactivate!

**Closed by jasonmalinowski** 2021-01-07 19:55 UTC
Labels: Area-IDE, Bug, Tenet-Reliability
