### ISSUE TITLE
Add documentation for JSON and Regex related code style analyzer rules

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65771] opened 2022-12-05 09:18 UTC
<html>
<body>

JSON001 |   | Invalid JSON pattern
-- | -- | --
JSON002 |   | Probable JSON string detected
RE0001 |   | Invalid regex pattern

</body>
</html>

1. Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

2. Remove the below workarounds: https://github.com/dotnet/roslyn/blob/8aec055f5242a7de8b2e576acea12d329e257cc2/src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs#L260-L266

**Comment by Youssef1313** [comment] 2022-12-05 09:56
@CyrusNajmabadi You might want to work on top of https://github.com/dotnet/docs/pull/23203

**Comment by Youssef1313** [comment] 2022-12-05 09:56
Note that these analyzers are not in "Analyzers" layer, and hence won't work for command-line builds. This limitation should be documented.

**Comment by Youssef1313** [comment] 2022-12-05 09:57
@mavasani This is a duplicate of https://github.com/dotnet/roslyn/issues/48530. Can we close one of the issues and keep the other?

**Comment by mavasani** [comment] 2022-12-05 10:29
The test for checking help links may be unskipped after documenting this. See https://github.com/dotnet/roslyn/pull/51690

**Closed** 2022-12-05 17:09 UTC
Labels: Area-IDE, Feature Request, Documentation, untriaged
