### ISSUE TITLE
Find All References separately for property getter/setters

### ISSUE THREAD

**Issue by omariom** [dotnet/roslyn#20303] opened 2017-06-18 12:38 UTC
I'd like to put cursor on `set` keyword and Find All References  only for the  setter. The same for getter.

Currently I have to scan through all the refs.

**Comment by Pilchie** [comment] 2017-06-19 20:20
Duplicate of https://github.com/dotnet/roslyn/issues/17684

**Closed by Pilchie** 2017-06-19 20:20 UTC
Labels: Area-IDE, Feature Request

**Comment by omariom** [comment] 2017-06-19 20:33
@Pilchie 

Is https://developercommunity.visualstudio.com/ a better place to request such things?
I've just found it.

**Comment by Pilchie** [comment] 2017-06-19 21:14
Nope - for things that we would implement here on this project, we'd prefer to have the issues/feature requests be here too.

Sometimes, we'll event take feedback from developercommunity and re-file it here.  Of course, the problem can sometimes be knowing whether it's a Roslyn issue, or something else, but we'll let you know if there's a better place if it ends up in the wrong one.
