### ISSUE TITLE
Incorrect fading for redundant initialization

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34444] opened 2019-03-26 15:29 UTC
**Version Used**: Visual Studio 2019 RC

**Steps to Reproduce**:

```csharp
object value = null;
value = new object();
```

**Expected Behavior**:

The initializing expression `= null` is faded out.

**Actual Behavior**:

The variable declaration `value` is faded out, and the initializing expression is *not* faded.

**Comment by CyrusNajmabadi** [comment] 2022-10-31 22:30
@mavasani this was by design iirc?

**Comment by mavasani** [comment] 2022-11-01 04:09
Duplicate of https://github.com/dotnet/roslyn/issues/47784

**Closed by mavasani** 2022-11-01 04:09 UTC
Labels: Bug, help wanted, Area-IDE, IDE-CodeStyle
