### ISSUE TITLE
Make Compilation.Emit with EmitOptions(metadataOnly: true) tolerate errors

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7482] opened 2015-12-15 01:32 UTC
We use `Compilation.Emit` with `EmitOptions(metadataOnly: true)` in the IDE to enable semantic analysis to work across projects and across languages. But currently `Emit` fails unless the program is without errors.

Things would be improved it it were (somewhat) resilient to (some kinds of) errors. How resilient it is and how many different kinds of common errors it is resilient to are quality of implementation issues that can be improved over time.

This issue is to kick off the work, initially in the C# compiler. Part of that work will be creating a mechanism for communicating _error symbols_ through metadata.

**Comment by jcouv** [comment] 2017-08-28 05:17
Closing as duplicate of https://github.com/dotnet/roslyn/issues/20914

**Closed by jcouv** 2017-08-28 05:17 UTC
Labels: Area-Compilers, Concept-Determinism, Feature Request, Language-C#
