### ISSUE TITLE
C# Intellisense Incorrect IDE0019 'use pattern matching' for array element across method call

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25207] opened 2018-03-04 07:53 UTC
Intellisense give an incorrect suggestion for the function `SomeFunc_Original` in the following code. Applying the suggestion results in the code shown in `SomeFunc_Suggested_by_IDE0019`, which is not semantically equivalent to the original because method call `SomeExternal()` might modify the contents of variable `rg`, which may result in the element at index '3' being different between the original array and its replacement.

This is not the same behavior as In the original code, where the element from the original array is preserved by being stored in a local variable prior to the function call.

&lt;code&gt;
|   using System;
|
|   public class B { };
|
|   public class D : B
|   {
|       public static void SomeExternal() { }
|
|       public B[] rg;
|
|       public void SomeFunc_Original()
|       {
|           /// FOLLOWING LINE --&gt; INCORRECT IDE0019 'Use pattern matching' 
|           var k = rg[3] as D;
|
|           SomeExternal();
|
|           if (k != null)
|               Console.WriteLine(&quot;x&quot;);
|       }
|
|       public void SomeFunc_Suggested_by_IDE0019()
|       {
|           SomeExternal();
|
|           if (rg[3] is D k)
|               Console.WriteLine(&quot;x&quot;);
|       }
|   };
&lt;/code&gt;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/206110/c-intellisense-incorrect-ide0019-use-pattern-match.html
VSTS ticketId: 574861_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2023-11-22 20:44
Dupe of https://github.com/dotnet/roslyn/issues/25102

**Closed by CyrusNajmabadi** 2023-11-22 20:44 UTC
Labels: Bug, Area-IDE, Developer Community, Feature - IDE0019
