### ISSUE TITLE
EditorConfig makes changes to my .editorconfig when switching the Code Style tab

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#57743] opened 2021-11-12 21:37 UTC
**Version Used**: 
Version 17.1.0 Preview 2.0 [31910.343.main]

Editors should not modify files unless I make changes.

**Steps to Reproduce**:

1. git clone https://github.com/davkean/audio-switcher
2. git checkout 4f834870cadadc5b90a4ed8d50bc05f1eb0c03f5
2. Open src\AudioSwitcher.sln
3. Navigate to Solution Items\.editorconfig and open it
4. Switch tabs to Code Style

**Expected Behavior**:
Does not modify .editorconfig

**Actual Behavior**:
Modifies .editorconfig adding the following:

![image](https://user-images.githubusercontent.com/1103906/141537416-bfb4a687-7188-4f6e-8e57-db21e839fcfe.png)

**Comment by jmarolf** [comment] 2022-03-18 21:55
duplicate of duplicate of https://github.com/dotnet/roslyn/issues/59325

**Closed by jmarolf** 2022-03-18 21:55 UTC
Labels: Bug, Area-IDE, Investigation Required
