### ISSUE TITLE
IDE0007 conversion method detection heuristic does not take generics into account

### ISSUE THREAD

**Issue by idg10** [dotnet/roslyn#30450] opened 2018-10-11 11:51 UTC
**Version Used**: 
Version 15.8.6

**Steps to Reproduce**:

1. Choose the following settings in an `.editorconfig`:
```
csharp_style_var_for_built_in_types = false:warning
csharp_style_var_when_type_is_apparent = true:warning
csharp_style_var_elsewhere = false:warning
```
2. Write a statement that declares and initializes a variable with a LINQ expression ending in `ToList()` e.g.:
```csharp
public static bool Test(Dictionary<string, int> items)
{
    List<KeyValuePair<string, int>> results = items.Where(x => x.Key != "foo").ToList();
```
3. Give the analyzers time to kick in, and it will recommend that you use `var` with an IDE0007 

**Expected Behavior**:
This should not suggest `var`, because our `.editorconfig` settings say only to use `var` when the type is already apparent from the expression. It is not.

**Actual Behavior**:
It recommend `var`.

The problem here is that `TypeStyleHelper.IsPossibleConversionMethod` contains this code:

```csharp
return methodSymbol.Name.Equals("To" + returnTypeName, StringComparison.Ordinal);
```

and by the time this runs, `returnTypeName` seems to be the simplified type name, even if the actual type is generic. So in this case, the type is `List<KeyValuePair<string, int>>`, but `returnTypeName` has simplified this to just `List`. So this rule sees the `ToList` method call and decides that the type name is apparent. In fact, just part of the type name is apparent.

This is unhelpful because the whole reason we use the editor config settings shown above is to facilitate PR-based code reviews, in which we need to be able to work out what code is doing by looking at it. We don't want to be forced to perform type inference in our heads, which is why we prefer not to use `var` in these scenarios.

While it's true that the use of `ToList` means it's apparent that there's going to be a `List<something>` there, the `something` is *not* apparent, and that's the bit of type inference we don't want to be forced to do in our heads.

Ideally, this whole mechanism would take generics into account properly. E.g., if the expression ended with `ToList<Foo>()`, then I'd be perfectly happy for it to suggest `var` instead of `List<Foo>`. (And by the same token, code such as `IBar bar = serviceProvider.GetRequired<IBar>();` should also get it to recommend `var`.) But in places where the generic type argument is implied, it should be treated as not being apparent.

**Comment by mwadams** [comment] 2018-10-11 12:19
A heuristic which also applied `To`, `As`, `Get` etc.

**Comment by sharwell** [comment] 2018-10-11 13:03
Duplicate of #29657

**Closed by sharwell** 2018-10-11 13:03 UTC

**Comment by sharwell** [comment] 2018-10-11 13:04
@mwadams The specific argument I plan to bring to the design discussion on this is listed in https://github.com/dotnet/roslyn/issues/29657#issuecomment-418465279.
