### ISSUE TITLE
Usage of Activator.CreateInstance won't show in references on the constructor, so there is misleading info!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74774] opened 2024-08-15 13:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Usage-of-ActivatorCreateInstance-wont-/10718602)._

---
\[severity:It’s more difficult to complete my work\]  
Hi there,  
I have found out, that when using Activator.CreateInstance(typeof(T), arguments…) in some generic class of some type T, these usages then won’t be shown as references on the respective constructors, so it is misleading information, someone may to remove that constructor or to think it is not used at all, while it actually is with Activator.CreateInstance…

Could it be possible to add this information to the references shown on the constructors?  
At least in the situations, where I constrain type T to be some interface or class…  
You could like add at least some warning triangle with exclamation mark to all constructors in classes implementing that interface or inheriting that class, that these constructor may actually be used with Activator.CreateInstance.  
Which you of course cannot know, what constructors would be then actually used, so that is probably the reason why it is not there, but still a little warning, that this constructor is maybe used by Activator.CreateInstance would be very helpful.

It would be super awesome improvement, because people use to rely on this information, and Activator.CreateInstance indeed makes this information to be misleading!

Thanks so much, if you decide to implement this, it would be super awesome 😃

---
#### Alison Jin [MSFT] on 8/8/2024, 11:15 PM: 

(private comment, text removed)
#### Peter Hevesi on 8/9/2024, 05:57 AM: 

(private comment, text removed)
#### Feedback Bot on 8/15/2024, 03:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:42
Closing out as by design.  Reflection is it's own space external to the language.  Find references is finding the references the compiler knows about.  At runtime this may be entirely different.  Same as us not finding references when people call SomeType.GetMethod("whatever").

**Closed by CyrusNajmabadi** 2024-11-26 02:42 UTC
Labels: Area-IDE, IDE-Navigation, untriaged, Navigation-FAR
