### ISSUE TITLE
MEF composition failure around AbstractGenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#25427] opened 2018-03-12 19:59 UTC
**Version Used**: 
2.8.0-beta2-62708-11

**Steps to Reproduce**:
VSMac updated to Roslyn 2.8.0-beta2-62708-11 and our MEF composition fails with:

```
MEF catalog scanning errors encountered.
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider". ---> System.InvalidOperationException: No importing constructor found.
   at Microsoft.Verify.Operation(Boolean condition, String message)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass27_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace ---
```

This is because this abstract class shouldn't export itself?
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs,22

**Expected Behavior**:
No errors in VSMEF

**Actual Behavior**:
As above

**Comment by CyrusNajmabadi** [comment] 2018-03-12 20:59
Dupe of https://github.com/dotnet/roslyn/issues/25211 i believe.

**Closed** 2018-03-12 21:32 UTC

**Comment by KirillOsenkov** [comment] 2018-03-12 21:33
Duplicate of #25211
