### ISSUE TITLE
foreach/else

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [dotnet/roslyn#134] opened 2015-01-28 23:28 UTC
The following proposal's value may be really low, nothing revolutionary, but sometimes one may need the code like the following:

    // bar is an IEnumerable<T>
    foreach ( var foo : bar ) {
        Console.WriteLine(foo);
    } else {
        Console.WriteLine("no foos in the bar");
    }

Just a little syntax sugar.

EDIT

Please note that there would be no a straightforward extension method: foreach might contain `break`, `continue` and `return`.

**Comment by Maxwe11** [comment] 2015-01-28 23:53
More obviously

    foreach (var foo in bar)
    {
        empty { Console.WriteLine("no foos in the bar"); }
    }
like in #131

**Comment by lyubomyr-shaydariv** [comment] 2015-01-28 23:55
@Maxwe11 just curious: why put `empty` inside the `foreach` block? Where would you place `Console.WriteLine(foo);` then?

**Comment by Maxwe11** [comment] 2015-01-29 00:02
@lyubomyr-shaydariv `Console.WriteLine(foo);` could be placed anywhere inside `foreach` block.

**Comment by lyubomyr-shaydariv** [comment] 2015-01-29 00:07
@Maxwe11 hmm, it does not really look natural to me. It reminds me something like:

    if ( flag ) {
        else {
            Console.WriteLine("else");
        }
        Console.WriteLine("true");
    }

**Comment by shunsukeaida** [comment] 2015-01-29 00:55
This and #131 make me wish we had an `Each` method, like jQuery (aside of possible perf regression).

```cs
foos.Each( (foo, index) => {  Console.WriteLine(foo); } ).Empty(()=>{ Console.WriteLine("no foo"); });
```

**Comment by khellang** [comment] 2015-01-29 00:59
> This and #131 make me wish we had an Each method, like jQuery (aside of possible perf regression).

That's a quick fix. Just add some extension methods :smile:

**Comment by Maxwe11** [comment] 2015-01-29 01:04
@lyubomyr-shaydariv putting `empty` block inside `foreach` block we emphasize on that it belongs to ~~zero iterations of~~ cycle. Construction `loop { } else { }` looks like someone forgot `if` statement. Also it some dissonance with that two equal branches could be executed differently (first branch repeatedly against second branch once).

**Comment by AdamSpeight2008** [comment] 2015-01-29 01:47
Instead of 'else' what about 'otherwise'?

    foreach( var x in xs )
    {
    }
    otherwise
    {
    }

**Comment by lyubomyr-shaydariv** [comment] 2015-01-29 07:02
@Maxwe11 It shouldn't have a big impact for readability. Suppose the following construction:

    if ( fooCollection.Count != 0 ) { // it's easy for collections
       foreach ( var foo : fooCollection ) { Console.WriteLine("foo"); }
    } else { Console.WriteLine("bar"); }

This covers what you mentioned for the different execution (the `else` has the same semantics). Concerning the `loop/else` I think it just follows the "if/else" and "do/while" style, where the place of `else` is more of a matter of readability/formatting.

**Comment by AdamSpeight2008** [comment] 2015-01-29 13:58
This code doesn't work

       var en = seq.GetEnumerator();
       var o = "";
       if( en.MoveNext() )
       {
           o = en.Current.ToString();
           foreach(var s in en)
           {
               o = o + ", " + s.ToString();
           }
       }
but  should it? Since `en` is an Enumerator. 

An **OnFirst** extension method should return a `Tuple<IEnumerator<T>, R>` so that the enumerator can be "passed on" to the next method. LINQ extension methods have to be implemented on that return Type.

**Comment by RichiCoder1** [comment] 2015-01-29 20:03
Maybe something like:
```csharp
foreach(var item in items)
{
    // Do stuff...
} empty {
    // Do other stuff...
}
```
which we be the same as
```csharp
bool didLoop = false;
var itemsEnumerator = items.GetEnumerator();
while(itemsEnumerator.MoveNext())
{
    var item = items.Current;
    if(!didLoop)
        didLoop = true;
    // Do stuff...
}
if(!didLoop)
{
    // Do other stuff...
}

**Comment by lyubomyr-shaydariv** [comment] 2015-01-29 20:21
Or a little shorter without an auxiliary flag:

	public static void ForeachElse<T>(this IEnumerable<T> enumerable, Action<T> onForeach, Action onElse) {
		var enumerator = enumerable.GetEnumerator();
		if ( enumerator.MoveNext() ) {
			do {
				onForeach(enumerator.Current);
			} while ( enumerator.MoveNext() );
		} else {
			onElse();
		}
	}

**Comment by vlova** [comment] 2015-01-29 21:03
And what if collection is null? There are several ways to handle null collections
1) Fall with exceptions (like now)
2) Threat null as empty collection if 'else' branch is provided
3) Add `empty`, `empty or null`, `null` branches

**Comment by lyubomyr-shaydariv** [comment] 2015-01-29 21:10
Yeah, just fail with NRE.

**Comment by RichiCoder1** [comment] 2015-01-29 21:10
My preference would be for a `NullReferenceException`. That's how `foreach` handles it, and it only makes sense to do the same. Trying to account for null collections would only make the code handling it even harder. 
I'd also be against a `empty` checking for null, if only because that basically boils down to
```csharp
if(items == null) {
    // Do null stuff
}
foreach(var item in items) {
}
```
Making empty be the same is `if(collection != null && collection.MoveNext()/collection.Length != 0)` might easily confuse people too.

**Comment by Richiban** [comment] 2015-02-03 13:09
This would be extremely useful in MVC views.

`@foreach(var item in Model.items)
{
    <p>@item</p>
}
else
{
    <p>There are no items</p>
}
`

**Comment by SachinKainth** [comment] 2015-02-03 13:35
The nicest syntax I've seen here is @AdamSpeight2008's 'otherwise' suggestion.  Only problem is that it is a breaking change.

**Comment by AdamSpeight2008** [comment] 2015-02-04 09:26
@SachinKainth `else` would be a breaking change also since it appears where it wouldn't have appeared before.

**Comment by lyubomyr-shaydariv** [comment] 2015-02-04 09:47
Yes, @AdamSpeight2008 is right. I've just read a discussion on Nemerle `foreach/otherwise` -- they changed the `foreach/else` because it's ambiguous if the `foreach` is nested directly into an `if` having no curly braces.

Also, if I understand [this macro](https://github.com/rsdn/nemerle/blob/master/ncc/testsuite/positive/while-otherwise-macro.n) right, they enhance even `while` to execute code if no iterations were performed within the `while` statement.

**Comment by AdamSpeight2008** [comment] 2015-02-04 10:41
@lyubomyr-shaydariv  The source code of the nemerle macros is available [here](https://github.com/rsdn/nemerle/blob/master/macros/core.n)
**While .. Otherwise** macro
```nemerle
  /** 
  * while .. otherwise macro. 
  * else block is called when while block was not called. 
  */ 
  macro WhileOtherwise(cond, body, otherwiseBody) 
  syntax ("while", "(", cond, ")", body, "otherwise", otherwiseBody) 
  { 
     <[ 
       mutable firstHit = false; 
 
 
       while ($cond) 
       { 
         firstHit = true; 
         $body 
       } 
 
 
       when (!firstHit) 
         $otherwiseBody; 
     ]> 
  } 

```
**While** is also a macro
```
 /** this macro provides convenient way to write a simple while loop, 
     which performs execution of [body] parameter as long as 
     [condition] is true 
 */ 
 macro @while (cond, body) 
 syntax ("while", "(", cond, ")", body) 
 { 
   <[ 
      ($("_N_break" : global) : { 
         def loop () : void 
         { 
           when ($cond) 
           { 
             ($("_N_continue" : global) : { 
               $body 
             }) : void; 
             loop () 
           } 
         } 
  
       loop (); 
       }) : void 
     ]> 
   } 

```

**Comment by gafter** [comment] 2015-08-26 19:10
Closing, as I cannot imagine anyone on the extended design team championing this over other work. @MadsTorgersen please reopen if you disagree.

**Closed by gafter** 2015-08-26 19:10 UTC
Labels: Area-Language Design, Feature Request, Language-C#
