### ISSUE TITLE
Code fix for CS0305 is not helpful

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#2757] opened 2015-05-14 20:24 UTC
Given the following code:

``` C#
using System.Collections.Generic;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            HashSet<> // CS0305 Using the generic type 'HashSet<T>' requires 1 type arguments	
        }
    }
}
```

The light bulb fix for CS0305 above offers to prefix the HashSet<> with "System.Collections.Generic" to turn the code into:

``` C#
using System.Collections.Generic;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Collections.Generic.HashSet<> // CS0305 Using the generic type 'HashSet<T>' requires 1 type arguments	
        }
    }
}
```

Which is not useful and does get us any closer to fixing the actual issue.

**Comment by srivatsn** [comment] 2015-05-15 20:28
Dupe of #81

**Closed by srivatsn** 2015-05-15 20:28 UTC
Labels: Area-Analyzers, Bug

**Comment by davkean** [comment] 2015-05-15 20:35
Actually a dup of #1269.

**Comment by srivatsn** [comment] 2015-05-15 20:42
Ah yes correct.

**Comment by MattGertz** [comment] 2015-05-15 22:16
Verified dupe.
