### ISSUE TITLE
About Single line XML comment of C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44500] opened 2020-05-21 19:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1035288/about-single-line-xml-comment-of-c.html)._

---
In a C# code editor, When I type " /// ", the editor will automatically complete the following code:

```
	/// <summary>
	/// |
	/// </summary>
	public class TestClass
	{

```
This is very good. 
But there are some cases that I just need to write a signle line of comments, So I want to be like this when I enter " /// " after:
```
	/// <summary>|</summary>
	public class TestClass
	{
```
The benefit is that I can **save two lines** of code.

So much,  thank you!

Best regards.

---
#### Visual Studio Feedback System on 5/18/2020, 03:46 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-05-21 19:59
Duplicate of #43710

**Closed by sharwell** 2020-05-21 19:59 UTC
