### ISSUE TITLE
Flaky test - Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.BclMathCall

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52409] opened 2021-04-04 13:32 UTC
someone needs to modify the test to force the interactive host process to crash when this test fails. We already have tools in place to capture that crash dump and attach it to the build

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/issues/51856#issuecomment-810613400_

**Comment by CyrusNajmabadi** [comment] 2021-04-05 17:34
Dupe of https://github.com/dotnet/roslyn/issues/51856

**Comment by CyrusNajmabadi** [comment] 2021-04-05 17:34
Reopening.  Misrtead the issue.

**Comment by CyrusNajmabadi** [comment] 2021-04-05 17:34
also hit here: https://github.com/dotnet/roslyn/pull/52380/checks?check_run_id=2268085554

**Comment by sharwell** [comment] 2021-04-06 15:29
Assigning to @tmat. Heap dumps for the hang are now available in this build:
https://dev.azure.com/dnceng/public/_build/results?buildId=1073818

**Closed** 2021-04-07 18:33 UTC
Labels: Area-IDE, Integration-Test, Investigation Required, Urgency-Now
