### ISSUE TITLE
Memory allocation using method group

### ISSUE THREAD

**Issue by sungam3r** [dotnet/roslyn#39869] opened 2019-11-18 20:35 UTC
I noticed that when using method group, memory is allocated on the heap. It seemed to me that in .NET Framework this did not happen. The delegate instance cached in the static field was used.

After that, I decided to write a test and it turned out that in the case of using a lambda, memory is not allocated. I don’t understand why, when using the static method, the compiler allocates a new instance of `Func` each time. Here is an example reproducing this issue:
```c#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;

namespace ConsoleApp9
{
    class Program
    {
        static void Main() => BenchmarkRunner.Run<Bench>();
    }

    [MemoryDiagnoser]
    public class Bench
    {
        private static Func<int, int> cached = Method;

        [Benchmark]
        public void MethodGroup() => Action(Method);

        [Benchmark]
        public void StaticFunc() => Action(cached);

        [Benchmark]
        public void Lambda() => Action(a => Method(a));

        private void Action(Func<int, int> func) { }

        private static int Method(int i) => 0;
    }
}
```
Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.12.0" />
  </ItemGroup>

</Project>
```

Results:
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.14393.3243 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=3515625 Hz, Resolution=284.4444 ns, Timer=TSC
.NET Core SDK=3.0.100
  [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
  DefaultJob : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT


```
|      Method |      Mean |     Error |    StdDev |    Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |----------:|----------:|----------:|----------:|-------:|------:|------:|----------:|
| MethodGroup | 9.2319 ns | 0.2163 ns | 0.4883 ns | 9.1957 ns | 0.0153 |     - |     - |      64 B |
|  StaticFunc | 0.0060 ns | 0.0117 ns | 0.0164 ns | 0.0000 ns |      - |     - |     - |         - |
|      Lambda | 0.2220 ns | 0.0364 ns | 0.0433 ns | 0.2135 ns |      - |     - |     - |         - |

I ran into this issue when using `ConcurrentDictionary`:
```c#
public class CachingStrategy
{
        private static readonly ConcurrentDictionary<Type, CacheEntry> _cache = new ConcurrentDictionary<Type, CacheEntry>();

        public virtual CacheEntry Cache(object value)
        {
            // allocates Func each call, disasmed line:
            // CacheEntry orAdd = CachingStrategy._cache.GetOrAdd(value.GetType(), new Func<Type, CacheEntry>((object) null, __methodptr(CreateCacheEntry)));
            return _cache.GetOrAdd(value.GetType(), CreateCacheEntry);

            // does not allocate 
            //return _cache.GetOrAdd(value.GetType(), t => CreateCacheEntry(t));
        }
        
        // it is static!
        private static CacheEntry CreateCacheEntry(Type type) => new CacheEntry(type);
}

public class CacheEntry
{
   public CacheEntry(Type type) { }
}
```

This behavior is very confusing, since I always expected that a static method without using closures would never allocate memory being used as method group.

```
> dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Therzok** [comment] 2019-11-18 20:38
https://github.com/dotnet/roslyn/pull/6642

**Comment by Therzok** [comment] 2019-11-18 20:39
Dupe of https://github.com/dotnet/roslyn/issues/5835

**Comment by gafter** [comment] 2019-11-18 20:40
The short answer to your question as to why memory is allocated is that it is required by the language specification.  See the last two bullets of https://github.com/dotnet/csharplang/blob/master/spec/conversions.md (at the very bottom of the file)

**Closed by gafter** 2019-11-18 20:40 UTC

**Comment by benaadams** [comment] 2019-11-18 20:55
Aside; a side effect of using the lambda to do the caching is if an error is thrown inside it shows up a bit weird in the stacktrace. 

However, you can cache to a `readonly static` and then use that variable and it will show up just as the method e.g.

```csharp
private readonly static Func<Type, CacheEntry> s_createCacheEntry 
    = new Func<Type, CacheEntry>(CreateCacheEntry);

private static CacheEntry CreateCacheEntry(Type type) => new CacheEntry(type);

public class CacheEntry
{
    public CacheEntry(Type type) { }
}
```
Then
```csharp
public virtual CacheEntry Cache(object value)
{
    return _cache.GetOrAdd(value.GetType(), s_createCacheEntry);
}
```

**Comment by sungam3r** [comment] 2019-11-19 06:30
> However, you can cache to a readonly static and then use that variable and it will show up just as the method e.g.

I know, it is `StaticFunc` in my example. I wanted to emphasize that such behavior with the creation of a new delegate each call was completely unexpected for me. As if 2 + 2 became 5.

**Comment by benaadams** [comment] 2019-11-19 06:33
I'd agree

**Comment by sungam3r** [comment] 2019-12-03 19:49
@gafter Thanks for pointing this
> The short answer to your question as to why memory is allocated is that it is required by the language specification. See the last two bullets of https://github.com/dotnet/csharplang/blob/master/spec/conversions.md (at the very bottom of the file)

@gafter @benaadams I read section of the specification about method group conversions. Although it describes what is happening, but it does not do it completely. It’s about creating a delegate for the conversion. Good. But for some reason, the specification omits the description of whether it **should be created every time**. I suspect that a concrete implementation might very well be deciding. For example, [this section](https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#evaluation-of-anonymous-function-conversions-to-expression-tree-types) explicitly states that:

>  The precise structure of the expression tree, as well as the exact process for creating it, are **implementation defined**.

Therefore, in this case, I do not understand why the specification is silent about the possibility of **reusing** created delegate, if possible, that is, when the delegate is static and does not use closures. Why should a developer explicitly cache a delegate if the compiler can handle this? Indeed, in the example I have cited, there is **absolutely no sense** in creating a delegate for each call. I am sure that this behavior did not exist before. And now, just recompiling the code is enough to get a performance degradation. Why?

Excuse me if I do not understand something, I have not read #6642 and #5835 yet.

**Comment by sungam3r** [comment] 2019-12-03 20:50
I read #6642, #5835  and a dozen other related issues. I do not even know what to say... This story lasts for many years. Well, okay :(.

**Comment by gafter** [comment] 2019-12-03 22:24
> But for some reason, the specification omits the description of whether it **should be created every time**.

The specification says

> The run-time evaluation of a method group conversion proceeds as follows: ... A new instance of the delegate type `D` is allocated. ...

The delegate creation is required to be evaluated every time it is... evaluated.

Since the program can determine whether or not the specification is obeyed (by saving the result of the conversion to see if a new instance was return by the evaluation of the method group conversion *every time*), the compiler must create a new instance *every time* in order to obey the language specification.

**Comment by sungam3r** [comment] 2019-12-03 22:56
Well, OK. Can you tell me if this behavior has really changed over time? This is the last question that interests me. It can not be that a delegate has always been created before. Thanks.

**Comment by gafter** [comment] 2019-12-04 03:18
As far as I know a delegate has always been created under these circumstances.
