### ISSUE TITLE
Test failure: Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestRefKindRef_FromReference

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#10212] opened 2016-03-30 22:11 UTC
Log [here](http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit64/1045/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences/FindReferencesTests/TestRefKindRef_FromReference/)

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: OrderedEnumerable<String, String> ["Lib: Test1.cs"]\r\nActual: OrderedEnumerable<String, String> []
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.VB$StateMachine_476_TestAsync.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\FindReferences\FindReferencesTests.vb:line 57
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.VB$StateMachine_397_TestRefKindRef_FromReference.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\FindReferences\FindReferencesTests.OrdinaryMethodSymbols.vb:line 2806 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by jasonmalinowski** [comment] 2016-04-01 18:16
Quick analysis: skeleton assemblies built successfully, so it's not a compiler bug (yet.)

**Comment by jasonmalinowski** [comment] 2016-04-13 17:29
@jaredpar, have we seen this fail recently, since you have magic tools to track that? It's quite possible this is a dupe of @dpoeschl's bug...

**Comment by jasonmalinowski** [comment] 2016-04-26 20:37
Closing as a dupe of #10132. That other bug could have caused this, and we haven't seen any failures here since his fix went in.

**Closed by jasonmalinowski** 2016-04-26 20:37 UTC
Labels: Area-IDE, Bug, Test, Urgency-Soon
