### ISSUE TITLE
Incorrect "Cast is redundant" on nullables assigned to dynamic

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#7861] opened 2016-01-08 22:08 UTC
```C#
class Test
{
    public int Value;
}

static void Main(string[] args)
{
    dynamic test = new Test();
    int? nullable = 4;

    test.Value = (int)nullable;
}
```

I get the `(int)` marked as unnecessary cast. The suggested removal results in runtime error.

(Update 1 RTM 24720)

**Comment by gafter** [comment] 2016-01-08 23:21
Hey, IDE team, Is this really a compiler bug?

**Comment by DustinCampbell** [comment] 2016-02-02 20:55
For what it's worth, I can't reproduce this with the latest bits. I believe this was fixed by #6569, which may not have made it into Update 1.

**Comment by DustinCampbell** [comment] 2016-02-02 23:45
Added a regression test for this particular scenario -- #8341

**Comment by DustinCampbell** [comment] 2016-02-02 23:46
Ultimately, this is a dupe of #6490, but thanks very much for filing!

**Closed by DustinCampbell** 2016-02-02 23:46 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
