### ISSUE TITLE
C# Text Editor - Add spacing option for tuples

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35864] opened 2019-05-22 00:00 UTC
VSF_TYPE_MARKDOWNThere is currently no option to set spacing preferences for tuples.
As a result, the automatic formatting will change something like:
( &quot;hello&quot;, &quot;world&quot; )
into:
(&quot;hello&quot;, &quot;world&quot;)
For those who prefer the first, please add &quot;Insert space within element list parentheses (for tuples)&quot;
in Text Editor &gt; C# &gt; Code Style &gt; Formatting &gt; Spacing.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/565361/c-text-editor-add-spacing-option-for-tuples.html
VSTS ticketId: 891843_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/13/2019, 02:11 AM (8 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-05-22 17:56
Duplicate of #10587

**Closed by jinujoseph** 2019-05-22 17:56 UTC
Labels: Area-IDE, Bug, Developer Community, IDE-CodeStyle
