### ISSUE TITLE
Add documentation for IDEXXXX

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65760] opened 2022-12-05 08:52 UTC
<html>
<body>

IDE0200 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0200 | Remove unnecessary lambda expression
-- | -- | --

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by CyrusNajmabadi** [comment] 2022-12-05 17:09
Dupe of https://github.com/dotnet/roslyn/issues/65760

**Closed by CyrusNajmabadi** 2022-12-05 17:09 UTC
Labels: help wanted, Area-IDE, Feature Request, Documentation, untriaged
