### ISSUE TITLE
Compiler crash: base call to state machine method, in state machine method

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#9872] opened 2016-03-18 00:23 UTC
```C#
using System.Collections.Generic;

abstract class A
{
    protected virtual IEnumerable<int> GetChildren()
    {
        return null;
    }
}

class B : A
{
    protected override IEnumerable<int> GetChildren()
    {
        yield return 2;
    }
}

class C : B
{
    protected IEnumerable<int> GetChildren2()
    {
        yield return 1;
        base.GetChildren();
    }
}
```

This crashes the `future` compiler, but not the `master` compiler.  We have yet to determine why they behave differently.

Thanks @zooba for the report and @tmat for the reduced repro!

We also have half a dozen Watson hits for this crash.

**Comment by amcasey** [comment] 2016-03-18 00:23
FYI @ManishJayaswal, this needs a milestone.

**Comment by amcasey** [comment] 2016-03-18 01:23
A quick diff shows some changes to `AwaitExpressionSpiller`, but they look sane.

**Comment by amcasey** [comment] 2016-03-18 01:24
The changes to `SynthesizedMethodBaseSymbol.cs` might be more significant.

**Comment by ManishJayaswal** [comment] 2016-03-18 05:22
@amcasey Is this an EnC issue or compiler issue? Does it only happen during EnC?

**Comment by tmat** [comment] 2016-03-18 06:32
Crashes during compilation.

**Comment by amcasey** [comment] 2016-03-18 16:49
@ManishJayaswal The crash occurs during batch compilation while synthesizing information required for EnC.

**Comment by jaredpar** [comment] 2016-03-18 18:44
@VSadov please investigate this today and ensure we're not at risk for a hidden bug here in update 2.

**Comment by VSadov** [comment] 2016-03-19 00:04
This is a bug specific to future branch it is caused very indirectly by the local function.

**Comment by jaredpar** [comment] 2016-09-13 22:33
Resolving as a dupe of #11649 which is the bug we eventually tracked this issue with.

**Closed by jaredpar** 2016-09-13 22:33 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
