### ISSUE TITLE
Crash while editing Syntax.xml

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#57987] opened 2021-11-25 01:34 UTC
Got this exception:

```
System.NotImplementedException: The method or operation is not implemented.
      at Microsoft.CodeAnalysis.SolutionState.GeneratedFileReplacingCompilationTracker.Fork(SolutionServices solutionServices, ProjectState newProject, CompilationAndGeneratorDriverTranslationAction translate, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionState.ForkProject(ProjectState newProjectState, CompilationAndGeneratorDriverTranslationAction translate, ProjectDependencyGraph newDependencyGraph, ImmutableDictionary`2 newFilePathToDocumentIdsMap, Boolean forkTracker)
      at Microsoft.CodeAnalysis.SolutionState.UpdateAdditionalDocumentState(AdditionalDocumentState newDocument, Boolean textChanged, Boolean recalculateDependentVersions)
      at Microsoft.CodeAnalysis.SolutionState.WithAdditionalDocumentText(DocumentId documentId, SourceText text, PreservationMode mode)
      at Microsoft.CodeAnalysis.Solution.WithAdditionalDocumentText(DocumentId documentId, SourceText text, PreservationMode mode)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentAsync(TextDocument document, DocumentStateChecksums oldDocumentChecksums, DocumentStateChecksums newDocumentChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentsAsync(Project project, ProjectStateChecksums projectChecksums, IEnumerable`1 existingTextDocumentStates, ChecksumCollection oldChecksums, ChecksumCollection newChecksums, Func`3 addDocuments, Func`3 removeDocument)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectAsync(Project project, ProjectStateChecksums oldProjectChecksums, ProjectStateChecksums newProjectChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, HashSet`1 oldChecksums, HashSet`1 newChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, ChecksumCollection oldChecksums, ChecksumCollection newChecksums)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.CreateSolutionAsync(Checksum newSolutionChecksum)
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment] 2021-11-25 06:05
https://github.com/dotnet/roslyn/blob/dac98b924d25aeb2f8ad09b4500e4dec98b8c4fe/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs#L58-L64

The comment suggests this can only happen for source generated files. While `Syntax.xml` is indeed generated, it's just generated by a simple script, `eng/generate-compiler-code.cmd`.

How can it be marked as source generated file? and what feature is trying to operate on it? Most of Roslyn features operate only on C# files.

**Comment by RikkiGibson** [comment] 2021-11-26 20:21
Syntax.xml is not generated, right?

**Comment by CyrusNajmabadi** [comment] 2021-11-26 20:59
It is not. However we generate a lot of files when syntax.xml changes. Presumably that's what is crashinf here

**Comment by jasonmalinowski** [comment] 2021-11-29 19:12
Dupe of #57082.

**Closed by jasonmalinowski** 2021-11-29 19:12 UTC
Labels: Area-IDE, untriaged

**Comment by jasonmalinowski** [comment] 2021-11-29 19:18
And to explain a bit, the required sequence of events here is something along the lines of:

1. Have the generated Syntax.cs file open.
2. Edit the Syntax.xml file.

And get a bit lucky. We're not syncing the state over to OOP correctly and trying to apply the edit from step 2 to a temporary solution forked when the Syntax.cs file was out of sync from the updated state.
