### ISSUE TITLE
Attempting to change severity of an analyzer fails and throws up yellow bar

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39915] opened 2019-11-21 02:52 UTC
**Version Used**: 
Version 16.5.0 Preview 2.0 [29520.138.master

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 8a68d2b7737fbf19d96ba41a53cc1c6617d396c8`
4. `ProjectSystem.sln`
5. Navigate to src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Packaging\ManagedProjectSystemPackage.cs
6. On line 43, drop down Lightbulb
7. Choose: 
![image](https://user-images.githubusercontent.com/1103906/69299990-1ebb2480-0c66-11ea-8845-75291efd74d1.png)

**Expected Behavior**:
.editorconfig to be changed.

**Actual Behavior**:
Yellow bar with the following:

```
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider, String filePath, IVsHierarchy hierarchyOpt, Boolean needsSave, Boolean needsUndoDisabled)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(DocumentId documentId)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId, SourceText newText)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAnalyzerConfigDocumentTextChanged(DocumentId documentId, SourceText newText)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace, IProgressTracker progressTracker, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, ImmutableArray`1 operations, IProgressTracker progressTracker, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, ImmutableArray`1 operations, String title, IProgressTracker progressTracker, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument, IProgressTracker progressTracker, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass20_0.&lt;InvokeCore&gt;b__0()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager, Object extension, Action action)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by davkean** [comment] 2019-11-21 02:52
tag @mavasani

**Comment by mavasani** [comment] 2019-11-21 11:45
@davkean This is a duplicate of https://github.com/dotnet/roslyn/issues/23973. The issue is not specific to any code fix, but an issue with the code fix engine.

**Closed by mavasani** 2019-11-21 11:45 UTC
