### ISSUE TITLE
An unhandled exception of type 'System.TypeLoadException'

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/roslyn#3814] opened 2015-07-02 20:17 UTC
I am running on Windows 7.  

The Solution file contains both C# projects and VB. When I attempt to build a VB project I get the following:

    [Window Title]
    VBCSCompiler.exe
    
    [Main Instruction]
    VBCSCompiler.exe has stopped working
    
    [Content]
    A problem caused the program to stop working correctly. Please close the program.
    
    [Close the program] [Debug the program]

Debuging I see the exception is:

    System.TypeLoadException was unhandled
    Message: An unhandled exception of type 'System.TypeLoadException' occurred in Microsoft.CodeAnalysis.dll
    Additional information: Could not load type 'Microsoft.CodeAnalysis.ArrayBuilder`1' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

After that fails it continues and displays

    [Window Title]
    vbc2.exe
    
    [Main Instruction]
    vbc2.exe has stopped working
    
    [Content]
    A problem caused the program to stop working correctly. Please close the program.
    
    [Close the program] [Debug the program]

And debugging I get the exception:

    System.TypeLoadException was unhandled
    Message: An unhandled exception of type 'System.TypeLoadException' occurred in Microsoft.CodeAnalysis.dll
    Additional information: Could not load type 'Microsoft.CodeAnalysis.ArrayBuilder`1' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

See the version info below:

    Microsoft Visual Studio Enterprise 2015 RC
    Version 14.0.22823.1 D14REL
    Microsoft .NET Framework
    Version 4.6.00057
    
    Installed Version: Enterprise
    
    Architecture and Modeling Tools   00269-30000-00001-AA842
    Microsoft Architecture and Modeling Tools
    
    UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
    
    Visual Basic 2015 RC   00269-30000-00001-AA842
    Microsoft Visual Basic 2015 RC
    
    Visual C# 2015 RC   00269-30000-00001-AA842
    Microsoft Visual C# 2015 RC
    
    Visual C++ 2015 RC   00269-30000-00001-AA842
    Microsoft Visual C++ 2015 RC
    
    Visual F# 2015 RC   00269-30000-00001-AA842
    Microsoft Visual F# 2015 RC
    
    ASP.NET and Web Tools RC   14.0.20417.0
    ASP.NET and Web Tools RC
    
    ASP.NET Web Frameworks and Tools 2013   5.2.30411.0
    For additional information, visit http://www.asp.net/
    
    Common Azure Tools   1.4
    Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
    
    GenerateUnitTest   1.0
    Generates unit test code for methods in classes under test.
    
    GitFlow.VS.Extension   1.0
    Visual Studio extension that integrates GitFlow
    
    GitHub.VisualStudio   1.0
    A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
    
    JustDecompile Tools   1.0
    Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.
    
    JustMock   2015.2.616.2
    Telerik JustMock Extension.
    
    Microsoft Azure Mobile Services Tools   1.4
    Microsoft Azure Mobile Services Tools
    
    Microsoft Code Digger   0.9
    Microsoft Code Digger
    
    Microsoft.Pex.VisualStudio   1.0
    Pex
    
    NuGet Package Manager   3.0.0
    NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
    
    SQL Server Data Tools   14.0.50325.0
    Microsoft SQL Server Data Tools
    
    Telerik ASP.NET MVC VSExtensions   2015.3.622.0
    Telerik UI for ASP.NET MVC VSExtensions
    
    Telerik JustTrace   2015.2.616.3
    Information about my package

**Comment by dzakic** [comment] 2015-10-02 01:37
I have the same problem. 
A VB project builds fine with msbuild.
In VS2013, it builds fine.
In VS2015 I get error MSB6006: "vbc.exe" exited with code -2146232797.
Application Log:
```
Application: vbc.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.ArrayBuilder`1' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1.SavePending()
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1.Scan()
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1.Analyze()
   at Microsoft.CodeAnalysis.VisualBasic.ControlFlowPass.Analyze(FlowAnalysisInfo info, DiagnosticBag diagnostics, Boolean suppressConstantExpressionsSupport)
   at Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisPass.Analyze(VisualBasicCompilation compilation, MethodSymbol method, BoundBlock block, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Analyzer.AnalyzeMethodBody(MethodSymbol method, BoundBlock body, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.BindAndAnalyzeMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, Binder containingTypeBinder, MethodSymbol& referencedConstructor, Boolean& injectDefaultConstructorCall, Binder& methodBodyBinder)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(MethodSymbol method, Int32 methodOrdinal, Int32& withEventPropertyIdDispenser, Int32& delegateRelaxationIdDispenser, Predicate`1 filter, TypeCompilationState compilationState, ProcessedFieldOrPropertyInitializers processedInitializers, Binder containingTypeBinder, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol& referencedConstructor)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol, Predicate`1 filter)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__31-0._Lambda$__0()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.FatalError.Report(System.Exception)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler+_Closure$__31-0._Lambda$__0()
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1[[Microsoft.CodeAnalysis.VisualBasic.ControlFlowPass+LocalState, Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SavePending()
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1[[Microsoft.CodeAnalysis.VisualBasic.ControlFlowPass+LocalState, Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Scan()
   at Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass`1[[Microsoft.CodeAnalysis.VisualBasic.ControlFlowPass+LocalState, Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Analyze()
   at Microsoft.CodeAnalysis.VisualBasic.ControlFlowPass.Analyze(Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisInfo, Microsoft.CodeAnalysis.DiagnosticBag, Boolean)
   at Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisPass.Analyze(Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Microsoft.CodeAnalysis.VisualBasic.BoundBlock, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Analyzer.AnalyzeMethodBody(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Microsoft.CodeAnalysis.VisualBasic.BoundBlock, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.BindAndAnalyzeMethodBody(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.VisualBasic.Binder, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol ByRef, Boolean ByRef, Microsoft.CodeAnalysis.VisualBasic.Binder ByRef)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Int32, Int32 ByRef, Int32 ByRef, System.Predicate`1<Microsoft.CodeAnalysis.VisualBasic.Symbol>, Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState, ProcessedFieldOrPropertyInitializers, Microsoft.CodeAnalysis.VisualBasic.Binder, Microsoft.CodeAnalysis.VisualBasic.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol ByRef)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol, System.Predicate`1<Microsoft.CodeAnalysis.VisualBasic.Symbol>)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler+_Closure$__31-0._Lambda$__0()
   at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by Pilchie** [comment] 2015-10-23 16:42
Moving to compiler based on the stack and where the errors are coming from.

**Comment by VSadov** [comment] 2015-10-28 18:13
I am unable to reproduce this. Either there are additional conditions for the crash or it has been fixed.
Is there a small repro project that can be shared?

**Comment by jaredpar** [comment] 2015-10-29 16:56
This problem should only reproduce if vbc, and csc are located in a directory that doesn't contain their supporting DLLs.

**Comment by jeremysimmons** [comment] 2015-11-18 20:39
@dzakic how did you get the application log for vbc.exe?

**Comment by jaredpar** [comment] 2015-11-30 22:52
This appears to be the result of copying csc, vbc or vbcscompiler into a directory that does not contain their supporting DLLs.  If you can reproduce this with the supporting DLLs in place please let us know.  We'd definitely like to look into that.

**Closed by jaredpar** 2015-11-30 22:52 UTC
Labels: Area-Compilers, Need More Info

**Comment by dzakic** [comment] 2015-12-02 23:44
@jeremysimmons I got the log from Event Viewer.
@jaredpar I have not copied vbc to a new folder. Note msbuild on solution file worked just fine.

Today, I looked into AppCrash_vbc.exe_{guid} folders where Report.wer shows Loaded Modules. It starts with LoadedModule[0]=C:\Program Files (x86)\MSBuild\14.0\bin\vbc.exe, then all usual system dlls, and then Telerik JustMock !

I go to VS JustMock menu, disable profiler, and now compile works! No crash.
What is annoying though, I can no longer reproduce the problem by enabling the Telerik profiler again.

Thanks everyone for looking into this.

**Comment by kfrancis** [comment] 2016-01-06 15:37
@dzakic AHA! That did it for me as well. I submitted a bug report to Telerik, and I'll update my Microsoft bug ticket as well with the new information.

Interestingly enough, enabling it for me (after the initial disable) still causes vbc.exe to fail 100% of the time.

**Comment by kfrancis** [comment] 2016-01-07 14:46
According to Telerik support - this is a known issue, which is now fixed. The fix will be made available with the next official release some time in January.

You can apply the fix locally by editing the following files:

"C:\Program Files (x86)\Telerik\JustMock\Libraries\CodeWeaver\32\ImageBlacklist.cfg"
"C:\Program Files (x86)\Telerik\JustMock\Libraries\CodeWeaver\64\ImageBlacklist.cfg"

Add the following lines to both files:
VBCSCompiler
vbc
csc

Doing so will exclude the given executables from ever being instrumented by JustMock. You should also see a considerable speed-up of compilation.
