### ISSUE TITLE
NetCore Console App - "Fix All Occurrences in Document/Project/Solution" does nothing

### ISSUE THREAD

**Issue by snerks** [dotnet/roslyn#17661] opened 2017-03-09 11:29 UTC
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01055

Windows 7 SP1 - 64 bit.

Installed Version: Community

**Steps to Reproduce**:

Launch VS2017 Community RTW
Select `File/New`
Select `Visual C#/.NET Core/Console App (.NET Core)`
Add a class (e.g. `Another.cs`)

VS2017 creates the file with the content (see below).

Note that none of the `using` statements is required (grayed by editor)

Place the cursor within the `using` statements (Lines 1-3)
Select the "Lightbulb"
Note the availability of `Remove unnecessary usings` option
Select `Fix all occurrences in` `Document`

**Contents of `Another.cs`**
```cs
using System;
using System.Collections.Generic;
using System.Text;

namespace CoreConsoleApp1
{
    class Another
    {
    }
} 
```

**Expected Behavior**:
All `using` statements are removed.

**Actual Behavior**:
No `using` statement is removed.

**Comment by sharwell** [comment] 2017-05-25 06:48
This is believed to be a duplicate of the issue described by @tannergooding in #17183. Thank you for taking time to report it; I made sure to test this case explicitly as part of verifying the fix. 👍

**Closed by sharwell** 2017-05-25 06:48 UTC
Labels: 4 - In Review, Area-IDE, Bug
