### ISSUE TITLE
[.NET Core] Cannot compile when operations on dynamic types are performed

### ISSUE THREAD

**Issue by ppekrol** [dotnet/roslyn#12045] opened 2016-06-16 14:14 UTC
**Version Used**: 1.3.0-beta1-20160429-01

**Steps to Reproduce**:

1. https://github.com/ppekrol/Roslyn.Issue
2. Works on net452
3. Compilation exception on netcoreapp1.0

**Expected Behavior**:
Should work.

**Actual Behavior**:
(10,25): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.BinaryOperation'

I would appreciate any help. Maybe I'm missing something?

**Comment by svick** [comment] 2016-06-17 10:33
This sounds very similar to #10693.

**Comment by jaredpar** [comment] 2016-09-09 21:16
This does appear to be a duplicate of #10693.

The root cause here is that you're not providing the compiler a reference to Microsoft.CSharp.dll.  That DLL holds a lot of members necessary for generating code around `dynamic`.  Adding a reference to this library should fix the error.

**Closed by jaredpar** 2016-09-09 21:16 UTC
Labels: Area-Compilers, Bug, Concept-Portability

**Comment by ppekrol** [comment] 2016-09-09 23:08
Following 4 references are provided in the code:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Private.CoreLib.ni.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Linq.dll
**C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\Microsoft.CSharp.dll**
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Dynamic.Runtime.dll

This line https://github.com/ppekrol/Roslyn.Issue/blob/master/src/Roslyn.Issue/Program.cs#L19 provides required Microsoft.CSharp.dll.

Am I doing it the wrong way? What am I missing?

**Comment by jaredpar** [comment] 2016-09-09 23:23
That code works just fine when compiled against a full copy of Microsoft.CSharp.dll.  I just verified it using a Console app targeting .NET 4.5.2.  

In this case I'm guessing the Microsoft.CSharp.dll from that directory is a slimmed down copy which is missing the necessary members for the compiler. 

CC @VSadov so he can provid emore info

**Comment by tmat** [comment] 2016-09-09 23:26
@jaredpar I think the problem is that the sample is using implementation assemblies and not reference assemblies. I don't think 'Microsoft.CSharp.RuntimeBinder.Binder.BinaryOperation' is actually missing. More likely the compiler is confused for some reason about types from corlib and can't match the BinaryOperation signature to the expected signature.

**Comment by tmat** [comment] 2016-09-09 23:42
Actually, I think it's ```System.Linq.Expressions.dll``` that's missing. BinaryOperation signature as a reference to ```ExpressionType``` which is defined in ```System.Linq.Expressions.dll```

**Comment by ayende** [comment] 2016-09-10 07:10
Yes, I can confirm that the issue is missing this:

            MetadataReference.CreateFromFile(typeof(ExpressionType).GetTypeInfo().Assembly.Location),

However, the error is very misleading, and should probably generate a better error.

**Comment by ppekrol** [comment] 2016-09-10 13:36
@tmat and @ayende 
I've added the System.Linq.Expressions.dll https://github.com/ppekrol/Roslyn.Issue/blob/master/src/Roslyn.Issue/Program.cs#L22

but I'm still getting the same error on .NET Core.

**Comment by ppekrol** [comment] 2016-09-11 09:25
I've found minimal set of DLLs that need to be loaded in order for the code to compile
```
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Private.CoreLib.ni.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\Microsoft.CSharp.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Dynamic.Runtime.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Linq.Expressions.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\mscorlib.dll
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Runtime.dll
```

so the final set of references is (added last 3):
```csharp
MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location),
MetadataReference.CreateFromFile(typeof(RuntimeBinderException).GetTypeInfo().Assembly.Location),
MetadataReference.CreateFromFile(typeof(System.Runtime.CompilerServices.DynamicAttribute).GetTypeInfo().Assembly.Location),
MetadataReference.CreateFromFile(typeof(ExpressionType).GetTypeInfo().Assembly.Location),
MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("mscorlib")).Location),
MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("System.Runtime")).Location)
```

Thanks for all the help.

**Comment by svick** [comment] 2016-09-11 14:57
If anyone is interested, I think I understand now why `mscrolib.dll` and `System.Runtime.dll` are necessary, even though they seemingly don't contain any of the necessary runtime types:

`Microsoft.CSharp` depends on `System.Runtime`, for example, the `BinaryOperation` method mentioned in the error message references `System.Type` from `System.Runtime`.

`System.Runtime` depends on `mscorlib`, specifically, it forwards `System.Type` to `mscorlib`.

And `mscorlib` depends on `System.Private.CoreLib`, specifically it forwards `System.Type` to `System.Private.CoreLib`.

`System.Private.CoreLib` actually contains the implementation of most base types, which is why it's returned from `typeof(object).GetTypeInfo().Assembly.Location`.

---

My conclusion is that Roslyn could be clearer in the error message, but any real improvement would probably have to come from .Net Core.
