### ISSUE TITLE
An expression tree may not contain a tuple literal

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#16995] opened 2017-02-07 18:25 UTC
I've really been looking forward to the day when I can use tuple syntax in expressions and write things like `from model in db.TestModels select (model, model.Name + "x")`. I had sort of assumed it would just work when C# 7 RTMs, but I realized I'd better try it. Right now it results in CS8143 An expression tree may not contain a tuple literal.

The downside to using an anonymous type is that I can't pass it outside the method, which with Entity Framework I invariably need to do. That means a second select into an identical struct and then a second ToList. I thought tuples would be the best of both worlds, saving me from having the two Selects and two ToLists and saving me from having to write a struct duplicating the fields of the anonymous type.
EF Core supports selecting directly to `ValueTuple.Create` which works fine except that I can't provide any field names. But EF core doesn't support selecting directly to a `new CustomStruct`, and even if it did, tuples would be so much less verbose.

I'd like to follow the progress. Is this on a roadmap?

**Comment by jcouv** [comment] 2017-03-17 03:00
Duplicate of https://github.com/dotnet/roslyn/issues/12897

**Comment by jcouv** [comment] 2017-03-23 19:38
I forgot to close this issue as duplicate. Please use #12897 for follow-up.

**Closed** 2017-03-23 19:44 UTC
Labels: Area-Compilers, Feature Request, New Language Feature - Tuples
