### ISSUE TITLE
VB Change Signature when caller does not have trailing () fails

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#48091] opened 2020-09-27 02:53 UTC
**Version Used**: 
Version 16.8.0 Preview 3.1

**Steps to Reproduce**:

1. Create Extension with no additional parameters or only optional parameters, for example
```VB
<Extension>
Friend Function WithTrailingEOL(Of T As SyntaxNode)(node As T, Optional RemoveContinuation As Boolean = True) As T
```
2.  Call function with no () at the end
```VB
Dim X  = stmt.WithConvertedTriviaFrom(node.Body.GetBraces.Item1).WithTrailingEOL
Dim Y  = stmt.WithConvertedTriviaFrom(node.Body.GetBraces.Item1).WithTrailingEOL()
Dim Z  = stmt.WithConvertedTriviaFrom(node.Body.GetBraces.Item1).WithTrailingEOL(RemoveContinuation:=True)
```
3. Select Change Signature on WithTrailingEOL and add a required parameter

**Expected Behavior**:
X, Y and Z will all have the new parameter added
**Actual Behavior**:
Only lines with Y and Z have the new parameter added, line X is unchanged, I have not tried this with non extensions.

**Comment by allisonchou** [comment] 2020-10-13 23:14
Closing as a dupe of #48090.

**Closed by allisonchou** 2020-10-13 23:14 UTC
Labels: Area-IDE, Bug, help wanted
