### ISSUE TITLE
VS crash when removing project from multi project solution

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5972] opened 2015-10-14 21:14 UTC
Repro:
1. Create new VB console application.
2. Add a 2nd new console application to the solution.
3. Remove the 2nd project from the solution.

VS then crashes. 

System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.CodeAnalysis.Workspaces.dll
Additional information: Object reference not set to an instance of an object.

**Comment by Pilchie** [comment] 2015-10-15 01:40
This seems to be caused by recent (internal) changes to prevent serializing TS projects to the CodeLens out of process workspace.

**Comment by balajikris** [comment] 2015-10-15 02:14
Looking..

**Comment by balajikris** [comment] 2015-10-15 16:42
Fixed internally with PR 5513

**Comment by balajikris** [comment] 2015-10-15 16:43
Fix should be in last night's build.

**Closed** 2015-10-15 16:42 UTC
Labels: Area-IDE, Bug, Resolution-Fixed, Tenet-Reliability
