### ISSUE TITLE
Duplication word  when rename property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39326] opened 2019-10-16 19:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/761897/duplication-word-when-rename-property.html)._

---
Note: VS 2019 Community 16.3.1

**Act**
We have two members, for excample:

```
private const string _sidSearchFilter = &quot;(&amp;(objectClass=user)(objectClass=person)(objectGUID={0}))&quot;;
private const string _emailAttribute = &quot;mail&quot;;
```

**Arrange**
Rename them, click &quot;Ctrl+R&quot;

**Assert**
1) For `_sidSearchFilter`, rename preview will be as `_sidSearchFilter` - _**ok**_;
2) For `_emailAttribute`, rename preview will be as `_emailAttributeAttribute` - _**Is it ok?**_;

---
#### Visual Studio Feedback System on 10/7/2019, 01:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 01:57 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2019-10-16 19:07
Confirmed repro in 16.4 preview 2

**Comment by jinujoseph** [comment] 2019-10-30 19:20
Duplicate of #35253

**Comment by jinujoseph** [comment] 2019-10-30 19:20
cc @ryzngard

**Closed by jinujoseph** 2019-10-30 19:20 UTC
Labels: Area-IDE, Bug
