### ISSUE TITLE
ENC tests failed: BreakMode_ModuleDisallowsEditAndContinue and GetDocumentTextChangesAsync

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#39696] opened 2019-11-05 20:46 UTC
Test results here: https://dev.azure.com/dnceng/public/_build/results?buildId=416558&view=ms.vss-test-web.build-test-results-tab&runId=13087564&resultId=131526&paneView=debug

`BreakMode_ModuleDisallowsEditAndContinue`
```
Expected:
[17..19): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[66..67): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[101..101): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[136..137): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*

Actual:
[17..19): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[37..37): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[66..67): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
[72..142): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*
Differences:
    [17..19): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
++> [37..37): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
    [66..67): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
++> [72..142): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
--> [101..101): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*,
--> [136..137): ENC2123: Changes made in project 'Test' will prevent the debug session from continuing: *message*

Expected: True

Actual: False
```

`GetDocumentTextChangesAsync`
```
Expected:
[17..17) '
',
[64..65) '9',
[98..99) '',
[133..133) '0'

Actual:
[17..17) '
',
[35..103) '',
[132..133) '9',
[137..137) ' System.Console.WriteLine();
 System.Console.WriteLine(30);
'
Differences:
 [17..17) '
',
++> [35..103) '',
++> [132..133) '9',
++> [137..137) ' System.Console.WriteLine();
 System.Console.WriteLine(30);
',
--> [64..65) '9',
--> [98..99) '',
--> [133..133) '0'

Expected: True
Actual: False
```

**Comment by tmat** [comment] 2019-11-06 05:09
Both failures have the same root cause. `GetDocumentTextChangesAsync` is a trivial test - it just calls `SyntaxTree.GetChanges`. From the output it seems that this compiler API sometimes returns a different result, which is very odd - I briefly looked at the implementation and don't see any obvious non-determinism. Both the expected and the actual results are valid edit scripts, but it's not clear why we get the "expected" most of the time and "actual" this time around.

@agocke @jcouv  Any ideas?

**Comment by tmat** [comment] 2020-01-28 00:04
I don't see how this test could fail this way. Moving to backlog in case we see it again.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:08
Closing out as this test seems to be gone.

**Closed by CyrusNajmabadi** 2024-10-21 19:08 UTC
Labels: Area-IDE, Test
