### ISSUE TITLE
`using static` statement does not work with C# 12's new `alias any type` feature

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#70805] opened 2023-11-14 19:47 UTC
**Version Used**: 

.NET 8.0.100

**Steps to Reproduce**:
``` csharp
using static string;

string x = Join(',', 1, 2, 3);
```

[sharplab](https://sharplab.io/#v2:CYLg1APgAgDABFAjANgYmBuAsAKF0+ADzgF44ApAewEsA7ACgHIAaFuRZuAJk4GYBKDEA===)

**Diagnostic Id**:

N/A

**Expected Behavior**:

Identical to

``` csharp
using static System.String;

string x = Join(',', 1, 2, 3);
```

**Actual Behavior**:

It cannot parse the syntax.

**Comment by CyrusNajmabadi** [comment] 2023-11-14 20:03
Closing out as by design.  This was not something the specification said should be legal.  See specification here:  https://github.com/dotnet/csharplang/issues/4284

**Closed by CyrusNajmabadi** 2023-11-14 20:03 UTC
Labels: Area-Compilers, untriaged
