### ISSUE TITLE
Automatic refactoring produces wrong code for async partial void

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70063] opened 2023-09-21 21:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-refactoring-produces-wrong-cod/10471338)._

---
Through the suggestions lightbulb in Visual Studio one can automatically refactor a partial void method which contains await expression to become async method via the option "Make method async (stay void)". But that rewrite produces a method with a signature "partial async void" which is incorrect C# code. The async keyword must come before partial keyword as "async partial void", otherwise the code will not compile.

---
#### Feedback Bot on 9/20/2023, 09:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment] 2023-09-24 07:57
Duplicate of https://github.com/dotnet/roslyn/issues/63404

**Closed** 2024-11-23 06:45 UTC
Labels: Area-IDE, IDE-CodeStyle
