### ISSUE TITLE
Visual Studio crashes while analyzing provided code

### ISSUE THREAD

**Issue by SirDuke** [dotnet/roslyn#26195] opened 2018-04-17 12:37 UTC
**Version Used**: 
Microsoft Visual Studio Professional 2017, Version 15.6.6

**Steps to Reproduce**:
Create new solution and copy-paste sample code there:

```C#
using System;
unsafe class Test
{
	public void Method()
	{
		Test obj1 = stackalloc int[2];
	}

	public static implicit operator Test2(int* value)
	{
		return default(Test);
	}
}
```

**Expected Behavior**:
No crasg

**Actual Behavior**:
Visual studio crashes

**Comment by Neme12** [comment] 2018-04-17 12:58
This is a bug in the compiler:
Unexpected value 'StackAllocToPointerType' of type 'Microsoft.CodeAnalysis.CSharp.ConversionKind'

```c#
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.IsEncompassingImplicitConversionKind(ConversionKind kind)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.EncompassingImplicitConversion(BoundExpression aExpr, TypeSymbol a, TypeSymbol b, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ComputeApplicableUserDefinedImplicitConversionSet(BoundExpression sourceExpression, TypeSymbol source, TypeSymbol target, ArrayBuilder`1 d, ArrayBuilder`1 u, HashSet`1& useSiteDiagnostics, Boolean allowAnyTarget)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.AnalyzeImplicitUserDefinedConversions(BoundExpression sourceExpression, TypeSymbol source, TypeSymbol target, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.GetImplicitUserDefinedConversion(BoundExpression sourceExpression, TypeSymbol source, TypeSymbol destination, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ClassifyImplicitConversionFromExpression(BoundExpression sourceExpression, TypeSymbol destination, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ClassifyConversionFromExpression(BoundExpression sourceExpression, TypeSymbol destination, HashSet`1& useSiteDiagnostics, Boolean forCast)
   at Microsoft.CodeAnalysis.CSharp.Binder.GenerateConversionForAssignment(TypeSymbol targetType, BoundExpression expression, DiagnosticBag diagnostics, Boolean isDefaultParameter, Boolean isRefAssignment)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeSymbol declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, CSharpSyntaxNode associatedSyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeSymbol declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, CSharpSyntaxNode associatedSyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, ValueTuple`3& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GenerateCompilationEvents(AnalysisScope analysisScope, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GenerateCompilationEventsAndPopulateEventsCacheAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__57.MoveNext()
```

**Comment by jcouv** [comment] 2018-04-17 14:42
@jaredpar for bar check. Should we consider this issue for 15.7, or is the bar too high already?

**Comment by jaredpar** [comment] 2018-04-17 17:10
@VSadov made late changes to 15.7 which should cover this case. I'm updating my 15.7 installation to verify.

**Comment by alrz** [comment] 2018-04-18 04:35
should we add missing types/symbols to the compiler test plan?

**Comment by jcouv** [comment] 2018-04-18 05:33
@alrz it's already listed. That said, how is the present issue caused by a missing type?

**Comment by jaredpar** [comment] 2018-04-18 15:13
This is still reproducing on 15.7 latest. I don't think this meets the bar at this point given it's a crash on bad code and it is using implicit conversions on a stackalloc which is fairly corner case. Still we should fix this now and have it in our back pocket in case there is a more common case.

**Comment by sharwell** [comment] 2018-04-18 15:54
@jaredpar Can you confirm that this is only a compiler crash; i.e. the IDE stays running but the compiler fails to report a reasonable error?

If this is actually an IDE crash and the fix is simple, I would encourage resolving it.

**Comment by jaredpar** [comment] 2018-04-18 16:01
@sharwell it's an IDE crash. A single report in a corner case (implicit conversion + unsafe + stackalloc) is below our bar at the moment. More severe bugs have been rejected in the past. If the IDE team feels they can get it in under their bar then we are happy to support.

**Closed** 2018-05-09 07:13 UTC
Labels: 4 - In Review, Area-Compilers, Bug
