### ISSUE TITLE
Autocomplete Broken for Properties in .ThenInclude in EF Core 3.1 with Visual Studio 2019

### ISSUE THREAD

**Issue by C26000** [dotnet/roslyn#41527] opened 2020-02-09 23:40 UTC
There is a problem with the autocomplete feature in Visual Studio 2019 and EF Core 3.1: For example I have the following entity clases:

```
class Cliente {
     public List<ContactoCliente> Contactos { get; set; }
}

class ContactoCliente {
   public Contacto Contacto { get; set; }
}

```
Then autocomplete of cc.Contacto fails in the following statement:

`
ctx.Clientes.Include(c => c.Contactos).ThenInclude(cc => cc.Contacto)
`

I have tested it and actually it has a very inconsistent behaviour. The first time you try to type Contacto it doesn't show up. But after the first time that you type it manually and you delete it, it starts appearing in the autocompletion list.

I'm writing this new issue because I was told to do it in this original issue about the same problem that is already closed https://github.com/dotnet/roslyn/issues/8237

**Comment by dpoeschl** [comment] 2020-02-10 18:01
> ...very inconsistent behaviour. The first time you try to type Contacto it doesn't show up. But after the first time that you type it manually and you delete it, it starts appearing in the autocompletion list.

That's extraordinarily unexpected. I don't know what could even cause behavior like that. 

@C26000 I took your code and tried to make a full repro out of it, but I'm not seeing the problem. Do you see the failure with the below code?

```C#
using Microsoft.EntityFrameworkCore; // From NuGet package Microsoft.EntityFrameworkCore (3.1.1)
using System.Collections.Generic;
using System.Linq;

class C
{
    void M()
    {
        IQueryable<Cliente> clients = default;
        clients.Include(c => c.Contactos).ThenInclude(cc => cc.Contacto);
    }
}

class Cliente
{
    public List<ContactoCliente> Contactos { get; set; }
}

class ContactoCliente
{
    public Contacto Contacto { get; set; }
}

public class Contacto
{
}
```

**Comment by C26000** [comment] 2020-02-10 18:19
Yes, I'm still experiencing the problem, I had to change a little your code to avoid C#8 null warnings see the screenshot.

![image](https://user-images.githubusercontent.com/18756972/74177037-e7c23280-4c06-11ea-87fb-3e709e1fdedf.png)

I type dot (.) , then 'cont' and nothing shows up. Then I type 'Contacto' completely, it gets recognized by intellisense with the rectangle around it . I select something else so the autocomplete list disapears, then I delete the last 'o' and now 'Contacto' shows up in the autocomplete:

![image](https://user-images.githubusercontent.com/18756972/74177505-d3326a00-4c07-11ea-9b77-33bc700e0841.png)

**Comment by dpoeschl** [comment] 2020-02-10 19:02
@C26000 Thank you for the details! I can also reproduce this using the latest official build (16.4.4). This is probably the same as [this one](https://github.com/dotnet/roslyn/issues/8237#issuecomment-565601034), which was fixed by @ivanbasov as part of `https://github.com/dotnet/roslyn/pull/39479`, which says it will be available in 16.5 Preview 1.

I've tested in the latest public preview (16.5 Preview 2), and it appears to be fixed there. Feel free to give that preview a try and see if it resolves the issue for you as well.

**Comment by C26000** [comment] 2020-02-10 19:15
Thank you for looking into it. Well, I prefer not to install Preview versions in my machine. The problem itself doesn't bother me too much, I was just trying to help. I'm glad it has been already fixed for future versions.

**Comment by dpoeschl** [comment] 2020-02-10 20:32
Okay, no worries. Thank you for the detailed report! We really appreciate it. Can't wait for it to make it into the official release for you. :)

**Closed** 2020-02-10 20:32 UTC
Labels: Area-IDE

**Comment by DavidRill** [comment] 2020-07-26 22:15
Hello David, I'm sorry to bother you with this, but I'm having a privacy concern about my old username that is affecting me and my family. Since I posted here code that could be tracked to my project in github your replies where you mention my older user name are a problem... Can you please edit out your repplies and remove my older username? It would help me alot to my peace of mind. Thank you and sorry for bothering with this kind of stuff...

**Comment by dpoeschl** [comment] 2020-07-26 22:41
@DavidRill No worries at all, I want to make sure we do whatever's needed. I believe I've removed the old @ references. Does that part look good? Does anything else need altered (e.g. code snippets)?

**Comment by DavidRill** [comment] 2020-07-26 22:43
That was quick! I don't need anything else as long as the old username doesn't show up.

Thank you very much David!
