### ISSUE TITLE
EditorTextFactoryService should handle exceptions better when calling editor's CreateTextBuffer

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#37386] opened 2019-07-19 23:41 UTC
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Workspaces/EditorTextFactoryService.cs,79 calls an editor API to CreateTextBuffer.

This can throw more exceptions than are currently handled, (file access exceptions for files in excess of 3gb, binary characters (new exception), etc.).

Currently this is causing VS to crash when opening Roslyn on VS master as changes were made to throw a FileFormatException when binary characters are encountered.  I've created an issue to track down where these files are and why.
https://github.com/dotnet/roslyn/issues/37385  

Even if these are not valid, we still should probably not be crashing / provide a better error to help diagnose which file has the issue.

**Comment by dibarbet** [comment] 2019-07-19 23:42
cc @dpugh

**Comment by sharwell** [comment] 2019-07-23 17:53
Duplicate of #37363

**Closed by sharwell** 2019-07-23 17:53 UTC
Labels: Area-IDE
