### ISSUE TITLE
Editorconfig suggestions 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37552] opened 2019-07-30 00:35 UTC
Creating new editorconfig by hand is difficult because visual studio suggests properties which are already defined which makes browsing through all of the properties and picking the ones we want unnecessarily difficult. I suggest Visual Studio to not show items which are already defined in .editorconfig file.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/582512/editorconfig-suggestions.html
VSTS ticketId: 899254_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/27/2019, 01:08 AM (63 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment] 2019-07-30 17:55
Duplicate of #37347

**Closed by jinujoseph** 2019-07-30 17:55 UTC
