### ISSUE TITLE
CSharpScript with Single File .NET6 not working

### ISSUE THREAD

**Issue by adirh3** [dotnet/roslyn#57947] opened 2021-11-23 20:25 UTC
**Version Used**: 

Microsoft.CodeAnalysis.CSharp.Scripting version - 4.1.0-1.final

**Steps to Reproduce**:

1. Create new project - 
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.1.0-1.final" />
    </ItemGroup>

</Project>
```

2. Add program.cs -
```
using Microsoft.CodeAnalysis.CSharp.Scripting;

object result = await CSharpScript.EvaluateAsync("return 5;");
Console.WriteLine(result);
```

3. Publish to single file - 
`dotnet publish -c release -r win10-x64 --self-contained=true /p:publishsinglefile=true /p:IncludeNativeLibrariesForSelfExtract=true`

4. Run published executable.

**Expected Behavior**:

`5` is written to console.

**Actual Behavior**:
Program crashes when trying to run the script -
```
Unhandled exception. System.NotSupportedException: Can't create a metadata reference to an assembly without location.
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.Script.GetReferencesForCompilation(CommonMessageProvider messageProvider, DiagnosticBag diagnostics, MetadataReference languageRuntimeReferenceOpt)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScriptCompiler.CreateSubmission(Script script)
   at Microsoft.CodeAnalysis.Scripting.Script.GetCompilation()
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\adirh\RiderProjects\CSharpScriptingPlayground\CSharpScriptingPlayground\Program.cs:line 16
   at Program.<Main>(String[] args)
```

**Comment by svick** [comment] 2021-11-29 12:40
This is a duplicate of https://github.com/dotnet/roslyn/issues/50719.

**Closed by svick** 2021-11-29 12:40 UTC
Labels: Area-Interactive, untriaged
