### ISSUE TITLE
Incorrect operation tree when referencing instance in XML

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50582] opened 2021-01-18 17:43 UTC
See https://github.com/dotnet/roslyn-analyzers/pull/4709

It's likely that operations are not generated *at all* for `XmlEmbeddedExpression`s.

**Comment by mavasani** [comment] 2021-01-19 17:04
Duplicate of https://github.com/dotnet/roslyn/issues/27564

**Closed by mavasani** 2021-01-19 17:04 UTC
Labels: Area-Analyzers, Resolution-Duplicate, untriaged
