### ISSUE TITLE
Enum autocomplete list contains inherited members

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#8007] opened 2016-01-16 19:26 UTC
```C#
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            Test(ConsoleColor.|
        }

        static ConsoleColor ConsoleColor { get; set; }
        static void Test(ConsoleColor color) { }
    }
}
```

The content of autocomplete list after typing the dot differs on whether the `ConsoleColor` property below is defined. If it is, members like `GetUnderlyingType` are present, if not, only the enum values are present in the list (as expected).

**Comment by dpoeschl** [comment] 2016-01-17 03:21
Nice find!

**Comment by asvishnyakov** [comment] 2016-01-17 14:04
No, you're wrong. In you case, you may use ConsoleColor property in Test method call, so ConsoleColor may be both enum and property and autocomplete show you right tip.

**Comment by miloush** [comment] 2016-01-17 14:11
@asvishnyakov That's fine and I even believe the autocomplete list should contain both property and enum (I did not have time to confirm this was the previous behavior). This issue is about what happens after you hit dot. And neither in the case of property nor in the case of enum you should see the static Enum members. (Where 'should' means based on previous behavior and on places where there is not such a property.)

**Comment by asvishnyakov** [comment] 2016-01-17 14:15
@miloush My apologizes. I was wrong in the previous comment.
Excepted behavior is case when members like GetUnderlyingType are present, because both of this samples are valid:
```c#
        static void Main(string[] args)
        {
            ConsoleColor.GetUnderlyingType(typeof(ConsoleColor));
        }

        static void Test(ConsoleColor color) { }
```
```c#
        static void Main(string[] args)
        {
            ConsoleColor.GetUnderlyingType(typeof(ConsoleColor));
        }

        //ConsoleColor ConsoleColor { get; set; }

        static void Test(ConsoleColor color) { }
```

**Comment by asvishnyakov** [comment] 2016-01-17 14:23
All enums internally defined by CLR as Enum class inheritors. When you type `ConsoleColor` in you sample. compiler has two variants: it's property or it's enum. We interest in second variant. Because all enums inherited from Enum class, they all has it's static members like GetUnderlyingType. So autocomplete must show static members in both cases (with property and without) and bug is when static members are not showed when property ConsoleColor is not exists.

**Comment by miloush** [comment] 2016-01-17 14:23
@asvishnyakov I agree that the reason I filed this was the difference. Nevertheless I believe I have never seen Enum members on its instances even when they are technically there, but as I said I don't have VS 2013 now to confirm.

**Comment by asvishnyakov** [comment] 2016-01-17 14:32
@miloush I have. VS 2013 don't show static members of Enum class in enums, but I see this as a bug too.

**Comment by Pilchie** [comment] 2016-01-19 17:15
This looks like a duplicate of #5373

**Closed by Pilchie** 2016-01-19 17:15 UTC
Labels: Area-IDE, Bug
