### ISSUE TITLE
C# simplify intitialiation does not understand that 'default(T)' is equivalent to new 'T()'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32129] opened 2019-01-03 16:55 UTC
For exposition purposes:

```csharp
class T { public int f; }
```

For the following, you get the suggestion to simplify init. That's good.

```csharp
var t = new T();
t.f = 0;
```

For the following (equivalent) code, you do not get that suggestion. That's bad.

```csharp
var t = default(T);
t.f = 0;
```

Please give that latter case some TLC.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/405414/c-simplify-intitialiation-does-not-understand-that.html
VSTS ticketId: 748847_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2019-01-03 17:02
This is by design.  While you can write: 

```c#
var t = new T();
t.f = 0;

// becomes

var t = new T()
{
    f = 0
}
```

It is not the case that you can do anything with `default(T)`.  There is no "shorthand initializer that gives a 'default/null' value for the instance".

**Comment by tamlin-mike** [comment] 2019-01-09 02:18
Perhaps I'm missing something, but provided `default(T)` is equivalent to `new T()`, I'd expect the following transform to be both valid and obvious:
`var t = default(T); t.f = 0;`
=>
`var t = new T { f = 0 };`

**Comment by CyrusNajmabadi** [comment] 2019-01-09 02:30
> Perhaps I'm missing something, but provided default(T) is equivalent to new T()

It is not.  

1. For reference types (which is what your example was) `default(T)` is equivalent to `null`, whereas as `new T()` instantiates an instance of that reference type. 
2. For value types, `default(T)` is equivalent to a zero'ed out instance of the value.  `new T()` is equivalent to calling the constructor of that value-type if it has one, or a zero'd out instance otherwise.

So, when you wrote:

```c#
class T { public int f; }

//... 

var t = default(T);
t.f = 0;
```

That was exactly equivalent to you writing:

```c#
class T { public int f; }

//... 

T t = null;
t.f = 0;
```

It will immediately crash (which you can observe trivially by just trying to run your code sample).

**Comment by tamlin-mike** [comment] 2019-01-09 10:04
> For value types, `default(T)` is equivalent to a zero'ed out instance of the value. new T() is equivalent to calling the constructor of that value-type if it has one, or a zero'd out instance otherwise.

Right. For the case _when_ `default(T)` is equivalent to `new T()`, the transformation is valid.

It's unfortunate the original example used `class`.

**Comment by CyrusNajmabadi** [comment] 2019-01-09 15:08
> Right. For the case when default(T) is equivalent to new T(), the transformation is valid.

Sure.  But it's such a niche case, i never bothered supporting it when writing the 'use object initializer' code-fixer.

Furthermore, at least with `T t = new T(); t.P = 1;` it's a very idiomatic transformation to change that to `T t = new T { P = 1 };`.  That isn't the case with `default(T)`.  If someone writes that, the presumably have some reason they preferred `default` versus `new`.  So offering the fix seems unnecessary and potentially unwanted.

@jinujoseph @vatsalyaagrawal this can be closed as by-design.  Thanks!

**Comment by sharwell** [comment] 2019-01-09 15:11
> @jinujoseph @vatsalyaagrawal this can be closed as by-design. 

The case brought up above is technically valid, so I'll wait for it to come out of a design review before closing it. At that time, it will either be Won't Fix or marked as help wanted. By Design would not be a correct resolution.

**Comment by tannergooding** [comment] 2019-01-09 15:33
> The case brought up above is technically valid

@sharwell, I'm not sure I'd agree. Changing from `new T()` to `default(T)` is not an equivalent transformation. This is because having a `new T()` that initializes to a non-zero value is completely valid at the IL level (and the compiler explicitly calls such a constructor, if it exists, when using `new T()`).

C# currently does not allow creating such a constructor, but it has been proposed multiple times in the past and could conceivably be allowed by the language in the future (at which point, such a transformation would be considered invalid to be offered).

**Comment by sharwell** [comment] 2019-01-09 15:47
@tannergooding Keep the following in mind:

1. If `T` is defined in the same assembly as the `new T()` operation, the refactoring would preserve semantics under the current rules of the C# language. If `T` is defined in a different assembly but also in C#, the same is likely to hold indefinitely under various compatibility policies. This covers the majority of cases where a user could encounter this situation.
1. Refactoring operations in the IDE are not required to preserve exact semantics, so even if exceptions to the previous claim exist now or in the future, it would not necessarily block it.

**Comment by CyrusNajmabadi** [comment] 2019-01-09 15:55
I put this in the "by design" category in that the design is: "take an object-creation and make it into an object-creation-initializer".  We don't have an object-creation here.  Furthermore, while the transformation would be semantics-preserving, that doesn't mean i think it should be something that is actually done.  I want analyers/fixers to make good choices about intent, and in this case, i don't believe there are strong enough signals to indicate that this transformation would be desirable.

**Comment by CyrusNajmabadi** [comment] 2019-01-09 15:58
Put another way: it's long been described in C# that one can initialize structs in several different ways, including forms like:

```c#
MyStruct s;
s.X = 1;
s.Y = 2;
// ...
```

Technically (ignoring a struct with user-provided empty arg constructor), semantics would be preserved converting the above to:

```c#
MyStruct s new MyStruct()
{
  X = 1,
  Y = 2
}
// ...
```

But that doesn't mean i think we should offer that change.  Writing code with certain patterns gives signals about the approach the user is trying to take, and the user (in both these cases) was not writing a call to the constructor followed by assignment statements.  As that is what the 'object initializer form' translates to, i would prefer we stick to finding the equivalent expansion and only converting those.

**Comment by CyrusNajmabadi** [comment] 2020-03-08 20:56
Closing out.  The intent of the feature is to take the clear case of `new + assignments` and use an object-initializer.  The case of just seeing assignments to some zero-inited value was never intended to be in scope for the feature and seems niche enough to not warrant attention.  Closing out as won't-fix.

**Closed by CyrusNajmabadi** 2020-03-08 20:56 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review

**Comment by tamlin-mike** [comment] 2020-03-09 00:39
Since it hasn't been acted upon for fourteen months before closing it was pretty clear this would not be fixed. Just felt like adding a few closing words on this.

>  If someone writes that, the presumably have some reason they preferred `default` versus `new`.

That's one option. Another option is that it was generated code. There are many more options, and only one of them includes intent by the original author.

> But it's such a niche case

Perhaps, but when I encounter it I usually do it en-masse; sometimes hundreds of spread out instances of `blah = default(StructType); blah.field1 = something1; blah.field2 = somethin2;` that needs to be manually modified to `blah = new StructType(); blah.field1 = something1; blah.field2 = somethin2;` for the Roslyn-provided object-initializer refactoring to function. That's both a time-consuming drag and a physical pain-inducer due to RSI.

> The intent of the feature is to take the clear case of new + assignments and use an object-initializer.

Oh, I thought it was to be a helpful refactoring to allow _any_ valid object construction to be converted to/from object-initializer form. My bad.

Perhaps that limitation should be documented? Especially the part that it's an intentional omission could be useful information for both existing and potential future customers/users.

**Comment by CyrusNajmabadi** [comment] 2020-03-09 01:07
> Oh, I thought it was to be a helpful refactoring to allow any valid object construction to be converted to/from object-initializer form. My bad.

In general no.  These come with costs and scenarios to allow hitting the mainline cases, without trying to exhaustively cover any potential case.  

> Perhaps, but when I encounter it I usually do it en-masse

Sure.  It may be super relevant to your use cases.  In that case, i would recommend writing your own roslyn analyzer/fixer for your needs.  

Roslyn-IDE doesn't intend to have all features be exactly what all customers need it to be.  It tries to solve the main cases, while providing customers the tools to fix more niche scenarios themselves if it is worthwhile.
