### ISSUE TITLE
Asked to simplify symbol usage in "var" in foreach incorrectly

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27521] opened 2018-06-06 09:56 UTC
**Version Used**: 

**Steps to Reproduce**:

1. 

``` C#
        static void Main(string[] args)
        {
            string code = "89 414 9'20 135 1911818";

            StringBuilder b = new StringBuilder();

            foreach (char c in code)
            {
                if (char.IsWhiteSpace(c) || c == '\'')
                {
                    b.Append(c);
                }
                else
                {

                }
            }

            Console.WriteLine(b.ToString());
        }
```

![image](https://user-images.githubusercontent.com/1103906/41031319-b014c072-69c3-11e8-9e19-0341e8f8c6f2.png)

**Comment by sharwell** [comment] 2018-06-06 12:32
Duplicate of #26923

**Closed by sharwell** 2018-06-06 12:32 UTC
