### ISSUE TITLE
Not working format for array initialization syntax

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#27217] opened 2018-05-29 07:45 UTC
Affected Branch: [27623.0.d15.7]
Affected Build: 15.7.0 Preview 5.0
Affected Product Language: C#, VB

Steps to reproduce:

1. Create C# or VB application (in my case Console app)
2. Add following code to Main method:

```C#
string[] a = {
                "test",
            "test2",
          "test3",
          "test4",
               "test5"
                                    };
```

```VB
Dim strings As String() = {
                "test",
            "test2",
          "test3",
          "test4",
               "test5"
                                                  }
```

3. Edit -> Advanced -> Format Document

Expected: code formatted 
Actual: code not formatted

[Gif-sharp, gif-vb.]([url](https://microsoft-my.sharepoint.com/:i:/p/v-margko/EcX3u-On8oBCpHt1mot2p98BcZJ7NYHZFYvJ2_zjTC66Gg?e=MI3Pb6))

**Comment by v-rodudi** [comment] 2018-06-08 06:28
Missed links to gifs with repro:
[Gif-sharp](https://microsoft-my.sharepoint.com/personal/v-rodudi_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv-rodudi_microsoft_com%2FDocuments%2FVS-gifs%2Farray-init-formatting-sharp%2Egif&parent=%2Fpersonal%2Fv-rodudi_microsoft_com%2FDocuments%2FVS-gifs&slrid=17046f9e-1092-0000-8a22-35d0518a7243)
[gif-vb](https://microsoft-my.sharepoint.com/personal/v-rodudi_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv-rodudi_microsoft_com%2FDocuments%2FVS-gifs%2Farray-init-formatting-vb%2Egif&parent=%2Fpersonal%2Fv-rodudi_microsoft_com%2FDocuments%2FVS-gifs&slrid=17046f9e-1079-0000-8a22-3d20529c69ab)

**Comment by sharwell** [comment] 2018-06-17 13:45
Duplicate of #779

**Closed by sharwell** 2018-06-17 13:45 UTC
Labels: Area-IDE, Bug
