### ISSUE TITLE
csc.exe crashes with exit code -2146232797

### ISSUE THREAD

**Issue by wldevries** [dotnet/roslyn#21811] opened 2017-08-30 12:45 UTC
**Version Used**: 

Roslyn included in VS 2017 15.3.3

**Steps to Reproduce**:

Compile the following code:
```c#
    class Program
    {
        static void Main(string[] args)
        {
            var history = new Queue<long>();
            Enumerable.Range(0, 5)
                .Select(i =>
                {
                    history.Enqueue(i);
                    return Test(i);

                    bool Test(int v)
                    {
                        history.Dequeue();
                        return Square(v) > 5;
                    }

                    int Square(int w)
                    {
                        return w * w;
                    }
                });
        }
    }
```
**Expected Behavior**:

Since this is valid C# syntax the code should compile

**Actual Behavior**:

csc.exe crashes with exit code -2146232797

**Comment by svick** [comment] 2017-08-30 14:27
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/19033, which is already fixed in master (but the fix is not in VS 15.3).

And indeed, [your code causes the compiler to throw an exception in the released version](https://sharplab.io/#v2:D4AQDABCCMAsDcBYAUOK0B0AZAlgOwEclkUQAmdAdhQG8UIH0A2KWdADgAoYwBtAXQgBDAE4BzAM4BKeozrJGiiADdREABY4JAFwD2IgJ4QAvBDwBTAO4QAigFdzDgDwAbXXjEA+TlOJLGAKJ4dgC25iJCAEYu5hgASkIe5pxgADQQAKwyCv5KGADK5jEAxtqcOCaesrk1ctW1DQyaOvoGGEEEDg7lvvWNtSCUEAAq5jo9xH39uZG6ui4jY2X42irZ043yGxvNeoYYACLmnY7JvTnbjYMQ+Z2iycpSEJ6Zfpe5AL4oU+8QKzd3ETJf6Wda/JRbcE1a7WABUEEsbyhDC+F3eH3OilRHyAA===), but [it works fine on master](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGALAbgFgAodLbAOgBkBLAOwEcjiSUAmcgdhIG8SMB5AGxZc5ABwAKHGgDaAXQwQEAcygBKfoL7FBejADdlGABY1YAewQBPDAF4MdOAHcMARQCucLwB4ANhZ0KgB8kurM+oIAonQeYIgQwH5wFABKEEFwkmgANBgArJq6kfoUAMpwyQDGMJI09sFaJc3aTS3tAmaWNhQxDF5edeFtHS0onBgAKnCwQ8wjoyXAFhZ+UzO19DCGRYsdOnt7XTBW1hQAInD93lnDxYcd4xhl/cpZBuoYwQURDyUAviQFn8MFtnq8EFkwc5diD9Ac4c0nq4AFQYZy/RECQH3P7/O56HH/IA).

**Comment by jcouv** [comment] 2017-08-31 22:57
@agocke to confirm and close. Thanks

**Comment by JiriZidek** [comment] 2017-09-01 14:38
Looks like related to or duplicate of #21543

**Comment by jnm2** [comment] 2017-09-07 13:30
Trying to find my code which is causing -2146232797. So what I'm looking for to get a workaround is something related to local functions and lambdas? I'm positive I'm not putting a local function inside a lambda but the tree of linked issues here seems to cover various issues relating to local functions and lambdas?

**Comment by jnm2** [comment] 2017-09-07 13:30
To bad there's no "Find local functions" feature.

**Comment by jnm2** [comment] 2017-09-07 13:38
Found it! No lambdas around though. Worth getting a repro on sharplab.io so you can see if you've covered it yet?

**Comment by jnm2** [comment] 2017-09-07 13:50
The `try...finally` seems to be essential to the repro.

**Comment by jnm2** [comment] 2017-09-07 13:50
Nope, just the scope.

**Comment by jnm2** [comment] 2017-09-07 13:54
Guessing what will break it is counter-intuitive. :D

**Comment by jnm2** [comment] 2017-09-07 14:00
Yup, [broken](https://sharplab.io/#v2:D4AQTABAwgsAUAb3hFEQBYIFkAUB7AIwCsBTAYwBcIAHAQwCdaBbEik+gSmVSTlX4i8BwiADcGEAHbkSAZ1kMAnhAC8NBs1bsA3NxGoMEAIIAbWXgByM+UpwdVAPggAZPGVomQAVgoBLPJJ2unz6Bpiu7p4+/oH2Kk4A+qrqjCxs9MH6AL56EDlw+UA=) in the current release, [fixed](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMACAwgWAFADe+GJGKALBgLIAUA9sAFZwDGMGADhAhGHPAgCUxUkTykJGMZJkYAbtwwA7VnChRuATwwBeTt179EAbhGzSFDAEEANlDoA5Veq01BugHwYAMnRYQbFABWGABLOiU3U3FzC0pff0CQ8Mj3HS8AfV19Hj4BaPMAXzMMYrwyoA===) in master.

**Comment by jnm2** [comment] 2017-09-07 14:02
So my workaround is to move the local functions out of the scope they're in to the very end of the enclosing method. :+1:

**Closed** 2017-09-15 20:53 UTC
Labels: Area-Compilers
