### ISSUE TITLE
Nested type argument brace completion fails with code on next line

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#284] opened 2015-02-06 19:28 UTC
Ported from TFS WorkItem: <b>1095904</b>

---

<p><b>Repro Steps:</b></p>

<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Copy/paste C#:</P><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">;</SPAN>
<SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Collections</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Generic</SPAN><SPAN style="COLOR: black">;</SPAN>
<SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Linq</SPAN><SPAN style="COLOR: black">;</SPAN>
<SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Threading</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Tasks</SPAN><SPAN style="COLOR: black">;</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">static</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">string</SPAN><SPAN style="COLOR: black">[]</SPAN> <SPAN style="COLOR: black">args</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        $$
        <SPAN style="COLOR: blue">var</SPAN> <SPAN style="COLOR: black">x</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: black">7</SPAN><SPAN style="COLOR: black">;</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>
<P>2. Remove $$ if necessary and type:</P><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: #2b91af">IEnumerable</SPAN><SPAN style="COLOR: black">&lt;</SPAN><SPAN style="COLOR: #2b91af">Tuple</SPAN><SPAN style="COLOR: black">&lt;</SPAN>
</PRE>
<P>&nbsp;</P>

<P><STRONG>Expected</STRONG>: IEnumerable&lt;Tuple&lt;$$&gt;&gt;</P>

<P><STRONG>Actual</STRONG>: IEnumerable&lt;Tuple&lt;$$&gt;</P>

<P>&nbsp;</P>

<P>Note: If the "var x = 7;" is deleted, then the nested brace completion works.</P>

---

<p><b>Revisions:</b></p>

1) Created By David Poeschl (12/12/2014 3:33:15 PM)

---

**Comment by balajikris** [comment] 2015-04-22 01:16
Ah, this is a deep. Let me try to lay out what is going on here.

>Note: If the "var x = 7;" is deleted, then the nested brace completion works.

Note that when we're still typing `Tuple<`, the code is incomplete and we are in a error scenario. 

1. The presence of `var x = 7;` makes the previous line `Tuple<` *parse differently*.
1. Brace Highlighting works completely on the UI thread. For performance reasons, brace completion is mostly syntactic and rarely does semantic analysis.
  * syntactically check if we're in a type argument context, if yes, complete the brace.
  * If not, then we do semantic analysis `SemanticModel::GetSymbolInfo` to determine if we're *possibly* in a type argument
1. In the case where we do not have additional code on the next line, the parse tree is such that the syntactic checks are good enough for us to know that we're in a type argument context and we complete the brace.
1. In the case where there is additional code on the next line, the parse tree is different and we get into the semantic analysis part.
1. We bind the node that represents `Tuple` and check to see if any of the CandidateSymbols are a Generic Type or Generic Method. If so, we complete the brace.
1. We hit another issue here: `GetSymbolInfo` is not sufficient for us, in cases where a symbol matched both generic and non-generic candidates (e.g., `Tuple` matches both generic and non-generic types) but with the given context and parsetree, the compiler would pick the non-generic one as the only candidate symbol, whereas the IDE is hoping for the generic ones to show up.
1. The repro, hence could be simplified to typing `Tuple<`

**Possible solutions**: 

1. *Won't Fix* the bug.

2. If `GetSymbolInfo` didn't help, `LookUpSymbols` at the position of interest and match the ones with the symbol name we're looking for, see if there are any generic types or methods. I have implemented this approach in this [commit](https://github.com/dotnet/roslyn/commit/a29b6dded664ae0cfde8221eddbb21846c2c727f).
  * This is the correct way of doing it.
  * Have to measure perf impact, since this will be invoked if user types a `<` following a Generic type or method that also has a non-generic counterpart and also the source is parsed in a certain manner that forces us to do semantic checks.

3. If `GetSymbolInfo` returned a `TypeSymbol` or `MethodSymbol`, go ahead and complete the brace, since the user **_could not_** be in a valid **_`LessThanComparison`_** operation. For `MethodSymbols` one also needs to check if the `<` is before after the `IdentifierName` or after a method invocation `()`. The former is `TypeArgument` context and the latter is `Comparison` operation.
  * This makes a couple more syntactic checks and avoids the need for the new `LookUpSymbols` call. So, this should be faster.
  * This will change user experience where we would throw in matching parens after a Non-Generic type name or method if the user unintentionally typed the open `<` following the type or method name. However, if the user backspaces to delete the `<`, we'd also delete the matching '>' that we put in.
  * If we didn't constrain the cases tightly, we'd be throwing in matching angled brackets where it wouldn't be expected.

Thanks @dpoeschl for suggesting the 3rd approach. 

Tagging a few people for inputs, to discuss which approach should we adopt here. 
@heejaechang @DustinCampbell @Pilchie @dpoeschl

**Comment by Pilchie** [comment] 2015-04-22 03:04
Note - this issue reproed in VS2013 as well.  Moving out of 1.0 (stable), so that we have more time to consider between options 2 and 3.  Tentatively, I like option 3 best, but would want to be careful to avoid too many false positives (your 3rd bullet).

**Comment by balajikris** [comment] 2015-04-22 03:55
I think VS2013 does not complete braces on generic members at all. I agree that we could do this post RTM, meanwhile just making a sidenote that the nature of the issue is specific to Roslyn.

**Comment by Pilchie** [comment] 2015-04-22 14:54
Oh, duh.  Forgot about that limitation of VS 2013.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 20:23
No repro, i properly get:

![Image](https://github.com/user-attachments/assets/f675139e-3674-49a5-8397-bae0c4d5edce)

**Closed by CyrusNajmabadi** 2024-10-18 20:23 UTC
Labels: Bug, help wanted, Area-IDE
