### ISSUE TITLE
Use Pattern Matching Code Fix produces logically wrong results

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59932] opened 2022-03-03 21:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Use-Pattern-Matching-Code-Fix-produces-l/1679017)._

---
[severity:It's more difficult to complete my work]
For the following line

```
 if (args. Length is not 2 || args. Length is not 3)
```
Visual Studio suggests the use of pattern matching.

The code fix changes the above to

```
if (args. Length is not 2 or not 3)
```
This generates a CS8794 warning (pattern matches all integers)

The fixer should instead give out the following

```
if (args. Length is not (2 or 3))
```

---
#### Feedback Bot on 2/28/2022, 05:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-03-03 21:35
The original code is not logically correct either. It will always match. The compiler can tell this once it moves to pattern matching. Closing as by design (and desirable) behavior.

**Closed by CyrusNajmabadi** 2022-03-03 21:35 UTC
Labels: Area-IDE, untriaged
