### ISSUE TITLE
Visual Studio Navigate to (Ctrl+,) doesn't rank "camel hump" matches highly

### ISSUE THREAD

**Issue by eamodio** [dotnet/roslyn#12042] opened 2016-06-16 02:11 UTC
**Version Used**: 
Visual Studio 2015 Update 3 RC (but this has existed in all version of VS 2015)

**Steps to Reproduce**:

1.  Open Navigate to (Ctrl+,)
2. Type "NTIP" 

**Expected Behavior**:
Matches such as **N**avigate**T**o**I**tem**P**rovider[.cs] should be ranked highly

**Actual Behavior**:
Instead these types of matches seem to come last (or at least very low) in the ranking.

The low ranking of these types of searches seems very counter intuitive especially since they only work if you use all capital letters, which imo reenforces the idea that they should be ranked much higher.

Sadly because of the low rankings my whole team (myself included) didn't even realize that VS supported this type of searching for a very long time (as we have a VERY large project so there are lots of matches) -- I only figured it out as I started out building a VS extension to implement it!

I'm not sure if this is a VS or Roslyn issue, but @davkean asked me to post it here to get it sorted.

Thanks!

**Comment by Pilchie** [comment] 2016-06-30 16:47
Duplicate of https://github.com/dotnet/roslyn/issues/9346.

**Closed by Pilchie** 2016-06-30 16:47 UTC
Labels: Area-IDE
