### ISSUE TITLE
Go to definition in VB source goes to metadata view even though corresponding C# project is part of the same solution

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2450] opened 2015-05-01 23:36 UTC
In Roslyn solution, go to the following line in src\Compilers\VisualBasic\Portable\Symbols\Source\SourceAssemblySymbol.vb
```
If Not AssemblyIdentity.TryParseDisplayName(displayName, identity, parts) Then
```

Go to definition on **AssemblyIdentity** - two partial definitions in source files are found as expected.
Go to definition on **TryParseDisplayName** - goes to metadata view of AssemblyIdentity type, expected to go to definition is source.

**Comment by Pilchie** [comment] 2015-05-01 23:48
Dupe of #599.

**Closed by Pilchie** 2015-05-01 23:48 UTC
Labels: Area-IDE, Bug

**Comment by MattGertz** [comment] 2015-05-15 22:19
Verifying as dupe.
