### ISSUE TITLE
Jenkins failing to build

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14090] opened 2016-09-26 23:00 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4027/

CreatePkgDef : error : ProvideCodeBaseAttribute: Could not load specified assembly: '' reason: Could not load file or assembly 'file:///D:\j\workspace\windows_debug---09a07fba\Binaries\Debug\System.AppContext.dll' or one of its dependencies. The system cannot find the file specified. [D:\j\workspace\windows_debug---09a07fba\src\VisualStudio\Setup\VisualStudioSetup.csproj]
Indication 2

**Comment by jasonmalinowski** [comment] 2016-10-05 17:03
@mattwar Can you get out the targeted fix for this ASAP?

**Comment by natidea** [comment] 2016-10-10 17:36
@mattwar Can we close this issue now?

**Comment by mattwar** [comment] 2016-10-10 19:06
Not certain that this fix alone fixes the problem.  If we don't see this kind of error pop up this week, then I think we can close it.

**Comment by jaredpar** [comment] 2016-10-12 17:20
I've verified this is a dupe of the primary build race condition #13980

**Closed by jaredpar** 2016-10-12 17:20 UTC
Labels: Area-Infrastructure, Urgency-Now
