### ISSUE TITLE
Error message when defining named arguments to an implicitly defined tuple

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#16781] opened 2017-01-26 22:59 UTC
1. Create a VB.Net Console Project.
2. From project options, turn explicit option off.
3. Inside `Sub Main()`, type the following line and press **Enter** afterwards.

```vb.net
x = (first:=1, second:=2)
```

VS **one or more errors occurred** dialog pops up, and the following exception appears in `ActivityLog.xml`:

```
System.AggregateException: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.InvalidCastException: Unable to cast object of type "Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax" to type "Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax".
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNameColonEquals(NameColonEqualsSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NameColonEqualsSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitSimpleArgument(SimpleArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitTupleExpression(TupleExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.VisitExpression(ExpressionSyntax node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitAssignmentStatement(AssignmentStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AssignmentStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitModuleBlock(ModuleBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ModuleBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.VB$StateMachine_4_CleanupAsync.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;IterateAllCodeCleanupProvidersAsync&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;CleanupAsync&gt;d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LineCommit.CommitFormatter.VB$StateMachine_3_CommitRegionAsync.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LineCommit.CommitBufferManager.CommitDirty(Boolean isExplicitFormat, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LineCommit.CommitViewManager._Lambda$__11-0(IWaitContext waitContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Boolean showProgress, Action`1 action)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LineCommit.CommitViewManager.OnLostAggregateFocus(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
---&gt; (Inner Exception #0) System.AggregateException: One or more errors occurred. ---&gt; System.InvalidCastException: Unable to cast object of type "Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax" to type "Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax".
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNameColonEquals(NameColonEqualsSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NameColonEqualsSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitSimpleArgument(SimpleArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitTupleExpression(TupleExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.VisitExpression(ExpressionSyntax node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitAssignmentStatement(AssignmentStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AssignmentStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitModuleBlock(ModuleBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ModuleBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.VB$StateMachine_4_CleanupAsync.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;IterateAllCodeCleanupProvidersAsync&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;CleanupAsync&gt;d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LineCommit.CommitFormatter.VB$StateMachine_3_CommitRegionAsync.MoveNext()
---&gt; (Inner Exception #0) System.InvalidCastException: Unable to cast object of type "Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax" to type "Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax".
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNameColonEquals(NameColonEqualsSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NameColonEqualsSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitSimpleArgument(SimpleArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitTupleExpression(TupleExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.VisitExpression(ExpressionSyntax node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitAssignmentStatement(AssignmentStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AssignmentStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitModuleBlock(ModuleBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ModuleBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.Rewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AddMissingTokensCodeCleanupProvider.AddMissingTokensRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CodeCleanup.Providers.AbstractTokensCodeCleanupProvider.VB$StateMachine_4_CleanupAsync.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;IterateAllCodeCleanupProvidersAsync&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.&lt;CleanupAsync&gt;d__1.MoveNext()&lt;---
&lt;---
```

**Comment by gafter** [comment] 2017-01-28 06:41
I think we should aim to fix this in 2.0 (RTM), as this is a crash in a core scenario of a new feature.

**Comment by jcouv** [comment] 2017-02-01 21:39
@jaredpar Should this be moved out of RTM milestone?

**Comment by VSadov** [comment] 2017-02-03 19:16
This is not a compiler bug. CodeCleanup tries to turn `Alice:=1` into `Alice():=1` , that does not fit into syntax model of `:=` and causes InvalidCast exception

**Comment by Pilchie** [comment] 2017-02-06 20:56
Moving back to compiler - didn't we decide that the core problem here is that the tuple element name binds to a method when the IDE calls `GetSemanticInfo`?

**Comment by OmarTawfik** [comment] 2017-02-09 23:15
@VSadov should this still be in 2.1?

**Comment by VSadov** [comment] 2017-02-14 22:12
Under no conditions `Alice():=1` would fit the syntax model of `NameColonEquals`. 

I do not have other repros, but in theory it does not need to be in a tuple.
Whenever there is a case of `Alice:=1` and `Alice` happens to bind to a method, due to a bug or for a valid reason - this crash will reproduce.

CodeCleanup should not make an invalid syntax transformation conditional on semantics.

**Comment by sharwell** [comment] 2017-05-23 19:15
Removing **Tenet-Reliability** since this doesn't cause an application crash.

**Comment by jinujoseph** [comment] 2018-07-08 07:41
also reported [link](https://developercommunity.visualstudio.com/content/problem/280154/valuetuple-with-tab-crashes-formattting.html)

**Comment by Dorus** [comment] 2018-07-09 14:01
Re: my report:

I find it interesting that i do not get any error and formatting works just fine with most names but not `tab` or `second`.

For example `Dim i = {(rr:=1, tab2:=2)}` (vb.net code) works just fine, but `Dim i = {(rr:=1, tab:=2)}` instantly crashes the formatter.

![afbeelding](https://user-images.githubusercontent.com/4461459/42454622-3f38f6d4-8390-11e8-80c3-c13d36a3c81d.png)

**Comment by Youssef1313** [comment] 2021-03-07 07:44
I cannot reproduce this in 16.10. The only strange behavior I get is that pressing enter moves the caret two lines instead of only one.

@sharwell Should this be closed?

**Comment by CyrusNajmabadi** [comment] 2024-11-05 21:10
Closing out as not repro.

**Closed by CyrusNajmabadi** 2024-11-05 21:10 UTC
Labels: Bug, Area-IDE, Language-VB, New Language Feature - Tuples, Developer Community
