### ISSUE TITLE
Go-to definition doesn't work anymore on project references

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/roslyn#68472] opened 2023-06-07 15:48 UTC
## Environment data
`dotnet --info` output:
```
% dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set
```

VS Code version: 1.78.2 (Universal)
C# Extension version: 2.0.206 (Pre-Release)

## Steps to reproduce

1. Open a project directory
2. Make sure the solution explorer is loaded and you see the solution and its projects
3. Have 2 projects on the solution
4. Add a reference from one project to another (doesn't matter which one)
5. From the project which has the reference try to use a type from the referenced project
6. Press F12 (go to definition)

## Expected  behavior
Since it is a project reference, I was expecting the "old" behavior to persist which is go to the file on the referenced project which defines the type/method. 

## Actual behavior
What is actually happening is that it is opening a read-only tab. Like if it was reading the type metadata from using the assembly explorer. You can see the path on the top pointing to `<referencedProjectPath>/obj/Debug/net7.0/ref/xxx.dll`.

This behavior is ok if we are using a type from a reference assembly or a package reference, but not for project references.

**Comment by CyrusNajmabadi** [comment] 2023-06-07 17:36
@jasonmalinowski @tmeschter  Something broken with vscode with P2P references?  Sounds like we're not makign the switch internally from it being a metadata reference to a project reference.

**Comment by jasonmalinowski** [comment] 2023-06-07 17:40
Sounds like we do have some issue here. One thing to confirm specifically @galvesribeiro:

> You can see the path on the top pointing to <referencedProjectPath>/obj/Debug/net7.0/ref/xxx.dll.

That's a path in _obj_, not _bin_? Also, is this a project that happens to be open source or shareable that we can look at?

**Comment by dibarbet** [comment] 2023-06-07 17:57
More reports here as well - https://github.com/dotnet/vscode-csharp/issues/5711

**Comment by dibarbet** [comment] 2023-06-07 20:24
This also repros opening roslyn in vscode
<img width="1176" alt="image" src="https://github.com/dotnet/roslyn/assets/5749229/fb7b1503-d8eb-4d04-bc69-3751b8dccd08">

I see this in the logs (though possibly not the only issue)
```
[Warn  - 12:02:24 PM] [LanguageServerProjectSystem]Failure while loading c:\Users\dabarbet\source\repos\roslyn\src\Workspaces\Core\Portable\Microsoft.CodeAnalysis.Workspaces.csproj: The "GatherXlf" task could not be loaded from the assembly C:\Users\dabarbet\.nuget\packages\microsoft.dotnet.xlifftasks\1.0.0-beta.23218.1\build\..\tools\net8.0\Microsoft.DotNet.XliffTasks.dll. Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by jasonmalinowski** [comment] 2023-06-08 01:18
Looks like this is fallout from us accidentally loading projects with both project systems (the devkit one, and the one in the C# extension) at the same time. Since duplicate projects meant there were two projects with the same output path, we stopped the P2P reference conversion since something was clearly up.

**Comment by jasonmalinowski** [comment] 2023-06-14 18:33
This is now fixed with version 2.0.212 of the C# extension we shipped earlier today.

**Closed** 2023-06-14 18:32 UTC
Labels: Area-IDE, VSCode

**Comment by galvesribeiro** [comment] 2023-06-14 18:38
Awesome! I can confirm it is working properly now.  Thank you!

**Comment by galvesribeiro** [comment] 2023-06-14 18:46
Alright, not sure it is related @jasonmalinowski but although it got the original problem fixed, now every file I open it spam several errors: 

```
[Error - 3:43:44 PM] Request codeLens/resolve failed.
  Message: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
  Code: -32000 
[object Object]
[Error - 3:43:45 PM] [LanguageServerHost]System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2326
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.IsDiagnosticSuppressed(Diagnostic diagnostic, SuppressMessageInfo& info) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs:line 175
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ApplySourceSuppressions(Diagnostic diagnostic) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs:line 122
   at Microsoft.CodeAnalysis.GeneratorDriver.FilterDiagnostics(Compilation compilation, ImmutableArray`1 generatorDiagnostics, DiagnosticBag driverDiagnostics, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs:line 388
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs:line 312
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisExecutor.CreateCompilationWithAnalyzersAsync(Project project, IdeAnalyzerOptions ideOptions, IEnumerable`1 analyzers, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs:line 137
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.GetOrCreateCompilationWithAnalyzersAsync(Project project, IdeAnalyzerOptions ideOptions, IEnumerable`1 stateSets, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 159
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.CreateAsync(DiagnosticIncrementalAnalyzer owner, TextDocument document, Nullable`1 range, Boolean blockForData, Func`2 addOperationScope, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Func`2 shouldIncludeDiagnostic, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 123
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, ArrayBuilder`1 result, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 30
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.GetDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 50
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.DocumentDiagnosticSource.GetDiagnosticsAsync(IDiagnosticAnalyzerService diagnosticAnalyzerService, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs:line 29
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.ComputeAndReportCurrentDiagnosticsAsync(RequestContext context, IDiagnosticSource diagnosticSource, BufferedProgress`1 progress, String resultId, ClientCapabilities clientCapabilities, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 283
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.HandleRequestAsync(TDiagnosticsParams diagnosticsParams, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 207
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 179
[Error - 3:43:45 PM] Request textDocument/diagnostic failed.
  Message: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
  Code: -32000 
[object Object]
[Error - 3:43:45 PM] Document pull failed for text document file:///Users/guto/dev/repos/orleans/test/Extensions/Google.Tests/Emulators/EmulatorTest.cs
  Message: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
  Code: -32000 
[object Object]
[Error - 3:44:04 PM] [LanguageServerHost]System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2326
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.IsDiagnosticSuppressed(Diagnostic diagnostic, SuppressMessageInfo& info) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs:line 175
   at Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ApplySourceSuppressions(Diagnostic diagnostic) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs:line 122
   at Microsoft.CodeAnalysis.GeneratorDriver.FilterDiagnostics(Compilation compilation, ImmutableArray`1 generatorDiagnostics, DiagnosticBag driverDiagnostics, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs:line 388
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs:line 312
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.SolutionState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 2006
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 998
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 514
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 464
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 421
   at Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Solution/Document.cs:line 314
   at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.FindAsync[T](Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Func`2 onResults, Func`2 onCapped, Int32 searchCap, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs:line 83
   at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.GetReferenceCountAsync(Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Int32 maxSearchResults, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs:line 100
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 179
[Error - 3:44:04 PM] Request codeLens/resolve failed.
  Message: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
  Code: -32000 
[object Object]
```

<img width="528" alt="image" src="https://github.com/dotnet/roslyn/assets/4714040/bd4abc9d-38fe-4bbf-8b0d-6bbcad194ed0">

**Comment by jasonmalinowski** [comment] 2023-06-14 18:54
That one is is being tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1823316 and other places too.

**Comment by galvesribeiro** [comment] 2023-06-15 17:06
@jasonmalinowski I see you made a commit linked to this. Any plan to have a new build?

**Comment by jasonmalinowski** [comment] 2023-06-15 17:12
@galvesribeiro the linked commit is for the fix for the _original_ bug in this conversation which we shipped yesterday. The other one we're tracking in other places.

**Comment by jasonmalinowski** [comment] 2023-06-15 17:13
For example, we think https://github.com/dotnet/roslyn/pull/68635 combines with a few other fixes for the issue you're also reporting.

**Comment by galvesribeiro** [comment] 2023-06-15 17:14
Cool! Looking forward for a new build with it :) It is being extremely annoying the spam of popups :)

**Comment by LeedsCode** [comment] 2023-09-27 21:47
I don't know if it's related or not, but this just started happening in my Visual Studio Community 2022 (not vscode) program.

**Comment by jasonmalinowski** [comment] 2023-09-27 22:51
@LeedsCode What is "this" in this context? Can you file a new bug with a bit more info for us to track from there? This issue got a bit muddled with a few other things and to avoid confusion just starting a new issue would be helpful.

**Comment by LeedsCode** [comment] 2023-09-28 03:40
I have multiple projects in one solution. Project A has a reference to project B. A class method within project A is calling a class method in project B. When clicking on the name of the method and hitting F12 a new tab opens with the decompiled code of project B instead of just going to the file in project B.

**Comment by jasonmalinowski** [comment] 2023-09-28 21:55
@LeedsCode If you're still able to reproduce (or the remove/re-add didn't change your project file in some way), please file a new bug. Feel free to tag me.
