### ISSUE TITLE
character C# intellisence

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51776] opened 2021-03-10 17:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/character-C-intellisence/1338653)._

---
[severity:It bothers me. A fix would be nice]
InteliSence shows an error for:

```csharp
string[] string_list = chunck. Split('🕋');
```

'🕋' is not regarded a character.

---
#### Feedback Bot on 2/14/2021, 06:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2021-03-10 18:29
I believe this should be moved to dotnet/csharplang. `🕋` is part of Unicode 8.0 yet C# only supports Unicode 6.0

**Comment by CyrusNajmabadi** [comment] 2022-11-02 00:04
Closing out as this is currently by design for the language.  If this feature is wanted, it should be a discussion at dotnet/csharplang.

**Closed by CyrusNajmabadi** 2022-11-02 00:04 UTC
Labels: Area-Compilers, Developer Community
