### ISSUE TITLE
Language Service / Intellisense never recycles/reloads CodeGenerators

### ISSUE THREAD

**Issue by hopperpl** [dotnet/roslyn#71771] opened 2024-01-23 12:08 UTC
**Version Used**: 

Version 17.9.0 Preview 3.0

**Steps to Reproduce**:

When you have a project that uses code generators (within the solution), and the code generator from the solution is being updated, then LSP never reloads the code generator assembly and continues to use the outdated version. 

This generates so much noise about "type not found" and "compile errors" and all that from Intellisense, which is simply just outdated artifacts. Otherwise all works fine with updated code generators, except LSP which needs to recycle/restart. Or display a message that analyzers, code generates are out of date and LSP needs a restart. Anything except flooding everything with bogus error messages.

**Expected Behavior**:
LSP notices updates analyzers/code generators

**Actual Behavior**:
LSP uses outdated assemblies and generates a lot of noise with thousands of errors that flood all editors

-----

I don't know exactly how you load analyzer assemblies, but it seems to have something to do with "%Temp%\VS\AnalyzerAssemblyLoader" and their assemblies as here I found my code gen assembly. Interestingly, `devenv.exe` has the latest version loaded, while `RoslynCodeAnalysisService.exe` has not.

**Comment by weltkante** [comment] 2024-01-23 16:48
Probably duplicate of #48083, had a long discussion there and result was its expected behavior, you are supposed to write your generators against unit tests not interactively in VS. Several workarounds exist and are mentioned in the other issue but you're currently on your own figuring out what works best for you if you don't follow the guidance.

**Comment by CyrusNajmabadi** [comment] 2024-01-23 18:16
Yup.  Closing as dupe.  Note: We are interested in making this better.  But it's a challenging problem.  Hopefully we'll have something this year though.

**Closed by CyrusNajmabadi** 2024-01-23 18:16 UTC
Labels: Area-IDE, untriaged
