### ISSUE TITLE
CS1998 proposed fix "Make method synchronous" should not be offered for overrides and interface implementations

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#65535] opened 2022-11-21 14:17 UTC
**Version Used**: VS 17.4.1 (VisualStudio.17.Release/17.4.1+33110.190 ; C# Tools 4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c)

**Steps to Reproduce**:

1. Write the following code:

```csharp
using System.Threading.Tasks;

abstract class C
{
    public abstract Task M();
}

class D : C
{
    public override async Task M()
    {
    }
}
```

2. Open the lightbulb menu for the CS1998 ("the async method lacks await operators") warning

(Note: this also repros with a non-abstract `C` and a `virtual` `M`, or with `C` being an `interface`)

**Diagnostic Id**: CS1998

**Expected Behavior**: The proposed fixes should only contain actions that are reasonable in context

**Actual Behavior**: The proposed fixes contain "Make method synchronous", which changes `D.M` to `public override void M()` but does not change `C.M` (and in the general case, cannot), leading to a compile error.

**Comment by sdelarosbil** [comment] 2024-02-19 14:48
Hey, can I take this?

I think not offering it for all the cases outlined here seems reasonable.

**Comment by CyrusNajmabadi** [comment] 2024-02-19 15:53
No.  We have open design questions about this. As an example, I ended up still using this as part of a series of refactorings I was making to some code I was writing. 

Often it is better to still allow the user to do something, versus disabling it and making them confused why something is missing.

**Comment by CyrusNajmabadi** [comment] 2024-11-22 19:34
Closing out as workign as intended.  Blocking fixes is problematic as users often want to perform a series of edits.  Here, those edits are fine to just that method, and the user can make further edits past that.

**Closed by CyrusNajmabadi** 2024-11-22 19:34 UTC
Labels: Bug, help wanted, Area-IDE, good first issue
