### ISSUE TITLE
Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.TypeSubstitutedLocalSymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedLocal'

### ISSUE THREAD

**Issue by ghisguth** [dotnet/roslyn#5814] opened 2015-10-09 01:40 UTC
C# Compiler crashes when trying to compile following code:

```c#
public Task<T> GetAsync<T>(Func<Task<T>> asyncFunc, string action, object key)
   where T : class
{

    Func<Task<CacheWrapper<T>>> wrapperFunc = async () =>
        {
            return new CacheWrapper<T> { Instance = await asyncFunc() };
        };

    return null;
}

private class CacheWrapper<T>
{
    public T Instance
    {
        get;
        set;
    }
}
```

Can reproduce the bug in VS 2015. The code can be compiled in VS 2013.

Compiler version: Microsoft (R) Visual C# Compiler version 1.0.0.50618

VS reports following error:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code -2146232797.

When I run csc.exe from command line, I can attach debugger and see exception like this: 

An unhandled exception of type 'System.InvalidCastException' occurred in Microsoft.CodeAnalysis.dll
Additional information: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.TypeSubstitutedLocalSymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedLocal'.

The workaround is very simple:

```C#
Func<Task<CacheWrapper<T>>> wrapperFunc = async () =>
    {
        var instance = await asyncFunc();
        return new CacheWrapper<T> { Instance = instance };
    };
```

**Comment by jaredpar** [comment] 2015-10-09 08:19
Thanks for taking the time to file this bug.  This appears to be a duplicate of #4697.  This bug has been fixed and will appear in VS 2015 Update 1.

**Closed by jaredpar** 2015-10-09 08:19 UTC
Labels: Area-Compilers
