### ISSUE TITLE
Unexpected "Break Mode" dialog after performing two or more EnC operations in VB UWP App

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#2582] opened 2015-05-07 18:08 UTC
1.  Create a new VB Windows Universal (Blank App)
2.  Set a breakpoint in App.OnLaunched:
![capture1](https://cloud.githubusercontent.com/assets/6464209/7522247/cfa5dea0-f4a8-11e4-9cc0-82d205780005.PNG)
3.  F5
4.  When breakpoint is hit, insert ```Dim x = { 1, 2, 3 }``` on the line above the breakpoint
5.  Drag IP to line you just added
6.  Insert new line after current line
7.  F10

**RESULTS**
![capture2](https://cloud.githubusercontent.com/assets/6464209/7522331/5be950ea-f4a9-11e4-8c0f-9d7fc7dac1f7.PNG)

**Comment by wschae** [comment] 2015-05-07 18:51
Adding another repro step:
1. Create WPF app.
2. Run.
3. Break All.

**Comment by tmat** [comment] 2015-05-19 20:27
@wschae I can't repro with WPF app on the latest dogfood build.

**Comment by wschae** [comment] 2015-05-19 21:39
I still could see the dialog:

  
![1](https://cloud.githubusercontent.com/assets/4300700/7714607/c2bc85f0-fe34-11e4-854b-26ab8a7493d0.png)


However, in this case, the explanation saying “all threads were executing external code (system or framework code)” seems fine. What about Kevin’s repro step?

**Comment by tmat** [comment] 2015-06-06 02:04
I have verified that Roslyn produces the expected IL, metadata and PDB (at least to my knowledge). Seems like the problem is in the runtime or the debugger. Tracked internally as 1184236.

**Comment by ManishJayaswal** [comment] 2015-06-10 19:55
Internal bug has been fixed so resolving and closing this issue.

**Closed by ManishJayaswal** 2015-06-10 19:55 UTC
Labels: Area-Interactive, Bug, Interactive-EnC, Resolution-External, Verification Not Required

**Comment by ManishJayaswal** [comment] 2015-06-10 19:58
@tmat @wschae FYI. Please verify.

**Comment by wschae** [comment] 2015-06-16 20:21
I also verified this fix. No dialog pops up for the original repro step (i.e., VB UWP App).
