### ISSUE TITLE
Solution containing F# and C# projects break some C# tooling, even if projects are not referencing each other

### ISSUE THREAD

**Issue by TIHan** [dotnet/roslyn#28474] opened 2018-07-11 23:57 UTC
**Version Used**: 15.6, 15.7.4, 15.8 preview 4

**Steps to Reproduce**:

1. Create new solution
2. Create a C# project and a F# project
3. Try to perform a rename operation in C# and watch it not work

**Expected Behavior**:

Rename should properly rename when pressing Enter.

**Actual Behavior**:

Nothing happens when pressing Enter on rename.

--

This isn't specific to rename, there are other issues when trying to do F12 navigation.
This is directly related to this: https://github.com/Microsoft/visualfsharp/issues/4796#issuecomment-404344061

Quoting from the issue here:
> After investigation in the case of using rename for a type in C#, Roslyn will iterate over all projects to try to find that type. When it hits a F# project, it will throw because it is trying to get a ISyntaxFactsService from our language service which we don't have and never will. https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_ProjectIndex.cs#L55

> When that throws, it will cancel C#'s rename task and nothing works.

> I don't think this is a regression, or at least a very recent one. Most of the code paths to get to this point haven't changed from 11 months to 2 years.

> This also occurs even if the C# project isn't referenced or is referencing a F# project.

**Comment by dgchurchill** [comment] 2018-07-13 04:38
Seems like this could have been introduced in the following commit:

https://github.com/dotnet/roslyn/commit/95a2444883741b61d44385d9bb7040ba33778ca3#diff-cae35fdca4a58c14603b4de0661109bbR606

and the previous default behaviour was to ignore case:

https://github.com/dotnet/roslyn/commit/95a2444883741b61d44385d9bb7040ba33778ca3#diff-cae35fdca4a58c14603b4de0661109bbL729

**Comment by jasonmalinowski** [comment] 2018-07-16 23:57
Indeed, that path does look bad. My attempts to reproduce this internally are currently being thrwarted by a worse bug that means creating a C# project prevents F# projects from being loaded.

**Comment by davidagross** [comment] 2018-08-16 18:39
Fixed by #28789 (tracing back to [Rename refactor crashes](https://developercommunity.visualstudio.com/content/problem/222498/rename-refactor-crashes.html))

**Comment by rlreis90** [comment] 2018-08-17 10:46
Is this in 15.8.0? I'm still observing the issues.

- Activating Refactor Rename on a symbol does nothing.
- Ctrl+F12 Go To Implementation also doesn't work.

On the upside, activating the commands hasn't crashed Visual Studio...

I can confirm that unloading the F# project from the solution fixes the problem. So it looks to be the same root issue.

**Comment by jasonmalinowski** [comment] 2018-08-17 17:26
@rlreis90 Which exact version are you running from Help > About? We did fix some of these, but there was also another bug we fixed which has the symptoms you're describing.

It's also possible there's still more bugs here, which wouldn't surprise me.

**Comment by davidagross** [comment] 2018-08-18 09:56
Ach, I just ran into a Ctrl+R, Ctrl+R rename that hangs (it's search doesn't complete) but executes just fine after unloading the F# project in the mixed solution.  I wonder why it was different from the other renames that worked...

**Comment by rlreis90** [comment] 2018-08-19 00:34
@jasonmalinowski I'm running 15.8.1 atm, same status.

I did get the same "This may be caused by an extension" popup as @davidagross.

Rename hasn't made the UI hang for me so far (it had previously), but it simply does nothing; it doesn't highlight the text in green, nothing.

**Comment by davidagross** [comment] 2018-08-19 04:53
@rlreis90, words mean things and I should have been precise: VS doesn't hang but the search window in Ctrl+R, Ctrl+R doesn't find any of the instances, as if it's search process hangs, though VS is otherwise still responsive.

**Comment by JanWosnitza** [comment] 2018-08-20 08:28
@davidagross renaming local variables or private members always worked, just public renaming had/has issues.

@rlreis90 it crashed only if you try to rename a public member which is used by the F# binary.

**Comment by epsen** [comment] 2018-08-21 11:16
I have had the same problems mentioned is this issue with the latest versions of Visual Studio. My solution contains both C# and F# projects, and Rename and "Find all references" are not working. I have rolled my Visual Studio back to version 15.4.5, which is the latest version of VS that does not have these problems. So I guess the issue has been introduced with the release of version 15.5.

**Comment by rlreis90** [comment] 2018-09-20 20:07
Just updated to latest version and now some symbols aren't even loading anymore (editor time). F12 doesn't work on them & Error List marks them as errors.

**Comment by jasonmalinowski** [comment] 2018-11-26 19:10
@TIHan Are we still getting reports of issues like this?

**Comment by epsen** [comment] 2018-11-27 09:03
@jasonmalinowski, I have just testet my Solution in Visual Studio 2017 15.9.2, and it is still the same problem: My solution contains both C# and F# projects, and Rename and "Find all references" on public members are not working. I have rolled my Visual Studio back to version 15.4.5, which is the latest version of VS that does not have these problems. So I guess the issue has been introduced with the release of version 15.5.

**Comment by CyrusNajmabadi** [comment] 2018-12-04 18:35
@JanWosnitza Can you clarify whwat you mean by 'broken' here?  Thanks!

**Comment by JanWosnitza** [comment] 2018-12-05 11:06
Hi @CyrusNajmabadi, with broken I mean the following:

### Rename
rename a public property/event/function using Visual Studio's refactoring tools. It starts the renaming process, I can change the name and when I hit RETURN to accept the new name it's not renaming.
![Rename](https://media.giphy.com/media/3LdVU4nVYeAN1xbbtm/giphy.gif)

### Find All References
_Find All References_ opens the Find All References window but does not show any references except the one where you started the search for and the progress-bar never finishes.
![Find All References](https://media.giphy.com/media/5h3EOJegOw5KuFRGDL/giphy.gif)

### Repoduction
I also noticed, that indeed it works now when the project is not referenced by any F# project, thus I tried to reproduce the bug in a small solution:

1. Create a C# library project
2. Create an F# console project
3. add C# library to references of F# console
4. Rename or find references

You can download my test solution here: [Test.zip](https://drive.google.com/file/d/14M2vMvP6IVeJXnLuQGeQwDXW0sxoYzxY/view?usp=sharing)

**Comment by JanWosnitza** [comment] 2018-12-18 09:40
If you can't reproduce or require more information, don't hesitate to ask :)

**Comment by petarrepac** [comment] 2018-12-20 16:39
Open mixed solution in VS 15.9.4
Rebuild All succeeds 
Position cursor on interface name in .cs file (single implementation is in some .fs file)
Right click - Go to Implementation 

An exception has been encountered. This may be caused by an extension.
You can get more information by examining the file '.....\ActivityLog.xml'.

**Comment by JanWosnitza** [comment] 2018-12-24 11:14
I started VS with `devenv /Log`, but in the `ActivityLog.xml` file are no errors reported.

**Comment by JanWosnitza** [comment] 2019-06-17 15:48
Is this issue still alive? I'm waiting for the bugfix for one and a half year now. 😀

**Comment by Droni** [comment] 2019-06-17 15:57
you are lucky. We are waiting for fix more than 2 years. Looks like F# is no longer evolving ...

**Comment by veloek** [comment] 2019-09-24 08:20
@jasonmalinowski, I see this getting pushed again and again. Is it too big of a task or is it just not important enough? It sure is a big pain for my team and probably many others. Really looking forward to see this resolved! 🙂

**Comment by CyrusNajmabadi** [comment] 2019-09-24 18:34
> I see this getting pushed again and again. Is it too big of a task or is it just not important enough

Can you clarify.  Is the issue that there are legitimate bugs where the product just breaks when you try to do things?  i.e. you try to do a rename, and simply *nothing* happens (probably because something crashed internally), as opposed to just C# or just F# performing the rename.

Or is the issue that there are feature requests for C# and F# to work better?  For example, that you'd like to be able to more easily jump between languages, or have a rename in one language reflected in the other.

I'm a bit lost as to what the current state is here.  Thanks!

Note: if hte issue is that things are broken, it's likely the case that F# should drive investigations into finding out what's up there and pushing for the relevant fixes.  If the issue is better feature support between the languages, that is certainly being looked into (for example: https://github.com/dotnet/roslyn/pull/33723) but it is a large and complex space, and Roslyn is a project with thousands of issues and hundreds of PRs for the team to get through.  If you'd like to help contribute time/PRs here, that would likely be super helpful.

**Comment by veloek** [comment] 2019-09-24 18:53
@CyrusNajmabadi, the IDE is throwing an exception when I'm trying to jump to implementation (ctrl+f12) in a mixed C#/F# solution. I don't have the stack trace/log file in front of me, but I can provide it tomorrow if that would help solve the issue.

It's not a feature request, but an annoying bug that has been around for years now. I was excited when I first search around for this bug and noticed it was assigned to a milestone, but seeing how it's just pushed forward, I've almost lost hope.

Let me know if I can be of further assistance. I don't think I would have the spear time to dig deep enough into this issue to solve it and make a PR myself, so I'm hoping I can somehow bump it up the list of prioritized tasks.

**Comment by CyrusNajmabadi** [comment] 2019-09-24 18:57
> @CyrusNajmabadi, the IDE is throwing an exception when I'm trying to jump to implementation (ctrl+f12) in a mixed C#/F# solution. I don't have the stack trace/log file in front of me, but I can provide it tomorrow if that would help solve the issue.

Would definitely be helpful.  Note: the original post says this:

> After investigation in the case of using rename for a type in C#, Roslyn will iterate over all projects to try to find that type. When it hits a F# project, it will throw because it is trying to get a ISyntaxFactsService from our language service which we don't have and never will. 

People def seem to care deeply about this.  My recommendation would be to just open a PR that fixes this.

**Comment by CyrusNajmabadi** [comment] 2019-09-25 00:15
I spent a while today trying to repro an issue.  I couldn't run into any crashes, or anything that indicated that thins were not working.  If someone can give me a repro case, i'm happy to try investigating further.

Thanks!

**Comment by CyrusNajmabadi** [comment] 2019-09-25 00:47
I have a fix for the rename crash.

**Comment by Droni** [comment] 2019-09-25 07:05
@CyrusNajmabadi 
it looks strange. I have reported the issue with the steps to reproduce: 
[VS Community](https://developercommunity.visualstudio.com/content/problem/464811/find-all-references-is-broken-on-mixed-f-and-c-sol.html)
[GitHub](https://github.com/dotnet/roslyn/issues/33627)

But my issue has marked as duplicated. Now we see that this issue maked as fixed, but my the initial problem still reproducible. Looks like the nature of the problem was not researched by the man which mark issues as duplicate.

**Comment by veloek** [comment] 2019-09-25 07:27
@CyrusNajmabadi, the stack trace I'm seeing is the same as in @davidagross's [comment](#issuecomment-414044734). There's a nullref exception being thrown somewhere. I'm working on putting together a minimal solution that can be used to reproduce the issue.

**Comment by JanWosnitza** [comment] 2019-09-26 09:15
@CyrusNajmabadi, there is a zip attached to https://github.com/dotnet/roslyn/issues/28474#issuecomment-444447681 with a VS solution already setup and follow the repro steps at that same comment and you will see that e.g. renaming doesn't work.

**Comment by CyrusNajmabadi** [comment] 2019-09-26 16:12
@veloek @JanWosnitza Yes.  I opened a fix for this a couple of days ago: https://github.com/dotnet/roslyn/pull/38841

Cheers!

**Comment by JanWosnitza** [comment] 2019-09-27 08:55
🎈 Is this real life? 🎉 #MadeMyYear 👌
(even if it might be too early:) Thanks a lot!

**Comment by jasonmalinowski** [comment] 2019-10-03 19:31
Fix is merged, and should be in 16.4 Preview *3*.

**Closed** 2019-10-03 19:30 UTC
Labels: Area-IDE, Bug

**Comment by jasonmalinowski** [comment] 2019-10-03 19:39
And @veloek my apologies for punting the bug a few times from one release to the next. This bug was on my plate as the "we should get to it" and the invariably some last minute things always resulted in it getting punted. Asking about it was absolutely 100% the right thing to do since "customers are complaining" is always the easiest way to prioritize something higher!

**Comment by veloek** [comment] 2019-10-03 20:00
@jasonmalinowski, yeah I was hoping a friendly nudge would bump it up the list of prioritized tasks :slightly_smiling_face:

**Comment by veloek** [comment] 2019-11-05 10:26
VS 16.4 Preview 3 is out and I can confirm that "go to implementation" now works! A day of celebration! 🎉

**Comment by Droni** [comment] 2019-11-05 10:41
Hmm.... It is interesting solution. Now the project reference to F# project looks like a reference to assembly. As result you can not rename members which are using in both projects.
Find all references feature show code from the F# project as metadata. Good work! It looks like F# buried by Microsoft.

**Comment by CyrusNajmabadi** [comment] 2019-11-05 19:49
@Droni can you file a new issue about this.  Thanks!

**Comment by Droni** [comment] 2019-11-06 06:45
@CyrusNajmabadi Sure. [The project reference to F# project looks as assembly reference 16.4.0 Preview 3.0](https://github.com/dotnet/roslyn/issues/39703)
