### ISSUE TITLE
Add a feature to specify using editorconfig defaults without falling back to visual studio settings

### ISSUE THREAD

**Issue by xPaw** [dotnet/roslyn#67036] opened 2023-02-24 15:19 UTC
## Summary

Currently, it is impossible to have consistent formatting without listing every single rule in editorconfig for csharp, and it gets more complicated when new versions add new rules.

For example:
![image](https://user-images.githubusercontent.com/613331/221214980-541a2ae6-657b-4206-841c-58eec8b3ea48.png)

Even running `dotnet new editorconfig` will create a new file for you which is currently almost 400 lines long.

## Background and Motivation

As far as I am aware, it is currently impossible to have consistent formatting without specifying every single rule in editorconfig.

Furthermore, you need to keep the file updated for new versions when new rules are added.

Currently in Visual Studio, opening .editorconfig UI and then saving the file will also add many new lines of defaults.

## Proposed Feature

Considering there is already a template with defaults provided by `dotnet new editorconfig`, I propose adding some kind of option which says that any unspecified rule should fall back to however it is specified in the dotnet template, and not to visual studio settings.

Something as simple as `csharp_inherit_defaults = true` could do the trick.

## Alternative Designs

A nuget package with default editorconfig could be provided, but it's seemingly not currently possible: #19028

**Comment by sharwell** [comment] 2023-02-24 15:30
Duplicate of #39928

**Closed by sharwell** 2023-02-24 15:30 UTC
Labels: Area-IDE, Feature Request
