### ISSUE TITLE
VB Function call without () is not identified as InvocationExpression

### ISSUE THREAD

**Issue by NiKiZe** [dotnet/roslyn#45191] opened 2020-06-15 11:47 UTC
This might be a bug, But especially it is a question on how to identify function calls as calls when `()` is not given in the source.

**Version Used**: 
DiagnosticAnalyzer .NET 471

**Steps to Reproduce**:
Using `VisualBasicSyntaxWalker` to dump the tree

VB.NET code with a function call ending with `()`
```VB.NET
    Public Function SubName() As Object
        Return Environment.GetCommandLineArgs()
    End Function
```

Results in reasonable tree
```
Visit: CompilationUnit ## Public Function SubName() As Object
        Return Environment.GetCommandLineArgs()
    End Function
Visit: FunctionBlock ## Public Function SubName() As Object
        Return Environment.GetCommandLineArgs()
    End Function
Visit: FunctionStatement ## Public Function SubName() As Object
Visit: ParameterList ## ()
Visit: SimpleAsClause ## As Object
Visit: PredefinedType ## Object
Visit: ReturnStatement ## Return Environment.GetCommandLineArgs()
Visit: InvocationExpression ## Environment.GetCommandLineArgs()
Visit: SimpleMemberAccessExpression ## Environment.GetCommandLineArgs
Visit: IdentifierName ## Environment
Visit: IdentifierName ## GetCommandLineArgs
Visit: ArgumentList ## ()
Visit: EndFunctionStatement ## End Function
```

Same code, without the empty `()` parameterlist on `Environment.GetCommandLineArgs`
```VB.NET
    Public Function SubName() As Object
        Return Environment.GetCommandLineArgs
    End Function
```
Has no `InvocationExpression`
```
Visit: CompilationUnit ## Public Function SubName() As Object
        Return Environment.GetCommandLineArgs
    End Function
Visit: FunctionBlock ## Public Function SubName() As Object
        Return Environment.GetCommandLineArgs
    End Function
Visit: FunctionStatement ## Public Function SubName() As Object
Visit: ParameterList ## ()
Visit: SimpleAsClause ## As Object
Visit: PredefinedType ## Object
Visit: ReturnStatement ## Return Environment.GetCommandLineArgs
Visit: SimpleMemberAccessExpression ## Environment.GetCommandLineArgs
Visit: IdentifierName ## Environment
Visit: IdentifierName ## GetCommandLineArgs
Visit: EndFunctionStatement ## End Function
```

**Expected Behavior**:
Should see `Visit: InvocationExpression ## Environment.GetCommandLineArgs`

**Actual Behavior**:
No `InvocationExpression`, only `Visit: SimpleMemberAccessExpression ## Environment.GetCommandLineArgs`

I still think the tree should find this as an `InvocationExpression`
But given current framework, is there any way to find function calls without `()` in analyzers?
(also it would be great if we could have a warning from the compiler when there is no `()` on a function call)

**Comment by CyrusNajmabadi** [comment] 2020-06-15 17:13
Closing out as this is by design.  

> I still think the tree should find this as an InvocationExpression

It's definitely a member access expression.  How this ends up being emit isn't relevant to the sytnax tree, which only represents the raw concrete syntax of the tree.

> But given current framework, is there any way to find function calls without

Yes, you can use IOperation for this and look IInvocationOperation. IOperation represents the *semantics* of the code, not just the *syntax*

> also it would be great if we could have a warning from the compiler when there is no () on a function call

Tracked over at: https://github.com/dotnet/roslyn/issues/45170

Thanks!

**Closed by CyrusNajmabadi** 2020-06-15 17:13 UTC
