### ISSUE TITLE
O/I icon should show base/derived classes/method in a tree

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59918] opened 2022-03-03 16:38 UTC
The blue O & I icons in the left margin bring up a window with the base types, implemented interfaces, and derived types. However, there is no indication of the type hierarchy structure. ReSharper has a comparable _Inspect class hierarchy_ that bolds overriden methods also.

**Comment by CyrusNajmabadi** [comment] 2022-03-03 16:49
Effective dupe of the issues raised in https://github.com/dotnet/roslyn/issues/58219

**Closed by CyrusNajmabadi** 2022-03-03 16:49 UTC
Labels: Area-IDE, untriaged
