### ISSUE TITLE
Should collapse separate comment blocks separately

### ISSUE THREAD

**Issue by denisz1** [dotnet/roslyn#74816] opened 2024-08-20 02:06 UTC
I am unclear if this repo is the one for roslyn code folding in vscode and vs.

I have this code:
```cs
// some notes, etc. etc. etc. etc. etc. etc. etc. etc. etc. etc.
// etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc.
// etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc. etc.

// some other notes  etc. etc. etc. etc. etc. etc. etc. etc. etc.
// etc. etc. etc. etc. etc. etc.
```

That will collapse to this:
```cs
// some notes, etc. etc. etc. etc. etc. etc. etc. etc. etc. etc.
```

Instead of this:
```cs
// some notes, etc. etc. etc. etc. etc. etc. etc. etc. etc. etc.

// some other notes  etc. etc. etc. etc. etc. etc. etc. etc. etc.
```

In all other collapsings, the code blocks are collapsed separately. But if it is two comments blocks then they are merged.

I think if they are separated then they are not related and so must be collapsed separately. It is very frustrating that we have many documentations in our code, but they are always collapsed into one mega collapse... hard to find what we are looking for.

Thank you.

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:46
Closing out due to lack of broad feedback here.

**Comment by CyrusNajmabadi** [comment] 2024-11-26 02:46
Note: this is by design so a user can comment out a large section of code and then easily collapse it.  changing this behavior would regress a known scenario we want to keep working.

**Closed by CyrusNajmabadi** 2024-11-26 02:46 UTC
Labels: help wanted, Area-IDE, Feature Request, Concept-Continuous Improvement, Structure (Outlining)
