### ISSUE TITLE
Race condition completing (empty) attribute list for an event

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#16753] opened 2017-01-25 21:30 UTC
The following test (recommended in `CompilationEventTests.cs`)

``` c#
        [Fact, WorkItem(16753, "https://github.com/dotnet/roslyn/issues/16753")]
        public void TestConcurrentCompletionMany()
        {
            for (int i = 0; i < 1000; i++)
            {
                TestConcurrentCompletion();
            }
        }

        private static void TestConcurrentCompletion()
        {
            var source =
@"
using System;
public enum E1 { A, B, C, D, E }
public class C1
{
    public event Action e1;
    public event Action e2;
    public event Action e3;
    Action Events => e1 + e2 + e3;
}
public unsafe struct S1
{
    public fixed int X[10];
    public int A, B, C, D;
    public CI P1 => null;
    public CI P2 => null;
    public CI P3 => null;
    public CI this[CI a, CI b, CI c] => null;
}
internal class CI {}
";
            var q = new AsyncQueue<CompilationEvent>();
            var compilation = CreateCompilationWithMscorlib45(source).WithEventQueue(q);
            Func<Task> makeTask = async () => {
                try
                {
                    while (true)
                    {
                        var compilationEvent = await q.DequeueAsync();
                        compilation.GetDiagnostics();
                    }
                }
                catch (OperationCanceledException)
                {
                }
            };
            Task kickoff = Task.Run(() =>
            {
                compilation.GetDiagnostics();
            });
            // start a handful of tasks each of which waits on the queue
            var tasks = Enumerable.Range(0, 30).Select(i => i != 19 ? makeTask() : kickoff).ToArray();
            Task.WaitAll(tasks);
        }
```

frequently fails with an assertion error here in SourceEventSymbol.cs:

``` c#
        private CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
        {
            if ((_lazyCustomAttributesBag == null || !_lazyCustomAttributesBag.IsSealed) &&
                LoadAndValidateAttributes(OneOrMany.Create(this.AttributeDeclarationSyntaxList), ref _lazyCustomAttributesBag))
            {
                var completed = state.NotePartComplete(CompletionPart.Attributes);
                Debug.Assert(completed);
                DeclaringCompilation.SymbolDeclaredEvent(this);
            }

            return _lazyCustomAttributesBag;
        }
```

This looks like it may be a previously unknown race condition.

**Comment by jaredpar** [comment] 2018-09-12 16:48
Dupe of #28954

**Closed by jaredpar** 2018-09-12 16:48 UTC
Labels: Area-Compilers, Bug, Language-C#
