### ISSUE TITLE
IDocumentTrackingService is null in the OOP process

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#39781] opened 2019-11-12 19:16 UTC
Both @CyrusNajmabadi and I found this while attempting to refactor code that runs in OOP. See https://github.com/dotnet/roslyn/pull/39699#discussion_r343383146

**Comment by CyrusNajmabadi** [comment] 2022-11-01 18:37
Closing out as this is by design.  OOP will have no concept of these as it is intended to be stateless.  The caller needs to pass this info in if relevant.

**Closed by CyrusNajmabadi** 2022-11-01 18:37 UTC
Labels: Area-IDE, Concept-Continuous Improvement
