### ISSUE TITLE
Highlighting call to local function calls ExtractMethodCodeRefactoringProvider to throw

### ISSUE THREAD

**Issue by khyperia** [dotnet/roslyn#34803] opened 2019-04-05 23:24 UTC
**Version Used**: 

Visual Studio 2017

**Steps to Reproduce**:

```cs
class Program {
    public static void Main() {
        int x = 1;
        int Func() => x + (x = 2);
        Func();
    }
}
```

Highlight the call to `Func();` on the last line

**Expected Behavior**:

Not throw an exception

**Actual Behavior**:

`ExtractMethodCodeRefactoringProvider encountered an error and has been disabled`

```
System.InvalidOperationException : Matrix does not contain Key 'AB'.
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

---

Method extraction with local functions turns out to be really hard yet again :wink: (Sorry if I spammed y'all with a bajillion Watsons while narrowing this down to a minimal repro)

**Comment by sharwell** [comment] 2019-04-08 17:34
Duplicate of #31249

**Closed by sharwell** 2019-04-08 17:34 UTC
Labels: Area-IDE, Bug
