### ISSUE TITLE
Flaky Test: Analyzer failures

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#14700] opened 2016-10-24 17:48 UTC
Failure during some VSI tests. This is appearing as an error:

`Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.NamingStyles.CSharpNamingStyleDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.` 

Causes there to be more errors in the error list than expected. https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1059/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1061/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1062/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1063/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1064/

@dotnet/roslyn-analysis 

![image](https://cloud.githubusercontent.com/assets/2371880/19656687/d5a7df46-99d5-11e6-967b-7e1550c3b772.png)

**Comment by mavasani** [comment] 2016-10-24 17:49
This is an IDE analyzer - tagging @dpoeschl

**Comment by 333fred** [comment] 2016-10-24 17:51
Some more failures:
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/1005/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/1006/
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/1008/

**Comment by heejaechang** [comment] 2016-10-24 19:36
how one is supposed to investigate vsi test nowaday?

**Comment by panopticoncentral** [comment] 2016-10-24 19:54
Generally I build roslyn-internal and then run tao.exe in the binaries directory, choosing the test you want.

**Comment by heejaechang** [comment] 2016-10-24 20:03
so, Jenkins doesn't save any dump and etc to make investigation simpler anymore?

**Comment by 333fred** [comment] 2016-10-24 20:05
It does some saving. Head into the Build Artifacts for the build you're investigating, like here: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/1059/artifact/Open/Binaries/Release/. There's lots of logs under different folders.

**Comment by heejaechang** [comment] 2016-10-24 20:07
I know, there is log. but seems there is no dump.

**Comment by 333fred** [comment] 2016-10-25 07:53
These are continuing to fail on our internal VSI tests, there have been 7 failures on vsi_p3 in the last 24 hours.

**Comment by Pilchie** [comment] 2016-10-25 15:12
Tag @mmitche and @jasonmalinowski is dump archiving still disabled? 😢 

@CyrusNajmabadi can you take a look since @dpoeschl is OOF right now?

**Comment by Pilchie** [comment] 2016-10-25 15:12
@333fred I see results only for master above - can you confirm that this is NOT affecting `dev15-rc` builds?

**Comment by mmitche** [comment] 2016-10-25 15:24
I was under the impression it got turned back on after some rough heuristics to avoid a dump overload.

**Comment by 333fred** [comment] 2016-10-25 15:52
@Pilchie that's correct, it's just master.

**Comment by jasonmalinowski** [comment] 2016-10-25 17:38
Dump archiving is back on, under the promise we'll eventually implement those heuristics. ;-) It's still on, but that doesn't mean dumps always get created when you think they are.

**Comment by CyrusNajmabadi** [comment] 2016-10-25 20:36
Is tehre a dump i can actually look at for this?  @333fred have you still seen this issue?  If so, can you point me at a failure with a dump?  Thanks!

**Comment by 333fred** [comment] 2016-10-25 21:18
@CyrusNajmabadi it's still occurring on every run of https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3/. I'm not sure about a dump, I don't see any in the output from that vsi test.

**Comment by CyrusNajmabadi** [comment] 2016-10-25 21:24
I don't know what can be done without a dump.

**Comment by CyrusNajmabadi** [comment] 2016-10-25 21:24
Can we contact Swat to get things fixed up to capture dumps?

**Comment by 333fred** [comment] 2016-10-25 21:27
@dotnet/roslyn-infrastructure

**Comment by Pilchie** [comment] 2016-10-25 21:30
@mmitche / @jasonmalinowski Were they maybe not enabled for all the PR legs?

**Comment by mmitche** [comment] 2016-10-25 21:36
@Pilchie I haven't checked.  You're free to enable it again (it's in the netci.groovy file for the master branch).  However, you must put in at least some mitigation to avoid attempting to archive a huge amount of data (deleting most dumps, etc.).  The last time this got enabled a failure made it into checked in code and the jobs were attempting to archive 80GB on each run.

**Comment by Pilchie** [comment] 2016-11-02 23:27
@genlu Is this still an issue?

**Comment by genlu** [comment] 2016-11-04 17:40
@Pilchie I don't see the analyzer error in recent windows_vsi_p0. All of them passing except 2, which were caused by windows update on nodes.

**Closed** 2016-11-04 20:12 UTC
Labels: Area-IDE, Bug, Urgency-Now
