### ISSUE TITLE
Code style preferences not honoured

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#15814] opened 2016-12-09 23:35 UTC
**Version Used**: 
Microsoft Visual Studio Community 2017 RC
Version 15.0.25914.0 D15REL

**Steps to Reproduce**:

1. Change code style to _not_ prefer throw expressions, and have a severity of "None"
2. Build your solution

**Expected Behavior**: No hints, faded code, suggestions or any other mention of the code style I just expressed no interest in.

**Actual Behavior**:
![suggestion](https://cloud.githubusercontent.com/assets/13181165/21068057/2b9a811e-be67-11e6-8fb7-27c8124e1a90.png)

Changing the severity to error doesn't cause any compile errors either, so it seems to be using the default settings.

**Comment by lorcanmooney** [comment] 2016-12-10 00:28
This is bizarre. If I have no open documents, I get 83 use-throw expression suggestions in the error list. If I open a document with some of these suggestions, they're _removed_ from the list after a couple of seconds. Close the document, and all the suggestions are restored.

However, if I open a document with _no_ suggestions, then open one _with_ suggestions, the suggestions remain unchanged. Closing the former sometimes impacts the listed suggestions, but I have found a pattern there.

All of this is with full solution analysis turned on (which is a terrible name!)

**Comment by Pilchie** [comment] 2016-12-31 22:10
Tagging @heejaechang any ideas here?  Could this be related to the other issues with clearing that you were looking at?

**Comment by heejaechang** [comment] 2017-01-03 21:16
I will start looking at these issues. there are some issues around changing options, editor config files, open file only options. FSA options.

**Comment by Pilchie** [comment] 2017-01-19 22:26
@CyrusNajmabadi Can you take a look here?  Is this a dupe of the `IBuiltInAnalyzer` issue?

**Comment by Pilchie** [comment] 2017-01-20 20:44
Seems to have been - I can't repro with the latest build, @CyrusNajmabadi is going to verify with "just-built" bits this afternoon.

**Comment by CyrusNajmabadi** [comment] 2017-01-20 21:21
I can't repro this either.  Seems to have been fixed.

**Closed by CyrusNajmabadi** 2017-01-20 21:21 UTC
Labels: Area-IDE, Bug
