### ISSUE TITLE
KeyNotFoundException from Pythia.AbstractPythiaCompletionProvider.GetTextChangeAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59895] opened 2022-03-02 22:55 UTC
```
System.Collections.Generic.KeyNotFoundException : The given key 'InsertionText' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Pythia.AbstractPythiaCompletionProvider.GetTextChangeAsync(Document document,CompletionItem item,Nullable`1 ch,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.GetChangeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetChangeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.GetInsertionTextAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckItemsAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2022-03-02 22:57
@jinujoseph how do we contact Pythia for issues in their code?

**Comment by jinujoseph** [comment] 2022-03-02 23:47
@genlu  ??

**Comment by vivlimmsft** [comment] 2022-03-03 00:19
It looks like we have some code in pythia that assumes `CompletionItem`s always have a property named `InsertionText`. Seems it's been there since the beginning of the project. Is that an unsafe assumption to make? How was this exception found @tmat ?

**Comment by genlu** [comment] 2022-03-03 00:42
This is fixed by https://github.com/dotnet/roslyn/pull/59724, but not yet inserted due to some infra issue.

> Is that an unsafe assumption to make?

@vivlimmsft yes, stuff in the property bag is supposed to be implementation details of specific provider, which shouldn't be used by anyone else. However, in your case, we have exposed SymbolCompletionItem helpers to pythia (which was intended to serve roslyn's own providers), and it seems this blur of boundary somehow made it necessary to use those properties. Ideally, we should remove all such dependencies from Pythia.

**Closed** 2022-03-03 00:43 UTC
Labels: Area-IDE, untriaged
