### ISSUE TITLE
Navigate to Decompiled Sources Cancel

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#33305] opened 2019-02-11 23:21 UTC
There should be a way to cancel Navigate to Decompiled Sources in the dialog. Even selecting `No` will still open the metadata view.

**Steps to Reproduce**:

1. Ctrl+click on an external reference that triggers Navigate to Decompiled Sources. (The experimental Navigate to Decompiled sources setting in Tools > Options would need to be on.)
2. Hit `No` in dialog
![image](https://user-images.githubusercontent.com/8293542/52600458-8ce9d580-2e10-11e9-88ef-a01d57238d91.png)

**Expected Behavior**:
Does not navigate to metadata, or there is an option to cancel navigating entirely.

**Actual Behavior**:
Navigates to metadata.

Originated from [customer tweet](https://twitter.com/mortenmertner/status/1094625474079268871).

**Comment by sharwell** [comment] 2019-02-12 00:09
Duplicate of #28274

**Closed by sharwell** 2019-02-12 00:09 UTC
