### ISSUE TITLE
code fix engine not honoring span given by LB engine for refactoring

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#1631] opened 2015-03-27 01:55 UTC
```
if (supportSuggestion.SupportsRefactorings(document))
{
    var refactoringResult = GetRefactorings(requestedActionCategories, document, snapshot, workspace, optionService, cancellationToken);

    result = result == null ? refactoringResult :
                     refactoringResult == null ? result :
                         result.Concat(refactoringResult);
}
```

I think we have a bug around refactoring in LB.

since many refactoring requires scope (selection in the code or caret position), we pass that to refactoring provider but completely ignore span given by LB.

you can try selecting some code for extract method, and move mouse caret to completely unrelated errors and open LB from quick info. extract method will be there.

we should check the selection intersects with given span by LB, and only when it intersects, we should call refactoring.

...

we also should start not returning refactoring fix when only asked for codefix.

**Comment by shyamnamboodiripad** [comment] 2015-04-03 04:58
This is a dupe of #1595 that @amcasey had logged. As you mention above there are two issues we need to fix here. The 2nd issue (i.e. we shouldn't return refactorings when only asked for code fixes is captured in #1030.

**Comment by srivatsn** [comment] 2015-04-09 17:30
Fixed by #1824

**Closed by srivatsn** 2015-04-09 17:30 UTC
Labels: Area-Analyzers, Bug

**Comment by shyamnamboodiripad** [comment] 2015-04-09 22:06
Could you please verify that this is fixed @heejaechang?

**Comment by heejaechang** [comment] 2015-04-09 22:34
sure
