### ISSUE TITLE
Could #load argument completion offer file paths?

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4242] opened 2015-07-30 20:54 UTC
...analogous to the way ```#r``` offers assembly names.

**Comment by amcasey** [comment] 2015-07-30 20:54
FYI @kuhlenh @DustinCampbell @tmat @KevinH-MS

**Comment by DustinCampbell** [comment] 2015-07-30 21:14
It should. It's just broken.

**Comment by DustinCampbell** [comment] 2015-08-05 22:53
I took a look at this and the problem is that the CompletionPresenter in the EditorFeatures layer is not MEF-exported for the "Interactive Command" content type. When ```#load``` becomes part of the the C# language. Then, ```#load" will no longer be an command, so the content type of the buffer will be C#, which already has the CompletionPresenter MEF-exported properly.

I can easily hack this with a one-line change:

![image](https://cloud.githubusercontent.com/assets/116161/9099882/ecaf0710-3b89-11e5-8c45-398eb77a9f7f.png)

**Comment by DustinCampbell** [comment] 2015-08-05 22:58
Note: this is totally a hack. @KevinH-MS, if you're going to have ```#load``` in the C# language soon then you shouldn't bother with this hack.

![image](https://cloud.githubusercontent.com/assets/116161/9099953/80f6d024-3b8a-11e5-929a-7014da5153a5.png)

The file to hack this in is here:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Presentation/CompletionPresenter.cs#L12-L16

**Comment by KevinH-MS** [comment] 2015-09-14 03:52
Fixed with commit 0f14b3f34b3d76d3f16b47b3daf6ad9448f99731

**Closed by KevinH-MS** 2015-09-14 03:52 UTC
Labels: Area-Interactive, Feature Request, Interactive-Scripting

**Comment by amcasey** [comment] 2015-09-22 20:11
Works for me.
