### ISSUE TITLE
Unnecessary code colapse points 

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38567] opened 2019-09-07 00:11 UTC
**Version Used**: 
16.4.intpreview

**Steps to Reproduce**:
Have code with sufficient amount of constructs that have header and then block. Look at collapsible regions.

```
        /// <summary>
        /// Use this helper to register multiple refactorings (<paramref name="actions"/>).
        /// </summary>
        internal static void RegisterRefactorings<TCodeAction>(
            this CodeRefactoringContext context, ImmutableArray<TCodeAction> actions)
            where TCodeAction : CodeAction
        {
            if (!actions.IsDefault)
            {
                foreach (var action in actions)
                {
                    context.RegisterRefactoring(action);
                }
            }
        }
````

![image](https://user-images.githubusercontent.com/1764721/64466836-e70df900-d0c8-11e9-8d71-3543dbf6209b.png)

**Expected Behavior**:
Only the top marked collapsible region is there.

**Actual Behavior**:
Both are, the lower one is redundant from UX point of view.

Useful:
![image](https://user-images.githubusercontent.com/1764721/64466920-47049f80-d0c9-11e9-8eb6-ef52ffee4164.png)

Not useful:
![image](https://user-images.githubusercontent.com/1764721/64466896-2fc5b200-d0c9-11e9-8e9b-0fdde809c7d1.png)

**Comment by liamlim** [comment] 2019-09-11 08:52
I personally prefer second option. I find it easier to quickly append or prepend something to a block without a need of uncollapsing it because the block may be very long.

**Comment by sharwell** [comment] 2019-09-23 19:10
@dibarbet can you verify that this is reproducible? It looks like the bug where the TextMate features were running on C# code.

**Comment by dibarbet** [comment] 2019-09-23 19:30
Yep, the duplicate folding ranges was caused by the blue pencil textmate bug.  That was fixed a week or two ago.  I cannot reproduce this in the current dogfooding build.
<img width="509" alt="folding_ranges" src="https://user-images.githubusercontent.com/5749229/65456253-c3072300-ddfd-11e9-99f0-34e887f31b83.png">

Closing as duplicate of https://github.com/dotnet/roslyn/issues/38559

**Closed by dibarbet** 2019-09-23 19:30 UTC
Labels: Area-IDE, Bug, Investigation Required
