### ISSUE TITLE
Collapsed xml doc comment is missing a space

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20865] opened 2017-07-13 19:03 UTC
**Version Used**: d15rel 26711.1

**Steps to Reproduce**:

```csharp
        /// <summary>
        /// A flag indicating whether the <see cref="OnCompleted"/> has been invoked.
        /// </summary>
        private bool onCompletedInvoked;
```

**Expected Behavior**:

Collapsed appears like this:

```csharp
        /// <summary> A flag indicating whether the OnCompleted has been invoked.
        private bool onCompletedInvoked;
```

**Actual Behavior**:

Collapsed appears like this:

```csharp
        /// <summary> A flag indicating whether the OnCompletedhas been invoked.
        private bool onCompletedInvoked;
```

![image](https://user-images.githubusercontent.com/3548/28183170-51665f16-67c3-11e7-9ed4-fc6128372637.png)

**Comment by sharwell** [comment] 2017-07-13 20:49
Heh, we specifically tested the case where we don't want the space, but looks like this was missed.

**Comment by CyrusNajmabadi** [comment] 2017-07-14 15:41
Fixed with https://github.com/dotnet/roslyn/pull/20694

**Comment by CyrusNajmabadi** [comment] 2017-07-14 15:42
Currently looks like:

![image](https://user-images.githubusercontent.com/4564579/28219295-57e49fbc-6870-11e7-9e45-6cfae6383140.png)

**Closed by CyrusNajmabadi** 2017-07-14 15:41 UTC
Labels: Area-IDE, Bug, up-for-grabs

**Comment by sharwell** [comment] 2017-07-15 02:08
Duplicate of #20679.

**Comment by AArnott** [comment] 2017-07-15 13:56
Thanks
