### ISSUE TITLE
VS 2019 compiler issue following use of Quick action feature

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61544] opened 2022-05-26 19:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2019-compiler-issue-following-use-of-/10053518)._

---
[severity:Other]
I am using Visual Studio 2019 (Enterprise version) with all updates. I added the following line of code:

`private DateTime StartDateForQuestions => new DateTime(2021, 12, 3);`

There was a quick action recommendation I selected which resulted in:

```private DateTime StartDateForCNSTFactualQuestions => new(2021, 12, 3);```

I then did further work on the file and when I compiled it there were no errors in the error list but the following appeared in the output file:
```
 CaseListService.cs(46,66,46,70): error CS1031: Type expected
 CaseListService.cs(46,66,46,70): error CS8124: Tuple must contain at least two elements.
 CaseListService.cs(46,66,46,70): error CS1026: ) expected
 CaseListService.cs(46,66,46,70): error CS1526: A new expression requires (), [], or {} after type
 CaseListService.cs(46,66,46,70): error CS1002: ; expected
 CaseListService.cs(46,66,46,70): error CS1519: Invalid token '2021' in class, struct, or interface member declaration
```

It's a large file so I didn't immediately spot that the error was coming from the Quick action change; reversing that change fixed the problem.

---
#### Feedback Bot on 5/25/2022, 07:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-05-26 19:41
Looks like they're invoking a command line compiler that doesn't support implicit new expressions somehow.

**Comment by sharwell** [comment] 2022-06-03 00:28
This issue can occur if Visual Studio is instructed to use one version of the language, and the command line compiler is instructed to use a different version of the language. The most common cause of this would be an explicit `<LangVersion>` property in the project file which specifies `default` or `latest` or `preview`. Rather than specify a version which can vary across systems, the project can specific a known constant version (e.g. `7.3`) which is supported by both the IDE and the command line compiler.

**Comment by X-I-Interactive** [comment] 2022-06-06 19:31
@sharwell The project file has no `<LangVersion>` entry and is autogenerted bu VS 2019.

**Comment by Neme12** [comment] 2022-06-06 19:34
@X-I-Interactive Could you provide more info about what kind of a project it is? Or even better, a small repro including the project file?

**Comment by CyrusNajmabadi** [comment] 2024-10-22 20:23
Closing out as by design.  VS's compiler and the command line may be different.  If one is significantly out of date, you can get different errors.

**Closed by CyrusNajmabadi** 2024-10-22 20:23 UTC
Labels: Question, Area-IDE, Resolution-Answered
