### ISSUE TITLE
"Shared Project" appears twice in the New Project Dialog

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14194] opened 2016-09-29 21:13 UTC
**Version Used**: 25725

![image](https://cloud.githubusercontent.com/assets/235241/18972639/de9d7b14-864e-11e6-9a39-db4009b683e0.png)

**Comment by dpoeschl** [comment] 2016-09-29 21:13
@jmarolf Any ideas?

**Comment by dpoeschl** [comment] 2016-09-29 21:59
Are they identical (i.e., is this harmless), or is there some underlying difference?

**Comment by jmarolf** [comment] 2016-09-30 17:02
dupe of https://github.com/dotnet/roslyn-project-system/issues/375 Fixed in bcb2

**Closed by jmarolf** 2016-09-30 17:02 UTC
Labels: Area-IDE
