### ISSUE TITLE
CSharpCodeProvider vs Roslyn, round 2

### ISSUE THREAD

**Issue by codemonkey493** [dotnet/roslyn#26729] opened 2018-05-08 23:20 UTC
**Version Used**: 
```
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.8" targetFramework="net462" />
  <package id="Microsoft.Net.Compilers" version="2.8.0" targetFramework="net462" developmentDependency="true" />
```

**Steps to Reproduce**:

1. Create a fresh package with the packages above
2. create a CSharpCodeProvider object
3. Call CompileAssemblyFromFile()

**Expected Behavior**:
Compile.

**Actual Behavior**:
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'D:\Projects\MyProject\Bin\bin\roslyn\csc.exe'.'
(bin or roslyn folders aren't present in the D:\Projects\MyProject\Bin folder at all)

**Comment by jmarolf** [comment] 2018-05-08 23:52
>Create a fresh package with the packages above

Could you please list the packages you referenced?

**Comment by codemonkey493** [comment] 2018-05-09 00:06
@jmarolf fixed (broken formatting)

**Comment by jmarolf** [comment] 2018-05-09 00:11
@codemonkey493 this looks like an issue with https://github.com/aspnet/RoslynCodeDomProvider do you mind if I move this issue over there?

**Comment by codemonkey493** [comment] 2018-05-09 00:33
@jmarolf at the first sight it looks like the problem is due to Roslyn not copying itself to the bin output folder.

**Comment by jmarolf** [comment] 2018-05-09 01:02
`developmentDependency="true"` means "do not copy this package to the output folder".  This is fine because `Microsoft.Net.Compilers` is intended to be used to replace the compiler your project builds with, not the compiler that `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` uses.  I believe the problem is that `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` requests that certain compiler assemblies be copied to the output folder and `developmentDependency="true"` says to not copy compiler assemblies.  either removing `developmentDependency="true"`  or removing the package reference to `Microsoft.Net.Compilers` will fix this issue, but https://github.com/aspnet/RoslynCodeDomProvider will need to decide how they want to handle this specific case.

**Comment by codemonkey493** [comment] 2018-05-09 02:41
@jmarolf removing `developmentDependency="true"` didn't solve the problem, there must be something else

**Comment by jmarolf** [comment] 2018-05-09 18:18
Sorry for the confusion, `Microsoft.Net.Compilers` should never copy itself to the output directory. `developmentDependency="false"` won't effect what gets copied where.

`Microsoft.Net.Compilers` description from [nuget.org](https://www.nuget.org/packages/Microsoft.Net.Compilers/):

>   Referencing this package will cause the project to be built using the specific version of the C# and Visual Basic compilers contained in the package, as opposed to any system installed version.

`Microsoft.Net.Compilers` purpose is to let your build the project that references this package using a newer compiler.  If you look at the `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` package you will see that version `1.0.8` references and attempts to copy  the compilers references in `Microsoft.Net.Compilers` but in `2.0.0-preview` they abandon this approach and just package the compilers in `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` itself.

**Comment by jmarolf** [comment] 2018-05-09 19:04
moving this issue to https://github.com/aspnet/RoslynCodeDomProvider/issues/46 to get clarification from the team about how `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` should be consumed

**Closed by jmarolf** 2018-05-09 19:04 UTC

**Comment by codemonkey493** [comment] 2018-05-09 20:44
@jmarolf I wonder if there is any way to make `Microsoft.Net.Compilers` assemblies copy to the output folder, then?
I don't really need the `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` package and it's too buggy.

**Comment by jmarolf** [comment] 2018-05-09 20:46
@codemonkey493 what are you trying to do? What will you use `csc.exe` for in the output directory?

**Comment by codemonkey493** [comment] 2018-05-09 21:31
@jmarolf I want to use it compile some code that I generate in runtime.

**Comment by jmarolf** [comment] 2018-05-09 21:38
@codemonkey493 I see.  There are a couple of options for that.  If you just want to run dynamically generated code then I think [`Microsoft.CodeAnalysis.CSharp.Scripting`](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting/) might be the right choice to start with.  You can see some example use cases [here](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples).  Is that your intention or do you need the generate code dynamically as part of the build?

**Comment by codemonkey493** [comment] 2018-05-09 21:48
@jmarolf this might be useful. No, I only need it during runtime.

**Comment by jmarolf** [comment] 2018-05-09 21:49
@codemonkey493 alright, let me know how it goes

**Comment by codemonkey493** [comment] 2018-05-09 22:30
@jmarolf 
```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(16,1): error CS7021: Cannot declare namespace in script code
```

It's also very slow. Looks like this is not what I need.
The ability to simply package Roslyn's csc.exe with my application would be perfectly enough.

**Comment by jmarolf** [comment] 2018-05-10 00:35
@codemonkey493 scripting API is our answer for runtime code generation but if that doesn't meet your needs, you still don't need `csc.exe` to generate or compile code.  You can use [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/), create a [`CSharpCompilation`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,36) object and call [`Emit`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,2047) to compile the contents to a stream.

see [this](https://github.com/dotnet/roslyn-sdk/blob/master/samples/CSharp/APISamples/Compilations.cs#L19) sample for how to do this.

**Comment by codemonkey493** [comment] 2018-05-16 20:18
@jmarolf I've just noticed that the roslyn binaries were copied to the root of the disk instead.

**Comment by jmarolf** [comment] 2018-05-16 20:21
@codemonkey493 what does that mean? Are the binaries being copied to `C:\`? Can you give me the contents of your project file?

**Comment by fandrei** [comment] 2018-05-29 20:59
@jmarolf the binaries were copied to the root of the folder where my project was, i.e. `D:\` in my case. Unfortunately I can't reproduce this behavior as I already changed the project file.
