### ISSUE TITLE
Missing IConstructorBodyOperation for types with PrimaryConstructor

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#58741] opened 2022-01-09 19:56 UTC
**Version Used**: 4.2.0-1.22057.5

**Steps to Reproduce**:

Execute the following code:
```csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

var tree = ParseSyntaxTree(@"

var foo = new Foo();

public record BaseFoo
{
    public int B { get; init; }

    public BaseFoo(int x = 12)
    {

    }
}

public record Foo(int A = 42) : BaseFoo
{

}");

var refApis = AppDomain.CurrentDomain.GetAssemblies().Select(a => MetadataReference.CreateFromFile(a.Location));
var com = CSharpCompilation.Create("something", new[] { tree }, refApis);
var diag = com.GetDiagnostics().Where(e => e.Severity == DiagnosticSeverity.Error).ToList();
var model = com.GetSemanticModel(tree);

foreach (var d in diag)
{
	Console.WriteLine(d);
}

var fooSyn = tree.GetRoot().DescendantNodes().OfType<RecordDeclarationSyntax>().Skip(1).First();

Console.WriteLine("node to analyze:");
Console.WriteLine(fooSyn);

Console.WriteLine("---------");

Console.WriteLine("operations:");
foreach (var subSyn in fooSyn.DescendantNodesAndSelf())
{
	var operation = model.GetOperation(subSyn);
	if (operation is { })
	{
		Console.WriteLine(operation.GetType().Name);
	}
}

Console.WriteLine("---------");
Console.WriteLine("declared symbols:");
foreach (var subSyn in fooSyn.DescendantNodesAndSelf())
{
	var sym = model.GetDeclaredSymbol(subSyn);
	if (sym is { })
	{
		Console.WriteLine(sym.GetType().Name);
		Console.WriteLine(subSyn);
		Console.WriteLine();
	}
}


Console.WriteLine("---------");
Console.WriteLine("symbols:");
foreach (var subSyn in fooSyn.DescendantNodesAndSelf())
{
	var sym = model.GetSymbolInfo(subSyn).Symbol;
	if (sym is { })
	{
		Console.WriteLine(sym.GetType().Name);
		Console.WriteLine(subSyn);
		Console.WriteLine();
	}
}
```

**Expected Behavior**:
There should be at least a single `IConstructorBodyOperation` for the primary constructor. In addition there should be an `IMethodSymbol` for the primary constructor (expected on `ParameterListSyntax` of the type)

**Actual Behavior**:
No `IOperation` or `ISymbol`

The program prints:
```
node to analyze:
public record Foo(int A = 42) : BaseFoo
{

}
---------
operations:
ParameterInitializerOperation
LiteralOperation
---------
declared symbols:
NonErrorNamedTypeSymbol
public record Foo(int A = 42) : BaseFoo
{

}

ParameterSymbol
int A = 42

---------
symbols:
NonErrorNamedTypeSymbol
int

NonErrorNamedTypeSymbol
BaseFoo
```

**Comment by 333fred** [comment] 2022-08-09 18:30
Duplicate of https://github.com/dotnet/roslyn/issues/47829.

**Closed by 333fred** 2022-08-09 18:30 UTC
Labels: Bug, Area-Compilers, Feature - IOperation
