### ISSUE TITLE
IDE automatically adds async keyword to methods without changing the return type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55975] opened 2021-08-27 21:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE-automatically-adds-async-keyword-to-/1511718)._

---
I was editing in the IDE and noticed that as soon as I used an await keyword in a non-async function, it changed the method to be `async`. However, the return type of the method remained unchanged. `async void` is rarely the right thing to be using and it's easy for this feature to turn into a source of bugs in an unassuming user's app.

---
#### Feedback Bot on 8/24/2021, 02:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/25/2021, 10:19 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment] 2021-09-10 17:54
Based on the feedback in https://github.com/dotnet/roslyn/pull/55983, this is by design. We'd like to address the concern in this feedback by also changing the return type to Task instead.

**Comment by sharwell** [comment] 2021-11-30 15:54
@genlu I strongly disagree with the proposed redirection. Typing `await` in the middle of a method body _must not_ implicitly change the method return type. I've hit #55983 multiple times and was just assuming there was a delay on getting it shipped. We should reopen that issue in its original form and get it merged.

/cc @CyrusNajmabadi

**Comment by FrancescoCarraro** [comment] 2022-03-22 09:02
99.9% of times I use _await_ keyword in a method, I want this to be changed into an _async_ one and return type changed. Either the introduction of await change the host method or leave it unchanged (using the **CTRL + .** to solve the issue). The middle (only adding async) is the worse solution

**Comment by sharwell** [comment] 2022-03-22 13:59
@FrancescoCarraro the adding async feature was never expected to apply in cases where the return type needed to be changed. It was designed for cases where a method already returned an awaitable type (e.g. `Task<bool>`), where the only missing part was `async`. I've reopened #55983 to fix this bug.

**Closed** 2024-11-30 17:05 UTC
Labels: Bug, Area-IDE, Developer Community, IntelliSense-Completion
