### ISSUE TITLE
Wrap parameters style should be configurable from code style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38515] opened 2019-09-05 17:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/699244/wrap-parameters-style-should-be-configurable-from.html)._

---
When you right click on a method name you get options on the context menu to wrap and align parameters.

Rather than picking the style of wrapping each time it is used, I would like to be able to configure which style of wrapping is to be used for the whole solution in the code style options and save them to .editorConfig rather than having each developer choose on a case-by-ca se basis.

I would also like code cleanup to automatically wrap parameters using my chosen style when the line length is over a configured length.

---
#### Jane Wu [MSFT] on 8/20/2019, 03:54 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment] 2019-09-10 17:58
Duplicate of #37962

**Comment by sharwell** [comment] 2019-09-10 17:58
Also related to #33872

**Closed by sharwell** 2019-09-10 17:58 UTC
Labels: Area-IDE, Feature Request, Need Design Review
