### ISSUE TITLE
VS 20221 .editorConfig not detecting custom settings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57812] opened 2021-11-17 07:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-20221-editorConfig-not-detecting-cus/1580585)._

---
[regression] [worked-in:2019]
We have a customized .editorConfig file in our solution that has certain analyzer rules disabled etc. 

This works fine in VS2019 but not in VS2022

Raw .editorConfig value
![B47e1ca5632bd4c0d977e7e3ae4dbfe26637722401156229809_20211111-170834-image](https://user-images.githubusercontent.com/9797472/142157809-74ec8b90-9f99-4db0-be35-1e4ba6fdd0d0.png)

VS2019
![B2606346f3fdf4ae39e8ee4717f0487f7637722400567444228_20211111-170735-image](https://user-images.githubusercontent.com/9797472/142157840-2d815307-f38b-4849-b1c1-0f39ceb11ce3.png)

VS2022
![B31cd820b3c0c4dddbc9ce27fe5bb7b77637722399903154550_20211111-170629-image](https://user-images.githubusercontent.com/9797472/142157879-4ca7a3f2-2c78-4959-b7ca-12aff0b6dcdf.png)

So obviously this is being picked up in the IDE as a warning when it shouldn't be. Build still works fine.

---
#### Feedback Bot on 11/11/2021, 07:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/12/2021, 09:53 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2022-03-18 21:57
duplicate of https://github.com/dotnet/roslyn/issues/60232

**Closed by jmarolf** 2022-03-18 21:57 UTC
Labels: Bug, Area-Analyzers
