### ISSUE TITLE
Preprocessor Directives in .csproj files get rejected when they contain line breaks or white space.

### ISSUE THREAD

**Issue by ChrisKoebke** [dotnet/roslyn#58391] opened 2021-12-17 10:45 UTC
**Version Used**: 
VS2022 Latest Version

**Steps to Reproduce**:

1. Create a new console application project
2. Add the following to any active PropertyGroup inside your .csproj file:

```
<DefineConstants>
		MY_DIRECTIVE_A;
		MY_DIRECTIVE_B;
</DefineConstants>
```

**Expected Behavior**:
White space and line breaks should be trimmed after splitting the DefineConstants string by ';'

**Actual Behavior**:
The compiler adds these including line breaks/white space causing them to get ignored:

```
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(75,5): warning MSB3052: The parameter to the compiler is invalid, '/define:
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(75,5): warning MSB3052: 		MY_DIRECTIVE_A' will be ignored.
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(75,5): warning MSB3052: The parameter to the compiler is invalid, '/define:
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(75,5): warning MSB3052: 		MY_DIRECTIVE_B' will be ignored.
```

**Comment by Youssef1313** [comment] 2021-12-17 12:16
A VB bug around the same area is https://github.com/dotnet/roslyn/issues/38433.

**Comment by jaredpar** [comment] 2022-01-04 04:38
Closing as this behavior is presently "By Design". This behavior has existed since MSBuild 1.0 (to my understanding). Would need to see a compelling reason for making this change.

**Closed by jaredpar** 2022-01-04 04:38 UTC
Labels: Area-Compilers, untriaged

**Comment by cjacobi** [comment] 2023-07-06 17:55
The behavior of MSBuild is completely absurd.  Why can they refuse your request.
A co sufferer
Chris
