### ISSUE TITLE
Suggestion: Auto-populate constructor arguments.

### ISSUE THREAD

**Issue by fiseni** [dotnet/roslyn#49474] opened 2020-11-18 18:47 UTC
Object initializer syntax is a great feature and easy to use with VS. But, not rarely we have to utilize constructors with few/several arguments. It would be really great if VS can automatically create the layout, auto-populate the constructor arguments, and style it as shown below.

```
var address = new Address
(
	street: ,
	city: ,
	region: ,
	country: ,
	zip: 
);
```

**Comment by sharwell** [comment] 2020-11-18 19:14
Duplicate of #12363

**Comment by sharwell** [comment] 2020-11-18 19:15
I marked this as a duplicate of #12363, since we have a design in progress described by https://github.com/dotnet/roslyn/issues/12363#issuecomment-602865938

**Closed by sharwell** 2020-11-18 19:14 UTC
Labels: Area-IDE, untriaged
