### ISSUE TITLE
Analyzer-generated warnings disappear from Error List after a few seconds

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20238] opened 2017-06-15 15:17 UTC
**Version Used**: d15rel 26612.0

**Steps to Reproduce**:

```
git clone https://github.com/Microsoft/vs-mef
cd vs-mef\src
git checkout 98494bf5abd722bcb6759090badb87be747ed777
msbuild /t:restore
Microsoft.VisualStudio.Composition.sln
```

Once in VS, build the solution (or at least the Microsoft.VisualStudio.Composition project). 

**Expected Behavior**:

The Error List initially populates with several warnings (consistent with warnings in the output window).
![image](https://user-images.githubusercontent.com/3548/27188468-1794806e-51a3-11e7-8322-ef8b07bd90fa.png)

**Actual Behavior**:

After the Error List populates, perhaps about 30 seconds later, it clears all warnings and they don't come back.
![image](https://user-images.githubusercontent.com/3548/27188474-1ba66eec-51a3-11e7-9b47-706f9e3b1255.png)

**Comment by sharwell** [comment] 2017-06-15 21:13
Could this be a duplicate of #6649?

**Comment by AArnott** [comment] 2017-06-16 00:32
Seems similar, in that these warnings are in non-code files. However #6649 says they simply don't show up. In my case, they show up after a build temporarily. I'm not sure whether that means it's a dupe or not.

**Comment by sharwell** [comment] 2017-06-16 01:52
@AArnott the reason they show up after a build is the error list shows everything reported by the compiler. It then replaces the items in the list after the next IntelliSense update, which in your case removes them.

**Closed** 2017-06-16 01:52 UTC
Labels: Area-Analyzers, Resolution-Duplicate
