### ISSUE TITLE
Behavior Differences in Extension Methods: this ref vs this in 

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#26864] opened 2018-05-15 17:01 UTC
**Version Used**: 
VS 2017 15.8 Preview 1, C# 7.3

**Steps to Reproduce**:
`static T Method<T>(this ref T it) => it; //CS8337 The first parameter of a 'ref' extension method 'Method' must be a value type or a generic type constrained to struct.`
`static T Method<T>(this ref T it) where T : struct => it; //OK`
`static T Method<T>(this in T it) => it; //CS8338 The first parameter of an 'in' extension method 'Method' must be a value type.`
`static T Method<T>(this in T it) where T : struct => it; //CS8338 The first parameter of an 'in' extension method 'Method' must be a value type.`

**Expected Behavior**:
`static T Method<T>(this in T it) where T : struct => it; //OK (struct is a value type)`

**Actual Behavior**:
`static T Method<T>(this in T it) where T : struct => it; //CS8338 The first parameter of an 'in' extension method 'Method' must be a value type.`

**Comment by sharwell** [comment] 2018-05-15 22:49
Duplicate of #24601

**Closed by sharwell** 2018-05-15 22:49 UTC

**Comment by fitdev** [comment] 2018-05-16 07:48
@sharwell Sorry I was not aware of this related issue. However mine seems to be subtly different in that there is just one constraint, namely : `struct`, no interfaces. Therefore, given that there are no additional Interface-constraints, in the case I outlined, shouldn't the code be allowed to compile?

**Comment by sharwell** [comment] 2018-05-16 16:12
@fitdev I don't believe the interface constraint has any impact on the behavior (and probably isn't the basis for the design). I would suggest raising your question in the other issue if you are interested in relaxing the compiler restrictions for some case you encountered.
