### ISSUE TITLE
Crash in simpleprograms + 16.7p1 branch

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#43878] opened 2020-05-01 18:39 UTC
```C#
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddStatementsWorker[TDeclarationNode](TDeclarationNode destinationMember, IEnumerable`1 statements, CodeGenerationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddStatements[TDeclarationNode](TDeclarationNode destinationMember, IEnumerable`1 statements, CodeGenerationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.<GenerateAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.<ExtractMethodAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.<ExtractMethodAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.<ExtractLocalFunctionAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.<GetCodeActionsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.<ComputeRefactoringsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__13.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionErrorHandler.HandleError(System.Object, System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionManager+ExtensionManager.HandleException(System.Object, System.Exception)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<GetRefactoringFromProviderAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
```

Relates to https://github.com/dotnet/roslyn/issues/43563 (test plan for top-level statements)

**Comment by jcouv** [comment] 2020-05-02 14:03
Watching back the [recording](https://msit.microsoftstream.com/video/2d40a1ff-0400-96d1-e567-f1ea8be16e42) (shortly after 7min), the scenario was a switch expression in a top-level statement (the one in `#region switch` below) and then selecting the region inside the braces.

CC @AlekseyTs 

Andy shared his code sample:
```
using Microsoft.CodeAnalysis.CSharp;
using System;
Console.WriteLine("Hello, world");
#region ascii
Console.WriteLine(isAsciiLetter('d'));
Console.WriteLine(isAsciiLetter(';'));
bool isAsciiLetter(char c)
{
return c is (> 'a' and < 'z') or (> 'A' and < 'Z');
}
#endregion
#region switch
SyntaxKind kind = SyntaxKind.None;
string s = kind switch
{
< SyntaxKind.YieldReturnStatement => "less",
SyntaxKind.YieldBreakStatement or
SyntaxKind.YieldReturnStatement => "iterator",
> SyntaxKind.YieldBreakStatement => "greater"
};
#endregion
#region test
s = null;
if (s is not null)
{
Console.WriteLine("not null");
}
else
{
Console.WriteLine("null");
}
#endregion
```

**Comment by AlekseyTs** [comment] 2020-05-04 22:11
It looks like the code above has some syntax errors and semantic errors until expected references are added. After simply copy pasting the code and hovering over ```c is (> 'a' and < 'z') or (> 'A' and < 'Z');``` an assert fires:
 ```Debug.Fail("The diagnostic can only be produced in context of a deconstruction-assignment or deconstruction-foreach");```

```
>	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.CodeFixes.GenerateDeconstructMethod.GenerateDeconstructMethodCodeFixProvider.RegisterCodeFixesAsync(Microsoft.CodeAnalysis.CodeFixes.CodeFixContext context) Line 59	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync.AnonymousMethod__1() Line 629	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(Microsoft.CodeAnalysis.Extensions.IExtensionManager extensionManager, object extension, System.Func<System.Threading.Tasks.Task> function) Line 73	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Diagnostics.DiagnosticData diagnostic, System.Threading.CancellationToken cancellationToken) Line 629	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetFirstDiagnosticWithFixAsync(Microsoft.CodeAnalysis.Document document, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> severityGroup, Microsoft.CodeAnalysis.Text.TextSpan range, System.Threading.CancellationToken cancellationToken) Line 144	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetMostSevereFixableDiagnosticAsync.AnonymousMethod__2() Line 112	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

**Comment by jcouv** [comment] 2020-05-05 04:45
Thanks. Removing area-compiler

**Comment by AlekseyTs** [comment] 2020-05-05 16:24
> Thanks. Removing area-compiler

I am not claiming that the assert and the crash are the same issue. However, given call stacks that we have so far, I think it makes sense for IDE team to take a look at this issue first.

**Comment by CyrusNajmabadi** [comment] 2020-05-27 20:45
@sharwell You fixed the crash in CSharpCodeGenerationService.AddStatements right?

**Comment by sharwell** [comment] 2020-05-27 22:32
@CyrusNajmabadi Not sure. Need to verify.

**Comment by sharwell** [comment] 2020-09-10 16:50
Duplicate of #44260

**Closed** 2020-11-13 00:06 UTC
Labels: Area-IDE, Bug, New Language Feature - Simple Programs, Resolution-Duplicate
