### ISSUE TITLE
Ambiguity incorrectly detected involving delegate parameter on uncallable overload

### ISSUE THREAD

**Issue by qwertie** [dotnet/roslyn#54586] opened 2021-07-03 04:26 UTC
**Version Used**: C# 9.0 / VS 16.9.0

**Steps to Reproduce**:

Compile or paste this code in VS:

~~~cs
using System;

interface I { }
struct S : I { }
    
class FalseAmbiguity {
    void BizarreError() {
        WTF(ActionS); // OK
        WTF(ActionI); // Error CS0121: The call is ambiguous
    }

    static void WTF(Action<S> action) { }
    static void WTF(Action<I> action) { }

    void ActionS(S s) { }
    void ActionI(I s) { }
}
~~~

**Expected Behavior**: No error, as `ActionI` is an invalid argument to `WTF(Action<S> action)`. If there's a language spec saying this is ambiguous, the spec is surely wrong.

**Actual Behavior**: Error CS0121

**Comment by Youssef1313** [comment] 2021-07-03 05:19
Possibly duplicate of https://github.com/dotnet/roslyn/issues/51232. This is tracked by https://github.com/dotnet/csharplang/issues/3277.

**Closed** 2021-07-07 05:49 UTC
Labels: Area-Compilers, Resolution-Duplicate
