### ISSUE TITLE
Allow expression body in try/catch statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42724] opened 2020-03-24 16:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/950645/allow-expression-body-in-trycatch-statement.html)._

---
Add the ability to specify an expression body in try/catch statements:

```
try 
{   
    var a = 10 / 0;
}
catch (DivideByZeroException e) => Console.WriteLine(e.ToString());
catch (Exception e) => Console.WriteLine(e.Message);
finally => Console.WriteLine("Done");
```

Or something similar to this. Maybe even allow it for the `try` statement as well. Embedded try/catch blocks might be trickier.

---
#### Visual Studio Feedback System on 3/17/2020, 02:29 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-03-24 17:12
Dupe of https://github.com/dotnet/csharplang/issues/2734

**Closed by CyrusNajmabadi** 2020-03-24 17:12 UTC
