### ISSUE TITLE
`nameof` operator is not provided as an operation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8874] opened 2016-02-18 07:04 UTC
For example 

``` cs
var a = nameof(x);
```

the `IVariableDeclaration` operation has a `None` operation as `InitialValue`.

**Comment by genlu** [comment] 2016-02-18 07:05
@JohnHamby Should this be fixed for 1.2?

**Comment by mavasani** [comment] 2017-07-07 22:24
Dupe of https://github.com/dotnet/roslyn/issues/19954

**Closed by mavasani** 2017-07-07 22:24 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation
