### ISSUE TITLE
IDE0034  default expression can be simplified

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#22956] opened 2017-11-01 19:39 UTC
The statement

int? x = default(int)

Generates a warning IDE0034 'default' expression can be simplified and the suggestion is to replace 'default(int)' with just 'default'. This is wrong because defalt(int) is 0 while default for int? is null.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/140204/default-expression-can-be-simplified.html
VSTS ticketId: 516774_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2017-11-01 19:58
This appears to be a duplicate of #20856, which is fixed for 15.5 (Preview 1 and newer).

**Closed** 2017-11-01 19:59 UTC
Labels: Resolution-Duplicate
