### ISSUE TITLE
SymbolKey.Resolve should prefer instances from source over metadata when things are ambiguous

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#6791] opened 2015-11-15 20:19 UTC
While investigating http://connect.microsoft.com/VisualStudio/feedback/details/2013884/error-hresult-e-fail-has-been-returned-from-a-call-to-a-com-component and https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/00aede04-d8cd-4475-8114-4b4792261052/winforms-designer-error-hresult-efail-has-been-returned-from-a-call-to-a-com-component, I found that the issue was that a project had a reference to itself.  This led to ambiguous `SymbolKey` resolutions because the same type appeared in multiple places.  However, the compiler prefers instances from source in that case, and SymbolKey should do the same.

**Comment by CyrusNajmabadi** [comment] 2016-03-31 00:40
I'm not actually certain this is the correct thing for SymbolKey to do.  Say, for example, you have a metadata type and you get the symbol key for that.  It doesn't necessarily make sense to me that resolving that symbol key would not end up giving you back that same symbol.

So i think it is correct for SymbolKey to resolve back to multiple symbols (even if they cross source/metadata).  I think it's the onus of the consumer to not assume that you'll only get one symbol back, or that that symbol will be from source.

I think this is by design to me.

**Closed by CyrusNajmabadi** 2016-03-31 00:40 UTC
Labels: Area-IDE, Bug
