### ISSUE TITLE
When record implements an interface with events, the compiler throws exceptions.

### ISSUE THREAD

**Issue by zxgamekingdom** [dotnet/roslyn#51122] opened 2021-02-04 01:55 UTC
In .Net 5, record can implement the interface, right? When record implements an interface with events, the compiler throws exceptions, not syntax error.
```
using System;

namespace ConsoleApp1
{
    static class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.ReadKey();
        }
    }

    public record Test : ITest
    {
        public event EventHandler<int> TestEvent;

        protected virtual void OnTestEvent(int e)
        {
            TestEvent?.Invoke(this, e);
        }
    }

    public interface ITest
    {
        public event EventHandler<int> TestEvent;
    }
}
```
```
.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by CyrusNajmabadi** [comment] 2021-02-11 02:00
> the compiler throws exceptions, not syntax error.

What exception does the compiler throw for you?

**Comment by jaredpar** [comment] 2021-02-11 16:58
Thanks for taking the time to file this issue. Looks to be a dupe of #49286. Verified it no longer repros on current.

**Closed by jaredpar** 2021-02-11 16:58 UTC
Labels: Area-Compilers, untriaged
