### ISSUE TITLE
xml doc comment generation for @parameters should drop the @

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#4456] opened 2015-08-09 16:44 UTC
When typing `///` in front of a method with a parameter that has a leading `@` in its name, the generated xml doc comment retains the `@`:

        /// <summary>
        /// 
        /// </summary>
        /// <param name="@o"></param>
        private void foo(object @o) { }

This leads the compiler to then generate these two warnings:

> Warning	CS1572	XML comment has a param tag for '@o', but there is no parameter by that name
Warning	CS1573	Parameter 'o' has no matching param tag in the XML comment for 'GitExtensions.foo(object)' (but other parameters do)

The correct xml doc comment should omit the `@` character in the parameter name.

Note of course that the `@` character is only required in parameter names that conflict with language keywords. This bug repros whether or not the parameter name is actually a keyword.

**Comment by sharwell** [comment] 2015-08-10 04:13
Duplicate of #2936, with a pull request for a proposed solution now under review at #4165.

**Closed** 2015-08-10 14:30 UTC
