### ISSUE TITLE
[Failing Test] BasicQuickInfo.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15862] opened 2016-12-13 14:16 UTC
document missing from result

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_prtest/132/artifact/Open/Binaries/Release/Exes/EditorTestApp/VSIntegrationTestLogs/BasicQuickInfo.html

....

System.Exception: 
ExpectedQuickInfo: Class‎ System.String
Represents text as a series of Unicode characters.To browse the .NET Framework source code for this type, see the Reference Source.

ActualQuickInfo: Class‎ System.String

**Comment by Pilchie** [comment] 2016-12-13 17:22
Dupe of #15841

**Closed by Pilchie** 2016-12-13 17:22 UTC
