### ISSUE TITLE
Add this or me qualification rule triggered incorrectly in return statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23016] opened 2017-11-05 15:42 UTC
Have the following code:

            return new UserSession
            {
                UserId = subject
            };

Where UserSession is a simple class with property UserId. I'm getting green squiggles under the UserId in that statement, suggesting I add this or me qualification.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/126539/add-this-or-me-qualification-rule-triggered-incorr.html
VSTS ticketId: 505612_
_These are the original issue comments:_

David Poeschl [MSFT] on ‎10‎/‎18‎/‎2017, 00:37 PM (17 days ago): <p>Thank you for your feedback! I've so far been unable to reproduce this problem. I tried with the following code:</p><p><br></p><p>class C</p><p>\{</p><p>  static UserSession M()</p><p>  \{</p><p>    object subject = null;</p><p>    return new UserSession</p><p>    \{</p><p>      UserId = subject</p><p>    };</p><p>  }</p><p>}</p><p><br></p><p>internal class UserSession</p><p>\{</p><p>  public object UserId \{ get; set; }</p><p>}</p><p><br></p><p>And under &quot;Text Editor | C# | Code Style | General | 'this.' preferences&quot; I've set everything to &quot;Prefer 'this.'&quot; with &quot;Warning&quot; severity. Am I missing a step that you can tell? Thanks!</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2017-11-05 15:45
@zaytsev-victor This was reported in 15.5 Preview, but @dpoeschl was unable to reproduce it on the first attempt.

**Comment by zaytsev-victor** [comment] 2017-11-05 16:31
@sharwell I was able to reproduce this issue with the following code
```csharp
class C
{
    public object UserId { get; set; }

    UserSession M()
    {
        object subject = null;

        return new UserSession
        {
            UserId = subject
        };
    }
}

internal class UserSession
{
    public object UserId { get; set; }
}
```

I will take a look.

**Comment by zaytsev-victor** [comment] 2017-11-23 12:18
@sharwell It is probably a duplicate of #22776

**Comment by zaytsev-victor** [comment] 2017-11-23 12:35
the problem  that in 15.4 version value of ```memberReference.Instance``` [here](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs#L65) was ```null```. But in 15.5 it has a value.

**Closed** 2018-01-09 21:02 UTC
Labels: Area-IDE, Bug, Developer Community, Resolution-Fixed
