### ISSUE TITLE
AnalyzerDriver is asserting during bootstrap build

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5962] opened 2015-10-14 16:37 UTC
The AnalyzerDriver type is asserting during a bootstrap build on the [following line](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs#L605):

``` csharp
catch (TaskCanceledException) when (!prePopulatedEventQueue)
{
    // When the queue is completed with a pending DequeueAsync return then a 
    // TaskCanceledException will be thrown.  This just signals the queue is 
    // complete and we should finish processing it.

    // *** this line *** 
    Debug.Assert(CompilationEventQueue.IsCompleted, "DequeueAsync should never throw unless the AsyncQueue<T> is completed.");
    break;
}
```

This assert is firing a bit randomly.  But if you run the bootstrap build locally 5-6 times you will see it.  The assert is being commented out for now in order to fix Jenkins.

**Comment by srivatsn** [comment] 2015-10-14 22:57
Seems to be a dupe of #3001

**Comment by srivatsn** [comment] 2015-10-14 23:05
Closing as dupe.

**Closed by srivatsn** 2015-10-14 23:05 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate, Test
