### ISSUE TITLE
Intellisense on lambdas as method arguments in Visual Studio 2019 is not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35402] opened 2019-05-01 17:33 UTC
VSF_TYPE_MARKDOWN
```
public void Test(Action<IOption> act)
{
    ...
}

public void Consume()
{
    Test(opt => opt.
}        
```

The intellisense popup when dotting opt in the above example, is the intellisense for the action delegate and not the IOption parameter.

Doing the following works fine

`Action<IOption> act = opt => opt. Something();`

So it's only when used as a parameter for a method call that the problem exists.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/550945/intellisense-on-lambdas-as-method-arguments-in-vis.html
VSTS ticketId: 859078_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 07:53 PM (38 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ivanbasov** [comment] 2019-05-01 18:41
It is a duplicate of https://github.com/dotnet/roslyn/issues/35027. Should be fixed with https://github.com/dotnet/roslyn/pull/35067 in 16.1 Preview 3. Please let me know if there are any issue with it.

**Closed by ivanbasov** 2019-05-01 18:41 UTC
Labels: Area-IDE, Bug, Developer Community

**Comment by stevenxi** [comment] 2020-06-02 21:54
hi,

Is this issue fixed?

I'm still experiencing similar problem in V16.6.1

Screen shot attached.  I don't think it is expected.

![Capture2](https://user-images.githubusercontent.com/3340119/83573779-02a51380-a524-11ea-9e3a-b65fd8b63b67.JPG)
![Capture](https://user-images.githubusercontent.com/3340119/83573781-033daa00-a524-11ea-82fb-3d961dfabb7c.JPG)
