### ISSUE TITLE
Const identifier not bound

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#76403] opened 2024-12-12 20:47 UTC
```
unsafe struct S
{
    const int X = 4;
    public fixed uint hashTable[X];
}
```

Place caret on the second X and F12, it should go to def but it doesn't. Seems like it is not bound?

**Comment by CyrusNajmabadi** [comment] 2024-12-12 21:21
Dupe of https://github.com/dotnet/roslyn/issues/29224

**Closed by CyrusNajmabadi** 2024-12-12 21:21 UTC
Labels: Area-IDE, untriaged
