### ISSUE TITLE
IDE syntax coloring: missing keyword-like classification for binding-fallback-discards

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#18276] opened 2017-03-29 11:41 UTC
Perfectionist hell:

<img width="182" alt="screen shot 2017-03-29 at 14 39 25" src="https://cloud.githubusercontent.com/assets/194765/24452772/8becc0aa-148d-11e7-833a-a279e56b480b.png">

<img width="282" alt="screen shot 2017-03-29 at 14 36 37" src="https://cloud.githubusercontent.com/assets/194765/24452738/4eda1744-148d-11e7-9bec-76978cdd9e57.png">

Since this kind of "binding fallback" discards can change meaning if symbol named `_` suddenly appears in scope, syntax coloring can be especially important.

**Comment by Pilchie** [comment] 2017-03-29 19:10
@jcouv want to take a stab at this?

**Comment by jcouv** [comment] 2017-03-29 19:13
I'm a perfectionist too ;-)
Duplicate of https://github.com/dotnet/roslyn/issues/16667

**Closed by jcouv** 2017-03-29 19:13 UTC
Labels: Area-IDE, Bug

**Comment by jcouv** [comment] 2017-03-29 19:14
Thanks @controlflow for reporting this.

**Comment by jcouv** [comment] 2017-07-03 20:16
This was fixed by https://github.com/dotnet/roslyn/issues/18276 for 15.5
