### ISSUE TITLE
When Implementing Interface via Intellisense create methods with `<inheritdoc />` automatically

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53558] opened 2021-05-20 20:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-Implementing-Interface-via-Intellis/1419934)._

---
When using an interface in a class and choosing `Implement Interface` have it create the method with the XML summary of `<inheritdoc />` automatically so that the interfaces documentation is applied without the developer having to do the three forward strokes, undo the automatic text insertion and then add the `inheritdoc` tag

eg.

```csharp
public class MyClass : IMyClass
{
    /// <inheritdoc />
    public void MyMethodFromInterface()
    {
         throw new NotImplementedException();
    }
}
```

---
#### Feedback Bot on 5/12/2021, 11:25 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2021-05-20 20:51
The `<inheritdoc />` element is redundant in this case. Members which implement an interface member inherit documentation by default.

**Comment by sharwell** [comment] 2021-05-20 20:52
Duplicate of #47436

**Closed by sharwell** 2021-05-20 20:52 UTC
Labels: Area-IDE, untriaged

**Comment by dotMorten** [comment] 2021-06-03 17:58
@sharwell it's redundant? If I don't put anything there I get this build warning:

` warning CS1591: Missing XML comment for publicly visible type or member 'MyClass.MyMethodFromInterface'`

Also looking at the generated XML doc, this entire thing is now gone. Also DocFX will complain that doc is missing.

**Comment by sharwell** [comment] 2021-06-03 19:45
> warning CS1591

I would recommend disabling this warning. The compiler does not account for inheritdoc so you'll be prone to false positives with this warning. A tracking issue for the scenario is #42392.

> Also looking at the generated XML doc, this entire thing is now gone. Also DocFX will complain that doc is missing.

This is a DocFX bug/limitation. If it hasn't already been updated to account for implicit inheritdoc, it would be good to complete that.

**Comment by dotMorten** [comment] 2021-06-03 20:04
> I would recommend disabling this warning. The compiler does not account for inheritdoc so you'll be prone to false positives with this warning. A tracking issue for the scenario is #42392.

That's not really an option. We want to generate doc for our code, so disabling it would mean missing out where it is needed, and doing it per-member is A LOT of work. Might be easier to just post-process the entire thing. At least with cref it gets into the generated xml, and docfx does seem to some extent know that the member is coming from an interface, so again a post-process thing there could fix it. I'd just prefer things "just works" :-)
