### ISSUE TITLE
TreatWarningsAsErrors doesn't work on diagnostics configured via category

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53742] opened 2021-05-28 00:14 UTC
**Version Used**: 16.10.0

Diagnostics configured via category or for all analyzers remain as warnings even when TreatWarningsAsErrors is true. They should instead be shown as errors in the error list and during command-line builds just like they do when each diagnostic is individually configured by ID to be a warning.

We don't want to configure these as errors because we don't want them to show that way in the IDE or block inner loop building/testing. We don't want to configure each diagnostic individually as a warning because that's a lot of lines. But we also want TreatWarningsAsErrors to turn these into errors during CI builds to prevent clutter from building up in the error list.

```cs
class C
{
    void M() { }
}
```

```ini
root = true

[*.cs]
dotnet_analyzer_diagnostic.category-CodeQuality.severity = warning

# This doesn't work either
dotnet_analyzer_diagnostic.category.severity = warning

# Uncomment to see the warning start showing as an error in the Error List and in command line builds
# dotnet_diagnostic.IDE0051.severity = warning
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
```

**Comment by mavasani** [comment] 2021-12-22 09:42
Duplicate of https://github.com/dotnet/roslyn/issues/55541

**Comment by mavasani** [comment] 2021-12-22 09:42
https://github.com/dotnet/roslyn/pull/58460 has been created to fix the underlying issue.

**Closed by mavasani** 2021-12-22 09:42 UTC
Labels: Bug, Area-Analyzers
