### ISSUE TITLE
VB Wrong IDE0037 (Member name can be simplified) when member have same name of some variable

### ISSUE THREAD

**Issue by ehasis** [dotnet/roslyn#24315] opened 2018-01-18 19:38 UTC
**Version Used**:  15.5.4

**Steps to Reproduce**:
1. In any VB project, consider the following code:
```vb
Class Customer
    Public Property Age As Integer
End Class

Sub Main()
    Dim Age = 21
    Dim c = New Customer With {.Age = Age}
End Sub
```

**Expected Behavior**:
Don't suggest IDE0037 fix for the `.Age = Age` object initialization.

**Actual Behavior**:
Suggesting IDE0037 fix for the `.Age = Age` object initialization (grayed out) and if you apply the fix the code became invalid and don't compile.

It's important to mention that this behavior only appears if the initialization member have the same name of some other member (local, parameter, instance, shared, etc.)

**Note**: This problem doesn't manifest in C# code.

**Comment by jinujoseph** [comment] 2018-01-22 09:01
also reported [here](https://developercommunity.visualstudio.com/content/problem/182277/with-keyword-doesnt-function-properly-in-initialis.html)

**Comment by conficient** [comment] 2018-01-23 16:26
Duplicate see https://github.com/dotnet/roslyn/issues/23659

**Comment by sharwell** [comment] 2018-01-30 18:36
Duplicate of #23659

**Closed by sharwell** 2018-01-30 18:36 UTC
Labels: Area-IDE, Bug, Developer Community, help wanted
