### ISSUE TITLE
C#8 compiler reports CS8620 for IEnumerable<T?> after filtering for not null

### ISSUE THREAD

**Issue by Bonuspunkt** [dotnet/roslyn#38812] opened 2019-09-24 09:13 UTC
**Version Used**: 
dotnet-sdk-3.0.100

**Steps to Reproduce**:
enable nullable
```csharp
public static void Run()
{
    var enumerable = Enumerable.Range(1, 10).Select(i => i % 2 == 0 ? null : i.ToString());
    var notNulls = enumerable.Where(item => item != null);
    Check(notNulls);
}
private static void Check(IEnumerable<string> notNull) { }
```

**Expected Behavior**:
no warning

**Actual Behavior**:
Warning CS8620 Argument of type 'IEnumerable<string?>' cannot be used for parameter 'notNull' of type 'IEnumerable<string>' in 'void Check(IEnumerable<string> notNull)' due to differences in the nullability of reference types.

my current workaround is
```csharp
    var notNulls = enumerable.Where(item => item != null).Select(item => item!);
```

**Comment by huoyaoyuan** [comment] 2019-09-24 13:28
`Where(x => x != null)` is quite hard to deal for nullable analysis.
Potential solutions:
- A concrete method `IEnumerable<T> WhereNotNull<T>(IEnumerable<T?>)`, using yield return itself.
- Use `OfType<T>`. The semantic of `OfType` equals to null-check when applied to the same reference type.

**Comment by RikkiGibson** [comment] 2019-09-24 19:53
Related to #37468

**Comment by jcouv** [comment] 2019-12-13 19:51
Yes, this is a duplicate of https://github.com/dotnet/roslyn/issues/37468
I'll go ahead and close as such. Thanks

**Closed by jcouv** 2019-12-13 19:51 UTC
Labels: Resolution-Duplicate, Area-Compilers, Area-Language Design, New Language Feature - Nullable Reference Types
