### ISSUE TITLE
Intellisense not auto complete when writing code continously without enter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57646] opened 2021-11-09 09:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-not-auto-complete-when-writ/1574217)._

---
[severity:It bothers me. A fix would be nice]
VS 2022 latest, Console App Top-level statements.
Example code:

```
using System.Reflection;
FieldInfo f = null;
```
Now when i write continously without enter: `f.field==` then it will not auto complete to `f.FieldType`  or `f.FieldHandle`.
Even if i use arrow keys to select `FieldType` in the suggestion popup list, it will not auto complete !
I think it will also not auto complete for some other types when writing without enter (fastest way to write code !)
I have reproduced the problem in the video.

---
#### Feedback Bot on 11/9/2021, 01:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/9/2021, 06:14 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment] 2021-11-09 09:20
This repros for me with `FieldInfo` as in the users report, but not with other code 🤷‍♂️

**Comment by HyVong007** [comment] 2021-11-21 17:02
> This repros for me with `FieldInfo` as in the users report, but not with other code 🤷‍♂️

Can you reproduce the issues with `FieldInfo` ? And can you reproduce with other code ?

**Comment by davidwengier** [comment] 2022-03-24 00:36
Duplicate of https://github.com/dotnet/roslyn/issues/55806

**Closed** 2022-03-24 00:36 UTC
Labels: Bug, Resolution-Duplicate, Area-IDE, Investigation Required, Developer Community
