### ISSUE TITLE
Errors around referencing csc2.exe and vbc2.exe when opening Roslyn.sln in VS

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#593] opened 2015-02-17 20:15 UTC
When I open Roslyn.sln in VS, I always see the following errors in the error list. The errors (i.e. CS0009) don't show up during build on the command line.

![image](https://cloud.githubusercontent.com/assets/10579684/6236307/795c0008-b69e-11e4-89f8-9c94f9d66a88.png)

- Is it a compiler bug that the above CS0009 errors only show up in VS but don't fail command line build?

- Could we please fix up the VBCSCompilerTests project to not reference these native exes? The above errors are sticky in the error list and I find them quite annoying.

**Comment by agocke** [comment] 2015-02-17 20:26
Not a compiler bug -- project system bug.

**Comment by tmeschter** [comment] 2015-02-17 21:40
The basic problem is that the VBCSCompilerTests project depends on csc2 and vbc--not to build, but in order to run tests. There doesn't seem to be a good way to represent this in MSBuild, unfortunately.

**Comment by shyamnamboodiripad** [comment] 2015-02-19 00:50
I believe it is possible to indicate project dependencies via the solution properties dialog i.e. it should be possible to indicate that csc2 and vbc2 projects should be built before VBCSCompilerTests project without adding these reference. Looks like this is already correctly set up so far as dependency on csc2 is concerned - but the dependency on vbc2 has not been specified.

![image](https://cloud.githubusercontent.com/assets/10579684/6259970/8791fdd6-b78d-11e4-9422-308fd98f7ab1.png)

![image](https://cloud.githubusercontent.com/assets/10579684/6259987/a18e5c02-b78d-11e4-951e-1b3c3eb66f7b.png)

In what cases, would csc2 and vbc2 be missing at the point of running tests? If the above dependencies are correctly specified, shouldn't csc2 and vbc2 always be present at the time of running tests so long as one builds the VBCSCompilerTests project before running tests?

**Comment by shyamnamboodiripad** [comment] 2015-02-19 00:52
Regardless, I think we should also look into the above issue that causes this error to be displayed in VS but not during command line builds.

**Comment by jasonmalinowski** [comment] 2015-02-25 20:55
I'm not sure I follow what the problem is here. Once the project references are correctly specified, is there still a problem?

**Comment by shyamnamboodiripad** [comment] 2015-03-02 19:59
vbc2 and csc2 are native assemblies and we are adding references to these from the managed test project that contains tests for the compiler server. This leads to warnings / errors in the error list in VS that never go away (see original issue description for screenshot describing these errors). I *think* we are doing this to ensure that vbc2 and csc2 are available at the time when the tests are run. I am not sure what the fix is - but I find these errors / warnings annoying. I am sure others do too and I would like them to go away :)

**Comment by Pilchie** [comment] 2015-03-11 22:35
Note - the errors were a bug in the C++ targets that has been fixed in our new base drops.  The warnings are possibly annoying, but have lived forever, and I don't think enough people do this to worry about fixing it now.

Note that as of 2f77a182e77755349867c88e63c558788223d2c0, we don't have those projects anymore, so it won't be a dogfooding issue either.

**Closed by Pilchie** 2015-03-11 22:35 UTC
Labels: Area-IDE, Area-Infrastructure, Bug
