### ISSUE TITLE
Prevent Drop VB line Continuation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41663] opened 2020-02-13 18:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/913733/prevent-drop-vb-line-continuation.html)._

---
Hi,

I would like to know how can i prevent the visual studio from automatically remove the underscore in vb code for line continuation when i formatting my code.

---
#### Visual Studio Feedback System on 2/11/2020, 02:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by paul1956** [comment] 2020-02-14 00:54
You can just add a ' after the line continuation character. The IDE will add a space between _ '.

**Comment by jswolf19** [comment] 2020-03-12 08:00
I also have an issue with this. I have code that's been maintained for quite some time, and I don't want excessive changes to pollute my change history diffs. Adding a ' after the line continuation character is the same as removing the line continuation characters in this respect. 

Is there a reason this is not provided as a code style option?

**Comment by CyrusNajmabadi** [comment] 2020-03-12 19:41
> Is there a reason this is not provided as a code style option?

VB has long had hte behavior of just auto-fixing things up.  You should be able to disable this with: 

![image](https://user-images.githubusercontent.com/4564579/76560593-b7b4bc00-645e-11ea-9a76-8865d83cd17c.png)

**Comment by jswolf19** [comment] 2020-03-19 05:19
@CyrusNajmabadi
This feature does a lot of things I do want, though, like auto-tabbing the code that I'm fixing.
I have no problem with it affecting what I change and newer code, the problem is that it often affects more than what I've actually changed when editing code, due to temporarily un-closed code blocks. 

When I'm dealing with code that's likely been around since before .net, and is thousands of lines long, just changing a few lines near the top can cause a lot of "changes" to occur in the file.

C# has a lot of granular formatting options that vb.net just doesn't seem to have.

**Comment by CyrusNajmabadi** [comment] 2020-03-19 05:23
> When I'm dealing with code that's likely been around since before .net, and is thousands of lines long, just changing a few lines near the top can cause a lot of "changes" to occur in the file.

My recommendation would be to make a formatting-only change that gets the code in a consistent style with the VB coding patterns.   Commit that.

Then, from that point on, just make functional changes.  Taht way you don't mix/match functional and style changes that are hard to reconcile.

**Comment by jswolf19** [comment] 2020-03-19 06:57
@CyrusNajmabadi
Underbars were necessary for a while even after moving to .Net.
I shouldn't have to reformat old code just because the language changed and my productivity is suddenly being hindered by my productivity tools.

**Comment by jrmoreno1** [comment] 2020-04-16 00:20
@jswolf19 : this is an opportunity to remove unnecessary junk from your code, you should take advantage of it.  The under bars now help neither you nor the compiler.  Do it all at once and it should be clear in your history.

**Comment by jswolf19** [comment] 2020-04-16 01:00
@jrmoreno1 When I "remove unnecessary junk" should be my decision, not my editor's. I shouldn't have to go through all my files to find out what changed just because I upgraded my framework version.

Look, I'm not expecting this feature to be implemented, but it is a problem for me, so I wanted to add my use case as an example for why implementing such a feature would be useful for some users.

I am not asking for advice on how to deal with this, so if you aren't adding information relevant to the issue, then please don't tell me how to handle my code unsolicited.

**Comment by CyrusNajmabadi** [comment] 2020-04-16 01:05
> @jrmoreno1 When I "remove unnecessary junk" should be my decision, not my editor's.

It is.  If you don't want auto-cleanup you can disable that option.  But the idea of hte option is to automatically apply cleanup and best practices.  If that's not a desirable state for your, then you don't have to use it :)

**Comment by CyrusNajmabadi** [comment] 2020-04-16 01:06
> I shouldn't have to reformat old code just because the language changed and my productivity is suddenly being hindered by my productivity tools.

You don't have to.  As mentioned a few times, this is a long standing default behavior for VB that you can disable if you don't want for your codebase.

**Comment by jswolf19** [comment] 2020-04-16 06:04
> You don't have to. As mentioned a few times, this is a long standing default behavior for VB that you can disable if you don't want for your codebase. :)

While I've already said [why I don't feel that is an adequate solution](#issuecomment-600993788), I would also like to point out that this is an editor option, meaning that (unless I'm missing something) I can't turn it off only for the projects/solutions/files where I am dealing with legacy code.

**Comment by CyrusNajmabadi** [comment] 2020-04-16 06:31
> C# has a lot of granular formatting options that vb.net just doesn't seem to have.

yes, this has been the explicit design choice of the VB experience since... well.. forever :)  It's always been an all-or-nothing thing.  

> I would also like to point out that this is an editor option, meaning that (unless I'm missing something) I can't turn it off only for the projects/solutions/files where I am dealing with legacy code.

Yes.  That's correct.  It's all or nothing.  That's been an explicit design around VB for i think about 30 years now if i'm not mistaken :-/

**Comment by CyrusNajmabadi** [comment] 2022-11-01 19:21
Closing out as this is not planned.

**Closed by CyrusNajmabadi** 2022-11-01 19:21 UTC
Labels: Question, Area-IDE, Developer Community, Need Design Review, IDE-Formatter
