### ISSUE TITLE
Pasting into a raw string literal should ensure things stay parseable.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#59820] opened 2022-02-28 23:14 UTC
Examples of what this should do include:

1. if the content pasted includes a sequence of quotes longer than the delimiters then we shoudl grow the delimiters to be large enough to make the quotes not a problem.
2. lines of content need to be indented to fit the indentation of the literal.
3. if we start with a single-line raw string and paste contents that has newlines in it (or starts/ends with a quote), then convert to multiline raw strings.

This should all be done in two steps, so that an undo gives you the contents as if you had pasted things and not had anything get updated.

**Comment by jinujoseph** [comment] 2022-03-02 18:48
Duplicate of #31869

**Comment by jinujoseph** [comment] 2022-03-02 18:49
@CyrusNajmabadi can you check if this is dupe of 31869

**Comment by CyrusNajmabadi** [comment] 2022-03-02 18:50
Sort of.  For both it's about keeping things working fine when you paste content.  However, i would still like this tracked for the raw-string release.

**Comment by sharwell** [comment] 2022-03-02 21:07
Resolving as duplicate of prior feature request, since the earlier feature encompasses this issue with a more complete picture. Will update labels and milestone of the earlier issue.

**Closed by sharwell** 2022-03-02 21:07 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement
