### ISSUE TITLE
Support anonymous subtypes

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#1728] opened 2015-04-01 11:37 UTC
Syntax can be very similar to #13 but I think it should be extended to subtyping other classes as well.

Aside from general usefulness it will prevent potential interface overuse that could happen if only interfaces are supported via #13. I tend to use both interfaces and abstract classes depending on "A is B" vs "A supports B" semantic choices rather than making everything an interface "because DI".

http://www.jot.fm/issues/issue_2005_07/article1.pdf

>Note that as generalizations, interfaces compete with abstract classes. In fact, in
practice interfaces and abstract classes are sometimes used as if they were the same
concept. However, since abstract classes have the potential to pass on implementation to
their subclasses, they should be used if (and only if) the relationship to the subclasses is
genetic, i.e., if it is (or at least could be) based on the inheritance of internal structure, that
is, implementation. If on the other hand the relationship is based on pure function (or,
weaker still, on sameness of protocol), interfaces should be used. For instance, a linked
list and a dynamic array would normally not be genetically related (i.e., have no common
pieces of implementation), yet they share the interface of lists (specifying sequential
access to their elements).

I think Java supports this as "anonymous classes".

**Comment by svick** [comment] 2015-04-01 12:02
This seems to be a duplicate of #13, only with different (and IMO worse) syntax.

**Comment by dsaf** [comment] 2015-04-01 12:47
Actually the syntax is identical, but yeah it is a duplicate.

**Comment by gafter** [comment] 2015-04-14 02:51
Closing as a dup of #13.

Noted that @dsaf would like it extended to other types as well.

**Closed by gafter** 2015-04-14 02:51 UTC
Labels: Area-Language Design, Feature Request
