### ISSUE TITLE
Error CS8103 Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### ISSUE THREAD

**Issue by educanjr** [dotnet/roslyn#39676] opened 2019-11-04 19:59 UTC
netCore 3.0, VS 2019 v.16.3.2

Have a MVC netCore project, it have a huge ammount of partials views (1500), but this partials views only have html code (not razor code is needed). When I try to build the aplication VS showme the error: 
"Severity Code Description Project File Line Suppression State Suppression State Error CS8103 Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals." 
What can I do to fix this??

Regards

**Comment by tmat** [comment] 2019-11-06 05:33
This seems like ASP.NET Core issue, not Roslyn. There is a limit on amount of strings an assembly can contain. The compiler can't do anything about that.

**Comment by gafter** [comment] 2019-11-06 17:15
Closing as fixed in 16.4 due to https://github.com/dotnet/roslyn/pull/37915.  Please reopen if that is not in fact fixed.

**Closed by gafter** 2019-11-06 17:15 UTC
Labels: Area-Compilers

**Comment by tmat** [comment] 2019-11-07 04:43
See https://github.com/dotnet/roslyn/issues/25136#issuecomment-550736180

**Comment by Tuncu** [comment] 2020-04-29 09:30
Very annoying asp net core 2.2  vs 2019 or vs 2017 no metter. I couldn't find a way. adding one empty div couse problem. throw CS8103 Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals. and please as a suggestion do not tell me -simplyfiy string

**Comment by gr8tushar** [comment] 2020-05-05 10:17
@Tuncu - You mean to say that you were getting that error because of an empty div ?

**Comment by 3xtc** [comment] 2021-10-04 03:02
so how do we actually fix this problem ? i want string b64 but i get that shitty error. because b64 too long. surely this has been fixed 1 year down the track. i can share code if it helps but this is sorta stupid issue. i dont want to use a whole file in my project people can view or takei want to memorystream it. do i gotta update from vs 2019 16.11 or what?

**Comment by CyrusNajmabadi** [comment] 2021-10-04 03:25
@3xtc please open a new issue with the coffee you have that is causing this. Without now information we have no idea what you're running into our what would need to be done about it

**Comment by robinwilson16** [comment] 2023-01-10 00:37
I can confirm the issue remains in Visual Studio 2022 with a .NET 7 project
I needed to copy pages from a legacy website and create them here so it is lots of razor pages containing HTML. If I add one additional bit of text/HTML then I hit the error and it fails to compile, remove a bit of text and it is fine (or remove a folder of razor pages).

So essentially this means it is impossible to create a large website with many pages as eventually you hit the error and there is no fix except to have less HTML.

If I can't find a solution to the limitation I am going to have to split into two websites or use another programming language. 

I am not sure why more specific examples are needed or how these can be provided as the issue is that too much HTML equals broken project.

**Comment by MohanSF3988** [comment] 2023-01-22 17:56
![image](https://user-images.githubusercontent.com/121280890/213931897-927f7d6d-34b9-4bc5-8eaf-d5360c8f2db1.png)

Is there any fix to this issue

**Comment by robinwilson16** [comment] 2023-01-24 00:48
The only workaround I found was to switch compilation to happen at runtime rather than when the project is compiled.

This involves going into the project folder and editing the `.csproj` file and adding the following;

```
  <PropertyGroup>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>
```

With this change I was able to compile and publish the large project without hitting the error.

If you only want to apply it to the `Debug` profile then you can do this instead:
```
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>
```

Switching to runtime compilation is not ideal but it is the only workaround I could find until the issue is solved.

Saying that, as the issue has been left unaddressed since 2019 when it was closed as fixed and persisted through multiple .NET versions the chance of it being fixed seems uncertain.

**Comment by robinwilson16** [comment] 2023-08-22 21:39
Is it possible this could be re-opened and fixed please?
To replicate the error just add lorem ipsum to one or many razor pages in a new project and try to run it and you hit the error.
Not hard to replicate.

It now appears that the workaround to the bug stops identity from scaffolding where any customisations are not shown and even the correct layout is not loaded.

**Comment by anilpulugujja** [comment] 2023-09-14 20:34
I have the same issue, because there is no fix for this I am unable to migrate my legacy projects to the latest .Net framework.

**Comment by CyrusNajmabadi** [comment] 2023-09-14 23:31
@anilpulugujja @robinwilson16 this is not an issue with Roslyn.  Can you let ASP/razor know this as this appears to be something on their end?

**Comment by anilpulugujja** [comment] 2023-09-15 16:54
@CyrusNajmabadi  Thank you for responding, I checked the same issue in aspnetcore team, and there is a [closed issue](https://github.com/dotnet/aspnetcore/issues/20224) on this, as per @javiercn[ last comment, ](https://github.com/dotnet/aspnetcore/issues/20224#issuecomment-606618094)  he is asking to check with Roslyn team.

**Comment by robinwilson16** [comment] 2023-09-18 00:21
Could the Roslyn team possibly talk directly to the aspnetcore team? Hopefully they are friends and it will be a way of fixing this one day. A workaround is to split a project into multiple smaller projects but that is a workaround and not a fix.

It seems to be a simple issue of the compiler generating everything into a single string which ends up longer than supported so if a project is too large it crashes if the string gets too long so not ideal when you have deadlines and have to go off and get creative to get around the limitation/bug.

The challenge is getting someone to accept this is a bug and take responsibility in fixing it.

**Comment by CyrusNajmabadi** [comment] 2023-09-18 00:55
Afaict, the Roslyn compiler is correct here. The number of strings exceeds the total amount allowed.  You'd have to ask asp.net to change how they emit the code to use less string literals.

**Comment by anilpulugujja** [comment] 2023-09-18 01:25
@CyrusNajmabadi but the same string length is working fine in the ASP .Net MVC Web application project (.netframework 4.8), is there any way I can overcome this issue?

**Comment by CyrusNajmabadi** [comment] 2023-09-18 04:13
> @CyrusNajmabadi but the same string length is working fine in the ASP .Net MVC Web application project (.netframework 4.8), is there any way I can overcome this issue?

Find out what the different cases are generating and see why the new generation strategy it uses exacerbates the issue.  Maybe there's a way to get it to use the prior strategy.

**Comment by pancoaster** [comment] 2023-11-09 01:05
recursive gpt4 loops with api, running into this issue, any plans to resolve Error CS8103 or should I migrate from C# to C++?

**Comment by CyrusNajmabadi** [comment] 2023-11-09 01:17
@pancoaster You can store your strings in a myriad of different ways:

1. embedded resources
2. additional file with all the strings in it
3. additional files per string

There's no need to embed all your gpt4 strings as constants in a program you're compiling.

**Comment by harr1424** [comment] 2023-11-09 01:50
@CyrusNajmabadi I have encountered this error when creating an initial migration for my EF Core database. I am seeding a large amount of data from a file, which I have embedded in the assembly as a resource. Now when this resource is accessed in order to seed the database the EF Migrations script parses the data into the script resulting in a large amount of long string literals. It is unfortunate that Roslyn enforces this limit as it means I cannot programmatically seed my database using EF Core.

**Comment by pancoaster** [comment] 2023-11-09 01:52
the initial experiment prompt was a prompt for gpt4 to generate prompts for itself. Then i passed all the prompts back to GPT4 and pruned based on strict filtering for offensive contexts. Now there exists thousands of really good prompts (unlimited if for looped)  Each string triggers a recursive loop that generates 128k of context length for each prompt in a list of strings. I require all the strings at runtime, loading from text kept generating really weird errors. noticed worksheet failures and text overflowing when pasting some of this gpt4 output into Excel for sorting and pruning. Trying to paste the strings into text or json works for about 95% of the prompts, but some require manually writing modifications. Cant notice required modifications until strings are compiled by compiler. Thats why so many strings are specified in the code at compile time. Is it possible for Microsoft engineering to remove this limitation with a linked list data structure approach or something?

On Nov 8, 2023, at 8:17 PM, Cyrus Najmabadi ***@***.***> wrote:

﻿

@pancoaster<https://github.com/pancoaster> You can store your strings in a myriad of different ways:

  1.  embedded resources
  2.  additional file with all the strings in it
  3.  additional files per string

There's no need to embed all your gpt4 strings as constants in a program you're compiling.

**Comment by CyrusNajmabadi** [comment] 2023-11-09 03:36
> @CyrusNajmabadi I have encountered this error when creating an initial migration for my EF Core database. I am seeding a large amount of data from a file, which I have embedded in the assembly as a resource. Now when this resource is accessed in order to seed the database the EF Migrations script parses the data into the script resulting in a large amount of long string literals. It is unfortunate that Roslyn enforces this limit as it means I cannot programmatically seed my database using EF Core.

@harr1424 that sounds like an issue you need to take up with ef core. They do not need to store string constants in this fashion.

**Comment by CyrusNajmabadi** [comment] 2023-11-09 03:37
> the initial experiment prompt was a prompt for gpt4 to generate prompts for itself. Then returned all the prompts back to GPT4 and pruned based on strict filtering for offensive contexts. Now there exists thousands of really good prompts (unlimited if for looped)  a for Each loop triggers a recursive function that generates 128k of context length for each prompt in a list of strings. I require all the strings at runtime, loading from text kept generating really weird errors. noticed worksheet failures and text buffers overflowing when pasting some of this gpt4 output into Excel for sorting and pruning. Trying to paste the strings into text or json works for about 95% of the prompts, but some require manually writing modifications. Cant notice required modifications until strings are compiled by compiler. Thats why so many strings are specified in the code at compile time. Is it possible for Microsoft engineering to remove this limitation with a linked list data structure approach or something?
> 
> 

@pancoaster all of the above can be done writing out the values to another file (like a json, csv, ini, or any format you want). There is no need for the constants to be embedded in your source code. 

What you are describing is normal program data. There are tons of normal ways to store such things.

**Comment by thecreatorofthisthing** [comment] 2023-11-20 00:52
prepare for infinitely recursive generative pretrained model loops

[AssertionOutline for Role of Humor in Emotional Intelligence.docx](https://github.com/dotnet/roslyn/files/13405173/AssertionOutline.for.Role.of.Humor.in.Emotional.Intelligence.docx)

**Comment by Coastrnaut** [comment] 2023-12-02 15:53
Any way to compile with unlimited string literals in theory?

**Comment by CyrusNajmabadi** [comment] 2023-12-02 16:22
@Coastrnaut yes. Extract them into normal resources. There should be no effective limit at that point.

**Comment by Coastrnaut** [comment] 2023-12-11 04:23
I completely get the feasibility of the solution you have described @CyrusNajmabadi , however it is abundantly clear that you do not understand my request.  There exists infinite ways to solve a solution with code.  I seek removal the string literal limitation with future iterations of Roslyn.  If you point me where to look, I am happy to begin implementation. Check out these random GPT results;  in the future I want one where unlimited string literals compiled into a binary that equals a prime number is my overarching goal. Take this writing as CC 1.0
[In this symphony of semiconduct.docx](https://github.com/dotnet/roslyn/files/13630937/In.this.symphony.of.semiconduct.docx)

**Comment by CyrusNajmabadi** [comment] 2023-12-11 05:20
@Coastrnaut 

> I seek removal the string literal limitation with future iterations of Roslyn.

The limitations is not in Roslyn.  

>  Take this writing as CC 1.0

I'm not going ot open a random docx file.  You'll need to explain why you have to embed things as string-literals and cannot just use normal resources.

**Comment by CyrusNajmabadi** [comment] 2023-12-11 05:22
> edit: ref https://en.wikipedia.org/wiki/Illegal_number for an example of a prime number that equals a softwarez

None of that demonstrates why you have to embed these values as string-literals and cannot just a normal resource (which has no limitations).

**Comment by Coastrnaut** [comment] 2023-12-11 06:09
I apprecaite the response. This is just a pet GPT4 project for me.  The document attached includes results from GPT4 with cognition fees of a couple thousand. Why cant I just compile all the strings into one binary file? Then I want to modify the binary with a IDA or redgate to be equal to a prime number.  Thats kinda the general idea.  I would like all the strings/etc baked into the exe, not some resource file. I completely misunderstood the context of this entire thread and was assuming that Roslyn compiler limited the number of strings due to some tokenizer or intermediate file structure limitation.  Havent done the deep dive yet.  Where can I read more about how to compile unlimited strings in c#?

**Comment by CyrusNajmabadi** [comment] 2023-12-11 06:30
> Why cant I just compile all the strings into one binary file?

You can.  Just embed the strings as resources.  

> I would like all the strings/etc baked into the exe, not some resource file. 

That's what a resource is.  Data baked into the dll/exe.  Here's an example:

![image](https://github.com/dotnet/roslyn/assets/4564579/6e98875a-4f70-4320-9b17-d98a8764431b)

> Where can I read more about how to compile unlimited strings in c#?

Using resources.  As mentioned a few times.  There should be effectively no limit there.   

> Then I want to modify the binary with a IDA or redgate to be equal to a prime number.

You can do this.  Crack open the dll and modify it to your heart's content.

**Comment by Coastrnaut** [comment] 2023-12-11 06:32
will give it a try, thanks! i guess resources will be sufficient for incrementing towards a larger prime.

**Comment by CyrusNajmabadi** [comment] 2023-12-11 06:32
>  The document attached includes results from GPT4 with cognition fees of a couple thousand

All of that is trivially supported in C# through the mechanisms i already mentioned.  There's no need, or benefit to trying to embed those results as string *literals* in your program.  You can't once given a reason why this data needs to be literals and not normal resources.

> and was assuming that Roslyn compiler limited the number of strings due to some tokenizer

No.  This is nothing to do with roslyn.  This is part of ecma-335.  The string table (unrelated to the resources-table i showed above) has certain limits.

**Comment by CyrusNajmabadi** [comment] 2023-12-11 06:33
> will give it a try, thanks! i guess resources will be sufficient for incrementing towards a larger prime.

None of this has anything to do with the constant string table limits or the resource-table.  It's unclear at all why such computation needs either.

**Comment by Coastrnaut** [comment] 2023-12-11 06:34
Have you ever compiled a code into prime?

**Comment by CyrusNajmabadi** [comment] 2023-12-11 06:36
Depends on what you mean.  If you mean assigning some number with an associated program code, then sure.  But that doesn't need embedded constant literals.  As above, if you want these capabilities, you're going to need to explain in detail what you're trying to, why you are trying to go about it this way, and what actual issues you're running into.

**Comment by Coastrnaut** [comment] 2023-12-11 06:48
I require this to compile one text file as C# text into a binary.  The exact Size (in decimal) of the binary will be equal to a large prime number in base 10, divisible by only one and itself.  For instance, let explorer.exe equal ~50million.  So I would want to edit the code to compile to and exact prime slightly larger than ~50million. Therefore creating a replicable unique prime from C# that compiles from one text file.

**Comment by CyrusNajmabadi** [comment] 2023-12-11 06:57
None of that needs embedded string literals.  :)
