### ISSUE TITLE
My project making use of Source Generators breaks with `Microsoft.CodeAnalysis.CSharp.Workspaces` > 3.8.0

### ISSUE THREAD

**Issue by AntonC9018** [dotnet/roslyn#54235] opened 2021-06-19 20:26 UTC
**Version Used**: 
`dotnet` CLI version 5.0.101, Windows 7, fresh VS 2019 installation.

**Steps to Reproduce**:
[See the minimal example](https://github.com/AntonC9018/Generators_Issue). 
It has two relevant branches: one broken and the other one working.
The sole difference between the branches is essentially in the version used.
I base my example on [this repo](https://github.com/davidwengier/SourceGeneratorTemplate).

**Expected Behavior**:
The type `Foo` is generated and included into the compilation. Running the example should print:
```
$ dotnet run
Types in this assembly:
Foo
Consumer.Program
```

**Actual Behavior**:
The code is generated successfully with `Microsoft.CodeAnalysis.CSharp.Workspaces` set to 3.8.0, but not while it is set to any higher version.
In this case I'm either getting a warning at build:
```
$ dotnet run
CSC : warning CS8032: An instance of analyzer Generator.MyGenerator cannot be created from D:\Coding\C#\Generators_Issue\Generator\bin\Debug\netstandard2.0\Generator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [D:\Coding\C#\Generators_Issue\Consumer\Consumer.csproj]
Types in this assembly:
Consumer.Program
```
Or not even getting a warning, or the generated type, on subsequent compilations.

**Notes**:
Played around with `Microsoft.CodeAnalysis.Analyzers`'s version, setting it from 3.3.1 to 3.3.2 and back, but that did not seem to have any impact.

**Comment by AntonC9018** [comment] 2021-06-20 23:32
This most definitely has something to do with the MSBuild location migration.

**Comment by alexrosenfeld10** [comment] 2021-07-01 11:03
I'm seeing the same problem. Build works in a docker container, but locally on my (and 3 coworkers, mac and windows alike) it fails with:

```
CSC : warning CS8032: An instance of analyzer My.Company.SomeGenerator cannot be created from /Users/me/dev/git/my-repo/src/My.Company.GeneratorProject/bin/Debug/netstandard2.1/My.Company.SomeGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
```

**Comment by jaredpar** [comment] 2021-07-13 20:57
Guessing this is a duplicate of #54710. Essentially using an incompatible version of the APIs in an older SDK. Will let @chsienki confirm

**Comment by chsienki** [comment] 2021-08-13 21:50
Closing as a dupe of #54710

**Closed by chsienki** 2021-08-13 21:50 UTC
Labels: Bug, Area-Compilers, New Feature - Source Generators
