### ISSUE TITLE
VB: inline a local updates code that should be left unchanged

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#18491] opened 2017-04-06 04:43 UTC
In the code below (from `CompilationEmitTests.vb`), inline `peImage`
I don't expect irrelevant code to be rewritten. But inlining the local produces much more complicated code above (which I wouldn't expect to change at all).

Before:
![image](https://cloud.githubusercontent.com/assets/12466233/24738131/8b9f79e2-1a48-11e7-805b-1c4e4044d330.png)

After:
![image](https://cloud.githubusercontent.com/assets/12466233/24738143/9fd81e46-1a48-11e7-9ce8-1963ccd78f36.png)

```VB
        <Fact>
        Public Sub VerifyRefAssembly()
            Dim source = "
Public MustInherit Class PublicClass
    Public Sub PublicMethod()
        System.Console.Write(""Hello"")
    End Sub
    Private Sub PrivateMethod()
        System.Console.Write(""Hello"")
    End Sub
    Protected Sub ProtectedMethod()
        System.Console.Write(""Hello"")
    End Sub
    Friend Sub InternalMethod()
        System.Console.Write(""Hello"")
    End Sub
    Public MustOverride Sub AbstractMethod()
End Class"
            Dim comp As Compilation = CreateCompilation(source, references:={MscorlibRef},
                            options:=TestOptions.DebugDll.WithDeterministic(True))

            Dim verifier = CompileAndVerify(comp, emitOptions:=EmitOptions.Default.WithEmitMetadataOnly(True), verify:=True)

            ' verify metadata (types, members, attributes) of the regular assembly
            Dim realImage = comp.EmitToImageReference(EmitOptions.Default)
            Dim compWithReal = CreateCompilation("", references:={MscorlibRef, realImage},
                            options:=TestOptions.DebugDll.WithMetadataImportOptions(MetadataImportOptions.All))
            Dim realAssembly = compWithReal.SourceModule.GetReferencedAssemblySymbols().Last()
            AssertEx.SetEqual(realAssembly.GlobalNamespace.GetMembers().Select(Function(m) m.ToDisplayString()),
                {"<Module>", "PublicClass"})

            AssertEx.SetEqual(
                DirectCast(realAssembly.GlobalNamespace.GetMember("PublicClass"), NamedTypeSymbol).GetMembers().
                                Select(Function(m) m.ToTestDisplayString()),
                            {"Sub PublicClass.PublicMethod()", "Sub PublicClass.PrivateMethod()",
                                "Sub PublicClass.InternalMethod()", "Sub PublicClass.ProtectedMethod()",
                                "Sub PublicClass.AbstractMethod()", "Sub PublicClass..ctor()"})

            AssertEx.SetEqual(realAssembly.GetAttributes().Select(Function(a) a.AttributeClass.ToTestDisplayString()),
                {"System.Runtime.CompilerServices.CompilationRelaxationsAttribute",
                    "System.Runtime.CompilerServices.RuntimeCompatibilityAttribute",
                    "System.Diagnostics.DebuggableAttribute"})

            ' verify metadata (types, members, attributes) of the metadata-only assembly
            Dim emitMetadataOnly = EmitOptions.Default.WithEmitMetadataOnly(True)
            CompileAndVerify(comp, emitOptions:=emitMetadataOnly, verify:=True)

            Dim metadataImage = comp.EmitToImageReference(emitMetadataOnly)
            Dim compWithMetadata = CreateCompilation("", references:={MscorlibRef, metadataImage},
                            options:=TestOptions.DebugDll.WithMetadataImportOptions(MetadataImportOptions.All))
            Dim metadataAssembly As AssemblySymbol = compWithMetadata.SourceModule.GetReferencedAssemblySymbols().Last()
            AssertEx.SetEqual(metadataAssembly.GlobalNamespace.GetMembers().Select(Function(m) m.ToDisplayString()),
                {"<Module>", "PublicClass"})

            AssertEx.SetEqual(
                DirectCast(metadataAssembly.GlobalNamespace.GetMember("PublicClass"), NamedTypeSymbol).GetMembers().
                                Select(Function(m) m.ToTestDisplayString()),
                            {"Sub PublicClass.PublicMethod()", "Sub PublicClass.PrivateMethod()",
                                "Sub PublicClass.InternalMethod()", "Sub PublicClass.ProtectedMethod()",
                                "Sub PublicClass.AbstractMethod()", "Sub PublicClass..ctor()"})

            AssertEx.SetEqual(metadataAssembly.GetAttributes().Select(Function(a) a.AttributeClass.ToTestDisplayString()),
                {"System.Runtime.CompilerServices.CompilationRelaxationsAttribute",
                    "System.Runtime.CompilerServices.RuntimeCompatibilityAttribute",
                    "System.Diagnostics.DebuggableAttribute"})

            Dim peImage = comp.EmitToArray(emitMetadataOnly)
            MetadataReaderUtils.AssertEmptyOrThrowNull(peImage)

            ' verify metadata (types, members, attributes) of the metadata-only assembly
            Dim emitRefOnly = EmitOptions.Default.WithEmitMetadataOnly(True).WithIncludePrivateMembers(False)
            CompileAndVerify(comp, emitOptions:=emitRefOnly, verify:=True)

            Dim refImage = comp.EmitToImageReference(emitRefOnly)
            Dim compWithRef = CreateCompilation("", references:={MscorlibRef, refImage},
                            options:=TestOptions.DebugDll.WithMetadataImportOptions(MetadataImportOptions.All))
            Dim refAssembly As AssemblySymbol = compWithRef.SourceModule.GetReferencedAssemblySymbols().Last()
            AssertEx.SetEqual(refAssembly.GlobalNamespace.GetMembers().Select(Function(m) m.ToDisplayString()),
                {"<Module>", "PublicClass"})

            AssertEx.SetEqual(
                DirectCast(refAssembly.GlobalNamespace.GetMember("PublicClass"), NamedTypeSymbol).GetMembers().
                                Select(Function(m) m.ToTestDisplayString()),
                            {"Sub PublicClass..ctor()", "Sub PublicClass.PublicMethod()",
                                "Sub PublicClass.ProtectedMethod()", "Sub PublicClass.AbstractMethod()"})

            AssertEx.SetEqual(refAssembly.GetAttributes().Select(Function(a) a.AttributeClass.ToTestDisplayString()),
                {"System.Runtime.CompilerServices.CompilationRelaxationsAttribute",
                    "System.Runtime.CompilerServices.RuntimeCompatibilityAttribute",
                    "System.Diagnostics.DebuggableAttribute",
                    "System.Runtime.CompilerServices.ReferenceAssemblyAttribute"})

            MetadataReaderUtils.AssertEmptyOrThrowNull(comp.EmitToArray(emitRefOnly))
        End Sub
```

**Comment by Pilchie** [comment] 2017-04-06 21:08
Is this a dupe of https://github.com/dotnet/roslyn/issues/7504?

**Comment by jcouv** [comment] 2017-04-06 22:31
Could be related, but this example seems worse as it replaces a simple call to an extension method `Select` with `Linq.ImmutableArrayExtensions.Select`.

**Comment by Pilchie** [comment] 2017-04-06 23:00
That's still just expand/reduce being called.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 22:43
We are not changing vb experiences now.

**Closed by CyrusNajmabadi** 2024-10-19 22:43 UTC
Labels: Bug, Area-IDE
