### ISSUE TITLE
C# compiler freezes in certain platform analysis scenarios.

### ISSUE THREAD

**Issue by nickwhaley** [dotnet/roslyn#51652] opened 2021-03-04 01:34 UTC
SDK 5.0.200. Visual Studio 16.9.0.
Compile this:

```csharp
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading.Tasks;

static async Task Main(string[] args) {
	while (true)
		try {
			await Task.Delay(1000);
			if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
				Test();
		} catch {
			if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
				Test();
			throw;
		}
}
[SupportedOSPlatform("windows")]
static void Test() { }
```

It will lock up and never finish compiling. Even when platform analysis is disabled (CA1416), it still locks up.

In previous versions of the SDK, you would get the following nonsensical warning instead of freezing, and I just had disabled CA1416, which used to be a workaround.

`Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.LiteralOperation''.	ConsoleApp1	C:\Users\tfs\source\repos\ConsoleApp1\ConsoleApp1\CSC	1	Active`

**Comment by Youssef1313** [comment] 2021-03-04 02:39
@buyaa-n @sharwell Looks like another repro of the same issue?
Could someone move it to dotnet/roslyn-analyzers?

**Comment by jaredpar** [comment] 2021-03-04 04:21
Thanks for reporting. This looks like another dupe of https://github.com/dotnet/roslyn-analyzers/issues/4920.

**Closed by jaredpar** 2021-03-04 04:21 UTC
Labels: Area-Compilers, untriaged

**Comment by Youssef1313** [comment] 2021-03-06 17:32
This is being fixed in https://github.com/dotnet/roslyn-analyzers/pull/4928. It was discovered it's different than dotnet/roslyn-analyzers#4920.
