### ISSUE TITLE
netcore sdk 3.1.101 can not use Microsoft.CodeAnalysis 3.7 package.

### ISSUE THREAD

**Issue by yuanfeimyob** [dotnet/roslyn#54625] opened 2021-07-05 12:17 UTC
**Version Used**: 
dotnet sdk 3.1.101
**Steps to Reproduce**:

1. create project with dotnet new webapi
2. add microsoft.entityframeworkcore.analyzers, 5.0.6.
3. build the project.

**Expected Behavior**:
build without issue.

**Actual Behavior**:
  An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /Users/xxx/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.6/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..

**Comment by Youssef1313** [comment] 2021-07-06 05:56
I guess you'd need to upgrade the SDK to a newer version.

**Comment by yuanfeimyob** [comment] 2021-07-07 01:19
thanks for your reply, yes upgrade fixed the warning. is there a way to know what is the root cause of this warning, or a way check a package's dependency on sdk level.  in nuget both package involved here just says net standard 2.0.

**Comment by jaredpar** [comment] 2021-07-12 18:32
Closing as a duplicate of #54108. That is the issue we are tracking that will enable analyzers / generators to be more version resilient here.

**Closed by jaredpar** 2021-07-12 18:32 UTC
Labels: Area-Compilers, untriaged
