### ISSUE TITLE
If a method is inaccessible due to its protection level, then Ctrl + . should make it public

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58684] opened 2022-01-06 22:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/If-a-method-is-inaccessible-due-to-its-p/1619359)._

---
If a method is inaccessible due to its protection level, and the source code of the method is editable (i.e. it's not a referenced assembly), then when I press `Ctrl` + `.` I should be prompted with the ability to make it `public` or at least accessible (i.e. `private` to `internal` if that does the trick) and not have to open the method and change the visibility modifier by hand.

![image.png](https://user-images.githubusercontent.com/5833655/148625661-b54f1e4c-e780-43c2-9586-192326072eef.png)

---
#### Feedback Bot on 12/22/2021, 00:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by RikkiGibson** [comment] 2022-01-08 01:56
Looks like this was previously discussed in #31837

**Comment by jinujoseph** [comment] 2022-01-13 23:47
Duplicate of #31837

**Closed by jinujoseph** 2022-01-13 23:47 UTC
Labels: Area-IDE, untriaged
