### ISSUE TITLE
Collection expressions formatting issue

### ISSUE THREAD

**Issue by Badaxis** [dotnet/roslyn#71708] opened 2024-01-18 18:14 UTC
**Version Used**: 
VS 2022 17.8.5

I have an issue with the automatic formatting of collection expressions in C#, everything is put on a new line while i want to keep the layout i write. It was not an issue when initializing in .net 6 with ```{ }``` but it is now in .net 8 with ```[ ]```.
I can't find where to alter this behavior; I'm sorry if this is a miss on my part.

Example, this:
 ```c#
float[] triangleData =
[
    -1f, -1f, 0f,
    +1f, -1f, 0f,
     0f, +1f, 0f
];
```
Turns into this after Format Document:
```c#
float[] triangleData =
[
    -1f,
    -1f,
    0f,
    +1f,
    -1f,
    0f,
    0f,
    +1f,
    0f
];
```
I'll add that it doesn't matter if I use literals (like in this example) or variables.

**Comment by DoctorKrolic** [comment] 2024-01-18 18:47
Duplicate of https://github.com/dotnet/roslyn/issues/70951

**Closed** 2024-01-18 19:22 UTC
Labels: untriaged
