### ISSUE TITLE
Pseudo-Static Extensions [CLR Support?]

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8164] opened 2016-01-25 22:04 UTC
**Proposal (Rough)**

A `Static Extensions`, extend (add) a static member (not instance members) of an object type,

Could this be supported by having an object that provides them of the (target) object's behalf.

``` C#
class StaticExtensionManager
{
  var _Members  = new Dictionary< Type, VTable >();

  TResult Invoke<T>( T obj, member mem )
  {
    try
    {
      return ObjectInvoker( obj , mem )
    }
    catch ( MissingMethodException ex)
    {
      if( _members.Contains( GetType(T) )
      {
        return ObjectInvoker( _member(GetType(T)) , mem );
      }
      else
      {
        throw new MissingMethodException()
      }
    }
  }


}
```

The CLR / Compiler creates and instance of this class (`StaticExtensionManager`).

1, Does the target object already have a member that matches the signature? Then use that.
2. Does the `StaticExtenstionManager` object provide an implementation? Then use that.
3. No, report error.

**Comment by HaloFour** [comment] 2016-01-25 22:54
This is a dupe of #996, I think.  This "proposal" is incredibly incoherent.

**Comment by AdamSpeight2008** [comment] 2016-01-25 23:21
@HaloFour #996 is a suggestion, this a possible implementation proposal,

**Comment by HaloFour** [comment] 2016-01-25 23:42
@AdamSpeight2008 I'll wait until it even remotely resembles one, then.  So far what little there is makes no sense yet manages to be much more complicated than it should ever need to be.

**Comment by gafter** [comment] 2017-03-20 20:12
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Closed by gafter** 2017-03-20 20:12 UTC
Labels: Area-Language Design, Discussion
