### ISSUE TITLE
Multi-Line String Literal + Indentation = Gotcha

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#2231] opened 2015-04-24 02:46 UTC
VB.net will support multi-line string literals, but it has introduce a gotcha has well.
That of significant whitespace.  After the pressing return to add a newline within the string the following text is indented to align with the current indentation level. But that automatic indentation isn't marked as insignificant. The issue also accord when XML Literals were added to the language.

**Repo Code**
```vb
Imports System
public class C 
    public Sub M() 
        Dim x = "1
        2
        3
        4
        5
        "
        Console.Write(x)
    end sub
  
End Class
```

**Expectation**
```
1
2
3
4
5

```

**Actual**
```
1
        2
        3
        4
        5

```

**Work Around**
A work around is to left-align the string literal.
```
Imports System
public class C 
    public Sub M() 
        Dim x = _
"1
2
3
4
5
"
        Console.Write(x)
    end sub
  
End Class
```

**Desired Resolution**

1. Have the string literal be aware of the indentation level and take it into account.
2. On pressing Return ignore the indentation level, and place the carat at the left-hard margin.

**Comment by gafter** [comment] 2015-04-24 16:35
The current behavior is as designed. I don't believe we would like to change it (and the time is very short in which we could possibly change it).

/cc @AnthonyDGreen @ljw1004 Please chime in if you disagree with this resolution.

**Comment by ljw1004** [comment] 2015-04-24 16:54
I disagree with the resolution! I think we should change the IDE indent behavior, exactly as Adam suggested!

**Comment by HaloFour** [comment] 2015-04-24 17:02
Are there any languages that are known to strip indentation from multi-line strings?  Even Python considers the indentation a part of the string.  CoffeeScript doesn't, but CoffeeScript also strips out the newlines and compacts the whitespace.

**Comment by tmat** [comment] 2015-04-24 17:22
In the latest build the IDE doesn't indent inside a multiline string.

**Comment by AdamSpeight2008** [comment] 2015-04-24 17:22
I be happy with as a minimum resolution 2 as it's similar behaviour to what you'd expect from a text editor / word processor. The user still can insert the spaces if it required. Also (I think) it wouldn't need as much to implement then need for resolution 1 *(I haven't researched it further)*.

@HaloFour  It's mainly about not surprising the user.

**Comment by HaloFour** [comment] 2015-04-24 17:26
@AdamSpeight2008 With the IDE auto-indenting I can see that being annoying.  C# doesn't indent in those strings.  From @tmat 's comment it looks like it will be resolved.

**Comment by AnthonyDGreen** [comment] 2015-04-24 17:27
This is an IDE behavior bug as Adam and Lucian have noted. We wouldn't change the language semantics for this but the indentation shouldn't be automatically inserted.

**Comment by gafter** [comment] 2015-04-24 17:34
As I understand the consensus of the conversation, we'd like the IDE *not* to auto-indent after the first newline in a string literal.

**Comment by HaloFour** [comment] 2015-04-24 17:40
@gafter Sounds about right.  That's how VS2013 behaves with verbatim string literals in C#.  Sounds like it's already fixed, we just don't have that build.

**Comment by AdamSpeight2008** [comment] 2015-04-24 17:42
The plain literal works as desired. String Interpolation Literals don't.

**Comment by Pilchie** [comment] 2015-04-25 20:58
@basoundr - can you close with the commit where this was fixed?

**Comment by ljw1004** [comment] 2015-04-26 01:31
Just to confirm what I'm expecting:

* In C# currently, when you write
```var x = @"```
and hit enter, then the IDE provides no indent.

* In C# currently, when you write `var x = $@"` and hit enter, you once again get no indent.

* In VB currently, when you write `Dim x = "` and hit enter, you once again get no indent.

* In VB currently, when you write `Dim x = $"` and hit enter, **then you do get an indent**

It's that final behavior that's the bug, that should be fixed.

**Comment by Pilchie** [comment] 2015-04-26 03:10
Oh, you're right @ljw1004.  We should fix that last case to not indent.

**Closed** 2015-04-29 16:51 UTC
Labels: Area-IDE, Bug, Language-VB

**Comment by OJacot-Descombes** [comment] 2019-08-12 12:14
Please see (and upvote) my suggestion for the Visual Studio IDE: [Indent multi-line verbatim strings](https://developercommunity.visualstudio.com/idea/602807/indent-multi-line-verbatim-strings.html).
