### ISSUE TITLE
Non-exhaustive switch expression w/ tuple deconstruction causes csc.exe to fail with exit code -2146232797

### ISSUE THREAD

**Issue by mikechristiansenvae** [dotnet/roslyn#64370] opened 2022-09-29 19:23 UTC
**Version Used**: Issue occurs with both .NET 6.0.400 and .NET 7.0.100-preview.7.22377.5

**Steps to Reproduce**:

1. Copy/paste the below code into a C# file

```csharp
void Bar(int a, int b)
{
    _ = (a, b) switch
    {
        // (not (0 or 1), 1) => (1, 1),
        // ^---- Uncommenting this line allows compilation to succeed
        (0, 1) => (1, 0),
        (1, 1) => (1, 0),
        (_, > 1) => (a, b - 1),
        (_, <= 0) => (a, 0),
    };
}
```

**Expected Behavior**:

An error/warning is produced that indicates the switch expression is non-exhaustive, since case `(not (0 or 1), 1)` is not handled.

**Actual Behavior**:

In Visual Studio 2022, Version 17.3.1:

```
Build started...
1>------ Build started: Project: Repro, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.exe" exited with code -2146232797.
1>Done building project "Repro.csproj" -- FAILED.
```

In both `dotnet build` and Rider 2022.2.3 (Build #RD-222.4167.23):

```
  Microsoft.CSharp.Core.targets(79, 5): Process terminated. System.ArgumentException: Value does not fall within the expected range.
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.NumericValueSet`2.Microsoft.CodeAnalysis.CSharp.IValueSet.get_Sample()
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SampleValueString(IValueSet remainingValues, TypeSymbol type, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.<SamplePatternForTemp>g__tryHandleTuplePattern|2_5(Boolean& unnamedEnumValue, <>c__DisplayClass2_0&)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalFunctionStatement(LocalFunctionStatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgramCompilationUnit(CompilationUnitSyntax compilationUnit, SynthesizedSimpleProgramEntryPointSymbol simpleProgram, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
  Microsoft.CSharp.Core.targets(79, 5):    at System.Environment.FailFast(System.String, System.Exception)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportAndPropagateUnlessCanceled(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.ValueSetFactory+NumericValueSet`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.CSharp.ValueSetFactory+IntTC, Microsoft.CodeAnalysis.CSharp, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Microsoft.CodeAnalysis.CSharp.IValueSet.get_Sample()
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SampleValueString(Microsoft.CodeAnalysis.CSharp.IValueSet, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Boolean, Boolean ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(Microsoft.CodeAnalysis.CSharp.BoundDagTemp, System.Collections.Generic.Dictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<System.ValueTuple`2<Microsoft.CodeAnalysis.CSharp.BoundDagTest,Boolean>>>, System.Collections.Generic.Dictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.BoundDagEvaluation>>, Boolean, Boolean ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.<SamplePatternForTemp>g__tryHandleTuplePattern|2_5(Boolean ByRef, <>c__DisplayClass2_0 ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(Microsoft.CodeAnalysis.CSharp.BoundDagTemp, System.Collections.Generic.Dictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<System.ValueTuple`2<Microsoft.CodeAnalysis.CSharp.BoundDagTest,Boolean>>>, System.Collections.Generic.Dictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.BoundDagEvaluation>>, Boolean, Boolean ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(Microsoft.CodeAnalysis.CSharp.BoundDagTemp, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode, Boolean, Boolean ByRef, Boolean ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDag ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.LabelSymbol ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Boolean)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Boolean)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Boolean, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalFunctionStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgramCompilationUnit(Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedSimpleProgramEntryPointSymbol, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.BoundNode, Boolean, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, Boolean ByRef, InitialState ByRef)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
  Microsoft.CSharp.Core.targets(79, 5):    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
  Microsoft.CSharp.Core.targets(79, 5):    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
  Microsoft.CSharp.Core.targets(79, 5):    at System.Threading.ThreadPoolWorkQueue.Dispatch()
  Microsoft.CSharp.Core.targets(79, 5):    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  Microsoft.CSharp.Core.targets(79, 5): System.ArgumentException: Value does not fall within the expected range.
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.NumericValueSet`2.Microsoft.CodeAnalysis.CSharp.IValueSet.get_Sample()
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SampleValueString(IValueSet remainingValues, TypeSymbol type, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.<SamplePatternForTemp>g__tryHandleTuplePattern|2_5(Boolean& unnamedEnumValue, <>c__DisplayClass2_0&)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause, Boolean& unnamedEnumValue)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalFunctionStatement(LocalFunctionStatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgramCompilationUnit(CompilationUnitSyntax compilationUnit, SynthesizedSimpleProgramEntryPointSymbol simpleProgram, BindingDiagnosticBag diagnostics)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
  Microsoft.CSharp.Core.targets(79, 5):    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
```

**Comment by mikechristiansenvae** [comment] 2022-09-29 19:29
Note: This issue is similar to issue #57148

**Comment by jaredpar** [comment] 2022-10-10 23:02
Looks like a dupe of #64399. Going to let that be the primary as we've already assigned it all out (sorry triaging in wrong order today).

**Closed by jaredpar** 2022-10-10 23:02 UTC
Labels: Area-Compilers, untriaged
