### ISSUE TITLE
IDE0007 and IDE0008 do not work for 'Fix all occurrences'

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#17183] opened 2017-02-16 19:00 UTC
Attempting to 'Fix all occurrences' for IDE0007 (Use 'var' instead of explicit type) or IDE0008 (Use explicit type instead of 'var') results in Preview Changes dialog that contains no entries:

![image](https://cloud.githubusercontent.com/assets/10487869/23036247/ed95aa82-f436-11e6-82e5-e6537ebad583.png)

**Comment by CyrusNajmabadi** [comment] 2017-02-26 21:57
Not repro for me:

![image](https://cloud.githubusercontent.com/assets/4564579/23344106/75376dee-fc2b-11e6-8a95-3cd068e7f8f3.png)

**Comment by CyrusNajmabadi** [comment] 2017-02-26 21:57
Do you have an example where this happens?  @mavasani Do you know of any issues with 'Fix all' that would prevent it working?

**Comment by tannergooding** [comment] 2017-04-10 15:22
Reopening, this appears to only impact .NET Core projects.

A similar customer feedback bug is here: https://developercommunity.visualstudio.com/content/problem/21740/simplify-member-access-is-not-working-with-net-cor.html

**Comment by mavasani** [comment] 2017-04-10 15:46
We have seen reports of FixAll not working at times for NetCore projects, but none for NetFx projects. I am wondering if this is some race in the new project system. Tanner, do we have a repro?

**Comment by tannergooding** [comment] 2017-04-10 16:12
Customer bug has one.

For this bug it's essentially the same:
1. Create .NET Core Project
2. Turn on Suggestion for `For built-in types prefer 'var'`
3. Write code that triggers the lightbulb (such as `class C { void M() { int x = 0; } }`)
4. Try to fix all occurrences for the suggested lightbulb

**Comment by AlexanderTaeschner** [comment] 2017-04-18 15:09
I see the same behaviour also for classic .NET library and windows forms projects, but only when "Enable full solution analysis" is selected.

**Comment by sharwell** [comment] 2017-04-28 19:57
@tannergooding There are two reasons you could have seen the behavior you did:

1. You had the diagnostic severity for the item set to Hidden (None in Tools|Options). Fix All is disabled in this case but still shows an empty preview. This is a nuisance and #19068 changes the behavior for one specific analyzer to avoid this situation.
2. You used **.editorconfig** to set the severity to suggestion, warning, or error. In this case the empty preview is due to #19089.

**Comment by tannergooding** [comment] 2017-04-28 20:01
@sharwell, this repro'd in neither of those two cases. As in the repro above, we explicitly turn the diagnostic severity to "suggestion" (from a new .NET Core project which does not have an .editorconfig). This causes the initial lightbulb to display. Then selecting "Fix all" fails.

**Comment by tannergooding** [comment] 2017-04-28 20:01
It is continuing to reproduce in the latest dogfood build of VS.

**Comment by sharwell** [comment] 2017-04-28 20:03
@tannergooding Can you clarify *exactly* how/where you set the severity to Suggestion? Just to make sure I have an accurate set of steps.

**Comment by tannergooding** [comment] 2017-04-28 20:06
Tools->Options->Text Editor->C#->Code Style->'var' preferences:->For built-in types = Prefer 'var'/Suggestion (it also repros under 'Warning' or 'Error')

**Comment by manchas** [comment] 2017-05-15 14:01
I have this issue reported somewhere else (https://developercommunity.visualstudio.com/content/problem/24592/fix-all-ocurrences-in-project-failling-with-black.html). There, it was closed as a duplicate by @sharwell. 
The difference between this issue and mine is that I don't have a single dotNet Core project in my solution, 100% of my 153 projects are targeting framework 4.6.1, and I was still seeing the black screen.
The fix in my case was to sync the properties between the .editorConfig and Visual Studio properties (as suggested above by @sharwell, issue #19089) and use the latest VS 2017 update.
I'm leaving this comment here in case it helps some one else with the same problem.

**Comment by sharwell** [comment] 2017-05-15 14:14
@manchas Thank you for the update. It sounds like we do already have an issue for this, but I linked to the wrong one. I'm hoping we have all these related issues fixed soon!

> The fix in my case was to sync the properties between the .editorConfig and Visual Studio properties

I'm glad you found a workaround, though it highlights the importance of fixing this (since .editorconfig simply isn't working for you). :smile:

**Comment by AlexanderTaeschner** [comment] 2017-05-17 11:42
For me the following is reproducible with Community 2017 Version 15.2 (26430.6) and the following settings: 
Options > Text Editor > C# > Advanced > Select "Enable full solution analysis"
Options > Text Editor > C# > Code Style: Prefer 'var' for all three types; severity 'Suggestion'

1. Create new Project: Visual C# > Windows Classic Desktop > Console App (.NET Framework); .NET Framework 4.5.2
2. Insert the following code in the main method:
```csharp
        static void Main(string[] args)
        {
            int a = 1;
        }
```
3. Click on 'int' and select the fix all occurrences Solution option via the lightbulb -> Preview is black
![blackpreview](https://cloud.githubusercontent.com/assets/12712997/26152162/13d0d2d8-3b06-11e7-8315-cc219647fdef.PNG)
4. Deselect "Options > Text Editor > C# > Advanced > Enable full solution analysis"
5. Click on 'int' and select the fix all occurrences Solution option via the lightbulb -> Preview is correct
![correctpreview](https://cloud.githubusercontent.com/assets/12712997/26152267/832e5aba-3b06-11e7-897b-6e5b39e30c18.PNG)

**Comment by sharwell** [comment] 2017-05-23 19:03
@AlexanderTaeschner thank you for the additional test case. I will use that for additional validation of a fix.

**Closed** 2017-05-26 07:44 UTC
Labels: Area-IDE, Bug, Resolution-Fixed
