### ISSUE TITLE
MSBuildWorkspace compilation errors for netcoreapp31/net5.0 'The type or namespace name 'System' could not be found'

### ISSUE THREAD

**Issue by Rora** [dotnet/roslyn#53906] opened 2021-06-06 18:50 UTC
**Version Used**: 
3.9.0

**Steps to Reproduce**:

1. Use MSBuildLocator.RegisterDefaults
2. Create a MSBuildWorkspace
3. Load a solution 
4. Compile a net5.0 or netcoreapp3.1 project 
5. Validate the compilation diagnostics

**Expected Behavior**:
No errors

**Actual Behavior**:
The following errors occur:

1. error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
2. error CS0518: Predefined type 'System.Object' is not defined or imported
3. error CS1729: 'object' does not contain a constructor that takes 0 arguments

I've also tried to scan a netstandard2.1 project and that seems to work fine. I created a solution which reproduces this issue: https://github.com/Rora/msbuild-workspace-dotnetcoreapp-repro

**Comment by koenbeuk** [comment] 2021-07-07 12:12
I'm experiencing the same issue, is there a known workaround?

**Comment by JoeRobich** [comment] 2021-07-07 17:05
@Rora So looking at the contents of `workspace.Diagnostics` after loading the solution, there are several errors of the form:

```
"Msbuild failed when processing the file '/Users/joeyrobichaud/Source/msbuild-workspace-dotnetcoreapp-repro/RoslynScanner/RoslynScanner/RoslynScanner.csproj' with message: /usr/local/share/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets: (63, 5): The \"ProcessFrameworkReferences\" task failed unexpectedly.
System.MissingMethodException: Method not found: 'System.String NuGet.Frameworks.NuGetFramework.get_Platform()'.
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.KnownFrameworkReferenceAppliesToTargetFramework(NuGetFramework knownFrameworkReferenceTargetFramework)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.<ExecuteCore>b__105_1(KnownFrameworkReference kfr)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)"
```

This is an issue where `Microsoft.NET.Test.Sdk` depends on `Microsoft.TestPlatform.TestHost` which depends on `Microsoft.TestPlatform.ObjectModel`  which depends on and older version of `NuGet.Frameworks`. To fix this in your tests you can add a PackageReference to "NuGet.Frameworks" version 5.9.0+.

**Comment by koenbeuk** [comment] 2021-07-07 19:39
I can confirm that adding NuGet.Frameworks as a package reference as suggest by @JoeRobich solves this issue. 

There are a triage of other issues when having .net core 6 preview installed. After uninstalling .net core 6 preview, things finally started working. I suspect that those other issues are unrelated to this issue though, will open new issues if I see the need.

**Comment by JoeRobich** [comment] 2021-07-15 01:20
Closing this issue as a duplicate ofhttps://github.com/dotnet/roslyn/issues/52954

**Closed** 2021-09-08 21:29 UTC
Labels: Bug, Resolution-Duplicate, Area-IDE, IDE-MSBuildWorkspace
