### ISSUE TITLE
"After-the-fact" ctrl+dot rename fails silently rather than avoiding conflicts

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3508] opened 2015-06-15 20:06 UTC
Watch this video:
![postofactofailure](https://cloud.githubusercontent.com/assets/3316258/8169510/ed275a1a-135e-11e5-9304-46b6c3d8d0ae.gif)

I prefer to edit identifiers and then use the "dotted border after-the-fact rename refactoring" (rather than using ctrl+R ctrl+R).

In this repro, the first "after-the-fact" rename works fine. But the second one fails silently to do any renaming. (what causes the silent failure is that it would need to do some conflict-resolution here).

For convenience, here's the full code:
```vb
Module Module1
    Sub Main()
    End Sub

    Sub f(c As Integer)
        Dim x = CCC.p
    End Sub
End Module

Class CCC
    Public Shared p As Integer
End Class
```

**Comment by balajikris** [comment] 2015-06-15 21:00
though @dpoeschl reproed the issue reported here, I'm curious to know what build of VS this is ? Ctrl + . shows 2 options for Rename tracking (one with preview and one without), whereas I'd expect it to show one option and show preview by default.

**Comment by dpoeschl** [comment] 2015-06-15 21:07
As Balaji mentions, you're on a bit of an older build (there should only be one "Rename 'c' to 'cc'" option in the list), but the problem is still present on current builds. 

The problem here is that clicking on the lightbulb (or hitting Ctrl+<dot>) causes case correction to kick in, which changes the document (lowercasing the ```CCC```).

You can repro this without Inline Rename by taking:
```VB
    Sub f(ccc As Integer)
        Dim x = 7 + ccc
    End Sub
```
and changing ```ccc``` on the line where ```x``` is declared to ```Ccc```, highlighting ```7 + Ccc```, and hitting ctrl+<dot> to Extract Method. The first attempt will briefly flash the lightbulb and only perform the case correction.

**Comment by basoundr** [comment] 2015-06-15 21:16
This issue is a duplicate of #2123

**Comment by ljw1004** [comment] 2015-06-15 22:11
Thanks! (I'm using VS2015 RC, which yes is a pretty old build by now).

**Comment by dpoeschl** [comment] 2015-06-16 01:02
Closing as duplicate. I've added your video to that bug, as it is quite illustrative of the problem.

**Closed** 2015-06-16 01:02 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
