### ISSUE TITLE
ArgumentException is thrown when getting compilation for project with duplicate project references

### ISSUE THREAD

**Issue by DieselMachine84** [dotnet/roslyn#16010] opened 2016-12-19 14:47 UTC
**Version Used**: 
2.0.0-rc2
[RoslynTest.zip](https://github.com/dotnet/roslyn/files/661239/RoslynTest.zip)

**Steps to Reproduce**:
1. Use the attached sample project. Note that file RoslynTest.csproj has two identical references to ClassLibrary.csproj
2. Run the following code
`            string projectPath = @"d:\Work\RoslynTest\RoslynTest\RoslynTest.csproj"; //Use your path
            MSBuildWorkspace workspace = MSBuildWorkspace.Create();
            Project project = workspace.OpenProjectAsync(projectPath).Result;
            Compilation compilation = project.GetCompilationAsync().Result;
`

**Actual Behavior**:
Exception is thrown: System.ArgumentException: 'An item with the same key has already been added.' at
`            private async Task<CompilationInfo> FinalizeCompilationAsync(...)
            {
                ...
                metadataReferenceToProjectId.Add(metadataReference, projectReference.ProjectId);
                ...
            }
`

**Comment by jaredpar** [comment] 2016-12-20 19:19
CC @mattwar 

My intuition is this is the type of problem that should produce a diagnostic vs. an exception.  Wanted to check and see if there was an explicit design reason MSBuildWorkspace was done this way though.

**Comment by mattwar** [comment] 2016-12-20 22:00
The exception is coming from CompilationTracker which is the same code used by all workspaces. This problem is typically caught by the workspace before this step though.

**Comment by mattwar** [comment] 2016-12-20 22:05
This code path should only occur when accumulating metadata references from project references. So there should somehow be duplicate project references, which also should have already been caught by the workspace.

**Comment by mattwar** [comment] 2016-12-20 22:14
I see now that duplicate project reference is in the steps to reproduce.. doh.

I think the truth is that the workspace does not have any code to handle this case.

**Comment by sharwell** [comment] 2019-09-03 21:42
Duplicate of #22537

**Closed by sharwell** 2019-09-03 21:42 UTC
Labels: Area-IDE, Bug
