### ISSUE TITLE
A possible way to break out of if statements.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45736] opened 2020-07-07 03:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1102247/a-possible-way-to-break-out-of-if-statements.html)._

---
Another idea would be to have a way to break out of an if statement. 

```
if(colour == Color.Blue)
   {
       if(shape == Shape.Round)
       {
           // Do stuff
       }

if(result.valid != true)
            break 1;   // The number would be the index of the if-statement-layer 
                            // to break out of counting from the inside out.

if(shape == Shape.Square)
       {
           // Do stuff
       }
   }
```

In the above example, break 0; would break out of  if(result.valid != true), which would be not what was required in this case. Break 1; would break out of if(colour == Color.Blue) and is what was intended.

This could result in nicer code where if stucture could be otherwise undersirably complex.  However, using this device to much would not be desirable either.  Good programmers would likely appreciate another tool to help build well structured programs.

---
#### Feedback Bot on 7/6/2020, 02:01 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment] 2020-07-07 19:19
Closing out as a duplicate of https://github.com/dotnet/csharplang/issues/869.

**Closed by CyrusNajmabadi** 2020-07-07 19:19 UTC
Labels: Area-Compilers
