### ISSUE TITLE
Default parameter value binding to property instead of type name (i.e. Color Color problem)

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#40045] opened 2019-11-27 22:25 UTC
**Version Used**: Roslyn 3.5.0-beta2-19570-07+4bd316035f64c9776d5420af71df8ba38e8e23e4

![image](https://user-images.githubusercontent.com/201340/69763281-8c14fc80-1121-11ea-8650-2ccc05833c53.png)

**Expected Behavior:** the "Color" before the period where we are typing is colored blue.
**Actual Behavior:** it's binding to the property so it stays the wrong color.

I had some complicated case where I wasn't getting completion either. I'm not sure if I have a repro for that but this classification issue was very confusing.

**Comment by jasonmalinowski** [comment] 2019-11-27 22:25
Tagging this under IDE for initial investigation, but this may be a compiler bug.

**Comment by CyrusNajmabadi** [comment] 2023-02-17 20:14
Not repro:

![image](https://user-images.githubusercontent.com/4564579/219784207-714ed865-e405-41f2-acea-263e1561e9c4.png)

**Comment by CyrusNajmabadi** [comment] 2023-02-17 20:15
Reactivating.  The issue is about what it classifies as when we don't have a member after the dot.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 19:20
Closing ouot due to lacck of broad feedback on this.

**Closed by CyrusNajmabadi** 2024-10-25 19:20 UTC
Labels: Bug, Area-IDE
