### ISSUE TITLE
Ctrl+click GTD is too aggressive on string literals

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#22786] opened 2017-10-20 07:29 UTC
From: Daofa Li 
Basically C# identifies all literals as clickable symbols. The worst case is where the string literal is a url. Ctrl+click on the url may open the string metadata in editor as well as open the url in external browser. 

Can this be improved not to return literals as navigable symbols? The current behavior doesn’t make much sense to me as a user.
![image](https://user-images.githubusercontent.com/12449387/31809648-8172baee-b52d-11e7-96c8-11f9b6a9f594.png)

**Comment by jinujoseph** [comment] 2017-10-20 07:31
cc @dpoeschl

**Comment by lineralpha** [comment] 2017-11-14 23:06
This bug is causing issue reported in this feedback: https://developercommunity.visualstudio.com/content/problem/135746/mouse-cursor-stuck-to-the-pointer-hand-icon.html

When the string literal is a url, both the navigable symbol tagger (which drives ctrl+GTD under the hood) and url tagger change the mouse cursor to hand pointer. When mouse moves out the url they both restore the mouse cursor to previous shape which was hand pointer no matter whoever makes the change first.

**Comment by sharwell** [comment] 2017-11-25 17:12
@lineralpha The cursor bug is a conflict between `UrlMouseHandler` and `GoToDefMouseHandler`, which are not part of this repository. These handlers need to be able to handle overlapping tags regardless of the decision made for the handling of literals.

**Comment by sharwell** [comment] 2017-11-25 17:15
To reduce confusion, I'm closing this issue as a duplicate of #23030. Specifically note:

* The decision on whether or not Ctrl+Click for Go To Definition works on literals in code is a Roslyn decision (and is the focus of #23030)
* The handling of overlapping tags (e.g. `IUrlTag` and `INavigableSymbol`) is an editor issue unrelated to Roslyn

**Comment by kuhlenh** [comment] 2018-01-22 22:58
per our design discussion today:
- Remove literal support from Ctrl+Click entirely (there will be no hyperlink when holding Ctrl and hovering over any literal).
- The above should allow ctrl+click on a url to navigate to the webpage.

**Comment by jinujoseph** [comment] 2018-01-22 23:21
Tracked in #23030

**Closed** 2018-01-22 23:21 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate, _Product-level triaged, help wanted
