### ISSUE TITLE
Sync Namespaces is calling some kind of code cleanup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59080] opened 2022-01-26 17:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sync-Namespaces-is-calling-some-kind-of-/1645579)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:New Feature in VS2022]
Since upgrading to VS2022 I have started making use of the "Sync Namespaces" functionality. We use Microsoft.CodeAnalysis.NetAnalyzers / Stylecop / Sonar Analyser to enforce a set of style rules (and warnings are set to error). 

After running "Sync Namespaces" I find the code in the class where the namespace has changed has been altered. The "this." prefix has been removed on access to class level variables and the space between "new" and "()" has been removed. e.g 

this._username = "fred";
becomes 
_username = "fred"; 

MyObject x = new ();
becomes
MyObject x = new();

Both of these break now break our style rules and the code will no longer compile. I then have to go through and re-insert all the ".this" and spaces manually.

Surely "Sync Namespaces" should just alter the namespaces as needed and not alter the code within the classes?

---
#### Feedback Bot on 1/24/2022, 10:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2022-01-26 19:19
@jmarolf we can't avoid complexify/simplify for this step, so the fix might be to create/update .editorconfig to better represent the desired code style.

**Comment by jmarolf** [comment] 2022-01-26 22:19
yeah, presumably the user could work around this by specifying their desired behavior with the existing options. 

We could try to preserve existing rules by tracking things like style diagnostics before/after and ensuring they stay the same. so, if a file violates style in a section, we ensure that violation is preserved after complexify/simplify step. I believe this could be done with syntax tags.

**Comment by CyrusNajmabadi** [comment] 2022-05-11 13:44
> Why?

Because changing the namespace could change the meaning of your code. For example a reference to `Foo` might now bind to a different type than before.

**Comment by hopperpl** [comment] 2022-12-31 11:16
I'd like to rant about this abysmal feature, it needs to be removed. It also needs a big warning about this fully destroying code, making it uncompilable, deleting comments, removing all format information. Maybe make the warning box with 2FA. require at least 2 security tokens, the absolute destructiveness of this completely and utterly broken feature surely requires it.

what dangerous thing did I do to deserve this punishment?
* I accidentally moved a class file into a different project folder 
* the original namespace didn't even match the folder name before

what did this feature then do?
* synching namespaces then
* using a destination folder name with a space and adding that as an identifier in it (knowledge bomb: identifiers cannot have spaces)
* changing all using directives from "using System;" to "using stem;" remove the first 2 letters
* cutting multi-line comments so some comments having */ removed, stayed open
* changing all line endings to CRLF
* changing all indent from 2 to 4 (do both the .editorconfig and VS2022 config define otherwise? yes, both define 2-space and LF)
* vertical alignment was completely removed 
* incorrectly added braces around if/while statements AFTER multi line comments were cut - making, so I assume, Roslyn unable to context parse the source and then randomly defining blocks
* otherwise code formatting was completely unrelated to the VS2022 and .editorconfig settings --- something HARDCODED, right? 
* compiler was not able to run this code, it compiled perfectly before
* I was not able to revert the changes manually as a lot was simply deleted/lost

what did I have to do?
* global undo
* ... resulting in around 20 messages about "InvalidOperationException"
* ... after that Visual Studio fully crashed
* checking the then after-crash source files proved to be impossible to recover
* full hard git restore losing half a day's work

Have you ever considered to test features? This drives me really angry, because it still underlines the base mantras of Microsoft development
* release unfinished features
* never really test features (a 3-line single-file-project as test is not a test)
* have no option anywhere to disable bugged/broken features
* trigger such features automatically without confirmation fully aware that it's broken, bugged and destroys code
* disable/break any undo functionality to make it permanent (back to lack of testing)
* enforce Microsoft rules onto others like CRLF and 4-space tab (personal settings are ignored "Microsoft knows better")
* lack of comprehension by a lot of Microsoft developers that something like LF even exists ("Microsoft bubble") hence they don't even consider to, maybe, check settings

who implemented this feature? an unpaid intern? and then it was verified and tested by  a second unpaid intern?

And I really, really, really don't want to hear about "reference updates due to type changes". This has nothing to do at all with deleting and rewriting SyntaxTrivia (or "whitespace" tokens). Renaming a namespace works! I never had any issue with that. It doesn't reformat code. "sync namespace" does rewrite code in a destructive way!

**Comment by CyrusNajmabadi** [comment] 2022-12-31 15:54
@hopperpl abusive language is not ok. Please follow the rules of .net and keep the discussion purely constructive. It would be super helpful if you can provide a repro here. A github link to your repo and the steps you took there would allow us to see what might have happened in your case. 

Note: we need this info as VS is an extremely extensible system and it's often the case that things go wrong in a case like this with some extension or different system at a higher layer. With the repro we can pull in the right teams to look at this. 

And, again, please keep this civil. No one intended  this to not work for you.

**Comment by CyrusNajmabadi** [comment] 2022-12-31 23:03
It's possible, but it will also likely break other cases :-/

Hopefully we can get to fixing this in an upcoming milestone.

**Comment by sharwell** [comment] 2023-09-25 13:03
Duplicate of #34707

**Closed by sharwell** 2023-09-25 13:03 UTC
Labels: Question, Area-IDE, Developer Community
