### ISSUE TITLE
Invalid nuget licenses

### ISSUE THREAD

**Issue by Sigvaard** [dotnet/roslyn#31173] opened 2018-11-14 09:35 UTC
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/
https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/

Shouldn't it be MIT? Correct me if I'm wrong.

**Comment by jhinder** [comment] 2018-11-14 10:08
Roslyn does not use a MIT licence, but the [Apache 2.0 licence](https://github.com/dotnet/roslyn/blob/master/License.txt).

For a previous discussion on package licences, see issue #20169.

**Comment by Sigvaard** [comment] 2018-11-14 12:34
@jhinder yeah but nuget points to https://www.microsoft.com/net/dotnet_library_license.htm instead of apache 2.0

**Comment by sharwell** [comment] 2018-11-15 18:20
Duplicate of #20169

**Closed by sharwell** 2018-11-15 18:20 UTC
Labels: Area-Infrastructure
