### ISSUE TITLE
Automatic adding async for overrides on C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42726] opened 2020-03-24 16:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/952826/automatic-adding-async-for-overrides-on-c.html)._

---
Hey guys,

I stumbled a lot of times into the situation, that im overriding an async method, which is common in my case, it copies almost all necessary "properties" over into the function definition, but missing the async keyword itself. Which is really annoying.

Here is an example of my Telegram Bot Framework (https://github.com/MajMcCloud/TelegramBotFramework):

Overriding the following method:
public virtual async Task Action(MessageResult message)

results in:
public override Task Action(MessageResult message)

Thats sad, cause everytime i have to add that keyword. A setting or default(in my opinion better) would be great.

May you add this please ?

Warm regards
Florian Dahn

---
#### Visual Studio Feedback System on 3/17/2020, 10:42 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by YairHalberstadt** [comment] 2020-03-24 18:55
async is not part of the method signature, and this is perfectly legal:

```csharp
using System;
using System.Threading.Tasks;

public class Base {
    public virtual async Task M() => await Task.Yield();
}

public class Derived : Base {
    public override Task M() => Task.CompletedTask;
}
```

Thus I don't think it makes sense to copy it over.

**Comment by jinujoseph** [comment] 2020-03-24 19:30
Duplicate of #27181

**Closed by jinujoseph** 2020-03-24 19:30 UTC

**Comment by CyrusNajmabadi** [comment] 2020-03-24 22:02
the open quesiton @YairHalberstadt is if it's more common to have an override that will use `await` in it, or not.  If it's more common, we can just add `async` as a nice convenience for the user.  i.e. we should put the onus on hte smaller group to have to fixup.

**Comment by IanKemp** [comment] 2020-06-18 10:30
> the open quesiton @YairHalberstadt is if it's more common to have an override that will use `await` in it, or not. If it's more common, we can just add `async` as a nice convenience for the user. i.e. we should put the onus on hte smaller group to have to fixup.

It is absolutely more common.
