### ISSUE TITLE
[Test Failure] Individual TAO Test Failure (+1 more) in windows_release_eta_prtest on PR #1180

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12642] opened 2016-07-20 21:36 UTC
PR: [#1180](https://github.com/dotnet/roslyn-internal/pull/1180) *Revert previous integration change now that open side has gone through.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_release_eta_prtest/362/

**2 Test Failures:**
BasicIntellisense.Signature help shows up
BasicIntellisense.Completion's interaction with Undo and Commit (Bug 12294)

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicIntellisense.xml

**Issue 2: ETA integration tests failed**
ETA integration tests failed

**Comment by jasonmalinowski** [comment] 2016-10-19 02:31
Dupe of #12618.

**Closed by jasonmalinowski** 2016-10-19 02:31 UTC
Labels: Area-IDE, Bug, Contributor Pain
