### ISSUE TITLE
Invalid "Collection initialization can be simplified"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72483] opened 2024-03-11 16:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Invalid-Collection-initialization-can-b/10611908)._

---
Given the following method:

```
public static TheoryData<string> Valid() {
    return new TheoryData<string> {
        $""
    };
}
```

I'm being given a code fix for IDE0028 on `new` saying that it can be simplified.  If I apply it, I end up with this invalid code:

```
public static TheoryData<string> Valid() {
    return [
        $""
    ];
}
```

The string there has error CS0029: Cannot implicitly conver string to object[]

---
#### Feedback Bot on 3/10/2024, 09:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2024-03-11 19:43
Duplicate of #71240

**Closed by sharwell** 2024-03-11 19:43 UTC
Labels: Area-IDE, untriaged
