### ISSUE TITLE
Feature 'Navigation bar' is currently unavailable due to an internal error.

### ISSUE THREAD

**Issue by twest820** [dotnet/roslyn#68672] opened 2023-06-18 17:09 UTC
**Version Used**: Visual Studio 17.6.3

**Steps to Reproduce**: Routine C# .NET 6.0 coding on a small WPF app in VS.

**Expected Behavior**: Syntax tree handling is robust enough to normal typing code analysis doesn't put up error ribbons in the VS UX multiple times an hour.

**Actual Behavior**:
```
StreamJsonRpc.RemoteInvocationException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
      at Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(Document document, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.NavigationBar.CSharpNavigationBarItemService.GetTypesInFileAsync(Document document, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.NavigationBar.CSharpNavigationBarItemService.GetItemsInCurrentProcessAsync(Document document, Boolean supportsCodeGeneration, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.NavigationBar.AbstractNavigationBarItemService.GetItemsAsync(Document document, Boolean supportsCodeGeneration, Boolean forceFrozenPartialSemanticsForCrossProcessOperations, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteNavigationBarItemService.<>c__DisplayClass2_0.<<GetItemsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

**Comment by sharwell** [comment] 2023-06-19 14:26
Duplicate of AB#1832877

**Comment by sharwell** [comment] 2023-06-19 14:26
🔗 The public facing issue for the above link is https://developercommunity.visualstudio.com/t/Feature-Navigation-bar-is-currently-un/10387584

**Closed by sharwell** 2023-06-19 14:26 UTC
