### ISSUE TITLE
Question: Participate in Hacktoberfest?

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [dotnet/roslyn#48344] opened 2020-10-05 23:05 UTC
Hacktoberfest is going on this month. They have changed the rules to an "opt-in" policy by adding Hacktoberfest top to the repository. Here is a link - [Hacktoberfest Update](https://hacktoberfest.digitalocean.com/hacktoberfest-update). It's a good way to get new contributors.

**Comment by sharwell** [comment] 2020-10-05 23:51
Duplicate of #48285

**Closed by sharwell** 2020-10-05 23:51 UTC
