### ISSUE TITLE
Quick Action to add missing fields to intializers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60631] opened 2022-04-07 20:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Action-to-add-missing-fields-to-in/1702602)._

---
It would be handy to be able to use a Quick Action to add the remaining fields to class / struct intializers with their default values.

So if you had a code as follows:

```
class MyClass
{
    string A { get; set; }
    bool B { get; set; }
    MyOtherClass C { get; set; }
}

void MyFunction()
{
    var myClass= new MyClass 
    {
        A = "something",        
    }
}
```

.... and the Quick Action was applied tmp the remaining fields would be filled in as follows:

```
var myClass = new MyClass 
{
    A = "something",        
    B = false,
    C = null,
}
```

---
#### Feedback Bot on 3/25/2022, 02:26 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment] 2022-04-07 20:31
I'm not certain i see teh benefit here.  These properties will already have default values, so the initialization would be redundant.

**Comment by CyrusNajmabadi** [comment] 2024-10-22 20:07
Closing as by design.

**Closed by CyrusNajmabadi** 2024-10-22 20:07 UTC
Labels: Area-IDE, Feature Request, Developer Community, Need Design Review
