### ISSUE TITLE
Expose TypeSymbol.IsReadOnly property

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#27061] opened 2018-05-23 00:12 UTC
**Version Used**:  master

I'm working on a set of analyzers called ErrorProne.NET. One of the analyzers there deals with readonly structs and warns if non-readonly struct is used in 'readonly contexts' like passed by 'in' etc.

Unfortunately, there is no way right now to check that a struct is readonly, especially if the struct is not declared in the current code base. When the source code is available it is possible to get the source tree and then to check the list of modifiers. But this option is not available if the type comes from the metadata.

Basically, the problem is that `ITypeSymbol` does not have 'IsReadOnly' property and both `TypeSymbol` type and `IsReadOnly` property are both [internal](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbol.cs,627).

And I can't even find a reasonable workaround (except to go through reflection) because `PENamedTypeSymbol.GetAttributes` filters out `IsReadOnlyAttribute` [from the result](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Metadata/PE/PENamedTypeSymbol.cs,593).

It basically means that there are no official ways today to write an analyzer that will do something different for readonly structs.

**Comment by jmarolf** [comment] 2018-05-23 03:38
Seems like something that should at least be added to IOperation if not the symbol API.

**Comment by JosefPihrt** [comment] 2018-05-24 18:30
A duplicate of https://github.com/dotnet/roslyn/issues/23792

**Comment by jcouv** [comment] 2018-05-25 16:57
Closing as duplicate of #23792 (thanks @JosefPihrt).
@SergeyTeplyakov please chime in on that original issue. Thanks

**Closed by jcouv** 2018-05-25 16:57 UTC
