### ISSUE TITLE
View jumps to caret position when applying a lightbulb fix even if caret is far away

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#51100] opened 2021-02-09 19:31 UTC
**Version Used**: 
31007.54.main

**Steps to Reproduce**:

1.	Set up a situation where you will have a lightbulb somewhere.
2.	Move the caret far away.
3.	Scroll back to the lightbulb position, hover to bring up the lightbulb (but don’t click to move the caret), pick a lightbulb refactoring.
4.	Edit is performed and the view scrolls to the caret location.

**Expected Behavior**:
View shouldn't scroll.

**Actual Behavior**:
It looks like the lightbulb code does a caret.EnsureVisible & the view scrolls to the caret location rather than remaining on the lightbulb.

See Jason's comments:
That’s probably this line:

https://github.com/dotnet/roslyn/blob/2d3ffe0c9adf9c72874162fe6f2d08f93c508d2e/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.CaretPositionRestorer.cs#L77

It looks like that’s been there since literally the introduction of our lightbulb implementation. I’m guessing the “and ensure visible” was just part of the helper we’re calling and not really necessary.

**Comment by jinujoseph** [comment] 2021-02-10 20:17
Duplicate of #27141

**Closed by jinujoseph** 2021-02-10 20:17 UTC
Labels: Area-IDE, Bug
