### ISSUE TITLE
IDE0016 provides invalid codefix on generic type without constraint

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#22926] opened 2017-10-31 05:39 UTC
**Version Used**: 
Visual Studio 15.4.1

**Steps to Reproduce**:
```csharp
class A<T>
{
    T x;
    public A(T t)
    {
        if (t == null) throw new ArgumentNullException();
        x = t;
    }
}
```

**Expected Behavior**:
T is not constrained, so `??` cannot be applied on it.

**Actual Behavior**:
Code fix to
```csharp
x = t ?? throw new ArgumentNullException();
```

How about allowing `??` on unconstrained generic type? For value type, just ignore it, as it implies `== null`.

**Comment by sharwell** [comment] 2017-10-31 05:44
This appears to be a duplicate of #17754.

**Comment by sharwell** [comment] 2017-10-31 05:47
Reopening since this should have been fixed in 15.3, but @huoyaoyuan was observing it in 15.4.1.

**Closed** 2017-11-17 17:37 UTC
Labels: Area-IDE, Bug, Resolution-Fixed
