### ISSUE TITLE
Provide a generic code fixer for navigating the URL of a diagnostic

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#42103] opened 2020-03-02 21:02 UTC
The `DiagnosticDescriptor` has a [`HelpLinkUri` property](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,4a0a00cc5df1dbb4,references) which is used by the IDE to render a hyperlink in the error list:

![image](https://user-images.githubusercontent.com/5169960/75716965-1622b300-5c85-11ea-875e-962a56026860.png)

However, this is quite subtle and I've seen many people not noticing this. In my own analyzer, I've added a code fixer that offers to browse to the location:

![image](https://user-images.githubusercontent.com/5169960/75717085-4d915f80-5c85-11ea-9dc9-7bce3d2095f2.png)

However, my code fixer is specific to my own diagnostics. It might help to provide a built-in code fixer that offers this capability for all diagnostics. Especially because the priority of this fixer should probably be lower than other code fixers but the ability to tweak priorities wasn't exposed last time I checked.

**Comment by terrajobst** [comment] 2020-03-03 00:48
Tagging folks who have an interest in this space: @mikadumont @mavasani @CyrusNajmabadi

**Comment by terrajobst** [comment] 2020-03-30 23:37
Any chance we could prioritize this for .NET 5? This is part of the [better obsoletion](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/better-obsoletion.md#goals) work.

> Documentation pages are easily accessible. Developers must be able to go from the diagnostic in the error list straight to the documentation that provides the details.

My concern is that the hyperlink in the error list isn't discoverable enough.

**Comment by CyrusNajmabadi** [comment] 2020-03-31 00:30
> My concern is that the hyperlink in the error list isn't discoverable enough.

Any way we could get data on that?  it seems pretty clear to me.  it's blue.  it's got an underline.  i know my mouse has gone over it many times and seen it light up.  So i'm totally biased, but even not being at all part of the design there, it was immediately obvious to me what that was.

**Comment by terrajobst** [comment] 2020-03-31 03:12
> Any way we could get data on that? it seems pretty clear to me. it's blue. it's got an underline. i know my mouse has gone over it many times and seen it light up. So i'm totally biased, but even not being at all part of the design there, it was immediately obvious to me what that was.

We have implemented said fixer in our platform-compat tool because based on customer interactions it was quite clear that many didn't realize that the guidance was available by clicking on the error code in the error list.

**Comment by CyrusNajmabadi** [comment] 2020-03-31 03:23
The problem is that we may have many items in that list.  It's common to have 10 or more fixes offered for a variety of issues that may be on that line.  I'm really hesitant to have this item here as it would effectively double the size of those lists.

We already have feedback that we even have too many items already, and we spent a ton of timing getting down to even the set we do offer.  Adding more seems not great.  I think this is the standard discoverability/intrusiveness problem.  We can make things more discoverable by putting them more in hte user's face.  But once they're discovered, now what does that do the rest of the experience?  How does htat impact users who don't necessarily want these?  etc. etc.

Maybe we should rename the bottom bucket and make it a general catch-all for this sort of thing.  i.e. if you want more info you go into this:

![image](https://user-images.githubusercontent.com/4564579/77983610-4d0bd900-72c4-11ea-92c0-9e196f0c97d0.png)

And you can suppress/config/about/report-issue.

**Comment by terrajobst** [comment] 2020-03-31 04:14
Could we collapse them into a single menu item with sub items, like

* Navigate to Guidance 
    - IDE0003: http://aka.ms/dotnet-issues/IDE0003
    - IDE0059: http://aka.ms/dotnet-issues/IDE0059

**Comment by mavasani** [comment] 2020-04-01 19:01
@terrajobst @CyrusNajmabadi I can implement this as per Immo's suggestion. I prefer keeping "Help Link/Guidance" menu separate from "Suppress/Configure issues" - they seems separate actions. @mikadumont for her views.

**Comment by mikadumont** [comment] 2020-04-01 19:50
I agree with Cyrus that the hyperlink is visible enough.

**Comment by CyrusNajmabadi** [comment] 2020-04-01 19:51
I'm ok with a new item in the list if it's a single item at the bottom (likely below suppress/configure).  But my gut goes with: i would prefer to do nothing.

**Comment by mavasani** [comment] 2020-04-01 19:52
I think at this point we clearly need more customer data to move forward on this...

**Comment by svick** [comment] 2020-04-03 17:29
@CyrusNajmabadi 

> it seems pretty clear to me. it's blue. it's got an underline. i know my mouse has gone over it many times and seen it light up. So i'm totally biased, but even not being at all part of the design there, it was immediately obvious to me what that was.

It's blue, but in its own column, so I think the color doesn't stand out as much as it would e.g. inside a paragraph of text. And it's got an underline only when you hover over it or when it's selected.

But most importantly, you can't quickly differentiate between a link that will send you to the actual official documentation from a link that will just google the error for you (and it doesn't even use Google for that). And since the latter is the case for many errors, I suspect many developers become "blind" to those links, after trying them a few times and finding them not useful.

So I think it makes sense to have a more obvious way of providing a link that is actually useful.

**Comment by mavasani** [comment] 2020-04-03 17:44
> So I think it makes sense to have a more obvious way of providing a link that is actually useful.

Note: this issue is not about providing a different link. The link is actually not controlled by the error list or the editor - it is provided by the diagnostic provider (compiler or analyzer that produced the diagnostic also provides the help link). This issue is about making whatever link that was provided to the IDE more discoverable.

We already have separate issues tracking improving the help links for compiler diagnostic and IDE analyzer diagnostics. See https://github.com/dotnet/roslyn/issues/40863 and https://github.com/dotnet/roslyn/issues/41324

**Comment by sharwell** [comment] 2020-04-27 21:27
Design review conclusion: We should add a hyperlinked diagnostic IDE to the Quick Info popup for the messages presented by diagnostics. At the time diagnostics were first added to the error list, we did not have the ability to hyperlink items in Quick Info. That has since changed, so we can leverage the new functionality to serve two purposes:

1. It will be easier to see which messages in Quick Info are related to which diagnostic IDs
2. It will be possible to navigate from Quick Info to the help link provided for a diagnostic

**Comment by sharwell** [comment] 2020-04-27 21:30
Closing this issue in favor of #43728.

**Closed by sharwell** 2020-04-27 21:30 UTC
Labels: Area-IDE, Feature Request, Need Design Review
