### ISSUE TITLE
Assert in Microsoft.CodeAnalysis.CSharp.Binder.GetValEscape method during build

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65167] opened 2022-11-02 09:02 UTC
**Version Used**: Latest Roslyn bits from main branch

**Steps to Reproduce**:

1. F5 Roslyn.sln built from main branch
2. Clone and checkout https://github.com/nikcio/lucenenet/tree/debug/vs2022-crash
3. Build `Lucene.Net.Minimal.sln`

Below assert fires: https://github.com/dotnet/roslyn/blob/f30083b91d472bae32b202418a45cdda15ae5591/src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs#L3642-L3646

**Assert message:** `ArgList expression of System.RuntimeArgumentHandle type`

**Call stack:**
```
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression expr, uint scopeOfTheContainingExpression) Line 3364	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetInvocationEscapeScope(Microsoft.CodeAnalysis.CSharp.Symbol symbol, Microsoft.CodeAnalysis.CSharp.BoundExpression receiver, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol> parameters, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> argsOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind> argRefKindsOpt, System.Collections.Immutable.ImmutableArray<int> argsToParamsOpt, uint scopeOfTheContainingExpression, bool isRefEscape) Line 1522	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetValEscape(Microsoft.CodeAnalysis.CSharp.BoundExpression expr, uint scopeOfTheContainingExpression) Line 3227	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol localSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind kind, bool isVar, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax declarator, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations declTypeOpt, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol aliasOpt, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool includeBoundType, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode associatedSyntaxNode) Line 1118	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind kind, bool isVar, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax declarator, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations declTypeOpt, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol aliasOpt, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool includeBoundType, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode associatedSyntaxNode) Line 950	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 716	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 681	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 66	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1852	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1840	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 63	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode declaration, Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax blockBody, Microsoft.CodeAnalysis.CSharp.Syntax.ArrowExpressionClauseSyntax expressionBody, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 3636	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 3491	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool includeInitializersInBody, Microsoft.CodeAnalysis.CSharp.BoundNode initializersBody, bool reportNullableDiagnostics, out Microsoft.CodeAnalysis.CSharp.ImportChain importChain, out bool originalBodyNested, out bool prependedDefaultValueTypeConstructorInitializer, out Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.InitialState forSemanticModel) Line 1778	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol methodSymbol, int methodOrdinal, ref Microsoft.CodeAnalysis.CSharp.Binder.ProcessedFieldInitializers processedInitializers, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields previousSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState) Line 1042	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType) Line 530	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsync.AnonymousMethod__0() Line 424	C#
 	Microsoft.CodeAnalysis.dll!Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0() Line 139	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
```

**Comment by Youssef1313** [comment] 2022-11-02 13:46
Related issues:

https://github.com/dotnet/roslyn/issues/64471
https://github.com/dotnet/roslyn/issues/58177

**Comment by jcouv** [comment] 2022-11-03 05:35
Closing as duplicate of https://github.com/dotnet/roslyn/issues/58177

**Closed** 2022-11-03 05:35 UTC
Labels: Bug, Area-Compilers, untriaged
