### ISSUE TITLE
Source generators run very unreliably (especially with multi-targeting)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#67123] opened 2023-03-01 13:39 UTC
**Version Used**: 17.4.3 to 17.6 Preview 1

We're seeing multiple issues being reported of the MVVM Toolkit source generators not working correctly, especially in the 8.1 release, which is the first one that uses Roslyn multi-targeting. This is a major issue for us, as it (1) causes frustration to users and sometimes outright prevents them from using the MVVM Toolkit, and (2) leads them to assume the MVVM Toolkit is at fault here, and then report issues in our repo, where there isn't really much we can do (and I suspect the issue is rather somewhere in Roslyn/VS).

The common symptoms are:
- IntelliSense not working correctly (red squiggly lines all over the place for generated members)
- Builds outright being broken with various source generator errors (common one being that they run twice)

We've noticed reports in several configurations, from MAUI to WinUI 3, etc. I have tried to reproduce this and so far I've just been completely unable to do so. This included setting up test projects on various frameworks and inspecting our unit tests. I genuinely have no idea what's going on and why things are breaking up for so many people, and could use some help 🥲

Related issues:
- https://github.com/CommunityToolkit/dotnet/issues/493
- https://github.com/CommunityToolkit/dotnet/issues/584
- https://github.com/CommunityToolkit/dotnet/issues/598
- https://github.com/CommunityToolkit/dotnet/issues/623
- https://github.com/CommunityToolkit/dotnet/issues/625

> **Note**: this seems unrelated to the previous issue caused by CsWin32 bundling `System.Memory` assemblies (which @jaredpar fixed in Roslyn, and the CsWin32 team also addressed on their end), as that was just causing the generators to completely fail to be loaded. This is different: they are loaded but then either result in IntelliSense being broken, or they throw errors, or they just seem to not run at all. I have been unable to find a setup/configuration that consistently reproduces the issue.

Interestingly, several people seem to also report downgrading to 8.0 fixes the issue. The main difference I can see in 8.1 is that we're now using Roslyn multi-targeting. I wonder if there might be some bug in that area that causes Roslyn to sometimes trip up? Not saying this is 100% the cause of the issue, but in some cases it does seem downgrading solves it.

cc. @333fred @sharwell @chsienki

**Comment by Sastum** [comment] 2023-03-05 14:13
Yes,  downgrading to 8.0 fixes the issue, at least form me.

**Comment by RokG** [comment] 2023-03-06 18:34
The only issue I had was the one where IntelliSense was broken. 
Can also confirm that downgrading to 8.0.0 has resolved this issue for me. 
My solution is of type WPF App with three WPF Class Library projects.
The issue was the same on .net5, .net6 and .net7

To sum up my experience on a Related issue:

This seemed completely random, but it looked like it always started happening with properties like:

```
[ObservableProperty]
[NotifyCanExecuteChangedFor(nameof(SomeMethodCommand))]
private string someProperty
```

After some time of coding, squiggly lines first appeared under `SomeMethodCommand`. Then more and more squiggly lines started to appear (for example, under `SomeProperty` wherever it was used in code.

I tried to find a pattern, to reproduce the issue but I didn't find anything.. The only repeatable thing was that the squiggly lines first appeared under `[NotifyCanExecuteChangedFor(nameof(SomeMethodCommand))]`.

If I used F12 to get to the autogenerated file on some other property within the same .cs file, I could see that there really were no properties that were underlined with the squiggly lines there. So the IntelliSense was working "correctly". Regardless, I could still build and ran the solution without any problems, apart from Hot Reload not working due to these false Errors.

The AutoGenerated files were all in `C:\Users\<MyUser>\AppData\Local\Temp\VSGeneratedDocuments\<SomeRandomString>`

**Comment by majora2007** [comment] 2023-03-06 19:10
I also had a similar issue with Regex Source Generators ([GeneratedRegex]) showing a squiggly line in Rider, but the solution would build and run completely fine (in dotnet 7). 

This was reported and I believe it is indeed a Roslyn issue. 
https://youtrack.jetbrains.com/issue/RIDER-85361#focus=Comments-27-6869809.0-0

**Comment by CyrusNajmabadi** [comment] 2023-03-06 19:23
FYI that SGs are not a current priority for the team.  So best bet for any progress here would be if someone could determine what is potentially going wrong and submit a fix externally.  Not sure when we'll have resources taht would be able to look into this issue.  Generally speaking though, i would recommend only minimal use of SGs and not try to make them part of the inner loop where you want IDE features working for them.

**Comment by Sergio0694** [comment] 2023-03-06 22:49
> "i would recommend only minimal use of SGs and not try to make them part of the inner loop where you want IDE features working for them"

This is not really a viable suggestion for us, as it's essentially saying not to use the MVVM Toolkit at all. It's a core component of our dev inner loop both for external consumers and first party apps, so not really advice we can follow 🥲

And I will say again, I do think this hasn't been made clear well enough at all when source generators (even incremental ones) were made available as an API.

**Comment by Balkoth** [comment] 2023-03-07 11:01
If what you are saying is true, then any new feature you guys are implementing should just be ignored, because it might be released in a half-finished state and never get fixed. You guys have a serious communication problem if stuff like this creeps out into the wild.

**Comment by TomOeser** [comment] 2023-03-07 12:53
> If what you are saying is true, then any new feature you guys are implementing should just be ignored, because it might be released in a half-finished state and never get fixed. You guys have a serious communication problem if stuff like this creeps out into the wild.

So you're saying you can do all this much better? Go ahead - no one is stopping you ;)

Back to topic:
What worked wonderfully for me was specifying a particular platform (32/64) and removing the Any Platform specification from the project settings.

**Comment by polymorphicshade** [comment] 2023-03-09 00:38
I'm here to confirm I have the same issue.
I mistakenly thought it was related to something else, see my outline in [#493](https://github.com/CommunityToolkit/dotnet/issues/493#issuecomment-1441014366).

Downgrading to 8.0.0 did not seem to resolve anything, even after deleting my bin/obj folders.

**Comment by borrmann** [comment] 2023-03-09 11:09
+1, downgrading is the only way I can work with VS and MVVM effectively at the moment. When everything is fine in my solution the SG works fine, but once I have an error somewhere, the SG adds hundreds to thousands more to my solution, so that I have to read the build output to find my actual errors.
The SG is the main reason I am using this toolkit and I would imagine this applies to many other people, so giving this a low priority doesn't make sense to me. 
Maybe you could consider to rollback these changes, if you cant solve them at the moment?
Lastly, I really appreciate this great toolkit, so thank you for all your hard work!

**Comment by RokG** [comment] 2023-03-09 21:42
I think I managed to reproduce it..

Pseudocode:
```
// Property:
[ObservableProperty]
[NotifyCanExecuteChangedFor(nameof(SomeMethodCommand))]
private SomeClass someClassProperty;

// Method:
[RelayCommand(CanExecute = nameof(CanExecuteSomeMethod))]
private async void SomeMethod()
{}

// CanExecute Method
private bool CanExecuteSomeMethod
{
   return SomeClassProperty != null;
}

```

Code analyzer suggested making the `CanExecuteSomeMethod` to `static`, so I did and saved the file.
This underlined the `SomeClassProperty` and also underlined **ALL** `[NotifyCanExecuteChangedFor(nameof(...))]` above any other properties in red.
Then I removed the `static` from `CanExecuteSomeMethod` and saved the file again. Now the red line under  `SomeClassProperty` inside the method was gone, but all `[NotifyCanExecuteChangedFor(nameof(...))]` were still underlined

**Comment by polymorphicshade** [comment] 2023-03-09 22:58
> FYI that SGs are not a current priority for the team. So best bet for any progress here would be if someone could determine what is potentially going wrong and submit a fix externally. Not sure when we'll have resources taht would be able to look into this issue. Generally speaking though, i would recommend only minimal use of SGs and not try to make them part of the inner loop where you want IDE features working for them.

I think it's worth noting anecdotally, my team and I can no longer use this toolkit. For us, we almost exclusively use the SGs with the toolkit since we primarily develop XAML-focused MVVM apps. Without restarting Visual Studio, we are forced to use classical INotifyPropertyChanged implementations which basically triples our development time.

Downgrading doesn't seem to fix anything but we will continue to try to find workarounds.

**Comment by 0xF6** [comment] 2023-03-11 20:28
Why SG still very problematic like a year ago, like now, it works every other time, I constantly have to restart VS
Not ready to using in business? If so, why is this feature not under the feature flag\beta\alpha\etc?

**Comment by CyrusNajmabadi** [comment] 2023-03-11 20:44
> Why SG still very problematic like a year ago, 

There currently no resources available to invest in the source generator space. We would happily take community involvement to help in areas we're not able to currently focus on. Thanks!

**Comment by DJRM2021** [comment] 2023-03-16 16:06
> +1, downgrading is the only way I can work with VS and MVVM effectively at the moment. When everything is fine in my solution the SG works fine, but once I have an error somewhere, the SG adds hundreds to thousands more to my solution, so that I have to read the build output to find my actual errors. The SG is the main reason I am using this toolkit and I would imagine this applies to many other people, so giving this a low priority doesn't make sense to me. Maybe you could consider to rollback these changes, if you cant solve them at the moment? Lastly, I really appreciate this great toolkit, so thank you for all your hard work!

I agree with this and from recent experience, SGs of Mvvm toolkit will add hundreds (even thousands) of errors in the whole VS2022 project even if you check that there are literally no errors in code. Just the other day, Mvvm decided to put in 300+ errors to my projects. Clean + Rebuild will temporarily get rid of errors, but after a few minutes, they will come back.

**Comment by VincentH-Net** [comment] 2023-03-17 13:43
@RokG mentioned:
> Hot Reload not working due to these false Errors

This is the main problem this issue causes for me: it makes CommunityToolkit.Mvvm above version 8.0.0 unusable for working with [C# Markup 2](https://github.com/VincentH-Net/CSharpForMarkup) for Windows App SDK and/or Uno Platform.

Hot Reload is essential for the inner dev loop with C# UI.

Workaround is to downgrade to CommunityToolkit.Mvvm 8.0.0

**Comment by Sergio0694** [comment] 2023-03-17 13:53
@chsienki @sharwell I know that as @CyrusNajmabadi mentioned there's currently no resources to significantly invest in SG tooling, but this issue is becoming particularly problematic for us, as it's essentially harming our adoption of the new CommunityToolkit.Mvvm release significantly. Like, the amount of people having problems and needing to rollback is just way too high, and I genuinely have no clue on what's going on or how we could help at all.

Given the issues seems to be particularly widespread with 8.1 and not 8.0, would it be possible for someone from the Roslyn team to look into this (I'd be more than happy to assist if needed) so that we could at least maybe narrow down what change we made that's causing Roslyn to choke up so much, and possibly come up with some workaround for the time being? 🥲

**Comment by chsienki** [comment] 2023-03-17 17:32
Are these errors specific to the IDE, or do they happen on the command line too?

**Comment by VincentH-Net** [comment] 2023-03-17 17:46
@chsienki 
> Are these errors specific to the IDE, or do they happen on the command line too?
In VS Windows, I experience Intellisense errors - there are no build errors. So I would expect they do not happen on the cli

**Comment by Sergio0694** [comment] 2023-03-20 12:15
Question for everyone that has experienced issues with the MVVM Toolkit 8.1 and not on 8.0: are you also using _any other generators_ that are working fine? Because from what I can see, there's two main differences between 8.0 and 8.1:
- 8.0 only targets Roslyn 4.0, 8.1 multi-targets 8.0 and 8.1 (though this shouldn't be a problem) 
- 8.1 makes heavy use of `ForAttributeWithMetadataName`
  - This has several known bugs that cause issues in some cases (see: https://github.com/dotnet/roslyn/pull/66643). I'm wondering whether what we're seeing here is that same issue.

My hypothesis is: it's FAWMN causing problems, so people rolling back to 8.0 are fine because that API isn't used anymore.

Essentially I'd be curious to know whether for people that stopped having issues going back to 8.0, whether they are referencing any other generators that are using FAWMN, and not just eg. `ISourceGenerator` or other APIs 🤔

cc. @CyrusNajmabadi @jjonescz

**Comment by HavenDV** [comment] 2023-03-20 22:19
Is `ForAttributeWithMetadataName` resistant to copy-paste operations? I notice that Intellisence often breaks when adding new attributes through copy-paste of existing code.

**Comment by CyrusNajmabadi** [comment] 2023-03-20 22:26
There is no concept in generators of what sort of edit caused the change. All changes are processed in the same fashion.

**Comment by Sergio0694** [comment] 2023-03-20 22:31
> "I notice that Intellisence often breaks when adding new attributes through copy-paste of existing code."

@HavenDV just to double check: is that not the case on 8.0? Or does IntelliSense also break down there?

**Comment by CyrusNajmabadi** [comment] 2023-03-21 00:03
FAWMN stresses the underlying incremental engine (lots of interesting things it does).  I could easily see it doing something that causes a break in that engine, which then leads to things getting bad.

**Comment by christosk92** [comment] 2023-03-21 05:50
I just get IntelliSense errors.

I trust the MVVM toolkit to work fine and rarely get any build errors. If I do I just do a clean and it's resolved. I don't think it has ever been breaking for me. I'm on the MVVM toolkit 8.2 preview 1 and .NET 8 preview 2

**Comment by Sergio0694** [comment] 2023-03-25 16:48
This whole issue seems potentially related (at least in part) to the problem fixed by https://github.com/dotnet/roslyn/pull/66643.
cc. @jjonescz since you contributed that fix (thank you!) 😄

**Comment by huynhsontung** [comment] 2023-03-26 16:39
I got the issue with Intellisense using [MVVM Toolkit](https://www.nuget.org/packages/CommunityToolkit.Mvvm/) version 8.1 or above. This also breaks hot reload as others have mentioned. Downgraded to MVVM 8.0 for now.

**Comment by jasonmsmith** [comment] 2023-03-29 19:09
I can confirm that downgrading MVVM Toolkit from 8.1 to 8.0 fixed this problem for me. As others have noted, the problems I experienced were "bogus" errors reported due to the source generators crashing for various reasons. The project always built successfully, but intellisense and error reporting during development would become useless after 10-15 minutes of development and required restarting VS 2022. I experienced this issue using VS 17.5.3.

**Comment by Sergio0694** [comment] 2023-05-16 20:11
Asking here as well (since not everyone is in https://github.com/CommunityToolkit/dotnet/issues/493). Now that [Visual Studio 2022 17.6 is out](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-6-now-available/), that should include a lot of fixes to Roslyn that should hopefully mitigate or solve these issues that people were encountering with the MVVM Toolkit. If anyone has a chance to check this on their end, let us know if it did solve the issues for you! Thank you! 🙂

**Comment by codengine** [comment] 2023-05-17 00:15
I observed this behavior:
https://github.com/CommunityToolkit/dotnet/issues/493#issuecomment-1550432518

Could anyone deny or confirm that this is the core of the issue?

**Comment by jasonmsmith** [comment] 2023-05-19 13:52
Upgrading to VS 17.6.0 64-bit Community Edition did not fix this problem for me. When I upgraded from CommunityToolkit.MVVM 8.0.0 to 8.2.0, I got the same behavior as before; after a few minutes of coding, bogus errors start showing up. Attached is a screenshot of two representative errors. With a few more minutes of coding, there will be dozens more. The most common errors I see are "Ambiguity between Foo.Bar and Foo.Bar" and "Generator XYZ failed to generate source because the hint name 'FooPackage.Foo.Bar.g.cs' must be unique. Despite the errors in the error list, the project compiles normally and runs fine.
![Screenshot 2023-05-19 094545](https://github.com/dotnet/roslyn/assets/10959016/041b9fe5-066d-4647-8976-161e8946c83f)

**Comment by DJRM2021** [comment] 2023-05-30 14:40
Just an update, updating to VS Community 17.6.2 64-bit and CommunityToolkit.Mvvm 8.2.0, solved this issue for me.
All of the rogue and bogus errors are gone, even on build time.

**Comment by codengine** [comment] 2023-05-30 15:01
> Upgrading to VS 17.6.0 64-bit Community Edition did not fix this problem for me. When I upgraded from CommunityToolkit.MVVM 8.0.0 to 8.2.0, I got the same behavior as before; after a few minutes of coding, bogus errors start showing up. Attached is a screenshot of two representative errors. With a few more minutes of coding, there will be dozens more. The most common errors I see are "Ambiguity between Foo.Bar and Foo.Bar" and "Generator XYZ failed to generate source because the hint name 'FooPackage.Foo.Bar.g.cs' must be unique." Despite the errors in the error list, the project compiles normally and runs fine. ![Screenshot 2023-05-19 094545](https://user-images.githubusercontent.com/10959016/239550432-041b9fe5-066d-4647-8976-161e8946c83f.png)

Out of curiosity: Do you have commands/fields that have the same name as the classes?
Because this was my observation which might cause the issues to arise.

**Comment by DJRM2021** [comment] 2023-05-30 15:46
> > Upgrading to VS 17.6.0 64-bit Community Edition did not fix this problem for me. When I upgraded from CommunityToolkit.MVVM 8.0.0 to 8.2.0, I got the same behavior as before; after a few minutes of coding, bogus errors start showing up. Attached is a screenshot of two representative errors. With a few more minutes of coding, there will be dozens more. The most common errors I see are "Ambiguity between Foo.Bar and Foo.Bar" and "Generator XYZ failed to generate source because the hint name 'FooPackage.Foo.Bar.g.cs' must be unique." Despite the errors in the error list, the project compiles normally and runs fine. ![Screenshot 2023-05-19 094545](https://user-images.githubusercontent.com/10959016/239550432-041b9fe5-066d-4647-8976-161e8946c83f.png)
> 
> Out of curiosity: Do you have commands/fields that have the same name as the classes? Because this was my observation which might cause the issues to arise.

Unfortunately, my use case is different. I do not have any class properties that have the same name as their classes. Most of the time here's my pattern:

`public partial class Foo : ObservableObject
    {
        [ObservableProperty] string fooBar;
    }`

**Comment by KuroiRoy** [comment] 2023-06-08 09:39
Can confirm this is still an issue. We're running CommunityToolkit.MVVM 8.2.0 and Visual Studio 17.6.2.

Builds work fine, but Visual Studio does not. Restarting VS doesn't help but switching to 8.0.0 fixes it

**Comment by CyrusNajmabadi** [comment] 2023-06-08 16:18
17.6 is very buggy wrt SGs.  Would recommend using 17.7 instead.

**Comment by codengine** [comment] 2023-06-08 16:25
> 17.6 is very buggy wrt SGs. Would recommend using 17.7 instead.

From my knowledge there is no 17.7 yet

**Comment by CyrusNajmabadi** [comment] 2023-06-08 16:31
You can get it here: https://visualstudio.microsoft.com/vs/preview/

It runs sxs with non-preview VS.

**Closed** 2023-06-15 22:40 UTC
Labels: Bug, Area-Compilers, New Feature - Source Generators

**Comment by heartacker** [comment] 2023-06-15 22:48
When can we earn this fix?

**Comment by Sergio0694** [comment] 2023-06-15 22:56
It was just merged so I assume it should be in VS 17.7 Preview 4 (maybe 3, but that seems unlikely?).

**Comment by polymorphicshade** [comment] 2023-06-15 23:39
@Sergio0694 I'm excited to try this when it's available. Thank you and the team for working on this 😀

**Comment by DJRM2021** [comment] 2023-06-16 04:50
This is great news! Can't wait to try it!

**Comment by heartacker** [comment] 2023-07-09 02:53
But when releasing the update, I want to know what update we need to installing to solve this problem
1. vscode's c# extension
2. THE  .NET SDK7
3. VS 2022

@Sergio0694 

or something else?

**Comment by Sergio0694** [comment] 2023-08-11 19:18
Try VS 17.7?

**Comment by xlievo** [comment] 2023-08-11 21:30
> Try VS 17.7?
Unfortunately, 17.7.0 also has the same issue.

I tried to describe as clearly as possible, 
a class library project for a multi-objective framework <TargetFrameworks>netstandard2.0; Net5.0</TargetFrameworks>,
The first vs generation was successful, but the second generation failed due to caching the cs file content of the netstandard2.0 target.

The following situations will succeed
1: Change the class library to any individual target framework
2: Command line publish specifying a separate target framework dotnet publish - f

So,,, my conclusion is that SG does not support the generation of multi-objective frameworks or has some unknown issues.

**Comment by huynhsontung** [comment] 2023-08-13 19:20
I am on VS 17.7 and I still get this issue :( I a solution clean and solution rebuild. No chance.
CommunityToolkit.Mvvm v8.2.1

![image](https://github.com/dotnet/roslyn/assets/31434093/f0fc193e-8f9b-4059-9a12-e6cb60983478)
