### ISSUE TITLE
IDE0044 (add readonly modifier) fires incorrectly for fixed buffers

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#26364] opened 2018-04-24 20:23 UTC
**Version Used**: 15.7.0 Preview 4.0

**Steps to Reproduce**:

1. In a new C# project, set "Allow unsafe" to true in the project properties.
2. In a new file, type
```C#
unsafe struct Foo
{
    private fixed byte _data[8];
}
```
2. Put caret on the _data field and press Ctrl . (light-bulb)

**Expected Behavior**:
No tip

**Actual Behavior**:
"Add readonly modifier" (IDE0044) is suggested to replace 'fixed' with 'readonly'.
If you take the suggestion, the app fails to compile with:
```
error CS0650: Bad array declarator: To declare a managed array the rank specifier precedes the variable's identifier. To declare a fixed size buffer field, use the fixed keyword before the field type.
error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression)
```

**Comment by rob8861** [comment] 2018-06-04 14:46
Hello,

I just wanted to indicate that this issue also in Unity when decorating a private variable as [SerializedField]. Roslyn marks the field with IDE0044 , however, no fix it suggested. In fact the tool tip is completely blank and the only "suggested fix" is to suppress it.

**Comment by Xwilarg** [comment] 2018-06-16 09:21
@rob8861 I have the suggestion to add a readonly modifier on Unity
![readonlymodifier](https://user-images.githubusercontent.com/20053454/41497517-225b4c92-7157-11e8-9fa8-c52c7e18fa34.png)

However the description is empty
![description](https://user-images.githubusercontent.com/20053454/41497536-4c840e64-7157-11e8-8645-260176b455b7.png)

**Comment by CyrusNajmabadi** [comment] 2018-06-16 18:30
@Xwilarg for those of us who are not Unity devs, could you explain what the issue is here?  Is this a field that is only ever written in a constructor?  Or is it written somewhere else?  If so, where?

**Comment by sharwell** [comment] 2018-06-16 21:02
@Xwilarg the empty description is a duplicate of #26219. If there are other issues, can you describe those in some additional detail?

**Comment by Xwilarg** [comment] 2018-06-16 22:51
@CyrusNajmabadi I think Unity documentation would explain better than me https://docs.unity3d.com/ScriptReference/SerializeField.html

I used them because they allow you to fill variable's values directly from the Unity editor
![unity](https://user-images.githubusercontent.com/20053454/41503006-6df72a92-71c8-11e8-8d60-965661bb7d03.png)

**Comment by CyrusNajmabadi** [comment] 2018-06-16 23:01
@Xwilarg That reference talks about a specific attribute being on certain fields.  However, in your post there aren't any attributes on "tookStairs".  So i'm a bit confused :)

**Comment by Xwilarg** [comment] 2018-06-16 23:30
@CyrusNajmabadi Oh sorry, in fact there was a [SerializedField] but it was out of the screenshot.

**Comment by PipoSigh** [comment] 2018-07-26 20:48
@Xwilarg this issue is also repaired using public variables instead a [SerializedField], and my question about this is, in a project dev, whit partners and friend in job is so important the hidden info principle?

**Closed** 2018-11-01 22:48 UTC
Labels: 4 - In Review, Area-IDE, Bug
