### ISSUE TITLE
Multiline method chaining doesn't increase indentation level inside array initializers

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#18568] opened 2017-04-09 21:01 UTC
**Version Used**: VS 2017

**Repro:**

```cs
public class Foo { }

public void Works()
{
    // Indentation level increases when Enter is hit
    new Foo()[|]
}

public void DoesNotWork()
{
    // Indentation level does not increase when Enter is hit
    new Foo[]
    {
        new Foo()[|]
    }
}
```

**Comment by Pilchie** [comment] 2017-04-10 17:02
Dupe of https://github.com/dotnet/roslyn/issues/779.  We don't actually format inside array initializers...

**Closed** 2017-04-10 17:02 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
