### ISSUE TITLE
Please publish debug symbols for Release builds

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#1524] opened 2015-03-24 16:41 UTC
Can you please publish PDBs for Roslyn assemblies in NuGet release & VS previews on a symbol server? (or even just as a download somewhere)

I'd be able to give much more detailed bug reports if I could load symbols and see what's actually going on inside a debugger.

**Comment by JoshVarty** [comment] 2015-03-27 23:24
+1

**Comment by mattwarren** [comment] 2015-04-22 08:46
+1

**Comment by davkean** [comment] 2015-10-21 06:12
@ManishJayaswal In this on track for the 1.1 milestone?

**Comment by ManishJayaswal** [comment] 2015-10-28 06:08
@amcasey likley a dupe of #3

**Comment by amcasey** [comment] 2015-11-07 00:55
@agocke probably subsumed by #3.

**Comment by agocke** [comment] 2015-11-19 04:40
Dup of #3

**Closed by agocke** 2015-11-19 04:40 UTC
Labels: Area-Infrastructure
