### ISSUE TITLE
double click doesn't select whole word

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35954] opened 2019-05-24 22:19 UTC
VSF_TYPE_MARKDOWNI have  &quot;வாழைப்பழம&quot; in the code editor. I expect the whole word to be selected if I double click on any letter.
Instead, depending on the place where I click, it either:
- makes caret go to the beginning of the word
- selects only latter part &quot;ப்பழம&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/578580/double-click-doesnt-select-whole-word.html
VSTS ticketId: 897045_
_These are the original issue comments:_

Visual Studio Feedback System on 5/23/2019, 01:53 AM (37 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-05-24 22:21
Reproduces in 16.1

`string ts = "வாழைப்பழம";`

Double click on the string.

Expected behavior: Whole string should be selected.

Actual behavior: Partial string is selected.

**Comment by vatsalyaagrawal** [comment] 2019-06-07 22:14
@olegtk is this editor?

**Comment by olegtk** [comment] 2019-06-07 22:33
The editor is selecting the span as provided by ITextStructureNavigator.GetExtentOfWord(point). Please check what Roslyn implementation of GetExtentOfWord returns in this case: https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/EditorFeatures/Core/Implementation/TextStructureNavigation/AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs#L43

**Comment by CyrusNajmabadi** [comment] 2020-03-09 03:38
@olegtk We see that we're within a string.  And because of that, we know this isn't a C# language construct.  So we call into:

```
                // Fall back to natural language navigator do its thing.
                return _naturalLanguageNavigator.GetExtentOfWord(position);
```

We got that navigator by calling:

```
            var naturalLanguageNavigator = _selectorService.CreateTextStructureNavigator(
                subjectBuffer,
                _contentTypeService.GetContentType("any"));
```

At runtime this is a:

```
▶ | _naturalLanguageNavigator.GetType() | {Name = "NaturalLanguageNavigator" FullName = "Microsoft.VisualStudio.Text.Operations.Implementation.NaturalLanguageNavigator"}
```

So i believe this is over to you @olegtk .  Do you want to move to editor?

**Comment by olegtk** [comment] 2020-03-09 16:24
Thanks, makes sense. I routed https://developercommunity.visualstudio.com/content/problem/578580/double-click-doesnt-select-whole-word.html to the editor, feel free to close this issue.

**Closed** 2020-03-09 16:25 UTC
Labels: Area-IDE, Bug, Developer Community

**Comment by TalonZA** [comment] 2022-11-11 12:48
Tools > Options > Text Editor > General > [ ] Select subword on double click

Just uncheck this
