### ISSUE TITLE
Highlight implemented members in current file when selecting an interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53864] opened 2021-06-03 20:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Highlight-implemented-members-in-current/1425780)._

---
On example below, left clicking `randomField` on `MyClass` will highlight the field and its usage (inside the parameter);
On the same class, after left clicking `IHasName`, I believe implemented members should be highlighted.

So, left clicking on `IHasName` on `MyClass.cs` should highlight both `name`, `PrintName`, and `IHasName` usages.

File 1 (IHasName.cs):
```
interface IHasName {
      string name { get; set; }
      void PrintName();
}
```
File 2 (MyClass.cs):
```
class MyClass : IHasName {
       public string name { get; set; }
       int randomField;
       
void PrintRandomField() => Console.WriteLine(randomField1);
       void PrintName() => Console.WriteLine(name);
       void SanityCheck() { if (!( this is IHasName)) { throw new Exception("This is madness!"); } }
}

```

I think this will speed up development :)

---
#### Feedback Bot on 5/18/2021, 08:20 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Mika Dumont [MSFT] on 5/27/2021, 02:47 PM: 

<p>Thanks for taking the time to provide this feedback! Have you tried the new inheritance margin feature? In 16.10 Preview 2 we added inheritance margin providing a visual representation for navigating and inspecting the inheritance chain. This option is off by default so you will need to turn it on in Tools &gt; Options &gt; Text Editor &gt; C# &gt; Advanced and select Show inheritance margin. Enabling inheritance margin will add new icons to the margins representing your code’s implementations and overrides. Clicking on the inheritance margin icon will display inheritance options that you can select to navigate to. Please give it a try and let us know if this accomplishes your request!</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

**Comment by CyrusNajmabadi** [comment] 2021-06-04 00:24
Closing out as by design. I don't think we would really desire to change highlight-refs in this fashion. And I think we have suitable other shopping features that can serve the desired purpose better (as mentioned by Mika)

@sharwell for gut check as well. Feel free to reactivate if you disagree Sam. Thanks!

**Comment by sharwell** [comment] 2021-06-04 00:50
I've wanted a way to see this in the past, so we could see what other people think.

**Comment by sharwell** [comment] 2021-06-15 15:52
Design review conclusion: The highlighting requested here sounds like a good idea, especially for cases like Metadata As Source where an unfamiliar document has been collapsed to definitions. The most important characteristic to ensure is cycling through highlighted references should _not_ rehighlight the document, since the highlights normally present for a member are different from the ones proposed by this feature.

**Comment by jmarolf** [comment] 2021-06-16 20:42
## Design Review

**Discussion:**
 - Suggestion was met with positive sentiment over the course of a long discussion. Concerns about how subtle it might be with suggestions for including this functionality in the planned outline view and even adding a new command “Go to implementing members”. The new command was argued to be overkill without further feedback though we want to think about this as part of a wholistic design. One important requirement that was teased out is that having the ability to persist the results (the set of implemented members) somewhere would be useful.

**Conclusion:**

 - @Cosifne to work on a complete design

**Comment by CyrusNajmabadi** [comment] 2024-10-22 19:17
We would take a targeted community pr here.

**Closed by CyrusNajmabadi** 2024-10-22 19:17 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, Dev17 IDE Priority
