### ISSUE TITLE
Return this type for fluent API

### ISSUE THREAD

**Issue by VanKrock** [dotnet/roslyn#23719] opened 2017-12-11 12:32 UTC
Hello, is it realistic to implement this [issue](https://github.com/dotnet/csharplang/issues/902) in NuGet package?
I want to write fluent API:
```csharp
    public interface IMyClass
    {
        this SomeChange(int value);
    }

    public class MyClass : IMyClass
    {
        private int _value;
        public this SomeChange(int value)
        {
            _value = value;
        }
    }
```

To use:
```csharp
    public class SomeClass
    {
        public IMyClass MyFirstClass => new MyClass().SomeChange(1);

        public IMyClass MySecondClass => new MyClass().SomeChange(2);
    }
```

Translate to this Code:
```csharp
    public interface IMyClass
    {
        void SomeChange(int value);
    }

    public class MyClass : IMyClass
    {
        private int _value;
        public void SomeChange(int value)
        {
            _value = value;
        }
    }

    public class SomeClass
    {
        public IMyClass MyFirstClass 
        { 
            get 
            { 
               var myClass = new MyClass();
               myClass.SomeChange(1);
               return myClass;
            }
         }

         public IMyClass MySecondClass 
         { 
            get 
            { 
               var myClass = new MyClass();
               myClass.SomeChange(2);
               return myClass;
            }
         }
      }
```

It's real?

**Comment by sharwell** [comment] 2017-12-11 13:09
It's not currently possible to modify the compiler in the proposed manner without replacing it. Technically, it would be possible to completely replace the C# compiler, but at that point you have a new language of sorts (or at least a dialect).

Closing this as a duplicate of dotnet/csharplang#902 to (partially) focus discussion, which provides the best chance that the proposal is eventually able to move forward.

**Closed by sharwell** 2017-12-11 13:09 UTC
