### ISSUE TITLE
Proposal: The C# nameof operator should support a way of referring to the current class and method without having to explicitly name them

### ISSUE THREAD

**Issue by billgr** [dotnet/roslyn#18575] opened 2017-04-10 13:44 UTC
## Problem

I should be able to use the **nameof** operator to refer to the current class and/or method in a way that enables me to copy/paste that same statement from one class/method to a completely different class/method without needing to update the class name or the method name.

Something like this is not very copyable:

```
        public class Class1
        {
            public void Method1()
            {
                Trace.WriteLine($"{nameof(Class1)}.{nameof(Method1)}: Some interesting message.");
            }
        }
```
After the copy/paste I will need to, obviously, update the message. But I shouldn't have to also update the reference to the current class/method.

## Solution

I want to be able say something along the lines of this instead:

```
        public class Class1
        {
            public void Method1()
            {
                Trace.WriteLine($"{nameof(class)}.{nameof(method)}: Some interesting message.");
            }
        }
```
It is often more productive to copy/paste/update a logging statement than it is to manually type a completely new one. It would be even more productive if we didn't have to keep changing the class and method names to match the context of the where the line was pasted.

**Comment by CyrusNajmabadi** [comment] 2017-04-10 13:52
Instead of using 'nameof', you can use CallerMemberNameAttribute on your actual trace function so that it picks up the caller's name automatically without you having to do anything.

**Comment by jrmoreno1** [comment] 2017-04-11 19:14
duplicate of https://github.com/dotnet/csharplang/issues/345

**Comment by jrmoreno1** [comment] 2017-04-11 19:15
@CyrusNajmabadi: that won't help with a property

**Comment by CyrusNajmabadi** [comment] 2017-04-11 19:17
What happens when you have a property?  If CallerMemberName doesn't work with properties, maybe that's the bug to fix?

**Comment by CyrusNajmabadi** [comment] 2017-04-11 19:19
Hrmm... i just tried it and it seems to work fine with properties.

**Comment by gafter** [comment] 2017-05-24 21:02
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

-----------------

I have not moved this feature request to the csharplang repo because I don't believe it would ever rise in priority over other requests to be something we would ever do in any particular release. However, you are welcome to move discussion to the new repo if this still interests you.

This may be close enough to https://github.com/dotnet/csharplang/issues/345 that discussion can continue there.

**Closed by gafter** 2017-05-24 21:02 UTC
Labels: Area-Language Design
