### ISSUE TITLE
Remove out of context suggestions from IntelliSense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59919] opened 2022-03-03 17:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-out-of-context-suggestions-from-I/1662323)._

---
In C#, when adding `using` statements on top of the file, it keeps suggesting `ushort` instead. Can it be de-prioritized way down below `using`?
Also, when typing in an expression, the `unchecked` keyword is suggested all the time when starting with `un...`. If I'm not mistaken, `unchecked` cannot be used inside an expression at all?
Also, I didn't find "smart IntelliSense" to be useful and disabled it. However, it still shows the matching identifier on top of the list, and not among its closest siblings (alpha-sort based), which is extremely annoying - can this be reverted to how it was earlier? (when "smart IntelliSense" is off)

---
#### Feedback Bot on 2/13/2022, 10:13 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment] 2022-03-09 19:51
Duplicate of #44459

**Comment by sharwell** [comment] 2022-03-09 19:52
`unchecked` is allowed in expressions:

```
int x = unchecked((int)(int.MaxValue + 1));

**Closed by jinujoseph** 2022-03-09 19:51 UTC
Labels: Area-IDE, Developer Community

**Comment by TahirAhmadov** [comment] 2023-05-18 15:31
@jinujoseph that issue is for the `ushort` shortcoming only, not the other two I raised.

@sharwell thanks for pointing it out, I personally never had to use that feature so I wasn't aware of this. Still, I think `unchecked` should be de-prioritized somehow, perhaps, basing on the history of usage? Per installation, perhaps? Or there could be a way to "hide"/"move way down" a keyword using some kind of a configuration setting or right-click in the Intellisense dropdown or something like that?

And finally, regarding item# 3, it is very annoying that even when "smart" Intellisense is off, the matching identifier is on top, and not among its siblings by alpha-sort, which makes it difficult to look for other members.

**Comment by sharwell** [comment] 2023-05-18 17:09
Hi @TahirAhmadov ,

Our tools only allow us to track one issue at a time, so we handled this according to the first issue mentioned. Can you provide more specific examples (including screenshots) relating to how you are encountering the other issues?

Thanks!

**Comment by TahirAhmadov** [comment] 2023-05-31 23:18
Regarding the `unchecked` being suggested by default in IS, I think it may have been fixed - it's now de-prioritized compared to other identifiers which also start with "un" (whereas I recall it wasn't in earlier versions).

Regarding the item # 3 and the sorting of suggestions in IS, please look at these screenshots. 
In the first screenshot, you can see that I unchecked "Promote likely items ...":
![image](https://github.com/dotnet/roslyn/assets/16783987/7b7db505-1f9f-45f7-b1dd-d3b3741427a9)

In the second screenshot, when I press Ctrl - J, it shows the existing identifier and other identifiers which contain the existing identifier:
![image](https://github.com/dotnet/roslyn/assets/16783987/0ac326d1-2bef-4fba-a964-5aedff187405)

In the third screenshot, I try to choose another identifier which is alphabetically adjacent to the existing one, but it requires me to hit down arrow repetitively to essentially go through half of the list, until I find the identifier I need:
![image](https://github.com/dotnet/roslyn/assets/16783987/d1ae29f1-923f-4795-bdec-a0fe3d79104c)

In the previous versions of VS, Ctrl - J always sorted the identifiers alphabetically, and finding other relevant identifiers was much easier: (this is VS 2017)
![image](https://github.com/dotnet/roslyn/assets/16783987/6cd00f2e-7bed-4fc6-acef-8ec655385ded)
