### ISSUE TITLE
Optionally include namespaces / symbol hierarchies in nameof

### ISSUE THREAD

**Issue by chucker** [dotnet/roslyn#7973] opened 2016-01-15 00:18 UTC
`nameof` is cool! But sometimes, I have an entire chain of symbols I want to reference.

For instance, suppose I want to store a default value for a property in a setting container:

``` C#
namespace FooCorp.BarProduct.UI
{
    public class SuperBaz
    {
        public int MaxAwesomeness { get; private set; }
    }
}

namespace FooCorp.Lib
{
    public class Settings
    {
        public static Settings CreateDefault()
        {
            var defaultSettings = new Settings();

            // without nameof
            defaultSettings["FooCorp.BarProduct.UI.MaxAwesomeness"] = 0;

            // with nameof, but wrong
            defaultSettings[nameof(FooCorp.BarProduct.UI.MaxAwesomeness)] = 0;

            // with nameof
            defaultSettings[$"{nameof(FooCorp)}.{nameof(BarProduct)}.{nameof(UI)}.{nameof(MaxAwesomeness)}"] = 0;
        }
    }
}
```

Without nameof, I can refer to the namespace, class, and property all in one go by chaining dots. With nameof, doing so only yields (as usually desired) the right-most symbol, which I can only work around by calling nameof multiple times, which 1) breaks compile-time safety should the class's namespace change or something else move around, and 2) is fairly ugly to compose and hard to read.

``` C#
namespace FooCorp.BarProduct.UI
{
    public class SuperBaz
    {
        public int MaxAwesomeness { get; private set; }
    }
}

namespace FooCorp.Lib
{
    public class Settings
    {
        public static Settings CreateDefault()
        {
            var defaultSettings = new Settings();

            // existing syntax
            defaultSettings[nameof(FooCorp.BarProduct.UI.MaxAwesomeness)] = 0; // returns MaxAwesomeness

            // proposed nameof syntax with optional argument
            defaultSettings[nameof(FooCorp.BarProduct.UI.MaxAwesomeness, partial)] = 0; // returns MaxAwesomeness
            defaultSettings[nameof(FooCorp.BarProduct.UI.MaxAwesomeness, complete)] = 0; // returns FooCorp.BarProduct.UI.MaxAwesomeness
        }
    }
}
```

I propose an optional argument with the two contextual keywords `partial` and `complete`, where the former reflects the current behavior and remains the default if the argument is omitted. `partial` was chosen as it is [already used as a contextual keyword for some cases](https://msdn.microsoft.com/en-us/library/x53a06bb.aspx).

**Comment by asvishnyakov** [comment] 2016-01-16 14:51
:+1:
How about just use modifiers (namespace, type, name...)?
```c#
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness, namespace)] // FooCorp.BarProduct.UI
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness, namespace, type)] // FooCorp.BarProduct.UI.SuperBaz
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness, namespace, type, name)] // FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness, type, name)] // SuperBaz.MaxAwesomeness
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness, name)] // MaxAwesomeness
defaultSettings[nameof(FooCorp.BarProduct.UI.SuperBaz.MaxAwesomeness)] // MaxAwesomeness
```
`namespace, class` and `name` keywords maybe just enumerators of enum (`Scope.Namespace, Scope.Type, Scope.Name`)

**Comment by AdamSpeight2008** [comment] 2016-01-16 19:00
Possible dupe of #3759

**Comment by chucker** [comment] 2016-01-16 19:19
Yep, I also thought of going to the flags enum route — `namespace | type | name`.

**Comment by gafter** [comment] 2017-03-24 20:21
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

I am not moving this particular issue because I don't have confidence that the LDM would likely consider doing this.

**Closed by gafter** 2017-03-24 20:21 UTC
Labels: Area-Language Design
