### ISSUE TITLE
MSBuildWorkspace doesn't raise warnings or errors if the app is targeting too low of a version of Roslyn

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [dotnet/roslyn#69578] opened 2023-08-15 20:59 UTC
On .NET SDK 7.0.307 I was able to use [GetCompilationAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project.getcompilationasync) to compile razor projects, however after updating to .NET SDK 7.0.4, it does not work anymore.

The issue might be related to [this](https://github.com/dotnet/roslyn/issues/61454) Roslyn issue, but I am not sure.
As I have described on that issue after updating to v7.0.4 [a workaround](https://github.com/dotnet/roslyn/issues/61454#issuecomment-1677525404) needs to be applied to be able to load the project successfully. After loading the project successfully, the compilation succeeds too, but the razor-generated files cannot be seen in the syntax trees.

**Comment by antonioaversa** [comment] 2023-10-03 12:59
@jasonmalinowski 
I reproduce a similar `NuGet.Frameworks` issue after moving from .NET SDK `7.0.400` to `8.0.100-rc.1.23463.5`, with `Microsoft.CodeAnalysis.*` dependencies set to `4.7.0-2.final` (latest available on nuget), when building a `net8.0` Razor minimal project via `MSBuildWorkspace`.

The very same project builds correctly when the build is performed from Visual Studio (Community 2022 17.8.0 Preview 2.0).

The error message is the following: `Could not load file or assembly 'NuGet.Frameworks, Version=6.8.0.69, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.` 

The version of `6.8.0.69` of `NuGet.Frameworks` has not been released yet - the latest publicly available version is [6.7.0](https://www.nuget.org/packages/NuGet.Frameworks/6.7.0).

**Comment by jasonmalinowski** [comment] 2023-10-03 17:26
@antonioaversa Yep, that's something we're working on fixing. Which TFMs was your app that was using MSBuildWorkspace targeting?

**Comment by antonioaversa** [comment] 2023-10-04 11:34
@jasonmalinowski 
The target frameworks of the project using the `MSBuildWorkspace` are `net48;net8.0`.
The target framework of the project being built by the `MSBuildWorkspace` is `net8.0`. It's a very simple `Library` project with `Sdk="Microsoft.NET.Sdk.Web"`, no references, latest `LangVersion` and a couple of razor files.

**Comment by jasonmalinowski** [comment] 2023-11-17 23:35
So I _think_ this bug can now be closed since https://github.com/dotnet/roslyn/issues/61454 is closed too; I don't see anything that was specific in this otherwise that isn't fixed by OOP builds?

**Comment by jasonmalinowski** [comment] 2024-01-03 00:33
Closing this now that the 4.9.0-2.final packages are out; if there's still issues people are running into it'd be best for us to have a new issue since there's a lot of different things being conflated here.

**Closed by jasonmalinowski** 2024-01-03 00:33 UTC
Labels: Bug, Area-Analyzers
