### ISSUE TITLE
CSharpMoveDeclarationNearReferenceCodeRefactoringProvider throw exceptions

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30977] opened 2018-11-06 08:41 UTC
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.State.TryInitializeAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.State.GenerateAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.ComputeRefactoringsAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2018-11-06 08:43
Dupe of https://github.com/dotnet/roslyn/issues/30976?

**Comment by heejaechang** [comment] 2018-11-06 08:43
got same thing from csharp side this time. I was doing navigate to so not sure why this suddenly throw. probably navigate to make a file opened up for preview and caret position caused it to happen?

**Comment by CyrusNajmabadi** [comment] 2018-11-06 08:43
@heejaechang You seem to have run into this twice.  Could you attach a debugger and then try to edit/navigate around the last place you were?  You might be able to hit this again.

**Comment by heejaechang** [comment] 2018-11-06 08:44
looks like VisualStudio\Core\Def\Implementation\ProjectSystem\VisualStudioWorkspaceImpl.cs @758 or code around it causing it.

**Comment by jasonmalinowski** [comment] 2018-11-07 02:48
@heejaechang Did you get a dump file?

**Comment by CyrusNajmabadi** [comment] 2022-02-04 21:50
No dump reported.  No reports from anyone else.  Closing out.

**Closed by CyrusNajmabadi** 2022-02-04 21:50 UTC
Labels: Bug, help wanted, Area-IDE
