### ISSUE TITLE
Assigning members of ICollection types with collection initializers can provably cause NullReferenceExceptions

### ISSUE THREAD

**Issue by Will-Boulton** [dotnet/roslyn#73679] opened 2024-05-23 22:03 UTC
**Versions Used**: main, C#12, C#9, ...

## **Steps to Reproduce**:

1. Create a member variable of some object which is of some reference type which implements `ICollection<T>`
2. Initialize a new instance of the object and assign to the member in an object initializer expression using a collection initialize
3. Compile and run the code, a `NullReferenceException` will be thrown.

[sharplab repro](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQygg5hG6CeADgJYB2WANACYgDUAPgAIBMAjALABQjADAASNWAFgDcXLgDdMfKHwC8fUhADufAPIBrLgG8uASABiAeyPy+fbX1YU+zPgF8u9sZy6CAnAAoARJr7I4AGNAiAgqMO8AShdxTikEPmAzJVUAIShyPh0uc3MAejy+ABUAC2JkPgAbMgg+cr4YEtrCBCNgSogAWz5UOrAZCsIIBIBhAGUADgA2VgmGpr5OruBhuorSIxg60mIYYihqgC8wmTAYVcbawJgjBJzcgvmIUhkYc87CPcybgeRiLBeyl2JRkfECRkqHWuxCMLzIu32R1WQMhMkqyig+AqSAClS2ZFBADk4JCAEoQSBIUghACiAA8Qp8YS97vlCisyFh5q1lC9YHwEHAXnslgA6LKcQwmMwWKw2Oz2CisiW5PiPACS/Uui2Wq3q4UClUwJyg6xJRvatUuwoWVH2AKMyD2gT442mAHZ+PUEFByicCdr4XsDsRjglqk7tk7oFRlY8MQgdpkoMAjHAtrJCI6/u18IpzTrOisEOLlekEgpLNZbA5lXHCuqZNg4FaSvz+dqhcy+EYtU1kFblKYSBAQhVewJWFMZKQDlj6vVZOCPsQjXtYXxhq0EsghoFiGBiIEDpU80LwglLgOwbC7evSMgQPWenwAIINIi1IqsPhtiqyJYi1WCdZCQSlnhCD8hj4ZQykCEFiA+DollIGAKnVEYIShe8AB4imYAA+Z9elKWpAOLNZN2BVZZEPCBKioHsEgyGR02HVohgQGB8GI4o2y2ci9XWTZtgRENjkYqhEE5G8HxgQVoQ3Cdv14184R2YMkXDcp8RtK4jHCWSnQUr4uW/V53k+CoflNP4AQaUxtUEhJeFBcFIVHe9RM00NhnrfzOFVDUbXqZAQlnBAYVdSYpk9AZQQTJMuQXB84DAQ992eDMKl2SiWiMKRLXmDsFmcyiNi2AArOBIyzZAc1PfNIRsZ9gHTAVYCaBJcoAfT/HqHMSWpSHNGwMkYy4wNuWoUUqNEMSxMEoBq2pQKFEVaggBkICZWFRScGJXG4ABmAQ7HSTJskCh5Cm1ZcSA6br/0qJAoCoPMUw6Qb4NHDQ+lBfLOO48qRKDRFfMY4A821DanjBG4EnujpzgqTw3RmCZIn0RhToAGR0nCyBgAi+GMUxLBwGARHMAcqYcFVcmVHG+Hxp1CdQgiAH4+HLWVKep/xcGpxxOBF2I3FOlh1D+q69GZ1mYHZ4nSelbR+cFqn7GSFRPGiJxYiAA=)

**Diagnostic Id**: CS8618, CS8670

Depending if the field is declared as nullable or not one these two diagnostics will be raised at a warning level.

I argue that at the union of these two pieces of static analysis is a compilation error specifically under these conditions:
- A type `T1` has a member of a reference type which implements `ICollection<T2>`
- The member is either a field or an auto property
- That member is not initialized during construction of `T1`
- An initializer list in the code constructing `T1` attempts to assign to the member using a collection initializer

In this scenario CS8670 as a warning is insufficient as it is provable* that the member is not just possibly null, but rather it _has_ to be null, and therefore will always cause a runtime exception. This is probably worth a separate diagnostic at a error level.

*_I think the place where this may fall down is for types crossing assembly boundaries or imported from packages as it may not be possible to prove the member is not initialized during construction of `T1` from a compiled binary._

## **Expected Behavior**:

Code does not compile, a diagnostic is raised indicating that this is invalid due to de-referencing a null member.

## **Actual Behavior**:

Code compiles and throws a `NullReferenceException` at runtime.

**Comment by CyrusNajmabadi** [comment] 2024-05-23 22:20
> In this scenario CS8670 as a warning is insufficient as it is provable* that the member is not just possibly null, but rather it has to be null

There is no such concept in the language or compiler.  All we have is "believed to be not null" and "believed to be possibly null", there is no "has to be null".  As such, we just warn.  This was an explicit decision at the language level as analysis to be certain something is certainly null is too expensive and costly (both in terms of design and impl) to be felt to be worthwhile.

**Comment by CyrusNajmabadi** [comment] 2024-05-23 22:22
Note: this is clearly evident even when doing simple things like `X x = null; /*nothing intervening*/ x.`. Even in these trivial cases, we warn instead of error.  

Closing out as by design.  @jaredpar let me know if you disagree with that assessment.

**Closed by CyrusNajmabadi** 2024-05-23 22:22 UTC
Labels: Area-Compilers, untriaged

**Comment by Will-Boulton** [comment] 2024-05-24 20:20
Thanks @CyrusNajmabadi, I thought that may be the case!

**Comment by CyrusNajmabadi** [comment] 2024-05-24 21:51
yw :)
