### ISSUE TITLE
IntelliSense still outputs "errors" in the Output window when it cannot file files due to races

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17131] opened 2017-02-14 00:22 UTC
1. Create a new Console App (.NET Framework)
2. Delete Program.cs

Expected: No error
Actual in the Output window I get this "error":

```
[Failure] Could not find file 'c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs'.
```

**Comment by davkean** [comment] 2017-02-14 00:23
I was under the impression this was being fixed for this release - but cannot see a bug that represents it.

**Comment by Pilchie** [comment] 2017-02-15 18:26
Duplicate of https://github.com/dotnet/roslyn/issues/12202

**Closed by Pilchie** 2017-02-15 18:26 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
