### ISSUE TITLE
Warn about possibly unintended behavior in `x is not A or B` pattern matching expressions

### ISSUE THREAD

**Issue by dubiousconst282** [dotnet/roslyn#71204] opened 2023-12-11 03:32 UTC
Pattern matching makes it convenient to check that a variable is equal to any of a few other values/classes, but negating such a pattern by prepending `not` can lead to unintended results due to operator precedence rules.

Currently, `x is not A or B` will be parsed as `x is (not A) or B` and compile without warnings, which may often have an unintended behavior because `is B` is unreachable after `is not A` (unless one is a class that derives from the other).

### Describe suggestions on how to achieve the rule
The analyser could check for expressions like `x is not A or B` and warn or offer to insert parentheses in one of such ways, for clarity:
- `x is not (A or B)`
- `x is (not A) or B`  (only if `B` is a class deriving `A`)

**Comment by mavasani** [comment] 2023-12-11 07:42
Moving to Roslyn repo as this is a suggestion for flagging potential unintentional usage of new C# language features.

**Comment by jaredpar** [comment] 2024-01-02 22:44
Closing as this behavior is by design. Consider that our behavior with `not a or b` binds exactly like `!a || b` and there is no call for a warning in that case.

**Closed by jaredpar** 2024-01-02 22:44 UTC
Labels: Area-IDE, Feature Request, Need Design Review, IDE-CodeStyle
