### ISSUE TITLE
Bad parser error recovery in initializer expressions

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#71065] opened 2023-12-02 23:40 UTC
Repro: https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzggPgAQEwEYCwAUJgMwAEOZAwmQN5FmMXmYAsZAsgBQCUdDTQQDcIAJzIAPAJ4AvMgF4yMAKYB3MgA1Z/QoL1MNCsgFYA3AP0Bfc7v0VcATi4AiABbKANh4D2znjcFLIiDCIlFlAGNvUQATTVkieltGUjJYBE06MgBzZQRTNJgofLIQwVT0sgBNLNyS2GKCsqYKmAyALVq8goaSkMsgA==

Text:
```
public class C {
    public void M() {
        var xyz = new Xyz {
            X = 5;
        };
        Console.WriteLine("hello");
    }
}
```

Notice the semicolon. after `X = 5`. That should be a comma. But rather than eating it as a skipped token, the parser is ending the parse for the initializer. This causes bad downstream effects, with errors on the Console.WriteLine below.

**Comment by sdelarosbil** [comment] 2024-01-17 22:18
Hey, can I take this?

**Comment by CyrusNajmabadi** [comment] 2024-01-17 23:17
Yup!  Go for it!

**Comment by sdelarosbil** [comment] 2024-01-18 17:21
@CyrusNajmabadi Hey so I investigated this thoroughly and I think this one is very nuanced when it comes to addressing it.

Basically, there's 2 erroneous cases that have a different ideal solution, but seems mutually exclusive to me. Here's the one reported in this issue:
```cs
public class C {
    public void M() {
        var xyz = new Xyz {
            X = 5;
        };
        Console.WriteLine("hello");
    }
}
```
Here, the solution is to eat the ; after the initializer member (either expecting a comma or just a skipped trivia, either would work). I assume if everything was simple, we would just fix this by doing this (was thinking of passing `allowSemicolonAsSeparator` to true on the `ParseCommaSeparatedSyntaxList` call which would eat it expecting a comma).

The problem is checking the unit tests, there's another similar case with a different ideal solution that competes with the first one:
```cs
public class C {
    public void M() {
        var xyz = new Xyz {
            X = 5;
        Console.WriteLine("hello");
    }
}
```
Here, the solution is to expect a } before the ; which would fix this. This is what the current logic does: it sees the ; as terminator to the declaration so it stops the list parsing (but doesn't eat the ;), sees that it's missing a closing brace and then actually eats the ; correctly because it sees it as the actual terminator of the declaration.

I guess if we view the amount of diagnostic, the second case is cleaner (it just expects a } before the ;}, but this same logic is what prevents the first case to be simplified. That same logic on the first case means that it will see the }; tokens as just stray tokens after the declaration has been fully parsed. This is why we see a lot of error propagation further. On the other hand, I tried to see what would happen if I sent `allowSemicolonAsSeparator` as true and what it does is the first case gets simplified to eating the ; expecting a comma while the second case is now 3 diagnostics (but then continues as normal):
- Eats the ; expecting a comma
- Sees a missing }
- Sees a missing ;

So this is where it become nuanced enough to ask what would be the best here? A lot of the unit tests on error recovery seems to be based on the second case instead of the first one, but intuitively, I feel the second case is harder to recover than the first.

On another note: I am not sure I like the impact the current logic has on the syntax tree. Checking the provided sharplab link reveals the current logic kinda makes it look like a mess: it starts to see weird stuff like the Console.WriteLine is an IncompleteMember with the param list...a tuple? It's actually worse when I check an even simpler case:
```cs
var xyz = new Xyz { X = 5; };
```
Now, the declaration ends on the first ;, the } is a skipped trivia and the last ; is an empty statement.

So it seems to me that the current logic is worse than the one I am thinking of, but it does make the second case I presented 3 diagnostics instead of 1 hence why I am asking if it still seems like a good solution or if there's a way to fix this I am not seeing.

**Comment by CyrusNajmabadi** [comment] 2024-01-18 18:26
Currently on vacation. Agree this is nuanced.  

Short advice: instead of always trying to be resilient to ; appearing in the initializer, only do so (i.e. "consume as if it was a comma) if what follows is a reasonable continuation of the initializer. 

So only mage the change of what follows is a `}`, or `name =`, or `[` (which can start an indexed assignment. 

So, in the case you listed, with Console.WriteLine, it would be change behavior. 

I hope that helps!

**Comment by sdelarosbil** [comment] 2024-01-18 20:52
> Currently on vacation. Agree this is nuanced.
> 
> Short advice: instead of always trying to be resilient to ; appearing in the initializer, only do so (i.e. "consume as if it was a comma) if what follows is a reasonable continuation of the initializer.
> 
> So only mage the change of what follows is a `}`, or `name =`, or `[` (which can start an indexed assignment.
> 
> So, in the case you listed, with Console.WriteLine, it would not change behavior.
> 
> I hope that helps!

I think I will end up doing this because it does half work, but when trying it, the test cases still gets more diagnostic:

```cs
class c { void m() { var x = new C { a = b; } }
```
This I don't even know what you can do here: the next token is a `}`, but if we go by the ideal solution (expect a `}` before the `;`), it's not the list one, it's the method's body end. So it still ends up unsimplifying the diagnostics like I said above, but it would preserve cases where there is something after the `;`.

What I'll do is I'll do the changes, open a pr and we'll see if this is still okay because it still guarantees the errors don't propaguate compared to the current logic and it still gives a better syntax tree, it's just these edge cases might have more diagnostics than before.

**Comment by CyrusNajmabadi** [comment] 2024-01-19 00:00
Unbalanced curlies is a general problem no matter what. I wouldn't concern yourself too much about this, or try to resolve that sort of issue. 

In other words, I think it's fine for the curly to terminate the initializer.

**Closed** 2024-02-08 20:11 UTC
Labels: help wanted, Area-Compilers
