### ISSUE TITLE
Xml doc produced for function pointers have a blank type

### ISSUE THREAD

**Issue by steveharter** [dotnet/roslyn#62565] opened 2022-07-12 16:15 UTC
**Version Used**: 
 4.2.0-4.22220.5 (VS 17.2.0 Preview 6.0)

**Steps to Reproduce**:
1. Create a class library:
```cs
namespace ClassLibrary1
{
    /// <summary>
    /// Class1
    /// </summary>
    public class Class1
    {
        /// <summary>
        /// Summary for MyFcnPtrMethod1
        /// </summary>
        /// <param name="f1">Pass f1 please</param>
        public static unsafe void MyFcnPtrMethod1(delegate* unmanaged[Stdcall, SuppressGCTransition]<int, void> f1) { }

        /// <summary>
        /// Summary for MyFcnPtrMethod2
        /// </summary>
        /// <param name="f2">Pass f2 please</param>
        public static unsafe void MyFcnPtrMethod2(delegate*<int, void> f2) { }

        /// <summary>
        /// Summary for MyNormalMethod
        /// </summary>
        /// <param name="i">Pass i please</param>
        public static unsafe void MyNormalMethod(int i) { }
    }
}
```

2. Turn on allow unsafe code and XML doc:
```
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
```

Inspect the produced .XML file

**Expected Behavior**:
```
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary1</name>
    </assembly>
    <members>
        <member name="T:ClassLibrary1.Class1">
            <summary>
            Class1
            </summary>
        </member>
        <member name="M:ClassLibrary1.Class1.MyFcnPtrMethod1(delegate* unmanaged[Stdcall, SuppressGCTransition]<int, void>)">
            <summary>
            Summary for MyFcnPtrMethod1
            </summary>
            <param name="f1">Pass f1 please</param>
        </member>
        <member name="M:ClassLibrary1.Class1.MyFcnPtrMethod2(delegate*<int, void>)">
            <summary>
            Summary for MyFcnPtrMethod2
            </summary>
            <param name="f2">Pass f2 please</param>
        </member>
        <member name="M:ClassLibrary1.Class1.MyNormalMethod(System.Int32)">
            <summary>
            Summary for MyNormalMethod
            </summary>
            <param name="i">Pass i please</param>
        </member>
    </members>
</doc>
```

**Actual Behavior**:
```
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary1</name>
    </assembly>
    <members>
        <member name="T:ClassLibrary1.Class1">
            <summary>
            Class1
            </summary>
        </member>
        <member name="M:ClassLibrary1.Class1.MyFcnPtrMethod1()">
            <summary>
            Summary for MyFcnPtrMethod1
            </summary>
            <param name="f1">Pass f1 please</param>
        </member>
        <member name="M:ClassLibrary1.Class1.MyFcnPtrMethod2()">
            <summary>
            Summary for MyFcnPtrMethod2
            </summary>
            <param name="f2">Pass f2 please</param>
        </member>
        <member name="M:ClassLibrary1.Class1.MyNormalMethod(System.Int32)">
            <summary>
            Summary for MyNormalMethod
            </summary>
            <param name="i">Pass i please</param>
        </member>
    </members>
</doc>
```

**Comment by svick** [comment] 2022-07-13 12:19
This is a duplicate of https://github.com/dotnet/roslyn/issues/46674 and related to https://github.com/dotnet/roslyn/issues/48363.

**Comment by 333fred** [comment] 2022-07-13 13:31
Closing as a duplicate of https://github.com/dotnet/roslyn/issues/46674.

**Closed** 2022-07-13 13:31 UTC
Labels: Bug, Area-Compilers, Feature - Function Pointers
