### ISSUE TITLE
Provide an option that forces accessibility modifiers, except on partial classes

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27837] opened 2018-06-14 10:18 UTC
I have a code style like the following:

``` C#

Parent.cs:

public sealed partial class Parent
{
   [...]
}

Parent.Nested.cs:

partial class Parent
{
   internal class Nested
   {
   }
}

```

I do this so that if I change the accessibility or other modifier of Parent I only need to change it one place. Unfortunately:

```
dotnet_style_require_accessibility_modifiers = always:warning
```

Forces me to always specify a accessibility on second declaration of Parent.

Please give me a way that lets me force accessibility *everywhere* except on partial classes if another partial declaration has already specified it.

**Comment by Logerfo** [comment] 2019-04-26 12:49
Why didn't this get any attention? Even the Windows Forms designer uses no accessibility modifiers for partial classes (`.designer.cs`). It's intriguing that there is no option to match the IDE code generator style itself.

**Comment by sharwell** [comment] 2020-05-04 20:18
Duplicate of #36544

**Comment by sharwell** [comment] 2020-05-04 20:18
@davkean I marked this as a duplicate of #36544, since that issue already went through a design review and has a follow-up action item linked to it.

**Closed by sharwell** 2020-05-04 20:18 UTC
Labels: Area-IDE, Feature Request, Need Design Review

**Comment by davkean** [comment] 2020-05-05 00:24
@sharwell  I don't follow, that bug has been closed as by design and there's no link to a different issue tracking this. Can you point me to the followup action?

**Comment by sharwell** [comment] 2020-05-05 00:57
@davkean The design notes are in https://github.com/dotnet/roslyn/issues/36544#issuecomment-531984637. The follow-up issue is https://github.com/dotnet/roslyn/issues/38715.

**Comment by davkean** [comment] 2020-05-05 00:59
That is tracking a different feature other than what is asked above and the linked bug. I don't want to consolidate modifiers, I want to only apply the visibility modifier to a single partial declaration.

**Comment by sharwell** [comment] 2020-05-05 01:08
Right. #36544 was requesting the same thing, but we determined that the current behavior is by design.

If you still want to exclude analysis of partial types, I would recommend one of the following approaches:

1. Implement a diagnostic suppressor which suppresses IDE0040 when it appears on a partial type. Here is [an example](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/RelaxTestNamingSuppressor.cs) of a diagnostic suppressor we implemented to exclude a naming rule from applying to test methods.
1. Disable IDE0040, and optionally replace it with an alternative rule tailored to the specific rules of your project.
