### ISSUE TITLE
Inline temporary refactoring should work from references as well as declaration.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#21892] opened 2017-09-02 14:46 UTC
**Version Used**: 

Visual Studio Community 2017 v15.3.2

**Steps to Reproduce**:

Type in the following code:

```vb

Public Module Module1
  Public Sub Main()
    Dim TempToInline = 12
    Console.WriteLine(TempToInline)
  End Sub
End Module
```
When you click the `TempToInline` variable in `Console.WriteLine(TempToInline)` the light-bulb actions available do not include the option to inline the temporary variable.

**Expected Behavior**:

Plugins like CodeRush for Rosyln which also provide the "inline temp" refactoring can do so from references to a variable or at the declaration of the variable. Visual Studio should do the same.

**Actual Behavior**:

Visual Studio only offers to inline the temp when when you click it on the declaration ` Dim TempToInline = 12`

**Comment by ericmutta** [comment] 2018-05-06 21:27
> @CyrusNajmabadi You can also just hit ctrl-rr, or f2.

May I ask what those shortcuts invoke? (I've remapped my shortcuts heavily, so on my machine pressing Ctrl+R immediately jumps to the Solution Explorer, I don't even get a chance to press the second R. Also F2 opens the Object Browser for me).

**Comment by CyrusNajmabadi** [comment] 2018-05-06 21:30
those are the "rename" shortcuts.

**Comment by sharwell** [comment] 2021-06-04 19:57
Duplicate of #34142

**Comment by sharwell** [comment] 2021-06-04 19:57
(The duplicate issue is newer, but that issue contains the design review commentary)

**Closed by sharwell** 2021-06-04 19:57 UTC
Labels: Area-IDE, Feature Request
