### ISSUE TITLE
Statement indentation level gets broken with comment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37408] opened 2019-07-22 18:53 UTC
```
if (true)
{
    //some comment
}
```

If you hit enter twice after the comment, the caret moves to curly bracket level.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/649720/statement-indentation-level-gets-broken-with-comme.html
VSTS ticketId: 948418_
_These are the original issue comments:_

Visual Studio Feedback System on 7/18/2019, 02:37 AM (4 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Enbi Zhang [MSFT] on 7/19/2019, 00:40 AM (3 days ago): <markdown><p>Thanks for your feedback.<br>
Which language of your project used? C#, VB or C++?<br>
Also did you install any extension? If yes, can you disable/uninstall them and reopen vs, see if the issue still occurs?</p>
</markdown>
savascilve on 7/19/2019, 02:19 AM (3 days ago): Hi,<br><br>It's C#. I've tried disabling all extensions one by one, no luck. Also I've tried on diiferent type of projects (class library, web api, console app, winforms..) on net framework 4.6.2, 4.7, .net core 2.1, .net core 2.2. <br><br>Attached a gif.<br>
Enbi Zhang [MSFT] on 7/21/2019, 06:42 PM (17 hours ago): <markdown><p>We have redirected your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by vatsalyaagrawal** [comment] 2019-07-22 18:53
Repros in 16.3.P1

**Comment by sharwell** [comment] 2019-07-22 18:54
Duplicate of #28752

**Closed by sharwell** 2019-07-22 18:54 UTC
Labels: Developer Community
