### ISSUE TITLE
Spaces missing in single-line dictionary initializers

### ISSUE THREAD

**Issue by breyed** [dotnet/roslyn#5340] opened 2015-09-18 19:14 UTC
When Visual Studio auto-formats indexer-style C# dictionary initializers with multiple pairs on the same line, it fails to insert a space after the opening brace and separating commas.

For example, type:

    var a = new Dictionary<int,int>{[1]=2,[3]=4};

Auto-format the document. The result is:

    var a = new Dictionary<int, int> {[1] = 2,[3] = 4 };

The result should be:

    var a = new Dictionary<int, int> { [1] = 2, [3] = 4 };

**Comment by gafter** [comment] 2015-09-20 16:35
Not sure where the relevant code is. IDE?

**Comment by breyed** [comment] 2015-09-20 21:03
This issue occurs in the Visual Studio 2015 C# editor. Does that answer your question?

**Comment by gafter** [comment] 2015-09-20 23:45
My question is for the Roslyn implementors: where is the misbehaving code, and which team should this be assigned to?

**Comment by Pilchie** [comment] 2015-09-21 16:22
Is this a dupe of #4280? Does the fix for that address the space after the ",".

**Closed** 2015-09-21 16:24 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate

**Comment by DustinCampbell** [comment] 2015-09-21 16:26
Yup. I can verify that this is working now.
