### ISSUE TITLE
Visual Studio: Navigate from compiled code file to GitHub

### ISSUE THREAD

**Issue by MintPlayer** [dotnet/roslyn#42021] opened 2020-02-20 13:55 UTC
(Suggestion)

# Navigate from Visual Studio to GitHub

When ctrl+clicking a symbol in Visual Studio, it takes you to the definition of the class/method. 
When the class is defined in a DLL, only the public headers can be displayed.

```
#region Assembly Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.0\ref\netcoreapp3.1\Microsoft.AspNetCore.Http.Abstractions.dll
#endregion
```

I'd think it would be convenient if the author of the DLL would have an option to provide a symlink to a GitHub file-url. This way anyone can ctrl+click on a symbol, see the metadata file and go to the corresponding GitHub page rightaway.

**Comment by jasonmalinowski** [comment] 2020-02-28 19:07
@tmat @sharwell Where is our primary bug to track this?

**Comment by tmat** [comment] 2020-02-28 19:47
https://github.com/dotnet/roslyn/issues/24349

**Comment by sharwell** [comment] 2020-03-05 00:38
Related to, but not a duplicate of #24349

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:30
Source link should subsume this.

**Closed by CyrusNajmabadi** 2024-10-21 19:30 UTC
Labels: Area-IDE, Feature Request, IDE-Navigation
