### ISSUE TITLE
Object initializer inside array initializer not formatted

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#22573] opened 2017-10-06 13:53 UTC
**Version Used**: 

Visual Studio 15.3.5

**Steps to Reproduce**:

Sample code:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var x = new[]
        {
            new{a=1}
        };
    }
}
```

**Expected Behavior**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var x = new[]
        {
            new { a = 1 }
        };
    }
}
```

**Actual Behavior**:
The object initializer inside array initializer not formatted.

**Comment by huoyaoyuan** [comment] 2017-10-06 13:55
I'm new to  the Roslyn repo, and want to do some contributions. Is there any instructions about adding tests and pull requests?

**Comment by Pilchie** [comment] 2017-10-06 15:45
This is a dupe of the issue that we deliberately don't format collection initializers.

@sharwell for the question about contributions.

**Comment by sharwell** [comment] 2017-11-01 12:42
@huoyaoyuan There are many different components in Roslyn, each with their own code and test locations. Our general contributor instructions are located in the [**Contribute!** section of the readme](https://github.com/dotnet/roslyn#contribute). The best thing to do is find an issue you are interested in working on, and asking in that issue where to start. We understand that it's easy for new contributors to miss some details, so we try hard to help people through any questions they have during the process. 😄 

Duplicate of #8269.

**Closed by sharwell** 2017-11-01 12:42 UTC
Labels: Area-IDE
