### ISSUE TITLE
All VB projects fail to load references in design-time build

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#20223] opened 2017-06-14 21:52 UTC
This is what it looks like in the editor:

![image](https://user-images.githubusercontent.com/573215/27156166-c8b4ca9a-5110-11e7-81d3-a3efd2458231.png)

I've tried `git clean -xdf && restore && msbuild Compilers.sln && devenv Compilers.sln` but the issue persists.

dump and workspace log here: 
\\mlangfs1\public\tyoverby\workspace_bug

**Comment by TyOverby** [comment] 2017-06-14 21:53
cc @jasonmalinowski @tannergooding @jaredpar @agocke

**Comment by jaredpar** [comment] 2017-06-14 21:54
Please list the version of VS that you are using.

**Comment by TyOverby** [comment] 2017-06-14 22:04
![image](https://user-images.githubusercontent.com/573215/27156631-b89356c0-5112-11e7-9cb8-6a09fbfc7452.png)

**Comment by Pilchie** [comment] 2017-06-14 23:15
This is expected, you need at least 15.3 P1 to edit Roslyn.

**Comment by Pilchie** [comment] 2017-06-15 15:41
BTW - this is happening because we started using `default` expressions in signatures, and that broke skeleton assembly generation.

Tag @jcouv

**Comment by jcouv** [comment] 2017-06-15 18:09
This is by design. If you use an older version of VS (that doesn't support C# 7.1), then the C# project in Roslyn won't compile (because we use some new features, like "default" literal), therefore squiggles.
Ty, feel free to verify with new VS and close the issue.

**Comment by davkean** [comment] 2017-06-20 04:15
What's the default literal?

**Comment by jcouv** [comment] 2017-06-20 04:52
`int x = default; // no need to spell the type, we infer it`
New in c# 7.1

**Comment by davkean** [comment] 2017-06-20 04:54
oh nice.

**Comment by davkean** [comment] 2017-06-22 05:56
I'm going to close this issue, on top of above, I believe we only added desktop support for VB in 15.3.

**Closed by davkean** 2017-06-22 05:56 UTC
Labels: Area-Compilers, Bug, Resolution-By Design
