### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.GenerateTypeInExistingEmptyFile_Usings_DefaultNamespace

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9670] opened 2016-03-10 21:59 UTC
PR: [#9648](https://github.com/dotnet/roslyn/pull/9648) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5058/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.GenerateTypeInExistingEmptyFile_Usings_DefaultNamespace

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by jmarolf** [comment] 2016-03-15 17:18
```
Stacktrace

MESSAGE:
Expected 0 items but found 1: Found analyzer exception diagnostics\r\nItems:\r\n warning AD0001: Analyzer 'Microsoft.CodeAnalysis.Diagnostics.CSharp.CSharpCompilerDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Cannot enqueue data after PromiseNotToEnqueue.'.\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at Roslyn.Test.Utilities.AssertEx.Fail(String message) in d:\j\workspace\roslyn_prtest---45fcf4bc\src\Test\Utilities\Shared\Assert\AssertEx.cs:line 314 
at Roslyn.Test.Utilities.AssertEx.Empty[T](IEnumerable`1 items, String message) in d:\j\workspace\roslyn_prtest---45fcf4bc\src\Test\Utilities\Shared\Assert\AssertEx.cs:line 499
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractDiagnosticProviderBasedUserDiagnosticTest.AssertNoAnalyzerExceptionDiagnostics(IEnumerable`1 diagnostics) in d:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\Test\Diagnostics\AbstractDiagnosticProviderBasedUserDiagnosticTest.cs:line 122
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractDiagnosticProviderBasedUserDiagnosticTest.<GetDiagnosticAndFixesAsync>d__5.MoveNext() in d:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\Test\Diagnostics\AbstractDiagnosticProviderBasedUserDiagnosticTest.cs:line 73 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractUserDiagnosticTest.<TestWithMockedGenerateTypeDialog>d__18.MoveNext() in d:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\Test\Diagnostics\AbstractUserDiagnosticTest.cs:line 448 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.<GenerateTypeInExistingEmptyFile_Usings_DefaultNamespace>d__187.MoveNext() in d:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\CSharpTest\Diagnostics\GenerateType\GenerateTypeTests_Dialog.cs:line 540 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)```

**Comment by jmarolf** [comment] 2016-03-15 17:21
dupe of https://github.com/dotnet/roslyn/issues/8178

**Closed** 2016-03-15 17:41 UTC
Labels: Area-IDE, Contributor Pain, Flaky, Resolution-Duplicate, Urgency-Now
