### ISSUE TITLE
VS2019-Debugger produces high CPU (depending on CancellationTokens?)

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/roslyn#44009] opened 2020-05-06 14:25 UTC
We're creating an application that contains a producer-consumer problem. There are more than 100 consumers who are notified of values. Each consumer runs in a Task.Run and is checking a CancellationToken to cancel it's work.

If this application runs in VS2019 (16.5.4 up-to-date) debugger it produces a high CPU usage. After detaching the debugger from a running application the CPU usage goes down to an expected value.

I was able to strip down the problem to this piece of code:

    private static void Main(string[] args)
    {
        Console.WriteLine("Press to start...");
        Console.ReadKey();

        var cts = new CancellationTokenSource();
        var cancellationToken = cts.Token;

        var buffers = (from _ in Enumerable.Range(0, 40)
                       let queueLock = new SemaphoreSlim(1)
                       let queue = new ConcurrentQueue<object>()
                       select (queueLock, queue)).ToList();

        async Task Producer()
        {
            var instance = new object();

            var loop = 0;
            while (!cancellationToken.IsCancellationRequested)
            {
                await Task.Delay(10, cancellationToken);
                foreach (var (queueLock, queue) in buffers)
                {
                    queue.Enqueue(instance);
                    queueLock.Release();
                }

                ++loop;
                if (loop % 100 == 0)
                    Console.WriteLine(loop);
            }
        }

        async Task Consumer(SemaphoreSlim queueLock, ConcurrentQueue<object> queue)
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                await queueLock.WaitAsync(cancellationToken);
                queue.TryDequeue(out _);
            }
        }

        foreach (var (queueLock, queue) in buffers)
        {
            Task.Run(() => Consumer(queueLock, queue), CancellationToken.None);
        }

        Task.Run(Producer, CancellationToken.None);

        Console.ReadKey();
        cts.Cancel();
    }

The problem lowers to arround half of the cpu usage if you change the line var cancellationToken = cts.Token to var cancellationToken = CancellationToken.None. The problem completely disappears if you substitute the SemaphoreSlim and ConcurrentQueue<T> to a BlockingCollection<T>. But this is not an option because this blocks all the threads in ThreadPool if no value is produced.

In our productive code we're using AsyncCollection<T> that causes the same problem. In that case we don't need a SemaphoreSlim but exclude this collection I used a SemaphoreSlim and ConcurrentQueue<T> to be sure that only natively provided types are used.

I posted this as a question on [stackoverflow](https://stackoverflow.com/q/61637293/2729609) and got the hint to post it here. That post contains an animated gif that shows the problem. I was not able to add a gif in here.

[Link to GIF](https://i.stack.imgur.com/nNRYP.gif)

**Comment by springy76** [comment] 2020-05-06 14:49
Just 2 cents since you mentioned AsyncCollection and BlockingCollection: Did you try what happens when using the classes in `System.Threading.Channels` namespace?

**Comment by jinujoseph** [comment] 2020-05-06 18:47
cc @tmat

**Comment by SebastianSchumann** [comment] 2020-05-07 05:19
@springy76 I tried channels but the problem is still the same.

The used code is:

    using var cts = new CancellationTokenSource();

    var channels = (from _ in Enumerable.Range(0, 40)
                    select Channel.CreateUnbounded<object>()).ToList();

    async Task Producer(CancellationToken cancellationToken)
    {
        var instance = new object();
        var writers = channels.Select(item => item.Writer).ToList();

        for (var loop = 0; !cancellationToken.IsCancellationRequested; ++loop)
        {
            await Task.Delay(10, cancellationToken);
            foreach (var writer in writers)
                await writer.WriteAsync(instance, cancellationToken);

            if (loop % 100 == 0)
                Console.WriteLine(loop);
        }
    }

    async Task Consumer(Channel<object> channel, CancellationToken cancellationToken)
    {
        var reader = channel.Reader;
        while (!cancellationToken.IsCancellationRequested)
            await reader.ReadAsync(cancellationToken);
    }

    foreach (var channel in channels)
        Task.Run(() => Consumer(channel, cts.Token), CancellationToken.None);

    Task.Run(() => Producer(cts.Token), CancellationToken.None);

    Console.ReadKey();
    cts.Cancel();

**Comment by SebastianSchumann** [comment] 2020-09-08 05:50
I tested version 16.7.2 and the problem still remains.

**Comment by SebastianSchumann** [comment] 2021-12-15 06:21
This Problem still remains in 16.11.8 and VS2022!

**Comment by CyrusNajmabadi** [comment] 2021-12-20 16:40
@SebastianSchumann please file an issue using:

![image](https://user-images.githubusercontent.com/4564579/146801587-86611145-3895-4bf3-929d-4e72c729f66b.png)

This will allow a trace to be uploaded with the report that will help us track down what component is at fault here.  It's possible it is roslyn, but it's also possible it has nothing to do with us.  Without the trace we won't be able to tell.  THanks!

**Comment by CyrusNajmabadi** [comment] 2021-12-20 16:41
@jinujoseph can we move this to debugger?

**Comment by SebastianSchumann** [comment] 2021-12-21 05:31
@CyrusNajmabadi I tried that but it will open a new issue (and I did it). I also tried to download all the files but I was not able to attach them here (the only error message I get is _is not included in the list_).

I tried to link that issue here - but I've to apologize because I'm not able to find the reported issue...

**Comment by SebastianSchumann** [comment] 2021-12-21 05:32
Oh sorry - it took some time to display it:
[https://developercommunity.visualstudio.com/t/VS2019-Debugger-produces-high-CPU-depen/1618470](https://developercommunity.visualstudio.com/t/VS2019-Debugger-produces-high-CPU-depen/1618470)

**Comment by CyrusNajmabadi** [comment] 2021-12-21 07:16
I'm closing this out as a dupe of https://developercommunity.visualstudio.com/t/VS2019-Debugger-produces-high-CPU-depen/1618470.  That issue will have the traces and can be properly routed to the debugger team to look into.

**Closed by CyrusNajmabadi** 2021-12-21 07:16 UTC
Labels: Bug, Interactive-Debugging, Area-Performance
