### ISSUE TITLE
Collapsed sections for cases inside of a switch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49041] opened 2020-10-29 16:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Collapsed-sections-for-cases-inside-of-a/1234520?preview=true)._

---
Right now, you can collapse switch statements, but not individual case inside it, just the whole thing.
Please add the option to also collapse individual cases inside of a switch.

---
#### Feedback Bot on 10/27/2020, 08:04 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2020-11-04 01:48
Duplicate of https://github.com/dotnet/roslyn/issues/29998

**Closed by jinujoseph** 2020-11-04 01:48 UTC
Labels: Area-IDE, Developer Community
