### ISSUE TITLE
Incorrect "use throw expression" refactoring

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#20389] opened 2017-06-22 10:29 UTC
**Version Used**: 
2.2.0.61624

**Steps to Reproduce**:

```cs
using System;
using System.Collections;

namespace Test
{
    public class Program
    {
        public static void Main()
        {
        }
    }

    public class DirectoryAttribute : CollectionBase
    {
        public object this[int index]
        {
            get => List[index];
            set
            {
                if (value == null)
                {
                    throw new ArgumentNullException("value");
                }
                else if (!(value is string) && !(value is byte[]) && !(value is Uri))
                {
                    throw new ArgumentException("!!", nameof(value));
                }

                List[index] = value;
            }
        }
    }
}
```

**Expected Behavior**:
No refactoring provided

**Actual Behavior**:
![untitled](https://user-images.githubusercontent.com/1275900/27429742-5d854e46-5770-11e7-859f-6e72f203133d.png)

**Comment by Pilchie** [comment] 2017-06-22 17:03
Dupe of https://github.com/dotnet/roslyn/pull/18679.

**Closed** 2017-06-22 17:43 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
