### ISSUE TITLE
Completions from unimported namespaces don't respect global usings

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66802] opened 2023-02-10 09:48 UTC
**Version Used**:
Latest `main`

**Steps to Reproduce**:
1. Create new console app
2. Go to project file and remove `ImplicitUsings` from there
3. Create new `GlobalUsings.cs` file and put `global using System;` line there
4. Go to `Program.cs`
5. Type `Console`

**Expected Behavior**:
There is only 1 `Console` completion

**Actual Behavior**:
There are 2 `Console` completions, one of which is from "unimported" namespace

**Demo:**
![devenv_cGJosa3rqW](https://user-images.githubusercontent.com/70431552/218059417-7110c276-1bde-4fe4-9180-4fb1925c4df5.png)

**Comment by Youssef1313** [comment] 2023-02-10 13:37
Duplicate of https://github.com/dotnet/roslyn/issues/58473

**Comment by CyrusNajmabadi** [comment] 2023-02-10 14:13
Closing as dupe

**Closed by CyrusNajmabadi** 2023-02-10 14:13 UTC
Labels: Area-IDE, untriaged
