### ISSUE TITLE
Completion window closes immediately when editing .cshtml files

### ISSUE THREAD

**Issue by dfkeenan** [dotnet/roslyn#9219] opened 2016-02-26 02:32 UTC
Hi,

I keep getting an issue where the code completion windows closes almost immediately without being able to make a selection when editing the code blocks in .cshtml files.  I have not tested this with other web files .vbhtml, .aspx etc.

I have not been able to reproduce it in a simple test application.  Could size of project/solution be a factor?

I have tried:
- Invalid syntax in a .cs file
- Invalid csharp syntax in .cshtml file
- Malformed html tags in .cshtml file

And various combinations there of.

Cheers,
dfkeenan

**Comment by DustinCampbell** [comment] 2016-02-26 17:16
@brettfo, we've seen lots of feedback about this problem coming through the VS Feedback channels as well. We need to get a repro and solve it.

**Comment by CyrusNajmabadi** [comment] 2016-11-02 05:36
@dfkeenan Can you provide a repro solution where this happens for you?

**Comment by dfkeenan** [comment] 2016-11-02 06:03
@CyrusNajmabadi I haven't been able to create a simple project that reproduces it.  It happens in the current solution I'm working on but I don't think I am allowed to hand over the code 😢

**Comment by dfkeenan** [comment] 2016-11-02 06:17
Interesting. I Just basically started with a vanilla MVC C# project added a model class, added a empty view (with model). And it was happening when editing the new view. I suppose I could send you that. But there could be other things going on like the fact I have several other instances of VS (with MVC projects) open.  Could that play some part?

**Comment by CyrusNajmabadi** [comment] 2016-11-02 06:40
It *shouldn't* matter that there were other instances of VS open.  (But VS is so complicated, i can't even state that with certainty).

Could you show the code you were typing, and where your cursor was?  And some sort of description of what sort of edits you were making?  Also, what version of VS are you using now?  And do you repro this sort of behavior with the latest beta of VS15?  Thanks!

**Comment by dfkeenan** [comment] 2016-11-02 22:47
OS: Microsoft Windows 8.1 Enterprise (Version	6.3.9600 Build 9600)
Visual Studio: Enterprise 2015 (Update 3)

Steps I did to Reproduce;

* Create new MVC 4 project
* A new model class:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class ExampleModel
    {
        public string Example { get; set; }
    }
}
```

* Added a new view with model (Views\Home\Example.cshtml)
```
@model WebApplication1.Models.ExampleModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Example</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

```

* Put cursor on last line and typed `@str.`. Completing selected and inserted `string`. Completion window flashed up (didn't stay open).
* Typed backspace then `.`. Completion window appeared as expected.
* Typed `e.`. Completion selected and inserted `Empty`, did not show completion window.
* Typed backspace then `.`. Completion window appeared as expected.
* Typed `com`, selected `CompareTo`. Typed backspace once completion window closed. (It stays open when doing the exact same steps in a .cs file.

Hope that wasn't confusing. I Haven't tried VS15.

**Comment by CyrusNajmabadi** [comment] 2016-12-16 21:50
@rchande Isn't this something you have fixed?

**Comment by Pilchie** [comment] 2017-01-09 23:17
@rchande Can you see if this still repros?

**Comment by rchande** [comment] 2017-01-10 17:32
@dfkeenan Can you tell us what build of Update 3 you're on? I can't reproduce this on 14.0.25431

**Comment by dfkeenan** [comment] 2017-01-10 23:20
My PC at work has:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Do you want a complete dump of the info in the About dialog?

It also  has a number of different versions of VS installed (2008 through 2015). Not sure if that would make any difference.

**Comment by jorgeleo** [comment] 2017-09-08 20:38
This is still happening on Visual Studio Community for mac... any hope to fix it? Intellisense is one of the primary functionalities of Visual Studio for over a decade

**Comment by rchande** [comment] 2017-09-08 20:53
@jorgeleo This bug is tracking behavior in Visual Studio for Windows. Can you file feedback for VS for Mac at https://developercommunity.visualstudio.com/spaces/41/index.html ? Thanks!

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:41
No reports in 7 years, and this is now handled by razor.  closing out.

**Closed by CyrusNajmabadi** 2024-10-19 21:41 UTC
Labels: Bug, Area-IDE
