### ISSUE TITLE
Naming suggestions should pluralize for collection types

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19574] opened 2017-05-17 01:03 UTC
For example in the following, I'd want "GetEvaluationHandlers":

![image](https://cloud.githubusercontent.com/assets/1103906/26134225/6d6faa50-3af0-11e7-958a-e910ea31b929.png)

**Comment by Pilchie** [comment] 2017-05-17 16:50
Dupe of https://github.com/dotnet/roslyn/issues/17987

**Closed by Pilchie** 2017-05-17 16:50 UTC
Labels: Area-IDE, Feature Request
