### ISSUE TITLE
Add documentation for IDE0211

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65762] opened 2022-12-05 08:55 UTC
<html>
<body>

IDE0211 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0211 | Convert to 'Program.Main' style program
-- | -- | --

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by mavasani** [comment] 2022-12-05 08:56
@Youssef1313

**Comment by CyrusNajmabadi** [comment] 2022-12-05 17:09
Dupe of https://github.com/dotnet/roslyn/issues/65760

**Closed by CyrusNajmabadi** 2022-12-05 17:09 UTC
Labels: help wanted, Area-IDE, Feature Request, Documentation, untriaged
