### ISSUE TITLE
abilty of indentation in XML documentation (inserting spaces)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40313] opened 2019-12-11 22:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/778040/abilty-of-indentation-in-xml-documentation-inserti.html)._

---
<p>If an example is inserted into docmenatation (summary), spaces are ignored, no indentation is possible. This reduces the readability of the documentation. Also, line breaks must be used.</p> <p>        /// &lt;summary&gt;<br>        /// &lt;example&gt;&lt;code&gt;<br>        /// &lt;br&gt;&quot;cfg_t&quot;: {&lt;/br&gt; <br>        /// &lt;br&gt;    &quot;members&quot;: {&lt;/br&gt;<br>        /// &lt;br&gt;         &quot;cfg&quot;: {&quot;class&quot;: &quot;cfg_t&quot;},,.... &lt;/br&gt;&lt;/code&gt;&lt;/example&gt;<br>        /// &lt;/summary&gt;</p><p>will be shown with all lines starting at the same column. Without breaks, single line will be shown.</p>

---
#### Jane Wu [MSFT] on 10/15/2019, 07:26 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Matteo Taveggia [MSFT] on 11/26/2019, 06:34 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by sharwell** [comment] 2019-12-11 23:01
Duplicate of #39140

**Closed by sharwell** 2019-12-11 23:01 UTC
