### ISSUE TITLE
What is the actual license for the CodeAnalysis assemblies?

### ISSUE THREAD

**Issue by Jaykul** [dotnet/roslyn#27524] opened 2018-06-06 17:25 UTC
The [NuGet package Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/), for example, points to a, uhm ... legacy ... [dotnet library license](https://www.microsoft.com/net/dotnet_library_license.htm), but also points to this project -- where the LICENSE.txt is clearly the Apache license...

There appear to be a few of these artifacts floating around: long-standing packages with the old dotnet library license, which appear to come from clearly open source projects -- I'm just trying to understand, because I'm taking a dependency on a project which took a dependency on this 😉

**Comment by Pilchie** [comment] 2018-06-06 17:52
IANAL, so please do not construe this as legal advice.  However, I did work *with* some of our lawyers on this process.

It may not be obvious at first glance, but there are two different artifacts at play herre:
1. **Compiled binary files (potentially with optimization data, signed by Microsoft's authenticode and strong name keys, etc).**  These are covered by the license contained in the package from which you acquired them.
2. **The uncompiled source code.**  This is covered by the Apache license, and allows you to compile your own binaries and distribute them under whatever license you choose.

**Comment by svick** [comment] 2018-06-06 18:14
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/20169.

**Comment by sharwell** [comment] 2018-06-06 19:01
Duplicate of #20169

**Comment by sharwell** [comment] 2018-06-06 19:02
Thanks @svick I didn't realize we had another issue tracking this :smile:

**Closed by sharwell** 2018-06-06 19:01 UTC
