### ISSUE TITLE
VB test CustomizableTagsForUnnecessaryCode intermittently failing in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46786] opened 2020-08-13 16:52 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=768040&view=results

```
Assert.Equal() Failure\r\nExpected: 2\r\nActual:   1
```

Stack trace
```
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.VB$StateMachine_6_CustomizableTagsForUnnecessaryCode.MoveNext() in /_/src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by tmat** [comment] 2020-08-13 16:58
@mavasani FYI

**Comment by sharwell** [comment] 2020-08-13 17:00
Skipped as part of #46787. @mavasani this is quickly moving to top of the priority list.

**Comment by mavasani** [comment] 2020-08-13 17:08
So, I have seen lot of related issues pop up - is the underlying cause still that some of our tests were using the `DefaultDiagnosticAnalyzerService` and now use the `DiagnosticAnalyzerService` that we actually ship in IDE? Just confirming before I investigate...

**Comment by sharwell** [comment] 2020-08-13 17:23
@mavasani This issue was improved by #46521 (before which I was able to reproduce 100% locally), but there is still some flakiness involved.

**Comment by sharwell** [comment] 2020-08-18 19:48
@mavasani Another case from #46931:

Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorTagGeneratedForSimpleError

Merge PR: https://github.com/dotnet/roslyn/pull/46913
Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=776388&view=ms.vss-test-web.build-test-results-tab&runId=24280238&resultId=180776&paneView=debug

Stack trace:
```
Assert.Equal() Failure\r\nExpected: 1\r\nActual:   0
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.VB$StateMachine_2_ErrorTagGeneratedForSimpleError.MoveNext() in /_/src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by allisonchou** [comment] 2020-08-18 22:06
Hit again here: https://dev.azure.com/dnceng/public/_build/results?buildId=776781&view=ms.vss-test-web.build-test-results-tab&runId=24294506&resultId=178536&paneView=debug

**Comment by mavasani** [comment] 2020-08-18 22:19
Investigating.. but the test is already disabled correct? https://github.com/dotnet/roslyn/pull/46787

**Comment by sharwell** [comment] 2020-08-18 22:22
@mavasani the driver is flaky. One test is disabled because it hit the race condition most often, but numerous other tests are potentially going to see it.

**Comment by mavasani** [comment] 2020-08-18 22:31
@sharwell Interesting thing is only VB diagnostic squiggle tests are flaky - other components or C# does not seem to be have these failure, so issue might be elsewhere? Anycase, I will investigate.

**Comment by sharwell** [comment] 2020-08-18 22:32
I've seen the failure in C# tests as well.

**Comment by allisonchou** [comment] 2020-08-19 05:24
Hit again here:
https://dev.azure.com/dnceng/public/_build/results?buildId=777134&view=ms.vss-test-web.build-test-results-tab&runId=24314366&resultId=120403&paneView=debug

and here:
https://dev.azure.com/dnceng/public/_build/results?buildId=777326&view=ms.vss-test-web.build-test-results-tab&runId=24326910&resultId=120790&paneView=debug

**Comment by mavasani** [comment] 2020-08-19 12:26
**Update:** I was able to modify one of these tests to get a pretty consistent local failure. For all occurrences of a failure, it seems that something is triggering cancellation on the solution crawler while running analyzers, which in turn means background analysis does not fully compute diagnostics.

![image](https://user-images.githubusercontent.com/10605811/90634074-028bea00-e1dc-11ea-80b4-a79e9266f493.png)

I am investigating what component is triggering this intermittent cancellation. However, it does feel that this is not a product issue, but a test issue - solution crawler being unable to finish analysis would lead to incomplete background analysis and hence incomplete diagnostics/tags from background analysis.

**Comment by mavasani** [comment] 2020-08-19 12:46
I have a dump at `\\mlangfs1\public\mavasani\DumpForTaggerBug\testhost.x86.dmp` in case someone is more proficient at root causing this scenario.

**Comment by sharwell** [comment] 2020-08-19 13:09
`_expeditedDelayCancellationTokenSource` does not represent cancellation. Rather, it means "the results of the operation after the delay are needed immediately, so stop all delays and produce the result". It's part of the reason our tests are as fast as they are.

**Comment by mavasani** [comment] 2020-08-19 14:24
Confirmed that this is a test regression, more details in PR description: https://github.com/dotnet/roslyn/pull/46965

**Closed** 2020-08-19 22:28 UTC
Labels: Area-Analyzers, Disabled Test, Test, Urgency-Now
