### ISSUE TITLE
InvalidOperationException when renaming in projection buffer

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#24054] opened 2018-01-04 20:49 UTC
Repro:

 1. Create an "ASP .NET Web Site (Razor v3)" // probably actually happens with any cshtml file
 2. Open About.html
 3. Add the following at the bottom
```html
<script>
    var x = 1;
    x++;
</script>
```

4) Rename "x" to "y"

100% repro on my box.  Doesn't happen if there's only one occurrence of "x".

Crashes if test DLL is installed (by design); shows an error dialog otherwise.

```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by amcasey** [comment] 2018-01-04 20:49
I see two open projection buffers: one with content type CSharp and one with content type TypeScript.  They have different inert content, but share the same RazorCSharp child.  I believe the issue is that, when the temporary rename is rolled back in the CSharp projection buffer, the RazorCSharp buffer is flagged as changing, causing the TypeScript buffer to be flagged as changed.  Since inline rename only unsubscribes each buffer from changes as that particular buffer is reverted, the TypeScript buffer change is observed (which it should not be) and triggers a second attempt to dismiss the rename session (which fails, since it has already been marked as dismissed).

**Comment by amcasey** [comment] 2018-01-04 20:50
Tracked internally as 510599.

**Comment by jinujoseph** [comment] 2018-01-08 20:05
dupe of https://github.com/dotnet/roslyn/issues/18277

**Closed by jinujoseph** 2018-01-08 20:05 UTC
Labels: Area-IDE, Bug
