### ISSUE TITLE
Should `static bool IsDefault<T>(T xx = default) => xx == default;` compile?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#35684] opened 2019-05-13 10:29 UTC
**Version Used**: 
sharplab.io(master/2.9.0)

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChsBmQgJnwGF8BvS/DwogNn2AHt+AG3wBJKABE4AMwgBXITCIAeACoA+ABSr8AD134AvPhQz5igJRH1eg4eMA7BUPIVOXXgOFjJZhTDo1LR19IxM/S2tbfABLKHwnIRd2TmJPQRFxKVl/aiDtaONTHMjDG1D7cJKYV3cAejq0vgyfbPMYABZ8kLsq9qsywqKImG0LVwBfIA=

**Expected Behavior**:
https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/proposals/csharp-7.1/target-typed-default.md
`xx == default` should be the same as `xx == default(T)`, and can't compile.

**Actual Behavior**:
`xx == default` is compile as `xx == null` without warns, and so `default(T) == default` is always false for struct.

**Comment by gafter** [comment] 2019-07-09 22:41
Placing in 16.3 milestone as if we need to make a (possibly breaking) change here, we should do so sooner rather than later.

**Comment by jcouv** [comment] 2019-08-08 05:10
Closing as duplicate of https://github.com/dotnet/roslyn/issues/36492
I'm working on a fix

**Closed by jcouv** 2019-08-08 05:10 UTC
Labels: Area-Compilers, Bug, Urgency-Soon
