### ISSUE TITLE
Should have a way to go from a Code Style fixer -> code style setting

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15757] opened 2016-12-08 08:38 UTC
For naming rules, I can go from the fixer to the rule, but for code styles, there's no association between the message that shows up in the ErrorList/Editor and the rule that enforces it:

![image](https://cloud.githubusercontent.com/assets/1103906/21003125/b97c1e42-bd7d-11e6-8ea8-0dfa3860eef5.png)

It looks like I'm expected to understand that "IDE0017" is controlled by the "Prefer object initializer" setting?

**Comment by Pilchie** [comment] 2016-12-31 22:08
We definitely want to generalize what we have in the other styles that do have the button.

**Comment by Pilchie** [comment] 2016-12-31 22:09
Can you take a look at how hard it is to add this for our current style analyzers that have Tools\Options settings?

**Comment by Pilchie** [comment] 2017-01-19 02:53
Dupe of https://github.com/dotnet/roslyn/issues/13439

**Closed by Pilchie** 2017-01-19 02:53 UTC
Labels: Area-IDE, Feature Request
