### ISSUE TITLE
IOperation GetOpeartionsToAnalyzer assert

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#32775] opened 2019-01-25 09:51 UTC
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Expected operation with kind 'Invocation' to be the root operation with null 'Parent', but instead it has a non-null Parent with kind 'ExpressionStatement'

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass14_0.<TryExecuteDeclaringReferenceActions>g__getOperationsToAnalyzeWithStackGuard|4(ImmutableArray`1 operationBlocksToAnalyze)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass14_0.<TryExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|3()

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean should......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

dump - \\mlangfs1\public\hechang\IOperationDump

**Comment by heejaechang** [comment] 2019-01-25 09:51
tagging @mavasani

**Comment by mavasani** [comment] 2019-01-25 13:38
Dupe of https://github.com/dotnet/roslyn/issues/26217

**Closed** 2019-01-29 19:10 UTC
Labels: Area-IDE
