### ISSUE TITLE
Code fix to move a type to another file also migrates the `#nullable X` directive, removing it from the original file

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#58533] opened 2021-12-30 14:11 UTC
**Version Used**: Visual Studio Version 17.1.0 Preview 1.1

**Steps to Reproduce**:

1. Have a file that contains at least 2 types, named after the one. Ensure a file-scoped namespace declaration.
2. Use a `#nullable X` directive above the first declared type (or the one that will be migrated to another file).
3. Use the code fix to move the one type to a new file named after it.

## Example File
```csharp
// File name: B.cs
namespace N;

#nullable enable 

public class A
{
    public A? Copy() => null;
}

public class B
{
    public B? Destroy() => null;
}
```

**Expected Behavior**:
Both the original and the created files contain the `#nullable X` directive.

**Actual Behavior**:
The `#nullable X` directive is moved along, but does not remain on the original file that contained it.

**Comment by sharwell** [comment] 2022-01-04 23:41
Duplicate of #19613

**Closed by sharwell** 2022-01-04 23:41 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement
