### ISSUE TITLE
Nullable annotation should not be added to foreach iterator variable

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#43665] opened 2020-04-24 21:39 UTC
**Version Used**: 16.7.0 Preview 1.0 (30023.18)

**Steps to Reproduce**:

[SharpLab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWAChiABAJgEYyAGLUygFgG5iyBme8rAYSwG9iWYVgAOAJwCWAN2QAXbAwBs9SuwA8AeVQArDAGM5APiwBxXBnHyA9uIAUASiwBeE3IAW46wHcsMDL4ActZyAJIAtqKY4bgKwACiAB76GKJyktYwjqxEIlhCIqScyvSMWADK1jEekjAA5o4FwoK5eSIAZrYYyPrudrLiWJIK4UMwZhZWcraODk1tLW0iAL7zq0TLQA=)

```cs
#nullable enable

using System;
using System.Collections.Generic;

public class C {
    private static IEnumerable<Object> Generator() => throw new NotImplementedException();
    
    public static void Something()
    {
        foreach (var item in Generator())
        {
        }
    }
}
```

In the VS editor, press Ctrl+. on the `var` keyword within the `foreach`. Execute the "Use explicit type instead of var" command.

**Expected Behavior**:

`object` replaces the `var` keyword.

**Actual Behavior**:

`object?` replaces the `var` keyword.

![image](https://user-images.githubusercontent.com/3548/80258904-98a27000-8641-11ea-91c1-94237468dbde.png)

While I get that Roslyn recently decided that implicit `var` types get nullable-annotations implicitly, in a `foreach` loop that makes no sense. The sequence being enumerated produces non-nullable items.  The C# does not allow for this variable to be assigned within the loop. Therefore it can *never* be null or assigned null. And therefore, should not carry the `?` annotation.

**Comment by jcouv** [comment] 2020-04-27 18:05
I think that makes sense (tweak to the ExplicitType fix/refactoring).

**Comment by sharwell** [comment] 2020-04-28 20:00
Duplicate of #41243

**Closed by sharwell** 2020-04-28 20:01 UTC
Labels: Area-IDE, Bug
