### ISSUE TITLE
CS8717 mis-fires for MaybeNullWhen out parameter

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#39656] opened 2019-11-03 14:19 UTC
**Version Used**: VS 16.5 Preview 1 (29502.12.master)

**Steps to Reproduce**:

1. Create a .NET Core 3.0 library or console app.
2. Introduce a source file with this content:

```cs
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

#nullable enable

class WKD<TValue>
{
    private readonly Dictionary<int, TValue> dictionary = new Dictionary<int, TValue>();

    public bool TryGetValue(int key, [MaybeNullWhen(false)] out TValue value)
    {
        return this.dictionary.TryGetValue(key, out value);
    }
}
``` 

**Expected Behavior**:

No warnings. I declare that `value` may be null when false is returned just like the method I'm calling.

**Actual Behavior**:

> Warning	CS8717	A member returning a [MaybeNull] value introduces a null value when 'TValue' is a non-nullable reference type.	

![image](https://user-images.githubusercontent.com/3548/68086519-31ca9980-fe0a-11e9-9c3d-efb883f0c17e.png)

I can't figure out any code change other than suppressing the warning with `#pragma` to eliminate the warning.

**Comment by mavasani** [comment] 2019-11-26 15:18
Likely dupe of https://github.com/dotnet/roslyn/issues/38638

**Comment by mavasani** [comment] 2019-11-26 15:18
Tagging @cston

**Comment by jcouv** [comment] 2019-12-11 00:35
The `[MaybeNullWhen(false)]` attribute only affects callers of the `WKD.TryGetValue` method. It currently does not affect the method body. This is a known limitation at the moment (we didn't have time for the initial release). This is tracked by https://github.com/dotnet/roslyn/issues/36039

Your example is a bit more tricky though (conditional) so it may still not work after that work item is done. So I think it is worth keeping this issue open at the moment.

**Comment by jaredpar** [comment] 2019-12-14 01:02
Letting #36039 be the primary driver here.

**Closed by jaredpar** 2019-12-14 01:02 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-Duplicate
