### ISSUE TITLE
Intellisense not ordering by casing

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#39764] opened 2019-11-11 23:31 UTC
[Internal customer feedback]

**Version Used**: VS2019 version 16.3

**Steps to Reproduce**:
```csharp
class Sample
{
  public Sample(string subject)
  {
  }

  public string Subject { get; }
}

```
1. Start typing "Subject = sub" in constructor

**Expected Behavior**:
Put "subject" at the top of the completion list. Not "Subject".

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/8293542/68629084-650ac980-0497-11ea-9c60-cedf23ebdfbc.png)

In a fuzzy matching scenario:
![image](https://user-images.githubusercontent.com/8293542/68629213-c468d980-0497-11ea-87b4-cce7659a68ee.png)

**Comment by Joe4evr** [comment] 2019-11-12 01:14
You know that [Capital letters come first in ASCII](https://en.wikipedia.org/wiki/ASCII#Character_set), right?

**Comment by kendrahavens** [comment] 2019-11-12 02:10
@Joe4evr I'm following up with customer for further clarification, but I believe the idea is that we should not put the mismatched casing higher than the results that match the casing for the entire intellisense list:

Let's say I'm trying to use the string "abcd". I have to scroll down past the capitalized strings to get to it.

![image](https://user-images.githubusercontent.com/8293542/68635679-2af8f200-04ae-11ea-8dd7-7e46a47e3edd.png)

This would mean that results aren't alphabetical, but do match casing.

**Comment by CyrusNajmabadi** [comment] 2019-11-12 05:18
The latter scenario seems contrived. And i'm not sure what's wrong with the former one.

**Comment by CyrusNajmabadi** [comment] 2019-11-12 05:19
> Put "subject" at the top of the completion list. Not "Subject".

Does this mean we'd be reordering the list *as* you type characters?

**Comment by sharwell** [comment] 2019-11-27 23:09
While IntelliSense is not _ordering_ by casing, it is _selecting_ by casing. While some IDEs restrict completion to only select the first item in the list by default (and therefore rely on ordering as a driver for selection), Visual Studio treats the two as independent operations. The relative order of `Subject` and `subject` in the list does not matter (the order will not influence the selection process), but it _does_ matter that we keep the behavior consistent over time.

Resolving this one as **By Design**.

**Comment by sharwell** [comment] 2019-11-27 23:16
Actually reopening this to get an answer on one specific thing: why is `Subject` sorting before `subject`, but `abc` sorts before `aBC`?

**Comment by genlu** [comment] 2020-01-02 22:12
@sharwell I'm actually seeing the expected sorting result

![image](https://user-images.githubusercontent.com/788783/71696354-a027cb80-2d69-11ea-8b81-d6cad12ce210.png)

**Closed** 2020-01-09 20:00 UTC
Labels: Area-IDE, IDE-IntelliSense, Question, Resolution-By Design
