### ISSUE TITLE
[Bug]: No IntelliSense pop-ups within interpolation expressions

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#70918] opened 2023-11-21 16:09 UTC
### Version Used

* Compiler version: '4.9.0-1.23530.4 (79d1884d)'
* VSCode: 1.84.2, 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, x64
* C# extension: v2.10.28, C# Dev Kit extension: v1.1.12
* IntelliCode for C# Dev Kit: v0.1.26

### Steps to Reproduce

1. Open or create any C# project.
2. Create an interpolated string and attempt to reference any symbol;
    ```cs
    int foo = 0;
    Console.WriteLine($"{foo}");
    ```
3. Observe the behavior as you are typing the symbol's name.

### Expected Behavior

Available symbols are suggested in usual IntelliSense fashion.

### Actual Behavior

No suggestions appear.

However, symbols do still appear to be suggested; hitting Tab after typing the beginning of a symbol's name does complete its name.

**Comment by 333fred** [comment] 2023-11-21 18:55
Are you referring to intellicode, or standard completion?

**Comment by just-ero** [comment] 2023-11-21 19:20
I'm not sure. What's the difference? I thought they were synonymous.

**Comment by CyrusNajmabadi** [comment] 2023-11-21 19:22
IntelliCode is the AI suggestions that completes out whole sentences at a time.  IntelliSense is the dropdown that pops up that helps you normally complete a word (or small number of words) at a time.

**Comment by just-ero** [comment] 2023-11-21 19:23
I thought it was the other way around. My bad.

**Comment by CyrusNajmabadi** [comment] 2023-11-21 19:24
NO worries :)  we just wanted clarity to ensure we knew what you were talking about.  Thanks!

**Comment by CyrusNajmabadi** [comment] 2024-10-26 17:54
No repro:

![Image](https://github.com/user-attachments/assets/b8ac39b8-10d9-4f68-8d85-b32f1658913c)

**Comment by just-ero** [comment] 2024-10-27 13:35
@CyrusNajmabadi
Is this controlled by something else in Visual Studio Code?

In other contexts, I get IntelliSense:
![Image](https://github.com/user-attachments/assets/f3e47ba3-6c02-49c6-a0b6-9045d9ca66b6)

But not in interpolated strings:
![Image](https://github.com/user-attachments/assets/ead0c1d8-2402-4591-8cfe-caa391a0e9c9)

**Comment by CyrusNajmabadi** [comment] 2024-10-31 14:15
@dibarbet can you ptal and see if there's something vscode/lsp specific causing an issue here?

**Comment by dibarbet** [comment] 2024-10-31 20:47
There seem to be multiple issues here.  

The first is with just typing a `{`.  In VS this never brings up completion by itself.  However in some contexts in VSCode, typing the `{` will bring up completion:
![Image](https://github.com/user-attachments/assets/567e5edd-7401-4836-9f01-8e7ecc7867ab)

but it doesn't happen in other contexts, for example typing `{` in  `CompletionResultFactory.cs` in Roslyn.sln *does not* bring up completion:
![Image](https://github.com/user-attachments/assets/5eee173b-14d0-484b-859a-4ca6292f1b81)

Secondly, typing a word character inside the curly braces should bring up completion (as it does in VS).  However in VSCode, this never happens.  I am guessing this is because vscode is classifying the cursor location as being inside a string - and VSCode does not automatically bring up completion in strings by default.  This is controllable by a setting though - for example if you add this to your settings:
```
"editor.quickSuggestions": {
    "strings": "on"
}
```
you will start getting completion when typing inside strings:
![Image](https://github.com/user-attachments/assets/c5e8c3dd-f77d-4c65-ab2c-3b563ebda8ed)

However this can be annoying as it will also show generally irrelevant generic vscode suggestions when hitting space inside a string
![Image](https://github.com/user-attachments/assets/303d175f-811c-44f4-a950-39f2bd5df0ab)

I'm not 100% certain how vscode makes the determination that it is in a string - I am guessing this comes from text mate.  We may need to adjust the text mate grammar here to make sure locations inside the curly braces are not considered as part of the string.

**Comment by dibarbet** [comment] 2024-10-31 21:40
Closing this as a dupe of https://github.com/dotnet/vscode-csharp/issues/5297

I believe I should have a fix for this soon, keep an eye on the linked issue for updates.

**Closed by dibarbet** 2024-10-31 21:40 UTC
Labels: Area-IDE
