### ISSUE TITLE
Intellisense tooltip should show docs from <exception> tag.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#58140] opened 2021-12-06 21:54 UTC
**Version Used**: 

Visual Studio Community 2022 v17.02

**Steps to Reproduce**:

Suppose you have code like this which uses XML doc tags:

```csharp
public class Foo
{
  /// <summary>This WILL be shown in tooltip.</summary>
  /// <exception cref="NotImplementedException">
  /// This will NOT be shown in tooltip.
  /// </exception>
  public static void Blah() => throw new NotImplementedException();
}
```

If you hover over the `Blah()` identifier, Visual Studio Intellisense shows a tooltip like this:

![image](https://user-images.githubusercontent.com/20465797/144927309-e72b1d3b-fc5a-49c6-81f7-9a79cc4955bd.png)

...notice how we only see text from the `<summary>` tag (i.e. the words `This WILL be shown in tooltip`). The docs for the `NotImplementedException` in the `<exception>` tag do NOT appear in the tooltip. **If you want to see all the docs, you currently have to open the Object Browser, where you see this:**

![image](https://user-images.githubusercontent.com/20465797/144927820-8e02e54e-eef8-45c8-bba3-0b78282af7b3.png)

**Expected Behavior**:

It would be pretty handy to be able to see ALL the docs for an element right there in the tooltip shown when you hover over it. I know for a fact its not a limit on how much text you have, because Visual Studio is happy to show really bad-ass tooltips like this one which contains hyperlinks, formatted text, coloured text, etc:

![image](https://user-images.githubusercontent.com/20465797/144928312-436d8037-7ed8-4c03-969f-1410965aee19.png)

**Comment by sharwell** [comment] 2021-12-06 22:01
Duplicate of #1515

**Closed by sharwell** 2021-12-06 22:01 UTC
Labels: Area-IDE, untriaged
