### ISSUE TITLE
C# code formating of braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39168] opened 2019-10-09 22:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/767939/c-code-formating-of-braces.html)._

---
[regression] [worked-in:16.2.x]
1. In a C# code editor, Type the following code in editor, Ensure the cursor after the close curly bracket :
```
       if () { }|
```

2.  Press &quot;Left Arrow&quot; key, Move the cursor between the two braces:
```
       if () {|}
```
3. Press &quot;Enter&quot; key, Then the code looks like this:
```
       if () {
|}

```

### **But here's what I expect:**
```
       if () {
          |
       }
```
or
```
       if ()
       {
          |
       }

```
This problem occurred after the update VisualStudio and was **previously normal.**

Ok, so mush.
best regards

---
#### Visual Studio Feedback System on 10/9/2019, 02:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment] 2019-10-15 19:37
@ryzngard  can you check if you can repro this.

**Comment by ryzngard** [comment] 2019-10-22 20:17
There are a few things listed here, so I want to be clear about the expected behavior. 

```c#
    if (true) { | }
```

Hitting enter here should result in the following code, which is by design

```c#
    if (true) {
    }
```

If the issue is that the opening brace remains on the line, then that is intentional. You can use format document to clean this up across the board (or other formatting tools) .

If the issue is that the resulting code is the following, then we have a bug. I was unable to reproduce this scenario though

```c#
    if (true) {
}
````

Please let me know which of these is the issue so we can follow up accordingly.

**Comment by sharwell** [comment] 2019-10-22 20:28
I was not able to reproduce the failure to indent the `}` character in Visual Studio 2017 (15.9), or in Visual Studio 2019 (16.3 or 16.4 Preview 2). Closing this as Not Reproducible based on the above.

**Closed by sharwell** 2019-10-22 20:28 UTC
Labels: Area-IDE, Bug, Developer Community, Need More Info

**Comment by Dreamescaper** [comment] 2019-10-22 20:37
> If the issue is that the opening brace remains on the line, then that is intentional. You can use format document to clean this up across the board (or other formatting tools) 

Just curious - why? Typing `'{' -> 'Enter'` leads to formatted brackets. Why moving cursor position back and forth changes behavior?

**Comment by ryzngard** [comment] 2019-10-22 23:57
I wasn't there for the original design decision, so take this as an informed opinion that may differ from reality. 

When typing `{` we have the context of being directly after that brace. We fill in the closing brace for you (settings variant) and try to assume that you want to comply with general code formatting. 

However, if we come across some arbitrary `if () { }` and you start typing in it, we try to assume as little as possible about your intent. You've already left the code like that, why should we make it harder to keep that way while editing? If you need to format it, we have the tools to do so. 

Given those two statements, it seems reasonable to bucket the scenario of cursor position change into the second one. You've already moved on in some way, so we drop our assumptions and behave more conservatively on auto format while typing. 

Hopefully that helps answer your question.
