### ISSUE TITLE
Can't use mouse to select formatting option lines

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#18614] opened 2017-04-11 23:14 UTC
"Tools, Options, Text Editor, C#, Code Style, Formatting, New Lines.

It's currently impossible to just select one of the items in the list with mouse click - it registers as a toggle for the checkbox, no matter where on the line you click. Generally I'm lazy so that's good, but it's not good when I want to select a different item/line.

Please stop toggling yet unselected lines. Only when selected should the toggling kick in."

**Comment by Pilchie** [comment] 2017-04-12 20:41
Similar to #13577

**Comment by tamlin-mike** [comment] 2017-04-30 07:00
@rchande Only four months since I reported that bug. Is the backlog getting thin? :)

@Pilchie Is that part of the proprietary VS source base, or is it in the open Roslyn src? If the latter I can take a look at it.

**Comment by CyrusNajmabadi** [comment] 2017-04-30 18:51
@tamlin-mike You can find this code in https://github.com/dotnet/roslyn/tree/master/src/VisualStudio/CSharp/Impl/Options/Formatting

**Comment by tamlin-mike** [comment] 2017-05-01 06:54
@CyrusNajmabadi Thanks.
After having looked into this, it seems the current behavior is to always consume a click as a selection-state change.

1. For a "normal" dialog property page, that is expected, as you don't have a list of options to move around in with cursor-key up/dn.

2. The problem is for the "special" pages, that kindasorta look like list controls, but are not, where if they have any top-level concrete options _at all_ the behavior mimics that of 1. If on the other hand they _don't_ have any top-level concrete items, as can be seen in
 _Tools->Options->Text Editor->C/C++->Formatting->New Lines_
they _do_ work as expected - allowing change-to-item on anywhere-on-the-line-except-the-actual-control-"icon" first click, and only once selected does the next click register as a toggle.

From my understanding this behavior is all implemented inside the proprietary VS Platform _Shell_, more specifically the interaction handler(s) for `ProvideLanguageEditorOptionPageAttribute`.

If that understanding is correct, this could only be fixed by Microsoft - and since it's not a crashing bug, it most likely won't ever get fixed. Sorry for the bad news.

**Comment by CyrusNajmabadi** [comment] 2017-05-01 19:02
> If that understanding is correct,

@Pilchie @dpoeschl Can you weigh in on this?  Is there nothing in the Roslyn side of things that can address this issue?

**Comment by diryboy** [comment] 2017-05-10 15:42
I think the code is in `src\VisualStudio\Core\Impl\Options\OptionPreviewControl.xaml`? The ServicesVisualStudioImpl project.

**Comment by diryboy** [comment] 2017-05-10 16:01
OK, I fixed this in my local build, will make a PR.

**Comment by tamlin-mike** [comment] 2017-05-10 20:42
@diryboy It was as simple as moving "TextBlock" in XAML? If so, no wonder I didn't grok it! I grepped the src (*.cs). If this fixes it: For you, the cake is no lie (ref. the game Portal).

**Closed** 2018-06-08 22:19 UTC
Labels: 4 - In Review, Area-IDE, Bug, _Product-level triaged
