### ISSUE TITLE
Support unbound generic types in nameof

### ISSUE THREAD

**Issue by jrote1** [dotnet/roslyn#5960] opened 2015-10-14 16:27 UTC
I think the following code should be valid for nameof:

    nameof(IGenericInterface<>.Method)

As it does not matter what is in the generic part when getting the name of something. It would also make this more consistent with typeof.

**Comment by svick** [comment] 2015-10-14 17:46
I believe this is a duplicate of #4827.

**Closed** 2015-10-14 18:17 UTC
Labels: Area-Language Design, Resolution-Duplicate
