### ISSUE TITLE
VB Tuples - need to handle generic methods in ValueTuple types

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#13298] opened 2016-08-22 20:20 UTC
We do not have generic methods in ValueTuple, but in a custom ValueTuple implementation, they may exist.

We need to handle that case.

**Comment by jaredpar** [comment] 2016-08-23 18:14
Is this specific to VB or is this a problem in C# as well?

**Comment by jcouv** [comment] 2017-03-23 23:18
Duplicate of https://github.com/dotnet/roslyn/issues/13053
This is specific to VB. If you implement your own ValueTuple type in C#, you can include generic methods in  it.

**Closed by jcouv** 2017-03-23 23:18 UTC
Labels: Area-Compilers, Bug, Language-VB, New Language Feature - Tuples
