### ISSUE TITLE
Reference failed on parameters in attribute marked on a parameter of primary constructors in records

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#54916] opened 2021-07-19 12:17 UTC
**Version Used**: 
VS 17.0 Preview 2

**Steps to Reproduce**:

![](https://user-images.githubusercontent.com/23616315/126158149-1657c1de-f02e-4bee-b4cc-8f868019dc36.png)

Here the property `Solution` has been declared into the current record type. When I mark the `MemberNotNullWhenAttribute` on a parameter to reference it, it reports "Not found", and we must change the code to be with the type name such as `nameof(AnalysisResult.Solution)` instead of `nameof(Solution)` here.

**Expected Behavior**:

No error.

**Actual Behavior**:

CS0103 raised.

**Comment by jaredpar** [comment] 2021-08-03 11:23
This should be a minimal repro of the behavior above:

```c#
record R(string s = nameof(Prop)) {
    public int Prop => 42;
}
```

Believe this is "By Design" though at the moment as the members of the record aren't in scope here. Will let @jcouv comment

**Comment by jcouv** [comment] 2021-08-03 16:32
Yes, that's by-design at the moment.

@SunnieShine I believe you can declare that property and put the attribute there. I would recommend that anyways, so that you can also include an assertion corresponding to the attribute in that property getter.

**Comment by jcouv** [comment] 2021-08-03 16:33
Note: I don't think this would be addressed by the work in https://github.com/dotnet/roslyn/issues/40524 (allowing `nameof(parameter)`) which we're now aiming for C# 11

**Closed by jcouv** 2021-08-03 16:32 UTC
Labels: Area-Compilers, Bug, New Language Feature - Records

**Comment by SunnieShine** [comment] 2021-08-03 18:38
@jcouv Thank you so much. :)
