### ISSUE TITLE
Visual Studio crashes when I type couple of cyrillic letters in cs file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45444] opened 2020-06-25 00:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1085582/visual-studio-crashes-when-i-type-couple-of-cyrill.html)._

---
[regression] [worked-in:16.5.4]
After upgrade to 16.6.2.
Visual Studio crashes, when I try to type cyrillic letters in *.cs file.
It is some codepage problem related to source files.

It happens in files with only english letters and only if the option is set:
Environment -> Documents -> Save documents as Unicode when data cannot be saved in codepage.

If it is not set, everythin is ok in all scenarios.

---
#### Visual Studio Feedback System on 6/19/2020, 07:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Rebecca Peng [MSFT] on 6/22/2020, 02:01 AM: 

<p>Hi customer,</p>
<p>Thanks for your feedback. In order for us to investigate this further, could you please provide following information:</p>
<ol>
<li>Did you meet this issue only once or always?</li>
<li>This issue only occurs on cs file or all type of files?</li>
</ol>
<p>We are looking forward to hearing from you soon.<br>
Thanks</p>

#### scazy on 6/22/2020, 04:30 AM: 

<p>1. It appears sometimes while a day.</p><p>2. Yes, just cs files. I can't reproduce it in other file types.</p>

#### Visual Studio Feedback System on 6/22/2020, 06:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-06-25 00:21
Stack trace:

```
Event Time (UTC): 2020-06-19 11:29:09 AM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.AggregateException: One or more errors occurred. ---> System.Text.EncoderFallbackException: Value does not fall within the expected range.

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallback.HandleFallbackOccurred(Object sender, EventArgs args)

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallbackBuffer.RaiseFallbackOccurred()

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallbackBuffer.Fallback(Char charUnknown, Int32 index)

   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)

   at System.Text.SBCSCodePageEncoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS encoder)

   at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)

   at System.Text.EncoderNLS.Convert(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)

   at Microsoft.CodeAnalysis.Text.SourceTextStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)

   at Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum(Stream stream, SourceHashAlgorithm algorithmId)

   at Microsoft.CodeAnalysis.Text.SourceText.GetChecksum()

   at Microsoft.CodeAnalysis.Serialization.SerializerService.CreateChecksum(Object value, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.TextDocumentState.<ComputeChecksumsAsync>d__48.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

   --- End of inner exception stack trace ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.SolutionChecksumUpdater.<>c__DisplayClass17_0.<<PushTextChanges>b__0>d.MoveNext()

---> (Inner Exception #0) System.Text.EncoderFallbackException: Value does not fall within the expected range.

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallback.HandleFallbackOccurred(Object sender, EventArgs args)

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallbackBuffer.RaiseFallbackOccurred()

   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.DocumentEncoderFallbackBuffer.Fallback(Char charUnknown, Int32 index)

   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)

   at System.Text.SBCSCodePageEncoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS encoder)

   at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)

   at System.Text.EncoderNLS.Convert(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)

   at Microsoft.CodeAnalysis.Text.SourceTextStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)

   at Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum(Stream stream, SourceHashAlgorithm algorithmId)

   at Microsoft.CodeAnalysis.Text.SourceText.GetChecksum()

   at Microsoft.CodeAnalysis.Serialization.SerializerService.CreateChecksum(Object value, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.TextDocumentState.<ComputeChecksumsAsync>d__48.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---


Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessInnerTask(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessCompletedOuterTask(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeCore(System.Threading.Tasks.Task)
   at System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by scazy-ekb** [comment] 2020-08-02 13:26
Update of the issue: same bag rises in *.js files too.

**Comment by dj312** [comment] 2020-08-02 13:43
No problème 

Envoyé de mon iPhone

**Comment by davidwengier** [comment] 2020-09-18 06:25
I can't reproduce this in the Visual Studio 16.8 Preview 3, even when pasting random Cyrillic characters into an XML comment per the repro steps on the issue.

@scazy-ekb are you able to reproduce this in the latest previews?

**Comment by scazy-ekb** [comment] 2020-09-18 06:51
It doesn't appear now in 16.7.3.

**Comment by davidwengier** [comment] 2020-09-18 08:47
Thank you for following up. I will close this out, please let us know if there are any new issues that crop up.

**Closed by davidwengier** 2020-09-18 08:47 UTC
Labels: Area-IDE, Bug, Developer Community, Tenet-Reliability
