### ISSUE TITLE
TestPreviewDiagnosticTaggerInPreviewPane is flakey

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14444] opened 2016-10-12 01:03 UTC
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/1039/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Preview/PreviewWorkspaceTests/TestPreviewDiagnosticTaggerInPreviewPane/

Stacktrace

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
+++++++++++++++++++
STACK TRACE:
 at Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests.<TestPreviewDiagnosticTaggerInPreviewPane>d__9.MoveNext() in q:\roslyn\src\EditorFeatures\Test\Preview\PreviewWorkspaceTests.cs:line 268
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Pilchie** [comment] 2016-10-17 18:01
Is the same root cause as https://github.com/dotnet/roslyn/issues/10916 (which I am woefully behind in investigating)?

**Comment by CyrusNajmabadi** [comment] 2017-05-24 19:57
Still flakey

**Comment by Pilchie** [comment] 2017-05-25 02:22
@CyrusNajmabadi could you link to the Jenkins job where this failed again, so that I can take a look and if the failure was the same?

**Comment by MattGertz** [comment] 2017-06-30 18:40
Mondo escrow triage:  test-only, moving this out (again) to get this off the radar, but we really need to figure this out.

**Closed** 2018-02-13 23:04 UTC
Labels: Area-IDE, Bug, Disabled Test, Flaky, Resolution-Fixed, Test
