### ISSUE TITLE
"Hide base name" code fix does the wrong thing for const fields

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#14455] opened 2016-10-12 18:59 UTC
_Ported from Visual Studio Feedback_

``` C#
class A { internal const int i = 0; }
class B : A { internal const int i = 1; }
```

Apply "Hide base name" from the light bulb.

![image](https://cloud.githubusercontent.com/assets/116161/19323713/f126c8fc-9072-11e6-97cb-bca47196e7ef.png)

Note that there are two problems. First, there's a formatting issue, and second, that's an illegal position for "new" to appear in the language.

**Comment by sharwell** [comment] 2017-04-03 19:27
Marking as a duplicate of #18391 (could have been the other way around, but the work was done on that issue)

**Closed by sharwell** 2017-04-03 19:27 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
