### ISSUE TITLE
ExtractMethod: unable to cast object of type to type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23382] opened 2017-11-27 02:01 UTC
While typing in C# code editor I got a header bar. I clicked &quot;Enable&quot; and it appears many times. Here is the stack trace:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ConstructorDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax'.
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.AddInvocationAtCallSiteAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.CreateStatementsOrInitializerToInsertAtCallSiteAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateBodyForCallSiteContainerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/148945/unable-to-cast-object-of-type-to-type.html
VSTS ticketId: 523810_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jnyrup** [comment] 2017-12-06 13:24
While I can't provide a fully reproducible case, here's my observations when I got the exception:

I had somewhat class similar to 
```csharp
abstract class Base
    {
        protected Base(int a) { }
    }

    abstract class Derived : Base
    {
        protected int m_field;

        protected Derived(int field)
            : base(0) => m_field = field;
    }
```

I had the cursor on `m_field` in  `protected int m_field`;
When pressing "ctrl + shift + down" to get to the assignment of `m_field` in the ctor, the exception was thrown.

**Comment by JasonBock** [comment] 2018-03-23 14:31
FWIW I just got that exception. Here's a screen shot of VS when I encountered the error:

![image](https://user-images.githubusercontent.com/904213/37834899-e3e9b966-2e7c-11e8-9aa2-00ff94b450da.png)

**Comment by jinujoseph** [comment] 2018-04-02 08:09
Also reported [here](https://developercommunity.visualstudio.com/content/problem/217491/extractmethodcoderefactoring-invalidcastexception.html)

**Comment by JVimes** [comment] 2018-04-11 15:39
This happens several times per hour, for me.

**Comment by CyrusNajmabadi** [comment] 2018-04-11 17:41
can you guys click on this button when this happens, and please provide the stack trace:

![image](https://user-images.githubusercontent.com/4564579/38633553-e41a39b8-3d74-11e8-9afa-a47e27841cab.png)


Thanks!

**Comment by CyrusNajmabadi** [comment] 2018-04-11 17:42
tagging @heejaechang Can you please advise on what is the right fix here?

**Comment by heejaechang** [comment] 2018-04-11 18:58
looks like extract method tree rewriter doesn't know how to handle constructor declaration syntax. we can make either rewriter how to handle such syntax type or make extract method to bail out if destination involves such node.

**Comment by heejaechang** [comment] 2018-04-11 19:02
tagging @jinujoseph

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:10
> or make extract method to bail out if destination involves such node.

Can you expand on that.  What would it mean to "bail out if destination involves such node"?  What impact does that have on the user?  Does that mean you cannot do extract-method in a constructor?

**Comment by heejaechang** [comment] 2018-04-11 19:14
basically when we got to the point where we are in rewriter, it should already know where it is inserting new node. so, we can bail out without trying to rewrite.
..
by the way, the screenshot doesn't have selection, so not sure what it is actually trying to extract out.

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:16
Sorry.  i still don't understand what impact that will have on the user.  How will this manifest to them.  What sort of extract-method scenarios will be blocked if we do this?

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:16
> by the way, the screenshot doesn't have selection, so not sure what it is actually trying to extract out.

I think the onus is on us to figure that out :)   User's are just running into this while editing.  So something about this code is making extract method unhappy.

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:18
Basically, it's really hard to tell if we should do "make either rewriter how to handle such syntax type or make extract method to bail out if destination", because it's unclear what hte impact of those choices are.  Can you flesh that out so that we can make a more informed choice?

**Comment by heejaechang** [comment] 2018-04-11 19:18
I don't know exactly what it is trying to do. so, not sure what the end impact will be at the end. but code  wise, if we bail out on the specific node, then rewriter won't rewrite any change that involves that node. 

anyway, can't say without knowing exact context.

**Comment by heejaechang** [comment] 2018-04-11 19:20
without debugging into, I don't know either. but on top of my head, simple 2 choice looks like we either support the new node type that got added (ConstructorDeclarationSyntax) to the rewriter, or detect such case and just not offer extract method at all.

**Comment by heejaechang** [comment] 2018-04-11 19:25
I meant. "=>" language feature added that changed shape of tree for constructor body.

**Comment by heejaechang** [comment] 2018-04-11 19:26
we can leave it to @jinujoseph to decide what to do. like I said, without debugging into I dont know why it is happening. and what we want to do.

**Comment by heejaechang** [comment] 2018-04-11 19:27
I didn't even know that IDE team has changed extract method refactor to run without user actually selecting anything. what does it even trying to extract out?

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:30
> we can leave it to @jinujoseph to decide what to do. 

How can a decision be made without understanding the consequences of the choices?  All i've asked is for those consequences to be better explained so that a real decision can be made.

> I didn't even know that IDE team has changed extract method refactor to run without user actually selecting anything. what does it even trying to extract out?

Where are you getting that impression from?  The code literally starts with:

```c#
            // Don't bother if there isn't a selection
            var textSpan = context.Span;
            if (textSpan.IsEmpty)
            {
                return;
            }
```

What we have from customers are reports that things are crashing, and they've provided hte general code they were editing when that happened to provide context.  No one said that this happened without a selection.

**Comment by heejaechang** [comment] 2018-04-11 19:34
when we actually triage it out, someone propbably dig into find out why it is happening, what option we have. without digging into, all I can say is the thing I already told you. and I am not going to digging into right now.

..

without selection, I don't know what result impact users will have. did user select whole file? did user select "=>" and this happening? I dont know.

**Comment by CyrusNajmabadi** [comment] 2018-04-11 19:38
> without selection, I don't know what result impact users will have. 

If we don't know the resulting impact on a user, then we probably shouldn't be asking for decisions to be made about which choices to take.  At the very least we should have some understanding of the impacts of those potential choices first.  Otherwise we'd just making off the cuff engineering decisions.

**Comment by heejaechang** [comment] 2018-04-11 19:46
I didn't say we need to make decisions now, or choice I gave is all choice we have. those are rough choice I can give without actually debugging into the issue. from the info I have, feels like the issue is happening because extract method re-writter doesn't know how to handle "=>" for constructor body. so simple choice for such case seems to be either make extract method to handle such case or bail out gracefully.

what's all I said. I dont know how hard/easy it will be. or exactly what user experience we should provide users if we decide to not support such one now.

or I dont know whether my gut feeling on why it is happening was right. all those I can only know if I actually spend time to debug into and know exactly what users was trying to do.,

**Comment by svick** [comment] 2018-05-06 17:34
In case it helps, I have two ways to reproduce this (in VS 15.7 Preview 6 and with the same stack trace as in the original post). One of them happens during normal editing and seems to require ReSharper enabled, the second one involves selecting text and explicitly invoking the refactoring menu (and does not require ReSharper).

In both cases, you start with this code:

```c#
using System.Collections.Generic;

class C
{
    List<object> list;

    C() => list = new List<object>();
}
```

The first repro:

0. Have ReSharper enabled.
1. In `new List<object>()`, select the `object` keyword by double clicking on it and change it to `string` by typing.
2. Undo (by pressing the toolbar button or <kbd>Ctrl</kbd>+<kbd>Z</kbd>).
3. This causes `object` to be highlighted and also throws the exception.

The second repro:

0. Have ReSharper enabled or disabled, doesn't matter.
1. Select `new List<object>()`.
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd> to show the refactoring menu.
3. This shows the refactoring menu and also throws the exception.

**Comment by nick-morhun** [comment] 2018-07-25 15:33
The issue seems to be in this [source line](https://github.com/dotnet/roslyn/blob/933f8864a9733a2cd87fbc5ce94094642e2ae050/src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs#L175). Obviously, when a ConstructorDeclarationSyntax object is returned, it is not of StatementSyntax type. However, [CSharpCodeGenerator](https://github.com/dotnet/roslyn/blob/933f8864a9733a2cd87fbc5ce94094642e2ae050/src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs) works only with StatementSyntax because it was this way before expression-bodied methods were added.

**Comment by heejaechang** [comment] 2018-10-02 23:09
@nnpcYvIVl can you share repro steps? that can make things more faster.

**Comment by nnpcYvIVl** [comment] 2018-10-03 02:41
@heejaechang 
```csharp
namespace Test
{
    public class Class
    {
        public Class(int i) => i = 0;
    }
}
```
Select i in the assignment and press <kbd>CTRL</kbd>+<kbd>.</kbd> to cause "ExtractMethodCodeRefactoringProvider encountered an error and has been disabled".

**Comment by nnpcYvIVl** [comment] 2019-03-18 22:00
@heejaechang Is there an ETA for a fix? I'm still getting this in VS 15.9.9 and VS 16 RC2.

**Comment by jinujoseph** [comment] 2019-03-21 06:35
also reported [here](https://developercommunity.visualstudio.com/content/problem/500065/systeminvalidcastexception-unable-to-cast-object-o.html)

**Comment by ryzngard** [comment] 2019-04-25 22:37
@nnpcYvIVl , @svick , @JVimes 

I've tried to reproduce this issue with 16.1 preview 2 with no success. I've used the following code, where `[|` and `|]` indicate my cursor selection, beginning to end respectively. 

```
    namespace Test
    {
        public class Class
        {
            public Class(int i) => [|i = 0|];
        }
    }
```

I also tried with the below

```
using System.Collections.Generic;

class C
{
    List<object> list;

    C() => list = [|new List<object>()|];
}
```

Can you verify this still reproducs in the latest preview? Or, if able, tell me the exact selection you have that reproduces using a screenshot or the same annotation above. 

Until then I'm marking as not reproducable, but once I have a repro I will investigate.

**Comment by nnpcYvIVl** [comment] 2019-04-26 13:39
@ryzngard To reproduce select just the i instead of i = 0.

I can reproduce it in 16.0.2 but don't have the preview version to test.

![Untitled](https://user-images.githubusercontent.com/8421414/56811598-b5be1c00-67fe-11e9-8ceb-377098206df7.png)

**Comment by ryzngard** [comment] 2019-04-26 18:59
@nnpcYvIVl  perfect, I have a repro now! Thanks for the quick follow up

**Comment by ryzngard** [comment] 2019-04-26 19:19
I've confirmed this repros in 16.0.2, but no longer repros in 16.1 preview 3. There's a number of bug fixes that went in for ExtractMethod, so it may have been fixed from one of those. 

Feel free to re-open or file a new bug if you're still seeing issues after updating to 16.1. Thanks again for providing feedback

**Closed by ryzngard** 2019-04-26 19:19 UTC
Labels: Area-IDE, Bug, Developer Community
