### ISSUE TITLE
Compiler doesn't tokenize surrogate pairs correctly

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#69041] opened 2023-07-14 20:51 UTC
The language spec allows Unicode character classes Lu, Ll, Lt, Lm, Lo, or Nl to be used in identifiers. 
`SyntaxFacts.IsIdentifierStartCharacter` (also used by the lexer) however only takes `char` as a parameter. That’s not sufficient for Unicode code points that are represented as a pair of UTF16 surrogates in `string`.

Simple test shows that there are 90 Unicode code points that are represented by UTF16 surrogates that should classify as identifier characters but are not. The test should succeed.

```C#
[Fact]
public void UnexpectedCharacter_Surrogate()
{
    var identifiers = new List<string>();
    for (var lo = '\ud800'; lo < '\udbff'; lo++)
    {
        for (var hi = '\udc00'; lo < '\udfff'; lo++)
        {
            string s = lo.ToString() + hi;

            switch (CharUnicodeInfo.GetUnicodeCategory(s, 0))
            {
                case UnicodeCategory.UppercaseLetter:
                case UnicodeCategory.LowercaseLetter:
                case UnicodeCategory.TitlecaseLetter:
                case UnicodeCategory.ModifierLetter:
                case UnicodeCategory.OtherLetter:
                case UnicodeCategory.LetterNumber:
                    identifiers.Add(s);
                    break;
            }
        }
    }

    var code = "class " + identifiers.First() + ";";

    ParserErrorMessageTests.ParseAndValidate(code);
}
```

There are probably other Unicode classes that have a similar issue.

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:21
My recollection on this was that this was considered and explicitly rejected as not being worthwhile.  This, in particular, was because our suggestion for users in this case is to actually not write with surrogage pairs, but just use the full `\U....` syntax.  

We also did a review of hte spec at that point and felt that it was simply 'ambiguous' here.  It mentions 'character' many times, but doesn't make it clear if it references a single uncombined char, or if it refers to the final unicode interpreted representation of multiple surrogates.  In all places where it talks about a *non*-escaped character, it's always within the range of \u0001-\uFFFF.  THe only time it recognizes things outside of that range are explicitly when provdied by the user with the `\U12345678` syntax.  

I recall this is also due to us basically not hearing about thsi being an issue (likely because these corners of unicode tend to be in comments/strings, but not actually in code).  Given the lack of any reports, the low need to actually support this for real code, and the spec's wishy-washyness here where it is unclear if this is even an issue in the first place, we just explicitly punted and said "this is how it works and we're ok with that" :)

@jaredpar if he recalls anything.  I remember discussing this at length with Neal the last time around, and i recall this being where we intentionally landed.

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:27
Note: the part of the spec that leans toward this being the intended behavior is where it says:

> A character literal represents a single character, and consists of a character in quotes, as in 'a'.

if 'a single character' could be *any* unicode character, then char literal would support effectively much more than the 16bit range that it supports today.  However, it has always only supported those 16 bits, indicating that we view 'a single character' as being a 16bit entity.  As such, for things like 'identifiers' when we specify that it's stating 'character' must be within certain classes, the implication here is that we are referring to the initial 16bit char of the identifier.

--

If we did want to support this, i think we'd want to take this through teh language first.  Define our philosophy (effectively, do we care about these 90 chars or not), and then be very clear in the spec about exactly what behavior is expected.  That would then help drive any changes in roslyn.

**Comment by tmat** [comment] 2023-07-14 21:30
Seems inconsistent:
![image](https://github.com/dotnet/roslyn/assets/41759/85c8f849-34f8-4987-8b08-18390b618670)

**Comment by tmat** [comment] 2023-07-14 21:33
> if 'a single character' could be any unicode character, then char literal would support effectively much more than the 16bit range that it supports today

This is specifically called out in the spec. The difference is that this deals with the definition of `char` type. The characters allowed in identifiers are entirely independent of the runtime. The fact that the compiler represents the source code in UTF16 string is leaking through the implementation. I don't think this is intended. The compiler could very well represent the source code in UTF8 and then it would just work.

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:33
can you supply the code for that?  (and ideally, the individual chars for the characters in the first line, versus the second).

--

Note: i'm not saying we shouldn't do this.  it's possible things have changed since our last assessment.  I'm just giving my recollection of the last assessment, and also saying that if we do this, we need to likely take it through as lang clarification in the spec.

**Comment by tmat** [comment] 2023-07-14 21:35
```
> ((int)"䌦"[0]).ToString("X")
"4326"
> (((int)"𧀀"[0]).ToString("X"), ((int)"𧀀"[1]).ToString("X"))
(D85C, DC00)
```

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:35
> This is specifically called out in the spec. The difference is that this deals with the definition of char type. 

Yes, i know :)   But my point is that it about the only place where it even states what a character (like 'a single character').  ANd yes, due to it having to be char, it is limited to that 16bit range.  As i was mentioning, our prior read on this was simply that the spec is either ambiguous or just vague/underspecified here.  In other words, you can do a reading of it that says the compiler is in the right, or a reading that says it is in the wrong.  The last time we evaluated we sort of went: "meh... it's ok what it does, and there's no need to change".  That could certainly be reevaluated if we think it's important.  But my preference, if we do, is simply to start with beefing of the spec *explicitly* so tehre is no uncertainty about what it views as a character and how this should work when in non-escaped form.  Directly calling out surrogate pairs *not* as escapes would be important.

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:40
```
> ((int)"䌦"[0]).ToString("X")
"4326"
> (((int)"𧀀"[0]).ToString("X"), ((int)"𧀀"[1]).ToString("X"))
(D85C, DC00)
```

RIght.  So that just seems to fit exactly into how it is expected to work based on last review.  Namely, in the firstcase it isn't a surrogate, so it's a legal char within the class expected, so it is an identifier character.   In the second case, it is a surrogate, and the spec doesn't clearly spell out that that *must* be treated as a single final unicode character (outside of the 16bit range) that we need to support.

--

In other words, i totally understand the case your'e making, and the example you're giving.  SO the question simply is:

1. has anything changed since last time?  The answer could totally be yes.  We may think that these cases are relevant enough to actually put the effort into.
2. How should we deal with this?  My preference is to treat the *spec* as the problem initially and force it to be updated to be absolutely clear on this point that it operates on unicode's full range of characters, and that it operates on a view that is *after* interpretation of any encoding (like utf16).   

--

That said, my personal view is: meh.  NBD.  Can live with this like we have up till now :)  I'll leave to @jaredpar for thoughts on pri and what path we'd take on this.

**Comment by tmat** [comment] 2023-07-14 21:41
> As i was mentioning, our prior read on this was simply that the spec is either ambiguous or just vague/underspecified here

Agreed, it could be clarified a bit more.

This is pretty clear to me though:

[> Conceptually speaking, a program is compiled using three steps:
Transformation, which converts a file from a particular character repertoire and encoding scheme into a sequence of Unicode characters.
- Lexical analysis, which translates a stream of Unicode input characters into a stream of tokens.
- Syntactic analysis, which translates the stream of tokens into executable code.
- Conforming implementations shall accept Unicode compilation units encoded with the UTF-8 encoding form (as defined by the Unicode standard), and transform them into a sequence of Unicode characters. Implementations can choose to accept and transform additional character encoding schemes (such as UTF-16, UTF-32, or non-Unicode character mappings).
](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/lexical-structure.md?plain=1#L7-L13)

"Unicode characters" means any Unicode code point, not just those that encode in [0..0xffff] in UTF16.

**Comment by CyrusNajmabadi** [comment] 2023-07-14 21:48
I'll leave it to compiler to see if we want to do anything here :)

**Comment by jaredpar** [comment] 2023-07-14 23:04
> My recollection on this was that this was considered and explicitly rejected as not being worthwhile. This, in particular, was because our suggestion for users in this case is to actually not write with surrogage pairs, but just use the full \U.... syntax.
> @jaredpar if he recalls anything. I remember discussing this at length with Neal the last time around, and i recall this being where we intentionally landed.

This is my memory as well. The compiler has "by design" deviations from the spec when it comes to unicode support and, I believe, this is one of them. There are a number of historical reasons for this (how native compiler was implemented for example). The decision was made to live with the gap between spec and impl. 

@333fred in case he remembers more.

**Comment by 333fred** [comment] 2023-07-15 00:03
I'm pretty certain this was before I started on the team.

**Comment by tannergooding** [comment] 2023-07-15 06:13
There’s various historical context and other dupes of the issue available from https://github.com/dotnet/roslyn/issues/9731

**Comment by jaredpar** [comment] 2023-07-18 05:45
Duping to #9731

**Closed by jaredpar** 2023-07-18 05:45 UTC
Labels: Area-Compilers, untriaged
