### ISSUE TITLE
VS crashes when pressing "Ctrl + t" and inputing content 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#18943] opened 2017-04-24 09:18 UTC
_From @MiaomiaoHuangfu on April 24, 2017 8:44_

- Open the .sln file under \\mlangfs1\public\jomorris\ConnectProductivityDemoOn.NETCore have Trainer.cs opened;
- Press "Ctrl + t" ;
- try to search "workout" and VS crashes.
  ![vscrashesafterctrt](https://cloud.githubusercontent.com/assets/22901391/25328598/069e613c-290b-11e7-91a6-4167006b335f.PNG)
Expected result: Go to feature run smoothly and can quickly navigate to any file/type/member/symbol via "Ctrl + t".

Test on d15prerel.26421.06
OS: Windows 10 X64

_Copied from original issue: dotnet/project-system#2060_

**Comment by sharwell** [comment] 2017-04-24 12:16
Depending on which commit was being tested at the time, it's possible #18887 fixed this late last night.

**Comment by Pilchie** [comment] 2017-05-22 21:15
@MiaomiaoHuangfu do you have a dump?  Do you know what build you had?

**Comment by MiaomiaoHuangfu** [comment] 2017-05-23 01:32
The issue is not repro on the latest build d15prerel.26521.01.
I will close the bug. 
It will be reactive or reopen if the issue is repro again.

**Comment by MiaomiaoHuangfu** [comment] 2017-05-23 01:40
The issue is not repro on the latest builds d15prerel.26521.01 and d15prerel.26517.00.
I think we could close this bug. 
we can reactive or reopen the bug if it is repro again.

**Closed** 2017-05-23 18:41 UTC
Labels: Area-IDE, Bug, Resolution-Not Reproducible, Tenet-Reliability
