### ISSUE TITLE
Test_ConflictingParameterNames1 failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9408] opened 2016-03-02 17:28 UTC
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4670/

```
Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.ImplementInterface.ImplementInterfaceCrossLanguageTests.Test_ConflictingParameterNames1
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        src\EditorFeatures\Test2\Diagnostics\AbstractCrossLanguageUserDiagnosticTest.vb(42,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_4_TestAsync.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        src\EditorFeatures\Test2\Diagnostics\ImplementInterface\ImplementInterfaceCrossLanguageTests.vb(265,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.ImplementInterface.ImplementInterfaceCrossLanguageTests.VB$StateMachine_7_Test_ConflictingParameterNames1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by DustinCampbell** [comment] 2016-03-03 17:05
@jasonmalinowski is this a dupe of the other cross language test failures that you're looking at?

**Comment by jasonmalinowski** [comment] 2016-03-06 05:11
Yep, it should be a dupe of #9308.

**Closed by jasonmalinowski** 2016-03-06 05:11 UTC
Labels: Area-IDE, Flaky, Test
