### ISSUE TITLE
"csc.exe" exited with code -1066598274

### ISSUE THREAD

**Issue by 649727360** [dotnet/roslyn#59799] opened 2022-02-27 02:42 UTC
**Version Used**: 
Visual Studio 2019 (Enterprise)

**Steps to Reproduce**:
The program suddenly reported an error and just recompiled it.

..\packages\Microsoft.Net.Compilers.1.3.2\tools\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code -1066598274。

**Expected Behavior**:
Successful build

**Actual Behavior**:
Compiler error

Can someone help me on this issue? Thank you.

**Comment by jcouv** [comment] 2022-02-28 05:57
Two things:
1. This is an old version of Microsoft.Net.Compilers (1.3.2 dates from 2016) so even if we can confirm the issue you'd have to update to a newer reference to get the fix. I suggest you start by trying that. That may resolves the issue (many issues have been fixed during that time).
2. Could you clarify what you mean by "suddenly"? Did this crash not happen before? Maybe your recent change to the code  could give us an idea what's the root cause. Trying to narrow down the problem to some specific problematic code and a small self-contained repro would be ideal so that we can help you effectively.

**Comment by jcouv** [comment] 2022-03-01 20:49
I'll go ahead and close this issue. Please re-open if the problem occurs with a recent version of Roslyn (such as 4.2). Thanks

**Closed by jcouv** 2022-03-01 20:49 UTC
Labels: Area-Compilers, Resolution-Not Reproducible, Need More Info, untriaged
