### ISSUE TITLE
VS 15.8 Format Document introduces compile error due to IDE0009

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#28654] opened 2018-07-18 19:45 UTC
**Version Used**: 15.8 Preview 5 27917.1.d15.8

**Steps to Reproduce**:

1. Have a class like this:
```cs
[DebuggerDisplay("{" + nameof(DebuggerDisplay) + "}")]
class Channel {
    string DebuggerDisplay => "Some string";
}
```
1. Like `this.`: 
![image](https://user-images.githubusercontent.com/3548/42904013-731eaa9e-8a88-11e8-976f-02884d1b266f.png)

1. Configure Format Document to "Apply 'this.' qualification preferences"
![image](https://user-images.githubusercontent.com/3548/42903946-35a643ca-8a88-11e8-8b86-8bd01085f4d4.png)

1. Execute Format Document.

**Expected Behavior**:

No compile errors.

**Actual Behavior**:

A compile error is created when `this.` is prefixed to my `DebuggerDisplay` reference:

```cs
[DebuggerDisplay("{" + nameof(this.DebuggerDisplay) + "}")]
class Channel {
    string DebuggerDisplay => "Some string";
}
```

The compiler does not allow `this.` to be used on a class attribute.

**Comment by sharwell** [comment] 2018-07-18 20:32
Duplicate of #26893

**Closed by sharwell** 2018-07-18 20:32 UTC
