### ISSUE TITLE
Upgrade VS, now every time i want to go to Metadata-as-source i get prompted if i want to decompile

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42613] opened 2020-03-20 04:58 UTC
Upgraded to 16.6p1 
![image](https://user-images.githubusercontent.com/4564579/77137801-a8b8a580-6a2c-11ea-9561-314e4b6abac0.png)

Now, every time i say "goto def" i get prompted if i want to decompile. I say "no", and it takes me to metadata.  But this preference doesn't stick, and i have to repeat this over and over again.

**Comment by CyrusNajmabadi** [comment] 2020-03-20 04:59
Tagging @sharwell @jinujoseph this behavior is really poor.  It's the #1 top reason i regret upgrading to 16.6 so far :)

**Comment by sharwell** [comment] 2020-03-20 05:14
Duplicate of #25299

**Comment by CyrusNajmabadi** [comment] 2020-03-20 07:19
This is not a duplicate of that issue.  That issue was reported *2* years ago.  This just started happening now to me after upgrading to 16.6p1 (presumably i was on on one of the 16.5 builds).  Something broke here that i think we should look into.

**Comment by sharwell** [comment] 2020-03-20 20:53
This turned out to be a duplicate. The **Navigate to Decompiled Sources (experimental)** feature was turned on.

**Closed by sharwell** 2020-03-20 20:53 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate

**Comment by CyrusNajmabadi** [comment] 2020-03-20 21:14
@kendrahavens @mikadumont for visbility.  I got flighted into this experiment and it's awful.  It does nothign but break the goto-def experience for the user on *every* invocation.  

People need to not be flighted into this.  Or, if we're going to do this, we need to make it so that there's a simple way with the dialog that pops up to day "remember this and stop asking me every single damn time" :)

Tagging @davkean as i think this happened to him as well.
