### ISSUE TITLE
Suppress ReplaceMethodWithProperty for overriden method declared outside solution

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#15165] opened 2016-11-11 11:17 UTC
I would propose to suppress ReplaceMethodWithProperty refactoring for overriden method that are declared outside solution.

An attempt to replace that kind of method with property will always produce invalid code.

#### Code Sample:

```csharp
public class Foo
{
    public override string ToString() // Replace 'ToString' with property
    {
        return base.ToString();
    }
}
```

**Comment by svick** [comment] 2016-11-11 15:13
Is this a duplicate of https://github.com/dotnet/roslyn/issues/14991?

**Closed** 2016-11-14 23:52 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
