### ISSUE TITLE
Need a proper representation for __arglist argument for IOperation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#19673] opened 2017-05-20 00:08 UTC
Take the following example,
```cs
        Console.Write("{0} {1} {2} {3} {4}", 1, 2, 3, 4, __arglist(5));
```
The __arglist is currently returned as:
```
    IArgument (ArgumentKind.Explicit, Matching Parameter: null) (OperationKind.Argument, IsInvalid) (Syntax: '__arglist(5)')
      IOperation:  (OperationKind.None) (Syntax: '__arglist(5)')
        Children(1): ILiteralExpression (Text: 5) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 5) (Syntax: '5')
```

I believe this can be solved by simply adding `ArgumentKind.ArgList`, and create such an `IArgument` based on underlying `BoundArgListOperator`.

**Comment by genlu** [comment] 2017-05-20 00:21
FYI @heejaechang @jinujoseph

**Comment by nguerrera** [comment] 2017-05-20 00:39
#8394

**Comment by genlu** [comment] 2017-05-31 17:46
Do we want to discuss this today? @jinujoseph

**Comment by jinujoseph** [comment] 2017-05-31 17:48
sure , we should actually discuss #8394 in general

**Comment by CyrusNajmabadi** [comment] 2017-06-01 22:25
We tink we should have:

```c#
    public interface IArgList : IOperation
    {
        List<IOperation> Values;
    }
```

If user uses __arglist(1, 2, 3), then they will have an IArgument with a VAlue that is this IArgList.  The IArgList will point at 1, 2, 3.  The Kind of the ArgumentKind of the IArgument will be a new value called ... ArgList

**Comment by mavasani** [comment] 2018-06-26 15:03
Dupe of https://github.com/dotnet/roslyn/issues/8394

**Closed by mavasani** 2018-06-26 15:03 UTC
Labels: Area-Analyzers, New Feature - IOperation, _Product-level triaged
