### ISSUE TITLE
Call for cooperation between VS C# components

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47036] opened 2020-08-21 16:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1150623/call-for-cooperation-between-vs-c-components.html)._

---
While the famous straw (that broke the camel's back) was during editing an SDK-style C# project, I'm fairly confident this applies to all kinds of project types.

In VS there are a multitude of parsers, all competing for resources, and all doing things slightly_ different. Two of them are CodeLens and Roslyn.

CodeLens is generally much faster than Roslyn in identifying references to identifiers, such as method names. This has the unfortunate effect that if you try to use rename refactoring on such a method, while CodeLens could display "0 references", Roslyn can go on a multi-minute killing spree trying to find all references to it that it can.

This obviously frustrates users of the software, when they for the hundredth of thousandth time see "It's all bloody there, in gray on white -- zero!", yet have to wait for minutes for Roslyn to waste resources (which in the end boils down to a LOT of money, globally) trying to find out what is already known!

Once upon a time I can understand if Microsoft was reluctant to (OK, likely directly opposing, to be more precise) using CodeLens's features in Roslyn, since CodeLens was an "Enterprise SKU only" feature, but it's quite long since it became part of the core (read: all SKU's). Roslyn could be sped up **several orders of magntude** for operations requiring information about:
- Is this identifier used _anywhere_ else in the project or solution?
- Where are the references to this identifier?

Yes, it would require exposing a _small_ interface from VS (for the component implemeting CodeLens), that also other editors/IDE's could expose to Roslyn, but that tiny interface addition is a drop in the ocean compared to the saved millions upon millions of man-hours (globally) currently spent wasted in waiting for Roslyn to catch up to what the IDE already knows.

Please, _please_, consider implementing this functionality.

---
#### Feedback Bot on 8/17/2020, 00:54 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by RikkiGibson** [comment] 2020-08-24 18:14
The problem described seems to be that sometimes CodeLens appears to be done on a symbol while FAR is still searching for references to the same symbol.

If I had to guess I would say that CodeLens is either showing a stale result that still happens to be correct, or is successfully loading the result from a cache, while FAR for some reason is not using that cache.

**Comment by CyrusNajmabadi** [comment] 2020-08-24 18:38
If that's the case, taht sounds like an appropriate compromise for the goals of these features.  FAR wants to be accurate.  So when you perform it, it's going to get you the real full set of items, and it's going to compute it righ there.  CodeLens, on the other hand, wants to be useful, but not overly impactful on the experience.  Finding refernces is expensive.  So it's likely that CodeLens aggressively throttles and lazily brings itself up to date when it can, showing the best information it has at the time until that point.

If FAR uses codelens' cached information, it would likely miss items.  If CodeLens aggressively computed full data, it would likely completely bog down the system.  So teh different behaviors try to balance things out.

**Comment by svick** [comment] 2020-08-24 19:18
@CyrusNajmabadi Would it be possible if FAR immediately showed the cached information, while at the same time recomputing the data (and clearly visually indicating that it does so) and when it's done, showing the up-to-date information?

**Comment by CyrusNajmabadi** [comment] 2020-08-24 20:25
@svick We are effectively doing that through the 'rich navigation' efforts.  Hopefully shipping soon.

**Comment by sharwell** [comment] 2020-08-25 22:05
Yep, this is a duplicate of RichNav feature coming from the platform.

**Comment by CyrusNajmabadi** [comment] 2022-11-01 22:16
Closing out as a dupe of another effort.

**Closed by CyrusNajmabadi** 2022-11-01 22:16 UTC
Labels: Area-IDE, Feature Request, LSP
