### ISSUE TITLE
Incorrect quick fix suggestion with default parameters

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#33390] opened 2019-02-14 19:56 UTC
**Version Used**: 
.NET Core 3 Preview 2 / VS 2019 Preview 3

When an optional parameter is combined with compound assignment, the analyzers show an incorrect suggestion to remove a redundant parameter:

![image](https://user-images.githubusercontent.com/1427284/52813682-4ee6ee80-3068-11e9-8cd2-54363df7071b.png)

Same code before changing to the compound assignment does not show any suggestions on the parameters:

![image](https://user-images.githubusercontent.com/1427284/52813831-a84f1d80-3068-11e9-860c-135e93aa7168.png)

**Comment by mavasani** [comment] 2019-02-19 19:10
Duplicate of https://github.com/dotnet/roslyn/issues/33299

**Closed by mavasani** 2019-02-19 19:10 UTC
Labels: Area-IDE, Bug
