### ISSUE TITLE
cshtml sometimes passes in position that is out of bounds

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9325] opened 2016-03-01 00:50 UTC
PR https://github.com/dotnet/roslyn/pull/9279 was added to get more telemetry on this scenario

example stack:

```
0:067> !pe 8c3aaaa0
Exception object: 8c3aaaa0
Exception type:   System.ArgumentOutOfRangeException
Message:          Specified argument was out of the range of valid values.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    3B2EE694 1EEB4087 Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindToken(Int32, Boolean)+0x5fe0b7
    3B2EE6C8 1E9913C8 Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindToken(Int32, System.Func`2<Microsoft.CodeAnalysis.SyntaxTrivia,Boolean>)+0x28
    3B2EE70C 1E8B6055 Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindToken(Int32, Boolean)+0x85
    3B2EE740 1E991394 Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindTokenCore(Int32, Boolean)+0x14
    3B2EE74C 1F30AB92 Microsoft_CodeAnalysis_CSharp_Workspaces_ni!Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(Microsoft.CodeAnalysis.SyntaxTree, Int32, System.Threading.CancellationToken)+0x42
    3B2EE804 1F308FE9 Microsoft_CodeAnalysis_CSharp_Workspaces_ni!Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsInNonUserCode(Microsoft.CodeAnalysis.SyntaxTree, Int32, System.Threading.CancellationToken)+0x29
    3B2EE81C 3FCAEBB1 Microsoft_CodeAnalysis_CSharp_Features_ni!Microsoft.CodeAnalysis.CSharp.Completion.Providers.SpeculativeTCompletionProvider+<GetSpeculativeTCompletions>d__5.MoveNext()+0x101
    3B2EE9F4 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EEA04 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EEA10 3FCAE90C Microsoft_CodeAnalysis_CSharp_Features_ni!Microsoft.CodeAnalysis.CSharp.Completion.Providers.SpeculativeTCompletionProvider+<>c__DisplayClass4_0+<<GetItemsWorkerAsync>b__0>d.MoveNext()+0x9c
    3B2EEAE8 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EEAF8 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EEB04 1E30A57D Microsoft_CodeAnalysis_Features_ni!Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions+<GetUnionResultsFromDocumentAndLinks>d__3`1[[System.__Canon, mscorlib]].MoveNext()+0x26d
    3B2EEBFC 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EEC0C 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EEC18 3FCAE6D4 Microsoft_CodeAnalysis_CSharp_Features_ni!Microsoft.CodeAnalysis.CSharp.Completion.Providers.SpeculativeTCompletionProvider+<GetItemsWorkerAsync>d__4.MoveNext()+0xf4
    3B2EED0C 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EED1C 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EED28 1E30A075 Microsoft_CodeAnalysis_Features_ni!Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider+<GetItemsAsync>d__7.MoveNext()+0x155
    3B2EEE48 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EEE58 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EEE64 1E309B52 Microsoft_CodeAnalysis_Features_ni!Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider+<GetGroupAsync>d__4.MoveNext()+0xb2
    3B2EEFDC 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EEFEC 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EEFF8 72314CCA mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)+0x1a
    3B2EEFFC 1E3090B4 Microsoft_CodeAnalysis_Features_ni!Microsoft.CodeAnalysis.Completion.AbstractCompletionService+<GetGroupsAsync>d__13.MoveNext()+0x254
    3B2EF190 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EF1A0 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EF1AC 1E308D0D Microsoft_CodeAnalysis_Features_ni!Microsoft.CodeAnalysis.Completion.AbstractCompletionService+<GetGroupsAsync>d__10.MoveNext()+0x16d
    3B2EF2F0 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EF300 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EF30C 1B8CD04F Microsoft_CodeAnalysis_EditorFeatures_ni!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer+<GetGroupsAsync>d__16.MoveNext()+0xcf
    3B2EF408 72314D70 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    3B2EF418 72314D07 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    3B2EF424 72314CCA mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)+0x1a
    3B2EF428 1B8CC79D Microsoft_CodeAnalysis_EditorFeatures_ni!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer+<DoInBackgroundAsync>d__15.MoveNext()+0x2bd
```

**Comment by Pilchie** [comment] 2016-04-13 20:22
@brettfo Is this the same thing that is happening in QuickInfo in the bug you have?

**Comment by brettfo** [comment] 2016-04-13 21:01
Yes, same problem and possibly related to @dpoeschl's theory about a text buffer's version and reiterated version getting out of sync.

**Comment by Pilchie** [comment] 2016-04-13 21:07
Given all of these bugs seem to involve razor, are we sure the problem isn't passing a position/span from the wrong buffer in a projection buffer?

**Comment by dpoeschl** [comment] 2016-04-14 22:43
@brettfo This doesn't look like the same failure as the [suspected reiterated version thing](https://github.com/dotnet/roslyn/issues/7660)...

**Comment by rchande** [comment] 2016-09-19 19:34
@mavasani Do we have any Watsons for this?

**Comment by mavasani** [comment] 2016-09-19 19:40
VSO [209299](https://devdiv.visualstudio.com/DevDiv/_workitems?id=209299&_a=edit)?

**Comment by rchande** [comment] 2016-11-08 22:04
@tmeschter Looks like the watson @mavasani found hasn't gotten any hits since Preview 3. I think we should close this bug and 209299 if you're not tracking anything else like this.

**Comment by rchande** [comment] 2016-11-15 20:31
Haven't seen any more hits, closing.

**Closed by rchande** 2016-11-15 20:31 UTC
Labels: Area-IDE, Bug
