### ISSUE TITLE
Suppressing StyleCop Rule with QuickAction changed indentation of summary

### ISSUE THREAD

**Issue by KlemensE** [dotnet/roslyn#16358] opened 2017-01-09 22:06 UTC
**Version Used**: 1.3.1.60621

**Steps to Reproduce**:

1. Using following code:
```
        /// <summary>
        /// Intercepts route not found error in order to show it as friendly message on the screen.
        /// </summary>
        /// <param name="path">Path.</param>
        /// <returns>404 with <see cref="ErrorInfoModel"/> object as content.</returns>
        [HttpGet, HttpPost, HttpPut, HttpPatch, HttpDelete, HttpHead, HttpOptions]
        public HttpResponseMessage NotFound(string path)
        {
        }
```
2. Using [StyleCop](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) with active Rule [SA1133](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1133.md)
3. The attribute HttpPost will be reported as violating.
4. Suppressing the Rule

**Expected Behavior**: The code should look like this:

```
#pragma warning disable SA1133 // Do not combine attributes
        /// <summary>
        /// Intercepts route not found error in order to show it as friendly message on the screen.
        /// </summary>
        /// <param name="path">Path.</param>
        /// <returns>404 with <see cref="ErrorInfoModel"/> object as content.</returns>
        [HttpGet, HttpPost, HttpPut, HttpPatch, HttpDelete, HttpHead, HttpOptions]
#pragma warning restore SA1133 // Do not combine attributes
        public HttpResponseMessage NotFound(string path)
        {
        }
```

**Actual Behavior**: The summary will be indented to far:

```
#pragma warning disable SA1133 // Do not combine attributes
                              /// <summary>
                              /// Intercepts route not found error in order to show it as friendly message on the screen.
                              /// </summary>
                              /// <param name="path">Path.</param>
                              /// <returns>404 with <see cref="ErrorInfoModel"/> object as content.</returns>
        [HttpGet, HttpPost, HttpPut, HttpPatch, HttpDelete, HttpHead, HttpOptions]
#pragma warning restore SA1133 // Do not combine attributes
        public HttpResponseMessage NotFound(string path)
        {
        }
```

Originally filed as [DotNetAnalyzers/StyleCopAnalyzers#2273](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2273), but they referred me here since the code fix that caused a problem is provided by Roslyn.

**Comment by Pilchie** [comment] 2017-01-20 17:58
Similar to https://github.com/dotnet/roslyn/issues/228.

**Comment by sharwell** [comment] 2019-09-27 02:01
Duplicate of #16681

**Closed by sharwell** 2019-09-27 02:01 UTC
Labels: Area-IDE, Bug
