### ISSUE TITLE
UI - Override auto-complete throws error with generic class when also a static class of same name

### ISSUE THREAD

**Issue by ahowroyd** [dotnet/roslyn#15313] opened 2016-11-17 02:50 UTC
**Version Used**: 
Visual studio Version 14.0.25431.01 Update 3
Not tested on latest Roslyn, so could be fixed. (but easy to test)

**Steps to Reproduce**:

1. Enter the following code 

```c#
    public static class BaseClass
    {
    }
    public abstract class BaseClass<T>
    {
          public abstract bool Method();
    }
    public sealed class SubClass<T> : BaseClass<T>
    {
    }
```

2. In ```SubClass<T>```
      start typing 'override' inside the { }
      when intellisense pick list appears select 'Method' and hit enter to get auto-complete.
     (note that suggestion box on class to implement interface works without error)

**Expected Behavior**:
    The method should be created.

**Actual Behavior**:
  Visual studio displays message box with: "one or more errors occurred".

**Comment by ahowroyd** [comment] 2016-11-17 02:52
Sorry - the input thing has nuke the angle brackets in my example. Second BaseClass and SubClass should have a generic parameter.

**Comment by ahowroyd** [comment] 2016-11-17 02:55
This might work    
   public static class BaseClass
    {
    }
    public abstract class BaseClass< T >
    {
        public abstract bool Method();
    }
    public sealed class SubClass< T > : BaseClass< T >
    {
    }

**Comment by CyrusNajmabadi** [comment] 2016-11-17 02:56
I've edited your first post to properly format the code :)

**Comment by rchande** [comment] 2016-11-21 18:31
Hey @ahowroyd--I'm unable to reproduce this on VS 15 RC. Closing this but feel free to reactivate if you see it again.

**Closed by rchande** 2016-11-21 18:31 UTC
Labels: Area-IDE, Bug
