### ISSUE TITLE
VB compiler reports an error if CompilerGeneratedAttribute or DebuggerHiddenAttribute are not present

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9167] opened 2016-02-25 03:27 UTC
When compiling async method. C# ignores these if not present.

See test ```EditAndContinueStateMachineTests.MissingAsyncStateMachineAttribute```.

**Comment by jcouv** [comment] 2016-03-03 21:00
Both of those types (`CompilerGeneratedAttribute` and `DebuggerHiddenAttribute`) are [explicitly required](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Lowering/AsyncRewriter/AsyncRewriter.vb,298) in the VB compiler. 
I will check the behavior of native VB compiler to confirm this is by design.

**Comment by tmat** [comment] 2016-03-03 21:13
I don't see reason why they should be required. I also see a comment where you pointed at
```
' TODO: change to "don't use if not found"
```

**Comment by jcouv** [comment] 2016-03-03 22:12
@tmat Makes sense.

I noticed another situation similar to the one your test encounters with AsyncRewriter. That other one is in [IteratorRewriter.vb](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Lowering/IteratorRewriter/IteratorRewriter.vb,88).  
I'll try to find a unittest that hits IteratorRewriter and fix it together.

**Comment by jcouv** [comment] 2016-03-05 05:21
The async and iterator rewriters in VB have been relaxed not to mandate the existence of those optional attributes. 
The C# compiler didn't need any change.
Merged PR #9476.

**Closed by jcouv** 2016-03-05 05:21 UTC
Labels: Area-Compilers, Bug, Resolution-Fixed
