### ISSUE TITLE
Error CS0570 while debugging a default interface generator method of a variant interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43262] opened 2020-04-10 17:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/983400/error-cs0570-while-debugging-a-default-interface-g.html)._

---
Consider the following interface and a dummy class that implements it.
```cs
interface I<out T>
{
    System.Collections.Generic.IEnumerable<T> M()
    {
        var x = default(T);
        yield return x;
    }
}

public class C : I<C>
{
    public static void Main() => System.Linq.Enumerable.Any(((I<C>)new C()). M());
}
```
now put a breakpoint on line 6 (`yield return x;`).
Execute the program and you'll notice something odd if you try to watch `x`, It tells you the following::

> error CS0570: '<>x<T>.<>m0(I<T>.<M> d__0)' is not supported by the language

Obviously, the program works so it is supported by the language, but the debugger has no idea what to do with it. 
This also happens for `async` (`ValueTask`,`Task`,`Task<T>`,`ValueTask<T>`, or `IAsyncEnumerable<T>`) returning methods

---
#### Visual Studio Feedback System on 4/8/2020, 06:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2020-04-14 19:48
Duplicate of #43282

**Closed by sharwell** 2020-04-14 19:48 UTC
Labels: Area-Interactive, Bug, Developer Community, Interactive-Debugging
