### ISSUE TITLE
Cannot open solution.

### ISSUE THREAD

**Issue by jchannon** [dotnet/roslyn#3877] opened 2015-07-09 09:20 UTC
I've being trying to port Nancy to dnx and VS will no longer open and jusr crashes.

Here's some crash dumps - https://gist.github.com/jchannon/c69d10f58e59bc832d25

**Comment by KirillOsenkov** [comment] 2015-07-09 18:39
The callstack you provide shows that the nullref happens when the Highlight References feature is running (when you place caret on an identifier it highlights references to the same symbol in the current file using gray tags). For this feature to even run, a solution must be open with projects and an open editor window.

What are the steps you're taking from the moment VS starts to the moment it disappears? Do you just open a solution? Which one? What exact VS version is this? Did you try cleaning your repo? (e.g. git clean -xdf to delete files like .suo etc.)

**Comment by jchannon** [comment] 2015-07-09 19:18
I open the solution in the DNX branch of Nancy. A file is already open. It
loads the projects then just crashes with the modal dialog asking if I
wanted to close or debug the all

Doing a git clean seemed to work but then I get DNX errors

**Comment by KirillOsenkov** [comment] 2015-07-11 00:47
This explains the part why git clean is temporarily solving the Roslyn problem. VS stores the list of last opened files in the solutionname.suo file. If you delete the file (via git clean) it doesn't reopen the editor and so the Highlight References feature doesn't get a chance to run. However the bug is likely still there if you re-open the file manually.

There's likely two bugs - the root cause bug and the bug in Roslyn unable to deal with the situation (causing the NullRef in FAR).

@rchande @dpoeschl

**Comment by balajikris** [comment] 2015-09-28 20:10
@jchannon could you please point me to the repo and/or share a series of steps I need to do (what file was it and what identifier was your caret on, if you know etc.) to get to the crash? In case you had saved a dump with heap, I could work with that too.

**Comment by balajikris** [comment] 2015-09-29 04:24
From the gist provided, VS version is 14.0.22823.1, which is RC. The crash has been fixed in RTM by PR https://github.com/dotnet/roslyn/pull/2977.

For internal reference, see bugs : 136580, 107096 or search by call stack: "Microsoft.CodeAnalysis.FindSymbols.DependentProjectsFinder"

**Comment by balajikris** [comment] 2015-09-29 04:30
clearing milestone and assignment to let triage take a look at this. @Pilchie, the crash has been fixed in RTM. What else should we address here?

**Comment by Pilchie** [comment] 2015-09-29 16:34
I only see one issue here - a crash in highlight references.  @jchannon Do you think there is anything more to do here?

**Closed by Pilchie** 2015-09-29 16:34 UTC
Labels: Area-IDE, Bug

**Comment by jchannon** [comment] 2015-09-29 16:35
Nope
