### ISSUE TITLE
[Test Failure] MSBuild Error in prtest/win/dbg/unit32 on PR #10106

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#10115] opened 2016-03-25 21:17 UTC
PR: [#10106](https://github.com/dotnet/roslyn/pull/10106) *Prepare cibuild.cmd (hotfixes branch) to receive /buildTimeLimit* by @lgolding
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5613/

**Issue 1: MSBuild Error**
error MSB3491:  Could not write lines to file "D:\j\workspace\roslyn_prtest---345e02d2\Binaries\Temp\.NETPortable,Version=v5.0.AssemblyAttributes.cs". The process cannot access the file 'D:\j\workspace\roslyn_prtest---345e02d2\Binaries\Temp\.NETPortable,Version=v5.0.AssemblyAttributes.cs' because it is being used by another process. [D:\j\workspace\roslyn_prtest---345e02d2\src\Tools\Source\CompilerGeneratorTools\Source\BoundTreeGenerator\CompilersBoundTreeGenerator.csproj] -&gt;      5&gt;C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2992,5):

**Comment by davkean** [comment] 2016-03-26 17:47
Dupe of https://github.com/dotnet/roslyn/issues/10116

**Closed by davkean** 2016-03-26 17:47 UTC
Labels: Bug
