### ISSUE TITLE
No way to "View Code" of an .editorconfig after the designer was added

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#54537] opened 2021-07-01 18:35 UTC
Typically, files with designers give these options in the context menu in Solution Explorer:

![image](https://user-images.githubusercontent.com/9797472/124173776-5bfdb000-da60-11eb-81b0-2fe6b4ec7cc3.png)

**Comment by Youssef1313** [comment] 2021-07-01 19:42
The shortcut works, but loses syntax highlighting for some weird reason. This is also a duplicate of https://github.com/dotnet/roslyn/issues/53120.

**Comment by sharwell** [comment] 2021-07-02 23:29
Duplicate of #53120

**Closed by sharwell** 2021-07-02 23:29 UTC
Labels: Area-IDE, untriaged
