### ISSUE TITLE
Hard to see cursor when using in-place rename refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24032] opened 2018-01-04 02:06 UTC
I use dark VS theme (don't know if its relevant)
I press Ctrl+R, Ctrl+R on identifier to start Rename refactoring.
Text cursor vanishes.
It is super annoying because I don't understand what will happen when I press something. It returns after finishing Rename

![image](https://user-images.githubusercontent.com/1408396/34547571-b1fbd888-f0c1-11e7-91b7-4556355fdc43.png)

Can you do something about it? It should be easy fix (I hope) and it will dramatically improve my daily usage of VS

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/153970/hard-to-see-cursor-when-using-in-place-rename-refa.html
VSTS ticketId: 527771_
_These are the original issue comments:_

Jinu Joseph [MSFT] on ‎12‎/‎3‎/‎2017, 04:27 AM (31 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2018-01-04 02:08
I've hit this a bunch of times, but didn't get around to filing a bug for it. Now someone else has 😄

**Comment by AbhitejJohn** [comment] 2020-06-08 23:10
Looks like a dupe of #8136

**Comment by AbhitejJohn** [comment] 2020-06-11 02:09
JFYI, that there's an internal bug tracking this as well: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1139737

**Comment by CyrusNajmabadi** [comment] 2024-10-25 04:12
Closing o ut due to lack of feedback on this.

**Closed by CyrusNajmabadi** 2024-10-25 04:12 UTC
Labels: Bug, Area-IDE, Tenet-User Friendly, Developer Community, Feature - Rename
