### ISSUE TITLE
Clickable hyperlink in IntelliSense tooltip from Obsolete 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50499] opened 2021-01-15 00:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Clickable-hyperlink-in-IntelliSense-tool/1298590)._

---
[severity:I'm unable to use this version]
I cannot get the Clickable hyperlink from ObsoleteAttribute class under VS Intellisense  tooltip.
Like this:

! [image.png] (https://aka.ms/dc/image?name=B321cbcab77c14a07bf5c16dfe7fc82b0637449126774832297_20201230-161116-image.png&tid=321cbcab77c14a07bf5c16dfe7fc82b0637449126774832297)

I cannot get the clickable hyperlink. 

**However**, when I use this for xml documentation comments:

! [image.png] (https://aka.ms/dc/image?name=B863a6e66d58f4658b0069d94f16a00c9637449127621343389_20201230-161241-image.png&tid=863a6e66d58f4658b0069d94f16a00c9637449127621343389)

It works well. So how this happens?

---
#### Feedback Bot on 12/30/2020, 00:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### mis tian on 1/4/2021, 00:03 AM: 

<p>Hi, any progress about this issue?</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2021-01-19 20:56
The text passed to [`ObsoleteAttribute(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.-ctor?view=net-5.0#System_ObsoleteAttribute__ctor_System_String_) is rendered as a text literal. There is no support for styles; the BCL team would need to define a syntax for styles before we could apply them here.

/cc @stephentoub @terrajobst

**Comment by sharwell** [comment] 2021-06-02 18:26
Duplicate of #27139

**Closed by sharwell** 2021-06-02 18:26 UTC
Labels: Area-IDE, Blocked, Developer Community, Feature Request, IDE-IntelliSense, IntelliSense-Quick Info
