### ISSUE TITLE
Feature request: Ignore spaces in single line property definitions and single line expression bodies.

### ISSUE THREAD

**Issue by DasOhmoff** [dotnet/roslyn#43219] opened 2020-04-09 11:21 UTC
Hello, I have a feature request regarding the auto formatter. I personally organize my code by grouping and aligning it (with a plugin), because I find the code easier to read then. For example:
```
public class Person
{
   // Name of person
   public string Forename { get; set; }
   public string Surname  { get; set; }

   // Location of person
   public string State      { get; set; }
   public string PostalCode { get; set; }
   public string City       { get; set; }
   public string Address    { get; set; }

   // Note: I know that these could also be properties, this is just an example
   public string GetFullName    () => Forename + ' '  + Surname;
   public string GetFullLocation() => State    + ", " + PostalCode + ' ' + City + ", " + Address;
}
```
When I use the auto formatter, the code gets formatted like so:
```
public class Person
{
   // Name of person
   public string Forename { get; set; }
   public string Surname { get; set; }

   // Location of person
   public string State { get; set; }
   public string PostalCode { get; set; }
   public string City { get; set; }
   public string Address { get; set; }

   public string GetFullName() => Forename + ' ' + Surname;
   public string GetFullLocation() => State + ", " + PostalCode + ' ' + City + ", " + Address;
}
```
It would be great to have options in the formatting settings that change this behavior. There is a similar option which is called "Ignore spaces in declaration statements":
![image](https://user-images.githubusercontent.com/16063186/78889407-e0cb6b00-7a63-11ea-9feb-f7d2af7a2f9c.png)

These two extra options would be very much appreciated:
    - Ignore spaces in single line property definitions.
    - Ignore spaces in single line expression bodies.

Thank you for your help :)

**Comment by sharwell** [comment] 2020-04-09 13:29
Duplicate of #31691

**Comment by sharwell** [comment] 2020-04-09 13:30
This is _slightly_ different from the linked issue, but the outcome is the same. The formatter extension that works for one will either work automatically with the other, or will work with minimal modification.

**Closed by sharwell** 2020-04-09 13:29 UTC
