### ISSUE TITLE
Intellisense not properly picking up model members when using @model IEnumerable <type>

### ISSUE THREAD

**Issue by mjnorman** [dotnet/roslyn#23040] opened 2017-11-07 01:19 UTC
**Version Used**: 
VS2017 netcoreapp2.0

v 15.4.2, although happened on previous patch also.
**Steps to Reproduce**:

1. Create razor view with `@model IEnumerable <anytype>`
2. Using @Html.DisplayNameFor (), intellisense does not recognize the model properties inside the IEnumerable.  It will only show the IEnumerable methods.

**Expected Behavior**:
Intellisense should show model properties in the format `model => model.property`.

**Actual Behavior**:
Only visible properties are IENUMERABLE such as Append, etc.

More discussion at this closed issue over at dotnet/Razor, 

https://github.com/aspnet/Razor/issues/1755

**Comment by CyrusNajmabadi** [comment] 2017-11-07 01:23
Could you provide a gist (or example here) with a full source code example of this?

**Comment by mjnorman** [comment] 2017-11-07 01:24
Sure thing.  --

Ok, better with specifics for sure.

Given the following model:
```
    public partial class MOM
    {
        public int Id { get; set; }
        [Display(Name = "Message")]
        public int? MessageId { get; set; }
        [Display(Name = "UUI")]
        public int? UuiId { get; set; }
        [Display(Name = "Transfer Number")]
        public string Transfernumber { get; set; }
        [Display(Name = "Application")]
        public int? AppId { get; set; }
        [Display(Name = "Dialed Number")]
        public int DnisId { get; set; }

        public Applications App { get; set; }
        public Dnis Dnis { get; set; }
        public Message Message { get; set; }
        public Uui Uui { get; set; }
    }
```

The scaffolded cshtml page is created as below:

```
@model IEnumerable<ncotelecom.MOMCore.Data.Models.MOM>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Transfernumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dnis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Uui)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Transfernumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.App.Application)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dnis.Dialednumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message.Messagedetail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uui.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
```

Ok no issue so far, everything works fine.  You'll notice that in the table header section, the @Html.DisplayNameFor() method is taking <model.member> as input, and everything compiles and runs.  
However, if you attempt to use intellisense in the header section you get the IEnumerable methods, not the inner model.  So if I can pass model.member as a parameter, intellisense should be smart enough to see that.

**Comment by CyrusNajmabadi** [comment] 2017-11-07 01:30
Based on the linked issue, i'm guessing this is a dupe of https://github.com/dotnet/roslyn/issues/8237.  However:

1. I'm don't know enough to state that with certainty.
2. Even if it is a dupe, we should def keep your issue tracked so that any fix is validated against your usecase.

Tagging @sharwell @jinujoseph on this.

**Comment by mjnorman** [comment] 2017-11-07 01:37
Just read through that and definitely looks the same.

**Comment by CyrusNajmabadi** [comment] 2024-10-18 22:07
This is razor.  Closing out as this should be tracked by them if its still an issue in their new lsp editor.

**Closed by CyrusNajmabadi** 2024-10-18 22:07 UTC
Labels: Area-IDE, Area-Compilers
