### ISSUE TITLE
.NET 9 regression: Collection initializer with call to Span property results in System.InvalidOperationException: Unexpected value 'PropertyAccess' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'

### ISSUE THREAD

**Issue by RobinsonWM** [dotnet/roslyn#75222] opened 2024-09-24 19:51 UTC
**Version Used**: 

Works as expected with .NET SDK `8.0.400`
Fails with .NET SDK `9.0.100-rc.1.24452.12`

**Steps to Reproduce**:

```csharp
using System.Collections.Immutable;

ReadOnlyMemory<byte> data = new byte[]{1, 2, 3}.AsMemory();
ImmutableArray<byte> immutable = [..data.Span];
```

**Expected Behavior**:

The code compiles, and when run, `immutable` is created as a new ImmutableArray with the contents of `data`.

**Actual Behavior**:

An exception is thrown during compilation.

```no-highlight
>dotnet build
Restore complete (0.5s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  ConsoleApp1 failed with 82 error(s) (11.4s)
    C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Roslyn\Microsoft.CSharp.Core.targets(89,5): error : Process terminated. System.InvalidOperationException: Unexpected value 'PropertyAccess' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
    C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used)
    C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
    C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters, ImmutableArray`1 argRefKindsOpt)
```

The exception didn't have any information about which line in the codebase caused the failure.  In order to create the minimal repro, I had to attach a debugger and break on the exception to see where the problem happened.

**Comment by cston** [comment] 2024-09-24 19:57
Same issue as https://github.com/dotnet/roslyn/issues/75194?

**Comment by RobinsonWM** [comment] 2024-09-24 20:00
Ah yes, seems likely.  The exception message is different, but I missed that both issues are related to collection initializers with the spread operator.

**Comment by jaredpar** [comment] 2024-09-24 22:00
closing as a dupe of #75194

**Closed by jaredpar** 2024-09-24 22:00 UTC
Labels: Area-Compilers, untriaged
