### ISSUE TITLE
"var foo = (null," autocompletes "null" to Nullable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30592] opened 2018-10-18 19:34 UTC
The intellisense autocompletion (set to its default state) for C# projects does not handle tuples with `null` as a value correctly. 

Typing in the following

```
var foo = (null,
```

causes `null` to be changed to `Nullable` as soon as the `,` is typed in.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/325201/var-foo-null-autocompletes-null-to-nullable.html

**Comment by CyrusNajmabadi** [comment] 2018-10-18 19:57
`var foo = (null` can't start a legal statement.  That's because the compiler will not allow 'null' there as there's no type to convert it to.

**Comment by mqudsi** [comment] 2018-10-18 20:18
_I filed this via the visual studio feedback_

You are correct that it's not legal, that was an incorrect, contrived case of the bug I was experiencing and a poor attempt at simplifying it.

At any rate, I can't reproduce it under 15.9 Preview 3, so yay!

**Comment by jinujoseph** [comment] 2018-10-18 20:31
Thanks @CyrusNajmabadi 
@mqudsi glad your concern is addressed, closing this issue

**Comment by sharwell** [comment] 2018-10-18 20:32
```csharp
using System;
public class C {
    public void M() {
        var data = (null, null);
    }
}

public class var {
    public static implicit operator var((Object, Object) details) { throw null; }
}
```

**Comment by Neme12** [comment] 2018-10-18 20:38
@sharwell

> At any rate, I can't reproduce it under 15.9 Preview 3, so yay!

![image](https://user-images.githubusercontent.com/11444821/47182747-8b0e7a80-d326-11e8-8f55-96e0f07efb80.png)

**Comment by sharwell** [comment] 2018-10-18 20:39
@Neme12 Ah, thanks. Thread moved ahead while I was typing the example.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 20:43
@sharwell 's case is clearly not realistically going to happen :)   Though the pedantry is appreciated :D

**Comment by mqudsi** [comment] 2018-10-18 20:48
I'm sorry, I was too hasty.

I `rg`d through my codebase and was able to reproduce it after all:

![image](https://user-images.githubusercontent.com/606923/47183264-369ad900-d2ed-11e8-8e86-d77f2eeaf093.png)

**Comment by Neme12** [comment] 2018-10-18 20:52
@mqudsi Can you please make a minimum repro that we can look at?
I still cannot reproduce this:
![image](https://user-images.githubusercontent.com/11444821/47183475-6adfbb00-d328-11e8-9194-a7f4e5cf3957.png)
Thanks

**Comment by CyrusNajmabadi** [comment] 2018-10-18 20:52
@Neme12 is it possible because of hte next line?  It may be that his code is getting parsed as a cast.  and thus only showing types within it.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 20:53
Paging @jcouv

**Comment by Neme12** [comment] 2018-10-18 20:54
Yes, you're right. It's the next line:
![image](https://user-images.githubusercontent.com/11444821/47183572-b09c8380-d328-11e8-85c4-ede25f094622.png)

**Comment by CyrusNajmabadi** [comment] 2018-10-18 20:54
I repro this as well:

![image](https://user-images.githubusercontent.com/4564579/47183601-54f8d880-d2dd-11e8-9d32-62899d97b28a.png)

Likely due to parsing as a cast.

**Comment by CyrusNajmabadi** [comment] 2018-10-18 20:55
@mqudsi Definitely a bug.  And definitely a realistic user scenario that should be addressed.  @jinujoseph to assign/milestone according.

**Comment by mqudsi** [comment] 2018-10-18 21:03
Thanks for figuring it out, @CyrusNajmabadi.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 19:41
I don't repro this.

**Closed by CyrusNajmabadi** 2024-10-21 19:41 UTC
Labels: Bug, Area-IDE, Developer Community
