### ISSUE TITLE
MSBuildWorkspace cannot compile project

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#10629] opened 2016-04-15 21:48 UTC
**Version Used**:  Microsoft.CodeAnalysis 1.2.1

**Steps to Reproduce**:

1. Sample project (one project, one file) at: https://github.com/JoshVarty/MSBuildWorkspaceBug
2. Use the following to try to build the project:

```CSharp
//Replace with the correct filepath
var filePath = @"C:\Users\JoshVarty\Documents\GitHub\MSBuildWorkspaceBug\MSBuildWorkspaceBug.sln";
var msbws = MSBuildWorkspace.Create();
var soln = msbws.OpenSolutionAsync(filePath).Result;

foreach(var proj in soln.Projects)
{
    var name = proj.Name;
    var compilation = proj.GetCompilationAsync().Result;
    var errors = compilation.GetDiagnostics().Where(n => n.Severity == DiagnosticSeverity.Error).ToList();
}
```
3. Observe the following four errors:

```
C:\Users\JoshVarty\Documents\GitHub\MSBuildWorkspaceBug\raw\RawAssemblyAttributes.cs(12,11): error CS0246: The type or namespace name 'CLSCompliantAttribute' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\JoshVarty\Documents\GitHub\MSBuildWorkspaceBug\raw\RawAssemblyAttributes.cs(12,11): error CS0246: The type or namespace name 'CLSCompliant' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\JoshVarty\Documents\GitHub\MSBuildWorkspaceBug\raw\RawAssemblyAttributes.cs(12,24): error CS0518: Predefined type 'System.Boolean' is not defined or imported
C:\Users\JoshVarty\Documents\GitHub\MSBuildWorkspaceBug\raw\RawAssemblyAttributes.cs(11,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
```

**Expected Behavior**:

Compiles without errors as it does within Visual Studio.

I'm assuming there are problems with the references, so I'll include the `.csproj` here as well:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <ProductVersion>8.0.50727</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{C18D303B-2C55-43EB-A3DF-39CF3FB1D447}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>raw</RootNamespace>
    <AssemblyName>raw</AssemblyName>
    <WarningLevel>4</WarningLevel>
    <StartupObject>
    </StartupObject>
    <AssemblyOriginatorKeyFile>
    </AssemblyOriginatorKeyFile>
    <AssemblyOriginatorKeyMode>File</AssemblyOriginatorKeyMode>
    <SignAssembly>true</SignAssembly>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <OldToolsVersion>2.0</OldToolsVersion>
    <UpgradeBackupLocation />
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <TargetFrameworkProfile>Client</TargetFrameworkProfile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\..\..\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <RunCodeAnalysis>true</RunCodeAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>..\..\..\bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RawAssemblyAttributes.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System">
      <HintPath>..\..\..\..\..\..\..\..\..\..\..\..\..\WINDOWS\Microsoft.NET\Framework\v2.0.50727\System.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSHARP.Targets" />
  <PropertyGroup Condition="">
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
</Project>
```

**Comment by JoshVarty** [comment] 2016-04-16 22:09
If I add:
```
<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
```

to the first `PropertyGroup` it seems to compile correctly.

**Comment by Pilchie** [comment] 2016-04-21 20:54
It sounds like this is a dupe of #5389.

**Closed by Pilchie** 2016-04-21 20:54 UTC
Labels: Area-IDE
