### ISSUE TITLE
`NotNullIfNotNull` does not flow when using delegates as method groups.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/roslyn#67288] opened 2023-03-13 23:13 UTC
**Version Used**: `Compiler version: '4.5.0-6.23123.11 (271ccd71)'. Language version: latest (11.0).`

**Steps to Reproduce**:

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRhQG4BYAKGz3wDoBJAeVItwOoBkBLAOwEcnyMAZjwAmHAGEcAb3I45eYQSRVBAHgJYAfDgBiECDgC8m2fLMARDrDAAXaAE9qAUS4BXALYwoAQxswdHAA2MADOABQARBEANDhRAJTUAMowwbZhAAq+ABbUAOIwNgHBAHLenvFMAL5AA)

```csharp
using System.Collections.Generic;
using System.IO;
using System.Linq;

public class C {
    public static IEnumerable<string> Foo =>
        Directory.EnumerateFiles("", "").Select(Path.GetFileName);
}
```

**Expected Behavior**: Code successfuly compiles without warnings. It does if a lambda were used instead of a method group.

**Actual Behavior**: `warning CS8619: Nullability of reference types in value of type 'IEnumerable<string?>' doesn't match target type 'IEnumerable<string>'.` on the entire implementation of `Foo`.

**Comment by RikkiGibson** [comment] 2023-03-14 20:31
I think this is a duplicate of #44174.

**Comment by RikkiGibson** [comment] 2023-03-14 20:32
Thank you for reporting, it does help us gauge the impact of the bug here.

**Closed** 2023-03-14 20:32 UTC
Labels: Bug, Resolution-Duplicate, Area-Compilers, New Language Feature - Nullable Reference Types
