### ISSUE TITLE
Func<T>.?Invoke won't compile in all cases

### ISSUE THREAD

**Issue by AceHack** [dotnet/roslyn#26340] opened 2018-04-23 18:15 UTC
**Version Used**: 
7.2

**Steps to Reproduce**:
```
        public static T Get<T>(Func<T> func)
        {
            return func?.Invoke();
        }
```
**Expected Behavior**:
Complies method

**Actual Behavior**:
> Error - CS0023 - Operator '?' cannot be applied to operand of type 'T'	

If I change the definition to 
```
        public static T Get<T>(Func<T> func)
            where T : class
        {
            return func?.Invoke();
        }
```
Then it will compile.  This is very odd.  func is should always be able to ?.

**Comment by Joe4evr** [comment] 2018-04-23 23:52
This probably stems from the fact that the `func?.Invoke()` expression is translated to return a `T?`, but since `T` is unconstrained, it's not possible to apply that since it may be a value type, and nullable value types are a distinct type.

That code returning `CS0023` is something that could see an improvement, though. If you were to change it to return a defined struct type instead of a generic:
```cs
public static int Get(Func<int> func)
{
    return func?.Invoke();
}
```
[then you get the much more sensible error](https://sharplab.io/#v2:D4AQDABCCMDcCwAoJMBsUBMEDCSDeSERUAzFNOgJYB2ALhAOICmtAFCAKwA8NtAfBABmAV2oBjAJSFiBRMXlQA7ENFiA/ADoAktQBuAewDWTVhIRziAXySWgA===): `error CS0266: Cannot implicitly convert type 'int?' to 'int'. An explicit conversion exists (are you missing a cast?)`

**Comment by svick** [comment] 2018-04-24 00:03
This is pretty much a duplicate of https://github.com/dotnet/roslyn/issues/25471. The conclusion in that issue is what @Joe4evr said: the compiler behaves correctly, but the error message could be improved.

**Comment by AceHack** [comment] 2018-04-24 01:50
That's very helpful thanks so much.

**Comment by jcouv** [comment] 2018-04-24 14:32
Thanks all.
I'll go ahead and close a duplicate of #25471.

**Closed by jcouv** 2018-04-24 14:32 UTC
