### ISSUE TITLE
VS crashes when moving a line past a label in a c# file

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#17750] opened 2017-03-11 19:32 UTC
**Version Used**: 
```
Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA284
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA284
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA284
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA284
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

CodeRush for Roslyn   16.2.6.0
DevExpress CodeRush for Roslyn package.

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Markdown Editor   1.11.201
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SolutionVisualizer   1.0
SolutionVisualizer

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio
```

**Steps to Reproduce**:

1. Open [Lexer.cs](https://gist.github.com/orthoxerox/49e7f0b0100b79cec1b435b76c26584d)
2. Navigate to line 159 (`public Token Current => cache.Peek();`)
3. Hold Alt+Up

**Expected Behavior**:

The line is moved past line 102: (`match:`)

**Actual Behavior**:

VS crashes with error:

```
  <entry>
    <record>677</record>
    <time>2017/03/11 19:29:12.117</time>
    <type>Error</type>
    <source>Color Theme Service</source>
    <description>The color &apos;Popup&apos; in category &apos;de7b1121-99a4-4708-aedf-15f40c9b332f&apos; does not exist.</description>
  </entry>
```

If line 102 is commented out, no crash occurs, so it looks like it's a Roslyn error.

**Comment by jasonmalinowski** [comment] 2017-03-13 18:04
@orthoxerox: thanks for the (very simple!) bug report.

Moving to the compiler, the underlying exception here is in the incremental parser:

```
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GreenNode.AdjustFlagsAndWidth(Microsoft.CodeAnalysis.GreenNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LabeledStatementSyntax.LabeledStatementSyntax(Microsoft.CodeAnalysis.CSharp.SyntaxKind kind, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken colonToken, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.StatementSyntax statement, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxFactoryContext context)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ContextAwareSyntax.LabeledStatement(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken colonToken, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.StatementSyntax statement)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLabeledStatement()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementNoDeclaration(bool allowAnyExpression)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatements(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CSharpSyntaxNode previousNode, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.StatementSyntax> statements, bool stopOnSwitchSections)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlock(bool isMethodBody, bool isAccessorBody)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlockAndExpressionBodiesWithSemicolon(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax blockBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ArrowExpressionClauseSyntax expressionBody, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken semicolon, bool parseSemicolonAfterBlock, Microsoft.CodeAnalysis.CSharp.MessageID requestedExpressionBodyFeature)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeParameterListSyntax typeParameterList)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind, string typeName)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceDeclaration()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax>(System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> parseFunc, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> createEmptyNodeFunc)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(Microsoft.CodeAnalysis.Text.SourceText newText, System.Collections.Generic.IReadOnlyList<Microsoft.CodeAnalysis.Text.TextChangeRange> changes)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(Microsoft.CodeAnalysis.Text.SourceText newText)	Unknown
```

**Comment by jaredpar** [comment] 2017-05-16 21:26
Thanks for reporting.  Looks like a dupe of https://github.com/dotnet/roslyn/pull/19281

**Closed by jaredpar** 2017-05-16 21:26 UTC
Labels: Area-Compilers, Bug
