### ISSUE TITLE
CS8121 - should this be a warning not an error?

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#45394] opened 2020-06-23 18:15 UTC
Scenario - `sealed` type that **does not** implement an interface that we're testing for:

``` c#
interface IHazFeature { void DoTheThing(); }
sealed class SomeType { }
static void Main()
{
    var obj = new SomeType();
    if (obj is IHazFeature haz) // error CS8121 - An expression of type 'SomeType' cannot be handled by a pattern of type 'IHazFeature'.	
    {
        haz.DoTheThing();
    }
}
```

Now, you can look at this and think "well, the compiler is right, it never does implement that interface - the type is sealed", but: the compiler is wrong. Because in this case, whether `SomeType : IHazFeature` is **library version dependent**, and later versions of the library (that we don't want to demand in the ref tree, but we want to support if it is there) *do* implement it. It could also be TFM-specific in a multi-targeted library where we're targeting the generic (netstandard) version, and some TFMs have more specific features.

We can work around it with:

``` c#
if ((object)obj is IHazFeature haz)
{
    haz.DoTheThing();
}
```

but this smells like it should never have been an *error* here, but rather: a warning. Because the compiler cannot be sure about the intent / context, and the code as written *can be correct*.

**Comment by jaredpar** [comment] 2020-06-24 21:32
@gafter for patterns

> Now, you can look at this and think "well, the compiler is right, it never does implement that interface - the type is sealed", but: the compiler is wrong

It is true that the `class` could be come unsealed in a future version. At the same time though at the moment we compiled this code the type was `sealed` and we emit the diagnostics based on that designation. The compiler is fairly consistent in this approach. 

Consider for example deriving from a type. Should we allow derivation even though the type is `sealed` because at load time it could be unsealed? Why should the compiler respect `sealed` in one case but not the other?

> Because the compiler cannot be sure about the intent / context, and the code as written can be correct.

As written the code cannot be correct, it requires an external change to become valid.

**Comment by gafter** [comment] 2020-06-24 21:54
These are also an error for the same reason:

```csharp
        var x = (IHazFeature)obj;
        var y = obj as IHazFeature;
```

I can imagine changing the language to allow all three, but the intent of this error is that it is more useful to the programmer to give an error for this than to permit it. As you say, you can usually cast.

Closing as by design. If you want a language change, please propose it in `csharplang`.

**Closed by gafter** 2020-06-24 21:54 UTC
Labels: Area-Compilers
