### ISSUE TITLE
Recommend types that are not imported yet in the autocomplete list

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#21233] opened 2017-08-01 11:40 UTC
```cs
class C {
  void M() {
    Int32|
  }
}
```
Int32 should show up in the list and once it's committed (e.g. by hitting space) `using System;` should be inserted.

**Comment by Pilchie** [comment] 2017-08-08 21:09
Duplicate of #7053

**Closed by Pilchie** 2017-08-08 21:09 UTC
Labels: Area-IDE, Feature Request
