### ISSUE TITLE
Go-To-Member not finding members

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#38649] opened 2019-09-11 22:56 UTC
Using go-to-all with the `m` filter will occasionally not find any members whatsoever. I haven't found a consistent repro for this yet, but when it starts it repros continuously. Repros on Version 16.4.0 Preview 1.0 [29310.158.master]

**Comment by 333fred** [comment] 2019-09-11 22:57
I've taken a trace with the roslyn general purpose settings and left it here: "\\mlangfs1\public\frsilb\dumps\38649\ReproTrace.etl.zip"

**Comment by jinujoseph** [comment] 2020-02-21 21:15
looks like dupe of https://github.com/dotnet/roslyn/issues/41122

**Comment by 333fred** [comment] 2020-02-21 23:53
@jinujoseph no, that's too many symbols showing. This is no symbols showing.

**Comment by vsccarl** [comment] 2020-04-20 18:51
I've tried this out in 30019.14.d16.6 and I've been unable to repro.

**Comment by jinujoseph** [comment] 2020-04-20 19:10
@333fred closing as no repro or fixed in latest build .
Can you revalidate and reopen if you continue to see the issue here?

**Closed by jinujoseph** 2020-04-20 19:10 UTC
Labels: Area-IDE, Bug

**Comment by 333fred** [comment] 2020-04-20 19:12
I've never been able to get a consistent repro, so if I see it again I'll reopen. But I can't say with confidence it's fixed either. 😔
