### ISSUE TITLE
Failure of BasicVenus.xml  is blocking integration from master to future

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#10729] opened 2016-04-20 19:09 UTC
See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/625/

**Comment by balajikris** [comment] 2016-04-20 23:27
dupe of https://github.com/dotnet/roslyn/issues/9409

**Closed** 2016-04-20 23:27 UTC
Labels: Area-IDE, Resolution-Duplicate, Test, Urgency-Now
