### ISSUE TITLE
Error/Warning messages on network share are not navigable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74105] opened 2024-06-21 16:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ErrorWarning-messages-does-not-react-to/10664069)._

---
[regression] [worked-in:17.9.7]
Clicking on any error/warning does not react, does not jump to the code row where the problem is.
I just rolled the version back.

---
#### Alison Jin [MSFT] on 5/22/2024, 01:56 AM: 

(private comment, text removed)
#### anhig on 5/22/2024, 02:30 AM: 

(private comment, text removed)
#### anhig on 5/23/2024, 10:12 AM: 

(private comment, text removed)
#### Feedback Bot on 5/26/2024, 06:53 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 5/28/2024, 00:20 AM: 

(private comment, text removed)
#### anhig on 5/29/2024, 01:48 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 5/30/2024, 02:42 AM: 

(private comment, text removed)
#### Feedback Bot on 6/12/2024, 01:44 AM: 

(private comment, text removed)
#### anhig on 6/12/2024, 02:17 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 6/18/2024, 02:32 AM: 

(private comment, text removed)
#### Feedback Bot on 6/20/2024, 06:07 AM: 

(private comment, text removed)
#### frank.stutzkowski on 6/21/2024, 00:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-06-21 16:24
My guess is that we get a URI wrong.  @dibarbet can you ptal.  It may be on our end, or it may end up gonig to @kayle if we're doing things properly on hte roslyn side.  

If it is our end, i'm likely to insist that we remove whatever manual file-path munging code we have :)

**Comment by MarcioRodrigues001** [comment] 2024-07-05 19:22
Alguma solução par essa questão

**Comment by dibarbet** [comment] 2024-07-11 18:02
Duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2073453/, should be fixed in 17.12 P1

**Closed by dibarbet** 2024-07-11 18:02 UTC
Labels: Area-IDE
