### ISSUE TITLE
Unable to instantiate analyzer

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6512] opened 2015-11-02 17:26 UTC
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit32/359
```
CSC : error CS8032: An instance of analyzer Roslyn.Diagnostics.Analyzers.Reliability.MixedVersionsOfMefAttributesAnalyzer cannot be created from C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.RoslynDiagnostics\1.1.1-beta1-20150818-01\tools\Roslyn.Diagnostics.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. [d:\j\workspace\roslyn-internal_master_win_rel_unit32\Open\src\Workspaces\Core\Portable\Workspaces.csproj]
```

**Comment by amcasey** [comment] 2015-11-02 17:27
It's not surprising that it couldn't be found - there should be a binding redirect to whichever version (1.1, 1.2, or 2.0) the build produces (1.2, in this case).

**Comment by tmeschter** [comment] 2015-11-02 19:03
The binding redirect needs to be to the version of the compiler that is being used, which may or may not be the same as the version of the compiler being produced.

**Comment by mavasani** [comment] 2015-11-02 19:26
The binding redirects come from the compilers (csc.exe.config, vbc.exe.config, VBCSCompiler.exe.config), there is nothing special being done for analyzers.
My question: Is there a build break in roslyn-internal master branch due to this OR was this a one off failure seen while attempting to merge stabilization into master (I see this build is for Tanner's PR for the merge)?
If the build in master is not broken, then we can just ignore this failure. Adding @tannergooding to confirm.

**Comment by amcasey** [comment] 2015-11-02 21:36
It's happening in non-PR runs, but not consistently.

**Comment by amcasey** [comment] 2015-11-02 21:36
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p1/302/

**Comment by amcasey** [comment] 2015-11-02 21:37
Both failures were on rbld 3

**Comment by amcasey** [comment] 2015-11-02 21:38
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit32/366/

**Comment by amcasey** [comment] 2015-11-04 21:41
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_eta/313/
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit32/384/

**Comment by amcasey** [comment] 2015-11-04 21:41
@jaredpar, I see this has moved to your team.  Would you mind having someone look at it?

**Comment by davkean** [comment] 2015-11-20 03:18
Dropping infrastructure, as assigned to a feature team.

**Comment by davkean** [comment] 2015-11-20 03:42
I also hit this: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1985/.

This is way past the 48 turnaround for flaky issues, @jaredpar can you get someone to look at this?

**Comment by jaredpar** [comment] 2015-11-20 22:26
@agocke and I have looked at this.  It's very easy to imagine when this error would occur:

- A compilation is started using versions of Microsoft.CodeAnalysis with a version greater than 1.0.0.0 and there is no supporting config file with binding redirects. 

However we can't figure out a case where this would happen.  Here are all the known places where we use the compiler:

- The toolset nuget package: has the binding redirects.
- The bootstrap compiler: has the binding redirects. 
- MSBuild from VS 2015 RTM: uses the 1.0.0.0 version of Microsoft.CodeAnalysis. 

In all the above cases this error should not occur.  There must be some other case we are missing where the compiler gets used.  Perhaps there is still some machine patching going on here ...

**Comment by jaredpar** [comment] 2015-11-20 22:34
@agocke and I figured this out.  The root cause here is dci-win-rbld-03.  This is a machine that has lingered since we were patching Jenkins machines as a part of our internal test runs.  As a result the binaries in the MSBuild directory all have the version 42.42.42.42 and do not have proper binding redirects for that version.  

I've taken this machine offline.  I'll tell infraswat to nuke and rebuild it.

**Closed by jaredpar** 2015-11-20 22:34 UTC
Labels: Area-Compilers, Contributor Pain, Flaky
