### ISSUE TITLE
Consider renaming `ForEachVariableStatementSyntax`

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#35809] opened 2019-05-20 16:05 UTC
I just spent a few extra minutes debugging an issue which, ultimately, was caused by a lapse of mine: I never noticed such AST node `ForEachVariableStatementSyntax`.

I **think** that I understand the reason for the existence of "another foreach" node, given that `ForEachStatementSyntax` already has an identifier for the *singly* declared variable. Yet, I still wonder why not just creating an additional child node ...?

In the worst case, I'd suggest renaming `ForEachVariableStatementSyntax` to `ComplexForEachStatementSyntax` or something in the like. The current name is not very distinguishing and also misleading (i.e., i'd imply that the original `ForEachStatementSyntax` doesn't declare a variable).

**Comment by sharwell** [comment] 2019-05-20 16:13
This type is part of our stable public API (already shipped to customers), so it is not possible to rename it. Do you have any suggestions for how we can improve this API without renaming it?

**Comment by CyrusNajmabadi** [comment] 2019-05-20 16:56
> Yet, I still wonder why not just creating an additional child node ...?

The main issue is that we don't want nodes that have a complex relationship between subsets of their children and their presence/absence.  So, with ForEach, the existing node has the two children for `Type name`, and the new one has a single child for the `Variable`.  We don't want to have a situation where you then need to know that you either have those original two nodes, or this one new node.  

Admittedly, this is all somewhat of an unfortunate historical issue as we likely should never have taken anything variable-esque and 'inlined' the form into the parent.  i.e. we shouldn't have modeled the original ForEach node with 'Type identifier' directly into the node.  We should have used one of the broader node types that already encompasses that form and more.  It would have given us more flexibility in the future and not limited our hands here.

--

However, as Sam says, we've shipped this, and we can't really get rid of these.  So, of a lot of not-great choices, this was hte best non-great choice we had.

**Comment by ltcmelo** [comment] 2019-05-20 19:13
@sharwell, I can't think of a change that would significantly improve the API without causing any break. But, maybe, to make things more uniform, depreciating both `ForEachStatementSyntax`/`ForEachVariableStatementSyntax` and introducing an unified `RangeBasedForStatementSyntax`. At least the name would stand out.

@CyrusNajmabadi, I see... I imagined something like that. Yet, can't actually tell whether that would still be a more intuitive API, though.

**Comment by CyrusNajmabadi** [comment] 2019-05-20 19:38
So our policy is to not deprecate nodes.  Or to ahve existing code constructs generate some new node.  This breaks existing analyzers/fixers/etc. that are written against the original constructs.

**Comment by sharwell** [comment] 2019-05-22 05:35
I'm going to close this as **By Design** - specifically by the design for our long-term compatibility policy. There are a few unfortunate API forms that snuck in over time, but the policy helps more often than it hurts. 😅

**Closed by sharwell** 2019-05-22 05:35 UTC

**Comment by sharwell** [comment] 2019-05-22 05:36
@dotnet/compiler please reopen this if you disagree with my resolution.
