### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p2 on PR #11023

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#11035] opened 2016-05-03 21:12 UTC
PR: [#11023](https://github.com/dotnet/roslyn/pull/11023) *Add options to enable/disable nuget search.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/715/

**1 Test Failures:**
CSharpLineSeparators.Verify Line Separators

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpLineSeparators.xml

**Comment by Pilchie** [comment] 2016-05-03 21:14
Dupe of https://github.com/dotnet/roslyn/issues/10916

**Closed by Pilchie** 2016-05-03 21:14 UTC
Labels: Bug
