### ISSUE TITLE
Analyzer improperly suggests inlining declaration to "out var" 

### ISSUE THREAD

**Issue by vcsjones** [dotnet/roslyn#18936] opened 2017-04-23 17:45 UTC
**Version Used**: VS2017 15.1 (26403.7).

**Steps to Reproduce**:

Given a method with a signature like this:

```csharp
public IDisposable Foo(out string baz) {
    baz = "hello";
    return default(IDisposable);
}
```

If this `Foo` is placed in a Dispose using statement, and the `baz` is used later after the dispose block, an analyzer will improperly suggestion making `Foo`'s out variable as an "out var". For example:

```csharp
string baz;
using (Foo(out baz))
{
    //...
}
baz.ToLower();
```

**Expected Behavior**:

No suggestion to move `baz` to an inline declaration.

**Actual Behavior**:

The analyzer suggests inlining, thus resulting in broken code.

![screen shot 2017-04-23 at 1 43 59 pm](https://cloud.githubusercontent.com/assets/361677/25315904/0cabbdbc-282b-11e7-99f6-7b05a954a71e.png)

**Comment by sharwell** [comment] 2017-04-23 19:32
This appears to be a duplicate of #18076, which I fixed a short time ago and expect to see in the 15.3 release. 👍

**Closed by sharwell** 2017-04-23 19:32 UTC
