### ISSUE TITLE
VB quickfix "insert missing cast" doesn't work and lacks preview - regression from VS2013

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3161] opened 2015-05-28 23:36 UTC
Here's a screenshot. There is a quickfix offering to "Insert Missing Cast". However performing the quickfix doesn't make any fixes to my file. Additionally, there is no inline preview of what the fix will look like, and clicking on the "Preview Changes" link shows no changes.
![fails-to-cast](https://cloud.githubusercontent.com/assets/3316258/7873440/3e137e24-0557-11e5-8685-c53a677b9ab7.png)
Note that if I manually fix up my code, with CType(red,Color), then it compiles correctly.

Here's full source code for the repro.
```vb
Option Strict On

Module Module1

    Sub Main()
        Dim red = ColorF.FromArgb(255, 255, 0, 0)
        Dim c As Color = red
    End Sub

End Module

Public Structure ColorF
    Public A, R, G, B As Single
    Public Shared Function FromArgb(a As Double, r As Double, g As Double, b As Double) As ColorF
        Return New ColorF With {.A = CSng(a), .R = CSng(r), .G = CSng(g), .B = CSng(b)}
    End Function
    Public Shared Widening Operator CType(x As Color) As ColorF
        Return ColorF.FromArgb(x.A / 255, x.R / 255, x.G / 255, x.B / 255)
    End Operator
    Public Shared Narrowing Operator CType(x As ColorF) As Color
        Return Color.FromArgb(CByte(x.A * 255), CByte(x.R * 255), CByte(x.G * 255), CByte(x.B * 255))
    End Operator
End Structure

Public Structure Color
    Public A, R, G, B As Byte
    Public Shared Function FromArgb(a As Byte, r As Byte, g As Byte, b As Byte) As Color
        Return New Color With {.A = a, .R = r, .G = g, .B = b}
    End Function
End Structure
```

**Comment by ljw1004** [comment] 2015-05-28 23:40
This bug might be related to #3163 (where, if you insert the missing cast, then it tells me that the cast was redundant!)

**Comment by srivatsn** [comment] 2015-06-01 22:10
If this is the same as #3163, please resolve this as dupe.

**Comment by jmarolf** [comment] 2015-06-03 03:18
Duplicate of #3163

**Closed by jmarolf** 2015-06-03 03:18 UTC
Labels: Area-Analyzers, Bug, Resolution-Duplicate
