### ISSUE TITLE
Toggling Show advanced build configurations should update project's configuration

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#28267] opened 2018-07-03 18:56 UTC
**Version Used**: 15.8 preview 5

**Steps to Reproduce**:

1. Create a C# console application (desktop)
2. Ensure that `Debug` configuration is used
3. Create an `#if DEBUG` block inside of a class
4. Write a method inside of the `#if DEBUG` block
5. Turn on simplified build (turn off "Show advanced build configurations" in Tools -> Options)

**Expected Behavior**:

Either:
1. Project should be build using debug configuration
2. Method inside of `#if DEBUG` should no longer be highlighted

**Actual Behavior**:

1. The project ends up being built into the release folder
2. Method inside of `#if DEBUG` is still syntax highlighted

**Comment by ManishJayaswal** [comment] 2018-07-03 21:50
@Pilchie @davkean @heejaechang @jinujoseph @jaredpar  - is this a known issue? It seems like entire rolsyn does not know what configuration the solution is in. This is happening on desktop projects as well. We realized this from the following feedback item - (https://devdiv.visualstudio.com/DevDiv/_queries/edit/638789/?triage=true)

**Comment by davkean** [comment] 2018-07-03 23:45
How did you come to conclusion of the expected behavior?

**Comment by davkean** [comment] 2018-07-03 23:52
(Had to familiarize with this feature again - ignore above) 

I just tried C# and Visual Basic Console Apps using legacy project system and cannot repro this. Both projects build to release & `#if DEBUG` are not parsed/highlight/colorized or built.

**Comment by davkean** [comment] 2018-07-03 23:56
Okay, can you try your repro a again, but after 5) wait 30 seconds for the file to be reparsed?

**Comment by drognanar** [comment] 2018-07-04 02:22
@davkean this is the first time I'm stumbling upon this feature too and definitely using the old project system.

Highlighting does not update after 30seconds. I did notice that running a build command builds into the release folder, but running a debug command builds into the debug folder. Intellisense and other anlyzers seem to use the most recently used configuration. So if I run the build command and reload the solution I see no highlighting, but if I debug the app and reload the solution I see highlighting.

**Comment by drognanar** [comment] 2018-07-04 02:23
It's confusing for both TestWindow's test discoverer and Live Unit Testing as they assume that Roslyn/project system's projects can be matched based on their output paths. However in the scenario where a debug command is run, the Roslyn project's output path targets the debug folder while the project system's project targets the release folder.

**Comment by davkean** [comment] 2018-07-04 02:37
I have zero idea what the expectation is here - I don't know how this feature is supposed to work.

**Comment by Pilchie** [comment] 2018-07-05 16:00
The feature here is that by default, the solution is in DEBUG, and F5 will debug a build from the DEBUG configuration, but if you execute just build, it will switch to release, build, and then switch back to debug.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:10
Closing out due to age and no more reports of this being an issue.

**Closed by CyrusNajmabadi** 2024-11-06 02:10 UTC
Labels: Bug, Area-IDE
