### ISSUE TITLE
String concatenation is incorrect in .net 6 preview 7

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/roslyn#56246] opened 2021-09-08 12:54 UTC
A piece of my code dynamically generates CSS style string. It worked perfectly in .net 5. However, in .net 6 (preview 7) the string concatenation is happening incorrectly.

Following is the test code:

ConcatTest.cs

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StringConcatBug
{
    public class ConcatTest
    {
        int[] dimensions = new int[2] { 2, 2 };
        int Rows { get => dimensions[0]; }
        int Columns { get => dimensions[1]; }

        public string GetStyleString(string rowGap = "", string colGap = "")
        {
            var stylestring = $"height:100%;width:100%;" +
                $"display: grid; " +
                $"grid: repeat({Rows},minmax(60px,2000px)) / repeat({Columns}, minmax(50px,2000px));" +
                $"gap:{rowGap} {colGap};min-width:0;";
            return stylestring;
        }
    }
}
```

Program.cs

```
StringConcatBug.ConcatTest test = new ();

Console.WriteLine(test.GetStyleString());

```

Output:

`height:100%;width:100%;display: grid; , minmax(50px,2000px));2,minmax(60px,2000px)) / repeat(2grid: repeat(;min-width:0; gap:`

It is clearly not what is expected. Attaching code sample for repro.

[StringConcatBug.zip](https://github.com/dotnet/aspnetcore/files/7128950/StringConcatBug.zip)

**Comment by mayur-ekbote** [comment] 2021-09-08 13:44
@SteveSandersonMS Is there a specific condition that causes this? It would help me in putting off testing in those cases till the fix arrives.

**Comment by SteveSandersonMS** [comment] 2021-09-08 14:53
I think the underlying issue is https://github.com/dotnet/roslyn/issues/55461, which might provide hints on a workaround or the trigger conditions.

**Comment by Youssef1313** [comment] 2021-09-08 16:49
I think the workaround is to replace:

```csharp
            var stylestring = $"height:100%;width:100%;" +
                $"display: grid; " +
                $"grid: repeat({Rows},minmax(60px,2000px)) / repeat({Columns}, minmax(50px,2000px));" +
                $"gap:{rowGap} {colGap};min-width:0;";
            return stylestring;
```

With:

```csharp
            var stylestring = $"height:100%;width:100%;display: grid; grid: repeat({Rows},minmax(60px,2000px)) / repeat({Columns}, minmax(50px,2000px));gap:{rowGap} {colGap};min-width:0;";
            return stylestring;

```

But it's much much better to update to a newer version with the fix.

**Comment by jaredpar** [comment] 2021-09-09 15:10
Closing as this is a dupe of #55461

**Closed by jaredpar** 2021-09-09 15:10 UTC
Labels: Area-Compilers, untriaged
