### ISSUE TITLE
Create an analyzer + fixer for missing OSS copyright comment

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#2022] opened 2015-04-15 21:15 UTC
We often forget to add the OSS copyright comments when creating new files. Based on recent code reviews this seems like a common problem. We have also had cases where the problem slipped past code reviewers unnoticed until someone happened to notice and fix up the issue a few weeks later.

Adding an analyzer + fixer for this would be nice. The analyzer would also be very cheap (purely syntax based and only needs to be invoked once per file).

**Comment by srivatsn** [comment] 2015-04-16 01:26
@dpoeschl - weren't you working on this?

**Comment by dpoeschl** [comment] 2015-04-16 16:16
Yeah, I have an old analyzer/fixer for this that I could update. It was difficult to integrate into our internal dogfooding experience at the time for various reasons, which is why it was not checked in then.

**Comment by sharwell** [comment] 2019-01-31 18:58
Duplicate of #33012

**Closed by sharwell** 2019-01-31 18:58 UTC
Labels: Area-Analyzers
