### ISSUE TITLE
SymbolKind.Preprocessing is not supported for symbol analyzer actions

### ISSUE THREAD

**Issue by AleksandrAlbert** [dotnet/roslyn#9709] opened 2016-03-12 01:47 UTC
I am trying to create a roslyn code analyzer that will require any code written in a #region block to be indented, as follows:

Default Visual Studio behavior
```
#region 
// code starts here
#endregion
```

Desired behavior
```
#region 
    // code should start here
#endregion
```

Having never written an analyzer before, my thoughts were that I would have to register a preprocessing symbol action in my DiagnosticAnalyzer
```
Initialize(AnalysisContext context)
{
    context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.Preprocessing);
}
```

I get an error however saying that SymbolKind.Preprocessing is not a supported symbol for analysis. How would I go about achieving my desired behavior?

**Comment by srivatsn** [comment] 2016-05-09 22:45
You need to Register a SyntaxTreeAction (`context.RegisterSyntaxTreeAction`) and go through the tree to identify the pre-processing blocks and compute the indent inside the blocks. Resolving as By design.

**Closed by srivatsn** 2016-05-09 22:45 UTC
Labels: Area-Analyzers, Resolution-By Design
