### ISSUE TITLE
Move to next highlighted reference stops working if the current reference is incremented

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#38484] opened 2019-09-04 17:46 UTC
**Version Used**: VS 16.2

**Steps to Reproduce**:

- Move caret to the first `i` and wait for it to be highlighted
- Move to next highlighted reference once (`Ctrl+Shift+Down`), wait 1 sec
- Move to next highlighted reference once (`Ctrl+Shift+Down`), wait 1 sec
- Move to next highlighted reference once (`Ctrl+Shift+Down`), only now it won't work

```C#
namespace ConsoleApp18
{
    class Program
    {
        static void Main(string[] args)
        {
            int i = 0;
            if (i == 1) { }
            i++;
            _ = i;
        }
    }
}
```

**Expected Behavior**:

The reference is still highlighted even if it's incrementing its value (`i++`) so you can move to the next reference again.

**Actual Behavior**:

The reference isn't highlighted anymore (it takes ~0.5 secs)

I think this is a regression.

**Comment by jasonmalinowski** [comment] 2020-05-27 21:24
What seems to be happening is when the selection is moved to the `i++`, the caret ends up landing between the `i` and the `++`. That's supposed to prefer the `i` side of things when we pick which token is active, but some reason we're not here.

**Comment by akhera99** [comment] 2021-06-29 22:58
Dupe of #51841

**Closed by akhera99** 2021-06-29 22:58 UTC
Labels: Area-IDE, Bug, IDE-Navigation, help wanted
