### ISSUE TITLE
Automatic placement of brackets at pressing the space key after typing a sub or function in vb.net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42036] opened 2020-02-29 01:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/929567/automatic-placement-of-brackets-at-pressing-the-sp.html)._

---
<p>There could be an add-in of some kind for Visual Studios 2015, 2017 and 2019, which would enable automatic placement of round brackets when user presses the space key, for example:</p><p>When I type &quot;MsgBox&quot;(or I select it from autocompletion menu) and then press Space, it would add round brackets and put the caret in between.</p> <p>… Just a quick thought, I know there're some considerations to be made...</p>

---
#### Visual Studio Feedback System on 2/25/2020, 05:13 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by kendrahavens** [comment] 2020-02-29 01:28
Possible duplicate of https://github.com/dotnet/roslyn/issues/12363 if C# and Visual Basic could be handled together.

**Comment by jinujoseph** [comment] 2020-03-05 00:34
Duplicate of #12363

**Closed by jinujoseph** 2020-03-05 00:34 UTC
