### ISSUE TITLE
lang=sql support

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/roslyn#74572] opened 2024-07-26 10:26 UTC
**Brief description:**

We have C# string syntax highlighting for C#, Json, Regex. Could we also have basic support for SQL?

https://github.com/dotnet/roslyn/tree/main/src/Features/Core/Portable/EmbeddedLanguages

This would be especially useful in EF Core migrations
```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                    UPDATE c
                    SET c.UserId = ur.UserId
                    FROM dbo.SomeTable c
                    INNER JOIN dbo.UserRoles ur ON c.Id = ur.SomeOtherId
                    WHERE ur.UserId IS NOT NULL;
                """
            );
        }
```

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by JoeRobich** [comment] 2024-07-26 20:49
This is a duplicate of #31028

**Closed by JoeRobich** 2024-07-26 20:49 UTC
Labels: Resolution-Duplicate, Area-IDE, Feature Request, untriaged
