### ISSUE TITLE
IOperation API for declaration expressions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#20798] opened 2017-07-11 19:04 UTC
We need to add a separate IOperation API to represent declaration expressions, currently they get represented as ILocalReferenceExpressions. See https://github.com/dotnet/roslyn/pull/20749#discussion_r126770272

Examples:
`M(out var x);`
`var (x, y) = (1, 2);`

**Comment by jinujoseph** [comment] 2017-07-13 19:35
We think these should be exposed as their own IOperation.  However, if this is difficult to do because of how the bound nodes work, then let us know.  We could decide that it's just too expensive and we can settle with just having ILocalReferenceExpressions with some sort of way to map from them to the declaration expression.

**Comment by jinujoseph** [comment] 2017-09-29 20:06
@333fred can you verify if we did declarationExpression ?

**Comment by 333fred** [comment] 2017-09-29 20:07
We settled on `IsDeclaration` on `ILocalReferenceExpression` and `IFieldReferenceExpression`. https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Operations/ILocalReferenceExpression.cs#L21-L25

**Comment by 333fred** [comment] 2017-09-29 20:08
Dupe of https://github.com/dotnet/roslyn/issues/18303.

**Closed by 333fred** 2017-09-29 20:07 UTC
Labels: Area-Analyzers, Bug, New Feature - IOperation

**Comment by jinujoseph** [comment] 2017-09-29 20:09
how about tuples var (x, y) = (1, 2); scenario ?

**Comment by 333fred** [comment] 2017-09-29 20:17
That was one of the tests I added.
