### ISSUE TITLE
[Test Failure] VSSDK Build error (+1 more) in prtest/win/dbg/unit64 on PR #8083

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8101] opened 2016-01-22 07:44 UTC
PR: [#8083](https://github.com/dotnet/roslyn/pull/8083) *[WIP] readonly locals and parameters* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3034/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'ImplementNotifyPropertyChanged.4f1499c0-20db-4a1d-a357-819c30d74aaa' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit64\src\Samples\CSharp\ImplementNotifyPropertyChanged\Impl\ImplementNotifyPropertyChangedCS.csproj]

**Issue 2: Compile Error**

**Comment by diryboy** [comment] 2016-01-22 07:58
+1 http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2973/

**Comment by jmarolf** [comment] 2016-01-22 09:00
dupe of https://github.com/dotnet/roslyn/issues/8077

**Closed by jmarolf** 2016-01-22 09:00 UTC
Labels: Bug
