### ISSUE TITLE
Runtime and build-time recursive cast for generic arguments

### ISSUE THREAD

**Issue by Logerfo** [dotnet/roslyn#69035] opened 2023-07-14 14:31 UTC
Consider the following piece of code:
```c#
using System.Collections.Generic;

var a = new Dictionary<int, Dictionary<int, int>>();
var b = (IDictionary<int, Dictionary<int, int>>)a; //works
var c = (IDictionary<int, IDictionary<int, int>>)a; //runtime error InvalidCastException
var d = (Dictionary<int, IDictionary<int, int>>)a; //build error CS0030
```
I wonder if `c` and `d` could both build and run if some sort of recursive cast was supported. Would that be achievable?

**Comment by CyrusNajmabadi** [comment] 2023-07-14 14:46
Closing out. This is by design as Dict is not co or contravariant on its type parameters. 

The cast you are trying to do is genuinely unsafe. Consider if you cast to `IDictionary<int, IDictionary<int, int>>>`. Note you'd be able to add a NON-Dictionary value to the original dictionary, which would blow up.

**Closed by CyrusNajmabadi** 2023-07-14 14:46 UTC
Labels: untriaged

**Comment by Logerfo** [comment] 2023-07-14 14:56
@CyrusNajmabadi I see. I understand the concept of variance and agree with your explanation, but I thought that could be possible because my solution to the problem was the following:
```c#
IDictionary<int, IDictionary<int, int>> x = a.ToDictionary(kvp => kvp.Key, kvp => (IDictionary<int, int>)kvp.Value)
```
Which creates another dictionary through the `ToDictionary` call, but casting alone probably should not allocate anything, so I understand why it is how it is.
Thank you!

**Comment by CyrusNajmabadi** [comment] 2023-07-14 16:56
You're welcome :)
