### ISSUE TITLE
Ambiguity in calling base class method.

### ISSUE THREAD

**Issue by Rezarick** [dotnet/roslyn#37685] opened 2019-08-02 23:08 UTC
**Version Used**: 
I am using VS community 2019 16.1.4...

**Steps to Reproduce**:
1) First, Write two classes one inherits from the other. Let's call them 'Class' and 'BaseClass' for example.

2) Second, Define two methods with the same name one in each class. In the 'BaseClass' the method should take a more generic parameter type than the one in 'Class'. For instance, in 'BaseClass' we define void Method(int instance), and in 'Class' we define void Method(object instance).

3) Finally, create another class that inherits from 'Class'. Now, try and call the one with the specific parameter type from the newly created class. And here we encounter the issue.The call is not possible unless the method with the more specific parameter is redefined in 'Class'.
Here is an example that reproduces the problem:

```
    public class TestClass : Class 
    {
        public void CallTest(int instance)
        {
            // Calls Class.Method(object) instead of BaseClass.Method(int)
            base.Method(instance);
        }
    }

    public class Class : BaseClass
    {
        public void Method(object instance)
        {
        }
    }

    public class BaseClass
    {
        public void Method(int instance)
        {
        }
    }

```
**Expected Behavior**:
Normally this call base.Method(instance) is supposed to invoke the most specific method. Meaning it should call BaseClass.Method(int) but it doesn't. 

**Actual Behavior**:
Instead it calls the more generic version which takes an object and there is no possible way to call the one that takes an int.

**Comment by CyrusNajmabadi** [comment] 2019-08-03 03:25
This appears to be by design.  Could you clarify why you think this is not correct behavior as per the C# language spec?

**Comment by canton7** [comment] 2019-08-04 11:02
@CyrusNajmabadi Do you have a reference, out of curiosity? I couldn't find anything in section 14.4.2 of ECMA-334.

**Comment by canton7** [comment] 2019-08-04 11:14
For reference, from Section 7.6.5.1 of the spec:

> •	The set of candidate methods is reduced to contain only methods from the most derived types: For each method C.F in the set, where C is the type in which the method F is declared, all methods declared in a base type of C are removed from the set. Furthermore, if C is a class type other than object, all methods declared in an interface type are removed from the set. (This latter rule only has affect when the method group was the result of a member lookup on a type parameter having an effective base class other than object and a non-empty effective interface set.)

To me that seems like quite a strange rule -- do you know the rationale behind it, out of curiosity?

**Comment by CyrusNajmabadi** [comment] 2019-08-04 16:13
Probably for this exact case.  A person makes a derived type and says "i want to put a method here that will handle *all* values.".  If we ignored this method and went up to the base type, we'd be skipping the derived type and would be forcing it to have to redeclare all these members.

**Comment by Rezarick** [comment] 2019-08-04 21:54
@CyrusNajmabadi In that case we can easily force the call we want by casting the parameter to an object for instance and that will call the method that takes an object. The call would be as follows base.Method((object)instance) fairly simple. But in the current situation, to my knowledge, there is no possible way to call the specific method although Intellisense clearly suggests it, unless through reflection. 
After researching the problem a bit more, I believe it has to do with the mechanism used by the compiler for overloads resolution, where the compiler searches base classes level by level and stops whenever it finds a compatible overload.

**Comment by CyrusNajmabadi** [comment] 2019-08-04 23:44
> here is no possible way to call the specific method although Intellisense clearly suggests it, unless through reflection.

Sure there is:

```c#
            ((BaseClass)this).Method(instance);
```

>  I believe it has to do with the mechanism used by the compiler for overloads resolution, where the compiler searches base classes level by level and stops whenever it finds a compatible overload.

Correct.  Very much intentional and part of how C# has worked since 1.0.  This is heavily baked into the core concepts of how classes expose methods and how that works with subclassing.

**Comment by gafter** [comment] 2019-08-20 20:59
Closing as by design.

**Closed by gafter** 2019-08-20 20:59 UTC
Labels: Area-Compilers
