### ISSUE TITLE
NuGet License mismatch?

### ISSUE THREAD

**Issue by TheAifam5** [dotnet/roslyn#28362] opened 2018-07-09 09:29 UTC
The Roslyn project uses Apache License 2.0, but in the package of "Microsoft.Net.Compilers" is still the "https://www.microsoft.com/web/webpi/eula/dotnet_library_license_non_redistributable.htm" as a license.

Which of them is valid, which of them should I use?

Regards,
Mateusz Paluszkiewicz

**Comment by Pilchie** [comment] 2018-07-09 14:04
Tagging @gafter

**Comment by svick** [comment] 2018-07-11 13:53
Based on the resolution of https://github.com/dotnet/roslyn/issues/20169, the next version of Microsoft.Net.Compilers will use the more liberal https://www.microsoft.com/net/dotnet_library_license.htm.

Though it's still not an open source license and it's not clear to me why using the Apache license for at least some Roslyn NuGet packages is not an option.

**Comment by jcouv** [comment] 2018-07-11 15:32
Resolving as dupe of #20169

**Closed by jcouv** 2018-07-11 15:32 UTC
