### ISSUE TITLE
Writing code to call a function using identifiers that don’t exist yet.

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#33667] opened 2019-02-25 22:04 UTC
Source: Scenario 1 at https://developercommunity.visualstudio.com/content/problem/465732/vs-2019-preview-3-intellisense-auto-selecting-para.html

Writing code to call a function using identifiers that don’t exist yet.

```
class Program
{
    static void Main ( string[] args )
    {
        var mySvc = new MyService(10, otherSvc, $$);
    }        
}

class MyService
{
    public MyService (int id, OtherService otherService, string name)
    {
    }
}

class OtherService
{
}
```

In this scenario I’ve just put the comma in the call to new MyService in Main. I now enter a variable name name that doesn’t exist yet. As soon as you hit space or a dot (because this is an object) then IS autocompletes to the name: parameter name. This isn’t what I wanted so I have to stop my typing, go back and correct to the variable (I haven’t defined yet) and then continue typing. In VS 2017 it doesn’t autocomplete to the parameter name. It does recognize that the parameter name is the best choice, it just doesn’t auto complete it.

**Expected by user**
`        var mySvc = new MyService(10, otherSvc, name);`
**Actual**
`        var mySvc = new MyService(10, otherSvc, name:);`
The behavior is the same with the old completion and the new completion. It seems it is caused by https://github.com/dotnet/roslyn/pull/26764

**Comment by ivanbasov** [comment] 2019-02-25 22:05
I actually do not think that the previous behavior was better than the new one. @CyrusNajmabadi , what do you think?

**Comment by CyrusNajmabadi** [comment] 2019-02-25 22:35
Sorry, i'm confused by your repro.  Can you clarify things like: I now enter a variable name name

Do you mean you're entering the characters `name`?  or something else?

**Comment by ivanbasov** [comment] 2019-02-25 22:52
Sorry, @CyrusNajmabadi ! 
Please type "na" and space in $$. The user expects "name" and this happens in VS 15.9. Currently both completions (old and new) add a colon "name:".

**Comment by CyrusNajmabadi** [comment] 2019-02-26 00:19
"Please type "na" and space in $$. The user expects "name" and this happens in VS 15.9. Currently both completions (old and new) add a colon "name:"."

if the user wanted "name" why did they write `na<space>` instead of 'name'?  Since they're typing the name of something that doesn't exist, i woudl expect them to have to write out the entire name.

**Comment by CyrusNajmabadi** [comment] 2019-02-26 00:20
Note: i believe this has been the behavior ever since we added `named param` completion.  Could you explain what behavior you woudl want, including for the customer that wants to type `na<space>` and get `name: `?

**Comment by CyrusNajmabadi** [comment] 2019-02-26 00:23
for example, i do this all the time:

```canc<space>``` 

I know that this will select and insert `cancellationToken: ` so that i can then continue from there.  If you change this behavior you will badly break my muscle memory here.

**Comment by ivanbasov** [comment] 2019-02-26 01:49
> "Please type "na" and space in $$. The user expects "name" and this happens in VS 15.9. Currently both completions (old and new) add a colon "name:"."
> 
> if the user wanted "name" why did they write `na<space>` instead of 'name'? Since they're typing the name of something that doesn't exist, i woudl expect them to have to write out the entire name.

Thank you, @CyrusNajmabadi !

1. I'm totally fine with `name:`
2. It seems that the user is used to get `name` with typing `na<space>`. This is the complain.
3. I just would like to confirm with you that adding `:` was intentional. If so, we will just resolve the issue.

**Comment by CyrusNajmabadi** [comment] 2019-02-26 02:16
>     3\. I just would like to confirm with you that adding `:` was intentional. If so, we will just resolve the issue.

I believe so.  But we should check.  IIRC, we've had this behavior since forever.  However, if we haven't we should try to preserve whatever we've been doing since like VS2010 onwards.

**Comment by ivanbasov** [comment] 2019-02-26 03:04
@CyrusNajmabadi , sorry! I'm not sure I understand you. There is a change between 15.9 and 16.0.
Here is 15.9:
![name_no_colon](https://user-images.githubusercontent.com/5455484/53384451-ce5da300-392f-11e9-8f2a-886694787d38.gif)

Here is 16.0:
![name_colon](https://user-images.githubusercontent.com/5455484/53384463-d74e7480-392f-11e9-86b3-39f30c3432a5.gif)

I typed `name<space>` in both cases. Sorry - not `na<space>` and I got different results.
I think this change is intentional and correct.
Do you agree?

**Comment by sharwell** [comment] 2019-02-27 19:03
@ivanbasov The colon should not be completed for these entries unless the commit character is `:`.

**Comment by ivanbasov** [comment] 2019-02-27 20:02
> @ivanbasov The colon should not be completed for these entries unless the commit character is `:`.

@sharwell , why? VS does not know about the variable you may going to add in the future. However, it knows that there is a parameter with the corresponding name. Why should not it suggest the whole `name:` by typing `space` or `Tab`? I would not consider it as a regression but as an improvement. Not?

**Comment by sharwell** [comment] 2019-02-27 20:58
I have been hitting this frequently while trying to work in 16.0, where it inserts a `:` but the item I wanted was the name without the `:`.

**Comment by sharwell** [comment] 2019-02-27 21:00
See #32204

**Comment by CyrusNajmabadi** [comment] 2019-02-27 21:12
Yeah sorry.  My overall position is: don't change behavior here.

**Comment by simon1749** [comment] 2019-04-03 21:39
The intellisense in vs2019 pro (16.0) inserts 'EnvironmentVariableTarget' as soon as I type 'var' and press the space bar. This is really bad, hope it will be fixed soon.

**Comment by sharwell** [comment] 2019-04-03 21:53
I still hit this all the time.

**Comment by sharwell** [comment] 2019-07-06 01:57
Design review conclusion: To avoid muscle memory regressions, async completion in 16.x should be following the same behavior that 15.9 and earlier did for this scenario.

**Comment by jinujoseph** [comment] 2019-08-12 23:23
reported at [DC](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962599)

**Closed** 2019-08-24 02:32 UTC
Labels: Area-IDE, Bug, IDE-IntelliSense, Regression
