### ISSUE TITLE
Suggestion: provide better SemanticModel/IDE experience inside broken foreach declaration

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15601] opened 2016-11-30 05:01 UTC
[In a code review it was suggested](https://github.com/dotnet/roslyn/pull/15548#discussion_r90164938) that we should bind and give good SemanticModel (and therefore IDE) experience inside an expression in this context:

`foreach (AnyExpression in e) {}`

where `AnyExpression` is some expression form not legally supported in this context.

**Comment by 333fred** [comment] 2018-03-30 17:56
Duplicate of https://github.com/dotnet/roslyn/issues/19996

**Closed by 333fred** 2018-03-30 17:56 UTC
Labels: Area-Compilers, Bug, Resolution-Duplicate
