### ISSUE TITLE
Breaking changes in conditional expression parsing (nullable reference types)

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#31313] opened 2018-11-22 04:46 UTC
**Version Used**: 

Branch master (28 Oct 2018)
Latest commit bfade8 by Sam Harwell:
Merge pull request #30815 from eladeyal-intel/patch-1

Delete 0

**Steps to Reproduce**:

Compile the following code:
```cs
class A
{
  struct S {}

  public static void Main()
  {
    object obj = 1;
    obj = obj is S?[] ? null : (object) null;
  }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMACAggWAFADe+GGsCArgMYwYDKGBAvvsRigMxsCMAbGwCwYAshACWAOwAUASlZE8JEgHtgAKzjUMK1RgC8GLgG5WytXq1nRUOgH4A2gF0MNjOPIAbdxhAZJ2jTDSrh7uxgoYzHiMQA=

**Expected Behavior**:

The code is compiled without errors just as it does now in VS2017

**Actual Behavior**:

```
    error CS1002: ; expected
    error CS1002: ; expected
    error CS1513: } expected
    error CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
```

**Comment by AArnott** [comment] 2018-12-21 00:09
This may be a dupe of https://developercommunity.visualstudio.com/content/problem/378571/nullable-reference-types-compiler-error-produced-w.html

**Comment by Neme12** [comment] 2018-12-21 18:12
possible dupe of #31666? tagging @cston

**Comment by Neme12** [comment] 2018-12-21 23:04
Can this be closed then?

**Comment by AArnott** [comment] 2018-12-21 23:06
That bug was supposedly fixed on Nov 13. But I have a very recent Dev16 IntPreview build and am still seeing the error. So I think we should keep it open till we verify that it's actually fixed.

**Comment by AArnott** [comment] 2018-12-21 23:07
I don't see this in VS2019 any more, BTW. I only see it when I run `dotnet build` from the command line.

**Comment by Neme12** [comment] 2018-12-21 23:07
@AArnott 
> But I have a very recent Dev16 IntPreview

Can you share so that I can verify this? :smile:

**Comment by AArnott** [comment] 2018-12-21 23:08
![image](https://user-images.githubusercontent.com/3548/50367049-3a87e900-0532-11e9-97a5-c97e3a331eeb.png)

**Comment by Neme12** [comment] 2018-12-21 23:08
I meant the actual VS build. Sorry, not a good joke...

**Comment by AArnott** [comment] 2018-12-21 23:10
You mean you want me to allow you to install it?

BTW, I just tried repro'ing using `dotnet build` and as of today it... stopped reproing. 🦆

**Comment by Neme12** [comment] 2018-12-21 23:11
Yes, that's what I meant

**Comment by AArnott** [comment] 2018-12-21 23:13
ok, got it. sorry I'm slow today. 😆

**Closed** 2019-01-02 20:41 UTC
Labels: Area-IDE, Bug, help wanted
