### ISSUE TITLE
Namespace references are being added unnecessarily

### ISSUE THREAD

**Issue by ortund** [dotnet/roslyn#20643] opened 2017-07-05 15:07 UTC
**Version Used**: 14.0.25421.03

**Steps to Reproduce**: Problem is intermittent and therefore cannot be intentionally reproduced.

**Expected Behavior**: No addition of namespaces that are redundant when a "using" has been included at the top of the page.

**Actual Behavior**:

The problem most often happens when I'm writing a using in my code:

`using Ortund.Models;

protected void btnFoo_Click(object sender, EventArgs e)
{
        using (OrtundDbContext Context = new OrtundDbContext())
        {
        }
}` 
This block represents code that I _want_ but when I hit Tab to finish the using block and insert the `new OrtundDbContext()` part, Visual Studio often times will rewrite it as `new Models.OrtundDbContext()` which will give me an improvement suggestion indicating that the code can be simplified by removing the Models. part that I didn't even try to add in the first place.

**Comment by Pilchie** [comment] 2017-07-05 19:20
This is a duplicate of https://github.com/dotnet/roslyn/issues/12552. It's fixed for VS 2017.

**Closed by Pilchie** 2017-07-05 19:20 UTC
Labels: Area-IDE, Bug

**Comment by ortund** [comment] 2017-07-06 06:42
Fixed for 2017 is great, but **I'm not using VS 2017**. This is literally less than uselessly unhelpful
