### ISSUE TITLE
Error persists after restore of NuGet packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#11190] opened 2016-05-09 21:08 UTC
**Version Used**: 
VS Update 2

**Steps to Reproduce**:
1. Open SLN from here: 
   [designTimeRefreshLag.zip](https://github.com/dotnet/roslyn/files/255905/designTimeRefreshLag.zip)
2. Build once, observe it builds successfully.
3. In solution explorer, click show all files.
4. Delete the project.lock.json.
5. Open Program.cs and observe compile errors (expected).
6. Build the solution, nuget restore will run to regenerate the project.lock.json and build completes successfully.
7. Errors still appear in program.cs. (could be expected).
8. Click refresh in solution explorer.
9. Click program.cs.

**Expected Behavior**:
All errors in program.cs go away.

**Actual Behavior**:
The following error persists until I unload and reload the project:

| Severity | Code | Description | Project | File | Line | Suppression State |
| --- | --- | --- | --- | --- | --- | --- |
| Error | CS7069 | Reference to type 'ISerializationSurrogateProvider' claims it is defined in 'System.Runtime.Serialization.Primitives', but it could not be found | desktopApp | c:\Users\ericstj\Documents\Visual Studio 2015\Projects\testBindingRedirects\desktopApp\Program.cs | 17 | Active |

/cc @Pilchie

**Comment by jasonmalinowski** [comment] 2016-05-20 21:01
This doesn't appear to be a complete dupe of #11048. We're getting both of these as references to the IDE:

    .nuget\packages\System.Runtime.Serialization.Primitives\4.1.1-rc2-24027\ref\net46\System.Runtime.Serialization.Primitives.dll
    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Serialization.Primitives.dll

Before the restore happens, we already have the 4.6 Façade added, and once the NuGet one is coming in we aren't removing the other one.

**Comment by jasonmalinowski** [comment] 2018-01-19 22:51
Closing: at this point we've deprecated project.json...

**Closed by jasonmalinowski** 2018-01-19 22:51 UTC
Labels: Area-IDE, Bug
