### ISSUE TITLE
C# and VB operation trees are different for logically the same code

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66511] opened 2023-01-21 11:09 UTC
**Version Used**:
MS.CA.CS/VB 4.5.0-2.final

**Steps to Reproduce**:
```cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.VisualBasic;

using CSharpSyntax = Microsoft.CodeAnalysis.CSharp.Syntax;
using VBSyntax = Microsoft.CodeAnalysis.VisualBasic.Syntax;

var csharpSyntaxTree = CSharpSyntaxTree.ParseText("""
    class C
    {
        void M(string x)
        {
            _ = x?.Test();
        }
    }

    static class Test
    {
        public static string Test(this string s)
        {
            return s;
        }
    }
    """);

var vbSyntaxTree = VisualBasicSyntaxTree.ParseText("""
    Imports System.Runtime.CompilerServices

    Class C
        Sub M(x As String)
            Dim result = x?.Test()
        End Sub
    End Class

    Module Test
        <Extension()> 
        Public Function Test(s As String) As String
            Return s
        End Function
    End Module
    """);

var csharpRoot = csharpSyntaxTree.GetRoot();
var vbRoot = vbSyntaxTree.GetRoot();

var csInvocation = csharpRoot.DescendantNodes().OfType<CSharpSyntax.InvocationExpressionSyntax>().First();
var vbInvocation = vbRoot.DescendantNodes().OfType<VBSyntax.InvocationExpressionSyntax>().First();

var csCompilation = CSharpCompilation.Create("TestCS", new[] { csharpSyntaxTree }, new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) } );
var vbCompilation = VisualBasicCompilation.Create("TestVB", new[] { vbSyntaxTree }, new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) } );

var csSemanticModel = csCompilation.GetSemanticModel(csharpSyntaxTree);
var vbSemanticModel = vbCompilation.GetSemanticModel(vbSyntaxTree);

var csOperation = (IInvocationOperation)csSemanticModel.GetOperation(csInvocation)!;
var vbOperation = (IInvocationOperation)vbSemanticModel.GetOperation(vbInvocation)!;

Console.WriteLine($"C# operation instance: {(csOperation.Instance is null ? "null" : "not null")}");
Console.WriteLine($"VB operation instance: {(vbOperation.Instance is null ? "null" : "not null")}");
```

**Expected Behavior**:
Either in both cases `null` or `not null`

**Actual Behavior**:
C# - `null`
VB - `not null`

**Additional Info:**
Considering that both examples do the same thing (access an extension method via conditional access operator) I expect both operation trees to be the same. But having such inconsistencies leads to very dirty code in a shared layer when implementing an analyzer/codefix for both languages. Examples of real-world pain: https://github.com/dotnet/roslyn-analyzers/pull/6366#discussion_r1050771559, https://github.com/dotnet/roslyn-analyzers/pull/6366#discussion_r1050773960

**Comment by 333fred** [comment] 2023-02-14 18:05
Duplicate of https://github.com/dotnet/roslyn/issues/56644.

**Closed** 2023-02-14 18:05 UTC
Labels: Bug, Area-Compilers
