### ISSUE TITLE
Rename UI: highlighting span doesn't shrink when the new name is shorter

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#65299] opened 2022-11-09 12:53 UTC
**Version Used**: VS 2022 17.4.0

**Steps to Reproduce**:
Rename the variable to something shorter.
```csharp
int M()
{
    var myTestVariable = 3;
    return myTestVariable;
}
```

**Expected Behavior**: The blue highlighting span gets smaller during the edit.

**Actual Behavior**: The span appears to always have the same length and can highlight other parts of the code.

![grafik](https://user-images.githubusercontent.com/823398/200835006-4ba0ed40-6d35-40de-87e6-7e3b50e69a74.png)

**Comment by ryzngard** [comment] 2023-05-15 20:37
Dupe of https://github.com/dotnet/roslyn/issues/63933 , and has been fixed :)

**Closed by ryzngard** 2023-05-15 20:37 UTC
Labels: Bug, Area-IDE
