### ISSUE TITLE
[Bug]   IDE0058  not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74073] opened 2024-06-20 13:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug---IDE0058--not-work-/10685425)._

---
Not working in a Top-level Program:
![B8bd0a115fd144d418798f7b982c49e49638543123115519396_20240618-205830-image](https://github.com/dotnet/roslyn/assets/1408396/f5462bac-a603-4f41-b16b-732eb27d6e29)

Not working with conditional compilation symbols:
![Bed6518844d94401bb49f3945aa29f951638543123673373602_20240618-205926-image](https://github.com/dotnet/roslyn/assets/1408396/1bf64ee8-4104-4295-91f2-c1696ae879b4)

---
#### Feedback Bot on 6/18/2024, 09:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2024-11-26 01:58
Closing out as by design.  Within pp directives we often disable features due to the high cost and low value we get back investing there.

**Closed by CyrusNajmabadi** 2024-11-26 01:58 UTC
Labels: Area-IDE
