### ISSUE TITLE
NFW: InvalidOperationException: The project already references the target project.

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#43632] opened 2020-04-24 06:19 UTC
This is the #4 highest non-fatal watson for the project-system, with 13% of all hits. This is a regression in 16.6-pre3.

**Version Used**: 
16.6-pre3

**Steps to Reproduce**:

```
InvalidOperationException: The project already references the target project.
Microsoft.CodeAnalysis.Solution.AddProjectReferences(ProjectId,IEnumerable`1)
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProject.<>c__DisplayClass85_0.<OnBatchScopeDisposed>b__0(Solution)
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyBatchChangeToWorkspace(Func`2)
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProject.OnBatchScopeDisposed()
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProject.BatchScope.Dispose()
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.EndBatch()
Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.<ApplyProjectChangesUnderLockAsync>d__19.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter.GetResult()
Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<ExecuteAsync>d__3.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.<ExecuteUnderLockCoreAsync>d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception)
Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
GuardMethodClass.GuardMethod(Func`1,Func`2,Func`2)

```

**Comment by jasonmalinowski** [comment] 2020-04-24 18:16
Is this a dupe of #39032?

**Comment by davkean** [comment] 2020-04-25 01:20
Yes looks like it. We've started reporting it now, hence why showing up.

**Comment by davkean** [comment] 2020-04-25 01:34
I think  the EndBatch call was hiding this one, hence why its new for 16.3 pre3.

**Comment by davkean** [comment] 2020-04-29 07:31
There might be a dump in https://github.com/dotnet/project-system/issues/6141.

**Comment by davkean** [comment] 2020-04-29 07:40
You'll need to pull uncollected exceptions off the stack.

**Closed** 2020-05-01 02:09 UTC
Labels: Area-IDE, Bug
