### ISSUE TITLE
Adds the description of the exceptions documentation in the QuickInfo popup.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59000] opened 2022-01-21 17:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adds-the-description-of-the-exceptions-d/1635657)._

---
At the moment only the exception type is shown in QuickInfo.

Or an option to display it in the `Options > C# > Advanced > Editor` menu like the remarks tag.

For more detail : https://stackoverflow.com/questions/48637422/how-can-i-make-visual-studio-show-the-entire-documentation-for-exceptions

---
#### Feedback Bot on 1/12/2022, 11:23 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by sharwell** [comment] 2022-01-21 18:10
Duplicate of #1515

**Closed by sharwell** 2022-01-21 18:10 UTC
Labels: Area-Interactive, untriaged
