### ISSUE TITLE
AddUsing: Internal extension methods not recommended (IVT present)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#43623] opened 2020-04-23 22:10 UTC
**Version Used**: 
3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6

1. Have two projects, A and B, B references A
2. A has IVT to B
3. A declares an extension method
4. Attempt using that extension method in B, but without the using namespace of the declaring class

**Expected:**
LightBulb on the extension method call site should offer to add the missing using, so that the extension method can light up

**Actual:** 
Add using is not recommended, have to add the using manually for extension method to bind

**Comment by CyrusNajmabadi** [comment] 2020-04-23 22:15
@genlu

**Comment by genlu** [comment] 2020-04-23 22:29
Is it an assembly reference or project reference? IIRC we ignore internal extention methods from assembly reference even with IVT

**Comment by KirillOsenkov** [comment] 2020-04-23 23:54
It's an assembly reference

**Comment by genlu** [comment] 2020-04-24 18:46
Not a bug, change to feature request.

Current behavior is by design for perf reasons, the presumption is for most people they have source access to the assemblies containing IVT information, adding internal symbols from metadata to the index will increase its size and make things slower.

**Comment by sharwell** [comment] 2020-04-24 18:54
@genlu We have `GivesAccessTo` which can be used to filter the metadata references.

**Comment by CyrusNajmabadi** [comment] 2024-10-21 20:02
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-21 20:02 UTC
Labels: Area-IDE, Feature Request
