### ISSUE TITLE
Show <exception> description in XML Document Comment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40800] opened 2020-01-08 03:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/870945/use-of-c-xml-document-comment-tagc-xml-document-co.html)._

In VisualStudio, I think the ability to display annotations of variables using XML Document is very good, but i think that it is particularly useful in describing whether it is a good exception to ignore if you can display it because there is a column that describes "description" in the <exception> tag, so I want the ability to display not only the exception that occurs, but also the description of the exception that occurs.

**Comment by sharwell** [comment] 2020-01-08 14:02
Duplicate of #1515

**Closed by sharwell** 2020-01-08 14:02 UTC
