### ISSUE TITLE
"Enable solution analysis" doesn't show up in Options search results

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19856] opened 2017-05-30 02:13 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/26565748/677807be-4531-11e7-9747-c8bd0327592c.png)

**Comment by Pilchie** [comment] 2017-05-30 16:30
Dupe of https://github.com/dotnet/roslyn/issues/16014

**Closed by Pilchie** 2017-05-30 16:30 UTC
