### ISSUE TITLE
Compiler shouldn't perform expressions optimizations

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#29396] opened 2018-08-20 11:46 UTC
Taking into account that expressions could be used in various scenarios, e.g. converted to sql, it could lead to unwanted side-effects. 

Example below shows how char constant below is converted to integer constant which leads by integer sql literal generation by underlying IQueryProvider instead of string literal. See https://github.com/linq2db/linq2db/issues/1287

**Version Used**: Microsoft (R) Visual C# Compiler version 2.9.0.63208 (958f2354)

**Steps to Reproduce**:

```cs
public static char Force(char chr) => chr;

        static void Main(string[] args)
        {
            char property = 'x';
            char? propertyNullable = null;

            Expression<Func<bool>> test1 = () => propertyNullable == '1';
            Expression<Func<bool>> test2 = () => propertyNullable == (char)'1';
            Expression<Func<bool>> test3 = () => propertyNullable == (char?)'1';
            Expression<Func<bool>> test4 = () => propertyNullable == Force('1');

            Expression<Func<bool>> test5 = () => property == '1';
            Expression<Func<bool>> test6 = () => property == (char)'1';
            Expression<Func<bool>> test7 = () => property == Force('1');

            Expression<Func<bool>> test8 = () => '1' == '2';
        }
```

**Expected Behavior**:
expressions contain char constant as constant of char type

**Actual Behavior**:
expressions contain integer constant. Last expression (test8) contains false constant at all.

**Comment by jaredpar** [comment] 2018-08-20 15:08
Is this a behavior change you are noticing or behavior that has always been there for expression trees?

**Comment by MaceWindu** [comment] 2018-08-20 15:14
Well, looks like it was here for some time already, as I found out we already handle this pattern in linq2db for 
`property(char) == constant(char)`, so I just added additional handling for `property(char?) == constant(char)`.

I think we can live with it, but things like that a bit surprising to find.

It would help a lot if optimizations like that to expressions are documented somewhere.

**Comment by jaredpar** [comment] 2018-08-20 15:27
> Well, looks like it was here for some time already

Thanks for confirming. As such I'm closing this issue as "By Design". Consumers of expression trees tend to be very sensitive to the shape of the trees and even subtle changes can have big impact on code bases. At this point we only change them when there is a significant deviation from the native compiler behavior (which there doesn't appear to be here). 

> It would help a lot if optimizations like that to expressions are documented somewhere.

I agree. Unfortunately expression trees in general have very little documentation, including around optimizations. It is on the list of things we would like to improve, particularly if we revisit them for statements.

**Closed by jaredpar** 2018-08-20 15:27 UTC
Labels: Area-Compilers, Need More Info

**Comment by gafter** [comment] 2018-08-20 16:10
This isn't an optimization. An expression like `'1' == '2'` is required by the language specification to be treated as the boolean constant false.  See https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#constant-expressions
