### ISSUE TITLE
"IDE0017 object initialization can be simplified" leads to erroneous "CS0165 Use of unassigned local variable"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#26317] opened 2018-04-22 02:04 UTC
If you initialize an object with a value, and then use the object initializer to set more properties, where one of those properties in some way is or encapsulates the value being initialized, the C# compiler reports an erroneous CS0165.

var state = new SomeObject()
{
    SomeProperty = new SomeOtherObject(state);
};

The aboves statement is actually just syntactic sugar for the following:

var state = new SomeObject();
state.SomeProperty = new SomeOtherObject(state);

Which is valid because at that point of assigning SomeProperty, state clearly has been initialized to something.

Interestingly, the refactoring tools recognize this and appropriate suggest the object initializer syntax, but as soon as you use it, the compiler complains.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/224646/ide0017-object-initialization-can-be-simplified-le.html
VSTS ticketId: 591397_
_These are the original issue comments:_

Andrew Stanton on 3/30/2018, 00:08 PM (22 days ago):  @Manish Jayaswal [MSFT] - I'm not sure what the value is of any further effort. There is no API or other scriptable invocation that is supported, and if there was, Intellitest requires only 32bit. I havent been able to purchase a non 64 bit windows OS  since Server 2008. There is the availability to run Intellitest for an entire namespace, but its still not near the level of completeness one would have expected after this many years. Its still just crippled.
Anthony Langlois on 3/30/2018, 02:46 PM (22 days ago): <p>This looks like it is a comment on the wrong thread...or is there something I'm missing?</p>

Andrew Stanton on 3/31/2018, 01:01 PM (21 days ago): No, I mistyped the comment ID. It was supposed to be attached to parent 224616. but i mistyped 224646 (this issue) when posting.  Sorry about that. The grand poobah of feedback suspended my account for pointing out some poor issue handling (rather than address the handling) so I'm left respond to questions the hard way. 
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2018-04-22 02:08
I don't repro this behavior on the lastest VS bits.  The usage of "state" in "new SomeOtherObject(state);" blocks the refactoring from being offered.  If you remove the usage, then it is offered.

**Comment by Youssef1313** [comment] 2021-03-08 14:43
> the C# compiler reports an erroneous CS0165.

@CyrusNajmabadi If I understand this correctly, the complaint here appears to be about compiler behavior, which is possibly by design.

**Comment by CyrusNajmabadi** [comment] 2023-02-09 21:24
Closing as this doesn't repro, and the compiler error seems entirely correct to me.

**Closed by CyrusNajmabadi** 2023-02-09 21:24 UTC
Labels: Area-IDE, Resolution-Not Reproducible, Developer Community, Feature - IDE0017
