### ISSUE TITLE
IDE C# formatter indentation issue after a comment

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#9441] opened 2016-03-03 06:09 UTC
Say you have this
```
using System;
<-- no indentation on ENTER
/* blah */ or // blah
<-- no indentation on ENTER
    <-- indentation on ENTER
```

VS2015 Update 1

**Comment by DustinCampbell** [comment] 2016-03-03 16:17
This is a duplicate of #3321.

**Closed by DustinCampbell** 2016-03-03 16:17 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate

**Comment by leppie** [comment] 2016-03-03 16:36
Sorry :)
