### ISSUE TITLE
Query code for occurance of X (Roslyn)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36210] opened 2019-06-06 17:42 UTC
VSF_TYPE_MARKDOWNIn our company (like so many others) we have issues with DateTime.. 

What i'd like to do, is to find EVERY occurance where DateTime is converted to or from string. 

eg: 
- Every Implicit Cast
- Every Explicit Cast
- Every Parse

I imagine that Roslyn could locate all of these occurances for me ?

I'm not sure how the query language or function should be made, but it would be of great help.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/580464/query-code-for-occurance-of-x-roslyn.html
VSTS ticketId: 897603_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/24/2019, 03:43 AM (13 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ryzngard** [comment] 2019-10-07 22:50
Design Review: Customer ask is unclear. We believe that addition of implicit conversion operator to find all references would be a valid addition to help solve this problem. There may already be tools to help with this ask.

**Comment by sharwell** [comment] 2019-10-17 23:26
Duplicate of #39375

**Closed by sharwell** 2019-10-17 23:26 UTC
Labels: Area-IDE, Feature Request, IDE-Navigation, Need Design Review
