### ISSUE TITLE
Implicit Conversion Regression in VS v16.8

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#49627] opened 2020-11-26 00:13 UTC
**Version Used**: 

Visual Studio 2019 v16.8
.NET 5.0.100

**Steps to Reproduce**:

1. Create a new project with `dotnet new classlib`
2. Lock the C# version to 7.3 with `<LangVersion>7.3</LangVersion>`
3. Attempt to compile the following code:

```csharp
public class Repro
{
    Repro JobHeader => throw null;

    ZShort FH_VoteUpDownAmount => throw null;
    bool IsWorkflow => throw null;

    public ZDecimal DirectNudge => (IsWorkflow ? JobHeader.FH_VoteUpDownAmount : 0) + FH_VoteUpDownAmount;
}

#pragma warning disable IDE0060 // Remove unused parameter

public struct ZDecimal
{
    public ZDecimal(decimal value) { }

    public static implicit operator ZDecimal(int value) => throw null;
}

public struct ZShort
{
    public ZShort(short value) { }

    public static implicit operator ZShort(short value) => throw null;
    public static implicit operator int(ZShort wrapper) => throw null;
    public static ZShort operator +(ZShort x, ZShort y) => throw null;
}
```

**Expected Behavior**:

> Build succeeded.
    0 Warning(s)
    0 Error(s)

**Actual Behavior**:

> C:\Temp\roslynrepro\Class1.cs(8,37): error CS8370: Feature 'target-typed conditional expression' is not available in C# 7.3. Please use language version 9.0 or greater. [C:\Temp\roslynrepro\roslynrepro.csproj]
C:\Temp\roslynrepro\Class1.cs(8,36): error CS0029: Cannot implicitly convert type 'ZShort' to 'ZDecimal' [C:\Temp\roslynrepro\roslynrepro.csproj]
    0 Warning(s)
    2 Error(s)

**Notes**:

This code compiles fine with .NET SDK 3.1.107 and prior versions of Visual Studio.

**Comment by jaredpar** [comment] 2020-12-01 13:27
Thanks for filing this. Looks like a dupe of #49598.

**Closed by jaredpar** 2020-12-01 13:27 UTC
Labels: Area-Compilers, untriaged
