### ISSUE TITLE
EditorConfig setting for csharp_new_line_before_open_brace is not saved correctly in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57937] opened 2021-11-23 01:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EditorConfig-setting-for-csharp_new_line/1589482)._

---
[severity:It's more difficult to complete my work]
When using the default editor layout in Visual Studio 2022 for a .editorconfig file, when making changes to the csharp_new_line_before_open_brace entry, regardless of what is selected, the setting value saved to the .editorconfig is always "all".

If you use the default editor in Visual Studio, after you make changes to the csharp_new_line_before_open_brace option, the file is not marked as dirty to show changes are not saved.  If you close the editor and re-launch it, any changes made to those settings are gone.

If you edit the .editorconfig file manually using any text editor in Visual Studio, you can manually change it to none or all and it works.  The code formatting for braces is applied correctly.  I don't know what other values are permissible for csharp_new_line_before_open_brace, so that's why I use the default editor in Visual Studio and simply select/unselect the options from the list provided.

I was expecting Visual Studio to write & save the correct value for the csharp_new_line_before_open_brace setting based on the selections made from the list provided in the default editor.

Jason

---
#### Feedback Bot on 11/18/2021, 07:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/19/2021, 09:42 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-11-23 05:04
Possibly it's the same as the 7th point in https://github.com/dotnet/roslyn/issues/53171.

**Comment by jmarolf** [comment] 2022-03-18 21:55
duplicate of https://github.com/dotnet/roslyn/issues/54556

**Closed by jmarolf** 2022-03-18 21:55 UTC
Labels: help wanted, Area-IDE, Concept-Continuous Improvement, Developer Community
