### ISSUE TITLE
Enum type in autocomplete list if member of the same name exists

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#13269] opened 2016-08-19 14:12 UTC
**Version Used**: 2.0.0.60808 (I suspect this is might be a regression)

**Steps to Reproduce**:
```C#
class Program
{
    static ConsoleKey ConsoleKey { get; }

    static void Main(string[] args)
    {
        ConsoleKey key = ConsoleKey.|
    }
}
```
**Expected Behavior**:
Only enum values in the list.

**Actual Behavior**:
![untitled](https://cloud.githubusercontent.com/assets/10546952/17812534/5a435b6c-661f-11e6-952d-50a98315d8ab.png)
I can't think of a situation where this would be a valid suggestion.

Might be related to #5418.

**Comment by gafter** [comment] 2016-08-19 17:05
It seems that `ConsoleKey.AnyInstanceMember` could be the start of an expression whose final value is of the right type. Therefore I think the behavior is correct.

**Comment by miloush** [comment] 2016-08-19 17:23
Sorry I do not get it, could please give me an example in which you would use this suggestion?

**Comment by Pilchie** [comment] 2016-08-19 17:46
This is a dupe of https://github.com/dotnet/roslyn/issues/12733, which is already fixed.

**Closed** 2016-08-19 17:46 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
