### ISSUE TITLE
C# 8 Intellisense "Introduce 'using' statement" should use **simple** using statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36882] opened 2019-06-28 22:20 UTC
VSF_TYPE_MARKDOWNWhen we get the warning &quot;Disposable object created by '' is never disposed&quot;, C# 8 intellisense should us the **simple** using statement ( e.g. using var s = new MemoryStream(); ) instead of the using block statement.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/619119/c-8-intellisense-introduce-using-statement-should.html
VSTS ticketId: 936507_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/25/2019, 01:31 AM (3 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by sharwell** [comment] 2019-07-02 18:20
This refactoring should use simple using statements if and only if the scope for the inserted block ends at the end of the enclosing block. In other words, it should use the simple using statement only when the semantics of the simple using statement are the same as the semantics for the block this refactoring inserts today. We have a refactoring to assist in converting full using statements to the simple form; the analysis from that refactoring could be reused for this feature.

**Comment by jnm2** [comment] 2019-07-16 01:00
In C# spec lingo, the one we've always had is a 'using statement' and the new thing is a 'using declaration.'

**Comment by sharwell** [comment] 2020-03-30 18:50
Duplicate of #33699

**Closed by sharwell** 2020-03-30 18:50 UTC
Labels: Area-IDE, Developer Community, Feature Request, help wanted
