### ISSUE TITLE
Mono Linux failure mono_class_from_mono_type

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6348] opened 2015-10-26 23:50 UTC
*See http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/552/ for more details.*

Here's the PR: https://github.com/dotnet/roslyn/pull/6310

**Issue 1: mono Core Dumped**
mono crashed while running $MONO_ARGS $xunit_runner Binaries/$BUILD_CONFIGURATION/$i.dll -xml Binaries/$BUILD_CONFIGURATION/xUnitResults/$i.dll.xml -noshadow

```
10:57:57 Native stacktrace:
10:57:57 
10:57:57 mono_class_from_mono_type: implement me 0x9d
10:57:57 
10:57:57 * Assertion: should not be reached at class.c:6523
10:57:57 
10:57:57 
./cibuild.sh: line 234: 17794 Aborted                 (core dumped) mono $MONO_ARGS $xunit_runner Binaries/$BUILD_CONFIGURATION/$i.dll -xml Binaries/$BUILD_CONFIGURATION/xUnitResults/$i.dll.xml -noshadow
```

/cc: @davkean

**Comment by dpoeschl** [comment] 2015-10-27 16:27
FYI: Rerunning the test made it pass.

**Comment by davkean** [comment] 2015-12-11 17:32
Not a lot we can do with this - other than live with it.

**Comment by jaredpar** [comment] 2015-12-11 17:51
Eventually #7139 will fix this error for us. That should be completed in the update 2 timeframe.

**Comment by davkean** [comment] 2016-02-26 06:06
Dupe of https://github.com/dotnet/roslyn/issues/6407

**Closed by davkean** 2016-02-26 06:06 UTC
Labels: Area-Infrastructure, Contributor Pain, Flaky, Flaky-ExceptionGranted
