### ISSUE TITLE
Excluding a file from the Roslyn analyzers

### ISSUE THREAD

**Issue by BryanKelly** [dotnet/roslyn#3940] opened 2015-07-14 14:02 UTC
It would be nice if there was a built-in way to exclude auto-generated files from DiagnosticAnalyzer's.

**Comment by bkoelman** [comment] 2015-07-14 15:26
Related to #1751 and https://github.com/dotnet/roslyn/issues/2369#issuecomment-98418064.

**Comment by srivatsn** [comment] 2015-07-30 14:59
This seems to be a dupe of #3705

**Closed by srivatsn** 2015-07-30 14:59 UTC
Labels: Area-Analyzers, Feature Request
