### ISSUE TITLE
Method groups not inferred based on receiver type (nullable walker)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#33637] opened 2019-02-24 10:01 UTC
In `NullableWalker.VisitMethodGroup`, we recompute the type of the group's receiver and then drop it on the floor.  When the method group is an argument to a generic, we will need the recomputed method (or group of methods) for proper type inference.

Here is a test that demonstrates the issue:

``` c#
        [Fact]
        public void MethodGroupReinferredAfterReceiver()
        {
            var source =
@"public class C
{
    G<T> CreateG<T>(T t) => new G<T>();
    void Main(string? s1, string? s2)
    {
        Run(CreateG(s1).M, s2)/*T:(string?, string?)!*/;
        if (s1 == null) return;
        Run(CreateG(s1).M, s2)/*T:(string!, string?)!*/;
        if (s2 == null) return;
        Run(CreateG(s1).M, s2)/*T:(string!, string!)!*/;
    }
    (T, U) Run<T, U>(MyDelegate<T, U> del, U u) => del(u);
}
public class G<T>
{
    public T t = default(T)!;
    public (T, U) M<U>(U u) => (t, u)!;
}
public delegate (T, U) MyDelegate<T, U>(U u);
";
            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
            comp.VerifyDiagnostics();
            comp.VerifyTypes();
        }
```

The failure is

``` none
Message: void C.Main(System.String? s1, System.String? s2)

Expected:
(string?, string?)!,
(string!, string?)!,
(string!, string!)!
Actual:
(string, string?),
(string, string?),
(string, string!)
Differences:
++> (string, string?),
++> (string, string?),
++> (string, string!),
--> (string?, string?)!,
--> (string!, string?)!,
--> (string!, string!)!

Expected: True
Actual:   False
```

**Comment by jcouv** [comment] 2019-02-25 06:23
Possible dupe of https://github.com/dotnet/roslyn/issues/32697 ?

**Comment by gafter** [comment] 2019-02-26 05:02
I think that one is about the method group conversion.

**Closed** 2019-05-14 17:50 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
