### ISSUE TITLE
Suggestion: void as a first-class citizen

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#234] opened 2015-02-04 15:57 UTC
I don't know if this is possible, but I find that it would often be useful to be allowed to use `void` as a normal type (which I think is commonly called `unit` in functional languages).

This means, for example, that delegating methods can look the same whether they return void or not (note that M1 and M2 have syntactically identical definitions):

```
class C {
    C _wrapped;

    public void M1(int a) {
        return _wrapped.M1(a);
    }

    public int M2(int a) {
        return _wrapped.M2(a);
    }

    public void M3(int a) {
        var result = _wrapped.M3(a);
        DoSomethingElse();
        return result;
    }
}
```

Especially when doing code generation, this becomes an issue at times.

Bonus points if it would also be possible to treat an `Action<T>` as equivalent to `Func<T, void>`.

**Comment by sharwell** [comment] 2015-02-04 17:54
This is not a duplicate of #166, but that issue does contain quite a bit of discussion about this particular issue.

**Comment by BrannonKing** [comment] 2015-02-04 21:54
There has been a few occasions where I wanted to return a void method from inside a void method. It would make for more consistent code to be able to return void.

**Comment by ryanbnl** [comment] 2015-02-12 21:07
What is the relation between ```void``` and ```null```? F# has ```null``` for interop. There must have been a reason why it wasn't replaced with ```unit```....

**Comment by yufeih** [comment] 2015-03-11 14:54
Then Task<void> will also be equivalent to Task

**Comment by ibrahimbensalah** [comment] 2015-11-13 11:54
I really would love to see this feature in future version of C#. In my case i have a lot of utility 'duplicated' method overloads, one for Action<> and other for Func<,>.
In some case, type inference also breaks because compiler is not able to choose the right overload, altho it's probably an issue of the compiler itself.
anyhow, it would be much cleaner if Action<T> is just an instance of Func<T, Void> where void is first class refugee ;)

**Comment by gafter** [comment] 2017-03-20 20:21
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Closed by gafter** 2017-03-20 20:21 UTC
Labels: 0 - Backlog, Area-Language Design, Feature Request, Language-C#
