### ISSUE TITLE
System.NullReferenceException at SyntaxNode.get_EndPosition via CSharpSemanticModel.GetSymbolInfoCore

### ISSUE THREAD

**Issue by suprak** [dotnet/roslyn#11009] opened 2016-05-02 04:04 UTC
**Version Used**:
1.2

**Steps to Reproduce**:
Unknown (caught in the wild)

**Expected Behavior**:

Exception is not thrown.

**Actual Behavior**:

```
System.NullReferenceException:
   at Microsoft.CodeAnalysis.SyntaxNode.get_EndPosition (Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.SyntaxNode.GetChildPosition (Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Syntax.AccessorDeclarationSyntax.get_Keyword (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertyAccessorSymbol.CreateAccessorSymbol (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbol.CreateAccessorSymbol (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbol..ctor (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbol.Create (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.AddNonTypeMembers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.AddDeclaredNontypeMembers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.BuildMembersAndInitializers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembersAndInitializers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.MakeAllMembers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembersByNameSlow (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetCandidateMembers (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersWithoutInheritance (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInClass (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInType (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersWithFallback (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccessWithBoundLeft (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccess (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel+IncrementalBinder.BindStatement (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore (Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by jaredpar** [comment] 2016-05-09 17:40
Thanks for finding this issue.  We'll take a look at this.

**Comment by TyOverby** [comment] 2016-10-19 21:17
@suprak This is a tough one, it looks like it is impossible for the method in question (`Microsoft.CodeAnalysis.SyntaxNode.get_EndPosition`) to dereference null.  Would it be possible to get a dump exhibiting this bug?

Also, another recent "impossible" bug was found out to be caused by a profiler injecting code into the running process.  You wouldn't happen to be running a profiler would you?

**Comment by suprak** [comment] 2016-10-19 21:33
Crash was from a customer environment so I don't have a dump and couldn't for sure say if a profiler was running.
However it does seem plausible.

**Comment by jaredpar** [comment] 2016-11-16 19:00
Going to close this issue out for now on the assumption that it was related to a profiler.  If you find any info contrary to that please let us know and we'll look into it.

**Closed by jaredpar** 2016-11-16 19:00 UTC
Labels: Area-Compilers, Blocked, Bug, Concept-API
