### ISSUE TITLE
Implement Interface: control generated property style

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#13932] opened 2016-09-20 19:26 UTC
Ported from DevDiv 220644

---

 Problem Description 

---

 Description: It's not really a bug but an improvement could be made. 

 In previous versions of Visual Studio it was possible to change the generation of PropertyStubs during "Implement Interface" actions (See also https://connect.microsoft.com/VisualStudio/feedback/details/1857694/visual-studio-2015-implement-interface-snippet-not-working) 

 I don't like the generation of properties like this: 
 public string Name 
 { 
 get 
 { 
 throw new NotImplementedException(); 
 } 
 set 
 { 
 throw new NotImplementedException(); 
 } 

 why it is not possible to customize it (like in previous versions by modifying snippets) to get something like: 
 public string Name { get; set; } 
 } 

 Snippets in directory are not used anymore for refactoring 
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC#\Snippets\1031\Refactoring 

 Repro Steps:Define some Interface, write class that should implement that interface, and execute "Implement interface" from context menu. 

 public interface ITest 
{ 
 string Name { get;set;} 
 } 

 public class Test : ITest (right click - implement interface) 
 { 
 } 

 Impact:It was a good feature to modify the snippets, why it's gone?

**Comment by Pilchie** [comment] 2016-09-22 16:21
This is the C# equivalent of #5898.

**Comment by Pilchie** [comment] 2017-04-11 16:23
Resolving as a dupe of #5898 - don't need both of these to track.

**Closed by Pilchie** 2017-04-11 16:24 UTC
Labels: Area-IDE, Feature Request
