### ISSUE TITLE
NotNullIfNotNull fails for explicit conversion of generic

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42614] opened 2020-03-20 05:01 UTC
**Version Used**: 3.6.0-1.20127.6 (572b1f0e)

**Steps to Reproduce**:

Create a conversion operator like this:

```csharp
[return: NotNullIfNotNull("option")]
public static explicit operator PerLanguageOption<T>?(PerLanguageOption2<T>? option)
{
    if (option is null)
    {
        return null;
    }

    return new PerLanguageOption<T>(option.OptionDefinition, option.StorageLocations.As<OptionStorageLocation>());
}
```

Then use the conversion operator like this:

```csharp
public static PerLanguageOption<bool> UseTabs1 { get; } = (PerLanguageOption<bool>)FormattingOptions2.UseTabs;

public static PerLanguageOption<bool> UseTabs2 { get; } = (PerLanguageOption<bool>?)FormattingOptions2.UseTabs;
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

UseTabs1 has warning CS8600 (Converting null literal or possible null value to non-nullable type.)

UseTabs2 has warning CS8601 (Possible null reference assignment.)

**Comment by jcouv** [comment] 2020-03-25 23:14
Nullable attributes are currently not analyzed on operators (known issue).
Closing as duplicate of https://github.com/dotnet/roslyn/issues/39802 (NotNullIfNotNull is not working with implicit operator)

**Closed by jcouv** 2020-03-25 23:14 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types

**Comment by jcouv** [comment] 2020-03-25 23:16
Here's the more general issue (annotations and operators): https://github.com/dotnet/roslyn/issues/32671
