### ISSUE TITLE
Static array of static arrays enumeration causes NRE

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#24814] opened 2018-02-13 19:33 UTC
Not sure if this is compiler or some other component so putting here for now for triage. If this is not meant to work then at least compiler error or warning would be useful.
Switching field order (ab in the end) fixes the problem.

**Version Used**:

Also repros on full framework (.NET 4.7.02556 / VS Enterprise 15.6.0 Preview 5.0 [27409.1.d15.6])

```
dotnet --info
.NET Command Line Tools (15.5.0-preview-007044)

Product Information:
 Version:            15.5.0-preview-007044
 Commit SHA-1 hash:  278cbf6c44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\15.5.0-preview-007044\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c
```

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;

namespace ConsoleApp75
{
    class Program
    {
        static void Main(string[] args)
        {
            foreach (var t in All())
            {
                Console.WriteLine(t);
            }
        }

        static IEnumerable<string> All()
        {
            foreach (var arr in ab)
                foreach (var el in arr)
                    yield return el;
        }

        static string[][] ab = new[] { a, b };
        static string[] a = new[] { "a", "b", "c" };
        static string[] b = new[] { "d", "e", "f" };
    }
}
```

**Expected Behavior**:

Prints letters or compile error

**Actual Behavior**:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp75.Program.<All>d__1.MoveNext() in <path>\ConsoleApp75\ConsoleApp75\Program.cs:line 19
   at ConsoleApp75.Program.Main(String[] args) in <path>\ConsoleApp75\ConsoleApp75\Program.cs:line 10
```

**Comment by CyrusNajmabadi** [comment] 2018-02-13 20:58
This is by design. 

```c#
        static string[][] ab = new[] { a, b };
        static string[] a = new[] { "a", "b", "c" };
        static string[] b = new[] { "d", "e", "f" };
```

When you create 'ab' you're making an array of length 2, and putting the values of 'a' and 'b' into slot 0 and 1 of that array.  At that array creation point 'a' and 'b' do not have values, and thus are null.  so 'ab'  is an array of length 2 with 'null' values in every position.

If you want this to work, put the defintions of 'a' and 'b' above the definition of 'ab'.

**Comment by krwq** [comment] 2018-02-13 21:48
@CyrusNajmabadi I know the workaround (I included it in the issue) - my request was to add a warning/error about this if this is by design

**Comment by CyrusNajmabadi** [comment] 2018-02-13 21:55
> my request was to add a warning/error about this if this is by design

Definitely by design.  A warning would be breaking as there can be code out there that depends on this behavior.  Why would writing to a static field after that field has been captured be bad?  Code may absolutely to this :)

Now, if you still want a warning here, i would suggest writing your own analyzer that checks for this sort of thing and lets you know if you consider it a bad coding pattern in your own codebase.  You can even put that analyzer up on nuget so others can use it :)

**Comment by jcouv** [comment] 2018-02-14 07:08
Tagging @gafter Is this something we'd want to consider for warning wave, or should we close as by-design?

**Comment by jaredpar** [comment] 2018-02-21 16:04
Closing as "by Design"

**Closed by jaredpar** 2018-02-21 16:04 UTC
Labels: Area-Compilers, New Feature - Warning Waves
