### ISSUE TITLE
IDE1008 shows a nearly duplicate message with less information

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#49819] opened 2020-12-06 03:29 UTC
**Version Used**: 16.9-p1

It's redundant with the CS error being shown:

![image](https://user-images.githubusercontent.com/8040367/101270668-4550de00-3749-11eb-9714-a1b34b203dd0.png)

Repro seems to require a missing semicolon and being in a lambda:

```cs
class C
{
    public C(int x)
    {
        _ = new Action(() =>
        {
            new C()
        });
    }
}
```

![image](https://user-images.githubusercontent.com/8040367/101270766-46ced600-374a-11eb-91fc-5ed445484f87.png)

**Comment by Youssef1313** [comment] 2020-12-06 03:39
@mavasani I can't find the docs for IDE1008.

**Comment by jnm2** [comment] 2020-12-06 16:40
@Youssef1313, @CyrusNajmabadi gave some context at https://gitter.im/dotnet/roslyn?at=5fcc4fa74b6e8f2d3c807b5d.

**Comment by jmarolf** [comment] 2020-12-07 09:00
@jnm2 what is happening is that the compiler does not attempt to bind semantic information in the presence of some syntactic errors in a lambda. This is because it can cause errors to cascade and become unhelpful. The IDE attempts (poorly as @CyrusNajmabadi explains on gitter) to kick off the binding proccess for these cases so some IDE features can trigger. 

All these are internal details and we should just have the compiler produce the diagnostics in the first place.

**Comment by mavasani** [comment] 2020-12-07 16:29
https://github.com/dotnet/roslyn/issues/32628 tracks the compiler feature request that would help us remove this IDE analyzer, the analyzer is a bug farm that we would happily remove, https://github.com/dotnet/roslyn/issues/23667 has the background

**Comment by jnm2** [comment] 2020-12-08 03:31
@mavasani I'm also happy to close if this additional tracking item doesn't add anything beyond #32628.

**Comment by jinujoseph** [comment] 2020-12-11 08:32
Duplicate of #32628

**Closed by jinujoseph** 2020-12-11 08:32 UTC
Labels: Area-Analyzers, Resolution-Duplicate
