### ISSUE TITLE
[Test Failure] xUnit returned error code without errors in prtest/win/dbg/unit32 on PR #9648

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9672] opened 2016-03-10 22:00 UTC
PR: [#9648](https://github.com/dotnet/roslyn/pull/9648) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5082/

**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Comment by davkean** [comment] 2016-03-11 06:59
Dupe of https://github.com/dotnet/roslyn/issues/9490

**Comment by jinujoseph** [comment] 2016-03-28 16:06
PR: [#10127](https://github.com/dotnet/roslyn/pull/10127) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5630/


**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code -2146233082

**Comment by davkean** [comment] 2016-03-28 16:09
@jinujoseph This is a different issue, affecting a different assembly. This was originally ProjectSystem, the build you are looking at is
```
08:17:02   Roslyn.VisualStudio.CSharp.UnitTests.dll                                    FAILED 00:00:24.3729999
```

**Comment by jinujoseph** [comment] 2016-03-28 17:17
ah , my bad.
I will close this and look for the right issue

**Closed by jinujoseph** 2016-03-28 17:17 UTC
Labels: Area-Infrastructure, Contributor Pain
