### ISSUE TITLE
[LOC] Roslyn.Services.UnitTests.dll has extra assert failure for JPN

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5668] opened 2015-10-02 23:56 UTC
Run Roslyn.Services.UnitTests.dll on JPN OS, JPN VS, with VSUML installed.

Error is :
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_MetadataReferenceHasDocComments [FAIL]
      Assert.NotEqual() Failure
      Stack Trace:
            êŠ Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer)
            êŠ Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_MetadataReferenceHasDocCommen

**Comment by balajikris** [comment] 2015-10-05 23:20
xUnit.net console test runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2014 Outercurve Foundation.

Starting: Roslyn.Services.UnitTests.dll
   Microsoft.CodeAnalysis.UnitTests.DocumentationCommentTests.ParseTagWithMultiLineComments [SKIP]
      Bug 522741
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_MetadataReferenceHasDocComments [FAIL]
      Assert.NotEqual() Failure
      Stack Trace:
            場所 Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer)
            場所 Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_MetadataReferenceHasDocComments()
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithPrefer32BitAndConsoleApplication [FAIL]
      Assert.Equal() Failure\r\nExpected: AnyCpu32BitPreferred\r\nActual:   AnyCpu
      Stack Trace:
            場所 Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            場所 Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithPrefer32BitAndConsoleApplication()
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestCompilationOptions_VisualBasic_OptionStrict_On [FAIL]
      Assert.Equal() Failure\r\nExpected: On\r\nActual:   Off
      Stack Trace:
            場所 Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            場所 Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTestBase.AssertVBOptions[T](T expected, Func`2 actual)
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_AddVBDefaultReferences [SKIP]
      .NET Framework 3.5 is not installed
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenSolution_SolutionFileHasMissingEndProject [SKIP]
      531283
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.Test_OpenProjectReferencingPortableProject [SKIP]
      Needs target file update. Activate when we move to new base drop.
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithoutPrefer32BitAndConsoleApplication [FAIL]
      Assert.Equal() Failure\r\nExpected: AnyCpu32BitPreferred\r\nActual:   AnyCpu
      Stack Trace:
            場所 Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            場所 Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithoutPrefer32BitAndConsoleApplication()
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml [FAIL]
      Assert.Equal() Failure\r\nExpected: 6\r\nActual:   4
      Stack Trace:
            場所 Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            場所 Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml()
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithReferencedProject_LoadMetadata_ExistingMetadata_Succeeds [SKIP]
      https://roslyn.codeplex.com/workitem/451
   Microsoft.CodeAnalysis.UnitTests.CodeCleanup.FixIncorrectTokensTests.FixEndIfKeyword_SameLineAsIf [SKIP]
      889521
Finished: Roslyn.Services.UnitTests.dll

=== TEST EXECUTION SUMMARY ===
   Roslyn.Services.UnitTests.dll  Total: 858, Failed: 5, Skipped: 6

**Comment by jinujoseph** [comment] 2015-10-07 18:56
looks like related to https://github.com/dotnet/roslyn/issues/5721

**Comment by balajikris** [comment] 2015-10-14 20:52
The failures in common with #5721 no longer repro here. Note that they were also failing in ENU as well as JPN, so they weren't LOC specific. Looks like it was a legitimate break that was fixed.. 

The failures I see now are:

1. TestWorkspaceChangedEvent
event DocumentChanged was not fired within 00:05:00
Expected: True
Actual:   False

2. TestOpenProject_WithXaml
Expected: 6
Actual:   4

3. TestOpenProject_MetadataReferencesHasDocComments
Expected: Not 0
Actual:   0

**Comment by mattscheffer** [comment] 2015-10-14 20:57
I believe TestOpenProject_WithXaml repros with ENG as well. #5557 Just reopened because it was closed mistakenly.

**Comment by balajikris** [comment] 2015-10-14 23:40
Notes about failures in TestOpenProject_MetadataReferencesHasDocComments:
the assert failed because the test fetched a doc comment of length 0 for `System.Console` symbol retrieved from the compilation for a loaded project. If the same project is loaded into VS, doc comment works in the UI.

**Comment by Pilchie** [comment] 2015-10-23 16:53
This appears to be because `MSBuildWorkspace` doesn't load localized xml doc coment files.  This is not a regression from VS2015 RTM.

**Comment by balajikris** [comment] 2015-10-23 16:56
@Pilchie I have a fix locally, PR coming shortly.

**Comment by balajikris** [comment] 2015-10-23 23:15
TestOpenProject_MetadataReferencesHasDocComments is addressed by the above PR. The remaining failures are as follows and they're not LOC specific, they fail on standalone ENU runs as well.

Remaining failures from run #4042721
    Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestWorkspaceChangedWeakEvent [FAIL]
      event DocumentChanged was not fired within 00:05:00
      Expected: True
      Actual:   False
      Stack Trace:
           at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestWorkspaceChangedWeakEvent()
    Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestWorkspaceChangedEvent [FAIL]
      event DocumentChanged was not fired within 00:05:00
      Expected: True
      Actual:   False
      Stack Trace:
           at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestWorkspaceChangedEvent()
    Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml [FAIL]
      Assert.Equal() Failure
      Expected: 6
      Actual:   4
      Stack Trace:
           at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml()


/cc: @mattscheffer

**Comment by Pilchie** [comment] 2015-10-24 19:31
The last at least is already mentioned in #5557

**Comment by DustinCampbell** [comment] 2016-02-22 22:38
This issue is getting pretty stale. Is it still a problem?

**Comment by Pilchie** [comment] 2017-01-07 00:53
Moving to 2.1, as we won't address this in escrow.

**Comment by DustinCampbell** [comment] 2017-12-09 07:41
This is not a localization issue. The problem is caused by https://github.com/dotnet/roslyn/issues/23685.

**Closed** 2018-04-05 02:08 UTC
Labels: Area-IDE, Bug, Test
