### ISSUE TITLE
Extract internal class to an internal interface

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38637] opened 2019-09-11 18:37 UTC
Customer request copying here:

> The VS implementation doesn't copy documentation and only works for public members. (Often we have an internal class with all internal methods that we would like to extract to an internal interface. VS should look for dependencies and change access modifiers automatically where necessary).
Right now these limitations mean I either copy paste and do it all manually, or do some weird extra step like find replacing internal to public etc.

**Comment by ryzngard** [comment] 2020-05-04 08:17
Once we get #41576 designed we should consider visibility of new types as another configuration. 

There's also a note that seems to indicate that internal methods can't be extracted to an interface. I believe this is by design.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 03:25
Closing out due to low amount of feedback.

**Closed by CyrusNajmabadi** 2024-11-06 03:25 UTC
Labels: Area-IDE, Feature Request, Feature - Extract Method
