### ISSUE TITLE
ValidTagsDuringSimpleRename failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#31706] opened 2018-12-12 02:36 UTC
https://dnceng.visualstudio.com/public/_build/results?buildId=56656&view=ms.vss-test-web.test-result-details

```

Assert.Equal() Failure\r\nExpected: WhereSelectEnumerableIterator<TextSpan, Span> [[40..43), [208..211), [220..223)]\r\nActual: List<Span> [[40..43), [208..211), [208..211), [220..223), [220..223)]
Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_2_VerifyTaggedSpans.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_10_ValidTagsDuringSimpleRename.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by JoeRobich** [comment] 2019-01-22 16:45
Saw this again in #32665 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=77019&view=ms.vss-test-web.test-result-details) Attempt 1

**Comment by JoeRobich** [comment] 2019-04-16 14:51
Saw this again [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=156789&view=ms.vss-test-web.build-test-results-tab) Attempt 1

**Comment by dpoeschl** [comment] 2019-05-22 17:17
Another failure: https://dev.azure.com/dnceng/public/_build/results?buildId=188630&view=ms.vss-test-web.build-test-results-tab&runId=4546772&resultId=168363&paneView=debug

**Comment by sharwell** [comment] 2019-06-11 16:33
Duplicate of #29483

**Closed by sharwell** 2019-06-11 16:33 UTC
Labels: Area-IDE, Test
