### ISSUE TITLE
LastDesignTimeBuildSucceeded=false causes errors to shutdown for all but open files

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#19626] opened 2017-05-18 18:06 UTC
Project system set LastDesignTimeBuildSucceeded=false when designtime build fails to let the LS know that the information that LS has is incomplete. In that case we shutoff reporting errors because they are likely wrong but we don't do that for open files. 

After some internal discussion, this is the proposal:

If LastDesignTimeBuildSucceeded=false then

1.	We still get syntax errors from the compiler. (NB: these might not be entirely accurate since we might not have the right language version. I think that’s fine.)
2.	We don’t get semantic errors from the compiler. This means fixes driven from those are broken, but I think that’s fine. Consider “remove unused usings” – most definitely unsafe to invoke.
3.	We still run third party analyzers and code fixes triggered from them. We expect them to respect the flag if needed.

**Comment by sharwell** [comment] 2017-05-18 19:45
@srivatsn I am on board with this proposal too. I'd like to provide specific guidance for analyzer authors related to this:

1. What is the fastest way to tell if a `SyntaxTree` (or `SyntaxNode`) has syntax errors? (Make it easy to fail fast for analyzers that don't want to support error scenarios)
2. What is the fastest way to tell if a `SyntaxTree` (or `SyntaxNode`) has semantic errors from the compiler?

**Comment by heejaechang** [comment] 2017-05-18 22:59
analyzer author can't access the flag. they just need to make their analyzers works with error cases.

**Comment by CyrusNajmabadi** [comment] 2017-05-18 23:01
How does the user know that they're in this state?  Note: i mean the user using VS.  Not the person authoring an analyzer/fix.

**Comment by heejaechang** [comment] 2017-05-18 23:08
they get some kind of errors in error list. I dont believe they get errors for all cases though.

**Comment by CyrusNajmabadi** [comment] 2017-05-18 23:10
Any time we change behavior, but give no user visible indication, then that is effectively a bug.  As far as the user will be concerned, their IDE will not be working an they won't know why.  We'll get bug reports (as we have numerous examples of) and it will be enormously difficult to root cause what is actually happening.

We already made that mistake once.  Please, if you're going to change any behavior, do not do it silently.

**Comment by heejaechang** [comment] 2017-05-18 23:12
@srivatsn I guess it is your call. I prepared PR that does what you guys are asking.

**Comment by CyrusNajmabadi** [comment] 2017-05-18 23:15
For some perspective: the last time we did this, it took 13 months between the introduction of the 'fix' and our discovery that it was the issue that was leading to so many people reporting that 'fix all' was not working.  Silent behavior change not only can hurt users, but it absolutely negatively affects our own ability to diagnose and address real problems that are hitting customers.

**Comment by CyrusNajmabadi** [comment] 2017-05-18 23:27
Was there a meeting/discussion about this?  Can i get any notes or info on this?  As this affects IDE scenarios, i'd def like to be in the loop on this.  Thanks!

**Comment by jinujoseph** [comment] 2017-06-04 09:00
Closed via #19637

**Closed by jinujoseph** 2017-06-04 09:00 UTC
Labels: 4 - In Review, Area-Analyzers, Bug
