### ISSUE TITLE
Add a way to enforce naming of type parameters

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23710] opened 2017-12-11 01:21 UTC
It appears that [`applicable_kinds` doesn't have a concept of "type parameters"](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions). Please add this symbol so that we can enforce that type parameters begin with 'T'.

**Comment by sharwell** [comment] 2017-12-11 13:05
Duplicate of #18121

**Closed by sharwell** 2017-12-11 13:05 UTC
