### ISSUE TITLE
Snippets not offered in completion above usings in C#

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22810] opened 2017-10-23 21:36 UTC
**Version Used**: 15.5 Preview2

Can't find the old bug for this, so making a new one.

Developer Community Link: https://developercommunity.visualstudio.com/content/problem/25009/cannot-expand-snippet-at-top-of-source-file.html

**Comment by CyrusNajmabadi** [comment] 2017-11-02 00:32
This was intentional back since the yee olde days of the native language service.  When we added snippets it greatly degraded the *perceived* intellisense experience when typing using directives.  That's because you used to only see this tiny number of keywords that strongly demonstrated that the IDE knew exactly what was going on and was directing you to type only legal things.  Once snippets were added, that list blew up and made it seem messy and confusing.  So explicit code was added in to suppress snippets in cases like this where it was felt that hte benefit to intellisense far outweighed potentially not showing snippets here.

**Comment by CyrusNajmabadi** [comment] 2017-11-02 00:33
Basically, a by design limitation to make one common experience better at the cost of making a far less common scenario worse.

**Comment by mvinca** [comment] 2018-12-24 15:43
Can we define an explicit code snippet type that would allow only these types to appear at the top of source files?

**Comment by CyrusNajmabadi** [comment] 2023-02-08 18:56
Closing out as our intended design.  New snippets can show up above usings if they use the new snippet authoring system (where they have full control over where htey show up).  Existing snippets will not show up here as there is no capability for that, and we do not want to degrade teh experience there by showing all snippets.

**Closed by CyrusNajmabadi** 2023-02-08 18:56 UTC
Labels: Area-IDE, Developer Community
