### ISSUE TITLE
Resolve from NuGet doesn't work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27010] opened 2018-05-21 13:11 UTC
**Version Used**: 
Version 15.8.0 Preview 2.0 [27716.1.d15.8]

**Steps to Reproduce**:

1. 
```
    class Program
    {
        static void Main(string[] args)
        {
            JObject foo; // <-- CTRL+. on JObject
        }
    }
```
**Expected Behavior**:
To be able to resolve from NuGet

**Actual Behavior**:
Unable to resolve from NuGet.

**Comment by sharwell** [comment] 2018-05-21 14:40
I am not able to reproduce this on 15.8 Preview 1, so this is either a regression in the internal build or somehow the option was disabled locally (it's disabled by default so any settings reset would disable this feature).

**Comment by jmarolf** [comment] 2018-05-21 15:27
@davkean the fix is not offered until we have initialized the type catalog.  This happens asynchronously so you may see cases where the fix isn't offered initially after you update Visual Studio but it should show after a few seconds.  Alternatively it could be as @Pilchie says and we can't get instantiate the catalog at all for some reason (telemetry should be logged in this case but I'll need to check).

**Comment by davkean** [comment] 2018-05-21 22:12
This is broken for me in 15.8 Preview 1.1 and the build above. The option is checked, and VS has been open for 12 hours.

**Comment by davkean** [comment] 2018-06-15 06:54
This still doesn't work, can someone point me to logs so that I can figure out what's going on?

**Comment by davkean** [comment] 2018-06-28 05:49
I have 3 side-by-side versions of VS installed:

15.7.4
15.8 Preview 3
15.8 Preview 4.0 [27821.3001.d15.8stg]

None of them offer me NuGet packages.

I have the settings turned on.

@CyrusNajmabadi Do you remember what's required to have this feature work? I do remember something about sources needing to be set to default. I noticed I have 2 extra sources that I never added; CLIFallbackFolder, Microsoft Visual Studio Offline Packages and NuGet.org, but reducing this down to NuGet.org didn't fix the issue.

**Comment by davkean** [comment] 2018-07-23 23:49
I checked on disk and all instances have downloaded the index, for example:

C:\Users\davkean\AppData\Local\Microsoft\VisualStudio\15.0_ebf6642c\PackageCache\Format1\nuget.org.txt

**Comment by CyrusNajmabadi** [comment] 2018-07-30 15:39
You need at least this in your package source:

![image](https://user-images.githubusercontent.com/4564579/43407624-3c0ca664-93ed-11e8-8d6a-642ab5d44c9a.png)

**Comment by CyrusNajmabadi** [comment] 2018-07-30 20:55
Codestack to debug would be:

```
>	Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.FindPackagesWithTypeAsync(string source, string name, int arity, System.Threading.CancellationToken cancellationToken) Line 101	C#
 	Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchService.FindPackagesWithTypeAsync(string source, string name, int arity, System.Threading.CancellationToken cancellationToken) Line 115	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.SymbolReferenceFinder.FindNugetTypeReferencesAsync(Microsoft.CodeAnalysis.Packaging.PackageSource source, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.Reference> allReferences, Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax nameNode, string name, int arity, bool isAttributeSearch, System.Threading.CancellationToken cancellationToken) Line 123	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.SymbolReferenceFinder.FindNugetOrReferenceAssemblyTypeReferencesWorkerAsync(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.Reference> allReferences, Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax nameNode, string name, int arity, bool isAttributeSearch, System.Threading.CancellationToken cancellationToken) Line 77	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.SymbolReferenceFinder.FindNugetOrReferenceAssemblyTypeReferencesAsync(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.Reference> allReferences, Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax nameNode, string name, int arity, bool inAttributeContext, System.Threading.CancellationToken cancellationToken) Line 58	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.SymbolReferenceFinder.FindNugetOrReferenceAssemblyReferencesAsync(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.Reference> allReferences, System.Threading.CancellationToken cancellationToken) Line 42	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.FindResultsAsync(System.Collections.Concurrent.ConcurrentDictionary<Microsoft.CodeAnalysis.Project, Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.IAssemblySymbol>> projectToAssembly, System.Collections.Concurrent.ConcurrentDictionary<Microsoft.CodeAnalysis.PortableExecutableReference, Microsoft.CodeAnalysis.Compilation> referenceToCompilation, Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.SymbolReferenceFinder finder, bool exact, System.Threading.CancellationToken cancellationToken) Line 203	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.FindResultsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SemanticModel semanticModel, string diagnosticId, Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.SymbolSearch.ISymbolSearchService symbolSearchService, bool searchReferenceAssemblies, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Packaging.PackageSource> packageSources, System.Threading.CancellationToken cancellationToken) Line 148	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.GetFixesInCurrentProcessAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan span, string diagnosticId, bool placeSystemNamespaceFirst, Microsoft.CodeAnalysis.SymbolSearch.ISymbolSearchService symbolSearchService, bool searchReferenceAssemblies, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Packaging.PackageSource> packageSources, System.Threading.CancellationToken cancellationToken) Line 113	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService<Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax>.GetFixesAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan span, string diagnosticId, bool placeSystemNamespaceFirst, Microsoft.CodeAnalysis.SymbolSearch.ISymbolSearchService symbolSearchService, bool searchReferenceAssemblies, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Packaging.PackageSource> packageSources, System.Threading.CancellationToken cancellationToken) Line 87	C#
 	Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(Microsoft.CodeAnalysis.CodeFixes.CodeFixContext context) Line 66	C#
 	Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan span, Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider fixer, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic> diagnostics, System.Threading.CancellationToken cancellationToken) Line 325	C#
```

**Comment by davkean** [comment] 2018-07-31 00:13
I had to drop looking into this because there's no symbols (https://github.com/dotnet/roslyn/issues/28800).

**Comment by davkean** [comment] 2019-05-01 13:16
Just as a reminder this was never resolved, this has not worked on my machine for over a year. I have various versions of Visual Studio installed and this feature works in none of them.

**Comment by jmarolf** [comment] 2019-05-01 13:33
I was looking at something on @mikadumont 's machine and this codefix did not show up there either. @sharwell can you confirm this feature working via telemetry? The nuget index may just be too far out of date.

**Comment by davkean** [comment] 2019-05-01 14:01
I debugged into this. This is because my NuGet.org source was named "NuGet" and not "nuget.org", switching back to nuget.org resolved this:

![image](https://user-images.githubusercontent.com/1103906/57020649-44062800-6c6d-11e9-8c2e-f5009b057fae.png)

There has to be a better way to find the data that matches that source.

**Comment by jmarolf** [comment] 2019-05-01 14:48
Yeah, we should just key off of the source URL, not the name, that is too brittle

**Comment by jmarolf** [comment] 2019-05-01 14:49
I'll confirm this is what happened on @mikadumont 's machine but it seems likely since all the repos in dotnet mess with the default package source

**Comment by jmarolf** [comment] 2019-05-01 14:50
@davkean can you change the repro steps now that we know whats going on?

**Comment by jmarolf** [comment] 2019-05-01 16:08
It was easier to just fix this over breakfast: https://github.com/dotnet/roslyn/pull/35397

**Comment by donnie-msft** [comment] 2021-09-22 01:57
Hit this issue today where the NuGet codefix wasn't appearing. Unfortunately, I now realize it's because in VS, my nuget.org source was named "nuget" but Roslyn requires it to be "nuget.org".

The fix that closed this issue was reverted, but the issue is still closed.

**Closed** 2021-09-23 07:03 UTC
Labels: Bug, Area-IDE
