### ISSUE TITLE
VS should show all possible exceptions thrown from a method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41543] opened 2020-02-10 18:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/896458/vs-should-show-all-possible-exceptions-thrown-from.html)._

---
Right now, if you hover over library methods, VS shows what exceptions are thrown from that method.  VS should use this information to determine the possible exceptions thrown from all methods, including non-library methods.  This would dramatically simplify implementing exception handling.

---
#### Visual Studio Feedback System on 1/28/2020, 01:20 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2020-02-12 20:35
Duplicate of https://github.com/dotnet/roslyn/issues/15573

**Closed by jinujoseph** 2020-02-12 20:35 UTC
Labels: Area-IDE, Developer Community
