### ISSUE TITLE
Go to All and Find All References deduplication improvements

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#19376] opened 2017-05-09 22:23 UTC
<sup>Moving the conversation @NickCraver started [from Twitter](https://twitter.com/Nick_Craver/status/861718011409039361) at @davkean's request.</sup>

VS2017's Go to All and Find All References duplicates items for each platform or framework you're building against. If you build for six platforms, every member shows up six times but takes you to exactly the same point in the same document. It's pure noise which limits what else you can see in the list.

For example, using @NickCraver's screenshots:

<img src="https://cloud.githubusercontent.com/assets/8040367/25875091/be3ab424-34e3-11e7-9a37-5e40438c01b7.jpg" width="50%"><img src="https://cloud.githubusercontent.com/assets/8040367/25875092/c09b7a46-34e3-11e7-97af-de8577bb14c7.jpg" width="50%">

The items should be grouped by destination. The information that is unique to each entry (the framework) should be shown in small print underneath. Only one thing should be clickable for all platforms, unless there are signatures in different physical files or positions due to csproj conditional file includes or `#if` preprocessor. One navigation destination, one entry.

This would be amazing (pardon my MS Paint):

<img src="https://cloud.githubusercontent.com/assets/8040367/25875241/58da2bfe-34e4-11e7-9ef8-1af942cab604.jpg" width="50%">

**Comment by NickCraver** [comment] 2017-05-09 22:30
Related here, there' a search bug I noticed in capturing these. Note what happens I enter `T` right after a `<` in the search, certainly not expected behavior:

<img width="478" alt="screen shot 2017-05-08 at 19 23 32" src="https://cloud.githubusercontent.com/assets/454813/25875385/20345e9a-34e5-11e7-9440-2db4296e6a03.png">

...with a `T` goes to:

<img width="474" alt="screen shot 2017-05-08 at 19 23 39" src="https://cloud.githubusercontent.com/assets/454813/25875407/3a23aa40-34e5-11e7-99e0-6cc8204c5d25.png">

If I had to guess it seems like the `<` is ignored completely, and then `T` is pressed it's actually searching for `QueryT`? Maybe not, just a guess. Should I file another issue on that? I'm not sure if this is search or Roslyn or both or...

**Comment by jnm2** [comment] 2017-05-09 22:30
@NickCraver My guess is separate issue.

**Comment by CyrusNajmabadi** [comment] 2017-05-09 23:49
PRs welcome

**Comment by CyrusNajmabadi** [comment] 2017-05-09 23:51
We don't support any sort of special syntax for generic types.  Note that we're also moving our pattern matching code down to the platform layer (so all managed languages in VS could use it).  As such, it gets even more difficult to put in support for matching all the sorts of special constructs that could be different across languages.

**Comment by jnm2** [comment] 2017-05-09 23:55
@CyrusNajmabadi
> We don't support any sort of special syntax for generic types.

It's literally a matter of matching the text of the items that show up in the list. Instead of just indexing the name, you could index the display text.

**Comment by NickCraver** [comment] 2017-05-09 23:57
That's unfortunate, searching for a generic is a **very** common case here. A specific usage, or <T>, etc. Reverting to text find for all those cases really is very frustrating since I can see the results just down the list...but a text find is often faster than going through it.

I'm unfamiliar with VS tooling, really not a good use of my time (compared to libs for the community), but I hope someone more familiar is able to tackle this. I'd readily test away on any bits.

**Comment by jnm2** [comment] 2017-05-09 23:59
@NickCraver This is definitely two separate issues though.

**Comment by NickCraver** [comment] 2017-05-10 00:00
@jnm2 yeah totally fair - I'll at least file this out, un momento.

**Comment by jnm2** [comment] 2017-05-10 00:00
@NickCraver loop me in please? I have an idea that I'll add.

**Comment by jnm2** [comment] 2017-05-10 00:02
I added this issue to my PR wishlist, so maybe I'll get around to this in a year if no one beats me to it. 😝

**Comment by NickCraver** [comment] 2017-05-10 00:05
Filed as an issue in https://github.com/dotnet/roslyn/issues/19380

**Comment by CyrusNajmabadi** [comment] 2017-05-10 00:23
> It's literally a matter of matching the text of the items that show up in the list. Instead of just indexing the name, you could index the display text.

It's really not that simple :)

(trust me, i've written and rewritten this system several times).  For one thing we don't want symbols to be generated when producing the index.  So we don't have a context of 'DisplayText'.   

Furthermore, this gets deeply complex due to the fact that different languages have different symbolic representations for these things.  For example, say you wrote the type in VB, but you want to search for it in C#.

**Comment by Pilchie** [comment] 2017-05-10 19:03
The FAR issue is already tracked as https://github.com/dotnet/roslyn/issues/16587.  I'm going to close this as a dupe, but update the original issue to point out that it affects Go To as well.

**Closed by Pilchie** 2017-05-10 19:03 UTC
Labels: Area-IDE, Bug, up-for-grabs
