### ISSUE TITLE
Non-unicode source code with Cyrillic symbols in identifiers leads either to unexpected results, or compilation errors

### ISSUE THREAD

**Issue by Dennis-Petrov** [dotnet/roslyn#4410] opened 2015-08-07 11:19 UTC
Hi.
Consider this code:

    using System;

    class Program
    {
        enum Цвета
        {
            Красный,
            Желтый,
            Зеленый
        }

	    public static void Main()
	    {
		    Console.WriteLine(Цвета.Красный);
	    }
    }

Identifiers here (particularly, `enum`) contain Cyrillic symbols. If this code will be saved to the cs file, using WIN-1251 code page, it will be compiled, but the output will be "E?aniue" instead of "Красный".

The "old" compiler (from "%Windir%\Microsoft.NET...") compiles this code correctly, the program output is "Красный". Saving source to UTF-8 also helps.

Using Rolsyn from VS 2015 with this bug leads to compilation errors in output window, while IntelliSense works fine.

**Comment by gafter** [comment] 2015-08-07 17:54
@agocke @jaredpar Is this related to #4335 or #1039

**Comment by jaredpar** [comment] 2015-08-13 18:26
Thanks for reporting.  This appears to be a dupe of #4222.  This fix will be included in the next release of the compiler.

**Closed by jaredpar** 2015-08-13 18:26 UTC
Labels: Area-Compilers
