### ISSUE TITLE
CSharp.Scripting...ObjectFormatterTests Failing

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9237] opened 2016-02-26 16:47 UTC
`Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests.StackTrace_Dynamic` started failing in X64 Rolling Build (roslyn_stabil_win_rel_unit64) following the merge of this PR:
https://github.com/dotnet/roslyn/pull/9193

http://dotnet-ci.cloudapp.net/job/roslyn_stabil_win_rel_unit64/136/

@tmat @dotnet/roslyn-infrastructure

**Comment by natidea** [comment] 2016-02-26 16:48
@tmat could you take a look?

**Comment by davkean** [comment] 2016-02-26 16:49
Dupe of #9221

**Closed by davkean** 2016-02-26 16:49 UTC
Labels: Area-Interactive, Bug, Urgency-Now
