### ISSUE TITLE
AbstractSpellCheckCodeFixProvider depends on IDE completion options

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#58745] opened 2022-01-10 00:33 UTC
The code fix provider reads CompletionOptions from Solution snapshot. These options are not configurable via .editorconfig, only in the IDE. Therefore this code fix provider will behave differently when executed from build vs IDE.

https://github.com/dotnet/roslyn/blob/f36574c3abecf2ed738c55bf11e79eaed57cf49f/src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs#L106-L122

**Comment by tmat** [comment] 2022-01-10 00:37
@CyrusNajmabadi What's the logic behind using completion items in spell checker? Should the spell checker use constant, non-configurable set of completion options rather then reading them from the solution options?

**Comment by CyrusNajmabadi** [comment] 2022-01-10 00:52
> @CyrusNajmabadi What's the logic behind using completion items in spell checker?

Basically, the idea is:  completion already is the reverse side of this process.  It informs us as to what names we already think are valid in this location (through all of our completion logic systems).  So if you misspell something, we can just use completion to guess as to what they may have meant instead.  

> Should the spell checker use constant, non-configurable set of completion options rather then reading them from the solution options?

I think a constant set of options is entirely fine.

**Comment by tmat** [comment] 2022-01-10 01:23
Sounds reasonable.

**Comment by tmat** [comment] 2022-01-10 01:56
@sharwell

We do have other code fix providers that depend on IDE options, e.g. Add Import.
Do we explicitly distinguish between code fix providers that are expected to be only invoked from IDE and those we want to potentially invoke from `dotnet-format`?

**Comment by sharwell** [comment] 2022-01-13 23:31
> this code fix provider will behave differently when executed from build vs IDE.

Code fixes are only executed in the IDE.

Analyzers execute in both, but NuGet-installed analyzers are blocked from accessing the IDE definitions of options.

**Comment by CyrusNajmabadi** [comment] 2024-11-29 21:46
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-11-29 21:46 UTC
Labels: Area-IDE, Concept-Continuous Improvement
