### ISSUE TITLE
IDE0090 incorrectly suggested for `new` expression

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/roslyn#50735] opened 2021-01-24 07:53 UTC
**Version Used**: 

`Microsoft.CodeAnalysis.CSharp.NetAnalyzers` 5.0.102
`Microsoft.CodeAnalysis.NetAnalyzers` 5.0.102

**Steps to Reproduce**:

Write the following code:
```cs
public static class StructExtensions
{
    public static T? ToNullable<T>(this T value)
            where T : struct
        => new T?(value);
}
```

**Expected Behavior**:

Code fixes offered should be for correct code.

**Actual Behavior**:

Roslyn suggests "IDE0090: 'new' expression can be simplified" on the `new T?(value)` expression in the above code snippet. It suggests the code fix `new(value)`. However, applying this change results in an error, "CS0417: 'T': cannot provide arguments when created an instance of a variable type".

**Comment by Youssef1313** [comment] 2021-01-24 10:55
This feels like a compiler issue. The type here should be inferable as "Nullable<T>" which has a constructor taking one argument. i.e. `new(value)` should compile IMO.

Tagging @jcouv @alrz who worked on the feature.

**Comment by Youssef1313** [comment] 2021-01-24 11:32
https://github.com/dotnet/roslyn/blob/6bf3920b9170f201c9c2fb8301d2a07e22870756/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L5505-L5528

I think the case for one or more arguments should check if it's a nullable value type and bind to `Nullable<T>`.

**Comment by alrz** [comment] 2021-01-24 13:29
For nullable types, we target the underlying type e.g. `T` in this example. 

https://github.com/dotnet/roslyn/blob/6bf3920b9170f201c9c2fb8301d2a07e22870756/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs#L193-L196

So the example above cannot use `new()` but it could be simplified to `=> value;`

**Comment by Zannick** [comment] 2021-03-27 00:35
I am getting this suggestion on a line
```c#
List<Card> stack = new List<Card>(4);
```
where `Card` is an integer Enum. The suggestion turns the line into
```c#
List<Card> stack = new(4);
```

**Expected behavior**

Suggestion results in correct code, or suggestion is not given.

**Actual behavior**

The following compiler errors, the first five of which point at the `4` and the last of which points at the closing paren:
```
error CS1031: Type expected
error CS8124: Tuple must contain at least two elements.
error CS1026: ) expected
error CS1526: A new expression requires (), [], or {} after type
error CS1002: ; expected
error CS1002: ; expected
```


<details><summary>Versions</summary>

Microsoft Visual Studio Community 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23  
Microsoft .NET Framework Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
Azure App Service Tools v3.0.0   16.9.688.6828
Azure Functions and Web Jobs Tools   16.9.688.6828
C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Common Azure Tools   1.10
CreateActionClasses Extension   1.0
IntelliCode Extension   1.0
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1
Microsoft Continuous Delivery Tools for Visual Studio   0.4
Microsoft JVM Debugger   1.0
Microsoft Library Manager   2.1.113+g422d40002e.RR
Microsoft MI-Based Debugger   1.0
Microsoft Visual Studio Tools for Containers   1.1
NuGet Package Manager   5.9.0
NVIDIA Nsight Visual Studio Edition   2020.3.0.20315
NVIDIA Nsight Visual Studio Edition - CUDA support   2020.3.0.20315
ProjectServicesPackage Extension   1.0
SQL Server Data Tools   16.0.62103.10080
TypeScript Tools   16.0.30201.2001
Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Container Tools Extensions   1.0
Visual Studio Tools for Containers   1.0
</details>

**Comment by CyrusNajmabadi** [comment] 2021-03-27 01:23
@jcouv ?

**Comment by Youssef1313** [comment] 2021-03-27 05:51
I can't reproduce compile errors:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYAWAbgFgAoa7AZkICZ8Bhagb2v28IexPwBZABQBKLj05UeM/ABkAlrAA8LCAhQA+fLAgBjANb4AvPgB2cAO7CSoytJ4Bfas5pV6+OGYCuYVupR8dkcgA==

Looking at the analyzer implementation, it also does seem to handle the language version correctly:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Analyzers/CSharp/Analyzers/UseImplicitObjectCreation/CSharpUseImplicitObjectCreationDiagnosticAnalyzer.cs#L42-L44

**Comment by Zannick** [comment] 2021-03-27 06:24
Did not correctly capture my compiler version generating the error--it's `3.0.19.17001 (1deafee3)` according to `#error version`.

**Comment by juniorodilton** [comment] 2021-07-11 16:12
> I am getting this suggestion on a line
> 
> ```cs
> List<Card> stack = new List<Card>(4);
> ```
> 
> where `Card` is an integer Enum. The suggestion turns the line into
> 
> ```cs
> List<Card> stack = new(4);
> ```
> 
> **Expected behavior**
> 
> Suggestion results in correct code, or suggestion is not given.
> 
> **Actual behavior**
> 
> The following compiler errors, the first five of which point at the `4` and the last of which points at the closing paren:
> 
> ```
> error CS1031: Type expected
> error CS8124: Tuple must contain at least two elements.
> error CS1026: ) expected
> error CS1526: A new expression requires (), [], or {} after type
> error CS1002: ; expected
> error CS1002: ; expected
> ```
> 
> Versions

I have the same error

**Comment by CyrusNajmabadi** [comment] 2021-07-11 16:22
What version of vs are you using?

**Comment by HSyr** [comment] 2021-08-10 11:24
I had the same issue and resolved it by deleting the following line from my .csproj file:

`<Import Project="packages\Microsoft.Net.Compilers ...`

**Comment by marschne** [comment] 2021-09-27 08:04
I updated the NuGet package "Microsoft.Net.Compilers" from version 3.3.1 to 3.11.0 (using VS Pro 16.11.3). Problem solved.

**Closed** 2022-02-11 08:51 UTC
Labels: Bug, help wanted, Area-IDE, IDE-CodeStyle
