### ISSUE TITLE
Warn if a condition is always true or false

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#25592] opened 2018-03-19 14:50 UTC
**Version Used**:   `NullableReferenceTypes` branch,

**Steps to Reproduce**:

The following program produces a `Possible dereference of a null reference` warning on `o.M();`.

```cs
class C {
    void M() {
        object? o = null;
        if (o == null)
            o.M();
    }
}
```

you can change the code like this: `o?.M()` to address the issue. But a more useful warning is to say:

*`o == null` is always true*

so there should be another bug before we even reach the possible dereference.

There is a similar feature request for this analysis on the IDE side, but I think it is tightly coupled with the one that is planned for nullable reference types and they can actually exchange information to give the most relevant warning.

This could be not limited to the `null` constant, as any value that can be statically decided for `o` at that point, may produce a similar warning.

Relates to: https://github.com/dotnet/roslyn/issues/22743

**Comment by gafter** [comment] 2018-03-19 15:30
We don't track that a variable is definitely null. Only that it is possibly null.

**Comment by gafter** [comment] 2018-03-19 15:41
The states that we track are
1. Possibly null (nullable reference type)
2. Definitely not null (non-nullable reference type)
3. Shut up (gullible reference type)

**Comment by alrz** [comment] 2018-09-13 10:14
I think this could be a part of warning waves where we flag "always true/false" on branches,

https://github.com/dotnet/roslyn/blob/8edf4999ab3a1581277786440089b3d081de17fe/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs#L106-L109

Could flag possible bugs when you wrap an piece of code in a if statement, etc.

**Comment by jaredpar** [comment] 2019-01-26 00:37
Closing as this behavior is by design.

**Closed by jaredpar** 2019-01-26 00:37 UTC
Labels: Area-Compilers, Bug, Concept-Diagnostic Clarity, New Language Feature - Nullable Reference Types
