### ISSUE TITLE
Collapse to Definitions does not collapse enum types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38932] opened 2019-09-27 22:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/732602/ctrl-m-o不能折叠内部类型比如enum.html)._

---
Ctrl and M-O cannot collapse internal types such as enum

---
#### Jane Wu [MSFT] on 9/16/2019, 00:23 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment] 2019-10-01 18:39
I believe this behavior is By Design, but I'll confirm it with the team during a design review before closing. 👍

**Comment by ryzngard** [comment] 2019-10-07 22:37
Design Review: We agree this is by design.

**Closed by ryzngard** 2019-10-07 22:37 UTC
Labels: Area-IDE, Developer Community, Need Design Review, Question, Resolution-By Design
