### ISSUE TITLE
ProjectChanges.GetChangedDocuments(true) returns unchanged document

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#30674] opened 2018-10-23 22:14 UTC
**Version Used**: 2.9.0

**Steps to Reproduce**:

```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Text;

static class Program
{
    static async Task Main()
    {
        const string source = @"
#Disable Warning x

Namespace N
End Namespace";

        Document document = new AdhocWorkspace()
            .CurrentSolution
            .AddProject("TestProject", "TestProject", LanguageNames.VisualBasic)
            .WithMetadataReferences(new MetadataReference[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) })
            .AddDocument("Test.cs", SourceText.From(source));

        Console.WriteLine((await document.GetTextVersionAsync().ConfigureAwait(false)).ToString());
        Document newDocument = await Formatter.FormatAsync(document).ConfigureAwait(false);
        Console.WriteLine((await newDocument.GetTextVersionAsync().ConfigureAwait(false)).ToString());

        Console.WriteLine("changed documents: " + newDocument.Project.GetChanges(document.Project).GetChangedDocuments(onlyGetDocumentsWithTextChanges: true).Count());
        Console.WriteLine("text changes: " + (await newDocument.GetTextChangesAsync(document).ConfigureAwait(false)).Count());
        Console.WriteLine("text equals: " + (document.GetSyntaxRootAsync().Result.ToFullString() == newDocument.GetSyntaxRootAsync().Result.ToFullString()));

        Console.ReadKey();
    }
}
```

**Expected Behavior**:
`GetChangedDocuments(true)` returns no document.

**Actual Behavior**:
`GetChangedDocuments(true)` returns unchanged document.

**Comment by jinujoseph** [comment] 2018-10-26 18:31
cc @heejaechang

**Comment by JosefPihrt** [comment] 2018-11-02 14:49
My original sample was VB code. The issue can be also reproduced with this C# code:
```csharp
class C
{
    void M()
    {
        if (true &&
            // x
            true)
            M();
    }
}
```

**Comment by CyrusNajmabadi** [comment] 2018-11-02 21:38
Could you add more info?  For example, what is GetTextChangesAsync returning?

**Comment by JosefPihrt** [comment] 2018-11-02 22:31
GetChangedDocuments returns the document whereas GetTextChangesAsync returns no changes.

**Comment by CyrusNajmabadi** [comment] 2022-10-31 21:28
i can't repro this.  we'd need a repro project that shows the issue.

**Comment by JosefPihrt** [comment] 2022-10-31 22:37
Hi,

The complete repro is in the first post.

I tried to run it again (with 4.3.1) and I'm getting this output:

```
2022-10-31T22:32:25.5160852Z-10005-0
2022-10-31T22:32:27.3712044Z-10007-0
changed documents: 1
text changes: 0
text equals: True
```

`GetChangedDocuments(onlyGetDocumentsWithTextChanges: true)` returns one document even though there are no text changes and the documents' texts are identical.

**Comment by CyrusNajmabadi** [comment] 2022-10-31 23:38
@JosefPihrt 

> we'd need a repro project that shows the issue.

**Comment by JosefPihrt** [comment] 2022-11-01 00:14
Repro project is here:

[GetChangedDocumentsBug.zip](https://github.com/dotnet/roslyn/files/9905714/GetChangedDocumentsBug.zip)

**Comment by CyrusNajmabadi** [comment] 2024-10-25 05:16
I still can't repro this.  Can you debug through and see what the reason is it is reporting a change?

**Comment by josefpihrt** [comment] 2024-10-26 18:25
I can still repro this one on 4.11.0

Project to reproduce: [GetChangedDocumentsBug.zip](https://github.com/user-attachments/files/17531619/GetChangedDocumentsBug.zip)

I got following output:
```
2024-10-26T18:24:33.8328230Z-10005-0
2024-10-26T18:24:34.1678560Z-10007-0
changed documents: 1
text changes: 0
text equals: True
```

**Comment by CyrusNajmabadi** [comment] 2024-10-26 18:38
@josefpihrt can you debug through this?  Something odd is happening on your side

**Comment by josefpihrt** [comment] 2024-10-26 18:49
I was able to get here

https://github.com/dotnet/roslyn/blob/57c4b92785d4b64bd1c68f6fc7694f313c2e686a/src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs#L224

where on the left is RecoverableTextAndVersion and on the right is DocumentState.TreeTextSource.

**Comment by CyrusNajmabadi** [comment] 2024-10-26 19:43
Ah this is by design then.  One solution is backed by text, the other by a tree. That tree may be different from what the text would produce and might contain things like annotations. 

As some features may need this info, they need to know they're getting a different backing instance.

**Comment by CyrusNajmabadi** [comment] 2024-11-06 02:20
Closing as by design.

**Closed by CyrusNajmabadi** 2024-11-06 02:20 UTC
Labels: Bug, Area-IDE, untriaged
