### ISSUE TITLE
C# Intellisense: group suggestion members from last child type then members of parent types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50796] opened 2021-01-26 19:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Intellisense:-group-suggestion-member/1312114)._

---
Sorry for my bad english, you may feel hard to understand the title.

```
public class A
{
	public int myField;

public void MyMethod1() { }

public void MyMethod2() 
	{
		A a = null;
		a.
	}
}
```

When i ctrl+space "a." it shows too many suggestions, i want to see the members of the class A FIRSTLY.
Another example: class A inherit from class B, class B inherit from class C.
In class A: i want to see members suggestion of A FIRSTLY, then members of B SECONDLY then members of C THIRDLY then finally members of Object.

In the same class, all members will be sorted by alphabet.
The members list of every type in the hierarchy should be separated by lines and titles.

For the interfaces, it will be similar to classes: the interface-members of the LAST TYPE will be showed FIRSTLY.
Thank you !

---
#### Feedback Bot on 1/17/2021, 11:56 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2021-01-26 21:22
Duplicate of #42676

**Closed by jinujoseph** 2021-01-26 21:22 UTC
Labels: Area-IDE, Concept-Continuous Improvement, Developer Community
