### ISSUE TITLE
Incorrect quick fix opton in editorconfig `IDE0037 Member name can be simplified` for anonymous type member names

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40481] opened 2019-12-18 23:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/853373/incorrect-quick-fix-opton-in-editorconfig-ide0037.html)._

---
It's suggesting `dotnet_style_prefer_inferred_tuple_names` instead of `dotnet_style_prefer_inferred_anonymous_type_member_names`

e.g.
```
_ = new { Length = "". Length };
```

using Visual Studio 2019 16.3.5

---
#### Visual Studio Feedback System on 12/12/2019, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/18/2019, 03:05 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment] 2019-12-18 23:27
Tagging @allisonchou - I believe this was fixed by you few days ago. Can you confirm and resolve as a duplicate?

**Comment by allisonchou** [comment] 2019-12-19 00:41
Yes, this should now be fixed by #40017.

**Comment by allisonchou** [comment] 2019-12-19 00:43
Duplicate of #40017.

**Closed by allisonchou** 2019-12-19 00:43 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
