### ISSUE TITLE
IDE0060 when the parameters are needed due to other overloads

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#34000] opened 2019-03-09 21:18 UTC
**Version Used**: VS2019 RC.1 SVC1

Can Roslyn do anything to help this situation, maybe bail if it detects that there are other overloads following the same pattern?

```cs
class Foo
{
    public Foo Reduce(SaveClickedAction action)
    {
        // Some of these methods use `action`, others don't.
        // ...
    }

    public Foo Reduce(FinishClickedAction action)
    {
        // ...
    }

    public Foo Reduce(SaveCompletedAction action)
    {
        // ...
    }

    public Foo Reduce(SaveErroredAction action)
    {
        // ...
    }
}
```

**Comment by CyrusNajmabadi** [comment] 2019-03-09 21:24
Could you clarify this example some more.  What's the problem if you remove `SaveClickedAction action`?  Wouldn't it be weird if someone produced a delegate and passed it along here just to pick this overload, only to have it not be used?

**Comment by jnm2** [comment] 2019-03-09 21:38
These actions are all descriptive structs, but some of them are empty structs because there is no parameterization needed besides the kind of action itself. Kind of like a loose discriminated union.

The problem if you remove the parameter is that there's nothing to show what kind of action is being handled.

Maybe the convention could be to move the type name to the method name rather than passing a fieldless struct.

**Comment by CyrusNajmabadi** [comment] 2019-03-09 21:51
Gotcha... definitely an interesting way to do things!

**Comment by sharwell** [comment] 2019-03-11 13:31
@mavasani for input

**Comment by mavasani** [comment] 2019-03-11 14:05
You can use ‘_’, ‘_1’, ‘_2’, etc. as parameter names to indicate unused but non-removable parameters, which will not be flagged. We should improve the diagnostic text for the message to clarify this.

**Comment by sharwell** [comment] 2019-03-11 14:10
@mavasani the argument *is* used for overload disambiguation. Also, changing the parameter name would hurt documentation for API consumers.

**Comment by jnm2** [comment] 2019-03-11 14:34
@mavasani Then I have to reckon with my naming conventions which error if a parameter name starts with `_`, and I think the same way Sam does about the API documenting itself.

**Comment by mavasani** [comment] 2019-03-11 15:29
> the argument is used for overload disambiguation

The _type_ of the parameter is used for overload resolution, not the parameter or it's underlying value. In that sense, the parameter itself is unused and the argument is discarded. I don't think the unused parameters analyzer itself should bail out on methods which have overloads, as this will mask real unused parameter violations.

> Maybe we update the documentation to list cases like this as a reason to suppress the diagnostic for a whole type or file

I agree with this, we should improve diagnostic message here to make case for scenarios where a suppression is the best choice. You seemed to have a case where you really want a documented, but unused parameter for very special reasons, and a suppression with a property justification to retain unused parameter is the right approach. This suppression would also serve as documentation for future developers to not remove this parameter or rename it to a discard.

**Comment by mavasani** [comment] 2019-03-11 15:38
@jnm2 I looked at the repro code and also find the code super confusing. I would personally rewrite this as below:

```
class Foo
{
    public Foo Reduce(BaseClickedAction action)
    {
        switch (action)
        {
           case FinishClickedAction finishedClickedAction:
                return Reduce(finishedClickedAction);

           case SaveCompletedAction saveCompletedAction:
                return Reduce(saveCompletedAction);

           case SaveErroredAction _:
                  return ReduceForSaveErroredAction();
        }
    }

    public Foo Reduce(FinishClickedAction action)
    {
        // 'action' is used
    }

    public Foo Reduce(SaveCompletedAction action)
    {
        // 'action' is used
    }

    private Foo ReduceForSaveErroredAction()
    {
        // 'action' is not required
    }
}
```

**Comment by jnm2** [comment] 2019-03-11 16:23
That's what I mentioned doing at the end of my second comment. On the other hand, properties are often added to existing empty structs, so there's where the pain will lie. It might be the best tradeoff.

**Comment by mavasani** [comment] 2019-03-11 17:41
@sharwell I have marked this as Needs design review + tentatively by design. We should discuss this at the design meeting.

**Comment by sharwell** [comment] 2019-03-25 03:35
We concluded in the design meeting that this is a reasonable situation to suppress the diagnostic. As an alternative, you could define an internal interface with the methods, as this diagnostic will not report parameters as unused when the method implements an interface method.

**Closed by sharwell** 2019-03-25 03:35 UTC
Labels: Area-IDE, Need Design Review, Resolution-By Design
