### ISSUE TITLE
Allow implementing properties from getter and setter declared in separate interfaces

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/roslyn#6559] opened 2015-11-04 21:01 UTC
Being able to declare separate readonly and writeonly interfaces that could be "joined" into a common read-write interface including **properties** and **indexers** would allow great interface designs.

``` C#
public interface IReadOnlyFoo<out T> {
    T Value { get; }
}

public interface IWriteOnlyFoo<in T> {
    T Value { set; }
}

// If you program against this interface, currently you get an "ambiguity" compiler error.
public interface IReadWriteFoo<T> : IReadOnlyFoo<T>, IWriteOnlyFoo<T> {
}

// This, however works:
public class ReadWriteFoo<T> : IReadOnlyFoo<T>, IWriteOnlyFoo<T> {
    T Value { get; set; } // Implements IReadOnlyFoo<T>.Value and IWriteOnlyFoo<T>.Value
}
```
**Note**: This would allow us to have a call-site variance by specifying either the Read or the Write interface.

**Comment by HaloFour** [comment] 2015-11-04 21:12
This is legal in C# 6.0/VS2015:

```cs
public interface IFoo<out T> {
    T Blah { get; }
}

public interface IBar<in T> {
    T Blah { set; }
}

public interface IFooBar<T> : IFoo<T>, IBar<T> {
    new T Blah { get; set; }
}

public class FooBar<T> : IFooBar<T>, IFoo<T>, IBar<T> {
    public T Blah { get; set; }
}
```

**Comment by svick** [comment] 2015-11-04 21:13
This already seems to work for me:

```c#
public class ReadWriteFoo<T> : IReadOnlyFoo<T>, IWriteOnlyFoo<T> {
    public T Value { get; set; }
}
```

In `IReadWriteFoo<T>`, you don't need to redeclare the property, just inheriting from the base interfaces is enough:

```c#
public interface IReadWriteFoo<T> : IReadOnlyFoo<T>, IWriteOnlyFoo<T> {
}

public class ReadWriteFoo<T> : IReadWriteFoo<T> {
    public T Value { get; set; }
}
```

**Comment by OJacot-Descombes** [comment] 2015-11-04 21:29
Ok, you are right. I was pretty sure that I had tried that earlier and that it didn't work. I was wrong. Sorry.

**Comment by OJacot-Descombes** [comment] 2015-11-04 21:38
I think that I closed to early.

```C#
    IReadWriteFoo<string> rw = new ReadWriteFoo<string>();
    rw.Value = "hello"; // ==> Ambiguity between ' IReadOnlyFoo<string>.Value and 
                        //        IWriteOnlyFoo<string> Value'
```

**Comment by HaloFour** [comment] 2015-11-04 21:46
It's interesting, if `IReadWriteFoo<T>` declares a shadowing property it works fine, but if it just "inherits" the members from `IReadOnlyFoo<T>` and `IWriteOnlyFoo<T>` it fails with the message that you're seeing.

**Comment by iskiselev** [comment] 2017-01-18 02:00
Looks like #14164 is duplicate of it, but this one is still in planning state, other one was closed with "Resolution-By Design" label.

**Comment by OJacot-Descombes** [comment] 2017-01-18 13:12
@iskiselev: The point of my issue is have a kind of  call-site variance by specifying either the Read or the Write interface.

**Comment by jcouv** [comment] 2017-10-22 05:30
Moving language design discussions to csharplang. Thanks

**Comment by jcouv** [comment] 2017-10-22 05:30
Issue moved to [dotnet/csharplang #1031](https://github.com/dotnet/csharplang/issues/1031) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jcouv** 2017-10-22 05:30 UTC
Labels: 1 - Planning, Area-Language Design
