### ISSUE TITLE
RegisterCompilationEndAction not getting called

### ISSUE THREAD

**Issue by bipinacellere** [dotnet/roslyn#47413] opened 2020-09-03 08:43 UTC
**Version Used**: 
3.7.0

**Steps to Reproduce**:

1. Using Visual Studios 2019 16.7.2 version.
2. Following code : 

```
public override void Initialize(AnalysisContext context)
{
         context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | 
                                                                                 GeneratedCodeAnalysisFlags.ReportDiagnostics);
            context.EnableConcurrentExecution();
            
            context.RegisterCompilationStartAction(ctx =>
            {
                var analyzerContext = new AnalyzerContext(ctx.Compilation);
                ctx.RegisterSymbolAction(analyzerContext.AnalyzeNamedTypeSymbol, SymbolKind.NamedType);
                ctx.RegisterCompilationEndAction(analyzerContext.AnalyzeCompilationEnd);
            });
}
.....
.....

.....
public void AnalyzeCompilationEnd(CompilationAnalysisContext context)
{
     ......
     ......
}
```
**Expected Behavior**:
AnalyzeCompilationEnd method should be called after Compilation End.

**Actual Behavior**:
AnalyzeCompilationEnd is never called.

**Comment by CyrusNajmabadi** [comment] 2020-09-03 23:37
Do you not get the call when running in the IDE?  Or do you not get it when running from teh command line?  If teh IDE, this is by design if "full solution analysis" is off.

**Comment by sharwell** [comment] 2020-09-04 00:08
Duplicate of #11750

**Closed** 2020-09-08 18:07 UTC
Labels: Area-Analyzers
