### ISSUE TITLE
Explicit interface implementation 'RefCustomModifiers' is not inherited

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#39167] opened 2019-10-09 22:01 UTC
https://github.com/dotnet/roslyn/blob/82f09c4e6067d3a164000f1acf355ee8e774fad5/src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderMethodSymbol.cs#L169-L178

**Comment by gafter** [comment] 2019-10-24 19:32
Can you please explain what "it" is in "it does not currently work", or otherwise elaborate on what the issue is?

**Comment by jcouv** [comment] 2021-02-09 23:06
@sharwell I'm able to remove this property/block from the code and still compile roslyn with `build.cmd`. So I think the issue is now fixed.
Can you confirm this was indeed the correct interpretation of the issue?

**Closed** 2021-08-03 11:37 UTC
Labels: Area-Compilers, Need More Info, New Language Feature - Nullable Reference Types
