### ISSUE TITLE
IntroduceVariableCodeRefactoringProvider ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn#32537] opened 2019-01-16 21:57 UTC
Type a space after the plus symbol then double click the mouse to cause ```IntroduceVariableCodeRefactoringProvider ArgumentOutOfRangeException : 'end' must not be less than 'start'.```

```csharp
namespace IntroduceVariableCodeRefactoringProvider_ArgumentOutOfRangeException
{
    public class Class
    {
        public string Test => "123" +
    }
}
```

I'm using Visual Studio 15.9.5.

**Comment by jinujoseph** [comment] 2019-01-17 18:04
@JoeRobich  dupe of https://github.com/dotnet/roslyn/issues/27949?

**Comment by JoeRobich** [comment] 2019-01-18 17:22
@jinujoseph Yes, this one is a duplicate.

**Closed by JoeRobich** 2019-01-18 17:22 UTC
Labels: Area-IDE, Bug
