### ISSUE TITLE
Compiler unable to figure out whether to use get or set accessor

### ISSUE THREAD

**Issue by lellid** [dotnet/roslyn#24215] opened 2018-01-12 22:34 UTC
**Version Used**:  Visual Studio Community 15.5.3

**Steps to Reproduce**:
Consider the following code:
````
        public interface IROClass
	{
		string Name { get; }
	}

	public interface IWOClass
	{
		string Name { set; }
	}

	public interface IRWClass : IROClass, IWOClass
	{
	}

	public class RWClassImpl : IRWClass
	{
		public string Name { get; set; }
	}

	public class UseCase
	{
		public void Test1_DoesCompile()
		{
			var rw = new RWClassImpl();
			rw.Name = "Foo";
			var name = rw.Name;
		}

		public void Test2_DoesNotCompile()
		{
			IRWClass rw = new RWClassImpl();
			rw.Name = "Foo"; // Compiler error: Ambiguity between IROClass.Name and IWOClass.Name
			var name = rw.Name; // Compiler error: Ambiguity between IROClass.Name and IWOClass.Name
		}
        }
````

**Expected Behavior**:
Test2 should compile.
In Test2, the compiler should be able to figure out to use interface IWOClass when making the assignment to 'rw.Name'. And when accessing 'rw.Name', it should be able to figure out to use IROClass  interface. There is no ambiguity between IROClass.Name and IWOClass.Name since IROClass.Name has only a get accessor and IWOClass.Name has only a set accessor.

**Actual Behavior**:
Test1 can be compiled, whereas Test2 fails to compile.

**Comment by jcouv** [comment] 2018-01-16 08:30
I believe this is by design. The ambiguity is not between accessors, but between properties. There are two properties of the same name which could be referenced by `rw.Name`.
I don't think the context (whether that member is accessed for reading or writing) comes into account to disambiguite which member you mean.

**Comment by jcouv** [comment] 2018-03-15 20:29
Closing as by-design.
If you have an idea how to improve the language design for this, please open a language proposal in the csharplang repo. Thanks

**Closed by jcouv** 2018-03-15 20:29 UTC
Labels: Area-Compilers, Resolution-By Design
