### ISSUE TITLE
[CallerArgumentExpression] attribute works with any language version, changing behavior of existing code on compiler update

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#55695] opened 2021-08-18 13:08 UTC
**Version Used**: 
```
Microsoft Visual Studio Professional 2019
Version 16.11.0
VisualStudio.16.Release/16.11.0+31605.320
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:

Compile and run the code below with the following configuration:
```
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>4</LangVersion>
```

The code:
```cs
using System;
using System.Runtime.CompilerServices;

class C
{
  static void Main(string[] args)
  {
    var res = new C().M1("nameArgument");
    Console.WriteLine(res);
  }

  public string M1(string name = null, [CallerArgumentExpression("name")] string arg = null)
  {
    return arg;
  }
}
```

**Expected Behavior**:
An empty line is printed

**Actual Behavior**:
`"nameArgument"` is printed

**Notes**:
I'm not really sure if this is expected or not, but it looks worrisome that updating a minor VS version without changing the language level or target framework of your project can change the behavior of your code. I'd expect the change in behavior to be gated by the new language version

**Comment by Youssef1313** [comment] 2021-08-18 15:43
From the test plan: https://github.com/dotnet/roslyn/issues/52745

> LangVersion - No lang version impact for caller info attributes.

Commit where the behavior was changed: https://github.com/dotnet/roslyn/pull/54839/commits/f22bb4c99fce35dbf8cf76f1ac6870bb94c5e895

**Comment by TessenR** [comment] 2021-08-18 21:19
So this is expected and works as intended then? I guess it could be closed as by design in this case

**Comment by Youssef1313** [comment] 2021-08-18 21:33
I'd like to hear from @333fred or @jcouv before closing. Especially that in the very initial reviews, @AlekseyTs expressed interest in having an error if the feature is used on previous language versions (only on callsites where the compiler does an actual binding, not declarations).

**Comment by 333fred** [comment] 2021-08-18 22:34
Yes, this is expected behavior. We don't gate any of the CallerInfo attributes on langversion, even though the others were technically introduced in either C# 5 or 6 (if I'm remembering correctly).

**Comment by 333fred** [comment] 2021-08-18 22:36
As to the behavior change, we did think about that, especially because the attribute already existed in the BCL. However, the extreme likelihood is that the change is what the user was originally hoping to have happen, so we considered it fine.

**Comment by jcouv** [comment] 2021-08-19 02:54
Closing as by-design. Thanks

**Closed by jcouv** 2021-08-19 02:54 UTC
Labels: Area-Compilers, Resolution-By Design
