### ISSUE TITLE
CSharpUseImplicitTypeDiagnosticAnalyzer crashes on `ref var`

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#25063] opened 2018-02-26 21:41 UTC
Sample code:

```C#
int i = 0;
ref var y = ref i;
```

This causes the CSharpUseImplicitTypeDiagnosticAnalyzer to crash due to a null ref exception.

**Comment by agocke** [comment] 2018-03-10 00:56
cc @jinujoseph for triage. As we expand the capabilities of ref variables more, this may become more important to fix.

**Comment by Neme12** [comment] 2018-03-12 17:20
I can't reproduce this on 15.6.1

**Comment by jcouv** [comment] 2018-05-31 20:20
Fixed in https://github.com/dotnet/roslyn/pull/27246

**Closed by jcouv** 2018-05-31 20:20 UTC
Labels: Area-IDE, Bug, help wanted
