### ISSUE TITLE
Enum preselection broken.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15090] opened 2016-11-08 18:43 UTC
![image](https://cloud.githubusercontent.com/assets/4564579/20112166/1ac325d8-a5a0-11e6-822e-5f582c80cbca.png)

After hitting space after the ```==``` 'WaitIndicatorResult' should be selected.  Instead, we've preferred a local parameter.  Specifically teh local parameter i'm already checking :(

**Comment by CyrusNajmabadi** [comment] 2016-11-08 19:02
tagging @rchande

**Comment by Pilchie** [comment] 2016-11-14 23:29
Another duplicate of https://github.com/dotnet/roslyn/issues/14813?

**Closed by Pilchie** 2016-11-14 23:29 UTC
Labels: Area-IDE, Bug
