### ISSUE TITLE
Difficult to distinguish Error from Disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#1405] opened 2015-03-20 01:49 UTC
Quick, find the error(s):

I recommend changing the disabled glyph to gray at minimum. They certainly shouldn't stand out.

![image](https://cloud.githubusercontent.com/assets/1408396/6744563/37222760-ce79-11e4-83e8-46766bb9999f.png)

**Comment by srivatsn** [comment] 2015-03-20 04:14
All of the glyphs have been made gray to be consistent with other icons. We got feedback that people thought there was actually an error in solution explorer instead of denoting an error severity. So the icons have been made to stand out less.

**Comment by srivatsn** [comment] 2015-03-26 23:41
This issue itself is not fixed but is different now - i dont think the new icons make it easy to distinguish either and #1412 tracks figuring that out. I'll resolve this as a duplicate of that issue.

**Closed by srivatsn** 2015-03-26 23:41 UTC
Labels: Area-Analyzers
