### ISSUE TITLE
Bug with pointer to array (unsafer unsafeness)

### ISSUE THREAD

**Issue by hamarb123** [dotnet/roslyn#65529] opened 2022-11-20 22:27 UTC
**Version Used**: SDK 7.0.100 in VS 17.4.0

**Steps to Reproduce**:

As a part of the unsafer unsafeness in C# 11, it seems that we can now take pointers to objects like so:
```csharp
object o = new();
object* ptr = &o;
```

But it seems like it doesn't work properly for array types:
```csharp
string[] arr = new string[0];
string[]* ptr1 = &arr; //doesn't work
var ptr2 = &arr; //works
```

VS even seems to think this should be possible:
![image](https://user-images.githubusercontent.com/25316035/202929465-d6ffd653-ddd8-473f-b020-0cb87826f4fb.png)

In case it isn't clear why this is an issue: the reason this would be an issue is you wouldn't be able to cast another pointer to this type, or specify a parameter of this type.

**Expected Behavior**:

Code should compile with warnings.

**Actual Behavior**:

`ptr1` gets a nonsense error that is unrelated to the issue:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/25316035/202929548-e1613f84-49b1-45ea-bdbd-ce792d9739af.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/25316035/202929560-4108671e-adc4-4f2a-8c75-9de350f8a619.png">

Originally reported [here](https://github.com/dotnet/csharplang/discussions/6692)

**Comment by 333fred** [comment] 2022-11-20 22:35
Duplicate of https://github.com/dotnet/roslyn/issues/65429.

**Closed by 333fred** 2022-11-20 22:35 UTC
Labels: Area-Compilers, untriaged
