### ISSUE TITLE
Generic Attribute not possible when passing on generic type

### ISSUE THREAD

**Issue by R0boC0p** [dotnet/roslyn#67569] opened 2023-03-30 07:15 UTC
Hi guys,
.net 7 provides generic Attributes, which works as expected. But if you are passing on a generic type from a wrapping class, it shows a `CS8968` compiler error. I wonder if you can help me here.
Thanks a lot in advance.

**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.3
.net core: 7.0.202

**Steps to Reproduce**:

1.  Create a generic class derived from `Attribute`.
2.  Create another generic class.
3.  Use the type of the attribute within the previously created class, using its generic parameter.

```c#
public class ReproAttribute<T> : Attribute { }

public class Repro<T>
{
    [Repro<T>]
    public string Test { get; set; }
}
```

**Expected Behavior**:

Generic attribute to work inside a generic class like it would in global scope.

**Actual Behavior**:

CS8968: 'T' an attribute type argument cannot use type parameters.

**Comment by ufcpp** [comment] 2023-03-30 07:35
You should suggest to [csharplang](https://github.com/dotnet/csharplang) because this is by design so far. Also, there is a runtime limitation, so a suggestion to [runtime](https://github.com/dotnet/runtime/) is also needed.

Proposal issue: https://github.com/dotnet/csharplang/issues/124

**Comment by jcouv** [comment] 2023-04-14 17:49
Thanks @ufcpp. This limitation is indeed by-design at the moment. Closing as such

**Closed by jcouv** 2023-04-14 17:49 UTC
Labels: Area-Compilers, untriaged
