### ISSUE TITLE
Code editor stop working when primitive type in lambda parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60164] opened 2022-03-14 19:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-editor-stop-working-when-primitive-/1689356)._

---
This simple (invalid) code confuse the editor, all code becomes white.
Any primitive types as lambda parameter cause this.

```cs
public class TestClass
{
    public void TestMethod()
    {
        TestMethod(int => );
    }
}
```

Reproduced by my colleague.

---
#### Feedback Bot on 3/10/2022, 06:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2022-03-14 19:40
Yes.  this is pretty much 'by design' wrt intellisense.  THe above is entirely illegal code.  The parser likely goes entirely off the rails after `int` here.  If we get the parser to be better here (perhaps by pretending this was like `@int =>` or perhaps `(int) => ` 
 (also illegal, but likely better recovery) then things will be *slightly* better.

**Comment by jinujoseph** [comment] 2022-03-22 17:15
Probably dupe of #59756

**Comment by jcouv** [comment] 2022-04-15 08:04
Closing as duplicate of https://github.com/dotnet/roslyn/issues/59756 (parsing and error recovery of incomplete lambda)

**Closed by jcouv** 2022-04-15 08:04 UTC
Labels: Area-Compilers, Concept-Diagnostic Clarity, Developer Community
