### ISSUE TITLE
Record in metadata shouldn't be "a class"

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#50465] opened 2021-01-14 13:07 UTC
**Version Used**: 
VS 16.9 Preview 2

**Steps to Reproduce**:

1. Type code to create a record type:
```csharp
public sealed record R(int Prop1, string Prop2);
```

2. Compile it to a `dll` file.
3. Create a project that references to that `dll` file.
4. Test code like:
```csharp
var r = new R(20, "Hello");
```

5. Ctrl+Click the token `R` or press F12.
6. The metadata displays, but `R` shows as a normal class, with a clone method called `<Clone>$`.

**Snapshot**:

![Shapshot](https://user-images.githubusercontent.com/23616315/104594393-0e58db00-56ac-11eb-9be1-8fa59bd7a5ee.png)

**Expected Behavior**:

The metadata should display record as "a record", not "a class".

**Actual Behavior**:

```csharp
#nullable enable

using System;

namespace RecordTester
{
    public sealed class R : IEquatable<R>
    {
        public R(int Prop1, string Prop2);

        public int Prop1 { get; init; }
        public string Prop2 { get; init; }

        public R <Clone>$();
        public void Deconstruct(out int Prop1, out string Prop2);
        public override bool Equals(object? obj);
        public bool Equals(R? other);
        public override int GetHashCode();
#nullable disable
        public override string ToString();

#nullable enable
        public static bool operator ==(R? r1, R? r2);
        public static bool operator !=(R? r1, R? r2);
    }
}
```

**Comment by jinujoseph** [comment] 2021-01-19 21:14
Duplicate of #44566

**Closed by jinujoseph** 2021-01-19 21:14 UTC
Labels: Area-IDE
