### ISSUE TITLE
DocumentId is changing in newly added Document after workspace applies changes

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#36501] opened 2019-06-17 09:03 UTC
**Version Used**: 
It happens in VS2019, it does not happen in VS2017

**Steps to Reproduce**:

1.  Try to run this example:
```
using System.Collections.Generic;
using System.Composition;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeRefactorings;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Simplification;
using Microsoft.CodeAnalysis.Text;

namespace ImplementNotifyPropertyChangedCS {
    [ExportCodeRefactoringProvider(LanguageNames.CSharp, Name = "SampleRefactoring"), Shared]
    internal partial class SampleCodeRefactoringProvider : CodeRefactoringProvider {
        public sealed override Task ComputeRefactoringsAsync(CodeRefactoringContext context) {
            Document document = context.Document;
            CancellationToken cancellationToken = context.CancellationToken;
            CodeAction action = CodeAction.Create(
                "Sample Refactoring",
                c => ExecuteAsync(document, c),
                equivalenceKey: nameof(SampleCodeRefactoringProvider));

            context.RegisterRefactoring(action);
            return Task.CompletedTask;
        }

        private async Task<Document> ExecuteAsync(Document document, CancellationToken cancellationToken) {
            var code = @"using System;
namespace SampleRefactoring
{
    public class SampleClass
    {
    }
}";
            var newDocument = document.Project.AddDocument("SampleClass.cs", SourceText.From(code));
            var documentId = newDocument.Id;
            newDocument = await Formatter.FormatAsync(newDocument, Formatter.Annotation, cancellationToken: cancellationToken).ConfigureAwait(false);
            await Application.Current.Dispatcher.InvokeAsync(() => {
                var workspace = document.Project.Solution.Workspace;
                workspace.TryApplyChanges(newDocument.Project.Solution);
                var addedDocument = workspace.CurrentSolution.GetDocument(documentId);
                Debug.Assert(addedDocument != null);
            });
            return document;
        }
    }
}
```

**Expected Behavior**:
addedDocument is not null

**Actual Behavior**:
addedDocument is null. There is proper document in the solution, but it has different DocumentId

**Comment by jasonmalinowski** [comment] 2019-06-19 20:53
Duplicate of #35531.

**Closed by jasonmalinowski** 2019-06-19 20:53 UTC
Labels: Area-IDE, Bug, IDE-Project
