### ISSUE TITLE
Create MetadataReference to assembly in ASP.NET 5

### ISSUE THREAD

**Issue by jamesgaunt** [dotnet/roslyn#861] opened 2015-02-25 17:22 UTC
I'm trying to create an ASP.NET 5 application which uses Roslyn, and references one of the project assemblies.

If I just create a ASP.NET Web Application (or Console Application), and reference Microsoft.CodeAnalysis, then the following code throws a System.ArgumentException: Empty path name is not legal.

            MetadataReference.CreateFromAssembly(this.GetType().Assembly);

Stepping into the code confirms that Assembly.Path == String.Empty. The CreateFromAssembly method is looking for the assembly to have a Path here:

http://source.roslyn.io/#Microsoft.CodeAnalysis/MetadataReference/MetadataReference.cs,297

I'm assuming the issue is due to the ASP.NET 5 build system building the Assembly in memory and not writing to disc.

Everything works if a project is published with the precompile option, and then deployed, but it prevents the project being run locally or use of the Ctrl-F5 / live rebuild feature.

**Comment by tmat** [comment] 2015-02-25 17:30
We don't support referencing in-memory assemblies right now.

**Comment by tmat** [comment] 2015-02-25 17:36
I have filed issue 862 to track this feature request.

**Comment by davidfowl** [comment] 2015-02-25 17:44
@jamesgaunt ASP.NET 5 has an API for this. You can do what Razor does https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L132

**Comment by jamesgaunt** [comment] 2015-02-25 17:48
@davidfowl that is fantastic!  Thank you very much.

**Comment by theoy** [comment] 2015-03-05 22:05
Considering this a dupe of #862.

**Closed by theoy** 2015-03-05 22:05 UTC
Labels: Area-Compilers, Bug, Portability
