### ISSUE TITLE
CodeRefactoringService IntroduceVariable fails with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#39293] opened 2019-10-15 17:59 UTC
**Version Used**: 
Version 16.4.0 Preview 3.0 [29409.185.master]

![image](https://user-images.githubusercontent.com/41759/66856739-b5dfde80-ef3a-11e9-8a5a-28f9e7a0654c.png)

while editing `src\EditorFeatures\Test\EditAndContinue\EditAndContinueWorkspaceServiceTests.cs` in Roslyn.sln.

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position,Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.CodeRefactoringHelpers.IsNodeUnderselected(SyntaxNode node,TextSpan selection)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.TryInitializeAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.GenerateAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2019-10-15 18:38
@petrroll Already fixed?

**Comment by petrroll** [comment] 2019-10-15 18:47
Should be fixed by https://github.com/dotnet/roslyn/pull/39091

**Comment by jinujoseph** [comment] 2019-10-15 19:30
Duplicate of #38708

**Closed by jinujoseph** 2019-10-15 19:30 UTC
Labels: Area-IDE, Resolution-Duplicate
