### ISSUE TITLE
Lifted operators on nullable types should affect null-state warning

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#31863] opened 2018-12-17 16:45 UTC
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:

```C#
using System;

class C
{
    public C()
    {
        DateTime? dt = null;
        DateTime latest = DateTime.UtcNow;

        if (dt > latest)
        {
            Console.WriteLine(dt.Value);
        }
    }
}
```

**Expected Behavior**:
No warning.

**Actual Behavior**:
Warning on the `.Value`.

**Comment by Suchiman** [comment] 2018-12-26 20:49
Similiar case

**Version Used**: 2019P1

**Steps to Reproduce**:

```csharp
using System;

public class C
{
    public void M(string[]? test)
    {
        if (test?.Length > 0)
        {
            Console.WriteLine(test[0]);
        }
    }
}
```

**Expected Behavior**:
No warning.

**Actual Behavior**:
Warning on `test[0]`.

**Comment by jaredpar** [comment] 2019-01-02 18:30
Thanks for filing. Looks like a dupe of #31500 (@cston).

**Closed by jaredpar** 2019-01-02 18:30 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types
