### ISSUE TITLE
Roslyn doesn't update inferred nullable annotations for fields with type parameters on subsequent data flow passes

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#33295] opened 2019-02-11 17:40 UTC
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.1
VisualStudio.16.Preview/16.0.0-pre.2.1+28529.54
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
class C<T>
{
  public T FieldWithInferredAnnotation;
}
class C
{
  static void Main()
  {
    Test(null);
  }

  static void Test(string? s)
  {
    s = "";
    hell:
    var c = GetC(s);
    c.FieldWithInferredAnnotation.ToString();
    s = null;
    goto hell;
  }

  public static C<T> GetC<T>(T t) => new C<T> { FieldWithInferredAnnotation = t };
  public static T GetT<T>(T t) => t;
}
```

**Expected Behavior**:
Warning `CS8602 Possible dereference of a null reference.` for the line 
`c.FieldWithInferredAnnotation.ToString();` since on the second pass the type of `c` should be inferred to be `C<string?>` and its `FieldWithInferredAnnotation` should be recognized as nullable.

**Actual Behavior**:
No warnings. The program crashes with a `NullReferenceException` at the line `c.FieldWithInferredAnnotation.ToString();`

**Notes**
Roslyn correctly updates nullability of local variables in similar scenarios but fails when type arguments are used in the target types' fields or properties.
I.e. the following code correctly reports CS8602:

```cs
class C
{
  static void Test(string? s)
  {
    s = "";
    hell:
    var t = GetT(s);
    t.ToString(); // CS8602
    s = null;
    goto hell;
  }

  public static T GetT<T>(T t) => t;
}
```

**Comment by TessenR** [comment] 2019-02-11 19:56
Interestingly enough it looks like some warnings are affected by the changes of inferred type arguments' nullability and some aren't. In the following example CS8625 warning correctly disappears because the field becomes nullable in the first test (with `goto`) but CS8602 does not appear.

```cs
#nullable enable
class C<T>
{
  public T FieldWithInferredAnnotation;
}
class C
{
  static void Test1(string? s)
  {
    s = "";
    hell:
    var c = GetC(s);
    c.FieldWithInferredAnnotation.ToString(); // no warnings, should be CS8602
    c.FieldWithInferredAnnotation = null; // no warnings
    s = null;
    goto hell;
  }

  
  static void Test2(string? s)
  {
    s = "";
    hell:
    var c = GetC(s);
    c.FieldWithInferredAnnotation.ToString(); // no warnings, correct
    c.FieldWithInferredAnnotation = null; // CS8625
    s = null;
    //goto hell;
  }

  public static C<T> GetC<T>(T t) => new C<T> { FieldWithInferredAnnotation = t };
}
```

**Comment by jaredpar** [comment] 2021-02-10 16:12
Looks like this is fixed now. Adding a regression test.

**Closed** 2021-02-10 23:41 UTC
Labels: Area-Compilers, Bug, New Language Feature - Nullable Reference Types
