### ISSUE TITLE
Explicit interface declaration implementation on nullable types, it FAILS!!!

### ISSUE THREAD

**Issue by ArsalanImamverdi** [dotnet/roslyn#70958] opened 2023-11-24 16:46 UTC
### Describe the bug
When explicitly implement an interface declaration with nullable type, the compiler gives an error which the `explicit interface declaration is not found among members of the interface that can be implemented`!

### To Reproduce

```
 public interface ISomeInterface
 {
     T? Get<T>();
     Task<T?> GetAsync<T>();

     T OtherGet<T>();
     Task<T> OtherGetAsync<T>();
 }

 public class SomeClass : ISomeInterface
 {
     T? ISomeInterface.Get<T>() // there is an error here
     {
         throw new NotImplementedException();
     }

     Task<T?> ISomeInterface.GetAsync<T>() // there is an error here
     {
         throw new NotImplementedException();
     }

     T ISomeInterface.OtherGet<T>() // there is NO error here
     {
         throw new NotImplementedException();
     }

     Task<T> ISomeInterface.OtherGetAsync<T>() // there is NO error here
     {
         throw new NotImplementedException();
     }
 }
```

### Further technical details
The dotnet version : 
```
dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.23536
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.125 [C:\Program Files\dotnet\sdk]
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.103 [C:\Program Files\dotnet\sdk]
  7.0.311 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Visual studio version:
```
Microsoft Visual Studio Enterprise 2022
Version 17.9.0 Preview 1.0
VisualStudio.17.Preview/17.9.0-pre.1.0+34310.174
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00482-10000-00261-AA909
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.101.55877
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.101.55877
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.101.55877
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23293.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.50908.1 Commit Hash:c294679b821c4b8f7f9c6db3827b7655db80fc28
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34217.00
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.23293.1
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.23293.1
Profiling support for Python projects.

Python with Pylance   17.0.23293.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.9.1.2355806+8f4bea9f2567429c455f24b09d37645f022bbcbd
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.7.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.21025.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23523.7+0c5e24d19dc915b00b8755a8532bfb2582aa2b47
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
```

**Comment by CyrusNajmabadi** [comment] 2023-11-24 20:54
Closing out.  This is by design.  Compiler doesn't know what the constraints are on T and has to deal with it potentially being a nullable value type or nullable reference type.  The way to implement this is like so (which the IDE will also do for you):

```c#
class C : ISomeInterface
{
    T? ISomeInterface.Get<T>() where T : default
    {
        throw new NotImplementedException();
    }

    Task<T?> ISomeInterface.GetAsync<T>() where T : default
    {
        throw new NotImplementedException();
    }

    T ISomeInterface.OtherGet<T>()
    {
        throw new NotImplementedException();
    }

    Task<T> ISomeInterface.OtherGetAsync<T>()
    {
        throw new NotImplementedException();
    }
}
```

**Closed by CyrusNajmabadi** 2023-11-24 20:54 UTC
Labels: Area-Compilers, untriaged
