### ISSUE TITLE
OutliningTagger test failed in signed build

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#21326] opened 2017-08-04 20:23 UTC
See https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=903861

Failure traces:

```
    Microsoft.CodeAnalysis.Editor.UnitTests.Structure.StructureTaggerTests.CSharpOutliningTagger_RegionIsDefinition
      System.Reflection.TargetParameterCountException : Parameter count mismatch.
      Stack Trace:
           at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Delegate.DynamicInvokeImpl(Object[] args)
           at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
           at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
           at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Windows.Threading.DispatcherOperation.Invoke()
           at System.Windows.Threading.Dispatcher.ProcessQueue()
           at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
           at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
           at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
           at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
           at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
           at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
           at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
           at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
           at Roslyn.Test.Utilities.DispatcherExtensions.DoEvents(Dispatcher dispatcher)
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        src\EditorFeatures\Test\Structure\StructureTaggerTests.cs(64,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Structure.StructureTaggerTests.<CSharpOutliningTagger_RegionIsDefinition>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Pilchie** [comment] 2017-08-08 21:29
@jasonmalinowski you saw this once on Jenkins, right?  Did you make any progress identifying what went wrong?

**Comment by jasonmalinowski** [comment] 2017-08-08 21:47
No, we didn't. 😦

**Comment by 333fred** [comment] 2017-08-15 17:18
Dupe of https://github.com/dotnet/roslyn/issues/20106.

**Comment by jasonmalinowski** [comment] 2017-08-15 17:45
@333fred I believe these are distinct issues.

**Comment by 333fred** [comment] 2018-03-15 20:05
Failed here: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.6.x-vs-deps/job/windows_release_unit32/39/

**Comment by jasonmalinowski** [comment] 2019-01-16 22:50
Going to close old flaky test bugs and we'll reactivate as they appear.

**Closed by jasonmalinowski** 2019-01-16 22:50 UTC
Labels: Area-IDE, Flaky, Test
