### ISSUE TITLE
Can Visual Studio customize the development code?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46270] opened 2020-07-23 20:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1123102/can-visual-studio-customize-the-development-code.html)._

---
<p> I only speak Chinese, not English, translated </p><p> I will only Chinese, English will not, please translate to see </p><p></p><p> Can I customize the development of the </p>. Can <p> customize the rollout code? </p><p></p><p>.
I hope to develop the book this, Please see the picture below</p><p> I hope to be able to collect the code like this, please see the following figure </p><p>&quot; https://developercommunityapi.westuscloudapp.azure.com/storage/attachments/147673-qq screenshot 2020073123023025.png.</a></p>

---
#### Feedback Bot on 7/22/2020, 10:58 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment] 2020-07-28 19:24
@genlu Can you take a look at the issue and screenshot? My hypothesis is this is a duplicate of #37575 but it would be good if you could confirm this.

**Comment by mikadumont** [comment] 2020-07-28 19:27
The customer would like #Region to be customized to their language: 

![image](https://user-images.githubusercontent.com/46729679/88711780-89621100-d0cd-11ea-8d33-efc69a73693e.png)

**Comment by genlu** [comment] 2020-07-28 20:38
I'm not sure exact what the ask is, as far as I can see, this is how it works today

![image](https://user-images.githubusercontent.com/788783/88719134-a7cd0a00-d0d7-11ea-8d4a-e9fbe406c90d.png)


here's the direct translation:

Can I customize how the code block expand/collapse works? I want to collapse code block like this (see the screenshot)

**Comment by hnpvqve** [comment] 2020-08-11 13:41
@sharwell @mikadumont 

我希望可以作在select case 中进行收展，因为select case 中的代码很长，导致我无法更好的预览或定位。
I hope it can be developed in the select case, because the code in the select case is very long, which prevents me from previewing or positioning better.

**Closed** 2021-09-15 23:03 UTC
Labels: Area-IDE, Feature Request, Need More Info, fabric-bot-test
