### ISSUE TITLE
Inline functions that are iterators are erroneously not allowed in try blocks with a catch clause

### ISSUE THREAD

**Issue by marklio** [dotnet/roslyn#24102] opened 2018-01-08 18:41 UTC
**Version Used**: 

**Steps to Reproduce**:

1. Compile the following console app:

```C#
using System;
using System.Collections.Generic;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                IEnumerable<string> Foo() // CS1626: Cannot yield a value in the body of a try block with a catch clause
                {
                    yield return "bar";
                }
                foreach (var s in Foo())
                {
                    Console.WriteLine(s);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

**Expected Behavior**:
Successful compile and an app that prints "bar" to stdout.

**Actual Behavior**:
CS1626: Cannot yield a value in the body of a try block with a catch clause

It would seem that perhaps the rule is looking at the wrong scope to determine whether yield return is allowed. Moving the definition outside the try works, but might not be possible in some cases due to captured state if the function is more complicated.

**Comment by jcouv** [comment] 2018-01-16 08:34
Assigning to @t-camaia, since the issue is closely related to one he's currently working on (https://github.com/dotnet/roslyn/issues/18644).
FYI @agocke @jaredpar

**Comment by jcouv** [comment] 2018-01-22 21:59
Closing the issue on behalf of @t-camaia 
The fix was merged to `features/compiler` which will likely ship in 15.7.

**Closed by jcouv** 2018-01-22 21:59 UTC
Labels: Area-Compilers, Bug, New Language Feature - Local Functions
