### ISSUE TITLE
Short cut CTRL+K+D Clean references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37008] opened 2019-07-05 18:59 UTC
Was implemented a feature to clear (not used) references when input Ctrl+K+D. But when i have a &quot;#if DEBUG&quot;, it cleaned All used  references on release mode.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/631890/short-cut-ctrlkd-clean-references.html
VSTS ticketId: 941886_
_These are the original issue comments:_

Visual Studio Feedback System on 7/4/2019, 01:04 AM (34 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-07-10 22:52
Duplicate of #35559

**Closed by sharwell** 2019-07-10 22:52 UTC
Labels: Area-IDE, Developer Community

**Comment by sharwell** [comment] 2019-07-11 00:33
Duplicate of #24084
