### ISSUE TITLE
Changing the severity of an analyzer from the editor lightbulb doesn't update the EditorConfig unless the EditorConfig is open

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#53488] opened 2021-05-18 17:03 UTC
**Version Used**: 
VS 2019 16.10 Preview 2

**Steps to Reproduce**:
1. Selecting the lightbulb from the editor to configure the severity of an analyzer doesn't update the severity level in the editor or update the new severity level in my EditorConfig:

![image](https://user-images.githubusercontent.com/46729679/118693371-dda2c280-b7bf-11eb-8761-3c05f2a44139.png)

2. Selecting the lightbulb from the editor to configure the severity of an analyzer will only update the severity level in the editor and in my EditorConfig file only if my EditorConfig file is open.

**Comment by sharwell** [comment] 2021-05-18 17:11
Duplicate of #45417

**Comment by sharwell** [comment] 2021-05-18 17:11
📝 The feature works with the file closed, but only if the file is part of the solution somewhere (either in a project, or in a Solution Folder).

**Closed by sharwell** 2021-05-18 17:11 UTC
Labels: Area-IDE, untriaged
