### ISSUE TITLE
Use inference for part of non inferable generic arguments only

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#6207] opened 2015-10-21 07:03 UTC
When we have a method like this:

``` cs
void Foo<T1, T2, T3, T4>(T1 t1, T2 t2, T3 t3, T4 t4)
{
}
```

It's great that the compiler can infer generic arguments from the call.

But when one generic argument cannot be inferred, we need to specify all.

It would be great to have a way to specify only generic arguments that cannot be inferred.

Ex:

``` cs
void Foo<T1, T2, T3, T4, TResult>(T1 t1, T2 t2, T3 t3, T4 t4)
{
}

Foo<TResult:int>(0, 0, 0, 0);
```

**Comment by tpetrina** [comment] 2015-10-21 14:27
I second this. It would be great if we could specify non-inferrable generic arguments similar to optional parameters for functions.

**Comment by alrz** [comment] 2015-10-22 19:00
Duplicate of #6114

**Comment by gafter** [comment] 2015-10-29 17:29
> Duplicate of #6114

#6114 appears to be about "inferring" type parameters at a declaration site. This is about specifying only uninferred type arguments at a use site.

**Comment by alrz** [comment] 2015-10-29 17:33
When I wrote that comment the first example was
>```
void Foo(T1 t1, T2 t2, T3 t3, T4 t4)
{
}
```
I have no idea.

**Comment by gafter** [comment] 2017-03-23 21:50
We are now taking language feature discussion in other repositories:
- https://github.com/dotnet/csharplang for C# specific issues
- https://github.com/dotnet/vblang for VB-specific features
- https://github.com/dotnet/csharplang for features that affect both languages

Features that are under active design or development, or which are "championed" by someone on the language design team, have already been moved either as issues or as checked-in design documents. For example, the proposal in this repo "Proposal: Partial interface implementation a.k.a. Traits" (issue 16139 and a few other issues that request the same thing) are now tracked by the language team at issue 52 in https://github.com/dotnet/csharplang/issues, and there is a draft spec at https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md and further discussion at issue 288 in https://github.com/dotnet/csharplang/issues. Prototyping of the compiler portion of language features is still tracked here; see, for example, https://github.com/dotnet/roslyn/tree/features/DefaultInterfaceImplementation and issue 17952.

In order to facilitate that transition, we have started closing the least recently active language design discussions from [the roslyn repo](https://github.com/dotnet/roslyn) with a note briefly explaining why. When we are aware of an existing discussion for the feature already in the new repo, we are adding a link to that. But we're not adding new issues to the new repos for existing discussions in this repo that the language design team does not currently envision taking on. Our intent is to eventually close the language design issues in the Roslyn repo and encourage discussion in one of the new repos instead.

Our intent is not to shut down discussion on language design - you can still continue discussion on the closed issues if you want - but rather we would like to encourage people to move discussion to where we are more likely to be paying attention (the new repo), or to abandon discussions that are no longer of interest to you.

If you happen to notice that one of the closed issues has a relevant issue in the new repo, and we have not added a link to the new issue, we would appreciate you providing a link from the old to the new discussion. That way people who are still interested in the discussion can start paying attention to the new issue.

Also, we'd welcome any ideas you might have on how we could better manage the transition. Comments and discussion about closing and/or moving issues should be directed to https://github.com/dotnet/roslyn/issues/18002. Comments and discussion about this issue can take place here or on an issue in the relevant repo.

This may be close enough to https://github.com/dotnet/csharplang/issues/280 that discussion can continue there.

**Closed by gafter** 2017-03-23 21:50 UTC
Labels: 0 - Backlog, Area-Language Design, Feature Request
