### ISSUE TITLE
High CPU in ComputeAnalyzerDiagnosticsAsync

### ISSUE THREAD

**Issue by dennis-yemelyanov** [dotnet/roslyn#40194] opened 2019-12-06 00:52 UTC
When building code using an external build system devenv.exe (Visual Studio 2019 16.3.4) CPU becomes abnormally high (while the VS window itself is minimized and should be idle). Looks like most of the time is spent in some code analysis-related methods starting with `ComputeAnalyzerDiagnosticsAsync`.

I'm not sure what's triggering this analysis, is it possible that some file changes or other disk acticity cause Visual Studio to run it?

It's not clear which public method invokes `ComputeAnalyzerDiagnosticsAsync`, but it looks like some of the public methods that do are obsolete with the following message: "This API was found to have performance issues and hence has been deprecated. Instead, invoke the API 'GetAnalysisResultAsync' and access the property 'CompilationDiagnostics' on the returned 'AnalysisResult' to fetch the compilation diagnostics."

Is it possible that Visual Studio is still calling one of the obsolete methods?

And, finally, is there some config to disable all code analysis for all projects at once?

![image](https://user-images.githubusercontent.com/10681271/70286237-4db1ba00-177f-11ea-9f1e-97d381cf6032.png)

**Comment by mavasani** [comment] 2019-12-11 14:42
> Is it possible that Visual Studio is still calling one of the obsolete methods?

None of the obsolete method in [CompilationWithAnalyzers](http://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,7efdf3edc21e904a) are invoked within Visual Studio or the compiler layer.

> When building code using an external build system devenv.exe (Visual Studio 2019 16.3.4) CPU becomes abnormally high (while the VS window itself is minimized and should be idle). Looks like most of the time is spent in some code analysis-related methods starting with ComputeAnalyzerDiagnosticsAsync

Performance of analyzer execution will depend on the installed analyzers. `ComputeAnalyzerDiagnosticsAsync` is the core method that invokes analyzer callbacks, so it is not possible to just look at performance data showing this method on the stacks. I would recommend you either provide a repro project OR collect a performance trace following the steps at http://aka.ms/reportPerf.

> And, finally, is there some config to disable all code analysis for all projects at once?

Yes, support has been just added, which should be available in VS2019 16.5 Preview2 and later: https://github.com/dotnet/roslyn/issues/24513#issuecomment-556406880

**Comment by mavasani** [comment] 2020-01-06 19:53
Closing this issue, pending additional performance data indicating the issue is with the analyzer driver and not specific analyzer(s).

**Closed by mavasani** 2020-01-06 19:53 UTC
Labels: Area-Analyzers, Need More Info
