### ISSUE TITLE
Editor CommandExecutionContext doesn't properly support progress.  It is also not threadsafe.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28354] opened 2018-07-07 03:47 UTC
Related issue: https://github.com/dotnet/roslyn/issues/28032 (cancelling an editor context can tear down VS)

More info to follow.

Tagging @olegtk @jasonmalinowski @jinujoseph @dpoeschl

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:50
Discovered while working on this PR: https://github.com/dotnet/roslyn/pull/28353

Effectively, the new editor CommandExecutionContext (CEC) has an API that indicates it supports progress.  However, progress isn't actually displayed.  This is due to bugs in teh impl (which i will outline below) that cause the messages to update the UI to nor be fired.

Another problem is that CEC itself is not threadsafe.  If you add/dispose of 'Scopes' on it, you can end up corrupting its internal state.  This makes it a poor fit for using in Roslyn (which commonly wants to execute many concurrently).

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:50
Recap of investigation follows:

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:50
@olegtk @gundermanc i need a little help with this.  I'm trying to use the IUIThreadOperationScope to report both the description and the progress of the work we're doing.

However, even though i'm reporting this information to the scope, it doesn't seem to have any effect.  The UI continues to just show "Formatting document..." (which is the description we provided when making the scope).  i.e.:

![image](https://user-images.githubusercontent.com/4564579/42405833-b775e8fa-8151-11e8-82d1-a47dcd6aa4cf.png)

Can you take a look at this PR and let me know what i'm doing wrong?  Effectively, all we're trying to do is call either ```scope.Descrtiption = ...``` to set the description, and ```scope.Progress.Report(new ProgressInfo(...))``` to update the progress bar.  

I've debugged through the code at my disposal, and things like the description are getting passed along.  however, the actual VS components are not being updated.  For example:

![image](https://user-images.githubusercontent.com/4564579/42405872-3f449768-8152-11e8-94b1-5293035d3dfa.png)

However, here's some very weird stuff i've seen. Looking at your source code, it looks like your scope goes and updates your context object with its values.  However, when i look at the context object, here's what i see for progress:

![image](https://user-images.githubusercontent.com/4564579/42406016-6423695e-8154-11e8-96d3-67c84e876ce0.png)


![image](https://user-images.githubusercontent.com/4564579/42405888-86f8f770-8152-11e8-8a29-01107e6c1e92.png)

Even though Roslyn thinks actually at:

![image](https://user-images.githubusercontent.com/4564579/42405907-b228f288-8152-11e8-9e2c-0e842ccc10dc.png)

--

Does your UIContext/Scope objects actually support progress/descriptions?

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:50
@olegtk There's clearly something busted here.  Here's the roslyn code where we're about to notify you of the first piece of progress:

![image](https://user-images.githubusercontent.com/4564579/42406054-5cce08f2-8155-11e8-82b0-ae0ff0e22beb.png)

Here, everything is in a good state.  Roslyn has the values 0/1 and we're about to call .Progress.Report on your scope.

Looking at IL spy, that should execute this code:

```
	public IProgress<ProgressInfo> Progress
	{
		get
		{
			return this._progress ?? (this._progress = new Progress<ProgressInfo>(delegate(ProgressInfo progressInfo)
			{
				this.OnProgressChanged(progressInfo);
			}));
		}
	}

private void OnProgressChanged(ProgressInfo progressInfo)
{
	Interlocked.Exchange(ref this._completedItems, progressInfo.CompletedItems);
	Interlocked.Exchange(ref this._totalItems, progressInfo.TotalItems);
	this._context.OnScopeProgressChanged(this);
}
```

So, stepping over this, i would expect to see *your* values get updated to 0/1 as well.  However, here is what i see post-step:

![image](https://user-images.githubusercontent.com/4564579/42406079-b1a5f466-8155-11e8-8773-9e102188986f.png)

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:51
@olegtk There appear to be at least three *major* regressions i can identify here:

1. Trying to actually update progress does not work.  This was something supported when roslyn had our own wait dialog.
2. clicking 'cancel' will often crash VS.  I reported this previously, but the appears to be because the code was blindly changed over to the new form without realizing the old form handled the cancellation exceptions that were thrown.
3. the new API is not threadsafe.  You can cause memory corruption when using it.  For example, if you add/dispose a scope concurrently, that can corrupt the .LazyScopes property.

These are all pretty severe issues.  Will it be possible to address them in the 15.8 timeframe?

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:51
Ah.  I see the problem.  VSUIThreadOperationContext.OnScopeProgressChanged does not call base.OnScoprProgressChanged.  So the logic to actually update your cached progress data doesn't happen.  So progress basically does not work with these dialogs.  i.e.:

This is the VSUIThreadOperationContext impl:

```c#
	protected override void OnScopeProgressChanged(IUIThreadOperationScope scope)
	{
		this.UpdateDialog();
	}
```

this is AbstractUIThreadOperationContext:

```c#
	protected virtual void OnScopeProgressChanged(IUIThreadOperationScope changedScope)
	{
		int num = 0;
		int num2 = 0;
		foreach (UIThreadOperationScope lazyScope in this.LazyScopes)
		{
			num += lazyScope.CompletedItems;
			num2 += lazyScope.TotalItems;
		}
		Interlocked.Exchange(ref this._completedItems, num);
		Interlocked.Exchange(ref this._totalItems, num2);
	}
```

That collation of values is not happening so we're never reporting progress properly.

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:51
Now.  what i can't figure out is why the description isn't getting updated in the UI.  the codepaths look ok for that piece of data...

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:51
Oh, nevermind.  I see what the problem is with the description. it's similar ot the progress problem.  Namely.  When the description changes the scope calls:

```c#
	set
	{
		if (!string.Equals(this._description, value, StringComparison.Ordinal))
		{
			this._description = value;
			this._context.OnScopeChanged(this);
		}
	}
```

However, OnScopeChanged has no body:

```c#
protected virtual void OnScopeChanged(IUIThreadOperationScope uiThreadOperationScope)
{
}
```

There is an overridden method called "OnScopesChanged" (not that this is 'Scopes' not 'Scope').  Nothing ends up calling this.  So nothing updates the UI.  AFAICT, unless i'm using this API completely improperly, nothing about progress works in this new API.

**Comment by CyrusNajmabadi** [comment] 2018-07-07 03:52
@olegtk @gundermanc The context object does not appear to be threadsafe either.  There is no protection for AddScope or Scope.Dispose happening on any thread.

**Comment by CyrusNajmabadi** [comment] 2018-07-12 18:44
@jinujoseph I haven't heard back from @olegtk.  Can you assign this accordingly?   @jasonmalinowski Is likely a good candidate.

**Comment by olegtk** [comment] 2018-07-12 20:42
@jinujoseph can you please file and route this to the editor? thanks!

**Comment by olegtk** [comment] 2018-07-12 20:46
Clicking cancel is fixed in Preview5, hopefully progress will be fixed too.
Not sure about thread safety though. Commanding API in general is not thread safe and intended to be only called on UI thread currently. Might be Dev16 improvement though.

**Comment by CyrusNajmabadi** [comment] 2018-07-12 20:50
> Not sure about thread safety though. Commanding API in general is not thread safe and intended to be only called on UI thread currently. Might be Dev16 improvement though.

That seems very strange (to me at least).  The previous progress system didn't have threading concerns here.  And it was specifically designed so it could be used without having to own the UI thread. 

If tehre is a threading requirement, it would be good if that could be:

1. doc'ed.
2. checked by the impl so that it throws if used by a non-UI thread.

Because right now it can just silently corrupt internal state.  

--

Note: making this thread-safe honestly doesn't seem that hard.  It would just be around protecting the lazyscopes value and ensuring that it is only mutated by one thread at a time.

**Comment by olegtk** [comment] 2018-07-12 20:52
ok, if it's a regression we should fix it. thanks!

**Comment by olegtk** [comment] 2018-07-12 20:53
A separate thanks for the debugging and root causing these!

**Comment by jinujoseph** [comment] 2018-07-12 21:13
ported over to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646739)

**Closed by jinujoseph** 2018-07-12 21:13 UTC
Labels: Area-IDE, Concept-Continuous Improvement
