### ISSUE TITLE
[Test Failure] VSSDK Build error (+1 more) in prtest/win/dbg/unit64 on PR #8070

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8080] opened 2016-01-21 20:24 UTC
PR: [#8070](https://github.com/dotnet/roslyn/pull/8070) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2967/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'MakeConstCS.Microsoft.601d632a-0bfd-4ef1-8d17-3bd25daec3f3' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit64\src\Samples\CSharp\MakeConst\Impl\MakeConstCS.csproj]

**Issue 2: Compile Error**

**Comment by davkean** [comment] 2016-01-21 21:55
Dupe of: https://github.com/dotnet/roslyn/issues/8077

**Closed by davkean** 2016-01-21 21:55 UTC
Labels: Area-Infrastructure, Contributor Pain
