### ISSUE TITLE
IntelliSense does not insert parentheses at the end of suggested method.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35187] opened 2019-04-22 21:39 UTC
VSF_TYPE_MARKDOWNFor example I have some variable &quot;list&quot; of IList&lt;T&gt; type.
When I type &quot;list.&quot; IntelliSense suggest a &quot;Find&quot; method, then I press Enter key and then I get only &quot;list.Find&quot;, but not expected &quot;list.Find();&quot; . So then I have to add parentheses by myself. How can I fix this behaviour?

I am currently using VS 2019 Community with no extensions installed.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/518751/intellisense-does-not-insert-parentheses-at-the-en.html
VSTS ticketId: 839865_
_These are the original issue comments:_

Visual Studio Feedback System on 4/8/2019, 01:38 AM (14 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jcouv** [comment] 2019-04-22 23:02
Note: there are some scenarios where the parens probably should not be inserted. For instance when typing `Action a = list.Find;`.

**Comment by miloush** [comment] 2019-04-25 14:16
Others include event handlers, nameof, xml documentation etc.

Similar with semicolon - apart from the examples above, you don't want it to be inserted when it's an argument to a method or LINQ query for example.

Might be worth pointing out that the autocompletion can also committed by `(`, not only the Enter key. If the automatic brace completion is on, it will insert `list.Find()` which is almost as desired while still using a single key.

**Comment by sharwell** [comment] 2019-05-01 18:02
Tentatively marking this as **By Design**. I will update this with the final conclusion after the design review meeting.

**Comment by sharwell** [comment] 2019-05-06 19:43
This behavior is By Design, but we have an open feature request to add new support for completing argument lists of invocations: #12363

**Closed by sharwell** 2019-05-06 19:43 UTC
Labels: Area-IDE, Bug, Developer Community, IDE-IntelliSense, Need Design Review, Resolution-By Design

**Comment by GuilhermeMorais** [comment] 2019-08-26 08:14
Hi guys, do you have any news about this? This is one of the features I miss the most comparing to R#.
