### ISSUE TITLE
AV in compiler/runtime during PR tests

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#14035] opened 2016-09-23 22:28 UTC
There are repeated PR tests fail with AV's

This is one example:  http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/3882/console

Example of call stack:   So far all failure stacks look similar, failing during call to GetBaseTypeOfTypeOrThrow in the compiler.

16:24:03     6 running, 2 queued, 46 completed
16:24:11     6 running, 1 queued, 47 completed
16:24:26     6 running, 0 queued, 48 completed
16:24:38     5 running, 0 queued, 49 completed
16:25:49     4 running, 0 queued, 50 completed
16:26:32     3 running, 0 queued, 51 completed
16:27:36     2 running, 0 queued, 52 completed
16:27:37     1 running, 0 queued, 53 completed
16:29:59     0 running, 0 queued, 54 completed
16:29:59   Errors Roslyn.Services.Editor.UnitTests2.dll: 
16:29:59   
16:29:59   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
16:29:59      at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
16:29:59      at System.Reflection.Metadata.TypeDefinition.get_BaseType()
16:29:59      at Microsoft.CodeAnalysis.PEModule.GetBaseTypeOfTypeOrThrow(TypeDefinitionHandle typeDef) in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 860
16:29:59      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 429
16:29:59      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(ConsList`1 basesBeingResolved) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 406
16:29:59      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 1603
16:29:59      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeSymbol.cs:line 694
16:29:59      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.VisitNamedType(INamedTypeSymbol namedTypeSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 368
16:29:59      at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\NamedTypeSymbol.cs:line 1499
16:29:59      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.WriteSymbolKey(ISymbol symbol, Boolean first) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 163
16:29:59      at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyWriter.WriteFirstSymbolKey(ISymbol symbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.SymbolKeyWriter.cs:line 129
16:29:59      at Microsoft.CodeAnalysis.SymbolKey.ToString(ISymbol symbol, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 134
16:29:59      at Microsoft.CodeAnalysis.SymbolKey.Create(ISymbol symbol, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 125
16:29:59      at Microsoft.CodeAnalysis.SymbolKeyExtensions.GetSymbolKey(ISymbol symbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolKey\SymbolKeyExtensions.cs:line 11
16:29:59      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__6.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 161

@jasonmalinowski @jaredpar @tannergooding @TyOverby

**Comment by jaredpar** [comment] 2016-09-23 23:15
dupe of #13243

**Closed by jaredpar** 2016-09-23 23:15 UTC
Labels: Area-Infrastructure, Urgency-Now
