### ISSUE TITLE
ServiceHub.RoslynCodeAnalysisService32.exe high CPU when overriding methods from Object

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/roslyn#18706] opened 2017-04-14 18:29 UTC
**Version Used**: 
Visual Studio Enterprise 2017 Version 15.1 (26403.3) Release

**Steps to Reproduce**:
1. Open a large solution
2. Open a file that has a class that overrides ToString, Equals, and or GetHashCode

**Expected Behavior**:
It would be nice if we could disable CodeLense from getting the count of references for methods that are overridden from Object to prevent massive CPU spikes.

**Actual Behavior**:
ServiceHub.RoslynCodeAnalysisService32.exe spins up to almost 100% CPU while it goes out and calculates all the references to ToString, Equals, and GetHashCode

**Comment by Pilchie** [comment] 2017-04-17 17:27
We do cap the result count at 100 now.  How long are you seeing the CPU stay active in that case?

Also  @CyrusNajmabadi is working on getting persistence working in ServiceHub.RoslynCodeAnalysisService32.exe which should allow some improvements here at least until the indices have been built in memory.

**Comment by ChristopherHaws** [comment] 2017-04-18 01:04
@Pilchie I look forward to the performance improvements! :)

I just opened a file that overrides `Equals`, `GetHashCode`, and `ToString` and my CPU was pegged at 92% for 56 seconds, and this particular solution is fairly small. To give you an idea, there are only 11 other classes that override `ToString`. In some of our larger solutions I have seen it stay up in the 90's for several minutes at a time.

**Comment by Pilchie** [comment] 2017-04-18 01:47
For comparison - how long does invoking Find All References on one of those methods take?

**Comment by ChristopherHaws** [comment] 2017-04-18 18:24
It takes about 40 seconds to find all references.

**Comment by MattGertz** [comment] 2017-06-30 19:56
Mondo escrow triage: the scenario would meet the bar.  @Pilchie @rchande , do we have anything understood & planned to fix for 15.3 here?

**Comment by rchande** [comment] 2017-07-05 19:58
Not currently. CodeLens already limits the number of results it requests so this would require changes to how cascading actually works within FAR.

**Comment by solidrock** [comment] 2017-08-23 06:29
Same to me

**Comment by StefanOssendorf** [comment] 2017-09-14 06:49
Even with CodeLens disabled the exe is spinning up to >90% usage within some files.

**Comment by msfreed** [comment] 2017-09-18 17:47
I experience the same thing

**Comment by sharwell** [comment] 2017-09-18 17:56
@solidrock @StefanOssendorf @msfreed Please consider submitting a performance trace using the Report a Problem tool. These traces allow us to pinpoint the features most affecting performance in your individual use cases. We also use the traces as concrete evidence of end-user gains from performance improvements, in some cases even allowing us to prioritize work that was previously on the backlog.

See the information about the "Record" tab in the following documentation:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017

**Comment by StefanOssendorf** [comment] 2017-09-19 07:31
@sharwell Here is my report: https://developercommunity.visualstudio.com/content/problem/115469/disabled-codelens-high-cpu-servicehubroslyncodeana-1.html

**Comment by sharwell** [comment] 2017-09-19 14:47
@StefanOssendorf Thank you for making those reports. I saw that you submitted 5 reports total. So far only one showed up in the internal system (which I have now analyzed and replied to). I'm working with an internal team to figure why the other 4 were delayed getting to me.

**Comment by StefanOssendorf** [comment] 2017-09-19 16:07
@sharwell You're welcome :) But I have submitted only one report (and got 4 confirmation mails).

**Comment by sharwell** [comment] 2018-01-23 02:13
Based on an analysis of the feedback ticket, most of the items present were resolved for the 15.6 release. The primary remaining item is a duplicate of #18950.

**Closed by sharwell** 2018-01-23 02:13 UTC
Labels: Area-IDE, Bug, Tenet-Performance
