### ISSUE TITLE
Invalid "Use of unassigned variable".

### ISSUE THREAD

**Issue by CheloXL** [dotnet/roslyn#47585] opened 2020-09-10 15:06 UTC
**Version Used**: 
Using .net5/preview 8

**Steps to Reproduce**:
The following code was compiling just fine with the 3.1 sdk:
```csharp
private static string? FindRequestValue(HttpRequest? request, string value)
{
	if (request?.Headers?.TryGetValue(value, out var headers) != true)
	{
		return null;
	}

	return headers.Count > 0 ? headers[0] : null;
}
```

**Expected Behavior**:
Code compiles

**Actual Behavior**:
Error compiling: _Use of unassigned local variable 'headers'_ in the return line.

**Comment by Youssef1313** [comment] 2020-09-10 16:46
Is "TryGetValue" a method that you defined?

I cannot find it in the API reference: https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection?view=net-5.0

**Comment by CheloXL** [comment] 2020-09-10 17:56
The project is a netcoreapp3.1. You have to include in your csproj the following line: `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to have access to the HttpRequest.

Anyways, the problem is related to the code analysis.

If I change the code to 
```csharp
if (request?.Headers == null)
{
	return null;
}

if (!request.Headers.TryGetValue(value, out var headers))
{
	return null;
}

return headers.Count > 0 ? headers[0] : null;
```
The method compiles without issues.

**Comment by RikkiGibson** [comment] 2020-09-15 04:43
Duplicate of #45582.

Many people have requested this change, but a definite assignment spec change is required first.

**Closed by RikkiGibson** 2020-09-15 04:43 UTC
Labels: Area-Compilers

**Comment by bpaczkowski** [comment] 2021-05-09 22:10
@RikkiGibson I'm not sure if it's the same issue. The issue described in this report is a change in .NET 5.0, when compiled to .NET Core 3.1 it compiles without errors. That would mean that before .NET 5.0 it wasn't working as per spec, but in .NET 5.0 it was fixed, which is causing this?

**Comment by RikkiGibson** [comment] 2021-05-09 22:40
> That would mean that before .NET 5.0 it wasn't working as per spec, but in .NET 5.0 it was fixed, which is causing this?

Yeah. What's happening is most likely similar to https://github.com/dotnet/roslyn/issues/52834#issuecomment-825749694

We expect to fix this scenario in C# 10. dotnet/csharplang#4465
