### ISSUE TITLE
is not SomeType fails to compile if there is a member with the same name

### ISSUE THREAD

**Issue by seanblue** [dotnet/roslyn#50671] opened 2021-01-21 15:27 UTC
**Version Used**: 
.NET 5.0
C# 9
Visual Studio 2019 version 16.8.4

Add the following type:
```csharp
public class SomeType
{
	public int SomeProperty { get; init; }
}
```

You can use both `is SomeType` and `is not SomeType` in a class without a member called `SomeType`.
```csharp
// Compiles
public class Version1
{
	public void Execute(object data)
	{
		if (data is SomeType)
			Console.WriteLine("data is SomeType");
		else
			Console.WriteLine("data is not SomeType");
	}
}
```

```csharp
// Compiles
public class Version2
{
	public void Execute(object data)
	{
		if (data is not SomeType)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

However, in a class containing a member called `SomeType`, `is SomeType` compiles, but `is not SomeType` does not compile.

```csharp
/// Compiles
public class Version3
{
	private string SomeType => "some type";

	public void Execute(object data)
	{
		if (data is SomeType)
			Console.WriteLine("data is SomeType");
		else
			Console.WriteLine("data is not SomeType");
	}
}
```

```csharp
// Fails to compile with error CS0428.
public class Version4
{
	private string SomeType => "some type";

	public void Execute(object data)
	{
		if (data is not SomeType)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

Currently, version 4 fails to compile with error CS0428. The issue occurs when there is a static or non-static field, property, or method called `SomeType`. Workarounds are to change the member `SomeType`  to any other name or to fully qualifying the type as in `is not SomeNamespace.SomeType`.

Given that version 3 compiles, I would also expect version 4 to compile without these workarounds.

**Comment by Youssef1313** [comment] 2021-01-21 16:02
Confirmed this bug [reproduces](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoE7AZgAI9KBlAezDgBUBPABzkoG8BfEslRoA1RFACW9AHYAWEtxIBIdgnEA3CPGr4ADHUYsOXALwA+SgCIoByjCMWA3AOKKK1GZQCiADzgBjAFd4AAp6YAArfxhKFE0IAEolBRdFcQAzSmDYmAhKcShKAHoAKil6GGLC/SY2TniiqoBBFBRKMujgCD8Aa0oIKVaoOC4/RnZxABsuRAR6BAA6JUVXfABOYIts3Py28urDTgt4pxS4CaGllfXNuLyChhr7Y6V+YlegA) on master. It looks like a valid compiler bug, the behavior should be consistent between `is` and `is not`. Both should compile successfully.

**Comment by Youssef1313** [comment] 2021-01-21 16:12
I even see a much deeper issue where both `is` and `is not` will compile, but the identifier after them will refer to different things.

See [here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGSAmIDUAfAAQCYBGAWAChKA7OAdwAIA1RKASwHtqAWACgEoAdAFEAHnADGAV3i9ajAMocwcACoBPAA5wB/ANyVKBAMwNiDJSo3aGAbwC+hiibNFmrTj0q3KASE0IbABuEPAMElywZiQADBbKalpwDAC8DABE6QZUFL4uBNwMYpIyOhzAAFaSMAyYoRD8fj65vmwAZgy8dTAQDGxQ8VZJ/AwA9KMMCHBtrAwwHHMAFsnEgn6+eSQAnLzp3b39g4na6frrlAyXV5ftnft9A9QcNZbHcCPjk9Oz80vJEdQogRYhdrmDLsCdnt6g8GE8XglrHBTtlfI4KOigA===).

**Comment by RikkiGibson** [comment] 2021-01-21 21:01
How does the binding work in other places patterns are accepted such as in switch expression arms? Do we choose the `const string SomeType` or `class SomeType`? I imagine it is the const string?

**Comment by seanblue** [comment] 2021-01-21 21:47
@RikkiGibson For the non-const case like I originally wrote up, both the positive and `not` cases fail to compile when a member with the same type name exists.

Both of these compile:
```csharp
public class Version5
{
	public void Execute(object data)
	{
		var result = data switch
		{
			SomeType => "data is SomeType",
			_ => "data is not SomeType"
		};
			
		Console.WriteLine(result);
	}
}
```

```csharp
public class Version6
{
	public void Execute(object data)
	{
		var result = data switch
		{
			not SomeType => "data is not SomeType",
			_ => "data is SomeType"
		};
			
		Console.WriteLine(result);
	}
}
```

Both of these fail to compile with error CS0428:

```csharp
public class Version7
{
	private string SomeType() => "some type";

	public void Execute(object data)
	{
		var result = data switch
		{
			SomeType => "data is SomeType",
			_ => "data is not SomeType"
		};

		Console.WriteLine(result);
	}
}
```

```csharp
public class Version8
{
	private string SomeType() => "some type";

	public void Execute(object data)
	{
		var result = data switch
		{
			not SomeType => "data is not SomeType",
			_ => "data is SomeType"
		};

		Console.WriteLine(result);
	}
}
```

---

Now, looking at the `const` case, it works exactly as you predicted.

```csharp
public class Version9
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		var result = data switch
		{
			SomeType => "data is SomeType",
			_ => "data is not SomeType"
		};

		Console.WriteLine(result);
	}
}

public class Version10
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		var result = data switch
		{
			not SomeType => "data is not SomeType",
			_ => "data is SomeType"
		};

		Console.WriteLine(result);
	}
}
```

Both of those compile, but always output "data is not SomeType" regardless of whether the object passed in was `SomeType` or another type (assuming `data` doesn't match the `const` value obviously). This is consistent with what @Youssef1313 found for the `const` variation of my original case.

[Sharp Lab Demo here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKBuIGYACMxgZQHsw4AVATwAc4jAN4BfGnSYsAaoigBLdpgCcNYTQCQ/BPIBuEeIwDGS2M3IAGNpx4ChAXkYAiKDcYw7TgNwTqGhswALIwAogAecEbo8AAU7MAAVpEwjDgGEACUmup+GvoIjAhwUOgANimOaTAQjFAA7vIwRgAWmho5Gp0cXHyCjPYAfM5VNfJQ1j2eSG0aAPr9Q04jjGOMmOwp3baCTm2iPrS5xOTKMUUl5RkHGuLUt5LMpIyyCApKlmqa2noGQiaYZmOVi2vQczlcXHcngOmgCxGC4Ui0TgcUSyVS6Syfg6eQgBXOZQqGOqtQaTVauRxGnWmxsoIWw3SK3GNIm2zgTmmuTmDKWTNWIM8exhRxOZ2KhKumlu92ocKexwA7J9qIw1eYAGxBRgAWQg8kwMSBAG0ALqMPEAcygWPVIhodrtmDgdWeckUKhiGQAdIiorFna7BYIvVLVY61YG3a8PacfX7kTEnE4wxHIy7o29PfGIv6US43B4dqm01GXlnLF7fbnE1HgyiMiWI2X3e8LFWE7Fk03HS2Y22OzWuxChEWOT2ZUA=)

**Comment by Youssef1313** [comment] 2021-01-22 09:30
@RikkiGibson Are there concerns for an attempt to fix this? That would be, unfortunately, a breaking change. The current behavior is also very confusing and can lead to bugs for seemingly innocent change (such as using `x is not y` instead of `!(x is y)`).

I'd also think the IDE should **not** suggest using `is not` instead of `!(x is y)` in those cases if this won't be fixed compiler-side.

cc: @CyrusNajmabadi for the IDE side of this.

**Comment by Youssef1313** [comment] 2021-01-22 09:36
Related issue #49262 (Not duplicate).

**Comment by jaredpar** [comment] 2021-01-22 13:39
Does seem like a bug. The behavior is not limited to `not` but also extends to `and` and `or`. 

Need to discuss in LDM / compat council before we consider fixing this. Too late in 16.9 to take a change like this so punting out to 16.10.

**Comment by seanblue** [comment] 2021-01-22 13:42
@Youssef1313 There's another IDE rule that isn't valid if this won't be fixed compiler-side. Take the following:
```csharp
public class Version11
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		if (data is SomeType)
			Console.WriteLine("data is SomeType");
		else
			Console.WriteLine("data is not SomeType");
	}
}
```
And run the following:
```csharp
new Version11().Execute(new SomeType());
new Version11().Execute("");
new Version11().Execute("some type");
```

This outputs as you'd expect:
> data is SomeType
> data is not SomeType
> data is not SomeType

Visual Studio suggests the following automated change (I don't see an `IDE` number though):
```csharp
public class Version11
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		switch (data)
		{
			case SomeType:
				Console.WriteLine("data is SomeType");
				break;
			default:
				Console.WriteLine("data is not SomeType");
				break;
		}
	}
}
```

But running the execution in this case results in 
> data is not SomeType
> data is not SomeType
> data is SomeType

This happens because the `is SomeType` is checking against `class SomeType`, but the switch `case SomeType` is checking against the `const string SomeType`.

---

Testing this same situation with `is not SomeType` and the IDE suggestion of `case not SomeType` results in the following in both cases:
> data is not SomeType
> data is not SomeType
> data is SomeType

This isn't surprising based on what we're already seen, as both `is not SomeType` and `case not SomeType` are checking against `const string SomeType`.

**Comment by RikkiGibson** [comment] 2021-01-22 16:07
I guess I'm wondering what the proposed remedy is.

Do we introduce a "mode" for binding patterns in is-pattern expressions which prefers types when things are ambiguous while preserving the behavior to prefer consts in switches?

Basically I'm convinced that we should do something but I wonder if that something is potentially a warning wave and a bug fix on IDE's "use `is`" fixer. The warning occurs when an `is` operand could bind as either a type or an expression. Don't know if we could limit it to constant values but that would be nice.

**Comment by Youssef1313** [comment] 2021-01-22 16:19
@RikkiGibson If the compat council accepts a breaking change here (which is what I hope - given that C# 9 hasn't been for so long), I'd say to change the binding order the same as it worked for pattern matching in pre-C# 9. I'd also make the spec more clear about that.

**Comment by seanblue** [comment] 2021-01-22 16:34
@RikkiGibson At a minimum, I think `is` and `is not` patterns should work the same as the old `is` operator in cases where there are no `const` conflicts. If the options are "fail to compile" (current behavior) or "select the type", I think selecting the type is an obvious and understandable solution. This represents cases `Version4`, `Version7`, and `Version8` from my previous comments.

The problem is that `is` and `is not` patterns currently select the `const`, while the `is` operator currently selects the type. You could perhaps justify this difference across different constructs (`if` condition versus `switch` for example), but I think it's really hard to justify this behavior difference between `if (data is SomeType)` and `if (data is not SomeType)`. Hopefully this bizarre inconsistency convinces the compat council to accept a breaking change (to always prefer the type as the old `is` operator currently does).

**Comment by seanblue** [comment] 2021-01-23 15:57
In another interesting twist, in all the cases where the code doesn't compile or where it uses the constant string instead of the type, adding a discard variable assignment forces it to use the type, as in `data is not SomeType _`. Using a non-discard variable (where allowed) does the same thing, but results in IDE suggestions that change behavior.

For example, this doesn't compile:
```csharp
public class Version4
{
	private string SomeType() => "some type";

	public void Execute(object data)
	{
		if (data is not SomeType)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

But this does and knows that `SomeType` represents the type, not the member:
```csharp
public class Version4
{
	private string SomeType() => "some type";

	public void Execute(object data)
	{
		if (data is not SomeType _)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

As stated above, you *can* use a variable name other than the `_` discard, but in such cases Visual Studio suggests (via `IDE0059`) removing the "unnecessary" assignment, and changes the code back to the uncompilable version. (It says "Use discard '_'", but it actually just removes the variable entirely.)

Adding the discard in the `switch` versions (with non-`const` member) also changes it from uncompilable to compiling using the type. As with the previous case, using a variable name other than the discard results in an IDE suggestion to remove it, resulting in uncompilable code. In the `switch` `not` case, the discard also fixes it to compile using the type, but you can't use another variable name since it could never be used.

---
As before, the `const` cases are worse. In these cases, adding the discard will change the behavior from using the `const string` to using the type. However, if you used a named variable, the IDE suggestion to remove the unused variable will result in still-compiling code with changed behavior, because after the change it would resolve to the `const string` instead of the type.

For example:
```csharp
public class Version12
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		if (data is not SomeType a)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

In this case, `SomeType` represents the type. Visual Studio recommends removed the unused assignment to `a`, which results in the following code:
```csharp
public class Version12
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		if (data is not SomeType)
			Console.WriteLine("data is not SomeType");
		else
			Console.WriteLine("data is SomeType");
	}
}
```

This version now resolves to the `const string` instead of the type, changing the behavior.

**Comment by seanblue** [comment] 2021-01-23 16:10
> I'd say to change the binding order the same as it worked for pattern matching in pre-C# 9.

@Youssef1313 How would I go about trying this in an older version of the compiler. I switched my test project to use .Net Core 2.1 rather than .NET 5 to also force the C# version back to 7.3, where you could use types in switches, but before you could use complex pattern matching like `not`. With that setup, the following example still uses the `const string` instead of the type.

```csharp
public class Version13
{
	private const string SomeType = "some type";

	public void Execute(object data)
	{
		switch(data)
		{
			case SomeType:
				Console.WriteLine("data is SomeType");
				break;
			default:
				Console.WriteLine("data is not SomeType");
				break;
		};
	}
}
```

As in the examples in my previous comment, adding the discard will change the behavior to use the type.

But I imagine this is still using the latest compiler from my version of Visual Studio (just blocking unavailable language features), right? How can I test this using an older compiler to actually see if this was happening before? It might be worth knowing whether C# 9 actually *broke* this behavior, or if it simply makes it more prevalent by adding more ways it can happen.

**Comment by CyrusNajmabadi** [comment] 2021-01-24 00:16
> I'd also think the IDE rule (IDE0083) should not suggest using is not instead of !(x is y) in those cases if this won't be fixed compiler-side.

> cc: @CyrusNajmabadi for the IDE side of this.

My caring level is near zero here.  This doesn't seem relevant enough to look for.

**Comment by Youssef1313** [comment] 2021-01-24 10:21
@CyrusNajmabadi Let's wait for the compiler side first. But to me, I think it's worth fixing the analyzer, or even better, fix the code fix provider if it currently doesn't behave correctly (I haven't yet confirmed)

**Comment by jaredpar** [comment] 2021-01-25 15:59
> Do we introduce a "mode" for binding patterns in is-pattern expressions which prefers types when things are ambiguous while preserving the behavior to prefer consts in switches?

Generally this is not done because it is not a sustainable pattern. Consider that every such mode must be tested in combination with each other. That gets unsustainable very quickly. 

I error'd by mentioning compat council in my first comment here. This feature RTM'd with 16.9 which means we're not even in the first update yet. Compat decisions don't begin to take hold firmly for close to a year after RTM. We just need to confirm with LDM that this is the intended behavior and if so clarify the spec plus fix the bug.

**Comment by gafter** [comment] 2021-01-28 18:27
This is not a bug.  `is Type` is the is-type construct, not pattern-matching.  `is not Type` is an is-pattern operation.  Pattern-matching and is-type necessarily have different binding rules.  For compatibility, the former must bind to a type if one exists, even if it would be shadowed by a constant, which means it skips other members during lookup.  The latter can match to other members, so its name lookup rules do not skip members and do not prioritize a type.  Similarly for `and` and `or`.  This is one of the areas where we could not fully hide the seam between compatibility with existing constructs and extending the language to use the "same" syntax for extended functionality.

**Comment by seanblue** [comment] 2021-01-28 19:50
> We could not use the same rules for pattern-matching because that would (among other things) break the Color-Color situation. 

@gafter Can you explain what the Color-Color situation is?

---

Regarding the rest of your comment, would it be possible to have a version of `is not` that uses the is-type construct instead of pattern matching? As previously mentioned, my biggest concern is that `if (!(data is SomeType))` can have different behavior from `if (data is not SomeType)`. To me this is very unintuitive.

Also, in the case that it prioritizes members over types, does this still make sense even when the result can't compile? Is there any reason the compiler shouldn't skip to using the type if the member is a non-const and therefore can't compile?

**Comment by RikkiGibson** [comment] 2021-01-28 20:21
One way to "force" it to match the type would be to add the `_` a la `if (data is not SomeType _)`. Basically a variable declaration pattern but the variable name is a discard.

**Comment by seanblue** [comment] 2021-01-28 20:41
@RikkiGibson Yeah, I noticed that as well and mentioned it in a previous comment. I still find it a bit strange though.

**Closed** 2021-02-01 18:23 UTC
Labels: Area-Compilers, Bug, New Language Feature - Pattern Matching

**Comment by RikkiGibson** [comment] 2021-02-01 18:43
> Can you explain what the Color-Color situation is?

IIRC, Color-Color is pretty similar to the situation in the issue description.

```cs
class Color { ... }

class Widget
{
    Color Color;
}
```

i.e. inside the class `Widget`, when do you pick the type `Color` or the member `Color`.

**Comment by seanblue** [comment] 2021-02-01 22:59
@jaredpar I don't think it's fair to close this as "by design" without other aspects being discussed.

1. Is it possible to add an `is not` operator, so at least `!(data is SomeType)` and `data is not SomeType` work consistently in all cases? I didn't know the Color-Color thing by name, but that's actually the exact case I ran into that made me find this discrepancy. I tried to use `is not SomeType`, but it failed to compile because I also had a property in that class of type `SomeType` and named `SomeType`.
2. If we're saying it's by design to prioritize consts over types for pattern matching, does that *have* to apply to non-const members as well? In those cases, the code literally can't compile, so what's the value in prioritizing non-compiling code over using the type? Right now for pattern matching, the compiler seems to say `member > type`. Is there any reason it couldn't be enhanced to do `const > type > other (uncompilable) member`? Importantly, this would *not* be a breaking change, but it would resolve what is probably the most common unhandled situation – the Color-Color case.
3. If for some reason none of these changes are acceptable, doesn't Visual Studio at least need to be updated to handle these exceptional cases? Right now, Visual Studio suggests going from `!(data is SomeType)` to `(data is not SomeType)` in cases that would result in uncompilable code (when a non-const member with the same name exists), or changes in behavior (when a const with the same name exists). If no compiler changes will be made, shouldn't that be fixed?

**Comment by jaredpar** [comment] 2021-02-02 01:27
>  I don't think it's fair to close this as "by design" without discussing other aspects that have come up in this issue

The issue was filed on the behavior of `is not` in comparison to the standard `is` operator. That behavior is confirmed to be "By Design" hence the issue was correspondingly closed as such.  Closing the issue doesn't need to stop the discussion but it is an acknowledgement that the behavior described in the issue is not a bug. 

> Is it possible to add an is not operator, so at least

This is effectively a proposal to add a feature to the language. The best place to discuss that is on dotnet/csharplang. This repo is generally more concerned with the behavior of the compiler implementation of the language features. 

> Right now, Visual Studio suggests going from !(data is SomeType) to (data is not SomeType) in cases that would result in uncompilable code (when a non-const member with the same name exists), or changes in behavior (when a const with the same name exists). If no compiler changes will be made, shouldn't that be fixed?

I agree that is a problem that the IDE suggests the change. I think we should probably open a new issue for that though. This issue is getting a bit dense to look through. Think it's better to have a clean issue here where we call out the incorrect IDE behavior and focus on a fix for it.

**Comment by seanblue** [comment] 2021-02-02 02:54
@jaredpar Okay, thanks for clarifying that. I'll look into opening separate issues as needed.

**Comment by jnm2** [comment] 2021-05-11 15:36
Someone else has independently started a csharplang discussion on this: https://github.com/dotnet/csharplang/discussions/4743
