### ISSUE TITLE
IDE0055 report incorrectly on region define in pragma

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#61163] opened 2022-05-06 10:11 UTC
**Version Used**: 7.0.100-preview.1.22110.4

**Steps to Reproduce**:

```
#if NETFRAMEWORK
using System;

public class C : IDisposable
{
	#region IDisposable support // OK with NETFRAMEWORK build but IDE0055 in !NETFRAMEWORK build
	#endregion
}
#endif
```

**Expected Behavior**:

No issue for non .net framework based builds as the region is within a pragma. Note that maybe from the language specification point of view the order is correct.

**Actual Behavior**:

Warning raised on region.

**Comment by vatsalyaagrawal** [comment] 2022-05-13 19:33
Duplicate of #31419

**Closed by vatsalyaagrawal** 2022-05-13 19:33 UTC
Labels: Area-IDE
