### ISSUE TITLE
AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase_BaseCall Failed in test run

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26694] opened 2018-05-07 22:32 UTC
AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase_BaseCall  [failed in this run](https://ci.dot.net/job/dotnet_roslyn/job/features_NullableReferenceTypes/job/windows_debug_spanish_unit32_prtest/40/)

With the following message

```ini
MESSAGE:
System.AggregateException : Se han producido uno o varios errores.
---- System.InvalidOperationException :
+++++++++++++++++++
STACK TRACE:
en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
en System.Threading.Tasks.Task.Wait() 
en System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) 
en System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
en Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) en Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected) 
en Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase_BaseCall() 
----- Inner Stack Trace ----- 
en Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) 
en System.Diagnostics.TraceListener.Fail(String message) 
en System.Diagnostics.TraceInternal.Fail(String message) 
en System.Diagnostics.Debug.Assert(Boolean condition) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributesBag() 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributes() 
en Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteObsoleteAttribute() 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckOverrideMember(Symbol overridingMember, OverriddenOrHiddenMembersResult overriddenOrHiddenMembers, DiagnosticBag diagnostics, Boolean& suppressAccessors) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckMembersAgainstBaseType(DiagnosticBag diagnostics, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetSynthesizedExplicitImplementations(CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) 
en Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass47_1.<ForceComplete>b__0(Int32 i) 
en Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param) 
en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1() 
en System.Threading.Tasks.Task.InnerInvoke() 
en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) 
en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

**Comment by jaredpar** [comment] 2018-09-12 16:48
Dupe of #28954

**Closed by jaredpar** 2018-09-12 16:48 UTC
Labels: Area-Compilers, Bug
