### ISSUE TITLE
VS2015 C# regression bug with pointers

### ISSUE THREAD

**Issue by psmacchia** [dotnet/roslyn#5712] opened 2015-10-06 08:27 UTC
The following code used to compile with VS2013 but not anymore with VS2015:

      class Foo3 { 
         internal struct Struct1<U> {} 
      }

      unsafe void NMethodCecilNameHelper_Parameter_AllTogether<U>(ref Foo3.Struct1<int>**[][,,] ppi) { }

      [Test]
      public void Test_NMethodCecilNameHelper_Parameter_AllTogether1() {
         MakeSureTheFollowingMethodExists(
            "NMethodCecilNameHelper_Parameter_AllTogether<U>(Test_NMethodCecilNameHelper+Foo3+Struct1<Int32>**[,,][]&)", false);
      }

and now we get the C# error

    Error	CS0208	Cannot take the address of, get the size of, or declare a pointer to a managed type 

We'd never use such a syntax construct, but it is just for our testing purposes.

![capture](https://cloud.githubusercontent.com/assets/511445/10303497/2522c458-6c25-11e5-9fec-e0b208af5e9f.PNG)

**Comment by gafter** [comment] 2015-10-06 16:56
Assigning to the 1.1 milestone for evaluation.

**Comment by jaredpar** [comment] 2015-10-07 16:18
Thanks for reporting.  We're taking a look at this.  The root cause appears to be the following bit of code:

http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/BaseTypeAnalysis.cs,262

Following up to see if this was an intentional break or not.

**Comment by agocke** [comment] 2016-05-18 01:39
This is a break, but I believe it is correct and no correct program could be possibly broke by it.

This behavior appears to be a bug in the native compiler. The minimal repro I found is as follows:
```csharp
class C
{
    public struct S<T> { }

    unsafe void M(ref S<int>*[] p) { }
}
```

Which compiles successfully in the native csc, but shouldn't. The native compiler correctly treats all generic structs as managed types, but something about the addition of `ref` seems to cause confusion.

For example, the following program:

```csharp
class C
{
    public struct S<T> { }

    unsafe void M(S<int>*[] p) { }
}
```

produces

```
test.cs(5,17): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('C.S<int>')
```

Roslyn correctly finds fault with both programs. While this is technically a break, I don't believe this behavior can ever be observed in C# since the caller must declare a variable of type `S<int>*[]` to be passed by ref and both Roslyn and the native compiler produce an error on the declaration of such a type.

I think we should loop this one around to the compat council, but for now I'll add a regression test in a PR.

**Comment by gafter** [comment] 2016-05-18 03:49
@dotnet/roslyn-compat-council I propose to keep the break in Roslyn (and document it), since an API declared this way cannot be consumed from C# or VB, and it violates the language specification. I agree with @agocke that it was a bug in the native compiler that it failed to diagnose the problem in these particular circumstances. No customers are known to have had production code broken by this.

**Comment by DustinCampbell** [comment] 2016-05-18 13:40
Agreed

**Comment by Pilchie** [comment] 2016-05-18 15:00
Agreed here too.

**Closed** 2016-05-19 06:16 UTC
Labels: Area-Compilers, Bug, Tenet-Compatibility

**Comment by CJBrew** [comment] 2016-12-21 14:40
@gafter "No customers are known to have had production code broken by this."

I have just come across some production code broken by this. It's third party code though; and I have advised the authors of the issue.
