### ISSUE TITLE
False negative error CS9503 "Required member cannot be less visible than the containing type" for member in nested type

### ISSUE THREAD

**Issue by sirduke** [dotnet/roslyn#61528] opened 2022-05-26 09:08 UTC
**Version Used**: 
features/required-members

**Steps to Reproduce**:

```
public class Outer {
    protected class ProtectedClass {
        protected required int ProtectedProperty { get; set; }
    }
}

 class Derived : Outer {
     public void Test() {
         var p = new ProtectedClass() // error "Required member 'Outer.ProtectedClass.ProtectedProperty' must be set
         {
           // ProtectedProperty = 1 // cannot set the property because it is inaccessible
         };
     }
 }
```

**Expected Behavior**:
Error CS9503 is shown for `ProtectedProperty` declaration

**Actual Behavior**:
No error for `ProtectedProperty` declaration is shown but it is impossible to create instance of `ProtectedClass` in derived class

**Comment by Bosch-Eli-Black** [comment] 2022-06-01 06:31
Dupe of https://github.com/dotnet/roslyn/issues/61527

**Comment by 333fred** [comment] 2022-06-01 15:03
No, this is not a duplicate.

**Comment by Bosch-Eli-Black** [comment] 2022-06-02 02:13
Sorry, I must have been tired yesterday 😅

**Closed** 2022-06-14 19:25 UTC
Labels: Bug, Area-Compilers, 4 - In Review, New Feature - Required Members
