### ISSUE TITLE
Renaming of lambda parameter with 1 ref takes about 30 seconds

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/roslyn#55400] opened 2021-08-04 16:50 UTC
**Version Used**: 

* VS 16.10.4
* VS 17.0.0 Preview 2.1
* Roslyn 3.10.0.0

**Steps to Reproduce**:

Try to rename `ch` or `i` lambda parameter using either VS or `Renamer.RenameSymbolAsync` API

```cs

using System;
using System.Collections.Immutable;
using System.Linq;

internal static class RenameTest
{
    public static void CreateCharIndexMap(ImmutableHashSet<string> values, bool reverse)
    {
        var map = values
            .Select(s =>
            {
                return (
                    value: s,
                    chars: ((reverse) ? s.Reverse() : s).Select((ch, i) => (ch, i))); // Try to rename ch or i
            })
            .SelectMany(f => f.chars.Select(g =>
            {
                return (
                    f.value,
                    g.ch,
                    g.i,
                    key: new WordChar(g.ch, g.i));
            }))
            .GroupBy(f => f.key)
            .ToImmutableDictionary(
                f => f.Key,
                f => f.Select(f => f.value).ToImmutableHashSet());
    }
}

internal readonly struct WordChar
{
    public WordChar(char value, int index)
    {
        Value = value;
        Index = index;
    }

    public char Value { get; }
    public int Index { get; }
}
```

**Actual Behavior**:

It takes about 35 seconds to complete the operation on my laptop.

**Comment by sharwell** [comment] 2021-08-06 16:08
I'm not able to reproduce this. Can you submit feedback with a performance recording following these steps?
https://aka.ms/reportPerf

Once the feedback system sends you an email, you can paste the link to the item here for us to review.

**Comment by JosefPihrt** [comment] 2021-08-09 23:16
@sharwell https://developercommunity.visualstudio.com/t/Renaming-of-lambda-parameter-with-1-ref/1498195

**Comment by 333fred** [comment] 2021-08-24 23:46
Looking at the stacks, it doesn't appear that this is related to @cston's work around inferred lambda types, it's just a nasty case of inferred lambdas affecting method type inference inside inferred lambdas affecting method type inference. @JosefPihrt, a simple workaround for now would be to specify some types involved here, such as for the nested lambda parameters.

**Comment by 333fred** [comment] 2021-08-24 23:50
Also likely related to 140235.

**Comment by 333fred** [comment] 2021-09-02 00:10
Alright, I'm going to close this out as it's not a regression. We're tracking potential improvements to this scenario in that DevDiv bug I linked above, but in general this just an issue where nested type inference can cause exponential type explosion and is generally an NP-complete problem. A good workaround is adding some types to help the compiler: for example, here you could change the outer `Select` lambda to start with `.Select((string, IEnumerable<(char, int)>) (string s) =>` instead of `.Select(s =>`, which should significantly improve the performance here (takes it from 5+ seconds on a beefier desktop to near-instantaneous).

**Closed by 333fred** 2021-09-02 00:11 UTC
Labels: Bug, Area-Compilers

**Comment by JosefPihrt** [comment] 2021-09-02 18:11
@333fred Thanks for answer. I'm fine with closing this one. It's very rare case and there is a workaround.
