### ISSUE TITLE
IDE0059: Variables are used and not handled correctly

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#61404] opened 2022-05-19 08:55 UTC
**Version Used**: 
Visual studio 2019

**Steps to Reproduce**:
Copy the following sample code to reproduce

**Expected Behavior**:
Variable status should not be grayed out, no warning hints
**Actual Behavior**:
The variable status should be grayed out and the warning prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/23723575/169254289-4b4661c4-21fa-4070-955d-2fc83bb96c6d.png)
![image](https://user-images.githubusercontent.com/23723575/169254135-c3522d65-8f99-4d56-8311-e56e73e70c3e.png)

**Demo Code**

```C#
        public static TestClass Get1(int num)
        {
            var result = default(TestClass);

            if (num > 0)
                result = new TestClass();

            else
                throw new ArgumentNullException(nameof(result));

            return result;
        }

        public static TestClass Get2(int num)
        {
            TestClass result = null;

            if (num > 0)
                result = new TestClass();

            else
                throw new ArgumentNullException(nameof(result));

            return result;
        }

        public static TestClass Get3(int num)
        {
            TestClass result;

            if (num > 0)
                result = new TestClass();

            else
                throw new ArgumentNullException(nameof(result));

            return result;
        }

        public class TestClass
        {
            public int Name { get; set; }
        }
```

**Comment by svick** [comment] 2022-05-19 12:28
The message is correct: the assignment is unnecessary, as you demonstrate in `Get3()`.

Is this issue about the fact that the variable is greyed out, when it's only the assigned value that can be removed?

**Comment by kelicto** [comment] 2022-05-19 17:46
Yes, it should not be grayed out because variables are used, such as returning results.

**Comment by sharwell** [comment] 2022-05-19 19:34
Duplicate of #36202

**Closed by sharwell** 2022-05-19 19:34 UTC
Labels: Area-IDE, untriaged
