### ISSUE TITLE
Using 'var' to deduce type with a string constant causes type to be deduced as a nullable string

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/roslyn#45787] opened 2020-07-08 15:47 UTC
---
**Issue moved from microsoft/msbuild#5491**
- Please respond to @firedraco.

---

_From @firedraco on Tuesday, July 7, 2020 6:04:42 PM_

### Steps to reproduce
With `<Nullable>enabled</Nullable>` in the csproj file, use var to deduce the type of a variable assigned with a string constant. By highlighting the type, looking at Intellisense results, or building the project, you can see that the deduced type is of 'string?'.

```
var str = "value"; // str is of type 'string?'
```

On earlier versions of Visual Studio (Like 16.4.x), the type was deduced as 'string'. This resulted in some discrepancies in behavior and created additional warnings in the code that were not present before.

### Expected behavior
The deduced type of str would be 'string'

### Actual behavior
On 16.4.3: The type of str is 'string'
On 16.6.1, 16.6.3: The type of str is 'string?'

### Environment data

Used Visual Studio 16.6.1 or 16.6.3 to compile on Windows 10 (64bit)

### Project demonstrating issue
[TestApp.zip](https://github.com/microsoft/msbuild/files/4886421/TestApp.zip)

**Comment by sharwell** [comment] 2020-07-08 15:59
A variable declared like this is expected to hold a non-null value, but you should be allowed to assign null to it without introducing a warning. The expected result is one of the following two scenarios:

1. The variable never has a nullable value assigned to it. In this case, there is no difference between declaring the variable as `string?` and declaring the variable as `string`.
2. The variable has a maybe-null value assigned to it at some point, in which case the variable being declared as `string?` means the code will work without further changes.

If a specific problem arises, a separate bug with the specific example should be created.

**Comment by jmarolf** [comment] 2020-07-08 18:04
@rainersigwald this is an intentional change that the compiler team made. `var` always implies `T?` though, as Sam says, null state tracking still happens so you should not get a warning for trying to dereference this variable.

**Comment by firedraco** [comment] 2020-07-08 20:12
`var value = 2; //value is of type 'int'
value = null; //error
var str = "string"; //value is of type 'string?'
str = null; //not an error`
seems inconsistent to me. Is this just a difference between how value/reference types are handled by `var` here?

Since this is expected behavior, perhaps there should be an update to the IDE0007 code suggestion to replace the `string` with `var` in `string str = "value";`. It implies this is is an equivalent change, but with `<Nullable>enabled</Nullable>` in the csproj, `var` will allow me to assign null, even though using just `string` will not allow that.

Thanks for your quick responses!

**Comment by sharwell** [comment] 2020-07-08 20:42
@firedraco The design is based on type safety, and not necessarily a strict code style. The compiler will warn if you assign a maybe-null value to something that was originally not null, and then try to use it in a non-null manner. However, if you assign a maybe-null value to it and then only do null-safe operations, the compiler will allow it.

> Since this is expected behavior, perhaps there should be an update to the IDE0007 code suggestion to replace the string with var in string str = "value";

It looks like this already works (tested in 16.7 Preview 3.1).

> Is there a way to get var-like type deduction but forcing the type to be not nullable?

No. Strict type declarations are provided explicitly, not implicitly.

> I don't want to have to go update everything to specify the type just to enforce not-nullability.

You also have the option of using an `IOperation` analyzer to prevent the use of null as a code style.

**Comment by firedraco** [comment] 2020-07-09 16:02
Thanks for the response!

I can't remove null completely as there is some code that does make sense to have it, but I was hoping there'd be a way to remove it everywhere except where we explicitly allowed it. I'll take a look at that analyzer and see if I can do something with it!

**Comment by jmarolf** [comment] 2020-07-09 22:22
If you do not what nullable to be the default type infererred for `var` in reference types you should file a new issue on github.com/dotnet/csharplang to disuses it.  As it stands if you want the type to be non-nullable you must not use `var`

**Comment by firedraco** [comment] 2020-07-09 22:26
Will do! Thanks!

**Comment by jaredpar** [comment] 2020-07-10 17:01
Closing as this was a deliberate design change, as noted in the discussion.

**Closed by jaredpar** 2020-07-10 17:01 UTC
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Resolution-By Design
