### ISSUE TITLE
Split Comment option in VS Tools->Options is mistakenly bound to Split String option

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/roslyn#63309] opened 2022-08-10 20:01 UTC
**Version Used**: latest VS builds (Version 17.4.0 Preview 2.0 [32810.39.main])

**Steps to Reproduce**:

1. Open Tools -> Options -> Text Editor -> C# -> Advanced
2. Uncheck the box for "Insert // at the beginning of lines when writing // comments"
   * Note: the option for "Split string literals on enter" in the next section will also toggle... 🤔
3. Find a // comment and insert a newline in the middle of it

**Expected Behavior**:
The new line should not start with // because I thought I turned that off

**Actual Behavior**:
It still gets the // inserted

More details:
This seems to simply be a binding issue [here](https://github.com/dotnet/roslyn/blob/77c17746ec78a57ca0c84ef819614b82947fa94f/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs#L118)

**Comment by Youssef1313** [comment] 2022-08-10 20:56
Duplicate of https://github.com/dotnet/roslyn/issues/62362

**Closed** 2022-08-15 18:24 UTC
Labels: Resolution-Duplicate, Area-IDE
