### ISSUE TITLE
AnalysisContext.EnableConcurrentExecution should receive a flag

### ISSUE THREAD

**Issue by b-straub** [dotnet/roslyn#49109] opened 2020-11-01 09:49 UTC
**Version Used**: 

Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 5.0

C# Tools 3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

**Steps to Reproduce**:

1.  Implement an Analyzer 

2. Don't call `AnalysisContext.EnableConcurrentExecution()` in `Initialize(AnalysisContext context)`

**Expected Behavior**:

`EnableConcurrentExecution` should be customizable such as `EnableConcurrentExecution(false)`

**Actual Behavior**:

`EnableConcurrentExecution `can only be omitted, this will show a `MicrosoftCodeAnalysisCorrectness.RS1026` warning.
There should be always a way to improve code quality or reconsider the correct implementation other than suppressing an Analyzer warning.

**Comment by CyrusNajmabadi** [comment] 2020-11-01 16:38
> There should be always a way to improve code quality or reconsider the correct implementation other than suppressing an Analyzer warning.

Why?  Analyzers are supposed to be stateless and concurrency safe. So all analyzers sound call this. The only ones that shouldn't legacy ones that have problems that we need to support for back compat.  These legacy 3rd party analyzers should either become concurrency safe, or should suppress this. 

No one should be explicitly stating that they are not concurrency safe as that's an anti pattern for analyzers. 

I'm going to close this out as by design.

**Closed by CyrusNajmabadi** 2020-11-01 16:38 UTC
Labels: Area-Analyzers, untriaged
