### ISSUE TITLE
DiagnosticSeverity.Error doe's not stop a build progress

### ISSUE THREAD

**Issue by nikolasmagno** [dotnet/roslyn#5493] opened 2015-09-28 19:48 UTC
Hellow,

In first place, I'm sorry but my english is not perfect (I'm a english student).
I think it's a problem, because I define same DiagnosticResult using a DiagnosticSeverity.Error (check code down), and when I'm building a application with this 'error' the build complete without errors like this: 
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

Code:

 internal const string Title = "Your Regex expression is wrong";
        internal const string MessageFormat = "{0}";
        internal const string Category = SupportedCategories.Naming;
        const string Description = "This diagnostic compile the Regex expression and trigger if the compilation fail "
            + "by throwing an exception.";

        internal static DiagnosticDescriptor Rule = new DiagnosticDescriptor(
            DiagnosticId.Regex.ToDiagnosticId(),
            Title,
            MessageFormat,
            Category,
            DiagnosticSeverity.Error,
            isEnabledByDefault: true,
            description: Description,
            helpLinkUri: HelpLink.ForDiagnostic(DiagnosticId.Regex));

  try
            {
                System.Text.RegularExpressions.Regex.Match("", regex);
            }
            catch (ArgumentException e)
            {
                var diag = Diagnostic.Create(Rule, regexLiteral.GetLocation(), e.Message);
                context.ReportDiagnostic(diag);
            }

VS Info's:

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA347
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-80000-00000-AA347
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA347
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA347
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA347
Microsoft Visual C++ 2015

Visual F# 2015 RC   00322-80000-00000-AA347
Microsoft Visual F# 2015 RC

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA347
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20626.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.23121.00 D14OOB
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   3.11.816.0 (cefca47)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.5.2 (2e8568c9f3a3ce0b66203412a268b39618824338)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.4.0 (099f94bba4532201864249a9064bf73be56f8667)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

Thx for you help!

**Comment by jmarolf** [comment] 2015-09-28 21:17
Can you give us the build output when you build your project?  Also how are you loading your analyzer?

**Comment by nikolasmagno** [comment] 2015-09-29 11:13
Hellow, 
Thx for you help, unfortunately the build output (aplication) is:

== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

I Take a sample of ' https://github.com/code-cracker/code-cracker.git' and this sample have a RegexAnalyzer where check for this '    Regex.Match("""", ""["");'. I change the DiagnosticDescriptor to set a DiagnosticSeverity.Error, So when I'm running a box-visual-studio (running the analyzer by F5 on VS2015), I wrote some code with Regex.Match("""", ""[""); analyzer find the error and report then, BUT when I'm compiling this aplication (with wrong code). The build result is: 
== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

if you wanna I can publish my code, but like I said is the same code as 'https://github.com/code-cracker/code-cracker.git', just changed a DiagnosticSeverity to Error on RegexAnalyzer  class.

**Comment by nikolasmagno** [comment] 2015-09-29 12:58
I'm starting to test now some solution, I will put my analyzer DLL on project and test if msbuild will check and stop if find some analyzer error, but I don't know if it's the best solution..

**Comment by sharwell** [comment] 2015-09-30 11:43
> Obs: I'm loading using Visual Studio extension.

Diagnostics only have the ability to stop a build when they are part of a project. Otherwise builds in the IDE and builds on the command line would have completely different results.

For StyleCop.Analyzers, we addressed this issue by not shipping the VSIX at all. Individual developers working on the project can compile it from source and use it for testing, but users who want StyleCop functionality need to install the NuGet package to get reliable/reproducible build behavior.

**Comment by nikolasmagno** [comment] 2015-09-30 11:53
Yeah Sharwell...

Thx for you help, I tried yesterday putting a analyzer dll into the project (using nuget) and work very well. I think this information is very important and I didn't see it on examples/documentation.

So, thanks for everybody help.

**Comment by mavasani** [comment] 2015-10-02 18:19
@nikolasmagno Closing this issue as your issue seems to be addressed.

**Closed by mavasani** 2015-10-02 18:19 UTC
Labels: Area-Analyzers
