### ISSUE TITLE
No completion for parameter names inside `nameof` in attributes

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65419] opened 2022-11-14 20:22 UTC
```csharp
class C
{
    [Obsolete(nameof($$))]
    void M(string myParam)
    {

    }
}
```

There should be completion for `myParam` inside `nameof`

**Comment by jasonmalinowski** [comment] 2022-11-16 01:11
@CyrusNajmabadi did we never implement this?

**Comment by jasonmalinowski** [comment] 2022-11-16 01:13
Looks like this is a duplicate of #60812.

**Closed by jasonmalinowski** 2022-11-16 01:13 UTC
Labels: Area-IDE
