### ISSUE TITLE
C# Preprocessor bug?; found in VS2017 (15.7.2)

### ISSUE THREAD

**Issue by jpapp05** [dotnet/roslyn#27109] opened 2018-05-24 17:52 UTC
Hi all,

The code below gives the following compilation error:

error CS1024: Preprocessor directive expected

The strange part is that it ONLY happens when the code is part of a #if/#endif block that is NOT defined.

```
// If this is uncommented out, it compiles!
// #define _THIS_IS_NOT_DEFINED_

#if _THIS_IS_NOT_DEFINED_
class Class
{
const string data = @"File Format
#rates
0
1
2
3";
}
#endif
```

This seems like a bug.

**Comment by jpapp05** [comment] 2018-05-24 18:15
Thanks for the detail explanation.  It does feel odd that valid code can start to fail if wrapped in an undefined preprocessor block in this way; however, it is certainly easy to work around.  Should the scanning of disabled text take into account the `@"` text as a future improvement to the C# preprocessor?  I’m just curious on your take.

Thanks much.

**Comment by CyrusNajmabadi** [comment] 2018-05-24 18:23
> text take into account the @" text as a future improvement to the C# preprocessor? I’m just curious on your take.

Unfortunately, that can't happen, it would be a breaking change.  There is code out there that def depends on this behavior.  :-/

**Comment by svick** [comment] 2018-05-24 18:35
Maybe it would make sense to ignore unknown preprocessor directives in disabled sections of code? I think that wouldn't be a breaking change.

**Comment by Rohansi** [comment] 2019-05-03 03:27
You also get some [fun error messages](https://sharplab.io/#v2:CYLg1APgxAlgZgAgCoFEDKSCMAmAzAWACgABABgWMwG4jjcLsEBBBAbyIEgB6AKjooAsCABoAKAJRsiCGQgC+RWIlQYAkgDkA4jgKFZFesSEBNCVL2yFhKAFMAdsHg8uRK7YfwgA) when you have commented out preprocessor blocks. In VS this only errors at build time.

**Comment by CyrusNajmabadi** [comment] 2022-11-08 17:27
Closing out as thsi is by design.

**Closed by CyrusNajmabadi** 2022-11-08 17:27 UTC
Labels: Area-Language Design
