### ISSUE TITLE
Reference count for const variables.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#36735] opened 2019-06-25 16:48 UTC
VSF_TYPE_MARKDOWNGetting code lens reference counts for properties and methods is immensely useful. It would also be handy to get counts for const variables as well.

ie,
```
public class Foo
{
   // Awesome to see a reference count here.
   public const string NameOfThingNeededForAttributeValue = &quot;Bar&quot;;
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/606869/reference-count-for-const-variables.html
VSTS ticketId: 918151_
_These are the original issue comments:_

Jane Wu [MSFT] on 6/14/2019, 01:29 AM (11 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by marionzr** [comment] 2019-11-07 17:52
An alternative is using static getter only properties

`public static string EXTERNAL_TOOLS => "https://www.nuget.org/packages/Nzr.ToolBox.Core.Single/, https://www.nuget.org/packages/Nzr.Orm.Core/";`

![image](https://user-images.githubusercontent.com/47438990/68413991-1ba43c80-016e-11ea-9075-d5bfaa5d74b0.png)

**Comment by mkv2** [comment] 2020-08-14 10:23
An advantage of using a const over a static property is that the tip text for the const includes its value.

![const_hintbutnorefs](https://user-images.githubusercontent.com/20664891/90239825-16bc9980-de20-11ea-822a-b0f6504d7a91.png)
versus:
![staticprop_refsbutnohintvalue](https://user-images.githubusercontent.com/20664891/90239873-2c31c380-de20-11ea-991e-29b421a27c57.png)

...it would be nice to have both benefits through one of those.

**Comment by fhaag** [comment] 2020-12-04 14:08
> An alternative is using static getter only properties

Static read-only properties cannot be used as arguments to an attribute, while `const` values can.

**Comment by joaobsneto** [comment] 2021-02-12 17:52
No updates on this? I'm moving some code in a project to a library and I have a lot of constants that I would like to remove from it. It would be a great help to have the references listed so I could remove more easily.

**Comment by CyrusNajmabadi** [comment] 2021-02-12 20:47
@joaobsneto No, this is currently in our backlog.

**Comment by CSymes** [comment] 2021-07-14 06:57
Seems to be a duplicate of #32320

**Comment by sharwell** [comment] 2021-07-16 13:34
Duplicate of #36735

**Closed by sharwell** 2021-07-16 13:34 UTC
Labels: Area-IDE, Developer Community, Feature Request
