### ISSUE TITLE
Getting NxFault in csproj.dll

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#18967] opened 2017-04-24 23:44 UTC
Watson is here: http://watson/BucketDetails?BucketIdentifier=87fb5e9c-e570-080c-e72b-730a083d6e51

Failure is:
software_nx_fault_c0000005_csproj.dll!clangfilenode::clearmsbuilditem

I've hit this locally, and it looks like there are around 5-10 hits a day.

**Comment by Pilchie** [comment] 2017-04-28 21:33
Dupe of https://github.com/dotnet/roslyn/issues/15044

**Closed by Pilchie** 2017-04-28 21:33 UTC
