### ISSUE TITLE
[Bug]: Visual studio 2022 debugger C# .Net framework application mistakenly thought this was a C++ project And not showing variable values

### ISSUE THREAD

**Issue by eveloki** [dotnet/roslyn#70888] opened 2023-11-18 13:38 UTC
**Version Used**: 
Microsoft Visual Studio Community 2022 x64  17.8.0

<details><summary>Details</summary>
<p>
Microsoft Visual Studio Community 2022
  版本 17.8.0
  VisualStudio.17.Release/17.8.0+34309.116
  Microsoft .NET Framework
  版本 4.8.09037
  
  已安装的版本: Community
  
  Visual C++ 2022   00482-90000-00000-AA815
  Microsoft Visual C++ 2022
  
  ASP.NET and Web Tools   17.8.352.38654
  ASP.NET and Web Tools
  
  Azure Functions and Web Jobs Tools   17.8.352.38654
  Azure Functions and Web Jobs Tools
  
  Azure 应用服务工具 3.0.0 版   17.8.352.38654
  Azure 应用服务工具 3.0.0 版
  
  C# 工具   4.8.0-7.23558.1+e091728607ca0fc9efca55ccfb3e59259c6b5a0a
  IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。
  
  Common Azure Tools   1.10
  Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
  
  Microsoft JVM Debugger   1.0
  Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
  
  NuGet 包管理器   6.8.0
  Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 https://docs.nuget.org/
  
  Razor (ASP.NET Core)   17.8.3.2353105+f0a326f3e15b2370371693a76fd379635387c74d
  提供 ASP.NET Core Razor 的语言服务。
  
  SQL Server Data Tools   17.8.119.0
  Microsoft SQL Server Data Tools
  
  TypeScript Tools   17.0.20920.2001
  TypeScript Tools for Microsoft Visual Studio
  
  Visual Basic 工具   4.8.0-7.23558.1+e091728607ca0fc9efca55ccfb3e59259c6b5a0a
  IDE 中使用的 Visual Basic 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。
  
  Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
  Microsoft Visual F# Tools
  
  Visual Studio IntelliCode   2.2
  Visual Studio 的 AI 协助开发。
  
  适用于 Google Test 的测试适配器   1.0
  启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。
  
  用于 Boost.Test 的测试适配器   1.0
  通过针对 Boost.Test 编写的单元测试启用 Visual Studio 测试工具。扩展安装目录中提供用户条款和第三方通知。

</p>
</details> 

like https://github.com/dotnet/winforms/issues/8354
      https://github.com/dotnet/roslyn/issues/66109

**Steps to Reproduce**:

1. Make A net framework console app project, for example 472, i try 4.8 has same results
![image](https://github.com/dotnet/roslyn/assets/24290190/39e46abf-91c6-4f71-b431-242beb18f629)

**project file path must contain Unicode characters，such as chinese characters. If the file path only contains English characters, the problem will not recur.**

Error Unable to resolve identifier: 'args"

<details><summary>Debug log</summary>
<p>
“ConsoleApp1_472.exe”(CLR v4.0.30319: DefaultDomain): 已加载“C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll”。
“ConsoleApp1_472.exe”(CLR v4.0.30319: DefaultDomain): 已加载“E:\****\BlueControl\ConsoleApp1_472\bin\Debug\ConsoleApp1_472.exe”。已加载符号。
程序“[10916] ConsoleApp1_472.exe”已退出，返回值为 4294967295 (0xffffffff)。
</p>
</details> 
debugger is don't work

2. Make A net 7 or net 8 console app project

![image](https://github.com/dotnet/roslyn/assets/24290190/5085d363-fa0a-4239-923e-61cd68de675e)

debugger is work

**Expected**: 
User is able to evaluate the value 

**dotnet info**: 
<details><summary>Details</summary>
<p>
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

已安装 .NET 工作负载:
 Workload version: 8.0.100-manifests.8d38d0cc
没有要显示的已安装工作负载。

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.320 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</p>
</details> 

**Further details**:  
vs2019 is all are ok,but this error has big difference by https://github.com/dotnet/winforms/issues/8354
V.S. Debugger not capturing local variables in any net framework project ( i try  WinForms\console\wpf)

**VisualStudioDeveloperCommunity Issues Under Investigation**
https://developercommunity.visualstudio.com/t/VS2022178C-The-identifier-is-not-defin/10520176

**Comment by eveloki** [comment] 2023-11-18 13:45
@isadorasophia  @kirsan31 @merriemcgaw @Olina-Zhang  help，plz；

**Comment by eveloki** [comment] 2023-11-18 15:03
Expected:

![image](https://github.com/dotnet/roslyn/assets/24290190/d938d38b-2d46-4d1f-a65d-3d6b38e5430b)

![image](https://github.com/dotnet/roslyn/assets/24290190/762a10f8-9052-45f6-9fe4-621ab028b04f)
Microsoft Visual Studio Enterprise 2022 (64 位) - LTSC 17.6
Verified it in different VS versions: cannot repro in 17.6.10 release build and previous versions,Due to personal energy constraints, I will test 17.9 Preview again

**Comment by eveloki** [comment] 2023-11-18 15:48
also repo in 17.9.0 Preview 1.0
![image](https://github.com/dotnet/roslyn/assets/24290190/253581e6-202a-4f7f-986a-bb7215d40453)

**Comment by Olina-Zhang** [comment] 2023-11-20 08:08
@eveloki I didn't reproduce it in 17.8.0 with .Console .Net framework application:
![image](https://github.com/dotnet/roslyn/assets/26474449/36408135-8371-47dc-b707-d6d895d30d50)

**Comment by eveloki** [comment] 2023-11-20 08:45
> @eveloki I didn't reproduce it in 17.8.0 with .Console .Net framework application: ![image](https://user-images.githubusercontent.com/26474449/284188671-36408135-8371-47dc-b707-d6d895d30d50.png)

why？I try reinstall Visual Studio, but also repo

**Comment by eveloki** [comment] 2023-11-20 09:25
I found an interesting piece of evidence.
look,in Net 7 app ,debugger think this project language is c#
![image](https://github.com/dotnet/roslyn/assets/24290190/2fb73708-4a4b-4931-b4d4-8a0c9c356d35)
but in .Net framework application,debugger think this project language is c++
![image](https://github.com/dotnet/roslyn/assets/24290190/c1c6c03e-0302-41ef-abff-28a989bf9a9d)

why? can I change this?

**Comment by Olina-Zhang** [comment] 2023-11-20 09:58
@eveloki Sorry, I have no idea.

**Comment by Finch-Liu** [comment] 2023-11-20 11:25
![image](https://github.com/dotnet/roslyn/assets/77435774/058b0e6e-8e94-4722-b2f9-849d836b5e66)
same issue as you , i download .net 8 last week and updated my VS to the latest version , today when i came back to work the issue showed up. it's freaky that the VS create my C# code as C++

**Comment by Fjukas** [comment] 2023-11-20 12:28
We have the same issue. Since installing .NET 8 and Visual Studio 17.8.0  most local variables are not recognized at all by the debugger and the symbols that it does recognize seems to be handled as C++ symbols. Strangely, some locals are recognized, but which ones seems random. In a method I'm debugging right now I can view one of two string locals, and a List<T>, but none of the parameters (which are a string, two DateTime:s and an int).

**Comment by isadorasophia** [comment] 2023-11-21 00:49
This looks very similar to #70580, could you confirm if your file path has unicode characters?

**Comment by Alwaysmissing** [comment] 2023-11-21 01:23
同样的问题，我的项目是.net framework 472 wpf，回滚到17.7.2就好了

**Comment by eveloki** [comment] 2023-11-21 01:38
> This looks very similar to #70580, could you confirm if your file path has unicode characters?

yes！,If the file path contains only English characters, the problem will not recur
​

**Comment by isadorasophia** [comment] 2023-11-21 01:43
@tmat  can you route this? it's impacting .NET Framework users on 17.8

**Comment by eveloki** [comment] 2023-11-21 01:48
@Olina-Zhang Can you reproduce it? when the file path contains unicode characters?

**Comment by WtW7707** [comment] 2023-11-21 01:50
> 你能重现它吗？当文件路径包含 Unicode 字符时？

I tried and it worked normally when the path was all in English

**Comment by Olina-Zhang** [comment] 2023-11-21 02:34
> @Olina-Zhang Can you reproduce it? when the file path contains unicode characters?

Yes, I can reproduce it now in that case:
![image](https://github.com/dotnet/roslyn/assets/26474449/59d15be6-5478-4d7a-b02b-4e1d3e24af3e)

**Comment by eveloki** [comment] 2023-11-21 02:53
> > @Olina-Zhang Can you reproduce it? when the file path contains unicode characters?
> 
> Yes, I can reproduce it now in that case: ![image](https://user-images.githubusercontent.com/26474449/284444024-59d15be6-5478-4d7a-b02b-4e1d3e24af3e.png)
@Olina-Zhang @isadorasophia
This is a very widespread and serious bug, It has seriously affected my work，a lot of feedback has said that this issue has been regressed multiple times in multiple versions, can we elevate this issue to a higher level？

**Comment by Olina-Zhang** [comment] 2023-11-21 07:24
@eveloki It needs to this repo owner to triage and look into it asap. @CyrusNajmabadi and @arkalyanms I see you are members of roslyn-ide team, can you look at this issue at your earliest convenience? Thanks!

**Comment by tmat** [comment] 2023-11-22 17:17
@Olina-Zhang I can't reproduce the issue. Which characters exactly are problematic?

**Comment by eveloki** [comment] 2023-11-22 19:11
@tmat  Test Project https://github.com/eveloki/ConsoleApp1_ChineseTest
My Project Path is "D:\Project\项目\ConsoleApp1中文测试\ConsoleApp1Net8中文测试"
I have updated to version 17.8.1, and the issue has improved a bit, but the debugger still does not work correctly. In my solution, 'ConsoleApp1中文测试' is a test project for .NET Framework 4.8. However, the debugger still thinks it's a C++ project and can only recognize local variables. It cannot display variables for other classes, and it even fails to display the parameters of the Main function. 'ConsoleApp1Net8中文测试' is a .NET 8 test project, and everything is normal. The debugger correctly recognizes the project language type and can display all variables. Please take a look at the video below. Thank you very much for helping to address this issue.

**.NET Framework 4.8**
https://github.com/dotnet/roslyn/assets/24290190/a3cb36e1-882b-400a-a1d2-c08f61430057

**.NET 8**
https://github.com/dotnet/roslyn/assets/24290190/19fe71e1-81a6-4eb1-8231-05f3c6c819d7

**Comment by tmat** [comment] 2023-11-22 19:18
Duplicate of https://github.com/dotnet/roslyn/issues/70580

**Comment by tmat** [comment] 2023-11-22 19:19
A workaround is available. See https://github.com/dotnet/roslyn/issues/70580

**Closed by tmat** 2023-11-22 19:18 UTC
Labels: Area-Interactive, untriaged

**Comment by godxing** [comment] 2023-12-05 03:29
BUG修复了吗，打开之前的项目调试就会有识别成C++，创建新项目就正常

**Comment by Porridge38** [comment] 2025-01-30 20:36
> [@Olina-Zhang](https://github.com/Olina-Zhang) I found an interesting piece of evidence. look,in Net 7 app ,debugger think this project language is c# ![image](https://github.com/dotnet/roslyn/assets/24290190/2fb73708-4a4b-4931-b4d4-8a0c9c356d35) but in .Net framework application,debugger think this project language is c++ ![image](https://github.com/dotnet/roslyn/assets/24290190/c1c6c03e-0302-41ef-abff-28a989bf9a9d)
> 
> why? can I change this?





https://stackdev.space/questions/what-is-the-best-way-to-obtain-a-string-with-special-characters-in-c
