### ISSUE TITLE
Inline Temporary Variable Refactoring produces invalid code

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18655] opened 2017-04-12 23:00 UTC
**Version Used**: VS2017 RTM

**Steps to Reproduce**:

1. Type the following code in a method
2. Trigger `inline-temporary-value` from the declaration of `t`

``` c#
            object o = null;
            var t = o as ValueTuple<int, int>?;
            if (t != null)
            {
            }
```

**Expected Behavior**:

``` c#
            object o = null;
            if (o is ValueTuple<int, int> t)
            {
            }
```

(with appropriate adjustment of uses of `t`)

**Actual Behavior**:

``` c#
            object o = null;
            if (o is ValueTuple<int, int>? t)
            {
            }
```

Along with a compilation error that you cannot use a nullable type with pattern-matching.

An alternative approach would be to refuse to apply the refactoring here, or not offer it in the first place.

**Comment by Pilchie** [comment] 2017-04-13 18:09
Dupe of https://developercommunity.visualstudio.com/content/problem/32721/ide0016-null-check-can-be-simplified-in-generic-cl.html, and fixed in https://github.com/dotnet/roslyn/pull/18178

**Closed by Pilchie** 2017-04-13 18:09 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
