### ISSUE TITLE
[Refactoring] Introduce Parameter

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#22051] opened 2017-09-11 22:22 UTC
*Note:* I thought I had filed this before, but couldn't find it. @wli3 was especially interested in this one and can provide more scenarios (I've also heard this from external customers a lot). 

This lets you add a new parameter to a method declaration from a selection.

**Comment by wli3** [comment] 2017-09-11 23:08
![image](https://user-images.githubusercontent.com/6993335/30300682-cdbfb17c-970a-11e7-943f-efc61ef1ce35.png)

This is very useful when there is a logic that doesn't belong to the method, in this case, use "stock shares multiply with price" should not be in a method that in charge of the display. This refactoring is error prone by hand. Because the logic need to be moved to the caller side

**Comment by DustinCampbell** [comment] 2017-09-12 17:23
This is potentially a dupe of https://github.com/dotnet/roslyn/issues/21446.

**Comment by wli3** [comment] 2017-09-13 01:33
It does look similar, maybe it can share majority of the code. But from user point of view, this case is move **some logic out of the method by passing result**, and #21446 is to add **some more data into this method**

**Comment by kuhlenh** [comment] 2017-09-25 16:14
Looks like it might be a dupe of this one: https://github.com/dotnet/roslyn/issues/20977

**Comment by wli3** [comment] 2017-09-25 17:22
@kuhlenh it is on different level. This issue if for push variable to method parameter, and #20977 is for push field to constructor. Underlying implementation might be the same but is it different from user point of view

**Comment by mikadumont** [comment] 2020-07-20 20:46
@wli3 We now have the option to add a parameter in the change method signature dialog. 

Documentation can be found here: https://docs.microsoft.com/en-us/visualstudio/ide/reference/change-method-signature?view=vs-2019

Is there anything missing from this current experience that `introduce parameter` offers?

**Comment by wli3** [comment] 2020-07-20 21:47
@mikadumont I don't think it is the same thing from reading the document. Maybe the feature request should be called "push up" parameter. The key is to move a variable that is currently local to the method to passed-in. That would require 1. signature change 2. all call site having this local to be passed-in.

It is used when some logic is not belonged to the method or the method is accessing fields that could be passed-in (so this method can be more generic or it can be moved to other classes).

**Comment by mikadumont** [comment] 2020-07-20 21:53
@sharwell and @CyrusNajmabadi to note @wli3's scenario.

**Comment by arnaud-fabre** [comment] 2020-07-21 10:08
I agree with @wli3 that this introduce parameter going beyond the current change signature refactoring. It would enable any expression to be pushed up to caller, including expression that use other method parameters like the example provided above with a Stock object.

As an added benefit, that refactoring could detect when a parameter becomes  unused (as the `stock` parameter in wil3's example) and ask to remove it in the same process.

**Comment by akhera99** [comment] 2021-02-11 19:49
Update:
Will be introducing a parameter for any expression in which the call-sites have access to the variables within the expression. This will be updated in the future when more complex cases get added.
There will be two options, one to simply go and refactor all the call-sites and another to create an inline method and trampoline. 
There will be no dialogue window unless there is a need in the future.

**Closed** 2021-04-22 20:16 UTC
Labels: Area-IDE, Feature Request, InternalAsk, help wanted
