### ISSUE TITLE
Crash in VB Workflow editor on select all and delete

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#2348] opened 2015-04-28 23:35 UTC
This doesn't repro always, and I haven't figured out the key yet, but while looking at internal bug 953882, I frequently hit this crash.

Callstack:
========
>	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.MapUpToSnapshot Line 89	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.GetSubjectBufferTextSpanInViewBuffer Line 76	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model.GetDefaultTrackingSpanEnd Line 149	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model.CreateModel Line 130	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.DoInBackgroundAsync Line 122	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.Do.AnonymousMethod__14_0 Line 86	C#
 	Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model>.ChainTaskAndNotifyControllerWhenFinished.AnonymousMethod__0 Line 136	C#

Dump file saved internally at <internalshare>\team\public\kevinpi\2348.dmp

**Comment by Pilchie** [comment] 2015-04-28 23:41
When this happens, the target has a single `SourceSnapshot` that matches `start`, but it doesn't appear to actually be projected anywhere.

@rchande @jasonmalinowski Are we perhaps missing some event that should cancel the model computation in this case?

**Comment by Pilchie** [comment] 2015-04-28 23:45
Oh, huh.  I found a simple repro.  Just hit Ctrl+Space in the expression editor with no text :frowning:

**Comment by jasonmalinowski** [comment] 2015-04-29 01:11
Is this just a problem where the projection being created by the expression editor is broken? Or has a bad edit resolver or something?

**Comment by Pilchie** [comment] 2015-04-29 15:34
Quite possibly - I don't know enough about how it's supposed to be set up.

**Comment by jasonmalinowski** [comment] 2015-05-01 00:45
Turns out @rchande has bug #1471 that might be a dupe of this.

**Comment by Pilchie** [comment] 2015-05-01 00:47
Yep, looks identical.  @rchande do you want to look into it?

**Comment by rchande** [comment] 2015-05-01 00:49
Perhaps. @jasonmalinowski mentioned that @brettfo might have a good repro for this.

**Comment by rchande** [comment] 2015-05-01 00:50
Oh, never mind, I see your earlier comment, @Pilchie.

**Comment by rchande** [comment] 2015-06-09 22:33
Merged into stabilization with #3383

**Comment by rchande** [comment] 2015-06-09 22:42
@Pilchie  please verify.

**Closed** 2015-06-09 22:42 UTC
Labels: Area-IDE, Bug

**Comment by brettfo** [comment] 2015-06-11 20:44
Confirmed fixed in `stabilization`.
