### ISSUE TITLE
Referencing a project that uses a Source Generator results in Source Generator running twice

### ISSUE THREAD

**Issue by flo-everett-xero** [dotnet/roslyn#59725] opened 2022-02-24 00:37 UTC
netcore 3.1.22
**Steps to Reproduce**:

1. Make a project (A) that uses a source generator imported through a nuget package
2. Make another project (B) that references the Project A
3. Make the Project A's `InternalsVisibleTo` the Project B
4. Try and run the Project B (in my case, this was an mstest project. unsure if this is relevant)

**Expected Behavior**:
Source generator is only run once, when building Project A. 

**Actual Behavior**:
Source generator is apparently run twice: 
```
error CS0436: The type 'GeneratedType' in 'SourceGenerator/SourceGenerator.Generator/GeneratedCode.g.cs' conflicts with the imported type 'GeneratedType' in 'Project.A, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
```

**Comment by jcouv** [comment] 2022-02-25 18:00
Tagging @chsienki for triage.

**Comment by b-straub** [comment] 2022-04-10 21:07
For me it only occurs with the old generator, switching to 'IIncrementalGenerator' fixed the problem.

**Comment by Lachanophobia** [comment] 2022-05-08 20:48
I have the same problem. 

just to work around this issue I added this to  "project (B)"

```
	<Target Name="DisableAnalyzers"
	        BeforeTargets="CoreCompile">
		<ItemGroup>
			<Analyzer Remove="@(Analyzer)"
			          Condition="'%(Filename)' == 'MyAnalyser"/> 
		</ItemGroup>
	</Target>
```
	
	
to remove the analyser.
	
I wish I could switch to IIncrementalGenerator but I have this issue.  https://stackoverflow.com/questions/72095200/c-sharp-incremental-generator-how-i-can-read-additional-files-additionaltexts

**Comment by ChristophHornung** [comment] 2023-02-22 17:05
> For me it only occurs with the old generator, switching to 'IIncrementalGenerator' fixed the problem.

@b-straub 
In my scenario this also happened for my IIncrementalGenerator. Do you have an example for one where it does not happen?

**Comment by b-straub** [comment] 2023-02-22 17:28
>Do you have an example for one where it does not happen?
> 
> 

https://github.com/b-straub/DexieNET/blob/829128e7f9c4ba17ae2f1025d66e0c9623e19f9c/DexieNETTableGenerator/Generator.cs

This is a different generator but with a similar architecture to the one I had initially the same problem. Hope this helps!

**Comment by Xo3-ToBapbl** [comment] 2024-03-04 20:44
@Lachanophobia could please elaborate your workaround? In my project analyzer added as project reference:
<ProjectReference Include="Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" /> 
Is it possible to use your solution in this case? What should I put instead of @(Analyzer) ?

**Comment by sharwell** [comment] 2024-03-04 21:50
This behavior is by design. NuGet packages are imported transitively by default. If you do not wish to have the package apply to projects further down stream, you need to specify `PrivateAssets="all"` on the `<PackageReference>` element that imported the source generator.

**Comment by Xo3-ToBapbl** [comment] 2024-03-05 08:36
@sharwell sorry but I don't get what you mean. I don't have nuget packages that import source generators. Instead of this, I have separate generator project in the solution which is referenced by main project. Did you mean that in this case running generator twice is by design?

**Comment by sharwell** [comment] 2024-03-05 14:03
@Xo3-ToBapbl Your issue is a different issue. Can you file a new issue for the behavior you are hitting? The first line of this issue is:

> Make a project (A) that uses a source generator imported through a nuget package

**Comment by Xo3-ToBapbl** [comment] 2024-03-11 08:57
@sharwell my apologies:( Thanks for you patience, probably will do new issue :)

**Comment by sharwell** [comment] 2024-03-11 12:38
Resolving as answered, since the `PrivateAssets="all"` attribute in https://github.com/dotnet/roslyn/issues/59725#issuecomment-1977522988 will fix the original issues closed above. Will address other issues once they are filed. 👍

**Closed by sharwell** 2024-03-11 12:38 UTC
Labels: Question, Area-Compilers

**Comment by ChristophHornung** [comment] 2024-03-11 12:49
@sharwell How do you set the `PrivateAssets="all"` on a Project reference? Isn't that only valid on nuget references?
