### ISSUE TITLE
C# formatting rules should have a "do not enforce" option

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#71218] opened 2023-12-11 23:38 UTC
There are some formatting rules where I want to have different conventions in different parts of my source code, like for `csharp_space_before_open_square_brackets` I want to sometimes have a space before an open bracket and sometimes not.  Please add an option value of `ignore` or something so that it doesn't try to enforce IDE0055 on such rules.

**Comment by CyrusNajmabadi** [comment] 2023-12-12 00:32
Closing out as a break dupe of a more extensible and flexible formatting system.

**Closed** 2023-12-12 00:32 UTC
Labels: Area-IDE, Feature Request, untriaged

**Comment by jez9999** [comment] 2023-12-12 14:41
@CyrusNajmabadi Is there a Github issue for said new formatting system?
