### ISSUE TITLE
CS1503 cannot convert from 'object' to

### ISSUE THREAD

**Issue by martore** [dotnet/roslyn#73098] opened 2024-04-19 03:45 UTC
**Version Used**:  Visual Studio 17.10.0 Preview 4.0, Visual Studio 17.10.0 Preview 3.0, .NET 8

**Steps to Reproduce**:

```
using AutoMapper;

var autoMapperCfg = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Car, Vehicle>().ReverseMap();
});

var autoMapper = autoMapperCfg.CreateMapper();

dynamic myCar = new Car();
Vehicle myVehicle = new();

var map =  autoMapper.Map<Vehicle, Car>(Activator.CreateInstance(myCar.GetType(), myVehicle)); // <-- CS1503

public class Vehicle { }
public class Car : Vehicle { }
```

**Diagnostic Id**: CS1503 cannot convert from 'object' to 'Vehicle'

**Expected Behavior**: Worked fine until Visual Studio 17.10.0 Preview 3.0.

**Comment by RikkiGibson** [comment] 2024-04-29 19:17
This looks like a duplicate of #72750. Please let us know if it continues to repro in the latest 17.10 preview.

**Closed by RikkiGibson** 2024-04-29 19:17 UTC
Labels: Bug, Area-Compilers
