### ISSUE TITLE
Make Auto-Implemented Properties being able to run code.

### ISSUE THREAD

**Issue by feinstein** [dotnet/roslyn#4182] opened 2015-07-28 21:30 UTC
I work with MVVM so usually I have to type a lot of redundant code just to make some backing fields, for example, I have to run some code in the Properties accessors, like a `NotifyPropertyChanged()`. This is really annoying because my Classes are structured in a way that I have Fields -> Constructor -> Properties, so basically, I have to keep going up and down in the Class to edit simple stuff. I think it can be better than that, and here is my idea:

I would like to do something like this:
```C#
public int MyInt
{
    get 
    {
		if (MyInt > 100)                
			return 100;                
		else 
			return MyInt; 
	}
	set 
	{ 
		MyInt = value; 
	}     
}
```
Currently this code doesn't make any sense to anyone, since it will go into an infinite loop, and the intent of the user is pretty clear, he just want to use the value inside the property, hence, the Backing Field.

So whenever the compiler sees this, it will just substitute the Property's name to an auto-generated Backing Field, removing the infinite loop.

I can't see how this will break previous code versions, since no one would be able to code anything that works trying to access the property itself. Maybe it could have a problem using the Setter inside the getter like: 

```C#
private _myInt
public int MyInt
{
    get { return MyInt++; }
    set { _myInt = value + 2; }
}
```

So maybe a `new` word could solve this cases, so there should be a explicit `new MyInt = 5;`

And also it could have a problem using the getter inside the setter like:

```C#
private _myInt
public int MyInt
{
    get { 
        if(_myInt > 100) return 100; 
        else return _myInt; 
    }
    set { _myInt = MyInt + value; }
}
```
And this case, to be honest I don't know which word is a better use to make the compiler understand your intent and not break previous code....maybe using `this` or `value` and `new value` to update the auto-generated backing filed, I don't know, I just want to share my idea so others can pick up and join the discussion.

I am not a specialist, so I might be saying something wrong, but please, focus on the idea in general: **To be able to run code, in the getter and setter, without the need to make a private backing field. Just complete automation of Properties.**

Thanks a lot!

**Comment by HaloFour** [comment] 2015-07-29 00:05
Dupe of #4025.  Auto-properties exist specifically as a shorthand for properties that don't have additional logic.  If you want to run code, write a proper property with a backing field.

**Comment by feinstein** [comment] 2015-07-29 00:14
Wow, so I have this idea in my head for months and I am only late for 8 days hahaha

But anyways, I know, I just wished it could be different.

**Closed** 2015-07-29 00:14 UTC

**Comment by jnm2** [comment] 2020-04-04 13:01
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
