### ISSUE TITLE
`Add null check` is offered for arguments with default value of `null`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66343] opened 2023-01-10 15:16 UTC
**Version Used**:
VS 17.5 Preview 2

**Steps to Reproduce**:
```cs
class MyClass
{
    void M(string [||]s = null)
    {

    }
}
```

**Expected Behavior**:
`Add null check`, `Add 'string.IsNullOrEmpty' check` and `Add 'string.IsNullOrWhiteSpace' check` are not offered

**Actual Behavior**:
Opposite to expected

**Comment by CyrusNajmabadi** [comment] 2023-01-10 17:21
I think we're overthinking things here. There are far more areas where we can provide high value to lots of users. Spending excessive time over fitting features is just not a good use of time and resources.

**Comment by Youssef1313** [comment] 2023-01-10 17:38
One can even come up with weird use cases like caller info attributes where someone might want to guard against a null.

**Comment by CyrusNajmabadi** [comment] 2024-10-25 18:14
Closing out as by design.

**Closed by CyrusNajmabadi** 2024-10-25 18:14 UTC
Labels: help wanted, Area-IDE
