### ISSUE TITLE
.editorconfig code analysis suppressions not always honored

### ISSUE THREAD

**Issue by kernst123** [dotnet/roslyn#62064] opened 2022-06-21 19:50 UTC
I have a solution with 38 project.
We have code the code analysis enabled for our projects and we have various code analysis issues suppressed in various .editorconfig files.
I have noticed that on some occasions I will observe compile errors ( we treat all warnings as errors ) due to a code analysis issue that is suppressed in an .editorconfig file.   It does not happen all the time.  Seems to be random.
I'm wondering if there might be a race condition for the analysis and reading the suppressions.
We have different levels of suppressions based on different .editorconfig files in different directories.
Most of the time it all works.  It is only on some occasion that it does not.
Any suggestions on possible logging that I might enable to help track down the issue?

**Comment by pinkfloydx33** [comment] 2022-06-26 09:38
I've been noticing this recently as well. Not as many projects in the solution, but same setup with editorconfig files at different levels. We see the same seemingly random behavior where suppressions stop working.

What I can say is that in our case at least, the suppressions are always additive--we're not suppressing a rule and then re-enabling it at a different level. We only ever add new suppressions.

**Comment by kernst123** [comment] 2022-06-27 12:11
Same here.  We have rules suppress at the top but as we go to lower level directories we add some extra suppressions.
I have 24 virtual cores so I see this problem more than others in our office.  Is there any logging that could be enabled to help diagnose this problem?
Is it possible that I could compile a version locally that I could debug?

**Comment by kernst123** [comment] 2022-07-04 13:05
Any updated on this or my questions?

**Comment by mavasani** [comment] 2022-07-05 05:18
@kernst123 @pinkfloydx33 This is a duplicate of https://github.com/dotnet/roslyn/issues/49718, which seems to be an intermittent race condition. Unfortunately, it has been very hard to track this down, though the investigations are still in progress.

**Closed by mavasani** 2022-07-05 05:18 UTC
Labels: Area-Analyzers, untriaged

**Comment by kernst123** [comment] 2022-07-05 12:51
How can you close it only because it is hard to reproduce??
I asked if there was something I could do on my end to help track down the issue.
This is going to become a bigger problem when developer machines have more cores.  I have 24 virtual cores which is why I think I see this more than others.
Please DON'T CLOSE THIS JUST BECAUSE IT'S NOT SIMPLE TO REPRODUCE!

**Comment by kernst123** [comment] 2022-07-05 12:59
Sorry my mistake.  I thought both were now closes.
