### ISSUE TITLE
Show exception description in C# XML documentation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59925] opened 2022-03-03 17:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-exception-description-in-C-XML-doc/1670731)._

---
The comment on the exception is not visible on mouseover.
It would be very helpful if the comment for the exception was displayed.
At the moment, only exception types are displayed
! [image.png] (https://aka.ms/dc/image?name=B8f805303ff9749f0833186c5156f4413637808166822723536_20220218-223121-image.png&tid=8f805303ff9749f0833186c5156f4413637808166822723536)

---
#### Feedback Bot on 2/20/2022, 10:54 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by Youssef1313** [comment] 2022-03-03 17:49
Duplicate of https://github.com/dotnet/roslyn/issues/1515

**Closed** 2022-03-09 19:37 UTC
Labels: Area-Interactive
