### ISSUE TITLE
VB: LightBulb offers weird CodeFix when System-Namespace is missing

### ISSUE THREAD

**Issue by vbspoony** [dotnet/roslyn#1916] opened 2015-04-10 09:58 UTC
Hey all,

take a look at the enclosed screenshot. I'm getting this CodeFix suggestion, when the System-Namespace is commented out. Without it, the VB compiler says it cannot convert DateTimeOffset? to DateTimeOffset and is offering a Widening operator.
![2015-04-10 11_49_27-wrongwideningtooltip](https://cloud.githubusercontent.com/assets/9663150/7085630/d1246afc-df78-11e4-81de-f0a412e39f9f.png)

**Comment by jmarolf** [comment] 2015-04-10 18:12
I believe I fixed this, are you using CTP 6?

**Comment by SLaks** [comment] 2015-04-12 13:14
Dupe of #559

**Comment by srivatsn** [comment] 2015-04-13 20:57
Closing since this has been fixed and the fix should show up in the next preview.

**Closed by srivatsn** 2015-04-13 20:57 UTC
Labels: Area-Analyzers
