### ISSUE TITLE
Go to implementation on abstract items returns both the abstract definition + override/impl

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#44295] opened 2020-05-15 17:49 UTC
**Version Used**: 
![image](https://user-images.githubusercontent.com/2008729/82080538-9b6d0f80-9699-11ea-97ee-328e605d1816.png)

**Steps to Reproduce**:

1. New console app
2. Paste the following minimal repro:
```C#
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Go to impl on Foo in the next line
            Foo abc;
        }

        public abstract class Foo { }
        public class FooImpl : Foo { }
    }
}
```
3. Go to implementation on `Foo` in the `Foo abc;` line.

**Expected Behavior**:
It brings the cursor to `FooImpl`

**Actual Behavior**:
It opens up a window with two entries:
![image](https://user-images.githubusercontent.com/2008729/82080510-8b553000-9699-11ea-9059-a4a87b54b7ff.png)

**Notes**:
This also happens on overrides. OmniSharp in VSCode does the "expected" behavior so this is specific to non-VSCode scenarios.

/cc @CyrusNajmabadi

**Comment by jinujoseph** [comment] 2020-05-20 19:27
Duplicate of #26167

**Comment by jinujoseph** [comment] 2020-05-20 19:28
cc @jcouv

**Closed** 2020-05-20 19:28 UTC
Labels: Area-IDE
