### ISSUE TITLE
async keyword overly sensitive in VS2015

### ISSUE THREAD

**Issue by brockallen** [dotnet/roslyn#5128] opened 2015-09-10 18:10 UTC
When I write a method that returns `Task` and apply thr `async` modifier, then the intellisense in VS2015 seems to have lots of problems. If anything in the method doesn't compile, then the intellisense is broken. This is often due to something later in the method with a syntax error – it causes intellisense for everything prior in the method to just now work (this used to be ok in VS2013).

**Comment by Pilchie** [comment] 2015-09-10 18:12
Thanks for the report - can you give a specific code sample where you see this?  We have a lot of fault tolerance rules in place, and this is too general to be actionable.

**Comment by brockallen** [comment] 2015-09-10 18:36
I'm writing some ASP.NET 5 middleware as an anonymous delegate, and if I write something like this:

```
            app.Use(async (ctx, next) =>
            {
                ctx.Authentication.AuthenticateAsync()
            });
```

with keyboard focus inside the `()` above and I hit Ctrl-Shift-Space in VS and I get no intellisense. Half of the method is green squiggles and the other is red squiggles. Intelliense is dead at this point. 

This exact same typing workflow worked in VS2013.

Thanks.

**Comment by brockallen** [comment] 2015-09-10 18:38
Even if I add `async`, then I get the same behavior:

```
            app.Use(async (ctx, next) =>
            {
                await ctx.Authentication.AuthenticateAsync();
            });
```

**Comment by gafter** [comment] 2015-09-11 03:11
Please let us know if this IDE behavior is caused by poor compiler error recovery.

**Comment by brockallen** [comment] 2015-09-11 03:36
@gafter i'm not sure what that means.

**Comment by Pilchie** [comment] 2015-09-11 03:50
That was meant for me (with the addition of the Area-IDE label)

**Comment by Pilchie** [comment] 2015-09-11 15:53
A standalone repro seems to be:

``` C#
using System;
using System.Threading.Tasks;

public delegate Task RequestDelegate(HttpContext context);

public class AuthenticationResult { }

public abstract class AuthenticationManager
{
    public abstract Task<AuthenticationResult> AuthenticateAsync(string authenticationScheme);
}

public abstract class HttpContext
{
    public abstract AuthenticationManager Authentication { get; }
}

interface IApplicationBuilder
{
    IApplicationBuilder Use(Func<RequestDelegate, RequestDelegate> middleware);
}

static class IApplicationBuilderExtensions
{
    public static IApplicationBuilder Use(this IApplicationBuilder app, Func<HttpContext, Func<Task>, Task> middleware)
    {
        return app;
    }
}

class C
{
    void M(IApplicationBuilder app)
    {
        app.Use(async (ctx, next) =>
        {
            await ctx.Authentication.AuthenticateAsync($$);
        });
    }
}
```

The issue seems to be that once we see the error in the lambda, we immediately fall back to only considering the instance method `Use`.  Either making both `Use` methods instance methods on the interface, or making both extension methods allows sig help to work here.

**Comment by Pilchie** [comment] 2015-09-11 16:29
@brettfo Can you confirm that the fallback is happening in the compiler and hand off if so?

**Comment by brettfo** [comment] 2015-09-11 17:58
Like @Pilchie suggested, signature help isn't being given the extension method symbol.  Stepping into the binder it looks like [`GetCandidateExtensionMethods()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/InContainerBinder.cs,1c63d4a50d3fc332,references) is returning zero results.

I'm replacing the `Area-IDE` tag with `Area-Compilers` and clearing out the assignee field.

**Comment by AlekseyTs** [comment] 2015-10-01 20:37
Additional details from @brettfo: the ID is calling SemanticModel.GetMemberGroup API for ```ctx.Authentication.AuthenticateAsync``` node and gets an empty group.

**Comment by AlekseyTs** [comment] 2015-10-02 20:34
This is not going to be a simple fix, I think. 
The fact that C# compiler is unable to combine both instance and extension methods within a single ```Microsoft.CodeAnalysis.CSharp.MethodGroupResolution``` is at the root of the issue. Given the same call site, AnalyzedArguments stored inside MethodGroupResolution are going to be different for a group of instance methods and for a group of extension methods. I think for extension methods it includes the receiver as well. 
This creates a problem when we have candidates of both kinds and none of them are applicable. Since the candidates of different kind cannot be merged into a single MethodGroupResolution, Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal have to choose one or another and, when none of the candidates are applicable, it prefers to keep instance methods. The information about presence of extension methods candidates is lost after that point and the rest of the binding pipeline operates as if they do not exist. 
```
Microsoft.CodeAnalysis.CSharp.Binder
        private MethodGroupResolution ResolveMethodGroupInternal(
            BoundMethodGroup methodGroup,
            CSharpSyntaxNode expression,
            string methodName,
            AnalyzedArguments analyzedArguments,
            bool isMethodGroupConversion,
            ref HashSet<DiagnosticInfo> useSiteDiagnostics,
            bool inferWithDynamic = false,
            bool allowUnexpandedForm = true)
```

For our original repro scenario (this is GetMemberGroupInsideIncompleteLambda_01 unit-test, see commit https://github.com/AlekseyTs/roslyn/commit/1d2d8ad790e0c344fa0e7b1726417e1a21f64a85), for the ```app.Use``` invocation we end up with MethodGroupResolution containing only one method , ```IApplicationBuilder IApplicationBuilder.Use(System.Func<RequestDelegate, RequestDelegate> middleware)```, which is an instance method. The other candidate, ```IApplicationBuilder IApplicationBuilderExtensions.Use(this IApplicationBuilder app, System.Func<HttpContext, System.Func<System.Threading.Tasks.Task>, System.Threading.Tasks.Task> middleware)```, is getting dropped due to the reason described earlier (at this point, it is also considered inapplicable because the lambda is incomplete and, therefore, has errors). This fact can be observed by examining result returned by SemanticMode.GetSymbolInfo API for ```app.Use```, CandidateSymbols consists of only one symbol, which represents the instance method candidate. In contrast, if both methods were instance methods, or both methods were extension methods, both of them would be in CandidateSymbols set (see GetMemberGroupInsideIncompleteLambda_03 and GetMemberGroupInsideIncompleteLambda_04 unit-test).

Eventually, Microsoft.CodeAnalysis.CSharp.Binder.CreateBadCall is getting called to create a bound node for the ```app.Use``` invocation.
```
Microsoft.CodeAnalysis.CSharp.Binder
        private BoundCall CreateBadCall(
            CSharpSyntaxNode node,
            string name,
            BoundExpression receiver,
            ImmutableArray<MethodSymbol> methods,
            LookupResultKind resultKind,
            ImmutableArray<TypeSymbol> typeArguments,
            AnalyzedArguments analyzedArguments,
            bool invokedAsExtensionMethod,
            bool isDelegate)
```
It has a special logic, if there is only one candidate method, all arguments are strongly tied to that candidate. I.e. bound node for the lambda will be a BoundLambda bound against target delegate type for that single candidate. In our case the target delegate type is System.Func<RequestDelegate, RequestDelegate>, which doesn’t match the shape of the lambda, therefore, no meaningful semantic information can be provided for the body of the lambda. 

However, the diagnostics reported for the invocation ``` ctx.Authentication.AuthenticateAsync```:
```
error CS7036: There is no argument given that corresponds to the required formal parameter 'authenticationScheme' of 'AuthenticationManager.AuthenticateAsync(string)'
   await ctx.Authentication.AuthenticateAsync();
```
might lead an observer into thinking that compiler actually considered extension method as a “better” inapplicable candidate. That is not the case. There is a logic in Microsoft.CodeAnalysis.CSharp.OverloadResolutionResult<TMember>.ReportDiagnostics<T>
```
Microsoft.CodeAnalysis.CSharp.OverloadResolutionResult<TMember>
        internal void ReportDiagnostics<T>(
            Binder binder,
            Location location,
            DiagnosticBag diagnostics,
            string name,
            BoundExpression receiver,
            AnalyzedArguments arguments,
            ImmutableArray<T> memberGroup, // the T is just a convenience for the caller
            NamedTypeSymbol typeContainingConstructor,
            NamedTypeSymbol delegateTypeBeingInvoked,
            CSharpSyntaxNode queryClause = null,
            bool isMethodGroupConversion = false) where T : Symbol
```
to report errors from lambda bodies, if there are any lambdas among the arguments. And prioritize these errors over other argument errors. The errors are collected across all trial bindings performed for a given lambda. That is why an error related to a candidate dropped by ResolveMethodGroupInternal makes its way to the top, even though it is not even related to the method compiler has.

I think that the proper way to address the issue is to be able to combine candidates of different kinds in a single MethodGroupResolution without having to make an arbitrary choice between instance and extension methods.

**Closed** 2016-01-06 18:24 UTC
Labels: 4 - In Review, Area-Compilers, Bug

**Comment by brockallen** [comment] 2016-01-06 18:28
"Fixed"? Yay, thanks!

**Comment by AlekseyTs** [comment] 2016-01-06 18:28
@brettfo, Please verify that IDE is getting information it expects.

**Comment by brettfo** [comment] 2016-01-06 20:42
Confirmed that the IDE is getting what it expects and the scenario works with the merge of #7740.
