### ISSUE TITLE
MSBuildWorkspace can't compile Class Library referencing PCL

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#2824] opened 2015-05-16 03:48 UTC
Related to #560 and various dupes #1373, #2700, #1894

We first noticed this problem when trying to compile [XUnit](https://github.com/xunit/xunit) with `MSBuildWorkspace`. All the Desktop projects failed to build but all the PCLs were fine.

To repro:

 - Create new ClassLibrary project (I've called mine Desktop)
 - Create new PortableClassLibrary project (I'm called mine PortableClassLibrary)
 - Create reference to PortableClassLibrary in ClassLibrary
 - The projects must interact in some way. For example:

In the ClassLibrary I use the following:

```CSharp
namespace Desktop
{
    public class Class1
    {
        public void MyMethod()
        {
            var test = new PortableClassLibrary.Class1();
            var obj = test.PCLMethod();
        }
    }
}
```

And in the PCL:

```CSharp
namespace PortableClassLibrary
{
    public class Class1
    {
        public object PCLMethod()
        {
            return new object();
        }
    }
}
```

Now in another solution try to compile the above with Roslyn:

```CSharp
var msws = MSBuildWorkspace.Create(new Dictionary<string, string> { { "CheckForSystemRuntimeDependency", "true" } });
var soln = msws.OpenSolutionAsync(@"C:\Users\Josh\Documents\GitHub\Orange\Desktop\Desktop.sln").Result;
var comp = soln.Projects.First().GetCompilationAsync().Result;
var errs = comp.GetDiagnostics().Where(n => n.Severity == DiagnosticSeverity.Error).ToList();
//One error
```

*Expected:* Project builds without errors (as it does in Visual Studio).

*Actual:* We receive the following error:
```
C:\Users\Josh\Documents\GitHub\Orange\Desktop\Desktop\Class1.cs(14,23): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

**Comment by JoshVarty** [comment] 2015-05-16 03:50
One note: We receive the error regardless of whether or not `CheckForSystemRuntimeDependency` is set to true or omitted.

**Comment by Pilchie** [comment] 2015-05-27 22:46
I've been looking at this, and I *think* that putting:

``` C#
                { "DesignTimeBuild", "true" },
                { "IntelliSenseBuild", "true" },
                { "BuildingInVisualStudio", "true" },
```

into your properties *should* work, but doesn't seem to on my RC VM.  Running msbuild on the command line with those seems to correctly `ImplicitlyExpandDesignTimeFacades` according to my diagnostic log.

Having trouble debugging the actual msbuild workspace code to figure out what's up, but will keep looking.

**Comment by mattwar** [comment] 2015-05-28 04:21
I think you meant "BuildingInsideVisualStudio"

**Comment by Pilchie** [comment] 2015-05-28 16:45
Yes, I did mean that, but it doesn't help either :frowning:

**Comment by JoshVarty** [comment] 2015-05-29 03:05
You mention it doesn't work on your RC VM. Does it work on later builds?

**Comment by Pilchie** [comment] 2015-05-29 03:29
No, I broke it worse with the "fix" to the other PCL bugs. :frowning: I'm going to address that, and then see what happens on recent builds.

**Comment by Pilchie** [comment] 2015-06-10 02:50
Well, even with my fix for the other PCL bugs, we still have this issue.  It looks like the problem is here:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/MSBuild/ProjectFile/ProjectFile.cs,63

Without building ResolveProjectReferences, the right info doesn't get into the ImplicitlyExpandDesignTimeFacades, so we don't add them.

@mattwar Do you know the reason for the comment about not wanting the referenced project's output path?  I think to fix this we would need to run ResolveProjectReferences and deal with filtering the output back out.

**Comment by mattwar** [comment] 2015-06-10 14:43
@pilchie it means that it is not possible to filter out the referenced project's assemblies from the references lists without knowing the output path of each of the referenced projects. To know that, you have to have load and evaluate all the referenced projects, which is considerable slower because you are redundantly doing this for each project.

**Comment by Pilchie** [comment] 2015-06-10 15:23
I wonder if there is some item metadata on the resolved references that we could use to filter them back out.

**Comment by mattwar** [comment] 2015-06-10 17:28
You can filter them once they are passed back to the workspace, but the metadata references have already been built by then, and these days that's expensive since they preload the metadata now. It would take some refactoring similar to what I was doing for the app domain change, so that references are not computed in this part of the code, but it could be done.

**Comment by Pilchie** [comment] 2015-06-10 17:38
Now that we pass `BuildingInsideVisualStudio`, we shouldn't be actually building the referenced projects anymore, just invoking the `GetTargetPath` or `GetTargetPathWithTargetPlatformMoniker` target.

**Comment by mattwar** [comment] 2015-06-10 18:15
That wasn't the problem. The names of the project's output assemblies (if they existed and maybe also if not, don't remember) get added to the list of metadata references, which would turn into metadata, which would then have duplicates of the symbols coming from the referenced projects from source, which would lead to lots of errors.

**Comment by Pilchie** [comment] 2015-06-10 21:00
Matt is looking at a fix to this.

**Comment by Pilchie** [comment] 2015-06-11 21:52
Closing since this is fixed in stabilization.

**Closed by Pilchie** 2015-06-11 21:52 UTC
Labels: Area-IDE, Bug

**Comment by allancm** [comment] 2015-07-17 22:55
How do we know the build number where the fix is included?
I have the version 1.0.0.50417 of .NET Compiler Platform SDK Templates for RC.
Downloaded from https://visualstudiogallery.msdn.microsoft.com/e2e07e91-9d0b-4944-ba40-e86bcbec1599

**Comment by Pilchie** [comment] 2015-07-18 23:07
You will need the 1.0 NuGet packages that match the VS RTM release coming out on 7/20.  You also need the RTM version of the MSBuild targets to completely address the scenario.
