### ISSUE TITLE
Move type to carries extra preceding #endregion

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#35517] opened 2019-05-04 07:14 UTC
**Version Used**: VisualStudio.16.Preview/16.1.0-pre.2.0+28822.285

**Steps to Reproduce**:

```C#
public class Foo
{
    #region Region1
    class Xyz {}
    #endregion

    #region Region
    public class Bar // Move type to 'Bar.cs'
    {
    }
    #endregion
}
```

**Actual Behavior**:
```C#
    public partial class Foo
    {
        #endregion

        #region Region
        public class Bar // Move type to 'Bar.cs'
        {
        }
        #endregion
    }
```

**Expected Behavior**:
```C#
    public partial class Foo
    {
        #region Region
        public class Bar // Move type to 'Bar.cs'
        {
        }
        #endregion
    }
```

(related #19613)

**Comment by vatsalyaagrawal** [comment] 2019-05-06 18:48
Duplicate of #32428

**Closed by vatsalyaagrawal** 2019-05-06 18:48 UTC
Labels: Area-IDE
