### ISSUE TITLE
Running Fix All across a project or solution doesn't always fix all

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#247] opened 2015-02-04 23:49 UTC
Ported from TFS WorkItem: <b>1114847</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Open Roslyn.sln.</P>
<P>2.&nbsp;Delete the contexts of a bunch of the PublicAPI.txt files.</P>
<P>3. Apply the DeclarePublicAPI fix across the whole solution.</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG></P>
<P>All public APIs across the whole solution are added to the proper PublicAPI.txt files.</P>
<P>&nbsp;</P>
<P><STRONG>Actual</STRONG></P>
<P>Not all PublicAPI.txt files are updated. Sometimes even the ones that are updated are missing items that should be present.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Tom Meschter (1/26/2015 11:14:51 AM)

<p>This is something I ran across while writing the DeclarePublicAPI analyzer and fix. Running Fix All across a document always worked, but when I ran Fix All across a project or solution it didn't actually fix everything--sometimes it only found and fixed a few issues.&nbsp;I wound up running it repeatedly until it found everything.</p>
<p>&nbsp;</p>
<p>My guess is that we don't block waiting for the Solution Crawler to actually find all issues across the solution, and instead the Fix All provider just gets whatever issues it is currently aware of. I think it would be preferable to block until we really have found all the problems and can fix them all at once.</p>

------------------------------

**Comment by mavasani** [comment] 2015-03-03 22:02
I spend some time playing around with this and have a few observations:

1. Repro (1): Remove all entries from PublicAPI.txt in CodeAnalysis.csproj and open any one source file with a public declaration and invoke fix all in project.

Behavior with Roslyn in Main hive: Only the Public API entries for that source file get added.
Behavior in RoslynDev hive: All entries for entire project always added.

I think Heejae's recent fix to state management might have fixed this.

2. Repro (2): Remove all entries from PublicAPI.txt in CodeAnalysis.csproj and CSharpCodeAnalysis.csproj and trigger a fix all in Solution from a source file in CodeAnalysis.csproj

Behavior: All entries for CodeAnalysis are correctly generated but the entries for CSharpCodeAnalysis.csproj are partial in that all the entries for member symbols are generated but no entries for top level declarations are generated. I think the issue might be that because CodeAnalysis is a project reference of CSharpCodeAnalysis, and CodeAnalysis is in error due to removed PublicAPI entries, either the analyzer OR the IDE driver OR the semantic model bails out on declaration symbols causing this behavior. I'll investigate further to find the root cause here. However, this may not be that high pri an issue due to a referenced project being in error.

3. Repro (3): Remove all PublicAPI.txt entries from independent projects and ranging across VB and C# (CSharpCodeAnalysis.csproj, BasicCodeAnalysis.csproj and Workspaces.csproj). Trigger fix all in solution from a source file in CSharpCodeAnalysis.csproj

Behavior: All correct entries generated for both C# projects, but no entries generated for BasicCodeAnalysis.csproj. This is probably more of a missing feature in current FixAll implementation rather then a bug. FixAll was always designed to work for a specific project language from which it is invoked, we also had a backlog work item to expand it to enabling solution wide cross language fix all However, given that the DeclarePublicAPI analyzer and fixer both support both languages, it does indeed seem redundant to invoke this from both language projects. @srivatsn do you have a github issue to track this backlog item (solution wide cross language fix all), otherwise I can open one.

**Comment by srivatsn** [comment] 2015-03-04 00:55
No there's not github issue tracking it. Please file one.

**Comment by mavasani** [comment] 2015-03-04 09:35
Filed #1011 for FixAll support across all supported languages of the underlying fixer.

Regarding Repro (2), I have been unable to repro it after trying it numerous times. It only reproed once for me, but since then it seems to work fine. This is most likely a skeleton assembly issue where skeleton assembly for CodeAnalysis was not available for one time it did repro. It may also still be a race condition in our diagnostic engine, but its very hard to tell until we have a consistent repro. I am resolving this for now, @tmeschter please re-activate if you still have a reasonably consistent repro.

**Comment by tmeschter** [comment] 2015-03-26 16:38
New repro:

1. Use InstallDogfood to install Main-Signed-Release 20150325.1.
2. Open Roslyn.sln.
3. Close all open files.
4. Open PublicAPI.txt in Workspaces.Desktop.
5. Remove the first five lines (the ones referring to `CommandLineProject` and `FileTextLoader`).
6. Open CommandLineProject.cs.
7. Put the cursor on `CommandLineProject`, open the light bulb, and click the link to fix all occurrences in the project.

**Expected:**
Preview shows fixes for both `CommandLineProject` and `FileTextLoader`.

**Actual:**
Preview shows fixes for only `CommandLineProject`.

**Comment by tmeschter** [comment] 2015-03-26 16:39
@mavasani This issue still occurs.

**Comment by tmeschter** [comment] 2015-03-26 16:44
I just noticed that if I wait long enough eventually errors for all the missing symbols in PublicAPI.txt show up in the Error List. If I then run Fix All across the project it does, in fact, fix all.

So it seems that when running Fix All we aren't waiting for all the diagnostics to be computed before running the fixer.

**Comment by srivatsn** [comment] 2015-03-26 17:24
I suspect this is because normally while computing fixes we won't force CompilationEndActions. In the case of a fixall since it's a blocking long running operation anyway, we should force compilationendactions but I suspect it's going through a similar codepath and not waiting for those diagnostics.

**Comment by mavasani** [comment] 2015-03-30 17:40
@srivatsn Ah, that seems very likely. I'll investigate. However, does this qualify of an rc2 milestone or should it be pushed out to 1.0 (stable)?

**Comment by srivatsn** [comment] 2015-03-30 17:53
1.0 sounds fine.

**Comment by mavasani** [comment] 2015-04-01 19:04
Moved back to @tmeschter for verification.

**Comment by tmeschter** [comment] 2015-04-17 19:24
@mavasani Nope, still repros on 20150417.1. :-(

**Comment by mavasani** [comment] 2015-04-17 20:49
Hmm intersting, doesn't repro for me after multiple attempts.. I'll continue investigating.

**Comment by mavasani** [comment] 2015-04-29 09:00
@tmeschter So, I finally got a repro for this, though it repros only intermittently for me.

For the cases where I got a repro, the issue seems to be that `IDELatestDiagnosticGetter`(http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs,517), ends up re-using **stale** previously cached/persisted diagnostics for some closed files (`FileTextLoader.cs` for your repro). The below screenshot shows that when computing diagnostics for FileTextLoader.cs, the data/semantic version of cached diagnostic data and requested version data are different, though their text versions are identical. This is because the additional file contents have changed for the project in between. However, `CheckSemanticVersions` still returns true causing stale existingData (with 0 diagnostics) to be re-used for this file.

![stale_diagnostics](https://cloud.githubusercontent.com/assets/10605811/7387599/59c5e5a4-ee13-11e4-8e0e-0d1d71a1cab7.png)

@heejaechang seems to have fixed exactly this issue in https://github.com/dotnet/roslyn/commit/9ce72ee0aa5dcfd02c2bd0ae3530e7382abdb01a. Now `CheckSemanticVersions` cannot return if data or text versions differ for existing and requested versions. HeeJae, please correct me if this is not true.

@tmeschter I cannot repro this bug in RoslynDev hive after numerous attempts. So I am going to verify this scenario on the next signed drop that comes out, and if it doesn't repro then request you to do the same to confirm whether or not this indeed fixed.

**Comment by heejaechang** [comment] 2015-04-29 09:24
Yes. Previous dependent semantic version checking across VS session was too easy to get broken. Now we will only use one from same vs session. To confirm. You can delete .vs folder and see whether it repros.



-          heejae

**Comment by mavasani** [comment] 2015-04-29 09:43
@heejaechang Yes, that fixed it but started to repro again after a while. I'll wait for next drop with your fix and give it a try again.

**Comment by heejaechang** [comment] 2015-04-29 09:51
Ya, once it has .vs saved. it can.


-          Heejae

**Comment by mavasani** [comment] 2015-04-30 22:23
@tmeschter I am unable to repro this on the latest signed drop. Moving it back to you, once again, to verify!

**Closed** 2015-04-30 22:23 UTC
Labels: 2 - Ready, Area-Analyzers, Bug
