### ISSUE TITLE
Navigating between lines in "Find References" result changes focus in an unexpected way

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#56313] opened 2021-09-10 00:11 UTC
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 5.0 [31706.66.main]

Observed:
When I navigate to the previous/next line in the result window by using arrow keys on the keyboard, focus switches to the source window where the reference was found

Expected:
The source with the reference should be "brought forward", but the focus should stay in the result window. It should be possible to "arrow" through all lines in the result without having to return focus after every keystroke. This is how it used to work in VS 2019.

**Comment by CyrusNajmabadi** [comment] 2021-09-10 00:45
@ryzngard @davidwengier did anything change here?  I seem to recall some change in the flags we pass to vs to navigate.

**Comment by ryzngard** [comment] 2021-09-10 19:05
https://github.com/dotnet/roslyn/pull/43586 

This changed the behavior a while back, and is the only change I know of that I did. There are 2 cases where this happens: 

1. We're navigating to an external item that is navigable. 
2. There is only one result in FAR. 

@AlekseyTs does that align with what you're seeing?

**Comment by AlekseyTs** [comment] 2021-09-10 20:40
> We're navigating to an external item that is navigable.

I am not sure what "external" means in this context.

> There is only one result in FAR.

I have multiple lines in the result and trying to "arrow" between them.

**Comment by ryzngard** [comment] 2021-09-10 20:51
@AlekseyTs  can you take a screen recording? Locally I'm not seeing the same behavior. 

![373686bf-bf43-469f-81b0-b8a79ba26dfd](https://user-images.githubusercontent.com/475144/132916108-329a895f-fc5e-44e2-a166-b768153bc245.gif)

**Comment by AlekseyTs** [comment] 2021-09-13 20:14
@ryzngard I tried Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit) Version 17.0.0 Preview 5.0 [31710.301.main] and still see the behavior that I showed to you off line.

**Comment by ryzngard** [comment] 2021-09-13 21:51
@AlekseyTs please record a trace with the feedback tool and send to me. This is not the intended behavior and we haven't recently changed this. There might be some other setting that is impacting this.

**Comment by AlekseyTs** [comment] 2021-09-14 22:12
@ryzngard I uploaded various logs through VS Feedback mechanism - https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1404370

**Comment by ryzngard** [comment] 2021-09-15 18:49
Thanks @AlekseyTs . I'm going to use that to drive the issue for now since I need to loop in the editor team. Closing this as a dupe against AB#140437

**Closed by ryzngard** 2021-09-15 18:49 UTC
Labels: Bug, Area-IDE, Investigation Required, IDE-Navigation, Navigation-FAR
