### ISSUE TITLE
DeclarePublicAPIFix code fix crashing

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#33644] opened 2019-02-24 20:36 UTC
**Version Used**:
dev16 preview. Doesn't reproduce in dev15.

**Steps to Reproduce**:

1. Add public API to Microsoft.CodeAnalysis.CSharp
2. Inspect the new diagnostic on the member not added to PublicAPI.Unshipped.txt
3. Run the DeclarePublicAPIFix

**Expected Behavior**:

Line added to PublicAPI.Unshipped.txt

**Actual Behavior**:

Code fix is disabled with the exception/stack trace below:
```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAdditionalDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
```

**Comment by 333fred** [comment] 2019-03-18 21:46
@genlu @RikkiGibson dupe of https://github.com/dotnet/roslyn/issues/33884. Workaround is to close the unshipped API txt file.

**Closed** 2019-03-18 21:46 UTC
Labels: Area-IDE, Area-Infrastructure, Resolution-Duplicate
