### ISSUE TITLE
NullReferenceException in VB ReplaceMethodWithPropertyCodeRefactoringProvider

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#17503] opened 2017-03-01 22:36 UTC
**Version Used**: D15Rel 26223.01

**Steps to Reproduce**:

1. Create a new VB class library
2. Inside `Class1` add the following:
  ```
  Sub Method()

  End Sub
  ```
3. In the body of `Method` type `sub<space>`
4. Wait a moment

**Expected Behavior**:

No errors occur

**Actual Behavior**:

A yellow info bar pops up stating "'ReplaceMethodWithPropertyCodeRefactoringProvider' has encountered an error and has been disabled." and offering to re-enable the refactoring.

If the refactoring is re-enabled, this is easily reproduced again by making edits after `sub`.

Exception:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.ReplaceMethodWithProperty.VisualBasicReplaceMethodWithPropertyService.GetMethodDeclaration(SyntaxToken token)
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Pilchie** [comment] 2017-03-08 18:27
Dupe of #17368.

**Closed by Pilchie** 2017-03-08 18:27 UTC
Labels: Area-IDE, Bug
