### ISSUE TITLE
Using Roslyn for doing code modifications from a console app, gives sporadic exceptions

### ISSUE THREAD

**Issue by mterwoord** [dotnet/roslyn#12005] opened 2016-06-14 18:54 UTC
**Version Used**: 
Nuget version 1.2.2

**Steps to Reproduce**:

This is going to be complex. 
- Grab CosmosOS/Cosmos@d144745. This is the source code i'm running the console app on
- Grab CosmosOS/RoslynRefactorings@5d0fc1b. This is the console app.

The console app assumes the cosmos repository is cloned at ```c:\Data\Sources\OpenSource\Cosmos```
This can be changed in Program.cs

**Expected Behavior**:
When running the console app, it's supposed to output a whole lot of dots to the console (meaning it succeeded modifying a single occurrence), and then exit because it's done. 

**Actual Behavior**:
Sporadically, I'm seeing the following error:

```
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Kan een object van het type Microsoft.CodeAnalysis.Text.CompositeText niet converteren naar het type Microsoft.CodeAnalysis.Text.ChangedText.
   at Microsoft.CodeAnalysis.Text.ChangedText.WithChanges(IEnumerable`1 changes)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
   at RoslynTest.Program.<DoMainAsync>d__5.MoveNext() in C:\Data\Sources\OpenSource\CosmosRoslynRefactorings\RegistersToEnumRefactoring\Program.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at RoslynTest.Program.Main(String[] args) in C:\Data\Sources\OpenSource\CosmosRoslynRefactorings\RegistersToEnumRefactoring\Program.cs:line 33
---> (Inner Exception #0) System.InvalidCastException: Kan een object van het type Microsoft.CodeAnalysis.Text.CompositeText niet converteren naar het type Microsoft.CodeAnalysis.Text.ChangedText.
   at Microsoft.CodeAnalysis.Text.ChangedText.WithChanges(IEnumerable`1 changes)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
   at RoslynTest.Program.<DoMainAsync>d__5.MoveNext() in C:\Data\Sources\OpenSource\CosmosRoslynRefactorings\RegistersToEnumRefactoring\Program.cs:line 84<---```

**Comment by mterwoord** [comment] 2016-06-14 19:07
You'll actually want CosmosOS/RoslynRefactorings@5f5d6b2 

It fixes a loop bug.

**Comment by 0xd4d** [comment] 2016-06-14 19:07
Seems related to https://github.com/dotnet/roslyn/issues/10452

**Comment by Pilchie** [comment] 2016-06-16 16:44
Yes this looks like a duplicate of #10452 - @mattwar any update on that one?

**Closed by Pilchie** 2016-06-16 16:44 UTC
