### ISSUE TITLE
"Remove unused parameter" is firing 10s of times for the same issue

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31743] opened 2018-12-13 06:51 UTC
``` C#
        private static bool ShouldRouteCommandBackToVS(Guid cmdGuid, uint cmdId, bool translated, bool startsMultiKeyChord)
        {
            //Any command that wasn't translated by TranslateAcceleratorEx or has no VS handler in global scope should be routed to WPF
            if (!translated || cmdGuid == Guid.Empty)
            {
                return false;
            }

            //Allow VS to take over for anything that would be a common shell command
            //  (CTRL+Tab, CTRL+Shift+TAB, Shift+ALT+Enter, etc.)
            if (cmdGuid == VSConstants.GUID_VSStandardCommandSet97)
            {
                //If there's a GUID_VSStandardCommandSet97 command that should be handled by WPF instead, check for them and return false

                //Otherwise indicate that the command should be handled by VS
                return true;
            }

            //If there are additional commands that VS should be handling instead of WPF, check for them and return true here

            //Otherwise indicate that the command should be handled by WPF
            return false;
        }
```

Expected:
```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active

```

Actual:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active
Message	IDE0060	Remove unused parameter 'cmdId'	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPageElementHost.cs	43	Style	Active

```

**Comment by mavasani** [comment] 2018-12-13 16:33
Dupe of https://github.com/dotnet/roslyn/issues/31381

**Closed** 2018-12-14 23:14 UTC
Labels: 4 - In Review, Area-IDE, Bug
