### ISSUE TITLE
Inconsistent behaviour of source code generators in VS 2022

### ISSUE THREAD

**Issue by brgrz** [dotnet/roslyn#69633] opened 2023-08-21 10:12 UTC
**Version Used**: 

		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.7.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />

**Steps to Reproduce**:

1. Create a source generator with an error (for example mine was throwing NullReferenceException)
2. There will be a warning in the Output window

```
warning CS8785: Generator 'ControllerGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'
```
3. No code generated
4. Fix the generator or replace it with a working one for example the simple one from https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#generated-class
5. Rebuild with Ctrl+Shift+B - nothing will get built by the source generator
6. Exit and restart Visual Studio
7. Occasionally immediately after restart you will see the new code present or sometimes it will still take another rebuild 

In general, whenever there is an error within the source generator, it is impossible to get it to work (even if replaced with errorless generator code) without restarting VS.

Also, most of the times, if the source generator was working and it was modified with code that fails, the old generated sources will remain present - possibly this is how it works? I'd expect it to remove previously generated sources on new build.

**Comment by sharwell** [comment] 2023-08-23 14:18
Duplicate of #48083

**Closed by sharwell** 2023-08-23 14:18 UTC
Labels: Area-Compilers, untriaged
