### ISSUE TITLE
[Proposal] foreach with index, isLast, implicit locally scoped item typing

### ISSUE THREAD

**Issue by scottt732** [dotnet/roslyn#5194] opened 2015-09-12 18:30 UTC
This would be nice...

    foreach ((item, idx) in someEnumerable) {
        ...
    }

or

    foreach ((item, idx, isLast) in someEnumerable) {
        ...
    }

isFirst, isOdd, isEven, etc could still be figured out using idx.  I think this would get rid of just about every situations where I need to use a regular for loop.  

*The alternatives*
The foreach loop with a counter syntax forces me to stick the counter variable in the outer scope.  

    var idx = 0; /* The scope on this is annoying */
    foreach (var item in someEnumerable) {
      // Do something with item
      var isFirst = (idx == 0);
      var isLast = /* Impossible to figure out without iterating or converting to array? */
      idx++;
    }

The for loop with an indexer lookup is boilerplate and maybe has a performance penalty?

    for (var idx = 0; idx < someArray.Length; idx++) {
        var item = someArray[idx]; /* This is annoying */
        var isFirst = (idx == 0);
        var isLast = (idx == someArray.Length - 1);
    }

I realize that figuring out IsLast on an IEnumerable might be tricky/impossible unless you could somehow ToArray() on the fly.  I can live without it (or maybe restrict it to arrays and ILists)... but the indexer would be a huge time saver.

**Comment by gafter** [comment] 2015-09-12 18:53
This is a duplicate of #1752

**Closed by gafter** 2015-09-12 18:53 UTC
Labels: Area-Language Design, Resolution-Duplicate

**Comment by scottt732** [comment] 2015-09-13 02:13
I'm sure that you guys are busy, but I think the first syntax has some merit and I would be curious to hear some feedback.  I admit that I have no language design experience, but I've been writing C# since .NET 1.0 and this would scratch an itch.  I wasn't crazy about the syntax in #1752 but I agree with the author on this particular idea.  Is it something you'd consider a pull request for or is it just fundamentally flawed/not going to happen?

More thoughts... When looping over an IEnumerable<T>, we know that the variable is of type T.  The only real downside I can think of is that you might have to assume that idx is a long when an int would generally cut it as you can't tell the size at compile time.  The (item, idx) syntax would imply that both variables are scoped to the body of the loop only.  If this existed, I can't imagine ever using a for loop again.  Thanks.
