### ISSUE TITLE
Error while executing msbuild /v:m /m Roslyn.sln

### ISSUE THREAD

**Issue by skosterin88** [dotnet/roslyn#17329] opened 2017-02-23 19:02 UTC
**Version Used**: 
I use Visual Studio 2015 Community Edition Update 3 on Windows 7 x64. 
**Steps to Reproduce**:
 
1. As it was said in the instruction file "Building, Debugging, and Testing on Windows.md", I ran Restore.cmd before building.
2. I ran msbuild /v:m /m Roslyn.sln from the command prompt opened from the Roslyn directory.

**Expected Behavior**:
As far as I understand, the solution should compile and all its projects should be fully available.
**Actual Behavior**:
In the command line, I get:
..\roslyn\Roslyn.sln.metaproj: error MSB4126: The specified solution configuration "Debug|MCD" is invalid.  Please specify a valid solution configuration using the Configuration and Platform properties(e.g. MSBuild.exe Solutions.sln/p:Configuration=Debug/p:Platform="AnyCPU") or leave those properties blank to use the default solution configuration.

After that, when I try to open Roslyn.sln in Visual Studio, I get multiple projects with "load failed" or "unavailable" status, including the "Roslyn" project itself. 

I understand that I make a very, very stupid mistake somewhere but I can't understand where exactly. I did all steps from "Building, Debugging, and Testing on Windows.md" word by word. What am I doing wrong?

**Comment by Pilchie** [comment] 2017-02-23 19:21
Are you on an HP machine?  It sounds like something is setting the `Platform` environment variable and msbuild is picking up on that.

Please check your environment and make sure that `Platform` is not set.

**Comment by skosterin88** [comment] 2017-02-23 20:15
OK, I deleted that environment variable. There is no such error. But I forgot to mention: when I run Restore.cmd from the command line, I get the following error: 

System.Management.Automation.RuntimeException: The variable '$_' cannot be retrieved because it has not been set.
at System.Management.Automation.VariableDereferenceNode.GetVariable(ExecutionContext context)
at System.Management.Automation.VariableDereferenceNode.PrivateGetValue(ExecutionContext context)
at System.Management.Automation.VariableDereferenceNode.GetValue(ExecutionContext context)
at System.Management.Automation.ArrayLiteralNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
at System.Management.Automation.MethodCallNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
Error loading NuGet.exe information 65535

And, as I guess, it leads to loading the solution with multiple errors.

Any ideas?

**Comment by Pilchie** [comment] 2017-02-23 20:16
@jaredpar ?

**Comment by jaredpar** [comment] 2017-02-23 20:31
Do you know which script is producing that error? 

It's possible we've taken a dependncy on a new feature of powershell that wasn't present in Windows 7 here.

**Comment by skosterin88** [comment] 2017-02-23 21:18
So this happens just because I am working under Windows 7, right? And I should upgrade to Win8 or higher? No other ways to solve the problem?

**Comment by jaredpar** [comment] 2017-02-23 21:22
> So this happens just because I am working under Windows 7, right? 

Possibly.  That's why I'm curious to know if the output says which script failed.  If I know which script it is I can take a deeper look and see if there is any newer syntax there which may be at fault.  

> No other ways to solve the problem?

Depends.  Powershell versions are per-OS.  Each version has little quirks and it's very easy to accidentally take a dependency on one of these quirks in our scripts.  If it's a simple quirk I'd be inclined to fix it.  Will know more once we know which script is acting up.

**Comment by jasonmalinowski** [comment] 2017-02-24 06:26
FYI this is a dupe of #15667 which has more info. I'll leave this open though so we keep the conversation going here to get more info.

**Comment by jasonmalinowski** [comment] 2017-03-01 21:20
@jaredpar Do we need any additional info from @skosterin88 here?

**Comment by jaredpar** [comment] 2017-03-01 21:30
Yes

> Do you know which script is producing that error?

**Comment by jgleaton** [comment] 2017-03-02 01:41
I'm on Windows 7 as well.

> Do you know which script is producing that error?

For me it is download-nuget.ps1.

**Comment by jaredpar** [comment] 2017-03-02 16:27
Hmm, the only use of `$_` in the script is in the catch block.  Hence it seems there is another error and then the script is throwing trying to print the error.  Can you try removing the try / catch and see if it prints the real error?

On higher note: that script is **very** basic.  If Windows 7 Powershell can't handle it, I'm not sure how it's going to handle the rest of our scripts which have more complex items than that.

**Comment by jasonmalinowski** [comment] 2017-03-02 18:06
Is it worth getting one of our CI queues using Windows 7? Given it's a supported platform of Visual Studio we probably should be doing that anyways...

**Comment by jaredpar** [comment] 2017-03-02 18:23
There is a difference between our supported and development platforms even though they have significant overlap.  It's not a requirement that we test all supported platforms in our development phase, just that we test them at some point.  Our product is tested on less common OS like Windows 7 are tested regularly, just not in CI. 

Thinking about this though I think there are a couple paths forward.  

1. Reach out to Powershell and find out if there is a way to properly constrain Powershell to Windows 7.0 features only (roughly Powershell v2.0).  Essentially a feature similar to the C# `/langversion` flag.  I do not believe such a feature exists though. 
1. Have one of our CI machines use Windows 7 as a test operating system.  This will be more palatable to once my change is merged to have our unit test legs run on a bare Windows operating system.  When bugs happen though it will be annoying to track down as none of our developers run Windows 7 ATM. 
1. Change the platforms we support for active development of the repo to be the minimum Windows version we run in Jenkins.

**Comment by jgleaton** [comment] 2017-03-02 22:50
I commented out the try/catch, but the error makes even less sense :/
![image](https://cloud.githubusercontent.com/assets/3639415/23530036/9daadeea-ff65-11e6-807c-bcd9ca3c328d.png)

The only ways I managed to get past this was either comment-out the set-strictmode:
`...`
`#set-strictmode -version 2.0`
`...`
\- or \-
comment out the param syntax:
`#param (`
`#    [string]$nugetVersion = $(throw "Need a nuget version"),`
`#    [string]$destDir = $(throw "Need a path to download too"),`
`#    [string]$binariesDir = $(throw "Need path to Binaries directory"))`
`set-strictmode -version 2.0`
`$ErrorActionPreference="Stop"`

`$nugetVersion = "3.6.0-beta1"`
`$destDir = "..\.."`
`$binariesDir = "..\..\Binaries"`
`...`

On subsequent executions, 'get-filehash' does not appear to exist.
`        #$destHash = (get-filehash $destFile -algorithm MD5).Hash`
`        #$scratchHash = (get-filehash $scratchFile -algorithm MD5).Hash`
`        $scratchVersion = gc $versionFile`
`        if ($scratchVersion -eq $nugetVersion) { # ($destHash -eq $scratchHash) -and (...)`
`            write-host "Using existing NuGet.exe at version $nuGetVersion"`
`            exit 0`
`        }`

With these changes in place, everything (mostly) works as expected:
___
PS X:\roslyn\build\scripts> powershell -noprofile -file ".\download-nuget.ps1" "3.6.0-beta1" "..\.." "..\..\Binaries"
Downloading NuGet.exe
___
PS X:\roslyn\build\scripts> powershell -noprofile -file ".\download-nuget.ps1" "3.6.0-beta1" "..\.." "..\..\Binaries"
Using existing NuGet.exe at version 3.6.0-beta1
___

**Comment by skosterin88** [comment] 2017-03-03 20:16
Well... I have made the changes pointed by @jgleaton and the solution has been built without errors.

**Comment by lachbaer** [comment] 2017-03-24 13:10
You should update to a newer version of Powershell. I ran into the same problem.

Now I had that MSB4126 problem on my HP notebook. Issued `set platform=` before the `msbuild ...` and it works.

**Comment by jasonmalinowski** [comment] 2017-09-29 20:16
We now document the steps to upgrade PowerShell on Windows 7, so we'll call this good.

**Closed by jasonmalinowski** 2017-09-29 20:16 UTC
Labels: Area-Infrastructure
