### ISSUE TITLE
IDE0007 triggers on cast in foreach

### ISSUE THREAD

**Issue by RobinHood70** [dotnet/roslyn#18559] opened 2017-04-08 22:30 UTC
**Version Used**: Visual Studio Community 2017, build 26403.0

**Steps to Reproduce**:

1. Create a foreach loop with an explicit cast such as `foreach (Match match in myMatchCollection)`
2. Enable IDE0007

**Expected Behavior**: IDE0007 should not trigger, since the explicit type does not match the type that would be generated from using a `var`.

**Actual Behavior**: IDE0007 triggers, and will incorrectly replace the explicit cast if the suggestion lightbulb is used, causing errors.

**Comment by Pilchie** [comment] 2017-04-10 16:59
Dupe of https://github.com/dotnet/roslyn/issues/14052.

**Closed by Pilchie** 2017-04-10 16:59 UTC
Labels: Area-IDE, Bug, Resolution-Duplicate
