### ISSUE TITLE
Would allowing extension methods to be defined in nested classes make sense?

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#9139] opened 2016-02-24 17:17 UTC
```
public class Foo
{
    ...
    private static class Bar
    {
        internal static string Baz(this string s)
        {
            ...
        }
    }
}
```

My thinking is that allowing ^ would be a way to scope extension methods to only be visible in `Foo`.
Could be nice for extensions on types like string when a limited scope is desired.
I don't remember the reason why extension methods are not allowed in nested classes.
I have not though much about and it may be a bad idea, wrote this to get some feedback.
Would this add much complexity to parsing etc?

**Comment by jnm2** [comment] 2017-01-06 17:25
Yes! This restriction is frustrating once in a while in general and frustrating frequently in C# scripts like Cake, where there is no way to declare an extension method.

**Comment by filipw** [comment] 2017-02-24 20:36
@jnm2 

C# scripts have supported extension methods for a while. This is a valid script for example:

```
static void Hi(this object o) {
    Console.WriteLine("hi " + o);
}

"foo".Hi();
```

**Comment by filipw** [comment] 2017-02-24 20:36
here is the PR https://github.com/dotnet/roslyn/pull/3472

**Comment by jnm2** [comment] 2017-02-24 20:46
Hmm... thanks for the heads up. The most recent version of Roslyn that Cake uses is `1.0.0-rc2`, so that's why I'm still getting CS1106.

**Comment by filipw** [comment] 2017-02-24 20:55
that's the last version that supported .NET 4.5. it's also almost 2 years old, with 2.0.0 going RTM soon and 2.0.0-rc4 being the latest

**Comment by svick** [comment] 2017-08-09 20:22
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/4565 (which was moved to https://github.com/dotnet/csharplang/issues/301).

**Comment by OJacot-Descombes** [comment] 2018-05-02 15:36
Why declare it in a nested static class instead of directly in the class?

```
public class Foo
{
    ...
    protected static string Baz(this string s) // Always protected or private
    {
        ...
    }
}
```

**Comment by jnm2** [comment] 2018-09-27 01:17
Would you close the issue, please, since all language design issues have migrated to https://github.com/dotnet/csharplang?

**Closed** 2018-09-27 05:09 UTC
Labels: Area-Language Design, Question
