### ISSUE TITLE
Invalid LambdaExpression's member for derived types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#30636] opened 2018-10-21 07:36 UTC
<p>The lambda-expression compiler generates an invalid expression for derived types with an overriden property.</p><p>Example:</p><pre>class Base
{
	public virtual string Property { get; set; }
}

class Derived : Base
{
	public override string Property { get; set; }	
}
</pre><p>In this case the following call will return `Base` instead of `Derived`:</p><pre>void Main()
{
	var derived = new Derived();
	var expression = (Expression&lt;Func&lt;string&gt;&gt;)(() =&gt; ((Derived)derived).Property);
	var name = DemoVisitor.GetMemberInfo(expression).DeclaringType.Name;
}
</pre><p>The corresponding ExpressionVisitor is:</p><pre>internal class DemoVisitor : ExpressionVisitor
{
	private MemberInfo _member;
	
	public static MemberInfo GetMemberInfo(LambdaExpression expression)
	{
		var visitor = new DemoVisitor();
		visitor.Visit(expression);
		
		return visitor._member;
	}

	protected override Expression VisitMember(MemberExpression node)
	{
		// invalid member here
		node.Member.DeclaringType.Name.Dump();
		_member = _member ?? node.Member;

		return base.VisitMember(node);
	}
}
</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/357178/invalid-lambdaexpressions-member-for-derived-types.html
VSTS ticketId: 705626_
_These are the original issue comments:_

he-dev on 10/14/2018, 07:11 AM (6 days ago): <p>I'm giving up... it's not possible to format the code correctly. Sorry.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by svick** [comment] 2018-10-21 11:32
What makes you think the expression is invalid? If I compile it and invoke the delegate, it works fine.

I believe it's common in .Net to refer to virtual methods by using the original definition in the base type. For example, it's also what is used if I convert your lambda directly to a delegate instead of an expression:

```il
callvirt    Base.get_Property
```

**Comment by he-dev** [comment] 2018-10-21 12:06
@svick the expression is invalid because it returns the base member and not the derived one. I'm reading attributes from that property and it is giving me the wrong ones. If the instance is `Derived` and a member is overriden then I expect to get that overriden member (hier a  property) of this derived class and not that of the `Base`.

**Comment by he-dev** [comment] 2018-10-21 12:35
@ufcpp 

it means that for this

```c#
var derived = new Derived();
        var expression = (System.Linq.Expressions.Expression<System.Func<string>>)(() => derived.Property)
```

the issue is somewhere here:

```
        // sequence point: hidden
        IL_0000: newobj instance void Program/'<>c__DisplayClass0_0'::.ctor()
        IL_0005: dup
        IL_0006: newobj instance void Derived::.ctor()
        IL_000b: stfld class Derived Program/'<>c__DisplayClass0_0'::derived
        IL_0010: ldtoken Program/'<>c__DisplayClass0_0'
        IL_0015: call class [mscorlib]System.Type [mscorlib]System.Type::GetTypeFromHandle(valuetype [mscorlib]System.RuntimeTypeHandle)
        IL_001a: call class [System.Core]System.Linq.Expressions.ConstantExpression [System.Core]System.Linq.Expressions.Expression::Constant(object, class [mscorlib]System.Type)
        IL_001f: ldtoken field class Derived Program/'<>c__DisplayClass0_0'::derived
        IL_0024: call class [mscorlib]System.Reflection.FieldInfo [mscorlib]System.Reflection.FieldInfo::GetFieldFromHandle(valuetype [mscorlib]System.RuntimeFieldHandle)
        IL_0029: call class [System.Core]System.Linq.Expressions.MemberExpression [System.Core]System.Linq.Expressions.Expression::Field(class [System.Core]System.Linq.Expressions.Expression, class [mscorlib]System.Reflection.FieldInfo)
        IL_002e: ldtoken method instance string Base::get_Property()
        IL_0033: call class [mscorlib]System.Reflection.MethodBase [mscorlib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [mscorlib]System.RuntimeMethodHandle)
        IL_0038: castclass [mscorlib]System.Reflection.MethodInfo
        IL_003d: call class [System.Core]System.Linq.Expressions.MemberExpression [System.Core]System.Linq.Expressions.Expression::Property(class [System.Core]System.Linq.Expressions.Expression, class [mscorlib]System.Reflection.MethodInfo)
        IL_0042: call !!0[] [mscorlib]System.Array::Empty<class [System.Core]System.Linq.Expressions.ParameterExpression>()
        IL_0047: call class [System.Core]System.Linq.Expressions.Expression`1<!!0> [System.Core]System.Linq.Expressions.Expression::Lambda<class [mscorlib]System.Func`1<string>>(class [System.Core]System.Linq.Expressions.Expression, class [System.Core]System.Linq.Expressions.ParameterExpression[])
        IL_004c: pop
        IL_004d: ret
```

**Comment by svick** [comment] 2018-10-21 13:37
@he-dev I understand it's not the behavior you want, but I don't see how that makes it "invalid" or "incorrect". When invoking a virtual member, it doesn't matter if you use the base member or the derived member, both work the same.

I *think* the compiler chooses the base member, because it's more robust: if the derived class is in a separate library and you update to a new version of that library, which removes the derived member, but don't recompile your code, it will still work, because the base member still exists.

Reflection has to return the derived member, it would be nigh useless otherwise. But I don't see a good reason why the compiler would have to choose the derived member here, while there is a good reason why the base member should be used instead.

**Comment by he-dev** [comment] 2018-10-21 14:07
@svick _I understand it's not the behavior you want, but I don't see how that makes it "invalid" or "incorrect". _ - I don't thinkg this is a very good argument as every invalid behaviour is disovered by someone who tried to do something and well... something unexpected happened. If all bugs were treated this way then nothing ever had to be corrected.

_I think the compiler chooses the base member, because it's more robust:_ - I appreciate your efforts trying to explain this issue though these are only speculations.

I suggest we wait for someone to replay who actually designed the expression tree compiler and for sure can tell wheter this is (un)expected.

_But I don't see a good reason why the compiler would have to choose the derived member here, while there is a good reason why the base member should be used instead._  - there is no reason in picking the base member if I'm using a derived type and it should pick the derived member because it's the one that is used here otherwise it makes the entire concept of inheritance useles when the reflection and expression trees randomly pick members as they like. It's totaly unreliable. With this reasoning you could just pick the base class too because in this case there is actually absolutely no reason in using the derived one. If it worked this way it would be just a huge mess. Well... it's one anyway because of the compiler being confused about the correct member.

**Comment by CyrusNajmabadi** [comment] 2018-10-21 17:29
> Well... it's one anyway because of the compiler being confused about the correct member.

There is no confusion. The compiler is picking the expected member exactly as specified in the language specification

**Comment by CyrusNajmabadi** [comment] 2018-10-21 17:39
The critical part is:

> For example, the set of candidates for a method invocation does not include methods marked override (Member lookup)

This also applies to things like properties:

>Otherwise, the set consists of all accessible (Member access) members named N in T, including inherited members and the accessible members named N in object. If T is a constructed type, the set of members is obtained by substituting type arguments as described in Members of constructed types. Members that include an override modifier are excluded from the set.

When picking members, these overridden members are effectively ignored.   This makes sense as the actual override cannot even be known until runtime, even if the type was explicitly casted to some type. That's because the real runtime your might **still** be yet another subclass of that type, with its own override that will be called.

**Comment by CyrusNajmabadi** [comment] 2018-10-21 17:51
> Here's a workaround that I'm currently using. I have to get the correct property with:

This workaround is not valid either. It fails to take into account that the real type might be some even deeper subclass of _type at runtime.  

If you want to represent virtual members, you have to do the lookup on the final type that exists when being invoked

**Comment by jaredpar** [comment] 2018-10-29 15:34
Closing as the behavior is by design (as noted in the discussion in this thread).

**Closed by jaredpar** 2018-10-29 15:34 UTC
Labels: Area-Compilers
