### ISSUE TITLE
Diagnostics: OperationCanceledException in ExecuteSuppressionAction

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#41713] opened 2020-02-14 23:54 UTC
VSMac logs contain exceptions from Roslyn with this stack:

```
ERROR [2020-02-07 15:05:15Z]: Roslyn fatal exception
System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> System.OperationCanceledException: The operation was canceled.
  at System.Threading.CancellationToken.ThrowOperationCanceledException () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:338 
  at System.Threading.CancellationToken.ThrowIfCancellationRequested () [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:333 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSuppressionAction (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor, System.Collections.Immutable.ImmutableArray`1[T] reportedDiagnostics) [0x0000a] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:297 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass73_0.<ApplyProgrammaticSuppressionsCore>b__3 (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor) [0x00000] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:697 
  at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 (System.Collections.IEnumerator& partitionState, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) [0x00103] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3220 
--- End of stack trace from previous location where exception was thrown ---
```

The fact that this is an OperationCanceledException tells me there should be a catch(OperationCanceledException) somewhere but I can't find it. How is this supposed to work? Is this benign?

**Comment by KirillOsenkov** [comment] 2020-02-14 23:55
More stack:

```
  at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException (System.Collections.ICollection exceptions, System.Threading.CancellationToken cancelToken, System.Exception otherException) [0x00007] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3418 
  at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal] (System.Collections.Concurrent.Partitioner`1[TSource] source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] simpleBody, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) [0x001c9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3334 
  at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal] (System.Collections.Generic.IEnumerable`1[T] source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) [0x0004a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:2139 
  at System.Threading.Tasks.Parallel.ForEach[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Action`1[T] body) [0x0001c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:1558 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ApplyProgrammaticSuppressionsCore>g__executeSuppressionActions|73_0 (System.Collections.Generic.IEnumerable`1[T] reportedDiagnostics, System.Boolean concurrent) [0x00026] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:695 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ApplyProgrammaticSuppressionsCore (System.Collections.Immutable.ImmutableArray`1[T] reportedDiagnostics, Microsoft.CodeAnalysis.Compilation compilation) [0x00022] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:658 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ApplyProgrammaticSuppressions (System.Collections.Immutable.ImmutableArray`1[T] reportedDiagnostics, Microsoft.CodeAnalysis.Compilation compilation) [0x00013] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:632 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.FilterDiagnosticsSuppressedInSourceOrByAnalyzers (System.Collections.Immutable.ImmutableArray`1[T] diagnostics, Microsoft.CodeAnalysis.Compilation compilation) [0x00014] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:770 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.DequeueLocalDiagnosticsAndApplySuppressions (Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Boolean syntax, Microsoft.CodeAnalysis.Compilation compilation) [0x0001e] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:758 
  at Microsoft.CodeAnalysis.Diagnostics.AnalysisResultBuilder.ApplySuppressionsAndStoreAnalysisResult (Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Compilation compilation, System.Func`2[T,TResult] getAnalyzerActionCounts, System.Boolean fullAnalysisResultForAnalyzersInScope) [0x00026] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisResultBuilder.cs:84 
  at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync (Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1[TElement] eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken) [0x000c3] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:902 
  at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers+<>c__DisplayClass57_1.<ComputeAnalyzerDiagnosticsAsync>b__1 () [0x000bb] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:727 
  at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync (Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Func`1[TResult] getPendingEventsOpt, System.Int32 newTaskToken, System.Threading.CancellationToken cancellationToken) [0x002e1] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:747 
  at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalyzerSemanticDiagnosticsCoreAsync (Microsoft.CodeAnalysis.SemanticModel model, System.Nullable`1[T] filterSpan, System.Collections.Immutable.ImmutableArray`1[T] analyzers, System.Threading.CancellationToken cancellationToken, System.Boolean forceCompletePartialTrees) [0x00170] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:590 
  at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalyzerSemanticDiagnosticsAsync (Microsoft.CodeAnalysis.SemanticModel model, System.Nullable`1[T] filterSpan, System.Collections.Immutable.ImmutableArray`1[T] analyzers, System.Threading.CancellationToken cancellationToken) [0x00058] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:566 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper+<>c__DisplayClass38_0.<ComputeDiagnosticsAsync>g__ComputeDiagnosticAnalyzerDiagnosticsAsync|0 () [0x002d3] in /_/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs:448 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.ComputeDiagnosticsAsync (Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService service, Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.Diagnostics.AnalysisKind kind, System.Nullable`1[T] spanOpt, Microsoft.CodeAnalysis.Diagnostics.Log.DiagnosticLogAggregator logAggregatorOpt, System.Threading.CancellationToken cancellationToken) [0x00196] in /_/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs:416 
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+Executor.GetDocumentAnalysisDataAsync (Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers analyzerDriverOpt, Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+StateSet stateSet, Microsoft.CodeAnalysis.Diagnostics.AnalysisKind kind, System.Threading.CancellationToken cancellationToken) [0x001cf] in /_/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs:67 
---> (Inner Exception #0) System.OperationCanceledException: The operation was canceled.
  at System.Threading.CancellationToken.ThrowOperationCanceledException () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:338 
  at System.Threading.CancellationToken.ThrowIfCancellationRequested () [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:333 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSuppressionAction (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor, System.Collections.Immutable.ImmutableArray`1[T] reportedDiagnostics) [0x0000a] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:297 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass73_0.<ApplyProgrammaticSuppressionsCore>b__3 (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor) [0x00000] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:697 
  at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 (System.Collections.IEnumerator& partitionState, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) [0x00103] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3220 
--- End of stack trace from previous location where exception was thrown ---

  at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 (System.Collections.IEnumerator& partitionState, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) [0x0025f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3294 
  at System.Threading.Tasks.TaskReplicator+Replica`1[TState].ExecuteAction (System.Boolean& yieldedBeforeCompletion) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/TaskReplicator.cs:123 
  at System.Threading.Tasks.TaskReplicator+Replica.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/TaskReplicator.cs:78 <---
```

**Comment by KirillOsenkov** [comment] 2020-02-14 23:59
Basically I'm curious where's the catch for this line:
https://github.com/dotnet/roslyn/blob/6a099895d6bbe76ffdb80a9557ae464d2aba147b/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs#L317

**Comment by KirillOsenkov** [comment] 2020-02-15 00:00
Also, does this method unwrap an AggregateException containing an OperationCanceledException? 
http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/InternalUtilities/FatalError.cs,b3dc86e597a5e321

**Comment by sharwell** [comment] 2020-02-19 20:11
@AmadeusW is this a duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1070469?

**Comment by KirillOsenkov** [comment] 2020-02-19 22:04
The stack seems different. In my stack there's a Parallel.ForEach and we're in the middle of calculation.

**Comment by sharwell** [comment] 2020-02-19 22:27
> Also, does this method unwrap an AggregateException containing an OperationCanceledException?

This is the source of the problem. The handler for the cancellation exception is here, but it only works if we unwrap it:
https://github.com/dotnet/roslyn/blob/22b7f4612cdfcfd9c487a742b7f2a693e65a31d1/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L910

Assigning to @mavasani

**Comment by sharwell** [comment] 2020-02-19 22:44
@KirillOsenkov The workaround is either disabling concurrency or disabling suppressors for IDE analysis. For Visual Studio, we disable concurrency for default scenarios, and we disable suppressors when Full Solution Analysis is enabled (not intentional, but works around the crash either way).

**Closed** 2020-02-26 17:43 UTC
Labels: 4 - In Review, Area-Analyzers, Bug, Tenet-Reliability
