### ISSUE TITLE
Flaky test AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#27648] opened 2018-06-08 20:58 UTC
I got the following spurious error during a desktop test run:

``` none
------ Test started: Assembly: Roslyn.Compilers.CSharp.Emit.UnitTests.dll ------
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase' failed: System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : 

	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
	at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
	Symbols\Source\SourceNamespaceSymbol_Completion.cs(53,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Source\SourceModuleSymbol.cs(258,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Source\SourceAssemblySymbol.cs(908,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2257,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2144,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2080,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2074,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)
	Diagnostics\DiagnosticExtensions.cs(98,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
	Attributes\AttributeTests_WellKnownAttributes.cs(6944,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_WellKnownAttributes.ObsoleteOnVirtual_OnBase()
	----- Inner Stack Trace -----
	ThrowingTraceListener.cs(24,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition)
	Symbols\Source\SourceEventSymbol.cs(184,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributesBag()
	Symbols\Source\SourceEventSymbol.cs(200,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol.GetAttributes()
	Symbols\Symbol_Attributes.cs(725,0): at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteObsoleteAttribute()
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(693,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckOverrideMember(Symbol overridingMember, OverriddenOrHiddenMembersResult overriddenOrHiddenMembers, DiagnosticBag diagnostics, Boolean& suppressAccessors)
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(463,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckMembersAgainstBaseType(DiagnosticBag diagnostics, CancellationToken cancellationToken)
	Symbols\Source\SourceMemberContainerSymbol_ImplementationChecks.cs(31,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetSynthesizedExplicitImplementations(CancellationToken cancellationToken)
	Symbols\Source\SourceMemberContainerSymbol.cs(499,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
	Symbols\Symbol.cs(712,0): at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
	Symbols\Source\SourceNamespaceSymbol_Completion.cs(56,0): at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass47_1.<ForceComplete>b__0(Int32 i)
	InternalUtilities\UICultureUtilities.cs(157,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param)
	at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
	at System.Threading.Tasks.Task.InnerInvoke()
	at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
	at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

**Comment by jaredpar** [comment] 2018-09-12 16:47
Dupe of #28954

**Closed by jaredpar** 2018-09-12 16:47 UTC
Labels: Area-Compilers, Flaky, Test
