### ISSUE TITLE
IOperation: VB - BoundCall.ArgumentMatchingParameter doesn't check anything except parameter's ordinal

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8772] opened 2016-02-16 23:23 UTC
This method is used to implement IHasArgumentsExpression.GetArgumentMatchingParameter. Note it doesn't even check that the parameter belongs to the method, simply grabs its ordinal. If having IParameterSymbol is significant, then we should make sure it belongs to the method being called. Otherwise, perhaps the IHasArgumentsExpression.GetArgumentMatchingParameter API simply should take the ordinal.  

```
        Friend Shared Function ArgumentMatchingParameter(arguments As ImmutableArray(Of BoundExpression), parameter As IParameterSymbol, parameters As ImmutableArray(Of Symbols.ParameterSymbol)) As IArgument
            Dim index As Integer = parameter.Ordinal
            If index <= arguments.Length Then
                Return DeriveArgument(index, arguments(index), parameters)
            End If

            Return Nothing
        End Function
```

**Comment by genlu** [comment] 2017-07-12 22:44
Related to #18658

**Comment by tmat** [comment] 2017-09-06 23:58
@genlu Anything needs to be done here?

**Comment by jinujoseph** [comment] 2017-09-29 21:07
dupe of #18658

**Closed by jinujoseph** 2017-09-29 21:07 UTC
Labels: 0 - Backlog, Area-Analyzers, Area-Interactive, Bug, Language-VB, New Feature - IOperation
