### ISSUE TITLE
Type comparison across compilation boundaries always fails.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5514] opened 2015-09-29 00:00 UTC
**REPRO:**

1. Create a new C# console app and add references to:
  - `Microsoft.CodeAnalysis`
  - `Microsoft.CodeAnalysis.CSharp`
  - `Mcirosoft.CodeAnalysis.CSharp.Workspaces`
  - `Mcirosoft.CodeAnalysis.VisualBasic`
  - `Mcirosoft.CodeAnalysis.VisualBasic.Workspaces`
  - `Mcirosoft.CodeAnalysis.Workspaces`
  - `Mcirosoft.CodeAnalysis.Workspaces.Desktop`
2. Set the body of `Program.cs` to:
    ``` C#
    static void Main(string[] args)
    {
        DoWork().Wait();
    }

    private static async Task DoWork()
    {
        var solution = await MSBuildWorkspace.Create().OpenSolutionAsync(@"C:\path\to\Roslyn.sln");

        var vsLangServices = solution.Projects.Single(p => p.Name == "ServicesVisualStudio");
        var vscompilation = await vsLangServices.GetCompilationAsync();
        var previewDialogWorkspace = vscompilation.GetTypeByMetadataName("Microsoft.VisualStudio.LanguageServices.Implementation.Preview.PreviewUpdater+PreviewDialogWorkspace");

        var editorFeatures = solution.Projects.Single(p => p.Name == "EditorFeatures");
        var efcompilation = await editorFeatures.GetCompilationAsync();
        var previewWorkspace = efcompilation.GetTypeByMetadataName("Microsoft.CodeAnalysis.Editor.Shared.Preview.PreviewWorkspace");

        var previewDialogWorkspaceOriginalBase = await SymbolFinder.FindSourceDefinitionAsync(previewDialogWorkspace.BaseType, solution);
        var previewWorkspaceOriginal = await SymbolFinder.FindSourceDefinitionAsync(previewWorkspace, solution);

        Console.WriteLine($"previewDialogWorkspace.BaseType == previewWorkspace: {previewDialogWorkspace.BaseType == previewWorkspace}");
        Console.WriteLine($"previewDialogWorkspaceOriginalBase == previewWorkspace: {previewDialogWorkspaceOriginalBase == previewWorkspace}");
        Console.WriteLine($"previewDialogWorkspace.BaseType == previewWorkspaceOriginal: {previewDialogWorkspace.BaseType == previewWorkspaceOriginal}");
        Console.WriteLine($"previewDialogWorkspaceOriginalBase == previewWorkspaceOriginal: {previewDialogWorkspaceOriginalBase == previewWorkspaceOriginal}");
    }
    ```
3. Run.

**RESULT:**
All checks report `False`, but browsing [the source](http://source.roslyn.io) clearly shows the inheritance.

This appears to be the root cause to #4973 and #5496.

**Comment by Pilchie** [comment] 2015-09-29 01:36
Isn't this by design?  Don't we need to call our "GetSourceDefinition" before doing the comparison?

**Comment by MrJul** [comment] 2015-09-29 08:10
Also see #63

**Comment by brettfo** [comment] 2015-09-29 19:01
I've also checked with [`FindSourceDefinitionAsync()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/SymbolFinder.cs,ad50ce0fb65de489) and all checks still fail.  Original repro updated (see the last 6 lines.)

**Comment by agocke** [comment] 2015-11-04 05:59
This is by design. Closing.

**Closed by agocke** 2015-11-04 05:59 UTC
Labels: Area-Compilers, Bug
