### ISSUE TITLE
AD0001 (unreachable) for the CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#34829] opened 2019-04-08 11:06 UTC
**Version Used**:
16.0.0

**Steps to Reproduce**:
```csharp
public class C
{
    private const string m = "";
}
```

Opening my solution with this file already open immediately results in
```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'.	*		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: *
ISymbol: m (Field)

System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.ShouldReportUnusedParameters(ISymbol symbol, UnusedParametersPreference unusedParametersPreference, ReportDiagnostic unusedParametersSeverity)
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.AnalyzeOperationBlockEnd(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`2.<ExecuteBlockActions>b__55_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Expected Behavior**:
No AD0001, but an actual diagnostic

**Actual Behavior**:
AD0001 with stack trace

**Comment by mavasani** [comment] 2019-06-25 13:26
Duplicate of https://github.com/dotnet/roslyn/issues/34830

**Closed by mavasani** 2019-06-25 13:26 UTC
Labels: Area-IDE, Bug, IDE-CodeStyle, help wanted
