### ISSUE TITLE
[MaybeNullWhen(false)] results in disagreement between IntelliSense and compiler

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38547] opened 2019-09-06 13:06 UTC
**Version Used**: 
3.4.0-beta1-19426-03+b18d90790da95b6862def56802fa4249e4868bb4

**Steps to Reproduce**:
```C#
#nullable enable
using System.Diagnostics.CodeAnalysis;

class Program
{
    static void Main()
    {
        var d = new MyDictionary<string, string>();
        d.TryGetValue("hello", out string? s1);
        d.TryGetValue("hello", out string s2);
    }
}

class MyDictionary<TKey, TValue>
{
    public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TKey value)
    {
        value = default!;
        return false;
    }
}
```

**Expected Behavior**:
The compiler's needs and IntelliSense match.

**Actual Behavior**:
The compiler requires a `?` on the `out` argument, but IntelliSense doesn't include one:
![image](https://user-images.githubusercontent.com/2642209/64430139-99bc6800-d085-11e9-9e6a-c77ecf63be5e.png)

**Comment by RikkiGibson** [comment] 2019-09-06 18:11
Related to #38329 and #38358

**Comment by sharwell** [comment] 2019-09-06 18:23
I'm hoping for Quick Info to apply `MaybeNull` in signatures when substituting type parameters. For example, when applying `TKey`&rarr;`string`, you would also go from `[MaybeNull] TKey`&rarr;`string?`.

**Comment by RikkiGibson** [comment] 2019-09-06 18:26
Did you mean `TValue`&rarr;`string`?

**Comment by RikkiGibson** [comment] 2019-09-09 21:48
@sharwell is there an issue tracking that work?

**Comment by sharwell** [comment] 2019-09-10 06:39
@RikkiGibson Not so far, no

**Comment by jasonmalinowski** [comment] 2020-01-14 03:02
Hmm, thinking about this now, this is the same sort of transformation that we're doing in https://github.com/dotnet/roslyn/pull/38203 just not in a code generator scenario. In hindsight, it'd be Really Cool (and possibly Really Problematic) if a constructed named type or constructed method just automatically dropped the attributes and changed annotations when we had a unconstrained generic that was substituted with something that resulted in things like this. Then this would have worked, that feature would have worked, etc.

**Comment by RikkiGibson** [comment] 2021-01-27 14:30
Closing as a duplicate of #38358

**Closed by RikkiGibson** 2021-01-27 14:30 UTC
Labels: Area-IDE, Bug, New Language Feature - Nullable Reference Types
