### ISSUE TITLE
IDE0055 incorrectly indents with intermixed comment styles

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38224] opened 2019-08-22 21:18 UTC
**Version Used**: 
3.3.0-beta3-19415-01+f5ba9f2c61a2fe853dc4913888d40df221539147

**Steps to Reproduce**:
```C#
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main() { }

    [DllImport("kernel32.dll")]
    internal static extern bool CreateDirectory(
        /*LPCSTR*/ string path, // this is a nice comment
        /*LPSECURITY_ATTRIBUTES*/ IntPtr lpSecurityAttributes);
}
```

**Expected Behavior**:
IDE0055 not offerred.

**Actual Behavior**:
IDE0055 offered and formats the code to this:
```C#
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main() { }

    [DllImport("kernel32.dll")]
    internal static extern bool CreateDirectory(
        /*LPCSTR*/ string path, // this is a nice comment
                                /*LPSECURITY_ATTRIBUTES*/ IntPtr lpSecurityAttributes);
}
```

**Comment by CyrusNajmabadi** [comment] 2019-08-22 21:58
This is less about the diagnostic, and just the fact that the formatting engine wants to format things this way.  You'd get this with anything formatting related (i.e. format-doc, or typing the close brace of the class, or pasting).

Tagging @heejaechang for visibility.

**Comment by sharwell** [comment] 2019-08-23 16:49
Duplicate of #29482

**Comment by sharwell** [comment] 2019-08-23 16:50
One option for the case seen above would be this:

```csharp
using LPCSTR = System.String;
using LPSECURITY_ATTRIBUTES = System.IntPtr;
```

**Comment by sharwell** [comment] 2019-08-23 21:51
Keeping this open for the following distinction: the continuation comment does not appear on a line by itself; code follows the comment on the same line.

**Comment by sharwell** [comment] 2019-09-27 04:36
Design review conclusion: Only line comments will be eligible for end-of-line continuation comment alignment. The use of a block comment should have excluded the sample above from getting moved.

**Closed** 2019-09-27 17:40 UTC
Labels: 4 - In Review, Area-IDE, Concept-Continuous Improvement, IDE-Formatter
