### ISSUE TITLE
CS8363: A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern 'var _'.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#25450] opened 2018-03-13 19:51 UTC
Since version 15.6.0 I get hundreds of errors in our projects because &quot;is default&quot; is generating an error: &quot;CS8363	A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern 'var _'.&quot;

It looks like a wonderful feature from a previous version is removed. Which was not in the release notes at all!

To solve the build-error, we have to go back to the old notation &quot;is default(T)&quot; where T is the specific class. Which is annoying step backwards... Since the compiler knows the type of the object.

The most annoying part it that visual studio still will recommend that &quot;is default(T)&quot; can be simplified to &quot;is default&quot;, which will result in the above error...

Hopefully the removal of this features will be reconsidered in a coming version. So far, my other colleagues will not upgrade to version 15.6.x.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/211562/cs8363-a-default-literal-default-is-not-valid-as-a.html
VSTS ticketId: 579646_
_These are the original issue comments:_

Michael Johnson on 3/9/2018, 05:15 AM (4 days ago): I have the exact same issue - only started today after installing VS updated 15.6.1
Dmitriy Bobrovskiy on 3/11/2018, 08:43 PM (40 hours ago): <p>I have same trouble after updating today on 15.6.1</p>

NJ on 3/13/2018, 05:53 AM (6 hours ago): <p>Would it be possible that the solutions to this issue could be the cause of our problems: <a target='_blank' href="https://github.com/dotnet/roslyn/issues/23499" target="_blank">https://github.com/dotnet/roslyn/issues/23499</a>?</p><p>It seems that the solution mentioned in the issue above has a completely different purpose. Trying to fix a mix up with the default case in a switch statement. I am wondering if the fix to this, might be the cause of the problems I am having.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by agocke** [comment] 2018-03-13 21:57
cc @gafter

**Comment by gafter** [comment] 2018-03-13 22:17
> To solve the build-error, we have to go back to the old notation "is default(T)" where T is the specific class. Which is annoying step backwards... Since the compiler knows the type of the object.

You don't need to write `is default(T)` where T is the specific class. Just write `is null`.

**Comment by gafter** [comment] 2018-03-13 22:23
There are a few reasons for this change. First, we have seen people getting confused and writing

`case default:`

thinking that they were writing the default case of their switch. This problem will be worse in C# 8, when we are introducing a new switch *expression*, which will look something like this:

`expression switch { Pattern => value, Pattern => value }`

If you use `default` as one of the patterns, it will look just like it is a default for the switch. But it isn't. To address that category of issue we are forbidding `default` *as a pattern*.

Since the only values you could be intending by `default` in a pattern are `null` and `0`, and writing that is more clear and shorter, we recommend doing that instead.

**Comment by jaredpar** [comment] 2018-03-13 22:29
Closing as this was indeed by design. The original issue is here.

https://github.com/dotnet/roslyn/issues/23499

Do apologize for the inconvenience here. Breaking on issues like this is not something we take lightly but in this case we felt it needed to be done.

**Closed by jaredpar** 2018-03-13 22:29 UTC

**Comment by Enjeej** [comment] 2018-03-14 07:12
Hello,

Since I was the writer of the original issue I have the feeling I need to clarify the problem. My problem is not in a switch-statement, but in an if-statement. 

@gafter: Writing `is null` is not always possible, especially when using non-nullable types.

The error I get:
![gh_vs15_6_0_error](https://user-images.githubusercontent.com/37361278/37387569-38d97c4e-275d-11e8-9039-780828931228.png)

As a result of fixing this into: `if(configuration is default(QlikViewProductTypeConfiguration))`
There will be a suggestion to simplify this according to the feature introduced in C#7.1 "[Default literals](https://blogs.msdn.microsoft.com/mazhou/2017/06/06/c-7-series-part-3-default-literals/)":  
![gh_vs15_6_0_simplify](https://user-images.githubusercontent.com/37361278/37387568-38beeb90-275d-11e8-9734-2e833f007aaf.png)

I hope that is was not your intention to destroy the complet functionality of this new feature and give days of work to undo all the errors I am having at the moment. If this was your intention: I think the simplify-suggestion is a bug a the moment.

However, I hope that you did not intent to destroy this wonderful new feature and maybe just try to fix the confusion some people have in switch-statements... Although I have to agree with @ericwj in #23499, it is not that difficult to understand the difference between `default:` and `case (default):`.

Anyway I think this item should not be closed yet, because either way there is a BUG!

With king regards,

NJ

**Comment by gafter** [comment] 2018-03-14 07:43
I've opened a bug for the IDE behavior at https://github.com/dotnet/roslyn/issues/25456
