### ISSUE TITLE
Error Handling............

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52491] opened 2021-04-08 17:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-Handling/1372726)._

---
If there is an error regarding an semi colon is missing or expected {,} 
then please automatically add the semi colon or {,}

contact me for future information on this topic

---
### Original Comments
(no comments)

**Comment by sharwell** [comment] 2021-04-09 06:27
Duplicate of #30238

**Closed by sharwell** 2021-04-09 06:27 UTC
Labels: untriaged
