### ISSUE TITLE
Attempting to open some existing .editorconfig files crashes the new UI editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52716] opened 2021-04-18 20:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Attempting-to-open-some-existing-editor/1399549)._

---
[severity:It bothers me. A fix would be nice]
Attempting to open some existing .editorconfig files crashes the new UI editor.

Here's the contents of the file I showed exhibiting the problem in the attached screen recording:
```ini
# To learn more about .editorconfig see https://aka.ms/editorconfigdocs
############################### 
# Core EditorConfig Options   # 
############################### 
# All files 
[*] 
indent_style = space 
# Code files 

# no-extra-parens: Web Code Analysis
dotnet_diagnostic.no-extra-parens.severity = none

[*. {cs,csx,vb,vbx}]
charset = utf-8-bom 
indent_size = 4
insert_final_newline = false
trim_trailing_whitespace = true

[*. {cs,vb}]
# Organize usings
dotnet_sort_system_directives_first = true
dotnet_separate_import_directive_groups = false

[*. {cs}]
# CSharp specific things
csharp_using_directive_placement = inside_namespace:silent
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:suggestion
dotnet_style_require_accessibility_modifiers = always:suggestion

# Expression-level preferences
csharp_prefer_braces = true:silent
csharp_prefer_simple_default_expression = true:suggestion
csharp_style_pattern_local_over_anonymous_function = true:suggestion
csharp_style_inlined_variable_declaration = true:suggestion

# New line preferences
csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_members_in_anonymous_types = true
csharp_new_line_between_query_expression_clauses = true

# Indentation preferences
csharp_indent_case_contents = true
csharp_indent_switch_labels = true
csharp_indent_labels = flush_left

# Space preferences
csharp_space_after_cast = false
csharp_space_after_keywords_in_control_flow_statements = true
csharp_space_between_method_call_parameter_list_parentheses = false
csharp_space_between_method_declaration_parameter_list_parentheses = false
csharp_space_between_parentheses = false
csharp_space_before_colon_in_inheritance_clause = true
csharp_space_after_colon_in_inheritance_clause = true
csharp_space_around_binary_operators = before_and_after
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_call_empty_parameter_list_parentheses = false
```
---
#### Feedback Bot on 4/16/2021, 07:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/16/2021, 11:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment] 2021-04-19 17:52
**NOTE:** This only happens if you are in the folder view (meaning nothing is loaded)

**Comment by jmarolf** [comment] 2021-04-19 17:53
duplicate of https://github.com/dotnet/roslyn/issues/52668

**Closed by jmarolf** 2021-04-19 17:53 UTC
Labels: Area-IDE, Bug, Feature - Editor Config UI, Tenet-Reliability, help wanted
