### ISSUE TITLE
Visual indicator for deprecated code

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#48330] opened 2020-10-05 16:36 UTC
Direct customer ask copying here: 
>Strike through deprecated functions/methods similar to VSCode:
![image](https://user-images.githubusercontent.com/46729679/95106586-8d259b80-06ed-11eb-8ace-7f0cc32040d9.png)

(Twitter comment: https://twitter.com/jeffreypriebe/status/1311831025136279552)

Since the compiler/runtime folks did the work for warnings for deprecated APIs. We can have a visual indicator that lets users know when their code is deprecated.

**Comment by sharwell** [comment] 2020-10-05 23:50
Duplicate of #26488

**Comment by mikadumont** [comment] 2020-12-12 02:41
relates to #26488

**Comment by CyrusNajmabadi** [comment] 2024-10-21 21:35
Closing as dupe.

**Closed by CyrusNajmabadi** 2024-10-21 21:35 UTC
Labels: Resolution-Duplicate, Area-IDE, Feature Request
