### ISSUE TITLE
Refactoring "Generate class in new file" creates file in wrong folder

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#14682] opened 2016-10-22 02:35 UTC
**Steps to Reproduce**:
1. I have project **Foo**.
2. In that project I have a folder with the same name.
3. In that folder I have a file with the following content:

``` csharp
namespace Namespace
{
    public static class Class
    {
        public static void Method()
        {
            var x = new Bar();
        }
    }
}
```

**Bar** is unknown identifier.

When I use "Generate class 'Bar' in new file", the file is placed in project folder but It should be placed in folder 'Foo'.

This error occurs when a project and a folder have the same name.

**Comment by Pilchie** [comment] 2016-11-07 21:25
@JosefPihrt - what type of project was this?  Was it a .NET Core project, or a Shared Project?

**Comment by Pilchie** [comment] 2016-11-07 21:28
If .NET Core, this looks like a duplicate of #8342.

**Comment by JosefPihrt** [comment] 2016-11-08 03:38
It was Portable Project (.NET 4.5, Windows 8, ASP.NET Core 1.0).

**Comment by CyrusNajmabadi** [comment] 2024-10-20 19:28
Closing out due to lack of feedback.

**Closed by CyrusNajmabadi** 2024-10-20 19:28 UTC
Labels: Bug, Area-IDE
