### ISSUE TITLE
Tracking issue to ensure collection spread expression are target typed properly.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#69625] opened 2023-08-19 17:55 UTC
Currently they are target typed by teh element type of the expression.  This is def not correct.  To ensure things work properly, they should likely be target typed to something like `ReadOnlySpan<ElementType>` allowing the expressions there to both properly type, as well as have local scope for stack-allocing.

Relates to test plan https://github.com/dotnet/roslyn/issues/66418

**Comment by cston** [comment] 2023-08-31 21:57
Duplicate of https://github.com/dotnet/roslyn/issues/69277.

**Closed by cston** 2023-08-31 21:57 UTC
Labels: Area-IDE, New Feature - Collection Expressions
