### ISSUE TITLE
Focus issue after adding import

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#2154] opened 2015-04-21 17:28 UTC
Since the end of last week (~4/16) I've been seeing some weird behavior after I add import.  I type an identifier (e.g. ```BitArray```) and, when I get to the end, I hit Ctrl-. Enter (quickly) to add the missing import.  More than 50% of the time (but less than 100%), I'm no longer able to type after the import is added.  Up and Down still move the highlighted "current line", but typed characters don't seem to have any effect.  I do, however, notice a faint dashed line around the editor and nav bars (but not the document tabs), suggesting that focus has moved to a different UI component.

![dashedborder](https://cloud.githubusercontent.com/assets/10508071/7258389/09270e96-e811-11e4-85e7-087d7b5c9ff6.jpg)

**Comment by srivatsn** [comment] 2015-04-27 19:19
Can you check to see if this is a regression in the platform bits?

**Comment by shyamnamboodiripad** [comment] 2015-04-27 22:13
Spoke with folks from the platform team. Seems like this is a dupe of an issue that they fixed last week. 

@amcasey Please reactivate if you continue to run into this on newer drop containing the fix.

**Closed** 2015-04-27 22:13 UTC
Labels: Area-Analyzers, Bug, Resolution-Fixed

**Comment by amcasey** [comment] 2015-05-05 00:32
Verified (e.g. http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_windows_prtest/2352/console)

**Comment by amcasey** [comment] 2015-05-26 17:56
Haven't seen this since moving to the latest base drop.
