### ISSUE TITLE
IDE0058 reported if type does not resolve

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33073] opened 2019-02-02 20:59 UTC
**Version Used**: Visual Studio 2019 Preview 2

**Steps to Reproduce**:

Write the following _without_ including an import for `System.Threading`.

```
await Task.Delay(0, CancellationToken.None).ConfigureAwait(false);
```

**Expected Behavior**:

IDE0058 not reported.

**Actual Behavior**:

IDE0058 is reported, and the code fix adds `_ =` in front of the statement.

**Comment by mavasani** [comment] 2019-02-03 00:18
Very likely a dupe of 
https://github.com/dotnet/roslyn/issues/3295. Will verify and close.9

**Comment by mavasani** [comment] 2019-02-04 19:55
Not a dupe - need to add an additional test for error type.

**Closed** 2019-02-04 23:32 UTC
Labels: 4 - In Review, Area-IDE, Bug, IDE-CodeStyle
