### ISSUE TITLE
FixAllOccurrencesTriggeredFromGeneratedCode failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43330] opened 2020-04-14 02:44 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=599381&view=ms.vss-test-web.build-test-results-tab&runId=18874972&resultId=100390&paneView=debug

```
Assert.Equal() Failure
 ↓ (pos 17)
Expected: 
using System;
class D
{
 public IntPtr X1 { get;
···

Actual: 
using System;
using System.Threading;

class D
{
 ··· ↑ (pos 17)
```

**Comment by sharwell** [comment] 2020-04-14 21:02
@tmat In the build, it appears the OOP process crashed. This test runs a Fix All operation that relies on OOP for diagnostics. It would fail with this outcome if the process crashed.

![image](https://user-images.githubusercontent.com/1408396/79273585-169f9380-7e58-11ea-8f3b-f979d533b5ad.png)

The process crashed with the following:

```
Event Time (UTC): 4/14/2020 1:49:44 AM
Event ID: 1026
Data: Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.CodeAnalysis.FailFast.DumpStackTrace(System.Exception, System.String)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.CodeAnalysis.SQLite.v1.Interop.SqlConnection.Finalize()
```

**Comment by sharwell** [comment] 2020-04-14 21:08
Closing as Not Reproducible since the underlying cause of the failure is unrelated to the test in question.

**Closed by sharwell** 2020-04-14 21:08 UTC
Labels: Area-IDE, Resolution-Not Reproducible, Test
