### ISSUE TITLE
GenerateMethodCrossLanguageTests.GenerateMethodUsingTypeConstraint_SingleNamedType test is flaky

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#9263] opened 2016-02-27 00:02 UTC
See build http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4411/

**Comment by jmarolf** [comment] 2016-03-01 23:53
Duplicate of https://github.com/dotnet/roslyn/issues/9308

**Closed by jmarolf** 2016-03-01 23:53 UTC
Labels: Area-IDE, Flaky, Test, Urgency-Soon
