### ISSUE TITLE
Impossible to implement Source Generators for projects targeting .NET 8

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/roslyn#70922] opened 2023-11-21 18:19 UTC
**Version Used**: 
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198
```

**Steps to Reproduce**:

1. Have main project which targets `net8.0` TFM
2. Have supplementary project which targets `netstandard2.0` because it is a requirement for Source Generators
3. Impossible to reference a newer project and use code that can only work on newer TFMs from that said project

**Expected Behavior**:
Source generators do not have arbitrary restriction and can target `net8.0` TFM or reference such projects.

**Actual Behavior**:
For source generators to work according to the specification, the project containing them must target `netstandard2.0`. This makes source generators unusable for projects that simply cannot target `nestandard2.0` due to runtime features required (if source generators need to reference such projects).

**Comment by jcouv** [comment] 2023-11-21 21:56
Closing as duplicate of https://github.com/dotnet/roslyn/issues/45162. This is by-design at the moment. Sorry for the inconvenience

**Closed by jcouv** 2023-11-21 21:56 UTC
Labels: Area-Compilers, untriaged

**Comment by neon-sunset** [comment] 2023-11-22 02:38
@jcouv the original issue and every other ones are closed. I do understand that this is caused by the existence of Visual Studio and the fact that it's stuck with .NET Framework but closing this is just saying "we will never fix this, take it or leave it". Not exactly the level of response one would expect from .NET teams?

**Comment by CyrusNajmabadi** [comment] 2023-11-22 06:46
@neon-sunset This is the current design.  So things are working as expected here, and it isn't a bug from our perspective that the limitations we have explicitly stated are in effect.

If things change in this front, then we'll let people know.  But for now, this is the expected behavior.

**Comment by jacob7395** [comment] 2024-04-22 16:11
@CyrusNajmabadi sorry to drag up an old issues but is this say that if I can't use source code generation in .net 8.

I've left my generator project on netstandard2.0, then updated my main project to .net 8 and my generator just don't seem to work anymore.

Is this by design? or am I missing somehting.
