### ISSUE TITLE
Widespread failings across LanguageServices and EditorFeatures

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9179] opened 2016-02-25 16:28 UTC
PR: [#9152](https://github.com/dotnet/roslyn/pull/9152) *Revert "Temporary disable archiving"* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4253/

**2261 Test Failures:** (showing first 10)
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteAddedToDescription_DifferentSnippetShortcutCasing
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteNotAddedToDescription_ShortcutIsProperSubstringOfInsertedText
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteAddedToDescription_ExactMatch
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteAddedToDescription_DisplayTextDoesNotMatchShortcutButInsertionTextDoes
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteNotAddedToDescription_ShortcutIsProperSuperstringOfInsertedText
Microsoft.VisualStudio.LanguageServices.UnitTests.Completion.VisualBasicCompletionSnippetNoteTests.SnippetExpansionNoteNotAddedToDescription_DisplayTextMatchesShortcutButInsertionTextDoesNot
Microsoft.VisualStudio.LanguageServices.UnitTests.DebuggerIntelliSense.VisualBasicDebuggerIntellisenseTests.SignatureHelpInMethodCall
Microsoft.VisualStudio.LanguageServices.UnitTests.DebuggerIntelliSense.VisualBasicDebuggerIntellisenseTests.ExitingMethod
Microsoft.VisualStudio.LanguageServices.UnitTests.DebuggerIntelliSense.VisualBasicDebuggerIntellisenseTests.EnteringMethod
Microsoft.VisualStudio.LanguageServices.UnitTests.DebuggerIntelliSense.VisualBasicDebuggerIntellisenseTests.CompletionInExpression

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment] 2016-02-25 16:30
Make note this build the tests didn't actually fail in my build, due to @jaredpar's test runner thing that prevents us from running unneeded tests, this likely failed in a earlier build.

**Comment by davkean** [comment] 2016-02-25 16:45
I had a look into this, given the Jenkins outage, I [can't find a build](http://dotnet-ci.cloudapp.net/computer/dci-win-tbld-26/builds) before mine that actually caused the failure, but the test results have been uploaded so we might be able to gleam something from it.

**Comment by jaredpar** [comment] 2016-02-25 16:51
This is the run that broke the suites

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4241/

**Comment by davkean** [comment] 2016-02-25 16:58
Hmm, can't figure out what happened here @jasonmalinowski's  [PR](https://github.com/dotnet/roslyn/pull/9062) seems to have trigged the build, but I can't see where or how the failure showed up on it. 

As far as I can see, Jason didn't retest or push a new commit. @jasonmalinowski?

**Comment by jasonmalinowski** [comment] 2016-02-25 17:58
I closed/reopened the PR, wanting to make sure that Jenkins was merged against latest.

**Comment by jasonmalinowski** [comment] 2016-02-25 17:59
I did do a new push: I amended the commit to re-add the null check I accidentally lost that caused all the tests to fail.

**Comment by davkean** [comment] 2016-02-25 18:00
@jaredpar This looks like a bug then in your test runner. Why didn't this re-trigger the tests to run?

**Comment by jasonmalinowski** [comment] 2016-02-25 18:01
I think this is a GitHub (!) bug:

![image](https://cloud.githubusercontent.com/assets/201340/13328986/80b50164-dba6-11e5-9a51-9d08e3941f8e.png)

Observe the commit that was pushed and tested was 71d2e07, but the "merged" commit is 651dfbb. It seems like I did a force push and it did test my new commit, but inexplicably it still merged my old one.

**Comment by jaredpar** [comment] 2016-02-25 18:01
@davkean because the content didn't change.  Even though @jasonmalinowski pushed he didn't change any code.  Hence the caching logic sees the same bits being run and grabs the previous result.

**Comment by davkean** [comment] 2016-02-25 18:02
The plot thickens...

**Comment by jasonmalinowski** [comment] 2016-02-25 18:02
Nope, deleting my statement about GitHub merge. The commit named is the merge commit.

**Comment by jasonmalinowski** [comment] 2016-02-25 18:03
@jaredpar: the content most definitely changed. I added a null check to the product.

**Comment by jasonmalinowski** [comment] 2016-02-25 18:11
@jaredpar: how do you handle MEF? Checking now, but I'm wondering if this is a case that we load the assembly I changed through MEF, but the assembly itself doesn't have a stated dependency.

**Comment by jaredpar** [comment] 2016-02-25 18:14
Here is the data I'm seeing.  

Original Failure:

- Jenkins Job: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4241/
- Commit: ea631718b524eab90a1c27f7a10c2030eaa0605b

Failure for this Isssue:

- Jenkins Job: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4253
- Commit: 88efb3824085bf0e15805595113c3a9db150c034

@jasonmalinowski change:

- Commit:  6ba53d330e050fcb538f3f1ee4121e725ed11184
- Merge Commit: 651dfbb 

If you follow the Git history.  The only change is an IVT change between the original failure and the one listed in this issue.  This wouldn't affect the cache key for this assembly (to my knowledge).

**Comment by jaredpar** [comment] 2016-02-25 18:15
@jasonmalinowski MEF is not handled today.  When we originally reviewed this we concluded the test assemblies themselves referenced everything loaded by MEF hence it wasn't a factor.  If it became one though we were going to find a way to declaratively add it to the cache.

**Comment by jasonmalinowski** [comment] 2016-02-25 18:21
@jaredpar: that's not the only change. I amended my commit in the PR. The original tested commit was ea63171, but the final commit was 71d2e07. These differ by a null check:

F:\Projects\Roslyn\Open>git diff ea63171 71d2e07
```
diff --git a/src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Expressions/TrueFalseKeywordRecommender.vb b/src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Expressions/TrueFalseKeywordRecommender.vb
index 9fe00b4..b9db7a1 100644
--- a/src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Expressions/TrueFalseKeywordRecommender.vb
+++ b/src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Expressions/TrueFalseKeywordRecommender.vb
@@ -28,6 +28,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Expr
             ' This function still gets test coverage through the all-up completion tests.
             Dim document = context.Workspace?.CurrentSolution.GetDocument(context.SyntaxTree)

+            If document Is Nothing Then
+                Return False
+            End If
+
             Dim typeInferenceService = document.Project.LanguageServices.GetService(Of ITypeInferenceService)()
             Dim types = typeInferenceService.InferTypes(context.SemanticModel, context.Position, cancellationToken)
```

**Comment by jaredpar** [comment] 2016-02-25 19:11
@jasonmalinowski and I have worked an this for a bit and are at a bit of an impasse:

- It seems unlikely to be a bug in the test runner.  The key that is generated for the test results includes a checksum of all referenced binaries.  Manually verified this does include the binary @jasonmalinowski changed with his commit.  Hence for this to produce a false positive his commit would have necessarily had an MD5 collision between the two versions of the binary.  That seems extremely unlikely.  
- One possibly explanation is a bad up to date check.  Given these tests ran on the same machine it's possible that MSBuild reused a binary vs. rebuilding.  If that binary was the one with the bad change then it would result in this behavior.  Agree this is unlikely , but seems less so than an MD5 collision. 
- Jenkins doesn't actually build the commit it lists but rather a merge of that commit and the state of HEAD at the time the job is run.  Makes it hard to try and reproduce this locally.  Considering augmenting cibuild.cmd to make it clearer what actually gets built here.  
- Archiving was disabled for the period when these tests ran.  Hence we can't even dig into the logs here to see what actually happened.

**Comment by davkean** [comment] 2016-02-25 19:54
@jaredpar What do you want to do with this? I'm guessing there's not enough information to figure this out? If not, let's close it and watch for more cases.

**Comment by jaredpar** [comment] 2016-02-25 20:59
I think we should close for now and see if this comes up again.  With archiving and the logic @jasonmalinowski is adding it should let us look into this next time it happens.

**Closed by jaredpar** 2016-02-25 20:59 UTC
Labels: Area-Infrastructure, Bug
