### ISSUE TITLE
collapse summary into code block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45491] opened 2020-06-26 21:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1086799/collapse-summary-into-code-block.html)._

---
As a (good?) developer, I write a lot of triple slash code comments.  Practically on anything not marked as private.
When navigating over a class that has many responsibilities - many methods, I tend to collapse code down to the method, and naturally, I collapse the summary text (triple slash comments) down to a single row too.

I therefore see pairs of rows for each method, both collapsed, and the summary collapsed above it. 

The Summary in this sense can become noise on screen when all you want is to scan over the code and read the method names.

I propose that we allow the Summary to collapse into the class / method definition - as they are related.
Perhaps the little line between the two [+] icons when hovered over will change to a new symbol suggesting you can click on it, and it will collapse the summary into the class/method.  The class/method [+] icon perhaps could become a few pixels larger to imply multiple collapses.

The reverse should also be true - that clicking the "big" [+] icon will first expand to two [+] icons of smaller size, restoring the current view of two rows of [+] icons, with their normal behaviours.

To be clear other than the expanding icon size, this is really the same behaviour as enclosing the class/method and its triple slash comments into a #region with a name identical to the method.  But do I really want all those regions adding noise to the code when it is not collapsed?

---
#### Visual Studio Feedback System on 6/23/2020, 00:20 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by dibarbet** [comment] 2020-07-20 21:47
This is a duplicate of https://github.com/dotnet/roslyn/issues/43285 where we will make the behavior similar to MetadataAsSource

**Closed by dibarbet** 2020-07-20 21:47 UTC
Labels: Area-IDE, Developer Community, Feature Request, Need Design Review
