### ISSUE TITLE
Find All References/Goto Implementation for a C# declaration doesn't find information in VB code 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#42998] opened 2020-04-01 22:31 UTC
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.6.0 Preview 3.0 [29930.152.master]

**Steps to Reproduce**:

1. Find all references or Goto Implementation on 
```internal abstract void ComputeDeclarationsInSpan(TextSpan span, bool getSymbol, ArrayBuilder<DeclarationInfo> builder, CancellationToken cancellationToken);``` in SemanticModel.

**Expected Behavior**:

Should find an override in VB compiler

**Actual Behavior**:

Only an override in C# compiler is found.

![image](https://user-images.githubusercontent.com/10522107/78192722-8d3a9b00-742d-11ea-8501-26678ab3b107.png)

![image](https://user-images.githubusercontent.com/10522107/78192788-b8bd8580-742d-11ea-8666-a94985b8876c.png)

**Comment by sharwell** [comment] 2020-04-08 19:00
Duplicate of #43093

**Closed by sharwell** 2020-04-08 19:00 UTC
Labels: Area-IDE, Bug, IDE-Navigation
