### ISSUE TITLE
"Unresolvable conflict" when renaming a C# 9 record property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50450] opened 2021-01-14 02:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Unresolvable-conflict-when-renaming-a-/1275487)._

---
[severity:It bothers me. A fix would be nice]
Using Visual Studio 2019 v16.8.2 with a .NET 5 project.

Renaming a property within a C# 9 record does not rename any usages of that property, like it would for a regular _class_ property.

I tried the following scenario's:
1. Within the record constructor, change the property name and then hit Ctrl+. to select the 'Rename' refactoring from the quick actions.
2. Within the record constructor, hit the rename command (Ctrl+R, Ctrl+R), and type the new name.
3. On any property use, change the property name and then hit Ctrl+. to select the 'Rename' refactoring from the quick actions.
4. On any property use, hit the rename command (Ctrl+R, Ctrl+R), and type the new name.

The results were as follows:
In scenario 1 the rename action just silently fails to update anything.
In scenario 2 there is a notion of 'Unresolvable conflict' (see screenshot below).
In scenario 3 & 4, rename works properly (ie. it will also update the property declaration and all other usages).

! [image.png] (https://aka.ms/dc/image?name=Be87d81ec94434456bf69d23edf00ae5e637425096607254506_20201202-134059-image.png&tid=e87d81ec94434456bf69d23edf00ae5e637425096607254506)

---
#### Feedback Bot on 12/2/2020, 10:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/3/2020, 11:06 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-05-14 14:38
Possible duplicate of #44560.

**Comment by jjanuszkiewicz** [comment] 2021-09-20 06:19
I've just noticed this in the most recent VS2022 preview (VisualStudio.17.Preview/17.0.0-pre.4.0+31710.8), this is 
quite irritating. A fix would be very welcome.

**Comment by danielabbatt** [comment] 2022-01-15 11:59
Yes this is really annoying. I'd love to use the concise form of Records but I can't use the VS2022 (17.0.5 at time of writing this) to get references to the properties if they're defined in the short concise form at the point of definition.

If I go find an actual record property reference in the code, I can then use the usual "Find all references" functionality and do a rename from there; but this is quite counter intuitive and the only way I can find where the references are initially is to change the property name in the record definition so it highlights in the code where the now broken references are.

**Comment by Lumoryel** [comment] 2022-01-31 09:44
Same here. I really need this feature. "Find all references" on a record field isn't working either :(

**Comment by CyrusNajmabadi** [comment] 2024-07-18 00:01
Should be fixed with https://github.com/dotnet/roslyn/pull/74168

**Closed by CyrusNajmabadi** 2024-07-18 00:01 UTC
Labels: Area-IDE, Concept-Continuous Improvement, New Language Feature - Records, Developer Community, Feature - Rename
