### ISSUE TITLE
Add option to default all analyzer rules to a specific severity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39827] opened 2019-11-14 18:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/819126/add-option-to-default-all-analyzer-rules-to-a-spec.html)._

---
It would be nice for the purpose of organization and control if all analyzers could be defaulted to a severity.

One could then default all rules to 'None' and then opt-in on all rules they care about.

The current pattern can be hard to track since rules have a variety of defaults, some of which a user might agree with or not.

This provides a clear way to do both opt-in and opt-out patterns for analyzers.

Possibly it would be good if this was on a per analyzer namespace basis.

---
#### Visual Studio Feedback System on 11/13/2019, 11:22 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment] 2019-12-04 20:49
cc @mavasani

**Comment by mavasani** [comment] 2019-12-04 20:54
Duplicate of https://github.com/dotnet/roslyn/issues/38674. Support for this has been added for upcoming VS2019 16.5 release with syntax as per https://github.com/dotnet/roslyn/pull/38886#issue-321838740. This will also be documented at https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers once VS2019 16.5 is released.

**Closed by mavasani** 2019-12-04 20:54 UTC
Labels: Area-Analyzers, Developer Community, Feature Request, Need Design Review
