### ISSUE TITLE
"Simplify name" has started enforcing var & this. usage opposite to editorconfig settings

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27819] opened 2018-06-14 04:27 UTC
**Version Used**: 
Version 15.8.0 Preview 3.0 [27807.3004.d15.8stg]

This is a regression from 15.7. "Simplify name" (IDE0001) has started enforcing var usage, despite "use 'var' instead of explicit type" (IDE0007) already enforcing this.

It also isn't respecting var settings:

```
csharp_style_var_for_built_in_types = true:none
csharp_style_var_elsewhere = true:none
```

**Steps to Reproduce**:

``` C#
    class Program
    {
        static void Main(string[] args)
        {
            FileData curData = CreateData();
        }

        private static FileData CreateData()
        {
            throw new NotImplementedException();
        }
    }
``` 

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/41391585-dad1c028-6fde-11e8-91cf-de496bd9d347.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/41391576-d27b4124-6fde-11e8-9e38-212dcab32913.png)

In my tree, this actually causing it to show up as error:

![image](https://user-images.githubusercontent.com/1103906/41391619-fb0d3282-6fde-11e8-99ed-2fcd14924127.png)

**Comment by davkean** [comment] 2018-06-14 04:27
@CyrusNajmabadi I think you made some changes here, right?

**Comment by CyrusNajmabadi** [comment] 2018-06-14 18:21
I made some changes in the core simplifier code to respect user preferences and attempt to convert code with the 'simplifier' annotation to those preferences.  That way certain features (like for-to-foreach/etc.) could just generate variables, and roslyn would appropriately use 'var' if possible.  In that regard, i think my work was correct.

However, I think the core issue here is that the SimplifyTypeNames code fix provider works *not* by just taking the node-in-question and simplifying the name.  Instead, it just adds the 'simplifier' annotation and lets the core simplifier infrastructure take over.  This is fairly dangerous because it's trying to offer a specific behavior, but doing so by sitting on top of a huge subsystem that is effectively allowed to do whatever it wants to code to make it fit user-options.  

The appropriate fix here would likely be to make the SimplifyTypeNames provider act more like all the rest of our providers.  Namely, it should be given a diagnostic on a node, and it would perform a very specific and precise rewriting of that node to produce the correct final result.

Note: a mitigating fix might be to just add the DoNotAllowVarAnnotation on the node when the SimplifyTypeNames provider operates on it.   However, we'd still be somewhat at hte mercy of the simplifier not wanting to perform other changes to it.

--

Tagging @sharwell .  I think this intersects, but is orthogonal to, all the work i'm doing to make a cohesive experience around 'simplify names'.  Frankly, there seem to be so many issues/concerns/interactions, that i think this is a feature area that might just need to go to a design review.  Effectively we need to establish:

1. What are the sets of options users have to control things (afaict, we already have that).
2. How do all these options interact with each other.
3. What is the user experience around all the diagnostics, the lightbulbs, and the fixes.

This design would help at least produce a quality test suite that we could then use to ensure things were behaving properly.  Right now, our test suites are very good for testing just hte feature on its own.  But it's not that great at testing these sorts of overlapping areas.

**Comment by davkean** [comment] 2018-07-12 02:56
I have the var rules and simplifier fighting each other wanting to undo each other:

![image](https://user-images.githubusercontent.com/1103906/42610016-d1de4fcc-85d2-11e8-89d4-b5f2d57ecc33.png)

![image](https://user-images.githubusercontent.com/1103906/42610040-e7e253f4-85d2-11e8-8b6e-c422f239cdf6.png)

**Comment by CyrusNajmabadi** [comment] 2018-07-12 03:05
Your first picture is a screwdriver.  It is intentional that it is offered and that it can go against your actual settings.  It exists for cases where you want to deviate, and you would still like the IDE's help to generate the type name.

Note that the first one is not suggested to you with any sort of squiggle/dots/etc.  it is simply a tool that you can choose to use if you want.  In this case, you asked to flip the 'var' to a full type, so the IDE happily did what you asked for :)

**Comment by CyrusNajmabadi** [comment] 2018-07-12 03:06
Note: we have this model for many part of our system (and intend to have it for pretty much everything that can be flipped between states).   For example, you may have a style preference that you want ```=>``` bodied methods.  But then, you decide on one of your methods you don't actually like that.  So the screwdriver is there to give you quick access to the 'convert to block body' change for that case.

**Comment by davkean** [comment] 2018-07-12 03:10
Yeah, looks like I'm getting confused because I'm getting asked to do reverse things in the following:

``` C#
        public static async Task TimeoutAfter(this Task task, TimeSpan timeout)
        {
            using (var cts = new CancellationTokenSource())
            {
                Task timeoutTask = Task.Delay(timeout, cts.Token);
                var completedTask = await Task.WhenAny(task, timeoutTask)
                                              .ConfigureAwait(false);

                if (timeoutTask == completedTask)
                    throw new TimeoutException($"Task timed out after {timeout.TotalMilliseconds} ms");

                cts.Cancel();
                await task.ConfigureAwait(false);
            }
        }
```

My error list states:

```
Message	IDE0008	Use explicit type instead of 'var'	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\Threading\Tasks\TaskTimeoutExtensions.cs	12	Active
Error	IDE0001	Name can be simplified.	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\Threading\Tasks\TaskTimeoutExtensions.cs	11	Active
Message	IDE0007	use 'var' instead of explicit type	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\Threading\Tasks\TaskTimeoutExtensions.cs	11	Active

```

I'm getting asked to do reverse things to `timeoutTask` and `completedTask` for reasons I don't understand.

**Comment by davkean** [comment] 2018-07-12 03:17
Oh, it looks like it's stating that `Task.Delay` obviously returns `Task` but I'm awaiting `Task.WhenAny` which return type is not obvious. Wish there was a way to say "CTRL+." doesn't do refactorings.

**Comment by CyrusNajmabadi** [comment] 2018-07-12 03:30
hrmm.. the problem with the Task.WhenAny is that you're acutally awaiting ```....ConfigureAwait(false)```.  And we don't consider the type 'obvious' there.  We might want to special case that one though and just ask "is the type obvious on hte left of the ConfigureAwait?"

The reason Task.Delay is considered obvious is that's it's a static method on a type that returns an instance of that type.  i.e. something like "Int32.Parse" or "XElement.Load".  We essentially consider those 'factory methods' and we consider their type as being 'apparent' since you wrote it in the source.

**Comment by davkean** [comment] 2018-07-12 03:33
It's not the ConfigureAwait, it's the await. `Task.WhenAny` returns `Task<Task>`, it's the unwrapped `Task` that its saying is not obvious.

**Comment by CyrusNajmabadi** [comment] 2018-07-12 03:36
Ah, interesting.  I wonder if that's appropriate... or not.   There are many examples of a non-generic type having a static method that returns a generic type.  i.e.  ValueTuple.Create, ImmutableArray.Create, etc. etc.  i think it would make sense to consider that 'apparent'.

**Comment by CyrusNajmabadi** [comment] 2018-07-12 03:40
Note: i actually think both ConfigureAwait and Task<task> are hte problems.  `ConfigureAwait` is a problem due to:

https://github.com/dotnet/roslyn/blob/fe0fe4096f4109652a981f7577a1bf5f5e565d52/src/Workspaces/CSharp/Portable/CodeStyle/TypeStyle/TypeStyleHelper.cs#L132

Here we get the rightmost invocation (i.e. ```ConfigureAwait(false)```).

However, even if we fixed that, we woudl still be blocked here:

https://github.com/dotnet/roslyn/blob/fe0fe4096f4109652a981f7577a1bf5f5e565d52/src/Workspaces/CSharp/Portable/CodeStyle/TypeStyle/TypeStyleHelper.cs#L210-L212

Here we would not consider a generic type 'apperant' when being created from a non-generic starting type.

Can you file a bug on this @davkean ?  I think it would be valuable to have the IDE improve here.

**Comment by davkean** [comment] 2018-08-06 01:40
This has also started enforcing "this." removal usage. I see multiple weirdness:

If I have the following settings:

```
# Avoid "this." and "Me." if not necessary
dotnet_style_qualification_for_field = false:warning
dotnet_style_qualification_for_property = false:warning
dotnet_style_qualification_for_method = false:warning
dotnet_style_qualification_for_event = false:warning
```

It treats "this" qualification as an error despite it being a warning:

![image](https://user-images.githubusercontent.com/1103906/43692704-ffae9e4a-996c-11e8-85cb-00a3ae11fd12.png)

If I reverse the settings and enforce this. qualification:

```
# Avoid "this." and "Me." if not necessary
dotnet_style_qualification_for_field = true:information
dotnet_style_qualification_for_property = true:information
dotnet_style_qualification_for_method = true:information
dotnet_style_qualification_for_event = true:information
```

It still greys out and wants me to remove "this.":

![image](https://user-images.githubusercontent.com/1103906/43692722-2f090a36-996d-11e8-9bea-3af2836e5551.png)

I'm about to present a talk on this and I cannot explain how this behavior works.

**Comment by CyrusNajmabadi** [comment] 2018-08-06 01:53
When using hte VS UI i do not repro this.  For your first case, i have the UI at:

![image](https://user-images.githubusercontent.com/4564579/43692958-5f5ecb86-98f9-11e8-88cb-e8a147aae728.png)

This produces as warning as expected:

![image](https://user-images.githubusercontent.com/4564579/43692988-89a158dc-98f9-11e8-8869-98e4124754c6.png)

With the right fix:

![image](https://user-images.githubusercontent.com/4564579/43692991-90ba85c6-98f9-11e8-8cc9-f8450e32178d.png)

--

If i then change the options to the second form:

![image](https://user-images.githubusercontent.com/4564579/43693017-ac99ab96-98f9-11e8-8822-635b226e9dc1.png)

Then i get this experience:

![image](https://user-images.githubusercontent.com/4564579/43693023-ba0350d4-98f9-11e8-8aa9-e0beee2a1e31.png)

Again, as expected.

--

So, this does not appear to be a feature bug, or a general issue with its options.  if you are seeing this behavior is sounds like it is something specific to editor config.   @sharwell @heejaechang  Do you know of any issues here that would cause the wrong values to be sent to the analyzer which could affect this?

**Comment by davkean** [comment] 2018-08-06 02:02
I updated above, the error behavior was a mistake on my part - I had TreatWarningsAsErrors turn on.

With regards to the second issue, I found the repo - if I have the following settings in Options:

![image](https://user-images.githubusercontent.com/1103906/43693250-473859c4-9970-11e8-95eb-88b2a3f67902.png)

But the following settings in editorconfig:

```
# Avoid "this." and "Me." if not necessary
dotnet_style_qualification_for_field = true:information
dotnet_style_qualification_for_property = true:information
dotnet_style_qualification_for_method = true:information
dotnet_style_qualification_for_event = true:information
```

Then the greying out occurs. It looks those editorconfig settings aren't be respected at all. It doesn't flag usage when I remove the "this." either.

**Comment by CyrusNajmabadi** [comment] 2018-08-06 02:10
> I updated above, the error behavior was a mistake on my part - I had TreatWarningsAsErrors turn on.

No worries.   That's a totally easy mistake to make :)

> Then the greying out occurs. It looks those editorconfig settings aren't be respected for the "true" case - it is being respected for the false case. It doesn't flag usage when I remove the "this." either.

I think the problem is "true:information".  There is no such category as "information".  The categories are:

none
warning
error
suggestion
refactoring (or silent)

If you say "true:information" i think we effectively say "fuck if i know what that means".  

There's actually no difference if you use "false" afaict.  It's just that in both cases we go back to the 'default' value (which is 'false'), so screwing things up there isn't really a problem since the fallback is to the value you wanted.

**Comment by CyrusNajmabadi** [comment] 2018-08-06 02:11
@sharwell @kuhlenh .  Are there any items tracking validation and notification of invalid .editorconfig values?  I think it would likely be pretty handy to be able to at least warn somewhere that we didn't understand the value the user entered.  It might help avoid very easy mistakes that then lead to totally inexplicable behavior (from the user's perspective at least)!

**Comment by davkean** [comment] 2018-08-06 02:11
Ugh so this is me getting confused again...

**Comment by CyrusNajmabadi** [comment] 2018-08-06 02:15
Maybe :)   But designs that let you fall into this trap certainly are not what i would describe as "good" or "user friendly".  When things aren't working properly, and you have no idea how to tell why... it's not good.  I'm hoping we can do something in the future to highlight these issues in a clear way.

--

Also, on a good note, @allisonchou is working on a cool feature to generate a .editorconfig from the VS options:

https://github.com/dotnet/roslyn/pull/28472

That would certainly have helped here as you could have likely generated the options you wanted from the UI, without having to worry about them being incorrect!

**Comment by davkean** [comment] 2018-08-06 02:18
That would work for the first time I'm creating an editorconfig, but once you've generated it what options do I have? What I really want is a Visual Studio editor or squiggles inline/intellisense in the editorconfig itself.

**Comment by CyrusNajmabadi** [comment] 2018-08-06 02:27
> That would work for the first time I'm creating an editorconfig, but once you've generated it what options do I have?

Generate a new one.  Copy out the parts you care about :)

> What I really want is a Visual Studio editor or squiggles inline/intellisense in the editorconfig itself.

Makes sense to me.  I think that will hopefully be possible soon.  @agocke with your editorconfig work, with the .editorconfig file be part of the compilation?  if so, it should hopefully be possible for Roslyn to hook up editor services to it (like squiggles).

**Comment by sharwell** [comment] 2018-08-06 17:18
> Are there any items tracking validation and notification of invalid .editorconfig values?

#19055

> What I really want is a Visual Studio editor or squiggles inline/intellisense in the editorconfig itself.

This is something we are tracking, but since it applies to more than just Roslyn content it's being tracked on one of the internal bug lists.

> if so, it should hopefully be possible for Roslyn to hook up editor services to it (like squiggles).

Possibly #6649
More generally, we have a known limitation where diagnostics reported outside of source files doesn't provide a good editor (squiggle) or code fix (light bulb) experience.

**Comment by davkean** [comment] 2018-08-07 11:30
Reopening, Simplify name is still enforcing var usage, despite the conversations latter in this thread.

**Comment by sharwell** [comment] 2018-08-07 12:54
@davkean I just verified that IDE0001 is not enforcing `var` usage. There was however a change to the code fix behavior for IDE0001. Consider the following configuration and source file:

```ini
root = true

[*.cs]
# Use language keywords instead of framework type names for type references
dotnet_style_predefined_type_for_locals_parameters_members = true:warning
dotnet_style_predefined_type_for_member_access = true:warning

# Prefer "var" everywhere
csharp_style_var_for_built_in_types = true:warning
csharp_style_var_when_type_is_apparent = true:warning
csharp_style_var_elsewhere = true:warning
```

```csharp
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        void Method()
        {
            String value = "";
        }
    }
}
```

This code produces the same warnings in 15.7 and 15.8:

1. IDE0001 for the use of `String` instead of `string`
2. IDE0007 for the use of an explicit type name instead of `var`

Since the enforcement of code style relates to the set of warnings reported for a given configuration and input, this is not a regression with respect to the enforcement of preferences. That leaves the code fix...

The behavior change is the code fix for IDE0001 now changes the code from `String`&rarr;`var` instead of requiring the user first go from `String`&rarr;`string` and second from `string`&rarr;`var`. I'll add this to the design review list since the behavior is leading to confusion.

**Comment by sharwell** [comment] 2018-08-07 13:03
@davkean I just verified that IDE0001 is not enforcing `var` usage. There was however a change to the code fix behavior for IDE0001 and a change to warning IDE0012. Consider the following configuration and source file:

```ini
root = true

[*.cs]
# Use language keywords instead of framework type names for type references
dotnet_style_predefined_type_for_locals_parameters_members = true:warning
dotnet_style_predefined_type_for_member_access = true:warning

# Prefer "var" everywhere
csharp_style_var_for_built_in_types = true:warning
csharp_style_var_when_type_is_apparent = true:warning
csharp_style_var_elsewhere = true:warning
```

```csharp
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        void Method()
        {
            String value = "";
        }
    }
}
```

This code produces the following warnings in 15.7 and 15.8.

1. IDE0001 (15.8 only as a hidden diagnostic) as a trigger for Simplify Type Name code fix
1. IDE0007 for the use of an explicit type name instead of `var`
1. IDE0012 (15.7 only as a warning) for the use of `String` instead of `string`

Since the enforcement of code style relates to the set of warnings reported for a given configuration and input, this is not a regression with respect to the enforcement of preferences. 15.8 produces fewer and more specific warnings for the same code than 15.7 produced. That leaves the code fix...

The behavior change is the code fix for IDE0001 now changes the code from `String`&rarr;`var` instead of requiring the user first go from `String`&rarr;`string` and second from `string`&rarr;`var` (fixing two warnings separately). I'll add this to the design review list since the behavior is leading to confusion, but overall the current design is a streamlined approach to the same configuration enforced in both versions.

**Comment by davkean** [comment] 2018-08-10 03:11
@sharwell 
My var rules state:

```
[*.cs]
# Prefer "var" only when the type is apparent
csharp_style_var_for_built_in_types = false:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = false:suggestion

[src/*Tests/**/*.cs]
# We allow usage of "var" inside tests as it reduces churn as we remove/rename types
csharp_style_var_for_built_in_types = true:none
csharp_style_var_elsewhere = true:none

```

Inside my tests, I am getting an error:

![image](https://user-images.githubusercontent.com/1103906/43936960-790ad61c-9c9e-11e8-80a1-5069624e0bfa.png)

TBH, I don't have enough time to understand how this stuff all works, but I just want the IDE to stop telling me that I must change this line of code. This doesn't repro in 15.7 and therefore is a regression.

**Comment by davkean** [comment] 2018-08-10 03:11
This is what it looks like in 15.7:
![image](https://user-images.githubusercontent.com/1103906/43937062-ecadbbe8-9c9e-11e8-810e-b524b2ae40e7.png)

**Comment by CyrusNajmabadi** [comment] 2018-08-10 04:36
Fascinating.  It's unclear to me how that would ever happen.  Effectively, something which at worst should be a suggestion is being mapped to an error.  @sharwell could this be some of the ReportDiagnostic/Severity stuff you were working on?

**Comment by davkean** [comment] 2018-08-10 04:39
We've come full circle, it's happening because I have "Simplify name" turned on as an error, and it's started enforcing var usage whereas it didn't in 15.7.

**Comment by CyrusNajmabadi** [comment] 2018-08-10 04:54
@davkean Can you give me the precise settings you're talking about?  I want to make sure i'm not inferring something different from what you're trying to say.  Thanks!

**Comment by davkean** [comment] 2018-08-10 06:34
In 15.7, there was a single rule that enforced var usage (IDE0007).
In 15.8, there are now two rules that enforce var usage (IDE0001 and IDE0007).

We have a ruleset that says IDE0001 is an error:

``` XML
<Rule Id="IDE0001" Action="Error" />                      <!-- Simplify names                               System.Version version;                             Version version;                      -->
```

We have an editor config entry that says IDE0007 is not an error, but only for refactoring:

```
csharp_style_var_elsewhere = true:none
```

**Comment by CyrusNajmabadi** [comment] 2018-08-10 07:05
Gotcha.  Yes, i think i see the problem.  The issue is that the simplifier says: "yup.  i totally can simplify things.  i can simplify things by using 'var' here instead of your full name".  While that is true, it definitely goes against your spirit/intent here.

@sharwell @dotnet/roslyn-ide :
It's likely that we do not want the SimplifyTypeNamesDiagnosticAnalyzer codepath to actually allow this to happen.  The only codepaths that should deal with 'var' (and the surrounding diagnostics/suggestions/warnings/errors) should be the UseImplicitType/UseExplicitType analyzers/providers.

In terms of the actual fix, i can see two things we could do:
1. have SimplifyTypeNamesDiagnosticAnalyzer pass some sort of flag to TryReduceOrSimplifyExplicitName saying "do not try to simplify to var".  or
2. Just call TryReduceOrSimplifyExplicitName, but if you get 'var' back, ignore the result.

**Comment by sharwell** [comment] 2018-08-10 11:30
We could also set the NotConfigurable flag for IDE0001. This ID was never designed for use as anything other than hidden.

**Comment by sharwell** [comment] 2018-08-20 04:40
> We could also set the NotConfigurable flag for IDE0001. 

I believe this is the direction we are planning to pursue. More visible diagnostics for enforcing code style will be provided through other diagnostic IDs that focus on specific behaviors.

**Comment by davkean** [comment] 2018-08-20 04:41
Do not regress this until you have a replacement.

**Comment by sharwell** [comment] 2018-08-20 04:46
> Do not regress this until you have a replacement.

The diagnostic was not intended to be used in the manner seen in the project-system project. The ability of a ruleset file to change the reporting of this diagnostic in ways that cannot be represented in a .editorconfig file isn't accounted for in the design of the diagnostic, so the NotConfigurable flag is simply correcting these cases to adhere to the original design.

**Comment by davkean** [comment] 2018-08-20 04:49
I don't work on this so I have to assume those words are correct, just make sure you let me control this before you regress it again.

**Comment by sharwell** [comment] 2018-10-29 13:22
Tentatively marking this as **Won't Fix** prior to today's design review, but leaving this open until we complete the review the proposed resolution. I'll update the issue following the review.

**Comment by Neme12** [comment] 2018-10-29 13:32
I see this too, even in a new project with no .editorconfig and settings to always prefer 'var'. Repro:
```c#
class C
{
    void M()
    {
        C c = new C();
    }
}
```

I see two code fixes that do the exact same thing:
![image](https://user-images.githubusercontent.com/11444821/47652864-67013380-db87-11e8-9c2c-3b2693ebce51.png)
![image](https://user-images.githubusercontent.com/11444821/47652869-6a94ba80-db87-11e8-9c34-516354c53e4e.png)


In my opinion "Simplify name" should *not* apply var preferences, as @CyrusNajmabadi suggested.

**Closed** 2019-12-30 17:51 UTC
Labels: Area-IDE, Concept-Diagnostic Clarity, Need Design Review, Regression, Resolution-Won't Fix

**Comment by CyrusNajmabadi** [comment] 2019-12-30 19:52
@sharwell we probably need to keep ths open (or break out a new bug).  Specifically, there are two bugs here:

1. "has started enforcing `var`"
2 "& `this.` usage"

I fixed the former.  But the latter is likely still an issue.

**Comment by CyrusNajmabadi** [comment] 2019-12-30 19:56
Nevermind.  Validated that this isn't an issue.
