### ISSUE TITLE
Rename variable refactoring broken in Visual Studio 2019 version 16.5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42703] opened 2020-03-23 19:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/955848/rename-variable-refactoring-broken-in-visual-studi.html)._

---
[regression] [worked-in:16.4.6]

Symptom
===
After upgrading to version 16.5, I went to simply rename a variable. As usual, I just directly changed the name, then used the [Ctrl]+[.] shortcut to bring up the "Rename 'originalName' to 'newName'" context dialog option. But this time, the option wasn't there. It didn't even work if I tried the other shortcut ([Ctrl]+[R, R]). Instead, the default option was to "Encapsulate field" (in that particular case).

Workaround/Solution
===
In the project settings, go to the "Code Analyzers" tab. Check the "Run on live analysis" box. "Rename refactoring" will start working again.  I had turned that off because it was making my CPU fan run constantly and I was tired of the noise and CPU usage.

Steps to Reproduce
===

1. In Visual Studio 2019 version 16.5, create a new Asp.Net Core Web Application ( like the MS tutorial here [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#create-a-web-project) )
1. Open up the WeatherForecast.cs file. 
1. Change the Date property's name to something else, use [Ctrl]+[.] and notice that there's an option to "Rename" the variable.
1. Get into the project's properties page, change to the "Code Analysis" tab, and uncheck the "Run on live analysis" box.
1. Return to the WeatherForecast.cs file and re-attempt to change that "Date" property to something else. You will no longer have the option to "Rename". Instead, the default option became "Replace 'Date' with methods".

---
#### Visual Studio Feedback System on 3/20/2020, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/23/2020, 11:27 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment] 2020-03-24 06:47
Fixed with https://github.com/dotnet/roslyn/pull/42246.  Rename is no longer an analyzer.

**Comment by CyrusNajmabadi** [comment] 2020-03-24 06:48
@ryzngard This should be fixed now.  Do you want to confirm on latest builds?

**Closed by CyrusNajmabadi** 2020-03-24 06:47 UTC
Labels: Area-IDE, Bug

**Comment by ryzngard** [comment] 2020-03-24 15:54
@CyrusNajmabadi  I'll double check on latest builds and reopen as needed

**Comment by pvpxan** [comment] 2020-05-22 13:23
Issue still seems to be present in 16.6.0.

**Comment by ryzngard** [comment] 2020-05-22 18:37
@pvpxan I wasn't able to reproduce the issue using the steps described in the bug. Do you have more information about steps used or configuration?

**Comment by pvpxan** [comment] 2020-05-22 20:33
@ryzngard What do you need from me? Here is my process that is now broken:
Lets say I have a variable `int testRename`. Normally if I want to rename this and all references to this, I would just hit `Ctrl + .` and chose Rename testRename to <new name> and it work all work. The option to Rename is not missing since updating to 16.6.0 as I had skipped over 16.5.0.

**Comment by CyrusNajmabadi** [comment] 2020-05-22 21:07
@pvpxan can you provide a repro solutoin where we can try this out?

**Comment by pvpxan** [comment] 2020-05-26 13:50
> @pvpxan can you provide a repro solutoin where we can try this out?

I doubt that would help as this happens to all my projects and any new project I create.

**Comment by CyrusNajmabadi** [comment] 2020-05-26 19:15
>  as this happens to all my projects and any new project I create.

Can you supply tht new project?  sounds like it should be easy to repro if we have that.  Thanks!

**Comment by NekoKoneko** [comment] 2020-05-27 08:46
Steps to reproduce:
1. Create a new Console App project (.NET Framework or .NET Core)
2. Add the following line to the Main method:
```C#
var i = 0;
```
3. Change variable name to ```j``` via keyboard.
4. Hover over the ```j``` variable and press the light bulb. The Rename command is missing.
<details>

![1](https://user-images.githubusercontent.com/1853737/82996997-76b85680-a00e-11ea-95b1-3178599f5f9e.png)

</details>
5. Now press Ctrl+. The rename command is present.
<details>

![2](https://user-images.githubusercontent.com/1853737/82997510-2261a680-a00f-11ea-986b-42c0061a28fe.png)
</details>

Checked on Visual Studio Community 2019 16.6.0.

**Comment by pvpxan** [comment] 2020-05-27 15:27
After some more testing, it seems the issue is related to method names that violate rule IDE1006. This is not affecting variables inside of methods for me. Also I am getting a constant error when mousing over options from below.

![image](https://user-images.githubusercontent.com/26392713/83040044-d4e43a00-a00c-11ea-80da-2df168ba32ae.png)

If I mouse over `Configure IDE Severity` FIRST, I get an error and all the options except `Suppress IDE1006` vanish until I restart VS2019. I am sorry I cannot share this project for security reasons but this sadly does not happen to other projects.

**ERROR:** [ActivityLog.zip](https://github.com/dotnet/roslyn/files/4689656/ActivityLog.zip)

Moving on with more details.,,

Since it seems things are tied to the IDE1006, I went into the VS2019 options and tried to remove the following:

![image](https://user-images.githubusercontent.com/26392713/83033127-b5e1aa00-a004-11ea-88aa-95de286e513f.png)

After doing this, when I mouse over something after changing the name, I no longer get the option to `Show Potential Fixes`. I now have to manually hit `Ctrl .` to show the options for which the Rename option is now present.

It would really be nice if you would just find a way to make it work like it use to. I could probably deal with having to hit `Ctrl .` now, but it is an extra step that really should not need to be taken.

**Comment by mavasani** [comment] 2020-05-27 17:04
@NekoKoneko @pvpxan Can you check if the refactoring is available for the light bulb that shows up in the margin?

There is also a feedback ticket https://github.com/dotnet/roslyn/issues/44594 reporting the same issue. We need to update fix the lightbulb within the text editor to show applicable refactorings.

**Comment by NekoKoneko** [comment] 2020-05-27 17:11
Yes, it is available in the margin's light bulb.
<details>

![3](https://user-images.githubusercontent.com/1853737/83051111-341a6c80-a056-11ea-9b9e-c3822b3050d5.png)

</details>
