### ISSUE TITLE
IsNullOrEmpty isn't treated as a null reference check

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/roslyn#37995] opened 2019-08-14 22:24 UTC
The preview 8 compiler is unable to correctly interpret `string.IsNullOrEmpty` method call and produces a warning `warning CS8602: Dereference of a possibly null reference.`, but it must not. The same thing happens with `IsNullOrWhiteSpace`.

```csharp
string? nullableString = null;
int y = string.IsNullOrEmpty(nullableString) ? 24 : nullableString.Length;
int z = string.IsNullOrWhiteSpace(nullableString) ? 24 : nullableString.Length;
```

The problem can be worked around by using `value?.Length > 0` instead of the method.

Previously was discussed in #37328 and marked as fixed.

**Comment by RikkiGibson** [comment] 2019-08-14 23:49
I'm not able to reproduce this using .NET Core 3 Preview 8 and compiler version 3.3.0-beta3-19406-05.

Could you please share the output of `dotnet --version` and also what message you see when adding `#error version` to a source file and running a build?

**Comment by JamesNK** [comment] 2019-08-19 05:13
I also get this.

![image](https://user-images.githubusercontent.com/303201/63240620-94e56f00-c2a4-11e9-8bd1-54a41672eabf.png)

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-013927
 Commit:    e1f793b16d
```

**Comment by YohDeadfall** [comment] 2019-08-19 09:13
I'm using .NET 3.0.100-preview8-013656. The compiler version is:
```
Compiler version: '3.3.0-beta2-19381-14 (ef3a7a38)'. Language version: 8.0.
```

The problem doesn't occur on `netstandard2.1` and `netcoreapp3.0`, so it looks like it affects all TFM below these. Another bug I found is that running `dotnet build` twice fixes compiler errors.

**Comment by jmarolf** [comment] 2019-08-19 13:20
@YohDeadfall 	This is happening because you are using a target (.NET Standard 2.0) that does not have any nullable annotations in the framework.

**Comment by YohDeadfall** [comment] 2019-08-19 15:55
Sure, but how should I compile code that targets multiple frameworks? Having separate code bases isn't an option.

**Comment by alrz** [comment] 2019-08-19 17:25
```cs
#if NETSTANDARD20
#nullable enable
#endif
```
? (probably you need to add those target-specific symbols yourself)

**Comment by JamesNK** [comment] 2019-08-19 21:38
Why did this use to work? This only became a problem in preview 8.

I'm creating a package with a `netstandard2.0` target (among others). What is the solution here?

I could write my own internal implementations of `string.IsNullOrEmpty` and `Debug.Assert`, and add attributes to them. That seems like kicking the problem onto end developers.

**Comment by jmarolf** [comment] 2019-08-20 04:15
>Why did this use to work? 

Curious to know the repro steps for this.  As far as I am aware this was never supposed to work.

**Comment by JamesNK** [comment] 2019-08-20 05:10
https://github.com/jamesnk/newtonsoft.json

Builds without warnings/errors using `3.3.0-beta1-final`. Update to `3.3.0-beta2-final` and the nullable warnings that were suppressed by `string.IsNullOrEmpty` and `Debug.Assert` show up.

`string.IsNullOrEmpty` and `Debug.Assert` have always worked for me (since the beginning of the year) on all targets.

**Comment by YohDeadfall** [comment] 2019-08-20 06:51
The same for Npgsql, but we switched from preview 7 to preview 8. No problems before that.

https://github.com/npgsql/npgsql/pull/2551

**Comment by jmarolf** [comment] 2019-08-20 16:18
hmm @RikkiGibson 	was there a nullable bug in beta1 that caused nullable warnings to not show?

**Comment by RikkiGibson** [comment] 2019-08-20 16:23
Possibly preview7 contained a compiler that predated this PR merge: https://github.com/dotnet/roslyn/pull/34916

**Comment by natemcmaster** [comment] 2019-09-04 04:32
I ran into this too. What is the guidance for library authors that multi-target and want to take advantage of nullability?

**Comment by JeremyCaney** [comment] 2019-09-06 20:26
Like @natemcmaster, I am curious what the guidance here is. Is the long-term plan to support nullable annotations in e.g. .NET Standard 3.0+, but not in prior versions of .NET Standard? If so, that makes sense to me. Given that, however, I assume the guidance is to only use nullable annotation contexts in projects target (ASP).NET {Standard|Core} 3+ (and, thus, .NET Framework 5+)?

**Comment by cartermp** [comment] 2019-09-06 21:32
There's no current plan to have nullable annotations outside of .NET Core 3.0+. That is subject to change based on feedback, though.

**Comment by agocke** [comment] 2019-09-06 21:33
As to why this worked previously, for previews there were a few APIs that were special-cased in the compiler. Those special cases have been removed and we now rely on annotations, which are present in netcoreapp3.0 and netstandard2.1, but not net4x or netstandard2.0

**Comment by RikkiGibson** [comment] 2019-09-06 22:00
If you want to multi-target and take advantage of nullability analysis, you may wish to enable nullable warnings only in the target frameworks which have nullable annotations for the core libraries.

Something like:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netcoreapp3.0;netstandard2.0</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework) == 'netcoreapp3.0'">
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

**Comment by JamesNK** [comment] 2019-09-08 08:37
That doesn't work for me. Newtonsoft.Json doesn't have a netcoreapp3.0/netstandard2.0 target.

**Comment by agocke** [comment] 2019-09-09 18:17
@JamesNK You would have to add one if you want the appropriate analysis from those methods.

**Comment by JamesNK** [comment] 2019-09-15 09:16
I don't want to add one just for this.

I've added my own wrapping methods: https://github.com/JamesNK/Newtonsoft.Json/pull/2163. It's not pretty but it works.

**Comment by jcouv** [comment] 2019-12-11 01:45
I think the issue was resolved. The problem is that an older TFM was targeted, which did not include the nullable annotations. 
I'll go ahead and close this. Please re-open if my understanding is incorrect.

**Closed by jcouv** 2019-12-11 01:45 UTC
Labels: Area-Compilers, Discussion, New Language Feature - Nullable Reference Types

**Comment by trampster** [comment] 2021-07-02 05:28
We have this problem using a Xamarin.Android project. I guess mono is missing the annotations.
