### ISSUE TITLE
Incorrect editor behavior during Rename Refactor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39435] opened 2019-10-21 23:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/784737/incorrect-editor-behavior-during-rename-refactor.html)._

---
<ol><li>In a C# project, initiate a rename refactor on an identifier having more than one character.</li><li>Press Shift+Left Arrow to select one or more characters, but not all of them.</li><li>Type some characters.</li></ol><p>RESULT: The selected characters are deleted, but the typed characters appear at the beginning of the identifier.</p><p>EXPECT: The typed characters to overwrite the selected characters.</p>

---
#### Visual Studio Feedback System on 10/20/2019, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:11 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment] 2020-05-16 23:37
I'm going to close this as by design, but I honestly see why there's confusion about this. 

When we start a rename session, we highlight the whole identifier. That highlight can be hard to spot the difference with the highlight that happens for all references to the identifier. I'll use dark theme because I think it's more of a culprit than light theme for this issue. 

![image](https://user-images.githubusercontent.com/475144/82132299-254cd380-9793-11ea-8cb8-2f8bf1925d1f.png)

The second highlight in the image is the place I'm renaming. The other is showing places that will be changed. 

Here's another image if I hit shift+left arrow twice 

![image](https://user-images.githubusercontent.com/475144/82132309-3bf32a80-9793-11ea-8a9f-f66bc24cf20c.png)

You can see the green highlight background is starting to show, and the blue is going left. The blue highlight represents cursor selection, and the green represents reference highlight. It behaves the same as if you highlighted the whole word and used shift+arrow keys to change the selection. 

One workaround for this is to hit the right arrow first, which puts the cursor at the end of a selection. Then use shift+left arrow to change the selection. That will get the desired behavior.

**Closed by ryzngard** 2020-05-16 23:37 UTC
Labels: Area-IDE, Bug, Developer Community
