### ISSUE TITLE
IDE crashes when renaming a local (SymbolKey.NonDeclarationSymbolKey'1.EnumerateSymbols)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#11155] opened 2016-05-06 23:31 UTC
VS crashed a few times and I captured some crash dumps. The callstack points to `SymbolKey.NonDeclarationSymbolKey'1.EnumerateSymbols`. I managed to catch it in a debugger and it is the `compilation` parameter that is null.

![null-ref](https://cloud.githubusercontent.com/assets/12466233/15088371/86cc7f80-13a7-11e6-83c1-5f87ca236536.png)

```
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey<Microsoft.CodeAnalysis.ILocalSymbol>.EnumerateSymbols(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.ISymbol containingSymbol, string name, System.Threading.CancellationToken cancellationToken) Line 75           C#
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey<Microsoft.CodeAnalysis.ILocalSymbol>.NonDeclarationSymbolKey(Microsoft.CodeAnalysis.ILocalSymbol symbol, Microsoft.CodeAnalysis.SymbolKey.Visitor visitor) Line 33             C#
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(Microsoft.CodeAnalysis.ILocalSymbol localSymbol) Line 59       C#
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept<System.__Canon>(Microsoft.CodeAnalysis.SymbolVisitor<System.__Canon> visitor)  Unknown
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.SymbolKey.Visitor visitor) Line 121           C#
> Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionWorkerAsync(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Solution solution, System.Threading.CancellationToken cancellationToken) Line 149                C#
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionAsync(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Solution solution, System.Threading.CancellationToken cancellationToken) Line 87                C#
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.DetermineIfRenamableSymbolAsync(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxToken token)          Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TriggerIdentifierKind>.Start<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22>(ref Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22 stateMachine)  Unknown
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.DetermineIfRenamableSymbolAsync(Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxToken token)          Unknown
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.DetermineIfRenamableIdentifierAsync(Microsoft.VisualStudio.Text.SnapshotSpan snapshotSpan, bool initialCheck)               Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TriggerIdentifierKind>.Start<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20>(ref Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20 stateMachine)  Unknown
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.DetermineIfRenamableIdentifierAsync(Microsoft.VisualStudio.Text.SnapshotSpan snapshotSpan, bool initialCheck)               Unknown
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.CheckNewIdentifier.AnonymousMethod__0(System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TriggerIdentifierKind> t)             Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.(ref Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<>c__DisplayClass17_0.<<CheckNewIdentifier>b__0>d stateMachine)  Unknown
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.CheckNewIdentifier.AnonymousMethod__0(System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TriggerIdentifierKind> t)             Unknown
Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWithFromAsync.AnonymousMethod__0(System.Threading.Tasks.Task antecedent) Line 253      C#
mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task<bool>>.InnerInvoke()                Unknown
               mscorlib.dll!System.Threading.Tasks.Task.Execute()         Unknown
               mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Unknown
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)           Unknown
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Unknown
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)               Unknown
               mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Unknown
               mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()                Unknown
               mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()             Unknown
               mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Unknown

```

The repro itself is to select `underlyingType` (squiggled in red below) and type `x`.
This is using VS2015 update 2.

![image](https://cloud.githubusercontent.com/assets/12466233/15088439/c7ff2f24-13a8-11e6-9b9b-af228c667122.png)

**Comment by jcouv** [comment] 2016-05-07 01:32
@jasonmalinowski I've been debugging this, but it looks like you may have already fixed it (commit [4c49bf2e](https://github.com/dotnet/roslyn/commit/4c49bf2e42b66c02db9fec6cdffdeab227a211f6#diff-535645ac79009687d395c1e45c94bbc9), 1/22/2016 10:17:27 AM).

Can you confirm this can be resolved "no repro" at this point?

**Comment by jmarolf** [comment] 2016-05-07 05:11
looks like dupe of https://github.com/dotnet/roslyn/issues/11092

**Comment by mavasani** [comment] 2016-05-09 14:13
@jasonmalinowski @jmarolf I have installdogfood the latest bits from today morning and still hitting this very often - atleast 10 times a day. Can we please make some defensive fix asap - this is basically blocking me from dogfooding latest Roslyn bits (diagnostics v2 engine that we want to ship in U3)

**Comment by jasonmalinowski** [comment] 2016-05-09 16:56
This is most definitely still reproducing. This was clearly regressed in recent days by...something.

**Comment by mavasani** [comment] 2016-05-09 16:59
I have a consistent repro for this: https://github.com/dotnet/roslyn/issues/11092#issuecomment-217880309

**Comment by DustinCampbell** [comment] 2016-05-10 16:22
Passing to @jmarolf -- this looks exactly like what he's already looking at.

**Comment by jmarolf** [comment] 2016-05-14 00:11
Fixed with https://github.com/dotnet/roslyn/pull/11238

**Closed by jmarolf** 2016-05-14 00:11 UTC
Labels: Area-IDE, Bug, Tenet-Reliability
