### ISSUE TITLE
Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#47726] opened 2020-09-15 21:18 UTC
Encountered this in a debug build of master @tmat I assume this means we are reading or writing the wrong format for OOP?

```
Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o) in C:\source\dotnet\roslyn\src\Compilers\Core\Portable\InternalUtilities\ExceptionUtilities.cs:line 22
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind kind) in C:\source\dotnet\roslyn\src\Compilers\Core\Portable\Serialization\ObjectReader.cs:line 364
   at Roslyn.Utilities.ObjectReader.ReadStringValue() in C:\source\dotnet\roslyn\src\Compilers\Core\Portable\Serialization\ObjectReader.cs:line 343
   at Roslyn.Utilities.ObjectReader.ReadString() in C:\source\dotnet\roslyn\src\Compilers\Core\Portable\Serialization\ObjectReader.cs:line 130
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.ReadDiagnosticAnalysisResults(ObjectReader reader, IDictionary`2 analyzerMap, DocumentAnalysisScope documentAnalysisScope, Project project, VersionStamp version, CancellationToken cancellationToken) in C:\source\dotnet\roslyn\src\Features\Core\Portable\Diagnostics\DiagnosticResultSerializer.cs:line 140
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.<ReadCompilerAnalysisResultAsync>d__12.MoveNext() in C:\source\dotnet\roslyn\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs:line 221
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.ReadCompilerAnalysisResultAsync(Stream stream, Dictionary`2 analyzerMap, DocumentAnalysisScope documentAnalysisScope, Project project, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.<>c__DisplayClass11_0.<AnalyzeOutOfProcAsync>b__2(Stream stream, CancellationToken cancellationToken) in C:\source\dotnet\roslyn\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs:line 198
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass11_0`1.<<InvokeStreamingServiceAsync>b__1>d.MoveNext() in C:\source\dotnet\roslyn\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 144
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass11_0`1.<InvokeStreamingServiceAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by CyrusNajmabadi** [comment] 2020-09-16 17:20
Dupe of https://github.com/dotnet/roslyn/issues/47683.  @mavasani high pri to fix.

**Closed by CyrusNajmabadi** 2020-09-16 17:20 UTC
Labels: Area-IDE, Bug, Concept-OOP

**Comment by mavasani** [comment] 2020-09-17 14:53
Done, please sync to latest master sources.
