### ISSUE TITLE
C# file with /*/ crashes IDE

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#16186] opened 2017-01-02 11:44 UTC
**Version Used**: 
VS2015 Update 3 with RC Insider VSIX

**Steps to Reproduce**:
1. New a C# console project
1. Empty the Program.cs
1. Type `/*/`
1. Wait for a few seconds

**Expected Behavior**:
No crash

**Actual Behavior**:
Crash

**Comment by TonyValenti** [comment] 2017-01-02 12:37
I can confirm it crashes in Update3 without the RC Insider VSIX

**Comment by gafter** [comment] 2017-01-02 18:48
Assigning to compiler team for initial investigation

**Comment by gafter** [comment] 2017-01-02 19:58
Here is a call stack on failure:

```none
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractBlockStructureProvider.ProvideBlockStructureAsync(Microsoft.CodeAnalysis.Structure.BlockStructureContext context)	Unknown
 	[Native to Managed Transition]	
 	mscorlib.dll!string.Substring(int startIndex, int length)	Unknown
 	mscorlib.dll!string.Substring(int startIndex)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CSharpStructureHelpers.CreateCommentBannerTextWithPrefix(string text, string prefix)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CSharpStructureHelpers.GetCommentBannerText(Microsoft.CodeAnalysis.SyntaxTrivia comment)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CSharpStructureHelpers.CreateCommentRegion(Microsoft.CodeAnalysis.SyntaxTrivia startComment, Microsoft.CodeAnalysis.SyntaxTrivia endComment)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CSharpStructureHelpers.CollectCommentRegions(Microsoft.CodeAnalysis.SyntaxTriviaList triviaList, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CSharpStructureHelpers.CollectCommentRegions(Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Structure.CompilationUnitStructureProvider.CollectBlockSpans(Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax compilationUnit, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractSyntaxNodeStructureProvider<Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax>.CollectBlockSpans(Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractSyntaxNodeStructureProvider<Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax>.CollectBlockSpans(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.BlockSpanCollector.GetBlockSpans(Microsoft.CodeAnalysis.SyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.BlockSpanCollector.Collect(Microsoft.CodeAnalysis.SyntaxNode root)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.BlockSpanCollector.CollectBlockSpans(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxNode syntaxRoot, System.Collections.Immutable.ImmutableDictionary<System.Type, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.AbstractSyntaxStructureProvider>> nodeOutlinerMap, System.Collections.Immutable.ImmutableDictionary<int, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.AbstractSyntaxStructureProvider>> triviaOutlinerMap, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Structure.BlockSpan>.Builder spans, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractBlockStructureProvider.ProvideBlockStructureWorker(Microsoft.CodeAnalysis.Structure.BlockStructureContext context, Microsoft.CodeAnalysis.SyntaxNode syntaxRoot)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractBlockStructureProvider.ProvideBlockStructureAsync(Microsoft.CodeAnalysis.Structure.BlockStructureContext context)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.AbstractBlockStructureProvider.ProvideBlockStructureAsync(Microsoft.CodeAnalysis.Structure.BlockStructureContext context)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.BlockStructureServiceWithProviders.GetBlockStructureAsync(Microsoft.CodeAnalysis.Document document, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Structure.BlockStructureServiceWithProviders.GetBlockStructureAsync(Microsoft.CodeAnalysis.Document document, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag> context, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan documentSnapshotSpan, int? caretPosition)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag> context, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan documentSnapshotSpan, int? caretPosition)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag> context)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag> context)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.TagSource.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag> context)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.TagSource.RecomputeTagsAsync(object oldState, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>> oldTagTrees, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.TagSource.RecomputeTagsAsync(object oldState, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>> oldTagTrees, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IOutliningRegionTag>.TagSource.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue.EnqueueBackgroundTask.AnonymousMethod__0(System.Threading.Tasks.Task _)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

**Comment by CyrusNajmabadi** [comment] 2017-01-02 19:59
Looks like this is in outlining.  You can assign to me if you want.

**Closed** 2017-01-04 06:22 UTC
Labels: Area-IDE, Bug
