### ISSUE TITLE
32-bit Integration Tests failing to upload servicehub logs

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50521] opened 2021-01-15 12:38 UTC
```
Extra run diagnostics for logging, did not impact run results
Test execution time: 00:44:07.7645168
All tests passed
Copying ServiceHub logs to F:\workspace\_work\1\s\artifacts\log\Debug
##[error](NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed
Cannot find path 'F:\workspace\_work\1\s\artifacts\tmp\Debug\servicehub\logs' because it does not exist.
System.Management.Automation.ItemNotFoundException: Cannot find path 'F:\workspace\_work\1\s\artifacts\tmp\Debug\servicehub\logs' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.CopyItem(String[] paths, String copyPath, Boolean recurse, CopyContainers copyContainers, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.CopyItemCommand.ProcessRecord()
at TestUsingRunTests, F:\workspace\_work\1\s\eng\build.ps1: line 409
at <ScriptBlock>, F:\workspace\_work\1\s\eng\build.ps1: line 628
at <ScriptBlock>, F:\workspace\_work\_temp\c3e5413e-c186-4c35-bdfc-fb5b7af30a3e.ps1: line 3
at <ScriptBlock>, <No file>: line 1
Killing running build processes...
Killing running build processes...
##[error]PowerShell exited with code '1'.
```

```
##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: F:\workspace\_work\1\s\artifacts\bin\Microsoft.VisualStudio.LanguageServices.IntegrationTests\Debug\net472\xUnitResults
```

See <https://dev.azure.com/dnceng/public/_build/results?buildId=952611&view=results>

**Comment by Youssef1313** [comment] 2021-01-18 17:00
His this again in https://dev.azure.com/dnceng/public/_build/results?buildId=955459&view=results

**Comment by Youssef1313** [comment] 2021-01-21 19:01
Another hit of this: https://github.com/dotnet/roslyn/pull/50675/

**Comment by RikkiGibson** [comment] 2021-01-21 20:07
Is this a race condition of some kind?

**Comment by Youssef1313** [comment] 2021-01-21 20:52
@RikkiGibson Probably. It might be the copy is being executed at around the same time when the logs are written, causing the copy to fail. But I don't know when/how these logs are written to disk.

**Comment by sharwell** [comment] 2021-01-28 01:24
Trying to figure this out...

**Comment by 333fred** [comment] 2021-01-28 01:28
Hit this twice more in the past hour.

https://dev.azure.com/dnceng/public/_build/results?buildId=968638&view=logs&j=9e93af80-e8ae-58aa-0f47-c3fff1766aa4&t=03df6b5c-2902-5a61-fef1-7cb300e3f14b&l=800
https://dev.azure.com/dnceng/public/_build/results?buildId=968669&view=logs&j=9e93af80-e8ae-58aa-0f47-c3fff1766aa4&t=03df6b5c-2902-5a61-fef1-7cb300e3f14b&l=799

**Comment by 333fred** [comment] 2021-01-28 01:28
Marking this as urgent because it is reproducing _constantly_.

**Closed** 2021-01-28 17:46 UTC
Labels: Area-Infrastructure, Bug, Contributor Pain, Urgency-Now
