### ISSUE TITLE
Switching Build and Build+Intellisense in Errors shows outdated errors in the list

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#30372] opened 2018-10-08 15:18 UTC
_From @abpiskunov on September 19, 2018 21:40_

Repro: 

1. Set Build+Intellisense in Error list filter.
2. Have a project with some build errors and some intellisense only errors
3. Build and see all errors in the ErrorList
4. Fix some build errors and wait for them to disappear from Error List
5. Then switch to Build Only in the filter

Actual result:

Old error count and errors are back to error list even though they were fixed already, clicking on them open fixed files in old positions

Expected:

Only remaining errors to be in the list.

![image](https://user-images.githubusercontent.com/1592091/45783189-f24ae900-bc19-11e8-834c-2c07ebc28778.png)

![image](https://user-images.githubusercontent.com/1592091/45783198-f840ca00-bc19-11e8-8082-3c5bf5091e4f.png)

_Copied from original issue: dotnet/project-system#4041_

**Comment by Pilchie** [comment] 2018-10-08 15:18
_From @davkean on September 19, 2018 23:12_

@heejaechang 

That's by design - `Build Only` shows the builds errors from the last build, regardless if you've fixed them (Error List behavior since v1). If you want live reporting, that's the `Build + IntelliSense` category.

**Comment by Pilchie** [comment] 2018-10-08 15:18
Ping @heejaechang - any more thoughts here?

**Comment by Pilchie** [comment] 2018-10-08 15:19
Moved to Roslyn, since that's what populates the error list for "IntelliSense"

**Comment by sharwell** [comment] 2018-10-09 16:28
Tentatively marking this **By Design**. Will update with details and results following a design review.

**Comment by CyrusNajmabadi** [comment] 2024-10-19 21:21
Closing out as tehse experiences were all rewritten for lsp.

**Closed by CyrusNajmabadi** 2024-10-19 21:21 UTC
Labels: Bug, Area-IDE, Resolution-External, Need Design Review
