### ISSUE TITLE
CS8019 violation in Resources.Designer.cs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37349] opened 2019-07-18 23:05 UTC
Visual Studio 2019 Enterprise (16.1.6)

I have a `Resources.resx` file in a .NET FX 4.6 C# project. IntelliSense reports &quot;Unnecessary using directive. (CS8019)&quot; in the the auto-generated `Resources.Designer.cs`, complaining `using System;` is unnecessary.

Auto generated file should not have compile/CA warnings. Please either fix the code generation tool or the compiler.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/639401/cs8019-violation-in-resourcesdesignercs.html
VSTS ticketId: 944547_
_These are the original issue comments:_

Visual Studio Feedback System on 7/10/2019, 00:44 AM (8 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Drew Noakes [MSFT] on 7/17/2019, 02:31 AM (37 hours ago): <markdown><p>Thanks for the feedback. Can you please confirm whether you’re seeing the CS8019 diagnostic in the build output (when you compile) or only in the IDE when the file is opened in the editor?</p>
</markdown>
James Liang [MSFT] on 7/17/2019, 08:58 PM (19 hours ago): <p>The CS8019 violations are shown in IDE Error List (with IntelliSense on) only, not yet observed in build output.</p><p>By the way, I have "Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.3" installed for the projects, configed with customzied ruleset file, and have .editconfig file above.</p>

Visual Studio Feedback System on 7/17/2019, 09:10 PM (18 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment] 2019-07-19 00:17
Duplicate of #22579

**Closed by sharwell** 2019-07-19 00:17 UTC
Labels: Area-IDE, Bug
