### ISSUE TITLE
Unloading a project freezes Visual Studio forever

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/roslyn#17085] opened 2017-02-10 13:57 UTC
VS 2017 RC4.

1. Load a solution (https://github.com/Microsoft/visualfsharp/blob/master/VisualFSharp.sln in my case)
2. Unload a project (https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Compiler/FSharp.Compiler.fsproj in my case)
3. VS hangs forever, no CPU load

![image](https://cloud.githubusercontent.com/assets/873919/22828802/5de18eea-efb0-11e6-80e7-3146ffeda402.png)

Dump is here https://drive.google.com/open?id=0B8HLQUKik9VteUFrZ2NjMnRkSk0

**Comment by miloush** [comment] 2017-02-10 16:42
My guess would be this is a dupe of #14479 .

**Comment by vasily-kirichenko** [comment] 2017-02-10 17:11
@miloush no. That issue is fixed in RC4. This is a new one.

**Comment by miloush** [comment] 2017-02-10 17:24
@vasily-kirichenko I can reproduce this one reliably in couple of recent builds, including 26206. The problem is in the linked files, and I have been told that's a dupe of #14479 several weeks ago. Why do you think it's fixed in RC4?

**Comment by miloush** [comment] 2017-02-10 17:27
Also if you close the shared documents before unloading the project, it shouldn't repro, is that your experience too?

**Comment by vasily-kirichenko** [comment] 2017-02-10 17:29
@miloush yes, the projects I'm working on have lots of linked documents, almost all of docs are linked. Unfortunately, I cannot reproduce it on my home machine, either having the docs open or closed.

**Comment by vasily-kirichenko** [comment] 2017-02-10 17:30
> Why do you think it's fixed in RC4?

Because the solution I'm working on freezes VS on exit in 100% of times in RC3, no single freeze on RC4 so far.

**Comment by miloush** [comment] 2017-02-10 17:32
Interesting, my solution still freezes 100% of times on VS exit in RC4.

**Comment by Pilchie** [comment] 2017-02-10 19:01
@dpoeschl Can you investigate?

**Comment by dpoeschl** [comment] 2017-02-28 18:39
Fixed by https://github.com/dotnet/roslyn/pull/17372

**Closed by dpoeschl** 2017-02-28 18:39 UTC
Labels: Area-IDE, Bug

**Comment by sergeykorolevsky** [comment] 2018-02-15 10:00
I've faced this issue with last VS2017 version 15.5.6, OS - Win8.1

**Comment by Pilchie** [comment] 2018-05-02 14:10
Can those of you hitting this issue in 15.6 use VS's "report a problem" from a second instance of VS to record it while hung and report it? That should give us actionable memory dumps to investigate.

Go ahead and link the resulting developer community issues here too.

**Comment by levu74** [comment] 2018-06-14 10:09
Still face the issue if having nested solution folders.

**Comment by Dogrtt** [comment] 2019-09-26 19:59
Face the issue on 16.3.1 when I closed my UE4 project...

**Comment by JaydenMaalouf** [comment] 2019-10-05 12:46
@Dogrtt Exactly the same here. I followed the answer posted [here](https://developercommunity.visualstudio.com/content/problem/25310/unload-projects-hangs-on-close-solution.html) and it worked wonders. It does suck if I ever need the service though.

**Comment by mlop3s** [comment] 2020-10-16 11:34
I have the same issue since months, with all updates. I've created two dumps over ~ 2GB. On both days when it happened.

Microsoft Visual Studio Enterprise 2019
Version 16.7.5

Mainly it happens on my mixed native C++ C# solution with over 80 projects.
I can make it available if needed. Let me know.

Cheers

**Comment by CyrusNajmabadi** [comment] 2020-10-16 15:21
@mlop3s please open a new issue and include information about what build you have as well as links to the dumps. Ideally, of you can provide a link to the single
Solution as well that would be helpful.
